[msg MSG_000_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 2 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]If I put in my greatest effort, I will achieve the greatest outcome![n][uf 1 1][e]

[msg MSG_000_2_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 2 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]One needle, one soul! This is my subete—my everything![n][uf 1 1][e]

[msg MSG_001_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 0 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]Huh... That cheap material has been completely transformed![n][uf 1 1][e]

[msg MSG_001_3_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 3 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]I could never have done this on my own.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 112 3 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]Without you, I would probably be back home already.[n][uf 1 1][e]

[msg MSG_001_5_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 1 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]And thanks to all your help, the kimono is almost finished! I feel so blessed![n][uf 1 1][e]

[sel SEL_002_0_0 top]
[uf 0 5 65278][uf 2 1]Congrats![e]
[uf 0 5 65278][uf 2 1]Aren't you homesick?[e]
[uf 0 5 65278][uf 2 1]Don't forget, you owe me.[e]

[msg MSG_003_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 1 65535 65535 0 0][uf 3 1 1 0 0 7 0 0][uf 5 13 15 5 112]Many thanks—katajikenai! Your kind words help me forget my aches and pains![n][uf 1 1][e]

[msg MSG_004_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 3 65535 65535 0 0][uf 3 1 1 0 0 8 0 0][uf 5 13 15 15 112]My home country... With my aunt gone, there is nothing there for me now![n][uf 1 1][e]

[msg MSG_004_1_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 2 65535 65535 0 0][uf 3 1 1 0 0 9 0 0]I just want to hurry and put an end to this so that I may live and die in Nihon![n][uf 1 1][e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]Bebe's pretty fired up.[n][uf 1 1][e]

[msg MSG_006_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 1 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]I would love to repay you![n][uf 1 1][e]

[msg MSG_006_1_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 3 65535 65535 0 0][uf 3 1 1 0 0 11 0 0]If I could, I'd treat you to a feast of Japanese snacks! But sadly, my wallet is empty.[n][uf 1 1][e]

[msg MSG_007_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 0 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]There's something I need to tell you, [uf 4 2]-sama.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 112 0 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]I have gotten to know many people since coming to Nihon.[n][uf 1 1][e]

[msg MSG_007_2_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 1 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]But you have been the most subarashii person of them all.[n][uf 1 1][e]

[msg MSG_008_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 3 65535 65535 0 0][uf 3 1 1 0 0 15 0 0]If my aunt was still alive...[n][uf 1 1][e]

[msg MSG_008_1_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 0 65535 65535 0 0][uf 3 1 1 0 0 16 0 0]I would tell her about what a wonderful friend you have been to me.[n][uf 1 1][e]

[msg MND_009_0_0]
[uf 0 5 65278][uf 2 1]I can tell that Bebe really trusts me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like we're growing closer...[n][uf 1 1][e]

[msg MSG_010_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 1 65535 65535 0 0][uf 3 1 1 0 0 17 0 0]And nooow! We put the final touches on this kimono![n][uf 1 1][e]

[msg MSG_010_3_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 3 65535 65535 0 0][uf 3 1 1 0 0 18 0 0]Sure, I am so tired I may be hallucinating a little bit.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 112 2 65535 65535 0 0][uf 3 1 1 0 0 19 0 0][uf 4 23 0 1 2 25 25]But this is the last part... I can't give up now![n][uf 1 1][e]

[msg MSG_010_5_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 0 65535 65535 0 0][uf 3 1 1 0 0 20 0 0]Ready, set... go![n][uf 1 1][e]

[msg MND_011_0_0]
[uf 0 5 65278][uf 2 1]I spent the day helping Bebe,[n]then went back to the dorm.[n][uf 1 1][e]

