[msg MSG_000_0_0 [Voz de la asesora]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 1 0 0]¡Kazushi![n][uf 1 1][e]

[msg MSG_001_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 151 65535 0 0][uf 3 1 1 0 0 2 0 0]¿Q-qué pasa? ¿A qué viene esa cara de susto?[n][uf 1 1][e]

[msg MSG_002_0_0 [Asesor del equipo de atletismo]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 3 0 0]Pero ¡¿qué haces?![n][uf 1 1][e]

[msg MSG_003_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 151 65535 0 0][uf 3 1 1 0 0 4 0 0]P-pues entrenar.[n][uf 1 1][e]

[msg MSG_004_0_0 [Asesor del equipo de atletismo]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 5 0 0]Mira, ya has entrenado suficiente. Tira echando leches a la enfermería.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 6 0 0]¡Los demás seguid a lo vuestro![n][uf 1 1][e]

[msg MSG_005_0_0 [Miembro de segundo]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 7 0 0][uf 5 21 0 1]¿A la enfermería?[n][uf 1 1][e]

[msg MSG_006_0_0 [Miembro de tercero]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 8 0 0][uf 5 21 0 2]Kazushi, ¿ha pasado algo?[n][uf 1 1][e]

[msg MSG_007_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 151 65535 0 0][uf 3 1 0 0 0 9 0 0]...[n][uf 1 1][e]

[msg MSG_008_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 2 101 65535 0 0][uf 3 1 1 0 0 10 0 0]Lo sabía. Es que se le da de pena mentir. Se nota a la legua que está forzando la rodilla.[n][uf 1 1][e]

[msg MSG_008_3_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 101 65535 0 0][uf 3 1 1 0 0 11 0 0]Sé que tú también estás metida en esto, [uf 4 1]. Lo siento, pero tienes que venir conmigo.[n][uf 1 1][e]

[msg MND_009_0_0]
[uf 0 5 65278][uf 2 1]Me he dirigido a la enfermería con Yuko.[n][uf 1 1][e]

