[msg MSG_TARTAROS_BTL_YUKARI_ [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 65535 65535 0 0][uf 3 1 3 0 65535 1128 0 0]¡Si no te apartas, te apartaremos nosotros![n][uf 1 1][e]

[msg MSG_TARTAROS_BTL_YUKARI__2 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 65535 65535 0 0][uf 3 1 3 0 65535 1117 0 0]¿Lista? ¡En marcha![n][uf 1 1][e]

[msg MSG_TARTAROS_BTL_JUNPEI_ [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 3 0 65535 2119 0 0]¡Adelante, equipo! ¡No me quitéis ojo de encima![n][uf 1 1][e]

[msg MSG_TARTAROS_BTL_JUNPEI__2 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 2 65535 65535 0 0][uf 3 1 3 0 65535 2088 0 0]Parece más fuerte de lo que pensaba... ¡Pero a mí no hay quien me pare![n][uf 1 1][e]

[msg MSG_TARTAROS_BTL_SANADA_ [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 65535 65535 0 0][uf 3 1 3 0 65535 3116 0 0]¡Lo siento, pero tenemos que abrirnos paso![n][uf 1 1][e]

[msg MSG_TARTAROS_BTL_SANADA__2 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 9 65535 65535 0 0][uf 3 1 3 0 65535 3117 0 0]Va a ser divertido. ¡Vamos, en marcha![n][uf 1 1][e]

[msg MSG_TARTAROS_BTL_MITSURU [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 65535 65535 0 0][uf 3 1 3 0 65535 4007 0 0]¡Viene hacia aquí! ¡Preparaos![n][uf 1 1][e]

[msg MSG_TARTAROS_BTL_MITSURU_2 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 65535 65535 0 0][uf 3 1 3 0 65535 4143 0 0]¡A por ello![n][uf 1 1][e]

[msg MSG_TARTAROS_BTL_MITSURU_3 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 65535 65535 0 0][uf 3 1 3 0 65535 4085 0 0]¡Te lo dejo a ti![n][uf 1 1][e]

[msg MSG_TARTAR_BTL_PT_MITSUR [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 65535 65535 0 0][uf 3 1 3 0 65535 4117 0 0]¡Estad alerta! ¡Desconocemos los poderes del enemigo![n][uf 1 1][e]

[msg MSG_TARTAR_BTL_PT_MITSUR_2 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4140 0 0]¿Estás preparada? ¡Porque vamos a abrirnos paso a la fuerza![n][uf 1 1][e]

[msg MSG_TARTAROS_BTL_AEGIS_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6007 0 0]Aproximándose a la sombra enemiga. Eliminando objetivo.[n][uf 1 1][e]

[msg MSG_TARTAROS_BTL_AEGIS_1 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6007 0 0]Entrando en combate. Como se suele decir: "ven a buscarlo".[n][uf 1 1][e]

[msg MSG_TARTAROS_BTL_AEGIS_2 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 2 65535 65535 0 0][uf 3 1 3 0 65535 6005 0 0]Va a ser un combate complicado. ¡Tenemos que ser precavidos![n][uf 1 1][e]

[msg MSG_TARTAROS_BTL_AEGIS_3 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 2 65535 65535 0 0][uf 3 1 3 0 65535 6118 0 0]¡Pienso esforzarme al máximo! ¡Venga, a trabajar en equipo![n][uf 1 1][e]

[msg MSG_TARTAROS_BTL_KOROMAR [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 2 65535 65535 0 0][uf 3 1 3 0 65535 8002 0 0]Grrr... ¡Arf![n][uf 1 1][e]

[msg MSG_TARTAROS_BTL_KOROMAR_2 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 2 65535 65535 0 0][uf 3 1 3 0 65535 8002 0 0]¡Grrr...![n][uf 1 1][e]

[msg MSG_TARTAROS_BTL_AMADA_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 65535 65535 0 0][uf 3 1 3 0 65535 7119 0 0]¡Venga, adelante! ¡Te vas a enterar![n][uf 1 1][e]

[msg MSG_TARTAROS_BTL_AMADA_1 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 65535 65535 0 0][uf 3 1 3 0 65535 7118 0 0]¡Aquí viene! ¡Démosle su merecido![n][uf 1 1][e]

[msg MSG_TARTAROS_BTL_ARAGAKI [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 2 65535 65535 0 0][uf 3 1 3 0 65535 9109 0 0]¡Preparaos, que viene![n][uf 1 1][e]

[msg MSG_TARTAROS_BTL_ARAGAKI_2 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 2 65535 65535 0 0][uf 3 1 3 0 65535 9108 0 0]Si no podemos avanzar, tendremos que hacerles picadillo.[n][uf 1 1][e]

[msg MSG_TARTAROS_BTL_FUKA_1 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 3 0 65535 5128 0 0]¡Se acerca una sombra enemiga![n][uf 1 1][e]

[msg MSG_TARTAROS_BTL_FUKA_2 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 3 0 65535 5128 0 0]¡Contad conmigo! ¡Juntos, podremos con esto![n][uf 1 1][e]

[msg MSG_TARTAROS_BTL_FUKA_3 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 50 0 0][uf 3 1 3 0 65535 5128 0 0]¡Tú puedes! ¡Confío en ti![n][uf 1 1][e]

