[msg MSG_000_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 5 65535 0 0][uf 3 1 1 0 0 1 0 0]Ah, je sens qu'aujourd'hui va envoyer du lourd.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 5 65535 0 0][uf 3 1 1 0 0 2 0 0][uf 4 23 0 3 3 25 25]C'est quand même vraiment dommage que les troisième année et les autres filles viennent pas.[n][uf 1 1][e]

[msg MSG_001_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 5 65535 0 0][uf 3 1 1 0 0 3 0 0]Euh, si cela implique de fendre des pastèques, ce sera sans moi.[n][uf 1 1][e]

[msg MSG_002_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 5 65535 0 0][uf 3 1 1 0 0 4 0 0]Attends... T'es sérieux ?! J'ai encore rien dit ![n][uf 1 1][e]

[msg MSG_003_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 5 65535 0 0][uf 3 1 1 0 0 5 0 0]Il y a une pastèque et une batte de base-ball... Qu'est-ce que tu veux qu'on fasse d'autre avec ?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 5 65535 0 0][uf 3 1 1 0 0 6 0 0]C'est plus pour les gamins de toute façon, et puis il fait super chaud. Et je sais bien que t'essaies d'être sympa...[n][uf 1 1][e]

[sel SEL_004_0_0 top]
[uf 0 5 65278][uf 2 1]Tu devrais te joindre à nous.[e]
[uf 0 5 65278][uf 2 1]Allez, on s'ennuie.[e]

[msg MSG_005_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 5 65535 0 0][uf 3 1 1 0 0 7 0 0]Ouais, carrément ! Sans toi, ce serait juste [uf 4 2] et moi...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 5 65535 0 0][uf 3 1 1 0 0 8 0 0]Avoue que ce serait la lose quand même, non ?[n][uf 1 1][e]

[msg MSG_006_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 5 65535 0 0][uf 3 1 1 0 0 9 0 0]Vu comme ça... J'imagine que je n'ai pas trop le choix.[n][uf 1 1][e]

[msg MSG_007_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 9 5 65535 0 0][uf 3 1 1 0 0 10 0 0]Meuf, à t'entendre on croirait qu'on a rien de mieux à faire.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 5 65535 0 0][uf 3 1 1 0 0 11 0 0][uf 4 23 0 3 1 25 25]Bah, ce serait pas totalement faux, hein ? Allez, il est temps de s'éclater un peu ![n][uf 1 1][e]

[msg MSG_008_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 5 65535 0 0][uf 3 1 1 0 0 12 0 0]Vu comme ça... Peut-être juste un peu alors.[n][uf 1 1][e]

[msg MSG_009_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 1 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]Ouaf ! Ouaf ![n][uf 1 1][e]

[msg MSG_010_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 5 65535 0 0][uf 3 1 1 0 0 14 0 0]Je sais, Koromaru. T'inquiète, mon petit gars, on t'a pas oublié ![n][uf 1 1][e]

[msg MSG_011_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 5 65535 0 0][uf 3 1 1 0 0 15 0 0]Bon alors, qu'est-ce qu'on attend ? C'est aux plus jeunes de commencer ![n][uf 1 1][e]

[msg MSG_012_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 5 65535 0 0][uf 3 1 1 0 0 16 0 0]Voilà, ça c'est digne de l'été ! Je suis au taquet ![n][uf 1 1][e]

[msg MSG_013_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 5 65535 0 0][uf 3 1 1 0 0 17 0 0]Je me demande bien qui est vraiment le "gamin" ici... Héhé.[n][uf 1 1][e]

[msg MSG_014_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 5 65535 0 0][uf 3 1 1 0 0 18 0 0]Oh, ouais, où est le bandeau ? On peut pas fendre une pastèque avec juste une batte de base-ball.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 4 5 65535 0 0][uf 3 1 1 0 0 19 0 0][uf 4 23 0 8 4 25 25]D'ailleurs, en parlant de ça... cette batte a l'air plutôt usée, non ?[n][uf 1 1][e]

[msg MSG_015_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 5 65535 0 0][uf 3 1 1 0 0 20 0 0]Oh, ouah, t'as remarqué ? Ouais, cette batte et moi, on en a vécu des choses...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 5 65535 0 0][uf 3 1 1 0 0 21 0 0][uf 4 23 0 3 0 25 25]J'ai eu cette batte alors que j'étais tout gamin. Je t'en ai jamais parlé ?[n][uf 1 1][e]

[sel SEL_016_0_0 top]
[uf 0 5 65278][uf 2 1]C'est nouveau.[e]
[uf 0 5 65278][uf 2 1]Ça me dit quelque chose.[e]

[msg MSG_017_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 5 65535 0 0][uf 3 1 1 0 0 22 0 0]Ah, j'ai peut-être jamais eu l'occase de te dire que je jouais au base-ball, en fait.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 6 5 65535 0 0][uf 3 1 1 0 0 23 0 0][uf 4 23 0 3 6 25 25]Bref, ça remonte de toute façon.[n][uf 1 1][e]

[msg MSG_018_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 5 65535 0 0][uf 3 1 1 0 0 24 0 0]Ah ouais ? Bah, c'est pas un secret, hein.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 5 65535 0 0][uf 3 1 1 0 0 25 0 0]Je jouais au base-ball à l'époque. Mais bon, c'est vieux tout ça.[n][uf 1 1][e]

[msg MSG_019_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 5 65535 0 0][uf 3 1 1 0 0 26 0 0]On ne devrait peut-être pas frapper des pastèques avec dans ce cas ?[n][uf 1 1][e]

[msg MSG_020_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 6 5 65535 0 0][uf 3 1 1 0 0 27 0 0]Hmm ? Ah, bah...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 5 65535 0 0][uf 3 1 1 0 0 28 0 0][uf 4 23 0 3 0 25 25]T'inquiète, ça me dérange pas. Je pense pas que je vais m'en resservir de toute façon.[n][uf 1 1][e]

[msg MSG_021_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 3 65535 65535 0 0][uf 3 1 1 0 0 29 0 0]Kaï ![n][uf 1 1][e]

[msg MSG_022_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 5 65535 0 0][uf 3 1 1 0 0 30 0 0]Qu'est-ce qui va pas, mon petit gars ? T'as envie de pastèque ?[n][uf 1 1][e]

[msg MND_023_0_0]
[uf 0 5 65278][uf 2 1]Koromaru essaie de nous dire quelque chose.[n][uf 1 1][e]

[msg MSG_024_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 1 0 0 31 0 0]Ouaf ![n][uf 1 1][e]

[msg MSG_025_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 5 65535 0 0][uf 3 1 1 0 0 32 0 0]Hé, allez, Koromaru... On peut pas frapper la pastèque si tu restes dans nos pattes.[n][uf 1 1][e]

[msg MSG_026_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 5 65535 0 0][uf 3 1 1 0 0 33 0 0]Koromaru...[n][uf 1 1][e]

[msg MSG_026_5_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 5 65535 0 0][uf 3 1 1 0 0 34 0 0]Hé, pourquoi ne pas utiliser autre chose au lieu de cette batte ?[n][uf 1 1][e]

[sel SEL_027_0_0 top]
[uf 0 5 65278][uf 2 1]Bonne idée.[e]
[uf 0 5 65278][uf 2 1]Et qu'est-ce que tu veux utiliser ?[e]

[msg MSG_028_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 5 65535 0 0][uf 3 1 1 0 0 35 0 0]Tu vois ? Senpai pense la même chose ![n][uf 1 1][e]

[msg MSG_029_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 5 65535 0 0][uf 3 1 1 0 0 36 0 0]Et tu veux qu'on utilise quoi au juste ?[n][uf 1 1][e]

[msg MSG_030_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 4 5 65535 0 1][uf 3 1 1 0 0 37 0 0]Euh, n'importe quoi, je dirais ! Tant que ça reste intéressant ![n][uf 1 1][e]

[msg MSG_031_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 6 5 65535 0 1][uf 3 1 1 0 0 38 0 0]Intéressant ? C'est chelou comme requête... Oh, comme si Sanada défonçait une pastèque avec ses poings ?[n][uf 1 1][e]

[msg MSG_032_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 5 65535 0 0][uf 3 1 1 0 0 39 0 0]Quelqu'un m'a appelé ?[n][uf 1 1][e]

[msg MSG_033_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 4 5 65535 0 0][uf 3 1 1 0 0 40 0 0]Ouah, Sanada ![n][uf 1 1][e]

[msg MSG_034_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 5 65535 0 0][uf 3 1 1 0 0 41 0 0]J'ai entendu des voix venant du toit en rentrant, donc je suis venu jeter un œil. Vous allez éclater des pastèques, hein ?[n][uf 1 1][e]

[msg MSG_035_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 5 65535 0 0][uf 3 1 1 0 0 42 0 0]C-C'est ça ! On réfléchissait justement à ce qu'on pourrait utiliser pour les exploser ![n][uf 1 1][e]

[msg MSG_036_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 5 65535 0 0][uf 3 1 1 0 0 43 0 0]Vous n'allez pas utiliser cette batte ?[n][uf 1 1][e]

[sel SEL_037_0_0 top]
[uf 0 5 65278][uf 2 1]On veut utiliser autre chose.[e]
[uf 0 5 65278][uf 2 1]On veut que tu utilises tes poings.[e]

[msg MSG_038_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 5 65535 0 0][uf 3 1 1 0 0 44 0 0]Ouais ! On se disait que tu pourrais peut-être en casser une à main nue ![n][uf 1 1][e]

[msg MSG_039_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 5 65535 0 0][uf 3 1 1 0 0 45 0 0]Au vu de la taille, c'est tentant. T'es sûr de toi ?[n][uf 1 1][e]

[msg MSG_040_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 5 65535 0 0][uf 3 1 1 0 0 46 0 0]Mes poings ? Pour fracasser ça ?[n][uf 1 1][e]

[msg MSG_041_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 5 65535 0 0][uf 3 1 1 0 0 47 0 0]Oh ouais ! Honnêtement, j'adorerais voir ça ![n][uf 1 1][e]

[msg MSG_041_5_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 5 65535 0 0][uf 3 1 1 0 0 48 0 0]Ça ne te dérangerait pas, pas vrai, Junpei ?[n][uf 1 1][e]

[msg MSG_042_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 5 65535 0 0][uf 3 1 1 0 0 49 0 0]Hein ? Euh, ouais, pas de problème, si c'est ce qui te botte.[n][uf 1 1][e]

[msg MSG_043_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 5 65535 0 0][uf 3 1 1 0 0 50 0 0]Très bien. Je suppose que je vais devoir faire de mon mieux dans ce cas.[n][uf 1 1][e]

[msg MSG_044_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 5 65535 0 0][uf 3 1 1 0 0 51 0 0]Hé, vas-y mollo, hein, sinon y'aura plus rien à bouffer après.[n][uf 1 1][e]

[msg MSG_045_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 8 5 65535 0 0][uf 3 1 1 0 0 52 0 0]Aaah ![n][uf 1 1][e]

[msg MSG_046_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 5 65535 0 0][uf 3 1 1 0 0 53 0 0]Ouaaah ! Sanada, tu es vraiment incroyable ![n][uf 1 1][e]

[msg MSG_047_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 1 65535 65535 0 0][uf 3 1 1 0 0 54 0 0]Ouaf ! Ouaf ![n][uf 1 1][e]

[msg MSG_048_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 5 65535 0 0][uf 3 1 1 0 0 55 0 0]Bordel ! Et comment on est censés manger ça maintenant ?![n][uf 1 1][e]

[msg MSG_049_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 6 5 65535 0 0][uf 3 1 1 0 0 56 0 0]J'en reviens pas que ce truc soit encore mangeable après avoir explosé comme ça.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 6 5 65535 0 0][uf 3 1 1 0 0 57 0 0][uf 4 23 0 3 6 25 25]Bon, ça s'est pas passé comme je l'aurais imaginé, mais Amada a l'air de s'être amusé au moins.[n][uf 1 1][e]

[msg MSG_050_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 5 65535 0 0][uf 3 1 1 0 0 58 0 0]Aaah, j'ai vraiment été nul, hein ?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 5 65535 0 0][uf 3 1 1 0 0 59 0 0]Tu sais, avant qu'on fasse péter la pastèque...[n][uf 1 1][e]

[msg MSG_051_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 5 65535 0 0][uf 3 1 1 0 0 60 0 0]Je parle de cette histoire de batte. T'essayais juste d'être sympa.[n][uf 1 1][e]

[msg MSG_051_5_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 5 65535 0 0][uf 3 1 1 0 0 61 0 0]Je voulais pas donner l'impression que j'hésitais, mais j'ai pas pu m'en empêcher, hein ?[n][uf 1 1][e]

[msg MSG_052_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 6 5 65535 0 1][uf 3 1 1 0 0 62 0 0]J'étais censé être le mentor super cool, mais au lieu de ça... le gamin a eu pitié de moi.[n][uf 1 1][e]

[sel SEL_053_0_0 top]
[uf 0 5 65278][uf 2 1]Tu as fait de ton mieux.[e]
[uf 0 5 65278][uf 2 1]C'est un début.[e]
[uf 0 5 65278][uf 2 1]Tu as d'excellentes qualités.[e]

[msg MSG_054_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 6 5 65535 0 0][uf 3 1 1 0 0 63 0 0]Haha, t'en fais pas pour moi. Ça risque de me rendre encore plus triste.[n][uf 1 1][e]

[msg MSG_055_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 5 65535 0 0][uf 3 1 1 0 0 64 0 0]Je dis pas que c'est de ta faute, [uf 4 2].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 5 65535 0 0][uf 3 1 1 0 0 65 0 0][uf 4 23 0 3 3 25 25]Ah, comment dire ? Bah, disons que c'est mon problème. Tu pourrais pas comprendre.[n][uf 1 1][e]

[msg MSG_056_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 5 65535 0 0][uf 3 1 1 0 0 66 0 0]J'ai l'impression que ma vie, mon adolescence...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 6 5 65535 0 0][uf 3 1 1 0 0 67 0 0][uf 4 23 0 3 6 25 25]Tout part dans tous les sens.[n][uf 1 1][e]

[msg MSG_057_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 5 65535 0 0][uf 3 1 1 0 0 68 0 0]Bref, je pense qu'on peut en rester là aujourd'hui, hein ?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 5 65535 0 0][uf 3 1 1 0 0 69 0 0]Merci de m'avoir aidé à préparer et à nettoyer tout ça. Bon allez, descendons.[n][uf 1 1][e]

[msg MND_058_0_0]
[uf 0 5 65278][uf 2 1]Je sens que j'ai gagné en [uf 4 30 1 1 1 0] en voyant à quel point Junpei est attentionné...[n][uf 1 1][e]

