[msg MSG_000_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0][uf 4 23 0 1 0 25 25]Guau.[n][uf 1 1][e]

[msg MSG_001_0_0 [Chica con camiseta de flores]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 2 0 0][uf 5 21 0 2]Koromaru, he vuelto.[n][uf 1 1][e]

[msg MSG_002_0_0 [Chico pillo]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 3 0 0][uf 5 21 0 3]¡Qué calentito estás![n][uf 1 1][e]

[msg MSG_003_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 1 0 0 4 0 0][uf 4 23 0 1 0 25 25]Guau, guauuu... Auuu...[n][uf 1 1][e]

[msg MND_002_5_0]
[uf 0 5 65278][uf 2 1]Los niños están jugando a lo bestia con Koromaru.[n][uf 1 1][e]

[msg MSG_004_0_0 [Chica con camiseta de flores]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 5 0 0][uf 5 21 0 2]Mm...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 6 0 0][uf 5 21 0 2]No te pongas malo, ¿eh? Últimamente, hay mucha gente enferma.[n][uf 1 1][e]

[msg MSG_005_0_0 [Chico pillo]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 7 0 0][uf 5 21 0 3]He oído que, si respiras al hacer gárgaras, no te contagias.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 8 0 0][uf 5 21 0 3]Y, si se te enfrían mucho los pies, te entra depresión, así que abrígate bien para dormir.[n][uf 1 1][e]

[msg MSG_006_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 1 0 0 9 0 0][uf 4 23 0 1 0 25 25]¡Guau![n][uf 1 1][e]

[msg MSG_007_0_0 [Chica con camiseta de flores]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 10 0 0][uf 5 21 0 2]Vale, hasta luego.[n][uf 1 1][e]

[msg MSG_008_0_0 [Mujer amable]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 11 0 0][uf 5 21 0 4]Je, je, qué emocionante.[n][uf 1 1][e]

[msg MSG_009_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 1 0 0 12 0 0][uf 4 23 0 1 0 25 25]Haaa, haaa... ¿Guau?[n][uf 1 1][e]

[msg MSG_010_0_0 [Mujer amable]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 13 0 0][uf 5 21 0 4]La ciudad está cambiada, ¿no crees?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 14 0 0][uf 5 21 0 4]Hay mucha gente con la mirada muerta, por no mencionar las historias descabelladas que circulan.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 15 0 0][uf 5 21 0 4]Estaba preocupada y por eso he venido a ver cómo estás.[n][uf 1 1][e]

[msg MSG_011_0_0 [Mujer amable]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 16 0 0][uf 5 21 0 4]Pero no tenía razones para preocuparme.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 17 0 0][uf 5 21 0 4]Cambiemos de tema. A la próxima, traeré algo para picar.[n][uf 1 1][e]

[msg MND_012_0_0]
[uf 0 5 65278][uf 2 1]Hay mucha gente nerviosa por los extraños sucesos que están teniendo lugar en el mundo.[n][uf 1 1][e]

[msg MSG_013_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 0 0 0 18 0 0][uf 4 23 0 1 0 25 25]Haaa, haaa...[n][uf 1 1][e]

[sel SEL_014_0_0 top]
[uf 0 5 65278][uf 2 1]Vamos a por todas.[e]
[uf 0 5 65278][uf 2 1]No podemos perder.[e]
[uf 0 5 65278][uf 2 1]Confío en ti.[e]

[msg MSG_015_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 1 0 0 19 0 0][uf 4 23 0 1 0 25 25]¡Guau, guau![n][uf 1 1][e]

[msg MSG_016_0_0 [Voz de anciano]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 20 0 0][uf 5 21 0 5]¡Ah, ahí están![n][uf 1 1][e]

[msg MSG_017_0_0 [Anciano]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 21 0 0][uf 5 21 0 5]Uf, estoy molido. Además, hace fresco.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 22 0 0][uf 5 21 0 5]Ah, sí. ¿Sabes jugar al shogi, muchacha?[n][uf 1 1][e]

[sel SEL_018_0_0 top]
[uf 0 5 65278][uf 2 1]Sí, soy bastante buena.[e]
[uf 0 5 65278][uf 2 1]Solo un poco.[e]
[uf 0 5 65278][uf 2 1]No, nunca había jugado.[e]

[msg MSG_019_0_0 [Anciano]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 23 0 0][uf 5 21 0 5]Vaya, qué bien.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 24 0 0][uf 5 21 0 5]¿Te apetece echar una partida conmigo?[n][uf 1 1][e]

[msg MSG_020_0_0 [Anciano]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 25 0 0][uf 5 21 0 5]No me digas. Bueno, Koromaru te echará una pata.[n][uf 1 1][e]

[msg MSG_021_0_0 [Anciano]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 26 0 0][uf 5 21 0 5]Yo te enseño. Y, ya que estamos, Koromaru te echará una pata.[n][uf 1 1][e]

[msg MSG_022_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 1 65535 65535 0 0][uf 3 1 1 0 0 27 0 0][uf 4 23 0 1 1 25 25]¡Guau![n][uf 1 1][e]

[msg MND_023_0_0]
[uf 0 5 65278][uf 2 1]Koromaru parece que tiene ganas.[n][uf 1 1][e]

[msg MSG_024_0_0 [Anciano]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 28 0 0][uf 5 21 0 5]Bueno, ¿qué? ¿Jugamos?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 29 0 0][uf 5 21 0 5]Ya no tengo con quien jugar. Verás qué bien nos lo pasamos.[n][uf 1 1][e]

[msg MND_025_0_0]
[uf 0 5 65278][uf 2 1]Koromaru y yo hemos jugado al shogi con el anciano.[n][uf 1 1][e]

[msg MSG_026_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 1 0 0 30 0 0][uf 4 23 0 1 0 25 25]Haaa, haaa... ¡Guau![n][uf 1 1][e]

[msg MSG_027_0_0 [Anciano]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 31 0 0][uf 5 21 0 5]Calla, Korocito. Aún es pronto para darle esa pista.[n][uf 1 1][e]

[msg MSG_028_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 1 0 0 32 0 0][uf 4 23 0 1 0 25 25]¡Guau, guau![n][uf 1 1][e]

[msg MSG_029_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 33 0 0]¿Qué ocurre aquí?[n][uf 1 1][e]

[msg MSG_030_0_0 [Anciano]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 34 0 0][uf 5 21 0 5]Uy.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 35 0 0][uf 5 21 0 5]Vaya, perdona. Estamos en toda la entrada.[n][uf 1 1][e]

[msg MSG_031_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 0 36 0 0]¿Eh? Ay, no, no se preocupe.[n][uf 1 1][e]

[msg MSG_032_0_0 [Anciano]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 37 0 0][uf 5 21 0 5]Ah, claro. Es una residencia de estudiantes.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 38 0 0][uf 5 21 0 5]Entonces, te marcharás de aquí algún día, ¿no, muchacho?[n][uf 1 1][e]

[msg MSG_033_0_0 [Anciano]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 39 0 0][uf 5 21 0 5]Ya.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 40 0 0][uf 5 21 0 5]Bueno, Koromaru, el próximo grupo de estudiantes también cuidará de ti.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 41 0 0][uf 5 21 0 5]Las despedidas forman parte de la vida, pero uno nunca se acostumbra.[n][uf 1 1][e]

[msg MSG_034_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 3 65535 65535 0 0][uf 3 1 1 0 0 42 0 0][uf 4 23 0 1 3 25 25]Auuu...[n][uf 1 1][e]

[sel SEL_035_0_0 top]
[uf 0 5 65278][uf 2 1]Jaque mate.[e]
[uf 0 5 65278][uf 2 1]Se acabó.[e]

[msg MSG_036_0_0 [Anciano]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 43 0 0][uf 5 21 0 5]¡¿Qué?![n][uf 1 1][e]

[msg MSG_037_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 0 44 0 0]Qué buen movimiento.[n][uf 1 1][e]

[msg MSG_038_0_0 [Anciano]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 45 0 0][uf 5 21 0 5]¿Y qué? ¡No hemos hecho más que empezar![n][uf 1 1][e]

[msg MSG_039_0_0 [Anciano]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 46 0 0][uf 5 21 0 5]Qué buena partida. Tendré que dejarme caer por aquí en otra ocasión.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 47 0 0][uf 5 21 0 5]Hasta la próxima. Y a la señorita tan encantadora de ahí, adieu.[n][uf 1 1][e]

[msg MSG_040_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 48 0 0][uf 4 23 0 6 0 25 25]Claro... Cuando terminemos de luchar, habrá que marcharse de la residencia.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 49 0 0][uf 4 23 0 6 0 25 25]Ahora mismo cuesta imaginárselo, pero tarde o temprano ocurrirá.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 50 0 0][uf 4 23 0 6 0 25 25]A fin de cuentas, luchamos precisamente por el futuro.[n][uf 1 1][e]

[msg MSG_041_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 3 65535 65535 0 0][uf 3 1 1 0 0 51 0 0][uf 4 23 0 1 3 25 25]Auuu...[n][uf 1 1][e]

[msg MSG_042_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 0 52 0 0][uf 4 23 0 6 1 25 25]Tú no te preocupes, Koromaru. Todo el mundo te adorará.[n][uf 1 1][e]

[msg MSG_043_0_0 [Voz de anciano]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 53 0 0]Qué faena, mis piezas de shogi...[n][uf 1 1][e]

[msg MSG_044_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 54 0 0][uf 4 23 0 6 0 25 25]¿Es el mismo anciano de antes?[n][uf 1 1][e]

[msg MND_045_0_0]
[uf 0 5 65278][uf 2 1]Hay piezas de shogi tiradas por el suelo, a los pies del anciano.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Creo que debería ayudarlo.[n][uf 1 1][e]

[msg MSG_046_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 1 0 0 55 0 0][uf 4 23 0 1 0 25 25]Haaa, haaa... ¡Guau![n][uf 1 1][e]

[msg MND_047_0_0]
[uf 0 5 65278][uf 2 1]Koromaru y yo ayudamos al anciano y lo acompañamos hasta su casa.[n][uf 1 1][e]

