[msg MSG_000_0_0 [Letter from Bebe]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 1 0 0]"Hello, [uf 4 2]-sama.[n]It is me, Bebe."[n][uf 1 1][e]

[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]Bebe's unsteady scribbles[n]fill the page...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I can picture Bebe's smiling face.[n][uf 1 1][e]

[msg MSG_002_0_0 [Letter from Bebe]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 2 0 0]"Writing in your language is difficult, so forgive me if it is hard to read."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 3 0 0]"I learned a lot in Japan, but I still need lots of help."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 4 0 0]"I write this with a dictionary."[n][uf 1 1][e]

[msg MSG_002_5_0 [Letter from Bebe]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 5 0 0]"I showed Uncle the kimono. He said many wonderful things about it."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 6 0 0]"He said Japan is a great country. I was thrilled to hear it!"[n][uf 1 1][e]

[msg MSG_002_7_0 [Letter from Bebe]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 7 0 0]"So I tell Uncle that I want to go back to Japan."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 8 0 0]"I tell him over and over. Finally he says, 'Okay!'"[n][uf 1 1][e]

[msg MND_003_0_0]
[uf 0 5 65278][uf 2 1]I can really feel Bebe's joy[n]coming through in his letter.[n][uf 1 1][e]

[msg MSG_004_0_0 [Letter from Bebe]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 9 0 0]"But I decided not to go back."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 10 0 0]"I am sorry, [uf 4 2]-sama. I said I would come back, but it was a lie."[n][uf 1 1][e]

[msg MSG_004_2_0 [Letter from Bebe]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 11 0 0]"I didn't know."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 12 0 0]"My aunt was not the only one who helped me study abroad."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 13 0 0]"Uncle, relatives, neighbors... So many people helped me."[n][uf 1 1][e]

[msg MSG_004_4_0 [Letter from Bebe]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 14 0 0]"They all wanted me to go back. They said they would help pay for it."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 15 0 0]"But Uncle is sad after he lost my aunt."[n][uf 1 1][e]

[msg MSG_004_6_0 [Letter from Bebe]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 16 0 0]"While Uncle grieves, I would not be able to enjoy myself in Japan."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 17 0 0]"I cannot take everyone's money for my own fun."[n][uf 1 1][e]

[msg MSG_004_8_0 [Letter from Bebe]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 18 0 0]"Besides, I can learn about Japan here in France, too."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 19 0 0]"And so, in France I will stay."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 20 0 0]"Someday, I will return to Japan on my own, without anyone's help."[n][uf 1 1][e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]I can feel the determination[n]in Bebe's words.[n][uf 1 1][e]

[msg MSG_006_0_0 [Letter from Bebe]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 21 0 0]"I reflected on how fun it was to make clothes with you, [uf 4 2]-sama, so I enrolled in fashion school."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 22 0 0]"I made some clothes for the school contest, and I won first prize!"[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 23 0 0]"I have come up with a name for my winning design."[n][uf 1 1][e]

[msg MSG_006_3_0 [Letter from Bebe]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 24 0 0]"'[uf 4 2]'... A very wonderful name, I think."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 25 0 0]"It is a name that means a lot to me."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 26 0 0]"Japan and France, [uf 4 2]-sama and me... All so far apart."[n][uf 1 1][e]

[msg MSG_006_5_0 [Letter from Bebe]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 27 0 0]"But I am always here for you. No amount of distance will ever change that."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 28 0 0]"Every day was so much fun. More fun than I've ever had."[n][uf 1 1][e]

[msg MSG_006_7_0 [Letter from Bebe]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 29 0 0]"I hope I get to see you again someday."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 30 0 0]"To my precious friend, [uf 4 2]-sama[n]　　　　　　　　　　　　　　　　Bebe"[n][uf 1 1][e]

[msg MND_007_0_0]
[uf 0 5 65278][uf 2 1]The words near the end are smudged...[n][uf 1 1][e]

