[msg MSG_000_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0][uf 4 23 0 1 1 25 25]Lo que estoy a punto de contarte es un secreto. No lo puede saber nadie, ¿entendido?[n][uf 1 1][e]

[msg MSG_000_3_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 1 0 0 2 0 0][uf 4 23 0 1 0 25 25]Este mundo acabará pronto. Toda la humanidad será aniquilada.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 1 65535 65535 0 0][uf 3 1 1 0 0 3 0 0][uf 4 23 0 1 1 25 25]Pero ¡no te preocupes! Lo recrearemos en una nueva tierra para los supervivientes: ¡Paraíso![n][uf 1 1][e]

[msg MSG_000_5_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 1 65535 65535 0 0][uf 3 1 1 0 0 4 0 0][uf 4 23 0 1 1 25 25]¿Y bien? Estás flipando, ¿eh?[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]Sí, qué nervios.[e]
[uf 0 5 65278][uf 2 1]No, la verdad.[e]
[uf 0 5 65278][uf 2 1]¿El mundo se acaba?[e]

[msg MSG_002_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 2 65535 65535 0 0][uf 3 1 1 0 0 5 0 0][uf 4 23 0 1 2 25 25]Pero no te mees encima ni nada de eso, que estoy intentando comerme una hamburguesa.[n][uf 1 1][e]

[msg MSG_003_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 1 65535 65535 0 0][uf 3 1 1 0 0 6 0 0][uf 4 23 0 1 1 25 25]Pero no pasa nada. Te perdono.[n][uf 1 1][e]

[msg MSG_004_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 4 65535 65535 0 0][uf 3 1 1 0 0 7 0 0][uf 4 23 0 1 4 25 25][uf 5 13 19 5 116]Vaya, [uf 4 2]. Quiero ser como tú.[n][uf 1 1][e]

[msg MSG_005_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 3 65535 65535 0 0][uf 3 1 1 0 0 8 0 0][uf 4 23 0 1 3 25 25]Cuando yo me enteré, tuve que cambiarme de pantalones.[n][uf 1 1][e]

[msg MSG_006_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 4 65535 65535 0 0][uf 3 1 1 0 0 9 0 0][uf 4 23 0 1 4 25 25][uf 5 13 19 15 116]¡O-oye! ¡Baja la voz, [uf 4 2]![n][uf 1 1][e]

[msg MSG_007_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 4 65535 65535 0 0][uf 3 1 1 0 0 10 0 0][uf 4 23 0 1 4 25 25]¡Ya te he dicho que es un secreto! No queremos que cunda el pánico.[n][uf 1 1][e]

[msg MSG_008_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 1 65535 65535 0 0][uf 3 1 1 0 0 11 0 0][uf 4 23 0 1 1 25 25]En Paraíso, la gente tendrá alas y una figura perfecta... y olerá a flores.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 1 65535 65535 0 0][uf 3 1 1 0 0 12 0 0][uf 4 23 0 1 1 25 25]Yo... ¡por fin me reencarnaré en un cuerpo digno![n][uf 1 1][e]

[msg MSG_009_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 3 65535 65535 0 0][uf 3 1 1 0 0 13 0 0][uf 4 23 0 1 3 25 25]Pero, si no hacemos algo, te quedarás atrás cuando el mundo acabe.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 3 65535 65535 0 0][uf 3 1 1 0 0 14 0 0][uf 4 23 0 1 3 25 25]¡Y me niego! Venga, ¡vayamos a Paraíso juntos![n][uf 1 1][e]

[msg MSG_009_3_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 3 65535 65535 0 0][uf 3 1 1 0 0 15 0 0][uf 4 23 0 1 3 25 25]No lo hagas solo por ser mi súbdito, ¡¿vale?! Hazlo porque somos... amigos.[n][uf 1 1][e]

[msg MND_010_0_0]
[uf 0 5 65278][uf 2 1]Creo que Suemitsu me considera una buena amiga.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Tengo la sensación de que nuestra relación se ha fortalecido.[n][uf 1 1][e]

[msg MSG_011_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 1 65535 65535 0 0][uf 3 1 1 0 0 16 0 0][uf 4 23 0 1 1 25 25]A ver qué te parece esto.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 1 65535 65535 0 0][uf 3 1 1 0 0 17 0 0][uf 4 23 0 1 1 25 25]Si tenemos en cuenta las tasas de iniciación, las escrituras y otros productos..., serían 132 000 yenes. Puedes pedir un préstamo, ¿no?[n][uf 1 1][e]

[msg MSG_011_3_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 1 65535 65535 0 0][uf 3 1 1 0 0 18 0 0][uf 4 23 0 1 1 25 25]Además, obtendrás un descuento, porque yo también te recomendaré. ¡Qué suertuda![n][uf 1 1][e]

[sel SEL_012_0_0 top]
[uf 0 5 65278][uf 2 1]¡Menuda locura![e]
[uf 0 5 65278][uf 2 1]No pienso pagar nada.[e]

[msg MSG_013_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 4 65535 65535 0 0][uf 3 1 1 0 0 19 0 0][uf 4 23 0 1 4 25 25]¡¿L-locura?! Tú sí que estás loca, canalla pecadora.[n][uf 1 1][e]

[msg MSG_014_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 2 65535 65535 0 0][uf 3 1 1 0 0 20 0 0][uf 4 23 0 1 2 25 25]Solo quería compartir contigo la felicidad eterna porque tu alma me importa.[n][uf 1 1][e]

[msg MSG_015_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 4 65535 65535 0 0][uf 3 1 1 0 0 21 0 0][uf 4 23 0 1 4 25 25]¿Q-qué? ¡¿T-tienes idea de lo que dices?![n][uf 1 1][e]

[msg MSG_016_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 2 65535 65535 0 0][uf 3 1 1 0 0 22 0 0][uf 4 23 0 1 2 25 25]Solo quería compartir contigo la felicidad eterna porque tu alma me importa.[n][uf 1 1][e]

[msg MSG_017_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 4 65535 65535 0 0][uf 3 1 1 0 0 23 0 0][uf 4 23 0 1 4 25 25]¡He de ir a confesarme en tu nombre! En nombre de la fe, ¡emergencia![n][uf 1 1][e]

[msg MND_018_0_0]
[uf 0 5 65278][uf 2 1]He decidido volver a la residencia.[n][uf 1 1][e]

