[msg MSG_000_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 3 0 65535 1002 0 0]Ça fait plutôt bizarre de traîner ici alors qu'on n'a pas cours, tu trouves pas ?[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][f 4 23 0 2 0 25 25]Si quelqu'un nous voit, ça pourrait faire jaser...[n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0][f 4 23 0 2 1 25 25]Bon... Je pense qu'il est trop tard pour s'en inquiéter... Haha.[n][w][e]

[msg MSG_001_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0]Au fait, qu'est-ce que tu fais quand tu n'as pas cours, d'habitude ?[n][w][e]

[msg MSG_002_0_0 [Yukari Takeba]]
[f 2 1][bup 2 4 65535 65535 0 0][vp 3 0 65535 1111 0 0]Je voulais pas être indiscrète, hein... C'était juste par curiosité.[n][w][e]

[sel SEL_003_0_0 top]
[f 2 1]Je passe du temps en bonne compagnie.[e]
[f 2 1]Je reste dans ma chambre.[e]
[f 2 1]Je ne me souviens pas.[e]

[msg MSG_004_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 3 0 65535 1132 0 0][f 5 13 7 30 2]J-Je vois. Comme ce qu'on fait aujourd'hui, donc ?[n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0]Bien sûr, je me doute bien que tout le monde aime traîner avec toi, [nl].[n][w][e]

[msg MND_005_0_0]
[f 2 1]Yukari hoche la tête.[n][w][e]
[f 2 1]J'ai l'impression qu'on s'est beaucoup rapprochées, aujourd'hui.[n][w][e]

[msg MSG_006_0_0 [Yukari Takeba]]
[f 2 1][bup 2 3 65535 65535 0 0][vp 3 0 65535 1107 0 0][f 5 13 7 15 2]Vraiment ? Comment je l'ai pas remarqué ? On est dans le même dortoir.[n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0][f 4 23 0 2 1 25 25]Alors, euh... Tu devrais m'inviter à sortir... Tu te sens pas un peu seule, dans ton coin ?[n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0]Oui, ça serait marrant, je pense.[n][w][e]

[msg MND_007_0_0]
[f 2 1]Yukari hoche la tête.[n][w][e]
[f 2 1]Aujourd'hui, j'en ai appris un peu plus sur elle.[n][w][e]

[msg MSG_008_0_0 [Yukari Takeba]]
[f 2 1][bup 2 4 65535 65535 0 0][vp 3 0 65535 1122 0 0]Hein ? C'est impossible que t'arrives pas à t'en souvenir.[n][w][e]
[f 2 1][bup 2 4 65535 65535 0 0]Ou peut-être que tu ne veux pas admettre que tu restes dans ta chambre à te tourner les pouces.[n][w][e]
[f 2 1][bup 2 6 65535 65535 0 0][f 4 23 0 2 6 25 25]Tu sais, quand on vit aussi mal, c'est sûr qu'on va mal vieillir.[n][w][e]

[msg MND_009_0_0]
[f 2 1]Yukari a l'air de s'en faire pour moi.[n][w][e]
[f 2 1]J'ai l'impression qu'on ne s'est pas rapprochées, aujourd'hui...[n][w][e]

[msg MSG_010_0_0 [Yukari Takeba]]
[f 2 1][bup 2 4 65535 65535 0 0][vp 3 0 65535 1067 0 0]Oh ? Regarde l'heure ! Décidément, le temps passe trop vite quand on s'amuse...[n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0][f 4 23 0 2 1 25 25]Allez, on va encore quelque part avant de rentrer. Il faut qu'on profite du temps qui nous reste ![n][w][e]

[msg MND_011_0_0]
[f 2 1]On a passé un peu de temps ensemble, avant de rentrer au dortoir.[n][w][e]

