[msg MND_014_0_0]
[f 2 1]C'est un autre épisode de cette docusérie sur une meute de loups...[n][w][e]
[f 2 1]Dans celui-ci, un louveteau espiègle joue avec son père.[n][w][e]

[msg MSG_015_0_0 [Koromaru]]
[f 2 1][bup 9 3 65535 65535 0 0][vp 0 0 0 1 0 0][f 4 23 0 1 3 25 25]......[n][w][e]

[msg MND_016_0_0]
[f 2 1]Koromaru a l'air un peu triste...[n][w][e]

[msg MSG_017_0_0 [Koromaru]]
[f 2 1][bup 9 3 65535 65535 0 0][vp 1 0 0 2 0 0][f 4 23 0 1 3 25 25]Wouf ! Wouuuf ![n][w][e]

[sel SEL_018_0_0 top]
[f 2 1]Un problème ?[e]
[f 2 1]Tes parents te manquent ?[e]
[f 2 1]Tu veux qu'on en reste là ?[e]

[msg MSG_019_0_0 [Koromaru]]
[f 2 1][bup 9 3 65535 65535 0 0][vp 1 0 0 3 0 0][f 4 23 0 1 3 25 25]Kaï...[n][w][e]

[msg MSG_020_0_0 [Koromaru]]
[f 2 1][bup 9 3 65535 65535 0 0][vp 1 0 0 4 0 0][f 4 23 0 1 3 25 25]Wouf.[n][w][e]

[msg MSG_021_0_0 [Koromaru]]
[f 2 1][bup 9 2 65535 65535 0 0][vp 1 0 0 5 0 0][f 4 23 0 1 2 25 25]Ouaf ! Ouaf, ouaf ![n][w][e]

[msg MSG_022_0_0 [Koromaru]]
[f 2 1][bup 9 3 65535 65535 0 0][vp 0 0 0 6 0 0][f 4 23 0 1 0 25 25]......[n][w][e]

[msg MND_023_0_0]
[f 2 1]Koromaru semble captivé par ce passage. Il a un air de nostalgie dans les yeux.[n][w][e]
[f 2 1]Je me demande si ses parents lui manquent...[n][w][e]

[msg MSG_024_0_0 [Koromaru]]
[f 2 1][bup 9 0 65535 65535 0 0][vp 1 0 0 7 0 0][f 4 23 0 1 0 25 25]Ouaf ![n][w][e]

[msg MND_025_0_0]
[f 2 1]Observer comment les animaux vivent dans la nature m'a fait gagner en [f 4 30 0 1 1 0].[n][w][e]

[msg MSG_026_0_0 [Koromaru]]
[f 2 1][bup 9 0 65535 65535 0 0][vp 1 0 0 8 0 0][f 4 23 0 1 0 25 25]Grrr... Ouaf ![n][w][e]

[msg MND_027_0_0]
[f 2 1]On dirait que cette série documentaire sur les loups a une suite...[n][w][e]
[f 2 1]Je la regarderai peut-être avec Koromaru quand j'aurai le temps.[n][w][e]

