[msg MSG_000_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 1 0 0]J'aimerais faire du thé... mais il faut que j'enlève ça d'abord.[n][w][e]

[sel SEL_001_0_0 top]
[f 2 1]C'est quoi ?[e]
[f 2 1]Classe.[e]

[msg MSG_002_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 2 0 0]Ce sont des bandages pour les mains. Ça sert à protéger les jointures et le poignet.[n][w][e]

[msg MSG_003_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 1 65535 65535 0 0][vp 1 0 0 3 0 0]Ce n'est pas juste pour faire joli. Ces bandages servent à protéger mes jointures et mon poignet.[n][w][e]

[msg MSG_004_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 4 0 0]Et ça ne sert pas juste à me protéger, ça donne aussi plus d'impact à mes coups selon la manière dont j'enveloppe mes poings.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 5 0 0]Sans ses bandages, mes poings seraient inoffensifs. Quand je suis sur le ring, ils font toute la différence.[n][w][e]

[msg MSG_005_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 6 0 0]Bref, mets-toi à l'aise.[n][w][e]

[msg MSG_006_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 7 0 0]Alors, si je t'ai demandé de venir aujourd'hui... c'est parce que je voulais te parler de ce sur quoi je travaille.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 8 0 0]J'ai passé beaucoup de temps à m'entraîner et à m'améliorer...[n][w][e]

[msg MSG_007_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 9 0 0]Et je pensais avoir enfin atteint un stade où je pourrais avoir confiance en ma force.[n][w][e]

[msg MSG_008_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 3 65535 65535 0 0][vp 1 0 0 10 0 0]... Mais après avoir entendu l'Évaluateur, j'ai eu peur.[n][w][e]
[f 2 1][bup 4 3 65535 65535 0 0][vp 1 0 0 11 0 0]J'ai aussi ressenti de la colère, car l'entraînement que j'avais suivi n'avait aucun sens.[n][w][e]
[f 2 1][bup 4 3 65535 65535 0 0][vp 1 0 0 12 0 0]Je me suis dit que j'affronterai les choses en face, mais je suis toujours aussi faible qu'avant.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 13 0 0][f 4 23 0 4 0 25 25]Dis-moi... est-ce que tu me trouves assez fort ?[n][w][e]

[sel SEL_009_0_0 top]
[f 2 1]Carrément.[e]
[f 2 1]Je ne sais pas.[e]
[f 2 1]Ne perds pas espoir.[e]

[msg MSG_010_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 14 0 0]Héhé. J'aimerais le croire, mais je ne sais plus.[n][w][e]

[msg MSG_011_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 15 0 0]Pas faux. Je découvrirai peut-être la réponse dans un avenir proche.[n][w][e]

[msg MSG_012_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 1 65535 65535 0 0][vp 1 0 0 16 0 0]Tu as raison. Je suis sûr que je découvrirai la réponse bien assez tôt.[n][w][e]

[msg MSG_013_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 3 65535 65535 0 0][vp 1 0 0 17 0 0]Tout le monde perd confiance en soi de temps à autre. C'est à ce moment-là que les points faibles ressurgissent.[n][w][e]
[f 2 1][bup 4 3 65535 65535 0 0][vp 1 0 0 18 0 0]C'est difficile d'être sur le point de saisir quelque chose, tout en étant aux prises avec la peur et la frustration de tout perdre à nouveau...[n][w][e]
[f 2 1][bup 4 3 65535 65535 0 0][vp 1 0 0 19 0 0]Je ne comprends que trop bien ce sentiment.[n][w][e]

[msg MSG_014_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 3 65535 65535 0 0][vp 1 0 0 20 0 0]Je sais qu'on t'a poussé à prendre cette décision cruciale, et j'imagine bien que c'était pas évident.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 21 0 0][f 4 23 0 4 0 25 25]Mais... ne rejette pas la faute sur Junpei et les autres.[n][w][e]

[sel SEL_015_0_0 top]
[f 2 1]Je sais.[e]
[f 2 1]Ils pourraient déjà se rattraper.[e]
[f 2 1]Un peu tard pour ça.[e]

[msg MSG_016_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 1 65535 65535 0 0][vp 1 0 0 22 0 0]Tu es vraiment forte, tu sais ça ?[n][w][e]

[msg MSG_017_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 1 65535 65535 0 0][vp 1 0 0 23 0 0]C'est bon. Je sais qu'ils vont faire le nécessaire.[n][w][e]

[msg MSG_018_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 1 65535 65535 0 0][vp 1 0 0 24 0 0]J'aurais pu t'épargner des problèmes si je t'en avais parlé plus tôt, hein ?[n][w][e]

[msg MSG_019_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 25 0 0]Bref, vu que moi aussi, j'étais là, je voulais juste que tu le saches.[n][w][e]

[msg MSG_020_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 26 0 0]... Peu importe ta décision, j'accomplirai mon devoir.[n][w][e]

[msg MSG_021_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 27 0 0]J'ai affronté d'innombrables adversaires pour en arriver là.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 28 0 0]Si j'affirme que tout mon entraînement n'a aucun sens, ça reviendrait à ne pas reconnaître leurs efforts.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 29 0 0]Ce serait inacceptable, tu ne crois pas ?[n][w][e]

[msg MSG_022_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 1 65535 65535 0 0][vp 1 0 0 30 0 0]Désolé, je ne voulais pas changer de sujet comme ça.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 31 0 0][f 4 23 0 4 0 25 25]Je t'ai demandé de m'accompagner et tu t'es retrouvée mêlée à mon combat. Je vais devoir te rendre la pareille, c'est le minimum.[n][w][e]

[msg MSG_023_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 32 0 0]Hmm... J'étais pourtant certain que mon mélange spécial de protéines se trouvait quelque part par ici...[n][w][e]

[msg MND_024_0_0]
[f 2 1]......[n][w][e]
[f 2 1]Je peux apercevoir un objet fait main familier sur le bureau.[n][w][e]
[f 2 1]C'est cette médaille d'or en carton faite par la sœur de Sanada...[n][w][e]

[msg MSG_025_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 33 0 0]Oh, ça...[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 34 0 0]Je pensais la renvoyer à mes parents avec ma carte du Nouvel An.[n][w][e]
[f 2 1][bup 4 3 65535 65535 0 0][vp 1 0 0 35 0 0][f 4 23 0 4 3 25 25]On ne sait pas de quoi l'avenir sera fait. Je préfère que ce soient eux qui l'aient.[n][w][e]

[sel SEL_026_0_0 top]
[f 2 1]Ça t'appartient.[e]
[f 2 1]Ne t'enfuis pas.[e]

[msg MSG_027_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 4 65535 65535 0 0][vp 0 0 0 36 0 0]... ![n][w][e]

[msg MSG_028_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 37 0 0]T'es bizarre. Pendant qu'on se battait tout à l'heure, je pensais...[n][w][e]
[f 2 1][bup 4 1 65535 65535 0 0][vp 1 0 0 38 0 0][f 4 23 0 4 1 25 25]J'ignore pourquoi, mais je sens que je peux te faire confiance. J'ai l'impression qu'ensemble, on peut tout surmonter.[n][w][e]

[msg MSG_029_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 39 0 0]Pendant longtemps, tout ce qui m'importait était d'avoir la puissance nécessaire pour protéger quelqu'un.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 40 0 0]Je pensais que me montrer dur envers moi-même et rivaliser avec les autres était le seul moyen d'y arriver.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 41 0 0]C'est vrai que cette approche m'a permis de gagner en force.[n][w][e]

[msg MSG_030_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 42 0 0]À présent, je ne suis plus seul à me battre.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 43 0 0]J'ai donc des gens que je veux protéger, mais en même temps, je veux qu'ils se battent à mes côtés.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 44 0 0]... En fin de compte, c'est grâce à votre présence que je sens que je peux devenir encore plus fort.[n][w][e]

[msg MSG_031_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 3 65535 65535 0 0][vp 1 0 0 45 0 0]... Je ne sais toujours pas si je suis assez fort ou gentil pour mériter cette médaille.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 46 0 0][f 4 23 0 4 0 25 25]Mais c'est un bon début, et je devrais la garder pour toujours avec moi.[n][w][e]

[msg MSG_032_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 47 0 0]Tu m'as donné une leçon précieuse aujourd'hui. Bon, où je vais mettre...[n][w][e]

[sel SEL_033_0_0 top]
[f 2 1]Laisse-moi voir.[e]
[f 2 1]Tu devrais afficher ça.[e]

[msg MSG_034_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 48 0 0]Oh... Bien sûr.[n][w][e]

[msg MSG_035_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 4 65535 65535 0 0][vp 0 0 0 49 0 0]... ![n][w][e]

[msg MSG_036_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 0 0 0 50 0 0]......[n][w][e]

[msg MSG_037_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 51 0 0]Oui, je pense que je le ferai.[n][w][e]

[msg MSG_038_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 0 0 0 52 0 0]......[n][w][e]

[msg MSG_039_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 3 65535 65535 0 0][vp 1 0 0 53 0 0]... J'ai réussi, Miki.[n][w][e]

[sel SEL_040_0_0 top]
[f 2 1]Tu le mérites.[e]
[f 2 1]Continue à travailler dur.[e]

[msg MSG_041_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 54 0 0]... C'est un immense honneur. Je me battrai pour la protéger comme un champion qui combat pour conserver son titre.[n][w][e]

[msg MSG_042_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 55 0 0]Si tu le dis. Je vais continuer à me battre comme le challenger d'un titre détenu par un autre boxeur.[n][w][e]

[msg MSG_043_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 56 0 0]... Je ne suis peut-être pas très doué pour motiver les gens avec des mots, ou pour communiquer ce que je ressens.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 57 0 0]Mais tu peux être sûr que je ne reculerai jamais devant un combat.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 58 0 0]Même si je suis battu à plate couture et que je suis à terre, je me relèverai à chaque fois.[n][w][e]

[msg MSG_044_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 59 0 0]Je n'abandonnerai jamais. C'est mon devoir.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 60 0 0]Alors tu peux compter sur moi... Je te jure que je te protégerai.[n][w][e]

[msg MSG_045_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 61 0 0]... Cela dit, je te dois encore tellement.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 62 0 0]Je ferai de mon mieux pour rembourser cette dette. Je n'ai pas encore pu te remercier correctement pour ton aide.[n][w][e]

[msg MSG_046_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 63 0 0]Ah, c'est vrai. Je comptais au moins te remercier pour aujourd'hui.[n][w][e]

[msg MSG_047_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 0 0 0 64 0 0]......[n][w][e]
[f 2 1][bup 4 3 65535 65535 0 0][vp 1 0 0 65 0 0][f 4 23 0 4 3 25 25]Mince... On dirait que je n'ai plus de poudre de protéines.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 66 0 0][f 4 23 0 4 0 25 25]Qu'est-ce que j'ai d'autre... Ah, tiens. Tu peux prendre ces haltères.[n][w][e]

[msg MSG_048_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 67 0 0]Juste une minute. Je vais te préparer ça.[n][w][e]

[msg MSG_049_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 1 65535 65535 0 0][vp 1 0 0 68 0 0]Tu peux changer le poids pour qu'ils correspondent à ta force musculaire.[n][w][e]
[f 2 1][bup 4 1 65535 65535 0 0][vp 1 0 0 69 0 0]Dans ton cas, je commencerais avec 8 kg... Non, en fait je pense que tu peux aller jusqu'à 10.[n][w][e]
[f 2 1][bup 4 1 65535 65535 0 0][vp 1 0 0 70 0 0]Tu peux aussi utiliser une machine, mais il est important de faire aussi un peu de musculation avec des haltères....[n][w][e]

[msg MND_050_0_0]
[f 2 1]Après avoir silencieusement approuvé la détermination de Sanada, je suis retournée dans ma chambre.[n][w][e]
[f 2 1]Je me suis sentie inspirée par son enthousiasme...[n][w][e]

[msg PFM_SPUP_0_0]
[f 2 1][vp 1 0 0 71 0 0]PC max augmentés de 3.[n][w][e]

