[msg MSG_000_0_0 [Type hostile]]
[f 2 1][vp 1 0 0 1 0 0][f 5 21 0 1011]Hé, le prends pas comme ça... Je connais le coin parfait pour nous, poupée.[n][w][e]

[msg MSG_001_0_0 [Fan de tout à l'heure]]
[f 2 1][vp 1 0 0 2 0 0][f 5 21 0 1001]S'il vous plaît, laissez-nous tranquilles ! Nous ne sommes pas intéressées.[n][w][e]

[msg MSG_001_5_0 [Type vantard]]
[f 2 1][vp 1 0 0 3 0 0][f 5 21 0 1012]Un verre, c'est tout ce qu'on demande. Allez, ça va être marrant.[n][w][e]

[msg MSG_001_7_0 [Fan effrayée]]
[f 2 1][vp 1 0 0 4 0 0][f 5 21 0 1002]On a dit non, OK ?![n][w][e]

[sel SEL_002_0_0 top]
[f 2 1]Ce sont les filles de tout à l'heure.[e]
[f 2 1]Est-ce qu'ils les harcèlent ?[e]

[msg MSG_003_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 2 65535 65535 0 0][vp 0 0 0 5 0 0]......[n][w][e]

[msg MSG_005_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 2 65535 65535 0 0][vp 1 0 0 6 0 0]Hé...[n][w][e]

[msg MSG_006_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 2 65535 65535 0 0][vp 1 0 0 7 0 0]Laissez-les tranquilles. Vous ne voudriez pas que la police vienne s'en mêler ?[n][w][e]

[msg MSG_007_0_0 [Type hostile]]
[f 2 1][vp 1 0 0 8 0 0][f 5 21 0 1011]Hein ? T'es qui, toi ?[n][w][e]

[msg MSG_008_0_0 [Type vantard]]
[f 2 1][vp 1 0 0 9 0 0][f 5 21 0 1012]Tu veux appeler les flics ? Arrête de jouer au dur, petit merdeux ![n][w][e]

[msg MSG_009_0_0 [Type hostile]]
[f 2 1][vp 1 0 0 10 0 0][f 5 21 0 1011]Ouais, allez... CASSE-TOI ![n][w][e]

[msg MSG_010_0_0 [Type vantard]]
[f 2 1][vp 1 0 0 11 0 0][f 5 21 0 1012]Sale fils de... ![n][w][e]

[msg MSG_011_0_0 [Type baraqué]]
[f 2 1][vp 1 0 0 12 0 0][f 5 21 0 1013]Une minute...[n][w][e]

[msg MSG_012_0_0 [Type baraqué]]
[f 2 1][vp 1 0 0 13 0 0][f 5 21 0 1013]T'as l'air de connaître des techniques plutôt cool... Je parie que tu sais te battre, pas vrai ?[n][w][e]

[msg MSG_013_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 2 65535 65535 0 0][vp 1 0 0 14 0 0]Et si c'était le cas ?[n][w][e]

[msg MSG_014_0_0 [Type baraqué]]
[f 2 1][vp 1 0 0 15 0 0][f 5 21 0 1013]Qu'est-ce que tu dirais de m'affronter ? Si t'as rien d'autre à faire, je connais le coin parfait juste derrière.[n][w][e]

[msg MSG_023_0_0 [Type baraqué]]
[f 2 1][vp 1 0 0 16 0 0][f 5 21 0 1013]Chaque fois que je vois des gars qui se la racontent je peux pas m'empêcher de les remettre à leur place.[n][w][e]
[f 2 1][vp 1 0 0 17 0 0][f 5 21 0 1013]Je suis sûr que les gens te voient comme un gros dur, alors si tu me montrais ce que t'as dans le ventre ?[n][w][e]

[msg MSG_024_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 2 65535 65535 0 0][vp 0 0 0 18 0 0]......[n][w][e]

[msg MSG_025_0_0 [Larbin]]
[f 2 1][vp 1 0 0 19 0 0][f 5 21 0 1014]Hein ? Il chie dans son froc ? Hahaha ![n][w][e]

[msg MSG_026_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 20 0 0]Tu vois ? Je t'avais dit... Que des ennuis...[n][w][e]
[f 2 1][bup 4 2 65535 65535 0 0][vp 1 0 0 21 0 0][f 4 23 0 4 2 25 25]Attends-moi là. Je n'en aurai pas pour longtemps...[n][w][e]

[msg MSG_027_0_0 [Type baraqué]]
[f 2 1][vp 1 0 0 22 0 0][f 5 21 0 1013]Quoi ?! Tu crois pouvoir me vaincre juste comme ça ?![n][w][e]

[msg MSG_028_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 2 65535 65535 0 0][vp 1 0 0 23 0 0]Ne t'en fais pas, je retiens mes coups avec les amateurs... Le combat doit rester équitable.[n][w][e]

[msg MSG_029_0_0 [Type baraqué]]
[f 2 1][vp 1 0 0 24 0 0][f 5 21 0 1013]Arg ![n][w][e]

[msg MSG_030_0_0 [Voix venant d'une voiture de police]]
[f 2 1][vp 1 0 0 25 0 0]Hé, vous, là-bas ! Arrêtez ça tout de suite ![n][w][e]

[msg MSG_031_0_0 [Type baraqué]]
[f 2 1][vp 1 0 0 26 0 0][f 5 21 0 1013]Pff... Cassons-nous ![n][w][e]

[msg MSG_032_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 3 65535 65535 0 1][vp 1 0 0 27 0 0]Je vous l'ai dit, inspecteur... Ce sont eux qui nous ont cherché des problèmes.[n][w][e]

[msg MSG_032_5_0 [Jeune inspecteur]]
[f 2 1][vp 1 0 0 28 0 0][f 5 21 0 1021]Et je t'ai déjà dit que nous verrons ça au poste...[n][w][e]

[msg MSG_032_7_0 [Inspecteur d'âge mûr]]
[f 2 1][vp 1 0 0 29 0 0][f 5 21 0 1022]Vous êtes lycéens, c'est ça ? Nous allons avoir besoin d'un numéro pour contacter vos parents à ce sujet.[n][w][e]

[msg MSG_098_0_0 [Inspecteur Kurosawa]]
[f 2 1][bup 1086 0 65535 65535 0 0][vp 1 0 0 30 0 0][f 5 21 0 1086]Si je peux me permettre...[n][w][e]

[msg MSG_099_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 1 65535 65535 0 0][vp 1 0 0 31 0 0]Kurosawa ![n][w][e]

[msg MSG_102_0_0 [Inspecteur Kurosawa]]
[f 2 1][bup 1086 0 65535 65535 0 0][vp 1 0 0 32 0 0][f 5 21 0 1086]Je vais m'occuper de ces deux-là. Je me suis déjà arrangé avec mon patron.[n][w][e]

[msg MSG_033_0_0 [Inspecteur Kurosawa]]
[f 2 1][bup 1086 0 65535 65535 0 0][vp 1 0 0 33 0 0][f 5 21 0 1086]Je ne sais pas ce qu'il se passe ici, mais tu n'as pas intérêt à causer des problèmes...[n][w][e]

[sel SEL_033_5_0 top]
[f 2 1]Aucun problème à l'horizon...[e]
[f 2 1]Ce n'était pas de notre faute.[e]
[f 2 1]C'était moins une.[e]

[msg MSG_033_2_0 [Inspecteur Kurosawa]]
[f 2 1][bup 1086 0 65535 65535 0 0][vp 1 0 0 34 0 0][f 5 21 0 1086]Alors pourquoi j'ai une déposition de deux demoiselles stipulant que tu as été attaqué par des loubards ?[n][w][e]

[msg MSG_033_4_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 35 0 0]Ils voulaient que je leur montre l'étendue de ma force... Je n'ai fait que leur offrir ce qu'ils voulaient.[n][w][e]

[msg MSG_033_6_0 [Inspecteur Kurosawa]]
[f 2 1][bup 1086 0 65535 65535 0 0][vp 1 0 0 36 0 0][f 5 21 0 1086]Au beau milieu de la rue ? Il va vraiment falloir que tu commences à réfléchir un peu plus.[n][w][e]

[msg MSG_034_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 1 65535 65535 0 0][vp 1 0 0 37 0 0]Ne me dis pas que t'as vraiment cru qu'on était en danger ?[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 38 0 0][f 4 23 0 4 0 25 25]Même si les choses peuvent dégénérer des fois, je ne te mettrai jamais en danger.[n][w][e]

[msg MSG_034_5_0 [Inspecteur Kurosawa]]
[f 2 1][bup 1086 0 65535 65535 0 0][vp 1 0 0 39 0 0][f 5 21 0 1086]Alors pourquoi j'ai une déposition de deux demoiselles stipulant que tu as été attaqué par des loubards ?[n][w][e]
[f 2 1][bup 1086 0 65535 65535 0 0][vp 1 0 0 40 0 0][f 5 21 0 1086]Si tu voulais impressionner ta copine, t'as mal choisi ton moment.[n][w][e]

[msg MSG_035_0_0 [Inspecteur Kurosawa]]
[f 2 1][bup 1086 0 65535 65535 0 0][vp 1 0 0 41 0 0][f 5 21 0 1086]Écoute, je reste un gardien de la paix avant tout. Qui que tu sois, si tu viens troubler la paix, tu auras affaire à moi.[n][w][e]

[msg MSG_036_0_0 [Inspecteur Kurosawa]]
[f 2 1][bup 1086 0 65535 65535 0 0][vp 1 0 0 42 0 0][f 5 21 0 1086]Comme tu peux le voir, ton ami a un peu trop tendance à être une tête brûlée...[n][w][e]
[f 2 1][bup 1086 0 65535 65535 0 0][vp 1 0 0 43 0 0][f 5 21 0 1086]Je sais que ça risque de ne pas être facile pour toi, mais essaie de veiller sur lui, d'accord ?[n][w][e]

[sel SEL_037_0_0 top]
[f 2 1]Je m'en occupe.[e]
[f 2 1]Je ne suis pas sûre de pouvoir.[e]

[msg MSG_038_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 1 65535 65535 0 0][vp 1 0 0 44 0 0]Je vois que tu ne manques pas de courage... mais merci.[n][w][e]

[msg MSG_039_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 1 65535 65535 0 0][vp 1 0 0 45 0 0]Ne t'inquiète pas pour ça. Je sais ce que je fais quand je décide de me battre.[n][w][e]

[msg MSG_040_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 46 0 0]Mon bras est guéri, et on a bien plus de soutien maintenant. Je n'aurais pas pu rêver mieux pour remettre le pied à l'étrier.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 47 0 0]Qui plus est maintenant qu'on a quelqu'un comme toi avec nous. On a vraiment eu du bol.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 48 0 0]Donc je vais continuer de me perfectionner. Comme ça, je pourrais vaincre n'importe quel adversaire à la force de mes poings.[n][w][e]

[msg MSG_041_0_0 [Inspecteur Kurosawa]]
[f 2 1][bup 1086 0 65535 65535 0 0][vp 1 0 0 49 0 0][f 5 21 0 1086]Tu n'as pas changé d'un poil...[n][w][e]

[msg MSG_042_0_0 [Inspecteur Kurosawa]]
[f 2 1][bup 1086 0 65535 65535 0 0][vp 1 0 0 50 0 0][f 5 21 0 1086]Dans tous les cas, ne te mets pas dans la panade.[n][w][e]
[f 2 1][bup 1086 0 65535 65535 0 0][vp 1 0 0 51 0 0][f 5 21 0 1086]Les gars qui te sont tombés dessus, je crois qu'ils font partie d'un gang qui sévit dans le coin ces derniers temps.[n][w][e]
[f 2 1][bup 1086 0 65535 65535 0 0][vp 1 0 0 52 0 0][f 5 21 0 1086]Fais attention. Mieux ne vaut pas te les mettre à dos, parce que s'ils te prennent pour cible, ils ne te lâcheront plus.[n][w][e]
[f 2 1][bup 1086 0 65535 65535 0 0][vp 1 0 0 53 0 0][f 5 21 0 1086]Bon, allez, il commence à faire tard. Vous feriez mieux de rentrer.[n][w][e]

[msg MSG_043_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 54 0 0]Avec tout ça on n'a pas pu aller manger.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 55 0 0]Mais Kurosawa a raison. On ferait mieux de rentrer. Désolé, je t'inviterai une prochaine fois.[n][w][e]

[msg MSG_044_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 56 0 0]Je vais aller courir un peu en rentrant. Tu veux venir ?[n][w][e]

[sel SEL_045_0_0 top]
[f 2 1]OK...[e]
[f 2 1]Non merci.[e]

[msg MSG_046_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 57 0 0]Bonne réponse. La nuit est tombée, alors faut faire attention aux voitures.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 58 0 0]Je pars devant. Contente-toi de me suivre à ton rythme ![n][w][e]

[msg MND_047_0_0]
[f 2 1]......[n][w][e]
[f 2 1]Je suis rentrée en courant au dortoir.[n][w][e]
[f 2 1]J'ai l'impression que mon énergie s'est améliorée après avoir autant couru...[n][w][e]

[msg SYS_HPUP_0_0]
[f 2 1]PV max augmentés de 5.[n][w][e]

[msg MSG_048_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 59 0 0]Tu es sûre ? Tu irais plus vite en courant.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 60 0 0]Bon, je pars devant. Fais attention en rentrant, OK ?[n][w][e]

[msg MND_049_0_0]
[f 2 1]Après le départ de Sanada, je suis retournée au dortoir.[n][w][e]
[f 2 1]Après avoir vu l'expression stoïque de Sanada, mon esprit semble plus affûté.[n][w][e]

[msg PFM_SPUP_0_0]
[f 2 1][vp 1 0 0 61 0 0]PC max augmentés de 3.[n][w][e]

