[msg MSG_000_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 1 65535 65535 0 0][vp 1 0 0 1 0 0]Tu as réussi à suivre mon entraînement strict. Je suis impressionné.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0][vp 0 0 0 2 0 0][f 4 23 0 4 0 25 25]......[n][w][e]

[msg MSG_001_0_0 [(SE) Akihiko Sanada]]
[f 2 1][vp 1 0 0 3 0 0]Hmm...[n][w][e]

[msg MSG_002_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 4 0 0]Alors, qu'est-ce que t'en penses ?[n][w][e]

[sel SEL_003_0_0 top]
[f 2 1]De quoi ?[e]
[f 2 1]Je suis épuisée.[e]

[msg MSG_004_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 5 0 0]Bon...[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 6 0 0]La raison pour laquelle je t'ai demandé de venir aujourd'hui, c'est parce que...[n][w][e]

[msg MSG_005_0_0 [Voix de brute]]
[f 2 1][vp 1 0 0 7 0 0][f 5 21 0 1001]On t'a enfin trouvé... Akihiko Sanada.[n][w][e]

[msg MSG_006_0_0 [Type baraqué]]
[f 2 1][vp 1 0 0 8 0 0][f 5 21 0 1001]On s'est bien amusé jusque là, mais aujourd'hui c'est la fin pour toi.[n][w][e]

[msg MSG_007_0_0 [Larbin]]
[f 2 1][vp 1 0 0 9 0 0][f 5 21 0 1002]T'inquiète, tu peux crier si tu veux. Personne viendra te sauver.[n][w][e]

[msg MSG_008_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 2 65535 65535 0 0][vp 1 0 0 10 0 0]Décidément, ces types ne veulent pas laisser tomber.[n][w][e]

[msg MSG_009_0_0 [Sous-fifre]]
[f 2 1][vp 1 0 0 11 0 0][f 5 21 0 1003]Vous pouvez pas nous échapper. Vous êtes coincés, ta copine trouillarde et toi.[n][w][e]

[msg MSG_010_0_0 [Type baraqué]]
[f 2 1][vp 1 0 0 12 0 0][f 5 21 0 1001]Vous vivez dans le dortoir du coin, pas vrai ? Enfin, c'est pas comme si j'en avais quelque chose à foutre...[n][w][e]

[msg MSG_011_0_0 [Larbin]]
[f 2 1][vp 1 0 0 13 0 0][f 5 21 0 1002]Ouais, on a vu des nanas là-bas, et un gamin aussi. J'espère qu'il va rien leur arriver, hein... Hahaha ![n][w][e]

[sel SEL_012_0_0 top]
[f 2 1]Vous n'allez pas vous en tirer comme ça.[e]
[f 2 1]Vous êtes des ordures.[e]

[msg MSG_013_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 14 0 0]Recule, [nl]...[n][w][e]
[f 2 1][bup 4 2 65535 65535 0 0][vp 1 0 0 15 0 0][f 4 23 0 4 2 25 25]Je vais te créer une occasion de t'enfuir.[n][w][e]

[msg MSG_014_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 2 65535 65535 0 0][vp 1 0 0 16 0 0]Si vous voulez vous en prendre à mes amis, vous allez d'abord devoir me passer sur le corps.[n][w][e]
[f 2 1][bup 4 2 65535 65535 0 0][vp 1 0 0 17 0 0]Allez, je vous attends.[n][w][e]

[msg MSG_015_0_0 [Type baraqué]]
[f 2 1][vp 1 0 0 18 0 0][f 5 21 0 1001]Argh...[n][w][e]

[msg MSG_016_0_0 [Type baraqué]]
[f 2 1][vp 1 0 0 19 0 0][f 5 21 0 1001]T-Tu sais ce qui arrive aux professionnels comme toi qui tabassent des amateurs ?[n][w][e]
[f 2 1][vp 1 0 0 20 0 0][f 5 21 0 1001]L'équipe de boxe sera suspendue, et tu seras exclu ! Ou pire, tu pourrais aller en prison et foutre toute ta vie en l'air.[n][w][e]
[f 2 1][vp 1 0 0 21 0 0][f 5 21 0 1001]C'est ce que tu veux ? Hein ?![n][w][e]

[msg MSG_017_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 22 0 0]C'est vrai... Je ne pourrais jamais faire ça à mon superviseur, ou au reste de mon équipe de boxe.[n][w][e]

[msg MSG_018_0_0 [Larbin]]
[f 2 1][vp 1 0 0 23 0 0][f 5 21 0 1002]Héhéhé...[n][w][e]

[msg MSG_019_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 2 65535 65535 0 0][vp 1 0 0 24 0 0]Mais... même si c'est ce que je ressens, je ne peux plus reculer maintenant.[n][w][e]
[f 2 1][bup 4 2 65535 65535 0 0][vp 1 0 0 25 0 0]J'en prendrai l'entière responsabilité, et le paierai pour le restant de ma vie s'il le faut.[n][w][e]
[f 2 1][bup 4 2 65535 65535 0 0][vp 1 0 0 26 0 0]Je protégerai ce qui compte à mes yeux... C'est à ça que servent ces poings.[n][w][e]

[msg MSG_020_0_0 [Sous-fifre]]
[f 2 1][vp 1 0 0 27 0 0][f 5 21 0 1003]Hein ? Qu'est-ce que tu racontes ?![n][w][e]

[msg MSG_021_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 4 65535 65535 0 0][vp 1 0 0 28 0 0]Oh, [nl]...[n][w][e]

[sel SEL_022_0_0 top]
[f 2 1]Occupons-nous d'eux.[e]
[f 2 1]C'est de la légitime défense.[e]

[msg MSG_023_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 1 65535 65535 0 0][vp 1 0 0 29 0 0]OK, très bien...[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 30 0 0][f 4 23 0 4 0 25 25]Je compte sur toi pour couvrir mes arrières. Fais juste attention à pas les blesser. Je suis sûr que ça te posera aucun problème.[n][w][e]

[msg MSG_024_0_0 [Type baraqué]]
[f 2 1][vp 1 0 0 31 0 0][f 5 21 0 1001]Petits merdeux ![n][w][e]

[msg MSG_025_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 32 0 0]Bon, on a l'air d'en avoir fini... Vu leur nombre, je dois avouer que ça n'a pas été facile.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 33 0 0]Tu n'as rien, [nl] ?[n][w][e]

[msg MSG_026_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 2 65535 65535 0 0][vp 1 0 0 34 0 0]Que je ne vous revois plus dans le coin ![n][w][e]
[f 2 1][bup 4 2 65535 65535 0 0][vp 1 0 0 35 0 0]Et si je vous prends encore à menacer un de mes amis, vous savez ce qui vous attend...[n][w][e]

[msg MSG_027_0_0 [Type baraqué]]
[f 2 1][vp 1 0 0 36 0 0]O-OK...[n][w][e]

[msg MSG_028_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 37 0 0]Allez, il commence à faire froid... et puis quelqu'un a peut-être déjà prévenu la police.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 38 0 0]Allons dans ma chambre pour l'instant.[n][w][e]

