[msg MSG_000_0_0 [Elizabeth]]
[f 2 1][bup 202 0 65535 65535 0 0][vp 1 0 0 1 0 0]Pardon de t'avoir fait venir dans un délai aussi court.[n][w][e]

[msg MSG_001_0_0 [Elizabeth]]
[f 2 1][bup 202 0 65535 65535 0 0][vp 1 0 0 2 0 0]En vérité... j'ai une faveur à te demander.[n][w][e]
[f 2 1][bup 202 1 65535 65535 0 0][vp 1 0 0 3 0 0][f 4 23 0 202 1 25 25]Je suis à la recherche d'une personne aux compétences exceptionnelles.[n][w][e]

[msg MSG_002_0_0 [Elizabeth]]
[f 2 1][bup 202 0 65535 65535 0 0][vp 1 0 0 4 0 0]Si tu as le temps, que dirais-tu d'effectuer mes requêtes ?[n][w][e]
[f 2 1][bup 202 0 65535 65535 0 0][vp 1 0 0 5 0 0]Je te demanderai parfois de m'escorter lors d'excursions spéciales.[n][w][e]

[msg MSG_003_0_0 [Elizabeth]]
[f 2 1][bup 202 1 65535 65535 0 0][vp 1 0 0 6 0 0]Tu seras bien évidemment récompensée pour chaque requête terminée.[n][w][e]
[f 2 1][bup 202 0 65535 65535 0 0][vp 1 0 0 7 0 0][f 4 23 0 202 0 25 25]Je compte sur ta coopération et j'espère vite te voir faire tes preuves.[n][w][e]

[msg MND_004_0_0 [Monologue intérieur]]
[f 2 1]Je peux désormais accepter les requêtes d'Elizabeth.[n][w][e]

