[msg MSG_000_0_0 [Femme douce]]
[f 2 1][vp 1 0 0 1 0 0][f 5 21 0 1]Oh, c'est toi.[n][w][e]
[f 2 1][vp 1 0 0 2 0 0][f 5 21 0 1]Tout se passe bien ?[n][w][e]

[msg MND_001_0_0]
[f 2 1]Comment lui parler de ce que ressent vraiment Koromaru ?[n][w][e]
[f 2 1]Je ne peux mentionner ni les Personae ni l'Heure sombre.[n][w][e]

[msg MSG_002_0_0 [Femme douce]]
[f 2 1][vp 1 0 0 3 0 0][f 5 21 0 1]Dis-moi, c'est à propos de Koromaru ?[n][w][e]

[sel SEL_003_0_0 top]
[f 2 1]Plus ou moins.[e]
[f 2 1]Il avait une raison...[e]

[msg MSG_004_0_0 [Femme douce]]
[f 2 1][vp 1 0 0 4 0 0][f 5 21 0 1]Héhé, ne t'inquiète pas.[n][w][e]
[f 2 1][vp 1 0 0 5 0 0][f 5 21 0 1]Je sais que Koromaru a ses raisons et ses problèmes.[n][w][e]
[f 2 1][vp 1 0 0 6 0 0][f 5 21 0 1]C'est vraiment un bon chien, si gentil.[n][w][e]

[msg MSG_005_0_0 [Femme douce]]
[f 2 1][vp 1 0 0 7 0 0][f 5 21 0 1]Ne t'en fais pas, je comprends.[n][w][e]
[f 2 1][vp 1 0 0 8 0 0][f 5 21 0 1]Parfois, les mots sont superflus. Tu ne crois pas ?[n][w][e]
[f 2 1][vp 1 0 0 9 0 0][f 5 21 0 1]C'est vraiment un bon chien, si gentil.[n][w][e]

[msg MSG_006_0_0 [Femme douce]]
[f 2 1][vp 1 0 0 10 0 0][f 5 21 0 1]Bref, moi, ça ira. Mais merci de ton attention.[n][w][e]

[msg MSG_007_0_0 [Femme douce]]
[f 2 1][vp 1 0 0 11 0 0][f 5 21 0 1]Quand je le vois à tes côtés...[n][w][e]
[f 2 1][vp 1 0 0 12 0 0][f 5 21 0 1]Il est comme quand il accompagnait le prêtre.[n][w][e]
[f 2 1][vp 1 0 0 13 0 0][f 5 21 0 1]Il doit vraiment te faire confiance, du fond de son cœur.[n][w][e]

[msg MSG_008_0_0 [Femme douce]]
[f 2 1][vp 1 0 0 14 0 0][f 5 21 0 1]Prends bien soin de Koromaru.[n][w][e]

[sel SEL_009_0_0 top]
[f 2 1]On sera toujours ensemble.[e]
[f 2 1]Je m'occuperai de lui jusqu'au bout.[e]

[msg MND_010_0_0]
[f 2 1]On dirait que Koromaru m'a entendu...[n][w][e]

[msg MSG_011_0_0 [Koromaru]]
[f 2 1][bup 9 0 65535 65535 0 0][vp 1 0 0 15 0 0]Rouaf ![n][w][e]

[msg MSG_012_0_0 [Femme douce]]
[f 2 1][vp 1 0 0 16 0 0][f 5 21 0 1]Koromaru a vraiment de la chance d'avoir tant d'amis merveilleux.[n][w][e]
[f 2 1][vp 1 0 0 17 0 0][f 5 21 0 1]Il faut bien les chérir, d'accord ?[n][w][e]

[msg MSG_013_0_0 [Koromaru]]
[f 2 1][bup 9 0 65535 65535 0 0][vp 1 0 0 18 0 0]Wouf ![n][w][e]

[msg MSG_014_0_0 [Femme douce]]
[f 2 1][vp 1 0 0 19 0 0][f 5 21 0 1]Donc, à partir de maintenant, tu seras dans ce dortoir.[n][w][e]
[f 2 1][vp 1 0 0 20 0 0][f 5 21 0 1]Il faudra absolument que je revienne te voir, alors. Héhé.[n][w][e]

[msg MSG_015_0_0 [Koromaru]]
[f 2 1][bup 9 0 65535 65535 0 0][vp 0 0 0 21 0 0]Arf, arf.[n][w][e]

[msg MND_016_0_0]
[f 2 1]Je sens que Koromaru me fait confiance.[n][w][e]

[msg MSG_017_0_0 [Koromaru]]
[f 2 1][bup 9 1 65535 65535 0 0][vp 1 0 0 22 0 0]Arf... Rouaf ![n][w][e]

[msg MND_018_0_0]
[f 2 1]J'ai emmené Koromaru se promener avant de rentrer. Il était fou de joie.[n][w][e]

[msg PFM_SPEEDUP_0_0]
[f 2 1][vp 1 0 0 23 0 0]L'agilité de la Persona de Koromaru, [clr 1]Cerbère[clr 27], a été augmentée de 3.[n][w][e]

