[msg MSG_000_0_0 [Elizabeth]]
[f 2 1][bup 202 4 65535 65535 0 0][vp 1 0 0 1 0 0]Voici donc ta chambre... Je n'en avais pas vu beaucoup jusqu'à présent.[n][w][e]
[f 2 1][bup 202 0 65535 65535 0 0][vp 0 0 0 2 0 0][f 4 23 0 202 0 25 25]......[n][w][e]

[msg MSG_000_5_0 [Elizabeth]]
[f 2 1][bup 202 0 65535 65535 0 0][vp 1 0 0 3 0 0]Si je puis me permettre... quand j'ai demandé à visiter ta chambre...[n][w][e]
[f 2 1][bup 202 3 65535 65535 0 0][vp 1 0 0 4 0 0][f 4 23 0 202 3 25 25]Ma requête t'a-t-elle paru suspecte ?[n][w][e]

[sel SEL_001_0_0 top]
[f 2 1]Oui, un peu.[e]
[f 2 1]Pas vraiment.[e]

[msg MSG_002_0_0 [Elizabeth]]
[f 2 1][bup 202 3 65535 65535 0 0][vp 1 0 0 5 0 0]En vérité... je voulais te parler de quelque chose.[n][w][e]

[msg MSG_003_0_0 [Elizabeth]]
[f 2 1][bup 202 3 65535 65535 0 0][vp 1 0 0 6 0 0]Je vois...[n][w][e]
[f 2 1][bup 202 0 65535 65535 0 0][vp 1 0 0 7 0 0][f 4 23 0 202 0 25 25]En vérité, je voulais te parler de quelque chose.[n][w][e]

[msg MSG_004_0_0 [Elizabeth]]
[f 2 1][bup 202 0 65535 65535 0 0][vp 1 0 0 8 0 0]Lors de mes incursions dans ton monde, j'ai fait de nombreuses découvertes.[n][w][e]
[f 2 1][bup 202 0 65535 65535 0 0][vp 1 0 0 9 0 0]Chacune de ces sorties est pour moi un souvenir inoubliable, telles des gemmes brillantes et polies.[n][w][e]

[msg MSG_004_5_0 [Elizabeth]]
[f 2 1][bup 202 1 65535 65535 0 0][vp 1 0 0 10 0 0]Se promener dans les rues bondées de Port Island, déguster la cuisine locale...[n][w][e]
[f 2 1][bup 202 1 65535 65535 0 0][vp 1 0 0 11 0 0]Passer du temps au sanctuaire, visiter ton lycée le temps d'une journée...[n][w][e]
[f 2 1][bup 202 0 65535 65535 0 0][vp 1 0 0 12 0 0][f 4 23 0 202 0 25 25]C'est là que j'ai compris...[n][w][e]

[msg MSG_005_0_0 [Elizabeth]]
[f 2 1][bup 202 0 65535 65535 0 0][vp 1 0 0 13 0 0]Inconsciemment, je demandais à visiter des endroits occupant une place de plus en plus centrale dans ta vie.[n][w][e]
[f 2 1][bup 202 0 65535 65535 0 0][vp 1 0 0 14 0 0]Et aujourd'hui, j'ai décidé de voir l'endroit qui me permettrait d'en apprendre le plus sur toi.[n][w][e]
[f 2 1][bup 202 0 65535 65535 0 0][vp 1 0 0 15 0 0]C'est pourquoi j'ai demandé à visiter ta chambre.[n][w][e]

[msg MSG_006_0_0 [Elizabeth]]
[f 2 1][bup 202 0 65535 65535 0 0][vp 1 0 0 16 0 0]Si je puis me permettre cette audace...[n][w][e]

[msg MSG_007_0_0 [Elizabeth]]
[f 2 1][bup 202 1 65535 65535 0 0][vp 1 0 0 17 0 0]Te rappelles-tu le jour où tu m'as fait visiter ton lycée ?[n][w][e]
[f 2 1][bup 202 1 65535 65535 0 0][vp 1 0 0 18 0 0]À un moment, je t'ai révélé que je m'étais sentie "comblée" quand je t'avais touchée.[n][w][e]

[sel SEL_008_0_0 top]
[f 2 1]Je m'en souviens.[e]
[f 2 1]Ça ne me dit rien.[e]

[msg MSG_009_0_0 [Elizabeth]]
[f 2 1][bup 202 0 65535 65535 0 0][vp 1 0 0 19 0 0]Je n'avais jamais ressenti cela avant.[n][w][e]

[msg MSG_010_0_0 [Elizabeth]]
[f 2 1][bup 202 3 65535 65535 0 0][vp 0 0 0 20 0 0]......[n][w][e]
[f 2 1][bup 202 0 65535 65535 0 0][vp 1 0 0 21 0 0][f 4 23 0 202 0 25 25]Je n'avais jamais ressenti cela avant.[n][w][e]

[msg MSG_011_0_0 [Elizabeth]]
[f 2 1][bup 202 3 65535 65535 0 0][vp 1 0 0 22 0 0]Je me suis demandé pourquoi j'étais si comblée.[n][w][e]
[f 2 1][bup 202 0 65535 65535 0 0][vp 1 0 0 23 0 0][f 4 23 0 202 0 25 25]Et maintenant que je suis ici, j'ai enfin trouvé la réponse.[n][w][e]

[msg MSG_012_0_0 [Elizabeth]]
[f 2 1][bup 202 0 65535 65535 0 0][vp 1 0 0 24 0 0]Je pense que c'est parce que j'ai eu la chance de voir le monde de ton point de vue.[n][w][e]
[f 2 1][bup 202 1 65535 65535 0 0][vp 1 0 0 25 0 0][f 4 23 0 202 1 25 25]Nous, les résidents de la Chambre de velours, attendons avec impatience nos "invités"...[n][w][e]

[msg MSG_012_5_0 [Elizabeth]]
[f 2 1][bup 202 1 65535 65535 0 0][vp 1 0 0 26 0 0]Leur arrivée représente notre seul lien avec le monde extérieur et nous donne une raison d'être.[n][w][e]
[f 2 1][bup 202 0 65535 65535 0 0][vp 1 0 0 27 0 0][f 4 23 0 202 0 25 25]Quand je suis avec toi... je peux avoir tout cela rien que pour moi.[n][w][e]

[sel SEL_013_0_0 top]
[f 2 1]Je crois que je comprends.[e]
[f 2 1]J'ai du mal à saisir.[e]

[msg MSG_014_0_0 [Elizabeth]]
[f 2 1][bup 202 0 65535 65535 0 0][vp 1 0 0 28 0 0]Je vais être plus claire.[n][w][e]
[f 2 1][bup 202 0 65535 65535 0 0][vp 1 0 0 29 0 0]J'ignore les coutumes de ton monde, et j'ai sûrement agi de façon extravagante à plusieurs reprises.[n][w][e]
[f 2 1][bup 202 1 65535 65535 0 0][vp 1 0 0 30 0 0][f 4 23 0 202 1 25 25]Cependant... même moi, je connais les implications d'inviter quelqu'un dans sa propre chambre.[n][w][e]

[msg MSG_015_0_0 [Elizabeth]]
[f 2 1][bup 202 3 65535 65535 0 0][vp 1 0 0 31 0 0]Si cela ne te dérange pas...[n][w][e]
[f 2 1][bup 202 3 65535 65535 0 0][vp 1 0 0 32 0 0]J'aimerais... que tu acceptes de me guider dans cette expérience.[n][w][e]

[sel SEL_016_0_0 top]
[f 2 1]Accepter avec audace[e]
[f 2 1]Refuser poliment[e]

[msg MSG_017_0_0 [Elizabeth]]
[f 2 1][bup 202 0 65535 65535 0 0][vp 1 0 0 33 0 0]Merci.[n][w][e]

[msg MSG_018_0_0 [Elizabeth]]
[f 2 1][bup 202 3 65535 65535 0 0][vp 0 0 0 34 0 0]......[n][w][e]
[f 2 1][bup 202 0 65535 65535 0 0][vp 1 0 0 35 0 0][f 4 23 0 202 0 25 25]Je comprends.[n][w][e]
[f 2 1][bup 202 0 65535 65535 0 0][vp 1 0 0 36 0 0]Je ne réitérerai plus cette demande.[n][w][e]

[msg MND_019_0_0]
[f 2 1]......[n][w][e]
[f 2 1]J'ai passé du temps seule avec Elizabeth.[n][w][e]

