[msg MSG_000_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 1 65535 65535 0 0][vp 1 0 0 1 0 0]Bonsoir.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 2 0 0][f 4 23 0 222 0 25 25]Je viens prendre des nouvelles de Koromaru. Ça ira, tu crois ?[n][w][e]

[sel SEL_001_0_0 top]
[f 2 1]Ça va aller.[e]
[f 2 1]Je ne suis pas sûre.[e]
[f 2 1]Il est trop tôt pour le dire.[e]

[msg MSG_002_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 1 65535 65535 0 0][vp 1 0 0 3 0 0]Heureux de l'entendre.[n][w][e]
[f 2 1][bup 222 1 65535 65535 0 0][vp 1 0 0 4 0 0]Vu sa réputation de loyauté, je ne m'inquiétais pas trop.[n][w][e]

[msg MSG_003_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 5 0 0]Ne sois pas trop dure avec toi-même. Je ferai mon possible pour vous soutenir.[n][w][e]
[f 2 1][bup 222 4 65535 65535 0 0][vp 1 0 0 6 0 0][f 4 23 0 222 4 25 25]Ou alors tu es plutôt chats que chiens ? Là, je ne vois pas quoi faire...[n][w][e]

[msg MSG_004_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 7 0 0]C'est juste, je suppose.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 8 0 0]Pas de précipitation. Vous aurez tout le temps pour faire connaissance.[n][w][e]

[msg MSG_005_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 9 0 0]Si tu as le moindre souci, n'hésite pas à m'en parler.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 10 0 0]C'est ma responsabilité, comme c'est moi qui ai demandé qu'il rejoigne l'équipe.[n][w][e]

[msg MSG_006_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 1 0 0 11 0 0]Moi, je suis à 100 % pour l'accueillir ![n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0][vp 1 0 0 12 0 0]Il aura même droit à des leçons du maître : moi ![n][w][e]

[msg MSG_007_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 13 0 0]Je suis sûre que Koro est déjà plus discipliné que toi.[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 14 0 0]Si on te disait "assis", tu saurais rester sans bouger ?[n][w][e]

[msg MSG_008_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 65535 65535 0 0][vp 1 0 0 15 0 0]Me compare pas à un chien s'te plaît ![n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0][vp 1 0 0 16 0 0][f 4 23 0 3 0 25 25]Je suis discipliné ! Je sais me tenir... Je crois ?[n][w][e]

[msg MSG_009_0_0 [Yukari Takeba]]
[f 2 1][bup 2 6 65535 65535 0 0][vp 1 0 0 17 0 0]Oui, on est tous convaincus.[n][w][e]

[msg MSG_010_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 1 0 0 18 0 0]Ouais... À part ça, M. le directeur, euh... concernant ces cours d'été...[n][w][e]

[msg MSG_011_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 19 0 0]Ah oui, le projet de Kirijo.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 20 0 0]L'idée m'a paru bonne et je l'ai approuvée.[n][w][e]

[msg MSG_012_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 65535 65535 0 0][vp 1 0 0 21 0 0]Non ! Pourquoi vous avez accepté ?[n][w][e]

[msg MSG_013_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 22 0 0]Ça ne me regardait pas ?[n][w][e]

[msg MSG_014_0_0 [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0][vp 1 0 0 23 0 0]Adieu, amour d'été dont je rêvais... Tu t'évanouis dans la lumière du soleil...[n][w][e]
[f 2 1][bup 3 3 65535 65535 0 0][vp 1 0 0 24 0 0]Adieu, toi ma belle citadine... qui m'attendait sur le sable...[n][w][e]

[msg MSG_015_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 25 0 0]La ville ou la plage ? Faut choisir ![n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 26 0 0]Sans les cours, tu n'aurais fait que glander vers la gare.[n][w][e]
[f 2 1][bup 2 2 65535 65535 0 0][vp 1 0 0 27 0 0][f 4 23 0 2 2 25 25]Tu ferais mieux d'accepter ton destin.[n][w][e]

[msg MSG_016_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 28 0 0]Au fait, M. le directeur...[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 29 0 0]Vous alliez nous dire quelque chose, avant que [nl] arrive.[n][w][e]

[msg MSG_017_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 30 0 0]Hmm ? Ah, c'est vrai.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 31 0 0]Je me mêle de ce qui ne me regarde pas, et en plus, j'ai une requête.[n][w][e]

[msg MSG_018_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 32 0 0]Vous avez tous un instant ?[n][w][e]

[msg MSG_019_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 33 0 0]Je crois qu'il est temps que vous passiez une visite médicale de routine.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 34 0 0]Vous savez où est le Tatsumi Memorial Hospital ?[n][w][e]

[msg MSG_020_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 35 0 0]Ah, c'est là que Sanada a été soigné.[n][w][e]

[msg MSG_021_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 36 0 0]Vous avez beaucoup combattu ces derniers temps, il est important de contrôler votre forme physique.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 37 0 0]Il faut vérifier que vos Personae n'en demandent pas trop à votre corps.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 38 0 0]Vous pourrez passer à l'hôpital en rentrant de vos cours d'été, ce n'est pas loin.[n][w][e]

[msg MSG_022_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 39 0 0]Je comprends. C'est juste... un peu soudain.[n][w][e]

[msg MSG_023_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 1 65535 65535 0 0][vp 1 0 0 40 0 0]Ne t'en fais pas. Comme on dit : mieux vaut prévenir que guérir ![n][w][e]

[msg MSG_024_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 41 0 0]Vous passerez votre examen individuellement, un par jour.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 42 0 0]Décidez entre vous de qui passera quand.[n][w][e]

[msg MSG_025_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 1 65535 65535 0 0][vp 1 0 0 43 0 0]Au moins, pour ces examens-là, vous n'aurez pas à réviser. Haha ![n][w][e]

[msg MSG_026_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 1 65535 65535 0 0][vp 1 0 0 44 0 0]Ramenez peut-être vos evokers... si jamais c'est le coup de feu ! Hahaha ![n][w][e]

