[msg MSG_000_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 51 65535 0 0][vp 1 0 0 1 0 0]Hé, elle est là ![n][w][e]
[f 2 1][bup 3 1 51 65535 0 0][vp 1 0 0 2 0 0]On était super inquiets pour toi.[n][w][e]

[sel SEL_001_0_0 top]
[f 2 1]Désolée pour l'attente.[e]
[f 2 1]Contente que vous alliez bien.[e]

[msg MSG_002_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 51 65535 0 0][vp 1 0 0 3 0 0]Je pense qu'on devrait plus aller à Tartare comme ça.[n][w][e]

[msg MSG_003_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 51 65535 0 0][vp 1 0 0 4 0 0]Au fait, t'as entendu une voix quand t'étais là-bas ?[n][w][e]
[f 2 1][bup 3 0 51 65535 0 0][vp 1 0 0 5 0 0]Euh, un peu comme...[n][w][e]

[msg MSG_004_0_0 [Voix mystérieuse]]
[f 2 1][vp 1 0 0 6 0 0]Qui est là ? Vous êtes... humains ?[n][w][e]

[msg MSG_005_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 51 65535 0 0][vp 1 0 0 7 0 0]Ça ! Cette voix-là ![n][w][e]
[f 2 1][bup 3 4 51 65535 0 0][vp 1 0 0 8 0 0]Minute, elle venait pas de derrière nous ?[n][w][e]

[msg MSG_005_5_0 [Junpei Iori]]
[f 2 1][cut 3 4 0][e]

[msg MSG_006_0_0 [Fille pâle]]
[f 2 1][bup 6 3 2 65535 0 0][vp 1 0 0 9 0 0]Ah...[n][w][e]

[msg MSG_007_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 51 65535 0 0][vp 1 0 0 10 0 0]Tu es Fuuka Yamagishi ?[n][w][e]

[msg MSG_008_0_0 [Fille pâle]]
[f 2 1][bup 6 4 2 65535 0 0][vp 1 0 0 11 0 0]O-Oui ![n][w][e]

[msg MSG_009_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 51 65535 0 0][vp 1 0 0 12 0 0]Ouf, t'es en vie ! C'est génial ![n][w][e]
[f 2 1][bup 3 1 51 65535 0 0][vp 1 0 0 13 0 0]Ne crains rien ! La cavalerie est là ![n][w][e]

[msg MSG_010_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 1 51 65535 0 0][vp 1 0 0 14 0 0]Ravi de voir que tu vas bien.[n][w][e]
[f 2 1][bup 4 0 51 65535 0 0][vp 1 0 0 15 0 0][f 4 23 0 4 0 25 25]Viens avec nous.[n][w][e]

[msg MSG_011_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 10 2 65535 0 0][vp 1 0 0 16 0 0]Merci beaucoup... Je...[n][w][e]

[sel SEL_012_0_0 top]
[f 2 1]Il n'y a plus rien à craindre.[e]
[f 2 1]Ça va ?[e]

[msg MSG_012_5_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 10 2 65535 0 0][vp 1 0 0 17 0 0]O-Oui, ça va. Désolée, je suis tellement soulagée.[n][w][e]

[msg MSG_013_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 1 51 65535 0 0][vp 1 0 0 18 0 0]On a pris la bonne décision. Je vais essayer de contacter Mitsuru.[n][w][e]

[msg MSG_014_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 2 65535 0 0][vp 1 0 0 19 0 0]Quel est cet endroit ? J'étais au lycée et la seconde d'après...[n][w][e]

[msg MSG_015_0_0 [Junpei Iori]]
[f 2 1][bup 3 3 51 65535 0 0][vp 1 0 0 20 0 0]Euh... c'est une longue histoire... On t'expliquera quand on sera sortis de là.[n][w][e]

[msg MSG_016_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 51 65535 0 0][vp 1 0 0 21 0 0]Mitsuru, tu m'entends ?[n][w][e]
[f 2 1][bup 4 0 51 65535 0 0][vp 0 0 0 22 0 0]...[n][w][e]
[f 2 1][bup 4 3 51 65535 0 0][vp 1 0 0 23 0 0]C'est mauvais. J'entends que des grésillements.[n][w][e]

[msg MSG_017_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 51 65535 0 0][vp 1 0 0 24 0 0]Oh, tu es blessée ?[n][w][e]
[f 2 1][bup 3 0 51 65535 0 0][vp 1 0 0 25 0 0]Tu as dû voir les monstres qui se promènent, n'est-ce pas ?[n][w][e]

[msg MSG_018_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 2 65535 0 0][vp 1 0 0 26 0 0]Il y a donc bien quelque chose de dangereux ici.[n][w][e]
[f 2 1][bup 6 3 2 65535 0 0][vp 1 0 0 27 0 0]J'ai fait en sorte qu'ils ne me trouvent pas.[n][w][e]

[msg MSG_019_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 4 51 65535 0 0][vp 1 0 0 28 0 0]Attends, tu les as évités tout ce temps ?[n][w][e]
[f 2 1][bup 4 4 51 65535 0 0][vp 1 0 0 29 0 0]Comment c'est possible ?[n][w][e]

[msg MSG_020_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 2 65535 0 0][vp 1 0 0 30 0 0]C'est difficile à décrire, mais j'arrive à percevoir où ils sont...[n][w][e]

[msg MSG_021_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 51 65535 0 0][vp 1 0 0 31 0 0]Comment ça ? T'es voyante ou quoi ?[n][w][e]

[msg MSG_022_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 51 65535 0 0][vp 1 0 0 32 0 0]Elle a le même pouvoir que Mitsuru.[n][w][e]
[f 2 1][bup 4 0 51 65535 0 0][vp 1 0 0 33 0 0]En fait, elle pourrait être plus puissante.[n][w][e]
[f 2 1][bup 4 0 51 65535 0 0][vp 1 0 0 34 0 0]D'abord, la Persona de Mitsuru a toujours été plus axée combat.[n][w][e]

[msg MSG_023_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 2 65535 0 0][vp 1 0 0 35 0 0]"Persona"... ?[n][w][e]

[msg MSG_024_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 51 65535 0 0][vp 1 0 0 36 0 0]Prends ça.[n][w][e]

[msg MSG_025_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 4 2 65535 0 0][vp 1 0 0 37 0 0]Hein ? Attendez, c'est... c'est un pistolet ?![n][w][e]

[msg MSG_026_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 51 65535 0 0][vp 1 0 0 38 0 0]Une sorte de porte-bonheur. Elle ne tire pas de vraies balles.[n][w][e]

[msg MSG_027_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 2 65535 0 0][vp 1 0 0 39 0 0]Euh... OK...[n][w][e]

[msg MSG_028_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 51 65535 0 0][vp 1 0 0 40 0 0]Allez, on bouge.[n][w][e]

