[msg MSG_000_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 1 0 0]Mmh, c'est délicieux ! Heureusement que j'ai choisi le même plat que toi, [nl].[n][w][e]

[msg MSG_001_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 2 0 0]Oh, je me disais : manger du poisson, ça me rappelle l'océan. Pas toi ?[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 3 0 0]Vivre sur la côte fait partie de notre vie. On passe même nos vacances à la plage.[n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 4 0 0][f 4 23 0 2 1 25 25]Quand tout sera fini, on devrait partir ailleurs... à la montagne, par exemple.[n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 5 0 0]On pourrait déjeuner en plein air, voir un cerf ou d'autres animaux. T'en dis quoi ?[n][w][e]

[sel SEL_002_0_0 top]
[f 2 1]Bonne idée.[e]
[f 2 1]Allons-y avec tous les autres.[e]
[f 2 1]Allons-y rien que nous deux.[f 2 9 1 1 344][e]
[f 2 1]Non merci.[e]

[msg MSG_003_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 6 0 0][f 5 13 7 15 2]Oui, hein ?[n][w][e]

[msg MSG_004_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 7 0 0]D'accord, alors je vais nous préparer le déjeuner ![n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 8 0 0]Je n'en ai peut-être pas l'air, mais je cuisine bien ! Tu vas voir ![n][w][e]

[msg MSG_005_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 9 0 0][f 5 13 7 5 2]Hmm... mais oui, pourquoi pas ? On le mérite tous, après tout.[n][w][e]

[msg MSG_006_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 10 0 0]D'accord, alors je vais nous préparer le déjeuner ![n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 11 0 0]Je n'en ai peut-être pas l'air, mais je cuisine bien ! Tu vas voir ![n][w][e]

[msg MSG_007_0_0 [Yukari Takeba]]
[f 2 1][bup 2 4 65535 65535 0 0][vp 1 0 0 12 0 0][f 5 13 7 15 2]Hé, qu'est-ce qui te prend, tout à coup ?[n][w][e]
[f 2 1][bup 2 4 65535 65535 0 0][vp 1 0 0 13 0 0]Rien que nous deux ? C'est... pas ce que j'avais en tête.[n][w][e]
[f 2 1][bup 2 4 65535 65535 0 0][vp 1 0 0 14 0 0]C'est pas que je ne veux pas, c'est juste que... je ne suis pas encore prête.[n][w][e]
[f 2 1][bup 2 4 65535 65535 0 0][vp 1 0 0 15 0 0]Oh, mais qu'est-ce que je raconte ?[n][w][e]

[msg MSG_008_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 16 0 0]En tout cas... ça me plairait bien qu'on sorte quelque part, toutes les deux. Je pourrais même nous faire à déjeuner ![n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 17 0 0][f 4 23 0 2 1 25 25]Je n'en ai peut-être pas l'air, mais je cuisine bien ! Tu vas voir ![n][w][e]

[msg MSG_009_0_0 [Yukari Takeba]]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 18 0 0]Hein ? Pourquoi pas ?[n][w][e]

[msg MSG_010_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 19 0 0]Si tu t'inquiètes pour le déjeuner, je te rassure : c'est moi qui cuisine ![n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 20 0 0][f 4 23 0 2 0 25 25]Je n'en ai peut-être pas l'air, mais je cuisine bien ! Tu vas voir ![n][w][e]

[msg MSG_011_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 21 0 0]Héhé, ça remonte à loin, la dernière fois qu'on a parlé de partir en vacances ensemble. Rien que d'y penser, je kiffe ![n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 22 0 0][f 4 23 0 2 0 25 25]Je ne sais pas trop comment le tourner, mais... quand je suis avec toi, [nl]...[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 23 0 0]Je ne me sens plus aussi seule.[n][w][e]

[msg MSG_012_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 24 0 0]J'ai des amis... et puis tous les autres, au dortoir, mais...[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 25 0 0][f 4 23 0 2 3 25 25]En temps normal, j'ai l'impression que mon vrai moi est piégé au plus profond de mon être.[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 26 0 0]J'ai tendance à mettre de la distance avec les autres, sans m'en rendre compte. C'est peut-être à cause de ma famille...[n][w][e]

[msg MSG_012_3_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 27 0 0]Mais ça a changé, dernièrement...[n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 28 0 0][f 4 23 0 2 1 25 25]Et je crois que c'est grâce à toi, [nl].[n][w][e]

[msg MND_013_0_0]
[f 2 1]Yukari me fait confiance.[n][w][e]
[f 2 1]J'ai l'impression que nous nous sommes rapprochées...[n][w][e]

[msg MSG_014_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 29 0 0]Bon, on s'est régalées, mais il se fait tard.[n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 30 0 0]On rentre ?[n][w][e]

[msg MND_015_0_0]
[f 2 1]J'ai décidé de retourner au dortoir...[n][w][e]

