[msg MND_000_0_0]
[f 2 1]On dirait que Sanada n'est pas encore arrivé...[n][w][e]

[msg MSG_001_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 1 0 0]Désolé, je suis en retard. J'ai eu un petit problème en route.[n][w][e]

[msg MSG_002_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 2 0 0]OK, c'est parti. Je vais avoir besoin de toi, si ça te dérange pas ?[n][w][e]

[msg MSG_003_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 3 0 0]Je vais faire des pancakes. Tu penses pouvoir m'aider ?[n][w][e]
[f 2 1][bup 4 1 65535 65535 0 0][vp 1 0 0 4 0 0][f 4 23 0 1 1 25 25]J'ai eu soudainement envie d'en faire... On en mangeait tout le temps à l'orphelinat.[n][w][e]
[f 2 1][bup 4 1 65535 65535 0 0][vp 1 0 0 5 0 0][f 4 23 0 1 1 25 25]Je sais qu'ils en vendent des surgelés maintenant, mais rien ne vaut des pancakes faits maison, pas vrai ?[n][w][e]

[sel SEL_004_0_0 top]
[f 2 1]Pourquoi maintenant ?[e]
[f 2 1]Tu en fais un sacré paquet...[e]

[msg MSG_005_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 6 0 0]J'ai besoin d'une raison pour ça ? J'ai juste eu envie d'en faire, c'est tout.[n][w][e]

[msg MSG_006_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 7 0 0]Tu penses ? Je me disais juste qu'il valait mieux en faire trop que pas assez.[n][w][e]

[msg MSG_007_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 8 0 0]Bon, mettons-nous au travail. OK, alors, pour commencer...[n][w][e]

[msg MSG_008_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 9 0 0]Euh... On doit commencer par quoi ?[n][w][e]

[msg MSG_009_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 10 0 0]D'après la recette, il faut beaucoup de beurre, je crois, et il faut réguler la température en utilisant un torchon humide...[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 11 0 0]Mais si on utilise un torchon dans la poêle, il ne va pas brûler ?[n][w][e]

[sel SEL_010_0_0 top]
[f 2 1]Tu veux que je m'en occupe ?[e]
[f 2 1]S'il te plaît, laisse-moi faire...[e]

[msg MSG_011_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 12 0 0]Tu es sûre ? Merci. Je n'ai pas la moindre idée de comment cuisiner quoi que ce soit en dehors de mes produits protéinés...[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 13 0 0]Je peux casser les œufs et mélanger la pâte. Je préfère te laisser t'occuper de la cuisson à proprement parler.[n][w][e]

[msg MSG_012_0_0 [Akihiko Sanada (SE)]]
[f 2 1][vp 1 0 0 14 0 0]Oooh, alors c'est à ça que sert le torchon.[n][w][e]

[msg MSG_013_0_0 [Akihiko Sanada (SE)]]
[f 2 1][vp 1 0 0 15 0 0]On pourrait peut-être ajouter de la protéine en poudre...[n][w][e]

[msg MSG_014_0_0 [Akihiko Sanada (SE)]]
[f 2 1][vp 1 0 0 16 0 0]Hé, me regarde pas comme ça.[n][w][e]

[msg MSG_015_0_0 [Akihiko Sanada]]

[msg MSG_016_0_0 [Akihiko Sanada]]

[msg MSG_017_0_0 [Akihiko Sanada (SE)]]
[f 2 1][vp 1 0 0 19 0 0]Oh, je ferais mieux d'aller chercher les assiettes.[n][w][e]

[msg MSG_018_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 1 65535 65535 0 0][vp 1 0 0 20 0 0]OK, je pense que ça devrait suffire.[n][w][e]

[msg MSG_019_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 21 0 0]Oh, regardez ça ![n][w][e]

[msg MSG_020_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 22 0 0]Ouah, regardez tous ces pancakes ! Je me disais bien que quelque chose sentait bon.[n][w][e]

[msg MSG_021_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 1 65535 65535 0 0][vp 1 0 0 23 0 0]Ouais, juste une minute... On pourra manger une fois que j'aurai tout apporté.[n][w][e]
[f 2 1][bup 4 1 65535 65535 0 0][vp 1 0 0 24 0 0]Est-ce que vous pourriez appeler tout le monde ? Et n'oubliez pas Amada.[n][w][e]

[msg MSG_022_0_0 [Yukari Takeba (SE)]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 25 0 0]Ouaaais ![n][w][e]

[msg MSG_023_0_0 [Fuuka (SE)]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 26 0 0]Youhou ![n][w][e]

[msg MSG_024_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 1 0 0 27 0 0]Ouah... On dirait Tartare, mais en pancakes ![n][w][e]

[msg MSG_025_0_0 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 1 0 0 28 0 0]Vous avez fait tout ça juste tous les deux ?[n][w][e]

[msg MSG_026_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 1 65535 65535 0 0][vp 1 0 0 29 0 0]Ouais, même si [nl] a presque tout fait. J'avais envie d'en manger aujourd'hui, mais on en a peut-être trop fait...[n][w][e]
[f 2 1][bup 4 1 65535 65535 0 0][vp 1 0 0 30 0 0]J'adore les pancakes, mais je n'arriverai jamais à manger tout ça. Si vous pouviez en prendre quelques-uns, ça m'arrangerait.[n][w][e]

[msg MSG_027_0_0 [Ken Amada]]
[f 2 1][bup 8 1 65535 65535 0 0][vp 1 0 0 31 0 0]Alors comme ça, tu aimes les pancakes aussi, Sanada...[n][w][e]
[f 2 1][bup 8 1 65535 65535 0 0][vp 1 0 0 32 0 0]Merci ! J'ai hâte d'en manger ![n][w][e]

[msg MSG_028_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 33 0 0]Je vais préparer du thé. Je pense en avoir un qui irait à merveille avec ces pancakes.[n][w][e]

[msg MSG_029_0_0 [Aigis]]
[f 2 1][bup 7 1 65535 65535 0 0][vp 1 0 0 34 0 0]C'est l'heure des pancakes ! Hmm... C'est bien ainsi qu'on dit, n'est-ce pas ?[n][w][e]

[msg MSG_030_0_0 [Koromaru]]
[f 2 1][bup 9 1 65535 65535 0 0][vp 1 0 0 35 0 0]Ouaf ![n][w][e]

[msg MSG_031_0_0 [Ken Amada (SE)]]
[f 2 1][vp 1 0 0 36 0 0]Ils sont tellement bons ! Je pourrais en manger toute la journée.[n][w][e]

[msg MSG_032_0_0 [Akihiko Sanada (SE)]]
[f 2 1][vp 1 0 0 37 0 0]Ah ouais ? Ravi de l'entendre.[n][w][e]

[msg MSG_033_0_0 [Fuuka Yamagishi (SE)]]
[f 2 1][vp 1 0 0 38 0 0]J'en ai le sourire aux lèvres ![n][w][e]

[msg MSG_034_0_0 [Junpei Iori (SE)]]
[f 2 1][vp 1 0 0 39 0 0]Ce ne serait pas plutôt... les pancakes que t'as aux lèvres ?[n][w][e]

[msg MSG_035_0_0 [Yukari Takeba (SE)]]
[f 2 1][vp 1 0 0 40 0 0]Euh... Tu veux remplacer le directeur, c'est ça ?[n][w][e]
[f 2 1][vp 1 0 0 41 0 0]Blague à part, ils sont super bons ![n][w][e]

[msg MSG_036_0_0 [Mitsuru Kirijo (SE)]]
[f 2 1][vp 1 0 0 42 0 0]La cuisson est absolument parfaite... Mes compliments au chef.[n][w][e]

[msg MSG_037_0_0 [Aigis (SE)]]
[f 2 1][vp 1 0 0 43 0 0]Quelle est la différence entre les pancakes et les crêpes ?[n][w][e]

[msg MSG_038_0_0 [Koromaru (SE)]]
[f 2 1][vp 1 0 0 44 0 0]Ouaf ! Ouaf ![n][w][e]

[msg MSG_039_0_0 [Ken Amada]]
[f 2 1][bup 8 1 65535 65535 0 0][vp 1 0 0 45 0 0]Merci encore pour ces pancakes. Ils étaient délicieux.[n][w][e]
[f 2 1][bup 8 1 65535 65535 0 0][vp 1 0 0 46 0 0]J'ai l'impression qu'ils ont été faits avec beaucoup de soin.[n][w][e]
[f 2 1][bup 8 1 65535 65535 0 0][vp 1 0 0 47 0 0]Si jamais tu veux en refaire, j'aimerais bien t'aider, moi aussi ![n][w][e]

[msg MSG_040_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 1 65535 65535 0 0][vp 1 0 0 48 0 0]Malgré la quantité, ils n'ont pas fait long feu, dis donc...[n][w][e]

[msg MSG_041_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 49 0 0]La cuisine, ce n'est pas mon fort.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 50 0 0]Je connais quelqu'un qui me dirait : "Si pour toi, de la protéine en poudre c'est un ingrédient, t'as rien à foutre en cuisine !"[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 51 0 0]D'habitude, je me contente de regarder quelqu'un cuisiner, donc je n'ai jamais vraiment appris à me débrouiller à ce niveau.[n][w][e]
[f 2 1][bup 4 1 65535 65535 0 0][vp 1 0 0 52 0 0][f 4 23 0 1 1 25 25]Bref, merci de m'avoir aidé aujourd'hui. J'espère que ça aura fait plaisir à tout le monde.[n][w][e]

[sel SEL_042_0_0 top]
[f 2 1]Tu avais prévu ça depuis le début ?[e]
[f 2 1]Pourquoi tu as décidé de faire ça ?[e]

[msg MSG_043_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 53 0 0]Ouais, on peut dire ça.[n][w][e]

[msg MSG_044_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 54 0 0]Ils faisaient ce genre de trucs à l'orphelinat. Je voulais juste revivre ce genre de moments.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 55 0 0]Ma sœur pleurait souvent, mais les pancakes lui redonnaient tout le temps le sourire.[n][w][e]

[msg MSG_045_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 0 0 0 56 0 0]......[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 57 0 0]Tu te rappelles la médaille que tu as trouvée dans le colis de mes parents ?[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 58 0 0]Ma sœur, Miki... C'est elle qui l'avait faite pour moi quand on était à l'orphelinat.[n][w][e]

[msg MSG_046_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 59 0 0]Au vu de la lettre qui allait avec, je présume que mes parents l'ont retrouvée en nettoyant la maison.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 60 0 0]Miki allait me la donner pour marquer le fait que j'allais être adopté et partir.[n][w][e]
[f 2 1][bup 4 3 65535 65535 0 0][vp 1 0 0 61 0 0][f 4 23 0 1 3 25 25]Mais... l'incendie a eu lieu juste après et Miki... Cette médaille est tout ce qui a survécu.[n][w][e]

[sel SEL_047_0_0 top]
[f 2 1]On dirait que vous étiez proches.[e]
[f 2 1]Je suis désolée...[e]

[msg MSG_048_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 62 0 0]Apparemment, Miki disait toujours qu'elle voulait me remercier d'être si fort et si gentil.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 63 0 0]Elle était toujours si calme, et elle me suivait partout.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 64 0 0]Je ne me souviens pas d'avoir fait quoi que ce soit de spécial pour elle, mais j'imagine qu'elle me voyait comme un grand frère.[n][w][e]

[msg MSG_049_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 65 0 0]Revoir cette médaille m'a fait réfléchir.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 66 0 0]Est-ce que ma sœur serait fière du garçon que je suis devenu ?[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 67 0 0]Est-ce que je suis assez fort et charitable pour mériter cette médaille ?[n][w][e]

[msg MSG_050_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 3 65535 65535 0 0][vp 1 0 0 68 0 0]Pour être honnête, je ne sais pas vraiment ce que ça signifie d'être fort ou charitable.[n][w][e]
[f 2 1][bup 4 3 65535 65535 0 0][vp 1 0 0 69 0 0]Tous ceux qui m'ont dit que je l'étais m'ont quitté sans m'expliquer le plus important.[n][w][e]
[f 2 1][bup 4 3 65535 65535 0 0][vp 1 0 0 70 0 0]Tu as vu comme je me suis comporté aujourd'hui... C'est tout ce dont je suis capable maintenant.[n][w][e]
[f 2 1][bup 4 3 65535 65535 0 0][vp 1 0 0 71 0 0]Je n'ai pas beaucoup changé depuis l'orphelinat... Je suis sûr qu'ils seraient morts de rire s'ils me voyaient en ce moment.[n][w][e]

[sel SEL_051_0_0 top]
[f 2 1]C'est faux.[e]
[f 2 1]Tu es bien assez fort et charitable.[e]
[f 2 1]On peut pas se battre le ventre vide.[e]

[msg MSG_052_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 72 0 0][f 4 23 0 1 0 25 25]C'est peut-être le genre de choses que dirait ma sœur, mais tout le monde ne serait pas aussi sympa avec moi.[n][w][e]

[msg MSG_053_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 1 65535 65535 0 0][vp 1 0 0 73 0 0][f 4 23 0 1 1 25 25]Hmm... Je suis content que tu penses ça, mais j'ai encore beaucoup à apprendre.[n][w][e]

[msg MSG_054_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 1 65535 65535 0 0][vp 1 0 0 74 0 0][f 4 23 0 1 1 25 25]C'est vrai. Les sucreries peuvent redonner de l'énergie. Je pense pouvoir être de nouveau prêt à me battre dès demain.[n][w][e]

[msg MSG_055_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 75 0 0]Cela dit, j'ai compris un truc... J'ai passé mon temps à fuir, à prétendre que j'étais trop occupé avec mes propres problèmes...[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 76 0 0]Mais à partir d'aujourd'hui, je vais me battre pour tous vous protéger.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 77 0 0]Nous nous sommes promis de devenir plus forts ensemble... Je ne le décevrai pas.[n][w][e]

[sel SEL_056_0_0 top]
[f 2 1]Je sais que tu peux y arriver.[e]
[f 2 1]Je suis là si tu as besoin de moi.[e]
[f 2 1]Bonne chance.[e]

[msg MSG_057_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 1 65535 65535 0 0][vp 1 0 0 78 0 0]Si c'est vraiment ce que tu penses, je ferais mieux de ne pas te décevoir.[n][w][e]

[msg MSG_058_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 1 65535 65535 0 0][vp 1 0 0 79 0 0]Je te remercie. Je compte sur toi pour la prochaine fois.[n][w][e]

[msg MSG_059_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 1 65535 65535 0 0][vp 1 0 0 80 0 0]Ouais. Vous êtes plusieurs, comme toi, à compter sur moi, donc je ne peux pas me permettre de vous décevoir.[n][w][e]

[msg MSG_060_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 1 65535 65535 0 0][vp 1 0 0 81 0 0]Hmm... Je voulais remonter le moral à tout le monde avec ça, et c'est moi qui me retrouve à être encouragé...[n][w][e]
[f 2 1][bup 4 1 65535 65535 0 0][vp 1 0 0 82 0 0]Tu sais, je pense que ma sœur t'aurait beaucoup apprécié.[n][w][e]

[msg MSG_061_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 83 0 0]OK, assez parlé du passé. Dépêchons-nous de finir de nett...[n][w][e]

[msg MSG_061_5_0 [Akihiko Sanada]]
[f 2 1][bup 4 5 65535 65535 0 0][vp 1 0 0 84 0 0]Arg...[n][w][e]

[sel SEL_062_0_0 top]
[f 2 1]Qu'est-ce qui va pas ?[e]
[f 2 1]Tu es blessé ?[e]

[msg MSG_063_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 85 0 0]Je suis tombé sur un groupe de loubards après avoir fait des courses aujourd'hui.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 86 0 0]Ils étaient plus nombreux cette fois, et un des types ne m'a pas raté...[n][w][e]

[msg MSG_064_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 87 0 0]T'inquiète pas. Je n'ai rien fait qui aurait pu me mettre à mal vis-à-vis de la police.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 88 0 0]Je les ai juste laissés me cogner jusqu'à qu'ils en aient marre et me laissent tranquille.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 89 0 0]Je pensais pouvoir esquiver tous leurs coups, mais... il faut croire que j'ai encore beaucoup à apprendre.[n][w][e]

[msg MND_065_0_0]
[f 2 1]J'ai fini de nettoyer avec Sanada, et je suis retourné dans ma chambre...[n][w][e]
[f 2 1]Je sens que j'ai gagné en [f 4 30 1 1 1 0] après avoir vu le côté attentionné de Sanada...[n][w][e]

