[msg MSG_000_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 1 0 0]Hmm... Elle dort encore.[n][w][e]

[msg MSG_001_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 2 0 0]L'Heure sombre survient chaque jour à minuit. Disons que c'est... une heure "cachée".[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 3 0 0]Pendant cette heure, une personne ordinaire est transmutée en cercueil et n'a plus conscience de rien.[n][w][e]

[msg MSG_002_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 51 65535 0 0][vp 1 0 0 4 0 0]Donc, elle est sans doute...[n][w][e]

[msg MSG_003_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 5 0 0]Comme tu peux le voir, elle a gardé sa forme humaine.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 6 0 0]Elle a beau dormir, elle n'en subit pas moins les effets de l'Heure sombre.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 7 0 0]Il ne reste donc plus qu'à savoir s'elle possède ou non le potentiel.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 8 0 0]Même si, en y réfléchissant, c'est sûrement le cas... Sinon, elle aurait déjà été ciblée.[n][w][e]

[msg MSG_004_0_0 [Yukari Takeba]]
[f 2 1][bup 2 3 51 65535 0 0][vp 1 0 0 9 0 0]Effrayant...[n][w][e]

[msg MSG_005_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 10 0 0]Quoi qu'il en soit, nous devrions la surveiller encore quelques jours.[n][w][e]

[msg MSG_006_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 51 65535 0 0][vp 1 0 0 11 0 0]Oui, monsieur.[n][w][e]

[msg MSG_007_0_0 [Yukari Takeba]]
[f 2 1][bup 2 3 51 65535 0 0][vp 1 0 0 12 0 0]L'espionner comme ça me gêne un peu...[n][w][e]

