[msg MSG_000_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 3 0 65535 1114 0 0]Pfiou, merci pour le repas. On n'est jamais déçu, ici.[n][w][e]

[msg MSG_001_0_0 [Yukari Takeba]]
[f 2 1][bup 2 4 65535 65535 0 0][f 4 25 2]Oh...[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][f 4 23 0 2 0 25 25]Hum...[n][w][e]

[msg MSG_002_0_0 [Yukari Takeba]]
[f 2 1][bup 2 3 65535 65535 0 0][vp 3 0 65535 1110 0 0]Je...[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0]Je sais que j'ai un appétit d'ogre...[n][w][e]

[sel SEL_003_0_0 top]
[f 2 1]Moi qui pensais que j'avais de l'appétit...[e]
[f 2 1]Tu veux ma part ?[e]
[f 2 1]Tu manges à ta faim.[e]

[msg MSG_004_0_0 [Yukari Takeba]]
[f 2 1][bup 2 2 65535 65535 0 0][vp 3 0 65535 1089 0 0]C'est plus fort que moi... L'entraînement a tendance à m'ouvrir l'appétit ![n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][f 4 23 0 2 0 25 25][f 4 25 2]......[n][w][e]

[msg MSG_004_3_0 [Yukari Takeba]]
[f 2 1][bup 2 3 65535 65535 0 0]Mais bon, j'ai pas trop envie de me gaver...[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][f 4 23 0 2 0 25 25]Hmm, j'ai plus très faim... Merci.[n][w][e]

[msg MND_005_0_0]
[f 2 1] Yukari semble nerveuse.[n][w][e]
[f 2 1]J'ai l'impression qu'on ne s'est pas rapprochées, aujourd'hui...[n][w][e]

[msg MSG_006_0_0 [Yukari Takeba]]
[f 2 1][bup 2 10 65535 65535 0 0][vp 3 0 65535 1119 0 0][f 5 13 7 15 2]Honnêtement, oui, mais...[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][f 4 23 0 2 0 25 25]Je voudrais surtout pas te priver...[n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0][f 4 23 0 2 1 25 25]Oh non... je peux pas résister... bon, d'accord, je vais goûter ! Merci ![n][w][e]

[msg MND_007_0_0]
[f 2 1]Yukari a l'air de bien s'amuser.[n][w][e]
[f 2 1]Aujourd'hui, j'en ai appris un peu plus sur elle.[n][w][e]

[msg MSG_008_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 3 0 65535 1113 0 0][f 5 13 7 30 2]T-Tu crois ?[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0]Hé, c'est quoi ce sourire ?[n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0][f 4 23 0 2 1 25 25]À ma faim, hein... Hahaha ![n][w][e]

[msg MND_009_0_0]
[f 2 1]Yukari semble contente.[n][w][e]
[f 2 1]J'ai l'impression qu'on s'est beaucoup rapprochées, aujourd'hui.[n][w][e]

[msg MSG_010_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 3 0 65535 1002 0 0]Hé, tu voudrais pas faire un détour... il faut que j'élimine tout ce que j'ai avalé.[n][w][e]

[msg MND_011_0_0]
[f 2 1]Après manger, on s'est baladées un moment, avant de rentrer au dortoir.[n][w][e]

