[msg MSG_002_0_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 1 0 0 1 0 0]J'espère qu'ils ne seront pas trop amers...[n][w][e]

[msg MSG_003_0_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 1 0 0 2 0 0]Si la température se maintient, ils devraient bien grandir.[n][w][e]

[msg MSG_004_0_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 1 0 0 3 0 0]Ça suffira, pour l'engrais. Pour le reste, il faut s'en remettre à la météo.[n][w][e]

