[msg MSG_004_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 8 0 0]Je te prie de m'excuser pour l'erreur concernant ton logement.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 9 0 0]Mais il faudra encore un peu de temps avant que tu puisses t'installer dans la bonne chambre.[n][w][e]
[f 2 1][bup 222 1 65535 65535 0 0][vp 1 0 0 10 0 0][f 4 23 0 222 1 25 25]Est-ce que tu as des questions ?[n][w][e]

[sel SEL_005_0_0 top]
[f 2 1]Que faites-vous là ?[e]
[f 2 1]Qui d'autre vit ici ?[e]
[f 2 1]L'autre soir, j'ai vu...[e]
[f 2 1]Non, ça va.[e]

[msg MSG_006_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 1 65535 65535 0 0][vp 1 0 0 11 0 0]【未使用】なぜって…君を迎えるためさ。[n]ダメかい？[n][w][e]

[msg MSG_006_1_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 12 0 0][f 4 23 0 222 0 25 25]【未使用】…あ、岳羽君。[n]そう言えば、桐条君は？[n][w][e]

[msg MSG_007_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 13 0 0]【未使用】ハイ、もう上に。[n][w][e]

[msg MSG_008_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 14 0 0]【未使用】いつもながらマジメだねぇ。[n]顔くらい出せばいいのに。[n][w][e]

[msg MSG_009_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 15 0 0]Autre chose ?[n][w][e]

[msg MSG_010_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 16 0 0]【未使用】この寮の住人は、[n]君を含めて４人だ。[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 17 0 0]【未使用】ここにいる岳羽君と、[n]それから、桐条君。[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 18 0 0]【未使用】あと、３年生の男子で[n]真田明彦君という生徒がいる。[n][w][e]
[f 2 1][bup 222 1 65535 65535 0 0][vp 1 0 0 19 0 0]【未使用】ひとつ、仲良くね。[n][w][e]

[msg MSG_011_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 20 0 0]Tu as d'autres questions ?[n][w][e]

[msg MSG_012_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 4 65535 65535 0 0][vp 1 0 0 21 0 0]【未使用】変なモノ？[n]…なんの事だい？[n][w][e]

[msg MSG_013_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 22 0 0]【未使用】……[n][w][e]

[msg MSG_014_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 1 65535 65535 0 0][vp 1 0 0 23 0 0]【未使用】多分、疲れてたんじゃないかな？[n]あまり気にしない事だ。[n][w][e]

[msg MND_015_0_0 [Monologue intérieur]]
[f 2 1]【未使用】なにか怪しい…[n][w][e]

[msg MSG_016_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 24 0 0]Tu as des questions ?[n][w][e]

