[msg MSG_000_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 1 0 0]Bon, cette fois, autant parler de nos futures batailles devant un bon repas.[n][w][e]

[msg MSG_000_3_0 [Yukari Takeba]]
[f 2 1][vp 1 0 0 27 0 0]Ou alors tu t'en fiches, toi, tant que t'as l'occasion de te battre ?[n][w][e]

[msg MSG_000_5_0 [Akihiko Sanada]]
[f 2 1][bup 4 3 65535 65535 0 0][vp 0 0 0 2 0 0][f 4 23 0 4 3 25 25]...[n][w][e]
[f 2 1][bup 4 3 65535 65535 0 0][vp 1 0 0 3 0 0]Nos futures batailles, hein ?[n][w][e]

[sel SEL_001_0_0 top]
[f 2 1]Qu'y a-t-il ?[e]
[f 2 1]Un coup de fatigue ?[e]

[msg MSG_002_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 4 0 0]Ça va, ne t'en fais pas. D'abord, on va se chercher à manger.[n][w][e]

[msg MSG_002_3_0 [Passante]]
[f 2 1][vp 1 0 0 5 0 0]Hé, qu'est-ce qui se passe ?[n][w][e]

[msg MSG_002_5_0 [Acheteuse]]
[f 2 1][vp 1 0 0 6 0 0]Ça me dit rien qui vaille.[n][w][e]

[msg MSG_003_0_0 [Voix de brute]]
[f 2 1][vp 1 0 0 7 0 0][f 5 21 0 1001]Te voilà, Akihiko Sanada.[n][w][e]

[msg MSG_004_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 2 65535 65535 0 0][vp 1 0 0 8 0 0]Oh, on se connaît, non ?[n][w][e]

[msg MSG_005_0_0 [Type hostile]]
[f 2 1][vp 1 0 0 9 0 0][f 5 21 0 1001]Il paraît que t'es plutôt célèbre ? T'es une étoile montante de la boxe, c'est ça ?[n][w][e]

[msg MSG_005_5_0 [Type baraqué]]
[f 2 1][vp 1 0 0 10 0 0][f 5 21 0 1002]Je propose qu'on reprenne là où on en était restés. Montre-moi ce que tu vaux.[n][w][e]

[msg MSG_005_7_0 [Akihiko Sanada]]
[f 2 1][bup 4 2 65535 65535 0 0][vp 0 0 0 11 0 0]...[n][w][e]

[msg MSG_005_9_0 [Type baraqué]]
[f 2 1][vp 1 0 0 12 0 0][f 5 21 0 1002]Te botter le cul, ça va nous faire mousser, sûr. C'est une occasion à pas rater.[n][w][e]

[msg MSG_006_0_0 [Sous-fifre]]
[f 2 1][vp 1 0 0 13 0 0][f 5 21 0 1003]T'es peut-être un champion, mais vise combien on est. T'as aucune chance ![n][w][e]

[sel SEL_007_0_0 top]
[f 2 1]C'est déloyal.[e]
[f 2 1]Battez-vous un par un.[e]
[f 2 1]J'appelle la police.[e]

[msg MSG_008_0_0 [Type hostile]]
[f 2 1][vp 1 0 0 14 0 0][f 5 21 0 1001]Je croyais que les boxeurs, c'était des bonhommes ? T'as les foies, c'est ça ?[n][w][e]

[msg MSG_009_0_0 [Sous-fifre]]
[f 2 1][vp 1 0 0 15 0 0][f 5 21 0 1003]Toi, la pisseuse. Tu peux faire équipe avec lui, si ça te chante. Si ça, c'est pas fair-play... Hahaha ![n][w][e]

[msg MSG_010_0_0 [Type hostile]]
[f 2 1][vp 1 0 0 16 0 0][f 5 21 0 1001]Tu l'auras voulu. On va vous refaire le portrait vite fait.[n][w][e]

[msg MSG_011_0_0 [Type vantard]]
[f 2 1][vp 1 0 0 17 0 0][f 5 21 0 1004]Tu veux peut-être appeler une ambulance, à la place ? Hahaha ![n][w][e]

[msg MSG_012_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 2 65535 65535 0 0][vp 1 0 0 18 0 0]Me battre "vous ferait mousser", c'est ça ?[n][w][e]
[f 2 1][bup 4 2 65535 65535 0 0][vp 1 0 0 19 0 0]Je croyais que l'idée, c'était de mesurer nos forces.[n][w][e]

[msg MSG_013_0_0 [Type baraqué]]
[f 2 1][vp 1 0 0 20 0 0][f 5 21 0 1002]Espèce de crétin arrogant. Je vais adorer te mettre la misère.[n][w][e]
[f 2 1][vp 1 0 0 21 0 0][f 5 21 0 1002]Ce qui compte, c'est de gagner, peu importe la manière. C'est pas comme ça que tu marches, toi ?[n][w][e]

[msg MSG_014_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 2 65535 65535 0 0][vp 0 0 0 22 0 0]...[n][w][e]

[msg MND_015_0_0]
[f 2 1]On dirait qu'un combat est sur le point d'éclater. Je dois faire quelque chose...[n][w][e]

[msg MSG_016_0_0 [Type baraqué]]
[f 2 1][vp 1 0 0 23 0 0][f 5 21 0 1002]Tu veux commencer ?[n][w][e]

[msg MSG_017_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 2 65535 65535 0 0][vp 1 0 0 24 0 0]Recule, [nl] ![n][w][e]

[sel SEL_018_0_0 top]
[f 2 1]M'sieur l'agent, par ici ![e]
[f 2 1]Là-bas, un incendie ![e]

[msg MSG_019_0_0 [Type baraqué]]
[f 2 1][vp 1 0 0 25 0 0][f 5 21 0 1002]Tu te fous de moi ? Ramène-toi ![n][w][e]

[msg MSG_020_0_0 [Type hostile]]
[f 2 1][vp 1 0 0 26 0 0][f 5 21 0 1001]Hé ! Si tu crois qu'on va te laisser filer ![n][w][e]

