[msg MSG_000_0_0 [M. Edogawa]]
[f 2 1][bup 1081 1 65535 65535 0 0][vp 3 0 65535 14823 0 0]Qu'est-ce qui t'amène à l'infirmerie ? Héhéhé.[n][w][e]
[f 2 1][bup 1081 1 65535 65535 0 0]Alors, qu'avons-nous ici ? Tu as l'air fatiguée. Est-ce dû à une blessure ? Un virus ? Un mauvais sort ? Ou à l'amour ?[n][w][e]
[f 2 1][bup 1081 1 65535 65535 0 0]C'est l'occasion idéale pour tester ma nouvelle préparation. Héhéhé.[n][w][e]

[msg MSG_001_0_0 [M. Edogawa]]
[f 2 1][bup 1081 1 65535 65535 0 0][vp 3 0 65535 14804 0 0]Tiens, essaie ça.[n][w][e]
[f 2 1][bup 1081 1 65535 65535 0 0]Un petit mélange d'absinthe, de cigüe, de jusquiame noire, de jujube, de fougère patte de lapin, etc.[n][w][e]
[f 2 1][bup 1081 1 65535 65535 0 0]Même le meilleur alchimiste d'Hakusan serait étonné par les ingrédients.[n][w][e]
[f 2 1][bup 1081 1 65535 65535 0 0]Je vais guérir ton mal immédiatement.[n][w][e]
[f 2 1][bup 1081 0 65535 65535 0 0][vp 3 0 65535 14808 0 0]Maintenant, bois ça. Allez... Cul sec ![n][w][e]

[msg MND_002_0_0]
[f 2 1]Le médicament que m'a donné M. Edogawa a une odeur très étrange.[n][w][e]
[f 2 1]Est-ce que je devrais le boire ?[n][w][e]

[sel SEL_003_0_0 top]
[f 2 1]Boire[e]
[f 2 1]Ne pas boire[e]

[msg MND_004_0_0]
[f 2 1]J'ai bu le médicament étrange, mais je ne sens aucun effet.[n][w][e]

[msg MSG_005_0_0 [M. Edogawa]]
[f 2 1][bup 1081 1 65535 65535 0 0][vp 3 0 65535 14817 0 0]Pfiou... Bien joué.[n][w][e]
[f 2 1][bup 1081 1 65535 65535 0 0]Savoir si ça a fonctionné est sans importance. Tu as survécu ![n][w][e]
[f 2 1][bup 1081 1 65535 65535 0 0]Tu as déjà vidé ton verre, mais... trinquons à ton courage ![n][w][e]

[msg MSG_006_0_0 [M. Edogawa]]
[f 2 1][bup 1081 0 65535 65535 0 0][vp 3 0 65535 14815 0 0]Bon, si tu veux bien m'excuser, Saturne m'appelle.[n][w][e]

[msg MSG_007_0_0 [M. Edogawa]]
[f 2 1][bup 1081 0 65535 65535 0 0][vp 3 0 65535 14820 0 0]Comment ça, tu ne veux pas la boire ? Quelle lâche ! Même Algernon l'a bue.[n][w][e]
[f 2 1][bup 1081 0 65535 65535 0 0]Cette petite souris tranquille est sortie de là absolument pleine d'énergie ![n][w][e]

[msg MSG_008_0_0 [M. Edogawa]]
[f 2 1][bup 1081 0 65535 65535 0 0][vp 3 0 65535 14822 0 0]Oh, Algernon est mon familier. Enfin, mon animal de compagnie.[n][w][e]
[f 2 1][bup 1081 1 65535 65535 0 0]Mais bon, il vaut mieux ne pas prendre trop de médicaments.[n][w][e]

[msg MSG_009_0_0 [M. Edogawa]]
[f 2 1][bup 1081 0 65535 65535 0 0][vp 3 0 65535 14803 0 0]Tu devrais rentrer te reposer. Allez, file.[n][w][e]

