[msg MSG_001_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 1 0 0]Depuis que j'ai pu reprendre mon entraînement comme il faut, j'ai récupéré ma forme.[n][w][e]
[f 2 1][bup 4 1 65535 65535 0 0][vp 1 0 0 2 0 0][f 4 23 0 4 1 25 25]Je voulais te remercier pour ça. Tu as vraiment assuré en tant que chef.[n][w][e]
[f 2 1][bup 4 1 65535 65535 0 0][vp 1 0 0 3 0 0]Donc, je t'invite, ce soir. Ça ne doit pas être facile d'endosser autant de responsabilités.[n][w][e]

[sel SEL_002_0_0 top]
[f 2 1]Je peux gérer.[e]
[f 2 1]Je m'en sors à peine.[e]
[f 2 1]Parfait, je meurs de faim.[e]

[msg MSG_003_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 1 65535 65535 0 0][vp 1 0 0 4 0 0]Hahaha, tu n'es clairement pas comme les autres... Je me disais bien que tu m'avais fait bonne impression.[n][w][e]

[msg MSG_004_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 5 0 0]Vraiment ? Je dirais que tu t'en sors très bien. Pense juste à bien manger et à te reposer quand il faut.[n][w][e]

[msg MSG_005_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 1 65535 65535 0 0][vp 1 0 0 6 0 0]Alors comme ça tu as du talent et de l'appétit. Je pense que tu ferais une excellente athlète.[n][w][e]

[msg MSG_006_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 7 0 0]Ne te surmène pas, d'accord ? Avec l'expérience, tu devrais pouvoir gérer tout ça plus facilement.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 8 0 0]Et si tu as besoin de quoi que ce soit, je suis là. Je ferai tout ce que je peux pour t'aider.[n][w][e]

[msg MSG_007_0_0 [Voix de jeune femme]]
[f 2 1][vp 1 0 0 9 0 0][f 5 21 0 1001]Pardon...[n][w][e]

[msg MSG_008_0_0 [Fan enthousiaste]]
[f 2 1][vp 1 0 0 10 0 0][f 5 21 0 1001]Ah, je le savais ! Tu es bien Akihiko Sanada, du lycée Gekkoukan ![n][w][e]
[f 2 1][vp 1 0 0 11 0 0][f 5 21 0 1001]J'ai entendu dire que tu vivais à Iwatodai, mais ouaaah... J'ai vraiment du bol d'être tombée sur toi ici ![n][w][e]

[msg MSG_009_0_0 [Fan insistante]]
[f 2 1][vp 1 0 0 12 0 0][f 5 21 0 1002]On est tes fans ! S'il te plaît, on peut prendre une photo avec toi ?![n][w][e]

[msg MSG_010_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 13 0 0]Je suis occupé... Et puis je n'aime pas être pris en photo.[n][w][e]

[msg MSG_011_0_0 [Fan enthousiaste]]
[f 2 1][vp 1 0 0 14 0 0][f 5 21 0 1001]J'ai pas arrêté d'entendre des rumeurs comme quoi tu t'étais blessé. Tu n'as rien ?[n][w][e]

[msg MSG_012_0_0 [Fan insistante]]
[f 2 1][vp 1 0 0 15 0 0][f 5 21 0 1002]Tu as besoin d'aide ? Tu veux qu'on t'apporte un truc peut-être ?[n][w][e]

[msg MSG_012_3_0 [Passante]]
[f 2 1][vp 1 0 0 16 0 0][f 5 21 0 1003]Oooh, il est connu ce jeune ?[n][w][e]

[msg MSG_012_5_0 [Homme curieux]]
[f 2 1][vp 1 0 0 17 0 0][f 5 21 0 1004]Je sais pas. C'est peut-être une célébrité ? Tu veux aller jeter un œil ?[n][w][e]

[msg MSG_012_7_0 [Akihiko Sanada]]
[f 2 1][bup 4 3 65535 65535 0 0][vp 0 0 0 18 0 0]......[n][w][e]

[msg MSG_013_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 19 0 0]Allons-y, [nl].[n][w][e]

[msg MSG_014_0_0 [Excited Fan (SE)]]
[f 2 1][vp 1 0 0 20 0 0][f 5 21 0 1001]Attends... Sanadaaa ![n][w][e]

[msg MSG_015_0_0 [Akihiko Sanada]]

[msg MSG_016_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 3 65535 65535 0 0][vp 1 0 0 22 0 0]On m'a déjà ennuyé de la sorte au lycée... mais je ne pensais pas que ça arriverait ici aussi.[n][w][e]
[f 2 1][bup 4 3 65535 65535 0 0][vp 1 0 0 23 0 0]C'est sûrement à cause des interviews et des rumeurs. Je n'arrête pas d'attirer les foules depuis que j'enchaîne les victoires.[n][w][e]

[sel SEL_017_0_0 top]
[f 2 1]Ça n'a pas l'air agréable.[e]
[f 2 1]Je suis jalouse.[e]

[msg MSG_018_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 24 0 0]Et comment... Je ne suis pas une bête de foire juste là pour divertir les autres.[n][w][e]

[msg MSG_019_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 1 65535 65535 0 0][vp 1 0 0 25 0 0]J'ai déjà entendu Junpei dire ça, mais je ne m'attendais pas à ça de toi.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 26 0 0][f 4 23 0 4 0 25 25]Hmm... J'apprécie le soutien, mais je n'ai pas le temps pour ça en ce moment.[n][w][e]

[msg MSG_020_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 27 0 0]Tout ce qui m'intéresse, c'est de devenir plus fort. Je veux m'entraîner durement et être fier de ma puissance.[n][w][e]
[f 2 1][bup 4 3 65535 65535 0 0][vp 1 0 0 28 0 0][f 4 23 0 4 3 25 25]Mais cela ne semble m'apporter que des ennuis...[n][w][e]

[msg MSG_022_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 29 0 0]Bon, on dirait qu'elles ont abandonné...[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 30 0 0]Allons manger, pour de vrai cette fois. Ne perdons pas plus de temps ce soir.[n][w][e]

