[msg MSG_000_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 2 65535 0 0][vp 1 0 0 1 0 0]C'est Takeba. Tu es réveillée ?[n][w][e]

[sel SEL_001_0_0 top]
[f 2 1]Bonjour.[e]
[f 2 1]...[e]

[msg MSG_002_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 2 65535 0 0][vp 1 0 0 2 0 0]Salut ! Allez, ouvre la porte, sinon ça va me retomber dessus ![n][w][e]

[msg MSG_003_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 2 65535 0 0][vp 1 0 0 3 0 0]Bonjour. Tu as bien dormi ?[n][w][e]

[msg MSG_004_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 2 65535 0 0][vp 1 0 0 4 0 0]On m'a demandé de te montrer le chemin jusqu'au lycée.[n][w][e]
[f 2 1][bup 2 0 2 65535 0 0][vp 1 0 0 5 0 0]On peut y aller ?[n][w][e]

[sel SEL_005_0_0 top]
[f 2 1]Ouais, on peut.[e]
[f 2 1]Je me débrouillerai.[e]

[msg MSG_006_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 2 65535 0 0][vp 1 0 0 6 0 0]Parfait ! Allons-y ![n][w][e]

[msg MSG_007_0_0 [Yukari Takeba]]
[f 2 1][bup 2 6 2 65535 0 0][vp 1 0 0 7 0 0]Euh... Je m'attendais pas à ce que tu refuses.[n][w][e]
[f 2 1][bup 2 0 2 65535 0 0][vp 1 0 0 8 0 0][f 4 23 0 1 0 25 25]Tu veux pas risquer d'arriver en retard pour ton premier jour, hein ?[n][w][e]
[f 2 1][bup 2 1 2 65535 0 0][vp 1 0 0 9 0 0][f 4 23 0 1 1 25 25]Allez, bouge, faut qu'on y aille ![n][w][e]

