[msg MSG_000_0_0 [Voix d'élève]]
[f 2 1][vp 1 0 0 1 0 0][f 5 21 0 1]Hé, t'es au courant pour cette fille en 2-E ?[n][w][e]

[msg MSG_001_0_0 [Voix d'élève]]
[f 2 1][vp 1 0 0 2 0 0][f 5 21 0 2]Oui, apparemment, personne sait ce qui s'est passé.[n][w][e]

[msg MSG_002_0_0 [Voix d'élève]]
[f 2 1][vp 1 0 0 3 0 0][f 5 21 0 1]Bon sang, c'est vraiment bizarre ![n][w][e]

[msg MSG_003_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 1 0 0 4 0 0]Tout le monde ne parle que de ça. Les gens ont vraiment beaucoup de temps à perdre.[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0][vp 1 0 0 5 0 0]T'es au courant aussi ?[n][w][e]

[sel SEL_004_0_0 top]
[f 2 1]Non.[e]
[f 2 1]Ça m'intéresse pas.[e]

[msg MSG_005_0_0 [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0][vp 1 0 0 6 0 0]Pfff, tu te prends pour une de ces citadins trop stylés ?[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0][vp 1 0 0 7 0 0][f 4 23 0 3 0 25 25]Tu dois te tenir au courant de ce genre de trucs.[n][w][e]

[msg MSG_006_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 1 0 0 8 0 0]Une fille en 2-E a disparu alors qu'elle était sortie la nuit dernière.[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0][vp 1 0 0 9 0 0]Ce matin, ils l'ont trouvée allongée par terre devant le portail du lycée.[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0][vp 1 0 0 10 0 0]Personne sait ce qui est arrivé et elle serait toujours dans le coma.[n][w][e]

[msg MSG_007_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 11 0 0]Bonjour.[n][w][e]

[msg MSG_008_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 1 0 0 12 0 0]Salut, Yuka.[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0][vp 1 0 0 13 0 0]C'est une affaire difficile, même pour Junpei Iori, super détective.[n][w][e]

[msg MSG_009_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 14 0 0]Super détective ?[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 15 0 0]T'es vraiment bête.[n][w][e]

[msg MSG_009_3_0 [Yukari Takeba]]
[f 2 1][bup 2 3 65535 65535 0 0][vp 0 0 0 16 0 0]...[n][w][e]

[msg MSG_009_5_0 [Yukari Takeba]]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 17 0 0]Plutôt, Stupei, super déficient.[n][w][e]

[msg MSG_010_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 65535 65535 0 0][vp 1 0 0 18 0 0]Oh ! Pourquoi tu me dis ça ?[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0][vp 1 0 0 19 0 0][f 4 23 0 3 0 25 25]Mais maintenant que j'y pense, t'as disparu toute la matinée. Où t'étais ?[n][w][e]

[msg MSG_011_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 20 0 0]Je discutais avec le prof.[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 21 0 0]Cette fille qu'ils ont trouvée... Je l'ai vue hier, en revenant de l'entraînement.[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 22 0 0]Elle allait très bien.[n][w][e]

[msg MSG_012_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 1 0 0 23 0 0]Hum...[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0][vp 1 0 0 24 0 0]L'affaire se corse.[n][w][e]

