[msg MSG_000_0_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 0 0 0 1 0 0][f 4 23 0 1 0 25 25]......[n][w][e]
[f 2 1][bup 10 0 65535 65535 0 0][vp 1 0 0 2 0 0][f 4 23 0 1 0 25 25]Bon, pourquoi tu trimballes encore ce truc ?[n][w][e]

[sel SEL_001_0_0 top]
[f 2 1]Je n'ai pas pu le donner.[e]
[f 2 1]Réfléchis à nouveau.[e]

[msg MSG_002_0_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 0 0 0 3 0 0][f 4 23 0 1 0 25 25]......[n][w][e]
[f 2 1][bup 10 0 65535 65535 0 0][vp 1 0 0 4 0 0][f 4 23 0 1 0 25 25]On dirait que tu te contentes pas de jouer les messagers, ce coup-ci.[n][w][e]

[msg MSG_003_0_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 1 0 0 5 0 0][f 4 23 0 1 0 25 25]Désolé, mais je ne retourne pas au lycée.[n][w][e]

[msg MSG_004_0_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 1 0 0 6 0 0][f 4 23 0 1 0 25 25]Écoute... Vu que c'est toi, je peux bien te le dire. J'ai plus beaucoup de temps à vivre.[n][w][e]
[f 2 1][bup 10 0 65535 65535 0 0][vp 1 0 0 7 0 0][f 4 23 0 1 0 25 25]Je m'en sors avec les médocs pour l'instant. Mais ça ne durera pas éternellement.[n][w][e]

[sel SEL_005_0_0 top]
[f 2 1]Comment c'est arrivé ?[e]
[f 2 1]On peut faire quelque chose ?[e]

[msg MSG_006_0_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 3 65535 65535 0 0][vp 0 0 0 8 0 0][f 4 23 0 1 3 25 25]......[n][w][e]
[f 2 1][bup 10 3 65535 65535 0 0][vp 1 0 0 9 0 0][f 4 23 0 1 3 25 25]Je connaissais pas mes limites, et j'ai eu les yeux plus gros que le ventre... C'est tout ce que je mérite.[n][w][e]

[msg MSG_007_0_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 1 0 0 10 0 0][f 4 23 0 1 0 25 25]Je devrais sûrement prier pour un miracle, mais ça n'a jamais marché pour moi.[n][w][e]

[msg MSG_008_0_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 1 0 0 11 0 0][f 4 23 0 1 0 25 25]On parle de mon corps, là. Je le connais mieux que quiconque. Et je sais qu'il n'y a rien à faire.[n][w][e]

[msg MSG_009_0_0 [Serveur]]
[f 2 1][vp 1 0 0 12 0 0][f 5 21 0 2]Deux extras, chaud devant ![n][w][e]

[msg MSG_010_0_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 1 0 0 13 0 0][f 4 23 0 1 0 25 25]Allez, mange. Les nouilles vont ramollir.[n][w][e]

[msg MSG_011_0_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 0 0 0 14 0 0][f 4 23 0 1 0 25 25]......[n][w][e]
[f 2 1][bup 10 0 65535 65535 0 0][vp 1 0 0 15 0 0][f 4 23 0 1 0 25 25]On dirait que je t'ai fait perdre ton temps, je sais. Mais...[n][w][e]

[msg MSG_012_0_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 1 0 0 16 0 0][f 4 23 0 1 0 25 25]Les bons souvenirs, c'est ce qui permet aux gens de traverser les périodes difficiles.[n][w][e]
[f 2 1][bup 10 0 65535 65535 0 0][vp 1 0 0 17 0 0][f 4 23 0 1 0 25 25]Mais ce sont aussi les erreurs qu'on commet qui nous hantent à tout jamais.[n][w][e]
[f 2 1][bup 10 0 65535 65535 0 0][vp 1 0 0 18 0 0][f 4 23 0 1 0 25 25]Je dois profiter du temps qu'il me reste pour rectifier le cap. Je peux pas me permettre de faire quoi que ce soit d'autre.[n][w][e]

[sel SEL_013_0_0 top]
[f 2 1]N'oublie pas ta promesse.[e]
[f 2 1]Il faut toujours tenir ses promesses.[e]

[msg MSG_014_0_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 4 65535 65535 0 0][vp 0 0 0 19 0 0][f 4 23 0 1 4 25 25]... ![n][w][e]
[f 2 1][bup 10 0 65535 65535 0 0][vp 1 0 0 20 0 0][f 4 23 0 1 0 25 25]Ah ben la vache. Tu mâches pas tes mots, toi.[n][w][e]

[msg MSG_015_0_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 1 65535 65535 0 0][vp 1 0 0 21 0 0][f 4 23 0 1 1 25 25]Mais tu sais, c'est pas si mal.[n][w][e]
[f 2 1][bup 10 1 65535 65535 0 0][vp 1 0 0 22 0 0][f 4 23 0 1 1 25 25]Ça change des gens qui la bouclent parce qu'ils ont peur de me blesser.[n][w][e]

[msg MSG_016_0_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 1 0 0 23 0 0][f 4 23 0 1 0 25 25]Ça doit être pour ça qu'ils comptent autant sur toi.[n][w][e]
[f 2 1][bup 10 0 65535 65535 0 0][vp 1 0 0 24 0 0][f 4 23 0 1 0 25 25]Aki et Kirijo combattent avec beaucoup plus de confiance qu'il y a deux ans.[n][w][e]
[f 2 1][bup 10 0 65535 65535 0 0][vp 1 0 0 25 0 0][f 4 23 0 1 0 25 25]Ouais, t'es vraiment pas comme les autres.[n][w][e]

[msg MSG_017_0_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 1 0 0 26 0 0][f 4 23 0 1 0 25 25]Mais franchement, si tu as du temps à perdre avec moi, consacre-le plutôt à quelqu'un d'autre.[n][w][e]
[f 2 1][bup 10 3 65535 65535 0 0][vp 1 0 0 27 0 0][f 4 23 0 1 3 25 25]Comme Ken Amada. C'est encore un gamin, il est complètement dépassé.[n][w][e]
[f 2 1][bup 10 3 65535 65535 0 0][vp 1 0 0 28 0 0][f 4 23 0 1 3 25 25]Je ferai tout ce que je peux pour aider, mais après...[n][w][e]

[msg MSG_018_0_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 1 0 0 29 0 0][f 4 23 0 1 0 25 25]... Je compte sur toi.[n][w][e]

[msg MSG_019_0_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 1 0 0 30 0 0][f 4 23 0 1 0 25 25]Je vais prendre ça.[n][w][e]
[f 2 1][bup 10 0 65535 65535 0 0][vp 1 0 0 31 0 0][f 4 23 0 1 0 25 25]Ouais, c'est moi qui aurais dû aller donner ce papier. Désolé de t'avoir mis ça sur les épaules.[n][w][e]

[msg MSG_020_0_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 1 0 0 32 0 0][f 4 23 0 1 0 25 25]Tu peux y aller. Aujourd'hui, c'est moi qui paie.[n][w][e]

[msg MSG_021_0_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 3 65535 65535 0 0][vp 0 0 0 33 0 0][f 4 23 0 1 3 25 25]......[n][w][e]

[msg MSG_022_0_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 1 0 0 34 0 0][f 4 23 0 1 0 25 25]Merci. L'argent est sur le comptoir.[n][w][e]

[msg MSG_023_0_0 [Serveur]]
[f 2 1][vp 1 0 0 35 0 0][f 5 21 0 2]Merci monsieur, au plaisir ![n][w][e]

[msg MND_024_0_0]
[f 2 1]Aragaki et moi sommes rentrés au dortoir en silence...[n][w][e]
[f 2 1]Je sens que la confiance d'Aragaki m'a fait gagner en [f 4 30 2 1 1 0]...[n][w][e]

