[msg MND_001_0_0]
[f 2 1]J'ai décidé de goûter au nouveau burger.[n][w][e]

[msg MND_002_0_0]
[f 2 1]Malgré sa texture particulière, il est étonnamment bon ![n][w][e]

[msg MND_003_0_0]
[f 2 1]Accompagné de frites imbibées d'huile, j'ai dévoré le mystérieux burger.[n][w][e]

[msg MND_004_0_0]
[f 2 1]Un employé m'a regardé d'un air désolé avant de se détourner.[n][w][e]
[f 2 1]Un peu mal à l'aise, je suis quand même parvenue à tout manger.[n][w][e]

[msg MND_005_0_0]
[f 2 1]J'ai décidé de goûter au menu week-end du Wilduck.[n][w][e]

[msg MND_006_0_0]
[f 2 1]J'ai été surprise par la quantité, mais je suis parvenue à tout manger.[n][w][e]

[msg MND_007_0_0]
[f 2 1]Je serais incapable d'en décrire la saveur, mais cela ne m'a pas empêché de tout manger.[n][w][e]

[msg MND_008_0_0]
[f 2 1]Malgré son goût curieux et étrange, j'ai fini par tout manger.[n][w][e]

