[msg MSG_000_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 3 0 65535 1002 0 0]Irgendwie komisch, an unserem freien Tag zusammen abzuhängen, findest du nicht?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 4 23 0 2 0 25 25]Wenn man uns zusammen sieht, wird es bestimmt Gerüchte geben ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 4 23 0 2 1 25 25]... Es ist wohl zu spät, um sich darüber Sorgen zu machen ... Haha.[n][uf 1 1][e]

[msg MSG_001_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]Ach, übrigens, was machst du so in deiner Freizeit?[n][uf 1 1][e]

[msg MSG_002_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 65535 65535 0 0][uf 3 1 3 0 65535 1111 0 0]I-Ich will nicht rumspionieren. Ich war bloß neugierig.[n][uf 1 1][e]

[sel SEL_003_0_0 top]
[uf 0 5 65278][uf 2 1]Mit einem Freund abhängen.[e]
[uf 0 5 65278][uf 2 1]In meinem Zimmer bleiben.[e]
[uf 0 5 65278][uf 2 1]Das weiß ich hinterher alles gar nicht mehr.[e]

[msg MSG_004_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 3 0 65535 1132 0 0][uf 5 13 7 30 2]V-Verstehe. Genau wie heute, was?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0]Ich bin sicher, alle hängen gerne mit dir ab, [uf 4 1]-chan.[n][uf 1 1][e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]Yukari nickt mit dem Kopf.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Ich habe das Gefühl, wir sind uns heute sehr viel näher gekommen.[n][uf 1 1][e]

[msg MSG_006_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0][uf 3 1 3 0 65535 1107 0 0][uf 5 13 7 15 2]Wirklich? Warum habe ich das nie bemerkt?[n]Wir sind im gleichen Wohnheim.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 4 23 0 2 1 25 25]Dann, ähm ... komm doch mal vorbei. Fühlst du dich so ganz allein nicht einsam?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0]Ja, das würde Spaß machen.[n][uf 1 1][e]

[msg MND_007_0_0]
[uf 0 5 65278][uf 2 1]Yukari nickt mit dem Kopf.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Ich habe heute etwas Neues über sie erfahren ...[n][uf 1 1][e]

[msg MSG_008_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 65535 65535 0 0][uf 3 1 3 0 65535 1122 0 0]Was? So was kannst du doch nicht vergessen haben.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 65535 65535 0 0]Oder willst du vielleicht einfach nicht zugeben, dass du in deinem Zimmer bleibst ...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 65535 65535 0 0][uf 4 23 0 2 6 25 25]Weißt du, so zu leben ist eine Garantie dafür, schlecht zu altern.[n][uf 1 1][e]

[msg MND_009_0_0]
[uf 0 5 65278][uf 2 1]Yukari scheint um mich besorgt zu sein.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Ich habe das Gefühl, wir sind uns heute kein Stück nähergekommen ...[n][uf 1 1][e]

[msg MSG_010_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 65535 65535 0 0][uf 3 1 3 0 65535 1067 0 0]Was? Schon so spät? An freien Tagen rast die Zeit nur so vorbei.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 4 23 0 2 1 25 25]Machen wir noch einen Halt, ehe wir zurückgehen. Wir müssen die Zeit schließlich nutzen![n][uf 1 1][e]

[msg MND_011_0_0]
[uf 0 5 65278][uf 2 1]Wir haben noch etwas Zeit zusammen verbracht und sind dann zum Wohnheim zurückgegangen.[n][uf 1 1][e]

