[msg MSG_000_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]Não temos muito tempo pra treinar aqui, então vocês precisam praticar sozinhos também se quiserem vencer![n][uf 1 1][e]

[msg MSG_001_0_0 [Garoto determinado]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 2 0 0][uf 5 21 0 1001]É, a gente consegue![n][uf 1 1][e]

[msg MSG_002_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]Ótimo! E não se esqueçam: saibam seus limites e lembrem de se alongar direito![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]Ah, [uf 4 1]-chan, por que você não dá um conselho pra eles também?[n][uf 1 1][e]

[sel SEL_003_0_0 top]
[uf 0 5 65278][uf 2 1]Vocês conseguem.[e]
[uf 0 5 65278][uf 2 1]Determinação, pessoal![e]

[msg MSG_004_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 5 0 0][uf 5 13 12 5 106]Isso aí! Mas não se esqueçam de manter o foco até o final![n][uf 1 1][e]

[msg MSG_005_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 6 0 0][uf 5 13 12 5 106]Isso! Garra! Determinação! Vocês conseguem, eu sei que conseguem![n][uf 1 1][e]

[msg MSG_006_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]Agora, escutem aqui. Não importa o que aconteça...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 2 65535 65535 0 0][uf 3 1 1 0 0 8 0 0][uf 4 23 0 1 0 25 25]Pensem positivo e não tenham medo![n][uf 1 1][e]

[msg MND_007_0_0]
[uf 0 5 65278][uf 2 1]As crianças foram para casa após o treino.[n][uf 1 1][e]

[msg MSG_008_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 9 0 0]Essas crianças vão desafiar os alunos do sétimo ano em breve.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]Aparentemente, os vencedores poderão usar o pátio da escola.[n][uf 1 1][e]

[msg MSG_008_5_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 0 0][uf 3 1 1 0 0 11 0 0]Mais cedo, eles me pediram pra escrever uma carta de desafio... Estou um pouco preocupada, na verdade.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]Não só pela corrida, mas também porque não sei se escrevi alguma coisa errada ou não.[n][uf 1 1][e]

[msg MSG_009_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]Então, o que você acha?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]A diferença de idade importa muito quando você é jovem assim. Você acha mesmo que eles conseguem vencer os alunos do sétimo ano?[n][uf 1 1][e]

[sel SEL_010_0_0 top]
[uf 0 5 65278][uf 2 1]Vai ser difícil.[e]
[uf 0 5 65278][uf 2 1]Desde que acreditemos neles.[e]

[msg MSG_011_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 0 0][uf 3 1 1 0 0 15 0 0]É, não tem jeito, eu acho...[n][uf 1 1][e]

[msg MSG_012_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 0 0][uf 3 1 1 0 0 16 0 0]Alguns dos meninos dessa idade são até maiores do que eu. É muita diferença na força física.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 17 0 0][uf 4 23 0 1 0 25 25]Mas mesmo assim![n][uf 1 1][e]

[msg MSG_013_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 18 0 0][uf 5 13 12 5 106]S-Sim, você tem razão! Uma treinadora tem que acreditar na sua equipe![n][uf 1 1][e]

[msg MSG_014_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 19 0 0]E todos eles treinaram muito também![n][uf 1 1][e]

[msg MSG_015_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 20 0 0]Eles vão ficar bem, né?! Afinal, eles aprenderam com a gente![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 0 0][uf 3 1 1 0 0 21 0 0][uf 4 23 0 1 3 25 25]Então por que eu tô tão nervosa...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 22 0 0][uf 4 23 0 1 0 25 25]Vai dar tudo certo. Eu sei que eles podem vencer![n][uf 1 1][e]

[msg MND_016_0_0]
[uf 0 5 65278][uf 2 1]Sinto que estou formando um laço com Yuko.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Sinto que minha relação com ela está amadurecendo...[n][uf 1 1][e]

[msg MSG_017_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 0 0][uf 3 1 1 0 0 23 0 0]Pensando bem, eu deveria ter pedido pra você escrever a carta de desafio, [uf 4 1]-chan...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 0 0][uf 3 1 1 0 0 24 0 0]Eu devia ter usado palavras mais difíceis... Ugh, eu vou ficar tão envergonhada se aqueles alunos do sétimo ano rirem da carta.[n][uf 1 1][e]

[msg MND_018_0_0]
[uf 0 5 65278][uf 2 1]Yuko e eu caminhamos juntas para casa.[n][uf 1 1][e]

