[msg MSG_000_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 1 65535 65535 0 0][uf 4 23 0 114 1 25 25][uf 5 13 17 5 114]Your head's actually a mop, huh? It just soaks up everything I tell ya...[n][uf 1 1][e]

[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]I can feel my bond with Mutatsu grow[n]stronger as we spend time together...[n][uf 1 1][e]

[msg MSG_002_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 3 0 65535 12288 0 0][uf 5 13 17 5 114]I bet people say you're a pretty weird girl, huh?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 114 1 65535 65535 0 0][uf 4 23 0 114 1 25 25]Well, that ain't a bad thing.[n][uf 1 1][e]

[msg MND_003_0_0]
[uf 0 5 65278][uf 2 1]I can feel my bond with Mutatsu grow[n]stronger as we spend time together...[n][uf 1 1][e]

[msg MSG_004_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 1 65535 65535 0 0][uf 3 1 3 0 65535 12292 0 0][uf 5 13 17 5 114][uf 4 23 0 114 1 25 25]Y'know, all you need to get through life is a smile. Why don'tcha try showin' off your pearly whites like me?[n][uf 1 1][e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]I can feel my bond with Mutatsu grow[n]stronger as we spend time together...[n][uf 1 1][e]

[msg MSG_006_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 0 65535 65535 0 0][uf 3 1 3 0 65535 12218 0 0][uf 5 13 17 5 114]They say men're s'pposed to be ballsy and women charmin' but it's really the other way around, see.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 114 1 65535 65535 0 0][uf 4 23 0 114 1 25 25]Well, if you're plenty attractive, anyone'd open up to ya though.[n][uf 1 1][e]

[msg MND_007_0_0]
[uf 0 5 65278][uf 2 1]I can feel my bond with Mutatsu grow[n]stronger as we spend time together...[n][uf 1 1][e]

[msg MND_008_0_0]
[uf 0 5 65278][uf 2 1]I feel like our relationship[n]will grow stronger soon...[n][uf 1 1][e]

[msg MND_009_0_0]
[uf 0 5 65278][uf 2 1]It's getting late...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I decided to go back to the dorm.[n][uf 1 1][e]

