[msg SYS_PERSONA_DROP]
[f 2 1][clr 35][f 2 4 0][clr 27] adlı Personayı serbest bırakmak istediğine emin misin?[f 1 4 1][n][w][e]

[msg SYS_PERSONA_DROP_NG]
[f 2 1]Donanılan mevcut Personayı serbest bırakamazsın.[n][w][e]

[msg SYS_PERSONA_SET]
[f 2 1]Bu Persona donanılsın mı?[n][f 1 4 1][w][e]

[msg SYS_PERSONA_EQUIPED]
[f 2 1][clr 35][f 2 4 0][clr 27] zaten donanıldı.[n][w][e]

[msg SYS_SKILL_FULL]
[f 2 1]Bu Persona daha fazla yetenek edinemez. [n]Lütfen unutmak için bir tanesini seç.[n][w][e]

[msg SYS_SKILL_FORGET]
[f 2 1][clr 35][f 2 4 0][clr 27] unutulsun mu?[n][f 1 4 1][w][e]

[msg SYS_BIRTH_CONCEPTION]
[f 2 1][clr 35][f 2 4 0][clr 27], [f 4 4 1 37 1 1] yarattı.[n][w][e]

[msg SYS_SKILLCARD_ALREADY]
[f 2 1][clr 35][f 2 4 0][clr 27] zaten öğrenildi.[n][w][e]

[msg SYS_SKILL_CHANGE [Igor]]

[msg SYS_REMEMBER_CONF]
[f 2 1]Çıkış yapmak istediğine emin misin?[n][f 1 4 1][w][e]

[msg SYS_NO_EFFECT_INCENSE]
[f 2 1]Zaten sınıra ulaşıldı.[n][w][e]

[msg SYS_SYSTEM_BACK_TO_TITLE]
[f 2 1]Başlık ekranına geri dönülsün mü?[n][f 1 4 1][w][e]

[msg SYS_TITL_USE_NETWORK]
[f 2 1][f 1 4 1]Bu oyun, ağa bağlanıldığında çevrimiçi özellikleri destekler.[n][f 1 5 0]Bu özellikleri şimdi etkinleştirmek istiyor musun?[n][w][e]

[msg SYS_TITL_DONT_USE_NETWOR]
[f 2 1]Ağ işlevselliği [clr 2]KAPATILDI[clr 27].[n][f 1 5 0]Bunu Yapılandırma menüsünden istediğin zaman değiştirebilirsin.[n][w][e]

[msg SYS_SAVE_LOAD_CHECK]
[f 2 1]Bu kayıt verileri yüklensin mi?[n][f 1 4 1][w][e]

[msg SYS_SAVE_LOAD_OK [Igor]]

[msg SYS_SAVE_NETWORK_LOAD]
[f 2 1]Ağ kaydı verileri yükleniyor...[n][w][e]

[msg SYS_SAVE_NETWORK_LOAD_OK]
[f 2 1]Ağ kayıt verileri başarılı bir şekilde yüklendi.[n][w][e]

[msg SYS_SAVE_NETWORK_LOAD_ER]
[f 2 1]Ağ kayıt verileri yüklenemedi.[n][w][e]

[msg SYS_SAVE_NETWORK_UP]
[f 2 1]Kayıt verileri yükleniyor...[n][w][e]

[msg SYS_SAVE_NETWORK_UP_OK]
[f 2 1]Kayıt verileri başarılı bir şekilde yüklendi.[n][w][e]

[msg SYS_SAVE_NETWORK_UP_ERRO]
[f 2 1]Kayıt verileri yüklenemedi.[n][w][e]

[msg SYS_SAVE_NETWORK_BROKEN]
[f 2 1]Ağ kaydı verileri bozuldu.[n][w][e]

[msg SYS_SAVE_NETWORK_INVALID]
[f 2 1]Ağ işlevselliği şu anda devre dışı.[n][f 1 5 0]Bu ayarı Yapılandırma menüsünden değiştir.[n][w][e]

[msg SYS_SAVE_NETWORK_NOTEXIS]
[f 2 1]Ağa kayıtlı herhangi bir veri bulunamadı.[n][w][e]

[msg SYS_SAVE_OVERWRITE_CHECK]
[f 2 1]Kayıt verileri zaten mevcut.[n][f 1 5 0]Bu verileri geçersiz kılmak istiyor musun?[n][f 1 4 1][w][e]

[msg SYS_SAVE_OK [Igor]]

[msg SYS_SAVE_ROLLBACK_CHECK]
[f 2 1]Bu noktaya dönersen daha güncel geri sarma verileri kaybolacak.[n][f 1 5 0]Devam edilsin mi?[n][f 1 4 1][w][e]

[msg SYS_CONF_CLOSE_CHECK]
[f 2 1]Değişiklikler uygulanmadan çıkış yapılsın mı?[n][f 1 4 1][w][e]

[msg SYS_CONF_DIFF_CHECK]
[f 2 1]Acımasız zorluk düzeyini değiştirirsen eski hâline döndüremeyeceksin.[n][f 1 5 0]Devam etmek istediğine emin misin?[n][f 1 4 1][w][e]

[msg SYS_CONF_DIFF_CHANGED]
[f 2 1]Zorluk düzeyi [clr 2][f 2 4 0][clr 27] olarak değiştirildi.[n][w][e]

[msg SYS_CONF_CONNECT_ERROR]
[f 2 1]Ağ bağlantısı başarısız oldu.[n][w][e]

[msg SYS_CONF_CONNECTING]
[f 2 1]Ağa bağlanılıyor...[n][w][e]

[msg SYS_PARTY_MEMBEROVER_0_0]
[f 2 1]Maksimum takım kapasitesinden [f 2 4 0] üye fazla var.[n][w][e]

[msg SYS_DIFFICULTY_CHECK]
[f 2 1]Oyunu [clr 2][f 2 4 0][clr 27] zorluk düzeyinde mi başlatacaksın?[n][f 1 4 1][w][e]

[msg SYS_DIFFICULTY_DESC_SAFE]
[f 2 1]Hikayeye odaklanmak isteyen oyuncular için.[n][w][e]

[msg SYS_DIFFICULTY_DESC_EASY]
[f 2 1]Gelişigüzel oyuncular için.[n][w][e]

[msg SYS_DIFFICULTY_DESC_NORM]
[f 2 1]Tecrübeli oyuncular için.[n][w][e]

[msg SYS_DIFFICULTY_DESC_HARD]
[f 2 1]Strateji yapmaktan keyif alan oyuncular için.[n][w][e]

[msg SYS_DIFFICULTY_DESC_LUNA]
[f 2 1]Oldukça ileri düzeydeki oyuncular için.[n][w][e]

[msg SYS_DIFFICULTY_INFO_SAFE]
[f 2 1]Takımın yenilgiden sonra otomatik olarak canlanır. [clr 43]Zorluk seçimin hikayeyi etkilemez ve istediğin zaman değiştirilebilir (Acımasız dışında).[clr 27][n][w][e]

[msg SYS_DIFFICULTY_INFO_EASY]
[f 2 1]Muharebe az streslidir. [clr 43]Zorluk seçimin hikayeyi etkilemez ve istediğin zaman değiştirilebilir (Acımasız dışında).[clr 27][n][w][e]

[msg SYS_DIFFICULTY_INFO_NORM]
[f 2 1]Muharebe kısmen zordur. [clr 43]Zorluk seçimin hikayeyi etkilemez ve istediğin zaman değiştirilebilir (Acımasız dışında).[clr 27][n][w][e]

[msg SYS_DIFFICULTY_INFO_HARD]
[f 2 1]Muharebe önemli ölçüde zordur. [clr 43]Zorluk seçimin hikayeyi etkilemez ve istediğin zaman değiştirilebilir (Acımasız dışında).[clr 27][n][w][e]

[msg SYS_DIFFICULTY_INFO_LUNA]
[f 2 1]Muharebe aşırı derecede zordur. [clr 43]Zorluk seçimin hikayeyi etkilemez ve istediğin zaman değiştirilebilir ama Acımasız zorluğundan vazgeçtiğinde bu zorluğa geri dönemezsin.[clr 27][n][w][e]

[msg MND_SKILL_NOT_CHANGE]
[f 2 1][f 2 4 2] tiz bir şekilde haykırır.[n][w][e]

[msg SYS_NETWORK_CONNECT_CHEC [Igor]]

[msg SYS_NETWORK_CONNECT_YES]
[f 2 1]Ağ işlevselliği [clr 2]AÇILDI[clr 27].[n][f 1 5 0]Bunu Yapılandırma menüsünden istediğin zaman değiştirebilirsin.[n][w][e]

[msg SYS_NETWORK_CONNECT_NO [Igor]]

[msg SYS_NETWORK_VOICE_ERROR]
[f 2 1]Ağ hatası. Lütfen bağlantını kontrol et.[n][w][e]

[msg MSG_SKILL_CHANGE [Igor]]
[f 2 1]Ha?.. Yeteneklerinden biri değişmek üzere gibi görünüyor... Devam edecek misin?[n][w][e]

[sel SEL_SKILL_CHANGE top]
[f 2 1]Yetenek değişimini engelle[e]
[f 2 1]Yetenek değişimini kabul et[e]
[f 2 1]Yetenekleri kontrol et[e]

[msg SYS_PARTY_FIXED_MEMBER_0]
[f 2 1][f 2 4 0], takımında olmalı.[n][w][e]

[msg SYS_RECHECK_BACK_TO_TITL]
[f 2 1]Son oyun kaydından bu noktaya kadar gerçekleştirdiğin tüm ilerlemeyi kaybedeceksin.[n][f 1 5 0]Başlık ekranına dönmek istediğine emin misin?[n][f 1 4 1][w][e]

[msg SYS_GAMEDATA_INSTALL]
[f 2 1]Oyun verisi yükleniyor...[n][w][e]

[msg SYS_GAMEDATA_INSTALL_OK]
[f 2 1]Yükleme tamamlandı.[n][w][e]

[msg SYS_ACTIVITY_DATA_NOT_MA]
[f 2 1]Seçili aktivite, son kaydedilen verilerin durumuyla eşleşmedi.[n][f 1 5 0]Oyun normal bir şekilde başlayacak.[n][w][e]

[msg SYS_KEYCONFIG_ASSIGN]
[f 2 1]Şuna bağlamak için bir tuş gir: [clr 35][f 2 4 0][clr 27].[n][f 1 5 0]Ayarlar menüsüne dönmek için Esc tuşuna bas.[n][w][e]

[msg SYS_KEYCONFIG_OVERWRITE]
[f 2 1]Seçili tuş bağlamada bir uyuşmazlık var: [clr 2][f 2 4 0][clr 27][n][f 1 5 0]Mevcut tuş bağlama geçersiz kılınsın mı?[n][f 1 5 0][f 1 4 1][f 1 5 0][f 1 5 0][f 1 5 0][w][e]

[msg SYS_KEYCONFIG_FINISH]
[f 2 1]Mevcut ayarlarla bitirilsin mi?[n][f 1 4 1][w][e]

[msg SYS_KEYCONFIG_NOT_SET]
[f 2 1]Bazı yapılandırmalar ayarlanmadı.[n][w][e]

[msg SYS_KEYCONFIG_RESET_KEYB]
[f 2 1]Klavye yapılandırmasının varsayılan ayarları geri yüklensin mi?[n][f 1 4 1][w][e]

[msg SYS_KEYCONFIG_RESET_MOUS]
[f 2 1]Fare yapılandırmasının varsayılan ayarları geri yüklensin mi?[n][f 1 4 1][w][e]

[msg SYS_KEYCONFIG_RESET_GAME]
[f 2 1]Oyun kumandası yapılandırmasının varsayılan ayarları geri yüklensin mi?[n][f 1 4 1][w][e]

[msg SYS_CONF_DISPLAY_CHECK]
[f 2 1]Görüntü ayarları düzenlendi. Bu değişiklikleri saklamak istediğinden emin misin?[n][f 1 5 0]Oyuncu giriş yapmadığı takdirde [f 2 4 0] saniye sonra ayarlar eski hâline dönecek.[n][f 1 4 1][w][e]

[msg SYS_INPUT_DEVICE_LOST]
[f 2 1]Bir cihazın bağlantısı koptu. Lütfen bağlantı durumunu kontrol et.[n][w][e]

[msg SYS_SAVE_NO_SPACE]
[f 2 1]Kaydetme başarısız oldu. Lütfen mevcut depo alanını kontrol et.[n][w][e]

[msg SYS_APP_QUIT]
[f 2 1]Oyundan çıkılsın mı?[n][f 1 4 1][w][e]

[msg SYS_APPLY_INIT_NAME_STOR]
[f 2 1]Dil ayarlarındaki bir değişiklikten dolayı ana karakterin adı varsayılan olarak "Kotone Shiomi" olacak.[n][f 1 5 0]Orijinal adı geri getirmek için dil, ad girilirken kullanılan dille aynı olmalı.[n][w][e]

[msg SYS_APPLY_INIT_NAME_NETW]
[f 2 1]Dil ayarlarındaki bir değişiklikten dolayı ana karakterin adı varsayılan olarak "Kotone Shiomi" olacak.[n][f 1 5 0]Orijinal adı geri getirmek için dil, ad girilirken kullanılan dille aynı olmalı.[n][w][e]

