[msg Item_000]
[f 2 1]未使用[n][e]

[msg Item_001]
[f 2 1]Son teknoloji, seyyar bir müzik çalar.[n][e]

[msg Item_002]
[f 2 1]Kalp şeklinde sevimli, beyaz bir tasma kolye.[n][e]

[msg Item_003]
[f 2 1]Şık, gümüş bir kolye. Şu aralar erkek moda dergilerinde popüler.[n][e]

[msg Item_004]
[f 2 1]İnce deri eldiven. Mükemmel bir şekilde ellerini sarar.[n][e]

[msg Item_005]
[f 2 1]Güzel değerli taşlarla süslü takma tırnaklar. Görkemli ve şık.[n][e]

[msg Item_006]
[f 2 1]Lise çağındaki kızlar arasında çok popüler olan sevimli bir kolye.[n][e]

[msg Item_007]
[f 2 1]Büyük, kızıl bir kurdele. Yakaya zarafet ve renk katar.[n][e]

[msg Item_008]
[f 2 1]Sportif insanlar için tasarlanmış sade bir bileklik.[n][e]

[msg Item_009]
[f 2 1]Melek kanatlarını andıran süslü bir aksesuar. Çok az işlevseldir.[n][e]

[msg Item_00A]
[f 2 1]Erkekler için sade, gösterişsiz bir başlık.[n][e]

[msg Item_00B]
[f 2 1]Sert bir halat bandı. Fiziksel gücü biraz artırır.[n][e]

[msg Item_00C]
[f 2 1]Sert bir halat bandı. Fiziksel gücü az çok artırır.[n][e]

[msg Item_00D]
[f 2 1]Sert bir halat bandı. Fiziksel gücü önemli ölçüde artırır.[n][e]

[msg Item_00E]
[f 2 1]Mistik bir ipek bant. Büyü gücünü biraz artırır.[n][e]

[msg Item_00F]
[f 2 1]Mistik bir ipek bant. Büyü gücünü az çok artırır.[n][e]

[msg Item_010]
[f 2 1]Mistik bir ipek bant. Büyü gücünü önemli ölçüde artırır.[n][e]

[msg Item_011]
[f 2 1]Sağlam bir çelik bant. Savunma mukavemetini biraz artırır.[n][e]

[msg Item_012]
[f 2 1]Sağlam bir çelik bant. Savunma mukavemetini az çok artırır.[n][e]

[msg Item_013]
[f 2 1]Sağlam bir çelik bant. Savunma mukavemetini önemli ölçüde artırır.[n][e]

[msg Item_014]
[f 2 1]Havadar bir kumaş bant. İnsanın kendisini biraz daha hafif hissetmesini sağlar.[n][e]

[msg Item_015]
[f 2 1]Havadar bir kumaş bant. İnsanın kendisini az çok daha hafif hissetmesini sağlar.[n][e]

[msg Item_016]
[f 2 1]Havadar bir kumaş bant. İnsanın kendisini önemli ölçüde daha hafif hissetmesini sağlar.[n][e]

[msg Item_017]
[f 2 1]Çarpıcı bir örgü bant. İyi talihi biraz artırır.[n][e]

[msg Item_018]
[f 2 1]Çarpıcı bir örgü bant. İyi talihi az çok artırır.[n][e]

[msg Item_019]
[f 2 1]Çarpıcı bir örgü bant. İyi talihi önemli ölçüde artırır.[n][e]

[msg Item_01A]
[f 2 1]Lüks bir gümüş bant. Tüm özellikleri biraz artırır.[n][e]

[msg Item_01B]
[f 2 1]Lüks bir saydam bant. Tüm özellikleri önemli ölçüde artırır.[n][e]

[msg Item_01C]
[f 2 1]未使用[n][e]

[msg Item_01D]
[f 2 1]未使用[n][e]

[msg Item_01E]
[f 2 1]未使用[n][e]

[msg Item_01F]
[f 2 1]未使用[n][e]

[msg Item_020]
[f 2 1]Sert bir halat bandı. Fiziksel gücü büyük ölçüde artırır.[n][e]

[msg Item_021]
[f 2 1]Mistik bir ipek bant. Büyü gücünü büyük ölçüde artırır.[n][e]

[msg Item_022]
[f 2 1]Sağlam bir çelik bant. Savunma mukavemetini büyük ölçüde artırır.[n][e]

[msg Item_023]
[f 2 1]Havadar bir kumaş bant. İnsanın kendisini büyük ölçüde daha hafif hissetmesini sağlar.[n][e]

[msg Item_024]
[f 2 1]Çarpıcı bir örgü bant. İyi talihi büyük ölçüde artırır.[n][e]

[msg Item_025]
[f 2 1]未使用[n][e]

[msg Item_026]
[f 2 1]未使用[n][e]

[msg Item_027]
[f 2 1]Giyen kişiyi savaşın başında geçici olarak güçlendirir.[n][e]

[msg Item_028]
[f 2 1]Giyen kişiyi savaşın başında geçici olarak daha dayanıklı kılar.[n][e]

[msg Item_029]
[f 2 1]Giyen kişiyi savaşın başında geçici olarak daha çevik kılar.[n][e]

[msg Item_02A]
[f 2 1]Üzerinde bir alev tasarımı bulunan bir bilezik. Ateş hasarını artırır.[n][e]

[msg Item_02B]
[f 2 1]Ateş tanrısının gücünü içinde barındırır. Ateş hasarını fazlasıyla artırır.[n][e]

[msg Item_02C]
[f 2 1]Üzerinde bir buzul tasarımı bulunan bir bilezik. Buz hasarını artırır.[n][e]

[msg Item_02D]
[f 2 1]Buz tanrısının gücünü içinde barındırır. Buz hasarını fazlasıyla artırır.[n][e]

[msg Item_02E]
[f 2 1]Üzerinde bir yıldırım tasarımı bulunan bir bilezik. Elektrik hasarını artırır.[n][e]

[msg Item_02F]
[f 2 1]Gökyüzü tanrısının gücünü içinde barındırır. Elektrik hasarını fazlasıyla artırır.[n][e]

[msg Item_030]
[f 2 1]Üzerinde bir fırtına tasarımı bulunan bir bilezik. Rüzgar hasarını artırır.[n][e]

[msg Item_031]
[f 2 1]Rüzgar tanrısının gücünü içinde barındırır. Rüzgar hasarını fazlasıyla artırır.[n][e]

[msg Item_032]
[f 2 1]Öfkelendiğinde takan kişinin Saldırı gücünü artıran gizemli bir tespih.[n][e]

[msg Item_033]
[f 2 1]Sevimli bir bal kabağı maskesi. Karanlık hasarını artırır.[n][e]

[msg Item_034]
[f 2 1]Tüm müttefikleri savaşın başında geçici olarak güçlendirir.[n][e]

[msg Item_035]
[f 2 1]Tüm müttefikleri savaşın başında geçici olarak daha dayanıklı kılar.[n][e]

[msg Item_036]
[f 2 1]Tüm müttefikleri savaşın başında geçici olarak daha çevik kılar.[n][e]

[msg Item_037]
[f 2 1]Savaşın başında giyen kişinin kritik oranını geçici olarak artırır.[n][e]

[msg Item_038]
[f 2 1]未使用[n][e]

[msg Item_039]
[f 2 1]Fiziksel saldırılardan kaçınma tekniklerine dair eğitici bir metin.[n][e]

[msg Item_03A]
[f 2 1]İlkel bir tılsım. Büyü saldırılarından kaçınma becerisi bahşeder.[n][e]

[msg Item_03B]
[f 2 1]Kesik saldırılarından kaçınma tekniklerine dair eğitici bir metin.[n][e]

[msg Item_03C]
[f 2 1]Kesik saldırılarından daha kolay kaçınmak için gelişmiş bir öğreti metni.[n][e]

[msg Item_03D]
[f 2 1]Vuruş saldırılarından kaçınma tekniklerine dair eğitici bir metin.[n][e]

[msg Item_03E]
[f 2 1]Vuruş saldırılarından daha kolay kaçınmak için gelişmiş bir öğreti metni.[n][e]

[msg Item_03F]
[f 2 1]Delme saldırılarından kaçınma tekniklerine dair eğitici bir metin.[n][e]

[msg Item_040]
[f 2 1]Delme saldırılarından daha kolay kaçınmak için gelişmiş bir öğreti metni.[n][e]

[msg Item_041]
[f 2 1]İlkel bir tılsım. Ateş saldırılarından kaçınma becerisi bahşeder.[n][e]

[msg Item_042]
[f 2 1]Ateş saldırılarından kaçınma becerisini fazlasıyla artırır.[n][e]

[msg Item_043]
[f 2 1]İlkel bir tılsım. Buz saldırılarından kaçınma becerisi bahşeder.[n][e]

[msg Item_044]
[f 2 1]Buz saldırılarından kaçınma becerisini fazlasıyla artırır.[n][e]

[msg Item_045]
[f 2 1]İlkel bir tılsım. Rüzgar saldırılarından kaçınma becerisi bahşeder.[n][e]

[msg Item_046]
[f 2 1]Rüzgar saldırılarından kaçınma becerisini fazlasıyla artırır.[n][e]

[msg Item_047]
[f 2 1]İlkel bir tılsım. Elektrik saldırılarından kaçınma becerisi bahşeder.[n][e]

[msg Item_048]
[f 2 1]Elektrik saldırılarından kaçınma becerisini fazlasıyla artırır.[n][e]

[msg Item_049]
[f 2 1]Bu güçlü rastalar, insanın fiziksel saldırılara tepki verme becerisini geliştirir.[n][e]

[msg Item_04A]
[f 2 1]Büyü saldırılarından kaçınmanın sırlarını tasvir eden antik bir metin.[n][e]

[msg Item_04B]
[f 2 1]Göz korkutucu bir kol bandı. Giyen kişiye vurmayı zorlaştırır.[n][e]

[msg Item_04C]
[f 2 1]İlkel bir tılsım. Işık saldırılarından kaçınma becerisi bahşeder.[n][e]

[msg Item_04D]
[f 2 1]Işık saldırılarından kaçınma becerisini fazlasıyla artırır.[n][e]

[msg Item_04E]
[f 2 1]İlkel bir tılsım. Karanlık saldırılarından kaçınma becerisi bahşeder.[n][e]

[msg Item_04F]
[f 2 1]Karanlık saldırılarından kaçınma becerisini fazlasıyla artırır.[n][e]

[msg Item_050]
[f 2 1]未使用[n][e]

[msg Item_051]
[f 2 1]Bir zamanlar Kılıçlar Tanrısı'nın kullandığı çelik bir kın. Tüm kılıçları engellediği söylenir.[n][e]

[msg Item_052]
[f 2 1]Kalın, altın bir pul. Kör saldırılara karşı savunmasız.[n][e]

[msg Item_053]
[f 2 1]Delinemeyen, dayanıklı bir toprak figür.[n][e]

[msg Item_054]
[f 2 1]Alevle işlenmiş bir taş. Alevi, sıcağıyla diğer tüm sıcakları önemsiz kılar.[n][e]

[msg Item_055]
[f 2 1]Güzel, lacivert bir kristal. Tüm ayaz ve üşüme biçimlerini keser.[n][e]

[msg Item_056]
[f 2 1]Gök gürültüsü tanrısının giydiği eldiven. Tüm elektriği dağıtır.[n][e]

[msg Item_057]
[f 2 1]Mersin ağacına benzer şekillendirilmiş bir yüzük. En şiddetli fırtınaları bile bastırır.[n][e]

[msg Item_058]
[f 2 1]Saf beyaz bir yüzük. Kutsal güç biçimlerinden korur.[n][e]

[msg Item_059]
[f 2 1]Obsidiyen siyahı bir yüzük. Karanlık kuvvetleri engeller.[n][e]

[msg Item_05A]
[f 2 1]Buzlu bir aura yayan özel bir pazubent. Donmayı önler.[n][e]

[msg Item_05B]
[f 2 1]Statik bir aura yayan özel bir pazubent. Şoku önler.[n][e]

[msg Item_05C]
[f 2 1]Tek boynuzlu bir atın boynuzu gibi şekillendirilmiş bir aksesuar. Zehri önler.[n][e]

[msg Item_05D]
[f 2 1]Bir ruh sürüsüne benzeyen bir süs. Kafa Karışıklığını önler.[n][e]

[msg Item_05E]
[f 2 1]Bir pranga. Tuhaf bir şekilde rahatlatıcı. Endişeyi önler.[n][e]

[msg Item_05F]
[f 2 1]Tüm ayartmaları kaldıran, çiçekli bir süsleme. Efsunu önler.[n][e]

[msg Item_060]
[f 2 1]Avuç büyüklüğünde bir göz küresi. Sıkınca sinirlerin gevşer. Korkuyu önler.[n][e]

[msg Item_061]
[f 2 1]Lüks, mavi bir yüzük. Buna bakınca öfken yatışır. Öfkeyi önler.[n][e]

[msg Item_062]
[f 2 1]Kafa Karışıklığını, Endişeyi, Efsunu, Korkuyu ve Öfkeyi önleyen bir kitap.[n][e]

[msg Item_063]
[f 2 1]Neredeyse yok edilemez, bilinmeyen bir malzemeden yapılmış bir küre.[n][e]

[msg Item_064]
[f 2 1]Usta bir savaşçının işareti. Fiziksel saldırılara karşılık verme ihtimali düşük.[n][e]

[msg Item_065]
[f 2 1]Bir savaş tanrısının işareti. Fiziksel saldırılara karşılık verme ihtimali orta.[n][e]

[msg Item_066]
[f 2 1]Korkunç bir asinin işareti. Fiziksel saldırılara karşılık verme ihtimali yüksek.[n][e]

[msg Item_067]
[f 2 1]Kutsal bir eser. Kullanıcı kaçınamaz ama alınan hasar yarıya indirilir.[n][e]

[msg Item_068]
[f 2 1]Zifiri karanlıkta bile kusursuz görüş sunan yüksek donanımlı gözlük.[n][e]

[msg Item_069]
[f 2 1]Korku ve ayartma gibi zihin hastalıklarını defetmeye yardımcı olur.[n][e]

[msg Item_06A]
[f 2 1]Yatıştırıcı aromaya sahip bir odun parçası. Rahatsızlık iyileşmesini hızlandırır.[n][e]

[msg Item_06B]
[f 2 1]Hoş bir koku içerir. Durum rahatsızlıklarını anında tedavi eder.[n][e]

[msg Item_06C]
[f 2 1]未使用[n][e]

[msg Item_06D]
[f 2 1]Bu mühür, toprağın gücünü yayar. Her turda azıcık SP yeniler.[n][e]

[msg Item_06E]
[f 2 1]Bu mühür, Dünya'nın gücünü yayar. Her turda birazcık SP yeniler.[n][e]

[msg Item_06F]
[f 2 1]Bu mühür, uzayın gücünü yayar. Her turda biraz SP yeniler.[n][e]

[msg Item_070]
[f 2 1]Çi'nin gücünü uyandıran bir rozet. Her turda azıcık RP yeniler.[n][e]

[msg Item_071]
[f 2 1]Çi'nin gücünü artıran bir rozet. Her turda birazcık RP yeniler.[n][e]

[msg Item_072]
[f 2 1]Çi'nin gücüyle dolup taşan bir rozet. Her turda biraz RP yeniler.[n][e]

[msg Item_073]
[f 2 1]Maiko'dan alınan sevimli bir bebek. Her turda azıcık RP yeniler.[n][e]

[msg Item_074]
[f 2 1]未使用[n][e]

[msg Item_075]
[f 2 1]Her savaşta bir defa, ölünce tüm SP'yi yenileyen ilahi bir eser.[n][e]

[msg Item_076]
[f 2 1]1 SP ile tek bir Karanlık ani ölüm saldırısından kurtulmaya imkan tanıyan dua tespihi.[n][e]

[msg Item_077]
[f 2 1]1 SP ile tek bir Işık ani ölüm saldırısından kurtulmaya imkan tanıyan aksesuar.[n][e]

[msg Item_078]
[f 2 1]1 SP ile tek bir ani ölüm saldırısından kurtulmaya imkan tanıyan bilezik.[n][e]

[msg Item_079]
[f 2 1]未使用[n][e]

[msg Item_07A]
[f 2 1]未使用[n][e]

[msg Item_07B]
[f 2 1]未使用[n][e]

[msg Item_07C]
[f 2 1]未使用[n][e]

[msg Item_07D]
[f 2 1]Maliyetli malzemelerden yapılmış bir broş. Pahalıdır ama hiçbir işe yaramaz.[n][e]

[msg Item_07E]
[f 2 1]Fiziksel yeteneklerin SP maliyetini yarıya düşüren bir yüzük.[n][e]

[msg Item_07F]
[f 2 1]Büyü yeteneklerinin RP maliyetini yarıya düşüren bir yüzük.[n][e]

[msg Item_080]
[f 2 1]未使用[n][e]

[msg Item_081]
[f 2 1]Kritik vuruş almaya devam etme olasılığını düşürür.[n][e]

[msg Item_082]
[f 2 1]Kullanıcının kritik oranını artırır.[n][e]

[msg Item_083]
[f 2 1]未使用[n][e]

[msg Item_084]
[f 2 1]未使用[n][e]

[msg Item_085]
[f 2 1]Samurayların giydiğine benzer bir kuşak. Azıcık zindelik uyandırır.[n][e]

[msg Item_086]
[f 2 1]Samurayların giydiğine benzer bir kuşak. Birazcık zindelik uyandırır.[n][e]

[msg Item_087]
[f 2 1]Samurayların giydiğine benzer bir kuşak. Biraz zindelik uyandırır.[n][e]

[msg Item_088]
[f 2 1]Samurayların giydiğine benzer bir kuşak. Önemli ölçüde zindelik uyandırır.[n][e]

[msg Item_089]
[f 2 1]Samurayların giydiğine benzer bir kuşak. Büyük ölçüde zindelik uyandırır.[n][e]

[msg Item_08A]
[f 2 1]İçinde sayısız askerin ruhunun yaşadığı kalın, kırmızı bir sancak.[n][e]

[msg Item_08B]
[f 2 1]Bir cadının kullanabileceği bir tılsım. Azıcık büyü gücü uyandırır.[n][e]

[msg Item_08C]
[f 2 1]Bir cadının kullanabileceği bir tılsım. Birazcık büyü gücü uyandırır.[n][e]

[msg Item_08D]
[f 2 1]Bir cadının kullanabileceği bir tılsım. Biraz büyü gücü uyandırır.[n][e]

[msg Item_08E]
[f 2 1]Bir cadının kullanabileceği bir tılsım. Önemli ölçüde büyü gücü uyandırır.[n][e]

[msg Item_08F]
[f 2 1]Bir cadının kullanabileceği bir tılsım. Büyük ölçüde büyü gücü uyandırır.[n][e]

[msg Item_090]
[f 2 1]Rünler kazınmış bir saç aksesuarı. Takan kişinin altıncı hissini serbest bırakır.[n][e]

[msg Item_091]
[f 2 1]Takan kişiye savaşta daha fazla deneyim veren bir yüzük.[n][e]

[msg Item_092]
[f 2 1]Kullanıcının savaştaki deneyimini en üst düzeye çıkaran bir tılsım.[n][e]

[msg Item_093]
[f 2 1]未使用[n][e]

[msg Item_094]
[f 2 1]未使用[n][e]

[msg Item_095]
[f 2 1]未使用[n][e]

[msg Item_096]
[f 2 1]未使用[n][e]

[msg Item_097]
[f 2 1]未使用[n][e]

[msg Item_098]
[f 2 1]未使用[n][e]

[msg Item_099]
[f 2 1]未使用[n][e]

[msg Item_09A]
[f 2 1]未使用[n][e]

[msg Item_09B]
[f 2 1]O kadar gürültülüdür ki takan kişinin dikkati dağılmaz. Baş Dönmesini önler.[n][e]

[msg Item_09C]
[f 2 1]未使用[n][e]

[msg Item_09D]
[f 2 1]未使用[n][e]

[msg Item_09E]
[f 2 1]未使用[n][e]

[msg Item_09F]
[f 2 1]未使用[n][e]

[msg Item_0A0]
[f 2 1]未使用[n][e]

[msg Item_0A1]
[f 2 1]未使用[n][e]

[msg Item_0A2]
[f 2 1]未使用[n][e]

[msg Item_0A3]
[f 2 1]未使用[n][e]

[msg Item_0A4]
[f 2 1]Donma ihtimalini düşüren ahşap bir etiket.[n][e]

[msg Item_0A5]
[f 2 1]Şok olma ihtimalini düşüren ahşap bir etiket.[n][e]

[msg Item_0A6]
[f 2 1]Zehirlenme ihtimalini düşüren ahşap bir etiket.[n][e]

[msg Item_0A7]
[f 2 1]Kafa karışıklığı ihtimalini düşüren ahşap bir etiket.[n][e]

[msg Item_0A8]
[f 2 1]Endişelenme ihtimalini düşüren ahşap bir etiket.[n][e]

[msg Item_0A9]
[f 2 1]Çıldırma ihtimalini düşüren ahşap bir etiket.[n][e]

[msg Item_0AA]
[f 2 1]Korkma ihtimalini düşüren ahşap bir etiket.[n][e]

[msg Item_0AB]
[f 2 1]Öfkelenme ihtimalini düşüren ahşap bir etiket.[n][e]

[msg Item_0AC]
[f 2 1]未使用[n][e]

[msg Item_0AD]
[f 2 1]未使用[n][e]

[msg Item_0AE]
[f 2 1]未使用[n][e]

[msg Item_0AF]
[f 2 1]未使用[n][e]

[msg Item_0B0]
[f 2 1]未使用[n][e]

[msg Item_0B1]
[f 2 1]未使用[n][e]

[msg Item_0B2]
[f 2 1]未使用[n][e]

[msg Item_0B3]
[f 2 1]未使用[n][e]

[msg Item_0B4]
[f 2 1]Kafa Karışıklığı etkisi verme ihtimalini artıran ahşap bir etiket.[n][e]

[msg Item_0B5]
[f 2 1]Endişe etkisi verme ihtimalini artıran ahşap bir etiket.[n][e]

[msg Item_0B6]
[f 2 1]未使用[n][e]

[msg Item_0B7]
[f 2 1]Korku etkisi verme ihtimalini artıran ahşap bir etiket.[n][e]

[msg Item_0B8]
[f 2 1]未使用[n][e]

[msg Item_0B9]
[f 2 1]Baş Dönmesi etkisi verme ihtimalini artıran ahşap bir etiket.[n][e]

[msg Item_0BA]
[f 2 1]未使用[n][e]

[msg Item_0BB]
[f 2 1]未使用[n][e]

[msg Item_0BC]
[f 2 1]未使用[n][e]

[msg Item_0BD]
[f 2 1]未使用[n][e]

[msg Item_0BE]
[f 2 1]未使用[n][e]

[msg Item_0BF]
[f 2 1]未使用[n][e]

[msg Item_0C0]
[f 2 1]未使用[n][e]

[msg Item_0C1]
[f 2 1]未使用[n][e]

[msg Item_0C2]
[f 2 1]未使用[n][e]

[msg Item_0C3]
[f 2 1]未使用[n][e]

[msg Item_0C4]
[f 2 1]未使用[n][e]

[msg Item_0C5]
[f 2 1]未使用[n][e]

[msg Item_0C6]
[f 2 1]未使用[n][e]

[msg Item_0C7]
[f 2 1]未使用[n][e]

[msg Item_0C8]
[f 2 1]Kesik saldırılarından alınan hasarı biraz azaltan bir küpe.[n][e]

[msg Item_0C9]
[f 2 1]Kesik saldırılarından alınan hasarı kısmen azaltan bir broş.[n][e]

[msg Item_0CA]
[f 2 1]Kesik saldırılarından alınan hasarı aşırı derecede azaltan bir kolye.[n][e]

[msg Item_0CB]
[f 2 1]Vuruş saldırılarından alınan hasarı biraz azaltan bir küpe.[n][e]

[msg Item_0CC]
[f 2 1]Vuruş saldırılarından alınan hasarı kısmen azaltan bir broş.[n][e]

[msg Item_0CD]
[f 2 1]Vuruş saldırılarından alınan hasarı aşırı derecede azaltan bir kolye.[n][e]

[msg Item_0CE]
[f 2 1]Delme saldırılarından alınan hasarı biraz azaltan bir küpe.[n][e]

[msg Item_0CF]
[f 2 1]Delme saldırılarından alınan hasarı kısmen azaltan bir broş.[n][e]

[msg Item_0D0]
[f 2 1]Delme saldırılarından alınan hasarı aşırı derecede azaltan bir kolye.[n][e]

[msg Item_0D1]
[f 2 1]Fiziksel saldırılardan alınan hasarı biraz azaltan bir küpe.[n][e]

[msg Item_0D2]
[f 2 1]Fiziksel saldırılardan alınan hasarı kısmen azaltan bir broş.[n][e]

[msg Item_0D3]
[f 2 1]Fiziksel saldırılardan alınan hasarı aşırı derecede azaltan bir kolye.[n][e]

[msg Item_0D4]
[f 2 1]Ateş saldırılarından alınan hasarı biraz azaltan bir küpe.[n][e]

[msg Item_0D5]
[f 2 1]Ateş saldırılarından alınan hasarı kısmen azaltan bir broş.[n][e]

[msg Item_0D6]
[f 2 1]Ateş saldırılarından alınan hasarı aşırı derecede azaltan bir kolye.[n][e]

[msg Item_0D7]
[f 2 1]Buz saldırılarından alınan hasarı biraz azaltan bir küpe.[n][e]

[msg Item_0D8]
[f 2 1]Buz saldırılarından alınan hasarı kısmen azaltan bir broş.[n][e]

[msg Item_0D9]
[f 2 1]Buz saldırılarından alınan hasarı aşırı derecede azaltan bir kolye.[n][e]

[msg Item_0DA]
[f 2 1]Elektrik saldırılarından alınan hasarı biraz azaltan bir küpe.[n][e]

[msg Item_0DB]
[f 2 1]Elektrik saldırılarından alınan hasarı kısmen azaltan bir broş.[n][e]

[msg Item_0DC]
[f 2 1]Elektrik saldırılarından alınan hasarı aşırı derecede azaltan bir kolye.[n][e]

[msg Item_0DD]
[f 2 1]Rüzgar saldırılarından alınan hasarı biraz azaltan bir küpe.[n][e]

[msg Item_0DE]
[f 2 1]Rüzgar saldırılarından alınan hasarı kısmen azaltan bir broş.[n][e]

[msg Item_0DF]
[f 2 1]Rüzgar saldırılarından alınan hasarı aşırı derecede azaltan bir kolye.[n][e]

[msg Item_0E0]
[f 2 1]Işık saldırılarından alınan hasarı biraz azaltan bir küpe.[n][e]

[msg Item_0E1]
[f 2 1]Işık saldırılarından alınan hasarı kısmen azaltan bir broş.[n][e]

[msg Item_0E2]
[f 2 1]Işık saldırılarından alınan hasarı aşırı derecede azaltan bir kolye.[n][e]

[msg Item_0E3]
[f 2 1]Karanlık saldırılarından alınan hasarı biraz azaltan bir küpe.[n][e]

[msg Item_0E4]
[f 2 1]Karanlık saldırılarından alınan hasarı kısmen azaltan bir broş.[n][e]

[msg Item_0E5]
[f 2 1]Karanlık saldırılarından alınan hasarı aşırı derecede azaltan bir kolye.[n][e]

[msg Item_0E6]
[f 2 1]Büyü saldırılarından alınan hasarı biraz azaltan bir küpe.[n][e]

[msg Item_0E7]
[f 2 1]Büyü saldırılarından alınan hasarı kısmen azaltan bir broş.[n][e]

[msg Item_0E8]
[f 2 1]Büyü saldırılarından alınan hasarı aşırı derecede azaltan bir kolye.[n][e]

[msg Item_0E9]
[f 2 1]未使用[n][e]

[msg Item_0EA]
[f 2 1]未使用[n][e]

[msg Item_0EB]
[f 2 1]未使用[n][e]

[msg Item_0EC]
[f 2 1]未使用[n][e]

[msg Item_0ED]
[f 2 1]未使用[n][e]

[msg Item_0EE]
[f 2 1]未使用[n][e]

[msg Item_0EF]
[f 2 1]未使用[n][e]

[msg Item_0F0]
[f 2 1]Üzerinde parlak bir tasarım bulunan bir bilezik. Işık hasarını artırır.[n][e]

[msg Item_0F1]
[f 2 1]Seher tanrıçasının gücünü içerir. Işık hasarını fazlasıyla artırır.[n][e]

[msg Item_0F2]
[f 2 1]Üzerinde kasvetli bir tasarım bulunan bir bilezik. Karanlık hasarını artırır.[n][e]

[msg Item_0F3]
[f 2 1]Gece tanrıçasının gücünü içerir. Karanlık hasarını fazlasıyla artırır.[n][e]

[msg Item_0F4]
[f 2 1]Üzerinde bir kılıç tasarımı bulunan bir bilezik. Kesik hasarını artırır.[n][e]

[msg Item_0F5]
[f 2 1]İlahi kılıcın gücünü içerir. Kesik hasarını fazlasıyla artırır.[n][e]

[msg Item_0F6]
[f 2 1]Üzerinde bir yumruk tasarımı bulunan bir bilezik. Vuruş hasarını artırır.[n][e]

[msg Item_0F7]
[f 2 1]İlahi gürzün gücünü içerir. Vuruş hasarını fazlasıyla artırır.[n][e]

[msg Item_0F8]
[f 2 1]Üzerinde bir ok tasarımı bulunan bir bilezik. Delme hasarını artırır.[n][e]

[msg Item_0F9]
[f 2 1]İlahi yayın gücünü içerir. Delme hasarını fazlasıyla artırır.[n][e]

[msg Item_0FA]
[f 2 1]未使用[n][e]

[msg Item_0FB]
[f 2 1]未使用[n][e]

[msg Item_0FC]
[f 2 1]未使用[n][e]

[msg Item_0FD]
[f 2 1]未使用[n][e]

[msg Item_0FE]
[f 2 1]未使用[n][e]

[msg Item_0FF]
[f 2 1]未使用[n][e]

[msg Item_100]
[f 2 1]未使用[n][e]

[msg Item_101]
[f 2 1]未使用[n][e]

[msg Item_102]
[f 2 1]未使用[n][e]

[msg Item_103]
[f 2 1]未使用[n][e]

[msg Item_104]
[f 2 1]Savaşın başında 3 tur boyunca Ateş hasarına direnen bir şal.[n][e]

[msg Item_105]
[f 2 1]Savaşın başında 3 tur boyunca Buz hasarına direnen bir şal.[n][e]

[msg Item_106]
[f 2 1]Savaşın başında 3 tur boyunca Elektrik Direnci sağlayan bir şal.[n][e]

[msg Item_107]
[f 2 1]Savaşın başında 3 tur boyunca Rüzgar hasarına direnen bir şal.[n][e]

[msg Item_108]
[f 2 1]Giyen kişi, Değişimi alan tarafta olunca RP yeniler.[n][e]

[msg Item_109]
[f 2 1]Takan kişiyi manyetik bir alanla koruyan, prototip bir aksesuar.[n][e]

[msg Item_10A]
[f 2 1]Lüks bir altın bant. Tüm özellikleri az çok güçlendirir.[n][e]

[msg Item_10B]
[f 2 1]Giyen kişi, Değişimi alan tarafta olunca Saldırıyı artırır.[n][e]

[msg Item_10C]
[f 2 1]Her savaşta bir defa, ölünce tüm SP'yi yenileyen bir tılsım.[n][e]

[msg Item_10D]
[f 2 1]Takan kişinin bağlarıyla çalışan bir güç akınını serbest bırakır.[n][e]

[msg Item_10E]
[f 2 1]Chihiro'nun sana yaptığı sevimli bir anahtarlık.[n][e]

[msg Item_10F]
[f 2 1]Takan kişiyi tüm rahatsızlıklardan koruyan lüks bir kolye.[n][e]

[msg Item_110]
[f 2 1]Her savaşta bir defa, ölünce 1 SP yenileyen küpe.[n][e]

[msg Item_111]
[f 2 1]未使用[n][e]

[msg Item_112]
[f 2 1]未使用[n][e]

[msg Item_113]
[f 2 1]未使用[n][e]

[msg Item_114]
[f 2 1]未使用[n][e]

[msg Item_115]
[f 2 1]未使用[n][e]

[msg Item_116]
[f 2 1]未使用[n][e]

[msg Item_117]
[f 2 1]未使用[n][e]

[msg Item_118]
[f 2 1]未使用[n][e]

[msg Item_119]
[f 2 1]未使用[n][e]

[msg Item_11A]
[f 2 1]未使用[n][e]

[msg Item_11B]
[f 2 1]未使用[n][e]

[msg Item_11C]
[f 2 1]未使用[n][e]

[msg Item_11D]
[f 2 1]未使用[n][e]

[msg Item_11E]
[f 2 1]未使用[n][e]

[msg Item_11F]
[f 2 1]未使用[n][e]

[msg Item_120]
[f 2 1]未使用[n][e]

[msg Item_121]
[f 2 1]未使用[n][e]

[msg Item_122]
[f 2 1]未使用[n][e]

[msg Item_123]
[f 2 1]未使用[n][e]

[msg Item_124]
[f 2 1]未使用[n][e]

[msg Item_125]
[f 2 1]未使用[n][e]

[msg Item_126]
[f 2 1]未使用[n][e]

[msg Item_127]
[f 2 1]未使用[n][e]

[msg Item_128]
[f 2 1]未使用[n][e]

[msg Item_129]
[f 2 1]未使用[n][e]

[msg Item_12A]
[f 2 1]未使用[n][e]

[msg Item_12B]
[f 2 1]未使用[n][e]

[msg Item_12C]
[f 2 1]未使用[n][e]

[msg Item_12D]
[f 2 1]未使用[n][e]

[msg Item_12E]
[f 2 1]未使用[n][e]

[msg Item_12F]
[f 2 1]未使用[n][e]

[msg Item_130]
[f 2 1]未使用[n][e]

[msg Item_131]
[f 2 1]未使用[n][e]

[msg Item_132]
[f 2 1]未使用[n][e]

[msg Item_133]
[f 2 1]未使用[n][e]

[msg Item_134]
[f 2 1]未使用[n][e]

[msg Item_135]
[f 2 1]未使用[n][e]

[msg Item_136]
[f 2 1]未使用[n][e]

[msg Item_137]
[f 2 1]未使用[n][e]

[msg Item_138]
[f 2 1]未使用[n][e]

[msg Item_139]
[f 2 1]未使用[n][e]

[msg Item_13A]
[f 2 1]未使用[n][e]

[msg Item_13B]
[f 2 1]未使用[n][e]

[msg Item_13C]
[f 2 1]未使用[n][e]

[msg Item_13D]
[f 2 1]未使用[n][e]

[msg Item_13E]
[f 2 1]未使用[n][e]

[msg Item_13F]
[f 2 1]未使用[n][e]

[msg Item_140]
[f 2 1]未使用[n][e]

[msg Item_141]
[f 2 1]未使用[n][e]

[msg Item_142]
[f 2 1]未使用[n][e]

[msg Item_143]
[f 2 1]未使用[n][e]

[msg Item_144]
[f 2 1]未使用[n][e]

[msg Item_145]
[f 2 1]未使用[n][e]

[msg Item_146]
[f 2 1]未使用[n][e]

[msg Item_147]
[f 2 1]未使用[n][e]

[msg Item_148]
[f 2 1]未使用[n][e]

[msg Item_149]
[f 2 1]未使用[n][e]

[msg Item_14A]
[f 2 1]未使用[n][e]

[msg Item_14B]
[f 2 1]未使用[n][e]

[msg Item_14C]
[f 2 1]未使用[n][e]

[msg Item_14D]
[f 2 1]未使用[n][e]

[msg Item_14E]
[f 2 1]未使用[n][e]

[msg Item_14F]
[f 2 1]未使用[n][e]

[msg Item_150]
[f 2 1]未使用[n][e]

[msg Item_151]
[f 2 1]未使用[n][e]

[msg Item_152]
[f 2 1]未使用[n][e]

[msg Item_153]
[f 2 1]未使用[n][e]

[msg Item_154]
[f 2 1]未使用[n][e]

[msg Item_155]
[f 2 1]未使用[n][e]

[msg Item_156]
[f 2 1]未使用[n][e]

[msg Item_157]
[f 2 1]未使用[n][e]

[msg Item_158]
[f 2 1]未使用[n][e]

[msg Item_159]
[f 2 1]未使用[n][e]

[msg Item_15A]
[f 2 1]未使用[n][e]

[msg Item_15B]
[f 2 1]未使用[n][e]

[msg Item_15C]
[f 2 1]未使用[n][e]

[msg Item_15D]
[f 2 1]未使用[n][e]

[msg Item_15E]
[f 2 1]未使用[n][e]

[msg Item_15F]
[f 2 1]未使用[n][e]

[msg Item_160]
[f 2 1]未使用[n][e]

[msg Item_161]
[f 2 1]未使用[n][e]

[msg Item_162]
[f 2 1]未使用[n][e]

[msg Item_163]
[f 2 1]未使用[n][e]

[msg Item_164]
[f 2 1]未使用[n][e]

[msg Item_165]
[f 2 1]未使用[n][e]

[msg Item_166]
[f 2 1]未使用[n][e]

[msg Item_167]
[f 2 1]未使用[n][e]

[msg Item_168]
[f 2 1]未使用[n][e]

[msg Item_169]
[f 2 1]未使用[n][e]

[msg Item_16A]
[f 2 1]未使用[n][e]

[msg Item_16B]
[f 2 1]未使用[n][e]

[msg Item_16C]
[f 2 1]未使用[n][e]

[msg Item_16D]
[f 2 1]未使用[n][e]

[msg Item_16E]
[f 2 1]未使用[n][e]

[msg Item_16F]
[f 2 1]未使用[n][e]

[msg Item_170]
[f 2 1]未使用[n][e]

[msg Item_171]
[f 2 1]未使用[n][e]

[msg Item_172]
[f 2 1]未使用[n][e]

[msg Item_173]
[f 2 1]未使用[n][e]

[msg Item_174]
[f 2 1]未使用[n][e]

[msg Item_175]
[f 2 1]未使用[n][e]

[msg Item_176]
[f 2 1]未使用[n][e]

[msg Item_177]
[f 2 1]未使用[n][e]

[msg Item_178]
[f 2 1]未使用[n][e]

[msg Item_179]
[f 2 1]未使用[n][e]

[msg Item_17A]
[f 2 1]未使用[n][e]

[msg Item_17B]
[f 2 1]未使用[n][e]

[msg Item_17C]
[f 2 1]未使用[n][e]

[msg Item_17D]
[f 2 1]未使用[n][e]

[msg Item_17E]
[f 2 1]未使用[n][e]

[msg Item_17F]
[f 2 1]未使用[n][e]

[msg Item_180]
[f 2 1]未使用[n][e]

[msg Item_181]
[f 2 1]未使用[n][e]

[msg Item_182]
[f 2 1]未使用[n][e]

[msg Item_183]
[f 2 1]未使用[n][e]

[msg Item_184]
[f 2 1]未使用[n][e]

[msg Item_185]
[f 2 1]未使用[n][e]

[msg Item_186]
[f 2 1]未使用[n][e]

[msg Item_187]
[f 2 1]未使用[n][e]

[msg Item_188]
[f 2 1]未使用[n][e]

[msg Item_189]
[f 2 1]未使用[n][e]

[msg Item_18A]
[f 2 1]未使用[n][e]

[msg Item_18B]
[f 2 1]未使用[n][e]

[msg Item_18C]
[f 2 1]未使用[n][e]

[msg Item_18D]
[f 2 1]未使用[n][e]

[msg Item_18E]
[f 2 1]未使用[n][e]

[msg Item_18F]
[f 2 1]未使用[n][e]

[msg Item_190]
[f 2 1]未使用[n][e]

[msg Item_191]
[f 2 1]未使用[n][e]

[msg Item_192]
[f 2 1]未使用[n][e]

[msg Item_193]
[f 2 1]未使用[n][e]

[msg Item_194]
[f 2 1]未使用[n][e]

[msg Item_195]
[f 2 1]未使用[n][e]

[msg Item_196]
[f 2 1]未使用[n][e]

[msg Item_197]
[f 2 1]未使用[n][e]

[msg Item_198]
[f 2 1]未使用[n][e]

[msg Item_199]
[f 2 1]未使用[n][e]

[msg Item_19A]
[f 2 1]未使用[n][e]

[msg Item_19B]
[f 2 1]未使用[n][e]

[msg Item_19C]
[f 2 1]未使用[n][e]

[msg Item_19D]
[f 2 1]未使用[n][e]

[msg Item_19E]
[f 2 1]未使用[n][e]

[msg Item_19F]
[f 2 1]未使用[n][e]

[msg Item_1A0]
[f 2 1]未使用[n][e]

[msg Item_1A1]
[f 2 1]未使用[n][e]

[msg Item_1A2]
[f 2 1]未使用[n][e]

[msg Item_1A3]
[f 2 1]未使用[n][e]

[msg Item_1A4]
[f 2 1]未使用[n][e]

[msg Item_1A5]
[f 2 1]未使用[n][e]

[msg Item_1A6]
[f 2 1]未使用[n][e]

[msg Item_1A7]
[f 2 1]未使用[n][e]

[msg Item_1A8]
[f 2 1]未使用[n][e]

[msg Item_1A9]
[f 2 1]未使用[n][e]

[msg Item_1AA]
[f 2 1]未使用[n][e]

[msg Item_1AB]
[f 2 1]未使用[n][e]

[msg Item_1AC]
[f 2 1]未使用[n][e]

[msg Item_1AD]
[f 2 1]未使用[n][e]

[msg Item_1AE]
[f 2 1]未使用[n][e]

[msg Item_1AF]
[f 2 1]未使用[n][e]

[msg Item_1B0]
[f 2 1]未使用[n][e]

[msg Item_1B1]
[f 2 1]未使用[n][e]

[msg Item_1B2]
[f 2 1]未使用[n][e]

[msg Item_1B3]
[f 2 1]未使用[n][e]

[msg Item_1B4]
[f 2 1]未使用[n][e]

[msg Item_1B5]
[f 2 1]未使用[n][e]

[msg Item_1B6]
[f 2 1]未使用[n][e]

[msg Item_1B7]
[f 2 1]未使用[n][e]

[msg Item_1B8]
[f 2 1]未使用[n][e]

[msg Item_1B9]
[f 2 1]未使用[n][e]

[msg Item_1BA]
[f 2 1]未使用[n][e]

[msg Item_1BB]
[f 2 1]未使用[n][e]

[msg Item_1BC]
[f 2 1]未使用[n][e]

[msg Item_1BD]
[f 2 1]未使用[n][e]

[msg Item_1BE]
[f 2 1]未使用[n][e]

[msg Item_1BF]
[f 2 1]未使用[n][e]

[msg Item_1C0]
[f 2 1]未使用[n][e]

[msg Item_1C1]
[f 2 1]未使用[n][e]

[msg Item_1C2]
[f 2 1]未使用[n][e]

[msg Item_1C3]
[f 2 1]未使用[n][e]

[msg Item_1C4]
[f 2 1]未使用[n][e]

[msg Item_1C5]
[f 2 1]未使用[n][e]

[msg Item_1C6]
[f 2 1]未使用[n][e]

[msg Item_1C7]
[f 2 1]未使用[n][e]

[msg Item_1C8]
[f 2 1]未使用[n][e]

[msg Item_1C9]
[f 2 1]未使用[n][e]

[msg Item_1CA]
[f 2 1]未使用[n][e]

[msg Item_1CB]
[f 2 1]未使用[n][e]

[msg Item_1CC]
[f 2 1]未使用[n][e]

[msg Item_1CD]
[f 2 1]未使用[n][e]

[msg Item_1CE]
[f 2 1]未使用[n][e]

[msg Item_1CF]
[f 2 1]未使用[n][e]

[msg Item_1D0]
[f 2 1]未使用[n][e]

[msg Item_1D1]
[f 2 1]未使用[n][e]

[msg Item_1D2]
[f 2 1]未使用[n][e]

[msg Item_1D3]
[f 2 1]未使用[n][e]

[msg Item_1D4]
[f 2 1]未使用[n][e]

[msg Item_1D5]
[f 2 1]未使用[n][e]

[msg Item_1D6]
[f 2 1]未使用[n][e]

[msg Item_1D7]
[f 2 1]未使用[n][e]

[msg Item_1D8]
[f 2 1]未使用[n][e]

[msg Item_1D9]
[f 2 1]未使用[n][e]

[msg Item_1DA]
[f 2 1]未使用[n][e]

[msg Item_1DB]
[f 2 1]未使用[n][e]

[msg Item_1DC]
[f 2 1]未使用[n][e]

[msg Item_1DD]
[f 2 1]未使用[n][e]

[msg Item_1DE]
[f 2 1]未使用[n][e]

[msg Item_1DF]
[f 2 1]未使用[n][e]

[msg Item_1E0]
[f 2 1]未使用[n][e]

[msg Item_1E1]
[f 2 1]未使用[n][e]

[msg Item_1E2]
[f 2 1]未使用[n][e]

[msg Item_1E3]
[f 2 1]未使用[n][e]

[msg Item_1E4]
[f 2 1]未使用[n][e]

[msg Item_1E5]
[f 2 1]未使用[n][e]

[msg Item_1E6]
[f 2 1]未使用[n][e]

[msg Item_1E7]
[f 2 1]未使用[n][e]

[msg Item_1E8]
[f 2 1]未使用[n][e]

[msg Item_1E9]
[f 2 1]未使用[n][e]

[msg Item_1EA]
[f 2 1]未使用[n][e]

[msg Item_1EB]
[f 2 1]未使用[n][e]

[msg Item_1EC]
[f 2 1]未使用[n][e]

[msg Item_1ED]
[f 2 1]未使用[n][e]

[msg Item_1EE]
[f 2 1]未使用[n][e]

[msg Item_1EF]
[f 2 1]未使用[n][e]

[msg Item_1F0]
[f 2 1]未使用[n][e]

[msg Item_1F1]
[f 2 1]未使用[n][e]

[msg Item_1F2]
[f 2 1]未使用[n][e]

[msg Item_1F3]
[f 2 1]未使用[n][e]

[msg Item_1F4]
[f 2 1]未使用[n][e]

[msg Item_1F5]
[f 2 1]未使用[n][e]

[msg Item_1F6]
[f 2 1]未使用[n][e]

[msg Item_1F7]
[f 2 1]未使用[n][e]

[msg Item_1F8]
[f 2 1]未使用[n][e]

[msg Item_1F9]
[f 2 1]未使用[n][e]

[msg Item_1FA]
[f 2 1]未使用[n][e]

[msg Item_1FB]
[f 2 1]未使用[n][e]

[msg Item_1FC]
[f 2 1]未使用[n][e]

[msg Item_1FD]
[f 2 1]未使用[n][e]

[msg Item_1FE]
[f 2 1]未使用[n][e]

[msg Item_1FF]
[f 2 1]未使用[n][e]

