[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]I played the dating simulator[n]High School of Youth.[n][uf 1 1][e]

[msg MND_003_0_0]
[uf 0 5 65278][uf 2 1]I learned the ins and outs of[n]romance and courtship...![n][uf 1 1][e]

[msg MND_004_0_0]
[uf 0 5 65278][uf 2 1]I feel like I understand a person's heart[n]now after wooing the game's heroines...[n][uf 1 1][e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]I practiced some lines and[n]mannerisms that I can use to[n]make a good impression with girls...![n][uf 1 1][e]

[msg MND_009_0_0]
[uf 0 5 65278][uf 2 1]I played the fighting game Punch Boxer.[n][uf 1 1][e]

[msg MND_011_0_0]
[uf 0 5 65278][uf 2 1]I demonstrated my strength by knocking[n]down endless enemies with my fists...![n][uf 1 1][e]

[msg MND_012_0_0]
[uf 0 5 65278][uf 2 1]I threw a punch at just the right moment,[n]defeating my foe with a single blow...[n][uf 1 1][e]

[msg MND_013_0_0]
[uf 0 5 65278][uf 2 1]Right, right, left, right... Uppercut...[n]I dominated the opponent...![n][uf 1 1][e]

[msg PFM_015_0_0]
[uf 0 5 65278][uf 2 1]The equipped Persona's[n][uf 0 1 2]Strength[uf 0 1 27] was raised by [uf 0 1 2]3[uf 0 1 27].[n][uf 1 1][e]

[msg MND_017_0_0]
[uf 0 5 65278][uf 2 1]I played the horror game[n]House of the Deceased.[n][uf 1 1][e]

[msg MND_019_0_0]
[uf 0 5 65278][uf 2 1]I fearlessly stood my ground against[n]an oncoming horde of zombies...![n][uf 1 1][e]

[msg MND_020_0_0]
[uf 0 5 65278][uf 2 1]The jump scares didn't faze me and I[n]calmly dispatched many zombies...[n][uf 1 1][e]

[msg MND_021_0_0]
[uf 0 5 65278][uf 2 1]I saw many gruesome scenes, but managed[n]to calmly defeat all my enemies...[n][uf 1 1][e]

[msg MND_025_0_0]
[uf 0 5 65278][uf 2 1]I played the racing game Real Wheel Racer.[n][uf 1 1][e]

[msg MND_027_0_0]
[uf 0 5 65278][uf 2 1]I overtook the best racers and felt[n]like I became one with the wind...[n][uf 1 1][e]

[msg MND_028_0_0]
[uf 0 5 65278][uf 2 1]I honed my driving techniques and[n]completed the course as fast as lightning...[n][uf 1 1][e]

[msg MND_029_0_0]
[uf 0 5 65278][uf 2 1]I drifted close to the apex of every turn[n]and set a new record with my lap time...![n][uf 1 1][e]

[msg PFM_031_0_0]
[uf 0 5 65278][uf 2 1]The equipped Persona's[n][uf 0 1 2]Agility[uf 0 1 27] was raised by [uf 0 1 2]3[uf 0 1 27].[n][uf 1 1][e]

[msg MND_033_0_0]
[uf 0 5 65278][uf 2 1]I played the quiz game You're the Answer.[n][uf 1 1][e]

[msg MND_035_0_0]
[uf 0 5 65278][uf 2 1]I increased my intelligence by competing[n]against other players from all over Japan...![n][uf 1 1][e]

[msg MND_036_0_0]
[uf 0 5 65278][uf 2 1]I learned from my wrong answers[n]and gained new knowledge...[n][uf 1 1][e]

[msg MND_037_0_0]
[uf 0 5 65278][uf 2 1]My brain feels sharper after beating[n]other players with my quick answers...![n][uf 1 1][e]

[msg MND_041_0_0]
[uf 0 5 65278][uf 2 1]I played the fortune telling game[n]Edgar's House of Fortunes.[n][uf 1 1][e]

[msg MND_043_0_0]
[uf 0 5 65278][uf 2 1]Dr. Edgar's dubious-sounding fortunes[n]were actually right on point...[n][uf 1 1][e]

[msg MND_044_0_0]
[uf 0 5 65278][uf 2 1]After experiencing a mystical tarot reading,[n]it seems my spiritual power has increased...![n][uf 1 1][e]

[msg MND_045_0_0]
[uf 0 5 65278][uf 2 1]After hearing Dr. Edgar's surprisingly accurate[n]fortune, my sixth sense feels sharper...![n][uf 1 1][e]

[msg PFM_047_0_0]
[uf 0 5 65278][uf 2 1]The equipped Persona's[n][uf 0 1 2]Magic[uf 0 1 27] was raised by [uf 0 1 2]3[uf 0 1 27].[n][uf 1 1][e]

[msg MND_NO_UP]
[uf 0 5 65278][uf 2 1]But it seems I can no longer[n]improve in this regard...[n][uf 1 1][e]

