[msg MND_000_0_0]
[uf 0 5 65278][uf 2 1]Koromaru a l'air satisfait.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Je l'ai brossé aussi soigneusement que possible...[n][uf 1 1][e]

[msg MSG_001_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 201 65535 0 0][uf 3 1 1 0 0 1 0 0]Ouaf ![n][uf 1 1][e]

[msg MND_002_0_0]
[uf 0 5 65278][uf 2 1]Koromaru a rapporté "[uf 4 4 1 37 0 0]".[n]Serait-ce pour me remercier de l'avoir brossé ?[n][uf 1 1][e]

[msg MSG_003_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 1 201 65535 0 0][uf 3 1 1 0 0 2 0 0]Ouaf ! Ouaf ![n][uf 1 1][e]

[msg MND_004_0_0]
[uf 0 5 65278][uf 2 1]J'ai joué un moment avec Koromaru avant de retourner dans ma chambre.[n][uf 1 1][e]

