[msg MND_Temperance]
[f 2 1]El arcano de la Templanza podría ayudarme a mejorar todavía más.[n][w][e]

[msg MSG_000_0_0 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 3 0 65535 7001 0 0]He alquilado un DVD. Es una película extranjera sobre un detective curtido.[n][w][e]
[f 2 1][bup 8 0 65535 65535 0 0]Tengo tiempo libre, así que...[n][w][e]

[msg MSG_500_1113_1 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 3 0 65535 7068 0 0]Ah, [nl].[n][w][e]
[f 2 1][bup 8 0 65535 65535 0 0]Pues... he alquilado un DVD. Es una película extranjera sobre un detective curtido.[n][w][e]
[f 2 1][bup 8 0 65535 65535 0 0]Como no podemos ir a la torre Tártaro, tengo mucho tiempo libre...[n][w][e]

[msg MND_001_0_0]
[f 2 1]Ver una peli de detectives con Amada podría ayudarme a ganar más [f 4 30 2 1 1 0]...[n][w][e]

[msg MSG_002_0_0 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0]Si no tienes nada que hacer, ¿quieres verla conmigo?[n][w][e]

[sel SEL_003_0_0 top]
[f 2 1]Vamos a verlo juntos.[e]
[f 2 1]Es un mal momento.[e]

[msg MSG_004_0_0 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 3 0 65535 7001 0 0]¿Quieres ver otra peli de la saga que empezamos juntos?[n][w][e]
[f 2 1][bup 8 0 65535 65535 0 0]Justo he alquilado otra peli de la misma saga porque me apetece verla en algún momento...[n][w][e]

[msg MND_005_0_0]
[f 2 1]Ver una peli de detectives con Amada podría ayudarme a ganar más [f 4 30 2 1 1 0]...[n][w][e]

[msg MSG_006_0_0 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0]En internet tiene muy buenas críticas, así que seguro que vale la pena verla.[n][w][e]

[sel SEL_007_0_0 top]
[f 2 1]Vamos a verlo juntos.[e]
[f 2 1]Es un mal momento.[e]

[msg MSG_008_0_0 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 3 0 65535 7064 0 0]He alquilado la última peli de la saga.[n][w][e]
[f 2 1][bup 8 1 65535 65535 0 0]Estoy seguro de que va a ser buena.[n][w][e]

[msg MSG_500_1113_3 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 3 0 65535 7063 0 0]La relación de Junpei y Chidori parece sacada de una peli, ¿verdad?[n][w][e]
[f 2 1][bup 8 0 65535 65535 0 0]Hablando de películas, he alquilado la última peli de la saga...[n][w][e]
[f 2 1][bup 8 1 65535 65535 0 0]Estoy seguro de que va a ser buena.[n][w][e]

[msg MND_009_0_0]
[f 2 1]Me da la sensación de que Amada tiene ganas de quedar.[n][w][e]
[f 2 1]Ver una peli de detectives con Amada podría ayudarme a ganar más [f 4 30 2 1 1 0].[n][w][e]
[f 2 1]Amada podría obtener una nueva habilidad pronto.[n][w][e]

[msg MSG_010_0_0 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0]¿Te apetece verla conmigo, [nl]?[n][w][e]

[sel SEL_011_0_0 top]
[f 2 1]Vamos a verlo juntos.[e]
[f 2 1]Es un mal momento.[e]

[msg MSG_012_0_0 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 3 0 65535 7062 0 0]Parece que el director de la peli que vimos tiene un catálogo enorme...[n][w][e]

[msg MSG_500_1113_4 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 3 0 65535 7062 0 0]He descubierto que el director de la peli que vimos tiene muchísimo repertorio.[n][w][e]
[f 2 1][bup 8 0 65535 65535 0 0]He alquilado otras películas que ha dirigido.[n][w][e]
[f 2 1][bup 8 3 65535 65535 0 0]No quiero molestarte, pero esperaba que pudiéramos recomendarle alguna buena a Junpei...[n][w][e]

[msg MND_013_0_0]
[f 2 1]Parece que Amada no va a conseguir nuevas habilidades aunque vea un DVD con él.[n][w][e]
[f 2 1]Pero ver una peli de detectives con Amada podría ayudarme a ganar más [f 4 30 2 1 1 0].[n][w][e]

[msg MSG_014_0_0 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0]Si no estás ocupada, ¿te apetece que veamos la peli juntos?[n][w][e]

[sel SEL_015_0_0 top]
[f 2 1]Vamos a verlo juntos.[e]
[f 2 1]Es un mal momento.[e]

[msg MSG_016_0_0 [Ken Amada]]
[f 2 1][bup 8 1 65535 65535 0 0][vp 3 0 65535 7132 0 0]Venga, yo la pongo.[n][w][e]

[msg MSG_017_0_0 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 3 0 65535 7068 0 0]Vaya, supongo que estás ocupada. La próxima vez será...[n][w][e]

[msg MSG_018_0_0 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 3 0 65535 7068 0 0]¿Te apetece, entonces?[n][w][e]

[msg MND_019_0_0]
[f 2 1]Parece que Amada no va a conseguir nuevas habilidades aunque vea un DVD con él.[n][w][e]
[f 2 1]Pero ver una peli de detectives con Amada podría ayudarme a ganar más [f 4 30 2 1 1 0].[n][w][e]

[msg MND_020_0_0]
[f 2 1]Ver una peli de detectives con Amada podría ayudarme a ganar más [f 4 30 2 1 1 0].[n][w][e]

[msg MSG_020_5_0 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0]Si te parece bien, podríamos ver la peli juntos...[n][w][e]

[sel SEL_021_0_0 top]
[f 2 1]Vamos a verlo juntos.[e]
[f 2 1]Es un mal momento.[e]

[msg MSG_022_0_0 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 3 0 65535 7001 0 0]Sé que no viene a cuento, pero... ¿te apetece que vayamos a por un café?[n][w][e]
[f 2 1][bup 8 0 65535 65535 0 0]No instantáneo, un café de verdad, con sus granos bien molidos y todo eso.[n][w][e]
[f 2 1][bup 8 0 65535 65535 0 0]El otro día vi a alguien preparándolo en un programa y me apetece intentarlo...[n][w][e]

[msg MND_023_0_0]
[f 2 1]Amada me ha invitado a tomar café con él...[n][w][e]
[f 2 1]¿Debería pasar la tarde con él?[n][w][e]

[msg MSG_024_0_0 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0]¿Qué te parece ser mi catadora, [nl]?[n][w][e]

[sel SEL_025_0_0 top]
[f 2 1]Vale.[e]
[f 2 1]Ahora mismo no.[e]

[msg MSG_026_0_0 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 3 0 65535 7062 0 0]Me he informado sobre granos de café.[n][w][e]
[f 2 1][bup 8 0 65535 65535 0 0]Me apetece probar lo que he aprendido. ¿Estás libre ahora?[n][w][e]

[msg MND_027_0_0]
[f 2 1]Amada me ha invitado a tomar café con él...[n][w][e]
[f 2 1]¿Debería pasar la tarde con él?[n][w][e]

[msg MSG_028_0_0 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0]Te prometo que esta vez lo prepararé bien.[n][w][e]

[sel SEL_029_0_0 top]
[f 2 1]Vale.[e]
[f 2 1]Ahora mismo no.[e]

[msg MSG_030_0_0 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 3 0 65535 7002 0 0]Estaba pensando en preparar café.[n][w][e]
[f 2 1][bup 8 0 65535 65535 0 0]Quiero demostrarte que puedo hacerlo...[n][w][e]

[msg MND_031_0_0]
[f 2 1]Amada está serio.[n][w][e]
[f 2 1]Podría obtener una nueva habilidad pronto...[n][w][e]
[f 2 1]¿Debería pasar la tarde con Amada?[n][w][e]

[msg MSG_032_0_0 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0]Mm, ¿tienes tiempo ahora?[n][w][e]

[sel SEL_033_0_0 top]
[f 2 1]Por supuesto.[e]
[f 2 1]No, la verdad.[e]

[msg MSG_034_0_0 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 3 0 65535 7068 0 0]Estaba pensando en preparar café. ¿Te apetece una taza?[n][w][e]

[msg MND_035_0_0]
[f 2 1]Parece que Amada no va a conseguir nuevas habilidades aunque cocinemos juntos...[n][w][e]

[msg MSG_036_0_0 [Ken Amada]]
[f 2 1][bup 8 1 65535 65535 0 0]Je, es como si fuera un barista. Qué díver.[n][w][e]
[f 2 1][bup 8 1 65535 65535 0 0]Puedes hacerlo para llevar, si quieres.[n][w][e]

[sel SEL_037_0_0 top]
[f 2 1]Oh, claro. Gracias.[e]
[f 2 1]Es un mal momento.[e]

[msg MSG_038_0_0 [Ken Amada]]
[f 2 1][bup 8 1 65535 65535 0 0][vp 3 0 65535 7088 0 0]¡Guay! Me pondré a ello.[n][w][e]

[msg MSG_039_0_0 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 3 0 65535 7095 0 0]Ah, vaya... A la próxima, quizá.[n][w][e]

[msg MSG_040_0_0 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 3 0 65535 7068 0 0]¿Te apuntas a lo del café?[n][w][e]

[msg MND_041_0_0]
[f 2 1]Parece que Amada no va a conseguir nuevas habilidades aunque cocinemos juntos...[n][w][e]

[msg MND_042_0_0]
[f 2 1]¿Debería pasar la tarde con Amada?[n][w][e]

[msg MSG_042_5_0 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0]Me encantaría que vinieras conmigo.[n][w][e]

[sel SEL_043_0_0 top]
[f 2 1]Vale.[e]
[f 2 1]Ahora mismo no.[e]

