[msg MSG_000_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 50 0 0][vp 3 0 65535 4107 0 0]Buen trabajo. Has derrotado a un enemigo poderoso.[n][w][e]
[f 2 1][bup 5 0 65535 50 0 0]Confío en tus habilidades como líder. ¿Cómo te ves tú?[n][w][e]

[sel SEL_001_0_0 top]
[f 2 1]Perfecta.[e]
[f 2 1]No sé yo...[e]
[f 2 1]Estoy bien.[e]

[msg MSG_002_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 50 0 0][vp 3 0 65535 4131 0 0]Te veo bastante segura de ti misma. Sigue así.[n][w][e]

[msg MSG_003_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 50 0 0][vp 3 0 65535 4131 0 0]No te preocupes, lo estás haciendo muy bien. Solo necesitas conseguir más experiencia.[n][w][e]

[msg MSG_004_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 50 0 0][vp 3 0 65535 4131 0 0]Veo que tienes potencial. Estoy deseando ver de qué eres capaz.[n][w][e]

[msg MSG_005_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 50 0 0]Muy bien, hora de retomar la exploración. Si necesitas cualquier cosa, dímelo.[n][w][e]

[msg MSG_006_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 50 0 0][vp 3 0 65535 4108 0 0]Buen trabajo. Ahora se puede acceder al camino.[n][w][e]
[f 2 1][bup 5 0 65535 50 0 0]Si quieres, podemos dejarlo por hoy. ¿Qué te parece?[n][w][e]

[sel SEL_007_0_0 top]
[f 2 1]Pues vámonos a casa.[e]
[f 2 1]Sigamos.[e]
[f 2 1]¿Por qué no decides?[e]

[msg MSG_008_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 50 0 0][vp 3 0 65535 4113 0 0]Muy bien. Para volver a la entrada, puedes usar el teletransportador que tienes cerca.[n][w][e]

[msg MSG_009_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 50 0 0][vp 3 0 65535 4113 0 0]Entendido. En ese caso, seguiré ofreciendo mi ayuda.[n][w][e]

[msg MSG_010_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 50 0 0][vp 3 0 65535 4094 0 0]Tú eres la líder, así que tú decides qué hacer en el campo de batalla.[n][w][e]

[msg MSG_011_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 50 0 0]Te lo dejo a ti.[n][w][e]

[msg MSG_012_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 50 0 0][vp 3 0 65535 4107 0 0]Habéis luchado de maravilla.[n][w][e]
[f 2 1][bup 5 0 65535 50 0 0]¿Quieres continuar hoy con la exploración? ¿Cómo te sientes?[n][w][e]

[sel SEL_013_0_0 top]
[f 2 1]Creo que podemos seguir.[e]
[f 2 1]Mmm, dejémoslo por hoy.[e]
[f 2 1]Si tú quieres...[e]

[msg MSG_014_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 50 0 0][vp 3 0 65535 4115 0 0]Muy bien. Continuaremos cuando hayas descansado. Yo te seguiré cubriendo las espaldas.[n][w][e]

[msg MSG_015_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 50 0 0][vp 3 0 65535 4113 0 0]Muy bien, volvamos entonces a la entrada. Forzarse demasiado no es bueno.[n][w][e]

[msg MSG_016_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 50 0 0][vp 3 0 65535 4061 0 0]No quiero obligarte a nada. Tú eres quien debe tomar la decisión en función de la situación actual.[n][w][e]

[msg MSG_017_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 50 0 0][vp 3 0 65535 4086 0 0]¡Excelente victoria![n][w][e]
[f 2 1][bup 5 0 65535 50 0 0]Parece que le has pillado el truco a luchar.[n][w][e]

[sel SEL_018_0_0 top]
[f 2 1]Claro.[e]
[f 2 1]Pues no...[e]
[f 2 1]No pienso bajar la guardia.[e]

[msg MSG_019_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 50 0 0][vp 3 0 65535 4107 0 0]Estoy muy impresionada, la verdad. Creo que hasta podrías arreglártelas sin mi ayuda.[n][w][e]

[msg MSG_020_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 50 0 0][vp 3 0 65535 4131 0 0]Je, je. ¿Intentas ser humilde? Nunca dejarás de sorprenderme.[n][w][e]

[msg MSG_021_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 50 0 0][vp 3 0 65535 4065 0 0]Me alegra oír eso. No sabemos qué nos aguarda en este sitio.[n][w][e]

[msg MSG_022_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 50 0 0]Cuando os veo a todos en plena acción, me entran ganas de unirme a mí también...[n][w][e]
[f 2 1][bup 5 0 65535 50 0 0]No me hagáis caso. Continuad con la exploración.[n][w][e]

[msg MSG_023_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 4 65535 50 0 0][vp 3 0 65535 4030 0 0]¡Es increíble que hayas logrado la victoria tú sola! Te felicito.[n][w][e]
[f 2 1][bup 5 1 65535 50 0 0]No sé qué pretendías luchando sola, pero ha sido un espectáculo digno de ver.[n][w][e]
[f 2 1][bup 5 0 65535 50 0 0]Aunque prefiero que lleves a alguien contigo.[n][w][e]

[sel SEL_024_0_0 top]
[f 2 1]Quizá sea una buena idea.[e]
[f 2 1]No es necesario.[e]
[f 2 1]Me lo pensaré.[e]

[msg MSG_025_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 50 0 0][vp 3 0 65535 4024 0 0]No tienes por qué arriesgarte a ir sola.[n][w][e]
[f 2 1][bup 5 0 65535 50 0 0]Los demás están preparados. Si quieres formar un grupo, vuelve a la entrada.[n][w][e]

[msg MSG_026_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 6 65535 50 0 0][vp 3 0 65535 4061 0 0]Entiendo. Tú eres la líder sobre el campo de batalla, así que no cuestionaré tus estrategias.[n][w][e]
[f 2 1][bup 5 0 65535 50 0 0]Aunque confío en tu capacidad, no deberías bajar nunca la guardia.[n][w][e]

[msg MSG_027_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 50 0 0][vp 3 0 65535 4036 0 0]La decisión es tuya, pero ten en cuenta que es importante que los demás también ganen experiencia.[n][w][e]
[f 2 1][bup 5 0 65535 50 0 0]Si quieres que alguien te acompañe, tienes que volver a la entrada y formar un grupo.[n][w][e]

[msg MSG_028_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 50 0 0]Vale, confío en ti.[n][w][e]

[msg MSG_029_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 50 0 0][vp 3 0 65535 5011 0 0]El enemigo ha sido derrotado. ¡Buen trabajo, equipo![n][w][e]
[f 2 1][bup 6 0 65535 50 0 0]¡Has sabido dar muy bien las órdenes, líder![n][w][e]

[sel SEL_030_0_0 top]
[f 2 1]Sí, ha ido bien.[e]
[f 2 1]Yo no lo tengo tan claro...[e]
[f 2 1]Y todo gracias a ti, Fuuka.[e]

[msg MSG_031_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 50 0 0][vp 3 0 65535 5145 0 0]Ya sabía que no tenía nada de qué preocuparme, pero has hecho un gran trabajo, [nl].[n][w][e]

[msg MSG_032_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 50 0 0][vp 3 0 65535 5122 0 0]¿De verdad? Ah, pues creo que lo has hecho muy bien.[n][w][e]

[msg MSG_033_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 4 65535 50 1 0][vp 3 0 65535 5122 0 0]¿C-cómo? Pero si yo no... Bueno, me alegro de haberte sido de ayuda.[n][w][e]

[msg MSG_034_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 50 0 0]Por cierto, ahí delante hay unas escaleras. ¡Hay que seguir así![n][w][e]

[msg MSG_035_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 50 0 0][vp 3 0 65535 5113 0 0]Buen trabajo, equipo.[n][w][e]
[f 2 1][bup 6 0 65535 50 0 0]Este puede ser un buen lugar para hacer un alto. ¿Quieres dejarlo por hoy?[n][w][e]

[sel SEL_036_0_0 top]
[f 2 1]Sí, vale.[e]
[f 2 1]¡No, esto es solo el comienzo![e]
[f 2 1]Estás siendo demasiado prudente.[e]

[msg MSG_037_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 50 0 0][vp 3 0 65535 5145 0 0]Genial, te veo en la entrada.[n][w][e]

[msg MSG_038_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 50 0 0][vp 3 0 65535 5061 0 0]Ah, vale. En ese caso, seguiré prestándote mi ayuda.[n][w][e]

[msg MSG_039_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 50 0 0][vp 3 0 65535 5065 0 0]Bueno, uno nunca sabe qué puede pasar, así que será mejor ir con cuidado...[n][w][e]
[f 2 1][bup 6 0 65535 50 0 0]Aunque eso ya es decisión tuya, líder. No te fuerces más de la cuenta, ¿vale?[n][w][e]

[msg MSG_040_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 50 0 0][vp 3 0 65535 5087 0 0]¡Enemigo derrotado! Gracias por vuestros esfuerzos, chicos.[n][w][e]
[f 2 1][bup 6 0 65535 50 0 0]Si te apetece, ¿por qué no sigues explorando un poco más?[n][w][e]

[sel SEL_041_0_0 top]
[f 2 1]Ese es el plan.[e]
[f 2 1]Quiero volver.[e]
[f 2 1]Como sea.[e]

[msg MSG_042_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 50 0 0][vp 3 0 65535 5145 0 0]¡Muy bien! ¡Las escaleras están justo ahí delante![n][w][e]

[msg MSG_043_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 50 0 0][vp 3 0 65535 5145 0 0]Vale. Ten cuidado al bajar.[n][w][e]

[msg MSG_044_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 50 0 0][vp 3 0 65535 5062 0 0]Es una decisión difícil. Retirarse también es otra opción perfectamente plausible.[n][w][e]
[f 2 1][bup 6 1 65535 50 0 0]Haremos lo que tú nos digas, [nl].[n][w][e]

[msg MSG_045_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 50 0 0][vp 3 0 65535 5086 0 0]¡Enemigo derrotado! ¿Cómo estáis todos?[n][w][e]

[msg MSG_046_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 50 0 0]Oye, perdonad que os suelte esto así, de sopetón, pero...[n][w][e]
[f 2 1][bup 6 0 65535 50 0 0]Os admiro un montón por estar luchando en primera línea a pesar del peligro.[n][w][e]

[sel SEL_047_0_0 top]
[f 2 1]Estamos acostumbrados.[e]
[f 2 1]Está mal.[e]
[f 2 1]¿Quieres probarlos?[e]

[msg MSG_048_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 4 65535 50 0 0][vp 3 0 65535 5099 0 0]Ah, ¿así que es eso? Bueno, aun así, creo que es increíble.[n][w][e]
[f 2 1][bup 6 1 65535 50 0 0]Ahora que lo pienso, creo que hasta yo estoy más calmada que al principio.[n][w][e]

[msg MSG_049_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 50 0 0][vp 3 0 65535 5060 0 0]Sí... Un paso en falso y podría ocurrir una desgracia.[n][w][e]
[f 2 1][bup 6 0 65535 50 0 0]Pero yo estaré vigilando desde aquí para que nada de eso pase.[n][w][e]

[msg MSG_050_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 50 0 0][vp 3 0 65535 5062 0 0]A veces, desearía poder... Pero no creo que sea muy realista por mi parte.[n][w][e]
[f 2 1][bup 6 0 65535 50 0 0]En vez de eso, os ayudaré en todo lo que pueda para que estéis seguros durante el recorrido.[n][w][e]

[msg MSG_051_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 4 65535 50 0 0]En fin..., solo quería deciros que os estoy muy agradecida a todos.[n][w][e]
[f 2 1][bup 6 1 65535 50 0 0]¡Hay que seguir así![n][w][e]

[msg MSG_052_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 4 65535 50 0 0][vp 3 0 65535 5088 0 0]Vaya... ¡No me creo que hayas ganado a todos tú solita![n][w][e]
[f 2 1][bup 6 1 65535 50 0 0]Los demás también están alucinando. ¿Vas a continuar sola?[n][w][e]

[sel SEL_053_0_0 top]
[f 2 1]Llegaré hasta donde pueda.[e]
[f 2 1]Estoy agotadísima...[e]
[f 2 1]Déjame que me lo piense.[e]

[msg MSG_054_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 50 0 0][vp 3 0 65535 5116 0 0]Vale. La verdad es que me preocupa un poco que vayas por ahí sin compañía...[n][w][e]
[f 2 1][bup 6 1 65535 50 0 0]Pero también tengo ganas de ver de qué más cosas eres capaz. Ten mucho cuidado.[n][w][e]

[msg MSG_055_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 4 65535 50 0 0][vp 3 0 65535 5099 0 0]Ah, en ese caso, vuelve ahora mismo. Estarás más segura si vas con todo el grupo.[n][w][e]

[msg MSG_056_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 50 0 0][vp 3 0 65535 5062 0 0]Vale, seguro que te irá bien, pero no te fuerces demasiado.[n][w][e]

[msg MSG_057_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 50 0 0]Todos aquí te están apoyando y están listos por si los necesitas.[n][w][e]
[f 2 1][bup 6 1 65535 50 0 0]¡Buena suerte![n][w][e]

