[msg MSG_SENDER_NAME]
[f 2 1]Kenji Tomochika[n][w][e]

[msg MSG_001_0_0]
[f 2 1]¿Hoy estás libre?[n][w][e]

[msg MSG_002_0_0]
[f 2 1]¡Por fin se acabaron las clases! ¿Quieres hacer algo al salir? Voy a quedarme un rato por aquí, así que pásate por mi mesa si te apetece. [f 1 3 137][n][w][e]

[msg MSG_003_0_0]
[f 2 1]Me abuuurrooo[n][w][e]

[msg MSG_004_0_0]
[f 2 1]¿Luego tienes algo que hacer? Podemos quedar si estás libre. Estaré en mi sitio de siempre. [f 1 3 137][n][w][e]

[msg MSG_005_0_0]
[f 2 1]¡¡¡AYUDA!!![n][w][e]

[msg MSG_006_0_0]
[f 2 1]perdona, tía, pero solo puedo confiar en ti... no hagas preguntas, tú ven y ya. ¡¿entendido?![n][w][e]

[msg MSG_007_0_0]
[f 2 1]¡Buenaaas![n][w][e]

[msg MSG_008_0_0]
[f 2 1]¿Quedamos después de clase? [f 1 3 135][f 1 3 135][n]¡Quiero comentarte una cosa![n][w][e]

[msg MSG_009_0_0]
[f 2 1]Vamos a pillar...[n][w][e]

[msg MSG_010_0_0]
[f 2 1]¡Ramen! ¡Ramen! ¡Ramen! ¡Ramen![n]¡Ramen! ¡Ramen! ¡Ramen! ¡Ramen![n]¡Seguro que ahora te apetece comer ramen! ¿Qué me dices? [f 1 3 137][n][w][e]

[msg MSG_011_0_0]
[f 2 1]¿Tienes algo que hacer hoy?[n][w][e]

[msg MSG_012_0_0]
[f 2 1]Justo cuando por fin me decido a trabajar duro para labrarme un futuro mejor, tiene que venir algo a fastidiarme [f 1 3 138][n]¿Puedo contártelo?[n][w][e]

[msg MSG_013_0_0]
[f 2 1]¿Qué hago?[n][w][e]

[msg MSG_014_0_0]
[f 2 1]Perdona, sé que es un poco repentino, pero estoy en un buen aprieto [f 1 3 138][f 1 3 138][f 1 3 138][n]No tengo a nadie más... ¿Podemos hablar?[n][w][e]

[msg MSG_015_0_0]
[f 2 1]Se acabó[n][w][e]

[msg MSG_016_0_0]
[f 2 1]He tomado una decisión. Quiero explicártelo todo, de principio a fin. ¿Podemos quedar?[n][w][e]

[msg MSG_017_0_0]
[f 2 1]Hola, monada~ [f 1 3 132][n][w][e]

[msg MSG_018_0_0]
[f 2 1]¿Hoy estás libre, [nl]?[n]Tengamos una cita [f 1 3 132][n]Quiero comer ramen contigo~[n][w][e]

[msg MSG_019_0_0]
[f 2 1]¿Cómo va eso?[n][w][e]

[msg MSG_020_0_0]
[f 2 1]Hagamos algo después de clase si estás libre [f 1 3 137][n][w][e]

[msg MSG_021_0_0]
[f 2 1]¡ey![n][w][e]

[msg MSG_022_0_0]
[f 2 1]¿Estás libre? Avísame si quieres quedar. Estaré en clase.[n][w][e]

[msg MSG_023_0_0]
[f 2 1]oye[n][w][e]

[msg MSG_024_0_0]
[f 2 1]Estás libre, ¿verdad? Vamos a quedar [f 1 3 136][n][w][e]

[msg MSG_025_0_0]
[f 2 1]andas libre?[n][w][e]

[msg MSG_026_0_0]
[f 2 1]Como hoy no hay clase, avísame si quieres ir a algún lado. No tengo nada que hacer hasta la tarde [f 1 3 137][n][w][e]

[msg MSG_027_0_0]
[f 2 1]¡Vamos a ver una peli![n][w][e]

[msg MSG_028_0_0]
[f 2 1]Echan una a la que le tengo muchas ganas [f 1 3 151][n]¡Encenderá un fuego dentro de ti, tía![n]Ya tengo las entradas. ¡Dime si quieres venir antes de mediodía![n][w][e]

[msg MSG_029_0_0]
[f 2 1]¡Esta floristería vende cosas raras![n][w][e]

[msg MSG_030_0_0]
[f 2 1]¿Conoces la floristería de la estación de la isla Puerto? La chica que trabaja allí es mona, pero las flores son carísimas [f 1 3 155] ¡Lo único que puedo permitirme son un par de semillas! En fin, solo quería quejarme [f 1 3 138][n][w][e]

