[msg MSG_000_0_0 [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0][vp 1 0 0 1 0 0]¡¿Qué cojones?! Pone: "Prohibido jugar a la pelota en el parque".[n][w][e]

[msg MSG_001_0_0 [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0][vp 1 0 0 2 0 0]Qué raro, ¿no crees?[n][w][e]
[f 2 1][bup 3 3 65535 65535 0 0][vp 1 0 0 3 0 0]Los críos hacen amigos jugando a la pelota. ¡Los adultos no pueden prohibirlo así como así![n][w][e]

[sel SEL_002_0_0 top]
[f 2 1]Depende de dónde.[e]
[f 2 1]Exacto, ¡no pueden hacer eso![e]

[msg MSG_003_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 65535 65535 0 0][vp 1 0 0 4 0 0]Y aquí habla la voz de la razón.[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0][vp 1 0 0 5 0 0][f 4 23 0 1 0 25 25]Solo digo que, si esta costumbre se extiende, los críos que quieran jugar al béisbol van a tener un problemón.[n][w][e]

[msg MSG_004_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 1 0 0 6 0 0]¿Verdad? ¡Esto no me gusta ni un pelo![n][w][e]

[msg MSG_005_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 1 0 0 7 0 0]En cualquier caso, no sabía que lo habían prohibido aquí.[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0][vp 1 0 0 8 0 0]Cuando me mudé a este lugar, jugaba contra la pared de vez en cuando.[n][w][e]

[msg MSG_006_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 1 0 0 9 0 0]Todo esto de jugar a la pelota... viene porque quería poner a tono los brazos.[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0][vp 1 0 0 10 0 0]He estado pensando en que igual debería volver al béisbol.[n][w][e]

[msg MSG_007_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 1 0 0 11 0 0]Aún no tengo ni idea de qué hacer con mi vida.[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0][vp 1 0 0 12 0 0]Y si sigo evitando el tema, lo único que conseguiré es arrepentirme.[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0][vp 1 0 0 13 0 0]La próxima vez que me pregunten qué haré en dos años, tendré una respuesta.[n][w][e]

[msg MSG_008_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 1 0 0 14 0 0]Por eso pienso retomar el béisbol. Eh... ¿Crees que hago bien?[n][w][e]

[sel SEL_009_0_0 top]
[f 2 1]A mí me parece bien.[e]
[f 2 1]¿En serio te parece bien?[e]
[f 2 1]Típico de ti.[e]

[msg MSG_010_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 1 0 0 15 0 0]¿Ah, sí? Uf, la verdad es que ahora me siento mucho mejor.[n][w][e]

[msg MSG_011_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 1 0 0 16 0 0]Bueno..., tampoco se me ocurre otra cosa.[n][w][e]

[msg MSG_012_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 1 0 0 17 0 0]Je, ¿se supone que es un cumplido?[n][w][e]

[msg MSG_013_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 1 0 0 18 0 0]Toma, esto es para ti.[n][w][e]

[msg MSG_014_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 1 0 0 19 0 0]Hoy la cosa no ha ido bien, pero lo seguiremos intentando. Aguanta hasta entonces.[n][w][e]

[msg MSG_015_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 1 0 0 20 0 0]Aunque tendremos que esperar hasta que pase eso que tú ya sabes, ¿eh?[n][w][e]

[msg MSG_016_0_0 [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0][vp 1 0 0 21 0 0]Ay, no sé... La verdad es que me siento así desde abril.[n][w][e]
[f 2 1][bup 3 3 65535 65535 0 0][vp 1 0 0 22 0 0]Ya me cuesta manejar lo que tengo ahora entre manos, imagínate pensar en el futuro...[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0][vp 1 0 0 23 0 0][f 4 23 0 1 0 25 25]Aunque los de tercero sí que son la caña. Están preparándose para los exámenes a pesar de todo.[n][w][e]

[msg MSG_017_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 1 0 0 24 0 0]Madre mía, menudo añito.[n][w][e]

[msg MSG_018_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 1 0 0 25 0 0]Algún día, echaremos la vista atrás y nos preguntaremos cómo pudimos superar todo esto.[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0][vp 1 0 0 26 0 0]La cosa no ha ido bien y hemos tenido un par de rachas malas...[n][w][e]

[msg MSG_019_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 1 0 0 27 0 0]Supongo que nuestra vida ha sido corta pero intensa por ahora, ¿eh?[n][w][e]

[sel SEL_020_0_0 top]
[f 2 1]Tú lo has dicho.[e]
[f 2 1]No me lo parece.[e]

[msg MSG_021_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 1 0 0 28 0 0]Ja, ja, ¿verdad?[n][w][e]

[msg MSG_022_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 1 0 0 29 0 0]Solo tenías que asentir y coincidir conmigo. En fin, tampoco esperaba menos de ti.[n][w][e]

[msg MSG_023_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 1 0 0 30 0 0]A pesar de todo lo que ha pasado, me alegra que seas nuestra líder, [nf].[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0][vp 1 0 0 31 0 0]Te dije que podías hacer lo que quisieses, pero gracias por quedarte a luchar.[n][w][e]

[msg MSG_024_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 1 0 0 32 0 0]Bueno...[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0][vp 1 0 0 33 0 0]Acabemos este capítulo de nuestras vidas de la mejor manera posible, ¿vale?[n][w][e]

[msg MSG_025_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 1 0 0 34 0 0]¡Y luego Hollywood hará una película de nuestras biografías![n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0][vp 1 0 0 35 0 0]Yo seré el prota, obvio. ¡Y a ti el papel de coprotagonista te viene al pelo![n][w][e]

[msg MSG_026_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 1 0 0 36 0 0]Je, je, je.[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0][vp 1 0 0 37 0 0]A nosotros no nos va nada ese rollo serio, ¿eh?[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0][vp 1 0 0 38 0 0]Venga, volvamos a casa y pensemos cómo arrasar en los Óscar de camino.[n][w][e]

[msg MND_027_0_0]
[f 2 1]Junpei y yo hemos hecho el tonto[n]de camino a casa.[n][w][e]

[msg SYS_028_0_0]
[f 2 1]Has forjado un poderoso vínculo con Junpei.[n]¡Ahora puedes fusionar a [clr 35]Surt[clr 27], señor del fuego![n][w][e]

