[msg MSG_000_0_0 [Keisuke Hiraga]]
[f 2 1][bup 108 1 65535 65535 0 0][vp 3 0 65535 11268 0 0]¡Oh, mira cuántos tickets![n][w][e]
[f 2 1][bup 108 1 65535 65535 0 0]No me imaginaba que ganaríamos tantos... ¡Qué divertido![n][w][e]

[msg MSG_001_0_0 [Keisuke Hiraga]]
[f 2 1][bup 108 0 65535 65535 0 0]Aunque quizá fue más bien suerte. Ahora que lo pienso, siempre me ha sonreído...[n][w][e]
[f 2 1][bup 108 0 65535 65535 0 0]Como en el concurso. En realidad, no quería ganar nada y no pensé que lo haría.[n][w][e]

[msg MSG_002_0_0 [Keisuke Hiraga]]
[f 2 1][bup 108 3 65535 65535 0 0][vp 3 0 65535 11250 0 0]¿C-crees que me merezco estar en la final?[n][w][e]

[sel SEL_003_0_0 top]
[f 2 1]Sí, te has esforzado mucho.[e]
[f 2 1]Cree en ti mismo.[e]
[f 2 1]Es que los demás eran malísimos.[e]

[msg MSG_004_0_0 [Keisuke Hiraga]]
[f 2 1][bup 108 0 65535 65535 0 0][vp 3 0 65535 11255 0 0][f 5 13 11 30 108]Bueno, si lo dices así, supongo que no pasa nada.[n][w][e]
[f 2 1][bup 108 0 65535 65535 0 0]Eres muy madura para todo... Y se supone que el mayor soy yo.[n][w][e]

[msg MND_005_0_0]
[f 2 1]Hiraga me mira con respeto.[n][w][e]
[f 2 1]Siento que hoy nuestra relación se ha estrechado.[n][w][e]

[msg MSG_006_0_0 [Keisuke Hiraga]]
[f 2 1][bup 108 0 65535 65535 0 0][vp 3 0 65535 11221 0 0][f 5 13 11 15 108]Sí, eso es lo que me dice todo el mundo.[n][w][e]
[f 2 1][bup 108 0 65535 65535 0 0]Creo que me pongo un poquito nervioso porque nunca he entrenado en condiciones...[n][w][e]

[msg MND_007_0_0]
[f 2 1]Hiraga parece un poco avergonzado.[n][w][e]
[f 2 1]Hoy he aprendido un poco más sobre él.[n][w][e]

[msg MSG_008_0_0 [Keisuke Hiraga]]
[f 2 1][bup 108 4 65535 65535 0 0][vp 3 0 65535 11226 0 0]¡E-eso no es verdad! ¡Había gente muy buena de otros institutos![n][w][e]
[f 2 1][bup 108 3 65535 65535 0 0][f 4 23 0 108 3 25 25]Me da igual lo que opines de mí, pero hablar así de los demás está muy feo...[n][w][e]

[msg MND_009_0_0]
[f 2 1]Parece que Hiraga no quiere seguir hablando del tema.[n][w][e]
[f 2 1]Siento que hoy nuestra relación no ha cambiado nada...[n][w][e]

[msg MSG_010_0_0 [Keisuke Hiraga]]
[f 2 1][bup 108 0 65535 65535 0 0]Sienta bien cambiar de aires, que últimamente el club me ha tenido muy ocupado.[n][w][e]
[f 2 1][bup 108 0 65535 65535 0 0][vp 3 0 65535 11293 0 0]No tardaremos en volver. Debería ponerme manos a la obra lo antes posible.[n][w][e]

[msg MND_011_0_0]
[f 2 1]Los dos pasamos un rato más juntos antes de volver a la residencia.[n][w][e]

