[msg MSG_000_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 0 65535 65535 0 0][vp 1 0 0 1 0 0]Hola, tía. Gracias por venir. Espera un momento, anda.[n][w][e]

[sel SEL_001_0_0 top]
[f 2 1]Claro.[e]
[f 2 1]¿Por qué?[e]

[msg MSG_002_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 1 65535 65535 0 0][vp 1 0 0 2 0 0]Escúchame, pero no te alteres.[n][w][e]
[f 2 1][bup 101 1 65535 65535 0 0][vp 1 0 0 3 0 0]¡Voy a pedirle salir a la profesora Kanou ahora mismo![n][w][e]

[sel SEL_003_0_0 top]
[f 2 1]¡Buena suerte![e]
[f 2 1]Ni se te ocurra.[e]
[f 2 1]Pues vale.[e]

[msg MSG_004_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 1 65535 65535 0 0][vp 1 0 0 4 0 0][f 5 13 2 15 101]¡Muchas gracias! ¡Por fin voy a echarme novia![n][w][e]

[msg MSG_005_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 6 65535 65535 0 0][vp 1 0 0 5 0 0]N-no me asustes de esa manera. Me vendrían bien unas palabras de ánimo.[n][w][e]

[msg MSG_006_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 3 65535 65535 0 0][vp 1 0 0 6 0 0]No seas tan fría conmigo. Siempre cabe la posibilidad de que me rechace, ¿no?[n][w][e]
[f 2 1][bup 101 3 65535 65535 0 0][vp 1 0 0 7 0 0]Y, si me dice que no, no estaré como para volver solo a casa. Tú espera y verás.[n][w][e]

[msg MSG_007_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 0 65535 65535 0 0][vp 1 0 0 8 0 0]Muy bien, aquí es... ¡Allá voy![n][w][e]

[msg MSG_008_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 1 65535 65535 0 0][vp 1 0 0 9 0 0]Madre mía, ¡vas a flipar![n][w][e]
[f 2 1][bup 101 1 65535 65535 0 0][vp 1 0 0 10 0 0]¡Me ha dicho que sí! ¡Flipa, qué locurón![n][w][e]
[f 2 1][bup 101 1 65535 65535 0 0][vp 1 0 0 11 0 0]Justo cuando iba a pedirle salir, me ha preguntado si me interesaría que me diera clases particulares.[n][w][e]

[msg MSG_009_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 1 65535 65535 0 0][vp 1 0 0 12 0 0]¡Te debo una, mujer! ¡Muchas gracias por escucharme![n][w][e]

[msg MND_010_0_0]
[f 2 1]Parece que el plan secreto de Kenji ha salido bien.[n][w][e]
[f 2 1]Tengo la sensación de que nuestra relación se ha fortalecido.[n][w][e]

[msg MSG_011_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 1 65535 65535 0 0][vp 1 0 0 13 0 0]Voy a ir a su casa ahora. ¡Qué fuerte, no estoy preparado![n][w][e]
[f 2 1][bup 101 1 65535 65535 0 0][vp 1 0 0 14 0 0]Mejor no me espero nada especial el primer día, ¿verdad? Aunque ella ya es adulta, así que...[n][w][e]

[msg MSG_012_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 0 65535 65535 0 0][vp 1 0 0 15 0 0]Uy, se me había olvidado que estabas aquí. ¡Me voy pitando![n][w][e]

[msg MND_013_0_0]
[f 2 1]...[n][w][e]
[f 2 1]Se estaba haciendo tarde, así que he vuelto a casa.[n][w][e]

