[msg MSG_000_0_0 [Koromaru]]
[f 2 1][bup 9 2 52 65535 0 0][vp 1 0 0 1 0 0]¡Guau, guau![n][w][e]

[msg MSG_001_0_0 [Yukari Takeba]]
[f 2 1][bup 2 4 52 65535 0 0][vp 1 0 0 2 0 0]¡¿Aigis?![n][w][e]

[msg MSG_002_0_0 [Aigis]]
[f 2 1][bup 7 30 203 65535 0 0][vp 1 0 0 3 0 0]Lo siento mucho...[n][w][e]
[f 2 1][bup 7 30 203 65535 0 0][vp 1 0 0 4 0 0]Lo... recuerdo todo...[n][w][e]
[f 2 1][bup 7 30 203 65535 0 0][vp 1 0 0 5 0 0]Recuerdo quién soy... y quién es él...[n][w][e]

[msg MSG_003_0_0 [Aigis]]
[f 2 1][bup 7 30 203 65535 0 0][vp 1 0 0 6 0 0][nf]...[n][w][e]
[f 2 1][bup 7 30 203 65535 0 0][vp 1 0 0 7 0 0]Ya sé por qué quería estar siempre a tu lado.[n][w][e]
[f 2 1][bup 7 30 203 65535 0 0][vp 1 0 0 8 0 0]Siento haberte fallado...[n][w][e]

[sel SEL_004_0_0 top]
[f 2 1]¿Qué pasa?[e]
[f 2 1]Todo saldrá bien.[e]
[f 2 1]No malgastes tu energía.[e]

[msg MSG_005_0_0 [Aigis]]
[f 2 1][bup 7 30 203 65535 0 0][vp 1 0 0 9 0 0]Lo siento de veras...[n][w][e]

[msg MSG_006_0_0 [Voz familiar]]
[f 2 1][vp 1 0 0 10 0 0]No tienes por qué pedir perdón.[n][w][e]

[msg MSG_007_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 52 65535 0 0][vp 1 0 0 11 0 0]¡¿Tú?![n][w][e]

[msg MSG_008_0_0 [Ryoji Mochizuki]]
[f 2 1][bup 221 0 65535 65535 0 0][vp 0 0 0 12 0 0]...[n][w][e]

[msg MSG_009_0_0 [Yukari Takeba]]
[f 2 1][bup 2 4 52 65535 0 0][vp 1 0 0 13 0 0]¡¿Ryoji?![n][w][e]
[f 2 1][bup 2 4 52 65535 0 0][vp 1 0 0 14 0 0]Espera, ¡¿qué haces tú aquí?![n][w][e]

[msg MSG_010_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 4 52 65535 0 0][vp 1 0 0 15 0 0]¡¿Aigis?![n][w][e]

[msg MND_011_0_0]
[f 2 1]Aigis se ha quedado inmóvil.[n][w][e]
[f 2 1]Parece que ha dejado de funcionar.[n][w][e]

[msg MSG_012_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 2 52 65535 0 0][vp 1 0 0 16 0 0]¿Qué está pasando...?[n][w][e]

[msg MSG_013_0_0 [Ryoji Mochizuki]]
[f 2 1][bup 221 3 65535 65535 0 0][vp 1 0 0 17 0 0]Es todo por mi culpa...[n][w][e]

[msg MSG_014_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 2 52 65535 0 0][vp 1 0 0 18 0 0]¿Qué...? ¡¿Esto es cosa tuya?![n][w][e]

[msg MSG_015_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 52 65535 0 0][vp 1 0 0 19 0 0]Akihiko, espera. No muestra ningún signo de hostilidad.[n][w][e]

[msg MSG_016_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 52 65535 0 0][vp 1 0 0 20 0 0]Ahora dinos...[n][w][e]
[f 2 1][bup 5 0 52 65535 0 0][vp 1 0 0 21 0 0]¿Quién eres? ¿O qué eres?[n][w][e]

[msg MSG_017_0_0 [Ryoji Mochizuki]]
[f 2 1][bup 221 3 65535 65535 0 0][vp 1 0 0 22 0 0]Parece que no soy muy diferente a las criaturas a las que llamáis sombras.[n][w][e]

[msg MSG_018_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 52 65535 0 0][vp 1 0 0 23 0 0]¡¿Eres una sombra?![n][w][e]

[msg MSG_019_0_0 [Ryoji Mochizuki]]
[f 2 1][bup 221 0 65535 65535 0 0][vp 1 0 0 24 0 0]Soy más que eso.[n][w][e]
[f 2 1][bup 221 0 65535 65535 0 0][vp 1 0 0 25 0 0]Soy el Tasador, nacido de la unión de los doce arcanos.[n][w][e]

[msg MSG_020_0_0 [Yukari Takeba]]
[f 2 1][bup 2 3 52 65535 0 0][vp 1 0 0 26 0 0]¡¿El Tasador?![n][w][e]

[msg MSG_021_0_0 [Ryoji Mochizuki]]
[f 2 1][bup 221 0 65535 65535 0 0][vp 1 0 0 27 0 0]Ahora lo recuerdo todo.[n][w][e]
[f 2 1][bup 221 3 65535 65535 0 0][vp 1 0 0 28 0 0][f 4 23 0 221 3 25 25]La horrible verdad sobre las sombras y sobre mí mismo.[n][w][e]
[f 2 1][bup 221 10 65535 65535 0 0][vp 1 0 0 29 0 0][f 4 23 0 221 10 25 25]Cuesta tanto creerlo...[n][w][e]

[msg MSG_022_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 52 65535 0 0][vp 1 0 0 30 0 0]¿Sabes la "verdad" sobre las sombras?[n][w][e]

[msg MSG_023_0_0 [Ryoji Mochizuki]]
[f 2 1][bup 221 3 65535 65535 0 0][vp 1 0 0 31 0 0]Sí.[n][w][e]

[msg MSG_024_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 4 52 65535 0 0][vp 1 0 0 32 0 0]¡¿Qué?![n][w][e]

[msg MSG_025_0_0 [Ryoji Mochizuki]]
[f 2 1][bup 221 3 65535 65535 0 0][vp 1 0 0 33 0 0]La función de las sombras consiste en contribuir al renacimiento del ser materno.[n][w][e]
[f 2 1][bup 221 3 65535 65535 0 0][vp 1 0 0 34 0 0]En cuanto al Tasador...[n][w][e]
[f 2 1][bup 221 3 65535 65535 0 0][vp 1 0 0 35 0 0]Él es el que se encarga de atraer al ser materno para que despierte.[n][w][e]

[msg MSG_026_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 4 52 65535 0 0][vp 1 0 0 36 0 0]¿Y ese Tasador eres tú?[n][w][e]

[msg MSG_027_0_0 [Ryoji Mochizuki]]
[f 2 1][bup 221 3 65535 65535 0 0][vp 1 0 0 37 0 0]Eso es.[n][w][e]

[msg MSG_028_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 52 65535 0 0][vp 1 0 0 38 0 0]¿Qué es eso del "ser materno"?[n][w][e]

[msg MSG_029_0_0 [Ryoji Mochizuki]]
[f 2 1][bup 221 3 65535 65535 0 0][vp 1 0 0 39 0 0]Está a otro nivel. Nuestro idioma ni siquiera tiene palabras para describirla.[n][w][e]

[msg MSG_030_0_0 [Ryoji Mochizuki]]
[f 2 1][bup 221 3 65535 65535 0 0][vp 1 0 0 40 0 0]Hace diez años, un hombre reunió hordas de sombras y las encerró en un laboratorio.[n][w][e]
[f 2 1][bup 221 3 65535 65535 0 0][vp 1 0 0 41 0 0]Así nací yo.[n][w][e]
[f 2 1][bup 221 3 65535 65535 0 0][vp 1 0 0 42 0 0]Pero algo interrumpió la unión y me desperté antes de completarme.[n][w][e]
[f 2 1][bup 221 3 65535 65535 0 0][vp 1 0 0 43 0 0]Después, Aigis acabó conmigo y yo le devolví el favor.[n][w][e]

[msg MSG_031_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 52 65535 0 0][vp 1 0 0 44 0 0]¡¿Aigis?![n][w][e]
[f 2 1][bup 3 4 52 65535 0 0][vp 1 0 0 45 0 0]¿Eso es verdad, Ryoji?[n][w][e]

[msg MSG_032_0_0 [Ryoji Mochizuki]]
[f 2 1][bup 221 3 65535 65535 0 0][vp 1 0 0 46 0 0]Sabía que no podía derrotarme por completo.[n][w][e]
[f 2 1][bup 221 3 65535 65535 0 0][vp 1 0 0 47 0 0]Así que, como medida desesperada, me encerró dentro de una niña que pasaba por allí de casualidad.[n][w][e]
[f 2 1][bup 221 3 65535 65535 0 0][vp 1 0 0 48 0 0]La niña creció conmigo en su interior. Y el destino quiso que terminase volviendo aquí...[n][w][e]
[f 2 1][bup 221 3 65535 65535 0 0][vp 1 0 0 49 0 0]Incluso se cambió a vuestro colegio.[n][w][e]

[msg MSG_033_0_0 [Yukari Takeba]]
[f 2 1][bup 2 4 52 65535 0 0][vp 1 0 0 50 0 0]¿Una alumna nueva? ¿No será...?[n][w][e]

[msg MSG_034_0_0 [Ryoji Mochizuki]]
[f 2 1][bup 221 3 65535 65535 0 0][vp 1 0 0 51 0 0]Eso es. [nf].[n][w][e]
[f 2 1][bup 221 3 65535 65535 0 0][vp 1 0 0 52 0 0]He vivido dentro de ella durante mucho tiempo.[n][w][e]

[sel SEL_035_0_0 top]
[f 2 1]¿Dentro de mí?[e]
[f 2 1]...[e]

[msg MSG_036_0_0 [Yukari Takeba]]
[f 2 1][bup 2 3 52 65535 0 0][vp 1 0 0 53 0 0]¿P-pero cómo es posible...?[n][w][e]

[msg MSG_037_0_0 [Ryoji Mochizuki]]
[f 2 1][bup 221 3 65535 65535 0 0][vp 1 0 0 54 0 0]Cuando su Persona despertó, también lo hicieron las doce sombras.[n][w][e]
[f 2 1][bup 221 3 65535 65535 0 0][vp 1 0 0 55 0 0]Y todo para unirse a mí y volvernos un solo ser.[n][w][e]

[msg MSG_038_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 52 65535 0 0][vp 1 0 0 56 0 0]Ryoji, ¿tú eres el Tasador? ¡¿Y estabas dentro de ella?![n][w][e]
[f 2 1][bup 3 2 52 65535 0 0][vp 1 0 0 57 0 0][f 4 23 0 3 2 25 25]¡¿Cómo esperas que nos traguemos todo eso?![n][w][e]

[msg MSG_039_0_0 [Ryoji Mochizuki]]
[f 2 1][bup 221 3 65535 65535 0 0][vp 1 0 0 58 0 0]Es todo por mi culpa...[n][w][e]
[f 2 1][bup 221 3 65535 65535 0 0][vp 1 0 0 59 0 0]Lo siento.[n][w][e]
[f 2 1][bup 221 10 65535 65535 0 0][vp 1 0 0 60 0 0][f 4 23 0 221 10 25 25]Pero hay algo más... que necesito contaros.[n][w][e]

[msg MSG_040_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 4 52 65535 0 0][vp 1 0 0 61 0 0]¡Ryoji![n][w][e]

[msg MND_041_0_0]
[f 2 1]Ha perdido el conocimiento.[n][w][e]

[msg MSG_042_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 52 65535 0 0][vp 1 0 0 62 0 0]Está completamente agotado.[n][w][e]
[f 2 1][bup 5 0 52 65535 0 0][vp 1 0 0 63 0 0]Dejémosle descansar. Aigis nos necesita también.[n][w][e]
[f 2 1][bup 5 0 52 65535 0 0][vp 1 0 0 64 0 0]Retomaremos el tema desde donde lo dejamos.[n][w][e]

[msg MND_043_0_0]
[f 2 1]...[n][w][e]
[f 2 1]Qué duro ha sido escuchar eso...[n][w][e]
[f 2 1]Ryoji estuvo diez años viviendo dentro de mí, a la espera de entrar en contacto con las doce sombras.[n][w][e]
[f 2 1]Entonces, ¿el niño, ese tal Pharos, en realidad era Ryoji?[n][w][e]
[f 2 1]...[n][w][e]
[f 2 1]Hay muchas preguntas sin respuesta, pero Ryoji está inconsciente.[n][w][e]
[f 2 1]...[n][w][e]
[f 2 1]Llevamos a Ryoji y a Aigis a casa. Corre un aire frío y oscuro.[n][w][e]

