[msg MSG_000_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 1 65535 0 0][vp 1 0 0 1 0 0]Hola de nuevo. Ya tenemos aquí a todos los de segundo.[n][w][e]

[msg MSG_001_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 1 65535 0 0][vp 1 0 0 2 0 0]Bueno... ¿Por qué estamos todos aquí?[n][w][e]

[msg MSG_002_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 1 65535 0 0][vp 1 0 0 3 0 0]Ah, iba a hacerle una visita guiada de la residencia a Yamagishi.[n][w][e]
[f 2 1][bup 5 0 1 65535 0 0][vp 1 0 0 4 0 0][f 4 23 0 5 0 25 25]Pero entonces caí en la cuenta de que a vosotros tampoco os la he enseñado bien.[n][w][e]
[f 2 1][bup 5 0 1 65535 0 0][vp 1 0 0 5 0 0]Os pido perdón. Me gustaría aprovechar la ocasión para compensároslo.[n][w][e]

[sel SEL_003_0_0 top]
[f 2 1]Me parece bien.[e]
[f 2 1]A buenas horas.[e]

[msg MSG_004_0_0 [Junpei Iori]]
[f 2 1][bup 3 6 1 65535 0 0][vp 1 0 0 6 0 0]Eh, hace ya tiempo que vivimos aquí... Creo que nos hacemos una idea de cómo es.[n][w][e]

[msg MSG_004_5_0 [Yukari Takeba]]
[f 2 1][bup 2 6 1 65535 0 0][vp 1 0 0 7 0 0]Pues justo a ti no te vendría mal.[n][w][e]
[f 2 1][bup 2 0 1 65535 0 0][vp 1 0 0 8 0 0][f 4 23 0 2 0 25 25]Eres consciente de que, si haces el tonto y rompes algo, nos meterás a todos en un lío, ¿no?[n][w][e]

[msg MSG_005_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 1 65535 0 0][vp 1 0 0 9 0 0]Tampoco está de más hacerla, por si acaso.[n][w][e]

[msg MSG_005_5_0 [Yukari Takeba]]
[f 2 1][bup 2 6 1 65535 0 0][vp 1 0 0 10 0 0]Nunca se sabe si a cierta persona le dará por hacer el tonto a oscuras y romper algo.[n][w][e]

[msg MSG_006_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 1 65535 0 0][vp 1 0 0 11 0 0]Venga ya, ¡me las apaño bien! De hecho, ¡conozco tan bien este sitio que podría hacer yo la visita![n][w][e]

[msg MSG_007_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 1 65535 0 0][vp 1 0 0 12 0 0]Je... Entonces, serás un gran asistente.[n][w][e]
[f 2 1][bup 5 0 1 65535 0 0][vp 1 0 0 13 0 0][f 4 23 0 5 0 25 25]Dame el gusto, ¿quieres? Viendo que el número de miembros aumenta, vamos a poder acceder a más instalaciones.[n][w][e]

[msg MSG_008_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 1 65535 0 0][vp 1 0 0 14 0 0]¿Cómo, cosas nuevas? ¡Genial![n][w][e]
[f 2 1][bup 3 1 1 65535 0 0][vp 1 0 0 15 0 0]Entonces, ¿vamos a tener termas? ¡¿O un casino?![n][w][e]

[msg MSG_009_0_0 [Yukari Takeba]]
[f 2 1][bup 2 6 1 65535 0 0][vp 1 0 0 16 0 0]Qué tonto eres...[n][w][e]

[msg MSG_010_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 1 65535 0 0][vp 1 0 0 17 0 0]Habrá que verlo, ¿no?[n][w][e]

[msg MSG_010_5_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 1 65535 0 0][vp 1 0 0 18 0 0]Bueno, empecemos. Yamagishi, sígueme.[n][w][e]

[msg MSG_011_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 1 65535 0 0][vp 1 0 0 19 0 0]¡Ah, vale! Gracias por organizar esto para mí.[n][w][e]

[msg MSG_012_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 1 65535 0 0][vp 1 0 0 20 0 0]Esta es la cocina compartida.[n][w][e]

[msg MSG_012_5_0 [Yukari Takeba]]
[f 2 1][bup 2 1 1 65535 0 0][vp 1 0 0 21 0 0]Vaya, ¡qué limpia está ahora! No sabía que era tan grande...[n][w][e]

[msg MSG_012_7_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 1 65535 0 0][vp 1 0 0 22 0 0]Tenía pensado hacerlo antes, pero entre el ataque de la sombra de abril y la subsiguiente investigación, no he tenido tiempo.[n][w][e]
[f 2 1][bup 5 0 1 65535 0 0][vp 1 0 0 23 0 0]Ahora debería ser mucho más accesible. Podéis utilizar todo el menaje de cocina.[n][w][e]

[msg MSG_013_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 1 65535 0 0][vp 1 0 0 24 0 0]¿Cada uno os hacéis vuestra comida?[n][w][e]

[msg MSG_013_5_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 1 65535 0 0][vp 1 0 0 25 0 0]De vez en cuando, veo a Akihiko por aquí. En cuanto a mí, no puedo decir lo mismo.[n][w][e]
[f 2 1][bup 5 3 1 65535 0 0][vp 1 0 0 26 0 0][f 4 23 0 5 3 25 25]Antes teníamos a alguien que cocinaba bastante a menudo, pero...[n][w][e]

[msg MSG_014_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 1 65535 0 0][vp 1 0 0 27 0 0]Ahora que lo pienso, yo solo vengo para coger agua caliente. ¿Y tú?[n][w][e]

[sel SEL_014_5_0 top]
[f 2 1]Yo no cocino.[e]
[f 2 1]Me encantaría probar.[e]

[msg MSG_015_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 1 65535 0 0][vp 1 0 0 28 0 0]Supongo que, si solo cocinas para uno, tampoco ahorras mucho dinero.[n][w][e]
[f 2 1][bup 2 0 1 65535 0 0][vp 1 0 0 29 0 0]Es difícil gastar todo lo que compras antes de que se ponga malo, así que para eso es mejor comer fuera.[n][w][e]

[msg MSG_016_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 1 65535 0 0][vp 1 0 0 30 0 0]Si te preocupa llevar una dieta equilibrada, lo mejor es que te hagas tú la comida.[n][w][e]
[f 2 1][bup 2 0 1 65535 0 0][vp 1 0 0 31 0 0]Pero no es tan barato como lo pintan. No es fácil gastarlo todo antes de que se ponga malo.[n][w][e]

[msg MSG_017_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 1 65535 0 0][vp 1 0 0 32 0 0]Caray, Yukari... ¿Eso significa que sabes cocinar?[n][w][e]

[msg MSG_018_0_0 [Yukari Takeba]]
[f 2 1][bup 2 4 1 65535 0 0][vp 1 0 0 33 0 0]¿Eh? Ah, bueno... Supongo que sí, ¡pero no soy ninguna chef![n][w][e]
[f 2 1][bup 2 0 1 65535 0 0][vp 1 0 0 34 0 0][f 4 23 0 2 0 25 25]Hace mucho que no lo hago, y ya he pasado suficiente vergüenza.[n][w][e]

[msg MSG_018_5_0 [Yukari Takeba]]
[f 2 1][bup 2 1 1 65535 0 0][vp 1 0 0 35 0 0]Pero, en una cocina así de grande, creo que podrían colaborar varias personas a la vez.[n][w][e]
[f 2 1][bup 2 1 1 65535 0 0][vp 1 0 0 36 0 0]Podemos dividir el trabajo y multiplicar el sabor, ¿no creéis? Probémoslo otro día.[n][w][e]

[msg MND_019_0_0]
[f 2 1]Si invito a alguien a cocinar,[n]podríamos preparar algo en la cocina.[n][w][e]

[msg MSG_020_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 1 65535 0 0][vp 1 0 0 37 0 0]Sigamos avanzando...[n][w][e]

[msg MSG_021_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 1 65535 0 0][vp 1 0 0 38 0 0]¡Aquí es donde pasamos el rato![n][w][e]

[msg MSG_022_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 1 65535 0 0][vp 1 0 0 39 0 0]Este es el vestíbulo... No creo que necesite más explicación.[n][w][e]

[msg MSG_022_5_0 [Junpei Iori]]
[f 2 1][bup 3 1 1 65535 0 0][vp 1 0 0 40 0 0]Espera... ¡¿Eso es un reproductor de DVD?! ¿Desde cuándo lo tenemos?[n][w][e]

[msg MSG_023_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 1 65535 0 0][vp 1 0 0 41 0 0]Ah, es mío.[n][w][e]
[f 2 1][bup 6 0 1 65535 0 0][vp 1 0 0 42 0 0]Me lo traje de casa, aunque es un modelo algo viejo...[n][w][e]

[sel SEL_023_5_0 top]
[f 2 1]Gracias.[e]
[f 2 1]¿No te importa dejarlo aquí?[e]

[msg MSG_023_7_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 1 65535 0 0][vp 1 0 0 43 0 0]No hay problema. Era uno que estaba roto.[n][w][e]
[f 2 1][bup 6 0 1 65535 0 0][vp 1 0 0 44 0 0]Pero he conseguido arreglarlo, así que espero que podáis usarlo.[n][w][e]

[msg MSG_024_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 1 65535 0 0][vp 1 0 0 45 0 0]Si me lo llevo a mi cuarto, estaría viendo pelis yo sola en el portátil. Espero que vosotros le deis mejor uso.[n][w][e]
[f 2 1][bup 6 1 1 65535 0 0][vp 1 0 0 46 0 0][f 4 23 0 6 1 25 25]Además, me gustan más los colores de la televisión de tubo.[n][w][e]

[msg MSG_025_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 1 65535 0 0][vp 1 0 0 47 0 0]Estos sofás son bastante cómodos. Sería el lugar perfecto para ver algo.[n][w][e]

[msg MSG_026_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 1 65535 0 0][vp 1 0 0 48 0 0]Anda, igual este sería un buen sitio...[n][w][e]
[f 2 1][bup 2 3 1 65535 0 0][vp 1 0 0 49 0 0][f 4 23 0 2 3 25 25]Hace tiempo que quiero ver unas películas, pero... preferiría no verlas sola.[n][w][e]

[msg MSG_027_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 1 65535 0 0][vp 1 0 0 50 0 0]¿Qué me dices? ¿A Yuka le dan miedo las pelis de terror?[n][w][e]
[f 2 1][bup 3 1 1 65535 0 0][vp 1 0 0 51 0 0]Menuda sorpresa que muestres tu lado tierno... Cuesta creer que seas la misma persona.[n][w][e]

[msg MSG_028_0_0 [Yukari Takeba]]
[f 2 1][bup 2 2 1 65535 0 0][vp 1 0 0 52 0 0]¿Qué pretendes decir con eso exactamente?[n][w][e]

[msg MSG_028_5_0 [Junpei Iori]]
[f 2 1][bup 3 4 1 65535 0 0][vp 1 0 0 53 0 0]Eh... Espera, ¿qué he dicho? ¡Lo retiro! No pretendía insinuar nada, ¡lo juro![n][w][e]

[msg MSG_029_0_0 [Yukari Takeba]]
[f 2 1][bup 2 2 1 65535 0 0][vp 1 0 0 54 0 0]Los tienes cuadrados, Junpei.[n][w][e]
[f 2 1][bup 2 2 1 65535 0 0][vp 1 0 0 55 0 0]Más te vale andarte con ojo la próxima vez que vayamos a la Tártaro.[n][w][e]

[msg MSG_029_5_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 6 1 65535 0 0][vp 1 0 0 56 0 0]Eh, ¿Yukari? Me estás asustando...[n][w][e]

[msg MND_030_0_0]
[f 2 1]Creo que aquí podría ver una peli[n]con alguien.[n][w][e]

[msg MSG_031_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 1 65535 0 0][vp 1 0 0 57 0 0]Con esto, damos por vista la primera planta. Subamos.[n][w][e]

[msg MSG_032_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 1 65535 0 0][vp 1 0 0 58 0 0]Ah, por cierto, Kirijo...[n][w][e]
[f 2 1][bup 6 0 1 65535 0 0][vp 1 0 0 59 0 0]¿Podemos coger los libros que están en esa estantería de atrás?[n][w][e]

[msg MSG_033_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 1 65535 0 0][vp 1 0 0 60 0 0]Por supuesto.[n][w][e]
[f 2 1][bup 5 0 1 65535 0 0][vp 1 0 0 61 0 0]Los donaron algunos residentes. Yo misma los leo de vez en cuando.[n][w][e]

[msg MSG_034_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 1 65535 0 0][vp 1 0 0 62 0 0]Esta zona está muy bien. Es bonita, tranquila y te digo yo que esas sillas son mulliditas.[n][w][e]
[f 2 1][bup 3 1 1 65535 0 0][vp 1 0 0 63 0 0]Cuando vengo aquí a leer un buen libro, siempre terminan dándome las tantas.[n][w][e]

[msg MSG_035_0_0 [Yukari Takeba]]
[f 2 1][bup 2 6 1 65535 0 0][vp 1 0 0 64 0 0]Tú solo lees manga...[n][w][e]

[msg MSG_036_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 1 65535 0 0][vp 1 0 0 65 0 0]Je, je, a mí el manga me parece un tipo de literatura respetable. Quizá yo también pruebe a leer aquí.[n][w][e]

[msg MSG_037_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 1 65535 0 0][vp 1 0 0 66 0 0]En el vestíbulo siempre hay gente entrando y saliendo, así que igual aquí hay menos distracciones.[n][w][e]

[msg MND_037_5_0]
[f 2 1]Creo que aquí podría concentrarme[n]y leer un libro.[n][w][e]

[msg MSG_038_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 1 65535 0 0][vp 1 0 0 67 0 0]Utiliza este espacio como quieras. Cualquier libro sirve como medio para ampliar horizontes.[n][w][e]

[msg MSG_039_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 1 65535 0 0][vp 1 0 0 68 0 0]¡Sí, capitana![n][w][e]

[msg MSG_040_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 1 65535 0 0][vp 1 0 0 69 0 0]Solo una cosa, Iori...[n][w][e]

[msg MSG_041_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 1 65535 0 0][vp 1 0 0 70 0 0]Cuando termines un manga, vuelve a dejarlo en la estantería. No quiero verlos apilados en las mesas ni en las sillas.[n][w][e]

[msg MSG_041_5_0 [Junpei Iori]]
[f 2 1][bup 3 4 1 65535 0 0][vp 1 0 0 71 0 0]Oído cocina...[n][w][e]

[msg MSG_042_0_0 [Yukari Takeba]]
[f 2 1][bup 2 6 1 65535 0 0][vp 1 0 0 72 0 0]Jesús... [nl], échale un ojo a Junpei para que no lo ponga todo patas arriba.[n][w][e]

[msg MSG_043_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 1 65535 0 0][vp 1 0 0 73 0 0]Sigamos, entonces.[n][w][e]

