[msg MSG_000_0_0 [Monje]]
[f 2 1][bup 114 0 65535 65535 0 0][vp 1 0 0 1 0 0]¿Dónde está mi bebida?[n][w][e]

[msg MND_000_5_0]
[f 2 1]Le he dicho que la he pedido...[n][w][e]
[f 2 1]Eso debe haber impresionado al monje. Parece que se ha interesado por mí.[n][w][e]

[msg MSG_001_0_0 [Monje]]
[f 2 1][bup 114 0 65535 65535 0 0][vp 1 0 0 2 0 0]Tienes pinta de ser muy joven. ¿Sigues en el instituto?[n][w][e]

[msg MSG_001_3_0 [Monje]]
[f 2 1][bup 114 0 65535 65535 0 0][vp 1 0 0 3 0 0]¿En qué piensan los empleados de aquí dejando entrar a alguien como tú?[n][w][e]

[msg MSG_001_5_0 [Monje]]
[f 2 1][bup 114 0 65535 65535 0 0][vp 1 0 0 4 0 0]Ya que me has invitado a una copa, haré como que soy tu padre para que no te echen de aquí. Siéntate.[n][w][e]
[f 2 1][bup 114 2 65535 65535 0 0][vp 1 0 0 5 0 0][f 4 23 0 114 2 25 25]¿Y bien? Venga, siéntate. Me va a dar un tirón en el cuello de mirar hacia arriba.[n][w][e]

[msg MSG_002_0_0 [Monje]]
[f 2 1][bup 114 1 65535 65535 0 0][vp 1 0 0 6 0 0]¿Querías ver lo que hacen con su tiempo los adultos? Me lo puedo imaginar.[n][w][e]
[f 2 1][bup 114 0 65535 65535 0 0][vp 1 0 0 7 0 0][f 4 23 0 114 0 25 25]Bueno, no te preocupes, en dos o tres años podrás pasar el tiempo aquí sin supervisión.[n][w][e]
[f 2 1][bup 114 0 65535 65535 0 0][vp 1 0 0 8 0 0]Tómatelo con calma, jovencita. Enseguida llegarás a la mayoría de edad. No tengas prisa.[n][w][e]

[msg MSG_002_5_0 [Monje]]
[f 2 1][bup 114 0 65535 65535 0 0][vp 1 0 0 9 0 0]Dártelas de adulta solo te hace parecer más pequeña.[n][w][e]
[f 2 1][bup 114 0 65535 65535 0 0][vp 1 0 0 10 0 0]Je... Tiene gracia viniendo de un monje que bebe y fuma, ¿eh?[n][w][e]

[sel SEL_003_0_0 top]
[f 2 1]¿Sabe bien el alcohol?[e]
[f 2 1]¿A qué sabe el tabaco?[e]

[msg MSG_004_0_0 [Monje]]
[f 2 1][bup 114 0 65535 65535 0 0][vp 1 0 0 11 0 0]Hay a quien le gusta, supongo eso es todo. Quizá. No tengo ni idea.[n][w][e]
[f 2 1][bup 114 0 65535 65535 0 0][vp 1 0 0 12 0 0]Yo solo bebo para emborracharme. Te sientes mejor estando borracho.[n][w][e]

[msg MSG_005_0_0 [Monje]]
[f 2 1][bup 114 0 65535 65535 0 0][vp 1 0 0 13 0 0]¿Que a qué sabe? A hojas... No se me ocurre otra manera de describirlo.[n][w][e]
[f 2 1][bup 114 0 65535 65535 0 0][vp 1 0 0 14 0 0]No tiene que saberte bien. Solo fumo porque me ayuda a centrarme.[n][w][e]

[msg MSG_006_0_0 [Monje]]
[f 2 1][bup 114 0 65535 65535 0 0][vp 1 0 0 15 0 0]Los jóvenes nunca estáis contentos con lo que tenéis...[n][w][e]
[f 2 1][bup 114 0 65535 65535 0 0][vp 1 0 0 16 0 0]Pues no esperes gran cosa, jovencita. Así no te decepcionarás cuando las cosas no salgan bien.[n][w][e]
[f 2 1][bup 114 0 65535 65535 0 0][vp 1 0 0 17 0 0]Porque puede llegar un momento en que tengas que beber sin ganas y fumar para sobrellevar el día...[n][w][e]

[msg MSG_006_3_0 [Monje]]
[f 2 1][bup 114 0 65535 65535 0 0][vp 1 0 0 18 0 0]No te pareces nada a las maleantes que veo por la ciudad últimamente.[n][w][e]
[f 2 1][bup 114 0 65535 65535 0 0][vp 1 0 0 19 0 0]Siempre se las lleva la policía para interrogarlas. Qué vergüenza.[n][w][e]

[msg MSG_006_7_0 [Monje]]
[f 2 1][bup 114 1 65535 65535 0 0][vp 1 0 0 20 0 0]Voy a acordarme de tu cara. A la próxima, haré que te saquen de aquí, ¿me has entendido?[n][w][e]

[msg MND_007_0_0]
[f 2 1]He conocido a un monje extraño.[n][w][e]

[msg MSG_008_0_0 [Monje]]
[f 2 1][bup 114 0 65535 65535 0 0][vp 1 0 0 21 0 0]Cuando te canses, vete. Y no vuelvas.[n][w][e]

[msg MND_009_0_0]
[f 2 1]He decidido volver a la residencia.[n][w][e]

