[msg MSG_000_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 1 65535 65535 0 0][vp 1 0 0 1 0 0]Fua, qué locura. El sabor es muy adictivo, ¿verdad?[n][w][e]

[msg MND_001_0_0]
[f 2 1]A pesar de lo sencillo que parece el caldo a simple vista, los fideos acentúan su sabor.[n][w][e]

[msg MSG_002_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 0 65535 65535 0 0][vp 1 0 0 2 0 0]Por cierto, ¿por qué narices tu residencia es mixta?[n][w][e]
[f 2 1][bup 101 1 65535 65535 0 0][vp 1 0 0 3 0 0][f 4 23 0 101 1 25 25]¿Puedes ir, en plan, al dormitorio de Yukari y ese rollo?[n][w][e]

[sel SEL_003_0_0 top]
[f 2 1]Por supuesto.[e]
[f 2 1]Ni loca.[e]
[f 2 1]Es un secreto.[e]

[msg MSG_004_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 2 65535 65535 0 0][vp 1 0 0 4 0 0]¡¿P-por supuesto?! A ver, tampoco es una locura.[n][w][e]

[msg MSG_005_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 1 65535 65535 0 0][vp 1 0 0 5 0 0][f 5 13 2 5 101]Sí, eso pensaba. Está claro que es imposible abarcarlo todo.[n][w][e]

[msg MSG_006_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 1 65535 65535 0 0][vp 1 0 0 6 0 0][f 5 13 2 5 101]¿Secreto? A ver, el único secreto es que no hay nada entre vosotros.[n][w][e]

[msg MSG_007_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 0 65535 65535 0 0][vp 1 0 0 7 0 0]Bueno, de todas formas, las chicas de su edad no me van.[n][w][e]
[f 2 1][bup 101 0 65535 65535 0 0][vp 1 0 0 8 0 0]Me gustan las mujeres más mayores. ¿Y a ti?[n][w][e]

[sel SEL_008_0_0 top]
[f 2 1]A mí también me molan más mayores.[e]
[f 2 1]Las prefiero de mi edad.[e]
[f 2 1]¡Me gustan todas![e]

[msg MSG_009_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 1 65535 65535 0 0][vp 1 0 0 9 0 0][f 5 13 2 5 101]Ostras, ¿en serio? No hay muchas personas que piensen así.[n][w][e]
[f 2 1][bup 101 1 65535 65535 0 0][vp 1 0 0 10 0 0]¡Jolín, molas más de lo que pensaba![n][w][e]

[msg MSG_010_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 6 65535 65535 0 0][vp 1 0 0 11 0 0]Pff, no sabes lo que te pierdes, tía.[n][w][e]
[f 2 1][bup 101 0 65535 65535 0 0][vp 1 0 0 12 0 0][f 4 23 0 101 0 25 25]Las mujeres mayores son inteligentes, atractivas y sofisticadas.[n][w][e]
[f 2 1][bup 101 6 65535 65535 0 0][vp 1 0 0 13 0 0][f 4 23 0 101 3 25 25] Joder, mujer. Y yo que pensaba que lo comprenderías...[n][w][e]

[msg MSG_011_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 4 65535 65535 0 0][vp 1 0 0 14 0 0]¡Telita! No le haces ascos a ninguna, ¿eh?[n][w][e]
[f 2 1][bup 101 1 65535 65535 0 0][vp 1 0 0 15 0 0][f 4 23 0 101 1 25 25][f 5 13 2 5 101]Muy interesante. Así se vive de lujo, colega.[n][w][e]

[msg MSG_012_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 1 65535 65535 0 0][vp 1 0 0 16 0 0]A ver, que quede entre nosotros, pero hay alguien que me hace tilín.[n][w][e]
[f 2 1][bup 101 1 65535 65535 0 0][vp 1 0 0 17 0 0]Ese era el "plan secreto" del que te hablaba. La cuestión es que voy a pedirle salir.[n][w][e]

[msg MSG_012_3_0 [Kenji Tomochika]]
[f 2 1][bup 101 1 65535 65535 0 0][vp 1 0 0 18 0 0]Pero, escucha, es una profesora del insti.[n][w][e]
[f 2 1][bup 101 1 65535 65535 0 0][vp 1 0 0 19 0 0]Aunque eso no me echa para atrás. Prométeme que no se lo dirás a nadie, ¿vale?[n][w][e]
[f 2 1][bup 101 1 65535 65535 0 0][vp 1 0 0 20 0 0]Quizá sea raro que una profesora y su alumno salgan juntos.[n][w][e]

[msg MND_013_0_0]
[f 2 1]Kenji me ha contado su plan secreto.[n][w][e]
[f 2 1]Tengo la sensación de que nuestra relación se ha fortalecido.[n][w][e]

[msg SYS_014_0_0]
[f 2 1]DEV: Unused label.[n][w][e]

[msg MSG_015_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 4 65535 65535 0 0][vp 1 0 0 21 0 0]Mierda, que enseguida empieza mi programa favorito. ¡Me piro![n][w][e]

[msg MND_016_0_0]
[f 2 1]Me he despedido de Kenji y he vuelto a la residencia.[n][w][e]

