[msg MSG_000_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 2 65535 0 0][vp 1 0 0 1 0 0]¡Eh![n][w][e]
[f 2 1][bup 3 1 2 65535 0 0][vp 1 0 0 2 0 0]Uf, hace un frío que pela. Pero, claro, tú nunca faltarías a clase. Estoy impresionado.[n][w][e]

[msg MSG_001_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 2 65535 0 0][vp 1 0 0 3 0 0]El último año se me ha pasado volando. Ya estamos en tercero prácticamente.[n][w][e]
[f 2 1][bup 3 1 2 65535 0 0][vp 1 0 0 4 0 0]Solo queda un año más de instituto. ¿Crees que hay algo interesante en el horizonte?[n][w][e]

[sel SEL_002_0_0 top]
[f 2 1]Totalmente.[e]
[f 2 1]A saber.[e]

[msg MSG_003_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 2 65535 0 0][vp 1 0 0 5 0 0]¿Eso crees?[n][w][e]
[f 2 1][bup 3 0 2 65535 0 0][vp 1 0 0 6 0 0]A juzgar por los de tercero, yo no estaría tan seguro...[n][w][e]

[msg MSG_003_5_0 [Junpei Iori]]
[f 2 1][bup 3 0 2 65535 0 0][vp 1 0 0 7 0 0]Se pasan estudiando todo el puñetero día. Para mí, eso tiene poco de divertido.[n][w][e]
[f 2 1][bup 3 3 2 65535 0 0][vp 1 0 0 8 0 0][f 4 23 0 3 3 25 25]¿Así vamos a estar nosotros el año que viene? Rayos,¿por qué tengo la sensación de que se me está olvidando algo?[n][w][e]

[msg MSG_004_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 2 65535 0 0][vp 1 0 0 9 0 0]A juzgar por los de tercero, yo no estaría tan seguro...[n][w][e]
[f 2 1][bup 3 0 2 65535 0 0][vp 1 0 0 10 0 0]Se pasan estudiando todo el puñetero día. Para mí, eso tiene poco de divertido.[n][w][e]
[f 2 1][bup 3 3 2 65535 0 0][vp 1 0 0 11 0 0][f 4 23 0 3 3 25 25]¿Así vamos a estar nosotros el año que viene? Rayos,¿por qué tengo la sensación de que se me está olvidando algo?[n][w][e]

[msg MSG_005_0_0 [Chica]]
[f 2 1][bup 7 0 2 65535 0 0][vp 0 0 0 12 0 0]...[n][w][e]

[msg MSG_006_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 2 65535 0 0][vp 1 0 0 13 0 0]Eh, ¿esa chica nos está mirando?[n][w][e]
[f 2 1][bup 3 1 2 65535 0 0][vp 1 0 0 14 0 0][f 4 23 0 3 1 25 25]¡Es bien guapa! ¿Cómo es que no la he visto antes?[n][w][e]

[msg MSG_007_0_0 [Yukari Takeba]]
[f 2 1][bup 2 6 2 65535 0 0][vp 1 0 0 15 0 0]Pero ¿qué dices? Si vive en nuestra residencia...[n][w][e]

[msg MSG_008_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 2 65535 0 0][vp 1 0 0 16 0 0]Espera, ¡¿en serio?![n][w][e]
[f 2 1][bup 3 0 2 65535 0 0][vp 1 0 0 17 0 0][f 4 23 0 3 0 25 25]Y, eh... ¿Cómo se llama?[n][w][e]

[msg MSG_009_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 2 65535 0 0][vp 1 0 0 18 0 0]No sé. Tú me dirás.[n][w][e]

[msg MSG_010_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 2 65535 0 0][vp 1 0 0 19 0 0]Jo, entonces estás igual que yo.[n][w][e]
[f 2 1][bup 3 0 2 65535 0 0][vp 1 0 0 20 0 0]De todas formas, a estas alturas del año siempre hay jaleo en la residencia, con tanta gente yendo y viniendo.[n][w][e]

[msg MSG_010_5_0 [Junpei Iori]]
[f 2 1][bup 3 0 2 65535 0 0][vp 1 0 0 21 0 0]Ah, por cierto, ¿te has enterado? Sanada se marcha.[n][w][e]
[f 2 1][bup 3 0 2 65535 0 0][vp 1 0 0 22 0 0]Tú lo conoces, ¿no? Es el capitán del equipo de boxeo.[n][w][e]

[msg MSG_011_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 2 65535 0 0][vp 1 0 0 23 0 0]Sí, pero no suelo hablar mucho con él. Y sí; obviamente se marchan todos los graduados.[n][w][e]
[f 2 1][bup 2 0 2 65535 0 0][vp 1 0 0 24 0 0]Kirijo también lo está preparando todo para irse.[n][w][e]

[msg MSG_012_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 2 65535 0 0][vp 1 0 0 25 0 0]Mitsuru... Ah, la presidenta del consejo estudiantil. Ella también está en nuestra residencia, ¿no?[n][w][e]

[msg MSG_013_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 2 65535 0 0][vp 1 0 0 26 0 0]Pero ¿qué le pasa a esa chica?[n][w][e]
[f 2 1][bup 2 0 2 65535 0 0][vp 1 0 0 27 0 0][f 4 21 2 7]¡Eh, tú! ¿Nos estás mirando a nosotros?[n][w][e]
[f 2 1][bup 2 0 2 65535 0 0][vp 1 0 0 28 0 0]¿Pasa algo?[n][w][e]

[msg MSG_014_0_0 [Chica]]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 29 0 0]Ah, no; no es nada.[n][w][e]

[msg MSG_015_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 2 65535 0 0][vp 1 0 0 30 0 0]Parecía pensativa, ¿no?[n][w][e]

[msg MSG_016_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 2 65535 0 0][vp 1 0 0 31 0 0]Oye, no estará interesada en mi, ¡¿verdad?![n][w][e]

[msg MSG_017_0_0 [Yukari Takeba]]
[f 2 1][bup 2 6 2 65535 0 0][vp 1 0 0 32 0 0]Ja, ja, ni de broma.[n][w][e]

[msg MSG_018_0_0 [Junpei Iori]]
[f 2 1][bup 3 6 2 65535 0 0][vp 1 0 0 33 0 0]Yuka, tú sí que sabes cómo hacerme daño...[n][w][e]

