[msg MSG_000_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 1 0][vp 3 0 65535 2094 0 0]Venga, seamos serios. Es monísima...[n][w][e]
[f 2 1][bup 3 0 65535 65535 1 0]Seguro que es superpopular. Habrá un montón de tíos loquitos por ella.[n][w][e]
[f 2 1][bup 3 0 65535 65535 1 0]Pero ¿y si descubren que es... lo que ya sabes? Su forma de andar, su manera de hablar...[n][w][e]

[msg MSG_001_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2082 0 0]¡Aragaki es la hostia, colega! Jamás olvidaré lo que hizo por nosotros en el callejón.[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]¡Con él de vuelta en el equipo, nadie podrá con nosotros![n][w][e]

[msg MSG_002_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2002 0 0]¿Qué pasa, [nf]? ¡Lo de ser un héroe es lo más![n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]¡Qué ganas tengo de mañana, colega![n][w][e]

[msg MSG_003_0_0 [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0][vp 3 0 65535 2093 0 0][f 4 25 3]...[n][w][e]
[f 2 1][bup 3 3 65535 65535 0 0]Lo siento, pero necesito un tiempo a solas.[n][w][e]

[msg MSG_004_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2077 0 0]Oye, hipotéticamente hablando...[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Alguien me dice que se quiere morir. Y yo le respondo que no quiero que se muera.[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]¿Qué te parece? ¿Es raro?[n][w][e]

[sel SEL_005_0_0 top]
[f 2 1]No es raro para mí.[e]
[f 2 1]Sí, un poco.[e]

[msg MSG_006_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2042 0 0]Oh, me alegro. Gracias...[n][w][e]

[msg MSG_007_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2028 0 0]Tienes razón. Siempre actúo como un bicho raro cuando estoy cerca de ella...[n][w][e]

[msg MSG_008_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2004 0 0]¿Alguna vez has pensado en el sentido de la vida?[n][w][e]

[sel SEL_009_0_0 top]
[f 2 1]Hasta cierto punto.[e]
[f 2 1]Para nada.[e]

[msg MSG_010_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2062 0 0]Vaya, no imaginaba que fueras tan filosófica.[n][w][e]

[msg MSG_011_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2067 0 0]Yo tampoco lo hacía antes, pero últimamente pienso mucho en ello...[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Sobre todo cuando la miro. Hace que me replantee mi razón de vivir.[n][w][e]

[msg MSG_011_5_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2062 0 0]No, pero en serio. ¿Para qué vivo? Nunca me había parado a pensarlo hasta ahora...[n][w][e]

[msg MSG_012_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2001 0 0]Ahora que está Aragaki, el ambiente es mucho más serio...[n][w][e]

[msg MSG_013_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6024 0 0]Ahora que está Junpei, el ambiente es mucho más infantil...[n][w][e]

[msg MSG_014_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 65535 65535 0 0][vp 3 0 65535 2101 0 0]¡Ouch! Esa ha dolido, Ai.[n][w][e]
[f 2 1][bup 3 4 65535 65535 0 0]No sé ni qué responderte, vaya.[n][w][e]

[msg MSG_015_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2078 0 0]Eh, dicen que va a llegar un tifón a esta zona.[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Espero que se quede para largo...[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Así no tendremos que ir a clase con toda la lluvia.[n][w][e]
[f 2 1][bup 3 4 65535 65535 0 0][vp 3 0 65535 2126 0 0]¡Si no, sería un fastidio![n][w][e]

[msg MSG_016_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2077 0 0]Sí, Chidori va a necesitar algo de tiempo para tranquilizarse.[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Así que le voy a dar espacio antes de siquiera pensar en ir en serio. Y nada de atajos, por supuesto.[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]Ya sé que será difícil, pero no me importa. Valdrá la pena si es por ella.[n][w][e]

[msg MSG_017_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2032 0 0]Lo único malo de que se cancele el festival del instituto es que no podremos ver a Yuka vestida de sirvienta.[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Vaya mierda, ¿eh?[n][w][e]

[sel SEL_018_0_0 top]
[f 2 1]Y que lo digas.[e]
[f 2 1]¿Y si le pido que se ponga el traje?[e]

[msg MSG_019_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2026 0 0]¿A que sí?[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Estoy seguro de que no somos los únicos que lo pensamos.[n][w][e]

[msg MSG_020_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2048 0 0]¿Eh? ¡¿Desde cuándo estás tan interesada?![n][w][e]

[msg MSG_021_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2001 0 0]Se dice que los tontos nunca se ponen enfermos, ¿lo sabías?[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Ah, espera. Eso significa que... como has enfermado, ¡tienes buen coco! Y como yo no, debo de ser...[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]B-bah, ¿qué sabrá la gente?[n][w][e]

[msg MSG_022_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2078 0 0]Madre mía, ¡qué locura de tifón! Todo estaba volando por los aires.[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Bueno, a ver, todo tampoco.[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]No he visto un puesto de ramen volando, por ejemplo...[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2062 0 0]Ains. Lo que habría dado por verlo.[n][w][e]

[msg MSG_023_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2074 0 0]Ojalá el tifón nos echara una mano...[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]¡Podría volar un puesto de ramen entero y matar a una sombra de un golpe![n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]¡¿A que molaría?![n][w][e]

[msg MSG_024_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][f 4 25 7]...[n][w][e]

[msg MSG_025_0_0 [Yukari Takeba]]
[f 2 1][bup 2 6 65535 65535 0 0][f 4 25 2]...[n][w][e]

[msg MSG_026_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 6 65535 65535 0 0][f 4 25 6]...[n][w][e]

[msg MSG_027_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 65535 65535 0 0][vp 3 0 65535 2092 0 0][f 4 25 3]...[n][w][e]

[msg MSG_028_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2009 0 0]Ey, [nf]. ¿Qué tal todo?[n][w][e]

[sel SEL_029_0_0 top]
[f 2 1]Bien.[e]
[f 2 1]No muy allá.[e]

[msg MSG_030_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2133 0 0]¡No hay nada malo en estar bien! Al fin y al cabo, ¡hay gente que necesita de mi energía positiva![n][w][e]

[msg MSG_031_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 65535 65535 0 0][vp 3 0 65535 2099 0 0]¿En serio, tía? Venga ya...[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]¡Anímate, que eres joven! ¡Sal a divertirte![n][w][e]

[msg MSG_032_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2132 0 0]Quizá debería probar un régimen de entrenamiento personalizado como Sanada.[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]Como Chidori está mejorando, creo que debería empezar a entrenar duro otra vez.[n][w][e]

[msg MSG_033_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2001 0 0]Sabéis lo que dicen de los animales acorralados, ¿no?[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Que se ponen nerviosos y contraatacan.[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]¿Crees que se aplica también a las sombras?[n][w][e]

[msg MSG_034_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6058 0 0]¿Mejorará su poder de combate si se encuentran bajo presión?[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0]No estoy del todo segura, pero tenemos que estar preparados por si acaso.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0]Creo que lo más beneficioso sería seguir entrenando nuestra fuerza. Al fin y al cabo, nunca se es demasiado fuerte.[n][w][e]

[msg MSG_035_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2007 0 0]Colega, de verdad, ¡están boicoteando mi relación con Chidori! ¡Te lo digo en serio![n][w][e]

[sel SEL_036_0_0 top]
[f 2 1]A ver, cuenta.[e]
[f 2 1]No me interesa, lo siento.[e]

[msg MSG_037_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2075 0 0]Sabes que últimamente paso mucho tiempo en el hospital, ¿no?[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Pues hay una anciana que trabaja en recepción, y no veas...[n][w][e]
[f 2 1][bup 3 4 65535 65535 0 0]Colega, ¡es una plasta de la leche! ¡No para de atosigarme con preguntas superembarazosas![n][w][e]
[f 2 1][bup 3 4 65535 65535 0 0][vp 3 0 65535 2113 0 0]Y cuando no, ¡me dice que me pire porque se ha pasado la hora de visitas![n][w][e]
[f 2 1][bup 3 3 65535 65535 0 0]¡Está haciendo que pierda tiempo de estar con Chidori! Que me deje en paz de una vez, colega.[n][w][e]

[msg MSG_038_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 65535 65535 0 0][vp 3 0 65535 2103 0 0]Ah, venga, mi amiga, mi hermana, mi compañera del alma, escúchame, anda.[n][w][e]

[msg MSG_039_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2086 0 0]¡Puedes dejarme la próxima operación a mí![n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]¡Yo te cubro! No tienes que preocuparte por mí.[n][w][e]

[msg MSG_040_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2001 0 0]¿Qué estrategia crees que seguirá Strega en esta ocasión?[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]Ahora que Chidori está de mi lado, no tienen a nadie que les preste apoyo.[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]¡Son como un suspensorio sin coquilla![n][w][e]

[msg MSG_041_0_0 [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0][vp 3 0 65535 2077 0 0]Aragaki fue un fuera de serie hasta el mismo final...[n][w][e]
[f 2 1][bup 3 3 65535 65535 0 0]Ya sabes, cuando dijo eso de "Así es como tiene que ser"...[n][w][e]
[f 2 1][bup 3 3 65535 65535 0 0]Tengo sus últimas palabras grabadas en el cerebro...[n][w][e]
[f 2 1][bup 3 3 65535 65535 0 0][vp 3 0 65535 2061 0 0]¿Crees que tus últimas palabras tendrán tanto impacto?[n][w][e]

[sel SEL_042_0_0 top]
[f 2 1]Por supuesto.[e]
[f 2 1]Ni de broma.[e]
[f 2 1]Las tuyas también podrían.[e]

[msg MSG_043_0_0 [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0][vp 3 0 65535 2084 0 0]Vaya, no creo que pudiera decir algo así...[n][w][e]

[msg MSG_044_0_0 [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0][vp 3 0 65535 2093 0 0]Ya, yo no creo que pudiera decir algo así...[n][w][e]

[msg MSG_045_0_0 [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0][vp 3 0 65535 2092 0 0]Ja, ni de coña, tú. No tengo huevos a decir algo así.[n][w][e]

[msg MSG_045_5_0 [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0][vp 3 0 65535 2092 0 0]Aragaki es la hostia. Una persona normal no podría hacer lo que él hizo...[n][w][e]

[msg MSG_046_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2110 0 0]Es mucho más duro de lo que creía.[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]Yo estaría como tres días en el pozo... O puede que una semana entera.[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]Pero ¿como si nada en solo un día? Nah, ¡es un campeón![n][w][e]

[msg MSG_047_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2032 0 0]Sí, ya, sé que tendría estar estudiando.[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Pero no puedo concentrarme.[n][w][e]
[f 2 1][bup 3 3 65535 65535 0 0]Ha sido un golpe muy duro, colega...[n][w][e]
[f 2 1][bup 3 3 65535 65535 0 0][vp 3 0 65535 2129 0 0]¿Por qué, Aragaki...?[n][w][e]

[msg MSG_048_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2124 0 0]Tengo la motivación bajo mínimos, colega. He intentado estudiar porque los exámenes son pronto, pero...[n][w][e]
[f 2 1][bup 3 3 65535 65535 0 0]No sé, no puedo superar las cosas tan rápidamente...[n][w][e]

[msg MSG_049_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2088 0 0]¡Toma ya, se acabaron los exámenes! ¡Al cuerno con las notas![n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]¡A salir con Chidori se ha dicho![n][w][e]

[msg MSG_050_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2114 0 0]Fiu, todas aprobadas...[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]No tendré que decirle a Aragaki que he suspendido cuando vaya a visitar su tumba.[n][w][e]

[msg MSG_051_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2063 0 0]Pues, si la Hora Oscura desaparece, yo solo pienso dormir.[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Luchar en la torre Tártaro es de lo más extenuante...[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Solo pido una noche de sueño. Que pueda dormir como un bebé.[n][w][e]

[msg MSG_052_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0]Uf, qué bien suena. Un sueño reparador me vendría de perlas. A mi piel le viene bien un poco de amor...[n][w][e]

[msg MSG_053_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6058 0 0]Con un poco de mantenimiento, el cuerpo se me queda como nuevo.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0]¿Quieres quedarte un rato conmigo, Yukari?[n][w][e]

[msg MSG_054_0_0 [Yukari Takeba]]
[f 2 1][bup 2 6 65535 65535 0 0][vp 3 0 65535 1122 0 0]Eh, no creo que eso sea posible.[n][w][e]

[msg MSG_055_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2001 0 0]Todo volverá a la normalidad cuando derrotemos al próximo enemigo.[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]La verdad es que me pone un poco triste, pero una vida normal es mucho mejor...[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]Quiero salir con mis amigos para hacer el tonto, y quedar más a menudo con Chidori...[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2117 0 0]¡Vamos a darle una paliza de aúpa a esa sombra, tío![n][w][e]

[msg MSG_056_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2001 0 0]Fuuka ha cambiado mucho, ¿verdad? Me pregunto si será porque Moriyama se ha mudado.[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Pero ¿lo normal no sería sentir tristeza por que se vaya?[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Tío, no entiendo a las chicas...[n][w][e]

[msg MSG_057_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2062 0 0]¿Soy yo...[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]o Sanada ha cambiado? Parece distinto a como era antes.[n][w][e]

[sel SEL_058_0_0 top]
[f 2 1]Es verdad.[e]
[f 2 1]Son imaginaciones tuyas.[e]

[msg MSG_059_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2110 0 0]Después de todo lo que ha pasado, no ha perdido la esperanza. Todo lo contrario.[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Aragaki es la hostia, sí..., pero Sanada también.[n][w][e]
[f 2 1][bup 3 3 65535 65535 0 0]Son la definición de un dúo perfecto. Ojalá llegue a ser tan fuerte como ellos algún día.[n][w][e]

[msg MSG_060_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2036 0 0]¡Qué va! Tiene un aura totalmente distinta. Fíjate más la próxima vez.[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]O sea, cuando vuelve de correr, casi parece que le sale humo del cuerpo. El tío está a tope.[n][w][e]

[msg MSG_061_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2077 0 0]A ver, es una pregunta rara, pero tengo que hacerla...[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]¿Mi época de superhéroe terminará cuando dejemos de luchar?[n][w][e]

[sel SEL_062_0_0 top]
[f 2 1]Sí, supongo.[e]
[f 2 1]Pues hombre, claro.[e]

[msg MSG_063_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2092 0 0]Sí... eso pensaba.[n][w][e]

[msg MSG_064_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0]Bueno, no pasa nada, de verdad.[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]¡Eso no cambiará el vínculo que tengo con Chidori![n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2117 0 0]¡Disfrutaré de ser un superhéroe mientras dure![n][w][e]

[msg MSG_065_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 65535 65535 0 0][vp 3 0 65535 2101 0 0]¡Eh! Colega, relájate. ¡La bordería sobra![n][w][e]

[msg MSG_065_5_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2095 0 0]Bueno, aunque deje de ser un superhéroe, no cambiará mi relación con Chidori...[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]Así que nos encargaremos igual que siempre. ¡Vamos a por la victoria![n][w][e]

[msg MSG_066_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2009 0 0]¡Koromaru es increíble, colega![n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]No teme enfrentarse a las sombras a pesar de su tamaño.[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]¡Venga, la próxima sombra que derrote se la dedico a Koromaru![n][w][e]

[msg MSG_067_0_0 [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0][vp 3 0 65535 2074 0 0]Estos días ando tan liado que no he podido ver a Chidori...[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]Pero pronto le daremos carpetazo a este asunto.[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]En cuanto acabemos con la última sombra, ¡iré derechito al hospital a verla![n][w][e]

[msg MSG_068_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2078 0 0]Uy, casi se me pasa que mañana tenemos el día libre.[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Lo más seguro es que me quede aquí sin hacer nada. También toca prepararse para la última operación.[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]¡Mañana tenemos que ir a por todas![n][w][e]

[msg MSG_069_0_0 [Junpei Iori]]
[f 2 1][bup 3 2 65535 65535 0 0][vp 3 0 65535 2129 0 0]No me puedo creer que respetásemos a ese cabronazo de Ikutsuki.[n][w][e]
[f 2 1][bup 3 2 65535 65535 0 0]Colega, no sabes el cabreo que llevo. Ojalá tuviera una de esas máquinas que borran los recuerdos.[n][w][e]
[f 2 1][bup 3 2 65535 65535 0 0]No pienso confiar en ningún otro adulto.[n][w][e]

[msg MSG_070_1_0 [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0][vp 3 0 65535 2092 0 0]Chidori... ¿Qué te ha pasado?[n][w][e]

[msg MSG_075_0_0 [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0][vp 3 0 65535 2093 0 0]No entiendo nada... ¿Qué le ha pasado a Chidori...?[n][w][e]

[msg MSG_076_1_0 [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0][vp 3 0 65535 2111 0 0]A lo mejor debería ir a visitarla otra vez, pero...[n][w][e]
[f 2 1][bup 3 3 65535 65535 0 0]No sé qué decirle. Si tuviera algún motivo para verla...[n][w][e]

[msg MSG_076_2_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2001 0 0]Fui al hospital a ver a Chidori...[n][w][e]
[f 2 1][bup 3 3 65535 65535 0 0]Me ha ignorado todo el tiempo.[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]En fin, no me queda otra. A lo mejor me toca quedarme toda la noche en vela pensando chistes para hacerla reír...[n][w][e]

[msg MSG_077_1_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2005 0 0]Eh, colega, escúchame un segundo...[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Es que llegué a la habitación de Chidori, me armé de valor y le solté mi mejor frase...[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Para sorpresa de nadie, volvió a ignorarme. Pero lo peor fueron las miradas que me echaron todos. Uf...[n][w][e]

[msg MSG_077_2_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2111 0 0]¿Estaría de mal humor...?[n][w][e]
[f 2 1][bup 3 3 65535 65535 0 0]A lo mejor debería ir a verla, pero... Mmm...[n][w][e]

[msg MSG_082_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2125 0 0]¿Mm? ¿Quién es misterioso? ¿Ryoji?[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]¡Ja! Es pura fachada, te lo digo yo.[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2070 0 0]Solo intenta camelarse a las tías haciéndose el interesante.[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]Es un chico guapete como cualquier otro. Es decir, ¡como aquí el menda![n][w][e]

[msg MSG_083_1_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2062 0 0]Fui a visitar a Chidori y, mira tú por dónde... pasó de mi culo.[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]Así que hice todo lo posible, dejé la dignidad en casa y volví arrastrándome.[n][w][e]

[msg MSG_083_2_0 [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0][vp 3 0 65535 2093 0 0]Aunque visite a Chidori, volverá a rechazarme...[n][w][e]
[f 2 1][bup 3 4 65535 65535 0 0]¡Argh! ¡No me puedo creer que lleve una semana llorando por las esquinas por esto![n][w][e]

[msg MSG_088_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2077 0 0]Sanada también lo está pasando mal.[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Qué mal, colega. ¿Qué pasa si los de tercero deciden abandonar SEES?[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]No sé yo si seremos capaces de conseguirlo sin ellos.[n][w][e]

[msg MSG_089_0_0 [Ken Amada]]
[f 2 1][bup 8 3 65535 65535 0 0][vp 3 0 65535 7065 0 0]¡No digas eso, Junpei![n][w][e]

[msg MSG_090_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2062 0 0]En este mundo, hay cosas que no se pueden cambiar.[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Así que es mejor concentrarse en aquello que sí.[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]¿Me pillas, no?[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2117 0 0]Lo que intento decir es que... ¡Hay que pasárselo bomba en el viaje escolar![n][w][e]

[msg MSG_091_0_0 [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0][vp 3 0 65535 2070 0 0]Hablando de recuerdos...[n][w][e]
[f 2 1][bup 3 3 65535 65535 0 0]Las pasamos canutas en las aguas termales, ¿eh?[n][w][e]
[f 2 1][bup 3 3 65535 65535 0 0]Si las chicas fueran menos propensas a las ejecuciones... No quiero ni acordarme.[n][w][e]

[msg MSG_092_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2098 0 0]¿Mm? ¿Recuerdos de Kioto?[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0][f 4 25 3]...[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Pues... No me acuerdo de nada. Pero nada de nada.[n][w][e]

[msg MSG_094_1_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2119 0 0]¡Tengo una estrategia nueva! Le hablaré a Chidori del viaje escolar. ¡Seguro que eso nos une más![n][w][e]
[f 2 1][bup 3 3 65535 65535 0 0]O eso creo, vaya. No sé yo si funcionará...[n][w][e]

[msg MSG_099_0_0 [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0][vp 3 0 65535 2077 0 0]A Chidori no le gustaría que fuera llorando por las esquinas, ¿verdad?[n][w][e]

[sel SEL_100_0_0 top]
[f 2 1]Es verdad.[e]
[f 2 1]Lo entendemos.[e]

[msg MSG_101_0_0 [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0][vp 3 0 65535 2028 0 0]Sí, lo sé... Ya lo sé.[n][w][e]
[f 2 1][bup 3 3 65535 65535 0 0]Sé que tengo que superarlo. Intento olvidarme del tema, pero es que no puedo.[n][w][e]
[f 2 1][bup 3 3 65535 65535 0 0]Ahora sé lo que significa que te rompan el corazón...[n][w][e]

[msg MSG_102_0_0 [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0][vp 3 0 65535 2067 0 0]Je, ¿qué intentas, animarme o algo?[n][w][e]
[f 2 1][bup 3 3 65535 65535 0 0]Pero gracias. Intentaré salir de este agujero.[n][w][e]

[msg MSG_103_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2084 0 0]Lo he decidido. Lucharé para acabar con la Hora Oscura.[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Lucharé para acabar con la Hora Oscura... Para acabar con la Hora Oscura, con todo lo demás y para vivir por los dos.[n][w][e]
[f 2 1][bup 3 64 65535 65535 0 0][vp 3 0 65535 2136 0 0]Por mí y por... Por Chi...[n][w][e]
[f 2 1][bup 3 64 65535 65535 0 0]Lo siento, hoy estoy un poco desganado. A lo mejor mañana.[n][w][e]

[msg MSG_104_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2078 0 0]Eh, ¿qué pasa? Ryoji y yo estamos pasando el rato en mi habitación.[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]No se va a quedar mucho, así que avisa si quieres tirar a la torre Tártaro.[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Bueno, ¿qué refresco quería...?[n][w][e]

[msg MSG_105_0_0 [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0][vp 3 0 65535 2001 0 0]Es rarísimo esto. Mañana es luna llena, pero todo está tranquilo. Demasiado tranquilo, diría yo...[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Bueno, supongo que esto demuestra que hemos vuelto a nuestra vida cotidiana.[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]No sé bien por qué, pero estoy algo inquieto...[n][w][e]

[msg MSG_106_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2074 0 0]¿No te quedaste a cuadros?[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]¿Te acuerdas de cuando Ai empezó a preguntarnos qué significaba vivir y todo eso?[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Han pasado tantas cosas. Me pregunto si le habrá estado afectando...[n][w][e]

[msg MSG_107_0_0 [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0][vp 3 0 65535 2129 0 0]Ese cabronazo de Ryoji... Se le ha tenido que ir la olla para soltar todo eso sin venir a cuento.[n][w][e]
[f 2 1][bup 3 3 65535 65535 0 0]Vaya mierda, colega. No lo entiendo...[n][w][e]

[msg MSG_108_0_0 [Junpei Iori]]
[f 2 1][bup 3 2 65535 65535 0 0][vp 3 0 65535 2135 0 0]Estúpido Ryoji...[n][w][e]
[f 2 1][bup 3 2 65535 65535 0 0]A quién se le ocurre decir que el mundo va a terminarse...[n][w][e]
[f 2 1][bup 3 2 65535 65535 0 0]Además, ¡¿a qué se refiere con eso de "El Tasador"?![n][w][e]

[msg MSG_109_0_0 [Junpei Iori]]
[f 2 1][bup 3 2 65535 65535 0 0][vp 3 0 65535 2129 0 0]Ryoji se ha esfumado, sin más...[n][w][e]
[f 2 1][bup 3 2 65535 65535 0 0]Va, suelta todo eso de que el mundo se acaba y que tenemos que tomar una decisión antes de Nochevieja, y desaparece...[n][w][e]
[f 2 1][bup 3 64 65535 65535 0 0]¿Qué cojones, colega? No tiene gracia.[n][w][e]

[msg MSG_110_0_0 [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0][vp 3 0 65535 2094 0 0]Vaya plan... Me voy a morir justo cuando empiezo a conocerme mejor...[n][w][e]
[f 2 1][bup 3 3 65535 65535 0 0]Puede que a esto se refiriera Chidori cuando dijo que tenía miedo...[n][w][e]
[f 2 1][bup 3 3 65535 65535 0 0]Chidori... Creo que ya lo pillo.[n][w][e]
[f 2 1][bup 3 3 65535 65535 0 0][vp 3 0 65535 2093 0 0][f 4 25 3]...[n][w][e]

[msg MSG_111_0_0 [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0][vp 3 0 65535 2053 0 0]Siento lo de antes, colega. Encima que me has estado ayudando todo este tiempo...[n][w][e]
[f 2 1][bup 3 3 65535 65535 0 0]Pero ¿sabes esa angustia cuando llegas a un callejón sin salida? Qué asco.[n][w][e]

[msg MSG_112_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2032 0 0]Colega, tengo un problemón. No he estudiado nada para los exámenes.[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]¿Y tú?[n][w][e]

[sel SEL_113_0_0 top]
[f 2 1]Por supuesto.[e]
[f 2 1]Para nada.[e]

[msg MSG_114_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 65535 65535 0 0][vp 3 0 65535 2101 0 0]¡¿Qué?! ¿Me vas a dejar en la estacada?[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]¿De qué vas? Somos amigos, ¿no? Colegas. Cómplices. Venga, ¡acompáñame en el camino al fracaso![n][w][e]

[msg MSG_115_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2132 0 0]¡Que se note que somos colegas![n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]¡Venga, a suspender![n][w][e]

[msg MSG_115_5_0 [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0][vp 3 0 65535 2062 0 0]Mmm, ya, no creo que cambie mucho la cosa aunque me ponga a estudiar ahora.[n][w][e]
[f 2 1][bup 3 3 65535 65535 0 0]Además, no estoy de humor para estudiar...[n][w][e]

[msg MSG_116_0_0 [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0][vp 3 0 65535 2066 0 0]Creo que la he cagado en los exámenes.[n][w][e]
[f 2 1][bup 3 3 65535 65535 0 0]¿Cómo me iba a concentrar sabiendo que el mundo se va a pique...?[n][w][e]

[msg MSG_117_0_0 [Junpei Iori]]
[f 2 1][bup 3 2 65535 65535 0 0][vp 3 0 65535 2074 0 0]Los imbéciles de Strega no han hecho nada aún, ¿no?[n][w][e]
[f 2 1][bup 3 2 65535 65535 0 0]Que se den prisa y den la cara.[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]No sé lo que se traen entre manos, pero los voy a machacar.[n][w][e]

[msg MSG_118_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 2 65535 65535 0 0][vp 3 0 65535 3024 0 0]Ahí llevas razón.[n][w][e]
[f 2 1][bup 4 2 65535 65535 0 0]No pienso dejarlos impunes después de lo que le hicieron a Shinji y a Chidori.[n][w][e]

[msg MSG_119_0_0 [Koromaru]]
[f 2 1][bup 9 2 65535 65535 0 0][vp 3 0 65535 8004 0 0]¡Guau...![n][w][e]

[msg MSG_120_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0]Parece que Koromaru se apunta. ¿A que sí, colega?[n][w][e]

[msg MSG_121_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2078 0 0]¡Ya mismo es Navidad! ¿Tienes ganas?[n][w][e]

[sel SEL_122_0_0 top]
[f 2 1]Por supuesto.[e]
[f 2 1]No, la verdad.[e]

[msg MSG_123_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2088 0 0]¡Chachi! ¡A disfrutar de la Navidad![n][w][e]

[msg MSG_124_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 65535 65535 0 0][vp 3 0 65535 2007 0 0]¡Venga! No tires la toalla.[n][w][e]
[f 2 1][bup 3 4 65535 65535 0 0]¡Esta podría ser nuestra última Navidad![n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]¡Tienes que disfrutarla mientras dure![n][w][e]

[msg MSG_124_5_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2086 0 0]¡Esta es la nuestra! ¡Hagamos que estas Navidades sean inolvidables![n][w][e]

[msg MSG_125_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2002 0 0]¡Anda, colega! Parece que vamos a pasar la Navidad más solos que la una.[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]¡Vamos a hacer una locura esta noche! ¿Vamos a la ciudad solos tú y yo?[n][w][e]

[sel SEL_126_0_0 top]
[f 2 1]Buen intento, Tontei.[e]
[f 2 1]... Pues no es mala idea.[e]

[msg MSG_127_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 65535 65535 0 0][vp 3 0 65535 2102 0 0]Colega, relájate.[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]Era broma. No montes un drama.[n][w][e]

[msg MSG_128_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 65535 65535 0 0][vp 3 0 65535 2007 0 0]¡Que era broma, tú! No le des tantas vueltas.[n][w][e]

[msg MSG_129_0_0 [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0][vp 3 0 65535 2108 0 0]Bueno, bueno, bueno... Mira qué contenta estás.[n][w][e]
[f 2 1][bup 3 3 65535 65535 0 0]Me he enterado de que anoche también llegaste tarde.[n][w][e]
[f 2 1][bup 3 3 65535 65535 0 0]¿Tienes que ir presumiendo? Qué envidia me das, colega.[n][w][e]

[msg MSG_130_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2001 0 0]Los últimos exámenes han sido la leche de difíciles, ¿eh?[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]La he cagado en todos. Y no soy el único, mis amigos están superpreocupados también.[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Aunque viendo el panorama...[n][w][e]
[f 2 1][bup 3 3 65535 65535 0 0][vp 3 0 65535 2060 0 0]Parece que mis notas son lo de menos. Je...[n][w][e]

[msg MSG_131_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2075 0 0]Chidori dio su vida... para que yo pudiera seguir con la mía.[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]Por eso no puedo aceptarlo. Y una mierda me voy a olvidar de ella.[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]Prefiero morir a olvidar.[n][w][e]

[msg MSG_132_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2001 0 0]Oye, ¿le pasó algo a Ai cuando la estaban reparando?[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Parece distinta...[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Es como si fuera humana. No sé, es difícil de explicar.[n][w][e]

[msg MSG_133_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2086 0 0]¿Todavía no ha llegado Ryoji? ¿Dónde leches se mete este tío?[n][w][e]

[msg MSG_134_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2043 0 0]Lo sabía, colega. Sabía que harías eso.[n][w][e]

[msg MSG_135_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2009 0 0]Eh, qué oportuno. Me entiendes, ¿verdad?[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Cuando te imaginas un kimono, piensas en una tía buenorra sin nada debajo, ¿verdad?[n][w][e]

[sel SEL_136_0_0 top]
[f 2 1]Prueba con otra persona.[e]
[f 2 1]...[e]
[f 2 1]Sin comentarios.[e]

[msg MSG_137_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2036 0 0]Venga, que no es culpa mía. ¡Es la fantasía de cualquier tío![n][w][e]

[msg MSG_138_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2026 0 0]¡Ja! ¿Alguien ha dicho algo? ¡Porque yo no![n][w][e]

[msg MSG_139_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2066 0 0]Venga, colega. No disimules. ¡Seguro que las chicas también lo pensáis![n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]Apuesto a que vas a fantasear con ello cuando vuelvas a tu habitación.[n][w][e]

[msg MSG_140_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2114 0 0]Ya sé que es Año Nuevo, pero no sé, no se siente como tal...[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Que si la secta, que si el fin del mundo... Vaya manera de cargarse el ambiente.[n][w][e]

[msg MSG_141_0_0 [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0][vp 3 0 65535 2123 0 0]¿Has visto lo que ha hecho la secta esa?[n][w][e]
[f 2 1][bup 3 3 65535 65535 0 0]¡Está todo hecho un caos! ¿Cómo de pirado tienes que estar para hacer algo así?[n][w][e]

[msg MSG_142_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2078 0 0]Va a comenzar el instituto. ¿Cómo estarán los demás...?[n][w][e]

[sel SEL_143_0_0 top]
[f 2 1]Seguro que igual.[e]
[f 2 1]Con el coco comido por la secta.[e]

[msg MSG_144_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2025 0 0]Tienes razón. Las vacaciones no han sido tan largas como para que la gente cambie.[n][w][e]

[msg MSG_145_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 65535 65535 0 0][vp 3 0 65535 2103 0 0]E-es broma, ¿no?[n][w][e]
[f 2 1][bup 3 4 65535 65535 0 0]No puedes hablar en serio...[n][w][e]
[f 2 1][bup 3 3 65535 65535 0 0]¡Porque si ese es el plan que hay, paso de ir![n][w][e]

[msg MSG_146_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2129 0 0]Puñeteros Strega... No tenemos tiempo para andar jugando al escondite.[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Será mejor que los encontremos antes de que la líen más.[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]¿Por qué no mandamos a Koromaru a rastrearlos?[n][w][e]

[msg MSG_147_0_0 [Koromaru]]
[f 2 1][bup 9 0 65535 65535 0 0][vp 3 0 65535 8008 0 0]¿Guau?[n][w][e]

[msg MSG_148_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2074 0 0]Parece que los exámenes de acceso son el 16 y el 17 de este mes.[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Seguro que Sanada y Kirijo van a bordarlos.[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Intentan disimular, pero está claro que no paran de empollar.[n][w][e]

[msg MSG_149_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2074 0 0]Es verdad, mañana tenemos el día libre por... ¿por qué era?[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Ah, cierto, es el Día de la Mayoría de Edad.[n][w][e]
[f 2 1][bup 3 3 65535 65535 0 0]Ya sabes que lo único que espero es poder llegar al menos a los 20...[n][w][e]

[msg MSG_150_0_0 [Junpei Iori]]
[f 2 1][bup 3 2 65535 65535 0 0][vp 3 0 65535 2062 0 0]¿Quién es el idiota que lidera la secta?[n][w][e]
[f 2 1][bup 3 2 65535 65535 0 0]Nosotros partiéndonos los cuernos, y nos salen estos con sus tonterías.[n][w][e]

[msg MSG_151_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6006 0 0]No puedes culpar solo a la secta.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0]La secta existe porque hay gente que está dispuesta a creer en ella.[n][w][e]

[msg MSG_152_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2062 0 0]Sí... El mundo es así, supongo.[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Lo que significa que es decisión nuestra hacer algo al respecto.[n][w][e]

[msg MSG_153_0_0 [Junpei Iori]]
[f 2 1][bup 3 2 65535 65535 0 0][vp 3 0 65535 2091 0 0]¡Joder! ¿Te puedes creer que los capullos de Strega nos la hayan liado así?[n][w][e]
[f 2 1][bup 3 2 65535 65535 0 0]Todo el tiempo hablando de la secta de mierda esa, ¿y ahora nos van a echar la culpa a nosotros?[n][w][e]
[f 2 1][bup 3 2 65535 65535 0 0]¡Se van a cagar! ¡No voy a dejar que se vayan de rositas ni aunque supliquen clemencia de rodillas![n][w][e]

[msg MSG_154_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2123 0 0]¡Más vale que los que siguen a esa secta abran los ojos![n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]¿Acaso no saben que Strega está detrás de todo...?[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]¿No tienen otra cosa que hacer que creerse las milongas de los sermones de Strega?[n][w][e]

[msg MSG_155_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2013 0 0]Sanada y Kirijo están haciendo los exámenes de acceso ahora.[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Ya mismo nos tocará a nosotros.[n][w][e]
[f 2 1][bup 3 3 65535 65535 0 0]Me duele la tripa solo de pensarlo...[n][w][e]

[msg MSG_156_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2077 0 0]La verdad es que la idea de luchar contra Nix me asusta un huevo.[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]Aunque, no sé por qué, cuando miro el dibujo de Chidori, siento que puedo con todo.[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]Dio su vida por mí, así que no dejaré que nadie me la arrebate.[n][w][e]

[msg MSG_157_0_0 [Ken Amada]]
[f 2 1][bup 8 4 65535 65535 0 0][vp 3 0 65535 7099 0 0]Ahí va, Junpei... Siempre te he tenido por un vago.[n][w][e]
[f 2 1][bup 8 1 65535 65535 0 0]Pero ahora estás casi a la par con Sanada.[n][w][e]

[msg MSG_158_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 1 65535 65535 0 0][vp 3 0 65535 3035 0 0]Ah, ¿sí? Será mejor que me ponga las pilas.[n][w][e]
[f 2 1][bup 4 1 65535 65535 0 0]A ver si podemos plantarle cara a Nix.[n][w][e]

[msg MSG_159_0_0 [Junpei Iori]]
[f 2 1][bup 3 61 65535 65535 0 0][vp 3 0 65535 2136 0 0]Snif. [nf]...[n][w][e]
[f 2 1][bup 3 61 65535 65535 0 0]Sin duda, hoy es el mejor día de toda mi vida...[n][w][e]
[f 2 1][bup 3 61 65535 65535 0 0]Snif, snif.[n][w][e]

[msg MSG_160_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2060 0 0]Es verdad, colega...[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Koromaru suele comer comida de perro y ya.[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]¡Ya es hora de que disfrute de un buen manjar![n][w][e]

[msg MSG_161_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2067 0 0]Así que una charla de orientación...[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]¿Por qué tenemos que hacer esta mierda antes de un combate? Joder, es que la cabeza no me da...[n][w][e]
[f 2 1][bup 3 3 65535 65535 0 0]¿Crees que puedo saltármelo...?[n][w][e]

[msg MSG_162_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2001 0 0]¿Ves este ramen instantáneo?[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Si me pusiera a pensar que este podría ser el último que me coma, me emocionaría. ¿Tú no?[n][w][e]

[sel SEL_163_0_0 top]
[f 2 1]Sí, yo también.[e]
[f 2 1]No, la verdad.[e]

[msg MSG_164_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2096 0 0]¿A que sí? Menudo descubrimiento. El ramen instantáneo. Y del barato.[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Así que a esto sabe la vida... A salsa de soja.[n][w][e]

[msg MSG_165_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2123 0 0]Venga ya, ¿es que no puedes apreciar las pequeñas cosas de la vida?[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]Sigue con esa actitud y no serás muy adulta cuando derrotemos a Nix.[n][w][e]

[msg MSG_165_5_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2062 0 0]Muy bien, hoy me voy a tomar mi tiempo y saborear la vida.[n][w][e]

[msg MSG_166_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2077 0 0]El mes se ha pasado volando, tú. Ya casi es la hora del enfrentamiento final...[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]¡Venga vamos, [nf]! ¡Hagamos que la recta final valga la pena![n][w][e]

[msg MSG_0131_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2002 0 0]Anda, qué curioso verte aquí.[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]¿Sabes...? Aquí es donde Chidori y yo nos conocimos.[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Estaba aquí dibujando, y decidí acercarme a ella.[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2117 0 0]Tenemos que derrotar al último jefe para mantener el sitio de Chidori a salvo.[n][w][e]

[msg MSG_167_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 52 65535 0 0][vp 3 0 65535 2088 0 0]Chidori dio la vida por mí... ¡y no pienso desperdiciarla![n][w][e]
[f 2 1][bup 3 1 52 65535 0 0]¡Le daré a Nix su merecido y viviré una vida larga y plena![n][w][e]

[msg MSG_168_0_0 [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0][vp 3 0 65535 2061 0 0]A lo mejor va siendo hora de visitarla, pero... Mmm...[n][w][e]

[msg MSG_168_1_0 [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0][vp 3 0 65535 2062 0 0]Mañana iré a visitarla sí o sí, pero...[n][w][e]
[f 2 1][bup 3 3 65535 65535 0 0]No sé qué decirle. Si tuviera algún motivo para verla...[n][w][e]

[msg MSG_168_2_0 [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0][vp 3 0 65535 2061 0 0]Me pregunto qué estará haciendo ahora Chidori...[n][w][e]
[f 2 1][bup 3 3 65535 65535 0 0]A lo mejor podría inventarme una excusa para ir al hospital. Puedo decir que he pillado un catarro o algo así...[n][w][e]

[msg MSG_168_3_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2062 0 0]En lugar de perder el tiempo preocupándome, debería ir a ver a Chidori y ya.[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Pero... siento que no es lo correcto.[n][w][e]

[msg MSG_168_4_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2062 0 0]De verdad que quiero verla,[n][w][e]
[f 2 1][bup 3 3 65535 65535 0 0]pero no puedo ir con las manos vacías, ¿no? Si al menos tuviera algo de lo que hablar con ella...[n][w][e]

[msg MSG_168_5_0 [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0][vp 3 0 65535 2077 0 0]¿Crees que se habrá olvidado de mí? Ya hace tiempo que no me paso por el hospital...[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Nah, estoy seguro de que no, pero... debería visitarla pronto.[n][w][e]

[msg MSG_168_6_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2124 0 0]El viaje escolar, eh...[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Quizás lo arreglamos si le llevo un souvenir de Kioto...[n][w][e]

[msg MSG_168_7_0 [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0][vp 3 0 65535 2061 0 0]Sé que tengo que ir a ver a Chidori y hablar las cosas...[n][w][e]
[f 2 1][bup 3 10 65535 65535 0 0]Llevo dándole vueltas muchísimo tiempo pero, por algún motivo, no reúno el valor para ir...[n][w][e]

[msg MND_169_0_0]
[f 2 1]Parece que Junpei no ha podido visitar el hospital todavía...[n][w][e]

[msg MND_169_1_0]
[f 2 1]Ahora que lo pienso, tengo la [f 4 4 0 37 1 16523] que Junpei quería.[n][w][e]
[f 2 1]¿Debería dársela?[n][w][e]

[sel SEL_386_0_0 top]
[f 2 1]Dar a Junpei[e]
[f 2 1]Reconsiderar[e]

[msg MSG_391_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 65535 65535 0 0][vp 3 0 65535 2098 0 0]Eh... ¡¿esa es...?![n][w][e]
[f 2 1][bup 3 4 65535 65535 0 0]Venga, hablemos un momento.[n][w][e]

[msg MSG_392_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0]（未使用）[n][w][e]

[msg MSG_393_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0]（未使用）[n][w][e]

[sel SEL_395_0_0 top]
[f 2 1]（未使用）[e]

[msg MSG_394_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 65535 65535 0 0]（未使用）[n][w][e]

[msg MND_398_0_0]
[f 2 1]Si pudiera darle a Junpei algo que lo animara a pasar a la acción...[n][w][e]

[msg MSG_399_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0]（未使用）[n][w][e]

[msg MSG_400_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0]（未使用）[n][w][e]

[msg MSG_401_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2009 0 0]Venga, voy a intentar hablar con Chidori.[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]No puedo cagarla ahora, de verdad. No puedo echarme atrás.[n][w][e]

