[msg MSG_000_0_0 [Padre de Maiko]]
[f 2 1][vp 1 0 0 1 0 0][f 5 21 0 10]Cuando veo este lugar, recuerdo todas las veces que he venido con Maiko.[n][w][e]
[f 2 1][vp 1 0 0 2 0 0][f 5 21 0 10]Ella también vino aquí cuando se fugó de casa.[n][w][e]

[msg MSG_000_3_0 [Padre de Maiko]]
[f 2 1][vp 1 0 0 3 0 0][f 5 21 0 10]Le encantaba el takoyaki.[n][w][e]

[msg MSG_000_5_0 [Padre de Maiko]]
[f 2 1][vp 1 0 0 4 0 0][f 5 21 0 10]Es una buena niña, ¿no crees?[n][w][e]

[sel SEL_001_0_0 top]
[f 2 1]Sí...[e]
[f 2 1]¿Lo es?[e]

[msg MSG_002_0_0 [Padre de Maiko]]
[f 2 1][vp 1 0 0 5 0 0][f 5 21 0 10]Es tan buena que a veces me pregunto si de verdad es hija mía.[n][w][e]

[msg MSG_003_0_0 [Padre de Maiko]]
[f 2 1][vp 1 0 0 6 0 0][f 5 21 0 10]Ah... ¿No os conocíais tanto? Bueno, he pensado que al menos tenía que decírtelo.[n][w][e]

[msg MSG_004_0_0 [Padre de Maiko]]
[f 2 1][vp 1 0 0 7 0 0][f 5 21 0 10]Hace poco me envió una carta.[n][w][e]
[f 2 1][vp 1 0 0 8 0 0][f 5 21 0 10]Incluye muchos detalles sobre su nueva vida.[n][w][e]

[msg MSG_004_1_0 [Padre de Maiko]]
[f 2 1][vp 1 0 0 9 0 0][f 5 21 0 10]Dice que ha hecho un montón de amigos.[n][w][e]
[f 2 1][vp 1 0 0 10 0 0][f 5 21 0 10]Veamos... Se encarga del cuidado de los conejos de su nuevo colegio y se levanta temprano para limpiar las jaulas.[n][w][e]
[f 2 1][vp 1 0 0 11 0 0][f 5 21 0 10]Le gritaron por olvidar su uniforme de Educación Física... Olvidó sus deberes y tuvo que copiar los de una amiga...[n][w][e]

[msg MSG_004_2_0 [Padre de Maiko]]
[f 2 1][vp 1 0 0 12 0 0][f 5 21 0 10]Supongo que puede ser un poco despistada. No lo sabía...[n][w][e]
[f 2 1][vp 1 0 0 13 0 0][f 5 21 0 10]Ah, hizo tan bien su examen de flauta que le pidieron que tocase delante de todo el mundo.[n][w][e]

[msg MSG_004_2_5 [Padre de Maiko]]
[f 2 1][vp 1 0 0 14 0 0][f 5 21 0 10]A continuación, dice que juega todos los días con sus amigos en el parque que hay cerca del colegio.[n][w][e]
[f 2 1][vp 1 0 0 15 0 0][f 5 21 0 10]Su madre también está bien. Se divierten mucho juntas.[n][w][e]

[msg MSG_004_3_0 [Padre de Maiko]]
[f 2 1][vp 0 0 0 16 0 0][f 5 21 0 10]...[n][w][e]
[f 2 1][vp 1 0 0 17 0 0][f 5 21 0 10]Divertirse... Tiene que estar bien.[n][w][e]
[f 2 1][vp 1 0 0 18 0 0][f 5 21 0 10]Ahora vuelvo a casa y me la encuentro vacía... Las habitaciones me parecen muy grandes sin ellas.[n][w][e]

[msg MSG_004_5_0 [Padre de Maiko]]
[f 2 1][vp 1 0 0 19 0 0]Me pregunto si a ella le pasará lo mismo al vivir en una casa sin padre.[n][w][e]
[f 2 1][vp 1 0 0 20 0 0][f 5 21 0 10]Por culpa de nuestros problemas, la niña lo ha pasado muy mal.[n][w][e]
[f 2 1][vp 1 0 0 21 0 0][f 5 21 0 10]Me siento fatal por ello.[n][w][e]

[msg MSG_004_7_0 [Padre de Maiko]]
[f 2 1][vp 1 0 0 22 0 0][f 5 21 0 10]Por cierto, ¡también tengo cuentas que saldar contigo![n][w][e]
[f 2 1][vp 1 0 0 23 0 0][f 5 21 0 10]A Maiko le debes gustar mucho, ¿eh? Me lo ha contado todo.[n][w][e]

[msg MSG_005_0_0 [Carta de Maiko]]
[f 2 1][vp 1 0 0 24 0 0]"¡Estoy deseando hacerme mayor!".[n][w][e]
[f 2 1][vp 1 0 0 25 0 0]"Por eso bebo mucha leche".[n][w][e]
[f 2 1][vp 1 0 0 26 0 0]"¡Algún día me casaré con ella!".[n][w][e]

[msg MSG_006_0_0 [Padre de Maiko]]
[f 2 1][vp 0 0 0 27 0 0]...[n][w][e]
[f 2 1][vp 0 0 0 28 0 0]......[n][w][e]
[f 2 1][vp 0 0 0 29 0 0].........[n][w][e]

[msg MSG_006_5_0 [Padre de Maiko]]
[f 2 1][vp 1 0 0 30 0 0][f 5 21 0 10]¡¿De qué va todo esto, canalla?![n][w][e]

[msg MSG_007_0_0 [Padre de Maiko]]
[f 2 1][vp 1 0 0 31 0 0][f 5 21 0 10]E-estabas aprovechándote de mi pequeña Maiko, ¿no es cierto?[n][w][e]
[f 2 1][vp 1 0 0 32 0 0][f 5 21 0 10]Tal vez no haya sido el mejor padre, p-pero sigue siendo mi hija, ¡joder![n][w][e]
[f 2 1][vp 1 0 0 33 0 0][f 5 21 0 10]¡Y no voy a dejar que alguien como tú se le acerque![n][w][e]

[msg MSG_008_0_0 [Padre de Maiko]]
[f 2 1][vp 1 0 0 34 0 0][f 5 21 0 10]¡N-nunca dejaré que te cases con ella! ¡No lo olvides![n][w][e]

