[msg MSG_SANADA_TARTAROS_0701 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0]¿Te has enterado? La próxima operación será el 7 de julio.[n][w][e]
[f 2 1][bup 4 1 65535 65535 0 0]Eso significa que va a ser un combate especial del Festival de las Estrellas.[n][w][e]

[msg MSG_FUKA_TARTAROS_0704 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0]Quizás ya lo sepas, pero la próxima luna llena caerá el martes de la semana que viene.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Estoy segura de que aparecerá algún tipo de Sombra fuerte.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Estate preparada, por favor.[n][w][e]

[msg MSG_JUNPEI_TARTAROS_0706 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0]Mañana es el día.[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Como perdamos, la ciudad será conquistada por los Perdidos, ¿eh?[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Tenemos que ganar, sí o sí...[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]Venga, vamos a la torre Tártaro esta noche. ¡Nada como apalear unas cuantas Sombras para desempolvar tus habilidades![n][w][e]

[msg MSG_JUNPEI_0706 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0]Mañana es el día.[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Como perdamos, la ciudad será conquistada por los Perdidos, ¿eh?[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Tenemos que ganar, sí o sí...[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]¿Te hace ir luego a la Tártaro? Quiero sacar algo de músculo.[n][w][e]

[msg MSG_JUNPEI_OK_0706 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0]Mañana es el día.[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Como perdamos, la ciudad será conquistada por los Perdidos, ¿eh?[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]Tenemos que ganar, sí o sí. ¡Somos los guardianes de la paz en la ciudad! Es coña...[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]En fin, hay que ponerse las pilas. Si vas hoy a la torre Tártaro, ¡cuenta conmigo![n][w][e]

[msg MSG_FUKA_0706 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5067 0 0]Ah, cierto, [nl].[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Para mañana, me gustaría que te quedaras a la espera en la residencia, por si pasa algo...[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0]Así que si tienes alguna preparación pendiente, encárgate hoy de ello, por favor.[n][w][e]

[msg MSG_YUKARI_TARTAROS_0708 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0]Perdona, tengo que hablar con Fuuka...[n][w][e]

[sel SEL_004_0_0 top]
[f 2 1]¿Todo bien?[e]
[f 2 1]¿Vamos luego a la Tártaro?[e]

[msg MSG_YUKARI_0708_RE1 [Yukari Takeba]]
[f 2 1][bup 2 10 65535 65535 0 0][vp 3 0 65535 1093 0 0]Ah, sí, em, hay una cosita que tenemos que aclarar.[n][w][e]

[msg MSG_YUKARI_0708_RE2 [Yukari Takeba]]
[f 2 1][bup 2 10 65535 65535 0 0][vp 3 0 65535 1092 0 0]Pues... Me siento un poquito cansada esta noche, así que no creo.[n][w][e]

[msg MSG_FUKA_TARTAROS_0708 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5003 0 0]Seguro que tú también te sientes un poco quemada justo después de una operación...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Yo creo que te vendría bien tomarte hoy como descanso.[n][w][e]

[msg MSG_MITSURU_STUDY_0709 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0]¿Has descansado?[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Todavía queda bastante para la siguiente luna llena, y a pesar de que me gustaría decirte que puedes relajarte...[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Los finales comienzan el lunes que viene, así que te recomiendo que cuides tu salud y te centres en los estudios.[n][w][e]

[msg MSG_YUKARII_STUDY_0710 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0]Oye, ¿estás libre esta noche?[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0]Ya que se acercan los exámenes, he pensado que los de segundo podríamos hacer una sesión de estudio...[n][w][e]

[msg MSG_JUNPEI_STUDY_0710_1 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0]Pasando. Me subo a la habitación.[n][w][e]

[msg MSG_YUKARII_STUDY_0710_0 [Yukari Takeba]]
[f 2 1][bup 2 4 65535 65535 0 0][vp 3 0 65535 1098 0 0]¿Eh? Espera- ¡Junpei![n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0]Bueno, él se lo pierde. Quedamos Fuuka, tú y yo para poder estudiar juntas.[n][w][e]

[msg MND_0718]
[f 2 1]La tienda antigua en el Centro comercial Paulownia...[n]El director me ha sugerido que le eche un vistazo...[n][w][e]
[f 2 1]Iré ahora en un momento...[n][w][e]

[msg MSG_JUNPEI_TARTAROS_0723 [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0]*suspiro* Tío, estoy reventado...[n][w][e]
[f 2 1][bup 3 3 65535 65535 0 0]Parecía que nunca íbamos a volver...[n][w][e]

[msg MSG_FUKA_TARTAROS_0723 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 3 0 65535 5143 0 0]Sí, el viaje nos ha cansado mucho.[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0]Por favor, aseguraos de descansar bien para estar listos para la próxima operación.[n][w][e]

[msg MSG_YUKARI_TARTAROS_0723 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 3 0 65535 1028 0 0]Nos quedan seis batallas, ¿verdad?[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0]Las últimas Sombras de luna llena y después todo volverá a la normalidad. Nada de Síndrome de Apatía, solo una vida sencillita y cotidiana...[n][w][e]
[f 2 1][bup 2 2 65535 65535 0 0]¡Vamos a por todas! Al fin y al cabo, nosotros somos los únicos que podemos.[n][w][e]

[msg MSG_FUKA_0724_1 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0]Por cierto, ¿qué tal te han ido los exámenes?[n][w][e]

[sel SEL_022_0_0 top]
[f 2 1]Ni tan mal.[e]
[f 2 1]Un poco un desastre...[e]

[msg MSG_FUKA_0724_RE_1 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 3 0 65535 5131 0 0]¡Qué buenas noticias! Estoy contenta por ti.[n][w][e]

[msg MSG_FUKA_0724_RE_2 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0][vp 3 0 65535 5065 0 0]Ah...[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0]Bueno, sigue siendo solo el primer semestre... Podrás remontar.[n][w][e]

[msg MSG_FUKA_0724_2 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0]Ahora que caigo, ¡he visto que Kirijo vuelve a ser la mejor de su clase![n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]¿Pero de dónde consigue sacar el tiempo? Es increíble.[n][w][e]

[msg MSG_AEGIS_0724_1 [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 3 0 65535 6001 0 0]...En dos semanas, la luna volverá a lucir llena.[n][w][e]

[msg MSG_JUNPEI_0724_1 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2061 0 0]Tía, van a volver a salir los raritos esos con Apatía- Em, digo, los Perdidos.[n][w][e]
[f 2 1][bup 3 3 65535 65535 0 0]A ver, que lo siento por las víctimas y tal, pero es que de verdad, ¡esto no tiene fin alguno![n][w][e]

[msg MSG_AEGIS_0724_2 [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 3 0 65535 6037 0 0]Técnicamente, sí tiene un fin alguno: quedan seis Sombras.[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0]Si son eliminadas, la Hora Oscura desaparecerá.[n][w][e]

[msg MSG_JUNPEI_0724_2 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2066 0 0]Ah, sí, cierto...[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Eso significa que luchar es mucho más importante que estudiar, ¿a que sí?[n][w][e]
[f 2 1][bup 3 9 65535 65535 0 0]¡Muy bien dicho, Aigis![n][w][e]

[msg MSG_AMADA_TARTAROS_0725 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0]Me llamo Ken Amada. Voy a vivir aquí durante un tiempo.[n][w][e]
[f 2 1][bup 8 0 65535 65535 0 0]Trataré de no causar molestia, así que por favor, no os preocupéis por mí.[n][w][e]

[msg MSG_AMADA_TARTAROS_0726 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0]Ahora que lo pineso, ¿has oído hablar del [clr 2]Be Blue V[clr 27]?[n][w][e]
[f 2 1][bup 8 0 65535 65535 0 0]Es una tienda en el Centro comercial Paulownia en la que, según dicen, ¡puedes hablar con espíritus![n][w][e]
[f 2 1][bup 8 3 65535 65535 0 0]Suena un poco raro, ¿no? Me pregunto qué tipo de tienda será...[n][w][e]

[msg MSG_JUNPEI_0727_1 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0]Ah, es verdad, tenías que ir al club hoy, ¿no? ¿Qué tal ha ido?[n][w][e]

[sel SEL_032_0_0 top]
[f 2 1]Iba sobrada.[e]
[f 2 1]Ha sido duro.[e]

[msg MSG_JUNPEI_0727_RE_1 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2108 0 0]Ah, ¿sí? Eres más dura de lo que pensaba.[n][w][e]

[msg MSG_JUNPEI_0727_RE_2 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2094 0 0]Bueno, tampoco te exijas demasiado, ¿vale, tía?[n][w][e]

[msg MSG_JUNPEI_TARTAROS_0727 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0]Oye, si te ves capaz, ¡vamos esta noche a la torre Tártaro![n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Ya queda menos de dos semanas para la luna llena, así que quiero volver a practicar mis movimientos.[n][w][e]

[msg MSG_JUNPEI_0727_2 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0]Oye, si te ves capaz, ¡vamos esta noche a la torre Tártaro![n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]Ya queda menos de dos semanas para la luna llena. Hay que seguir con el condicionamiento, ¿eh?[n][w][e]

[msg MSG_JUNPEI_OK_0727_2 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0]Bueno, mientras no acabes lesionada...[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Ya queda menos de dos semanas para la luna llena, así que no te nos hagas daño, ¿eh?[n][w][e]

[msg MSG_MITSURU_TARTAROS_072 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0]La Apatía vuelve a estar en aumento...[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]La gente parece estar más tranquila, a pesar de la prensa, pero van a haber problemas serios como no acabemos con esto.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Hemos de derrotar a las últimas seis Sombras, empezando por la que se anticipa durante esta luna llena.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Si el número de Perdidos continúa aumentando, la ciudad sucumbirá al caos.[n][w][e]

[msg MSG_JUNPEI_TARTAROS_0728 [Junpei Iori]]
[f 2 1][bup 3 4 65535 65535 0 0][vp 3 0 65535 2098 0 0]E-Estás exagerando, ¿verdad?[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]...Aunque no te falta razón.[n][w][e]

[msg MSG_FUKA_TARTAROS_0729 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0]El resto no han vuelto todavía...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Kirijo me dijo que llegarían sobre medianoche.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]...Igual no deberíamos ir a la torre Tártaro por hoy.[n][w][e]

[msg MSG_JUNPEI_TARTAROS_0730 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0]Una semanita hasta que sea luna llena...[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]¿Has visto cómo está la cosa en el Centro comercial Paulownia? Sí que están los Perdidos están en aumento...[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]Siento que de verdad está en nuestras manos hacer algo al respecto. ¡Así que vamos a zurrarles de lo lindo a estas Sombras![n][w][e]

[msg MSG_YUKARI_TARTAROS_0731 [Yukari Takeba]]
[f 2 1][bup 2 3 65535 65535 0 0]Oye... ¿No te parece que hay muchos más Perdidos que antes?[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0]Hoy habían bastantes en la ciudad. Mi amiga estaba muy asustada...[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0]*suspiro* Cuándo cae la luna llena, ¿la semana que viene? Lo vamos a dar todo, ¿a que sí?[n][w][e]

[msg MSG_WELCOME_YUKARI_OUT [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 3 0 65535 1019 0 0]Ah, eh... Hola.[n][w][e]

[msg MSG_WELCOME_YUKARI_OUT2 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 3 0 65535 1012 0 0]Eh... Hola...[n][w][e]

[msg MSG_WELCOME_JUNPEI_OUT [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2018 0 0]¿Qué pasa, tía?[n][w][e]

[msg MSG_WELCOME_JUNPEI_OUT2 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2012 0 0]Hola, tía...[n][w][e]

[msg MSG_WELCOME_MITSURU_OUT [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4018 0 0]Hola de nuevo.[n][w][e]

[msg MSG_WELCOME_MITSURU_OUT2 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4027 0 0]Hola de nuevo...[n][w][e]

[msg MSG_WELCOME_SANADA_OUT [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 3 0 65535 3017 0 0]Anda, has vuelto.[n][w][e]

[msg MSG_WELCOME_FUKA_OUT [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5018 0 0]Hola, ¿qué tal el día?[n][w][e]

[msg MSG_WELCOME_FUKA_OUT2 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5028 0 0]Ah... Hola...[n][w][e]

[msg MSG_WELCOME_AEGIS_OUT_RO [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 3 0 65535 6018 0 0]Saludos.[n][w][e]

[msg MSG_WELCOME_AEGIS_OUT [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6018 0 0]Saludos.[n][w][e]

[msg MSG_WELCOME_AEGIS_OUT_NA [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6017 0 0]Hola otra vez. Me alegro de volver a verte.[n][w][e]

[msg MSG_WELCOME_KOROMARU_OUT [Koromaru]]
[f 2 1][bup 9 0 65535 65535 0 0][vp 3 0 65535 8008 0 0]¡Guau![n][w][e]

[msg MSG_WELCOME_AMADA_OUT [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 3 0 65535 7020 0 0]¡Anda, hola![n][w][e]

[msg MSG_WELCOME_AMADA_OUT2 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 3 0 65535 7012 0 0]Ah... Hola...[n][w][e]

[msg MSG_WELCOME_ARAGAKI_OUT [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 3 0 65535 9014 0 0]Ey...[n][w][e]

[msg MSG_WELCOME_IKUTSUKI_OUT [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 3 0 65535 14201 0 0]Hola de nuevo.[n][w][e]

[msg MSG_WELCOME_YUKARI_IN [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 3 0 65535 1067 0 0]¡Ah, estás aquí![n][w][e]

[msg MSG_WELCOME_YUKARI_IN2 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 3 0 65535 1012 0 0]Ah, ¿ya has llegado? Perdona, no te había visto.[n][w][e]

[msg MSG_WELCOME_JUNPEI_IN [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2009 0 0]Eh, ¿qué pasa?[n][w][e]

[msg MSG_WELCOME_JUNPEI_IN2 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2012 0 0]Ah, hola...[n][w][e]

[msg MSG_WELCOME_MITSURU_IN [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4029 0 0]¿Eh? Ah, eres tú...[n][w][e]

[msg MSG_WELCOME_MITSURU_IN2 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4027 0 0]¿Mmm? Ah, ya estás aquí.[n][w][e]

[msg MSG_WELCOME_SANADA_IN [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 3 0 65535 3024 0 0]¿Has estado en tu habitación todo este tiempo?[n][w][e]

[msg MSG_WELCOME_FUKA_IN [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5067 0 0]¡Ah, hola! No sabía que ya estabas aquí.[n][w][e]

[msg MSG_WELCOME_FUKA_IN2 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5093 0 0]Anda, ¿estás aquí? Hola...[n][w][e]

[msg MSG_WELCOME_FUKA_IN_0712 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5067 0 0]Ah, [nl]...[n][w][e]

[msg MSG_WELCOME_AEGIS_IN_ROB [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 3 0 65535 6008 0 0]Buenas tardes.[n][w][e]

[msg MSG_WELCOME_AEGIS_IN [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6008 0 0]Buenas tardes.[n][w][e]

[msg MSG_WELCOME_AEGIS_IN_NAK [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6009 0 0]¿Qué tal el día? ¿Todo bien?[n][w][e]

[msg MSG_WELCOME_KOROMARU_IN [Koromaru]]
[f 2 1][bup 9 0 65535 65535 0 0][vp 3 0 65535 8001 0 0]¡Guau, guau![n][w][e]

[msg MSG_WELCOME_AMADA_IN [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 3 0 65535 7010 0 0]¿Has estudiado algo?[n][w][e]

[msg MSG_WELCOME_AMADA_IN2 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 3 0 65535 7012 0 0]¿Estabas aquí? Pues... hola.[n][w][e]

[msg MSG_WELCOME_ARAGAKI_IN [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 3 0 65535 9056 0 0]... ¿Qué hay?[n][w][e]

[msg MSG_WELCOME_IKUTSUKI_IN [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 3 0 65535 14204 0 0]Ah, no sabía que ya estabas aquí. He venido a hacer una visita rápida.[n][w][e]

[msg MND_SHYUKAKU_OK]
[f 2 1]Ahora que lo pienso, las hortalizas que planté en la azotea ya se podrán recolectar.[n][w][e]
[f 2 1]Debería ir a echarles un ojo...[n][w][e]

[msg MND_SHYUKAKU_TAIYAKI_OK]
[f 2 1]Ahora que lo pienso, las hortalizas que planté en la azotea ya se podrán recolectar.[n][w][e]
[f 2 1]Y el taiyaki que metí en la nevera también debería estar frío.[n][w][e]
[f 2 1]Debería ir a echarles un ojo...[n][w][e]

[msg MND_SHYUKAKU_TAIYAKI_OK_]
[f 2 1]Ahora que lo pienso, las hortalizas que planté en la azotea ya se podrán recolectar.[n][w][e]
[f 2 1]Y el taiyaki que metí en la nevera también debería estar frío.[n][w][e]
[f 2 1]Debería sacarlo de la nevera y dárselo a Elizabeth.[n][w][e]

[msg MND_TAIYAKI_OK]
[f 2 1]Ahora que lo pienso, el taiyaki que metí en la nevera ya debería estar frío.[n][w][e]
[f 2 1]Debería ir a por él.[n][w][e]

[msg MND_TAIYAKI_OK_QUEST]
[f 2 1]Ahora que lo pienso, el taiyaki que metí en la nevera ya debería estar frío.[n][w][e]
[f 2 1]Debería sacarlo de la nevera y dárselo a Elizabeth.[n][w][e]

[msg MSG_ERROR [Shuji Ikutsuki]]
[f 2 1]エラーメッセージです。[n][f 1 5 0]杉山まで報告ください。[n][w][e]

