[msg MSG_000_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 3 0 65535 5061 0 0]Sin duda, este sitio es idóneo.[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0]No solo es asequible, sino que sus platos están muy bien equilibrados.[n][w][e]

[msg MSG_000_5_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0]El ambiente también es muy acogedor, así que a nosotras nos resulta fácil venir y comer por nuestra cuenta.[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0]Me gusta venir aquí de vez en cuando. Tener un sitio así cerca está muy bien.[n][w][e]

[msg MSG_001_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0]Ah, bien. [nl], quería preguntarte una cosa.[n][w][e]

[msg MSG_002_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5074 0 0]¿Qué comida te gusta más, la japonesa o la occidental?[n][w][e]

[sel SEL_003_0_0 top]
[f 2 1]Cocina japonesa.[e]
[f 2 1]Comida del oeste.[e]
[f 2 1]No le hago ascos a nada.[e]

[msg MSG_004_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 3 0 65535 5131 0 0][f 5 13 3 30 6]¿En serio?[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0]Me alegra oír eso. Yo también prefiero la comida japonesa.[n][w][e]

[msg MSG_004_5_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0]Mmm... Creo que voy a empezar con arroz blanco y sopa de miso.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][f 4 23 0 6 0 25 25]Voy a intentar recrear la comida que hacen aquí.[n][w][e]

[msg MSG_004_7_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0]¡Estoy deseando empezar![n][w][e]

[msg MND_005_0_0]
[f 2 1]Fuuka parece emocionada.[n][w][e]
[f 2 1]Siento que hoy nuestra relación se ha estrechado.[n][w][e]

[msg MSG_006_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5107 0 0][f 5 13 3 15 6]Ah, ya.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Mmm... Hay muchos tipos distintos de comida occidental.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Y también tendré que acostumbrarme a cocinar con aceite vegetal.[n][w][e]

[msg MSG_006_5_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0]¡Pero tengo muchas ganas de intentarlo![n][w][e]

[msg MND_007_0_0]
[f 2 1]Fuuka parece decidida.[n][w][e]
[f 2 1]Hoy he aprendido un poco más sobre ella.[n][w][e]

[msg MSG_008_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5049 0 0]Ah, ¿en serio?[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]¿Entonces no hay nada que te guste en especial?[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0][f 4 23 0 6 3 25 25]Mmm... Me complicas un poco las cosas.[n][w][e]

[msg MND_009_0_0]
[f 2 1]Fuuka parece un tanto decepcionada...[n][w][e]
[f 2 1]Siento que hoy nuestra relación no ha cambiado nada...[n][w][e]

[msg MSG_010_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5067 0 0]Ah, será mejor que tome nota de las ideas que se me ocurren antes de que se me olviden.[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0][f 4 23 0 6 1 25 25]No me hagas caso, [nl]. Puedes seguir comiendo. Mmm, veamos...[n][w][e]

[msg MND_011_0_0]
[f 2 1]He esperado a que Fuuka terminase de escribir sus notas antes de volver a la residencia.[n][w][e]

