[msg MSG_000_0_0 [Bebe]]
[f 2 1][bup 112 1 65535 65535 0 0][vp 1 0 0 1 0 0]¡Yatta! ¡Es mi mejor pieza hasta la fecha![n][w][e]

[msg MND_001_0_0]
[f 2 1]El estudiante de intercambio que conocí[n]en la librería está ocupado cosiendo.[n][w][e]

[sel SEL_002_0_0 top]
[f 2 1]Debería saludar.[e]
[f 2 1]Es mejor dejarlo en paz.[e]

[msg MSG_003_0_0 [Bebe]]
[f 2 1][bup 112 4 65535 65535 0 0][vp 1 0 0 2 0 0]¡¿Eh?! ¡Bonjour, [nf]![n][w][e]
[f 2 1][bup 112 1 65535 65535 0 0][vp 1 0 0 3 0 0][f 4 23 0 1 1 25 25]¡No te he visto desde aquel día en la librería![n][w][e]

[msg MSG_004_0_0 [Bebe]]
[f 2 1][bup 112 2 65535 65535 0 0][vp 1 0 0 4 0 0]¡¿Quién anda ahí?! ¿Quién se atreve a irrumpir en la sagrada aula de Economía Doméstica?[n][w][e]

[msg MSG_004_3_0 [Bebe]]
[f 2 1][bup 112 1 65535 65535 0 0][vp 1 0 0 5 0 0]¡¿Eh?! ¡Bonjour, [nf]![n][w][e]

[msg MSG_005_0_0 [Bebe]]
[f 2 1][bup 112 1 65535 65535 0 0][vp 1 0 0 6 0 0]¡Has venido![n][w][e]
[f 2 1][bup 112 1 65535 65535 0 0][vp 1 0 0 7 0 0]¡Qué sorpresa tan agradable! ¡Me alegro de verte![n][w][e]

[sel SEL_006_0_0 top]
[f 2 1]¿Qué haces?[e]
[f 2 1]¿Sabes cómo me llamo?[e]

[msg MSG_007_0_0 [Bebe]]
[f 2 1][bup 112 1 65535 65535 0 0][vp 1 0 0 8 0 0]¡Estoy practicando el arte de coser![n][w][e]

[msg MSG_008_0_0 [Bebe]]
[f 2 1][bup 112 0 65535 65535 0 0][vp 1 0 0 9 0 0]Oui, le pregunté a la profe.[n][w][e]
[f 2 1][bup 112 1 65535 65535 0 0][vp 1 0 0 10 0 0][f 4 23 0 1 1 25 25]Y, por lo que sé, ¡somos del mismo curso! ¡Qué suerte![n][w][e]

[msg MSG_009_0_0 [Bebe]]
[f 2 1][bup 112 0 65535 65535 0 0][vp 1 0 0 11 0 0]Estoy en el club de moda para perfeccionar mi técnica de costura.[n][w][e]
[f 2 1][bup 112 1 65535 65535 0 0][vp 1 0 0 12 0 0][f 4 23 0 1 1 25 25]¿Te apetece unirte, [nf]? ¡Esto es tanoshii, muy divertido![n][w][e]

[msg MSG_010_0_0 [Bebe]]
[f 2 1][bup 112 0 65535 65535 0 0][vp 1 0 0 13 0 0]Si me permites la osadía, ¿te unes a mi club?[n][w][e]

[sel SEL_011_0_0 top]
[f 2 1]Claro, me uniré.[e]
[f 2 1]No, gracias.[e]

[msg MSG_012_0_0 [Bebe]]
[f 2 1][bup 112 4 65535 65535 0 0][vp 1 0 0 14 0 0]¡¿Honto?! ¿En serio?[n][w][e]

[msg MSG_013_0_0 [Bebe]]
[f 2 1][bup 112 0 65535 65535 0 0][vp 1 0 0 15 0 0]¡Pero si las actividades de club son fáciles![n][w][e]
[f 2 1][bup 112 0 65535 65535 0 0][vp 1 0 0 16 0 0]¡Puedes venir cuando te apetezca! Onegaishimasu... S'il te plaît.[n][w][e]

[msg MND_014_0_0]
[f 2 1]Bebe empieza a suplicar...[n][w][e]
[f 2 1]¿Cómo le voy a decir que no?[n]Me uniré y ya.[n][w][e]

[msg MSG_015_0_0 [Bebe]]
[f 2 1][bup 112 1 65535 65535 0 0][vp 1 0 0 17 0 0]Katajikenai, ¡muchas gracias! ¡Qué alegría contar con alguien nueva![n][w][e]
[f 2 1][bup 112 0 65535 65535 0 0][vp 1 0 0 18 0 0][f 4 23 0 1 0 25 25]Vengo aquí los [clr 2]martes, miércoles y viernes[clr 27].[n]Pero estará cerrado en época de exámenes.[n][w][e]

[msg MSG_015_3_0 [Bebe]]
[f 2 1][bup 112 3 65535 65535 0 0][vp 1 0 0 19 0 0]No he hecho buenos amigos, así que me siento muy solo. Quizá sea porque no encajo.[n][w][e]

[msg MSG_015_5_0 [Bebe]]
[f 2 1][bup 112 1 65535 65535 0 0][vp 1 0 0 20 0 0]¡Pero ahora estás aquí, [nf]! ¡El destino nos ha juntado![n][w][e]

[msg MND_016_0_0]
[f 2 1]He acabado apuntándome al club de moda.[n][w][e]
[f 2 1]He conocido a Bebe,[n]el estudiante de intercambio.[n][w][e]

[msg MSG_017_0_0 [Bebe]]
[f 2 1][bup 112 4 65535 65535 0 0][vp 1 0 0 21 0 0]¡Hala! ¡Mira qué hora es![n][w][e]

[msg MSG_017_3_0 [Bebe]]
[f 2 1][bup 112 0 65535 65535 0 0][vp 1 0 0 22 0 0]En fin, au revoir, [nf].[n][w][e]

[msg MSG_017_5_0 [Bebe]]
[f 2 1][bup 112 1 65535 65535 0 0][vp 1 0 0 23 0 0]¡Ah, por cierto![n][w][e]
[f 2 1][bup 112 0 65535 65535 0 0][vp 1 0 0 24 0 0][f 4 23 0 1 0 25 25]¿Cuál es la mejor manera de despedirse de una amiga? ¿Qué está más culturalmente aceptado?[n][w][e]

[sel SEL_018_0_0 top]
[f 2 1]Algo simple: "¡Nos vemos!".[f 2 9 1 1 611][e]
[f 2 1]Algo divertido: "¡Hasta luegui!".[f 2 9 1 1 612][e]
[f 2 1]Algo majestuoso: "Hasta la próxima".[f 2 9 1 1 613][e]
[f 2 1]Algo intenso y teatral: "¡Volveré!".[f 2 9 1 1 614][e]

[msg MSG_019_0_0 [Bebe]]
[f 2 1][bup 112 1 65535 65535 0 0][vp 1 0 0 25 0 0]¡Lo entiendo perfectamente! ¡Nos vemos![n][w][e]

[msg MSG_020_0_0 [Bebe]]
[f 2 1][bup 112 1 65535 65535 0 0][vp 1 0 0 26 0 0]¡Lo entiendo perfectamente! ¡Hasta luegui![n][w][e]

[msg MSG_021_0_0 [Bebe]]
[f 2 1][bup 112 1 65535 65535 0 0][vp 1 0 0 27 0 0]¡Lo entiendo perfectamente! ¡Hasta la próxima![n][w][e]

[msg MSG_022_0_0 [Bebe]]
[f 2 1][bup 112 1 65535 65535 0 0][vp 1 0 0 28 0 0]¡Lo entiendo perfectamente! ¡Volveré![n][w][e]

[msg MND_023_0_0]
[f 2 1]Me he despedido de Bebe[n]y he vuelto a la residencia.[n][w][e]

