[msg MND_000_0_0]
[f 2 1]Veamos qué echan en la tele.[n][w][e]

[msg MND_001_0_0]
[f 2 1]Están dando las noticias.[n][w][e]

[msg MSG_002_0_0 [Presentador de telediario]]
[f 2 1]Más noticias.[n][w][e]
[f 2 1]Han ofrecido más datos sobre los casos de apatía, que han ido en aumento.[n][w][e]
[f 2 1]La asociación de médicos cree que puede tratarse de un trastorno psicológico provocado por los cambios medioambientales, como...[n][w][e]

[msg MSG_003_0_0 [Presentador de telediario]]
[f 2 1]... se emborrachó e inició una pelea con otro cliente. La policía se lo llevó detenido.[n][w][e]
[f 2 1]A continuación, más flores primaverales.[n][w][e]
[f 2 1]La flor de hoy es el tulipán.[n][w][e]
[f 2 1]Existen muchos tipos de tulipanes, cada uno con su forma y color.[n][w][e]
[f 2 1]Se puede encontrar más información sobre los tulipanes en internet.[n][w][e]

[msg MSG_004_0_0 [Periodista]]
[f 2 1]Hola, soy Trish y os traigo un nuevo programa de "Quién es quién".[n][w][e]
[f 2 1]El sujeto de hoy es una joven de 20 años que irradia seguridad.[n][w][e]
[f 2 1]Su hermana trabaja de cámara y me han contado que obtuvo la suya de su mentor.[n][w][e]
[f 2 1]Ahora, las noticias. ¡Sana, sana, colita de rana![n][w][e]

[msg MSG_005_0_0 [Presentador de telediario]]
[f 2 1]... familias de turistas han disfrutado de una hermosa primavera.[n][w][e]
[f 2 1]La atracción seguirá en marcha hasta el 5 de mayo, el último día de las vacaciones del mes que viene.[n][w][e]

[msg MND_006_0_0 [Presentador de telediario]]

[msg MSG_007_0_0 [Presentador de telediario]]
[f 2 1]Se prevé que mañana será un gran día para divertirse. Una oportunidad fantástica para participar en eventos al aire libre.[n][w][e]
[f 2 1]A continuación, la tasa de cambio de hoy.[n][w][e]

[msg MSG_008_0_0 [Narrador]]
[f 2 1]Mañana, a la misma hora, ¡el próximo episodio de Phoenix Rangers Featherman R![n][w][e]
[f 2 1]Episodio 9: ¡Sobrevivir a la guerra del amor! ¡Búho![n][w][e]
[f 2 1]¡No os lo perdáis![n][w][e]

[msg MSG_009_0_0 [Presentador de telediario]]
[f 2 1]Vamos con las noticias de hoy.[n][w][e]

[msg MSG_010_0_0 [Presentador de telediario]]
[f 2 1]... y todavía no contamos con más información.[n][w][e]
[f 2 1]Los investigadores se enfrentan a un caso difícil, pues no hay testigos.[n][w][e]
[f 2 1]Este es el duodécimo caso de este tipo de incidente misterioso.[n][w][e]
[f 2 1]Un equipo de investigadores se esfuerza en seguir las pistas.[n][w][e]

[msg MSG_011_0_0 [Periodista]]
[f 2 1]... fue trasladado de inmediato al hospital.[n][w][e]
[f 2 1]El hombre ha recobrado la conciencia, pero debido a su estado, todavía no ha podido prestar declaración.[n][w][e]
[f 2 1]La policía espera a que se recupere para poder interrogarlo.[n][w][e]
[f 2 1]Y hasta aquí las noticias de hoy.[n][w][e]

[msg MSG_012_0_0 [Presentador de telediario]]
[f 2 1]... los clientes estaban emocionados de verla así.[n][w][e]
[f 2 1]Nuestra próxima noticia trata de la liberación de la carpa en primavera.[n][w][e]
[f 2 1]Este año se han soltado en el río más de 10 000 ejemplares.[n][w][e]
[f 2 1]La temporada de pesca de carpa comenzará en junio.[n][w][e]

[msg MSG_013_0_0 [Presentador de telediario]]
[f 2 1]... a pesar de eso, pudieron finalizar el concierto sin incidentes.[n][w][e]
[f 2 1]La próxima noticia la protagoniza un extraño animal extranjero.[n][w][e]
[f 2 1]Se llama... ornitorrinco.[n][w][e]
[f 2 1]El ornitorrinco, nativo de Australia, es un mamífero que pone huevos.[n][w][e]
[f 2 1]Y los machos tienen espolones venenosos en las patas. ¡Qué animales tan raros![n][w][e]

[msg MSG_014_0_0 [Presentador de telediario]]
[f 2 1]Mucha gente prefiere viajar al extranjero en vacaciones.[n][w][e]
[f 2 1]Se ha convertido en la primera opción vacacional este año.[n][w][e]
[f 2 1]Los aeropuertos están abarrotados...[n][w][e]
[f 2 1]Según una encuesta, Hawái vuelve a ser el destino favorito.[n][w][e]

[msg MSG_015_0_0 [Narrador]]
[f 2 1]¡En el próximo episodio de Phoenix Rangers Featherman R![n][w][e]
[f 2 1]Episodio 10: Festín de ramen instantáneo: ¡Cisne![n][w][e]

[msg MSG_016_0_0 [Presentador de telediario]]
[f 2 1]Vamos con las noticias de hoy.[n][w][e]
[f 2 1]En primer lugar, hablaremos de la gran cantidad de jóvenes que trabajan a tiempo parcial...[n][w][e]

[msg MSG_017_0_0 [Presentador de telediario]]
[f 2 1]... la tasa de cambio de hoy.[n][w][e]
[f 2 1]Los cambios en la economía han fortalecido el dólar frente al yen.[n][w][e]
[f 2 1]Actualmente, 1 dólar equivale a 115 yenes.[n][w][e]
[f 2 1]Esto indica un debilitamiento del yen del 1,4 % con respecto a ayer.[n][w][e]

[msg MSG_018_0_0 [Presentador de telediario]]
[f 2 1]... muchos esperan con impaciencia el día de mañana.[n][w][e]
[f 2 1]Debido a la Golden Week, se espera que las carreteras registren más tráfico.[n][w][e]
[f 2 1]Desde mañana hasta el 3 de mayo, circular será más complicado.[n][w][e]
[f 2 1]Se espera que las carreteras estén despejadas para el día 4.[n][w][e]
[f 2 1]De parte de todo el equipo de Noticias de acción, ¡feliz Golden Week![n][w][e]

[msg MSG_019_0_0 [Presentador de telediario]]
[f 2 1]... accidente en la intersección. Hay más de 9 kilómetros de atasco.[n][w][e]
[f 2 1]A continuación, más noticias sobre el tráfico. Parece que no hay problemas en esta sección, pero...[n][w][e]
[f 2 1]Hay embotellamiento en el carril que va en dirección contraria.[n][w][e]
[f 2 1]Se espera que la congestión desaparezca para el 4 de mayo.[n][w][e]

[msg MSG_020_0_0 [Presentador de telediario]]
[f 2 1]... los cerezos han florecido cerca del castillo de Aomori.[n][w][e]
[f 2 1]El equipo de Noticias de acción recomendamos tomar aire fresco y hacer ejercicio durante la Golden Week.[n][w][e]

[msg MSG_021_0_0 [Periodista]]
[f 2 1]... entrevistas a pie de calle. Díganos, ¿cuáles son sus planes para la Golden Week este año?[n][w][e]

[msg MSG_022_0_0 [Mochilero]]
[f 2 1]Esto... Yo, eh...[n][w][e]

[msg MSG_023_0_0 [Periodista]]
[f 2 1]P-pues esto es lo que nos cuentan a pie de calle.[n][w][e]
[f 2 1]Volvemos al estudio con más noticias...[n][w][e]

[msg MSG_024_0_0 [Presentador de telediario]]
[f 2 1]Hoy es Hachiju Hachiya.[n][w][e]
[f 2 1]Hachiju Hachiya significa la "noche 88". Marca el comienzo de la temporada del rocío tardío.[n][w][e]
[f 2 1]Por todos es sabido que en esta época del año se recogen las mejores hojas de té.[n][w][e]
[f 2 1]El cielo ha estado despejado sin rastro de niebla y el sabor del té es excelente.[n][w][e]
[f 2 1]Se han celebrado varias fiestas de té por toda la ciudad.[n][w][e]

[msg MSG_025_0_0 [Narrador]]
[f 2 1]¡En el próximo episodio de Phoenix Rangers Featherman R![n][w][e]
[f 2 1]Episodio 11: ¡Un juego peligroso! ¡Voláis demasiado, Feathermen![n][w][e]

[msg MSG_026_0_0 [Presentador de telediario]]
[f 2 1]Vamos con las noticias de hoy.[n][w][e]
[f 2 1]Hoy analizaremos la epidemia de depresión juvenil y entrevistaremos al líder de...[n][w][e]

[msg MSG_027_0_0 [Periodista]]
[f 2 1]Hola, soy Trish y os traigo un nuevo programa de "Quién es quién".[n][w][e]
[f 2 1]El sujeto de hoy es una joven de 20 años con un reluciente pelo rubio.[n][w][e]
[f 2 1]¡Dicen que su hermana era una superestrella! ¡Me pregunto cómo será tener un familiar así![n][w][e]
[f 2 1]Ahora, las noticias. ¡Sana, sana, colita de rana![n][w][e]

[msg MSG_028_0_0 [Presentador de telediario]]
[f 2 1]Hoy es el Día de los Niños.[n][w][e]
[f 2 1]El ministro de la Administración Pública ha informado del número de niños menores de quince años.[n][w][e]
[f 2 1]Según el informe, el 9,8 % de la población tiene quince años o menos.[n][w][e]
[f 2 1]Es la primera vez que la población infantil de Japón está por debajo del 10 %.[n][w][e]
[f 2 1]El envejecimiento de la población empieza a ser un problema en algunas zonas...[n][w][e]
[f 2 1]El gobierno ha pedido más datos sobre la situación y ha ordenado un estudio sobre el asunto.[n][w][e]

[msg MSG_029_0_0 [Presentador de telediario]]
[f 2 1]... virus, se han filtrado en internet los datos personales de unas 4500 personas.[n][w][e]
[f 2 1]El empleado que creó el código malicioso ya ha sido despedido...[n][w][e]
[f 2 1]Los directivos de la empresa aún no conocen el verdadero alcance de la filtración.[n][w][e]

[msg MSG_030_0_0 [Presentador de telediario]]
[f 2 1]... para los tauro, el color de la suerte es el azul.[n][w][e]
[f 2 1]Si quieren un poco de suerte extra, ¡salten y jueguen con energía![n][w][e]

[msg MSG_031_0_0 [Periodista]]
[f 2 1]Las víctimas de apatía están aumentando y no se ha encontrado la causa de la epidemia.[n][w][e]
[f 2 1]La ansiedad se extiende cerca de la isla Puerto, de donde son muchas de las víctimas.[n][w][e]
[f 2 1]Soy Kaede Kuroki, informando desde el hospital Memorial de Tatsumi.[n][w][e]

[msg MSG_032_0_0 [Presentador de telediario]]
[f 2 1]... casi descarriló cuando el monorraíl se pasó de la raya.[n][w][e]
[f 2 1]El último tren, el Anehazuru, no se detuvo en el semáforo en rojo y sobrepasó su punto de parada.[n][w][e]
[f 2 1]La policía y la dirección del monorraíl siguen investigando la causa del incidente.[n][w][e]
[f 2 1]Aunque el tren se pasó más de 600 metros de la raya, no hubo heridos.[n][w][e]
[f 2 1]La dirección del monorraíl sospecha del conductor del tren, que fue detenido y será interrogado.[n][w][e]
[f 2 1]Mientras tanto, prometen hacer todo lo posible para reducir el índice de accidentes de monorraíl.[n][w][e]
[f 2 1]Por ahora, el servicio del tren Anehazuru continuará con normalidad.[n][w][e]

[msg MSG_033_0_0 [Periodista]]
[f 2 1]... misteriosa apatía, pero las víctimas ya muestran signos de recuperación.[n][w][e]
[f 2 1]Sus familiares y amigos están muy felices de que vuelvan a la normalidad.[n][w][e]
[f 2 1]Soy Kaede Kuroki, informando desde el hospital Memorial de Tatsumi.[n][w][e]

[msg MND_034_0_0]
[f 2 1]No hay nada interesante en las noticias.[n][w][e]

[msg MSG_035_0_0 [Presentador de telediario]]
[f 2 1]... que le dejó una gasa en el estómago.[n][w][e]
[f 2 1]El hospital ha pactado más de un millón de yenes con el paciente.[n][w][e]
[f 2 1]A continuación, la previsión del tiempo de la época estival...[n][w][e]

[msg MSG_036_0_0 [Presentador de telediario]]
[f 2 1]... la tasa de cambio de hoy.[n][w][e]
[f 2 1]El dólar equivale a 114,9 yenes, un leve aumento respecto al último dato.[n][w][e]

[msg MND_037_0_0]
[f 2 1]No hay nada interesante en las noticias.[n][w][e]

[msg MSG_038_0_0 [Presentador de telediario]]
[f 2 1]... la pastelería más popular de la ciudad.[n][w][e]
[f 2 1]Es tan famosa que los cincuenta panecillos dulces, uno por cliente, se agotaron en los primeros cinco minutos.[n][w][e]

[msg MSG_039_0_0 [Narrador]]
[f 2 1]¡En el próximo episodio de Phoenix Rangers Featherman R![n][w][e]
[f 2 1]Episodio 13: ¡Laberinto de amor! Un beso de consuelo acaba en... ¡¿bofetada?![n][w][e]

[msg MSG_040_0_0 [Presentador de telediario]]
[f 2 1]Vamos con las noticias de hoy.[n][w][e]

[msg MSG_041_0_0 [Presentador de telediario]]
[f 2 1]... joven de 22 años ha sido arrestado por vender copias de un famoso juego de ordenador.[n][w][e]
[f 2 1]En la redada también se incautó el ordenador del detenido.[n][w][e]

[msg MSG_042_0_0 [Narrador]]
[f 2 1]¡En el próximo episodio de Phoenix Rangers Featherman R![n][w][e]
[f 2 1]Episodio 14: ¡Bomba de amor! A veces, la única estrategia para ganar es... ¡una vil disculpa![n][w][e]

[msg MSG_043_0_0 [Presentador de telediario]]
[f 2 1]Vamos con las noticias de hoy.[n][w][e]

[msg MSG_044_0_0 [Presentador de telediario]]
[f 2 1]... una anciana de 92 años con un pasatiempo sorprendente: los juegos en línea.[n][w][e]
[f 2 1]Cuando hablamos con ella, nos confesó que lo que más le gustaba de jugar era poder hablar con los jóvenes.[n][w][e]

[msg MSG_045_0_0 [Presentador de telediario]]
[f 2 1]... el resultado económico de abril.[n][w][e]
[f 2 1]Parece que la economía vuelve a estar en alza...[n][w][e]
[f 2 1]Aunque una leve tendencia a la inflación ha hecho que algunos clientes protesten.[n][w][e]

[msg MSG_046_0_0 [Presentador de telediario]]
[f 2 1]... su asistencia, el equipo remontó.[n][w][e]
[f 2 1]En las noticias de temporada, el sector turístico de Okinawa se prepara para otro año.[n][w][e]
[f 2 1]Aunque hace más frío este año, los turistas pasan los primeros días del verano en la isla.[n][w][e]

[msg MSG_047_0_0 [Presentador de telediario]]
[f 2 1]Anoche, un hombre de 40 años fue trasladado al hospital.[n][w][e]
[f 2 1]Según los médicos, es una víctima de apatía.[n][w][e]

[msg MSG_048_0_0 [Presentador de telediario]]
[f 2 1]... fugas de agua en las torres de refrigeración de la central nuclear.[n][w][e]
[f 2 1]Se analizó el agua y se descubrió que contenía radiación. Por suerte, no salió de la planta.[n][w][e]

[msg MSG_049_0_0 [Presentador de telediario]]
[f 2 1]... para los acuario, el color de la suerte es el rojo.[n][w][e]
[f 2 1]Para más suerte, ¡mantengan los pulgares levantados todo el día![n][w][e]

[msg MSG_050_0_0 [Narrador]]
[f 2 1]¡En el próximo episodio de Phoenix Rangers Featherman R![n][w][e]
[f 2 1]Episodio 15: ¡Combate en el instituto! ¡Canta a pleno pulmón! ¡Cisne![n][w][e]

[msg MSG_051_0_0 [Presentador de telediario]]
[f 2 1]Vamos con las noticias de hoy.[n][w][e]

[msg MSG_052_0_0 [Narrador]]
[f 2 1]Nubes oscuras cubren el cielo...[n][w][e]
[f 2 1]Para quienes están luchando, la luz aún no se ha abierto paso.[n][w][e]

[msg MSG_053_0_0 [Presentador de telediario]]
[f 2 1]Aquí concluye nuestro informe especial. A continuación, las noticias.[n][w][e]

[msg MSG_054_0_0 [Presentador de telediario]]
[f 2 1]Un escándalo hizo que las acciones de una desafortunada empresa se desplomaran hoy...[n][w][e]
[f 2 1]Al cierre del mercado, el precio de la acción había caído a 4242 yenes.[n][w][e]

[msg MSG_055_0_0 [Presentador de telediario]]
[f 2 1]... la temporada de lluvias comenzará el día 10.[n][w][e]
[f 2 1]Sin embargo, los expertos prevén que no lloverá mucho, lo que provocará escasez de agua en verano.[n][w][e]
[f 2 1]Pasemos a otra noticia...[n][w][e]
[f 2 1]Volvemos a hablar de apatía. Ya hay más de 70 casos y...[n][w][e]

[msg MSG_056_0_0 [Periodista]]
[f 2 1]Hola, soy Trish y os traigo un nuevo programa de "Quién es quién".[n][w][e]
[f 2 1]El sujeto de hoy es una chica de 20 años con un lunar cerca de la boca.[n][w][e]
[f 2 1]Dicen que es una excelente terapeuta... ¡Me gustaría pedir cita![n][w][e]
[f 2 1]Ahora, las noticias. ¡Sana, sana, colita de rana![n][w][e]

[msg MSG_057_0_0 [Presentador de telediario]]
[f 2 1]... un artículo muy popular que vuela de los estantes de las tiendas.[n][w][e]
[f 2 1]Se trata del contador Geiger para uso doméstico.[n][w][e]
[f 2 1]El miedo tras el incidente de la central nuclear ha llevado a un récord de ventas de estos dispositivos...[n][w][e]

[msg MSG_058_0_0 [Presentador de telediario]]
[f 2 1]... la tasa de cambio de hoy.[n][w][e]
[f 2 1]Un dólar equivale a 115,12 yenes, lo que supone un descenso de 0,11 yenes.[n][w][e]

[msg MSG_059_0_0 [Narrador]]
[f 2 1]¡En el próximo episodio de Phoenix Rangers Featherman R![n][w][e]
[f 2 1]Episodio 16: ¡Confusión en la prensa! ¡Una foto de comida no cuenta! ¡Halcón![n][w][e]

[msg MSG_060_0_0 [Presentador de telediario]]
[f 2 1]Vamos con las noticias de hoy.[n][w][e]

[msg MSG_061_0_0 [Narrador]]
[f 2 1]Id preparados y no olvidéis llevar paraguas en los meses de lluvia.[n][w][e]
[f 2 1]Todavía hoy se libra la batalla entre quienes llevan paraguas y el viento que arrecia...[n][w][e]

[msg MSG_062_0_0 [Presentador de telediario]]
[f 2 1]Hasta aquí nuestro informe especial.[n][w][e]
[f 2 1]A continuación, las noticias. Y después, les daremos información sobre quienes se recuperan de la apatía.[n][w][e]

[msg MND_063_0_0]
[f 2 1]No hay nada interesante en las noticias.[n][w][e]

[msg MSG_064_0_0 [Presentador de telediario]]
[f 2 1]La sonda lunar japonesa ha completado su observación de dos años hoy a las 03:25 y ha aterrizado en la luna.[n][w][e]
[f 2 1]La sonda ha investigado varios aspectos de la luna y ha contribuido en gran medida al estudio de su superficie...[n][w][e]

[msg MSG_065_0_0 [Presentador de telediario]]
[f 2 1]La temporada de lluvias se acerca, y les traemos un vídeo inusual.[n][w][e]
[f 2 1]Lo que ven es el prototipo de un generador de lluvia artificial.[n][w][e]
[f 2 1]Para un país como este, donde cada vez escasea más el agua...[n][w][e]

[msg MSG_066_0_0 [Periodista]]
[f 2 1]Hola, soy Trish y os traigo un nuevo programa de "Quién es quién".[n][w][e]
[f 2 1]El sujeto de hoy es un hombre de unos 30 años con gafas de sol y una melena hasta la espalda.[n][w][e]
[f 2 1]Cuando le pregunté a qué se dedicaba, se enfadó... ¿Por qué será?[n][w][e]
[f 2 1]Ahora, las noticias. ¡Sana, sana, colita de rana![n][w][e]

[msg MSG_067_0_0 [Narrador]]
[f 2 1]¡En el próximo episodio de Phoenix Rangers Featherman R![n][w][e]
[f 2 1]Episodio 17: ¡La sacerdotisa resucita! ¡El regreso del mal traerá tiempos difíciles![n][w][e]

[msg MSG_068_0_0 [Presentador de telediario]]
[f 2 1]Vamos con las noticias de hoy.[n][w][e]

[msg MSG_069_0_0 [Hombre del tiempo]]
[f 2 1]¡Esta semana se espera mucho sol! Solo hay un 10-20 % de probabilidad de lluvia.[n][w][e]
[f 2 1]Cuidado con la deshidratación, incluso en los meses de lluvia. ¡Va a ser como estar en el horno![n][w][e]
[f 2 1]¡Volvemos al estudio![n][w][e]

[msg MSG_070_0_0 [Presentador de telediario]]
[f 2 1]Ahora, en Noticias de acción: ¡todo lo ocurrido en deportes![n][w][e]

[msg MSG_071_0_0 [Presentador de telediario]]
[f 2 1]... implementado un nuevo sistema de control automático en coches.[n][w][e]
[f 2 1]Los expertos prevén menos derrapes en días de lluvia.[n][w][e]

[msg MSG_072_0_0 [Halcón]]
[f 2 1]¡Venid a vernos al centro comercial Paulownia! Aunque no estaremos allí.[n][w][e]

[msg MSG_073_0_0 [Narrador]]
[f 2 1]Phoenix Rangers Featherman R, ¡cada domingo! ¡No os lo perdáis![n][w][e]

[msg MSG_074_0_0 [Presentador de telediario]]
[f 2 1]Vamos con las noticias de hoy.[n][w][e]

[msg MSG_075_0_0 [Presentador de telediario]]
[f 2 1]A continuación, las noticias.[n][w][e]
[f 2 1]Ayako Yoshimoto, alumna de tercer año del Instituto Gekkoukan, ha desaparecido.[n][w][e]
[f 2 1]La policía busca pistas y ha solicitado la colaboración ciudadana.[n][w][e]

[msg MND_076_0_0]
[f 2 1]Cabe la posibilidad de que se haya adentrado en la torre Tártaro...[n][w][e]
[f 2 1]Tenemos que ir a salvarla.[n][w][e]

[msg MSG_077_0_0 [Presentador de telediario]]
[f 2 1]... festivales de la lluvia antiguos.[n][w][e]
[f 2 1]Especialmente este año, que se prevé poca lluvia, se ha organizado un festival...[n][w][e]

[msg MSG_078_0_0 [Presentador de telediario]]
[f 2 1]El tema del día es el aumento de los divorcios en parejas que se casan en junio.[n][w][e]
[f 2 1]El divorcio está a la orden del día y, a veces, se solicita justo después de la luna de miel.[n][w][e]
[f 2 1]¿Cuál es la causa? Hablaremos de ello después de estos mensajes.[n][w][e]

[msg MSG_079_0_0 [Narrador]]
[f 2 1]¡En el próximo episodio de Phoenix Rangers Featherman R![n][w][e]
[f 2 1]Episodio 18: ¡Muerte de un Cóndor! ¡Tened pañuelos a mano![n][w][e]

[msg MSG_080_0_0 [Presentador de telediario]]
[f 2 1]Vamos con las noticias de hoy.[n][w][e]

[msg MSG_081_0_0 [Presentador de telediario]]
[f 2 1]... ha sido pasto de las llamas, junto con la casa vecina.[n][w][e]
[f 2 1]La policía cree que pudo ser un incendio provocado.[n][w][e]
[f 2 1]Pasemos a otra noticia...[n][w][e]
[f 2 1]Anoche hallaron un cadáver tras la estación de la isla Puerto.[n][w][e]
[f 2 1]Parece que la víctima estudiaba en un instituto cercano.[n][w][e]
[f 2 1]La policía investiga cualquier indicio que pueda tener relación con el suceso.[n][w][e]

[msg MSG_082_0_0 [Presentador de telediario]]
[f 2 1]Una joven se quedó parada en mitad de la carretera y detuvo el tráfico durante varios minutos.[n][w][e]
[f 2 1]Finalmente, la policía se llevó a la joven, que no pareció inmutarse.[n][w][e]
[f 2 1]Ya se han dado varios casos parecidos, lo que causa problemas añadidos para la policía...[n][w][e]

[msg MSG_083_0_0 [Presentador de telediario]]
[f 2 1]Los turistas acuden al acuario para ver las liebres de mar.[n][w][e]
[f 2 1]Una advertencia: cuidado con el clima seco, ya que podría provocar insolaciones.[n][w][e]
[f 2 1]Pasamos a otra noticia sobre más personas que se quedan quietas en la calle, bloqueando el tráfico...[n][w][e]

[msg MSG_084_0_0 [Narrador]]
[f 2 1]... los organizadores de bodas se esfuerzan para que el amor sea eterno...[n][w][e]
[f 2 1]Pero los divorcios siguen aumentando.[n][w][e]
[f 2 1]Los estudios indican que una de cada cinco parejas se divorciará en el primer año de matrimonio.[n][w][e]

[msg MSG_085_0_0 [Presentador de telediario]]
[f 2 1]Aquí concluye nuestro informe especial. A continuación, las noticias.[n][w][e]

[msg MSG_086_0_0 [Presentador de telediario]]
[f 2 1]Es cierto que la moral se vuelve más laxa con la edad, pero hay quienes no soportan esta situación.[n][w][e]
[f 2 1]Los jóvenes tienen un mensaje para los adultos irresponsables.[n][w][e]

[msg MSG_087_0_0 [Chica de instituto (16)]]
[f 2 1]En lugar de decirme que deje el móvil, ¿por qué no controláis las ganas de robarle el sitio a la gente?[n][w][e]
[f 2 1]No tenéis ningún derecho a sermonearnos.[n][w][e]

[msg MSG_088_0_0 [Presentador de telediario]]
[f 2 1]Más noticias.[n][w][e]
[f 2 1]Nos informan de que Kenjiro Tsutsumi (31) y Yoshimi Miyama (24), dos oficinistas de Minato...[n][w][e]
[f 2 1]han desaparecido hace unas horas.[n][w][e]
[f 2 1]La policía busca pistas y ha solicitado la colaboración ciudadana.[n][w][e]

[msg MND_089_0_0]
[f 2 1]Cabe la posibilidad de que se hayan adentrado en la torre Tártaro...[n][w][e]
[f 2 1]Tenemos que ir a salvarlos.[n][w][e]

[msg MSG_090_0_0 [Presentador de telediario]]
[f 2 1]... más de un 50 % de probabilidades de que se seque la presa.[n][w][e]
[f 2 1]Si sigue este clima todo el verano, hablaríamos de un problema serio.[n][w][e]

[msg MSG_091_0_0 [Narrador]]
[f 2 1]¡En el próximo episodio de Phoenix Rangers Featherman R![n][w][e]
[f 2 1]Episodio 19: ¡Cree en ti! ¡No hay nada que no puedas conseguir! ¡Cisne![n][w][e]

[msg MSG_092_0_0 [Presentador de telediario]]
[f 2 1]Vamos con las noticias de hoy.[n][w][e]
[f 2 1]Las víctimas de apatía aumentan a diario por toda la ciudad...[n][w][e]

[msg MND_093_0_0]
[f 2 1]No hay nada interesante en las noticias.[n][w][e]

[msg MSG_094_0_0 [Hombre del tiempo]]
[f 2 1]De nuevo, el sol brilla bien alto en el cielo.[n][w][e]
[f 2 1]¡Llevad siempre agua encima y no os deshidratéis![n][w][e]
[f 2 1]¡Volvemos al estudio![n][w][e]

[msg MSG_095_0_0 [Presentador de telediario]]
[f 2 1]Ahora, en Noticias de acción: ¡todo lo ocurrido en deportes![n][w][e]

[msg MSG_096_0_0 [Presentador de telediario]]
[f 2 1]... todo el mundo se pregunta cuándo podrá usar el paraguas.[n][w][e]
[f 2 1]Como resultado, la venta de paraguas se ha desplomado este año.[n][w][e]
[f 2 1]En comparación con el año pasado, los vendedores han sufrido una caída del 70 % de ingresos.[n][w][e]

[msg MSG_097_0_0 [Experto en fitness]]
[f 2 1]La palabra cantonesa de hoy es "lei ho". Mueve el brazo, ¡"lei"! Sube las piernas, ¡"ho"![n][w][e]
[f 2 1]"Lei ho" significa "hola".[n][w][e]
[f 2 1]¡Eso es todo por esta semana! ¡Volvemos a las noticias![n][w][e]

[msg MSG_098_0_0 [Presentador de telediario]]
[f 2 1]... un mensaje de texto que decía "llegaré tarde" antes de desaparecer.[n][w][e]
[f 2 1]Al no volver a casa al día siguiente, sus padres, preocupados, avisaron a la policía.[n][w][e]
[f 2 1]Varios testigos aseguran haber visto a la chica con amigos por la ciudad alrededor de medianoche.[n][w][e]
[f 2 1]La investigación policial sigue en marcha.[n][w][e]

[msg MSG_099_0_0 [Presentador de telediario]]
[f 2 1]... no volver a casa, sus padres avisaron a la policía, que comenzó la búsqueda de la joven.[n][w][e]
[f 2 1]Los testigos aseguran haberla visto a medianoche con una amiga, que también ha desaparecido.[n][w][e]
[f 2 1]Esta es la sexta desaparición misteriosa en lo que va de mes.[n][w][e]
[f 2 1]La policía sigue buscando indicios relacionados con el caso...[n][w][e]

[msg MSG_100_0_0 [Narrador]]
[f 2 1]¡En el próximo episodio de Phoenix Rangers Featherman R![n][w][e]
[f 2 1]Episodio 20: ¡La vida de casados! En...[n][w][e]

[msg MSG_101_0_0 [Presentador de telediario]]
[f 2 1]Interrumpimos la programación para un anuncio importante.[n][w][e]
[f 2 1]Han encontrado a la niña de primaria desaparecida.[n][w][e]
[f 2 1]Sin embargo, su falta de expresión podría indicar que ha caído víctima de la apatía.[n][w][e]

[msg MSG_102_0_0 [Presentador de telediario]]
[f 2 1]... Tanabata o el festival de las estrellas es mañana.[n][w][e]
[f 2 1]Muchos de los deseos que se cuelgan son ruegos para que por fin acabe la apatía.[n][w][e]

[msg MSG_103_0_0 [Presentador de telediario]]
[f 2 1]Pasemos a otra noticia...[n][w][e]
[f 2 1]El hotel Champs de Fleurs ha sufrido un misterioso ataque vandálico.[n][w][e]
[f 2 1]Los espejos de las habitaciones han quedado destruidos.[n][w][e]
[f 2 1]A pesar de los muchos huéspedes del hotel, nadie vio al culpable.[n][w][e]
[f 2 1]Algunos clientes también han informado que han sufrido robos.[n][w][e]
[f 2 1]La policía investiga ahora mismo los hechos.[n][w][e]

[msg MSG_104_0_0 [Presentador de telediario]]
[f 2 1]A continuación, una buena noticia...[n][w][e]
[f 2 1]El natto se ha vuelto muy popular en el extranjero.[n][w][e]
[f 2 1]Las llaman "alubias milagrosas" y se venden cinco veces más que en Japón.[n][w][e]
[f 2 1]Según declara un famoso productor de nato: "¡Menos mal que seguí con la producción!".[n][w][e]

[msg MSG_105_0_0 [Presentador de telediario]]
[f 2 1]La próxima noticia trata de un suceso muy extraño...[n][w][e]
[f 2 1]Una flor milagrosa que solo crece una vez cada cien años ha florecido.[n][w][e]
[f 2 1]Parece responder al resto de casos extraños que ocurren en la ciudad.[n][w][e]

[msg MSG_106_0_0 [Periodista]]
[f 2 1]Hola, soy Trish y os traigo un nuevo programa de "Quién es quién".[n][w][e]
[f 2 1]El sujeto de hoy es un joven de 20 años con gorra amarilla.[n][w][e]
[f 2 1]Estudia arte en el extranjero, ¡así que tenemos mucha suerte de que esté aquí![n][w][e]
[f 2 1]Ahora, las noticias. ¡Sana, sana, colita de rana![n][w][e]

[msg MSG_107_0_0 [Narrador]]
[f 2 1]¡En el próximo episodio de Phoenix Rangers Featherman R![n][w][e]
[f 2 1]Episodio 21: ¡Monstruo de la basura al ataque! ¡Recoged, niños![n][w][e]

[msg MSG_108_0_0 [Presentador de telediario]]
[f 2 1]Vamos con las noticias de hoy.[n][w][e]

[msg MSG_109_0_0 [Presentador de telediario]]
[f 2 1]... para los cáncer, el color de la suerte es el verde.[n][w][e]
[f 2 1]Para tener más suerte, ¡pónganse los zapatos en el pie contrario![n][w][e]

[msg MSG_110_0_0 [Presentador de telediario]]
[f 2 1]Hoy se celebró una sesión de planificación de emergencia...[n][w][e]
[f 2 1]En ella se habló de los numerosos casos de apatía de los últimos meses.[n][w][e]
[f 2 1]Los antropólogos culturales investigan las causas y...[n][w][e]

[msg MSG_111_0_0 [Presentador de telediario]]
[f 2 1]... eclipse solar el día 22, el cual será el más largo de la historia.[n][w][e]
[f 2 1]Solo se podrá ver el 25 % del sol en Tokio y el 18 % en Osaka.[n][w][e]
[f 2 1]A causa del eclipse, las temperaturas descenderán ligeramente.[n][w][e]

[msg MND_112_0_0]
[f 2 1]No hay nada interesante en las noticias.[n][w][e]

[msg MSG_113_0_0 [Presentador de telediario]]
[f 2 1]... la tasa de cambio de hoy.[n][w][e]
[f 2 1]Un dólar equivale a 115,12 yenes, 0,15 yenes más que la última vez.[n][w][e]

[msg MSG_114_0_0 [Presentador de telediario]]
[f 2 1]Hoy, en noticias para los niños...[n][w][e]
[f 2 1]Ah, acabamos de recibir este boletín.[n][w][e]
[f 2 1]Se han visto más pacientes que sufren apatía.[n][w][e]
[f 2 1]Parece ser que los pacientes de meses anteriores están recayendo...[n][w][e]

[msg MSG_115_0_0 [Presentador de telediario]]
[f 2 1]Ahora, noticias del extranjero.[n][w][e]
[f 2 1]"Vida en el espacio" fue el inusual tema de un reciente desfile en Milán.[n][w][e]
[f 2 1]Los asistentes vieron a supermodelos desfilar con trajes espaciales y probaron comida galáctica.[n][w][e]

[msg MSG_116_0_0 [Narrador]]
[f 2 1]¡En el próximo episodio de Phoenix Rangers Featherman R![n][w][e]
[f 2 1]Episodio 23: ¡Un nuevo contrincante! ¡Llega Langosta ninja![n][w][e]
[f 2 1]Antes de dar paso a las noticias, ¡Cóndor tiene un mensaje que daros![n][w][e]

[msg MSG_117_0_0 [Cóndor]]
[f 2 1]¡Hola, amigos! Por ahí hay mucha gente con mala cara, pero vosotros estáis bien, ¿verdad?[n][w][e]
[f 2 1]¡Contáis conmigo para cuidaros, así que no os preocupéis! ¡Hasta la semana que viene![n][w][e]

[msg MSG_118_0_0 [Presentador de telediario]]
[f 2 1]Vamos con las noticias de hoy.[n][w][e]

[msg MSG_119_0_0 [Periodista]]
[f 2 1]Hola, soy Trish y os traigo un nuevo programa de "Quién es quién".[n][w][e]
[f 2 1]¡El sujeto de hoy es mi tipo ideal! ¡Está como un tren y tiene unos 20 años![n][w][e]
[f 2 1]Parece que quiere ser policía, como su hermano.[n][w][e]
[f 2 1]Ahora, las noticias. ¡Sana, sana, colita de rana![n][w][e]

[msg MND_120_0_0]
[f 2 1]No hay nada interesante en las noticias.[n][w][e]

[msg MSG_121_0_0 [Presentador de telediario]]
[f 2 1]Ha habido un pequeño cambio de planes: hoy hablaremos de los casos de apatía.[n][w][e]
[f 2 1]Es una misteriosa enfermedad que afecta a mentes inestables y gente con problemas psicológicos.[n][w][e]
[f 2 1]Las víctimas solo gruñen y no comen ni hablan con normalidad.[n][w][e]
[f 2 1]Los investigadores aún no saben qué la causa, pero sí sabemos que las víctimas pueden recuperarse.[n][w][e]

[msg MSG_122_0_0 [Experto en fitness]]
[f 2 1]La palabra cantonesa de hoy es "wai". Es raro, pero ¡levanta los brazos y grita "waiiii"![n][w][e]
[f 2 1]"Wai" se usa para decir "¡oye!".[n][w][e]
[f 2 1]¡Eso es todo por esta semana! ¡Volvemos a las noticias![n][w][e]

[msg MSG_123_0_0 [Presentador de telediario]]
[f 2 1]... al calor, no dejan de aumentar los casos de insolación.[n][w][e]
[f 2 1]El problema parece afectar en especial a las víctimas de apatía, ya que no se mueven...[n][w][e]

[msg MSG_124_0_0 [Hombre del tiempo]]
[f 2 1]¡Hoy hace un calor abrasador! ¡Llevamos días a más de 30 grados![n][w][e]
[f 2 1]No olvidéis llevar suficiente agua, ¡y guardad energías![n][w][e]
[f 2 1]¡Volvemos al estudio![n][w][e]

[msg MSG_125_0_0 [Presentador de telediario]]
[f 2 1]La apatía se ha cobrado más víctimas de insolaciones.[n][w][e]
[f 2 1]Si no se hubiesen encontrado a tiempo, podrían haber muerto. Tengan cuidado...[n][w][e]

[msg MSG_126_0_0 [Narrador]]
[f 2 1]¡En el próximo episodio de Phoenix Rangers Featherman R![n][w][e]
[f 2 1]Episodio 24: ¡Desfile de robots gigantes! ¡Ícaro! ¡Garuda! ¡Fusión![n][w][e]

[msg MSG_127_0_0 [Presentador de telediario]]
[f 2 1]Vamos con las noticias de hoy.[n][w][e]
[f 2 1]Más víctimas de apatía han sucumbido hoy al calor...[n][w][e]

[msg MSG_128_0_0 [Presentador de telediario]]
[f 2 1]Hoy en "Estoy de vacas", ¡conoceremos una playa famosísima![n][w][e]
[f 2 1]Quizá ya sepan de cuál hablamos: ¡el sur de Miami, en EE. UU.![n][w][e]
[f 2 1]¡Veamos qué nos cuentan![n][w][e]

[msg MSG_129_0_0 [Corresponsal internacional]]
[f 2 1]Hola y bienvenidos a Miami. ¡En esta época está lleno de turistas![n][w][e]

[msg MSG_130_0_0 [Presentador de telediario]]
[f 2 1]Vamos con las noticias de hoy.[n][w][e]
[f 2 1]Shuichi Niimura, alumno del Instituto Gekkoukan, y Yasuko Murabayashi (51), ama de casa de Minato...[n][w][e]
[f 2 1]han desaparecido hace unas horas.[n][w][e]
[f 2 1]La policía busca pistas y ha solicitado la colaboración ciudadana.[n][w][e]

[msg MND_131_0_0]
[f 2 1]Cabe la posibilidad de que se hayan adentrado en la torre Tártaro...[n][w][e]
[f 2 1]Tenemos que ir a salvarlas.[n][w][e]

[msg MSG_132_0_0 [Presentador de telediario]]
[f 2 1]... el color de la suerte de los libra es el naranja.[n][w][e]
[f 2 1]Para tener más suerte, ¡hagan que os pillen las puertas del tren![n][w][e]

[msg MSG_133_0_0 [Presentador de telediario]]
[f 2 1]... ha comenzado hoy.[n][w][e]
[f 2 1]Esta vez, el portavoz fue un estudiante de otro instituto ganador...[n][w][e]

[msg MSG_134_0_0 [Presentador de telediario]]
[f 2 1]... último Tanabata.[n][w][e]
[f 2 1]Por aquella época, la gente pedía que se recuperasen...[n][w][e]
[f 2 1]Hoy en día, el número de víctimas afectadas por la apatía ha descendido.[n][w][e]
[f 2 1]Parece que los deseos se cumplieron, aunque con retraso.[n][w][e]

[msg MSG_135_0_0 [Presentador de telediario]]
[f 2 1]... festival del Obon a la vuelta de la esquina, aumentará el tráfico.[n][w][e]
[f 2 1]Habrá embotellamiento en el tráfico en dirección sur hasta el día 15.[n][w][e]
[f 2 1]Por otro lado, las carreteras que van al norte se llenarán del 20 al 21.[n][w][e]

[msg MSG_136_0_0 [Narrador]]
[f 2 1]¡En el próximo episodio de Phoenix Rangers Featherman R![n][w][e]
[f 2 1]Episodio 25: ¡La media sonrisa de la sombra! ¡¿Ha perdido el norte tras ver la luz?![n][w][e]

[msg MSG_137_0_0 [Presentador de telediario]]
[f 2 1]Vamos con las noticias de hoy.[n][w][e]

[msg MSG_138_0_0 [Presentador de telediario]]
[f 2 1]... noticia sobre el festival.[n][w][e]
[f 2 1]El hombre que iba sobre el santuario portátil cayó al suelo.[n][w][e]
[f 2 1]No resultó herido, pero tres de los portadores que estaban debajo fueron hospitalizados.[n][w][e]
[f 2 1]El hombre ebrio dijo "¿Estáis cabreados? ¡Ahí arriba me gustaría veros!".[n][w][e]

[msg MSG_139_0_0 [Narrador]]
[f 2 1]¡En el próximo episodio de Phoenix Rangers Featherman R![n][w][e]
[f 2 1]Episodio 26: ¡Amor cavernícola! El romance no tiene límites, ¡va más allá de las eras![n][w][e]

[msg MSG_140_0_0 [Presentador de telediario]]
[f 2 1]Vamos con las noticias de hoy.[n][w][e]

[msg MSG_141_0_0 [Presentador de telediario]]
[f 2 1]En la sección del tiempo...[n][w][e]
[f 2 1]¿Es ahora Japón de clima subtropical?[n][w][e]
[f 2 1]Según los datos, esta semana también será húmeda.[n][w][e]
[f 2 1]Esto se añade a todos los desastres que suceden por todo el mundo: huracanes, tsunamis...[n][w][e]

[msg MSG_142_0_0 [Periodista]]
[f 2 1]Hola, soy Trish y os traigo un nuevo programa de "Quién es quién".[n][w][e]
[f 2 1]El sujeto de hoy es un joven de 20 años con mala cara... Digo, un oficinista muy guapo.[n][w][e]
[f 2 1]Aunque la oculta con el pelo, se ve a cicatriz que tiene en la frente. Me pregunto qué le pasó...[n][w][e]
[f 2 1]Ahora, las noticias. ¡Sana, sana, colita de rana![n][w][e]

[msg MSG_143_0_0 [Presentador de telediario]]
[f 2 1]... instituto logró su undécima victoria, la primera en cuatro años.[n][w][e]
[f 2 1]Y ahora, otro aviso de persona desaparecida.[n][w][e]
[f 2 1]Se ha denunciado la desaparición de Satsuki Onozuka (34), ama de casa de Minato.[n][w][e]
[f 2 1]La policía busca pistas y ha solicitado la colaboración ciudadana.[n][w][e]

[msg MND_144_0_0]
[f 2 1]Cabe la posibilidad de que se haya adentrado en la torre Tártaro...[n][w][e]
[f 2 1]Tenemos que ir a salvarla.[n][w][e]

[msg MND_145_0_0]
[f 2 1]Parece que hay un especial sobre el juego que anunciaron hoy...[n][w][e]

[msg MSG_146_0_0 [Presentador de telediario]]

[msg MND_147_0_0]
[f 2 1]No hay nada interesante en las noticias.[n][w][e]

[msg MND_148_0_0]
[f 2 1]No hay nada interesante en las noticias.[n][w][e]

[msg MSG_149_0_0 [Narrador]]
[f 2 1]¡En el próximo episodio de Phoenix Rangers Featherman R![n][w][e]
[f 2 1]Episodio 27: ¡Se abren las puertas del infierno! ¡Golondrina, Cóndor, Búho![n][w][e]

[msg MSG_150_0_0 [Presentador de telediario]]
[f 2 1]Vamos con las noticias de hoy.[n][w][e]

[msg MSG_151_0_0 [Crítica]]
[f 2 1]¡La gente está muriendo con este calor![n][w][e]
[f 2 1]No se pueden decir barbaridades como que hay que dejar que se recuperen...[n][w][e]

[msg MSG_152_0_0 [Doctor]]
[f 2 1]Hacemos todo lo posible para ocuparnos de la apatía, pero ahora mismo solo podemos...[n][w][e]

[msg MSG_153_0_0 [Crítica]]
[f 2 1]¡Solo sabe decir eso![n][w][e]

[msg MSG_154_0_0 [Presentador]]
[f 2 1]¡Uf! El ambiente está tan caldeado como fuera. Pero nos hemos quedado sin tiempo por hoy.[n][w][e]
[f 2 1]A continuación, las noticias.[n][w][e]

[msg MND_155_0_0]
[f 2 1]No hay nada interesante en las noticias.[n][w][e]

[msg MND_156_0_0]
[f 2 1]No hay nada interesante en las noticias.[n][w][e]

[msg MSG_157_0_0 [Presentador de telediario]]
[f 2 1]... página web del tiempo colapsó tras el aluvión de visitas.[n][w][e]
[f 2 1]Es posible que se debiera a que los estudiantes estaban planeando sus vacaciones de verano...[n][w][e]

[msg MSG_158_0_0 [Presentador de telediario]]
[f 2 1]Pasemos a otra noticia...[n][w][e]
[f 2 1]Han vuelto los niños de primaria que viajaron por Japón en bicicleta.[n][w][e]
[f 2 1]Están broceados y felices, y sus familias se alegran mucho de tenerlos de vuelta.[n][w][e]

[msg MSG_159_0_0 [Presentador de telediario]]
[f 2 1]Las entradas del último concierto de un famoso grupo se agotaron...[n][w][e]
[f 2 1]Pero, el día del espectáculo, el público no mostró emoción alguna.[n][w][e]
[f 2 1]Al parecer, la mayoría de los que tenían entrada sufrían apatía...[n][w][e]

[msg MND_160_0_0]
[f 2 1]La noticia sigue...[n][w][e]

[msg MSG_161_0_0 [Presentador de telediario]]
[f 2 1]Y ahora, otro aviso de persona desaparecida.[n][w][e]
[f 2 1]Se ha denunciado la desaparición de Hirotaka Tanigami (25), un oficinista de Minato.[n][w][e]
[f 2 1]La policía busca pistas y ha solicitado la colaboración ciudadana.[n][w][e]

[msg MND_162_0_0]
[f 2 1]Cabe la posibilidad de que se haya adentrado en la torre Tártaro...[n][w][e]
[f 2 1]Tenemos que ir a salvarlo.[n][w][e]

[msg MSG_163_0_0 [Narrador]]
[f 2 1]¡En el próximo episodio de Phoenix Rangers Featherman R![n][w][e]
[f 2 1]Episodio 28: ¡Bestia dimensional! ¿El enemigo es... mono?[n][w][e]

[msg MSG_164_0_0 [Presentador de telediario]]
[f 2 1]Vamos con las noticias de hoy.[n][w][e]
[f 2 1]La apatía cada vez se extiende más y más...[n][w][e]

[msg MSG_165_0_0 [Presentador de telediario]]
[f 2 1]Por fin es 31 de agosto.[n][w][e]
[f 2 1]Mañana comienza el nuevo curso y los niños regresarán al colegio. Para evitar caras largas, proponemos...[n][w][e]

[msg MSG_166_0_0 [Presentador de telediario]]
[f 2 1]Hoy hablaremos sobre el problema ético de la libertad de expresión.[n][w][e]
[f 2 1]Un importante periódico publicó la foto de una víctima de apatía sin ocultar su identidad y...[n][w][e]

[msg MSG_167_0_0 [Presentador de telediario]]
[f 2 1]... el canal de cocina os mostrará otra popular comida.[n][w][e]
[f 2 1]El año pasado fue un consomé. ¿Cuál será la de este año?[n][w][e]
[f 2 1]Tras estos mensajes, el reportaje especial de hoy será sobre las víctimas de apatía...[n][w][e]

[msg MSG_168_0_0 [Experto en fitness]]
[f 2 1]La palabra cantonesa de hoy es "houshonah". ¡Estírate y di "houshonah"![n][w][e]
[f 2 1]"Houshonah" significa "duro". ¡Es muy duro cuando alguien que te gusta te dice "houshonah"![n][w][e]
[f 2 1]¡Eso es todo por esta semana! ¡Volvemos a las noticias![n][w][e]
[f 2 1]¡No dejes que la apatía ni el calor te depriman! ¡Hasta la próxima![n][w][e]

[msg MSG_169_0_0 [Presentador de telediario]]
[f 2 1]Vamos con las noticias de hoy. Empezamos con otro aviso de persona desaparecida.[n][w][e]
[f 2 1]Se ha denunciado la desaparición de Reiko Makita (33), una oficinista de Minato.[n][w][e]
[f 2 1]La policía busca pistas y ha solicitado la colaboración ciudadana.[n][w][e]

[msg MND_170_0_0]
[f 2 1]Cabe la posibilidad de que se haya adentrado en la torre Tártaro...[n][w][e]
[f 2 1]Tenemos que ir a salvarla.[n][w][e]

[msg MSG_171_0_0 [Presentador de telediario]]
[f 2 1]... convención internacional presentó una nueva tecnología: NewClear.[n][w][e]
[f 2 1]El proceso es tan asombroso que han empezado a llamarla "Nuclear".[n][w][e]
[f 2 1]En el reportaje especial de hoy, investigaremos qué es esto de NewClear.[n][w][e]

[msg MSG_172_0_0 [Narrador]]
[f 2 1]¡En el próximo episodio de Phoenix Rangers Featherman R![n][w][e]
[f 2 1]Episodio 29: ¡La batalla final! ¡¿Una pelea ha dejado a Halcón fuera de combate?![n][w][e]

[msg MSG_173_0_0 [Presentador de telediario]]
[f 2 1]Vamos con las noticias de hoy.[n][w][e]
[f 2 1]La última víctima es el quinto caso de apatía en lo que va de mes...[n][w][e]

[msg MND_174_0_0]
[f 2 1]No hay nada interesante en las noticias.[n][w][e]

[msg MSG_175_0_0 [Presentador de telediario]]
[f 2 1]... planes para ir de excursión a recoger setas matsutake.[n][w][e]
[f 2 1]Las reservas turísticas se están disparando y...[n][w][e]

[msg MND_176_0_0]
[f 2 1]No hay nada interesante en las noticias.[n][w][e]

[msg MSG_177_0_0 [Presentador de telediario]]
[f 2 1]... el color de la suerte para los virgo es el amarillo.[n][w][e]
[f 2 1]Para tener más suerte hoy, ¡peguen tres puñetazos delante del espejo![n][w][e]

[msg MND_178_0_0]
[f 2 1]No hay nada interesante en las noticias.[n][w][e]

[msg MSG_179_0_0 [Presentador de telediario]]
[f 2 1]... la tasa de cambio de hoy.[n][w][e]
[f 2 1]Un dólar equivale a 115,23 yenes, un 0,11 % más que la última vez.[n][w][e]
[f 2 1]A continuación, otra noticia sobre una persona desaparecida.[n][w][e]
[f 2 1]Se ha denunciado la desaparición de Bunkichi Kitamura (80), propietario de una tienda de libros usados en Minato.[n][w][e]
[f 2 1]La policía busca pistas y ha solicitado la colaboración ciudadana.[n][w][e]

[msg MND_180_0_0]
[f 2 1]Cabe la posibilidad de que se haya adentrado en la torre Tártaro...[n][w][e]
[f 2 1]Tenemos que ir a salvarlo.[n][w][e]

[msg MSG_181_0_0 [Narrador]]
[f 2 1]¡En el próximo episodio de Phoenix Rangers Featherman R![n][w][e]
[f 2 1]Episodio 30: ¡Despiertan tres demonios! ¡Dejad a mi amante![n][w][e]

[msg MSG_182_0_0 [Presentador de telediario]]
[f 2 1]Vamos con las noticias de hoy.[n][w][e]

[msg MSG_183_0_0 [Periodista]]
[f 2 1]¡Enhorabuenaaa![n][w][e]
[f 2 1]¡Estamos en el vestuario entrevistando a los ganadores! ¡Lo habéis hecho genial![n][w][e]
[f 2 1]¡Caray! ¡Q-qué fría está la cerveza![n][w][e]

[msg MND_184_0_0]
[f 2 1]No hay nada interesante en las noticias.[n][w][e]

[msg MND_185_0_0]
[f 2 1]No hay nada interesante en las noticias.[n][w][e]

[msg MSG_186_0_0 [Experto en fitness]]
[f 2 1]La palabra cantonesa de hoy es "kehhei". ¡Flexiona los dedos y... "kehhei"![n][w][e]
[f 2 1]"Kehhei" significa "qué cabreo". ¡Un tren lleno de gente te pone "kehhei"![n][w][e]
[f 2 1]¡Eso es todo por esta semana! ¡Volvemos a las noticias![n][w][e]

[msg MSG_187_0_0 [Presentador de telediario]]
[f 2 1]... se acerca un enorme tifón. Ahora mismo está azotando el continente.[n][w][e]
[f 2 1]Según las condiciones meteorológicas, podría pasar sobre Japón esta noche.[n][w][e]

[msg MSG_188_0_0 [Periodista]]
[f 2 1]Hola, soy Trish y os traigo un nuevo programa de "Quién es quién".[n][w][e]
[f 2 1]Hoy tenemos a una chica de unos 20 años con un original corte de pelo.[n][w][e]
[f 2 1]Estudió en el extranjero, habla inglés a la perfección ¡y es tan guapa como inteligente![n][w][e]
[f 2 1]Ahora, las noticias. ¡Sana, sana, colita de rana![n][w][e]

[msg MSG_189_0_0 [Presentador de telediario]]
[f 2 1]El cielo vuelve a estar azul y despejado.[n][w][e]
[f 2 1]Todo el que tenga la ropa tendida al sol puede estar tranquilo: por la tarde estará seca.[n][w][e]
[f 2 1]A continuación, otra noticia sobre una persona desaparecida.[n][w][e]
[f 2 1]Aki Kurobe, alumna de tercero del Instituto Gekkoukan, y Yasunobu Shimozono (44), el presidente de una compañía de Minato...[n][w][e]
[f 2 1]han desaparecido hace unas horas.[n][w][e]
[f 2 1]La policía busca pistas y ha solicitado la colaboración ciudadana.[n][w][e]

[msg MND_190_0_0]
[f 2 1]Cabe la posibilidad de que se hayan adentrado en la torre Tártaro...[n][w][e]
[f 2 1]Tenemos que ir a salvarlos.[n][w][e]

[msg MSG_191_0_0 [Presentador de telediario]]
[f 2 1]... antropólogos culturales han hecho un anuncio relacionado con la apatía.[n][w][e]
[f 2 1]Han calculado cuándo se recuperarán las víctimas y cuándo se cobrará otras nuevas...[n][w][e]
[f 2 1]La gente espera escuchar el día exacto en que aumentarán las víctimas el mes que viene...[n][w][e]

[msg MSG_192_0_0 [Presentador de telediario]]
[f 2 1]... hombre muerto tenía lazos con usureros de la zona.[n][w][e]
[f 2 1]La policía afirma que todo apunta a que conocía a su asaltante, ya que no hay signos de forcejeo.[n][w][e]
[f 2 1]Es muy posible que la víctima sufriera de apatía, lo que le impidió defenderse.[n][w][e]

[msg MSG_193_0_0 [Presentador de telediario]]
[f 2 1]... acalorado intercambio ayer en un videoclub debido al recargo por demora.[n][w][e]
[f 2 1]El cliente insistía en que tenía apatía, lo que le impidió devolver las películas en la fecha indicada...[n][w][e]
[f 2 1]Pero el dueño no cedía y afirmaba que su política no contemplaba ninguna excusa.[n][w][e]
[f 2 1]A pesar de la frustración del cliente, la disputa tuvo un final satisfactorio para ambos cuando...[n][w][e]

[msg MSG_194_0_0 [Presentador de telediario]]
[f 2 1]La apatía está aún más extendida que nunca.[n][w][e]
[f 2 1]El personal sanitario no da crédito a la cantidad de nuevas víctimas que están ingresando en los hospitales...[n][w][e]

[msg MSG_195_0_0 [Narrador]]
[f 2 1]¡En el próximo episodio de Phoenix Rangers Featherman R![n][w][e]
[f 2 1]Episodio 32: ¡El retorno del ala! ¡Los demonios no quieren irse![n][w][e]

[msg MSG_196_0_0 [Presentador de telediario]]
[f 2 1]Vamos con las noticias de hoy.[n][w][e]
[f 2 1]La expansión de la apatía no parece que vaya a detenerse...[n][w][e]

[msg MSG_197_0_0 [Presentador de telediario]]
[f 2 1]Aunque se sabe que la apatía no es contagiosa...[n][w][e]
[f 2 1]Si ve alguna víctima, no se acerque. Mejor llame a la policía o al hospital...[n][w][e]

[msg MSG_198_0_0 [Celebridad]]
[f 2 1]La apatía no es una enfermedad... Las víctimas son como nosotros; solo están más cansadas.[n][w][e]
[f 2 1]Llama al número que aparece en pantalla y haz gala de tu bondad...[n][w][e]

[msg MND_199_0_0]
[f 2 1]En la tele se puede ver el dinero recaudado hasta ahora para la apatía en el telemaratón de personas famosas.[n][w][e]

[msg MSG_200_0_0 [Presentador de telediario]]
[f 2 1]A continuación, las noticias.[n][w][e]

[msg MSG_201_0_0 [Presentador de telediario]]
[f 2 1]Los antropólogos culturales han obtenido más información sobre la apatía...[n][w][e]
[f 2 1]Según ellos, las víctimas necesitan unas dos semanas para recuperarse.[n][w][e]
[f 2 1]Si tienen razón, las víctimas actuales comenzarán a recuperarse el día 5 del mes que viene...[n][w][e]

[msg MSG_202_0_0 [Experto en fitness]]
[f 2 1]La palabra cantonesa de hoy es "toche". ¡Inclínate y di "toche"![n][w][e]
[f 2 1]"Toche" significa "gracias". ¡Espero que algún día se ponga de moda![n][w][e]
[f 2 1]¡Eso es todo por esta semana! ¡Volvemos a las noticias![n][w][e]

[msg MSG_203_0_0 [Presentador de telediario]]
[f 2 1]A continuación, las noticias.[n][w][e]
[f 2 1]El tema del día es la apatía...[n][w][e]

[msg MSG_204_0_0 [Periodista]]
[f 2 1]Hola, soy Trish y os traigo un nuevo programa de "Quién es quién".[n][w][e]
[f 2 1]El sujeto de hoy es un joven de 20 años que se jacta de su increíble intelecto.[n][w][e]
[f 2 1]Se le puede reconocer por el diseño de "#1" que lleva siempre en la ropa.[n][w][e]
[f 2 1]Pasamos a las noticias. ¡Apatía, vete y no vuelvas![n][w][e]

[msg MSG_205_0_0 [Presentador de telediario]]
[f 2 1]En cuanto a la actualidad económica...[n][w][e]
[f 2 1]El creciente número de víctimas de apatía ha provocado el declive de la economía japonesa y...[n][w][e]

[msg MSG_206_0_0 [Presentador de telediario]]
[f 2 1]... han atacado a un estudiante en la estación de la isla Puerto y el joven ha fallecido.[n][w][e]
[f 2 1]Aunque apenas asistía al instituto, iba a menudo a la escena del crimen.[n][w][e]
[f 2 1]La policía cree que el incidente se debió a una disputa y está interrogando a los jóvenes de la zona.[n][w][e]

[msg MSG_207_0_0 [Presentador de telediario]]
[f 2 1]Todo el mundo está pendiente de los antropólogos que predijeron la recuperación de las víctimas de apatía.[n][w][e]
[f 2 1]De momento, todas sus hipótesis han sido acertadas...[n][w][e]
[f 2 1]Muchos se alegran de tener al fin información precisa sobre la apatía.[n][w][e]
[f 2 1]Ahora, uno de los antropólogos está intentando determinar cuándo aparecerán más víctimas.[n][w][e]

[msg MND_208_0_0]
[f 2 1]No hay nada interesante en las noticias.[n][w][e]

[msg MSG_209_0_0 [Presentador de telediario]]
[f 2 1]... la tasa de cambio de hoy.[n][w][e]
[f 2 1]Según la tasa actual, un dólar son 114,30 yenes. El yen ha caído un 0,22 % desde la última vez.[n][w][e]

[msg MND_210_0_0]
[f 2 1]No hay nada interesante en las noticias.[n][w][e]

[msg MSG_211_0_0 [Narrador]]
[f 2 1]... huesos e intestinos frágiles. El riesgo es mayor para aquellos que no hacen deporte.[n][w][e]
[f 2 1]Cada vez hay más niños que no hacen el ejercicio que necesitan.[n][w][e]
[f 2 1]Así concluye nuestro informe especial del Día del Deporte y la Salud.[n][w][e]

[msg MSG_212_0_0 [Presentador de telediario]]
[f 2 1]A continuación, las noticias.[n][w][e]

[msg MSG_213_0_0 [Narrador]]
[f 2 1]¡En el próximo episodio de Phoenix Rangers Featherman R![n][w][e]
[f 2 1]Episodio 34: ¡Halcón ha dormido demasiado! Hay que despertarlo con la técnica definitiva: ¡Ciclón superconductor![n][w][e]

[msg MSG_214_0_0 [Presentador de telediario]]
[f 2 1]Vamos con las noticias de hoy.[n][w][e]

[msg MSG_215_0_0 [Presentador de telediario]]
[f 2 1]... el color de la suerte para los sagitario es el rosa.[n][w][e]
[f 2 1]Para tener más suerte, ¡pongan una flor en la puerta![n][w][e]

[msg MSG_216_0_0 [Presentador de telediario]]
[f 2 1]Los antropólogos culturales han calculado otra fecha.[n][w][e]
[f 2 1]Dicen que, en una semana, comenzarán a aparecer nuevas víctimas de apatía.[n][w][e]

[msg MSG_217_0_0 [Narrador]]
[f 2 1]¡En el próximo episodio de Phoenix Rangers Featherman R![n][w][e]
[f 2 1]Episodio 35: ¡Amor de paloma migratoria! ¡Lucha por tu amor, Golondrina![n][w][e]

[msg MSG_218_0_0 [Presentador de telediario]]
[f 2 1]Vamos con las noticias de hoy.[n][w][e]

[msg MND_219_0_0]
[f 2 1]No hay nada interesante en las noticias.[n][w][e]

[msg MSG_220_0_0 [Presentador de telediario]]
[f 2 1]Hoy en día los casinos son un destino muy turístico, pero...[n][w][e]
[f 2 1]Para ver un casino de verdad, ¡hay que ir a Las Vegas, en EE. UU.![n][w][e]
[f 2 1]Contactamos con nuestro corresponsal, que se encuentra en el Strip. ¡Hola![n][w][e]

[msg MSG_221_0_0 [Corresponsal internacional]]
[f 2 1]Hola y bienvenidos a Las Vegas, ¡la capital mundial de las apuestas![n][w][e]

[msg MSG_222_0_0 [Presentador de telediario]]
[f 2 1]El aumento de víctimas de apatía de anoche alcanzó el número previsto.[n][w][e]
[f 2 1]Se equivocó por un par de días, pero la predicción del antropólogo se cumplió de nuevo.[n][w][e]
[f 2 1]Ha comunicado su intención de continuar con la investigación de...[n][w][e]

[msg MND_223_0_0]
[f 2 1]La noticia sigue...[n][w][e]

[msg MSG_224_0_0 [Presentador de telediario]]
[f 2 1]Y ahora, otro aviso de persona desaparecida.[n][w][e]
[f 2 1]El universitario Ryohei Nakatsugawa (19), junto con Maiko Ohashi, hija del oficinista Takahiro Ohashi (36).[n][w][e]
[f 2 1]... han desaparecido prácticamente al mismo tiempo.[n][w][e]
[f 2 1]La policía busca pistas y ha solicitado la colaboración ciudadana.[n][w][e]

[msg MND_225_0_0]
[f 2 1]Cabe la posibilidad de que se hayan adentrado en la torre Tártaro...[n][w][e]
[f 2 1]Tenemos que ir a salvarlos.[n][w][e]

[msg MSG_226_0_0 [Periodista]]
[f 2 1]... centro comercial de Iwatodai está infestado de víctimas de apatía.[n][w][e]
[f 2 1]A continuación, las noticias.[n][w][e]

[msg MSG_227_0_0 [Presentador de telediario]]
[f 2 1]Pedimos disculpas por haber dicho que el centro comercial está infestado de víctimas de apatía.[n][w][e]
[f 2 1]Tras el elevado número de quejas de nuestros espectadores, el responsable ha sido suspendido.[n][w][e]

[msg MND_228_0_0]
[f 2 1]En todos los canales hay noticias relacionadas con la apatía...[n][w][e]

[msg MSG_229_0_0 [Narrador]]
[f 2 1]¡En el próximo episodio de Phoenix Rangers Featherman R![n][w][e]
[f 2 1]Episodio 36: ¡Hombre hormiga, el apetito con patas! ¡¿Halcón miró a hurtadillas en el baño de señoras?![n][w][e]

[msg MSG_230_0_0 [Presentador de telediario]]
[f 2 1]Vamos con las noticias de hoy.[n][w][e]
[f 2 1]El avance de la apatía no cesa y empieza a cundir el pánico...[n][w][e]

[msg MSG_231_0_0 [Presentador de telediario]]
[f 2 1]... cómico ha hecho una sorprendente observación en una revista de deportes.[n][w][e]
[f 2 1]Su declaración de que Nostradamus predijo la apatía ha calado en la mente de muchas personas...[n][w][e]

[msg MSG_232_0_0 [Presentador de telediario]]
[f 2 1]Los antropólogos culturales han dado más información.[n][w][e]
[f 2 1]Uno de ellos ha deducido con exactitud las fechas de recuperación y recaída hasta ahora...[n][w][e]
[f 2 1]Cree que la próxima ola de recuperación comenzará el día 7.[n][w][e]

[msg MND_233_0_0]
[f 2 1]En todos los canales hay noticias relacionadas con la apatía...[n][w][e]

[msg MSG_234_0_0 [Experto en fitness]]
[f 2 1]La palabra cantonesa de hoy es "kaumena". ¡Gira la cabeza a ambos lados y di "kaumena"![n][w][e]
[f 2 1]"Kaumena" significa "ayuda". Yo hasta digo "kaumena" para las víctimas de apatía.[n][w][e]
[f 2 1]¡Eso es todo por esta semana! ¡Volvemos a las noticias![n][w][e]

[msg MSG_235_0_0 [Presentador de telediario]]
[f 2 1]Aunque los antropólogos han determinado las fechas exactas de enfermedad y recuperación...[n][w][e]
[f 2 1]La gente sigue preocupada porque todavía no se conocen las causas de la apatía.[n][w][e]

[msg MND_236_0_0]
[f 2 1]La noticia sigue...[n][w][e]

[msg MSG_237_0_0 [Presentador de telediario]]
[f 2 1]Y ahora, otro aviso de persona desaparecida.[n][w][e]
[f 2 1]Takeko Hiraoka (38), ama de casa, ha desaparecido hace unas horas.[n][w][e]
[f 2 1]La policía busca pistas y ha solicitado la colaboración ciudadana.[n][w][e]

[msg MND_238_0_0]
[f 2 1]Cabe la posibilidad de que se haya adentrado en la torre Tártaro...[n][w][e]
[f 2 1]Tenemos que ir a salvarla.[n][w][e]

[msg MSG_239_0_0 [Presentador de telediario]]
[f 2 1]... otoño, las luces son preciosas.[n][w][e]
[f 2 1]Especialmente en el puente Moonlight de Minato...[n][w][e]

[msg MSG_240_0_0 [Narrador]]
[f 2 1]¡En el próximo episodio de Phoenix Rangers Featherman R![n][w][e]
[f 2 1]Episodio 37: ¡Aquí llega el emperador! ¡¿Quién sería capaz de comer más que Búho y amar más que Cóndor?![n][w][e]

[msg MSG_241_0_0 [Presentador de telediario]]
[f 2 1]Vamos con las noticias de hoy.[n][w][e]
[f 2 1]La última consola portátil ha salido hoy a la venta. ¡Se han formado colas kilométricas en todo el país![n][w][e]

[msg MSG_242_0_0 [Presentador de telediario]]
[f 2 1]... para los leo, el color de la suerte es el marrón.[n][w][e]
[f 2 1]Para tener todavía más suerte, ¡quiten el marcapáginas de un libro que estén leyendo![n][w][e]

[msg MSG_243_0_0 [Presentador de telediario]]
[f 2 1]Esta mañana, han comenzado a curarse las víctimas de la última ronda de apatía.[n][w][e]
[f 2 1]Parece que los antropólogos han vuelto a dar en el blanco.[n][w][e]
[f 2 1]Uno de ellos dice que la apatía resurgirá el día 20.[n][w][e]
[f 2 1]Instamos a nuestros espectadores a que tengan cuidado en esas fechas y...[n][w][e]

[msg MSG_244_0_0 [Presentador de telediario]]
[f 2 1]... estupefacto por la repentina muerte del presidente del Grupo Kirijo.[n][w][e]
[f 2 1]Debido a este suceso, se ha convocado una reunión de emergencia...[n][w][e]

[msg MSG_245_0_0 [Presentador de telediario]]
[f 2 1]... última hora.[n][w][e]
[f 2 1]La apatía se ha extendido todavía más en estos últimos dos días.[n][w][e]
[f 2 1]Todo el mundo está decepcionado, ya que se anunció que comenzaría a disminuir sobre el 20...[n][w][e]

[msg MND_246_0_0]
[f 2 1]En todos los canales hay noticias relacionadas con la apatía...[n][w][e]

[msg MSG_247_0_0 [Narrador]]
[f 2 1]¡En el próximo episodio de Phoenix Rangers Featherman R![n][w][e]
[f 2 1]Episodio 38: ¡Emboscada! Espectadores..., ¡tratad bien a vuestros amigos![n][w][e]

[msg MSG_248_0_0 [Presentador de telediario]]
[f 2 1]Vamos con las noticias de hoy.[n][w][e]
[f 2 1]Debido al repentino aumento de víctimas de apatía, el hospital se ha visto colapsado...[n][w][e]

[msg MSG_249_0_0 [Presentador de telediario]]
[f 2 1]... preguntas para el antropólogo cultural.[n][w][e]
[f 2 1]Según su hipótesis, la actual ola de apatía debería haber terminado el día 20.[n][w][e]
[f 2 1]Sin embargo, debido al incesante avance de la apatía, su confianza ha ido...[n][w][e]

[msg MND_250_0_0]
[f 2 1]En todos los canales hay noticias relacionadas con la apatía...[n][w][e]

[msg MSG_251_0_0 [Presentador de telediario]]
[f 2 1]... médicos hacen turnos interminables debido al número de pacientes.[n][w][e]
[f 2 1]La situación es cada vez peor, y algunos médicos también caen víctimas de la apatía...[n][w][e]

[msg MSG_252_0_0 [Experto en fitness]]
[f 2 1]La palabra cantonesa de hoy es "chinyan". ¡Haz un corazón con los dedos y di "chinyan!"[n][w][e]
[f 2 1]"Chinyan" significa "apasionado". Si pillas la apatía, dejarás de ser "chinyan".[n][w][e]
[f 2 1]¡Eso es todo por esta semana! ¡Volvemos a las noticias![n][w][e]

[msg MSG_253_0_0 [Presentador de telediario]]
[f 2 1]... la tasa de cambio de hoy.[n][w][e]
[f 2 1]Un dólar equivale a 115,52 yenes, un 0,24 % menos que la última vez.[n][w][e]
[f 2 1]La economía de Japón empieza a notar los efectos de la apatía...[n][w][e]

[msg MND_254_0_0]
[f 2 1]En todos los canales hay noticias relacionadas con la apatía...[n][w][e]

[msg MSG_255_0_0 [Narrador]]
[f 2 1]¡En el próximo episodio de Phoenix Rangers Featherman R![n][w][e]
[f 2 1]Episodio 39: ¡Lanza los dados! ¡Salva el mundo sacando un 20![n][w][e]

[msg MSG_256_0_0 [Presentador de telediario]]
[f 2 1]Vamos con las noticias de hoy.[n][w][e]
[f 2 1]Ayer atraparon al ladrón que robaba a las víctimas de apatía...[n][w][e]

[msg MSG_257_0_0 [Periodista]]
[f 2 1]Hola, soy Trish y os traigo un nuevo programa de "Quién es quién".[n][w][e]
[f 2 1]El sujeto de hoy tiene el pelo azul, un maquillaje curioso, una funda de guitarra y una forma rara de caminar.[n][w][e]
[f 2 1]Es cocinero de sushi y tiene un grupo. ¡Y hoy es su cumpleaños![n][w][e]
[f 2 1]Pasamos a las noticias. ¡Apatía, vete y no vuelvas![n][w][e]

[msg MND_258_0_0]
[f 2 1]En todos los canales hay noticias relacionadas con la apatía...[n][w][e]

[msg MND_259_0_0]
[f 2 1]En todos los canales hay noticias relacionadas con la apatía...[n][w][e]

[msg MSG_260_0_0 [Presentador de telediario]]
[f 2 1]Interrumpimos Phoenix Rangers Featherman R por una noticia de última hora.[n][w][e]
[f 2 1]Parece que anoche alguien lanzó un dispositivo explosivo en el interior del hospital de Minato.[n][w][e]
[f 2 1]La policía sospecha que fue el familiar enloquecido de una víctima de apatía...[n][w][e]

[msg MSG_261_0_0 [Presentador de telediario]]
[f 2 1]Más detalles sobre el explosivo que lanzaron en el hospital Memorial de Tatsumi...[n][w][e]
[f 2 1]Milagrosamente, no hubo muertos ni heridos, pero se desconoce el paradero de una paciente...[n][w][e]

[msg MSG_262_0_0 [Presentador de telediario]]
[f 2 1]... novedades sobre la paciente que desapareció ayer.[n][w][e]
[f 2 1]Muy probablemente, la persona que lanzó el explosivo secuestró a la niña...[n][w][e]

[msg MSG_263_0_0 [Presentador de telediario]]
[f 2 1]A continuación, otra noticia sobre una persona desaparecida.[n][w][e]
[f 2 1]Tomoyuki Itami (57), un oficinista de Minato, y Katsue Sugi (47), ama de casa...[n][w][e]
[f 2 1]han desaparecido casi al mismo tiempo.[n][w][e]
[f 2 1]La policía busca pistas y ha solicitado la colaboración ciudadana.[n][w][e]

[msg MND_264_0_0]
[f 2 1]Cabe la posibilidad de que se hayan adentrado en la torre Tártaro...[n][w][e]
[f 2 1]Tenemos que ir a salvarlos.[n][w][e]

[msg MSG_265_0_0 [Narrador]]
[f 2 1]¡En el próximo episodio de Phoenix Rangers Featherman R![n][w][e]
[f 2 1]Episodio 41: ¡La base secreta E*X*P*L*O*T*A! ¡Recupérala, Featherman R![n][w][e]

[msg MSG_266_0_0 [Presentador de telediario]]
[f 2 1]Vamos con las noticias de hoy.[n][w][e]
[f 2 1]La apatía sigue provocando mucha tensión, ya que aún no se sabe qué la causa...[n][w][e]

[msg MSG_267_0_0 [Periodista]]
[f 2 1]Hola, soy Trish y os traigo un nuevo programa de "Quién es quién".[n][w][e]
[f 2 1]El sujeto de hoy es una mujer de unos 30 años con un lunar bajo el ojo.[n][w][e]
[f 2 1]Sabe bailar flamenco, así que me pregunto cómo le quedaría una rosa en la boca...[n][w][e]
[f 2 1]Pasamos a las noticias. ¡Apatía, vete y no vuelvas![n][w][e]

[msg MND_268_0_0]
[f 2 1]En todos los canales hay noticias relacionadas con la apatía...[n][w][e]

[msg MND_269_0_0]
[f 2 1]En todos los canales hay noticias relacionadas con la apatía...[n][w][e]

[msg MSG_270_0_0 [Presentador de telediario]]
[f 2 1]Este mes todavía no ha descendido el número de pacientes con apatía.[n][w][e]
[f 2 1]Muchos se cuestionan la competencia de los expertos que predijeron cuándo comenzaría la recuperación...[n][w][e]

[msg MSG_271_0_0 [Presentador de telediario]]
[f 2 1]... el color de la suerte de los capricornio es el celeste.[n][w][e]
[f 2 1]Para protegerse de la apatía, ¡despídanse del sol al atardecer![n][w][e]

[msg MSG_272_0_0 [Presentador de telediario]]
[f 2 1]... la tasa de cambio de hoy.[n][w][e]
[f 2 1]Un dólar equivale a 115,6 yenes, por lo que ha variado en un 0,13 %.[n][w][e]
[f 2 1]El avance de la apatía está afectando a la economía de...[n][w][e]

[msg MSG_273_0_0 [Narrador]]
[f 2 1]¡En el próximo episodio de Phoenix Rangers Featherman R![n][w][e]
[f 2 1]Episodio 42: ¡Duerme en mis brazos! Amor y nada más... Pero ¡¿y las batallas?![n][w][e]

[msg MSG_274_0_0 [Presentador de telediario]]
[f 2 1]Vamos con las noticias de hoy.[n][w][e]

[msg MSG_275_0_0 [Presentador de telediario]]
[f 2 1]... novedades en moda.[n][w][e]
[f 2 1]Los expertos dicen que no podrán sobrevivir al invierno sin cachemira...[n][w][e]

[msg MSG_276_0_0 [Presentador de telediario]]
[f 2 1]... temporada de cangrejos, pero los pescadores no pueden cubrir la demanda.[n][w][e]
[f 2 1]La epidemia de apatía también ha afectado a los pescadores y...[n][w][e]

[msg MND_277_0_0]
[f 2 1]En todos los canales hay noticias relacionadas con la apatía...[n][w][e]

[msg MSG_278_0_0 [Experto en fitness]]
[f 2 1]La palabra cantonesa de hoy es "aiyah". ¡Ponte la mano delante de la boca y di "aiyah"![n][w][e]
[f 2 1]"Aiyah" es una palabra muy común. Significa "¡ni de broma!".[n][w][e]
[f 2 1]¡Eso es todo por esta semana! ¡Aléjate del frío y de la apatía! ¡Volvemos a las noticias![n][w][e]

[msg MSG_279_0_0 [Presentador de telediario]]
[f 2 1]Las rebajas de invierno están a punto de comenzar en las tiendas.[n][w][e]
[f 2 1]Los grandes almacenes de la ciudad han estimado los beneficios de la época festiva...[n][w][e]
[f 2 1]Aunque esperan unos ingresos del 110 % al 120 %...[n][w][e]
[f 2 1]La falta de compradores debido a la apatía puede que no permita que se cumplan esas expectativas...[n][w][e]

[msg MSG_280_0_0 [Presentador de telediario]]
[f 2 1]... partido político intentó destituir a los insurgentes, pero la oposición estaba formada por más de 50 miembros.[n][w][e]
[f 2 1]El presidente del partido no tuvo más opción que retractarse.[n][w][e]
[f 2 1]A este paso, seguro que habrá debate sobre qué partido se equivoca...[n][w][e]

[msg MSG_281_0_0 [Narrador]]
[f 2 1]¡En el próximo episodio de Phoenix Rangers Featherman R![n][w][e]
[f 2 1]Episodio 43: ¡En el cuerpo político! Los Feathermen encogen para investigar la enfermedad del ministro.[n][w][e]

[msg MSG_282_0_0 [Presentador de telediario]]
[f 2 1]Vamos con las noticias de hoy.[n][w][e]
[f 2 1]La apatía todavía no ha...[n][w][e]

[msg MSG_283_0_0 [Hombre del tiempo]]
[f 2 1]Según el mapa meteorológico de hoy, ¡hará sol el resto de la semana![n][w][e]
[f 2 1]¡Toda una decepción para los que esperaban una blanca Navidad![n][w][e]
[f 2 1]¡Volvemos al estudio![n][w][e]

[msg MSG_284_0_0 [Presentador de telediario]]
[f 2 1]¡Les damos la bienvenida a Supernoticias de acción, con todas las noticias del día y más![n][w][e]

[msg MSG_285_0_0 [Narrador]]
[f 2 1]¡En el próximo episodio de Phoenix Rangers Featherman R![n][w][e]
[f 2 1]Episodio 44: ¡Tannika, el robot demonio! ¡Cuidado, Featherman R![n][w][e]

[msg MSG_286_0_0 [Presentador de telediario]]
[f 2 1]Vamos con las noticias de hoy.[n][w][e]
[f 2 1]La apatía todavía no ha...[n][w][e]

[msg MND_287_0_0]
[f 2 1]En todos los canales hay noticias relacionadas con la apatía...[n][w][e]

[msg MSG_288_0_0 [Presentador de telediario]]
[f 2 1]Vamos con las noticias de hoy.[n][w][e]
[f 2 1]En primer lugar, tenemos otra persona desaparecida.[n][w][e]
[f 2 1]La trabajadora social Yumiko Sasamaki (28) y la oficinista Nobuko Fukuchi (26)...[n][w][e]
[f 2 1]han desaparecido casi al mismo tiempo.[n][w][e]
[f 2 1]La policía busca pistas y ha solicitado la colaboración ciudadana.[n][w][e]

[msg MND_289_0_0]
[f 2 1]Cabe la posibilidad de que se hayan adentrado en la torre Tártaro...[n][w][e]
[f 2 1]Tenemos que ir a salvarlas.[n][w][e]

[msg MSG_290_0_0 [Presentador de telediario]]
[f 2 1]... Nochebuena mañana.[n][w][e]
[f 2 1]Los árboles de Navidad iluminarán la noche por toda la ciudad...[n][w][e]

[msg MSG_291_0_0 [Experto en fitness]]
[f 2 1]¡Mañana es Navidad! Con tanto banquete, ¡no dejéis de hacer ejercicio![n][w][e]
[f 2 1]La palabra cantonesa de hoy es "haime". ¡Haz una mueca y di "haime"![n][w][e]
[f 2 1]"Haime" significa "¡¿me estás vacilando?!". Por ejemplo: "haime", ¡¿tengo que trabajar en Navidad?![n][w][e]
[f 2 1]¡Eso es todo por esta semana! ¡Volvemos a las noticias![n][w][e]

[msg MSG_292_0_0 [Presentador de telediario]]
[f 2 1]... la mitad de los estudiantes faltaron a la ceremonia de clausura del segundo trimestre por apatía...[n][w][e]

[msg MSG_293_0_0 [Presentador de telediario]]
[f 2 1]... robo de productos de marca.[n][w][e]
[f 2 1]Había tanta gente que todavía no hay sospechosos ni testigos...[n][w][e]
[f 2 1]Pero la mayoría de los clientes eran mujeres comprando regalos de Navidad, así que...[n][w][e]

[msg MSG_294_0_0 [Narrador]]
[f 2 1]¡En el próximo episodio de Phoenix Rangers Featherman R![n][w][e]
[f 2 1]Episodio 45: ¡El chocolate de la victoria! ¡Encuentra el punto débil del robot demonio y derrótalo![n][w][e]

[msg MSG_295_0_0 [Presentador de telediario]]
[f 2 1]Vamos con las noticias de hoy.[n][w][e]
[f 2 1]Vamos a dedicar 15 minutos a repasar las diferentes formas de prevenir la apatía con el famoso...[n][w][e]

[msg MSG_296_0_0 [Narrador]]
[f 2 1]... tras las sonrisas navideñas se oculta una ardua batalla.[n][w][e]
[f 2 1]Hoy se apagan para siempre las luces de esta tienda de juguetes que abrió hace 50 años...[n][w][e]

[msg MSG_297_0_0 [Presentador de telediario]]
[f 2 1]Aquí concluye nuestro informe especial. A continuación, las noticias.[n][w][e]

[msg MSG_298_0_0 [Presentador de telediario]]
[f 2 1]Una encuesta sobre las noticias más populares pone la apatía en el número 1...[n][w][e]

[msg MSG_299_0_0 [Periodista]]
[f 2 1]Hola, soy Trish y os traigo un nuevo programa de "Quién es quién".[n][w][e]
[f 2 1]El sujeto de hoy es un hombre de unos 30 años que viste con trajes muy elegantes.[n][w][e]
[f 2 1]Aunque es policía, también le da a la cocina a escondidas.[n][w][e]
[f 2 1]A continuación, las noticias. ¡La apatía tiene que irse este año![n][w][e]

[msg MSG_300_0_0 [Presentador de telediario]]
[f 2 1]La apatía sigue extendiéndose y eso causa malestar en la...[n][w][e]

[msg MSG_301_0_0 [Presentador de telediario]]
[f 2 1]... feliz Año Nuevo! Y ahora, las primeras noticias de 2010.[n][w][e]
[f 2 1]El primer paciente con apatía del año ingresó a la 01:13 de la madrugada.[n][w][e]

[msg MSG_302_0_0 [Presentador de telediario]]
[f 2 1]... se centran en pintar y colocar carteles por toda la ciudad.[n][w][e]
[f 2 1]Como todas las obras tienen diseños similares, la policía cree que el culpable es el mismo...[n][w][e]

[msg MSG_303_0_0 [Presentador de telediario]]
[f 2 1]Han detenido a un hombre que perdió los estribos en el santuario.[n][w][e]
[f 2 1]El hombre, no identificado, repetía: "La caída es la salvación"...[n][w][e]

[msg MSG_304_0_0 [Presentador de telediario]]
[f 2 1]Un hombre ha sido arrestado por intentar reclutar a otros para un suicidio colectivo.[n][w][e]
[f 2 1]El detenido es un hombre de 30 años, desempleado y adicto a las revistas relacionadas con sectas...[n][w][e]

[msg MSG_305_0_0 [Narrador]]
[f 2 1]... finalmente, el anciano que sufría apatía murió por malnutrición.[n][w][e]
[f 2 1]Este hombre ha sido el primer paciente que el doctor no ha podido salvar. Corrían lágrimas por sus mejillas...[n][w][e]

[msg MSG_306_0_0 [Presentador de telediario]]
[f 2 1]Aquí concluye nuestro informe especial. A continuación, las noticias.[n][w][e]

[msg MND_307_0_0]
[f 2 1]En todos los canales hay noticias relacionadas con la apatía...[n][w][e]

[msg MSG_308_0_0 [Experto en fitness]]
[f 2 1]¡Feliz Año Nuevo! ¡Vamos con el primer ejercicio de 2010! No les diré cuántos años tengo, ¡pero son bastantes![n][w][e]
[f 2 1]La palabra cantonesa de hoy es "hoisamuro". ¡Pega un puñetazo al aire y di "hoisamuro"![n][w][e]
[f 2 1]"Hoisamuro" significa "¡bien!". ¡Los estudiantes, tras terminar los exámenes, gritaron "hoisamuro"![n][w][e]
[f 2 1]¡Eso es todo por esta semana! ¡Volvemos a las noticias sobre sectas![n][w][e]

[msg MSG_309_0_0 [Presentador de telediario]]
[f 2 1]... investigación muestra que los regalos de este año nuevo se han visto afectados por la apatía.[n][w][e]
[f 2 1]Debido a la epidemia, los padres no pueden visitar a sus parientes y...[n][w][e]

[msg MSG_310_0_0 [Presentador de telediario]]
[f 2 1]Ahora, noticias bursátiles.[n][w][e]
[f 2 1]Según avanza el mes, las empresas de seguridad aumentan sus beneficios.[n][w][e]
[f 2 1]El pensamiento apocalíptico que se ha extendido entre la población parece ser un factor decisivo...[n][w][e]

[msg MSG_311_0_0 [Narrador]]
[f 2 1]¡En el próximo episodio de Phoenix Rangers Featherman R![n][w][e]
[f 2 1]Episodio 46: ¡La granja de tomates del gran demonio! ¡¿A Búho no le gustan los tomates?![n][w][e]

[msg MSG_312_0_0 [Presentador de telediario]]
[f 2 1]Vamos con las noticias de hoy.[n][w][e]
[f 2 1]A las autoridades municipales les preocupa que los carteles y grafitis estén dañando la imagen de la ciudad...[n][w][e]

[msg MSG_313_0_0 [Presentador de telediario]]
[f 2 1]Hoy es el Día de la Mayoría de Edad y había fiestas planeadas en cada zona para los que cumplen 20.[n][w][e]
[f 2 1]Sin embargo, debido a la apatía, muchas de ellas han sido canceladas.[n][w][e]

[msg MSG_314_0_0 [Hombre del tiempo]]
[f 2 1]Como se ve en el mapa, ¡el cielo estará despejado toda la semana![n][w][e]
[f 2 1]¡Los que tengáis exámenes de acceso no tendréis que preocuparos por la nieve![n][w][e]
[f 2 1]¡Volvemos al estudio![n][w][e]

[msg MSG_315_0_0 [Presentador de telediario]]
[f 2 1]¡Les damos la bienvenida a Supernoticias de acción, con todas las noticias del día y más![n][w][e]

[msg MSG_316_0_0 [Presentador de telediario]]
[f 2 1]Una revista que salió ayer está causando problemas en toda la comunidad.[n][w][e]
[f 2 1]El alboroto se originó por un artículo sobre el líder de una secta llamado Carisma.[n][w][e]
[f 2 1]Según las doctrinas de Nix, hay un poder que elimina las preocupaciones por el futuro.[n][w][e]
[f 2 1]Creer en esta habilidad está provocando que muchos jóvenes estudiantes se unan a la secta...[n][w][e]

[msg MSG_317_0_0 [Presentador de telediario]]
[f 2 1]... la tasa de cambio de hoy.[n][w][e]
[f 2 1]Un dólar equivale a 108,42 yenes. La moneda japonesa ha sufrido un tremendo declive...[n][w][e]
[f 2 1]El resultado de la apatía y la doctrina de la secta se están convirtiendo...[n][w][e]

[msg MSG_318_0_0 [Presentador de telediario]]
[f 2 1]... para los géminis, el color de la suerte es el naranja.[n][w][e]
[f 2 1]¡Para mantener la apatía a raya, pónganse la camiseta del revés! Nunca se sabe, podría funcionar...[n][w][e]

[msg MSG_318_1_0 [Presentador de telediario]]
[f 2 1]Vamos con las noticias de hoy.[n][w][e]
[f 2 1]En primer lugar, tenemos otra persona desaparecida.[n][w][e]
[f 2 1]Mitsutoshi Okimoto, alumno de primer año del Instituto Gekkoukan, y Fumika Terado, 21, trabajadora de una tienda...[n][w][e]
[f 2 1]han desaparecido casi al mismo tiempo.[n][w][e]
[f 2 1]La policía busca pistas y ha solicitado la colaboración ciudadana.[n][w][e]

[msg MND_319_0_0]
[f 2 1]Cabe la posibilidad de que se hayan adentrado en la torre Tártaro...[n][w][e]
[f 2 1]Tenemos que ir a salvarlos.[n][w][e]

[msg MSG_320_0_0 [Presentador de telediario]]
[f 2 1]... exámenes de acceso a la universidad han tenido lugar hoy.[n][w][e]
[f 2 1]Un estudiante llevó una pistola de balines al centro de examinación y sembró el pánico entre la multitud...[n][w][e]

[msg MSG_321_0_0 [Narrador]]
[f 2 1]¡En el próximo episodio de Phoenix Rangers Featherman R![n][w][e]
[f 2 1]Episodio 47: ¡La gloria del gran emperador! ¡La lucha llega a su fin![n][w][e]

[msg MSG_322_0_0 [Presentador de telediario]]
[f 2 1]Vamos con las noticias de hoy.[n][w][e]
[f 2 1]Parece que la creencia en Nix está aumentando en la ciudad...[n][w][e]

[msg MND_323_0_0]
[f 2 1]En todos los canales hay noticias relacionadas con la secta...[n][w][e]

[msg MSG_324_0_0 [Presentador de telediario]]
[f 2 1]Un ama de casa de 50 años se vio implicada en un fraude bancario...[n][w][e]
[f 2 1]Durante el interrogatorio, afirmó que un hombre que decía ser el "hijo de Nix" la obligó a hacerlo...[n][w][e]

[msg MSG_325_0_0 [Presentador de telediario]]
[f 2 1]Durante una demostración en directo, un hombre con una bandana empezó a dar un discurso.[n][w][e]
[f 2 1]"¡El descenso de Nix es real!", dijo el hombre. Después...[n][w][e]

[msg MSG_326_0_0 [Experto en fitness]]
[f 2 1]La palabra cantonesa de hoy es "holeen".[n][w][e]
[f 2 1]"Holeen" significa "patético". ¿Somos "holeen" por vivir en un mundo así?[n][w][e]
[f 2 1]Eso es todo por esta semana... Volvemos a las noticias...[n][w][e]

[msg MSG_327_0_0 [Presentador de telediario]]
[f 2 1]Los exámenes de acceso se ciernen sobre la población estudiantil de la ciudad.[n][w][e]
[f 2 1]Sin embargo, hay que tener cuidado con tanto sectario suelto...[n][w][e]

[msg MND_328_0_0]
[f 2 1]En todos los canales hay noticias relacionadas con la secta...[n][w][e]

[msg MSG_329_0_0 [Narrador]]
[f 2 1]¡En el próximo episodio de Phoenix Rangers Featherman R![n][w][e]
[f 2 1]Último episodio: ¡Vuela, Fénix! ¡Halcón y Cisne se casan! Y en cuanto a Cóndor...[n][w][e]

[msg MSG_330_0_0 [Presentador de telediario]]
[f 2 1]Vamos con las noticias de hoy.[n][w][e]
[f 2 1]La afiliación a la secta sigue creciendo, mientras...[n][w][e]

[msg MND_331_0_0]
[f 2 1]En todos los canales hay noticias relacionadas con la secta...[n][w][e]

[msg MSG_332_0_0 [Presentador de telediario]]
[f 2 1]... granja se encontró cinco huevos sin yema.[n][w][e]
[f 2 1]Según leyendas locales, estos huevos traen muy mala suerte.[n][w][e]
[f 2 1]Los habitantes de la zona temen que ocurra cualquier catástrofe.[n][w][e]

[msg MSG_333_0_0 [Presentador de telediario]]
[f 2 1]Una mujer reprendió a un grupo de adolescentes por pintar grafitis.[n][w][e]
[f 2 1]Posteriormente, uno de los jóvenes la apuñaló mientras el resto se daba a la fuga.[n][w][e]
[f 2 1]Los médicos dicen que la mujer ha tenido suerte y que tardará alrededor de una semana en recuperarse.[n][w][e]

[msg MSG_334_0_0 [Presentador de telediario]]
[f 2 1]... nota decía: "He suspendido los exámenes de acceso. No tengo motivos para vivir"...[n][w][e]
[f 2 1]La policía ha calificado el suceso como un suicidio tras suspender los exámenes de acceso a la universidad.[n][w][e]
[f 2 1]Ha habido al menos ocho casos de suicidio como resultado de los exámenes y...[n][w][e]

[msg MND_335_0_0]
[f 2 1]En todos los canales hay noticias relacionadas con la secta...[n][w][e]

[msg MSG_336_0_0 [Presentador de telediario]]
[f 2 1]Hoy comenzaremos una nueva serie de reportajes de investigación: "Esperanza para el futuro".[n][w][e]
[f 2 1]Ante la tremenda desigualdad salarial, encuestaremos a la ciudadanía sobre sus esperanzas para el futuro.[n][w][e]
[f 2 1]Nuestro primer reportaje será: "Jóvenes pesimistas tras pincharse la burbuja".[n][w][e]
[f 2 1]Hablaremos con esos jóvenes que han dejado sus sueños a un lado por su desilusión con el capitalismo...[n][w][e]

[msg MSG_337_0_0 [Presentador de telediario]]
[f 2 1]... parque lleno de gente, todos vestidos de negro.[n][w][e]
[f 2 1]Parece que esta gran multitud se debe a una reunión de la secta.[n][w][e]
[f 2 1]Algunos miembros llevan pancartas en las que pone "Nix" o "Revolución silenciosa". Qué escena tan enigmática...[n][w][e]

[msg MSG_338_0_0 [Presentador de telediario]]
[f 2 1]Y ahora, noticias sobre salud.[n][w][e]
[f 2 1]Recuerden hacer gárgaras con agua caliente para alejar...[n][w][e]

[msg MSG_339_0_0 [Presentador de telediario]]
[f 2 1]La temporada de graduaciones está a punto de comenzar.[n][w][e]
[f 2 1]Ya se empieza a ver a muchas estudiantes con sus cheongsams.[n][w][e]
[f 2 1]Podríamos estar perfectamente en una fiesta de disfraces si no fuera por los diplomas que llevan en la mano.[n][w][e]

[msg MSG_340_0_0 [Presentador de telediario]]
[f 2 1]Pasemos a otra noticia...[n][w][e]
[f 2 1]Volvemos a hablar de la misteriosa apatía...[n][w][e]
[f 2 1]Todos los pacientes se han recuperado durante el último mes y no se han descubierto más casos.[n][w][e]

[msg MSG_341_0_0 [Presentador de telediario]]
[f 2 1]... terminado de limpiar los grafitis y casi se han quitado todos los carteles.[n][w][e]
[f 2 1]En estos momentos, el paradero de la secta...[n][w][e]

