[msg MSG_000_0_0 [Niños]]
[f 2 1][vp 1 0 0 1 0 0]¡La entrenadora y su novia![n][w][e]

[msg MSG_001_0_0 [(SE) Niño enérgico]]
[f 2 1]¡La entrenadora y su novia![n][w][e]

[msg MSG_002_0_0 [(SE) Chico enérgico]]
[f 2 1]¡La entrenadora y su novia![n][w][e]

[msg MSG_003_0_0 [(SE) Chica serena]]
[f 2 1]¡La entrenadora y su novia![n][w][e]

[msg MSG_004_0_0 [Chica serena]]
[f 2 1][vp 1 0 0 5 0 0][f 5 21 0 1001]¡Entrenadora! ¡Hemos competido con todos ellos uno a uno y hemos ganado dos![n][w][e]

[msg MSG_005_0_0 [Niño enérgico]]
[f 2 1][vp 1 0 0 6 0 0][f 5 21 0 1002]¡Hemos empatado con los de sexto! ¡¿Te lo puedes creer?![n][w][e]
[f 2 1][vp 1 0 0 7 0 0][f 5 21 0 1002]¡Nos van a dejar jugar en el patio! ¡Y, encima, también nos hemos hecho amigos![n][w][e]
[f 2 1][vp 1 0 0 8 0 0][f 5 21 0 1002]¡Dicen que somos muy rápidos para ser de cuarto y nos han invitado a jugar con ellos de vez en cuando![n][w][e]

[msg MSG_006_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 9 0 0]Ay, chicos...[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 10 0 0][f 4 23 0 1 1 25 25]Nunca dudé de vosotros, porque sé lo mucho que os habéis esforzado.[n][w][e]

[msg MSG_007_0_0 [Niño enérgico]]
[f 2 1][vp 1 0 0 11 0 0][f 5 21 0 1002]¡Muchas gracias! Eh... ¡Yuko![n][w][e]

[msg MSG_008_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 12 0 0]Ah, no hace falta que me llaméis así si no queréis. Me he acostumbrado a "tita Yuko".[n][w][e]

[msg MSG_009_0_0 [Niño enérgico]]
[f 2 1][vp 1 0 0 13 0 0][f 5 21 0 1002]Una, dos... ¡y tres![n][w][e]

[msg MSG_009_5_0 [Niños]]
[f 2 1][vp 1 0 0 14 0 0]¡Buena suerte con tu novia![n][w][e]

[msg MSG_010_0_0 [(SE) Niño enérgico]]
[f 2 1]¡Buena suerte con tu novia![n][w][e]

[msg MSG_011_0_0 [(SE) Chico enérgico]]
[f 2 1]¡Buena suerte con tu novia![n][w][e]

[msg MSG_012_0_0 [(SE) Chica serena]]
[f 2 1]¡Buena suerte con tu novia![n][w][e]

[msg MSG_013_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 18 0 0]Erre que erre con que eres mi novia...[n][w][e]

[sel SEL_014_0_0 top]
[f 2 1]¿Quieres que lo hagamos realidad?[f 2 9 1 1 346][e]
[f 2 1]Me da mucho corte.[e]
[f 2 1]Solo están de broma.[e]

[msg MSG_015_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 4 65535 65535 1 0][vp 1 0 0 19 0 0]Ah, vale... E-espera, ¡¿qué?![n][w][e]

[msg MSG_016_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 2 65535 65535 0 0][vp 1 0 0 20 0 0]¡Eh! ¡No te rías! ¡Que casi me da un jamacuco con esa broma![n][w][e]
[f 2 1][bup 106 3 65535 65535 0 0][vp 1 0 0 21 0 0][f 4 23 0 1 3 25 25]Me has pillado desprevenida diciendo eso así de la nada...[n][w][e]

[msg MSG_017_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 22 0 0]Ya, sé que son solo críos, pero...[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 23 0 0]Solo de pensarlo se me pone la piel de gallina.[n][w][e]

[msg MSG_018_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 24 0 0]Sí, lo sé.[n][w][e]
[f 2 1][bup 106 3 65535 65535 0 0][vp 1 0 0 25 0 0][f 4 23 0 1 3 25 25]Hasta dicen que Kaz es mi novio cuando voy con él.[n][w][e]

[msg MSG_019_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 0 0 0 26 0 0]...[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 27 0 0]¿Sabes lo que parece esto?[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 28 0 0]El episodio final de una serie ñoña de instituto.[n][w][e]

[msg MSG_019_5_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 3 65535 65535 0 0][vp 0 0 0 29 0 0]...[n][w][e]
[f 2 1][bup 106 3 65535 65535 0 0][vp 1 0 0 30 0 0]Es como que los niños han abandonado el nido...[n][w][e]

[sel SEL_020_0_0 top]
[f 2 1]¿Estás triste?[e]
[f 2 1]¿Te sientes más aliviada?[e]

[msg MSG_021_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 31 0 0]Sí, un poco. Ahora hay mucho silencio...[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 32 0 0][f 4 23 0 1 1 25 25]Aunque al principio me costó mucho.[n][w][e]

[msg MSG_022_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 2 65535 65535 0 0][vp 1 0 0 33 0 0][f 5 13 12 5 106]¡Pues claro! Estaba preocupadísima por que se lesionaran.[n][w][e]

[msg MSG_023_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 3 65535 65535 0 0][vp 1 0 0 34 0 0]Para ser sincera, al principio me costó, pero ahora que no están aquí me siento un poco sola.[n][w][e]

[msg MSG_024_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 35 0 0]Me lo he pasado bomba enseñando a correr a los críos.[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 36 0 0][f 4 23 0 1 1 25 25]Se les veía radiantes cada vez que corrían más rápido, y a mí también me hacían feliz.[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 37 0 0]Mis ganas de querer ayudarlos aumentaban más y más.[n][w][e]

[msg MSG_025_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 38 0 0]La verdad, ha sido la primera vez que me vuelco en cuerpo y alma en algo.[n][w][e]

[msg MSG_025_5_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 39 0 0]Tampoco quiero que te pienses que me rasco la barriga como encargada del equipo...[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 40 0 0][f 4 23 0 1 1 25 25]Pero ¿y si lo mío es ayudar y enseñar a la gente?[n][w][e]

[msg MSG_025_7_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 41 0 0]Esto me ha hecho pensar. Sobre lo que quiero hacer en el futuro, quiero decir.[n][w][e]

[msg MSG_026_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 42 0 0]¡Ah! Por cierto, mil millones de gracias, [nl].[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 43 0 0]Podríamos hacer una fiestecilla. Ya sabes, para celebrar nuestra primera experiencia como entrenadoras.[n][w][e]

[sel SEL_027_0_0 top]
[f 2 1]Venga, vale.[e]
[f 2 1]¿Por qué?[e]

[msg MSG_028_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 44 0 0][f 5 13 12 15 106]¡Yupi! ¡Me muero de ganas![n][w][e]

[msg MSG_029_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 3 65535 65535 0 0][vp 1 0 0 45 0 0]Pues porque nos ha costado mucho trabajo... ¿No crees que es una buena idea?[n][w][e]

[msg MSG_030_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 46 0 0]Mmm, ¿dónde podríamos celebrarla?[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 47 0 0][f 4 23 0 1 1 25 25]Me apetece que sea algo elegante. ¡Buscaré algún sitio![n][w][e]

[msg MND_031_0_0]
[f 2 1]Yuko desborda entusiasmo.[n][w][e]
[f 2 1]Siento que mi relación con ella se ha fortalecido.[n][w][e]

[msg MSG_032_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 48 0 0]Al principio no tenía mucha confianza, así que el hecho de que estuvieras conmigo fue...[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 49 0 0][f 4 23 0 1 1 25 25]Bueno, ya hablaremos de eso. Habrá tiempo de sobra en la fiesta.[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 50 0 0]¿Nos vamos a casa?[n][w][e]

[msg MND_033_0_0]
[f 2 1]Me marché del instituto con Yuko.[n][w][e]

