[msg MSG_000_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 2 65535 0 0][vp 1 0 0 1 0 0]Muy bien. Parece que estamos todos.[n][w][e]

[msg MSG_001_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 2 65535 0 0][vp 1 0 0 2 0 0]Bueno, ya ha pasado una semana. ¿Qué vamos a hacer?[n][w][e]
[f 2 1][bup 2 0 2 65535 0 0][vp 1 0 0 3 0 0]¿Estás bien, Fuuka?[n][w][e]

[msg MSG_002_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 2 65535 0 0][vp 1 0 0 4 0 0]E-estás muy tranquila, Yukari.[n][w][e]

[msg MSG_003_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 2 65535 0 0][vp 1 0 0 5 0 0]Preocuparse no sirve de nada.[n][w][e]
[f 2 1][bup 2 0 2 65535 0 0][vp 1 0 0 6 0 0]Además, esta semana los ánimos están muy bajos y nadie irá a la torre Tártaro.[n][w][e]

[msg MSG_004_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 2 65535 0 0][vp 1 0 0 7 0 0]Tienes toda la razón.[n][w][e]
[f 2 1][bup 5 0 2 65535 0 0][vp 1 0 0 8 0 0]Los humanos somos muy resistentes. Podemos adaptarnos a cualquier situación si disponemos de tiempo.[n][w][e]
[f 2 1][bup 5 0 2 65535 0 0][vp 1 0 0 9 0 0]Bueno, ¿qué pensáis? Es hora de que hablemos del tema.[n][w][e]

[msg MSG_005_0_0 [Junpei Iori]]
[f 2 1][bup 3 10 2 65535 0 0][vp 0 0 0 10 0 0]...[n][w][e]

[msg MSG_006_0_0 [Ken Amada]]
[f 2 1][bup 8 0 2 65535 0 0][vp 1 0 0 11 0 0]¿Te has decidido, Sanada?[n][w][e]

[msg MSG_007_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 2 65535 0 0][vp 1 0 0 12 0 0]No.[n][w][e]
[f 2 1][bup 4 2 2 65535 0 0][vp 1 0 0 13 0 0][f 4 23 0 4 2 25 25]Pero no pienso huir.[n][w][e]

[msg MSG_008_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 2 65535 0 0][vp 1 0 0 14 0 0]Entonces, ¿vas a enfrentarte a Nix?[n][w][e]

[msg MSG_009_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 2 65535 0 0][vp 1 0 0 15 0 0]No lo sé. Se supone que es invencible.[n][w][e]
[f 2 1][bup 4 0 2 65535 0 0][vp 1 0 0 16 0 0]¿Y tú? ¿Qué piensas de todo esto?[n][w][e]

[msg MSG_010_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 3 2 65535 0 0][vp 1 0 0 17 0 0]Pues, sinceramente, es la primera vez que sopeso mi propia muerte.[n][w][e]
[f 2 1][bup 5 3 2 65535 0 0][vp 1 0 0 18 0 0]De todas formas, tenemos que decantarnos por una opción u otra.[n][w][e]

[msg MSG_010_5_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 2 65535 0 0][vp 1 0 0 19 0 0]Obviamente no quiero sufrir, pero eso conlleva sacrificar una vida.[n][w][e]
[f 2 1][bup 5 0 2 65535 0 0][vp 1 0 0 20 0 0]Eso sin mencionar que vamos a morir de todas formas.[n][w][e]

[msg MSG_011_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 2 65535 0 0][vp 1 0 0 21 0 0]Entonces, ¿estamos todos de acuerdo en que no queremos hacerle daño a Ryoji?[n][w][e]

[msg MSG_012_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 2 65535 0 0][vp 1 0 0 22 0 0]¿A ti te parece bien?[n][w][e]

[msg MSG_013_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 2 65535 0 0][vp 1 0 0 23 0 0]¿A mí? Mmm...[n][w][e]

[msg MSG_014_0_0 [Yukari Takeba]]
[f 2 1][bup 2 3 2 65535 0 0][vp 1 0 0 24 0 0]A mí me parece justo. Lo natural no es elegir la manera en la que vamos a morir.[n][w][e]

[msg MSG_015_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 2 65535 0 0][vp 1 0 0 25 0 0]¿Y tú, Junpei? ¿Ya te lo has pensado?[n][w][e]

[msg MSG_016_0_0 [Junpei Iori]]
[f 2 1][bup 3 3 2 65535 0 0][vp 1 0 0 26 0 0]Qué va...[n][w][e]

[msg MSG_017_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 2 65535 0 0][vp 1 0 0 27 0 0]¿Es que tienes miedo?[n][w][e]

[msg MSG_018_0_0 [Junpei Iori]]
[f 2 1][bup 3 2 2 65535 0 0][vp 1 0 0 28 0 0]¿A ti qué mierda te pasa? ¿Esto te parece una broma?[n][w][e]

[msg MSG_019_0_0 [Yukari Takeba]]
[f 2 1][bup 2 3 2 65535 0 0][vp 1 0 0 29 0 0]Junpei, yo...[n][w][e]

[msg MSG_020_0_0 [Junpei Iori]]
[f 2 1][bup 3 2 2 65535 0 0][vp 1 0 0 30 0 0]¡Estamos hablando de morir! ¡Pues claro que me da miedo![n][w][e]
[f 2 1][bup 3 2 2 65535 0 0][vp 1 0 0 31 0 0]¡Y vosotros parece que estáis en un puto pícnic! ¡¿Es que no veis que vamos a morir todos?![n][w][e]

[msg MSG_021_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 2 65535 0 0][vp 1 0 0 32 0 0]Entonces, ¿qué crees que deberíamos hacer?[n][w][e]
[f 2 1][bup 5 0 2 65535 0 0][vp 1 0 0 33 0 0]¿Quieres matarlo?[n][w][e]

[msg MSG_022_0_0 [Junpei Iori]]
[f 2 1][bup 3 10 2 65535 0 0][vp 1 0 0 34 0 0]Yo no puedo hacer nada. Ella es la única que puede matarlo.[n][w][e]

[msg MSG_023_0_0 [Junpei Iori]]
[f 2 1][bup 3 3 2 65535 0 0][vp 1 0 0 35 0 0]Eh, [nf]...[n][w][e]
[f 2 1][bup 3 3 2 65535 0 0][vp 0 0 0 36 0 0]...[n][w][e]
[f 2 1][bup 3 3 2 65535 0 0][vp 1 0 0 37 0 0]Todo esto es culpa tuya.[n][w][e]

[msg MSG_024_0_0 [Junpei Iori]]
[f 2 1][bup 3 2 2 65535 0 0][vp 1 0 0 38 0 0]Lo tenías en tu interior y ni siquiera lo sabías.[n][w][e]
[f 2 1][bup 3 2 2 65535 0 0][vp 1 0 0 39 0 0]¡Tú fuiste la que lo criaste, joder! ¡Si no fuera por ti, nada de esto hubiera pasado![n][w][e]

[msg MSG_025_0_0 [Yukari Takeba]]
[f 2 1][bup 2 2 2 65535 0 0][vp 1 0 0 40 0 0]¡Junpei![n][w][e]

[msg MSG_025_5_0 [Yukari Takeba]]
[f 2 1][cut 3 2 0][f 1 5 0][e]

[msg MSG_026_0_0 [Junpei Iori]]
[f 2 1][bup 3 2 2 65535 0 0][vp 1 0 0 41 0 0]Se supone que tú eres "especial", ¡¿no?! ¡Pues, entonces, haz algo![n][w][e]

[sel SEL_027_0_0 top]
[f 2 1]No es culpa mía.[e]
[f 2 1]No hay nada que pueda hacer.[e]
[f 2 1]No pienso huir.[e]
[f 2 1]Yo también tengo miedo.[e]

[msg MSG_028_0_0 [Yukari Takeba]]
[f 2 1][bup 2 8 2 65535 0 0][vp 1 0 0 42 0 0]¡Para, Junpei! ¡No es culpa suya![n][w][e]
[f 2 1][bup 2 8 2 65535 0 0][vp 1 0 0 43 0 0]¡Si tenemos la posibilidad de elegir, es gracias a que ella lo ha llevado dentro![n][w][e]

[msg MSG_029_0_0 [Junpei Iori]]
[f 2 1][bup 3 10 2 65535 0 0][vp 1 0 0 44 0 0]¡Joder, ya lo sé! Es solo que...[n][w][e]
[f 2 1][bup 3 10 2 65535 0 0][vp 1 0 0 45 0 0]Bah, da igual cuántas veces intente autoconvencerme.[n][w][e]

[msg MSG_030_0_0 [Junpei Iori]]
[f 2 1][bup 3 10 2 65535 0 0][vp 1 0 0 46 0 0]¡Esto no tiene arreglo y me da un miedo que te cagas![n][w][e]

[msg MSG_031_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 2 65535 0 0][vp 1 0 0 47 0 0]Sé cómo te sientes, Junpei.[n][w][e]

[msg MSG_032_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 3 2 65535 0 0][vp 1 0 0 48 0 0]Todos estamos asustados. Yo también tengo miedo.[n][w][e]

[msg MSG_033_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 3 2 65535 0 0][vp 1 0 0 49 0 0]Yo también.[n][w][e]
[f 2 1][bup 5 3 2 65535 0 0][vp 1 0 0 50 0 0]Nunca me había sentido tan acorralada. No puedo parar de temblar...[n][w][e]

[msg MSG_034_0_0 [Yukari Takeba]]
[f 2 1][bup 2 3 2 65535 0 0][vp 1 0 0 51 0 0]Yo estoy igual. Todos estamos en las mismas.[n][w][e]
[f 2 1][bup 2 3 2 65535 0 0][vp 1 0 0 52 0 0]Ah, y perdona por haberme metido contigo antes.[n][w][e]

[msg MSG_034_5_0 [Yukari Takeba]]
[f 2 1][bup 2 3 2 65535 0 0][vp 1 0 0 53 0 0]Lo he hecho porque no quiero olvidarme de nada.[n][w][e]
[f 2 1][bup 2 3 2 65535 0 0][vp 1 0 0 54 0 0]Desde que llegué aquí, he aprendido muchísimo.[n][w][e]

[msg MSG_035_0_0 [Junpei Iori]]
[f 2 1][bup 3 3 2 65535 0 0][vp 1 0 0 55 0 0]Yuka...[n][w][e]
[f 2 1][bup 3 3 2 65535 0 0][vp 1 0 0 56 0 0]Lo siento, no quería gritarte de esa manera.[n][w][e]

[msg MSG_036_0_0 [Yukari Takeba]]
[f 2 1][bup 2 3 2 65535 0 0][vp 1 0 0 57 0 0]No se te puede culpar de nada en estos momentos, Junpei.[n][w][e]

[msg MSG_036_5_0 [Yukari Takeba]]
[f 2 1][bup 2 0 2 65535 0 0][vp 1 0 0 58 0 0]Así que todo arreglado. ¿Verdad, [nl]?[n][w][e]

[sel SEL_037_0_0 top]
[f 2 1]Sí, no pasa nada.[e]
[f 2 1]No es culpa de nadie.[e]
[f 2 1]Lo siento...[e]

[msg MSG_038_0_0 [Junpei Iori]]
[f 2 1][bup 3 3 2 65535 0 0][vp 1 0 0 59 0 0]Lo siento...[n][w][e]
[f 2 1][bup 3 3 2 65535 0 0][vp 1 0 0 60 0 0]En el fondo sabía la verdad, y aun así...[n][w][e]
[f 2 1][bup 3 3 2 65535 0 0][vp 1 0 0 61 0 0]Siento haberme comportado como un idiota.[n][w][e]

[msg MSG_039_0_0 [Junpei Iori]]
[f 2 1][bup 3 3 2 65535 0 0][vp 1 0 0 62 0 0]No tienes que disculparte.[n][w][e]
[f 2 1][bup 3 3 2 65535 0 0][vp 1 0 0 63 0 0]En el fondo sabía la verdad, y aun así...[n][w][e]
[f 2 1][bup 3 3 2 65535 0 0][vp 1 0 0 64 0 0]Siento haberme comportado como un idiota.[n][w][e]

[msg MSG_040_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 2 65535 0 0][vp 1 0 0 65 0 0]Muy bien. Evitaremos cualquier reunión innecesaria de momento.[n][w][e]
[f 2 1][bup 5 0 2 65535 0 0][vp 1 0 0 66 0 0]Ryoji dijo que volvería en Nochevieja, así que vamos a intentar hacer vida normal hasta entonces.[n][w][e]

[msg MSG_041_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 3 2 65535 0 0][vp 1 0 0 67 0 0]Todavía tenemos tiempo, así que aún podemos contemplar algunas opciones.[n][w][e]

