[msg MSG_000_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 1 0 0]Sí, correcto. La respuesta es "Enfermedad de mayo". En la siguiente frase...[n][w][e]

[msg MSG_001_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 0 0 0 2 0 0]...[n][w][e]

[msg MSG_002_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 3 0 0]¿Qué pasa, Iori? ¿Tienes la enfermedad de mayo?[n][w][e]

[msg MSG_003_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 65535 65535 0 0][vp 1 0 0 4 0 0]¡¿Eh?! Ah, no, ¡no es nada![n][w][e]

[msg MSG_004_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 5 0 0]Eh, ¡Kirijo! Esta pregunta de aquí...[n][w][e]

[msg MSG_005_0_0 [Junpei Iori]]
[f 2 1][bup 3 9 65535 65535 0 0][vp 1 0 0 6 0 0]Oye, [nf]... ¿Hueles eso? Me tiene loco...[n][w][e]

[sel SEL_006_0_0 top]
[f 2 1]¿Qué olor?[e]
[f 2 1]Concéntrate.[e]
[f 2 1]Me está entrando hambre.[e]

[msg MSG_007_0_0 [Junpei Iori]]
[f 2 1][bup 3 9 65535 65535 0 0][vp 1 0 0 7 0 0]¡Sabes perfectamente a lo que me refiero! Ese olor a flores que viene de donde está Kirijo.[n][w][e]

[msg MSG_008_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 65535 65535 0 0][vp 1 0 0 8 0 0]¡¿Cómo quieres que me concentre?! Ese olor al otro lado de la mesa es tan...[n][w][e]

[msg MSG_009_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 65535 65535 0 0][vp 1 0 0 9 0 0]¡Venga ya, tía! ¡Ordena tus prioridades! ¡¿Es que no notas cuando una fragancia seductora te pasa por el lado?![n][w][e]

[msg MSG_010_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 1 65535 65535 0 0][vp 1 0 0 10 0 0]Sí, te entiendo perfectamente. Si te digo la verdad, me encanta ese olor.[n][w][e]

[msg MSG_011_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 1 0 0 11 0 0]¡Ajá! ¡Así me gusta, Akihiko![n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0][vp 1 0 0 12 0 0]Tío, esto es la gloria... ¡Qué delicadeza, qué elegancia! ¡Huele a clase pudiente![n][w][e]

[msg MSG_012_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 13 0 0]Yo lo describiría como... estimulante. Hasta puedo saborear su jugosa ternura.[n][w][e]

[msg MSG_013_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 1 0 0 14 0 0]¿De qué hablas?[n][w][e]

[msg MSG_014_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 1 65535 65535 0 0][vp 1 0 0 15 0 0]Estaba calentándome un bol de ternera para picar algo antes de irme a la cama. ¿A que huele que alimenta?[n][w][e]

[msg MSG_015_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 65535 65535 0 0][vp 1 0 0 16 0 0]¿Un bol de ternera? ¡¿A eso te estabas refiriendo?![n][w][e]

[sel SEL_016_0_0 top]
[f 2 1]Se me hace la boca agua.[e]
[f 2 1]¡Estaba esperando esto![e]

[msg MSG_017_0_0 [Junpei Iori]]
[f 2 1][bup 3 2 65535 65535 0 0][vp 1 0 0 17 0 0]¡No me digas que tú también! Tendríamos que estar pensando en... ¡Bueno, en otras cosas que no son comida![n][w][e]

[msg MSG_018_0_0 [Junpei Iori]]
[f 2 1][bup 3 6 65535 65535 0 0][vp 1 0 0 18 0 0]Ja, ja, ja... Por cierto, Akihiko, no te sobrará un poco, ¿no?[n][w][e]

[msg MSG_019_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 19 0 0]Nada de comer hasta que hayas avanzado algo. Concéntrate, [nl]. No quiero verte soltar el lápiz.[n][w][e]

[msg MND_020_0_0]
[f 2 1]El embriagador olor a bol de ternera[n]me ha motivado aún más.[n][w][e]

[msg MSG_021_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 1 0 0 20 0 0]¡Ternera, ternera, terneeera![n][w][e]

[msg MSG_022_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 6 65535 65535 0 0][vp 1 0 0 21 0 0]Madre mía... Vale, si respondes bien cinco preguntas más, puedes comer.[n][w][e]

[msg MSG_023_0_0 [Junpei Iori]]
[f 2 1][bup 3 8 65535 65535 0 0][vp 1 0 0 22 0 0]¡Jiaaaaa! ¡Ternera, ternera, terneeera![n][w][e]

[msg MSG_024_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 6 65535 65535 0 0][vp 1 0 0 23 0 0]Eres como un burro con anteojeras...[n][w][e]

[msg MSG_025_0_0 [Yukari Takeba]]
[f 2 1][bup 2 6 65535 65535 0 0][vp 1 0 0 24 0 0]Es mencionar comida y mandas todo a tomar por saco. Mira que eres débil, ¿eh?[n][w][e]

[msg MSG_026_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 25 0 0]Muy bien, ya hemos terminado por hoy. Procurad no comer mucho antes de dormir.[n][w][e]

