[msg MSG_000_0_0 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 1 0 0 1 0 0]Gracias por acompañarme, [nl].[n][w][e]
[f 2 1][bup 8 0 65535 65535 0 0][vp 1 0 0 2 0 0]Y perdona por haberte preocupado.[n][w][e]

[msg MSG_001_0_0 [Ken Amada]]
[f 2 1][bup 8 3 65535 65535 0 0][vp 1 0 0 3 0 0]No hemos hablado en condiciones desde lo que le pasó a Shinjiro.[n][w][e]

[msg MSG_002_0_0 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 1 0 0 4 0 0]No dejo de pensar en lo último que me dijo.[n][w][e]
[f 2 1][bup 8 0 65535 65535 0 0][vp 1 0 0 5 0 0]Mi vida tengo que vivirla yo, pero ¿cómo lo hago?[n][w][e]

[msg MSG_003_0_0 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 1 0 0 6 0 0]Como no sabía por dónde empezar, he probado varias cosas.[n][w][e]
[f 2 1][bup 8 3 65535 65535 0 0][vp 1 0 0 7 0 0][f 4 23 0 8 3 25 25]Cosas que antes ni me habría planteado.[n][w][e]
[f 2 1][bup 8 0 65535 65535 0 0][vp 1 0 0 8 0 0][f 4 23 0 8 0 25 25]Como pasar tiempo con mis amigos en el insti, leer mangas e incluso ver la tele.[n][w][e]

[msg MSG_004_0_0 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 1 0 0 9 0 0]Y me estoy esforzando por hablar más con la gente de la resi.[n][w][e]
[f 2 1][bup 8 0 65535 65535 0 0][vp 1 0 0 10 0 0]Mitsuru me ayudó con los deberes el otro día. ¡Y le gané a Junpei en un videojuego![n][w][e]
[f 2 1][bup 8 0 65535 65535 0 0][vp 1 0 0 11 0 0]También comí chuches con Yukari y los demás, y Aigis me ayudó a darle de comer a Hamburguesa.[n][w][e]

[msg MSG_005_0_0 [Ken Amada]]
[f 2 1][bup 8 1 65535 65535 0 0][vp 1 0 0 12 0 0]Me he dado cuenta de que esas pequeñas cosas amenizan la vida.[n][w][e]
[f 2 1][bup 8 1 65535 65535 0 0][vp 1 0 0 13 0 0]Eso es lo que he aprendido.[n][w][e]

[sel SEL_006_0_0 top]
[f 2 1]Con eso me basta y me sobra.[e]
[f 2 1]Sigue así.[e]
[f 2 1]A la próxima, invitas tú.[e]

[msg MSG_007_0_0 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 1 0 0 14 0 0]Cierto. Más adelante quizá pruebe más cosas, pero...[n][w][e]
[f 2 1][bup 8 1 65535 65535 0 0][vp 1 0 0 15 0 0][f 4 23 0 8 1 25 25]De momento, creo que he aprendido a sentirme vivo.[n][w][e]

[msg MSG_008_0_0 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 1 0 0 16 0 0]Sí. Y no pienso ceñirme a eso, quiero probar a hacer otras cosas.[n][w][e]
[f 2 1][bup 8 1 65535 65535 0 0][vp 1 0 0 17 0 0][f 4 23 0 8 1 25 25]De momento, creo que he aprendido a sentirme vivo.[n][w][e]

[msg MSG_009_0_0 [Ken Amada]]
[f 2 1][bup 8 1 65535 65535 0 0][vp 1 0 0 18 0 0]¡Claro! Hay que repetir y volver a comer ramen juntos.[n][w][e]
[f 2 1][bup 8 1 65535 65535 0 0][vp 1 0 0 19 0 0]El último que nos comimos estaba para morirse.[n][w][e]

[msg MSG_010_0_0 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 1 0 0 20 0 0]¿Sabes qué? En la resi hablan mucho de ti, [nl].[n][w][e]
[f 2 1][bup 8 1 65535 65535 0 0][vp 1 0 0 21 0 0][f 4 23 0 8 1 25 25]Y encima hablan con alegría.[n][w][e]
[f 2 1][bup 8 0 65535 65535 0 0][vp 1 0 0 22 0 0][f 4 23 0 8 0 25 25]Aunque los combates sean duros, creo que el motivo por el que seguimos adelante...[n][w][e]

[msg MSG_011_0_0 [Ken Amada]]
[f 2 1][bup 8 1 65535 65535 0 0][vp 1 0 0 23 0 0]Es porque sabemos que, cuando volvamos, seguirás aquí para apoyarnos.[n][w][e]

[sel SEL_012_0_0 top]
[f 2 1]Qué exagerado.[e]
[f 2 1]Ojalá.[e]
[f 2 1]¿A ti te parece bien?[e]

[msg MSG_013_0_0 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 1 0 0 24 0 0]¿Tú crees? Bueno, yo me siento así.[n][w][e]
[f 2 1][bup 8 0 65535 65535 0 0][vp 1 0 0 25 0 0]Nos guías y nos infundes valor.[n][w][e]

[msg MSG_014_0_0 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 1 0 0 26 0 0]Seguro que sí. Eres más que una líder en combate.[n][w][e]
[f 2 1][bup 8 0 65535 65535 0 0][vp 1 0 0 27 0 0]Te preocupas por nosotros y por nuestro bienestar.[n][w][e]

[msg MSG_015_0_0 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 1 0 0 28 0 0]Sí. No sé explicarme bien, pero...[n][w][e]
[f 2 1][bup 8 0 65535 65535 0 0][vp 1 0 0 29 0 0]Creo que tú me ves tal y como soy.[n][w][e]

[msg MSG_016_0_0 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 1 0 0 30 0 0]Quiero parecerme a ti, [nl].[n][w][e]
[f 2 1][bup 8 0 65535 65535 0 0][vp 1 0 0 31 0 0]Permíteme que te acompañe para aprender a ser como tú.[n][w][e]

[msg MSG_017_0_0 [Ken Amada]]
[f 2 1][bup 8 3 65535 65535 0 0][vp 1 0 0 32 0 0]En fin, perdona por tardar tanto. Hace fresco esta noche.[n][w][e]
[f 2 1][bup 8 1 65535 65535 0 0][vp 1 0 0 33 0 0][f 4 23 0 8 1 25 25]¿Volvemos?[n][w][e]

[msg MND_018_0_0]
[f 2 1]De camino a la residencia, Amada te ha contado qué se trae entre manos.[n][w][e]
[f 2 1]Siento que mi [f 4 30 1 1 1 0] ha aumentado tras ser testigo de lo considerado que es Amada con Mitsuru.[n][w][e]

