[msg MSG_000_0_0 [Tendera de Octopia]]
[f 2 1][vp 3 0 65535 20101 0 0][f 5 21 1 103]¡Eh, jovencita, acércate![n][w][e]
[f 2 1][f 5 21 1 103]Mi takoyaki es barato y está de vicio. ¡Solo cuesta 400 yenes![n][w][e]
[f 2 1][vp 3 0 65535 20102 0 0][f 5 21 1 103]No tiene pulpo, pero... pruébalo de todas formas.[n][w][e]

[msg MSG_004_0_0 [Tendera de Octopia]]
[f 2 1][vp 3 0 65535 20105 0 0][f 5 21 1 103]¡Gracias! ¡Vuelve pronto![n][w][e]

[msg MND_010_0_0]
[f 2 1]Están las persianas bajadas.[n][w][e]

