[msg MSG_000_0_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 1 0 0 1 0 0]Bueno, ¿qué quieres?[n][w][e]

[msg MSG_001_0_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 1 0 0 2 0 0]¿Qué se supone que es esto?[n][w][e]

[msg MSG_002_0_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 4 65535 65535 0 0][vp 1 0 0 3 0 0]¿Por qué lo tenías tú?[n][w][e]
[f 2 1][bup 10 0 65535 65535 0 0][vp 0 0 0 4 0 0][f 4 23 0 1 1 25 25]...[n][w][e]
[f 2 1][bup 10 0 65535 65535 0 0][vp 1 0 0 5 0 0][f 4 23 0 1 0 25 25]Ah, ya. Te lo habrá pedido Mitsuru.[n][w][e]

[sel SEL_003_0_0 top]
[f 2 1]Sí, ha sido cosa suya.[e]
[f 2 1]Lo has pillado al vuelo.[e]

[msg MSG_004_0_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 1 0 0 6 0 0]Muy típico de ella. Se desvive por las mayores gilipolleces.[n][w][e]

[msg MSG_005_0_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 6 65535 65535 0 0][vp 1 0 0 7 0 0]No es la primera vez que recurre a esto. Sabía que el sobre me resultaría familiar.[n][w][e]

[msg MSG_006_0_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 1 0 0 8 0 0]Por una vez, piensa por ti misma, anda. No acates lo que dicten los demás.[n][w][e]

[sel SEL_007_0_0 top]
[f 2 1]Solo quería ayudar.[e]
[f 2 1]Yo también me preocupo por ti.[e]
[f 2 1]Lo siento.[e]

[msg MSG_008_0_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 3 65535 65535 0 0][vp 1 0 0 9 0 0]Aprende a decir que no.[n][w][e]
[f 2 1][bup 10 0 65535 65535 0 0][vp 1 0 0 10 0 0][f 4 23 0 1 0 25 25]Normal que acabaran nombrándote líder.[n][w][e]

[msg MSG_009_0_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 1 0 0 11 0 0]Métete en tus putos asuntos. ¿Por qué sois todos así?[n][w][e]
[f 2 1][bup 10 0 65535 65535 0 0][vp 1 0 0 12 0 0]Pero supongo que no puedes. Por eso aceptaste convertirte en líder.[n][w][e]

[msg MSG_010_0_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 1 0 0 13 0 0]No me extraña.[n][w][e]
[f 2 1][bup 10 1 65535 65535 0 0][vp 1 0 0 14 0 0][f 4 23 0 1 1 25 25]Tss, mira que eres rarita. Gracias a ti me han vuelto a engatusar.[n][w][e]

[msg MSG_011_0_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 0 0 0 15 0 0]...[n][w][e]
[f 2 1][bup 10 0 65535 65535 0 0][vp 1 0 0 16 0 0]¿Hemos acabado? Pues pírate.[n][w][e]

[msg MSG_012_0_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 1 0 0 17 0 0]Ey.[n][w][e]

[msg MSG_013_0_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 1 0 0 18 0 0]Gracias por tomarte tantas molestias.[n][w][e]
[f 2 1][bup 10 1 65535 65535 0 0][vp 1 0 0 19 0 0][f 4 23 0 1 1 25 25]A lo mejor te invito a comer algún día.[n][w][e]

[msg MSG_014_0_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 1 0 0 20 0 0]¿Te supone algún problema?[n][w][e]

[sel SEL_015_0_0 top]
[f 2 1]¿Por qué no ahora?[e]
[f 2 1]¿Todavía no vuelves a casa?[e]

[msg MSG_016_0_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 6 65535 65535 0 0][vp 1 0 0 21 0 0]Te he dicho que te vayas. Ya tengo planes.[n][w][e]

[msg MSG_017_0_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 6 65535 65535 0 0][vp 1 0 0 22 0 0]A tí qué te importa. No preguntes tonterías.[n][w][e]

[msg MSG_018_0_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 1 0 0 23 0 0]Qué más dará. Volveré esta noche.[n][w][e]
[f 2 1][bup 10 0 65535 65535 0 0][vp 1 0 0 24 0 0]Por eso he vuelto al equipo.[n][w][e]

[msg MSG_019_0_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 3 65535 65535 0 0][vp 1 0 0 25 0 0]Tss...[n][w][e]

[msg MND_020_0_0]
[f 2 1]He decidido volver a la residencia sin Shinjiro.[n][w][e]
[f 2 1]Le he entregado la carta a Aragaki sin que me intimide. Siento que mi [f 4 30 2 1 1 0] ha aumentado.[n][w][e]

