[msg MND_000_0_0]
[f 2 1]牛乳やスポーツドリンクが入っている。[n][f 1 5 0]誰かの買い置きだろうか…[n][w][e]

[msg MND_002_0_0]
[f 2 1]La nevera está hasta arriba de comida e ingredientes.[n][w][e]

[msg MND_066_0_0]
[f 2 1]Parece que mi [f 4 4 1 37 1 0] no cabe.[n][w][e]

[msg MND_013_0_0]
[f 2 1]No hay nada mío dentro.[n][w][e]

[msg MND_NEXT_EMPTY]
[f 2 1]Hay una nota dentro de la nevera.[n][w][e]
[f 2 1]"Próxima limpieza: [clr 2][f 2 4 2]/[f 2 4 1][clr 27]". Puede que después haya espacio dentro.[n][w][e]

[msg MND_003_0_0]
[f 2 1]Queda un poco de espacio.[n][w][e]

[msg MND_009_0_0]
[f 2 1]Mi [f 4 4 1 37 1 0] está enfriándose dentro.[n][w][e]

[msg MND_004_0_0]
[f 2 1]No tengo nada que quiera enfriar.[n][w][e]

[msg MND_008_0_0]
[f 2 1]Ahora que lo pienso, tengo [f 4 4 1 37 1 0].[n][w][e]
[f 2 1]¿Debería usar la nevera para que se enfríe?[n][w][e]

[sel SEL_010_0_0 top]
[f 2 1]Enfriar[e]
[f 2 1]Ahora no[e]

[msg MND_011_0_0]
[f 2 1]He metido mi [f 4 4 1 37 1 0] en la nevera.[n][w][e]

[msg MND_012_0_0]
[f 2 1]Debería recogerse [clr 2]mañana o más adelante[clr 27].[n][w][e]

[msg MND_TAIYAKI_GET]
[f 2 1]El [f 4 4 1 37 1 0] que puse antes dentro ya se ha enfriado lo suficiente.[n][w][e]

[msg MND_MYSTERYFOOD_GET]
[f 2 1]¡¿...?![n][w][e]
[f 2 1]El taiyaki que metí en la nevera hace tiempo está completamente cambiado.[n][w][e]

[msg MND_MYSTERYFOOD_GET2]
[f 2 1]Parece que lo dejé en la nevera demasiado tiempo. La próxima vez tendré más cuidado.[n][w][e]

[msg MND_GET_0601_0616]
[f 2 1]El taiyaki que puse antes dentro ha desaparecido.[n][w][e]
[f 2 1]Han colocado una nota en el lugar donde dejé el taiyaki.[n][w][e]

[msg MSG_GET2_0601_0616 [Nota]]
[f 2 1]A quien sea que se dejó el taiyaki aquí... Lo siento, no pude evitarlo.[n][w][e]
[f 2 1]¡La he cagado! Te lo cambio por unos fideos instantáneos.[n]-Junpei[n][w][e]

[msg MND_GET_0617_0630]
[f 2 1]El taiyaki que puse antes dentro ha desaparecido.[n][w][e]
[f 2 1]Hay una nota en su lugar. Me parece que es del director.[n][w][e]

[msg MSG_GET2_0617_0630 [Carta de Ikutsuki]]
[f 2 1]Querida [nl]:[n]Siento haberme comido tu taiyaki.[n][w][e]
[f 2 1]Había comprado justo el mismo, pero olvidé dónde lo dejé.[n][w][e]
[f 2 1]Te compraré otro. Hasta entonces, acepta esto como disculpa.[n][w][e]
[f 2 1]P.D.[n]Espero que mi gusto por el taiyaki no te resulte... SOS-PEZ-OSO.[n][w][e]

[msg MND_GET_0730_0802]
[f 2 1]El taiyaki que puse antes dentro se ha enfriado.[n][w][e]
[f 2 1]Hay algo con una nota adhesiva al lado del taiyaki.[n][w][e]

[msg MSG_GET2_0730_0802 [Nota adhesiva]]
[f 2 1]Para [nl]: ¡Por esforzarte tanto en las actividades del club! -Yukari[n][w][e]

[msg MND_GET3_0730_0802]
[f 2 1]Es de Yukari. Aceptaré encantada.[n][w][e]

[msg MND_GET_0914_0926]
[f 2 1]El taiyaki que puse antes dentro ha desaparecido.[n][w][e]
[f 2 1]Han colocado una nota en el lugar donde dejé el taiyaki.[n][w][e]

[msg MSG_GET2_0914_0926 [Nota]]
[f 2 1]Para [nl]: Lo siento, me he comido tu taiyaki. Pensaba que era para mí.[n][w][e]
[f 2 1]Toma esto a cambio. -Sanada[n][w][e]

[msg MND_GET_0927_1025]
[f 2 1]El taiyaki que puse antes dentro se ha enfriado.[n][w][e]
[f 2 1]A su lado hay unos aperitivos con una nota pegada.[n][w][e]

[msg MSG_GET2_0927_1025 [Nota]]
[f 2 1]Me han regalado esto. Que coja quien quiera.[n]-Aragaki[n][w][e]

[msg MND_GET3_0927_1025]
[f 2 1]Parece que no son de nadie. Me llevaré uno por el momento.[n][w][e]

[msg MND_GET_1026_1111]
[f 2 1]El taiyaki que puse antes dentro ha desaparecido.[n][w][e]
[f 2 1]En su lugar, han dejado una nota.[n][w][e]

[msg MSG_GET2_1026_1111 [Nota]]
[f 2 1]Me he zampado el taiyaki. Seguro que era tuyo, ¿no, [nf]?[n][w][e]
[f 2 1]¡Es la hostia para quitar el antojo de noche! Gracias por enfriarlo para mí.[n][w][e]
[f 2 1]Es coña. Siento habérmelo ventilado. Toma esto y estamos en paz, ¿vale? -Junpei[n][w][e]

[msg MND_GET_1224_1225]
[f 2 1]El taiyaki que puse antes dentro se ha enfriado.[n][w][e]
[f 2 1]Hay una tarjeta metida debajo.[n][w][e]

[msg MSG_GET2_1224_1225 [Tarjeta]]
[f 2 1]Querida [nl]: Feliz Navidad de parte de Amada.[n][w][e]
[f 2 1]Coge chocolate si te apetece.[n][w][e]
[f 2 1]Se lo dieron a Koromaru en el santuario. Pero como los perros no pueden comerlo...[n][w][e]
[f 2 1]Me pareció que Koromaru quería que fuera para ti, así que hala.[n][w][e]
[f 2 1](Yo también he pillado).[n][w][e]

[msg MND_GET3_1224_1225]
[f 2 1]Lo aceptaré encantada.[n][w][e]

[msg MND_GET_0110_0121]
[f 2 1]El taiyaki que puse antes dentro se ha enfriado.[n][w][e]
[f 2 1]Hay una cesta con una nota al lado del taiyaki.[n][w][e]

[msg MSG_GET2_0110_0121 [Nota]]
[f 2 1]A todos los residentes:[n]Podéis coger una si os apetece.[n][w][e]
[f 2 1]Me las regaló un conocido cuando iba a hacer los exámenes de acceso a la universidad.[n][w][e]
[f 2 1]No olvidéis beber agua en vuestras sesiones de estudio. -Mitsuru[n][w][e]

[msg MND_GET3_0110_0121]
[f 2 1]La cesta contiene bebidas embotelladas.[n][w][e]
[f 2 1]Aceptaré una encantada.[n][w][e]

[msg MND_GET_0122_0131]
[f 2 1]El taiyaki que puse antes dentro se ha enfriado.[n][w][e]
[f 2 1]Hay un gran número de [f 4 4 1 37 1 1] al lado.[n][w][e]

[msg MSG_GET_0122_0131 [Nota]]
[f 2 1]Hola a todos:[n]Esto es para vosotros.[n][w][e]
[f 2 1]¡Superaremos el 31 de enero cueste lo que cueste![n]-Fuuka[n][w][e]

[msg MND_GET3_0122_0131]
[f 2 1]Aceptaré una encantada.[n][w][e]

[msg MND_068_0_0]
[f 2 1]A ver si me acuerdo de dárselo a Elizabeth [clr 2]mañana o más adelante[clr 27].[n][w][e]

[msg MND_069_0_0]
[f 2 1]Ahora que lo pienso, Elizabeth dijo que quería taiyaki frío.[n][w][e]
[f 2 1]Debería llevarle este [f 4 4 1 37 1 1].[n][w][e]

