[msg MSG_000_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 1 65535 65535 0 0][vp 1 0 0 1 0 0]¡[nl]! ¡Aquí![n][w][e]
[f 2 1][bup 109 0 65535 65535 0 0][vp 1 0 0 2 0 0][f 4 22 0 109 25 25 20]¿Te puedes creer que haya sido capaz de soltar todo eso en la sala de profesores? ¡Hasta a mí me sorprende un poco![n][w][e]
[f 2 1][bup 109 0 65535 65535 0 0][vp 1 0 0 3 0 0]Ha sido increíble... Je, je.[n][w][e]
[f 2 1][bup 109 1 65535 65535 0 0][vp 1 0 0 4 0 0][f 4 23 0 109 1 25 25][f 4 22 0 109 31 25 20]¡Je, je, je![n][w][e]

[sel SEL_001_0_0 top]
[f 2 1]¿Qué mosca te ha picado?[e]
[f 2 1]Así que eras la culpable.[e]

[msg MSG_002_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 1 65535 65535 0 0][vp 1 0 0 5 0 0][f 5 13 9 5 109]Venga... ¡Déjame fanfarronear un rato! Je, je, ja, ja, ja...[n][w][e]

[msg MSG_003_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 3 65535 65535 0 0][vp 1 0 0 6 0 0]¡No, qué va![n][w][e]

[msg MSG_004_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 1 65535 65535 0 0][vp 1 0 0 7 0 0]¿Recuerdas cuando le dije a la presidenta que no podía permitirlo? Je, je...[n][w][e]

[msg MSG_004_5_0 [Chihiro Fushimi]]
[f 2 1][bup 109 0 65535 65535 0 0][vp 1 0 0 8 0 0]Es que al pensar que la presidenta y tú ibais a estar solas en una habitación...[n][w][e]
[f 2 1][bup 109 0 65535 65535 0 0][vp 1 0 0 9 0 0]Me cabreé mucho solo de imaginármelo.[n][w][e]

[msg MND_005_0_0]
[f 2 1]Chihiro esboza una sonrisa alentadora.[n][w][e]
[f 2 1]Siento que nuestra relación se ha fortalecido.[n][w][e]

[msg MSG_006_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 1 65535 65535 0 0][vp 1 0 0 10 0 0]De pequeña ya era así. O, al menos, eso dice mi madre.[n][w][e]
[f 2 1][bup 109 1 65535 65535 0 0][vp 1 0 0 11 0 0]Normalmente soy muy tímida y callada, pero cuando algo me importa de verdad, saco las garras.[n][w][e]

[msg MSG_006_5_0 [Chihiro Fushimi]]
[f 2 1][bup 109 0 65535 65535 1 0][vp 1 0 0 12 0 0]Es que yo...[n][w][e]

[msg MSG_007_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 0 65535 65535 0 0][vp 1 0 0 13 0 0]Mmm, [nl]...[n][w][e]
[f 2 1][bup 109 0 65535 65535 0 0][vp 1 0 0 14 0 0][f 4 22 0 109 25 25 20]Tengo... Tengo que decirte algo.[n][w][e]

[msg MSG_008_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 0 65535 65535 0 0][vp 1 0 0 15 0 0]De hecho, llevo un tiempo queriendo decírtelo, pero no lograba armarme de valor.[n][w][e]
[f 2 1][bup 109 0 65535 65535 0 0][vp 1 0 0 16 0 0]Creo que ahora sí puedo.[n][w][e]

[msg MND_010_0_0]
[f 2 1]Debería tener mucho cuidado con lo que digo.[n][w][e]

[msg MND_011_0_0]
[f 2 1]Debería tener mucho cuidado con lo que digo.[n][w][e]
[f 2 1]Ahora que lo pienso, [clr 2]ya tengo una relación especial[clr 27][n][clr 2]con otra persona[clr 27]...[n][w][e]

[msg MSG_009_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 0 65535 65535 0 0][vp 1 0 0 17 0 0][nl], y-yo...[n][w][e]
[f 2 1][bup 109 1 65535 65535 0 0][vp 1 0 0 18 0 0][f 4 23 0 109 1 25 25]¡Te quiero![n][w][e]

[sel SEL_012_0_0 top]
[f 2 1]Yo siento lo mismo, Chihiro.[f 2 9 1 1 351][e]
[f 2 1]Me gusta trabajar contigo, pero...[e]

[msg MSG_013_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 4 65535 65535 0 0][vp 1 0 0 19 0 0]¿Eh? ¿Qué has dicho?[n][w][e]

[sel SEL_014_0_0 top]
[f 2 1]He dicho que siento lo mismo.[e]
[f 2 1]Te quiero.[e]

[msg MSG_015_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 1 65535 65535 1 0][vp 1 0 0 20 0 0]¡Ay, qué contenta estoy, [nl]![n][w][e]
[f 2 1][bup 109 1 65535 65535 1 0][vp 1 0 0 21 0 0]Parece algo más propio de un sueño.[n][w][e]
[f 2 1][bup 109 1 65535 65535 1 0][vp 1 0 0 22 0 0][f 4 22 0 109 53 25 20]Mmm, eh... Espero que sigamos llevándonos bien.[n][w][e]

[msg MND_016_0_0]
[f 2 1]He entablado una relación especial[n]con Chihiro.[n][w][e]

[msg MND_017_0_0]
[f 2 1]Ya no hay marcha atrás.[n][w][e]

[msg MSG_018_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 0 65535 65535 0 0][vp 1 0 0 23 0 0]¡Ah! Todavía tengo que pedirle disculpas a la presidenta.[n][w][e]
[f 2 1][bup 109 1 65535 65535 0 0][vp 1 0 0 24 0 0][f 4 22 0 109 24 25 21][f 4 23 0 109 1 25 25]Mmm, ¿puedes esperarme en la puerta del instituto?[n][w][e]
[f 2 1][bup 109 1 65535 65535 1 0][vp 1 0 0 25 0 0]Me gustaría que volviéramos juntas a casa...[n][w][e]

[msg MND_019_0_0]
[f 2 1]Tras hablar con Mitsuru, volvimos juntas a casa.[n][w][e]
[f 2 1]Al final he vuelto a casa[n]un poco más tarde de lo normal.[n][w][e]

[msg MSG_020_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 10 65535 65535 0 0][vp 1 0 0 26 0 0]A-ah, ya veo...[n][w][e]

[msg MSG_021_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 3 65535 65535 0 0][vp 1 0 0 27 0 0]Mmm...[n][w][e]
[f 2 1][bup 109 3 65535 65535 0 0][vp 1 0 0 28 0 0]Entonces, ¿crees que podríamos seguir siendo amigas?[n][w][e]

[sel SEL_022_0_0 top]
[f 2 1]Faltaría más.[e]
[f 2 1]Sí, amigas.[e]

[msg MSG_023_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 0 65535 65535 0 0][vp 1 0 0 29 0 0]Menos mal...[n][w][e]
[f 2 1][bup 109 0 65535 65535 0 0][vp 1 0 0 30 0 0]Me alegra que ahora tengamos una relación más estrecha.[n][w][e]

[msg MSG_024_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 1 65535 65535 0 0][vp 1 0 0 31 0 0]¡Ah! Todavía tengo que pedirle disculpas a la presidenta.[n][w][e]

[msg MSG_024_3_0 [Chihiro Fushimi]]
[f 2 1][bup 109 10 65535 65535 0 0][vp 1 0 0 32 0 0]Creo que le debo una explicación... Perdona.[n][w][e]

[msg MND_025_0_0]
[f 2 1]Me he despedido de Chihiro y he vuelto sola a la residencia.[n][w][e]

