[msg MND_GoodEnd_0303]
[f 2 1]...Todo está en silencio.[n][w][e]
[f 2 1]No parece que los[n]demás hayan vuelto todavía.[n][w][e]
[f 2 1]Estarán disfrutando de[n]un atardecer pacífico...[n][w][e]
[f 2 1]......[n][w][e]
[f 2 1]Solamente he ido al instituto hoy, pero[n]mi cuerpo entero se siente lento y pesado...[n][w][e]
[f 2 1]Apenas puedo tener los ojos abiertos...[n][w][e]
[f 2 1]Debería irme temprano a la cama esta noche.[n][w][e]

[msg MND_GoodEnd_0304]
[f 2 1]......[n][w][e]
[f 2 1]Estoy agotada...[n][w][e]
[f 2 1]No puedo tener los ojos abiertos...[n][w][e]
[f 2 1]La ceremonia de graduación[n]de los de tercero es mañana.[n][w][e]
[f 2 1]Debería irme temprano a la cama hoy.[n][w][e]

[msg MSG_WELCOME_YUKARI_OUT [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 3 0 65535 1019 0 0]Ah, eh... Hola.[n][w][e]

[msg MSG_WELCOME_YUKARI_OUT2 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 3 0 65535 1012 0 0]Eh... Hola...[n][w][e]

[msg MSG_WELCOME_JUNPEI_OUT [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2018 0 0]¿Qué pasa, tía?[n][w][e]

[msg MSG_WELCOME_JUNPEI_OUT2 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2012 0 0]Hola, tía...[n][w][e]

[msg MSG_WELCOME_MITSURU_OUT [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4018 0 0]Hola de nuevo.[n][w][e]

[msg MSG_WELCOME_MITSURU_OUT2 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4027 0 0]Hola de nuevo...[n][w][e]

[msg MSG_WELCOME_SANADA_OUT [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 3 0 65535 3017 0 0]Anda, has vuelto.[n][w][e]

[msg MSG_WELCOME_FUKA_OUT [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5018 0 0]Hola, ¿qué tal el día?[n][w][e]

[msg MSG_WELCOME_FUKA_OUT2 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5028 0 0]Ah... Hola...[n][w][e]

[msg MSG_WELCOME_AEGIS_OUT_RO [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 3 0 65535 6018 0 0]Saludos.[n][w][e]

[msg MSG_WELCOME_AEGIS_OUT [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6018 0 0]Saludos.[n][w][e]

[msg MSG_WELCOME_AEGIS_OUT_NA [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6017 0 0]Hola otra vez. Me alegro de volver a verte.[n][w][e]

[msg MSG_WELCOME_KOROMARU_OUT [Koromaru]]
[f 2 1][bup 9 0 65535 65535 0 0][vp 3 0 65535 8008 0 0]¡Guau![n][w][e]

[msg MSG_WELCOME_AMADA_OUT [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 3 0 65535 7020 0 0]¡Anda, hola![n][w][e]

[msg MSG_WELCOME_AMADA_OUT2 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 3 0 65535 7012 0 0]Ah... Hola...[n][w][e]

[msg MSG_WELCOME_ARAGAKI_OUT [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 3 0 65535 9014 0 0]Ey...[n][w][e]

[msg MSG_WELCOME_IKUTSUKI_OUT [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 3 0 65535 14201 0 0]Hola de nuevo.[n][w][e]

[msg MSG_WELCOME_YUKARI_IN [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 3 0 65535 1067 0 0]¡Ah, estás aquí![n][w][e]

[msg MSG_WELCOME_YUKARI_IN2 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 3 0 65535 1012 0 0]Ah, ¿ya has llegado? Perdona, no te había visto.[n][w][e]

[msg MSG_WELCOME_JUNPEI_IN [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2009 0 0]Eh, ¿qué pasa?[n][w][e]

[msg MSG_WELCOME_JUNPEI_IN2 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2012 0 0]Ah, hola...[n][w][e]

[msg MSG_WELCOME_MITSURU_IN [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4029 0 0]¿Eh? Ah, eres tú...[n][w][e]

[msg MSG_WELCOME_MITSURU_IN2 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4027 0 0]¿Mmm? Ah, ya estás aquí.[n][w][e]

[msg MSG_WELCOME_SANADA_IN [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 3 0 65535 3024 0 0]¿Has estado en tu habitación todo este tiempo?[n][w][e]

[msg MSG_WELCOME_FUKA_IN [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5067 0 0]¡Ah, hola! No sabía que ya estabas aquí.[n][w][e]

[msg MSG_WELCOME_FUKA_IN2 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5093 0 0]Anda, ¿estás aquí? Hola...[n][w][e]

[msg MSG_WELCOME_FUKA_IN_0712 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5067 0 0]Ah, [nl]...[n][w][e]

[msg MSG_WELCOME_AEGIS_IN_ROB [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 3 0 65535 6008 0 0]Buenas tardes.[n][w][e]

[msg MSG_WELCOME_AEGIS_IN [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6008 0 0]Buenas tardes.[n][w][e]

[msg MSG_WELCOME_AEGIS_IN_NAK [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6009 0 0]¿Qué tal el día? ¿Todo bien?[n][w][e]

[msg MSG_WELCOME_KOROMARU_IN [Koromaru]]
[f 2 1][bup 9 0 65535 65535 0 0][vp 3 0 65535 8001 0 0]¡Guau, guau![n][w][e]

[msg MSG_WELCOME_AMADA_IN [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 3 0 65535 7010 0 0]¿Has estudiado algo?[n][w][e]

[msg MSG_WELCOME_AMADA_IN2 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 3 0 65535 7012 0 0]¿Estabas aquí? Pues... hola.[n][w][e]

[msg MSG_WELCOME_ARAGAKI_IN [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 3 0 65535 9056 0 0]... ¿Qué hay?[n][w][e]

[msg MSG_WELCOME_IKUTSUKI_IN [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 3 0 65535 14204 0 0]Ah, no sabía que ya estabas aquí. He venido a hacer una visita rápida.[n][w][e]

[msg MND_SHYUKAKU_OK]
[f 2 1]Ahora que lo pienso, las hortalizas que planté en la azotea ya se podrán recolectar.[n][w][e]
[f 2 1]Debería ir a echarles un ojo...[n][w][e]

[msg MND_SHYUKAKU_TAIYAKI_OK]
[f 2 1]Ahora que lo pienso, las hortalizas que planté en la azotea ya se podrán recolectar.[n][w][e]
[f 2 1]Y el taiyaki que metí en la nevera también debería estar frío.[n][w][e]
[f 2 1]Debería ir a echarles un ojo...[n][w][e]

[msg MND_SHYUKAKU_TAIYAKI_OK_]
[f 2 1]Ahora que lo pienso, las hortalizas que planté en la azotea ya se podrán recolectar.[n][w][e]
[f 2 1]Y el taiyaki que metí en la nevera también debería estar frío.[n][w][e]
[f 2 1]Debería sacarlo de la nevera y dárselo a Elizabeth.[n][w][e]

[msg MND_TAIYAKI_OK]
[f 2 1]Ahora que lo pienso, el taiyaki que metí en la nevera ya debería estar frío.[n][w][e]
[f 2 1]Debería ir a por él.[n][w][e]

[msg MND_TAIYAKI_OK_QUEST]
[f 2 1]Ahora que lo pienso, el taiyaki que metí en la nevera ya debería estar frío.[n][w][e]
[f 2 1]Debería sacarlo de la nevera y dárselo a Elizabeth.[n][w][e]

[msg MSG_ERROR [Shuji Ikutsuki]]
[f 2 1]エラーメッセージです。[n][f 1 5 0]杉山まで報告ください。[n][w][e]

