[msg MSG_001_0_0 [Hombre sudoroso]]
[f 2 1][f 5 21 1 693]¿Les estás ayudando a ligar con tías?[n][w][e]
[f 2 1][f 5 21 1 693]¡Pues vais de culo! Como no seáis más sutiles, vais a espantarlas a todas.[n][w][e]
[f 2 1][f 5 21 1 693]Yo también he venido con intenciones de agenciarme una novia. Eso nos convierte en rivales, ¿no?[n][w][e]

[msg MSG_004_0_0 [Hombre sudoroso]]
[f 2 1][f 5 21 1 693]Qué duras han sido esas tías... No deberíais discutir con ellas cuando se ponen así.[n][w][e]
[f 2 1][f 5 21 1 693]¡Limitaos a darles la razón y a colmarlas de elogios! Es una técnica primordial.[n][w][e]

[msg MSG_006_0_0 [Hombre sudoroso]]
[f 2 1][f 5 21 1 693]Pues ya tenía novio... Qué mala suerte la mía.[n][w][e]
[f 2 1]...[n][w][e]
[f 2 1][f 5 21 1 693]Han dicho que tirarles la caña a las chicas en la playa es de cutres.[n][w][e]

[msg MSG_008_0_0 [Hombre sudoroso]]
[f 2 1][f 5 21 1 693]Hala, ¿te has echado novia?[n][w][e]
[f 2 1][f 5 21 1 693]¡¿Cómo has hecho llorar a esa muñeca?! ¡Corre, ve tras ella![n][w][e]

