[msg MSG_000_0_0 [Hombre sospechoso]]
[f 2 1][vp 3 0 65535 20603 0 0][f 5 21 1 105]Mmm... Este foro es totalmente fascinante.[n][w][e]
[f 2 1][f 5 21 1 105]¿Eh? ¿A ti también te interesa la dark web?[n][w][e]
[f 2 1][f 5 21 1 105]Recopilo información de distintas personas sobre páginas y foros "interesantes".[n][w][e]
[f 2 1][f 5 21 1 105]Si quieres, puedo venderte información, incluso muy confidencial.[n][w][e]

[msg MSG_001_0_0 [Hombre sospechoso]]
[f 2 1][vp 3 0 65535 20602 0 0][f 5 21 1 105]Je, veo que eres bastante curiosa. No te cortes, echa un ojo.[n][w][e]

[msg MSG_002_0_0 [Hombre sospechoso]]
[f 2 1][vp 3 0 65535 20604 0 0][f 5 21 1 105]Gracias. Me voy en busca de más información exquisita.[n][w][e]

[msg MSG_003_0_0 [Hombre sospechoso]]
[f 2 1][vp 3 0 65535 20606 0 0][f 5 21 1 105]Hasta otro día...[n][w][e]

[msg MSG_004_0_0 [Hombre sospechoso]]
[f 2 1][vp 3 0 65535 20605 0 0][f 5 21 1 105]Perdona, esta noche me pillas ocupado. Vuelve en otro momento, ¿vale?[n][w][e]

[msg MSG_005_0_0 [Hombre sospechoso]]
[f 2 1]¿Mm? ¿Qué quieres?[n][w][e]
[f 2 1]Agallas no te faltan para venir sola a un lugar como este.[n][w][e]
[f 2 1]Yo encantado de venderte información sobre páginas "poco convencionales", pero...[n][w][e]
[f 2 1]¿Tienes ordenador personal? Te hará falta para acceder a mis servicios.[n][w][e]

[msg MND_006_0_0]
[f 2 1]Puedo conseguir información[n]de páginas poco convencionales aquí.[n][w][e]
[f 2 1][clr 2]Si puedo usar un ordenador en la residencia[clr 27],[n]podría examinar estas páginas web.[n][w][e]

