[msg MSG_SANADA_TARTAROS_0801 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0]He oído que mañana vas a participar en la competición esa. Tienes que darlo todo para ganar.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0]Aunque correrás contra un tal "Hayase", y dicen que va a arrasar con la competencia.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0]Estate atenta contra él.[n][w][e]

[msg MSG_JUNPEI_TARTAROS_0801 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2067 0 0]Ah, sí, he oído hablar de él...[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Es un tío muy famoso, le he visto en revistas de deportes.[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]¿Acaso qué sentido tiene intentar enfrentarse a tipos como él? Lo único que consigues es desgastarte...[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Pero bueno, en poco cae una luna llena, así que puedes tratar esto como un entrenamiento o algo.[n][w][e]

[msg MSG_MITSURU_TARTAROS_080 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0]Akihiko me ha hablado de que te ha ido bien en la competición.[n][w][e]

[sel SEL_003_0_0 top]
[f 2 1]No es para tanto.[e]
[f 2 1]Qué pena no haber ganado.[e]

[msg MSG_MITSURU_TARTAROS_080_2 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4031 0 0]De todas formas, estoy impresionada con tu habilidad para equilibrar tantos aspectos de tu vida.[n][w][e]

[msg MSG_YUKARI_TARTAROS_0802 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 3 0 65535 1107 0 0]Eso es, [nl], ¡eres increíble! Deberías darte algo más de crédito.[n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0]Aunque sea por estar haciendo algo con tu vida, no como alguien que yo me sé.[n][w][e]

[msg MSG_JUNPEI_TARTAROS_0802 [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0][vp 3 0 65535 2041 0 0]Ya, ya, a palabras necias, oídos... em, eso...[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]El caso, ya casi es luna nueva, ¿no?[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]¡Eso es "algo" que sé como hacer! ... Me refiero a la misión.[n][w][e]

[msg MSG_SANADA_TARTAROS_0802 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 3 0 65535 3027 0 0]Correcto, la siguiente luna llena será el 6 de agosto, que cae en jueves.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0]Es probable que este enemigo sea más fuerte que los anteriores. Asegúrate de estar preparada.[n][w][e]

[msg MSG_FUKA_TARTAROS_0803 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0]Este jueves habrá luna llena.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Estoy segura de que aparecerá algún tipo de Sombra fuerte.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Queda poco tiempo, así que por favor, prepárate bien.[n][w][e]

[msg MSG_JUNPEI_TARTAROS_0804 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0]Con que pasado mañana toca luna llena, ¿eh?[n][w][e]
[f 2 1][bup 3 9 65535 65535 0 0]¡Qué ganas que tengo ya! ¡Lo vamos a petar![n][w][e]

[msg MSG_YUKARI_0805_1 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0]Pues mañana es luna llena...[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0]¿Cómo te ves, [nl]?[n][w][e]

[sel SEL_011_0_0 top]
[f 2 1]¡Más lista que nunca![e]
[f 2 1]Estoy algo nerviosa...[e]

[msg MSG_YUKARI_0805_RE_1 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 3 0 65535 1025 0 0]¡Qué bien! ¡Yo también![n][w][e]

[msg MSG_YUKARI_0805_RE_2 [Yukari Takeba]]
[f 2 1][bup 2 3 65535 65535 0 0][vp 3 0 65535 1122 0 0]Ya, siempre da algo de cosa...[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0]Pero siempre se puede contar contigo en estas situaciones, así que tengo poco que temer.[n][w][e]

[msg MSG_YUKARI_0805_2 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0]Pero bueno, además de estar listas mentalmente, también tenemos que estarlo físicamente.[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0]Mañana nos quedaremos en la residencia a la espera, así que reunamos todo lo que necesitemos esta noche.[n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0]¡Venga, va! ¡Vamos a por todas, como siempre![n][w][e]

[msg MSG_MITSURU_TARTAROS_080_3 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4024 0 0]Estaba hablando sobre Koromaru con los demás.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Va a necesitar que lo saquen a pasear, pero tampoco es prudente encargar a una persona en concreto.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Sería muy conveniente que pudieras [clr 2]sacar a Koromaru a pasear de noche, cuando parezca que quiera salir[clr 27].[n][w][e]

[msg MSG_YUKARI_0815_1 [Yukari Takeba]]
[f 2 1][bup 2 3 65535 65535 0 0][vp 3 0 65535 1114 0 0]Por fin se acaban las clases de verano, pero... ¿no te da la sensación de que hemos tirado las vacaciones de verano?[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0]Tendré que hacer muchos planes para compensar. Me pregunto si habrá algo interesante...[n][w][e]

[msg MSG_AEGIS_0815_1 [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 3 0 65535 6080 0 0]Puedo recomendar ir al [clr 2]festival de verano[clr 27] mañana y al [clr 2]festival del cine[clr 27] el día siguiente.[n][w][e]

[msg MSG_YUKARI_0815_2 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 3 0 65535 1067 0 0]Ah, es verdad. Un momento, Aigis, ¿tienes pensado ir a los festivales?[n][w][e]

[msg MSG_AEGIS_0815_2 [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 3 0 65535 6024 0 0]Correcto. Mis datos indican que los festivales y otros eventos similares ofrecen experiencias únicas.[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0]Por tanto, mi intención es infiltrarme a dichos "jolgorios" con fines de investigación.[n][w][e]

[msg MSG_YUKARI_0815_3 [Yukari Takeba]]
[f 2 1][bup 2 3 65535 65535 0 0][vp 3 0 65535 1028 0 0]Vaaale... Tú intenta no destacar demasiado.[n][w][e]

[msg MSG_YUKARI_0817_1 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0]Qué calooor... Odio este tiempo...[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0]¿Tú como vas, [nl]?[n][w][e]

[sel SEL_016_0_0 top]
[f 2 1]¡Mejor que nunca![e]
[f 2 1]No puedo más...[e]

[msg MSG_YUKARI_0817_RE_1 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 3 0 65535 1104 0 0]Ah, ¿en serio? ¡Pues sí que estás aprovechando el verano![n][w][e]

[msg MSG_YUKARI_0817_RE_2 [Yukari Takeba]]
[f 2 1][bup 2 6 65535 65535 0 0][vp 3 0 65535 1114 0 0]Sí, ¿eh? Este calor es de lo peor... Estoy agotada con tan solo estar sentada...[n][w][e]

[msg MSG_YUKARI_0817_2 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0]A ver si puedo dejar de pensar en el calor. Veamos... la siguiente luna llena será en septiembre, justo al volver de vacaciones...[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0]Ains... Dicho así parece que me estoy preparando para un examen o algo así...[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0]Pero bueno, solo quedan cuatro Sombras... Hay que aguantar un pelín más.[n][w][e]

[msg MSG_MITSURU_TARTAROS_081 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0]Las vacaciones de verano se acabarán en poco menos de dos semanas.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Por supuesto, la lucha contra las Sombras es prioritaria, pero tampoco te olvides de estudiar.[n][w][e]

[msg MSG_JUNPEI_TARTAROS_0819 [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0]Jope, qué calor...[n][w][e]
[f 2 1][bup 3 3 65535 65535 0 0]Estoy sudando como un pollo, tío...[n][w][e]

[msg MSG_MITSURU_TARTAROS_081_2 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4032 0 0]Sé fuerte, Iori. El calor sólo te puede afectar si lo permites.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][f 4 25 5]......[n][w][e]
[f 2 1][bup 5 3 65535 65535 0 0]...Aunque cierto es, que esa teoría tiene sus límites.[n][w][e]

[msg MSG_JUNPEI_TARTAROS_0819_2 [Junpei Iori]]
[f 2 1][bup 3 6 65535 65535 0 0][vp 3 0 65535 2111 0 0]Uf...[n][w][e]

[msg MSG_AEGIS_TARTAROS_0821_ [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0]La próxima luna llena será el día 5 de septiembre.[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0]Esto significa que disponemos de aproximadamente dos semanas hasta la próxima misión.[n][w][e]

[msg MSG_JUNPEI_TARTAROS_0821 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2072 0 0]Oye, Ai, ¿te apetece organizar una "misión" para ir a por helados?[n][w][e]

[msg MSG_AEGIS_TARTAROS_0821__2 [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 3 0 65535 6066 0 0]Mis informes indican que el consumo de helado puede suponer un riesgo para la salud que puede comprometer nuestras próximas operaciones.[n][w][e]

[msg MSG_JUNPEI_TARTAROS_0821_2 [Junpei Iori]]
[f 2 1][bup 3 4 65535 65535 0 0][vp 3 0 65535 2037 0 0]Jolines, ¡vaya forma de arruinar el helado![n][w][e]

[msg MSG_AEGIS_TARTAROS_0822_ [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0]Me gustaría hacerte una pregunta.[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0]¿Por qué las escuelas cierran temporalmente durante el verano?[n][w][e]

[sel SEL_035_0_0 top]
[f 2 1]Porque hace calor.[e]
[f 2 1]Es una costumbre.[e]

[msg MSG_AEGIS_TARTAROS_0822__2 [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0]Ya veo.[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0]Una vez concluye el periodo de descanso, las clases reanudan.[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0][vp 3 0 65535 6142 0 0]Comprendo.[n][w][e]

[msg MSG_IKUTSUKI_TARTAROS_08 [Shuji Ikutsuki]]
[f 2 1][bup 222 6 65535 65535 0 0]Mmm... Como este patrón sea constante, los casos de Apatía volverán a aumentar de nuevo.[n][w][e]
[f 2 1][bup 222 6 65535 65535 0 0]Qué lástima, dado que son vuestras vacaciones... Pero las Sombras no descansan.[n][w][e]

[msg MSG_FUKA_TARTAROS_0824 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0]Una semana más para que se acaben las vacaciones de verano...[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0]Han sido muy movidas, pero no creo que haya tenido unas vacaciones tan satisfactorias como estas.[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0]Vamos a divertirnos estos últimos días, y tratar que el calor del verano no nos afecte demasiado.[n][w][e]

[msg MSG_FUKA_TARTAROS_0826 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0]Pues sí que hace calor dentro de la residencia...[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0]¿A lo mejor se hace más llevadero si nos imaginamos que es una sauna...?[n][w][e]

[msg MSG_SANADA_TARTAROS_0825 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0]Es un peñazo lidiar con este calor todos los días, pero en realidad viene muy bien para entrenar.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0]El sistema nervioso simpático se activa con el calor, y el flujo sanguíneo a los músculos aumenta.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0]Es ideal para entrenar. Si vas a la torre Tártaro, te acompaño.[n][w][e]

[msg MSG_SANADA_0825 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0]Es un peñazo lidiar con este calor todos los días, pero en realidad viene muy bien para entrenar.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0]El sistema nervioso simpático se activa con el calor, y los resultados de entrenar mejoran.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0]Estas condiciones son las ideales para entrenar en la torre Tártaro. ¿Qué te parece?[n][w][e]

[msg MSG_SANADA_OK_0825 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0]Es un peñazo lidiar con este calor todos los días, pero en realidad viene muy bien para entrenar.[n][w][e]
[f 2 1][bup 4 1 65535 65535 0 0]Creo que haré un rutina de alta intensidad esta noche.[n][w][e]

[msg MSG_AEGIS_TARTAROS_0829 [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0]Queda una semana para la luna llena. Además, los Perdidos aumentan en número.[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0]Recomiendo continuar monitorizando la situación, pendientes de cualquier irregularidad.[n][w][e]

[msg MSG_AMADA_TARTAROS_0830 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0]Estos días parece que están habiendo más... Son "los Perdidos", ¿si no me equivoco?[n][w][e]
[f 2 1][bup 8 0 65535 65535 0 0]No quiero ser imprudente, pero... Quiero hacer buen uso de mi poder.[n][w][e]

[msg MSG_MITSURU_TARTAROS_083 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0]La luna lucirá llena dentro de poco...[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Sé que no hace falta repetirlo a estas alturas pero, asegúrate de estar adecuadamente preparada.[n][w][e]

[msg MSG_YUKARI_TARTAROS_08 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0]En diez días se acaban las vacaciones, ¿no? Este año estábamos igual de ocupados que de normal...[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0]Aunque Junpei parece estar tan libre como de normal.[n][w][e]

[msg MSG_JUNPEI_TARTAROS_08 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0]No, no, estoy disfrutando de mi tiempo libre. Lo llaman "compostura de adulto".[n][w][e]

[msg MSG_YUKARI_TARTAROS_08_2 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0]Pues como tienes tanta "compostura", qué tal si terminas tus deberes de una vez...[n][w][e]

[msg MSG_JUNPEI_0822 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0]*suspiro* Me muero del aburrimiento...[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Tía, ¿tú qué dirías que es la mejor manera de "disfrutar" del tiempo libre?[n][w][e]

[sel SEL_038_0_0 top]
[f 2 1]Dormir.[e]
[f 2 1]Ponerse a currar.[e]

[msg MSG_JUNPEI_0822_RE_1 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2062 0 0]Esa es buena... Pero, en momentos como este, no me siento cansado.[n][w][e]

[msg MSG_JUNPEI_0822_RE_2 [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0][vp 3 0 65535 2114 0 0]¿En serio? ¡He dicho "disfrutar"![n][w][e]

[msg MSG_WELCOME_YUKARI_OUT [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 3 0 65535 1019 0 0]Ah, eh... Hola.[n][w][e]

[msg MSG_WELCOME_YUKARI_OUT2 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 3 0 65535 1012 0 0]Eh... Hola...[n][w][e]

[msg MSG_WELCOME_JUNPEI_OUT [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2018 0 0]¿Qué pasa, tía?[n][w][e]

[msg MSG_WELCOME_JUNPEI_OUT2 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2012 0 0]Hola, tía...[n][w][e]

[msg MSG_WELCOME_MITSURU_OUT [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4018 0 0]Hola de nuevo.[n][w][e]

[msg MSG_WELCOME_MITSURU_OUT2 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4027 0 0]Hola de nuevo...[n][w][e]

[msg MSG_WELCOME_SANADA_OUT [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 3 0 65535 3017 0 0]Anda, has vuelto.[n][w][e]

[msg MSG_WELCOME_FUKA_OUT [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5018 0 0]Hola, ¿qué tal el día?[n][w][e]

[msg MSG_WELCOME_FUKA_OUT2 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5028 0 0]Ah... Hola...[n][w][e]

[msg MSG_WELCOME_AEGIS_OUT_RO [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 3 0 65535 6018 0 0]Saludos.[n][w][e]

[msg MSG_WELCOME_AEGIS_OUT [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6018 0 0]Saludos.[n][w][e]

[msg MSG_WELCOME_AEGIS_OUT_NA [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6017 0 0]Hola otra vez. Me alegro de volver a verte.[n][w][e]

[msg MSG_WELCOME_KOROMARU_OUT [Koromaru]]
[f 2 1][bup 9 0 65535 65535 0 0][vp 3 0 65535 8008 0 0]¡Guau![n][w][e]

[msg MSG_WELCOME_AMADA_OUT [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 3 0 65535 7020 0 0]¡Anda, hola![n][w][e]

[msg MSG_WELCOME_AMADA_OUT2 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 3 0 65535 7012 0 0]Ah... Hola...[n][w][e]

[msg MSG_WELCOME_ARAGAKI_OUT [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 3 0 65535 9014 0 0]Ey...[n][w][e]

[msg MSG_WELCOME_IKUTSUKI_OUT [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 3 0 65535 14201 0 0]Hola de nuevo.[n][w][e]

[msg MSG_WELCOME_YUKARI_IN [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 3 0 65535 1067 0 0]¡Ah, estás aquí![n][w][e]

[msg MSG_WELCOME_YUKARI_IN2 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 3 0 65535 1012 0 0]Ah, ¿ya has llegado? Perdona, no te había visto.[n][w][e]

[msg MSG_WELCOME_JUNPEI_IN [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2009 0 0]Eh, ¿qué pasa?[n][w][e]

[msg MSG_WELCOME_JUNPEI_IN2 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2012 0 0]Ah, hola...[n][w][e]

[msg MSG_WELCOME_MITSURU_IN [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4029 0 0]¿Eh? Ah, eres tú...[n][w][e]

[msg MSG_WELCOME_MITSURU_IN2 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4027 0 0]¿Mmm? Ah, ya estás aquí.[n][w][e]

[msg MSG_WELCOME_SANADA_IN [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 3 0 65535 3024 0 0]¿Has estado en tu habitación todo este tiempo?[n][w][e]

[msg MSG_WELCOME_FUKA_IN [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5067 0 0]¡Ah, hola! No sabía que ya estabas aquí.[n][w][e]

[msg MSG_WELCOME_FUKA_IN2 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5093 0 0]Anda, ¿estás aquí? Hola...[n][w][e]

[msg MSG_WELCOME_FUKA_IN_0712 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5067 0 0]Ah, [nl]...[n][w][e]

[msg MSG_WELCOME_AEGIS_IN_ROB [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 3 0 65535 6008 0 0]Buenas tardes.[n][w][e]

[msg MSG_WELCOME_AEGIS_IN [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6008 0 0]Buenas tardes.[n][w][e]

[msg MSG_WELCOME_AEGIS_IN_NAK [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6009 0 0]¿Qué tal el día? ¿Todo bien?[n][w][e]

[msg MSG_WELCOME_KOROMARU_IN [Koromaru]]
[f 2 1][bup 9 0 65535 65535 0 0][vp 3 0 65535 8001 0 0]¡Guau, guau![n][w][e]

[msg MSG_WELCOME_AMADA_IN [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 3 0 65535 7010 0 0]¿Has estudiado algo?[n][w][e]

[msg MSG_WELCOME_AMADA_IN2 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 3 0 65535 7012 0 0]¿Estabas aquí? Pues... hola.[n][w][e]

[msg MSG_WELCOME_ARAGAKI_IN [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 3 0 65535 9056 0 0]... ¿Qué hay?[n][w][e]

[msg MSG_WELCOME_IKUTSUKI_IN [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 3 0 65535 14204 0 0]Ah, no sabía que ya estabas aquí. He venido a hacer una visita rápida.[n][w][e]

[msg MND_SHYUKAKU_OK]
[f 2 1]Ahora que lo pienso, las hortalizas que planté en la azotea ya se podrán recolectar.[n][w][e]
[f 2 1]Debería ir a echarles un ojo...[n][w][e]

[msg MND_SHYUKAKU_TAIYAKI_OK]
[f 2 1]Ahora que lo pienso, las hortalizas que planté en la azotea ya se podrán recolectar.[n][w][e]
[f 2 1]Y el taiyaki que metí en la nevera también debería estar frío.[n][w][e]
[f 2 1]Debería ir a echarles un ojo...[n][w][e]

[msg MND_SHYUKAKU_TAIYAKI_OK_]
[f 2 1]Ahora que lo pienso, las hortalizas que planté en la azotea ya se podrán recolectar.[n][w][e]
[f 2 1]Y el taiyaki que metí en la nevera también debería estar frío.[n][w][e]
[f 2 1]Debería sacarlo de la nevera y dárselo a Elizabeth.[n][w][e]

[msg MND_TAIYAKI_OK]
[f 2 1]Ahora que lo pienso, el taiyaki que metí en la nevera ya debería estar frío.[n][w][e]
[f 2 1]Debería ir a por él.[n][w][e]

[msg MND_TAIYAKI_OK_QUEST]
[f 2 1]Ahora que lo pienso, el taiyaki que metí en la nevera ya debería estar frío.[n][w][e]
[f 2 1]Debería sacarlo de la nevera y dárselo a Elizabeth.[n][w][e]

[msg MSG_ERROR [Shuji Ikutsuki]]
[f 2 1]エラーメッセージです。[n][f 1 5 0]杉山まで報告ください。[n][w][e]

