[msg MSG_Strong_01_Mituru [Mitsuru Kirijo]]
[f 2 1][bup 5 2 65535 50 0 0][vp 3 0 65535 4102 0 0]¡Espera![n][w][e]
[f 2 1][bup 5 2 65535 50 0 0]Hay un enemigo cerca, pero...[n][w][e]

[msg MSG_Strong_01_Mituru_02 [Mitsuru Kirijo]]
[f 2 1][bup 5 2 65535 50 0 0]Esa juega en otra liga. Es muy diferente a las sombras normales y corrientes que hay por esta zona.[n][w][e]
[f 2 1][bup 5 2 65535 50 0 0]Va a ser un combate complicado. Si no confías en tus posibilidades, más vale que no te metas en peleas.[n][w][e]

[msg MSG_Strong_01_Mituru_03 [Mitsuru Kirijo]]
[f 2 1][bup 5 2 65535 50 0 0]Si tenemos que entrar en combate, siempre podemos retirarnos.[n][w][e]
[f 2 1][bup 5 2 65535 50 0 0]Necesitamos una líder capaz de tomar decisiones racionales para que no acabemos en apuros.[n][w][e]

[msg MSG_Strong_01_Fuka [Fuuka Yamagishi]]
[f 2 1][bup 6 2 65535 50 0 0][vp 3 0 65535 5072 0 0]¡Espera...![n][w][e]
[f 2 1][bup 6 2 65535 50 0 0]Percibo un enemigo cerca, pero...[n][w][e]

[msg MSG_Strong_01_Fuka_02 [Fuuka Yamagishi]]
[f 2 1][bup 6 2 65535 50 0 0]Esta sombra parece un poco más fuerte que las demás de la zona.[n][w][e]
[f 2 1][bup 6 2 65535 50 0 0]Será una batalla complicada, así que si crees que no puedes con ella, intenta evitar el combate.[n][w][e]

[msg MSG_Strong_01_Fuka_03 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 50 0 0]Si te ves superada en combate, te recomiendo que te retires cuanto antes.[n][w][e]
[f 2 1][bup 6 0 65535 50 0 0]Y, lo que es más importante, no tomes decisiones a lo loco. Necesitamos que tengas la mente fría.[n][w][e]

