[msg MSG_000_0_0 [Alumno perezoso]]
[f 2 1][f 5 21 1 317]Toda la gente que conozco está en algún club, pero...[n][w][e]
[f 2 1][f 5 21 1 317]Yo no tengo ganas de unirme a ninguno.[n][w][e]
[f 2 1][f 5 21 1 317]Dicen que haría muchos amigos y toda la pesca...[n][w][e]
[f 2 1][f 5 21 1 317]Pero me da igual.[n][w][e]

[msg MSG_001_0_0 [Alumno perezoso]]
[f 2 1][f 5 21 1 317]No entiendo por qué la gente está perdiendo la cabeza con esas historias de fantasmas.[n][w][e]
[f 2 1][f 5 21 1 317]Es decir, ir por el instituto pegando gritos y propagando rumores... A ver si maduran.[n][w][e]
[f 2 1][f 5 21 1 317]A ver si maduran.[n][w][e]

[msg MSG_002_0_0 [Alumno perezoso]]
[f 2 1][f 5 21 1 317]Ya falta poco para las vacaciones de verano.[n][w][e]
[f 2 1][f 5 21 1 317]De pequeño me encantaban...[n][w][e]
[f 2 1][f 5 21 1 317]Pero ahora, como que me dan igual. Ya no me hacen ilusión.[n][w][e]

[msg MSG_003_0_0 [Alumno perezoso]]
[f 2 1][f 5 21 1 317]Que si el festival cultural esto, que si el festival cultural lo otro...[n][w][e]
[f 2 1][f 5 21 1 317]¡A toooodos les encanta el festival cultural![n][w][e]
[f 2 1][f 5 21 1 317]Pero a mí no, colega. Creo que es una pérdida de tiempo.[n][w][e]
[f 2 1][f 5 21 1 317]Ojalá viniera un tifón y lo cancelaran.[n][w][e]
[f 2 1][f 5 21 1 317]Bueno, quizá me estoy pasando un poco...[n][w][e]

[msg MSG_004_0_0 [Alumno perezoso]]
[f 2 1][f 5 21 1 317]¡¿Q-qué?! ¡No he hecho nada malo![n][w][e]

[sel SEL_005_0_0 top]
[f 2 1]Yo no he dicho eso.[e]
[f 2 1]Vale.[e]
[f 2 1]¡Con que fuiste tú![e]

[msg MSG_006_0_0 [Alumno perezoso]]
[f 2 1][f 5 21 1 317]¿Eh? ¿N-no has venido por... eso?[n][w][e]
[f 2 1][f 5 21 1 317]¡Menudo susto![n][w][e]

[msg MSG_007_0_0 [Alumno perezoso]]
[f 2 1][f 5 21 1 317]Eso es. Nadie tiene por qué saberlo.[n][w][e]

[msg MSG_008_0_0 [Alumno perezoso]]
[f 2 1][f 5 21 1 317]Sí..., es verdad que deseé lo del tifón.[n][w][e]
[f 2 1][f 5 21 1 317]Hasta colgué muñecos de vudú del revés y les clavé agujas en la cabeza.[n][w][e]
[f 2 1][f 5 21 1 317]Pero ¡nunca pensé que fuera a pasar de verdad! ¡Fue un accidente![n][w][e]
[f 2 1][f 5 21 1 317]¡No es culpa mía![n][w][e]

[msg MSG_009_0_0 [Alumno perezoso]]
[f 2 1][f 5 21 1 317]Tío, Mitsuru es la leche.[n][w][e]
[f 2 1][f 5 21 1 317]Su padre acaba de morir y aun así se planta en una reunión para decidir el futuro del Grupo Kirijo.[n][w][e]
[f 2 1][f 5 21 1 317]Es increíble lo aplicada que es.[n][w][e]
[f 2 1][f 5 21 1 317]Ojalá pudiera ser así. Bah... ¿A quién quiero engañar? Me encanta hacer el vago.[n][w][e]

[msg MSG_010_0_0 [Alumno perezoso]]
[f 2 1][f 5 21 1 317]Colega, ¿de qué van en lo de las jornadas de experiencia profesional?[n][w][e]
[f 2 1][f 5 21 1 317]Me hicieron llevar cajas de cartón de aquí para allá todo el día...[n][w][e]
[f 2 1][f 5 21 1 317]Los brazos me están matando.[n][w][e]

[msg MSG_011_0_0 [Alumno perezoso]]
[f 2 1][f 5 21 1 317]Mmm... No tengo ganas de hacer nada.[n][w][e]

[sel SEL_012_0_0 top]
[f 2 1]Ni yo.[e]
[f 2 1]Ponte las pilas, anda.[e]

[msg MSG_013_0_0 [Alumno perezoso]]
[f 2 1][f 5 21 1 317]Sabes a qué me refiero, ¿verdad?[n][w][e]
[f 2 1][f 5 21 1 317]Ahora todo me parece una enorme pérdida de tiempo... Creo que el mundo debería terminarse y ya.[n][w][e]

[msg MSG_014_0_0 [Alumno perezoso]]
[f 2 1][f 5 21 1 317]Es que menuda flojera... ¿Cómo lo hacéis?[n][w][e]

[msg MSG_015_0_0 [Alumno perezoso]]
[f 2 1][f 5 21 1 317]Mientras apruebes los exámenes, todo irá bien.[n][w][e]
[f 2 1][f 5 21 1 317]Yo nunca estudio porque soy demasiado vago.[n][w][e]

[msg MSG_016_0_0 [Alumno perezoso]]
[f 2 1][f 5 21 1 317]La última vez que estuve en el centro comercial, vi a un tío que tenía un estilo muy salvaje.[n][w][e]
[f 2 1][f 5 21 1 317]Llevaba el pelo largo y ondulado, iba sin camiseta y tenía tatuajes en los brazos.[n][w][e]
[f 2 1][f 5 21 1 317]Hacía un poco de calor para la época en la que estamos, pero creo que se pasó...[n][w][e]
[f 2 1][f 5 21 1 317]En fin, quizá sea mejor hacerse notar.[n][w][e]
[f 2 1][f 5 21 1 317]Ojalá fuera como él y me importara un comino lo que piense la gente de mí.[n][w][e]

[msg MSG_017_0_0 [Alumno perezoso]]
[f 2 1][f 5 21 1 317]Últimamente, todo el mundo está haciendo amigos. No sé yo... Me parece que cuesta mucho esfuerzo.[n][w][e]
[f 2 1][f 5 21 1 317]Sé que tener amigos tiene su lado bueno, pero...[n][w][e]
[f 2 1][f 5 21 1 317]Ojalá pudiera hacerlo sin todo ese rollo de "conectar", ¿me sigues?[n][w][e]

[msg MSG_018_0_0 [Alumno perezoso]]
[f 2 1][f 5 21 1 317]Puf, cada vez estoy más vago.[n][w][e]
[f 2 1][f 5 21 1 317]¿Y si tengo la apatía esa?[n][w][e]

[sel SEL_019_0_0 top]
[f 2 1]A mí no me lo parece.[e]
[f 2 1]Quizá.[e]
[f 2 1]Que te mejores.[e]

[msg MSG_020_0_0 [Alumno perezoso]]
[f 2 1][f 5 21 1 317]Ya, supongo que será flojera normal y corriente.[n][w][e]

[msg MSG_021_0_0 [Alumno perezoso]]
[f 2 1][f 5 21 1 317]O-oye, que era broma. No te lo tomes tan en serio.[n][w][e]

[msg MSG_022_0_0 [Alumno perezoso]]
[f 2 1][f 5 21 1 317]O-oye, solo estaba bromeando.[n][w][e]

[msg MSG_023_0_0 [Alumno perezoso]]
[f 2 1][f 5 21 1 317]Los días de calor como hoy hay que ir al manga café. Se está fresquito y puedes leer lo que quieras.[n][w][e]
[f 2 1][f 5 21 1 317]También tienen ordenadores para navegar por internet.[n][w][e]
[f 2 1][f 5 21 1 317]Ah, por cierto... A veces veo a un tipo raro allí.[n][w][e]
[f 2 1][f 5 21 1 317]Siempre está aporreando las teclas de su pequeño portátil y hablando entre dientes.[n][w][e]
[f 2 1][f 5 21 1 317]Además, siempre va con un maletín. ¿Será un agente de bolsa o algo así?[n][w][e]

[msg MSG_024_0_0 [Alumno perezoso]]
[f 2 1][f 5 21 1 317]¿No crees que la ciudad es un caos últimamente?[n][w][e]

[sel SEL_025_0_0 top]
[f 2 1]Sin duda.[e]
[f 2 1]¿De verdad?[e]
[f 2 1]A mí me gusta así.[e]

[msg MSG_026_0_0 [Alumno perezoso]]
[f 2 1][f 5 21 1 317]¿A que sí? Y hay un montón de raritos...[n][w][e]
[f 2 1][f 5 21 1 317]Ya de por sí soy un flojeras, pero creo que cada vez voy a ir a más.[n][w][e]

[msg MSG_027_0_0 [Alumno perezoso]]
[f 2 1][f 5 21 1 317]Te lo digo yo...[n][w][e]

[msg MSG_028_0_0 [Alumno perezoso]]
[f 2 1][f 5 21 1 317]Tú estás mal de la chaveta. ¿Te ha pasado algo malo?[n][w][e]

[msg MSG_029_0_0 [Alumno perezoso]]
[f 2 1][f 5 21 1 317]Ya han empezado las clases... Qué flojera.[n][w][e]
[f 2 1][f 5 21 1 317]¿Que por qué? No necesito ningún motivo para que me dé flojera. Todos están así después de las vacas.[n][w][e]
[f 2 1][f 5 21 1 317]Te lo juro.[n][w][e]

[msg MSG_030_0_0 [Alumno perezoso]]
[f 2 1]He oído que un tío se hizo amigo de algunos empleados. ¿No te parece una pérdida de tiempo?[n][w][e]
[f 2 1][f 5 21 1 317]A mí no me incomoda ser el cliente. No necesito ser su amigo también.[n][w][e]
[f 2 1][f 5 21 1 317]En fin, seguro que tiene su parte buena, pero... la verdad es que paso.[n][w][e]
[f 2 1][f 5 21 1 317]Es demasiado lío para mí.[n][w][e]

[msg MSG_031_0_0 [Alumno perezoso]]
[f 2 1][f 5 21 1 317]Fíjate en esto. Vagos por todas partes.[n][w][e]
[f 2 1][f 5 21 1 317]¿Qué se les pasará por la cabeza? Supongo que nada.[n][w][e]
[f 2 1][f 5 21 1 317]Qué envidia me dan. Me gustaría ser como ellos.[n][w][e]
[f 2 1][f 5 21 1 317]Ya soy vago de narices, ¡así que tengo la ventaja de conseguir dejar la mente totalmente en blanco![n][w][e]

[msg MSG_032_0_0 [Alumno perezoso]]
[f 2 1][f 5 21 1 317]Se ven un montón de parejas en las vacaciones de verano, ¿eh?[n][w][e]
[f 2 1][f 5 21 1 317]A lo mejor debería echarme novia. Aunque me da una pereza terrible.[n][w][e]
[f 2 1][f 5 21 1 317]Justo antes vi a una pareja discutiendo y la chica estaba en plan...[n][w][e]
[f 2 1][f 5 21 1 317]"¡Voy a escribir sobre ti en la web de venganza!".[n][w][e]
[f 2 1][f 5 21 1 317]¿De qué estaría hablando?[n][w][e]

[msg MSG_033_0_0 [Alumno perezoso]]
[f 2 1][f 5 21 1 317]Ay, qué vago soy...[n][w][e]
[f 2 1][f 5 21 1 317]Adivina por qué.[n][w][e]

[sel SEL_034_0_0 top]
[f 2 1]¿Ha empezado el segundo trimestre?[e]
[f 2 1]Por el calor.[e]
[f 2 1]Tienes apatía.[e]
[f 2 1]Ni idea.[e]

[msg MSG_035_0_0 [Alumno perezoso]]
[f 2 1][f 5 21 1 317]Eso es. Cómo me conoces.[n][w][e]

[msg MSG_036_0_0 [Alumno perezoso]]
[f 2 1][f 5 21 1 317]Bueno, eso también.[n][w][e]
[f 2 1][f 5 21 1 317]Pero sobre todo es porque sigo en modo vacaciones de verano.[n][w][e]

[msg MSG_037_0_0 [Alumno perezoso]]
[f 2 1][f 5 21 1 317]Anda, no digas eso. No estoy tan mal.[n][w][e]

[msg MSG_038_0_0 [Alumno perezoso]]
[f 2 1][f 5 21 1 317]Jo, vaya cortarrollos. Ahora estoy aún más desganado.[n][w][e]

[msg MSG_039_0_0 [Alumno perezoso]]
[f 2 1][f 5 21 1 317]Ese Aragaki murió en el punto de encuentro de las bandas, ¿no?[n][w][e]
[f 2 1][f 5 21 1 317]A veces vago sin rumbo fijo y acabo ahí, pero...[n][w][e]
[f 2 1][f 5 21 1 317]Debería dejar de hacerlo.[n][w][e]

[msg MSG_040_0_0 [Alumno perezoso]]
[f 2 1][f 5 21 1 317]A los que creen en el Fin al menos les queda algo de energía.[n][w][e]
[f 2 1][f 5 21 1 317]Quiero decir, tienen la suficiente para creer en algo, ¿me sigues?[n][w][e]
[f 2 1][f 5 21 1 317]Yo ni siquiera tengo eso. Estoy acabado.[n][w][e]

