[sel SEL_TALK top]
[f 2 1]Vayamos juntos.[e]
[f 2 1]Mantente a la espera por ahora.[e]
[f 2 1]Deja que me lo piense...[e]

[sel SEL_BACK_UP_00 top]
[f 2 1]Consultar progreso[e]
[f 2 1]Da igual[e]

[sel SEL_PARTY top]
[f 2 1]Yukari[e]
[f 2 1]Aigis[e]
[f 2 1]Mitsuru[e]
[f 2 1]Junpei[e]
[f 2 1]Sanada[e]
[f 2 1]Amada[e]
[f 2 1]Aragaki[e]
[f 2 1]Koromaru[e]
[f 2 1]Mantente a la espera por ahora.[e]

[sel SEL_DOOR top]
[f 2 1]Introducir[e]
[f 2 1]No entrar[e]

[sel SEL_BACK_UP_01 top]
[f 2 1]Consultar el estado de todos[e]
[f 2 1]Da igual[e]

[sel SEL_BACK_UP_02 top]
[f 2 1]Preguntar por el objetivo[e]
[f 2 1]Da igual[e]

[sel SEL_BACK_UP_03 top]
[f 2 1]Consultar el estado de todos[e]
[f 2 1]Ir al Escapade[e]
[f 2 1]Un momento[e]

[sel SEL_BACK_UP_04 top]
[f 2 1]Consultar el estado de todos[e]
[f 2 1]Dirigirse a la estación[e]
[f 2 1]Un momento[e]

[sel SEL_BACK_UP_05 top]
[f 2 1]Consultar el estado de todos[e]
[f 2 1]Comenzar la operación[e]
[f 2 1]Un momento[e]

[msg MSG_JUNPEI_PARTY_IN_00 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0]Sabes que necesitas mi ayuda. ¿Todo listo para empezar?[n][w][e]

[msg MSG_JUNPEI_PARTY_IN_AFTE [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0]Vale, ¡vamos al lío![n][w][e]

[msg MSG_JUNPEI_PARTY_OUT_00 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0]Venga, ¡en marcha![n][w][e]

[msg MSG_JUNPEI_PARTY_OUT_AFT [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0]Ains. Vale, lo entiendo...[n][w][e]

[msg MSG_JUNPEI_PARTY_OVER_00 [Junpei Iori]]
[f 2 1][bup 3 4 65535 65535 0 0]Eh, ¿qué pasa? ¡Tienes el equipo completo![n][w][e]

[msg MSG_JUNPEI_PARTY_CHANGE_ [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0]Bueno, ¿a quién sustituyo?[n][w][e]

[msg MSG_JUNPEI_PARTY_CHANGE__2 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0]Bueno, ¿a quién sustituyo?[n][w][e]

[msg MSG_JUNPEI_PARTY_IN_AFTE_2 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0]¡Hecho, tía![n][w][e]

[msg MSG_JUNPEI_PARTY_OUT_AFT_2 [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0]Muy bien...[n][w][e]

[msg MSG_JUNPEI_PARTY_OUT_01 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2025 0 0]Vámonos, colega.[n][w][e]
[f 2 1][bup 3 4 65535 65535 0 0]Colega, ¡¿qué?! No soy un lastre..., ¿verdad?[n][w][e]

[msg MSG_JUNPEI_PARTY_OVER_01 [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0]El equipo está a tope, colega.[n][w][e]

[msg MSG_JUNPEI_TUTORIAL_BEFO [Junpei Iori]]
[f 2 1][bup 3 2 65535 65535 0 0][vp 3 0 65535 2118 0 0]Vale, ¡vamos al lío![n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]¡Demostraré que yo debería estar al mando![n][w][e]

[msg MSG_JUNPEI_TUTORIAL_AFTE [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0][vp 3 0 65535 2111 0 0]Colega, no aguanto más...[n][w][e]
[f 2 1][bup 3 3 65535 65535 0 0]Me muero de hambre...[n][w][e]

[msg MSG_JUNPEI_THEURGIA_BEFO [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2010 0 0]Tú dirás, chica.[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]¡Yo los contendré por aquí, así que venga, dales para el pelo![n][w][e]

[msg MSG_JUNPEI_PARTY_IN_AFTE_3 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0]¡Yo te cubro![n][w][e]

[msg MSG_JUNPEI_PARTY_OUT_AFT_3 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0]No te mueras, colega...[n][w][e]

[msg MSG_JUNPEI_PARTY_OVER_02 [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0]No hay hueco...[n][w][e]

[msg MSG_JUNPEI_PARTY_CHANGE__3 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0]¿Con quién quieres que me cambie?[n][w][e]

[msg MSG_JUNPEI_PARTY_IN_01 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2117 0 0]Muy bien... ¿Todo listo para que empiece el espectáculo?[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]¡Aquí tienes tu as en la manga![n][w][e]

[msg MSG_JUNPEI_PARTY_OUT_02 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2004 0 0]Cuando quieras.[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]¡Déjamelo a mí![n][w][e]

[msg MSG_JUNPEI_PARTY_IN_02 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0]Tsk... Si era tan listo, ¿por qué ha desperdiciado su vida de esa forma?[n][w][e]

[msg MSG_JUNPEI_PARTY_OUT_03 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0]Bueno, no tiene sentido comerse el coco tampoco... Vamos.[n][w][e]

[msg MSG_JUNPEI_PARTY_IN_03 [Junpei Iori]]
[f 2 1][bup 3 2 65535 65535 0 0][vp 3 0 65535 2129 0 0]Ahora nos toca ir a por ese mierda seca, ¿no? ¿Puedo ir contigo?[n][w][e]
[f 2 1][bup 3 2 65535 65535 0 0]Tengo asuntos pendientes con él...[n][w][e]

[msg MSG_JUNPEI_PARTY_OUT_04 [Junpei Iori]]
[f 2 1][bup 3 2 65535 65535 0 0][vp 3 0 65535 2129 0 0]Supongo que darle una paliza tampoco lo arreglaría todo, pero...[n][w][e]
[f 2 1][bup 3 2 65535 65535 0 0]En fin, tenemos que librarnos de él de una manera u otra. ¿Todo listo?[n][w][e]

[msg MSG_JUNPEI_PARTY_IN_04 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2117 0 0]Ha llegado el momento de la batalla definitiva.[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]¡Vamos a acabar por todo lo alto![n][w][e]

[msg MSG_JUNPEI_PARTY_OUT_05 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2132 0 0]Je, nos irá bien. Podemos hacerlo.[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]¡El cuarto bate, Junpei Iori, va a marcarse un tanto![n][w][e]

[msg MSG_JUNPEI_PARTY_IN_05 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0]Bueno, en marcha.[n][w][e]

[msg MSG_JUNPEI_PARTY_OUT_06 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0]¿Pasa algo? Venga, vamos.[n][w][e]

[msg MSG_JUNPEI_PARTY_IN_06 [Junpei Iori]]
[f 2 1][bup 3 2 65535 65535 0 0][vp 3 0 65535 2129 0 0]¿Qué cojones les pasa? Viniendo aquí con tanta chulería para darnos la brasa con su sermón...[n][w][e]
[f 2 1][bup 3 2 65535 65535 0 0]Desgraciados, ¡¿os creéis que nos da miedo que nos encierren?! En fin, ¡vamos allá![n][w][e]

[msg MSG_JUNPEI_PARTY_OUT_07 [Junpei Iori]]
[f 2 1][bup 3 4 65535 65535 0 0][vp 3 0 65535 2098 0 0]Eh, ¡estoy empezando a venirme arriba![n][w][e]

[msg MSG_JUNPEI_PARTY_OVER_03 [Junpei Iori]]
[f 2 1][bup 3 4 65535 65535 0 0]Venga ya... ¡que el grupo ya está a tope![n][w][e]

[msg MSG_JUNPEI_PARTY_CHANGE__4 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0]¿Por quién me cambio?[n][w][e]

[msg MSG_JUNPEI_PARTY_IN_07 [Junpei Iori]]
[f 2 1][bup 3 2 65535 65535 0 0][vp 3 0 65535 2129 0 0]Será la primera vez que vaya a un lugar así. Madre mía, tengo mariposas en el estómago...[n][w][e]

[msg MSG_JUNPEI_PARTY_IN_08 [Junpei Iori]]
[f 2 1][bup 3 2 65535 65535 0 0][vp 3 0 65535 2118 0 0]Empiezo a ver la luz al final del túnel... ¡Vamos a repartir leña![n][w][e]
[f 2 1][bup 3 4 65535 65535 0 0]Oye, ¿voy a estar en el equipo titular?[n][w][e]

[msg MSG_JUNPEI_PARTY_IN_09 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2062 0 0]Me pregunto qué se traerán entre manos Amada y Aragaki.[n][w][e]
[f 2 1][bup 3 4 65535 65535 0 0]Un momento, ¿crees que es su forma de decir que confían en mí y lo dejan todo en mis manos? Colega...[n][w][e]

[msg MSG_JUNPEI_PARTY_IN_10 [Junpei Iori]]
[f 2 1][bup 3 2 65535 65535 0 0][vp 3 0 65535 2118 0 0]Ya solo nos queda el grandullón, ¿eh?[n][w][e]
[f 2 1][bup 3 2 65535 65535 0 0]Muy bien, ¡ha llegado mi momento! ¡Nos llevaré de vuelta a casa![n][w][e]

[msg MSG_JUNPEI_PARTY_OUT_08 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2117 0 0]¡Venga![n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]¡Todo listo para subir a batear! ¡Manos a la obra![n][w][e]

[msg MSG_JUNPEI_PARTY_OUT_AFT_4 [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0]Bueno, vale... Pero será mejor que no pierdas, ¿eh?[n][w][e]

[msg MSG_JUNPEI_PARTY_OVER_04 [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0]Mujer, que no queda sitio.[n][w][e]

[msg MSG_JUNPEI_PARTY_CHANGE__5 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0]¿Quién me cambia el sitio?[n][w][e]

[msg MSG_JUNPEI_PARTY_OUT_TKJ [Junpei Iori]]
[f 2 1][bup 3 2 65535 65535 0 0][vp 3 0 65535 2129 0 0]No pienso darles cancha.[n][w][e]
[f 2 1][bup 3 4 65535 65535 0 0]Oye, no me irás a dejar en el banquillo, ¿no?[n][w][e]

[msg MSG_0425_0508_JUNPEI_DUN [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2095 0 0]Me importa un rábano de dónde vienen los enemigos. ¡Los machacaré uno a uno![n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]¡Cuenta conmigo![n][w][e]

[msg MSG_0510_0514_JUNPEI_DUN [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2062 0 0]Lo que ha ocurrido en el monorraíl ha sido una locura.[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Me dan ganas de escribir un guion para una serie de televisión, pero supongo que no puedo.[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Qué mierda... Habría sido un triunfazo.[n][w][e]

[msg MSG_0523_JUNPEI_DUNGE [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2066 0 0]Sanada ha vuelto.[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]¡Me alegro de que por fin haya aparecido un rival tan apuesto como yo![n][w][e]

[msg MSG_0602_0605_JUNPEI_DUN [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2066 0 0]¡"Junpei y sus historias para no dormir" es un exitazo! ¡No veas cómo ha ido subiendo su popularidad![n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Hasta durante el tórrido verano, ¡mis historias para no dormirte harán tiritar de miedo![n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Je, es broma.[n][w][e]

[msg MSG_0606_0607_JUNPEI_DUN [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2001 0 0]El tío que nos ha salvado, ese tal Aragaki, es una bestia, ¿eh?[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]¡Se ha cargado al enemigo de un cabezazo! Me la refanfinfla quien seas, ha sido brutal.[n][w][e]

[msg MSG_0613_JUNPEI_DUNGE [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2132 0 0]La delicadeza del esgrima de Kirijo y la voz tranquilizadora de Fuuka...[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]¡Son un verdadero oasis en el desierto![n][w][e]

[msg MSG_0623_0707_JUNPEI_DUN [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2095 0 0]¡Tachán! ¡Junpei ha subido de nivel![n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Ojalá pudiera decirlo unas cien veces al día.[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Cuanto más subo de nivel, ¡más molo![n][w][e]

[msg MSG_0709_0717_JUNPEI_DUN [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2011 0 0]¿Qué? ¿Ahora necesitas algo de mí?[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0][f 4 25 3]Tss...[n][w][e]

[msg MSG_0718_JUNPEI_DUNGE [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2088 0 0]Joder, ¡qué emoción lo de Yakushima![n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]Tengo tantas ganas que hasta la torre Tártaro se me empieza a parecer a la playa.[n][w][e]

[msg MSG_0724_JUNPEI_DUNGE [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2001 0 0]Ai es increíble...[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Es monísima, ¡y encima dispara balas con los dedos![n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Qué bien que esté de nuestro lado. No molaría tenerla como enemiga.[n][w][e]

[msg MSG_0725_0805_JUNPEI_DUN [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2062 0 0]Está claro que Amada es muy maduro para su edad.[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Pero, aun así, ¿no crees que Yukari le está tirando demasiadas flores?[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Ojalá me alabase a mí así de vez en cuando...[n][w][e]

[msg MSG_0806_0809_JUNPEI_DUN [Junpei Iori]]
[f 2 1][bup 3 6 65535 65535 0 0][vp 3 0 65535 2111 0 0]¡No me puedo creer que tengamos que ir a clases de verano![n][w][e]
[f 2 1][bup 3 3 65535 65535 0 0]Igual si me quedo en la torre Tártaro no tendré que ir...[n][w][e]

[msg MSG_0810_0820_JUNPEI_DUN [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2066 0 0]Ahora que Koromaru está de nuestro lado, ¡esto va a ser mejor si cabe![n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Con tanta gente en el grupo, ir a la torre Tártaro será más divertido ¡O eso espero![n][w][e]

[msg MSG_0821_0827_JUNPEI_DUN [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2129 0 0]Jo, las vacaciones de verano están a punto de acabarse...[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Bueno, al menos aún podemos crear buenos recuerdos en la torre Tártaro.[n][w][e]
[f 2 1][bup 3 6 65535 65535 0 0]¡Es algo que no todos pueden hacer![n][w][e]

[msg MSG_0828_0902_JUNPEI_DUN [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2062 0 0]Amada todavía está en primaria, pero tiene una determinación increíble. ¿No te parece una pasada?[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]En cambio, yo...[n][w][e]

[msg MSG_0903_0904_JUNPEI_DUN [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2001 0 0]Aragaki es mayor que nosotros y lleva más tiempo en SEES... Ah, ¡y también tiene más experiencia en lo de las Personas![n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Si me pidiera que le comprara pan de yakisoba, no podría negarme.[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]¿Pero y si me lo pide aquí? ¡Que en la torre Tártaro no hay pan de yakisoba![n][w][e]

[msg MSG_0906_0918_JUNPEI_DUN [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2062 0 0]Desde que empecé a hablar con Chidori, he estado dándole vueltas a la cabeza...[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Sabes... Nunca me había parado a pensar en cosas como la vida, la muerte y eso...[n][w][e]

[msg MSG_0919_1003_JUNPEI_DUN [Junpei Iori]]
[f 2 1][bup 3 2 65535 65535 0 0][vp 3 0 65535 2129 0 0]Esos tíos de Strega seguramente salgan durante la próxima luna llena, ¿no?[n][w][e]
[f 2 1][bup 3 2 65535 65535 0 0]No puedo perder... ni por mí ni por Chidori...[n][w][e]

[msg MSG_1005_1016_JUNPEI_DUN [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2093 0 0]Jamás aceptaría mi muerte con tanta facilidad.[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Aragaki es una pasada...[n][w][e]

[msg MSG_1019_1102_JUNPEI_DUN [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2004 0 0]Cuando la torre Tártaro desaparezca, lo primero que voy a hacer es ir a ver a Chidori.[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]Ja, ja, me siento como si fuese un héroe de un videojuego o algo así.[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]"Y después de derrotar al enemigo final, iré en busca de la dama en apuros". Je, je, je...[n][w][e]

[msg MSG_1106_1109_JUNPEI_DUN [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0][vp 3 0 65535 2004 0 0]Entonces, ¿Ikutsuki ha estado jugando con nosotros todo el tiempo?[n][w][e]
[f 2 1][bup 3 3 65535 65535 0 0]Cuanto más lo pienso, más odio la torre Tártaro...[n][w][e]

[msg MSG_1110_1117_JUNPEI_DUN [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2004 0 0]Joder, Kirijo tiene muy mal aspecto. Es como un cuerpo inerte...[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Pero me parece normal.[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Si yo perdiera a un ser querido, probablemente también estaría así.[n][w][e]

[msg MSG_1121_JUNPEI_DUNGE [Junpei Iori]]
[f 2 1][bup 3 6 65535 65535 0 0][vp 3 0 65535 2111 0 0]Sigo dolorido, colega... Kirijo no tenía por qué llegar tan lejos con su "ejecución".[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Después de eso, no deberíamos ni estar aquí esta noche. Nos estamos esforzando demasiado...[n][w][e]

[msg MSG_1121_JUNPEI_DUNGE_2 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2001 0 0]¿Le habrá pasado algo a Kirijo en el viaje escolar?[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]O sea, estaba deprimidísima, pero ahora está como una rosa.[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Bueno... me alegro de que por lo menos esté bien.[n][w][e]

[msg MSG_1122_1127_JUNPEI_DUN [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2004 0 0]Chidori me dio la vida...[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Ahora no es solo mía. He de cuidarla...[n][w][e]

[msg MSG_1203_1213_JUNPEI_DUN [Junpei Iori]]
[f 2 1][bup 3 2 65535 65535 0 0][vp 3 0 65535 2129 0 0]Joder, menudo bombazo nos ha soltado Ryoji, ¿eh?[n][w][e]
[f 2 1][bup 3 2 65535 65535 0 0]¿Que el mundo se va a acabar? ¿Cómo voy a aceptar eso...?[n][w][e]

[msg MSG_0101_0114_JUNPEI_DUN [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2066 0 0]Ai ha cambiado. No sé, ahora... se la ve más resplandeciente o algo así.[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Bueno, ¡yo todavía sigo mejorando! ¡Voy a subir de nivel como la espuma![n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Así que... ¡en marcha![n][w][e]

[msg MSG_0115_0130_JUNPEI_DUN [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2086 0 0]¡Esta es la última jugada![n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]¡Luchemos, subamos de nivel y mandemos a Nix al espacio exterior![n][w][e]

[msg MSG_0131_JUNPEI_DUNGE [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2062 0 0]Joder, supongo que esta es la última noche que te llamamos "líder", ¿no, [nf]?[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Sería complicado llamarte así fuera de la Tártaro. Seguro que nos mirarían raro en el insti.[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]Bueno, ¡no nos queda otra que buscarte un apodo nuevo a partir de mañana![n][w][e]

[msg MSG_TEST_JUNPEI_DUNGE [Junpei Iori]]
[f 2 1][bup 3 4 65535 65535 0 0][vp 3 0 65535 2102 0 0]¡Ni una palabra sobre los exámenes![n][w][e]
[f 2 1][bup 3 4 65535 65535 0 0]¡No quiero pensar en ellos mientras estoy en la torre Tártaro![n][w][e]

[msg MSG_HANYOU1_JUNPEI_DUNGE [Junpei Iori]]
[f 2 1][bup 3 6 65535 65535 0 0][vp 3 0 65535 2093 0 0]Aaaaaah, ¡qué hambre tengo![n][w][e]
[f 2 1][bup 3 6 65535 65535 0 0]La Tártaro... La tártara...La salsa tártara...[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Fua, menuda mierda...Me apetecen unas gambas fritas...[n][w][e]

[msg MSG_HANYOU2_JUNPEI_DUNGE [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2001 0 0]Ojalá hubiese una tienda de autoservicio en la torre Tártaro.[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]¡Podrían tener de todo y no nos preocuparíamos por pasar hambre![n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Ojalá el Grupo Kirijo montara una...[n][w][e]

[msg MSG_JUNPEI_ZEKKOCHO [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2088 0 0]Venid, sombritas... Tranquilas, que no muerdo.[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]¡Solo os haré picadillo![n][w][e]

