[msg MSG_SENDER_NAME]
[f 2 1]Kazushi Miyamoto[n][w][e]

[msg MSG_001_0_0]
[f 2 1]¡¡SOY MIYAMOTO!![n][w][e]

[msg MSG_002_0_0]
[f 2 1]Vas a entrenar, ¡¿verdad?! Estaré en el aula, ¡pégame un grito![n][w][e]

[msg MSG_003_0_0]
[f 2 1]RE: ¡¡SOY MIYAMOTO!![n][w][e]

[msg MSG_004_0_0]
[f 2 1]¡Vamos a entrenar! ¡Te demostraré de qué pasta estoy hecho![n][w][e]

[msg MSG_005_0_0]
[f 2 1]RE: RE: ¡¡SOY MIYAMOTO!![n][w][e]

[msg MSG_006_0_0]
[f 2 1]¡Hora de ir a entrenar! ¡No me dejes tirado![n][w][e]

[msg MSG_007_0_0]
[f 2 1]RE: RE: RE: ¡¡SOY MIYAMOTO!![n][w][e]

[msg MSG_008_0_0]
[f 2 1]¿Hoy vas a ir a entrenar? Sí, ¡¿no?![n][w][e]

[msg MSG_009_0_0]
[f 2 1]RE: RE: RE: RE: ¡¡SOY MIYA...[n][w][e]

[msg MSG_010_0_0]
[f 2 1]¡¿Estás lista?! ¡Vamos a entrenar![n][w][e]

[msg MSG_011_0_0]
[f 2 1]RE: RE: RE: RE: RE: ¡¡SOY MIYA...[n][w][e]

[msg MSG_012_0_0]
[f 2 1]¡¿Estás lista?! ¡Vamos a entrenar![n][w][e]

[msg MSG_013_0_0]
[f 2 1]RE: RE: RE: RE: RE: RE: ¡¡SOY M...[n][w][e]

[msg MSG_014_0_0]
[f 2 1]¡¿ESTÁS LISTAAA?! ¡¡VAMOS YA A ENTRENAR!![n][w][e]

[msg MSG_015_0_0]
[f 2 1]¡¡Voy a ganar!![n][w][e]

[msg MSG_016_0_0]
[f 2 1]¡Hoy voy a darlo todo! ¡Vamos corriendo a entrenar![n][w][e]

[msg MSG_017_0_0]
[f 2 1]RE: ¡¡Voy a ganar!![n][w][e]

[msg MSG_018_0_0]
[f 2 1]¡¡Vamos a entrenar!! ¡Hoy pienso ganarte! Bueno, ¡en sueños![n][w][e]

[msg MSG_019_0_0]
[f 2 1]¡¡¡ENTRENAMIENTO!!![n][w][e]

[msg MSG_020_0_0]
[f 2 1]Hoy vienes, ¡¿no?! ¡Más te vale![n][w][e]

[msg MSG_021_0_0]
[f 2 1]¡¡¡A CORRER!!![n][w][e]

[msg MSG_022_0_0]
[f 2 1]Venga, ¡¡vámonos!! ¡¡Más te vale espabilar!![n][w][e]

[msg MSG_023_0_0]
[f 2 1]¡¡¡ENTRENAMIENTO!!![n][w][e]

[msg MSG_024_0_0]
[f 2 1]¡¡¡ES HOOOY!!! ¡¡¡VAMOOOS!!![n][w][e]

[msg MSG_025_0_0]
[f 2 1]¡¡¡Recordatorio!!![n][w][e]

[msg MSG_026_0_0]
[f 2 1]¿Hoy qué vas a hacer? Podríamos ir a algún lado si estás libre. Avísame si puedes quedar antes de esta tarde.[n][w][e]

[msg MSG_027_0_0]
[f 2 1]¡¡¡PELI!!![n][w][e]

[msg MSG_028_0_0]
[f 2 1]¿Estás libre hoy? Vamos a ver una peli, anda. Dicen que esta es pura pasión, y seguro que nos anima. Me han regalado un par de entradas, así que avísame si puedes por la tarde.[n][w][e]

