[msg MSG_000_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 1 0 0][f 4 23 0 1 0 25 25]Ah, eres tú.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 2 0 0][f 4 23 0 1 0 25 25]Perdona por el susto. Tenía la sensación de que había alguien.[n][w][e]

[msg MSG_001_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 3 0 0][f 4 23 0 1 0 25 25]¿Qué es eso?[n][w][e]

[msg MSG_002_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 4 65535 65535 0 0][vp 0 0 0 4 0 0][f 4 23 0 1 4 25 25]...[n][w][e]
[f 2 1][bup 5 4 65535 65535 0 0][vp 1 0 0 5 0 0][f 4 23 0 1 4 25 25]¿Lo has encontrado tú?[n][w][e]

[sel SEL_003_0_0 top]
[f 2 1]Sí.[e]
[f 2 1]Estaba en su escritorio.[e]

[msg MSG_004_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 3 65535 65535 0 0][vp 1 0 0 6 0 0][f 4 23 0 1 3 25 25]Entiendo...[n][w][e]
[f 2 1][bup 5 3 65535 65535 0 0][vp 1 0 0 7 0 0][f 4 23 0 1 3 25 25]Se acostumbró a no dejar atrás pertenencias, pero...[n][w][e]
[f 2 1][bup 5 3 65535 65535 0 0][vp 0 0 0 8 0 0][f 4 23 0 1 3 25 25]...[n][w][e]

[msg MSG_005_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 9 0 0][f 4 23 0 1 0 25 25]No sé cuándo cumplimentaría el formulario para volver al instituto ni cuándo pensaba entregarlo.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 10 0 0][f 4 23 0 1 0 25 25]Pero esto demuestra que tenía presente nuestra promesa.[n][w][e]

[sel SEL_006_0_0 top]
[f 2 1]Seguro que sí.[e]
[f 2 1]¿Y yo qué sé?[e]
[f 2 1]Fui un poco pesada con el tema.[e]

[msg MSG_007_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 11 0 0][f 4 23 0 1 0 25 25]Sí... Se negaba en rotundo, pero aun así nos dejó esto.[n][w][e]

[msg MSG_008_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 3 65535 65535 0 0][vp 1 0 0 12 0 0][f 4 23 0 1 3 25 25]Ya... A lo mejor me estoy haciendo ilusiones, pero prefiero creerlo así.[n][w][e]

[msg MSG_009_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 3 65535 65535 0 0][vp 1 0 0 13 0 0][f 4 23 0 1 3 25 25]No estaba al tanto de sus circunstancias y es posible que yo le empeorase las cosas, pero...[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 14 0 0][f 4 23 0 1 0 25 25]Si supiera que nos sentíamos culpables, nos habría dicho que lo dejáramos en paz.[n][w][e]

[msg MSG_010_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 15 0 0][f 4 23 0 1 0 25 25]Debería enseñárselo a Akihiko. Aunque...[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 16 0 0][f 4 23 0 1 0 25 25]Mejor no. Seguramente no lo aceptaría.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 17 0 0][f 4 23 0 1 0 25 25]Que esto no salga de aquí, por favor.[n][w][e]

[sel SEL_011_0_0 top]
[f 2 1]Buena idea.[e]
[f 2 1]Qué movida.[e]

[msg MSG_012_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 18 0 0][f 4 23 0 1 1 25 25]Ja... Ya veo que has aprendido a manejarlos.[n][w][e]

[msg MSG_013_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 19 0 0][f 4 23 0 1 1 25 25]No podría estar más de acuerdo. A veces trabajar con tanto terco me da dolor de cabeza.[n][w][e]

[msg MSG_014_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 20 0 0][f 4 23 0 1 0 25 25]Gracias a ti, he logrado comprender cómo se sentía.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 21 0 0][f 4 23 0 1 1 25 25]De parte de los tres, muchísimas gracias.[n][w][e]

[msg MSG_015_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 22 0 0][f 4 23 0 1 0 25 25]Toma.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 23 0 0][f 4 23 0 1 0 25 25]Quédatelo, que tú fuiste quien consiguió que se sincerase.[n][w][e]

[msg MSG_016_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 24 0 0][f 4 23 0 1 0 25 25]El día que nos vayamos de la resi, se lo contaré a Akihiko.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 25 0 0][f 4 23 0 1 1 25 25]Le hablaré de lo mucho que le costó volver a esta habitación para cumplir con su promesa.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 26 0 0][f 4 23 0 1 1 25 25]Los días que pasamos los tres juntos... jamás se llegaron a olvidar.[n][w][e]

[msg MND_017_0_0]
[f 2 1]DEV: *Unused message labels. [n]*If it appears, it's a bug.[n][w][e]

[msg SYS_018_0_0]
[f 2 1]Has presenciado la última voluntad de Shinjiro. ¡Ya puedes fusionar al vándalo del inframundo, [clr 35]Ángel del infierno[clr 27]![n][w][e]

