[msg MSG_000_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 1 65535 65535 0 0][vp 1 0 0 1 0 0]Voy a comprar algo para el resfriado. Vengo en un momento.[n][w][e]

[msg MSG_001_0_0 [Hombre pretencioso]]
[f 2 1][vp 1 0 0 2 0 0][f 5 21 0 100]¡Anda, hola! ¿Vas de camino a casa?[n][w][e]

[msg MSG_002_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 3 65535 65535 0 0][vp 1 0 0 3 0 0]¿Eh? ¿Q-qué quieres?[n][w][e]

[msg MSG_003_0_0 [Hombre pretencioso]]
[f 2 1][vp 1 0 0 4 0 0][f 5 21 0 100]¡Si eres una monada! Ya me lo imaginaba, pero ahora que te veo de frente eres guapísima y las gafas te sientan de lujo.[n][w][e]
[f 2 1][vp 1 0 0 5 0 0][f 5 21 0 100]¿Te apetece ir a la cafetería y charlamos un rato?[n][w][e]

[msg MSG_004_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 3 65535 65535 0 0][vp 1 0 0 6 0 0]Mmm, pues...[n][w][e]

[msg MSG_005_0_0 [Hombre pretencioso]]
[f 2 1][vp 1 0 0 7 0 0][f 5 21 0 100]Venga, mujer, no te asustes. ¡Que no muerdo![n][w][e]

[msg MSG_006_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 3 65535 65535 0 0][vp 1 0 0 8 0 0]N-no... ¡Para, por favor![n][w][e]

[msg MSG_006_3_0 [Chihiro Fushimi]]
[f 2 1][bup 109 3 65535 65535 0 0][vp 1 0 0 9 0 0]¡[nl]![n][w][e]

[sel SEL_007_0_0 top]
[f 2 1]Piérdete.[e]
[f 2 1]Hola.[e]

[msg MSG_008_0_0 [Hombre pretencioso]]
[f 2 1][vp 1 0 0 10 0 0][f 5 21 0 100]¿Eh? ¿Quién demonios eres tú?[n][w][e]

[msg MSG_008_3_0 [Hombre pretencioso]]
[f 2 1][vp 1 0 0 11 0 0][f 5 21 0 100]Espera, no me digas que estás con ella...[n][w][e]
[f 2 1][vp 0 0 0 12 0 0][f 5 21 0 100]Jum...[n][w][e]

[msg MSG_008_7_0 [Hombre pretencioso]]
[f 2 1][vp 1 0 0 13 0 0][f 5 21 0 100]Pfff, y yo que pensaba que podría ligármela porque parecía tan normalita...[n][w][e]

[msg MSG_009_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 3 65535 65535 0 0][vp 1 0 0 14 0 0]Ay, menos mal... Por un momento, pensé que ibas a pegarte con él, [nl].[n][w][e]
[f 2 1][bup 109 3 65535 65535 0 0][vp 1 0 0 15 0 0]No me gustaría que te metieras en peleas por mi culpa, pero... has estado tan...[n][w][e]

[msg MSG_010_0_0 [Hombre pretencioso]]
[f 2 1][vp 1 0 0 16 0 0][f 5 21 0 100]¿Y a ti qué te pasa? ¿Por qué me miras así?[n][w][e]

[msg MSG_010_3_0 [Hombre pretencioso]]
[f 2 1][vp 1 0 0 17 0 0][f 5 21 0 100]Espera... No me digas que estás con ella.[n][w][e]

[msg MSG_010_7_0 [Hombre pretencioso]]
[f 2 1][vp 1 0 0 18 0 0][f 5 21 0 100]Joder, ya está pillada...[n][w][e]

[msg MSG_011_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 3 65535 65535 0 0][vp 1 0 0 19 0 0]Sueles ser muy calladita, [nl]... Pero también eres capaz de ponerte firme cuando toca.[n][w][e]
[f 2 1][bup 109 0 65535 65535 0 0][vp 1 0 0 20 0 0][f 4 23 0 109 0 25 25]A-ah, pero no lo digo como algo malo. Eh...[n][w][e]

[msg MSG_012_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 3 65535 65535 0 0][vp 1 0 0 21 0 0]Uf... M-me has ayudado y ya no tengo miedo, pero...[n][w][e]
[f 2 1][bup 109 3 65535 65535 0 0][vp 1 0 0 22 0 0]¿Por qué no paro de temblar?[n][w][e]

[sel SEL_013_0_0 top]
[f 2 1]Vamos a darnos la mano.[e]
[f 2 1]Estoy contigo.[e]
[f 2 1]Respira hondo.[e]

[msg MSG_014_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 4 65535 65535 0 0][vp 1 0 0 23 0 0]¿Eh? ¿D-darnos la mano?[n][w][e]

[msg MSG_015_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 3 65535 65535 0 0][vp 1 0 0 24 0 0]L-lo siento... C-creo que no estoy preparada para eso...[n][w][e]

[msg MSG_015_5_0 [Chihiro Fushimi]]
[f 2 1][bup 109 0 65535 65535 0 0][vp 1 0 0 25 0 0]Ah, al menos ya no estoy temblando. Gracias...[n][w][e]

[msg MSG_016_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 0 65535 65535 0 0][vp 1 0 0 26 0 0][f 5 13 9 15 109]Eso me hace sentir mucho mejor... Vale.[n][w][e]

[msg MSG_016_5_0 [Chihiro Fushimi]]
[f 2 1][bup 109 0 65535 65535 0 0][vp 1 0 0 27 0 0]Gracias. Creo que ya estoy bien.[n][w][e]

[msg MSG_017_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 0 65535 65535 0 0][vp 1 0 0 28 0 0]Uf, ya me siento más tranquila.[n][w][e]

[msg MSG_017_5_0 [Chihiro Fushimi]]
[f 2 1][bup 109 0 65535 65535 0 0][vp 1 0 0 29 0 0]Gracias. Creo que ya estoy bien.[n][w][e]

[msg MND_018_0_0]
[f 2 1]Percibo que Chihiro confía en mí.[n][w][e]
[f 2 1]Siento que nuestra relación se ha fortalecido.[n][w][e]

[msg MSG_019_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 3 65535 65535 1 0][vp 1 0 0 30 0 0]¿Eh? ¿P-por qué... me falta el aire de repente?[n][w][e]
[f 2 1][bup 109 3 65535 65535 1 0][vp 1 0 0 31 0 0][nl], yo...[n][w][e]

[msg MSG_020_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 3 65535 65535 1 0][vp 1 0 0 32 0 0]Pues sí que parece que me he resfriado... Siento que tengo la cara encendida.[n][w][e]

[msg MSG_020_5_0 [Chihiro Fushimi]]
[f 2 1][bup 109 0 65535 65535 1 0][vp 1 0 0 33 0 0]Mmm... ¡Gracias una vez más por salvarme![n][w][e]
[f 2 1][bup 109 0 65535 65535 1 0][vp 1 0 0 34 0 0][f 4 21 109 11]Ahora, si me disculpas...[n][w][e]

[msg MND_021_0_0]
[f 2 1]Chihiro se ha ido a toda prisa...[n][w][e]
[f 2 1]He decidido volver a la residencia.[n][w][e]

