[msg Item_000]
[f 2 1]未使用[n][e]

[msg Item_001]
[f 2 1]Un reproductor de música portátil de última generación que se puede llevar al cuello.[n][e]

[msg Item_002]
[f 2 1]Una gargantilla blanca muy cuqui con forma de corazón.[n][e]

[msg Item_003]
[f 2 1]Un colgante elegante de plata. Es el último grito en las revistas de moda masculina.[n][e]

[msg Item_004]
[f 2 1]Guantes finos de cuero. Se ajustan perfectamente a la mano.[n][e]

[msg Item_005]
[f 2 1]Uñas postizas adornadas con unas joyas preciosas. Bonitas y elegantes.[n][e]

[msg Item_006]
[f 2 1]Un bonito colgante que está muy de moda entre las chicas de instituto.[n][e]

[msg Item_007]
[f 2 1]Un lazo carmesí enorme. Añade sofisticación y un toque de color al collar.[n][e]

[msg Item_008]
[f 2 1]Una pulsera sencilla diseñada para los amantes del deporte.[n][e]

[msg Item_009]
[f 2 1]Un accesorio decorativo con forma de alas de ángel. Poco funcional.[n][e]

[msg Item_00A]
[f 2 1]Un gorro de lana sencillo y sin florituras para hombres.[n][e]

[msg Item_00B]
[f 2 1]Una pulsera de cuerda resistente. Mejora un poco la fuerza física.[n][e]

[msg Item_00C]
[f 2 1]Una pulsera de cuerda resistente. Mejora bastante la fuerza física.[n][e]

[msg Item_00D]
[f 2 1]Una pulsera de cuerda resistente. Mejora mucho la fuerza física.[n][e]

[msg Item_00E]
[f 2 1]Una pulsera de seda mística. Mejora un poco el poder mágico.[n][e]

[msg Item_00F]
[f 2 1]Una pulsera de seda mística. Mejora bastante el poder mágico.[n][e]

[msg Item_010]
[f 2 1]Una pulsera de seda mística. Mejora mucho el poder mágico.[n][e]

[msg Item_011]
[f 2 1]Una pulsera de acero resistente. Mejora un poco la defensa.[n][e]

[msg Item_012]
[f 2 1]Una pulsera de acero resistente. Mejora bastante la defensa.[n][e]

[msg Item_013]
[f 2 1]Una pulsera de acero resistente. Mejora mucho la defensa.[n][e]

[msg Item_014]
[f 2 1]Una pulsera de tela vaporosa. Hace sentir un poco más ligero a quien la lleva.[n][e]

[msg Item_015]
[f 2 1]Una pulsera de tela vaporosa. Hace sentir bastante más ligero a quien la lleva.[n][e]

[msg Item_016]
[f 2 1]Una pulsera de tela vaporosa. Hace sentir mucho más ligero a quien la lleva.[n][e]

[msg Item_017]
[f 2 1]Una pulsera trenzada ostentosa. Mejora un poco la buena fortuna.[n][e]

[msg Item_018]
[f 2 1]Una pulsera trenzada ostentosa. Mejora bastante la buena fortuna.[n][e]

[msg Item_019]
[f 2 1]Una pulsera trenzada ostentosa. Mejora mucho la buena fortuna.[n][e]

[msg Item_01A]
[f 2 1]Una pulsera de plata lujosa. Mejora un poco todos los atributos.[n][e]

[msg Item_01B]
[f 2 1]Una pulsera translúcida lujosa. Mejora mucho todos los atributos.[n][e]

[msg Item_01C]
[f 2 1]未使用[n][e]

[msg Item_01D]
[f 2 1]未使用[n][e]

[msg Item_01E]
[f 2 1]未使用[n][e]

[msg Item_01F]
[f 2 1]未使用[n][e]

[msg Item_020]
[f 2 1]Una pulsera de cuerda resistente. Mejora muchísimo la fuerza física.[n][e]

[msg Item_021]
[f 2 1]Una pulsera de seda mística. Mejora muchísimo el poder mágico.[n][e]

[msg Item_022]
[f 2 1]Una pulsera de acero resistente. Mejora muchísimo la defensa.[n][e]

[msg Item_023]
[f 2 1]Una pulsera de tela vaporosa. Hace sentir muchísimo más ligero a quien la lleva.[n][e]

[msg Item_024]
[f 2 1]Una pulsera trenzada ostentosa. Mejora muchísimo la buena fortuna.[n][e]

[msg Item_025]
[f 2 1]未使用[n][e]

[msg Item_026]
[f 2 1]未使用[n][e]

[msg Item_027]
[f 2 1]Hace que quien lo lleva sea más fuerte temporalmente al empezar un combate.[n][e]

[msg Item_028]
[f 2 1]Hace que quien lo lleva sea más resistente temporalmente al empezar un combate.[n][e]

[msg Item_029]
[f 2 1]Hace que quien lo lleva sea más ágil temporalmente al empezar un combate.[n][e]

[msg Item_02A]
[f 2 1]Unos brazales con un diseño ígneo. Aumentan el daño de fuego.[n][e]

[msg Item_02B]
[f 2 1]Contienen el poder del dios del fuego. Aumentan mucho el daño de fuego.[n][e]

[msg Item_02C]
[f 2 1]Unos brazales con un diseño glaciar. Aumentan el daño de hielo.[n][e]

[msg Item_02D]
[f 2 1]Contienen el poder del dios del hielo. Aumentan mucho el daño de hielo.[n][e]

[msg Item_02E]
[f 2 1]Unos brazales con un diseño eléctrico. Aumentan el daño eléctrico.[n][e]

[msg Item_02F]
[f 2 1]Contienen el poder del dios del rayo. Aumentan mucho el daño eléctrico.[n][e]

[msg Item_030]
[f 2 1]Unos brazales con un diseño de tormenta. Aumentan el daño de viento.[n][e]

[msg Item_031]
[f 2 1]Contienen el poder del dios del viento. Aumentan mucho el daño de viento.[n][e]

[msg Item_032]
[f 2 1]Un rosario misterioso que aumenta el poder de ataque de quien lo lleva al enfurecerse.[n][e]

[msg Item_033]
[f 2 1]Una adorable máscara de calabaza. Aumenta el daño de oscuridad.[n][e]

[msg Item_034]
[f 2 1]Hace que todos los aliados sean más fuertes temporalmente al empezar un combate.[n][e]

[msg Item_035]
[f 2 1]Hace que todos los aliados sean más resistentes temporalmente al empezar un combate.[n][e]

[msg Item_036]
[f 2 1]Hace que todos los aliados sean más ágiles temporalmente al empezar un combate.[n][e]

[msg Item_037]
[f 2 1]Aumenta temporalmente la probabilidad de críticos de quien lo lleva al empezar un combate.[n][e]

[msg Item_038]
[f 2 1]未使用[n][e]

[msg Item_039]
[f 2 1]Un texto instructivo de técnicas para esquivar ataques físicos.[n][e]

[msg Item_03A]
[f 2 1]Un amuleto con un diseño tosco. Otorga la habilidad de esquivar ataques mágicos.[n][e]

[msg Item_03B]
[f 2 1]Un texto instructivo de técnicas para esquivar ataques cortantes.[n][e]

[msg Item_03C]
[f 2 1]Un texto avanzado de técnicas para esquivar ataques cortantes con más facilidad.[n][e]

[msg Item_03D]
[f 2 1]Un texto instructivo de técnicas para esquivar ataques contundentes.[n][e]

[msg Item_03E]
[f 2 1]Un texto avanzado de técnicas para esquivar ataques contundentes con más facilidad.[n][e]

[msg Item_03F]
[f 2 1]Un texto instructivo de técnicas para esquivar ataques perforantes.[n][e]

[msg Item_040]
[f 2 1]Un texto avanzado de técnicas para esquivar ataques perforantes con más facilidad.[n][e]

[msg Item_041]
[f 2 1]Un amuleto con un diseño tosco. Otorga la habilidad de esquivar ataques de fuego.[n][e]

[msg Item_042]
[f 2 1]Aumenta mucho la habilidad de esquivar ataques de fuego.[n][e]

[msg Item_043]
[f 2 1]Un amuleto con un diseño tosco. Otorga la habilidad de esquivar ataques de hielo.[n][e]

[msg Item_044]
[f 2 1]Aumenta mucho la habilidad de esquivar ataques de hielo.[n][e]

[msg Item_045]
[f 2 1]Un amuleto con un diseño tosco. Otorga la habilidad de esquivar ataques de viento.[n][e]

[msg Item_046]
[f 2 1]Aumenta mucho la habilidad de esquivar ataques de viento.[n][e]

[msg Item_047]
[f 2 1]Un amuleto con un diseño tosco. Otorga la habilidad de esquivar ataques eléctricos.[n][e]

[msg Item_048]
[f 2 1]Aumenta mucho la habilidad de esquivar ataques eléctricos.[n][e]

[msg Item_049]
[f 2 1]Estos fuertes rizos mejoran la capacidad de reacción a ataques físicos.[n][e]

[msg Item_04A]
[f 2 1]Un texto ancestral que describe los secretos para esquivar ataques mágicos.[n][e]

[msg Item_04B]
[f 2 1]Unos brazales intimidantes. Hace que sea más difícil golpear a quien los lleva.[n][e]

[msg Item_04C]
[f 2 1]Un amuleto con un diseño tosco. Otorga la habilidad de esquivar ataques de luz.[n][e]

[msg Item_04D]
[f 2 1]Aumenta mucho la habilidad de esquivar ataques de luz.[n][e]

[msg Item_04E]
[f 2 1]Un amuleto con un diseño tosco. Otorga la habilidad de esquivar ataques de oscuridad.[n][e]

[msg Item_04F]
[f 2 1]Aumenta mucho la habilidad de esquivar ataques de oscuridad.[n][e]

[msg Item_050]
[f 2 1]未使用[n][e]

[msg Item_051]
[f 2 1]Una vaina de acero que otrora usó el dios de las espadas. Dicen que puede bloquear cualquier filo.[n][e]

[msg Item_052]
[f 2 1]Una escama dorada gruesa. Invulnerable a los golpes contundentes.[n][e]

[msg Item_053]
[f 2 1]Una figura de cerámica indestructible que no se puede atravesar.[n][e]

[msg Item_054]
[f 2 1]Una piedra imbuida con una llama tan ardiente que resta fuerza a otras fuentes de calor.[n][e]

[msg Item_055]
[f 2 1]Un cristal precioso de color azul marino. Evita todo tipo de congelación y hielo.[n][e]

[msg Item_056]
[f 2 1]Guantes que llevó el dios del trueno. Disipa toda electricidad.[n][e]

[msg Item_057]
[f 2 1]Un anillo con forma parecida a un vendaval. Apacigua hasta las tormentas más feroces.[n][e]

[msg Item_058]
[f 2 1]Un anillo de color blanco puro. Protege de todas las formas sagradas de poder.[n][e]

[msg Item_059]
[f 2 1]Un anillo de color negro obsidiana. Pone freno a las fuerzas oscuras.[n][e]

[msg Item_05A]
[f 2 1]Un brazalete especial que emite un aura gélida. Evita Congelación.[n][e]

[msg Item_05B]
[f 2 1]Un brazalete especial que emite un aura estática. Evita Paralización.[n][e]

[msg Item_05C]
[f 2 1]Un accesorio con forma de cuerno de unicornio. Evita Veneno.[n][e]

[msg Item_05D]
[f 2 1]Un adorno que recuerda a una horda de espíritus. Evita Confusión.[n][e]

[msg Item_05E]
[f 2 1]Una bola y una cadena. Es extrañamente reconfortante. Evita Angustia.[n][e]

[msg Item_05F]
[f 2 1]Una flor de adorno que acaba con toda tentación. Evita Manipulación.[n][e]

[msg Item_060]
[f 2 1]Un globo ocular del tamaño de una mano. Apretarlo ayuda a calmar los nervios. Evita Miedo.[n][e]

[msg Item_061]
[f 2 1]Un anillo azul de lujo. Disipa la rabia al observarlo. Evita Furia.[n][e]

[msg Item_062]
[f 2 1]Un libro que evita Confusión, Angustia, Manipulación, Miedo y Furia.[n][e]

[msg Item_063]
[f 2 1]Una esfera de un material desconocido que es prácticamente indestructible.[n][e]

[msg Item_064]
[f 2 1]La marca de un gran guerrero. Probabilidad baja de contraatacar ataques físicos.[n][e]

[msg Item_065]
[f 2 1]La marca de un dios de la guerra. Probabilidad media de contraatacar ataques físicos.[n][e]

[msg Item_066]
[f 2 1]La marca de una bestia temible. Probabilidad alta de contraatacar ataques físicos.[n][e]

[msg Item_067]
[f 2 1]Un artefacto sagrado. El usuario no puede esquivar, pero el daño recibido se reduce a la mitad.[n][e]

[msg Item_068]
[f 2 1]Gafas de lujo que ofrecen una visión perfecta incluso en la oscuridad total.[n][e]

[msg Item_069]
[f 2 1]Ayuda a mantener a raya los males de la mente, como el miedo y la tentación.[n][e]

[msg Item_06A]
[f 2 1]Madera con un aroma calmante. Acelera la recuperación de estados alterados.[n][e]

[msg Item_06B]
[f 2 1]Contiene una fragancia agradable. Cura al instante los estados alterados.[n][e]

[msg Item_06C]
[f 2 1]未使用[n][e]

[msg Item_06D]
[f 2 1]Este sello emana el poder de los dominios. Restaura una cantidad ínfima de PS cada turno.[n][e]

[msg Item_06E]
[f 2 1]Este sello emana el poder de la Tierra. Restaura una cantidad minúscula de PS cada turno.[n][e]

[msg Item_06F]
[f 2 1]Este sello emana el poder del espacio. Restaura algunos PS cada turno.[n][e]

[msg Item_070]
[f 2 1]Una insignia que despierta el poder del qi. Restaura una cantidad ínfima de PE cada turno.[n][e]

[msg Item_071]
[f 2 1]Una insignia que aumenta el poder del qi. Restaura una cantidad minúscula de PE cada turno.[n][e]

[msg Item_072]
[f 2 1]Una insignia que rebosa de poder del qi. Restaura algunos PE cada turno.[n][e]

[msg Item_073]
[f 2 1]Una muñeca adorable que dio Maiko. Restaura una cantidad ínfima de PE cada turno.[n][e]

[msg Item_074]
[f 2 1]未使用[n][e]

[msg Item_075]
[f 2 1]Un artefacto divino que restaura todos los PS al morir una vez por batalla.[n][e]

[msg Item_076]
[f 2 1]Cuentas de oración que permiten sobrevivir a un ataque de muerte instantánea por oscuridad con 1 PS.[n][e]

[msg Item_077]
[f 2 1]Accesorio que permite sobrevivir a un ataque de muerte instantánea por luz con 1 PS.[n][e]

[msg Item_078]
[f 2 1]Un brazalete que permite sobrevivir a un ataque de muerte instantánea con 1 PS.[n][e]

[msg Item_079]
[f 2 1]未使用[n][e]

[msg Item_07A]
[f 2 1]未使用[n][e]

[msg Item_07B]
[f 2 1]未使用[n][e]

[msg Item_07C]
[f 2 1]未使用[n][e]

[msg Item_07D]
[f 2 1]Un broche de materiales de lujo. Es caro, pero no sirve para nada.[n][e]

[msg Item_07E]
[f 2 1]Un anillo que reduce el coste de PS de las habilidades físicas a la mitad.[n][e]

[msg Item_07F]
[f 2 1]Un anillo que reduce el coste de PE de las habilidades mágicas a la mitad.[n][e]

[msg Item_080]
[f 2 1]未使用[n][e]

[msg Item_081]
[f 2 1]Reduce la probabilidad de sufrir golpes críticos.[n][e]

[msg Item_082]
[f 2 1]Aumenta la probabilidad de críticos del usuario.[n][e]

[msg Item_083]
[f 2 1]未使用[n][e]

[msg Item_084]
[f 2 1]未使用[n][e]

[msg Item_085]
[f 2 1]Una faja como la de los samuráis. Otorga una cantidad ínfima de vitalidad.[n][e]

[msg Item_086]
[f 2 1]Una faja como la de los samuráis. Otorga una cantidad minúscula de vitalidad.[n][e]

[msg Item_087]
[f 2 1]Una faja como la de los samuráis. Otorga algo de vitalidad.[n][e]

[msg Item_088]
[f 2 1]Una faja como la de los samurái. Otorga una cantidad considerable de vitalidad.[n][e]

[msg Item_089]
[f 2 1]Una faja como la de los samuráis. Otorga muchísima vitalidad.[n][e]

[msg Item_08A]
[f 2 1]Un cartel rojo y llamativo habitado por las almas de innumerables soldados.[n][e]

[msg Item_08B]
[f 2 1]Un amuleto digno de una bruja. Otorga una cantidad ínfima de poder mágico.[n][e]

[msg Item_08C]
[f 2 1]Un amuleto digno de una bruja. Otorga una cantidad minúscula de poder mágico.[n][e]

[msg Item_08D]
[f 2 1]Un amuleto digno de una bruja. Otorga algo de poder mágico.[n][e]

[msg Item_08E]
[f 2 1]Un amuleto digno de una bruja. Otorga una cantidad considerable de poder mágico.[n][e]

[msg Item_08F]
[f 2 1]Un amuleto digno de una bruja. Otorga muchísimo poder mágico.[n][e]

[msg Item_090]
[f 2 1]Un accesorio para el pelo con runas grabadas. Desata el sexto sentido de quien lo lleva.[n][e]

[msg Item_091]
[f 2 1]Un anillo que otorga más experiencia en batalla a quien lo lleva.[n][e]

[msg Item_092]
[f 2 1]Un amuleto que potencia al máximo la experiencia en batalla de quien lo lleva.[n][e]

[msg Item_093]
[f 2 1]未使用[n][e]

[msg Item_094]
[f 2 1]未使用[n][e]

[msg Item_095]
[f 2 1]未使用[n][e]

[msg Item_096]
[f 2 1]未使用[n][e]

[msg Item_097]
[f 2 1]未使用[n][e]

[msg Item_098]
[f 2 1]未使用[n][e]

[msg Item_099]
[f 2 1]未使用[n][e]

[msg Item_09A]
[f 2 1]未使用[n][e]

[msg Item_09B]
[f 2 1]Hace tanto ruido que quien lo lleva no se distrae. Evita Mareo.[n][e]

[msg Item_09C]
[f 2 1]未使用[n][e]

[msg Item_09D]
[f 2 1]未使用[n][e]

[msg Item_09E]
[f 2 1]未使用[n][e]

[msg Item_09F]
[f 2 1]未使用[n][e]

[msg Item_0A0]
[f 2 1]未使用[n][e]

[msg Item_0A1]
[f 2 1]未使用[n][e]

[msg Item_0A2]
[f 2 1]未使用[n][e]

[msg Item_0A3]
[f 2 1]未使用[n][e]

[msg Item_0A4]
[f 2 1]Una chapa de madera que reduce la probabilidad de sufrir Congelación.[n][e]

[msg Item_0A5]
[f 2 1]Una chapa de madera que reduce la probabilidad de sufrir Paralización.[n][e]

[msg Item_0A6]
[f 2 1]Una chapa de madera que reduce la probabilidad de sufrir Veneno.[n][e]

[msg Item_0A7]
[f 2 1]Una chapa de madera que reduce la probabilidad de sufrir Confusión.[n][e]

[msg Item_0A8]
[f 2 1]Una chapa de madera que reduce la probabilidad de sufrir Angustia.[n][e]

[msg Item_0A9]
[f 2 1]Una chapa de madera que reduce la probabilidad de sufrir Manipulación.[n][e]

[msg Item_0AA]
[f 2 1]Una chapa de madera que reduce la probabilidad de sufrir Miedo.[n][e]

[msg Item_0AB]
[f 2 1]Una chapa de madera que reduce la probabilidad de sufrir Furia.[n][e]

[msg Item_0AC]
[f 2 1]未使用[n][e]

[msg Item_0AD]
[f 2 1]未使用[n][e]

[msg Item_0AE]
[f 2 1]未使用[n][e]

[msg Item_0AF]
[f 2 1]未使用[n][e]

[msg Item_0B0]
[f 2 1]未使用[n][e]

[msg Item_0B1]
[f 2 1]未使用[n][e]

[msg Item_0B2]
[f 2 1]未使用[n][e]

[msg Item_0B3]
[f 2 1]未使用[n][e]

[msg Item_0B4]
[f 2 1]Una chapa de madera que aumenta la probabilidad de infligir Confusión.[n][e]

[msg Item_0B5]
[f 2 1]Una chapa de madera que aumenta la probabilidad de infligir Angustia.[n][e]

[msg Item_0B6]
[f 2 1]未使用[n][e]

[msg Item_0B7]
[f 2 1]Una chapa de madera que aumenta la probabilidad de infligir Miedo.[n][e]

[msg Item_0B8]
[f 2 1]未使用[n][e]

[msg Item_0B9]
[f 2 1]Una chapa de madera que aumenta la probabilidad de infligir Mareo.[n][e]

[msg Item_0BA]
[f 2 1]未使用[n][e]

[msg Item_0BB]
[f 2 1]未使用[n][e]

[msg Item_0BC]
[f 2 1]未使用[n][e]

[msg Item_0BD]
[f 2 1]未使用[n][e]

[msg Item_0BE]
[f 2 1]未使用[n][e]

[msg Item_0BF]
[f 2 1]未使用[n][e]

[msg Item_0C0]
[f 2 1]未使用[n][e]

[msg Item_0C1]
[f 2 1]未使用[n][e]

[msg Item_0C2]
[f 2 1]未使用[n][e]

[msg Item_0C3]
[f 2 1]未使用[n][e]

[msg Item_0C4]
[f 2 1]未使用[n][e]

[msg Item_0C5]
[f 2 1]未使用[n][e]

[msg Item_0C6]
[f 2 1]未使用[n][e]

[msg Item_0C7]
[f 2 1]未使用[n][e]

[msg Item_0C8]
[f 2 1]Unos pendientes que reducen un poco el daño de los ataques cortantes.[n][e]

[msg Item_0C9]
[f 2 1]Un broche que reduce bastante el daño de los ataques cortantes.[n][e]

[msg Item_0CA]
[f 2 1]Un collar que reduce mucho el daño de los ataques cortantes.[n][e]

[msg Item_0CB]
[f 2 1]Unos pendientes que reducen un poco el daño de los ataques contundentes.[n][e]

[msg Item_0CC]
[f 2 1]Un broche que reduce bastante el daño de los ataques contundentes.[n][e]

[msg Item_0CD]
[f 2 1]Un collar que reduce mucho el daño de los ataques contundentes.[n][e]

[msg Item_0CE]
[f 2 1]Unos pendientes que reducen un poco el daño de los ataques perforantes.[n][e]

[msg Item_0CF]
[f 2 1]Un broche que reduce bastante el daño de los ataques perforantes.[n][e]

[msg Item_0D0]
[f 2 1]Un collar que reduce mucho el daño de los ataques perforantes.[n][e]

[msg Item_0D1]
[f 2 1]Unos pendientes que reducen un poco el daño de los ataques físicos.[n][e]

[msg Item_0D2]
[f 2 1]Un broche que reduce bastante el daño de los ataques físicos.[n][e]

[msg Item_0D3]
[f 2 1]Un collar que reduce mucho el daño de los ataques físicos.[n][e]

[msg Item_0D4]
[f 2 1]Unos pendientes que reducen un poco el daño de los ataques de fuego.[n][e]

[msg Item_0D5]
[f 2 1]Un broche que reduce bastante el daño de los ataques de fuego.[n][e]

[msg Item_0D6]
[f 2 1]Un collar que reduce mucho el daño de los ataques de fuego.[n][e]

[msg Item_0D7]
[f 2 1]Unos pendientes que reducen un poco el daño de los ataques de hielo.[n][e]

[msg Item_0D8]
[f 2 1]Un broche que reduce bastante el daño de los ataques de hielo.[n][e]

[msg Item_0D9]
[f 2 1]Un collar que reduce mucho el daño de los ataques de hielo.[n][e]

[msg Item_0DA]
[f 2 1]Unos pendientes que reducen un poco el daño de los ataques eléctricos.[n][e]

[msg Item_0DB]
[f 2 1]Un broche que reduce bastante el daño de los ataques eléctricos.[n][e]

[msg Item_0DC]
[f 2 1]Un collar que reduce mucho el daño de los ataques eléctricos.[n][e]

[msg Item_0DD]
[f 2 1]Unos pendientes que reducen un poco el daño de los ataques de viento.[n][e]

[msg Item_0DE]
[f 2 1]Un broche que reduce bastante el daño de los ataques de viento.[n][e]

[msg Item_0DF]
[f 2 1]Un collar que reduce mucho el daño de los ataques de viento.[n][e]

[msg Item_0E0]
[f 2 1]Unos pendientes que reducen un poco el daño de los ataques de luz.[n][e]

[msg Item_0E1]
[f 2 1]Un broche que reduce bastante el daño de los ataques de luz.[n][e]

[msg Item_0E2]
[f 2 1]Un collar que reduce mucho el daño de los ataques de luz.[n][e]

[msg Item_0E3]
[f 2 1]Unos pendientes que reducen un poco el daño de los ataques de oscuridad.[n][e]

[msg Item_0E4]
[f 2 1]Un broche que reduce bastante el daño de los ataques de oscuridad.[n][e]

[msg Item_0E5]
[f 2 1]Un collar que reduce mucho el daño de los ataques de oscuridad.[n][e]

[msg Item_0E6]
[f 2 1]Unos pendientes que reducen un poco el daño de los ataques mágicos.[n][e]

[msg Item_0E7]
[f 2 1]Un broche que reduce bastante el daño de los ataques mágicos.[n][e]

[msg Item_0E8]
[f 2 1]Un collar que reduce mucho el daño de los ataques mágicos.[n][e]

[msg Item_0E9]
[f 2 1]未使用[n][e]

[msg Item_0EA]
[f 2 1]未使用[n][e]

[msg Item_0EB]
[f 2 1]未使用[n][e]

[msg Item_0EC]
[f 2 1]未使用[n][e]

[msg Item_0ED]
[f 2 1]未使用[n][e]

[msg Item_0EE]
[f 2 1]未使用[n][e]

[msg Item_0EF]
[f 2 1]未使用[n][e]

[msg Item_0F0]
[f 2 1]Unos brazales con un diseño brillante. Aumentan el daño de luz.[n][e]

[msg Item_0F1]
[f 2 1]Contienen el poder de la diosa del amanecer. Aumentan mucho el daño de luz.[n][e]

[msg Item_0F2]
[f 2 1]Un brazalete con un diseño sombrío. Aumenta el daño de oscuridad.[n][e]

[msg Item_0F3]
[f 2 1]Contienen el poder de la diosa de la noche. Aumentan mucho el daño de oscuridad.[n][e]

[msg Item_0F4]
[f 2 1]Unos brazales con un diseño de una espada. Aumentan el daño cortante.[n][e]

[msg Item_0F5]
[f 2 1]Contienen el poder de una espada divina. Aumentan mucho el daño cortante.[n][e]

[msg Item_0F6]
[f 2 1]Unos brazales con un diseño de un puño. Aumentan el daño contundente.[n][e]

[msg Item_0F7]
[f 2 1]Contienen el poder de un mazo divino. Aumentan mucho el daño contundente.[n][e]

[msg Item_0F8]
[f 2 1]Unos brazales con un diseño de una flecha. Aumentan el daño perforante.[n][e]

[msg Item_0F9]
[f 2 1]Contienen el poder de un arco divino. Aumentan mucho el daño perforante.[n][e]

[msg Item_0FA]
[f 2 1]未使用[n][e]

[msg Item_0FB]
[f 2 1]未使用[n][e]

[msg Item_0FC]
[f 2 1]未使用[n][e]

[msg Item_0FD]
[f 2 1]未使用[n][e]

[msg Item_0FE]
[f 2 1]未使用[n][e]

[msg Item_0FF]
[f 2 1]未使用[n][e]

[msg Item_100]
[f 2 1]未使用[n][e]

[msg Item_101]
[f 2 1]未使用[n][e]

[msg Item_102]
[f 2 1]未使用[n][e]

[msg Item_103]
[f 2 1]未使用[n][e]

[msg Item_104]
[f 2 1]Un mantón que resiste el daño de fuego durante 3 turnos al empezar el combate.[n][e]

[msg Item_105]
[f 2 1]Un mantón que resiste el daño de hielo durante 3 turnos al empezar el combate.[n][e]

[msg Item_106]
[f 2 1]Un mantón que otorga "Resistir electricidad" que dura 3 turnos al empezar el combate.[n][e]

[msg Item_107]
[f 2 1]Un mantón que resiste el daño de viento durante 3 turnos al empezar el combate.[n][e]

[msg Item_108]
[f 2 1]Recupera PE de quien lo lleva al relevar a un aliado.[n][e]

[msg Item_109]
[f 2 1]Un prototipo de accesorio que protege a quien lo lleva con un campo magnético.[n][e]

[msg Item_10A]
[f 2 1]Una pulsera de oro lujosa. Mejora bastante todos los atributos.[n][e]

[msg Item_10B]
[f 2 1]Aumenta el ataque de quien lo lleva al relevar a un aliado.[n][e]

[msg Item_10C]
[f 2 1]Un amuleto que restaura todos los PS al morir una vez por batalla.[n][e]

[msg Item_10D]
[f 2 1]Libera un pico de fuerza potenciado por los vínculos de quien lo lleva.[n][e]

[msg Item_10E]
[f 2 1]Un llavero mono que te hizo Chihiro.[n][e]

[msg Item_10F]
[f 2 1]Un collar de lujo que protege a quien lo lleva de todos los estados alterados.[n][e]

[msg Item_110]
[f 2 1]Unos pendientes que restauran 1 PS al morir una vez por batalla.[n][e]

[msg Item_111]
[f 2 1]未使用[n][e]

[msg Item_112]
[f 2 1]未使用[n][e]

[msg Item_113]
[f 2 1]未使用[n][e]

[msg Item_114]
[f 2 1]未使用[n][e]

[msg Item_115]
[f 2 1]未使用[n][e]

[msg Item_116]
[f 2 1]未使用[n][e]

[msg Item_117]
[f 2 1]未使用[n][e]

[msg Item_118]
[f 2 1]未使用[n][e]

[msg Item_119]
[f 2 1]未使用[n][e]

[msg Item_11A]
[f 2 1]未使用[n][e]

[msg Item_11B]
[f 2 1]未使用[n][e]

[msg Item_11C]
[f 2 1]未使用[n][e]

[msg Item_11D]
[f 2 1]未使用[n][e]

[msg Item_11E]
[f 2 1]未使用[n][e]

[msg Item_11F]
[f 2 1]未使用[n][e]

[msg Item_120]
[f 2 1]未使用[n][e]

[msg Item_121]
[f 2 1]未使用[n][e]

[msg Item_122]
[f 2 1]未使用[n][e]

[msg Item_123]
[f 2 1]未使用[n][e]

[msg Item_124]
[f 2 1]未使用[n][e]

[msg Item_125]
[f 2 1]未使用[n][e]

[msg Item_126]
[f 2 1]未使用[n][e]

[msg Item_127]
[f 2 1]未使用[n][e]

[msg Item_128]
[f 2 1]未使用[n][e]

[msg Item_129]
[f 2 1]未使用[n][e]

[msg Item_12A]
[f 2 1]未使用[n][e]

[msg Item_12B]
[f 2 1]未使用[n][e]

[msg Item_12C]
[f 2 1]未使用[n][e]

[msg Item_12D]
[f 2 1]未使用[n][e]

[msg Item_12E]
[f 2 1]未使用[n][e]

[msg Item_12F]
[f 2 1]未使用[n][e]

[msg Item_130]
[f 2 1]未使用[n][e]

[msg Item_131]
[f 2 1]未使用[n][e]

[msg Item_132]
[f 2 1]未使用[n][e]

[msg Item_133]
[f 2 1]未使用[n][e]

[msg Item_134]
[f 2 1]未使用[n][e]

[msg Item_135]
[f 2 1]未使用[n][e]

[msg Item_136]
[f 2 1]未使用[n][e]

[msg Item_137]
[f 2 1]未使用[n][e]

[msg Item_138]
[f 2 1]未使用[n][e]

[msg Item_139]
[f 2 1]未使用[n][e]

[msg Item_13A]
[f 2 1]未使用[n][e]

[msg Item_13B]
[f 2 1]未使用[n][e]

[msg Item_13C]
[f 2 1]未使用[n][e]

[msg Item_13D]
[f 2 1]未使用[n][e]

[msg Item_13E]
[f 2 1]未使用[n][e]

[msg Item_13F]
[f 2 1]未使用[n][e]

[msg Item_140]
[f 2 1]未使用[n][e]

[msg Item_141]
[f 2 1]未使用[n][e]

[msg Item_142]
[f 2 1]未使用[n][e]

[msg Item_143]
[f 2 1]未使用[n][e]

[msg Item_144]
[f 2 1]未使用[n][e]

[msg Item_145]
[f 2 1]未使用[n][e]

[msg Item_146]
[f 2 1]未使用[n][e]

[msg Item_147]
[f 2 1]未使用[n][e]

[msg Item_148]
[f 2 1]未使用[n][e]

[msg Item_149]
[f 2 1]未使用[n][e]

[msg Item_14A]
[f 2 1]未使用[n][e]

[msg Item_14B]
[f 2 1]未使用[n][e]

[msg Item_14C]
[f 2 1]未使用[n][e]

[msg Item_14D]
[f 2 1]未使用[n][e]

[msg Item_14E]
[f 2 1]未使用[n][e]

[msg Item_14F]
[f 2 1]未使用[n][e]

[msg Item_150]
[f 2 1]未使用[n][e]

[msg Item_151]
[f 2 1]未使用[n][e]

[msg Item_152]
[f 2 1]未使用[n][e]

[msg Item_153]
[f 2 1]未使用[n][e]

[msg Item_154]
[f 2 1]未使用[n][e]

[msg Item_155]
[f 2 1]未使用[n][e]

[msg Item_156]
[f 2 1]未使用[n][e]

[msg Item_157]
[f 2 1]未使用[n][e]

[msg Item_158]
[f 2 1]未使用[n][e]

[msg Item_159]
[f 2 1]未使用[n][e]

[msg Item_15A]
[f 2 1]未使用[n][e]

[msg Item_15B]
[f 2 1]未使用[n][e]

[msg Item_15C]
[f 2 1]未使用[n][e]

[msg Item_15D]
[f 2 1]未使用[n][e]

[msg Item_15E]
[f 2 1]未使用[n][e]

[msg Item_15F]
[f 2 1]未使用[n][e]

[msg Item_160]
[f 2 1]未使用[n][e]

[msg Item_161]
[f 2 1]未使用[n][e]

[msg Item_162]
[f 2 1]未使用[n][e]

[msg Item_163]
[f 2 1]未使用[n][e]

[msg Item_164]
[f 2 1]未使用[n][e]

[msg Item_165]
[f 2 1]未使用[n][e]

[msg Item_166]
[f 2 1]未使用[n][e]

[msg Item_167]
[f 2 1]未使用[n][e]

[msg Item_168]
[f 2 1]未使用[n][e]

[msg Item_169]
[f 2 1]未使用[n][e]

[msg Item_16A]
[f 2 1]未使用[n][e]

[msg Item_16B]
[f 2 1]未使用[n][e]

[msg Item_16C]
[f 2 1]未使用[n][e]

[msg Item_16D]
[f 2 1]未使用[n][e]

[msg Item_16E]
[f 2 1]未使用[n][e]

[msg Item_16F]
[f 2 1]未使用[n][e]

[msg Item_170]
[f 2 1]未使用[n][e]

[msg Item_171]
[f 2 1]未使用[n][e]

[msg Item_172]
[f 2 1]未使用[n][e]

[msg Item_173]
[f 2 1]未使用[n][e]

[msg Item_174]
[f 2 1]未使用[n][e]

[msg Item_175]
[f 2 1]未使用[n][e]

[msg Item_176]
[f 2 1]未使用[n][e]

[msg Item_177]
[f 2 1]未使用[n][e]

[msg Item_178]
[f 2 1]未使用[n][e]

[msg Item_179]
[f 2 1]未使用[n][e]

[msg Item_17A]
[f 2 1]未使用[n][e]

[msg Item_17B]
[f 2 1]未使用[n][e]

[msg Item_17C]
[f 2 1]未使用[n][e]

[msg Item_17D]
[f 2 1]未使用[n][e]

[msg Item_17E]
[f 2 1]未使用[n][e]

[msg Item_17F]
[f 2 1]未使用[n][e]

[msg Item_180]
[f 2 1]未使用[n][e]

[msg Item_181]
[f 2 1]未使用[n][e]

[msg Item_182]
[f 2 1]未使用[n][e]

[msg Item_183]
[f 2 1]未使用[n][e]

[msg Item_184]
[f 2 1]未使用[n][e]

[msg Item_185]
[f 2 1]未使用[n][e]

[msg Item_186]
[f 2 1]未使用[n][e]

[msg Item_187]
[f 2 1]未使用[n][e]

[msg Item_188]
[f 2 1]未使用[n][e]

[msg Item_189]
[f 2 1]未使用[n][e]

[msg Item_18A]
[f 2 1]未使用[n][e]

[msg Item_18B]
[f 2 1]未使用[n][e]

[msg Item_18C]
[f 2 1]未使用[n][e]

[msg Item_18D]
[f 2 1]未使用[n][e]

[msg Item_18E]
[f 2 1]未使用[n][e]

[msg Item_18F]
[f 2 1]未使用[n][e]

[msg Item_190]
[f 2 1]未使用[n][e]

[msg Item_191]
[f 2 1]未使用[n][e]

[msg Item_192]
[f 2 1]未使用[n][e]

[msg Item_193]
[f 2 1]未使用[n][e]

[msg Item_194]
[f 2 1]未使用[n][e]

[msg Item_195]
[f 2 1]未使用[n][e]

[msg Item_196]
[f 2 1]未使用[n][e]

[msg Item_197]
[f 2 1]未使用[n][e]

[msg Item_198]
[f 2 1]未使用[n][e]

[msg Item_199]
[f 2 1]未使用[n][e]

[msg Item_19A]
[f 2 1]未使用[n][e]

[msg Item_19B]
[f 2 1]未使用[n][e]

[msg Item_19C]
[f 2 1]未使用[n][e]

[msg Item_19D]
[f 2 1]未使用[n][e]

[msg Item_19E]
[f 2 1]未使用[n][e]

[msg Item_19F]
[f 2 1]未使用[n][e]

[msg Item_1A0]
[f 2 1]未使用[n][e]

[msg Item_1A1]
[f 2 1]未使用[n][e]

[msg Item_1A2]
[f 2 1]未使用[n][e]

[msg Item_1A3]
[f 2 1]未使用[n][e]

[msg Item_1A4]
[f 2 1]未使用[n][e]

[msg Item_1A5]
[f 2 1]未使用[n][e]

[msg Item_1A6]
[f 2 1]未使用[n][e]

[msg Item_1A7]
[f 2 1]未使用[n][e]

[msg Item_1A8]
[f 2 1]未使用[n][e]

[msg Item_1A9]
[f 2 1]未使用[n][e]

[msg Item_1AA]
[f 2 1]未使用[n][e]

[msg Item_1AB]
[f 2 1]未使用[n][e]

[msg Item_1AC]
[f 2 1]未使用[n][e]

[msg Item_1AD]
[f 2 1]未使用[n][e]

[msg Item_1AE]
[f 2 1]未使用[n][e]

[msg Item_1AF]
[f 2 1]未使用[n][e]

[msg Item_1B0]
[f 2 1]未使用[n][e]

[msg Item_1B1]
[f 2 1]未使用[n][e]

[msg Item_1B2]
[f 2 1]未使用[n][e]

[msg Item_1B3]
[f 2 1]未使用[n][e]

[msg Item_1B4]
[f 2 1]未使用[n][e]

[msg Item_1B5]
[f 2 1]未使用[n][e]

[msg Item_1B6]
[f 2 1]未使用[n][e]

[msg Item_1B7]
[f 2 1]未使用[n][e]

[msg Item_1B8]
[f 2 1]未使用[n][e]

[msg Item_1B9]
[f 2 1]未使用[n][e]

[msg Item_1BA]
[f 2 1]未使用[n][e]

[msg Item_1BB]
[f 2 1]未使用[n][e]

[msg Item_1BC]
[f 2 1]未使用[n][e]

[msg Item_1BD]
[f 2 1]未使用[n][e]

[msg Item_1BE]
[f 2 1]未使用[n][e]

[msg Item_1BF]
[f 2 1]未使用[n][e]

[msg Item_1C0]
[f 2 1]未使用[n][e]

[msg Item_1C1]
[f 2 1]未使用[n][e]

[msg Item_1C2]
[f 2 1]未使用[n][e]

[msg Item_1C3]
[f 2 1]未使用[n][e]

[msg Item_1C4]
[f 2 1]未使用[n][e]

[msg Item_1C5]
[f 2 1]未使用[n][e]

[msg Item_1C6]
[f 2 1]未使用[n][e]

[msg Item_1C7]
[f 2 1]未使用[n][e]

[msg Item_1C8]
[f 2 1]未使用[n][e]

[msg Item_1C9]
[f 2 1]未使用[n][e]

[msg Item_1CA]
[f 2 1]未使用[n][e]

[msg Item_1CB]
[f 2 1]未使用[n][e]

[msg Item_1CC]
[f 2 1]未使用[n][e]

[msg Item_1CD]
[f 2 1]未使用[n][e]

[msg Item_1CE]
[f 2 1]未使用[n][e]

[msg Item_1CF]
[f 2 1]未使用[n][e]

[msg Item_1D0]
[f 2 1]未使用[n][e]

[msg Item_1D1]
[f 2 1]未使用[n][e]

[msg Item_1D2]
[f 2 1]未使用[n][e]

[msg Item_1D3]
[f 2 1]未使用[n][e]

[msg Item_1D4]
[f 2 1]未使用[n][e]

[msg Item_1D5]
[f 2 1]未使用[n][e]

[msg Item_1D6]
[f 2 1]未使用[n][e]

[msg Item_1D7]
[f 2 1]未使用[n][e]

[msg Item_1D8]
[f 2 1]未使用[n][e]

[msg Item_1D9]
[f 2 1]未使用[n][e]

[msg Item_1DA]
[f 2 1]未使用[n][e]

[msg Item_1DB]
[f 2 1]未使用[n][e]

[msg Item_1DC]
[f 2 1]未使用[n][e]

[msg Item_1DD]
[f 2 1]未使用[n][e]

[msg Item_1DE]
[f 2 1]未使用[n][e]

[msg Item_1DF]
[f 2 1]未使用[n][e]

[msg Item_1E0]
[f 2 1]未使用[n][e]

[msg Item_1E1]
[f 2 1]未使用[n][e]

[msg Item_1E2]
[f 2 1]未使用[n][e]

[msg Item_1E3]
[f 2 1]未使用[n][e]

[msg Item_1E4]
[f 2 1]未使用[n][e]

[msg Item_1E5]
[f 2 1]未使用[n][e]

[msg Item_1E6]
[f 2 1]未使用[n][e]

[msg Item_1E7]
[f 2 1]未使用[n][e]

[msg Item_1E8]
[f 2 1]未使用[n][e]

[msg Item_1E9]
[f 2 1]未使用[n][e]

[msg Item_1EA]
[f 2 1]未使用[n][e]

[msg Item_1EB]
[f 2 1]未使用[n][e]

[msg Item_1EC]
[f 2 1]未使用[n][e]

[msg Item_1ED]
[f 2 1]未使用[n][e]

[msg Item_1EE]
[f 2 1]未使用[n][e]

[msg Item_1EF]
[f 2 1]未使用[n][e]

[msg Item_1F0]
[f 2 1]未使用[n][e]

[msg Item_1F1]
[f 2 1]未使用[n][e]

[msg Item_1F2]
[f 2 1]未使用[n][e]

[msg Item_1F3]
[f 2 1]未使用[n][e]

[msg Item_1F4]
[f 2 1]未使用[n][e]

[msg Item_1F5]
[f 2 1]未使用[n][e]

[msg Item_1F6]
[f 2 1]未使用[n][e]

[msg Item_1F7]
[f 2 1]未使用[n][e]

[msg Item_1F8]
[f 2 1]未使用[n][e]

[msg Item_1F9]
[f 2 1]未使用[n][e]

[msg Item_1FA]
[f 2 1]未使用[n][e]

[msg Item_1FB]
[f 2 1]未使用[n][e]

[msg Item_1FC]
[f 2 1]未使用[n][e]

[msg Item_1FD]
[f 2 1]未使用[n][e]

[msg Item_1FE]
[f 2 1]未使用[n][e]

[msg Item_1FF]
[f 2 1]未使用[n][e]

