[msg MSG_000_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 1 65535 65535 0 0][vp 1 0 0 1 0 0]Buenas tardes.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 2 0 0][f 4 23 0 222 0 25 25]He venido a ver a Koromaru. ¿Crees que nos servirá de ayuda?[n][w][e]

[sel SEL_001_0_0 top]
[f 2 1]Estará bien.[e]
[f 2 1]No estoy segura.[e]
[f 2 1]Todavía es pronto.[e]

[msg MSG_002_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 1 65535 65535 0 0][vp 1 0 0 3 0 0]Me alegro.[n][w][e]
[f 2 1][bup 222 1 65535 65535 0 0][vp 1 0 0 4 0 0]Bueno, con lo fiel que es, no me preocupa más de la cuenta.[n][w][e]

[msg MSG_003_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 5 0 0]No hace falta que te exijas tanto. Yo ayudaré también en lo que buenamente pueda.[n][w][e]
[f 2 1][bup 222 4 65535 65535 0 0][vp 1 0 0 6 0 0][f 4 23 0 222 4 25 25]Uy, ¿te gustan más los gatos? Pues entonces poco puedo hacer.[n][w][e]

[msg MSG_004_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 7 0 0]Pues sí.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 8 0 0]No hace falta correr, ya tendréis tiempo de sobra para conoceros.[n][w][e]

[msg MSG_005_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 9 0 0]Si tienes dudas, pregúntame cuando sea.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 10 0 0]Es lo más justo. Al fin y al cabo, fui yo quien pidió que Koromaru se uniera.[n][w][e]

[msg MSG_006_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 1 0 0 11 0 0]¡Yo estoy completamente a favor de que Koromaru se una![n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0][vp 1 0 0 12 0 0]Hasta incluiré clases de entrenamiento del maestro.[n][w][e]

[msg MSG_007_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 13 0 0]Me parece a mí que Korocito ya tiene más disciplina que tú.[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 14 0 0]A ver si tú eres capaz de quedarte quieto si te lo piden.[n][w][e]

[msg MSG_008_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 65535 65535 0 0][vp 1 0 0 15 0 0]¡No me compares con un perro![n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0][vp 1 0 0 16 0 0][f 4 23 0 3 0 25 25]Tengo buena disciplina y sé seguir órdenes. Creo...[n][w][e]

[msg MSG_009_0_0 [Yukari Takeba]]
[f 2 1][bup 2 6 65535 65535 0 0][vp 1 0 0 17 0 0]Sí, eres superconvincente.[n][w][e]

[msg MSG_010_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 1 0 0 18 0 0]Hablando de otro tema, señor director..., las clases de verano...[n][w][e]

[msg MSG_011_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 19 0 0]Ah, sí, estoy al tanto del plan de Kirijo.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 20 0 0]Me parece buena idea, así que adelante.[n][w][e]

[msg MSG_012_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 65535 65535 0 0][vp 1 0 0 21 0 0]¡No! ¿Por qué le parece bien?[n][w][e]

[msg MSG_013_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 22 0 0]Uy, ¿me estoy metiendo donde no me llaman?[n][w][e]

[msg MSG_014_0_0 [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0][vp 1 0 0 23 0 0]Qué forma de dejar escapar a mi amor de verano... Se desvanece delante de mis narices...[n][w][e]
[f 2 1][bup 3 3 65535 65535 0 0][vp 1 0 0 24 0 0]Adiós, urbanita guapísima de mi corazón que me aguarda en la costa...[n][w][e]

[msg MSG_015_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 25 0 0]Ciudad o playa. Elige.[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 26 0 0]Aunque no tuvieras clase, te pasarías el día por la estación.[n][w][e]
[f 2 1][bup 2 2 65535 65535 0 0][vp 1 0 0 27 0 0][f 4 23 0 2 2 25 25]Deberías aceptar tu destino.[n][w][e]

[msg MSG_016_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 28 0 0]Ah, por cierto, señor director...[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 29 0 0]Iba a decirnos algo antes de que llegase [nl].[n][w][e]

[msg MSG_017_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 30 0 0]¿Mmm...? Ah, sí.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 31 0 0]Aparte de mis innecesarias intromisiones, quiero pediros otra cosa.[n][w][e]

[msg MSG_018_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 32 0 0]¿Estáis todos libres ahora mismo?[n][w][e]

[msg MSG_019_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 33 0 0]Creo que va siendo hora de que os hagáis una revisión médica.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 34 0 0]¿Sabéis dónde está el hospital Memorial de Tatsumi?[n][w][e]

[msg MSG_020_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 35 0 0]Ah, ahí fue donde trataron a Sanada.[n][w][e]

[msg MSG_021_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 36 0 0]Con todo lo que habéis peleado últimamente, os conviene mantener una buena salud física.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 37 0 0]Si vuestro cuerpo se resiente por culpa de vuestras Personas, mala señal.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 38 0 0]Os podéis acercar al hospital cuando salgáis de clase, que os pilla de paso.[n][w][e]

[msg MSG_022_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 39 0 0]Ya. Aun así, entiendo que no contabais con esto.[n][w][e]

[msg MSG_023_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 1 65535 65535 0 0][vp 1 0 0 40 0 0]No te preocupes. Como bien dice el dicho: "Más vale prevenir que llorar". Digo, curar.[n][w][e]

[msg MSG_024_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 41 0 0]Iremos haciendo las revisiones poco a poco e individualmente.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 42 0 0]Podéis decidir entre vosotros el orden en el que ir y la fecha.[n][w][e]

[msg MSG_025_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 1 65535 65535 0 0][vp 1 0 0 43 0 0]¡Para ir a esta revisión no hace falta estudiar! Ja, ja, es broma.[n][w][e]

[msg MSG_026_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 1 65535 65535 0 0][vp 1 0 0 44 0 0]Ah, llevaos los Evocadores, por si acaso os pinchan.[n][w][e]

