[msg MSG_000_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 1 0 0]He pensado que es buen momento para renovar el uniforme del equipo.[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 2 0 0]¿Qué te parecería cambiar a mallas para correr? Al parecer, reducen la resistencia al viento.[n][w][e]

[msg MSG_001_0_0 [Chica de pelo reluciente]]
[f 2 1][vp 1 0 0 3 0 0][f 5 21 0 10]Aaaanda, mira tú por dónde. ¡Si es Nishiwaki![n][w][e]

[msg MSG_002_0_0 [Chica con medias negras]]
[f 2 1][vp 1 0 0 4 0 0][f 5 21 0 11]¿Es tu nueva pareja?[n][w][e]
[f 2 1][vp 1 0 0 5 0 0][f 5 21 0 11]Vas saltando de flor en flor, ¿eh? Magnífico, Nishiwaki.[n][w][e]

[msg MSG_003_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 6 0 0]No estamos saliendo. Es una amiga del equipo.[n][w][e]

[msg MSG_004_0_0 [Chica con medias negras]]
[f 2 1][vp 1 0 0 7 0 0][f 5 21 0 11]Venga ya, no hace falta que lo escondas. Di las cosas como son.[n][w][e]
[f 2 1][vp 1 0 0 8 0 0][f 5 21 0 11]Me sorprende que estés con alguien tan guapa. Igual yo también debería ser encargada de un equipo.[n][w][e]

[msg MSG_005_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 3 65535 65535 0 0][vp 1 0 0 9 0 0]Te equivocas del todo, como siempre.[n][w][e]

[msg MSG_006_0_0 [Chica de pelo reluciente]]
[f 2 1][vp 1 0 0 10 0 0][f 5 21 0 10]Ni se te ocurra hacerlo. Te pasarías el día detrás de todo el mundo.[n][w][e]
[f 2 1][vp 1 0 0 11 0 0][f 5 21 0 10]Además, las chicas musculosas no son muy atractivas.[n][w][e]

[msg MSG_007_0_0 [Chica con medias negras]]
[f 2 1][vp 1 0 0 12 0 0][f 5 21 0 11]Oye, baja la voz, que su novia está ahí mismo. Me da pena por ella y todo.[n][w][e]

[msg MSG_008_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 2 65535 65535 0 0][vp 1 0 0 13 0 0]Si es lo que quieres, no voy a detenerte, pero yo que tú me buscaría pareja en otra parte.[n][w][e]
[f 2 1][bup 106 2 65535 65535 0 0][vp 1 0 0 14 0 0]Ser encargada no es nada fácil. No tendrías tiempo para andar pegando chicles en los zapateros de la gente.[n][w][e]

[msg MSG_009_0_0 [Chica de pelo reluciente]]
[f 2 1][vp 1 0 0 15 0 0][f 5 21 0 10]¿P-pero qué dices? N-no sé de qué me hablas.[n][w][e]

[msg MSG_010_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 16 0 0]Claro que no, solo era un ejemplo que se me acaba de ocurrir.[n][w][e]

[msg MSG_011_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 2 65535 65535 0 0][vp 1 0 0 17 0 0]¿Qué pasa? ¿He dicho algo que te haya molestado?[n][w][e]

[msg MSG_012_0_0 [Chica con medias negras]]
[f 2 1][vp 1 0 0 18 0 0][f 5 21 0 11]Para nada.[n][w][e]

[msg MSG_013_0_0 [Chica de pelo reluciente]]
[f 2 1][vp 1 0 0 19 0 0][f 5 21 0 10]E-eh, vámonos ya.[n][w][e]

[msg MSG_014_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 3 65535 65535 0 0][vp 1 0 0 20 0 0]Siento haberte implicado en esto.[n][w][e]

[sel SEL_015_0_0 top]
[f 2 1]¿Amigas tuyas?[e]
[f 2 1]No te preocupes.[e]

[msg MSG_016_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 3 65535 65535 0 0][vp 1 0 0 21 0 0]Las conozco, pero no mucho.[n][w][e]

[msg MSG_017_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 22 0 0]Debería ponerte al corriente.[n][w][e]

[msg MSG_018_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 3 65535 65535 0 0][vp 1 0 0 23 0 0][f 5 13 12 5 106]No, no tendrías que haber lidiado con eso. Lo siento.[n][w][e]

[msg MSG_019_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 24 0 0]Debería ponerte al corriente antes de que te hagas una idea equivocada.[n][w][e]

[msg MSG_020_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 25 0 0]Vamos a sentarnos.[n][w][e]

[msg MSG_021_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 26 0 0]La chica con medias negras... fue a la misma escuela que yo.[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 27 0 0]Había un chico en el equipo de baloncesto que me pidió salir y estuvimos juntos.[n][w][e]

[msg MSG_021_5_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 2 65535 65535 0 0][vp 1 0 0 28 0 0]¡Pero resultó que también estaba con ella a la vez![n][w][e]
[f 2 1][bup 106 2 65535 65535 0 0][vp 1 0 0 29 0 0]Cuando ella se enteró, me acusó de haberle robado al novio. Y eso que yo también era una víctima.[n][w][e]
[f 2 1][bup 106 2 65535 65535 0 0][vp 1 0 0 30 0 0]Me echó la culpa porque yo era la encargada del equipo de baloncesto. Un disparate, ¿verdad?[n][w][e]

[msg MSG_021_7_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 3 65535 65535 0 0][vp 1 0 0 31 0 0]Y, cuando me encargué del equipo de atletismo del instituto, volvió a ponerse en mi contra.[n][w][e]
[f 2 1][bup 106 3 65535 65535 0 0][vp 1 0 0 32 0 0]Lo único que quiero es apoyar a los demás para que puedan dar lo mejor de sí mismos.[n][w][e]

[msg MSG_022_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 3 65535 65535 0 0][vp 1 0 0 33 0 0]¿Recuerdas el chicle del zapatero? Pues seguramente sea cosa suya. Todavía me guarda rencor.[n][w][e]

[msg MSG_023_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 2 65535 65535 0 0][vp 1 0 0 34 0 0]Esas chicas tienen demasiado tiempo libre. Solo se quejan y chismorrean.[n][w][e]
[f 2 1][bup 106 2 65535 65535 0 0][vp 1 0 0 35 0 0]¡¿Por qué no hacen algo más productivo?! ¡Ellas sí que se merecen que Ekoda les dé la chapa![n][w][e]
[f 2 1][bup 106 2 65535 65535 0 0][vp 1 0 0 36 0 0]¿Que no estoy pensando en mi futuro? ¡Díselo a ellas! A mí déjame en paz.[n][w][e]

[msg MSG_024_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 4 65535 65535 0 0][vp 1 0 0 37 0 0]¡Ah! Por cierto, perdón por lo que te han dicho antes...[n][w][e]
[f 2 1][bup 106 3 65535 65535 0 0][vp 1 0 0 38 0 0][f 4 23 0 1 3 25 25]Han dicho que eras mi novia. Seguro que eso te ha hecho sentir incómoda, ¿no?[n][w][e]

[sel SEL_025_0_0 top]
[f 2 1]Me halaga.[f 2 9 1 1 346][e]
[f 2 1]No pasa nada.[e]
[f 2 1]Podría ser un problema.[e]

[msg MSG_026_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 4 65535 65535 0 0][vp 1 0 0 39 0 0][f 5 13 12 5 106]¡O-oye![n][w][e]
[f 2 1][bup 106 4 65535 65535 0 0][vp 1 0 0 40 0 0]¿Cómo puedes decir algo así con tanta calma? ¿A cuántas personas más les has dicho lo mismo?[n][w][e]
[f 2 1][bup 106 4 65535 65535 0 0][vp 1 0 0 41 0 0]En las relaciones, no se debe jugar nunca con los sentimientos.[n][w][e]

[msg MSG_027_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 42 0 0][f 5 13 12 5 106]Sí, gracias...[n][w][e]
[f 2 1][bup 106 4 65535 65535 0 0][vp 1 0 0 43 0 0][f 4 23 0 1 4 25 25]¡P-pero debería importarte! ¡Al fin y al cabo, soy una chica de instituto![n][w][e]

[msg MSG_028_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 3 65535 65535 0 0][vp 1 0 0 44 0 0]T-tampoco hacía falta ponerse tan brusca...[n][w][e]

[msg MSG_029_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 3 65535 65535 0 0][vp 1 0 0 45 0 0]Mmm, ¿por qué me siento así? Después de todo, solo estamos en el mismo equipo.[n][w][e]

[msg MSG_030_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 46 0 0]Ah, sí.[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 47 0 0]No le vayas a contar a Kaz ni a nadie lo de los cuernos, ¿vale?[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 48 0 0]Eres la única que lo sabe, [nl].[n][w][e]

[msg MSG_031_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 4 65535 65535 0 0][vp 1 0 0 49 0 0]¡Ah, otra cosa![n][w][e]
[f 2 1][bup 106 4 65535 65535 0 0][vp 1 0 0 50 0 0]Dejé a ese imbécil infiel hace mucho tiempo. ¡Solo para que lo sepas![n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 51 0 0][f 4 23 0 1 1 25 25]Pero ¿qué estoy diciendo? Si es algo que ni te va ni te viene. Ja, ja...[n][w][e]

[msg MND_032_0_0]
[f 2 1]Yuko parece inquieta por algún motivo.[n][w][e]
[f 2 1]Siento que mi relación con ella se ha fortalecido.[n][w][e]

[msg MSG_033_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 52 0 0]Vaya, se nos ha echado la hora encima. Deberíamos volver a casa.[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 53 0 0][f 4 23 0 1 1 25 25]¡Nos vemos![n][w][e]

[msg MND_034_0_0]
[f 2 1]Tras despedirme de Yuko,[n]he decidido volver a la residencia.[n][w][e]

