[msg MSG_000_0_0 [Bebe]]
[f 2 1][bup 112 0 65535 65535 0 0][vp 3 0 65535 11899 0 0]¡Qué bueno! ¡Menuda bendición![n][w][e]

[msg MSG_001_0_0 [Bebe]]
[f 2 1][bup 112 2 65535 65535 0 0]Pero no puedo evitar estar nervioso.[n][w][e]

[msg MSG_002_0_0 [Bebe]]
[f 2 1][bup 112 2 65535 65535 0 0][vp 3 0 65535 11867 0 0]No es momento de obsesionarme con la comida.[n][w][e]
[f 2 1][bup 112 2 65535 65535 0 0]Tengo que darme prisa y terminar el kimono.[n][w][e]

[sel SEL_003_0_0 top]
[f 2 1]Ve a terminarlo ya.[e]
[f 2 1]Paciencia.[e]
[f 2 1]Relájate.[e]

[msg MSG_004_0_0 [Bebe]]
[f 2 1][bup 112 2 65535 65535 0 0][vp 3 0 65535 11904 0 0]¡No tengo máquina de coser chez moi! ¡Tengo que aguantar hasta que volvamos al instituto![n][w][e]
[f 2 1][bup 112 2 65535 65535 0 0]Un verdadero samurái debe perseverar en todo lo que la vida le depare.[n][w][e]

[msg MND_005_0_0 [DEV: Internal MES]]
[f 2 1]Bebe parece estar nervioso.[n][w][e]
[f 2 1]Siento que hoy nuestra relación no ha cambiado nada...[n][w][e]

[msg MSG_006_0_0 [Bebe]]
[f 2 1][bup 112 0 65535 65535 0 0][vp 3 0 65535 11839 0 0][f 5 13 15 15 112]¡Tienes razón! Un verdadero samurái debe perseverar en todo lo que la vida le depare.[n][w][e]

[msg MND_007_0_0 [DEV: Internal MES]]
[f 2 1]Bebe parece motivado.[n][w][e]
[f 2 1]Hoy has aprendido un poco más sobre él.[n][w][e]

[msg MSG_008_0_0 [Bebe]]
[f 2 1][bup 112 4 65535 65535 0 0][vp 3 0 65535 11801 0 0]¡¿Que me relaje?![n][w][e]
[f 2 1][bup 112 1 65535 65535 0 0][f 4 23 0 112 1 25 25][f 5 13 15 30 112]¡Por supuesto! Las prisas no ayudarán. Debo mantener la compostura y relajarme.[n][w][e]

[msg MND_009_0_0 [DEV: Internal MES]]
[f 2 1]Bebe parece muy motivado.[n][w][e]
[f 2 1]Siento que hoy nuestra relación se ha estrechado.[n][w][e]

[msg MSG_010_0_0 [Bebe]]
[f 2 1][bup 112 0 65535 65535 0 0][vp 3 0 65535 11900 0 0]Eso me recuerda... Hay un sabio proverbio japonés para esta misma situación.[n][w][e]
[f 2 1][bup 112 0 65535 65535 0 0]¡No se puede luchar con el estómago vacío! ¡Así que ahora toca comer![n][w][e]

[msg MND_011_0_0 [DEV: Internal MES]]
[f 2 1]Tras disfrutar juntos de la comida, he vuelto a la residencia.[n][w][e]

