[msg MSG_000_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 1 0 0][nf]...[n][w][e]

[msg MSG_000_3_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 1 0][vp 0 0 0 2 0 0]...[n][w][e]

[msg MSG_000_5_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 1 0][vp 1 0 0 3 0 0]Es solo que... me apetecía decir tu nombre.[n][w][e]

[msg MSG_000_6_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 1 0][vp 0 0 0 4 0 0]...[n][w][e]

[msg MSG_000_7_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 1 0][vp 1 0 0 5 0 0]No debería ser para tanto, la verdad...[n][w][e]

[msg MSG_000_9_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 1 0][vp 1 0 0 6 0 0][f 5 13 4 5 5]No me mires así.[n][w][e]

[msg MSG_001_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 1 0][vp 1 0 0 7 0 0][nf], como me sigas mirando así...[n][w][e]
[f 2 1][bup 5 0 65535 65535 1 0][vp 0 0 0 8 0 0]...[n][w][e]

[msg MND_002_0_0 [Mensaje interno]]
[f 2 1]He compartido una tarde especial con Mitsuru.[n][w][e]
[f 2 1]Siento que entre nosotras hay un vínculo irrompible.[n][w][e]

