[msg MSG_000_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 1 0 0]¿No te parece interesante que los rayos del sol parezcan más brillantes en invierno que en verano?[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 2 0 0]Igual se debe a que el sol se encuentra más bajo y no hace falta mirar hacia arriba para verlo.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 3 0 0]Me he acostumbrado a estas vistas, pero nunca son las mismas.[n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 4 0 0]Podrías decir lo mismo sobre la rutina diaria de las personas.[n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 5 0 0]O sobre la vida misma...[n][w][e]

[msg MSG_001_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 6 0 0]Ya casi es el día de la promesa.[n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 7 0 0][f 4 23 0 1 3 25 25]El 31 de enero...[n][w][e]

[sel SEL_002_0_0 top]
[f 2 1]Es verdad.[e]
[f 2 1]No me había dado cuenta.[e]

[msg MSG_003_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 8 0 0][f 5 13 22 15 7]Cada vez que subo aquí, me pongo a reflexionar.[n][w][e]
[f 2 1][bup 7 1 65535 65535 0 0][vp 1 0 0 9 0 0][f 4 23 0 1 1 25 25]Cosas como... "No puedo permitir que esto acabe". "Debo protegerlos"[n][w][e]

[msg MSG_004_0_0 [Aigis]]
[f 2 1][bup 7 1 65535 65535 0 0][vp 1 0 0 10 0 0][f 4 23 0 1 1 25 25][f 5 13 22 5 7]Ojalá pudiera estar tranquila.[n][w][e]

[msg MSG_005_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 11 0 0]Desde el otro día, he intentado razonar con más rigor.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 12 0 0]He pensado en la anciana y en Chai, y también en Kiyoshi...[n][w][e]

[msg MSG_006_0_0 [Aigis]]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 13 0 0]Me pregunto si Chai estuvo sola hasta que falleció...[n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 14 0 0]En un lugar donde nadie pudiera encontrarla...[n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 15 0 0]Creo que la señora quería estar con ella hasta el final.[n][w][e]

[msg MSG_007_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 16 0 0]Vivir es conectar con las personas, pero todo llega a su fin y las despedidas son inevitables.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 17 0 0]Me apena pensar en ello, pero tú y yo también nos despediremos algún día.[n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 18 0 0][f 4 23 0 1 3 25 25]Y entonces..., no podré volver a verte.[n][w][e]

[msg MSG_008_0_0 [Aigis]]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 19 0 0]Hay muchas cosas que no comprendo sobre la vida. Está repleta de dolor.[n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 20 0 0]Conoces a las personas, creas amistades y pasas tiempo con ellas..., y luego desaparecen, dejándote atrás.[n][w][e]
[f 2 1][bup 7 10 65535 65535 0 0][vp 1 0 0 21 0 0][f 4 23 0 1 10 25 25]Dejándote... sola.[n][w][e]
[f 2 1][bup 7 10 65535 65535 0 0][vp 0 0 0 22 0 0][f 4 23 0 1 10 25 25]...[n][w][e]

[msg MSG_009_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 23 0 0]Soy una máquina.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 24 0 0]Por muy humano que se vuelva mi corazón, mi cuerpo nunca será de carne y hueso.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 25 0 0]Mientras me realicen labores de mantenimiento y me reemplacen las partes rotas, existiré eternamente.[n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 26 0 0][f 4 23 0 1 3 25 25]Entiendo que esto es lo que soy.[n][w][e]

[msg MSG_010_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 27 0 0]No hay dos paisajes iguales. Ni tampoco dos días iguales.[n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 28 0 0][f 4 23 0 1 3 25 25]Es natural que todo desaparezca, vuelva y cambie constantemente.[n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 29 0 0][f 4 23 0 1 3 25 25]La vida es finita y efímera.[n][w][e]

[msg MSG_010_3_0 [Aigis]]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 30 0 0]Es lo que la hace tan valiosa, y por lo que sentimos que hay que apreciarla.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 31 0 0][f 4 23 0 1 0 25 25]Que dos personas se encuentren en este caótico flujo espaciotemporal es casi un milagro...[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 32 0 0][f 4 23 0 1 0 25 25]Por eso forjar vínculos y crear relaciones nos aporta felicidad.[n][w][e]

[msg MSG_010_5_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 33 0 0]A eso se reduce la vida.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 34 0 0]Es agridulce, y tener fin lo hace incluso más hermoso...[n][w][e]

[msg MSG_010_7_0 [Aigis]]
[f 2 1][bup 7 2 65535 65535 0 0][vp 1 0 0 35 0 0]Si me paro a pensarlo, no hay tiempo para dudar.[n][w][e]
[f 2 1][bup 7 2 65535 65535 0 0][vp 1 0 0 36 0 0]Debo decirte lo que siento.[n][w][e]

[msg MSG_011_0_0 [Aigis]]
[f 2 1][bup 7 2 65535 65535 0 0][vp 1 0 0 37 0 0]Me gustaría pasar tiempo contigo.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 38 0 0][f 4 23 0 1 0 25 25]Quiero contemplar nuevos paisajes e ir a lugares nuevos contigo.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 39 0 0][f 4 23 0 1 0 25 25]Para compartir nuevas experiencias... y también muchos más recuerdos.[n][w][e]

[msg MSG_012_0_0 [Aigis]]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 40 0 0]Sé que estoy pidiendo mucho.[n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 41 0 0]Sé que no es justo que alguien como yo acapare tu preciado tiempo...[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 42 0 0][f 4 23 0 1 0 25 25]Pero, aun así, deseo ser tu mejor amiga.[n][w][e]

[sel SEL_013_0_0 top]
[f 2 1]Ya eres mi mejor amiga.[e]
[f 2 1]Qué deseo tan bonito.[e]

[msg MSG_014_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 43 0 0]¡...![n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 44 0 0][f 4 23 0 1 3 25 25]L-lo siento, no sé qué decir.[n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 45 0 0][f 4 23 0 1 3 25 25]Pensaba que con soltarlo todo sería suficiente.[n][w][e]

[msg MSG_014_3_0 [Aigis]]
[f 2 1][bup 7 1 65535 65535 0 0][vp 1 0 0 46 0 0]Pero oírte decir eso me agrada.[n][w][e]
[f 2 1][bup 7 1 65535 65535 0 0][vp 0 0 0 47 0 0]...[n][w][e]

[msg MSG_015_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 48 0 0]¡...![n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 49 0 0]L-lo siento, no sé qué decir.[n][w][e]

[msg MSG_015_3_0 [Aigis]]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 50 0 0]Me daba miedo no ser más que una carga para ti.[n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0][vp 0 0 0 51 0 0]...[n][w][e]

[msg MSG_016_0_0 [Aigis]]
[f 2 1][bup 7 1 65535 65535 0 0][vp 1 0 0 52 0 0]Muchas gracias, [nf].[n][w][e]
[f 2 1][bup 7 1 65535 65535 0 0][vp 1 0 0 53 0 0]Nunca olvidaré el rato que hemos pasado hoy.[n][w][e]

[msg MSG_017_0_0 [Aigis]]
[f 2 1][bup 7 1 65535 65535 0 0][vp 1 0 0 54 0 0]Deberíamos volver.[n][w][e]
[f 2 1][bup 7 1 65535 65535 0 0][vp 1 0 0 55 0 0]No quiero que mi mejor amiga pille un resfriado por estar fuera hasta tarde.[n][w][e]

[msg MND_018_0_0]
[f 2 1]He decidido volver a la residencia con Aigis.[n][w][e]

