[msg MSG_000_0_0 [Amante de los gatos]]
[f 2 1][f 5 21 1 413]¡Mi amigo tiene un gato supercuqui![n][w][e]
[f 2 1][f 5 21 1 413]Yo también quiero uno, pero mi madre odia los animales.[n][w][e]

[msg MSG_001_0_0 [Amante de los gatos]]
[f 2 1][f 5 21 1 413]He vuelto a jugar con el gato de mi amigo en su casa.[n][w][e]
[f 2 1][f 5 21 1 413]Ains. Yo también quiero uno...[n][w][e]
[f 2 1][f 5 21 1 413]Ya sé que mi madre odia los animales, pero podría preguntarle.[n][w][e]

[msg MSG_002_0_0 [Amante de los gatos]]
[f 2 1][f 5 21 1 413]Le he pedido a mi madre un gato y me ha respondido que no.[n][w][e]
[f 2 1][f 5 21 1 413]"No, no y no". Solo sabe decir eso.[n][w][e]
[f 2 1][f 5 21 1 413]Ains. Quiero un gato...[n][w][e]

[msg MSG_003_0_0 [Amante de los gatos]]
[f 2 1][f 5 21 1 413]He intentado convencer a mi padre para que tengamos un gato.[n][w][e]
[f 2 1][f 5 21 1 413]Pero también me ha dicho que no.[n][w][e]
[f 2 1][f 5 21 1 413]Los gatos son caros, y la comida y demás también cuestan un ojo de la cara.[n][w][e]
[f 2 1][f 5 21 1 413]No podemos permitírnoslo.[n][w][e]

[msg MSG_004_0_0 [Amante de los gatos]]
[f 2 1][f 5 21 1 413]Le he preguntado a mi amigo si su gato les costó mucho.[n][w][e]
[f 2 1][f 5 21 1 413]¿Y sabes qué? ¡Me ha dicho que fue gratis![n][w][e]
[f 2 1][f 5 21 1 413]Su madre lo adoptó del refugio de animales.[n][w][e]
[f 2 1][f 5 21 1 413]No sabía que se pudiera hacer eso. Pensaba que solo se compraban en tiendas de animales.[n][w][e]

[msg MSG_005_0_0 [Amante de los gatos]]
[f 2 1][f 5 21 1 413]He vuelto a comentarle a mi padre lo de tener un gato.[n][w][e]
[f 2 1][f 5 21 1 413]Le he dicho que los gatos del refugio son gratis.[n][w][e]
[f 2 1][f 5 21 1 413]Pero me ha vuelto a decir que no.[n][w][e]
[f 2 1][f 5 21 1 413]A él le da igual, pero, si mi madre dice que no, eso va a misa.[n][w][e]
[f 2 1][f 5 21 1 413]Así que ella es la que lo decide. Mi padre es tonto.[n][w][e]

[msg MSG_006_0_0 [Amante de los gatos]]
[f 2 1][f 5 21 1 413]Mi amigo del cole dice que por aquí ronda un gato callejero.[n][w][e]
[f 2 1][f 5 21 1 413]Estoy esperando a que salga.[n][w][e]
[f 2 1][f 5 21 1 413]No voy a cogerlo ni nada, solo quiero verlo.[n][w][e]
[f 2 1][f 5 21 1 413]¿Qué tipo de gato será...?[n][w][e]

[msg MSG_007_0_0 [Amante de los gatos]]
[f 2 1][f 5 21 1 413]¿Te has fijado en que hay muchos sitios de comida por aquí?[n][w][e]
[f 2 1][f 5 21 1 413]Pues el gato se come las sobras de los dueños.[n][w][e]
[f 2 1][f 5 21 1 413]Les he preguntado a qué hora suele venir y me la han dicho.[n][w][e]
[f 2 1][f 5 21 1 413]¡Seguro que lo veo![n][w][e]

[msg MSG_008_0_0 [Amante de los gatos]]
[f 2 1][f 5 21 1 413]¿Qué tipo de gato crees que es?[n][w][e]

[sel SEL_009_0_0 top]
[f 2 1]Ni idea.[e]
[f 2 1]Un gato callejero.[e]
[f 2 1]No y no me interesa.[e]

[msg MSG_010_0_0 [Amante de los gatos]]
[f 2 1][f 5 21 1 413]¡Vale, pues te lo digo![n][w][e]

[msg MSG_011_0_0 [Amante de los gatos]]
[f 2 1][f 5 21 1 413]Bah... Ya lo sabías.[n][w][e]

[msg MSG_012_0_0 [Amante de los gatos]]
[f 2 1][f 5 21 1 413]¡Serás borde! Pero te voy a dar la respuesta de todas formas.[n][w][e]

[msg MSG_013_0_0 [Amante de los gatos]]
[f 2 1][f 5 21 1 413]¡Es un gato callejero![n][w][e]
[f 2 1][f 5 21 1 413]Pero es mi amigo. La primera vez que lo vi, ni siquiera salió corriendo. Se acercó para que lo tocara.[n][w][e]
[f 2 1][f 5 21 1 413]Eso significa que es mi alma gemela, ¿a que sí?[n][w][e]

[msg MSG_014_0_0 [Amante de los gatos]]
[f 2 1][f 5 21 1 413]Solo come las sobras de las tiendas.[n][w][e]
[f 2 1][f 5 21 1 413]Pero creo que se está cansando.[n][w][e]
[f 2 1][f 5 21 1 413]¡Podría ir a por un platito de leche para él![n][w][e]
[f 2 1][f 5 21 1 413]Sí, voy a comprar leche. Creo que le gustará.[n][w][e]

[sel SEL_015_0_0 top]
[f 2 1]Bien pensado.[e]
[f 2 1]Es mala idea.[e]

[msg MSG_016_0_0 [Amante de los gatos]]
[f 2 1][f 5 21 1 413]¡Sí! ¡Seguro que le gusta![n][w][e]

[msg MSG_017_0_0 [Amante de los gatos]]
[f 2 1][f 5 21 1 413]¡¿E-en serio?! ¿Le duele la tripa si toma leche normal?[n][w][e]
[f 2 1][f 5 21 1 413]¡No lo sabía! ¡Muchas gracias por avisarme![n][w][e]

[msg MSG_018_0_0 [Amante de los gatos]]
[f 2 1][f 5 21 1 413]Voy a comprarle leche para la próxima.[n][w][e]

[msg MSG_019_0_0 [Amante de los gatos]]
[f 2 1][f 5 21 1 413]Ah, que la leche normal es mala para los gatos... Lo recordaré.[n][w][e]

[msg MSG_020_0_0 [Amante de los gatos]]
[f 2 1][f 5 21 1 413]Les he preguntado a mis amigos qué darles de comer a los gatos y he estado leyendo sobre el tema.[n][w][e]
[f 2 1][f 5 21 1 413]Resulta que hay muchas cosas que no deberían comer.[n][w][e]
[f 2 1][f 5 21 1 413]La leche que quise darle la última vez es una de ellas.[n][w][e]
[f 2 1][f 5 21 1 413]No me lo esperaba, pero de todo se aprende.[n][w][e]

[msg MSG_021_0_0 [Amante de los gatos]]
[f 2 1][f 5 21 1 413]Le he preguntado a mi padre si puedo llevarme el gato a casa.[n][w][e]
[f 2 1][f 5 21 1 413]Me ha respondido que a él no le importa, pero que depende de mi madre.[n][w][e]
[f 2 1][f 5 21 1 413]Ains. Pero ya sé lo que va a decir. ¿Qué hago?[n][w][e]

[msg MSG_022_0_0 [Amante de los gatos]]
[f 2 1][f 5 21 1 413]¿Qué hago? El gato se ha ido.[n][w][e]
[f 2 1][f 5 21 1 413]Nadie sabe dónde está.[n][w][e]
[f 2 1][f 5 21 1 413]A lo mejor ha sido culpa del tifón.[n][w][e]
[f 2 1][f 5 21 1 413]Si me lo hubiera llevado a casa, esto no habría pasado.[n][w][e]

[msg MSG_023_0_0 [Amante de los gatos]]
[f 2 1][f 5 21 1 413]¡Mira, mira! ¡El gato ha vuelto![n][w][e]
[f 2 1][f 5 21 1 413]Hala... Ha sobrevivido al tifón.[n][w][e]
[f 2 1][f 5 21 1 413]A lo mejor se escondió en algún sitio.[n][w][e]
[f 2 1][f 5 21 1 413]Bueno, es igual. En cualquier caso, me alegro de que esté bien.[n][w][e]

[msg MSG_024_0_0 [Amante de los gatos]]
[f 2 1][f 5 21 1 413]He decidido que me quiero llevar el gato a casa.[n][w][e]
[f 2 1][f 5 21 1 413]Voy a convencer a mi madre para que me deje tenerlo de mascota.[n][w][e]
[f 2 1][f 5 21 1 413]Me da igual lo que diga, no pienso echarme atrás.[n][w][e]

[msg MSG_025_0_0 [Amante de los gatos]]
[f 2 1][f 5 21 1 413]El hombre y la señora... Los señores mayores también...[n][w][e]
[f 2 1][f 5 21 1 413]¿Qué hacen ahí pasmados mirando hacia la nada?[n][w][e]
[f 2 1][f 5 21 1 413]¿Están tan cansados que ya no quieren hacer nada?[n][w][e]

[msg MSG_026_0_0 [Amante de los gatos]]
[f 2 1][f 5 21 1 413]Mi madre me ha dicho que de ninguna de las maneras puedo tener un gato.[n][w][e]
[f 2 1][f 5 21 1 413]Pero no pasa nada, ¡porque mi padre me apoya![n][w][e]
[f 2 1][f 5 21 1 413]Voy a aprender de todo sobre gatos y a demostrarle que puedo hacerme cargo de uno.[n][w][e]
[f 2 1][f 5 21 1 413]¡Así mi padre la convencerá![n][w][e]
[f 2 1][f 5 21 1 413]¡Voy a darlo todo![n][w][e]

[msg MSG_027_0_0 [Amante de los gatos]]
[f 2 1][f 5 21 1 413]Está refrescando...[n][w][e]
[f 2 1][f 5 21 1 413]Podría entrar y ya está, pero ¿y él?[n][w][e]
[f 2 1][f 5 21 1 413]Creo que hay muchos lugares calentitos por aquí cerca, pero...[n][w][e]
[f 2 1][f 5 21 1 413]¿Seguro que no le pasará nada?[n][w][e]

[msg MSG_028_0_0 [Amante de los gatos]]
[f 2 1][f 5 21 1 413]Ya lo sé todo sobre los gatos.[n][w][e]
[f 2 1][f 5 21 1 413]He aprendido que no ven el color rojo. ¿Cómo será eso...?[n][w][e]

[msg MSG_029_0_0 [Amante de los gatos]]
[f 2 1][f 5 21 1 413]Ya lo sé todo sobre los gatos y se lo he dicho a mi padre.[n][w][e]
[f 2 1][f 5 21 1 413]¡Me ha dicho que he hecho un buen trabajo y que está impresionado![n][w][e]
[f 2 1][f 5 21 1 413]Me ha prometido que convencería a mi madre.[n][w][e]
[f 2 1][f 5 21 1 413]Ojalá pueda adoptar al gato.[n][w][e]

[msg MSG_030_0_0 [Amante de los gatos]]
[f 2 1][f 5 21 1 413]Este gato se comporta de forma rara. No deja de mirar al infinito.[n][w][e]
[f 2 1][f 5 21 1 413]No lo entiendo.[n][w][e]
[f 2 1][f 5 21 1 413]Pero creo que mi madre me dejará tenerlo de mascota.[n][w][e]
[f 2 1][f 5 21 1 413]Cuando mi padre vuelva hoy del trabajo, se lo preguntaremos juntos.[n][w][e]

[msg MSG_031_0_0 [Amante de los gatos]]
[f 2 1][f 5 21 1 413]He probado a ponerme orejas de gato, pero el gato ni me mira...[n][w][e]
[f 2 1][f 5 21 1 413]A lo mejor si tuviera un juguete para gatos... Pero creo que no tengo suficiente dinero para comprarlo.[n][w][e]
[f 2 1][f 5 21 1 413]¡Ah! ¿Eso es un juguete para gatos? ¿Tienes gato?[n][w][e]

[sel SEL_032_0_0 top]
[f 2 1]No. Puedes quedártelo.[e]
[f 2 1]Sí, esto es para mi gato.[e]

[msg MSG_033_0_0 [Amante de los gatos]]
[f 2 1][f 5 21 1 413]¡¿Puedo?! ¡Gracias![n][w][e]
[f 2 1][f 5 21 1 413]Debería darte algo a cambio... ¡Ah, ya sé![n][w][e]
[f 2 1][f 5 21 1 413]Puedes quedarte esta diadema de gato. Ya no me hace falta.[n][w][e]
[f 2 1][f 5 21 1 413]Aquí tienes.[n][w][e]

[msg MND_034_0_0]
[f 2 1]A lo mejor a Elizabeth le gusta esta diadema.[n][w][e]
[f 2 1]Debería enseñársela.[n][w][e]

[msg MSG_035_0_0 [Amante de los gatos]]
[f 2 1][f 5 21 1 413]Vaya, ¿en serio? Me encantaría tener un gato.[n][w][e]

