[msg MSG_000_0_0 [Aigis]]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 1 0 0]Ya estoy aquí, chicos. Siento haberos preocupado.[n][w][e]

[msg MSG_001_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 6 65535 0 0][vp 1 0 0 2 0 0]¡Qué alegría verte, tía! Ya había pasado un mes. Me estaba poniendo nervioso y todo.[n][w][e]

[msg MSG_002_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 6 65535 0 0][vp 1 0 0 3 0 0]Yo también. Me daba miedo no volver a verte...[n][w][e]

[msg MSG_003_0_0 [Aigis]]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 4 0 0]Soy una máquina, así que siempre se me puede reconstruir.[n][w][e]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 5 0 0]Aunque me destruyesen por completo, los datos de programación seguirían existiendo.[n][w][e]

[msg MSG_004_0_0 [Yukari Takeba]]
[f 2 1][bup 2 3 6 65535 0 0][vp 1 0 0 6 0 0]Venga, no hables de ti en ese plan.[n][w][e]

[msg MSG_005_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 6 65535 0 0][vp 1 0 0 7 0 0]Me dijeron que necesitaría otra semana para recuperarse del todo, pero conseguí que aceleraran el proceso.[n][w][e]
[f 2 1][bup 5 0 6 65535 0 0][vp 1 0 0 8 0 0]Mañana es Nochevieja.[n][w][e]

[msg MSG_006_0_0 [Aigis]]
[f 2 1][bup 7 3 6 65535 0 0][vp 1 0 0 9 0 0]Espero que me perdonéis por todos los problemas que os he causado.[n][w][e]

[msg MSG_006_5_0 [Aigis]]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 10 0 0]Mitsuru vino a verme al laboratorio.[n][w][e]
[f 2 1][bup 7 3 6 65535 0 0][vp 1 0 0 11 0 0][f 4 23 0 7 3 25 25]Ya me he enterado de lo que ha pasado... Ha tenido que ser muy duro.[n][w][e]

[msg MSG_007_0_0 [Aigis]]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 12 0 0][nf], ¿estás bien?[n][w][e]
[f 2 1][bup 7 3 6 65535 0 0][vp 1 0 0 13 0 0][f 4 23 0 7 3 25 25]Bueno, dadas las circunstancias, supongo que no.[n][w][e]

[sel SEL_008_0_0 top]
[f 2 1]Pues no.[e]
[f 2 1]No me quejo.[e]
[f 2 1]Estaba preocupada por ti.[e]

[msg MSG_009_0_0 [Aigis]]
[f 2 1][bup 7 1 6 65535 0 0][vp 1 0 0 14 0 0]¿En serio? Menos mal.[n][w][e]

[msg MSG_010_0_0 [Aigis]]
[f 2 1][bup 7 3 6 65535 0 0][vp 1 0 0 15 0 0]Lo siento. Podría haber hecho mucho más.[n][w][e]

[msg MSG_011_0_0 [Aigis]]
[f 2 1][bup 7 3 6 65535 0 0][vp 1 0 0 16 0 0]Lo que te hice hace diez años fue...[n][w][e]
[f 2 1][bup 7 3 6 65535 0 0][vp 0 0 0 17 0 0]...[n][w][e]

[sel SEL_012_0_0 top]
[f 2 1]Hiciste lo que tenías que hacer.[e]
[f 2 1]Tenías las manos atadas.[e]
[f 2 1]Hiciste lo correcto.[e]

[msg MSG_013_0_0 [Aigis]]
[f 2 1][bup 7 3 6 65535 0 0][vp 1 0 0 18 0 0]Pero...[n][w][e]
[f 2 1][bup 7 3 6 65535 0 0][vp 1 0 0 19 0 0]De no ser por lo que hice, ahora no estarías sufriendo tanto.[n][w][e]

[msg MSG_014_0_0 [Aigis]]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 20 0 0]En cuanto a lo que dijo Ryoji...[n][w][e]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 21 0 0]¿Has tomado ya una decisión al respecto?[n][w][e]

[sel SEL_015_0_0 top]
[f 2 1]Sí.[e]
[f 2 1]No, aún no.[e]

[msg MSG_016_0_0 [Aigis]]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 22 0 0]Tengo que pedirte un favor.[n][w][e]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 23 0 0]Mañana, cuando Ryoji vuelva...[n][w][e]

[msg MSG_016_3_0 [Aigis]]
[f 2 1][bup 7 2 6 65535 0 0][vp 1 0 0 24 0 0]¡Quiero que le mates![n][w][e]
[f 2 1][bup 7 2 6 65535 0 0][vp 1 0 0 25 0 0]¡No puedo soportar veros sufrir de esta manera![n][w][e]
[f 2 1][bup 7 2 6 65535 0 0][vp 1 0 0 26 0 0]¡Si tanto estáis sufriendo, os pido por favor que elijáis renunciar a vuestros recuerdos![n][w][e]

[msg MSG_016_5_0 [Aigis]]
[f 2 1][bup 7 3 6 65535 0 0][vp 1 0 0 27 0 0]Aunque...[n][w][e]

[msg MSG_017_0_0 [Aigis]]
[f 2 1][bup 7 3 6 65535 0 0][vp 1 0 0 28 0 0]Aunque eso signifique que todo, incluido nosotros...[n][w][e]
[f 2 1][bup 7 3 6 65535 0 0][vp 1 0 0 29 0 0]... caigamos en el olvido.[n][w][e]

[msg MSG_018_0_0 [Yukari Takeba]]
[f 2 1][bup 2 4 6 65535 0 0][vp 1 0 0 30 0 0]P-pero ¡¿qué estás diciendo, Aigis?![n][w][e]

[msg MSG_019_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 6 65535 0 0][vp 1 0 0 31 0 0]¡Pero bueno! Esto no es propio de ti.[n][w][e]

[msg MSG_020_0_0 [Aigis]]
[f 2 1][bup 7 3 6 65535 0 0][vp 0 0 0 32 0 0]...[n][w][e]

[msg MSG_021_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 6 65535 0 0][vp 1 0 0 33 0 0]¿Qué pasa, Aigis?[n][w][e]

[msg MSG_022_0_0 [Aigis]]
[f 2 1][bup 7 3 6 65535 0 0][vp 1 0 0 34 0 0]¿Por qué...? ¿Por qué he vuelto?[n][w][e]
[f 2 1][bup 7 3 6 65535 0 0][vp 1 0 0 35 0 0]Mi deber es proteger a las personas de las sombras.[n][w][e]
[f 2 1][bup 7 3 6 65535 0 0][vp 1 0 0 36 0 0]Pero ha quedado claro que no puedo derrotarlas.[n][w][e]

[msg MSG_022_5_0 [Aigis]]
[f 2 1][bup 7 3 6 65535 0 0][vp 1 0 0 37 0 0]¿Qué pinto yo aquí?[n][w][e]
[f 2 1][bup 7 3 6 65535 0 0][vp 1 0 0 38 0 0]Por mucho que lo intento, ni siquiera puedo derramar una lágrima por vosotros...[n][w][e]

[msg MSG_023_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 6 65535 0 0][vp 1 0 0 39 0 0]Aigis...[n][w][e]

[msg MSG_024_0_0 [Aigis]]
[f 2 1][bup 7 2 6 65535 0 0][vp 1 0 0 40 0 0]¿Por qué queréis luchar si sabéis que será en vano?[n][w][e]
[f 2 1][bup 7 2 6 65535 0 0][vp 1 0 0 41 0 0]¡¿Para qué arriesgarlo todo si lo único que va a traer es sufrimiento?![n][w][e]
[f 2 1][bup 7 2 6 65535 0 0][vp 1 0 0 42 0 0]¡Estáis desperdiciando vuestras vidas! ¡No puedo entenderlo![n][w][e]

[msg MSG_025_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 6 65535 0 0][vp 1 0 0 43 0 0]Aquí nadie está desperdiciando su vida.[n][w][e]
[f 2 1][bup 4 0 6 65535 0 0][vp 1 0 0 44 0 0]De hecho, estamos pensando en el futuro, ¿verdad?[n][w][e]

[msg MSG_026_0_0 [Ken Amada]]
[f 2 1][bup 8 1 6 65535 0 0][vp 1 0 0 45 0 0]Eso es.[n][w][e]

[msg MSG_027_0_0 [Aigis]]
[f 2 1][bup 7 3 6 65535 0 0][vp 1 0 0 46 0 0]No lo comprendo. Será porque no tengo vida propia.[n][w][e]

[msg MSG_028_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 6 65535 0 0][vp 1 0 0 47 0 0]Ja, ja. Esto no tiene nada que ver con tener una vida.[n][w][e]

[msg MSG_029_0_0 [Aigis]]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 48 0 0]Soy una máquina creada para proteger a los humanos de las sombras.[n][w][e]
[f 2 1][bup 7 3 6 65535 0 0][vp 1 0 0 49 0 0][f 4 23 0 7 3 25 25]Pero, con el poder que tengo, no puedo cumplir mi objetivo.[n][w][e]

[msg MSG_029_5_0 [Aigis]]
[f 2 1][bup 7 3 6 65535 0 0][vp 1 0 0 50 0 0]¿Cuál es mi propósito, entonces? Estoy perdida...[n][w][e]
[f 2 1][bup 7 3 6 65535 0 0][vp 1 0 0 51 0 0]Y nadie puede darme una respuesta.[n][w][e]

[msg MSG_030_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 6 65535 0 0][vp 1 0 0 52 0 0]Bueno, nosotros no te podemos ayudar en eso.[n][w][e]
[f 2 1][bup 3 0 6 65535 0 0][vp 1 0 0 53 0 0]El significado de la vida o de la muerte no te lo puede enseñar nadie.[n][w][e]
[f 2 1][bup 3 0 6 65535 0 0][vp 1 0 0 54 0 0]Seas quien seas, tomar decisiones es algo complicado. Ninguna es la correcta, ¿sabes?[n][w][e]

[msg MSG_030_3_0 [Junpei Iori]]
[f 2 1][bup 3 0 6 65535 0 0][vp 1 0 0 55 0 0]Pero algo debemos hacer mientras sigamos con vida.[n][w][e]
[f 2 1][bup 3 0 6 65535 0 0][vp 1 0 0 56 0 0]Cuando ves a alguien pasando por lo mismo que tú, te motiva a querer ayudarle.[n][w][e]
[f 2 1][bup 3 1 6 65535 0 0][vp 1 0 0 57 0 0][f 4 23 0 3 1 25 25]Así es como planeamos superar esto.[n][w][e]

[msg MSG_030_5_0 [Junpei Iori]]
[f 2 1][bup 3 1 6 65535 0 0][vp 1 0 0 58 0 0]Ja, ja. Quizá no me haya explicado muy bien, pero esa es la idea.[n][w][e]

[msg MSG_031_0_0 [Aigis]]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 59 0 0]¿Cómo que esa es la idea?[n][w][e]

[msg MSG_032_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 6 65535 0 0][vp 1 0 0 60 0 0]Cuando te derrumbaste, me di cuenta de algo.[n][w][e]
[f 2 1][bup 6 0 6 65535 0 0][vp 1 0 0 61 0 0][f 4 23 0 6 0 25 25]Quiero protegerte, Aigis. No quiero olvidarme de ti.[n][w][e]

[msg MSG_033_0_0 [Aigis]]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 62 0 0]Fuuka...[n][w][e]

[msg MSG_034_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 6 65535 0 0][vp 1 0 0 63 0 0]Habrá momentos en los que perderás de vista tu objetivo y tendrás que ponerte a buscarlo.[n][w][e]
[f 2 1][bup 5 0 6 65535 0 0][vp 1 0 0 64 0 0]Y, si no puedes encontrarlo, tendrás que fijarte uno nuevo.[n][w][e]

[msg MSG_034_5_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 6 65535 0 0][vp 1 0 0 65 0 0]No soy quién para hablar, pero siento que este año he aprendido algo muy importante.[n][w][e]
[f 2 1][bup 5 0 6 65535 0 0][vp 1 0 0 66 0 0]Vivir consiste en estar dispuesto a hacer cambios. Y ese tipo de decisiones nos corresponde a nosotros tomarlas.[n][w][e]

[msg MSG_035_0_0 [Aigis]]
[f 2 1][bup 7 3 6 65535 0 0][vp 1 0 0 67 0 0]¿Crees que yo también podré cambiar?[n][w][e]

[msg MSG_036_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 6 65535 0 0][vp 1 0 0 68 0 0]Tú ya has cambiado, y mucho. ¿No te has dado cuenta?[n][w][e]
[f 2 1][bup 5 1 6 65535 0 0][vp 1 0 0 69 0 0]Hasta hablas como una persona de verdad.[n][w][e]

[msg MSG_037_0_0 [Aigis]]
[f 2 1][bup 7 1 6 65535 0 0][vp 1 0 0 70 0 0]Ahora entiendo cuál es mi propósito.[n][w][e]

[msg MSG_038_0_0 [Aigis]]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 71 0 0]Soy una máquina a la que le han dado la orden de "vivir".[n][w][e]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 72 0 0]Y quien ha emitido esta nueva orden... soy yo.[n][w][e]

[sel SEL_039_0_0 top]
[f 2 1]Como debería ser.[e]
[f 2 1]Tú decides.[e]

[msg MSG_040_0_0 [Aigis]]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 73 0 0]Miraré al miedo a la cara y elegiré vivir. Es una promesa que me hago a mí misma.[n][w][e]
[f 2 1][bup 7 1 6 65535 0 0][vp 1 0 0 74 0 0][f 4 23 0 7 1 25 25]No tengo muy claro cómo voy a lograrlo, pero supongo que eso también forma parte de la vida.[n][w][e]

[msg MSG_041_0_0 [Ken Amada]]
[f 2 1][bup 8 1 6 65535 0 0][vp 1 0 0 75 0 0]Sin duda.[n][w][e]

[msg MSG_042_0_0 [Koromaru]]
[f 2 1][bup 9 1 65535 65535 0 0][vp 1 0 0 76 0 0]¡Guau![n][w][e]

[msg MND_043_0_0]
[f 2 1]La resolución del corazón de Aigis ha despertado una nueva Persona.[n][w][e]

[msg MND_044_0_0]
[f 2 1]¡La Persona de Aigis, [clr 35]Paladio[clr 27], ha dado lugar a [clr 35]Atenea[clr 27]![n][w][e]

[msg MSG_045_0_0 [Aigis]]
[f 2 1][bup 7 1 6 65535 0 0][vp 1 0 0 77 0 0]¿Me permitiréis unirme a vosotros en esta lucha?[n][w][e]

[msg MSG_046_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 6 65535 0 0][vp 1 0 0 78 0 0]¿Estás de guasa? ¡Pues claro! ¡Si siempre has sido una de los nuestros![n][w][e]

[msg MSG_047_0_0 [Aigis]]
[f 2 1][bup 7 1 6 65535 0 0][vp 1 0 0 79 0 0]¡Gracias![n][w][e]
[f 2 1][bup 7 1 6 65535 0 0][vp 1 0 0 80 0 0]A partir de ahora, estaré a vuestro lado.[n][w][e]
[f 2 1][bup 7 1 6 65535 0 0][vp 1 0 0 81 0 0]¡Pase lo que pase![n][w][e]

[msg MSG_048_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 6 65535 0 0][vp 1 0 0 82 0 0]¡Así se habla![n][w][e]

