[msg MND_000_0_0]
[f 2 1]¿Dónde estoy?[n][w][e]
[f 2 1]Se me nubla la mente...[n][w][e]
[f 2 1]No recuerdo qué hago aquí...[n][w][e]

[sel SEL_001_0_0 top]
[f 2 1]¿Qué estaba haciendo?[e]
[f 2 1]Supongo que da igual...[e]

[msg MND_002_0_0]
[f 2 1]Tengo la sensación de que se me olvida algo importante...[n][w][e]

[msg MND_003_0_0]
[f 2 1]¿...?[n][w][e]
[f 2 1]Oigo el agua correr en el baño...[n][w][e]

[msg MSG_004_0_0 [Voz de tu cabeza]]
[f 2 1][vp 1 0 0 1 0 0]Acepta tus deseos...[n][w][e]

[msg MND_005_0_0]
[f 2 1]Una voz extraña resuena en mi cabeza...[n][w][e]

[msg MSG_006_0_0 [Voz de tu cabeza]]
[f 2 1][vp 1 0 0 2 0 0]Soy la voz de tu yo interior...[n][w][e]
[f 2 1][vp 1 0 0 3 0 0]Disfruta del ahora...[n][w][e]
[f 2 1][vp 1 0 0 4 0 0]Lo que no se puede sentir no es más que un sueño... No tenemos más que el presente.[n][w][e]

[sel SEL_007_0_0 top]
[f 2 1]Exacto...[e]
[f 2 1]Eso no es cierto...[e]
[f 2 1]¿Qué más da eso?[e]

[msg MSG_008_0_0 [Voz de tu cabeza]]
[f 2 1][vp 1 0 0 5 0 0]El futuro es una ilusión, el recuerdo de una mentira...[n][w][e]
[f 2 1][vp 1 0 0 6 0 0]Que los deseos te liberen de tus cadenas... Ese es tu deseo...[n][w][e]

[sel SEL_009_0_0 top]
[f 2 1]No puedo sucumbir...[e]
[f 2 1]"Puede ser...".[e]
[f 2 1]No lo entiendo...[e]

[msg MSG_010_0_0 [Voz de tu cabeza]]
[f 2 1][vp 1 0 0 7 0 0]El placer es lo que anhelas.[n][w][e]
[f 2 1][vp 1 0 0 8 0 0]Ante ti se halla la puerta[n]hacia la felicidad.[n][w][e]
[f 2 1][vp 1 0 0 9 0 0]No puedes reprimir tus instintos... Acepta tus deseos...[n][w][e]

[sel SEL_011_0_0 top]
[f 2 1]No lo entiendo...[e]
[f 2 1]Te escucho...[e]
[f 2 1]Pasando...[e]

[msg MND_012_0_0]
[f 2 1]Empiezo a perder la consciencia...[n][w][e]
[f 2 1]Pero sé que aún tengo cosas que hacer...[n][w][e]

[msg MSG_013_0_0 [Voz de tu cabeza]]
[f 2 1][vp 1 0 0 10 0 0]¿Por qué te resistes? No apartes la vista de la verdad...[n][w][e]

[msg MND_014_0_0]
[f 2 1]Empiezo a pensar con claridad.[n][w][e]
[f 2 1]Parece que algo intentaba manipular mis pensamientos.[n][w][e]

[msg MND_015_0_0]
[f 2 1]Han cerrado el grifo de la ducha.[n][w][e]

[msg MSG_016_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 154 65535 0 0][vp 1 0 0 11 0 0]Eh... ¿Qué estaba...?[n][w][e]

[msg MSG_017_0_0 [Yukari Takeba]]
[f 2 1][bup 2 4 154 65535 1 0][vp 1 0 0 12 0 0]¿Eh?[n][f 1 2 50][e]

[msg MSG_017_3_0 [Yukari Takeba]]
[f 2 1][cut 2 10 0][e]

[msg MSG_017_5_0 [Yukari Takeba]]
[f 2 1][bup 2 8 154 65535 1 0][vp 1 0 0 13 0 0]¡Aaaaaaah![n][f 1 2 45][e]

[msg MND_018_0_0]
[f 2 1]Parece que también estaban manipulando los pensamientos de Yukari.[n][w][e]

[msg MSG_019_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 4 52 50 0 0][vp 1 0 0 14 0 0]Ah, ¡por fin doy con vosotras![n][w][e]
[f 2 1][bup 6 4 52 50 0 0][vp 1 0 0 15 0 0]¿Me oís?[n][w][e]

[sel SEL_020_0_0 top]
[f 2 1]Claro.[e]
[f 2 1]¿Qué ocurre?[e]

[msg MSG_021_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 52 50 0 0][vp 1 0 0 16 0 0]Lo siento, no he podido establecer contacto antes.[n][w][e]
[f 2 1][bup 6 3 52 50 0 0][vp 1 0 0 17 0 0]La sombra interfería con vuestros pensamientos, no podía establecer contacto.[n][w][e]
[f 2 1][bup 6 3 52 50 0 0][vp 1 0 0 18 0 0]Parece que a vosotras dos también os han teletransportado. El grupo se ha separado.[n][w][e]
[f 2 1][bup 6 3 52 50 0 0][vp 1 0 0 19 0 0]El enemigo sigue en la misma habitación. Reagruparos e id hasta allí.[n][w][e]

[msg MSG_022_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 52 50 0 0][vp 1 0 0 20 0 0]¿Me has oído, Yukari?[n][w][e]

[msg MSG_023_0_0 [Yukari Takeba]]
[f 2 1][vp 1 0 0 21 0 0]Sí, te he oído.[n][w][e]

[msg MSG_024_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 4 52 50 0 0][vp 1 0 0 22 0 0]Oye, ¿ha pasado algo?[n][w][e]

[msg MSG_025_0_0 [Yukari Takeba]]
[f 2 1][vp 1 0 0 23 0 0]¡No, todo bien![n][w][e]

[msg MSG_026_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 52 65535 0 0][vp 1 0 0 24 0 0]Venga, vamos.[n][w][e]

[msg MSG_026_1_0 [Yukari Takeba]]
[f 2 1][cut 2 2 0][e]

[msg MSG_026_3_0 [Yukari Takeba]]
[f 2 1][bup 2 2 52 65535 0 0][vp 1 0 0 25 0 0]¿Qué tal si no le contamos esto a nadie? ¿Te parece?[n][w][e]

