[msg MND_000_0_0]
[f 2 1]Restaurante de ramen Hagakure...[n][w][e]

[msg MND_001_0_0]
[f 2 1]Ahora mismo hay demasiada gente.[n][w][e]

[msg MND_002_0_0]
[f 2 1]"Ramen de cerdo - 900 yenes"[n]"¡El colágeno te dejará la piel como la seda!".[n][w][e]

[msg MND_003_0_0]
[f 2 1]Comer alimentos ricos en colágeno podría ayudarme a mejorar mi [f 4 30 1 1 1 0].[n][w][e]

[msg MND_004_0_0]

[msg MND_005_0_0]
[f 2 1]¿Debería pasar el día aquí?[n][w][e]

[msg MND_006_0_0]
[f 2 1]¿Debería pasar la noche aquí?[n][w][e]

[sel SEL_007_0_0 top]
[f 2 1]Comer en el Hagakure[e]
[f 2 1]Comprobar qué se puede hacer aquí[e]
[f 2 1]Ahora no[e]

[msg MND_008_0_0]
[f 2 1]No tengo suficiente dinero.[n][w][e]

[msg MND_009_0_0]
[f 2 1]"¡Solo servimos el bol Hagakure especial [clr 2]los martes, miércoles y viernes por la noche[clr 27]!".[n][w][e]

[msg MND_010_0_0]

[msg MND_011_0_0]
[f 2 1][vp 3 0 65535 20003 0 0]He hecho acopio de [f 4 30 2 1 1 0] y le he pedido el bol Hagakure especial al dueño fortachón.[n][w][e]

[msg MND_012_0_0]
[f 2 1]Un cliente habitual se ha atrevido a pedirle el bol Hagakure especial al dueño fortachón.[n][w][e]
[f 2 1]Parece que es parte de un menú especial que solo está disponible los [clr 2]martes, miércoles y viernes por la noche[clr 27].[n][w][e]
[f 2 1]Quizá podría pedirlo si mi [f 4 30 2 1 1 0] fuese al menos [f 4 31 2 3 1 0].[n][w][e]

[msg MND_013_0_0]

[msg MND_014_0_0]

[sel SEL_015_0_0 top]
[f 2 1]Pedir[e]
[f 2 1]No pedir[e]

[msg MND_016_0_0]
[f 2 1]El arcano de la Templanza[n]podría ayudarme todavía más...[n][w][e]

[msg MND_017_0_0]
[f 2 1]Parece que mi [f 4 30 1 1 1 0] ya está al máximo.[n][w][e]
[f 2 1]¿Pido el ramen de cerdo igualmente?[n][w][e]

[msg MND_018_0_0]
[f 2 1]Parece que mi [f 4 30 1 1 1 0] ya está al máximo.[n][w][e]
[f 2 1]¿Pido el bol Hagakure especial igualmente?[n][w][e]

[msg MND_019_0_0]
[f 2 1]No tengo coraje suficiente para pedirle el bol Hagakure especial al dueño fortachón.[n][w][e]
[f 2 1]Si mi [f 4 30 2 1 1 0] fuera al menos [f 4 31 2 3 1 0], igual podría pedirlo.[n][w][e]

[msg MND_020_0_0]
[f 2 1]Restaurante de ramen Hagakure.[n][w][e]

[msg MND_021_0_0]
[f 2 1]¿Qué debería pedir?[n][w][e]

[sel SEL_022_0_0 top]
[f 2 1]Ramen de cerdo [f 4 26 23 0][e]
[f 2 1]Bol Hagakure especial [f 4 26 24 0][e]

[msg MND_023_0_0]
[f 2 1]Un plato bien cargadito de colágeno que te cala hasta los huesos. Tu [f 4 30 1 1 0 0] aumentará.[n][w][e]

[msg MND_023_1_0]
[f 2 1]Un plato de un menú especial con colágeno para dar y regalar. Tu [f 4 30 1 1 0 0] aumentará.[n][w][e]

[msg MND_024_0_0]
[f 2 1]Hoy es el día de la promesa. Más vale que vaya a la torre Tártaro.[n][w][e]

