[msg MND_000_0_0]
[f 2 1]El familiar olor a pescado[n]inunda el restaurante.[n][w][e]

[msg MSG_001_0_0 [Nozomi Suemitsu]]
[f 2 1][bup 116 1 65535 65535 0 0][vp 1 0 0 1 0 0]¿Te parecen suficientes aperitivos?[n][w][e]

[msg MSG_001_3_0 [Nozomi Suemitsu]]
[f 2 1][bup 116 1 65535 65535 0 0][vp 1 0 0 2 0 0]¡Disculpe, señor! ¡Dos boles de lo de siempre! Y que uno sea extragrande.[n][w][e]

[msg MSG_002_0_0 [Dueño del restaurante de ramen]]
[f 2 1][vp 1 0 0 3 0 0][f 5 21 0 1001]Enseguida.[n][w][e]

[msg MND_003_0_0]
[f 2 1]Han sustituido nuestros boles[n]por otros dos recién hechos.[n][w][e]

[msg MSG_004_0_0 [Nozomi Suemitsu]]
[f 2 1][bup 116 1 65535 65535 0 0][vp 1 0 0 4 0 0]Una vez que pruebas esto, amiga mía, no hay vuelta atrás.[n][w][e]
[f 2 1][bup 116 1 65535 65535 0 0][vp 1 0 0 5 0 0]¡Fideos Tan-Tan-Tan! ¡Sí! ¡Son tres, cuéntalos! ¡Tres Tan![n][w][e]

[msg MSG_004_3_0 [Nozomi Suemitsu]]
[f 2 1][bup 116 1 65535 65535 0 0][vp 1 0 0 6 0 0]Esta es la joya de la corona del menú secreto. ¡Es incluso mejor que el bol de Hagakure![n][w][e]
[f 2 1][bup 116 1 65535 65535 0 0][vp 1 0 0 7 0 0]El sencillo caldo a base de sal, complementado con la rica y picante salsa de miso... ¡Es como un microcosmos del milagro de la creación![n][w][e]

[msg MND_005_0_0]
[f 2 1]¡Hala![n][w][e]
[f 2 1]¡Un sabor tan increíble como este[n]elimina todos mis problemas![n][w][e]

[msg MSG_006_0_0 [Nozomi Suemitsu]]
[f 2 1][bup 116 0 65535 65535 0 0][vp 1 0 0 8 0 0]¡La clave es ese menú secreto! Aunque, ¿cómo lo encontrará la gente si es tan secreto?[n][w][e]
[f 2 1][bup 116 1 65535 65535 0 0][vp 1 0 0 9 0 0][f 4 23 0 116 1 25 25]En fin, es igual. Cuanto más vueltas le dé, más hambre me entrará.[n][w][e]

[msg MSG_007_0_0 [Nozomi Suemitsu]]
[f 2 1][bup 116 0 65535 65535 0 0][vp 1 0 0 10 0 0]¡Señor! No tire ese primer bol, ¿vale? ¡Esa sopa y yo tenemos asuntos pendientes![n][w][e]

[msg MSG_008_0_0 [Nozomi Suemitsu]]
[f 2 1][bup 116 1 65535 65535 0 0][vp 1 0 0 11 0 0]Esto es un gran honor para ti, ¿sabes? Eres la segunda persona que prueba esto después de mí.[n][w][e]
[f 2 1][bup 116 1 65535 65535 0 0][vp 1 0 0 12 0 0]No olvides soplar a los fideos para enfriarlos.[n][w][e]

[msg MND_009_0_0]
[f 2 1]Percibo la amabilidad de Suemitsu.[n][w][e]
[f 2 1]Tengo la sensación de que nuestra relación se ha fortalecido.[n][w][e]

[msg MSG_010_0_0 [Nozomi Suemitsu]]
[f 2 1][bup 116 1 65535 65535 0 0][vp 1 0 0 13 0 0]Menuda suerte tienes. ¡Te has hecho mi amiga![n][w][e]
[f 2 1][bup 116 3 65535 65535 0 0][vp 1 0 0 14 0 0][f 4 23 0 116 3 25 25]Y, para que lo sepas, no disfrutarías de esto con mi hermano pequeño. ¡Porque el hermano pequeño del Rey gourmet no es el Rey gourmet![n][w][e]

[msg MSG_010_3_0 [Nozomi Suemitsu]]
[f 2 1][bup 116 1 65535 65535 0 0][vp 1 0 0 15 0 0]Me entiendes, ¿verdad? ¿Quién soy? Venga, ¡quiero escucharte decirlo![n][w][e]

[sel SEL_011_0_0 top]
[f 2 1]Nozomi Suemitsu.[e]
[f 2 1]El Rey gourmet.[e]

[msg MSG_012_0_0 [Nozomi Suemitsu]]
[f 2 1][bup 116 3 65535 65535 0 0][vp 1 0 0 16 0 0]Bueno, sí. Supongo que eso es cierto... Muy guapa, sí, pero le falta cerebro.[n][w][e]

[msg MSG_013_0_0 [Nozomi Suemitsu]]
[f 2 1][bup 116 1 65535 65535 0 0][vp 1 0 0 17 0 0][f 5 13 19 15 116]¡Ostras, no lo digas tan alto! ¿Intentas dejarme en evidencia? Toma, come un poco de mi huevo duro. Le he dado un par de bocados, ¡pero está buenísimo![n][w][e]

[msg MSG_014_0_0 [Nozomi Suemitsu]]
[f 2 1][bup 116 4 65535 65535 0 0][vp 1 0 0 18 0 0]¡Ay! ¡Basta de cháchara! ¡La comida va a estar correosa e insípida si no nos la zampamos![n][w][e]

[msg MSG_014_5_0 [Nozomi Suemitsu]]
[f 2 1][bup 116 2 65535 65535 0 1][vp 1 0 0 19 0 0]¡Señor! Ha guardado el primer bol, ¿verdad? ¡Porque lo voy a necesitar![n][w][e]

[msg MND_015_0_0]
[f 2 1]Suemitsu y yo nos acabamos el ramen[n]y volvimos a la residencia.[n][w][e]

