[msg MND_000_0_0]
[f 2 1]A ver...[n][w][e]

[sel SEL_001_0_0 top]
[f 2 1]Volver a tu habitación[e]
[f 2 1]No hacer nada[e]

[msg MND_002_0_0]
[f 2 1]Hoy me dijeron que fuera a la cuarta planta.[n][w][e]

[msg MND_003_0_0]
[f 2 1]¿Debería volver ya a mi habitación?[n][w][e]

[sel SEL_004_0_0 top]
[f 2 1]Volver[e]
[f 2 1]Aún no[e]

[msg MND_005_0_0]
[f 2 1]Estoy cansada. Me convendría reponer fuerzas.[n][w][e]

[msg MND_006_0_0]
[f 2 1]Estoy agotada... Hoy debería acostarme pronto.[n][w][e]

[msg MND_007_0_0]
[f 2 1]Debo ir a la torre Tártaro.[n][w][e]

[msg MND_008_0_0]
[f 2 1]Es la lista de los residentes.[n][w][e]
[f 2 1]No se han añadido nuevos nombres recientemente.[n][w][e]

[msg MND_009_0_0]
[f 2 1]Es la lista de los residentes.[n][w][e]
[f 2 1]Mi nombre también está en la lista.[n][w][e]

[msg MND_010_0_0]
[f 2 1]Es la lista de los residentes.[n][w][e]
[f 2 1]El nombre de Junpei está en la lista en negrita.[n][w][e]

[msg MND_011_0_0]
[f 2 1]Es la lista de los residentes.[n][w][e]
[f 2 1]El nombre de Fuuka está escrito muy bonito.[n][w][e]

[msg MND_012_0_0]
[f 2 1]Es la lista de los residentes.[n][w][e]
[f 2 1]El nombre de Aigis está perfectamente impreso.[n][w][e]

[msg MND_013_0_0]
[f 2 1]Es la lista de los residentes.[n][w][e]
[f 2 1]"Ken Amada" está escrito entero en kanji.[n][w][e]

[msg MND_014_0_0]
[f 2 1]Es la lista de los residentes.[n][w][e]
[f 2 1]Hay una huella de pata. ¿Será de Koromaru?[n][w][e]

[msg MND_015_0_0]
[f 2 1]Es la lista de los residentes.[n][w][e]
[f 2 1]El nombre de Aragaki estaba escrito antes que el mío.[n][w][e]

[msg MND_016_0_0]
[f 2 1]Es la lista de los residentes.[n][w][e]
[f 2 1]Hay diez nombres. Cada vez se llena más la residencia.[n][w][e]

[msg MND_017_0_0]
[f 2 1]Es la lista de los residentes.[n][w][e]
[f 2 1]Hay diez nombres escritos.[n][w][e]
[f 2 1]...[n][w][e]

[msg MND_018_0_0]
[f 2 1]Es la lista de los residentes.[n][w][e]
[f 2 1]Aparecen los nombres de mis amigos que han jurado proteger el futuro de todos.[n][w][e]
[f 2 1]La batalla final que estamos a punto de afrentar... Me esforzaré al máximo con el resto.[n][w][e]

