[msg AST_btl_06_blank]
[f 2 1][vp 2 0 65535 0 0 0]未使用[n][w][e]

[msg AST_btl_06_001_01]
[f 2 1][vp 2 0 65535 1 0 0]¡Tenemos la iniciativa! No parecen muy fuertes.[n][w][e]

[msg AST_btl_06_002_01]
[f 2 1][vp 2 0 65535 2 0 0]¡Podemos atacar primero! ¡A por todas![n][w][e]

[msg AST_btl_06_003_01]
[f 2 1][vp 2 0 65535 3 0 0]¡El enemigo es fuerte, pero atacamos primero![n][w][e]

[msg AST_btl_06_004_01]
[f 2 1][vp 2 0 65535 4 0 0]¡Podemos movernos primero! Dos enemigos... ¡Podéis con ellos![n][w][e]

[msg AST_btl_06_005_01]
[f 2 1][vp 2 0 65535 5 0 0]Dos enemigos... ¡Podemos atacar primero![n][w][e]

[msg AST_btl_06_006_01]
[f 2 1][vp 2 0 65535 6 0 0]Dos enemigos. Son fuertes, ¡pero llevamos la delantera![n][w][e]

[msg AST_btl_06_007_01]
[f 2 1][vp 2 0 65535 7 0 0]¡Tres objetivos! ¡No nos verán llegar![n][w][e]

[msg AST_btl_06_008_01]
[f 2 1][vp 2 0 65535 8 0 0]Tres enemigos detectados. ¡Tenemos las de ganar![n][w][e]

[msg AST_btl_06_009_01]
[f 2 1][vp 2 0 65535 9 0 0]¡Tres enemigos poderosos! ¡Podemos atacar en primer lugar![n][w][e]

[msg AST_btl_06_010_01]
[f 2 1][vp 2 0 65535 10 0 0]¡Cuatro enemigos y tenemos ventaja! No os contengáis.[n][w][e]

[msg AST_btl_06_011_01]
[f 2 1][vp 2 0 65535 11 0 0]¡Cuatro objetivos! ¡Es nuestra oportunidad de atacar primero![n][w][e]

[msg AST_btl_06_012_01]
[f 2 1][vp 2 0 65535 12 0 0]Cuatro objetivos. Atacamos primero, ¡pero son duros de roer![n][w][e]

[msg AST_btl_06_013_01]
[f 2 1][vp 2 0 65535 13 0 0]¡Tenemos la iniciativa! Son cinco, ¡pero os irá bien![n][w][e]

[msg AST_btl_06_014_01]
[f 2 1][vp 2 0 65535 14 0 0]Cinco enemigos. ¡Podemos atacar primero![n][w][e]

[msg AST_btl_06_015_01]
[f 2 1][vp 2 0 65535 15 0 0]Cinco enemigos fuertes... ¡Vamos a reducir sus filas mientras tenemos ventaja![n][w][e]

[msg AST_btl_06_016_01]
[f 2 1][vp 2 0 65535 16 0 0]El enemigo lleva la iniciativa, pero no hay nada que temer.[n][w][e]

[msg AST_btl_06_017_01]
[f 2 1][vp 2 0 65535 17 0 0]¡Ataque enemigo! ¡Aguantad![n][w][e]

[msg AST_btl_06_018_01]
[f 2 1][vp 2 0 65535 18 0 0]¡Ataque enemigo! Cuidado, ¡es de los fuertes![n][w][e]

[msg AST_btl_06_019_01]
[f 2 1][vp 2 0 65535 19 0 0]¡Emboscada de dos enemigos! Podéis con ellos; ¡mantened la calma![n][w][e]

[msg AST_btl_06_020_01]
[f 2 1][vp 2 0 65535 20 0 0]¡Nos atacan! ¡Hay dos![n][w][e]

[msg AST_btl_06_021_01]
[f 2 1][vp 2 0 65535 21 0 0]Dos enemigos fuertes. ¡Llevan la iniciativa! ¡Tenéis que resistir![n][w][e]

[msg AST_btl_06_022_01]
[f 2 1][vp 2 0 65535 22 0 0]Tres objetivos. Se nos han adelantado, ¡pero podéis cambiar las tornas![n][w][e]

[msg AST_btl_06_023_01]
[f 2 1][vp 2 0 65535 23 0 0]Tres enemigos. ¡Llevan la iniciativa![n][w][e]

[msg AST_btl_06_024_01]
[f 2 1][vp 2 0 65535 24 0 0]Tres enemigos potentes... ¡Es una emboscada! ¡Preparaos![n][w][e]

[msg AST_btl_06_025_01]
[f 2 1][vp 2 0 65535 25 0 0]Es un grupo de cuatro. No son fuertes, ¡pero llevan la iniciativa![n][w][e]

[msg AST_btl_06_026_01]
[f 2 1][vp 2 0 65535 26 0 0]Cuatro enemigos. ¡Llevan la delantera![n][w][e]

[msg AST_btl_06_027_01]
[f 2 1][vp 2 0 65535 27 0 0]¡El enemigo lleva ventaja! Son cuatro fuertes; ¡tendréis que aguantar![n][w][e]

[msg AST_btl_06_028_01]
[f 2 1][vp 2 0 65535 28 0 0]Es un grupo de cinco..., ¡pero podéis con ellos![n][w][e]

[msg AST_btl_06_029_01]
[f 2 1][vp 2 0 65535 29 0 0]¡Se acercan! ¡Hay cinco! ¡Esto no pinta bien![n][w][e]

[msg AST_btl_06_030_01]
[f 2 1][vp 2 0 65535 30 0 0]No... ¡Una emboscada! Nos superan en fuerza y número... ¡Tenéis que aguantar![n][w][e]

[msg AST_btl_06_031_01]
[f 2 1][vp 2 0 65535 31 0 0]¡Un objetivo! ¡Esto será pan comido![n][w][e]

[msg AST_btl_06_032_01]
[f 2 1][vp 2 0 65535 32 0 0]¡Hay un enemigo![n][w][e]

[msg AST_btl_06_033_01]
[f 2 1][vp 2 0 65535 33 0 0]Detectado un único enemigo... ¡Es de los fuertes![n][w][e]

[msg AST_btl_06_034_01]
[f 2 1][vp 2 0 65535 34 0 0]¡Hay dos objetivos![n][w][e]

[msg AST_btl_06_035_01]
[f 2 1][vp 2 0 65535 35 0 0]Dos enemigos. ¡Podéis hacerlo![n][w][e]

[msg AST_btl_06_036_01]
[f 2 1][vp 2 0 65535 36 0 0]¡Dos enemigos! Cuidado, ¡que son fuertes![n][w][e]

[msg AST_btl_06_037_01]
[f 2 1][vp 2 0 65535 37 0 0]¡Tres objetivos! Son débiles, pero no os descuidéis.[n][w][e]

[msg AST_btl_06_038_01]
[f 2 1][vp 2 0 65535 38 0 0]¡Tres enemigos! ¡Mucho cuidado![n][w][e]

[msg AST_btl_06_039_01]
[f 2 1][vp 2 0 65535 39 0 0]Hay tres enemigos... ¡Parecen fuertes![n][w][e]

[msg AST_btl_06_040_01]
[f 2 1][vp 2 0 65535 40 0 0]Cuatro enemigos, ¡pero no supondrán una amenaza![n][w][e]

[msg AST_btl_06_041_01]
[f 2 1][vp 2 0 65535 41 0 0]¡Cuatro objetivos! Cuidado, ¡que tienen fuerza de sobra![n][w][e]

[msg AST_btl_06_042_01]
[f 2 1][vp 2 0 65535 42 0 0]¡Cuatro enemigos potentes! Este combate va a estar complicado...[n][w][e]

[msg AST_btl_06_043_01]
[f 2 1][vp 2 0 65535 43 0 0]¡Cinco objetivos! No son fuertes, ¡pero son un montón![n][w][e]

[msg AST_btl_06_044_01]
[f 2 1][vp 2 0 65535 44 0 0]¡Cinco enemigos detectados! ¡Calmaos y abatidlos![n][w][e]

[msg AST_btl_06_045_01]
[f 2 1][vp 2 0 65535 45 0 0]Cinco enemigos fuertes... ¡Tened cuidado![n][w][e]

[msg AST_btl_06_046_01]
[f 2 1][vp 2 0 65535 46 0 0]¡Ah! ¡El enemigo parece duro![n][w][e]

[msg AST_btl_06_046_02]
[f 2 1][vp 2 0 65535 47 0 0]Es peligroso... ¡No bajéis la guardia![n][w][e]

[msg AST_btl_06_046_03]
[f 2 1][vp 2 0 65535 48 0 0]Estoy detectando un pico de energía... ¡Mucho cuidado![n][w][e]

[msg AST_btl_06_047_01]
[f 2 1][vp 2 0 65535 49 0 0]¡Un enemigo poco común! ¡Derrotarlo sería estupendo![n][w][e]

[msg AST_btl_06_047_02]
[f 2 1][vp 2 0 65535 50 0 0]¡Ese es especial! ¡Liquidadlo si podéis![n][w][e]

[msg AST_btl_06_047_03]
[f 2 1][vp 2 0 65535 51 0 0]¡Una sombra rara! ¡Haz lo posible por abatirla![n][w][e]

[msg AST_btl_06_048_01]
[f 2 1][vp 2 0 65535 52 0 0]¡Un enemigo del arcano de la Muerte! ¡Tenéis que salir de ahí![n][w][e]

[msg AST_btl_06_048_02]
[f 2 1][vp 2 0 65535 53 0 0]No tenéis oportunidad... ¡Retiraos![n][w][e]

[msg AST_btl_06_049_01]
[f 2 1][vp 2 0 65535 54 0 0]Un enemigo del arcano de la Muerte... ¡Vamos a darlo todo![n][w][e]

[msg AST_btl_06_049_02]
[f 2 1][vp 2 0 65535 55 0 0]¡Si las cosas se ponen feas, siempre podéis retiraros![n][w][e]

[msg AST_btl_06_050_01]
[f 2 1][vp 2 0 65535 56 0 0]¡Refuerzos enemigos![n][w][e]

[msg AST_btl_06_050_02]
[f 2 1][vp 2 0 65535 57 0 0]¡Otra oleada de enemigos![n][w][e]

[msg AST_btl_06_050_03]
[f 2 1][vp 2 0 65535 58 0 0]¡Se acercan más![n][w][e]

[msg AST_btl_06_051_01]
[f 2 1][vp 2 0 65535 59 0 0]Parece el jefe de este sitio. Detecto un pico de energía... ¡Tened cuidado![n][w][e]

[msg AST_btl_06_051_02]
[f 2 1][vp 2 0 65535 60 0 0]Esa no es una sombra corriente. ¡Id con mucho ojo![n][w][e]

[msg AST_btl_06_051_03]
[f 2 1][vp 2 0 65535 61 0 0]Es el guardián de esta zona. ¡Todos concentrados![n][w][e]

[msg AST_btl_06_052_01]
[f 2 1][vp 2 0 65535 62 0 0]¡Varios miembros abatidos![n][w][e]

[msg AST_btl_06_053_01]
[f 2 1][vp 2 0 65535 63 0 0]¿Qué? ¡Líder! ¡Di algo, por favor![n][w][e]

[msg AST_btl_06_054_01]
[f 2 1][vp 2 0 65535 64 0 0]No... ¡Yukari![n][w][e]

[msg AST_btl_06_055_01]
[f 2 1][vp 2 0 65535 65 0 0]¡Junpei está fuera de combate![n][w][e]

[msg AST_btl_06_056_01]
[f 2 1][vp 2 0 65535 66 0 0]¡Sanada, no![n][w][e]

[msg AST_btl_06_057_01]
[f 2 1][vp 2 0 65535 67 0 0]No puede ser... ¡Kirijo![n][w][e]

[msg AST_btl_06_058_01]
[f 2 1][vp 2 0 65535 68 0 0]¡Ah! ¡Aigis![n][w][e]

[msg AST_btl_06_059_01]
[f 2 1][vp 2 0 65535 69 0 0]Oh, no... ¡Amada![n][w][e]

[msg AST_btl_06_060_01]
[f 2 1][vp 2 0 65535 70 0 0]¿Eh? ¡¿Korocito?![n][w][e]

[msg AST_btl_06_061_01]
[f 2 1][vp 2 0 65535 71 0 0]¡Han abatido a Aragaki! ¡Que alguien lo ayude![n][w][e]

[msg AST_btl_06_062_01]
[f 2 1][vp 2 0 65535 72 0 0]No... ¡¿Alguien puede ayudar?![n][w][e]

[msg AST_btl_06_063_01]
[f 2 1][vp 2 0 65535 73 0 0]Oh, no. Esto pinta fatal...[n][w][e]

[msg AST_btl_06_064_01]
[f 2 1][vp 2 0 65535 74 0 0]¡La líder corre peligro![n][w][e]

[msg AST_btl_06_065_01]
[f 2 1][vp 2 0 65535 75 0 0]¡Yukari! ¿Te encuentras bien...?[n][w][e]

[msg AST_btl_06_066_01]
[f 2 1][vp 2 0 65535 76 0 0]¡Junpei está para el arrastre![n][w][e]

[msg AST_btl_06_067_01]
[f 2 1][vp 2 0 65535 77 0 0]¡Ah! ¡Sanada está en peligro![n][w][e]

[msg AST_btl_06_068_01]
[f 2 1][vp 2 0 65535 78 0 0]¡Kirijo! ¡Que alguien la ayude![n][w][e]

[msg AST_btl_06_069_01]
[f 2 1][vp 2 0 65535 79 0 0]¡Aigis ha recibido mucho daño![n][w][e]

[msg AST_btl_06_070_01]
[f 2 1][vp 2 0 65535 80 0 0]¡Amada, ten cuidado![n][w][e]

[msg AST_btl_06_071_01]
[f 2 1][vp 2 0 65535 81 0 0]Korocito, ¡no recibas ni un golpe más![n][w][e]

[msg AST_btl_06_072_01]
[f 2 1][vp 2 0 65535 82 0 0]Aragaki, ¡no podrás aguantar mucho más![n][w][e]

[msg AST_btl_06_073_01]
[f 2 1][vp 2 0 65535 83 0 0]¡Estás herida! ¿Tienes algo para curarte?[n][w][e]

[msg AST_btl_06_074_01]
[f 2 1][vp 2 0 65535 84 0 0]¡Oh, no! ¡Tienes que intentar levantarte![n][w][e]

[msg AST_btl_06_075_01]
[f 2 1][vp 2 0 65535 85 0 0]¡Ay! ¡Han derribado a la líder![n][w][e]

[msg AST_btl_06_076_01]
[f 2 1][vp 2 0 65535 86 0 0]¡Han derribado a Yukari! ¡Está en apuros![n][w][e]

[msg AST_btl_06_077_01]
[f 2 1][vp 2 0 65535 87 0 0]¡Junpei ha caído! ¡Que alguien lo cubra![n][w][e]

[msg AST_btl_06_078_01]
[f 2 1][vp 2 0 65535 88 0 0]¡Han derribado a Sanada! ¡¿Estás bien?![n][w][e]

[msg AST_btl_06_079_01]
[f 2 1][vp 2 0 65535 89 0 0]¡Han derribado a Kirijo! ¡Que alguien haga algo![n][w][e]

[msg AST_btl_06_080_01]
[f 2 1][vp 2 0 65535 90 0 0]¡Han derribado a Aigis! Mal asunto...[n][w][e]

[msg AST_btl_06_081_01]
[f 2 1][vp 2 0 65535 91 0 0]¡Han derribado a Amada! ¡Necesita ayuda![n][w][e]

[msg AST_btl_06_082_01]
[f 2 1][vp 2 0 65535 92 0 0]¡Oh, no! ¡Han abatido a Korocito![n][w][e]

[msg AST_btl_06_083_01]
[f 2 1][vp 2 0 65535 93 0 0]¡Han derribado a Aragaki! ¿Estás bien?[n][w][e]

[msg AST_btl_06_084_01]
[f 2 1][vp 2 0 65535 94 0 0]Ay, ¡te han derribado![n][w][e]

[msg AST_btl_06_085_01]
[f 2 1][vp 2 0 65535 95 0 0]Hala... ¡Nadie ha sufrido daños![n][w][e]

[msg AST_btl_06_086_01]
[f 2 1][vp 2 0 65535 96 0 0]¡Lo has esquivado! ¡Esa es nuestra líder![n][w][e]

[msg AST_btl_06_087_01]
[f 2 1][vp 2 0 65535 97 0 0]¡Vaya reflejos, Yukari![n][w][e]

[msg AST_btl_06_088_01]
[f 2 1][vp 2 0 65535 98 0 0]¡Buena evasión, Junpei![n][w][e]

[msg AST_btl_06_089_01]
[f 2 1][vp 2 0 65535 99 0 0]¡Gran juego de piernas, Sanada![n][w][e]

[msg AST_btl_06_090_01]
[f 2 1][vp 2 0 65535 100 0 0]¡Kirijo, una esquiva preciosa![n][w][e]

[msg AST_btl_06_091_01]
[f 2 1][vp 2 0 65535 101 0 0]¡Aigis ha esquivado el ataque![n][w][e]

[msg AST_btl_06_092_01]
[f 2 1][vp 2 0 65535 102 0 0]¡Muy buena evasión, Amada![n][w][e]

[msg AST_btl_06_093_01]
[f 2 1][vp 2 0 65535 103 0 0]¡Buen chico, Korocito![n][w][e]

[msg AST_btl_06_094_01]
[f 2 1][vp 2 0 65535 104 0 0]¡Aragaki ha esquivado un ataque![n][w][e]

[msg AST_btl_06_095_01]
[f 2 1][vp 2 0 65535 105 0 0]¡Has esquivado el ataque! ¡Qué buena![n][w][e]

[msg AST_btl_06_096_01]
[f 2 1][vp 2 0 65535 106 0 0]¡El enemigo ha huido! ¡Quedan cuatro![n][w][e]

[msg AST_btl_06_097_01]
[f 2 1][vp 2 0 65535 107 0 0]¡El enemigo se ha retirado! ¡Quedan tres![n][w][e]

[msg AST_btl_06_098_01]
[f 2 1][vp 2 0 65535 108 0 0]¡Ha huido! ¡Quedan dos![n][w][e]

[msg AST_btl_06_099_01]
[f 2 1][vp 2 0 65535 109 0 0]¡Un enemigo ha escapado! ¡Ya solo nos falta uno![n][w][e]

[msg AST_btl_06_100_01]
[f 2 1][vp 2 0 65535 110 0 0]¡El enemigo se retira! ¡Así se hace, equipo![n][w][e]

[msg AST_btl_06_101_01]
[f 2 1][vp 2 0 65535 111 0 0]Cuidado, tu poder de ataque es bajo.[n][w][e]

[msg AST_btl_06_102_01]
[f 2 1][vp 2 0 65535 112 0 0]¡Yukari, tu poder de ataque se ha reducido![n][w][e]

[msg AST_btl_06_103_01]
[f 2 1][vp 2 0 65535 113 0 0]¡Junpei, tu poder de ataque ha caído![n][w][e]

[msg AST_btl_06_104_01]
[f 2 1][vp 2 0 65535 114 0 0]¡Sanada, tu poder de ataque se ha reducido![n][w][e]

[msg AST_btl_06_105_01]
[f 2 1][vp 2 0 65535 115 0 0]¡Kirijo, tu poder de ataque ha disminuido![n][w][e]

[msg AST_btl_06_106_01]
[f 2 1][vp 2 0 65535 116 0 0]¡Aigis, tu poder de ataque ha disminuido![n][w][e]

[msg AST_btl_06_107_01]
[f 2 1][vp 2 0 65535 117 0 0]¡Amada, tu poder de ataque ha disminuido![n][w][e]

[msg AST_btl_06_108_01]
[f 2 1][vp 2 0 65535 118 0 0]¡Korocito, tu poder de ataque ha caído![n][w][e]

[msg AST_btl_06_109_01]
[f 2 1][vp 2 0 65535 119 0 0]¡Aragaki, tu poder de ataque se ha reducido![n][w][e]

[msg AST_btl_06_110_01]
[f 2 1][vp 2 0 65535 120 0 0]Se ha reducido tu poder de ataque...[n][w][e]

[msg AST_btl_06_111_01]
[f 2 1][vp 2 0 65535 121 0 0]Tu defensa ha caído. ¡Cuidado con tu salud![n][w][e]

[msg AST_btl_06_112_01]
[f 2 1][vp 2 0 65535 122 0 0]Yukari, ten cuidado. ¡Tu defensa ha caído![n][w][e]

[msg AST_btl_06_113_01]
[f 2 1][vp 2 0 65535 123 0 0]¡Cuidado, Junpei! ¡Tu defensa ha disminuido![n][w][e]

[msg AST_btl_06_114_01]
[f 2 1][vp 2 0 65535 124 0 0]Sanada, ¡tu defensa se ha reducido![n][w][e]

[msg AST_btl_06_115_01]
[f 2 1][vp 2 0 65535 125 0 0]Kirijo, ¡tu defensa se ha reducido![n][w][e]

[msg AST_btl_06_116_01]
[f 2 1][vp 2 0 65535 126 0 0]¡Aigis, ahora tienes poca defensa![n][w][e]

[msg AST_btl_06_117_01]
[f 2 1][vp 2 0 65535 127 0 0]¡Amada, tu defensa ha disminuido![n][w][e]

[msg AST_btl_06_118_01]
[f 2 1][vp 2 0 65535 128 0 0]Korocito, ¡tu defensa ha caído![n][w][e]

[msg AST_btl_06_119_01]
[f 2 1][vp 2 0 65535 129 0 0]¡Aragaki, tu defensa ha disminuido![n][w][e]

[msg AST_btl_06_120_01]
[f 2 1][vp 2 0 65535 130 0 0]Tienes poca defensa...[n][w][e]

[msg AST_btl_06_121_01]
[f 2 1][vp 2 0 65535 131 0 0]Tu velocidad se ha reducido... ¡Ten cuidado![n][w][e]

[msg AST_btl_06_122_01]
[f 2 1][vp 2 0 65535 132 0 0]¡Tu velocidad se ha reducido, Yukari![n][w][e]

[msg AST_btl_06_123_01]
[f 2 1][vp 2 0 65535 133 0 0]Junpei, ¡tu velocidad se ha reducido![n][w][e]

[msg AST_btl_06_124_01]
[f 2 1][vp 2 0 65535 134 0 0]Sanada, ¡tu velocidad ha caído![n][w][e]

[msg AST_btl_06_125_01]
[f 2 1][vp 2 0 65535 135 0 0]Kirijo, ¡tu velocidad ha disminuido![n][w][e]

[msg AST_btl_06_126_01]
[f 2 1][vp 2 0 65535 136 0 0]¡Cuidado, Aigis! ¡Tu velocidad ha disminuido![n][w][e]

[msg AST_btl_06_127_01]
[f 2 1][vp 2 0 65535 137 0 0]Amada, ¡tu velocidad ha disminuido![n][w][e]

[msg AST_btl_06_128_01]
[f 2 1][vp 2 0 65535 138 0 0]¡Korocito, tu velocidad se ha reducido![n][w][e]

[msg AST_btl_06_129_01]
[f 2 1][vp 2 0 65535 139 0 0]Aragaki, ¡tu velocidad está a mínimos![n][w][e]

[msg AST_btl_06_130_01]
[f 2 1][vp 2 0 65535 140 0 0]¡Se ha reducido tu velocidad! Tendrá un impacto en tu precisión y evasión.[n][w][e]

[msg AST_btl_06_131_01]
[f 2 1][vp 2 0 65535 141 0 0]¡Cinco enemigos! ¡No cometamos imprudencias![n][w][e]

[msg AST_btl_06_132_01]
[f 2 1][vp 2 0 65535 142 0 0]¡Hay cuatro! ¡Vamos a por todas![n][w][e]

[msg AST_btl_06_133_01]
[f 2 1][vp 2 0 65535 143 0 0]¡Quedan tres enemigos! ¡No bajemos la guardia![n][w][e]

[msg AST_btl_06_134_01]
[f 2 1][vp 2 0 65535 144 0 0]¡Solo quedan dos! ¡Claro que podéis![n][w][e]

[msg AST_btl_06_135_01]
[f 2 1][vp 2 0 65535 145 0 0]¡Último! ¡Acabemos con esto![n][w][e]

[msg AST_btl_06_136_01]
[f 2 1][vp 2 0 65535 146 0 0]Están todos agotados, ¡mira a ver si curas un poco![n][w][e]

[msg AST_btl_06_137_01]
[f 2 1][vp 2 0 65535 147 0 0]Líder, ¡te queda poca salud! ¡Ve con cuidado![n][w][e]

[msg AST_btl_06_138_01]
[f 2 1][vp 2 0 65535 148 0 0]Yukari está en apuros... ¿Tienes un momento para sanarla?[n][w][e]

[msg AST_btl_06_139_01]
[f 2 1][vp 2 0 65535 149 0 0]Junpei, ¿te encuentras bien? Vigila tu salud.[n][w][e]

[msg AST_btl_06_140_01]
[f 2 1][vp 2 0 65535 150 0 0]¡Sanada está en apuros! ¡Que alguien lo ayude![n][w][e]

[msg AST_btl_06_141_01]
[f 2 1][vp 2 0 65535 151 0 0]¡La salud de Kirijo está en mínimos! ¡Que alguien la ayude![n][w][e]

[msg AST_btl_06_142_01]
[f 2 1][vp 2 0 65535 152 0 0]Aigis ha recibido mucho daño... ¡Necesita recuperarse![n][w][e]

[msg AST_btl_06_143_01]
[f 2 1][vp 2 0 65535 153 0 0]Amada, ¿estás bien? ¿Le puede echar alguien un vistazo?[n][w][e]

[msg AST_btl_06_144_01]
[f 2 1][vp 2 0 65535 154 0 0]¡Korocito está en peligro! ¡Necesita ayuda ya![n][w][e]

[msg AST_btl_06_145_01]
[f 2 1][vp 2 0 65535 155 0 0]¡Aragaki está herido! ¡Necesita tratamiento![n][w][e]

[msg AST_btl_06_146_01]
[f 2 1][vp 2 0 65535 156 0 0]¡No te queda mucha salud! ¿Puedes curarte?[n][w][e]

[msg AST_btl_06_147_01]
[f 2 1][vp 2 0 65535 157 0 0]¡Aguanta hasta que entres en calor![n][w][e]

[msg AST_btl_06_148_01]
[f 2 1][vp 2 0 65535 158 0 0]¡Yukari está congelada! ¡No puede moverse![n][w][e]

[msg AST_btl_06_149_01]
[f 2 1][vp 2 0 65535 159 0 0]¡Junpei! ¡Está congelado![n][w][e]

[msg AST_btl_06_150_01]
[f 2 1][vp 2 0 65535 160 0 0]¡Parece que Sanada no puede moverse![n][w][e]

[msg AST_btl_06_151_01]
[f 2 1][vp 2 0 65535 161 0 0]¡Kirijo está congelada! ¡No puede moverse sola![n][w][e]

[msg AST_btl_06_152_01]
[f 2 1][vp 2 0 65535 162 0 0]¡Aigis se ha congelado![n][w][e]

[msg AST_btl_06_153_01]
[f 2 1][vp 2 0 65535 163 0 0]Amada está congelado... ¡Así no podrá moverse![n][w][e]

[msg AST_btl_06_154_01]
[f 2 1][vp 2 0 65535 164 0 0]Ay, ¡han congelado a Korocito![n][w][e]

[msg AST_btl_06_155_01]
[f 2 1][vp 2 0 65535 165 0 0]Aragaki está congelado... ¡No puede moverse![n][w][e]

[msg AST_btl_06_156_01]
[f 2 1][vp 2 0 65535 166 0 0]¡Estás congelada! ¡Así no podrás moverte![n][w][e]

[msg AST_btl_06_157_01]
[f 2 1][vp 2 0 65535 167 0 0]¡Aguanta de momento! ¡Saldrás de esta![n][w][e]

[msg AST_btl_06_158_01]
[f 2 1][vp 2 0 65535 168 0 0]¡Yukari! ¡La electricidad no te deja moverte![n][w][e]

[msg AST_btl_06_159_01]
[f 2 1][vp 2 0 65535 169 0 0]No parece que Junpei pueda moverse...[n][w][e]

[msg AST_btl_06_160_01]
[f 2 1][vp 2 0 65535 170 0 0]Sanada está paralizado. ¡No puede moverse![n][w][e]

[msg AST_btl_06_161_01]
[f 2 1][vp 2 0 65535 171 0 0]¡Kirijo sigue sin poder moverse![n][w][e]

[msg AST_btl_06_162_01]
[f 2 1][vp 2 0 65535 172 0 0]¡Aigis está paralizada por la descarga![n][w][e]

[msg AST_btl_06_163_01]
[f 2 1][vp 2 0 65535 173 0 0]Amada está electrificado. ¡No puede moverse![n][w][e]

[msg AST_btl_06_164_01]
[f 2 1][vp 2 0 65535 174 0 0]¡La electricidad no deja moverse a Korocito![n][w][e]

[msg AST_btl_06_165_01]
[f 2 1][vp 2 0 65535 175 0 0]Aragaki está electrificado. ¡Aún no puede moverse![n][w][e]

[msg AST_btl_06_166_01]
[f 2 1][vp 2 0 65535 176 0 0]¡La descarga eléctrica impide moverte![n][w][e]

[msg AST_btl_06_167_01]
[f 2 1][vp 2 0 65535 177 0 0]¡Líder! ¡¿Me oyes?![n][w][e]

[msg AST_btl_06_168_01]
[f 2 1][vp 2 0 65535 178 0 0]Han manipulado a Yukari. ¿Podrías ayudarla?[n][w][e]

[msg AST_btl_06_169_01]
[f 2 1][vp 2 0 65535 179 0 0]¡Junpei sufre manipulación! ¡Vamos, recupera el sentido![n][w][e]

[msg AST_btl_06_170_01]
[f 2 1][vp 2 0 65535 180 0 0]¡Han manipulado a Sanada! ¿Puedes ayudarlo?[n][w][e]

[msg AST_btl_06_171_01]
[f 2 1][vp 2 0 65535 181 0 0]¡Kirijo está bajo los efectos de la manipulación! ¿Puedes hacer algo?[n][w][e]

[msg AST_btl_06_172_01]
[f 2 1][vp 2 0 65535 182 0 0]Aigis está manipulada... ¡No distingue amigos de enemigos![n][w][e]

[msg AST_btl_06_173_01]
[f 2 1][vp 2 0 65535 183 0 0]Están manipulando a Amada. ¡Entra en razón, por favor![n][w][e]

[msg AST_btl_06_174_01]
[f 2 1][vp 2 0 65535 184 0 0]¡Korocito! ¡Oh, no! ¡Se ha puesto de su parte![n][w][e]

[msg AST_btl_06_175_01]
[f 2 1][vp 2 0 65535 185 0 0]¡Aragaki está siendo manipulado! ¡Necesita ayuda![n][w][e]

[msg AST_btl_06_176_01]
[f 2 1][vp 2 0 65535 186 0 0]¡Te está manipulando el enemigo! Estamos de tu parte...[n][w][e]

[msg AST_btl_06_177_01]
[f 2 1][vp 2 0 65535 187 0 0]Te han envenenado... ¡Estás perdiendo salud![n][w][e]

[msg AST_btl_06_178_01]
[f 2 1][vp 2 0 65535 188 0 0]Han envenenado a Yukari. ¿Tienes un antídoto?[n][w][e]

[msg AST_btl_06_179_01]
[f 2 1][vp 2 0 65535 189 0 0]Junpei está envenenado. ¡Cuidado con la salud![n][w][e]

[msg AST_btl_06_180_01]
[f 2 1][vp 2 0 65535 190 0 0]Sanada, ¡estás envenenado! ¡Mucho ojo a tu salud![n][w][e]

[msg AST_btl_06_181_01]
[f 2 1][vp 2 0 65535 191 0 0]Han envenado a Kirijo. ¡¿Alguien puede curarla?![n][w][e]

[msg AST_btl_06_182_01]
[f 2 1][vp 2 0 65535 192 0 0]¡Aigis está envenenada! ¡Está perdiendo salud![n][w][e]

[msg AST_btl_06_183_01]
[f 2 1][vp 2 0 65535 193 0 0]¡Amada está envenenado...! ¡Tienes que curarlo![n][w][e]

[msg AST_btl_06_184_01]
[f 2 1][vp 2 0 65535 194 0 0]¡Korocito está envenenado! ¡Necesita ayuda![n][w][e]

[msg AST_btl_06_185_01]
[f 2 1][vp 2 0 65535 195 0 0]Aragaki está envenenado... ¡Controlad la salud![n][w][e]

[msg AST_btl_06_186_01]
[f 2 1][vp 2 0 65535 196 0 0]¡Te han envenenado! ¡Mucho ojo a tu salud![n][w][e]

[msg AST_btl_06_187_01]
[f 2 1][vp 2 0 65535 197 0 0]Estás angustiada. ¡Respira hondo![n][w][e]

[msg AST_btl_06_188_01]
[f 2 1][vp 2 0 65535 198 0 0]Yukari, ¡tranquilízate![n][w][e]

[msg AST_btl_06_189_01]
[f 2 1][vp 2 0 65535 199 0 0]Junpei, ¡cálmate![n][w][e]

[msg AST_btl_06_190_01]
[f 2 1][vp 2 0 65535 200 0 0]¡Sanada ha entrado en pánico![n][w][e]

[msg AST_btl_06_191_01]
[f 2 1][vp 2 0 65535 201 0 0]¡Kirijo está angustiada![n][w][e]

[msg AST_btl_06_192_01]
[f 2 1][vp 2 0 65535 202 0 0]Aigis, ¡tienes que calmarte![n][w][e]

[msg AST_btl_06_193_01]
[f 2 1][vp 2 0 65535 203 0 0]Amada está entrando en pánico. ¡Ayudadlo![n][w][e]

[msg AST_btl_06_194_01]
[f 2 1][vp 2 0 65535 204 0 0]¡Korocito está angustiado![n][w][e]

[msg AST_btl_06_195_01]
[f 2 1][vp 2 0 65535 205 0 0]¡Aragaki está angustiado![n][w][e]

[msg AST_btl_06_196_01]
[f 2 1][vp 2 0 65535 206 0 0]Te veo angustiada...[n][w][e]

[msg AST_btl_06_197_01]
[f 2 1][vp 2 0 65535 207 0 0]¡La líder está confundida! ¡Que alguien la cubra![n][w][e]

[msg AST_btl_06_198_01]
[f 2 1][vp 2 0 65535 208 0 0]¡Yukari está confundida! ¡Oh, no! ¡Está actuando sin sentido![n][w][e]

[msg AST_btl_06_199_01]
[f 2 1][vp 2 0 65535 209 0 0]¡Junpei está confundido! ¡C-cálmate un poco![n][w][e]

[msg AST_btl_06_200_01]
[f 2 1][vp 2 0 65535 210 0 0]¡Sanada está confundido! ¡Cuidado![n][w][e]

[msg AST_btl_06_201_01]
[f 2 1][vp 2 0 65535 211 0 0]¡Kirijo está confundida! ¡¿Q-qué está haciendo?![n][w][e]

[msg AST_btl_06_202_01]
[f 2 1][vp 2 0 65535 212 0 0]¡Aigis está confundida! ¡Intenta calmarte![n][w][e]

[msg AST_btl_06_203_01]
[f 2 1][vp 2 0 65535 213 0 0]¡Amada está confundido! ¡Que alguien lo cubra![n][w][e]

[msg AST_btl_06_204_01]
[f 2 1][vp 2 0 65535 214 0 0]¡Para, Korocito! ¡Tienes que calmarte![n][w][e]

[msg AST_btl_06_205_01]
[f 2 1][vp 2 0 65535 215 0 0]¡Aragaki está confundido! ¡T-tranquilízate![n][w][e]

[msg AST_btl_06_206_01]
[f 2 1][vp 2 0 65535 216 0 0]¡Alguien está confundido y puede actuar de forma impredecible![n][w][e]

[msg AST_btl_06_207_01]
[f 2 1][vp 2 0 65535 217 0 0]El miedo se pasa con el tiempo. ¡Aguanta![n][w][e]

[msg AST_btl_06_208_01]
[f 2 1][vp 2 0 65535 218 0 0]Yukari, ¡no dejes que te afecte el miedo![n][w][e]

[msg AST_btl_06_209_01]
[f 2 1][vp 2 0 65535 219 0 0]Junpei... ¿Será capaz de pelear?[n][w][e]

[msg AST_btl_06_210_01]
[f 2 1][vp 2 0 65535 220 0 0]Sanada está muy asustado para moverse.[n][w][e]

[msg AST_btl_06_211_01]
[f 2 1][vp 2 0 65535 221 0 0]Kirijo no puede hacer nada ahora mismo.[n][w][e]

[msg AST_btl_06_212_01]
[f 2 1][vp 2 0 65535 222 0 0]¡Aigis! ¿Estará bien?[n][w][e]

[msg AST_btl_06_213_01]
[f 2 1][vp 2 0 65535 223 0 0]¡Amada tiene miedo! ¡Ayudadlo![n][w][e]

[msg AST_btl_06_214_01]
[f 2 1][vp 2 0 65535 224 0 0]¡Korocito tiembla del miedo![n][w][e]

[msg AST_btl_06_215_01]
[f 2 1][vp 2 0 65535 225 0 0]Aragaki está muy mortificado para moverse.[n][w][e]

[msg AST_btl_06_216_01]
[f 2 1][vp 2 0 65535 226 0 0]El enemigo os ha infundido miedo. ¡Puede que alguien huya![n][w][e]

[msg AST_btl_06_217_01]
[f 2 1][vp 2 0 65535 227 0 0]¡Nuestra líder está inquieta! ¡Contrólate![n][w][e]

[msg AST_btl_06_218_01]
[f 2 1][vp 2 0 65535 228 0 0]Yukari está enfadada... ¡Tienes que entrar en razón![n][w][e]

[msg AST_btl_06_219_01]
[f 2 1][vp 2 0 65535 229 0 0]Junpei, ¡recupera el sentido de una vez![n][w][e]

[msg AST_btl_06_220_01]
[f 2 1][vp 2 0 65535 230 0 0]¡Sanada se está volviendo agresivo! ¡Cálmate, por favor![n][w][e]

[msg AST_btl_06_221_01]
[f 2 1][vp 2 0 65535 231 0 0]Kirijo, ¡tienes que despejar la mente![n][w][e]

[msg AST_btl_06_222_01]
[f 2 1][vp 2 0 65535 232 0 0]Aigis está perdiendo el temple. ¡Aguanta![n][w][e]

[msg AST_btl_06_223_01]
[f 2 1][vp 2 0 65535 233 0 0]Amada está perdiendo los nervios... ¡Tranquilízate![n][w][e]

[msg AST_btl_06_224_01]
[f 2 1][vp 2 0 65535 234 0 0]¡Korocito, no te enfades tanto![n][w][e]

[msg AST_btl_06_225_01]
[f 2 1][vp 2 0 65535 235 0 0]Aragaki parece cabreado. ¡Mantén la calma![n][w][e]

[msg AST_btl_06_226_01]
[f 2 1][vp 2 0 65535 236 0 0]La provocación del enemigo te está cabreando...[n][w][e]

[msg AST_btl_06_227_01]
[f 2 1][vp 2 0 65535 237 0 0]¡La líder está mareada![n][w][e]

[msg AST_btl_06_228_01]
[f 2 1][vp 2 0 65535 238 0 0]¡Yukari está mareada![n][w][e]

[msg AST_btl_06_229_01]
[f 2 1][vp 2 0 65535 239 0 0]¡Junpei está mareado![n][w][e]

[msg AST_btl_06_230_01]
[f 2 1][vp 2 0 65535 240 0 0]¡Sanada está mareado![n][w][e]

[msg AST_btl_06_231_01]
[f 2 1][vp 2 0 65535 241 0 0]¡Kirijo está mareada![n][w][e]

[msg AST_btl_06_232_01]
[f 2 1][vp 2 0 65535 242 0 0]¡Aigis está mareada![n][w][e]

[msg AST_btl_06_233_01]
[f 2 1][vp 2 0 65535 243 0 0]¡Amada está mareado![n][w][e]

[msg AST_btl_06_234_01]
[f 2 1][vp 2 0 65535 244 0 0]¡Levántate, Korocito![n][w][e]

[msg AST_btl_06_235_01]
[f 2 1][vp 2 0 65535 245 0 0]¡Aragaki está mareado![n][w][e]

[msg AST_btl_06_236_01]
[f 2 1][vp 2 0 65535 246 0 0]El mareo aún no se ha pasado...[n][w][e]

[msg AST_btl_06_237_01]
[f 2 1][vp 2 0 65535 247 0 0]¡Menos mal! ¡Es momento de contraatacar![n][w][e]

[msg AST_btl_06_238_01]
[f 2 1][vp 2 0 65535 248 0 0]¡Yukari se ha recuperado! ¡Hora de la revancha![n][w][e]

[msg AST_btl_06_239_01]
[f 2 1][vp 2 0 65535 249 0 0]¡Junpei! ¡Hora del contraataque![n][w][e]

[msg AST_btl_06_240_01]
[f 2 1][vp 2 0 65535 250 0 0]¡Sanada vuelve al combate![n][w][e]

[msg AST_btl_06_241_01]
[f 2 1][vp 2 0 65535 251 0 0]¡Kirijo se ha puesto de pie![n][w][e]

[msg AST_btl_06_242_01]
[f 2 1][vp 2 0 65535 252 0 0]¡Aigis se ha recuperado! ¡Hora de tomar represalias![n][w][e]

[msg AST_btl_06_243_01]
[f 2 1][vp 2 0 65535 253 0 0]¡Amada! ¡Hay que girar las tornas![n][w][e]

[msg AST_btl_06_244_01]
[f 2 1][vp 2 0 65535 254 0 0]¡Korocito vuelve a la faena! ¡Lo pagarán![n][w][e]

[msg AST_btl_06_245_01]
[f 2 1][vp 2 0 65535 255 0 0]¡Aragaki se ha recuperado! ¡Nos toca remontar![n][w][e]

[msg AST_btl_06_246_01]
[f 2 1][vp 2 0 65535 256 0 0]¡Has vuelto al combate! ¡Es nuestro turno![n][w][e]

[msg AST_btl_06_247_01]
[f 2 1][vp 2 0 65535 257 0 0]Creo que alguien podría aprovechar una debilidad...[n][w][e]

[msg AST_btl_06_247_02]
[f 2 1][vp 2 0 65535 258 0 0]¡Alguien puede aprovechar una debilidad! ¡Haz un cambio![n][w][e]

[msg AST_btl_06_247_03]
[f 2 1][vp 2 0 65535 259 0 0]Alguien podría atacar una debilidad. ¡Pasa el relevo![n][w][e]

[msg AST_btl_06_247_04]
[f 2 1][vp 2 0 65535 260 0 0]Si cambias, puedes atacar la debilidad del enemigo.[n][w][e]

[msg AST_btl_06_247_05]
[f 2 1][vp 2 0 65535 261 0 0]¡En equipo, podéis atacar la debilidad del enemigo![n][w][e]

[msg AST_btl_06_248_01]
[f 2 1][vp 2 0 65535 262 0 0]¡Estás en mal estado! ¡Tienes que recuperarte antes de que te golpeen![n][w][e]

[msg AST_btl_06_248_02]
[f 2 1][vp 2 0 65535 263 0 0]¡Ataque inminente del enemigo! ¡Tienes que curarte, rápido![n][w][e]

[msg AST_btl_06_248_03]
[f 2 1][vp 2 0 65535 264 0 0]¡Estás malherida! ¡Tienes que curarte ya![n][w][e]

[msg AST_btl_06_248_04]
[f 2 1][vp 2 0 65535 265 0 0]¿Puedes curarte? El enemigo va a atacar...[n][w][e]

[msg AST_btl_06_248_05]
[f 2 1][vp 2 0 65535 266 0 0]¡Llega el turno del enemigo! ¡Cúrate mientras puedas![n][w][e]

[msg AST_btl_06_249_01]
[f 2 1][vp 2 0 65535 267 0 0]El enemigo está congelado. ¡Es tu oportunidad![n][w][e]

[msg AST_btl_06_250_01]
[f 2 1][vp 2 0 65535 268 0 0]Están electrificados. ¡Están al descubierto![n][w][e]

[msg AST_btl_06_251_01]
[f 2 1][vp 2 0 65535 269 0 0]¡Tu teúrgia está lista![n][w][e]

[msg AST_btl_06_252_01]
[f 2 1][vp 2 0 65535 270 0 0]¡Puedes usar tu teúrgia! ¡Vamos, Yukari![n][w][e]

[msg AST_btl_06_253_01]
[f 2 1][vp 2 0 65535 271 0 0]¡Junpei! ¡Tu teúrgia está lista![n][w][e]

[msg AST_btl_06_254_01]
[f 2 1][vp 2 0 65535 272 0 0]¡Puedes usar tu teúrgia! ¡Adelante, Sanada![n][w][e]

[msg AST_btl_06_255_01]
[f 2 1][vp 2 0 65535 273 0 0]¡Puedes usar tu teúrgia! ¡Vamos, Kirijo![n][w][e]

[msg AST_btl_06_256_01]
[f 2 1][vp 2 0 65535 274 0 0]¡Aigis! ¡Tu teúrgia está lista![n][w][e]

[msg AST_btl_06_257_01]
[f 2 1][vp 2 0 65535 275 0 0]¡Amada! ¡Puedes usar tu teúrgia![n][w][e]

[msg AST_btl_06_258_01]
[f 2 1][vp 2 0 65535 276 0 0]¡Korocito! ¡Usa tu teúrgia![n][w][e]

[msg AST_btl_06_259_01]
[f 2 1][vp 2 0 65535 277 0 0]¡Puedes usar tu teúrgia! ¡Adelante, Aragaki![n][w][e]

[msg AST_btl_06_260_01]
[f 2 1][vp 2 0 65535 278 0 0]¡Tu teúrgia está lista! ¡Adelante![n][w][e]

[msg AST_btl_06_261_01]
[f 2 1][vp 2 0 65535 279 0 0]Mi teúrgia... Creo que la puedo usar ya.[n][w][e]

[msg AST_btl_06_262_01]
[f 2 1][vp 2 0 65535 280 0 0]¡Así se hace, líder![n][w][e]

[msg AST_btl_06_263_01]
[f 2 1][vp 2 0 65535 281 0 0]Yukari está completamente concentrada...[n][w][e]

[msg AST_btl_06_264_01]
[f 2 1][vp 2 0 65535 282 0 0]Junpei, ¡estás en racha![n][w][e]

[msg AST_btl_06_265_01]
[f 2 1][vp 2 0 65535 283 0 0]Sanada derrocha intensidad.[n][w][e]

[msg AST_btl_06_266_01]
[f 2 1][vp 2 0 65535 284 0 0]¡Kirijo está muy decidida![n][w][e]

[msg AST_btl_06_267_01]
[f 2 1][vp 2 0 65535 285 0 0]¡El nivel de poder de Aigis está en auge![n][w][e]

[msg AST_btl_06_268_01]
[f 2 1][vp 2 0 65535 286 0 0]¡Amada va cogiendo impulso![n][w][e]

[msg AST_btl_06_269_01]
[f 2 1][vp 2 0 65535 287 0 0]¡Korocito está lleno de energía![n][w][e]

[msg AST_btl_06_270_01]
[f 2 1][vp 2 0 65535 288 0 0]Aragaki está muy serio... Hay electricidad en el ambiente...[n][w][e]

[msg AST_btl_06_271_01]
[f 2 1][vp 2 0 65535 289 0 0]Estoy al tanto de tu salud. ¡Vas genial![n][w][e]

[msg AST_btl_06_272_01]
[f 2 1][vp 2 0 65535 290 0 0]¡Nuestra líder ha asestado el último golpe! ¡Ya estamos![n][w][e]

[msg AST_btl_06_273_01]
[f 2 1][vp 2 0 65535 291 0 0]¡Yukari ha acabado con ellos! ¡Buen trabajo![n][w][e]

[msg AST_btl_06_274_01]
[f 2 1][vp 2 0 65535 292 0 0]¡Buen golpe, Junpei! ¡Apañado![n][w][e]

[msg AST_btl_06_275_01]
[f 2 1][vp 2 0 65535 293 0 0]¡Sanada ha dado el golpe de gracia![n][w][e]

[msg AST_btl_06_276_01]
[f 2 1][vp 2 0 65535 294 0 0]¡Kirijo ha eliminado al enemigo![n][w][e]

[msg AST_btl_06_277_01]
[f 2 1][vp 2 0 65535 295 0 0]¡Aigis ha destruido al enemigo! ¡Buen trabajo![n][w][e]

[msg AST_btl_06_278_01]
[f 2 1][vp 2 0 65535 296 0 0]¡Amada ha liquidado al enemigo! No quedan objetivos.[n][w][e]

[msg AST_btl_06_279_01]
[f 2 1][vp 2 0 65535 297 0 0]¡Korocito ha dado el golpe de gracia![n][w][e]

[msg AST_btl_06_280_01]
[f 2 1][vp 2 0 65535 298 0 0]¡Aragaki ha arrollado al enemigo! ¡Hemos acabado![n][w][e]

[msg AST_btl_06_281_01]
[f 2 1][vp 2 0 65535 299 0 0]¡Todos los objetivos están fuera! ¡Gran trabajo![n][w][e]

[msg AST_btl_06_282_01]
[f 2 1][vp 2 0 65535 300 0 0]¡Tu poder es increíble, líder![n][w][e]

[msg AST_btl_06_283_01]
[f 2 1][vp 2 0 65535 301 0 0]¡Lo has clavado, Yukari![n][w][e]

[msg AST_btl_06_284_01]
[f 2 1][vp 2 0 65535 302 0 0]¡Junpei se ha cargado al enemigo![n][w][e]

[msg AST_btl_06_285_01]
[f 2 1][vp 2 0 65535 303 0 0]¡Sanada ha logrado acabar con ellos![n][w][e]

[msg AST_btl_06_286_01]
[f 2 1][vp 2 0 65535 304 0 0]¡Qué perfección! ¡Impresionante como siempre, Kirijo![n][w][e]

[msg AST_btl_06_287_01]
[f 2 1][vp 2 0 65535 305 0 0]¡Enemigos eliminados! ¡Fabuloso, Aigis![n][w][e]

[msg AST_btl_06_288_01]
[f 2 1][vp 2 0 65535 306 0 0]¡Se acabó el combate! Buena teúrgia, Amada.[n][w][e]

[msg AST_btl_06_289_01]
[f 2 1][vp 2 0 65535 307 0 0]¡Korocito ha abatido al enemigo! ¡Ha sido impresionante![n][w][e]

[msg AST_btl_06_290_01]
[f 2 1][vp 2 0 65535 308 0 0]¡Enemigo liquidado! ¡Así se hace, Aragaki![n][w][e]

[msg AST_btl_06_291_01]
[f 2 1][vp 2 0 65535 309 0 0]Con que este es el poder de la teúrgia... ¡No quedan enemigos![n][w][e]

[msg AST_btl_06_292_01]
[f 2 1][vp 2 0 65535 310 0 0]¡Cuatro objetivos eliminados! ¡Qué pasada, líder![n][w][e]

[msg AST_btl_06_293_01]
[f 2 1][vp 2 0 65535 311 0 0]¡Cuatro enemigos liquidados! ¡Bien hecho, Yukari![n][w][e]

[msg AST_btl_06_294_01]
[f 2 1][vp 2 0 65535 312 0 0]¡Cuatro a tomar viento! ¡Muy bien, Junpei![n][w][e]

[msg AST_btl_06_295_01]
[f 2 1][vp 2 0 65535 313 0 0]¡Cuatro a la vez! ¡Fantástico, Sanada![n][w][e]

[msg AST_btl_06_296_01]
[f 2 1][vp 2 0 65535 314 0 0]¡Cuatro enemigos derrotados! ¡Bien hecho, Kirijo![n][w][e]

[msg AST_btl_06_297_01]
[f 2 1][vp 2 0 65535 315 0 0]¡Cuatro objetivos destruidos! ¡Gran trabajo, Aigis![n][w][e]

[msg AST_btl_06_298_01]
[f 2 1][vp 2 0 65535 316 0 0]¡Cuatro liquidados a la vez! ¡Así se hace, Amada![n][w][e]

[msg AST_btl_06_299_01]
[f 2 1][vp 2 0 65535 317 0 0]¡Cuatro a la vez! ¡Buen chico, Korocito![n][w][e]

[msg AST_btl_06_300_01]
[f 2 1][vp 2 0 65535 318 0 0]¡Cuatro enemigos eliminados! ¡Menos mal que podemos contar con Aragaki![n][w][e]

[msg AST_btl_06_301_01]
[f 2 1][vp 2 0 65535 319 0 0]¡Guau! ¡Has eliminado a cuatro a la vez![n][w][e]

[msg AST_btl_06_302_01]
[f 2 1][vp 2 0 65535 320 0 0]¡Tres enemigos eliminados! ¡Buen trabajo![n][w][e]

[msg AST_btl_06_303_01]
[f 2 1][vp 2 0 65535 321 0 0]¡Yukari se ha cargado a tres a la vez![n][w][e]

[msg AST_btl_06_304_01]
[f 2 1][vp 2 0 65535 322 0 0]¡Tres a la vez! ¡Qué buena, Junpei![n][w][e]

[msg AST_btl_06_305_01]
[f 2 1][vp 2 0 65535 323 0 0]¡Sanada se ha cargado a tres enemigos![n][w][e]

[msg AST_btl_06_306_01]
[f 2 1][vp 2 0 65535 324 0 0]¡Kirijo se ha cargado a tres objetivos con ese ataque![n][w][e]

[msg AST_btl_06_307_01]
[f 2 1][vp 2 0 65535 325 0 0]¡Aigis se ha cargado a tres enemigos![n][w][e]

[msg AST_btl_06_308_01]
[f 2 1][vp 2 0 65535 326 0 0]¡Amada ha eliminado a tres enemigos![n][w][e]

[msg AST_btl_06_309_01]
[f 2 1][vp 2 0 65535 327 0 0]¡Tres enemigos derrotados! ¡Buena esa, Korocito![n][w][e]

[msg AST_btl_06_310_01]
[f 2 1][vp 2 0 65535 328 0 0]¡Aragaki ha derribado a tres enemigos![n][w][e]

[msg AST_btl_06_311_01]
[f 2 1][vp 2 0 65535 329 0 0]¡Tres enemigos derrotados a la vez![n][w][e]

[msg AST_btl_06_312_01]
[f 2 1][vp 2 0 65535 330 0 0]¡Nuestra líder ha liquidado a dos enemigos![n][w][e]

[msg AST_btl_06_313_01]
[f 2 1][vp 2 0 65535 331 0 0]¡Muy bien, Yukari! ¡Dos enemigos menos![n][w][e]

[msg AST_btl_06_314_01]
[f 2 1][vp 2 0 65535 332 0 0]¡Junpei se ha cargado a dos enemigos![n][w][e]

[msg AST_btl_06_315_01]
[f 2 1][vp 2 0 65535 333 0 0]¡Sanada ha derrotado a dos enemigos![n][w][e]

[msg AST_btl_06_316_01]
[f 2 1][vp 2 0 65535 334 0 0]¡Kirijo ha derrotado a dos enemigos![n][w][e]

[msg AST_btl_06_317_01]
[f 2 1][vp 2 0 65535 335 0 0]¡Lo haces genial, Aigis! ¡Dos enemigos derrotados![n][w][e]

[msg AST_btl_06_318_01]
[f 2 1][vp 2 0 65535 336 0 0]¡Lo has conseguido, Amada! ¡Dos enemigos de golpe![n][w][e]

[msg AST_btl_06_319_01]
[f 2 1][vp 2 0 65535 337 0 0]¡Muy bien, Korocito! ¡Dos enemigos menos![n][w][e]

[msg AST_btl_06_320_01]
[f 2 1][vp 2 0 65535 338 0 0]¡Que aprendan, Aragaki! ¡Dos por uno![n][w][e]

[msg AST_btl_06_321_01]
[f 2 1][vp 2 0 65535 339 0 0]¡Dos enemigos derrotados a la vez![n][w][e]

[msg AST_btl_06_322_01]
[f 2 1][vp 2 0 65535 340 0 0]¡La líder ha acabado con uno![n][w][e]

[msg AST_btl_06_323_01]
[f 2 1][vp 2 0 65535 341 0 0]¡Enemigo derrotado! ¡Vas genial, Yukari![n][w][e]

[msg AST_btl_06_324_01]
[f 2 1][vp 2 0 65535 342 0 0]¡Un enemigo menos! ¡Sigue así, Junpei![n][w][e]

[msg AST_btl_06_325_01]
[f 2 1][vp 2 0 65535 343 0 0]¡Enemigo eliminado! ¡Qué buena, Sanada![n][w][e]

[msg AST_btl_06_326_01]
[f 2 1][vp 2 0 65535 344 0 0]¡Un enemigo derrotado! ¡Así se hace, Mitsuru![n][w][e]

[msg AST_btl_06_327_01]
[f 2 1][vp 2 0 65535 345 0 0]¡Objetivo destruido! ¡Así se hace, Aigis![n][w][e]

[msg AST_btl_06_328_01]
[f 2 1][vp 2 0 65535 346 0 0]¡Enemigo derrotado! ¡Buen trabajo, Amada![n][w][e]

[msg AST_btl_06_329_01]
[f 2 1][vp 2 0 65535 347 0 0]¡Enemigo eliminado! ¡Buen chico, Korocito![n][w][e]

[msg AST_btl_06_330_01]
[f 2 1][vp 2 0 65535 348 0 0]¡Enemigo destruido! ¡Vaya fuerza, Aragaki![n][w][e]

[msg AST_btl_06_331_01]
[f 2 1][vp 2 0 65535 349 0 0]¡Un enemigo eliminado![n][w][e]

[msg AST_btl_06_332_01]
[f 2 1][vp 2 0 65535 350 0 0]¡Genial! ¡Todos los enemigos están derribados![n][w][e]

[msg AST_btl_06_333_01]
[f 2 1][vp 2 0 65535 351 0 0]¡Todas derribadas! ¡Así se hace, Yukari![n][w][e]

[msg AST_btl_06_334_01]
[f 2 1][vp 2 0 65535 352 0 0]¡Todos derribados! ¡Estás a tope, Junpei![n][w][e]

[msg AST_btl_06_335_01]
[f 2 1][vp 2 0 65535 353 0 0]¡Todos los enemigos derribados! ¡Muy bien, Sanada![n][w][e]

[msg AST_btl_06_336_01]
[f 2 1][vp 2 0 65535 354 0 0]¡Todos derribados! ¡Impresionante, Kirijo![n][w][e]

[msg AST_btl_06_337_01]
[f 2 1][vp 2 0 65535 355 0 0]¡Todos derribados! ¡Qué bien, Aigis![n][w][e]

[msg AST_btl_06_338_01]
[f 2 1][vp 2 0 65535 356 0 0]¡Todos derribados! ¡Muy buena, Amada![n][w][e]

[msg AST_btl_06_339_01]
[f 2 1][vp 2 0 65535 357 0 0]¡Todos derribados! ¡Lo has conseguido, Korocito![n][w][e]

[msg AST_btl_06_340_01]
[f 2 1][vp 2 0 65535 358 0 0]¡Todos derribados! ¡Buen trabajo, Aragaki![n][w][e]

[msg AST_btl_06_341_01]
[f 2 1][vp 2 0 65535 359 0 0]¡Madre mía, has roto su formación![n][w][e]

[msg AST_btl_06_342_01]
[f 2 1][vp 2 0 65535 360 0 0]¡Cuatro enemigos derribados! ¡Fenomenal![n][w][e]

[msg AST_btl_06_343_01]
[f 2 1][vp 2 0 65535 361 0 0]¡Cuatro menos! ¡Perfecto, Yukari![n][w][e]

[msg AST_btl_06_344_01]
[f 2 1][vp 2 0 65535 362 0 0]¡Cuatro enemigos derribados! ¡Sigue así, Junpei![n][w][e]

[msg AST_btl_06_345_01]
[f 2 1][vp 2 0 65535 363 0 0]¡Sanada ha derribado a cuatro enemigos a la vez![n][w][e]

[msg AST_btl_06_346_01]
[f 2 1][vp 2 0 65535 364 0 0]¡Kirijo ha derribado a cuatro a la vez![n][w][e]

[msg AST_btl_06_347_01]
[f 2 1][vp 2 0 65535 365 0 0]¡Cuatro enemigos derribados! ¡Increíble, Aigis![n][w][e]

[msg AST_btl_06_348_01]
[f 2 1][vp 2 0 65535 366 0 0]¡Cuatro derribados! ¡Sigue así, Amada![n][w][e]

[msg AST_btl_06_349_01]
[f 2 1][vp 2 0 65535 367 0 0]¡Cuatro enemigos derribados! ¡Korocito es la caña![n][w][e]

[msg AST_btl_06_350_01]
[f 2 1][vp 2 0 65535 368 0 0]¡Aragaki ha abatido a cuatro enemigos![n][w][e]

[msg AST_btl_06_351_01]
[f 2 1][vp 2 0 65535 369 0 0]¡Cuatro enemigos derribados![n][w][e]

[msg AST_btl_06_352_01]
[f 2 1][vp 2 0 65535 370 0 0]¡Tres enemigos derribados! ¡Tú puedes![n][w][e]

[msg AST_btl_06_353_01]
[f 2 1][vp 2 0 65535 371 0 0]¡Tres enemigos derribados! ¡Genial, Yukari![n][w][e]

[msg AST_btl_06_354_01]
[f 2 1][vp 2 0 65535 372 0 0]¡Tres menos! ¡Buen trabajo, Junpei![n][w][e]

[msg AST_btl_06_355_01]
[f 2 1][vp 2 0 65535 373 0 0]¡Tres derribos! ¡Muy buena, Sanada![n][w][e]

[msg AST_btl_06_356_01]
[f 2 1][vp 2 0 65535 374 0 0]¡Tres menos! ¡Maravilloso, Kirijo![n][w][e]

[msg AST_btl_06_357_01]
[f 2 1][vp 2 0 65535 375 0 0]¡Aigis ha derribado a tres enemigos![n][w][e]

[msg AST_btl_06_358_01]
[f 2 1][vp 2 0 65535 376 0 0]¡Tres enemigos derribados! ¡Increíble, Amada![n][w][e]

[msg AST_btl_06_359_01]
[f 2 1][vp 2 0 65535 377 0 0]¡Tres enemigos derribados! ¡Buen trabajo, Korocito![n][w][e]

[msg AST_btl_06_360_01]
[f 2 1][vp 2 0 65535 378 0 0]¡Tres menos! ¡Buen trabajo, Aragaki![n][w][e]

[msg AST_btl_06_361_01]
[f 2 1][vp 2 0 65535 379 0 0]¡Tres enemigos derribados![n][w][e]

[msg AST_btl_06_362_01]
[f 2 1][vp 2 0 65535 380 0 0]¡Sí, conseguido! ¡Dos enemigos derribados![n][w][e]

[msg AST_btl_06_363_01]
[f 2 1][vp 2 0 65535 381 0 0]¡Yukari ha derribado a dos enemigos![n][w][e]

[msg AST_btl_06_364_01]
[f 2 1][vp 2 0 65535 382 0 0]¡Dos enemigos derribados por Junpei![n][w][e]

[msg AST_btl_06_365_01]
[f 2 1][vp 2 0 65535 383 0 0]¡Sanada ha derribado a dos con ese ataque![n][w][e]

[msg AST_btl_06_366_01]
[f 2 1][vp 2 0 65535 384 0 0]¡Kirijo ha derribado a dos con ese ataque![n][w][e]

[msg AST_btl_06_367_01]
[f 2 1][vp 2 0 65535 385 0 0]¡Dos enemigos derribados! ¡Bien hecho, Aigis![n][w][e]

[msg AST_btl_06_368_01]
[f 2 1][vp 2 0 65535 386 0 0]¡Dos enemigos derribados! ¡Sigue así, Amada![n][w][e]

[msg AST_btl_06_369_01]
[f 2 1][vp 2 0 65535 387 0 0]¡Korocito ha tumbado a dos enemigos![n][w][e]

[msg AST_btl_06_370_01]
[f 2 1][vp 2 0 65535 388 0 0]¡Aragaki acaba de derribar a dos![n][w][e]

[msg AST_btl_06_371_01]
[f 2 1][vp 2 0 65535 389 0 0]¡Dos enemigos derribados![n][w][e]

[msg AST_btl_06_372_01]
[f 2 1][vp 2 0 65535 390 0 0]¡Enemigo fuera![n][w][e]

[msg AST_btl_06_373_01]
[f 2 1][vp 2 0 65535 391 0 0]¡Yukari ha derribado a uno![n][w][e]

[msg AST_btl_06_374_01]
[f 2 1][vp 2 0 65535 392 0 0]¡Gran derribo de Junpei![n][w][e]

[msg AST_btl_06_375_01]
[f 2 1][vp 2 0 65535 393 0 0]¡Sanada ha derribado a un enemigo![n][w][e]

[msg AST_btl_06_376_01]
[f 2 1][vp 2 0 65535 394 0 0]¡Kirijo ha derribado a un enemigo![n][w][e]

[msg AST_btl_06_377_01]
[f 2 1][vp 2 0 65535 395 0 0]¡Enemigo derribado por Aigis![n][w][e]

[msg AST_btl_06_378_01]
[f 2 1][vp 2 0 65535 396 0 0]¡Enemigo derribado por Amada![n][w][e]

[msg AST_btl_06_379_01]
[f 2 1][vp 2 0 65535 397 0 0]¡Korocito ha derribado a uno![n][w][e]

[msg AST_btl_06_380_01]
[f 2 1][vp 2 0 65535 398 0 0]¡Aragaki ha derribado al enemigo![n][w][e]

[msg AST_btl_06_381_01]
[f 2 1][vp 2 0 65535 399 0 0]¡Eso es! ¡Enemigo derribado![n][w][e]

[msg AST_btl_06_382_01]
[f 2 1][vp 2 0 65535 400 0 0]¡Le habéis dado en el punto débil![n][w][e]

[msg AST_btl_06_383_01]
[f 2 1][vp 2 0 65535 401 0 0]¡Una debilidad! ¡Buena, Yukari![n][w][e]

[msg AST_btl_06_384_01]
[f 2 1][vp 2 0 65535 402 0 0]¡Le has dado en una debilidad! ¡Bien, Junpei![n][w][e]

[msg AST_btl_06_385_01]
[f 2 1][vp 2 0 65535 403 0 0]¡Le has dado en el punto débil! ¡Qué buena, Sanada![n][w][e]

[msg AST_btl_06_386_01]
[f 2 1][vp 2 0 65535 404 0 0]¡Has dado en una debilidad! ¡Buen trabajo como siempre, Kirijo![n][w][e]

[msg AST_btl_06_387_01]
[f 2 1][vp 2 0 65535 405 0 0]¡Impacto directo en una debilidad! ¡Increíble, Aigis![n][w][e]

[msg AST_btl_06_388_01]
[f 2 1][vp 2 0 65535 406 0 0]¡Ese es su punto débil! ¡Sigue así, Amada![n][w][e]

[msg AST_btl_06_389_01]
[f 2 1][vp 2 0 65535 407 0 0]¡Eso es un punto débil! ¡Eres el mejor, Korocito![n][w][e]

[msg AST_btl_06_390_01]
[f 2 1][vp 2 0 65535 408 0 0]¡Le has dado en su punto débil! ¡Bien hecho, Aragaki![n][w][e]

[msg AST_btl_06_391_01]
[f 2 1][vp 2 0 65535 409 0 0]¡Le has dado en el punto débil![n][w][e]

[msg AST_btl_06_392_01]
[f 2 1][vp 2 0 65535 410 0 0]¡Un golpe limpio![n][w][e]

[msg AST_btl_06_393_01]
[f 2 1][vp 2 0 65535 411 0 0]Yukari, ¡ha sido una pasada![n][w][e]

[msg AST_btl_06_394_01]
[f 2 1][vp 2 0 65535 412 0 0]¡Menudo golpe, Junpei![n][w][e]

[msg AST_btl_06_395_01]
[f 2 1][vp 2 0 65535 413 0 0]¡Sanada le ha dado una buena![n][w][e]

[msg AST_btl_06_396_01]
[f 2 1][vp 2 0 65535 414 0 0]¡Ha sido un golpe maravilloso, Kirijo![n][w][e]

[msg AST_btl_06_397_01]
[f 2 1][vp 2 0 65535 415 0 0]¡Muy buena, Aigis! ¡En sus puntos débiles![n][w][e]

[msg AST_btl_06_398_01]
[f 2 1][vp 2 0 65535 416 0 0]¡Magnífico, Amada! ¡Has dado justo en el blanco![n][w][e]

[msg AST_btl_06_399_01]
[f 2 1][vp 2 0 65535 417 0 0]¡Fenomenal, Korocito! ¡Ha sido crítico![n][w][e]

[msg AST_btl_06_400_01]
[f 2 1][vp 2 0 65535 418 0 0]¡Aragaki ha dado un golpe devastador![n][w][e]

[msg AST_btl_06_401_01]
[f 2 1][vp 2 0 65535 419 0 0]¡Un golpe crítico![n][w][e]

[msg AST_btl_06_402_01]
[f 2 1][vp 2 0 65535 420 0 0]¡Vaya, has fallado![n][w][e]

[msg AST_btl_06_403_01]
[f 2 1][vp 2 0 65535 421 0 0]Ah, ¡por qué poco! ¡Ya le darás la próxima vez, Yukari![n][w][e]

[msg AST_btl_06_404_01]
[f 2 1][vp 2 0 65535 422 0 0]Junpei... Mmm, la próxima vez será.[n][w][e]

[msg AST_btl_06_405_01]
[f 2 1][vp 2 0 65535 423 0 0]¡Ah! ¡Concéntrate, Sanada![n][w][e]

[msg AST_btl_06_406_01]
[f 2 1][vp 2 0 65535 424 0 0]¡Ah! ¡No dejes que te afecte, Kirijo![n][w][e]

[msg AST_btl_06_407_01]
[f 2 1][vp 2 0 65535 425 0 0]El enemigo ha esquivado... Aigis, ¡ajusta la precisión![n][w][e]

[msg AST_btl_06_408_01]
[f 2 1][vp 2 0 65535 426 0 0]¡Por qué poco, Amada! ¡Céntrate![n][w][e]

[msg AST_btl_06_409_01]
[f 2 1][vp 2 0 65535 427 0 0]Korocito, ¡observa con detenimiento al enemigo![n][w][e]

[msg AST_btl_06_410_01]
[f 2 1][vp 2 0 65535 428 0 0]Has fallado... No pasa nada, ¡tú puedes, Aragaki![n][w][e]

[msg AST_btl_06_411_01]
[f 2 1][vp 2 0 65535 429 0 0]Ah, por qué poco... ¡La próxima vez será![n][w][e]

[msg AST_btl_06_412_01]
[f 2 1][vp 2 0 65535 430 0 0]Yukari, ¡no te vayas![n][w][e]

[msg AST_btl_06_413_01]
[f 2 1][vp 2 0 65535 431 0 0]¡Espera, Junpei! ¡¿Qué haces?![n][w][e]

[msg AST_btl_06_414_01]
[f 2 1][vp 2 0 65535 432 0 0]¿Eh? Sanada, ¿adónde vas?[n][w][e]

[msg AST_btl_06_415_01]
[f 2 1][vp 2 0 65535 433 0 0]¡Ah! Kirijo, ¡no huyas![n][w][e]

[msg AST_btl_06_416_01]
[f 2 1][vp 2 0 65535 434 0 0]Aigis, ¡no huyas![n][w][e]

[msg AST_btl_06_417_01]
[f 2 1][vp 2 0 65535 435 0 0]¡Amada! ¡Espera, no huyas![n][w][e]

[msg AST_btl_06_418_01]
[f 2 1][vp 2 0 65535 436 0 0]¡Ah! ¡Korocito, chico malo! ¡Vuelve aquí![n][w][e]

[msg AST_btl_06_419_01]
[f 2 1][vp 2 0 65535 437 0 0]¡Aragaki, vuelve![n][w][e]

[msg AST_btl_06_420_01]
[f 2 1][vp 2 0 65535 438 0 0]Espera, ¡no huyas![n][w][e]

[msg AST_btl_06_421_01]
[f 2 1][vp 2 0 65535 439 0 0]¡La líder está a tope![n][w][e]

[msg AST_btl_06_422_01]
[f 2 1][vp 2 0 65535 440 0 0]Parece que Yukari se está concentrando...[n][w][e]

[msg AST_btl_06_423_01]
[f 2 1][vp 2 0 65535 441 0 0]¡Junpei está a tope![n][w][e]

[msg AST_btl_06_424_01]
[f 2 1][vp 2 0 65535 442 0 0]Sanada está muy motivado.[n][w][e]

[msg AST_btl_06_425_01]
[f 2 1][vp 2 0 65535 443 0 0]Kirijo parece muy centrada...[n][w][e]

[msg AST_btl_06_426_01]
[f 2 1][vp 2 0 65535 444 0 0]¡La energía de Aigis se sale del medidor![n][w][e]

[msg AST_btl_06_427_01]
[f 2 1][vp 2 0 65535 445 0 0]Parece que Amada no tiene dudas.[n][w][e]

[msg AST_btl_06_428_01]
[f 2 1][vp 2 0 65535 446 0 0]¡Korocito está de buen humor![n][w][e]

[msg AST_btl_06_429_01]
[f 2 1][vp 2 0 65535 447 0 0]Vaya, Aragaki está superconcentrado...[n][w][e]

[msg AST_btl_06_430_01]
[f 2 1][vp 2 0 65535 448 0 0]¡Estoy al tanto de tu salud! ¡Vas genial![n][w][e]

[msg AST_btl_06_431_01]
[f 2 1][vp 2 0 65535 449 0 0]¡Hala...! ¡Cuantísimo poder tenéis![n][w][e]

[msg AST_btl_06_431_02]
[f 2 1][vp 2 0 65535 450 0 0]¡Seguid así, equipo![n][w][e]

[msg AST_btl_06_431_03]
[f 2 1][vp 2 0 65535 451 0 0]Podéis parar si la cosa se pone fea...[n][w][e]

[msg AST_btl_06_432_01]
[f 2 1][vp 2 0 65535 452 0 0]¡Sí! ¡Es hora de hacer un ataque combinado![n][w][e]

[msg AST_btl_06_432_02]
[f 2 1][vp 2 0 65535 453 0 0]¡Estupendo! ¡Toca hacer un ataque combinado![n][w][e]

[msg AST_btl_06_432_03]
[f 2 1][vp 2 0 65535 454 0 0]¡Habéis roto la defensa del enemigo! ¡Es vuestra oportunidad![n][w][e]

[msg AST_btl_06_433_01]
[f 2 1][vp 2 0 65535 455 0 0]¡Vamos a por todas! ¡Vosotros podéis![n][w][e]

[msg AST_btl_06_433_02]
[f 2 1][vp 2 0 65535 456 0 0]¡Ahora! ¡Ni un paso atrás![n][w][e]

[msg AST_btl_06_433_03]
[f 2 1][vp 2 0 65535 457 0 0]¡Terminemos con esto![n][w][e]

[msg AST_btl_06_433_04]
[f 2 1][vp 2 0 65535 458 0 0]¡La victoria será nuestra![n][w][e]

[msg AST_btl_06_433_05]
[f 2 1][vp 2 0 65535 459 0 0]¡Que nada os pare![n][w][e]

[msg AST_btl_06_434_01]
[f 2 1][vp 2 0 65535 460 0 0]Entendido. Buscaré una vía de escape en la línea enemiga...[n][w][e]

[msg AST_btl_06_435_01]
[f 2 1][vp 2 0 65535 461 0 0]Tiene mala pinta... No parece que podamos salir de esta.[n][w][e]

[msg AST_btl_06_436_01]
[f 2 1][vp 2 0 65535 462 0 0]Lo siento, aún estoy buscando una vía de escape. Aguanta un poco más.[n][w][e]

[msg AST_btl_06_437_01]
[f 2 1][vp 2 0 65535 463 0 0]¡Ahora! ¡Ya deberías poder salir![n][w][e]

[msg AST_btl_06_438_01]
[f 2 1][vp 2 0 65535 464 0 0]Oh, no... No he encontrado ninguna salida.[n][w][e]

[msg AST_btl_06_439_01]
[f 2 1][vp 2 0 65535 465 0 0]¡Puedes atacar una debilidad con esto![n][w][e]

[msg AST_btl_06_439_02]
[f 2 1][vp 2 0 65535 466 0 0]¡Tienes una habilidad que puede atacar una debilidad![n][w][e]

[msg AST_btl_06_439_03]
[f 2 1][vp 2 0 65535 467 0 0]¡Parece que puedes atacar una debilidad![n][w][e]

[msg AST_btl_06_440_01]
[f 2 1][vp 2 0 65535 468 0 0]No parece que tengas las habilidades adecuadas...[n][w][e]

[msg AST_btl_06_440_02]
[f 2 1][vp 2 0 65535 469 0 0]Parece que no puedes atacar ninguna debilidad.[n][w][e]

[msg AST_btl_06_440_03]
[f 2 1][vp 2 0 65535 470 0 0]Creo que no tienes ninguna habilidad que funcione bien ahora.[n][w][e]

[msg AST_btl_06_441_01]
[f 2 1][vp 2 0 65535 471 0 0]¡Podrías atacar una debilidad si cambias![n][w][e]

[msg AST_btl_06_441_02]
[f 2 1][vp 2 0 65535 472 0 0]¡Alguien más podría atacar una debilidad del enemigo![n][w][e]

[msg AST_btl_06_441_03]
[f 2 1][vp 2 0 65535 473 0 0]¡Cambia para atacar la debilidad del enemigo![n][w][e]

[msg AST_btl_06_442_01]
[f 2 1][vp 2 0 65535 474 0 0]¡Tienes un ataque que funciona bien![n][w][e]

[msg AST_btl_06_442_02]
[f 2 1][vp 2 0 65535 475 0 0]Con esto infligirás mucho daño.[n][w][e]

[msg AST_btl_06_442_03]
[f 2 1][vp 2 0 65535 476 0 0]Parece que puedes infligir un daño eficaz.[n][w][e]

[msg AST_btl_06_443_01]
[f 2 1][vp 2 0 65535 477 0 0]¡Puedes usar tu arma para atacar la debilidad del enemigo![n][w][e]

[msg AST_btl_06_443_02]
[f 2 1][vp 2 0 65535 478 0 0]¡Estás de suerte! ¡El enemigo es débil a tu ataque básico![n][w][e]

[msg AST_btl_06_443_03]
[f 2 1][vp 2 0 65535 479 0 0]¡Parece que el enemigo es débil a tu arma![n][w][e]

[msg AST_btl_06_444_01]
[f 2 1][vp 2 0 65535 480 0 0]¡El ataque de tu arma debería ser eficaz![n][w][e]

[msg AST_btl_06_444_02]
[f 2 1][vp 2 0 65535 481 0 0]Puedes infligir bastante daño con los ataques de tu arma.[n][w][e]

[msg AST_btl_06_444_03]
[f 2 1][vp 2 0 65535 482 0 0]Los ataques de tu arma parecen ser eficaces.[n][w][e]

[msg AST_btl_06_445_01]
[f 2 1][vp 2 0 65535 483 0 0]Tienes cosas que funcionan, pero quizá haya otras debilidades que puedas aprovechar.[n][w][e]

[msg AST_btl_06_445_02]
[f 2 1][vp 2 0 65535 484 0 0]Cuentas con un ataque efectivo, pero parece que hay otras debilidades.[n][w][e]

[msg AST_btl_06_446_01]
[f 2 1][vp 2 0 65535 485 0 0]No he visto ninguna debilidad. Tendrás que usar la técnica de ensayo y error.[n][w][e]

[msg AST_btl_06_446_02]
[f 2 1][vp 2 0 65535 486 0 0]Aún no conocemos ninguna debilidad... ¿Puedes comprobar qué funciona?[n][w][e]

[msg AST_btl_06_447_01]
[f 2 1][vp 2 0 65535 487 0 0]¡Utiliza un objeto para darles en su punto débil![n][w][e]

[msg AST_btl_06_447_02]
[f 2 1][vp 2 0 65535 488 0 0]¡Los objetos pueden ser una buena forma de atacar debilidades![n][w][e]

[msg AST_btl_06_447_03]
[f 2 1][vp 2 0 65535 489 0 0]Ah, ¡creo que tienes un objeto con el que puedes atacar la debilidad del enemigo![n][w][e]

[msg AST_btl_06_448_01]
[f 2 1][vp 2 0 65535 490 0 0]¡Todos los enemigos derrotados! ¡Buen trabajo![n][w][e]

[msg AST_btl_06_448_02]
[f 2 1][vp 2 0 65535 491 0 0]¡Ya está! No se han detectado sombras.[n][w][e]

[msg AST_btl_06_448_03]
[f 2 1][vp 2 0 65535 492 0 0]¡Es una victoria para el equipo! ¡Buen trabajo![n][w][e]

[msg AST_btl_06_449_01]
[f 2 1][vp 2 0 65535 493 0 0]El enemigo ha escapado. Se acabó el combate.[n][w][e]

[msg AST_btl_06_450_01]
[f 2 1][vp 2 0 65535 494 0 0]¡Hora de cambiar! ¡Tú puedes![n][w][e]

[msg AST_btl_06_450_02]
[f 2 1][vp 2 0 65535 495 0 0]¡Cambio![n][w][e]

[msg AST_btl_06_451_01]
[f 2 1][vp 2 0 65535 496 0 0]¡Te toca! ¡A por todas![n][w][e]

[msg AST_btl_06_451_02]
[f 2 1][vp 2 0 65535 497 0 0]¡Otro cambio![n][w][e]

[msg AST_btl_06_452_01]
[f 2 1][vp 2 0 65535 498 0 0]¡Ese es el tercer cambio! Qué buena sincronización.[n][w][e]

[msg AST_btl_06_452_02]
[f 2 1][vp 2 0 65535 499 0 0]Ese es el equipo al completo. ¡Muy buena coordinación![n][w][e]

[msg AST_btl_06_453_01]
[f 2 1][vp 2 0 65535 500 0 0]Tienes que elegir a otro compañero.[n][w][e]

[msg AST_btl_06_453_02]
[f 2 1][vp 2 0 65535 501 0 0]Vosotros dos ya os habéis cambiado.[n][w][e]

[msg AST_btl_06_454_01]
[f 2 1][vp 2 0 65535 502 0 0]Ese es fuerte... ¡No bajes la guardia![n][w][e]

[msg AST_btl_06_455_01]
[f 2 1][vp 2 0 65535 503 0 0]No hay nada que temer. Acabemos rápido.[n][w][e]

[msg AST_btl_06_456_01]
[f 2 1][vp 2 0 65535 504 0 0]Esta debería ser una buena prueba de tu fuerza... ¡Pero no te descuides![n][w][e]

[msg AST_btl_06_457_01]
[f 2 1][vp 2 0 65535 505 0 0]¡Es débil a los ataques cortantes! ¡Tu arma infligirá mucho daño![n][w][e]

[msg AST_btl_06_458_01]
[f 2 1][vp 2 0 65535 506 0 0]¡Los ataques contundentes son su debilidad! ¡Puños a pares![n][w][e]

[msg AST_btl_06_459_01]
[f 2 1][vp 2 0 65535 507 0 0]Es débil a la perforación. ¡Prueba con flechas o balas![n][w][e]

[msg AST_btl_06_460_01]
[f 2 1][vp 2 0 65535 508 0 0]¡Parece que el fuego es efectivo![n][w][e]

[msg AST_btl_06_461_01]
[f 2 1][vp 2 0 65535 509 0 0]¡El enemigo es débil al hielo! ¡Hagamos un polo con él![n][w][e]

[msg AST_btl_06_462_01]
[f 2 1][vp 2 0 65535 510 0 0]¡Hay que usar viento![n][w][e]

[msg AST_btl_06_463_01]
[f 2 1][vp 2 0 65535 511 0 0]¡Prueba con una descarga eléctrica![n][w][e]

[msg AST_btl_06_464_01]
[f 2 1][vp 2 0 65535 512 0 0]¡Parece que el enemigo es débil a la luz![n][w][e]

[msg AST_btl_06_465_01]
[f 2 1][vp 2 0 65535 513 0 0]Aquí parece ser efectiva la oscuridad.[n][w][e]

[msg AST_btl_06_466_01]
[f 2 1][vp 2 0 65535 514 0 0]Cortar no va funcionar. Ni te molestes en usar tu arma.[n][w][e]

[msg AST_btl_06_467_01]
[f 2 1][vp 2 0 65535 515 0 0]Los ataques contundentes no sirven de nada. Mucho cuidado.[n][w][e]

[msg AST_btl_06_468_01]
[f 2 1][vp 2 0 65535 516 0 0]Al enemigo no se le puede perforar.[n][w][e]

[msg AST_btl_06_469_01]
[f 2 1][vp 2 0 65535 517 0 0]¡El fuego no funcionará![n]¡Tened cuidado![n][w][e]

[msg AST_btl_06_470_01]
[f 2 1][vp 2 0 65535 518 0 0]Parece que el hielo no tiene ningún efecto.[n][w][e]

[msg AST_btl_06_471_01]
[f 2 1][vp 2 0 65535 519 0 0]El viento no funciona con este. ¡Tendrás que probar otra cosa![n][w][e]

[msg AST_btl_06_472_01]
[f 2 1][vp 2 0 65535 520 0 0]Aquí la electricidad no sirve... ¡Tenlo presente![n][w][e]

[msg AST_btl_06_473_01]
[f 2 1][vp 2 0 65535 521 0 0]Parece que la luz no es eficaz.[n][w][e]

[msg AST_btl_06_474_01]
[f 2 1][vp 2 0 65535 522 0 0]La oscuridad no afecta a este enemigo.[n][w][e]

[msg AST_btl_06_475_01]
[f 2 1][vp 2 0 65535 523 0 0]¡Al enemigo se le manipula con facilidad! ¿Alguna habilidad para conseguirlo?[n][w][e]

[msg AST_btl_06_476_01]
[f 2 1][vp 2 0 65535 524 0 0]Es vulnerable al veneno. ¡Intenta aprovecharlo![n][w][e]

[msg AST_btl_06_477_01]
[f 2 1][vp 2 0 65535 525 0 0]¡Puede que el enemigo se angustie con facilidad![n][w][e]

[msg AST_btl_06_478_01]
[f 2 1][vp 2 0 65535 526 0 0]Quizá puedas infligir Confusión... ¿Quieres intentarlo?[n][w][e]

[msg AST_btl_06_479_01]
[f 2 1][vp 2 0 65535 527 0 0]Este enemigo parece asustadizo. ¿Podrías darle un susto?[n][w][e]

[msg AST_btl_06_480_01]
[f 2 1][vp 2 0 65535 528 0 0]Parece que este tiene mal carácter. Podrías cabrearlo...[n][w][e]

[msg AST_btl_06_481_01]
[f 2 1][vp 2 0 65535 529 0 0]¡Allá voy![n][w][e]

[msg AST_btl_06_481_02]
[f 2 1][vp 2 0 65535 530 0 0]¡Esto será de ayuda![n][w][e]

[msg AST_btl_06_481_03]
[f 2 1][vp 2 0 65535 531 0 0]Por favor, ¡protégelos![n][w][e]

[msg AST_btl_06_482_01]
[f 2 1][vp 2 0 65535 532 0 0]¡Ven a mí, Juno![n][w][e]

[msg AST_btl_06_482_02]
[f 2 1][vp 2 0 65535 533 0 0]¡Escúdalos![n][w][e]

[msg AST_btl_06_482_03]
[f 2 1][vp 2 0 65535 534 0 0]¡Se acabó![n][w][e]

[msg AST_btl_06_483_01]
[f 2 1][vp 2 0 65535 535 0 0]Hay que ganar.[n][w][e]

[msg AST_btl_06_483_02]
[f 2 1][vp 2 0 65535 536 0 0]¡Ven a mí, Lucía![n][w][e]

[msg AST_btl_06_483_03]
[f 2 1][vp 2 0 65535 537 0 0]¡Ten...![n][w][e]

[msg AST_btl_06_484_01]
[f 2 1][vp 2 0 65535 538 0 0]¡Los protegeré![n][w][e]

[msg AST_btl_06_484_02]
[f 2 1][vp 2 0 65535 539 0 0]¡Guíalos hacia la victoria![n][w][e]

[msg AST_btl_06_484_03]
[f 2 1][vp 2 0 65535 540 0 0]¡Oráculo...![n][w][e]

[msg AST_btl_06_485_01]
[f 2 1][vp 2 0 65535 541 0 0]Tengo que hacer mi parte.[n][w][e]

[msg AST_btl_06_485_02]
[f 2 1][vp 2 0 65535 542 0 0]Necesito concentrarme.[n][w][e]

[msg AST_btl_06_485_03]
[f 2 1][vp 2 0 65535 543 0 0]Mi teúrgia necesita un poco más de tiempo.[n][w][e]

[msg AST_btl_06_486_01]
[f 2 1][vp 2 0 65535 544 0 0]¿Ya casi estás, Lucía?[n][w][e]

[msg AST_btl_06_486_02]
[f 2 1][vp 2 0 65535 545 0 0]Ya casi es la hora, Juno.[n][w][e]

[msg AST_btl_06_486_03]
[f 2 1][vp 2 0 65535 546 0 0]Sí... Mi teúrgia pronto estará lista.[n][w][e]

[msg AST_btl_06_487_01]
[f 2 1][vp 2 0 65535 547 0 0]Empezaré con el análisis...[n][w][e]

[msg AST_btl_06_487_02]
[f 2 1][vp 2 0 65535 548 0 0]¡Pronto podré escanear al enemigo![n][w][e]

[msg AST_btl_06_487_03]
[f 2 1][vp 2 0 65535 549 0 0]¡Preparándome para analizar![n][w][e]

[msg AST_btl_06_488_01]
[f 2 1][vp 2 0 65535 550 0 0]Estoy preparándolo todo.[n]Voy a tardar un ratito.[n][w][e]

[msg AST_btl_06_489_01]
[f 2 1][vp 2 0 65535 551 0 0]¿Qué...? ¿No puedo escanear?[n][w][e]

[msg AST_btl_06_490_01]
[f 2 1][vp 2 0 65535 552 0 0]¡Preparativos completados![n][w][e]

[msg AST_btl_06_490_02]
[f 2 1][vp 2 0 65535 553 0 0]¡Todo preparado para escanear! ¿Empiezo ya?[n][w][e]

[msg AST_btl_06_490_03]
[f 2 1][vp 2 0 65535 554 0 0]¡Ya puedo analizar! ¡Solo tienes que pedirlo![n][w][e]

[msg AST_btl_06_491_01]
[f 2 1][vp 2 0 65535 555 0 0]¿Escaneo a este enemigo?[n][w][e]

[msg AST_btl_06_492_01]
[f 2 1][vp 2 0 65535 556 0 0]¡Análisis completado![n][w][e]

[msg AST_btl_06_492_02]
[f 2 1][vp 2 0 65535 557 0 0]Esto es lo que he encontrado...[n][w][e]

[msg AST_btl_06_492_03]
[f 2 1][vp 2 0 65535 558 0 0]Conque a esto es a lo que nos enfrentamos...[n][w][e]

[msg AST_btl_06_493_01]
[f 2 1][vp 2 0 65535 559 0 0]Ya la he escaneado.[n][w][e]

[msg AST_btl_06_494_01]
[f 2 1][vp 2 0 65535 560 0 0]Lo siento, ahora mismo no puedo escanear.[n][w][e]

[msg AST_btl_06_495_01]
[f 2 1][vp 2 0 65535 561 0 0]¡He conseguido un nuevo poder![n][w][e]

[msg AST_btl_06_495_02]
[f 2 1][vp 2 0 65535 562 0 0]¡Ahora podré daros incluso más apoyo![n][w][e]

[msg AST_btl_06_496_01]
[f 2 1][vp 2 0 65535 563 0 0]El enemigo sufre un estado alterado. ¡Es nuestra oportunidad![n][w][e]

[msg AST_btl_06_496_02]
[f 2 1][vp 2 0 65535 564 0 0]El enemigo está sufriendo un poco. ¡Tenemos la ventaja![n][w][e]

[msg AST_btl_06_496_03]
[f 2 1][vp 2 0 65535 565 0 0]¡Enemigo debilitado! ¡Vamos a acabar con esto![n][w][e]

[msg AST_btl_06_499_01]
[f 2 1][vp 2 0 65535 566 0 0]未使用[n][w][e]

[msg AST_btl_06_500_01]
[f 2 1][vp 2 0 65535 567 0 0]未使用[n][w][e]

[msg AST_btl_06_501_01]
[f 2 1][vp 2 0 65535 568 0 0]未使用[n][w][e]

[msg AST_btl_06_502_01]
[f 2 1][vp 2 0 65535 569 0 0]未使用[n][w][e]

[msg AST_btl_06_503_01]
[f 2 1][vp 2 0 65535 570 0 0]未使用[n][w][e]

[msg AST_btl_06_504_01]
[f 2 1][vp 2 0 65535 571 0 0]未使用[n][w][e]

[msg AST_btl_06_505_01]
[f 2 1][vp 2 0 65535 572 0 0]未使用[n][w][e]

[msg AST_btl_06_506_01]
[f 2 1][vp 2 0 65535 573 0 0]未使用[n][w][e]

[msg AST_btl_06_507_01]
[f 2 1][vp 2 0 65535 574 0 0]未使用[n][w][e]

[msg AST_btl_06_508_01]
[f 2 1][vp 2 0 65535 575 0 0]未使用[n][w][e]

[msg AST_btl_06_509_01]
[f 2 1][vp 2 0 65535 576 0 0]未使用[n][w][e]

[msg AST_btl_06_510_01]
[f 2 1][vp 2 0 65535 577 0 0]未使用[n][w][e]

[msg AST_btl_06_511_01]
[f 2 1][vp 2 0 65535 578 0 0]未使用[n][w][e]

[msg AST_btl_06_512_01]
[f 2 1][vp 2 0 65535 579 0 0]未使用[n][w][e]

[msg AST_btl_06_513_01]
[f 2 1][vp 2 0 65535 580 0 0]未使用[n][w][e]

[msg AST_btl_06_514_01]
[f 2 1][vp 2 0 65535 581 0 0]未使用[n][w][e]

[msg AST_btl_06_515_01]
[f 2 1][vp 2 0 65535 582 0 0]未使用[n][w][e]

[msg AST_btl_06_516_01]
[f 2 1][vp 2 0 65535 583 0 0]未使用[n][w][e]

[msg AST_btl_06_517_01]
[f 2 1][vp 2 0 65535 584 0 0]未使用[n][w][e]

[msg AST_btl_06_518_01]
[f 2 1][vp 2 0 65535 585 0 0]未使用[n][w][e]

[msg AST_btl_06_519_01]
[f 2 1][vp 2 0 65535 586 0 0]未使用[n][w][e]

[msg AST_btl_06_520_01]
[f 2 1][vp 2 0 65535 587 0 0]未使用[n][w][e]

[msg AST_btl_06_521_01]
[f 2 1][vp 2 0 65535 588 0 0]未使用[n][w][e]

[msg AST_btl_06_522_01]
[f 2 1][vp 2 0 65535 589 0 0]未使用[n][w][e]

[msg AST_btl_06_523_01]
[f 2 1][vp 2 0 65535 590 0 0]未使用[n][w][e]

[msg AST_btl_06_524_01]
[f 2 1][vp 2 0 65535 591 0 0]未使用[n][w][e]

[msg AST_btl_06_525_01]
[f 2 1][vp 2 0 65535 592 0 0]未使用[n][w][e]

[msg AST_btl_06_526_01]
[f 2 1][vp 2 0 65535 593 0 0]未使用[n][w][e]

[msg AST_btl_06_527_01]
[f 2 1][vp 2 0 65535 594 0 0]未使用[n][w][e]

[msg AST_btl_06_528_01]
[f 2 1][vp 2 0 65535 595 0 0]未使用[n][w][e]

[msg AST_btl_06_529_01]
[f 2 1][vp 2 0 65535 596 0 0]Por favor, ¡dame algo de tiempo![n][w][e]

[msg AST_btl_06_530_01]
[f 2 1][vp 2 0 65535 597 0 0]¡Puedo iniciar el análisis en cualquier momento![n][w][e]

[msg AST_btl_06_531_01]
[f 2 1][vp 2 0 65535 598 0 0]¡Esta es la debilidad del monstruo![n][w][e]

[msg AST_btl_06_532_01]
[f 2 1][vp 2 0 65535 599 0 0]¿E-eh? Me siento débil.[n][w][e]

[msg AST_btl_06_533_01]
[f 2 1][vp 2 0 65535 600 0 0]¡El aura del enemigo ha cambiado![n][w][e]

[msg AST_btl_06_534_01]
[f 2 1][vp 2 0 65535 601 0 0]¡Ahora puedo ver la debilidad del enemigo![n][w][e]

[msg AST_btl_06_535_01]
[f 2 1][vp 2 0 65535 602 0 0]未使用[n][w][e]

[msg AST_btl_06_536_01]
[f 2 1][vp 2 0 65535 603 0 0]未使用[n][w][e]

[msg AST_btl_06_537_01]
[f 2 1][vp 2 0 65535 604 0 0]未使用[n][w][e]

[msg AST_btl_06_538_01]
[f 2 1][vp 2 0 65535 605 0 0]¡Esta gran sombra es del arcano del Hierofante![n][w][e]

[msg AST_btl_06_539_01]
[f 2 1][vp 2 0 65535 606 0 0]No sabemos qué hará. ¡Hay que prepararse para lo que sea![n][w][e]

[msg AST_btl_06_540_01]
[f 2 1][vp 2 0 65535 607 0 0]未使用[n][w][e]

[msg AST_btl_06_541_01]
[f 2 1][vp 2 0 65535 608 0 0]未使用[n][w][e]

[msg AST_btl_06_542_01]
[f 2 1][vp 2 0 65535 609 0 0]未使用[n][w][e]

[msg AST_btl_06_543_01]
[f 2 1][vp 2 0 65535 610 0 0]Esta es del arcano de los Amantes. ¡Es la fuente de la manipulación mental![n][w][e]

[msg AST_btl_06_544_01]
[f 2 1][vp 2 0 65535 611 0 0]¡¿Yukari...?![n][w][e]

[msg AST_btl_06_545_01]
[f 2 1][vp 2 0 65535 612 0 0]未使用[n][w][e]

[msg AST_btl_06_546_01]
[f 2 1][vp 2 0 65535 613 0 0]未使用[n][w][e]

[msg AST_btl_06_547_01]
[f 2 1][vp 2 0 65535 614 0 0]未使用[n][w][e]

[msg AST_btl_06_548_01]
[f 2 1][vp 2 0 65535 615 0 0]¡Imposible! ¡¿Se ha dividido en dos?![n][w][e]

[msg AST_btl_06_549_01]
[f 2 1][vp 2 0 65535 616 0 0]¡¿Qué...?! ¡¿Ha revivido?![n][w][e]

[msg AST_btl_06_550_01]
[f 2 1][vp 2 0 65535 617 0 0]¡Se han vuelto a separar! Nuestro daño está dividido a partes iguales entre ellos.[n][w][e]

[msg AST_btl_06_551_01]
[f 2 1][vp 2 0 65535 618 0 0]Aigis...[n][w][e]

[msg AST_btl_06_552_01]
[f 2 1][vp 2 0 65535 619 0 0]未使用[n][w][e]

[msg AST_btl_06_553_01]
[f 2 1][vp 2 0 65535 620 0 0]Esta gran sombra es del arcano del Ermitaño. ¡Cuidado con los ataques que usan electricidad![n][w][e]

[msg AST_btl_06_554_01]
[f 2 1][vp 2 0 65535 621 0 0]¡La sombra enemiga está cargándose![n][w][e]

[msg AST_btl_06_555_01]
[f 2 1][vp 2 0 65535 622 0 0]¡Hemos hecho que el enemigo deje de aumentar su poder![n][w][e]

[msg AST_btl_06_556_01]
[f 2 1][vp 2 0 65535 623 0 0]未使用[n][w][e]

[msg AST_btl_06_557_01]
[f 2 1][vp 2 0 65535 624 0 0]未使用[n][w][e]

[msg AST_btl_06_558_01]
[f 2 1][vp 2 0 65535 625 0 0]¡¿Q-qué es esto?! ¡¿Una ruleta?![n][w][e]

[msg AST_btl_06_559_01]
[f 2 1][vp 2 0 65535 626 0 0]Parece que el arcano de la Fuerza confía en su poder. ¡Que no te engañe su aspecto![n][w][e]

[msg AST_btl_06_560_01]
[f 2 1][vp 2 0 65535 627 0 0]El arcano de la Fuerza posee una gran fortaleza.[n][w][e]

[msg AST_btl_06_561_01]
[f 2 1][vp 2 0 65535 628 0 0]Este tablero de ruleta me da muy mala espina.[n][w][e]

[msg AST_btl_06_562_01]
[f 2 1][vp 2 0 65535 629 0 0]未使用[n][w][e]

[msg AST_btl_06_563_01]
[f 2 1][vp 2 0 65535 630 0 0]未使用[n][w][e]

[msg AST_btl_06_564_01]
[f 2 1][vp 2 0 65535 631 0 0]未使用[n][w][e]

[msg AST_btl_06_565_01]
[f 2 1][vp 2 0 65535 632 0 0]未使用[n][w][e]

[msg AST_btl_06_566_01]
[f 2 1][vp 2 0 65535 633 0 0]¡La sombra vuelve a estar suspendida en el aire! ¡Ya no podéis atacar![n][w][e]

[msg AST_btl_06_567_01]
[f 2 1][vp 2 0 65535 634 0 0]未使用[n][w][e]

[msg AST_btl_06_568_01]
[f 2 1][vp 2 0 65535 635 0 0]未使用[n][w][e]

[msg AST_btl_06_569_01]
[f 2 1][vp 2 0 65535 636 0 0]未使用[n][w][e]

[msg AST_btl_06_570_01]
[f 2 1][vp 2 0 65535 637 0 0]未使用[n][w][e]

[msg AST_btl_06_571_01]
[f 2 1][vp 2 0 65535 638 0 0]未使用[n][w][e]

[msg AST_btl_06_572_01]
[f 2 1][vp 2 0 65535 639 0 0]未使用[n][w][e]

[msg AST_btl_06_573_01]
[f 2 1][vp 2 0 65535 640 0 0]No importa cuántas veces cambie de arcano... ¡Lo escanearé igual![n][w][e]

[msg AST_btl_06_574_01]
[f 2 1][vp 2 0 65535 641 0 0]Quiero proteger este mundo y a todos los que están en él... ¡Sé que puedo hacerlo![n][w][e]

[msg AST_btl_06_575_01]
[f 2 1][vp 2 0 65535 642 0 0]¡Nix ha cambiado al Hierofante![n][w][e]

[msg AST_btl_06_576_01]
[f 2 1][vp 2 0 65535 643 0 0]¡Nix ha cambiado al tipo Amantes![n][w][e]

[msg AST_btl_06_577_01]
[f 2 1][vp 2 0 65535 644 0 0]¡Ahora Nix ha cambiado al Carro![n][w][e]

[msg AST_btl_06_578_01]
[f 2 1][vp 2 0 65535 645 0 0]¡Nix ha cambiado al arcano de la Justicia![n][w][e]

[msg AST_btl_06_579_01]
[f 2 1][vp 2 0 65535 646 0 0]¡Ha cambiado al Ermitaño![n][w][e]

[msg AST_btl_06_580_01]
[f 2 1][vp 2 0 65535 647 0 0]¡Ahora es el arcano de la Fortuna![n][w][e]

[msg AST_btl_06_581_01]
[f 2 1][vp 2 0 65535 648 0 0]¡Nix ha cambiado al arcano de la Fuerza![n][w][e]

[msg AST_btl_06_582_01]
[f 2 1][vp 2 0 65535 649 0 0]¡Nix ha cambiado al Ahorcado![n][w][e]

[msg AST_btl_06_583_01]
[f 2 1][vp 2 0 65535 650 0 0]¡Sed fuertes![n][w][e]

[msg AST_btl_06_584_01]
[f 2 1][vp 2 0 65535 651 0 0]未使用[n][w][e]

[msg AST_btl_06_585_01]
[f 2 1][vp 2 0 65535 652 0 0]Estos dos van en serio... ¡Pero sé que podemos conseguirlo![n][w][e]

[msg AST_btl_06_586_01]
[f 2 1][vp 2 0 65535 653 0 0]Sed precavidos. ¡Siento un poder aún mayor que antes![n][w][e]

[msg AST_btl_06_587_01]
[f 2 1][vp 2 0 65535 654 0 0]¡Ah! ¡El miedo ha afectado a todos! ¡Tengo un mal presentimiento! Por favor, ¡levantaos![n][w][e]

[msg AST_btl_06_588_01]
[f 2 1][vp 2 0 65535 655 0 0]未使用[n][w][e]

[msg AST_btl_06_589_01]
[f 2 1][vp 2 0 65535 656 0 0]未使用[n][w][e]

[msg AST_btl_06_590_01]
[f 2 1][vp 2 0 65535 657 0 0]未使用[n][w][e]

[msg AST_btl_06_591_01]
[f 2 1][vp 2 0 65535 658 0 0]未使用[n][w][e]

[msg AST_btl_06_592_01]
[f 2 1][vp 2 0 65535 659 0 0]未使用[n][w][e]

[msg AST_btl_06_593_01]
[f 2 1][vp 2 0 65535 660 0 0]未使用[n][w][e]

[msg AST_btl_06_594_01]
[f 2 1][vp 2 0 65535 661 0 0]未使用[n][w][e]

[msg AST_btl_06_595_01]
[f 2 1][vp 2 0 65535 662 0 0]未使用[n][w][e]

[msg AST_btl_06_596_01]
[f 2 1][vp 2 0 65535 663 0 0]未使用[n][w][e]

[msg AST_btl_06_597_01]
[f 2 1][vp 2 0 65535 664 0 0]未使用[n][w][e]

[msg AST_btl_06_598_01]
[f 2 1][vp 2 0 65535 665 0 0]未使用[n][w][e]

[msg AST_btl_06_599_01]
[f 2 1][vp 2 0 65535 666 0 0]未使用[n][w][e]

[msg AST_btl_06_600_01]
[f 2 1][vp 2 0 65535 667 0 0]未使用[n][w][e]

[msg AST_btl_06_601_01]
[f 2 1][vp 2 0 65535 668 0 0]未使用[n][w][e]

[msg AST_btl_06_602_01]
[f 2 1][vp 2 0 65535 669 0 0]未使用[n][w][e]

[msg AST_btl_06_603_01]
[f 2 1][vp 2 0 65535 670 0 0]未使用[n][w][e]

[msg AST_btl_06_604_01]
[f 2 1][vp 2 0 65535 671 0 0]未使用[n][w][e]

[msg AST_btl_06_605_01]
[f 2 1][vp 2 0 65535 672 0 0]未使用[n][w][e]

[msg AST_btl_06_606_01]
[f 2 1][vp 2 0 65535 673 0 0]未使用[n][w][e]

[msg AST_btl_06_607_01]
[f 2 1][vp 2 0 65535 674 0 0]未使用[n][w][e]

[msg AST_btl_06_608_01]
[f 2 1][vp 2 0 65535 675 0 0]未使用[n][w][e]

[msg AST_btl_06_609_01]
[f 2 1][vp 2 0 65535 676 0 0]未使用[n][w][e]

[msg AST_btl_06_610_01]
[f 2 1][vp 2 0 65535 677 0 0]未使用[n][w][e]

[msg AST_btl_06_611_01]
[f 2 1][vp 2 0 65535 678 0 0]未使用[n][w][e]

[msg AST_btl_06_612_01]
[f 2 1][vp 2 0 65535 679 0 0]未使用[n][w][e]

[msg AST_btl_06_613_01]
[f 2 1][vp 2 0 65535 680 0 0]未使用[n][w][e]

[msg AST_btl_06_614_01]
[f 2 1][vp 2 0 65535 681 0 0]未使用[n][w][e]

[msg AST_btl_06_615_01]
[f 2 1][vp 2 0 65535 682 0 0]未使用[n][w][e]

[msg AST_btl_06_616_01]
[f 2 1][vp 2 0 65535 683 0 0]未使用[n][w][e]

[msg AST_btl_06_617_01]
[f 2 1][vp 2 0 65535 684 0 0]未使用[n][w][e]

[msg AST_btl_06_618_01]
[f 2 1][vp 2 0 65535 685 0 0]未使用[n][w][e]

[msg AST_btl_06_619_01]
[f 2 1][vp 2 0 65535 686 0 0]未使用[n][w][e]

[msg AST_btl_06_620_01]
[f 2 1][vp 2 0 65535 687 0 0]未使用[n][w][e]

[msg AST_btl_06_621_01]
[f 2 1][vp 2 0 65535 688 0 0]未使用[n][w][e]

[msg AST_btl_06_622_01]
[f 2 1][vp 2 0 65535 689 0 0]未使用[n][w][e]

[msg AST_btl_06_623_01]
[f 2 1][vp 2 0 65535 690 0 0]未使用[n][w][e]

[msg AST_btl_06_624_01]
[f 2 1][vp 2 0 65535 691 0 0]未使用[n][w][e]

[msg AST_btl_06_625_01]
[f 2 1][vp 2 0 65535 692 0 0]未使用[n][w][e]

[msg AST_btl_06_626_01]
[f 2 1][vp 2 0 65535 693 0 0]未使用[n][w][e]

[msg AST_btl_06_627_01]
[f 2 1][vp 2 0 65535 694 0 0]未使用[n][w][e]

[msg AST_btl_06_628_01]
[f 2 1][vp 2 0 65535 695 0 0]未使用[n][w][e]

[msg AST_btl_06_629_01]
[f 2 1][vp 2 0 65535 696 0 0]未使用[n][w][e]

[msg AST_btl_06_630_01]
[f 2 1][vp 2 0 65535 697 0 0]未使用[n][w][e]

[msg AST_btl_06_631_01]
[f 2 1][vp 2 0 65535 698 0 0]未使用[n][w][e]

[msg AST_btl_06_632_01]
[f 2 1][vp 2 0 65535 699 0 0]未使用[n][w][e]

[msg AST_btl_06_633_01]
[f 2 1][vp 2 0 65535 700 0 0]未使用[n][w][e]

