[msg MSG_001_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 3 0 65535 5001 0 0]Vivir en la residencia es superguay, ¿verdad?[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Estrenar habitación es un buen cambio de aires. Aunque me está costando colocar las cosas que traigo...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]La verdad es que me alegro de haberme venido a vivir con vosotros.[n][w][e]

[msg MSG_001_1_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5131 0 0]Pensaba que teníamos que quedarnos en la residencia durante los días libres...[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0]Bueno, o eso creía.[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0]Yukari me dijo antes que iba a ir a visitar el santuario.[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0]Aquí tenemos más libertad de la que me imaginaba. Es una experiencia totalmente nueva para mí.[n][w][e]

[msg MSG_002_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5003 0 0]Como ya sabrás, mi Persona se llama Lucía.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Mi especialidad consiste en detectar enemigos y procesar información, por eso sirvo de ayuda para el equipo.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Aunque no puedo enfrentarme directamente a los enemigos...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]... hago todo lo que puedo para asistir al grupo.[n][w][e]

[msg MSG_003_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5074 0 0]Junpei me ha dicho que estás jugando a un juego en línea. ¿Es eso cierto, [nl]?[n][w][e]

[sel SEL_004_0_0 top]
[f 2 1]Sí, así es.[e]
[f 2 1]No.[e]

[msg MSG_005_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5107 0 0]Anda, entonces puedes jugar con gente de todo el mundo, ¿verdad?[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0]Es fantástico que internet conecte a tanta gente diferente. Quizá lo pruebe...[n][w][e]

[msg MSG_006_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5067 0 0]Anda, ya veo... Pero Junpei te dio uno, ¿no?[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Igual deberías probarlo. ¿Quién sabe? Quizá conozcas a alguien en el juego.[n][w][e]

[msg MSG_007_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5076 0 0]Hice una estimación de la fuerza de las sombras grandes que aún nos quedan por enfrentar y que aparecen durante las lunas llenas.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Como habrás podido imaginar, nos toca un combate de los duros, pero creo que no tendremos problemas.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Todo saldrá bien si seguís entrenando y ganando fuerza en la Tártaro.[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0][vp 3 0 65535 5117 0 0]Esforcémonos a tope.[n][w][e]

[msg MSG_008_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5014 0 0]Vaya, aquí no hay nadie... Habrán salido.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Creo que Yukari ha ido otra vez al santuario.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Hoy no tengo planes, así que creo que me quedaré aquí.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Si quieres salir, ve. Tú no te preocupes por mí, que yo estoy bien.[n][w][e]

[msg MSG_009_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5062 0 0]Parece que Kirijo y Sanada no están, así que habrá que ir a la Tártaro en otro momento.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Yo también creo que esta noche me quedaré descansando.[n][w][e]

[msg MSG_010_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5077 0 0]El otro día leí una cosa en internet mientras estaba buscando información...[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0]Por lo visto, hubo una explosión cerca de nuestro instituto hace diez años.[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0]Al mismo tiempo, un gran número de estudiantes se negó a ir a clase...[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0]Las noticias afirmaban que ambos incidentes guardaban relación.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Y eso es todo lo que se sabe. Sé que pasó hace mucho, pero ¿no te llama la atención?[n][w][e]

[msg MSG_011_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5003 0 0]Sé que el director tiene buenas intenciones, pero muchas veces no sé cómo reaccionar a sus bromas.[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0]Y tampoco me gusta eso de fingir que no le he oído... ¿Qué debería hacer?[n][w][e]

[sel SEL_012_0_0 top]
[f 2 1]Finge una risa.[e]
[f 2 1]Sé fiel a tu corazón.[e]
[f 2 1]Actúa con normalidad.[e]

[msg MSG_013_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5027 0 0]Tienes razón...[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0]¿Algo así? "¡Anda, señor director, qué gracioooso! Ja, ja, ja...".[n][w][e]

[msg MSG_014_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5028 0 0]Creo que es importante hacer lo que tu corazón te diga, pero esto es una excepción.[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0]Si le digo que sus bromas no tienen gracia, heriré sus sentimientos...[n][w][e]

[msg MSG_015_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5025 0 0]V-vale... Sé normal... Normal...[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0]Aunque no sé cuánto aguantaré así... Ojalá cambiara de tema y hablara de otra cosa.[n][w][e]

[msg MSG_016_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0][vp 3 0 65535 5004 0 0]¿Te has enterado de lo de las parejas que se han contagiado de apatía? En mi clase no se habla de otra cosa.[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0]No tengo ni idea de por qué están atacando a parejas en concreto...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Es que no tiene sentido. ¿Acaso forma parte de algún plan de las sombras?[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Ojalá encontremos algo cuando investiguemos... Bueno, será mejor que no nos desanimemos.[n][w][e]

[msg MSG_017_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5017 0 0]Hoy tampoco hay nadie por aquí. A esta gente parece que le gusta mucho la calle.[n][w][e]

[msg MSG_018_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5062 0 0]Parece que Kirijo y Sanada no están, así que habrá que ir a la Tártaro en otro momento.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Creo que hoy me meteré temprano en la cama, porque al final siempre me acuesto muy tarde.[n][w][e]

[msg MSG_019_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5003 0 0]Ah, mmm... S-solo estábamos hablando de cosas de chicas.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]No me han pedido que averigüe algo ni nada por el estilo. De verdad.[n][w][e]

[msg MSG_020_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5074 0 0]Ah, sí... ¿Has estado llevando la cuenta de las fases lunares todos los meses, [nl]?[n][w][e]

[sel SEL_021_0_0 top]
[f 2 1]Por supuesto.[e]
[f 2 1]Para nada.[e]

[msg MSG_022_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 3 0 65535 5108 0 0]¡Anda, qué bien! Por eso eres nuestra líder.[n][w][e]

[msg MSG_023_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5049 0 0]Vaya... Es que es un montón de trabajo.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Espero que puedas dedicar unos minutos a pensar en ello de vez en cuando. Así nos organizaremos mejor.[n][w][e]

[msg MSG_023_5_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5062 0 0]Pronto será luna llena, así que será mejor que me organice yo también.[n][w][e]

[msg MSG_024_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5074 0 0]Por cierto, la próxima luna llena es el 7 de julio, el mismo día que el Tanabata.[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0]La verdad es que no tengo ni idea de cómo será el próximo combate...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Lo mejor será prepararse para lo que sea. Así no nos llevaremos ningún susto.[n][w][e]

[msg MSG_025_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 2 65535 65535 0 0][vp 3 0 65535 5001 0 0]Quedan dos días para que sea luna llena...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Aún no me imagino qué tipo de combate será.[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0]Intentemos ir lo mejor preparados posibles. Más vale prevenir que curar.[n][w][e]

[msg MSG_026_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5062 0 0]Mmm... No capto ninguna señal de la sombra que tiene que aparecer en la luna llena de mañana...[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0]Me parece que nos va a tocar esperar a que aparezca.[n][w][e]

[msg MSG_027_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5003 0 0]Oye, quiero preguntarte algo de la operación de anoche...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]¿Pasó algo entre Yukari y tú?[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0]Últimamente Yukari está muy rara. Espero que no esté preocupada por algo.[n][w][e]

[msg MSG_028_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0][vp 3 0 65535 5077 0 0]Me parece maravilloso que Kirijo esté tan volcada en la causa...[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0]Pero tanto arrojo puede confundir a las personas de tu alrededor. Es un acto difícil de equilibrar...[n][w][e]

[msg MSG_029_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5066 0 0]Quizás no deberíamos ir a la Tártaro esta noche...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Junpei me ha pedido que repasara lo que hablamos en la reunión...[n][w][e]

[msg MSG_030_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2062 0 0]Pero si derrotamos a las doce sombras...[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]No podré usar mi Persona nunca más.[n][w][e]
[f 2 1][bup 3 3 65535 65535 0 0]Buf, es un poder increíble... No puedo dejar que se desperdicie...[n][w][e]

[msg MSG_031_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5003 0 0]Quizá sería mejor posponer nuestra visita de esta noche a la Tártaro. Parece que todos están en su habitación estudiando.[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0][f 4 25 6]...[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0]Todos están tan callados porque están ocupados estudiando, ¿verdad...?[n][w][e]

[sel SEL_032_0_0 top]
[f 2 1]Eso es.[e]
[f 2 1]Eso espero...[e]

[msg MSG_033_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0][vp 3 0 65535 5028 0 0]Si es así, todo volverá a la normalidad cuando los exámenes terminen.[n][w][e]

[msg MSG_034_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0][vp 3 0 65535 5027 0 0]Y yo... No puedo evitar pensar en ello.[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0]¿Y si están escondidos en sus habitaciones por otro motivo...?[n][w][e]

[msg MSG_035_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 3 0 65535 5007 0 0]Qué ganas tengo de hacer el viaje.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Yo solo conozco Yakushima de los libros de texto.[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0]Hasta hace poco resultaba impensable que pudiera hacer un viaje con vosotros...[n][w][e]

[msg MSG_036_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5001 0 0]Kirijo y Sanada no están aquí, así que dudo que vayamos esta noche a la Tártaro.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Mañana salimos de viaje, así que creo que me voy a ir ya a la cama.[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0][vp 3 0 65535 5076 0 0]Oye, por cierto. ¿Crees que Yukari está bien?[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0]Esta tarde fuimos a comprarnos unos bikinis, pero parecía tristona...[n][w][e]

[msg MSG_037_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5131 0 0]Parece que todos estamos cansados. Tú también tienes que estar agotada, [nl].[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0]Mejor no vamos a la Tártaro y nos quedamos descansando.[n][w][e]

[msg MSG_038_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5078 0 0]Kirijo es increíble...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Ha bordado los exámenes, y eso con la que tenemos encima...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Es capaz de ignorar toda distracción y centrarse en lo que toca. Ojalá yo pudiera hacer lo mismo.[n][w][e]

[msg MSG_039_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5002 0 0]Creo que Amada se molestaría si se enterara de que he dicho esto, pero... ¿no te parece que es adorable?[n][w][e]

[sel SEL_040_0_0 top]
[f 2 1]Ya, tienes razón.[e]
[f 2 1]No, la verdad.[e]
[f 2 1]¿No es un poco precoz?[e]

[msg MSG_041_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 3 0 65535 5131 0 0]Je, je. Supongo que esto es lo que se siente cuando se tiene un hermano pequeño.[n][w][e]

[msg MSG_042_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5067 0 0]Uy...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Quizá no debería decir esas cosas, pero es que me gusta mucho la idea de tener un hermano pequeño.[n][w][e]

[msg MSG_043_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 3 0 65535 5132 0 0]Je, je. Eso es lo bueno de él, que es como un hermano pequeño.[n][w][e]

[msg MSG_043_5_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 3 0 65535 5131 0 0]Si Amada fuera mi hermanito de verdad, creo que le perdonaría todo.[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0]Aunque es bastante maduro. No tiene pinta de ir por ahí metiéndose en problemas.[n][w][e]

[msg MSG_044_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0][vp 3 0 65535 5123 0 0]¿Qué pasará si el país se va a pique?[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0]¿Estallaría una guerra?[n][w][e]
[f 2 1][bup 6 4 65535 65535 0 0]No debería darle demasiadas vueltas. Al fin y al cabo, estamos luchando para evitar que eso ocurra.[n][w][e]

[msg MSG_045_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5076 0 0]Oye, ¿sabes lo del incidente que ocurrió por culpa de los experimentos del Grupo Kirijo?[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Dicen que pasó porque estaban intentando reunir sombras.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]¿Eso significa que las sombras existían antes de que surgieran la torre Tártaro y la Hora Oscura?[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]¿Y cuánto tiempo llevan existiendo...?[n][w][e]

[msg MSG_046_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5009 0 0]Como ya dije antes, hoy no deberíamos ir a la torre Tártaro.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Sé que quieres ir porque pronto habrá luna llena, pero...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Será mejor que no...[n][w][e]

[msg MSG_047_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5069 0 0]Espero que no sea nada, pero...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]¿No te da la sensación de que últimamente hay más gente con apatía que el mes pasado?[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Tenemos que hacer lo posible para que todo el mundo pueda volver a sus vidas.[n][w][e]

[msg MSG_048_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 3 0 65535 5115 0 0]Dicen que Korocito se pondrá bien... Qué alivio.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]¿Crees que el sacerdote que falleció lo protegía?[n][w][e]

[sel SEL_049_0_0 top]
[f 2 1]Eso creo.[e]
[f 2 1]Ni idea.[e]

[msg MSG_050_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 3 0 65535 5029 0 0]El vínculo entre una persona y su mascota es increíble.[n][w][e]

[msg MSG_051_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 3 0 65535 5081 0 0]Me gustaría pensar que fue el sacerdote, la verdad.[n][w][e]

[msg MSG_052_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5138 0 0]Me he enterado de que has terminado la competición, [nl].[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Tienes que estar cansada, ¿eh? Quizá sea mejor que no vayamos a la Tártaro. Ve a descansar un rato.[n][w][e]

[msg MSG_053_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5004 0 0]La operación del mes pasado no fue tan bien porque el comportamiento del enemigo era imprevisible...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Por eso estoy haciendo algunos entrenamientos y ejercicios de visualización, para asegurarme de que no vuelva a ocurrir.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]¡Haré todo lo que pueda por ayudaros![n][w][e]

[msg MSG_054_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 2 65535 65535 0 0][vp 3 0 65535 5001 0 0]Tenemos que ganar también esta vez.[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0]Haré todo lo posible para poder estar junto a Korocito, que ya está mejor.[n][w][e]

[msg MSG_055_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5062 0 0]Todos parecen agotados...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Kirijo y Sanada tampoco están, así que ya iremos a la Tártaro otro día.[n][w][e]

[msg MSG_056_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0][vp 3 0 65535 5089 0 0]Lucía no pudo detectar a los miembros de esa tal Strega.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Deben tener mucho poder para ser capaces de escabullirse de ella.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]¿Quiénes diantres serán...?[n][w][e]

[msg MSG_057_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5074 0 0]Por cierto, ¿qué vamos a hacer con las comidas de Korocito?[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]¿Vamos a comprar comida de perro o a cocinar para él? Deberíamos decidirlo.[n][w][e]

[msg MSG_058_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5066 0 0]Entiendo que no quieras asistir a las clases de verano, pero creo que son necesarias.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Cuando derrotemos al resto de sombras, volveremos a ser estudiantes normales y corrientes.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Y, si ahora vamos mal en los estudios, después será peor.[n][w][e]

[msg MSG_059_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5131 0 0]¿A Korocito le gustará vivir en la residencia?[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Espero que se adapte y que le termine encantando vivir aquí.[n][w][e]

[msg MSG_060_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5003 0 0]Kirijo y Sanada no están, así que dudo que esta noche vayamos a la Tártaro.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Últimamente no hemos ido mucho por culpa de las clases de verano, pero tampoco nos queda otra.[n][w][e]

[msg MSG_061_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5074 0 0]Ahora que me acuerdo, hoy se celebraba un festival de verano en el santuario.[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0]Yo ya hice planes con una amiga, así que no puedo ir...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]A ver si vamos todos juntos el año que viene.[n][w][e]

[msg MSG_062_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5025 0 0]Sé que Korocito no quería herir los sentimientos de Yukari.[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0]Pero... está algo alicaída...[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0]En momentos como estos, no sé qué hacer...[n][w][e]

[msg MSG_063_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5001 0 0]Deberíamos seguir el consejo de Yukari y terminar cuanto antes nuestros deberes de verano.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Junpei dice que los va a hacer todos de golpe... ¿Tú cómo vas a hacer los tuyos, [nl]?[n][w][e]

[sel SEL_064_0_0 top]
[f 2 1]Todos a la vez.[e]
[f 2 1]Poco a poco.[e]

[msg MSG_065_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 3 0 65535 5067 0 0]Anda, ¿tú también? Cada maestrillo tiene su librillo.[n][w][e]

[msg MSG_066_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5029 0 0]Yo también pienso que es la mejor forma de hacerlos.[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0]Yo lo he estado haciendo así y ya me lo he quitado casi todo de encima.[n][w][e]

[msg MSG_066_5_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5079 0 0]Anda, ahora que caigo... Espero que a Natsuki le vaya bien con las tareas.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Me dijo que se dejó todos los libros en el instituto... Será mejor que le pregunte luego qué tal le va.[n][w][e]

[msg MSG_067_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5076 0 0]Mucha gente ha estado escribiendo sobre los Perdidos en sus blogs.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Tenemos que derrotar a las cuatro sombras que quedan y así frenar el daño que están haciendo a la sociedad.[n][w][e]

[msg MSG_068_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 3 0 65535 1067 0 0]Yo también lo he oído.[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0]Una chica relataba el sufrimiento que padeció cuando formaba parte de los Perdidos. Y otro chico hablaba de cómo sus padres fueron víctimas.[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0]Ahora hay más personas afectadas...[n][w][e]

[msg MSG_069_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5004 0 0]El número de personas víctimas de las sombras ha vuelto a aumentar.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Hay que derrotar a las cuatro sombras restantes, cueste lo que cueste.[n][w][e]

[msg MSG_070_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5078 0 0]Explorar la Tártaro y derrotar las sombras es importante, pero también lo son los deberes de verano.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]De hecho, puede que los deberes tengan incluso más prioridad por la fecha de entrega...[n][w][e]

[msg MSG_071_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0]Exacto. ¿Has oído, Junpei?[n][w][e]

[msg MSG_072_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0]¡Pues claro! ¿Quién te crees que soy?[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]¡Vale, me habéis pillado! ¡Ni siquiera he empezado![n][w][e]

[msg MSG_073_0_0 [Yukari Takeba]]
[f 2 1][bup 2 2 65535 65535 0 0][f 4 25 2]...[n][w][e]

[msg MSG_074_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 65535 65535 0 0][vp 3 0 65535 2113 0 0]¡Para! ¡No pongas esa mirada de decepción![n][w][e]

[msg MSG_074_1_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5074 0 0]El otro día oí algo interesante en la tele...[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0]Cuando hace calor, a uno se le quita el apetito, ¿verdad? Pues bien, comer helado podría producir golpes de calor.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]A veces, solo me como un helado para almorzar. Debería tener más cuidado con esas cosas.[n][w][e]

[msg MSG_075_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5062 0 0]Amada parecía algo aletargado...[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0]¿Será un golpe de calor? Últimamente hace mucho bochorno.[n][w][e]

[msg MSG_076_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5002 0 0]Junpei y Amada parecen hermanos, ¿verdad?[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0]Junpei es el hermano mayor tonto y Amada, el pequeño y sensato.[n][w][e]

[msg MSG_077_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2036 0 0]Querrás decir "el hermano mayor superguay y maduro", ¿no?[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Pues no suena nada mal eso de tener un hermanito. ¿Crees que lograré que me llame "hermano mayor"?[n][w][e]

[msg MSG_078_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0][vp 3 0 65535 5003 0 0]Sanada está muy raro últimamente, ¿no te parece?[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0]Quizá le resulta difícil ver a Amada ponerse en peligro...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]A pesar de las apariencias, creo que en el fondo Sanada es un pedazo de pan...[n][w][e]

[msg MSG_079_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5002 0 0]Le he dado a Aigis ropa de invierno para que vaya cubierta.[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0]Espero que no pase mucho calor.[n][w][e]

[msg MSG_080_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0][vp 3 0 65535 5062 0 0]Aragaki tiene unas pintas que dan miedo, pero creo que solo es un incomprendido...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]No creo que sea mal tipo. Al fin y al cabo, luchaba con Sanada y Kirijo.[n][w][e]

[msg MSG_080_1_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5075 0 0]Aún no conozco demasiado a Aragaki.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Aunque, no sé por qué, siento que puedo confiar en él. ¿Será porque está acostumbrado a luchar contra las sombras?[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Yo también me esforzaré para ser una ayuda más útil para el equipo.[n][w][e]

[msg MSG_081_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5063 0 0]¿Recuerdas que Lucía no pudo detectar a Strega cuando nos los topamos la última vez?[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Creo que fue alguna habilidad de Medea la que lo impidió.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Solo vimos a dos de ellos, pero esa chica debía estar cerca.[n][w][e]

[msg MSG_083_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5003 0 0]Hay muchas cosas que no comprendemos sobre Chidori.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Además, es curioso que Lucía no pueda percibirla...[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0]Ahora mismo no está estable mentalmente. No puedo imaginar por lo que estará pasando para llegar a autolesionarse.[n][w][e]

[msg MSG_084_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 3 0 65535 5025 0 0]Me alegro de que Junpei haya vuelto a la normalidad.[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0]Pero... ¿crees que su relación con Chidori saldrá adelante?[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0]Forma parte de Strega y son nuestros rivales.[n][w][e]

[sel SEL_085_0_0 top]
[f 2 1]No les pasará nada.[e]
[f 2 1]Ni idea.[e]

[msg MSG_086_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 3 0 65535 5029 0 0]Espero que así sea.[n][w][e]

[msg MSG_087_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0][vp 3 0 65535 5027 0 0]Justo ahora que se llevaban mejor... Qué ironía del destino.[n][w][e]

[msg MSG_088_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 3 0 65535 5081 0 0]Me alegro de que Aragaki se uniera a nosotros. La verdad es que nos ha facilitado mucho las cosas.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Pero tampoco es plan de echar sobre él toda la carga, porque entonces nunca nos haremos más fuertes.[n][w][e]

[msg MSG_089_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 65535 65535 0 0][vp 3 0 65535 2108 0 0]Vaya, lo dices en serio.[n][w][e]

[msg MSG_090_0_0 [Yukari Takeba]]
[f 2 1][bup 2 2 65535 65535 0 0][vp 3 0 65535 1123 0 0]Pues claro. ¿Qué te sorprende? Deberías aprender de su ejemplo.[n][w][e]

[msg MSG_095_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 3 0 65535 5131 0 0]Junpei se preocupa mucho por Chidori.[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0]Hasta ahora, solo le había visto haciendo el tonto.[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0]Pero parece que es todo un caballero...[n][w][e]

[msg MSG_096_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0][vp 3 0 65535 5006 0 0]¡Te has calado! ¿Te encuentras bien? No tienes buen aspecto...[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0]Creo que no deberías ir a la torre Tártaro esta noche. Quédate descansando.[n][w][e]

[msg MSG_097_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 3 0 65535 3024 0 0]Yamagishi tiene razón. Deberías cuidarte.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0]Tampoco creo que nadie esté por la labor de ir a la torre Tártaro con este viento y esta lluvia.[n][w][e]

[msg MSG_098_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 3 0 65535 5067 0 0]Me alegra que estés mejor.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Pero no te fuerces demasiado, ¿vale? No vaya a ser que cojas otro resfriado.[n][w][e]

[msg MSG_099_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5002 0 0]Me alegra que te hayas recuperado rápido.[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0]Será porque te has pasado dos días seguidos en cama.[n][w][e]

[msg MSG_100_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5068 0 0]Si la Hora Oscura desaparece...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Lo más seguro es que perdamos nuestras habilidades de Persona y volvamos a ser estudiantes normales, ¿no?[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Ah, pero supongo que no seremos los mismos de antes.[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0][vp 3 0 65535 5028 0 0]Viviremos vidas más ricas y plenas gracias a todo lo que hemos experimentado juntos.[n][w][e]

[msg MSG_101_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5074 0 0]¿Cómo será un día en la vida de Aragaki?[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Nunca le vemos por el instituto y tampoco tiene pinta de querer hablar del tema.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Sé que me meto donde no me llaman, pero es que me pica la curiosidad.[n][w][e]

[msg MSG_102_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5004 0 0]Amada está muy triste últimamente. ¿Qué mosca le habrá picado?[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0]No sé qué decir.[n][w][e]

[msg MSG_103_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5077 0 0]Sigo preocupada por Amada...[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0]Creo que algo le tiene preocupado últimamente. Ojalá se abriera y se desahogara con nosotros.[n][w][e]

[msg MSG_104_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 3 0 65535 1062 0 0]Tiene que ser duro. Parece el tipo de persona que trata de resolver todo por su cuenta.[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0]Si algo no le fuera bien... Estaría más que encantada de ayudarle.[n][w][e]

[msg MSG_105_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5108 0 0]Los de tercero son todos increíbles.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Aunque estamos a punto de librar nuestra última batalla contra las sombras, no parece que estén nerviosos.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]O puede que estén intentando ocultarlo para no preocuparnos... Pues si es así, eso dice mucho de ellos.[n][w][e]

[msg MSG_105_1_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5074 0 0]El dispositivo de la sala de mando lleva un registro de cuándo se inicia, pero no se ha encontrado ningún problema.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Parece que la tele comparte el mando con otra cosa, por eso se enciende sola a veces...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]¿Quizá alguien esté usando el mismo control desde otra sala?[n][w][e]

[msg MSG_106_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 3 0 65535 5113 0 0]Ya es octubre...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Hace nada era verano... El tiempo se pasa volando.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Quizá sea porque hemos estado muy ocupados con lo de las lunas llenas y las sombras.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Desde que me mudé a la residencia, parece que todo ha pasado de golpe.[n][w][e]

[msg MSG_106_1_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5117 0 0]Solo quedan tres sombras de las grandes.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Tenemos que estar preparados para cualquier cosa.[n][w][e]

[msg MSG_107_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0][vp 3 0 65535 5110 0 0]Soy de lo peor...[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0]Perdí la compostura y le grité a Yukari.[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0][vp 3 0 65535 5084 0 0]Es que Amada me tiene muy preocupada...[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0]Sé lo que es sentir que no encajas en ninguna parte.[n][w][e]

[msg MSG_108_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5001 0 0]Hoy ha sido un día muy movidito. ¿Qué tal si dejamos la Tártaro para otro momento?[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Mañana volvemos al lío. Y Amada también vendrá con nosotros, por supuesto.[n][w][e]

[msg MSG_109_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0][vp 3 0 65535 5134 0 0]Aunque no llegase a estar mucho tiempo con nosotros, aún no me creo que no lo vayamos a volver a ver.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Sabía que el riesgo siempre estaba ahí, pero...[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0]Disculpa, estoy... algo alterada. No puedo pensar con claridad.[n][w][e]

[msg MSG_110_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5003 0 0][nl], ¿has estudiado para los exámenes?[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0]A veces me cuesta dejar de pensar en Aragaki...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5035 0 0]Aunque de nada sirve darle más vueltas a lo sucedido...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Lo que tenemos que hacer es centrarnos en los parciales.[n][w][e]

[msg MSG_111_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5074 0 0]Mañana es festivo por el Día del Deporte y la Salud.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Aunque también es la víspera de los parciales, por lo que yo me dedicaré a estudiar todo el día.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Quizá dé un paseo o algo. No es bueno estar dándole vueltas a lo mismo todo el rato.[n][w][e]

[msg MSG_112_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0][vp 3 0 65535 5011 0 0]Ufff, por fin hemos terminado los exámenes. Creo que esta vez no me han salido muy bien...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Me ha costado la vida recordar términos y ecuaciones...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]¿Cómo te ha ido, [nl]?[n][w][e]

[sel SEL_113_0_0 top]
[f 2 1]Como siempre.[e]
[f 2 1]No muy allá.[e]

[msg MSG_114_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 3 0 65535 5107 0 0]Eso es estupendo. Así no tendrás que preocuparte por las notas.[n][w][e]

[msg MSG_115_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5028 0 0]Anda, ¿tú también? Nos tocará compensarlo en los finales.[n][w][e]

[msg MSG_115_5_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0][vp 3 0 65535 5062 0 0]Nunca me había sentido tan descontenta con mis notas... Voy a tener que estudiar más para los finales.[n][w][e]

[msg MSG_120_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5003 0 0]¿Has visto los resultados de los exámenes?[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Al final no me habían salido tan mal como yo pensaba... Aun así, creo que lo podría haber hecho mucho mejor.[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0]Creo que es porque aún tengo demasiadas cosas en la cabeza.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Tengo que mantener la calma.[n][w][e]

[msg MSG_121_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5004 0 0]Pues sí, Natsuki se marcha. La verdad es que estoy muy triste.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Aunque sé que siempre estaremos juntas, por muy lejos que nos encontremos.[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0]Sé que estaré bien porque no hay nada que pueda romper el vínculo que compartimos.[n][w][e]

[msg MSG_122_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5062 0 0]¿Que qué haré yo cuando desaparezca la Hora Oscura? Mmm... No lo sé...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Supongo que intentaré mejorar mi rutina de sueño.[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0]Las noches que toca ir a la Tártaro me acuesto bastante tarde.[n][w][e]

[msg MSG_123_0_0 [Koromaru]]
[f 2 1][bup 9 0 65535 65535 0 0][vp 3 0 65535 8003 0 0]Auuu...[n][w][e]

[msg MSG_125_0_0 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 3 0 65535 7069 0 0]¿Tú también, Koromaru? Pero... tú puedes dormir cuando quieras, ¿no?[n][w][e]

[msg MSG_126_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5074 0 0]A veces, cuando me meto en internet...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Me pongo a pensar lo útil que resulta a la hora de establecer vínculos con otras personas.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Normalmente no le prestamos atención a esas cosas, pero cuando buscamos información en internet, conectamos con otros y formamos vínculos.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5054 0 0]Ay, perdona. Ha sonado raro lo que he dicho, ¿no? Solo quería compartir mis pensamientos con alguien.[n][w][e]

[msg MSG_128_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0][vp 3 0 65535 5123 0 0]La operación ha sido un éxito y, aun así, el número de Perdidos no ha disminuido...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Pero casi hemos acabado. La paz volverá pronto a la ciudad.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Tengo que prepararme para nuestra última batalla.[n][w][e]

[msg MSG_129_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5001 0 0]Ya estoy nerviosa por la batalla que nos toca librar en la próxima luna llena...[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0]¡E-en estos casos, lo mejor es mantener la calma![n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0]¡Así que vamos a intentar tranquilizarnos e ir a por la victoria![n][w][e]

[msg MSG_131_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5003 0 0]Creo que lo mejor será no ir esta noche a la Tártaro. Además, no todos están...[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0]Dudo que los demás quieran ir.[n][w][e]

[msg MSG_132_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5115 0 0]Parece que Aigis no tiene nada grave. Menos mal.[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0]Aun así, me pregunto si estará bien. Espero que no se sienta culpable por lo sucedido.[n][w][e]

[sel SEL_133_0_0 top]
[f 2 1]Estará bien.[e]
[f 2 1]Ni te rayes.[e]

[msg MSG_134_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 3 0 65535 5039 0 0]Sí, tienes razón.[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0]Me siento más tranquila al oírte decir eso.[n][w][e]

[msg MSG_135_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 2 65535 65535 0 0][vp 3 0 65535 5050 0 0]¿T-tú crees...?[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Supongo que tienes razón. Quizá esté paranoica. Seguro que Aigis estará bien.[n][w][e]

[msg MSG_136_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5069 0 0]El director siempre estaba contando chistes malos... ¿Crees que su personalidad era así de verdad?[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0]¿O quizá estuvo fingiendo todo este tiempo para que no nos diésemos cuenta?[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0]¿Disfrutaría del tiempo que pasó aquí...?[n][w][e]

[msg MSG_137_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6058 0 0]Nadie lo sabe. Las respuestas nos rehúyen ahora, y así será siempre.[n][w][e]

[msg MSG_138_0_0 [Yukari Takeba]]
[f 2 1][bup 2 2 65535 65535 0 0][vp 3 0 65535 1028 0 0]¿Qué más da...? Lo único que importa es que nos traicionó.[n][w][e]
[f 2 1][bup 2 2 65535 65535 0 0]Nunca le perdonaré por usar a mi padre...[n][w][e]

[msg MSG_140_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5003 0 0]Eh, ¿cómo se llamaba...? ¿Ryoji...? ¿Ryoji Mochizuki? Eso es. Bueno, pues lo he visto en el pasillo.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Tiene un aura muy inquietante...[n][w][e]

[msg MSG_141_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0][vp 3 0 65535 5077 0 0]Me preocupa Kirijo...[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0]Siempre está muy tranquila y es muy sensata. No soporto verla así...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Espero que el viaje escolar le levante los ánimos...[n][w][e]

[msg MSG_142_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5002 0 0]Hace un rato estaba hablando con Yukari.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]¿Sabías que antes vivía en Kioto?[n][w][e]

[sel SEL_143_0_0 top]
[f 2 1]Ya lo sabía.[e]
[f 2 1]No lo sabía.[e]

[msg MSG_144_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 3 0 65535 5131 0 0]Podríamos pedirle que nos hiciese de guía.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]¿O es de mala educación...?[n][w][e]

[msg MSG_145_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5029 0 0]Yo no lo sabía hasta que se lo pregunté directamente.[n][w][e]
[f 2 1][bup 6 4 65535 65535 0 0]Cuando Yukari habla, parece que es de por aquí. ¿Le cambiará el acento cuando estemos en Kioto?[n][w][e]

[msg MSG_145_5_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 3 0 65535 5131 0 0]¿Cómo será vivir en Kioto?[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Aquí no hay apenas nada histórico ni cultural...[n][w][e]

[msg MSG_150_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5004 0 0]Debe de ser difícil reponerse de un incidente tan doloroso...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Pero el viaje escolar solo es una vez en la vida. Espero que se lo pase bien allí.[n][w][e]

[msg MSG_151_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 3 0 65535 1060 0 0]Sí, lo sé...[n][w][e]

[msg MSG_152_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5138 0 0]Seguro que todos están hoy cansados. Será mejor que vayamos otro día a la Tártaro.[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0]Je, je. Yo me lo he pasado genial en el viaje escolar. ¿Y tú?[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0]Hemos visitado tantos lugares bonitos... Y también he disfrutado mucho las aguas termales.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5005 0 0]Ahora que me acuerdo... Oímos algo extraño cuando estábamos bañándonos. Creo que sería algún mono...[n][w][e]
[f 2 1][bup 6 4 65535 65535 0 0]¿Me estás escuchando, [nl]? Estás sudando... ¿Te encuentras bien?[n][w][e]

[msg MSG_153_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5012 0 0]Solo voy a decirte una cosa.[n][w][e]
[f 2 1][bup 6 2 65535 65535 0 0]Estamos todos agotados por el viaje, así que no iremos a explorar la Tártaro esta noche.[n][w][e]
[f 2 1][bup 6 2 65535 65535 0 0]Eso es todo. Buenas noches.[n][w][e]

[msg MSG_153_1_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5002 0 0]Como Ryoji acaba de llegar, Junpei se ha encargado de enseñarle el instituto.[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0]Parece que Junpei también tiene un lado tierno.[n][w][e]

[msg MSG_154_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5062 0 0]Sé que nadie tiene ganas, pero hay que hacerlo.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]La perseverancia es importante, y más cuando se es adulto en edad de trabajar.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Si ves esto como una oportunidad para consolidar esa aptitud, te será más fácil superar las jornadas de experiencia profesional, ¿no te parece?[n][w][e]

[sel SEL_155_0_0 top]
[f 2 1]Tienes razón.[e]
[f 2 1]Dudo que pueda.[e]

[msg MSG_156_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5025 0 0]Sé que no va a ser fácil, pero tenemos que aguantar estos cuatro días y hacerlo lo mejor que podamos.[n][w][e]

[msg MSG_157_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5098 0 0]De todas formas, la semana de las jornadas de experiencia profesional es obligatoria, así que hagámoslo lo mejor posible.[n][w][e]

[msg MSG_157_1_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5003 0 0]Kirijo y Sanada no volverán hasta la noche.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Así que hoy no vamos a la Tártaro.[n][w][e]

[msg MSG_158_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 10 65535 65535 0 0][vp 3 0 65535 5134 0 0]Junpei y Chidori tenían un vínculo precioso...[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0]Incluso ahora siguen juntos, pero...[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0]Jamás se me pasó por la cabeza que esto fuese a acabar así... Es una tragedia.[n][w][e]

[msg MSG_159_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5003 0 0]¿Crees que Junpei ha ido a las jornadas de experiencia profesional?[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0]Esperemos que no se haya escondido para no ir...[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0]Es difícil adivinar qué hace la gente cuando sale del instituto...[n][w][e]

[msg MSG_160_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5081 0 0]Después de separarme de Natsuki, comprendí que los vínculos que compartimos nunca desaparecerán.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Pienso que pasa lo mismo con Junpei y Chidori.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Aunque Chidori ya no esté aquí..., el vínculo que comparten siempre seguirá existiendo.[n][w][e]

[msg MSG_162_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5001 0 0]¿Crees que Aigis está distinta últimamente?[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0]Parece que está preocupada por algo...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Me inquieta un poco... Espero que solo sean imaginaciones mías.[n][w][e]

[msg MSG_166_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5078 0 0]Esta noche habrá luna llena. Estaré vigilante con Juno por si las moscas.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Otra noche vamos a la Tártaro, ¿vale?[n][w][e]

[msg MSG_167_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0][f 4 25 6]...[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0][vp 3 0 65535 5003 0 0]Vamos a morir todos...[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0]Por muchas ganas que tengamos de vivir, nadie escapa a la muerte...[n][w][e]

[msg MSG_168_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0][vp 3 0 65535 5077 0 0]Con todo lo que está pasando, no podremos ir a la Tártaro durante un tiempo.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Yo también tengo que aclarar mis ideas. Ay, ¿querías preguntarme algo?[n][w][e]

[sel SEL_169_0_0 top]
[f 2 1]El aumento de usuarios de Persona.[e]
[f 2 1]Mi existencia.[e]
[f 2 1]Las doce sombras reviven[e]

[msg MSG_170_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5062 0 0]Según Ryoji, que haya más usuarios de Persona se debe a tu existencia.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Viniste con Ryoji en tu interior, lo que acabó juntándonos a todos...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Así como a las sombras que estaban dispersas por distintos lugares.[n][w][e]

[msg MSG_171_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5061 0 0]Mm, por lo que contó Ryoji...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Hace diez años, estuviste presente en la lucha entre Aigis y Ryoji.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Como Aigis no pudo derrotar a Ryoji, decidió sellarlo en tu interior.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][f 4 25 6]...[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0]Lo que te pasó fue terrible.[n][w][e]

[msg MSG_172_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5065 0 0]Cuando viniste aquí...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Ryoji comenzó a despertar en tu interior y las doce sombras empezaron a actuar.[n][w][e]

[msg MSG_173_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5077 0 0]Quería escuchar la voz de Natsuki..., así que la he llamado.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Se dio cuenta de que estaba preocupada y por eso me preguntó qué me pasaba.[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0][vp 3 0 65535 5110 0 0]Pero no he sido capaz de decirle que el mundo está al borde del abismo.[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0]No sé qué pensar...[n][w][e]

[msg MSG_174_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5003 0 0]He estado pensando en lo que va diciendo por ahí Strega.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]En parte me recuerda a lo que contó Ryoji.[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0]Así que tenían que saber algo de la Caída...[n][w][e]

[msg MSG_175_0_0 [Yukari Takeba]]
[f 2 1][bup 2 2 65535 65535 0 0][vp 3 0 65535 1065 0 0]Qué frustración más grande.[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0]Es como si se rieran de nosotros...[n][w][e]

[msg MSG_176_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 3 65535 65535 0 0][vp 3 0 65535 4033 0 0]No hay nada que podamos hacer ahora mismo, así que vamos a centrarnos en Nix.[n][w][e]

[msg MSG_177_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5089 0 0]No es propio de mí decir esto, pero me alegro de que pronto sean los exámenes...[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0]Cuando estudio, no tengo que pensar en lo que nos depara el futuro.[n][w][e]

[msg MSG_178_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5077 0 0]¿Volverá Ryoji para Año Nuevo?[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]¿Qué estará haciendo ahora? ¿Estará llorando, como antes?[n][w][e]

[msg MSG_179_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5123 0 0]Estuve pensando en la relación que existe entre lo que nos dijeron Ikutsuki y Ryoji...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Y por fin todo cobra sentido.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Ikutsuki hizo que luchásemos contra las 12 sombras con la esperanza de que El Tasador volviera...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]De esta manera logró fusionar a Ryoji, que estaba dentro de ti, con las 12 sombras.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Y ahí es cuando Ryoji se nos apareció como El Tasador en su forma definitiva.[n][w][e]

[msg MSG_180_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5025 0 0]Hay que meditar en muchas cosas, pero también hay que estudiar para los exámenes.[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0]Como no lo haga, me volveré loca.[n][w][e]

[msg MSG_181_0_0 [Ken Amada]]
[f 2 1][bup 8 4 65535 65535 0 0][vp 3 0 65535 7103 0 0]Vaya, Fuuka. Te tomas los estudios muy en serio.[n][w][e]

[msg MSG_182_0_0 [Yukari Takeba]]
[f 2 1][bup 2 3 65535 65535 0 0][vp 3 0 65535 1022 0 0]Por mucho que odie admitirlo, yo también conozco ese sentimiento...[n][w][e]

[msg MSG_183_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4028 0 0]No pasa nada. Seguro que es lo mejor.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]De hecho, volver a la rutina puede ayudar a ver las cosas con mayor claridad llegado el día.[n][w][e]

[msg MSG_184_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5138 0 0]Esta vez me he esforzado más, así que creo que me saldrá todo bien.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]¿Y tú qué, [nl]? ¿Cómo te ha ido el examen?[n][w][e]

[sel SEL_185_0_0 top]
[f 2 1]Lo he bordado.[e]
[f 2 1]Muy mal.[e]

[msg MSG_186_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 3 0 65535 5131 0 0]Eso es genial. Yo creo que también me han ido bastante bien.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Aunque me he saltado algunas preguntas de las que no me sabía la respuesta. Las tendré que revisar después.[n][w][e]

[msg MSG_187_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5094 0 0]Bueno, es comprensible dada la situación en la que estamos.[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0]Si repasas las preguntas que no te sabías, la próxima vez seguro que te sale mejor.[n][w][e]

[msg MSG_187_5_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5003 0 0]No logro sacarme de la cabeza ni la Caída ni a Nix.[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0]Aunque estudiar me ha ayudado a distraerme un rato.[n][w][e]

[msg MSG_188_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5074 0 0]Ah, ya casi es Navidad.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][nl], ¿cuál crees que es el verdadero propósito de la Navidad?[n][w][e]

[sel SEL_189_0_0 top]
[f 2 1]Traer la paz a la Tierra.[e]
[f 2 1]Lograr la felicidad mundial.[e]
[f 2 1]El consumismo.[e]

[msg MSG_190_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 3 0 65535 5029 0 0]Esa es otra forma de verlo. Yo también pienso parecido.[n][w][e]

[msg MSG_191_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 3 0 65535 5026 0 0]Yo también pienso lo mismo.[n][w][e]

[msg MSG_192_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0][vp 3 0 65535 5027 0 0]Bueno, supongo que desde una perspectiva comercial sí que lo es. Es un poco triste.[n][w][e]

[msg MSG_193_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0]El espíritu navideño tendría que sacar a todos una sonrisa.[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0]¡Pues a sonreír![n][w][e]

[msg MSG_193_5_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 3 0 65535 5131 0 0]¡Es Navidad, la época de la alegría! Así que venga, a disfrutar.[n][w][e]

[msg MSG_194_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 3 0 65535 5005 0 0]Ya se han publicado los resultados de los exámenes. Una cosa menos de la que preocuparse.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Bueno, ¿qué hago en Navidad...?[n][w][e]

[msg MSG_195_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0][vp 3 0 65535 5089 0 0]¿Qué pasa...?[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0]Ahora mismo no tengo nada que decir, así que...[n][w][e]

[msg MSG_197_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5089 0 0]No sé si serán nuestras últimas Navidades o no...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Ay, no debería pensar en estas cosas.[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0]Bueno, Navidad solo es una vez al año, así que toca disfrutarla.[n][w][e]

[msg MSG_198_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5077 0 0]¿Cómo habrá pasado Ryoji las Navidades?[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]¿Habrá estado con chicas y se lo habrá pasado bien?[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0]¿O tal vez se las habrá pasado llorando y solo, como la última vez que le vimos?[n][w][e]

[sel SEL_199_0_0 top]
[f 2 1]Seguro que se lo pasó bien.[e]
[f 2 1]Puede que haya llorado.[e]

[msg MSG_200_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5028 0 0]Sí, espero que tengas razón...[n][w][e]

[msg MSG_201_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5084 0 0]No me puedo creer que estemos considerando la idea de matar...[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0]Tenemos que mantenernos firmes.[n][w][e]

[msg MSG_202_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5063 0 0]Leí que el miedo es una reacción emocional que se activa para que huyamos del peligro.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Pero nada va a cambiar si siempre huimos de aquello a lo que tememos.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Tenemos que enfrentarnos a nuestros miedos para encontrar la forma de sobrevivir.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5081 0 0][nl]... Está decidido...[n][w][e]

[msg MSG_202_1_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5113 0 0]Solo quedan tres días...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]No han desaparecido mis miedos, pero... me siento en calma, por alguna razón.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Creo que es porque estáis todos aquí conmigo.[n][w][e]

[msg MSG_203_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5074 0 0]Dicen que Aigis ha vuelto porque ya está totalmente arreglada...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Pero algo me dice que no ha sido solo una reparación.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Creo que ha vuelto siendo una persona completamente diferente.[n][w][e]

[msg MSG_204_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 3 0 65535 5063 0 0]Yo ya tengo mi respuesta. Voy a seguir adelante...[n][w][e]

[msg MSG_205_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5075 0 0]Me da muchísimo miedo la Caída, pero... la determinación que siento para afrontarla es más fuerte que mi temor.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Espero que los demás piensen lo mismo.[n][w][e]

[msg MSG_206_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 3 0 65535 5005 0 0]Es como si cada Año Nuevo trajera nuevos comienzos.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]¡Emplearé la energía que acabo de descubrir en esforzarme por traer de nuevo la paz a la ciudad![n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Así que, eh... ¡Hagamos que este año sea mejor![n][w][e]

[msg MSG_207_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5062 0 0]He oído que la secta se reunió hace poco.[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0]¿Tenía que ser justo después de Año Nuevo? Espero que la gente no piense nada raro...[n][w][e]

[msg MSG_208_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5074 0 0]La secta sigue predicando sobre la salvación y la liberación...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Pero el significado de la salvación varía de una persona a otra.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Hay quien desea riquezas, quien solo compra lo que necesita, quien desea la paz mundial...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]¿Qué creerá esta secta que será su salvación?[n][w][e]

[msg MSG_209_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5090 0 0]Tal como se esperaba, la influencia de la secta ha llegado al instituto...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Algunos parecen ya fervientes devotos.[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0]Hay que hacer algo con Nix.[n][w][e]

[msg MSG_211_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5071 0 0]Creer en la secta o no es una decisión de índole personal.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Yo, por mi parte, nunca creería.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Cuando pienso en mi amistad con Natsuki, siento que no me hace falta estar en ninguna secta.[n][w][e]

[msg MSG_212_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6058 0 0]Los vínculos de amistad...[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0]Aunque suene a tópico, creo que la capacidad de forjar vínculos es lo más hermoso del ser humano.[n][w][e]

[msg MSG_213_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 3 0 65535 1025 0 0]Al final, lo más importante es el vínculo que se crea entre las personas.[n][w][e]

[msg MSG_214_0_0 [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0][vp 3 0 65535 2009 0 0]Así es... No importa cuánto poder tengas, nadie puede sobrevivir solo.[n][w][e]

[msg MSG_215_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5070 0 0]He visto el nombre de usuario "Jin" antes...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Es muy popular y recibe mucho apoyo de sus seguidores. Se trata de un personaje muy carismático.[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0]No puedo creer que sea el mismo Jin de Strega...[n][w][e]

[msg MSG_215_1_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5001 0 0]El tiempo pasa volando...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Pasemos los dieciocho días que quedan sin arrepentimientos.[n][w][e]

[msg MSG_216_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5004 0 0]Siempre que veo a los seguidores de la secta...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Me recuerda que de ninguna manera podría ser devota de algo así.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Y aunque me acabara dejando convencer, la voz de Natsuki me devolvería a mis cabales.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5068 0 0]Ojalá todo el mundo pudiera forjar un fuerte vínculo con alguien. Así nadie acudiría a esta secta.[n][w][e]

[msg MSG_218_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0][vp 3 0 65535 5134 0 0]Snif, snif.[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0]Lo siento... Cada vez que recuerdo lo que ha pasado hoy, rompo a llorar.[n][w][e]

[msg MSG_219_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 3 0 65535 5078 0 0]¿Te acuerdas de cuando pedimos sushi? Pues Korocito fue el único que no lo probó.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Así que he preparado una cena especial solo para Korocito.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Espero que lo ayude a fortalecerse y que le guste, por supuesto.[n][w][e]

[msg MSG_220_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5074 0 0]Dentro de nada tendremos la charla de orientación laboral. Quiero ir a la uni...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]No ha sido una decisión difícil. Es que, aparte de estudiar, no se me ocurre otra cosa que pueda hacer.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Pero no es una decisión que haya elegido por el bien de mi propio futuro, ¿o sí...?[n][w][e]

[sel SEL_221_0_0 top]
[f 2 1]Quizá.[e]
[f 2 1]Eso no es verdad.[e]
[f 2 1]Ni idea.[e]

[msg MSG_222_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5062 0 0]Mmm, quizá deba pensarlo mejor. Debería ampliar mis horizontes.[n][w][e]

[msg MSG_223_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5060 0 0]Bueno, por ahora no pasa nada, pero tendré que decidirme algún día.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Tengo que ampliar mis perspectivas de futuro.[n][w][e]

[msg MSG_224_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5025 0 0]Sé que somos libres de elegir nuestro camino, pero eso solo hace que cueste aún más decidirnos...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Las posibilidades son infinitas.[n][w][e]

[msg MSG_224_5_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5062 0 0]Quizá no sea demasiado tarde para empezar a investigar y entrevistar a gente.[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0]Estaría bien tener muchas opciones, sobre todo porque soy la única que puede decidir qué hacer con mi futuro.[n][w][e]

[msg MSG_230_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5081 0 0]La verdad es que entiendo cómo se siente Junpei.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Todo se te hace un mundo si te pones a pensar que esta será la última vez que haces algo...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Esto es un poco triste.[n][w][e]

[sel SEL_231_0_0 top]
[f 2 1]Sí, así es.[e]
[f 2 1]Para nada.[e]

[msg MSG_232_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 3 0 65535 5029 0 0]¿Verdad? Me hace querer proteger aún más los preciosos momentos de nuestra vida cotidiana.[n][w][e]

[msg MSG_233_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0][vp 3 0 65535 5049 0 0]Ah, entiendo... No eres lo que se dice una sentimental.[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0]Pero seguro que ambas sentimos que tenemos que proteger nuestra vida cotidiana, ¿verdad?[n][w][e]

[msg MSG_234_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5075 0 0]Ahora mismo, Natsuki está en algún lugar lejos de aquí, haciendo todo lo que puede.[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0]Eso me da fuerzas para seguir adelante y no rendirme nunca.[n][w][e]

[msg MSG_0131_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5061 0 0]Estaba revisando todo para prepararme para esta noche cuando Aigis me sacó a tomar el aire.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Creo que seguiré después de tomarme un descanso.[n][w][e]

[sel SEL_0131_1_0 top]
[f 2 1]Intenta no forzarte demasiado.[e]
[f 2 1]Confiamos en ti.[e]

[msg MSG_0131_2_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 3 0 65535 5039 0 0]Je, je. Gracias. Tengo a Aigis conmigo, así que estaré bien.[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0]Ya que no puedo luchar en primera línea de batalla, quiero ayudar en lo máximo posible.[n][w][e]

[msg MSG_0131_3_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 3 0 65535 5025 0 0]¡Mm! ¡Tú déjamelo a mí![n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0]Gracias a los esfuerzos que hacéis todos, puedo centrarme en lo que hago.[n][w][e]

[msg MSG_235_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 52 65535 0 0][vp 3 0 65535 5008 0 0]Si el mundo acaba, nuestros lazos de amistad también desaparecerán. Y no quiero que eso ocurra.[n][w][e]
[f 2 1][bup 6 0 52 65535 0 0]Todavía hay mucha gente a la que quiero conocer y con la que quiero entablar amistad.[n][w][e]
[f 2 1][bup 6 0 52 65535 0 0]Por eso no permitiré que el mundo se acabe hoy.[n][w][e]

[msg MSG_236_0_0 [Fuuka Yamagishi]]

[sel SEL_237_0_0 top]
[f 2 1]Es algo estupendo.[e]
[f 2 1]Piensa en ti primero.[e]

[msg MSG_238_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0]Siento que es mi deber...[n][w][e]

[msg MSG_239_0_0 [Fuuka Yamagishi]]

