[msg MND_000_0_0]
[f 2 1]El santuario está atestado de gente[n]que disfruta del festival.[n][w][e]
[f 2 1]Me siento un poco sola al no tener compañía...[n][w][e]

[msg MSG_001_0_0 [Aigis]]
[f 2 1][bup 7 0 156 65535 0 0][vp 1 0 0 1 0 0]¡¿Qué son esas cosas?![n][w][e]

[msg MSG_002_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 156 65535 0 0][vp 1 0 0 2 0 0]Son máscaras. Se ponen en la cara como forma de esparcimiento.[n][w][e]

[msg MSG_003_0_0 [Aigis]]
[f 2 1][bup 7 0 156 65535 0 0][vp 1 0 0 3 0 0]¿Se puede uno divertir ocultando la cara?[n][w][e]

[msg MSG_004_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 156 65535 0 0][vp 1 0 0 4 0 0]El objetivo no es precisamente ocultar la cara, sino más bien disfrutar de tener una diferente.[n][w][e]
[f 2 1][bup 5 0 156 65535 0 0][vp 1 0 0 5 0 0]Mm... Es difícil explicar algo así...[n][w][e]

[msg MSG_005_0_0 [Aigis]]
[f 2 1][bup 7 0 156 65535 0 0][vp 1 0 0 6 0 0]Entonces, al llevar una cara diferente, ¿puedes convertirte en una versión diferente de ti mismo?[n][w][e]

[msg MSG_006_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 4 156 65535 0 0][vp 1 0 0 7 0 0]Sí, exacto. Lo cierto es que tu nivel de comprensión es realmente impresionante.[n][w][e]
[f 2 1][bup 5 0 156 65535 0 0][vp 1 0 0 8 0 0][f 4 23 0 5 0 25 25]A este paso, tras algunas pruebas más, el director te podría dar permiso para salir por tu cuenta.[n][w][e]

[msg MSG_007_0_0 [Aigis]]
[f 2 1][bup 7 0 156 65535 0 0][vp 1 0 0 9 0 0]Estoy deseando que llegue ese día.[n][w][e]

[msg MND_008_0_0]
[f 2 1]Continúan hablando...[n][w][e]

[sel SEL_009_0_0 top]
[f 2 1]Llamar[e]
[f 2 1]...[e]

[msg MND_010_0_0]
[f 2 1]Parece que no me han escuchado.[n][w][e]

[msg MND_011_0_0]
[f 2 1]Tras dar una vuelta más,[n]he decidido volver a la residencia.[n][w][e]

