[msg MSG_000_0_0 [Asesor del equipo de atletismo]]
[f 2 1][vp 1 0 6 1 17 0]Ah, [nl]. Te estaba buscando.[n][w][e]
[f 2 1][vp 1 0 6 2 17 0]Ha llegado esto para ti. Es de Hayase.[n][w][e]
[f 2 1][vp 1 0 6 3 17 0]Seguro que su instituto lamenta que se haya ido. Como atleta era un diez.[n][w][e]
[f 2 1][vp 1 0 6 4 17 0]Pero para nosotros son buenas noticias, ¡porque nada nos entorpece el camino hacia la victoria![n][w][e]
[f 2 1][vp 1 0 6 5 17 0]Bueno, nos vemos.[n][w][e]

[msg MND_001_0_0]
[f 2 1]He recibido una carta de Hayase.[n][w][e]
[f 2 1]Será mejor que la lea.[n][w][e]

