[msg MSG_000_0_0 [Anciano jovial]]
[f 2 1][f 5 21 1 400]Mires donde mires, siempre hay parejitas.[n][w][e]
[f 2 1][f 5 21 1 400]Bueno, ¿a qué esperas? ¡Encuentra a alguien ya![n][w][e]
[f 2 1][f 5 21 1 400]Aún eres joven. No tienes excusa para no encontrar a tu media naranja.[n][w][e]

[msg MSG_001_0_0 [Anciano jovial]]
[f 2 1][f 5 21 1 400]Conoces la cafetería Chagall, ¿no? Esa que es tan elegante.[n][w][e]
[f 2 1][f 5 21 1 400]Hay un club al lado... Un sitio algo más "maduro" para quedar, supongo.[n][w][e]
[f 2 1][f 5 21 1 400]No termino de ver con buenos ojos esa clase de sitios, pero tampoco soy quién para decirte lo que debes hacer.[n][w][e]

[msg MSG_002_0_0 [Anciano jovial]]
[f 2 1][f 5 21 1 400]Parece como si a esos jovenzuelos les hubieran robado el alma.[n][w][e]
[f 2 1][f 5 21 1 400]Ya les vale, siempre haciendo el vago. ¡Deberían salir, hacer amigos y disfrutar de la vida![n][w][e]

[msg MSG_003_0_0 [Anciano jovial]]
[f 2 1][f 5 21 1 400]Estos sitios me traen recuerdos.[n][w][e]
[f 2 1][f 5 21 1 400]Las salas de baile... ¡Las llamábamos tugurios! Siempre estaban a rebosar de gente.[n][w][e]
[f 2 1][f 5 21 1 400]Ahí es donde le robé el corazón a mi esposa, ¡en una sala de baile! Estaba hecho una gacela.[n][w][e]

[msg MSG_004_0_0 [Anciano jovial]]
[f 2 1][f 5 21 1 400]He oído que "Escapade" significa "travesura" en inglés.[n][w][e]
[f 2 1][f 5 21 1 400]A juzgar por el lugar, diría que significa "quédate despierto toda la noche y móntate un buen guateque".[n][w][e]

[msg MSG_005_0_0 [Anciano jovial]]
[f 2 1][f 5 21 1 400]Cuando tenía tu edad conocí a un tipo que es sepulturero.[n][w][e]
[f 2 1][f 5 21 1 400]Me dijo: "Cuando te mueras, te voy a hacer una tumba preciosa".[n][w][e]
[f 2 1][f 5 21 1 400]Qué detalle por su parte. De verdad que los buenos amigos son una bendición.[n][w][e]

[msg MSG_006_0_0 [Anciano jovial]]
[f 2 1][f 5 21 1 400]Los tiempos han cambiado, pero las historias de fantasmas que se cuentan en las escuelas nunca pasan de moda.[n][w][e]
[f 2 1][f 5 21 1 400]Yo me colaba en el instituto por las noches. Menudas broncas me echaban los profesores.[n][w][e]

[msg MSG_007_0_0 [Anciano jovial]]
[f 2 1][f 5 21 1 400]Oye, ¿qué se baila ahora en las discotecas? ¿Reggae? ¿Esa porquería a la que llaman "rap"?[n][w][e]
[f 2 1][f 5 21 1 400]En mi época era el tango o el swing. Uno iba a bailar con su chica, no a exhibirse.[n][w][e]
[f 2 1][f 5 21 1 400]Me enamoré a primera vista de mi mujer en una de esas salas.[n][w][e]

[msg MSG_008_0_0 [Anciano jovial]]
[f 2 1][f 5 21 1 400]Esa misteriosa apatía que afecta a las parejas está aumentando. ¿Tienes novio?[n][w][e]
[f 2 1][f 5 21 1 400]Los hombres han de luchar por sus mujeres, aunque tengan las de perder.[n][w][e]
[f 2 1][f 5 21 1 400]Me enorgullezco de poder decir que yo hice lo propio en mis tiempos.[n][w][e]

[msg MSG_009_0_0 [Anciano jovial]]
[f 2 1][f 5 21 1 400]He oído que ahora hay unos chanchullos raros en el internete ese.[n][w][e]
[f 2 1][f 5 21 1 400]¿Cómo te quedas? Para ser un viejo, estoy en la onda, ¿eh?[n][w][e]

[msg MSG_010_0_0 [Anciano jovial]]
[f 2 1][f 5 21 1 400]Estás de vacaciones, ¿no? Se supone que los jóvenes tenéis que salir y pasároslo en grande.[n][w][e]
[f 2 1][f 5 21 1 400]Eres joven, tienes tiempo de sobra para cometer errores. Al final, serán unos bonitos recuerdos.[n][w][e]

[msg MSG_011_0_0 [Anciano jovial]]
[f 2 1][f 5 21 1 400]Me gusta pasear por la estación, y a veces veo a una chica muy peculiar.[n][w][e]
[f 2 1][f 5 21 1 400]Que no te asuste lo que te voy a decir, pero... ¡tiene una espada atravesada en la cabeza![n][w][e]
[f 2 1][f 5 21 1 400]Ya sé que a las jóvenes les gustan los pendientes, pero... ¿por toda la cabeza?[n][w][e]
[f 2 1][f 5 21 1 400]¿Eh? ¿Crees que era una especie de truco? Bueno, si lo era, está claro que he picado.[n][w][e]

[msg MSG_012_0_0 [Anciano jovial]]
[f 2 1][f 5 21 1 400]En verano las chicas enseñan más carne para atraer las miradas de los chicos.[n][w][e]
[f 2 1][f 5 21 1 400]Me recuerda a la época en la que me echaba una novia en verano y rompíamos antes del otoño.[n][w][e]

[msg MSG_013_0_0 [Anciano jovial]]
[f 2 1][f 5 21 1 400]Hay mucha gente rara por ahí, como el joven al que vi el otro día.[n][w][e]
[f 2 1][f 5 21 1 400]Me he dado cuenta de que hay un hueco en la marabunta de gente caminando.[n][w][e]
[f 2 1][f 5 21 1 400]Me preguntaba por qué, así que eché un vistazo y entonces entendí por qué nadie pasaba por ahí.[n][w][e]
[f 2 1][f 5 21 1 400]Había un chico sin camiseta y con el pelo largo y gris. Tenía un aura extraña.[n][w][e]
[f 2 1][f 5 21 1 400]Y yo te pregunto, ¿adónde vamos a llegar en este mundo?[n][w][e]

[msg MSG_014_0_0 [Anciano jovial]]
[f 2 1][f 5 21 1 400]Entonces, han cancelado el festival cultural por el tifón, ¿no? Qué pena.[n][w][e]
[f 2 1][f 5 21 1 400]Pero no os pongáis tristes. Los jóvenes tenéis toda la vida por delante, así que podéis esperar hasta el próximo.[n][w][e]

[msg MSG_015_0_0 [Anciano jovial]]
[f 2 1][f 5 21 1 400]Tengo un amigo al que conozco desde que íbamos en pañales. Canta de maravilla.[n][w][e]
[f 2 1][f 5 21 1 400]Me dijo: "Si mueres, cantaré en tu entierro".[n][w][e]
[f 2 1][f 5 21 1 400]Qué detalle por su parte. Nos conocemos desde hace mucho.[n][w][e]

[msg MSG_016_0_0 [Anciano jovial]]
[f 2 1][f 5 21 1 400]Los jóvenes con cara de deprimidos deberían poner más ímpetu en hacer amigos.[n][w][e]
[f 2 1][f 5 21 1 400]Están todo el día en la "red" esa. Seguro que no saben ni hablar con las personas de la vida real.[n][w][e]

[msg MSG_017_0_0 [Anciano jovial]]
[f 2 1][f 5 21 1 400]En esta época, la gente que no tiene pareja se siente muy sola. Yo le echo la culpa al frío.[n][w][e]
[f 2 1][f 5 21 1 400]Pero no te pongas de repente a picar de flor en flor, porque te meterás en un buen lío.[n][w][e]

[msg MSG_018_0_0 [Anciano jovial]]
[f 2 1][f 5 21 1 400]No te lo pienses dos veces y disfruta en las discotecas. ¡Conocerás a gente nueva![n][w][e]
[f 2 1][f 5 21 1 400]Tú ponte a mover el esqueleto, aunque les dé rabia a los mojigatos de la AMPA.[n][w][e]

[msg MSG_019_0_0 [Anciano jovial]]
[f 2 1][f 5 21 1 400]Ha muerto un amigo mío... Siempre quiso ser astronauta.[n][w][e]
[f 2 1][f 5 21 1 400]Me dijo: "Aunque muera, siempre cuidaré de ti".[n][w][e]
[f 2 1][f 5 21 1 400]Me acuerdo de él cada vez que miro el cielo por la noche. En mi corazón, es un gran astronauta.[n][w][e]

[msg MSG_020_0_0 [Anciano jovial]]
[f 2 1][f 5 21 1 400]En Año Nuevo, siempre me reúno con mis viejos amigos del instituto para tomar sake.[n][w][e]
[f 2 1][f 5 21 1 400]Pero cada año aparecemos menos. A mi edad, es inevitable.[n][w][e]

[msg MSG_021_0_0 [Anciano jovial]]
[f 2 1][f 5 21 1 400]Aunque el correo electrónico esté de moda, a mí me encanta recibir postales de felicitación de Año Nuevo.[n][w][e]
[f 2 1][f 5 21 1 400]¿Tú les envías postales a tus amigos?[n][w][e]

[sel SEL_022_0_0 top]
[f 2 1]Sí.[e]
[f 2 1]No.[e]

[msg MSG_023_0_0 [Anciano jovial]]
[f 2 1][f 5 21 1 400]¿Has oído el dicho "Haz nuevos amigos, pero conserva a los viejos; unos son de plata y los otros, de oro"?[n][w][e]

[msg MSG_024_0_0 [Anciano jovial]]
[f 2 1][f 5 21 1 400]¿A tu edad? Qué deprimente.[n][w][e]
[f 2 1][f 5 21 1 400]Entonces, tu propósito de año nuevo debería ser conocer a gente nueva.[n][w][e]

[msg MSG_025_0_0 [Anciano jovial]]
[f 2 1][f 5 21 1 400]Parece que es lo que hay que hacer para unirse a esa secta.[n][w][e]
[f 2 1][f 5 21 1 400]Pero ¿por qué nadie trata de impedir que cometan semejantes estupideces?[n][w][e]

[msg MSG_026_0_0 [Anciano jovial]]
[f 2 1][f 5 21 1 400]Te preocupas porque te desconcierta, y te desconcierta porque no sabes en qué creer.[n][w][e]
[f 2 1][f 5 21 1 400]Los humanos somos criaturas débiles. Nos cuesta valernos por nosotros mismos.[n][w][e]
[f 2 1][f 5 21 1 400]El consejo que os doy a los jóvenes es que hagáis amigos y confiéis en ellos con todo vuestro ser.[n][w][e]

