[msg MSG_000_0_0 [Kazushi Miyamoto]]
[f 2 1][bup 105 0 101 65535 0 0][vp 3 0 65535 10887 0 0]Supongo que doy el cante que no veas. A lo mejor no tendría que haberme puesto chándal...[n][w][e]
[f 2 1][bup 105 0 101 65535 0 0]Bueh, me lo tomaré como parte de mi entrenamiento mental.[n][w][e]

[msg MSG_001_0_0 [Kazushi Miyamoto]]
[f 2 1][bup 105 0 101 65535 0 0]Es raro mencionar esto, pero, eh... A ver cómo te lo digo...[n][w][e]
[f 2 1][bup 105 0 101 65535 0 0]Me desmorono bajo presión. Me pongo muy nervioso. Aunque últimamente lo llevo mucho mejor.[n][w][e]

[msg MSG_002_0_0 [Kazushi Miyamoto]]
[f 2 1][bup 105 0 101 65535 0 0][vp 3 0 65535 10871 0 0]Cuantas más ganas tengo de ganar, más tenso me pongo.[n][w][e]

[sel SEL_003_0_0 top]
[f 2 1]Es parte de quién eres.[e]
[f 2 1]Puedes superarlo.[e]
[f 2 1]Ganar no lo es todo.[e]

[msg MSG_004_0_0 [Kazushi Miyamoto]]
[f 2 1][bup 105 3 101 65535 0 0][vp 3 0 65535 10828 0 0]Pero si no intentas superar tu debilidad, ¿no es como si huyeras?[n][w][e]
[f 2 1][bup 105 3 101 65535 0 0]¿Sabes que a veces una retirada a tiempo es una victoria? Pues ese no es mi estilo.[n][w][e]

[msg MND_005_0_0]
[f 2 1]Miyamoto se ha amargado.[n][w][e]
[f 2 1]Siento que hoy nuestra relación no ha cambiado nada...[n][w][e]

[msg MSG_006_0_0 [Kazushi Miyamoto]]
[f 2 1][bup 105 1 101 65535 0 0][vp 3 0 65535 10820 0 0][f 5 13 8 15 105]Sí, ¡tienes razón! Quejándome no voy a superarlo. ¡Solo lo lograré con fuerza de voluntad mental![n][w][e]
[f 2 1][bup 105 3 101 65535 0 0][f 4 23 0 105 3 25 25]De hecho, no sé, tía. Quizá eso no sea suficiente esta vez. ¿Qué se me escapa?[n][w][e]

[msg MND_007_0_0]
[f 2 1]Miyamoto está ensimismado.[n][w][e]
[f 2 1]Hoy he aprendido un poco más sobre él.[n][w][e]

[msg MSG_008_0_0 [Kazushi Miyamoto]]
[f 2 1][bup 105 0 101 65535 0 0][vp 3 0 65535 10850 0 0][f 5 13 8 30 105]Entonces, ¿me estás diciendo que no piense en ello? No sé si puedo.[n][w][e]
[f 2 1][bup 105 1 101 65535 0 0][f 4 23 0 105 1 25 25]Pero entiendo a dónde quieres llegar. Es bastante profundo.[n][w][e]

[msg MND_009_0_0]
[f 2 1]Miyamoto parece impresionado.[n][w][e]
[f 2 1]Siento que hoy nuestra relación se ha estrechado.[n][w][e]

[msg MSG_010_0_0 [Kazushi Miyamoto]]
[f 2 1][bup 105 0 101 65535 0 0][vp 3 0 65535 10883 0 0]Pero ojalá se dieran prisa y me dijeran que le pasa a mi rodilla. La intriga me está matando.[n][w][e]
[f 2 1][bup 105 1 101 65535 0 0][f 4 23 0 105 1 25 25]Hoy me encuentro bastante bien. A lo mejor corro un poco de camino a casa.[n][w][e]

[msg MND_011_0_0]
[f 2 1]Tras despedirme de Miyamoto, he decidido volver a la residencia.[n][w][e]

