[msg TRL_000_0_0 [Echar un vistazo]]
[f 2 1][f 4 8 0]Usa [f 1 3 121] para girar la cámara. Si pulsas [f 1 3 119], la cámara se colocará detrás de la protagonista.[n][w][e]

[msg TRL_001_0_0 [Echar un vistazo]]
[f 2 1][f 4 8 0]Mantén pulsado [f 1 3 104] para colocar la cámara más cerca de la protagonista. Si pulsas [f 1 3 105], la cámara volverá a su estado predeterminado.[n][w][e]

[msg TRL_002_0_0 [Echar un vistazo]]
[f 2 1][f 4 8 0]En determinados lugares, la cámara se quedará fija.[n][w][e]

[msg TRL_003_0_0 [Echar un vistazo]]
[f 2 1][f 4 8 0]Cuando sea posible, usar la cámara te ayudará a ver bien lo que te rodea.[n][w][e]

