[msg MSG_PRF_DUMMY_NAME]
[f 2 1]ダミー：ふりがな[n][w][e]

[msg MSG_PRF_DUMMY]
[f 2 1]ダミーのプロフィール[n][w][e]

[msg MSG_PRF_SEES_NAME]
[f 2 1]SEES[n][w][e]

[msg MSG_PRF_SEES]
[f 2 1]También conocida como la "Sociedad extraescolar de ejecución de sombras". Oficialmente, es un club escolar.[n][w][e]

[msg MSG_PRF_YUKARI_NAME]
[f 2 1]Yukari Takeba[n][w][e]

[msg MSG_PRF_YUKARI]
[f 2 1]Compañera de segundo del Instituto Gekkoukan, de la clase F. Miembro del club de tiro con arco.[n][w][e]

[msg MSG_PRF_YUKARI_REVERSE]
[f 2 1]Alumna de segundo del Instituto Gekkoukan, de la clase F. Miembro del club de tiro con arco. Ahora mismo, nuestra relación es algo rara.[n][w][e]

[msg MSG_PRF_JUNPEI_NAME]
[f 2 1]Junpei Iori[n][w][e]

[msg MSG_PRF_JUNPEI]
[f 2 1]Compañero de segundo del Instituto Gekkoukan, de la clase F. No está en ningún club.[n][w][e]

[msg MSG_PRF_AKIHIKO_NAME]
[f 2 1]Akihiko Sanada[n][w][e]

[msg MSG_PRF_AKIHIKO]
[f 2 1]Alumno de tercero del Gekkoukan, de la clase C. Capitán del equipo de boxeo, invicto. Saca notas impecables y es popular entre las chicas.[n][w][e]

[msg MSG_PRF_MITSURU_NAME]
[f 2 1]Mitsuru Kirijo[n][w][e]

[msg MSG_PRF_MITSURU]
[f 2 1]Alumna de tercero del Instituto Gekkoukan, de la clase D. Es miembro del equipo de esgrima y presidenta del consejo estudiantil.[n][w][e]

[msg MSG_PRF_FUKA_NAME]
[f 2 1]Fuuka Yamagishi[n][w][e]

[msg MSG_PRF_FUKA]
[f 2 1]Alumna de segundo del Instituto Gekkoukan, de la clase E. Miembro del club de arte. Es introvertida y tímida.[n][w][e]

[msg MSG_PRF_KEN_NAME]
[f 2 1]Ken Amada[n][w][e]

[msg MSG_PRF_KEN]
[f 2 1]Un alumno de quinto de primaria del Gekkoukan. Lleva viviendo en la residencia desde que su madre falleció en un accidente hace dos años.[n][w][e]

[msg MSG_PRF_KOROMARU_NAME]
[f 2 1]Koromaru[n][w][e]

[msg MSG_PRF_KOROMARU]
[f 2 1]Un shiba inu albino con pelaje blanco y ojos rojos. Su dueño era el sacerdote del santuario Naganaki.[n][w][e]

[msg MSG_PRF_SHINJIRO_NAME]
[f 2 1]Shinjiro Aragaki[n][w][e]

[msg MSG_PRF_SHINJIRO]
[f 2 1]Alumno de tercero del Instituto Gekkoukan, de la clase C. Uno de los primeros miembros de SEES y viejo amigo de Akihiko Sanada.[n][w][e]

[msg MSG_PRF_AEGIS_NAME]
[f 2 1]Aigis[n][w][e]

[msg MSG_PRF_AEGIS]
[f 2 1]Un arma antisombras creada por el Grupo Kirijo. Está catalogada como el modelo de séptima generación y lleva implantada la Pluma crepuscular.[n][w][e]

[msg MSG_PRF_TOMOCHIKA_NAME]
[f 2 1]Kenji Tomochika[n][w][e]

[msg MSG_PRF_TOMOCHIKA]
[f 2 1]Compañero de segundo del Instituto Gekkoukan, de la clase F. Es alegre y le gustan las mujeres mayores.[n][w][e]

[msg MSG_PRF_ODAGIRI_NAME]
[f 2 1]Hidetoshi Odagiri[n][w][e]

[msg MSG_PRF_ODAGIRI]
[f 2 1]Alumno de segundo del Gekkoukan. Miembro del comité disciplinario del consejo estudiantil. No es muy popular en el instituto.[n][w][e]

[msg MSG_PRF_BUNKICHI_NAME]
[f 2 1]Bunkichi Kitamura[n][w][e]

[msg MSG_PRF_BUNKICHI]
[f 2 1]Se encarga de la librería "Bookworms" con su mujer en la zona de tiendas de Iwatodai. Cumplió 80 este año. Su relación con su mujer es excelente.[n][w][e]

[msg MSG_PRF_BUN_MISSING]
[f 2 1]Se encarga de la librería "Bookworms" con su mujer en la zona de tiendas de Iwatodai. Cumplió 80 este año. Ha desaparecido hace poco.[n][w][e]

[msg MSG_PRF_BUN_LOST]
[f 2 1]Se encarga de la librería "Bookworms" con su mujer en la zona de tiendas de Iwatodai. Cumplió 80 este año. Ha desaparecido.[n][w][e]

[msg MSG_PRF_MITSUKO_NAME]
[f 2 1]Mitsuko Kitamura[n][w][e]

[msg MSG_PRF_MITSUKO]
[f 2 1]Se encarga de la librería "Bookworms" con su marido en la zona de tiendas de Iwatodai. Cumplió 72 este año.[n][w][e]

[msg MSG_PRF_MIT_MISSING]
[f 2 1]Se encarga de la librería "Bookworms" con su marido en la zona de tiendas de Iwatodai. Cumplió 72 este año. Su marido ha desaparecido.[n][w][e]

[msg MSG_PRF_MIT_LOST]
[f 2 1]Se encarga de la librería "Bookworms" con su marido en la zona de tiendas de Iwatodai. Cumplió 72 este año. La tienda está en silencio sin su marido...[n][w][e]

[msg MSG_PRF_MIYAMOTO_NAME]
[f 2 1]Kazushi Miyamoto[n][w][e]

[msg MSG_PRF_MIYAMOTO]
[f 2 1]Compañero de segundo del Instituto Gekkoukan, de la clase F. Es compañero de atletismo y candidato a capitán del equipo.[n][w][e]

[msg MSG_PRF_FUSIMI_NAME]
[f 2 1]Chihiro Fushimi[n][w][e]

[msg MSG_PRF_FUSIMI]
[f 2 1]Alumna de primer año del Instituto Gekkoukan. La nombraron tesorera del consejo estudiantil, pero no se le dan bien las mates.[n][w][e]

[msg MSG_PRF_FUSIMI_REVERSE]
[f 2 1]Alumna de primer año del Instituto Gekkoukan. La nombraron tesorera del consejo estudiantil. Es muy raro todo.[n][w][e]

[msg MSG_PRF_INTERNET_NAME]
[f 2 1]Maya[n][w][e]

[msg MSG_PRF_INTERNET]
[f 2 1]Una amiga del juego "Innocent Sin Online". Su avatar es una mujer vestida de rojo.[n][w][e]

[msg MSG_PRF_HIRAGA_NAME]
[f 2 1]Keisuke Hiraga[n][w][e]

[msg MSG_PRF_HIRAGA]
[f 2 1]Alumno de tercero del Instituto Gekkoukan. Presidente del club de arte. Tiene un amplio conocimiento médico.[n][w][e]

[msg MSG_PRF_NISHIWAKI_NAME]
[f 2 1]Yuko Nishiwaki[n][w][e]

[msg MSG_PRF_NISHIWAKI]
[f 2 1]Alumna de segundo del Instituto Gekkoukan. Es la encargada del equipo de atletismo y amiga de la infancia de Kazushi Miyamoto.[n][w][e]

[msg MSG_PRF_MAIKO_NAME]
[f 2 1]Maiko Oohashi[n][w][e]

[msg MSG_PRF_MAIKO]
[f 2 1]Una alumna de primaria que conocí en el santuario Naganaki. Como sus dos padres trabajan, suele estar sola después de clase.[n][w][e]

[msg MSG_PRF_MAIKO_MISSING]
[f 2 1]Una alumna de primaria que conocí en el santuario Naganaki. Suele estar en el parque después de clase, pero por lo visto, ha desaparecido.[n][w][e]

[msg MSG_PRF_MAIKO_LOST]
[f 2 1]Una alumna de primaria que conocí en el santuario Naganaki. Suele estar en el parque después de clase, pero por lo visto, ha desaparecido.[n][w][e]

[msg MSG_PRF_PHAROS_NAME]
[f 2 1]Pharos[n][w][e]

[msg MSG_PRF_PHAROS]
[f 2 1]Un chico que suele aparecer ante [f 4 3] con mensajes crípticos.[n][w][e]

[msg MSG_PRF_BEBE_NAME]
[f 2 1]Bebe[n][w][e]

[msg MSG_PRF_BEBE]
[f 2 1]Un estudiante de intercambio francés que adora Japón. Miembro del club de moda. Nombre completo: André Laurent Jean Geraux.[n][w][e]

[msg MSG_PRF_TANAKA_NAME]
[f 2 1]Presidente Tanaka[n][w][e]

[msg MSG_PRF_TANAKA]
[f 2 1]Conocido por promocionar productos personalmente en su programa de teletienda. Presidente de "Los increíbles artículos de Tanaka".[n][w][e]

[msg MSG_PRF_MUTATSU_NAME]
[f 2 1]Mutatsu[n][w][e]

[msg MSG_PRF_MUTATSU]
[f 2 1]Un monje poco ortodoxo que conocí en el Escapade. Le encanta beber y fumar.[n][w][e]

[msg MSG_PRF_HAYASE_NAME]
[f 2 1]Mamoru Hayase[n][w][e]

[msg MSG_PRF_HAYASE]
[f 2 1]El as del equipo de atletismo de otro instituto que participó en la copa Myouou. Conocido por su velocidad, tanto al correr como al comer.[n][w][e]

[msg MSG_PRF_SUEMITSU_NAME]
[f 2 1]Nozomi Suemitsu[n][w][e]

[msg MSG_PRF_SUEMITSU]
[f 2 1]Alumno de tercero del Gekkoukan con un apetito voraz conocido como el Rey gourmet. Conoce hasta los platos fuera de carta de la zona.[n][w][e]

[msg MSG_PRF_KAMIKI_NAME]
[f 2 1]Akinari Kamiki[n][w][e]

[msg MSG_PRF_KAMIKI]
[f 2 1]Joven que suele sentarse en los bancos del santuario Naganaki. Por lo visto, sufre una enfermedad terminal. Conoce a Maiko Oohashi.[n][w][e]

[msg MSG_PRF_SEES2_NAME]
[f 2 1]Equipo de aniquilación de Nix[n][w][e]

[msg MSG_PRF_SEES2]
[f 2 1]Los antiguos miembros de SEES que se oponen a Nix, con [f 4 3] como líder.[n][w][e]

