[msg MSG_000_0_0 [Mutatsu]]
[f 2 1][bup 114 30 65535 65535 1 0][vp 1 0 0 1 0 0]Eh, llegas tarde... ¿Qué te ha pasado?[n][w][e]

[msg MND_001_0_0]
[f 2 1]Mutatsu apesta más a alcohol que de normal...[n][w][e]
[f 2 1]Debe de haber estado bebiendo un montón.[n][w][e]

[msg MSG_002_0_0 [Mutatsu]]
[f 2 1][bup 114 30 65535 65535 1 0][vp 1 0 0 2 0 0]¿No crees que es *hip* maleducado hacer eshperar?[n][w][e]

[msg MSG_002_5_0 [Mutatsu]]
[f 2 1][bup 114 2 65535 65535 1 0][vp 1 0 0 3 0 0][f 4 23 0 114 2 25 25]¿No te ha dicho papá que no hagash eso?[n][w][e]

[sel SEL_003_0_0 top]
[f 2 1]¿Papá?[e]
[f 2 1]Es la primera vez que lo oigo.[e]
[f 2 1]...[e]

[msg MSG_004_0_0 [Mutatsu]]
[f 2 1][bup 114 30 65535 65535 1 0][vp 1 0 0 4 0 0][f 5 13 17 15 114]¿Papá? ¿Acabas de llamarme papá?[n][w][e]

[msg MSG_005_0_0 [Mutatsu]]
[f 2 1][bup 114 30 65535 65535 1 0][vp 1 0 0 5 0 0]Siempre me dicesh que soy un viejo deshgraciado, pero te vuelvesh amable cuando vienesh a pedir dinero.[n][w][e]

[msg MSG_006_0_0 [Mutatsu]]
[f 2 1][bup 114 30 65535 65535 1 0][vp 1 0 0 6 0 0][f 5 13 17 5 114]¿Eh? Hip. ¿Esh la primera vez que te lo digo...?[n][w][e]
[f 2 1][bup 114 30 65535 65535 1 0][vp 1 0 0 7 0 0]Cierto. Sí, supongo...[n][w][e]

[msg MSG_007_0_0 [Mutatsu]]
[f 2 1][bup 114 30 65535 65535 1 0][vp 1 0 0 8 0 0]Tss, ¿me ignoras? Puesh vale. *hip* No se puede eshperar gran cosa de alguien de tu generación.[n][w][e]

[msg MSG_008_0_0 [Mutatsu]]
[f 2 1][bup 114 30 65535 65535 1 0][vp 1 0 0 9 0 0]Pensé que te habíash matado en un accidente o algo...[n][w][e]

[msg MSG_008_5_0 [Mutatsu]]
[f 2 1][bup 114 30 65535 65535 1 0][vp 1 0 0 10 0 0]No hagash que me preocupe.[n][w][e]
[f 2 1][bup 114 30 65535 65535 1 0][vp 1 0 0 11 0 0]¡¿Qué naricesh hacíash por ahí hashta las tantash?![n][w][e]

[sel SEL_009_0_0 top]
[f 2 1]Estaba con amigos.[e]
[f 2 1]Estaba estudiando.[e]
[f 2 1]No es asunto tuyo.[e]

[msg MSG_010_0_0 [Mutatsu]]
[f 2 1][bup 114 2 65535 65535 1 0][vp 1 0 0 12 0 0][f 5 13 17 5 114]Conque amigosh, ¿eh? ¿Esh una chica? Sí que lo es. Aunque todavía les sacas los cuartos a tus padres...[n][w][e]
[f 2 1][bup 114 30 65535 65535 1 0][vp 1 0 0 13 0 0][f 4 23 0 114 0 25 25]Bah, de tal palo, tal ashtilla.[n][w][e]

[msg MSG_011_0_0 [Mutatsu]]
[f 2 1][bup 114 2 65535 65535 1 0][vp 1 0 0 14 0 0]¡¿Eshtudiando?! ¿Acaso quieresh ir a la universidad para acabar trabajando en una gran empresha?[n][w][e]

[msg MSG_011_5_0 [Mutatsu]]
[f 2 1][bup 114 30 65535 65535 1 0][vp 1 0 0 15 0 0][f 4 23 0 114 0 25 25]Puesh ni te moleshtesh. Aunque te dejesh la piel... ¿No te acuerdash de lo que tú y tu madre me hicishteish?[n][w][e]

[msg MSG_012_0_0 [Mutatsu]]
[f 2 1][bup 114 30 65535 65535 1 0][vp 1 0 0 16 0 0][f 5 13 17 5 114]B-bueno, esh verdad... Hip. No esh asunto mío.[n][w][e]

[msg MSG_013_0_0 [Mutatsu]]
[f 2 1][bup 114 2 65535 65535 1 0][vp 1 0 0 17 0 0]¡Cuida esa lengua! ¡¿Quién naricesh creesh que te ha criado, eh?![n][w][e]

[msg MSG_014_0_0 [Mutatsu]]
[f 2 1][bup 114 30 65535 65535 1 0][vp 1 0 0 18 0 0]Eh... ¿Mmm? ¿Tú...?[n][w][e]

[msg MSG_015_0_0 [Mutatsu]]
[f 2 1][bup 114 3 65535 65535 0 0][vp 1 0 0 19 0 0]Pero ¿qué...? He estado todo el tiempo creyéndome que eras... En fin, cada vez me falla más la vista.[n][w][e]

[msg MND_016_0_0]
[f 2 1]Parece que Mutatsu estaba preocupado por mí.[n][w][e]
[f 2 1]Creo que ahora entiendo a Mutatsu un poco mejor...[n][w][e]

[msg MSG_017_0_0 [Mutatsu]]
[f 2 1][bup 114 2 65535 65535 0 0][vp 1 0 0 20 0 0]Pasar todo el tiempo con clientes, perderme aniversarios y cumpleaños...[n][w][e]
[f 2 1][bup 114 0 65535 65535 0 0][vp 1 0 0 21 0 0][f 4 23 0 114 0 25 25]Me pregunto si se sentían igual que yo mientras te estaba esperando antes.[n][w][e]

[sel SEL_018_0_0 top]
[f 2 1]¿De quiénes hablas?[e]
[f 2 1]¿De qué estás hablando?[e]

[msg MSG_019_0_0 [Mutatsu]]
[f 2 1][bup 114 0 65535 65535 0 0][vp 1 0 0 22 0 0]Mi mujer e hijo me abandonaron... Fue cuando todavía era empresario.[n][w][e]

[msg MSG_019_5_0 [Mutatsu]]
[f 2 1][bup 114 0 65535 65535 0 0][vp 1 0 0 23 0 0]Ya han pasado cuatro años desde que se fueron.[n][w][e]

[msg MSG_020_0_0 [Mutatsu]]
[f 2 1][bup 114 0 65535 65535 0 0][vp 1 0 0 24 0 0]Antes de hacerme monje, era un simple hombre de negocios con mujer e hijo. Éramos una familia de lo más normal.[n][w][e]

[msg MSG_020_5_0 [Mutatsu]]
[f 2 1][bup 114 0 65535 65535 0 0][vp 1 0 0 25 0 0]Pero ambos me dejaron hace cuatro años. Mi mujer e hijo...[n][w][e]

[msg MSG_021_0_0 [Mutatsu]]
[f 2 1][bup 114 0 65535 65535 0 0][vp 1 0 0 26 0 0]Antes me quedaba por ahí hasta pasada la medianoche. Mi mujer y yo discutíamos siempre por eso.[n][w][e]
[f 2 1][bup 114 0 65535 65535 0 0][vp 1 0 0 27 0 0]Ahora no sé qué hacer con mi vida cuando vuelvo a casa. Por eso vengo aquí a beber todas las noches.[n][w][e]

[sel SEL_022_0_0 top]
[f 2 1]¿Echas de menos a tu familia?[e]
[f 2 1]¿Estás huyendo?[e]

[msg MSG_023_0_0 [Mutatsu]]
[f 2 1][bup 114 2 65535 65535 0 0][vp 1 0 0 28 0 0]¡C-claro que no! ¡Ellos son los que me abandonaron![n][w][e]

[msg MSG_024_0_0 [Mutatsu]]
[f 2 1][bup 114 3 65535 65535 0 0][vp 1 0 0 29 0 0]Además, después de tanto tiempo... No sé cómo mirarles a la cara.[n][w][e]

[msg MSG_025_0_0 [Mutatsu]]
[f 2 1][bup 114 3 65535 65535 0 0][vp 1 0 0 30 0 0][f 5 13 17 5 114]Sí, tienes toda la razón. Me rapé la cabeza, pero no fue más que un numerito.[n][w][e]

[msg MSG_026_0_0 [Mutatsu]]
[f 2 1][bup 114 2 65535 65535 0 0][vp 1 0 0 31 0 0]Me emborracho para evitar enfrentarme a mis problemas, así que se podría decir que estoy huyendo.[n][w][e]

[msg MSG_027_0_0 [Mutatsu]]
[f 2 1][bup 114 2 65535 65535 0 0][vp 1 0 0 32 0 0]No me han contactado desde entonces, así que ya me habrán superado.[n][w][e]

[msg MSG_027_5_0 [Mutatsu]]
[f 2 1][bup 114 3 65535 65535 0 0][vp 1 0 0 33 0 0][f 4 23 0 114 3 25 25]No tengo ni idea de dónde están... ni de si desean verme.[n][w][e]
[f 2 1][bup 114 0 65535 65535 0 0][vp 1 0 0 34 0 0][f 4 23 0 114 0 25 25]Es un follón.[n][w][e]

[msg MSG_028_0_0 [Mutatsu]]
[f 2 1][bup 114 0 65535 65535 0 0][vp 1 0 0 35 0 0]Venga, niña. Basta de hablar de cosas deprimentes. Salgamos de aquí. Quiero volver a casa y darme una ducha.[n][w][e]

[msg MND_029_0_0]
[f 2 1]Me marché del club con Mutatsu.[n][w][e]

