[msg MSG_000_0_0 [Mamoru Hayase]]
[f 2 1][bup 115 1 65535 65535 0 0][vp 1 0 0 1 0 0][f 4 23 0 1 1 25 25]¡Esto está de muerte![n][w][e]
[f 2 1][bup 115 0 65535 65535 0 0][vp 1 0 0 2 0 0][f 4 23 0 1 0 25 25]Qué suerte tengo de poder comer algo tan estupendo.[n][w][e]

[msg MSG_001_0_0 [Mamoru Hayase]]
[f 2 1][bup 115 3 65535 65535 0 0][vp 1 0 0 3 0 0][f 4 23 0 1 3 25 25]¿Debería llevar un poco a casa? Aunque tendría que pagarlo...[n][w][e]
[f 2 1][bup 115 3 65535 65535 0 0][vp 1 0 0 4 0 0][f 4 23 0 1 3 25 25]Mmm...[n][w][e]

[sel SEL_002_0_0 top]
[f 2 1]¡Hazlo![e]
[f 2 1]Yo puedo prestarte algo de pasta.[e]

[msg MSG_003_0_0 [Mamoru Hayase]]
[f 2 1][bup 115 1 65535 65535 0 0][vp 1 0 0 5 0 0][f 4 23 0 1 1 25 25][f 5 13 18 15 115]¡Pues sí! No me gusta ser el único de mi casa que puede comer.[n][w][e]

[msg MSG_004_0_0 [Mamoru Hayase]]
[f 2 1][bup 115 0 65535 65535 0 0][vp 1 0 0 6 0 0][f 4 23 0 1 0 25 25]No te preocupes, creo que podré pagarlo.[n][w][e]

[msg MSG_005_0_0 [Mamoru Hayase]]
[f 2 1][bup 115 0 65535 65535 0 0][vp 1 0 0 7 0 0][f 4 23 0 1 0 25 25]Ah, por cierto, en cuanto a mi madre...[n][w][e]
[f 2 1][bup 115 1 65535 65535 0 0][vp 1 0 0 8 0 0][f 4 23 0 1 1 25 25]¡No le queda nada para salir del hospital![n][w][e]
[f 2 1][bup 115 0 65535 65535 0 0][vp 1 0 0 9 0 0][f 4 23 0 1 0 25 25]Justo cuando por fin me estaba haciendo a la idea de cuidar de todos yo mismo.[n][w][e]

[msg MSG_006_0_0 [Mamoru Hayase]]
[f 2 1][bup 115 0 65535 65535 0 0][vp 1 0 0 10 0 0][f 4 23 0 1 0 25 25]¡¿Y adivina qué?! Mis compañeros de equipo se han ofrecido a ayudarme con mis hermanos.[n][w][e]
[f 2 1][bup 115 0 65535 65535 0 0][vp 1 0 0 11 0 0][f 4 23 0 1 0 25 25]Dicen que hasta recogerán a mi hermana del colegio.[n][w][e]
[f 2 1][bup 115 0 65535 65535 0 0][vp 1 0 0 12 0 0][f 4 23 0 1 0 25 25]Supongo que todo el mundo estaba preocupado por mí.[n][w][e]

[msg MSG_006_3_0 [Mamoru Hayase]]
[f 2 1][bup 115 3 65535 65535 0 0][vp 1 0 0 13 0 0][f 4 23 0 1 3 25 25]Y ahí estaba yo, cortísimo de miras, tratando de hacer todo por mi cuenta.[n][w][e]
[f 2 1][bup 115 3 65535 65535 0 0][vp 1 0 0 14 0 0][f 4 23 0 1 3 25 25]Al final, tal vez fue mi culpa que el equipo no pudiera entrenar en armonía.[n][w][e]

[sel SEL_007_0_0 top]
[f 2 1]Es lo más seguro.[e]
[f 2 1]Ni te rayes.[e]

[msg MSG_008_0_0 [Mamoru Hayase]]
[f 2 1][bup 115 1 65535 65535 0 0][vp 1 0 0 15 0 0][f 4 23 0 1 1 25 25][f 5 13 18 5 115]Ja, ja. Ya veo que no te andas con rodeos.[n][w][e]

[msg MSG_009_0_0 [Mamoru Hayase]]
[f 2 1][bup 115 1 65535 65535 0 0][vp 1 0 0 16 0 0][f 4 23 0 1 1 25 25][f 5 13 18 5 115]Ja, ja. La verdad es que es un alivio escucharte decir eso.[n][w][e]

[msg MSG_010_0_0 [Mamoru Hayase]]
[f 2 1][bup 115 0 65535 65535 0 0][vp 1 0 0 17 0 0][f 4 23 0 1 0 25 25]Me siento mucho mejor con todo ahora que sé cómo se sienten los demás.[n][w][e]
[f 2 1][bup 115 1 65535 65535 0 0][vp 1 0 0 18 0 0][f 4 23 0 1 1 25 25]¡Me divierto con solo correr alrededor de la pista! Siento el cuerpo ligero como una pluma.[n][w][e]

[msg MSG_011_0_0 [Mamoru Hayase]]
[f 2 1][bup 115 0 65535 65535 0 0][vp 1 0 0 19 0 0][f 4 23 0 1 0 25 25]Uy, creo que me he ido por las ramas.[n][w][e]
[f 2 1][bup 115 0 65535 65535 0 0][vp 1 0 0 20 0 0][f 4 23 0 1 0 25 25]Lo siento, tengo que irme. Descansa, [nl].[n][w][e]

[msg MSG_012_0_0 [Mamoru Hayase]]
[f 2 1][bup 115 0 65535 65535 0 0][vp 1 0 0 21 0 0][f 4 23 0 1 0 25 25]Y no lo olvides...[n][w][e]
[f 2 1][bup 115 0 65535 65535 0 0][vp 1 0 0 22 0 0][f 4 23 0 1 0 25 25]Solo he podido volver a centrarme en el entrenamiento porque me has echado una mano. Y me siento genial, así que gracias, amiga.[n][w][e]

[msg MND_013_0_0]
[f 2 1]Hayase ha hablado de corazón.[n][w][e]
[f 2 1]Tengo la sensación de que estamos estrechando lazos.[n][w][e]

[msg MSG_014_0_0 [Mamoru Hayase]]
[f 2 1][bup 115 1 65535 65535 0 0][vp 1 0 0 23 0 0][f 4 23 0 1 1 25 25]¡Hasta luego![n][w][e]

[msg MND_015_0_0]
[f 2 1]He decidido volver a la residencia.[n][w][e]

