[msg MSG_000_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 0 0 0 1 0 0]...[n][w][e]

[sel SEL_001_0_0 top]
[f 2 1]¿Sí?[e]
[f 2 1]...[e]
[f 2 1]Si no es nada, me voy.[e]

[msg MSG_002_0_0 [Yukari Takeba]]
[f 2 1][bup 2 4 65535 65535 0 0][vp 1 0 0 2 0 0]¡S-sí! ¡Te recibo![n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 3 0 0][f 4 23 0 2 0 25 25]Uf, perdona. No me des esos sustos.[n][w][e]

[msg MSG_003_0_0 [Yukari Takeba]]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 4 0 0][f 5 13 7 15 2]Uy...[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 5 0 0][f 4 23 0 2 0 25 25]Has venido... Gracias.[n][w][e]

[msg MSG_004_0_0 [Yukari Takeba]]
[f 2 1][bup 2 4 65535 65535 0 0][vp 0 0 0 6 0 0]¿Eh?[n][w][e]

[msg MSG_005_0_0 [Yukari Takeba]]
[f 2 1][bup 2 4 65535 65535 0 0][vp 1 0 0 7 0 0]¡Oye, no seas tan cruel![n][w][e]

[msg MSG_006_0_0 [Yukari Takeba]]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 8 0 0]Eh, es culpa mía... Perdona.[n][w][e]

[msg MSG_007_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 9 0 0]Oye, quiero preguntarte una cosa.[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 10 0 0]Eh... [nl]...[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0][vp 0 0 0 11 0 0][f 4 23 0 2 3 25 25]...[n][w][e]

[msg MSG_008_0_0 [Yukari Takeba]]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 12 0 0]¿Por qué pasas tanto tiempo conmigo?[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 13 0 0]Te he causado un montón de problemas...[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 14 0 0]Y, la verdad, he dicho cosas que no están bien.[n][w][e]

[msg MSG_009_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 15 0 0]¿Es porque los dos somos usuarios de Persona?[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 16 0 0]¿O de verdad somos buenas amigas?[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 17 0 0][f 4 23 0 2 3 25 25]¿O acaso sientes algo por...?[n][w][e]

[msg MND_010_0_0]
[f 2 1]A Yukari le tiembla la voz. Debería tener mucho cuidado con lo que digo.[n][w][e]

[msg MND_011_0_0]
[f 2 1]Ahora que lo pienso, [clr 2]ya tengo una relación especial[clr 27][n][clr 2]con otra persona[clr 27]...[n][w][e]

[msg MSG_012_0_0 [Yukari Takeba]]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 18 0 0]¿Qué piensas de mí en realidad?[n][w][e]

[sel SEL_013_0_0 top]
[f 2 1]Te quiero.[f 2 9 1 1 350][e]
[f 2 1]Eres una amiga muy importante.[e]

[msg MSG_014_0_0 [Yukari Takeba]]
[f 2 1][bup 2 4 65535 65535 0 0][vp 1 0 0 19 0 0]¿Cómo...?[n][w][e]

[msg MSG_014_3_0 [Yukari Takeba]]
[f 2 1][bup 2 4 65535 65535 0 0][vp 1 0 0 20 0 0]Ni de coña. ¿Lo dices en serio?[n][w][e]
[f 2 1][bup 2 4 65535 65535 0 0][vp 1 0 0 21 0 0]No te estarás quedando conmigo, ¿no? ¿Lo dices en serio?[n][w][e]

[msg MSG_015_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 22 0 0]C-caray...[n][w][e]

[msg MSG_016_0_0 [Yukari Takeba]]
[f 2 1][bup 2 61 65535 65535 0 0][vp 1 0 0 23 0 0]Ah...[n][w][e]

[msg MSG_017_0_0 [Yukari Takeba]]
[f 2 1][bup 2 61 65535 65535 0 0][vp 1 0 0 24 0 0]Ja, ja... Perdona. Es que siento que me he quitado un peso de encima.[n][w][e]
[f 2 1][bup 2 64 65535 65535 0 0][vp 1 0 0 25 0 0][f 4 23 0 2 6 25 25]Se me caen las lágrimas.[n][w][e]

[msg MSG_018_0_0 [Yukari Takeba]]
[f 2 1][bup 2 64 65535 65535 0 0][vp 0 0 0 26 0 0]...[n][w][e]
[f 2 1][bup 2 64 65535 65535 0 0][vp 1 0 0 27 0 0]Es difícil saber lo que piensas, [nl].[n][w][e]

[msg MSG_019_0_0 [Yukari Takeba]]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 28 0 0]Siempre te portas bien con todo el mundo.[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 29 0 0]Por eso pensaba que me considerabas una amiga, igual que las demás.[n][w][e]

[msg MSG_020_0_0 [Yukari Takeba]]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 30 0 0]Últimamente, me enfado cuando te veo hablar con Fuuka.[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 31 0 0]Me daba miedo estar convirtiéndome en una persona ruin y celosa. Me siento fatal.[n][w][e]

[msg MSG_020_3_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 32 0 0]Por eso... [nl]...[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 33 0 0]Me gustaría que tuvieras ojos para mí...[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 34 0 0][f 4 23 0 2 3 25 25]Y solo para mí...[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0][vp 0 0 0 35 0 0]...[n][w][e]

[msg MND_021_0_0]
[f 2 1]Percibo el cariño que me tiene Yukari.[n][w][e]
[f 2 1]He entablado una relación especial con Yukari.[n][w][e]

[msg MND_022_0_0]
[f 2 1]Ya no hay marcha atrás.[n][w][e]

[msg MSG_023_0_0 [Yukari Takeba]]
[f 2 1][bup 2 64 65535 65535 0 0][vp 1 0 0 36 0 0]E-entonces, tú...[n][w][e]

[msg MSG_023_3_0 [Yukari Takeba]]
[f 2 1][bup 2 4 65535 65535 0 0][vp 1 0 0 37 0 0]Ay, pero ¿qué estoy diciendo?[n][w][e]
[f 2 1][bup 2 4 65535 65535 0 0][vp 1 0 0 38 0 0]¡Me voy![n][w][e]

[msg MSG_024_0_0 [Yukari Takeba]]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 39 0 0]Ya, eso pensaba.[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 40 0 0]Vamos, te portas bien con todo el mundo.[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 41 0 0]No es que yo sea especial.[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 42 0 0]De todas formas, aunque sea como amiga, ¿te gusto?[n][w][e]

[msg MSG_025_0_0 [Yukari Takeba]]
[f 2 1][bup 2 61 65535 65535 0 0][vp 1 0 0 43 0 0]Ya veo... Me alegra oír eso.[n][w][e]

[msg MSG_026_0_0 [Yukari Takeba]]
[f 2 1][bup 2 64 65535 65535 0 0][vp 1 0 0 44 0 0]Ah...[n][w][e]

[msg MSG_027_0_0 [Yukari Takeba]]
[f 2 1][bup 2 61 65535 65535 0 0][vp 1 0 0 45 0 0]Ja, ja... Perdona. Es que siento que me he quitado un peso de encima.[n][w][e]
[f 2 1][bup 2 61 65535 65535 0 0][vp 1 0 0 46 0 0]Ay, ¡venga! ¡Céntrate, Yukari![n][w][e]

[msg MSG_028_0_0 [Yukari Takeba]]
[f 2 1][bup 2 3 65535 65535 0 0][vp 0 0 0 47 0 0]...[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 48 0 0][f 4 23 0 2 0 25 25]¿Sabes qué, [nl]? Igual tenemos conceptos diferentes de lo que significa "gustar".[n][w][e]

[msg MSG_029_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 49 0 0]Pero estamos conectados de otro modo.[n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 50 0 0][f 4 23 0 2 0 25 25]Creo que eso también es especial, ¿a que sí?[n][w][e]

[msg MND_030_0_0]
[f 2 1]Percibo el cariño que me tiene Yukari.[n][w][e]
[f 2 1]Parece que nuestra relación se ha estrechado.[n][w][e]

[msg MSG_031_0_0 [Yukari Takeba]]
[f 2 1][bup 2 4 65535 65535 0 0][vp 1 0 0 51 0 0]¡Madre mía! Pero ¡¿qué digo?! Voy a tomar el aire un rato.[n][w][e]
[f 2 1][bup 2 4 65535 65535 0 0][vp 1 0 0 52 0 0]Mañana haremos como que esto nunca ha pasado, ¿vale? Seguiré siendo una buena amiga.[n][w][e]
[f 2 1][bup 2 4 65535 65535 0 0][vp 1 0 0 53 0 0]En fin, me voy. ¡Adiós![n][w][e]

[msg MND_032_0_0]
[f 2 1]Yukari se ha ido.[n][w][e]
[f 2 1]He decidido volver a la residencia.[n][w][e]

