[msg MSG_000_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 1 0 0]Ah, casi se me olvida. En el descanso para comer, la chica esa empezó a molestarme otra vez.[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 2 0 0]¿Te acuerdas de ella? La que me ponía chicles en el zapatero.[n][w][e]
[f 2 1][bup 106 2 65535 65535 0 0][vp 1 0 0 3 0 0][f 4 23 0 106 2 25 25]Pues esta vez le he dicho a la cara lo que pensaba. Le he aconsejado que se busque algo que hacer en la vida.[n][w][e]

[msg MSG_001_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 4 0 0]Creo que no ha captado lo que pretendía decirle, pero desde que sé lo que quiero hacer con mi vida, ahora lo veo todo con perspectiva.[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 5 0 0][f 4 23 0 106 1 25 25]Antes era igual que ella, ¿sabes? Diría que he aprendido a empatizar con los demás.[n][w][e]
[f 2 1][bup 106 0 65535 65535 1 0][vp 1 0 0 6 0 0][f 4 23 0 106 0 25 25]Además, al final hemos acabado siendo pareja, así que...[n][w][e]

[msg MSG_002_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 1 0][vp 1 0 0 7 0 0]Ah, pero ¡no te he invitado aquí por eso![n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 8 0 0][f 4 23 0 106 0 25 25]Podría habértelo explicado en el instituto, pero quería hablar contigo en un lugar más tranquilo.[n][w][e]

[sel SEL_003_0_0 top]
[f 2 1]¿Tan importante es?[e]
[f 2 1]¿Qué pasa?[e]

[msg MSG_004_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 9 0 0][f 5 13 12 5 106]Mmm, más o menos... Ah, pero no es nada grave.[n][w][e]

[msg MSG_005_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 4 65535 65535 0 0][vp 1 0 0 10 0 0][f 5 13 12 5 106] ¡N-no seas tan impaciente! Ya voy. ¿Por qué me he puesto tan nerviosa ahora?[n][w][e]

[msg MSG_006_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 11 0 0]¿Te acuerdas de los niños a los que entrenamos?[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 12 0 0][f 4 23 0 106 1 25 25]Nos ha dejado cada uno un mensaje.[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 13 0 0]Sé que nos dieron mucha guerra, pero también tienen un lado muy entrañable, ¿no te parece?[n][w][e]

[sel SEL_007_0_0 top]
[f 2 1]Sí.[e]
[f 2 1]No creas.[e]

[msg MSG_008_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 14 0 0][f 5 13 12 5 106]Jo, [nl], eres un encanto.[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 15 0 0][f 4 23 0 106 0 25 25]No deja de sorprenderme tu mentalidad tan abierta. Necesito aprender de ti.[n][w][e]

[msg MSG_009_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 16 0 0][f 5 13 12 5 106]Ja, ja, ja, cómo te pasas.[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 17 0 0]Sé de buena tinta que siempre cuidabas de ellos. Creo que serías una gran entrenadora.[n][w][e]

[msg MSG_010_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 18 0 0]Toma, este es para ti.[n][w][e]

[msg MND_011_0_0]
[f 2 1]¡He recibido (ITEM NAME)![n][w][e]

[msg MSG_012_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 19 0 0]Los chiquillos me dijeron que "se lo diera a mi novia"... Es que me los como.[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 20 0 0]Por eso te he invitado.[n][w][e]
[f 2 1][bup 106 0 65535 65535 1 0][vp 0 0 0 21 0 0][f 4 23 0 106 0 25 25]...[n][w][e]
[f 2 1][bup 106 0 65535 65535 1 0][vp 1 0 0 22 0 0]Bueno, a decir verdad, solo era una excusa.[n][w][e]
[f 2 1][bup 106 3 65535 65535 1 0][vp 1 0 0 23 0 0][f 4 23 0 106 3 25 25]Porque hoy... Bueno, mis padres no están en casa, así que...[n][w][e]

[sel SEL_013_0_0 top]
[f 2 1]Ya.[e]
[f 2 1]¿Qué significa eso?[e]

[msg MSG_014_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 1 0][vp 1 0 0 24 0 0]Pues eso...[n][w][e]

[msg MSG_015_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 1 0][vp 1 0 0 25 0 0]Q-quiero decir, ¡estírate lo que quieras y relájate! No nos echarán la bronca por hacer ruido. Ja, ja, ja...[n][w][e]

[msg MSG_016_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 4 65535 65535 1 0][vp 1 0 0 26 0 0]¡N-no me hagas decirlo! Q-que me da mucho corte...[n][w][e]

[msg MSG_017_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 3 65535 65535 1 0][vp 1 0 0 27 0 0][f 5 13 12 5 106]Oye, deja de mirarme así. Ya sé que estoy roja como un tomate...[n][w][e]

[msg MSG_018_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 1 0][vp 1 0 0 28 0 0]Es que... Gracias a ti, [nl], he encontrado mi verdadera vocación.[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 29 0 0][f 4 23 0 106 1 25 25]Me alegro mucho de haberte conocido.[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 30 0 0]Esto es lo que siento y espero que sea recíproco.[n][w][e]
[f 2 1][bup 106 0 65535 65535 1 0][vp 1 0 0 31 0 0][f 4 23 0 106 0 25 25]Bueno... ¿te quedarás conmigo un poco más?[n][w][e]

[msg MND_019_0_0]
[f 2 1]Yuko ha expresado su amor por mí.[n][w][e]

[msg SYS_020_0_0]
[f 2 1]El vínculo social de la Fuerza ha alcanzado su nivel máximo. ¡Ya puedes fusionar al rey de la sabiduría, [clr 35]Atavaka[clr 27]![n][w][e]

[msg MSG_021_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 1 0][vp 1 0 0 32 0 0]Te quiero...[n][w][e]
[f 2 1][bup 106 1 65535 65535 1 0][vp 1 0 0 33 0 0][f 4 23 0 106 1 25 25]Muchísimo.[n][w][e]

[msg MND_022_0_0]
[f 2 1]He compartido una tarde especial con Yuko.[n][w][e]

