[msg MSG_000_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 1 65535 65535 0 0][vp 3 0 65535 10062 0 0]¡Colega, he sacado el plan definitivo del manga que estaba leyendo![n][w][e]
[f 2 1][bup 101 1 65535 65535 0 0]Así voy a conquistar a la profesora Kanou. ¿Quieres oírlo? ¿Eh? ¿Quieres? ¡Sabes que sí![n][w][e]

[msg MSG_001_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 0 65535 65535 0 0]Mira, le voy a decir esto...[n][w][e]
[f 2 1][bup 101 3 65535 65535 0 0][f 4 23 0 101 10 25 25]"Hola, profesora Kanou... Este problema me está dando mucho la lata"...[n][w][e]

[msg MSG_001_5_0 [Kenji Tomochika]]
[f 2 1][bup 101 0 65535 65535 0 0]Y ella dirá...[n][w][e]
[f 2 1][bup 101 1 65535 65535 0 0][f 4 23 0 101 1 25 25]"Ah, no te preocupes, Tomochika. Estoy aquí para ayudarte. Yo me encargaré de todo".[n][w][e]

[msg MSG_002_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 1 65535 65535 0 0][vp 3 0 65535 10005 0 0]Bueno, ¿qué te parece? ¿No es la hostia?[n][w][e]

[sel SEL_003_0_0 top]
[f 2 1]No va a funcionar.[e]
[f 2 1]¡Sí, perfecto![e]
[f 2 1]Tengo un plan mejor.[e]

[msg MSG_004_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 3 65535 65535 0 0][vp 3 0 65535 10091 0 0]Tía, ¿por qué tienes que ser tan aguafiestas? En el manga salía a pedir de boca...[n][w][e]

[msg MND_005_0_0]
[f 2 1]Tomochika parece decepcionado.[n][w][e]
[f 2 1]Siento que hoy nuestra relación no ha cambiado nada...[n][w][e]

[msg MSG_006_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 1 65535 65535 0 0][vp 3 0 65535 10094 0 0][f 5 13 2 15 101]Lo sé, ¿vale? ¡Va a salir bien![n][w][e]

[msg MND_007_0_0]
[f 2 1]Tomochika parece emocionado.[n][w][e]
[f 2 1]Hoy he aprendido un poco más sobre él.[n][w][e]

[msg MSG_008_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 4 65535 65535 0 0][vp 3 0 65535 10075 0 0][f 5 13 2 30 101]Vaya, ¿en serio? Tía, da gusto tener cerca a alguien como tú.[n][w][e]

[msg MND_009_0_0]
[f 2 1]Tomochika parece muy emocionado.[n][w][e]
[f 2 1]Siento que hoy nuestra relación se ha estrechado.[n][w][e]

[msg MSG_010_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 1 65535 65535 0 0][vp 3 0 65535 10095 0 0]Muy bien, ¡seguiré con la investigación para que acabemos felices y comiendo perdices![n][w][e]
[f 2 1][bup 101 1 65535 65535 0 0]Cuento contigo, tía. Si se te ocurre alguna jugada magistral, te invito a cenar o lo que sea.[n][w][e]

[msg MND_011_0_0]
[f 2 1]Me he despedido de Kenji y he vuelto a la residencia.[n][w][e]

