[msg MSG_024_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 1 0 0]Ahora que me acuerdo, una vez estaba leyendo este libro en clase y...[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 2 0 0]Un compañero lo vio y me dijo: "Vaya, qué sorpresa. Eres de las que hablan con los puños".[n][w][e]

[msg MSG_025_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 3 0 0][f 4 21 7 4]¿Qué imagen tiene la gente de mí?[n][w][e]

[sel SEL_026_0_0 top]
[f 2 1]Una estudiante normal.[e]
[f 2 1]No le des tantas vueltas.[e]
[f 2 1]Una chica mona.[e]

[msg MSG_027_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 4 0 0]Ya veo.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 5 0 0]Entonces, a ojos de los demás, no parezco tan fuerte.[n][w][e]

[msg MSG_028_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 6 0 0]No, he de tenerlo en cuenta.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 7 0 0]Parecía sorprendido, así que...[n][w][e]

[msg MSG_029_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 8 0 0][f 4 21 7 4]¿"Mona"?[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 9 0 0]Hasta donde yo sé, ese término es el femenino de "mono", un animal.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 10 0 0]¿Quieres decir que me consideran semejante a ellos?[n][w][e]

[msg MSG_030_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 11 0 0][f 4 23 0 7 0 25 25]Soy un arma antisombras, pero me toman por otra cosa.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 12 0 0]Debo atajar este problema de raíz.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 13 0 0]Si no, repercutirá en mi capacidad para desempeñar mis funciones.[n][w][e]

[msg MSG_031_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 14 0 0]Pensaré en una solución cuando termine de leer.[n][w][e]

[msg MSG_032_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 15 0 0]En combate, el estado mental de los rivales afecta al resultado.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 16 0 0]Quiero que mi presencia infunda terror en el corazón de mis enemigos y estimule a mis aliados.[n][w][e]

[msg MSG_032_5_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 17 0 0]¿Qué puedo hacer para dar esa impresión?[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 18 0 0]Lo ideal sería algo que anime a los demás a contar conmigo.[n][w][e]

[msg MSG_033_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 19 0 0]A lo mejor en el libro se incluyen consejos.[n][w][e]

[msg MND_034_0_0]
[f 2 1]Siento que mi [f 4 30 1 1 1 0] ha aumentado tras leer sobre el espíritu justiciero del protagonista.[n][w][e]

[msg MSG_035_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 20 0 0][f 5 13 22 1 7]Creo que ya hemos leído mucho por hoy. Volvamos a nuestras habitaciones.[n][w][e]

[msg MSG_036_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 21 0 0]Ahora que me acuerdo, una vez estaba leyendo este libro en clase y...[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 22 0 0]Un compañero lo vio y me dijo: "Vaya, qué sorpresa. Eres de las que hablan con los puños".[n][w][e]

[msg MSG_037_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 23 0 0][f 4 21 7 4]¿Qué imagen tiene la gente de mí?[n][w][e]

[sel SEL_038_0_0 top]
[f 2 1]Una estudiante normal.[e]
[f 2 1]No le des tantas vueltas.[e]
[f 2 1]Una chica mona.[e]

[msg MSG_039_0_0 [Aigis]]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 24 0 0][f 4 23 0 7 3 25 25]Ya veo.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 25 0 0][f 4 23 0 7 0 25 25]Entonces, a ojos de los demás, no parezco tan fuerte.[n][w][e]

[msg MSG_040_0_0 [Aigis]]
[f 2 1][bup 7 1 65535 65535 0 0][vp 1 0 0 26 0 0][f 4 23 0 7 1 25 25]Gracias. Sé que estás siendo considerada.[n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 27 0 0][f 4 23 0 7 3 25 25]Pero me molesta, no puedo evitarlo.[n][w][e]

[msg MSG_041_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 28 0 0]¿Mono?[n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 29 0 0][f 4 23 0 7 3 25 25]Entiendo que debo tomármelo como un cumplido.[n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 30 0 0]Pero si eso es lo que opinan de mí los demás, entonces...[n][w][e]

[msg MSG_042_0_0 [Aigis]]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 31 0 0][f 4 23 0 7 3 25 25]Soy un arma antisombras, pero me toman por otra cosa.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 32 0 0][f 4 23 0 7 0 25 25]¿No es grave?[n][w][e]

[msg MSG_043_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 33 0 0]Tendré que pensar en una solución cuando termine de leer.[n][w][e]

[msg MSG_044_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 34 0 0]En combate, el estado mental de los rivales afecta al resultado.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 35 0 0]Quiero intimidar a mis enemigos e infundir coraje a mis aliados.[n][w][e]

[msg MSG_045_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 36 0 0]¿Qué puedo hacer para dar esa impresión?[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 37 0 0]Lo ideal sería algo que me haga ser digna de confianza en combate.[n][w][e]

[msg MSG_135_0_0 [Aigis]]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 38 0 0][f 4 23 0 7 3 25 25]A lo mejor en el libro se incluyen consejos.[n][w][e]

[msg MND_046_0_0]
[f 2 1]Siento que mi [f 4 30 1 1 1 0] ha aumentado tras leer sobre el espíritu justiciero del protagonista.[n][w][e]

[msg MSG_047_0_0 [Aigis]]
[f 2 1][bup 7 1 65535 65535 0 0][vp 1 0 0 39 0 0][f 4 23 0 7 1 25 25][f 5 13 22 1 7]Bueno, dejémoslo por hoy. Buenas noches.[n][w][e]

