[msg MSG_000_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6012 0 0]Descansa. Ahora tú y yo estaremos siempre juntas, [nf].[n][w][e]

[msg MND_001_0_0]
[f 2 1]Aún le falta para poder hacerse pasar por humana.[n][w][e]
[f 2 1]Parece que todavía no entiende sentimientos y conversaciones normales.[n][w][e]
[f 2 1]Si lo hiciera, podría forjar un vínculo con ella.[n][w][e]

[msg MSG_002_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6080 0 0]He inspeccionado todo el instituto, pero no he encontrado a nadie que tuviera apatía.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0]¿Debería presuponer que han faltado a clase?[n][w][e]

[msg MND_003_0_0]
[f 2 1]Aún le falta para poder hacerse pasar por humana.[n][w][e]
[f 2 1]Parece que todavía no entiende sentimientos y conversaciones normales.[n][w][e]
[f 2 1]Si lo hiciera, podría forjar un vínculo con ella.[n][w][e]

[msg MSG_004_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6012 0 0]Junpei ya ha salido del instituto. Se ha ido al hospital.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0]Últimamente parece algo inestable emocionalmente.[n][w][e]

[msg MND_005_0_0]
[f 2 1]Aún le falta para poder hacerse pasar por humana.[n][w][e]
[f 2 1]Parece que todavía no entiende sentimientos y conversaciones normales.[n][w][e]
[f 2 1]Si lo hiciera, podría forjar un vínculo con ella.[n][w][e]

[msg MSG_006_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6012 0 0]Junpei se ha ido al hospital.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0]Parecía que iba con bastantes ganas. ¿El interrogatorio ha ido sin problemas?[n][w][e]

[sel SEL_007_0_0 top]
[f 2 1]Pues sí.[e]
[f 2 1]No, la verdad.[e]
[f 2 1]Está... "progresando".[e]

[msg MSG_008_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6030 0 0]Cabe esperar que recabemos información útil.[n][w][e]

[msg MSG_009_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6057 0 0]Es una lástima, pero me lo esperaba.[n][w][e]

[msg MSG_010_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6051 0 0]¿Detecto un significado subyacente? ¿Hay algo entre ella y Junpei que yo no haya notado?[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0]De todos modos, me cuesta comprender ese tipo de sutilezas.[n][w][e]

[msg MND_011_0_0]
[f 2 1]Aún le falta para poder hacerse pasar por humana.[n][w][e]
[f 2 1]Parece que todavía no entiende sentimientos y conversaciones normales.[n][w][e]
[f 2 1]Si lo hiciera, podría forjar un vínculo con ella.[n][w][e]

[msg MSG_012_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6064 0 0]Parece que todo el mundo tiene ganas de que llegue el festival.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0]Nunca he experimentado un evento así, por lo que no me lo imagino.[n][w][e]

[msg MND_013_0_0]
[f 2 1]Aún le falta para poder hacerse pasar por humana.[n][w][e]
[f 2 1]Parece que todavía no entiende sentimientos y conversaciones normales.[n][w][e]
[f 2 1]Si lo hiciera, podría forjar un vínculo con ella.[n][w][e]

[msg MSG_014_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6012 0 0]He oído que Yukari trabajará en la cafetería de sirvientas durante el festival.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0]Desconozco el concepto. Sin embargo...[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0]Parece que los alumnos están sumamente entusiasmados por ver su nuevo uniforme.[n][w][e]

[msg MND_015_0_0]
[f 2 1]Aún le falta para poder hacerse pasar por humana.[n][w][e]
[f 2 1]Parece que todavía no entiende sentimientos y conversaciones normales.[n][w][e]
[f 2 1]Si lo hiciera, podría forjar un vínculo con ella.[n][w][e]

[msg MSG_016_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6012 0 0]Fue un tifón de proporciones considerables. Creía que el instituto sufriría algunos daños.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0]No obstante, me equivoqué. Debieron de construirlo con materiales resistentes.[n][w][e]

[msg MND_017_0_0]
[f 2 1]Aún le falta para poder hacerse pasar por humana.[n][w][e]
[f 2 1]Parece que todavía no entiende sentimientos y conversaciones normales.[n][w][e]
[f 2 1]Si lo hiciera, podría forjar un vínculo con ella.[n][w][e]

[msg MSG_018_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6051 0 0]¿Puedo preguntarte algo?[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0]¿Crees que alguien sospecha que soy una robot?[n][w][e]

[sel SEL_019_0_0 top]
[f 2 1]Ni de broma.[e]
[f 2 1]Es posible.[e]

[msg MSG_020_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6030 0 0]Entonces, no es necesario realizar ningún ajuste.[n][w][e]

[msg MSG_021_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6064 0 0]¿Acaso me faltan amaneramientos humanos?[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0]De ahora en adelante, procuraré imitar varias idiosincrasias para evitar que me descubran.[n][w][e]

[msg MSG_022_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6080 0 0]Pronto volverá a haber luna llena. ¿Has realizado las preparaciones adecuadas para el combate?[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0]Si no te has preparado aún, deberías ir al centro comercial inmediatamente después del instituto.[n][w][e]

[msg MSG_023_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6064 0 0]Es una lástima, pero no hay muchos estudiantes que parezcan entristecidos por la muerte de Aragaki.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0]Por lo visto, los humanos olvidan sus relaciones rápidamente, aunque nuestro caso es excepcional.[n][w][e]

[msg MSG_024_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6030 0 0]Lo racional es que los estudiantes se centren en sus exámenes, en vez de en Aragaki.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0]No obstante, por alguna razón desconocida...[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0]Pongo en duda la validez de pensar así.[n][w][e]

[msg MSG_025_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6051 0 0]Fuuka dijo que "lo averiguó".[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0]¿Tú qué opinas, [nf]?[n][w][e]

[sel SEL_026_0_0 top]
[f 2 1]La comprendo...[e]
[f 2 1]No lo pillo.[e]

[msg MSG_027_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6030 0 0]Me alegro.[n][w][e]

[msg MSG_028_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6037 0 0]Ni yo.[n][w][e]

[msg MSG_029_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6060 0 0][f 4 25 7]...[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0]Ay, perdona... Estaba pensando en mis cosas.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0]Estaba considerando qué podría llegar a ganar yendo al instituto.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0]Pero creo que nada resultará de esta forma de pensar. No es algo que deba considerar.[n][w][e]

[msg MSG_030_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6074 0 0]Parece que Junpei duerme muchísimo.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0]Debe de estar guardando fuerzas para el combate.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0]Es una táctica interesante.[n][w][e]

[msg MSG_031_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6060 0 0][f 4 25 7]...[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0]Ay, perdona... Estaba pensando en mis cosas.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0]Me preguntaba qué pasará conmigo una vez derrotemos a todas las sombras.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0]Espero poder seguir yendo al instituto.[n][w][e]

[msg MSG_032_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6007 0 0]Mañana es la batalla final. ¿Estás lista?[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0]Si necesitas suministros o equipamiento, que no pase de hoy.[n][w][e]

[msg MSG_033_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6050 0 0]Por alguna razón, hoy no he podido concentrarme en clase.[n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0]No es nada propio de mí. Nunca antes había perdido la concentración en una tarea.[n][w][e]

[msg MSG_034_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6143 0 0]Ryoji es peligroso.[n][w][e]
[f 2 1][bup 7 2 65535 65535 0 0]Lo he vuelto a analizar y tampoco he detectado nada anormal. No obstante, tengo un "mal presentimiento" sobre él.[n][w][e]

[msg MSG_035_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6074 0 0]El hecho de que este instituto organice sus excursiones cada dos años no es normal, ¿verdad?[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0]El año pasado no hubo, lo que significa que quienes están ahora en el último curso aún no han ido de excursión.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0]Los de primero no van de excursión, así que este año los de segundo y tercero irán juntos.[n][w][e]

[msg MSG_036_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6001 0 0]La mayoría de la gente parece nerviosa por la próxima excursión.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0]¿Hay nervios, [nf]?[n][w][e]

[sel SEL_037_0_0 top]
[f 2 1]Claro que sí.[e]
[f 2 1]No, la verdad.[e]
[f 2 1]¿Qué me dices tú, Aigis?[e]

[msg MSG_038_0_0 [Aigis]]
[f 2 1][bup 7 1 65535 65535 0 0][vp 3 0 65535 6142 0 0]Está bien. Entonces, eres como los demás.[n][w][e]

[msg MSG_039_0_0 [Aigis]]
[f 2 1][bup 7 1 65535 65535 0 0][vp 3 0 65535 6060 0 0]Parece que mantienes la calma. Tal vez deberían afectarte un poco los nervios...[n][w][e]

[msg MSG_040_0_0 [Aigis]]
[f 2 1][bup 7 3 65535 65535 0 0][vp 3 0 65535 6081 0 0]No lo sé. ¿A ti te lo parece?[n][w][e]

[msg MSG_041_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6106 0 0]Decidir tu propia carrera parece ser un proceso fascinante.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0]No obstante, dado que me diseñaron principalmente para combatir, a mí no me resultaría muy útil.[n][w][e]

[msg MSG_042_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6074 0 0]Junpei ha vuelto a casa pronto hoy.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0]Se notaba que estaba desanimado. Tal vez no se ha recuperado del todo del incidente.[n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0]Me preocupa...[n][w][e]

[msg MSG_043_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6119 0 0]Me preocupa Ryoji, y eso está afectando incluso a mi concentración.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0]Es una situación grave. ¿Qué debería hacer?[n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0][f 4 25 7]...[n][w][e]

[msg MSG_044_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6060 0 0]Ryoji no ha venido hoy al instituto. ¿Qué habrá pasado?[n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0][f 4 25 7]...[n][w][e]

[msg MSG_045_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2078 0 0]UNUSED[n][w][e]

[msg MSG_046_0_0 [Aigis]]
[f 2 1][bup 7 3 65535 65535 0 0][f 4 25 7]Unused[n][w][e]

[msg MSG_047_0_0 [Aigis]]
[f 2 1][bup 7 0 157 65535 0 0][vp 3 0 65535 6087 0 0]He sacado una tira de la fortuna en la que ponía "Muy buena suerte".[n][w][e]
[f 2 1][bup 7 1 157 65535 0 0]Estoy segura de que eso significa que todo saldrá a pedir de boca.[n][w][e]

[msg MND_GENERAL_EVENTPLAY]
[f 2 1]Mensaje enviado por el guion. Repetición del evento del comité.[n][w][e]

[msg MND_GENERAL_PERSPNA]
[f 2 1]Siento que podemos estrechar lazos gracias a la Persona del arcano [f 2 4 2], [clr 35][f 2 4 5][clr 27].[n][w][e]

[msg MND_GENERALSELECTMSG_MAX]
[f 2 1]Siento un vínculo irrompible con [f 2 4 0]...[n][w][e]

[msg MND_GENERALMSG_BS_MAX]
[f 2 1]Siento un vínculo irrompible con la pareja de ancianos...[n][w][e]

[msg MND_GENERALSELECTMSG_RAN]
[f 2 1]Creo que mi relación con [f 2 4 0] se estrechará pronto.[n][w][e]

[msg MND_GENERALMSG_BS_RANKUP]
[f 2 1]Creo que mi relación con la pareja de ancianos se estrechará pronto.[n][w][e]

[msg MND_GENERALSELECTMSG_NOR]
[f 2 1]No creo que mi vínculo con [f 2 4 0] se fortalezca más aunque pasemos tiempo juntas...[n][w][e]

[msg MND_GENERALMSG_BS_NORMAL [Aigis]]
[f 2 1]No creo que nuestro vínculo se fortalezca más aunque pasemos tiempo juntas.[n][w][e]

[msg MND_GENERALSELECTMSG_MAX_2]
[f 2 1]Parece que tu relación no puede avanzar más...[n][w][e]
[f 2 1]¿Deberíamos pasar el rato juntas igualmente?[n][w][e]

[msg MND_GENERAL_MSG_SOLO_AS]
[f 2 1]¿Paso un rato con [f 2 4 0] después de clase?[n][w][e]

[msg MND_GENERAL_MSG_SOLO_DT]
[f 2 1]¿Debería pasar el día con [f 2 4 0]?[n][w][e]

[msg MND__GENERAL_MSG_NET]
[f 2 1]¿Debería pasar tiempo en línea jugando al MMORPG con [f 2 4 0]?[n][w][e]

[msg MND_GENERAL_MSG_SOLO_NT]
[f 2 1]¿Debería pasar la tarde con [f 2 4 0]...?[n][w][e]

[sel SEL_GENERALSELECTMSG_SOL top]
[f 2 1]Pasar tiempo con [f 2 4 0][e]
[f 2 1]Comprobar vínculo social[e]
[f 2 1]Da igual[e]

[msg MND_GENERAL_MSG_MULTIPLE]
[f 2 1]¿Paso un rato en [f 2 4 1] después de clase?[n][w][e]

[msg MND_GENERAL_MSG_FASHION_]
[f 2 1]¿Paso un rato en el club de moda después de clase?[n][w][e]

[msg MND_GENERAL_MSG_BOOKSTOR]
[f 2 1]¿Debería pasar el día en la librería?[n][w][e]

[msg MND_GENERAL_MSG_BOOKSTOR_2]
[f 2 1]¿Paso un rato en la librería después de clase?[n][w][e]

[msg MND_GENERAL_MSG_MULTIPLE_2]
[f 2 1]¿Debería pasar tiempo con [f 2 4 1] esta noche...?[n][w][e]

[sel SEL_GENERALSELECTMSG_MUL top]
[f 2 1]Pasar un rato: [f 2 4 1][e]
[f 2 1]Comprobar vínculo social[e]
[f 2 1]Da igual[e]

[sel SEL_GENERALSELECTMSG_FCL top]
[f 2 1]Ir al club de moda.[e]
[f 2 1]Comprobar vínculo social[e]
[f 2 1]Da igual[e]

[sel SEL_GENERALSELECTMSG_BS top]
[f 2 1]Entrar en la librería[e]
[f 2 1]Comprobar vínculo social[e]
[f 2 1]Da igual[e]

[msg MSG_GENERAL_EXAMREWARD_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4029 0 0]Ah.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]He visto tus notas. Buen trabajo.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Toma, de parte del director.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4108 0 0]Es tu recompensa por ser capaz de compaginar los estudios y nuestras... en fin, "actividades extraescolares".[n][w][e]

[msg MND_GENERAL_EXAMREWARD_0]
[f 2 1]DEV: UNUSED LABEL[n][w][e]

[msg MND_GENERAL_EXAMREWARD_0_2]
[f 2 1]Como he sacado la nota más alta en los exámenes, he obtenido: [f 4 4 1 37 1 3].[n][w][e]

[msg MSG_GENERAL_EXAMREWARD_0_2 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4029 0 0]Ah.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]He visto tus notas. Buen trabajo.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Toma, de parte del director.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4108 0 0]Es tu recompensa por ser capaz de compaginar los estudios y nuestras... en fin, "actividades extraescolares".[n][w][e]

[msg MSG_GENERAL_EXAMREWARD_0_3 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4077 0 0]Ah, cierto. Hay algo más.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]He visto tus notas. Buen trabajo.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Toma, de parte del director.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4131 0 0]Es tu recompensa por ser capaz de compaginar los estudios y nuestras... en fin, "actividades extraescolares".[n][w][e]

[msg MND_GENERAL_EXAMREWARD_0_3]
[f 2 1]Como he sacado la nota más alta en los exámenes, he obtenido: [f 4 4 1 37 1 3].[n][w][e]

[msg MSG_GENERAL_EXAMREWARD_0_4 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4029 0 0]Ah.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]He visto tus notas. Buen trabajo.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Toma, de parte del director.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4108 0 0]Es tu recompensa por ser capaz de compaginar los estudios y nuestras... en fin, "actividades extraescolares".[n][w][e]

[msg MND_GENERAL_EXAMREWARD_0_4]
[f 2 1]DEV: UNUSED LABEL[n][w][e]

[msg MSG_GENERAL_EXAMREWARD_0_5 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4029 0 0]Ah.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]He visto tus notas... Buen trabajo.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Es laudable que continúes destacando en el instituto mientras libras arduos combates.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0]Acepta este regalo para agradecerte tus esfuerzos.[n][w][e]

[msg MND_GENERAL_EXAMREWARD_0_5]
[f 2 1]未使用ラベルです。[n][w][e]

[msg MSG_GENERAL_EXAMREWARD_0_6 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 6 65535 0 0][vp 3 0 65535 4029 0 0]Ah.[n][w][e]
[f 2 1][bup 5 0 6 65535 0 0]He visto tus notas. Buen trabajo.[n][w][e]
[f 2 1][bup 5 0 6 65535 0 0]Es laudable que continúes destacando en el instituto mientras libras arduos combates.[n][w][e]
[f 2 1][bup 5 0 6 65535 0 0]Acepta este regalo para agradecerte tus esfuerzos.[n][w][e]

[msg MND_GENERAL_EXAMREWARD_1]
[f 2 1]Como he sacado la nota más alta en los exámenes, he obtenido: [f 4 4 1 37 1 3].[n][w][e]

[msg MSG_GENERAL_EXAMREWARD_1 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4029 0 0]Ah.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]He visto tus notas. Buen trabajo.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Es laudable que continúes destacando en el instituto mientras libras arduos combates.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4108 0 0]Acepta este regalo para agradecerte tus esfuerzos.[n][w][e]

[msg MND_GENERAL_EXAMREWARD_1_2]
[f 2 1]DEV: UNUSED LABEL[n][w][e]

[msg MND_GENERAL_EXAMREWARD_1_3]
[f 2 1]Como he sacado la nota más alta en los exámenes, he obtenido: [f 4 4 1 37 1 3].[n][w][e]

