[msg MSG_000_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 2 65535 0 0][vp 1 0 0 1 0 0][f 4 23 0 1 0 25 25]Siento no haberte avisado antes, pero... ¿puedes venir conmigo? Hay algo de lo que me gustaría hablar.[n][w][e]

[msg MSG_001_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 2 65535 0 0][vp 1 0 0 2 0 0][f 4 23 0 3 0 25 25]¡Uuuuh! ¿Nos quieres a todos o solo a ella?[n][w][e]

[msg MSG_002_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 2 65535 0 0][vp 1 0 0 3 0 0][f 4 23 0 1 0 25 25]Solo a ella de momento.[n][w][e]

[msg MSG_003_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 2 65535 0 0][vp 1 0 0 4 0 0][f 4 23 0 1 0 25 25]Acompáñame al aula del consejo estudiantil.[n][w][e]

[msg MSG_004_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 2 65535 0 0][vp 1 0 0 5 0 0]¿No es un poco raro que solo quiera hablar con ella?[n][w][e]

[msg MSG_005_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 2 65535 0 0][vp 1 0 0 6 0 0][f 4 23 0 3 0 25 25]A lo mejor es algún asunto importante del consejo estudiantil.[n][w][e]

[msg MSG_006_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 2 65535 0 0][vp 1 0 0 7 0 0]Puede ser, pero... la he visto un poco rara.[n][w][e]
[f 2 1][bup 2 3 2 65535 0 0][vp 1 0 0 8 0 0][f 4 23 0 2 3 25 25]Tenía esa mirada que se le pone cuando guarda un secreto de los gordos.[n][w][e]

[msg MSG_007_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 2 65535 0 0][vp 1 0 0 9 0 0][f 4 23 0 3 0 25 25]Te preocupas demasiado.[n][w][e]
[f 2 1][bup 3 0 2 65535 0 0][vp 1 0 0 10 0 0][f 4 23 0 3 0 25 25]En fin... Nosotros también deberíamos volver ya.[n][w][e]

[msg MSG_008_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 2 65535 0 0][vp 1 0 0 11 0 0]Oye, espera, Junpei. Según la tabla, si no está, te toca a ti limpiar por ella.[n][w][e]
[f 2 1][bup 2 0 2 65535 0 0][vp 1 0 0 12 0 0]¡Diviértete barriendo el pasillo![n][w][e]

[msg MSG_009_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 2 65535 0 0][vp 1 0 0 13 0 0][f 4 23 0 3 4 25 25]¡¿Eeeeh?! ¡¿Desde cuándo eso es así?![n][w][e]

