[msg MSG_000_0_0 [Kazushi Miyamoto]]
[f 2 1][bup 105 1 101 65535 0 0][vp 3 0 65535 10801 0 0]¿Qué te cuentas, [nl]?[n][w][e]
[f 2 1][bup 105 0 101 65535 0 0]¿Hoy vas a ir a entrenar?[n][w][e]

[msg MSG_001_0_0 [Kazushi Miyamoto]]
[f 2 1][bup 105 3 101 65535 0 0][vp 3 0 65535 10804 0 0]Ah, [nl]. ¿Hoy vas a ir a entrenar?[n][w][e]
[f 2 1][bup 105 3 101 65535 0 0]Lo siento, colega. Ve yendo sin mí.[n][w][e]

[msg MND_002_0_0]
[f 2 1]Miyamoto actúa de forma extraña.[n][w][e]

[msg MND_003_0_0]
[f 2 1]¿Voy un rato al entrenamiento de atletismo después de clase?[n][w][e]

[sel SEL_004_0_0 top]
[f 2 1]Ir a entrenar[e]
[f 2 1]Comprobar estado de vínculo social[e]
[f 2 1]Ahora no[e]

[msg MSG_005_0_0 [Kazushi Miyamoto]]
[f 2 1][bup 105 1 101 65535 0 0][vp 3 0 65535 10867 0 0]Vaya, veo que estás deseando ir. ¡Pero no podrás conmigo![n][w][e]
[f 2 1][bup 105 1 101 65535 0 0]¡Venga, corramos![n][w][e]

[msg MSG_006_0_0 [Kazushi Miyamoto]]
[f 2 1][bup 105 3 101 65535 0 0][vp 3 0 65535 10872 0 0]Sí, yo también voy. Un segundo.[n][w][e]

[msg MSG_007_0_0 [Kazushi Miyamoto]]
[f 2 1][bup 105 3 101 65535 0 0][vp 3 0 65535 10890 0 0]¿Eh? ¿Hoy no vas a ir?[n][w][e]
[f 2 1][bup 105 0 101 65535 0 0]Colega, ¿cómo vas a alcanzar mi nivel si no te esfuerzas? Será mejor que te pongas las pilas.[n][w][e]

[msg MSG_008_0_0 [Kazushi Miyamoto]]
[f 2 1][bup 105 0 101 65535 0 0][vp 3 0 65535 10817 0 0]Vale, nos vemos.[n][w][e]

[msg MSG_009_0_0 [Kazushi Miyamoto]]
[f 2 1][bup 105 0 101 65535 0 0]Parece que es hora de ir al entrenamiento.[n][w][e]
[f 2 1][bup 105 1 101 65535 0 0]¿Vienes? Aunque no sé si debería comer algo antes...[n][w][e]

[msg MSG_010_0_0 [Kazushi Miyamoto]]
[f 2 1][bup 105 0 101 65535 0 0]Ah, por cierto, ¿hoy vas a ir a entrenar, [nl]?[n][w][e]
[f 2 1][bup 105 3 101 65535 0 0]Lo siento, colega. Ve yendo sin mí.[n][w][e]

[msg MSG_011_0_0 [Kazushi Miyamoto]]
[f 2 1][bup 105 1 101 65535 0 0][vp 3 0 65535 10809 0 0]¡Eh, [nl]! ¡Por fin han terminado los exámenes![n][w][e]

[msg MSG_012_0_0 [Kazushi Miyamoto]]
[f 2 1][bup 105 0 101 65535 0 0][vp 3 0 65535 10811 0 0]¡Eh, [nl]! ¡Por fin han terminado los exámenes![n][w][e]

[msg MSG_013_0_0 [Kazushi Miyamoto]]
[f 2 1][bup 105 1 101 65535 0 0]Ahora podemos centrarnos en el entrenamiento.[n][w][e]

[msg MSG_014_0_0 [Kazushi Miyamoto]]
[f 2 1][bup 105 0 101 65535 0 0]Uf... ¿Qué plan hay hoy?[n][w][e]

[msg MSG_015_0_0 [Kazushi Miyamoto]]
[f 2 1][bup 105 0 101 65535 0 0][vp 3 0 65535 10812 0 0]Oye, ¿vas a ir a entrenar? Será mejor que vayas deprisa a cambiarte.[n][w][e]

[msg MSG_015_5_0 [Kazushi Miyamoto]]
[f 2 1][bup 105 0 101 65535 0 0]Ah, sí. ¿Vas a ir a entrenar? Será mejor que vayas deprisa a cambiarte.[n][w][e]

[msg MSG_016_0_0 [Kazushi Miyamoto]]
[f 2 1][bup 105 1 101 65535 0 0][vp 3 0 65535 10867 0 0]Genial, ¡vamos![n][w][e]
[f 2 1][bup 105 1 101 65535 0 0]Hoy vamos a ver de qué estás hecha, pero no te fuerces demasiado, ¿vale?[n][w][e]

[msg MSG_017_0_0 [Kazushi Miyamoto]]
[f 2 1][bup 105 0 101 65535 0 0][vp 3 0 65535 10802 0 0]¿Qué tal? Por fin salimos de clase, ¿eh?[n][w][e]
[f 2 1][bup 105 1 101 65535 0 0]¿Ahora vas a ir a entrenar? ¿Quieres que vayamos juntos a la pista?[n][w][e]

[msg MSG_017_5_0 [Kazushi Miyamoto]]
[f 2 1][bup 105 1 101 65535 0 0]Ah, sí. ¿Ahora vas a ir a entrenar? ¿Quieres que vayamos juntos a la pista?[n][w][e]

[msg MSG_018_0_0 [Kazushi Miyamoto]]
[f 2 1][bup 105 1 101 65535 0 0][vp 3 0 65535 10867 0 0]¡Es justo lo que quería oír![n][w][e]
[f 2 1][bup 105 0 101 65535 0 0]No puedo permitir que siempre me dejes en ridículo. ¡Ya es hora de que me lo tome en serio![n][w][e]

[msg MSG_019_0_0 [Kazushi Miyamoto]]
[f 2 1][bup 105 0 101 65535 0 0][vp 3 0 65535 10811 0 0]Hola, [nl]. ¿Vas a ir a entrenar?[n][w][e]
[f 2 1][bup 105 3 101 65535 0 0]Si vas a ir, ve sin mí. Te... Te veré luego.[n][w][e]

[msg MSG_019_5_0 [Kazushi Miyamoto]]
[f 2 1][bup 105 0 101 65535 0 0]¿Vas a ir a entrenar?[n][w][e]
[f 2 1][bup 105 3 101 65535 0 0]Si vas a ir, ve sin mí. Te... Te veré luego.[n][w][e]

[msg MSG_020_0_0 [Kazushi Miyamoto]]
[f 2 1][bup 105 3 101 65535 0 0][vp 3 0 65535 10850 0 0]Muy bien, nos vemos enseguida.[n][w][e]
[f 2 1][bup 105 0 101 65535 0 0]Díselo a todos los demás, ¿vale? No voy a hacer pellas ni nada por el estilo.[n][w][e]

[msg MSG_021_0_0 [Kazushi Miyamoto]]
[f 2 1][bup 105 1 101 65535 0 0][vp 3 0 65535 10805 0 0]Eh, ¿cómo estás? Hoy voy a dar un montón de vueltas.[n][w][e]

[msg MSG_021_5_0 [Kazushi Miyamoto]]
[f 2 1][bup 105 1 101 65535 0 0]Por cierto, ¿cómo estás? Hoy voy a dar un montón de vueltas.[n][w][e]

[msg MSG_022_0_0 [Kazushi Miyamoto]]
[f 2 1][bup 105 1 101 65535 0 0][vp 3 0 65535 10867 0 0]Vale, ¡vamos![n][w][e]
[f 2 1][bup 105 0 101 65535 0 0]Ah, espera. He olvidado cambiar los tacos de mis zapatillas.[n][w][e]
[f 2 1][bup 105 0 101 65535 0 0]Nos vemos enseguida.[n][w][e]

[msg MSG_023_0_0 [Kazushi Miyamoto]]
[f 2 1][bup 105 0 101 65535 0 0][vp 3 0 65535 10812 0 0]Oye, ¿vas a ir a entrenar?[n][w][e]
[f 2 1][bup 105 1 101 65535 0 0]Venga ya, no me mires así. ¡Estoy bien![n][w][e]

[msg MSG_023_5_0 [Kazushi Miyamoto]]
[f 2 1][bup 105 0 101 65535 0 0]Ah, ¿vas a ir a entrenar?[n][w][e]
[f 2 1][bup 105 1 101 65535 0 0]Venga ya, no me mires así. ¡Estoy bien![n][w][e]

[msg MSG_024_0_0 [Kazushi Miyamoto]]
[f 2 1][bup 105 1 101 65535 0 0][vp 3 0 65535 10823 0 0]Genial, ¡vamos a darlo todo! ¡Hoy va a ser el día que te gane![n][w][e]

[msg MSG_025_0_0 [Kazushi Miyamoto]]
[f 2 1][bup 105 1 101 65535 0 0][vp 3 0 65535 10802 0 0]Oye, vas a ir a entrenar, ¿verdad? Hoy me siento de maravilla.[n][w][e]

[msg MSG_025_5_0 [Kazushi Miyamoto]]
[f 2 1][bup 105 1 101 65535 0 0]Vas a ir a entrenar, ¿verdad? Hoy me siento de maravilla.[n][w][e]

[msg MSG_026_0_0 [Kazushi Miyamoto]]
[f 2 1][bup 105 1 101 65535 0 0][vp 3 0 65535 10823 0 0]¡Estupendo! Si tú no estás, no me motivo, ¿me entiendes?[n][w][e]
[f 2 1][bup 105 3 101 65535 0 0]Últimamente, estoy más lento, así que ahora tengo que esforzarme el doble.[n][w][e]

[msg MSG_027_0_0 [Kazushi Miyamoto]]
[f 2 1][bup 105 0 101 65535 0 0][vp 3 0 65535 10885 0 0]¿Te apetece correr, [nl]? Bajemos a la pista.[n][w][e]

[msg MSG_027_5_0 [Kazushi Miyamoto]]
[f 2 1][bup 105 0 101 65535 0 0]Ah, sí. ¿Te apetece correr, [nl]? Bajemos a la pista.[n][w][e]

[msg MSG_028_0_0 [Kazushi Miyamoto]]
[f 2 1][bup 105 1 101 65535 0 0][vp 3 0 65535 10893 0 0]Bueno, no puedo forzarme demasiado, pero por lo menos tengo que estar allí para apoyarte.[n][w][e]

[msg MSG_029_0_0 [Kazushi Miyamoto]]
[f 2 1][bup 105 1 101 65535 0 0][vp 3 0 65535 10812 0 0]Eh, estás aquí. ¡Vamos a entrenar, [nl]![n][w][e]

[msg MSG_029_5_0 [Kazushi Miyamoto]]
[f 2 1][bup 105 1 101 65535 0 0]Ups, casi se me olvida. ¡Vamos a entrenar, [nl]![n][w][e]

[msg MSG_030_0_0 [Kazushi Miyamoto]]
[f 2 1][bup 105 0 101 65535 0 0][vp 3 0 65535 10868 0 0]Estupendo. ¡Te echo una carrera hasta abajo![n][w][e]
[f 2 1][bup 105 1 101 65535 0 0]Es broooma. Vamos a reservarnos para la pista, ¿vale?[n][w][e]

[msg MSG_031_0_0 [Kazushi Miyamoto]]
[f 2 1][bup 105 3 101 65535 0 0][vp 3 0 65535 10850 0 0]¿Eh? ¿Hoy no vas a ir?[n][w][e]
[f 2 1][bup 105 0 101 65535 0 0]Colega, ¿cómo vas a alcanzar mi nivel si no te esfuerzas? Será mejor que te pongas las pilas.[n][w][e]

[msg MSG_032_0_0 [Kazushi Miyamoto]]
[f 2 1][bup 105 3 101 65535 0 0][vp 3 0 65535 10850 0 0]¿Eh? ¿Hoy no vas a ir?[n][w][e]
[f 2 1][bup 105 0 101 65535 0 0]Si no te pones las pilas, vas a morder el polvo. Al menos practica en tu tiempo libre.[n][w][e]

[msg MSG_033_0_0 [Kazushi Miyamoto]]
[f 2 1]Unused[n][w][e]

[msg MSG_034_0_0 [Kazushi Miyamoto]]
[f 2 1][bup 105 3 101 65535 0 0][vp 3 0 65535 10872 0 0]Ah, vale. Ya nos vemos.[n][w][e]

[msg MSG_035_0_0 [Kazushi Miyamoto]]
[f 2 1][bup 105 0 101 65535 0 0][vp 3 0 65535 10872 0 0]Ah, ¿sí? Bueno, ve a correr cuando puedas.[n][w][e]

[msg MSG_036_0_0 [Kazushi Miyamoto]]
[f 2 1][bup 105 3 101 65535 0 0][vp 3 0 65535 10850 0 0]¿Eh? ¿Hoy no vas a ir?[n][w][e]
[f 2 1][bup 105 0 101 65535 0 0]¡Será mejor que no te estés oxidando, porque no pienso dejar que me ganes![n][w][e]

[msg MSG_037_0_0 [Kazushi Miyamoto]]
[f 2 1][bup 105 3 101 65535 0 0][vp 3 0 65535 10850 0 0]¿Qué? ¿Hoy no vas a ir?[n][w][e]
[f 2 1][bup 105 0 101 65535 0 0]Si estás ocupada, lo entiendo perfectamente..., pero espero que no estés huyendo de una revancha.[n][w][e]

[msg MSG_038_0_0 [Kazushi Miyamoto]]
[f 2 1][bup 105 3 101 65535 0 0][vp 3 0 65535 10850 0 0]Ah... Esperaba verte allí.[n][w][e]
[f 2 1][bup 105 0 101 65535 0 0]Bueno, intenta ir la próxima vez, ¿vale?[n][w][e]

[msg MSG_039_0_0 [Kazushi Miyamoto]]
[f 2 1][bup 105 0 101 65535 0 0][vp 3 0 65535 10850 0 0]¿Eh? ¿Hoy no vas a ir?[n][w][e]
[f 2 1][bup 105 1 101 65535 0 0]¡Si te dedicas a holgazanear, no me ganarás nunca![n][w][e]

[msg MND_GENERAL_EVENTPLAY]
[f 2 1]Mensaje enviado por el guion. Repetición del evento del comité.[n][w][e]

[msg MND_GENERAL_PERSPNA]
[f 2 1]Siento que podemos estrechar lazos gracias a la Persona del arcano [f 2 4 2], [clr 35][f 2 4 5][clr 27].[n][w][e]

[msg MND_GENERALSELECTMSG_MAX]
[f 2 1]Siento un vínculo irrompible con [f 2 4 0]...[n][w][e]

[msg MND_GENERALMSG_BS_MAX]
[f 2 1]Siento un vínculo irrompible con la pareja de ancianos...[n][w][e]

[msg MND_GENERALSELECTMSG_RAN]
[f 2 1]Creo que mi relación con [f 2 4 0] se estrechará pronto.[n][w][e]

[msg MND_GENERALMSG_BS_RANKUP]
[f 2 1]Creo que mi relación con la pareja de ancianos se estrechará pronto.[n][w][e]

[msg MND_GENERALSELECTMSG_NOR]
[f 2 1]No creo que mi vínculo con [f 2 4 0] se fortalezca más aunque pasemos tiempo juntos...[n][w][e]

[msg MND_GENERALMSG_BS_NORMAL [Kazushi Miyamoto]]
[f 2 1]No creo que nuestro vínculo se fortalezca más aunque pasemos tiempo juntos.[n][w][e]

[msg MND_GENERALSELECTMSG_MAX_2]
[f 2 1]Parece que tu relación no puede avanzar más...[n][w][e]
[f 2 1]¿Deberíamos pasar el rato juntos igualmente?[n][w][e]

[msg MND_GENERAL_MSG_SOLO_AS]
[f 2 1]¿Paso un rato con [f 2 4 0] después de clase?[n][w][e]

[msg MND_GENERAL_MSG_SOLO_DT]
[f 2 1]¿Debería pasar el día con [f 2 4 0]?[n][w][e]

[msg MND__GENERAL_MSG_NET]
[f 2 1]¿Debería pasar tiempo en línea jugando al MMORPG con [f 2 4 0]?[n][w][e]

[msg MND_GENERAL_MSG_SOLO_NT]
[f 2 1]¿Debería pasar la tarde con [f 2 4 0]...?[n][w][e]

[sel SEL_GENERALSELECTMSG_SOL top]
[f 2 1]Pasar tiempo con [f 2 4 0][e]
[f 2 1]Comprobar vínculo social[e]
[f 2 1]Da igual[e]

[msg MND_GENERAL_MSG_MULTIPLE]
[f 2 1]¿Paso un rato en [f 2 4 1] después de clase?[n][w][e]

[msg MND_GENERAL_MSG_FASHION_]
[f 2 1]¿Paso un rato en el club de moda después de clase?[n][w][e]

[msg MND_GENERAL_MSG_BOOKSTOR]
[f 2 1]¿Debería pasar el día en la librería?[n][w][e]

[msg MND_GENERAL_MSG_BOOKSTOR_2]
[f 2 1]¿Paso un rato en la librería después de clase?[n][w][e]

[msg MND_GENERAL_MSG_MULTIPLE_2]
[f 2 1]¿Debería pasar tiempo con [f 2 4 1] esta noche...?[n][w][e]

[sel SEL_GENERALSELECTMSG_MUL top]
[f 2 1]Pasar un rato: [f 2 4 1][e]
[f 2 1]Comprobar vínculo social[e]
[f 2 1]Da igual[e]

[sel SEL_GENERALSELECTMSG_FCL top]
[f 2 1]Ir al club de moda.[e]
[f 2 1]Comprobar vínculo social[e]
[f 2 1]Da igual[e]

[sel SEL_GENERALSELECTMSG_BS top]
[f 2 1]Entrar en la librería[e]
[f 2 1]Comprobar vínculo social[e]
[f 2 1]Da igual[e]

[msg MSG_GENERAL_EXAMREWARD_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4029 0 0]Ah.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]He visto tus notas. Buen trabajo.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Toma, de parte del director.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4108 0 0]Es tu recompensa por ser capaz de compaginar los estudios y nuestras... en fin, "actividades extraescolares".[n][w][e]

[msg MND_GENERAL_EXAMREWARD_0]
[f 2 1]DEV: UNUSED LABEL[n][w][e]

[msg MND_GENERAL_EXAMREWARD_0_2]
[f 2 1]Como he sacado la nota más alta en los exámenes, he obtenido: [f 4 4 1 37 1 3].[n][w][e]

[msg MSG_GENERAL_EXAMREWARD_0_2 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4029 0 0]Ah.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]He visto tus notas. Buen trabajo.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Toma, de parte del director.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4108 0 0]Es tu recompensa por ser capaz de compaginar los estudios y nuestras... en fin, "actividades extraescolares".[n][w][e]

[msg MSG_GENERAL_EXAMREWARD_0_3 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4077 0 0]Ah, cierto. Hay algo más.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]He visto tus notas. Buen trabajo.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Toma, de parte del director.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4131 0 0]Es tu recompensa por ser capaz de compaginar los estudios y nuestras... en fin, "actividades extraescolares".[n][w][e]

[msg MND_GENERAL_EXAMREWARD_0_3]
[f 2 1]Como he sacado la nota más alta en los exámenes, he obtenido: [f 4 4 1 37 1 3].[n][w][e]

[msg MSG_GENERAL_EXAMREWARD_0_4 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4029 0 0]Ah.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]He visto tus notas. Buen trabajo.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Toma, de parte del director.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4108 0 0]Es tu recompensa por ser capaz de compaginar los estudios y nuestras... en fin, "actividades extraescolares".[n][w][e]

[msg MND_GENERAL_EXAMREWARD_0_4]
[f 2 1]DEV: UNUSED LABEL[n][w][e]

[msg MSG_GENERAL_EXAMREWARD_0_5 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4029 0 0]Ah.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]He visto tus notas... Buen trabajo.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Es laudable que continúes destacando en el instituto mientras libras arduos combates.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0]Acepta este regalo para agradecerte tus esfuerzos.[n][w][e]

[msg MND_GENERAL_EXAMREWARD_0_5]
[f 2 1]未使用ラベルです。[n][w][e]

[msg MSG_GENERAL_EXAMREWARD_0_6 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 6 65535 0 0][vp 3 0 65535 4029 0 0]Ah.[n][w][e]
[f 2 1][bup 5 0 6 65535 0 0]He visto tus notas. Buen trabajo.[n][w][e]
[f 2 1][bup 5 0 6 65535 0 0]Es laudable que continúes destacando en el instituto mientras libras arduos combates.[n][w][e]
[f 2 1][bup 5 0 6 65535 0 0]Acepta este regalo para agradecerte tus esfuerzos.[n][w][e]

[msg MND_GENERAL_EXAMREWARD_1]
[f 2 1]Como he sacado la nota más alta en los exámenes, he obtenido: [f 4 4 1 37 1 3].[n][w][e]

[msg MSG_GENERAL_EXAMREWARD_1 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4029 0 0]Ah.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]He visto tus notas. Buen trabajo.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Es laudable que continúes destacando en el instituto mientras libras arduos combates.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4108 0 0]Acepta este regalo para agradecerte tus esfuerzos.[n][w][e]

[msg MND_GENERAL_EXAMREWARD_1_2]
[f 2 1]DEV: UNUSED LABEL[n][w][e]

[msg MND_GENERAL_EXAMREWARD_1_3]
[f 2 1]Como he sacado la nota más alta en los exámenes, he obtenido: [f 4 4 1 37 1 3].[n][w][e]

