[msg MSG_000_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 0 0 0 1 0 0]...[n][w][e]

[msg MSG_001_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 2 0 0]Mitsuru... Esa parte no entra en el examen.[n][w][e]

[msg MSG_002_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 3 65535 65535 0 0][vp 1 0 0 3 0 0]Ay, perdona. Es que me está costando concentrarme.[n][w][e]

[msg MSG_003_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 6 65535 65535 0 0][vp 1 0 0 4 0 0]Normal, con todo lo que está pasando... A mí también me ha afectado.[n][w][e]
[f 2 1][bup 4 6 65535 65535 0 0][vp 1 0 0 5 0 0]Perdona, [nl]. Sé que te hemos invitado nosotros, pero... Míranos, estamos fatal.[n][w][e]

[sel SEL_004_0_0 top]
[f 2 1]No es culpa tuya.[e]
[f 2 1]Tenemos que seguir adelante.[e]
[f 2 1]¿Queréis cantar una canción?[e]

[msg MSG_005_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 6 0 0]Je... Te estamos preocupando, ¿no?[n][w][e]

[msg MSG_006_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 1 65535 65535 0 0][vp 1 0 0 7 0 0]Está claro que los que estamos más afectados hoy somos nosotros.[n][w][e]

[msg MSG_007_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 8 0 0]Entiendo lo que dices, pero no todos lo llevamos tan bien como tú.[n][w][e]
[f 2 1][bup 4 1 65535 65535 0 0][vp 1 0 0 9 0 0][f 4 23 0 4 1 25 25]Je... Aunque, como veteranos que somos, deberíamos mostrar un poco más de dignidad ante ti.[n][w][e]

[msg MSG_008_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 10 0 0]Tienes razón.[n][w][e]

[msg MSG_009_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 11 0 0]Estás tan tranquila que hasta das miedo.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 12 0 0]Si estuvieras ocultando tus sentimientos, sería para darte un Óscar. Pero en tu caso...[n][w][e]

[msg MSG_010_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 13 0 0]Sí, dudo que esté fingiendo. Es su forma de ser y ya está.[n][w][e]

[msg MSG_011_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 14 0 0]Bueno, no podemos dejar que esto nos supere, ¿verdad?[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 15 0 0]Llueva o nieve, este será nuestro último examen en el instituto. Más razón para darlo todo.[n][w][e]

[msg MSG_012_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 1 65535 65535 0 0][vp 1 0 0 16 0 0]Cierto, no hay excusas para holgazanear. Tenemos que demostrar lo que hemos aprendido en estos tres años.[n][w][e]

[msg MSG_013_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 17 0 0]Veo pasión en tu mirada. A este paso, puede que tenga que renunciar a mi puesto de alumna aventajada.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 18 0 0][f 4 23 0 5 0 25 25]Aunque las notas no son más que un número. Lo importante es seguir mejorando con cada paso.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 19 0 0][f 4 23 0 5 1 25 25]Ojalá ambos cerremos este ciclo de manera triunfal.[n][w][e]

[sel SEL_014_0_0 top]
[f 2 1]Veo que todo ha vuelto a la normalidad.[e]
[f 2 1]Menuda competición tan reñida...[e]

[msg MSG_015_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 20 0 0]Perdona si te hemos preocupado. Tranquila, ya volvemos a tener la cabeza en su sitio.[n][w][e]

[msg MSG_016_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 21 0 0]Je, ¿y adivina quién ha sido la responsable? Espero que podamos compensarte con esta sesión de estudio.[n][w][e]

[msg MSG_017_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 22 0 0]En fin, ya hemos vagueado bastante. Tenemos que recuperar el tiempo perdido.[n][w][e]

[msg MND_018_0_0]
[f 2 1]Percibo la fuerte motivación[n]de Mitsuru y Akihiko.[n][w][e]
[f 2 1]Siento que estoy más concentrada que de costumbre.[n][w][e]

[msg MSG_019_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 4 65535 65535 0 0][vp 1 0 0 23 0 0]Vaya... El tiempo se ha pasado volando. Supongo que estábamos muy concentrados.[n][w][e]

[msg MSG_020_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 24 0 0]Creo que no me concentraba así desde hacía tiempo. He podido repasar toda la lección.[n][w][e]

[sel SEL_021_0_0 top]
[f 2 1]Os lo habéis tomado en serio, ¿eh?[e]
[f 2 1]Apenas podía seguiros el ritmo...[e]

[msg MSG_022_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 1 65535 65535 0 0][vp 1 0 0 25 0 0]¿Tú crees? Je, eso no ha sido nada. Aunque supongo que nos ha servido para ganarnos un poco tu respeto.[n][w][e]

[msg MSG_023_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 1 65535 65535 0 0][vp 1 0 0 26 0 0]Je, ¿en serio? Bueno, supongo que así nos hemos ganado un poco tu respeto.[n][w][e]

[msg MSG_024_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 27 0 0]Venga, ya casi hemos terminado. Seguid así.[n][w][e]

[msg MSG_025_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 1 65535 65535 0 0][vp 1 0 0 28 0 0]Bueno, eso ha sido todo. Ahora, a bordar esos exámenes.[n][w][e]

