[msg MSG_000_0_0 [Takaya]]
[f 2 1][bup 211 0 65535 65535 0 0][vp 1 0 0 1 0 0]Vaya, vaya, ¿qué tenemos aquí?[n][w][e]

[msg MSG_001_0_0 [Takaya]]
[f 2 1][bup 211 0 65535 65535 0 0][vp 1 0 0 2 0 0]Cuánto poder, cuánto caos... No seré tan tonto como para darle la espalda a semejante depredador.[n][w][e]
[f 2 1][bup 211 0 65535 65535 0 0][vp 1 0 0 3 0 0]Además, hoy nos acompaña una invitada inesperada.[n][w][e]
[f 2 1][bup 211 0 65535 65535 0 0][vp 1 0 0 4 0 0]No es una situación muy favorable, visto lo visto.[n][w][e]

[msg MSG_002_0_0 [Takaya]]
[f 2 1][bup 211 0 65535 65535 0 0][vp 1 0 0 5 0 0]¿Cómo pretendes salir de este pequeño aprieto?[n][w][e]

[sel SEL_003_0_0 top]
[f 2 1]Estoy aquí para ayudar.[e]
[f 2 1]No te acerques.[e]
[f 2 1]A ver lo que vales.[e]

[msg MSG_004_0_0 [Takaya]]
[f 2 1][bup 211 0 65535 65535 0 0][vp 1 0 0 6 0 0]"El enemigo de mi enemigo es mi amigo", ¿no?[n][w][e]
[f 2 1][bup 211 0 65535 65535 0 0][vp 1 0 0 7 0 0]Lógico.[n][w][e]

[msg MSG_005_0_0 [Takaya]]
[f 2 1][bup 211 1 65535 65535 0 0][vp 1 0 0 8 0 0]Muy bien. A ver de lo que eres capaz.[n][w][e]
[f 2 1][bup 211 0 65535 65535 0 0][vp 1 0 0 9 0 0][f 4 23 0 1 0 25 25]Pero, como no estés a la altura, acabaré también contigo.[n][w][e]

[msg MSG_006_0_0 [Takaya]]
[f 2 1][bup 211 0 65535 65535 0 0][vp 1 0 0 10 0 0]Mientras no me plantes cara, todo bien.[n][w][e]
[f 2 1][bup 211 0 65535 65535 0 0][vp 1 0 0 11 0 0]No sé de lo que es capaz nuestro enemigo, pero espero que sepas protegerte.[n][w][e]

