[msg MSG_001_0_0 [Mujer de buen humor]]
[f 2 1][f 5 21 1 692]¡Me encantan los chicos que saben conducir! Al final, los miro a ellos en lugar del paisaje.[n][w][e]
[f 2 1][f 5 21 1 692]Hoy me ha llevado mi churri, ni se te ocurra tirarle los tejos.[n][w][e]

[msg MSG_004_0_0 [Mujer de buen humor]]
[f 2 1][f 5 21 1 692]Deberíamos ir tirando o no llegaremos a tiempo.[n][w][e]
[f 2 1][f 5 21 1 692]Como le quería dar una sorpresa a mi novio, he reservado una cena elegante.[n][w][e]

