[msg MSG_000_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 3 65535 65535 0 0][vp 1 0 0 1 0 0]Ay, siento que la fiesta haya acabado siendo en mi casa...[n][w][e]
[f 2 1][bup 106 3 65535 65535 0 0][vp 1 0 0 2 0 0]Salí a comprar cosas para el entrenamiento de atletismo y me quedé sin dinero.[n][w][e]

[sel SEL_001_0_0 top]
[f 2 1]No pasa nada.[e]
[f 2 1]Qué habitación tan bonita.[e]
[f 2 1]¿Cosas para los niños?[e]

[msg MSG_002_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 3 0 0]Gracias.[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 4 0 0]Podría haber cogido cosas del almacén del insti, pero el tamaño no habría sido el adecuado.[n][w][e]

[msg MSG_003_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 5 0 0]¿E-en serio? Menos mal que saqué tiempo para ordenar.[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 6 0 0]Oye, come todo lo que quieras, ¿vale?[n][w][e]

[msg MSG_004_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 7 0 0]Sí, pero nada emocionante.[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 8 0 0][f 4 23 0 1 0 25 25]Cosas como suspensorios y bolsas de hielo. Los del insti no se ajustarían a ellos igual de bien.[n][w][e]

[msg MSG_005_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 9 0 0]Hemos tenido que dar el callo, pero me alegro de que decidiéramos entrenar a esos niños.[n][w][e]

[msg MSG_005_5_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 10 0 0]¿Tú qué piensas?[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0][vp 0 0 0 11 0 0]...[n][w][e]

[msg MSG_006_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 4 65535 65535 0 0][vp 1 0 0 12 0 0]¡Uy, perdona![n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 13 0 0][f 4 23 0 1 0 25 25]Es que no me había fijado en lo largas que tienes las pestañas. Creo que nunca te había mirado tan de cerca...[n][w][e]
[f 2 1][bup 106 3 65535 65535 1 0][vp 1 0 0 14 0 0][f 4 23 0 1 3 25 25]Quizá estoy un poco nerviosa porque estamos las dos solas.[n][w][e]

[msg MSG_007_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 15 0 0]Eh... M-mejor cambio de tema. ¡Voy a preguntarte algo![n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 16 0 0]Mmm... Ah, ¿te gustan los niños?[n][w][e]

[sel SEL_008_0_0 top]
[f 2 1]Sí.[e]
[f 2 1]No creas.[e]

[msg MSG_009_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 17 0 0]¿En serio? ¡A mí también! Me encanta la pureza que tienen y lo mucho que se esfuerzan. Me dan ganas de ayudarlos en todo lo que pueda.[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 18 0 0]Últimamente me he dado cuenta de que me gusta cuidar de la gente.[n][w][e]

[msg MSG_010_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 19 0 0]Mmm, entiendo.[n][w][e]

[msg MSG_010_3_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 20 0 0]Pues a esos niños les caías bien.[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 21 0 0]Hay algo en ti que atrae a la gente, [nl].[n][w][e]

[msg MSG_010_5_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 1 0][vp 1 0 0 22 0 0]Si hasta a mí me...[n][w][e]

[msg MSG_010_7_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 4 65535 65535 0 0][vp 1 0 0 23 0 0]Eh... ¡N-no me hagas caso![n][w][e]

[msg MSG_011_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 24 0 0]A ver... Venga, ¡siguiente pregunta![n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 25 0 0]Supongamos que te casas y que tienes un hijo.[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 26 0 0]¿Qué te gustaría que fuese, niño o niña?[n][w][e]

[sel SEL_012_0_0 top]
[f 2 1]Un niño.[e]
[f 2 1]Una niña.[e]
[f 2 1]Me da igual.[e]

[msg MSG_013_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 27 0 0][f 5 13 12 5 106] Ya veo... Un niño, ¿eh?[n][w][e]

[msg MSG_014_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 28 0 0]Los niños son mucho más enérgicos y unos trastos de cuidado, pero seguro que dan mucha alegría a la casa.[n][w][e]

[msg MSG_015_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 29 0 0][f 5 13 12 5 106]¡A mí también! ¡Creo que tenemos gustos muy parecidos![n][w][e]

[msg MSG_016_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 30 0 0]Podría ponerle diferentes conjuntos de ropa. ¡Sería mi pequeña ayudante![n][w][e]

[msg MSG_017_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 31 0 0]¿Así es como piensas tú?[n][w][e]

[msg MSG_018_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 32 0 0]¡Ah! Si con eso quieres decir que lo importante es que el bebé esté sano, entonces pienso lo mismo que tú.[n][w][e]

[msg MSG_019_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 3 65535 65535 0 0][vp 1 0 0 33 0 0]En cualquier caso, no me gustaría que se pareciera a mí. Ya sabes lo bruta que soy.[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 34 0 0][f 4 23 0 1 1 25 25]Pero, si se pareciera a ti, [nl], ¡seguro que sería una monada![n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 35 0 0]Y tendría mucha energía. Me pregunto si acabaría interesándose por el deporte...[n][w][e]

[msg MND_020_0_0]
[f 2 1]Yuko parece absorta en sus pensamientos.[n][w][e]
[f 2 1]Siento que mi relación con ella se ha fortalecido.[n][w][e]

[msg MSG_021_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 36 0 0]Por cierto, ¿dirías que te pareces más a tu padre o a tu madre?[n][w][e]
[f 2 1][bup 106 3 65535 65535 0 0][vp 1 0 0 37 0 0][f 4 23 0 1 3 25 25]A mí me suelen decir que soy la viva imagen de mi padre.[n][w][e]
[f 2 1][bup 106 3 65535 65535 0 0][vp 1 0 0 38 0 0]No es que me moleste, pero tengo sentimientos encontrados al respecto.[n][w][e]

[msg MSG_022_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 3 65535 65535 0 0][vp 1 0 0 39 0 0]No sé, no creo que nos parezcamos tanto. Yo no tengo las cejas tan pobladas, eso para empezar...[n][w][e]

[msg MND_023_0_0]
[f 2 1]He hablado un rato con Yuko[n]y después he vuelto a la residencia.[n][w][e]

