[msg MSG_000_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 3 0 65535 1067 0 0]Oye, [nl], ¿puedes hacer algo con este tío?[n][w][e]
[f 2 1][bup 2 6 65535 65535 0 0]Ha venido a llorarme para que le ayude con los exámenes.[n][w][e]

[msg MSG_001_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 65535 65535 0 0][vp 3 0 65535 2103 0 0]¡Venga ya, tienes que echarme una mano, Yuka![n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0][nf], tú también me ayudarás, ¿verdad? ¡¿Verdad?![n][w][e]

[sel SEL_002_0_0 top]
[f 2 1]Estudiemos juntos.[e]
[f 2 1]No, gracias.[e]

[msg MSG_003_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2045 0 0]¡Toma ya! ¡Gracias, tía! Entonces, me ayudas tú también, ¿no, Yuka?[n][w][e]

[msg MSG_004_0_0 [Yukari Takeba]]
[f 2 1][bup 2 6 65535 65535 0 0][vp 3 0 65535 1123 0 0]Qué remedio...[n][w][e]

[msg MSG_005_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 3 0 65535 1062 0 0]Sí, no te culpo. Estudiar con Junpei es una auténtica pérdida de tiempo.[n][w][e]

[msg MSG_006_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 65535 65535 0 0]¿De qué vas? ¡No soy tan malo![n][w][e]

[msg MSG_007_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 3 0 65535 1022 0 0]Aunque me molaría que [nl] se uniera...[n][w][e]

[msg MSG_008_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0]Ah, [nf]. ¿Me ayudas a empollar?[n][w][e]

[msg MSG_008_1_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2002 0 0]Ah, [nf].[n][w][e]

[msg MSG_008_2_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0]¿Me ayudas a empollar?[n][w][e]

[sel SEL_009_0_0 top]
[f 2 1]Estudiemos juntos.[e]
[f 2 1]No, gracias.[e]

[msg MSG_010_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2045 0 0]¡Toma ya! ¡Gracias, tía! Entonces, me ayudas tú también, ¿no, Yuka?[n][w][e]

[msg MSG_011_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 3 0 65535 1122 0 0]Qué remedio...[n][w][e]

[msg MSG_012_0_0 [Yukari Takeba]]
[f 2 1][bup 2 6 65535 65535 0 0][vp 3 0 65535 1022 0 0]Eso es porque nunca te lo tomas en serio, Junpei. Lo ideal sería que [nl] se uniera...[n][w][e]

[msg MND_Temperance]
[f 2 1]El arcano de la Templanza podría ayudarme a mejorar todavía más.[n][w][e]

