[msg MSG_000_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 1 65535 65535 0 0][vp 3 0 65535 11451 0 0][f 5 13 9 5 109]Disfruto mucho hablando contigo, [nl]...[n][w][e]

[msg MND_001_0_0]
[f 2 1]Mi vínculo con Chihiro se estrecha a medida que paso tiempo con ella...[n][w][e]

[msg MND_002_0_0]
[f 2 1]Siento que nuestra relación se fortalecerá pronto.[n][w][e]

[msg MND_003_0_0]
[f 2 1]Es hora de irse del instituto.[n][w][e]
[f 2 1]He decidido volver a la residencia.[n][w][e]

