[msg MSG_000_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 4 65535 65535 0 0][vp 1 0 0 1 0 0]Ay, qué tarde se ha hecho ya...[n][w][e]

[msg MSG_000_5_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 2 0 0]Cuando estoy contigo, a veces desearía que el reloj dejase de moverse.[n][w][e]

[msg MSG_000_7_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 3 0 0]Qué sentimiento más curioso. Podría ser...[n][w][e]
[f 2 1][bup 5 0 65535 65535 1 0][vp 0 0 0 4 0 0]...[n][w][e]

[msg MSG_001_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 4 65535 65535 1 0][vp 1 0 0 5 0 0]Ah, lo siento. Estaba hablando sola.[n][w][e]

[msg MSG_001_3_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 4 65535 65535 1 0][vp 1 0 0 6 0 0]¡No es nada! Venga ya, no me mires con esa cara.[n][w][e]

[msg MSG_001_5_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 3 65535 65535 1 0][vp 1 0 0 7 0 0]Vas a conseguir que me ponga roja...[n][w][e]

[msg MSG_001_7_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 3 65535 65535 1 0][vp 0 0 0 8 0 0]...[n][w][e]
[f 2 1][bup 5 3 65535 65535 1 0][vp 1 0 0 9 0 0]Hay demasiada luz aquí...[n][w][e]

[msg MSG_002_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 3 65535 65535 1 0][vp 1 0 0 10 0 0]¿Te importa si vamos a otro sitio?[n][w][e]

[msg MND_003_0_0 [Mensaje interno]]
[f 2 1]He pasado el tiempo con Mitsuru hasta que anocheció.[n][w][e]

