[msg MSG_000_0_0 [Bebe]]
[f 2 1][bup 112 1 65535 65535 0 0][vp 3 0 65535 11897 0 0]¡Qué bueno! ¡Una delicia![n][w][e]

[msg MSG_001_0_0 [Bebe]]
[f 2 1][bup 112 1 65535 65535 0 0]Los dulces japoneses sí que saben demostrar el atractivo del azúcar.[n][w][e]

[msg MSG_002_0_0 [Bebe]]
[f 2 1][bup 112 0 65535 65535 0 0][vp 3 0 65535 11873 0 0]Las azuki, aunque sean pequeñas, tienen un sabor divino...[n][w][e]
[f 2 1][bup 112 0 65535 65535 0 0]¿Qué son exactamente? Parecen huevos de insecto.[n][w][e]

[sel SEL_003_0_0 top]
[f 2 1]No estoy seguro.[e]
[f 2 1]Son justo eso.[e]
[f 2 1]Son judías.[e]

[msg MSG_004_0_0 [Bebe]]
[f 2 1][bup 112 3 65535 65535 0 0][vp 3 0 65535 11865 0 0]¿Ni tú lo sabes, [nf]?[n][w][e]
[f 2 1][bup 112 3 65535 65535 0 0]Pues, ça c'est un problème; es muy desconcertante. Quizá nunca descubramos la verdad...[n][w][e]

[msg MND_005_0_0]
[f 2 1]Bebe parece afligido.[n][w][e]
[f 2 1]Siento que hoy nuestra relación no ha cambiado nada...[n][w][e]

[msg MSG_006_0_0 [Bebe]]
[f 2 1][bup 112 4 65535 65535 0 0][vp 3 0 65535 11888 0 0][f 5 13 15 15 112]¡¿En serio?! ¿Quieres decir que he acertado?[n][w][e]
[f 2 1][bup 112 1 65535 65535 0 0][f 4 23 0 112 1 25 25]¡He vuelto a aprender algo nuevo sobre Japón![n][w][e]

[msg MND_007_0_0]
[f 2 1]Bebe parece contento.[n][w][e]
[f 2 1]Hoy has aprendido un poco más sobre él.[n][w][e]

[msg MSG_008_0_0 [Bebe]]
[f 2 1][bup 112 4 65535 65535 0 0][vp 3 0 65535 11888 0 0][f 5 13 15 30 112]¡¿Judías?! ¿Algo tan rojo y suave es una judía?[n][w][e]
[f 2 1][bup 112 1 65535 65535 0 0][f 4 23 0 112 1 25 25]¡He vuelto a aprender algo nuevo sobre Japón![n][w][e]

[msg MND_009_0_0]
[f 2 1]Bebe parece muy contento.[n][w][e]
[f 2 1]Siento que hoy nuestra relación se ha estrechado.[n][w][e]

[msg MSG_010_0_0 [Bebe]]
[f 2 1][bup 112 0 65535 65535 0 0][vp 3 0 65535 11908 0 0]Así que el secreto de los dulces japoneses debe de estar escondido en las azuki...[n][w][e]
[f 2 1][bup 112 0 65535 65535 0 0]¿Dónde podríamos comprar unas cuantas? Venga, busquemos azuki, [nf].[n][w][e]

[msg MND_011_0_0]
[f 2 1]Después de ir de compras con Bebe, volví a la residencia.[n][w][e]

