[msg MSG_MITURU_TARTAROS_1101 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0]Solo quedan dos días...[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Ha sido un viaje muy largo, pero por fin se acaba.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Somos los únicos capaces de derrotarla, así que no bajes la guardia hasta el final.[n][w][e]

[msg MSG_SANADA_TARTAROS_1106 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0]Parece que Mitsuru no va a volver por un tiempo...[n][w][e]
[f 2 1][bup 4 3 65535 65535 0 0]Me gustaría pensar que estará bien, pero... esta vez no estoy muy seguro.[n][w][e]

[msg MSG_JUNPEI_TARTAROS_1109 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0]¿Qué pensáis sobre ese tal Ryoji?[n][w][e]
[f 2 1][bup 3 3 65535 65535 0 0]¡El tío va por ahí pidiendo salir a todas las tías que ve![n][w][e]
[f 2 1][bup 3 3 65535 65535 0 0]Madre mía... Ojalá yo tuviese esas agallas...[n][w][e]

[msg MSG_YUKARI_TARTAROS_1109 [Yukari Takeba]]
[f 2 1][bup 2 3 65535 65535 0 0][f 4 25 2]......[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0][vp 3 0 65535 1022 0 0]*suspiro* Otro más no...[n][w][e]

[msg MSG_AEGIS_1110 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0]Mitsuru ha regresado a la residencia.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0]Parecía estar muy cansada. Se dirigió directa a su habitación sin decir una palabra...[n][w][e]

[sel SEL_005_0_0 top]
[f 2 1]Estará bien.[e]
[f 2 1]¿Estás preocupada?[e]

[msg MSG_AEGIS_1110_RE_1 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6024 0 0]Eso espero...[n][w][e]

[msg MSG_AEGIS_1110_RE_2 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6065 0 0]¿Preocupada...? No, no exactamente.[n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0]¿Cómo decirlo? Siento... Siento que soy responsable por lo que ha sucedido.[n][w][e]

[msg MSG_AMADA_TARTAROS_1113 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0]Em... Es cosa mía, ¿o Junpei parece estar triste por algo?[n][w][e]
[f 2 1][bup 8 0 65535 65535 0 0]Lleva un buen rato hablando consigo mismo... ¿Crees que tiene que ver con Chidori?[n][w][e]
[f 2 1][bup 8 0 65535 65535 0 0]Bueno, quizá lo mejor sea darle espacio hasta que sepamos qué le ocurre, ¿no?[n][w][e]

[msg MSG_MITURU_TARTAROS_1114 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0]Iré con vosotros a la torre Tártaro esta noche.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]...Mis disculpas por haberos preocupado a todos.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Nuestra única prioridad es hacer algo al respecto con la torre Tártaro.[n][w][e]
[f 2 1][bup 5 3 65535 65535 0 0]Quiero... contar con todos vosotros una vez más.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Y bueno, la excursión del instituto es la semana que viene, supongo que será divertido.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Pero por desgracia, Amada y Koromaru deberán quedarse aquí.[n][w][e]

[msg MSG_JUNPEI_TARTAROS_1116 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0]¡Tía, mañana es la excursión![n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]¡Me muero de ganas![n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]...Aunque qué faena que solamente vayamos a ir a Kioto.[n][w][e]

[msg MSG_AMADA_TARTAROS_1116_ [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 3 0 65535 7138 0 0]Mm, Junpei parece que ha recuperado sus ánimos.[n][w][e]
[f 2 1][bup 8 0 65535 65535 0 0]Supongo que no había razón por la que preocuparse por él.[n][w][e]

[msg MSG_JUNPEI_TARTAROS_1116_2 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2066 0 0]¿Eh? ¿De qué estáis hablando? ¡Yo siempre estoy de buen ánimo![n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Por cierto, más te vale portarte bien mientras estemos fuera. Nada de fiestas, ¿me oyes?[n][w][e]

[msg MSG_AMADA_TARTAROS_1116__2 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 3 0 65535 7026 0 0]Descuida.[n][w][e]
[f 2 1][bup 8 0 65535 65535 0 0]Ah, y por favor, no os molestéis en traerme un souvenir.[n][w][e]

[msg MSG_JUNPEI_TARTAROS_1116_3 [Junpei Iori]]
[f 2 1][bup 3 4 65535 65535 0 0][vp 3 0 65535 2098 0 0]...Oye, ¿qué es esto? ¿Psicología inversa o algo del estilo?[n][w][e]

[msg MSG_AMADA_TARTAROS_1116__3 [Ken Amada]]
[f 2 1][bup 8 1 65535 65535 0 0][vp 3 0 65535 7038 0 0]No, claro que no.[n][w][e]
[f 2 1][bup 8 1 65535 65535 0 0]Es solamente que Kioto tiene muchos aperitivos muy ricos.[n][w][e]

[msg MND_1119_1]
[f 2 1]Me ha llegado un mensaje...[n][w][e]

[msg MND_1119_2]
[f 2 1]Debería hablar con Junpei más tarde..[n][w][e]

[msg MSG_AMADA_TARTAROS_1120_ [Ken Amada]]
[f 2 1][bup 8 1 65535 65535 0 0]Anda, sí que ha sido rápido...[n][w][e]

[msg MSG_JUNPEI_TARTAROS_1120 [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0][vp 3 0 65535 2115 0 0]Jo, macho... Estoy reventado.[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]...Pero, ha sido muy divertido.[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]Te he traído unas cuantas "historias souvenir", luego te las cuento.[n][w][e]

[msg MSG_AMADA_TARTAROS_1120__2 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 3 0 65535 7068 0 0]Ah, vale.[n][w][e]
[f 2 1][bup 8 3 65535 65535 0 0]Qué... ganas que tengo.[n][w][e]

[msg MSG_JUNPEI_TARTAROS_1120_2 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2062 0 0]Esta noche no iremos a la torre Tártaro. Todo el mundo está muy cansado.[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Vayamos mañana por la noche...[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]A pesar de que no tengamos nada por lo que luchar...[n][w][e]

[msg MSG_FUKA_TARTAROS_1121 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0]Ryoji justo acaba de irse.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Había venido a estar con Junpei.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]No es típico que recibamos visita por aquí.[n][w][e]

[msg MSG_YUKARI_TARTAROS_1121 [Yukari Takeba]]
[f 2 1][bup 2 3 65535 65535 0 0][vp 3 0 65535 1028 0 0]Ya... No pasará nada, ¿no?[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0]En verdad me sorprende que no haya quedado con una chica.[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0]Oye, ¿y Aigis?[n][w][e]

[msg MSG_AMADA_TARTAROS_1121 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 3 0 65535 7001 0 0]La vi en el segundo piso.[n][w][e]

[msg MSG_YUKARI_TARTAROS_1121_2 [Yukari Takeba]]
[f 2 1][bup 2 4 65535 65535 0 0][vp 3 0 65535 1098 0 0]Ah, ¿sí?[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0]Mmm, a lo mejor está con Koromaru... No es normal que se vayan porque sí.[n][w][e]

[msg MSG_AMADA_TARTAROS_1123 [Ken Amada]]
[f 2 1][bup 8 3 65535 65535 0 0]...Junpei sigue en su habitación.[n][w][e]
[f 2 1][bup 8 3 65535 65535 0 0]Es muy duro perder a alguien tan cercano...[n][w][e]
[f 2 1][bup 8 3 65535 65535 0 0][f 4 25 8]......[n][w][e]
[f 2 1][bup 8 3 65535 65535 0 0]Espero que esté bien...[n][w][e]

[msg MSG_AMADA_TARTAROS_1127_ [Ken Amada]]
[f 2 1][bup 8 3 65535 65535 0 0]Junpei sigue sin sentirse bien...[n][w][e]
[f 2 1][bup 8 3 65535 65535 0 0]Me está preocupando mucho...[n][w][e]

[msg MSG_YUKARI_TARTAROS_1127 [Yukari Takeba]]
[f 2 1][bup 2 3 65535 65535 0 0][vp 3 0 65535 1065 0 0]Después de todo lo que le ha pasado... No me sorprende que se sienta mal.[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0]Aunque ha tenido mucha suerte esta semana...[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0]Nadie se ha dado cuenta de que se ha tomado estos días libres porque estábamos en la Experiencia Profesional.[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0]Espero que esté al menos un poco mejor...[n][w][e]

[msg MSG_AMADA_TARTAROS_1127__2 [Ken Amada]]
[f 2 1][bup 8 3 65535 65535 0 0][vp 3 0 65535 7086 0 0]...Me pienso a cargar a esos tíos de Strega.[n][w][e]
[f 2 1][bup 8 2 65535 65535 0 0]¡No aguanto más![n][w][e]

[msg MSG_YUKARI_TARTAROS_1127_2 [Yukari Takeba]]
[f 2 1][bup 2 3 65535 65535 0 0][vp 3 0 65535 1028 0 0]Sé cómo te sientes...[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0]Pero no tienes por qué hacerlo todo tú solo.[n][w][e]

[msg MSG_AMADA_TARTAROS_1127__3 [Ken Amada]]
[f 2 1][bup 8 3 65535 65535 0 0][vp 3 0 65535 7029 0 0]...Ya lo sé.[n][w][e]

[msg MSG_YUKARI_TARTAROS_1129 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0]Ya casi es luna llena.[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0]No ha aparecido ninguna Sombra, pero aún así me preocupa.[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 3 0 65535 1074 0 0]Ah, eso me recuerda...[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0]Ryoji está aquí otra vez. Está con Junpei.[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0]Junpei sigue estando bastante mal...[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0]Cómo me alegro de que tenga un amigo tan bueno como Ryoji.[n][w][e]

[msg MSG_WELCOME_YUKARI_OUT [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 3 0 65535 1019 0 0]Ah, eh... Hola.[n][w][e]

[msg MSG_WELCOME_YUKARI_OUT2 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 3 0 65535 1012 0 0]Eh... Hola...[n][w][e]

[msg MSG_WELCOME_JUNPEI_OUT [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2018 0 0]¿Qué pasa, tía?[n][w][e]

[msg MSG_WELCOME_JUNPEI_OUT2 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2012 0 0]Hola, tía...[n][w][e]

[msg MSG_WELCOME_MITSURU_OUT [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4018 0 0]Hola de nuevo.[n][w][e]

[msg MSG_WELCOME_MITSURU_OUT2 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4027 0 0]Hola de nuevo...[n][w][e]

[msg MSG_WELCOME_SANADA_OUT [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 3 0 65535 3017 0 0]Anda, has vuelto.[n][w][e]

[msg MSG_WELCOME_FUKA_OUT [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5018 0 0]Hola, ¿qué tal el día?[n][w][e]

[msg MSG_WELCOME_FUKA_OUT2 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5028 0 0]Ah... Hola...[n][w][e]

[msg MSG_WELCOME_AEGIS_OUT_RO [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 3 0 65535 6018 0 0]Saludos.[n][w][e]

[msg MSG_WELCOME_AEGIS_OUT [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6018 0 0]Saludos.[n][w][e]

[msg MSG_WELCOME_AEGIS_OUT_NA [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6017 0 0]Hola otra vez. Me alegro de volver a verte.[n][w][e]

[msg MSG_WELCOME_KOROMARU_OUT [Koromaru]]
[f 2 1][bup 9 0 65535 65535 0 0][vp 3 0 65535 8008 0 0]¡Guau![n][w][e]

[msg MSG_WELCOME_AMADA_OUT [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 3 0 65535 7020 0 0]¡Anda, hola![n][w][e]

[msg MSG_WELCOME_AMADA_OUT2 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 3 0 65535 7012 0 0]Ah... Hola...[n][w][e]

[msg MSG_WELCOME_ARAGAKI_OUT [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 3 0 65535 9014 0 0]Ey...[n][w][e]

[msg MSG_WELCOME_IKUTSUKI_OUT [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 3 0 65535 14201 0 0]Hola de nuevo.[n][w][e]

[msg MSG_WELCOME_YUKARI_IN [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 3 0 65535 1067 0 0]¡Ah, estás aquí![n][w][e]

[msg MSG_WELCOME_YUKARI_IN2 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 3 0 65535 1012 0 0]Ah, ¿ya has llegado? Perdona, no te había visto.[n][w][e]

[msg MSG_WELCOME_JUNPEI_IN [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2009 0 0]Eh, ¿qué pasa?[n][w][e]

[msg MSG_WELCOME_JUNPEI_IN2 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2012 0 0]Ah, hola...[n][w][e]

[msg MSG_WELCOME_MITSURU_IN [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4029 0 0]¿Eh? Ah, eres tú...[n][w][e]

[msg MSG_WELCOME_MITSURU_IN2 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4027 0 0]¿Mmm? Ah, ya estás aquí.[n][w][e]

[msg MSG_WELCOME_SANADA_IN [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 3 0 65535 3024 0 0]¿Has estado en tu habitación todo este tiempo?[n][w][e]

[msg MSG_WELCOME_FUKA_IN [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5067 0 0]¡Ah, hola! No sabía que ya estabas aquí.[n][w][e]

[msg MSG_WELCOME_FUKA_IN2 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5093 0 0]Anda, ¿estás aquí? Hola...[n][w][e]

[msg MSG_WELCOME_FUKA_IN_0712 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5067 0 0]Ah, [nl]...[n][w][e]

[msg MSG_WELCOME_AEGIS_IN_ROB [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 3 0 65535 6008 0 0]Buenas tardes.[n][w][e]

[msg MSG_WELCOME_AEGIS_IN [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6008 0 0]Buenas tardes.[n][w][e]

[msg MSG_WELCOME_AEGIS_IN_NAK [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6009 0 0]¿Qué tal el día? ¿Todo bien?[n][w][e]

[msg MSG_WELCOME_KOROMARU_IN [Koromaru]]
[f 2 1][bup 9 0 65535 65535 0 0][vp 3 0 65535 8001 0 0]¡Guau, guau![n][w][e]

[msg MSG_WELCOME_AMADA_IN [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 3 0 65535 7010 0 0]¿Has estudiado algo?[n][w][e]

[msg MSG_WELCOME_AMADA_IN2 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 3 0 65535 7012 0 0]¿Estabas aquí? Pues... hola.[n][w][e]

[msg MSG_WELCOME_ARAGAKI_IN [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 3 0 65535 9056 0 0]... ¿Qué hay?[n][w][e]

[msg MSG_WELCOME_IKUTSUKI_IN [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 3 0 65535 14204 0 0]Ah, no sabía que ya estabas aquí. He venido a hacer una visita rápida.[n][w][e]

[msg MND_SHYUKAKU_OK]
[f 2 1]Ahora que lo pienso, las hortalizas que planté en la azotea ya se podrán recolectar.[n][w][e]
[f 2 1]Debería ir a echarles un ojo...[n][w][e]

[msg MND_SHYUKAKU_TAIYAKI_OK]
[f 2 1]Ahora que lo pienso, las hortalizas que planté en la azotea ya se podrán recolectar.[n][w][e]
[f 2 1]Y el taiyaki que metí en la nevera también debería estar frío.[n][w][e]
[f 2 1]Debería ir a echarles un ojo...[n][w][e]

[msg MND_SHYUKAKU_TAIYAKI_OK_]
[f 2 1]Ahora que lo pienso, las hortalizas que planté en la azotea ya se podrán recolectar.[n][w][e]
[f 2 1]Y el taiyaki que metí en la nevera también debería estar frío.[n][w][e]
[f 2 1]Debería sacarlo de la nevera y dárselo a Elizabeth.[n][w][e]

[msg MND_TAIYAKI_OK]
[f 2 1]Ahora que lo pienso, el taiyaki que metí en la nevera ya debería estar frío.[n][w][e]
[f 2 1]Debería ir a por él.[n][w][e]

[msg MND_TAIYAKI_OK_QUEST]
[f 2 1]Ahora que lo pienso, el taiyaki que metí en la nevera ya debería estar frío.[n][w][e]
[f 2 1]Debería sacarlo de la nevera y dárselo a Elizabeth.[n][w][e]

[msg MSG_ERROR [Shuji Ikutsuki]]
[f 2 1]エラーメッセージです。[n][f 1 5 0]杉山まで報告ください。[n][w][e]

