[msg MSG_000_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 4 65535 65535 0 0][vp 1 0 0 1 0 0]¡Perdón por llegar tarde![n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 2 0 0][f 4 23 0 106 0 25 25]Le estaba preguntando al profe una duda que me ha surgido en clase.[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 3 0 0]Pero eso ha dado pie a más preguntas, así que me he quedado un buen rato.[n][w][e]

[msg MSG_001_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 3 65535 65535 0 0][vp 1 0 0 4 0 0]Uf, cómo pesa. No debería haberlo apiñado todo ahí.[n][w][e]

[sel SEL_002_0_0 top]
[f 2 1]¿Cosas para el equipo de atletismo?[e]
[f 2 1]¿Quieres que la lleve yo?[e]

[msg MSG_003_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 5 0 0]No, son libros de consulta.[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 6 0 0]Tenía muchas dudas y al final me he llevado los libros de todas las asignaturas.[n][w][e]

[msg MSG_004_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 7 0 0][f 5 13 12 5 106]¡No, tranqui! Me lo tomaré como un entrenamiento de fuerza.[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 8 0 0]Aun así, ¡estos libros pesan de lo lindo! Qué crudo lo tienen los alumnos de todo el mundo.[n][w][e]

[msg MSG_005_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 0 0 0 9 0 0]...[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 10 0 0]Siempre que vengo aquí, me pongo nostálgica.[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 11 0 0]Y tampoco ha pasado tanto tiempo desde que entrenamos a los niños, ¿eh?[n][w][e]

[sel SEL_006_0_0 top]
[f 2 1]Fue muy gratificante.[e]
[f 2 1]Es la edad...[e]

[msg MSG_007_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 12 0 0][f 5 13 12 5 106]Eso mismo. Me entregué en cuerpo y alma.[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 13 0 0]Jamás había corrido así, ni siquiera para el equipo de atletismo.[n][w][e]

[msg MSG_008_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 14 0 0]Jo, ¡tampoco hace falta que lo digas así![n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 15 0 0]Podrías haber dicho que he crecido o madurado. Hay que ver...[n][w][e]

[msg MSG_009_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 16 0 0]Ah, se me olvidaba. Toma.[n][w][e]

[msg MND_010_0_0]
[f 2 1]¡He obtenido (ITEM NAME)![n][w][e]

[msg MSG_011_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 17 0 0]Me lo han dado los niños. Me han dicho que "no se me olvide dárselo a [nl]".[n][w][e]

[sel SEL_012_0_0 top]
[f 2 1]Se han acordado de cómo me llamo.[e]
[f 2 1]¿Y la tuya?[e]
[f 2 1]Gracias.[e]

[msg MSG_013_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 18 0 0]Sí, normalmente te llamaban "entrenadora" o "novia".[n][w][e]

[msg MSG_014_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 19 0 0][f 5 13 12 5 106]A mí también me han dado una. Me han dicho que nunca se olvidarán de su tita.[n][w][e]

[msg MSG_015_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 20 0 0]Les diré a los chiquillos que te ha gustado. Seguro que se alegran un montón.[n][w][e]

[msg MSG_016_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 21 0 0]Cuando te regalan algo así, te olvidas de lo difícil que fue todo en su momento.[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 22 0 0]Casi que me dan ganas de repetirlo. ¿Qué opinas tú?[n][w][e]

[sel SEL_017_0_0 top]
[f 2 1]Si surge la oportunidad...[e]
[f 2 1]Solo si tú lo haces también.[e]

[msg MSG_018_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 23 0 0][f 5 13 12 15 106]Sí, tienes razón.[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 24 0 0][f 4 23 0 106 0 25 25]Aunque, bueno, me gustaría que ayudara más gente. A las dos solas nos costó mucho.[n][w][e]

[msg MSG_019_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 25 0 0]¿Eh? ¿Yo? Sí, bueno, supongo que quiero.[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 26 0 0]Pero la próxima vez deberíamos pedir ayuda a más gente. A las dos solas nos costó mucho.[n][w][e]

[msg MSG_020_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 27 0 0]En cuanto me ponga al día con el insti, me gustaría reflexionar. No solo sobre el entrenamiento, sino sobre disfrutar de la vida.[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 28 0 0][f 4 23 0 106 1 25 25]Je, je. Me muero de ganas. Bueno, ¡a hincar los codos![n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 29 0 0][f 4 23 0 106 0 25 25]Oye, avísame cuando tengas claro qué quieres hacer en el futuro, ¿vale?[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 30 0 0]Si te planteas algo parecido, ¡quizá podríamos estudiar juntas![n][w][e]

[msg MND_021_0_0]
[f 2 1]Yuko y yo hablamos durante un buen rato.[n][w][e]
[f 2 1]Siento un fuerte vínculo con Yuko.[n][w][e]

[msg SYS_021_5_0]
[f 2 1]El vínculo social de la Fuerza ha alcanzado su nivel máximo. ¡Ya puedes fusionar al rey de la sabiduría, [clr 35]Atavaka[clr 27]![n][w][e]

[msg MSG_022_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 31 0 0]Uy, mira qué hora es. Tengo que ir a comprar unos libros de consulta.[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 32 0 0]Nos vemos, [nl].[n][w][e]

[msg MND_023_0_0]
[f 2 1]Tras despedirme de Yuko, he decidido volver a la residencia.[n][w][e]

[msg MSG_024_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 4 65535 65535 0 0][vp 1 0 0 1 0 0]¡Perdón por llegar tarde![n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 2 0 0][f 4 23 0 106 0 25 25]Le estaba preguntando al profe una duda que me ha surgido en clase.[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 3 0 0]Pero eso ha dado pie a más preguntas, así que me he quedado un buen rato.[n][w][e]

[msg MSG_025_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 3 65535 65535 0 0][vp 1 0 0 4 0 0]Uf, cómo pesa. No debería haberlo apiñado todo ahí.[n][w][e]

[sel SEL_026_0_0 top]
[f 2 1]¿Cosas para el equipo de atletismo?[e]
[f 2 1]¿Quieres que la lleve yo?[e]

[msg MSG_027_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 5 0 0]No, son libros de consulta.[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 6 0 0]Tenía muchas dudas y al final me he llevado los libros de todas las asignaturas.[n][w][e]

[msg MSG_028_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 7 0 0][f 5 13 12 5 106]¡No, tranqui! Me lo tomaré como un entrenamiento de fuerza.[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 8 0 0]Aun así, ¡estos libros pesan de lo lindo! Qué crudo lo tienen los alumnos de todo el mundo.[n][w][e]

[msg MSG_029_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 0 0 0 9 0 0]...[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 10 0 0]Siempre que vengo aquí, me pongo nostálgica.[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 11 0 0]Y tampoco ha pasado tanto tiempo desde que entrenamos a los niños, ¿eh?[n][w][e]

[sel SEL_030_0_0 top]
[f 2 1]Fue muy gratificante.[e]
[f 2 1]Es la edad...[e]

[msg MSG_031_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 12 0 0][f 5 13 12 5 106]Eso mismo. Me entregué en cuerpo y alma.[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 13 0 0]Jamás había corrido así, ni siquiera para el equipo de atletismo.[n][w][e]

[msg MSG_032_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 14 0 0]Jo, ¡tampoco hace falta que lo digas así![n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 15 0 0]Podrías haber dicho que he crecido o madurado. Hay que ver...[n][w][e]

[msg MSG_033_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 16 0 0]Ah, se me olvidaba. Toma.[n][w][e]

[msg MND_034_0_0]
[f 2 1]¡He obtenido (ITEM NAME)![n][w][e]

[msg MSG_035_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 49 0 0]Me lo han dado los niños. Me han dicho que "no se me olvide dárselo a mi novia".[n][w][e]

[sel SEL_036_0_0 top]
[f 2 1]Novia...[e]
[f 2 1]¿Y la tuya?[e]
[f 2 1]Me halaga.[e]

[msg MSG_037_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 50 0 0]Les he dicho por activa y por pasiva que no es verdad, pero no me hacen ni caso.[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 51 0 0]Tú y yo juntas... Qué imaginación tienen los niños.[n][w][e]

[msg MSG_038_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 52 0 0][f 5 13 12 5 106]A mí también me han dado una. Me han dicho que nunca se olvidarán de su tita.[n][w][e]

[msg MSG_039_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 53 0 0][f 5 13 12 5 106] H-hala, no pensaba que fueras a reaccionar así...[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 54 0 0]¿No te resulta un tanto inusual?[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 55 0 0][f 4 23 0 106 1 25 25]Bueno, les diré a los chiquillos que te ha gustado. Seguro que se alegran un montón.[n][w][e]

[msg MSG_040_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 56 0 0]Cuando te regalan algo así, te olvidas de lo difícil que fue todo en su momento.[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 57 0 0]Casi que me dan ganas de repetirlo. ¿Qué opinas tú?[n][w][e]

[sel SEL_041_0_0 top]
[f 2 1]Si surge la oportunidad...[e]
[f 2 1]Me lo pensaré.[e]

[msg MSG_042_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 58 0 0][f 5 13 12 5 106]Je, je. Me alegra oír eso.[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 59 0 0][f 4 23 0 106 0 25 25]Y, ya que estamos, ¡la próxima vez deberíamos invitar a más gente para que entrenen con nosotras![n][w][e]

[msg MSG_043_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 3 65535 65535 0 0][vp 1 0 0 60 0 0]Dudo que pudiese hacerlo sola...[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 61 0 0][f 4 23 0 106 0 25 25]A las dos solas nos costó mucho. La próxima vez deberíamos invitar a más gente para que entrenen con nosotras.[n][w][e]

[msg MSG_044_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 62 0 0]En cuanto me ponga al día con el insti, me gustaría reflexionar. No solo sobre el entrenamiento, sino sobre disfrutar de la vida.[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 63 0 0][f 4 23 0 106 1 25 25]¡Me gustaría que me esperaras hasta entonces! Estudiaré mucho.[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 64 0 0][f 4 23 0 106 0 25 25]¡Ah, por cierto![n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 65 0 0]Si logro hacerme preparadora física...[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 66 0 0]¡Mi primer trabajo será elaborar una rutina de entrenamiento para ti, [nl]![n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 67 0 0]No creo que aspires a ser atleta profesional, así que no será demasiado intensa.[n][w][e]

[msg MND_045_0_0]
[f 2 1]Yuko y yo hablamos durante un buen rato.[n][w][e]
[f 2 1]Siento un fuerte vínculo con Yuko.[n][w][e]

[msg MSG_046_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 68 0 0]Ostras, ¡qué tarde es! ¡Tengo que ir a comprar unos libros de consulta![n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 69 0 0]Hasta luego, [nl].[n][w][e]

[msg MND_047_0_0]
[f 2 1]Tras despedirme de Yuko, he decidido volver a la residencia.[n][w][e]

