[msg MSG_000_0_0 [Koromaru]]
[f 2 1][bup 9 0 52 65535 0 0][vp 0 0 0 1 0 0]Haaa, haaa...[n][w][e]

[msg MSG_001_0_0 [Koromaru]]
[f 2 1][bup 9 0 52 65535 0 0][vp 1 0 0 2 0 0]¡Guau![n][w][e]

[msg MSG_002_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 52 65535 0 0][vp 1 0 0 3 0 0]Alguien está deseando irse, ¿eh?[n][w][e]

[msg MSG_003_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 52 65535 0 0][vp 1 0 0 4 0 0]Oye, ¿tú crees que Koromaru entiende lo que hacemos?[n][w][e]

[sel SEL_004_0_0 top]
[f 2 1]Seguro que sí.[e]
[f 2 1]Seguramente no.[e]
[f 2 1]Me pregunto si...[e]

[msg MSG_005_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 52 65535 0 0][vp 1 0 0 5 0 0]¿En serio? Aunque use una Persona, sigue siendo un perro.[n][w][e]

[msg MSG_006_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 52 65535 0 0][vp 1 0 0 6 0 0]Uf... Eso ha dolido, jefa.[n][w][e]

[msg MSG_007_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 52 65535 0 0][vp 1 0 0 7 0 0]Sí, a saber.[n][w][e]

[msg MSG_008_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 52 65535 0 0][vp 1 0 0 8 0 0]¡Eh, Koromaru! ¿Qué nos dices?[n][w][e]

[msg MSG_009_0_0 [Koromaru]]
[f 2 1][bup 9 0 52 65535 0 0][vp 0 0 0 9 0 0]Haaa, haaa...[n][w][e]

[msg MSG_010_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 52 65535 0 0][vp 1 0 0 10 0 0]¿Eh? ¿Nada?[n][w][e]

[msg MSG_011_0_0 [Aigis]]
[f 2 1][bup 7 0 52 65535 0 0][vp 1 0 0 11 0 0]Dice que la determinación se demuestra con hechos.[n][w][e]

[msg MSG_012_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 52 65535 0 0][vp 1 0 0 12 0 0]P-pero si es un perro...[n][w][e]

[msg MSG_013_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 52 65535 0 0][vp 1 0 0 13 0 0]¡Eres un fuera de serie! El perro MÁS molón del mundo.[n][w][e]

