[msg MSG_000_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 4 65535 65535 0 0][vp 3 0 65535 14219 0 0]¿Eh? ¿Necesitas algo para limpiar las gafas?[n][w][e]
[f 2 1][bup 222 4 65535 65535 0 0]Sí, claro que tengo algo, pero... tú no llevas gafas.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0][vp 3 0 65535 14224 0 0]Ya veo.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0]¡Está claro, es para un amigo! ¿Lo pillas? Je, je...[n][w][e]
[f 2 1][bup 222 1 65535 65535 0 0]Un momento, que te lo traigo.[n][w][e]

[msg MSG_012_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 4 65535 65535 0 0][vp 3 0 65535 14219 0 0]¿Eh? ¿Necesitas algo para limpiar las gafas?[n][w][e]
[f 2 1][bup 222 4 65535 65535 0 0]Por supuesto que tengo algo, pero... tú no llevas gafas.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0]Si necesitas un paño para los cristales, tengo uno de sobra.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0][vp 3 0 65535 14207 0 0]Espera.[n][w][e]

[msg MSG_001_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 1 65535 65535 0 0][vp 3 0 65535 14225 0 0]Toma. Tiene mal aspecto, pero lo cierto es que funciona de maravilla.[n][w][e]

[msg MSG_002_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0]Ah, y aquí tienes otro regalito.[n][w][e]

[msg MSG_003_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 3 0 65535 14221 0 0]Es el objeto secreto que quería usar en la fiesta de despedida de los alumnos de tercer año.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0]Pero le quedará mejor a una chica moderna como tú que a un viejales como yo.[n][w][e]

[msg MSG_004_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 1 65535 65535 0 0]Parece menterio que tu porte desprenda tanto estilo. ¿Cómo lo haces?[n][w][e]
[f 2 1][bup 222 1 65535 65535 0 0][vp 3 0 65535 14237 0 0]¿Es que no lo ves? ¡Tienes mucho ojo para las gafas![n][w][e]

[msg MSG_014_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0]Es el objeto secreto con el que quería sorprender a Aragaki la próxima vez que nos viéramos.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0]¡Seguro que conseguiría que esa expresión estoica suya estallara de la risa! Al menos, ese era el plan.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0][vp 3 0 65535 14232 0 0]¿Y si te lo quedas tú? Me encantaría que le dieras buen uso.[n][w][e]

