[msg MSG_000_0_0 [Joven delgado]]
[f 2 1][bup 117 0 65535 65535 0 0][vp 3 0 65535 12807 0 0]Tú...[n][w][e]
[f 2 1][bup 117 0 65535 65535 0 0]Desde mi punto de vista, la gente lleva una vida de cuento de hadas.[n][w][e]
[f 2 1][bup 117 0 65535 65535 0 0]Y eso te incluye a ti. ¿O acaso te consideras víctima del sufrimiento?[n][w][e]

[sel SEL_001_0_0 top]
[f 2 1]¿Eh?[e]
[f 2 1]Yo soy normal.[e]

[msg MSG_002_0_0 [Joven delgado]]
[f 2 1][bup 117 0 65535 65535 0 0][vp 3 0 65535 12841 0 0]Da igual. La esperanza y la desesperación no son sino dos caras de la misma moneda.[n][w][e]

[msg MND_003_0_0]
[f 2 1]No se entiende muy bien qué intenta decir...[n][w][e]
[f 2 1]Para hablar con él, necesito mejorar mi [f 4 30 0 1 1 0]...[n][w][e]
[f 2 1]Si tuviera al menos [f 4 31 0 4 1 0], quizá pudiera entenderlo.[n][w][e]

[msg MSG_004_0_0 [Joven delgado]]
[f 2 1][bup 117 0 65535 65535 0 0][vp 3 0 65535 12854 0 0]Ya veo. Poco más hay que discutir.[n][w][e]

[msg MSG_005_0_0 [Joven delgado]]
[f 2 1][bup 117 0 65535 65535 0 0][vp 3 0 65535 12807 19 0]Tienes los ojos muy claros...[n][w][e]
[f 2 1][bup 117 0 65535 65535 0 0]Tu alma ha de arder con intensidad.[n][w][e]

[msg MND_006_0_0]
[f 2 1]Parece que he llamado la atención de ese joven gracias a mi impresionante [f 4 30 0 1 1 0].[n][w][e]
[f 2 1]Podría ser una buena oportunidad para conocerlo mejor.[n][w][e]

[msg MSG_007_0_0 [Joven delgado]]
[f 2 1][bup 117 0 65535 65535 0 0][vp 3 0 65535 12835 0 0]El reflejo de mí que veo en tus ojos y mi yo real..., si es que eso existe..., ¿cuán lejos están?[n][w][e]

[sel SEL_008_0_0 top]
[f 2 1]Casi nada.[e]
[f 2 1]Casi un brazo de largo.[e]
[f 2 1]¿Tres años luz?[e]

[msg MSG_009_0_0 [Joven delgado]]
[f 2 1][bup 117 0 65535 65535 0 0][vp 3 0 65535 12876 0 0]Mmm... Eso me vale.[n][w][e]

[msg MSG_010_0_0 [Joven delgado]]
[f 2 1][bup 117 1 65535 65535 0 0][vp 3 0 65535 12892 0 0]Ah, ¿lo dices en el sentido estricto de la palabra? Ja, ja. Supongo que llevas razón.[n][w][e]

[msg MSG_011_0_0 [Joven delgado]]
[f 2 1][bup 117 0 65535 65535 0 0][vp 3 0 65535 12819 0 0]Sí, eso parece... Una distancia muy larga y solitaria.[n][w][e]

[msg MSG_012_0_0 [Joven delgado]]
[f 2 1][bup 117 0 65535 65535 0 0][vp 3 0 65535 12863 0 0]Tus palabras son muy hermosas. Si tuviera algo con lo que escribir, las anotaría.[n][w][e]
[f 2 1][bup 117 0 65535 65535 0 0]Tengo una pluma estilográfica... Usa tinta roja, roja como la sangre.[n][w][e]
[f 2 1][bup 117 3 65535 65535 0 0]Mi pluma es mi compañera, mi portavoz y mi amiga. No obstante, parece que ha desaparecido.[n][w][e]
[f 2 1][bup 117 3 65535 65535 0 0]Sin ella, mis gritos están silenciados...[n][w][e]

[msg MND_013_0_0]
[f 2 1]El joven parece estar triste.[n][w][e]
[f 2 1]Parece que ha perdido su pluma.[n][w][e]

[msg MSG_014_0_0 [Joven delgado]]
[f 2 1][bup 117 0 65535 65535 0 0][vp 3 0 65535 12835 0 0]Aún estoy buscando mi pluma estilográfica. Avísame si la encuentras, por favor.[n][w][e]
[f 2 1][bup 117 0 65535 65535 0 0]Quizá la haya secuestrado la criatura de pelaje blanco y ojos rojos y brillantes...[n][w][e]

[msg MND_015_0_0]
[f 2 1]Parece que ha perdido su pluma.[n][w][e]

[msg MSG_016_0_0 [Joven delgado]]
[f 2 1][bup 117 0 65535 65535 0 0][vp 3 0 65535 12864 0 0]Ah... Esa pluma que llevas..., ¿es mi pluma estilográfica?[n][w][e]

[msg MND_017_0_0]
[f 2 1]Le he dado la [f 4 4 1 37 1 0].[n][w][e]

[msg MSG_018_0_0 [Joven delgado]]
[f 2 1][bup 117 1 65535 65535 0 0][vp 3 0 65535 12830 0 0]Aaah... Bienvenida a casa, amiga mía. Gracias por encontrarla.[n][w][e]
[f 2 1][bup 117 1 65535 65535 0 0]Ahora, el poderoso grito que brama en silencio dentro de mí ha recuperado su voz... Mi "diario"...[n][w][e]
[f 2 1][bup 117 1 65535 65535 0 0]Me llamo Akinari Kamiki.[n][w][e]

[msg MSG_019_0_0 [Akinari Kamiki]]
[f 2 1][bup 117 1 65535 65535 0 0][vp 3 0 65535 12807 0 0]Siéntate aquí, si quieres. Escribiré algo para nosotros dos.[n][w][e]

[msg MND_020_0_0]
[f 2 1]Parece que se ha interesado por mí.[n][w][e]
[f 2 1]¿Debería pasar el día con él?[n][w][e]

[sel SEL_021_0_0 top]
[f 2 1]Pasar un rato con él.[e]
[f 2 1]Ahora no[e]

[msg MSG_022_0_0 [Akinari Kamiki]]
[f 2 1][bup 117 3 65535 65535 0 0][vp 3 0 65535 12854 0 0]Qué lástima... Hasta la vista, mecenas mío.[n][w][e]

[msg MSG_023_0_0 [Akinari Kamiki]]
[f 2 1][bup 117 0 65535 65535 0 0][vp 3 0 65535 12802 0 0]Ah, eres tú.[n][w][e]
[f 2 1][bup 117 0 65535 65535 0 0]¿Por qué no te sientas? Este banco es demasiado grande como para que me siente solo yo.[n][w][e]

[msg MND_024_0_0]
[f 2 1]Creo que Kamiki disfrutaría de mi compañía.[n][w][e]

[msg MSG_025_0_0 [Akinari Kamiki]]
[f 2 1][bup 117 3 65535 65535 0 0][vp 3 0 65535 12810 0 0]Ah, eres tú... Cof, cof.[n][w][e]
[f 2 1][bup 117 5 65535 65535 0 0]Cof, cof. Uf, uf...[n][w][e]
[f 2 1][bup 117 5 65535 65535 0 0]Cof, cof.[n][w][e]

[msg MSG_026_0_0 [Akinari Kamiki]]
[f 2 1][bup 117 3 65535 65535 0 0][vp 3 0 65535 12894 0 0]Lo siento... Arf. arf. Arf. arf.[n][w][e]
[f 2 1][bup 117 5 65535 65535 0 0]¿Te importa... Arf. arf. quedarte... Arf. arf. hasta que recupere el aliento...?[n][w][e]

[msg MSG_027_0_0 [Akinari Kamiki]]
[f 2 1][bup 117 1 65535 65535 0 0][vp 3 0 65535 12822 0 0]Ah, hola.[n][w][e]
[f 2 1][bup 117 1 65535 65535 0 0]Me alegro de verte. Por favor, siéntate si lo deseas.[n][w][e]

[msg MND_028_0_0]
[f 2 1]¿Debería pasar el día con Kamiki?[n][w][e]

[sel SEL_029_0_0 top]
[f 2 1]Pasar un rato con él.[e]
[f 2 1]Comprobar estado de vínculo social[e]
[f 2 1]Ahora no[e]

[msg MSG_030_0_0 [Akinari Kamiki]]
[f 2 1][bup 117 1 65535 65535 0 0][vp 3 0 65535 12818 0 0]Entonces, este banco será nuestro punto de encuentro.[n][w][e]

[msg MSG_031_0_0 [Akinari Kamiki]]
[f 2 1][bup 117 3 65535 65535 0 0][vp 3 0 65535 12830 0 0]Gracias...[n][w][e]

[msg MSG_032_0_0 [Akinari Kamiki]]
[f 2 1][bup 117 3 65535 65535 0 0][vp 3 0 65535 12854 0 0]Entiendo... Tal vez podamos hablar en otra ocasión.[n][w][e]

[msg MSG_033_0_0 [Akinari Kamiki]]
[f 2 1][bup 117 0 65535 65535 0 0][vp 3 0 65535 12807 0 0]¿Tú...?[n][w][e]
[f 2 1][bup 117 3 65535 65535 0 0][f 4 25 117]...[n][w][e]
[f 2 1][bup 117 0 65535 65535 0 0]Ah, nada.[n][w][e]
[f 2 1][bup 117 0 65535 65535 0 0]¿Por qué no te sientas? Este banco es demasiado grande como para que me siente solo yo.[n][w][e]

[msg MSG_034_0_0 [Akinari Kamiki]]
[f 2 1][bup 117 0 65535 65535 0 0][vp 3 0 65535 12818 0 0]Entonces, este banco será nuestro punto de encuentro.[n][w][e]

[msg MSG_035_0_0 [Akinari Kamiki]]
[f 2 1][bup 117 3 65535 65535 0 0][vp 3 0 65535 12854 0 0]Ya veo... Bueno, quizá sea lo mejor.[n][w][e]

[msg MSG_036_0_0 [Akinari Kamiki]]
[f 2 1][bup 117 0 65535 65535 0 0][vp 3 0 65535 12822 0 0]Ah, eres tú.[n][w][e]
[f 2 1][bup 117 3 65535 65535 0 0]¿Te apetecería que hablásemos otra vez más? Solo si es de tu agrado, claro...[n][w][e]

[msg MSG_037_0_0 [Akinari Kamiki]]
[f 2 1][bup 117 1 65535 65535 0 0][vp 3 0 65535 12833 0 0]Gracias. Creo que en el fondo, te estaba esperando.[n][w][e]

[msg MSG_038_0_0 [Akinari Kamiki]]
[f 2 1][bup 117 3 65535 65535 0 0][vp 3 0 65535 12810 0 0]Ah, eres tú... Cof, cof.[n][w][e]
[f 2 1][bup 117 5 65535 65535 0 0]Cof, cof. Uf, uf...[n][w][e]
[f 2 1][bup 117 5 65535 65535 0 0]Cof, cof.[n][w][e]

[msg MSG_039_0_0 [Akinari Kamiki]]
[f 2 1][bup 117 5 65535 65535 0 0][vp 3 0 65535 12894 0 0]Lo siento... Fiu. Ya estoy otra vez... Arf. arf. Arf. arf.[n][w][e]
[f 2 1][bup 117 3 65535 65535 0 0]Se me pasará en un momento... ¿Te importa... quedarte conmigo hasta que se me pase?[n][w][e]

[msg MSG_040_0_0 [Akinari Kamiki]]
[f 2 1][bup 117 0 65535 65535 0 0][vp 3 0 65535 12833 0 0]Gracias, eres muy amable...[n][w][e]

[msg MSG_041_0_0 [Akinari Kamiki]]
[f 2 1][bup 117 0 65535 65535 0 0][vp 3 0 65535 12809 0 0]Ah, eres tú.[n][w][e]
[f 2 1][bup 117 3 65535 65535 0 0]Si el destino lo permite, me gustaría volver a hablar contigo.[n][w][e]

[msg MSG_042_0_0 [Akinari Kamiki]]
[f 2 1][bup 117 1 65535 65535 0 0][vp 3 0 65535 12832 0 0]Vaya, me alegra oír eso.[n][w][e]
[f 2 1][bup 117 1 65535 65535 0 0]Gracias a nuestras charlas, este banco se convierte en el puente que me conecta con la humanidad.[n][w][e]

[msg MSG_043_0_0 [Akinari Kamiki]]
[f 2 1][bup 117 0 65535 65535 0 0][vp 3 0 65535 12822 0 0]Ah, eres tú.[n][w][e]
[f 2 1][bup 117 0 65535 65535 0 0]Estaba contando las horas para poder hablar contigo de nuevo.[n][w][e]

[msg MSG_044_0_0 [Akinari Kamiki]]
[f 2 1][bup 117 1 65535 65535 0 0][vp 3 0 65535 12830 0 0]¿Piensas quedarte? Te lo agradecería un montón...[n][w][e]

[msg MSG_045_0_0 [Akinari Kamiki]]
[f 2 1][bup 117 3 65535 65535 0 0][vp 3 0 65535 12810 0 0]Ah, eres tú... Cof, cof. Cof, cof.[n][w][e]
[f 2 1][bup 117 5 65535 65535 0 0]Fiuu. Fiuu.[n][w][e]
[f 2 1][bup 117 5 65535 65535 0 0]¡Cof, cof! ¡Cof, cof! Arf. arf. Arf. arf.[n][w][e]

[msg MSG_046_0_0 [Akinari Kamiki]]
[f 2 1][bup 117 3 65535 65535 0 0][vp 3 0 65535 12896 0 0]Estoy... cof... bien...[n][w][e]
[f 2 1][bup 117 5 65535 65535 0 0]Perdona... Cof, cof. Se me pasará enseguida...[n][w][e]

[msg MSG_047_0_0 [Akinari Kamiki]]
[f 2 1][bup 117 3 65535 65535 0 0][vp 3 0 65535 12894 0 0]Graci... ¡Cof, cof! Me alegro... de que hayas venido.[n][w][e]

[msg MSG_048_0_0 [Akinari Kamiki]]
[f 2 1][bup 117 0 65535 65535 0 0][vp 3 0 65535 12802 0 0]Ah, eres tú...[n][w][e]
[f 2 1][bup 117 1 65535 65535 0 0]¿Te gustaría charlar un rato? Puedes sentarte aquí, como siempre...[n][w][e]

[msg MSG_049_0_0 [Akinari Kamiki]]
[f 2 1][bup 117 1 65535 65535 0 0][vp 3 0 65535 12830 0 0]Gracias. Hoy es un día especial.[n][w][e]

[msg MSG_050_0_0 [Akinari Kamiki]]
[f 2 1][bup 117 1 65535 65535 0 0][vp 3 0 65535 12830 0 0]Gracias...[n][w][e]
[f 2 1][bup 117 1 65535 65535 0 0]Este banco es nuestro lugar especial.[n][w][e]

[msg MSG_051_0_0 [Akinari Kamiki]]
[f 2 1][bup 117 5 65535 65535 0 0][vp 3 0 65535 12896 0 0]Ya veo... ¡Cof, cof! Arf. arf. Arf. arf.[n][w][e]
[f 2 1][bup 117 3 65535 65535 0 0]No te preocupes, estoy bien. Solo necesito... descansar aquí un ratito...[n][w][e]

[msg MSG_052_0_0 [Akinari Kamiki]]
[f 2 1][bup 117 5 65535 65535 0 0][vp 3 0 65535 12896 0 0]Ya veo... ¡Cof, cof! Arf. arf. Arf. arf.[n][w][e]
[f 2 1][bup 117 3 65535 65535 0 0]Estoy bien, pero... quiero descansar un ratito más.[n][w][e]

[msg MSG_053_0_0 [Akinari Kamiki]]
[f 2 1][bup 117 0 65535 65535 0 0][vp 3 0 65535 12814 0 0]Te entiendo; no pasa nada. La dueña de tu tiempo eres tú.[n][w][e]

[msg MSG_054_0_0 [Akinari Kamiki]]
[f 2 1][bup 117 0 65535 65535 0 0][vp 3 0 65535 12814 0 0]No pasa nada... Me encantaría volver a verte pronto.[n][w][e]

[msg MSG_055_0_0 [Akinari Kamiki]]
[f 2 1][bup 117 5 65535 65535 0 0][vp 3 0 65535 12896 0 0]Ya veo... ¡Cof, cof! Arf. arf. Arf. arf.[n][w][e]
[f 2 1][bup 117 3 65535 65535 0 0]No pasa nada... Estoy bien. Aquí se está a gustito.[n][w][e]

[msg MSG_056_0_0 [Akinari Kamiki]]
[f 2 1][bup 117 0 65535 65535 0 0][vp 3 0 65535 12817 0 0]Ya veo... Espero verte pronto.[n][w][e]

[msg MSG_057_0_0 [Akinari Kamiki]]
[f 2 1][bup 117 0 65535 65535 0 0][vp 3 0 65535 12818 0 0]Bueno.[n][w][e]
[f 2 1][bup 117 1 65535 65535 0 0]Nos vemos luego, entonces. Yo me voy a quedar aquí un ratito.[n][w][e]

[msg MND_GENERAL_EVENTPLAY]
[f 2 1]Mensaje enviado por el guion. Repetición del evento del comité.[n][w][e]

[msg MND_GENERAL_PERSPNA]
[f 2 1]Siento que podemos estrechar lazos gracias a la Persona del arcano [f 2 4 2], [clr 35][f 2 4 5][clr 27].[n][w][e]

[msg MND_GENERALSELECTMSG_MAX]
[f 2 1]Siento un vínculo irrompible con [f 2 4 0]...[n][w][e]

[msg MND_GENERALMSG_BS_MAX]
[f 2 1]Siento un vínculo irrompible con la pareja de ancianos...[n][w][e]

[msg MND_GENERALSELECTMSG_RAN]
[f 2 1]Creo que mi relación con [f 2 4 0] se estrechará pronto.[n][w][e]

[msg MND_GENERALMSG_BS_RANKUP]
[f 2 1]Creo que mi relación con la pareja de ancianos se estrechará pronto.[n][w][e]

[msg MND_GENERALSELECTMSG_NOR]
[f 2 1]No creo que mi vínculo con [f 2 4 0] se fortalezca más aunque pasemos tiempo juntos...[n][w][e]

[msg MND_GENERALMSG_BS_NORMAL [Akinari Kamiki]]
[f 2 1]No creo que nuestro vínculo se fortalezca más aunque pasemos tiempo juntos.[n][w][e]

[msg MND_GENERALSELECTMSG_MAX_2]
[f 2 1]Parece que tu relación no puede avanzar más...[n][w][e]
[f 2 1]¿Deberíamos pasar el rato juntos igualmente?[n][w][e]

[msg MND_GENERAL_MSG_SOLO_AS]
[f 2 1]¿Paso un rato con [f 2 4 0] después de clase?[n][w][e]

[msg MND_GENERAL_MSG_SOLO_DT]
[f 2 1]¿Debería pasar el día con [f 2 4 0]?[n][w][e]

[msg MND__GENERAL_MSG_NET]
[f 2 1]¿Debería pasar tiempo en línea jugando al MMORPG con [f 2 4 0]?[n][w][e]

[msg MND_GENERAL_MSG_SOLO_NT]
[f 2 1]¿Debería pasar la tarde con [f 2 4 0]...?[n][w][e]

[sel SEL_GENERALSELECTMSG_SOL top]
[f 2 1]Pasar tiempo con [f 2 4 0][e]
[f 2 1]Comprobar vínculo social[e]
[f 2 1]Da igual[e]

[msg MND_GENERAL_MSG_MULTIPLE]
[f 2 1]¿Paso un rato en [f 2 4 1] después de clase?[n][w][e]

[msg MND_GENERAL_MSG_FASHION_]
[f 2 1]¿Paso un rato en el club de moda después de clase?[n][w][e]

[msg MND_GENERAL_MSG_BOOKSTOR]
[f 2 1]¿Debería pasar el día en la librería?[n][w][e]

[msg MND_GENERAL_MSG_BOOKSTOR_2]
[f 2 1]¿Paso un rato en la librería después de clase?[n][w][e]

[msg MND_GENERAL_MSG_MULTIPLE_2]
[f 2 1]¿Debería pasar tiempo con [f 2 4 1] esta noche...?[n][w][e]

[sel SEL_GENERALSELECTMSG_MUL top]
[f 2 1]Pasar un rato: [f 2 4 1][e]
[f 2 1]Comprobar vínculo social[e]
[f 2 1]Da igual[e]

[sel SEL_GENERALSELECTMSG_FCL top]
[f 2 1]Ir al club de moda.[e]
[f 2 1]Comprobar vínculo social[e]
[f 2 1]Da igual[e]

[sel SEL_GENERALSELECTMSG_BS top]
[f 2 1]Entrar en la librería[e]
[f 2 1]Comprobar vínculo social[e]
[f 2 1]Da igual[e]

[msg MSG_GENERAL_EXAMREWARD_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4029 0 0]Ah.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]He visto tus notas. Buen trabajo.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Toma, de parte del director.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4108 0 0]Es tu recompensa por ser capaz de compaginar los estudios y nuestras... en fin, "actividades extraescolares".[n][w][e]

[msg MND_GENERAL_EXAMREWARD_0]
[f 2 1]DEV: UNUSED LABEL[n][w][e]

[msg MND_GENERAL_EXAMREWARD_0_2]
[f 2 1]Como he sacado la nota más alta en los exámenes, he obtenido: [f 4 4 1 37 1 3].[n][w][e]

[msg MSG_GENERAL_EXAMREWARD_0_2 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4029 0 0]Ah.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]He visto tus notas. Buen trabajo.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Toma, de parte del director.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4108 0 0]Es tu recompensa por ser capaz de compaginar los estudios y nuestras... en fin, "actividades extraescolares".[n][w][e]

[msg MSG_GENERAL_EXAMREWARD_0_3 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4077 0 0]Ah, cierto. Hay algo más.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]He visto tus notas. Buen trabajo.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Toma, de parte del director.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4131 0 0]Es tu recompensa por ser capaz de compaginar los estudios y nuestras... en fin, "actividades extraescolares".[n][w][e]

[msg MND_GENERAL_EXAMREWARD_0_3]
[f 2 1]Como he sacado la nota más alta en los exámenes, he obtenido: [f 4 4 1 37 1 3].[n][w][e]

[msg MSG_GENERAL_EXAMREWARD_0_4 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4029 0 0]Ah.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]He visto tus notas. Buen trabajo.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Toma, de parte del director.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4108 0 0]Es tu recompensa por ser capaz de compaginar los estudios y nuestras... en fin, "actividades extraescolares".[n][w][e]

[msg MND_GENERAL_EXAMREWARD_0_4]
[f 2 1]DEV: UNUSED LABEL[n][w][e]

[msg MSG_GENERAL_EXAMREWARD_0_5 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4029 0 0]Ah.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]He visto tus notas... Buen trabajo.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Es laudable que continúes destacando en el instituto mientras libras arduos combates.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0]Acepta este regalo para agradecerte tus esfuerzos.[n][w][e]

[msg MND_GENERAL_EXAMREWARD_0_5]
[f 2 1]未使用ラベルです。[n][w][e]

[msg MSG_GENERAL_EXAMREWARD_0_6 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 6 65535 0 0][vp 3 0 65535 4029 0 0]Ah.[n][w][e]
[f 2 1][bup 5 0 6 65535 0 0]He visto tus notas. Buen trabajo.[n][w][e]
[f 2 1][bup 5 0 6 65535 0 0]Es laudable que continúes destacando en el instituto mientras libras arduos combates.[n][w][e]
[f 2 1][bup 5 0 6 65535 0 0]Acepta este regalo para agradecerte tus esfuerzos.[n][w][e]

[msg MND_GENERAL_EXAMREWARD_1]
[f 2 1]Como he sacado la nota más alta en los exámenes, he obtenido: [f 4 4 1 37 1 3].[n][w][e]

[msg MSG_GENERAL_EXAMREWARD_1 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4029 0 0]Ah.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]He visto tus notas. Buen trabajo.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Es laudable que continúes destacando en el instituto mientras libras arduos combates.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4108 0 0]Acepta este regalo para agradecerte tus esfuerzos.[n][w][e]

[msg MND_GENERAL_EXAMREWARD_1_2]
[f 2 1]DEV: UNUSED LABEL[n][w][e]

[msg MND_GENERAL_EXAMREWARD_1_3]
[f 2 1]Como he sacado la nota más alta en los exámenes, he obtenido: [f 4 4 1 37 1 3].[n][w][e]

