[msg MSG_000_0_0 [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 3 0 65535 6085 0 0]Ahora mismo estoy muy ocupada, [nf].[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0]"Deberías relajarte en vacaciones...".[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0]Eso me han dicho. Así que estoy esforzándome por probar todas las formas posibles de relajación.[n][w][e]

[msg MND_001_0_0 [DEV: Internal MES]]
[f 2 1]Aigis parece seria. Mejor dejarla tranquila.[n][w][e]

[msg MSG_002_0_0 [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 3 0 65535 6001 0 0][nf]... Relajarse no es tarea fácil.[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0]El mero hecho de permanecer en un lugar no parece contar como relajación.[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0]Hoy estoy observando qué hace la gente. Quizá así mañana logre relajarme de la manera correcta.[n][w][e]

[msg MND_003_0_0 [DEV: Internal MES]]
[f 2 1]Aigis parece ocupada.[n][w][e]
[f 2 1]Quizá podría proponerle ir al festival de cine mañana.[n][w][e]

[msg MSG_004_0_0 [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 3 0 65535 6080 0 0]Esta noche hay reunión.[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0]Me relajaré mientras tanto.[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0]¿Me recomiendas alguna forma de relajación, [nf]?[n][w][e]

[msg MND_005_0_0 [DEV: Internal MES]]
[f 2 1]Parece que Aigis no está ocupada.[n][w][e]

[msg MND_005_1_0 [DEV: Internal MES]]
[f 2 1]¿Invito a Aigis al festival de cine?[n][w][e]

[sel SEL_006_0_0 top]
[f 2 1]Invitar al cine[e]
[f 2 1]No invitar[e]

[msg MSG_007_0_0 [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 3 0 65535 6024 0 0]¿Al... cine?[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0]Ya veo... Así que salir también es una forma de relajarse.[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0]En ese caso, salgamos a relajarnos.[n][w][e]

[msg MSG_008_0_0 [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 3 0 65535 6016 0 0]Buenos días, doña [nf].[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0]Es broma.[n][w][e]

[msg MSG_009_0_0 [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 3 0 65535 6001 0 0]Ya mismo terminan las vacaciones.[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0]La residencia estará más tranquila cuando todos vuelvan al instituto.[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0][f 4 25 7]...[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0]Estoy pensando en cómo pasar tiempo contigo a partir de septiembre.[n][w][e]

[msg MND_010_0_0 [DEV: Internal MES]]
[f 2 1]Aigis parece seria. Mejor dejarla tranquila.[n][w][e]

[msg MND_Temperance [DEV: Internal MES]]
[f 2 1]El arcano de la Templanza podría ayudarme a mejorar todavía más.[n][w][e]

