[msg MSG_000_0_0 [Monje]]
[f 2 1][bup 114 0 65535 65535 0 0][vp 1 0 0 1 0 0]Eh, me acuerdo de ti.[n][w][e]
[f 2 1][bup 114 0 65535 65535 0 0][vp 1 0 0 2 0 0]Te dije que no volvieras. Malditos críos...[n][w][e]
[f 2 1][bup 114 0 65535 65535 0 0][vp 1 0 0 3 0 0]En fin, mientras no me saques de quicio, me da igual. Toma asiento.[n][w][e]

[msg MSG_000_5_0 [Monje]]
[f 2 1][bup 114 0 65535 65535 0 0][vp 1 0 0 4 0 0]¿Qué te trae hoy por aquí, jovencita?[n][w][e]

[sel SEL_001_0_0 top]
[f 2 1]He venido a verte, abuelo.[e]
[f 2 1]No es asunto tuyo.[e]

[msg MSG_002_0_0 [Monje]]
[f 2 1][bup 114 2 65535 65535 0 0][vp 1 0 0 5 0 0]Deja de bromear, anda. Je, esa es buena.[n][w][e]

[msg MSG_003_0_0 [Monje]]
[f 2 1][bup 114 1 65535 65535 0 0][vp 1 0 0 6 0 0][f 5 13 17 15 114]Ja, ¡tienes toda la razón! No es asunto mío.[n][w][e]

[msg MSG_004_0_0 [Monje]]
[f 2 1][bup 114 2 65535 65535 0 0][vp 1 0 0 7 0 0]Cuidado con lo que dices, niña. No deberías decirle algo así a un adulto.[n][w][e]
[f 2 1][bup 114 2 65535 65535 0 0][vp 1 0 0 8 0 0]Si fueras mi hija, te daría tu merecido.[n][w][e]
[f 2 1][bup 114 0 65535 65535 0 0][vp 1 0 0 9 0 0][f 4 23 0 114 0 25 25]No hace falta que me veneres, pero al menos muéstrame respeto.[n][w][e]

[sel SEL_005_0_0 top]
[f 2 1]¿Cómo te llamas?[e]
[f 2 1]¿Que te muestre respeto?[e]

[msg MSG_006_0_0 [Monje]]
[f 2 1][bup 114 0 65535 65535 0 0][vp 1 0 0 10 0 0][f 5 13 17 5 114]Mutatsu. Es mi nombre budista, no el real, claro.[n][w][e]

[msg MSG_007_0_0 [Monje]]
[f 2 1][bup 114 2 65535 65535 0 0][vp 1 0 0 11 0 0]Vaya, no eres muy sagaz que digamos, ¿eh? Es una de esas cosas que se aprenden sin ayuda.[n][w][e]

[msg MSG_008_0_0 [Monje]]
[f 2 1][bup 114 0 65535 65535 0 0][vp 1 0 0 12 0 0]Si vas a dirigirte a mí, hazlo por mi nombre budista, Mutatsu.[n][w][e]

[msg MSG_009_0_0 [Mutatsu]]
[f 2 1][bup 114 0 65535 65535 0 0][vp 1 0 0 13 0 0]Y no te olvides de hablarme con respeto.[n][w][e]
[f 2 1][bup 114 0 65535 65535 0 0][vp 1 0 0 14 0 0]Este mundo no tiene piedad, joven. Hay que mostrar respeto hacia los demás.[n][w][e]

[msg MND_010_0_0]
[f 2 1]Mutatsu me ha soltado un sermón.[n][w][e]
[f 2 1]Percibo amabilidad en sus duras palabras.[n][w][e]
[f 2 1]Creo que ahora entiendo a Mutatsu un poco mejor...[n][w][e]

[msg SYS_011_0_0]
[f 2 1]DEV: Unused label.[n][w][e]

[msg MSG_012_0_0 [Mutatsu]]
[f 2 1][bup 114 0 65535 65535 0 0][vp 1 0 0 15 0 0]La verdad es que me da igual lo que les ocurra a los hijos de otros, pero...[n][w][e]
[f 2 1][bup 114 0 65535 65535 0 0][vp 1 0 0 16 0 0]Vete a casa, ¿quieres? Y no vuelvas más.[n][w][e]

[msg MND_013_0_0]
[f 2 1]Me he despedido de Mutatsu y he vuelto a la residencia.[n][w][e]

