[msg MND_000_0_0 [DEV: Internal MES]]
[f 2 1]Hoy me dijeron que fuera a la cuarta planta.[n][w][e]

[msg MND_001_0_0 [DEV: Internal MES]]
[f 2 1]Debo ir a la torre Tártaro.[n][w][e]

[msg MND_002_0_0 [DEV: Internal MES]]
[f 2 1]¿Debería volver ya a mi habitación?[n][w][e]

[sel SEL_003_0_0 top]
[f 2 1]Volver[e]
[f 2 1]Aún no[e]

[msg MND_004_0_0 [DEV: Internal MES]]
[f 2 1]Estoy cansada. Me convendría reponer fuerzas.[n][w][e]

[msg MND_005_0_0 [DEV: Internal MES]]
[f 2 1]Estoy agotada... Hoy debería acostarme pronto.[n][w][e]

