[msg MSG_000_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 1 65535 65535 0 0][vp 1 0 0 1 0 0]Ahí viene la campeona.[n][w][e]

[msg MSG_001_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 1 0 0 2 0 0]¡La cosa se pone interesante! ¡A por ella, Ken![n][w][e]

[msg MSG_002_0_0 [Koromaru]]
[f 2 1][bup 9 0 65535 65535 0 0][vp 1 0 0 3 0 0]¡Guau, guau![n][w][e]

[sel SEL_003_0_0 top]
[f 2 1]¿Qué hacéis aquí?[e]
[f 2 1]Se lo prometí a Ken.[e]

[msg MSG_004_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 4 0 0]Nos han comentando que ibais a batiros en duelo y hemos venido a verlo.[n][w][e]

[msg MSG_005_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 1 0 0 5 0 0]Estas cosas molan más con público, ¿no crees?[n][w][e]

[msg MSG_006_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 9 65535 65535 0 0][vp 1 0 0 6 0 0]Sí, y tenemos entendido que la promesa era un duelo. Hemos venido a verlo.[n][w][e]

[msg MSG_007_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 1 0 0 7 0 0]Eso es, venimos a ver triunfar al chavalín.[n][w][e]

[msg MSG_008_0_0 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 1 0 0 8 0 0]Cuando les conté que quería vencerte, se ofrecieron a ayudarme.[n][w][e]

[msg MSG_009_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 9 0 0]Le he preparado una rutina de entrenamiento y le he dado consejos sobre cómo moverse.[n][w][e]

[msg MSG_010_0_0 [Ken Amada]]
[f 2 1][bup 8 1 65535 65535 0 0][vp 1 0 0 10 0 0]Como quería fortalecer las piernas y el tronco, he salido a correr con Koromaru.[n][w][e]

[msg MSG_011_0_0 [Koromaru]]
[f 2 1][bup 9 1 65535 65535 0 0][vp 1 0 0 11 0 0]¡Guau![n][w][e]

[msg MSG_012_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 1 0 0 12 0 0]Y yo he asumido tu papel en los combates de entrenamiento.[n][w][e]

[msg MSG_013_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 13 0 0]Pensábamos que, si no conseguía darle un golpe a Junpei, ni por asomo te vencería a ti.[n][w][e]

[msg MSG_014_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 65535 65535 0 0][vp 1 0 0 14 0 0]Oye, un poquito de respeto por el tío que está lleno de moratones.[n][w][e]
[f 2 1][bup 3 3 65535 65535 0 0][vp 1 0 0 15 0 0][f 4 23 0 2 3 25 25]No se ha cortado ni un pelo...[n][w][e]

[msg MSG_015_0_0 [Ken Amada]]
[f 2 1][bup 8 2 65535 65535 0 0][vp 1 0 0 16 0 0]Bueno, al lío.[n][w][e]

[msg MSG_016_0_0 [Ken Amada]]
[f 2 1][bup 8 2 65535 65535 0 0][vp 1 0 0 17 0 0]¡Iaaaaah![n][w][e]

[msg MSG_017_0_0 [Junpei Iori (SE)]]
[f 2 1][vp 1 0 0 18 0 0]¡Aaaaaaaah![n][w][e]

[msg MSG_018_0_0 [Akihiko Sanada (SE)]]
[f 2 1][vp 1 0 0 19 0 0]Mmm...[n][w][e]

[msg MSG_019_0_0 [Koromaru (SE)]]
[f 2 1][vp 1 0 0 20 0 0]Aahh.[n][w][e]

[msg MSG_020_0_0 [Ken Amada]]
[f 2 1][bup 8 2 65535 65535 0 0][vp 1 0 0 21 0 0]Haaa, haaa...[n][w][e]

[msg MSG_021_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 1 0 0 22 0 0]¡Vas bien, Amada! ¡Sigue así![n][w][e]

[msg MSG_022_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 2 65535 65535 0 0][vp 1 0 0 23 0 0]¡Tú puedes, acércate un poquito más![n][w][e]

[msg MSG_023_0_0 [Koromaru]]
[f 2 1][bup 9 0 65535 65535 0 0][vp 1 0 0 24 0 0]¡Guau, guau![n][w][e]

[msg MSG_024_0_0 [Ken Amada]]
[f 2 1][bup 8 2 65535 65535 0 0][vp 1 0 0 25 0 0]¡Ah![n][w][e]

[msg MSG_025_0_0 [Junpei Iori (SE)]]
[f 2 1][vp 1 0 0 26 0 0]¡Ostras![n][w][e]

[msg MSG_026_0_0 [Akihiko Sanada (SE)]]
[f 2 1][vp 1 0 0 27 0 0]¡...![n][w][e]

[msg MSG_027_0_0 [Koromaru (SE)]]
[f 2 1][vp 1 0 0 28 0 0]¡Guau![n][w][e]

[msg MSG_028_0_0 [Ken Amada]]
[f 2 1][bup 8 5 65535 65535 0 0][vp 1 0 0 29 0 0]Uf...[n][w][e]

[msg MSG_029_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 65535 65535 0 0][vp 1 0 0 30 0 0]Mierda, ¿le ha dado?[n][w][e]

[msg MSG_030_0_0 [Koromaru]]
[f 2 1][bup 9 0 65535 65535 0 0][vp 1 0 0 31 0 0]¡Guau, guau![n][w][e]

[msg MSG_031_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 2 65535 65535 0 0][vp 1 0 0 32 0 0]¡Se acerca el siguiente, levántate![n][w][e]

[sel SEL_032_0_0 top]
[f 2 1]Estás acabado.[e]
[f 2 1]No hay rencor que valga.[e]

[msg MSG_033_0_0 [Voz de Yukari]]
[f 2 1][vp 1 0 0 33 0 0]¿Estáis ahí arriba?[n][w][e]

[msg MSG_033_5_0 [Voz de Yukari]]
[f 2 1][cut 8 2 0][f 1 5 0][e]

[msg MSG_034_0_0 [Ken Amada]]
[f 2 1][bup 8 2 65535 65535 0 0][vp 1 0 0 34 0 0]¡Ja![n][w][e]

[msg MSG_035_0_0 [Junpei Iori (SE)]]
[f 2 1][vp 1 0 0 35 0 0]¡Aaaaah![n][w][e]

[msg MSG_036_0_0 [Akihiko Sanada (SE)]]
[f 2 1][vp 1 0 0 36 0 0]Uy.[n][w][e]

[msg MSG_037_0_0 [Koromaru (SE)]]
[f 2 1][vp 1 0 0 37 0 0]¡Guau![n][w][e]

[msg MSG_038_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 1 0 0 38 0 0]¡Sí, señor! Un golpe limpio. El ganador es Ken, en la esquina azul.[n][w][e]

[msg MSG_039_0_0 [Koromaru]]
[f 2 1][bup 9 1 65535 65535 0 0][vp 1 0 0 39 0 0]¡Guau, guau![n][w][e]

[msg MSG_040_0_0 [Ken Amada]]
[f 2 1][bup 8 1 65535 65535 0 0][vp 1 0 0 40 0 0]Ha sido suerte, casi que he hecho trampas...[n][w][e]

[msg MSG_041_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 1 65535 65535 0 0][vp 1 0 0 41 0 0]No, has visto la oportunidad y la has aprovechado. Siéntete orgulloso.[n][w][e]

[msg MSG_042_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 42 0 0]Fuuka y yo hemos comprado boniatos asados. Os estaba buscando para comérnoslos juntos, pero...[n][w][e]
[f 2 1][bup 2 6 65535 65535 0 0][vp 1 0 0 43 0 0][f 4 23 0 1 6 25 25][f 4 21 2 10]¿Qué estáis haciendo aquí arriba?[n][w][e]

[msg MSG_043_0_0 [Junpei Iori]]
[f 2 1][bup 3 9 65535 65535 0 0][vp 1 0 0 44 0 0]Presenciando un duelo a muerte sin cuhillos. ¿A que sí, Ken?[n][w][e]

[msg MSG_044_0_0 [Ken Amada]]
[f 2 1][bup 8 1 65535 65535 0 0][vp 1 0 0 45 0 0]Dicho así, suena un poco raro, pero sí.[n][w][e]

[msg MSG_045_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 1 65535 65535 0 0][vp 1 0 0 46 0 0]Ha sido un buen duelo por ambas partes.[n][w][e]

[msg MSG_046_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 47 0 0]Mm...[n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 48 0 0][f 4 23 0 1 1 25 25]No lo pillo, pero parece que os estáis divirtiendo. Hace frío, no tardéis en entrar.[n][w][e]

[msg MSG_047_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 1 0 0 49 0 0]Oye, ¿has dicho que habías hecho boniatos? ¡Yo me apunto![n][w][e]

[msg MSG_048_0_0 [Yukari Takeba (SE)]]
[f 2 1][vp 1 0 0 50 0 0]¡Los he comprado para Amada! Tú cómete la piel y las partes quemadas, Junpei.[n][w][e]

[msg MSG_049_0_0 [Junpei Iori (SE)]]
[f 2 1][vp 1 0 0 51 0 0]¿Qué te crees que soy, un perro?[n][w][e]

[msg MSG_050_0_0 [Koromaru (SE)]]
[f 2 1][vp 1 0 0 52 0 0]¡Guau![n][w][e]

[msg MSG_051_0_0 [Ken Amada]]
[f 2 1][bup 8 1 65535 65535 0 0][vp 1 0 0 53 0 0]Gracias por el duelo, [nl]. He aprendido un montón.[n][w][e]

[sel SEL_052_0_0 top]
[f 2 1]Has estado genial.[e]
[f 2 1]He bajado la guardia.[e]
[f 2 1]Disputemos otro asalto.[e]

[msg MSG_053_0_0 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 1 0 0 54 0 0]No, ha sido suerte. He estado atascado en la defensa desde el principio.[n][w][e]
[f 2 1][bup 8 1 65535 65535 0 0][vp 1 0 0 55 0 0][f 4 23 0 3 1 25 25]Aunque creo que lo he hecho mejor que la última vez. Ahora me queda aplicarlo en un combate real.[n][w][e]

[msg MSG_054_0_0 [Ken Amada]]
[f 2 1][bup 8 1 65535 65535 0 0][vp 1 0 0 56 0 0]Ha sido suerte. He estado atascado en la defensa todo el tiempo.[n][w][e]
[f 2 1][bup 8 1 65535 65535 0 0][vp 1 0 0 57 0 0]Me queda un largo camino por delante. Tú eres increíble.[n][w][e]

[msg MSG_055_0_0 [Ken Amada]]
[f 2 1][bup 8 1 65535 65535 0 0][vp 1 0 0 58 0 0]Si disputamos otro asalto, seguro que pierdo.[n][w][e]
[f 2 1][bup 8 0 65535 65535 0 0][vp 1 0 0 59 0 0][f 4 23 0 3 0 25 25]Ha sido solo suerte. Tú eres increíble.[n][w][e]

[msg MSG_056_0_0 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 1 0 0 60 0 0]Técnicamente estamos empatados, así que a la próxima veremos quién es más fuerte. Aunque igual me estoy confiando mucho.[n][w][e]
[f 2 1][bup 8 1 65535 65535 0 0][vp 1 0 0 61 0 0][f 4 23 0 3 1 25 25]Espero retarte de nuevo más adelante. ¿Me prometes que volveremos a luchar?[n][w][e]

[msg MSG_057_0_0 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 1 0 0 62 0 0]Vale. Hasta entonces, quédate con esto.[n][w][e]

[msg MSG_058_0_0 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 1 0 0 63 0 0]Es la llave de la casa en la que vivía con mi madre.[n][w][e]

[msg MSG_059_0_0 [Ken Amada]]
[f 2 1][bup 8 3 65535 65535 0 0][vp 1 0 0 64 0 0]Cada vez que la miro, recuerdo el tiempo que pasé con ella.[n][w][e]
[f 2 1][bup 8 3 65535 65535 0 0][vp 1 0 0 65 0 0]Los recuerdos que compartimos juntos inundan la casa.[n][w][e]

[msg MSG_060_0_0 [Ken Amada]]
[f 2 1][bup 8 3 65535 65535 0 0][vp 1 0 0 66 0 0]Sé que la batalla final no será fácil.[n][w][e]
[f 2 1][bup 8 2 65535 65535 0 0][vp 1 0 0 67 0 0][f 4 23 0 3 2 25 25]Pero, pase lo que pase, quiero volver.[n][w][e]
[f 2 1][bup 8 0 65535 65535 0 0][vp 1 0 0 68 0 0][f 4 23 0 3 0 25 25]Creo que esta llave nos unirá.[n][w][e]

[msg MSG_061_0_0 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 1 0 0 69 0 0]Algún día espero convertirme en una persona a la que siempre se pueda acudir.[n][w][e]
[f 2 1][bup 8 0 65535 65535 0 0][vp 1 0 0 70 0 0]Igual que mi madre, todos los de la residencia y tú, que habéis estado ahí para mí.[n][w][e]

[msg MSG_062_0_0 [Ken Amada]]
[f 2 1][bup 8 1 65535 65535 0 0][vp 1 0 0 71 0 0]Ay, perdona por ponerme tan pesado contigo. ¿Bajamos a comer los boniatos?[n][w][e]

[msg MSG_063_0_0 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 1 0 0 72 0 0]Entonces, ¿nuestro próximo combate será el año que viene o más tarde?[n][w][e]
[f 2 1][bup 8 1 65535 65535 0 0][vp 1 0 0 73 0 0][f 4 23 0 3 1 25 25]¡Ya sé! ¿Y si esperamos a que te alcance en altura?[n][w][e]
[f 2 1][bup 8 0 65535 65535 0 0][vp 1 0 0 74 0 0][f 4 23 0 3 0 25 25]Si más o menos tenemos el mismo cuerpo, tendré posibilidades. Aunque seguramente seas más fuerte...[n][w][e]

[msg MSG_064_0_0 [Ken Amada]]
[f 2 1][bup 8 1 65535 65535 0 0][vp 1 0 0 75 0 0]Me pregunto cómo seréis todos en el futuro.[n][w][e]
[f 2 1][bup 8 1 65535 65535 0 0][vp 1 0 0 76 0 0]¡Me emociono de solo pensarlo![n][w][e]

[msg MND_065_0_0]
[f 2 1]Amada estaba exultante de alegría cuando nos hemos unido a los demás.[n][w][e]

[msg SYS_066_0_0]
[f 2 1]¡Has forjado un poderoso vínculo con Amada![n]¡Ahora puedes fusionar a [clr 35]Miguel[clr 27], el protector absoluto![n][w][e]

