[msg MSG_000_0_0 [Profesora Toriumi]]
[f 2 1][bup 1581 0 65535 65535 0 0][vp 1 0 0 1 0 0][f 5 21 0 1581]Hoy ha venido a clase una nueva alumna.[n][w][e]

[msg MSG_000_5_0 [Profesora Toriumi]]
[f 2 1][bup 1581 0 65535 65535 0 0][vp 1 0 0 2 0 0][f 5 21 0 1581]Adelante, preséntate.[n][w][e]

[msg MSG_001_0_0 [Aigis]]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 3 0 0]Me llamo Aigis. Es un placer conoceros.[n][w][e]

[msg MSG_002_0_0 [Profesora Toriumi]]
[f 2 1][bup 1581 0 65535 65535 0 0][vp 1 0 0 4 0 0][f 5 21 0 1581]¿Aigis? Nunca había oído ese nombre. A lo mejor es extranjera.[n][w][e]

[msg MSG_003_0_0 [Profesora Toriumi]]
[f 2 1][bup 1581 0 65535 65535 0 0][vp 1 0 0 5 0 0][f 5 21 0 1581]A ver, ¿algo más que deba saber? Mmm... ¿Arma... táctica humanoide?[n][w][e]

[msg MSG_004_0_0 [Yukari Takeba]]
[f 2 1][bup 2 4 1 65535 0 0][vp 1 0 0 6 0 0]¡¿Qué?![n][w][e]

[msg MSG_005_0_0 [Profesora Toriumi]]
[f 2 1][bup 1581 0 65535 65535 0 0][vp 1 0 0 7 0 0][f 5 21 0 1581]Está claro que es un error.[n][w][e]
[f 2 1][bup 1581 1 65535 65535 0 0][vp 1 0 0 8 0 0][f 5 21 0 1581]Esto no hace sino demostrar que uno no debe creerse todo lo que lee.[n][w][e]

[msg MSG_006_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 1 65535 0 0][vp 1 0 0 9 0 0]S-sí, ¡tal cual![n][w][e]

[msg MSG_007_0_0 [Profesora Toriumi]]
[f 2 1][bup 1581 0 65535 65535 0 0][vp 1 0 0 10 0 0][f 5 21 0 1581]A ver, te puedes sentar... Mmm. ¿Hay algún sitio libre?[n][w][e]

[msg MSG_008_0_0 [Profesora Toriumi]]
[f 2 1][bup 1581 0 65535 65535 0 0][vp 1 0 0 11 0 0][f 5 21 0 1581]Mira, allí. Justo a su lado.[n][w][e]

[msg MSG_009_0_0 [Profesora Toriumi]]
[f 2 1][bup 1581 0 65535 65535 0 0][vp 1 0 0 12 0 0][f 5 21 0 1581]Hala, listo.[n][w][e]

[msg MSG_010_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 1 65535 0 0][vp 1 0 0 13 0 0]Profesora Toriumi, ese sitio está ocupado. Hoy ha hecho pellas.[n][w][e]

[msg MSG_011_0_0 [Profesora Toriumi]]
[f 2 1][bup 1581 0 65535 65535 0 0][vp 1 0 0 14 0 0][f 5 21 0 1581]Pues si no está, se siente. Ahora es tu sitio.[n][w][e]
[f 2 1][bup 1581 0 65535 65535 0 0][vp 1 0 0 15 0 0][f 5 21 0 1581]Venga, siéntate.[n][w][e]

[msg MSG_012_0_0 [Aigis]]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 16 0 0]Es perfecto.[n][w][e]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 17 0 0]Mi mayor prioridad es estar con ella en todo momento.[n][w][e]

[msg MSG_013_0_0 [Yukari Takeba]]
[f 2 1][bup 2 2 1 65535 0 0][vp 1 0 0 18 0 0]¡Aigis![n][w][e]

[msg MSG_014_0_0 [Aigis]]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 19 0 0]¿Qué ocurre?[n][w][e]

[msg MSG_015_0_0 [Voz de un alumno]]
[f 2 1][vp 1 0 0 20 0 0]Yukari, ¿para qué te levantas?[n][w][e]

[msg MSG_016_0_0 [Yukari Takeba]]
[f 2 1][bup 2 4 1 65535 0 0][vp 1 0 0 21 0 0]¿Cómo?[n][w][e]

[msg MSG_016_5_0 [Yukari Takeba]]
[f 2 1][bup 2 2 1 65535 0 0][vp 1 0 0 22 0 0]¡Aj![n][w][e]

[msg MSG_017_0_0 [Profesora Toriumi]]
[f 2 1][bup 1581 1 65535 65535 0 0][vp 1 0 0 23 0 0][f 5 21 0 1581]Qué gusto da ver que os lleváis todos bien.[n][w][e]
[f 2 1][bup 1581 2 65535 65535 0 0][vp 1 0 0 24 0 0][f 5 21 0 1581]Hacedme el favor y estaos quietecitos hasta que acabe la clase.[n][w][e]

[msg MSG_018_0_0 [Yukari Takeba]]
[f 2 1][bup 2 6 1 65535 0 0][vp 1 0 0 25 0 0]Dios...[n][w][e]

