[msg MSG_MITSURU_0407_1 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4017 0 0]Anda, hola.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]¿Qué tal tu primer día de instituto?[n][w][e]

[sel SEL_0407_0_0 top]
[f 2 1]No está nada mal.[e]
[f 2 1]Agotador.[e]

[msg MSG_MITSURU_0407_RE_2 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4024 0 0]Ya veo. Bueno, si necesitas ayuda, no dudes en preguntar a tus compañeros.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Ay, disculpa. No te quería entretener. Has tenido un día larguísimo, así que vete a descansar.[n][w][e]

[msg MSG_MITSURU_0407_RE_3 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4061 0 0]Al principio es un poco apabullante, pero ya te acostumbrarás a todo con el paso del tiempo.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Por ahora, deberías volver a tu habitación a descansar.[n][w][e]

[msg MSG_MITSURU_TARTAROS_040 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4017 0 0]Llegas bastante tarde. No es mi intención ser prepotente, pero, por favor, que no se repita más.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]En cualquier caso, pareces bastante cansada. ¿Y si hoy te acuestas temprano?[n][w][e]

[msg MSG_YUKARI_HELP_0417 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 3 0 65535 1019 0 0]Ah, ¡hola de nuevo! Me alegro un montón de que hayas salido del hospital.[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0]No te excedas, ¿vale? ¿Quieres descansar un poco? No te preocupes, tu habitación ya es segura.[n][w][e]

[msg MSG_MITSURU_HELP_0422 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0]Por cierto, respecto a la Hora Oscura...[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Puede que no haga falta decirlo, pero es imposible que las tiendas abran a esa hora.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Así que prepárate de antemano. No querrás que te pille desprevenida cuando sea demasiado tarde.[n][w][e]

[msg MSG_JUNPEI_0423_1 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0]Entonces, ¿ahora eres amiga de Tomochika?[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]Dice que eres "alguien a quien hay que tener en cuenta". Ah, pero en el buen sentido.[n][w][e]

[sel SEL_0423_0_0 top]
[f 2 1]¡Ya te digo![e]
[f 2 1]¿También eres amigo suyo?[e]

[msg MSG_JUNPEI_0423_RE1 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2133 0 0]¡Ja, ja! No me extraña que os llevéis bien.[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]Es un poco mujeriego, pero es un buen tipo.[n][w][e]

[msg MSG_JUNPEI_0423_RE2 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2032 0 0]A ver, no somos superamigos ni nada, pero nos conocemos desde hace tiempo.[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]Es un poco mujeriego, pero es un buen tipo.[n][w][e]

[msg MSG_JUNPEI_0423_2 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2067 0 0]Ay, casi se me olvida. Iba a preguntarte si quieres ir esta noche a la Tártaro.[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]Parece que hay más de esos "desaparecidos", así que hay que eliminar más sombras, ¿no?[n][w][e]

[msg MSG_YUKARI_0424_1_JOIN [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0]Por cierto, hoy te vi en la pista.[n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0]Miyamoto, el de nuestra clase, también está en el equipo de atletismo, ¿verdad? Quizá os hacéis amigos.[n][w][e]

[msg MSG_YUKARI_0424_1_NON_JO [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0]Por cierto, si algún club te llama la atención, únete antes de que deje de aceptar miembros.[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0]Sé que unirse a algo nuevo puede ser difícil, pero será divertido, ¡y puede que hagas nuevos amigos![n][w][e]

[msg MSG_YUKARI_TARTAROS_0424 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0]Oye, hablando de extraescolares... ¿Te parece bien ir a la torre Tártaro esta noche?[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0]Hoy no he entrenado, así que no está de más que haga algo de ejercicio.[n][w][e]

[msg MSG_MITSURU_TARTAROS_042 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0]Me alegro de que tomes la iniciativa, pero no te lo tomes a la ligera. Recuerda que es peligroso.[n][w][e]

[msg MSG_YUKARI_TARTAROS_0424_2 [Yukari Takeba]]
[f 2 1][bup 2 3 65535 65535 0 0]Sí, lo sé.[n][w][e]

[msg MSG_YUKARI_0424_2 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0]Oye, hablando de extraescolares... ¿Te apetece ir a la torre Tártaro esta noche?[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0]Hoy no he entrenado, así que no está de más que haga algo de ejercicio.[n][w][e]

[msg MSG_MITSURU_0424 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0]Me alegro de que tomes la iniciativa, pero no te lo tomes tan a la ligera y bajes la guardia.[n][w][e]

[msg MSG_YUKARI_0424_3 [Yukari Takeba]]
[f 2 1][bup 2 3 65535 65535 0 0]Sí, lo sé...[n][w][e]

[msg MSG_YUKARI_OK_0424_2 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0]De hecho, he estado pensando en participar en más cosas además del tiro con arco.[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0]Bueno, supongo que ya lo hago, ¿no? Aunque no es lo que tenía en mente...[n][w][e]

[msg MSG_SANADA_TARTAROS_0425 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0]¿Entrenáis lo suficiente? No quiero que el equipo se vaya al garete mientras me recupero.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0]Solo vosotros podéis combatir ahora mismo.[n][w][e]

[msg MSG_SANADA_0425 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0]Parece que habéis hecho un buen trabajo explorando la Tártaro, pero...[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0]Aun así, te recomiendo que intentes hacerte más fuerte mientras puedas.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0]Nunca se sabe cuándo aparecerá otro enemigo importante, como el de antes.[n][w][e]

[msg MSG_SANADA_OK_0425 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0]Parece que habéis hecho un buen trabajo explorando la Tártaro.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0]Recordad que sois los únicos que podréis enfrentaros a lo que sea que pueda pasar.[n][w][e]
[f 2 1][bup 4 1 65535 65535 0 0]Hasta que me recupere, confío en vosotros.[n][w][e]

[msg MSG_JUNPEI_TARTAROS_0427 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0]Ah, sí; he oído que lo mismo entras en el consejo estudiantil.[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Kirijo, ¿estás segura de que quieres dejar que una holgazana como ella se una?[n][w][e]

[msg MSG_MITSURU_TARTAROS_042_2 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0]No la estoy obligando. De todas formas, si te preocupa su ética de trabajo, ¿preferirías unirte tú en su lugar?[n][w][e]

[msg MSG_JUNPEI_TARTAROS_0427_2 [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0][vp 3 0 65535 2035 0 0]Ah, eh... Yo paso. Pero gracias por la oferta.[n][w][e]

[msg MSG_JUNPEI_0429 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0]¡Por cierto! Puedes usar ese ordenador de ahí cuando quieras.[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]También puedes instalarle los programas que quieras.[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Pero ahórrate los juegos en línea. Sería una putada que alguien usara tu cuenta sin querer.[n][w][e]

[msg MSG_MITSURU_TARTAROS_GO [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4001 0 0][nl], tengo que hablar contigo.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Han pasado diez días desde la primera vez que entraste en la torre Tártaro, pero no has vuelto ni una sola vez.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]¿Se puede saber en qué estás pensando?[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Te dije que sería peligroso si no te entrenas adecuadamente.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Tal vez fue un error nombrarte como líder... Espero que no sigas decepcionándome.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Hoy iremos a la torre Tártaro, te guste o no. ¿Te queda claro?[n][w][e]

[sel SEL_020_0_0 top]
[f 2 1]Entendido.[e]
[f 2 1]Dame un momento.[e]

[msg MSG_MITSURU_TARTAROS_GO_ [Mitsuru Kirijo]]
[f 2 1][bup 5 2 65535 65535 0 0][vp 3 0 65535 4088 0 0]No quiero oír ninguna excusa. Has tenido tiempo suficiente de prepararte.[n][w][e]
[f 2 1][bup 5 2 65535 65535 0 0]Antes dejé que te organizaras por tu cuenta, pero ha sido un error.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Vamos a hacer lo que más le conviene a todo el mundo, no solo a ti. Prepárate.[n][w][e]

[msg MND_INVITE_4F]
[f 2 1]No hay nadie en el vestíbulo...[n][w][e]
[f 2 1]Todo el mundo estará ya esperando en la cuarta planta.[n][w][e]

[msg MSG_WELCOME_YUKARI_OUT [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 3 0 65535 1019 0 0]Ah, eh... Hola.[n][w][e]

[msg MSG_WELCOME_YUKARI_OUT2 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 3 0 65535 1012 0 0]Eh... Hola...[n][w][e]

[msg MSG_WELCOME_JUNPEI_OUT [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2018 0 0]¿Qué pasa, tía?[n][w][e]

[msg MSG_WELCOME_JUNPEI_OUT2 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2012 0 0]Hola, tía...[n][w][e]

[msg MSG_WELCOME_MITSURU_OUT [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4018 0 0]Hola de nuevo.[n][w][e]

[msg MSG_WELCOME_MITSURU_OUT2 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4027 0 0]Hola de nuevo...[n][w][e]

[msg MSG_WELCOME_SANADA_OUT [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 3 0 65535 3017 0 0]Anda, has vuelto.[n][w][e]

[msg MSG_WELCOME_FUKA_OUT [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5018 0 0]Hola, ¿qué tal el día?[n][w][e]

[msg MSG_WELCOME_FUKA_OUT2 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5028 0 0]Ah... Hola...[n][w][e]

[msg MSG_WELCOME_AEGIS_OUT_RO [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 3 0 65535 6018 0 0]Saludos.[n][w][e]

[msg MSG_WELCOME_AEGIS_OUT [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6018 0 0]Saludos.[n][w][e]

[msg MSG_WELCOME_AEGIS_OUT_NA [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6017 0 0]Hola otra vez. Me alegro de volver a verte.[n][w][e]

[msg MSG_WELCOME_KOROMARU_OUT [Koromaru]]
[f 2 1][bup 9 0 65535 65535 0 0][vp 3 0 65535 8008 0 0]¡Guau![n][w][e]

[msg MSG_WELCOME_AMADA_OUT [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 3 0 65535 7020 0 0]¡Anda, hola![n][w][e]

[msg MSG_WELCOME_AMADA_OUT2 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 3 0 65535 7012 0 0]Ah... Hola...[n][w][e]

[msg MSG_WELCOME_ARAGAKI_OUT [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 3 0 65535 9014 0 0]Ey...[n][w][e]

[msg MSG_WELCOME_IKUTSUKI_OUT [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 3 0 65535 14201 0 0]Hola de nuevo.[n][w][e]

[msg MSG_WELCOME_YUKARI_IN [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 3 0 65535 1067 0 0]¡Ah, estás aquí![n][w][e]

[msg MSG_WELCOME_YUKARI_IN2 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 3 0 65535 1012 0 0]Ah, ¿ya has llegado? Perdona, no te había visto.[n][w][e]

[msg MSG_WELCOME_JUNPEI_IN [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2009 0 0]Eh, ¿qué pasa?[n][w][e]

[msg MSG_WELCOME_JUNPEI_IN2 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2012 0 0]Ah, hola...[n][w][e]

[msg MSG_WELCOME_MITSURU_IN [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4029 0 0]¿Eh? Ah, eres tú...[n][w][e]

[msg MSG_WELCOME_MITSURU_IN2 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4027 0 0]¿Mmm? Ah, ya estás aquí.[n][w][e]

[msg MSG_WELCOME_SANADA_IN [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 3 0 65535 3024 0 0]¿Has estado en tu habitación todo este tiempo?[n][w][e]

[msg MSG_WELCOME_FUKA_IN [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5067 0 0]¡Ah, hola! No sabía que ya estabas aquí.[n][w][e]

[msg MSG_WELCOME_FUKA_IN2 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5093 0 0]Anda, ¿estás aquí? Hola...[n][w][e]

[msg MSG_WELCOME_FUKA_IN_0712 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5067 0 0]Ah, [nl]...[n][w][e]

[msg MSG_WELCOME_AEGIS_IN_ROB [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 3 0 65535 6008 0 0]Buenas tardes.[n][w][e]

[msg MSG_WELCOME_AEGIS_IN [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6008 0 0]Buenas tardes.[n][w][e]

[msg MSG_WELCOME_AEGIS_IN_NAK [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6009 0 0]¿Qué tal el día? ¿Todo bien?[n][w][e]

[msg MSG_WELCOME_KOROMARU_IN [Koromaru]]
[f 2 1][bup 9 0 65535 65535 0 0][vp 3 0 65535 8001 0 0]¡Guau, guau![n][w][e]

[msg MSG_WELCOME_AMADA_IN [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 3 0 65535 7010 0 0]¿Has estudiado algo?[n][w][e]

[msg MSG_WELCOME_AMADA_IN2 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 3 0 65535 7012 0 0]¿Estabas aquí? Pues... hola.[n][w][e]

[msg MSG_WELCOME_ARAGAKI_IN [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 3 0 65535 9056 0 0]... ¿Qué hay?[n][w][e]

[msg MSG_WELCOME_IKUTSUKI_IN [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 3 0 65535 14204 0 0]Ah, no sabía que ya estabas aquí. He venido a hacer una visita rápida.[n][w][e]

[msg MND_SHYUKAKU_OK]
[f 2 1]Ahora que lo pienso, las hortalizas que planté en la azotea ya se podrán recolectar.[n][w][e]
[f 2 1]Debería ir a echarles un ojo...[n][w][e]

[msg MND_SHYUKAKU_TAIYAKI_OK]
[f 2 1]Ahora que lo pienso, las hortalizas que planté en la azotea ya se podrán recolectar.[n][w][e]
[f 2 1]Y el taiyaki que metí en la nevera también debería estar frío.[n][w][e]
[f 2 1]Debería ir a echarles un ojo...[n][w][e]

[msg MND_SHYUKAKU_TAIYAKI_OK_]
[f 2 1]Ahora que lo pienso, las hortalizas que planté en la azotea ya se podrán recolectar.[n][w][e]
[f 2 1]Y el taiyaki que metí en la nevera también debería estar frío.[n][w][e]
[f 2 1]Debería sacarlo de la nevera y dárselo a Elizabeth.[n][w][e]

[msg MND_TAIYAKI_OK]
[f 2 1]Ahora que lo pienso, el taiyaki que metí en la nevera ya debería estar frío.[n][w][e]
[f 2 1]Debería ir a por él.[n][w][e]

[msg MND_TAIYAKI_OK_QUEST]
[f 2 1]Ahora que lo pienso, el taiyaki que metí en la nevera ya debería estar frío.[n][w][e]
[f 2 1]Debería sacarlo de la nevera y dárselo a Elizabeth.[n][w][e]

[msg MSG_ERROR [Shuji Ikutsuki]]
[f 2 1]エラーメッセージです。[n][f 1 5 0]杉山まで報告ください。[n][w][e]

