[msg MND_000_0_0]
[f 2 1]Estoy en la mazmorra de Shinagawa...[n][w][e]
[f 2 1]No veo a otros jugadores...[n][w][e]
[f 2 1]Se me acerca una chica de rojo.[n][w][e]

[msg MSG_001_0_0 [Chica de rojo]]
[f 2 1][bup 107 0 65535 65535 0 0][vp 3 0 65535 17004 0 0]spera, ste lugar no se llamaba d otra forma ants? o_O[n][w][e]
[f 2 1][bup 107 0 65535 65535 0 0]lunarvale, creo. bueno, da iguaal[n][w][e]
[f 2 1][bup 107 0 65535 65535 0 0]bienvnida, ulala *^_^* q alegria volver a vert[n][w][e]
[f 2 1][bup 107 0 65535 65535 0 0]t acuerdas d mí, no? =/[n][w][e]

[sel SEL_002_0_0 top]
[f 2 1]Por supuesto.[e]
[f 2 1]¿Nos hemos visto antes?[e]

[msg MSG_003_0_0 [Chica de rojo]]
[f 2 1][bup 107 0 65535 65535 0 0][vp 3 0 65535 17005 0 0][f 5 13 10 15 1]así q t acuerdas!! n_n[n][w][e]

[msg MND_004_0_0]
[f 2 1]La otra jugadora está contenta.[n][w][e]

[msg MSG_005_0_0 [Chica de rojo]]
[f 2 1][bup 107 0 65535 65535 0 0][vp 3 0 65535 17005 0 0]= q con maya y ulala, recuerdas? ^_^-b[n][w][e]

[msg MSG_006_0_0 [Chica de rojo]]
[f 2 1][bup 107 0 65535 65535 0 0][vp 3 0 65535 17004 0 0]ps vale. solo t he nmbrado... -_-;[n][w][e]

[msg MND_007_0_0]
[f 2 1]La otra jugadora está triste.[n][w][e]

[msg MSG_008_0_0 [Chica de rojo]]
[f 2 1][bup 107 0 65535 65535 0 0][vp 3 0 65535 17005 0 0]bno, si ves a algún gracioso, no t olvids d rscatarme, vale? =^_^=[n][w][e]

[msg MSG_009_0_0 [Maya]]
[f 2 1][bup 107 0 65535 65535 0 0][vp 3 0 65535 17005 0 0]mm... q hacemos jugando dntro cndo hace 1 día tan bueno?[n][w][e]

[sel SEL_010_0_0 top]
[f 2 1]¿No te gustan los videojuegos?[e]
[f 2 1]La luz del sol está sobrevalorada.[e]
[f 2 1]Supongo que somos unas fracasadas.[e]

[msg MSG_011_0_0 [Maya]]
[f 2 1][bup 107 0 65535 65535 0 0][vp 3 0 65535 17004 0 0]sí, los juegos molan, pero es q...(parezco 1 pringad).[n][w][e]
[f 2 1][bup 107 0 65535 65535 0 0]no tngo otras aficions, sabs? ._.[n][w][e]

[msg MND_012_0_0]
[f 2 1]Maya parece un poco desanimada.[n][w][e]

[msg MSG_013_0_0 [Maya]]
[f 2 1][bup 107 0 65535 65535 0 0][vp 3 0 65535 17002 0 0][f 5 13 10 5 1]JaJAjaJAJAJ!! ya te digo!XD[n][w][e]

[msg MND_014_0_0]
[f 2 1]Parece que a Maya le ha hecho gracia.[n][w][e]

[msg MSG_015_0_0 [Maya]]
[f 2 1][bup 107 0 65535 65535 0 0][vp 3 0 65535 17005 0 0]soy jugadora d por vida. :3[n][w][e]

[msg MSG_016_0_0 [Maya]]
[f 2 1][bup 107 0 65535 65535 0 0][vp 3 0 65535 17001 0 0]mmm... ps nsé. =/[n][w][e]

[msg MND_017_0_0]
[f 2 1]Maya está dudando.[n][w][e]

[msg MSG_018_0_0 [Maya]]
[f 2 1][bup 107 0 65535 65535 0 0][vp 3 0 65535 17005 0 0]la vida es 1 asco a vces...pro no qiero acabar solita ._.[n][w][e]

[msg MSG_019_0_0 [Maya]]
[f 2 1][bup 107 0 65535 65535 0 0][vp 3 0 65535 17005 0 0]me parto... tndríamos q star subien2 d nivel, pro ns hemos liao a hablar :3[n][w][e]
[f 2 1][bup 107 0 65535 65535 0 0]s q machacar los botones es 1 rollo. mola + hablar cntigo, ulala.[n][w][e]

[msg MND_020_0_0]
[f 2 1]Creo que Maya se está abriendo conmigo.[n][w][e]
[f 2 1]Tengo la sensación de que estamos estrechando lazos.[n][w][e]

[msg SYS_021_0_0]
[f 2 1]DEV: Unused label.[n][w][e]

[msg MSG_022_0_0 [Maya]]
[f 2 1][bup 107 0 65535 65535 0 0][vp 3 0 65535 17005 0 0]jo! mmm... m tengo q ir 1 rato, así q me dsconecto. prdón![n][w][e]
[f 2 1][bup 107 0 65535 65535 0 0]se m había olvida2 q hoy acaban las rbajas =x[n][w][e]

[msg MND_023_0_0]
[f 2 1]La jugadora Maya se ha desconectado...[n][w][e]
[f 2 1]He decidido desconectarme también.[n][w][e]

