[msg MSG_000_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 3 65535 65535 0 0][vp 3 0 65535 10084 0 0]La película era malísima, colega...[n][w][e]
[f 2 1][bup 101 3 65535 65535 0 0]¿Se supone que eso era gracioso o algo?[n][w][e]

[msg MSG_001_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 4 65535 65535 0 0][f 4 25 1]Mm...[n][w][e]
[f 2 1][bup 101 4 65535 65535 0 0]Para que lo sepas, tengo novia. No es que no quedemos nunca ni nada por el estilo.[n][w][e]

[msg MSG_001_5_0 [Kenji Tomochika]]
[f 2 1][bup 101 0 65535 65535 0 0]Lo que pasa es que Emiri siempre quiere que vaya a su casa...[n][w][e]
[f 2 1][bup 101 0 65535 65535 0 0]Y yo quiero llevarla a cenar o algo...[n][w][e]

[msg MSG_002_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 3 65535 65535 0 0][vp 3 0 65535 10092 0 0]Mmm... Tal vez sea por la apatía esa que hay por ahí.[n][w][e]
[f 2 1][bup 101 3 65535 65535 0 0]A lo mejor tiene miedo de pillarla... ¿Es contagiosa?[n][w][e]

[sel SEL_003_0_0 top]
[f 2 1]Sí, lo es.[e]
[f 2 1]No, no.[e]
[f 2 1]Ni idea.[e]

[msg MSG_004_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 4 65535 65535 0 0][vp 3 0 65535 10075 0 0]¡¿En serio?! Tía, entonces ¡¿qué hacemos aquí?![n][w][e]
[f 2 1][bup 101 3 65535 65535 0 0][f 4 23 0 101 10 25 25]¡Tenemos que quedarnos en casa o podríamos contagiarnos! Mierda, da miedo pensarlo...[n][w][e]

[msg MND_005_0_0]
[f 2 1]Tomochika parece muy preocupado.[n][w][e]
[f 2 1]Siento que hoy nuestra relación no ha cambiado nada...[n][w][e]

[msg MSG_006_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 1 65535 65535 0 0][vp 3 0 65535 10021 0 0][f 5 13 2 30 101]Ah, bien. Entonces, si se lo digo, probablemente me dejará llevarla a algún sitio, ¿no?[n][w][e]

[msg MND_007_0_0]
[f 2 1]Tomochika parece aliviado.[n][w][e]
[f 2 1]Siento que hoy nuestra relación se ha estrechado.[n][w][e]

[msg MSG_008_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 6 65535 65535 0 0][vp 3 0 65535 10072 0 0][f 5 13 2 15 101]Ya, supongo que tú tampoco lo sabrás. Nadie sabe mucho sobre el tema, ¿eh?[n][w][e]
[f 2 1][bup 101 0 65535 65535 0 0][f 4 23 0 101 0 25 25]No puedo reprocharle a Emiri que esté preocupada.[n][w][e]

[msg MND_009_0_0]
[f 2 1]Tomochika parece un poco serio.[n][w][e]
[f 2 1]Hoy he aprendido un poco más sobre él.[n][w][e]

[msg MSG_010_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 0 65535 65535 0 0][vp 3 0 65535 10054 0 0]Si salimos a una cita, deberíamos ir a un lugar donde haya menos gente, por si acaso...[n][w][e]
[f 2 1][bup 101 0 65535 65535 0 0]Quizá encuentro lugares así buscando en una revista. ¿Te importa si paramos en una librería?[n][w][e]

[msg MND_011_0_0]
[f 2 1]Tras ir a la librería, he decidido volver a la residencia.[n][w][e]

