[msg MSG_MITSURU_TARTAROS_050 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0]Se viene un fin de semana largo, sugiero que utilicemos este tiempo para ir a la torre Tártaro.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Todavía queda para que Akihiko se recupere, y no quiero repetir lo sucedido el mes pasado.[n][w][e]
[f 2 1][bup 5 3 65535 65535 0 0][vp 3 0 65535 4061 0 0]Además, el número de víctimas parece estar aumentando y... me da un mal presentimiento...[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Por todos estos motivos nos conviene fortalecernos todo lo que podamos.[n][w][e]

[msg MSG_MITSURU_0501 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0]Se avecina un fin de semana largo, ¿verdad?[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Akihiko va a necesitar mas tiempo para recuperarse. Espero que no ocurra nada mientras tanto.[n][w][e]
[f 2 1][bup 5 3 65535 65535 0 0]El número de víctimas parece aumentar, y me temo que esto sea el inicio de algo mucho mayor...[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Nos conviene fortalecernos mientras podamos.[n][w][e]

[msg MSG_MITSURU_OK_0501 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0]Ah, sobre la recuperación de Akihiko... Parece que necesitará un poco más de tiempo.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]...En fin, no es cuestión de ponerse a correr. Habéis trabajado duro. Aprovechad el fin de semana largo para descanar.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Dicho eso, está habiendo un aumento en el número de incidentes, así que manteneos al tanto.[n][w][e]
[f 2 1][bup 5 3 65535 65535 0 0][vp 3 0 65535 4061 0 0]...Tengo un mal presentimiento del que no consigo quitarme... Puede que sea una preocupación mía innecesaria.[n][w][e]

[msg MSG_JUNPEI_TARTAROS_0502 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0]Por fin, ¡mañana empieza el fin de semana de tres días![n][w][e]
[f 2 1][bup 3 3 65535 65535 0 0]Le pregunté a la peña si les apetecía quedar, pero solo los tíos querían quedar...[n][w][e]

[msg MSG_MITSURU_TARTAROS_050_2 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4136 0 0]Más te conviene utilizar tu tiempo con cabeza. ¿He de recordarte de los parciales a la vuelta de la esquina?[n][w][e]

[msg MSG_YUKARI_TARTAROS_0502 [Yukari Takeba]]
[f 2 1][bup 2 3 65535 65535 0 0][vp 3 0 65535 1119 0 0]Y yo que creía que podía vivir en la ignorancia por un par de días... *suspiro*[n][w][e]

[msg MSG_JUNPEI_TARTAROS_0503 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0]Un colega estaba contado...[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Aparentemente hay un tío en el Escapade vendiendo enlaces a... páginas peculiaries.[n][w][e]

[sel SEL_093_0_0 top]
[f 2 1]¿Vendiendo enlaces?[e]
[f 2 1]A que me compras uno.[e]

[msg MSG_JUNPEI_TARTAROS_0503_2 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2078 0 0]Sip. Dudo que sean páginas a las que un cualquiera pueda acceder sin más, ¿me pillas?[n][w][e]

[msg MSG_JUNPEI_TARTAROS_0503_3 [Junpei Iori]]
[f 2 1][bup 3 4 65535 65535 0 0][vp 3 0 65535 2102 0 0]¡¿Qué?! Anda, con que esas tenemos, ¿eh? Pues me da que no, tía.[n][w][e]

[msg MSG_JUNPEI_TARTAROS_0503_4 [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0]Suena bastante interesante, pero un club glamoroso como ese seguramente esté de seguridad a tutiplén, ¿no?[n][w][e]
[f 2 1][bup 3 3 65535 65535 0 0]Ni de coña dejan a un estudiante entrar así por la cara. Necesitas estar hasta arriba de [clr 34]Coraje[clr 27] para intentar colarte.[n][w][e]

[msg MSG_YUKARI_TARTAROS_0506 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][nl], vayamos a la torre Tártaro esta noche.[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0]No está pasando nada desde aquel día y me está empezando a preocupar...[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0]Y hay más gente cayendo con el Síndrome de Apatía estos días, ¿verdad? ¿No me estoy volviendo loca?[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0]Tengo el presentimiento de que algo chungo va a pasar... Igual me está pudiendo la paranoia, ja...[n][w][e]

[msg MSG_YUKARI_0506 [Yukari Takeba]]
[f 2 1][bup 2 3 65535 65535 0 0]¿Es cosa mía o es que hay más gente cayendo con el Síndrome de Apatía últimamente?[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0]...Oye, ¿y si vamos a la torre Tártaro más tarde?[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0]Deberíamos ponernos lo más fuertes que podamos, por si acaso.[n][w][e]

[msg MSG_YUKARI_OK_0506 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0]¿Es cosa mía o es que hay más gente cayendo con el Síndrome de Apatía últimamente?[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0]Por alguna razón, presiento que algo malo va a ocurrir... Quizá esté siendo paranoica.[n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0]A ver, no es que haya pasado nada desde aquel día, así que deberíamos estar bien, ¿no?[n][w][e]

[msg MSG_JUNPEI_TARTAROS_0507 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0]Oye, ¿has visto cuántos de esos raritos hay por la ciudad últimamente?[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]...Tío, todo tiene que ser un tremendo coñazo cuando esa es la noticia del día.[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2117 0 0]¿Qué tal si vamos a la torre Tártaro? ¿Qué mejor forma de hacer tiempo?[n][w][e]

[msg MSG_SANADA_TARTAROS_0507 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 3 0 65535 3130 0 0]A lo mejor yo también me apunto... Me muero del aburrimiento.[n][w][e]

[msg MSG_MITSURU_TARTAROS_050_3 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4089 0 0]...Akihiko, ¿acaso tratas de enfadarme?[n][w][e]

[msg MSG_JUNPEI_OK_0507 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0]Oye, ¿has visto cuántos de esos raritos hay por la ciudad últimamente?[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]...Tío, todo tiene que ser un tremendo coñazo cuando esa es la noticia del día.[n][w][e]
[f 2 1][bup 3 3 65535 65535 0 0]¿Qué tal si vamos a la torre Tártaro? Aunque hemos llegado a un bloqueo... Así que, ¿no podremos avanzar más?[n][w][e]

[msg MSG_SANADA_OK_0507 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0]Ni idea. La disposición del sitio cambia todos los días, supuestamente, ¿así que quién sabe?[n][w][e]
[f 2 1][bup 4 1 65535 65535 0 0][vp 3 0 65535 3085 0 0]Mm... Quizá deba de ir a investigar con vosotros, por si acaso.[n][w][e]

[msg MSG_MITSURU_OK_0507_2 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4089 0 0]...Akihiko, ¿acaso tratas de enfadarme?[n][w][e]

[msg MSG_MITSURU_TARTAROS_050_4 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0]...Qué extraño. Todo está muy en silencio.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Ha pasado un mes, pero no me creo que esa sea la última vez que las veamos fuera de la torre Tártaro.[n][w][e]

[msg MSG_SANADA_TARTAROS_0508 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 3 0 65535 3027 0 0]Estoy de acuerdo.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0]Ha habido un aumento considerable de Perdidos recientemente. No me sorprendería si algo hubiera pasado.[n][w][e]

[msg MND_TARTAROS_0508]
[f 2 1]El chico misterioso que vi durante la Hora[n]Oscura me avisó de un percal dentro de una semana.[n][w][e]
[f 2 1]Mañana será exactamente una semana[n]desde entonces. Debería prepararme hoy...[n][w][e]

[msg MND_ToVelvetRoom_0510]
[f 2 1]¿A qué se debe este asunto tan urgente?[n][w][e]
[f 2 1]Debería ir a la Sala Terciopelo.[n][w][e]

[msg MSG_MITSURU_TARTAROS_051 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0]Parece que la maquinaria de la sala de comandos no funciona correctamente.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]¿Te importaría subir a revisarla? No debería llevarte mucho tiempo.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]También se lo he pedido a Akihiko y a Iori, pero no parecían muy por la labor de resolver el problema.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]No parece ser particularmente urgente, por tanto ve cuando puedas. Gracias.[n][w][e]

[msg MSG_YUKARI_TARTAROS_0512 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0]Justo iba a salir a por los apuntes de mi amiga.[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0]Necesito de veras estudiar para los parciales...[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0]Así que hoy no podré ir a la Tártaro. Lo siento.[n][w][e]

[msg MSG_JUNPEI_0513_1 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0]*suspiro* Estoy tan harto de estudiar. Venga, vamos a la torre Tártaro.[n][w][e]

[sel SEL_016_0_0 top]
[f 2 1]Me lo pienso.[e]
[f 2 1]Deberías seguir estudiando.[e]

[msg MSG_JUNPEI_0513_RE [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2086 0 0]¡Genial! ¡Cómo sabía que podía contar contigo, tía![n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]Tú también te vienes, ¿verdad, Yuka?[n][w][e]

[msg MSG_JUNPEI_0513_RE_2 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2111 0 0]¿¡Tía, en serio!?[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]¿No es más importante salvar el mundo? Yuka, tú también quieres ir, ¿a que sí?[n][w][e]

[msg MSG_YUKARI_0513 [Yukari Takeba]]
[f 2 1][bup 2 3 65535 65535 0 0][vp 3 0 65535 1076 0 0]Tú te das cuenta de que los exámenes son en nada, ¿verdad?[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0]Pero supongo que un descanso nunca viene mal... Venga va, si váis a la torre Tártaro, yo también me animo.[n][w][e]

[msg MSG_JUNPEI_TARTAROS_0514 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0]Oye, vamos a la torre Tártaro.[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Puedes estudiar en cualquier momento. Tenemos que entrenar ya de ya.[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]No querrás que te deje mordiendo el polvo, ¿no? ¡Me cargo a la próxima Sombra grande yo solito![n][w][e]

[sel SEL_022_0_0 top]
[f 2 1]Qué confianza.[e]
[f 2 1]Ve a estudiar, anda.[e]

[msg MSG_JUNPEI_0514_RE_1 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2132 0 0]¡Hombre claro! ¡Estás que no![n][w][e]

[msg MSG_JUNPEI_0514_RE_2 [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0][vp 3 0 65535 2124 0 0]Venga tía, dame un respiro...[n][w][e]

[msg MSG_MITSURU_TARTAROS_051_2 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4136 0 0]Pero bueno, Iori, se ve que confías plenamente en tus notas para insistir tanto en no estudiar.[n][w][e]

[msg MSG_JUNPEI_TARTAROS_0514_2 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2111 0 0]Ah, sí, bueno... Igual no me viene mal repasar un poquito...[n][w][e]

[msg MSG_JUNPEI_0514_1 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0]Oye, vamos a la torre Tártaro.[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Puedes estudiar en cualquier momento. Tenemos que entrenar ya de ya.[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]¡Hermes se muere de ganas de repartir leña![n][w][e]

[msg MSG_JUNPEI_OK_0514_1 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0]Uf, me da tanta pereza estudiar, pero tampoco es que haya nada mejor que hacer...[n][w][e]

[sel SEL_095_0_0 top]
[f 2 1]Sé cómo te sientes.[e]
[f 2 1]Pues estudia.[e]

[msg MSG_JUNPEI_OK_0514_RE_1 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2026 0 0]¿A que sí? Haría prácticamente cualquier cosa con tal de no estudiar...[n][w][e]

[msg MSG_JUNPEI_OK_0514_RE_2 [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0][vp 3 0 65535 2124 0 0]Venga ya, tía, ¿tú también...?[n][w][e]

[msg MSG_MITSURU_OK_0514_1 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4061 0 0]Se ve que confías plenamente en tus notas, Iori. Espero con ansia los resultados de tus exámenes.[n][w][e]

[msg MSG_JUNPEI_STUDY_0516_1 [Junpei Iori]]
[f 2 1][bup 3 4 65535 65535 0 0][vp 3 0 65535 2006 0 0]Porfaaa, ¡Yukaaa! ¡Eres la única que puede salvarme! Esta será la última vez, ¡te lo juro![n][w][e]

[msg MSG_YUKARI_STUDY_0516_1 [Yukari Takeba]]
[f 2 1][bup 2 3 65535 65535 0 0][vp 3 0 65535 1049 0 0]¿Pero por qué soy la única? *suspiro* Vale, deja de quejarte. ¿Dónde has dejado de tomar apuntes?[n][w][e]

[msg MSG_JUNPEI_STUDY_0516_2 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0]Ah, pues, más o menos... al principio...[n][w][e]

[msg MSG_MITSURU_STUDY_0517_1 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0]Estoy segura de que ya lo sabes, pero los [clr 2]parciales[clr 27] empiezan mañana.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Ya que habéis dedicado tanto tiempo a explorar la Tártaro, qué menos que ayudaros con los estudios.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Por lo tanto, he organizado una sesión de estudio en grupo.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Ya he avisado a los demás, así que si dispones del tiempo, me gustaría que participases.[n][w][e]

[msg MSG_SANADA_TARTAROS_0526 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0]Oye, si te parece, ¿vamos luego a la torre Tártaro?[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0]Necesito volver a coger el ritmo.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0]Además, no es plan dejaros toda la diversión para vosotros.[n][w][e]

[msg MSG_SANADA_0526 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0]Oye, si te parece, ¿vamos luego a la torre Tártaro?[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0]Necesito volver a coger el ritmo. Probablemente también te venga bien entrenar un poco.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0]No podemos depender de una hipotética recluta nueva. El enemigo puede atacar en cualquier momento...[n][w][e]

[msg MSG_SANADA_OK_0526 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0]Sé que se está hablando de una nueva recluta, pero no esperes demasiado de ella inmediatamente.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0]Si hay otra pelea de las gordas, no deberíamos meterla de cabeza en el lío, si es que acaso se nos une.[n][w][e]
[f 2 1][bup 4 1 65535 65535 0 0]Pero aquí es donde entro yo. Tengo que compensar todas las peleas que me he perdido.[n][w][e]

[msg MSG_MITSURU_TARTAROS_052 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0]Qué extraño...[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]El número de víctimas del Síndrome de Apatía parece estar en aumento de nuevo...[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Evidentemente, el decremento anterior fue meramente temporal.[n][w][e]

[msg MSG_YUKARI_TARTAROS_0528 [Yukari Takeba]]
[f 2 1][bup 2 3 65535 65535 0 0][vp 3 0 65535 1092 0 0]Si ese es el caso, entonces, ¿qué sentido tiene luchar?[n][w][e]

[msg MSG_MITSURU_TARTAROS_052_2 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4031 0 0]Si no hacemos nada, todo el mundo formará parte de los Perdidos.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Nuestros esfuerzos han evitado que la crisis llegue hasta tal punto.[n][w][e]

[msg MSG_YUKARI_TARTAROS_0528_2 [Yukari Takeba]]
[f 2 1][bup 2 3 65535 65535 0 0][vp 3 0 65535 1028 0 0]Sí... Supongo que tienes razón.[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0]No me gustaría nada ver qué sería de la ciudad si no fuera por nuestras Personas...[n][w][e]

[msg MSG_YUKARI_TARTAROS_0530 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0]¿Has oído el rumor que corre por el instituto?[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0]Venga ya, a ver, ¿una historia de fantasmas? Te pensarías que ya son mayorcitos para creer en fantasmas, ¿no?[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0]...Em, en fin, esto... Me siento un poco rara así de repente, así que creo que me acostaré pronto.[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0][vp 3 0 65535 1056 0 0]Ah, supongo que entonces no iré a la torre Tártaro hoy. Lo siento.[n][w][e]

[msg MSG_WELCOME_YUKARI_OUT [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 3 0 65535 1019 0 0]Ah, eh... Hola.[n][w][e]

[msg MSG_WELCOME_YUKARI_OUT2 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 3 0 65535 1012 0 0]Eh... Hola...[n][w][e]

[msg MSG_WELCOME_JUNPEI_OUT [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2018 0 0]¿Qué pasa, tía?[n][w][e]

[msg MSG_WELCOME_JUNPEI_OUT2 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2012 0 0]Hola, tía...[n][w][e]

[msg MSG_WELCOME_MITSURU_OUT [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4018 0 0]Hola de nuevo.[n][w][e]

[msg MSG_WELCOME_MITSURU_OUT2 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4027 0 0]Hola de nuevo...[n][w][e]

[msg MSG_WELCOME_SANADA_OUT [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 3 0 65535 3017 0 0]Anda, has vuelto.[n][w][e]

[msg MSG_WELCOME_FUKA_OUT [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5018 0 0]Hola, ¿qué tal el día?[n][w][e]

[msg MSG_WELCOME_FUKA_OUT2 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5028 0 0]Ah... Hola...[n][w][e]

[msg MSG_WELCOME_AEGIS_OUT_RO [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 3 0 65535 6018 0 0]Saludos.[n][w][e]

[msg MSG_WELCOME_AEGIS_OUT [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6018 0 0]Saludos.[n][w][e]

[msg MSG_WELCOME_AEGIS_OUT_NA [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6017 0 0]Hola otra vez. Me alegro de volver a verte.[n][w][e]

[msg MSG_WELCOME_KOROMARU_OUT [Koromaru]]
[f 2 1][bup 9 0 65535 65535 0 0][vp 3 0 65535 8008 0 0]¡Guau![n][w][e]

[msg MSG_WELCOME_AMADA_OUT [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 3 0 65535 7020 0 0]¡Anda, hola![n][w][e]

[msg MSG_WELCOME_AMADA_OUT2 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 3 0 65535 7012 0 0]Ah... Hola...[n][w][e]

[msg MSG_WELCOME_ARAGAKI_OUT [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 3 0 65535 9014 0 0]Ey...[n][w][e]

[msg MSG_WELCOME_IKUTSUKI_OUT [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 3 0 65535 14201 0 0]Hola de nuevo.[n][w][e]

[msg MSG_WELCOME_YUKARI_IN [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 3 0 65535 1067 0 0]¡Ah, estás aquí![n][w][e]

[msg MSG_WELCOME_YUKARI_IN2 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 3 0 65535 1012 0 0]Ah, ¿ya has llegado? Perdona, no te había visto.[n][w][e]

[msg MSG_WELCOME_JUNPEI_IN [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2009 0 0]Eh, ¿qué pasa?[n][w][e]

[msg MSG_WELCOME_JUNPEI_IN2 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2012 0 0]Ah, hola...[n][w][e]

[msg MSG_WELCOME_MITSURU_IN [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4029 0 0]¿Eh? Ah, eres tú...[n][w][e]

[msg MSG_WELCOME_MITSURU_IN2 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4027 0 0]¿Mmm? Ah, ya estás aquí.[n][w][e]

[msg MSG_WELCOME_SANADA_IN [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 3 0 65535 3024 0 0]¿Has estado en tu habitación todo este tiempo?[n][w][e]

[msg MSG_WELCOME_FUKA_IN [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5067 0 0]¡Ah, hola! No sabía que ya estabas aquí.[n][w][e]

[msg MSG_WELCOME_FUKA_IN2 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5093 0 0]Anda, ¿estás aquí? Hola...[n][w][e]

[msg MSG_WELCOME_FUKA_IN_0712 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5067 0 0]Ah, [nl]...[n][w][e]

[msg MSG_WELCOME_AEGIS_IN_ROB [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 3 0 65535 6008 0 0]Buenas tardes.[n][w][e]

[msg MSG_WELCOME_AEGIS_IN [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6008 0 0]Buenas tardes.[n][w][e]

[msg MSG_WELCOME_AEGIS_IN_NAK [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6009 0 0]¿Qué tal el día? ¿Todo bien?[n][w][e]

[msg MSG_WELCOME_KOROMARU_IN [Koromaru]]
[f 2 1][bup 9 0 65535 65535 0 0][vp 3 0 65535 8001 0 0]¡Guau, guau![n][w][e]

[msg MSG_WELCOME_AMADA_IN [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 3 0 65535 7010 0 0]¿Has estudiado algo?[n][w][e]

[msg MSG_WELCOME_AMADA_IN2 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 3 0 65535 7012 0 0]¿Estabas aquí? Pues... hola.[n][w][e]

[msg MSG_WELCOME_ARAGAKI_IN [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 3 0 65535 9056 0 0]... ¿Qué hay?[n][w][e]

[msg MSG_WELCOME_IKUTSUKI_IN [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 3 0 65535 14204 0 0]Ah, no sabía que ya estabas aquí. He venido a hacer una visita rápida.[n][w][e]

[msg MND_SHYUKAKU_OK]
[f 2 1]Ahora que lo pienso, las hortalizas que planté en la azotea ya se podrán recolectar.[n][w][e]
[f 2 1]Debería ir a echarles un ojo...[n][w][e]

[msg MND_SHYUKAKU_TAIYAKI_OK]
[f 2 1]Ahora que lo pienso, las hortalizas que planté en la azotea ya se podrán recolectar.[n][w][e]
[f 2 1]Y el taiyaki que metí en la nevera también debería estar frío.[n][w][e]
[f 2 1]Debería ir a echarles un ojo...[n][w][e]

[msg MND_SHYUKAKU_TAIYAKI_OK_]
[f 2 1]Ahora que lo pienso, las hortalizas que planté en la azotea ya se podrán recolectar.[n][w][e]
[f 2 1]Y el taiyaki que metí en la nevera también debería estar frío.[n][w][e]
[f 2 1]Debería sacarlo de la nevera y dárselo a Elizabeth.[n][w][e]

[msg MND_TAIYAKI_OK]
[f 2 1]Ahora que lo pienso, el taiyaki que metí en la nevera ya debería estar frío.[n][w][e]
[f 2 1]Debería ir a por él.[n][w][e]

[msg MND_TAIYAKI_OK_QUEST]
[f 2 1]Ahora que lo pienso, el taiyaki que metí en la nevera ya debería estar frío.[n][w][e]
[f 2 1]Debería sacarlo de la nevera y dárselo a Elizabeth.[n][w][e]

[msg MSG_ERROR [Shuji Ikutsuki]]
[f 2 1]エラーメッセージです。[n][f 1 5 0]杉山まで報告ください。[n][w][e]

