[msg MND_000_0_0]
[f 2 1]Veo mi cara habitual reflejada en el espejo.[n][w][e]

[msg MND_001_0_0]
[f 2 1]Veo mi cara de cansancio reflejada en el espejo.[n][w][e]

[msg MND_002_0_0]
[f 2 1]Veo mi cara lozana reflejada en el espejo.[n][w][e]

[msg MND_003_0_0]
[f 2 1]Veo mi cara normal reflejada en el espejo.[n][w][e]

[msg MND_004_0_0]
[f 2 1]Me veo reflejada en el espejo. Estoy más viva que nunca.[n][w][e]

[msg MND_005_0_0]
[f 2 1]Me veo reflejada en el espejo. [n]Irradio un aura especial.[n][w][e]

[msg MND_006_0_0]
[f 2 1]Veo un reflejo atractivo capaz de conquistar el corazón de la gente.[n][w][e]

[msg MND_CLOSET_0406]
[f 2 1]En mi reflejo me veo cansada.[n][w][e]
[f 2 1]Debería guardar mis cosas y acostarme pronto.[n][w][e]

[msg MND_GO_TO_BED_0406]
[f 2 1]Veo mi cara de cansancio reflejada en el espejo. Hoy debería acostarme pronto.[n][w][e]

[msg MND_GO_TO_BED_0407]
[f 2 1]Veo mi cara de cansancio reflejada en el espejo. Debería meterme en la cama.[n][w][e]

[msg MND_010_0_0]
[f 2 1]Me veo reflejada en el espejo. Qué pinta tan espantosa...[n][w][e]

