[msg MSG_000_0_0 [Elizabeth]]
[f 2 1][bup 202 0 65535 65535 0 0][vp 3 0 65535 13212 0 0]Parece que tu poder se ha acrecentado. ¿Teúrgia, no...? Un logro de lo más encomiable.[n][w][e]
[f 2 1][bup 202 0 65535 65535 0 0]Hablando de ese poder... Quisiera saber si estás familiarizada con los arcanos mayores.[n][w][e]

[sel SEL_001_0_0 top]
[f 2 1]Sí.[e]
[f 2 1]¿Qué es eso...?[e]

[msg MSG_001_0_0 [Elizabeth]]
[f 2 1][bup 202 0 65535 65535 0 0][vp 3 0 65535 13207 0 0]Si usáramos una metáfora, diríamos que los arcanos mayores son como las plantas madre a partir de la que se desarrolla tu jardín de habilidades.[n][w][e]
[f 2 1][bup 202 0 65535 65535 0 0]Tras derrotar a las sombras más poderosas, estos arcanos mayores aparecerán en forma de carta.[n][w][e]
[f 2 1][bup 202 0 65535 65535 0 0]Sería conveniente que coleccionaras estas cartas a medida que las vayas encontrando.[n][w][e]

[msg MSG_002_0_0 [Elizabeth]]
[f 2 1][bup 202 0 65535 65535 0 0][vp 3 0 65535 13215 0 0]Parece que cuando cambias, también cambia la Tártaro. Tanto arriba como abajo.[n][w][e]
[f 2 1][bup 202 0 65535 65535 0 0]Han aparecido varias puertas singulares en la Tártaro.[n][w][e]
[f 2 1][bup 202 0 65535 65535 0 0]A dónde conducen estas puertas, o si presagian algo bueno o malo...[n][w][e]
[f 2 1][bup 202 0 65535 65535 0 0]... ni yo misma sabría decirlo.[n][w][e]
[f 2 1][bup 202 0 65535 65535 0 0]Sin embargo, creo que tú dispones de los medios para averiguarlo. Si te arriesgas, puede que descubras algo útil.[n][w][e]

[sel SEL_002_0_0 top]
[f 2 1]Vale.[e]
[f 2 1]Mejor no...[e]
[f 2 1]¿Por qué?[e]

[msg MSG_016_0_0 [Elizabeth]]
[f 2 1][bup 202 0 65535 65535 0 0]Estupendo. ¡Confío en vosotros![n][w][e]

[msg MSG_017_0_0 [Elizabeth]]
[f 2 1][bup 202 0 65535 65535 0 0]Vamos. En asuntos como este, la modestia no tiene cabida.[n][w][e]

[msg MSG_003_0_0 [Elizabeth]]
[f 2 1][bup 202 0 65535 65535 0 0][vp 3 0 65535 13228 0 0]Aquellos que se aventuran a lo desconocido, y que eligen el riesgo frente a la tranquilidad, suelen logran grandes cosas.[n][w][e]
[f 2 1][bup 202 0 65535 65535 0 0]Creo que esos retos facilitan el crecimiento.[n][w][e]
[f 2 1][bup 202 0 65535 65535 0 0]Tu valor te conducirá a la mejora, [nf]. Espero de todo corazón que sigas así.[n][w][e]

[msg MND_004_0_0 [DEV: Internal MES]]
[f 2 1]Algo extraño está pasando en la Tártaro...[n][w][e]
[f 2 1]¿Debería investigar estas puertas?[n][w][e]

[msg MSG_005_0_0 [Elizabeth]]
[f 2 1][bup 202 0 65535 65535 0 0][vp 3 0 65535 13222 0 0]Debo felicitarte por tu reciente victoria. Parece que tu poder no cesa de crecer.[n][w][e]
[f 2 1][bup 202 0 65535 65535 0 0]Hablando de ese poder... Quisiera saber si estás familiarizada con los arcanos mayores.[n][w][e]

[sel SEL_003_0_0 top]
[f 2 1]Sí.[e]
[f 2 1]¿Qué es eso...?[e]

[msg MND_007_0_0 [DEV: Internal MES]]
[f 2 1]Conque los arcanos mayores...[n][w][e]
[f 2 1]En el futuro serán un recurso útil...[n][w][e]

[msg MSG_006_0_0 [Elizabeth]]
[f 2 1][bup 202 0 65535 65535 0 0][vp 3 0 65535 13217 0 0]Mientras aguardaba tu llegada, sentí algo diferente en la Tártaro.[n][w][e]
[f 2 1][bup 202 0 65535 65535 0 0]Al parecer, han aparecido varias puertas extrañas.[n][w][e]
[f 2 1][bup 202 0 65535 65535 0 0]A dónde conducen estas puertas, o si presagian algo bueno o malo...[n][w][e]
[f 2 1][bup 202 0 65535 65535 0 0]... ni yo misma sabría decirlo.[n][w][e]
[f 2 1][bup 202 0 65535 65535 0 0]Sin embargo, creo que tú dispones de los medios para averiguarlo. Si te arriesgas, puede que descubras algo útil.[n][w][e]

