[msg MSG_000_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 102 65535 0 0][vp 1 0 0 1 0 0]¡Uoooo! ¡Objetivo a la vista![n][w][e]

[msg MSG_000_5_0 [Junpei Iori]]
[f 2 1][bup 3 1 102 65535 0 0][vp 1 0 0 2 0 0]¡Listo para matar![n][w][e]

[msg MSG_001_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 102 65535 0 0][vp 1 0 0 3 0 0]Atención, que en esto soy un experto, así que os voy a dar unos consejillos.[n][w][e]

[msg MSG_001_5_0 [Junpei Iori]]
[f 2 1][bup 3 1 102 65535 0 0][vp 1 0 0 4 0 0]Lo primero es pensar un tema de conversación, algo que les pueda interesar.[n][w][e]
[f 2 1][bup 3 1 102 65535 0 0][vp 1 0 0 5 0 0]Hay que hacerles una pregunta sencillita para que la cosa empiece a rodar. Esa es la clave.[n][w][e]

[msg MSG_002_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 102 65535 0 0][vp 1 0 0 6 0 0]Algo como "¿De dónde eres?" o "¿Qué, disfrutando?".[n][w][e]
[f 2 1][bup 3 1 102 65535 0 0][vp 1 0 0 7 0 0]Luego intercambiaréis preguntas y respuestas, como en un partido de tenis.[n][w][e]

[msg MSG_002_3_0 [Junpei Iori]]
[f 2 1][bup 3 1 102 65535 0 0][vp 1 0 0 8 0 0]Empiezo yo y tú haces las preguntas, ¿vale?[n][w][e]

[msg MSG_002_5_0 [Junpei Iori]]
[f 2 1][bup 3 0 102 65535 0 0][vp 1 0 0 9 0 0][f 4 23 0 3 0 25 25]Venga, vamos allá.[n][w][e]

[msg MSG_003_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 102 65535 0 0][vp 1 0 0 10 0 0]¡Hola, chicas![n][w][e]

[sel SEL_004_0_0 top]
[f 2 1]¿De dónde sois?[e]
[f 2 1]¿Qué, disfrutando?[e]

[msg MSG_005_0_0 [Chica de verde]]
[f 2 1][vp 1 0 0 11 0 0][f 5 21 0 1001]No es asunto vuestro.[n][w][e]

[msg MSG_006_0_0 [Chica de verde]]
[f 2 1][vp 1 0 0 12 0 0][f 5 21 0 1001]No es asunto vuestro.[n][w][e]

[msg MSG_007_0_0 [Junpei Iori]]
[f 2 1][bup 3 3 102 65535 0 0][vp 1 0 0 13 0 0]¿Eh?[n][w][e]

[msg MSG_007_5_0 [Junpei Iori]]
[f 2 1][bup 3 1 102 65535 0 0][vp 1 0 0 14 0 0][f 4 23 0 3 1 25 25]Venga, no seáis tímidas.[n][w][e]

[msg MSG_008_0_0 [Chica de naranja]]
[f 2 1][vp 1 0 0 15 0 0][f 5 21 0 1002]¿Por qué deberíamos decíroslo?[n][w][e]

[msg MSG_009_0_0 [Junpei Iori]]
[f 2 1][bup 3 3 102 65535 0 0][vp 1 0 0 16 0 0]¿Por qué? Pues porque...[n][w][e]

[msg MSG_009_5_0 [Junpei Iori]]
[f 2 1][bup 3 1 102 65535 0 0][vp 1 0 0 17 0 0][f 4 23 0 3 1 25 25]Venga, que solo queremos charlar un rato.[n][w][e]

[msg MSG_010_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 2 102 65535 0 0][vp 1 0 0 18 0 0]¿Como un partido de tenis decías?[n][w][e]

[msg MSG_011_0_0 [Junpei Iori]]
[f 2 1][bup 3 3 102 65535 0 0][vp 1 0 0 19 0 0]Tranqui, está todo controlado. Mira y aprende.[n][w][e]

[msg MSG_012_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 102 65535 0 0][vp 1 0 0 20 0 0]¿Estudiáis o trabajáis, guapas?[n][w][e]

[msg MSG_013_0_0 [Chica de naranja]]
[f 2 1][vp 1 0 0 21 0 0][f 5 21 0 1002]Mmm...[n][w][e]
[f 2 1][vp 1 0 0 22 0 0][f 5 21 0 1002]Vosotros parecéis un poco jóvenes. ¿Vais al instituto?[n][w][e]

[sel SEL_014_0_0 top]
[f 2 1]Eso es.[e]
[f 2 1]Qué va.[e]

[msg MSG_015_0_0 [Chica de verde]]
[f 2 1][vp 1 0 0 23 0 0][f 5 21 0 1001]¿Unos estudiantes de instituto de vacaciones en Yakushima? Maldita la gracia.[n][w][e]

[msg MSG_016_0_0 [Chica de verde]]
[f 2 1][vp 1 0 0 24 0 0][f 5 21 0 1001]¿En serio? Desde aquí, parecéis estudiantes de instituto.[n][w][e]

[msg MSG_017_0_0 [Junpei Iori]]
[f 2 1][bup 3 3 102 65535 0 0][vp 1 0 0 25 0 0]N-no, perdona. Era mentira.[n][w][e]

[msg MSG_018_0_0 [Chica de verde]]
[f 2 1][vp 1 0 0 26 0 0][f 5 21 0 1001]¿En serio?[n][w][e]

[msg MSG_018_5_0 [Chica de verde]]
[f 2 1][vp 1 0 0 27 0 0][f 5 21 0 1001]¿Unos estudiantes de instituto de vacaciones en Yakushima? Maldita la gracia.[n][w][e]

[msg MSG_019_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 3 102 65535 0 0][vp 1 0 0 28 0 0]Lamento que te sientas así.[n][w][e]
[f 2 1][bup 4 0 102 65535 0 0][vp 1 0 0 29 0 0][f 4 23 0 4 0 25 25]Es que una amiga nos ha invitado a su casa de veraneo.[n][w][e]

[msg MSG_020_0_0 [Chica de naranja]]
[f 2 1][vp 1 0 0 30 0 0][f 5 21 0 1002]Vaya, ¿una casa de veraneo en Yakushima? Pues me alegro por ella.[n][w][e]
[f 2 1][vp 1 0 0 31 0 0][f 5 21 0 1002]Nosotras hemos tenido que ahorrar mucho para venir.[n][w][e]

[msg MSG_021_0_0 [Junpei Iori]]
[f 2 1][bup 3 3 102 65535 0 0][vp 1 0 0 32 0 0]Jo, pues qué guay, ¿no?[n][w][e]

[msg MSG_022_0_0 [Chica de naranja]]
[f 2 1][vp 1 0 0 33 0 0][f 5 21 0 1002]No, la verdad.[n][w][e]
[f 2 1][vp 1 0 0 34 0 0][f 5 21 0 1002]Bueno, ¿y qué queréis?[n][w][e]

[sel SEL_023_0_0 top]
[f 2 1]Nada.[e]
[f 2 1]Hemos venido a ligar con vosotras.[e]

[msg MSG_024_0_0 [Chica de verde]]
[f 2 1][vp 1 0 0 35 0 0][f 5 21 0 1001]Genial, pues chaíto.[n][w][e]

[msg MSG_025_0_0 [Chica de verde]]
[f 2 1][vp 1 0 0 36 0 0][f 5 21 0 1001]¿Qué? Ja, ja, me gusta que seas sincera.[n][w][e]

[msg MSG_026_0_0 [Chica de naranja]]
[f 2 1][vp 1 0 0 37 0 0][f 5 21 0 1002]Pf, no les des coba. Si pasamos de ellos, se irán.[n][w][e]

[msg MSG_027_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 102 65535 0 0][vp 1 0 0 38 0 0]¡E-esperad, no nos hagáis eso![n][w][e]
[f 2 1][bup 3 1 102 65535 0 0][vp 1 0 0 39 0 0]¿Qué tiene de malo querer hablar con unos bellezones como vosotras?[n][w][e]

[msg MSG_028_0_0 [Chica de naranja]]
[f 2 1][vp 1 0 0 40 0 0][f 5 21 0 1002]Vaya panda de gilipollas.[n][w][e]

[msg MSG_029_0_0 [Chica de verde]]
[f 2 1][vp 1 0 0 41 0 0][f 5 21 0 1001]Sí, larguémonos de aquí.[n][w][e]

[sel SEL_030_0_0 top]
[f 2 1]Espera...[e]
[f 2 1]Hasta otra.[e]

[msg MSG_031_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 102 65535 0 0][vp 1 0 0 42 0 0]Venga, dadnos una oportunidad... ¿Damos un paseo por la playa?[n][w][e]

[msg MSG_032_0_0 [Chica de naranja]]
[f 2 1][vp 1 0 0 43 0 0][f 5 21 0 1002]Eres un plasta.[n][w][e]

[msg MSG_033_0_0 [Chica de naranja]]
[f 2 1][vp 1 0 0 44 0 0][f 5 21 0 1002]Hasta más ver, chavales.[n][w][e]

[msg MSG_034_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 102 65535 0 0][vp 1 0 0 45 0 0]Sí, se te da genial "jugar al tenis".[n][w][e]

[msg MSG_035_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 102 65535 0 0][vp 1 0 0 46 0 0]Oye, que lo he intentado.[n][w][e]

[msg MSG_035_5_0 [Junpei Iori]]
[f 2 1][bup 3 0 102 65535 0 0][vp 1 0 0 47 0 0][f 4 23 0 3 0 25 25]¡¿Y tú qué, Sanada?! Enséñanos tú cómo se hace, listo.[n][w][e]

[msg MSG_036_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 4 102 65535 0 0][vp 1 0 0 48 0 0]No tengo por qué enseñarte nada.[n][w][e]

[msg MSG_037_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 102 65535 0 0][vp 1 0 0 49 0 0]Bueno, en teoría esto era una operación, ¿no?[n][w][e]

[msg MSG_037_5_0 [Junpei Iori]]
[f 2 1][bup 3 1 102 65535 0 0][vp 1 0 0 50 0 0]¿Y no hay que trabajar en equipo para tener éxito?[n][w][e]

[msg MSG_038_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 3 102 65535 0 0][vp 0 0 0 51 0 0][f 4 25 4]...[n][w][e]
[f 2 1][bup 4 0 102 65535 0 0][vp 1 0 0 52 0 0][f 4 23 0 4 0 25 25]Razón no te falta.[n][w][e]

[msg MSG_039_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 1 102 65535 0 0][vp 1 0 0 53 0 0][f 4 23 0 4 1 25 25]Vale, le daré un tiento. Como poco, pienso hacerlo mejor que tú.[n][w][e]

[msg MSG_040_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 1 102 65535 0 0][vp 1 0 0 54 0 0]¿Me echas un cable, [nl]? Descuida, que yo marco el ritmo.[n][w][e]

