[msg MND_000_0_0]
[f 2 1]Es el baño de chicas.[n][w][e]

[sel SEL_001_0_0 top]
[f 2 1]Entrar[e]
[f 2 1]No entrar[e]

[msg MND_002_0_0]
[f 2 1]Siento que mi mente comienza a divagar mientras me lavo las manos.[n][w][e]

[msg MND_003_0_0]
[f 2 1]Hay alguien atrapado en la torre Tártaro...[n][w][e]
[f 2 1]Tengo que darme prisa para rescatar a esa persona.[n][w][e]

[msg MND_004_0_0]
[f 2 1]Junpei me ha preguntado si podíamos quedar hoy.[n][w][e]
[f 2 1]Debería ir a verlo después.[n][w][e]

[msg MND_005_0_0]
[f 2 1]Sanada me ha preguntado si podíamos quedar hoy.[n][w][e]
[f 2 1]Debería ir a verlo después.[n][w][e]

[msg MND_006_0_0]
[f 2 1]Amada me ha preguntado si podíamos quedar hoy.[n][w][e]
[f 2 1]Debería ir a verlo después.[n][w][e]

[msg MND_007_0_0]
[f 2 1]Aragaki me ha preguntado si podíamos quedar hoy.[n][w][e]
[f 2 1]Debería ir a verlo después.[n][w][e]

[msg MND_008_0_0]
[f 2 1]Ahora que lo pienso, Koromaru suele estar fuera de la residencia.[n][w][e]
[f 2 1]Debería ir a verlo después.[n][w][e]

[msg MND_009_0_0]
[f 2 1]La chica del parque quería comer algo redondo y calentito.[n][w][e]
[f 2 1]Debería comprárselo después.[n][w][e]

[msg MND_010_0_0]
[f 2 1]La chica del parque quería algo para beber.[n][w][e]
[f 2 1]Debería llevarle una bebida con gas, energética y amarga.[n][w][e]

[msg MND_011_0_0]
[f 2 1]Ahora que lo pienso, el chico del santuario estaba buscando una pluma estilográfica.[n][w][e]
[f 2 1]Quizá pueda ayudarle a encontrarla.[n][w][e]

[msg MND_012_0_0]
[f 2 1]He encontrado la pluma estilográfica que buscaba el chico del santuario.[n][w][e]
[f 2 1]Debería devolvérsela.[n][w][e]

[msg MND_013_0_0]
[f 2 1]El Rey gourmet me ha pedido que le lleve algo que jamás haya comido.[n][w][e]
[f 2 1]¿Debería hacer caso a su petición?[n][w][e]

[msg MND_014_0_0]
[f 2 1]Tengo que cosechar los cultivos de las macetas de la azotea.[n][w][e]

[msg MND_015_0_0]
[f 2 1]Creo que ahora mismo no hay nada a lo que deba prestarle atención.[n][w][e]

[msg MND_016_0_0]
[f 2 1]Es verdad... Le di dinero a ese hombre trajeado del centro comercial Paulownia.[n][w][e]
[f 2 1]A saber qué ha sido de ese dinero.[n][w][e]

[msg MND_017_0_0]
[f 2 1]He plantado [f 4 4 1 37 1 0].[n][w][e]
[f 2 1]Se podrá cosechar a partir del [clr 2][f 2 4 2]/[f 2 4 1][clr 27].[n][w][e]

[msg MND_018_0_0]
[f 2 1]Mitsuru me ha preguntado si podíamos quedar hoy.[n][w][e]

[msg MND_019_0_0]
[f 2 1]Ahora que lo pienso, Mitsuru me pidió que entregara el formulario de readmisión escolar.[n][w][e]

[msg MND_020_0_0]
[f 2 1]Todavía no me he acostumbrado a luchar... Igual deberíamos ir a la torre Tártaro esta noche.[n][w][e]

[msg MND_021_0_0]
[f 2 1]¿Nuestro trabajo en equipo habrá mejorado? Igual deberíamos ir a la torre Tártaro esta noche.[n][w][e]

[msg MND_022_0_0]
[f 2 1]¿Estaré haciendo un buen uso de la teúrgia? Igual deberíamos ir a la torre Tártaro esta noche.[n][w][e]

[msg MND_023_0_0]
[f 2 1]¿Habré estado usando bien mis Personas? Igual debería ir a la torre Tártaro esta noche.[n][w][e]

[msg MND_024_0_0]
[f 2 1]Como el equipo ha crecido, tengo que pensar en la formación. Igual deberíamos ir a la torre Tártaro.[n][w][e]

[msg MND_025_0_0]
[f 2 1]Los enemigos cada vez son más fuertes. Igual deberíamos ir a la torre Tártaro esta noche.[n][w][e]

[msg MND_026_0_0]
[f 2 1]La siguiente gran sombra será nuestra última misión. Igual deberíamos ir a la torre Tártaro esta noche.[n][w][e]

[msg MND_027_0_0]
[f 2 1]La Hora Oscura aún está presente. Igual deberíamos ir a la torre Tártaro esta noche.[n][w][e]

[msg MND_028_0_0]
[f 2 1]Me pregunto si estoy lista para luchar... Igual deberíamos ir a la torre Tártaro esta noche.[n][w][e]

[msg MND_029_0_0]
[f 2 1]Hoy tengo el día libre. ¿Qué hago después de esto?[n][w][e]

[msg MND_030_0_0]
[f 2 1]No falta nada para las vacaciones. ¿Qué debería hacer con mi tiempo?[n][w][e]

[msg MND_031_0_0]
[f 2 1]Ya tenemos encima los parciales del primer trimestre. Debería estudiar ahora que todavía tengo tiempo.[n][w][e]

[msg MND_032_0_0]
[f 2 1]Ya tenemos encima los finales del primer trimestre. Debería estudiar ahora que todavía tengo tiempo.[n][w][e]

[msg MND_033_0_0]
[f 2 1]Ya tenemos encima los parciales del segundo trimestre. Debería estudiar ahora que todavía tengo tiempo.[n][w][e]

[msg MND_034_0_0]
[f 2 1]Ya tenemos encima los finales del segundo trimestre. Debería estudiar ahora que todavía tengo tiempo.[n][w][e]

[msg MND_035_0_0]
[f 2 1]Ya falta poco para la luna llena. ¿Aparecerá otra gran sombra?[n][w][e]

[msg MND_036_0_0]
[f 2 1]Ya falta poco para la luna llena. ¿Tendremos que lidiar con más problemas?[n][w][e]

[msg MND_037_0_0]
[f 2 1]Ya falta poco para la luna llena. ¿A qué clase de enemigo nos enfrentaremos?[n][w][e]

[msg MND_038_0_0]
[f 2 1]Ya falta poco para la luna llena. No nos quedan muchos enemigos...[n][w][e]

[msg MND_039_0_0]
[f 2 1]Ya falta poco para la luna llena. Por fin acabaremos con todo esto.[n][w][e]

[msg MND_040_0_0]
[f 2 1]El viaje a Yakushima es dentro de nada. A saber qué nos depara...[n][w][e]

[msg MND_041_0_0]
[f 2 1]Pronto tendremos la excursión. ¿Qué debería visitar en Kioto?[n][w][e]

[msg MND_042_0_0]
[f 2 1]Nochevieja está a la vuelta de la esquina. Va siendo hora de tomar una decisión.[n][w][e]

[msg MND_043_0_0]
[f 2 1]El [clr 2]día de la promesa[clr 27] es inminente. Más vale que haga lo que pueda ahora si no quiero arrepentirme.[n][w][e]

[msg MND_045_0_0]
[f 2 1]Ahora que soy parte del programa de clientes de Umiushi, puedo pedir comida para llevar.[n][w][e]
[f 2 1]Debería probar en algún momento.[n][w][e]

[msg MND_046_0_0]
[f 2 1]Puedes comprar bebidas en la máquina expendedora de la estación de Iwatodai aunque ponga que están agotadas.[n][w][e]
[f 2 1]Debería intentar comprar una la próxima vez.[n][w][e]

[msg MND_047_0_0]
[f 2 1]Parece que el equipo de atletismo busca nuevos miembros.[n][w][e]
[f 2 1]Debería pasarme por allí algún día.[n][w][e]

[msg MND_048_0_0]
[f 2 1]La librería de segunda mano de la zona de tiendas de Iwatodai ha vuelto a abrir.[n][w][e]
[f 2 1]¿Qué clase de libros tendrán?[n][w][e]

[msg MND_049_0_0]
[f 2 1]La teletienda se emite los domingos.[n][w][e]
[f 2 1]Podría echarle un ojo en la tele de mi habitación.[n][w][e]

[msg MND_050_0_0]
[f 2 1]Hay una niña de primaria jugando sola en el santuario Naganaki.[n][w][e]
[f 2 1]¿Le pasará algo?[n][w][e]

[msg MND_051_0_0]
[f 2 1]Parece que hay una plaza en el club de arte.[n][w][e]
[f 2 1]Debería pasarme por allí algún día.[n][w][e]

[msg MND_052_0_0]
[f 2 1]Pronto habrá un festival de cine en el Screen Shot.[n][w][e]
[f 2 1]Igual debería invitar a alguien a acompañarme.[n][w][e]

[msg MND_053_0_0]
[f 2 1]El festival cultural es dentro de nada, pero se avecina un tifón.[n][w][e]
[f 2 1]A este paso, no sé yo si acabarán cancelándolo...[n][w][e]

[msg MND_054_0_0]
[f 2 1]Parece que van a celebrar un festival de cine de un día en el Screen Shot el 23 de septiembre.[n][w][e]
[f 2 1]Igual debería invitar a alguien a acompañarme.[n][w][e]

[msg MND_055_0_0]
[f 2 1]Las jornadas de experiencia profesional empiezan el 24 de noviembre... A saber qué haré esos días.[n][w][e]

[msg MND_056_0_0]
[f 2 1]Ah, sí... Tengo un taiyaki en la nevera. Debería comérmelo pronto.[n][w][e]

[msg MND_057_0_0]
[f 2 1]Cada vez que veo los cerezos en flor, siento que por fin ha llegado la primavera.[n][w][e]

[msg MND_058_0_0]
[f 2 1]A partir de hoy, podemos explorar la torre Tártaro en condiciones.[n][w][e]

[msg MND_059_0_0]
[f 2 1]Esta es la temporada en la que hay bichos por todas partes.[n][w][e]

[msg MND_060_0_0]
[f 2 1]Cada vez hace más calor y humedad. Se acerca el verano...[n][w][e]

[msg MND_061_0_0]
[f 2 1]Hace tanto calor que no paro de sudar, aunque esté sentada en el baño.[n][w][e]

[msg MND_062_0_0]
[f 2 1]Ya estamos en septiembre, pero el calor del verano aún no se va.[n][w][e]

[msg MND_063_0_0]
[f 2 1]Ya hace un poco más de fresco y los días son más agradables.[n][w][e]

[msg MND_064_0_0]
[f 2 1]Como ya estamos en otoño, ¿cambiará pronto el color de las hojas?[n][w][e]

[msg MND_065_0_0]
[f 2 1]Últimamente, hace mucho más frío. Por fin llega el invierno...[n][w][e]

[msg MND_066_0_0]
[f 2 1]Mañana es Nochebuena... ¿Qué debería hacer?[n][w][e]

[msg MND_067_0_0]
[f 2 1]Es Navidad...[n][w][e]
[f 2 1]Me pregunto si la gente de todo el mundo se lo estará pasando bien...[n][w][e]

[msg MND_068_0_0]
[f 2 1]Tengo más energía al comienzo de un nuevo año.[n][w][e]

[msg MND_069_0_0]
[f 2 1]Últimamente, hace un frío que pela. Lo único que me apetece es estar bajo el brasero.[n][w][e]

[msg MND_070_0_0]
[f 2 1]Qué cansada estoy...[n][w][e]
[f 2 1]Se me cierran los ojos...[n][w][e]

[msg MND_071_0_0]
[f 2 1]...[n][w][e]
[f 2 1]Hoy solo he ido al instituto, pero no puedo con mi vida.[n][w][e]
[f 2 1]Se me cierran los ojos...[n][w][e]
[f 2 1]Mañana es la ceremonia de graduación de los de último año.[n][w][e]
[f 2 1]Debería acostarme pronto.[n][w][e]

[msg MND_072_0_0]
[f 2 1]Ah, sí... Tengo lo que me pidió la cría del parque.[n][w][e]
[f 2 1]Debería ir a verla después.[n][w][e]

[msg MND_073_0_0]
[f 2 1]Hayase me ha invitado a comer con él.[n][w][e]
[f 2 1]Debería ir a la zona de tiendas después.[n][w][e]

[msg MND_074_0_0]
[f 2 1]Qué frío tengo... Igual he pillado un catarro o algo.[n][w][e]

[msg MND_075_0_0]
[f 2 1]Hoy es el día de la promesa. Cuando llegue la Hora Oscura, no habrá vuelta atrás.[n][w][e]
[f 2 1]Debería hacer lo que toca ahora que todavía tengo tiempo.[n][w][e]

[msg MND_076_0_0]
[f 2 1]Ah, sí... Aragaki me pidió que entregase su formulario de ausencia.[n][w][e]

[msg MND_077_0_0]
[f 2 1]Ahora que lo pienso, me pidieron que ordenara las pertenencias de Aragaki de su habitación.[n][w][e]

[msg MND_078_0_0]
[f 2 1]Ahora que lo pienso, debería ver qué tal está Amada.[n][w][e]

[msg MND_079_0_0]
[f 2 1]Hay un [clr 2]caqui[clr 27] en alguna parte del Instituto Gekkoukan.[n][w][e]
[f 2 1]Debería ir a echarle un ojo.[n][w][e]

[msg MND_080_0_0]
[f 2 1]Tengo el [f 4 4 1 37 1 0] que he recogido en el sendero.[n][w][e]
[f 2 1]Debería enseñárselo a la pareja de ancianos de la librería.[n][w][e]

[msg MND_081_0_0]
[f 2 1]Koromaru debería estar frente a la entrada de la residencia a estas horas.[n][w][e]
[f 2 1]Debería ir a verlo después.[n][w][e]

