[msg MSG_000_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 4 1 0 0]Ah, [nl]. ¿Te vas a casa?[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 4 2 0 0]Estás un poco pálida... ¿Estás bien?[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 4 3 0 0]No te sobreesfuerces, ¿vale? Tal vez deberías descansar en la enfermería antes de irte.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 4 4 0 0]Estaba a punto de ir a la sala de profesores. ¿Quieres que baje contigo?[n][w][e]

[msg MSG_001_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 1 0][vp 1 0 4 5 0 0]Quiero pasar todo el tiempo que pueda contigo...[n][w][e]

[sel SEL_002_0_0 top]
[f 2 1]Vamos allá.[e]
[f 2 1]Hoy estoy algo liada.[e]

[msg MSG_003_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 4 6 0 0]Me encantaría.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 4 7 0 0]Vale, bajemos juntas a la sala de profesores.[n][w][e]
[f 2 1][bup 6 0 65535 65535 1 0][vp 1 0 4 8 0 0]Ah...[n][w][e]
[f 2 1][bup 6 1 65535 65535 1 0][vp 1 0 4 9 0 0]Va a ser un poco embarazoso caminar juntas por el instituto, ¿no?[n][w][e]

[msg MSG_004_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 4 10 0 0]Ah... Bueno, ten cuidado de camino a casa, ¿vale?[n][w][e]

[sel SEL_005_0_0 top]
[f 2 1]Vamos allá.[e]
[f 2 1]Hoy estoy algo liada.[e]

[msg MSG_006_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 4 11 0 0]Me parece bien. La gente se suele poner mala con los cambios de estación, así que igual te estás poniendo pachucha.[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 4 12 0 0]Vale, vayamos juntas a la sala de profesores.[n][w][e]

[msg MSG_007_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 4 13 0 0]¿Ya tienes planes? Bueno, vete pronto a casa y descansa.[n][w][e]

