[msg MSG_000_0_0 [Señor misterioso]]
[f 2 1][bup 201 0 65535 65535 0 0][vp 1 0 0 1 0 0]Te doy la bienvenida a la Habitación Terciopelo.[n][w][e]

[msg MSG_001_0_0 [Señor misterioso]]
[f 2 1][bup 201 0 65535 65535 0 0][vp 1 0 0 2 0 0]Me llamo Igor. Es un placer conocerte.[n][w][e]

[msg MSG_002_0_0 [Igor]]
[f 2 1][bup 201 0 65535 65535 0 0][vp 1 0 0 3 0 0]Esta es Elizabeth. Reside aquí, como yo.[n][w][e]

[msg MSG_003_0_0 [Elizabeth]]
[f 2 1][bup 202 0 65535 65535 0 0][vp 1 0 0 4 0 0]Encantada de conocerte.[n][w][e]

[msg MSG_004_0_0 [Igor]]
[f 2 1][bup 201 0 65535 65535 0 0][vp 1 0 0 5 0 0]Este lugar existe entre el mundo onírico y la realidad, la mente y la materia...[n][w][e]
[f 2 1][bup 201 0 65535 65535 0 0][vp 1 0 0 6 0 0]Solo quienes hayan firmado el contrato pueden entrar en este lugar.[n][w][e]

[msg MND_005_0_0]
[f 2 1]Ese es el documento que firmé en la residencia...[n][w][e]

[msg MSG_006_0_0 [Igor]]
[f 2 1][bup 201 0 65535 65535 0 0][vp 1 0 0 7 0 0]Por lo tanto, te damos la bienvenida como huésped de la Habitación Terciopelo.[n][w][e]
[f 2 1][bup 201 0 65535 65535 0 0][vp 1 0 0 8 0 0]Tu destino es pulir esa habilidad única que posees, y para ello requerirás mi ayuda.[n][w][e]
[f 2 1][bup 201 0 65535 65535 0 0][vp 1 0 0 9 0 0]Solo pido una cosa a cambio.[n][w][e]
[f 2 1][bup 201 0 65535 65535 0 0][vp 1 0 0 10 0 0]Que cumplas el contrato y asumas toda responsabilidad de las decisiones que tomes.[n][w][e]

[sel SEL_007_0_0 top]
[f 2 1]De acuerdo.[e]
[f 2 1]No lo entiendo.[e]
[f 2 1]¿Estoy soñando?[e]

[msg MSG_008_0_0 [Igor]]
[f 2 1][bup 201 0 65535 65535 0 0][vp 1 0 0 11 0 0]De momento, no es necesario.[n][w][e]

[msg MSG_009_0_0 [Igor]]
[f 2 1][bup 201 0 65535 65535 0 0][vp 1 0 0 12 0 0]En efecto... Tu yo de la realidad está dormida mientras hablamos.[n][w][e]
[f 2 1][bup 201 0 65535 65535 0 0][vp 1 0 0 13 0 0]Esta visita es solo un sueño.[n][w][e]
[f 2 1][bup 201 0 65535 65535 0 0][vp 1 0 0 14 0 0]No obstante, tarde o temprano, vendrás por voluntad propia.[n][w][e]

[msg MSG_010_0_0 [Igor]]
[f 2 1][bup 201 0 65535 65535 0 0][vp 1 0 0 15 0 0]Quédate con esto.[n][w][e]

[msg MND_011_0_0 [Señor misterioso]]

[msg MSG_012_0_0 [Igor]]
[f 2 1][bup 201 0 65535 65535 0 0][vp 1 0 0 16 0 0]Hasta la próxima.[n][w][e]

