[msg MSG_000_0_0 [Alumna empollona]]
[f 2 1][f 5 21 1 310]Ah, debes de ser quien acaba de llegar. Te daré un consejo...[n][w][e]
[f 2 1][f 5 21 1 310]No olvides estudiar mucho para los exámenes, ya que habrá preguntas peliagudas.[n][w][e]

[msg MSG_001_0_0 [Alumna empollona]]
[f 2 1][f 5 21 1 310]Si solo empollas en casa, ¿no te parece que no estás estudiando suficiente?[n][w][e]
[f 2 1][f 5 21 1 310]Si te ocurre, te recomiendo ir a la biblioteca.[n][w][e]
[f 2 1][f 5 21 1 310]Puedes usar los libros que hay y concentrarte para estudiar en silencio. Además, ¡es gratis![n][w][e]

[msg MSG_002_0_0 [Alumna empollona]]
[f 2 1][f 5 21 1 310]Solo el tiempo lo dirá...[n][w][e]
[f 2 1][f 5 21 1 310]No voy a preocuparme por mi nota.[n][w][e]

[msg MSG_003_0_0 [Alumna empollona]]
[f 2 1][f 5 21 1 310]No estoy ni contenta ni decepcionada con mi nota, ya que está en la media.[n][w][e]
[f 2 1][f 5 21 1 310]¿Qué tal tú, chica nueva?[n][w][e]

[msg MSG_004_0_0 [Alumna empollona]]
[f 2 1][f 5 21 1 310]¿Has oído lo de las dos personas que encontraron inconscientes?[n][w][e]
[f 2 1][f 5 21 1 310]Seguro que muchos dejan de ponerles los cuernos a sus parejas de ahora en adelante.[n][w][e]
[f 2 1][f 5 21 1 310]Después de todo, uno era un hombre y la otra, una mujer.[n][w][e]
[f 2 1][f 5 21 1 310]Unas circunstancias la mar de incriminatorias, en mi opinión.[n][w][e]

[msg MSG_005_0_0 [Alumna empollona]]
[f 2 1][f 5 21 1 310]Los exámenes finales son mucho más difíciles que los parciales, ¿sabes?[n][w][e]
[f 2 1][f 5 21 1 310]Pero eso no quiere decir que vaya a estudiar más.[n][w][e]
[f 2 1][f 5 21 1 310]Ya veremos. A veces un esfuerzo extra merece la pena.[n][w][e]

[msg MSG_006_0_0 [Alumna empollona]]
[f 2 1][f 5 21 1 310]Parece que la nota media ha bajado esta vez... Supongo que no es algo malo.[n][w][e]
[f 2 1][f 5 21 1 310]Pero, si te digo la verdad, me decepciona un poco, ya que yo podría haber sacado como 20 puntos más.[n][w][e]
[f 2 1][f 5 21 1 310]Tendré que estudiar más durante las vacaciones.[n][w][e]

[msg MSG_007_0_0 [Alumna empollona]]
[f 2 1][f 5 21 1 310]El primer trimestre no es más que el calentamiento. El juego empieza de verdad en el segundo.[n][w][e]
[f 2 1][f 5 21 1 310]Será mejor que uses la biblioteca o estudies mucho en casa.[n][w][e]

[msg MSG_008_0_0 [Alumna empollona]]
[f 2 1][f 5 21 1 310]Esta vez sé que lo hice bastante bien. Estoy impaciente por ver los resultados.[n][w][e]

[msg MSG_009_0_0 [Alumna empollona]]
[f 2 1][f 5 21 1 310]Estoy feliz con mi nota. Estudiar tanto durante el verano ha dado sus frutos.[n][w][e]

[msg MSG_010_0_0 [Alumna empollona]]
[f 2 1][f 5 21 1 310]Este examen no es más que otra pequeña montaña en mi camino...[n][w][e]
[f 2 1][f 5 21 1 310]El desafío de verdad son los exámenes de acceso a la universidad... Lo demás no es más que práctica.[n][w][e]
[f 2 1][f 5 21 1 310]Seguro que para esos estudiaremos más de lo que jamás hemos imaginado.[n][w][e]

[msg MSG_011_0_0 [Alumna empollona]]
[f 2 1][f 5 21 1 310]Qué examen más difícil. No sé muy bien cómo me ha ido.[n][w][e]
[f 2 1][f 5 21 1 310]Supongo que tendré que esperar a que publiquen las notas.[n][w][e]

[msg MSG_012_0_0 [Alumna empollona]]
[f 2 1][f 5 21 1 310]La verdad es que se me dio bastante bien.[n][w][e]
[f 2 1][f 5 21 1 310]Ahora no tengo que estar depre durante las vacaciones.[n][w][e]
[f 2 1][f 5 21 1 310]¿Y tú qué? Oye, tienes la cara algo pálida...[n][w][e]
[f 2 1][f 5 21 1 310]B-bueno, no es el fin del mundo. Además, tienes otra oportunidad.[n][w][e]
[f 2 1][f 5 21 1 310]Así que anímate...[n][w][e]

