[msg MSG_000_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 3 0 65535 14201 0 0]Todavía no sabemos cómo entraron las sombras a este mundo.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0]Antes era investigador de Kirijo Electronics.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0]Esa es la razón por la que soy el director del consejo escolar de tu instituto.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0]Y también por la que la residencia resulta apropiada para llevar a cabo las actividades de SEES.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0][vp 3 0 65535 14223 0 0]Ah, y también deberías saber que no puedo invocar Personas.[n][w][e]
[f 2 1][bup 222 1 65535 65535 0 0]Sin embargo, para realizar mis investigaciones, me esforcé mucho para entrar en la Hora Oscura.[n][w][e]
[f 2 1][bup 222 1 65535 65535 0 0]No dudes en pedirme ayuda cuando lo necesites. Aunque claro, no podré hacer mucho al respecto. Ja, ja, ja...[n][w][e]

[msg MSG_001_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 3 0 65535 14202 0 0]Tu primera noche en la torre Tártaro ha ido muy bien.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0]Dime, ¿qué te ha parecido?[n][w][e]

[sel SEL_002_0_0 top]
[f 2 1]Ha sido agotador.[e]
[f 2 1]Ha sido escalofriante.[e]
[f 2 1]Ha sido pan comido.[e]

[msg MSG_003_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 3 0 65535 14211 0 0]Era de esperar. Es difícil evitar la fatiga durante la Hora Oscura.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0]Tener que luchar contra las sombras mientras exploras lo hace aún más agotador.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0]Pero, con el tiempo, no tengo duda de que irás adaptándote a su inclemencia.[n][w][e]

[msg MSG_004_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 3 0 65535 14210 0 0]Sí, coincido.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0]Suele ser la primera impresión que uno tiene al entrar en esa misteriosa torre.[n][w][e]

[msg MSG_005_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 4 65535 65535 0 0][vp 3 0 65535 14229 0 0]¡Eso es extraordinario! ¿No te gustaría ocupar mi puesto algún día?[n][w][e]

[msg MSG_005_5_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 3 0 65535 14210 0 0]Sea como sea, vamos a necesitar tu ayuda para investigar la torre.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0]Cuento contigo.[n][w][e]

[msg MSG_006_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 3 0 65535 14201 0 0]¿Cómo va la exploración de la torre Tártaro?[n][w][e]

[sel SEL_007_0_0 top]
[f 2 1]Muy bien.[e]
[f 2 1]No muy allá...[e]

[msg MSG_008_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 3 0 65535 14229 0 0]Fenomenal. A seguir así.[n][w][e]

[msg MSG_009_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 3 0 65535 14210 0 0]Bueno, no le des muchas vueltas. Tú intenta mejorar tus capacidades poco a poco.[n][w][e]

[msg MSG_009_5_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 3 0 65535 14224 0 0]Mantened un ritmo constante y no os forcéis más de lo necesario. Tomaos vuestro tiempo y avanzad con cautela.[n][w][e]

[msg MSG_010_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 3 0 65535 14222 0 0]¿Sabes a qué se dedica un director?[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0]Estoy tan ocupado que no tengo tiempo para mi investigación.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0]Por eso voy a dedicar todo este fin de semana a analizar datos.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0]Trabajaré de sol a sol como un robot... ¡A ver si me aprietan las tuercas! ¡Ja, ja, ja![n][w][e]

[msg MSG_011_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 3 0 65535 14201 0 0]¡Qué misión tan difícil! No me puedo creer lo que os ha ocurrido.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0]Menos mal que nadie ha salido herido...[n][w][e]
[f 2 1][bup 222 1 65535 65535 0 0]A todo esto, parece que se ha difundido el incidente de anoche con el monorraíl.[n][w][e]
[f 2 1][bup 222 1 65535 65535 0 0]Dicen que ha sido un fallo de los frenos. Pues menuda avería más grave, ¿no crees? Ja, ja...[n][w][e]

[msg MSG_012_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 3 0 65535 14222 0 0]Ah, es verdad. Mañana empiezan los parciales.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0]Ah, qué tiempos aquellos en los que me pasaba las noches empollando.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0]Dos exámenes más y me iban a empezar a salir plumas. ¿Lo pillas? Ja, ja...[n][w][e]

[msg MSG_012_1_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 1 65535 65535 0 0][vp 3 0 65535 14227 0 0]Me alegra mucho que hayas acordado encargarte de las plantas.[n][w][e]
[f 2 1][bup 222 1 65535 65535 0 0]Si te soy sincero, subir las escaleras para ir a la azotea es duro para un viejales como yo...[n][w][e]

[msg MSG_013_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 3 0 65535 14202 0 0]A mí también me ha decepcionado lo de Yamagishi.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0]Es muy difícil encontrar a gente con potencial.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0]¿No confiarías más en tus habilidades si hubiera más miembros en el grupo?[n][w][e]

[sel SEL_014_0_0 top]
[f 2 1]Cierto.[e]
[f 2 1]Nos irá bien solos.[e]

[msg MSG_015_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 3 0 65535 14211 0 0]Por suerte, Sanada ha regresado al equipo.[n][w][e]

[msg MSG_016_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 3 0 65535 14213 0 0]Pero, si alguien enferma, la fuerza del equipo se verá muy afectada.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0]Depender de tan pocos miembros nos pone en una situación muy precaria.[n][w][e]

[msg MSG_017_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 3 0 65535 14229 0 0]Mmm... Parece que Takeba tiene un sexto sentido para las sombras.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0]De hecho, es bastante frecuente.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0]Luchar contra sombras suele mejorar... otros sentidos.[n][w][e]

[msg MSG_018_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 3 0 65535 14233 0 0]Mmm... Esto no me gusta.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0]Tanto padres como periodistas están haciendo muchas preguntas...[n][w][e]

[msg MSG_019_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 3 0 65535 14223 0 0]Kirijo y Sanada han ido a llevar a Yamagishi a casa. Es tarde.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0]Pero hoy ha sido un gran día para todos.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0]Hemos conseguido nuevos poderes y hemos aprendido más sobre las sombras... Entramos en la nueva fase de la batalla.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0]Pero no podemos cruzarnos de brazos. Diría que podemos usar un nuevo as bajo la manga...[n][w][e]

[msg MSG_020_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 3 0 65535 14222 0 0]Yamagishi es sorprendentemente buena con la tecnología. Y muy amable, siempre está pendiente de los sentimientos del resto.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0]Su nombre le pega a la perfección. "Fuu" significa viento, y "ka", flor.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0]Es como una flor que sopla suavemente con el...[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0]Me estoy yendo por las ramas.[n][w][e]

[msg MSG_021_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 3 0 65535 14221 0 0]La cuestión es: ¿las sombras actúan de forma independiente? ¿O trabajan en equipo para lograr un objetivo?[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0]En esencia, un grupo de sombras toma a un humano como objetivo y destruye su mente con un propósito...[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0]¿Acaso está cada sombra devorando individualmente las mentes humanas para poder sobrevivir?[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0]Eso es lo que debemos discernir.[n][w][e]

[msg MSG_022_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 3 0 65535 14205 0 0]Como las cosas han estado tan tensas, había pensado en animar el ambiente.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0]Así que hoy voy a contaros a todos mis mejores diez chistes.[n][w][e]

[msg MSG_023_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 3 0 65535 14201 0 0]Si no me equivoco, la próxima sombra aparecerá pronto...[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0]Habrá luna llena el día 7. Me temo que la Hora Oscura de esa noche será muy agitada.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0]La siguiente operación es crucial para mi investigación.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0]Asegúrate de estar lista para la próxima luna llena.[n][w][e]

[msg MSG_024_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 3 0 65535 14201 0 0]Mañana pondremos a prueba mi hipótesis...[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0]Una sombra aparecerá durante la luna llena.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0]Como investigador que soy, me llena de emoción.[n][w][e]

[msg MSG_025_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 3 0 65535 14231 0 0]Lamento mucho todo. Si puedo ser de ayuda, avísame.[n][w][e]

[msg MSG_025_5_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 3 0 65535 14210 0 0]Si hay algo que quieras saber, no dudes en preguntar.[n][w][e]

[sel SEL_026_0_0 top]
[f 2 1]¿Qué son las doce sombras?[e]
[f 2 1]¿Cómo se lo tomó la gente?[e]
[f 2 1]¿Qué pasó con Mitsuru?[e]
[f 2 1]Háblame de Sanada.[e]

[msg MSG_027_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0]Las sombras especiales aparecen las noches de luna llena. Son consecuencia de un accidente que se produjo hace diez años.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0]En el incidente, una entidad experimental formada por varias sombras se dividió en doce partes de gran tamaño.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0]Por lo tanto, su poder supera con creces a las de la torre Tártaro. Proceded con sumo cuidado.[n][w][e]

[msg MSG_028_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0]Al final, más de 50 personas resultaron heridas en ese accidente.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0]Los medios culparon al Grupo Kirijo de la tragedia.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0]Señalaron a un investigador en concreto y lo declararon el principal culpable de todo lo ocurrido.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0]La cuestión no es si fue todo culpa suya o no...[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0]La ciudadanía buscaba a alguien sobre quien descargar su ira.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0]Por eso lo escogieron a él, a pesar de que era una víctima más.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0]Su ira no tuvo igual. Fue más terrorífico que ver una horda de sombras...[n][w][e]

[msg MSG_029_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0]Bajo el pretexto de que estaba ayudando al Grupo Kirijo, fue expuesta a experimentos en su Persona durante muchos años.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0]Descubrir el misterio oculto detrás de la habilidad de las Personas, el desarrollo del equipamiento, empezando por el Evocador...[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0]Nada de esto habría sido posible sin su cooperación.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0]Seguro que algunos de los experimentos eran bastante peligrosos, pero, aun así, estuvo de acuerdo con todo, por lo que sé...[n][w][e]

[msg MSG_030_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0]Kirijo y él se conocen desde hace mucho tiempo.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0]Sanada se unió a nosotros cuando aún estaba en secundaria.[n][w][e]
[f 2 1][bup 222 1 65535 65535 0 0]En aquel entonces, había un tercer miembro.[n][w][e]
[f 2 1][bup 222 1 65535 65535 0 0]En fin..., me estoy desviando del tema.[n][w][e]

[msg MSG_031_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 1 65535 65535 0 0][vp 3 0 65535 14201 0 0]Bueno, eso es todo sobre Yakushima.[n][w][e]
[f 2 1][bup 222 1 65535 65535 0 0]Ahora os toca concentraros en los exámenes finales.[n][w][e]

[msg MSG_032_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 1 65535 65535 0 0][vp 3 0 65535 14223 0 0]Quizá visite Miyoido yo mismo cuando tenga tiempo libre.[n][w][e]
[f 2 1][bup 222 1 65535 65535 0 0]Me gustaría pedir un par de cosas...[n][w][e]
[f 2 1][bup 222 1 65535 65535 0 0]Pero, sobre todo, me gustaría pasar el tiempo mirando las antigüedades y aprendiendo sobre la historia que hay detrás de cada pieza.[n][w][e]

[msg MSG_033_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 3 0 65535 14203 0 0]¿Hay algo que quieras saber sobre Aigis?[n][w][e]

[sel SEL_034_0_0 top]
[f 2 1]¿Dónde están las demás?[e]
[f 2 1]¿Por qué es tan... humana?[e]
[f 2 1]¿Cómo es que me conoce?[e]
[f 2 1]No, la verdad...[e]

[msg MSG_035_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0]Supongo que te refieres al resto de armas antisombras...[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0][vp 3 0 65535 14210 0 0]Se crearon muchas. Se podría decir que eran las hermanas de Aigis.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0]Pero todas fueron destruidas hace diez años en el incidente.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0]Aigis se ha sentido bastante sola desde entonces.[n][w][e]

[msg MSG_036_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0]Una Persona es un producto de la psique humana.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0]La idea era colocar una mente humana en el interior de un arma antisombras.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0]El único problema era la forma que tomaría el arma.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0]Si hubiéramos usado un tanque, por ejemplo, su mente se reconocería a sí misma como tal.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0]Y surgiría una contradicción, puesto que todos sabemos que un tanque no es una entidad viva.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0]La mente de un ser humano que intentara asimilar su existencia de esta manera colapsaría en un santiamén.[n][w][e]
[f 2 1][bup 222 1 65535 65535 0 0]Entonces, ¿cómo evitamos esa contradicción? Ya entiendes a dónde quiero llegar, ¿verdad?[n][w][e]
[f 2 1][bup 222 1 65535 65535 0 0][vp 3 0 65535 14210 0 0]Cuando recibe un cuerpo que se asemeja más a lo que la mente espera, el espíritu se estabiliza.[n][w][e]
[f 2 1][bup 222 1 65535 65535 0 0]Por eso Aigis y sus hermanas fueron creadas con formas humanas.[n][w][e]

[msg MSG_037_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 3 0 65535 14221 0 0]No sabría decirte.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0]A lo mejor es un fallo en su programa de reconocimiento facial...[n][w][e]
[f 2 1][bup 222 1 65535 65535 0 0]No es nada por lo que tengas que preocuparte. No le estarás dando demasiadas vueltas, ¿verdad?[n][w][e]

[msg MSG_038_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 4 65535 65535 0 0][vp 3 0 65535 14223 0 0]He oído que hay un perro que puede usar una Persona.[n][w][e]
[f 2 1][bup 222 4 65535 65535 0 0]Llevaba bastante tiempo investigando esa posibilidad, pero cuesta creer que pueda darse el caso.[n][w][e]
[f 2 1][bup 222 4 65535 65535 0 0]Santo cielo, es increíble. ¿Un perro usando una Persona? ¡Un perro! Solo puedo decir...[n][w][e]

[sel SEL_039_0_0 top]
[f 2 1]Guau.[e]
[f 2 1]Pero ¿cómo puede un perro...?[e]

[msg MSG_040_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 1 65535 65535 0 0][vp 3 0 65535 14228 0 0]¡Ahí va, me has leído la mente![n][w][e]
[f 2 1][bup 222 1 65535 65535 0 0]Un digno oponente, pero a este perro viejo no le ganas.[n][w][e]

[msg MSG_041_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 3 0 65535 14224 0 0]Bueno, seguro que no hay de qué preocuparse. Podría incluso ser beneficioso.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0]Se te va a empezar a caer el pelo si te preocupas tanto siendo joven.[n][w][e]

[msg MSG_041_5_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 3 0 65535 14224 0 0]Eso me recuerda que he oído que ese perro vivía con el sacerdote del santuario Naganaki.[n][w][e]
[f 2 1][bup 222 6 65535 65535 0 0]Así que se mantuvo firme para proteger un lugar importante para él... Se me van a saltar las lágrimas y todo.[n][w][e]

[msg MSG_042_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 3 0 65535 14201 0 0]¿Te falta un verano para acostumbrarte a las operaciones?[n][w][e]

[sel SEL_043_0_0 top]
[f 2 1]Estoy bien, gracias.[e]
[f 2 1]Ya vale.[e]

[msg MSG_044_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 1 65535 65535 0 0][vp 3 0 65535 14210 0 0]Buena suerte en la siguiente también. Te estaré animando desde las sombras. Ja, ja, ja.[n][w][e]

[msg MSG_045_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 1 65535 65535 0 0][vp 3 0 65535 14227 0 0]Ja, ja. Muy malo, ¿no?[n][w][e]
[f 2 1][bup 222 1 65535 65535 0 0]Buena suerte en la siguiente también. Te estaré animando desde las sombras. Ja, ja, ja.[n][w][e]

[msg MSG_046_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 3 0 65535 14201 0 0]Los perros son muy dignos de confianza.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0]Hay perros guía, de rescate, antinarcóticos...[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0]Confiemos en Koromaru.[n][w][e]

[msg MSG_047_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 3 0 65535 14203 0 0]Que no me entere de que tus notas van a peor por pasar demasiado tiempo en la torre Tártaro.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0]Es frustrante... No veo la forma de ayudar.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0]Así que hinca los codos y esfuérzate en las clases de verano.[n][w][e]

[msg MSG_048_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 3 0 65535 14212 0 0]Koromaru no es un perro cualquiera, es un miembro clave de SEES.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0]Cuidado con lo que le dais de comer.[n][w][e]

[msg MSG_049_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 4 65535 65535 0 0][vp 3 0 65535 14221 0 0]¿Sí? ¿Qué ocurre?[n][w][e]
[f 2 1][bup 222 4 65535 65535 0 0]Ah, crees que no sé nada de moda porque soy un investigador, ¿verdad?[n][w][e]

[sel SEL_050_0_0 top]
[f 2 1]Verdad.[e]
[f 2 1]Para nada.[e]

[msg MSG_051_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 3 0 65535 14215 0 0]Bueno, pues que sepas que sé tanto de moda como cualquier hijo de vecino.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0]Sin embargo, mi trabajo me obliga a estar siempre encerrado, así que no tengo muchas oportunidades de ponerme guapo.[n][w][e]

[msg MSG_052_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 1 65535 65535 0 0][vp 3 0 65535 14210 0 0]Muy bien. Sabes que no conviene juzgar a nadie basándose en prejuicios.[n][w][e]

[msg MSG_052_5_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 1 65535 65535 0 0][vp 3 0 65535 14210 0 0]Yo también tengo mi propio estilo, ¿eh? Por ejemplo, siempre combino la camisa que me pongo con el color de la chaqueta...[n][w][e]
[f 2 1][bup 222 1 65535 65535 0 0]¡Tienes que dejar a la gente a cuadros! ¿O quizás pegaría mejor a rayas? Je, ¿lo pillas? ¿No...?[n][w][e]

[msg MSG_053_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 3 0 65535 14229 0 0]Amada me ha impresionado mucho.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0]Es muy intrépido para su edad.[n][w][e]
[f 2 1][bup 222 1 65535 65535 0 0]Cuando yo estaba en primaria, era como un gato asustadizo.[n][w][e]
[f 2 1][bup 222 1 65535 65535 0 0]Lloraba y huía hasta cuando se me acercaba una abeja.[n][w][e]

[msg MSG_054_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 3 0 65535 14201 0 0]Confío en la operación de mañana...[n][w][e]
[f 2 1][bup 222 1 65535 65535 0 0]Con Aragaki de vuelta...,[n][w][e]
[f 2 1][bup 222 1 65535 65535 0 0]no me cabe duda de que ganaremos fácilmente.[n][w][e]

[msg MSG_055_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4148 0 0]Gracias, señor director, pero tal confianza solo puede llevar al fracaso.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Aunque es innegable que Aragaki es muy fuerte, lleva sin luchar bastante tiempo.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Todos debemos centrarnos en la misión y lograr una ejecución impecable para ganar.[n][w][e]

[msg MSG_056_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 3 0 65535 14238 0 0]Ains. ¿Por qué siempre eres tan aguafiestas?[n][w][e]

[msg MSG_057_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 3 0 65535 14201 0 0]No me ha sorprendido saber que se encarga del apoyo en Strega.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0]Atraparla nos otorgará una ventaja interesante.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0]Nos acercamos cada vez más al final de nuestra misión.[n][w][e]

[msg MSG_058_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 3 0 65535 14222 0 0]Hemos acabado con nueve sombras...[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0]Lo que significa que solo quedan tres.[n][w][e]
[f 2 1][bup 222 1 65535 65535 0 0]¡Qué maravilla![n][w][e]
[f 2 1][bup 222 1 65535 65535 0 0]Estamos muy cerca del final. Seguid así.[n][w][e]

[msg MSG_059_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 3 0 65535 14224 0 0]¿Te encuentras mejor, [nl]?[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0]Quería preguntártelo antes, pero seguro que no sienta muy bien que todo el mundo te pregunte cómo estás.[n][w][e]

[sel SEL_060_0_0 top]
[f 2 1]Solo un poco.[e]
[f 2 1]No, la verdad...[e]

[msg MSG_061_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 3 0 65535 14211 0 0]Bueno, es comprensible. Cuando alguien cae enfermo, los demás nos preocupamos.[n][w][e]
[f 2 1][bup 222 1 65535 65535 0 0]Seguro que pensabas: "Ay, ¡menudo tos-tón resfriarme ahora!". ¿Lo pillas? ¿No?[n][w][e]

[msg MSG_062_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 3 0 65535 14215 0 0]No hace falta tanta modestia. Al fin y al cabo, cuesta disfrutar de las cosas cuando no te sientes bien.[n][w][e]
[f 2 1][bup 222 1 65535 65535 0 0]Seguro que pensabas: "Ay, ¡menudo tos-tón resfriarme ahora!". ¿Lo pillas? ¿No?[n][w][e]

[msg MSG_063_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 1 65535 65535 0 0][vp 3 0 65535 14210 0 0]Confío plenamente en la próxima operación.[n][w][e]
[f 2 1][bup 222 1 65535 65535 0 0]Estoy seguro de que la victoria será nuestra.[n][w][e]

[msg MSG_064_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 3 0 65535 14202 0 0]Creo que Kirijo ya os ha explicado la tragedia que sufrió la familia de Amada...[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0]Sucedió tras derrotar a una sombra irregular una mañana después de la Hora Oscura.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0]Probablemente, Amada no fue consciente de lo que estaba ocurriendo en ese momento.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0]Amada y Aragaki... Sabía que algo pasaba entre los dos...[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0][vp 3 0 65535 14231 0 0]Pero jamás pensé que fuese a suceder una desgracia tan espantosa...[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0]Oremos por la felicidad de Aragaki en el más allá.[n][w][e]

[msg MSG_065_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 1 65535 65535 0 0][vp 3 0 65535 14206 0 0]Teniendo en cuenta lo mal que lo habéis pasado...[n][w][e]
[f 2 1][bup 222 1 65535 65535 0 0]Habéis hecho un trabajo excelente en los exámenes.[n][w][e]
[f 2 1][bup 222 1 65535 65535 0 0]Deberíais salir a disfrutar este fin de semana.[n][w][e]

[msg MSG_066_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 3 0 65535 14201 0 0]Ahora que habéis acabado los exámenes, centrémonos en la misión.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0]Queda una única sombra. Es la batalla final.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0]El destino de la ciudad está en vuestras manos.[n][w][e]
[f 2 1][bup 222 1 65535 65535 0 0]Confío en vosotros. Buena suerte.[n][w][e]

[msg MSG_067_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 1 65535 65535 0 0][vp 3 0 65535 14210 0 0]La moral del equipo está por las nubes.[n][w][e]
[f 2 1][bup 222 1 65535 65535 0 0]Es estupendo. Tengo ganas de celebrar nuestra victoria.[n][w][e]

[msg MSG_068_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 1 65535 65535 0 0][vp 3 0 65535 14223 0 0]¿Qué queréis pedir para esta última cena, chicos?[n][w][e]
[f 2 1][bup 222 1 65535 65535 0 0]¿Os apetece pizza Celebrazione o alitas de pollo con sabor a victoria?[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0]Ains. Me están ignorando...[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0][vp 3 0 65535 14231 0 0]Bah, estarán concentrados deleitándose con mis desternillantes chistes...[n][w][e]

