[msg MSG_000_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 1 65535 0 0][vp 1 0 0 1 0 0]Antes, la azotea era una zona restringida, pero hemos decidido abrirla hace poco.[n][w][e]
[f 2 1][bup 5 0 1 65535 0 0][vp 1 0 0 2 0 0]El director quería montar un pequeño huerto aquí arriba.[n][w][e]

[msg MSG_001_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 1 65535 0 0][vp 1 0 0 3 0 0]Vaya... No tenía ni idea de que esto estaba aquí. ¿Es para cultivar hortalizas?[n][w][e]
[f 2 1][bup 2 6 1 65535 0 0][vp 1 0 0 4 0 0][f 4 23 0 2 10 25 25]Ay, madre, ya lo estoy oyendo: "¡Comed verdura, guisantillos!".[n][w][e]

[msg MSG_001_5_0 [Junpei Iori]]
[f 2 1][bup 3 6 1 65535 0 0][vp 1 0 0 5 0 0]Tal cuaaal... Y seguro que lo dice con una sonrisilla en la cara.[n][w][e]

[msg MSG_002_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 1 65535 0 0][vp 1 0 0 6 0 0]Me dijeron que eres tú quien lo cuida, [nl].[n][w][e]
[f 2 1][bup 5 1 1 65535 0 0][vp 1 0 0 7 0 0][f 4 23 0 5 1 25 25]Parece que empieza a coger forma. El director hizo bien al encargártelo a ti.[n][w][e]

[msg MSG_003_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 1 65535 0 0][vp 1 0 0 8 0 0]Me dijeron que lo dejaron a tu cargo, [nl].[n][w][e]
[f 2 1][bup 5 0 1 65535 0 0][vp 1 0 0 9 0 0]Sé que es mucho trabajo, pero no estaría mal intentar cultivar algo.[n][w][e]

[msg MSG_004_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 1 65535 0 0][vp 1 0 0 10 0 0]Eh, ¿te las apañas bien tú sola?[n][w][e]

[sel SEL_004_5_0 top]
[f 2 1]No hay problema.[e]
[f 2 1]Me vendría bien una ayudita.[e]
[f 2 1]Ahora tú estás al mando.[e]

[msg MSG_005_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 1 65535 0 0][vp 1 0 0 11 0 0]No me digas. ¿Te gustan estas cosas? La verdad es que parece divertido.[n][w][e]
[f 2 1][bup 3 1 1 65535 0 0][vp 1 0 0 12 0 0]Cuando por fin estemos rastrillando los cultivos, habrá que celebrarlo. ¡Será "impepinable"![n][w][e]

[msg MSG_006_0_0 [Yukari Takeba]]
[f 2 1][bup 2 6 1 65535 0 0][vp 1 0 0 13 0 0]¿Qué tal si usas esa energía para ayudarla con el huerto?[n][w][e]

[msg MSG_007_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 1 65535 0 0][vp 1 0 0 14 0 0]¿Por qué no le echas una mano, Junpei? Tampoco es que tengas nada mejor que hacer.[n][w][e]

[msg MSG_008_0_0 [Junpei Iori]]
[f 2 1][bup 3 6 1 65535 0 0][vp 1 0 0 15 0 0]Sí, ya me lo veía yo venir... Pero, bueno, creo que puede ser divertido.[n][w][e]
[f 2 1][bup 3 1 1 65535 0 0][vp 1 0 0 16 0 0][f 4 23 0 3 1 25 25]Igual se me queda una piel suave y sedosa con tanta vitamina que tienen las verduras.[n][w][e]

[msg MSG_009_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 6 1 65535 0 0][vp 1 0 0 17 0 0]Je, je... Eso sería digno de ver.[n][w][e]

[msg MSG_010_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 1 65535 0 0][vp 1 0 0 18 0 0]¡¿Quién, yo?! No, no, mala idea.[n][w][e]
[f 2 1][bup 3 3 1 65535 0 0][vp 1 0 0 19 0 0][f 4 23 0 3 3 25 25]Planté campanillas para un proyecto en primaria y no sobrevivió ni una.[n][w][e]
[f 2 1][bup 3 0 1 65535 0 0][vp 1 0 0 20 0 0][f 4 23 0 3 0 25 25]Pero, oye, igual esto es una segunda oportunidad. Supongo que podría ayudar de vez en cuando...[n][w][e]

[msg MSG_011_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 1 65535 0 0][vp 1 0 0 21 0 0]Cuanto más tiempo y esmero le eches, mejores serán los resultados.[n][w][e]
[f 2 1][bup 5 1 1 65535 0 0][vp 1 0 0 22 0 0]Puede que merezca la pena colaborar con alguien.[n][w][e]

[msg MSG_012_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 1 65535 0 0][vp 1 0 0 23 0 0]Yo también estoy interesada...[n][w][e]

[msg MND_013_0_0]
[f 2 1]Contar con ayuda para el huerto[n]podría afectar al resultado final.[n][w][e]

[msg MSG_014_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 1 65535 0 0][vp 1 0 0 24 0 0]Pues esta zona queda vista. Volvamos abajo.[n][w][e]

