[msg MSG_000_0_0 [Hombre excéntrico]]
[f 2 1][f 5 21 1 436]Mmm...[n][w][e]
[f 2 1][f 5 21 1 436]Anda, hola. Sé que es repentino, pero ¿quieres ser Mamá Noel?[n][w][e]

[sel SEL_001_0_0 top]
[f 2 1]¿Mamá Noel?[e]
[f 2 1]¿Qué quieres decir?[e]

[msg MSG_002_0_0 [Hombre excéntrico]]
[f 2 1][f 5 21 1 436]Que esto quede entre nosotros, pero soy el Papá Noel que cumple los deseos de los niños en Navidad.[n][w][e]
[f 2 1][f 5 21 1 436]Aunque tampoco se puede saber si voy vestido así.[n][w][e]
[f 2 1][f 5 21 1 436]Mira, estoy buscando a alguien que me ayude con mis obligaciones navideñas.[n][w][e]
[f 2 1][f 5 21 1 436]Es un trabajo peculiar, pero nunca sobran manos. ¿Qué te parece? ¿Quieres probar?[n][w][e]

[sel SEL_003_0_0 top]
[f 2 1]Lo haré.[e]
[f 2 1]No, gracias.[e]

[msg MSG_004_0_0 [Hombre excéntrico]]
[f 2 1][f 5 21 1 436]¡Estupendo! Manos a la obra. Pero, antes de nada, una pregunta.[n][w][e]
[f 2 1][f 5 21 1 436]¿Podrías demostrarme que has hecho algo bueno por el mundo?[n][w][e]

[msg MSG_005_0_0 [Hombre excéntrico]]
[f 2 1][f 5 21 1 436]Entiendo... Bueno, si cambias de opinión, ya sabes dónde encontrarme.[n][w][e]

[msg MND_006_0_0]
[f 2 1]Algo bueno que he hecho por el mundo...[n][w][e]
[f 2 1]Si salvo a alguien de un lugar peligroso, podría reconocer mi buena acción.[n][w][e]

[msg MSG_007_0_0 [Hombre excéntrico]]
[f 2 1][f 5 21 1 436]Muy bien, te estaré esperando.[n][w][e]

[msg MSG_008_0_0 [Hombre excéntrico]]
[f 2 1][f 5 21 1 436]Mira, estoy buscando a alguien que me ayude con mis obligaciones navideñas.[n][w][e]
[f 2 1][f 5 21 1 436]Es un trabajo peculiar, pero nunca sobran manos. ¿Qué te parece? ¿Quieres probar?[n][w][e]

[msg MSG_009_0_0 [Hombre excéntrico]]
[f 2 1][f 5 21 1 436]¿Podrías demostrarme que has hecho algo bueno por el mundo?[n][w][e]

[msg MSG_010_0_0 [Hombre excéntrico]]
[f 2 1][f 5 21 1 436]¿Mmm? ¿Querías enseñarme algo?[n][w][e]

[msg MND_011_0_0]
[f 2 1]Le he enseñado al supuesto Papá Noel una carta de agradecimiento.[n][w][e]

[msg MSG_012_0_0 [Hombre excéntrico]]
[f 2 1][f 5 21 1 436]Anda, así que has rescatado a una persona desaparecida...[n][w][e]
[f 2 1][f 5 21 1 436]Jugarse la vida por ayudar a los demás es algo que no hace cualquiera.[n][w][e]
[f 2 1][f 5 21 1 436]Fantástico, ¡has pasado la prueba! Toma, aquí tienes.[n][w][e]

[msg MSG_013_0_0 [Hombre excéntrico]]
[f 2 1][f 5 21 1 436]Enhorabuena, ¡eres una Mamá Noel acreditada! Aunque los aprendices solo llevan el gorro.[n][w][e]
[f 2 1][f 5 21 1 436]Sin más dilaciones, ahí va tu primera tarea: entrega esto a alguien que lo necesite.[n][w][e]

[msg MSG_014_0_0 [Hombre excéntrico]]
[f 2 1][f 5 21 1 436]El trabajo de este año ya está casi hecho. El año que viene podrás empezar a emplearte a fondo.[n][w][e]
[f 2 1][f 5 21 1 436]Ya nos veremos cuando llegue el momento. ¡Feliz Navidad![n][w][e]

[msg MND_015_0_0]
[f 2 1]Ahora que caigo, recibí una carta de agradecimiento de una persona desaparecida a la que rescaté.[n][w][e]

[msg MSG_016_0_0 [Hombre excéntrico]]
[f 2 1]¿Mmm? ¿Querías enseñarme algo?[n][w][e]

