[sel SEL_YESNO top]
[f 2 1]Todo listo.[e]
[f 2 1]Vamos a evitar el combate por ahora.[e]

[msg MSG_MONAD_BTL_QUESTION_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 2 65535 50 0 0][vp 1 0 1 5343 0 0]¡Es un enemigo fuerte! ¿Lista para luchar?[n][w][e]

[msg MSG_MONAD_BTL_QUESTION_1 [Fuuka Yamagishi]]
[f 2 1][bup 6 2 65535 50 0 0][vp 1 0 1 5343 0 0]Tendrás que derrotar a este enemigo para avanzar... ¿Estás preparada?[n][w][e]

[msg MSG_MONAD_BTL_QUESTION_2 [Fuuka Yamagishi]]
[f 2 1][bup 6 2 65535 50 0 0][vp 1 0 1 5343 0 0]¡Un enemigo de lo más poderoso! Antes de enfrentarte a él, ¡asegúrate de que estás preparada![n][w][e]

