[msg MSG_000_0_0 [Bebe]]
[f 2 1][bup 112 3 65535 65535 0 0][vp 1 0 0 1 0 0]Uf, es inútil. No me concentro...[n][w][e]
[f 2 1][bup 112 3 65535 65535 0 0][vp 1 0 0 2 0 0]No he avanzado casi nada.[n][w][e]

[sel SEL_001_0_0 top]
[f 2 1]¿Qué ocurre?[e]
[f 2 1]¿No quieres descansar?[e]

[msg MSG_002_0_0 [Bebe]]
[f 2 1][bup 112 3 65535 65535 0 0][vp 1 0 0 3 0 0]No dejo de pensar en mi tío.[n][w][e]
[f 2 1][bup 112 3 65535 65535 0 0][vp 1 0 0 4 0 0]¿Cómo puedo convencerlo de que me deje quedarme aquí?[n][w][e]

[msg MSG_003_0_0 [Bebe]]
[f 2 1][bup 112 3 65535 65535 0 0][vp 1 0 0 5 0 0]Quizá, si me hiciera samurái, podría plantarle cara.[n][w][e]

[msg MSG_004_0_0 [Bebe]]
[f 2 1][bup 112 0 65535 65535 0 0][vp 1 0 0 6 0 0][f 5 13 15 5 112]Pues, en realidad, es muy buena idea. ¡Merci![n][w][e]

[msg MSG_005_0_0 [Bebe]]
[f 2 1][bup 112 3 65535 65535 0 0][vp 1 0 0 7 0 0]No dejo de pensar en mi tío.[n][w][e]
[f 2 1][bup 112 3 65535 65535 0 0][vp 1 0 0 8 0 0]¿Cómo puedo convencerlo de que me deje quedarme aquí?[n][w][e]
[f 2 1][bup 112 3 65535 65535 0 0][vp 1 0 0 9 0 0]Quizá, si me hiciera samurái, podría plantarle cara.[n][w][e]

[msg MSG_006_0_0 [Bebe]]
[f 2 1][bup 112 4 65535 65535 0 0][vp 1 0 0 10 0 0]¡Ah![n][w][e]
[f 2 1][bup 112 1 65535 65535 0 0][vp 1 0 0 11 0 0][f 4 23 0 1 1 25 25]Si vamos a comer algo dulce, ¡a lo mejor se me ocurre un plan![n][w][e]
[f 2 1][bup 112 0 65535 65535 0 0][vp 1 0 0 12 0 0][f 4 23 0 1 0 25 25]¿Te vienes a Azuki Arai avec moi?[n][w][e]

[sel SEL_007_0_0 top]
[f 2 1]Venga.[e]
[f 2 1]Solo un minuto...[e]

[msg MSG_008_0_0 [Bebe]]
[f 2 1][bup 112 1 65535 65535 0 0][vp 1 0 0 13 0 0][f 5 13 15 5 112]¡A Azuki Arai que vamos![n][w][e]

[msg MSG_009_0_0 [Bebe]]
[f 2 1][bup 112 4 65535 65535 0 0][vp 1 0 0 14 0 0][f 5 13 15 5 112]¡Ah, sugoi! ¿Quieres acabar de coser primero?[n][w][e]
[f 2 1][bup 112 0 65535 65535 0 0][vp 1 0 0 15 0 0][f 4 23 0 1 0 25 25]Cuánta disciplina, ¡como un auténtico samurái![n][w][e]

[msg MSG_010_0_0 [Bebe]]
[f 2 1][bup 112 0 65535 65535 0 0][vp 1 0 0 16 0 0]¡No puedo dejar que mi rival me supere! ¡Primero, a trabajar! Ya iremos luego.[n][w][e]

