[msg AST_BattleEnd_01 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 50 0 0]¡Menos mal que hemos podido ganar![n][w][e]

[msg MND_Encount_Try01]
[f 2 1]¿Deberíamos desafiar a un enemigo tan fuerte...?[n][w][e]

[sel SEL_Encount top]
[f 2 1]Al lío.[e]
[f 2 1]Un segundo...[e]

[msg MSG_Encount_Try_Yukari [Yukari Takeba]]
[f 2 1][bup 2 2 65535 0 0 0][vp 3 0 65535 1128 0 0]Parece fuerte... ¿Seguro que quieres continuar?[n][w][e]

[msg MSG_Encount_Try_Junpei [Junpei Iori]]
[f 2 1][bup 3 2 65535 0 0 0][vp 3 0 65535 2118 0 0]Bien, ¡vamos allá![n][w][e]

[msg MSG_Encount_Try_Sanada [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 0 0 0][vp 3 0 65535 3117 0 0]Va a ser un buen oponente. ¿Estás lista?[n][w][e]

[msg MSG_Encount_Try_Mitsuru [Mitsuru Kirijo]]
[f 2 1][bup 5 2 65535 0 0 0][vp 3 0 65535 4117 0 0]Es un oponente increíble... ¿Estás preparada?[n][w][e]

[msg MSG_Encount_Try_Aegis [Aigis]]
[f 2 1][bup 7 0 65535 0 0 0][vp 3 0 65535 6117 0 0]El enemigo parece ser bastante más fuerte de lo normal. Espero tus órdenes.[n][w][e]

[msg MSG_Encount_Try_Amada [Ken Amada]]
[f 2 1][bup 8 2 65535 0 0 0][vp 3 0 65535 7119 0 0]¡Estoy listo! ¡Vamos a acabar con esto![n][w][e]

[msg MSG_Encount_Try_Aragaki [Shinjiro Aragaki]]
[f 2 1][bup 10 2 65535 0 0 0][vp 3 0 65535 9109 0 0]¿Y bien? ¿Nos vamos?[n][w][e]

[msg MSG_Encount_Try_Fuka [Fuuka Yamagishi]]
[f 2 1][bup 6 2 65535 50 0 0]No podemos evitar la batalla que nos espera ahí delante. ¿Seguro que quieres continuar?[n][w][e]

[msg MND_Encount_Tutorial]
[f 2 1]Ha brotado algo en mí durante el combate...[n][w][e]

[msg MSG_Encount_Tutorial_Fuk [Fuuka Yamagishi]]
[f 2 1][bup 6 2 65535 50 0 0][vp 3 0 65535 5128 0 0]¡Detecto una sombra ahí delante! ¡Y de las poderosas![n][w][e]

[msg MSG_Encount_Tutorial_Fuk_2 [Fuuka Yamagishi]]
[f 2 1][bup 6 2 65535 50 0 0]Parece que, si queremos avanzar, no nos queda otra que luchar...[n][w][e]

[msg MSG_Encount_Tutorial_Fuk_3 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 50 0 0][vp 3 0 65535 5116 0 0]No percibo más enemigos por aquí...[n][w][e]
[f 2 1][bup 6 4 65535 50 0 0]¡Eh! ¡Hay un cofre del tesoro más adelante![n][w][e]

[msg MSG_Encount_Tutorial_Fuk_4 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 50 0 0]Me pregunto si esa sombra estaría vigilando esto...[n][w][e]
[f 2 1][bup 6 0 65535 50 0 0]No creo que nos hayamos enfrentado a una así antes. Échale un vistazo.[n][w][e]

[msg MSG_Encount_Tutorial_Fuk_5 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 50 0 0][vp 3 0 65535 5076 0 0]Parece que tendremos que luchar si queremos explorar más allá.[n][w][e]

[sel SEL_TutoEncount top]
[f 2 1]Todo listo.[e]
[f 2 1]Bueno, vámonos por ahora.[e]

