[sel SEL_BATTLE top]
[f 2 1]Vamos.[e]
[f 2 1]Espera un momento.[e]

[msg MSG_DUNGE_FUKA_STOP [Fuuka Yamagishi]]
[f 2 1][bup 6 4 65535 65535 0 0][vp 3 0 65535 5092 0 0]Esta sombra es demasiado fuerte para un grupo tan pequeño, ¡podrían matarte![n][w][e]

[msg MSG_DUNGE_FUKA_CONF [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5145 0 0]Muy bien... Aquí es.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]¿Estás lista?[n][w][e]

[msg MSG_DUNGE_FUKA_STOP_ESCA [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0][vp 3 0 65535 5076 0 0]Ahora no podemos retirarnos.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]¡Tomémonos un momento para respirar y prepararnos para atacar![n][w][e]

