[msg MSG_000_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 1 0 0]¿Qué quieres hacer ahora? ¿Ir al karaoke?[n][w][e]

[msg MSG_001_0_0 [Niño]]
[f 2 1][vp 1 0 0 2 0 0][f 5 21 0 1001]¡Mami! ¿Dónde estás?[n][w][e]

[msg MSG_002_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 0 0 0 3 0 0]¿...?[n][w][e]

[msg MSG_003_0_0 [Niño]]
[f 2 1][vp 1 0 0 4 0 0][f 5 21 0 1001]¡M-mamiiii! ¡¿Dónde estáááás?![n][w][e]

[msg MSG_004_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 5 0 0]Eh, ¿qué te pasa? ¿Te has perdido?[n][w][e]

[msg MSG_005_0_0 [Niño]]
[f 2 1][vp 1 0 0 6 0 0][f 5 21 0 1001]M-mi mamá me dijo que esperase aquí... y... y... me dio dinero, pero...[n][w][e]
[f 2 1][vp 1 0 0 7 0 0][f 5 21 0 1001]No... No ha vuelto...[n][w][e]

[msg MSG_006_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 8 0 0]Eh, no llores...[n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 9 0 0]¿Ves? No pasa nada.[n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 10 0 0]Me quedaré contigo, ¿vale?[n][w][e]

[msg MSG_006_5_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 11 0 0]Anda, ¡mira! ¡Seguro que allí nos ayudan![n][w][e]

[msg MSG_007_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 12 0 0]Venga, ven conmigo.[n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 13 0 0]Ese policía sabrá que hacer.[n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 14 0 0]Seguro que encuentra a tu madre, así que tranquilo.[n][w][e]

[msg MSG_008_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 15 0 0]Uf, qué alivio... Me alegro de que encontrara a sus padres.[n][w][e]
[f 2 1][bup 2 2 65535 65535 0 0][vp 1 0 0 16 0 0][f 4 23 0 2 2 25 25]Pero ¡¿cómo se les ocurre dejar al pobre niño solo?![n][w][e]
[f 2 1][bup 2 2 65535 65535 0 0][vp 1 0 0 17 0 0]¡Estas cosas me cabrean muchísimo![n][w][e]

[msg MSG_009_0_0 [Yukari Takeba]]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 18 0 0]Pero...[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 19 0 0]Mi madre es exactamente igual.[n][w][e]

[sel SEL_010_0_0 top]
[f 2 1]¿Por qué dices eso?[e]
[f 2 1]...[e]

[msg MSG_011_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 20 0 0]¿Por qué quieres saberlo?[n][w][e]

[msg MSG_012_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 21 0 0]Perdona, no pretendía burlarme de ti.[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 22 0 0]¿Recuerdas que te conté que mi madre y yo no estamos muy unidas?[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 23 0 0]Pues si tuviera que describir qué tipo de madre es, lo más exacto sería: "una terrible".[n][w][e]

[msg MSG_012_3_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 24 0 0]Aunque no siempre fue así.[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 25 0 0][f 4 23 0 2 3 25 25]Cambió por completo después de lo que le pasó a papá...[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 26 0 0][f 4 23 0 2 0 25 25]Seguro que ahora vive con alguno de sus novios... Casi prefiero ni saberlo.[n][w][e]

[msg MSG_013_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 27 0 0]¿No quieres saber a qué me refiero?[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 28 0 0]Imagino que no quieres meterte donde no te llaman, ¿me equivoco?[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 29 0 0]Bueno, supongo que tienes razón, es un asunto personal.[n][w][e]

[msg MSG_014_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 30 0 0]Aunque me preguntes, no sabría qué decir. No sé qué andará haciendo últimamente.[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 31 0 0]Seguro que está con alguno de sus novios. No sé más.[n][w][e]

[msg MSG_015_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 32 0 0]En fin, dejemos el tema.[n][w][e]

[msg MSG_016_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 33 0 0]Oye, [nl], que esto quede entre nosotras. No se lo he dicho a nadie más.[n][w][e]

[msg MND_017_0_0]
[f 2 1]Yukari me ha hablado de la complicada relación que tiene con su madre.[n][w][e]
[f 2 1]Parece que nuestra relación se ha estrechado.[n][w][e]

[msg MSG_018_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 34 0 0]Perdona, pero ya no me apetece ir al karaoke.[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 35 0 0]Vámonos a casa.[n][w][e]

[msg MND_019_0_0]
[f 2 1]Me he despedido de Yukari y he vuelto a la residencia.[n][w][e]

