[msg MSG_000_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 50 0 0][vp 1 0 1 10000 0 0]Debería haber un monorraíl unos 200 metros más adelante.[n][w][e]
[f 2 1][bup 5 0 65535 50 0 0][vp 1 0 1 10001 0 0]Alcánzalo cuanto antes. No queremos que ningún pasajero salga herido.[n][w][e]

[msg MSG_001_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 65535 65535 0 0][vp 1 0 1 20618 0 0]¡Hostia, estamos muy arriba! Creo que voy a vomitar.[n][w][e]

[msg MSG_002_0_0 [Yukari Takeba]]
[f 2 1][bup 2 6 65535 65535 0 0][vp 3 0 65535 1022 0 0]...[n][w][e]

[msg MSG_003_0_0 [Yukari Takeba]]
[f 2 1][bup 2 6 65535 65535 0 0][vp 3 0 65535 1124 0 0]Pero, ¿qué?[n][w][e]

