[msg MSG_000_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4024 0 0]Ah, eres tú. Me pillas ayudando a Akihiko con los estudios.[n][w][e]

[msg MSG_000_1_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0]¿Nos acompañas? Seguro que podemos echarte un cable.[n][w][e]

[sel SEL_001_0_0 top]
[f 2 1]Estudiemos juntos.[e]
[f 2 1]¿Cuál es el estado del grupo?[e]
[f 2 1]Quiero ir a la torre Tártaro.[e]
[f 2 1]No, gracias.[e]

[msg MSG_002_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4131 0 0]Muy bien. Empecemos.[n][w][e]

[msg MSG_003_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4130 0 0]Vaya, veo que estás confiada en que te saldrán bien.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Estaremos aquí durante un buen tiempo, por si cambias de opinión.[n][w][e]

[msg MSG_004_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4136 0 0]¿Qué sucede? ¿Al final te apetece que estudiemos juntos?[n][w][e]

[msg MSG_004_1_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4136 0 0]¿Qué sucede?[n][w][e]

[msg MSG_004_2_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0]¿Al final te apetece que estudiemos juntos?[n][w][e]

[sel SEL_005_0_0 top]
[f 2 1]Estudiemos juntos.[e]
[f 2 1]Quiero ir a la torre Tártaro.[e]
[f 2 1]No, gracias.[e]

[msg MSG_006_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4085 0 0]Vale, empecemos.[n][w][e]

[msg MSG_007_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4061 0 0]Entiendo. No te obligaré a nada.[n][w][e]

[msg MSG_012_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4061 0 0]Hay gente que ya tiene planes y no puede salir esta noche:[n][w][e]

[msg SYS_014_0_0]
[f 2 1]Yukari Takeba[n][w][e]

[msg MSG_013_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0]¿Necesitas algo más?[n][w][e]

[msg MSG_008_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4060 0 0]¿Quieres ir a la torre Tártaro? Espero que no te estés forzando demasiado, sobre todo ahora que llegan los exámenes.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Además, insisto en que no todo el mundo irá. Ahora bien, si de verdad quieres ir, no te detendré.[n][w][e]

[sel SEL_009_0_0 top]
[f 2 1]Pues yo quiero ir.[e]
[f 2 1]Da igual.[e]

[msg MSG_010_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4029 0 0]Muy bien, hora de reunirse.[n][w][e]

[msg MSG_011_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4061 0 0]Buena decisión. Lo mejor es que hoy te concentres en tus estudios.[n][w][e]

[msg MND_Temperance]
[f 2 1]El arcano de la Templanza podría ayudarme a mejorar todavía más.[n][w][e]

