[msg MSG_024_0_0 [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 1 0 0]Parece que las plagas han causado menos daños de lo que había previsto.[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 2 0 0][f 4 21 7 4]No hemos tomado medidas contra ellas. ¿A qué se deberá?[n][w][e]

[msg MSG_025_0_0 [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 3 0 0]¿Eh? Esto es...[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 4 0 0]¡Mira, [nf]! ¡Una larva de mariquita! Es pequeñísima, qué mona.[n][w][e]

[sel SEL_026_0_0 top]
[f 2 1]Matémosla.[e]
[f 2 1]Déjala.[e]
[f 2 1]No me la acerques.[e]

[msg MSG_027_0_0 [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 5 0 0]No, ni pensarlo.[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 6 0 0]Las mariquitas se alimentan de las plagas que dañan las plantas.[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 7 0 0]Por eso estarán creciendo tan sanas.[n][w][e]

[msg MSG_028_0_0 [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 8 0 0]Estoy de acuerdo. Mejor no interrumpirla mientras come.[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 9 0 0]Las mariquitas se alimentan de las plagas que dañan las plantas.[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 10 0 0]Por eso no hay insectos dañinos cerca.[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 11 0 0][f 4 21 7 7]Muchas gracias, mariquita.[n][w][e]

[msg MSG_029_0_0 [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 12 0 0]Te has puesto blanca. No te va a morder, tranquila.[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 13 0 0]La moveré a otra hoja.[n][w][e]

[msg MSG_029_5_0 [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 0 0 0 14 0 0]...[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 15 0 0]No se queda quieta.[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 16 0 0]Parece que la mariquita prefiere estar cerca de ti, [nf].[n][w][e]

[msg MSG_030_0_0 [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 17 0 0]Con lo pequeños que son los maceteros y la cantidad de vida que albergan...[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 18 0 0]Nadie les enseña nada. Solo lo hacen lo mejor que pueden.[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0][vp 0 0 0 19 0 0]...[n][w][e]

[msg MSG_031_0_0 [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 20 0 0]Perdona, me he distraído. Continuemos.[n][w][e]

[msg MND_032_0_0]
[f 2 1]He regado las plantas con Aigis.[n][w][e]

[msg MSG_033_0_0 [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 21 0 0]Disculpa, [nf]. Aplica el repelente en ese extremo, por favor.[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 22 0 0]Las plagas no merecen piedad.[n][w][e]

[msg MND_034_0_0]
[f 2 1]Las hemos cuidado con tanto mimo que darán buen fruto.[n][w][e]

[msg MSG_035_0_0 [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 23 0 0][f 5 13 22 1 7]Todo está en perfecto estado. No se detectan problemas.[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 24 0 0]Pues ya está, aquí concluye la misión de hoy. Deberíamos volver.[n][w][e]

[msg MSG_036_0_0 [Aigis]]
[f 2 1][bup 7 1 202 65535 0 0][vp 1 0 0 25 0 0][f 4 23 0 7 1 25 25]Menos mal, las plagas han causado menos daños de lo que esperaba.[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 26 0 0][f 4 21 7 4][f 4 23 0 7 0 25 25]Pero no hemos tomado medidas de ningún tipo. ¿Qué estará pasando?[n][w][e]

[msg MSG_037_0_0 [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 27 0 0]¿Eh? Esto es...[n][w][e]
[f 2 1][bup 7 1 202 65535 0 0][vp 1 0 0 28 0 0]¡Mira, [nf]! ¡Una larva de mariquita! Es pequeñísima, qué mona.[n][w][e]

[sel SEL_038_0_0 top]
[f 2 1]Matémosla.[e]
[f 2 1]Déjala.[e]
[f 2 1]No me la acerques.[e]

[msg MSG_039_0_0 [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 29 0 0]¡No, ni pensarlo![n][w][e]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 30 0 0]Las mariquitas se alimentan de las plagas que dañan las plantas.[n][w][e]
[f 2 1][bup 7 1 202 65535 0 0][vp 1 0 0 31 0 0]Por eso no hay insectos dañinos cerca.[n][w][e]

[msg MSG_040_0_0 [Aigis]]
[f 2 1][bup 7 1 202 65535 0 0][vp 1 0 0 32 0 0]Sí, mejor no interrumpirla mientras come.[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 33 0 0]Las mariquitas se alimentan de las plagas que dañan las plantas.[n][w][e]
[f 2 1][bup 7 1 202 65535 0 0][vp 1 0 0 34 0 0]Por eso no hay insectos dañinos cerca.[n][w][e]
[f 2 1][bup 7 1 202 65535 0 0][vp 1 0 0 35 0 0][f 4 21 7 7]Muchas gracias, mariquita.[n][w][e]

[msg MSG_041_0_0 [Aigis]]
[f 2 1][bup 7 3 202 65535 0 0][vp 1 0 0 36 0 0][f 4 23 0 7 3 25 25]¿Te incomodan los insectos? La moveré a otra hoja.[n][w][e]

[msg MSG_041_5_0 [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 0 0 0 37 0 0][f 4 23 0 7 0 25 25]...[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 38 0 0]No se queda quieta.[n][w][e]
[f 2 1][bup 7 1 202 65535 0 0][vp 1 0 0 39 0 0]Parece que la mariquita prefiere estar cerca de ti, [nf].[n][w][e]

[msg MSG_042_0_0 [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 40 0 0]Con lo pequeños que son los maceteros y la cantidad de vida que albergan...[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 41 0 0]Nadie les enseña nada. Solo lo hacen lo mejor que pueden.[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0][vp 0 0 0 42 0 0]...[n][w][e]

[msg MSG_043_0_0 [Aigis]]
[f 2 1][bup 7 1 202 65535 0 0][vp 1 0 0 43 0 0][f 4 23 0 7 1 25 25]Perdona, me he distraído. ¿Seguimos?[n][w][e]

[msg MND_044_0_0]
[f 2 1]He regado las plantas con Aigis.[n][w][e]

[msg MSG_045_0_0 [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 44 0 0]Anda, mira, [nf]...[n][w][e]
[f 2 1][bup 7 3 202 65535 0 0][vp 1 0 0 45 0 0][f 4 23 0 7 3 25 25]No me gusta interferir, pero no podemos permitir que destruyan las plantas.[n][w][e]
[f 2 1][bup 7 1 202 65535 0 0][vp 1 0 0 46 0 0][f 4 23 0 7 1 25 25]Ayudemos un poco a la mariquita.[n][w][e]

[msg MND_046_0_0]
[f 2 1]Las hemos cuidado con tanto mimo que darán buen fruto.[n][w][e]

[msg MSG_047_0_0 [Aigis]]
[f 2 1][bup 7 1 202 65535 0 0][vp 1 0 0 47 0 0][f 5 13 22 1 7]Todo está en perfecto estado. No se detectan problemas.[n][w][e]
[f 2 1][bup 7 1 202 65535 0 0][vp 1 0 0 48 0 0]Bueno, pues hoy ya hemos terminado. Es hora de volver.[n][w][e]

[msg MSG_072_0_0 [Aigis]]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 1 0 0]Parece que las plagas han causado menos daños de lo que había previsto.[n][w][e]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 2 0 0][f 4 21 7 4]No hemos tomado medidas contra ellas. ¿A qué se deberá?[n][w][e]

[msg MSG_073_0_0 [Aigis]]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 3 0 0]¿Eh? Esto es...[n][w][e]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 4 0 0]¡Mira, [nf]! ¡Una larva de mariquita! Es pequeñísima, qué mona.[n][w][e]

[sel SEL_074_0_0 top]
[f 2 1]Matémosla.[e]
[f 2 1]Déjala.[e]
[f 2 1]No me la acerques.[e]

[msg MSG_075_0_0 [Aigis]]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 5 0 0]No, ni pensarlo.[n][w][e]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 6 0 0]Las mariquitas se alimentan de las plagas que dañan las plantas.[n][w][e]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 7 0 0]Por eso estarán creciendo tan sanas.[n][w][e]

[msg MSG_076_0_0 [Aigis]]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 8 0 0]Estoy de acuerdo. Mejor no interrumpirla mientras come.[n][w][e]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 9 0 0]Las mariquitas se alimentan de las plagas que dañan las plantas.[n][w][e]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 10 0 0]Por eso no hay insectos dañinos cerca.[n][w][e]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 11 0 0][f 4 21 7 7]Muchas gracias, mariquita.[n][w][e]

[msg MSG_077_0_0 [Aigis]]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 12 0 0]Te has puesto blanca. No te va a morder, tranquila.[n][w][e]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 13 0 0]La moveré a otra hoja.[n][w][e]

[msg MSG_077_5_0 [Aigis]]
[f 2 1][bup 7 0 2 65535 0 0][vp 0 0 0 14 0 0]...[n][w][e]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 15 0 0]No se queda quieta.[n][w][e]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 16 0 0]Parece que la mariquita prefiere estar cerca de ti, [nf].[n][w][e]

[msg MSG_078_0_0 [Aigis]]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 17 0 0]Con lo pequeños que son los maceteros y la cantidad de vida que albergan...[n][w][e]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 18 0 0]Nadie les enseña nada. Solo lo hacen lo mejor que pueden.[n][w][e]
[f 2 1][bup 7 0 2 65535 0 0][vp 0 0 0 19 0 0]...[n][w][e]

[msg MSG_079_0_0 [Aigis]]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 20 0 0]Perdona, me he distraído. Continuemos.[n][w][e]

[msg MND_080_0_0]
[f 2 1]He regado las plantas con Aigis.[n][w][e]

[msg MSG_081_0_0 [Aigis]]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 21 0 0]Disculpa, [nf]. Aplica el repelente en ese extremo, por favor.[n][w][e]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 22 0 0]Las plagas no merecen piedad.[n][w][e]

[msg MND_082_0_0]
[f 2 1]Las hemos cuidado con tanto mimo que darán buen fruto.[n][w][e]

[msg MSG_083_0_0 [Aigis]]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 23 0 0][f 5 13 22 1 7]Todo está en perfecto estado. No se detectan problemas.[n][w][e]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 24 0 0]Pues ya está, aquí concluye la misión de hoy. Deberíamos volver.[n][w][e]

[msg MSG_084_0_0 [Aigis]]
[f 2 1][bup 7 1 2 65535 0 0][vp 1 0 0 25 0 0][f 4 23 0 7 1 25 25]Menos mal, las plagas han causado menos daños de lo que esperaba.[n][w][e]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 26 0 0][f 4 21 7 4][f 4 23 0 7 0 25 25]Pero no hemos tomado medidas de ningún tipo. ¿Qué estará pasando?[n][w][e]

[msg MSG_085_0_0 [Aigis]]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 27 0 0]¿Eh? Esto es...[n][w][e]
[f 2 1][bup 7 1 2 65535 0 0][vp 1 0 0 28 0 0]¡Mira, [nf]! ¡Una larva de mariquita! Es pequeñísima, qué mona.[n][w][e]

[sel SEL_086_0_0 top]
[f 2 1]Matémosla.[e]
[f 2 1]Déjala.[e]
[f 2 1]No me la acerques.[e]

[msg MSG_087_0_0 [Aigis]]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 29 0 0]¡No, ni pensarlo![n][w][e]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 30 0 0]Las mariquitas se alimentan de las plagas que dañan las plantas.[n][w][e]
[f 2 1][bup 7 1 2 65535 0 0][vp 1 0 0 31 0 0]Por eso no hay insectos dañinos cerca.[n][w][e]

[msg MSG_088_0_0 [Aigis]]
[f 2 1][bup 7 1 2 65535 0 0][vp 1 0 0 32 0 0]Sí, mejor no interrumpirla mientras come.[n][w][e]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 33 0 0]Las mariquitas se alimentan de las plagas que dañan las plantas.[n][w][e]
[f 2 1][bup 7 1 2 65535 0 0][vp 1 0 0 34 0 0]Por eso no hay insectos dañinos cerca.[n][w][e]
[f 2 1][bup 7 1 2 65535 0 0][vp 1 0 0 35 0 0][f 4 21 7 7]Muchas gracias, mariquita.[n][w][e]

[msg MSG_089_0_0 [Aigis]]
[f 2 1][bup 7 3 2 65535 0 0][vp 1 0 0 36 0 0][f 4 23 0 7 3 25 25]¿Te incomodan los insectos? La moveré a otra hoja.[n][w][e]

[msg MSG_089_5_0 [Aigis]]
[f 2 1][bup 7 0 2 65535 0 0][vp 0 0 0 37 0 0][f 4 23 0 7 0 25 25]...[n][w][e]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 38 0 0]No se queda quieta.[n][w][e]
[f 2 1][bup 7 1 2 65535 0 0][vp 1 0 0 39 0 0]Parece que la mariquita prefiere estar cerca de ti, [nf].[n][w][e]

[msg MSG_090_0_0 [Aigis]]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 40 0 0]Con lo pequeños que son los maceteros y la cantidad de vida que albergan...[n][w][e]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 41 0 0]Nadie les enseña nada. Solo lo hacen lo mejor que pueden.[n][w][e]
[f 2 1][bup 7 0 2 65535 0 0][vp 0 0 0 42 0 0]...[n][w][e]

[msg MSG_091_0_0 [Aigis]]
[f 2 1][bup 7 1 2 65535 0 0][vp 1 0 0 43 0 0][f 4 23 0 7 1 25 25]Perdona, me he distraído. ¿Seguimos?[n][w][e]

[msg MND_092_0_0]
[f 2 1]He regado las plantas con Aigis.[n][w][e]

[msg MSG_093_0_0 [Aigis]]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 44 0 0]Anda, mira, [nf]...[n][w][e]
[f 2 1][bup 7 3 2 65535 0 0][vp 1 0 0 45 0 0][f 4 23 0 7 3 25 25]No me gusta interferir, pero no podemos permitir que destruyan las plantas.[n][w][e]
[f 2 1][bup 7 1 2 65535 0 0][vp 1 0 0 46 0 0][f 4 23 0 7 1 25 25]Ayudemos un poco a la mariquita.[n][w][e]

[msg MND_094_0_0]
[f 2 1]Las hemos cuidado con tanto mimo que darán buen fruto.[n][w][e]

[msg MSG_095_0_0 [Aigis]]
[f 2 1][bup 7 1 2 65535 0 0][vp 1 0 0 47 0 0][f 5 13 22 1 7]Todo está en perfecto estado. No se detectan problemas.[n][w][e]
[f 2 1][bup 7 1 2 65535 0 0][vp 1 0 0 48 0 0]Bueno, pues hoy ya hemos terminado. Es hora de volver.[n][w][e]

[msg MSG_305_0_0 [Aigis]]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 1 0 0]Menos mal, las plagas han causado menos daños de lo que esperaba.[n][w][e]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 2 0 0][f 4 21 7 4]No hemos tomado medidas contra ellas. ¿A qué se deberá?[n][w][e]

[msg MSG_307_0_0 [Aigis]]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 3 0 0]¿Eh? Esto es...[n][w][e]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 4 0 0]¡Mira, [nf]! ¡Una larva de mariquita! Es pequeñísima, qué mona.[n][w][e]

[sel SEL_308_0_0 top]
[f 2 1]Matémosla.[e]
[f 2 1]Déjala.[e]
[f 2 1]No me la acerques.[e]

[msg MSG_311_0_0 [Aigis]]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 5 0 0]No, ni pensarlo.[n][w][e]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 6 0 0]Las mariquitas se alimentan de las plagas que dañan las plantas.[n][w][e]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 7 0 0]Por eso estarán creciendo tan sanas.[n][w][e]

[msg MSG_313_0_0 [Aigis]]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 8 0 0]Estoy de acuerdo. Mejor no interrumpirla mientras come.[n][w][e]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 9 0 0]Las mariquitas se alimentan de las plagas que dañan las plantas.[n][w][e]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 10 0 0]Por eso no hay insectos dañinos cerca.[n][w][e]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 11 0 0][f 4 21 7 7]Muchas gracias, mariquita.[n][w][e]

[msg MSG_318_0_0 [Aigis]]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 12 0 0]Te has puesto blanca. No te va a morder, tranquila.[n][w][e]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 13 0 0]La moveré a otra hoja.[n][w][e]

[msg MSG_318_5_0 [Aigis]]
[f 2 1][bup 7 0 6 65535 0 0][vp 0 0 0 14 0 0]...[n][w][e]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 15 0 0]No se queda quieta.[n][w][e]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 16 0 0]Parece que la mariquita prefiere estar cerca de ti, [nf].[n][w][e]

[msg MSG_323_0_0 [Aigis]]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 17 0 0]Con lo pequeños que son los maceteros y la cantidad de vida que albergan...[n][w][e]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 18 0 0]Nadie les enseña nada. Solo lo hacen lo mejor que pueden.[n][w][e]
[f 2 1][bup 7 0 6 65535 0 0][vp 0 0 0 19 0 0]...[n][w][e]

[msg MSG_324_0_0 [Aigis]]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 20 0 0]Perdona, me he distraído. Continuemos.[n][w][e]

[msg MND_326_0_0]
[f 2 1]He regado las plantas con Aigis.[n][w][e]

[msg MSG_328_0_0 [Aigis]]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 21 0 0]Disculpa, [nf]. Aplica el repelente en ese extremo, por favor.[n][w][e]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 22 0 0]Las plagas no merecen piedad.[n][w][e]

[msg MND_329_0_0]
[f 2 1]Las hemos cuidado con tanto mimo que darán buen fruto.[n][w][e]

[msg MSG_330_0_0 [Aigis]]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 23 0 0][f 5 13 22 1 7]Todo está en perfecto estado. No se detectan problemas.[n][w][e]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 24 0 0]Pues ya está, aquí concluye la misión de hoy. Deberíamos volver.[n][w][e]

[msg MSG_332_0_0 [Aigis]]
[f 2 1][bup 7 1 6 65535 0 0][vp 1 0 0 25 0 0][f 4 23 0 7 1 25 25]Menos mal, las plagas han causado menos daños de lo que esperaba.[n][w][e]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 26 0 0][f 4 21 7 4][f 4 23 0 7 0 25 25]Pero no hemos tomado medidas de ningún tipo. ¿Qué estará pasando?[n][w][e]

[msg MSG_335_0_0 [Aigis]]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 27 0 0][f 4 23 0 7 0 25 25]¿Eh? Esto es...[n][w][e]
[f 2 1][bup 7 1 6 65535 0 0][vp 1 0 0 28 0 0]¡Mira, [nf]! ¡Una larva de mariquita! Es pequeñísima, qué mona.[n][w][e]

[sel SEL_336_0_0 top]
[f 2 1]Matémosla.[e]
[f 2 1]Déjala.[e]
[f 2 1]No me la acerques.[e]

[msg MSG_339_0_0 [Aigis]]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 29 0 0]¡No, ni pensarlo![n][w][e]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 30 0 0]Las mariquitas se alimentan de las plagas que dañan las plantas.[n][w][e]
[f 2 1][bup 7 1 6 65535 0 0][vp 1 0 0 31 0 0]Por eso no hay insectos dañinos cerca.[n][w][e]

[msg MSG_342_0_0 [Aigis]]
[f 2 1][bup 7 1 6 65535 0 0][vp 1 0 0 32 0 0]Sí, mejor no interrumpirla mientras come.[n][w][e]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 33 0 0]Las mariquitas se alimentan de las plagas que dañan las plantas.[n][w][e]
[f 2 1][bup 7 1 6 65535 0 0][vp 1 0 0 34 0 0]Por eso no hay insectos dañinos cerca.[n][w][e]
[f 2 1][bup 7 1 6 65535 0 0][vp 1 0 0 35 0 0][f 4 21 7 7]Muchas gracias, mariquita.[n][w][e]

[msg MSG_346_0_0 [Aigis]]
[f 2 1][bup 7 3 6 65535 0 0][vp 1 0 0 36 0 0][f 4 23 0 7 3 25 25]¿Te incomodan los insectos? La moveré a otra hoja.[n][w][e]

[msg MSG_346_5_0 [Aigis]]
[f 2 1][bup 7 0 6 65535 0 0][vp 0 0 0 37 0 0][f 4 23 0 7 0 25 25]...[n][w][e]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 38 0 0]No se queda quieta.[n][w][e]
[f 2 1][bup 7 1 6 65535 0 0][vp 1 0 0 39 0 0]Parece que la mariquita prefiere estar cerca de ti, [nf].[n][w][e]

[msg MSG_351_0_0 [Aigis]]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 40 0 0]Con lo pequeños que son los maceteros y la cantidad de vida que albergan...[n][w][e]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 41 0 0]Nadie les enseña nada. Solo lo hacen lo mejor que pueden.[n][w][e]
[f 2 1][bup 7 0 6 65535 0 0][vp 0 0 0 42 0 0]...[n][w][e]

[msg MSG_352_0_0 [Aigis]]
[f 2 1][bup 7 1 6 65535 0 0][vp 1 0 0 43 0 0][f 4 23 0 7 1 25 25]Perdona, me he distraído. ¿Seguimos?[n][w][e]

[msg MND_354_0_0]
[f 2 1]He regado las plantas con Aigis.[n][w][e]

[msg MSG_356_0_0 [Aigis]]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 44 0 0]Anda, mira, [nf]...[n][w][e]
[f 2 1][bup 7 3 6 65535 0 0][vp 1 0 0 45 0 0][f 4 23 0 7 3 25 25]No me gusta interferir, pero no podemos permitir que destruyan las plantas.[n][w][e]
[f 2 1][bup 7 1 6 65535 0 0][vp 1 0 0 46 0 0][f 4 23 0 7 1 25 25]Ayudemos un poco a la mariquita.[n][w][e]

[msg MND_357_0_0]
[f 2 1]Las hemos cuidado con tanto mimo que darán buen fruto.[n][w][e]

[msg MSG_358_0_0 [Aigis]]
[f 2 1][bup 7 1 6 65535 0 0][vp 1 0 0 47 0 0][f 5 13 22 1 7]Todo está en perfecto estado. No se detectan problemas.[n][w][e]
[f 2 1][bup 7 1 6 65535 0 0][vp 1 0 0 48 0 0]Bueno, pues hoy ya hemos terminado. Es hora de volver.[n][w][e]

