[msg MSG_000_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 1 0 0]Mm, ¡esto está muy bueno! Qué bien hice pidiendo lo mismo que tú, [nl].[n][w][e]

[msg MSG_001_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 2 0 0]Acabo de caer en una cosa. ¿Comer pescado no te transporta al mar?[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 3 0 0]Supongo que, al vivir en la costa, es parte de nuestra vida. Hasta fuimos de vacaciones a la playa.[n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 4 0 0][f 4 23 0 2 1 25 25]Oye, cuando todo esto acabe, ¿por qué no vamos a otro sitio, como a la montaña?[n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 5 0 0]Podríamos hacer algún picnic. E incluso ver ciervos o algo. ¿Qué te parece?[n][w][e]

[sel SEL_002_0_0 top]
[f 2 1]Me parece bien.[e]
[f 2 1]Vayamos con todos.[e]
[f 2 1]Vayamos solo nosotras.[f 2 9 1 1 344][e]
[f 2 1]No, gracias.[e]

[msg MSG_003_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 6 0 0][f 5 13 7 15 2]¿A que sí?[n][w][e]

[msg MSG_004_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 7 0 0]Vale, ¡entonces yo haré la comida![n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 8 0 0]Puede que no lo parezca, ¡pero soy muy buena cocinera! ¡Espera y verás![n][w][e]

[msg MSG_005_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 9 0 0][f 5 13 7 5 2]Mmm, sí, ¿por qué no, verdad? Será como una recompensa por nuestro esfuerzo.[n][w][e]

[msg MSG_006_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 10 0 0]Vale, ¡entonces yo haré la comida![n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 11 0 0]Puede que no lo parezca, ¡pero soy muy buena cocinera! ¡Espera y verás![n][w][e]

[msg MSG_007_0_0 [Yukari Takeba]]
[f 2 1][bup 2 4 65535 65535 0 0][vp 1 0 0 12 0 0][f 5 13 7 15 2]¿A qué viene esto de repente?[n][w][e]
[f 2 1][bup 2 4 65535 65535 0 0][vp 1 0 0 13 0 0]¿Solo nosotras? Y-yo no iba por ahí.[n][w][e]
[f 2 1][bup 2 4 65535 65535 0 0][vp 1 0 0 14 0 0]A ver, no es que no quiera, pero... aún no estoy preparada.[n][w][e]
[f 2 1][bup 2 4 65535 65535 0 0][vp 1 0 0 15 0 0]Madre mía, pero ¡¿qué estoy diciendo?![n][w][e]

[msg MSG_008_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 16 0 0]En cualquier caso, estaría bien ir juntas a algún sitio. Yo puedo preparar la comida.[n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 17 0 0][f 4 23 0 2 1 25 25]Puede que no lo parezca, ¡pero soy muy buena cocinera! ¡Espera y verás![n][w][e]

[msg MSG_009_0_0 [Yukari Takeba]]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 18 0 0]¿Eh? ¿Por qué no?[n][w][e]

[msg MSG_010_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 19 0 0]No te preocupes por la comida, que yo me encargo.[n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 20 0 0][f 4 23 0 2 0 25 25]Puede que no lo parezca, ¡pero soy muy buena cocinera! ¡Espera y verás![n][w][e]

[msg MSG_011_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 21 0 0]Je, je, ya hace tiempo que no hablamos de las vacaciones. ¡Me emociono solo de pensarlo![n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 22 0 0][f 4 23 0 2 0 25 25]No sé cómo decírtelo, pero, cuando estoy contigo, [nl]...[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 23 0 0]No me siento tan sola.[n][w][e]

[msg MSG_012_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 24 0 0]O sea, tengo amigos y a toda la gente de la residencia, pero...[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 25 0 0][f 4 23 0 2 3 25 25]Normalmente, siento como si mi verdadero yo estuviera atrapado en lo más profundo de mi ser.[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 26 0 0]Quizá sea por mi situación familiar, pero siempre aparto de mi lado a la gente que me rodea sin darme cuenta.[n][w][e]

[msg MSG_012_3_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 27 0 0]Aunque creo que poco a poco voy cambiando.[n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 28 0 0][f 4 23 0 2 1 25 25]Y creo que es gracias a ti, [nl].[n][w][e]

[msg MND_013_0_0]
[f 2 1]Yukari confía en mí.[n][w][e]
[f 2 1]Parece que nuestra relación se ha estrechado.[n][w][e]

[msg MSG_014_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 29 0 0]Vaya, estaba riquísimo, pero se está haciendo tarde.[n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 30 0 0]¿Nos vamos?[n][w][e]

[msg MND_015_0_0]
[f 2 1]He decidido volver a la residencia.[n][w][e]

