[msg MND_000_0_0]
[f 2 1]Boles de ternera Umiushi...[n][w][e]
[f 2 1]Ahora mismo hay demasiada gente.[n][w][e]

[msg MND_001_0_0]
[f 2 1]En el sitio web pone que solo los miembros pueden pedir comida para llevar.[n][w][e]

[msg MSG_002_0_0 [Camarero de Umiushi]]
[f 2 1][vp 3 0 65535 20901 0 0]¡Bienvenida! ¿Quieres pedir para llevar?[n][w][e]
[f 2 1]Lo siento, pero solo está disponible para los miembros.[n][w][e]
[f 2 1]Puedes registrarte por internet usando el código incluido en el libro para fanes.[n][w][e]
[f 2 1]¡Regístrate si quieres! Puedes comprar el libro para fanes en el cibercafé.[n][w][e]

[msg MND_003_0_0]
[f 2 1]Debería pasarme por aquí cuando me haya registrado con el libro para fanes.[n][w][e]

[msg MSG_004_0_0 [Camarero de Umiushi]]
[f 2 1][vp 3 0 65535 20901 0 0]¡Bienvenida! Anda, ¡veo que eres una miembro![n][w][e]
[f 2 1]Tenemos platos exclusivos para los miembros, ¡así que échales un ojo![n][w][e]

[msg MSG_005_0_0 [Camarero de Umiushi]]
[f 2 1][vp 3 0 65535 20901 0 0]¡Buenas![n][w][e]

[msg MSG_006_0_0 [Camarero de Umiushi]]
[f 2 1][vp 3 0 65535 20904 0 0]¡Muchas gracias![n][w][e]

[msg MSG_007_0_0 [Camarero de Umiushi]]
[f 2 1][vp 3 0 65535 20902 0 0]Bienvenida...[n][w][e]

[msg MSG_008_0_0 [Camarero de Umiushi]]
[f 2 1][vp 3 0 65535 20906 0 0]Gracias.[n][w][e]

[msg MSG_009_0_0 [Camarero de Umiushi]]
[f 2 1][vp 3 0 65535 20901 0 0]¡Bienvenida! Lo siento, ahora estamos a tope.[n][w][e]
[f 2 1]Podrías pedir la comida para llevar, pero solo está disponible para los miembros.[n][w][e]
[f 2 1]Puedes registrarte por internet usando el código incluido en el libro para fanes.[n][w][e]
[f 2 1]¡Regístrate si quieres! Puedes comprar el libro para fanes en el cibercafé.[n][w][e]

[msg MSG_010_0_0 [Camarero de Umiushi]]
[f 2 1][vp 3 0 65535 20901 0 0]¡Bienvenida! Lo siento, ahora estamos a tope.[n][w][e]
[f 2 1]Anda, ¡veo que has comprado nuestro libro para fanes! Pero aún no te has registrado como miembro...[n][w][e]
[f 2 1]Si tienes un ordenador, visita nuestro sitio web y regístrate con el código de tu libro para fanes.[n][w][e]
[f 2 1]Cuando seas miembro, ¡podrás pedir comida para llevar! Piénsatelo bien.[n][w][e]

[msg MND_011_0_0]
[f 2 1]Tengo que registrarme como miembro para pedir comida para llevar.[n][w][e]
[f 2 1]Podría usar el ordenador de la residencia para registrarme.[n][w][e]

