[msg MSG_000_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6001 0 0]He oído que los estudiantes participan en un evento social llamado "grupo de estudio" antes de los exámenes.[n][w][e]

[msg MSG_000_1_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0]Tal actividad nos permitiría aprender más sobre nosotras. ¿Es algo admisible?[n][w][e]

[sel SEL_001_0_0 top]
[f 2 1]Estudiemos juntas.[e]
[f 2 1]No, gracias.[e]

[msg MSG_002_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6024 0 0]Recibido. Permíteme recuperar mis libros de texto y otros materiales de estudio.[n][w][e]

[msg MSG_003_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6057 0 0]Comprendo. Me mantendré a la espera por si cambias de opinión.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0]Estoy lista para llevar a cabo el "grupo de estudio" en cualquier momento.[n][w][e]

[msg MSG_004_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6068 0 0]¿Has decidido participar en las actividades de grupo de estudio que te solicité anteriormente?[n][w][e]

[msg MSG_004_1_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0]¿En qué piensas?[n][w][e]

[sel SEL_005_0_0 top]
[f 2 1]Estudiemos juntas.[e]
[f 2 1]No, gracias.[e]

[msg MSG_006_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6024 0 0]Recibido. Permíteme recuperar mis libros de texto y otros materiales de estudio.[n][w][e]

[msg MSG_007_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6057 0 0]Comprendo. Por favor, infórmame si cambias de opinión.[n][w][e]

[msg MND_Temperance]
[f 2 1]El arcano de la Templanza podría ayudarme a mejorar todavía más.[n][w][e]

