[msg MSG_000_0_0 [Koromaru]]
[f 2 1][bup 9 0 65535 65535 0 0][vp 3 0 65535 8010 0 0]¡Guau![n][w][e]

[msg MND_001_0_0]
[f 2 1]Koromaru parece estar satisfecho. Quizá debería sacarlo a pasear mañana.[n][w][e]

[msg MSG_066_0_0 [Koromaru]]
[f 2 1][bup 9 1 65535 65535 0 0][vp 3 0 65535 8001 0 0]¡Guau, guau![n][w][e]

[msg MND_068_0_0]
[f 2 1]Koromaru parece estar divirtiéndose.[n][w][e]

[msg MSG_071_0_0 [Koromaru]]
[f 2 1][bup 9 3 65535 65535 0 0][vp 3 0 65535 8003 0 0]Auuu...[n][w][e]

[msg MND_072_0_0]
[f 2 1]Parece estar arrepentido por algo.[n][w][e]

[msg MSG_002_0_0 [Koromaru]]
[f 2 1][bup 9 3 65535 65535 0 0][vp 3 0 65535 8003 0 0]Aahh.[n][w][e]

[msg MND_003_0_0]
[f 2 1]Koromaru parece desanimado.[n][w][e]

[msg MSG_067_0_0 [Koromaru]]
[f 2 1][bup 9 0 65535 65535 0 0][vp 3 0 65535 8008 0 0]¡Guau![n][w][e]

[msg MND_069_0_0]
[f 2 1]Koromaru parece calmado.[n][w][e]

[msg MSG_004_0_0 [Koromaru]]
[f 2 1][bup 9 0 65535 65535 0 0][vp 3 0 65535 8001 0 0]¡Guau, guau![n][w][e]

[msg MND_005_0_0]
[f 2 1]Parece que Koromaru está de buen humor.[n][w][e]

[msg MSG_006_0_0 [Koromaru]]
[f 2 1][bup 9 0 65535 65535 0 0][vp 3 0 65535 8005 0 0]Zzz.[n][w][e]

[msg MND_007_0_0]
[f 2 1]Está bostezando. Debe de tener sueño.[n][w][e]

[msg MSG_008_0_0 [Koromaru]]
[f 2 1][bup 9 0 65535 65535 0 0][vp 3 0 65535 8009 0 0]Haaa, haaa...[n][w][e]

[msg MND_009_0_0]
[f 2 1]Parece estar dispuesto a todo.[n][w][e]

[msg MSG_010_0_0 [Koromaru]]
[f 2 1][bup 9 0 65535 65535 0 0][vp 3 0 65535 8010 0 0]¿Guau?[n][w][e]

[msg MSG_011_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6142 0 0]Ya veo. Entonces, continuaré con mis observaciones.[n][w][e]

[msg MSG_012_0_0 [Koromaru]]
[f 2 1][bup 9 0 65535 65535 0 0][vp 3 0 65535 8003 0 0]Auuu...[n][w][e]

[msg MSG_013_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6059 0 0]Tranquilo, Koromaru. No cometeré ninguna imprudencia.[n][w][e]

[msg MSG_014_0_0 [Koromaru]]
[f 2 1][bup 9 0 65535 65535 0 0][vp 3 0 65535 8009 0 0]Uf, uf...[n][w][e]

[msg MND_015_0_0]
[f 2 1]Casi parece que está sonriendo. También jadea un montón.[n][w][e]

[msg MSG_016_0_0 [Koromaru]]
[f 2 1][bup 9 0 65535 65535 0 0][vp 3 0 65535 8008 0 0]¡Guau![n][w][e]

[msg MND_017_0_0]
[f 2 1]Koromaru tiene más determinación que de costumbre.[n][w][e]

[msg MSG_018_0_0 [Koromaru]]
[f 2 1][bup 9 0 65535 65535 0 0][vp 3 0 65535 8004 0 0]Guau.[n][w][e]

[msg MND_019_0_0]
[f 2 1]Parece que está de buen humor.[n][w][e]

[msg MSG_020_0_0 [Koromaru]]
[f 2 1][bup 9 0 65535 65535 0 0][vp 3 0 65535 8001 0 0]¡Guau, guau![n][w][e]

[msg MND_021_0_0]
[f 2 1]Koromaru me mira fijamente.[n][w][e]

[msg MSG_022_0_0 [Koromaru]]
[f 2 1][bup 9 0 65535 65535 0 0][vp 3 0 65535 8012 0 0]¡Guau, guau![n][w][e]

[msg MND_023_0_0]
[f 2 1]Siento una gran determinación de parte de Koromaru.[n][w][e]

[msg MSG_022_1_0 [Koromaru]]
[f 2 1][bup 9 0 52 65535 0 0][vp 3 0 65535 8012 0 0]¡Guau, guau![n][w][e]

[msg MSG_024_0_0 [Koromaru]]
[f 2 1][bup 9 0 52 65535 0 0][vp 3 0 65535 8008 0 0]Guau.[n][w][e]

[msg MND_025_0_0]
[f 2 1]Koromaru no se mueve. Hoy no creo que vaya a dar ningún paseo.[n][w][e]

[msg MND_026_0_0]
[f 2 1]No parece que Koromaru se vaya a mover del sitio. No debería intentar sacarlo de paseo.[n][w][e]

[msg MND_027_0_0]
[f 2 1]Koromaru ladea la cabeza. No tiene pinta de que le apetezca salir a pasear.[n][w][e]

[msg MND_028_0_0]
[f 2 1]Koromaru irradia una gran determinación. Parece que no está para paseos.[n][w][e]

[msg MND_029_0_0]
[f 2 1]Koromaru está relajado. No parece que esté para paseos hoy.[n][w][e]

[msg MND_030_0_0]
[f 2 1]Koromaru me mira suplicante.[n][w][e]
[f 2 1]Parece que quiere ir de paseo.[n][w][e]

[sel SEL_031_0_0 top]
[f 2 1]Sacarlo a pasear[e]
[f 2 1]Que lo haga otra persona[e]

[sel SEL_032_0_0 top]
[f 2 1]Ir juntos a dar un paseo[e]
[f 2 1]Pasear a Koromaru sola[e]
[f 2 1]Que lo haga otra persona[e]

[msg MND_033_0_0]
[f 2 1]Aigis puede acompañarnos esta noche.[n][w][e]

[msg MND_034_0_0]
[f 2 1]Sanada puede acompañarnos esta noche.[n][w][e]

[msg MND_035_0_0]
[f 2 1]Junpei puede acompañarnos esta noche.[n][w][e]

[msg MND_036_0_0]
[f 2 1]Fuuka puede acompañarnos esta noche.[n][w][e]

[msg MND_037_0_0]
[f 2 1]Mitsuru puede acompañarnos esta noche.[n][w][e]

[msg MND_038_0_0]
[f 2 1]Aragaki puede acompañarnos esta noche.[n][w][e]

[msg MND_039_0_0]
[f 2 1]Amada puede acompañarnos esta noche.[n][w][e]

[msg MND_040_0_0]
[f 2 1]Yukari puede acompañarnos esta noche.[n][w][e]

