[msg MSG_000_0_0 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 1 0 0 1 0 0]Siento ser una carga, pero es que era incapaz de concentrarme haciendo los deberes solo.[n][w][e]
[f 2 1][bup 8 1 65535 65535 0 0][vp 1 0 0 2 0 0][f 4 23 0 8 1 25 25]Gracias por dejarme estudiar contigo.[n][w][e]

[msg MSG_001_0_0 [Koromaru]]
[f 2 1][bup 9 0 65535 65535 0 0][vp 1 0 0 3 0 0]¡Guau![n][w][e]

[msg MSG_002_0_0 [Ken Amada]]
[f 2 1][bup 8 1 65535 65535 0 0][vp 1 0 0 4 0 0]Koromaru dice que también quiere estudiar. ¿A que sí, chico?[n][w][e]

[msg MSG_003_0_0 [Koromaru]]
[f 2 1][bup 9 1 65535 65535 0 0][vp 1 0 0 5 0 0]¡Guau![n][w][e]

[msg MSG_004_0_0 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 1 0 0 6 0 0]Os tiene que resultar difícil pensar en los exámenes con todo lo que está pasando.[n][w][e]

[sel SEL_005_0_0 top]
[f 2 1]No te creas.[e]
[f 2 1]Quizá un poco.[e]
[f 2 1]A mí me motiva aún más.[e]

[msg MSG_006_0_0 [Ken Amada]]
[f 2 1][bup 8 4 65535 65535 0 0][vp 1 0 0 7 0 0]Vaya... Se nota que eres la líder, [nl].[n][w][e]
[f 2 1][bup 8 0 65535 65535 0 0][vp 1 0 0 8 0 0][f 4 23 0 8 0 25 25]Aún tengo la esperanza de que esto sea un sueño del que nos despertaremos pronto.[n][w][e]

[msg MSG_007_0_0 [Ken Amada]]
[f 2 1][bup 8 3 65535 65535 0 0][vp 1 0 0 9 0 0]Ni tú te libras de sentir presión, [nl]...[n][w][e]
[f 2 1][bup 8 3 65535 65535 0 0][vp 1 0 0 10 0 0]Esta situación hace que me plantee si merece la pena hacer los deberes en un momento como este.[n][w][e]

[msg MSG_008_0_0 [Ken Amada]]
[f 2 1][bup 8 4 65535 65535 0 0][vp 1 0 0 11 0 0]¡¿Eh?! ¿Disfrutas con esto, [nl]?[n][w][e]
[f 2 1][bup 8 1 65535 65535 0 0][vp 1 0 0 12 0 0][f 4 23 0 8 1 25 25]Incluso ante el peligro, tú nunca te rindes y luchas con todas tus fuerzas. ¡Como una heroína! ¡Qué pasada![n][w][e]

[msg MSG_009_0_0 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 1 0 0 13 0 0]Lo único que nos queda es seguir adelante y hacer los deberes, como siempre.[n][w][e]

[msg MSG_010_0_0 [Koromaru]]
[f 2 1][bup 9 0 65535 65535 0 0][vp 1 0 0 14 0 0]¡Guau, guau![n][w][e]

[msg MSG_011_0_0 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 1 0 0 15 0 0]¿Qué pasa, Koromaru? ¿Eh? Trae algo en la boca.[n][w][e]

[msg MSG_012_0_0 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 1 0 0 16 0 0]¿Esto es para nosotros?[n][w][e]

[msg MSG_013_0_0 [Koromaru]]
[f 2 1][bup 9 1 65535 65535 0 0][vp 1 0 0 17 0 0]¡Guau![n][w][e]

[msg MSG_014_0_0 [Ken Amada]]
[f 2 1][bup 8 1 65535 65535 0 0][vp 1 0 0 18 0 0]Ja, ja. Gracias, Koromaru. Creo que está intentando animarnos.[n][w][e]

[msg MSG_015_0_0 [Ken Amada]]
[f 2 1][bup 8 1 65535 65535 0 0][vp 1 0 0 19 0 0]No debería preocuparlo tanto.[n][w][e]
[f 2 1][bup 8 1 65535 65535 0 0][vp 1 0 0 20 0 0]¡Vale, hora de estudiar! Si tengo alguna duda, ¿puedo preguntarte, [nl]?[n][w][e]

[msg MSG_016_0_0 [Ken Amada]]
[f 2 1][bup 8 1 65535 65535 0 0][vp 1 0 0 21 0 0]¡Y... listo! ¡Ya he terminado los deberes![n][w][e]
[f 2 1][bup 8 0 65535 65535 0 0][vp 1 0 0 22 0 0][f 4 23 0 8 0 25 25]Ah, a ti te queda un rato, ¿no? ¿Te importa... que me quede aquí contigo?[n][w][e]

[msg MSG_017_0_0 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 1 0 0 23 0 0]¡No te molestaré nada! Koromaru y yo te estaremos animando. ¡A por todas![n][w][e]

[msg MND_018_0_0]
[f 2 1]Seguí estudiando con Ken[n]y con Koromaru al lado.[n][w][e]

[msg MSG_019_0_0 [Ken Amada]]
[f 2 1][bup 8 1 65535 65535 0 0][vp 1 0 0 24 0 0]Anda, ¿ya has terminado? ¡Guay![n][w][e]

[msg MSG_019_5_0 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 1 0 0 25 0 0][f 4 23 0 8 0 25 25]Koromaru ha estado con nosotros todo el... Espera, ¿dónde se ha metido?[n][w][e]

[msg MSG_020_0_0 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 1 0 0 26 0 0]¿Estabas esperando a que acabásemos?[n][w][e]

[msg MSG_021_0_0 [Ken Amada]]
[f 2 1][bup 8 1 65535 65535 0 0][vp 1 0 0 27 0 0]Creo que ya va siendo hora de dedicarle un rato.[n][w][e]

[msg MSG_022_0_0 [Ken Amada]]
[f 2 1][bup 8 1 65535 65535 0 0][vp 1 0 0 28 0 0]Gracias por estudiar conmigo. Si te parece bien, me gustaría que repitiésemos otro día.[n][w][e]

