[msg MSG_000_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 1 0 0]¿Recuerdas que nos enfrentamos a esa sombra aquí en la azotea?[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 2 0 0]Cuando estuve limpiando todo el desastre, me encontré algunas macetas y herramientas de jardinería.[n][w][e]

[msg MSG_001_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 1 65535 65535 0 0][vp 1 0 0 3 0 0]¡No pude resistirme y planté nuestro propio huertecillo![n][w][e]
[f 2 1][bup 222 1 65535 65535 0 0][vp 1 0 0 4 0 0]En fin, ¿qué te parece? No está mal, ¿eh?[n][w][e]

[sel SEL_002_0_0 top]
[f 2 1]Pinta bien.[e]
[f 2 1]¿Te gusta la jardinería?[e]
[f 2 1]¿Qué hago aquí?[e]

[msg MSG_003_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 1 65535 65535 0 0][vp 1 0 0 5 0 0]Tienes un gusto exquisito. Menos mal que mis esfuerzos no han sido en balde.[n][w][e]
[f 2 1][bup 222 1 65535 65535 0 0][vp 1 0 0 6 0 0]Lo malo es que la espalda se me ha resentido un montón desde entonces... ¿Por casualidad conoces a un buen quiropráctico?[n][w][e]

[msg MSG_004_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 7 0 0]Bueno, tampoco es que sea mi pasatiempo favorito, pero se me vino la idea a la cabeza, y hala.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 8 0 0]Con tanto espacio disponible, sería una pena no aprovecharlo.[n][w][e]

[msg MSG_005_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 4 65535 65535 0 0][vp 1 0 0 9 0 0]¿Eh? ¿No te interesan estas cosas?[n][w][e]
[f 2 1][bup 222 1 65535 65535 0 0][vp 1 0 0 10 0 0][f 4 23 0 1 1 25 25]Cuidar las plantas puede resultar muy relajante... O eso dicen. La verdad es que yo nunca lo había hecho antes.[n][w][e]

[msg MSG_006_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 11 0 0]Bueno, que me voy por las ramas. La verdad es que te he traído aquí por un motivo.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 12 0 0]Me gustaría que les dieras buen uso a estas macetas.[n][w][e]

[msg MSG_007_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 13 0 0]Aunque fui yo quien empezó con esto, me temo que no voy a tener tanto tiempo para cuidarlas como me gustaría.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 14 0 0]Se lo comenté a Mitsuru, pero no le gustó mucho la idea. Supongo que será por la educación que recibió.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 15 0 0]Además, tú cocinas en la residencia, ¿no?[n][w][e]
[f 2 1][bup 222 1 65535 65535 0 0][vp 1 0 0 16 0 0][f 4 23 0 1 1 25 25]¡Pues ahora podrás comer más sano si plantas tus propias verduras![n][w][e]

[sel SEL_008_0_0 top]
[f 2 1]Suena interesante.[e]
[f 2 1]Eso es mucho curro.[e]
[f 2 1]No sé cómo hacerlo.[e]

[msg MSG_009_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 1 65535 65535 0 0][vp 1 0 0 17 0 0]Me alegra que digas eso. Me darías una alegría si consigues sacarles buen provecho.[n][w][e]
[f 2 1][bup 222 1 65535 65535 0 0][vp 1 0 0 18 0 0]Cuando le pilles el truco, verás que se pueden hacer un montón de cosas. Huelga decir que puedes usarlas a tu conveniencia.[n][w][e]

[msg MSG_010_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 19 0 0]Ah, no te sientas obligada si no quieres hacerlo.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 20 0 0]Era por darte la oportunidad si te apetecía. Puedes venir a plantar lo que sea cuando tengas ganas.[n][w][e]

[msg MSG_011_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 21 0 0]Ah, no te preocupes.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 22 0 0]Puedes plantar un par de semillas y dejar que la naturaleza siga su curso.[n][w][e]

[msg MSG_012_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 23 0 0]Aquí tienes algunas semillas. Puedes plantarlas cuando quieras.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 24 0 0]En la ciudad puedes adquirir de diferentes tipos. Te animo a que investigues.[n][w][e]

[msg MSG_013_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 25 0 0]Bueno, eso era todo. Ahora...[n][w][e]
[f 2 1][bup 222 1 65535 65535 0 0][vp 1 0 0 26 0 0][f 4 23 0 1 1 25 25]¡Es momento de llevar este huerto a nuevas cotas! Y como colofón...[n][w][e]
[f 2 1][bup 222 1 65535 65535 0 0][vp 1 0 0 27 0 0]¡Comed verdura, guisantillos![n][w][e]

[msg MSG_037_0_0]
[f 2 1]Temp tutorial message[n][f 1 5 0]rooftop planters unlocked[n][w][e]
[f 2 1]Cuando plantes semillas, podrás cosechar algunas plantas transcurridos unos días.[n][w][e]

