[msg MSG_000_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 1 0 0]Mm, aún sigue durmiendo.[n][w][e]

[msg MSG_001_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 2 0 0]La Hora Oscura tiene lugar todos los días a medianoche. Bien podría llamarse la hora "oculta".[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 3 0 0]Durante ese tiempo, una persona normal se metamorfosea en un ataúd, pero no se entera de nada.[n][w][e]

[msg MSG_002_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 51 65535 0 0][vp 1 0 0 4 0 0]Entonces, ella debe...[n][w][e]

[msg MSG_003_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 5 0 0]Como ves, mantiene su forma humana.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 6 0 0]Duerme, pero no hay duda de que está en la Hora Oscura.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 7 0 0]Solo falta averiguar si tiene o no el potencial.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 8 0 0]Aunque, ahora que lo pienso, debería. Si no fuera así, ya se habrían cebado con ella.[n][w][e]

[msg MSG_004_0_0 [Yukari Takeba]]
[f 2 1][bup 2 3 51 65535 0 0][vp 1 0 0 9 0 0]Qué miedo...[n][w][e]

[msg MSG_005_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 10 0 0]En cualquier caso, hay que vigilarla unos días más.[n][w][e]

[msg MSG_006_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 51 65535 0 0][vp 1 0 0 11 0 0]Sí, señor.[n][w][e]

[msg MSG_007_0_0 [Yukari Takeba]]
[f 2 1][bup 2 3 51 65535 0 0][vp 1 0 0 12 0 0]Me sabe un poco mal espiarla de esta manera.[n][w][e]

