[msg MSG_000_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 3 0 65535 11008 0 0]Ah, [nl].[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0]Estaba pensando en qué hacer hoy. Como no hay entrenamiento...[n][w][e]

[msg MND_001_0_0]
[f 2 1]Parece que Yuko quiere volver a casa contigo.[n][w][e]

[msg MSG_002_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 3 0 65535 11005 0 0]Hola, [nl]. ¿Te vas a casa?[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0]Como la última vez nos interrumpieron, podríamos volver a salir si te apetece.[n][w][e]

[msg MSG_003_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 3 0 65535 11002 0 0]Ah, oye, [nl]. ¿Tienes un rato libre?[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0]Los niños tuvieron su carrera y querían hablar con nosotros.[n][w][e]

[msg MSG_004_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0]未使用ラベルだよ。[n][w][e]

[msg MSG_005_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 3 0 65535 11011 0 0]Ah, [nl]...[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0]¿Hoy vas a hacer algo? Si no, a lo mejor podrías acompañarme...[n][w][e]

[msg MSG_006_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 3 0 65535 11005 0 0]Hola, [nl]. ¿Te vas ya?[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0]¿Te apetece charlar un rato fuera? Hace buen tiempo.[n][w][e]

[msg MND_007_0_0]
[f 2 1]¿Paso un rato con Yuko después de clase?[n][w][e]

[sel SEL_008_0_0 top]
[f 2 1]Pasar un rato con ella[e]
[f 2 1]Comprobar estado de vínculo social[e]
[f 2 1]Ahora no[e]

[msg MSG_009_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 3 0 65535 11031 0 0]¡Ay, genial! ¡Gracias![n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0]No puedo confiar en el resto de miembros del equipo... Lo entiendes, ¿no, [nl]?[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0]¡Bueno, vamos al centro comercial Paulownia![n][w][e]

[msg MSG_010_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 3 0 65535 11068 0 0]¡Guay! Pues vamos a algún sitio chulo.[n][w][e]

[msg MSG_011_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 3 0 65535 11093 0 0]¡Genial! Vamos a pasárnoslo en grande en la ciudad.[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0]¿Y si vamos al centro comercial Paulownia? Podríamos pillar tarta de Chagall.[n][w][e]

[msg MSG_012_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 3 0 65535 11085 0 0]Ahora no te puedes rajar, ¿eh?[n][w][e]
[f 2 1][bup 106 3 65535 65535 0 0]Mm, ¿adónde vamos...?[n][w][e]
[f 2 1][bup 106 3 65535 65535 1 0][vp 3 0 65535 11063 0 0]¿Y si vamos a mi casa? ¡Tranqui, he recogido de antemano![n][w][e]

[msg MSG_013_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 3 0 65535 11082 0 0]Ahora no te puedes rajar, ¿eh?[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0]¿Te apetece algo de comer? Tengo unos cuantos sitios en mente, pero la decisión es tuya.[n][w][e]

[msg MSG_014_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0]Unused[n][w][e]

[msg MSG_015_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 3 0 65535 11084 0 0]¿En serio? Estupendo...[n][w][e]

[msg MSG_016_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 1 0][vp 3 0 65535 11063 0 0]O-oye, ¿quieres volver a venir a mi casa? Me gustaría darte algo...[n][w][e]
[f 2 1][bup 106 4 65535 65535 1 0]Eso es todo, ¡de verdad! Solo quiero darte una cosita de nada, ¿vale?[n][w][e]

[msg MSG_017_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 3 0 65535 11032 0 0]Gracias. Ve tú primero a la pista.[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0]Yo me voy a pasar por la sala de profesores para ver unas notas.[n][w][e]

[msg MSG_018_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 3 0 65535 11089 0 0]Madre mía... Sí que se te ve con ganas, ¿no, [nl]?[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0]Pero no me importa...[n][w][e]
[f 2 1][bup 106 1 65535 65535 1 0]¿Quieres venir a mi casa? Pero no podemos hacer ruido, para que mis padres no se enteren.[n][w][e]

[msg MSG_019_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 3 0 65535 11018 0 0]Vaya, ¿ya habías hecho planes?[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0]Sí que pareces ajetreada... En fin, ya nos veremos.[n][w][e]

[msg MSG_020_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 3 0 65535 11009 0 0]Anda, hola, [nl].[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0]Desde que me ayudaste a descubrir mis sueños, he estado estudiando mucho para hacerlos realidad.[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0][vp 3 0 65535 11093 0 0]¡Sea lo que sea lo que decidas hacer, esfuérzate al máximo! Yo siempre te apoyaré, igual que tú hiciste conmigo.[n][w][e]

[msg MND_021_0_0]
[f 2 1]Siento un vínculo irrompible con Yuko...[n][w][e]

[msg MSG_022_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 3 0 65535 11008 0 0]Ah, hola, [nl].[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0]He estado estudiando a fondo. Tú me ayudaste a descubrir mis sueños y voy a hacerlos realidad.[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0][vp 3 0 65535 11082 0 0]¡Sea lo que sea lo que decidas hacer, esfuérzate al máximo! Yo siempre te apoyaré, igual que tú hiciste conmigo.[n][w][e]

[msg MND_023_0_0]
[f 2 1]Siento un vínculo irrompible con Yuko...[n][w][e]

[msg MSG_024_5_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 3 0 65535 11065 0 0]Ah, [nl].[n][w][e]

[msg MSG_024_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0]Conoces la discoteca del centro comercial Paulownia, ¿verdad?[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0]Nunca me ha interesado, porque no me da muy buen rollo. Tengo entendido que va gente extraña.[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0]Como un tío vestido de monje que se monta la fiesta padre cada noche.[n][w][e]
[f 2 1][bup 106 3 65535 65535 0 0][vp 3 0 65535 11054 0 0]Es imposible que sea un monje de verdad, ¿no? ¿Acaso pueden beber alcohol?[n][w][e]

[msg MND_025_0_0]
[f 2 1]Yuko me ha dado una pista sobre un monje que "lo da todo" en un club nocturno.[n][w][e]

[msg MSG_026_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 3 0 65535 11064 0 0]Ah, sí. Esos críos no me dejan de dar la tabarra para que los prepare.[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0]Como hoy no hay entrenamiento, la pista está libre. No sé si debería hacerlo y punto...[n][w][e]

[msg MSG_027_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0]Por cierto, ¿te vas a marchar pronto?[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0]Como hoy no hay entrenamiento, estaba pensando en qué hacer.[n][w][e]

[msg MSG_028_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0]Por cierto, ¿te vas a marchar pronto?[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0]Como hoy no hay entrenamiento, estaba pensando en qué hacer.[n][w][e]

[msg MSG_029_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0]Oye, ¿tienes mucho lío ahora?[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0]Los niños tuvieron su carrera y querían hablar con nosotras.[n][w][e]

[msg MSG_030_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0]Unused[n][w][e]

[msg MSG_031_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0]Eh... [nl].[n][w][e]
[f 2 1][bup 106 3 65535 65535 1 0]¿Hoy vas a hacer algo? Si no, a lo mejor podrías acompañarme...[n][w][e]

[msg MSG_032_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0]Por cierto, ¿te vas ya?[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0]¿Te apetece charlar un rato fuera? Hace buen tiempo.[n][w][e]

[msg MSG_033_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 3 0 65535 11005 0 0]Ah, hola, [nl]. Por fin se han acabado los exámenes.[n][w][e]

[msg MSG_034_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0]Ah, sí. Por fin se han acabado los exámenes.[n][w][e]

[msg MSG_035_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0]Enhorabuena por haber sobrevivido. Espero que no estés agotada de tanto empollar.[n][w][e]

[msg MSG_036_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0]Enhorabuena por haber sobrevivido. Ahora tenemos tiempo para hacer lo que queramos.[n][w][e]

[msg MSG_037_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0]Enhorabuena por haber sobrevivido. Es como si se hubiera despejado la niebla... Al fin veo lo que tengo delante.[n][w][e]

[msg MSG_038_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 3 0 65535 11065 0 0]Ah, [nl].[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0]En realidad, tengo que ir a hacer compras para el equipo de atletismo. Cinta atlética y demás.[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0]Es mucho, así que me vendrían bien un par de manos más para llevarlo todo. Guiño, guiño.[n][w][e]

[msg MSG_038_5_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0]¿Ah, estás libre hoy?[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0]En realidad, tengo que ir a hacer compras para el equipo de atletismo. Cinta atlética y demás.[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0]Es mucho, así que me vendrían bien un par de manos más para llevarlo todo. Guiño, guiño.[n][w][e]

[msg MSG_039_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 3 0 65535 11008 0 0]Ah, hola, [nl].[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0]Hoy no hay entrenamiento, así que es el momento perfecto para relajarse. ¿Te apetece hacer algo?[n][w][e]

[msg MSG_039_5_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0]Hoy no hay entrenamiento, así que es el momento perfecto para relajarse. ¿Te apetece hacer algo?[n][w][e]

[msg MSG_040_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 3 0 65535 11019 0 0]¡Genial! A ver, ¿adónde vamos?[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0]¿A por algo de comer? ¿O al karaoke? Ya lo vamos viendo por el camino.[n][w][e]

[msg MSG_040_5_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 3 0 65535 11064 0 0]Oye, ¿estás libre hoy?[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0]Como la última vez nos interrumpieron, podríamos volver a salir si te apetece.[n][w][e]

[msg MSG_041_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 3 0 65535 11012 0 0]Hola, ¿qué tal va todo?[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0]Esos críos no me dejan de dar la tabarra para que los prepare.[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0]Como hoy no hay entrenamiento, la pista está libre. No sé si debería hacerlo y punto...[n][w][e]

[msg MSG_042_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 3 0 65535 11093 0 0]¡Vale, de lujo! Pues voy a pedir permiso al profesor para usar la pista.[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0]¡Nos vemos allí! Cuento contigo, entrenadora.[n][w][e]

[msg MSG_044_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 3 0 65535 11002 0 0]Anda, [nl]. ¿Tienes mucho lío hoy?[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0]Estaba pensando en seguir entrenando a esos chavales. Se los veía con muchas ganas.[n][w][e]

[msg MSG_045_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 3 0 65535 11032 0 0]¡Genial! Gracias.[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0]He investigado mucho por mi parte, así que vamos a darles un buen entrenamiento.[n][w][e]

[msg MSG_046_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 3 0 65535 11024 0 0]Ah, de acuerdo. Voy a llamarlos.[n][w][e]
[f 2 1][bup 106 3 65535 65535 0 0][vp 3 0 65535 11083 0 0]¿Cómo les habrá ido? Ahora estoy nerviosa.[n][w][e]

[msg MSG_047_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 3 0 65535 11008 0 0]Ah, [nl]. ¿Tienes algo que hacer...?[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0]Estoy prácticamente lista para montar esa fiesta, así que había pensado en hacerlo hoy.[n][w][e]

[msg MSG_047_5_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0]Ah, por cierto..., ¿tienes algo que hacer?[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0]Estoy prácticamente lista para montar esa fiesta, así que había pensado en hacerlo hoy.[n][w][e]

[msg MSG_048_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 3 0 65535 11008 0 0]Ah, [nl]. ¿Tienes algo que hacer...?[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0]Había pensado que hoy sería buen momento para montar esa fiesta.[n][w][e]

[msg MSG_048_5_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0]Ah, oye... ¿estás libre al salir de clase?[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0]Había pensado que hoy sería buen momento para montar esa fiesta.[n][w][e]

[msg MSG_049_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 3 0 65535 11065 0 0]Ah, [nl].[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0]Si te marchas ya, ¿te apetece ir a algún lado? A todos nos hace falta relajarnos de vez en cuando, ¿no?[n][w][e]

[msg MSG_049_5_0 [Yuko Nishiwaki]]
[f 2 1]Si te marchas ya, ¿te apetece ir a algún lado? A todos nos hace falta relajarnos de vez en cuando, ¿no?[n][w][e]

[msg MSG_050_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 1 0][vp 3 0 65535 11082 0 0]Guay, ¿te parece si vamos a Chagall? Allí podemos charlar tranquilamente.[n][w][e]

[msg MSG_051_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 3 0 65535 11065 0 0]Ah, [nl].[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0]Si te marchas ya, ¿te apetece ir a algún lado? A todos nos hace falta relajarnos de vez en cuando, ¿no?[n][w][e]

[msg MSG_051_5_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0]Si te marchas ya, ¿te apetece ir a algún lado? A todos nos hace falta relajarnos de vez en cuando, ¿no?[n][w][e]

[msg MSG_052_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 3 0 65535 11024 0 0]Guay, ¿te parece si vamos a Chagall? Allí podemos charlar tranquilamente.[n][w][e]

[msg MSG_141_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 3 0 65535 11015 0 0]Ah, ¿tenías que ocuparte de algo?[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0]Perdona, no sabía que estuvieras ocupada. Nos vemos.[n][w][e]

[msg MSG_142_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 3 0 65535 11015 0 0]Vaya, ¿ya tenías planes? Pues nos vemos en otro momento.[n][w][e]

[msg MSG_143_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 3 0 65535 11050 0 0]Ah, pues vaya... ¡En otra ocasión, quizá![n][w][e]

[msg MSG_144_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 3 65535 65535 0 0][vp 3 0 65535 11050 0 0]Ah, que hoy no puedes...[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0]Vale, la próxima vez será. ¡Hasta luego![n][w][e]

[msg MSG_145_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 3 65535 65535 0 0][vp 3 0 65535 11050 0 0]Ah... ¿no puedes?[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0]Sin embargo, no hay nada que podamos hacer al respecto. La próxima, tal vez.[n][w][e]

[msg MSG_146_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 3 65535 65535 0 0][vp 3 0 65535 11050 0 0]Ah, que ya habías hecho planes... Qué pena.[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0]Ya te preguntaré en otra ocasión, entonces. Nos vemos.[n][w][e]

[msg MSG_147_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 3 65535 65535 0 0][vp 3 0 65535 11083 0 0]Ah... Supongo que ha sido muy repentino.[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0]Jopé, es que tenía muchísimas ganas, ¿sabes? En fin, nos vemos.[n][w][e]

[msg MSG_148_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 3 65535 65535 0 0][vp 3 0 65535 11083 0 0]A-ah... Qué pena.[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0]Estás liada, ¿verdad? Bueno, ya nos veremos por ahí.[n][w][e]

[msg MSG_149_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 3 65535 65535 0 0][vp 3 0 65535 11083 0 0]Ah, entiendo.[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0]Perdona por preguntarte de sopetón. Ya te preguntaré en otro momento.[n][w][e]

[msg MSG_150_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 3 0 65535 11050 0 0]Ah, ¿hoy no puedes?[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0]Bueno, pues me volveré a casa. A ver si podemos en otro momento.[n][w][e]

[msg MSG_151_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 3 0 65535 11050 0 0]Ah, ¿tienes mucho qué hacer?[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0]Bueno, avísame cuando estés libre, ¿vale? Nos vemos.[n][w][e]

[msg MSG_152_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 3 0 65535 11050 0 0]Ah, vale. Pues para la próxima.[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0]A lo mejor me vuelvo a casa a estudiar. Ya nos veremos.[n][w][e]

[msg MSG_153_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 3 0 65535 11093 0 0]¡Vamos a esforzarnos a tope! ¡Yo te animaré a ti también, [nl]![n][w][e]

[msg MND_GENERAL_EVENTPLAY]
[f 2 1]Mensaje enviado por el guion. Repetición del evento del comité.[n][w][e]

[msg MND_GENERAL_PERSPNA]
[f 2 1]Siento que podemos estrechar lazos gracias a la Persona del arcano [f 2 4 2], [clr 35][f 2 4 5][clr 27].[n][w][e]

[msg MND_GENERALSELECTMSG_MAX]
[f 2 1]Siento un vínculo irrompible con [f 2 4 0]...[n][w][e]

[msg MND_GENERALMSG_BS_MAX]
[f 2 1]Siento un vínculo irrompible con la pareja de ancianos...[n][w][e]

[msg MND_GENERALSELECTMSG_RAN]
[f 2 1]Creo que mi relación con [f 2 4 0] se estrechará pronto.[n][w][e]

[msg MND_GENERALMSG_BS_RANKUP]
[f 2 1]Creo que mi relación con la pareja de ancianos se estrechará pronto.[n][w][e]

[msg MND_GENERALSELECTMSG_NOR]
[f 2 1]No creo que mi vínculo con [f 2 4 0] se fortalezca más aunque pasemos tiempo juntas...[n][w][e]

[msg MND_GENERALMSG_BS_NORMAL [Yuko Nishiwaki]]
[f 2 1]No creo que nuestro vínculo se fortalezca más aunque pasemos tiempo juntas.[n][w][e]

[msg MND_GENERALSELECTMSG_MAX_2]
[f 2 1]Parece que tu relación no puede avanzar más...[n][w][e]
[f 2 1]¿Deberíamos pasar el rato juntas igualmente?[n][w][e]

[msg MND_GENERAL_MSG_SOLO_AS]
[f 2 1]¿Paso un rato con [f 2 4 0] después de clase?[n][w][e]

[msg MND_GENERAL_MSG_SOLO_DT]
[f 2 1]¿Debería pasar el día con [f 2 4 0]?[n][w][e]

[msg MND__GENERAL_MSG_NET]
[f 2 1]¿Debería pasar tiempo en línea jugando al MMORPG con [f 2 4 0]?[n][w][e]

[msg MND_GENERAL_MSG_SOLO_NT]
[f 2 1]¿Debería pasar la tarde con [f 2 4 0]...?[n][w][e]

[sel SEL_GENERALSELECTMSG_SOL top]
[f 2 1]Pasar tiempo con [f 2 4 0][e]
[f 2 1]Comprobar vínculo social[e]
[f 2 1]Da igual[e]

[msg MND_GENERAL_MSG_MULTIPLE]
[f 2 1]¿Paso un rato en [f 2 4 1] después de clase?[n][w][e]

[msg MND_GENERAL_MSG_FASHION_]
[f 2 1]¿Paso un rato en el club de moda después de clase?[n][w][e]

[msg MND_GENERAL_MSG_BOOKSTOR]
[f 2 1]¿Debería pasar el día en la librería?[n][w][e]

[msg MND_GENERAL_MSG_BOOKSTOR_2]
[f 2 1]¿Paso un rato en la librería después de clase?[n][w][e]

[msg MND_GENERAL_MSG_MULTIPLE_2]
[f 2 1]¿Debería pasar tiempo con [f 2 4 1] esta noche...?[n][w][e]

[sel SEL_GENERALSELECTMSG_MUL top]
[f 2 1]Pasar un rato: [f 2 4 1][e]
[f 2 1]Comprobar vínculo social[e]
[f 2 1]Da igual[e]

[sel SEL_GENERALSELECTMSG_FCL top]
[f 2 1]Ir al club de moda.[e]
[f 2 1]Comprobar vínculo social[e]
[f 2 1]Da igual[e]

[sel SEL_GENERALSELECTMSG_BS top]
[f 2 1]Entrar en la librería[e]
[f 2 1]Comprobar vínculo social[e]
[f 2 1]Da igual[e]

[msg MSG_GENERAL_EXAMREWARD_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4029 0 0]Ah.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]He visto tus notas. Buen trabajo.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Toma, de parte del director.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4108 0 0]Es tu recompensa por ser capaz de compaginar los estudios y nuestras... en fin, "actividades extraescolares".[n][w][e]

[msg MND_GENERAL_EXAMREWARD_0]
[f 2 1]DEV: UNUSED LABEL[n][w][e]

[msg MND_GENERAL_EXAMREWARD_0_2]
[f 2 1]Como he sacado la nota más alta en los exámenes, he obtenido: [f 4 4 1 37 1 3].[n][w][e]

[msg MSG_GENERAL_EXAMREWARD_0_2 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4029 0 0]Ah.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]He visto tus notas. Buen trabajo.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Toma, de parte del director.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4108 0 0]Es tu recompensa por ser capaz de compaginar los estudios y nuestras... en fin, "actividades extraescolares".[n][w][e]

[msg MSG_GENERAL_EXAMREWARD_0_3 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4077 0 0]Ah, cierto. Hay algo más.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]He visto tus notas. Buen trabajo.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Toma, de parte del director.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4131 0 0]Es tu recompensa por ser capaz de compaginar los estudios y nuestras... en fin, "actividades extraescolares".[n][w][e]

[msg MND_GENERAL_EXAMREWARD_0_3]
[f 2 1]Como he sacado la nota más alta en los exámenes, he obtenido: [f 4 4 1 37 1 3].[n][w][e]

[msg MSG_GENERAL_EXAMREWARD_0_4 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4029 0 0]Ah.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]He visto tus notas. Buen trabajo.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Toma, de parte del director.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4108 0 0]Es tu recompensa por ser capaz de compaginar los estudios y nuestras... en fin, "actividades extraescolares".[n][w][e]

[msg MND_GENERAL_EXAMREWARD_0_4]
[f 2 1]DEV: UNUSED LABEL[n][w][e]

[msg MSG_GENERAL_EXAMREWARD_0_5 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4029 0 0]Ah.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]He visto tus notas... Buen trabajo.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Es laudable que continúes destacando en el instituto mientras libras arduos combates.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0]Acepta este regalo para agradecerte tus esfuerzos.[n][w][e]

[msg MND_GENERAL_EXAMREWARD_0_5]
[f 2 1]未使用ラベルです。[n][w][e]

[msg MSG_GENERAL_EXAMREWARD_0_6 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 6 65535 0 0][vp 3 0 65535 4029 0 0]Ah.[n][w][e]
[f 2 1][bup 5 0 6 65535 0 0]He visto tus notas. Buen trabajo.[n][w][e]
[f 2 1][bup 5 0 6 65535 0 0]Es laudable que continúes destacando en el instituto mientras libras arduos combates.[n][w][e]
[f 2 1][bup 5 0 6 65535 0 0]Acepta este regalo para agradecerte tus esfuerzos.[n][w][e]

[msg MND_GENERAL_EXAMREWARD_1]
[f 2 1]Como he sacado la nota más alta en los exámenes, he obtenido: [f 4 4 1 37 1 3].[n][w][e]

[msg MSG_GENERAL_EXAMREWARD_1 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4029 0 0]Ah.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]He visto tus notas. Buen trabajo.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Es laudable que continúes destacando en el instituto mientras libras arduos combates.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4108 0 0]Acepta este regalo para agradecerte tus esfuerzos.[n][w][e]

[msg MND_GENERAL_EXAMREWARD_1_2]
[f 2 1]DEV: UNUSED LABEL[n][w][e]

[msg MND_GENERAL_EXAMREWARD_1_3]
[f 2 1]Como he sacado la nota más alta en los exámenes, he obtenido: [f 4 4 1 37 1 3].[n][w][e]

