[msg MSG_000_0_0 [Yukari Takeba]]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 1 0 0]P-perdona por haberte llamado...[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 2 0 0]Eh... Tengo que pedirte un pequeño favor.[n][w][e]
[f 2 1][bup 2 10 65535 65535 0 0][vp 1 0 0 3 0 0][f 4 23 0 1 3 25 25]Mm...[n][w][e]

[msg MSG_001_0_0 [Yukari Takeba]]
[f 2 1][bup 2 2 65535 65535 0 0][vp 1 0 0 4 0 0]¡E-es mi madre![n][w][e]
[f 2 1][bup 2 2 65535 65535 0 0][vp 1 0 0 5 0 0]Q-quiero presentártela.[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0][vp 0 0 0 6 0 0][f 4 23 0 1 3 25 25]...[n][w][e]

[msg MSG_002_0_0 [Yukari Takeba]]
[f 2 1][bup 2 4 65535 65535 0 0][vp 1 0 0 7 0 0]A ver, ¡no es nada raro![n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 8 0 0][f 4 23 0 1 3 25 25]Es que... le he prometido que nos veríamos, pero me sigue dando cosa.[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 9 0 0]Si la veo... Puede que termine diciéndole cosas feas...[n][w][e]

[msg MSG_003_0_0 [Yukari Takeba]]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 10 0 0]¿Y si terminamos peor de lo que estamos? No quiero hacerla sentir mal...[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 11 0 0]Es que todavía no tengo muy claro cómo me siento.[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 12 0 0]Pero... sí que quiero verla.[n][w][e]

[msg MSG_004_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 13 0 0]Por eso pensé que sería buena idea que fueras conmigo.[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 14 0 0][f 4 23 0 1 3 25 25]No hace falta ni que hables.[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 15 0 0]Simplemente, me sentiré más segura si estás a mi lado.[n][w][e]

[msg MSG_005_0_0 [Yukari Takeba]]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 16 0 0]Si tú estás delante, creo que podría ser más amable con mi madre.[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 17 0 0]Así que... si no es mucho pedir... ¿Qué te parece?[n][w][e]

[sel SEL_006_0_0 top]
[f 2 1]Claro.[e]
[f 2 1]Eso es pasarse.[e]

[msg MSG_007_0_0 [Yukari Takeba]]
[f 2 1][bup 2 11 65535 65535 0 0][vp 1 0 0 18 0 0]¡¿De verdad?! ¡Gracias![n][w][e]
[f 2 1][bup 2 11 65535 65535 0 0][vp 1 0 0 19 0 0]¡La llamaré ahora mismo! Ya lo he retrasado demasiado tiempo.[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 20 0 0][f 4 23 0 1 3 25 25]Siento haberte metido en mis líos familiares.[n][w][e]

[msg MSG_008_0_0 [Yukari Takeba]]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 21 0 0]¡P-pues claro que sí![n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 22 0 0]Quiero decir, conocer a los padres siempre es incómodo... Pero, en mi caso, ¡es mil veces peor![n][w][e]
[f 2 1][bup 2 6 65535 65535 0 0][vp 1 0 0 23 0 0][f 4 23 0 1 6 25 25]Eso seguro...[n][w][e]
[f 2 1][bup 2 10 65535 65535 0 0][vp 0 0 0 24 0 0][f 4 23 0 1 3 25 25]...[n][w][e]

[msg MSG_009_0_0 [Yukari Takeba]]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 25 0 0]De todos modos, no vamos a vernos ya mismo. Todavía no tengo la confianza suficiente...[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 26 0 0]Le preguntaré qué día tiene libre y, si tú no tienes planes para ese día... Bueno, tú piénsatelo, ¿vale?[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0][vp 0 0 0 27 0 0]...[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 28 0 0]Me harías muy feliz si me acompañases.[n][w][e]

[msg MSG_010_0_0 [Yukari Takeba]]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 29 0 0]Oye, eh...[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 30 0 0]Seguro que piensas que dependo demasiado de ti, ¿a que sí?[n][w][e]

[sel SEL_011_0_0 top]
[f 2 1]Sí.[e]
[f 2 1]Para nada.[e]

[msg MSG_012_0_0 [Yukari Takeba]]
[f 2 1][bup 2 4 65535 65535 0 0][vp 1 0 0 31 0 0]Hala, ¡viva la sinceridad a tope![n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 32 0 0][f 4 23 0 1 1 25 25]En ese caso, lo justo es que yo también te ayude a ti cuando lo necesites, ¿no?[n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 33 0 0]¡Y así estaremos en paz![n][w][e]

[msg MSG_013_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 34 0 0]Ja, ja, ja. Sabía que dirías eso.[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 35 0 0][f 4 23 0 1 0 25 25]Bueno, ¡pero esto es recíproco! Tú también tienes que avisarme cuando necesites ayuda, ¿eh?[n][w][e]

[msg MSG_014_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 36 0 0]¿Sabes que ya casi estamos de vacaciones?[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 37 0 0]Qué rápido se ha pasado... Pronto estaremos en el último curso.[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 38 0 0]Y después, toca graduarse e ir a la universidad... Y luego, ¿ser adultos y a trabajar?[n][w][e]

[msg MSG_015_0_0 [Yukari Takeba]]
[f 2 1][bup 2 6 65535 65535 0 0][vp 1 0 0 39 0 0]Vaya, cuesta imaginarlo.[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 40 0 0][f 4 23 0 1 0 25 25]¿Tú crees... que para entonces seguiremos juntas?[n][w][e]

[sel SEL_016_0_0 top]
[f 2 1]Por supuesto.[e]
[f 2 1]A saber.[e]

[msg MSG_017_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 41 0 0]Sí...[n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 42 0 0]Yo pienso lo mismo.[n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0][vp 0 0 0 43 0 0]...[n][w][e]

[msg MSG_018_0_0 [Yukari Takeba]]
[f 2 1][bup 2 6 65535 65535 0 0][vp 1 0 0 44 0 0]Ya estás otra vez...[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 45 0 0][f 4 23 0 1 0 25 25]Entiendo lo que quieres decir. Quién sabe cómo serán las cosas en un futuro tan lejano.[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 46 0 0]Me pregunto qué nos aguarda la vida...[n][w][e]

[msg MSG_019_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 47 0 0]En fin, mejor hablemos del futuro inmediato.[n][w][e]

[msg MSG_020_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 48 0 0]¿Te acuerdas que te dije que pensases un sitio al que ir?[n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 49 0 0]Yo sigo pensando que el mejor sitio para empezar es Destinyland.[n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 50 0 0]Es una excursión de un día, así que es mucho más fácil de planificar. ¡Y también es genial para grupos grandes![n][w][e]

[msg MSG_021_0_0 [Yukari Takeba]]
[f 2 1][bup 2 11 65535 65535 0 0][vp 1 0 0 51 0 0]Ay, pero si nos decantamos por ir a la montaña, deberíamos pasar la noche allí. Ya que vamos tan lejos, mejor aprovecharlo bien.[n][w][e]
[f 2 1][bup 2 11 65535 65535 0 0][vp 1 0 0 52 0 0]Je, je. ¡Me emociono solo de pensarlo![n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 53 0 0][f 4 23 0 1 1 25 25]Contigo voy a disfrutar igual, [nl], da igual adónde vaya.[n][w][e]

[msg MSG_022_0_0 [Yukari Takeba]]
[f 2 1][bup 2 4 65535 65535 0 0][vp 1 0 0 54 0 0]¡Ay, mierda! Se me ha olvidado entregar la tarea de hoy. ¡Más vale que me ponga con eso ya![n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 55 0 0][f 4 23 0 1 1 25 25]¡Ya retomamos la conversación luego![n][w][e]

[msg MSG_023_0_0 [Yukari Takeba]]
[f 2 1][bup 2 11 65535 65535 0 0][vp 1 0 0 56 0 0]¡Resérvate algo de tiempo libre en las vacaciones de primavera![n][w][e]

