[msg MSG_000_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 156 65535 0 0][vp 1 0 0 1 0 0]¡Anda, qué yukata tan bonito![n][w][e]
[f 2 1][bup 2 0 156 65535 0 0][vp 1 0 0 2 0 0][f 4 23 0 2 0 25 25]Vaya... No sabía que fabricaban yukatas así.[n][w][e]
[f 2 1][bup 2 3 156 65535 0 0][vp 1 0 0 3 0 0][f 4 23 0 2 3 25 25]Debería haber ido a más tiendas antes de decantarme por uno...[n][w][e]

[sel SEL_001_0_0 top]
[f 2 1]Tú tienes mejor tipo.[e]
[f 2 1]Te queda genial.[e]

[msg MSG_002_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 156 65535 1 0][vp 1 0 0 4 0 0][f 5 13 7 15 2]¿En serio?[n][w][e]
[f 2 1][bup 2 0 156 65535 0 0][vp 1 0 0 5 0 0][f 4 23 0 2 0 25 25]Espera... ¿Desde cuándo dices tú ese tipo de cosas?[n][w][e]

[msg MSG_002_5_0 [Yukari Takeba]]
[f 2 1][bup 2 1 156 65535 0 0][vp 1 0 0 6 0 0]Me lo tomaré como un halago.[n][w][e]

[msg MSG_003_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 156 65535 0 0][vp 1 0 0 7 0 0]Aun así, los yukatas son... ¿Cómo lo digo? Frescos.[n][w][e]
[f 2 1][bup 2 0 156 65535 0 0][vp 1 0 0 8 0 0]Están bien cuando hace bueno, pero la tela es finísima... No sé cómo la gente se acostumbra a llevarlos.[n][w][e]

[msg MSG_003_5_0 [Yukari Takeba]]
[f 2 1][bup 2 0 156 65535 0 0][vp 1 0 0 9 0 0]Supongo que las mujeres de antaño no se preocupaban tanto.[n][w][e]

[msg MSG_004_0_0 [Yukari Takeba]]
[f 2 1][bup 2 3 156 65535 1 0][vp 1 0 0 10 0 0][f 5 13 7 5 2]¡¿Eh?! Arcias...[n][w][e]
[f 2 1][bup 2 0 156 65535 1 0][vp 1 0 0 11 0 0][f 4 23 0 2 0 25 25]Gracias, quería decir.[n][w][e]

[msg MSG_004_5_0 [Yukari Takeba]]
[f 2 1][bup 2 1 156 65535 0 0][vp 1 0 0 12 0 0]Ostras, ¡no me lo esperaba! Se me ha trabado la lengua y todo.[n][w][e]
[f 2 1][bup 2 1 156 65535 0 0][vp 1 0 0 13 0 0]Eso sí, muy amable de tu parte.[n][w][e]

[msg MSG_005_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 156 65535 0 0][vp 1 0 0 14 0 0]Aun así, los yukatas son... ¿Cómo lo digo? Frescos.[n][w][e]
[f 2 1][bup 2 0 156 65535 0 0][vp 1 0 0 15 0 0]Están bien cuando hace bueno, pero la tela es finísima... No sé cómo la gente se acostumbra a llevarlos.[n][w][e]

[msg MSG_005_5_0 [Yukari Takeba]]
[f 2 1][bup 2 0 156 65535 0 0][vp 1 0 0 16 0 0]Supongo que las mujeres de antaño no se preocupaban tanto.[n][w][e]

[msg MSG_006_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 156 65535 0 0][vp 1 0 0 17 0 0]Mmm... Qué bien huele.[n][w][e]
[f 2 1][bup 2 0 156 65535 0 0][vp 1 0 0 18 0 0][f 4 23 0 2 0 25 25]Ya es hora de cenar, ¿no? ¡Normal que tenga tanta hambre![n][w][e]

[msg MSG_007_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 156 65535 0 0][vp 1 0 0 19 0 0]Oye, [nl], ¿vamos a por takoyaki?[n][w][e]
[f 2 1][bup 2 1 156 65535 0 0][vp 1 0 0 20 0 0]Dudo que pueda comerme un plato entero yo sola. ¿Te parece si lo compartimos?[n][w][e]

[msg MSG_008_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 156 65535 0 0][vp 1 0 0 21 0 0]Hola. Una de takoyaki, por favor.[n][w][e]
[f 2 1][bup 2 1 156 65535 0 0][vp 1 0 0 22 0 0]A ver... ¿Me podría poner extra de algas y bonito en tiras? ¡Con poca mayonesa![n][w][e]

[msg MSG_009_0_0 [Vendedora de takoyaki]]
[f 2 1][vp 1 0 0 23 0 0][f 5 21 0 10]Vaya, ¡tú sí que sabes![n][w][e]
[f 2 1][vp 1 0 0 24 0 0][f 5 21 0 10]¡Oído cocina! ¡Maaarchando![n][w][e]

[msg MSG_010_0_0 [Vendedora de takoyaki]]
[f 2 1][vp 1 0 0 25 0 0]¡Ten![n][w][e]
[f 2 1][vp 1 0 0 26 0 0]Te he puesto uno más. ¡Que os aproveche a ti y a tu novia![n][w][e]

[msg MSG_011_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 156 65535 0 0][vp 1 0 0 27 0 0]¡Gracias![n][w][e]

[msg MSG_012_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 156 65535 0 0][vp 1 0 0 28 0 0]¿Has oído, [nl]? Se ha creído que eres mi novia.[n][w][e]
[f 2 1][bup 2 11 156 65535 1 0][vp 1 0 0 29 0 0][f 4 23 0 2 11 25 25]Je, je...[n][w][e]

[msg MSG_013_0_0 [Yukari Takeba]]
[f 2 1][bup 2 11 156 65535 0 0][vp 1 0 0 30 0 0]Mmm... Sabe al de Ochtofía...[n][w][e]
[f 2 1][bup 2 0 156 65535 0 0][vp 0 0 0 31 0 0][f 4 23 0 2 0 25 25]...[n][w][e]

[msg MSG_014_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 156 65535 0 0][vp 1 0 0 32 0 0]¡Lo siento! Ya sé que no hay que hablar con la boca llena.[n][w][e]
[f 2 1][bup 2 1 156 65535 0 0][vp 1 0 0 33 0 0][f 4 23 0 2 1 25 25]Quería decir que sabe como el de Octopia. Ya sabes, el sitio que está por la estación.[n][w][e]

[msg MSG_014_5_0 [Yukari Takeba]]
[f 2 1][bup 2 0 156 65535 0 0][vp 1 0 0 34 0 0]Oye, un momento. ¿Crees que la señora del puesto será la misma persona?[n][w][e]
[f 2 1][bup 2 1 156 65535 0 0][vp 1 0 0 35 0 0][f 4 23 0 2 1 25 25]En cualquier caso, está riquísimo.[n][w][e]

[msg MSG_015_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 156 65535 0 0][vp 1 0 0 36 0 0]Hala, mira las máscaras.[n][w][e]
[f 2 1][bup 2 1 156 65535 0 0][vp 1 0 0 37 0 0][f 4 23 0 2 1 25 25]¡Es la primera vez que las veo en persona![n][w][e]

[msg MSG_015_3_0 [Yukari Takeba]]
[f 2 1][bup 2 1 156 65535 0 0][vp 1 0 0 38 0 0]Ahí va, si hay una máscara de perro. Oye... ¿No te recuerda a Korocito?[n][w][e]

[msg MSG_015_5_0 [Yukari Takeba]]
[f 2 1][bup 2 0 156 65535 0 0][vp 1 0 0 39 0 0]Ah, claro... Este santuario es su hogar.[n][w][e]
[f 2 1][bup 2 0 156 65535 0 0][vp 1 0 0 40 0 0]¿Crees que hicieron la máscara en su honor?[n][w][e]

[msg MSG_015_7_0 [Yukari Takeba]]
[f 2 1][bup 2 0 156 65535 0 0][vp 1 0 0 41 0 0]A ver... La tienda solo ha abierto por el festival. Igual me lo estoy imaginando.[n][w][e]

[msg MSG_016_0_0 [Asistente de juego]]
[f 2 1][vp 1 0 0 42 0 0][f 5 21 0 11]¡Eh, vosotras dos! ¿Os gustaría probar suerte?[n][w][e]
[f 2 1][vp 1 0 0 43 0 0][f 5 21 0 11]¡Tendréis un bonito recuerdo! La suerte os sonríe, ¡todavía quedan un montón de premios![n][w][e]

[msg MSG_017_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 156 65535 0 0][vp 1 0 0 44 0 0]Un montón de premios... ¿Qué te parece?[n][w][e]
[f 2 1][bup 2 1 156 65535 0 0][vp 1 0 0 45 0 0]Dice que la suerte nos sonríe. ¿Quieres probar?[n][w][e]
[f 2 1][bup 2 1 156 65535 0 0][vp 1 0 0 46 0 0]¡Yo te miro![n][w][e]

[msg MND_018_0_0]
[f 2 1]La caja está llena de papeletas[n]triangulares de la lotería.[n][w][e]

[sel SEL_019_0_0 top]
[f 2 1]Coger uno de arriba[e]
[f 2 1]Meter la mano hasta el fondo[e]

[msg MSG_020_0_0 [Asistente de juego]]
[f 2 1][vp 1 0 0 47 0 0][f 5 21 0 11]¡Enhorabuena! ¡Has ganado![n][w][e]
[f 2 1][vp 1 0 0 48 0 0][f 5 21 0 11]¡Hala! ¡Menuda suerte la tuya para ganar en el primer intento![n][w][e]
[f 2 1][vp 1 0 0 49 0 0][f 5 21 0 11]Aquí tienes tu premio. ¡Disfrútalo![n][w][e]

[msg MND_021_0_0]
[f 2 1]（アイテム名）を受け取った。[n][w][e]

[msg MSG_022_0_0 [Asistente de juego]]
[f 2 1][vp 1 0 0 50 0 0][f 5 21 0 11]¡Enhorabuena! ¡Has ganado![n][w][e]
[f 2 1][vp 1 0 0 51 0 0][f 5 21 0 11]¡Hala! ¡Menuda suerte la tuya para ganar en el primer intento![n][w][e]
[f 2 1][vp 1 0 0 52 0 0][f 5 21 0 11]Aquí tienes tu premio. ¡Disfrútalo![n][w][e]

[msg MND_023_0_0]
[f 2 1]（アイテム名）を受け取った。[n][w][e]

[msg MSG_024_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 156 65535 0 0][vp 1 0 0 53 0 0]¡Genial, [nl]![n][w][e]
[f 2 1][bup 2 0 156 65535 0 0][vp 1 0 0 54 0 0][f 4 23 0 2 0 25 25]Siempre he pensado que estas cosas estaban trucadas.[n][w][e]
[f 2 1][bup 2 0 156 65535 0 0][vp 1 0 0 55 0 0]Es la primera vez que veo a alguien ganar un premio en algo así.[n][w][e]

[msg MSG_025_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 156 65535 0 0][vp 1 0 0 56 0 0]Pensé que nos encontraríamos con algún compañero de clase, pero va a ser que no.[n][w][e]
[f 2 1][bup 2 1 156 65535 0 0][vp 1 0 0 57 0 0][f 4 23 0 2 1 25 25]He de reconocer que estoy algo decepcionada.[n][w][e]
[f 2 1][bup 2 1 156 65535 0 0][vp 1 0 0 58 0 0][f 4 23 0 2 1 25 25]Aun así, me alegro de que hayamos disfrutado del festival.[n][w][e]

[msg MSG_026_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 156 65535 0 0][vp 1 0 0 59 0 0]¡Gracias por lo de hoy! Me lo he pasado genial, [nl].[n][w][e]
[f 2 1][bup 2 1 156 65535 0 0][vp 1 0 0 60 0 0]Tenemos que volver a quedar.[n][w][e]
[f 2 1][bup 2 11 156 65535 0 0][vp 1 0 0 61 0 0][f 4 23 0 2 11 25 25]Je, je...[n][w][e]

[msg MND_027_0_0]
[f 2 1]Hemos decidido volver a la residencia.[n][w][e]

