[msg MSG_000_0_0 [Anciano]]
[f 2 1][bup 103 0 65535 65535 0 0][vp 3 0 65535 10424 0 0]Ah, ¿eres alumna de un instituto de la zona?[n][w][e]
[f 2 1][bup 103 0 65535 65535 0 0]Bueno, ¡te alegrará saber que puedes comer sushi de buena calidad por aquí cerca! ¡Lo hago yo mismo![n][w][e]
[f 2 1][bup 103 1 65535 65535 0 0]¡Pásate algún día si quieres! Bueno, en realidad aún estamos reformando el local. Lo siento.[n][w][e]

[msg MSG_004_0_0 [Anciana]]
[f 2 1][bup 104 0 65535 65535 0 0][vp 3 0 65535 10607 0 0]Esto es una librería, no un restaurante de sushi.[n][w][e]
[f 2 1][bup 104 0 65535 65535 0 0]Lo siento. Siempre está igual.[n][w][e]

