[msg MSG_000_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 3 0 65535 1086 0 0][f 4 23 1 2 1 25 25]Oye, muy buen trabajo, [nl]. Tienes madera de líder.[n][w][e]

[sel SEL_001_0_0 top]
[f 2 1]Claro que sí.[e]
[f 2 1]Solo he tenido suerte.[e]
[f 2 1]¿Quieres probar?[e]

[msg MSG_002_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 3 0 65535 1095 0 0]Ja, ja. A ti te sobra confianza, ¿no? Aunque lo cierto es que ver que tienes esa faceta resulta alentador.[n][w][e]

[msg MSG_003_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 3 0 65535 1104 0 0]¿Ah, sí? Pues ya sabes lo que dicen: la suerte se entrena.[n][w][e]

[msg MSG_004_0_0 [Yukari Takeba]]
[f 2 1][bup 2 4 65535 65535 0 0][vp 3 0 65535 1099 0 0][f 4 23 1 2 4 25 25]¿Quién, yo? Eh... No, gracias. Es mucha responsabilidad.[n][w][e]
[f 2 1][bup 2 6 65535 65535 0 0][f 4 23 1 2 6 25 25]A diferencia de ti, me rendiría a la hora de la verdad. Pierdo la calma con demasiada facilidad.[n][w][e]

[msg MSG_005_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][f 4 23 1 2 1 25 25]Bueno, ¿nos vamos? Después de ti, líder.[n][w][e]

[msg MSG_006_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 3 0 65535 1114 0 0]Buen trabajo. Los guardianes son duros de pelar, ¿eh?[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0]Quizá va siendo hora de dejarlo por hoy. ¿Tú cómo lo ves?[n][w][e]

[sel SEL_007_0_0 top]
[f 2 1]Sí, volvamos.[e]
[f 2 1]No he hecho más que empezar.[e]
[f 2 1]¿Quieres que volvamos?[e]

[msg MSG_008_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 3 0 65535 1025 0 0][f 4 23 1 2 1 25 25]¡Guay! Vamos a la entrada.[n][w][e]

[msg MSG_009_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 3 0 65535 1107 0 0][f 4 23 1 2 1 25 25]Cuánta motivación. Vale, a ver hasta dónde llegamos.[n][w][e]

[msg MSG_010_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 3 0 65535 1062 0 0]Ah, no lo decía por eso. No estoy cansada. Solo he pensado que era un buen momento para dejarlo.[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0]Pero estoy segura de que has planeado la expedición al más mínimo detalle, así que tú decides.[n][w][e]

[msg MSG_011_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 3 0 65535 1062 0 0]Fiu, ahora podemos cruzar.[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0]Estamos en racha. ¿Tú qué dices, [nl]? ¿Seguimos?[n][w][e]

[sel SEL_012_0_0 top]
[f 2 1]Sí, sigamos así.[e]
[f 2 1]Dejémoslo aquí.[e]
[f 2 1]Te veo motivada.[e]

[msg MSG_013_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 3 0 65535 1116 0 0][f 4 23 1 2 1 25 25]¡Eso es! ¿Crees que llegaremos al próximo guardián?[n][w][e]

[msg MSG_014_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 3 0 65535 1068 0 0][f 4 23 1 2 1 25 25]¿Estás cansada? Los guardianes son de armas tomar, ¿eh?[n][w][e]

[msg MSG_015_0_0 [Yukari Takeba]]
[f 2 1][bup 2 6 65535 65535 0 0][vp 3 0 65535 1061 0 0][f 4 23 1 2 6 25 25]Ya, supongo... Pero, dicho así, parece que normalmente no lo soy.[n][w][e]

[msg MSG_016_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][f 4 23 1 2 1 25 25]En fin, ¿nos vamos?[n][w][e]

[msg MSG_017_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 3 0 65535 1114 0 0]No hace mucho, creía que no tendríamos nada que hacer contra un enemigo tan poderoso.[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0]¿No te parece que nos hemos vuelto mucho más fuertes?[n][w][e]

[sel SEL_018_0_0 top]
[f 2 1]Por supuesto.[e]
[f 2 1]Hay margen de mejora.[e]
[f 2 1]No te dejes llevar.[e]

[msg MSG_019_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 3 0 65535 1096 0 0][f 4 23 1 2 1 25 25]Ja, ja. Gracias por el voto de confianza. Es muy alentador viniendo de ti.[n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0]Cuando empezamos, me costaba la vida invocar a mi Persona.[n][w][e]

[msg MSG_020_0_0 [Yukari Takeba]]
[f 2 1][bup 2 6 65535 65535 0 0][vp 3 0 65535 1122 0 0][f 4 23 1 2 6 25 25]Jopé, no estaría de más que me piropearas de vez en cuando.[n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0][f 4 23 1 2 1 25 25]Estoy de cooooña. En realidad, prefiero las críticas constructivas.[n][w][e]

[msg MSG_021_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 3 0 65535 1025 0 0]Pues claro. No somos las únicas que nos estamos volviendo fuertes.[n][w][e]
[f 2 1][bup 2 6 65535 65535 0 0][f 4 23 1 2 6 25 25]No dejaré que se me suba a la cabeza..., a diferencia de otro que yo me sé.[n][w][e]

[msg MSG_022_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][f 4 23 1 2 0 25 25]Bueno, sigamos. ¿Vamos a por el siguiente?[n][w][e]

[msg MSG_023_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 3 0 65535 1086 0 0][f 4 23 1 2 1 25 25]Fiu, hemos ganado... Siento que hoy lo estoy bordando.[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][f 4 23 1 2 0 25 25]Quizá es porque mi horóscopo decía que los libra tendríamos mucha suerte.[n][w][e]

[sel SEL_024_0_0 top]
[f 2 1]Sí, yo creo que sí.[e]
[f 2 1]Eso no tiene nada que ver.[e]
[f 2 1]Te leeré la mano.[e]

[msg MSG_025_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 3 0 65535 1095 0 0][f 4 23 1 2 1 25 25]Ja, ja. ¿Eres de las que se tragan las supersticiones? Te entiendo. Aunque seas escéptico, se te queda en la cabeza.[n][w][e]

[msg MSG_026_0_0 [Yukari Takeba]]
[f 2 1][bup 2 6 65535 65535 0 0][vp 3 0 65535 1119 0 0][f 4 23 1 2 6 25 25]Ahí llevas razón. Si todo fuera tan sencillo...[n][w][e]

[msg MSG_027_0_0 [Yukari Takeba]]
[f 2 1][bup 2 4 65535 65535 0 0][vp 3 0 65535 1099 0 0][f 4 23 1 2 4 25 25]¿En serio? No me imaginaba que te interesaría...[n][w][e]
[f 2 1][bup 2 2 65535 65535 0 0][f 4 23 1 2 2 25 25]Eh... ¿No será esto un ardid para cogerme de la mano?[n][w][e]
[f 2 1][bup 2 6 65535 65535 0 0][f 4 23 1 2 6 25 25]Bah, a quién quiero engañar... Tú no eres Junpei.[n][w][e]

[msg MSG_028_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][f 4 23 1 2 0 25 25]Bueno, dicen que la suerte se entrena, ¿no? No pasa nada por creer en buenos augurios...[n][w][e]

[msg MSG_029_0_0 [Yukari Takeba]]
[f 2 1][bup 2 4 65535 65535 0 1][f 4 23 1 2 4 25 25]Un momento... ¿Hemos cambiado de fecha?[n][w][e]

[msg MSG_030_0_0 [Yukari Takeba]]
[f 2 1][bup 2 4 65535 65535 0 1]¿El horóscopo cambia durante la Hora Oscura? Uf, la curiosidad me está matando.[n][w][e]

[msg MSG_031_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2088 0 0][f 4 23 1 3 1 25 25]¡Toooma ya! ¡Mirad cómo parto la pana![n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]Bueno, tú tampoco lo has hecho nada mal. Sigue así, tía.[n][w][e]

[sel SEL_032_0_0 top]
[f 2 1]Ah, jo. Gracias.[e]
[f 2 1]Te lo tienes muy creído.[e]
[f 2 1]Y lo mismo va para ti, tío.[e]

[msg MSG_033_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2029 0 0]Recuerda, colega. En tiempos así, el trabajo en equipo es fundamental.[n][w][e]

[msg MSG_034_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2036 0 0]Ja, ja. Solo intento animarte, tía. No te preocupes, vas a seguir cortando el bacalao.[n][w][e]

[msg MSG_035_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2026 0 0]¡Eh, tía! Yo te cubro, así que sigamos adelante juntos.[n][w][e]

[msg MSG_036_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0]Vale, ¡en marcha![n][w][e]

[msg MSG_037_0_0 [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0][vp 3 0 65535 2115 0 0][f 4 23 1 3 3 25 25]Puf... Estos bichos dan mucha guerra en comparación con las sombras de tres al cuarto.[n][w][e]
[f 2 1][bup 3 3 65535 65535 0 0]A ver, aún me queda combustible, pero no estaría de más hacer una parada en boxes.[n][w][e]

[sel SEL_038_0_0 top]
[f 2 1]Sí, volvamos.[e]
[f 2 1]Ahora mismo no.[e]
[f 2 1]¿Seguro que no estás cansado?[e]

[msg MSG_039_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2095 0 0][f 4 23 1 3 1 25 25]Je, je, je. Hay que saber cuál es el mejor momento para retirarse, ¿verdad?[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]Venga, te echo una carrera hasta el teletransportador más cercano. Preparados, listos... ¡ya![n][w][e]

[msg MSG_040_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 65535 65535 0 0][vp 3 0 65535 2099 0 0][f 4 23 1 3 4 25 25]¿Quééé? ¿En serio? Mira que eres aplicada...[n][w][e]
[f 2 1][bup 3 3 65535 65535 0 0][f 4 23 1 3 3 25 25]En fin, te haré compañía, tía.[n][w][e]

[msg MSG_041_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 65535 65535 0 0][vp 3 0 65535 2085 0 0][f 4 23 1 3 4 25 25]E-eh, alto ahí... Me preocupaba que fueras tú la que se quedara sin gasofa.[n][w][e]
[f 2 1][bup 3 3 65535 65535 0 0][f 4 23 1 3 3 25 25]Si tienes ganas de seguir, yo te cubro. Pero no te fuerces, ¿va?[n][w][e]

[msg MSG_042_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2096 0 0][f 4 23 1 3 1 25 25]¡Y eso es todo, amigos![n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]Somos la caña. ¡Nada nos puede detener! ¡Adelante, Sociedad extraescolar de ejecución de sombras![n][w][e]

[sel SEL_043_0_0 top]
[f 2 1]Vamos.[e]
[f 2 1]Volvamos.[e]
[f 2 1]Sigamos hasta la cima.[e]

[msg MSG_044_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2108 0 0]Da gusto verte rindiendo así de bien. Entre tú y yo, creo que el próximo combate lo tenemos ganado.[n][w][e]

[msg MSG_045_0_0 [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0][vp 3 0 65535 2101 0 0][f 4 23 1 3 3 25 25]Venga... No me digas que te rindes ya.[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0][f 4 23 1 3 1 25 25]En fin, es tan buen momento como otro para hacer una pausa. Ya tendremos tiempo para la segunda mitad de la Maratón de Junpei.[n][w][e]

[msg MSG_046_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2110 0 0]Qué ambiciosa, chica. ¡Yo te apoyo al 100 %![n][w][e]

[msg MSG_047_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0]Guay, pues vamos.[n][w][e]

[msg MSG_048_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2111 0 0]¿Es cosa mía o las sombras se están poniendo las pilas? ¿Cuándo van a dejar de hacerse más fuertes?[n][w][e]

[sel SEL_049_0_0 top]
[f 2 1]No quiero saberlo.[e]
[f 2 1]Ni idea.[e]
[f 2 1]Tenemos que ponernos serios.[e]

[msg MSG_050_0_0 [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0][vp 3 0 65535 2115 0 0][f 4 23 1 3 3 25 25]Y que lo digas. Quizá no tengan límite, pero tenemos que abrirnos paso.[n][w][e]

[msg MSG_051_0_0 [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0][vp 3 0 65535 2115 0 0][f 4 23 1 3 3 25 25]Bueno, pues olvidémonos de que las cosas vayan a ser más fáciles de aquí en adelante...[n][w][e]

[msg MSG_052_0_0 [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0][vp 3 0 65535 2115 0 0][f 4 23 1 3 3 25 25]Ya, bueno, pero es más fácil decirlo que hacerlo, ¿eh?[n][w][e]

[msg MSG_053_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 65535 65535 0 0][f 4 23 1 3 4 25 25]Oye, no te confundas, no les tengo miedo ni nada, ¿vale?[n][w][e]
[f 2 1][bup 3 2 65535 65535 0 0][f 4 23 1 3 2 25 25]Qué diantres, si ya estoy tramando planes para rematarlas con estilo...[n][w][e]

[msg MSG_054_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 65535 65535 0 0][f 4 23 1 3 4 25 25]¿Por qué me miras así? ¿Es que no me crees?[n][w][e]

[msg MSG_055_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2086 0 0][f 4 23 1 3 1 25 25]Fiu... Los hemos machacado.[n][w][e]
[f 2 1][bup 3 9 65535 65535 0 0][f 4 23 1 3 9 25 25]Si esto fuera un partido de béisbol, podríamos decir que Iori, el as del equipo, jugó por todos y dejó sin opciones al rival.[n][w][e]

[sel SEL_056_0_0 top]
[f 2 1]No lo pillo.[e]
[f 2 1]Esto no es béisbol.[e]
[f 2 1]Pero yo soy la as.[e]

[msg MSG_057_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2075 0 0][f 4 23 1 3 1 25 25]Vale, digamos que fui el cuarto bate y me marqué un home run de aquí te espero para embolsarnos una victoria tremebunda.[n][w][e]

[msg MSG_058_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 65535 65535 0 0][vp 3 0 65535 2132 0 0][f 4 23 1 3 4 25 25]¡Pues claro que no! ¿Es que no sabes lo que es una analogía?[n][w][e]

[msg MSG_059_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2110 0 0][f 4 23 1 3 1 25 25]Anda, mira cómo te gusta fanfarronear... Pero en el Salón de la Fama hay espacio para los dos.[n][w][e]

[msg MSG_060_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][f 4 23 1 3 1 25 25]En fin, a donde quiero llegar es que necesitas un equipo con bateadores fuertes y un toril potente para...[n][w][e]
[f 2 1][bup 3 4 65535 65535 0 0][f 4 23 1 3 4 25 25]Ostras, ¿de qué estábamos hablando?[n][w][e]

[msg MSG_061_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 3 0 65535 3086 0 0]¡Así se hace, [nl]![n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0]Tus instrucciones han sido certeras y has logrado mantener el temple contra un oponente muy duro.[n][w][e]

[sel SEL_062_0_0 top]
[f 2 1]La duda ofende.[e]
[f 2 1]No necesariamente.[e]
[f 2 1]Sí, ha sido duro.[e]

[msg MSG_063_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 1 65535 65535 0 0][vp 3 0 65535 3106 0 0][f 4 23 1 4 1 25 25]Je, je. Muy bien, maestra. Veo que estamos en buenas manos.[n][w][e]

[msg MSG_064_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 1 65535 65535 0 0][vp 3 0 65535 3094 0 0][f 4 23 1 4 1 25 25]Ja, ja, ¿así que has puesto cara de póquer todo este tiempo? Brillante.[n][w][e]

[msg MSG_065_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 1 65535 65535 0 0][vp 3 0 65535 3088 0 0][f 4 23 1 4 1 25 25]No hace falta que seas tan humilde solo porque soy mayor.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0][f 4 23 1 4 0 25 25]Pero recuerda que en el campo de batalla no hay jerarquías. Todos somos iguales, así que no te cortes.[n][w][e]

[msg MSG_066_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][f 4 23 1 4 0 25 25]Venga, avancemos. Permanezcamos ojo avizor.[n][w][e]

[msg MSG_067_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 3 0 65535 3085 0 0]Estupendo. Ya podemos avanzar.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0]Aunque siempre podemos dar la vuelta. ¿Qué opinas, [nl]?[n][w][e]

[sel SEL_068_0_0 top]
[f 2 1]Volvamos.[e]
[f 2 1]Sigamos.[e]
[f 2 1]Deja que me lo piense...[e]

[msg MSG_069_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 3 0 65535 3113 0 0]Bien, pues vamos a reagruparnos.[n][w][e]

[msg MSG_070_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 3 0 65535 3113 0 0]Recibido. Haremos las cosas a tu ritmo.[n][w][e]

[msg MSG_071_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 3 0 65535 3113 0 0]No te preocupes, adelante. Tómate el tiempo que necesites para analizar la situación. No hay prisa.[n][w][e]

[msg MSG_072_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 3 0 65535 3086 0 0]Genial, vía despejada.[n][w][e]
[f 2 1][bup 4 9 65535 65535 0 0][f 4 23 1 4 9 25 25]¿Cuál es el plan? Me apunto a darle una tunda al siguiente guardián si hace falta.[n][w][e]

[sel SEL_073_0_0 top]
[f 2 1]Vamos allá.[e]
[f 2 1]No sé yo...[e]
[f 2 1]Deja que me lo piense...[e]

[msg MSG_074_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 9 65535 65535 0 0][vp 3 0 65535 3108 0 0]Así me gusta. Me comprometo a seguir tirando del carro si tú también lo haces.[n][w][e]

[msg MSG_075_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 1 65535 65535 0 0][vp 3 0 65535 3045 0 0][f 4 23 1 4 1 25 25]¿Y eso? ¿Qué pasa, estás cansada?[n][w][e]
[f 2 1][bup 4 1 65535 65535 0 0]No pasa nada, no tienes por qué forzarte a avanzar. Nuestros oponentes no se van a ir a ningún sitio.[n][w][e]

[msg MSG_076_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 1 65535 65535 0 0][vp 3 0 65535 3028 0 0]Claro, adelante. Aún tengo fuerzas.[n][w][e]

[msg MSG_077_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][f 4 23 1 4 0 25 25]Muy bien, vámonos. Contamos contigo.[n][w][e]

[msg MSG_078_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 1 65535 65535 0 0][vp 3 0 65535 3002 0 0][f 4 23 1 4 1 25 25]El último oponente nos dio mucha guerra. Fue un buen combate.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0][f 4 23 1 4 0 25 25]Cuanto más duro es el oponente, más te emocionas. ¿No estás de acuerdo?[n][w][e]

[sel SEL_079_0_0 top]
[f 2 1]Sí, te entiendo.[e]
[f 2 1]Los prefiero más débiles.[e]
[f 2 1]Depende de la situación.[e]

[msg MSG_080_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 9 65535 65535 0 0][vp 3 0 65535 3025 0 0][f 4 23 1 4 9 25 25]Me alegra ver que coincidimos. Después de todo, la única forma de hacerse fuerte es superando tus límites.[n][w][e]

[msg MSG_081_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 1 65535 65535 0 0][vp 3 0 65535 3047 0 0][f 4 23 1 4 1 25 25]¿Tú crees? Mmm... Encargarse de los oponentes débiles podría ser un buen entrenamiento.[n][w][e]

[msg MSG_082_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 3 0 65535 3028 0 0][f 4 23 1 4 0 25 25]Tienes razón. Poco vas a sacar luchando contra un oponente que está fuera de tu alcance.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0]Sin embargo, a veces luchar contra un peso pesado sirve para dar un paso adelante.[n][w][e]

[msg MSG_083_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][f 4 23 1 4 0 25 25]Bueno..., ¿tienes ganas de descubrir lo que nos espera?[n][w][e]

[msg MSG_084_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 3 0 65535 3108 0 0]Por muchas veces que te vea luchar, sigo sin creérmelo.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0]¿Cómo diantres cambias de Persona a voluntad?[n][w][e]

[sel SEL_085_0_0 top]
[f 2 1]A mí también me ha sorprendido.[e]
[f 2 1]Dicen que no es frecuente.[e]
[f 2 1]¿Quieres que te preste uno?[e]

[msg MSG_086_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 3 0 65535 3106 0 0]Lo que tú digas, pero te mueves como pez al agua. ¿Sabes qué? Creo que tienes algo especial.[n][w][e]

[msg MSG_087_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 3 0 65535 3027 0 0]Eres rara, por así decirlo.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0]Pero no puedes ser la única... Seguro que hay alguien que tiene tu misma habilidad.[n][w][e]

[msg MSG_088_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 1 65535 65535 0 0][vp 3 0 65535 3131 0 0][f 4 23 1 4 1 25 25]Ja, ja. Agradezco la oferta, pero me temo que ya estoy hasta arriba con lo mío.[n][w][e]

[msg MSG_089_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][f 4 23 1 4 0 25 25]De todos modos, contigo al frente tendremos más estrategias en combate, así que lo aprovecharemos.[n][w][e]

[msg MSG_090_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4107 0 0]Magnífico, una victoria perfecta. Y todo gracias a tus órdenes precisas, [nl].[n][w][e]

[sel SEL_091_0_0 top]
[f 2 1]Ha ido bien.[e]
[f 2 1]No he hecho más que empezar.[e]
[f 2 1]Esto es agotador.[e]

[msg MSG_092_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4113 0 0][f 4 23 1 5 1 25 25]Estoy segura de que es difícil dirigir al equipo, pero resulta evidente que estás a la altura.[n][w][e]

[msg MSG_093_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4106 0 0][f 4 23 1 5 1 25 25]Admiro tu tenacidad. Ese ímpetu es lo que nos llevará adelante.[n][w][e]

[msg MSG_094_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4131 0 0][f 4 23 1 5 1 25 25]Desde luego. Hacer el papel de líder requiere mente y materia.[n][w][e]

[msg MSG_095_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][f 4 23 1 5 0 25 25]Por supuesto, te ayudaré en todo lo que pueda. Ahora bien, no actúes con imprudencia.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Venga, sigamos.[n][w][e]

[msg MSG_096_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4112 0 0]No sé cómo, pero lo hemos conseguido. Los guardianes son algo fuera de lo común.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Este sería un buen momento para reagruparnos, pero ¿tú qué dices?[n][w][e]

[sel SEL_097_0_0 top]
[f 2 1]Volvamos.[e]
[f 2 1]Me gustaría seguir.[e]
[f 2 1]No estoy segura.[e]

[msg MSG_098_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4115 0 0]Por mí, bien. Hay que prepararse para cualquier contingencia.[n][w][e]

[msg MSG_099_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4113 0 0][f 4 23 1 5 1 25 25]Entiendo que quieres aprovechar la racha para hacernos con otra victoria, ¿no? Muy bien, lo dejo a tu criterio.[n][w][e]

[msg MSG_100_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4065 0 0]Muy bien. No hay criterio estipulado sobre cuándo retirarse.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][f 4 23 1 5 1 25 25]Decidas lo que decidas, lo acataré. Tú mandas.[n][w][e]

[msg MSG_101_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4085 0 0]Bien, vía despejada. ¿Avanzamos?[n][w][e]

[sel SEL_102_0_0 top]
[f 2 1]Por supuesto.[e]
[f 2 1]Volvamos.[e]
[f 2 1]Solo si podemos todos.[e]

[msg MSG_103_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4113 0 0][f 4 23 1 5 1 25 25]Te veo en muy buena forma esta noche. Bueno, volvamos al lío.[n][w][e]

[msg MSG_104_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4113 0 0]Muy bien. Vayamos a la entrada.[n][w][e]

[msg MSG_105_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4113 0 0][f 4 23 1 5 1 25 25]Por supuesto. Nada que objetar.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][f 4 23 1 5 0 25 25]Puedo respirar tranquila contigo al mando. Sigue así.[n][w][e]

[msg MSG_106_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4112 0 0]¿Cuántos guardianes llevamos? Cada vez se vuelven más despiadados, ¿no crees?[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]De ahora en adelante, te enfrentarás a desafíos tácticos de mayor calibre, pero confío en que darás la talla.[n][w][e]

[sel SEL_107_0_0 top]
[f 2 1]Yo me encargo.[e]
[f 2 1]No sé yo...[e]
[f 2 1]No queda más remedio.[e]

[msg MSG_108_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4039 0 0]Huelga decir que haremos todo lo posible por apoyarte.[n][w][e]

[msg MSG_109_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4045 0 0][f 4 23 1 5 1 25 25]Bueno, sé que puedes lidiar con ello. No dudes de tu habilidad y sigue como hasta ahora.[n][w][e]

[msg MSG_110_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4024 0 0][f 4 23 1 5 1 25 25]Me temo que no, pero confía en mí, eres más que capaz. Y yo estaré contigo en todo momento.[n][w][e]

[msg MSG_111_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][f 4 23 1 5 0 25 25]¿Seguimos, pues?[n][w][e]

[msg MSG_112_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4112 0 0]Ahora podremos avanzar, pero... ¿cuántas plantas tendrá esta torre?[n][w][e]

[sel SEL_113_0_0 top]
[f 2 1]Ni idea.[e]
[f 2 1]Podríamos estar cerca.[e]
[f 2 1]No sirve de nada darle vueltas.[e]

[msg MSG_114_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4028 0 0]Creo que aún nos queda un largo camino por delante, pero parte de nuestra labor es asegurarnos.[n][w][e]

[msg MSG_115_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4027 0 0]Desearía que fuera verdad, pero tiene pinta de que aún nos queda mucho.[n][w][e]

[msg MSG_116_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4027 0 0]Es cierto. Lo que sí tenemos claro es que, pase lo que pase, llegaremos a nuestro objetivo.[n][w][e]

[msg MSG_117_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0]No estoy perdiendo el valor, que conste.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Llegar tan lejos ya es un hito de lo más extraordinario.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Por ahora, sigamos allanando el camino.[n][w][e]

[msg MSG_118_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6012 0 0]Sombra enemiga aniquilada. Tus dotes de toma de decisiones son superlativas, [nf].[n][w][e]

[sel SEL_119_0_0 top]
[f 2 1]Ha ido bien.[e]
[f 2 1]Ha sido suerte.[e]
[f 2 1]Lo has hecho genial, Aigis.[e]

[msg MSG_120_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6024 0 0]Sí, ha resultado muy útil aprender que la coordinación del equipo es tan importante como las fortalezas individuales.[n][w][e]

[msg MSG_121_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6037 0 0]Las probabilidades de que la operación se simplifique por casualidad son muy bajas. Sospecho que estás siendo humilde, como de costumbre.[n][w][e]

[msg MSG_122_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6039 0 0]Gracias. El combate ha sido coser y cantar, como se suele decir.[n][w][e]

[msg MSG_123_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0]Retomemos la exploración.[n][w][e]

[msg MSG_124_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6012 0 0]Amenaza de alto nivel eliminada. ¿Cuál es el estado actual del equipo?[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0]Si sentís fatiga, recomiendo encarecidamente volver pronto.[n][w][e]

[sel SEL_125_0_0 top]
[f 2 1]Dejémoslo por hoy.[e]
[f 2 1]Puedo seguir.[e]
[f 2 1]A mí me da igual.[e]

[msg MSG_126_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6024 0 0]Entendido. Volvamos a la entrada.[n][w][e]

[msg MSG_127_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6024 0 0]Es muy "magnifique", como se suele decir. Bueno, retomemos la exploración.[n][w][e]

[msg MSG_128_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6024 0 0]Es momento de ser resolutivo. Tienes la última palabra, [nf].[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0]Decidas lo que decidas, estaré a tu lado.[n][w][e]

[msg MSG_129_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6012 0 0]Sombra de guardián eliminada. Este parece un buen momento para detenernos...[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0]¿O prefieres que sigamos adelante?[n][w][e]

[sel SEL_130_0_0 top]
[f 2 1]Vale.[e]
[f 2 1]Quiero irme a casa.[e]
[f 2 1]Estás deseándolo.[e]

[msg MSG_131_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6024 0 0]Entendido. En ese caso, vamos a rocanrolear, como se suele decir.[n][w][e]

[msg MSG_132_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6024 0 0]Entiendo. Muy bien, volvamos para recuperarnos de cara a la próxima batalla.[n][w][e]

[msg MSG_133_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6030 0 0]Por supuesto. Después de todo, esta es mi misión.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0]¿Nos vamos, [nf]?[n][w][e]

[msg MSG_134_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6012 0 0]Amenaza eliminada. Misión cumplida.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0]Por cierto, ¿te has acostumbrado a los relevos y a la teúrgia en combate?[n][w][e]

[sel SEL_135_0_0 top]
[f 2 1]Hasta cierto punto.[e]
[f 2 1]No he tenido que hacerlo.[e]
[f 2 1]Parece instintivo.[e]

[msg MSG_136_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6024 0 0]Ambos son muy útiles en una batalla. Lo mejor sería que emplearas esas estrategias de forma óptima.[n][w][e]

[msg MSG_137_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6058 0 0]Ya veo. Es decir, que aún tienes que utilizarlos en combate.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0]¿Es esto a lo que se refieren con "dejar lo mejor para el final"? Tu potencial no conoce límites.[n][w][e]

[msg MSG_138_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6024 0 0]No esperaba menos de [nf]. Tu pericia táctica no tiene parangón.[n][w][e]

[msg MSG_139_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0]Yo también lucharé sin contener mi poder. Los próximos combates pondrán a prueba nuestra fuerza.[n][w][e]

[msg MSG_140_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6012 0 0]Operación de limpieza completada. Los enemigos de este calibre son como kappas de feria.[n][w][e]

[sel SEL_141_0_0 top]
[f 2 1]Lo has clavado.[e]
[f 2 1]No necesariamente.[e]
[f 2 1]¿Por qué "kappa"?[e]

[msg MSG_142_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6024 0 0]Ah, bien. Quizá los kappas se alegran por nosotros.[n][w][e]

[msg MSG_143_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6060 0 0]Ah, claro. No estamos en una feria, ¿verdad? Debería haber dicho "kappas de la torre". Qué difícil es hablar de forma idiomática.[n][w][e]

[msg MSG_144_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6024 0 0]Me han informado de que es una expresión idiomática que describe un blanco fácil o una presa indefensa.[n][w][e]

[msg MSG_145_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0]Por cierto..., ¿qué clase de criatura es el Sr. Kappa? Me gustaría conocerlo algún día.[n][w][e]

[msg MSG_146_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6008 0 0]Sombra enemiga eliminada. Un ataque muy bien coordinado, [nf].[n][w][e]

[sel SEL_147_0_0 top]
[f 2 1]Ha ido bien.[e]
[f 2 1]Ha sido suerte.[e]
[f 2 1]Lo has hecho genial, Aigis.[e]

[msg MSG_148_0_0 [Aigis]]
[f 2 1][bup 7 1 65535 65535 0 0][vp 3 0 65535 6027 0 0][f 4 23 1 7 1 25 25]Sí, un equipo bien coordinado resulta fundamental para alcanzar la victoria, ¿no crees?[n][w][e]

[msg MSG_149_0_0 [Aigis]]
[f 2 1][bup 7 1 65535 65535 0 0][vp 3 0 65535 6131 0 0][f 4 23 1 7 1 25 25]Je, je. Siempre tan humilde, [nf].[n][w][e]

[msg MSG_150_0_0 [Aigis]]
[f 2 1][bup 7 1 65535 65535 0 0][vp 3 0 65535 6039 0 0][f 4 23 1 7 1 25 25]Gracias. Lo mínimo que puedo hacer es cumplir con mi parte.[n][w][e]

[msg MSG_151_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][f 4 23 1 7 0 25 25]Bien, pues sigamos con la exploración.[n][w][e]

[msg MSG_152_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6087 0 0]Misión cumplida. ¿Hay alguien herido?[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0]Si estás cansada, no te fuerces demasiado y volvamos.[n][w][e]

[sel SEL_153_0_0 top]
[f 2 1]Volvamos por ahora.[e]
[f 2 1]Puedo seguir.[e]
[f 2 1]Nunca pierdes la compostura.[e]

[msg MSG_154_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6025 0 0]Entendido. Volvamos a la primera planta.[n][w][e]

[msg MSG_155_0_0 [Aigis]]
[f 2 1][bup 7 1 65535 65535 0 0][vp 3 0 65535 6025 0 0][f 4 23 1 7 1 25 25]¡Entendido! Quieres aprovechar la racha, ¿verdad?[n][w][e]

[msg MSG_156_0_0 [Aigis]]
[f 2 1][bup 7 1 65535 65535 0 0][vp 3 0 65535 6027 0 0][f 4 23 1 7 1 25 25]Como se suele decir: "vísteme despacio, que tengo prisa". Hay que tomarse un tiempo para sopesar todas las opciones.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][f 4 23 1 7 0 25 25]La decisión es tuya, [nf]. Confío en ti.[n][w][e]

[msg MSG_157_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6009 0 0]Buen trabajo, equipo. Quizá podríamos dejarlo aquí...[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0]Sin embargo, creo que podemos seguir. ¿Tú cómo lo ves?[n][w][e]

[sel SEL_158_0_0 top]
[f 2 1]Me parece bien.[e]
[f 2 1]Quiero irme a casa.[e]
[f 2 1]Estás deseándolo.[e]

[msg MSG_159_0_0 [Aigis]]
[f 2 1][bup 7 1 65535 65535 0 0][vp 3 0 65535 6025 0 0][f 4 23 1 7 1 25 25]¡Sí! ¡Pues vamos a rocanrolear![n][w][e]

[msg MSG_160_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6107 0 0]Entendido. Volvamos a la entrada, entonces.[n][w][e]

[msg MSG_161_0_0 [Aigis]]
[f 2 1][bup 7 1 65535 65535 0 0][vp 3 0 65535 6118 0 0][f 4 23 1 7 1 25 25]¡Por supuesto! Quiero hacer todo lo posible y luchar a vuestro lado.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][f 4 23 1 7 0 25 25]Dirígenos, [nf].[n][w][e]

[msg MSG_162_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6115 0 0]Bien hecho.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0]Ya sean los relevos o la teúrgia, conoces todas las tácticas que tienes a tu disposición, ¿no?[n][w][e]

[sel SEL_163_0_0 top]
[f 2 1]Hasta cierto punto.[e]
[f 2 1]Parece instintivo.[e]
[f 2 1]No estoy segura.[e]

[msg MSG_164_0_0 [Aigis]]
[f 2 1][bup 7 1 65535 65535 0 0][vp 3 0 65535 6131 0 0][f 4 23 1 7 1 25 25]No te gusta fanfarronear, ¿verdad, [nf]? Je, je. Tenemos mucha suerte de tenerte.[n][w][e]

[msg MSG_165_0_0 [Aigis]]
[f 2 1][bup 7 1 65535 65535 0 0][vp 3 0 65535 6131 0 0][f 4 23 1 7 1 25 25]Je, je. Tenemos mucha suerte de tenerte.[n][w][e]

[msg MSG_166_0_0 [Aigis]]
[f 2 1][bup 7 1 65535 65535 0 0][vp 3 0 65535 6061 0 0][f 4 23 1 7 1 25 25]Con lo lejos que has llegado, diría que puedes permitirte el lujo de tener confianza en ti misma, ¿no?[n][w][e]

[msg MSG_167_0_0 [Aigis]]
[f 2 1][bup 7 1 65535 65535 0 0]Yo también me prepararé para nuestra última batalla.[n][w][e]

[msg MSG_168_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6087 0 0]Los hemos derrotado con facilidad. Eran como kappas de feria.[n][w][e]

[sel SEL_169_0_0 top]
[f 2 1]Lo has clavado.[e]
[f 2 1]No necesariamente.[e]
[f 2 1]¿Por qué "kappa"?[e]

[msg MSG_170_0_0 [Aigis]]
[f 2 1][bup 7 1 65535 65535 0 0][vp 3 0 65535 6132 0 0][f 4 23 1 7 1 25 25]Je, je. Sin ánimo de ofender al Sr. Kappa, la expresión es un tanto divertida, ¿no crees?[n][w][e]

[msg MSG_171_0_0 [Aigis]]
[f 2 1][bup 7 3 65535 65535 0 0][vp 3 0 65535 6073 0 0][f 4 23 1 7 3 25 25]Ah... ¿Debería haber dicho "kappas de la torre"? Qué complicado es hablar de forma idiomática.[n][w][e]

[msg MSG_172_0_0 [Aigis]]
[f 2 1][bup 7 1 65535 65535 0 0][vp 3 0 65535 6060 0 0][f 4 23 1 7 1 25 25]Junpei me enseñó esa expresión. Describe a un blanco fácil o una presa indefensa.[n][w][e]

[msg MSG_173_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][f 4 23 1 7 0 25 25]Por cierto..., ¿qué clase de criatura es el Sr. Kappa? Me encantaría conocerlo algún día.[n][w][e]

[msg MSG_174_0_0 [Ken Amada]]
[f 2 1][bup 8 1 65535 65535 0 0][vp 3 0 65535 7011 0 0][f 4 23 1 8 1 25 25]¡Bien! Hemos liquidado a un enemigo difícil.[n][w][e]
[f 2 1][bup 8 1 65535 65535 0 0]¡Ha sido una victoria gracias a tus instrucciones, [nl]![n][w][e]

[sel SEL_175_0_0 top]
[f 2 1]Claro que sí.[e]
[f 2 1]No mucho.[e]
[f 2 1]Ha sido cosa tuya.[e]

[msg MSG_176_0_0 [Ken Amada]]
[f 2 1][bup 8 1 65535 65535 0 0][vp 3 0 65535 7132 0 0]Ha sido increíble.[n][w][e]
[f 2 1][bup 8 1 65535 65535 0 0]El líder tiene que dar órdenes precisas para que el equipo actúe como es debido.[n][w][e]

[msg MSG_177_0_0 [Ken Amada]]
[f 2 1][bup 8 1 65535 65535 0 0][vp 3 0 65535 7132 0 0]Ja, ja. Bueno, los demás también contribuimos combinando nuestras fuerzas individuales.[n][w][e]
[f 2 1][bup 8 1 65535 65535 0 0]Sin embargo, es el líder quien hace encajar todas las piezas, y se te da muy bien.[n][w][e]

[msg MSG_178_0_0 [Ken Amada]]
[f 2 1][bup 8 4 65535 65535 0 0][vp 3 0 65535 7037 0 0][f 4 23 1 8 4 25 25]¿Tú crees? Me alegra que lo pienses, pero...[n][w][e]
[f 2 1][bup 8 1 65535 65535 0 0][f 4 23 1 8 1 25 25]Creo que soy mucho más fuerte cuando lucho a vuestro lado.[n][w][e]

[msg MSG_179_0_0 [Ken Amada]]
[f 2 1][bup 8 1 65535 65535 0 0]Uy, perdón. Lo he dicho sin pensar.[n][w][e]
[f 2 1][bup 8 1 65535 65535 0 0]Siempre me he sentido así, así que quería decírtelo.[n][w][e]
[f 2 1][bup 8 1 65535 65535 0 0]Bueno, sigamos el ritmo.[n][w][e]

[msg MSG_180_0_0 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 3 0 65535 7115 0 0]Puf, estos guardianes son mucho más duros que las sombras comunes que deambulan por aquí.[n][w][e]
[f 2 1][bup 8 0 65535 65535 0 0]¿Seguimos un poco más? ¿O nos tomamos un descanso?[n][w][e]

[sel SEL_181_0_0 top]
[f 2 1]Volvamos.[e]
[f 2 1]Continuemos.[e]
[f 2 1]Ni fu ni fa.[e]

[msg MSG_182_0_0 [Ken Amada]]
[f 2 1][bup 8 1 65535 65535 0 0][vp 3 0 65535 7132 0 0][f 4 23 1 8 1 25 25]Buena idea. Volvamos a la entrada, entonces.[n][w][e]

[msg MSG_183_0_0 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 3 0 65535 7108 0 0]Ya veo... Eres una mujer de acero, [nl].[n][w][e]
[f 2 1][bup 8 1 65535 65535 0 0][f 4 23 1 8 1 25 25]¡Pero a mí también me sobran fuerzas! A ver hasta dónde llegamos.[n][w][e]

[msg MSG_184_0_0 [Ken Amada]]
[f 2 1][bup 8 1 65535 65535 0 0][f 4 23 1 8 1 25 25]Es un buen momento para parar, así que cuesta decidir, ¿eh?[n][w][e]
[f 2 1][bup 8 1 65535 65535 0 0]Bueno, avísame con lo que decidas. A mí me va bien cualquier cosa.[n][w][e]

[msg MSG_185_0_0 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 3 0 65535 7087 0 0]Creo que he tenido una pequeña revelación en este último combate.[n][w][e]
[f 2 1][bup 8 0 65535 65535 0 0]¿Podemos seguir? Me gustaría reforzar lo que he descubierto mientras lo tengo fresco.[n][w][e]

[sel SEL_186_0_0 top]
[f 2 1]Vale, vamos.[e]
[f 2 1]Volvamos primero.[e]
[f 2 1]Me lo pensaré.[e]

[msg MSG_187_0_0 [Ken Amada]]
[f 2 1][bup 8 1 65535 65535 0 0][vp 3 0 65535 7116 0 0][f 4 23 1 8 1 25 25]Gracias. Procuraré ser útil.[n][w][e]

[msg MSG_188_0_0 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 3 0 65535 7069 0 0]¿Te has cansado?[n][w][e]
[f 2 1][bup 8 1 65535 65535 0 0][f 4 23 1 8 1 25 25]No pasa nada. Ya lo retomaremos aquí la próxima vez.[n][w][e]

[msg MSG_189_0_0 [Ken Amada]]
[f 2 1][bup 8 1 65535 65535 0 0][vp 3 0 65535 7026 0 0][f 4 23 1 8 1 25 25]Confío en tu decisión, pero si podemos seguir, adelante.[n][w][e]

[msg MSG_190_0_0 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 3 0 65535 7115 0 0]¿Cuántas sombras guardianas crees que habrá en total?[n][w][e]
[f 2 1][bup 8 3 65535 65535 0 0][f 4 23 1 8 3 25 25]Cada vez son más fuertes, lo que implica que nos esperan sombras muy poderosas.[n][w][e]

[sel SEL_191_0_0 top]
[f 2 1]Sí, debería.[e]
[f 2 1]Espero que haya sido el último.[e]
[f 2 1]De nada sirve seguir dándole vueltas.[e]

[msg MSG_192_0_0 [Ken Amada]]
[f 2 1][bup 8 2 65535 65535 0 0][vp 3 0 65535 7090 0 0][f 4 23 1 8 2 25 25]En ese caso..., estaré preparado.[n][w][e]

[msg MSG_193_0_0 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 3 0 65535 7063 0 0][f 4 23 1 8 0 25 25]Ojalá... Estaría bien, pero a fin de cuentas, no son más que ilusiones vanas.[n][w][e]

[msg MSG_194_0_0 [Ken Amada]]
[f 2 1][bup 8 1 65535 65535 0 0][vp 3 0 65535 7120 0 0][f 4 23 1 8 1 25 25]Es verdad. Deberíamos centrarnos en los enemigos que nos esperan.[n][w][e]

[msg MSG_195_0_0 [Ken Amada]]
[f 2 1][bup 8 2 65535 65535 0 0][f 4 23 1 8 2 25 25]He de entrenar más para poder enfrentarme a cualquier enemigo, por muy fuerte que sea.[n][w][e]
[f 2 1][bup 8 1 65535 65535 0 0][f 4 23 1 8 1 25 25]Venga, vamos.[n][w][e]

[msg MSG_196_0_0 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 3 0 65535 7088 0 0]Puf, por fin. Menos mal que hemos terminado.[n][w][e]
[f 2 1][bup 8 0 65535 65535 0 0]Los guardianes son muy duros. Imagínate que todos los enemigos de la planta fueran guardianes.[n][w][e]

[sel SEL_197_0_0 top]
[f 2 1]Sí, mejor no.[e]
[f 2 1]Sería una buena experiencia.[e]
[f 2 1]Los machacaríamos.[e]

[msg MSG_198_0_0 [Ken Amada]]
[f 2 1][bup 8 3 65535 65535 0 0][vp 3 0 65535 7120 0 0][f 4 23 1 8 3 25 25]Ja, ja. Sé que he sacado yo el tema, pero se me ha puesto la piel de gallina de solo pensar en ello.[n][w][e]

[msg MSG_199_0_0 [Ken Amada]]
[f 2 1][bup 8 3 65535 65535 0 0][vp 3 0 65535 7120 0 0]Sí, eso nos mantendría en vilo... Aunque bueno, siempre estamos con los nervios de punta.[n][w][e]

[msg MSG_200_0_0 [Ken Amada]]
[f 2 1][bup 8 4 65535 65535 0 0][vp 3 0 65535 7103 0 0][f 4 23 1 8 4 25 25]¿Eh? ¿De verdad lo crees? [nl], ¡te veo muy convencida![n][w][e]
[f 2 1][bup 8 3 65535 65535 0 0][f 4 23 1 8 3 25 25]Sin embargo, a mí me dan escalofríos solo de imaginarlo.[n][w][e]

[msg MSG_201_0_0 [Ken Amada]]
[f 2 1][bup 8 2 65535 65535 0 0][f 4 23 1 8 2 25 25]No hay forma de saber con qué tretas nos van a sorprender. No bajemos la guardia.[n][w][e]

[msg MSG_202_0_0 [Koromaru]]
[f 2 1][bup 9 0 65535 65535 0 0][vp 3 0 65535 8001 0 0]¡Guau, guau![n][w][e]

[msg MND_203_0_0]
[f 2 1]Koromaru se alegra de que hayamos ganado.[n][w][e]

[msg MSG_204_0_0 [Koromaru]]
[f 2 1][bup 9 0 65535 65535 0 0]¡Guau![n][w][e]

[sel SEL_205_0_0 top]
[f 2 1]Buen chico.[e]
[f 2 1]Ya te invitaré, ¿vale?[e]
[f 2 1]Sigue así.[e]

[msg MSG_206_0_0 [Koromaru]]
[f 2 1][bup 9 0 65535 65535 0 0][vp 3 0 65535 8012 0 0]¡Guau, guau![n][w][e]

[msg MND_207_0_0]
[f 2 1]Koromaru parece orgulloso de sí mismo.[n][w][e]

[msg MSG_208_0_0 [Koromaru]]
[f 2 1][bup 9 0 65535 65535 0 0]¡Guau![n][w][e]

[msg MSG_209_0_0 [Koromaru]]
[f 2 1][bup 9 0 65535 65535 0 0][vp 3 0 65535 8009 0 0]Aj, aj...[n][w][e]

[msg MND_210_0_0]
[f 2 1]Koromaru está jadeando mucho.[n][w][e]
[f 2 1]¿Le habrá agotado el último combate?[n][w][e]

[msg MSG_211_0_0 [Koromaru]]
[f 2 1][bup 9 0 65535 65535 0 0]Auuu...[n][w][e]

[sel SEL_212_0_0 top]
[f 2 1]Volvamos.[e]
[f 2 1]Avancemos un poco más.[e]
[f 2 1]Déjame analizar la situación.[e]

[msg MSG_213_0_0 [Koromaru]]
[f 2 1][bup 9 0 65535 65535 0 0][vp 3 0 65535 8001 0 0]¡Guau, guau![n][w][e]

[msg MND_214_0_0]
[f 2 1]Parece que Koromaru se apunta.[n][w][e]
[f 2 1]Lo mejor va a ser volver...[n][w][e]

[msg MSG_215_0_0 [Koromaru]]
[f 2 1][bup 9 0 65535 65535 0 0][vp 3 0 65535 8001 0 0]¡Guau! ¡Guau, guau![n][w][e]

[msg MND_216_0_0]
[f 2 1]Parece que Koromaru se está mentalizando.[n][w][e]
[f 2 1]Parece que está dispuesto a darlo todo.[n][w][e]

[msg MSG_217_0_0 [Koromaru]]
[f 2 1][bup 9 0 65535 65535 0 0][vp 3 0 65535 8004 0 0]¡Guau![n][w][e]

[msg MND_218_0_0]
[f 2 1]Parece que Koromaru se apunta.[n][w][e]
[f 2 1]De mí depende que sigamos adelante o retrocedamos.[n][w][e]

[msg MSG_219_0_0 [Koromaru]]
[f 2 1][bup 9 1 65535 65535 0 0][vp 3 0 65535 8007 0 0][f 4 23 1 9 1 25 25]¡Auuuuuu![n][w][e]

[msg MND_220_0_0]
[f 2 1]Koromaru está de muy buen humor.[n][w][e]

[msg MSG_221_0_0 [Koromaru]]
[f 2 1][bup 9 0 65535 65535 0 0][f 4 23 1 9 0 25 25]¡Guau![n][w][e]

[sel SEL_222_0_0 top]
[f 2 1]¿Quieres que sigamos?[e]
[f 2 1]Volvamos.[e]
[f 2 1]Estamos en racha, ¿eh?[e]

[msg MSG_223_0_0 [Koromaru]]
[f 2 1][bup 9 0 65535 65535 0 0][vp 3 0 65535 8004 0 0]¡Guau![n][w][e]

[msg MND_224_0_0]
[f 2 1]Koromaru parece decidido.[n][w][e]

[msg MSG_225_0_0 [Koromaru]]
[f 2 1][bup 9 0 65535 65535 0 0][vp 3 0 65535 8004 0 0]¡Guau![n][w][e]

[msg MND_226_0_0]
[f 2 1]Parece que Koromaru se apunta.[n][w][e]

[msg MSG_227_0_0 [Koromaru]]
[f 2 1][bup 9 1 65535 65535 0 0][vp 3 0 65535 8001 0 0][f 4 23 1 9 1 25 25]¡Guau! ¡Guau![n][w][e]

[msg MND_228_0_0]
[f 2 1]Koromaru parece decidido.[n][w][e]

[msg MSG_229_0_0 [Koromaru]]
[f 2 1][bup 9 0 65535 65535 0 0][f 4 23 1 9 0 25 25]¡Guau![n][w][e]

[msg MSG_230_0_0 [Koromaru]]
[f 2 1][bup 9 0 65535 65535 0 0][vp 3 0 65535 8008 0 0]Aj, aj...[n][w][e]

[msg MSG_231_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 50 0 0]Buen trabajo. Tú también, Korocito.[n][w][e]
[f 2 1][bup 6 0 65535 50 0 0]Puesto que los enemigos cada vez son más fuertes, tendremos que ir con mucho cuidado de ahora en adelante.[n][w][e]

[sel SEL_232_0_0 top]
[f 2 1]Todo irá bien.[e]
[f 2 1]Estoy un poco de los nervios.[e]
[f 2 1]Tú puedes, Koromaru.[e]

[msg MSG_233_0_0 [Koromaru]]
[f 2 1][bup 9 0 65535 65535 0 0][vp 3 0 65535 8001 0 0]¡Guau, guau![n][w][e]

[msg MSG_234_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 50 0 0]Je, je, ¿tú también rebosas confianza, Korocito? Parece que tienes coraje a raudales.[n][w][e]

[msg MSG_235_0_0 [Koromaru]]
[f 2 1][bup 9 0 65535 65535 0 0][vp 3 0 65535 8012 0 0]¡Guau, guau![n][w][e]

[msg MSG_236_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 50 0 0]Korocito te está animando. ¡Te cubre las espaldas![n][w][e]

[msg MSG_237_0_0 [Koromaru]]
[f 2 1][bup 9 0 65535 65535 0 0][vp 3 0 65535 8010 0 0]¡Guau![n][w][e]

[msg MSG_238_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 50 0 0]Je, je, cuántos ánimos tienes. Contamos contigo, Korocito.[n][w][e]

[msg MSG_239_0_0 [Koromaru]]
[f 2 1][bup 9 0 65535 65535 0 0]¡Guau, guau![n][w][e]

[msg MSG_240_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 50 0 0][vp 3 0 65535 5011 0 0]¡Hemos derrotado al guardián! Gracias por vuestros esfuerzos, chicos.[n][w][e]

[msg MSG_241_0_0 [Koromaru]]
[f 2 1][bup 9 0 65535 65535 0 0]¡Guau![n][w][e]

[msg MSG_242_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 50 0 0]Sé que está más claro que el agua, pero Korocito es increíble, ¿a que sí?[n][w][e]
[f 2 1][bup 6 0 65535 50 0 0]Es muy atento y trabaja muy bien en equipo. Casi parece que entiende todo lo que le decimos.[n][w][e]

[sel SEL_243_0_0 top]
[f 2 1]Porque es un chico listo.[e]
[f 2 1]¿Y si son imaginaciones tuyas?[e]
[f 2 1]Buen chico, Koromaru.[e]

[msg MSG_244_0_0 [Koromaru]]
[f 2 1][bup 9 1 65535 65535 0 0][vp 3 0 65535 8001 0 0][f 4 23 1 9 1 25 25]¡Guau, guau![n][w][e]

[msg MSG_245_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 50 0 0]Je, je, mira qué contento está Korocito. ¿Ves? Nos entiende.[n][w][e]

[msg MSG_246_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 6 65535 50 0 0][vp 3 0 65535 5037 0 0]N-no, no puede ser. Tú nos entiendes, ¿verdad, Korocito?[n][w][e]

[msg MSG_247_0_0 [Koromaru]]
[f 2 1][bup 9 3 65535 65535 0 0][f 4 23 1 9 3 25 25]Auuu...[n][w][e]

[msg MSG_248_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 6 65535 50 0 0]¿Ves? Míralo qué triste se ha puesto. Estoy segura de que entiende lo que le decimos.[n][w][e]

[msg MSG_249_0_0 [Koromaru]]
[f 2 1][bup 9 1 65535 65535 0 0][vp 3 0 65535 8012 0 0][f 4 23 1 9 1 25 25]¡Guau, guau![n][w][e]

[msg MSG_250_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 50 0 0]Je, je, mira qué contento está Korocito. ¿Ves? Nos entiende.[n][w][e]

[msg MSG_251_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 50 0 0][f 4 23 1 9 0 25 25]¡Sigue así, Korocito![n][w][e]

[msg MSG_252_0_0 [Koromaru]]
[f 2 1][bup 9 0 65535 65535 0 0]¡Guau, guau![n][w][e]

[msg MSG_253_0_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 3 0 65535 9049 0 0]Ya hemos terminado aquí...[n][w][e]

[msg MSG_254_0_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0]Eres mejor de lo que pensaba. Ahora entiendo por qué Aki no dejaba de hablar de ti.[n][w][e]

[sel SEL_255_0_0 top]
[f 2 1]Tendré que darte las gracias...[e]
[f 2 1]No ha sido nada.[e]
[f 2 1]Tú tampoco eres moco de pavo.[e]

[msg MSG_256_0_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 3 0 65535 9024 0 0]Yo te cubro, así que haz lo que tengas que hacer.[n][w][e]

[msg MSG_257_0_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 3 0 65535 9098 0 0]Je, es mejor ser humilde. La soberbia puede acabar matándote.[n][w][e]

[msg MSG_258_0_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 3 0 65535 9102 0 0]Sí, bueno. No puedo permitirme el lujo de contenerme.[n][w][e]

[msg MSG_259_0_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0]Vamos.[n][w][e]

[msg MSG_260_0_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 3 0 65535 9101 0 0]Otro incordio menos.[n][w][e]
[f 2 1][bup 10 0 65535 65535 0 0]¿Chapamos ya por hoy?[n][w][e]

[sel SEL_261_0_0 top]
[f 2 1]Sí, vámonos.[e]
[f 2 1]Preferiría seguir.[e]
[f 2 1]¿Qué deberíamos hacer?[e]

[msg MSG_262_0_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 3 0 65535 9107 0 0]Muy lista. Volvamos y descansemos, o lo que sea. Hay que prepararse para el próximo viaje.[n][w][e]

[msg MSG_263_0_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 3 0 65535 9108 0 0]Entendido. Bueno, tú eres la líder. Iré donde tú vayas.[n][w][e]

[msg MSG_264_0_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 3 0 65535 9070 0 0]Tú verás. Pero no te metas en camisa de once varas.[n][w][e]

[msg MSG_265_0_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 3 0 65535 9126 0 0]Muy bien, camino despejado.[n][w][e]
[f 2 1][bup 10 0 65535 65535 0 0]Vamos a seguir, ¿no?[n][w][e]

[sel SEL_266_0_0 top]
[f 2 1]Sí, por supuesto.[e]
[f 2 1]Quizá deberíamos volver.[e]
[f 2 1]Te veo a tope.[e]

[msg MSG_267_0_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 1 65535 65535 0 0][vp 3 0 65535 9098 0 0][f 4 23 1 10 1 25 25]Je, menos mal que estamos en la misma onda. Aún tengo mucho combustible que quemar.[n][w][e]

[msg MSG_268_0_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 3 0 65535 9057 0 0]Me parece bien. No es mal momento para parar.[n][w][e]

[msg MSG_269_0_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 3 0 65535 9102 0 0]Qué va, solo quería ver cómo andabas.[n][w][e]
[f 2 1][bup 10 0 65535 65535 0 0]Yo tampoco voy demasiado mal.[n][w][e]

[msg MSG_270_0_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][f 4 23 1 10 0 25 25]Vamos.[n][w][e]

[msg MSG_271_0_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 3 0 65535 9104 0 0]Vaya puto cansino. Por suerte, no era rival para nosotros.[n][w][e]
[f 2 1][bup 10 0 65535 65535 0 0]Más adelante nos toparemos con combates más duros, así que ve preparándote.[n][w][e]

[sel SEL_272_0_0 top]
[f 2 1]Cuenta conmigo.[e]
[f 2 1]Yo me encargo de ellos.[e]
[f 2 1]Te lo dejo a ti.[e]

[msg MSG_273_0_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 3 0 65535 9069 0 0]No quiero ponerte contra las cuerdas, pero nuestra victoria depende de ti.[n][w][e]
[f 2 1][bup 10 0 65535 65535 0 0]Veamos qué sabes hacer, líder.[n][w][e]

[msg MSG_274_0_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 1 65535 65535 0 0][vp 3 0 65535 9049 0 0][f 4 23 1 10 1 25 25]Jum. Tienes agallas, lo admito.[n][w][e]
[f 2 1][bup 10 0 65535 65535 0 0][f 4 23 1 10 0 25 25]No pasa nada por ser un poco bravucona, pero no te lo tengas muy creído o te daré un sopapo.[n][w][e]

[msg MSG_275_0_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 3 0 65535 9056 0 0][f 4 25 10]...[n][w][e]
[f 2 1][bup 10 0 65535 65535 0 0]Eh, a mí no me eches el muerto. No puedo garantizar que siempre esté aquí.[n][w][e]

[msg MSG_276_0_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0]Bueno, en marcha.[n][w][e]

[msg MSG_277_0_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 3 0 65535 9107 0 0]Menos mal que ya se ha acabado.[n][w][e]
[f 2 1][bup 10 0 65535 65535 0 0]No pierdas el tiempo con este tipo de enemigos.[n][w][e]

[sel SEL_278_0_0 top]
[f 2 1]Pongámonos en marcha.[e]
[f 2 1]No hay por qué precipitarse.[e]
[f 2 1]¿Ya no puedes más?[e]

[msg MSG_279_0_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 3 0 65535 9024 0 0]Adelante.[n][w][e]
[f 2 1][bup 10 0 65535 65535 0 0]No sé si este sitio será muy grande, pero no estaría de más que avanzáramos un poco.[n][w][e]

[msg MSG_280_0_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 3 0 65535 9049 0 0]Me parece bien.[n][w][e]
[f 2 1][bup 10 0 65535 65535 0 0]Pero tampoco estaría de más que avanzáramos un poco, sobre todo ahora que ando de humor.[n][w][e]

[msg MSG_281_0_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 3 0 65535 9114 0 0]Qué, ¿vas a regañarme si no? No soy de cristal, así que preocúpate por ti.[n][w][e]
[f 2 1][bup 10 0 65535 65535 0 0]Haré lo que tenga que hacer, y lo haré muy bien. Tú descansa y haz tu trabajo.[n][w][e]

[msg MSG_282_0_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0]Venga, en marcha.[n][w][e]

[msg MSG_283_0_0 [Junpei Iori]]
[f 2 1][bup 3 2 65535 65535 0 0][vp 3 0 65535 2062 0 0][f 4 23 1 2 2 25 25]Mmm...[n][w][e]

[msg MSG_284_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 50 0 0]¿Sucede algo, Junpei? ¿Qué te preocupa?[n][w][e]

[msg MSG_285_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][f 4 23 1 2 0 25 25]Nah, no es nada. Es solo que... ¿Recuerdas esas sombras con libros en la cabeza?[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]¿Como esa con la que acabamos de luchar? ¿Qué habrá escrito en ese libro?[n][w][e]

[msg MSG_286_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 4 65535 50 0 0]Me estaba preguntando lo mismo...[n][w][e]
[f 2 1][bup 6 0 65535 50 0 0]De vez en cuando vemos cosas, pero es complicado distinguir nada luchando.[n][w][e]

[msg MSG_287_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2026 0 0][f 4 23 1 2 1 25 25]¿Verdad? A ver, que me la trae al pairo lo que ponga.[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]Pero si hay colecciones de fotos de modelos guapas, como en las revistas manga, pues...[n][w][e]

[msg MSG_288_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4061 0 0]¿Os habéis preguntado alguna vez cómo se mantienen de pie las sombras con forma de balanza?[n][w][e]

[msg MSG_289_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 50 0 0]Sí, sé a lo que te refieres. Entiendo que les costará mucho mantenerse erguidas y moverse.[n][w][e]

[msg MSG_290_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0]¿Existirá alguna razón por la que tienen ese aspecto?[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Es más, me siento muy tentada a volcarlas.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Perdón, me desvío del tema...[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]En marcha, líder.[n][w][e]

[msg MSG_291_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6012 0 0]Enemigo derrotado. Solicitando siguiente orden.[n][w][e]

[sel SEL_292_0_0 top]
[f 2 1]Sigamos explorando.[e]
[f 2 1]Dejémoslo por hoy.[e]
[f 2 1]¿Qué te gustaría hacer?[e]

[msg MSG_293_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6024 0 0]Afirmativo. Aunque la Tártaro sea una torre colosal...[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0]Con avances constantes y graduales, alcanzaremos poco a poco nuestro objetivo.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0]"Todo viaje comienza con un pequeño paso", como se suele decir.[n][w][e]

[msg MSG_294_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6024 0 0]Entendido. Más vale prevenir que curar, como se suele decir.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0]También hay otros dichos: "vísteme despacio, que tengo prisa" y "sin prisa, pero sin pausa".[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0]Aunque... ¿no sería mejor "con prisa, pero sin pausa"?[n][w][e]

[msg MSG_295_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6058 0 0]No me esperaba una pregunta en respuesta a mi pregunta.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0]¿A esto se refieren con "atacar por el lado ciego"?[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0]Sin embargo, yo no tengo ningún lado ciego. ¿Seguiría aplicándose eso a mí?[n][w][e]

[msg MSG_296_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 4 65535 50 0 0]A-Aigis, hablas de una forma muy peculiar. ¿Dónde has aprendido todas esas expresiones?[n][w][e]

[msg MSG_297_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0]Tengo un régimen académico diario.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0]El otro día, Junpei me enseñó a escribir haikus.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0]"Torre Tártaro...[n]Oscura y decrépita...[n]Eres muy alta".[n][w][e]

[msg MSG_298_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 3 0 65535 3085 0 0]Estupendo. Ya podemos avanzar.[n][w][e]

[msg MSG_299_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0]¿Tú qué piensas, [nl]? ¿Te preocupa algo de aquí en adelante?[n][w][e]

[sel SEL_300_0_0 top]
[f 2 1]Para nada.[e]
[f 2 1]Solo unos cuantos.[e]
[f 2 1]¿Debería preocuparme?[e]

[msg MSG_301_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 3 0 65535 3131 0 0]Me tranquiliza que tengas tanta confianza. Seguro que los demás también lo piensan.[n][w][e]

[msg MSG_302_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0]Sigue así. Te ayudaré en todo lo que pueda.[n][w][e]

[msg MSG_303_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 3 0 65535 3093 0 0]Ah, entiendo lo que quieres decir.[n][w][e]

[msg MSG_304_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0]Pero si lo estás haciendo de maravilla. Tú no te preocupes. No te detengas y todo irá bien.[n][w][e]

[msg MSG_305_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 3 0 65535 3060 0 0]Bueno, llevamos mucho tiempo en primera línea...[n][w][e]

[msg MSG_306_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0]Solo quería recordarte que puedes avisarme si necesitas algo.[n][w][e]

[msg MSG_307_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 50 0 0]Sanada...[n][w][e]
[f 2 1][bup 6 1 65535 50 0 0]Te veo... más tranquilo que antes. Es un cambio que se agradece.[n][w][e]

[msg MSG_308_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 1 65535 65535 0 0][f 4 23 1 4 1 25 25]Je, ¿tenías que dar la puntilla? "Un cambio que se agradece"...[n][w][e]
[f 2 1][bup 4 1 65535 65535 0 0]En fin, sigamos. Aún nos queda un largo camino por delante.[n][w][e]

[msg MSG_309_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 50 0 0][vp 3 0 65535 5002 0 0]¿Cómo te sientes al volver a la acción, Amada?[n][w][e]

[msg MSG_310_0_0 [Ken Amada]]
[f 2 1][bup 8 1 65535 65535 0 0][f 4 23 1 8 1 25 25]Muy bien, la verdad. Gracias por preguntar, Fuuka.[n][w][e]

[msg MSG_311_0_0 [Ken Amada]]
[f 2 1][bup 8 1 65535 65535 0 0][nl], quiero darte las gracias por dejarme estar al frente.[n][w][e]
[f 2 1][bup 8 2 65535 65535 0 0][f 4 23 1 8 2 25 25]Deseo volverme aún más fuerte para poder facilitaros las cosas.[n][w][e]

[sel SEL_312_0_0 top]
[f 2 1]Qué ganas.[e]
[f 2 1]Ya eres muy fuerte.[e]
[f 2 1]Te ayudaremos.[e]

[msg MSG_313_0_0 [Ken Amada]]
[f 2 1][bup 8 1 65535 65535 0 0][vp 3 0 65535 7040 0 0][f 4 23 1 8 1 25 25]Ya verás. Te prometo que llegaré hasta el final.[n][w][e]

[msg MSG_314_0_0 [Ken Amada]]
[f 2 1][bup 8 1 65535 65535 0 0][vp 3 0 65535 7052 0 0][f 4 23 1 8 1 25 25]Ja, ja. No necesito que me consientas. Además, estoy creciendo.[n][w][e]

[msg MSG_315_0_0 [Ken Amada]]
[f 2 1][bup 8 1 65535 65535 0 0][vp 3 0 65535 7026 0 0][f 4 23 1 8 1 25 25]Gracias, te lo agradezco.[n][w][e]

[msg MSG_316_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 50 0 0]Por cierto, Amada, ahora que me he fijado mejor...[n][w][e]
[f 2 1][bup 6 1 65535 50 0 0]Creo que has crecido un poco.[n][w][e]

[msg MSG_317_0_0 [Ken Amada]]
[f 2 1][bup 8 4 65535 65535 0 0][f 4 23 1 8 4 25 25]¡¿En serio?![n][w][e]
[f 2 1][bup 8 1 65535 65535 0 0][f 4 23 1 8 1 25 25]Será por toda la leche que bebo, je, je.[n][w][e]

[msg MSG_318_0_0 [Ken Amada]]
[f 2 1][bup 8 1 65535 65535 0 0]Bueno, [nl], ¿seguimos?[n][w][e]

[msg MSG_319_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 50 0 0][vp 3 0 65535 5011 0 0]Sombra enemiga eliminada.[n][w][e]

[msg MSG_320_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][f 4 23 1 2 1 25 25]Muy bien, equipo. Sigamos así y...[n][w][e]

[msg MSG_321_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 4 65535 50 0 0]Alto ahí, Yukari.[n][w][e]
[f 2 1][bup 6 0 65535 50 0 0]¿Tienes... ampollas en las manos?[n][w][e]

[msg MSG_322_0_0 [Yukari Takeba]]
[f 2 1][bup 2 4 65535 65535 0 0][f 4 23 1 2 4 25 25]¿Qué? ¡¿Cómo lo has sabido?![n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][f 4 23 1 2 0 25 25]Sí... Tengo unas cuantas ampollas, pero puedo disparar sin problemas.[n][w][e]

[sel SEL_323_0_0 top]
[f 2 1]Bien hecho, Fuuka.[e]
[f 2 1]Tómatelo con calma, Yukari.[e]
[f 2 1]¿Hacemos un descanso?[e]

[msg MSG_324_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 50 0 0][vp 3 0 65535 5061 0 0]Mmm... Hoy te notaba algo distinta.[n][w][e]
[f 2 1][bup 6 1 65535 50 0 0]Tengo vendas y otros artículos de primeros auxilios. Avísame si necesitas algo, ¿vale, Yukari?[n][w][e]

[msg MSG_325_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 50 0 0][vp 3 0 65535 5062 0 0]Coincido. Por suerte, no parece muy grave.[n][w][e]
[f 2 1][bup 6 1 65535 50 0 0]Puedes envolverte las manos con vendas si las ampollas te resultan molestas.[n][w][e]

[msg MSG_326_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 50 0 0][vp 3 0 65535 5062 0 0]Deberíamos. Por suerte, no parece muy grave.[n][w][e]
[f 2 1][bup 6 1 65535 50 0 0]Pero, si quieres descansar un rato, yo vigilaré el perímetro.[n][w][e]

[msg MSG_327_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][f 4 23 1 2 1 25 25]Vale. Gracias, Fuuka.[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][f 4 23 1 2 0 25 25][f 4 25 2]...[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0]Me da la sensación de que últimamente te preocupas más por nosotros que de costumbre.[n][w][e]

[msg MSG_328_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 4 65535 50 0 0]¿D-de verdad? Me alegro de ser útil.[n][w][e]
[f 2 1][bup 6 1 65535 50 0 0]Después de todo, mi función es ofreceros apoyo.[n][w][e]
[f 2 1][bup 6 1 65535 50 0 0]Bueno, ¿nos vamos, líder?[n][w][e]

[msg MSG_329_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 3 0 65535 1116 0 0]Genial. Ahora podemos seguir.[n][w][e]

[msg MSG_330_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0]Si al final no resulta ser cierto eso de que hay que derrotar a las sombras que aparecen en luna llena...[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0]Estoy segura de que habrá algo aquí que nos ayudará a acabar con la Hora Oscura.[n][w][e]

[sel SEL_331_0_0 top]
[f 2 1]Yo pienso lo mismo.[e]
[f 2 1]¿Y si no hay nada?[e]
[f 2 1]Solo hay una forma de saberlo.[e]

[msg MSG_332_0_0 [Yukari Takeba]]
[f 2 1][bup 2 6 65535 65535 0 0][vp 3 0 65535 1028 0 0][f 4 23 1 2 6 25 25]Sinceramente, me sorprendería que no hubiera nada...[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][f 4 23 1 2 0 25 25]Llegados a este punto, solo nos queda descubrirlo nosotros mismos. Al fin y al cabo, este trabajo solo lo podemos hacer nosotros.[n][w][e]

[msg MSG_333_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 3 0 65535 1095 0 0][f 4 23 1 2 1 25 25]Ja, ja, eso sería un asco. Pero, aunque lo intentáramos y falláramos, tampoco es que tengamos nada que perder, ¿no?[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][f 4 23 1 2 0 25 25]Si al final no hay nada, habremos descartado una posibilidad. En ese caso, tendremos que empezar a buscar en otra parte.[n][w][e]

[msg MSG_334_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 3 0 65535 1095 0 0][f 4 23 1 2 1 25 25]Ja, ja. Me alegra verte tan motivada, [nl].[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][f 4 23 1 2 0 25 25]Lo mejor es llegar lo más lejos posible y no quedarnos sentados dándole vueltas a hipótesis.[n][w][e]

[msg MSG_335_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 50 0 0]Me parece increíble que siempre veas un rayo de esperanza, Yukari.[n][w][e]

[msg MSG_336_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][f 4 23 1 2 1 25 25]Si te soy sincera, la mitad es pura fachada, pero la otra mitad es gracias a ti, Fuuka.[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][f 4 23 1 2 0 25 25]Muchas gracias por darme esa grabación.[n][w][e]

[msg MSG_337_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 50 0 0]Yukari...[n][w][e]

[msg MSG_338_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0]¡Muy bien! ¡Hora de marcharnos! Te seguimos, [nl].[n][w][e]

[msg MSG_339_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2086 0 0][f 4 23 1 3 1 25 25]¡Todos en fila! Con la racha que llevamos, ¿por qué no pisamos a fondo y seguimos?[n][w][e]

[sel SEL_340_0_0 top]
[f 2 1]Estás que te sales.[e]
[f 2 1]Tomémonoslo con calma.[e]
[f 2 1]Volvamos.[e]

[msg MSG_341_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2095 0 0]Tal cual. He pensado que andar lloriqueando no me iba a servir de nada.[n][w][e]

[msg MSG_342_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][f 4 23 1 3 0 25 25]Encontraremos respuestas en algún momento. ¿Por qué no luchamos mientras tanto? Al menos, nos haremos más fuertes.[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]A veces hay que mirar el lado positivo y hacer lo que hay que hacer, ¿sabes?[n][w][e]

[msg MSG_343_0_0 [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0][vp 3 0 65535 2123 0 0][f 4 23 1 3 3 25 25]No pillas lo que digo. No me refiero a ir más rápido, sino a motivarnos a tope.[n][w][e]

[msg MSG_344_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][f 4 23 1 3 0 25 25]En lugar de pensar en esto o aquello, ganamos más si derrotamos a un par de sombras, ¿no?[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Ahora mismo no tenemos ni idea de nada, pero todo acabará cobrando sentido. Confía en mí.[n][w][e]

[msg MSG_345_0_0 [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0][vp 3 0 65535 2105 0 0][f 4 23 1 3 3 25 25]Bueno, tú decides, pero no olvides que a veces hay que sacar tajada de la buena racha.[n][w][e]

[msg MSG_346_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][f 4 23 1 3 0 25 25]Créeme, sé a dónde quieres llegar. Un giro inesperado del guion y volvemos a la casilla de salida.[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Dicho eso, deberíamos esforzarnos para hacernos más fuertes y estar listos para lo que sea.[n][w][e]

[msg MSG_347_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][f 4 23 1 3 1 25 25]Bueno, ¡la decisión es tuya![n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]Tanto si quieres que avancemos o nos retiremos, cuenta conmigo, tía.[n][w][e]

