[msg MSG_000_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 1 0 0 1 0 0][f 4 23 0 1 0 25 25]Las hortalizas que veo en la tienda son de lo más normales y corrientes.[n][w][e]

[msg MSG_000_5_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 1 0 0 2 0 0]¿Conoces las hortalizas esas que solo come la gente como Kirijo?[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0][vp 1 0 0 3 0 0]Si pudiésemos cultivar algo así, ¡nos haríamos millonarios! ¿O no?[n][w][e]

[sel SEL_001_0_0 top]
[f 2 1]No digas tonterías.[e]
[f 2 1]Depende de si nos esforzamos mucho.[e]
[f 2 1]¿Sabes lo que estás haciendo?[e]

[msg MSG_002_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 1 0 0 4 0 0][f 4 23 0 1 1 25 25]Ja, ja, bueno, ya que estamos en ello, no tiene nada de malo querer darlo todo, ¿verdad?[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0][vp 1 0 0 5 0 0]A ti los trabajos manuales se te dan genial. ¿Qué te parece? ¿Aunamos fuerzas y nos hacemos famosos?[n][w][e]

[msg MSG_003_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 1 0 0 6 0 0][f 4 23 0 1 1 25 25]¡Ay! ¿En serio quieres que lo hagamos? ¡Toma ya! ¡Hay que apuntar alto![n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0][vp 1 0 0 7 0 0]A ti los trabajos manuales se te dan genial. ¿Qué te parece? ¿Aunamos fuerzas y nos hacemos famosos?[n][w][e]

[msg MSG_004_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 1 0 0 8 0 0][f 4 23 0 1 1 25 25]No, ¡ni una pizca! Una vez intenté plantar gloria de la mañana, ¡y me sorprendió que muriesen tan rápido![n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0][vp 1 0 0 9 0 0]Pero a ti los trabajos manuales se te dan genial, así que todo tuyo. ¿Te parece?[n][w][e]

[msg MSG_005_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 1 0 0 10 0 0][f 4 23 0 1 0 25 25]Bueno, deberíamos ponernos a currar antes de adelantar acontecimientos.[n][w][e]

[msg MND_006_0_0]
[f 2 1]He regado las macetas de la azotea con Junpei.[n][w][e]

[msg MSG_007_0_0 [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0][vp 1 0 0 11 0 0][f 4 23 0 1 3 25 25]Uf, me está empezando a doler la espalda y tengo las manos llenas de barro...[n][w][e]

[msg MND_008_0_0]
[f 2 1]Se nota el mimo que les damos,[n]ahora puedo cosechar más.[n][w][e]

[msg MSG_009_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 1 0 0 12 0 0][f 4 23 0 1 1 25 25]Pero tengo que seguir, ¡por la marca de verduras de lujo de Junpei![n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0][vp 1 0 0 13 0 0]No sé cómo voy a lidiar con todo esto solo, así que no dudes en volver, ¿eh?[n][w][e]

[msg MSG_010_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 1 0 0 14 0 0][f 4 23 0 1 1 25 25]¡Creced bonitas, mis preciosas y lujosas hortalizas![n][w][e]

[msg MSG_010_5_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 1 0 0 15 0 0][f 4 23 0 1 0 25 25]Pero... Tanto regar y tirar de las malas hierbas, sin olvidarnos de los bichos...[n][w][e]
[f 2 1][bup 3 3 65535 65535 0 0][vp 1 0 0 16 0 0][f 4 23 0 1 3 25 25]Es un trabajo monótono. Siento que es improductivo.[n][w][e]

[sel SEL_011_0_0 top]
[f 2 1]¡Ahí está la gracia![e]
[f 2 1]Imagina que es un entrenamiento.[e]
[f 2 1]A las plantas hay que tratarlas como a tu pareja.[e]

[msg MSG_012_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 1 0 0 17 0 0][f 4 23 0 1 0 25 25]A veces eres una chica de lo más rara, ¿sabes? Aunque la verdad es que...[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0][vp 1 0 0 18 0 0]La idea de cultivar algo poco a poco... me resulta familiar.[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0][vp 1 0 0 19 0 0][f 4 23 0 1 1 25 25]¡Ah, sí! Es como subir de nivel en un juego. Oye, igual esto no está tan mal en el fondo...[n][w][e]

[msg MSG_013_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 1 0 0 20 0 0][f 4 23 0 1 0 25 25]¿Qué eres, una monja o algo? ¿Intentas llegar a la iluminación o qué?[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0][vp 1 0 0 21 0 0][f 4 23 0 1 1 25 25]Bueno, si entrenamos y cultivamos hortalizas... es como matar dos pájaros de un tiro.[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0][vp 1 0 0 22 0 0]¿Probamos a coger moscas con los palillos, como hacían los maestros espadachines?[n][w][e]

[msg MSG_014_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 65535 65535 0 0][vp 1 0 0 23 0 0][f 4 23 0 1 4 25 25]¡¿Qué?! ¿Qué puñetas significa eso?[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0][vp 1 0 0 24 0 0][f 4 23 0 1 0 25 25]Pero, eh... Igual tienes razón.[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0][vp 1 0 0 25 0 0]Me gusta tratarlas con amor y cariño. ¿Le parece bien, señorita iluminada?[n][w][e]

[msg MSG_015_0_0 [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0][vp 1 0 0 26 0 0][f 4 23 0 1 3 25 25]Todavía nos queda mucho por delante antes de poder ganarnos la vida con las hortalizas.[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0][vp 1 0 0 27 0 0][f 4 23 0 1 1 25 25]En fin, he sido yo quien te ha pedido que me ayudes, así que me toca a mí cuidarlas.[n][w][e]

[msg MND_016_0_0]
[f 2 1]He regado las macetas de la azotea con Junpei.[n][w][e]

[msg MSG_017_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 1 0 0 28 0 0][f 4 23 0 1 1 25 25]¡Tachááááán! ¡Las hortalizas han subido de nivel![n][w][e]

[msg MND_018_0_0]
[f 2 1]Se nota el mimo que les damos,[n]ahora puedo cosechar más.[n][w][e]

[msg MSG_019_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 1 0 0 29 0 0][f 4 23 0 1 1 25 25]Puf, otro día trabajando a destajo. Volvamos abajo.[n][w][e]

