[msg MSG_000_0_0_1 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 50 0 0]未使用[n][w][e]
[f 2 1][bup 6 0 65535 50 0 0]未使用[n][w][e]
[f 2 1][bup 6 0 65535 50 0 0]未使用[n][w][e]

[sel SEL_001_0_0_1 top]
[f 2 1]未使用[e]
[f 2 1]未使用[e]
[f 2 1]未使用[e]

[msg MSG_002_0_0_1 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 50 0 0]未使用[n][w][e]
[f 2 1][bup 6 0 65535 50 0 0]未使用[n][w][e]

[msg MSG_003_0_0_1 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 50 0 0]未使用[n][w][e]
[f 2 1][bup 6 0 65535 50 0 0]未使用[n][w][e]

[msg MSG_004_0_0_1 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 50 0 0]未使用[n][w][e]
[f 2 1][bup 6 0 65535 50 0 0]未使用[n][w][e]

[msg MSG_005_0_0_1 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 50 0 0]未使用[n][w][e]

[msg MND_006_0_0_1]
[f 2 1]未使用[n][w][e]

[msg MSG_007_0_0_1 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 50 0 0]未使用[n][w][e]
[f 2 1][bup 6 0 65535 50 0 0]未使用[n][w][e]

[msg MSG_000_0_0_2 [Junpei Iori]]
[f 2 1][bup 3 0 65535 50 0 0][vp 3 0 65535 2138 0 0]Oye, ¿podéis oírme? Ay, genial. Parece que ya tenemos conexión.[n][w][e]
[f 2 1][bup 3 1 65535 50 0 0]¿Cómo va la cosa? Tiene pinta de que estáis en racha.[n][w][e]

[msg MSG_001_0_0_2 [Junpei Iori]]
[f 2 1][bup 3 2 65535 50 0 0]Ryoji dijo que era imposible ganar.[n][w][e]
[f 2 1][bup 3 1 65535 50 0 0]Pero a juzgar por cómo van las cosas, creo que esto va a estar tirado. Je, era broma. Ojalá fuera así.[n][w][e]

[sel SEL_002_0_0_2 top]
[f 2 1]No os descuidéis.[e]
[f 2 1]Bueno, ya veremos.[e]
[f 2 1]Quizá esté chupado.[e]

[msg MSG_003_0_0_2 [Junpei Iori]]
[f 2 1][bup 3 1 65535 50 0 0][vp 3 0 65535 2133 0 0]Tranqui, colega. No me lo estoy tomando a la ligera, lo que pasa es que me siento seguro de mí mismo.[n][w][e]
[f 2 1][bup 3 1 65535 50 0 0]Es mejor pensar que puedes lograrlo que creer que no serás capaz de hacerlo, ¿no te parece?[n][w][e]

[msg MSG_004_0_0_2 [Junpei Iori]]
[f 2 1][bup 3 1 65535 50 0 0][vp 3 0 65535 2133 0 0]Muy bien. Nos toca enfrentarnos a un monstruo con todas las de la ley, ¿no?[n][w][e]
[f 2 1][bup 3 1 65535 50 0 0]Lo mejor es tener confianza para que los nervios no nos jueguen una mala pasada.[n][w][e]

[msg MSG_005_0_0_2 [Junpei Iori]]
[f 2 1][bup 3 1 65535 50 0 0][vp 3 0 65535 2132 0 0]Je, je. Todo ese pesimismo por la derrota inminente no te ha amedrentado lo más mínimo.[n][w][e]
[f 2 1][bup 3 1 65535 50 0 0]Eres de lo que no hay, mujer. ¡Incluso podría considerarte una rival digna de mí![n][w][e]

[msg MSG_006_0_0_2 [Junpei Iori]]
[f 2 1][bup 3 9 65535 50 0 0]No me malinterpretes, pero sé que iba en serio cuando dijo que no podríamos derrotar a Nix.[n][w][e]
[f 2 1][bup 3 1 65535 50 0 0]¡Pues cuando le demostremos lo contrario, me voy a partir el culo![n][w][e]

[msg MND_007_0_0_2]
[f 2 1]Siento que todos se han fortalecido ahora que nos dirigimos hacia el combate final.[n][w][e]

[msg MSG_008_0_0_2 [Junpei Iori]]
[f 2 1][bup 3 1 65535 50 0 0]¡Os deseo lo mejor, chicos! ¡Si estáis en un apuro, ya sabéis a quién llamar![n][w][e]

[msg MSG_000_0_0_3 [Ken Amada]]
[f 2 1][bup 8 0 65535 50 0 0][vp 3 0 65535 7002 0 0][nl], ¡¿me oyes?![n][w][e]
[f 2 1][bup 8 1 65535 50 0 0]¡Lo habéis hecho muy bien con el guardián![n][w][e]

[msg MSG_001_0_0_3 [Ken Amada]]
[f 2 1][bup 8 0 65535 50 0 0]A medida que nos acercamos a la cima, no paro de dar vueltas a un montón de cosas.[n][w][e]
[f 2 1][bup 8 0 65535 50 0 0]¿Así es cómo se sentirá el héroe justo antes de que acabe la temporada?[n][w][e]

[sel SEL_002_0_0_3 top]
[f 2 1]Sí, es posible.[e]
[f 2 1]No es exactamente lo mismo...[e]
[f 2 1]Ni idea.[e]

[msg MSG_003_0_0_3 [Ken Amada]]
[f 2 1][bup 8 0 65535 50 0 0][vp 3 0 65535 7068 0 0]Es toda una experiencia, ¿verdad?[n][w][e]
[f 2 1][bup 8 0 65535 50 0 0]Nunca imaginé que mis sueños se harían realidad...[n][w][e]

[msg MSG_004_0_0_3 [Ken Amada]]
[f 2 1][bup 8 1 65535 50 0 0][vp 3 0 65535 7133 0 0]Ja, ja. Lo siento. No te preocupes, sé que lo que hacen es un papel.[n][w][e]
[f 2 1][bup 8 0 65535 50 0 0]Es que pensé que imaginarnos como héroes podría ser de ayuda.[n][w][e]

[msg MSG_005_0_0_3 [Ken Amada]]
[f 2 1][bup 8 0 65535 50 0 0][vp 3 0 65535 7063 0 0]Ay, espero que no me hayas malinterpretado. Sé que es ficción.[n][w][e]
[f 2 1][bup 8 0 65535 50 0 0]Es que pensé que si intentaba ponerme en la piel de un héroe, podría verlo todo con mejores ojos.[n][w][e]

[msg MSG_006_0_0_3 [Ken Amada]]
[f 2 1][bup 8 2 65535 50 0 0]Sabes que los héroes no son fuertes porque nunca pierden, ¿verdad?[n][w][e]
[f 2 1][bup 8 2 65535 50 0 0]Lo son porque nunca se rinden. Bueno, o así lo veo yo.[n][w][e]

[msg MND_007_0_0_3]
[f 2 1]Siento que todos se han fortalecido ahora que nos dirigimos hacia el combate final.[n][w][e]

[msg MSG_008_0_0_3 [Ken Amada]]
[f 2 1][bup 8 0 65535 50 0 0]Según Fuuka, quedan un montón de guardianes de aquí a la cima.[n][w][e]
[f 2 1][bup 8 1 65535 50 0 0]Pero lo conseguiremos. ¡Yo estoy listo para lo que sea![n][w][e]

[msg MSG_000_0_0_4 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 50 0 0][vp 3 0 65535 4086 0 0]Buen trabajo. Ahora toca seguir adelante.[n][w][e]

[msg MSG_001_0_0_4 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 50 0 0]Vamos de camino a la 250.ª planta. Hemos recorrido un buen trecho...[n][w][e]
[f 2 1][bup 5 0 65535 50 0 0]Ni siquiera ha pasado un año desde que la mayoría de vosotros os unisteis al SEES. Lo habéis hecho estupendamente.[n][w][e]
[f 2 1][bup 5 3 65535 50 0 0]No tengo palabras para agradecer vuestros esfuerzos a pesar de todo lo que habéis padecido.[n][w][e]

[sel SEL_002_0_0_4 top]
[f 2 1]No hay de qué.[e]
[f 2 1]Me debes una.[e]
[f 2 1]Tú invitas a ramen.[e]

[msg MSG_003_0_0_4 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 50 0 0][vp 3 0 65535 4131 0 0]Je, je. Es muy generoso por tu parte. Gracias.[n][w][e]

[msg MSG_004_0_0_4 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 50 0 0][vp 3 0 65535 4028 0 0]Eso es cierto. Aunque no creo que pueda pagar esa deuda por completo.[n][w][e]

[msg MSG_005_0_0_4 [Mitsuru Kirijo]]
[f 2 1][bup 5 4 65535 50 0 0][vp 3 0 65535 4098 0 0]¿Ramen? ¿Y por qué algo tan simple? Podrías... No, tienes toda la razón.[n][w][e]
[f 2 1][bup 5 1 65535 50 0 0]Al fin y al cabo, hemos estado luchando por recuperar nuestras vidas.[n][w][e]

[msg MSG_006_0_0_4 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 50 0 0]Aquellos a quienes hemos perdido están con nosotros en espíritu.[n][w][e]
[f 2 1][bup 5 0 65535 50 0 0]Venceremos sí o sí. El futuro de todos depende de nosotros.[n][w][e]

[msg MND_007_0_0_4]
[f 2 1]Siento que todos se han fortalecido ahora que nos dirigimos hacia el combate final.[n][w][e]

[msg MSG_008_0_0_4 [Mitsuru Kirijo]]
[f 2 1][bup 5 8 65535 50 0 0]Muy bien. Seguid haciendo que los guardianes caigan como moscas.[n][w][e]
[f 2 1][bup 5 8 65535 50 0 0]Aún quedan cinco, así que estad atentos. Yo también estaré preparada por si me necesitáis.[n][w][e]

[msg MSG_000_0_0_5 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 50 0 0][vp 3 0 65535 5113 0 0]Buen trabajo, equipo.[n][w][e]
[f 2 1][bup 6 0 65535 50 0 0]Ya queda nada y menos para llegar a la cima. Tened cuidad... ¿Eh?[n][w][e]

[msg MSG_001_0_0_5 [Koromaru]]
[f 2 1][bup 9 0 65535 50 0 0][vp 3 0 65535 8008 0 0]¡Guau![n][w][e]

[msg MSG_002_0_0_5 [Fuuka Yamagishi]]
[f 2 1][bup 6 6 65535 50 0 0]Oye, parece que Korocito quiere decirnos algo.[n][w][e]
[f 2 1][bup 6 0 65535 50 0 0]¿Qué ocurre, Korocito?[n][w][e]

[msg MSG_003_0_0_5 [Koromaru]]
[f 2 1][bup 9 0 65535 50 0 0]¡Guau, guau![n][w][e]
[f 2 1][bup 9 0 65535 50 0 0]¡Guau, guau! ¡Guau![n][w][e]

[msg MND_004_0_0_5]
[f 2 1]Siento que Koromaru está desesperado...[n][w][e]
[f 2 1]Parece que nos está animando.[n][w][e]

[msg MSG_005_0_0_5 [Koromaru]]
[f 2 1][bup 9 0 65535 50 0 0]¡Guau![n][w][e]

[sel SEL_006_0_0_5 top]
[f 2 1]También contamos contigo.[e]
[f 2 1]Te has ganado una recompensa.[e]
[f 2 1]¡Guau, guau, guau![e]

[msg MSG_007_0_0_5 [Koromaru]]
[f 2 1][bup 9 1 65535 50 0 0][vp 3 0 65535 8010 0 0]¡Guau![n][w][e]

[msg MND_008_0_0_5]
[f 2 1]Parece que Koromaru está incluso más motivado.[n][w][e]
[f 2 1]Siento que todos se han fortalecido ahora que nos dirigimos hacia el combate final.[n][w][e]

[msg MSG_009_0_0_5 [Koromaru]]
[f 2 1][bup 9 0 65535 50 0 0]Grrr... ¡Arf![n][w][e]

[msg MSG_010_0_0_5 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 50 0 0]Je, je. ¿Todo listo, Korocito? ¡Pues arreando![n][w][e]

[msg MSG_000_0_0_6 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 50 0 0][vp 3 0 65535 3085 0 0]Habéis luchado como unos jabatos. Ya tenemos que estar cerca de la línea de meta...[n][w][e]

[msg MSG_001_0_0_6 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 50 0 0]Habéis luchado muchísimo.[n][w][e]
[f 2 1][bup 4 0 65535 50 0 0]Cuando os sintáis desanimados, recordad cuánto sudor y lágrimas habéis derramado hasta llegar aquí.[n][w][e]

[sel SEL_002_0_0_6 top]
[f 2 1]Qué profundo.[e]
[f 2 1]Tampoco ha sido para tanto.[e]
[f 2 1]Eso es irrelevante.[e]

[msg MSG_003_0_0_6 [Akihiko Sanada]]
[f 2 1][bup 4 1 65535 50 0 0][vp 3 0 65535 3130 0 0]Espero que así te mantengas motivada.[n][w][e]

[msg MSG_004_0_0_6 [Akihiko Sanada]]
[f 2 1][bup 4 1 65535 50 0 0][vp 3 0 65535 3130 0 0]Cierto. Parece que tú nunca pierdes la calma.[n][w][e]
[f 2 1][bup 4 0 65535 50 0 0]Aunque sabemos muy bien cuánto te has esforzado.[n][w][e]

[msg MSG_005_0_0_6 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 50 0 0][vp 3 0 65535 3136 0 0]Mm... ¿Estás diciendo que la perseverancia por sí sola no sirve de nada contra nuestro oponente?[n][w][e]
[f 2 1][bup 4 0 65535 50 0 0]Bueno, puede que tengas razón. Aun así, confío en las habilidades que hemos conseguido gracias a ella.[n][w][e]

[msg MSG_006_0_0_6 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 50 0 0]En fin, que no quiero quedarme con remordimientos.[n][w][e]
[f 2 1][bup 4 0 65535 50 0 0]Haré las cosas lo mejor que pueda. Y tú tienes que hacer lo mismo, líder.[n][w][e]

[msg MND_007_0_0_6]
[f 2 1]Siento que todos se han fortalecido ahora que nos dirigimos hacia el combate final.[n][w][e]

[msg MSG_008_0_0_6 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 50 0 0]Perdón por interrumpir vuestra buena racha. Seguid así.[n][w][e]
[f 2 1][bup 4 9 65535 50 0 0]A estas alturas hay que sacar toda la artillería, ¡así que id a por todas! Yo también estoy preparado por si lo necesitáis.[n][w][e]

[msg MSG_000_0_0_7 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 50 0 0][vp 3 0 65535 1061 0 0]¡Eri...! ¿Me oye?[n][w][e]
[f 2 1][bup 2 1 65535 50 0 0]¡Lo estáis haciendo fenomenal! ¡Os queda casi nada![n][w][e]

[msg MSG_001_0_0_7 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 50 0 0]Sé que no hace falta que lo diga, pero tenemos que ir a por todas y vencer, ¿vale?[n][w][e]
[f 2 1][bup 2 0 65535 50 0 0]Digo esto porque... hemos compartido muchas cosas juntos y me gustaría seguir compartiendo muchas más...[n][w][e]
[f 2 1][bup 2 3 65535 50 0 0]Ay, perdonad que me ponga así y diga estas cosas...[n][w][e]

[sel SEL_002_0_0_7 top]
[f 2 1]No tiene nada de raro.[e]
[f 2 1]Sí, es raro.[e]
[f 2 1]La verdad es que es muy propio de ti.[e]

[msg MSG_003_0_0_7 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 50 0 0][vp 3 0 65535 1132 0 0]¡Ah, qué bien! Pensaba que estaba pareciendo algo forzado, pero me alegro que no te moleste.[n][w][e]

[msg MSG_004_0_0_7 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 50 0 0][vp 3 0 65535 1132 0 0]¡Oye, para ya! Aunque sí que es un poco raro. Ja, ja. Pero así es como me siento, por eso no me arrepiento de haberlo dicho.[n][w][e]

[msg MSG_005_0_0_7 [Yukari Takeba]]
[f 2 1][bup 2 4 65535 50 0 0][vp 3 0 65535 1098 0 0]¿E-en serio? Bueno, creo que soy más así cuando estoy contigo...[n][w][e]

[msg MSG_006_0_0_7 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 50 0 0]No pienso rendirme hasta el final. Bueno, mejor dicho... no pienso permitir que haya un final.[n][w][e]
[f 2 1][bup 2 0 65535 50 0 0]Así que, luchemos por seguir construyendo una vida juntos, líder.[n][w][e]

[msg MND_007_0_0_7]
[f 2 1]Siento que todos se han fortalecido ahora que nos dirigimos hacia el combate final.[n][w][e]

[msg MSG_008_0_0_7 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 50 0 0]Bueno, os lo dejo a vosotros. ¡Ya casi lo tenéis! ¡Estáis a punto de conseguirlo![n][w][e]

[msg MSG_000_0_0_8 [Aigis]]
[f 2 1][bup 7 0 65535 50 0 0][vp 3 0 65535 6006 0 0]¡Buen trabajo, equipo! Solo queda uno. Estáis muy cerquita.[n][w][e]

[msg MSG_001_0_0_8 [Aigis]]
[f 2 1][bup 7 3 65535 50 0 0]La verdad es que estaba algo preocupada.[n][w][e]
[f 2 1][bup 7 3 65535 50 0 0]Pensaba que mi deseo de ahorrarle el sufrimiento a quienes aprecio me impediría luchar.[n][w][e]
[f 2 1][bup 7 1 65535 50 0 0]Pero parece que es todo lo contario. Ahora me siento con más fuerzas que nunca para pelear.[n][w][e]

[sel SEL_002_0_0_8 top]
[f 2 1]A eso se le llama "valor".[e]
[f 2 1]Qué interesante.[e]
[f 2 1]En ti sí que se puede confiar.[e]

[msg MSG_003_0_0_8 [Aigis]]
[f 2 1][bup 7 1 65535 50 0 0][vp 3 0 65535 6107 0 0]¡Así que esto es tener valor! Supongo que así os habréis sentido los demás todo este tiempo...[n][w][e]

[msg MSG_004_0_0_8 [Aigis]]
[f 2 1][bup 7 1 65535 50 0 0][vp 3 0 65535 6131 0 0]De hecho, seguro que todos os sentisteis así desde el momento en el que decidisteis luchar.[n][w][e]

[msg MSG_005_0_0_8 [Aigis]]
[f 2 1][bup 7 1 65535 50 0 0][vp 3 0 65535 6025 0 0]Sí, cuenta conmigo cuando te haga falta.[n][w][e]

[msg MSG_006_0_0_8 [Aigis]]
[f 2 1][bup 7 1 65535 50 0 0]Me aferraré a este nuevo sentimiento para tener fuerzas y poder luchar a vuestro lado.[n][w][e]

[msg MND_007_0_0_8]
[f 2 1]Siento que todos se han fortalecido ahora que nos dirigimos hacia el combate final.[n][w][e]

[msg MSG_008_0_0_8 [Aigis]]
[f 2 1][bup 7 1 65535 50 0 0]Id con cuidado y tened mucha suerte. Y recordad: estaré ahí en cuestión de segundos si me necesitáis.[n][w][e]

[msg MSG_000_0_0_9 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 50 0 0][vp 3 0 65535 5131 0 0]¡La señal del guardián se ha perdido![n][w][e]
[f 2 1][bup 6 1 65535 50 0 0]¡Lo hemos conseguido! ¡Ese era el último![n][w][e]

[sel SEL_001_0_0_9 top]
[f 2 1]Ya era hora.[e]
[f 2 1]Ahora viene la batalla de verdad.[e]

[msg MSG_002_0_0_9 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 50 0 0][vp 3 0 65535 5144 0 0]Tienes razón. No hemos parado de dar el callo...[n][w][e]

[msg MSG_003_0_0_9 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 50 0 0][vp 3 0 65535 5145 0 0]Sí, tienes razón. Ya casi hemos llegado a nuestro objetivo...[n][w][e]

[msg MSG_004_0_0_9 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 50 0 0]Ahora que ya no están los guardianes, el camino ha quedado despejado.[n][w][e]
[f 2 1][bup 6 0 65535 50 0 0]Percibo una zona sin muro exterior un poco más arriba.[n][w][e]
[f 2 1][bup 6 2 65535 50 0 0]Seguramente ese sea el sitio del que nos habló Ryoji.[n][w][e]

[msg MSG_005_0_0_9 [Fuuka Yamagishi]]
[f 2 1][bup 6 2 65535 50 0 0]¡Venga, vamos todos juntos![n][w][e]

[msg MSG_006_0_0_9 [（ＳＥ）伊織 順平]]
[f 2 1]おうよ！[n][w][e]

[msg MSG_007_0_0_9 [（ＳＥ）岳羽 ゆかり]]
[f 2 1]うん！[n][w][e]

[msg MSG_008_0_0_9 [（ＳＥ）真田 明彦]]
[f 2 1]ああ。[n][w][e]

[msg MSG_009_0_0_9 [（ＳＥ）桐条 美鶴]]
[f 2 1]そうだな。[n][w][e]

[msg MSG_010_0_0_9 [（ＳＥ）コロマル]]
[f 2 1]ワン！[n][w][e]

[msg MSG_011_0_0_9 [（ＳＥ）天田 乾]]
[f 2 1]はい！[n][w][e]

[msg MSG_012_0_0_9 [（ＳＥ）アイギス]]
[f 2 1]…はい！[n][w][e]

[msg MND_013_0_0_9]
[f 2 1]Siento que todos se han fortalecido ahora que nos dirigimos hacia el combate final.[n][w][e]

[msg SYS_014_0_0_9]
[f 2 1]El vínculo social del Juicio ha alcanzado su nivel máximo. ¡Ahora puedes crear a [clr 35]Mesías[clr 27], el salvador![n][w][e]

[msg MSG_015_0_0_9 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 50 0 0]Tened cuidado por ahí. ¡Os deseo mucha suerte![n][w][e]

