[msg MSG_000_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 3 0 65535 5097 0 0]¡Qué buen día hace![n][w][e]

[msg MSG_000_3_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0]Madre mía, esto está a reventar de gente...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][f 4 23 0 6 0 25 25]Creía que estas muchedumbres solo se veían en la isla Puerto.[n][w][e]

[msg MSG_000_5_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0]Antes de mudarme a la residencia, no venía mucho a la zona de tiendas, pero me encanta.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]¡Ni me había dado cuenta de lo cerca que tenía estos sitios![n][w][e]

[msg MSG_001_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0]Mmm, [nl]...[n][w][e]

[msg MSG_002_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5076 0 0]¿Qué sueles hacer en tu tiempo libre?[n][w][e]

[sel SEL_003_0_0 top]
[f 2 1]Quedarme en mi habitación.[e]
[f 2 1]Salir con mis amigos.[e]
[f 2 1]No me acuerdo.[e]

[msg MSG_004_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 3 0 65535 5107 0 0][f 5 13 3 15 6]Ah, que eres de quedarte en casa.[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0]Pues no me lo esperaba. No pensaba que fueras hogareña.[n][w][e]

[msg MSG_004_5_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0]Yo también lo soy, pero... supongo que salta a la vista.[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0][f 4 23 0 6 1 25 25]Me alegra que tengamos eso en común.[n][w][e]

[msg MND_005_0_0]
[f 2 1]Fuuka esboza una sonrisa.[n][w][e]
[f 2 1]Hoy he aprendido un poco más sobre ella.[n][w][e]

[msg MSG_006_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 3 0 65535 5107 0 0][f 5 13 3 30 6]Bien. Parece que tienes muchos amigos.[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0][f 4 23 0 6 3 25 25]La verdad es que yo no tengo muchos...[n][w][e]

[msg MSG_007_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0]Me encantaría volver a salir y hacer algo así en otra ocasión.[n][w][e]

[msg MND_008_0_0]
[f 2 1]Fuuka parece un poco avergonzada.[n][w][e]
[f 2 1]Siento que hoy nuestra relación se ha estrechado.[n][w][e]

[msg MSG_009_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5094 0 0]Ah...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][f 4 25 6]...[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0][f 4 23 0 6 3 25 25]Mmm, eeeh...[n][w][e]

[msg MSG_009_5_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0]¿He sacado un tema incómodo?[n][w][e]

[msg MND_010_0_0]
[f 2 1]Fuuka parece preocupada.[n][w][e]
[f 2 1]Siento que hoy nuestra relación no ha cambiado nada...[n][w][e]

[msg MSG_011_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5079 0 0]Ah, siento distanciarme.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Como hoy hace un tiempo tan agradable, ¿por qué no compramos algo y nos sentamos a comer en un banco?[n][w][e]

[msg MND_012_0_0]
[f 2 1]Dimos una vuelta por la zona de tiendas antes de volver a la residencia.[n][w][e]

