[msg MSG_000_0_0 [Chico violento]]
[f 2 1][vp 1 0 0 1 0 0][f 5 21 0 1001]¿Qué has dicho? ¡Más te vale cerrar la boca, zorra![n][w][e]

[msg MSG_001_0_0 [Chico sonriente]]
[f 2 1][vp 1 0 0 2 0 0][f 5 21 0 1002]Como no te comportes, perderás algo más que la cartera.[n][w][e]

[msg MSG_002_0_0 [Yukari Takeba]]
[f 2 1][bup 2 2 65535 65535 0 0][vp 0 0 0 3 0 0]...[n][w][e]

[sel SEL_003_0_0 top]
[f 2 1]Te vas a enterar.[e]
[f 2 1]Llamaré a la policía.[e]
[f 2 1]¿Qué ocurre?[e]

[msg MSG_004_0_0 [Yukari Takeba]]
[f 2 1][bup 2 4 65535 65535 0 0][vp 1 0 0 4 0 0]¡...![n][w][e]

[msg MSG_005_0_0 [Chico violento]]
[f 2 1][vp 1 0 0 5 0 0][f 5 21 0 1001]¿Eh? ¿Quién narices eres tú?[n][w][e]

[msg MSG_006_0_0 [Yukari Takeba]]
[f 2 1][bup 2 4 65535 65535 0 0][vp 1 0 0 6 0 0]Eh, ¿no te he dicho que esperaras?[n][w][e]

[msg MSG_007_0_0 [Chico violento]]
[f 2 1][vp 1 0 0 7 0 0][f 5 21 0 1001]¿Eh? ¿Quién narices eres tú?[n][w][e]

[sel SEL_008_0_0 top]
[f 2 1]Su novia.[f 2 9 1 1 344][e]
[f 2 1]Su amiga.[e]
[f 2 1]Solo pasaba por aquí.[e]

[msg MSG_009_0_0 [Yukari Takeba]]
[f 2 1][bup 2 4 65535 65535 0 0][vp 1 0 0 8 0 0]¡Espera! Pero ¿qué dices?[n][w][e]

[msg MSG_010_0_0 [Chico violento]]
[f 2 1][vp 1 0 0 9 0 0][f 5 21 0 1001]Menuda zorra. ¡Te vamos a dar para el pelo![n][w][e]

[msg MSG_011_0_0 [Chico sonriente]]
[f 2 1][vp 1 0 0 10 0 0][f 5 21 0 1002]No queremos nada de una estupida como tú. ¡Lárgate si quieres salir ilesa![n][w][e]

[msg MSG_012_0_0 [Chico violento]]
[f 2 1][vp 1 0 0 11 0 0][f 5 21 0 1001]¿Qué cojones? ¡Se está sorteando una paliza y tú tienes todas las papeletas![n][w][e]

[msg MSG_013_0_0 [Chico sonriente]]
[f 2 1][vp 1 0 0 12 0 0][f 5 21 0 1002]Pues métete en tus cosas, joder. ¿Quieres problemas?[n][w][e]

[msg MSG_014_0_0 [Chico violento]]
[f 2 1][vp 1 0 0 13 0 0][f 5 21 0 1001]¿Qué? ¿Quieres presumir delante de la chica? ¡Nosotros somos más, pringada![n][w][e]

[msg MSG_015_0_0 [Yukari Takeba]]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 14 0 0]G-gracias.[n][w][e]

[msg MND_016_0_0]
[f 2 1]Yukari parece agradecida.[n][w][e]
[f 2 1]Parece que nuestra relación se ha estrechado.[n][w][e]

[msg MSG_017_0_0 [Yukari Takeba]]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 15 0 0]La cosa se ha puesto seria. Aunque no tenías que darles tal paliza.[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0][vp 0 0 0 16 0 0]...[n][w][e]

[msg MSG_018_0_0 [Yukari Takeba]]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 17 0 0]Oye, ¿por qué me has seguido?[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 18 0 0]¿No te dije que esperases?[n][w][e]

[msg MSG_019_0_0 [Yukari Takeba]]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 19 0 0]¿Creías que necesitaba que me salvaras?[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0][vp 0 0 0 20 0 0]...[n][w][e]
[f 2 1][bup 2 2 65535 65535 0 0][vp 1 0 0 21 0 0][f 4 23 0 2 2 25 25]No soy una pobre indefensa, que lo sepas.[n][w][e]

[msg MSG_019_3_0 [Yukari Takeba]]
[f 2 1][bup 2 2 65535 65535 0 0][vp 1 0 0 22 0 0]He recuperado la cartera yo solita.[n][w][e]
[f 2 1][bup 2 2 65535 65535 0 0][vp 1 0 0 23 0 0]¡No necesitaba tu ayuda![n][w][e]

[sel SEL_020_0_0 top]
[f 2 1]Lo siento.[e]
[f 2 1]Está bien apoyarse en los demás.[e]
[f 2 1]Somos chicas, así que...[f 2 9 1 1 70][e]

[msg MSG_021_0_0 [Yukari Takeba]]
[f 2 1][bup 2 3 65535 65535 0 0][vp 0 0 0 24 0 0]...[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 25 0 0]No te disculpes...[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 26 0 0][f 5 13 7 15 2]No, soy yo la que tendría que disculparse. Y gracias.[n][w][e]

[msg MSG_022_0_0 [Yukari Takeba]]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 27 0 0]Bueno, me marcho. Ya estoy bien. Lo siento de nuevo.[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 28 0 0]Adiós.[n][w][e]

[msg MSG_023_0_0 [Yukari Takeba]]
[f 2 1][bup 2 2 65535 65535 0 0][vp 1 0 0 29 0 0]¡Que no! Ya te lo he dicho, no quiero depender de los demas toda mi vida.[n][w][e]
[f 2 1][bup 2 2 65535 65535 0 0][vp 1 0 0 30 0 0]Yo...[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0][vp 0 0 0 31 0 0][f 4 23 0 2 3 25 25]...[n][w][e]

[msg MSG_023_3_0 [Yukari Takeba]]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 32 0 0]Perdona, me he pasado. Has venido porque estabas preocupada por mí, ¿verdad?[n][w][e]

[msg MSG_024_0_0 [Yukari Takeba]]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 33 0 0]Bueno, me marcho. Ya estoy bien. Lo siento de nuevo.[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 34 0 0]Adiós.[n][w][e]

[msg MSG_024_5_0 [Yukari Takeba]]
[f 2 1][cut 2 2 1][e]

[msg MSG_025_0_0 [Yukari Takeba]]
[f 2 1][bup 2 2 65535 65535 0 0][vp 1 0 0 35 0 0]¡¿Qué quieres decir con eso?! ¡¿Y qué si somos chicas?![n][w][e]
[f 2 1][bup 2 2 65535 65535 0 0][vp 1 0 0 36 0 0]¿Tengo que esconderme detrás de los demas toda la vida, como mi madre?![n][w][e]

[msg MSG_026_0_0 [Yukari Takeba]]
[f 2 1][bup 2 10 65535 65535 0 0][vp 1 0 0 37 0 0]No te burles de mí.[n][w][e]

[msg MSG_026_5_0 [Yukari Takeba]]
[f 2 1][bup 2 8 65535 65535 0 0][vp 1 0 0 38 0 0]¡Nunca te pedí ayuda! ¡Estoy muy bien yo solita![n][w][e]

[msg MND_027_0_0]
[f 2 1]Hay mucha tensión entre nosotras...[n][w][e]
[f 2 1]Parece que le he tocado la fibra sensible.[n][w][e]
[f 2 1]Nuestra relación se está volviendo inestable...[n][w][e]

[msg MSG_028_0_0 [Yukari Takeba]]
[f 2 1][bup 2 10 65535 65535 0 0][vp 1 0 0 39 0 0]Me voy a la resi...[n][w][e]

[msg MND_029_0_0]
[f 2 1]Me he despedido de Yukari y he regresado a la residencia.[n][w][e]

