[msg MND_000_0_0]
[uf 0 5 65278][uf 2 1]Es Yuko, la encargada del equipo.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]¿Debería saludarla?[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]Pues creo que sí.[e]
[uf 0 5 65278][uf 2 1]Mejor no.[e]

[msg MND_002_0_0]
[uf 0 5 65278][uf 2 1]Me he ido sin que Yuko se diera cuenta.[n][uf 1 1][e]

[msg MSG_003_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]Ah, [uf 4 1]. ¿Qué tal?[n][uf 1 1][e]

[sel SEL_004_0_0 top]
[uf 0 5 65278][uf 2 1]¿Quieres que volvamos juntas a casa?[uf 2 9 1 1 565][e]
[uf 0 5 65278][uf 2 1]Nada, hasta mañana.[e]

[msg MSG_005_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]Mmm... ¡Venga, vale![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 3 0 0][uf 4 23 0 106 1 25 25]¿Qué tal si paramos en algún sitio por el camino?[n][uf 1 1][e]

[msg MSG_006_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]Bueno, ¡hasta mañana![n][uf 1 1][e]

