[msg MSG_000_0_0 [Meek-Looking Girl]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 1 0 0][uf 5 21 0 1001]This field is soooo big![n][uf 1 1][e]

[msg MSG_001_0_0 [Spunky Boy]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 2 0 0][uf 5 21 0 1002]Wow, high school is amazing![n][uf 1 1][e]

[msg MSG_002_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]They said it's fine for us to use the schoolyard for a bit.[n][uf 1 1][e]

[msg MSG_003_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]...Normally, you wouldn't be allowed in here, understand?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]So don't touch anything you're not supposed to, and if something happens, let us know immediately.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]Can you promise that?[n][uf 1 1][e]

[msg MSG_004_0_0 [Spunky Boy]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 7 0 0][uf 5 21 0 1002]We promise![n][uf 1 1][e]

[msg MSG_005_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 8 0 0]Good. Then practice until the big hand on that clock reaches twelve. And don't go inside the school building![n][uf 1 1][e]

[msg MSG_006_0_0 [Spunky Boy]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 9 0 0][uf 5 21 0 1002]All right! Let's do this![n][uf 1 1][e]

[msg MSG_007_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]Wait, come here for a second.[n][uf 1 1][e]

[msg MSG_007_5_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 11 0 0]You need to pump your arms more.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]And don't lift your legs so high, or you might pull a muscle.[n][uf 1 1][e]

[msg MSG_008_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]Go on, give it a try! You just gotta believe in yourself![n][uf 1 1][e]

[msg MSG_009_0_0 [Spunky Boy]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 14 0 0][uf 5 21 0 1002]Woohoooo! Check this out![n][uf 1 1][e]

[msg MSG_010_0_0 [Meek-Looking Girl]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 15 0 0][uf 5 21 0 1001]Wow! Ken-chan, you're so fast![n][uf 1 1][e]

[msg MSG_010_5_0 [Meek-Looking Girl]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 16 0 0][uf 5 21 0 1001]...Hey, big sis! You should be our coach![n][uf 1 1][e]

[msg MSG_011_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 0 0][uf 3 1 1 0 0 17 0 0]Aw, I'm a real sucker when kids look at me that way...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 0 0][uf 3 1 1 0 0 18 0 0]But I've never tried coaching before...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 0 0][uf 3 1 1 0 0 19 0 0][uf 4 1]-kun, what do you think I should do?[n][uf 1 1][e]

[sel SEL_012_0_0 top]
[uf 0 5 65278][uf 2 1]Why not give it a go?[e]
[uf 0 5 65278][uf 2 1]That's for you to decide.[e]

[msg MSG_013_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 20 0 0]You really think I should?[n][uf 1 1][e]

[msg MSG_014_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 0 0][uf 3 1 1 0 0 21 0 0]Yeah, I know...[n][uf 1 1][e]

[msg MSG_015_0_0 [Spunky Boy]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 22 0 0][uf 5 21 0 1002]Come on, please![n][uf 1 1][e]

[msg MSG_016_0_0 [Kids]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 23 0 0]Pleeeease![n][uf 1 1][e]

[msg MSG_017_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 0 0][uf 3 1 1 0 0 24 0 0]Hmm...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 0 0][uf 3 1 1 0 0 25 0 0]Well, it isn't a decision to make lightly...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 0 0][uf 3 1 0 0 0 26 0 0]......[n][uf 1 1][e]

[msg MSG_017_5_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 27 0 0]All right, I'll be your coach![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 2 65535 65535 0 0][uf 3 1 1 0 0 28 0 0][uf 4 23 0 1 2 25 25]But I'm not gonna go easy on you guys! And no one's allowed to quit halfway, either![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 2 65535 65535 0 0][uf 3 1 1 0 0 29 0 0]Got it?[n][uf 1 1][e]

[msg MSG_018_0_0 [Kids]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 30 0 0]Got it, Coach Yuko![n][uf 1 1][e]

[msg MSG_019_0_0 [Mature-Looking Girl]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 31 0 0][uf 5 21 0 1003]Hey, is he gonna teach us, too? Is he your boyfriend, Coach?[n][uf 1 1][e]

[msg MSG_020_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 32 0 0]Never you mind about that.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 33 0 0]Now, everyone, line up! I said I wouldn't go easy on you, didn't I?[n][uf 1 1][e]

[msg MND_021_0_0]
[uf 0 5 65278][uf 2 1]Yuko began passionately[n]instructing each child.[n][uf 1 1][e]

[msg MSG_022_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 2 65535 65535 0 0][uf 3 1 1 0 0 34 0 0]Think positive! If you think you're gonna lose, you will! Don't be afraid of them just because they're sixth graders![n][uf 1 1][e]

[msg MSG_023_0_0 [Kids]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 35 0 0]That sounds hard... But okay![n][uf 1 1][e]

[msg MND_024_0_0]
[uf 0 5 65278][uf 2 1]I watched Yuko as she coached the kids.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Eventually, they all went home...[n][uf 1 1][e]

[msg MSG_025_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 36 0 0]Once they started calling me Coach, I couldn't resist.[n][uf 1 1][e]

[msg MSG_025_3_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 0 0][uf 3 1 1 0 0 37 0 0]Hey, um...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 0 0][uf 3 1 1 0 0 38 0 0]I was wondering. Would you maybe want to do this coaching thing together? I know I'm asking a lot, but...[n][uf 1 1][e]

[msg MSG_025_5_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 0 0][uf 3 1 1 0 0 39 0 0]I don't know much about racing. And plus, you're really athletic, too.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 0 0][uf 3 1 1 0 0 40 0 0]So if you'd coach them with me, I'd... really appreciate it.[n][uf 1 1][e]

[msg MSG_025_7_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 0 0][uf 3 1 1 0 0 41 0 0]I mean, why not, right? Please? Honestly, I don't think I can handle it on my own...[n][uf 1 1][e]

[sel SEL_026_0_0 top]
[uf 0 5 65278][uf 2 1]Sure thing.[e]
[uf 0 5 65278][uf 2 1]It's kind of a hassle.[e]

[msg MSG_027_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 42 0 0][uf 5 13 12 5 106]Oh, thank goodness...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 43 0 0]I'm sure those kids will be happy too! Thanks![n][uf 1 1][e]

[msg MSG_028_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 0 0][uf 3 1 1 0 0 44 0 0]Please! I'm begging you![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 0 0][uf 3 1 1 0 0 45 0 0]I mean, when they ask like that, don't you just want to help them? Come on, pretty please?[n][uf 1 1][e]

[msg MND_029_0_0]
[uf 0 5 65278][uf 2 1]It seems like Yuko is counting on me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like our relationship has grown...[n][uf 1 1][e]

[msg MSG_030_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 46 0 0]I know that I keep asking you for favors, but I'll make it up to you one day![n][uf 1 1][e]

[msg MND_031_0_0]
[uf 0 5 65278][uf 2 1]I left school with Yuko and[n]returned to the dorm...[n][uf 1 1][e]

