[msg MSG_010_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]Hã? Tem manchas brancas nessas folhas...[n][uf 1 1][e]

[msg MSG_010_5_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 65535 0 0][uf 3 1 1 0 0 2 0 0][uf 4 23 0 1 6 25 25]Acho que já vi isso em algum livro na biblioteca. É uma doença comum em verduras e flores.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 65535 0 0][uf 3 1 1 0 0 3 0 0][uf 4 21 6 11]O-O que a gente faz, [uf 4 1]-chan? E se as plantas morrerem...?[n][uf 1 1][e]

[sel SEL_011_0_0 top]
[uf 0 5 65278][uf 2 1]Se acalme.[e]
[uf 0 5 65278][uf 2 1]Qual é a solução do livro?[e]
[uf 0 5 65278][uf 2 1]Elas vão morrer.[e]

[msg MSG_012_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 65535 0 0][uf 3 1 1 0 0 4 0 0][uf 4 23 0 1 6 25 25]É-É, você tá certa. É por isso que li tantas coisas...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 5 0 0][uf 4 23 0 1 0 25 25]Pelo que estou vendo, ainda não parece muito sério. Se cuidarmos agora, elas devem ficar bem.[n][uf 1 1][e]

[msg MSG_013_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 65535 0 0][uf 3 1 1 0 0 6 0 0][uf 4 23 0 1 4 25 25]O quê... Ah, sim! Vai dar tudo certo se cuidarmos agora.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 7 0 0][uf 4 23 0 1 0 25 25]Pelo que estou vendo, ainda não parece muito sério. Hm, o que o livro dizia...[n][uf 1 1][e]

[msg MSG_014_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 65535 0 0][uf 3 1 1 0 0 8 0 0][uf 4 23 0 1 6 25 25]N-Não! Trabalhamos tanto...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 65535 0 0][uf 3 1 1 0 0 9 0 0]O livro disse que, se cuidarmos direito, elas vão ficar bem![n][uf 1 1][e]

[msg MSG_015_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 10 0 0][uf 4 23 0 1 0 25 25]Só precisamos cortar as partes brancas e... Isso mesmo, vinagre![n][uf 1 1][e]

[msg MSG_015_5_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 11 0 0]Diz para colocar vinagre diluído nas áreas afetadas. Vou pegar lá embaixo![n][uf 1 1][e]

[msg MND_016_0_0]
[uf 0 5 65278][uf 2 1]Cuidei das plantas do terraço com Fuuka...[n][uf 1 1][e]

[msg MSG_017_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 65535 0 0][uf 3 1 1 0 0 12 0 0][uf 4 23 0 1 6 25 25]Acho que é só isso que podemos fazer.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 13 0 0][uf 4 23 0 1 0 25 25]Já tiramos as folhas que caíram, e a circulação do ar está boa agora.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 14 0 0][uf 4 23 0 1 0 25 25][uf 4 22 0 6 49 25 21]Vai ficar tudo bem. Agora temos que confiar que elas vão se recuperar...[n][uf 1 1][e]

[msg MND_018_0_0]
[uf 0 5 65278][uf 2 1]Graças ao nosso cuidado,[n]parece que será uma grande safra.[n][uf 1 1][e]

[msg MSG_019_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 15 0 0][uf 5 13 3 1 6]Obrigada por hoje, [uf 4 1]-chan.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 16 0 0]Eu não teria conseguido salvar as plantas se você não estivesse aqui.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 17 0 0][uf 4 22 0 6 24 25 21]Ainda estou meio preocupada, mas... me ajude de novo numa próxima vez.[n][uf 1 1][e]

