[msg MSG_000_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 0 65535 65535 0 0][uf 3 1 3 0 65535 11899 0 0]So delicious! Ah, this must be true bliss![n][uf 1 1][e]

[msg MSG_001_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 2 65535 65535 0 0]Still, I cannot help but feel anxious...[n][uf 1 1][e]

[msg MSG_002_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 2 65535 65535 0 0][uf 3 1 3 0 65535 11867 0 0]Perhaps this is not the time to obsess over food.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 112 2 65535 65535 0 0]I must hurry and complete the kimono.[n][uf 1 1][e]

[sel SEL_003_0_0 top]
[uf 0 5 65278][uf 2 1]Go finish it now.[e]
[uf 0 5 65278][uf 2 1]Patience.[e]
[uf 0 5 65278][uf 2 1]Just relax.[e]

[msg MSG_004_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 2 65535 65535 0 0][uf 3 1 3 0 65535 11904 0 0]I do not have a sewing machine at my house! I must endure until we are able to return to school![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 112 2 65535 65535 0 0]A true samurai must persevere through whatever life may throw at them![n][uf 1 1][e]

[msg MND_005_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]Bebe looks anxious.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like we didn't get any closer today...[n][uf 1 1][e]

[msg MSG_006_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 0 65535 65535 0 0][uf 3 1 3 0 65535 11839 0 0][uf 5 13 15 15 112]You are right! A true samurai must persevere through whatever life may throw at them![n][uf 1 1][e]

[msg MND_007_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]Bebe seems motivated...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I learned a little more about him today...[n][uf 1 1][e]

[msg MSG_008_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 4 65535 65535 0 0][uf 3 1 3 0 65535 11801 0 0]"Relax," you say!?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 112 1 65535 65535 0 0][uf 4 23 0 112 1 25 25][uf 5 13 15 30 112]...Yes, of course, of course! Rushing will not help! I must keep my composure and relax![n][uf 1 1][e]

[msg MND_009_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]Bebe seems very motivated...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like we became a lot closer today.[n][uf 1 1][e]

[msg MSG_010_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 0 65535 65535 0 0][uf 3 1 3 0 65535 11900 0 0]That reminds me... There is a wise Japanese proverb that for this very occasion.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 112 0 65535 65535 0 0]You cannot fight on an empty stomach! So now I eat, and eat I shall![n][uf 1 1][e]

[msg MND_011_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]After enjoying a meal together,[n]I headed back to the dorm.[n][uf 1 1][e]

