[msg MSG_000_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 5 65535 0 0][uf 3 1 1 0 0 1 0 0]La série "Force de la volonté !"...[n][uf 1 1][e]

[msg MSG_000_5_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 5 65535 0 0][uf 3 1 1 0 0 2 0 0]J'avais prévu de regarder ça avec une copine de mon club. Je me disais que ça pourrait nous aider à nous motiver.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 5 65535 0 0][uf 3 1 1 0 0 3 0 0][uf 4 23 0 1 6 25 25][uf 4 21 2 11]Tu dois trouver ça ringard, cela dit... Et plus j'y pense, plus je me dis que ce n'est peut-être pas une si bonne idée, en fait...[n][uf 1 1][e]

[msg MSG_900_0_0 [Entraîneur du club sportif]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 4 0 0]Allez, montre-moi ce que t'as dans le ventre ! Tu dois te surpasser ! Tu m'as promis qu'on irait au tournoi national ![n][uf 1 1][e]

[msg MSG_901_0_0 [Entraîneur du club sportif]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 5 0 0]Et après, à nous la ligue professionnelle, le tournoi mondial... et les Jeux olympiques ! On se l'est promis ![n][uf 1 1][e]

[msg MSG_902_0_0 [Membre du club sportif]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 6 0 0]Et je ne l'oublierai jamais ! Je vais y arriver ! Je continuerai de courir jusqu'à atteindre le coucher de soleil ![n][uf 1 1][e]

[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]De la sueur s'écoule sur l'écran.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]J'ai appris qu'avec suffisamment de volonté, je peux tout surmonter...[n][uf 1 1][e]

[msg MSG_002_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 5 65535 0 0][uf 3 1 1 0 0 7 0 0]C'était impressionnant ! On est restées un bon moment, mais j'ai pas vu le temps passer ![n][uf 1 1][e]

[msg MSG_002_5_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 5 65535 0 0][uf 3 1 1 0 0 8 0 0]Comme quoi, dans la vie, il y a des fois où on ne peut compter que sur soi-même pour se motiver.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 5 65535 0 0][uf 3 1 1 0 0 9 0 0]Mais je suis encore jeune... Je n'ai pas encore fait quoi que ce soit d'extraordinaire.[n][uf 1 1][e]

[msg MSG_003_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 5 65535 0 0][uf 3 1 1 0 0 10 0 0]Oh, ouah ! Il commence à se faire tard. On a regardé combien de films ?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 5 65535 0 0][uf 3 1 1 0 0 11 0 0][uf 4 23 0 1 0 25 25]Celui sur le base-ball, sur le judo, sur les exercices militaires... Oh, j'ai failli oublier celui sur le lancer de poids ![n][uf 1 1][e]

[msg MSG_003_5_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 5 65535 0 0][uf 3 1 1 0 0 12 0 0]J'ai pas trop été emballée par le passage sur le lancer de poids, mais j'ai adoré les scènes d'après où on voyait le type courir.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 5 65535 0 0][uf 3 1 1 0 0 13 0 0][uf 4 23 0 1 1 25 25]J'ai pleuré comme une madeleine quand je l'ai vu faire le poirier en direction du soleil couchant ![n][uf 1 1][e]

[msg MSG_004_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 5 65535 0 0][uf 3 1 0 0 0 14 0 0]......[n][uf 1 1][e]

[msg MSG_004_5_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 5 65535 0 0][uf 3 1 1 0 0 15 0 0]Tu me trouves bizarre, hein ?[n][uf 1 1][e]

[msg MSG_004_7_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 5 65535 0 0][uf 3 1 1 0 0 16 0 0]Bref, je commence à avoir faim. On va manger un morceau quelque part avant de retourner au dortoir ?[n][uf 1 1][e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]J'ai décidé de retourner au dortoir avec Yukari.[n][uf 1 1][e]

