[msg MSG_000_0_0 [Presidente Tanaka]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0][uf 4 23 0 1 0 25 25]Antes de que proceda a iluminarte hoy...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 1 65535 65535 0 0][uf 3 1 1 0 0 2 0 0][uf 4 23 0 1 1 25 25]¿Y bien? ¿No me notas nada diferente?[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]¿Como qué?[e]
[uf 0 5 65278][uf 2 1]Más o menos...[e]

[msg MSG_002_0_0 [Presidente Tanaka]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 3 65535 65535 0 0][uf 3 1 1 0 0 3 0 0][uf 4 23 0 1 3 25 25]¿Estás ciega o qué?[n][uf 1 1][e]

[msg MSG_003_0_0 [Presidente Tanaka]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 1 65535 65535 0 0][uf 3 1 1 0 0 4 0 0][uf 4 23 0 1 1 25 25]Fui al balneario a hacerme una exfoliación facial. ¿No está mi piel completamente radiante?[n][uf 1 1][e]

[msg MSG_004_0_0 [Presidente Tanaka]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 1 65535 65535 0 0][uf 3 1 1 0 0 5 0 0][uf 4 23 0 1 1 25 25][uf 5 13 16 5 113]¡Anda! ¡¿Te has percatado?![n][uf 1 1][e]

[msg MSG_005_0_0 [Presidente Tanaka]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 1 65535 65535 0 0][uf 3 1 1 0 0 6 0 0][uf 4 23 0 1 1 25 25]Me han revitalizado el pelo. ¿No tiene un aspecto más sano ahora?[n][uf 1 1][e]

[msg MSG_006_0_0 [Presidente Tanaka]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 0 65535 65535 0 0][uf 3 1 1 0 0 7 0 0][uf 4 23 0 1 0 25 25]Es un rollo, sí, pero las apariencias son una parte importante de mi trabajo.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 0 65535 65535 0 0][uf 3 1 1 0 0 8 0 0][uf 4 23 0 1 0 25 25]Dicho esto, en casa soy el polo opuesto. Me visto con lo que pillo y solo me ducho cada tres días.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 3 65535 65535 0 0][uf 3 1 1 0 0 9 0 0][uf 4 23 0 1 3 25 25]Deja que piense en una analogía...[n][uf 1 1][e]

[msg MSG_007_0_0 [Presidente Tanaka]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 1 65535 65535 0 0][uf 3 1 1 0 0 10 0 0][uf 4 23 0 1 1 25 25]¡Verduras! ¡Perfecto![n][uf 1 1][e]

[msg MSG_007_3_0 [Presidente Tanaka]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 0 65535 65535 0 0][uf 3 1 1 0 0 11 0 0][uf 4 23 0 1 0 25 25]Imagínate un pepino de cultivo ecológico con un aspecto deforme.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 0 65535 65535 0 0][uf 3 1 1 0 0 12 0 0][uf 4 23 0 1 0 25 25]Compáralo con uno que está perfecto pero que creció a base de fertilizantes químicos y pesticidas.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 0 65535 65535 0 0][uf 3 1 1 0 0 13 0 0][uf 4 23 0 1 0 25 25]¿Cuál crees que repondría el supermercado?[n][uf 1 1][e]

[sel SEL_008_0_0 top]
[uf 0 5 65278][uf 2 1]El ecológico.[e]
[uf 0 5 65278][uf 2 1]El que tiene buena pinta.[e]

[msg MSG_009_0_0 [Presidente Tanaka]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 1 65535 65535 0 0][uf 3 1 1 0 0 14 0 0][uf 4 23 0 1 1 25 25][uf 5 13 16 15 113]¿No sería maravilloso?[n][uf 1 1][e]

[msg MSG_010_0_0 [Presidente Tanaka]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 0 65535 65535 0 0][uf 3 1 1 0 0 15 0 0][uf 4 23 0 1 0 25 25]En un mundo ideal, ofrecerían verduras salubres y deliciosas independientemente de su apariencia.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 1 65535 65535 0 0][uf 3 1 1 0 0 16 0 0][uf 4 23 0 1 1 25 25]Pero la realidad es que los supermercados colocan en las baldas los pepinos más bonitos que encuentran.[n][uf 1 1][e]

[msg MSG_011_0_0 [Presidente Tanaka]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 0 65535 65535 0 0][uf 3 1 1 0 0 17 0 0][uf 4 23 0 1 0 25 25]Esa es la simple y llana verdad.[n][uf 1 1][e]

[msg MSG_012_0_0 [Presidente Tanaka]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 0 65535 65535 0 0][uf 3 1 1 0 0 18 0 0][uf 4 23 0 1 0 25 25]Los pepinos con forma rara son difíciles de apilar, así que las tiendas los prefieren derechos.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 0 65535 65535 0 0][uf 3 1 1 0 0 19 0 0][uf 4 23 0 1 0 25 25]No se toman en consideración ni el sabor ni la salubridad. Venden pepinos que no se comerían ni las alimañas.[n][uf 1 1][e]

[msg MSG_013_0_0 [Presidente Tanaka]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 0 65535 65535 0 0][uf 3 1 1 0 0 20 0 0][uf 4 23 0 1 0 25 25]Entonces, ¿por qué los consumidores siguen comprando esos pepinos a pesar de conocer la verdad?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 0 65535 65535 0 0][uf 3 1 1 0 0 21 0 0][uf 4 23 0 1 0 25 25]Es simple. La gente confía en lo que ve. El mundo se rige más por las apariencias que por la realidad.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 2 65535 65535 0 0][uf 3 1 1 0 0 22 0 0][uf 4 23 0 1 2 25 25]Por eso, por mucho que odie gastar dinero, me compro corbatas caras para ganarme la confianza de la gente.[n][uf 1 1][e]

[msg MSG_013_5_0 [Presidente Tanaka]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 3 65535 65535 0 0][uf 3 1 1 0 0 23 0 0][uf 4 23 0 1 3 25 25]Un momento, ¿recuerdas lo que te conté antes?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 3 65535 65535 0 0][uf 3 1 1 0 0 24 0 0][uf 4 23 0 1 3 25 25]¿Lo de que visto con lo que pillo y no me ducho todos los días?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 2 65535 65535 0 0][uf 3 1 1 0 0 25 0 0][uf 4 23 0 1 2 25 25]¡Ni se te ocurra decírselo a nadie! ¡No puedo permitirme que la gente crea que soy corriente![n][uf 1 1][e]

[msg MSG_013_7_0 [Presidente Tanaka]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 3 65535 65535 0 0][uf 3 1 1 0 0 26 0 0][uf 4 23 0 1 3 25 25]Solo lo he admitido delante de ti. Nadie más sabe nada, ¿vale?[n][uf 1 1][e]

[msg MND_014_0_0 [Mensaje interno]]
[uf 0 5 65278][uf 2 1]El presidente Tanaka se está abriendo conmigo.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Ahora lo comprendo un poco mejor.[n][uf 1 1][e]

[msg MSG_015_0_0 [Presidente Tanaka]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 2 65535 65535 0 0][uf 3 1 1 0 0 27 0 0][uf 4 23 0 1 2 25 25]Recuerda: no se lo digas a nadie. Si incumples tu promesa...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 1 65535 65535 0 0][uf 3 1 1 0 0 28 0 0][uf 4 23 0 1 1 25 25]En fin, supongo que puedo confiar en ti. Vamos, vete.[n][uf 1 1][e]

[msg MND_016_0_0 [Mensaje interno]]
[uf 0 5 65278][uf 2 1]Tras despedirme del presidente Tanaka,[n]he decidido volver a la residencia.[n][uf 1 1][e]

