[msg MND_000_0_0]
[uf 0 5 65278][uf 2 1]We transferred to a tour bus[n]after arriving at Kyoto Station.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]The sun has already set...[n][uf 1 1][e]

[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]Higashiyama-Sanjo, Godaigo Inn...[n][uf 1 1][e]

[msg MSG_002_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 2 65535 0 0][uf 3 1 1 0 0 1 0 0]And here we are![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 2 65535 0 0][uf 3 1 1 0 0 2 0 0]Whoooa, nice place![n][uf 1 1][e]

[msg MSG_003_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 2 65535 0 0][uf 3 1 1 0 0 3 0 0]Yeah, this part of town is pretty fancy.[n][uf 1 1][e]

[msg MSG_004_0_0 [Ryoji Mochizuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 221 0 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]Hey, what's that umbrella for?[n][uf 1 1][e]

[sel SEL_005_0_0 top]
[uf 0 5 65278][uf 2 1]Fashion.[e]
[uf 0 5 65278][uf 2 1]In case the roof leaks.[e]
[uf 0 5 65278][uf 2 1]Wanna get under it?[e]

[msg MSG_006_0_0 [Ryoji Mochizuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 221 0 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]Ah, I see. So, that's the style here in Kyoto, huh?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 221 1 65535 65535 0 0][uf 3 1 1 0 0 6 0 0][uf 4 23 0 11 1 25 25]So, which way to the geishas? You think we can ask them to put on a show?[n][uf 1 1][e]

[msg MSG_007_0_0 [Ryoji Mochizuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 221 4 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]Huh? But this is the first floor! Guess these old Kyoto buildings have all sorts of surprises.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 221 1 65535 65535 0 0][uf 3 1 1 0 0 8 0 0][uf 4 23 0 11 1 25 25]So, which way to the geishas? Think we can ask them to put on a show?[n][uf 1 1][e]

[msg MSG_008_0_0 [Ryoji Mochizuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 221 1 65535 65535 0 0][uf 3 1 1 0 0 9 0 0]I get the feeling it's for good luck, you know?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 221 1 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]So, which way to the geishas? Think we can ask them to put on a show?[n][uf 1 1][e]

[msg MSG_009_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 2 65535 0 0][uf 3 1 1 0 0 11 0 0]Oh, that's right, I forgot about that! Hope it's not too pricey![n][uf 1 1][e]

[msg MSG_010_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 2 65535 0 0][uf 3 1 1 0 0 12 0 0]Keep dreamin', Junpei.[n][uf 1 1][e]

[msg MSG_011_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 13 0 0]The stone area outside is filled with water.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 14 0 0]Is this one of those open-air hot springs I've heard about?[n][uf 1 1][e]

[sel SEL_012_0_0 top]
[uf 0 5 65278][uf 2 1]Yep![e]
[uf 0 5 65278][uf 2 1]It's the courtyard, actually...[e]
[uf 0 5 65278][uf 2 1]Wanna go for a dip..?[e]

[msg MSG_013_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 2 65535 0 0][uf 3 1 1 0 0 15 0 0]Wha— N-No, Aigis! A bath wouldn't be so out in the open like this![n][uf 1 1][e]

[msg MSG_013_5_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 6 2 65535 0 0][uf 3 1 1 0 0 16 0 0]Come on, don't lie to her![n][uf 1 1][e]

[msg MSG_014_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 2 65535 0 0][uf 3 1 1 0 0 17 0 0]Right, this is the courtyard. Wanna go out for a walk later, Aigis?[n][uf 1 1][e]

[msg MSG_015_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 2 65535 0 0][uf 3 1 1 0 0 18 0 0]N-No! Aigis, you can't go in there![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 2 65535 0 0][uf 3 1 1 0 0 19 0 0]A bath wouldn't be so out in the open like this![n][uf 1 1][e]

[msg MSG_015_5_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 6 2 65535 0 0][uf 3 1 1 0 0 20 0 0]Come on, don't lie to her![n][uf 1 1][e]

[msg MSG_016_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 2 65535 0 0][uf 3 1 1 0 0 21 0 0]So, Ryoji. Where was your old school plannin' to go for their trip?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 2 65535 0 0][uf 3 1 1 0 0 22 0 0]Probably somewhere cool like another country, I bet. Kyoto's so typical, don't ya think?[n][uf 1 1][e]

[msg MSG_017_0_0 [Ryoji Mochizuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 221 0 65535 65535 0 0][uf 3 1 1 0 0 23 0 0]Hm? Me?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 221 0 65535 65535 0 0][uf 3 1 1 0 0 24 0 0]A trip... Hmm, did we even have one?[n][uf 1 1][e]

[msg MSG_018_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 2 65535 0 0][uf 3 1 1 0 0 25 0 0]How do you not know? That's an event most people tend to remember.[n][uf 1 1][e]

[msg MSG_019_0_0 [Ryoji Mochizuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 221 0 65535 65535 0 0][uf 3 1 1 0 0 26 0 0]It is?[n][uf 1 1][e]

[msg MSG_020_0_0 [Ms. Toriumi]]
[uf 0 5 65278][uf 2 1][uf 4 5 1581 0 65535 65535 0 0][uf 3 1 1 0 0 27 0 0][uf 5 21 0 1]All right, you can all chat later. You're blocking the hallway.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1581 0 65535 65535 0 0][uf 3 1 1 0 0 28 0 0][uf 5 21 0 1]Girls, your rooms are that way. Go on and get yourselves unpacked.[n][uf 1 1][e]

[msg MSG_021_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 2 65535 0 0][uf 3 1 1 0 0 29 0 0]You heard her.[n][uf 1 1][e]

[msg MSG_022_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 2 65535 0 0][uf 3 1 1 0 0 30 0 0]We'll see you later, then.[n][uf 1 1][e]

[msg MSG_023_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 2 65535 0 0][uf 3 1 1 0 0 31 0 0]Yeah, we'll see you later, [uf 4 2].[n][uf 1 1][e]

[msg MSG_024_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 2 65535 0 0][uf 3 1 1 0 0 32 0 0]Yes, I shall see you later, Yukari-san.[n][uf 1 1][e]

[msg MSG_025_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 2 65535 0 0][uf 3 1 1 0 0 33 0 0]Okay, okay, enough of this![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 2 65535 0 0][uf 3 1 1 0 0 34 0 0]Aigis, you're with us! Junpei, guys' room![n][uf 1 1][e]

[msg MSG_026_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 6 2 65535 0 0][uf 3 1 1 0 0 35 0 0]Maaan.[n][uf 1 1][e]

[msg MSG_027_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 36 0 0]Maaan.[n][uf 1 1][e]

