[msg MSG_000_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]Ah...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]Cette vieille dame, c'est la maîtresse de Minette...[n][uf 1 1][e]

[msg MSG_001_0_0 [Élève narquois]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 3 0 0][uf 5 21 0 2]Salut, mamie. Dis, j'ai un rencard demain.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 4 0 0][uf 5 21 0 2]Mais, euh, j'ai pas un rond, en fait.[n][uf 1 1][e]

[msg MSG_002_0_0 [Propriétaire de Minette]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 5 0 0][uf 5 21 0 3]Vraiment ? Oh, mon chéri...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 6 0 0][uf 5 21 0 3]Tu es un bon garçon, Kiyoshi... Tiens, voilà une avance sur ton argent de poche, mais ça reste entre nous.[n][uf 1 1][e]

[msg MSG_003_0_0 [Kiyoshi]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 7 0 0][uf 5 21 0 2]Arrête ! Je t'ai dit de pas m'appeler Kiyoshi ![n][uf 1 1][e]

[msg MSG_004_0_0 [Propriétaire de Minette]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 8 0 0][uf 5 21 0 3]Mais c'est un nom magnifique ! C'est moi qui l'ai choisi, tu sais.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 9 0 0][uf 5 21 0 3]C'était le nom d'un gentil médecin de mon village natal...[n][uf 1 1][e]

[msg MSG_005_0_0 [Kiyoshi]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 10 0 0][uf 5 21 0 2]J'ai déjà entendu ça mille fois.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 11 0 0][uf 5 21 0 2]Allez, passe le blé.[n][uf 1 1][e]

[msg MSG_006_0_0 [Propriétaire de Minette]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 12 0 0][uf 5 21 0 3]Oh, oui, bien sûr.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 13 0 0][uf 5 21 0 3]Ce n'est pas grand-chose, essaie de ne pas tout dépenser d'un coup ![n][uf 1 1][e]

[msg MSG_007_0_0 [Kiyoshi]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 14 0 0][uf 5 21 0 2]Yes, merci. À la prochaine.[n][uf 1 1][e]

[msg MSG_008_0_0 [Propriétaire de Minette]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 15 0 0][uf 5 21 0 3]Prends soin de toi, et reviens bientôt ![n][uf 1 1][e]

[msg MSG_009_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 16 0 0]J'ai quelque chose à demander à ce M. Kiyoshi...[n][uf 1 1][e]

