[msg MSG_000_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 6 65535 0 0][uf 3 1 1 0 0 1 0 0]Yes? Who is it?[n][uf 1 1][e]

[msg MSG_001_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0][uf 3 1 1 0 0 2 0 0]Um, it's me.[n][uf 1 1][e]

[msg MSG_002_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 6 65535 0 0][uf 3 1 1 0 0 3 0 0]Huh? Oh, come in.[n][uf 1 1][e]

[msg MSG_003_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 6 65535 0 0][uf 3 1 1 0 0 4 0 0]You don't stop by very often, Senpai.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 6 65535 0 0][uf 3 1 1 0 0 5 0 0]Is something wrong?[n][uf 1 1][e]

[msg MSG_004_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0][uf 3 1 1 0 0 6 0 0]No, not particularly. Is this a bad time?[n][uf 1 1][e]

[msg MSG_005_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 6 65535 0 0][uf 3 1 1 0 0 7 0 0]Awww, are you feeling lonely?[n][uf 1 1][e]

[msg MSG_006_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 6 65535 0 0][uf 3 1 1 0 0 8 0 0]Hey, are you teasing me?[n][uf 1 1][e]

[msg MSG_007_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 6 65535 0 0][uf 3 1 1 0 0 9 0 0]Nah, I'd never.[n][uf 1 1][e]

[msg MSG_008_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 6 65535 0 0][uf 3 1 1 0 0 10 0 0]Haha, sure.[n][uf 1 1][e]

[msg MSG_009_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 6 65535 0 0][uf 3 1 1 0 0 11 0 0]I wonder what this Nyx is like.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 6 65535 0 0][uf 3 1 1 0 0 12 0 0]Do you think it's inside Tartarus?[n][uf 1 1][e]

[msg MSG_010_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0][uf 3 1 1 0 0 13 0 0]I have no idea.[n][uf 1 1][e]

[msg MSG_011_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 6 65535 0 0][uf 3 1 1 0 0 14 0 0]Oh, by the way, I've made my decision.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 6 65535 0 0][uf 3 1 1 0 0 15 0 0]I want to fight to the end. It's better than doing nothing.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 6 65535 0 0][uf 3 1 1 0 0 16 0 0][uf 4 23 0 2 1 25 25]That's why you're here, right, Senpai?[n][uf 1 1][e]

[msg MSG_012_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 6 65535 0 0][uf 3 1 1 0 0 17 0 0]You got me.[n][uf 1 1][e]

[msg MSG_013_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 6 65535 0 0][uf 3 1 1 0 0 18 0 0]Yeah, you're pretty easy to read.[n][uf 1 1][e]

[msg MSG_014_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0][uf 3 1 1 0 0 19 0 0]I've made my decision as well.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0][uf 3 1 1 0 0 20 0 0]The Kirijo Group is slowly regaining its footing.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0][uf 3 1 1 0 0 21 0 0]After I graduate, the plan is for me to eventually take over as leader.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0][uf 3 1 1 0 0 22 0 0]Turning back was never really an option for me.[n][uf 1 1][e]

[msg MSG_015_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 6 65535 0 0][uf 3 1 1 0 0 23 0 0]But what if you die?[n][uf 1 1][e]

[msg MSG_016_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0][uf 3 1 1 0 0 24 0 0]If we can defeat Nyx and I die in the process, then the company will continue on without me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0][uf 3 1 1 0 0 25 0 0]And I'm confident they'd carry on my wishes.[n][uf 1 1][e]

[msg MSG_017_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 6 65535 0 0][uf 3 1 1 0 0 26 0 0]But from what we've heard, Nyx can't be defeated.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 6 65535 0 0][uf 3 1 1 0 0 27 0 0]Though I kinda wonder about that.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 6 65535 0 0][uf 3 1 1 0 0 28 0 0][uf 4 23 0 2 0 25 25]We've got someone on our team who seems pretty unkillable, too.[n][uf 1 1][e]

[msg MSG_018_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0][uf 3 1 1 0 0 29 0 0]That's true.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0][uf 3 1 1 0 0 30 0 0]And she's an exceptional Persona-user, even if Death was empowering her from within.[n][uf 1 1][e]

[msg MSG_019_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 6 65535 0 0][uf 3 1 1 0 0 31 0 0]She's an interesting girl, huh?[n][uf 1 1][e]

[msg MSG_020_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0][uf 3 1 1 0 0 32 0 0]She certainly is.[n][uf 1 1][e]

[msg MSG_021_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 6 65535 0 0][uf 3 1 1 0 0 33 0 0]You know, if things don't work out, I think I'll still be okay as long as I'm with everyone.[n][uf 1 1][e]

[msg MSG_022_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 6 65535 0 0][uf 3 1 1 0 0 34 0 0]Honestly, I don't think it matters if we live or die.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 6 65535 0 0][uf 3 1 1 0 0 35 0 0]All that really matters is that we're proud of how we lived.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 6 65535 0 0][uf 3 1 1 0 0 36 0 0]And I know I'd be proud if we decided to fight Nyx.[n][uf 1 1][e]

[msg MSG_023_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0][uf 3 1 1 0 0 37 0 0]Is this about honoring your father's legacy?[n][uf 1 1][e]

[msg MSG_024_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 6 65535 0 0][uf 3 1 1 0 0 38 0 0]Yeah, that's part of it. But mostly, it's about me and how I feel.[n][uf 1 1][e]

[msg MSG_025_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 6 65535 0 0][uf 3 1 1 0 0 39 0 0]I understand.[n][uf 1 1][e]

[msg MSG_026_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 6 65535 0 0][uf 3 1 1 0 0 40 0 0]Senpai, a while back, you asked me to face what comes next with you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 6 65535 0 0][uf 3 1 1 0 0 41 0 0]You didn't forget, did you?[n][uf 1 1][e]

[msg MSG_027_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 6 65535 0 0][uf 3 1 1 0 0 42 0 0]I could never forget.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0][uf 3 1 1 0 0 43 0 0][uf 4 23 0 5 0 25 25]We'll fight together, Yukari.[n][uf 1 1][e]

[msg MSG_028_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 6 65535 0 0][uf 3 1 1 0 0 44 0 0]...Good.[n][uf 1 1][e]

