[msg MSG_000_0_0 [Bunkichi]]
[uf 0 5 65278][uf 2 1][uf 4 5 103 4 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]Oh, [uf 4 2]-chan! Welcome![n][uf 1 1][e]

[msg MSG_001_0_0 [Mitsuko]]
[uf 0 5 65278][uf 2 1][uf 4 5 104 61 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]Ah...[n][uf 1 1][e]

[sel SEL_002_0_0 top]
[uf 0 5 65278][uf 2 1]What happened?[e]
[uf 0 5 65278][uf 2 1]Are you fighting again?[e]

[msg MSG_003_0_0 [Bunkichi]]
[uf 0 5 65278][uf 2 1][uf 4 5 103 1 65535 65535 0 0][uf 3 1 1 0 0 3 0 0][uf 5 13 6 5 103]Ah, don't you worry. She's— She's crying because she's happy.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 103 1 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]She's an emotional woman, bless her heart. She's been like this since the day we met.[n][uf 1 1][e]

[msg MSG_004_0_0 [Bunkichi]]
[uf 0 5 65278][uf 2 1][uf 4 5 103 0 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]Huh? You don't think I'm the one who made her cry, do you?[n][uf 1 1][e]

[msg MSG_005_0_0 [Bunkichi]]
[uf 0 5 65278][uf 2 1][uf 4 5 103 0 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]Maybe she's fed up with me because I always leave my socks inside out...[n][uf 1 1][e]

[msg MSG_005_5_0 [Bunkichi]]
[uf 0 5 65278][uf 2 1][uf 4 5 103 1 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]Wait, no, no, that's not it! She's crying tears of happiness![n][uf 1 1][e]

[msg MSG_006_0_0 [Bunkichi]]
[uf 0 5 65278][uf 2 1][uf 4 5 103 1 65535 65535 0 0][uf 3 1 1 0 0 8 0 0]You see, all the graduates from my son's class have come together.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 103 1 65535 65535 0 0][uf 3 1 1 0 0 9 0 0]They're collecting signatures to save the persimmon tree![n][uf 1 1][e]

[msg MSG_007_0_0 [Mitsuko]]
[uf 0 5 65278][uf 2 1][uf 4 5 104 1 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]They say the tree is a memorial to their former teacher... They don't want it to be cut down.[n][uf 1 1][e]

[sel SEL_008_0_0 top]
[uf 0 5 65278][uf 2 1]The tree? A memorial?[e]
[uf 0 5 65278][uf 2 1]That's great.[e]

[msg MSG_009_0_0 [Bunkichi]]
[uf 0 5 65278][uf 2 1][uf 4 5 103 3 65535 65535 0 0][uf 3 1 1 0 0 11 0 0]Hm... Guess it's over your head, being a transfer student and all...[n][uf 1 1][e]

[msg MSG_010_0_0 [Bunkichi]]
[uf 0 5 65278][uf 2 1][uf 4 5 103 0 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]Those three short years of high school made memories so precious they still cherish them decades later.[n][uf 1 1][e]

[msg MSG_011_0_0 [Bunkichi]]
[uf 0 5 65278][uf 2 1][uf 4 5 103 0 65535 65535 0 0][uf 3 1 1 0 0 13 0 0][uf 5 13 6 5 103]It was the same for our son's funeral... Many of them showed up for it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 103 1 65535 65535 0 0][uf 3 1 1 0 0 14 0 0][uf 4 23 0 1 1 25 25]It's been so many years since then, but they still remember him...[n][uf 1 1][e]

[msg MSG_012_0_0 [Mitsuko]]
[uf 0 5 65278][uf 2 1][uf 4 5 104 61 65535 65535 0 0][uf 3 1 1 0 0 15 0 0]They've given their precious time... for our son. I don't know what to say... I'm so grateful...[n][uf 1 1][e]

[msg MSG_013_0_0 [Bunkichi]]
[uf 0 5 65278][uf 2 1][uf 4 5 103 0 65535 65535 0 0][uf 3 1 1 0 0 16 0 0]You must be the one who called on them for this, right, [uf 4 2]-chan?[n][uf 1 1][e]

[sel SEL_014_0_0 top]
[uf 0 5 65278][uf 2 1]No.[e]
[uf 0 5 65278][uf 2 1]That's right.[e]
[uf 0 5 65278][uf 2 1]What are you talking about?[e]

[msg MSG_015_0_0 [Bunkichi]]
[uf 0 5 65278][uf 2 1][uf 4 5 103 1 65535 65535 0 0][uf 3 1 1 0 0 17 0 0][uf 5 13 6 5 103]Oh, don't pretend, it's just us. You don't have to be so modest, [uf 4 2]-chan...[n][uf 1 1][e]

[msg MSG_016_0_0 [Bunkichi]]
[uf 0 5 65278][uf 2 1][uf 4 5 103 1 65535 65535 0 0][uf 3 1 1 0 0 18 0 0][uf 5 13 6 5 103]I knew it! I knew it from the very beginning![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 103 1 65535 65535 0 0][uf 3 1 1 0 0 19 0 0]From the first time I saw you, I knew you were different from the other kids around here.[n][uf 1 1][e]

[msg MSG_017_0_0 [Bunkichi]]
[uf 0 5 65278][uf 2 1][uf 4 5 103 1 65535 65535 0 0][uf 3 1 1 0 0 20 0 0]You're a kunoichi, [uf 4 2]-chan! A modern-day kunoichi...[n][uf 1 1][e]

[msg MND_018_0_0]
[uf 0 5 65278][uf 2 1]The two seem to think I'm the[n]one responsible for the petition...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]They're showing considerable gratitude.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like we're growing closer...[n][uf 1 1][e]

[msg MSG_019_0_0 [Bunkichi]]
[uf 0 5 65278][uf 2 1][uf 4 5 103 1 65535 65535 0 0][uf 3 1 1 0 0 21 0 0]And before you know it, you'll graduate and step boldly into adulthood. Don't forget about us, y'hear?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 103 1 65535 65535 0 0][uf 3 1 1 0 0 22 0 0]Someday, I'd love to grab a drink, you and me...[n][uf 1 1][e]

[msg MSG_019_5_0 [Bunkichi]]
[uf 0 5 65278][uf 2 1][uf 4 5 103 1 65535 65535 0 0][uf 3 1 1 0 0 23 0 0]But for now, you'll have to make do with this.[n][uf 1 1][e]

[msg MND_020_0_0]
[uf 0 5 65278][uf 2 1]DEV: *Unused message label. [n][uf 1 5 0]*If this appears, it is a bug.[n][uf 1 1][e]

[msg MSG_021_0_0 [Bunkichi]]
[uf 0 5 65278][uf 2 1][uf 4 5 103 1 65535 65535 0 0][uf 3 1 1 0 0 24 0 0]See you again soon, [uf 4 2]-chan.[n][uf 1 1][e]

[msg MND_022_0_0]
[uf 0 5 65278][uf 2 1]I parted with the elderly couple[n]and went back to the dorm.[n][uf 1 1][e]

