[msg MSG_000_0_0 [Menina meiga]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 1 0 0][uf 5 21 0 1001]Esse campo é tãããão grande![n][uf 1 1][e]

[msg MSG_001_0_0 [Garoto determinado]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 2 0 0][uf 5 21 0 1002]Nossa, o colégio é demais![n][uf 1 1][e]

[msg MSG_002_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]Disseram que a gente pode usar o pátio do colégio por um tempo.[n][uf 1 1][e]

[msg MSG_003_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]Normalmente, vocês não poderiam estar aqui, entenderam?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]Então não mexam no que não devem e, se alguma coisa acontecer, avisem a gente na mesma hora.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]Prometem?[n][uf 1 1][e]

[msg MSG_004_0_0 [Garoto determinado]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 7 0 0][uf 5 21 0 1002]A gente promete![n][uf 1 1][e]

[msg MSG_005_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 8 0 0]Ótimo. Então podem treinar até o ponteiro grande daquele relógio chegar em doze. E não me inventem de entrar na escola![n][uf 1 1][e]

[msg MSG_006_0_0 [Garoto determinado]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 9 0 0][uf 5 21 0 1002]Tá bom! Vamos lá![n][uf 1 1][e]

[msg MSG_007_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]Espera, vem aqui um segundo.[n][uf 1 1][e]

[msg MSG_007_5_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 11 0 0]Você tem que flexionar mais os braços.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]E não precisa erguer tanto a perna, senão vai distender um músculo.[n][uf 1 1][e]

[msg MSG_008_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]Vai, pode tentar! É só acreditar em você mesmo![n][uf 1 1][e]

[msg MSG_009_0_0 [Garoto determinado]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 14 0 0][uf 5 21 0 1002]Uhuuuu! Saca só![n][uf 1 1][e]

[msg MSG_010_0_0 [Menina meiga]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 15 0 0][uf 5 21 0 1001]Uau! Ken-chan, como você é rápido![n][uf 1 1][e]

[msg MSG_010_5_0 [Menina meiga]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 16 0 0][uf 5 21 0 1001]Ei, mana! Você devia ser a nossa treinadora![n][uf 1 1][e]

[msg MSG_011_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 0 0][uf 3 1 1 0 0 17 0 0]Ah, eu não dou conta quando as crianças me olham assim...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 0 0][uf 3 1 1 0 0 18 0 0]Mas eu nunca tentei ser treinadora antes...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 0 0][uf 3 1 1 0 0 19 0 0][uf 4 1]-chan, o que você acha que eu devo fazer?[n][uf 1 1][e]

[sel SEL_012_0_0 top]
[uf 0 5 65278][uf 2 1]Por que você não tenta?[e]
[uf 0 5 65278][uf 2 1]Essa escolha é sua.[e]

[msg MSG_013_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 20 0 0]Você acha mesmo que eu deveria?[n][uf 1 1][e]

[msg MSG_014_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 0 0][uf 3 1 1 0 0 21 0 0]Pois é, eu sei...[n][uf 1 1][e]

[msg MSG_015_0_0 [Garoto determinado]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 22 0 0][uf 5 21 0 1002]Poxa, por favor![n][uf 1 1][e]

[msg MSG_016_0_0 [Crianças]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 23 0 0]Por favoooor![n][uf 1 1][e]

[msg MSG_017_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 0 0][uf 3 1 1 0 0 24 0 0]Hmm...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 0 0][uf 3 1 1 0 0 25 0 0]Bom, não é uma decisão fácil...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 0 0][uf 3 1 0 0 0 26 0 0]...[n][uf 1 1][e]

[msg MSG_017_5_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 27 0 0]Tá bom, eu topo ser a sua treinadora![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 2 65535 65535 0 0][uf 3 1 1 0 0 28 0 0][uf 4 23 0 1 2 25 25]Mas não vou pegar leve com vocês! E não quero saber de ninguém desistindo no meio![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 2 65535 65535 0 0][uf 3 1 1 0 0 29 0 0]Entendido?[n][uf 1 1][e]

[msg MSG_018_0_0 [Crianças]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 30 0 0]Entendido, Treinadora Yuko![n][uf 1 1][e]

[msg MSG_019_0_0 [Menina madura]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 31 0 0][uf 5 21 0 1003]Ei, ela também vai ensinar a gente? É a sua namorada, treinadora?[n][uf 1 1][e]

[msg MSG_020_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 32 0 0]Isso não é da sua conta.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 33 0 0]Agora, todo mundo fazendo fila! Eu disse que não ia pegar leve, não disse?[n][uf 1 1][e]

[msg MND_021_0_0]
[uf 0 5 65278][uf 2 1]Yuko começou a instruir cada criança fervorosamente.[n][uf 1 1][e]

[msg MSG_022_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 2 65535 65535 0 0][uf 3 1 1 0 0 34 0 0]Pensamento positivo! Se ficarem pensando que vão perder, vão perder! Não precisa ter medo deles só porque são do sétimo ano![n][uf 1 1][e]

[msg MSG_023_0_0 [Crianças]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 35 0 0]Deve ser complicado... Mas tá![n][uf 1 1][e]

[msg MND_024_0_0]
[uf 0 5 65278][uf 2 1]Eu vi Yuko treinar as crianças.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Com o tempo, todas foram para casa...[n][uf 1 1][e]

[msg MSG_025_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 36 0 0]Quando começaram a me chamar de treinadora, eu não resisti.[n][uf 1 1][e]

[msg MSG_025_3_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 0 0][uf 3 1 1 0 0 37 0 0]Ei, hum...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 0 0][uf 3 1 1 0 0 38 0 0]Tava pensando... Será que você não quer treinar as crianças comigo? Sei que é pedir muito, mas...[n][uf 1 1][e]

[msg MSG_025_5_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 0 0][uf 3 1 1 0 0 39 0 0]Não entendo muito de corrida. Sem contar que você é toda atlética também.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 0 0][uf 3 1 1 0 0 40 0 0]Então, se você topar treinar as crianças comigo, eu... ia gostar bastante.[n][uf 1 1][e]

[msg MSG_025_7_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 0 0][uf 3 1 1 0 0 41 0 0]Tipo, por que não, né? Por favor? Sinceramente, não sei se dou conta sozinha...[n][uf 1 1][e]

[sel SEL_026_0_0 top]
[uf 0 5 65278][uf 2 1]Com certeza.[e]
[uf 0 5 65278][uf 2 1]Vai ser uma dor de cabeça.[e]

[msg MSG_027_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 42 0 0][uf 5 13 12 5 106]Ufa, ainda bem...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 43 0 0]Aposto que as crianças vão adorar também! Valeu![n][uf 1 1][e]

[msg MSG_028_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 0 0][uf 3 1 1 0 0 44 0 0]Por favor! Eu imploro![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 0 0][uf 3 1 1 0 0 45 0 0]Quer dizer... Quando elas pedem daquele jeito, não dá pra não ajudar, né? Poxa, por favorzinho?[n][uf 1 1][e]

[msg MND_029_0_0]
[uf 0 5 65278][uf 2 1]Parece que Yuko está contando comigo.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Sinto que minha relação com ela está amadurecendo...[n][uf 1 1][e]

[msg MSG_030_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 46 0 0]Eu sei que eu só fico te pedindo favores, mas prometo que um dia eu vou retribuir![n][uf 1 1][e]

[msg MND_031_0_0]
[uf 0 5 65278][uf 2 1]Saí da escola com Yuko[n]e voltei ao dormitório.[n][uf 1 1][e]

