[msg MSG_000_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 1 0 0]Vaya...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 2 0 0]Si sobra, lo metemos en la nevera.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 3 0 0]Pero hemos cocinado para dos, así que no creo que queden sobras.[n][uf 1 1][e]

[msg MSG_001_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 4 0 0]Ah, casi se me olvida, estoy preparando katsudon.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 5 0 0]Si está malo como si está bueno, tienes que comértelo.[n][uf 1 1][e]

[sel SEL_002_0_0 top]
[uf 0 5 65278][uf 2 1]¿Lo estás haciendo tú?[e]
[uf 0 5 65278][uf 2 1]Solo si está bueno.[e]
[uf 0 5 65278][uf 2 1]Prefiero el ramen.[e]

[msg MSG_003_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 6 0 0]Te dije que te lo agradecería, ¿no?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 7 0 0]Si no quieres, aparto la carne. Pero menuda jodienda, así que come y calla.[n][uf 1 1][e]

[msg MSG_004_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 8 0 0]Los tienes bien puestos para decir eso.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 9 0 0]Es para darte las gracias, así que te prometo que estará rico.[n][uf 1 1][e]

[msg MSG_005_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 3 159 65535 0 0][uf 3 1 1 0 0 10 0 0][uf 4 23 0 10 3 25 25]Te dije que te lo agradecería, pero me faltan medios.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 11 0 0][uf 4 23 0 10 0 25 25]Me apetece arroz, así que hoy comemos katsudon, ¿te parece?[n][uf 1 1][e]

[msg MSG_006_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 12 0 0]Pues venga, manos a la obra.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 13 0 0]Como el arroz ya está listo, basta con servirse un poco en un bol cuando acabe.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 14 0 0]Por cierto, a mí échame bastante.[n][uf 1 1][e]

[msg MND_007_0_0]
[uf 0 5 65278][uf 2 1]He visto a Aragaki cocinar. Tiene la destreza propia de un cocinero profesional.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Ya está listo el katsudon.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Cerdo empanado y crujiente, cubierto con[n]un huevo medio hecho. Me podría[n]alimentar a base de esto.[n][uf 1 1][e]

[msg MSG_008_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 1 159 65535 0 0][uf 3 1 1 0 0 15 0 0][uf 4 23 0 10 1 25 25]Se ve que te gusta, ¿eh?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 0 0 0 16 0 0][uf 4 23 0 10 0 25 25]...[n][uf 1 1][e]

[msg MSG_009_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 18 0 0]Cualquiera puede hacer esto con práctica.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 19 0 0]Hoy ha sido arroz con cuatro ingredientes más, pero se puede acompañar de otras cosas.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 20 0 0]Cocínate un poco cuando tengas un rato.[n][uf 1 1][e]

[msg MSG_010_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 21 0 0]Bueno, yo ya he cumplido con mi parte, así que friegas tú.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 22 0 0]Hasta luego.[n][uf 1 1][e]

[msg MSG_011_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 23 0 0]Hoy también comemos katsudon.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 24 0 0]No me mires así, es que el cerdo estaba barato.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 25 0 0]En parte, empezar con los fritos tiene sus complicaciones, pero al final los conocimientos básicos son los que son.[n][uf 1 1][e]

[msg MSG_012_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 26 0 0]Estás como una cabra, tía. Mira que pedirme a mí que te enseñe a cocinar...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 27 0 0]¿Por qué quieres aprender?[n][uf 1 1][e]

[sel SEL_013_0_0 top]
[uf 0 5 65278][uf 2 1]Me importa mi salud.[e]
[uf 0 5 65278][uf 2 1]Me dio por ahí.[e]
[uf 0 5 65278][uf 2 1]Quiero ser popular.[e]

[msg MSG_014_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 28 0 0]Sí, ¿eh?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 29 0 0]Una razón tan buena como cualquier otra.[n][uf 1 1][e]

[msg MSG_015_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 3 159 65535 0 0][uf 3 1 1 0 0 30 0 0][uf 4 23 0 10 4 25 25]Tú no te paras a pensar siquiera, ¿eh?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 31 0 0][uf 4 23 0 10 0 25 25]Bueno, el saber no hace mal.[n][uf 1 1][e]

[msg MSG_016_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 32 0 0]Cada uno tiene sus motivos.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 33 0 0]El saber no ocupa lugar, pero aplícate bien si quieres tener éxito.[n][uf 1 1][e]

[msg MSG_017_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 34 0 0]A mí también me enseñaron a cocinar.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 35 0 0]Por eso, cuando alguien quiere aprender, me siento identificado.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 36 0 0]Venga, se acabó la turra. Al lío.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 37 0 0]Hoy cocinas tú. Primero, prepara la carne.[n][uf 1 1][e]

[msg MSG_018_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 38 0 0]Cuando vayas a freír algo, mete un palillo en el aceite y mira si salen burbujas pequeñas.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 39 0 0]Oye, está caliente de más. La carne no va a estar buena si se queda como una zapatilla.[n][uf 1 1][e]

[msg MSG_019_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 1 159 65535 0 0][uf 3 1 1 0 0 40 0 0][uf 4 23 0 10 1 25 25]Para ser la primera vez, te ha salido guay.[n][uf 1 1][e]

[msg MSG_019_5_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 41 0 0][uf 4 23 0 10 0 25 25]Aunque tienes que mejorar, sobre todo al manipular el cuchillo y usar la freidora.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 42 0 0]Pero, si te esmeras, con practicar es suficiente.[n][uf 1 1][e]

[msg MSG_020_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 43 0 0]Venga, vamos a limpiar.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 159 65535 0 0][uf 3 1 1 0 0 44 0 0]Uno no termina de cocinar hasta que limpia la cocina, así que espabila.[n][uf 1 1][e]

