[msg MND_000_0_0]
[uf 0 5 65278][uf 2 1]No sign of Miyamoto.[n][uf 1 1][e]

[msg MSG_001_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 101 65535 0 0][uf 3 1 1 0 0 1 0 0]Hey, [uf 4 1]-chan, I just got a text from Kaz.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 101 65535 0 0][uf 3 1 1 0 0 2 0 0]It's for you, but he wanted you to know ASAP, so he texted me, too.[n][uf 1 1][e]

[msg MSG_001_5_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 2 101 65535 0 0][uf 3 1 1 0 0 3 0 0]It says, "Come to Iwatodai Station." What is that guy thinking? He skipped practice today, too![n][uf 1 1][e]

[msg MND_002_0_0]
[uf 0 5 65278][uf 2 1]After practice, I made my[n]way to Iwatodai Station.[n][uf 1 1][e]

