[msg MSG_009_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 1 0 0 1 0 0]Man, our hero took an underdog baseball team that didn't even have enough players all the way to nationals.[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0][vp 1 0 0 2 0 0]No matter how tough the rival or desperate the situation, the hero always ends up findin' a way.[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0][vp 1 0 0 3 0 0]Hey, we're technically a team too, aren't we? Means we need a hotshot of our own, right?[n][w][e]

[sel SEL_010_0_0 top]
[f 2 1]Can it be me?[e]
[f 2 1]We’re all hotshots![e]
[f 2 1]You read too much manga...[e]

[msg MSG_011_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 1 0 0 4 0 0]Haha, don't sweat it. We've already got ourselves a major hotshot—me![n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0][vp 1 0 0 5 0 0]Everyone else has got their own strengths, kinda like the characters in a manga.[n][w][e]

[msg MSG_012_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 1 0 0 6 0 0]Haha, sounds an awful lot like hero talk to me. Share some of that glory, why don't ya?[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0][vp 1 0 0 7 0 0][f 4 23 0 3 0 25 25]Hotshot or not, the others've got so much personality, kinda like the characters in a manga.[n][w][e]

[msg MSG_013_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 1 0 0 8 0 0]Oh yeah? That not realistic enough for ya?[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0][vp 1 0 0 9 0 0]But don't ya think Sanada-san and Kirijo-senpai have way more personality than any manga character?[n][w][e]

[msg MSG_014_0_0 [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0][vp 1 0 0 10 0 0][f 4 23 0 3 3 25 25]Either way, kinda blows that real life can't be like how it is in a manga.[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0][vp 1 0 0 11 0 0][f 4 23 0 3 0 25 25]Anywho, on to the next page.[n][w][e]

[msg MSG_015_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 1 0 0 12 0 0]Oh yeah, that's right. Just before the big game, the hero collapses![n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0][vp 1 0 0 13 0 0]All after gettin' everyone together, trainin' like crazy, becomin' a hotshot hitter, and carryin' the whole team all by himself.[n][w][e]

[msg MND_016_0_0]
[f 2 1]The young hero's dedication[n]filled me with [f 4 30 2 1 1 0]![n][w][e]

[msg MSG_017_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 1 0 0 14 0 0]Dyin' to know what happens next, huh? Then I'll borrow the rest of the volumes from my buddy, pronto![n][w][e]

