[msg MSG_000_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 2 65535 0 0][uf 3 1 1 0 0 1 0 0]Oh, welcome back, [uf 4 1]-chan.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 2 65535 0 0][uf 3 1 1 0 0 2 0 0]You're late. Ryoji-kun was just leaving.[n][uf 1 1][e]

[msg MSG_001_0_0 [Ryoji Mochizuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 221 1 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]Oh, hey there. Chilly out, huh? Hope you don't go catching a cold.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 221 0 65535 65535 0 0][uf 3 1 1 0 0 4 0 0][uf 4 23 0 221 0 25 25]You know, I stop by here pretty often. Weird we never see each other.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 221 0 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]Well, I'm outta here. See you later.[n][uf 1 1][e]

[msg MSG_002_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 2 65535 0 0][uf 3 1 1 0 0 6 0 0]Later, Ryoji![n][uf 1 1][e]

[msg MSG_003_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 7 0 0]Was that Ryoji-san?[n][uf 1 1][e]

[msg MSG_004_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 2 65535 0 0][uf 3 1 1 0 0 8 0 0]Yeah, he said he was going home.[n][uf 1 1][e]

[msg MSG_005_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 2 65535 0 0][uf 3 1 1 0 0 9 0 0]Why was he here?[n][uf 1 1][e]

[msg MSG_006_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 2 65535 0 0][uf 3 1 1 0 0 10 0 0]To see Junpei. They've been hanging out a lot ever since the school trip.[n][uf 1 1][e]

[msg MSG_007_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 2 65535 0 0][uf 3 1 1 0 0 11 0 0]...But the rules state that visitors aren't allowed here.[n][uf 1 1][e]

[msg MSG_008_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 2 65535 0 0][uf 3 1 1 0 0 12 0 0]Yeah, but Kirijo-senpai said it's cool as long as no one stays late.[n][uf 1 1][e]

[msg MSG_009_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 2 65535 0 0][uf 3 1 1 0 0 13 0 0]I don't think we have anything to worry about.[n][uf 1 1][e]

[msg MSG_010_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 2 2 65535 0 0][uf 3 1 1 0 0 14 0 0]He... is dangerous.[n][uf 1 1][e]

[msg MSG_011_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 2 65535 0 0][uf 3 1 1 0 0 15 0 0]Dangerous? Ryoji-kun?[n][uf 1 1][e]

[msg MSG_012_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 2 65535 0 0][uf 3 1 1 0 0 16 0 0]Come to think of it, he did hit on Mitsuru-senpai the first time he met her.[n][uf 1 1][e]

[msg MSG_013_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 2 65535 0 0][uf 3 1 1 0 0 17 0 0]But having him around has really helped cheer you up, Junpei-kun.[n][uf 1 1][e]

[msg MSG_014_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 2 65535 0 0][uf 3 1 1 0 0 18 0 0]Well, no point in dwelling on the past, right? Won't change a damn thing.[n][uf 1 1][e]

[msg MSG_015_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 19 0 0]That's true...[n][uf 1 1][e]

[msg MSG_016_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 2 65535 0 0][uf 3 1 1 0 0 20 0 0]Hm? What's up, Ai-chan?[n][uf 1 1][e]

[msg MSG_017_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 21 0 0]I'm fine. It's just... I envy you, Junpei.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 2 65535 0 0][uf 3 1 1 0 0 22 0 0][uf 4 23 0 7 3 25 25]I'm a machine, so I don't understand what it feels like to "live."[n][uf 1 1][e]

[msg MSG_018_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 2 65535 0 0][uf 3 1 1 0 0 23 0 0]Really? But you don't seem that different.[n][uf 1 1][e]

[msg MSG_019_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 24 0 0]In my case, it's more accurate to say that I'm "operational" as opposed to alive.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 25 0 0]There are times when I malfunction, but I can always be repaired.[n][uf 1 1][e]

[msg MSG_020_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 2 65535 0 0][uf 3 1 1 0 0 26 0 0]Well, if we were all like you, then we'd never have to worry about dying.[n][uf 1 1][e]

[msg MSG_021_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 2 65535 0 0][uf 3 1 1 0 0 27 0 0]Ah, crap! Uh, I don't have time to talk right now. I've got a mountain of homework...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 2 65535 0 0][uf 3 1 1 0 0 28 0 0][uf 4 23 0 3 3 25 25]Serves me right for slackin'. Welp, no use whining.[n][uf 1 1][e]

[msg MSG_022_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 2 65535 0 0][uf 3 1 1 0 0 29 0 0]Junpei studying on purpose? I guess hell finally froze over. Well, better call it a night, then.[n][uf 1 1][e]

[msg MSG_023_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 30 0 0]The gift of life is not something I should possess.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 31 0 0]A weapon is much more difficult to operate when it's alive.[n][uf 1 1][e]

[msg MSG_024_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 2 65535 0 0][uf 3 1 1 0 0 32 0 0]That said, I believe I understand the concept of loss.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 2 65535 0 0][uf 3 1 1 0 0 33 0 0][uf 4 2]-san...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 2 65535 0 0][uf 3 1 1 0 0 34 0 0]The thought of something happening to you... It makes me...[n][uf 1 1][e]

[sel SEL_025_0_0 top]
[uf 0 5 65278][uf 2 1]Don't worry about me.[e]
[uf 0 5 65278][uf 2 1]Stop overanalyzing.[e]

[msg MSG_026_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 2 65535 0 0][uf 3 1 1 0 0 35 0 0]Understood.[n][uf 1 1][e]

[msg MSG_027_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 2 65535 0 0][uf 3 1 1 0 0 36 0 0]Forgive me. I'm just... concerned.[n][uf 1 1][e]

[msg MSG_028_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 37 0 0]You are very special to me...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 38 0 0]I can't explain why, but I never want to leave your side.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 39 0 0]I want to protect you at all costs, to be there for you always.[n][uf 1 1][e]

[msg MSG_029_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 40 0 0]Ah, I apologize for keeping you. You must be tired.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 41 0 0]So much has happened in so little time... I'll return to my room as well.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 42 0 0]Good night.[n][uf 1 1][e]

[msg MSG_030_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 2 2 65535 0 0][uf 3 1 1 0 0 43 0 0]Ryoji Mochizuki... He is dangerous.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 2 65535 0 0][uf 3 1 1 0 0 44 0 0][uf 4 23 0 7 3 25 25]What is this unsettling feeling?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 2 65535 0 0][uf 3 1 1 0 0 45 0 0]I am a machine.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 2 65535 0 0][uf 3 1 1 0 0 46 0 0]I can't die, so no one will have to grieve for me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 2 2 65535 0 0][uf 3 1 1 0 0 47 0 0][uf 4 23 0 7 2 25 25]I... have to do something.[n][uf 1 1][e]

[msg MSG_031_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 2 2 65535 0 0][uf 3 1 1 0 0 48 0 0]I don't want to see them suffer anymore.[n][uf 1 1][e]

