[msg MSG_000_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]Y así considero que es como deberían llevarse los uniformes. Por favor, tenedlo en cuenta.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]No estoy diciendo que haya que seguirlo a pies juntillas, ojo, eso es elección de cada uno.[n][uf 1 1][e]

[msg MSG_001_0_0 [Secretario]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 3 0 0][uf 5 21 0 1]La leche, ¿eso acaba de salir de su boca?[n][uf 1 1][e]

[msg MSG_002_0_0 [Vicepresidenta]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 4 0 0][uf 5 21 0 2]Es la primera vez que veo que tiene en cuenta las opiniones de los demás.[n][uf 1 1][e]

[msg MSG_003_0_0 [Enlace del consejo]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 5 0 0][uf 5 21 0 3]Bueno, al menos lo intenta.[n][uf 1 1][e]

[msg MSG_004_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]Gracias, [uf 4 1]. No podría haberlo hecho sin ti.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]¿Qué tal lo he hecho? ¿Qué opinan los demás?[n][uf 1 1][e]

[sel SEL_005_0_0 top]
[uf 0 5 65278][uf 2 1]Nada mal.[e]
[uf 0 5 65278][uf 2 1]Has estado increíble.[e]

[msg MSG_006_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 1 65535 65535 0 0][uf 3 1 1 0 0 8 0 0][uf 5 13 5 15 102]Pues yo estoy orgulloso de haber hecho el esfuerzo.[n][uf 1 1][e]

[msg MSG_007_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 0 9 0 0][uf 5 13 5 5 102]Gracias, me he quitado un peso enorme de encima.[n][uf 1 1][e]

[msg MSG_008_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]Creo que me he retratado como una persona egoísta y arrogante, así que debo volver a ganarme su confianza.[n][uf 1 1][e]

[msg MSG_009_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 0 11 0 0]Mira.[n][uf 1 1][e]

[msg MSG_010_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]Un chico ha confesado que la colilla del baño era suya.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]Después de mucho persuadirlo, me ha prometido que no volverá a fumar.[n][uf 1 1][e]

[msg MSG_010_5_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]Este mechero es la prueba.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 0 15 0 0]Me he ganado su confianza al mostrarle compasión, tal y como me enseñaste.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 0 16 0 0]Por eso deberías quedártelo tú.[n][uf 1 1][e]

[sel SEL_011_0_0 top]
[uf 0 5 65278][uf 2 1]Lo cuidaré.[e]
[uf 0 5 65278][uf 2 1]Vale, pues me lo quedo.[e]

[msg MSG_012_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 1 65535 65535 0 0][uf 3 1 1 0 0 17 0 0][uf 5 13 5 15 102]Gracias.[n][uf 1 1][e]

[msg MSG_013_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 1 65535 65535 0 0][uf 3 1 1 0 0 18 0 0][uf 5 13 5 15 102]Sí, por favor.[n][uf 1 1][e]

[msg MND_014_0_0]
[uf 0 5 65278][uf 2 1]DEV: *Unused message label. [n][uf 1 5 0]*If this appears, it is a bug.[n][uf 1 1][e]

[msg MSG_015_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 0 19 0 0]Me he pasado la vida menospreciando a los demás. Una fanfarronería infundada.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 0 20 0 0]Pero tú me has dado una lección muy importante que siempre recordaré.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 0 21 0 0]Aunque no creo que llegue a estar nunca a tu altura.[n][uf 1 1][e]

[msg MND_016_0_0]
[uf 0 5 65278][uf 2 1]Hidetoshi parece estar avergonzado.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Siento un vínculo irrompible con Hidetoshi.[n][uf 1 1][e]

[msg SYS_017_0_0]
[uf 0 5 65278][uf 2 1]El vínculo social del Emperador ha alcanzado su nivel máximo.[n]¡Ahora puedes fusionar a [uf 0 1 35]Odín[uf 0 1 27], dios de la tormenta![n][uf 1 1][e]

[msg MSG_018_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 0 22 0 0]¿Recuerdas la historia que te conté del guionista de televisión?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 0 23 0 0]Pues resulta que... es mi padre.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 0 24 0 0]Ahora entiendo lo importante que es la sinceridad y me enorgullezco de ello. Y también me he dado cuenta de lo increíble que es mi padre.[n][uf 1 1][e]

[msg MSG_018_5_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 0 25 0 0]Es hora de irse.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 0 26 0 0]Oye, [uf 4 1], ¿quieres parar en algún lado antes de irnos a casa?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 0 27 0 0]Ahora que caigo, nunca hemos quedado fuera del instituto.[n][uf 1 1][e]

[msg MND_019_0_0]
[uf 0 5 65278][uf 2 1]Me voy a casa con Hidetoshi, que está de buen humor.[n][uf 1 1][e]

