[msg MSG_000_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5002 0 0]Você sabia que parte do nome Kirijo vem do caractere para a árvore "kiri japonês"?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Eu pesquisei online. Como este shopping pertence ao Kirijo Group, o nome foi em homenagem ao grupo.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Acho que o Kirijo Group também é a matriz da nossa escola.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Interessante, não acha?[n][uf 1 1][e]

[msg MSG_001_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Ah, a propósito...[n][uf 1 1][e]

[msg MSG_002_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5075 0 0]Queria te perguntar uma coisa...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Eu tava conversando com o farmacêutico na Drogaria Aohige sobre culinária...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 65535 0 0][uf 4 23 0 6 3 25 25]E ele me recomendou usar carne seca de cobra como ingrediente... Dá pra acreditar?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 4 23 0 6 0 25 25]Hum... E se eu realmente fizesse um prato com carne de cobra, você comeria, [uf 4 1]-chan?[n][uf 1 1][e]

[sel SEL_003_0_0 top]
[uf 0 5 65278][uf 2 1]É claro.[e]
[uf 0 5 65278][uf 2 1]Não precisa fazer isso.[e]
[uf 0 5 65278][uf 2 1]Você quem sabe.[e]

[msg MSG_004_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 65535 0 0][uf 3 1 3 0 65535 5099 0 0][uf 5 13 3 15 6]Hã...? Espera, sério? T-Tenho mesmo que cozinhar com carne de cobra?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 65535 0 0]Mas, se é isso que você quer, então...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 6 65535 65535 0 0][uf 4 23 0 6 6 25 25][uf 4 25 6]...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 6 65535 65535 0 0]Desculpa... Não acho que consigo fazer isso. Só de pensar em tocar numa cobra, morta ou viva, fico toda arrepiada.[n][uf 1 1][e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]Fuuka parece estar se divertindo.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Eu aprendi mais a respeito dela hoje.[n][uf 1 1][e]

[msg MSG_006_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 3 0 65535 5025 0 0][uf 5 13 3 30 6]É-É, acho que não.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0]Fiquei com medo de você dizer que quer experimentar...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 6 65535 65535 0 0][uf 4 23 0 6 6 25 25]Acho que não sou capaz de cozinhar com carne de cobra... não ia nem conseguir tocar de medo.[n][uf 1 1][e]

[msg MND_007_0_0]
[uf 0 5 65278][uf 2 1]Fuuka parece aliviada.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Acho que nos aproximamos muito hoje.[n][uf 1 1][e]

[msg MSG_008_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 65535 0 0][uf 3 1 3 0 65535 5113 0 0]Então, acho melhor não...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 65535 0 0]Você já viu a cara da carne seca de cobra?![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 65535 0 0]Tem a textura de uma Sombra e é longa como a mangueira de um caminhão de incêndio...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 65535 0 0]Não levo um negócio desses pra dentro do dormitório de jeito nenhum! Não suportaria sequer tocar nesse treco![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 65535 0 0][uf 4 25 6]...[n][uf 1 1][e]

[msg MND_009_0_0]
[uf 0 5 65278][uf 2 1]Fuuka está com os olhos marejados...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Acho que não nos aproximamos hoje...[n][uf 1 1][e]

[msg MSG_010_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5061 0 0]Que outro ingrediente poderia substituir carne de cobra? Enguia?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Mas tenho a sensação de que a textura seria a mesma...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 4 23 0 6 1 25 25]Talvez eu encontre alguma alternativa no mercado de peixe. Quer ir comigo, [uf 4 1]-chan?[n][uf 1 1][e]

[msg MND_011_0_0]
[uf 0 5 65278][uf 2 1]Fomos comprar ingredientes[n]antes de voltar para o dormitório.[n][uf 1 1][e]

