[msg MSG_JUNPEI_TARTAROS_1201 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]Tomorrow's a full moon... Not like that means anything anymore, though.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]Man, there's nothing to do. I'm so bored...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]Maybe I'll go hang out with Ryoji.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0]I didn't see him at school today, but he was prolly just ditchin', so he should be around.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 65535 65535 0 0][uf 3 1 3 0 65535 2072 0 0]Oh, wait... Crap, I don't know where he lives...[n][uf 1 1][e]

[msg MSG_FUKA_TARTAROS_1202_1 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]There will be a full moon tonight...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]But we won't be conducting an operation.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]I was thinking I might summon Juno and search around a little just in case, though.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Oh, by the way, have you seen Aigis, [uf 4 1]-chan?[n][uf 1 1][e]

[sel SEL_002_0_0 top]
[uf 0 5 65278][uf 2 1]No, I haven't.[e]
[uf 0 5 65278][uf 2 1]Maybe she's in her room?[e]

[msg MSG_FUKA_TARTAROS_1202_2 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5028 0 0]Hm... Aigis has been coming home late recently...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]She didn't use to...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 65535 0 0]I wonder if something happened. I hope she's okay...[n][uf 1 1][e]

[msg MSG_JUNPEI_TARTAROS_1204 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 3 0 65535 2093 0 0][uf 4 25 3]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]Oh, hey...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0]So, like... what if everything yesterday was all just some crazy dream, y'know?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 4 25 3]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 10 65535 65535 0 0][uf 3 1 3 0 65535 2056 0 0]Prolly not, though, huh...?[n][uf 1 1][e]

[msg MSG_MITURU_1205_1 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 10 65535 65535 0 0][uf 3 1 3 0 65535 4097 0 0]...Oh, [uf 4 1].[n][uf 1 1][e]

[msg MSG_MITURU_1205_2 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 10 65535 65535 0 0]Um... Do you suppose...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 10 65535 65535 0 0][uf 4 25 5]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 10 65535 65535 0 0]No, never mind. There's no point in asking such things...[n][uf 1 1][e]

[sel SEL_006_0_0 top]
[uf 0 5 65278][uf 2 1]You're right.[e]
[uf 0 5 65278][uf 2 1]Are you scared?[e]

[msg MSG_MITURU_1205_RE_1 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 10 65535 65535 0 0]Yes...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 10 65535 65535 0 0][uf 3 1 3 0 65535 4027 0 0]I'm sorry. Forget I said anything.[n][uf 1 1][e]

[msg MSG_MITURU_1205_RE_2 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 10 65535 65535 0 0][uf 3 1 3 0 65535 4034 0 0]No, I don't think "scared" is the right word. I just can't seem to comprehend all that has happened.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 10 65535 65535 0 0]I thought I had become stronger after dealing with what happened to my father, but...[n][uf 1 1][e]

[msg MSG_SANADA_1206 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 3 65535 65535 0 0][uf 3 1 3 0 65535 3090 0 0][uf 4 25 4]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Hm...? Oh, it's you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Sorry, I was just thinking.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]...I was wondering, if I meet Shinji again some day, what he would say to me.[n][uf 1 1][e]

[sel SEL_010_0_0 top]
[uf 0 5 65278][uf 2 1]What would he say?[e]
[uf 0 5 65278][uf 2 1]Are you scared of death?[e]

[msg MSG_SANADA_1206_RE_1 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3031 0 0]I bet he wouldn't say anything.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]He'd just punch me in the face before either of us has a chance to speak.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]He's got a strong right hook, so I'm sure it's gonna hurt.[n][uf 1 1][e]

[msg MSG_SANADA_1206_RE_2 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3061 0 0]Death, huh...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Well, in terms of my own death, I can't always even fully wrap my head around it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]It's pathetic, isn't it? Especially considering how many times I've had to deal with others'...[n][uf 1 1][e]

[msg MSG_FUKA_1207 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 4 25 6]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]U-Um...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Why don't... we all try to cheer up a little?[n][uf 1 1][e]

[sel SEL_014_0_0 top]
[uf 0 5 65278][uf 2 1]I'm not sad, though.[e]
[uf 0 5 65278][uf 2 1]Good idea.[e]

[msg MSG_FUKA_1207_RE_1 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 65535 0 0][uf 3 1 3 0 65535 5092 0 0]O-Oh, I see.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 65535 0 0]Umm...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 65535 0 0]I'm sorry, [uf 4 1]-chan. I shouldn't be making assumptions...[n][uf 1 1][e]

[msg MSG_FUKA_1207_RE_2 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 65535 0 0][uf 3 1 3 0 65535 5067 0 0]Oh, um... Thank you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 65535 0 0][uf 4 25 6]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 65535 0 0]Sorry... I think I'm actually the one who's the most uneasy right now...[n][uf 1 1][e]

[msg MSG_YUKARI_1209 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 10 65535 65535 0 0]It's already been a week since Ryoji-kun told us everything, huh...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 10 65535 65535 0 0]I couldn't sleep for three days after that.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 10 65535 65535 0 0]It... feels weird, being this scared.[n][uf 1 1][e]

[sel SEL_018_0_0 top]
[uf 0 5 65278][uf 2 1]Yeah, it does.[e]
[uf 0 5 65278][uf 2 1]Everyone else is scared, too.[e]

[msg MSG_YUKARI_1209_RE_1 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1028 0 0]Yeah... I think I'm only just now realizing...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]No one really knows how much they take their lives for granted...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]Until they think there's a real possibility they might lose it.[n][uf 1 1][e]

[msg MSG_YUKARI_1209_RE_2 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1028 0 0]Yeah, I guess you're right.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]You know... I feel like no one really knows how much they take their lives for granted...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 10 65535 65535 0 0]Until they think there's a real possibility they might lose it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 10 65535 65535 0 0]I don't think anyone can really understand that kind of thing until they actually feel it...[n][uf 1 1][e]

[msg MSG_SANADA_STUDY_1211 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Exams begin next week.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]I know it's hard to focus, but don't ignore the present because you're worried about the future.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]That would just be giving up on life. No point in that.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3080 0 0]Personally, I'm going to keep on like always. I'll keep going to Tartarus, and studying too.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]I'm not leaving the ring without a win.[n][uf 1 1][e]

[msg MSG_FUKA_STUDY_1212 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 4 1]-chan, don't forget, it's almost time for exams.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 65535 0 0]I've been having a hard time trying to study, though. When I'm alone, my mind wanders...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 65535 0 0]...[uf 4 1]-chan, do you think maybe we could study together?[n][uf 1 1][e]

[msg MSG_JUNPEI_TARTAROS_1213 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]Exams start tomorrow, huh?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 10 65535 65535 0 0]I guess this'll be the first time I use an exam to distract me from something else, haha...[n][uf 1 1][e]

[msg MSG_MITURU_1219_1 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]After I finished my exams...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]I walked around town for a little while.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]The Lost are everywhere now... Running into them is no longer just an occasional incident.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Perhaps it has to do with the Fall.[n][uf 1 1][e]

[sel SEL_026_0_0 top]
[uf 0 5 65278][uf 2 1]It probably does.[e]
[uf 0 5 65278][uf 2 1]We have to do something.[e]

[msg MSG_MITURU_1219_RE_1 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4097 0 0]I haven't thought about it as much lately, but...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]We're the only ones who can save the world.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]It's all up to us.[n][uf 1 1][e]

[msg MSG_MITURU_1219_RE_2 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4027 0 0]Yes, I agree.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]We must continue going to Tartarus.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Whether our opponent is a Shadow or fate itself, we will need to be strong to win.[n][uf 1 1][e]

[msg MSG_YUKARI_TARTAROS_1221 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]Today is December 21st...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]Just ten days until New Year's Eve.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0]But, for some reason... I'm actually not scared at all.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]Well, maybe I shouldn't say "at all"... But I think I'm okay now.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 3 0 65535 1004 0 0]I'm gonna fight.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0]Whether we'd win or lose... I don't know. But I want to know that I did everything I could.[n][uf 1 1][e]

[msg MSG_AMADA_TARTAROS_1223 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]There are eight more days until New Year's Eve...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 4 1]-san, do you know what you'll decide yet?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7085 0 0]Well, I do. I'm going to fight.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0]I was thinking about it a lot, but then I realized there wasn't much to think about.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0]I mean, I can't tell my mom and Aragaki-san that we failed. So... that's that.[n][uf 1 1][e]

[msg MSG_SANADA_TARTAROS_1225 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]So today's December 25th.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]But all this talk about "death" and "fate"... What a depressing Christmas.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Christmas will be better next year.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3061 0 0]That's right, I said it—"next year." We're not gonna let the world end.[n][uf 1 1][e]

[msg MSG_MITURU_TARTAROS_1226 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]The second term is over... and only five days remain until New Year's Eve.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]To be completely honest, I'm still nervous...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]However, I am no longer uncertain.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4080 0 0]I have made up my mind beyond the shadow of a doubt.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]I will fight until the very end.[n][uf 1 1][e]

[msg MSG_FUKA_TARTAROS_1227 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Only four more days until New Year's Eve...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 65535 0 0]I was really worried for a while, and I wasn't sure what I was going to do...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 65535 0 0]I even thought my fear might completely overtake me and I wouldn't be able to decide anything...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5035 0 0]But I was wrong.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]I actually feel strong...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 3 0 65535 5116 0 0]Because everyone is with me.[n][uf 1 1][e]

[msg MSG_FUKA_TARTAROS_1228 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 65535 0 0]There are just three more days until New Year's Eve.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 65535 0 0]Have you decided what you're going to say to Ryoji-kun?[n][uf 1 1][e]

[msg MSG_JUNPEI_TARTAROS_1229 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]The day after tomorrow's the big day. You make up your mind yet?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0]I made up mine, by the way. Kinda took me a while to get there, though, haha.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 3 0 65535 2132 0 0]Well, you should make your choice soon, if you haven't. No changin' your mind at the last minute![n][uf 1 1][e]

[msg MSG_WELCOME_YUKARI_OUT [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1019 0 0]Oh, hey. Welcome back.[n][uf 1 1][e]

[msg MSG_WELCOME_YUKARI_OUT2 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1012 0 0]Hey... Welcome back...[n][uf 1 1][e]

[msg MSG_WELCOME_JUNPEI_OUT [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 3 0 65535 2018 0 0]'Sup, dude?[n][uf 1 1][e]

[msg MSG_WELCOME_JUNPEI_OUT2 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 3 0 65535 2012 0 0]Hey, man...[n][uf 1 1][e]

[msg MSG_WELCOME_MITSURU_OUT [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4018 0 0]Welcome back.[n][uf 1 1][e]

[msg MSG_WELCOME_MITSURU_OUT2 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4027 0 0]Welcome back...[n][uf 1 1][e]

[msg MSG_WELCOME_SANADA_OUT [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3017 0 0]Oh, you're back.[n][uf 1 1][e]

[msg MSG_WELCOME_FUKA_OUT [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5018 0 0]Hi, how was your day?[n][uf 1 1][e]

[msg MSG_WELCOME_FUKA_OUT2 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5028 0 0]Oh... Hello...[n][uf 1 1][e]

[msg MSG_WELCOME_AEGIS_OUT_RO [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 3 0 65535 6018 0 0]Greetings.[n][uf 1 1][e]

[msg MSG_WELCOME_AEGIS_OUT [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6018 0 0]Greetings.[n][uf 1 1][e]

[msg MSG_WELCOME_AEGIS_OUT_NA [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6017 0 0]Welcome back. It's good to see you again.[n][uf 1 1][e]

[msg MSG_WELCOME_KOROMARU_OUT [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 3 0 65535 8008 0 0]Arf![n][uf 1 1][e]

[msg MSG_WELCOME_AMADA_OUT [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7020 0 0]Oh, hello![n][uf 1 1][e]

[msg MSG_WELCOME_AMADA_OUT2 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7012 0 0]Oh... Hi...[n][uf 1 1][e]

[msg MSG_WELCOME_ARAGAKI_OUT [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0][uf 3 1 3 0 65535 9014 0 0]...Hey.[n][uf 1 1][e]

[msg MSG_WELCOME_IKUTSUKI_OUT [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 3 0 65535 14201 0 0]Hello there. Welcome back.[n][uf 1 1][e]

[msg MSG_WELCOME_YUKARI_IN [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1067 0 0]Oh, there you are![n][uf 1 1][e]

[msg MSG_WELCOME_YUKARI_IN2 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1012 0 0]Oh, you're here? Sorry, guess I missed you...[n][uf 1 1][e]

[msg MSG_WELCOME_JUNPEI_IN [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 3 0 65535 2009 0 0]Yooo, what's up?[n][uf 1 1][e]

[msg MSG_WELCOME_JUNPEI_IN2 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 3 0 65535 2012 0 0]Oh, hey...[n][uf 1 1][e]

[msg MSG_WELCOME_MITSURU_IN [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Hm? Oh, it's you.[n][uf 1 1][e]

[msg MSG_WELCOME_MITSURU_IN2 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4027 0 0]Hm...? Oh, I see you're here...[n][uf 1 1][e]

[msg MSG_WELCOME_SANADA_IN [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3024 0 0]Were you in your room all this time?[n][uf 1 1][e]

[msg MSG_WELCOME_FUKA_IN [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5067 0 0]Oh, hello! I didn't realize you were already here.[n][uf 1 1][e]

[msg MSG_WELCOME_FUKA_IN2 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5093 0 0]Oh, you're here? Hello...[n][uf 1 1][e]

[msg MSG_WELCOME_FUKA_IN_0712 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5067 0 0]Oh, [uf 4 1]-chan...![n][uf 1 1][e]

[msg MSG_WELCOME_AEGIS_IN_ROB [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 3 0 65535 6008 0 0]Good evening.[n][uf 1 1][e]

[msg MSG_WELCOME_AEGIS_IN [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6008 0 0]Good evening.[n][uf 1 1][e]

[msg MSG_WELCOME_AEGIS_IN_NAK [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6009 0 0]Did you have a good day?[n][uf 1 1][e]

[msg MSG_WELCOME_KOROMARU_IN [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 3 0 65535 8001 0 0]Arf, arf![n][uf 1 1][e]

[msg MSG_WELCOME_AMADA_IN [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7010 0 0]Get any studying done?[n][uf 1 1][e]

[msg MSG_WELCOME_AMADA_IN2 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7012 0 0]You were here? Well... Hello.[n][uf 1 1][e]

[msg MSG_WELCOME_ARAGAKI_IN [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0][uf 3 1 3 0 65535 9056 0 0]...'Sup?[n][uf 1 1][e]

[msg MSG_WELCOME_IKUTSUKI_IN [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 3 0 65535 14204 0 0]Oh, I didn't know you were already here. As you can see, I've come over for a quick visit.[n][uf 1 1][e]

[msg MND_SHYUKAKU_OK]
[uf 0 5 65278][uf 2 1]Come to think of it, the crops I planted on the[n]rooftop should be ready to harvest by now...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Maybe I should go check on them...[n][uf 1 1][e]

[msg MND_SHYUKAKU_TAIYAKI_OK]
[uf 0 5 65278][uf 2 1]Come to think of it, the crops I planted on the[n]rooftop should be ready to harvest by now...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]...And the taiyaki I put in the[n]fridge should be chilled, too.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Maybe I should go check on them...[n][uf 1 1][e]

[msg MND_SHYUKAKU_TAIYAKI_OK_]
[uf 0 5 65278][uf 2 1]Come to think of it, the crops I planted on the[n]rooftop should be ready to harvest by now...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]...And the taiyaki I put in the[n]fridge should be chilled, too.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I should get it from the fridge[n]and give it to Elizabeth...[n][uf 1 1][e]

[msg MND_TAIYAKI_OK]
[uf 0 5 65278][uf 2 1]Come to think of it, the taiyaki I put in[n]the fridge should be chilled by now...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Maybe I should go get it...[n][uf 1 1][e]

[msg MND_TAIYAKI_OK_QUEST]
[uf 0 5 65278][uf 2 1]Come to think of it, the taiyaki I put in[n]the fridge should be chilled by now...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I should get it from the fridge[n]and give it to Elizabeth...[n][uf 1 1][e]

[msg MSG_ERROR [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1]エラーメッセージです。[n][uf 1 5 0]杉山まで報告ください。[n][uf 1 1][e]

