[msg MND_GoodEnd_0303]
[uf 0 5 65278][uf 2 1]...All is quiet.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]It doesn't seem like the[n]others have returned yet.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]They all must be enjoying[n]the peaceful evening...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I only went to school today, but my[n]whole body feels heavy and sluggish...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I can't keep my eyes open...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I should head to bed early tonight.[n][uf 1 1][e]

[msg MND_GoodEnd_0304]
[uf 0 5 65278][uf 2 1]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel so exhausted...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I can't keep my eyes open...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]The third-years' graduation[n]ceremony is tomorrow.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I should head to bed early tonight.[n][uf 1 1][e]

[msg MSG_WELCOME_YUKARI_OUT [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1019 0 0]Oh, hey. Welcome back.[n][uf 1 1][e]

[msg MSG_WELCOME_YUKARI_OUT2 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1012 0 0]Hey... Welcome back...[n][uf 1 1][e]

[msg MSG_WELCOME_JUNPEI_OUT [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 3 0 65535 2018 0 0]'Sup, dude?[n][uf 1 1][e]

[msg MSG_WELCOME_JUNPEI_OUT2 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 3 0 65535 2012 0 0]Hey, man...[n][uf 1 1][e]

[msg MSG_WELCOME_MITSURU_OUT [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4018 0 0]Welcome back.[n][uf 1 1][e]

[msg MSG_WELCOME_MITSURU_OUT2 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4027 0 0]Welcome back...[n][uf 1 1][e]

[msg MSG_WELCOME_SANADA_OUT [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3017 0 0]Oh, you're back.[n][uf 1 1][e]

[msg MSG_WELCOME_FUKA_OUT [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5018 0 0]Hi, how was your day?[n][uf 1 1][e]

[msg MSG_WELCOME_FUKA_OUT2 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5028 0 0]Oh... Hello...[n][uf 1 1][e]

[msg MSG_WELCOME_AEGIS_OUT_RO [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 3 0 65535 6018 0 0]Greetings.[n][uf 1 1][e]

[msg MSG_WELCOME_AEGIS_OUT [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6018 0 0]Greetings.[n][uf 1 1][e]

[msg MSG_WELCOME_AEGIS_OUT_NA [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6017 0 0]Welcome back. It's good to see you again.[n][uf 1 1][e]

[msg MSG_WELCOME_KOROMARU_OUT [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 3 0 65535 8008 0 0]Arf![n][uf 1 1][e]

[msg MSG_WELCOME_AMADA_OUT [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7020 0 0]Oh, hello![n][uf 1 1][e]

[msg MSG_WELCOME_AMADA_OUT2 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7012 0 0]Oh... Hi...[n][uf 1 1][e]

[msg MSG_WELCOME_ARAGAKI_OUT [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0][uf 3 1 3 0 65535 9014 0 0]...Hey.[n][uf 1 1][e]

[msg MSG_WELCOME_IKUTSUKI_OUT [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 3 0 65535 14201 0 0]Hello there. Welcome back.[n][uf 1 1][e]

[msg MSG_WELCOME_YUKARI_IN [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1067 0 0]Oh, there you are![n][uf 1 1][e]

[msg MSG_WELCOME_YUKARI_IN2 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1012 0 0]Oh, you're here? Sorry, guess I missed you...[n][uf 1 1][e]

[msg MSG_WELCOME_JUNPEI_IN [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 3 0 65535 2009 0 0]Yooo, what's up?[n][uf 1 1][e]

[msg MSG_WELCOME_JUNPEI_IN2 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 3 0 65535 2012 0 0]Oh, hey...[n][uf 1 1][e]

[msg MSG_WELCOME_MITSURU_IN [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Hm? Oh, it's you.[n][uf 1 1][e]

[msg MSG_WELCOME_MITSURU_IN2 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4027 0 0]Hm...? Oh, I see you're here...[n][uf 1 1][e]

[msg MSG_WELCOME_SANADA_IN [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3024 0 0]Were you in your room all this time?[n][uf 1 1][e]

[msg MSG_WELCOME_FUKA_IN [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5067 0 0]Oh, hello! I didn't realize you were already here.[n][uf 1 1][e]

[msg MSG_WELCOME_FUKA_IN2 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5093 0 0]Oh, you're here? Hello...[n][uf 1 1][e]

[msg MSG_WELCOME_FUKA_IN_0712 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5067 0 0]Oh, [uf 4 1]-chan...![n][uf 1 1][e]

[msg MSG_WELCOME_AEGIS_IN_ROB [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 3 0 65535 6008 0 0]Good evening.[n][uf 1 1][e]

[msg MSG_WELCOME_AEGIS_IN [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6008 0 0]Good evening.[n][uf 1 1][e]

[msg MSG_WELCOME_AEGIS_IN_NAK [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6009 0 0]Did you have a good day?[n][uf 1 1][e]

[msg MSG_WELCOME_KOROMARU_IN [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 3 0 65535 8001 0 0]Arf, arf![n][uf 1 1][e]

[msg MSG_WELCOME_AMADA_IN [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7010 0 0]Get any studying done?[n][uf 1 1][e]

[msg MSG_WELCOME_AMADA_IN2 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7012 0 0]You were here? Well... Hello.[n][uf 1 1][e]

[msg MSG_WELCOME_ARAGAKI_IN [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0][uf 3 1 3 0 65535 9056 0 0]...'Sup?[n][uf 1 1][e]

[msg MSG_WELCOME_IKUTSUKI_IN [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 3 0 65535 14204 0 0]Oh, I didn't know you were already here. As you can see, I've come over for a quick visit.[n][uf 1 1][e]

[msg MND_SHYUKAKU_OK]
[uf 0 5 65278][uf 2 1]Come to think of it, the crops I planted on the[n]rooftop should be ready to harvest by now...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Maybe I should go check on them...[n][uf 1 1][e]

[msg MND_SHYUKAKU_TAIYAKI_OK]
[uf 0 5 65278][uf 2 1]Come to think of it, the crops I planted on the[n]rooftop should be ready to harvest by now...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]...And the taiyaki I put in the[n]fridge should be chilled, too.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Maybe I should go check on them...[n][uf 1 1][e]

[msg MND_SHYUKAKU_TAIYAKI_OK_]
[uf 0 5 65278][uf 2 1]Come to think of it, the crops I planted on the[n]rooftop should be ready to harvest by now...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]...And the taiyaki I put in the[n]fridge should be chilled, too.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I should get it from the fridge[n]and give it to Elizabeth...[n][uf 1 1][e]

[msg MND_TAIYAKI_OK]
[uf 0 5 65278][uf 2 1]Come to think of it, the taiyaki I put in[n]the fridge should be chilled by now...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Maybe I should go get it...[n][uf 1 1][e]

[msg MND_TAIYAKI_OK_QUEST]
[uf 0 5 65278][uf 2 1]Come to think of it, the taiyaki I put in[n]the fridge should be chilled by now...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I should get it from the fridge[n]and give it to Elizabeth...[n][uf 1 1][e]

[msg MSG_ERROR [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1]エラーメッセージです。[n][uf 1 5 0]杉山まで報告ください。[n][uf 1 1][e]

