[msg MSG_000_0_0 [Man in a Suit]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 1 65535 65535 0 0][uf 3 1 1 0 0 1 0 0][uf 4 23 0 1 1 25 25]All right... If you insist, I'll give you my autograph. It's always a pleasure to meet a fan.[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]Who are you?[e]
[uf 0 5 65278][uf 2 1]No, I don't need one.[e]
[uf 0 5 65278][uf 2 1]You look familiar...[e]

[msg MSG_002_0_0 [Man in a Suit]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 2 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]...Don't you have a television? Are you living in the stone age? How barbaric![n][uf 1 1][e]

[msg MSG_003_0_0 [Man in a Suit]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 2 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]Oh, don't be ridiculous! Never look a gift horse in the mouth.[n][uf 1 1][e]

[msg MSG_004_0_0 [Man in a Suit]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 3 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]Oh my... It's so very difficult being famous. I can hardly go anywhere without being recognized.[n][uf 1 1][e]

[msg MSG_005_0_0 [Man in a Suit]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 1 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]I'm sure you've seen the home-shopping program Tanaka's Amazing Commodities, yes?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 1 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]Allow me to introduce myself.[n][uf 1 1][e]

[msg MND_006_0_0]
[uf 0 5 65278][uf 2 1]The man handed me a business card...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]It says, "Tanaka, President & CEO."[n][uf 1 1][e]

[msg MSG_007_0_0 [President Tanaka]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 1 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]That's right! I'm Tanaka himself. Surely you've heard the name.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 1 65535 65535 0 0][uf 3 1 1 0 0 8 0 0]I'm afraid I can't offer any returns on your 40,000 yen, but I've autographed my business card for you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 1 65535 65535 0 0][uf 3 1 1 0 0 9 0 0]Hold onto that—it'll be worth a pretty penny in a year or so! And with that, I must be going.[n][uf 1 1][e]

[msg MSG_008_0_0 [President Tanaka]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 2 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]That little brat... Doesn't she realize she's in the presence of a star!?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 2 65535 65535 0 0][uf 3 1 1 0 0 11 0 0]Time is money—especially mine! I should've squeezed a few more payments out of her...[n][uf 1 1][e]

[msg MND_009_0_0]
[uf 0 5 65278][uf 2 1]It sounds like he's talking about me...[n][uf 1 1][e]

[sel SEL_010_0_0 top]
[uf 0 5 65278][uf 2 1]I can hear you.[e]
[uf 0 5 65278][uf 2 1]Ignore him[e]

[msg MSG_011_0_0 [President Tanaka]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 2 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]Huh!? Er— What do you want!? Quit disturbing me! Get out of here, shoo![n][uf 1 1][e]

[msg MSG_012_0_0 [President Tanaka]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 2 65535 65535 0 0][uf 3 1 0 0 0 13 0 0]......[n][uf 1 1][e]

[msg MSG_012_5_0 [President Tanaka]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 2 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]Hey! Go away! You're making me nervous! Get out of here, shoo![n][uf 1 1][e]

[msg MSG_013_0_0 [President Tanaka]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 2 65535 65535 0 0][uf 3 1 1 0 0 15 0 0]You... You overheard me talking to myself just now, didn't you!?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 2 65535 65535 0 0][uf 3 1 1 0 0 16 0 0]You'll forget it ever happened if you know what's good for you. I belong to a powerful talent agency.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 2 65535 65535 0 0][uf 3 1 1 0 0 17 0 0]I'm practically a celebrity. I have an image to maintain![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 2 65535 65535 0 0][uf 3 1 1 0 0 18 0 0]Don't even think about telling someone that I took your money or called you a little brat! Capiche!?[n][uf 1 1][e]

[sel SEL_014_0_0 top]
[uf 0 5 65278][uf 2 1]Got it.[e]
[uf 0 5 65278][uf 2 1]I'll tell everyone.[e]

[msg MSG_015_0_0 [President Tanaka]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 1 65535 65535 0 0][uf 3 1 1 0 0 19 0 0]...Blind obedience has a price attached. Better learn that before it bites ya, kiddo.[n][uf 1 1][e]

[msg MSG_016_0_0 [President Tanaka]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 2 65535 65535 0 0][uf 3 1 1 0 0 20 0 0]Don't get cute with me! You think you can get away with anything with that pretty face of yours!?[n][uf 1 1][e]

[msg MSG_017_0_0 [President Tanaka]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 1 65535 65535 0 0][uf 3 1 1 0 0 21 0 0]Oh, silly me! I've let you in on my little secret, haven't I? Heh heh heh...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 1 65535 65535 0 0][uf 3 1 1 0 0 22 0 0]Don't... tell anyone, okay?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 1 65535 65535 0 0][uf 3 1 1 0 0 23 0 0]Please! I'll lick your shoes clean if you want me to![n][uf 1 1][e]

[sel SEL_018_0_0 top]
[uf 0 5 65278][uf 2 1]All right.[e]
[uf 0 5 65278][uf 2 1]That's okay.[e]

[msg MSG_019_0_0 [President Tanaka]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 0 65535 65535 0 0][uf 3 1 1 0 0 24 0 0]Er— Really? You promise? You better be ready to cross your heart and hope to die if you're lying to me![n][uf 1 1][e]

[msg MSG_020_0_0 [President Tanaka]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 0 65535 65535 0 0][uf 3 1 1 0 0 25 0 0]So... you won't tell anyone, right? You better be ready to cross your heart and hope to die if you're lying to me![n][uf 1 1][e]

[msg MSG_021_0_0 [President Tanaka]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 2 65535 65535 0 0][uf 3 1 1 0 0 26 0 0]A verbal agreement is a form of contract, and if you breach it I'll sue your pants off![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 1 65535 65535 0 0][uf 3 1 1 0 0 27 0 0][uf 4 23 0 1 1 25 25]I've got your adorable little face etched into my memory.[n][uf 1 1][e]

[msg MND_022_0_0]
[uf 0 5 65278][uf 2 1]...He seems to have taken an interest in me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I'm now acquainted with Tanaka, the[n]producer of a home shopping TV show...[n][uf 1 1][e]

[msg MSG_023_0_0 [President Tanaka]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 0 65535 65535 0 0][uf 3 1 1 0 0 28 0 0]You're a diamond in the rough, my girl. All you need is a little polishing, and you'll sparkle.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 1 65535 65535 0 0][uf 3 1 1 0 0 29 0 0][uf 4 23 0 1 1 25 25]I often take my breaks here. I'd be happy to mold your young mind whenever you wish.[n][uf 1 1][e]

[msg MND_024_0_0]
[uf 0 5 65278][uf 2 1]After parting ways with President Tanaka,[n]I decided to return to the dorm.[n][uf 1 1][e]

[msg MND_024_5_0]
[uf 0 5 65278][uf 2 1]I parted ways with President Tanaka.[n]I should show Elizabeth this autograph[n]when I have the chance...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]For now, I'll return to the dorm.[n][uf 1 1][e]

