[msg MSG_000_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 0 0 0 1 0 0]...[n][uf 1 1][e]

[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]Sinto que meu nível de [uf 4 30 0 1 1 0][n]aumentou graças à expressão habilidosa na escrita.[n][uf 1 1][e]

[msg MSG_002_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]Ah, [uf 4 1]-chan. Você terminou de ler o livro final?[n][uf 1 1][e]

[msg MSG_003_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]Você ficou com uma cara superconcentrada enquanto lia. Me identifiquei muito.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]Quando cheguei no fim, estava tão absorta que quase esqueci de respirar.[n][uf 1 1][e]

[msg MSG_004_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]Que série incrível...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]No começo eu não notei, mas chegou uma hora que eu entendi, subitamente, a complexidade daquele universo. Não é curioso?[n][uf 1 1][e]

[sel SEL_005_0_0 top]
[uf 0 5 65278][uf 2 1]É como uma fantasia.[e]
[uf 0 5 65278][uf 2 1]Essa é a magia da escrita.[e]
[uf 0 5 65278][uf 2 1]Eu pulo as partes complicadas.[e]

[msg MSG_006_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]Ah, realmente parece ser assim, não é?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 8 0 0]A ficção científica intimida um pouco, mas muitas vezes vai de mãos dadas com a fantasia, né?[n][uf 1 1][e]

[msg MSG_007_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 9 0 0]Isso mesmo. Se fossem só explicações, seria cansativo demais tentar acompanhar todos os detalhes.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]Ser capaz de amarrar a construção do mundo na narrativa demonstra como o autor é habilidoso.[n][uf 1 1][e]

[msg MSG_008_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 11 0 0]Ah, eu também faço muito isso.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 12 0 0][uf 4 23 0 6 0 25 25]Às vezes você não entende tudo na primeira leitura, mas tudo começa a fazer sentido se continuar.[n][uf 1 1][e]

[msg MSG_009_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]Eu queria saber me comunicar tão bem quanto o autor faz neste livro.[n][uf 1 1][e]

[msg MSG_009_3_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]Lembra quando eu contei que tinha recomendado um livro a uma colega, mas ela não aceitou?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 15 0 0]Saber o que dizer é importante, mas saber como dizer também é difícil.[n][uf 1 1][e]

[msg MSG_009_7_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 16 0 0]Queria que ela soubesse como o livro é fascinante, mas ela estava mais preocupada com o tamanho da série ou a fama do autor.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 17 0 0]Não tem como convencer alguém a ler esta série se ela faz essas perguntas.[n][uf 1 1][e]

[sel SEL_010_0_0 top]
[uf 0 5 65278][uf 2 1]Você vai se sair melhor da próxima vez.[e]
[uf 0 5 65278][uf 2 1]Essa é difícil.[e]

[msg MSG_011_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 18 0 0]Obrigada. Talvez eu tente falar com ela de novo.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 19 0 0]Acho que terei muitas coisas boas a dizer sobre o livro quando chegar a hora.[n][uf 1 1][e]

[msg MSG_012_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 20 0 0]Certo. É tão fácil recorrer a informações assim, tipo os números de vendas ou o prestígio do autor.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 21 0 0]Mas, para explicar como uma história é boa, tenho que começar pelas emoções que ela evoca quando você lê.[n][uf 1 1][e]

[msg MSG_013_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 22 0 0]É sempre uma sensação boa quando alguém demonstra interesse por algo que você gosta.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 23 0 0]Só de compartilhar nossas opiniões assim já é muito revigorante.[n][uf 1 1][e]

[msg MSG_013_3_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 24 0 0]Por isso eu quero muito trabalhar a forma como eu comunico as coisas.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 25 0 0]Porque, se eu conseguir melhorar, talvez viva mais momentos divertidos assim.[n][uf 1 1][e]

[msg MND_013_5_0]
[uf 0 5 65278][uf 2 1]Fuuka assente com determinação.[n][uf 1 1][e]

[msg MSG_014_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 26 0 0]Ah, olha só a hora. Acho que é melhor a gente encerrar.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 27 0 0]Hm...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 28 0 0]Tenho outros livros para recomendar, se você quiser.[n][uf 1 1][e]

[msg MSG_015_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 29 0 0][uf 5 13 3 1 6]Obrigada, [uf 4 1]-chan. Espero que você goste deles também.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 30 0 0]Bem, então, boa noite.[n][uf 1 1][e]

