[msg MSG_000_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 51 65535 0 0][uf 3 1 1 0 0 1 0 0]Hey, here she is![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 51 65535 0 0][uf 3 1 1 0 0 2 0 0]Man, we were worried about you.[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]Sorry about the wait.[e]
[uf 0 5 65278][uf 2 1]I'm glad you two are safe.[e]

[msg MSG_002_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 51 65535 0 0][uf 3 1 1 0 0 3 0 0]I don't think we should enter Tartarus this way again.[n][uf 1 1][e]

[msg MSG_003_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 51 65535 0 0][uf 3 1 1 0 0 4 0 0]Oh yeah! Did you hear a voice on your way here?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 51 65535 0 0][uf 3 1 1 0 0 5 0 0]Uh, kinda like—[n][uf 1 1][e]

[msg MSG_004_0_0 [Mysterious Voice]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 6 0 0]Who's there...? Are you... human?[n][uf 1 1][e]

[msg MSG_005_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 51 65535 0 0][uf 3 1 1 0 0 7 0 0]Th-That's it! That's the voice![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 51 65535 0 0][uf 3 1 1 0 0 8 0 0]Wait, didn't that come from behind us...?[n][uf 1 1][e]

[msg MSG_005_5_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 17 3 4 0][e]

[msg MSG_006_0_0 [Pale-Faced Girl]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 2 65535 0 0][uf 3 1 1 0 0 9 0 0]Ah...[n][uf 1 1][e]

[msg MSG_007_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 51 65535 0 0][uf 3 1 1 0 0 10 0 0]Are you Fuuka Yamagishi?[n][uf 1 1][e]

[msg MSG_008_0_0 [Pale-Faced Girl]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 2 65535 0 0][uf 3 1 1 0 0 11 0 0]Y-Yes![n][uf 1 1][e]

[msg MSG_009_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 51 65535 0 0][uf 3 1 1 0 0 12 0 0]Wow, you're alive! That's awesome![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 51 65535 0 0][uf 3 1 1 0 0 13 0 0]Never fear, the heroes are here![n][uf 1 1][e]

[msg MSG_010_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 51 65535 0 0][uf 3 1 1 0 0 14 0 0]Good to see you're okay.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 51 65535 0 0][uf 3 1 1 0 0 15 0 0][uf 4 23 0 4 0 25 25]Come with us.[n][uf 1 1][e]

[msg MSG_011_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 10 2 65535 0 0][uf 3 1 1 0 0 16 0 0]Thank you so much... I...[n][uf 1 1][e]

[sel SEL_012_0_0 top]
[uf 0 5 65278][uf 2 1]Don't worry, you're safe now.[e]
[uf 0 5 65278][uf 2 1]Are you okay?[e]

[msg MSG_012_5_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 10 2 65535 0 0][uf 3 1 1 0 0 17 0 0]Y-Yes, I'll be fine... Sorry, I'm just so relieved.[n][uf 1 1][e]

[msg MSG_013_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 51 65535 0 0][uf 3 1 1 0 0 18 0 0]Looks like I made the right call then. I'll see if I can contact Mitsuru.[n][uf 1 1][e]

[msg MSG_014_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 2 65535 0 0][uf 3 1 1 0 0 19 0 0]What is this place? One second I was at school, and then...[n][uf 1 1][e]

[msg MSG_015_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 51 65535 0 0][uf 3 1 1 0 0 20 0 0]Uhhh... It's kind of a long story. We can explain after we get outta here.[n][uf 1 1][e]

[msg MSG_016_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 51 65535 0 0][uf 3 1 1 0 0 21 0 0]Mitsuru, can you hear me?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 51 65535 0 0][uf 3 1 0 0 0 22 0 0]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 3 51 65535 0 0][uf 3 1 1 0 0 23 0 0]No good. All I hear is static.[n][uf 1 1][e]

[msg MSG_017_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 51 65535 0 0][uf 3 1 1 0 0 24 0 0]Oh, are you hurt anywhere?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 51 65535 0 0][uf 3 1 1 0 0 25 0 0]You've probably seen the monsters wanderin' around, right?[n][uf 1 1][e]

[msg MSG_018_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 2 65535 0 0][uf 3 1 1 0 0 26 0 0]So there is something dangerous in here, then.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 2 65535 0 0][uf 3 1 1 0 0 27 0 0]I've gotten by without them finding me so far.[n][uf 1 1][e]

[msg MSG_019_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 4 51 65535 0 0][uf 3 1 1 0 0 28 0 0]Wait, you've avoided them this entire time!?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 4 51 65535 0 0][uf 3 1 1 0 0 29 0 0]How is that possible?[n][uf 1 1][e]

[msg MSG_020_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 2 65535 0 0][uf 3 1 1 0 0 30 0 0]Umm, it's hard to describe, but... I can sort of tell where they are.[n][uf 1 1][e]

[msg MSG_021_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 51 65535 0 0][uf 3 1 1 0 0 31 0 0]Whaddaya mean? Are you saying you're psychic or somethin'?[n][uf 1 1][e]

[msg MSG_022_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 51 65535 0 0][uf 3 1 1 0 0 32 0 0]She has the same power as Mitsuru.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 51 65535 0 0][uf 3 1 1 0 0 33 0 0]Actually, she might be even stronger.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 51 65535 0 0][uf 3 1 1 0 0 34 0 0]Mitsuru's Persona was always more combat-focused to begin with.[n][uf 1 1][e]

[msg MSG_023_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 2 65535 0 0][uf 3 1 1 0 0 35 0 0]"Persona"...?[n][uf 1 1][e]

[msg MSG_024_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 51 65535 0 0][uf 3 1 1 0 0 36 0 0]Hang on to this.[n][uf 1 1][e]

[msg MSG_025_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 2 65535 0 0][uf 3 1 1 0 0 37 0 0]Huh!? W-Wait, is this... Is this a gun!?[n][uf 1 1][e]

[msg MSG_026_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 51 65535 0 0][uf 3 1 1 0 0 38 0 0]Think of it as a lucky charm. It doesn't actually fire bullets.[n][uf 1 1][e]

[msg MSG_027_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 2 65535 0 0][uf 3 1 1 0 0 39 0 0]Um, okay...[n][uf 1 1][e]

[msg MSG_028_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 51 65535 0 0][uf 3 1 1 0 0 40 0 0]All right, let's get outta here![n][uf 1 1][e]

