[msg MSG_000_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 51 65535 0 0][uf 3 1 1 0 0 1 0 0]Muito bem... Até que enfim chegou a hora.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 51 65535 0 0][uf 3 1 1 0 0 2 0 0]Eu sei que a gente pôs um peso enorme em vocês, mas agora passou.[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]A gente tá contando com você.[e]
[uf 0 5 65278][uf 2 1]Toma cuidado pra não exagerar.[e]
[uf 0 5 65278][uf 2 1]Quais são seus pontos fortes?[e]

[msg MSG_002_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 9 51 65535 0 0][uf 3 1 1 0 0 3 0 0]Relaxa, eu me preparei pra esse dia. Você não vai se decepcionar.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 9 51 65535 0 0][uf 3 1 1 0 0 4 0 0]Vou obedecer qualquer ordem que você der. Você que é a líder.[n][uf 1 1][e]

[msg MSG_003_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 9 51 65535 0 0][uf 3 1 1 0 0 5 0 0]Heh, relaxa. Eu tô ótimo.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 9 51 65535 0 0][uf 3 1 1 0 0 6 0 0]Tô quase com pena dos inimigos. É só me dar uma oportunidade que eu te mostro.[n][uf 1 1][e]

[msg MSG_004_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 51 65535 0 0][uf 3 1 1 0 0 7 0 0]Eu sou um guerreiro forte que sobrepuja os inimigos com os punhos.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 9 51 65535 0 0][uf 3 1 1 0 0 8 0 0][uf 4 23 0 1 9 25 25]Pelo menos é o que aparento, né? Mas não é só isso.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 9 51 65535 0 0][uf 3 1 1 0 0 9 0 0]Andei aperfeiçoando minhas habilidades, inclusive minha capacidade de acertar o ponto fraco dos inimigos. Você vai ver.[n][uf 1 1][e]

[msg MSG_005_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 51 65535 0 0][uf 3 1 1 0 0 10 0 0]Vou compensar o tempo perdido rapidinho.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 51 65535 0 0][uf 3 1 1 0 0 11 0 0]Além do mais, como um dos veteranos, eu tenho que mostrar que dou conta do recado. Não deixa de me botar no time.[n][uf 1 1][e]

