[msg MSG_000_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 1 65535 0 0][uf 3 1 1 0 0 1 0 0]Ah, ahí está.[n][uf 1 1][e]

[msg MSG_001_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 1 65535 0 0][uf 3 1 1 0 0 2 0 0]Pues se acabó el primer día de vuelta.[n][uf 1 1][e]

[msg MSG_002_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 1 65535 0 0][uf 3 1 1 0 0 3 0 0]Habéis llegado justo a tiempo.[n][uf 1 1][e]

[msg MSG_003_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 1 65535 0 0][uf 3 1 1 0 0 4 0 0]¿Justo a tiempo? ¿Para qué?[n][uf 1 1][e]

[msg MSG_004_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 1 65535 0 0][uf 3 1 1 0 0 5 0 0]Oye, Fuuka, ¿ya está lista Aigis?[n][uf 1 1][e]

[msg MSG_005_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 1 65535 0 0][uf 3 1 1 0 0 6 0 0]Mmm. ¿Qué te parece?[n][uf 1 1][e]

[msg MSG_006_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 7 0 0]Este es mi nuevo aspecto.[n][uf 1 1][e]

[msg MSG_007_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 1 65535 0 0][uf 3 1 1 0 0 8 0 0]¿Eh? ¿Por qué lleva un uniforme del insti? ¿Qué está pasando aquí?[n][uf 1 1][e]

[msg MSG_008_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 1 65535 0 0][uf 3 1 1 0 0 9 0 0]Dijo que quería ir al instituto y se lo comenté a los demás a modo de broma.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 1 65535 0 0][uf 3 1 1 0 0 10 0 0]Pero el director está de acuerdo, así que mañana empieza en segundo.[n][uf 1 1][e]

[msg MSG_009_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 1 65535 0 0][uf 3 1 1 0 0 11 0 0]¡¿En serio?! ¿A él le parece bien?[n][uf 1 1][e]

[msg MSG_010_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 1 65535 0 0][uf 3 1 1 0 0 12 0 0]Dijo algo sobre estudiar su comportamiento en un entorno social.[n][uf 1 1][e]

[sel SEL_011_0_0 top]
[uf 0 5 65278][uf 2 1]Típico de él.[e]
[uf 0 5 65278][uf 2 1]Ese no es el problema.[e]

[msg MSG_012_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 1 65535 0 0][uf 3 1 1 0 0 13 0 0]Bueno, si le parece bien, ¿por qué no?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 1 65535 0 0][uf 3 1 1 0 0 14 0 0][uf 4 23 0 3 1 25 25]Además, le queda estupendo. Diría que está guapa y todo.[n][uf 1 1][e]

[msg MSG_013_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 15 0 0]El camuflaje escolar que me ha proporcionado Fuuka es más que adecuado.[n][uf 1 1][e]

[msg MSG_014_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 1 65535 0 0][uf 3 1 1 0 0 16 0 0]Te queda de lo más natural. Nadie sospechará nada.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 1 65535 0 0][uf 3 1 1 0 0 17 0 0][uf 4 23 0 8 3 25 25]¿Por qué quieres ir al instituto? No es interesante.[n][uf 1 1][e]

[msg MSG_015_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 18 0 0]Con el comienzo del segundo trimestre, mi intención es sincronizar nuestros horarios para contar con una mayor eficiencia.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 19 0 0]Si me quedara aquí a la espera, podría afectar a nuestros despliegues.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 20 0 0]Para adaptarme, he solicitado un traslado junto a la líder del equipo.[n][uf 1 1][e]

[msg MSG_016_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 1 65535 0 0][uf 3 1 1 0 0 21 0 0]A nuestros despliegues... Me da la sensación de que tenerte en el instituto empeorará las cosas.[n][uf 1 1][e]

[msg MSG_017_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 22 0 0]Haré los ajustes necesarios a medida que evolucione la situación.[n][uf 1 1][e]

[msg MSG_018_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 1 65535 0 0][uf 3 1 1 0 0 23 0 0]Sí, claro, faltaría más.[n][uf 1 1][e]

[msg MSG_019_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 1 0 0 24 0 0]¡Guau, guau![n][uf 1 1][e]

[msg MSG_020_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 25 0 0]Ha dicho: "Yo también quiero ir al instituto".[n][uf 1 1][e]

[msg MSG_021_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 1 65535 0 0][uf 3 1 1 0 0 26 0 0]Koromaru, tú tienes que quedarte aquí.[n][uf 1 1][e]

[msg MSG_022_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 3 65535 65535 0 0][uf 3 1 1 0 0 27 0 0]Auuu...[n][uf 1 1][e]

