[msg MSG_000_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 3 0 65535 11063 0 0]...You can have mine if you're still hungry.[n][uf 1 1][e]

[msg MSG_001_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 1 0]D-Don't worry. I'm not feeling sick or anything like that...[n][uf 1 1][e]

[msg MSG_002_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 3 0 65535 11065 0 0]Hey, [uf 4 1]-chan, you got some sauce around your mouth.[n][uf 1 1][e]

[sel SEL_003_0_0 top]
[uf 0 5 65278][uf 2 1]Oh, thanks.[e]
[uf 0 5 65278][uf 2 1]It's fine.[e]
[uf 0 5 65278][uf 2 1]Will you wipe it off for me?[e]

[msg MSG_004_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 3 0 65535 11019 0 0][uf 5 13 12 15 106]You're welcome.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 4 23 0 106 0 25 25]...Aren't ya gonna wipe it off? It's kinda bugging me.[n][uf 1 1][e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]Yuko seems to be enjoying herself.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I learned a little more about her today.[n][uf 1 1][e]

[msg MSG_006_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 3 0 65535 11071 0 0]Really? It's pretty obvious, you know?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0]C'mon, wipe yourself up. Here's a napkin...[n][uf 1 1][e]

[msg MND_007_0_0]
[uf 0 5 65278][uf 2 1]Yuko looks a little exasperated.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like we didn't get any closer today...[n][uf 1 1][e]

[msg MSG_008_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 3 0 65535 11089 0 0][uf 5 13 12 30 106]You're more childish than you let on, [uf 4 1]-chan.[n][uf 1 1][e]

[msg MSG_008_5_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 1 0][uf 4 23 0 106 1 25 25]Okay, fine. Here, I'll get it for you...[n][uf 1 1][e]

[msg MND_009_0_0]
[uf 0 5 65278][uf 2 1]Yuko is blushing.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like we became a lot closer today.[n][uf 1 1][e]

[msg MSG_010_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 3 0 65535 11093 0 0]...The meals here are pretty well-balanced nutrition-wise.[n][uf 1 1][e]

[msg MSG_011_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0]It's low in fat and the side dishes help you get the vitamins and minerals you need...[n][uf 1 1][e]

[msg MSG_012_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 3 0 65535 11065 0 0]Hey, [uf 4 1]-chan, you got some sauce around your mouth.[n][uf 1 1][e]

[sel SEL_013_0_0 top]
[uf 0 5 65278][uf 2 1]Oh, thanks.[e]
[uf 0 5 65278][uf 2 1]It's fine.[e]
[uf 0 5 65278][uf 2 1]It's a fashion statement.[e]

[msg MSG_014_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 3 0 65535 11019 0 0][uf 5 13 12 15 106]No problem.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 4 23 0 106 0 25 25]...Aren't ya gonna wipe it off? It's kinda bugging me.[n][uf 1 1][e]

[msg MND_015_0_0]
[uf 0 5 65278][uf 2 1]Yuko seems to be enjoying herself.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I learned a little more about her today.[n][uf 1 1][e]

[msg MSG_016_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 3 0 65535 11090 0 0]Oh no it's not. Wanna check yourself in a mirror?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0]You look like you've got a mustache or something. Kinda like some old, wise man, haha...[n][uf 1 1][e]

[msg MND_017_0_0]
[uf 0 5 65278][uf 2 1]Yuko is laughing at how I look.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like we didn't get any closer today...[n][uf 1 1][e]

[msg MSG_018_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 3 0 65535 11077 0 0][uf 5 13 12 30 106]Uh-huh, totally. It's all the rage these days...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 4 23 0 106 1 25 25]Yeah, right! Haha... C'mon, wipe yourself off.[n][uf 1 1][e]

[msg MND_019_0_0]
[uf 0 5 65278][uf 2 1]Yuko seems to be enjoying herself.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like we became a lot closer today.[n][uf 1 1][e]

[msg MSG_020_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 3 0 65535 11064 0 0]Oh, hey, since we're already at the strip mall, maybe I'll stop by the bookstore on my way home.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 4 23 0 106 1 25 25]...What? You surprised? Haha, well, yeah, I admit I'm not really the bookish type.[n][uf 1 1][e]

[msg MND_021_0_0]
[uf 0 5 65278][uf 2 1]After Yuko headed to the bookstore,[n]I decided to head back to the dorm.[n][uf 1 1][e]

