[msg MSG_000_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]Bom, então a gente se vê por aí. Tenho que ir pra casa estudar.[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]Boa sorte.[e]
[uf 0 5 65278][uf 2 1]Eu queria que você ficasse.[e]

[msg MSG_002_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 1 0][uf 3 1 1 0 0 2 0 0]Hehe, sim. Valeu![n][uf 1 1][e]

[msg MSG_003_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 1 0][uf 3 1 1 0 0 3 0 0]Ah... Você sabe que não dá.[n][uf 1 1][e]

[msg MSG_004_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]Ei, lembra do que eu tinha te falado? Sobre finalmente encontrar meu sonho?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]Eu nunca tive um objetivo de verdade até agora, então admito que estava de bobeira sem fazer nada.[n][uf 1 1][e]

[msg MSG_004_1_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]Pra falar a verdade, minhas notas estão péssimas! Tem sido difícil de recuperar.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]E é por isso que... eu preciso me esforçar mais.[n][uf 1 1][e]

[msg MSG_004_3_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 1 0][uf 3 1 1 0 0 8 0 0]Ugh, eu queria muito, MUITO passar um tempo com você, [uf 4 1]-chan![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 1 0][uf 3 1 1 0 0 9 0 0][uf 4 23 0 1 3 25 25]Eu quero... ficar com você.[n][uf 1 1][e]

[msg MSG_004_5_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 1 0][uf 3 1 1 0 0 10 0 0]E... quero me sentir mais próxima a você.[n][uf 1 1][e]

[msg MSG_004_7_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 11 0 0]Mas eu preciso ter paciência! É isso que eu tenho que colocar na cabeça.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]Eu quero realizar meu sonho com as minhas próprias mãos, e ficar ao seu lado de cabeça erguida.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]Quero que a gente caminhe juntas em direção ao futuro...[n][uf 1 1][e]

[msg MSG_004_9_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]Vai vendo, eu vou ficar ainda mais irresistível até lá.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 15 0 0]Aposto que você vai se apaixonar por mim de novo![n][uf 1 1][e]

[msg MSG_038_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 16 0 0]Tô brincando...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 0 0][uf 3 1 1 0 0 17 0 0][uf 4 23 0 1 3 25 25]Mas é por isso que eu preciso ter paciência agora.[n][uf 1 1][e]

[msg MSG_005_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 18 0 0]Ah, eu sei![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 19 0 0]Não dizem que a comida fica mais gostosa depois que você se esforçou ao máximo numa partida?[n][uf 1 1][e]

[msg MSG_005_3_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 1 0][uf 3 1 1 0 0 20 0 0]Então, é exatamente isso. Se tivermos paciência e formos com calma, então talvez depois...[n][uf 1 1][e]

[msg MSG_005_5_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 2 65535 65535 1 0][uf 3 1 1 0 0 21 0 0]Pera aí, o que você tá me fazendo dizer?![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 1 0][uf 3 1 0 0 0 22 0 0][uf 4 23 0 1 1 25 25]...[n][uf 1 1][e]

[msg MSG_005_7_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 23 0 0]E-Enfim, isso é tudo o que eu tenho a dizer. Até mais. A gente se vê em breve![n][uf 1 1][e]

[msg MSG_006_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 24 0 0]Bom, eu vou indo.[n][uf 1 1][e]

[sel SEL_007_0_0 top]
[uf 0 5 65278][uf 2 1]Vai estudar?[e]
[uf 0 5 65278][uf 2 1]Já vai pra casa?[e]

[msg MSG_008_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 25 0 0]Aham! Tenho feito todos os dias. Eu não sou incrível?[n][uf 1 1][e]

[msg MSG_009_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 26 0 0]Basicamente. Preciso voltar a estudar.[n][uf 1 1][e]

[msg MSG_010_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 27 0 0]Ei, lembra do que eu tinha te falado? Sobre finalmente encontrar meu sonho?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 0 0][uf 3 1 1 0 0 28 0 0][uf 4 23 0 1 3 25 25]Eu nunca tive um objetivo de verdade até agora, então admito que estava de bobeira sem fazer nada.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 29 0 0][uf 4 23 0 1 0 25 25]Pra falar a verdade, minhas notas estão péssimas! Tem sido difícil de recuperar.[n][uf 1 1][e]

[msg MSG_010_3_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 0 0][uf 3 1 1 0 0 30 0 0]Tipo, eu não faço ideia do que são essas matérias de química. Sério mesmo, parece uma língua estrangeira.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 31 0 0][uf 4 23 0 1 0 25 25]É por isso que eu preciso me esforçar.[n][uf 1 1][e]

[msg MSG_010_5_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 32 0 0]Sendo bem sincera, eu queria mesmo era sentar e aproveitar a vida![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 33 0 0]Mas eu preciso ter paciência! É isso que eu tenho que colocar na cabeça.[n][uf 1 1][e]

[msg MSG_010_7_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 34 0 0]Vou lutar pelos meus sonhos com minhas próprias mãos![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 35 0 0]Aí, vou estudar um pouco mais, e depois vou arranjar um emprego.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 36 0 0][uf 4 23 0 1 1 25 25]Mas depois disso, a gente devia sair de novo! Podemos convidar todo mundo da equipe de atletismo também.[n][uf 1 1][e]

[msg MSG_010_9_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 37 0 0]Aaah, que tal fazermos uma festa de bebida, já que seremos adultas![n][uf 1 1][e]

[msg MSG_011_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 38 0 0]Humm... Bom, de qualquer forma![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 39 0 0]Vou me concentrar apenas nos meus estudos por enquanto. Então nem pense em me distrair![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 40 0 0][uf 4 23 0 1 1 25 25]Hoje vou estudar três tópicos ao mesmo tempo. Impressionante, né?[n][uf 1 1][e]

[msg MSG_012_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 41 0 0]Eita, melhor ir logo. Ainda tenho que comprar a janta.[n][uf 1 1][e]

[msg MSG_013_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 42 0 0]Bom, a gente se vê![n][uf 1 1][e]

