[msg MSG_000_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 102 65535 0 0][vp 1 0 4 1 0 0][nl]-kun! Dacci una mano![n][w][e]
[f 2 1][bup 6 4 102 65535 0 0][vp 1 0 4 2 0 0]Junpei-kun non smette di... Ah! Aaah![n][w][e]

[msg MSG_001_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 102 65535 0 0][vp 1 0 4 3 0 0]Eheh! Prendi questo! E questo![n][w][e]
[f 2 1][bup 3 1 102 65535 0 0][vp 1 0 4 4 0 0]Dai, le lotte in acqua sono la base dello stare in spiaggia! Sono divertenti e rinfrescanti![n][w][e]

[msg MSG_002_0_0 [Yukari Takeba]]
[f 2 1][bup 2 2 102 65535 0 0][vp 1 0 4 5 0 0]Ehi, smettila! Stai esagerando! OK, d'accordo! Te la sei cercata![n][w][e]

[msg MSG_003_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 155 65535 0 0][vp 1 0 4 1 0 0]Prima ho visto Yukari-chan e Kirijo-senpai.[n][w][e]
[f 2 1][bup 6 0 155 65535 0 0][vp 1 0 4 2 0 0]Sembrava che si stessero divertendo chiacchierando assieme. Non capita spesso.[n][w][e]

[msg MSG_004_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 155 65535 0 0][vp 1 0 4 1 0 0]Sono felice che Kirijo-senpai sembri sentirsi meglio.[n][w][e]

[msg MND_GENERAL_EVENTPLAY]
[f 2 1]Message issued by the script. [n][f 1 5 0]Comm Event Replay.[n][w][e]

[msg MND_GENERAL_PERSPNA]
[f 2 1]Sento di poter rafforzare il nostro rapporto grazie alla Persona [f 2 4 2], [clr 35][f 2 4 5][clr 27]...[n][w][e]

[msg MND_GENERALSELECTMSG_MAX]
[f 2 1]Sento un legame indissolubile[n]tra me e [f 2 4 0]...[n][w][e]

[msg MND_GENERALMSG_BS_MAX]
[f 2 1]Sento un legame indissolubile[n]tra me e gli anziani...[n][w][e]

[msg MND_GENERALSELECTMSG_RAN]
[f 2 1]Sento che presto potrei avvicinarmi[n]di più a [f 2 4 0]...[n][w][e]

[msg MND_GENERALMSG_BS_RANKUP]
[f 2 1]Sento che presto potrei avvicinarmi[n]di più alla coppia di anziani...[n][w][e]

[msg MND_GENERALSELECTMSG_NOR]
[f 2 1]Non penso che il nostro legame si rafforzerà[n]ancora, anche se passassi del tempo con [f 2 4 0]...[n][w][e]

[msg MND_GENERALMSG_BS_NORMAL [Fuuka Yamagishi]]
[f 2 1]Non penso che il nostro legame si rafforzerà[n]ancora, anche se ci passassi altro tempo insieme...[n][w][e]

[msg MND_GENERALSELECTMSG_MAX_2]
[f 2 1]La nostra relazione non[n]può diventare più intima[n]di così...[n][w][e]
[f 2 1]Dovrei comunque passarci del tempo...?[n][w][e]

[msg MND_GENERAL_MSG_SOLO_AS]
[f 2 1]Dovrei passare del tempo con [f 2 4 0][n]dopo la scuola?[n][w][e]

[msg MND_GENERAL_MSG_SOLO_DT]
[f 2 1]Dovrei passare la giornata con [f 2 4 0]?[n][w][e]

[msg MND__GENERAL_MSG_NET]
[f 2 1]Dovrei giocare al MMORPG con [f 2 4 0]...?[n][w][e]

[msg MND_GENERAL_MSG_SOLO_NT]
[f 2 1]Dovrei passare la serata[n]con [f 2 4 0]?[n][w][e]

[sel SEL_GENERALSELECTMSG_SOL top]
[f 2 1]Passa il tempo con [f 2 4 0][e]
[f 2 1]Vedi Affinità Sociale[e]
[f 2 1]Non importa[e]

[msg MND_GENERAL_MSG_MULTIPLE]
[f 2 1]Dopo la scuola, dovrei trascorrere del tempo a: [f 2 4 1]?[n][w][e]

[msg MND_GENERAL_MSG_FASHION_]
[f 2 1]Dovrei andare al club di moda[n]dopo la scuola?[n][w][e]

[msg MND_GENERAL_MSG_BOOKSTOR]
[f 2 1]Dovrei passare la giornata in libreria...?[n][w][e]

[msg MND_GENERAL_MSG_BOOKSTOR_2]
[f 2 1]Dovrei andare in libreria[n]dopo la scuola?[n][w][e]

[msg MND_GENERAL_MSG_MULTIPLE_2]
[f 2 1]Dovrei passare la notte con [f 2 4 1]...?[n][w][e]

[sel SEL_GENERALSELECTMSG_MUL top]
[f 2 1]Trascorri del tempo: [f 2 4 1][e]
[f 2 1]Vedi Affinità Sociale[e]
[f 2 1]Non importa[e]

[sel SEL_GENERALSELECTMSG_FCL top]
[f 2 1]Vai al club di moda[e]
[f 2 1]Vedi Affinità Sociale[e]
[f 2 1]Non importa[e]

[sel SEL_GENERALSELECTMSG_BS top]
[f 2 1]Entra nella libreria[e]
[f 2 1]Vedi Affinità Sociale[e]
[f 2 1]Non importa[e]

[msg MSG_GENERAL_EXAMREWARD_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4029 0 0]Ah, [nl].[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Ho visto i risultati degli esami. Ottimo lavoro.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Tieni, questo è da parte del presidente.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4108 0 0]È una ricompensa per aver saputo conciliare la scuola e... ehm, le nostre "attività extracurricolari".[n][w][e]

[msg MND_GENERAL_EXAMREWARD_0]
[f 2 1]DEV: UNUSED LABEL[n][w][e]

[msg MND_GENERAL_EXAMREWARD_0_2]
[f 2 1]Dato che ho ottenuto il massimo agli[n]esami, ho anche ricevuto: [f 4 4 1 37 1 3].[n][w][e]

[msg MSG_GENERAL_EXAMREWARD_0_2 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4029 0 0]Ah, [nl].[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Ho visto i risultati degli esami. Ottimo lavoro.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Tieni, questo è da parte del presidente.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4108 0 0]È una ricompensa per aver saputo conciliare la scuola e... ehm, le nostre "attività extracurricolari".[n][w][e]

[msg MSG_GENERAL_EXAMREWARD_0_3 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4077 0 0]Ah, giusto. C'è un'altra cosa...[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Ho visto i risultati degli esami. Ottimo lavoro.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Tieni, questo è da parte del presidente.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4131 0 0]È una ricompensa per aver saputo conciliare la scuola e... ehm, le nostre "attività extracurricolari".[n][w][e]

[msg MND_GENERAL_EXAMREWARD_0_3]
[f 2 1]Dato che ho ottenuto il massimo agli[n]esami, ho anche ricevuto: [f 4 4 1 37 1 3].[n][w][e]

[msg MSG_GENERAL_EXAMREWARD_0_4 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4029 0 0]Ah, [nl].[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Ho visto i risultati degli esami. Ottimo lavoro.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Tieni, questo è da parte del presidente.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4108 0 0]È una ricompensa per aver saputo conciliare la scuola e... ehm, le nostre "attività extracurricolari".[n][w][e]

[msg MND_GENERAL_EXAMREWARD_0_4]
[f 2 1]DEV: UNUSED LABEL[n][w][e]

[msg MSG_GENERAL_EXAMREWARD_0_5 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4029 0 0]Ah, [nl].[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Ho visto i risultati degli esami.[n]Ottimo lavoro.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]È encomiabile come tu continui a eccellere a scuola pur combattendo tante ardue battaglie.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0]Ti ho preso un regalo come riconoscimento del tuo impegno. Ecco, prendi.[n][w][e]

[msg MND_GENERAL_EXAMREWARD_0_5]
[f 2 1]未使用ラベルです。[n][w][e]

[msg MSG_GENERAL_EXAMREWARD_0_6 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 6 65535 0 0][vp 3 0 65535 4029 0 0]Ah, [nl].[n][w][e]
[f 2 1][bup 5 0 6 65535 0 0]Ho visto i risultati degli esami. Ottimo lavoro.[n][w][e]
[f 2 1][bup 5 0 6 65535 0 0]È encomiabile come tu continui a eccellere a scuola pur combattendo tante ardue battaglie.[n][w][e]
[f 2 1][bup 5 0 6 65535 0 0]Ti ho preso un regalo come riconoscimento del tuo impegno. Ecco, prendi.[n][w][e]

[msg MND_GENERAL_EXAMREWARD_1]
[f 2 1]Dato che ho ottenuto il massimo agli[n]esami, ho anche ricevuto: [f 4 4 1 37 1 3].[n][w][e]

[msg MSG_GENERAL_EXAMREWARD_1 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4029 0 0]Ah, [nl].[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Ho visto i risultati degli esami. Ottimo lavoro.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]È encomiabile come tu continui a eccellere a scuola pur combattendo tante ardue battaglie.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4108 0 0]Ti ho preso un regalo come riconoscimento del tuo impegno. Ecco, prendi.[n][w][e]

[msg MND_GENERAL_EXAMREWARD_1_2]
[f 2 1]DEV: UNUSED LABEL[n][w][e]

[msg MND_GENERAL_EXAMREWARD_1_3]
[f 2 1]Dato che ho ottenuto il massimo agli[n]esami, ho anche ricevuto: [f 4 4 1 37 1 3].[n][w][e]

[msg MSG_042_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 155 65535 0 0]Oh, [nf]-chan. Do you want to go to the outdoor hot springs?[n][w][e]

[sel SEL_043_0_0 top]
[f 2 1]Sure, let's go.[e]
[f 2 1]I'll go in a bit.[e]

[msg MSG_044_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 155 65535 0 0]*giggle* I'm looking forward to it.[n][w][e]
[f 2 1][bup 6 0 155 65535 0 0][nf]-chan, you have to go back to your room and get ready first, right?[n][w][e]
[f 2 1][bup 6 0 155 65535 0 0]I'll talk to Kirijo-senpai and Yukari-chan about it while you're doing that.[n][w][e]
[f 2 1][bup 6 0 155 65535 0 0]I'll ask Aigis too, but... Is it all right for her to take a bath?[n][w][e]

[msg MSG_045_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 155 65535 0 0]You're not going to go yet?[n][w][e]
[f 2 1][bup 6 0 155 65535 0 0]Okay. Let me know when you're ready to go.[n][w][e]

[msg MSG_046_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 155 65535 0 0]*giggle* I'm looking forward to it.[n][w][e]

