[msg MSG_000_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 51 65535 0 0][uf 3 1 1 0 0 1 0 0]¡Ya estamos aquí![n][uf 1 1][e]

[msg MSG_001_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 51 65535 0 0][uf 3 1 1 0 0 2 0 0]¡¿Dónde está?! ¡Se va a enterar![n][uf 1 1][e]

[msg MSG_002_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 65535 0 0][uf 3 1 1 0 0 3 0 0]Hemos detectado una sombra fuera de la torre Tártaro.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 65535 0 0][uf 3 1 1 0 0 4 0 0]No estamos seguros, pero creemos que se trata de otra de las grandes, como la del mes pasado.[n][uf 1 1][e]

[msg MSG_003_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 65535 0 0][uf 3 1 1 0 0 5 0 0]Hay que derrotar a todas las que encontremos, y rápido.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 65535 0 0][uf 3 1 1 0 0 6 0 0]La gente no es consciente de la existencia de la Hora Oscura, pero, si se destruye la ciudad en ese momento, habrá muchas incoherencias.[n][uf 1 1][e]

[msg MSG_004_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 51 65535 0 0][uf 3 1 1 0 0 7 0 0]Vamos, que tenemos que repartir hostias, ¿no? ¡Me apunto![n][uf 1 1][e]

[msg MSG_005_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 51 65535 0 0][uf 3 1 1 0 0 8 0 0]Junpei...[n][uf 1 1][e]

[msg MSG_006_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 65535 0 0][uf 3 1 1 0 0 9 0 0]Akihiko, tú quédate aquí y espera al director.[n][uf 1 1][e]

[msg MSG_006_5_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 17 4 2 0][e]

[msg MSG_007_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 51 65535 0 0][uf 3 1 1 0 0 10 0 0]¡¿Qué?! ¡Ni muerto! ¡Yo voy![n][uf 1 1][e]

[msg MSG_008_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 65535 0 0][uf 3 1 1 0 0 11 0 0]Necesitas tiempo para recuperarte. Así lo único que harías sería estorbar.[n][uf 1 1][e]

[msg MSG_009_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 51 65535 0 0][uf 3 1 1 0 0 12 0 0]¡¿Qué has dicho?![n][uf 1 1][e]

[msg MSG_010_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 65535 0 0][uf 3 1 1 0 0 13 0 0]Teniendo en cuenta tu estado actual, les irá mejor sin ti.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 65535 0 0][uf 3 1 1 0 0 14 0 0]Confía en ellos, Akihiko. Ya han vivido combates en primera persona.[n][uf 1 1][e]

[msg MSG_011_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 51 65535 0 0][uf 3 1 0 0 0 15 0 0]...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 3 51 65535 0 0][uf 3 1 1 0 0 16 0 0][uf 4 23 0 4 3 25 25]Mierda.[n][uf 1 1][e]

[msg MSG_012_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 51 65535 0 0][uf 3 1 1 0 0 17 0 0]¡Tranqui! ¡Lo tengo todo controlado![n][uf 1 1][e]

[msg MSG_013_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 3 51 65535 0 0][uf 3 1 1 0 0 18 0 0]Supongo que no me queda otra.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 51 65535 0 0][uf 3 1 1 0 0 19 0 0][uf 4 23 0 4 0 25 25][uf 4 1], te dejo al mando.[n][uf 1 1][e]

[msg MSG_014_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 51 65535 0 0][uf 3 1 1 0 0 20 0 0]¿Otra vez ella?[n][uf 1 1][e]

[msg MSG_015_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 65535 0 0][uf 3 1 1 0 0 21 0 0]¿Puedes encargarte?[n][uf 1 1][e]

[sel SEL_016_0_0 top]
[uf 0 5 65278][uf 2 1]Os ayudaré en lo que pueda.[e]
[uf 0 5 65278][uf 2 1]No puedo...[e]
[uf 0 5 65278][uf 2 1]¿Por qué yo?[e]

[msg MSG_017_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 51 65535 0 0][uf 3 1 1 0 0 22 0 0]Bien. Contamos contigo.[n][uf 1 1][e]

[msg MSG_018_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 51 65535 0 0][uf 3 1 1 0 0 23 0 0]Claro que puedes. Hasta ahora lo has hecho bien, ¿no?[n][uf 1 1][e]

[msg MSG_019_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 51 65535 0 0][uf 3 1 1 0 0 24 0 0]¿Y qué más da? Te han elegido a ti, ¿no?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 51 65535 0 0][uf 3 1 1 0 0 25 0 0]Como siempre.[n][uf 1 1][e]

[msg MSG_020_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 51 65535 0 0][uf 3 1 1 0 0 26 0 0]A este paso, acabarás siendo la líder de por vida.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 51 65535 0 0][uf 3 1 1 0 0 27 0 0]Bueno, que a mí me da igual, la verdad.[n][uf 1 1][e]

[msg MSG_021_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 51 65535 0 0][uf 3 1 1 0 0 28 0 0]Los tres deberían ir primero. Tienes que prepararte, ¿no?[n][uf 1 1][e]

[msg MSG_022_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 65535 0 0][uf 3 1 1 0 0 29 0 0]En efecto. Nos vemos enfrente de la estación.[n][uf 1 1][e]

[msg MSG_023_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 51 65535 0 0][uf 3 1 1 0 0 30 0 0]Entendido.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 51 65535 0 0][uf 3 1 1 0 0 31 0 0][uf 4 23 0 2 2 25 25]Muy bien, ¡vamos![n][uf 1 1][e]

