[msg MSG_000_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 2 65535 0 0][uf 3 1 1 0 0 1 0 0]Everyone's okay with the special, right?[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]Yep, sounds good!.[e]
[uf 0 5 65278][uf 2 1]I'm fine with whatever.[e]
[uf 0 5 65278][uf 2 1]I'll take the regular.[e]

[msg MSG_002_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 2 65535 0 0][uf 3 1 1 0 0 2 0 0]Okay, five specials, please![n][uf 1 1][e]

[msg MSG_003_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 2 65535 0 0][uf 3 1 1 0 0 3 0 0]Okay, four specials and one regular, please![n][uf 1 1][e]

[msg MSG_004_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 2 65535 0 0][uf 3 1 1 0 0 4 0 0]Man, this is awesome![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 2 65535 0 0][uf 3 1 1 0 0 5 0 0]Sanada-san's NEVER treated us all to ramen before.[n][uf 1 1][e]

[msg MSG_005_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 3 2 65535 0 0][uf 3 1 1 0 0 6 0 0]I'll accept that I lost, but why do I have to treat all of you?[n][uf 1 1][e]

[msg MSG_006_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 2 65535 0 0][uf 3 1 1 0 0 7 0 0]You're still goin' on about that?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 2 65535 0 0][uf 3 1 1 0 0 8 0 0][uf 4 23 0 3 1 25 25]C'mon, Sanada-san, a bet's a bet. Ya gotta pay up![n][uf 1 1][e]

[msg MSG_007_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 3 2 65535 0 0][uf 3 1 1 0 0 9 0 0]All right, all right! I never said I wouldn't.[n][uf 1 1][e]

[msg MSG_008_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 0 0 0 10 0 0]......[n][uf 1 1][e]

[msg MSG_009_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 3 2 65535 0 0][uf 3 1 1 0 0 11 0 0]What's wrong, Aigis? You doubting me, too...?[n][uf 1 1][e]

[msg MSG_010_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 12 0 0]No, but...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 13 0 0]Have you seen the magazine on the counter? The headline caught my attention.[n][uf 1 1][e]

[msg MSG_011_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 2 65535 0 0][uf 3 1 1 0 0 14 0 0]What magazine?[n][uf 1 1][e]

[msg MSG_012_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 15 0 0]This one...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 16 0 0]"Emergence of a Messiah: The Charismatic One Speaks."[n][uf 1 1][e]

[msg MSG_013_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 2 65535 0 0][uf 3 1 1 0 0 17 0 0]Oh, it must be about that doomsday cult. They're all over the Internet, too.[n][uf 1 1][e]

[msg MSG_014_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 2 65535 0 0][uf 3 1 1 0 0 18 0 0]Huh...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 2 65535 0 0][uf 3 1 0 0 0 19 0 0]...?[n][uf 1 1][e]

[msg MSG_014_3_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 17 4 4 0][e]

[msg MSG_014_5_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 4 2 65535 0 0][uf 3 1 1 0 0 20 0 0]Hey, look at this photo! Check out their so-called "Messiah"...[n][uf 1 1][e]

[msg MSG_015_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 2 65535 0 0][uf 3 1 1 0 0 21 0 0]Wh-What the—!?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 2 65535 0 0][uf 3 1 1 0 0 22 0 0]Is that... Takaya!?[n][uf 1 1][e]

[msg MSG_016_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 2 65535 0 0][uf 3 1 1 0 0 23 0 0]I thought something was up. So, it's Strega, after all...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 2 65535 0 0][uf 3 1 1 0 0 24 0 0]I just lost my appetite.[n][uf 1 1][e]

[msg MSG_017_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 25 0 0]Listen...[n][uf 1 1][e]

[msg MSG_018_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 26 0 0]"Mankind is currently imprisoned by the sins of hate and anger."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 27 0 0]"But soon, a savior will descend upon this world to break the chains that bind us, and lift us to new heights."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 28 0 0]"This great being is known as Nyx. I have beheld her glory, and she has blessed me with power beyond belief."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 29 0 0]"When Nyx arrives... there will be no more pain, no more suffering. Humanity shall be freed..."[n][uf 1 1][e]

[msg MSG_019_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 2 65535 0 0][uf 3 1 1 0 0 30 0 0]How the hell does he know about Nyx!?[n][uf 1 1][e]

[msg MSG_020_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 2 65535 0 0][uf 3 1 1 0 0 31 0 0]Wait, he's saying that Nyx will save the world!? But that's a lie![n][uf 1 1][e]

[msg MSG_021_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 2 65535 0 0][uf 3 1 1 0 0 32 0 0]I don't think that even matters. This is all just a game to him.[n][uf 1 1][e]

[msg MSG_022_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 2 2 65535 0 0][uf 3 1 1 0 0 33 0 0]That bastard...[n][uf 1 1][e]

[msg MSG_023_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 34 0 0]"But there are those who do not understand the truth even though they have also been granted her blessing."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 35 0 0]"They have acquired the same power as I, yet they abuse it for their own personal gain."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 36 0 0]"These miscreants are the ones to blame for the recent tragedies that have been plaguing our streets."[n][uf 1 1][e]

[msg MSG_024_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 2 65535 0 0][uf 3 1 1 0 0 37 0 0]Wait, is he talking about us!?[n][uf 1 1][e]

[sel SEL_025_0_0 top]
[uf 0 5 65278][uf 2 1]That's a lie!.[e]
[uf 0 5 65278][uf 2 1]You're too loud.[e]

[msg MSG_026_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 2 65535 0 0][uf 3 1 1 0 0 38 0 0]Shhh! Not so loud! We're not the only ones here, you know![n][uf 1 1][e]

[msg MSG_027_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 2 2 65535 0 0][uf 3 1 1 0 0 39 0 0]R-Right, right, sorry... But can you blame me...?[n][uf 1 1][e]

[msg MSG_028_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 2 2 65535 0 0][uf 3 1 1 0 0 40 0 0]And what do they mean by "the charismatic one"?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 2 2 65535 0 0][uf 3 1 1 0 0 41 0 0]Why's he suddenly a celebrity?[n][uf 1 1][e]

[msg MSG_029_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 2 65535 0 0][uf 3 1 1 0 0 42 0 0]Well, apparently Jin was already pretty well-known on the Internet...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 2 65535 0 0][uf 3 1 1 0 0 43 0 0]He's probably good at influencing public perception.[n][uf 1 1][e]

[msg MSG_030_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 2 65535 0 0][uf 3 1 1 0 0 44 0 0]Yeah, I bet he orchestrated Takaya's rise to fame by building his brand like a celeb...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 2 65535 0 0][uf 3 1 1 0 0 45 0 0]Ugh, those two make me sick...[n][uf 1 1][e]

[msg MSG_031_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 46 0 0]"Brothers and sisters, I shall go forth to make preparations for Nyx's arrival..."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 47 0 0]"But do not fear those evildoers who desecrate their gifts. Nyx shall right their wrongs."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 48 0 0]"May your hearts be filled with peace as you await your salvation."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 49 0 0]"Blessed are those who take joy in the coming of Nyx."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 50 0 0]"The revolution is upon us, my brethren!"[n][uf 1 1][e]

[msg MSG_032_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 2 65535 0 0][uf 3 1 1 0 0 51 0 0]"Revolution"? People can't seriously be buying this crap, can they?[n][uf 1 1][e]

[msg MSG_033_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 52 0 0]"Perhaps the power of an exceptionally charismatic individual is the only way to change this nebulous future..."[n][uf 1 1][e]

[msg MSG_034_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 53 0 0]...That's the end of the article.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 54 0 0]It appears Strega disappeared again after the interview.[n][uf 1 1][e]

[msg MSG_035_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 2 65535 0 0][uf 3 1 1 0 0 55 0 0]Well, there's only one place they could've gone—Tartarus.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 2 65535 0 0][uf 3 1 1 0 0 56 0 0]Hmph... They're just wasting everyone's time.[n][uf 1 1][e]

[msg MSG_036_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 2 65535 0 0][uf 3 1 1 0 0 57 0 0]Still, it seems they've managed to shift the atmosphere of the entire city.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 2 65535 0 0][uf 3 1 1 0 0 58 0 0]Even if they don't say it out loud, people must be scared inside...[n][uf 1 1][e]

[msg MSG_037_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 2 65535 0 0][uf 3 1 1 0 0 59 0 0]Yeah, they probably are.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 2 65535 0 0][uf 3 1 1 0 0 60 0 0]Why else would anyone believe this nonsense? It's not normal.[n][uf 1 1][e]

[msg MSG_038_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 2 65535 0 0][uf 3 1 1 0 0 61 0 0]Believing what you hear is a choice. There's no real way for them to know what's true.[n][uf 1 1][e]

[msg MSG_039_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 10 2 65535 0 0][uf 3 1 1 0 0 62 0 0]Well, no wonder it feels like the world's ending... We're all gonna die.[n][uf 1 1][e]

[msg MSG_040_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 63 0 0]But is that so unusual?[n][uf 1 1][e]

[msg MSG_041_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 64 0 0]All life will eventually come to an end. Does Nyx's involvement change that in some way?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 65 0 0]Death is a natural occurrence in the cycle of life. Don't all humans realize this?[n][uf 1 1][e]

[sel SEL_042_0_0 top]
[uf 0 5 65278][uf 2 1]They're not ready to die.[e]
[uf 0 5 65278][uf 2 1]Dying is a scary thought.[e]
[uf 0 5 65278][uf 2 1]They want an escape.[e]

[msg MSG_043_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 2 65535 0 0][uf 3 1 1 0 0 66 0 0]I guess...[n][uf 1 1][e]

[msg MSG_044_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 2 65535 0 0][uf 3 1 1 0 0 67 0 0]To tell you the truth, I never even woulda thought about my own death if none of this happened.[n][uf 1 1][e]

[msg MSG_045_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 2 65535 0 0][uf 3 1 1 0 0 68 0 0]But we're already here, so why don't we just leave it at that?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 9 2 65535 0 0][uf 3 1 1 0 0 69 0 0][uf 4 23 0 3 9 25 25]Our target is Nyx. If Strega gets in our way, we'll deal with them, too. That's all there is to it.[n][uf 1 1][e]

[msg MSG_046_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 2 65535 0 0][uf 3 1 1 0 0 70 0 0]Agreed.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 2 65535 0 0][uf 3 1 1 0 0 71 0 0]We'll probably run into them in Tartarus, anyway...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 2 65535 0 0][uf 3 1 1 0 0 72 0 0]No matter how you look at it, they want us out of the picture.[n][uf 1 1][e]

[msg MSG_047_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 2 65535 0 0][uf 3 1 1 0 0 73 0 0]The Promised Day's almost here, huh...[n][uf 1 1][e]

[msg MSG_048_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 10 2 65535 0 0][uf 3 1 1 0 0 74 0 0]Yeah...[n][uf 1 1][e]

[msg MSG_049_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 2 65535 0 0][uf 3 1 1 0 0 75 0 0]We need to do all we can until then.[n][uf 1 1][e]

[msg MSG_050_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 2 65535 0 0][uf 3 1 1 0 0 76 0 0]Alright... Then first things first, we're gonna need lots of energy! Let's eat![n][uf 1 1][e]

[msg MSG_051_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 2 65535 0 0][uf 3 1 1 0 0 77 0 0]Excuse me! I'll add a Hagakure Bowl to the list![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 2 65535 0 0][uf 3 1 1 0 0 78 0 0]You don't mind, right, Sanada-san?[n][uf 1 1][e]

[msg MSG_052_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 2 65535 0 0][uf 3 1 1 0 0 79 0 0]Whoa, Junpei, didn't you say you were eating half of Aigis's food too?[n][uf 1 1][e]

[msg MSG_053_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 2 65535 0 0][uf 3 1 1 0 0 80 0 0]Oh, don't worry. I'm starving.[n][uf 1 1][e]

[msg MSG_054_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 6 2 65535 0 0][uf 3 1 1 0 0 81 0 0]...You better eat it all.[n][uf 1 1][e]

