[msg MSG_000_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0][uf 3 1 3 0 65535 10047 0 0]Hey, sorry to ask you to hang out all of a sudden.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0]The rest of my family's out today. Kinda didn't want to eat all by my lonesome, y'know?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0]That's when I remembered you eating ramen like it was your favorite thing ever! Great minds, yo.[n][uf 1 1][e]

[msg MSG_001_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0]I don't trust people that don't enjoy their food.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0]I mean, it's one thing if the food's really nasty.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 1 65535 65535 0 0][uf 4 23 0 101 1 25 25]Then there's those guys that pretend it's good even if they don't like it. Can't trust them either.[n][uf 1 1][e]

[msg MSG_002_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0][uf 3 1 3 0 65535 10061 0 0]By the way, are you picky about your food?[n][uf 1 1][e]

[sel SEL_003_0_0 top]
[uf 0 5 65278][uf 2 1]I'm pretty picky.[e]
[uf 0 5 65278][uf 2 1]Not at all.[e]
[uf 0 5 65278][uf 2 1]I refuse to eat certain things.[e]

[msg MSG_004_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 1 65535 65535 0 0][uf 3 1 3 0 65535 10021 0 0][uf 5 13 2 30 101]Heh, me too.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 1 65535 65535 0 0]I just can't stomach probably like half the food in the world. I don't even consider them edible.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 1 65535 65535 0 0]Oh, but if a gorgeous girl was the one cooking, I might be able to. That's different, y'know?[n][uf 1 1][e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]Tomochika seems to sympathize with me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like we became a lot closer today.[n][uf 1 1][e]

[msg MSG_006_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0][uf 3 1 3 0 65535 10042 0 0]Yikes, you serious? You must be overly forgiving...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0]I just can't stand some stuff, personally.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0]Like vegetables. They're pretty much just leaves. I'm not a bug, ya know...[n][uf 1 1][e]

[msg MND_007_0_0]
[uf 0 5 65278][uf 2 1]Tomochika sighs.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like we didn't get any closer today...[n][uf 1 1][e]

[msg MSG_008_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 1 65535 65535 0 0][uf 3 1 3 0 65535 10024 0 0][uf 5 13 2 15 101]Oh, I totally hear ya! There are just some things that make you wanna scream, "This ain't food!"[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0][uf 4 23 0 101 0 25 25]I mean, mushrooms are just fungus, right? Seafood's kinda pushin' the limits too...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0]And I hate stuff like ginger and beefsteak plants. Why in the world would you eat roots and leaves?[n][uf 1 1][e]

[msg MND_009_0_0]
[uf 0 5 65278][uf 2 1]Tomochika seems to sympathize with me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I learned a little more about him today.[n][uf 1 1][e]

[msg MSG_010_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 1 65535 65535 0 0][uf 3 1 3 0 65535 10067 0 0]Well, now I know what your taste in food is like. Next up: what type of girl do you like?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 1 65535 65535 0 0]You into the cute type or the sexy model type? Long hair or short?[n][uf 1 1][e]

[msg MND_011_0_0]
[uf 0 5 65278][uf 2 1]After Tomochika's interrogation,[n]I decided to return to the dorm.[n][uf 1 1][e]

