[msg MSG_000_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 1 65535 0 0][uf 3 1 1 0 0 1 0 0]Oh, there she is.[n][uf 1 1][e]

[msg MSG_001_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 1 65535 0 0][uf 3 1 1 0 0 2 0 0]Whew, that does it for our first day back...[n][uf 1 1][e]

[msg MSG_002_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 1 65535 0 0][uf 3 1 1 0 0 3 0 0]Well, you two have perfect timing.[n][uf 1 1][e]

[msg MSG_003_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 1 65535 0 0][uf 3 1 1 0 0 4 0 0]Perfect timing? For what?[n][uf 1 1][e]

[msg MSG_004_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 1 65535 0 0][uf 3 1 1 0 0 5 0 0]Hey, Fuuka, is Aigis ready?[n][uf 1 1][e]

[msg MSG_005_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 1 65535 0 0][uf 3 1 1 0 0 6 0 0]Um, what do you think?[n][uf 1 1][e]

[msg MSG_006_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 7 0 0]This is how I look now.[n][uf 1 1][e]

[msg MSG_007_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 1 65535 0 0][uf 3 1 1 0 0 8 0 0]Huh...? Why's she wearin' a school uniform!? What's going on here?[n][uf 1 1][e]

[msg MSG_008_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 1 65535 0 0][uf 3 1 1 0 0 9 0 0]She said she wanted to go to school with us, so I told the others as a joke...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 1 65535 0 0][uf 3 1 1 0 0 10 0 0]But the chairman actually agreed, so now she's gonna start as a second-year tomorrow...[n][uf 1 1][e]

[msg MSG_009_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 1 65535 0 0][uf 3 1 1 0 0 11 0 0]Seriously!? He's down with that?[n][uf 1 1][e]

[msg MSG_010_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 1 65535 0 0][uf 3 1 1 0 0 12 0 0]He said something about studying her behavior in a social environment...[n][uf 1 1][e]

[sel SEL_011_0_0 top]
[uf 0 5 65278][uf 2 1]Uhm... Is this really alright?[e]
[uf 0 5 65278][uf 2 1]That's hardly the problem here.[e]

[msg MSG_012_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 1 65535 0 0][uf 3 1 1 0 0 13 0 0]Well, if he's cool with it, then I guess it's alright...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 1 65535 0 0][uf 3 1 1 0 0 14 0 0][uf 4 23 0 3 1 25 25]Besides, I'd say it looks pretty good on her. Maybe even... cute?[n][uf 1 1][e]

[msg MSG_013_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 15 0 0]The school camouflage that Fuuka-san provided is more than appropriate.[n][uf 1 1][e]

[msg MSG_014_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 1 65535 0 0][uf 3 1 1 0 0 16 0 0]It looks very natural on you. No one will suspect a thing.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 1 65535 0 0][uf 3 1 1 0 0 17 0 0][uf 4 23 0 8 3 25 25]But, why do you want to go to school? It's not like it's interesting.[n][uf 1 1][e]

[msg MSG_015_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 18 0 0]As the second semester commences, I intend to synchronize my schedule with everyone for maximum efficiency.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 19 0 0]If I remain here on standby, it could affect our deployment efficiency.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 20 0 0]To accommodate, I requested reassignment alongside our squad leader.[n][uf 1 1][e]

[msg MSG_016_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 1 65535 0 0][uf 3 1 1 0 0 21 0 0]Deployment efficiency, huh... Why do I feel like you being at school would make that even worse?[n][uf 1 1][e]

[msg MSG_017_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 22 0 0]I will make any necessary adaptations as the situation evolves.[n][uf 1 1][e]

[msg MSG_018_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 1 65535 0 0][uf 3 1 1 0 0 23 0 0]Uhh, sure, you do that.[n][uf 1 1][e]

[msg MSG_019_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 1 0 0 24 0 0]Arf! Arf![n][uf 1 1][e]

[msg MSG_020_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 25 0 0]He says, "I want to go to school, too."[n][uf 1 1][e]

[msg MSG_021_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 1 65535 0 0][uf 3 1 1 0 0 26 0 0]Koromaru... No, you definitely have to stay here, okay?[n][uf 1 1][e]

[msg MSG_022_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 3 65535 65535 0 0][uf 3 1 1 0 0 27 0 0]*whine*[n][uf 1 1][e]

