[msg MSG_DUNGE_YUKARI_KAGAMI2 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 3 0 65535 1117 0 0]I knew it! Now we should be able to get to the Shadow, right?[n][uf 1 1][e]

[msg MSG_DUNGE_FUKA_KAGAMI2F_ [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0][uf 3 1 3 0 65535 5089 0 0]Huh!?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0]Actually, the seal's still intact! But that should've...[n][uf 1 1][e]

[msg MSG_DUNGE_MITSURU_KAGAMI [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Don't panic. Can you pick up any similar signals?[n][uf 1 1][e]

[msg MSG_DUNGE_SANADA_KAGAMI2 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Yeah, there must be something we're missing...[n][uf 1 1][e]

[msg MSG_DUNGE_FUKA_KAGAMI2F__2 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 4 25 6]Let me see...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0][uf 3 1 3 0 65535 5073 0 0]Got it! I'm getting a signal from a mirror on the third floor![n][uf 1 1][e]

[msg MSG_DUNGE_YUKARI_KAGAMI2_2 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]Then we just have to break that one too, right? Fuuka, can you tell which room it's in?[n][uf 1 1][e]

[msg MSG_DUNGE_FUKA_KAGAMI2F__3 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0]Sorry, I can't pinpoint the exact location. There's too much interference from the main signal...[n][uf 1 1][e]

[msg MSG_DUNGE_YUKARI_KAGAMI2_3 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]I guess we'll just have to go and find another mirror that doesn't show our reflection.[n][uf 1 1][e]

[msg MSG_DUNGE_FUKA_KAGAMI2F__4 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]It should be inside one of the rooms on the third floor! Good luck![n][uf 1 1][e]

[msg MSG_DUNGE_FUKA_KAGAMIHIN [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 50 0 0][uf 3 1 3 0 65535 5088 0 0]I'm not getting a signal from that mirror anymore. It looks like that did it![n][uf 1 1][e]

[msg MSG_DUNGE_FUKA_TOPPA_1 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 50 0 0][uf 3 1 3 0 65535 5088 0 0]The main signal is completely gone! The seal should be broken now![n][uf 1 1][e]

[msg MSG_DUNGE_MITSURU_TOPPA_ [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4085 0 0]Excellent! Then the target's room should be accessible now.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Still, we're behind schedule. Let's move![n][uf 1 1][e]

[msg MSG_DUNGE_SANADA_TOPPA_G [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3115 0 0]It's about time. Now we can finally meet the enemy face-to-face.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Let's be sure to repay the favor for all the trouble it's put us through.[n][uf 1 1][e]

[msg MSG_DNG_MIRROR_BREAK_YUK [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]Come on! Let's get this over with![n][uf 1 1][e]

[msg MSG_DNG_MIRROR_BREAK_JUN [Junpei Iori]]
[uf 0 5 65278][uf 2 1]Damn... Yuka-tan's lookin' pretty fired up.[n][uf 1 1][e]

[msg MSG_DNG_MIRROR_BREAK_SAN [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1]I say she's got the right idea. My fists are aching for some action, too.[n][uf 1 1][e]

[msg MSG_DNG_MIRROR_BREAK_MIT [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1]I get how you feel, but keep it together. We can't afford to lose focus against an enemy like this.[n][uf 1 1][e]

[msg MND_DUNGE_KAGAMI_NOMAL]
[uf 0 5 65278][uf 2 1]This mirror is pretty large...[n][uf 1 1][e]

[msg MSG_DUNGE_HIERO_HIT0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0][uf 3 1 3 0 65535 1062 0 0]Hm... A mirror this big would be convenient, but I'm not so sure about this design...[n][uf 1 1][e]

[msg MSG_DUNGE_IIDESUKA [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 3 0 65535 5006 0 0]I sense a large presence behind that door![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Are you ready?[n][uf 1 1][e]

[msg MSG_DUNGE_KOWASANA_AKAND [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 3 0 65535 5076 0 0]There's a powerful seal on that door![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0]You'll have to break the seal before you can fight the Shadow.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0]We'll be in big trouble if the Dark Hour ends before you defeat it. Please hurry![n][uf 1 1][e]

[msg MSG_DUNGE_HIERO_HIT11 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0][uf 3 1 3 0 65535 1001 0 0]Why can't this just be over already? I wanna go home and take a shower...[n][uf 1 1][e]

[msg MSG_DUNGE_HIERO_HIT12 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 65535 65535 0 0][uf 3 1 3 0 65535 3091 0 0]No dice, huh? Dammit, where could it be...?[n][uf 1 1][e]

[msg MSG_DUNGE_HIERO_HIT13 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4121 0 0]It doesn't seem like it's in there... Let's keep looking.[n][uf 1 1][e]

[msg MSG_DUNGE_HIERO_HIT21 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 65535 65535 0 0][uf 3 1 3 0 65535 1142 0 0]It's completely see-through... Why would they design it like this?[n][uf 1 1][e]

[msg MSG_DUNGE_HIERO_HIT22 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 65535 65535 0 0][uf 3 1 3 0 65535 1022 0 0]It's kinda creepy that it's see-through, but I guess that's easier for us... Looks like nothing's there.[n][uf 1 1][e]

[msg MSG_DUNGE_HIERO_HIT23 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4092 0 0]Hm, I'm not seeing anything... We'll just have to turn every stone.[n][uf 1 1][e]

[msg MSG_DUNGE_HIERO_HIT31 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 65535 65535 0 0][uf 3 1 3 0 65535 1110 0 0]Sheesh, even the bathroom door's way over the top. I bet it's the same inside too, huh...?[n][uf 1 1][e]

[msg MSG_DUNGE_HIERO_HIT32 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0][uf 3 1 3 0 65535 1062 0 0]Think it could be inside? There aren't really any places it could hide in there, though...[n][uf 1 1][e]

[msg MSG_DUNGE_HIERO_HIT41 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1107 0 0]Everything in this room is so fancy. Even the TV looks like it's top of the line.[n][uf 1 1][e]

[msg MSG_DUNGE_HIERO_HIT42 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 65535 65535 0 0][uf 3 1 3 0 65535 2073 0 0]What if there was a Shadow in the TV!? Yeah, right, like that would ever happen...[n][uf 1 1][e]

[msg MSG_DUNGE_HIERO_HIT51 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 65535 65535 0 0][uf 3 1 3 0 65535 1143 0 0]It's all such poor taste... Seriously, who'd want to sleep in place like this?[n][uf 1 1][e]

[msg MSG_DUNGE_HIERO_HIT52 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3091 0 0]Not here, huh? I'd like to put an end to this already...[n][uf 1 1][e]

[msg MSG_DUNGE_HIERO_HIT61 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 65535 65535 0 0][uf 3 1 3 0 65535 1114 0 0]They really committed to this theme, didn't they? Getting a little repetitive, don'tcha think?[n][uf 1 1][e]

[msg MSG_DUNGE_HIERO_HIT62 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4060 0 0]Nothing... We'll just have to keep checking everything.[n][uf 1 1][e]

[msg MSG_DUNGE_HIERO_HIT72 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 3 0 65535 2133 0 0]If it was actually in here the whole time, we'd have one ice-cold Shadow-sicle on our hands.[n][uf 1 1][e]

[msg MSG_DUNGE_HIERO_HIT73 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3122 0 0]Nothing here... Where else haven't we looked?[n][uf 1 1][e]

[msg MSG_DUNGE_HIERO_HIT8]
[uf 0 5 65278][uf 2 1]DEV: Hierophant's Chamber HIT 8: Backup[n][uf 1 1][e]

[msg MND_DUNGE_KAGAMI_SIRABER]
[uf 0 5 65278][uf 2 1]What should I do with this mirror...?[n][uf 1 1][e]

[sel SEL_MIRROR top]
[uf 0 5 65278][uf 2 1]Break it[e]
[uf 0 5 65278][uf 2 1]Don't break it[e]

[msg MND_DUNGE_KAGAMI_MATIGAI]
[uf 0 5 65278][uf 2 1]My mind is starting to feel fuzzy...[n][uf 1 1][e]

[msg MND_DUNGE_KAGAMI_HAKAIZU]
[uf 0 5 65278][uf 2 1]It looks like I already broke this mirror.[n][uf 1 1][e]

[msg MND_DUNGE_KAGAMI_HAKAIZU_2]
[uf 0 5 65278][uf 2 1]This mirror is broken.[n][uf 1 1][e]

[msg MSG_DUNGE_BOSS_ALL_IRU2 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 3 0 65535 5006 0 0]The Shadow is waiting behind this door![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Are you ready?[n][uf 1 1][e]

[sel SEL_BATTLE top]
[uf 0 5 65278][uf 2 1]I'm ready.[e]
[uf 0 5 65278][uf 2 1]Not yet.[e]

[msg MND_DUNGE_HOUOU_DOOR_HAZ]
[uf 0 5 65278][uf 2 1]The door won't budge.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]A strong force seems to be holding it shut.[n][uf 1 1][e]

[msg MSG_DUNGE_HOUOU_FUKA_1 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0]...![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0]What...!?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]I still sense a Shadow in that room![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]It's different from the one you just defeated![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0]But where is it? Is it hiding...?[n][uf 1 1][e]

[msg MSG_DUNGE_HOUOU_FUKA_2 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 3 0 65535 5006 0 0]I still sense a Shadow in that room![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]It must be hiding... Try to see if you can find it![n][uf 1 1][e]

[msg MSG_DUNGE_KAGAMI_YUKARI [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 65535 65535 0 0][uf 3 1 3 0 65535 1137 0 0]Hm...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 65535 65535 0 0]Hey... Is it just me, or is there something weird about this mirror?[n][uf 1 1][e]

[msg MND_BOSSROOM_OBJECT]
[uf 0 5 65278][uf 2 1]Nothing about this seems[n]terribly out of the ordinary.[n][uf 1 1][e]

[msg MND_DUNGE_HOUOUNOMA_TOIR]
[uf 0 5 65278][uf 2 1]Looks like a bathroom.[n][uf 1 1][e]

[msg MND_DUNGE_HOUOUNOMA_BED]
[uf 0 5 65278][uf 2 1]It's quite a large bed.[n][uf 1 1][e]

[msg MND_DUNGE_GARASU_MAE]
[uf 0 5 65278][uf 2 1]I can see the bathroom through the window.[n][uf 1 1][e]

[msg MSG_DUNGE_GARASU_ATO [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 65535 65535 0 0][uf 3 1 3 0 65535 1091 0 0]Hey! What are you staring at that for?[n][uf 1 1][e]

[msg MND_DUNGE_SYAWASITU_MAE]
[uf 0 5 65278][uf 2 1]The scent of soap is still[n]lingering from the bathroom.[n][uf 1 1][e]

[msg MSG_DUNGE_SYAWASITU_ATO [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 65535 65535 0 0][uf 3 1 3 0 65535 1076 0 0]What're you— There's no reason for us to be here! Let's go![n][uf 1 1][e]

[msg MND_DUNGE_SYAWASITU_PTAL]
[uf 0 5 65278][uf 2 1]Yukari doesn't look very happy...[n][uf 1 1][e]

[msg MND_DUNGE_SYAWASITU_REPE]
[uf 0 5 65278][uf 2 1]Yukari is giving me an icy glare...[n][uf 1 1][e]

[msg MSG_DUNGE_SYAWASITU_ATO1 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0][uf 3 1 3 0 65535 1110 0 0]Ugh... It's getting to the point where just being back here is giving me a headache...[n][uf 1 1][e]

[msg MSG_DUNGE_AORI_JYUNPEI1 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0]"Back here"? Oooh... Did something... steamy happen while we were separated?[n][uf 1 1][e]

[msg MSG_DUNGE_SYAWASITU_ATO2 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]...You know, I pretty much already knew, but...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 65535 65535 0 0]Your mind just lives in the gutter, doesn't it?[n][uf 1 1][e]

[msg MSG_DUNGE_AORI_JYUNPEI2 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 65535 65535 0 0][uf 3 1 3 0 65535 2053 0 0]Er... Sorry, ma'am...[n][uf 1 1][e]

[msg MSG_DUNGE_AORI_SANADA1 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3103 0 0]Hm? This bathroom seems recently used... But in the Dark Hour...? Who—[n][uf 1 1][e]

[msg MSG_DUNGE_SYAWASITU_ATO3 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 65535 65535 0 0]It doesn't matter! What's it to you, anyway?[n][uf 1 1][e]

[msg MSG_DUNGE_AORI_SANADA2 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 4 65535 65535 0 0]Wha—!? What did I say?[n][uf 1 1][e]

[msg MSG_DUNGE_SYAWASITU_ATO4 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 65535 65535 0 0]*sigh* Nothing. Let's just go![n][uf 1 1][e]

[msg MND_DUNGE_HEYA_HURO]
[uf 0 5 65278][uf 2 1]Looks like a bathroom.[n][uf 1 1][e]

[msg MND_DUNGE_HEYA_TV]
[uf 0 5 65278][uf 2 1]The TV doesn't seem to be working.[n][uf 1 1][e]

[msg MSG_DUNGE_HAIRUNA [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5076 0 0]The signal's coming from the large room on the third floor. Let's beat it before someone gets hurt![n][uf 1 1][e]

[msg MSG_DUNGE_HAIRUNA_Y [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 65535 65535 0 0][uf 3 1 3 0 65535 1123 0 0]What are you doing? We're not even on the right floor! C'mon, we need to deal with the Shadow![n][uf 1 1][e]

[msg MSG_DUNGE_HAIRUNA_J [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 65535 65535 0 0][uf 3 1 3 0 65535 2061 0 0]Hey, I wouldn't get sidetracked unless you want an earful from Yuka-tan...[n][uf 1 1][e]

[msg MSG_DUNGE_HAIRUNA_S [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3005 0 0]The signal's coming from the third floor, isn't it? We should go deal with the Shadow.[n][uf 1 1][e]

[msg MSG_DUNGE_HAIRUNA_M [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4001 0 0]There's no time to relax. It's crucial that we eliminate the target with all due haste.[n][uf 1 1][e]

[msg MSG_DUNGE_HAIRUNA_3F_1 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5062 0 0]I don't think that's the right room... It should be more spacious.[n][uf 1 1][e]

[msg MSG_DUNGE_HAIRUNA_3F_2 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5061 0 0]That's not it... The signal's coming from a different room.[n][uf 1 1][e]

[msg MSG_DUNGE_HAIRUNA_3F_3 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5037 0 0]No, it's not that one... Are there any larger rooms?[n][uf 1 1][e]

[msg MSG_DUNGE_HAIRUNA_3FY [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]Hey, I think I saw a big door earlier... Should we maybe check it out?[n][uf 1 1][e]

[msg MSG_DUNGE_HAIRUNA_3FJ [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]Didn't we pass by a fishy-lookin' place before? Maybe that's it?[n][uf 1 1][e]

[msg MSG_DUNGE_HAIRUNA_3FS [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]There are only so many rooms. We'll find it eventually.[n][uf 1 1][e]

[msg MSG_DUNGE_HAIRUNA_3FM [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]We're looking for an especially large room, right? It may look different from the other rooms.[n][uf 1 1][e]

[msg MSG_DUNGE_HAIRUNA2 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]The seal has been broken![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Please head for the Shadow![n][uf 1 1][e]

[msg MND_DUNGE_ELEVATOR_TUKAE]
[uf 0 5 65278][uf 2 1]Looks like the elevator isn't working...[n][uf 1 1][e]

[msg MSG_DUNGE_ELEVATOR_YUKAR [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1022 0 0]It's not working. We'll just have to take the stairs.[n][uf 1 1][e]

[msg MSG_DUNGE_ELEVATOR_FUKA [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5074 0 0]It must be out of order because it's the Dark Hour. Please use the stairs![n][uf 1 1][e]

[msg MSG_DUNGE_FUKA_HAJIKI [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5006 0 0]I'm getting a reading from the large room on the third floor. Please go quickly![n][uf 1 1][e]

[msg MSG_DUNGE_FUKA_HAJIKI2 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0][uf 3 1 3 0 65535 5110 0 0]The seal is surrounding the whole building. It looks like there's no way out right now...[n][uf 1 1][e]

[msg MSG_DUNGE_YUKARI_HAJIKI [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 65535 65535 0 0]In other words, we're not getting out until this Shadow goes down. Well, that's fine by me![n][uf 1 1][e]

[msg MSG_DUNGE_FUKA_HAJIKI3 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]The seal has been broken, so please head for the target![n][uf 1 1][e]

[msg MND_DUNGE_1F_PANEL]
[uf 0 5 65278][uf 2 1]Looks like a list of available rooms.[n][uf 1 1][e]

[msg MSG_DUNGE_PANEL_YUKARI [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1061 0 0]What's this? Are these room numbers?[n][uf 1 1][e]

[msg MND_DUNGE_1F_UKETUKE]
[uf 0 5 65278][uf 2 1]There's a coffin behind the reception desk...[n][uf 1 1][e]

[msg MSG_DUNGE_UKETUKE_JYUNPE [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 65535 65535 0 0][uf 3 1 3 0 65535 2108 0 0]Oof, these rooms are pretty pricey. Good to know...[n][uf 1 1][e]

[msg MND_DUNGE_1F_ZIHANKI]
[uf 0 5 65278][uf 2 1]The vending machine doesn't[n]seem to be working...[n][uf 1 1][e]

[msg MSG_DUNGE_ZIHANKI_YUKARI [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1001 0 0]They don't work during the Dark Hour. Let's go.[n][uf 1 1][e]

[msg MSG_DUNGE_ZIHANKI_JYUNPE [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 65535 65535 0 0][uf 3 1 3 0 65535 2124 0 0]Holy crap, they upcharge for drinks!? Not that I'm buying, but still...[n][uf 1 1][e]

[msg MSG_DUNGE_ZIHANKI_MITSUR [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4059 0 0]It's the Dark Hour. You won't be able to buy anything.[n][uf 1 1][e]

[msg MND_DUNGE_1F_MATIAISITU]
[uf 0 5 65278][uf 2 1]There's a chair behind the curtain.[n][uf 1 1][e]

[msg MND_DUNGE_2F_HININ]
[uf 0 5 65278][uf 2 1]This might be a guest of the hotel...[n][uf 1 1][e]

[msg MSG_DUNGE_HININ_YUKARI [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 65535 65535 0 0][uf 3 1 3 0 65535 1090 0 0]Wha—!? Hey, what're you looking at that for!? Anyways, moving on! Let's go![n][uf 1 1][e]

[msg MSG_DUNGE_HININ_JYUNPE [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 65535 65535 0 0][uf 3 1 3 0 65535 2127 0 0]So, uh... this pretty much proves what kinda hotel this is, right? It's not just my dirty mind?[n][uf 1 1][e]

[msg MSG_DUNGE_HININ_SANADA [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3104 0 0]"Family planning"...? What's this vending machine selling?[n][uf 1 1][e]

[msg MND_DUNGE_2F_HARIGAMI]
[uf 0 5 65278][uf 2 1]There's a poster on the wall here.[n][uf 1 1][e]

[msg MND_DUNGE_3F_HININ]
[uf 0 5 65278][uf 2 1]The vending machine doesn't[n]seem to be working...[n][uf 1 1][e]

[msg MND_DUNGE_3F_HARIGAMI]
[uf 0 5 65278][uf 2 1]There's a poster on the wall here.[n][uf 1 1][e]

[msg MSG_DUNGE_101_MIRROR_YUK [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1062 0 0]This one's just a normal mirror, right? Wasn't there something weird about the one before...?[n][uf 1 1][e]

[msg MND_DUNGE_ROOM101_ISU]
[uf 0 5 65278][uf 2 1]This chair has a backrest.[n][uf 1 1][e]

[msg MSG_DUNGE_ROOM101_ISU_Y [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1076 0 0]C'mon, this is no time to be putting your feet up![n][uf 1 1][e]

[msg MND_DUNGE_ROOM201_SHOWER]
[uf 0 5 65278][uf 2 1]This guest has been transmogrified.[n][uf 1 1][e]

[msg MND_DUNGE_ROOM201_BED]
[uf 0 5 65278][uf 2 1]This guest has been transmogrified.[n][uf 1 1][e]

[msg MND_DUNGE_ROOM202_BEDHUT]
[uf 0 5 65278][uf 2 1]This guest has been transmogrified.[n][uf 1 1][e]

[msg MND_DUNGE_ROOM203_BED]
[uf 0 5 65278][uf 2 1]This guest has been transmogrified.[n][uf 1 1][e]

[msg MND_DUNGE_ROOM203_SOFA]
[uf 0 5 65278][uf 2 1]This guest has been transmogrified.[n][uf 1 1][e]

[msg MND_DUNGE_ROOM204_KARAOK]
[uf 0 5 65278][uf 2 1]This guest has been transmogrified.[n][uf 1 1][e]

[msg MND_DUNGE_ROOM205_BEDHUT]
[uf 0 5 65278][uf 2 1]This guest has been transmogrified.[n][uf 1 1][e]

[msg MND_DUNGE_ROOM301_SHOWER]
[uf 0 5 65278][uf 2 1]This guest has been transmogrified.[n][uf 1 1][e]

[msg MND_DUNGE_ROOM302_ISU]
[uf 0 5 65278][uf 2 1]It's a heart-shaped chair.[n][uf 1 1][e]

[msg MND_DUNGE_ROOM303_BED]
[uf 0 5 65278][uf 2 1]It's a round bed.[n][uf 1 1][e]

[msg MND_DUNGE_ROOM303_OKE]
[uf 0 5 65278][uf 2 1]This guest has been transmogrified.[n][uf 1 1][e]

[msg MND_DUNGE_ROOM304_HITO]
[uf 0 5 65278][uf 2 1]This guest has been transmogrified.[n][uf 1 1][e]

[msg MND_DUNGE_ROOM305_SHOWER]
[uf 0 5 65278][uf 2 1]This guest has been transmogrified.[n][uf 1 1][e]

[msg MND_DUNGE_ROOM305_SOFA]
[uf 0 5 65278][uf 2 1]This guest has been transmogrified.[n][uf 1 1][e]

[msg MND_DUNGE_LOCKED]
[uf 0 5 65278][uf 2 1]The door is locked.[n][uf 1 1][e]

[msg MND_DUNGE_LOCKED_2]
[uf 0 5 65278][uf 2 1]Something's blocking the door from opening.[n]Possibly a coffin inside the room...[n][uf 1 1][e]

[msg MSG_DUNGE_LOCKED_JYUNPE [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 3 0 65535 2061 0 0]I tried that door, but it wouldn't open. I guess it's locked.[n][uf 1 1][e]

[msg MSG_DUNGE_LOCKED_SANADA [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3067 0 0]Being in a locked room might actually be safer for anyone inside right now.[n][uf 1 1][e]

[msg MSG_DUNGE_LOCKED_MITSURU [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4073 0 0]I checked there myself a short while ago. It's locked.[n][uf 1 1][e]

[msg MND_DUNGE_FRIDGE]
[uf 0 5 65278][uf 2 1]It's a small fridge.[n][uf 1 1][e]

[msg MSG_DUNGE_2FONLY [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5076 0 0]Please break the mirror on this floor first before moving on.[n][uf 1 1][e]

[msg MSG_DUNGE_205BREAK [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1001 0 0]Hmm, looks like it's not reflecting everything... Do you want to try breaking it?[n][uf 1 1][e]

[msg MSG_DUNGE_205BREAK_02 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]We can't know for sure if this is the right one, but do you want to try breaking it and see?[n][uf 1 1][e]

[msg MSG_DUNGE_2FMR_BLOCK1 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1060 0 0]This mirror looks pretty normal to me, but it's your call, Leader.[n][uf 1 1][e]

[msg MSG_DUNGE_2FMR_BROKEN [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1062 0 0]If this one's a dud, let's try breaking the mirror in Room 205, okay?[n][uf 1 1][e]

[msg MSG_DUNGE_CHECK_ANOTHER [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1116 0 0]Hey, why don't we check the mirror in the room across the way?[n][uf 1 1][e]

[msg MSG_DUNGE_2FMR_BLOCK2 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5076 0 0]The signal's coming from the third floor. Try searching the rooms there![n][uf 1 1][e]

[msg MSG_DUNGE_2FMR_BLOCK3 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5145 0 0]There's no need to break any more mirrors. Go for the Shadow![n][uf 1 1][e]

[msg MSG_DUNGE_YUKARI_BED [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 65535 65535 0 0]This thing takes up so much space... I guess it's no wonder, given its shape.[n][uf 1 1][e]

[msg MSG_DUNGE_JYUNPEI_BED [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 65535 65535 0 0][uf 3 1 3 0 65535 2108 0 0]Oh, is this the type that spins? Uh, I'm just guessing; it's not like I know anything about that...[n][uf 1 1][e]

[msg MSG_DUNGE_SANADA_BED [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Hm, this round shape... What purpose does is serve?[n][uf 1 1][e]

[msg MSG_DUNGE_MITSURU_BED [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4061 0 0]It may appear lavish at first glance, but the actual craftsmanship leaves much to be desired.[n][uf 1 1][e]

[msg MSG_DUNGE_YUKARI_BEDR [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]It looks super gaudy to me. But I wonder, when it's actually spinning...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 65535 65535 0 0]...No, then it'd just be gaudy and tacky. Anyway, let's keep moving.[n][uf 1 1][e]

[msg MND_DUNGE_ITEMGET]
[uf 0 5 65278][uf 2 1]There's something here...[n][uf 1 1][e]

[msg MSG_DUNGE_YUKARI_SOFA [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1062 0 0]This person might catch a cold, sleeping here like this... But I guess we can't exactly move them...[n][uf 1 1][e]

[msg MSG_DUNGE_YUKARI_3P [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 65535 65535 0 0][uf 3 1 3 0 65535 1022 0 0]Uh, [uf 4 1]-chan? Let's get going, okay?[n][uf 1 1][e]

[msg MSG_DUNGE_JYUNPEI_3P [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 65535 65535 0 0][uf 3 1 3 0 65535 2101 0 0]Wait a minute... One, two, thr— ...! Um, so anyway, uh... Some mission tonight, am I right?[n][uf 1 1][e]

[msg MSG_DUNGE_YUKARI_COUPLE [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 65535 65535 0 0]Hey, what're you staring at!? Focus on the mission![n][uf 1 1][e]

[msg MSG_DUNGE_JYUNPEI_COUPLE [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 65535 65535 0 0][uf 3 1 3 0 65535 2028 0 0]Dude... If the Dark Hour ended right now... *gulp*[n][uf 1 1][e]

[msg MSG_DUNGE_SANADA_COUPLE [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3003 0 0]Just how many guests are there? We've gotta take care of business ASAP.[n][uf 1 1][e]

[msg MSG_DUNGE_MITSURU_COUPLE [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4122 0 0]*sigh* Try not to get distracted so easily...[n][uf 1 1][e]

[msg MSG_DUNGE_YUKARI_COUPLER [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 65535 65535 0 0]Stop gawking like that! C'mon, we still have to deal with the Shadow, you know![n][uf 1 1][e]

[msg MSG_MIRROR_FIRST_CHECK1 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1061 0 0]Well, there's the mirror. So we just break it, right?[n][uf 1 1][e]

[msg MSG_MIRROR_FIRST_SANADA1 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]All right, then. Time to end this hoax.[n][uf 1 1][e]

[msg MSG_MIRROR_FIRST_JYUNPE1 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0]Then let's smash this thing to pieces on the count of three! One, two...[n][uf 1 1][e]

[msg MSG_MIRROR_FIRST_FUKA1_T [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0][uf 3 1 3 0 65535 5072 0 0]Wait, hold on![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0]The signal's close, but I'm not entirely certain that this is the right mirror...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0]Could you check the other room too, just in case?[n][uf 1 1][e]

[msg MSG_MIRROR_FIRST_FUKA1_T_2 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0][uf 3 1 3 0 65535 5056 0 0]Wait, hold on![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0]The signal's close, but I'm not entirely certain that this is the right mirror...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0]Could you check the other room too, just in case?[n][uf 1 1][e]

[msg MSG_MIRROR_FIRST_CHECK2 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]That's a good point... Better to be safe than sorry, so let's cover all our bases first.[n][uf 1 1][e]

[msg MSG_MIRROR_SECOND_CHECK1 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1072 0 0]Okay, there's the mirror.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 65535 65535 0 0]Oh, wait... There's something different about this one compared to the other one...[n][uf 1 1][e]

[msg MSG_MIRROR_SECOND_SANADA [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]You sure? It looks the same to me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]You notice anything, [uf 4 1]?[n][uf 1 1][e]

[msg MSG_MIRROR_SECOND_JYUNPE [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 65535 65535 0 0]Huh, I don't see anything different about it...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]...What about you?[n][uf 1 1][e]

[sel SEL_013_0_0 top]
[uf 0 5 65278][uf 2 1]Our reflections...[e]
[uf 0 5 65278][uf 2 1]The shape is different.[e]
[uf 0 5 65278][uf 2 1]I see ghosts in this one.[e]

[msg MSG_MIRROR_SECOND_SANADA_2 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 4 65535 65535 0 0][uf 3 1 3 0 65535 3030 0 0]Oh, you're right...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 4 65535 65535 0 0]Now that I think about it, the mirror in the other room didn't show our reflections.[n][uf 1 1][e]

[msg MSG_MIRROR_SECOND_JYUNPE_2 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 65535 65535 0 0][uf 3 1 3 0 65535 2094 0 0]What? They're messing with our reflections?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 65535 65535 0 0]Are they pullin' some sorta magic trick on us?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 2 65535 65535 0 0]Well, these are Shadows we're dealing with... You might be onto something![n][uf 1 1][e]

[msg MSG_MIRROR_SECOND_SANADA_3 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 4 65535 65535 0 0][uf 3 1 3 0 65535 3030 0 0]Oh, now that you mention it...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 4 65535 65535 0 0]This mirror is reflecting everything but us.[n][uf 1 1][e]

[msg MSG_MIRROR_SECOND_JYUNPE_3 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 3 0 65535 2103 0 0]What? No way...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 65535 65535 0 0]Holy crap, you're right! It's not showing me in all my heroic glory![n][uf 1 1][e]

[msg MSG_MIRROR_SECOND_SANADA_4 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3047 0 0]Really? I'm not seeing it...[n][uf 1 1][e]

[msg MSG_MIRROR_SECOND_SANADA_5 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]Hmm, no, I don't think that's it, but...[n][uf 1 1][e]

[msg MSG_MIRROR_SECOND_JYUNPE_4 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 65535 65535 0 0][uf 3 1 3 0 65535 2108 0 0]Actually, now that you mention it, this heart looks a little more... hearty?[n][uf 1 1][e]

[msg MSG_MIRROR_SECOND_JYUNPE_5 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 65535 65535 0 0]What does that even mean?[n][uf 1 1][e]

[msg MSG_MIRROR_SECOND_SANADA_6 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3075 0 0]I can't tell if you're being serious or not, but I don't believe in ghosts myself.[n][uf 1 1][e]

[msg MSG_MIRROR_SECOND_SANADA_7 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0]Seriously? You're starting to sound like Junpei...[n][uf 1 1][e]

[msg MSG_MIRROR_SECOND_JYUNPE_6 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 65535 65535 0 0][uf 3 1 3 0 65535 2113 0 0]Well, you know, these kinds of hotels are the perfect place for ghostly activities...[n][uf 1 1][e]

[msg MSG_MIRROR_SECOND_JYUNPE_7 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 65535 65535 0 0]Cut it out, [uf 4 1]-chan. We don't need you jumping on the doofus train, too...[n][uf 1 1][e]

[msg MSG_MIRROR_SECOND_CHECK3 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]Oh, good, you noticed it too, so I'm not just going crazy. Yeah, that other mirror...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]There's definitely something up with a mirror that reflects everything except people.[n][uf 1 1][e]

[msg MSG_MIRROR_SECOND_CHECK3_2 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]Yeah, looking back on it, I think it's the same thing as the mirror in the room the Shadow was in...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]There's definitely something up with a mirror that reflects everything except people.[n][uf 1 1][e]

[msg MSG_MIRROR_SECOND_FUKA21 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 50 0 0]Wow! Yukari-chan, Leader, nice catch, you two![n][uf 1 1][e]

[msg MSG_MIRROR_SECOND_CHECK3_3 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1062 0 0]I thought maybe I was just imagining things, but... I think the other mirror didn't show our reflection.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]There's definitely something up with a mirror that reflects everything except people.[n][uf 1 1][e]

[msg MSG_MIRROR_SECOND_CHECK3_4 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1062 0 0]Here, look. This mirror isn't showing our reflections, see?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]There's definitely something up with a mirror that reflects everything except people.[n][uf 1 1][e]

[msg MSG_MIRROR_SECOND_FUKA22 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 50 0 0]Oh, wow! Good eye, Yukari-chan![n][uf 1 1][e]

[msg MSG_MIRROR_SECOND_CHECK4 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]The mirror in this room is probably just a normal mirror.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]Why don't we go check Room 205 again?[n][uf 1 1][e]

[msg MSG_MIRROR_SECOND_CHECK4_2 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]There's definitely something up with a mirror that reflects everything except people.[n][uf 1 1][e]

[msg MSG_3F_ErrorDoor_01 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0][uf 3 1 3 0 65535 5035 0 0]The mirror in that room wasn't the right one. Let's check a different room.[n][uf 1 1][e]

[msg MSG_3F_ErrorDoor_02 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]Let's focus on trying to find the right mirror for now.[n][uf 1 1][e]

[msg MSG_HououLock_After [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 65535 65535 0 0][uf 3 1 3 0 65535 1006 0 0]The Shadow should be in this room, right? We have to find it![n][uf 1 1][e]

