[msg MSG_000_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2014 0 0]Ça roule, [nf] ?[n][w][e]

[msg MSG_001_0_0 [Ryoji Mochizuki]]
[f 2 1][bup 221 0 65535 65535 0 0][vp 3 0 65535 14001 0 0]Bonjour, [nf].[n][w][e]

[sel SEL_002_0_0 top]
[f 2 1]Bonjour.[e]
[f 2 1]Je ne vois pas ça souvent.[e]

[msg MSG_003_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2075 0 0]Tu sais, je suis sûr que vous vous entendriez bien, tous les deux.[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]Il voulait en savoir plus sur Gekkoukan, alors forcément, j'ai dû partager mon savoir avec lui.[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]C'est vraiment un type sympa.[n][w][e]

[msg MSG_004_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2075 0 0]On s'est juste croisés tout à l'heure et on a discuté.[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]Il voulait en savoir plus sur Gekkoukan, alors forcément, j'ai dû partager mon savoir avec lui.[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]C'est vraiment un type sympa.[n][w][e]

[msg MSG_005_0_0 [Ryoji Mochizuki]]
[f 2 1][bup 221 1 65535 65535 0 0][vp 3 0 65535 14018 0 0]Merci pour ton aide, Junpei.[n][w][e]
[f 2 1][bup 221 1 65535 65535 0 0]Et surtout, merci de m'avoir indiqué qui étaient les "dix filles les plus canon de Gekkoukan".[n][w][e]

[msg MSG_006_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 65535 65535 0 0][vp 3 0 65535 2127 0 0]Chuuut ! Pas si fort ![n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0][f 4 23 0 3 0 25 25]Si Yuka t'entend, je peux dire adieu à ma réputation ![n][w][e]

[sel SEL_007_0_0 top]
[f 2 1]Mais je veux savoir aussi.[e]
[f 2 1]C'est trop tard pour la sauver.[e]

[msg MSG_008_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2108 0 0]Hoho ! Regardez qui est intéressée, d'un coup ![n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]J'aimerais avoir ton opinion aussi. C'est une affaire très sérieuse, tu sais.[n][w][e]

[msg MSG_009_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 65535 65535 0 0][vp 3 0 65535 2113 0 0]Ça va, pas la peine d'en rajouter ! Je suis juste un grand incompris, d'accord ?[n][w][e]

[msg MSG_010_0_0 [Ryoji Mochizuki]]
[f 2 1][bup 221 1 65535 65535 0 0][vp 3 0 65535 14030 0 0]Haha, vous êtes vraiment proches, tous les deux.[n][w][e]
[f 2 1][bup 221 1 65535 65535 0 0]J'espère qu'on pourra aussi être amis, [nf]. On est tous les deux nouveaux ici, après tout.[n][w][e]

