[msg MSG_000_0_0 [Koromaru]]
[f 2 1][bup 9 0 65535 65535 0 0][vp 1 0 0 1 0 0]Kaï...[n][w][e]

[msg MSG_001_0_0 [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 2 0 0]Non.[n][w][e]

[msg MSG_002_0_0 [Koromaru]]
[f 2 1][bup 9 3 65535 65535 0 0][vp 1 0 0 3 0 0]Kaï...[n][w][e]

[msg MSG_003_0_0 [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 4 0 0]Non, c'est non.[n][w][e]

[sel SEL_004_0_0 top]
[f 2 1]Qu'y a-t-il ?[e]
[f 2 1]Quoi, non ?[e]

[msg MSG_005_0_0 [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 5 0 0]Je suis en négociations avec Koromaru.[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 6 0 0]Koromaru n'a pas le droit d'aller se promener seul.[n][w][e]

[msg MSG_006_0_0 [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 7 0 0]C'est l'heure de la patrouille en solo de Koromaru.[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 8 0 0]Plus connue sous le nom de "promenade".[n][w][e]

[msg MSG_007_0_0 [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 9 0 0]Des plans avaient été établis, Sanada devait accompagner Koromaru lors de sa promenade.[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 10 0 0]Cependant, l'heure dite est passée et Sanada n'est toujours pas revenu.[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 11 0 0]Koromaru a atteint les limites de sa patience.[n][w][e]

[msg MSG_008_0_0 [Koromaru]]
[f 2 1][bup 9 0 65535 65535 0 0][vp 0 0 0 12 0 0]......[n][w][e]

[msg MSG_009_0_0 [Koromaru]]
[f 2 1][bup 9 0 65535 65535 0 0][vp 1 0 0 13 0 0]Ouaf ![n][w][e]

[msg MSG_010_0_0 [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 14 0 0]Koromaru demande que [nf] l'accompagne à la place.[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 15 0 0]Es-tu disponible pour cette tâche, [nf] ?[n][w][e]

[sel SEL_011_0_0 top]
[f 2 1]Oui. Le timing est parfait.[e]
[f 2 1]Et toi, Aigis ?[e]

[msg MSG_012_0_0 [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 16 0 0]Tu es ce que l'on nomme une "sauveuse".[n][w][e]

[msg MSG_013_0_0 [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 17 0 0]Ma mission actuelle est de rester en veille au dortoir.[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 18 0 0]Je suis donc indisponible, j'en ai peur.[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 19 0 0]J'appuie la requête de Koromaru, [nf].[n][w][e]

[msg MSG_014_0_0 [Koromaru]]
[f 2 1][bup 9 0 65535 65535 0 0][vp 1 0 0 20 0 0]Ouaf ! Ouaf ![n][w][e]

[msg MND_015_0_0]
[f 2 1]Koromaru et moi avons quitté le dortoir pour une promenade.[n][w][e]

