[msg MSG_000_0_0 [Yukari Takeba]]
[f 2 1][bup 2 4 65535 65535 0 0][vp 3 0 65535 1067 0 0]Ça alors, la nuit tombe déjà...[n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0][f 4 23 0 2 1 25 25]Je n'avais pas réalisé que ça faisait si longtemps qu'on était là.[n][w][e]

[msg MSG_001_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0]Tu as remarqué qu'il y a un tas de mangas qui parlent de lycéens impliqués dans un combat quelconque ?[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][f 4 23 0 2 0 25 25]J'y avais pas encore réfléchi, mais... c'est carrément nous...[n][w][e]

[msg MSG_002_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 3 0 65535 1062 0 0]Mais personne n'est au courant... comme dans un manga, en fait.[n][w][e]

[sel SEL_003_0_0 top]
[f 2 1]Tu as l'air d'une héroïne.[e]
[f 2 1]Effectivement.[e]
[f 2 1]Certains le savent.[e]

[msg MSG_004_0_0 [Yukari Takeba]]
[f 2 1][bup 2 4 65535 65535 0 0][vp 3 0 65535 1047 0 0]Tu veux dire quoi en fait ?[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][f 4 23 0 2 0 25 25]Parce que je suis au club de tir à l'arc ?[n][w][e]

[msg MSG_004_3_0 [Yukari Takeba]]
[f 2 1][bup 2 2 65535 65535 0 0]C'est vrai, quoi... j'ai les bras plutôt musclés...[n][w][e]
[f 2 1][bup 2 2 65535 65535 0 0]Mais je m'en vante pas, hein ![n][w][e]

[msg MND_005_0_0]
[f 2 1]Yukari semble fâchée...[n][w][e]
[f 2 1]J'ai l'impression qu'on ne s'est pas rapprochées, aujourd'hui...[n][w][e]

[msg MSG_006_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 3 0 65535 1025 0 0][f 5 13 7 15 2]B-Bon... Peut-être que je réfléchis trop...[n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0]Il faut que je voie ça comme un secret, alors ?[n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0]Un secret...[n][w][e]

[msg MND_007_0_0]
[f 2 1]Yukari semble contente.[n][w][e]
[f 2 1]Aujourd'hui, j'en ai appris un peu plus sur elle.[n][w][e]

[msg MSG_008_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 3 0 65535 1061 0 0]Comme qui ?[n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0][f 4 23 0 2 1 25 25]Oh, tu parles de l'inspecteur Kurosawa ?[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][f 4 23 0 2 0 25 25]Et j'y pense... Je n'aime pas dire ça, surtout qu'il s'est montré coopératif, mais...[n][w][e]

[msg MSG_008_3_0 [Yukari Takeba]]
[f 2 1][bup 2 3 65535 65535 0 0]Tu trouves pas qu'il fait un peu peur ? Ses yeux, surtout. Mais le répète pas, hein.[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0][f 5 13 7 30 2]Enfin, c'est bon de savoir qu'il y a au moins quelqu'un qui sait ce qu'on fait.[n][w][e]

[msg MND_009_0_0]
[f 2 1]Yukari et moi, on a réussi à se comprendre un peu plus.[n][w][e]
[f 2 1]J'ai l'impression qu'on s'est beaucoup rapprochées, aujourd'hui.[n][w][e]

[msg MSG_010_0_0 [Yukari Takeba]]
[f 2 1][bup 2 6 65535 65535 0 0][vp 3 0 65535 1114 0 0]Ah... j'ai le dos bloqué à force d'être restée trop longtemps dans la même position...[n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0][f 4 23 0 2 1 25 25]Et si on allait se dégourdir un peu les jambes avant de rentrer ? Qu'est-ce que t'en dis ?[n][w][e]

[msg MND_011_0_0]
[f 2 1]On s'est baladées un moment ensemble avant de rentrer au dortoir.[n][w][e]

