[msg MND_002_0_0]
[f 2 1]J'ai décrit en détail divers produits à plusieurs clients intéressés...[n][w][e]

[msg MND_003_0_0]
[f 2 1]J'ai étudié à fond les propriétés des pierres curatives afin d'améliorer mon argumentaire...[n][w][e]

[msg MND_004_0_0]
[f 2 1]J'en ai appris plus sur les produits et leur utilisation dans le cadre de diverses pratiques...[n][w][e]

[msg MND_005_0_0]
[f 2 1]J'ai travaillé dur pour aider les clients au sein d'un magasin dédié à la relaxation et à la guérison...[n][w][e]

[msg MND_006_0_0]
[f 2 1]J'ai travaillé dur, entourée de cristaux qui brillaient mystérieusement...[n][w][e]

[msg MND_007_0_0]
[f 2 1]Les clients léthargiques sont repartis complètement revigorés ![n][w][e]

[msg MSG_008_0_0 [Responsable]]
[f 2 1][f 5 21 0 10]Bon, je vais augmenter ton taux horaire ! Tu sais ce qu'on dit, tout travail mérite salaire.[n][w][e]

[msg MND_009_0_0]
[f 2 1]Comme je commence à bien me débrouiller, je vais recevoir une petite augmentation...[n][w][e]

[msg MSG_010_0_0 [Responsable]]
[f 2 1][f 5 21 0 10]Hé, un client a dit du bien de toi tout à l'heure. Tu devrais venir travailler ici à plein temps quand tu auras fini le lycée ![n][w][e]

[msg MND_011_0_0]
[f 2 1]Comme je me suis améliorée au travail, je vais recevoir une petite augmentation...[n][w][e]

[msg MSG_012_0_0 [Responsable]]
[f 2 1][f 5 21 0 10]Tiens. N'hésite pas à revenir me donner un coup de main à l'occasion.[n][w][e]

[msg MND_013_0_0]
[f 2 1]Travailler avec des gemmes spirituelles semble m'avoir aidée à gagner en [f 4 30 0 1 1 0] et en [f 4 30 1 1 1 0] ![n][w][e]

