[msg MND_000_0_0]
[f 2 1]J'entends mes condisciples murmurer...[n][w][e]

[msg MND_001_0_0]
[f 2 1]J'ai un peu gagné en popularité...[n][w][e]

[msg MND_002_0_0]
[f 2 1]Je lui ai donné la mauvaise réponse...[n][w][e]

[msg MSG_003_0_0 [Mme Toriumi]]
[f 2 1][bup 1581 0 65535 65535 0 0][vp 3 0 65535 15807 0 0][f 5 21 0 100]Ouvrez vos manuels et jetons un œil au premier roman. C'est... du Zenzou Kasai.[n][w][e]
[f 2 1][bup 1581 0 65535 65535 0 0][f 5 21 0 100]Oh non, pas lui.[n][w][e]
[f 2 1][bup 1581 0 65535 65535 0 0][f 5 21 0 100]Ces derniers temps, les œuvres de Tota Kaneko m'intéressent beaucoup plus.[n][w][e]
[f 2 1][bup 1581 0 65535 65535 0 0][f 5 21 0 100]Ses essais sont excellents, et c'est aussi un poète reconnu pour ses haikus.[n][w][e]
[f 2 1][bup 1581 0 65535 65535 0 0][f 5 21 0 100]Je me demande pourquoi ce n'est pas dans le manuel. Bon, j'apporterai un Kaneko la prochaine fois.[n][w][e]

[msg MSG_004_0_0 [Mme Toriumi]]
[f 2 1][bup 1581 0 65535 65535 0 0][f 5 21 0 100]En parlant de haikus, leurs expressions sont souvent liées aux saisons, mais il est facile de se tromper.[n][w][e]
[f 2 1][bup 1581 0 65535 65535 0 0][f 5 21 0 100]Par exemple, "pousses de bambou savoureuses" ou "carpes dans l'eau claire", ça représente le printemps, bien sûr ?[n][w][e]
[f 2 1][bup 1581 0 65535 65535 0 0][f 5 21 0 100]Eh bien, en fait non, c'est l'été ![n][w][e]
[f 2 1][bup 1581 0 65535 65535 0 0][f 5 21 0 100]Les auteurs de haikus évoquaient les saisons selon le calendrier lunaire, ce qui complique les choses.[n][w][e]
[f 2 1][bup 1581 0 65535 65535 0 0][vp 3 0 65535 15801 0 0][f 5 21 0 100]Dis donc, Iori, tu écoutes ? J'ai une question pour toi.[n][w][e]
[f 2 1][bup 1581 0 65535 65535 0 0][f 5 21 0 100]Laquelle de ces expressions symbolise l'été ? "Pluie de pétales", "mirage mystique" ou "carpes dans l'eau claire" ?[n][w][e]

[msg MSG_005_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 65535 65535 0 0][vp 3 0 65535 2099 0 0][f 5 21 0 150]Que ? Euh...[n][w][e]
[f 2 1][bup 3 4 65535 65535 0 0]Hé, [nf] ! T'écoutais ? Viens à mon secours, meuf ![n][w][e]

[msg MSG_006_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 65535 65535 0 0][f 5 21 0 150]L'expression qui symbolise l'été ! Oui ![n][w][e]

[sel SEL_007_0_0 top]
[f 2 1]"Une pluie de pétales."[f 5 20 45 0][e]
[f 2 1]"Un mirage mystique."[f 5 20 45 1][e]
[f 2 1]"Des carpes dans l'eau claire."[f 2 9 1 0 13][f 5 20 45 2][e]

[msg MSG_008_0_0 [Mme Toriumi]]
[f 2 1][bup 1581 1 65535 65535 0 0][vp 3 0 65535 15841 0 0][f 5 21 0 100]Tout juste ![n][w][e]
[f 2 1][bup 1581 1 65535 65535 0 0][f 5 21 0 100]Alors tu m'écoutais, en fait ![n][w][e]

[msg MSG_009_0_0 [Mme Toriumi]]
[f 2 1][bup 1581 2 65535 65535 0 0][vp 3 0 65535 15829 0 0][f 5 21 0 100]Mais non ! Les "carpes dans l'eau claire" représentent l'été, je viens de le dire ![n][w][e]
[f 2 1][bup 1581 2 65535 65535 0 0][f 5 21 0 100]C'est envisageable, que tu écoutes en cours ?[n][w][e]
[f 2 1][bup 1581 2 65535 65535 0 0][f 5 21 0 100]Ah, ça me donne envie de pleurer ! Ouvre tes oreilles, la prochaine fois ![n][w][e]

[msg MSG_010_0_0 [Mme Toriumi]]
[f 2 1][bup 1581 0 65535 65535 0 0][f 5 21 0 100]En passant, "mirage mystique" et "pluie de pétales" symbolisent le printemps.[n][w][e]
[f 2 1][bup 1581 0 65535 65535 0 0][f 5 21 0 100]Les mirages sont un phénomène naturel qui a lieu de fin mars à début juin...[n][w][e]
[f 2 1][bup 1581 0 65535 65535 0 0][f 5 21 0 100]Et la pluie de pétales évoque les averses printanières, quand les cerisiers sont en fleur. Il ne pleut pas vraiment des fleurs.[n][w][e]
[f 2 1][bup 1581 0 65535 65535 0 0][f 5 21 0 100]Retenez bien tout ça. La suite...[n][w][e]

[msg MSG_011_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][f 5 21 0 150]Héhé... Oh, moi, écouter, c'est mon dada ![n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2044 0 0][f 5 21 0 150]Tu m'as grave sauvé la mise, là, [nf] ![n][w][e]

[msg MSG_012_0_0 [Camarade]]
[f 2 1][nl] lui a donné la réponse... Elle doit avoir une super mémoire.[n][w][e]

[msg MSG_013_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 65535 65535 0 0][vp 3 0 65535 2112 0 0][f 5 21 0 150]Oh, ben, euh... E-Excusez-moi ![n][w][e]
[f 2 1][bup 3 4 65535 65535 0 0][f 5 21 0 150]J'oublierai pas, meuf ![n][w][e]

[msg MSG_014_0_0 [Mme Miyahara]]
[f 2 1][bup 1085 0 65535 65535 0 0][vp 3 0 65535 15401 0 0][f 5 21 0 100]Bien, revenons sur les fonctions quadratiques. Vous vous souvenez, bien sûr ?[n][w][e]
[f 2 1][bup 1085 0 65535 65535 0 0][f 5 21 0 100]La courbe qui les représente peut être une parabole, ou une hyperbole.[n][w][e]
[f 2 1][bup 1085 0 65535 65535 0 0][f 5 21 0 100]Des courbes fort séduisantes... mais qui n'arrivent pas à la cheville des spirales paraboliques et hyperboliques ![n][w][e]
[f 2 1][bup 1085 0 65535 65535 0 0][f 5 21 0 100]Ce sont des spirales algébriques. Regardez ! Magnifiques, non ?[n][w][e]

[msg MSG_015_0_0 [Mme Miyahara]]
[f 2 1][bup 1085 0 65535 65535 0 0][vp 3 0 65535 15416 0 0][f 5 21 0 100]Bien. Iori, voyons si tu peux répondre à ma question, d'un point de vue mathématique...[n][w][e]
[f 2 1][bup 1085 0 65535 65535 0 0][f 5 21 0 100]Laquelle des spirales suivantes n'est pas algébrique ?[n][w][e]

[msg MSG_016_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 65535 65535 0 0][vp 3 0 65535 2103 0 0][f 5 21 0 150]Qu-Quoi ? Comment je suis censé savoir ça ?[n][w][e]

[msg MSG_017_0_0 [Junpei Iori]]
[f 2 1][f 5 21 0 150][nf] ! Tu sais laquelle n'est pas algébraque ou je sais pas quoi ?[n][w][e]

[sel SEL_018_0_0 top]
[f 2 1]A.[f 2 9 1 0 13][f 5 20 45 0][e]
[f 2 1]B.[f 5 20 45 1][e]
[f 2 1]C.[f 5 20 45 2][e]
[f 2 1]D.[f 5 20 45 3][e]

[msg MSG_019_0_0 [Mme Miyahara]]
[f 2 1][bup 1085 0 65535 65535 0 0][vp 3 0 65535 15418 0 0][f 5 21 0 100]Exact, bien joué ![n][w][e]
[f 2 1][bup 1085 0 65535 65535 0 0][f 5 21 0 100]Celle-ci est une spirale logarithmique. Quand le facteur de croissance correspond au nombre d'or, on l'appelle spirale d'or.[n][w][e]

[msg MSG_020_0_0 [Mme Miyahara]]
[f 2 1][bup 1085 0 65535 65535 0 0][vp 3 0 65535 15419 0 0][f 5 21 0 100]Dommage, la bonne réponse était A.[n][w][e]
[f 2 1][bup 1085 0 65535 65535 0 0][f 5 21 0 100]Celle-ci est une spirale logarithmique. Quand le facteur de croissance correspond au nombre d'or, on l'appelle spirale d'or.[n][w][e]

[msg MSG_021_0_0 [Mme Miyahara]]
[f 2 1][bup 1085 0 65535 65535 0 0][f 5 21 0 100]Comme son nom l'indique, on peut représenter une spirale algébrique avec une équation algébrique.[n][w][e]
[f 2 1][bup 1085 0 65535 65535 0 0][f 5 21 0 100]B est la spirale d'Archimède, C est une spirale parabolique, et D est un lituus. Les trois sont des spirales algébriques.[n][w][e]
[f 2 1][bup 1085 0 65535 65535 0 0][f 5 21 0 100]Par contre, A, la spirale logarithmique, n'est pas considérée comme une spirale algébrique.[n][w][e]
[f 2 1][bup 1085 0 65535 65535 0 0][f 5 21 0 100]C'est une spirale qu'on retrouve communément dans la nature, comme sur la coquille des nautiles ou les tournesols.[n][w][e]
[f 2 1][bup 1085 0 65535 65535 0 0][f 5 21 0 100]On peut zoomer en avant comme en arrière, tant qu'on veut, la forme reste similaire. On appelle ça l'autosimilarité.[n][w][e]

[msg MSG_022_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][f 5 21 0 150]Cette spirale, ça me rappelle un peu Tartare...[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2043 0 0][f 5 21 0 150]Quoi, pas toi ? Bon. Merci quand même ![n][w][e]

[msg MSG_023_0_0 [Camarade]]
[f 2 1][nl] lui a donné la réponse... Elle doit être super intelligente ![n][w][e]

[msg MSG_024_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2070 0 0][f 5 21 0 150]Euh, en fait... ça ressemble un peu à Tartare, non ? Mais sérieux, qui a bâti ce truc, en fait ?[n][w][e]

[msg MSG_025_0_0 [Mme Miyahara]]
[f 2 1][bup 1085 0 65535 65535 0 0][vp 3 0 65535 15405 0 0][f 5 21 0 100]Ciel... Les coordonnées cartésiennes ! Quelle beauté. Vous ne trouvez pas ?[n][w][e]
[f 2 1][bup 1085 0 65535 65535 0 0][f 5 21 0 100]Mais il y a un bijou en particulier, mon préféré... Vous êtes curieux ? J'en suis sûre. Non ?[n][w][e]

[msg MSG_026_0_0 [Mme Miyahara]]
[f 2 1][bup 1085 0 65535 65535 0 0][f 5 21 0 100]Cette courbe est la représentation d'une équation cartésienne...[n][w][e]
[f 2 1][bup 1085 0 65535 65535 0 0][f 5 21 0 100]Découverte par la mathématicienne italienne Maria Agnesi.[n][w][e]
[f 2 1][bup 1085 0 65535 65535 0 0][f 5 21 0 100]Elle porte d'ailleurs son nom : on l'appelle souvent courbe d'Agnesi.[n][w][e]
[f 2 1][bup 1085 0 65535 65535 0 0][vp 3 0 65535 15416 0 0][f 5 21 0 100]Mais elle a aussi un autre nom plus courant. Iori, une idée de ce que c'est ?[n][w][e]

[msg MSG_027_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 65535 65535 0 0][vp 3 0 65535 2101 0 0][f 5 21 0 150]Que ? Comment je suis censé savoir ? On parle encore de maths ?[n][w][e]
[f 2 1][bup 3 3 65535 65535 0 0][f 5 21 0 150]Psst, [nf]... Tu sais, toi ?[n][w][e]

[msg MSG_028_0_00 [Junpei Iori]]
[f 2 1][f 5 21 0 150]L'autre nom de cette courbe ?[n][w][e]

[sel SEL_029_0_0 top]
[f 2 1]Courbe orthogonale.[f 5 20 45 0][e]
[f 2 1]Spirale de Fermat.[f 5 20 45 1][e]
[f 2 1]Sorcière d'Agnesi.[f 2 9 1 0 13][f 5 20 45 2][e]

[msg MSG_030_0_0 [Mme Miyahara]]
[f 2 1][bup 1085 0 65535 65535 0 0][vp 3 0 65535 15417 0 0][f 5 21 0 100]Mais tout à fait ! Tu me surprends.[n][w][e]

[msg MSG_031_0_0 [Mme Miyahara]]
[f 2 1][bup 1085 0 65535 65535 0 0][vp 3 0 65535 15420 0 0][f 5 21 0 100]Eh non, c'est faux. Question trop difficile, peut-être ?[n][w][e]
[f 2 1][bup 1085 0 65535 65535 0 0][f 5 21 0 100]La courbe d'Agnesi est souvent appelée Sorcière d'Agnesi.[n][w][e]

[msg MSG_032_0_0 [Mme Miyahara]]
[f 2 1][bup 1085 0 65535 65535 0 0][f 5 21 0 100]Quant à savoir pourquoi on l'appelle Sorcière...[n][w][e]
[f 2 1][bup 1085 0 65535 65535 0 0][f 5 21 0 100]Personne ne sait exactement ! Ce serait une erreur de traduction du mot italien pour sinus verse.[n][w][e]
[f 2 1][bup 1085 0 65535 65535 0 0][f 5 21 0 100]Une erreur d'inattention, en quelque sorte ![n][w][e]
[f 2 1][bup 1085 0 65535 65535 0 0][f 5 21 0 100]Ça m'arrive parfois, à moi aussi... mais quand l'erreur persiste pendant des générations, c'est un peu gênant.[n][w][e]
[f 2 1][bup 1085 0 65535 65535 0 0][f 5 21 0 100]À la limite, si la courbe ressemblait à une sorcière, ça aurait été justifiable. Mais même pas, hélas.[n][w][e]

[msg MSG_033_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][f 5 21 0 150]Haha, c'est une question de bon sens, m'dame ![n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2039 0 0][f 5 21 0 150]Ouf... Merci, [nf] ! J'aurais eu l'air trop bête.[n][w][e]

[msg MSG_034_0_0 [Camarade]]
[f 2 1][nl] l'a aidé. Ça, c'est quelqu'un sur qui on peut compter.[n][w][e]

[msg MSG_035_0_0 [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0][vp 3 0 65535 2111 0 0][f 5 21 0 150]Sérieux, on est censé trouver la réponse comment, sans aucun indice ?[n][w][e]

[msg MSG_036_0_0 [M. Takenozuka]]
[f 2 1][bup 1084 0 65535 65535 0 0][vp 3 0 65535 15606 0 0][f 5 21 0 100]Tout le monde comprend la force de Lorentz et la règle de la main gauche ? J'efface le tableau ![n][w][e]
[f 2 1][bup 1084 0 65535 65535 0 0][f 5 21 0 100]J'espère que vous avez bien noté, parce que ça pourrait bien sortir [clr 2]aux examens, dans deux semaines[clr 27].[n][w][e]
[f 2 1][bup 1084 0 65535 65535 0 0][f 5 21 0 100]Mes épaules sont toutes légères, aujourd'hui. Je peux effacer tout en haut du tableau sans le moindre effort.[n][w][e]
[f 2 1][bup 1084 0 65535 65535 0 0][f 5 21 0 100]Peut-être parce que je suis allé aux bains publics, hier. J'ai profité d'un bon massage très relaxant dans le bain bouillonnant.[n][w][e]

[msg MSG_037_0_0 [M. Takenozuka]]
[f 2 1][bup 1084 0 65535 65535 0 0][vp 3 0 65535 15616 0 0][f 5 21 0 100]Ce qui nous amène à ma question...[n][w][e]
[f 2 1][bup 1084 0 65535 65535 0 0][f 5 21 0 100]Quand les jets de bulles du bain bouillonnant vous touchent, votre corps vibre. Nous sommes d'accord ?[n][w][e]
[f 2 1][bup 1084 0 65535 65535 0 0][f 5 21 0 100]Eh bien, ce phénomène porte un nom. Iori, tu le connais peut-être ?[n][w][e]

[msg MSG_038_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 65535 65535 0 0][vp 3 0 65535 2099 0 0][f 5 21 0 150]L'autre... Comment il veut que je sache ça ?[n][w][e]

[msg MSG_039_0_00 [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0][f 5 21 0 150]Hé, [nf] ! T'as une idée ?[n][w][e]
[f 2 1][bup 3 3 65535 65535 0 0][f 5 21 0 150]Quand les jets de bulles du bain bouillonnant touchent et font vibrer le corps, ça s'appelle comment ?[n][w][e]

[sel SEL_040_0_0 top]
[f 2 1]L'effet d'ancrage.[f 5 20 45 0][e]
[f 2 1]L'effet de flottement.[f 2 9 1 0 13][f 5 20 45 1][e]
[f 2 1]L'effet bouillonnant.[f 5 20 45 2][e]

[msg MSG_041_0_0 [M. Takenozuka]]
[f 2 1][bup 1084 0 65535 65535 0 0][vp 3 0 65535 15617 0 0]Ah, alors tu le savais déjà. C'est exact, c'est l'effet de flottement.[n][w][e]
[f 2 1][bup 1084 0 65535 65535 0 0]Le flottement désigne les petites vibrations générées par les interactions entre un écoulement d'air et d'autres forces.[n][w][e]

[msg MSG_042_0_0 [M. Takenozuka]]
[f 2 1][bup 1084 0 65535 65535 0 0][vp 3 0 65535 15620 0 0][f 5 21 0 100]Non, c'est faux. J'attendais que tu me dises : l'effet de flottement.[n][w][e]
[f 2 1][bup 1084 0 65535 65535 0 0][f 5 21 0 100]Le flottement désigne les petites vibrations générées par les interactions entre un écoulement d'air et d'autres forces.[n][w][e]

[msg MSG_043_0_0 [M. Takenozuka]]
[f 2 1][bup 1084 0 65535 65535 0 0][f 5 21 0 100]Les bains bouillonnants ne sont pas seuls à avoir des avantages. Ça vous arrive d'avoir des démangeaisons après un bain normal ?[n][w][e]
[f 2 1][bup 1084 0 65535 65535 0 0][f 5 21 0 100]On dit qu'un bain chaud peut améliorer la circulation sanguine, dans tout le corps.[n][w][e]
[f 2 1][bup 1084 0 65535 65535 0 0][f 5 21 0 100]Et quand le corps se réchauffe, les vaisseaux sanguins se dilatent, ce qui contribue à une élimination globale des toxines...[n][w][e]
[f 2 1][bup 1084 0 65535 65535 0 0][f 5 21 0 100]La chaleur peut stimuler la sécrétion d'histamine, qui conduit souvent à des démangeaisons.[n][w][e]
[f 2 1][bup 1084 0 65535 65535 0 0][f 5 21 0 100]Un bon bain chaud, c'est le paradis, mais profitez-en avec modération. L'eau tiède, par contre, aide à purifier la peau...[n][w][e]
[f 2 1][bup 1084 0 65535 65535 0 0][f 5 21 0 100]Hum, bon, je digresse. Remettons-nous au travail. Ouvrez vos livres page 8...[n][w][e]

[msg MSG_044_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2095 0 0][f 5 21 0 150]Je me ferais bien un bain bouillonnant, moi maintenant... On demande à Kirijo d'en installer un au dortoir ?[n][w][e]

[msg MSG_045_0_0 [Camarade]]
[f 2 1][nl] lui a donné la réponse... Elle doit être super intelligente ![n][w][e]

[msg MSG_046_0_0 [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0][vp 3 0 65535 2115 0 0][f 5 21 0 150]Ça sortira pas aux exams, ça, hein ? Je veux dire, on parlait juste de bains...[n][w][e]

[msg MSG_047_0_0 [M. Ekoda]]
[f 2 1][bup 1082 0 65535 65535 0 0][vp 3 0 65535 15002 0 0][f 5 21 0 100]Comme vous le savez sans doute, de nombreuses théories courent sur l'auteur, Murasaki Shikibu.[n][w][e]
[f 2 1][bup 1082 0 65535 65535 0 0][f 5 21 0 100]Le Dit du Genji serait l'œuvre d'un autre... Murasaki Shikibu ne serait qu'un nom de plume partagé...[n][w][e]
[f 2 1][bup 1082 0 65535 65535 0 0][f 5 21 0 100]Certains avancent même que Murasaki Shikibu était un être venu de l'espace. Très intrigant...[n][w][e]
[f 2 1][bup 1082 0 65535 65535 0 0][f 5 21 0 100]Vous avez sans doute vu son portrait : il figure sur les billets de 2 000 yens.[n][w][e]
[f 2 1][bup 1082 0 65535 65535 0 0][f 5 21 0 100]Et puisqu'on parle de Murasaki Shikibu, voici une question à propos du Dit du Genji.[n][w][e]

[msg MSG_048_0_0 [M. Ekoda]]
[f 2 1][bup 1082 0 65535 65535 0 0][f 5 21 0 100]"Vous n'évoquerez point ce monde devant la princesse"...[n][w][e]
[f 2 1][bup 1082 0 65535 65535 0 0][vp 3 0 65535 15013 0 0][f 5 21 0 100]Quel monde ne faut-il pas évoquer ? Iori ? J'écoute.[n][w][e]

[msg MSG_049_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2098 0 0][f 5 21 0 150]Qui ? Moi ?[n][w][e]

[msg MSG_050_0_0 [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0][f 5 21 0 150]Hé ! Au secours, [nf] ! Il parle de quoi ?[n][w][e]

[sel SEL_051_0_0 top]
[f 2 1]Un monde en paix.[f 5 20 45 0][e]
[f 2 1]L'opinion publique.[f 5 20 45 1][e]
[f 2 1]Les amours.[f 2 9 1 0 13][f 5 20 45 2][e]

[msg MSG_052_0_0 [M. Ekoda]]
[f 2 1][bup 1082 0 65535 65535 0 0][vp 3 0 65535 15018 0 0]Correct. C'était trop facile ?[n][w][e]

[msg MSG_053_0_0 [M. Ekoda]]
[f 2 1][bup 1082 0 65535 65535 0 0][vp 3 0 65535 15010 0 0][f 5 21 0 100]Et c'est... faux.[n][w][e]
[f 2 1][bup 1082 0 65535 65535 0 0][f 5 21 0 100]J'ai hâte de découvrir ce que tu évoqueras lors des examens.[n][w][e]

[msg MSG_054_0_0 [M. Ekoda]]
[f 2 1][bup 1082 0 65535 65535 0 0][f 5 21 0 100]Le "monde" dans cette phrase, c'est celui des relations amoureuses.[n][w][e]
[f 2 1][bup 1082 0 65535 65535 0 0][f 5 21 0 100]On lui dit donc de ne pas lire d'histoires amoureuses devant la princesse.[n][w][e]
[f 2 1][bup 1082 0 65535 65535 0 0][f 5 21 0 100]Cependant, le monde peut aussi évoquer la société, ou l'humanité, comme c'est le cas aujourd'hui.[n][w][e]
[f 2 1][bup 1082 0 65535 65535 0 0][f 5 21 0 100]Alors interprétez de façon adaptée, selon le contexte. Point suivant...[n][w][e]

[msg MSG_055_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2044 0 0][f 5 21 0 150]Ouf... Merci, [nf]. Comme tu m'as sauvé la vie...[n][w][e]

[msg MSG_056_0_0 [Camarade]]
[f 2 1][nl] a sorti du Junpei du pétrin. Quelle fille sympa ![n][w][e]

[msg MSG_057_0_0 [Junpei Iori]]
[f 2 1][bup 3 2 65535 65535 0 0][vp 3 0 65535 2129 0 0][f 5 21 0 150]Grrr... Ekoda égale bouffon...[n][w][e]
[f 2 1][bup 3 2 65535 65535 0 0][f 5 21 0 150]Comme si son Dit du Genji, ça allait nous servir un jour ! Nan mais sérieux ![n][w][e]

[msg MSG_058_0_0 [Mme Terauchi]]
[f 2 1][bup 1583 0 65535 65535 0 0][vp 3 0 65535 16203 0 0][f 5 21 0 100]Examinons quelques expressions idiomatiques anglaises.[n][w][e]
[f 2 1][bup 1583 0 65535 65535 0 0][f 5 21 0 100]Quelqu'un qui a une "big mouth" a une grande gueule, c'est un fanfaron.[n][w][e]

[msg MSG_059_0_0 [Mme Terauchi]]
[f 2 1][bup 1583 0 65535 65535 0 0][f 5 21 0 100]Il y a aussi l'expression "spill the beans"...[n][w][e]
[f 2 1][bup 1583 0 65535 65535 0 0][vp 3 0 65535 16206 0 0][f 5 21 0 100]Que signifie-t-elle ? Junpei, si tu nous le disais ?[n][w][e]

[msg MSG_060_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2098 0 0][f 5 21 0 150]Euh ? Moi ?[n][w][e]

[msg MSG_061_0_0 [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0][f 5 21 0 150]Dis, [nf] ! Tu sais ce que c'est, "spill the beans" ?[n][w][e]

[sel SEL_062_0_0 top]
[f 2 1]Laisser tomber des sous.[f 5 20 45 0][e]
[f 2 1]Se mettre à sourire.[f 5 20 45 1][e]
[f 2 1]Révéler un secret.[f 2 9 1 0 13][f 5 20 45 2][e]

[msg MSG_063_0_0 [Mme Terauchi]]
[f 2 1][bup 1583 0 65535 65535 0 0][vp 3 0 65535 16218 0 0][f 5 21 0 100]Oui, c'est bien ça ![n][w][e]

[msg MSG_064_0_0 [Mme Terauchi]]
[f 2 1][bup 1583 0 65535 65535 0 0][vp 3 0 65535 16219 0 0][f 5 21 0 100]Oh non, Junpei, non ! "Spill the beans" signifie révéler un secret.[n][w][e]

[msg MSG_065_0_0 [Mme Terauchi]]
[f 2 1][bup 1583 0 65535 65535 0 0][f 5 21 0 100]Pourquoi "beans", c'est-à-dire haricots ? Il y a diverses théories.[n][w][e]
[f 2 1][bup 1583 0 65535 65535 0 0][f 5 21 0 100]Selon l'une des plus connues, c'est parce que les haricots servaient à voter en Grèce antique.[n][w][e]
[f 2 1][bup 1583 0 65535 65535 0 0][f 5 21 0 100]À l'époque, on mettait un haricot blanc dans l'urne pour dire oui, et un noir pour dire non...[n][w][e]
[f 2 1][bup 1583 0 65535 65535 0 0][f 5 21 0 100]Donc, si on "spill the beans", si on renverse les haricots avant la fin du vote, on révèle la couleur... et on brise le secret.[n][w][e]
[f 2 1][bup 1583 0 65535 65535 0 0][f 5 21 0 100]Oh ! Ça me rappelle... La dernière fois, mon cher darling...[n][w][e]

[msg MSG_066_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2040 0 0][f 5 21 0 150]Ouf... Merci, [nf].[n][w][e]

[msg MSG_067_0_0 [Camarade]]
[f 2 1][nl] lui a donné la réponse... Elle doit être super intelligente ![n][w][e]

[msg MSG_068_0_0 [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0][vp 3 0 65535 2115 0 0][f 5 21 0 150]Bon, c'est pas la fin des haricots, quoi.[n][w][e]

[msg MSG_069_0_0 [Mme Toriumi]]
[f 2 1][bup 1581 0 65535 65535 0 0][vp 3 0 65535 15809 0 0][f 5 21 0 100][clr 2]Les examens commencent lundi[clr 27]. Vous avez bien révisé ? Parce que si vous vous plantez, c'est sur moi que ça retombe.[n][w][e]
[f 2 1][bup 1581 0 65535 65535 0 0][f 5 21 0 100]Ouvrez vos manuels, la leçon du jour sera sur... le pluriel et ses irréguliers.[n][w][e]
[f 2 1][bup 1581 0 65535 65535 0 0][f 5 21 0 100]On voit beaucoup ce genre d'erreur.[n][w][e]
[f 2 1][bup 1581 0 65535 65535 0 0][f 5 21 0 100]La règle générale est d'ajouter un "s" à la fin du mot pour marquer le pluriel.[n][w][e]
[f 2 1][bup 1581 0 65535 65535 0 0][f 5 21 0 100]Jusque-là, ça va ?[n][w][e]

[msg MSG_070_0_0 [Mme Toriumi]]
[f 2 1][bup 1581 2 65535 65535 0 0][vp 3 0 65535 15822 0 0][f 5 21 0 100]Mais il existe des mots irréguliers auxquels il faut faire attention.[n][w][e]
[f 2 1][bup 1581 0 65535 65535 0 0][f 5 21 0 100]Tu as l'air décontenancé, Iori.[n][w][e]
[f 2 1][bup 1581 0 65535 65535 0 0][f 5 21 0 100]Sais-tu lequel de ces pluriels est irrégulier ?[n][w][e]

[msg MSG_071_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 65535 65535 0 0][vp 3 0 65535 2098 0 0][f 5 21 0 150]Que... Quoi ? Moi ? Punaise... j'écoutais pas.[n][w][e]

[msg MSG_072_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][f 5 21 0 150][nf] ! À l'aide ![n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0][f 5 21 0 150]Tu sais de quoi elle parle ? C'est quoi, la réponse ?[n][w][e]

[sel SEL_073_0_0 top]
[f 2 1]Chèvre, chèvres.[f 5 20 45 0][e]
[f 2 1]Corail, coraux.[f 2 9 1 0 13][f 5 20 45 1][e]
[f 2 1]Emmental, emmentals.[f 5 20 45 2][e]

[msg MSG_074_0_0 [Mme Toriumi]]
[f 2 1][bup 1581 0 65535 65535 0 0][vp 3 0 65535 15842 0 0][f 5 21 0 100]Ah, tu écoutais, en fait. C'est drôle, on n'aurait pas cru...[n][w][e]

[msg MSG_075_0_0 [Mme Toriumi]]
[f 2 1][bup 1581 2 65535 65535 0 0][vp 3 0 65535 15843 0 0][f 5 21 0 100]Mais non ! La réponse est "coraux".[n][w][e]
[f 2 1][bup 1581 2 65535 65535 0 0][f 5 21 0 100]Arrête de rêver et fais attention ![n][w][e]

[msg MSG_076_0_0 [Mme Toriumi]]
[f 2 1][bup 1581 0 65535 65535 0 0][f 5 21 0 100]Comme pour la plupart des noms, il suffit d'ajouter un S à chèvre pour obtenir chèvres.[n][w][e]
[f 2 1][bup 1581 0 65535 65535 0 0][f 5 21 0 100]Emmental vient d'un nom propre et son pluriel prend simplement un S. C'est un cas particulier mais pas irrégulier.[n][w][e]
[f 2 1][bup 1581 0 65535 65535 0 0][f 5 21 0 100]Bon. La suite...[n][w][e]

[msg MSG_077_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][f 5 21 0 150]Sérieux... S'ils pouvaient tous arrêter de me tomber dessus...[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2042 0 0][f 5 21 0 150]Merci, [nf]. T'es une soeur.[n][w][e]

[msg MSG_078_0_0 [Camarade]]
[f 2 1][nl] a sorti du Junpei du pétrin. Quelle fille sympa ![n][w][e]

[msg MSG_079_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2092 0 0][f 5 21 0 150]Rêver, hein... OK, je rêvais peut-être, mais toi aussi, tu ferais bien de redescendre sur terre.[n][w][e]

