[msg MSG_000_0_0 [Hombre poco agradable]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 1 0 0][uf 5 21 0 1011]Oye, no seas así. Conozco un lugar perfecto para los dos, chica.[n][uf 1 1][e]

[msg MSG_001_0_0 [Fan de antes]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 2 0 0][uf 5 21 0 1001]¡Déjanos en paz! No nos interesa.[n][uf 1 1][e]

[msg MSG_001_5_0 [Hombre presumido]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 3 0 0][uf 5 21 0 1012]Una bebida, ¡es lo único que te pido! Venga ya, será divertido.[n][uf 1 1][e]

[msg MSG_001_7_0 [Fan con miedo]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 4 0 0][uf 5 21 0 1002]Hemos dicho que no, ¡¿vale?![n][uf 1 1][e]

[sel SEL_002_0_0 top]
[uf 0 5 65278][uf 2 1]Son las chicas de antes.[e]
[uf 0 5 65278][uf 2 1]¿Están ligando con ellas...?[e]

[msg MSG_003_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 65535 65535 0 0][uf 3 1 0 0 0 5 0 0]...[n][uf 1 1][e]

[msg MSG_005_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]Oye.[n][uf 1 1][e]

[msg MSG_006_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]Déjalas en paz, no querrás que llame a la policía, ¿no?[n][uf 1 1][e]

[msg MSG_007_0_0 [Hombre poco agradable]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 8 0 0][uf 5 21 0 1011]¿Eh? ¿Quién demonios eres tú?[n][uf 1 1][e]

[msg MSG_008_0_0 [Hombre presumido]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 9 0 0][uf 5 21 0 1012]¿Quieres llamar a la pasma? Deja de dártelas de valiente, niñato.[n][uf 1 1][e]

[msg MSG_009_0_0 [Hombre poco agradable]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 10 0 0][uf 5 21 0 1011]Sí, ¡va siendo hora de que te vayas a la mierda![n][uf 1 1][e]

[msg MSG_010_0_0 [Hombre presumido]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 11 0 0][uf 5 21 0 1012]¡Pedazo de...![n][uf 1 1][e]

[msg MSG_011_0_0 [Chico duro]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 12 0 0][uf 5 21 0 1013]Un momento.[n][uf 1 1][e]

[msg MSG_012_0_0 [Chico duro]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 13 0 0][uf 5 21 0 1013]Menudos derechazos. Sabes pelear, ¿me equivoco?[n][uf 1 1][e]

[msg MSG_013_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]¿Y qué si es así?[n][uf 1 1][e]

[msg MSG_014_0_0 [Chico duro]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 15 0 0][uf 5 21 0 1013]¿Qué te parece si luchamos un par de rondas? Si no estás muy ocupado, conozco un sitio estupendo por aquí.[n][uf 1 1][e]

[msg MSG_023_0_0 [Chico duro]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 16 0 0][uf 5 21 0 1013]Cada vez que veo a peña que se cree que son lo más, lo único que quiero es ponerlos en su sitio.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 17 0 0][uf 5 21 0 1013]Seguro que la gente te llama tipo duro. ¿Y si te ponemos a prueba?[n][uf 1 1][e]

[msg MSG_024_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 65535 65535 0 0][uf 3 1 0 0 0 18 0 0]...[n][uf 1 1][e]

[msg MSG_025_0_0 [Lacayo]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 19 0 0][uf 5 21 0 1014]¿Qué? ¿Ahora tiene miedo? ¡Ja, ja, ja, ja![n][uf 1 1][e]

[msg MSG_026_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 20 0 0]¿Ves? Te dije que solo causa problemas.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 65535 65535 0 0][uf 3 1 1 0 0 21 0 0][uf 4 23 0 4 2 25 25]Quedaos aquí, en un minuto vuelvo.[n][uf 1 1][e]

[msg MSG_027_0_0 [Chico duro]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 22 0 0][uf 5 21 0 1013]¡¿Qué pasa?! ¡¿Te crees que me vas a ganar así como así?![n][uf 1 1][e]

[msg MSG_028_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 65535 65535 0 0][uf 3 1 1 0 0 23 0 0]No te preocupes, no me vuelco por completo con enclenques como tú. Será un combate justo.[n][uf 1 1][e]

[msg MSG_029_0_0 [Chico duro]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 24 0 0][uf 5 21 0 1013]¡Agh...![n][uf 1 1][e]

[msg MSG_030_0_0 [Voz del coche de policía]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 25 0 0]¡Eh! ¡Vosotros, dejadlo ya![n][uf 1 1][e]

[msg MSG_031_0_0 [Chico duro]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 26 0 0][uf 5 21 0 1013]Tss, ¡nos vamos![n][uf 1 1][e]

[msg MSG_032_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 3 65535 65535 0 1][uf 3 1 1 0 0 27 0 0]Ya se lo he dicho agente, ellos han sido los que nos han provocado.[n][uf 1 1][e]

[msg MSG_032_5_0 [Policía joven]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 28 0 0][uf 5 21 0 1021]Y yo ya te he dicho que hablaremos del tema en la comisaría.[n][uf 1 1][e]

[msg MSG_032_7_0 [Policía de mediana edad]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 29 0 0][uf 5 21 0 1022]Sois estudiantes de instituto, ¿no? Necesitamos vuestra información de contacto para avisar a vuestros padres.[n][uf 1 1][e]

[msg MSG_098_0_0 [Agente Kurosawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 1 0 0 30 0 0][uf 5 21 0 1086]Perdón por la interrupción...[n][uf 1 1][e]

[msg MSG_099_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 31 0 0]¡Agente Kurosawa![n][uf 1 1][e]

[msg MSG_102_0_0 [Agente Kurosawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 1 0 0 32 0 0][uf 5 21 0 1086]Yo me encargo de estos dos. Ya lo he hablado con los jefes.[n][uf 1 1][e]

[msg MSG_033_0_0 [Agente Kurosawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 1 0 0 33 0 0][uf 5 21 0 1086]No sé qué está pasando aquí, pero más vale que no os metáis en problemas.[n][uf 1 1][e]

[sel SEL_033_5_0 top]
[uf 0 5 65278][uf 2 1]No ha pasado nada.[e]
[uf 0 5 65278][uf 2 1]No ha sido nuestra culpa.[e]
[uf 0 5 65278][uf 2 1]Ha faltado poco.[e]

[msg MSG_033_2_0 [Agente Kurosawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 1 0 0 34 0 0][uf 5 21 0 1086]¿Entonces por qué dos chicas nos han llamado diciendo que os ha atacado un grupo de maleantes?[n][uf 1 1][e]

[msg MSG_033_4_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 35 0 0]Querían poner a prueba mi fuerza, así que a eso me disponía.[n][uf 1 1][e]

[msg MSG_033_6_0 [Agente Kurosawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 1 0 0 36 0 0][uf 5 21 0 1086]¿En medio de la calle? Deberías pensar las cosas dos veces antes de actuar.[n][uf 1 1][e]

[msg MSG_034_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 37 0 0]Je, no te habrás pensado que estábamos en peligro, ¿no?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 38 0 0][uf 4 23 0 4 0 25 25]Aunque la cosa se haya puesto tensa, jamás te pondría en peligro.[n][uf 1 1][e]

[msg MSG_034_5_0 [Agente Kurosawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 1 0 0 39 0 0][uf 5 21 0 1086]¿Entonces por qué dos chicas nos han llamado diciendo que os ha atacado un grupo de maleantes?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 1 0 0 40 0 0][uf 5 21 0 1086]Si quieres demostrar lo fuerte que eres, hay momento y lugar para ello.[n][uf 1 1][e]

[msg MSG_035_0_0 [Agente Kurosawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 1 0 0 41 0 0][uf 5 21 0 1086]Escucha, soy agente de la ley. Me da igual quién seas; todo aquel que perturbe la paz tendrá que vérselas conmigo.[n][uf 1 1][e]

[msg MSG_036_0_0 [Agente Kurosawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 1 0 0 42 0 0][uf 5 21 0 1086]Como puedes ver, tu amigo es un poco bocachancla.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 1 0 0 43 0 0][uf 5 21 0 1086]Sé que no va a ser fácil, pero no le quites ojo de encima, ¿vale?[n][uf 1 1][e]

[sel SEL_037_0_0 top]
[uf 0 5 65278][uf 2 1]Yo me encargo.[e]
[uf 0 5 65278][uf 2 1]No sé si puedo.[e]

[msg MSG_038_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 44 0 0]Muy atrevido por tu parte, pero gracias.[n][uf 1 1][e]

[msg MSG_039_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 45 0 0]No se preocupe, sé contra quién combatir.[n][uf 1 1][e]

[msg MSG_040_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 46 0 0]Tengo el brazo totalmente curado y ahora tenemos más gente de fiar. No hay mejor momento para probar mi fuerza.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 47 0 0]Sobre todo ahora que contamos con alguien como tú. Hemos tenido mucha suerte.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 48 0 0]Voy a seguir afinando mis habilidades, así podré acabar con quien me plante cara con un movimiento de manos.[n][uf 1 1][e]

[msg MSG_041_0_0 [Agente Kurosawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 1 0 0 49 0 0][uf 5 21 0 1086]Veo que no has cambiado en absoluto...[n][uf 1 1][e]

[msg MSG_042_0_0 [Agente Kurosawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 1 0 0 50 0 0][uf 5 21 0 1086]En fin, que no se os suba a la cabeza.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 1 0 0 51 0 0][uf 5 21 0 1086]Me da la sensación de que esos tipos son miembros de una banda que ha estado haciendo de las suyas por aquí.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 1 0 0 52 0 0][uf 5 21 0 1086]Tened cuidado. Es mejor no cabrearlos, porque si os cogen tirria, no os van a dejar en paz.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1086 0 65535 65535 0 0][uf 3 1 1 0 0 53 0 0][uf 5 21 0 1086]En fin, es tarde. Va siendo hora de que volváis a la residencia.[n][uf 1 1][e]

[msg MSG_043_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 54 0 0]Damos la salida por terminada. No hemos tenido más que interrupciones.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 55 0 0]Aunque Kurosawa tiene razón, deberíamos volver a casa. Lo siento. Te lo compensaré en otro momento.[n][uf 1 1][e]

[msg MSG_044_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 56 0 0]Voy a volver corriendo a la residencia, ¿te apuntas?[n][uf 1 1][e]

[sel SEL_045_0_0 top]
[uf 0 5 65278][uf 2 1]Claro...[e]
[uf 0 5 65278][uf 2 1]No, gracias.[e]

[msg MSG_046_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 57 0 0]Bien dicho. Ya es de noche, así que cuidado con los coches.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 58 0 0]Yo me vuelvo corriendo, ¡tú ve a tu ritmo![n][uf 1 1][e]

[msg MND_047_0_0]
[uf 0 5 65278][uf 2 1]...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]He vuelto corriendo a la residencia.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Siento que mi aguante ha aumentado[n]tras correr tantos kilómetros...[n][uf 1 1][e]

[msg SYS_HPUP_0_0]
[uf 0 5 65278][uf 2 1]Tus PS máximos aumentan en 5.[n][uf 1 1][e]

[msg MSG_048_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 59 0 0]¿Seguro? Si corres, llegarás antes.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 60 0 0]En fin, me voy adelantando. ¡Ve con cuidado a la vuelta![n][uf 1 1][e]

[msg MND_049_0_0]
[uf 0 5 65278][uf 2 1]He despedido a Sanada y he vuelto a la residencia.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Me siento mucho más agudA tras ver la estoica expresión de Sanada...[n][uf 1 1][e]

[msg PFM_SPUP_0_0]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 61 0 0]Tus PE máximos aumentan en 3.[n][uf 1 1][e]

