[msg MSG_000_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 1 0 0]Ei, [nl]-chan![n][w][e]

[msg MSG_001_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 2 0 0]Se estiver livre hoje, vamos voltar pra casa juntas?[n][w][e]

[sel SEL_002_0_0 top]
[f 2 1]Claro.[e]
[f 2 1]Não.[e]

[msg MSG_003_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 3 0 0]Maravilha! Vamos passar na cafeteria no caminho de casa.[n][w][e]

[msg MSG_004_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 4 0 0]Poxa, não precisa ser assim. A gente só vai fazer um desviozinho, tá?[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 5 0 0]Quero falar sobre as atividades do nosso clube também. Relaxa, não vou te alugar demais.[n][w][e]

[msg MND_005_0_0 [Monólogo interno]]
[f 2 1]Parece que Yuko quer conversar[n]sobre alguma coisa...[n][w][e]
[f 2 1]Acho que é melhor eu ir na onda dela.[n][w][e]

[msg MSG_006_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 6 0 0]Maravilha! Vamos passar na cafeteria no caminho de casa.[n][w][e]

