[msg MSG_000_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 3 0 65535 11093 0 0]Ahh, finalmente... Que bom que deu pra gente se encontrar de verdade, em vez de ficar só se cumprimentando entre as aulas.[n][w][e]

[msg MSG_001_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0]Roupa maneira, [nl]-chan. Você tem bom gosto.[n][w][e]
[f 2 1][bup 106 3 65535 65535 0 0][f 4 23 0 106 3 25 25]O Kaz não é assim, só usa aquele agasalho... Dá vergonha, vou te dizer. Tipo, ele deve ter alguma coisa que não tenha cara de escola, né?[n][w][e]

[msg MSG_002_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 3 0 65535 11007 0 0]Eu, por exemplo. O que você acha da minha roupa?[n][w][e]

[sel SEL_003_0_0 top]
[f 2 1]Ficou uma gracinha.[e]
[f 2 1]Você parece mais madura.[e]
[f 2 1]Te deixa elegante.[e]

[msg MSG_004_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 3 0 65535 11054 0 0][f 5 13 12 15 106]... Gracinha, é?[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0]Não sei os outros, mas eu acho o termo "gracinha" um tanto condescendente.[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0][f 4 23 0 106 1 25 25]Mas sei que não foi o que você quis dizer, então vou encarar como um elogio.[n][w][e]

[msg MND_005_0_0]
[f 2 1]Yuko parece meio envergonhada...[n][w][e]
[f 2 1]Eu aprendi mais a respeito dela hoje.[n][w][e]

[msg MSG_006_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 2 65535 65535 0 0][vp 3 0 65535 11052 0 0]... [nl]-chan, do que você tá falando?[n][w][e]
[f 2 1][bup 106 2 65535 65535 0 0]Você acha que eu pareço uma vovozinha? Fala sério! Você acha que usar calças é coisa de gente... "madura"...[n][w][e]

[msg MND_007_0_0]
[f 2 1]Yuko parece estar chateada.[n][w][e]
[f 2 1]Acho que não nos aproximamos hoje...[n][w][e]

[msg MSG_008_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 4 65535 65535 0 0][vp 3 0 65535 11075 0 0][f 5 13 12 30 106]Sério? Você acha isso mesmo?[n][w][e]

[msg MSG_009_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 4 65535 65535 0 0]Tipo, quem sou eu pra te corrigir e tal, mas...[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0][f 4 23 0 106 1 25 25]Acho que não tô acostumada a andar com gente que elogia os outros do nada assim, então... Obrigada![n][w][e]

[msg MND_010_0_0]
[f 2 1]Yuko parece muito feliz.[n][w][e]
[f 2 1]Acho que nos aproximamos muito hoje.[n][w][e]

[msg MSG_011_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 3 0 65535 11067 0 0]Vamos caminhar um pouco mais e encontrar algo pra comer. Mas... nada de takoyaki.[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0]Se tem uma coisa que estraga um visual é pedaço de alga presa nos dentes.[n][w][e]

[msg MND_012_0_0]
[f 2 1]A gente deu umas voltas antes[n]de nos despedirmos.[n][w][e]

