[msg Item_000]
[f 2 1]未使用[n][e]

[msg Item_001]
[f 2 1]Sapatos de couro legítimo com ajuste confortável.[n][e]

[msg Item_002]
[f 2 1]Mocassins marrons com design simples.[n][e]

[msg Item_003]
[f 2 1]Botas genéricas decoradas com uma listra horizontal.[n][e]

[msg Item_004]
[f 2 1]Calçados atléticos com design clássico.[n][e]

[msg Item_005]
[f 2 1]Longas botas pretas com um brilho lustroso.[n][e]

[msg Item_006]
[f 2 1]Mocassins pretos com design simples.[n][e]

[msg Item_007]
[f 2 1]Coxotes para Aigis. Feitos de ferro puro.[n][e]

[msg Item_008]
[f 2 1]Calçados confortáveis para futsal.[n][e]

[msg Item_009]
[f 2 1]As almofadas das patas são muito macias.[n][e]

[msg Item_00A]
[f 2 1]Botas resistentes de salto baixo. Um pouco maiores do que botas comuns.[n][e]

[msg Item_00B]
[f 2 1]Sandálias texturizadas que oferecem uma pisada confortável.[n][e]

[msg Item_00C]
[f 2 1]Botas casuais de solado grosso.[n][e]

[msg Item_00D]
[f 2 1]Geta retrô que passa uma sensação barbárica.[n][e]

[msg Item_00E]
[f 2 1]Botas de couro feitas de material resistente.[n][e]

[msg Item_00F]
[f 2 1]Calçados com uma fileira de rodinhas que agilizam o deslocamento.[n][e]

[msg Item_010]
[f 2 1]Botas reforçadas usadas por militares.[n][e]

[msg Item_011]
[f 2 1]Geta mecanizada feita com tecnologia avançada.[n][e]

[msg Item_012]
[f 2 1]Meia-calça com estampa de leopardo extremamente chique.[n][e]

[msg Item_013]
[f 2 1]Grevas robustas pintadas de vermelho-escuro.[n][e]

[msg Item_014]
[f 2 1]Sandálias com design excêntrico que fortalecem o poder mágico.[n][e]

[msg Item_015]
[f 2 1]Calçados duráveis que aguentam até o peso de um tanque de guerra.[n][e]

[msg Item_016]
[f 2 1]Grevas de um guerreiro dedicado a aperfeiçoar a própria esgrima.[n][e]

[msg Item_017]
[f 2 1]Calçados avançados feitos com o poder da ciência.[n][e]

[msg Item_018]
[f 2 1]Tabi preta usada por ninjas para aumentar a Agilidade.[n][e]

[msg Item_019]
[f 2 1]Tabi imponente que aumenta o Ataque e a taxa de crítico do usuário.[n][e]

[msg Item_01A]
[f 2 1]Calçados cravejados que conferem um chute muito doloroso.[n][e]

[msg Item_01B]
[f 2 1]Botas motorizadas que vão além da tecnologia moderna.[n][e]

[msg Item_01C]
[f 2 1]Zori com cheiro de palha que permite movimentos ágeis.[n][e]

[msg Item_01D]
[f 2 1]Calçados extremamente leves que não fazem barulho nenhum.[n][e]

[msg Item_01E]
[f 2 1]Grevas tão resistentes que não quebram por nada.[n][e]

[msg Item_01F]
[f 2 1]Sapatos leves e bastante confortáveis.[n][e]

[msg Item_020]
[f 2 1]Geta teleguiada. Eleva o Ataque ao receber uma Troca.[n][e]

[msg Item_021]
[f 2 1]Calçados equipados com espinhos afiados. Manuseie com cuidado.[n][e]

[msg Item_022]
[f 2 1]Sandálias clássicas com uma estampa estilosa de leão.[n][e]

[msg Item_023]
[f 2 1]Sandálias arejadas na cor prata.[n][e]

[msg Item_024]
[f 2 1]Calçados de matadores de aluguel. Também são ótimos no dia a dia.[n][e]

[msg Item_025]
[f 2 1]Calçados excêntricos que dizem deixar o usuário mais atraente.[n][e]

[msg Item_026]
[f 2 1]Sandálias tão leves que fazem o usuário achar que está flutuando.[n][e]

[msg Item_027]
[f 2 1]Grevas de alto desempenho nas quais reside um deus da guerra.[n][e]

[msg Item_028]
[f 2 1]Botas suntuosas adornadas com um belo trabalho em ouro.[n][e]

[msg Item_029]
[f 2 1]Calçados abençoados pelo poder de um rei antigo.[n][e]

[msg Item_02A]
[f 2 1]Tabi que aumenta a Agilidade do grupo todo no início da batalha.[n][e]

[msg Item_02B]
[f 2 1]Botas misteriosas. Elevam o Ataque ao receber uma Troca.[n][e]

[msg Item_02C]
[f 2 1]Calçados misteriosos. Restauram PE ao receber uma Troca.[n][e]

[msg Item_02D]
[f 2 1]Calçados decorados que tornam muito mais fácil se esquivar de ataques.[n][e]

[msg Item_02E]
[f 2 1]Estimula pontos de pressão. Pode doer se o usuário não estiver saudável.[n][e]

[msg Item_02F]
[f 2 1]Saltos que não escorregam nem no gelo. São frios ao toque.[n][e]

[msg Item_030]
[f 2 1]Tênis que concedem a coragem necessária para dar mais um passo.[n][e]

[msg Item_031]
[f 2 1]Calçados que deixam qualquer um leve e veloz.[n][e]

[msg Item_032]
[f 2 1]Sandálias leves que fazem o usuário sentir que não pesa nada.[n][e]

[msg Item_033]
[f 2 1]Calçados para se mover agilmente em combate. Perfeitos para o Sanada.[n][e]

[msg Item_034]
[f 2 1]Meia-calça feminina que é resistente a eletricidade.[n][e]

[msg Item_035]
[f 2 1]Zori tradicional decorada com desenhos de raios.[n][e]

[msg Item_036]
[f 2 1]Calçados que dizem ter sido usados por quem conquistou o mundo.[n][e]

[msg Item_037]
[f 2 1]Botas misteriosas que trazem boa sorte ao usuário.[n][e]

[msg Item_038]
[f 2 1]Permitem aguentar um ataque de morte súbita de Trevas com 1 PV.[n][e]

[msg Item_039]
[f 2 1]Protetor leve e resistente que confere boa defesa às pernas.[n][e]

[msg Item_03A]
[f 2 1]Saltos que deixam o usuário com uma vontade repentina de dançar.[n][e]

[msg Item_03B]
[f 2 1]Lembram um casco de tartaruga. Chance baixa de refletir ataques físicos.[n][e]

[msg Item_03C]
[f 2 1]Calçados futuristas que despertam a criança interior.[n][e]

[msg Item_03D]
[f 2 1]Calçados diabólicos. Restauram PE ao receber uma Troca.[n][e]

[msg Item_03E]
[f 2 1]Botas leves. Restauram PE do aliado que recebe sua Troca.[n][e]

[msg Item_03F]
[f 2 1]Geta de origem desconhecida. Eleva as habilidades do usuário.[n][e]

[msg Item_040]
[f 2 1]Saltos que já pertenceram a um anjo.[n][e]

[msg Item_041]
[f 2 1]Calçados que aumentam a Agilidade a ponto de criar imagens residuais.[n][e]

[msg Item_042]
[f 2 1]Calçados dotados de uma beleza quase divina.[n][e]

[msg Item_043]
[f 2 1]Sandálias populares entre a molecada. Ótimas para o Amada.[n][e]

[msg Item_044]
[f 2 1]未使用[n][e]

[msg Item_045]
[f 2 1]未使用[n][e]

[msg Item_046]
[f 2 1]未使用[n][e]

[msg Item_047]
[f 2 1]未使用[n][e]

[msg Item_048]
[f 2 1]Coxotes para Aigis. Feitos de materiais carbonosos.[n][e]

[msg Item_049]
[f 2 1]Coxotes para Aigis. Fáceis de usar no dia a dia.[n][e]

[msg Item_04A]
[f 2 1]Coxotes para Aigis. Com boa durabilidade e resistência ao calor.[n][e]

[msg Item_04B]
[f 2 1]Coxotes para Aigis. Contêm um forte poder eletromagnético.[n][e]

[msg Item_04C]
[f 2 1]Coxotes para Aigis. Resistentes a corrosão.[n][e]

[msg Item_04D]
[f 2 1]Coxotes para Aigis. Produzidos com fibras especiais.[n][e]

[msg Item_04E]
[f 2 1]Coxotes para Aigis. Fortes e leves.[n][e]

[msg Item_04F]
[f 2 1]Coxotes para Aigis. Feitos com uma liga leve, preta e sofisticada.[n][e]

[msg Item_050]
[f 2 1]Coxotes para Aigis. Altamente resistentes a abrasão.[n][e]

[msg Item_051]
[f 2 1]Coxotes para Aigis. Extremamente resistentes a corrosão.[n][e]

[msg Item_052]
[f 2 1]Coxotes para Aigis. Feitos à imagem de uma divindade feral.[n][e]

[msg Item_053]
[f 2 1]Coxotes para Aigis. Modelo experimental usado em testes.[n][e]

[msg Item_054]
[f 2 1]Coxotes para Aigis. Produzidos com técnicas especiais.[n][e]

[msg Item_055]
[f 2 1]Coxotes para Aigis. Isola a eletricidade.[n][e]

[msg Item_056]
[f 2 1]Coxotes para Aigis. Restauram um pouco de PV durante a batalha.[n][e]

[msg Item_057]
[f 2 1]Coxotes para Aigis. Equipados com um sistema exaustor de calor.[n][e]

[msg Item_058]
[f 2 1]Coxotes para Aigis. Irradiam uma divindade angelical.[n][e]

[msg Item_059]
[f 2 1]Coxotes para Aigis. Aprimora todas as capacidades de desempenho.[n][e]

[msg Item_05A]
[f 2 1]Coxotes para Aigis. Sua aplicação prática é expressamente proibida.[n][e]

[msg Item_05B]
[f 2 1]未使用[n][e]

[msg Item_05C]
[f 2 1]未使用[n][e]

[msg Item_05D]
[f 2 1]未使用[n][e]

[msg Item_05E]
[f 2 1]未使用[n][e]

[msg Item_05F]
[f 2 1]未使用[n][e]

[msg Item_060]
[f 2 1]未使用[n][e]

[msg Item_061]
[f 2 1]未使用[n][e]

[msg Item_062]
[f 2 1]未使用[n][e]

[msg Item_063]
[f 2 1]未使用[n][e]

[msg Item_064]
[f 2 1]未使用[n][e]

[msg Item_065]
[f 2 1]未使用[n][e]

[msg Item_066]
[f 2 1]未使用[n][e]

[msg Item_067]
[f 2 1]未使用[n][e]

[msg Item_068]
[f 2 1]未使用[n][e]

[msg Item_069]
[f 2 1]未使用[n][e]

[msg Item_06A]
[f 2 1]未使用[n][e]

[msg Item_06B]
[f 2 1]未使用[n][e]

[msg Item_06C]
[f 2 1]未使用[n][e]

[msg Item_06D]
[f 2 1]未使用[n][e]

[msg Item_06E]
[f 2 1]未使用[n][e]

[msg Item_06F]
[f 2 1]未使用[n][e]

[msg Item_070]
[f 2 1]未使用[n][e]

[msg Item_071]
[f 2 1]未使用[n][e]

[msg Item_072]
[f 2 1]未使用[n][e]

[msg Item_073]
[f 2 1]未使用[n][e]

[msg Item_074]
[f 2 1]未使用[n][e]

[msg Item_075]
[f 2 1]未使用[n][e]

[msg Item_076]
[f 2 1]未使用[n][e]

[msg Item_077]
[f 2 1]未使用[n][e]

[msg Item_078]
[f 2 1]未使用[n][e]

[msg Item_079]
[f 2 1]未使用[n][e]

[msg Item_07A]
[f 2 1]未使用[n][e]

[msg Item_07B]
[f 2 1]未使用[n][e]

[msg Item_07C]
[f 2 1]未使用[n][e]

[msg Item_07D]
[f 2 1]未使用[n][e]

[msg Item_07E]
[f 2 1]未使用[n][e]

[msg Item_07F]
[f 2 1]未使用[n][e]

[msg Item_080]
[f 2 1]未使用[n][e]

[msg Item_081]
[f 2 1]未使用[n][e]

[msg Item_082]
[f 2 1]未使用[n][e]

[msg Item_083]
[f 2 1]未使用[n][e]

[msg Item_084]
[f 2 1]未使用[n][e]

[msg Item_085]
[f 2 1]未使用[n][e]

[msg Item_086]
[f 2 1]未使用[n][e]

[msg Item_087]
[f 2 1]未使用[n][e]

[msg Item_088]
[f 2 1]未使用[n][e]

[msg Item_089]
[f 2 1]未使用[n][e]

[msg Item_08A]
[f 2 1]未使用[n][e]

[msg Item_08B]
[f 2 1]未使用[n][e]

[msg Item_08C]
[f 2 1]未使用[n][e]

[msg Item_08D]
[f 2 1]未使用[n][e]

[msg Item_08E]
[f 2 1]未使用[n][e]

[msg Item_08F]
[f 2 1]未使用[n][e]

[msg Item_090]
[f 2 1]未使用[n][e]

[msg Item_091]
[f 2 1]未使用[n][e]

[msg Item_092]
[f 2 1]未使用[n][e]

[msg Item_093]
[f 2 1]未使用[n][e]

[msg Item_094]
[f 2 1]未使用[n][e]

[msg Item_095]
[f 2 1]未使用[n][e]

[msg Item_096]
[f 2 1]未使用[n][e]

[msg Item_097]
[f 2 1]未使用[n][e]

[msg Item_098]
[f 2 1]未使用[n][e]

[msg Item_099]
[f 2 1]未使用[n][e]

[msg Item_09A]
[f 2 1]未使用[n][e]

[msg Item_09B]
[f 2 1]未使用[n][e]

[msg Item_09C]
[f 2 1]未使用[n][e]

[msg Item_09D]
[f 2 1]未使用[n][e]

[msg Item_09E]
[f 2 1]未使用[n][e]

[msg Item_09F]
[f 2 1]未使用[n][e]

[msg Item_0A0]
[f 2 1]未使用[n][e]

[msg Item_0A1]
[f 2 1]未使用[n][e]

[msg Item_0A2]
[f 2 1]未使用[n][e]

[msg Item_0A3]
[f 2 1]未使用[n][e]

[msg Item_0A4]
[f 2 1]未使用[n][e]

[msg Item_0A5]
[f 2 1]未使用[n][e]

[msg Item_0A6]
[f 2 1]未使用[n][e]

[msg Item_0A7]
[f 2 1]未使用[n][e]

[msg Item_0A8]
[f 2 1]未使用[n][e]

[msg Item_0A9]
[f 2 1]未使用[n][e]

[msg Item_0AA]
[f 2 1]未使用[n][e]

[msg Item_0AB]
[f 2 1]未使用[n][e]

[msg Item_0AC]
[f 2 1]未使用[n][e]

[msg Item_0AD]
[f 2 1]未使用[n][e]

[msg Item_0AE]
[f 2 1]未使用[n][e]

[msg Item_0AF]
[f 2 1]未使用[n][e]

[msg Item_0B0]
[f 2 1]未使用[n][e]

[msg Item_0B1]
[f 2 1]未使用[n][e]

[msg Item_0B2]
[f 2 1]未使用[n][e]

[msg Item_0B3]
[f 2 1]未使用[n][e]

[msg Item_0B4]
[f 2 1]未使用[n][e]

[msg Item_0B5]
[f 2 1]未使用[n][e]

[msg Item_0B6]
[f 2 1]未使用[n][e]

[msg Item_0B7]
[f 2 1]未使用[n][e]

[msg Item_0B8]
[f 2 1]未使用[n][e]

[msg Item_0B9]
[f 2 1]未使用[n][e]

[msg Item_0BA]
[f 2 1]未使用[n][e]

[msg Item_0BB]
[f 2 1]未使用[n][e]

[msg Item_0BC]
[f 2 1]未使用[n][e]

[msg Item_0BD]
[f 2 1]未使用[n][e]

[msg Item_0BE]
[f 2 1]未使用[n][e]

[msg Item_0BF]
[f 2 1]未使用[n][e]

[msg Item_0C0]
[f 2 1]未使用[n][e]

[msg Item_0C1]
[f 2 1]未使用[n][e]

[msg Item_0C2]
[f 2 1]未使用[n][e]

[msg Item_0C3]
[f 2 1]未使用[n][e]

[msg Item_0C4]
[f 2 1]未使用[n][e]

[msg Item_0C5]
[f 2 1]未使用[n][e]

[msg Item_0C6]
[f 2 1]未使用[n][e]

[msg Item_0C7]
[f 2 1]未使用[n][e]

[msg Item_0C8]
[f 2 1]未使用[n][e]

[msg Item_0C9]
[f 2 1]未使用[n][e]

[msg Item_0CA]
[f 2 1]未使用[n][e]

[msg Item_0CB]
[f 2 1]未使用[n][e]

[msg Item_0CC]
[f 2 1]未使用[n][e]

[msg Item_0CD]
[f 2 1]未使用[n][e]

[msg Item_0CE]
[f 2 1]未使用[n][e]

[msg Item_0CF]
[f 2 1]未使用[n][e]

[msg Item_0D0]
[f 2 1]未使用[n][e]

[msg Item_0D1]
[f 2 1]未使用[n][e]

[msg Item_0D2]
[f 2 1]未使用[n][e]

[msg Item_0D3]
[f 2 1]未使用[n][e]

[msg Item_0D4]
[f 2 1]未使用[n][e]

[msg Item_0D5]
[f 2 1]未使用[n][e]

[msg Item_0D6]
[f 2 1]未使用[n][e]

[msg Item_0D7]
[f 2 1]未使用[n][e]

[msg Item_0D8]
[f 2 1]未使用[n][e]

[msg Item_0D9]
[f 2 1]未使用[n][e]

[msg Item_0DA]
[f 2 1]未使用[n][e]

[msg Item_0DB]
[f 2 1]未使用[n][e]

[msg Item_0DC]
[f 2 1]未使用[n][e]

[msg Item_0DD]
[f 2 1]未使用[n][e]

[msg Item_0DE]
[f 2 1]未使用[n][e]

[msg Item_0DF]
[f 2 1]未使用[n][e]

[msg Item_0E0]
[f 2 1]未使用[n][e]

[msg Item_0E1]
[f 2 1]未使用[n][e]

[msg Item_0E2]
[f 2 1]未使用[n][e]

[msg Item_0E3]
[f 2 1]未使用[n][e]

[msg Item_0E4]
[f 2 1]未使用[n][e]

[msg Item_0E5]
[f 2 1]未使用[n][e]

[msg Item_0E6]
[f 2 1]未使用[n][e]

[msg Item_0E7]
[f 2 1]未使用[n][e]

[msg Item_0E8]
[f 2 1]未使用[n][e]

[msg Item_0E9]
[f 2 1]未使用[n][e]

[msg Item_0EA]
[f 2 1]未使用[n][e]

[msg Item_0EB]
[f 2 1]未使用[n][e]

[msg Item_0EC]
[f 2 1]未使用[n][e]

[msg Item_0ED]
[f 2 1]未使用[n][e]

[msg Item_0EE]
[f 2 1]未使用[n][e]

[msg Item_0EF]
[f 2 1]未使用[n][e]

[msg Item_0F0]
[f 2 1]未使用[n][e]

[msg Item_0F1]
[f 2 1]未使用[n][e]

[msg Item_0F2]
[f 2 1]未使用[n][e]

[msg Item_0F3]
[f 2 1]未使用[n][e]

[msg Item_0F4]
[f 2 1]未使用[n][e]

[msg Item_0F5]
[f 2 1]未使用[n][e]

[msg Item_0F6]
[f 2 1]未使用[n][e]

[msg Item_0F7]
[f 2 1]未使用[n][e]

[msg Item_0F8]
[f 2 1]未使用[n][e]

[msg Item_0F9]
[f 2 1]未使用[n][e]

[msg Item_0FA]
[f 2 1]未使用[n][e]

[msg Item_0FB]
[f 2 1]未使用[n][e]

[msg Item_0FC]
[f 2 1]未使用[n][e]

[msg Item_0FD]
[f 2 1]未使用[n][e]

[msg Item_0FE]
[f 2 1]未使用[n][e]

[msg Item_0FF]
[f 2 1]未使用[n][e]

