[msg MSG_000_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 1 0 0]Então... Hã...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 2 0 0]Por favor, não ria disso, tá bem?[n][w][e]

[msg MSG_001_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 3 0 0]Outro dia, deixei a Yukari-chan provar um novo prato que eu fiz.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 4 0 0]Ela gostou tanto que comeu tudinho.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 5 0 0]Então expliquei pra ela que era um jeito de retribuir o favor que fizeram por mim.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 6 0 0]Mas ela ficou muito confusa e me perguntou que favor era esse.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 7 0 0]Ela parecia não fazer a menor ideia do que eu estava falando, então contei a história toda.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 8 0 0]E, quando eu terminei... ela caiu na gargalhada.[n][w][e]

[msg MSG_002_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 9 0 0]Ela me disse que eu não precisava fazer nada assim.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 10 0 0]Ela disse: "Não contamos favores de amigos."[n][w][e]

[sel SEL_003_0_0 top]
[f 2 1]Ela tem razão.[e]
[f 2 1]Ahaha! Que engraçado.[e]

[msg MSG_004_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 0 0 0 11 0 0]...[n][w][e]

[msg MSG_005_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 2 65535 65535 0 0][vp 1 0 0 12 0 0]Ei, eu pedi pra você não rir...[n][w][e]

[msg MSG_005_5_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 13 0 0]Sinceramente...[n][w][e]

[msg MSG_006_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 14 0 0]Eu fui tão negativa esse tempo todo.[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 15 0 0]Senti que precisava ser útil para ficar aqui.[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 16 0 0]Mas isso não era verdade. Eu que coloquei isso na cabeça.[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 17 0 0]Fiquei cega pelo medo.[n][w][e]

[msg MSG_006_5_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 18 0 0]Mas entender isso me fez ver o que eu realmente quero fazer.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 19 0 0]Fiquei pensando em como retribuir o que todos fizeram por mim, mas...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 20 0 0]O verdadeiro motivo é bem mais simples.[n][w][e]

[msg MSG_007_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 1 0][vp 1 0 0 21 0 0]Então, hã... você... vai me ouvir?[n][w][e]

[msg MSG_008_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 1 0][vp 1 0 0 22 0 0]Normalmente eu pediria a sua opinião sobre como fazer algo assim, mas...[n][w][e]
[f 2 1][bup 6 3 65535 65535 1 0][vp 0 0 0 23 0 0]...[n][w][e]

[msg MSG_009_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 1 0][vp 1 0 0 24 0 0]Eu...[n][w][e]
[f 2 1][bup 6 0 65535 65535 1 0][vp 1 0 0 25 0 0]Quero você ao meu lado, [nl]-chan.[n][w][e]
[f 2 1][bup 6 0 65535 65535 1 0][vp 1 0 0 26 0 0]Eu quero ficar com você pra sempre.[n][w][e]

[sel SEL_010_0_0 top]
[f 2 1]Sinto o mesmo.[e]
[f 2 1]Eu também.[e]

[msg MSG_011_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 1 0][vp 1 0 0 27 0 0]Hum...[n][w][e]
[f 2 1][bup 6 3 65535 65535 1 0][vp 1 0 0 28 0 0]E-Espero que você entenda o que eu quis dizer.[n][w][e]

[msg MND_012_0_0]
[f 2 1]É melhor eu escolher minhas palavras com cuidado...[n][w][e]

[msg MND_013_0_0]
[f 2 1]É melhor eu escolher minhas palavras com cuidado...[n][w][e]
[f 2 1]Pensando bem, [clr 2]eu já tenho um relacionamento[clr 27][n][clr 2]especial com outra pessoa[clr 27]...[n][w][e]

[msg MSG_011_5_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 1 0][vp 0 0 0 29 0 0]...[n][w][e]

[sel SEL_014_0_0 top]
[f 2 1]Eu te amo, Fuuka.[f 2 9 1 1 348][e]
[f 2 1]Sempre seremos amigas.[e]

[msg MSG_015_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 4 65535 65535 1 0][vp 0 0 0 30 0 0][f 5 13 3 15 6]...?![n][w][e]

[sel SEL_016_0_0 top]
[f 2 1]Nós sempre estaremos juntas.[e]
[f 2 1]Vou te tratar bem.[e]

[msg MSG_017_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 31 0 0]Sim...![n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 32 0 0]Não importa o que acontecer, vou estar ao seu lado.[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 33 0 0]Enquanto eu puder contar com você, [nl]-chan, sinto que posso fazer qualquer coisa.[n][w][e]

[msg MSG_018_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 1 0][vp 1 0 0 34 0 0]Obrigada...[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0][vp 0 0 0 35 0 0]...[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 36 0 0]Desculpa, não sei o que dizer.[n][w][e]

[msg MSG_019_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 1 0][vp 1 0 0 37 0 0]Hum...[n][w][e]
[f 2 1][bup 6 0 65535 65535 1 0][vp 0 0 0 38 0 0]...[n][w][e]
[f 2 1][bup 6 1 65535 65535 1 0][vp 1 0 0 39 0 0][f 4 23 0 6 1 25 25]Eu te amo.[n][w][e]

[msg MND_020_0_0]
[f 2 1]Fuuka declarou seu amor por mim.[n][w][e]
[f 2 1]O meu relacionamento com Fuuka agora é especial...[n][w][e]

[msg MND_021_0_0]
[f 2 1]É o sinal marcando[n]o fim do dia escolar...[n][w][e]

[msg MSG_022_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 40 0 0]Ah, olha a hora...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 0 0 0 41 0 0]...[n][w][e]

[msg MSG_022_5_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 1 0][vp 1 0 0 42 0 0]Você acha... que podemos conversar mais um pouco?[n][w][e]

[msg MND_023_0_0]
[f 2 1]Conversei com Fuuka por um longo tempo...[n][w][e]

[msg MSG_024_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0][vp 0 0 0 43 0 0]...[n][w][e]

[msg MSG_024_5_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 44 0 0]Obrigada...[n][w][e]

[msg MSG_025_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 45 0 0]Sabe, quando estou com você, e todo mundo no alojamento...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 46 0 0]Sinto que vai ficar tudo bem, não importa o que aconteça. Sei que nossos vínculos não vão acabar.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 47 0 0]Eu não sei se pensaria assim se você não estivesse lá para me ajudar com minhas péssimas habilidades culinárias, [nl]-chan.[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 48 0 0][f 4 23 0 6 1 25 25]Então, obrigada... Por tudo.[n][w][e]

[msg MSG_026_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 49 0 0]Não vou mais ficar pensando em ter que retribuir pra todo mundo.[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 50 0 0]Mas acho que vou continuar cozinhando.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 51 0 0][f 4 23 0 6 0 25 25]E, dessa vez, não para manter meu relacionamento com ninguém... É porque eu quero fazer por mim mesma.[n][w][e]

[msg MND_027_0_0]
[f 2 1]Sinto a determinação da Fuuka.[n][w][e]
[f 2 1]Parece que nos aproximamos...[n][w][e]

[msg MSG_028_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 52 0 0]Então, se estiver tudo bem, [nl]-chan...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 53 0 0]Acha que ainda pode me ajudar a cozinhar?[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 54 0 0]Sei que nem sempre vai dar certo, e às vezes parece que estou impondo isso a você...[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 55 0 0][f 4 23 0 6 1 25 25]Mas... acho que seria divertido cozinhar com amigos.[n][w][e]

[sel SEL_029_0_0 top]
[f 2 1]Claro.[e]
[f 2 1]Não tenho certeza.[e]
[f 2 1]O que você vai fazer?[e]

[msg MSG_030_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 56 0 0][f 5 13 3 15 6]Que bom! Obrigada, [nl]-chan.[n][w][e]

[msg MSG_031_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 57 0 0]Achei que seria melhor escolher alguma coisa divertida para fazer com outras pessoas.[n][w][e]

[msg MSG_032_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 58 0 0]Bem, acho que tudo bem, já que a gente faz isso como uma equipe.[n][w][e]

[msg MSG_033_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 59 0 0]Ah, mas...[n][w][e]

[msg MSG_033_5_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 60 0 0]Você acha que pode temperar?[n][w][e]

[msg MSG_034_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 61 0 0]Hmm, o que ficaria bom...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 62 0 0]Acho que vou tentar fazer alguma coisa que as pessoas não fazem todo dia.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 63 0 0]Talvez algo mais tradicional? Ou que tal algo francês?[n][w][e]

[msg MSG_035_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 64 0 0]Hehe, mal posso esperar.[n][w][e]

[msg MSG_036_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 65 0 0]Ah! Preciso ir andando.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 66 0 0]Tenho que comprar uns livros de culinária. Me avisa se você pensar em alguma coisa, tá?[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 67 0 0][f 4 23 0 6 1 25 25]Até depois.[n][w][e]

[msg MND_037_0_0]
[f 2 1]Me despedi da Fuuka e[n]voltei ao alojamento...[n][w][e]

