[msg MSG_000_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0][uf 4 23 0 1 0 25 25]Fuu, fuuu...[n][uf 1 1][e]

[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]A pesar de lo sencillo que parece el caldo a simple vista, los fideos acentúan su sabor.[n][uf 1 1][e]

[msg MSG_002_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 3 65535 65535 0 0][uf 3 1 1 0 0 2 0 0][uf 4 23 0 1 10 25 25]Dios, estoy hasta las narices, mujer.[n][uf 1 1][e]

[sel SEL_003_0_0 top]
[uf 0 5 65278][uf 2 1]¿Del ramen?[e]
[uf 0 5 65278][uf 2 1]¿Del insti?[e]
[uf 0 5 65278][uf 2 1]¿De la vida?[e]

[msg MSG_004_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 3 65535 65535 0 0][uf 3 1 1 0 0 3 0 0][uf 4 23 0 1 10 25 25]No, no. No estaría aquí si me hubiera hartado de comer ramen.[n][uf 1 1][e]

[msg MSG_005_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 6 65535 65535 0 0][uf 3 1 1 0 0 4 0 0][uf 4 23 0 1 3 25 25]Estoy harto del instituto desde que empecé.[n][uf 1 1][e]

[msg MSG_006_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 6 65535 65535 0 0][uf 3 1 1 0 0 5 0 0][uf 4 23 0 1 3 25 25][uf 5 13 2 15 101]¿De la vida? Anda que no ves tú películas.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 3 65535 65535 0 0][uf 3 1 1 0 0 6 0 0][uf 4 23 0 1 10 25 25]Aunque sí, viene a ser eso.[n][uf 1 1][e]

[msg MSG_007_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0][uf 3 1 1 0 0 7 0 0][uf 4 23 0 1 0 25 25]Me levanto, voy al instituto, escucho los tostones de clase, ceno, veo la tele y a dormir.[n][uf 1 1][e]

[msg MSG_008_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 1 65535 65535 0 0][uf 3 1 1 0 0 8 0 0][uf 4 23 0 1 1 25 25]Decidido, [uf 4 1]. ¡Voy a buscarme novia![n][uf 1 1][e]

[sel SEL_009_0_0 top]
[uf 0 5 65278][uf 2 1]Imposible.[e]
[uf 0 5 65278][uf 2 1]¡Buena suerte![e]

[msg MSG_010_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 2 65535 65535 0 0][uf 3 1 1 0 0 9 0 0][uf 4 23 0 1 2 25 25]Pero ¿qué dices? Si soy todo un donjuán. ¡No veas cómo ligo![n][uf 1 1][e]

[msg MSG_011_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 1 65535 65535 0 0][uf 3 1 1 0 0 10 0 0][uf 4 23 0 1 1 25 25][uf 5 13 2 5 101]¡Cómo molas, tía! A ver si me echo pronto novia y soy igual de guay que tú.[n][uf 1 1][e]

[msg MSG_012_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0][uf 3 1 1 0 0 11 0 0][uf 4 23 0 1 0 25 25]A ver, creo que voy a poner en marcha mi plan secreto.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0][uf 3 1 1 0 0 12 0 0][uf 4 23 0 1 0 25 25]Ya te comenté lo de la profesora, ¿no? Le pediré salir y haré que se enamore de mí.[n][uf 1 1][e]

[msg MSG_012_3_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 1 65535 65535 0 0][uf 3 1 1 0 0 13 0 0][uf 4 23 0 1 1 25 25]Es la profesora Kanou. ¿La conoces? Enseña Ética en tercero. Nos llevamos fenomenal.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 1 65535 65535 0 0][uf 3 1 1 0 0 14 0 0][uf 4 23 0 1 1 25 25]No cumple con los cánones de belleza, pero es muy guapa. Tiene unos ojillos muy monos y un cuerpazo.[n][uf 1 1][e]

[msg MSG_013_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 4 65535 65535 0 0][uf 3 1 1 0 0 15 0 0][uf 4 23 0 1 4 25 25]Oye, no le digas nada de esto a nadie, ¿vale? Solo lo sabes tú.[n][uf 1 1][e]

[msg MND_014_0_0]
[uf 0 5 65278][uf 2 1]Kenji me ha contado más cosas sobre su plan.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Tengo la sensación de que nuestra relación se ha fortalecido.[n][uf 1 1][e]

[msg MSG_015_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 1 65535 65535 0 0][uf 3 1 1 0 0 16 0 0][uf 4 23 0 1 1 25 25]¡Madre mía, qué emoción! ¡Vamos a idear un plan de ataque![n][uf 1 1][e]

[msg MND_016_0_0]
[uf 0 5 65278][uf 2 1]Kenji y yo hemos hablado de vuelta a casa.[n][uf 1 1][e]

