[msg MSG_000_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]Casi es medianoche.[n][uf 1 1][e]

[msg MSG_000_5_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]Supongo que hoy no vamos a la Tártaro, ¿no? Kirijo creía que no llegaríamos todos a tiempo.[n][uf 1 1][e]

[msg MSG_001_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]No te estoy aburriendo, ¿verdad? Sé que esta noche que has elegido pasar conmigo es especial.[n][uf 1 1][e]

[msg MSG_002_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]Perdona, ¿estoy siendo grosera? No sé ni lo que digo.[n][uf 1 1][e]

[msg MSG_002_5_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]Es la primera vez que hago algo así por Navidad y estoy nerviosa.[n][uf 1 1][e]

[msg MSG_002_7_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]Pero me hace muy feliz pasar la noche contigo. No lo olvidaré nunca.[n][uf 1 1][e]

[msg MSG_003_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]Muchas gracias por todo. Confío muchísimo en ti, de verdad.[n][uf 1 1][e]

[msg MSG_003_5_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 1 0][uf 3 1 1 0 0 8 0 0]Y no solo porque seas la líder. También es porque te... te...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 1 0][uf 3 1 1 0 0 9 0 0]Te qui...[n][uf 1 1][e]

[msg MSG_004_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 1 0][uf 3 1 1 0 0 10 0 0]Ay, ay, no... ¡Perdona![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 1 0][uf 3 1 0 0 0 11 0 0][uf 4 23 0 6 0 25 25]...[n][uf 1 1][e]

[msg MSG_004_3_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 1 0][uf 3 1 1 0 0 12 0 0]¿Qué hacemos después?[n][uf 1 1][e]

[msg MSG_004_5_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 1 0][uf 3 1 1 0 0 13 0 0]Todavía tenemos tiempo.[n][uf 1 1][e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]He estado con Fuuka hasta que ha anochecido.[n][uf 1 1][e]

