[msg MSG_000_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 4 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]Foi mal pelo atraso![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 2 0 0][uf 4 23 0 106 0 25 25]Tava tirando dúvida com o professor sobre uma coisa que eu não tinha entendido na aula.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]Mas aí isso gerou ainda mais dúvidas, então eu acabei ficando presa lá por um tempo.[n][uf 1 1][e]

[msg MSG_001_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]Ugh, isso tá muito pesado. Eu não deveria ter jogado tudo aqui dentro...[n][uf 1 1][e]

[sel SEL_002_0_0 top]
[uf 0 5 65278][uf 2 1]Equipamento para a equipe?[e]
[uf 0 5 65278][uf 2 1]Quer que eu carregue?[e]

[msg MSG_003_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]Não, são só livros.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]Eu tinha tantas dúvidas pra tirar que acabei trazendo os livros de todas as disciplinas.[n][uf 1 1][e]

[msg MSG_004_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 7 0 0][uf 5 13 12 5 106]Não precisa, tá tranquilo! É só imaginar que estou fazendo musculação.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 8 0 0]Mesmo assim, não dá pra acreditar no quanto esses livros são pesados! Estudantes do mundo inteiro sofrem mesmo.[n][uf 1 1][e]

[msg MSG_005_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 0 0 0 9 0 0]...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]Eu fico tão nostálgica quando venho nesse campo...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 11 0 0]Nem faz tanto tempo assim que treinamos as crianças, né?[n][uf 1 1][e]

[sel SEL_006_0_0 top]
[uf 0 5 65278][uf 2 1]É porque foi muito gratificante.[e]
[uf 0 5 65278][uf 2 1]É a idade...[e]

[msg MSG_007_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 12 0 0][uf 5 13 12 5 106]Com certeza. Eu realmente tive que colocar corpo e cérebro pra trabalhar.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]Eu nunca precisei correr tanto, nem mesmo na equipe de atletismo.[n][uf 1 1][e]

[msg MSG_008_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]Ei! Não seja tão insensível![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 15 0 0]Você podia simplesmente dizer que eu cresci ou amadureci. Qual foi, pô![n][uf 1 1][e]

[msg MSG_009_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 16 0 0]Ah é, quase esqueci. Isso aqui é pra você.[n][uf 1 1][e]

[msg MND_010_0_0]
[uf 0 5 65278][uf 2 1]Eu obtive o item (ITEM NAME)![n][uf 1 1][e]

[msg MSG_011_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 17 0 0]É das crianças. Elas me pediram para "entregar isso pra [uf 4 1]-san".[n][uf 1 1][e]

[sel SEL_012_0_0 top]
[uf 0 5 65278][uf 2 1]Elas lembraram do meu nome...[e]
[uf 0 5 65278][uf 2 1]Cadê o seu?[e]
[uf 0 5 65278][uf 2 1]Obrigada.[e]

[msg MSG_013_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 18 0 0]Pois é, elas costumavam te chamar de "Treinadora" ou "Namorada", né?[n][uf 1 1][e]

[msg MSG_014_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 19 0 0][uf 5 13 12 5 106]Eu ganhei um também. Elas disseram que "nunca vão esquecer da Tia".[n][uf 1 1][e]

[msg MSG_015_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 20 0 0]Vou avisar pra elas que você gostou. Vão ficar superfelizes de saber.[n][uf 1 1][e]

[msg MSG_016_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 21 0 0]Quando você ganha algo assim depois, até esquece o quanto tudo foi difícil antes.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 22 0 0]Me dá até uma vontade de fazer tudo de novo. E você?[n][uf 1 1][e]

[sel SEL_017_0_0 top]
[uf 0 5 65278][uf 2 1]Se a oportunidade surgir.[e]
[uf 0 5 65278][uf 2 1]Só se você for também.[e]

[msg MSG_018_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 23 0 0][uf 5 13 12 15 106]É, tem razão.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 24 0 0][uf 4 23 0 106 0 25 25]Ah, mas eu gostaria que mais pessoas ajudassem da próxima vez. Foi bem difícil só com nós duas.[n][uf 1 1][e]

[msg MSG_019_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 25 0 0]Hã? Eu? É... Talvez eu queira mesmo.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 26 0 0]Mas, da próxima vez, a gente devia pedir ajuda pra mais pessoas. Foi bem difícil só com nós duas.[n][uf 1 1][e]

[msg MSG_020_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 27 0 0]Assim que terminar a escola, eu quero tirar um tempo pra pensar. Não só sobre treino, mas sobre aproveitar a vida também e tudo mais.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 28 0 0][uf 4 23 0 106 1 25 25]Hehe, mal posso esperar. Beleza, hora de meter a cara nos livros![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 29 0 0][uf 4 23 0 106 0 25 25]Ah, e não esquece de me contar se você descobrir o que quer fazer no futuro, tá bem?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 30 0 0]Se resolver fazer algo parecido, talvez a gente possa até estudar juntas![n][uf 1 1][e]

[msg MND_021_0_0]
[uf 0 5 65278][uf 2 1]Yuko e eu conversamos por um bom tempo.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Sinto que tenho um laço muito forte com a Yuko...[n][uf 1 1][e]

[msg SYS_021_5_0]
[uf 0 5 65278][uf 2 1]O Vínculo Social da Força chegou ao nível máximo![n]Agora você pode fundir [uf 0 1 35]Atavaka[uf 0 1 27], o Rei General da Sabedoria![n][uf 1 1][e]

[msg MSG_022_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 31 0 0]Ah, olha a hora. Preciso comprar alguns livros pra estudar.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 32 0 0]A gente se vê por aí, [uf 4 1]-chan.[n][uf 1 1][e]

[msg MND_023_0_0]
[uf 0 5 65278][uf 2 1]Depois de me despedir da Yuko,[n]decidi voltar para o dormitório.[n][uf 1 1][e]

[msg MSG_024_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 4 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]Foi mal pelo atraso![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 2 0 0][uf 4 23 0 106 0 25 25]Tava tirando dúvida com o professor sobre uma coisa que eu não tinha entendido na aula.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]Mas aí isso gerou ainda mais dúvidas, então eu acabei ficando presa lá por um tempo.[n][uf 1 1][e]

[msg MSG_025_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]Ugh, isso tá muito pesado. Eu não deveria ter jogado tudo aqui dentro...[n][uf 1 1][e]

[sel SEL_026_0_0 top]
[uf 0 5 65278][uf 2 1]Equipamento para a equipe?[e]
[uf 0 5 65278][uf 2 1]Quer que eu carregue?[e]

[msg MSG_027_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]Não, são só livros.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]Eu tinha tantas dúvidas pra tirar que acabei trazendo os livros de todas as disciplinas.[n][uf 1 1][e]

[msg MSG_028_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 7 0 0][uf 5 13 12 5 106]Não precisa, tá tranquilo! É só imaginar que estou fazendo musculação.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 8 0 0]Mesmo assim, não dá pra acreditar no quanto esses livros são pesados! Estudantes do mundo inteiro sofrem mesmo.[n][uf 1 1][e]

[msg MSG_029_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 0 0 0 9 0 0]...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]Eu fico tão nostálgica quando venho nesse campo...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 11 0 0]Nem faz tanto tempo assim que treinamos as crianças, né?[n][uf 1 1][e]

[sel SEL_030_0_0 top]
[uf 0 5 65278][uf 2 1]É porque foi muito gratificante.[e]
[uf 0 5 65278][uf 2 1]É a idade...[e]

[msg MSG_031_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 12 0 0][uf 5 13 12 5 106]Com certeza. Eu realmente tive que colocar corpo e cérebro pra trabalhar.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]Eu nunca precisei correr tanto, nem mesmo na equipe de atletismo.[n][uf 1 1][e]

[msg MSG_032_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]Ei! Não seja tão insensível![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 15 0 0]Você podia simplesmente dizer que eu cresci ou amadureci. Qual foi, pô![n][uf 1 1][e]

[msg MSG_033_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 16 0 0]Ah é, quase esqueci. Isso aqui é pra você.[n][uf 1 1][e]

[msg MND_034_0_0]
[uf 0 5 65278][uf 2 1]Eu obtive o item (ITEM NAME)![n][uf 1 1][e]

[msg MSG_035_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 49 0 0]É das crianças. Elas me pediram para "entregar isso à minha namorada".[n][uf 1 1][e]

[sel SEL_036_0_0 top]
[uf 0 5 65278][uf 2 1]Namorada...[e]
[uf 0 5 65278][uf 2 1]Cadê o seu?[e]
[uf 0 5 65278][uf 2 1]Que honra.[e]

[msg MSG_037_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 50 0 0]Eu já disse pra elas que não tem nada a ver, mas elas simplesmente não estão nem aí.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 51 0 0]Você e eu de casal... Crianças têm uma imaginação fértil mesmo.[n][uf 1 1][e]

[msg MSG_038_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 52 0 0][uf 5 13 12 5 106]Eu ganhei um também. Elas disseram que "nunca vão esquecer da Tia".[n][uf 1 1][e]

[msg MSG_039_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 53 0 0][uf 5 13 12 5 106]N-Nossa. Não achei que você reagiria assim...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 54 0 0]Quer dizer, isso não é meio incomum pra você?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 55 0 0][uf 4 23 0 106 1 25 25]De qualquer forma, vou avisar pra elas que você gostou. Vão ficar superfelizes de saber.[n][uf 1 1][e]

[msg MSG_040_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 56 0 0]Quando você ganha algo assim depois, até esquece o quanto tudo foi difícil antes.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 57 0 0]Me dá até uma vontade de fazer tudo de novo. E você?[n][uf 1 1][e]

[sel SEL_041_0_0 top]
[uf 0 5 65278][uf 2 1]Se a oportunidade surgir.[e]
[uf 0 5 65278][uf 2 1]Deixa eu pensar sobre isso.[e]

[msg MSG_042_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 58 0 0][uf 5 13 12 5 106]Hehe, bom saber.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 59 0 0][uf 4 23 0 106 0 25 25]Ah, e aproveitando o assunto, a gente devia convidar mais pessoas pra treinar junto da próxima vez![n][uf 1 1][e]

[msg MSG_043_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 0 0][uf 3 1 1 0 0 60 0 0]... Eu não sei se conseguiria dar conta sozinha, viu.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 61 0 0][uf 4 23 0 106 0 25 25]Já foi bem difícil só com nós duas... Talvez eu devesse chamar mais pessoas pra treinar com a gente da próxima vez.[n][uf 1 1][e]

[msg MSG_044_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 62 0 0]Assim que terminar a escola, eu quero tirar um tempo pra pensar. Não só sobre treino, mas sobre aproveitar a vida também e tudo mais.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 63 0 0][uf 4 23 0 106 1 25 25]Tomara que você possa me esperar até lá! Garanto que vou estudar bastante.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 64 0 0][uf 4 23 0 106 0 25 25]Ah, quase esqueci![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 65 0 0]Se eu conseguir me tornar uma treinadora esportiva...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 66 0 0]Meu primeiro trabalho vai ser montar uma rotina de treino pra você, [uf 4 1]-chan![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 67 0 0]Você provavelmente não vai virar atleta profissional, então eu vou tentar pegar mais leve.[n][uf 1 1][e]

[msg MND_045_0_0]
[uf 0 5 65278][uf 2 1]Yuko e eu conversamos por um bom tempo.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Sinto que tenho um laço muito forte com a Yuko...[n][uf 1 1][e]

[msg MSG_046_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 68 0 0]Ah, olha a hora! Preciso comprar alguns livros pra estudar![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 69 0 0]A gente se vê por aí, [uf 4 1]-chan.[n][uf 1 1][e]

[msg MND_047_0_0]
[uf 0 5 65278][uf 2 1]Depois de me despedir da Yuko,[n]decidi voltar para o dormitório.[n][uf 1 1][e]

