[msg MSG_000_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 65535 0 0][uf 3 1 1 0 0 1 0 0]Hola de nuevo.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 65535 0 0][uf 3 1 1 0 0 2 0 0]Bueno, ¿qué tal ha ido, [uf 4 1]?[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]Sin problemas.[e]
[uf 0 5 65278][uf 2 1]No sé yo...[e]
[uf 0 5 65278][uf 2 1]Estoy agotada.[e]

[msg MSG_002_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 51 65535 0 0][uf 3 1 1 0 0 3 0 0]Vale. Si habéis cogido confianza, es lo mejor que ha podido pasaros.[n][uf 1 1][e]

[msg MSG_003_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 65535 0 0][uf 3 1 1 0 0 4 0 0]No te desanimes.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 65535 0 0][uf 3 1 1 0 0 5 0 0]Habéis completado vuestra tarea. Podéis estar orgullosos.[n][uf 1 1][e]

[msg MSG_004_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 51 65535 0 0][uf 3 1 1 0 0 6 0 0]Estaréis todos igual.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 51 65535 0 0][uf 3 1 1 0 0 7 0 0]No os preocupéis, ya os acostumbraréis.[n][uf 1 1][e]

[msg MSG_005_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 51 65535 0 0][uf 3 1 1 0 0 8 0 0]Buah, ¡jamás me habría imaginado que tuviera semejante poder![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 51 65535 0 0][uf 3 1 1 0 0 9 0 0][uf 4 23 0 1 3 25 25]Joder, ¿por qué estoy tan cansado?[n][uf 1 1][e]

[msg MSG_006_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 51 65535 0 0][uf 3 1 1 0 0 10 0 0]Porque no parabas de dar saltos como un crío.[n][uf 1 1][e]

[msg MSG_007_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 51 65535 0 0][uf 3 1 1 0 0 11 0 0]Pues tú también tienes cara de cansada, Yuka.[n][uf 1 1][e]

[msg MSG_008_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 51 65535 0 0][uf 3 1 1 0 0 12 0 0]Lo mío es diferente. Parece que me cuesta respirar. ¿Qué está pasando?[n][uf 1 1][e]

[msg MSG_009_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 65535 0 0][uf 3 1 1 0 0 13 0 0]Es el efecto de la Hora Oscura, se nota la fatiga con más facilidad.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 65535 0 0][uf 3 1 1 0 0 14 0 0]No os preocupéis, ya os acostumbraréis.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 51 65535 0 0][uf 3 1 1 0 0 15 0 0]Aunque he de decir que me habéis sorprendido. Lo habéis hecho mucho mejor de lo que esperaba.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 51 65535 0 0][uf 3 1 1 0 0 16 0 0]A este paso, te alcanzarán enseguida, Akihiko.[n][uf 1 1][e]

[msg MSG_010_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 51 65535 0 0][uf 3 1 1 0 0 17 0 0]Je, ya veremos.[n][uf 1 1][e]

[msg MND_011_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]Al combinar mis poderes con los del equipo, he sido capaz de plantarles cara a las sombras.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Siento un fuerte vínculo con ellos...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]¡¿...?![n][uf 1 1][e]

[msg MND_012_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]Al igual que Yukari y Junpei, el cansancio se apodera de mí.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Decido que lo mejor será volver a mi habitación y descansar.[n][uf 1 1][e]

