[msg MSG_000_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1022 0 0]Cuando he subido al monorraíl esta mañana, estaba de los nervios.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0]No puedo dejar de pensar en lo cerca que estuvimos aquella vez...[n][uf 1 1][e]

[msg MSG_001_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1072 0 0]Hola, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0]¿Sabes? Esos rumores... me dan escalofríos.[n][uf 1 1][e]

[msg MSG_002_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1001 0 0]¿Has averiguado algo sobre los fantasmas?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 65535 65535 0 0]Quiero demostrarle a todo el mundo que no es más que un rumor.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0]No estoy asustada, ¡¿vale?![n][uf 1 1][e]

[msg MSG_003_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1072 0 0]Oye, [uf 4 1], no te olvides de lo de hoy, ¿eh?[n][uf 1 1][e]

[msg MSG_004_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0][uf 3 1 3 0 65535 1093 0 0]Parece que Yamagishi sigue durmiendo.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0]No puedo evitar preocuparme por ella.[n][uf 1 1][e]

[msg MSG_005_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 3 0 65535 1115 0 0]Yamagishi va a salir pronto del hospital. ¿No es fantástico?[n][uf 1 1][e]

[msg MSG_006_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1022 0 0]Me alegro de que no haya luna llena por un tiempo, pero aun así...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]No puedo evitar darle vueltas.[n][uf 1 1][e]

[msg MSG_007_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1028 0 0][uf 4 1]...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0]Aún no lo tengo claro... Me duele la cabeza cuando lo pienso.[n][uf 1 1][e]

[msg MSG_008_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1089 0 0]He pensado en todo, [uf 4 1]...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 65535 65535 0 0]Creo que no nos queda otra. Tenemos que hacerlo sí o sí.[n][uf 1 1][e]

[msg MSG_009_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1114 0 0]Ya casi es época de exámenes.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0]Los de tercero son muy listos, así que, como no saquemos buenas notas, se reirán de nosotros.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 65535 65535 0 0]Mm... Debería estudiar en la biblioteca. Acabo cansadísima cuando estudio por la noche...[n][uf 1 1][e]

[msg MSG_010_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 3 0 65535 1095 0 0]Uf... Por fin se han acabado los exámenes.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 11 65535 65535 0 0]Jolín, ¡qué mal lo hemos pasado! Ahora solo quiero descansar.[n][uf 1 1][e]

[msg MSG_011_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1067 0 0]Ah, [uf 4 1]. He visto tu nota.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0]Bueno, eh... Las notas no lo son todo en la vida, ¿verdad?[n][uf 1 1][e]

[msg MSG_012_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1067 0 0]Ah, [uf 4 1]. He visto tu nota.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0]Creo que no ha sido tu mejor examen. ¿Tenías un mal día?[n][uf 1 1][e]

[msg MSG_013_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1067 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0]He visto la nota de tu examen. Está bastante bien.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0]Seguro que Kirijo y Sanada se alegran.[n][uf 1 1][e]

[msg MSG_014_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1072 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0]He visto la nota de tu examen. ¡Ha sido de las mejores![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 11 65535 65535 0 0]Kirijo parecía impresionada. A lo mejor hasta te da alguna recompensa.[n][uf 1 1][e]

[msg MSG_015_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1072 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0]He visto la nota de tu examen. ¡Ha sido de las mejores![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 11 65535 65535 0 0]Mitsuru parecía impresionada. A lo mejor hasta te da alguna recompensa.[n][uf 1 1][e]

[msg MSG_016_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1073 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 65535 65535 0 0]He visto la nota de tu examen. ¡No me lo creo, estás en lo más alto![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 11 65535 65535 0 0]Seguro que Kirijo está impresionada. A lo mejor hasta te da alguna recompensa.[n][uf 1 1][e]

[msg MSG_017_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1073 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 65535 65535 0 0]He visto la nota de tu examen. ¡No me lo creo, estás en lo más alto![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 11 65535 65535 0 0]Seguro que Mitsuru está impresionada. A lo mejor hasta te da alguna recompensa.[n][uf 1 1][e]

[msg MSG_018_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1067 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1074 0 0]¿Has oído que el club de arte está reclutando nuevos miembros?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]Ahora que lo pienso, ¿Fuuka no estaba en el club de arte?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0]Tal vez deberías ir a echar un vistazo si te interesa para ver cómo funciona y todo eso.[n][uf 1 1][e]

[msg MSG_019_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1067 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1074 0 0]Me han dicho que te has unido al equipo de atletismo. Dicen que tienes mucho potencial.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0]Yo estoy en el club de tiro con arco. Esforcémonos al máximo, ¿vale?[n][uf 1 1][e]

[msg MSG_020_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1009 0 0]Hola, [uf 4 1]. ¿Te vas ya a casa?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]Por si te interesa, el equipo de atletismo está reclutando nuevos miembros.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0]Según dicen, tienen buena reputación. A lo mejor deberías ir a echar un vistazo.[n][uf 1 1][e]

[msg MSG_021_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1009 0 0]Vaya, qué casualidad. ¿Tú también has venido a comprar, [uf 4 1]?[n][uf 1 1][e]

[sel SEL_022_0_0 top]
[uf 0 5 65278][uf 2 1]Eso es.[e]
[uf 0 5 65278][uf 2 1]Estoy dando una vuelta.[e]

[msg MSG_023_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 3 0 65535 1095 0 0]Este centro comercial es muy práctico. Tiene casi de todo.[n][uf 1 1][e]

[msg MSG_024_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1025 0 0]Siempre viene bien familiarizarse con la ciudad.[n][uf 1 1][e]

[msg MSG_025_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1067 0 0]Ah, hola. ¿Qué haces aquí solo? Bueno, yo también estoy sola.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]Salir con amigos es genial y tal, pero pasar tiempo a solas también es importante.[n][uf 1 1][e]

[msg MSG_026_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1072 0 0]Hola, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 65535 65535 0 0][uf 3 1 3 0 65535 1119 0 0]Parece que el verano está en su máximo esplendor... Madre mía, qué calor hace.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]Las clases de verano empiezan mañana, ¡así que voy a aprovechar el poco tiempo libre que me queda para divertirme![n][uf 1 1][e]

[msg MSG_027_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1061 0 0]Estamos casi en mayo. En esta época es muy complicado escoger la ropa.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]A veces piensas que va a hacer calor y de repente hace frío.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]Por eso los uniformes son tan prácticos. Además, darles tu toque personal también puede ser muy divertido.[n][uf 1 1][e]

[msg MSG_028_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1001 0 0]Unused[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 11 65535 65535 0 0]¡Korocito es genial! Qué valiente fue el otro día. No sé cómo lo adiestraron, pero ¡es de lo mejor![n][uf 1 1][e]

[msg MSG_029_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 65535 65535 0 0][uf 3 1 3 0 65535 1119 0 0]Otro día caluroso... Si te quedas fuera un rato, podría darte un golpe de calor.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 65535 65535 0 0]Voy a darme prisa en hacer la compra para volver pronto a casa.[n][uf 1 1][e]

[msg MSG_030_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1001 0 0]Entonces, ¿ya has terminado todos los deberes?[n][uf 1 1][e]

[sel SEL_031_0_0 top]
[uf 0 5 65278][uf 2 1]Sí.[e]
[uf 0 5 65278][uf 2 1]No.[e]
[uf 0 5 65278][uf 2 1]¡Los he perdido![e]

[msg MSG_032_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 65535 65535 0 0][uf 3 1 3 0 65535 1107 0 0]¡Así se hace! Qué responsable eres, [uf 4 1].[n][uf 1 1][e]

[msg MSG_033_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 65535 65535 0 0][uf 3 1 3 0 65535 1110 0 0]Sip... Deberíamos hacerlos pronto. A mí también me queda mucho aún.[n][uf 1 1][e]

[msg MSG_034_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 65535 65535 0 0][uf 3 1 3 0 65535 1022 0 0]A la profesora no le va a valer esa excusa, ¿sabes? Tendrás que realizar otra tarea después de clase.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]Y si eso ocurre, no podrás ir a la torre Tártaro. Es mejor hacerlos ahora.[n][uf 1 1][e]

[msg MSG_035_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1075 0 0]Voy a ir a ver una peli con una amiga. La estrenan hoy en el cine.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0]Pero llega tarde. Mmm, ¿dónde se habrá metido?[n][uf 1 1][e]

[msg MSG_036_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1062 0 0]Quería comprarme un bañador nuevo, pero no había ninguno que me gustase.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0]Me pregunto por qué. La verdad es que había un buen surtido.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0]Tal vez no esté de humor para ir de tiendas.[n][uf 1 1][e]

[msg MSG_037_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1061 0 0]Unused[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]No sé cómo explicarlo, pero ¿te has dado cuenta de que Sanada se comporta de forma distinta cuando está cerca de Amada?[n][uf 1 1][e]

[sel SEL_038_0_0 top]
[uf 0 5 65278][uf 2 1]Unused[e]
[uf 0 5 65278][uf 2 1]Más o menos. No tenía ni idea.[e]

[msg MSG_039_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1062 0 0]Unused[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]¿Por qué será? A lo mejor no le gustan los niños. No parece que tenga mucho don de gentes.[n][uf 1 1][e]

[msg MSG_040_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 65535 65535 0 0][uf 3 1 3 0 65535 1022 0 0]Unused[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]¿Tú no te das cuenta de esas cosas? Bueno, me pregunto por qué será... Nunca lo he visto así.[n][uf 1 1][e]

[msg MSG_041_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 3 0 65535 1078 0 0]Ah, [uf 4 1]. Te presento a Amada.[n][uf 1 1][e]

[msg MSG_042_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]Encantado de conocerte. Me llamo Ken Amada.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]¿Te llevas bien con Yukari y Junpei?[n][uf 1 1][e]

[msg MSG_043_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0]Sí, la mar de bien.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0]Los tres vivimos en la misma residencia.[n][uf 1 1][e]

[msg MSG_044_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 4 65535 65535 0 0]¿De veras? No sabía que los chicos y las chicas podían vivir juntos.[n][uf 1 1][e]

[msg MSG_045_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 1]Mmm, eeeh, bueno... Es que...[n][uf 1 1][e]

[msg MSG_046_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0]¡Somos especiales! Tenemos motivos de peso para vivir juntos.[n][uf 1 1][e]

[msg MSG_047_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 65535 65535 0 0]Ajá...[n][uf 1 1][e]

[msg MSG_048_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 3 0 65535 1131 0 0]Últimamente, he hablado mucho con Amada.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0]Me sorprende que sea tan digno de confianza. Y es mucho más maduro que Tontei.[n][uf 1 1][e]

[msg MSG_049_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1009 0 0]Ah, hola, [uf 4 1].[n][uf 1 1][e]

[msg MSG_050_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]Hola, [uf 4 1].[n][uf 1 1][e]

[msg MSG_051_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]Estaba hablando con Amada otra vez. ¿Tú también has venido a hacerle una visita?[n][uf 1 1][e]

[sel SEL_052_0_0 top]
[uf 0 5 65278][uf 2 1]Eso es.[e]
[uf 0 5 65278][uf 2 1]He venido a verte, Yukari.[e]

[msg MSG_053_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 11 65535 65535 0 0][uf 3 1 3 0 65535 1132 0 0]Oye, ¿no es fantástico, Amada? [uf 4 1] también quiere ser tu amigo.[n][uf 1 1][e]

[msg MSG_054_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0]¡Gracias por pasarte a verme![n][uf 1 1][e]

[msg MSG_055_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 65535 65535 0 0][uf 3 1 3 0 65535 1052 0 0]¿Yo? Pero si nos vemos todos los días en la residencia.[n][uf 1 1][e]

[msg MSG_056_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 65535 65535 0 0][uf 3 1 3 0 65535 1142 0 0]Ahí está Tontei de nuevo, siendo una mala influencia. A veces es como un crío...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]Aunque es cierto que no está mal hacer este tipo de cosas de vez en cuando.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0]Tengamos una actitud positiva y esperemos lo mejor.[n][uf 1 1][e]

[msg MND_GENERAL_EVENTPLAY]
[uf 0 5 65278][uf 2 1]Mensaje enviado por el guion. Repetición del evento del comité.[n][uf 1 1][e]

[msg MND_GENERAL_PERSPNA]
[uf 0 5 65278][uf 2 1]Siento que podemos estrechar lazos gracias a la Persona del arcano [uf 2 4 2], [uf 0 1 35][uf 2 4 5][uf 0 1 27].[n][uf 1 1][e]

[msg MND_GENERALSELECTMSG_MAX]
[uf 0 5 65278][uf 2 1]Siento un vínculo irrompible con [uf 2 4 0]...[n][uf 1 1][e]

[msg MND_GENERALMSG_BS_MAX]
[uf 0 5 65278][uf 2 1]Siento un vínculo irrompible con la pareja de ancianos...[n][uf 1 1][e]

[msg MND_GENERALSELECTMSG_RAN]
[uf 0 5 65278][uf 2 1]Creo que mi relación con [uf 2 4 0] se estrechará pronto.[n][uf 1 1][e]

[msg MND_GENERALMSG_BS_RANKUP]
[uf 0 5 65278][uf 2 1]Creo que mi relación con la pareja de ancianos se estrechará pronto.[n][uf 1 1][e]

[msg MND_GENERALSELECTMSG_NOR]
[uf 0 5 65278][uf 2 1]No creo que mi vínculo con [uf 2 4 0] se fortalezca más aunque pasemos tiempo juntos...[n][uf 1 1][e]

[msg MND_GENERALMSG_BS_NORMAL [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]No creo que nuestro vínculo se fortalezca más aunque pasemos tiempo juntos.[n][uf 1 1][e]

[msg MND_GENERALSELECTMSG_MAX_2]
[uf 0 5 65278][uf 2 1]Parece que tu relación no puede avanzar más...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]¿Deberíamos pasar el rato juntos igualmente?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_SOLO_AS]
[uf 0 5 65278][uf 2 1]¿Paso un rato con [uf 2 4 0] después de clase?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_SOLO_DT]
[uf 0 5 65278][uf 2 1]¿Debería pasar el día con [uf 2 4 0]?[n][uf 1 1][e]

[msg MND__GENERAL_MSG_NET]
[uf 0 5 65278][uf 2 1]¿Debería pasar tiempo en línea jugando al MMORPG con [uf 2 4 0]?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_SOLO_NT]
[uf 0 5 65278][uf 2 1]¿Debería pasar la tarde con [uf 2 4 0]...?[n][uf 1 1][e]

[sel SEL_GENERALSELECTMSG_SOL top]
[uf 0 5 65278][uf 2 1]Pasar tiempo con [uf 2 4 0][e]
[uf 0 5 65278][uf 2 1]Comprobar vínculo social[e]
[uf 0 5 65278][uf 2 1]Da igual[e]

[msg MND_GENERAL_MSG_MULTIPLE]
[uf 0 5 65278][uf 2 1]¿Paso un rato en [uf 2 4 1] después de clase?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_FASHION_]
[uf 0 5 65278][uf 2 1]¿Paso un rato en el club de moda después de clase?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_BOOKSTOR]
[uf 0 5 65278][uf 2 1]¿Debería pasar el día en la librería?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_BOOKSTOR_2]
[uf 0 5 65278][uf 2 1]¿Paso un rato en la librería después de clase?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_MULTIPLE_2]
[uf 0 5 65278][uf 2 1]¿Debería pasar tiempo con [uf 2 4 1] esta noche...?[n][uf 1 1][e]

[sel SEL_GENERALSELECTMSG_MUL top]
[uf 0 5 65278][uf 2 1]Pasar un rato: [uf 2 4 1][e]
[uf 0 5 65278][uf 2 1]Comprobar vínculo social[e]
[uf 0 5 65278][uf 2 1]Da igual[e]

[sel SEL_GENERALSELECTMSG_FCL top]
[uf 0 5 65278][uf 2 1]Ir al club de moda.[e]
[uf 0 5 65278][uf 2 1]Comprobar vínculo social[e]
[uf 0 5 65278][uf 2 1]Da igual[e]

[sel SEL_GENERALSELECTMSG_BS top]
[uf 0 5 65278][uf 2 1]Entrar en la librería[e]
[uf 0 5 65278][uf 2 1]Comprobar vínculo social[e]
[uf 0 5 65278][uf 2 1]Da igual[e]

[msg MSG_GENERAL_EXAMREWARD_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]He visto tus notas. Buen trabajo.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Toma, de parte del director.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4108 0 0]Es tu recompensa por ser capaz de compaginar los estudios y nuestras... en fin, "actividades extraescolares".[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_0]
[uf 0 5 65278][uf 2 1]DEV: UNUSED LABEL[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_0_2]
[uf 0 5 65278][uf 2 1]Como he sacado la nota más alta en los exámenes, he obtenido: [uf 4 4 1 37 1 3].[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_0_2 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]He visto tus notas. Buen trabajo.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Toma, de parte del director.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4108 0 0]Es tu recompensa por ser capaz de compaginar los estudios y nuestras... en fin, "actividades extraescolares".[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_0_3 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4077 0 0]Ah, cierto. Hay algo más.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]He visto tus notas. Buen trabajo.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Toma, de parte del director.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4131 0 0]Es tu recompensa por ser capaz de compaginar los estudios y nuestras... en fin, "actividades extraescolares".[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_0_3]
[uf 0 5 65278][uf 2 1]Como he sacado la nota más alta en los exámenes, he obtenido: [uf 4 4 1 37 1 3].[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_0_4 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]He visto tus notas. Buen trabajo.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Toma, de parte del director.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4108 0 0]Es tu recompensa por ser capaz de compaginar los estudios y nuestras... en fin, "actividades extraescolares".[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_0_4]
[uf 0 5 65278][uf 2 1]DEV: UNUSED LABEL[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_0_5 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]He visto tus notas... Buen trabajo.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Es laudable que continúes destacando en el instituto mientras libras arduos combates.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0]Acepta este regalo para agradecerte tus esfuerzos.[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_0_5]
[uf 0 5 65278][uf 2 1]未使用ラベルです。[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_0_6 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0]He visto tus notas. Buen trabajo.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0]Es laudable que continúes destacando en el instituto mientras libras arduos combates.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0]Acepta este regalo para agradecerte tus esfuerzos.[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_1]
[uf 0 5 65278][uf 2 1]Como he sacado la nota más alta en los exámenes, he obtenido: [uf 4 4 1 37 1 3].[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_1 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]He visto tus notas. Buen trabajo.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Es laudable que continúes destacando en el instituto mientras libras arduos combates.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4108 0 0]Acepta este regalo para agradecerte tus esfuerzos.[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_1_2]
[uf 0 5 65278][uf 2 1]DEV: UNUSED LABEL[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_1_3]
[uf 0 5 65278][uf 2 1]Como he sacado la nota más alta en los exámenes, he obtenido: [uf 4 4 1 37 1 3].[n][uf 1 1][e]

