[msg MSG_000_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 1 65535 65535 0 0][uf 3 1 1 0 0 1 0 0][uf 4 23 0 1 1 25 25]Heeey, [uf 4 2]-chan![n][uf 1 1][e]

[msg MSG_001_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 1 65535 65535 0 0][uf 3 1 1 0 0 2 0 0][uf 4 23 0 1 1 25 25]I did it! I finally met my quota! I found someone else to welcome into our flock![n][uf 1 1][e]

[msg MSG_001_5_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 1 65535 65535 0 0][uf 3 1 1 0 0 3 0 0][uf 4 23 0 1 1 25 25]...Oh! Speak of the devil![n][uf 1 1][e]

[msg MSG_002_0_0 [Familiar Young Man]]
[uf 0 5 65278][uf 2 1][uf 3 1 0 0 0 4 0 0]......[n][uf 1 1][e]

[msg MSG_003_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 1 65535 65535 0 0][uf 3 1 1 0 0 5 0 0][uf 4 23 0 1 1 25 25]Oh, wow! Are you interested in joining, too!?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 4 65535 65535 0 0][uf 3 1 1 0 0 6 0 0][uf 4 23 0 1 4 25 25]Finally, Paradise is smiling back at me! Yes! Yesss![n][uf 1 1][e]

[sel SEL_004_0_0 top]
[uf 0 5 65278][uf 2 1]You're gonna scam them, too?[e]
[uf 0 5 65278][uf 2 1]Just knock it off.[e]

[msg MSG_005_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 3 65535 65535 0 0][uf 3 1 1 0 0 7 0 0][uf 4 23 0 1 3 25 25]"Scam"? I don't know what you're talking about...[n][uf 1 1][e]

[msg MSG_006_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 2 65535 65535 0 0][uf 3 1 1 0 0 8 0 0][uf 4 23 0 1 2 25 25]I'm trying to save these people! They've suffered in this world, just like me![n][uf 1 1][e]

[msg MSG_007_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 3 65535 65535 0 0][uf 3 1 1 0 0 9 0 0][uf 4 23 0 1 3 25 25]Wh-What are you saying? That I should just abandon these people to their fate!?[n][uf 1 1][e]

[msg MSG_008_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 2 65535 65535 0 0][uf 3 1 1 0 0 10 0 0][uf 4 23 0 1 2 25 25]I'm trying to save these people! They've suffered in this world, just like me![n][uf 1 1][e]

[msg MSG_009_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 2 65535 65535 0 0][uf 3 1 1 0 0 11 0 0][uf 4 23 0 1 2 25 25]Someone as good-looking as you could never understand! You have no idea what people like me have to go through...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 2 65535 65535 0 1][uf 3 1 1 0 0 12 0 0][uf 4 23 0 1 2 25 25]Fine. If you're gonna try and stop me... then... then you and I are through![n][uf 1 1][e]

[msg MSG_010_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 3 65535 65535 0 0][uf 3 1 1 0 0 13 0 0][uf 4 23 0 1 3 25 25]Don't follow me around anymore! Only true believers are allowed into Paradise![n][uf 1 1][e]

[msg MND_011_0_0]
[uf 0 5 65278][uf 2 1]That new recruit seemed familiar...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I'm worried about Suemitsu.[n]I better follow him.[n][uf 1 1][e]

