[msg MSG_JUNPEI_TARTAROS_0102 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]Oye, vamos a la torre Tártaro. Empecemos el año fuerte, ¿eh?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]Que si nos lo tomamos sin más, me podría más nervioso si cupiera.[n][uf 1 1][e]

[msg MSG_JUNPEI_0102 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]Oye, ¿te hace ir luego a la torre Tártaro?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0]Venga, ¡que ya llevamos dos días en lo que va de año! ¡No podemos quedarnos parados todo el año![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0]En fin, ya fuera de coñas, empecemos fuerte este año, ¿vale?[n][uf 1 1][e]

[msg MSG_JUNPEI_OK_0102 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]Siento que el ponerse cómodo para intentar relajarse, como que ya no relaja mucho, ¿sabes?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0]Pero parece que hemos empezado el año con buen pie. ¿Quizá sea señal de lo que nos depara?[n][uf 1 1][e]

[msg MSG_YUKARI_TARTAROS_0104 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]Estos días he estado viendo muchos grafitis y pósters raros por la calle...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]Y hay mucha gente actuando de forma extraña. Me pregunto si todo esto estará relacionado con Nix...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]Venga, vamos a la torre Tártaro, que el mes se nos va a pasar volando a este ritmo.[n][uf 1 1][e]

[msg MSG_YUKARI_0104 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]Estos días he estado viendo muchos grafitis y pósters raros por la calle...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]Y hay mucha gente actuando de forma extraña. Me pregunto si todo esto estará relacionado con Nix...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]Oye, ¿y si volvemos a la torre Tártaro? Deberíamos entrenar todo lo que podamos.[n][uf 1 1][e]

[msg MSG_YUKARI_OK_0104 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]Estos días he estado viendo muchos grafitis y pósters raros por la calle...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]Me da muy mal rollo...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]Y hay mucha gente actuando de forma extraña. Me pregunto si todo esto estará relacionado con Nix...[n][uf 1 1][e]

[msg MSG_MITURU_TARTAROS_0106 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 4 1], ¿qué tal si vamos a la torre Tártaro esta noche?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Al contrario que a finales del año pasado, esta vez tenemos una meta clara, llegar a la cima de la Tártaro.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]No podemos aflojar antes de siquiera llegar hasta Nix.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Tenemos que ir con todo lo que tengamos.[n][uf 1 1][e]

[msg MSG_MITURU_0106 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 4 1], ¿qué tal si volvemos a la torre Tártaro esta noche?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Nuestro deber es derrotar a Nix.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Para esta misión en particular, no creo que "prepararse demasiado" sea motivo de preocuparse.[n][uf 1 1][e]

[msg MSG_FUKA_TARTAROS_0108 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]El instituto se siente diferente al año pasado. El ambiente es raro, ¿no crees?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Muchos alumnos en mi clase estaban hablando de sectas y otras cosas extrañas...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Imagino que todo esto se relaciona con la llegada de Nix...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5077 0 0]...En fin, avísame si quieres ir a la torre Tártaro.[n][uf 1 1][e]

[msg MSG_FUKA_0108 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]El instituto se siente diferente al año pasado. El ambiente es raro, ¿no crees?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Muchos alumnos en mi clase estaban hablando de sectas y otras cosas extrañas...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Imagino que todo esto se relaciona con la llegada de Nix...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5077 0 0]...En fin, avísame si quieres ir a la torre Tártaro. Haré lo imposible por tratar de ayudar.[n][uf 1 1][e]

[msg MSG_FUKA_OK_0108 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]El instituto se siente diferente al año pasado. El ambiente es raro, ¿no crees?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Muchos alumnos en mi clase estaban hablando de sectas y otras cosas extrañas...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Imagino que todo esto se relaciona con la llegada de Nix...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5025 0 0]...No podemos perder. ¡Superaremos el Día de la Promesa![n][uf 1 1][e]

[msg MSG_SANADA_TARTAROS_0109 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Quedan tres semanas para cierto día.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]El destino del mundo entero... No voy a preocuparme por eso ahora.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]En estos momentos voy a centrarme en seguir adelante.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3061 0 0]Así que dime cuando vayas a ir a la torre Tártaro.[n][uf 1 1][e]

[msg MSG_SANADA_0109 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Quedan tres semanas para cierto día.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]El destino del mundo entero... No voy a preocuparme por eso ahora.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Ahora mismo estoy centrado en el asalto final.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3061 0 0]Si quieres hacerte más fuerte, me gustaría ser tu compañero de entrenamiento.[n][uf 1 1][e]

[msg MSG_SANADA_OK_0109 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Quedan tres semanas para cierto día.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]El destino del mundo entero... No voy a preocuparme por eso ahora.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]En estos momentos voy a centrarme en seguir adelante.[n][uf 1 1][e]

[msg MSG_AMADA_TARTAROS_0111 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]Hoy es el Día de la Mayoría de Edad.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]No quiero que mi vida se acabe antes de convertirme en adulto.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]Esto... Me gustaría ir a la torre Tártaro esta noche.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]No puedo quedarme quieto y ver cómo se acaba el mundo...[n][uf 1 1][e]

[msg MSG_AMADA_0111 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]Hoy es el Día de la Mayoría de Edad.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]No quiero que mi vida se acabe antes de convertirme en adulto.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]Así que... sigámonos haciéndonos más fuertes hasta la batalla final.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]No puedo quedarme quieto y ver cómo se acaba el mundo...[n][uf 1 1][e]

[msg MSG_AMADA_OK_0111 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]Hoy es el Día de la Mayoría de Edad.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]No quiero que mi vida se acabe antes de convertirme en adulto.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]...Asegurémonos de que vamos a ganar, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]Para luego poder volver aquí, todos juntos, como siempre...[n][uf 1 1][e]

[msg MSG_HUKA_TARTAROS_0113 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Estamos casi a mediados de enero.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Hoy es 13, por lo que nos quedan dieciocho días más.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 65535 0 0]Em, [uf 4 1]... ¿Y si vamos hoy a la torre Tártaro?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 65535 0 0]Creo que lo mejor que podemos hacer ahora es darlo todo, incluso aunque nos cueste un poquito.[n][uf 1 1][e]

[msg MSG_HUKA_0113 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Estamos casi a mediados de enero.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Hoy es 13, por lo que nos quedan dieciocho días más.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 65535 0 0]Em, [uf 4 1]... ¿Y si vamos hoy también a la torre Tártaro?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 65535 0 0]Creo que deberíamos aprovechar lo que nos queda de tiempo para hacernos lo más fuerte que podamos.[n][uf 1 1][e]

[msg MSG_HUKA_OK_0113 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Estamos casi a mediados de enero.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Hoy es 13, por lo que nos quedan dieciocho días más.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Siendo sincera, seguía estando nerviosa hasta hace poco.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0]Pero ya no siento esos nervios. Sé que estaremos bien.[n][uf 1 1][e]

[msg MSG_AEGIS_TARTAROS_0115 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]Oye... ¿Por qué no vamos esta noche a la torre Tártaro?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]Siento que ha pasado bastante tiempo desde la última vez que sugerí yo de ir.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 65535 65535 0 0]Desde que me dieron el alta del laboratorio tras mis reparaciones, me sentía muy confusa...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]Pero ya no me siento confusa.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6003 0 0]Quiero estar a tu lado... y luchar junto a ti.[n][uf 1 1][e]

[msg MSG_AEGIS_OK_0115 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]El tiempo parece que pasa muy rápido últimamente. Estamos ya a la mitad de enero...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6003 0 0][uf 4 2]... No volveré a dudar.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]Sé lo que quiero hacer... Quiero luchar de tu lado.[n][uf 1 1][e]

[msg MSG_YUKARI_TARTAROS_0116 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]Mitsuru y Sanada han ido hoy a hacer sus exámenes de admisión.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0]Y mañana van a volver. ¿Cómo pueden concentrarse con todo lo que está pasando?[n][uf 1 1][e]

[msg MSG_SANADA_TARTAROS_0116 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3031 0 0]¿Cómo no me voy a concentrar? Ni mucho menos pienso rendirme.[n][uf 1 1][e]

[msg MSG_MITURU_TARTAROS_0116 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4130 0 0]Se podría decir que estamos desafiando al destino.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0]Pero quiero asegurarme de que estoy haciendo todo lo que está en mis manos.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0]Lo que viene a ser, yo tampoco voy a rendirme.[n][uf 1 1][e]

[msg MSG_SANADA_TARTAROS_0116_2 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3074 0 0]Por cierto, si vas a la torre Tártaro, voy contigo.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0]La batalla final es en un par de semanas. No voy a dejar el entrenamiento por un mero examen.[n][uf 1 1][e]

[msg MSG_YUKARI_TARTAROS_0116_2 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0][uf 3 1 3 0 65535 1110 0 0]Uf... no sé cómo voy a seguir el ritmo... pero por lo menos no pienso rendirme tampoco.[n][uf 1 1][e]

[msg MSG_KOROMARU_TARTAROS_01 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 3 0 65535 8008 0 0]¡Guau![n][uf 1 1][e]

[msg MSG_AEGIS_TARTAROS_0119 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 3 0 65535 6025 0 0]Parece que dice, "Vayamos hoy a la torre Tártaro."[n][uf 1 1][e]

[msg MSG_KOROMARU_OK_0119 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 3 0 65535 8008 0 0]¡Guau![n][uf 1 1][e]

[msg MSG_AEGIS_OK_0119 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 3 0 65535 6025 0 0]Parece que dice, "Vamos a ganar."[n][uf 1 1][e]

[msg MSG_FUKA_TARTAROS_0119 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 3 0 65535 5116 0 0]Sí, bien dicho. ¡Vamos a ganar juntos![n][uf 1 1][e]

[msg MSG_JUNPEI_TARTAROS_0120 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]Oye, vamos a la torre Tártaro esta noche.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]Quedan diez días sin contar hoy, ¡tenemos que entrar en calor![n][uf 1 1][e]

[msg MSG_JUNPEI_0120 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]Oye, vamos a la torre Tártaro esta noche.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]Quedan diez días sin contar hoy. Quiero entrenar un poco más, por si acaso, ¿sabes?[n][uf 1 1][e]

[sel SEL_081_0_0 top]
[uf 0 5 65278][uf 2 1]Me lo pensaré.[e]
[uf 0 5 65278][uf 2 1]No nos pasemos.[e]

[msg MSG_JUNPEI_0120_2 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 3 0 65535 2009 0 0]Guay. ¡Estoy listo para ir cuando tú lo estés![n][uf 1 1][e]

[msg MSG_JUNPEI_0120_3 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 3 0 65535 2036 0 0]¡Venga ya, tía! ¿Sabes qué es mejor que ser fuerte? ¡Ser demasiado fuerte![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0]Me refiero, cualquiera puede ser fuerte. Pero nosotros somos los héroes, ¡tenemos que ser fuertes fuertes![n][uf 1 1][e]

[msg MSG_JUNPEI_OK_0120 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]Sin contar hoy, son diez días hasta el día del que Ryoji nos hablaba, ¿eh?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0]Va, ¡estoy que me salgo! ¡Vamos a reventar a esa tal Nix![n][uf 1 1][e]

[msg MSG_SANADA_TARTAROS_0124 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Solo queda una semana hasta el 31.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Quizá ya te lo imaginabas, pero por si acaso te lo digo...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 0 1 2]Una vez entremos en la Tártaro el 31 de enero, no podremos salir hasta que termine la batalla.[uf 0 1 27][n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Perder no es una opción, así que utiliza esta última semana con cabeza.[n][uf 1 1][e]

[msg MSG_FUKA_TARTAROS_0125_1 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Hoy puede ser nuestro último lunes...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 65535 0 0]Si no ganamos, no habrá más...[n][uf 1 1][e]

[msg MSG_AEGIS_TARTAROS_0125_ [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 3 0 65535 6034 0 0]Todo saldrá bien.[n][uf 1 1][e]

[msg MSG_FUKA_TARTAROS_0125_2 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 65535 0 0][uf 3 1 3 0 65535 5092 0 0]¿Aigis?[n][uf 1 1][e]

[msg MSG_AEGIS_TARTAROS_0125__2 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6076 0 0]Vamos a ganar.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]Tenemos que ganar...[n][uf 1 1][e]

[msg MSG_YUKARI_TARTAROS_0125 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 3 0 65535 1131 0 0]Aigis...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]Eso es. No podemos seguir dudando de nosotros, ni siquiera un poco. Vamos a ganar, sí o sí.[n][uf 1 1][e]

[msg MSG_YUKARI_TARTAROS_0126 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]Quedan cinco días para el Día de la Promesa...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0]Pero vamos a romper esa "promesa".[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0]Oye, ¿vamos a la Tártaro más tarde? Estoy sintiéndome algo inquieta, ¡así que vamos allá![n][uf 1 1][e]

[msg MSG_YUKARI_OK_0126 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]Quedan cinco días para el Día de la Promesa...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]Pero vamos a romper esa "promesa".[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0]...Intento no sobrepensarlo demasiado pero, a veces cuesta, ¿me entiendes?[n][uf 1 1][e]

[msg MSG_SANADA_TARTAROS_0127 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Cuatro días más... Puedo sentir a Nix prácticamente respirando sobre mi cuello.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Dime cuando vayas a ir a la Tártaro, aunque sea todas y cada una de las noches.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Hemos llegado muy lejos... Nada es más importante que esto.[n][uf 1 1][e]

[msg MSG_SANADA_0127 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Cuatro días más... Puedo sentir a Nix prácticamente respirando sobre mi cuello.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Avísame cuando vayas a ir a la Tártaro. Quiero empujarme hasta mis límites.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Hemos llegado muy lejos... Nada es más importante que esto.[n][uf 1 1][e]

[msg MSG_SANADA_OK_0127 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Cuatro días más... Puedo sentir a Nix prácticamente respirando sobre mi cuello.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Prepárate en todos los aspectos, no te arrepientas de nada. Yo también me estoy preparando a mi manera.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Hemos llegado muy lejos... Nada es más importante que esto.[n][uf 1 1][e]

[msg MSG_JUNPEI_TARTAROS_0128 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]Tío, solo quedan tres días. En parte tengo muchas ganas y en parte... no tantas.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]En fin, ¿te hace ir luego a la torre Tártaro? Estos músculos no se cuidan solitos, ¿sabes?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0]Bueno, total. Te lo dejo en tus manos.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0]Después de todo lo que hemos pasado, confío plenamente en ti, tía.[n][uf 1 1][e]

[msg MSG_JUNPEI_0128 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]Tío, solo quedan tres días. En parte tengo muchas ganas y en parte... no tantas.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]Y tú, ¿en qué piensas? ¿Vamos hoy a la torre Tártaro a entrenar un pelín más?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0]Bueno, la decisión está en tus manos. Sé que nos guiarás por el camino correcto, como siempre.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0]¡Así que todo tuyo, líder![n][uf 1 1][e]

[msg MSG_JUNPEI_OK_0128 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]Tío, solo quedan tres días. En parte tengo muchas ganas y en parte... no tantas.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0]Escucha... Sé que te he dado mucho el coñazo, pero estoy contigo al cien por cien.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0]¡Vamos a darle caña a la Nix! ¿Qué me dices, líder?[n][uf 1 1][e]

[msg MSG_MITURU_TARTAROS_0129 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Quedan solamente dos días...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]El ambiente afuera se nota frío y deprimente, no te culparía si te sientes aún más deprimida en estos momentos. [n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0]Pero todavía tenemos que aguantar un poquito más. En nada llega la primavera, como se suele decir.[n][uf 1 1][e]

[msg MSG_AEGIS_TARTAROS_0130 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]Ya casi es la hora.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]Han pasado diez años desde que la "Muerte" ha despertado...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]Y mañana, por fin, llega el Día de la Promesa.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6059 0 0][uf 0 1 2]Una vez entremos mañana en la torre Tártaro, no podremos salir.[uf 0 1 27][n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]¿...Estás lista?[n][uf 1 1][e]

[msg MSG_WELCOME_YUKARI_OUT [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1019 0 0]Ah, eh... Hola.[n][uf 1 1][e]

[msg MSG_WELCOME_YUKARI_OUT2 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1012 0 0]Eh... Hola...[n][uf 1 1][e]

[msg MSG_WELCOME_JUNPEI_OUT [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 3 0 65535 2018 0 0]¿Qué pasa, tía?[n][uf 1 1][e]

[msg MSG_WELCOME_JUNPEI_OUT2 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 3 0 65535 2012 0 0]Hola, tía...[n][uf 1 1][e]

[msg MSG_WELCOME_MITSURU_OUT [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4018 0 0]Hola de nuevo.[n][uf 1 1][e]

[msg MSG_WELCOME_MITSURU_OUT2 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4027 0 0]Hola de nuevo...[n][uf 1 1][e]

[msg MSG_WELCOME_SANADA_OUT [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3017 0 0]Anda, has vuelto.[n][uf 1 1][e]

[msg MSG_WELCOME_FUKA_OUT [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5018 0 0]Hola, ¿qué tal el día?[n][uf 1 1][e]

[msg MSG_WELCOME_FUKA_OUT2 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5028 0 0]Ah... Hola...[n][uf 1 1][e]

[msg MSG_WELCOME_AEGIS_OUT_RO [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 3 0 65535 6018 0 0]Saludos.[n][uf 1 1][e]

[msg MSG_WELCOME_AEGIS_OUT [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6018 0 0]Saludos.[n][uf 1 1][e]

[msg MSG_WELCOME_AEGIS_OUT_NA [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6017 0 0]Hola otra vez. Me alegro de volver a verte.[n][uf 1 1][e]

[msg MSG_WELCOME_KOROMARU_OUT [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 3 0 65535 8008 0 0]¡Guau![n][uf 1 1][e]

[msg MSG_WELCOME_AMADA_OUT [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7020 0 0]¡Anda, hola![n][uf 1 1][e]

[msg MSG_WELCOME_AMADA_OUT2 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7012 0 0]Ah... Hola...[n][uf 1 1][e]

[msg MSG_WELCOME_ARAGAKI_OUT [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0][uf 3 1 3 0 65535 9014 0 0]Ey...[n][uf 1 1][e]

[msg MSG_WELCOME_IKUTSUKI_OUT [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 3 0 65535 14201 0 0]Hola de nuevo.[n][uf 1 1][e]

[msg MSG_WELCOME_YUKARI_IN [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1067 0 0]¡Ah, estás aquí![n][uf 1 1][e]

[msg MSG_WELCOME_YUKARI_IN2 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1012 0 0]Ah, ¿ya has llegado? Perdona, no te había visto.[n][uf 1 1][e]

[msg MSG_WELCOME_JUNPEI_IN [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 3 0 65535 2009 0 0]Eh, ¿qué pasa?[n][uf 1 1][e]

[msg MSG_WELCOME_JUNPEI_IN2 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 3 0 65535 2012 0 0]Ah, hola...[n][uf 1 1][e]

[msg MSG_WELCOME_MITSURU_IN [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]¿Eh? Ah, eres tú...[n][uf 1 1][e]

[msg MSG_WELCOME_MITSURU_IN2 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4027 0 0]¿Mmm? Ah, ya estás aquí.[n][uf 1 1][e]

[msg MSG_WELCOME_SANADA_IN [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3024 0 0]¿Has estado en tu habitación todo este tiempo?[n][uf 1 1][e]

[msg MSG_WELCOME_FUKA_IN [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5067 0 0]¡Ah, hola! No sabía que ya estabas aquí.[n][uf 1 1][e]

[msg MSG_WELCOME_FUKA_IN2 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5093 0 0]Anda, ¿estás aquí? Hola...[n][uf 1 1][e]

[msg MSG_WELCOME_FUKA_IN_0712 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5067 0 0]Ah, [uf 4 1]...[n][uf 1 1][e]

[msg MSG_WELCOME_AEGIS_IN_ROB [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 3 0 65535 6008 0 0]Buenas tardes.[n][uf 1 1][e]

[msg MSG_WELCOME_AEGIS_IN [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6008 0 0]Buenas tardes.[n][uf 1 1][e]

[msg MSG_WELCOME_AEGIS_IN_NAK [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6009 0 0]¿Qué tal el día? ¿Todo bien?[n][uf 1 1][e]

[msg MSG_WELCOME_KOROMARU_IN [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 3 0 65535 8001 0 0]¡Guau, guau![n][uf 1 1][e]

[msg MSG_WELCOME_AMADA_IN [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7010 0 0]¿Has estudiado algo?[n][uf 1 1][e]

[msg MSG_WELCOME_AMADA_IN2 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7012 0 0]¿Estabas aquí? Pues... hola.[n][uf 1 1][e]

[msg MSG_WELCOME_ARAGAKI_IN [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0][uf 3 1 3 0 65535 9056 0 0]... ¿Qué hay?[n][uf 1 1][e]

[msg MSG_WELCOME_IKUTSUKI_IN [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 3 0 65535 14204 0 0]Ah, no sabía que ya estabas aquí. He venido a hacer una visita rápida.[n][uf 1 1][e]

[msg MND_SHYUKAKU_OK]
[uf 0 5 65278][uf 2 1]Ahora que lo pienso, las hortalizas que planté en la azotea ya se podrán recolectar.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Debería ir a echarles un ojo...[n][uf 1 1][e]

[msg MND_SHYUKAKU_TAIYAKI_OK]
[uf 0 5 65278][uf 2 1]Ahora que lo pienso, las hortalizas que planté en la azotea ya se podrán recolectar.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Y el taiyaki que metí en la nevera también debería estar frío.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Debería ir a echarles un ojo...[n][uf 1 1][e]

[msg MND_SHYUKAKU_TAIYAKI_OK_]
[uf 0 5 65278][uf 2 1]Ahora que lo pienso, las hortalizas que planté en la azotea ya se podrán recolectar.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Y el taiyaki que metí en la nevera también debería estar frío.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Debería sacarlo de la nevera y dárselo a Elizabeth.[n][uf 1 1][e]

[msg MND_TAIYAKI_OK]
[uf 0 5 65278][uf 2 1]Ahora que lo pienso, el taiyaki que metí en la nevera ya debería estar frío.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Debería ir a por él.[n][uf 1 1][e]

[msg MND_TAIYAKI_OK_QUEST]
[uf 0 5 65278][uf 2 1]Ahora que lo pienso, el taiyaki que metí en la nevera ya debería estar frío.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Debería sacarlo de la nevera y dárselo a Elizabeth.[n][uf 1 1][e]

[msg MSG_ERROR [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1]エラーメッセージです。
[n][uf 1 5 0]杉山まで報告ください。
[n][uf 1 1][e]
