[msg MSG_ARAGAKI_TARTAROS_090 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0]...No me he introducido, ¿verdad?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0]Me llamo Shinjiro Aragaki. He estado aquí antes.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0]No te voy a dar el coñazo con los detalles...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0]El caso, que puedes contar conmigo.[n][uf 1 1][e]

[msg MSG_FUKA_TARTAROS_0903 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 65535 0 0][uf 3 1 3 0 65535 5061 0 0]Oye...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 65535 0 0]Pasado mañana va a haber luna llena.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Estoy segura de que aparecerá una Sombra poderosa, así que...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Asegúrate de que estés bien preparada, ¿vale?[n][uf 1 1][e]

[msg MSG_SANADA_TARTAROS_0904 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Mañana es el día...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Prepárate mientras puedas. Ya sabes cómo va esto. Estaremos a la espera mañana en la residencia.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0]Ja, qué ganas tengo... Da igual dónde o cúando aparezca, me la voy a cargar.[n][uf 1 1][e]

[msg MSG_FUKA_TARTAROS_0907 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]...Kirijo y los demás están en el hospital y no volverán hasta más tarde.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 65535 0 0]Según he oído, esa chica, Chidori, no dice nada...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 65535 0 0]Igual deberíamos pasar de ir a la Tártaro hasta que las cosas estén bajo control.[n][uf 1 1][e]

[msg MSG_FUKA_0908 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 65535 0 0]Esto... quizá hayas visto ya el mensaje que te he mandado, pero quería pedirte un favor.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 65535 0 0]Es sobre Amada...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 65535 0 0]Tengo la corazonada de que no lo se encuentra bien últimamente.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 65535 0 0]Cuando puedas, ¿podrías ir a verle? Debería estar en su habitación.[n][uf 1 1][e]

[msg MSG_ARAGAKI_0909 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0]Por cierto...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0]¿Cuánto tiempo llevamos reteniendo a la Chidori esta?[n][uf 1 1][e]

[sel SEL_005_0_0 top]
[uf 0 5 65278][uf 2 1]He perdido cuenta.[e]
[uf 0 5 65278][uf 2 1]Unos cuatro días.[e]

[msg MSG_ARAGAKI_0909_RE_1 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0]Ya veo...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0]...Bueno, déjalo.[n][uf 1 1][e]

[msg MSG_ARAGAKI_0909_RE_2 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0]Ya veo...[n][uf 1 1][e]

[msg MSG_MITSURU_TARTAROS_091 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]...Iori tiene permiso de vigilar a la chica por el momento.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Ahora no es el momento de atosigarla con preguntas.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Además, aún nos quedan tres Sombras a las que enfrentarnos.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Lo deberíamos lograr en los próximos meses, si la situación no cambia.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]No bajes la guardia hasta el final.[n][uf 1 1][e]

[msg MSG_FUKA_TARTAROS_0915 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]He oído que Chidori está empezando a hablar un poquito...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Pero parece que todavía le incomoda hablar sobre las Personas...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Quizá le lleve un poco más de tiempo para poder hacerlo.[n][uf 1 1][e]

[msg MSG_SANADA_TARTAROS_0915 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3061 0 0]No pasa nada.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Aún nos quedan tres Sombras por las que preocuparnos, así que centrémonos en eso.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Se arrepentirán de haberse adentrado en este mundo.[n][uf 1 1][e]

[msg MSG_MITSURU_TARTAROS_091_2 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]¿Es mi imaginación, o los Perdidos han estado proliferando más rápido de lo normal?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Todavía quedan dos semanas hasta la siguiente luna llena, ¿así que por qué...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Supongo que deberíamos centranos en lo que podemos hacer por ahora. Acabaremos con la próxima Sombra de forma rápida y eficaz.[n][uf 1 1][e]

[msg MND_HERO_0918]
[uf 0 5 65278][uf 2 1]Me siento un poco pachucha... Igual[n] debería irme pronto a la cama hoy.[n][uf 1 1][e]

[msg MSG_AMADA_TARTAROS_0924 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]Ah, [uf 4 1]. ¿Crees que podremos ir a la Tártaro esta noche?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]Están habiendo muchos casos últimamente... Quiero estar preparado para lo que sea.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]Por favor, dime si planeas ir esta noche, ¿vale?[n][uf 1 1][e]

[msg MSG_AMADA_0924 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]Ah, [uf 4 1]. ¿Estás pensando en ir a la Tártaro esta noche?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]Quiero ser más fuerte, ya que el número de casos está aumentando.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]Podemos ir cuando estés libre. Solo te pido que me lleves contigo a la Tártaro, por favor.[n][uf 1 1][e]

[msg MSG_AMADA_OK_0924 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]¿Has visto que se están dando muchos casos estos días? Ojalá pudiera hacer algo al respecto...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 65535 65535 0 0]Pero por ahora no puedo hacer nada, ¿no?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 65535 65535 0 0]Qué rabia...[n][uf 1 1][e]

[msg MSG_JUNPEI_TARTAROS_0925 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0]Dentro de poco cae otra luna llena...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0]Y ya que Chidori está mejorando, creo que ya es hora de que vuelva a entrenar.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]Además, esos tíos con Apatía no paran de salir por todos los lados.[n][uf 1 1][e]

[msg MSG_ARAGAKI_TARTAROS_092 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0]Queda una semana...[n][uf 1 1][e]

[msg MSG_FUKA_TARTAROS_0929 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 4 1], ¿has averiguado por qué la máquina de la sala de comandos está dando problemas?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Kirijo me pidió que le echara un ojo, pero no tengo ni idea de qué le pasa...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Parece que se estropea una vez al mes...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0]Ah, no te proecupes. No afecta a nuestras misiones en absoluto.[n][uf 1 1][e]

[msg MSG_SANADA_TARTAROS_0930 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Tiene toda la pinta de que la próxima operación será este domingo. Nos quedan cuatro días, así que nada de relajarse, ¿me oyes?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]Por cierto, la semana pasada comencé una nueva rutina enfocada al combate.[n][uf 1 1][e]

[msg MSG_JUNPEI_TARTAROS_0930 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 3 0 65535 2086 0 0]Oye, él no es el único con ganas de luchar. ¡Dame la señal, que puedes contar conmigo![n][uf 1 1][e]

[msg MSG_MITSURU_TARTAROS_093 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4061 0 0]Aprecio el entusiasmo, pero no te emociones demasiado.[n][uf 1 1][e]

[msg MSG_WELCOME_YUKARI_OUT [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1019 0 0]Ah, eh... Hola.[n][uf 1 1][e]

[msg MSG_WELCOME_YUKARI_OUT2 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1012 0 0]Eh... Hola...[n][uf 1 1][e]

[msg MSG_WELCOME_JUNPEI_OUT [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 3 0 65535 2018 0 0]¿Qué pasa, tía?[n][uf 1 1][e]

[msg MSG_WELCOME_JUNPEI_OUT2 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 3 0 65535 2012 0 0]Hola, tía...[n][uf 1 1][e]

[msg MSG_WELCOME_MITSURU_OUT [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4018 0 0]Hola de nuevo.[n][uf 1 1][e]

[msg MSG_WELCOME_MITSURU_OUT2 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4027 0 0]Hola de nuevo...[n][uf 1 1][e]

[msg MSG_WELCOME_SANADA_OUT [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3017 0 0]Anda, has vuelto.[n][uf 1 1][e]

[msg MSG_WELCOME_FUKA_OUT [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5018 0 0]Hola, ¿qué tal el día?[n][uf 1 1][e]

[msg MSG_WELCOME_FUKA_OUT2 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5028 0 0]Ah... Hola...[n][uf 1 1][e]

[msg MSG_WELCOME_AEGIS_OUT_RO [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 3 0 65535 6018 0 0]Saludos.[n][uf 1 1][e]

[msg MSG_WELCOME_AEGIS_OUT [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6018 0 0]Saludos.[n][uf 1 1][e]

[msg MSG_WELCOME_AEGIS_OUT_NA [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6017 0 0]Hola otra vez. Me alegro de volver a verte.[n][uf 1 1][e]

[msg MSG_WELCOME_KOROMARU_OUT [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 3 0 65535 8008 0 0]¡Guau![n][uf 1 1][e]

[msg MSG_WELCOME_AMADA_OUT [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7020 0 0]¡Anda, hola![n][uf 1 1][e]

[msg MSG_WELCOME_AMADA_OUT2 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7012 0 0]Ah... Hola...[n][uf 1 1][e]

[msg MSG_WELCOME_ARAGAKI_OUT [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0][uf 3 1 3 0 65535 9014 0 0]Ey...[n][uf 1 1][e]

[msg MSG_WELCOME_IKUTSUKI_OUT [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 3 0 65535 14201 0 0]Hola de nuevo.[n][uf 1 1][e]

[msg MSG_WELCOME_YUKARI_IN [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1067 0 0]¡Ah, estás aquí![n][uf 1 1][e]

[msg MSG_WELCOME_YUKARI_IN2 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1012 0 0]Ah, ¿ya has llegado? Perdona, no te había visto.[n][uf 1 1][e]

[msg MSG_WELCOME_JUNPEI_IN [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 3 0 65535 2009 0 0]Eh, ¿qué pasa?[n][uf 1 1][e]

[msg MSG_WELCOME_JUNPEI_IN2 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 3 0 65535 2012 0 0]Ah, hola...[n][uf 1 1][e]

[msg MSG_WELCOME_MITSURU_IN [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]¿Eh? Ah, eres tú...[n][uf 1 1][e]

[msg MSG_WELCOME_MITSURU_IN2 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4027 0 0]¿Mmm? Ah, ya estás aquí.[n][uf 1 1][e]

[msg MSG_WELCOME_SANADA_IN [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3024 0 0]¿Has estado en tu habitación todo este tiempo?[n][uf 1 1][e]

[msg MSG_WELCOME_FUKA_IN [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5067 0 0]¡Ah, hola! No sabía que ya estabas aquí.[n][uf 1 1][e]

[msg MSG_WELCOME_FUKA_IN2 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5093 0 0]Anda, ¿estás aquí? Hola...[n][uf 1 1][e]

[msg MSG_WELCOME_FUKA_IN_0712 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5067 0 0]Ah, [uf 4 1]...[n][uf 1 1][e]

[msg MSG_WELCOME_AEGIS_IN_ROB [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 3 0 65535 6008 0 0]Buenas tardes.[n][uf 1 1][e]

[msg MSG_WELCOME_AEGIS_IN [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6008 0 0]Buenas tardes.[n][uf 1 1][e]

[msg MSG_WELCOME_AEGIS_IN_NAK [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6009 0 0]¿Qué tal el día? ¿Todo bien?[n][uf 1 1][e]

[msg MSG_WELCOME_KOROMARU_IN [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 3 0 65535 8001 0 0]¡Guau, guau![n][uf 1 1][e]

[msg MSG_WELCOME_AMADA_IN [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7010 0 0]¿Has estudiado algo?[n][uf 1 1][e]

[msg MSG_WELCOME_AMADA_IN2 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7012 0 0]¿Estabas aquí? Pues... hola.[n][uf 1 1][e]

[msg MSG_WELCOME_ARAGAKI_IN [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0][uf 3 1 3 0 65535 9056 0 0]... ¿Qué hay?[n][uf 1 1][e]

[msg MSG_WELCOME_IKUTSUKI_IN [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 3 0 65535 14204 0 0]Ah, no sabía que ya estabas aquí. He venido a hacer una visita rápida.[n][uf 1 1][e]

[msg MND_SHYUKAKU_OK]
[uf 0 5 65278][uf 2 1]Ahora que lo pienso, las hortalizas que planté en la azotea ya se podrán recolectar.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Debería ir a echarles un ojo...[n][uf 1 1][e]

[msg MND_SHYUKAKU_TAIYAKI_OK]
[uf 0 5 65278][uf 2 1]Ahora que lo pienso, las hortalizas que planté en la azotea ya se podrán recolectar.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Y el taiyaki que metí en la nevera también debería estar frío.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Debería ir a echarles un ojo...[n][uf 1 1][e]

[msg MND_SHYUKAKU_TAIYAKI_OK_]
[uf 0 5 65278][uf 2 1]Ahora que lo pienso, las hortalizas que planté en la azotea ya se podrán recolectar.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Y el taiyaki que metí en la nevera también debería estar frío.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Debería sacarlo de la nevera y dárselo a Elizabeth.[n][uf 1 1][e]

[msg MND_TAIYAKI_OK]
[uf 0 5 65278][uf 2 1]Ahora que lo pienso, el taiyaki que metí en la nevera ya debería estar frío.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Debería ir a por él.[n][uf 1 1][e]

[msg MND_TAIYAKI_OK_QUEST]
[uf 0 5 65278][uf 2 1]Ahora que lo pienso, el taiyaki que metí en la nevera ya debería estar frío.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Debería sacarlo de la nevera y dárselo a Elizabeth.[n][uf 1 1][e]

[msg MSG_ERROR [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1]エラーメッセージです。
[n][uf 1 5 0]杉山まで報告ください。
[n][uf 1 1][e]


