[msg MSG_000_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 3 0 65535 11267 0 0]Comer dulces japoneses me hace sentir conectado a mi país de origen... Puede que esté exagerando.[n][uf 1 1][e]

[msg MSG_001_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0]En fin, he decidido irme a estudiar al extranjero.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0]Así que no volveremos a vernos...[n][uf 1 1][e]

[msg MSG_002_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 3 65535 65535 0 0]Lo siento, tiene que haber sonado rarísimo. Es que...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 3 65535 65535 0 0]Soy hijo único y siempre me he preguntado cómo sería tener una hermana.[n][uf 1 1][e]

[msg MSG_002_3_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 3 0 65535 11263 0 0]Por eso me preguntaba... cómo me llamarías si lo fueras.[n][uf 1 1][e]

[sel SEL_003_0_0 top]
[uf 0 5 65278][uf 2 1]¿Hermano pequeño?[e]
[uf 0 5 65278][uf 2 1]¿Y qué hay de ti?[e]
[uf 0 5 65278][uf 2 1]Vale, hermano.[e]

[msg MSG_004_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 3 65535 65535 0 0][uf 3 1 3 0 65535 11270 0 0]¿"Pequeño"? Pero si soy mayor que tú.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 3 65535 65535 0 0]Bueno, supongo que no soy gran cosa, así que no me extraña que tengas esa opinión de mí.[n][uf 1 1][e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]Hiraga parece deprimido.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Siento que hoy nuestra relación no ha cambiado nada...[n][uf 1 1][e]

[msg MSG_006_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 3 0 65535 11250 0 0][uf 5 13 11 15 108]A ver, s-soy el mayor, pero... Quizá no me he expresado bien.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0]Supongo que debería ser más directo en lo que quiero decir. Al menos lo he aprendido ahora, antes de irme.[n][uf 1 1][e]

[msg MND_007_0_0]
[uf 0 5 65278][uf 2 1]Hiraga asiente para sí mismo.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Hoy he aprendido un poco más sobre él.[n][uf 1 1][e]

[msg MSG_008_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 3 0 65535 11282 0 0][uf 5 13 11 30 108]Hermano... Ay, qué bonito suena.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0]Oye.... ¿p-puedes decirlo otra vez?[n][uf 1 1][e]

[msg MND_009_0_0]
[uf 0 5 65278][uf 2 1]Hiraga parece muy contento.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Siento que hoy nuestra relación se ha estrechado.[n][uf 1 1][e]

[msg MSG_010_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 3 0 65535 11251 0 0]Siempre se me va el santo al cielo cuando hablo contigo, pero he de comprar más cosas antes de irme al extranjero.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0]Debería llevarme productos de aquí a los que estoy acostumbrado, al menos para los primeros días.[n][uf 1 1][e]

[msg MND_011_0_0]
[uf 0 5 65278][uf 2 1]Después de ir de compras con Hiraga, volví a la residencia.[n][uf 1 1][e]

