[msg MSG_000_0_0 [Second-Year Club Member]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 1 0 0][uf 5 21 0 1001]Doesn't Miyamoto seem slower lately?[n][uf 1 1][e]

[msg MSG_001_0_0 [Third-Year Club Member]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 2 0 0][uf 5 21 0 1002]Yeah, he's not keeping his usual pace.[n][uf 1 1][e]

[msg MSG_002_0_0 [Second-Year Club Member]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 3 0 0][uf 5 21 0 1001]He thinks he'll make it to the nationals like that?[n][uf 1 1][e]

[msg MSG_003_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 101 65535 0 0][uf 3 1 1 0 0 4 0 0]If you guys have nothing better to do, then why don't you give me a hand with the laundry?[n][uf 1 1][e]

[msg MSG_004_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 2 101 65535 0 0][uf 3 1 1 0 0 5 0 0]The only thing they're good at is kicking up dirt...[n][uf 1 1][e]

[msg MSG_005_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 101 65535 0 0][uf 3 1 1 0 0 6 0 0]Hey, Kaz! Coach wants to see you in the office![n][uf 1 1][e]

[msg MSG_006_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 151 65535 0 0][uf 3 1 1 0 0 7 0 0]'Kay! Be right there![n][uf 1 1][e]

[msg MSG_007_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 101 65535 0 0][uf 3 1 0 0 0 8 0 0]......[n][uf 1 1][e]

[msg MSG_008_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 101 65535 0 0][uf 3 1 1 0 0 9 0 0]Hey, [uf 4 1]-chan...[n][uf 1 1][e]

[msg MSG_008_5_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 101 65535 0 0][uf 3 1 1 0 0 10 0 0]...Ah, never mind. I think we can wrap up practice for today.[n][uf 1 1][e]

[msg MND_009_0_0]
[uf 0 5 65278][uf 2 1]I went back to the dorm after practice.[n][uf 1 1][e]

