[msg MSG_000_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 6 65535 0 0][uf 3 1 1 0 0 1 0 0]¡Ay, mira, un yukata! Quizá debería haberme puesto uno...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 6 65535 0 0][uf 3 1 1 0 0 2 0 0]¿Crees que me quedaría bien?[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]Seguro que sí.[e]
[uf 0 5 65278][uf 2 1]También me gusta tu ropa habitual.[e]

[msg MSG_002_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 6 65535 1 0][uf 3 1 1 0 0 3 0 0][uf 5 13 12 15 106]¿T-tú crees?[n][uf 1 1][e]

[msg MSG_003_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 6 65535 0 0][uf 3 1 1 0 0 4 0 0]¡Supongo que los yukatas no pueden faltar en los festivales de verano![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 6 65535 0 0][uf 3 1 1 0 0 5 0 0]Aunque son muy apretados y cuesta mucho moverse con ellos. Son más incómodos de lo que se cree.[n][uf 1 1][e]

[msg MSG_003_5_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 6 65535 0 0][uf 3 1 1 0 0 6 0 0]La última vez que me puse uno aún era una niña. Recuerdo que me lo quité enseguida porque daba mucho calor.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 6 65535 0 0][uf 3 1 1 0 0 7 0 0][uf 4 23 0 106 1 25 25]Ah, no, eso era un kimono.[n][uf 1 1][e]

[msg MSG_004_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 6 65535 0 0][uf 3 1 1 0 0 8 0 0][uf 5 13 12 5 106]¿T-tú crees?[n][uf 1 1][e]

[msg MSG_005_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 6 65535 0 0][uf 3 1 1 0 0 9 0 0]¿No iría mejor con yukata, al ser el festival de verano?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 6 65535 0 0][uf 3 1 1 0 0 10 0 0][uf 4 23 0 106 0 25 25]Aunque son muy apretados y cuesta mucho moverse con ellos. Son más incómodos de lo que se cree.[n][uf 1 1][e]

[msg MSG_005_5_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 6 65535 0 0][uf 3 1 1 0 0 11 0 0]La última vez que me puse uno aún era una niña. Recuerdo que me lo quité enseguida porque daba mucho calor.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 6 65535 0 0][uf 3 1 1 0 0 12 0 0][uf 4 23 0 106 1 25 25]Ah, no, eso era un kimono.[n][uf 1 1][e]

[msg MSG_006_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 6 65535 0 0][uf 3 1 1 0 0 13 0 0]Mmm... Qué bien huele.[n][uf 1 1][e]

[msg MSG_006_5_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 6 65535 0 0][uf 3 1 1 0 0 14 0 0]¿Tienes hambre, [uf 4 1]?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 6 65535 0 0][uf 3 1 1 0 0 15 0 0]¡Vamos a comer takoyaki! Podemos compartirlo.[n][uf 1 1][e]

[msg MSG_007_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 6 65535 0 0][uf 3 1 1 0 0 16 0 0]¡Una de takoyaki, por favor![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 6 65535 0 0][uf 3 1 1 0 0 17 0 0][uf 4 23 0 106 0 25 25]Un momento, este takoyaki... ¿No lleva pulpo?[n][uf 1 1][e]

[msg MSG_008_0_0 [Vendedora de takoyaki]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 18 0 0][uf 5 21 0 10]Hay que probarlo para descubrirlo.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 19 0 0][uf 5 21 0 10]Un segundo, ahora te lo preparo.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 20 0 0][uf 5 21 0 10]¡Pero no mires lo que estoy poniendo dentro![n][uf 1 1][e]

[msg MSG_009_0_0 [Vendedora de takoyaki]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 21 0 0]Aquí tienes, ¡una de takoyaki![n][uf 1 1][e]

[msg MSG_010_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 6 65535 0 0][uf 3 1 1 0 0 22 0 0]Toma, come tú también, [uf 4 1].[n][uf 1 1][e]

[msg MSG_011_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 6 65535 0 0][uf 3 1 1 0 0 23 0 0]Uff... ¡Au! ¡Quema, quema![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 6 65535 0 0][uf 3 1 1 0 0 24 0 0][uf 4 23 0 106 1 25 25]¡Mmm! ¡Qué rico! ¡Y qué tierno está por dentro![n][uf 1 1][e]

[msg MSG_011_5_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 6 65535 0 0][uf 3 1 1 0 0 25 0 0]Aunque hay algo correoso en el centro...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 6 65535 0 0][uf 3 1 1 0 0 26 0 0]Mmm... Me pregunto qué será.[n][uf 1 1][e]

[msg MSG_012_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 6 65535 0 0][uf 3 1 1 0 0 27 0 0]¡Mira qué de máscaras diferentes![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 6 65535 0 0][uf 3 1 1 0 0 28 0 0]Mis padres me las solían comprar de pequeña. Sobre todo las de ese programa de superhéroes de la tele.[n][uf 1 1][e]

[msg MSG_012_5_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 6 65535 0 0][uf 3 1 1 0 0 29 0 0]¡Ay, mira! ¡Tienen las mismas que las de aquel entonces! Qué recuerdos...[n][uf 1 1][e]

[msg MSG_013_0_0 [Asistente de juego]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 30 0 0][uf 5 21 0 11]¡Eh, vosotras dos! ¿Os gustaría probar suerte?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 31 0 0][uf 5 21 0 11]¡Tendréis un bonito recuerdo! La suerte os sonríe, ¡todavía quedan un montón de premios![n][uf 1 1][e]

[msg MSG_014_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 6 65535 0 0][uf 3 1 1 0 0 32 0 0]¡Mira, [uf 4 1]! ¡Una lotería![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 6 65535 0 0][uf 3 1 1 0 0 33 0 0]Parece divertido, ¿verdad? Vamos a intentarlo, aunque a mí se me da fatal.[n][uf 1 1][e]

[msg MND_015_0_0]
[uf 0 5 65278][uf 2 1]La caja está llena de papeletas[n]triangulares de la lotería.[n][uf 1 1][e]

[sel SEL_016_0_0 top]
[uf 0 5 65278][uf 2 1]Coger uno de arriba[e]
[uf 0 5 65278][uf 2 1]Meter la mano hasta el fondo[e]

[msg MSG_017_0_0 [Asistente de juego]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 34 0 0][uf 5 21 0 11]¡Enhorabuena! ¡Has ganado![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 35 0 0][uf 5 21 0 11]¡Hala! ¡Menuda suerte la tuya para ganar en el primer intento![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 36 0 0][uf 5 21 0 11]Aquí tienes tu premio. ¡Disfrútalo![n][uf 1 1][e]

[msg MND_018_0_0]
[uf 0 5 65278][uf 2 1]He recibido (ITEM NAME).[n][uf 1 1][e]

[msg MSG_019_0_0 [Asistente de juego]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 37 0 0][uf 5 21 0 11]¡Enhorabuena! ¡Has ganado![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 38 0 0][uf 5 21 0 11]¡Hala! ¡Menuda suerte la tuya para ganar en el primer intento![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 39 0 0][uf 5 21 0 11]Aquí tienes tu premio. ¡Disfrútalo![n][uf 1 1][e]

[msg MND_020_0_0]
[uf 0 5 65278][uf 2 1]He recibido (ITEM NAME).[n][uf 1 1][e]

[msg MSG_021_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 6 65535 0 0][uf 3 1 1 0 0 40 0 0]Tiene pinta de ser caro. ¡Te has llevado un buen premio![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 6 65535 0 0][uf 3 1 1 0 0 41 0 0]Pero ¿ese chico no parecía un poco molesto?[n][uf 1 1][e]

[msg MSG_022_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 6 65535 0 0][uf 3 1 1 0 0 42 0 0]Uy, mira qué hora es. Deberíamos volver.[n][uf 1 1][e]

[msg MSG_022_5_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 6 65535 0 0][uf 3 1 1 0 0 43 0 0]Gracias, [uf 4 1]. ¡Qué bien me lo he pasado hoy![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 6 65535 0 0][uf 3 1 1 0 0 44 0 0]¡Tenemos que hacer más cosas de estas en el futuro![n][uf 1 1][e]

[msg MND_023_0_0]
[uf 0 5 65278][uf 2 1]Tras acompañar a Yuko a casa, he decidido volver a la residencia.[n][uf 1 1][e]

