[msg MSG_000_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 2 65535 0 0]Well... Let's go.[n][w][e]
[f 2 1][bup 6 0 2 65535 0 0][vp 3 0 0 5079 0 0]Junpei-kun and the others are... Oh, there they are.[n][w][e]

[msg MSG_000_1_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 2 65535 0 0][vp 3 0 0 5014 0 0]Morning... What's wrong?[n][w][e]

[msg MSG_001_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 2 65535 0 0]Oh, g-good morning, ladies.[n][w][e]

[msg MSG_002_0_0 [Yukari Takeba]]
[f 2 1][bup 2 4 2 65535 0 0][vp 3 0 0 1104 0 0]...Why're you being so formal?[n][w][e]

[msg MSG_003_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 2 65535 0 0]Sanada-senpai and Ryoji-kun don't look well either...[n][w][e]

[msg MSG_004_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 3 2 65535 0 0]Oh, no...[n][w][e]

[msg MSG_005_0_0 [Ryoji Mochizuki]]
[f 2 1][bup 221 1 65535 65535 0 0]We spent a little too much time in the bath yesterday.[n][w][e]

[msg MSG_006_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 2 2 65535 0 0][vp 3 0 0 3120 0 0]You idiot...![n][w][e]

[msg MSG_007_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 2 65535 0 0][vp 1 0 0 104 0 0]......?[n][w][e]
[f 2 1][bup 6 3 2 65535 0 0]Did the heat get to you?[n][w][e]

[msg MSG_008_0_0 [Ryoji Mochizuki]]
[f 2 1][bup 221 1 65535 65535 0 0][vp 3 0 0 14030 0 0]Heheh... Well, I guess you could put it that way.[n][w][e]

[msg MSG_008_1_0 [Ryoji Mochizuki]]
[f 2 1][bup 221 1 65535 65535 0 0][vp 3 0 0 14037 0 0]I didn't think it would be so amaz—[n][w][e]

[msg MSG_009_0_0 [Junpei Iori]]
[f 2 1][bup 3 2 2 65535 0 0][vp 3 0 0 2007 0 0]Quiet, you![n][w][e]

[msg MSG_010_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 2 65535 0 0][vp 3 0 0 5123 0 0]You're so weird.[n][w][e]

[msg MSG_011_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 2 65535 0 0][vp 3 0 0 1022 0 0]Well... whatever.[n][w][e]
[f 2 1][bup 2 1 2 65535 0 0][vp 3 0 0 1008 0 0]C'mon, [nf], let's go.[n][w][e]

[msg MND_012_0_0]
[f 2 1]...The guys are still whispering to each other...[n][w][e]

[msg MND_013_0_0]
[f 2 1]We decided to go on ahead.[n][w][e]

