[msg MND_000_0_0 [DEV: Internal MES]]
[f 2 1]This is the wrong room[n][w][e]
[f 2 1]My room is on the 3rd floor[n][w][e]

[msg MND_001_0_0 [DEV: Internal MES]]
[f 2 1]Rirurin is amazing!![n][w][e]

[msg MND_002_0_0 [DEV: Internal MES]]
[f 2 1]Rirurin is amazing!![n][w][e]

[msg MND_003_0_0 [DEV: Internal MES]]
[f 2 1]Rirurin is amazing!![n][w][e]

[msg MND_004_0_0 [DEV: Internal MES]]
[f 2 1]Hey you found Lucina!![n][w][e]

[msg MND_005_0_0 [DEV: Internal MES]]
[f 2 1]Rirurin is amazing!![n][w][e]

[msg MND_006_0_0 [DEV: Internal MES]]
[f 2 1]Rirurin is amazing!![n][w][e]

