[msg MSG_000_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]Hey, so uh, didn't Kirijo-senpai say we shouldn't be hanging out like this?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]Think she'll be mad if she finds out?[n][uf 1 1][e]

[msg MSG_001_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]I kind of doubt it...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]But I won't deny that seeing you all does remind me of recent events.[n][uf 1 1][e]

[msg MSG_002_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]R-Right! Well then, why don't we just call it a wrap here...?[n][uf 1 1][e]

[msg MSG_003_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]Um, Sanada-senpai! I'd like to ask for some help with this question![n][uf 1 1][e]

[msg MSG_004_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]Oh, uh... Wait, Junpei-kun! I wanted to ask you, uh... Um...[n][uf 1 1][e]

[msg MSG_005_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 8 0 0]I think I'll take Koromaru for a walk.[n][uf 1 1][e]

[msg MSG_006_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 65535 65535 0 0][uf 3 1 1 0 0 9 0 0]Hey, wait! We'll all take him on a walk when we're done. You can sit back down, Amada-kun![n][uf 1 1][e]

[msg MSG_007_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 0 0 0 10 0 0]......[n][uf 1 1][e]

[msg MSG_008_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0][uf 3 1 1 0 0 11 0 0]Oh, ahaha... I guess you found out. I was planning on inviting you too, Mitsuru-senpai...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 10 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]I do understand that we don't have time for chitchat, but...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 10 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]I just... wanted to spend time with everyone.[n][uf 1 1][e]

[msg MSG_009_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 8 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]Um, this was actually my idea! I was the one who wanted to gather everyone...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 65535 0 0][uf 3 1 1 0 0 15 0 0][uf 4 23 0 6 3 25 25]So... I'm sorry. I don't want everyone to get in trouble for my selfishness...[n][uf 1 1][e]

[msg MSG_010_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 6 65535 65535 0 0][uf 3 1 0 0 0 16 0 0]......[n][uf 1 1][e]

[msg MSG_011_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0][uf 3 1 1 0 0 17 0 0]Hey, you shouldn't be the only one that has to apologize. I feel the same way, Fuuka.[n][uf 1 1][e]

[msg MSG_012_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 65535 0 0][uf 3 1 1 0 0 18 0 0]Thanks, Yukari-chan. It's just... when I think this might be the last—[n][uf 1 1][e]

[msg MSG_013_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 8 65535 65535 0 0][uf 3 1 1 0 0 19 0 0]Um...! In any case, I apologize for this! Let's just call it for today![n][uf 1 1][e]

[sel SEL_014_0_0 top]
[uf 0 5 65278][uf 2 1]We're not calling it.[e]
[uf 0 5 65278][uf 2 1]Let's keep studying.[e]

[msg MSG_015_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 65535 65535 0 0][uf 3 1 1 0 0 20 0 0][uf 4 1]-chan...[n][uf 1 1][e]

[msg MSG_016_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 0 21 0 0]...Thank you.[n][uf 1 1][e]

[msg MSG_017_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 22 0 0]After warning you all, I wasn't sure how to go back on it. I was actually taking a walk to mull it over.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 0 23 0 0][uf 4 23 0 5 1 25 25]Yukari... Yamagishi... I feel the same way you do.[n][uf 1 1][e]

[msg MSG_018_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 24 0 0]Eh, you did say we should try to go about our lives for now. You hear that, Junpei? Let's get to it.[n][uf 1 1][e]

[msg MSG_019_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 6 65535 65535 0 0][uf 3 1 1 0 0 25 0 0]If we're talkin' MY life, studying's the last thing I'd be doing...[n][uf 1 1][e]

[msg MSG_020_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 11 65535 65535 0 0][uf 3 1 1 0 0 26 0 0]Mitsuru-senpai, could you help me with this?[n][uf 1 1][e]

[msg MSG_021_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 0 27 0 0]Heh, of course. What question did you need help with?[n][uf 1 1][e]

[msg MND_022_0_0]
[uf 0 5 65278][uf 2 1]We studied together as we always do...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel I was able to focus[n]better than usual...[n][uf 1 1][e]

[msg MSG_023_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 0 28 0 0]Whew, how long have we been studying? Time really flies when we're all in it together.[n][uf 1 1][e]

[msg MSG_024_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 29 0 0]I agree... Thank you for going along with my suggestion, everyone.[n][uf 1 1][e]

[sel SEL_025_0_0 top]
[uf 0 5 65278][uf 2 1]Time well spent.[e]
[uf 0 5 65278][uf 2 1]You owe us.[e]

[msg MSG_026_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 30 0 0]You think so? I hope everyone else feels the same way.[n][uf 1 1][e]

[msg MSG_027_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 31 0 0]Hehe... Sure! If anyone has any requests, please let me know. That includes you, [uf 4 1]-chan.[n][uf 1 1][e]

[msg MSG_028_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 65535 65535 0 0][uf 3 1 1 0 0 32 0 0]By the way... I hope you haven't forgotten about taking Koromaru for a walk.[n][uf 1 1][e]

[msg MSG_029_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 0 33 0 0]Er— Of course not! C'mon, everyone, let's go![n][uf 1 1][e]

[msg MSG_030_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 1 65535 65535 0 0][uf 3 1 1 0 0 34 0 0]Arf![n][uf 1 1][e]

[msg MSG_031_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 35 0 0]That'll be it for studying, then. Everyone, make sure to give it your all on the exams.[n][uf 1 1][e]

