[msg MSG_000_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 1 0 0]C'est très étrange...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 2 0 0]Ces plantes semblent être en bien meilleure santé que quand nous avons commencé.[n][uf 1 1][e]

[msg MSG_001_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 3 0 0]Est-ce que tu penses qu'elles sont heureuses que tu t'occupes d'elles ?[n][uf 1 1][e]

[sel SEL_002_0_0 top]
[uf 0 5 65278][uf 2 1]Je crois.[e]
[uf 0 5 65278][uf 2 1]C'est impossible.[e]
[uf 0 5 65278][uf 2 1]Et si tu demandais ?[e]

[msg MSG_003_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 4 0 0][uf 5 13 22 1 7]Fascinant. Il n'existe aucune donnée à ce sujet, mais tu sembles les comprendre.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 5 0 0]Bonjour, petites plantes. Je vais m'occuper de vous aussi, aujourd'hui. Ne vous inquiétez pas, je vais appliquer une pression réduite.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 6 0 0][uf 4 21 1 10]Mais si quelque chose vous fait mal, levez la main. Ou plutôt, la feuille.[n][uf 1 1][e]

[msg MSG_004_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 7 0 0][uf 5 13 22 1 7]C'est aussi ce que je pensais.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 8 0 0]Toutefois, des rapports suggèrent que les plantes poussent mieux quand on leur parle.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 9 0 0]Se pourrait-il qu'elles disposent de capacités que nous ignorons encore ?[n][uf 1 1][e]

[msg MSG_005_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 10 0 0][uf 5 13 22 1 7]Bonne idée. Je vais essayer.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 11 0 0]Bonjour à toutes les plantes. Ici Aigis. Si vous m'entendez, merci de répondre.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 0 0 0 12 0 0]...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 13 0 0]Malheureusement, je n'ai pas eu de réponse.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 14 0 0]La communication va être difficile avec mes compétences actuelles. Il faudra que j'y réfléchisse à l'avenir.[n][uf 1 1][e]

[msg MSG_006_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 15 0 0]J'avais déjà des connaissances sur les "plantes", mais c'est la première fois que j'en voyais d'aussi près.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 16 0 0]Ces petites graines et ces pousses dans la terre peuvent changer très rapidement.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 17 0 0]Est-ce la preuve qu'elles sont aussi vivantes ? C'est fascinant.[n][uf 1 1][e]

[msg MSG_007_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 18 0 0]J'aimerais regarder ces plantes pousser et documenter cette expérience pour mes archives personnelles.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 19 0 0][uf 4 21 7 7]Je vais m'occuper d'elles de toutes mes forces ![n][uf 1 1][e]

[msg MND_008_0_0]
[uf 0 5 65278][uf 2 1]Je me suis occupée des plants avec Aigis.[n][uf 1 1][e]

[msg MSG_009_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 20 0 0]Nous y avons passé plus de temps que je ne l'avais prévu.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 21 0 0]Je vais devoir effectuer plus de simulations pour éviter tout retard la prochaine fois.[n][uf 1 1][e]

[msg MND_010_0_0]
[uf 0 5 65278][uf 2 1]Grâce à nos efforts, on dirait que la récolte va être bonne.[n][uf 1 1][e]

[msg MSG_011_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 22 0 0]Il se fait tard. Nous devrions rentrer.[n][uf 1 1][e]

[msg MSG_012_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 23 0 0]Je me demandais...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 24 0 0]Ces plantes ont l'air en bien meilleure santé qu'avant notre intervention.[n][uf 1 1][e]

[msg MSG_013_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 202 65535 0 0][uf 3 1 1 0 0 25 0 0][uf 4 23 0 7 1 25 25]Est-ce que tu penses qu'elles sont heureuses que tu t'occupes d'elles, [uf 4 2] ?[n][uf 1 1][e]

[sel SEL_014_0_0 top]
[uf 0 5 65278][uf 2 1]C'est possible.[e]
[uf 0 5 65278][uf 2 1]Impossible.[e]
[uf 0 5 65278][uf 2 1]Tu pourrais demander ?[e]

[msg MSG_015_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 202 65535 0 0][uf 3 1 1 0 0 26 0 0][uf 5 13 22 1 7]Oui, tu t'en occupes avec le plus grand soin. Il est évident que tu tiens à elles.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 202 65535 0 0][uf 3 1 1 0 0 27 0 0]Je suis certaine que ces plantes savent tout ce que tu fais pour elles.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 202 65535 0 0][uf 3 1 1 0 0 28 0 0]Je ferai de mon mieux pour les rendre heureuses, moi aussi.[n][uf 1 1][e]

[msg MSG_016_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 29 0 0][uf 4 23 0 7 0 25 25][uf 5 13 22 1 7]Je suis d'accord. Mais c'est la raison pour laquelle je suis aussi surprise.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 30 0 0]On dit que parler aux plantes est bon pour leur croissance, n'est-ce pas ?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 31 0 0]Tu crois que ces plantes ont aussi un cœur dont nous n'avons pas conscience ?[n][uf 1 1][e]

[msg MSG_017_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 202 65535 0 0][uf 3 1 1 0 0 32 0 0][uf 5 13 22 1 7]Ce serait bien, si c'était possible.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 202 65535 0 0][uf 3 1 1 0 0 33 0 0]Je me demande si ces plantes ont aussi un cœur dont nous n'avons pas conscience.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 202 65535 0 0][uf 3 1 1 0 0 34 0 0]Nous les comprendrons peut-être mieux en continuant à nous en occuper ?[n][uf 1 1][e]

[msg MSG_018_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 202 65535 0 0][uf 3 1 1 0 0 35 0 0][uf 4 23 0 7 1 25 25]Regarder ces plantes me fait beaucoup réfléchir.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 202 65535 0 0][uf 3 1 1 0 0 36 0 0]Elles sont comme toi et les autres. Elles sont vivantes, elles aussi.[n][uf 1 1][e]

[msg MSG_019_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 202 65535 0 0][uf 3 1 1 0 0 37 0 0]Je veux les voir pousser de mes propres yeux.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 202 65535 0 0][uf 3 1 1 0 0 38 0 0][uf 4 21 7 7]Je vais faire tout ce qui est en mon pouvoir pour en prendre soin.[n][uf 1 1][e]

[msg MND_020_0_0]
[uf 0 5 65278][uf 2 1]Je me suis occupée des plants avec Aigis.[n][uf 1 1][e]

[msg MSG_021_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 39 0 0][uf 4 21 7 11]Pardon, c'est la première fois que je fais ceci. Je crois que je t'ai fait perdre du temps.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 202 65535 0 0][uf 3 1 1 0 0 40 0 0][uf 4 23 0 7 1 25 25]Je vais m'entraîner dans ma chambre pour aller plus vite la prochaine fois.[n][uf 1 1][e]

[msg MND_022_0_0]
[uf 0 5 65278][uf 2 1]Grâce à nos efforts, on dirait que la récolte va être bonne.[n][uf 1 1][e]

[msg MSG_023_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 202 65535 0 0][uf 3 1 1 0 0 41 0 0]Merci pour ton aide. Nous devrions rentrer.[n][uf 1 1][e]

[msg MSG_024_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 42 0 0]Les insectes nuisibles semblent avoir infligé moins de dégâts que dans mes prévisions.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 43 0 0]Pourtant, nous n'avons pas pris de mesures contre eux. Quelle en est la cause, alors ?[n][uf 1 1][e]

[msg MSG_025_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 44 0 0]Oh, c'est...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 45 0 0]Regarde, [uf 4 2] ! J'ai repéré une larve de coccinelle ! Toute petite et adorable.[n][uf 1 1][e]

[sel SEL_026_0_0 top]
[uf 0 5 65278][uf 2 1]Débarrassons-nous-en.[e]
[uf 0 5 65278][uf 2 1]Laissons-la en paix.[e]
[uf 0 5 65278][uf 2 1]Garde-la loin de moi.[e]

[msg MSG_027_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 46 0 0]Non, nous ne pouvons pas.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 47 0 0]Les coccinelles sont des prédateurs naturels des insectes nuisibles qui abîment les plantes.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 48 0 0]C'est sans doute pour cela qu'elles poussent si bien.[n][uf 1 1][e]

[msg MSG_028_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 49 0 0]Je partage cet avis. Nous ne devons pas l'interrompre dans son repas.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 50 0 0]Les coccinelles sont des prédateurs naturels des insectes nuisibles qui abîment les plantes.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 51 0 0]Voilà qui explique l'absence de nuisibles aux alentours.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 52 0 0]Merci beaucoup, petite coccinelle.[n][uf 1 1][e]

[msg MSG_029_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 53 0 0]Tu n'as pas l'air à ton aise. Tu n'as pas à craindre qu'elle te morde, pourtant...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 54 0 0]Bon, je vais la déplacer sur une autre feuille.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 0 0 0 55 0 0]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 56 0 0]Elle ne tient pas en place.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 57 0 0]On dirait que la coccinelle veut être près de toi, [uf 4 2].[n][uf 1 1][e]

[msg MSG_030_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 58 0 0]Même dans ces petits bacs, il y a tant de vie...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 59 0 0]Personne n'est là pour leur apprendre quoi que ce soit. Ils font du mieux qu'ils peuvent.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 0 0 0 60 0 0]......[n][uf 1 1][e]

[msg MSG_031_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 61 0 0]Toutes mes excuses, j'étais distraite. Continuons à travailler.[n][uf 1 1][e]

[msg MND_032_0_0]
[uf 0 5 65278][uf 2 1]Je me suis occupée des plants avec Aigis.[n][uf 1 1][e]

[msg MSG_033_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 62 0 0]Pardon, [uf 4 2]. Mets du répulsif de ce côté, s'il te plaît.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 63 0 0]Pas de pitié pour les nuisibles.[n][uf 1 1][e]

[msg MND_034_0_0]
[uf 0 5 65278][uf 2 1]Grâce à nos efforts, les plants devraient bien pousser.[n][uf 1 1][e]

[msg MSG_035_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 64 0 0][uf 5 13 22 1 7]Rapport de situation : feu vert d'un bout à l'autre. Aucun problème à signaler.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 65 0 0]Voilà qui conclut notre mission du jour. Rentrons, maintenant.[n][uf 1 1][e]

[msg MSG_036_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 66 0 0]Les nuisibles n'ont pas fait autant de dégâts que je l'avais prévu. C'est un soulagement.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 67 0 0]Pourtant, nous n'avons pas pris de mesures particulières. Comment est-ce possible ?[n][uf 1 1][e]

[msg MSG_037_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 68 0 0]Oh, c'est...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 69 0 0]Regarde, [uf 4 2] ! Une larve de coccinelle ! Toute petite et adorable.[n][uf 1 1][e]

[sel SEL_038_0_0 top]
[uf 0 5 65278][uf 2 1]Débarrassons-nous-en.[e]
[uf 0 5 65278][uf 2 1]Laissons-la en paix.[e]
[uf 0 5 65278][uf 2 1]Garde-la loin de moi.[e]

[msg MSG_039_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 70 0 0]Non, nous ne pouvons pas ![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 71 0 0]Les coccinelles sont des prédateurs naturels des insectes nuisibles qui abîment les plantes.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 72 0 0]Voilà qui explique l'absence de nuisibles aux alentours.[n][uf 1 1][e]

[msg MSG_040_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 73 0 0]Oui. Nous ne devons pas l'interrompre pendant son repas.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 74 0 0]Les coccinelles sont des prédateurs naturels des insectes nuisibles qui abîment les plantes.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 75 0 0]Voilà qui explique l'absence de nuisibles aux alentours.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 76 0 0]Merci beaucoup, petite coccinelle.[n][uf 1 1][e]

[msg MSG_041_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 77 0 0]Pardon. Les insectes te mettent mal à l'aise ? Je vais la mettre sur une autre feuille.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 0 0 0 78 0 0]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 79 0 0]Elle ne tient pas en place.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 80 0 0]On dirait que la coccinelle veut être près de toi, [uf 4 2].[n][uf 1 1][e]

[msg MSG_042_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 81 0 0]Même dans ces petits bacs, il y a tant de vie...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 82 0 0]Personne n'est là pour leur apprendre quoi que ce soit. Ils font du mieux qu'ils peuvent.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 0 0 0 83 0 0]......[n][uf 1 1][e]

[msg MSG_043_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 84 0 0]Pardon, j'étais distraite. On continue ?[n][uf 1 1][e]

[msg MND_044_0_0]
[uf 0 5 65278][uf 2 1]Je me suis occupée des plants avec Aigis.[n][uf 1 1][e]

[msg MSG_045_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 85 0 0]Oh, [uf 4 2], regarde...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 86 0 0]Il est peut-être indélicat d'intervenir, mais nous ne pouvons pas les laisser gâcher notre récolte.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 87 0 0]Portons assistance à la coccinelle, cette fois.[n][uf 1 1][e]

[msg MND_046_0_0]
[uf 0 5 65278][uf 2 1]Grâce à nos efforts, les plants devraient bien pousser.[n][uf 1 1][e]

[msg MSG_047_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 88 0 0][uf 5 13 22 1 7]Feu vert d'un bout à l'autre. Je ne vois aucun problème.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 89 0 0]Ça devrait suffire pour aujourd'hui. Rentrons.[n][uf 1 1][e]

[msg MSG_048_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 1 0 0]C'est très étrange...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 2 0 0]Ces plantes semblent être en bien meilleure santé que quand nous avons commencé.[n][uf 1 1][e]

[msg MSG_049_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 3 0 0]Est-ce que tu penses qu'elles sont heureuses que tu t'occupes d'elles ?[n][uf 1 1][e]

[sel SEL_050_0_0 top]
[uf 0 5 65278][uf 2 1]Je crois.[e]
[uf 0 5 65278][uf 2 1]C'est impossible.[e]
[uf 0 5 65278][uf 2 1]Et si tu demandais ?[e]

[msg MSG_051_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 4 0 0][uf 5 13 22 1 7]Fascinant. Il n'existe aucune donnée à ce sujet, mais tu sembles les comprendre.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 5 0 0]Bonjour, petites plantes. Je vais m'occuper de vous aussi, aujourd'hui. Ne vous inquiétez pas, je vais appliquer une pression réduite.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 6 0 0][uf 4 21 1 10]Mais si quelque chose vous fait mal, levez la main. Ou plutôt, la feuille.[n][uf 1 1][e]

[msg MSG_052_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 7 0 0][uf 5 13 22 1 7]C'est aussi ce que je pensais.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 8 0 0]Toutefois, des rapports suggèrent que les plantes poussent mieux quand on leur parle.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 9 0 0]Se pourrait-il qu'elles disposent de capacités que nous ignorons encore ?[n][uf 1 1][e]

[msg MSG_053_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 10 0 0][uf 5 13 22 1 7]Bonne idée. Je vais essayer.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 11 0 0]Bonjour à toutes les plantes. Ici Aigis. Si vous m'entendez, merci de répondre.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 0 0 0 12 0 0]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 13 0 0]Malheureusement, je n'ai pas eu de réponse.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 14 0 0]La communication va être difficile avec mes compétences actuelles. Il faudra que j'y réfléchisse à l'avenir.[n][uf 1 1][e]

[msg MSG_054_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 15 0 0]J'avais déjà des connaissances préalables sur les "plantes", mais c'est la première fois que j'en voyais d'aussi près.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 16 0 0]Ces petites graines et ces pousses dans la terre peuvent changer très rapidement.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 17 0 0]Est-ce la preuve qu'elles sont aussi vivantes ? C'est fascinant.[n][uf 1 1][e]

[msg MSG_055_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 18 0 0]J'aimerais regarder ces plantes pousser et documenter cette expérience pour mes archives personnelles.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 19 0 0][uf 4 21 7 7]Je vais m'occuper d'elles de toutes mes forces ![n][uf 1 1][e]

[msg MND_056_0_0]
[uf 0 5 65278][uf 2 1]Je me suis occupée des plants avec Aigis.[n][uf 1 1][e]

[msg MSG_057_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 20 0 0]Nous y avons passé plus de temps que je ne l'avais prévu.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 21 0 0]Je vais devoir effectuer plus de simulations pour éviter tout retard la prochaine fois.[n][uf 1 1][e]

[msg MND_058_0_0]
[uf 0 5 65278][uf 2 1]Grâce à nos efforts, on dirait que la récolte va être bonne.[n][uf 1 1][e]

[msg MSG_059_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 22 0 0]Il se fait tard. Nous devrions rentrer.[n][uf 1 1][e]

[msg MSG_060_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 23 0 0]Je me demandais...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 24 0 0]Ces plantes ont l'air en bien meilleure santé qu'avant notre intervention.[n][uf 1 1][e]

[msg MSG_061_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 2 65535 0 0][uf 3 1 1 0 0 25 0 0][uf 4 23 0 7 1 25 25]Est-ce que tu penses qu'elles sont heureuses que tu t'occupes d'elles, [uf 4 2] ?[n][uf 1 1][e]

[sel SEL_062_0_0 top]
[uf 0 5 65278][uf 2 1]C'est possible.[e]
[uf 0 5 65278][uf 2 1]C'est impossible.[e]
[uf 0 5 65278][uf 2 1]Et si tu demandais ?[e]

[msg MSG_063_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 2 65535 0 0][uf 3 1 1 0 0 26 0 0][uf 5 13 22 1 7]Oui, tu t'en occupes avec le plus grand soin. Il est évident que tu tiens à elles.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 2 65535 0 0][uf 3 1 1 0 0 27 0 0]Je suis certaine que ces plantes savent tout ce que tu fais pour elles.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 2 65535 0 0][uf 3 1 1 0 0 28 0 0]Je ferai de mon mieux pour les rendre heureuses, moi aussi.[n][uf 1 1][e]

[msg MSG_064_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 29 0 0][uf 4 23 0 7 0 25 25][uf 5 13 22 1 7]Je suis d'accord. Mais c'est la raison pour laquelle je suis aussi surprise.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 30 0 0]On dit que parler aux plantes est bon pour leur croissance, n'est-ce pas ?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 31 0 0]Je me demande si ces plantes ont aussi un cœur dont nous n'avons pas conscience.[n][uf 1 1][e]

[msg MSG_065_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 2 65535 0 0][uf 3 1 1 0 0 32 0 0][uf 5 13 22 1 7]Ce serait bien, si c'était possible.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 2 65535 0 0][uf 3 1 1 0 0 33 0 0]Je me demande si ces plantes ont aussi un cœur dont nous n'avons pas conscience.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 2 65535 0 0][uf 3 1 1 0 0 34 0 0]Nous les comprendrons peut-être mieux en continuant à nous en occuper ?[n][uf 1 1][e]

[msg MSG_066_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 2 65535 0 0][uf 3 1 1 0 0 35 0 0][uf 4 23 0 7 1 25 25]Regarder ces plantes me fait beaucoup réfléchir.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 2 65535 0 0][uf 3 1 1 0 0 36 0 0]Elles sont comme toi et les autres. Elles sont vivantes, elles aussi.[n][uf 1 1][e]

[msg MSG_067_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 2 65535 0 0][uf 3 1 1 0 0 37 0 0]Je veux les voir pousser de mes propres yeux.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 2 65535 0 0][uf 3 1 1 0 0 38 0 0][uf 4 21 7 7]Je vais faire tout ce qui est en mon pouvoir pour en prendre soin.[n][uf 1 1][e]

[msg MND_068_0_0]
[uf 0 5 65278][uf 2 1]Je me suis occupée des plants avec Aigis.[n][uf 1 1][e]

[msg MSG_069_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 39 0 0][uf 4 21 7 11]Pardon, c'est la première fois que je fais ceci. Je crois que je t'ai fait perdre du temps.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 2 65535 0 0][uf 3 1 1 0 0 40 0 0][uf 4 23 0 7 1 25 25]Je vais m'entraîner dans ma chambre pour aller plus vite la prochaine fois.[n][uf 1 1][e]

[msg MND_070_0_0]
[uf 0 5 65278][uf 2 1]Grâce à nos efforts, on dirait que la récolte va être bonne.[n][uf 1 1][e]

[msg MSG_071_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 2 65535 0 0][uf 3 1 1 0 0 41 0 0]Merci pour ton aide. Nous devrions rentrer.[n][uf 1 1][e]

[msg MSG_072_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 42 0 0]Les insectes nuisibles semblent avoir infligé moins de dégâts que dans mes prévisions.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 43 0 0]Pourtant, nous n'avons pas pris de mesures contre eux. Quelle en est la cause, alors ?[n][uf 1 1][e]

[msg MSG_073_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 44 0 0]Oh, c'est...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 45 0 0]Regarde, [uf 4 2] ! J'ai repéré une larve de coccinelle ! Toute petite et adorable.[n][uf 1 1][e]

[sel SEL_074_0_0 top]
[uf 0 5 65278][uf 2 1]Débarrassons-nous-en.[e]
[uf 0 5 65278][uf 2 1]Laissons-la en paix.[e]
[uf 0 5 65278][uf 2 1]Garde-la loin de moi.[e]

[msg MSG_075_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 46 0 0]Non, nous ne pouvons pas.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 47 0 0]Les coccinelles sont des prédateurs naturels des insectes nuisibles qui abîment les plantes.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 48 0 0]C'est sans doute pour cela qu'elles poussent si bien.[n][uf 1 1][e]

[msg MSG_076_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 49 0 0]Je partage cet avis. Nous ne devons pas l'interrompre dans son repas.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 50 0 0]Les coccinelles sont des prédateurs naturels des insectes nuisibles qui abîment les plantes.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 51 0 0]Voilà qui explique l'absence de nuisibles aux alentours.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 52 0 0]Merci beaucoup, petite coccinelle.[n][uf 1 1][e]

[msg MSG_077_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 53 0 0]Tu n'as pas l'air à ton aise. Tu n'as pas à craindre qu'elle te morde, pourtant...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 54 0 0]Bon, je vais la déplacer sur une autre feuille.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 0 0 0 55 0 0]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 56 0 0]Elle ne tient pas en place.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 57 0 0]On dirait que la coccinelle veut être près de toi, [uf 4 2].[n][uf 1 1][e]

[msg MSG_078_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 58 0 0]Même dans ces petits bacs, il y a tant de vie...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 59 0 0]Personne n'est là pour leur apprendre quoi que ce soit. Ils font du mieux qu'ils peuvent.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 0 0 0 60 0 0]......[n][uf 1 1][e]

[msg MSG_079_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 61 0 0]Toutes mes excuses, j'étais distraite. Continuons à travailler.[n][uf 1 1][e]

[msg MND_080_0_0]
[uf 0 5 65278][uf 2 1]Je me suis occupée des plants avec Aigis.[n][uf 1 1][e]

[msg MSG_081_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 62 0 0]Pardon, [uf 4 2]. Mets du répulsif de ce côté, s'il te plaît.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 63 0 0]Pas de pitié pour les nuisibles.[n][uf 1 1][e]

[msg MND_082_0_0]
[uf 0 5 65278][uf 2 1]Grâce à nos efforts, les plants devraient bien pousser.[n][uf 1 1][e]

[msg MSG_083_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 64 0 0][uf 5 13 22 1 7]Rapport de situation : feu vert d'un bout à l'autre. Aucun problème à signaler.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 65 0 0]Voilà qui conclut notre mission du jour. Rentrons, maintenant.[n][uf 1 1][e]

[msg MSG_084_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 66 0 0]Les nuisibles n'ont pas fait autant de dégâts que je l'avais prévu. C'est un soulagement.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 67 0 0]Pourtant, nous n'avons pas pris de mesures particulières. Comment est-ce possible ?[n][uf 1 1][e]

[msg MSG_085_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 68 0 0]Oh, c'est...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 69 0 0]Regarde, [uf 4 2] ! Une larve de coccinelle ! Toute petite et adorable.[n][uf 1 1][e]

[sel SEL_086_0_0 top]
[uf 0 5 65278][uf 2 1]Débarrassons-nous-en.[e]
[uf 0 5 65278][uf 2 1]Laissons-la en paix.[e]
[uf 0 5 65278][uf 2 1]Garde-la loin de moi.[e]

[msg MSG_087_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 70 0 0]Non, nous ne pouvons pas ![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 71 0 0]Les coccinelles sont des prédateurs naturels des insectes nuisibles qui abîment les plantes.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 72 0 0]Voilà qui explique l'absence de nuisibles aux alentours.[n][uf 1 1][e]

[msg MSG_088_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 73 0 0]Oui. Nous ne devons pas l'interrompre dans son repas.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 74 0 0]Les coccinelles sont des prédateurs naturels des insectes nuisibles qui abîment les plantes.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 75 0 0]Voilà qui explique l'absence de nuisibles aux alentours.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 76 0 0]Merci beaucoup, petite coccinelle.[n][uf 1 1][e]

[msg MSG_089_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 77 0 0]Pardon. Les insectes te mettent mal à l'aise ? Je vais la mettre sur une autre feuille.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 0 0 0 78 0 0]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 79 0 0]Elle ne tient pas en place.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 80 0 0]On dirait que la coccinelle veut être près de toi, [uf 4 2].[n][uf 1 1][e]

[msg MSG_090_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 81 0 0]Même dans ces petits bacs, il y a tant de vie...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 82 0 0]Personne n'est là pour leur apprendre quoi que ce soit. Ils font du mieux qu'ils peuvent.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 0 0 0 83 0 0]......[n][uf 1 1][e]

[msg MSG_091_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 84 0 0]Pardon, j'étais distraite. On continue ?[n][uf 1 1][e]

[msg MND_092_0_0]
[uf 0 5 65278][uf 2 1]Je me suis occupée des plants avec Aigis.[n][uf 1 1][e]

[msg MSG_093_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 85 0 0]Oh, [uf 4 2], regarde...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 86 0 0]Il est peut-être indélicat d'intervenir, mais nous ne pouvons pas les laisser gâcher notre récolte.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 87 0 0]Portons assistance à la coccinelle, cette fois.[n][uf 1 1][e]

[msg MND_094_0_0]
[uf 0 5 65278][uf 2 1]Grâce à nos efforts, les plants devraient bien pousser.[n][uf 1 1][e]

[msg MSG_095_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 88 0 0][uf 5 13 22 1 7]Feu vert d'un bout à l'autre. Je ne vois aucun problème.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 89 0 0]Ça devrait suffire pour aujourd'hui. Rentrons.[n][uf 1 1][e]

[msg MSG_247_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 1 0 0]C'est très étrange...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 2 0 0]Ces plantes semblent être en bien meilleure santé que quand nous avons commencé.[n][uf 1 1][e]

[msg MSG_248_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 3 0 0]Est-ce que tu penses qu'elles sont heureuses que tu t'occupes d'elles ?[n][uf 1 1][e]

[sel SEL_249_0_0 top]
[uf 0 5 65278][uf 2 1]Je crois.[e]
[uf 0 5 65278][uf 2 1]C'est impossible.[e]
[uf 0 5 65278][uf 2 1]Et si tu demandais ?[e]

[msg MSG_252_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 4 0 0][uf 5 13 22 1 7]Fascinant. Il n'existe aucune donnée à ce sujet, mais tu sembles les comprendre.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 5 0 0]Bonjour, petites plantes. Je vais m'occuper de vous aussi, aujourd'hui. Ne vous inquiétez pas, je vais appliquer une pression réduite.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 6 0 0][uf 4 21 1 10]Mais si quelque chose vous fait mal, levez la main. Ou plutôt, la feuille.[n][uf 1 1][e]

[msg MSG_256_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 7 0 0][uf 5 13 22 1 7]C'est aussi ce que je pensais.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 8 0 0]Toutefois, des rapports suggèrent que les plantes poussent mieux quand on leur parle.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 9 0 0]Se pourrait-il qu'elles disposent de capacités que nous ignorons encore ?[n][uf 1 1][e]

[msg MSG_259_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 10 0 0][uf 5 13 22 1 7]Bonne idée. Je vais essayer.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 11 0 0]Bonjour à toutes les plantes. Ici Aigis. Si vous m'entendez, merci de répondre.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 0 0 0 12 0 0]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 13 0 0]Malheureusement, je n'ai pas eu de réponse.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 14 0 0]La communication va être difficile avec mes compétences actuelles. Il faudra que j'y réfléchisse à l'avenir.[n][uf 1 1][e]

[msg MSG_263_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 15 0 0]J'avais déjà des connaissances préalables sur les "plantes", mais c'est la première fois que j'en voyais d'aussi près.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 16 0 0]Ces petites graines et ces pousses dans la terre peuvent changer très rapidement.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 17 0 0]Est-ce la preuve qu'elles sont aussi vivantes ? C'est fascinant.[n][uf 1 1][e]

[msg MSG_265_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 18 0 0]J'aimerais regarder ces plantes pousser et documenter cette expérience pour mes archives personnelles.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 19 0 0][uf 4 21 7 7]Je vais m'occuper d'elles de toutes mes forces ![n][uf 1 1][e]

[msg MND_267_0_0]
[uf 0 5 65278][uf 2 1]Je me suis occupée des plants avec Aigis.[n][uf 1 1][e]

[msg MSG_269_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 20 0 0]Nous y avons passé plus de temps que je ne l'avais prévu.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 21 0 0]Je vais devoir effectuer plus de simulations pour éviter tout retard la prochaine fois.[n][uf 1 1][e]

[msg MND_270_0_0]
[uf 0 5 65278][uf 2 1]Grâce à nos efforts, on dirait que la récolte va être bonne.[n][uf 1 1][e]

[msg MSG_271_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 22 0 0]Il se fait tard. Nous devrions rentrer.[n][uf 1 1][e]

[msg MSG_277_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 23 0 0]Je me demandais...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 24 0 0]Ces plantes ont l'air en bien meilleure santé qu'avant notre intervention.[n][uf 1 1][e]

[msg MSG_278_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 6 65535 0 0][uf 3 1 1 0 0 25 0 0][uf 4 23 0 7 1 25 25]Est-ce que tu penses qu'elles sont heureuses que tu t'occupes d'elles, [uf 4 2] ?[n][uf 1 1][e]

[sel SEL_279_0_0 top]
[uf 0 5 65278][uf 2 1]C'est possible.[e]
[uf 0 5 65278][uf 2 1]C'est impossible.[e]
[uf 0 5 65278][uf 2 1]Et si tu demandais ?[e]

[msg MSG_282_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 6 65535 0 0][uf 3 1 1 0 0 26 0 0][uf 5 13 22 1 7]Oui, tu t'en occupes avec le plus grand soin. Il est évident que tu tiens à elles.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 6 65535 0 0][uf 3 1 1 0 0 27 0 0]Je suis certaine que ces plantes savent tout ce que tu fais pour elles.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 6 65535 0 0][uf 3 1 1 0 0 28 0 0]Je ferai de mon mieux pour les rendre heureuses, moi aussi.[n][uf 1 1][e]

[msg MSG_285_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 29 0 0][uf 4 23 0 7 0 25 25][uf 5 13 22 1 7]Je suis d'accord. Mais c'est la raison pour laquelle je suis aussi surprise.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 30 0 0]On dit que parler aux plantes est bon pour leur croissance, n'est-ce pas ?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 31 0 0]Je me demande si ces plantes ont aussi un cœur dont nous n'avons pas conscience.[n][uf 1 1][e]

[msg MSG_288_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 6 65535 0 0][uf 3 1 1 0 0 32 0 0][uf 5 13 22 1 7]Ce serait bien, si c'était possible.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 6 65535 0 0][uf 3 1 1 0 0 33 0 0]Je me demande si ces plantes ont aussi un cœur dont nous n'avons pas conscience.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 6 65535 0 0][uf 3 1 1 0 0 34 0 0]Nous les comprendrons peut-être mieux en continuant à nous en occuper ?[n][uf 1 1][e]

[msg MSG_292_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 6 65535 0 0][uf 3 1 1 0 0 35 0 0][uf 4 23 0 7 1 25 25]Regarder ces plantes me fait beaucoup réfléchir.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 6 65535 0 0][uf 3 1 1 0 0 36 0 0]Elles sont comme toi et les autres. Elles sont vivantes, elles aussi.[n][uf 1 1][e]

[msg MSG_294_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 6 65535 0 0][uf 3 1 1 0 0 37 0 0]Je veux les voir pousser de mes propres yeux.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 6 65535 0 0][uf 3 1 1 0 0 38 0 0][uf 4 21 7 7]Je vais faire tout ce qui est en mon pouvoir pour en prendre soin.[n][uf 1 1][e]

[msg MND_296_0_0]
[uf 0 5 65278][uf 2 1]Je me suis occupé des plants avec Aigis.[n][uf 1 1][e]

[msg MSG_298_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 39 0 0][uf 4 21 7 11]Pardon, c'est la première fois que je fais ceci. Je crois que je t'ai fait perdre du temps.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 6 65535 0 0][uf 3 1 1 0 0 40 0 0][uf 4 23 0 7 1 25 25]Je vais m'entraîner dans ma chambre pour aller plus vite la prochaine fois.[n][uf 1 1][e]

[msg MND_299_0_0]
[uf 0 5 65278][uf 2 1]Grâce à nos efforts, on dirait que la récolte va être bonne.[n][uf 1 1][e]

[msg MSG_300_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 6 65535 0 0][uf 3 1 1 0 0 41 0 0]Merci pour ton aide. Nous devrions rentrer.[n][uf 1 1][e]

[msg MSG_305_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 42 0 0]Les nuisibles n'ont pas fait autant de dégâts que je l'avais prévu. C'est un soulagement.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 43 0 0]Pourtant, nous n'avons pas pris de mesures contre eux. Quelle en est la cause, alors ?[n][uf 1 1][e]

[msg MSG_307_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 44 0 0]Oh, c'est...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 45 0 0]Regarde, [uf 4 2] ! J'ai repéré une larve de coccinelle ! Toute petite et adorable.[n][uf 1 1][e]

[sel SEL_308_0_0 top]
[uf 0 5 65278][uf 2 1]Débarrassons-nous-en.[e]
[uf 0 5 65278][uf 2 1]Laissons-la en paix.[e]
[uf 0 5 65278][uf 2 1]Garde-la loin de moi.[e]

[msg MSG_311_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 46 0 0]Non, nous ne pouvons pas.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 47 0 0]Les coccinelles sont des prédateurs naturels des insectes nuisibles qui abîment les plantes.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 48 0 0]C'est sans doute pour cela qu'elles poussent si bien.[n][uf 1 1][e]

[msg MSG_313_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 49 0 0]Je partage cet avis. Nous ne devons pas l'interrompre dans son repas.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 50 0 0]Les coccinelles sont des prédateurs naturels des insectes nuisibles qui abîment les plantes.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 51 0 0]Voilà qui explique l'absence de nuisibles aux alentours.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 52 0 0]Merci beaucoup, petite coccinelle.[n][uf 1 1][e]

[msg MSG_318_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 53 0 0]Tu n'as pas l'air à ton aise. Tu n'as pas à craindre qu'elle te morde, pourtant...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 54 0 0]Bon, je vais la déplacer sur une autre feuille.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 0 0 0 55 0 0]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 56 0 0]Elle ne tient pas en place.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 57 0 0]On dirait que la coccinelle veut être près de toi, [uf 4 2].[n][uf 1 1][e]

[msg MSG_323_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 58 0 0]Même dans ces petits bacs, il y a tant de vie...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 59 0 0]Personne n'est là pour leur apprendre quoi que ce soit. Ils font du mieux qu'ils peuvent.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 0 0 0 60 0 0]......[n][uf 1 1][e]

[msg MSG_324_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 61 0 0]Toutes mes excuses, j'étais distraite. Continuons à travailler.[n][uf 1 1][e]

[msg MND_326_0_0]
[uf 0 5 65278][uf 2 1]Je me suis occupée des plants avec Aigis.[n][uf 1 1][e]

[msg MSG_328_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 62 0 0]Pardon, [uf 4 2]. Mets du répulsif de ce côté, s'il te plaît.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 63 0 0]Pas de pitié pour les nuisibles.[n][uf 1 1][e]

[msg MND_329_0_0]
[uf 0 5 65278][uf 2 1]Grâce à nos efforts, les plants devraient bien pousser.[n][uf 1 1][e]

[msg MSG_330_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 64 0 0][uf 5 13 22 1 7]Feu vert d'un bout à l'autre. Je ne vois aucun problème.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 65 0 0]Voilà qui conclut notre mission du jour. Rentrons, maintenant.[n][uf 1 1][e]

[msg MSG_332_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 66 0 0]Les nuisibles n'ont pas fait autant de dégâts que je l'avais prévu. C'est un soulagement.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 67 0 0]Pourtant, nous n'avons pas pris de mesures particulières. Comment est-ce possible ?[n][uf 1 1][e]

[msg MSG_335_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 68 0 0]Oh, c'est...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 69 0 0]Regarde, [uf 4 2] ! Une larve de coccinelle ! Toute petite et adorable.[n][uf 1 1][e]

[sel SEL_336_0_0 top]
[uf 0 5 65278][uf 2 1]Débarrassons-nous-en.[e]
[uf 0 5 65278][uf 2 1]Laissons-la en paix.[e]
[uf 0 5 65278][uf 2 1]Garde-la loin de moi.[e]

[msg MSG_339_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 70 0 0]Non, nous ne pouvons pas ![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 71 0 0]Les coccinelles sont des prédateurs naturels des insectes nuisibles qui abîment les plantes.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 72 0 0]Voilà qui explique l'absence de nuisibles aux alentours.[n][uf 1 1][e]

[msg MSG_342_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 73 0 0]Oui. Nous ne devons pas l'interrompre dans son repas.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 74 0 0]Les coccinelles sont des prédateurs naturels des insectes nuisibles qui abîment les plantes.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 75 0 0]Voilà qui explique l'absence de nuisibles aux alentours.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 76 0 0]Merci beaucoup, petite coccinelle.[n][uf 1 1][e]

[msg MSG_346_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 77 0 0]Pardon. Les insectes te mettent mal à l'aise ? Je vais la mettre sur une autre feuille.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 0 0 0 78 0 0]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 79 0 0]Elle ne tient pas en place.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 80 0 0]On dirait que la coccinelle veut être près de toi, [uf 4 2].[n][uf 1 1][e]

[msg MSG_351_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 81 0 0]Même dans ces petits bacs, il y a tant de vie...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 82 0 0]Personne n'est là pour leur apprendre quoi que ce soit. Ils font du mieux qu'ils peuvent.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 0 0 0 83 0 0]......[n][uf 1 1][e]

[msg MSG_352_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 84 0 0]Pardon, j'étais distraite. On continue ?[n][uf 1 1][e]

[msg MND_354_0_0]
[uf 0 5 65278][uf 2 1]Je me suis occupée des plants avec Aigis.[n][uf 1 1][e]

[msg MSG_356_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 85 0 0]Oh, [uf 4 2], regarde...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 86 0 0]Il est peut-être indélicat d'intervenir, mais nous ne pouvons pas les laisser gâcher notre récolte.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 87 0 0]Portons assistance à la coccinelle, cette fois.[n][uf 1 1][e]

[msg MND_357_0_0]
[uf 0 5 65278][uf 2 1]Grâce à nos efforts, les plants devraient bien pousser.[n][uf 1 1][e]

[msg MSG_358_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 88 0 0][uf 5 13 22 1 7]Feu vert d'un bout à l'autre. Je ne vois aucun problème.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 89 0 0]Ça devrait suffire pour aujourd'hui. Rentrons.[n][uf 1 1][e]

