[msg MSG_000_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 159 65535 0 0][uf 3 1 1 0 0 1 0 0]Hoy me gustaría preparar un aperitivo que pegue con el té.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 159 65535 0 0][uf 3 1 1 0 0 2 0 0][uf 4 23 0 1 1 25 25]No estoy muy versada en el arte de la cocina, todo sea dicho.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 159 65535 0 0][uf 3 1 1 0 0 3 0 0][uf 4 23 0 1 0 25 25]Por eso, me gustaría hacer algo simple, como karume-yaki. ¿Te enseñaron tus profes a hacerlo?[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]Eso creo.[e]
[uf 0 5 65278][uf 2 1]No me acuerdo.[e]
[uf 0 5 65278][uf 2 1]¿Karumequé?[e]

[msg MSG_002_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 159 65535 0 0][uf 3 1 1 0 0 4 0 0]Excelente, me puedo ahorrar la explicación.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 159 65535 0 0][uf 3 1 1 0 0 5 0 0]Venga, comencemos.[n][uf 1 1][e]

[msg MSG_003_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 159 65535 0 0][uf 3 1 1 0 0 6 0 0]A ver... Primero coges el bicarbonato sódico que, cuando se somete a una descomposición térmica...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 159 65535 0 0][uf 3 1 1 0 0 7 0 0]Creo que será más rápido que te vaya enseñando sobre la marcha. Empecemos.[n][uf 1 1][e]

[msg MSG_003_5_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 159 65535 0 0][uf 3 1 1 0 0 8 0 0]El karume-yaki es un dulce que llegó desde Portugal durante el periodo Sengoku.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 159 65535 0 0][uf 3 1 1 0 0 9 0 0]"Karume" deriva del portugués "caramelo", que es igual en español, además...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 159 65535 0 0][uf 3 1 1 0 0 10 0 0][uf 4 23 0 1 1 25 25]Bueno, será más rápido que lo veas por ti misma. Empecemos.[n][uf 1 1][e]

[msg MSG_004_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 159 65535 0 0][uf 3 1 1 0 0 11 0 0]La clave está en controlar la temperatura. Hay que apagar el horno justo antes de que llegue a 130 grados.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 4 159 65535 0 0][uf 3 1 1 0 0 12 0 0][uf 4 23 0 1 4 25 25]Ay, no perdamos tiempo. Primero ponemos el azúcar en el cazo...[n][uf 1 1][e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]He preparado karume-yaki con Mitsuru.[n][uf 1 1][e]

[msg MSG_006_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 159 65535 0 0][uf 3 1 1 0 0 13 0 0]Qué nostalgia me da este sabor...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 159 65535 0 0][uf 3 1 1 0 0 14 0 0][uf 4 23 0 1 0 25 25]No cuesta mucho hacerlos y el sabor no es que sea muy complejo, pero bueno...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 159 65535 0 0][uf 3 1 1 0 0 15 0 0]Me gustan mucho. Y, sobre todo, me gusta que los hayamos hecho nosotras solas.[n][uf 1 1][e]

[msg MSG_007_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 159 65535 0 0][uf 3 1 1 0 0 16 0 0]¿Sabes? Cuando lo vi por primera vez, me pareció algo mágico.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 159 65535 0 0][uf 3 1 1 0 0 17 0 0]He intentado hacerlos muchas veces, pero siempre acababan quemados.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 159 65535 0 0][uf 3 1 1 0 0 18 0 0][uf 4 23 0 1 1 25 25]Supongo que es un recuerdo agridulce. Pero nunca me rendí. Seguí practicando...[n][uf 1 1][e]

[msg MSG_007_5_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 159 65535 0 0][uf 3 1 1 0 0 19 0 0]Y al final, nos ha llevado al éxito de hoy. ¿Qué opinas?[n][uf 1 1][e]

[sel SEL_008_0_0 top]
[uf 0 5 65278][uf 2 1]Es una gran inspiración.[e]
[uf 0 5 65278][uf 2 1]¿No se te da bien cocinar?[e]

[msg MSG_009_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 159 65535 0 0][uf 3 1 1 0 0 20 0 0][uf 5 13 4 1 5]Oírte decir eso hace que me alegre de haberlo compartido.[n][uf 1 1][e]

[msg MSG_010_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 4 159 65535 0 0][uf 3 1 1 0 0 21 0 0]¿No lo sabías?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 159 65535 0 0][uf 3 1 1 0 0 22 0 0][uf 4 23 0 1 0 25 25][uf 5 13 4 1 5]En cualquier caso, ahora que le he pillado el truco, dudo que se me olvide.[n][uf 1 1][e]

[msg MSG_011_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 159 65535 0 0][uf 3 1 1 0 0 23 0 0]En casa, solíamos organizar cenas formales y fiestas de té.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 159 65535 0 0][uf 3 1 1 0 0 24 0 0]Pero nunca me pareció particularmente admirable que alguien cocinara esos platos extravagantes por nosotros.[n][uf 1 1][e]

[msg MSG_011_5_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 159 65535 0 0][uf 3 1 1 0 0 25 0 0]Cocinar por mi cuenta también me permite hablar contigo como ahora.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 159 65535 0 0][uf 3 1 1 0 0 26 0 0][uf 4 23 0 1 1 25 25]¿Y no es ese tipo de familiaridad la clave para entenderse mejor?[n][uf 1 1][e]

[msg MSG_012_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 159 65535 0 0][uf 3 1 1 0 0 27 0 0]Creo que... esta es la pieza que me faltaba.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 159 65535 0 0][uf 3 1 1 0 0 28 0 0][uf 4 23 0 1 0 25 25]En vez de quejarme por ser inaccesible, necesitaba crear una oportunidad para cambiar.[n][uf 1 1][e]

[msg MND_012_3_0]
[uf 0 5 65278][uf 2 1]Al cocinar este plato nostálgico, Mitsuru ha[n]aprendido algo nuevo sobre sí misma...[n][uf 1 1][e]

[msg MSG_012_5_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 159 65535 0 0][uf 3 1 1 0 0 29 0 0]Me fascina la de cosas que se pueden aprender tan solo invitando a alguien a tomar el té.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 159 65535 0 0][uf 3 1 1 0 0 30 0 0][uf 4 23 0 1 0 25 25]Gracias, [uf 4 1]. Espero que podamos charlar así otro día.[n][uf 1 1][e]

[msg MSG_013_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 159 65535 0 0][uf 3 1 1 0 0 31 0 0]Ah, es verdad, quería pedirte un favor.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 159 65535 0 0][uf 3 1 1 0 0 32 0 0]Todavía queda algo de azúcar y bicarbonato sódico. ¿Crees que podrías ayudarme a hacer otra tanda?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 159 65535 0 0][uf 3 1 1 0 0 33 0 0][uf 4 23 0 1 1 25 25]Los karume-yaki se conservan mucho tiempo, podríamos preparar unos cuantos para los demás.[n][uf 1 1][e]

[msg MND_025_0_0]
[uf 0 5 65278][uf 2 1]Después de hacer karume-yaki con Mitsuru,[n]me voy a mi habitación.[n][uf 1 1][e]

