[msg MSG_000_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 1 0 0]Mmm, superlecker! War eine gute Entscheidung, das Gleiche wie du zu nehmen, [nl]-chan.[n][w][e]

[msg MSG_001_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 2 0 0]Oh, sag mal: Denkst du beim Fischessen nicht auch immer an das Meer?[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 3 0 0]Gehört wohl dazu, wenn man an der Küste lebt. Wir haben sogar unseren Urlaub am Strand verbracht.[n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 4 0 0][f 4 23 0 2 1 25 25]Hey, wenn das alles vorbei ist, sollten wir mal ganz woanders hin. Vielleicht in die Berge?[n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 5 0 0]Wir könnten draußen essen. Vielleicht sehen wir dann Rehe oder so. Was meinst du?[n][w][e]

[sel SEL_002_0_0 top]
[f 2 1]Klingt gut.[e]
[f 2 1]Gehen wir mit den anderen.[e]
[f 2 1]Nur wir beide?[f 2 9 1 1 344][e]
[f 2 1]Nein danke.[e]

[msg MSG_003_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 6 0 0][f 5 13 7 15 2]Oder?[n][w][e]

[msg MSG_004_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 7 0 0]Okay, dann sorge ich für das Mittagessen![n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 8 0 0]Man sieht es mir zwar nicht an, aber ich kann ganz gut kochen! Warte nur ab![n][w][e]

[msg MSG_005_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 9 0 0][f 5 13 7 5 2]Hm, ja, warum nicht, oder? Das ist wie eine Belohnung für die ganze harte Arbeit.[n][w][e]

[msg MSG_006_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 10 0 0]Okay, dann sorge ich für das Mittagessen![n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 11 0 0]Man sieht es mir zwar nicht an, aber ich kann ganz gut kochen! Warte nur ab![n][w][e]

[msg MSG_007_0_0 [Yukari Takeba]]
[f 2 1][bup 2 4 65535 65535 0 0][vp 1 0 0 12 0 0][f 5 13 7 15 2]Warum sagst du das auf einmal?[n][w][e]
[f 2 1][bup 2 4 65535 65535 0 0][vp 1 0 0 13 0 0]Nur wir zwei ...? S-So meinte ich das nicht.[n][w][e]
[f 2 1][bup 2 4 65535 65535 0 0][vp 1 0 0 14 0 0]Ich meine, nicht, dass ich nicht will! Ich ... ich bin nur noch nicht so weit.[n][w][e]
[f 2 1][bup 2 4 65535 65535 0 0][vp 1 0 0 15 0 0]Oh Gott, was rede ich da?![n][w][e]

[msg MSG_008_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 16 0 0]Jedenfalls, ähm ... es wäre sicher schön, mal irgendwie abzuhängen. Ich könnte uns sogar was kochen![n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 17 0 0][f 4 23 0 2 1 25 25]Man sieht es mir zwar nicht an, aber ich kann ganz gut kochen! Warte nur ab![n][w][e]

[msg MSG_009_0_0 [Yukari Takeba]]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 18 0 0]Hm? Warum nicht?[n][w][e]

[msg MSG_010_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 19 0 0]Falls du dir Sorgen ums Essen machst, darum kümmere ich mich![n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 20 0 0][f 4 23 0 2 0 25 25]Man sieht es mir zwar nicht an, aber ich kann ganz gut kochen! Warte nur ab![n][w][e]

[msg MSG_011_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 21 0 0]Hehe, wir haben schon lange nicht an einen Urlaub gedacht. Ich werde ganz aufgeregt, wenn ich nur daran denke![n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 22 0 0][f 4 23 0 2 0 25 25]Ich weiß nicht, wie ich das sagen soll, [nl]-chan ... aber mit dir ...[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 23 0 0]... fühle ich mich nicht so einsam.[n][w][e]

[msg MSG_012_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 24 0 0]Ich habe natürlich Freunde ... Und dann sind da noch alle im Wohnheim, aber ...[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 25 0 0][f 4 23 0 2 3 25 25]Aber es fühlt sich immer so an, als könnte ich nicht ich selbst sein ...[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 26 0 0]Vielleicht liegt es an meiner Familie, aber ... ich schubse die Leute immer weg, ohne es zu merken.[n][w][e]

[msg MSG_012_3_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 27 0 0]Aber in letzter Zeit ändert sich das.[n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 28 0 0][f 4 23 0 2 1 25 25]Und ich glaube, das liegt an dir, [nl].[n][w][e]

[msg MND_013_0_0]
[f 2 1]Yukari vertraut mir.[n][w][e]
[f 2 1]Wir scheinen uns nähergekommen zu sein ...[n][w][e]

[msg MSG_014_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 29 0 0]Das war richtig lecker. Aber es wird schon spät.[n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 30 0 0]Wollen wir gehen?[n][w][e]

[msg MND_015_0_0]
[f 2 1]Ich ging zurück zum Wohnheim ...[n][w][e]

