[msg MSG_000_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 1 0 0]T-Tut mir leid, dass ich dich hergebeten habe ...[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 2 0 0]Äh ... Ich wollte dich um einen Gefallen bitten ...[n][w][e]
[f 2 1][bup 2 6 65535 65535 0 0][vp 1 0 0 3 0 0][f 4 23 0 1 6 25 25]Ähm ...[n][w][e]

[msg MSG_001_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 4 0 0]E-Es geht um meine Mutter ...[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 5 0 0]Ich ... Ich will, dass du sie kennenlernst.[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 0 0 0 6 0 0]......[n][w][e]

[msg MSG_002_0_0 [Yukari Takeba]]
[f 2 1][bup 2 4 65535 65535 0 0][vp 1 0 0 7 0 0]Nicht falsch verstehen![n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 8 0 0][f 4 23 0 1 3 25 25]Es ist nur ... Ich habe versprochen, mich mit ihr zu treffen, aber ich habe irgendwie immer noch Angst.[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 9 0 0]Wenn ich sie sehe ... könnte es passieren, dass ich fiese Sachen sage ...[n][w][e]

[msg MSG_003_0_0 [Yukari Takeba]]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 10 0 0]Was, wenn wir uns nur noch mehr an den Kopf werfen? Ich will ihre Gefühle nicht verletzen ...[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 11 0 0]Ich bin mir über meine Gefühle immer noch nicht ganz im Klaren.[n][w][e]
[f 2 1][bup 2 6 65535 65535 0 0][vp 1 0 0 12 0 0][f 4 23 0 1 6 25 25]Aber ich will sie sehen ... denke ich.[n][w][e]

[msg MSG_004_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 13 0 0]Deshalb dachte ich, es wäre toll, wenn du mitkommen könntest, [nl]-chan.[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 14 0 0]Du musst auch nicht wirklich etwas sagen ...[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 15 0 0]Ich fühle mich einfach sicherer, wenn du da bist.[n][w][e]

[msg MSG_005_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 16 0 0]Ich denke, mit dir an meiner Seite könnte ich meine Mutter mit etwas mehr Nachsicht behandeln.[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 17 0 0][f 4 23 0 1 3 25 25]Also, wenn es dir nicht zu viele Umstände macht ... Was denkst du?[n][w][e]

[sel SEL_006_0_0 top]
[f 2 1]Klar.[e]
[f 2 1]Das ist ein bisschen zu viel.[e]

[msg MSG_007_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 18 0 0]Du würdest es wirklich tun?! Danke![n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 19 0 0]Okay, ich rufe sie gleich an! Ich habe das so lange aufgeschoben ...[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 20 0 0][f 4 23 0 1 3 25 25]Tut mir leid, dass ich dich in meine Familienprobleme hineinziehe.[n][w][e]

[msg MSG_008_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 21 0 0]N-Na klar doch, ja![n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 22 0 0]Ich meine, die Eltern von irgendjemandem zu treffen, ist immer unangenehm ... Aber meine wären zehnmal schlimmer![n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 23 0 0][f 4 23 0 1 0 25 25]Das steht fest ...[n][w][e]
[f 2 1][bup 2 6 65535 65535 0 0][vp 0 0 0 24 0 0][f 4 23 0 1 6 25 25]......[n][w][e]

[msg MSG_009_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 25 0 0]Jedenfalls ... Es wird nicht sofort sein. Ich habe immer noch nicht das Selbstvertrauen, das ich brauche ...[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 26 0 0]Ich frage sie einfach, wann sie Zeit hat. Und wenn du an dem Tag noch nichts vorhast, überlegen wir es uns, okay?[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0][vp 0 0 0 27 0 0][f 4 23 0 1 3 25 25]......[n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 28 0 0][f 4 23 0 1 1 25 25]Es würde mir wirklich viel bedeuten, wenn du mitkommen würdest.[n][w][e]

[msg MSG_010_0_0 [Yukari Takeba]]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 29 0 0]Hey, ähm ...[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 30 0 0]Du denkst sicher, dein Leben wäre einfacher, wenn ich nicht so viele Probleme hätte.[n][w][e]

[sel SEL_011_0_0 top]
[f 2 1]Kann schon sein ...[e]
[f 2 1]Das ist nicht wahr.[e]

[msg MSG_012_0_0 [Yukari Takeba]]
[f 2 1][bup 2 2 65535 65535 0 0][vp 1 0 0 31 0 0]Autsch, das saß! Du sollst das doch abstreiten![n][w][e]
[f 2 1][bup 2 2 65535 65535 0 0][vp 1 0 0 32 0 0]Oh Mann ... Du bist so doof![n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 0 0 0 33 0 0][f 4 23 0 1 0 25 25]......[n][w][e]

[msg MSG_013_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 34 0 0]Haha ... War nur ein Scherz. Ich hab es schließlich selbst gesagt.[n][w][e]

[msg MSG_014_0_0 [Yukari Takeba]]
[f 2 1][bup 2 4 65535 65535 0 0][vp 1 0 0 35 0 0]Willst du damit ernsthaft sagen, dass du meine Probleme magst?[n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 36 0 0][f 4 23 0 1 1 25 25]Hey, mach dir keinen Kopf! Ich hab doch nur Spaß gemacht. Meine Güte.[n][w][e]

[msg MSG_015_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 37 0 0]Bald sind die Frühlingsferien.[n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 38 0 0]Die Zeit verging wie im Flug ... Wir sind bald schon im dritten Jahr.[n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 39 0 0]Und danach machen wir unseren Abschluss und gehen auf die Uni ... und dann ab in die Arbeitswelt, nehm ich an?[n][w][e]

[msg MSG_016_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 40 0 0]Wow, ist schwer vorstellbar ...[n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 41 0 0]Glaubst du ... wir sind dann noch zusammen?[n][w][e]

[sel SEL_017_0_0 top]
[f 2 1]Definitiv.[e]
[f 2 1]Wer weiß ...[e]

[msg MSG_018_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 42 0 0]Ja ...[n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 43 0 0]Das denke ich auch.[n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0][vp 0 0 0 44 0 0]......[n][w][e]

[msg MSG_019_0_0 [Yukari Takeba]]
[f 2 1][bup 2 6 65535 65535 0 0][vp 1 0 0 45 0 0]Da haben wir es wieder ...[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 46 0 0][f 4 23 0 1 0 25 25]Aber ich verstehe, was du meinst. Es ist schwer zu sagen, was die Zukunft bringen wird.[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 47 0 0]Ich frage mich, was aus uns werden wird ...[n][w][e]

[msg MSG_020_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 48 0 0]Dann lass uns erst mal über die nähere Zukunft reden.[n][w][e]

[msg MSG_021_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 49 0 0]Sollen wir in den Frühlingsferien etwas unternehmen? Oh, wir könnten nach Destinyland fahren![n][w][e]
[f 2 1][bup 2 1 65535 65535 1 0][vp 1 0 0 50 0 0]A-Aber nur wir beide, okay ...? Lad ja niemand anderes ein![n][w][e]
[f 2 1][bup 2 1 65535 65535 1 0][vp 0 0 0 51 0 0]......[n][w][e]

[msg MSG_022_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 1 0][vp 1 0 0 52 0 0]Also ... Wenn wir dort übernachten und so.[n][w][e]
[f 2 1][bup 2 1 65535 65535 1 0][vp 0 0 0 53 0 0]......[n][w][e]
[f 2 1][bup 2 1 65535 65535 1 0][vp 1 0 0 54 0 0]Ich frage mich, ob irgendjemand in den Wohnheimen merken würde, wenn wir eine Nacht wegbleiben würden ...[n][w][e]
[f 2 1][bup 2 1 65535 65535 1 0][vp 0 0 0 55 0 0]......[n][w][e]
[f 2 1][bup 2 1 65535 65535 1 0][vp 1 0 0 56 0 0]Komischer Gedanke ...[n][w][e]
[f 2 1][bup 2 1 65535 65535 1 0][vp 0 0 0 57 0 0]......[n][w][e]
[f 2 1][bup 2 1 65535 65535 1 0][vp 1 0 0 58 0 0]W-Wir können später weiter darüber reden.[n][w][e]

[msg MSG_023_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 59 0 0]Halt dir auf jeden Fall ein paar Tage in den Frühlingsferien frei, okay?[n][w][e]

