[msg MSG_000_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 1 0 0]"Guerres de ninjas"...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 2 0 0][uf 4 21 7 4]Cela fait-il référence à des groupes de ninjas qui s'opposent à l'écran ?[n][uf 1 1][e]

[msg MSG_000_5_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 6 65535 0 0][uf 3 1 1 0 0 3 0 0]"Chaque homme rêve d'être un ninja !"[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 4 0 0][uf 4 23 0 7 0 25 25]... D'après Junpei.[n][uf 1 1][e]

[msg MSG_900_0_0 [Génie du mal]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 5 0 0]Haha ! Quand j'activerai cette arme, le pays tout entier sera... Quoi ? Mes hommes ! Où sont-ils passés ?[n][uf 1 1][e]

[msg MSG_901_0_0 [Ninja]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 6 0 0]Tes hommes ? Ils se reposent...[n][uf 1 1][e]

[msg MSG_902_0_0 [Génie du mal]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 7 0 0]Que... Qui est là ? Montre-toi ![n][uf 1 1][e]

[msg MSG_903_0_0 [Ninja]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 8 0 0]Je suis une ombre. J'approche en silence... et je frappe.[n][uf 1 1][e]

[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]... C'est un film d'action à suspense qui en fait des tonnes.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Nous avons découvert l'histoire des ninjas et leurs techniques de combat hallucinantes...[n][uf 1 1][e]

[msg MSG_002_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 9 0 0]J'ai ajouté des informations précieuses à mes bases de données.[n][uf 1 1][e]

[msg MSG_002_3_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 10 0 0]Être un ninja est le statut ultime qu'un homme peut atteindre.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 11 0 0]Au combat, leur corps déploie une puissance équivalente à celle d'armes spéciales très avancées.[n][uf 1 1][e]

[msg MSG_002_5_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 12 0 0]C'étaient des machines de guerre surentraînées, aux compétences de combat inégalées.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 13 0 0][uf 4 21 7 4]Compte tenu de leur immense puissance, je me demande pourquoi ils n'existent plus aujourd'hui...[n][uf 1 1][e]

[msg MSG_003_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 0 0 0 14 0 0]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 15 0 0]Une période glaciaire ?[n][uf 1 1][e]

[msg MSG_003_3_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 0 0 0 16 0 0]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 17 0 0]La révolution Internet ?[n][uf 1 1][e]

[msg MSG_003_5_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 0 0 0 18 0 0]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 19 0 0]Le monde ne le saura peut-être jamais.[n][uf 1 1][e]

[msg MSG_003_7_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 20 0 0]Merci beaucoup pour aujourd'hui.[n][uf 1 1][e]

[msg MSG_004_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 6 65535 0 0][uf 3 1 1 0 0 22 0 0]J'ai appris que "Hattori Hanzô" était en réalité un titre, pas un nom.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 6 65535 0 0][uf 3 1 1 0 0 23 0 0]Par conséquent, je t'appellerai désormais Ninja Hattori.[n][uf 1 1][e]

[msg MSG_005_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 0 0 0 24 0 0]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 6 65535 0 0][uf 3 1 1 0 0 25 0 0][uf 4 23 0 7 1 25 25][uf 4 21 7 7]C'était une tentative d'humour de ma part.[n][uf 1 1][e]

[msg MND_006_0_0]
[uf 0 5 65278][uf 2 1]J'ai décidé de retourner au dortoir avec Aigis.[n][uf 1 1][e]

