[msg MSG_TUTO_BTL01_DISCOVERE [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 1 20500 0 0]¡Espera! Hay una sombra ahí delante.[n][uf 1 1][e]

[msg MSG_TUTO_BTL02_DISCOVERE [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 1 20508 0 0]Hay otra sombra justo delante. Vamos, así os acostumbraréis rápido a combatir.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 65535 50 0 0][uf 3 1 1 0 1 20509 0 0]¡La batalla está a punto de empezar! ¡Permaneced alerta![n][uf 1 1][e]

[msg MSG_DISCOVERED_TBOX_00 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 81 0 0][uf 3 1 1 0 1 20517 0 0]Pero ¿qué...? Oye, aquí hay una especie de caja.[n][uf 1 1][e]

[msg MSG_DISCOVERED_TBOX_01 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 1 20518 0 0]Sí, hay cajas así por toda la Tártaro.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 1 20519 0 0]A veces contienen objetos útiles para el combate. Encuentra tantas como puedas.[n][uf 1 1][e]

[msg MSG_DISCOVERED_TBOX_02 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 81 0 0][uf 3 1 1 0 1 20520 0 0]Mola. Son como cofres del tesoro.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 81 0 0][uf 3 1 1 0 1 20521 0 0]¡Toma ya! ¡Abrámoslo y veamos qué hay dentro![n][uf 1 1][e]

[msg MSG_NOT_GET_TBOX [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 65535 81 0 0][uf 3 1 1 0 1 20522 0 0]¡Venga ya! ¡¿No te mueres de ganas por ver qué contiene?![n][uf 1 1][e]

[msg MSG_TUTO_BTL03_DISCOVERE [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 1 20524 0 0]Sombra detectada.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 1 20525 0 0]Parece que todavía no te ha visto. Aprovecha.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 1 20526 0 0]Intenta sorprenderla por la espalda, pero que no te vea.[n][uf 1 1][e]

[msg MSG_TUTO_BTL03_RUN_AWAY_ [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 4 65535 50 0 0][uf 3 1 1 0 1 20527 0 0]¡El enemigo va a detectarte! ¡Retrocede![n][uf 1 1][e]

[msg MSG_TUTO_BTL03_RUN_AWAY__2 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 1 20528 0 0]Casi te entregas al enemigo.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 1 20529 0 0]No bajes la guardia solo por tener experiencia en combate.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 1 20530 0 0]Por suerte, el enemigo todavía no te ha visto. Vuelve a intentar atacar por la espalda.[n][uf 1 1][e]

[msg MSG_TUTO_BTL04_DISCOVERE [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 1 20536 0 0]Detecto otra sombra justo delante.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 1 20537 0 0]Aprovecha lo que acabas de aprender. Intenta no alertar al enemigo mientras te mueves.[n][uf 1 1][e]

[msg MSG_TUTO_BTL04_RUN_AWAY_ [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4561 0 0]¡El objetivo de hoy es adquirir experiencia en combate! Huir no es una opción.[n][uf 1 1][e]

[msg MSG_TUTO_BTL04_RUN_AWAY__2 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 1 20540 0 0]Espero que aún no estés cansada porque es el momento de avanzar.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 1 20541 0 0]Ahora acércate al enemigo por detrás, con cuidado.[n][uf 1 1][e]

[msg MSG_DISCOVERED_STAIRS_00 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 81 0 0][uf 3 1 1 0 1 20548 0 0]Eh, ¡he encontrado unas escaleras![n][uf 1 1][e]

[msg MSG_DISCOVERED_STAIRS_01 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 65535 81 0 0][uf 3 1 1 0 1 20549 0 0]¡Espera! Estamos buscando el teletransportador, ¿no?[n][uf 1 1][e]

[msg MSG_DISCOVERED_STAIRS_02 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 1 20550 0 0]Justo lo que dijo Takeba. Por favor, prioriza volver a salvo.[n][uf 1 1][e]

[msg MSG_NOT_GET_MEDAL_TBOX [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 1 20557 0 0]Aprovecha la oportunidad. Prueba a abrir el cofre.[n][uf 1 1][e]

[msg MSG_MEDAL_INFO [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4567 0 0]Esa reacción... ¿Llevas un [uf 0 1 39]fragmento crepuscular[uf 0 1 27] encima?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]Intenta acercarlo al cofre del tesoro.[n][uf 1 1][e]

[msg MSG_DISCOVERED_RETDEV_00 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 1 20558 0 0]Parece que has encontrado un teletransportador.[n][uf 1 1][e]

[msg MSG_DISCOVERED_RETDEV_01 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 1 20559 0 0]Úsalo para volver a la entrada.[n][uf 1 1][e]

