[sel SEL_YESNO top]
[uf 0 5 65278][uf 2 1]Vamos.[e]
[uf 0 5 65278][uf 2 1]Aún no.[e]

[msg MSG_TARTAROS_BTL_MITSURU [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4116 0 0]Nos adentramos en territorio enemigo. ¿Estás lista para la batalla?[n][uf 1 1][e]

[msg MSG_TARTAROS_BTL_FUKA_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5006 0 0]El enemigo es fuerte. ¡Asegúrate de tenerlo todo listo antes de combatir![n][uf 1 1][e]

[msg MSG_TARTAROS_BTL_MITSURU_2 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4001 0 0]¿Estás lista?[n][uf 1 1][e]

[msg MSG_TARTAROS_BTL_FUKA_5 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5006 0 0]¿Todo listo?[n][uf 1 1][e]

