[sel SEL_BOSS top]
[uf 0 5 65278][uf 2 1]Todo listo.[e]
[uf 0 5 65278][uf 2 1]Espera...[e]

[msg MND_STOP_UFO_CATCHER]
[uf 0 5 65278][uf 2 1]Parece que no hay electricidad...[n][uf 1 1][e]

[msg MSG_SHOP_STOP_YUKARI [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1062 0 0]¿Qué sucede?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]¡Si no movemos el culo, se acabará la Hora Oscura![n][uf 1 1][e]

[msg MSG_SHOP_STOP_AEGIS [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6001 0 0]El enemigo nos espera, pero no tenemos tiempo que perder.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0]Prepárate para el combate.[n][uf 1 1][e]

[msg MSG_SHOP_STOP_SANADA [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3003 0 0]¿Qué haces?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0]¿Has terminado ya de prepararte? ¡Yo lo tengo todo listo![n][uf 1 1][e]

[msg MSG_SHOP_STOP_ARAGAKI [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0][uf 3 1 3 0 65535 9003 0 0]¿Qué te pasa?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0]Mueve el trasero y ponte manos a la obra.[n][uf 1 1][e]

[msg MSG_SHOP_STOP_AMADA [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7001 0 0]Em, ¿nos vamos?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]La sombra está ahí delante, ¿no? Deberíamos acabar con ella cuanto antes.[n][uf 1 1][e]

[msg MSG_OUT_STOP [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4008 0 0]Como pierdas más tiempo, la Hora Oscura desaparecerá.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]¡Prepárate para infiltrarte en el Escapade![n][uf 1 1][e]

[msg MND_NO_VDOOR]
[uf 0 5 65278][uf 2 1]...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]No veo ninguna puerta.[n][uf 1 1][e]

[msg MSG_CLUB_STOP [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Necesitas más compañeros en el grupo. Vuelve y organízalo.[n][uf 1 1][e]

[msg MSG_GO_INTO_CLUB [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]¿Estás lista?[n][uf 1 1][e]

[msg MSG_FUKA_LETS_GO [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Por favor, mucho cuidado...[n][uf 1 1][e]

[sel SEL_BOSS_G top]
[uf 0 5 65278][uf 2 1]Todo listo.[e]
[uf 0 5 65278][uf 2 1]Espera un momento.[e]

[sel SEL_MALL_SHORTCUT top]
[uf 0 5 65278][uf 2 1]Comisaría de Tatsumi Este[e]
[uf 0 5 65278][uf 2 1]Farmacia Aohige[e]
[uf 0 5 65278][uf 2 1]Tienda de antigüedades[e]
[uf 0 5 65278][uf 2 1]Callejón[e]
[uf 0 5 65278][uf 2 1]Mapa de la ciudad[e]
[uf 0 5 65278][uf 2 1]Cancelar[e]

[msg MND_FLD_ORDERN]
[uf 0 5 65278][uf 2 1]¿Adónde voy...?[n][uf 1 1][e]

