[msg MSG_Darkzone_01 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0][uf 3 1 3 0 65535 5072 0 0]¡Ah, mirad![n][uf 1 1][e]

[msg MSG_Darkzone_02 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Puede que haya objetos de valor en esta planta, así que presta atención.[n][uf 1 1][e]

[msg MSG_Darkzone_03 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 3 0 65535 5006 0 0]¡Por ahí! ¡Y cuidado, no estás sola![n][uf 1 1][e]

[msg MSG_Darkzone_04 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Cuesta ver con tanta oscuridad, pero el enemigo está en las mismas.[n][uf 1 1][e]

