[msg MSG_000_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 3 0 65535 5131 0 0]O anmitsu estava impecável.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0]Hmm... A pasta de feijão azuki deles estava na dose certa de doçura. Acho que tô viciada.[n][uf 1 1][e]

[msg MSG_001_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5075 0 0]Hum, [uf 4 1]-chan. Você gosta de doces?[n][uf 1 1][e]

[sel SEL_002_0_0 top]
[uf 0 5 65278][uf 2 1]Gosto.[e]
[uf 0 5 65278][uf 2 1]Na verdade, não.[e]
[uf 0 5 65278][uf 2 1]Nunca parei pra pensar.[e]

[msg MSG_003_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 65535 0 0][uf 3 1 3 0 65535 5098 0 0][uf 5 13 3 30 6]Sério? Eu também sou doida por doces.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 4 23 0 6 1 25 25]Isso me alegra.[n][uf 1 1][e]

[msg MSG_003_5_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0]Sei que as pessoas dizem que açúcar faz mal, mas ele tem alguns benefícios pra saúde.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 4 23 0 6 0 25 25]Aliás, a glicose é fonte essencial de energia para o cérebro.[n][uf 1 1][e]

[msg MSG_003_7_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Sabe quando dá aquela fominha depois de ficar pensando o dia todo?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Isso acontece por causa dos baixos níveis de glicose, o que faz o açúcar do sangue cair.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 4 23 0 6 1 25 25]E você sabia...[n][uf 1 1][e]

[msg MND_004_0_0]
[uf 0 5 65278][uf 2 1]Fuuka parece muito feliz.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Acho que nos aproximamos muito hoje.[n][uf 1 1][e]

[msg MSG_005_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 65535 0 0][uf 3 1 3 0 65535 5094 0 0]Ah...[n][uf 1 1][e]

[msg MSG_005_5_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Que pena... eu adoro doces.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 65535 0 0][uf 4 23 0 6 3 25 25]Achei que se gostássemos das mesmas coisas, eu poderia te preparar o almoço um dia, mas...[n][uf 1 1][e]

[msg MSG_005_7_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Cada um tem uma opinião, né...[n][uf 1 1][e]

[msg MND_006_0_0]
[uf 0 5 65278][uf 2 1]Fuuka parece meio decepcionada.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Acho que não nos aproximamos hoje...[n][uf 1 1][e]

[msg MSG_007_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5107 0 0][uf 5 13 3 15 6]Entendi... Você é do tipo que não tem um prato favorito?[n][uf 1 1][e]

[msg MSG_007_5_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 65535 0 0]Pra falar a verdade, também sou um pouco assim. O que eu gosto mesmo é de cozinhar.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 4 23 0 6 0 25 25]Sabe como as pessoas costumam ficar horas numa fila só pra comprar um doce superfamoso?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Não consigo entender por que alguém faria isso...[n][uf 1 1][e]

[msg MSG_007_7_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0]Haha, acho que somos um pouco parecidos... de um jeito meio estranho?[n][uf 1 1][e]

[msg MND_008_0_0]
[uf 0 5 65278][uf 2 1]Fuuka está rindo.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Eu aprendi mais a respeito dela hoje.[n][uf 1 1][e]

[msg MSG_009_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 3 0 65535 5062 0 0]Acho importante experimentar todo tipo de comida. Dessa forma, posso melhorar meus dotes culinários.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0]Se eu criar um novo prato, você gostaria de experimentar? Talvez eu prepare algo com açúcar negro...[n][uf 1 1][e]

[msg MND_010_0_0]
[uf 0 5 65278][uf 2 1]Continuamos nossa conversa no[n]caminho de volta para o dormitório.[n][uf 1 1][e]

