[msg MSG_SENDER_NAME]
[uf 0 5 65278][uf 2 1]☆Maiko☆[n][uf 1 1][e]

[msg MSG_001_0_0]
[uf 0 5 65278][uf 2 1]¡A jugar! [uf 1 3 145][n][uf 1 1][e]

[msg MSG_002_0_0]
[uf 0 5 65278][uf 2 1]Estoy en el santuario[n]¡Vente a jugar![n][uf 1 3 145][uf 1 3 145][uf 1 3 145][uf 1 3 145][uf 1 3 145][uf 1 3 145][uf 1 1][e]

[msg MSG_003_0_0]
[uf 0 5 65278][uf 2 1]¡Hola! [uf 1 3 145][n][uf 1 1][e]

[msg MSG_004_0_0]
[uf 0 5 65278][uf 2 1]¡Estoy aquííí! ¡Vamos a jugar en el santuario![n][uf 1 3 145][uf 1 3 145][uf 1 3 145][uf 1 3 145][uf 1 3 145][uf 1 3 145][uf 1 3 145][uf 1 6 0][uf 1 3 149][uf 1 3 149][uf 1 3 149][uf 1 3 149][uf 1 3 149][uf 1 3 149][uf 1 3 149][uf 1 3 149][uf 1 1][e]

[msg MSG_005_0_0]
[uf 0 5 65278][uf 2 1][uf 1 3 138][uf 1 1][e]

[msg MSG_006_0_0]
[uf 0 5 65278][uf 2 1]¿Cómo estás? Yo bien [uf 1 3 145][n][uf 1 1][e]

[msg MSG_007_0_0]
[uf 0 5 65278][uf 2 1][uf 1 3 138][uf 1 1][e]

[msg MSG_008_0_0]
[uf 0 5 65278][uf 2 1]Quiero verte[n][uf 1 1][e]

[msg MSG_009_0_0]
[uf 0 5 65278][uf 2 1]Promesa[n][uf 1 1][e]

[msg MSG_010_0_0]
[uf 0 5 65278][uf 2 1]¿Le has dicho a alguien que voy a fugarme de casa? [uf 1 3 156][n][uf 1 1][e]

[msg MSG_011_0_0]
[uf 0 5 65278][uf 2 1]Cuídate [uf 1 3 137][n][uf 1 1][e]

[msg MSG_012_0_0]
[uf 0 5 65278][uf 2 1]Quiero verte por última vez[n]Ven al santuario [uf 1 3 137] No voy a llevarme el teléfono, así que no responderé a las llamadas[n][uf 1 1][e]

[msg MSG_013_0_0]
[uf 0 5 65278][uf 2 1]Juguemos[n][uf 1 1][e]

[msg MSG_014_0_0]
[uf 0 5 65278][uf 2 1]No voy a fugarme de casa[n]¡Vamos a jugar en el santuario![n][uf 1 3 146][uf 1 3 145][uf 1 3 146][uf 1 3 145][uf 1 3 146][uf 1 3 145][uf 1 3 146][uf 1 3 145][uf 1 3 146][uf 1 3 145][uf 1 1][e]

[msg MSG_015_0_0]
[uf 0 5 65278][uf 2 1]Soy Maiko[n][uf 1 1][e]

[msg MSG_016_0_0]
[uf 0 5 65278][uf 2 1]¿Hoy puedes jugar?[n][uf 1 1][e]

[msg MSG_017_0_0]
[uf 0 5 65278][uf 2 1][uf 1 3 145]Hola[uf 1 3 145][n][uf 1 1][e]

[msg MSG_018_0_0]
[uf 0 5 65278][uf 2 1]Quiero jugar contigo [n][uf 1 3 132][uf 1 3 137][uf 1 3 132][uf 1 3 137][uf 1 3 132][uf 1 3 137][uf 1 3 132][uf 1 3 137]muchooo[n][uf 1 3 132][uf 1 3 137][uf 1 3 132][uf 1 3 137][uf 1 3 132][uf 1 3 137][uf 1 3 132][uf 1 3 137]Y también quiero hablar contigo[n][uf 1 3 132][uf 1 3 137][uf 1 3 132][uf 1 3 137][uf 1 3 132][uf 1 3 137][uf 1 3 132][uf 1 3 137][uf 1 1][e]

[msg MSG_019_0_0]
[uf 0 5 65278][uf 2 1]Holiii[n][uf 1 1][e]

[msg MSG_020_0_0]
[uf 0 5 65278][uf 2 1]¿Hoy vamos a jugar?[n][uf 1 1][e]

[msg MSG_021_0_0]
[uf 0 5 65278][uf 2 1]¿Estás ocupada?[n][uf 1 1][e]

[msg MSG_022_0_0]
[uf 0 5 65278][uf 2 1]Hoy puedo jugar[n]Ven al santuario[uf 1 3 137][uf 1 3 137][n][uf 1 1][e]

[msg MSG_023_0_0]
[uf 0 5 65278][uf 2 1]¿A qué vamos a jugar hoy?[n][uf 1 1][e]

[msg MSG_024_0_0]
[uf 0 5 65278][uf 2 1]¡Quiero pasarme el día jugando![n]¡¡¡Y también quiero takoyaki!!![n][uf 1 1][e]

[msg MSG_025_0_0]
[uf 0 5 65278][uf 2 1]Domingo [uf 1 3 140][n][uf 1 1][e]

[msg MSG_026_0_0]
[uf 0 5 65278][uf 2 1]¿Crees que Pelos estará hoy en el santuario? Yo no puedo ir porque tengo cole, pero juega tú con él, porfa[n][uf 1 1][e]

[msg MSG_027_0_0]
[uf 0 5 65278][uf 2 1]Hola[n][uf 1 1][e]

[msg MSG_028_0_0]
[uf 0 5 65278][uf 2 1]¿Vas a venir hoy?[n][uf 1 1][e]

[msg MSG_029_0_0]
[uf 0 5 65278][uf 2 1](Sin asunto)[n][uf 1 1][e]

[msg MSG_030_0_0]
[uf 0 5 65278][uf 2 1]Quiero verte[n][uf 1 1][e]

