[msg MSG_000_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]Soy yo.[n][uf 1 1][e]

[msg MSG_001_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 0 2 0 0]Informe desde el lugar de los hechos. Ya hemos terminado.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 0 3 0 0]El monorraíl no ha sufrido daños significativos.[n][uf 1 1][e]

[msg MSG_002_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 1 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]Buen trabajo, Kirijo.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 1 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]Cuando me enteré de que habían secuestrado un monorraíl, me temí lo peor, pero lo habéis solucionado muy bien.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 1 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]Ya no tengo que preocuparme por los titulares de mañana.[n][uf 1 1][e]

[msg MSG_003_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 50 0 0][uf 3 1 1 0 0 7 0 0]El equipo ha hecho un trabajo increíble.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 50 0 0][uf 3 1 1 0 0 8 0 0]Han aprendido mucho en muy poco tiempo.[n][uf 1 1][e]

[msg MSG_004_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 9 0 0]Pero ¿qué les pasaba a las sombras?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]Nunca se habían apoderado de un monorraíl. Esto se está pasando de castaño oscuro.[n][uf 1 1][e]

[msg MSG_005_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 11 0 0]Investigaré al respecto.[n][uf 1 1][e]

[msg MSG_006_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 0 12 0 0]¿Eso significa... que ya ha empezado?[n][uf 1 1][e]

[msg MSG_007_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]Mmm..., no saquemos conclusiones precipitadas.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]Tenemos que estudiar su comportamiento en busca de patrones o pistas.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 15 0 0]No podemos estar siempre esperando a que den el primer paso.[n][uf 1 1][e]

[msg MSG_008_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 65535 50 0 0][uf 3 1 1 0 0 16 0 0]Si tuviera más poder, las cosas no serían tan difíciles para los demás.[n][uf 1 1][e]

[msg MSG_009_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 17 0 0]No seas tan dura contigo misma. Lo estás haciendo bien.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 18 0 0]Por cierto...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 19 0 0]¿Tienes algo de beber, Sanada?[n][uf 1 1][e]

[msg MSG_010_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 4 65535 65535 0 0][uf 3 1 0 0 0 20 0 0]¿Eh?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 4 65535 65535 0 0][uf 3 1 1 0 0 21 0 0]¿Por qué pareces tan cansado, Ikutsuki?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 4 65535 65535 0 0][uf 3 1 1 0 0 22 0 0]Espera... ¡No me digas que la bici de ahí fuera es tuya![n][uf 1 1][e]

[msg MSG_011_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 10 65535 65535 0 1][uf 3 1 1 0 0 23 0 0]Madre mía, mañana me va a doler hasta el paladar.[n][uf 1 1][e]

[msg MND_012_0_0]
[uf 0 5 65278][uf 2 1]El niño de mis sueños me advirtió sobre una dificultad.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Parece que su predicción se ha cumplido.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]¿Qué supondrá eso?[n][uf 1 1][e]

[msg MND_013_0_0]
[uf 0 5 65278][uf 2 1]...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Estoy demasiado cansada como para encontrarle explicación.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Debería echarme un rato en cuanto llegue a la residencia.[n][uf 1 1][e]

