[msg MSG_000_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]Oh, euh... Ne t'inquiète pas.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]Les cartouches par terre sont à blanc. Elles ne contiennent pas de poudre.[n][uf 1 1][e]

[msg MSG_000_3_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]A-Alors, que penses-tu de ma chambre ? Surprise ?[n][uf 1 1][e]

[msg MSG_000_3_1 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]Pour être franche... j'ai hésité à t'inviter ici.[n][uf 1 1][e]

[msg MSG_000_5_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]Je n'ai pas une décoration accueillante, pour qu'on se sente comme chez soi...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]Comment ai-je jamais pu penser que cette chambre était normale ?[n][uf 1 1][e]

[msg MSG_001_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]Mais c'est justement pour cela que je voulais te la montrer.[n][uf 1 1][e]

[msg MSG_001_1_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 8 0 0]Comme le décor l'indique, je suis une machine...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 9 0 0]Je ne serai jamais comme les humaines, comme Yukari ou Mitsuru.[n][uf 1 1][e]

[msg MSG_001_3_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]Ça me dérangeait, avant...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 11 0 0][uf 4 23 0 7 0 25 25]Mais j'ai trouvé une solution.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]Il y a quelque chose que moi seule peux dire, puisque je ne peux pas mourir.[n][uf 1 1][e]

[sel SEL_002_0_0 top]
[uf 0 5 65278][uf 2 1]De quoi s'agit-il ?[e]
[uf 0 5 65278][uf 2 1]J'ai du mal à saisir.[e]

[msg MSG_003_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]C'est très simple.[n][uf 1 1][e]

[msg MSG_004_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]Je... ne te quitterai jamais.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 15 0 0]Peu importe quand ou comment ta vie se terminera...[n][uf 1 1][e]

[msg MSG_004_2_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 1 0 0 16 0 0]À ce moment-là, je serai à tes côtés.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 1 0 0 17 0 0]Tu seras... toujours dans mon cœur.[n][uf 1 1][e]

[msg MSG_004_3_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 18 0 0]A-Ah oui... Hum...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 19 0 0]Accepterais-tu ceci ?[n][uf 1 1][e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]DEV: *Unused message labels. [n][uf 1 5 0]*If this appears, it is a bug.[n][uf 1 1][e]

[msg MSG_006_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 20 0 0]C'est une de mes pièces qui a dû être changée quand je me suis écroulée au Moonlight Bridge.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 21 0 0]J'ai demandé à Mitsuru de la faire envoyer ici.[n][uf 1 1][e]

[msg MSG_006_3_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 22 0 0]J'ai... grandi depuis.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 23 0 0]Je n'ai pas peur, je n'abandonnerai pas... Je me relèverai, encore et encore s'il le faut...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 24 0 0]Je combattrai à tes côtés et je te protégerai...[n][uf 1 1][e]

[msg MSG_006_5_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 1 0 0 25 0 0]Ceci est la preuve de ma détermination... et je veux que tu l'aies.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 1 0 0 26 0 0]C'est une partie de moi-même.[n][uf 1 1][e]

[msg MSG_007_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 27 0 0]Si vivre, c'est passer du temps avec ceux avec qui on a noué des liens...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 28 0 0]Alors je veux être plus proche de toi que n'importe qui d'autre.[n][uf 1 1][e]

[msg MSG_007_3_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 1 0 0 29 0 0]Le lien qui m'unit à toi est ma raison de vivre.[n][uf 1 1][e]

[msg MSG_007_4_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 1 0 0 30 0 0]Ce qu'il y a de plus important pour moi, c'est d'être à tes côtés.[n][uf 1 1][e]

[msg MND_008_0_0]
[uf 0 5 65278][uf 2 1]Aigis arbore un sourire sincère.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Je sens un lien fort avec Aigis...[n][uf 1 1][e]

[msg SYS_009_0_0]
[uf 0 5 65278][uf 2 1]Le lien social de L'Éon a atteint son niveau maximal. Il est désormais possible de créer [uf 0 1 35]Métatron[uf 0 1 27], l'assistant du trône ![n][uf 1 1][e]

[msg MSG_010_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 65535 65535 0 0][uf 3 1 1 0 0 31 0 0]Je, hum... J'ai encore une faveur à te demander...[n][uf 1 1][e]

[msg MSG_011_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 65535 65535 0 0][uf 3 1 1 0 0 32 0 0]À la base de mon cou, derrière le nœud de mon ruban...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 65535 65535 0 0][uf 3 1 1 0 0 33 0 0]C'est là que se trouve le plus important de mes composants.[n][uf 1 1][e]

[msg MSG_011_3_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 34 0 0]La psyché artificielle qui fait de moi ce que je suis...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 35 0 0]Mon moteur émotionnel... Le "Cœur de papillon".[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 36 0 0]Il est extrêmement sensible, et je n'ai pas le droit de l'exposer hors du milieu stérile du laboratoire...[n][uf 1 1][e]

[msg MSG_011_5_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 1 0][uf 3 1 1 0 0 37 0 0]Mais... je veux que tu le touches.[n][uf 1 1][e]

[msg MSG_011_6_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 1 0][uf 3 1 1 0 0 38 0 0]Si tu es en contact direct avec lui, tu y imprimeras sans doute tes informations génétiques.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 1 0][uf 3 1 1 0 0 39 0 0][uf 4 23 0 7 1 25 25]Et pourtant... je veux que tu le fasses.[n][uf 1 1][e]

[msg MSG_012_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 1 0 0 40 0 0]Je veux que tu laisses sur mon corps une preuve irréfutable de notre lien...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 1 0 0 41 0 0]Non pas un simple souvenir. Quelque chose de permanent... Quelque chose qui ne pourra jamais être effacé.[n][uf 1 1][e]

[msg MND_013_0_0]
[uf 0 5 65278][uf 2 1]Aigis me regarde intensément...[n][uf 1 1][e]

[sel SEL_014_0_0 top]
[uf 0 5 65278][uf 2 1]Hocher la tête[e]
[uf 0 5 65278][uf 2 1]Lui prendre la main[e]

[msg MSG_015_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 1 0 0 42 0 0]Merci.[n][uf 1 1][e]

[msg MSG_015_3_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 1 0 0 43 0 0]Je suis heureuse...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 1 0 0 44 0 0]S'il te plaît... viens plus près.[n][uf 1 1][e]

[msg MSG_016_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 45 0 0]Ah...[n][uf 1 1][e]

[msg MSG_016_3_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 1 0 0 46 0 0]Je suis heureuse...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 1 0 0 47 0 0]Bon...[n][uf 1 1][e]

[msg MSG_017_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 65535 65535 1 0][uf 3 1 1 0 0 48 0 0]Oh, hum...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 65535 65535 1 0][uf 3 1 1 0 0 49 0 0]Comme tu seras en contact direct avec mon cœur, euh...[n][uf 1 1][e]

[msg MSG_017_3_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 65535 65535 1 0][uf 3 1 1 0 0 50 0 0]Je m'excuse à l'avance si je dis quelque chose de bizarre ou si je produis des sons inhabituels...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 65535 65535 1 0][uf 3 1 1 0 0 51 0 0]Pour des raisons de sécurité, je vais désactiver les fonctions motrices de mes bras et de mes jambes.[n][uf 1 1][e]

[msg MSG_018_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 1 0][uf 3 1 1 0 0 52 0 0]Hum...[n][uf 1 1][e]

[msg MSG_018_1_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 1 0][uf 3 1 1 0 0 53 0 0]Peux-tu... défaire mon ruban ?[n][uf 1 1][e]

[msg MND_019_0_0]
[uf 0 5 65278][uf 2 1]Je suis resté un bon moment avec Aigis.[n][uf 1 1][e]

