[msg MSG_000_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 3 65535 65535 0 0][uf 3 1 3 0 65535 10054 0 0]*cough* *cough* Too much singing. My throat's killin' me...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 3 65535 65535 0 0][uf 4 25 101]......[n][uf 1 1][e]

[msg MSG_001_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0]We won't be able to hang out like this for much longer. My school life's coming to an end...[n][uf 1 1][e]

[msg MSG_002_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0][uf 3 1 3 0 65535 10064 0 0]You know, I haven't really taken much seriously before, but... now that I'm getting married...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 3 65535 65535 0 0][uf 4 23 0 101 10 25 25]Do you think I can make her happy?[n][uf 1 1][e]

[sel SEL_003_0_0 top]
[uf 0 5 65278][uf 2 1]You'll do fine.[e]
[uf 0 5 65278][uf 2 1]Just do your best.[e]
[uf 0 5 65278][uf 2 1]Probably not.[e]

[msg MSG_004_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 1 65535 65535 0 0][uf 3 1 3 0 65535 10023 0 0][uf 5 13 2 15 101]Yeah...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 1 65535 65535 0 0]I mean, plenty of couples are happy with their marriages, right? We just gotta be one of them.[n][uf 1 1][e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]Tomochika seems relieved...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I learned a little more about him today.[n][uf 1 1][e]

[msg MSG_006_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 1 65535 65535 0 0][uf 3 1 3 0 65535 10021 0 0][uf 5 13 2 30 101]Yeah, you're right. My best is all I can do![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 1 65535 65535 0 0]Thanks for the encouragement, dude.[n][uf 1 1][e]

[msg MND_007_0_0]
[uf 0 5 65278][uf 2 1]Tomochika seems relieved...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like we became a lot closer today.[n][uf 1 1][e]

[msg MSG_008_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 3 65535 65535 0 0][uf 3 1 3 0 65535 10071 0 0]C'mon! Show a little support![n][uf 1 1][e]

[msg MND_009_0_0]
[uf 0 5 65278][uf 2 1]Tomochika seems sad...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like we didn't get any closer today...[n][uf 1 1][e]

[msg MSG_010_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0]Huh... This might actually be the last time we...[n][uf 1 1][e]

[msg MSG_010_5_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 1 65535 65535 0 0][uf 3 1 3 0 65535 10086 0 0]Uh, alright! Let's do something else! How 'bout the arcade?[n][uf 1 1][e]

[msg MND_011_0_0]
[uf 0 5 65278][uf 2 1]After hanging out with Tomochika for[n]a while, I decided to go back to the dorm.[n][uf 1 1][e]

