[msg MSG_000_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]Hey, was willst du jetzt machen? Karaoke?[n][uf 1 1][e]

[msg MSG_001_0_0 [Kind]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 2 0 0][uf 5 21 0 1001]Mama! Wo bist du?[n][uf 1 1][e]

[msg MSG_002_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 0 0 0 3 0 0]...?[n][uf 1 1][e]

[msg MSG_003_0_0 [Kind]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 4 0 0][uf 5 21 0 1001]M-Mamaaaa! Wo biiiiist du?![n][uf 1 1][e]

[msg MSG_004_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]Hey, was hast du? Hast du dich verlaufen?[n][uf 1 1][e]

[msg MSG_005_0_0 [Kind]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 6 0 0][uf 5 21 0 1001]M-Mama hat gesagt, ich soll hier warten ... und ... und ... sie hat mir Geld gegeben, aber ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 7 0 0][uf 5 21 0 1001]Sie ... sie kommt nicht zurück ...[n][uf 1 1][e]

[msg MSG_006_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 0 8 0 0]Hey, nicht weinen ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 0 9 0 0]Jetzt ist doch alles in Ordnung.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]Ich bleibe hier bei dir, okay?[n][uf 1 1][e]

[msg MSG_006_5_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 0 11 0 0]Schau mal! Dort können wir Hilfe holen![n][uf 1 1][e]

[msg MSG_007_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]Komm mit.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]Der Polizist wird wissen, was zu tun ist.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]Er wird deine Mama finden, keine Sorge.[n][uf 1 1][e]

[msg MSG_008_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 0 15 0 0]Puh, da fällt mir ein Stein vom Herzen ... Gut, dass er die Eltern gefunden hat.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 65535 65535 0 0][uf 3 1 1 0 0 16 0 0][uf 4 23 0 2 2 25 25]Was denken die sich eigentlich, das arme Kind allein zu lassen?![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 65535 65535 0 0][uf 3 1 1 0 0 17 0 0]So was macht mich richtig wütend![n][uf 1 1][e]

[msg MSG_009_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0][uf 3 1 1 0 0 18 0 0]Aber ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0][uf 3 1 1 0 0 19 0 0]Aber meine Mutter ist wohl auch nicht anders.[n][uf 1 1][e]

[sel SEL_010_0_0 top]
[uf 0 5 65278][uf 2 1]Warum sagst du das?[e]
[uf 0 5 65278][uf 2 1]......[e]

[msg MSG_011_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 0 20 0 0]Warum willst du das wissen?[n][uf 1 1][e]

[msg MSG_012_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 21 0 0]Tut mir leid, ich wollte dich nicht aufziehen.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 22 0 0]Weißt du noch, dass ich dir gesagt habe, meine Mutter und ich stehen uns nicht sonderlich nah?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 23 0 0]Wenn du mich fragen würdest, wie sie als Mutter ist, würde ich sagen "schrecklich".[n][uf 1 1][e]

[msg MSG_012_3_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 24 0 0]Aber sie war nicht immer so ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0][uf 3 1 1 0 0 25 0 0][uf 4 23 0 2 3 25 25]Nach der Sache mit meinem Vater hat sie sich total verändert ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 26 0 0][uf 4 23 0 2 0 25 25]Sie lebt wahrscheinlich irgendwo mit einem ihrer Typen ... Ich will es gar nicht wissen.[n][uf 1 1][e]

[msg MSG_013_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 27 0 0]Willst du gar nicht wissen, was ich meine?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 28 0 0]Du versuchst wohl, nicht zu bohren ... oder ist das nur mein Wunschdenken?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 29 0 0]Na ja, du hast wohl recht, das ist ganz schön persönlich.[n][uf 1 1][e]

[msg MSG_014_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 30 0 0]Auch, wenn du fragen würdest, wüsste ich nicht, was ich sagen soll. Ich habe keine Ahnung, was sie treibt.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 31 0 0]Hängt wahrscheinlich mit einem ihrer Typen rum. Mehr weiß ich nicht.[n][uf 1 1][e]

[msg MSG_015_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 0 32 0 0]Aber ich will nicht mehr darüber reden, okay?[n][uf 1 1][e]

[msg MSG_016_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 33 0 0]Ähm, das bleibt unter uns, [uf 4 1]-chan, okay? Ich habe es nur dir erzählt.[n][uf 1 1][e]

[msg MND_017_0_0]
[uf 0 5 65278][uf 2 1]Yukari hat mir von ihrem schwierigen Verhältnis[n]zu ihrer Mutter berichtet.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Wir scheinen uns nähergekommen zu sein ...[n][uf 1 1][e]

[msg MSG_018_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 34 0 0]Sorry ... ich bin nicht mehr in Karaoke-Stimmung.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 35 0 0]Gehen wir nach Hause.[n][uf 1 1][e]

[msg MND_019_0_0]
[uf 0 5 65278][uf 2 1]Ich habe mich von Yukari verabschiedet und gehe zum Wohnheim zurück.[n][uf 1 1][e]

