[msg MSG_000_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0][uf 3 1 3 0 65535 10001 0 0]Eh, ¿qué pasa? Estoy a punto de irme a casa, ¿y tú?[n][uf 1 1][e]

[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]Parece que Tomochika quiere pasar el rato conmigo.[n][uf 1 1][e]

[msg MSG_002_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0][uf 3 1 3 0 65535 10004 0 0]Oye...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 3 65535 65535 0 0]Quiero hablar contigo...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 3 65535 65535 0 0]No tardaremos, no te preocupes.[n][uf 1 1][e]

[msg MSG_003_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 3 65535 65535 0 0][uf 3 1 3 0 65535 10092 0 0]Jo, tío, qué mal.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 3 65535 65535 0 0]Yo... Yo...[n][uf 1 1][e]

[msg MND_004_0_0]
[uf 0 5 65278][uf 2 1]¿Paso un rato con Tomochika después de clase?[n][uf 1 1][e]

[sel SEL_005_0_0 top]
[uf 0 5 65278][uf 2 1]Quedar con Tomochika[e]
[uf 0 5 65278][uf 2 1]Comprobar estado de vínculo social[e]
[uf 0 5 65278][uf 2 1]Ahora no[e]

[msg MSG_006_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0][uf 3 1 3 0 65535 10094 0 0]¿Eh? ¿Vienes conmigo?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0]Genial. Pues hagamos algo.[n][uf 1 1][e]

[msg MSG_007_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 4 65535 65535 0 0][uf 3 1 3 0 65535 10075 0 0]Ahí va, ¿en serio?[n][uf 1 1][e]

[msg MSG_008_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 2 65535 65535 0 0]Supongo que tenía que contártelo algún día.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 2 65535 65535 0 0]Venga, vamos al patio de abajo.[n][uf 1 1][e]

[msg MSG_009_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 3 65535 65535 0 0][uf 3 1 3 0 65535 10035 0 0]Gracias.[n][uf 1 1][e]

[msg MSG_010_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 3 65535 65535 0 0]Vamos a algún sitio donde podamos hablar en privado.[n][uf 1 1][e]

[msg MSG_011_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 6 65535 65535 0 0][uf 3 1 3 0 65535 10084 0 0]Ah, ¿tienes planes?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0]Vale. Hasta luego.[n][uf 1 1][e]

[msg MSG_012_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0][uf 3 1 3 0 65535 10010 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0]Estaba pensando que seguro que Takeba no se conforma con poco, ¿verdad?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0]Probablemente te hará falta ser todo un príncipe encantador para atraer su atención.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0]Bueno, tampoco es que a mí me importe. No estoy interesado en ella.[n][uf 1 1][e]

[msg MSG_013_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0][uf 3 1 3 0 65535 10063 0 0]Oye, una pregunta, ¿no habrás oído hablar del Rey gourmet?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0]Al parecer, hay un "gourmet" por aquí que está por encima del resto.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0]Dicen que es un alumno de nuestro instituto.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0]¿No molaría que nos dijera cuáles son los mejores sitios para ir a comer? Para cuando tengamos una cita.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0][uf 3 1 3 0 65535 10061 0 0]He oído que ahora le van los sándwiches, así que probablemente lo encontrarás comiéndose uno en la ciudad.[n][uf 1 1][e]

[msg MND_014_0_0]
[uf 0 5 65278][uf 2 1]Tomochika me ha dado una pista sobre el Rey gourmet.[n][uf 1 1][e]

[msg MSG_015_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0][uf 3 1 3 0 65535 10051 0 0]Mmm... Me considero bastante experto en ramen, pero el Rey gourmet está a otro nivel.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0]Al parecer, también conoce varios menús secretos. Por ejemplo, pide boles de arroz en el Hagakure.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 6 65535 65535 0 0]Se rumorea que va mucho al centro de la ciudad a comer sándwiches... Pero ¿quién narices es ese chico?[n][uf 1 1][e]

[msg MSG_016_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0][uf 3 1 3 0 65535 10020 0 0]Oye, ¿quieres saber cuál es el secreto para tener una relación feliz con la chica que te gusta?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0]Normalmente, quedarías con ella, charlaríais y os iríais conociendo mejor, ¿no?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0]Pero tienes que tener cuidado con lo que dices. Si pisas una mina, todo se esfumará.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0]Y si eso ocurre, se acabó, terminaréis la relación. Generalmente, no será para tanto, pero aun así...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0]Si ella te deja... Mmm, ¿qué podrías hacer?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0]Supongo que tendrías que arrodillarte y suplicarle que te perdone. Aunque te lleve días.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0][uf 3 1 3 0 65535 10083 0 0]¡No es que yo tenga que preocuparme por eso! Nadie conoce a Emiri mejor que yo.[n][uf 1 1][e]

[msg MSG_017_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0]Bueno, yo me voy ya. ¿Y tú?[n][uf 1 1][e]

[msg MSG_018_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0]Ah, eh, por cierto...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 3 65535 65535 0 0]Quería hablar contigo un momento...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 3 65535 65535 0 0]No tardaremos, no te preocupes.[n][uf 1 1][e]

[msg MSG_019_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0]Eh, pero no importa. Colega, esto no me gusta un pelo.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0]Yo... Yo...[n][uf 1 1][e]

[msg MSG_020_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0][uf 3 1 3 0 65535 10099 0 0]Uf, por fin se han acabado los exámenes.[n][uf 1 1][e]

[msg MSG_020_5_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0]Ah, ¡casi se me olvida! Por fin se han acabado los exámenes.[n][uf 1 1][e]

[msg MSG_021_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0]Uf, menos mal. ¡Parece que ambos hemos sobrevivido![n][uf 1 1][e]

[msg MSG_022_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0]Tío, he estudiado un montón por Emiri. Tener novia motiva mucho, ¿eh?[n][uf 1 1][e]

[msg MSG_023_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0]Colega, de repente estoy cansadísimo.[n][uf 1 1][e]

[msg MSG_024_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 1 65535 65535 0 0][uf 3 1 3 0 65535 10001 0 0]Eh, ¿qué pasa, colega? Yo me voy ya, ¿y tú?[n][uf 1 1][e]

[msg MSG_024_5_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 1 65535 65535 0 0]Bueno, yo me voy ya. ¿Y tú?[n][uf 1 1][e]

[msg MSG_025_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 1 65535 65535 0 0][uf 3 1 3 0 65535 10083 0 0]¿Eh? ¿Vienes conmigo?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0]Entonces, ¿qué te parece si vamos a comer ramen otra vez? Quiero que me cuentes más acerca de ti.[n][uf 1 1][e]

[msg MSG_026_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0][uf 3 1 3 0 65535 10005 0 0]¿Te vas? Hoy no tengo nada que hacer. Otra vez...[n][uf 1 1][e]

[msg MSG_026_5_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0]Por cierto, ¿te vas ya? Hoy no tengo nada que hacer. Otra vez...[n][uf 1 1][e]

[msg MSG_027_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 1 65535 65535 0 0][uf 3 1 3 0 65535 10068 0 0]Vaya, qué suerte tengo. Vale, pues vamos a algún sitio.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0]Dicho esto, tiene que ser donde tú sabes.[n][uf 1 1][e]

[msg MSG_028_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 1 65535 65535 0 0][uf 3 1 3 0 65535 10062 0 0]Oye, [uf 4 1]. Te vas ya, ¿verdad?[n][uf 1 1][e]

[msg MSG_028_5_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 1 65535 65535 0 0]Por cierto, te marchas ya, ¿no?[n][uf 1 1][e]

[msg MSG_029_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 1 65535 65535 0 0][uf 3 1 3 0 65535 10094 0 0]Perfecto, en ese caso...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0]Vamos al Wilduck. Tengo que hablar contigo de muchas cosas.[n][uf 1 1][e]

[msg MSG_030_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 3 65535 65535 0 0][uf 3 1 3 0 65535 10054 0 0][uf 4 25 101]...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 6 65535 65535 0 0]A-ah, [uf 4 1]. Quieres comer ramen, ¿no? Venga.[n][uf 1 1][e]

[msg MSG_030_5_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 6 65535 65535 0 0]A-ah, vale. Quieres comer ramen, ¿no? Venga.[n][uf 1 1][e]

[msg MSG_031_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0][uf 3 1 3 0 65535 10072 0 0]Muy bien, vamos. Creo que pediré un especial extragrande.[n][uf 1 1][e]

[msg MSG_032_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 3 65535 65535 0 0][uf 3 1 3 0 65535 10072 0 0]Ah, [uf 4 1]...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 3 65535 65535 0 0]¿Tienes un momento? Tengo que hablar contigo.[n][uf 1 1][e]

[msg MSG_032_5_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 3 65535 65535 0 0]Oye, eh... ¿Tienes un momento? Tengo que hablar contigo.[n][uf 1 1][e]

[msg MSG_033_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0][uf 3 1 3 0 65535 10046 0 0]Gracias por hacerme un hueco. Te lo agradezco, colega.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 6 65535 65535 0 0]Hoy no me apetece mucho comer ramen, así que vayamos al Wilduck.[n][uf 1 1][e]

[msg MSG_034_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 6 65535 65535 0 0][uf 3 1 3 0 65535 10064 0 0]...[uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 6 65535 65535 0 0]Si tienes un momento... ¿Podríamos hablar?[n][uf 1 1][e]

[msg MSG_034_5_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 6 65535 65535 0 0]Ah, vale. Si tienes un momento... ¿Podríamos hablar?[n][uf 1 1][e]

[msg MSG_035_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 3 65535 65535 0 0][uf 3 1 3 0 65535 10035 0 0]Muy bien. Entonces, hoy pago yo el ramen.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0]Te gusta el ramen, ¿verdad? Bien, pues vamos a comer ramen.[n][uf 1 1][e]

[msg MSG_036_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0][uf 3 1 3 0 65535 10013 0 0]Eh, ¿qué pasa?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 1 65535 65535 0 0]Hoy no tengo nada que hacer. Si estás libre, vayamos a comer ramen.[n][uf 1 1][e]

[msg MSG_036_5_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 1 65535 65535 0 0]Colega, hoy no tengo nada que hacer. Si estás libre, vayamos a comer ramen.[n][uf 1 1][e]

[msg MSG_037_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 1 65535 65535 0 0][uf 3 1 3 0 65535 10086 0 0]Guay, pues vamos.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 1 65535 65535 0 0]Hoy voy a pedir un especial extragrande y... Mmm, ¿pido también un bol de arroz?[n][uf 1 1][e]

[msg MSG_038_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 6 65535 65535 0 0][uf 3 1 3 0 65535 10084 0 0]Ah, que tienes cosas que hacer...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0]Vale. Hasta luego.[n][uf 1 1][e]

[msg MSG_039_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0][uf 3 1 3 0 65535 10026 0 0]Ah, ¿ya tienes planes?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 6 65535 65535 0 0]Pues vaya. Vale, nos vemos.[n][uf 1 1][e]

[msg MSG_040_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 3 65535 65535 0 0][uf 3 1 3 0 65535 10084 0 0]A-ah, vale...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 6 65535 65535 0 0]Uf, tío, ¿y qué hago ahora?[n][uf 1 1][e]

[msg MSG_041_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 6 65535 65535 0 0][uf 3 1 3 0 65535 10084 0 0]Ah, que tienes cosas que hacer...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0]Vale. Hasta luego.[n][uf 1 1][e]

[msg MSG_042_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 6 65535 65535 0 0][uf 3 1 3 0 65535 10084 0 0]Ah, que tienes cosas que hacer...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 3 65535 65535 0 0]Hasta luego.[n][uf 1 1][e]

[msg MSG_043_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 3 65535 65535 0 0][uf 3 1 3 0 65535 10084 0 0]Ah...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0]Eh, no te preocupes, no pasa nada. Nos vemos.[n][uf 1 1][e]

[msg MSG_044_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 3 65535 65535 0 0][uf 3 1 3 0 65535 10088 0 0]Ah, ¿estás ocupado?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 3 65535 65535 0 0]¿Qué se supone que debo hacer ahora?[n][uf 1 1][e]

[msg MSG_045_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 3 65535 65535 0 0][uf 3 1 3 0 65535 10084 0 0]Ah, vale. Quizá en otra ocasión.[n][uf 1 1][e]

[msg MSG_046_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 1 65535 65535 0 0][uf 3 1 3 0 65535 10083 0 0]¿Qué? ¿Tienes una cita o algo?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 1 65535 65535 0 0]Vale. Hasta luego.[n][uf 1 1][e]

[msg MND_GENERAL_EVENTPLAY]
[uf 0 5 65278][uf 2 1]Mensaje enviado por el guion. Repetición del evento del comité.[n][uf 1 1][e]

[msg MND_GENERAL_PERSPNA]
[uf 0 5 65278][uf 2 1]Siento que podemos estrechar lazos gracias a la Persona del arcano [uf 2 4 2], [uf 0 1 35][uf 2 4 5][uf 0 1 27].[n][uf 1 1][e]

[msg MND_GENERALSELECTMSG_MAX]
[uf 0 5 65278][uf 2 1]Siento un vínculo irrompible con [uf 2 4 0]...[n][uf 1 1][e]

[msg MND_GENERALMSG_BS_MAX]
[uf 0 5 65278][uf 2 1]Siento un vínculo irrompible con la pareja de ancianos...[n][uf 1 1][e]

[msg MND_GENERALSELECTMSG_RAN]
[uf 0 5 65278][uf 2 1]Creo que mi relación con [uf 2 4 0] se estrechará pronto.[n][uf 1 1][e]

[msg MND_GENERALMSG_BS_RANKUP]
[uf 0 5 65278][uf 2 1]Creo que mi relación con la pareja de ancianos se estrechará pronto.[n][uf 1 1][e]

[msg MND_GENERALSELECTMSG_NOR]
[uf 0 5 65278][uf 2 1]No creo que mi vínculo con [uf 2 4 0] se fortalezca más aunque pasemos tiempo juntos...[n][uf 1 1][e]

[msg MND_GENERALMSG_BS_NORMAL [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1]No creo que nuestro vínculo se fortalezca más aunque pasemos tiempo juntos.[n][uf 1 1][e]

[msg MND_GENERALSELECTMSG_MAX_2]
[uf 0 5 65278][uf 2 1]Parece que tu relación no puede avanzar más...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]¿Deberíamos pasar el rato juntos igualmente?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_SOLO_AS]
[uf 0 5 65278][uf 2 1]¿Paso un rato con [uf 2 4 0] después de clase?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_SOLO_DT]
[uf 0 5 65278][uf 2 1]¿Debería pasar el día con [uf 2 4 0]?[n][uf 1 1][e]

[msg MND__GENERAL_MSG_NET]
[uf 0 5 65278][uf 2 1]¿Debería pasar tiempo en línea jugando al MMORPG con [uf 2 4 0]?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_SOLO_NT]
[uf 0 5 65278][uf 2 1]¿Debería pasar la tarde con [uf 2 4 0]...?[n][uf 1 1][e]

[sel SEL_GENERALSELECTMSG_SOL top]
[uf 0 5 65278][uf 2 1]Pasar tiempo con [uf 2 4 0][e]
[uf 0 5 65278][uf 2 1]Comprobar vínculo social[e]
[uf 0 5 65278][uf 2 1]Da igual[e]

[msg MND_GENERAL_MSG_MULTIPLE]
[uf 0 5 65278][uf 2 1]¿Paso un rato en [uf 2 4 1] después de clase?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_FASHION_]
[uf 0 5 65278][uf 2 1]¿Paso un rato en el club de moda después de clase?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_BOOKSTOR]
[uf 0 5 65278][uf 2 1]¿Debería pasar el día en la librería?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_BOOKSTOR_2]
[uf 0 5 65278][uf 2 1]¿Paso un rato en la librería después de clase?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_MULTIPLE_2]
[uf 0 5 65278][uf 2 1]¿Debería pasar tiempo con [uf 2 4 1] esta noche...?[n][uf 1 1][e]

[sel SEL_GENERALSELECTMSG_MUL top]
[uf 0 5 65278][uf 2 1]Pasar un rato: [uf 2 4 1][e]
[uf 0 5 65278][uf 2 1]Comprobar vínculo social[e]
[uf 0 5 65278][uf 2 1]Da igual[e]

[sel SEL_GENERALSELECTMSG_FCL top]
[uf 0 5 65278][uf 2 1]Ir al club de moda.[e]
[uf 0 5 65278][uf 2 1]Comprobar vínculo social[e]
[uf 0 5 65278][uf 2 1]Da igual[e]

[sel SEL_GENERALSELECTMSG_BS top]
[uf 0 5 65278][uf 2 1]Entrar en la librería[e]
[uf 0 5 65278][uf 2 1]Comprobar vínculo social[e]
[uf 0 5 65278][uf 2 1]Da igual[e]

[msg MSG_GENERAL_EXAMREWARD_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]He visto tus notas. Buen trabajo.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Toma, de parte del director.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4108 0 0]Es tu recompensa por ser capaz de compaginar los estudios y nuestras... en fin, "actividades extraescolares".[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_0]
[uf 0 5 65278][uf 2 1]DEV: UNUSED LABEL[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_0_2]
[uf 0 5 65278][uf 2 1]Como he sacado la nota más alta en los exámenes, he obtenido: [uf 4 4 1 37 1 3].[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_0_2 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]He visto tus notas. Buen trabajo.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Toma, de parte del director.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4108 0 0]Es tu recompensa por ser capaz de compaginar los estudios y nuestras... en fin, "actividades extraescolares".[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_0_3 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4077 0 0]Ah, cierto. Hay algo más.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]He visto tus notas. Buen trabajo.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Toma, de parte del director.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4131 0 0]Es tu recompensa por ser capaz de compaginar los estudios y nuestras... en fin, "actividades extraescolares".[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_0_3]
[uf 0 5 65278][uf 2 1]Como he sacado la nota más alta en los exámenes, he obtenido: [uf 4 4 1 37 1 3].[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_0_4 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]He visto tus notas. Buen trabajo.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Toma, de parte del director.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4108 0 0]Es tu recompensa por ser capaz de compaginar los estudios y nuestras... en fin, "actividades extraescolares".[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_0_4]
[uf 0 5 65278][uf 2 1]DEV: UNUSED LABEL[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_0_5 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]He visto tus notas... Buen trabajo.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Es laudable que continúes destacando en el instituto mientras libras arduos combates.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0]Acepta este regalo para agradecerte tus esfuerzos.[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_0_5]
[uf 0 5 65278][uf 2 1]未使用ラベルです。[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_0_6 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0]He visto tus notas. Buen trabajo.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0]Es laudable que continúes destacando en el instituto mientras libras arduos combates.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0]Acepta este regalo para agradecerte tus esfuerzos.[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_1]
[uf 0 5 65278][uf 2 1]Como he sacado la nota más alta en los exámenes, he obtenido: [uf 4 4 1 37 1 3].[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_1 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]He visto tus notas. Buen trabajo.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Es laudable que continúes destacando en el instituto mientras libras arduos combates.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4108 0 0]Acepta este regalo para agradecerte tus esfuerzos.[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_1_2]
[uf 0 5 65278][uf 2 1]DEV: UNUSED LABEL[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_1_3]
[uf 0 5 65278][uf 2 1]Como he sacado la nota más alta en los exámenes, he obtenido: [uf 4 4 1 37 1 3].[n][uf 1 1][e]

