[msg MSG_000_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 3 0 65535 11094 0 0]My throat is so dry! I think I overdid it.[n][w][e]

[msg MSG_001_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0]Just so you know, this is just a pre-celebration for the end of our coaching duties![n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0]We still need to have a real celebration![n][w][e]

[msg MSG_002_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 3 0 65535 11007 0 0]You still have some time, right? What do you wanna do now?[n][w][e]

[sel SEL_003_0_0 top]
[f 2 1]Let's go to your place.[e]
[f 2 1]Let's go to a café.[e]
[f 2 1]Let's go to Wakatsu.[e]

[msg MSG_004_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 4 65535 65535 0 0][vp 3 0 65535 11076 0 0]Huh!? Are you serious!?[n][w][e]
[f 2 1][bup 106 3 65535 65535 0 0][f 4 23 0 106 3 25 25]Uh, my room is a mess right now! Maybe some other time, after I've cleaned up.[n][w][e]

[msg MSG_004_3_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0]How 'bout the café? It's not far from here.[n][w][e]

[msg MND_005_0_0]
[f 2 1]Yuko's excitement seems[n]to have died down.[n][w][e]
[f 2 1]I feel like we didn't get any closer today...[n][w][e]

[msg MSG_006_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 3 0 65535 11079 0 0][f 5 13 12 30 106]Perfect! I was thinking the same thing. I could use a cold drink right about now.[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0]Let's go.[n][w][e]

[msg MND_007_0_0]
[f 2 1]Yuko seems very happy.[n][w][e]
[f 2 1]I feel like we became a lot closer today.[n][w][e]

[msg MSG_008_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 3 0 65535 11077 0 0][f 5 13 12 15 106]Oh, are you hungry?[n][w][e]
[f 2 1][bup 106 3 65535 65535 0 0][f 4 23 0 106 3 25 25]Oh, hm... I'm not that hungry though.[n][w][e]

[msg MSG_008_3_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 3 65535 65535 0 0][f 4 25 106]......[n][w][e]

[msg MSG_008_5_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0]All right, sure, why not! I feel like I'm getting a little hungry anyway![n][w][e]

[msg MND_009_0_0]
[f 2 1]Yuko seems to be enjoying herself.[n][w][e]
[f 2 1]I learned a little more about her today.[n][w][e]

[msg MSG_010_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 3 0 65535 11082 0 0][f 4 23 0 106 1 25 25]You know, when we hang out like this and go to cafés or get food, it feels kinda like we're dat—[n][w][e]
[f 2 1][bup 106 1 65535 65535 1 0]Haha, I mean, uh... C'mon, let's go![n][w][e]

[msg MSG_011_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 3 0 65535 11093 0 0][f 4 23 0 106 1 25 25]You know, when we hang out like this and go to cafés or get food, it's almost like we're dating or something.[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0]Haha, I'm just kidding! C'mon, let's go![n][w][e]

[msg MND_012_0_0]
[f 2 1]After hanging out with Yuko,[n]I headed back to the dorm.[n][w][e]

