[msg MSG_000_0_0 [Kids]]
[f 2 1][vp 1 0 0 1 0 0]Coach and the girlfriend![n][w][e]

[msg MSG_001_0_0 [(SE) Spunky Boy]]
[f 2 1]Coach and the girlfriend![n][w][e]

[msg MSG_002_0_0 [(SE) Energetic Boy]]
[f 2 1]Coach and the girlfriend![n][w][e]

[msg MSG_003_0_0 [(SE) Meek-Looking Girl]]
[f 2 1]Coach and the girlfriend![n][w][e]

[msg MSG_004_0_0 [Meek-Looking Girl]]
[f 2 1][vp 1 0 0 5 0 0][f 5 21 0 1001]Coach! We raced 'em all one-on-one, and two of us actually won![n][w][e]

[msg MSG_005_0_0 [Spunky Boy]]
[f 2 1][vp 1 0 0 6 0 0][f 5 21 0 1002]That means we tied the sixth graders! Can you believe it!?[n][w][e]
[f 2 1][vp 1 0 0 7 0 0][f 5 21 0 1002]They said they're gonna let us use the schoolyard now! And they want to be friends with us![n][w][e]
[f 2 1][vp 1 0 0 8 0 0][f 5 21 0 1002]They think we're pretty fast for fourth graders, and told us we should play together sometime![n][w][e]

[msg MSG_006_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 9 0 0]Aww, you guys...[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 10 0 0][f 4 23 0 1 1 25 25]I never had a doubt! I know how hard you all worked![n][w][e]

[msg MSG_007_0_0 [Spunky Boy]]
[f 2 1][vp 1 0 0 11 0 0][f 5 21 0 1002]Wow, thanks! Um... B-Big Sis![n][w][e]

[msg MSG_008_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 12 0 0]Oh, you don't have to call me that if you don't want to. Auntie Yuko is fine.[n][w][e]

[msg MSG_009_0_0 [Spunky Boy]]
[f 2 1][vp 1 0 0 13 0 0][f 5 21 0 1002]One, two, three...![n][w][e]

[msg MSG_009_5_0 [Kids]]
[f 2 1][vp 1 0 0 14 0 0]Good luck with your girlfriend![n][w][e]

[msg MSG_010_0_0 [(SE) Spunky Boy]]
[f 2 1]Good luck with your girlfriend![n][w][e]

[msg MSG_011_0_0 [(SE) Energetic Boy]]
[f 2 1]Good luck with your girlfriend![n][w][e]

[msg MSG_012_0_0 [(SE) Meek-Looking Girl]]
[f 2 1]Good luck with your girlfriend![n][w][e]

[msg MSG_013_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 18 0 0]They called you my girlfriend till the very end...[n][w][e]

[sel SEL_014_0_0 top]
[f 2 1]Wanna make that true?[f 2 9 1 1 346][e]
[f 2 1]It's a little embarrassing.[e]
[f 2 1]They're just joking.[e]

[msg MSG_015_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 4 65535 65535 1 0][vp 1 0 0 19 0 0]Oh, okay... W-Wait, huh!?[n][w][e]

[msg MSG_016_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 2 65535 65535 0 0][vp 1 0 0 20 0 0]H-Hey! Don't laugh! Joking like that is bad for my heart![n][w][e]
[f 2 1][bup 106 3 65535 65535 0 0][vp 1 0 0 21 0 0][f 4 23 0 1 3 25 25]You really got me. Saying something like that out of nowhere...[n][w][e]

[msg MSG_017_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 22 0 0]Right? I know they're just being kids, but still...[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 23 0 0]Something about it gives me goosebumps.[n][w][e]

[msg MSG_018_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 24 0 0]Yeah, I know that.[n][w][e]
[f 2 1][bup 106 3 65535 65535 0 0][vp 1 0 0 25 0 0][f 4 23 0 1 3 25 25]Those kids even call Kaz my boyfriend when I'm with him...[n][w][e]

[msg MSG_019_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 0 0 0 26 0 0]......[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 27 0 0]You know what this feels like?[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 28 0 0]The end of some cheesy high school drama series.[n][w][e]

[msg MSG_019_5_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 3 65535 65535 0 0][vp 0 0 0 29 0 0]......[n][w][e]
[f 2 1][bup 106 3 65535 65535 0 0][vp 1 0 0 30 0 0]It's like the kids have left the nest...[n][w][e]

[sel SEL_020_0_0 top]
[f 2 1]Are you sad?[e]
[f 2 1]Are you relieved?[e]

[msg MSG_021_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 31 0 0]Now that it's suddenly so quiet... Yeah, a little.[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 32 0 0][f 4 23 0 1 1 25 25]Although, it was pretty tough at the beginning.[n][w][e]

[msg MSG_022_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 2 65535 65535 0 0][vp 1 0 0 33 0 0][f 5 13 12 5 106]Well, of course! I was constantly worried someone would get hurt.[n][w][e]

[msg MSG_023_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 3 65535 65535 0 0][vp 1 0 0 34 0 0]To be honest, it was tough at the beginning, but now that they're gone, it feels kinda lonely.[n][w][e]

[msg MSG_024_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 35 0 0]Teaching those kids how to race... It was pretty fun.[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 36 0 0][f 4 23 0 1 1 25 25]They looked so happy every time they got faster, and it made me happy too.[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 37 0 0]That feeling of wanting to help them just kept growing bigger and bigger.[n][w][e]

[msg MSG_025_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 38 0 0]You know, this might've been the first time I really put my heart into something.[n][w][e]

[msg MSG_025_5_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 39 0 0]And it's not that I've been slacking off as a team manager...[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 40 0 0][f 4 23 0 1 1 25 25]But, maybe helping and teaching people is more of my thing?[n][w][e]

[msg MSG_025_7_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 41 0 0]It kinda made me think. About the things I should do for my future, I mean.[n][w][e]

[msg MSG_026_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 42 0 0]Oh! By the way, I wanted to thank you, [nl]-chan.[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 43 0 0]Maybe we should throw a little party. You know, to celebrate our first attempt at coaching.[n][w][e]

[sel SEL_027_0_0 top]
[f 2 1]Let's do it.[e]
[f 2 1]Why?[e]

[msg MSG_028_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 44 0 0][f 5 13 12 15 106]Yay! I can't wait![n][w][e]

[msg MSG_029_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 3 65535 65535 0 0][vp 1 0 0 45 0 0]I mean, it took a lot of work to pull it off... Don't think it's a good idea?[n][w][e]

[msg MSG_030_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 46 0 0]Hmm, now where should we have the party at?[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 47 0 0][f 4 23 0 1 1 25 25]I kinda want it to be somewhat fancy. I'll look around for a place![n][w][e]

[msg MND_031_0_0]
[f 2 1]Yuko is full of enthusiasm.[n][w][e]
[f 2 1]I feel like our relationship has grown...[n][w][e]

[msg MSG_032_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 48 0 0]I didn't have much confidence at the beginning, so you being here with me was really—[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 49 0 0][f 4 23 0 1 1 25 25]...Well, let's talk about that next time. We'll have plenty of time at the party.[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 50 0 0]Shall we head home?[n][w][e]

[msg MND_033_0_0]
[f 2 1]I left school with Yuko.[n][w][e]

