[msg MSG_000_0_0 [Man in a Suit]]
[f 2 1][bup 113 3 65535 65535 0 0][vp 3 0 65535 12050 0 0]If only I could find someone who could steal our clients' hearts...[n][w][e]
[f 2 1][bup 113 0 65535 65535 0 0]There must be some handsome young woman out there who could drive all the housewives wild...[n][w][e]

[sel SEL_001_0_0 top]
[f 2 1]Right here.[e]
[f 2 1]Yep, somewhere out there.[e]

[msg MSG_002_0_0 [Man in a Suit]]
[f 2 1][bup 113 0 65535 65535 0 0][vp 3 0 65535 12071 0 0][f 4 25 113]......[n][w][e]
[f 2 1][bup 113 2 65535 65535 0 0]Where? I don't see anyone. For heaven's sake, quit wasting my precious time![n][w][e]

[msg MND_003_0_0]
[f 2 1]This must be the man Maya was[n]talking about, the one she saw on TV...[n][w][e]
[f 2 1]But he doesn't seem to be interested in me.[n][w][e]
[f 2 1]If I had enough [f 4 30 1 1 1 0] to be [f 4 31 1 4 1 0],[n]then maybe I could get his attention...[n][w][e]

[msg MSG_004_0_0 [Man in a Suit]]
[f 2 1][bup 113 2 65535 65535 0 0][vp 3 0 65535 12069 0 0]Of course, you imbecile! I just need to find her![n][w][e]

[msg MSG_005_0_0 [Man in a Suit]]
[f 2 1][bup 113 1 65535 65535 0 0][vp 3 0 65535 12008 0 0]My, aren't you cute...maybe...hmm.[n][w][e]
[f 2 1][bup 113 0 65535 65535 0 0]Can I interest you in being a part of a promotional campaign I'm running...? Oh, you're still in high school?[n][w][e]
[f 2 1][bup 113 0 65535 65535 0 0]Hmm... That would mean... Perhaps, if I trained her...[n][w][e]

[msg MND_006_0_0]
[f 2 1]The man seems to be[n]mumbling to himself...[n][w][e]
[f 2 1]It seems that my [f 4 30 1 1 1 0][n]has caught his attention.[n][w][e]

[msg MSG_007_0_0 [Man in a Suit]]
[f 2 1][bup 113 1 65535 65535 0 0][vp 3 0 65535 12004 0 0]Say, young lady... How would you like to have all your dreams come true? Well, do I have a golden opportunity for you.[n][w][e]

[sel SEL_008_0_0 top]
[f 2 1]Tell me more.[e]
[f 2 1]Not interested.[e]

[msg MSG_009_0_0 [Man in a Suit]]
[f 2 1][bup 113 3 65535 65535 0 0][vp 3 0 65535 12017 0 0]...Oh, really now. You'd pass up the chance to be rich beyond your wildest dreams?[n][w][e]
[f 2 1][bup 113 0 65535 65535 0 0]Well, if that's what you want...[n][w][e]

[msg MSG_010_0_0 [Man in a Suit]]
[f 2 1][bup 113 0 65535 65535 0 0][vp 3 0 65535 12061 0 0]Now, this stays between us, so don't go telling anyone, okay?[n][w][e]
[f 2 1][bup 113 0 65535 65535 0 0]...I can make you rich, 100% guaranteed.[n][w][e]
[f 2 1][bup 113 0 65535 65535 0 0]All you need is 20,000 yen, and your investment will multiply by ten— No, by one hundred![n][w][e]
[f 2 1][bup 113 1 65535 65535 0 0]And the best part is, you don't even have to lift a finger! You'll become fabulously wealthy overnight![n][w][e]
[f 2 1][bup 113 1 65535 65535 0 0]Just give me the 20,000 yen, and I'll take care of the rest.[n][w][e]
[f 2 1][bup 113 1 65535 65535 0 0][vp 3 0 65535 12093 0 0]Well, what do you say?[n][w][e]

[sel SEL_011_0_0 top]
[f 2 1]Okay.[e]
[f 2 1]Not interested.[e]

[msg MND_012_0_0]
[f 2 1]...I don't have enough money.[n][w][e]

[msg MSG_013_0_0 [Man in a Suit]]
[f 2 1][bup 113 3 65535 65535 0 0][vp 3 0 65535 12071 0 0]...What? You don't have that much? Well, I'm afraid the deal is off, then.[n][w][e]

[msg MND_014_0_0]
[f 2 1]I gave the man 20,000 yen.[n][w][e]

[msg MSG_015_0_0 [Man in a Suit]]
[f 2 1][bup 113 1 65535 65535 0 0][vp 3 0 65535 12018 0 0]That'll do it. I'll be in touch once your fortune has been made.[n][w][e]

[msg MSG_016_0_0 [Man in a Suit]]
[f 2 1][bup 113 3 65535 65535 0 0][vp 3 0 65535 12071 0 0]...Oh, really now. You'd pass up the chance to be rich beyond your wildest dreams?[n][w][e]
[f 2 1][bup 113 0 65535 65535 0 0]Well, if that's what you want...[n][w][e]

[msg MSG_017_0_0 [Man in a Suit]]
[f 2 1][bup 113 0 65535 65535 0 0][vp 3 0 65535 12008 0 0]Have you thought about what I told you last time?[n][w][e]
[f 2 1][bup 113 1 65535 65535 0 0]You can earn a fortune by investing just 20,000 yen.[n][w][e]
[f 2 1][bup 113 1 65535 65535 0 0]All you have to do is hand over the money.[n][w][e]
[f 2 1][bup 113 1 65535 65535 0 0][vp 3 0 65535 12093 0 0]Well, what do you say?[n][w][e]

[sel SEL_018_0_0 top]
[f 2 1]Okay.[e]
[f 2 1]Not interested.[e]

[msg MND_019_0_0]
[f 2 1]...I don't have enough money.[n][w][e]

[msg MSG_020_0_0 [Man in a Suit]]
[f 2 1][bup 113 3 65535 65535 0 0][vp 3 0 65535 12071 0 0]...What? You don't have that much? Well, I'm afraid the deal is off, then.[n][w][e]

[msg MND_021_0_0]
[f 2 1]I gave the man 20,000 yen.[n][w][e]

[msg MSG_022_0_0 [Man in a Suit]]
[f 2 1][bup 113 1 65535 65535 0 0][vp 3 0 65535 12018 0 0]That'll do it. I'll be in touch once your fortune has been made.[n][w][e]

[msg MSG_023_0_0 [Man in a Suit]]
[f 2 1][bup 113 3 65535 65535 0 0][vp 3 0 65535 12071 0 0]...Oh, really now. You'd pass up the chance to be rich beyond your wildest dreams?[n][w][e]
[f 2 1][bup 113 0 65535 65535 0 0]Well, if that's what you want...[n][w][e]

[msg MSG_024_0_0 [Man in a Suit]]
[f 2 1][bup 113 1 65535 65535 0 0][vp 3 0 65535 12015 0 0]I'll be in touch once your fortune has been made.[n][w][e]

[msg MSG_025_0_0 [Man in a Suit]]
[f 2 1][bup 113 3 65535 65535 0 0][vp 3 0 65535 12004 0 0]Oh, there you are... I've been looking for you.[n][w][e]
[f 2 1][bup 113 0 65535 65535 0 0]I have some unfortunate news regarding your investment.[n][w][e]
[f 2 1][bup 113 0 65535 65535 0 0]Things are not running as smoothly as planned. It still has the potential to turn a profit, but...[n][w][e]
[f 2 1][bup 113 1 65535 65535 0 0]I would require an additional 10,000 yen to get things back on track...[n][w][e]
[f 2 1][bup 113 1 65535 65535 0 0][vp 3 0 65535 12093 0 0]Are you willing to increase your investment by that much?[n][w][e]

[sel SEL_026_0_0 top]
[f 2 1]Sure.[e]
[f 2 1]Forget it.[e]

[msg MND_027_0_0]
[f 2 1]...I don't have enough money.[n][w][e]

[msg MSG_028_0_0 [Man in a Suit]]
[f 2 1][bup 113 3 65535 65535 0 0][vp 3 0 65535 12071 0 0]...What? You don't have that much? Well, I'm afraid the deal is off, then.[n][w][e]

[msg MND_029_0_0]
[f 2 1]I gave the man 10,000 yen.[n][w][e]

[msg MSG_030_0_0 [Man in a Suit]]
[f 2 1][bup 113 1 65535 65535 0 0][vp 3 0 65535 12093 0 0]Yes, yes, very good. I'll be in touch once your fortune has been made.[n][w][e]

[msg MSG_031_0_0 [Man in a Suit]]
[f 2 1][bup 113 3 65535 65535 0 0][vp 3 0 65535 12071 0 0]...Oh, really now. You'd pass up the chance to be rich beyond your wildest dreams?[n][w][e]
[f 2 1][bup 113 0 65535 65535 0 0]Well, if that's what you want...[n][w][e]

[msg MSG_032_0_0 [Man in a Suit]]
[f 2 1][bup 113 0 65535 65535 0 0][vp 3 0 65535 12001 0 0]Have you thought about what I told you last time?[n][w][e]
[f 2 1][bup 113 0 65535 65535 0 0]You can earn a fortune by investing just 10,000 yen more.[n][w][e]
[f 2 1][bup 113 1 65535 65535 0 0]All you have to do is give me the money.[n][w][e]
[f 2 1][bup 113 1 65535 65535 0 0][vp 3 0 65535 12093 0 0]Of course you'll do it, right?[n][w][e]

[sel SEL_033_0_0 top]
[f 2 1]Alright!.[e]
[f 2 1]No thanks.[e]

[msg MND_034_0_0]
[f 2 1]...I don't have enough money.[n][w][e]

[msg MSG_035_0_0 [Man in a Suit]]
[f 2 1][bup 113 3 65535 65535 0 0][vp 3 0 65535 12071 0 0]...What? You don't have that much? Well, I'm afraid the deal is off, then.[n][w][e]

[msg MND_036_0_0]
[f 2 1]I gave the man 10,000 yen.[n][w][e]

[msg MSG_037_0_0 [Man in a Suit]]
[f 2 1][bup 113 1 65535 65535 0 0][vp 3 0 65535 12018 0 0]Yes, yes, very good. I'll be in touch once your fortune has been made.[n][w][e]

[msg MSG_038_0_0 [Man in a Suit]]
[f 2 1][bup 113 3 65535 65535 0 0][vp 3 0 65535 12071 0 0]...Oh, really now. You'd pass up the chance to be rich beyond your wildest dreams?[n][w][e]
[f 2 1][bup 113 0 65535 65535 0 0]Well, if that's what you want...[n][w][e]

[msg MSG_039_0_0 [Man in a Suit]]
[f 2 1][bup 113 1 65535 65535 0 0][vp 3 0 65535 12035 0 0]You've got nothing to worry about. I'll be in touch once your fortune has been made.[n][w][e]

[msg MSG_040_0_0 [Man in a Suit]]
[f 2 1][bup 113 0 65535 65535 0 0][vp 3 0 65535 12004 0 0]Oh, there you are...[n][w][e]
[f 2 1][bup 113 3 65535 65535 0 0]We ran into a bit of a snag again. Some of the other investors decided to drop out...[n][w][e]
[f 2 1][bup 113 0 65535 65535 0 0]But since there are few investors, everyone will make even more of a profit! So, would you mind investing some more?[n][w][e]
[f 2 1][bup 113 1 65535 65535 0 0]Just 10,000 yen more. That should be plenty![n][w][e]
[f 2 1][bup 113 1 65535 65535 0 0][vp 3 0 65535 12067 0 0]Are you in?[n][w][e]

[sel SEL_041_0_0 top]
[f 2 1]I don't see why not.[e]
[f 2 1]Why not![e]

[msg MND_042_0_0]
[f 2 1]...I don't have enough money.[n][w][e]

[msg MSG_043_0_0 [Man in a Suit]]
[f 2 1][bup 113 3 65535 65535 0 0][vp 3 0 65535 12071 0 0]...What? You don't have that much? Well, I'm afraid the deal is off, then.[n][w][e]

[msg MND_044_0_0]
[f 2 1]I gave the man 10,000 yen.[n][w][e]

[msg MSG_045_0_0 [Man in a Suit]]
[f 2 1][bup 113 3 65535 65535 0 0][vp 3 0 65535 12071 0 0]...Oh, really now. You'd pass up the chance to be rich beyond your wildest dreams?[n][w][e]
[f 2 1][bup 113 0 65535 65535 0 0]Well, if that's what you want...[n][w][e]

[msg MSG_046_0_0 [Man in a Suit]]
[f 2 1][bup 113 0 65535 65535 0 0][vp 3 0 65535 12004 0 0]Have you thought about what I told you last time?[n][w][e]
[f 2 1][bup 113 1 65535 65535 0 0]I just need another 10,000 yen from you.[n][w][e]
[f 2 1][bup 113 1 65535 65535 0 0][vp 3 0 65535 12067 0 0]You'll do it, won't you?[n][w][e]

[sel SEL_047_0_0 top]
[f 2 1]Sure.[e]
[f 2 1]Hell no.[e]

[msg MND_048_0_0]
[f 2 1]...I don't have enough money.[n][w][e]

[msg MSG_049_0_0 [Man in a Suit]]
[f 2 1][bup 113 3 65535 65535 0 0][vp 3 0 65535 12071 0 0]...What? You don't have that much? Well, I'm afraid the deal is off, then.[n][w][e]

[msg MND_050_0_0]
[f 2 1]I gave the man 10,000 yen.[n][w][e]

[msg MSG_051_0_0 [Man in a Suit]]
[f 2 1][bup 113 3 65535 65535 0 0][vp 3 0 65535 12071 0 0]...Oh, really now. You'd pass up the chance to be rich beyond your wildest dreams?[n][w][e]
[f 2 1][bup 113 0 65535 65535 0 0]Well, if that's what you want...[n][w][e]

[msg MSG_052_0_0 [Man in a Suit]]
[f 2 1][bup 113 0 65535 65535 0 0][vp 0 0 0 0 0 0][f 4 25 113]......[n][w][e]
[f 2 1][bup 113 0 65535 65535 0 0]My foolish little apprentice...[n][w][e]
[f 2 1][bup 113 2 65535 65535 0 0][vp 3 0 65535 12070 0 0]Have you not yet realized that you are being deceived? Everything I've said has clearly been suspicious![n][w][e]
[f 2 1][bup 113 3 65535 65535 0 0]*sigh*[n][w][e]
[f 2 1][bup 113 3 65535 65535 0 0]Ignorance should be a crime.[n][w][e]

[msg MSG_053_0_0 [Man in a Suit]]
[f 2 1][bup 113 0 65535 65535 0 0][vp 3 0 65535 12052 0 0]Sure, you have some redeeming qualities, but if you remain this naive, everyone will take advantage of you.[n][w][e]
[f 2 1][bup 113 1 65535 65535 0 0]...Stick with me, and I'll show you how to be a winner.[n][w][e]

[msg MND_054_0_0]
[f 2 1]This man seems to be serious...[n][w][e]
[f 2 1]Should I spend some time[n]hearing him out...?[n][w][e]

[sel SEL_055_0_0 top]
[f 2 1]Yes please.[e]
[f 2 1]No thanks.[e]

[msg MSG_056_0_0 [Man in a Suit]]
[f 2 1][bup 113 2 65535 65535 0 0][vp 3 0 65535 12069 0 0]Oh my! You'd throw away this once-in-a-lifetime opportunity?[n][w][e]
[f 2 1][bup 113 3 65535 65535 0 0]Oh, what a shame. Ignorance truly is a crime.[n][w][e]

[msg MSG_057_0_0 [Man in a Suit]]
[f 2 1][bup 113 3 65535 65535 0 0][vp 3 0 65535 12077 0 0]Have you come back to be cheated out of even more money? It's high time you wised up.[n][w][e]
[f 2 1][bup 113 0 65535 65535 0 0]Stick with me, and I'll give you some advice worth that 40,000 yen.[n][w][e]

[msg MND_058_0_0]
[f 2 1]This man seems to be serious...[n][w][e]
[f 2 1]Should I spend some time[n]hearing him out...?[n][w][e]

[sel SEL_059_0_0 top]
[f 2 1]Yes please.[e]
[f 2 1]No thanks.[e]

[msg MSG_060_0_0 [Man in a Suit]]
[f 2 1][bup 113 2 65535 65535 0 0][vp 3 0 65535 12069 0 0]Oh my! You'd throw away this once-in-a-lifetime opportunity?[n][w][e]
[f 2 1][bup 113 3 65535 65535 0 0]Oh, what a shame. Ignorance truly is a crime.[n][w][e]

[msg MSG_061_0_0 [President Tanaka]]
[f 2 1][bup 113 0 65535 65535 0 0]Oh? Well, if it isn't [nl].[n][w][e]
[f 2 1][bup 113 1 65535 65535 0 0][vp 3 0 65535 12007 0 0]Are you busy at the moment? If not, I can teach you a valuable life lesson...[n][w][e]
[f 2 1][bup 113 1 65535 65535 0 0]Free of charge, of course.[n][w][e]

[msg MND_062_0_0]
[f 2 1]It seems like President Tanaka[n]wants to talk to me.[n][w][e]

[msg MND_063_0_0]
[f 2 1]Should I spend some time with him?[n][w][e]

[sel SEL_064_0_0 top]
[f 2 1]Talk to him[e]
[f 2 1]Check Social Link status[e]
[f 2 1]Not now[e]

[msg MSG_065_0_0 [President Tanaka]]
[f 2 1][bup 113 1 65535 65535 0 0][vp 3 0 65535 12067 0 0]My, aren't you enthusiastic...[n][w][e]

[msg MSG_066_0_0 [President Tanaka]]
[f 2 1][bup 113 3 65535 65535 0 0][vp 3 0 65535 12071 0 0]Hmph... It's not that the poor don't have a chance. It's just that they don't seize an opportunity.[n][w][e]

[msg MSG_067_0_0 [President Tanaka]]
[f 2 1][bup 113 0 65535 65535 0 0][vp 3 0 65535 12009 0 0]Oh? Well, if it isn't [nl]. Looks like you've something on your mind.[n][w][e]

[sel SEL_068_0_0 top]
[f 2 1]I'd like your autograph![e]
[f 2 1]Can I have an autograph?[e]

[msg MSG_069_0_0 [President Tanaka]]
[f 2 1][bup 113 0 65535 65535 0 0][vp 3 0 65535 12051 0 0]Hm? My autograph? Well, normally I'd charge an arm and a leg for this sort of thing...[n][w][e]
[f 2 1][bup 113 1 65535 65535 0 0]But—just this once—I'll make an exception and give you one for free. In return, you better spread the word about my generosity![n][w][e]

[msg MSG_070_0_0 [President Tanaka]]
[f 2 1][bup 113 1 65535 65535 0 0]Here you go. Stick it in a frame, and it'll make one valuable family heirloom.[n][w][e]

[msg MND_071_0_0]
[f 2 1]Now that I have an autograph from a[n]celebrity, I should show it to Elizabeth...[n][w][e]

[msg MSG_072_0_0 [President Tanaka]]
[f 2 1][bup 113 0 65535 65535 0 0][vp 3 0 65535 12008 0 0]Oh? Well, if it isn't [nl].[n][w][e]
[f 2 1][bup 113 1 65535 65535 0 0]Are you busy at the moment? If not, I can teach you a valuable life lesson...[n][w][e]
[f 2 1][bup 113 1 65535 65535 0 0]Free of charge, of course.[n][w][e]

[msg MSG_073_0_0 [President Tanaka]]
[f 2 1][bup 113 1 65535 65535 0 0][vp 3 0 65535 12093 0 0]My, aren't you enthusiastic. Then let's not waste any more time.[n][w][e]

[msg MSG_074_0_0 [President Tanaka]]
[f 2 1][bup 113 0 65535 65535 0 0][vp 3 0 65535 12008 0 0]Oh? Well, if it isn't [nl].[n][w][e]
[f 2 1][bup 113 0 65535 65535 0 0]You look like you have some time to spare. Shall I give you some more valuable life lessons?[n][w][e]
[f 2 1][bup 113 1 65535 65535 0 0]Free of charge, of course.[n][w][e]

[msg MSG_075_0_0 [President Tanaka]]
[f 2 1][bup 113 1 65535 65535 0 0][vp 3 0 65535 12067 0 0]I like your attitude. All right, then let's get right to it.[n][w][e]

[msg MSG_076_0_0 [President Tanaka]]
[f 2 1][bup 113 0 65535 65535 0 0][vp 3 0 65535 12012 0 0]Oh? Well, if it isn't [nl].[n][w][e]
[f 2 1][bup 113 3 65535 65535 0 0]I believe you're at the peak of adolescence, correct? Then what I have to say might prove very interesting...[n][w][e]
[f 2 1][bup 113 1 65535 65535 0 0]Naturally, it's free of charge.[n][w][e]

[msg MSG_077_0_0 [President Tanaka]]
[f 2 1][bup 113 1 65535 65535 0 0]Caught your attention, did I? Well, you better listen carefully, then.[n][w][e]

[msg MSG_078_0_0 [President Tanaka]]
[f 2 1][bup 113 3 65535 65535 0 0][vp 3 0 65535 12071 0 0]*sigh*[n][w][e]
[f 2 1][bup 113 0 65535 65535 0 0]Oh, [nl]... Are you here for another life lesson?[n][w][e]
[f 2 1][bup 113 0 65535 65535 0 0]As per usual, it'll be free of charge.[n][w][e]

[msg MSG_079_0_0 [President Tanaka]]
[f 2 1][bup 113 1 65535 65535 0 0][vp 3 0 65535 12050 0 0]I see... You're quite the honest young woman, I'll give you that.[n][w][e]

[msg MSG_080_0_0 [President Tanaka]]
[f 2 1][bup 113 0 65535 65535 0 0][vp 3 0 65535 12009 0 0]Ah, [nl]. Good evening.[n][w][e]
[f 2 1][bup 113 0 65535 65535 0 0]You came for another life lesson, didn't you? Why, it's written all over your face.[n][w][e]
[f 2 1][bup 113 1 65535 65535 0 0]Of course, it'll be entirely free of charge.[n][w][e]

[msg MSG_081_0_0 [President Tanaka]]
[f 2 1][bup 113 1 65535 65535 0 0][vp 3 0 65535 12093 0 0]Oh my, such enthusiasm. Have I got you hook, line and sinker?[n][w][e]

[msg MSG_082_0_0 [President Tanaka]]
[f 2 1][bup 113 0 65535 65535 0 0][vp 3 0 65535 12065 0 0]Ah, [nl]. Perfect timing.[n][w][e]
[f 2 1][bup 113 0 65535 65535 0 0]You're not busy at the moment, are you? Because I've got one riveting life lesson for you![n][w][e]
[f 2 1][bup 113 1 65535 65535 0 0]Entirely free of charge, might I add.[n][w][e]

[msg MSG_083_0_0 [President Tanaka]]
[f 2 1][bup 113 1 65535 65535 0 0][vp 3 0 65535 12067 0 0]Yes, yes, very good. That enthusiasm of yours is absolutely adorable.[n][w][e]

[msg MSG_084_0_0 [President Tanaka]]
[f 2 1][bup 113 0 65535 65535 0 0][vp 3 0 65535 12008 0 0]...Oh, well, if it isn't [nl].[n][w][e]
[f 2 1][bup 113 0 65535 65535 0 0]I can teach you a life lesson that you won't want to miss.[n][w][e]
[f 2 1][bup 113 1 65535 65535 0 0]And it's even free of charge.[n][w][e]

[msg MSG_085_0_0 [President Tanaka]]
[f 2 1][bup 113 0 65535 65535 0 0]I see...[n][w][e]
[f 2 1][bup 113 0 65535 65535 0 0]Then, for today... I have a story that's fresh off the press.[n][w][e]

[msg MSG_086_0_0 [President Tanaka]]
[f 2 1][bup 113 1 65535 65535 0 0][vp 3 0 65535 12093 0 0]You sure come by a lot, [nl]. I must be doing something right, then.[n][w][e]
[f 2 1][bup 113 0 65535 65535 0 0]But I suppose that means the value of a life lesson depends on the learner...[n][w][e]
[f 2 1][bup 113 0 65535 65535 0 0]Well, this one will be free of charge.[n][w][e]

[msg MSG_087_0_0 [President Tanaka]]
[f 2 1][bup 113 1 65535 65535 0 0][vp 3 0 65535 12067 0 0]Excellent. I've been waiting for— Ah, never you mind. That's not important.[n][w][e]

[msg MSG_088_0_0 [President Tanaka]]
[f 2 1][bup 113 0 65535 65535 0 0][vp 3 0 65535 12012 0 0]Oh, [nl].[n][w][e]
[f 2 1][bup 113 1 65535 65535 0 0]I do have something of a life lesson in mind... Though it might not necessarily apply to you. Still interested?[n][w][e]
[f 2 1][bup 113 1 65535 65535 0 0]It'll be 100% free.[n][w][e]

[msg MSG_089_0_0 [President Tanaka]]
[f 2 1][bup 113 1 65535 65535 0 0][vp 3 0 65535 12094 0 0]Heh, then let's not tarry any longer—the clock's ticking. Pay attention now.[n][w][e]

[msg MND_090_0_0]
[f 2 1]I should ask about the results[n]of my investment another time...[n][w][e]

[msg MSG_220_0_0 [President Tanaka]]
[f 2 1][bup 113 3 65535 65535 0 0][vp 3 0 65535 12014 0 0]Hmph... It's not that the poor don't have a chance. It's just that they don't seize the opportunities.[n][w][e]

[msg MSG_221_0_0 [President Tanaka]]
[f 2 1][bup 113 3 65535 65535 0 0][vp 3 0 65535 12014 0 0]Hmph... It's not that the poor don't have a chance. It's just that they pass up the opportunities.[n][w][e]

[msg MSG_222_0_0 [President Tanaka]]
[f 2 1][bup 113 3 65535 65535 0 0][vp 3 0 65535 12014 0 0]Hmph... It's not that the poor don't have a chance. It's just that they squander the opportunities.[n][w][e]

[msg MSG_223_0_0 [President Tanaka]]
[f 2 1][bup 113 3 65535 65535 0 0][vp 3 0 65535 12014 0 0]Hmph... It's not that the poor don't have a chance. It's just that they give up the opportunities.[n][w][e]

[msg MSG_224_0_0 [President Tanaka]]
[f 2 1][bup 113 3 65535 65535 0 0][vp 3 0 65535 12014 0 0]Hmph... It's not that the poor don't have a chance. It's just that they're afraid of the opportunities.[n][w][e]

[msg MSG_225_0_0 [President Tanaka]]
[f 2 1][bup 113 3 65535 65535 0 0][vp 3 0 65535 12014 0 0]Hmph... It's not that the poor don't have a chance. It's just that they waste the opportunities.[n][w][e]

[msg MSG_226_0_0 [President Tanaka]]
[f 2 1][bup 113 3 65535 65535 0 0][vp 3 0 65535 12014 0 0]Hmph... It's not that the poor don't have a chance. It's just that they don't have any initiative.[n][w][e]

[msg MSG_227_0_0 [President Tanaka]]
[f 2 1][bup 113 3 65535 65535 0 0][vp 3 0 65535 12014 0 0]Hmph... It's not that the poor don't have a chance. It's just that they don't care for the opportunities.[n][w][e]

[msg MSG_228_0_0 [President Tanaka]]
[f 2 1][bup 113 3 65535 65535 0 0][vp 3 0 65535 12014 0 0]Hmph... It's not that the poor don't have a chance. It's just that they don't notice the opportunities until it's too late.[n][w][e]

[msg MND_GENERAL_EVENTPLAY]
[f 2 1]Message issued by the script. [n][f 1 5 0]Comm Event Replay.[n][w][e]

[msg MND_GENERAL_PERSPNA]
[f 2 1]I feel as if we can grow closer thanks to the[n][f 2 4 2] Persona, [clr 35][f 2 4 5][clr 27]...[n][w][e]

[msg MND_GENERALSELECTMSG_MAX]
[f 2 1]I feel an unbreakable bond[n]with [f 2 4 0]...[n][w][e]

[msg MND_GENERALMSG_BS_MAX]
[f 2 1]I feel an unbreakable bond[n]with the elderly couple...[n][w][e]

[msg MND_GENERALSELECTMSG_RAN]
[f 2 1]I feel like I might grow closer[n]to [f 2 4 0] soon...[n][w][e]

[msg MND_GENERALMSG_BS_RANKUP]
[f 2 1]I feel like I might grow closer[n]to the elderly couple soon...[n][w][e]

[msg MND_GENERALSELECTMSG_NOR]
[f 2 1]I don't think our bond will grow[n]any stronger even if I spend[n]more time with [f 2 4 0]...[n][w][e]

[msg MND_GENERALMSG_BS_NORMAL [President Tanaka]]
[f 2 1]I don't think our bond will grow[n]any stronger even if I spend[n]more time with them...[n][w][e]

[msg MND_GENERALSELECTMSG_MAX_2]
[f 2 1]It doesn't seem that our relationship[n]can get any closer than it is...[n][w][e]
[f 2 1]Should I still spend time with them...?[n][w][e]

[msg MND_GENERAL_MSG_SOLO_AS]
[f 2 1]Should I spend some time after[n]school with [f 2 4 0]?[n][w][e]

[msg MND_GENERAL_MSG_SOLO_DT]
[f 2 1]Should I spend the day[n]with [f 2 4 0]?[n][w][e]

[msg MND__GENERAL_MSG_NET]
[f 2 1]Should I spend time online playing[n]the MMORPG with [f 2 4 0]...?[n][w][e]

[msg MND_GENERAL_MSG_SOLO_NT]
[f 2 1]Should I spend the evening[n]with [f 2 4 0]?[n][w][e]

[sel SEL_GENERALSELECTMSG_SOL top]
[f 2 1]Spend time with [f 2 4 0][e]
[f 2 1]Check Social Link[e]
[f 2 1]Never mind[e]

[msg MND_GENERAL_MSG_MULTIPLE]
[f 2 1]Should I spend some time after[n]school with the [f 2 4 1]?[n][w][e]

[msg MND_GENERAL_MSG_FASHION_]
[f 2 1]Should I spend some time after[n]school at the fashion club?[n][w][e]

[msg MND_GENERAL_MSG_BOOKSTOR]
[f 2 1]Should I spend the day at the bookstore?[n][w][e]

[msg MND_GENERAL_MSG_BOOKSTOR_2]
[f 2 1]Should I spend some time[n]after school at the bookstore?[n][w][e]

[msg MND_GENERAL_MSG_MULTIPLE_2]
[f 2 1]Should I spend the night[n]with [f 2 4 1]?[n][w][e]

[sel SEL_GENERALSELECTMSG_MUL top]
[f 2 1]Spend time w/ [f 2 4 1][e]
[f 2 1]Check Social Link[e]
[f 2 1]Never mind[e]

[sel SEL_GENERALSELECTMSG_FCL top]
[f 2 1]Go to the fashion club[e]
[f 2 1]Check Social Link[e]
[f 2 1]Never mind[e]

[sel SEL_GENERALSELECTMSG_BS top]
[f 2 1]Enter the bookstore[e]
[f 2 1]Check Social Link[e]
[f 2 1]Never mind[e]

[msg MSG_GENERAL_EXAMREWARD_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4029 0 0]Ah, [nl].[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]I saw your exam results. Good work.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Here, this is from the chairman.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4108 0 0]It's a reward for effectively balancing schoolwork as well as our... ahem, "extracurricular activities."[n][w][e]

[msg MND_GENERAL_EXAMREWARD_0]
[f 2 1]DEV: UNUSED LABEL[n][w][e]

[msg MND_GENERAL_EXAMREWARD_0_2]
[f 2 1]Since I placed at the top in the exams,[n]I also got this [f 4 4 1 37 1 3].[n][w][e]

[msg MSG_GENERAL_EXAMREWARD_0_2 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4029 0 0]Ah, [nl].[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]I saw your exam results. Good work.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Here, this is from the chairman.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4108 0 0]It's a reward for effectively balancing schoolwork as well as our... ahem, "extracurricular activities."[n][w][e]

[msg MSG_GENERAL_EXAMREWARD_0_3 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4077 0 0]Oh, right. There's something else...[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]I saw your exam results. Good work.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Here, this is from the chairman.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4131 0 0]It's a reward for effectively balancing schoolwork as well as our... ahem, "extracurricular activities."[n][w][e]

[msg MND_GENERAL_EXAMREWARD_0_3]
[f 2 1]Since I placed at the top in the exams,[n]I also got this [f 4 4 1 37 1 3].[n][w][e]

[msg MSG_GENERAL_EXAMREWARD_0_4 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4029 0 0]Ah, [nl].[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]I saw your exam results. Good work.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Here, this is from the chairman.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4108 0 0]It's a reward for effectively balancing schoolwork as well as our... ahem, "extracurricular activities."[n][w][e]

[msg MND_GENERAL_EXAMREWARD_0_4]
[f 2 1]DEV: UNUSED LABEL[n][w][e]

[msg MSG_GENERAL_EXAMREWARD_0_5 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4029 0 0]Ah, [nl].[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]I saw your exam results... Good work.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]It's admirable how you continue to excel in school while fighting arduous battle after battle.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0]I got you a gift to acknowledge all your hard work. Here, take it.[n][w][e]

[msg MND_GENERAL_EXAMREWARD_0_5]
[f 2 1]未使用ラベルです。[n][w][e]

[msg MSG_GENERAL_EXAMREWARD_0_6 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 6 65535 0 0][vp 3 0 65535 4029 0 0]Ah, [nl].[n][w][e]
[f 2 1][bup 5 0 6 65535 0 0]I saw your exam results. Good work.[n][w][e]
[f 2 1][bup 5 0 6 65535 0 0]It's admirable how you continue to excel in school while fighting arduous battle after battle.[n][w][e]
[f 2 1][bup 5 0 6 65535 0 0]I got you a gift to acknowledge all your hard work. Here, take it.[n][w][e]

[msg MND_GENERAL_EXAMREWARD_1]
[f 2 1]Since I placed at the top in the exams,[n]I also got this [f 4 4 1 37 1 3].[n][w][e]

[msg MSG_GENERAL_EXAMREWARD_1 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4029 0 0]Ah, [nl].[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]I saw your exam results. Good work.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]It's admirable how you continue to excel in school while fighting arduous battle after battle.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4108 0 0]I got you a gift to acknowledge all your hard work. Here, take it.[n][w][e]

[msg MND_GENERAL_EXAMREWARD_1_2]
[f 2 1]DEV: UNUSED LABEL[n][w][e]

[msg MND_GENERAL_EXAMREWARD_1_3]
[f 2 1]Since I placed at the top in the exams,[n]I also got this [f 4 4 1 37 1 3].[n][w][e]

