[msg MSG_000_0_0 [Camera Footage]]
[f 2 1]...＞ ...＞[n][w][e]
[f 2 1]05/10/2009 01:23:02[n]Starting playback...[n][w][e]

[msg MND_001_0_0]
[f 2 1]...!?[n][w][e]
[f 2 1]It's the command room. Ikutsuki[n]is alone, writing something.[n][w][e]

[msg MSG_002_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 10 0 0][vp 1 0 0 1 0 0]Hm... A Shadow in the middle of town... It managed to take over public transportation.[n][w][e]
[f 2 1][bup 222 1 65535 10 0 0][vp 1 0 0 2 0 0][f 4 23 0 222 1 25 25]I should investigate whether this means it's finally begun...[n][w][e]

[msg MSG_002_5_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 10 0 0][vp 1 0 0 3 0 0][f 4 23 0 222 0 25 25]The monorail...[n][w][e]

[msg MSG_002_7_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 1 65535 10 0 0][vp 1 0 0 4 0 0][f 4 23 0 222 1 25 25]I bet this subject would make a good "one-liner"...![n][w][e]

[msg MSG_003_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 1 65535 10 0 0][vp 1 0 0 5 0 0]Hehe... Ahahahaha![n][w][e]
[f 2 1][bup 222 1 65535 10 0 0][vp 1 0 0 6 0 0]Oh, I need to note that one down...[n][w][e]

[msg MSG_004_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 10 0 0][vp 1 0 0 7 0 0]Unfortunately, lady luck played a large part in our victory...[n][w][e]
[f 2 1][bup 222 0 65535 10 0 0][vp 1 0 0 8 0 0]Especially toward the end. If she hadn't guessed at the right controls, things could have been very bad.[n][w][e]
[f 2 1][bup 222 0 65535 10 0 0][vp 1 0 0 9 0 0]For Shadows to work in a group to overrun large machines is unprecedented.[n][w][e]

[msg MSG_004_3_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 10 0 0][vp 1 0 0 10 0 0]The engine...[n][w][e]

[msg MSG_004_4_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 1 65535 10 0 0][vp 1 0 0 11 0 0][f 4 23 0 222 1 25 25]That was an engine-ious move![n][w][e]

[msg MSG_004_5_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 1 65535 10 0 0][vp 1 0 0 12 0 0]Ahahaha! What is it with me today!? I'm on a roll![n][w][e]
[f 2 1][bup 222 1 65535 10 0 0][vp 1 0 0 13 0 0]Ah, better write that one down too...[n][w][e]

[msg MSG_005_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 2 65535 10 0 0][vp 1 0 0 14 0 0]Always be prepared for heavy lifting during a mission...[n][w][e]

[msg MSG_005_2_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 2 65535 10 0 0][vp 1 0 0 15 0 0]Because Shadows aren't light![n][w][e]
[f 2 1][bup 222 0 65535 10 0 0][vp 0 0 0 16 0 0][f 4 23 0 222 0 25 25]......[n][w][e]

[msg MSG_005_3_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 1 65535 10 0 0][vp 1 0 0 17 0 0]Whoa, I'm getting a little off-subject... But who cares!?[n][w][e]
[f 2 1][bup 222 0 65535 10 0 0][vp 1 0 0 18 0 0][f 4 23 0 222 0 25 25]Hey... I should write all these down and show them off the next time everyone gets together![n][w][e]

[msg MSG_005_5_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 2 65535 10 0 0][vp 1 0 0 19 0 0][f 4 23 0 222 2 25 25]"Don't care for seafood? They also serve GROUND beef!"[n][w][e]

[msg MSG_005_7_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 1 65535 10 0 0][vp 1 0 0 20 0 0]Hehe... Ahahaha! This has nothing to do with the status report anymore, but I'm having a blast![n][w][e]
[f 2 1][bup 222 0 65535 10 0 0][vp 1 0 0 21 0 0][f 4 23 0 222 0 25 25]Let's see, what else...?[n][w][e]

[msg MND_007_0_0]
[f 2 1]The recording ends here...[n][w][e]

