[msg MSG_000_0_0 [Boy with Ulterior Motives]]
[f 2 1][f 5 21 1 644]Yo, do you think they have a mixed-gender bath here?[n][w][e]

[sel SEL_001_0_0 top]
[f 2 1]What..?[e]
[f 2 1]So what if they do?[e]

[msg MSG_002_0_0 [Boy with Ulterior Motives]]
[f 2 1][f 5 21 1 644]Yeah, I guess not...[n][w][e]

[msg MSG_003_0_0 [Boy with Ulterior Motives]]
[f 2 1][f 5 21 1 644]What!? Isn't it obvious...?[n][w][e]
[f 2 1][f 5 21 1 644]...Hey, I'm just kidding! I don't have such a dirty mind![n][w][e]

