[msg MSG_000_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 0 65535 65535 0 0][vp 1 0 4 1 0 0]Oh, [nl]-chan.[n][w][e]
[f 2 1][bup 109 3 65535 65535 0 0][vp 1 0 4 2 0 0]A-Are you okay? You don't look so good...[n][w][e]
[f 2 1][bup 109 3 65535 65535 0 0][vp 1 0 4 3 0 0]You should get home and rest before it gets worse...[n][w][e]
[f 2 1][bup 109 0 65535 65535 0 0][vp 1 0 4 4 0 0]Right now, I, um...[n][w][e]
[f 2 1][bup 109 3 65535 65535 0 0][vp 1 0 4 5 0 0]...Oh, sorry! This isn't the time to talk about that...[n][w][e]

[sel SEL_001_0_0 top]
[f 2 1]What is it?[e]
[f 2 1]Maybe next time.[e]

[msg MSG_002_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 0 65535 65535 0 0][vp 1 0 4 6 0 0][nl]-chan...[n][w][e]
[f 2 1][bup 109 0 65535 65535 0 0][vp 1 0 4 7 0 0]U-Um, I suppose I can tell you. It's nothing important, though...[n][w][e]

[msg MSG_003_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 0 65535 65535 0 0][vp 1 0 4 8 0 0]O-Okay! I'm sorry...[n][w][e]
[f 2 1][bup 109 3 65535 65535 0 0][vp 1 0 4 9 0 0]Um, have a good rest...[n][w][e]

