[msg MSG_000_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 3 0 65535 11083 0 0]Phew... It was pretty crowded in there, huh?[n][w][e]
[f 2 1][bup 106 3 65535 65535 0 0][f 4 23 0 106 3 25 25]I wanted to give the punching machine a try, but the line's gotten so long I'd rather not...[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0][f 4 23 0 106 0 25 25]Let's come back when it's less packed—[n][w][e]

[msg MSG_000_3_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][f 4 25 106]Oh my gosh...[n][w][e]

[msg MSG_001_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0]Look! It's so cute! Plus... we might be able to get it in one shot.[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0]It's been a while since the last time I've played. I may not look it, but I'm pretty good at these.[n][w][e]

[msg MSG_002_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 4 65535 65535 0 0]H-Huh...? I couldn't grab it at all...[n][w][e]
[f 2 1][bup 106 2 65535 65535 0 0][vp 3 0 65535 11076 0 0][f 4 23 0 106 2 25 25]What!? No way! That's such bull! This has to be rigged or something![n][w][e]

[sel SEL_003_0_0 top]
[f 2 1]Let's just calm down first.[e]
[f 2 1]Man, you suck.[e]
[f 2 1]Want me to give a shot?[e]

[msg MSG_004_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 3 0 65535 11019 0 0][f 5 13 12 30 106]Oh. Yeah. Right.[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0][f 4 23 0 106 0 25 25]If grabbing it doesn't work... I'll just have to slowly shift its position till it drops.[n][w][e]

[msg MSG_004_3_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0]It's kind of a pain, but slow and steady wins the race.[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0]Same thing with sports, right? People who are dedicated to training become world-class athletes.[n][w][e]

[msg MSG_004_5_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0]Oh... Kinda went on a tangent there. Anyway, let's give this another shot![n][w][e]

[msg MND_005_0_0]
[f 2 1]Yuko seems motivated.[n][w][e]
[f 2 1]I feel like we became a lot closer today.[n][w][e]

[msg MSG_006_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 2 65535 65535 0 0][vp 3 0 65535 11027 0 0]No, I don't! It's the friggin' claw! It's too weak![n][w][e]
[f 2 1][bup 106 3 65535 65535 0 0][f 4 23 0 106 3 25 25]Ugh... Guess I just have to slowly adjust the position till it falls.[n][w][e]

[msg MSG_006_3_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0]In the end, slow and steady wins the race... even though it's a total drag.[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0]But it's the same with sports. People who are dedicated to training become world-class athletes.[n][w][e]

[msg MSG_006_5_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0]...But doesn't matter right now. All right, time to win this thing![n][w][e]

[msg MND_007_0_0]
[f 2 1]Yuko looks serious...[n][w][e]
[f 2 1]I feel like we didn't get any closer today...[n][w][e]

[msg MSG_008_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 4 65535 65535 0 0][vp 3 0 65535 11075 0 0][f 5 13 12 15 106]Huh? Oh, thanks for the offer, but don't worry.[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0][f 4 23 0 106 1 25 25]If I just keep nudging it in the right direction... I should be able to knock it down.[n][w][e]

[msg MSG_008_3_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0]Kind of a pain, but slow and steady wins the race, y'know?[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0]Same thing with sports. People who are dedicated to training become world-class athletes.[n][w][e]

[msg MSG_008_5_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0]Anyway, time to put my game face on. I'll keep at it until I win this thing...[n][w][e]

[msg MND_009_0_0]
[f 2 1]Yuko seems really focused.[n][w][e]
[f 2 1]I learned a little more about her today.[n][w][e]

[msg MSG_010_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 3 65535 65535 0 0]Well, at least I got it in the end...[n][w][e]
[f 2 1][bup 106 3 65535 65535 0 0]But I'm so tired now... I've definitely run out of stamina and money.[n][w][e]

[msg MSG_010_3_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 3 65535 65535 0 0][vp 3 0 65535 11071 0 0]Let's head back, [nl]-chan. I need to eat dinner and recuperate.[n][w][e]

[msg MND_011_0_0]
[f 2 1]After saying goodbye to Yuko,[n]I headed back to the dorm.[n][w][e]

