[msg MSG_000_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 1 0 0]...So, there's actually something I want you to try, [nl]-chan.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 2 0 0]And this time it isn't just for a taste test.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 3 0 0]I think you'll actually be able to eat it![n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 4 0 0]...Wait, uh, maybe I said the same thing last time...[n][w][e]

[msg MSG_000_5_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 5 0 0]Well, now I mean it![n][w][e]

[msg MND_001_0_0]
[f 2 1]Fuuka presents me with a bento box.[n][w][e]
[f 2 1]There are rice balls wrapped[n]in seaweed inside.[n][w][e]
[f 2 1]They smell good. I decide to try one...[n][w][e]

[msg MND_002_0_0]
[f 2 1]It's edible, at least.[n][w][e]
[f 2 1]The rice tastes good, and it has[n]just the right amount of seasoning.[n][w][e]
[f 2 1]In fact, I'd go so far as to say it's delicious.[n][w][e]

[msg MSG_003_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 6 0 0]W-Well... How is it?[n][w][e]

[sel SEL_004_0_0 top]
[f 2 1]It's good.[e]
[f 2 1]You did a great job.[e]

[msg MSG_005_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 7 0 0][f 5 13 3 5 6]Really? Oh, I'm so glad.[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 8 0 0]Hehe, I finally got you to say it.[n][w][e]

[msg MSG_006_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 9 0 0][f 5 13 3 15 6]Really? I'm so glad to hear that.[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 10 0 0]Thank you.[n][w][e]

[msg MSG_007_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 11 0 0]You know how I said I was having trouble with cooking?[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 12 0 0]Well, I decided to try and find a recipe that even I couldn't mess up.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 13 0 0]And after a lot of consideration... I thought maybe making rice balls is something I could handle.[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 14 0 0][f 4 23 0 6 1 25 25]But then I got really absorbed in how simple they are to make, yet still so hard to master.[n][w][e]

[msg MSG_008_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 15 0 0]I made some rice balls today in home economics class too.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 16 0 0]I know it's a little silly to make something so basic in high school, but it was all I could manage.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 17 0 0]But then, everyone in the class told me they were really good, though![n][w][e]

[msg MSG_009_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 18 0 0]Anyways, I've been really looking forward to have you try one, [nl]-chan.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 19 0 0]I wanted you to see how much progress I've made.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 20 0 0]Because, I don't think I could have made it this far without you.[n][w][e]

[sel SEL_010_0_0 top]
[f 2 1]I'm glad I could help.[e]
[f 2 1]I didn't do anything.[e]

[msg MSG_011_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 21 0 0][f 5 13 3 5 6]...Thanks.[n][w][e]

[msg MSG_012_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 22 0 0]But you did though. You taught me so much.[n][w][e]

[msg MSG_013_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 23 0 0]I know I've said this before, but...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 24 0 0]When I'm with you and the rest of the team, I'm able to see things more positively.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 25 0 0]And I think the most important thing is the feeling of wanting to make others happy.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 26 0 0]That might be the reason why I made such good rice balls. Because I was thinking about who was going to eat them.[n][w][e]

[sel SEL_014_0_0 top]
[f 2 1]Thank you.[e]
[f 2 1]I think I get it.[e]
[f 2 1]Can you make more sometime?[e]

[msg MSG_015_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 27 0 0][f 5 13 3 5 6]I'm the one that should be thanking you.[n][w][e]

[msg MSG_016_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 28 0 0]They say, "Love is the most flavorful spice," and it turns out it was true.[n][w][e]

[msg MSG_017_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 29 0 0][f 5 13 3 15 6]Of course! Just let me know anytime you want some.[n][w][e]

[msg MSG_018_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 30 0 0]Um, [nl]-chan, I just wanted to say...[n][w][e]

[msg MSG_018_5_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 31 0 0]Thank you so much. Really.[n][w][e]

[msg MND_019_0_0]
[f 2 1]Fuuka seems to really appreciate me.[n][w][e]
[f 2 1]Our relationship is getting deeper...[n][w][e]

[msg MSG_020_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 32 0 0]So it turns out, there's actually a trick to making good rice balls.[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 33 0 0]The first thing to note is while you're washing the rice...[n][w][e]

[msg MND_021_0_0]
[f 2 1]I spend the day listening to[n]Fuuka's tips on making rice balls.[n][w][e]
[f 2 1]I decided to go back to the dorm...[n][w][e]

