[msg MSG_001_0_0 [Fierce Guy]]
[f 2 1][f 5 21 1 691]I rented a car because I heard you could drive along the coast, but...[n][w][e]
[f 2 1][f 5 21 1 691]You can't really see the ocean from the road... Well, it's fine, 'cause my girlfriend had fun anyway.[n][w][e]

[msg MSG_004_0_0 [Fierce Guy]]
[f 2 1][f 5 21 1 691]...Hey, you. Could you slide off; you're a little to close to my girl? Only I can stand there.[n][w][e]

