[msg MSG_000_0_0 [Yukari Takeba]]
[f 2 1][bup 2 4 65535 65535 0 0][vp 1 0 4 1 0 0]Oh! [nl]-chan!?[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 4 2 0 0]Oh, sorry. I was just thinking about you...[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 4 3 0 0]Uh...[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 4 4 0 0][f 4 25 2]......[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 4 5 0 0]Can we go somewhere else?[n][w][e]

[sel SEL_001_0_0 top]
[f 2 1]All right.[e]
[f 2 1]Why?[e]

[msg MSG_002_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 4 6 0 0]Thanks...[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 4 7 0 0]Uh... You look like you're not feeling well. Sorry to bother you at a time like this, but I appreciate it.[n][w][e]

[msg MSG_003_0_0 [Yukari Takeba]]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 4 8 0 0]I dunno, sorry...[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 4 9 0 0]You look like you could use some rest anyway... Don't worry about it.[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 4 10 0 0]I'll see you later, then...[n][w][e]

