[msg MSG_001_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 101 65535 0 0][vp 1 0 0 1 0 0]Hey! No slackin', put your heart into it![n][w][e]
[f 2 1][bup 106 0 101 65535 0 0][vp 1 0 0 2 0 0]You'll never beat Hayase with that attitude![n][w][e]

[msg MSG_002_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 101 65535 0 0][vp 1 0 0 3 0 0]You're almost there! Keep up the pace![n][w][e]
[f 2 1][bup 106 0 101 65535 0 0][vp 1 0 0 4 0 0]This is our year! Hayase's got nothing on us![n][w][e]

[msg MSG_003_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 101 65535 0 0][vp 1 0 0 5 0 0]Wow, [nl]-chan! That was a great lap![n][w][e]
[f 2 1][bup 106 1 101 65535 0 0][vp 1 0 0 6 0 0]Keep it up! You might be able to win the whole thing![n][w][e]

[msg MND_004_0_0 [Internal MES]]
[f 2 1]Three days left until the competition...[n][w][e]

[msg MSG_005_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 101 65535 0 0][vp 1 0 0 7 0 0]Stay focused, everyone![n][w][e]
[f 2 1][bup 106 0 101 65535 0 0][vp 1 0 0 8 0 0]Tomorrow's the big day![n][w][e]
[f 2 1][bup 106 4 101 65535 0 0][vp 1 0 0 9 0 0]Whoa, you're doing great, [nl]-chan![n][w][e]
[f 2 1][bup 106 1 101 65535 0 0][vp 1 0 0 10 0 0]That's the fastest time on the team! Good luck tomorrow—you got this![n][w][e]

