[msg MND_000_0_0]
[f 2 1]Death is not a hunter unbeknownst to its prey.[n]One is always aware that it lies in wait.[n][w][e]
[f 2 1]Though life is merely a journey to the grave,[n]it must not be undertaken without hope.[n][w][e]
[f 2 1]Only then will a traveler's story live on,[n]treasured by those who bid her farewell.[n][w][e]
[f 2 1]Alas, my guest's life has now ended,[n]her tale left unwritten...[n][w][e]

[msg MSG_015_0_0]
[f 2 1]Game Over[n][w][e]

[msg MND_003_0_0]
[f 2 1]Resume play?[n][w][e]

[sel SEL_001_0_0 top]
[f 2 1]Lower difficulty level [f 4 26 10 0][e]
[f 2 1]Retry battle [f 4 26 11 0][e]
[f 2 1]Restart operation [f 4 26 12 0][e]
[f 2 1]Return to title screen [f 4 26 14 0][e]

[sel SEL_002_0_0 top]
[f 2 1]Lower difficulty level [f 4 26 10 0][e]
[f 2 1]Retry battle [f 4 26 11 0][e]
[f 2 1]Start from Tartarus entrance [f 4 26 13 0][e]
[f 2 1]Return to title screen [f 4 26 14 0][e]

[msg SYS_004_0_0]
[f 2 1][f 1 4 1]You will return to the beginning of the operation and lose your current progress in it, except for the change in difficulty. Are you sure?[n][w][e]

[msg SYS_005_0_0]
[f 2 1][f 1 4 1]You will return to the entrance of Tartarus and lose this visit's progress, except for the change in difficulty. Are you sure?[n][w][e]

[msg SYS_006_0_0]
[f 2 1][f 1 4 1]You will return to the title screen and lose all progress made since you last saved the game. Are you sure?[n][w][e]

[sel SEL_007_0_0 top]
[f 2 1]Yes[e]
[f 2 1]No[e]

[msg SYS_009_0_0]
[f 2 1][f 1 4 1]If you change the difficulty from Merciless, [clr 2]you cannot change it back to Merciless later[clr 27]. Do you still want to change to Hard difficulty?[n][w][e]

[msg MND_010_0_0]
[f 2 1]Lower the difficulty by one level.[n][w][e]

[msg MND_011_0_0]
[f 2 1]Start over from the beginning of the battle.[n][w][e]

[msg MND_012_0_0]
[f 2 1]Start over from the beginning of the operation.[n][w][e]

[msg MND_013_0_0]
[f 2 1]Start over from the entrance of Tartarus.[n][w][e]

[msg MND_014_0_0]
[f 2 1]Return to the title screen.[n][w][e]

[msg SYS_012_0_0]
[f 2 1][f 1 4 1]The difficulty is currently set to [clr 2]Easy[clr 27]. Would you like to change it to [clr 2]Peaceful[clr 27]?[n][w][e]

[msg SYS_011_0_0]
[f 2 1][f 1 4 1]The difficulty is currently set to [clr 2]Normal[clr 27]. Would you like to change it to [clr 2]Easy[clr 27]?[n][w][e]

[msg SYS_010_0_0]
[f 2 1][f 1 4 1]The difficulty is currently set to [clr 2]Hard[clr 27]. Would you like to change it to [clr 2]Normal[clr 27]?[n][w][e]

[msg SYS_008_0_0]
[f 2 1][f 1 4 1]The difficulty is currently set to [clr 2]Merciless[clr 27]. Would you like to change it to [clr 2]Hard[clr 27]?[n][w][e]

[msg SYS_016_0_0]
[f 2 1]The difficulty has been changed to [clr 2]Peaceful[clr 27].[n][w][e]

[msg SYS_021_0_0]
[f 2 1]The difficulty has been changed to [clr 2]Easy[clr 27].[n][w][e]

[msg SYS_022_0_0]
[f 2 1]The difficulty has been changed to [clr 2]Normal[clr 27].[n][w][e]

[msg SYS_023_0_0]
[f 2 1]The difficulty has been changed to [clr 2]Hard[clr 27].[n][w][e]

