[msg MSG_000_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 3 0 65535 11008 0 0]Oh, [nl]-chan.[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0]I was wondering what I should do since there's no practice today.[n][w][e]

[msg MND_001_0_0]
[f 2 1]It seems Yuko wants[n]to walk home together.[n][w][e]

[msg MSG_002_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 3 0 65535 11005 0 0]Hey, [nl]-chan. You heading home?[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0]We were interrupted last time, so if you're down, wanna try hanging out again?[n][w][e]

[msg MSG_003_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 3 0 65535 11002 0 0]Ah, hey, [nl]-chan. Are you free right now?[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0]Those kids had their race, and they said they wanna talk to us.[n][w][e]

[msg MSG_004_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0]未使用ラベルだよ。[n][w][e]

[msg MSG_005_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 3 0 65535 11011 0 0]Oh, [nl]-chan...[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0]Are you doing anything today? If not... maybe you could join me?[n][w][e]

[msg MSG_006_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 3 0 65535 11005 0 0]Heya, [nl]-chan. Are you about to leave?[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0]Wanna chat outside for a bit? The weather looks nice.[n][w][e]

[msg MND_007_0_0]
[f 2 1]Should I spend some time[n]after school with Yuko?[n][w][e]

[sel SEL_008_0_0 top]
[f 2 1]Spend time with her[e]
[f 2 1]Check Social Link status[e]
[f 2 1]Not now[e]

[msg MSG_009_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 3 0 65535 11031 0 0]Oh, cool! Thanks![n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0]I can't rely on the other team members at all... You get it, right, [nl]-chan?[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0]Okay then, off to Paulownia Mall we go![n][w][e]

[msg MSG_010_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 3 0 65535 11068 0 0]Sweet! Then let's go hang out somewhere fun.[n][w][e]

[msg MSG_011_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 3 0 65535 11093 0 0]Great! Then let's hit the town and have some fun this time![n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0]How about we head to Paulownia Mall? Maybe we could get some cake from Chagall, too![n][w][e]

[msg MSG_012_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 3 0 65535 11085 0 0]No backing out now, okay?[n][w][e]
[f 2 1][bup 106 3 65535 65535 0 0]Hm, where should we go...?[n][w][e]
[f 2 1][bup 106 3 65535 65535 1 0][vp 3 0 65535 11063 0 0]...How about my place? Don't worry, I tidied up beforehand![n][w][e]

[msg MSG_013_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 3 0 65535 11082 0 0]No backing out now, okay?[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0]Wanna grab a bite? I've got a few places in mind, but you can make the final choice.[n][w][e]

[msg MSG_014_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0]Unused[n][w][e]

[msg MSG_015_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 3 0 65535 11084 0 0]Really? Oh, perfect...[n][w][e]

[msg MSG_016_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 1 0][vp 3 0 65535 11063 0 0]U-Um, do you wanna come over again? I wanted to give you something...[n][w][e]
[f 2 1][bup 106 4 65535 65535 1 0]That's all, really! Just wanted to give you a little something, no big deal! Right?[n][w][e]

[msg MSG_017_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 3 0 65535 11032 0 0]Thanks. You go on ahead to the field.[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0]I'm gonna stop by the faculty office to go over some notes.[n][w][e]

[msg MSG_018_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 3 0 65535 11089 0 0]Oh my god... You're kinda needy, aren't you, [nl]-chan?[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0]But I don't mind it...[n][w][e]
[f 2 1][bup 106 1 65535 65535 1 0]...Wanna come over? But we better be quiet, so my parents don't find out...[n][w][e]

[msg MSG_019_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 3 0 65535 11018 0 0]Oh, did you already make plans?[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0]I guess you do seem busy... Well, see you around.[n][w][e]

[msg MSG_020_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 3 0 65535 11009 0 0]Oh, hey there, [nl]-chan.[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0]Ever since you helped me discover my dreams, I've been studying really hard, trying to make them come true.[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0][vp 3 0 65535 11093 0 0]So whatever you decide to do, give it your 100%! I'll always be there for you, like how you were for me.[n][w][e]

[msg MND_021_0_0]
[f 2 1]I feel an unbreakable bond[n]with Yuko...[n][w][e]

[msg MSG_022_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 3 0 65535 11008 0 0]Oh, hey, [nl]-chan.[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0]I've been studying really hard lately. You helped me discover my dreams, so now I'm gonna make them a reality.[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0][vp 3 0 65535 11082 0 0]So whatever you decide to do, give it your 100%! I'll always be there for you, like how you were for me.[n][w][e]

[msg MND_023_0_0]
[f 2 1]I feel an unbreakable bond[n]with Yuko...[n][w][e]

[msg MSG_024_5_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 3 0 65535 11065 0 0]Oh, [nl]-chan.[n][w][e]

[msg MSG_024_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0]You know about the nightclub at Paulownia Mall, right?[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0]I've never really cared for it since the place seems kinda sketchy. I hear a weird crowd hangs around there.[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0]Like, there's some guy dressed as a monk partying hard every night.[n][w][e]
[f 2 1][bup 106 3 65535 65535 0 0][vp 3 0 65535 11054 0 0]There's no way he's a real monk, right...? Are monks even allowed to drink alcohol?[n][w][e]

[msg MND_025_0_0]
[f 2 1]I got a lead from Yuko about a monk[n]who "parties hard" at a nightclub.[n][w][e]

[msg MSG_026_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 3 0 65535 11064 0 0]Oh, yeah. Those kids have really been getting on my case about this whole coaching thing.[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0]The track's open since there's no practice today, so I'm wondering if I should just do it...[n][w][e]

[msg MSG_027_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0]By the way, are you heading out soon?[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0]I was thinking about what to do since there's no practice today.[n][w][e]

[msg MSG_028_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0]By the way, are you heading out soon?[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0]I was thinking about what to do since there's no practice today.[n][w][e]

[msg MSG_029_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0]Hey, are you busy right now?[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0]Those kids had their race, and they said they wanna talk to us.[n][w][e]

[msg MSG_030_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0]Unused[n][w][e]

[msg MSG_031_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0]Um, hey... [nl]-chan.[n][w][e]
[f 2 1][bup 106 3 65535 65535 1 0]Are you doing anything today? If not... maybe you could join me?[n][w][e]

[msg MSG_032_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0]By the way, are you about to leave?[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0]Wanna chat outside for a bit? The weather looks nice.[n][w][e]

[msg MSG_033_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 3 0 65535 11005 0 0]Oh, hey, [nl]-chan. Exams are finally over, huh?[n][w][e]

[msg MSG_034_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0]Oh yeah. Exams are finally over, huh?[n][w][e]

[msg MSG_035_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0]Congrats on surviving. Hopefully, you're not too beat from all the studying?[n][w][e]

[msg MSG_036_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0]Congrats on surviving. Now we have time to do whatever we wanna do.[n][w][e]

[msg MSG_037_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0]Congrats on surviving. Man, it feels like a fog has lifted—like I can finally see what's in front of me.[n][w][e]

[msg MSG_038_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 3 0 65535 11065 0 0]Oh, [nl]-chan.[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0]I've actually gotta head out now to do some shopping for the track team. Like, buying athletic tape and stuff.[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0]There's a lot, so it'd be nice if I had an extra hand or two to carry everything... Hint, hint.[n][w][e]

[msg MSG_038_5_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0]Oh, are you free today?[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0]I've actually gotta head out now to do some shopping for the track team. Like, buying athletic tape and stuff.[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0]There's a lot, so it'd be nice if I had an extra hand or two to carry everything... Hint, hint.[n][w][e]

[msg MSG_039_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 3 0 65535 11008 0 0]Oh, hey, [nl]-chan.[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0]There's no practice today, so it's the perfect time to relax. If you're leaving, wanna hang out?[n][w][e]

[msg MSG_039_5_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0]There's no practice today, so it's the perfect time to relax. If you're leaving, wanna hang out?[n][w][e]

[msg MSG_040_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 3 0 65535 11019 0 0]Cool! Hm, where should we go then?[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0]Should we get something to eat? Or maybe do some karaoke? Let's decide on the way out.[n][w][e]

[msg MSG_040_5_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 3 0 65535 11064 0 0]Oh hey, are you free today?[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0]We were interrupted last time, so if you're down, wanna try hanging out again?[n][w][e]

[msg MSG_041_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 3 0 65535 11012 0 0]Heya, how've you been?[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0]Those kids have really been getting on my case about this whole coaching thing.[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0]The track's open since there's no practice today, so I'm wondering if I should just do it...[n][w][e]

[msg MSG_042_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 3 0 65535 11093 0 0]Okay, great! I'm gonna ask the teacher for permission to use the track then.[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0]I'll see you at the field! Countin' on ya, Coach![n][w][e]

[msg MSG_044_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 3 0 65535 11002 0 0]Oh, [nl]-chan. Are you busy today?[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0]I was thinking of coaching those kids some more. They were really looking forward to it.[n][w][e]

[msg MSG_045_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 3 0 65535 11032 0 0]Great! Thanks.[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0]I did a bunch of research on my end for this, so let's give 'em a real workout![n][w][e]

[msg MSG_046_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 3 0 65535 11024 0 0]Oh, okay. I'll go call them over, then.[n][w][e]
[f 2 1][bup 106 3 65535 65535 0 0][vp 3 0 65535 11083 0 0]I wonder how they did... Now I'm getting nervous.[n][w][e]

[msg MSG_047_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 3 0 65535 11008 0 0]Oh, [nl]-chan. Are you free today...?[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0]I'm pretty much ready to throw that party, so I thought today might be a good time...[n][w][e]

[msg MSG_047_5_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0]Oh, by the way... are you free today?[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0]I'm pretty much ready to throw that party, so I thought today might be a good time...[n][w][e]

[msg MSG_048_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 3 0 65535 11008 0 0]Oh, [nl]-chan. Are you free today...?[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0]I figured today might be a good time to throw that party...[n][w][e]

[msg MSG_048_5_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0]Oh yeah... Are you free today?[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0]I figured today might be a good time to throw that party...[n][w][e]

[msg MSG_049_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 3 0 65535 11065 0 0]Oh, [nl]-chan.[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0]If you're leaving, wanna hang out somewhere? We all need to take a breather sometimes, right?[n][w][e]

[msg MSG_049_5_0 [Yuko Nishiwaki]]
[f 2 1]If you're leaving, wanna hang out somewhere? We all need to take a breather sometimes, right?[n][w][e]

[msg MSG_050_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 1 0][vp 3 0 65535 11082 0 0]Cool, how about we head to Chagall? We can take our time chatting there.[n][w][e]

[msg MSG_051_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 3 0 65535 11065 0 0]Oh, [nl]-chan.[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0]If you're leaving, wanna hang out somewhere? We all need to take a breather sometimes, right?[n][w][e]

[msg MSG_051_5_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0]If you're leaving, wanna hang out somewhere? We all need to take a breather sometimes, right?[n][w][e]

[msg MSG_052_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 3 0 65535 11024 0 0]Cool, how about we head to Chagall? We can take our time chatting there.[n][w][e]

[msg MSG_141_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 3 0 65535 11015 0 0]Oh, did you need to take care of something?[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0]Sorry, I had no clue you were busy. I'll catch you later.[n][w][e]

[msg MSG_142_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 3 0 65535 11015 0 0]Oh, did you already have plans? All right, see you around.[n][w][e]

[msg MSG_143_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 3 0 65535 11050 0 0]Oh, that's too bad... Maybe next time, then![n][w][e]

[msg MSG_144_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 3 65535 65535 0 0][vp 3 0 65535 11050 0 0]Oh, you can't do today, huh...[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0]All right, maybe next time. See you then![n][w][e]

[msg MSG_145_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 3 65535 65535 0 0][vp 3 0 65535 11050 0 0]Oh... You can't?[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0]Guess there's nothing we can do about that. Maybe next time.[n][w][e]

[msg MSG_146_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 3 65535 65535 0 0][vp 3 0 65535 11050 0 0]Oh, you already had plans, huh... That's too bad.[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0]I'll try again some other time then. See you later.[n][w][e]

[msg MSG_147_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 3 65535 65535 0 0][vp 3 0 65535 11083 0 0]Oh... I guess that was too sudden.[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0]Dang, I was really looking forward to it, you know. Well, see you around.[n][w][e]

[msg MSG_148_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 3 65535 65535 0 0][vp 3 0 65535 11083 0 0]O-Oh... That's too bad.[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0]You're busy, right? I'll see you around, then.[n][w][e]

[msg MSG_149_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 3 65535 65535 0 0][vp 3 0 65535 11083 0 0]...Oh, gotcha.[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0]Sorry for asking so suddenly. I'll try again some other time.[n][w][e]

[msg MSG_150_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 3 0 65535 11050 0 0]Oh, you can't do today?[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0]Hm, guess I'll just head on home, then. Let's try again some other time.[n][w][e]

[msg MSG_151_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 3 0 65535 11050 0 0]Oh, you're busy?[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0]Let me know when you're free, okay? See you.[n][w][e]

[msg MSG_152_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 3 0 65535 11050 0 0]Oh, all right. Next time, then.[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0]Maybe I'll just head home and do some studying. Catch you later.[n][w][e]

[msg MSG_153_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 3 0 65535 11093 0 0]Let's work hard! Seriously! I'll be cheering you on, too, [nl]-chan![n][w][e]

[msg MND_GENERAL_EVENTPLAY]
[f 2 1]Message issued by the script. [n][f 1 5 0]Comm Event Replay.[n][w][e]

[msg MND_GENERAL_PERSPNA]
[f 2 1]I feel as if we can grow closer thanks to the[n][f 2 4 2] Persona, [clr 35][f 2 4 5][clr 27]...[n][w][e]

[msg MND_GENERALSELECTMSG_MAX]
[f 2 1]I feel an unbreakable bond[n]with [f 2 4 0]...[n][w][e]

[msg MND_GENERALMSG_BS_MAX]
[f 2 1]I feel an unbreakable bond[n]with the elderly couple...[n][w][e]

[msg MND_GENERALSELECTMSG_RAN]
[f 2 1]I feel like I might grow closer[n]to [f 2 4 0] soon...[n][w][e]

[msg MND_GENERALMSG_BS_RANKUP]
[f 2 1]I feel like I might grow closer[n]to the elderly couple soon...[n][w][e]

[msg MND_GENERALSELECTMSG_NOR]
[f 2 1]I don't think our bond will grow[n]any stronger even if I spend[n]more time with [f 2 4 0]...[n][w][e]

[msg MND_GENERALMSG_BS_NORMAL [Yuko Nishiwaki]]
[f 2 1]I don't think our bond will grow[n]any stronger even if I spend[n]more time with them...[n][w][e]

[msg MND_GENERALSELECTMSG_MAX_2]
[f 2 1]It doesn't seem that our relationship[n]can get any closer than it is...[n][w][e]
[f 2 1]Should I still spend time with them...?[n][w][e]

[msg MND_GENERAL_MSG_SOLO_AS]
[f 2 1]Should I spend some time after[n]school with [f 2 4 0]?[n][w][e]

[msg MND_GENERAL_MSG_SOLO_DT]
[f 2 1]Should I spend the day[n]with [f 2 4 0]?[n][w][e]

[msg MND__GENERAL_MSG_NET]
[f 2 1]Should I spend time online playing[n]the MMORPG with [f 2 4 0]...?[n][w][e]

[msg MND_GENERAL_MSG_SOLO_NT]
[f 2 1]Should I spend the evening[n]with [f 2 4 0]?[n][w][e]

[sel SEL_GENERALSELECTMSG_SOL top]
[f 2 1]Spend time with [f 2 4 0][e]
[f 2 1]Check Social Link[e]
[f 2 1]Never mind[e]

[msg MND_GENERAL_MSG_MULTIPLE]
[f 2 1]Should I spend some time after[n]school with the [f 2 4 1]?[n][w][e]

[msg MND_GENERAL_MSG_FASHION_]
[f 2 1]Should I spend some time after[n]school at the fashion club?[n][w][e]

[msg MND_GENERAL_MSG_BOOKSTOR]
[f 2 1]Should I spend the day at the bookstore?[n][w][e]

[msg MND_GENERAL_MSG_BOOKSTOR_2]
[f 2 1]Should I spend some time[n]after school at the bookstore?[n][w][e]

[msg MND_GENERAL_MSG_MULTIPLE_2]
[f 2 1]Should I spend the night[n]with [f 2 4 1]?[n][w][e]

[sel SEL_GENERALSELECTMSG_MUL top]
[f 2 1]Spend time w/ [f 2 4 1][e]
[f 2 1]Check Social Link[e]
[f 2 1]Never mind[e]

[sel SEL_GENERALSELECTMSG_FCL top]
[f 2 1]Go to the fashion club[e]
[f 2 1]Check Social Link[e]
[f 2 1]Never mind[e]

[sel SEL_GENERALSELECTMSG_BS top]
[f 2 1]Enter the bookstore[e]
[f 2 1]Check Social Link[e]
[f 2 1]Never mind[e]

[msg MSG_GENERAL_EXAMREWARD_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4029 0 0]Ah, [nl].[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]I saw your exam results. Good work.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Here, this is from the chairman.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4108 0 0]It's a reward for effectively balancing schoolwork as well as our... ahem, "extracurricular activities."[n][w][e]

[msg MND_GENERAL_EXAMREWARD_0]
[f 2 1]DEV: UNUSED LABEL[n][w][e]

[msg MND_GENERAL_EXAMREWARD_0_2]
[f 2 1]Since I placed at the top in the exams,[n]I also got this [f 4 4 1 37 1 3].[n][w][e]

[msg MSG_GENERAL_EXAMREWARD_0_2 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4029 0 0]Ah, [nl].[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]I saw your exam results. Good work.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Here, this is from the chairman.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4108 0 0]It's a reward for effectively balancing schoolwork as well as our... ahem, "extracurricular activities."[n][w][e]

[msg MSG_GENERAL_EXAMREWARD_0_3 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4077 0 0]Oh, right. There's something else...[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]I saw your exam results. Good work.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Here, this is from the chairman.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4131 0 0]It's a reward for effectively balancing schoolwork as well as our... ahem, "extracurricular activities."[n][w][e]

[msg MND_GENERAL_EXAMREWARD_0_3]
[f 2 1]Since I placed at the top in the exams,[n]I also got this [f 4 4 1 37 1 3].[n][w][e]

[msg MSG_GENERAL_EXAMREWARD_0_4 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4029 0 0]Ah, [nl].[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]I saw your exam results. Good work.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Here, this is from the chairman.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4108 0 0]It's a reward for effectively balancing schoolwork as well as our... ahem, "extracurricular activities."[n][w][e]

[msg MND_GENERAL_EXAMREWARD_0_4]
[f 2 1]DEV: UNUSED LABEL[n][w][e]

[msg MSG_GENERAL_EXAMREWARD_0_5 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4029 0 0]Ah, [nl].[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]I saw your exam results... Good work.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]It's admirable how you continue to excel in school while fighting arduous battle after battle.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0]I got you a gift to acknowledge all your hard work. Here, take it.[n][w][e]

[msg MND_GENERAL_EXAMREWARD_0_5]
[f 2 1]未使用ラベルです。[n][w][e]

[msg MSG_GENERAL_EXAMREWARD_0_6 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 6 65535 0 0][vp 3 0 65535 4029 0 0]Ah, [nl].[n][w][e]
[f 2 1][bup 5 0 6 65535 0 0]I saw your exam results. Good work.[n][w][e]
[f 2 1][bup 5 0 6 65535 0 0]It's admirable how you continue to excel in school while fighting arduous battle after battle.[n][w][e]
[f 2 1][bup 5 0 6 65535 0 0]I got you a gift to acknowledge all your hard work. Here, take it.[n][w][e]

[msg MND_GENERAL_EXAMREWARD_1]
[f 2 1]Since I placed at the top in the exams,[n]I also got this [f 4 4 1 37 1 3].[n][w][e]

[msg MSG_GENERAL_EXAMREWARD_1 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4029 0 0]Ah, [nl].[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]I saw your exam results. Good work.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]It's admirable how you continue to excel in school while fighting arduous battle after battle.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4108 0 0]I got you a gift to acknowledge all your hard work. Here, take it.[n][w][e]

[msg MND_GENERAL_EXAMREWARD_1_2]
[f 2 1]DEV: UNUSED LABEL[n][w][e]

[msg MND_GENERAL_EXAMREWARD_1_3]
[f 2 1]Since I placed at the top in the exams,[n]I also got this [f 4 4 1 37 1 3].[n][w][e]

