[msg MSG_000_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 1 0 0]I'm fine helping out with studying, but... wouldn't it be easier to focus without the distraction?[n][w][e]

[msg MSG_001_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 2 0 0]They say studying with others grants benefits that can't be found alone.[n][w][e]

[msg MSG_002_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 65535 65535 0 0][vp 1 0 0 3 0 0]Hey, so, if we flunk the exams... are we really gonna have to stay behind!? Tell me that's a joke![n][w][e]

[msg MSG_003_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 4 0 0]It's no joke. As students, studying is our top priority. Failure will result in consequences.[n][w][e]

[msg MSG_004_0_0 [Yukari Takeba]]
[f 2 1][bup 2 6 65535 65535 0 0][vp 1 0 0 5 0 0]Well, I'm not too worried about that. Not naming names here, but don't get in the way, Junpei.[n][w][e]

[msg MSG_005_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 65535 65535 0 0][vp 1 0 0 6 0 0]What happened to not naming names!?[n][w][e]
[f 2 1][bup 3 6 65535 65535 0 0][vp 1 0 0 7 0 0]Ugh... I guess if the fate of my trip depends on it, I don't really have a choice.[n][w][e]
[f 2 1][bup 3 2 65535 65535 0 0][vp 1 0 0 8 0 0][f 4 23 0 3 2 25 25]I'll show you. I'll prove just how serious I am about Yakushima![n][w][e]

[msg MND_006_0_0]
[f 2 1]My hand stops as I hit a tough question...[n][w][e]

[msg MSG_007_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 9 0 0]What's the matter, [nl]? Something you need help with?[n][w][e]

[sel SEL_008_0_0 top]
[f 2 1]This vocabulary...[e]
[f 2 1]This math problem...[e]
[f 2 1]This grammar...[e]

[msg MSG_009_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 10 0 0]Ah, "scintillating"... It can refer to either a literal sparkle, or a metaphorical brilliance.[n][w][e]

[msg MSG_010_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 1 65535 65535 0 0][vp 1 0 0 11 0 0]Learn your vocab, or instead of going to Yakushima, you're going to Yaku-see-me back at the dorm![n][w][e]
[f 2 1][bup 222 1 65535 65535 0 0][vp 1 0 0 12 0 0]Yakushima, Yaku-see-me... Hmm, maybe that one's a little forced...[n][w][e]

[msg MSG_011_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 13 0 0]An arithmetic sequence, huh? Do you remember the formula for calculating its sum? See, if you do this...[n][w][e]

[msg MSG_012_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 1 65535 65535 0 0][vp 1 0 0 14 0 0]A beautiful formula really arithmetickles my fancy! Haha, yeah, that one's pretty good. Let me write that down...[n][w][e]

[msg MSG_013_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 15 0 0]Old English verb conjugation differs from modern day. For example, "you are" becomes "thou art"...[n][w][e]

[msg MSG_014_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 1 65535 65535 0 0][vp 1 0 0 16 0 0]Oh my! Remembering how to use archaic forms of verbs sounds rather in-tense![n][w][e]
[f 2 1][bup 222 1 65535 65535 0 0][vp 1 0 0 17 0 0]Hmm... In-tense! I like the sound of that one. Keeping a note of that...[n][w][e]

[msg MSG_015_0_0 [Yukari Takeba]]
[f 2 1][bup 2 6 65535 65535 0 0][vp 1 0 0 18 0 0]Wisecracks from Junpei are one thing, but I didn't account for this...[n][w][e]

[msg MSG_016_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 19 0 0]Maybe he's trying to... test our ability to concentrate? Yeah, I suppose that's not likely.[n][w][e]

[msg MSG_017_0_0 [Junpei Iori]]
[f 2 1][bup 3 9 65535 65535 0 0][vp 1 0 0 20 0 0]Hmm, Ikutsuki-san's one-upping me. I've gotta think of a killer comeback...[n][w][e]

[msg MSG_018_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 2 65535 65535 0 0][vp 1 0 0 21 0 0]Stop getting distracted. You need to concentrate on your studies![n][w][e]

[msg MSG_019_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 22 0 0]She's right. Gotta focus... Let's keep at it, [nl]-chan.[n][w][e]

[msg MND_020_0_0]
[f 2 1]I focused so hard, I couldn't[n]hear anything else...[n][w][e]

[msg MSG_021_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 23 0 0]Are you struggling with memorization, [nl]? Nothing beats repeating it until you know it by heart.[n][w][e]

[msg MSG_022_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 1 65535 65535 0 0][vp 1 0 0 24 0 0]Beats... Heart? Bwahaha! Not bad, Kirijo-kun![n][w][e]

[msg MSG_023_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 4 65535 65535 1 0][vp 1 0 0 25 0 0]Wha—!? No, that— That was not my intent with that statement...[n][w][e]

[msg MSG_024_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 1 0 0 26 0 0]Well, if you're pullin' out of the race, then I win hands down! Kirijo-senpai de-feet-ed![n][w][e]

[msg MSG_025_0_0 [Yukari Takeba]]
[f 2 1][bup 2 6 65535 65535 0 0][vp 1 0 0 27 0 0]Ugh... This is giving me a headache.[n][w][e]

[msg MSG_026_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 28 0 0]Despite the diversions, I'd say that was productive. Keep it up so we can all go to Yakushima together.[n][w][e]

