[msg MSG_000_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 0 65535 65535 0 0][vp 3 0 65535 11484 0 0]Phew... I'm glad that illustration book is still there...[n][w][e]
[f 2 1][bup 109 3 65535 65535 0 0][f 4 23 0 109 3 25 25]But...[n][w][e]

[msg MSG_001_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 3 65535 65535 0 0]Um, sorry for changing the topic, but I'm still worried about the missing money...[n][w][e]

[msg MSG_002_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 3 65535 65535 0 0][vp 3 0 65535 11472 0 0]I hope it was just some kind of mistake...[n][w][e]
[f 2 1][bup 109 3 65535 65535 0 0]It's sad to think that there might be a thief at our school...[n][w][e]

[sel SEL_003_0_0 top]
[f 2 1]Don't worry, it wasn't a thief.[e]
[f 2 1]How much was stolen, huh?[e]
[f 2 1]They'll turn themselves in soon.[e]

[msg MSG_004_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 0 65535 65535 0 0][vp 3 0 65535 11467 0 0][f 5 13 9 30 109]...O-Of course, you're right. It couldn't be.[n][w][e]
[f 2 1][bup 109 0 65535 65535 0 0]As a member of the student council, I shouldn't make accusations like that. I should follow your example, [nl]-chan.[n][w][e]

[msg MND_005_0_0 [DEV: Internal MES]]
[f 2 1]Chihiro seems impressed.[n][w][e]
[f 2 1]I feel like we became a lot closer today.[n][w][e]

[msg MSG_006_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 3 65535 65535 0 0][vp 3 0 65535 11450 0 0]How much money? Um, I don't think the amount really matters...[n][w][e]
[f 2 1][bup 109 3 65535 65535 0 0]However small or large the sum, theft is a crime. We shouldn't take it lightly...[n][w][e]

[msg MND_007_0_0 [DEV: Internal MES]]
[f 2 1]Chihiro seems sad.[n][w][e]
[f 2 1]I feel like we didn't get any closer today...[n][w][e]

[msg MSG_008_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 3 65535 65535 0 0][vp 3 0 65535 11450 0 0]...I don't want to assume that it actually was a thief, but... maybe you're right.[n][w][e]
[f 2 1][bup 109 0 65535 65535 0 0][f 4 23 0 109 0 25 25][f 5 13 9 15 109]Perhaps it was just the heat of the moment. I... don't want to think that they're just evil...[n][w][e]

[msg MND_009_0_0 [DEV: Internal MES]]
[f 2 1]Chihiro is nodding.[n][w][e]
[f 2 1]I learned a little more about her today.[n][w][e]

[msg MSG_010_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 0 65535 65535 0 0][vp 3 0 65535 11445 0 0]Oh, I'm sorry... I didn't mean for you to have to listen to my worries on your day off.[n][w][e]
[f 2 1][bup 109 0 65535 65535 0 0]Um... How about I treat you to something as a thank-you?[n][w][e]

[msg MND_011_0_0 [DEV: Internal MES]]
[f 2 1]We spent some more time at the strip mall[n]together before I returned to the dorm.[n][w][e]

