[msg MSG_000_0_0 [Fortune Teller]]
[f 2 1][f 5 21 1 404]Hmm... I feel a strange aura around you...[n][w][e]
[f 2 1][f 5 21 1 404]In my mind, I see visions... People's pasts, presents, and futures...[n][w][e]
[f 2 1][f 5 21 1 404]For most people, I see clearly and far ahead...[n][w][e]
[f 2 1][f 5 21 1 404]But you are different... Your future is filled with both blinding light and stagnant shadow...[n][w][e]
[f 2 1][f 5 21 1 404]I can see but a small portion... What lies beyond that is shrouded in mystery...[n][w][e]
[f 2 1][f 5 21 1 404]What a peculiar fate you carry...[n][w][e]
[f 2 1][f 5 21 1 404]Now, young lady... Bearer of light and shadow...[n][w][e]
[f 2 1][f 5 21 1 404]If you wish to know more about the near future... come and talk to me...[n][w][e]
[f 2 1][f 5 21 1 404]I will share my limited visions with you...[n][w][e]

[msg MSG_001_5_0 [Fortune Teller]]
[f 2 1][f 5 21 1 404]Now, tell me... What shall it be?[n][w][e]

[msg MSG_001_0_0 [Fortune Teller]]
[f 2 1][f 5 21 1 404]Would you like to know your fortune?[n][w][e]

[sel SEL_002_0_0 top]
[f 2 1]Yes, please.[e]
[f 2 1]No thanks.[e]

[msg MSG_003_0_0 [Fortune Teller]]
[f 2 1][f 5 21 1 404]Then let us begin...[n][w][e]

[msg MSG_004_0_0 [Fortune Teller]]
[f 2 1][f 5 21 1 404]Let us hope that you find fortune in your destiny...[n][w][e]

[msg MSG_005_0_0 [Fortune Teller]]
[f 2 1][f 5 21 1 404]Come back any time...[n][w][e]

[msg MSG_006_0_0 [Fortune Teller]]
[f 2 1][f 5 21 1 404]You have pulled fate's trigger...[n][w][e]
[f 2 1][f 5 21 1 404]The bullet passes through many, heading directly to its target...[n][w][e]
[f 2 1][f 5 21 1 404]What target that may be, however, is unknown to me...[n][w][e]
[f 2 1][f 5 21 1 404]You must find that out for yourself...[n][w][e]

[msg MSG_007_0_0 [Fortune Teller]]
[f 2 1][f 5 21 1 404]A long rail under the empty sky... On it stands youth in disarray...[n][w][e]
[f 2 1][f 5 21 1 404]You seem to live a tumultuous life...[n][w][e]
[f 2 1][f 5 21 1 404]What do you see at the end of the rail...?[n][w][e]

[msg MSG_008_0_0 [Fortune Teller]]
[f 2 1][f 5 21 1 404]I feel another change...[n][w][e]
[f 2 1][f 5 21 1 404]A strong wind blows across the world, sending a blue flower's petals into the air...[n][w][e]
[f 2 1][f 5 21 1 404]How will you interpret this wind...?[n][w][e]
[f 2 1][f 5 21 1 404]As a weak and frail breeze, or a brave and mighty gust...?[n][w][e]

[msg MSG_009_0_0 [Fortune Teller]]
[f 2 1][f 5 21 1 404]It seems you have made another friend...[n][w][e]
[f 2 1][f 5 21 1 404]A late-night affair, unseen by all... A bond made in the darkness, where the shadows lurk...[n][w][e]
[f 2 1][f 5 21 1 404]The result of this bond is too distant to be seen...[n][w][e]
[f 2 1][f 5 21 1 404]The only way to know how it will end is to see for yourself...[n][w][e]

[msg MSG_010_0_0 [Fortune Teller]]
[f 2 1][f 5 21 1 404]Shadows within shadows... Many shadows crawl amidst the immense shadow...[n][w][e]
[f 2 1][f 5 21 1 404]Twelve shadows, feasting upon the heart of man... Monstrous, yet dignified...[n][w][e]
[f 2 1][f 5 21 1 404]They gather around you... Beware...[n][w][e]

[msg MSG_011_0_0 [Fortune Teller]]
[f 2 1][f 5 21 1 404]Guns scattered in the billowing shadow... Arms reach in to grasp them...[n][w][e]
[f 2 1][f 5 21 1 404]Their muzzles pointed at different shadows; their triggers pulled on different occasions...[n][w][e]
[f 2 1][f 5 21 1 404]Where do you point your gun? What will occur as a result of its firing...?[n][w][e]
[f 2 1][f 5 21 1 404]Can you collect all the guns that have been scattered...?[n][w][e]

[msg MSG_012_0_0 [Fortune Teller]]
[f 2 1][f 5 21 1 404]I see a girl...[n][w][e]
[f 2 1][f 5 21 1 404]She stands between light and dark, life and simulacrum...[n][w][e]
[f 2 1][f 5 21 1 404]She falters... as if not knowing on which side she belongs...[n][w][e]
[f 2 1][f 5 21 1 404]Hm...? She is trying to tell you something...[n][w][e]
[f 2 1][f 5 21 1 404]Can you hear her words...?[n][w][e]

[msg MSG_013_0_0 [Fortune Teller]]
[f 2 1][f 5 21 1 404]Three blades close in on you, tearing the shadow apart... A brave howl confronts them...[n][w][e]
[f 2 1][f 5 21 1 404]Things seem to be stirring around you once again...[n][w][e]
[f 2 1][f 5 21 1 404]There is more...[n][w][e]
[f 2 1][f 5 21 1 404]In the depths of the abyss, another blade watches you closely...[n][w][e]

[msg MSG_014_0_0 [Fortune Teller]]
[f 2 1][f 5 21 1 404]A dark past, sinking into the deep shadow...[n][w][e]
[f 2 1][f 5 21 1 404]It enfolds the people who are involved and captures them...[n][w][e]
[f 2 1][f 5 21 1 404]Who are the ones that are trapped...?[n][w][e]
[f 2 1][f 5 21 1 404]Hard though I try to see them, my vision blurs, and everything becomes obscure...[n][w][e]
[f 2 1][f 5 21 1 404]Can you see...?[n][w][e]

[msg MSG_015_0_0 [Fortune Teller]]
[f 2 1][f 5 21 1 404]The golden sky spreads outside the window... A girl holding a world of white in her slender arms...[n][w][e]
[f 2 1][f 5 21 1 404]A boy struggles, searching to find meaning in himself and the girl...[n][w][e]
[f 2 1][f 5 21 1 404]But the conclusion has not yet been written... It is entrusted to the girl and her white world...[n][w][e]
[f 2 1][f 5 21 1 404]You must stand firmly, and watch things unfold...[n][w][e]

[msg MSG_016_0_0 [Fortune Teller]]
[f 2 1][f 5 21 1 404]After the storm comes not calm, but another trial...[n][w][e]
[f 2 1][f 5 21 1 404]Do not despair, however...[n][w][e]
[f 2 1][f 5 21 1 404]I sense strong forces at your side, even more so than before...[n][w][e]
[f 2 1][f 5 21 1 404]Be brave, and confront this hardship with unshakeable resolve...[n][w][e]

[msg MSG_017_0_0 [Fortune Teller]]
[f 2 1][f 5 21 1 404]A light has disappeared... The shadow grows darker...[n][w][e]
[f 2 1][f 5 21 1 404]But the lost light's will lives on in a strong, new light...[n][w][e]
[f 2 1][f 5 21 1 404]You have reached a turning point... The light has begun to challenge the shadow...[n][w][e]
[f 2 1][f 5 21 1 404]Your time is coming... soon...[n][w][e]

[msg MSG_018_0_0 [Fortune Teller]]
[f 2 1][f 5 21 1 404]A strong wind blows across the world, sending a blue flower's petals into the air...[n][w][e]
[f 2 1][f 5 21 1 404]The flower discovered the world, made friends to protect, and has become another light...[n][w][e]
[f 2 1][f 5 21 1 404]The lights are gathering around you... Be prepared...[n][w][e]

[msg MSG_019_0_0 [Fortune Teller]]
[f 2 1][f 5 21 1 404]A bridge lit by the full moon... Songs of victory echo in the air, as the shadow is overcome...[n][w][e]
[f 2 1][f 5 21 1 404]Go... Now is the time for celebration...[n][w][e]

[msg MSG_020_0_0 [Fortune Teller]]
[f 2 1][f 5 21 1 404]Under the fat crescent moon... a feeble light at the hollow tower...[n][w][e]
[f 2 1][f 5 21 1 404]A gunshot rings out, shattering my vision into a thousand pieces...[n][w][e]
[f 2 1][f 5 21 1 404]I am sorry... I can see no further...[n][w][e]
[f 2 1][f 5 21 1 404]But I can say this... The shadow yet remains...[n][w][e]

[msg MSG_021_0_0 [Fortune Teller]]
[f 2 1][f 5 21 1 404]Oh...? Is this a new friend...?[n][w][e]
[f 2 1][f 5 21 1 404]How mystifying... No one can see into his essence...[n][w][e]
[f 2 1][f 5 21 1 404]No one, save for one girl...[n][w][e]

[msg MSG_022_0_0 [Fortune Teller]]
[f 2 1][f 5 21 1 404]The answer and the secret to life are passed on, one life to the next...[n][w][e]
[f 2 1][f 5 21 1 404]Two lights now pierce through the shadow...[n][w][e]
[f 2 1][f 5 21 1 404]The hour draws near... How do you fare...?[n][w][e]

[msg MSG_023_0_0 [Fortune Teller]]
[f 2 1][f 5 21 1 404]A girl falls under the full moon... A boy walks amidst shadow, and he himself is shadow...[n][w][e]
[f 2 1][f 5 21 1 404]A child who bears shadows within...[n][w][e]
[f 2 1][f 5 21 1 404]The immense shadow approaches... Its depth unfathomable; its extent without limit...[n][w][e]
[f 2 1][f 5 21 1 404]It comes to end all things... The darkness hidden by the shining heavens...[n][w][e]
[f 2 1][f 5 21 1 404]How will you stand against such a fate...?[n][w][e]

[msg MSG_024_0_0 [Fortune Teller]]
[f 2 1][f 5 21 1 404]You have pulled the trigger of fate...[n][w][e]
[f 2 1][f 5 21 1 404]I see it now... The target was the shadow of impending doom...[n][w][e]
[f 2 1][f 5 21 1 404]Your goal is now clear...[n][w][e]
[f 2 1][f 5 21 1 404]Keep your flame of life ablaze until the end...[n][w][e]

[msg MSG_025_0_0 [Fortune Teller]]
[f 2 1][f 5 21 1 404]I see nothing...[n][w][e]
[f 2 1][f 5 21 1 404]No... What I see is nothingness... It is the void...[n][w][e]
[f 2 1][f 5 21 1 404]But do not lose heart... Emptiness is not necessarily the end...[n][w][e]
[f 2 1][f 5 21 1 404]The void is infinite... as is the universe...[n][w][e]
[f 2 1][f 5 21 1 404]Whether this marks an end to all things or a beginning...[n][w][e]
[f 2 1][f 5 21 1 404]It is in your hands...[n][w][e]

[sel SEL_026_0_0 top]
[f 2 1]I want to know my fortune.[e]
[f 2 1]I want to know my future.[e]
[f 2 1]No thanks.[e]

[msg MSG_027_0_0 [Fortune Teller]]
[f 2 1][f 5 21 1 404]Too much of a good thing can turn things for the worse... The same is true for fortune telling.[n][w][e]
[f 2 1][f 5 21 1 404]You have already learned of your fortune for today... Return another day if you seek it again.[n][w][e]

[msg MSG_028_0_0 [Fortune Teller]]
[f 2 1][f 5 21 1 404]What kind of fortune do you seek?[n][w][e]

[msg MND_029_1_0 [Fortune Teller]]
[f 2 1]Increases chances of encountering rare enemies in Tartarus.[n][w][e]

[msg MND_029_2_0 [Fortune Teller]]
[f 2 1]Increases chances of inflicting enemies with ailments in Tartarus.[n][w][e]

[msg MND_029_4_0 [Fortune Teller]]
[f 2 1]Increases chances of enemies turning into strong or rare enemies.[n][w][e]

[msg MND_029_5_0 [Fortune Teller]]
[f 2 1]Prevents unfavorable events, such as the Reaper appearing.[n][w][e]

[msg MND_029_6_0 [Fortune Teller]]
[f 2 1]Increases the rate at which Theurgy gauges charge.[n][w][e]

[msg MND_029_0_0 [Fortune Teller]]
[f 2 1]Fortune[n][w][e]

[msg MND_029_7_0 [Fortune Teller]]
[f 2 1]未使用[n][w][e]

[msg MND_030_0_0 [Fortune Teller]]
[f 2 1]What kind of fortune should I ask for?[n][w][e]

[sel SEL_031_0_0 top]
[f 2 1]Rarity Fortune [f 4 26 30 0][e]
[f 2 1]Gamble Fortune [f 4 26 32 0][e]
[f 2 1]Soul Fortune [f 4 26 34 0][e]
[f 2 1]Blighting Fortune [f 4 26 31 0][e]
[f 2 1]Safety Fortune [f 4 26 33 0][e]

[msg MSG_032_0_0 [Fortune Teller]]
[f 2 1][f 5 21 1 404]If that is what you wish, it will be [f 2 4 0] yen... You are sure this is what you want?[n][w][e]

[msg MSG_033_0_0 [Fortune Teller]]
[f 2 1][f 5 21 1 404]Ah, you wish to reconsider... Is there perhaps another fortune you would like?[n][w][e]

[msg MSG_034_0_0 [Fortune Teller]]
[f 2 1][f 5 21 1 404]I'm afraid you don't have enough money...[n][w][e]

[msg MSG_088_0_0 [Fortune Teller]]
[f 2 1][f 5 21 1 404]...I see it.[n][w][e]
[f 2 1][f 5 21 1 404]If you go to the tower of shadow tonight... you are destined to face an adversary clad in gold...[n][w][e]

[msg SYS_035_0_0]
[f 2 1][clr 2]The chance of encountering rare Shadows has increased[clr 27] when exploring Tartarus![n][w][e]

[msg MSG_088_1_0 [Fortune Teller]]

[msg MSG_090_0_0 [Fortune Teller]]
[f 2 1][f 5 21 1 404]...I see it.[n][w][e]
[f 2 1][f 5 21 1 404]If you go to the tower of shadow tonight... you are destined to gain advantage in conflicts...[n][w][e]

[msg SYS_036_0_0]
[f 2 1][clr 2]The chance of inflicting enemies with status ailments has increased[clr 27] when exploring Tartarus![n][w][e]

[msg MSG_091_0_0 [Fortune Teller]]
[f 2 1][f 5 21 1 404]...I see it.[n][w][e]
[f 2 1][f 5 21 1 404]If you go to the tower of shadow tonight... you will surely feel a powerful drive from within...[n][w][e]

[msg SYS_038_0_0]
[f 2 1]All allies' [clr 2]Theurgy gauges will charge faster[clr 27]![n][w][e]

[msg MSG_092_0_0 [Fortune Teller]]
[f 2 1][f 5 21 1 404]...I see it.[n][w][e]
[f 2 1][f 5 21 1 404]If you go to the tower of shadow tonight... your destiny holds a double-edged sword...[n][w][e]

[msg SYS_039_0_0]
[f 2 1][clr 2]The chance of events occurring that turn all Shadows on a floor into rare or strong Shadows has increased[clr 27] when exploring Tartarus![n][w][e]

[msg MSG_094_0_0 [Fortune Teller]]
[f 2 1][f 5 21 1 404]...I see it.[n][w][e]
[f 2 1][f 5 21 1 404]If you go to the tower of shadow tonight... your destiny holds a moment of tranquility...[n][w][e]

[msg SYS_040_0_0]
[f 2 1]Unlucky events (such as [clr 2]all Shadows turning into strong Shadows[clr 27], [clr 2]Dark Zones appearing[clr 27], or [clr 2]the Reaper emerging[clr 27]) will not occur in Tartarus![n][w][e]

[msg MSG_103_0_0 [Fortune Teller]]
[f 2 1][f 5 21 1 404]Oh...? It appears that there has been a change within you...[n][w][e]
[f 2 1][f 5 21 1 404]Well, allow me to provide you with a new fortune befitting the unusual light that you hold within.[n][w][e]

[msg SYS_104_0_0]
[f 2 1]You are now able to select the new fortune, [clr 2]Soul Fortune[clr 27]![n][w][e]

[msg MSG_105_0_0 [Fortune Teller]]
[f 2 1][f 5 21 1 404]Oh my... There is a haze surrounding the tower of shadow...[n][w][e]
[f 2 1][f 5 21 1 404]It seems you won't be entering the tower tonight. Please return another day for your fortune.[n][w][e]

[msg MSG_106_0_0 [Fortune Teller]]
[f 2 1]Oh...? The shadow that envelops you has become even darker...[n][w][e]
[f 2 1]I'm afraid I am unable to provide you with words that can guide you at this time.[n][w][e]
[f 2 1]I may be able to once the full moon passes... Please return another day for your fortune.[n][w][e]

[msg SYS_107_0_0]
[f 2 1]You are now able to select the new fortune, [clr 2]Rarity Fortune[clr 27]![n][w][e]

[msg SYS_108_0_0]
[f 2 1]You are now able to select the new fortune, [clr 2]Gamble Fortune[clr 27]![n][w][e]

[msg SYS_109_0_0]
[f 2 1]You are now able to select the new fortune, [clr 2]Blighting Fortune[clr 27]![n][w][e]

[msg SYS_110_0_0]
[f 2 1]You are now able to select the new fortune, [clr 2]Safety Fortune[clr 27]![n][w][e]

