[msg MSG_SENDER_NAME]
[f 2 1]Keisuke Hiraga[n][w][e]

[msg MSG_001_0_0]
[f 2 1]It's Hiraga.[n][w][e]

[msg MSG_002_0_0]
[f 2 1]Hi. I'm not sure if you remember me, but it's Hiraga from the art club.[n][f 1 5 0]You're not obligated to attend, obviously, but... [f 1 3 138] It would be really nice if you showed up.[n][f 1 5 0]I'll be in the art room if you decide to stop by. [f 1 3 137][n][w][e]

[msg MSG_003_0_0]
[f 2 1]It's Hiraga.[n][w][e]

[msg MSG_004_0_0]
[f 2 1]Hey, are you gonna be at the club meeting? No pressure, of course, but if you're interested, I'd really like to paint together again. [f 1 3 137][n][f 1 5 0]I'll have supplies ready for you if you come by.[n][w][e]

[msg MSG_005_0_0]
[f 2 1]Art Club.[n][w][e]

[msg MSG_006_0_0]
[f 2 1]You keep showing up, so that must mean we're doing something right, huh? [f 1 3 137][n][f 1 5 0]There should be a lot of members today, so it would be nice if you were there too. [f 1 3 136][n][f 1 5 0]I'll wait for you at the club room.[n][w][e]

[msg MSG_007_0_0]
[f 2 1]About quitting the club.[n][w][e]

[msg MSG_008_0_0]
[f 2 1]I feel like you deserve an explanation.[n][f 1 5 0]I'll tell you all about it today, even if I have to do it in the middle of the club meeting. [f 1 3 136][n][f 1 5 0]Hope to see you there.[n][w][e]

[msg MSG_009_0_0]
[f 2 1]Sorry about before.[n][w][e]

[msg MSG_010_0_0]
[f 2 1]I must have made everyone worry when I left all of a sudden. [f 1 3 138][n][f 1 5 0]Now that the dust has settled a little, I can focus on making art.[n][f 1 5 0]You should come by. It would be nice to paint together. [f 1 3 137][n][w][e]

[msg MSG_011_0_0]
[f 2 1]I've been thinking.[n][w][e]

[msg MSG_012_0_0]
[f 2 1]I thought I had this all figured out... [f 1 3 138][n][f 1 5 0]Do you worry about the future?[n][f 1 5 0]Maybe I'm too in my head about this... Hopefully painting will ease the existential dread lol.[n][w][e]

[msg MSG_013_0_0]
[f 2 1]Brain's too loud.[n][w][e]

[msg MSG_014_0_0]
[f 2 1]Still thinking about it... I've actually lost sleep over this. [f 1 3 138][n][f 1 5 0]But I'm scheduled for cleaning duty today, so I'll be at the art club. [f 1 3 136][n][f 1 5 0]Will I see you there?[n][w][e]

[msg MSG_015_0_0]
[f 2 1]I've made a decision.[n][w][e]

[msg MSG_016_0_0]
[f 2 1]Please, if you can make it today, come to the art club. I really want to see you.[n][f 1 5 0]Sorry. I don't mean to be selfish, it's just that I'd rather tell you in person.[n][w][e]

[msg MSG_017_0_0]
[f 2 1][nl]-chan.[n][w][e]

[msg MSG_018_0_0]
[f 2 1]I've asked everyone in the club to come today.[n][f 1 5 0]I'd love it if you came too. Actually, I've decided that you have to. Doctor's orders. [f 1 3 137][n][w][e]

[msg MSG_019_0_0]
[f 2 1]Painting buddy[n][w][e]

[msg MSG_020_0_0]
[f 2 1]Hi! You coming to the art club today?[n][f 1 5 0]Hope to see you there. [f 1 3 137][n][w][e]

[msg MSG_021_0_0]
[f 2 1]Burnt out...?[n][w][e]

[msg MSG_022_0_0]
[f 2 1]What better way to remedy that than a relaxing painting session?[n][f 1 5 0]...[n][f 1 5 0]Ok, sorry, I'll quit with the advertiser voice lol. Swing by if you'd like. [f 1 3 136][n][w][e]

[msg MSG_023_0_0]
[f 2 1]Art club meets today! [f 1 3 145][n][w][e]

[msg MSG_024_0_0]
[f 2 1]I've been trying out some new painting techniques lately. [f 1 3 137][n][f 1 5 0]I'd be happy to teach you some of what I've learned.[n][f 1 5 0]Of course, we can talk about things besides art, too.[n][w][e]

[msg MSG_025_0_0]
[f 2 1]Down time...[n][w][e]

[msg MSG_026_0_0]
[f 2 1]G'morning! [f 1 3 140][n][f 1 5 0]Been feeling the burnout starting to creep up on me, so I'm gonna take some time for myself and go out.[n][f 1 5 0]I know you're probably busy, but I'd love it if you joined me. Just let me know what you decide before this afternoon.[n][f 1 5 0]Thanks! [f 1 3 140] [f 1 3 137][n][w][e]

[msg MSG_027_0_0]
[f 2 1]Movie, maybe?[n][w][e]

[msg MSG_028_0_0]
[f 2 1]Sorry for reaching out on such short notice![n][f 1 5 0]There's a movie out right now that's been getting some critical acclaim regarding its artistic direction. I'm sure it'd help with your charisma, too. [f 1 3 151][n][f 1 5 0]I might've bought an extra ticket, and I was wondering if you'd like to come along. Let me know! [f 1 3 137][n][w][e]

