[msg MSG_000_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 3 0 65535 1067 0 0]Oh, [nl]-chan, good timing! Fuuka just suggested that we study for the exams together.[n][w][e]

[msg MSG_001_0_0 [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0][vp 3 0 65535 2006 0 0]C'mon, there's no point studying at a time like this. You're with me, right, dude?[n][w][e]

[msg MSG_002_0_0 [Yukari Takeba]]
[f 2 1][bup 2 6 65535 65535 0 0][vp 3 0 65535 1123 0 0]"At a time like this," huh? Like you'd want to study if things were normal...[n][w][e]

[msg MSG_003_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5003 0 0]Um, I just thought studying with everyone might help take our minds off things...[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0]So, if it's not too much trouble... What do you think, [nl]-chan?[n][w][e]

[msg MSG_004_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 3 0 65535 65535 0 0]DEV: UNUSED[n][w][e]

[msg MSG_005_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0]DEV: UNUSED[n][w][e]

[sel SEL_006_0_0 top]
[f 2 1]Let's study together.[e]
[f 2 1]What's everyone's status?[e]
[f 2 1]I want to go to Tartarus.[e]
[f 2 1]I'll pass.[e]

[msg MSG_007_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 3 0 65535 5039 0 0]Oh, I'm so happy to hear that. Thank you![n][w][e]

[msg MSG_008_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 3 0 65535 1116 0 0]Better get your stuff, then. And Junpei, stop doodling on your notes![n][w][e]

[msg MSG_009_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 3 0 65535 1028 0 0]Okay. I understand if you're not in the mood for it.[n][w][e]

[msg MSG_010_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 3 0 65535 5025 0 0]If you feel like studying, just let us know. We'll be here.[n][w][e]

[msg MSG_011_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5067 0 0]Oh, [nl]-chan. Did you change your mind?[n][w][e]

[msg MSG_011_1_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0]Are you up for studying with us?[n][w][e]

[msg MSG_012_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 3 0 65535 65535 0 0]DEV: UNUSED[n][w][e]

[msg MSG_013_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 2 0 65535 65535 0 0]DEV: UNUSED[n][w][e]

[sel SEL_014_0_0 top]
[f 2 1]Let's study together.[e]
[f 2 1]I want to go to Tartarus.[e]
[f 2 1]No thanks.[e]

[msg MSG_015_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 3 0 65535 5039 0 0]That's great! I'm so glad we can all study together again, even at a time like this...[n][w][e]

[msg MSG_016_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 3 0 65535 1116 0 0][nl]-chan, you can sit here. Come on, Junpei, stop zoning out![n][w][e]

[msg MSG_017_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 3 0 65535 1061 0 0]All right. Well, whenever you're up for it.[n][w][e]

[msg MSG_018_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 3 0 65535 5025 0 0]Feel free to join us anytime you feel like studying.[n][w][e]

[msg MSG_025_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0]These people already have plans, so they can't go tonight:[n][w][e]

[msg SYS_026_0_0]
[f 2 1]Yukari Takeba & Aigis[n][w][e]

[msg MSG_027_0_0 [Yukari Takeba]]
[f 2 1][bup 2 5 65535 65535 0 0][vp 3 0 65535 1077 0 0]...It's looking pretty bad for me this time.[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0]I haven't been able to study at all. I'm gonna have to cram everything starting now...[n][w][e]

[msg MSG_028_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0]Um... Can I help you with something else?[n][w][e]

[msg MSG_019_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 65535 65535 0 0][vp 3 0 65535 2098 0 0]Dude, are you serious!? I mean, I don't wanna study either, but...[n][w][e]

[msg MSG_061_0_0 [Yukari Takeba]]
[f 2 1][bup 2 5 65535 65535 0 0][vp 3 0 65535 1053 0 0]Uh, sorry, but if you're really gonna go to Tartarus, I'll have to pass. I really need to study...[n][w][e]

[msg MSG_020_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5061 0 0]Not everyone will be able to go today, then... Would you still like to go anyway?[n][w][e]

[sel SEL_021_0_0 top]
[f 2 1]Commence operation[e]
[f 2 1]Never mind.[e]

[msg MSG_022_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5028 0 0]...All right. Let's gather when the time comes, then.[n][w][e]

[msg MSG_023_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2094 0 0]Seriously...? Well, I guess it's better than studying...[n][w][e]

[msg MSG_024_0_0 [Yukari Takeba]]
[f 2 1][bup 2 4 65535 65535 0 0][vp 3 0 65535 1114 0 0]You scared me there for a second...[n][w][e]

[msg MND_Temperance]
[f 2 1]Right now, the Temperance Arcana[n]may help me grow even more...[n][w][e]

