[sel SEL_YESNO top]
[f 2 1]Open[e]
[f 2 1]Don't open[e]

[msg MND_TBOX_MEDAL]
[f 2 1]The number of [f 4 4 1 0 1 0]s[n]I have is [clr 2][f 2 4 2][clr 27]. Using [clr 2][f 2 4 1][clr 27] should open it...[n][w][e]

[msg MND_TBOX_MEDAL_OPEN]
[f 2 1]I used [clr 2][f 2 4 1][clr 27] of my [f 4 4 1 0 1 0]s,[n]so now I have [f 2 4 3] left.[n][w][e]

[msg MND_TBOX_MEDAL_NOT_ENOUG]
[f 2 1]If I had [clr 2][f 2 4 1][clr 27] [f 4 4 1 0 1 0]s, I could[n]open it, but I only have [clr 2][f 2 4 2][clr 27] right now.[n][w][e]

[msg MND_TBOX_MedalNone]
[f 2 1]I don't have any [f 4 4 1 0 1 0]s[n]on hand. It looks like I need [clr 2][f 2 4 1][clr 27] to open it.[n][w][e]

[msg MSG_TBOX_RETURN_FUKA [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 50 0 0]I don't sense any more treasure chests here.[n][w][e]
[f 2 1][bup 6 0 65535 50 0 0]It's still dangerous, so please try to come back as soon as you can.[n][w][e]

[msg MSG_TBOX_OPEN_TUTO [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 50 0 0][vp 1 0 1 20523 0 0]That looks like it'll be useful. It's up to you to decide how to use it.[n][w][e]

[msg MSG_1ST_TRY_MEDAL_OPENED [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 50 0 0][vp 3 0 65535 4607 0 0]Ah, I thought that's what that was.[n][w][e]
[f 2 1][bup 5 1 65535 50 0 0]That's a [clr 39]Twilight Fragment[clr 27]. They can be used on devices throughout Tartarus.[n][w][e]
[f 2 1][bup 5 0 65535 50 0 0]You might find more in Tartarus or other locations with traces of Shadows.[n][w][e]
[f 2 1][bup 5 0 65535 50 0 0]If you come across any going forward, you'll want to take them.[n][w][e]

[msg MND_GET_ARCANA_CARD]
[f 2 1]The [f 4 4 1 0 1 0] is reacting...[n][w][e]

[msg PFM_GET_CARD_TEMPERANCE]
[f 2 1]It seems the Temperance Major Arcana[n]card can now appear during Shuffle Time.[n][w][e]

[msg PFM_GET_CARD_DEVIL]
[f 2 1]It seems the Devil Major Arcana card[n]can now appear during Shuffle Time.[n][w][e]

[msg PFM_GET_CARD_TOWER]
[f 2 1]It seems the Tower Major Arcana card[n]can now appear during Shuffle Time.[n][w][e]

[msg PFM_GET_CARD_STAR]
[f 2 1]It seems the Star Major Arcana card[n]can now appear during Shuffle Time.[n][w][e]

[msg PFM_GET_CARD_MOON]
[f 2 1]It seems the Moon Major Arcana card[n]can now appear during Shuffle Time.[n][w][e]

[msg PFM_GET_CARD_SUN]
[f 2 1]It seems the Sun Major Arcana card[n]can now appear during Shuffle Time.[n][w][e]

[msg PFM_GET_CARD_JUDGEMENT]
[f 2 1]It seems the Judgement Major Arcana[n]card can now appear during Shuffle Time.[n][w][e]

[msg MSG_ESCAPE_FUKA_00 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 50 0 0][vp 3 0 65535 5025 0 0]It looks like a dead end. Do you want to head back right away?[n][w][e]

[sel SEL_ESCAPE_HERO top]
[f 2 1]Leave Monad[e]
[f 2 1]Continue exploring[e]

[msg MSG_ESCAPE_FUKA_10 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 50 0 0]Okay.[n][w][e]
[f 2 1][bup 6 0 65535 50 0 0]Be careful on your way back.[n][w][e]

[msg MSG_ESCAPE_FUKA_11 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 50 0 0]Oh, do you think you might have missed something?[n][w][e]
[f 2 1][bup 6 0 65535 50 0 0]Well, there are no enemies left, but it's still dangerous.[n][w][e]
[f 2 1][bup 6 0 65535 50 0 0]Please be careful if you're going to keep exploring.[n][w][e]

[msg MND_ARAGAKI_REMIND]
[f 2 1]This would've looked good on Aragaki...[n]but he isn't here anymore...[n][w][e]

[msg MSG_TUTO01 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 50 0 0][vp 3 0 65535 5071 0 0]It looks like what the chairman gave you before, doesn't it, [nl]-chan?[n][w][e]
[f 2 1][bup 6 0 65535 50 0 0]It's apparently really rare. I'm surprised to see it in a place like this.[n][w][e]

[msg MND_TUTO02]
[f 2 1]Maybe the owner of the antique shop could[n]craft it into a piece of equipment for me...[n][w][e]

[msg MSG_TUTO03 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 50 0 0]It looks like you've seen everything here. Good job.[n][w][e]
[f 2 1][bup 6 0 65535 50 0 0]I think it's a good time to leave now. Please exit back out the door.[n][w][e]

[sel SEL_EQUIP_UPDATE_00 top]
[f 2 1]Equip [f 4 4 1 0 0 0][e]
[f 2 1]Keep current equipment[e]

[sel SEL_EQUIP_UPDATE_01 top]
[f 2 1]Replace with new equipment[e]
[f 2 1]Keep current equipment[e]

[sel SEL_EQUIP_UPDATE_02 top]
[f 2 1]Give to Yukari[e]
[f 2 1]Keep current equipment[e]

[sel SEL_EQUIP_UPDATE_03 top]
[f 2 1]Give to Junpei[e]
[f 2 1]Keep current equipment[e]

[sel SEL_EQUIP_UPDATE_04 top]
[f 2 1]Give to Sanada[e]
[f 2 1]Keep current equipment[e]

[sel SEL_EQUIP_UPDATE_05 top]
[f 2 1]Give to Mitsuru[e]
[f 2 1]Keep current equipment[e]

[sel SEL_EQUIP_UPDATE_06 top]
[f 2 1]未使用[e]

[sel SEL_EQUIP_UPDATE_07 top]
[f 2 1]Give to Aigis[e]
[f 2 1]Keep current equipment[e]

[sel SEL_EQUIP_UPDATE_08 top]
[f 2 1]Give to Amada[e]
[f 2 1]Keep current equipment[e]

[sel SEL_EQUIP_UPDATE_09 top]
[f 2 1]Give to Koromaru[e]
[f 2 1]Keep current equipment[e]

[sel SEL_EQUIP_UPDATE_10 top]
[f 2 1]Give to Aragaki[e]
[f 2 1]Keep current equipment[e]

[msg MND_EQUIP_UPDATE_HERO_00]
[f 2 1][f 4 4 1 0 1 0]...[n]Looks pretty good.[n][w][e]

[msg MSG_EQUIP_UPDATE_YUKARI_ [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 3 0 65535 1002 0 0]Hey, that's a nice-looking bow! I can use it, right?[n][w][e]

[msg MSG_EQUIP_UPDATE_JUNPEI_ [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2001 0 0]Yo, that weapon looks beastly! But it'd take a real master like me to make good use of it, so...[n][w][e]

[msg MSG_EQUIP_UPDATE_SANADA_ [Akihiko Sanada]]
[f 2 1][bup 4 1 65535 65535 0 0][vp 3 0 65535 3094 0 0]Oh, a new weapon, huh? It looks even better than what I'm using right now.[n][w][e]

[msg MSG_EQUIP_UPDATE_MITSURU [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4086 0 0]Ah, that looks like a fine weapon. Would you mind if I used it?[n][w][e]

[msg MSG_EQUIP_UPDATE_FUKA_00 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 50 0 0][vp 3 0 65535 5087 0 0]Oh, there was a weapon inside. I think Koro-chan would be able to use that one well.[n][w][e]

[msg MSG_EQUIP_UPDATE_AEGIS_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6080 0 0]New armaments acquired. It appears to be an upgrade. I propose a retrofit.[n][w][e]

[msg MSG_EQUIP_UPDATE_AMADA_0 [Ken Amada]]
[f 2 1][bup 8 1 65535 65535 0 0][vp 3 0 65535 7005 0 0]A new weapon...? May I please use it!?[n][w][e]

[msg MSG_EQUIP_UPDATE_KORO_00 [Koromaru]]
[f 2 1][bup 9 1 65535 65535 0 0][vp 3 0 65535 8001 0 0]Arf! Arf![n][w][e]

[msg MSG_EQUIP_UPDATE_ARAGAKI [Shinjiro Aragaki]]
[f 2 1][bup 10 1 65535 65535 0 0][vp 3 0 65535 9007 0 0]Well, what do we have here? You should let me use it.[n][w][e]

[msg MSG_EQUIP_UPDATE_AEGIS_0_2 [Aigis]]
[f 2 1][bup 7 1 65535 65535 0 0][vp 3 0 65535 6087 0 0]Oh, we have acquired new armaments! May I use it?[n][w][e]

[msg MND_EQUIP_UPDATE_HERO_01]
[f 2 1][f 4 4 1 0 1 0]...[n]Seems pretty good.[n][w][e]

[msg MSG_EQUIP_UPDATE_YUKARI__2 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 3 0 65535 1002 0 0]Ooh, that looks great! Whaddaya say? Can I use it?[n][w][e]

[msg MSG_EQUIP_UPDATE_JUNPEI__2 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2001 0 0]Hey, sick armor. I think it'd help bring out my inner charm, y'know?[n][w][e]

[msg MSG_EQUIP_UPDATE_SANADA__2 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 3 0 65535 3094 0 0]I think this armor would suit me well. Mind if I use it?[n][w][e]

[msg MSG_EQUIP_UPDATE_MITSURU_2 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4086 0 0]What a splendid piece of armor. I imagine it'd be more effective than what I'm currently using.[n][w][e]

[msg MSG_EQUIP_UPDATE_FUKA_01 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 50 0 0][vp 3 0 65535 5087 0 0]Oh! Don't you think that armor would be perfect for Koro-chan?[n][w][e]

[msg MSG_EQUIP_UPDATE_AEGIS_0_3 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6080 0 0]It appears to be a defensive article. I recommend allowing me to equip it.[n][w][e]

[msg MSG_EQUIP_UPDATE_AMADA_0_2 [Ken Amada]]
[f 2 1][bup 8 1 65535 65535 0 0][vp 3 0 65535 7005 0 0]Um, could I use that new armor? Even if it doesn't fit now, I'll definitely grow into it![n][w][e]

[msg MSG_EQUIP_UPDATE_KORO_01 [Koromaru]]
[f 2 1][bup 9 1 65535 65535 0 0][vp 3 0 65535 8001 0 0]Arf! Arf![n][w][e]

[msg MSG_EQUIP_UPDATE_ARAGAKI_2 [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 3 0 65535 9007 0 0]Hey, that's a decent find. I'll hold onto it if nobody's using it.[n][w][e]

[msg MSG_EQUIP_UPDATE_AEGIS_0_4 [Aigis]]
[f 2 1][bup 7 1 65535 65535 0 0][vp 3 0 65535 6087 0 0]That armor appears sturdier than my current equipment. Would it be okay if I used it?[n][w][e]

[msg MND_EQUIP_UPDATE_MULTI]
[f 2 1]Who should I give the[n][f 4 4 1 0 1 0]...?[n][w][e]

[sel SEL_PARTY top]
[f 2 1]Equip on self[e]
[f 2 1]Yukari[e]
[f 2 1]Junpei[e]
[f 2 1]Sanada[e]
[f 2 1]Mitsuru[e]
[f 2 1]Fuuka[e]
[f 2 1]Aigis[e]
[f 2 1]Amada[e]
[f 2 1]Koromaru[e]
[f 2 1]Aragaki[e]
[f 2 1]Don't equip now[e]

[msg MND_EQUIP_UPDATE_HERO_10]
[f 2 1]I've equipped the [f 4 4 1 0 1 0].[n][w][e]

[msg MSG_EQUIP_UPDATE_YUKARI__3 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 3 0 65535 1039 0 0]Yes! Thanks, I'll take good care of it![n][w][e]

[msg MSG_EQUIP_UPDATE_JUNPEI__3 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2117 0 0]Aw yeah, upgrade time, baby! Let's keep it rollin'![n][w][e]

[msg MSG_EQUIP_UPDATE_SANADA__3 [Akihiko Sanada]]
[f 2 1][bup 4 1 65535 65535 0 0][vp 3 0 65535 3042 0 0]There's no substitute for training, but I'll take solid gear where we can find it too.[n][w][e]

[msg MSG_EQUIP_UPDATE_MITSURU_3 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4038 0 0]You have my gratitude. I won't let you down.[n][w][e]

[msg MSG_EQUIP_UPDATE_FUKA_10 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 50 0 0]未使用[n][w][e]

[msg MSG_EQUIP_UPDATE_AEGIS_1 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6038 0 0]Equipment upgrade confirmed. I anticipate an improved combat performance.[n][w][e]

[msg MSG_EQUIP_UPDATE_AMADA_1 [Ken Amada]]
[f 2 1][bup 8 1 65535 65535 0 0][vp 3 0 65535 7040 0 0]Thank you very much. I'll do my best to be of help![n][w][e]

[msg MSG_EQUIP_UPDATE_KORO_10 [Koromaru]]
[f 2 1][bup 9 1 65535 65535 0 0][vp 3 0 65535 8012 0 0]Woof, woof![n][w][e]

[msg MSG_EQUIP_UPDATE_ARAGAKI_3 [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 3 0 65535 9051 0 0]Good choice. I'll see to it that you don't regret it.[n][w][e]

[msg MSG_EQUIP_UPDATE_AEGIS_1_2 [Aigis]]
[f 2 1][bup 7 1 65535 65535 0 0][vp 3 0 65535 6039 0 0]Equipment upgrade confirmed. Now I'm sure to improve even further![n][w][e]

[msg MSG_HIGH_RARE_TUTO_MITU_ [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 50 0 0]I'm no longer getting a signal from the Shadow. It must be fairly far away...[n][w][e]

[msg MSG_HIGH_RARE_TUTO_MITU__2 [Mitsuru Kirijo]]
[f 2 1][bup 5 3 65535 50 0 0]Well, it got the chest, but at least it knows we're here.[n][w][e]
[f 2 1][bup 5 0 65535 50 0 0]I'm sure it won't be able to ignore us if we keep opening treasure chests.[n][w][e]
[f 2 1][bup 5 0 65535 50 0 0]So let's keep looking for chests. We just might run into that Shadow again.[n][w][e]

[msg MSG_HIGH_RARE_TUTO_FUKA_ [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 50 0 0]I don't sense the Shadow anymore. It's probably pretty far away by now...[n][w][e]

[msg MSG_HIGH_RARE_TUTO_FUKA__2 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 50 0 0]It got the treasure chest... but I think it noticed us.[n][w][e]
[f 2 1][bup 6 0 65535 50 0 0]We should be able to get its attention if we keep opening chests.[n][w][e]
[f 2 1][bup 6 0 65535 50 0 0]Let's keep looking for them.[n][w][e]

[msg MSG_HIGH_RARE_BTL_MITU_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 50 0 0]The Shadow's coming our way. Get ready![n][w][e]

[msg MSG_HIGH_RARE_BTL_MITU_0_2 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 50 0 0]The target Shadow has been eliminated. Good work.[n][w][e]
[f 2 1][bup 5 0 65535 50 0 0]There aren't any Shadows left on this floor. Let's keep moving.[n][w][e]

[msg MSG_HIGH_RARE_BTL_FUKA_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 50 0 0]The Shadow's headed straight for us! This is our chance! Are you ready?[n][w][e]

[msg MSG_HIGH_RARE_BTL_FUKA_0_2 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 50 0 0]It looks like you defeated the Shadow. Good job.[n][w][e]
[f 2 1][bup 6 0 65535 50 0 0]I'm not sensing any more enemies on this floor. Let's move on.[n][w][e]

