[msg MSG_SANADA_TARTAROS_0701 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0]Did you hear? The next operation will be on July 7th.[n][w][e]
[f 2 1][bup 4 1 65535 65535 0 0]That means it's going to be a Star Festival special bout.[n][w][e]

[msg MSG_FUKA_TARTAROS_0704 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0]You probably already know this, but the next full moon will be on Tuesday of next week.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]I'm sure some kind of Shadow will show up.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Please be ready.[n][w][e]

[msg MSG_JUNPEI_TARTAROS_0706 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0]Tomorrow's the day.[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]If we lose, the city gets overrun with the Lost, right?[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]We gotta win this, no matter what...[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]Yo, let's go to Tartarus tonight. We can beat some Shadows to a pulp to brush up our skills![n][w][e]

[msg MSG_JUNPEI_0706 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0]Tomorrow's the day.[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]If we lose, the city gets overrun with the Lost, right?[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]We gotta win this, no matter what...[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]You down for hitting Tartarus later? I wanna pack on some muscle.[n][w][e]

[msg MSG_JUNPEI_OK_0706 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0]Tomorrow's the day.[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]If we lose, the city gets overrun with the Lost, right?[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]We gotta win this, no matter what. We're the peace keepers of this here town! ...Just kidding.[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]Well, we oughta get in gear. If you're goin' to Tartarus today, count me in![n][w][e]

[msg MSG_FUKA_0706 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5067 0 0]Oh, that's right, [nl]-chan.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]For tomorrow, I think I'll have you stand by at the dorm just in case...[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0]So if there are preparations you need to make, please take care of them today.[n][w][e]

[msg MSG_YUKARI_TARTAROS_0708 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0]Sorry, I need to talk to Fuuka...[n][w][e]

[sel SEL_004_0_0 top]
[f 2 1]About what?[e]
[f 2 1]Want to go to Tartarus?[e]

[msg MSG_YUKARI_0708_RE1 [Yukari Takeba]]
[f 2 1][bup 2 10 65535 65535 0 0][vp 3 0 65535 1093 0 0]Oh, um, there's something I have to clear up.[n][w][e]

[msg MSG_YUKARI_0708_RE2 [Yukari Takeba]]
[f 2 1][bup 2 10 65535 65535 0 0][vp 3 0 65535 1092 0 0]Um... I'm feelin' kinda tired today, so I'd rather not.[n][w][e]

[msg MSG_FUKA_TARTAROS_0708 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5003 0 0]I'm sure you're burnt out coming right off an operation...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]You know, it might do you good to just rest today.[n][w][e]

[msg MSG_MITSURU_STUDY_0709 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0]Feeling rested?[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]There's still some time until the next full moon, and while I wish I could tell you to take it slow...[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Finals start next Monday, so I'd like you to care for your health and concentrate on your studies.[n][w][e]

[msg MSG_YUKARII_STUDY_0710 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0]Hey, are you free tonight?[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0]With exams coming up, I thought maybe we second-years could hold a study session...[n][w][e]

[msg MSG_JUNPEI_STUDY_0710_1 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0]Pass. I'm headin' to my room.[n][w][e]

[msg MSG_YUKARII_STUDY_0710_0 [Yukari Takeba]]
[f 2 1][bup 2 4 65535 65535 0 0][vp 3 0 65535 1098 0 0]Huh? Wait— Junpei![n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0]Oh well, his loss. You, me, and Fuuka can still study together.[n][w][e]

[msg MND_0718]
[f 2 1]That antique shop in Paulownia Mall...[n]The chairman suggested I pay them a visit...[n][w][e]
[f 2 1]I'll head over there now...[n][w][e]

[msg MSG_JUNPEI_TARTAROS_0723 [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0]*sigh* Man, I'm beat...[n][w][e]
[f 2 1][bup 3 3 65535 65535 0 0]It seemed to take forever to get back...[n][w][e]

[msg MSG_FUKA_TARTAROS_0723 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 3 0 65535 5143 0 0]Yeah, it was a tiring trip.[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0]Please rest up so you're ready for the next operation.[n][w][e]

[msg MSG_YUKARI_TARTAROS_0723 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 3 0 65535 1028 0 0]There are six more to fight, right?[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0]Just the last full moon Shadows and things will go back to normal. No more Apathy Syndrome incidents, just plain, old, everyday life...[n][w][e]
[f 2 1][bup 2 2 65535 65535 0 0]Let's do our best! After all, we're the only ones who can help.[n][w][e]

[msg MSG_FUKA_0724_1 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0]By the way, how'd you fare on your exams?[n][w][e]

[sel SEL_022_0_0 top]
[f 2 1]Not too shabby.[e]
[f 2 1]Pretty badly...[e]

[msg MSG_FUKA_0724_RE_1 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 3 0 65535 5131 0 0]That's great news! I'm happy for you.[n][w][e]

[msg MSG_FUKA_0724_RE_2 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0][vp 3 0 65535 5065 0 0]Oh...[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0]Well, it is still just the first semester... You'll be all right.[n][w][e]

[msg MSG_FUKA_0724_2 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0]That reminds me, Kirijo-senpai was top of her class again![n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]I mean, where does she find the time? She's unreal.[n][w][e]

[msg MSG_AEGIS_0724_1 [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 3 0 65535 6001 0 0]...In two weeks, the moon will be full again.[n][w][e]

[msg MSG_JUNPEI_0724_1 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2061 0 0]Dude, those freaks with Apathy Syndrome will be everywhere— Wait, I mean the Lost.[n][w][e]
[f 2 1][bup 3 3 65535 65535 0 0]I mean, I feel bad for the victims and all, but seriously, it's like there's no end to 'em![n][w][e]

[msg MSG_AEGIS_0724_2 [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 3 0 65535 6037 0 0]Technically speaking, there is an end to them: six Shadows remain.[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0]If we can eliminate them, the Dark Hour will vanish.[n][w][e]

[msg MSG_JUNPEI_0724_2 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2066 0 0]Yeah, that's true...[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]So, what you're trying to say, Aigis, is that fighting is more important than studying, right?[n][w][e]
[f 2 1][bup 3 9 65535 65535 0 0]I agree 100%![n][w][e]

[msg MSG_AMADA_TARTAROS_0725 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0]My name is Ken Amada. I'll be staying here for a while.[n][w][e]
[f 2 1][bup 8 0 65535 65535 0 0]I'll try not to be a bother, so please don't mind me.[n][w][e]

[msg MSG_AMADA_TARTAROS_0726 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0]Come to think of it, have you heard about [clr 2]Be Blue V[clr 27]?[n][w][e]
[f 2 1][bup 8 0 65535 65535 0 0]It's this shop in Paulownia Mall, but there's a rumor you can talk to spirits there![n][w][e]
[f 2 1][bup 8 3 65535 65535 0 0]Sounds a little sketchy, huh? I wonder what kind of shop it is...[n][w][e]

[msg MSG_JUNPEI_0727_1 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0]Oh, that's right, didn't you have club today? How'd it go?[n][w][e]

[sel SEL_032_0_0 top]
[f 2 1]It was no sweat.[e]
[f 2 1]It wore me out.[e]

[msg MSG_JUNPEI_0727_RE_1 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2108 0 0]Oh, yeah? You're tougher than I thought.[n][w][e]

[msg MSG_JUNPEI_0727_RE_2 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2094 0 0]Well, don't push yourself too hard, dude.[n][w][e]

[msg MSG_JUNPEI_TARTAROS_0727 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0]Hey, if you think you can handle it, let's go to Tartarus tonight![n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]It's a little less than two weeks 'til the full moon, so I kinda wanna hit the bullpen.[n][w][e]

[msg MSG_JUNPEI_0727_2 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0]Hey, if you think you can handle it, let's go to Tartarus tonight![n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]It's a little less than two weeks 'til the full moon. Gotta get that conditioning in, right?[n][w][e]

[msg MSG_JUNPEI_OK_0727_2 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0]So, as long as you're off the injury list...[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]We're coming up on just under two weeks 'til the full moon, so don't go getting hurt, yeah?[n][w][e]

[msg MSG_MITSURU_TARTAROS_072 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0]Apathy Syndrome is on the rise again...[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]People seem to have calmed down a bit, despite the media, but there will be serious problems if we don't end this.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]We must defeat the last six Shadows, beginning with the one we anticipate on the next full moon.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]If the number of The Lost continues to increase, this city will fall into chaos.[n][w][e]

[msg MSG_JUNPEI_TARTAROS_0728 [Junpei Iori]]
[f 2 1][bup 3 4 65535 65535 0 0][vp 3 0 65535 2098 0 0]Y-You're just exaggerating, right?[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]...Then again, maybe not.[n][w][e]

[msg MSG_FUKA_TARTAROS_0729 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0]The others aren't back yet...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Kirijo-senpai said they'd be here by midnight.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]...Maybe we shouldn't go to Tartarus today.[n][w][e]

[msg MSG_JUNPEI_TARTAROS_0730 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0]One more week 'til the moon is full again...[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]You seen how things look at Paulownia Mall lately? The Lost are really on the rise...[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]I feel like it's really on us to do something about this now. Let's wipe the floor with these Shadows![n][w][e]

[msg MSG_YUKARI_TARTAROS_0731 [Yukari Takeba]]
[f 2 1][bup 2 3 65535 65535 0 0]Hey... Doesn't it seem like there's a lot more of the Lost than before?[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0]There were quite a few in the city today. They were making my friend really anxious...[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0]*sigh* When's the next full moon again, next week? We really have to bring our A-game, don't we?[n][w][e]

[msg MSG_WELCOME_YUKARI_OUT [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 3 0 65535 1019 0 0]Oh, hey. Welcome back.[n][w][e]

[msg MSG_WELCOME_YUKARI_OUT2 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 3 0 65535 1012 0 0]Hey... Welcome back...[n][w][e]

[msg MSG_WELCOME_JUNPEI_OUT [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2018 0 0]'Sup, dude?[n][w][e]

[msg MSG_WELCOME_JUNPEI_OUT2 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2012 0 0]Hey, man...[n][w][e]

[msg MSG_WELCOME_MITSURU_OUT [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4018 0 0]Welcome back.[n][w][e]

[msg MSG_WELCOME_MITSURU_OUT2 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4027 0 0]Welcome back...[n][w][e]

[msg MSG_WELCOME_SANADA_OUT [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 3 0 65535 3017 0 0]Oh, you're back.[n][w][e]

[msg MSG_WELCOME_FUKA_OUT [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5018 0 0]Hi, how was your day?[n][w][e]

[msg MSG_WELCOME_FUKA_OUT2 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5028 0 0]Oh... Hello...[n][w][e]

[msg MSG_WELCOME_AEGIS_OUT_RO [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 3 0 65535 6018 0 0]Greetings.[n][w][e]

[msg MSG_WELCOME_AEGIS_OUT [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6018 0 0]Greetings.[n][w][e]

[msg MSG_WELCOME_AEGIS_OUT_NA [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6017 0 0]Welcome back. It's good to see you again.[n][w][e]

[msg MSG_WELCOME_KOROMARU_OUT [Koromaru]]
[f 2 1][bup 9 0 65535 65535 0 0][vp 3 0 65535 8008 0 0]Arf![n][w][e]

[msg MSG_WELCOME_AMADA_OUT [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 3 0 65535 7020 0 0]Oh, hello![n][w][e]

[msg MSG_WELCOME_AMADA_OUT2 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 3 0 65535 7012 0 0]Oh... Hi...[n][w][e]

[msg MSG_WELCOME_ARAGAKI_OUT [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 3 0 65535 9014 0 0]...Hey.[n][w][e]

[msg MSG_WELCOME_IKUTSUKI_OUT [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 3 0 65535 14201 0 0]Hello there. Welcome back.[n][w][e]

[msg MSG_WELCOME_YUKARI_IN [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 3 0 65535 1067 0 0]Oh, there you are![n][w][e]

[msg MSG_WELCOME_YUKARI_IN2 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 3 0 65535 1012 0 0]Oh, you're here? Sorry, guess I missed you...[n][w][e]

[msg MSG_WELCOME_JUNPEI_IN [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2009 0 0]Yooo, what's up?[n][w][e]

[msg MSG_WELCOME_JUNPEI_IN2 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2012 0 0]Oh, hey...[n][w][e]

[msg MSG_WELCOME_MITSURU_IN [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4029 0 0]Hm? Oh, it's you.[n][w][e]

[msg MSG_WELCOME_MITSURU_IN2 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4027 0 0]Hm...? Oh, I see you're here...[n][w][e]

[msg MSG_WELCOME_SANADA_IN [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 3 0 65535 3024 0 0]Were you in your room all this time?[n][w][e]

[msg MSG_WELCOME_FUKA_IN [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5067 0 0]Oh, hello! I didn't realize you were already here.[n][w][e]

[msg MSG_WELCOME_FUKA_IN2 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5093 0 0]Oh, you're here? Hello...[n][w][e]

[msg MSG_WELCOME_FUKA_IN_0712 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5067 0 0]Oh, [nl]-chan...![n][w][e]

[msg MSG_WELCOME_AEGIS_IN_ROB [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 3 0 65535 6008 0 0]Good evening.[n][w][e]

[msg MSG_WELCOME_AEGIS_IN [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6008 0 0]Good evening.[n][w][e]

[msg MSG_WELCOME_AEGIS_IN_NAK [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6009 0 0]Did you have a good day?[n][w][e]

[msg MSG_WELCOME_KOROMARU_IN [Koromaru]]
[f 2 1][bup 9 0 65535 65535 0 0][vp 3 0 65535 8001 0 0]Arf, arf![n][w][e]

[msg MSG_WELCOME_AMADA_IN [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 3 0 65535 7010 0 0]Get any studying done?[n][w][e]

[msg MSG_WELCOME_AMADA_IN2 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 3 0 65535 7012 0 0]You were here? Well... Hello.[n][w][e]

[msg MSG_WELCOME_ARAGAKI_IN [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 3 0 65535 9056 0 0]...'Sup?[n][w][e]

[msg MSG_WELCOME_IKUTSUKI_IN [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 3 0 65535 14204 0 0]Oh, I didn't know you were already here. As you can see, I've come over for a quick visit.[n][w][e]

[msg MND_SHYUKAKU_OK]
[f 2 1]Come to think of it, the crops I planted on the[n]rooftop should be ready to harvest by now...[n][w][e]
[f 2 1]Maybe I should go check on them...[n][w][e]

[msg MND_SHYUKAKU_TAIYAKI_OK]
[f 2 1]Come to think of it, the crops I planted on the[n]rooftop should be ready to harvest by now...[n][w][e]
[f 2 1]...And the taiyaki I put in the[n]fridge should be chilled, too.[n][w][e]
[f 2 1]Maybe I should go check on them...[n][w][e]

[msg MND_SHYUKAKU_TAIYAKI_OK_]
[f 2 1]Come to think of it, the crops I planted on the[n]rooftop should be ready to harvest by now...[n][w][e]
[f 2 1]...And the taiyaki I put in the[n]fridge should be chilled, too.[n][w][e]
[f 2 1]I should get it from the fridge[n]and give it to Elizabeth...[n][w][e]

[msg MND_TAIYAKI_OK]
[f 2 1]Come to think of it, the taiyaki I put in[n]the fridge should be chilled by now...[n][w][e]
[f 2 1]Maybe I should go get it...[n][w][e]

[msg MND_TAIYAKI_OK_QUEST]
[f 2 1]Come to think of it, the taiyaki I put in[n]the fridge should be chilled by now...[n][w][e]
[f 2 1]I should get it from the fridge[n]and give it to Elizabeth...[n][w][e]

[msg MSG_ERROR [Shuji Ikutsuki]]
[f 2 1]エラーメッセージです。[n][f 1 5 0]杉山まで報告ください。[n][w][e]

