[msg MSG_000_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 3 65535 65535 0 0][vp 1 0 0 1 0 0]H-Hey. Sorry to make you come here. I, um... Ah, damn it...[n][w][e]

[sel SEL_001_0_0 top]
[f 2 1]Spit it out![e]
[f 2 1]Are you in trouble?[e]

[msg MSG_002_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 3 65535 65535 0 0][vp 1 0 0 2 0 0][f 5 13 2 5 101]Ah, sorry... You're right.[n][w][e]

[msg MSG_003_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 10 65535 65535 0 0][vp 1 0 0 3 0 0][f 5 13 2 15 101]Y-Yeah. I... I...[n][w][e]

[msg MSG_004_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 10 65535 65535 0 0][vp 1 0 0 4 0 0]Dude,it's bad! I don't know what to do![n][w][e]
[f 2 1][bup 101 10 65535 65535 0 0][vp 1 0 0 5 0 0]The school found out about Emiri and me! It blew up and became this huge thing...[n][w][e]
[f 2 1][bup 101 10 65535 65535 0 0][vp 1 0 0 6 0 0]And now she's being transferred to a school in Kyushu. What do I do!?[n][w][e]

[sel SEL_005_0_0 top]
[f 2 1]You should go with her.[e]
[f 2 1]You two should talk it out.[e]
[f 2 1]Figure it out yourself.[e]

[msg MSG_006_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 2 65535 65535 0 0][vp 1 0 0 7 0 0][f 5 13 2 5 101]Yeah, yeah, that's what I was thinking! I mean, I want to...[n][w][e]

[msg MSG_007_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 3 65535 65535 0 0][vp 1 0 0 8 0 0]Only... Emiri said I can't.[n][w][e]

[msg MSG_008_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 4 65535 65535 0 0][vp 1 0 0 9 0 0][f 5 13 2 5 101]Yeah, that's what I thought![n][w][e]

[msg MSG_009_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 3 65535 65535 0 0][vp 1 0 0 10 0 0]Except I feel like she's totally avoiding me...[n][w][e]

[msg MSG_010_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 3 65535 65535 0 0][vp 1 0 0 11 0 0]Wh-What the hell!? You're the only one I can count on...[n][w][e]

[msg MSG_011_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 3 65535 65535 0 0][vp 1 0 0 12 0 0]It's like, all of a sudden, she won't answer my calls or reply to my texts.[n][w][e]
[f 2 1][bup 101 3 65535 65535 0 0][vp 1 0 0 13 0 0]She's probably only doing this to protect me, but still...[n][w][e]

[msg MSG_012_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 10 65535 65535 0 0][vp 1 0 0 14 0 0]I can't just sit here and do nothing.[n][w][e]
[f 2 1][bup 101 10 65535 65535 0 0][vp 1 0 0 15 0 0]I gotta think of a plan. And I'm gonna need your help.[n][w][e]

[msg MND_013_0_0]
[f 2 1]Tomochika opened up to[n]me about his troubles.[n][w][e]
[f 2 1]I feel like our relationship is stronger...[n][w][e]

[msg MSG_014_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 3 65535 65535 0 0][vp 1 0 0 16 0 0]I'll see ya soon. Thanks for hearing me out today.[n][w][e]

[msg MND_015_0_0]
[f 2 1]I parted ways with Tomochika[n]and went back to the dorm.[n][w][e]

