[msg MSG_000_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 3 0 65535 1016 0 0]Mornin'.[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0]Hey... Have you talked to Mochizuki-kun at all?[n][w][e]

[sel SEL_001_0_0 top]
[f 2 1]Nope.[e]
[f 2 1]A little bit.[e]

[msg MSG_002_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 3 0 65535 1062 0 0]Oh, okay. I was just wondering what sort of person he is.[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0]He seems really, um... affectionate? Is that normal overseas?[n][w][e]

[msg MSG_003_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 3 0 65535 1107 0 0]Oh yeah? You think maybe you could get along with him?[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0]He seems really, um... affectionate? Is that normal overseas?[n][w][e]

[msg MSG_004_0_0 [Ryoji Mochizuki]]
[f 2 1][bup 221 0 65535 65535 0 0][vp 3 0 65535 14001 0 0]Why, hello, Takeba-san... Oh, and good morning to you, too, [nf]-chan.[n][w][e]

[msg MSG_005_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 3 0 65535 1093 0 0]Oh, hey. G'morning, Mochizuki-kun.[n][w][e]

[msg MSG_006_0_0 [Ryoji Mochizuki]]
[f 2 1][bup 221 1 65535 65535 0 0][vp 3 0 65535 14030 0 0]Please, call me Ryoji.[n][w][e]
[f 2 1][bup 221 1 65535 65535 0 0]You see, since I transferred here at such an awkward time, I was hoping I could get to know everyone better.[n][w][e]

[msg MSG_007_0_0 [Yukari Takeba]]
[f 2 1][bup 2 3 65535 65535 0 0][vp 3 0 65535 1028 0 0]Oh, I see...[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][f 4 23 0 2 0 25 25]It must suck having to transfer schools so often.[n][w][e]

[msg MSG_008_0_0 [Ryoji Mochizuki]]
[f 2 1][bup 221 0 65535 65535 0 0][vp 3 0 65535 14010 0 0]Can't deny that. I should be used to it by now, but it's always hard to leave new friends. Gets a little lonely, you know?[n][w][e]
[f 2 1][bup 221 1 65535 65535 0 0][f 4 23 0 221 1 25 25]So, how about keeping me company for a little while? Wanna grab a quick bite sometime?[n][w][e]

[msg MSG_009_0_0 [Ryoji Mochizuki]]
[f 2 1][bup 221 4 65535 65535 0 0][vp 3 0 65535 14028 0 0]Yukari-san...? Hey, wait up![n][w][e]

