[msg MSG_000_0_0 [Bebe]]
[f 2 1][bup 112 1 65535 65535 0 0][vp 3 0 65535 11900 0 0]I bought a CD with traditional Japanese folk songs![n][w][e]
[f 2 1][bup 112 1 65535 65535 0 0]These songs are simple, yes, but they are rich with the history of their region of origin![n][w][e]

[msg MSG_001_0_0 [Bebe]]
[f 2 1][bup 112 0 65535 65535 0 0]Ah, speaking of music in Japan...[n][w][e]
[f 2 1][bup 112 0 65535 65535 0 0]I love the sound crickets make. It is very soothing and very melodic.[n][w][e]

[msg MSG_002_0_0 [Bebe]]
[f 2 1][bup 112 0 65535 65535 0 0][vp 3 0 65535 11876 0 0]Do you like it, too, [nf]-sama?[n][w][e]

[sel SEL_003_0_0 top]
[f 2 1]Yeah, I do.[e]
[f 2 1]I don't, actually.[e]
[f 2 1]It's okay.[e]

[msg MSG_004_0_0 [Bebe]]
[f 2 1][bup 112 1 65535 65535 0 0][vp 3 0 65535 11895 0 0][f 5 13 15 30 112]Just as I thought! Crickets are indeed an international sensation, a global hit![n][w][e]
[f 2 1][bup 112 1 65535 65535 0 0]I would very much like my aunt to get the opportunity to hear these crickets...[n][w][e]

[msg MND_005_0_0]
[f 2 1]Bebe is singing merrily.[n][w][e]
[f 2 1]I feel like we became a lot closer today.[n][w][e]

[msg MSG_006_0_0 [Bebe]]
[f 2 1][bup 112 3 65535 65535 0 0][vp 3 0 65535 11904 0 0]Oh my! The sound is not to your liking? How sad...[n][w][e]

[msg MND_007_0_0]
[f 2 1]Bebe seems disappointed.[n][w][e]
[f 2 1]I feel like we didn't get any closer today...[n][w][e]

[msg MSG_008_0_0 [Bebe]]
[f 2 1][bup 112 0 65535 65535 0 0][vp 3 0 65535 11839 0 0][f 5 13 15 15 112]"Okay"? It is only okay? Then you must know of a sound that is even better! Hmmm...[n][w][e]
[f 2 1][bup 112 1 65535 65535 0 0][f 4 23 0 112 1 25 25]Perhaps nightingales? Or maybe bamboo fountains or cicadas? Japan does have many sounds that are soothing to the ear![n][w][e]

[msg MND_009_0_0]
[f 2 1]Bebe seems impressed.[n][w][e]
[f 2 1]I learned a little more about him today...[n][w][e]

[msg MSG_010_0_0 [Bebe]]
[f 2 1][bup 112 0 65535 65535 0 0][vp 3 0 65535 11880 0 0]I just had a great idea... I will collect all the beautiful sounds of Japan and send them to my aunt![n][w][e]
[f 2 1][bup 112 0 65535 65535 0 0]Now I must purchase a casette tape to record these sounds. Come, [nf]-sama![n][w][e]

[msg MND_011_0_0]
[f 2 1]After shopping with Bebe,[n]I returned to the dorm.[n][w][e]

