[msg MSG_000_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 1 65535 65535 0 0][vp 1 0 0 1 0 0][f 4 23 0 1 1 25 25]Another day, another bowl of ramen![n][w][e]

[msg MND_001_0_0]
[f 2 1]Despite its simple appearance,[n]the soup has a complex flavor[n]that's enhanced by the noodles.[n][w][e]

[msg MSG_002_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 1 65535 65535 0 0][vp 1 0 0 2 0 0][f 4 23 0 1 1 25 25]Damn, this really is some bomb ramen. How could I ever leave this city!?[n][w][e]

[msg MSG_002_5_0 [Kenji Tomochika]]
[f 2 1][bup 101 0 65535 65535 0 0][vp 0 0 0 3 0 0][f 4 23 0 1 0 25 25]......[n][w][e]
[f 2 1][bup 101 0 65535 65535 0 0][vp 1 0 0 4 0 0][f 4 23 0 1 0 25 25]Ms. Kanou must be in Kyushu by now. I wonder if she had her wedding already.[n][w][e]

[sel SEL_003_0_0 top]
[f 2 1]......[e]
[f 2 1]Maybe she did.[e]
[f 2 1]I'm stealing your egg![e]

[msg MSG_004_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 6 65535 65535 0 1][vp 1 0 0 5 0 0][f 4 23 0 1 3 25 25][f 5 13 2 5 101]You really don't you have anything to say to me?[n][w][e]
[f 2 1][bup 101 6 65535 65535 0 1][vp 1 0 0 6 0 0][f 4 23 0 1 3 25 25]Nothing inspiring or encouraging?[n][w][e]
[f 2 1][bup 101 6 65535 65535 0 1][vp 1 0 0 7 0 0][f 4 23 0 1 3 25 25]Anything? You gotta learn when to say the right words...[n][w][e]

[msg MSG_005_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 0 65535 65535 0 0][vp 1 0 0 8 0 0][f 4 23 0 1 0 25 25]And you know what else? My favorite show had its finale, and I didn't even notice.[n][w][e]
[f 2 1][bup 101 1 65535 65535 0 0][vp 1 0 0 9 0 0][f 4 23 0 1 1 25 25]My mind was really on one track for a while, huh? Kinda funny in a weird way.[n][w][e]

[msg MSG_006_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 4 65535 65535 0 0][vp 1 0 0 10 0 0][f 4 23 0 1 4 25 25]Heeey, give that back![n][w][e]
[f 2 1][bup 101 2 65535 65535 0 0][vp 1 0 0 11 0 0][f 4 23 0 1 2 25 25]That egg's all I got in this world, man! Hand it over or else![n][w][e]

[msg MND_007_0_0]
[f 2 1]We chatted for a while...[n][w][e]

[msg MSG_008_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 1 65535 65535 0 0][vp 1 0 0 12 0 0][f 4 23 0 1 1 25 25]Man, it's always a blast hanging out with you. That said... I still want a girlfriend![n][w][e]

[sel SEL_009_0_0 top]
[f 2 1]You don't know when to give up...[e]
[f 2 1]You've got this![e]
[f 2 1]Want me to find you a girl?[e]

[msg MSG_010_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 1 65535 65535 0 0][vp 1 0 0 13 0 0][f 4 23 0 1 1 25 25][f 5 13 2 5 101]Hell no! Men and women can't help but be attracted to each other. That's just biology.[n][w][e]
[f 2 1][bup 101 1 65535 65535 0 0][vp 1 0 0 14 0 0][f 4 23 0 1 1 25 25]C'mon, I just dropped some serious knowledge there. See how much I've been studying?[n][w][e]

[msg MSG_011_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 1 65535 65535 0 0][vp 1 0 0 15 0 0][f 4 23 0 1 1 25 25][f 5 13 2 15 101]Yeah! And you can be my wingman! Let's go pick up some chicks![n][w][e]

[msg MSG_012_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 4 65535 65535 0 0][vp 1 0 0 16 0 0][f 4 23 0 1 4 25 25][f 5 13 2 15 101]Really? Who? Someone from your dorm?[n][w][e]
[f 2 1][bup 101 1 65535 65535 0 0][vp 1 0 0 17 0 0][f 4 23 0 1 1 25 25]Sounds like I should be making more surprise visits.[n][w][e]

[msg MSG_013_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 4 65535 65535 0 0][vp 1 0 0 18 0 0][f 4 23 0 1 4 25 25]Ah, no, no— I'm getting off track![n][w][e]
[f 2 1][bup 101 0 65535 65535 0 0][vp 1 0 0 19 0 0][f 4 23 0 1 0 25 25]I've been doing some thinking after everything that went down.[n][w][e]

[msg MSG_013_3_0 [Kenji Tomochika]]
[f 2 1][bup 101 0 65535 65535 0 0][vp 1 0 0 20 0 0][f 4 23 0 1 0 25 25]When Emiri left, I was sad, sure. But on top of that, I felt... really dumb.[n][w][e]
[f 2 1][bup 101 0 65535 65535 0 0][vp 1 0 0 21 0 0][f 4 23 0 1 0 25 25]Did I really love Emiri, or did I just love the idea of dating a teacher?[n][w][e]
[f 2 1][bup 101 0 65535 65535 0 0][vp 1 0 0 22 0 0][f 4 23 0 1 0 25 25]I thought about it a lot.[n][w][e]
[f 2 1][bup 101 0 65535 65535 0 0][vp 0 0 0 23 0 0][f 4 23 0 1 0 25 25]......[n][w][e]

[msg MSG_013_5_0 [Kenji Tomochika]]
[f 2 1][bup 101 0 65535 65535 0 0][vp 1 0 0 24 0 0][f 4 23 0 1 0 25 25]But I couldn't figure it out.[n][w][e]
[f 2 1][bup 101 0 65535 65535 0 0][vp 1 0 0 25 0 0][f 4 23 0 1 0 25 25]What I did figure out is... you're a true friend.[n][w][e]

[sel SEL_014_0_0 top]
[f 2 1]...Are we still talking about love?[e]
[f 2 1]That's right! We're great friends.[e]

[msg MSG_015_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 4 65535 65535 0 1][vp 1 0 0 26 0 0][f 4 23 0 1 4 25 25]We're talking about the heart! Don't you feel it? Just shut up and feel it![n][w][e]

[msg MSG_016_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 6 65535 65535 0 1][vp 1 0 0 27 0 0][f 4 23 0 1 3 25 25]Ugh, dammit! Why do I say such embarrassing things!? God, I'm such a dumbass.[n][w][e]

[msg MSG_017_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 0 65535 65535 0 0][vp 1 0 0 28 0 0][f 4 23 0 1 0 25 25]Anyway... Here, take this.[n][w][e]

[msg MND_018_0_0]
[f 2 1]DEV: *Unused message label. *If this appears, it is a bug.[n][w][e]

[msg MSG_019_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 1 65535 65535 0 0][vp 1 0 0 29 0 0][f 4 23 0 1 1 25 25]I made it for you. Figured you could pull it off.[n][w][e]
[f 2 1][bup 101 1 65535 65535 0 0][vp 1 0 0 30 0 0][f 4 23 0 1 1 25 25]Your fashion sense is kinda meh, so I wanted to help you out. I mean, that's what best friends do, right?[n][w][e]
[f 2 1][bup 101 1 65535 65535 0 0][vp 1 0 0 31 0 0][f 4 23 0 1 1 25 25]It's a symbol of our friendship![n][w][e]

[msg MND_020_0_0]
[f 2 1]Tomochika told me I'm his best friend.[n][w][e]
[f 2 1]I feel a strong bond with Tomochika...[n][w][e]

[msg SYS_021_0_0]
[f 2 1]The Magician Social Link reached its maximum level! You can now fuse [clr 35]Futsunushi[clr 27], the warrior god![n][w][e]

[msg MSG_022_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 6 65535 65535 0 1][vp 1 0 0 32 0 0][f 4 23 0 1 3 25 25]I worked up an appetite acting all weird around you![n][w][e]
[f 2 1][bup 101 6 65535 65535 0 1][vp 1 0 0 33 0 0][f 4 23 0 1 3 25 25]More eggs, please! Make it ten![n][w][e]

[msg MND_023_0_0]
[f 2 1]Tomochika and I spent hours hanging out.[n][w][e]

