[msg MSG_000_0_0 [Mr. Ekoda]]
[f 2 1][bup 1082 0 65535 65535 0 0][vp 1 0 0 1 0 0][f 5 21 0 1001]Hmm? Yamagishi, what are you doing outside the faculty office?[n][w][e]

[msg MSG_001_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 4 65535 65535 0 0][vp 1 0 0 2 0 0]Oh, well... I-I want to start a tech club![n][w][e]

[msg MSG_002_0_0 [Mr. Ekoda]]
[f 2 1][bup 1082 0 65535 65535 0 0][vp 1 0 0 3 0 0][f 5 21 0 1001]Tech gloves?[n][w][e]
[f 2 1][bup 1082 0 65535 65535 0 0][vp 1 0 0 4 0 0][f 5 21 0 1001]...Are you referring to technician's gloves?[n][w][e]
[f 2 1][bup 1082 0 65535 65535 0 0][vp 1 0 0 5 0 0][f 5 21 0 1001]I think you'd have to go to a hardware store for those.[n][w][e]

[msg MSG_003_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 4 65535 65535 0 0][vp 1 0 0 6 0 0]Um, not "tech gloves"... A tech club![n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 7 0 0][f 4 23 0 6 0 25 25]Like a club all about technology and electronics![n][w][e]

[msg MSG_004_0_0 [Mr. Ekoda]]
[f 2 1][bup 1082 0 65535 65535 0 0][vp 1 0 0 8 0 0][f 5 21 0 1001]You want to start a club now?[n][w][e]
[f 2 1][bup 1082 0 65535 65535 0 0][vp 1 0 0 9 0 0][f 5 21 0 1001]...Why is it always you, Yamagishi?[n][w][e]
[f 2 1][bup 1082 0 65535 65535 0 0][vp 1 0 0 10 0 0][f 5 21 0 1001]Look, it's already March. Can't you at least wait until April?[n][w][e]

[msg MSG_005_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 4 65535 65535 0 0][vp 1 0 0 11 0 0]Huh? B-But I really want to get this group going![n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 12 0 0][f 4 23 0 6 0 25 25]I promise I'll do my best to find members and all that... So, do I have your permission to start the club?[n][w][e]

[msg MSG_006_0_0 [Mr. Ekoda]]
[f 2 1][bup 1082 0 65535 65535 0 0][vp 1 0 0 13 0 0][f 5 21 0 1001]What? You don't even have any members yet? Then it's not even worth discussing.[n][w][e]
[f 2 1][bup 1082 0 65535 65535 0 0][vp 1 0 0 14 0 0][f 5 21 0 1001]You can't start a club without at least five members.[n][w][e]
[f 2 1][bup 1082 0 65535 65535 0 0][vp 1 0 0 15 0 0][f 5 21 0 1001]Now, I must be going.[n][w][e]

[msg MSG_007_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 16 0 0]And he's gone...[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 17 0 0]Well, it looks like I need to find five people now.[n][w][e]

[msg MSG_008_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 18 0 0]...[nl]-chan, would you like to join my tech club?[n][w][e]

[sel SEL_009_0_0 top]
[f 2 1]Of course.[e]
[f 2 1]...I'll think about it.[e]

[msg MSG_010_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 19 0 0]Yesss! I'm so happy to hear that![n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 20 0 0]I was hoping you'd help me.[n][w][e]

[msg MSG_011_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 6 65535 65535 0 0][vp 1 0 0 21 0 0]Oh... Well, I think it'd be a lot of fun to have a tech club.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 22 0 0][f 4 23 0 6 0 25 25]But I guess I do tend to drag you into things only I'm interested in...[n][w][e]

[msg MSG_012_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0][vp 0 0 0 23 0 0]......[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 24 0 0]You know... I used to think it was wrong for me to like electronics.[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 25 0 0]I always kept it to myself, because I thought it was a strange thing for a girl to be interested in.[n][w][e]

[msg MSG_013_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 26 0 0]But you accepted me for who I am, [nl]-chan.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 27 0 0]That's why I decided to be strong and let everyone know who I really am.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 28 0 0]Even if people think I'm strange, I know it's okay.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 29 0 0]I have you with me, so there's nothing to be scared of.[n][w][e]

[msg MSG_014_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 30 0 0]Now I want to meet more people like me and hang out with them.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 31 0 0]Since I kept my love of electronics hidden, I never had any friends who shared my interests.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 32 0 0]That's why I thought I'd try starting a club all about it.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 33 0 0]Because maybe there are other people out there who like this stuff too. And if so, I want a way to talk to them.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 34 0 0]I do admit I'm a little nervous though...[n][w][e]

[msg MSG_015_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 35 0 0]But don't worry! I'll still keep going to art club.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 36 0 0]It'll probably get really busy... but I want to keep trying.[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 37 0 0][f 4 23 0 6 1 25 25]It's like... jumping off the diving board at the pool. That kind of feeling.[n][w][e]

[msg MSG_016_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 0 0 0 38 0 0]......[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 39 0 0]You'll stay in art club next year too, won't you, [nl]-chan?[n][w][e]

[sel SEL_017_0_0 top]
[f 2 1]I'd like to.[e]
[f 2 1]Not sure.[e]

[msg MSG_018_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 40 0 0]...That's good.[n][w][e]

[msg MSG_019_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 41 0 0]Oh... Really?[n][w][e]

[msg MSG_020_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 42 0 0]Next year, I want to be in whatever clubs you're in.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 43 0 0]I'd like to be in the same homeroom, too...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 44 0 0]And I'd love to see you more at the dorm...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 45 0 0]I think I just want to be with you more in general...[n][w][e]

[msg MSG_021_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 46 0 0]I keep asking "more" of you, don't I...?[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 47 0 0]...If there's anything I can do for you, don't hesitate to ask.[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 48 0 0]I know I'm not the most reliable...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 49 0 0][f 4 23 0 6 0 25 25]But I want to get to know you better.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 50 0 0]I want to be closer to you...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 0 0 0 51 0 0]......[n][w][e]

[msg MSG_022_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 4 65535 65535 0 0][vp 1 0 0 52 0 0]Oh! I-I've got to hurry and find some club members! And I need to make recruitment posters too...[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 53 0 0][f 4 23 0 6 1 25 25]W-Well, I'll see you later![n][w][e]

[msg MSG_023_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 1 0][vp 1 0 0 54 0 0]Next time... maybe we can talk about it more in my room...?[n][w][e]
[f 2 1][bup 6 0 65535 65535 1 0][vp 0 0 0 55 0 0][f 4 23 0 6 0 25 25]......[n][w][e]
[f 2 1][bup 6 1 65535 65535 1 0][vp 1 0 0 56 0 0][f 4 23 0 6 1 25 25]Now I really have to go now! Bye![n][w][e]

[msg MSG_024_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 57 0 0]But you and the team accepted me for who I am, [nl]-chan.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 58 0 0]That's why I decided to be strong and let everyone see my true self.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 59 0 0]So even if people think I'm strange, I know it's okay.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 60 0 0]I don't want to hide it anymore.[n][w][e]

[msg MSG_025_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 61 0 0]Now I want to meet more people like me and hang out with them.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 62 0 0]Since I kept my love of electronics hidden, I never had any friends who shared my interests.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 63 0 0]That's why I thought I'd try starting a club all about it.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 64 0 0]Because maybe there are other people out there who like this stuff too. And if so, I want a way to talk to them.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 65 0 0]I do admit I'm a little nervous though...[n][w][e]

[msg MSG_026_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 66 0 0]But don't worry! I'll still keep going to art club.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 67 0 0]It'll probably get really busy... but I want to keep trying.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 68 0 0]It's like... jumping off the diving board at the pool. That kind of feeling.[n][w][e]

[msg MSG_027_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 69 0 0]...Anyways, I've got to find some club members![n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 70 0 0][f 4 23 0 6 0 25 25]Hmm... Do I need to make recruitment posters and stuff?[n][w][e]

[sel SEL_028_0_0 top]
[f 2 1]You've got this.[e]
[f 2 1]Need some help?[e]

[msg MSG_029_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 71 0 0]Yes, thank you.[n][w][e]

[msg MSG_030_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 72 0 0]Thank you, but... I'm going to try this on my own first.[n][w][e]

[msg MSG_031_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 73 0 0]...To be honest, I'd be lying if I said I wasn't worried.[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 74 0 0]We're going to be third-years soon.[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 75 0 0]And that means everyone'll have to start thinking about what they want to do after we graduate.[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 76 0 0]In fact, Iori-kun and Yukari-chan were talking about college entrance exams just the other day...[n][w][e]

[msg MSG_032_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 77 0 0]But you know what? I think I'll be okay.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 78 0 0]I have everyone here to support me, so there's nothing to be afraid of.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 0 0 0 79 0 0]......[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 80 0 0][f 4 23 0 6 3 25 25]...Everyone?[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 81 0 0]I keep saying it, but who am I talking about...?[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 82 0 0][f 4 23 0 6 0 25 25]...Um, sorry. Don't mind me.[n][w][e]

[msg MSG_084_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 4 65535 65535 0 0][vp 1 0 0 83 0 0]Oh, I didn't realize it was so late! I hope the stores are still open...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 84 0 0][f 4 23 0 6 0 25 25]Let's see, I need paper... Oh, and I need to find a clubroom too...[n][w][e]

[msg MSG_033_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 85 0 0]I think this might be more work than I thought![n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 86 0 0][f 4 23 0 6 0 25 25]Sorry, [nl]-chan. I need to get going.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 87 0 0]I'll see you later![n][w][e]

