[msg MSG_000_0_0 [Representative]]
[f 2 1][vp 1 0 0 1 0 0]Attention![n][w][e]
[f 2 1][vp 1 0 0 2 0 0]The time is upon us to demonstrate outstanding sportsmanship! May the best runner win![n][w][e]

[msg MSG_001_0_0 [Kazushi Miyamoto]]
[f 2 1][bup 105 0 101 65535 0 0][vp 1 0 0 3 0 0]Hey, you're almost up, [nl]![n][w][e]

[msg MSG_002_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 101 65535 0 0][vp 1 0 0 4 0 0]How are you feeling? Think you got this?[n][w][e]

[sel SEL_003_0_0 top]
[f 2 1]Definitely.[e]
[f 2 1]I'm a little nervous.[e]
[f 2 1]Don't forget to cheer for me.[e]

[msg MSG_004_0_0 [Kazushi Miyamoto]]
[f 2 1][bup 105 1 101 65535 0 0][vp 1 0 0 5 0 0]Ooh, that's what I like to hear![n][w][e]
[f 2 1][bup 105 0 101 65535 0 0][vp 1 0 0 6 0 0][f 4 23 0 105 0 25 25]Since this is your first time, let me give you some advice.[n][w][e]
[f 2 1][bup 105 2 101 65535 0 0][vp 1 0 0 7 0 0][f 4 22 0 105 32 25 20][f 4 23 0 105 2 25 25][f 4 21 105 7]All you have to do is give it your all![n][w][e]
[f 2 1][bup 105 2 101 65535 0 0][vp 1 0 0 8 0 0]Remember, mind over matter![n][w][e]
[f 2 1][bup 105 2 101 65535 0 0][vp 1 0 0 9 0 0]And the biggest enemy out there... is yourself![n][w][e]

[msg MSG_005_0_0 [Kazushi Miyamoto]]
[f 2 1][bup 105 1 101 65535 0 0][vp 1 0 0 10 0 0]Yeah, I thought you might be.[n][w][e]
[f 2 1][bup 105 1 101 65535 0 0][vp 1 0 0 11 0 0][f 4 22 0 105 25 25 20]But don't worry, man! Everyone's like that in the beginning.[n][w][e]
[f 2 1][bup 105 0 101 65535 0 0][vp 1 0 0 12 0 0][f 4 23 0 105 0 25 25]Well, this is your first time, so let me give you some advice.[n][w][e]
[f 2 1][bup 105 2 101 65535 0 0][vp 1 0 0 13 0 0][f 4 22 0 105 32 25 20][f 4 23 0 105 2 25 25][f 4 21 105 7]All you have to do is give it your all![n][w][e]
[f 2 1][bup 105 2 101 65535 0 0][vp 1 0 0 14 0 0]Remember, mind over matter![n][w][e]
[f 2 1][bup 105 2 101 65535 0 0][vp 1 0 0 15 0 0]And the biggest enemy out there... is yourself![n][w][e]

[msg MSG_006_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 101 65535 0 0][vp 1 0 0 16 0 0]You got it! Leave the cheering to me![n][w][e]
[f 2 1][bup 106 1 101 65535 0 0][vp 1 0 0 17 0 0][f 4 22 0 106 9 25 8]Oh yeah... Here, take this, [nl]-chan.[n][w][e]
[f 2 1][bup 106 1 101 65535 0 0][vp 1 0 0 18 0 0]It should help get you energized for the race.[n][w][e]

[msg MSG_007_0_0 [Kazushi Miyamoto]]
[f 2 1][bup 105 1 101 65535 0 0][vp 1 0 0 19 0 0]Since this is your first big event, let me give you some advice.[n][w][e]
[f 2 1][bup 105 2 101 65535 0 0][vp 1 0 0 20 0 0][f 4 22 0 105 32 25 20][f 4 23 0 105 2 25 25][f 4 21 105 7]All you have to do is give it your all![n][w][e]
[f 2 1][bup 105 2 101 65535 0 0][vp 1 0 0 21 0 0]Remember, mind over matter![n][w][e]
[f 2 1][bup 105 2 101 65535 0 0][vp 1 0 0 22 0 0]And the biggest enemy out there... is yourself![n][w][e]

[msg MSG_008_0_0 [Kazushi Miyamoto]]
[f 2 1][bup 105 2 101 65535 0 0][vp 1 0 0 23 0 0]Alright, dude![n][w][e]
[f 2 1][bup 105 2 101 65535 0 0][vp 1 0 0 24 0 0]Go show 'em what you're made of![n][w][e]

[msg MSG_009_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 101 65535 0 0][vp 1 0 0 25 0 0]Woooooo! Keep it up, [nl]-chan![n][w][e]

[msg MSG_010_0_0 [Kazushi Miyamoto]]
[f 2 1][bup 105 1 101 65535 0 0][vp 1 0 0 26 0 0]Whoa! Holy crap, she's fast! Go, go, goooooo![n][w][e]

[msg MSG_011_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 101 65535 0 0][vp 1 0 0 27 0 0]That was amazing, [nl]-chan! I can't believe it's your first time competing![n][w][e]
[f 2 1][bup 106 1 101 65535 0 0][vp 1 0 0 28 0 0]On top of that, this was your fastest time yet![n][w][e]

[msg MSG_012_0_0 [Kazushi Miyamoto]]
[f 2 1][bup 105 1 101 65535 0 0][vp 1 0 0 29 0 0]Man, you killed it![n][w][e]
[f 2 1][bup 105 1 101 65535 0 0][vp 1 0 0 30 0 0]Looks like all your hard work paid off.[n][w][e]

[msg MSG_013_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 3 101 65535 0 0][vp 1 0 0 31 0 0]Still a bummer, though...[n][w][e]
[f 2 1][bup 106 3 101 65535 0 0][vp 1 0 0 32 0 0]Even with your incredible performance, that guy still won.[n][w][e]

[msg MSG_014_0_0 [Kazushi Miyamoto]]
[f 2 1][bup 105 0 101 65535 0 0][vp 1 0 0 33 0 0]You mean Hayase, right? They say he blows everyone out of the water in every competition.[n][w][e]
[f 2 1][bup 105 0 101 65535 0 0][vp 1 0 0 34 0 0][f 4 22 0 105 25 25 20]I thought people were exaggerating, but geez, he's insane![n][w][e]
[f 2 1][bup 105 0 101 65535 0 0][vp 1 0 0 35 0 0]Could sure use someone like him on our team...[n][w][e]
[f 2 1][bup 105 2 101 65535 0 0][vp 1 0 0 36 0 0][f 4 22 0 105 27 25 20][f 4 21 105 7][f 4 23 0 105 2 25 25]Arghhh, dammit![n][w][e]
[f 2 1][bup 105 2 101 65535 0 0][vp 1 0 0 37 0 0]We'll get 'em next time for sure![n][w][e]

[msg MSG_015_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 4 101 65535 0 0][vp 1 0 0 38 0 0]Hey, wait! Isn't that him?[n][w][e]

[msg MSG_016_0_0 [Competitor Named Hayase]]
[f 2 1][bup 115 0 65535 65535 0 0][vp 1 0 0 39 0 0]Yo.[n][w][e]
[f 2 1][bup 115 0 65535 65535 0 0][vp 1 0 0 40 0 0]You were pretty fast.[n][w][e]

[sel SEL_017_0_0 top]
[f 2 1]I've been training.[e]
[f 2 1]Not fast enough.[e]

[msg MSG_018_0_0 [Competitor Named Hayase]]
[f 2 1][bup 115 0 65535 65535 0 0][vp 1 0 0 41 0 0]Must've been some training...[n][w][e]

[msg MSG_019_0_0 [Competitor Named Hayase]]
[f 2 1][bup 115 1 65535 65535 0 0][vp 1 0 0 42 0 0]Plenty enough to make me sweat a bit.[n][w][e]

[msg MSG_020_0_0 [Competitor Named Hayase]]
[f 2 1][bup 115 0 65535 65535 0 0][vp 1 0 0 43 0 0]Hey, I know this is weird all of a sudden...[n][w][e]
[f 2 1][bup 115 0 65535 65535 0 0][vp 1 0 0 44 0 0]But would you want to hang out sometime?[n][w][e]

[sel SEL_021_0_0 top]
[f 2 1]Sure, I don't mind.[e]
[f 2 1]Why?[e]

[msg MSG_022_0_0 [Competitor Named Hayase]]
[f 2 1][bup 115 1 65535 65535 0 0][vp 1 0 0 45 0 0]Cool, sounds good.[n][w][e]
[f 2 1][bup 115 0 65535 65535 0 0][vp 1 0 0 46 0 0][f 4 23 0 115 0 25 25]You still need to work on your technique, but I feel like you've got potential.[n][w][e]
[f 2 1][bup 115 0 65535 65535 0 0][vp 1 0 0 47 0 0][f 4 22 0 115 33 25 20]Maybe you could help push me to test my limits.[n][w][e]

[msg MSG_023_0_0 [Competitor Named Hayase]]
[f 2 1][bup 115 0 65535 65535 0 0][vp 1 0 0 48 0 0]You still need to work on your technique, but I feel like you've got potential.[n][w][e]
[f 2 1][bup 115 0 65535 65535 0 0][vp 1 0 0 49 0 0][f 4 22 0 115 33 25 20]Maybe you could help push me to test my limits.[n][w][e]
[f 2 1][bup 115 0 65535 65535 0 0][vp 1 0 0 50 0 0]That's why.[n][w][e]

[msg MSG_024_0_0 [Competitor Named Hayase]]
[f 2 1][bup 115 0 65535 65535 0 0][vp 1 0 0 51 0 0]I usually grab a bite to eat at the [clr 2]strip mall[clr 27] in Iwatodai [clr 2]after school[clr 27]...[n][w][e]

[msg MSG_025_0_0 [Competitor Named Hayase]]
[f 2 1][bup 115 0 65535 65535 0 0][vp 1 0 0 52 0 0]Stop by sometime if you feel like it.[n][w][e]
[f 2 1][bup 115 1 65535 65535 0 0][vp 1 0 0 53 0 0][f 4 23 0 115 1 25 25]The name's Mamoru Hayase.[n][w][e]

[msg MSG_026_0_0 [Mamoru Hayase]]
[f 2 1][bup 115 0 65535 65535 0 0][vp 1 0 0 54 0 0]Well... I'll see you around.[n][w][e]

[msg MSG_027_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 101 65535 0 0][vp 1 0 0 55 0 0]Wow, [nl]-chan! Hayase must really see you as a worthy rival![n][w][e]

[msg MSG_028_0_0 [Kazushi Miyamoto]]
[f 2 1][bup 105 2 101 65535 0 0][vp 1 0 0 56 0 0]Hmph![n][w][e]
[f 2 1][bup 105 2 101 65535 0 0][vp 1 0 0 57 0 0]If you see him again, tell him this...[n][w][e]
[f 2 1][bup 105 2 101 65535 0 0][vp 1 0 0 58 0 0][f 4 22 0 105 27 25 20][f 4 21 105 7]Next time, I'll kick your ass![n][w][e]
[f 2 1][bup 105 0 101 65535 0 0][vp 1 0 0 59 0 0][f 4 23 0 105 0 25 25]You got that?[n][w][e]

[msg MSG_029_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 101 65535 0 0][vp 1 0 0 60 0 0]Calm down, Kaz.[n][w][e]
[f 2 1][bup 106 0 101 65535 0 0][vp 1 0 0 61 0 0][f 4 22 0 106 24 25 21]By the way, wasn't that Niimura guy from Third High supposed to be pretty good too? He never showed.[n][w][e]

[msg MSG_030_0_0 [Kazushi Miyamoto]]
[f 2 1][bup 105 0 101 65535 0 0][vp 1 0 0 62 0 0]Yeah, I was talking to some of the guys from his school. Apparently they couldn't get a hold of him.[n][w][e]
[f 2 1][bup 105 0 101 65535 0 0][vp 1 0 0 63 0 0]They even went out to check his house, but he wasn't there.[n][w][e]

[msg MSG_031_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 4 101 65535 0 0][vp 1 0 0 64 0 0]So he's gone missing!? Did he run away from home? Maybe he was afraid of going up against Hayase...[n][w][e]
[f 2 1][bup 106 0 101 65535 0 0][vp 1 0 0 65 0 0][f 4 23 0 106 0 25 25]Or, wait... Do you think it's because of that Apathy Syndrome thing...?[n][w][e]

[msg MSG_032_0_0 [Kazushi Miyamoto]]
[f 2 1][bup 105 3 101 65535 0 0][vp 1 0 0 66 0 0]No idea... Hope he shows up again soon in one piece.[n][w][e]

[msg MSG_033_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 3 101 65535 0 0][vp 1 0 0 67 0 0]Yeah...[n][w][e]
[f 2 1][bup 106 1 101 65535 0 0][vp 1 0 0 68 0 0][f 4 23 0 106 1 25 25][f 4 21 106 11]Anyway, now's not the time to get down in the dumps. Our school did great today, after all![n][w][e]
[f 2 1][bup 106 1 101 65535 0 0][vp 1 0 0 69 0 0][f 4 22 0 106 32 25 20]Good job out there, [nl]-chan![n][w][e]

[msg MSG_034_0_0 [Kazushi Miyamoto]]
[f 2 1][bup 105 1 101 65535 0 0][vp 1 0 0 70 0 0]Alright. Let's get outta here.[n][w][e]

[msg MND_035_0_0]
[f 2 1]I decided to head back with my teammates.[n][w][e]

