[msg MSG_000_0_0 [President Tanaka]]
[f 2 1][bup 113 1 65535 65535 0 0][vp 1 0 0 1 0 0][f 4 23 0 1 1 25 25]My schedule is so terribly packed. I don't usually have time for your average Joe, you know.[n][w][e]
[f 2 1][bup 113 0 65535 65535 0 0][vp 1 0 0 2 0 0][f 4 23 0 1 0 25 25]You should be glad you're such a beautiful girl.[n][w][e]

[msg MSG_000_5_0 [President Tanaka]]
[f 2 1][bup 113 1 65535 65535 0 0][vp 1 0 0 3 0 0][f 4 23 0 1 1 25 25]All right, let's add a new word to our vocabulary today. Repeat after me![n][w][e]
[f 2 1][bup 113 1 65535 65535 0 0][vp 1 0 0 4 0 0][f 4 23 0 1 1 25 25]"Placebo"! The stress is on the middle syllable.[n][w][e]

[sel SEL_001_0_0 top]
[f 2 1]Placebo![e]
[f 2 1]......[e]

[msg MSG_002_0_0 [President Tanaka]]
[f 2 1][bup 113 1 65535 65535 0 0][vp 1 0 0 5 0 0][f 4 23 0 1 1 25 25][f 5 13 16 15 113]Very good! You're feigning interest well![n][w][e]

[msg MSG_003_0_0 [President Tanaka]]
[f 2 1][bup 113 1 65535 65535 0 0][vp 1 0 0 6 0 0][f 4 23 0 1 1 25 25][f 5 13 16 5 113]Yes, I love that smoldering look in your eyes! You'll never succeed in life without skepticism![n][w][e]

[msg MSG_004_0_0 [President Tanaka]]
[f 2 1][bup 113 0 65535 65535 0 0][vp 1 0 0 7 0 0][f 4 23 0 1 0 25 25]A placebo is a "pretend" pill. Basically, it's a medicine to give you peace of mind.[n][w][e]

[msg MSG_004_5_0 [President Tanaka]]
[f 2 1][bup 113 1 65535 65535 0 0][vp 1 0 0 8 0 0][f 4 23 0 1 1 25 25]Imagine this: A supplement to eliminate those unsightly love handles without lifting a finger![n][w][e]
[f 2 1][bup 113 1 65535 65535 0 0][vp 1 0 0 9 0 0][f 4 23 0 1 1 25 25]Or a car navigation system that uses real-time image data to make your commute all the smoother! Or at least make it feel that way.[n][w][e]

[msg MSG_004_7_0 [President Tanaka]]
[f 2 1][bup 113 1 65535 65535 0 0][vp 1 0 0 10 0 0][f 4 23 0 1 1 25 25]These are just a fraction of our unique line of products![n][w][e]

[sel SEL_005_0_0 top]
[f 2 1]Wow.[e]
[f 2 1]Is that legal?[e]

[msg MSG_006_0_0 [President Tanaka]]
[f 2 1][bup 113 0 65535 65535 0 0][vp 1 0 0 11 0 0][f 4 23 0 1 0 25 25][f 5 13 16 5 113]Huh? You're really wowed by those bogus products...?[n][w][e]
[f 2 1][bup 113 3 65535 65535 0 0][vp 1 0 0 12 0 0][f 4 23 0 1 3 25 25]I suppose one could see them as rather spectacular...[n][w][e]

[msg MSG_007_0_0 [President Tanaka]]
[f 2 1][bup 113 1 65535 65535 0 0][vp 1 0 0 13 0 0][f 4 23 0 1 1 25 25][f 5 13 16 5 113]Well, of course I can. In fact, I sell them all the time![n][w][e]

[msg MSG_008_0_0 [President Tanaka]]
[f 2 1][bup 113 0 65535 65535 0 0][vp 1 0 0 14 0 0][f 4 23 0 1 0 25 25]Our business doesn't provide tangible benefits. It provides peace of mind.[n][w][e]

[msg MSG_008_3_0 [President Tanaka]]
[f 2 1][bup 113 0 65535 65535 0 0][vp 1 0 0 15 0 0][f 4 23 0 1 0 25 25]Take emergency supplies, for example. People feel safe just because they have them, don't they?[n][w][e]
[f 2 1][bup 113 1 65535 65535 0 0][vp 1 0 0 16 0 0][f 4 23 0 1 1 25 25]As it turns out, the more money people spend, the better they feel![n][w][e]

[msg MSG_008_5_0 [President Tanaka]]
[f 2 1][bup 113 0 65535 65535 0 0][vp 1 0 0 17 0 0][f 4 23 0 1 0 25 25]Now then! That's it for today's lesson. You can pay me back when you make your first million.[n][w][e]

[msg MND_009_0_0]
[f 2 1]I received somewhat questionable[n]advice from President Tanaka...[n][w][e]
[f 2 1]I understand him a little better now...[n][w][e]

[msg SYS_010_0_0]
[f 2 1]DEV: Unused[n][w][e]

[msg MSG_011_0_0 [President Tanaka]]
[f 2 1][bup 113 0 65535 65535 0 0][vp 1 0 0 18 0 0][f 4 23 0 1 0 25 25]Have you been keeping your promise? You didn't tell anyone, did you?[n][w][e]
[f 2 1][bup 113 2 65535 65535 0 0][vp 1 0 0 19 0 0][f 4 23 0 1 2 25 25]If you go back on your word, you might be surprised to find your profile suddenly on an Internet dating site![n][w][e]

[msg MND_012_0_0]
[f 2 1]It's getting late, so I'll go back to the dorm.[n][w][e]

