[msg MSG_001_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 52 50 0 0][vp 1 0 0 1 0 0]Oh, [nl]-chan. It looks like you're at Iwatodai Station now.[n][w][e]
[f 2 1][bup 6 0 52 50 0 0][vp 1 0 0 2 0 0]It's so late, we were starting to get worried...[n][w][e]
[f 2 1][bup 6 0 52 50 0 0][vp 1 0 0 3 0 0]Um, did you run into any trouble?[n][w][e]

[sel SEL_002_0_0 top]
[f 2 1]My check-up took a while.[e]
[f 2 1]It was nothing.[e]

[msg MSG_003_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 52 50 0 0][vp 1 0 0 4 0 0]Oh! I see. I hope everything's all right...[n][w][e]
[f 2 1][bup 6 0 52 50 0 0][vp 1 0 0 5 0 0]I'll let Kirijo-senpai know. We're in the command room right now.[n][w][e]

[msg MSG_004_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 4 52 50 0 0][vp 1 0 0 6 0 0]O-Oh, I see... Well, as long as you're okay...[n][w][e]
[f 2 1][bup 6 3 52 50 0 0][vp 1 0 0 7 0 0]It's already past curfew though, so that's a little bit of an issue...[n][w][e]
[f 2 1][bup 6 3 52 50 0 0][vp 1 0 0 8 0 0]Actually, um, I'm with Kirijo-senpai right now in the command room.[n][w][e]

[msg MSG_005_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 52 50 0 0][vp 1 0 0 9 0 0]I'll go ahead and navigate you back to the dorm.[n][w][e]
[f 2 1][bup 6 0 52 50 0 0][vp 1 0 0 10 0 0]I'm sure you'll be fine, but considering what happened with Koro-chan, I'd rather play it safe.[n][w][e]

[sel SEL_006_0_0 top]
[f 2 1]Thanks.[e]
[f 2 1]You worry too much.[e]

[msg MSG_007_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 52 50 0 0][vp 0 0 0 11 0 0]......[n][w][e]

[msg MSG_008_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 4 52 50 0 0][vp 0 0 0 12 0 0]...!?[n][w][e]

[msg MSG_009_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 4 52 50 0 0][vp 1 0 0 13 0 0]Wait... I can sense a Shadow![n][w][e]
[f 2 1][bup 6 4 52 50 0 0][vp 1 0 0 14 0 0]And it's really close to you, [nl]-chan! It's over at the Moonlight Bridge![n][w][e]
[f 2 1][bup 6 3 52 50 0 0][vp 1 0 0 15 0 0]It's too dangerous to go alone. You should stay put until everyone else gets there...[n][w][e]

[msg MSG_010_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 4 52 50 0 0][vp 1 0 0 16 0 0]Oh no...! There's another reading near the Shadow! It's a person![n][w][e]

[sel SEL_011_0_0 top]
[f 2 1]I'll buy some time.[e]
[f 2 1]Call the others, quick.[e]

[msg MSG_012_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 4 52 50 0 0][vp 1 0 0 17 0 0]Ah, wait— [nl]-chan!?[n][w][e]

