[msg MSG_000_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 3 0 65535 11050 0 0]There's been a lot of talk lately about that Apathy Syndrome stuff...[n][w][e]

[msg MSG_001_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0]But I'm sure it won't affect those kids one bit. They're so excited about the race, you know?[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0][f 4 23 0 106 1 25 25]They're pretty amazing kids...[n][w][e]

[msg MSG_002_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 3 0 65535 11083 0 0]I'm a little envious... since I don't really have anything I'm passionate about.[n][w][e]

[sel SEL_003_0_0 top]
[f 2 1]Don't give up yet.[e]
[f 2 1]You'll find something.[e]
[f 2 1]You're amazing too.[e]

[msg MSG_004_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 2 65535 65535 0 0][vp 3 0 65535 11069 0 0]Huh? Where'd that come from? I haven't given up. I just haven't found the right thing for me yet, that's all.[n][w][e]
[f 2 1][bup 106 3 65535 65535 0 0][f 4 23 0 106 3 25 25]Sorry... You were just trying to cheer me up, right?[n][w][e]
[f 2 1][bup 106 3 65535 65535 0 0]What is with me today? Maybe I'm just nervous because the tournament is coming up...[n][w][e]

[msg MND_005_0_0]
[f 2 1]Yuko suddenly fell silent.[n][w][e]
[f 2 1]I feel like we didn't get any closer today...[n][w][e]

[msg MSG_006_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 3 0 65535 11081 0 0][f 5 13 12 30 106]Y-You really think so? Thanks. Hearing that from you makes me feel a little better...[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0]I've just been so busy as team manager and as a coach for those kids... Not that I mind, of course.[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0]I don't have much free time these days, but... I dunno, it feels really... fulfilling, you know?[n][w][e]

[msg MND_007_0_0]
[f 2 1]Yuko seems very happy.[n][w][e]
[f 2 1]I feel like we became a lot closer today.[n][w][e]

[msg MSG_008_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 3 0 65535 11030 0 0][f 5 13 12 15 106]Aw, c'mon... You're giving me way too much credit here.[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0]But it does sound pretty cool to say that I'm both a team manager and a coach.[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0]I'll tell you what... If those kids win their big race, then you can sing my praises.[n][w][e]

[msg MND_009_0_0]
[f 2 1]Yuko looks a little embarrassed.[n][w][e]
[f 2 1]I learned a little more about her today.[n][w][e]

[msg MSG_010_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0]Okay, I think I'll pray for a little luck. I just want those kids to show how hard they've practiced.[n][w][e]

[msg MSG_011_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 3 0 65535 11061 0 0]So, uh... if you don't mind, do you wanna visit the shrine with me?[n][w][e]

[msg MND_012_0_0]
[f 2 1]After praying at the shrine with Yuko,[n]I decided to head back to the dorm.[n][w][e]

