[msg TRL_000_0_0 [Using Items and Skills]]
[f 2 1][f 4 8 0]If you get injured while exploring Tartarus, you can use items and skills to restore HP or SP.[n][w][e]

[msg TRL_001_0_0 [Using Items and Skills]]
[f 2 1][f 4 8 3]Open the [f 1 3 112] menu, select [clr 2]ITEM[clr 27], and choose a recovery item, such as [f 4 4 0 37 1 16385] or [f 4 4 0 37 1 16412]. Then choose a party member.[n][w][e]

[msg TRL_002_0_0 [Using Items and Skills]]
[f 2 1][f 4 8 2]Skills work in a similar way. Start by opening the menu, select [clr 2]SKILL[clr 27], and pick a recovery skill, such as [clr 35]Dia[clr 27]. Then choose a party member.[n][w][e]

[msg TRL_003_0_0 [Using Items and Skills]]
[f 2 1][f 4 8 0]It's best to prioritize [nf]'s HP so that she doesn't faint while exploring.[n][w][e]

