[msg MSG_000_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 1 0 0 1 0 0]Why do you have these flowers?[n][w][e]

[sel SEL_001_0_0 top]
[f 2 1]You should give them to her.[e]
[f 2 1]Did I cross a line?[e]

[msg MSG_002_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 65535 65535 0 0][vp 1 0 0 2 0 0]Wha—[n][w][e]
[f 2 1][bup 3 4 65535 65535 0 0][vp 0 0 0 3 0 0]......[n][w][e]

[msg MSG_003_0_0 [Junpei Iori]]
[f 2 1][bup 3 2 65535 65535 0 0][vp 1 0 0 4 0 0]What the heck... What's your deal!?[n][w][e]
[f 2 1][bup 3 2 65535 65535 0 0][vp 1 0 0 5 0 0]Or is this like, a crush thing!? 'Cause this is too much love to handle![n][w][e]

[sel SEL_004_0_0 top]
[f 2 1]Well, I don't hate you.[e]
[f 2 1]Nope, not exactly.[e]
[f 2 1]You're such a kid...[e]

[msg MSG_005_0_0 [Junpei Iori]]
[f 2 1][bup 3 2 65535 65535 0 0][vp 1 0 0 6 0 0]Yeah, yeah, I know! That's why you always have my back...[n][w][e]

[msg MSG_006_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 65535 65535 0 0][vp 1 0 0 7 0 0]Don't bother denyin' it! And if it weren't true, it'd be even weirder![n][w][e]

[msg MSG_007_0_0 [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0][vp 1 0 0 8 0 0]Whoa, uncalled for! Am I not allowed be in a bad mood!?[n][w][e]

[msg MSG_008_0_0 [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0][vp 1 0 0 9 0 0]Ahh, dammit! You really backed me into a corner here.[n][w][e]
[f 2 1][bup 3 3 65535 65535 0 0][vp 1 0 0 10 0 0]I can't just not go now after all this![n][w][e]

[msg MSG_009_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 1 0 0 11 0 0]But... Well, thanks.[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0][vp 1 0 0 12 0 0]Guess I should take a page outta your book and finesse my way in.[n][w][e]

[msg MSG_010_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 1 0 0 13 0 0]'Cept these flowers don't really make me look cool at all.[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0][vp 1 0 0 14 0 0]Maybe I should come burstin' in with a whole bouquet.[n][w][e]

