[msg MSG_000_0_0 [Aigis's Voice]]
[f 2 1][vp 1 0 0 1 0 0]It's me, Aigis.[n][w][e]
[f 2 1][vp 1 0 0 2 0 0]May I please come in?[n][w][e]

[sel SEL_001_0_0 top]
[f 2 1]Just a second.[e]
[f 2 1]I'm busy.[e]

[msg MSG_002_0_0 [Aigis's Voice]]
[f 2 1][vp 1 0 0 3 0 0]But... I...![n][w][e]

[msg MND_003_0_0]
[f 2 1]She sounds upset...[n][w][e]
[f 2 1]Maybe I should just let her in.[n][w][e]

[msg MSG_004_0_0 [Aigis]]
[f 2 1][bup 7 61 2 65535 0 0][vp 1 0 0 4 0 0][f 4 23 0 1 3 25 25]Thank goodness...[n][w][e]
[f 2 1][bup 7 61 2 65535 0 0][vp 1 0 0 5 0 0][f 4 23 0 1 3 25 25]I'm so happy to see you again.[n][w][e]

[msg MSG_005_0_0 [Aigis]]
[f 2 1][bup 7 3 2 65535 0 0][vp 1 0 0 6 0 0][f 4 23 0 1 3 25 25]I'm sorry to show up so suddenly...[n][w][e]
[f 2 1][bup 7 3 2 65535 0 0][vp 1 0 0 7 0 0][f 4 23 0 1 3 25 25]But... I really needed to talk to you.[n][w][e]

[sel SEL_006_0_0 top]
[f 2 1]Me too.[e]
[f 2 1]What's on your mind?[e]

[msg MSG_007_0_0 [Aigis]]
[f 2 1][bup 7 3 2 65535 0 0][vp 1 0 0 8 0 0][f 4 23 0 1 3 25 25]I... remember everything.[n][w][e]
[f 2 1][bup 7 3 2 65535 0 0][vp 1 0 0 9 0 0][f 4 23 0 1 3 25 25]It seems like everyone else has forgotten, but I remember...[n][w][e]
[f 2 1][bup 7 10 2 65535 0 0][vp 1 0 0 10 0 0][f 4 23 0 1 10 25 25]That day, we...[n][w][e]

[sel SEL_008_0_0 top]
[f 2 1]Yeah, we did.[e]
[f 2 1]Don't cry.[e]

[msg MSG_009_0_0 [Aigis]]
[f 2 1][bup 7 10 2 65535 0 0][vp 1 0 0 11 0 0][f 4 23 0 1 10 25 25]I'm sorry...[n][w][e]
[f 2 1][bup 7 3 2 65535 0 0][vp 1 0 0 12 0 0][f 4 23 0 1 3 25 25]It's just that, when I remembered...[n][w][e]
[f 2 1][bup 7 3 2 65535 0 0][vp 1 0 0 13 0 0][f 4 23 0 1 3 25 25]I was afraid you might go somewhere far away, like you did during the last battle...[n][w][e]

[sel SEL_010_0_0 top]
[f 2 1]I'm not going anywhere.[e]
[f 2 1]......[e]

[msg MSG_011_0_0 [Aigis]]
[f 2 1][bup 7 3 2 65535 0 0][vp 1 0 0 14 0 0][f 4 23 0 1 3 25 25]Today is graduation day... isn't it?[n][w][e]
[f 2 1][bup 7 3 2 65535 0 0][vp 1 0 0 15 0 0][f 4 23 0 1 3 25 25]I'm sorry... The ceremony's already begun.[n][w][e]

[msg MSG_012_0_0 [Aigis]]
[f 2 1][bup 7 1 2 65535 0 0][vp 1 0 0 16 0 0][f 4 23 0 1 1 25 25]The weather is so nice outside.[n][w][e]
[f 2 1][bup 7 1 2 65535 0 0][vp 1 0 0 17 0 0][f 4 23 0 1 1 25 25]Do you remember where we all promised to meet?[n][w][e]
[f 2 1][bup 7 1 2 65535 0 0][vp 1 0 0 18 0 0][f 4 23 0 1 1 25 25]Why don't we go ahead and wait for the others?[n][w][e]
[f 2 1][bup 7 1 2 65535 0 0][vp 1 0 0 19 0 0][f 4 23 0 1 1 25 25]We can enjoy the peaceful view of the city.[n][w][e]

