[msg MSG_000_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 1 0 0 1 0 0]'Sup! How's it goin'?[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0][vp 1 0 0 2 0 0][f 4 23 0 3 1 25 25]Wanna stop somewhere on the way home?[n][w][e]

[sel SEL_001_0_0 top]
[f 2 1]...Where?[e]
[f 2 1]I don't know...[e]

[msg MSG_002_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 1 0 0 3 0 0]I dunno, maybe grab a bite to eat?[n][w][e]

[msg MSG_003_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 1 0 0 4 0 0]Oh, come on. It'll be quick.[n][w][e]

[msg MSG_004_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 1 0 0 5 0 0]Thaaat's right, you're new around here.[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0][vp 1 0 0 6 0 0][f 4 23 0 3 1 25 25]No worries, I'll show ya. It's just around the corner from here. Let's go![n][w][e]

