[msg MSG_000_0_0 [Mamoru Hayase]]
[f 2 1][bup 115 0 65535 65535 0 0][vp 3 0 65535 12401 0 0]Hey, [nl]. You remembered me, huh?[n][w][e]
[f 2 1][bup 115 0 65535 65535 0 0]I'm gonna grab a bite to eat. Wanna join me?[n][w][e]

[sel SEL_001_0_0 top]
[f 2 1]You don't stand a chance![e]
[f 2 1]Not this time.[e]

[msg MSG_002_0_0 [Mamoru Hayase]]
[f 2 1][bup 115 1 65535 65535 0 0][vp 3 0 65535 12492 0 0]Let's see who can eat faster... The loser has to run a hundred laps around the city! Ready?[n][w][e]

[msg MND_003_0_0]
[f 2 1]Hayase is full of confidence...[n][w][e]
[f 2 1]I don't have the [f 4 30 2 1 1 0][n]to accept his challenge...[n][w][e]
[f 2 1]If I were at least [f 4 31 2 4 1 0] enough,[n]I'd feel better about my chances.[n][w][e]

[msg MSG_004_0_0 [Mamoru Hayase]]
[f 2 1][bup 115 0 65535 65535 0 0][vp 3 0 65535 12414 0 0]Oh, not feeling up to it? All right, just let me know if you change your mind.[n][w][e]

[msg MSG_005_0_0 [Mamoru Hayase]]
[f 2 1][bup 115 0 65535 65535 0 0][vp 3 0 65535 12413 0 0]All right, see you later, then.[n][w][e]

[msg MSG_006_0_0 [Mamoru Hayase]]
[f 2 1][bup 115 0 65535 65535 0 0][vp 3 0 65535 12402 0 0]Hey, [nl]. You remembered me, huh?[n][w][e]
[f 2 1][bup 115 1 65535 65535 0 0]I'm gonna grab a bite to eat. Wanna join me?[n][w][e]

[msg MSG_007_0_0 [Mamoru Hayase]]
[f 2 1][bup 115 0 65535 65535 0 0][vp 3 0 65535 12402 0 0]Yo, I've been waiting for you, [nl].[n][w][e]
[f 2 1][bup 115 1 65535 65535 0 0]Come on, let's go grab a bite to eat.[n][w][e]

[sel SEL_008_0_0 top]
[f 2 1]Alright.[e]
[f 2 1]Not today.[e]

[msg MSG_009_0_0 [Mamoru Hayase]]
[f 2 1][bup 115 1 65535 65535 0 0][vp 3 0 65535 12466 0 0]Let's see who can eat faster... The loser has to run a hundred laps around the city! Ready?[n][w][e]

[msg MND_010_0_0]
[f 2 1]Hayase is full of confidence...[n][w][e]
[f 2 1]But I can feel the [f 4 30 2 1 1 0][n]welling up within me to face him.[n][w][e]
[f 2 1]I can take him on![n][w][e]

[msg MSG_011_0_0 [Mamoru Hayase]]
[f 2 1][bup 115 3 65535 65535 0 0][vp 3 0 65535 12471 0 0]All right. Later, then.[n][w][e]

[msg MSG_012_0_0 [Mamoru Hayase]]
[f 2 1][bup 115 0 65535 65535 0 0][vp 3 0 65535 12401 0 0]Hey, [nl]. What's up?[n][w][e]
[f 2 1][bup 115 1 65535 65535 0 0]Wanna grab some chow?[n][w][e]

[msg MND_013_0_0]
[f 2 1]Hayase invited me to eat with him.[n][w][e]

[msg MSG_014_0_0 [Mamoru Hayase]]
[f 2 1][bup 115 0 65535 65535 0 0][vp 3 0 65535 12418 0 0]Oh, [nl]...[n][w][e]
[f 2 1][bup 115 3 65535 65535 0 0]I've actually got some shopping to do... You wanna tag along?[n][w][e]
[f 2 1][bup 115 3 65535 65535 0 0]My little bro's been begging me to pick up some new tunes for him, but I don't know much about music... I could really use your help.[n][w][e]

[msg MSG_015_0_0 [Mamoru Hayase]]
[f 2 1][bup 115 3 65535 65535 0 0][vp 3 0 65535 12404 0 0]...Oh, [nl]. I wish I could grab a bite with you, but I can't today.[n][w][e]
[f 2 1][bup 115 3 65535 65535 0 0]I actually need to talk to you. Do you mind joining me?[n][w][e]

[msg MND_016_0_0]
[f 2 1]Should I spend some time[n]after school with Hayase?[n][w][e]

[msg MND_017_0_0]
[f 2 1]Should I spend the day with Hayase?[n][w][e]

[sel SEL_018_0_0 top]
[f 2 1]Spend time with him[e]
[f 2 1]Check Social Link status[e]
[f 2 1]Not now[e]

[msg MSG_019_0_0 [Mamoru Hayase]]
[f 2 1][bup 115 1 65535 65535 0 0][vp 3 0 65535 12472 0 0]Sweet! Let's go![n][w][e]

[msg MSG_020_0_0 [Mamoru Hayase]]
[f 2 1][bup 115 1 65535 65535 0 0][vp 3 0 65535 12466 0 0]Cool, let's go! I'm going hard on the meat today...[n][w][e]

[msg MSG_021_0_0 [Mamoru Hayase]]
[f 2 1][bup 115 0 65535 65535 0 0]...Oh, actually, you go on ahead.[n][w][e]
[f 2 1][bup 115 0 65535 65535 0 0]I'm not done working out yet, but I'll be right there.[n][w][e]

[msg MSG_022_0_0 [Mamoru Hayase]]
[f 2 1][bup 115 1 65535 65535 0 0][vp 3 0 65535 12482 0 0]Oh, great![n][w][e]

[msg MSG_023_0_0 [Mamoru Hayase]]
[f 2 1][bup 115 0 65535 65535 0 0]There's a music store in Paulownia Mall, right? You mind going ahead?[n][w][e]
[f 2 1][bup 115 0 65535 65535 0 0]I'm gonna finish working out first. It shouldn't take long.[n][w][e]

[msg MSG_024_0_0 [Mamoru Hayase]]
[f 2 1][bup 115 3 65535 65535 0 0][vp 3 0 65535 12442 0 0]Thanks, I owe you one...[n][w][e]

[msg MSG_025_0_0 [Mamoru Hayase]]
[f 2 1][bup 115 0 65535 65535 0 0]Let's head somewhere else. Maybe the shrine...[n][w][e]

[msg MSG_026_0_0 [Mamoru Hayase]]
[f 2 1][bup 115 0 65535 65535 0 0][vp 3 0 65535 12413 0 0]All right. Later, man.[n][w][e]

[msg MSG_027_0_0 [Mamoru Hayase]]
[f 2 1][bup 115 0 65535 65535 0 0][vp 3 0 65535 12422 0 0]Oh, you're down? All right, then...[n][w][e]
[f 2 1][bup 115 1 65535 65535 0 0]How 'bout we get some ramen? Since you're already here and all.[n][w][e]

[msg MSG_028_0_0 [Mamoru Hayase]]
[f 2 1][bup 115 1 65535 65535 0 0][vp 3 0 65535 12402 0 0]Hey, how've you been? I'm in top form today.[n][w][e]
[f 2 1][bup 115 0 65535 65535 0 0]I got in thirty laps around this area, but now I'm starving.[n][w][e]

[msg MSG_029_0_0 [Mamoru Hayase]]
[f 2 1][bup 115 1 65535 65535 0 0][vp 3 0 65535 12492 0 0]Sweet! Then let's get some grub.[n][w][e]
[f 2 1][bup 115 1 65535 65535 0 0]I'm in the mood for some meat today![n][w][e]

[msg MSG_030_0_0 [Mamoru Hayase]]
[f 2 1][bup 115 0 65535 65535 0 0][vp 3 0 65535 12401 0 0]Oh, it's you.[n][w][e]
[f 2 1][bup 115 1 65535 65535 0 0]You look hungry. Or maybe it's just me.[n][w][e]

[msg MSG_031_0_0 [Mamoru Hayase]]
[f 2 1][bup 115 1 65535 65535 0 0][vp 3 0 65535 12484 0 0]Great, then let's eat![n][w][e]
[f 2 1][bup 115 0 65535 65535 0 0]Oh, but I'm kinda in a hurry today, so let's just get some takoyaki.[n][w][e]

[msg MSG_032_0_0 [Mamoru Hayase]]
[f 2 1][bup 115 0 65535 65535 0 0][vp 3 0 65535 12408 0 0]Oh, hey there, [nl].[n][w][e]
[f 2 1][bup 115 0 65535 65535 0 0]I was just about to grab a bite. How about you?[n][w][e]

[msg MSG_033_0_0 [Mamoru Hayase]]
[f 2 1][bup 115 0 65535 65535 0 0][vp 3 0 65535 12402 0 0]Oh, [nl].[n][w][e]
[f 2 1][bup 115 1 65535 65535 0 0]I was feeling hungry, but I wanted to wait for you. I was hoping we could eat together.[n][w][e]

[msg MSG_034_0_0 [Mamoru Hayase]]
[f 2 1][bup 115 1 65535 65535 0 0][vp 3 0 65535 12492 0 0]Cool, let's go![n][w][e]
[f 2 1][bup 115 1 65535 65535 0 0]Let's get some takoyaki today. I want some fresh off the stove.[n][w][e]

[msg MSG_035_0_0 [Mamoru Hayase]]
[f 2 1][bup 115 1 65535 65535 0 0][vp 3 0 65535 12402 0 0]Hey, [nl]. Wanna grab something to eat?[n][w][e]
[f 2 1][bup 115 0 65535 65535 0 0]There's something I wanted to talk to you about. Are you free right now?[n][w][e]

[msg MSG_036_0_0 [Mamoru Hayase]]
[f 2 1][bup 115 1 65535 65535 0 0][vp 3 0 65535 12466 0 0]Great, then let's get some ramen! Today, I'm gonna go with the special, extra-large![n][w][e]

[msg MSG_037_0_0 [Mamoru Hayase]]
[f 2 1][bup 115 1 65535 65535 0 0][vp 3 0 65535 12408 0 0]Hey, [nl]![n][w][e]
[f 2 1][bup 115 0 65535 65535 0 0]I've been waiting for you. Were you gonna go eat something just now?[n][w][e]

[msg MSG_038_0_0 [Mamoru Hayase]]
[f 2 1][bup 115 0 65535 65535 0 0][vp 3 0 65535 12485 0 0]Cool. Now, what should we get...?[n][w][e]
[f 2 1][bup 115 1 65535 65535 0 0]Can't go wrong with ramen. I don't think I'll ever get tired of it.[n][w][e]

[msg MSG_039_0_0 [Mamoru Hayase]]
[f 2 1][bup 115 0 65535 65535 0 0][vp 3 0 65535 12413 0 0]All right. Maybe next time.[n][w][e]

[msg MSG_040_0_0 [Mamoru Hayase]]
[f 2 1][bup 115 0 65535 65535 0 0][vp 3 0 65535 12413 0 0]Oh, you're busy? Well, come see me any time, then.[n][w][e]

[msg MSG_041_0_0 [Mamoru Hayase]]
[f 2 1][bup 115 0 65535 65535 0 0][vp 3 0 65535 12414 0 0]Oh, you already ate? Invite me next time, all right?[n][w][e]

[msg MSG_042_0_0 [Mamoru Hayase]]
[f 2 1][bup 115 0 65535 65535 0 0][vp 3 0 65535 12488 0 0]I see. Maybe next time, then.[n][w][e]

[msg MSG_043_0_0 [Mamoru Hayase]]
[f 2 1][bup 115 3 65535 65535 0 0][vp 3 0 65535 12471 0 0]Oh, I see... That's too bad.[n][w][e]

[msg MSG_044_0_0 [Mamoru Hayase]]
[f 2 1][bup 115 3 65535 65535 0 0][vp 3 0 65535 12471 0 0]Gotcha... That's fine. Let's try for another time.[n][w][e]

[msg MSG_045_0_0 [Mamoru Hayase]]
[f 2 1][bup 115 3 65535 65535 0 0][vp 3 0 65535 12488 0 0]Guess we'll just have to try for next time.[n][w][e]

[msg MSG_046_0_0 [Mamoru Hayase]]
[f 2 1][bup 115 0 65535 65535 0 0][vp 3 0 65535 12413 0 0]All right. Maybe next time, then.[n][w][e]

[msg MSG_047_0_0 [Mamoru Hayase]]
[f 2 1][bup 115 3 65535 65535 0 0][vp 3 0 65535 12488 0 0]I see...[n][w][e]
[f 2 1][bup 115 0 65535 65535 0 0]Next time, then. It's a promise.[n][w][e]

[msg MND_GENERAL_EVENTPLAY]
[f 2 1]Message issued by the script. [n][f 1 5 0]Comm Event Replay.[n][w][e]

[msg MND_GENERAL_PERSPNA]
[f 2 1]I feel as if we can grow closer thanks to the[n][f 2 4 2] Persona, [clr 35][f 2 4 5][clr 27]...[n][w][e]

[msg MND_GENERALSELECTMSG_MAX]
[f 2 1]I feel an unbreakable bond[n]with [f 2 4 0]...[n][w][e]

[msg MND_GENERALMSG_BS_MAX]
[f 2 1]I feel an unbreakable bond[n]with the elderly couple...[n][w][e]

[msg MND_GENERALSELECTMSG_RAN]
[f 2 1]I feel like I might grow closer[n]to [f 2 4 0] soon...[n][w][e]

[msg MND_GENERALMSG_BS_RANKUP]
[f 2 1]I feel like I might grow closer[n]to the elderly couple soon...[n][w][e]

[msg MND_GENERALSELECTMSG_NOR]
[f 2 1]I don't think our bond will grow[n]any stronger even if I spend[n]more time with [f 2 4 0]...[n][w][e]

[msg MND_GENERALMSG_BS_NORMAL [Mamoru Hayase]]
[f 2 1]I don't think our bond will grow[n]any stronger even if I spend[n]more time with them...[n][w][e]

[msg MND_GENERALSELECTMSG_MAX_2]
[f 2 1]It doesn't seem that our relationship[n]can get any closer than it is...[n][w][e]
[f 2 1]Should I still spend time with them...?[n][w][e]

[msg MND_GENERAL_MSG_SOLO_AS]
[f 2 1]Should I spend some time after[n]school with [f 2 4 0]?[n][w][e]

[msg MND_GENERAL_MSG_SOLO_DT]
[f 2 1]Should I spend the day[n]with [f 2 4 0]?[n][w][e]

[msg MND__GENERAL_MSG_NET]
[f 2 1]Should I spend time online playing[n]the MMORPG with [f 2 4 0]...?[n][w][e]

[msg MND_GENERAL_MSG_SOLO_NT]
[f 2 1]Should I spend the evening[n]with [f 2 4 0]?[n][w][e]

[sel SEL_GENERALSELECTMSG_SOL top]
[f 2 1]Spend time with [f 2 4 0][e]
[f 2 1]Check Social Link[e]
[f 2 1]Never mind[e]

[msg MND_GENERAL_MSG_MULTIPLE]
[f 2 1]Should I spend some time after[n]school with the [f 2 4 1]?[n][w][e]

[msg MND_GENERAL_MSG_FASHION_]
[f 2 1]Should I spend some time after[n]school at the fashion club?[n][w][e]

[msg MND_GENERAL_MSG_BOOKSTOR]
[f 2 1]Should I spend the day at the bookstore?[n][w][e]

[msg MND_GENERAL_MSG_BOOKSTOR_2]
[f 2 1]Should I spend some time[n]after school at the bookstore?[n][w][e]

[msg MND_GENERAL_MSG_MULTIPLE_2]
[f 2 1]Should I spend the night[n]with [f 2 4 1]?[n][w][e]

[sel SEL_GENERALSELECTMSG_MUL top]
[f 2 1]Spend time w/ [f 2 4 1][e]
[f 2 1]Check Social Link[e]
[f 2 1]Never mind[e]

[sel SEL_GENERALSELECTMSG_FCL top]
[f 2 1]Go to the fashion club[e]
[f 2 1]Check Social Link[e]
[f 2 1]Never mind[e]

[sel SEL_GENERALSELECTMSG_BS top]
[f 2 1]Enter the bookstore[e]
[f 2 1]Check Social Link[e]
[f 2 1]Never mind[e]

[msg MSG_GENERAL_EXAMREWARD_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4029 0 0]Ah, [nl].[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]I saw your exam results. Good work.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Here, this is from the chairman.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4108 0 0]It's a reward for effectively balancing schoolwork as well as our... ahem, "extracurricular activities."[n][w][e]

[msg MND_GENERAL_EXAMREWARD_0]
[f 2 1]DEV: UNUSED LABEL[n][w][e]

[msg MND_GENERAL_EXAMREWARD_0_2]
[f 2 1]Since I placed at the top in the exams,[n]I also got this [f 4 4 1 37 1 3].[n][w][e]

[msg MSG_GENERAL_EXAMREWARD_0_2 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4029 0 0]Ah, [nl].[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]I saw your exam results. Good work.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Here, this is from the chairman.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4108 0 0]It's a reward for effectively balancing schoolwork as well as our... ahem, "extracurricular activities."[n][w][e]

[msg MSG_GENERAL_EXAMREWARD_0_3 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4077 0 0]Oh, right. There's something else...[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]I saw your exam results. Good work.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Here, this is from the chairman.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4131 0 0]It's a reward for effectively balancing schoolwork as well as our... ahem, "extracurricular activities."[n][w][e]

[msg MND_GENERAL_EXAMREWARD_0_3]
[f 2 1]Since I placed at the top in the exams,[n]I also got this [f 4 4 1 37 1 3].[n][w][e]

[msg MSG_GENERAL_EXAMREWARD_0_4 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4029 0 0]Ah, [nl].[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]I saw your exam results. Good work.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Here, this is from the chairman.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4108 0 0]It's a reward for effectively balancing schoolwork as well as our... ahem, "extracurricular activities."[n][w][e]

[msg MND_GENERAL_EXAMREWARD_0_4]
[f 2 1]DEV: UNUSED LABEL[n][w][e]

[msg MSG_GENERAL_EXAMREWARD_0_5 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4029 0 0]Ah, [nl].[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]I saw your exam results... Good work.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]It's admirable how you continue to excel in school while fighting arduous battle after battle.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0]I got you a gift to acknowledge all your hard work. Here, take it.[n][w][e]

[msg MND_GENERAL_EXAMREWARD_0_5]
[f 2 1]未使用ラベルです。[n][w][e]

[msg MSG_GENERAL_EXAMREWARD_0_6 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 6 65535 0 0][vp 3 0 65535 4029 0 0]Ah, [nl].[n][w][e]
[f 2 1][bup 5 0 6 65535 0 0]I saw your exam results. Good work.[n][w][e]
[f 2 1][bup 5 0 6 65535 0 0]It's admirable how you continue to excel in school while fighting arduous battle after battle.[n][w][e]
[f 2 1][bup 5 0 6 65535 0 0]I got you a gift to acknowledge all your hard work. Here, take it.[n][w][e]

[msg MND_GENERAL_EXAMREWARD_1]
[f 2 1]Since I placed at the top in the exams,[n]I also got this [f 4 4 1 37 1 3].[n][w][e]

[msg MSG_GENERAL_EXAMREWARD_1 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4029 0 0]Ah, [nl].[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]I saw your exam results. Good work.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]It's admirable how you continue to excel in school while fighting arduous battle after battle.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4108 0 0]I got you a gift to acknowledge all your hard work. Here, take it.[n][w][e]

[msg MND_GENERAL_EXAMREWARD_1_2]
[f 2 1]DEV: UNUSED LABEL[n][w][e]

[msg MND_GENERAL_EXAMREWARD_1_3]
[f 2 1]Since I placed at the top in the exams,[n]I also got this [f 4 4 1 37 1 3].[n][w][e]

