[msg MSG_000_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 1 65535 65535 0 0][vp 3 0 65535 11494 0 0]I had never been to a place like this before. I didn't know it would be so much fun![n][w][e]

[msg MSG_001_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 3 65535 65535 0 0]I don't think I was very good at the racing games, though.[n][w][e]
[f 2 1][bup 109 3 65535 65535 0 0]I kept trying to stay under the speed limit instead of going fast...[n][w][e]

[msg MSG_002_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 3 65535 65535 0 0][vp 3 0 65535 11450 0 0]I'm probably not very good at driving in general... I have a hard time reacting to things quickly...[n][w][e]
[f 2 1][bup 109 0 65535 65535 0 0][f 4 23 0 109 0 25 25]What about you, [nl]-chan? Are you planning to get a driver's license?[n][w][e]

[sel SEL_003_0_0 top]
[f 2 1]I am.[e]
[f 2 1]Probably not.[e]
[f 2 1]It's a secret.[e]

[msg MSG_004_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 1 65535 65535 0 0][vp 3 0 65535 11479 0 0][f 5 13 9 30 109]Really?[n][w][e]
[f 2 1][bup 109 1 65535 65535 1 0]Um... Then I'd like to... go on a drive with you someday...[n][w][e]

[msg MND_005_0_0]
[f 2 1]Chihiro is blushing.[n][w][e]
[f 2 1]I feel like we became a lot closer today.[n][w][e]

[msg MSG_006_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 0 65535 65535 0 0][vp 3 0 65535 11472 0 0][f 5 13 9 15 109]Oh, okay...[n][w][e]
[f 2 1][bup 109 0 65535 65535 0 0]I was just... kind of curious what you'd look like behind the wheel...[n][w][e]
[f 2 1][bup 109 4 65535 65535 1 0][f 4 23 0 109 4 25 25]O-Oh, but I'm not saying you should definitely get a license! If you don't want to, that's okay too![n][w][e]

[msg MND_007_0_0]
[f 2 1]Chihiro seems to be having fun.[n][w][e]
[f 2 1]I learned a little more about her today.[n][w][e]

[msg MSG_008_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 3 65535 65535 0 0][vp 3 0 65535 11452 0 0]Um, "a secret"...?[n][w][e]
[f 2 1][bup 109 3 65535 65535 0 0]Is... there a reason you won't tell me? I kind of feel like that's the sort of thing I should know...[n][w][e]
[f 2 1][bup 109 3 65535 65535 0 0]Since we're... dating, and all...[n][w][e]

[msg MND_009_0_0]
[f 2 1]Chihiro seems disappointed.[n][w][e]
[f 2 1]I feel like we didn't get any closer today...[n][w][e]

[sel SEL_010_0_0 top]
[f 2 1]I am.[e]
[f 2 1]Probably not.[e]
[f 2 1]It's a secret.[e]

[msg MSG_011_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 1 65535 65535 0 0][vp 3 0 65535 11451 0 0][f 5 13 9 30 109]Well, when you do, maybe we could go on a small trip.[n][w][e]
[f 2 1][bup 109 1 65535 65535 0 0]Somewhere far away, with everyone on the student council...[n][w][e]
[f 2 1][bup 109 1 65535 65535 0 0]I've never really done a trip like that before, so I think it'd be fun to try.[n][w][e]

[msg MND_012_0_0]
[f 2 1]Chihiro seems like she's having fun.[n][w][e]
[f 2 1]I feel like we became a lot closer today.[n][w][e]

[msg MSG_013_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 0 65535 65535 0 0][vp 3 0 65535 11451 0 0][f 5 13 9 15 109]Yeah, I guess you don't really need a car around here, since you can just take the trains.[n][w][e]
[f 2 1][bup 109 0 65535 65535 0 0]You'd probably be fine without a driver's license.[n][w][e]

[msg MND_014_0_0]
[f 2 1]Chihiro is smiling.[n][w][e]
[f 2 1]I learned a little more about her today.[n][w][e]

[msg MSG_015_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 0 65535 65535 0 0][vp 3 0 65535 11454 0 0]Um, "a secret"?[n][w][e]
[f 2 1][bup 109 0 65535 65535 0 0]Were you planning on surprising everyone when you get your license...?[n][w][e]
[f 2 1][bup 109 0 65535 65535 0 0]Um, never mind. I shouldn't pry...[n][w][e]

[msg MND_016_0_0]
[f 2 1]Chihiro is making herself smile.[n][w][e]
[f 2 1]I feel like we didn't get any closer today...[n][w][e]

[msg MSG_017_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 0 65535 65535 0 0][vp 3 0 65535 11483 0 0]Hm, I think playing those arcade games made me thirsty... Do you mind getting something to drink?[n][w][e]

[msg MND_018_0_0]
[f 2 1]The two of us hung out at the café for[n]a while before I returned to the dorm.[n][w][e]

