[msg MSG_000_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5067 0 0]Oh, [nl]-chan. Are you on your way home?[n][w][e]

[sel SEL_001_0_0 top]
[f 2 1]Let's walk home together.[e]
[f 2 1]Yep. See you.[e]

[msg MSG_002_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0][vp 3 0 65535 5056 0 0]Oh, I'm sorry... I was about to do some research.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]I'm actually learning how to cook, but I'm still just experimenting...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]I don't think I can make anything edible at this point, and I don't want to waste your time...[n][w][e]

[msg MND_003_0_0]
[f 2 1]If I volunteer to help her, I might regret it...[n][w][e]
[f 2 1]I don't have the [f 4 30 2 1 1 0] to risk it...[n][w][e]
[f 2 1]My [f 4 30 2 1 1 0] would[n]need to be [f 4 31 2 6 1 0] first.[n][w][e]

[msg MSG_004_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5022 0 0]Okay. Be careful on your way home.[n][w][e]

[msg MSG_005_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 3 0 65535 5076 0 0]Oh, [nl]-chan... Are you busy?[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Also, if you happen to be a little hungry...[n][w][e]

[sel SEL_006_0_0 top]
[f 2 1]I'm free.[e]
[f 2 1]Sorry, I'm busy.[e]

[msg MSG_007_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 3 0 65535 5131 0 0]Oh, good! In that case, would you do me a favor?[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0]I was hoping you could taste the lunch I made.[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0]To be honest, I don't have very much confidence in my cooking...[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0]But today, I think it turned out okay![n][w][e]

[msg MSG_008_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0][vp 3 0 65535 5089 0 0]O-Oh, um...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]...N-Never mind. Sorry. Be careful on your way home.[n][w][e]

[msg MND_009_0_0]
[f 2 1]I've got a bad feeling about this...[n][w][e]
[f 2 1]But I have enough [f 4 30 2 1 1 0] to try it.[n][w][e]

[msg MSG_010_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0]So... will you taste it?[n][w][e]

[sel SEL_011_0_0 top]
[f 2 1]Let's try it...[e]
[f 2 1]I'll pass.[e]

[msg MSG_012_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 3 0 65535 5020 0 0]Oh, thank you! Okay, please come with me.[n][w][e]

[msg MSG_013_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0][vp 3 0 65535 5094 0 0]Oh, I see...[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0]I guess no one would want to eat something that doesn't taste very good...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]It's okay, don't worry about it.[n][w][e]

[msg MSG_014_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5067 0 0]Oh, [nl]-chan. Are you heading home?[n][w][e]

[msg MND_015_0_0]
[f 2 1]It seems like Fuuka wants[n]to walk home with me.[n][w][e]

[msg MSG_016_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0]Unused[n][w][e]

[msg MND_017_0_0]
[f 2 1]Should I spend some time[n]after school with Fuuka?[n][w][e]

[sel SEL_018_0_0 top]
[f 2 1]Spend time with her[e]
[f 2 1]Check Social Link status[e]
[f 2 1]Not now[e]

[msg MSG_019_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 3 0 65535 5025 0 0]Okay.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Where should we go?[n][w][e]

[msg MSG_020_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0]Unused[n][w][e]

[msg MSG_021_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 1 0]Unused[n][w][e]

[msg MSG_022_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 3 0 65535 5063 0 0]Oh, um...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Th-Then...[n][w][e]

[msg MSG_023_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 1 0]W-W-Would you...[n][w][e]
[f 2 1][bup 6 2 65535 65535 1 0]Would you like to come to my room!?[n][w][e]
[f 2 1][bup 6 0 65535 65535 1 0][f 4 25 6]......[n][w][e]
[f 2 1][bup 6 1 65535 65535 1 0]...I-I mean, if you want to. Is that okay?[n][w][e]

[msg MSG_024_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5098 0 0]U-Um...[n][w][e]
[f 2 1][bup 6 2 65535 65535 0 0]Okay... Sure.[n][w][e]
[f 2 1][bup 6 1 65535 65535 1 0]W-Would you... like to come to my room?[n][w][e]

[msg MSG_025_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0][vp 3 0 65535 5022 0 0]Oh, I see...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Okay, maybe some other time then.[n][w][e]

[msg MSG_026_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 3 0 65535 5067 0 0]Oh, [nl]-chan.[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0]I was just thinking... I hope we can be in the same class next year.[n][w][e]
[f 2 1][bup 6 11 65535 65535 0 0]I know it sounds silly, but I'd really like to see you every day.[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0]And I don't think my feelings will ever change...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][f 4 25 6]......[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0]...[nl]-chan.[n][w][e]
[f 2 1][bup 6 1 65535 65535 1 0][vp 3 0 65535 5131 0 0]I will always be by your side.[n][w][e]
[f 2 1][bup 6 0 65535 65535 1 0][f 4 25 6]......[n][w][e]

[msg MND_027_0_0]
[f 2 1]I feel an unbreakable bond[n]with Fuuka...[n][w][e]

[msg MSG_028_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0]Unused[n][w][e]

[msg MSG_029_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0]Unused[n][w][e]

[msg MSG_030_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0]Unused[n][w][e]

[msg MSG_031_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0]Unused[n][w][e]

[msg MSG_032_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0]Unused[n][w][e]

[msg MSG_033_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 11 65535 65535 0 0]Unused[n][w][e]

[msg MSG_034_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 3 0 65535 5079 0 0]Oh, [nl]-chan.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]I was just thinking, I really hope we can be in the same class next year.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]We're going to be third-years, so we'll probably be busy studying for college entrance exams and whatnot.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]But I think even that would be fun with all my friends.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5131 0 0]Plus, I might be able to help everyone else with their studies, too.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]So if you ever need help with anything, [nl]-chan, you can always count on me.[n][w][e]

[msg MND_035_0_0]
[f 2 1]I feel an unbreakable bond[n]with Fuuka...[n][w][e]

[msg MSG_036_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0]By the way, are you on your way home now? Did you have any plans?[n][w][e]

[msg MSG_036_5_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0]Say, are you busy right now?[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]By the way, if you happen to be a little hungry...[n][w][e]

[msg MSG_037_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0]Unused[n][w][e]

[msg MSG_038_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0]Unused[n][w][e]

[msg MSG_039_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 3 0 65535 5010 0 0]Oh, [nl]-chan. Looks like we're finally done with exams.[n][w][e]

[msg MSG_040_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0]We made it to the end. Now we can get back to our club activities.[n][w][e]

[msg MSG_041_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0]We made it to the end. Hopefully that relieves some stress at school for a while.[n][w][e]

[msg MSG_042_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0]We made it to the end. I hope we both did well.[n][w][e]

[msg MSG_043_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5001 0 0]Ah, [nl]-chan. Are you about to head home?[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0]Um... I could use your help again, if you have the time...[n][w][e]

[msg MSG_043_5_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0]Oh, right! Are you about to head home?[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0]Um... I could use your help again, if you have the time...[n][w][e]

[msg MSG_044_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 3 0 65535 5063 0 0]Really? Then, let's head to the courtyard again.[n][w][e]

[msg MSG_045_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5067 0 0]Oh, [nl]-chan.[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0]I'm just about to head home. How about you?[n][w][e]

[msg MSG_045_5_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0]Oh, that's right.[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0]I'm just about to head home. How about you?[n][w][e]

[msg MSG_046_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 3 0 65535 5025 0 0]Okay, then let's go.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Now that I think about it... even though we live in the same dorm, we've never gone back together before.[n][w][e]

[msg MSG_047_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5010 0 0]Hello, [nl]-chan.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]If you're leaving now, would you like to go shopping with me?[n][w][e]

[msg MSG_047_5_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0]Oh, by the way...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]If you're leaving now, would you like to go shopping with me?[n][w][e]

[msg MSG_048_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 3 0 65535 5039 0 0]Thank you! Let's head to Paulownia Mall.[n][w][e]

[msg MSG_049_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5002 0 0]Oh, [nl]-chan. Do you have any plans today?[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0]I have a favor to ask, if you have the time...[n][w][e]

[msg MSG_049_5_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0]Oh, did you have any plans today?[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0]I have a favor to ask, if you have the time...[n][w][e]

[msg MSG_050_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 3 0 65535 5043 0 0]Thank you. Let's see then...[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0]How about we go to the roof? The view up there is so nice...[n][w][e]

[msg MSG_051_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5077 0 0][nl]-chan...[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0]Are you free right now? There's something I want to talk to you about...[n][w][e]

[msg MSG_051_5_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0]Um... Are you free right now? There's something I want to talk to you about...[n][w][e]

[msg MSG_052_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 3 0 65535 5042 0 0]...Thank you.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Let's go back up to the roof. I'm sorry, this won't take long.[n][w][e]

[msg MSG_053_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5061 0 0]Oh, [nl]-chan. Are you busy today?[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0]I'm heading to the used bookstore right now. Do you want to join me?[n][w][e]

[msg MSG_053_5_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0]Say, are you busy today?[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0]I'm heading to the used bookstore right now. Do you want to join me?[n][w][e]

[msg MSG_054_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 3 0 65535 5043 0 0]Oh, great! Thank you.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]I've been looking for a good cookbook for a while now. Do you think they'll have any?[n][w][e]

[msg MSG_055_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5010 0 0]Hello, [nl]-chan. Are you heading home?[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0]...If you aren't too busy, do you think we could talk on the roof?[n][w][e]

[msg MSG_055_5_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0]Hi, are you heading home?[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0]...If you aren't too busy, do you think we could talk on the roof?[n][w][e]

[msg MSG_056_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 1 0][vp 3 0 65535 5025 0 0]Thank you! I hope no one's sitting at our usual spot...[n][w][e]

[msg MSG_057_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5079 0 0]Oh, [nl]-chan...[n][w][e]
[f 2 1][bup 6 0 65535 65535 1 0][f 4 25 6]......[n][w][e]
[f 2 1][bup 6 3 65535 65535 1 0][vp 3 0 65535 5077 0 0]Um... I was hoping we could talk.[n][w][e]

[msg MSG_057_5_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0]Also...[n][w][e]
[f 2 1][bup 6 0 65535 65535 1 0][f 4 25 6]......[n][w][e]
[f 2 1][bup 6 3 65535 65535 1 0][vp 3 0 65535 5077 0 0]Um... I was hoping we could talk.[n][w][e]

[msg MSG_058_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 3 0 65535 5028 0 0]Thank you...[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0]I'd like to go to the roof, then. Shall we?[n][w][e]

[msg MSG_059_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 4 65535 65535 0 0][vp 3 0 65535 5067 0 0]Oh, [nl]-chan...[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0]U-Um, are you heading home for the day? Did you have any plans?[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0]If not, maybe we could go together...[n][w][e]

[msg MSG_059_5_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0]U-Um, are you heading home for the day? Did you have plans?[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0]If not, maybe we could go together...[n][w][e]

[msg MSG_060_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 3 0 65535 5002 0 0]Oh, are you heading home?[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Would you happen to be free today? I was hoping you could join me for something.[n][w][e]

[msg MSG_060_5_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0]Oh, are you heading home?[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Would you happen to be free today? I was hoping you could join me for something.[n][w][e]

[msg MSG_061_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 3 0 65535 5039 0 0]Thanks. I would've had a hard time going by myself...[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0]It's the ramen shop at the strip mall. Do you eat there a lot?[n][w][e]

[msg MSG_062_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5063 0 0][nl]-chan, are you busy today?[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]If not... do you think we could chat on the roof for a bit?[n][w][e]

[msg MSG_062_5_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][nl]-chan, are you busy today?[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]If not... do you think we could chat on the roof for a bit?[n][w][e]

[msg MSG_063_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 3 0 65535 5025 0 0]Thanks. I actually really enjoy when we get to talk up there.[n][w][e]

[msg MSG_064_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 3 0 65535 5002 0 0]Oh, [nl]-chan![n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]I was thinking of returning to the dorm to cook...[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0]Would you like to join me? I'll be starting from scratch today.[n][w][e]

[msg MSG_064_5_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0]Oh, that's right.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]I was thinking of going back to the dorm right now to cook...[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0]Would you like to join me? I'll be starting from scratch today.[n][w][e]

[msg MSG_065_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 3 0 65535 5132 0 0]Great! Hehe, this is going to be so much fun.[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0]I've already bought everything we need, so why don't we head back and get started?[n][w][e]

[msg MSG_066_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0][vp 3 0 65535 5094 0 0]Oh, I see...[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0]Okay, maybe next time then.[n][w][e]

[msg MSG_067_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0][vp 3 0 65535 5094 0 0]Oh...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]All right, I'll see you later then.[n][w][e]

[msg MSG_068_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0][vp 3 0 65535 5056 0 0]Oh, I'm sorry. Did you have plans?[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]I guess it'll have to wait until next time.[n][w][e]

[msg MSG_069_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0][vp 3 0 65535 5094 0 0]Oh, I see...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Okay, maybe some other time then.[n][w][e]

[msg MSG_070_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5053 0 0]Oh, sorry. Are you busy?[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Okay, maybe next time then. I'll see you back at the dorm.[n][w][e]

[msg MSG_071_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0][vp 3 0 65535 5094 0 0]Oh, I see...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Okay, maybe next time, if you're free.[n][w][e]

[msg MSG_072_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5053 0 0]Oh, okay. Sorry about that.[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0]Maybe some other time then, when you're available.[n][w][e]

[msg MSG_073_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5025 0 0]Oh, that's too bad.[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0]Maybe some other day.[n][w][e]

[msg MSG_074_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0][vp 3 0 65535 5094 0 0]Oh, I see...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Okay, some other time then, when you're free.[n][w][e]

[msg MSG_075_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5067 0 0]Oh, did you already have plans?[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Maybe next time then. I think I might head home now.[n][w][e]

[msg MSG_076_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0][vp 3 0 65535 5094 0 0]O-Oh... I should've guessed...[n][w][e]
[f 2 1][bup 6 4 65535 65535 1 0]Um... It's nothing! I'll see you later![n][w][e]

[msg MSG_077_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5067 0 0]Oh, sorry, I shouldn't have imposed. It's okay if you're busy.[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0]Maybe some other time then. I'll see you later.[n][w][e]

[msg MSG_078_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 3 0 65535 5024 0 0]Okay, I'll see you back at the dorm. I'll be back before it gets too late.[n][w][e]

[msg MND_GENERAL_EVENTPLAY]
[f 2 1]Message issued by the script. [n][f 1 5 0]Comm Event Replay.[n][w][e]

[msg MND_GENERAL_PERSPNA]
[f 2 1]I feel as if we can grow closer thanks to the[n][f 2 4 2] Persona, [clr 35][f 2 4 5][clr 27]...[n][w][e]

[msg MND_GENERALSELECTMSG_MAX]
[f 2 1]I feel an unbreakable bond[n]with [f 2 4 0]...[n][w][e]

[msg MND_GENERALMSG_BS_MAX]
[f 2 1]I feel an unbreakable bond[n]with the elderly couple...[n][w][e]

[msg MND_GENERALSELECTMSG_RAN]
[f 2 1]I feel like I might grow closer[n]to [f 2 4 0] soon...[n][w][e]

[msg MND_GENERALMSG_BS_RANKUP]
[f 2 1]I feel like I might grow closer[n]to the elderly couple soon...[n][w][e]

[msg MND_GENERALSELECTMSG_NOR]
[f 2 1]I don't think our bond will grow[n]any stronger even if I spend[n]more time with [f 2 4 0]...[n][w][e]

[msg MND_GENERALMSG_BS_NORMAL [Fuuka Yamagishi]]
[f 2 1]I don't think our bond will grow[n]any stronger even if I spend[n]more time with them...[n][w][e]

[msg MND_GENERALSELECTMSG_MAX_2]
[f 2 1]It doesn't seem that our relationship[n]can get any closer than it is...[n][w][e]
[f 2 1]Should I still spend time with them...?[n][w][e]

[msg MND_GENERAL_MSG_SOLO_AS]
[f 2 1]Should I spend some time after[n]school with [f 2 4 0]?[n][w][e]

[msg MND_GENERAL_MSG_SOLO_DT]
[f 2 1]Should I spend the day[n]with [f 2 4 0]?[n][w][e]

[msg MND__GENERAL_MSG_NET]
[f 2 1]Should I spend time online playing[n]the MMORPG with [f 2 4 0]...?[n][w][e]

[msg MND_GENERAL_MSG_SOLO_NT]
[f 2 1]Should I spend the evening[n]with [f 2 4 0]?[n][w][e]

[sel SEL_GENERALSELECTMSG_SOL top]
[f 2 1]Spend time with [f 2 4 0][e]
[f 2 1]Check Social Link[e]
[f 2 1]Never mind[e]

[msg MND_GENERAL_MSG_MULTIPLE]
[f 2 1]Should I spend some time after[n]school with the [f 2 4 1]?[n][w][e]

[msg MND_GENERAL_MSG_FASHION_]
[f 2 1]Should I spend some time after[n]school at the fashion club?[n][w][e]

[msg MND_GENERAL_MSG_BOOKSTOR]
[f 2 1]Should I spend the day at the bookstore?[n][w][e]

[msg MND_GENERAL_MSG_BOOKSTOR_2]
[f 2 1]Should I spend some time[n]after school at the bookstore?[n][w][e]

[msg MND_GENERAL_MSG_MULTIPLE_2]
[f 2 1]Should I spend the night[n]with [f 2 4 1]?[n][w][e]

[sel SEL_GENERALSELECTMSG_MUL top]
[f 2 1]Spend time w/ [f 2 4 1][e]
[f 2 1]Check Social Link[e]
[f 2 1]Never mind[e]

[sel SEL_GENERALSELECTMSG_FCL top]
[f 2 1]Go to the fashion club[e]
[f 2 1]Check Social Link[e]
[f 2 1]Never mind[e]

[sel SEL_GENERALSELECTMSG_BS top]
[f 2 1]Enter the bookstore[e]
[f 2 1]Check Social Link[e]
[f 2 1]Never mind[e]

[msg MSG_GENERAL_EXAMREWARD_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4029 0 0]Ah, [nl].[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]I saw your exam results. Good work.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Here, this is from the chairman.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4108 0 0]It's a reward for effectively balancing schoolwork as well as our... ahem, "extracurricular activities."[n][w][e]

[msg MND_GENERAL_EXAMREWARD_0]
[f 2 1]DEV: UNUSED LABEL[n][w][e]

[msg MND_GENERAL_EXAMREWARD_0_2]
[f 2 1]Since I placed at the top in the exams,[n]I also got this [f 4 4 1 37 1 3].[n][w][e]

[msg MSG_GENERAL_EXAMREWARD_0_2 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4029 0 0]Ah, [nl].[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]I saw your exam results. Good work.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Here, this is from the chairman.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4108 0 0]It's a reward for effectively balancing schoolwork as well as our... ahem, "extracurricular activities."[n][w][e]

[msg MSG_GENERAL_EXAMREWARD_0_3 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4077 0 0]Oh, right. There's something else...[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]I saw your exam results. Good work.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Here, this is from the chairman.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4131 0 0]It's a reward for effectively balancing schoolwork as well as our... ahem, "extracurricular activities."[n][w][e]

[msg MND_GENERAL_EXAMREWARD_0_3]
[f 2 1]Since I placed at the top in the exams,[n]I also got this [f 4 4 1 37 1 3].[n][w][e]

[msg MSG_GENERAL_EXAMREWARD_0_4 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4029 0 0]Ah, [nl].[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]I saw your exam results. Good work.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Here, this is from the chairman.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4108 0 0]It's a reward for effectively balancing schoolwork as well as our... ahem, "extracurricular activities."[n][w][e]

[msg MND_GENERAL_EXAMREWARD_0_4]
[f 2 1]DEV: UNUSED LABEL[n][w][e]

[msg MSG_GENERAL_EXAMREWARD_0_5 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4029 0 0]Ah, [nl].[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]I saw your exam results... Good work.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]It's admirable how you continue to excel in school while fighting arduous battle after battle.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0]I got you a gift to acknowledge all your hard work. Here, take it.[n][w][e]

[msg MND_GENERAL_EXAMREWARD_0_5]
[f 2 1]未使用ラベルです。[n][w][e]

[msg MSG_GENERAL_EXAMREWARD_0_6 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 6 65535 0 0][vp 3 0 65535 4029 0 0]Ah, [nl].[n][w][e]
[f 2 1][bup 5 0 6 65535 0 0]I saw your exam results. Good work.[n][w][e]
[f 2 1][bup 5 0 6 65535 0 0]It's admirable how you continue to excel in school while fighting arduous battle after battle.[n][w][e]
[f 2 1][bup 5 0 6 65535 0 0]I got you a gift to acknowledge all your hard work. Here, take it.[n][w][e]

[msg MND_GENERAL_EXAMREWARD_1]
[f 2 1]Since I placed at the top in the exams,[n]I also got this [f 4 4 1 37 1 3].[n][w][e]

[msg MSG_GENERAL_EXAMREWARD_1 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4029 0 0]Ah, [nl].[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]I saw your exam results. Good work.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]It's admirable how you continue to excel in school while fighting arduous battle after battle.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4108 0 0]I got you a gift to acknowledge all your hard work. Here, take it.[n][w][e]

[msg MND_GENERAL_EXAMREWARD_1_2]
[f 2 1]DEV: UNUSED LABEL[n][w][e]

[msg MND_GENERAL_EXAMREWARD_1_3]
[f 2 1]Since I placed at the top in the exams,[n]I also got this [f 4 4 1 37 1 3].[n][w][e]

