[msg MSG_SENDER_NAME]
[f 2 1]Bebe[n][w][e]

[msg MSG_001_0_0]
[f 2 1]Konnichiwa.[n][w][e]

[msg MSG_002_0_0]
[f 2 1]Its très difficile to type. Sorry if I make any mistakes.[n][f 1 5 0]After school I will wait in the hallway.[n][w][e]

[msg MSG_003_0_0]
[f 2 1][nf]-sama[n][w][e]

[msg MSG_004_0_0]
[f 2 1]Did I spell your name correctly?[n][f 1 5 0]Lets sew together. I am in the hallway :D[n][w][e]

[msg MSG_005_0_0]
[f 2 1]It's bebe.[n][w][e]

[msg MSG_006_0_0]
[f 2 1][nf]-sama come to the home ec room please. I need to tell you something :([n][f 1 5 0]I will wait in the hallway.[n][w][e]

[msg MSG_007_0_0]
[f 2 1]:'([n][w][e]

[msg MSG_008_0_0]
[f 2 1]Thank you a million.[n][f 1 5 0]I want to sew. [nf]-sama I am waiting for you in the home ec room.[n][w][e]

[msg MSG_009_0_0]
[f 2 1]Greetings.[n][w][e]

[msg MSG_010_0_0]
[f 2 1]Is it weird to type that? ↑[n][f 1 5 0]I am happy that [nf]-sama sews too :-))[n][w][e]

[msg MSG_011_0_0]
[f 2 1]SUPER COOL!!![n][w][e]

[msg MSG_012_0_0]
[f 2 1]I have a very good idea. I want to tell you so come see me please.[n][w][e]

[msg MSG_013_0_0]
[f 2 1]I would like your help.[n][w][e]

[msg MSG_014_0_0]
[f 2 1]I want uncle to see kimono. I want to sew with [nf]-sama. We will do well. :-))[n][w][e]

[msg MSG_015_0_0]
[f 2 1]Almost.[n][w][e]

[msg MSG_016_0_0]
[f 2 1]Thank you for your help [nf]-sama. Can we make an exceptionnel kimono together?[n][f 1 5 0]I will go to the home ec room today too.[n][w][e]

[msg MSG_017_0_0]
[f 2 1][nf]-sama.[n][w][e]

[msg MSG_018_0_0]
[f 2 1]I will finish it today. I want you to see it. I would like you to come.[n][w][e]

[msg MSG_019_0_0]
[f 2 1]Sewing machine.[n][w][e]

[msg MSG_020_0_0]
[f 2 1]Class is over. Sewing is fun.[n][w][e]

[msg MSG_021_0_0]
[f 2 1]I must sew.[n][w][e]

[msg MSG_022_0_0]
[f 2 1]I will come get you for club activities.[n][w][e]

[msg MSG_023_0_0]
[f 2 1][nf]-sama :)[n][w][e]

[msg MSG_024_0_0]
[f 2 1]It is a good day for sewing.[n][w][e]

[msg MSG_025_0_0]
[f 2 1]Are you free?[n][w][e]

[msg MSG_026_0_0]
[f 2 1]Hello.[n][f 1 5 0]We have today off. I want to go out, [nf]-sama.[n][w][e]

[msg MSG_027_0_0]
[f 2 1]Go to the ciné?[n][w][e]

[msg MSG_028_0_0]
[f 2 1]There is a French movie today. It is good for learning :D[n][f 1 5 0]Do you want to go to the cinéma? Lets watch together. I already have tickets :)[n][w][e]

