[sel SEL_000_0_0 top]
[f 2 1]Enter[e]
[f 2 1]Don't enter[e]

[msg MND_001_0_0 [DEV: Internal MES]]
[f 2 1]It's the women's restroom. Should I go in...?[n][w][e]

[msg MSG_002_0_0 [Yukari Takeba]]
[f 2 1][bup 2 3 51 65535 0 0][vp 3 0 65535 1102 0 0]Wait, really? At a time like this?[n][w][e]
[f 2 1][bup 2 2 51 65535 0 0]Just try to be quick, will you?[n][w][e]

[msg MSG_003_0_0 [Yukari Takeba]]
[f 2 1][bup 2 2 51 65535 0 0][vp 3 0 65535 1090 0 0]Seriously? Again!? You're not doing this on purpose, are you?[n][w][e]
[f 2 1][bup 2 3 51 65535 0 0]Fine... But hurry up, okay?[n][w][e]

