[msg MND_000_0_0]
[f 2 1]Ryoji has returned, as promised...[n][w][e]
[f 2 1]It's time for me to make my decision.[n][w][e]

[msg MSG_001_0_0 [Ryoji Mochizuki]]
[f 2 1][bup 221 3 65535 65535 0 0][vp 1 0 0 1 0 0]Hey, it's been a while.[n][w][e]

[msg MSG_002_0_0 [Ryoji Mochizuki]]
[f 2 1][bup 221 3 65535 65535 0 0][vp 1 0 0 2 0 0]Midnight's just around the corner.[n][w][e]
[f 2 1][bup 221 10 65535 65535 0 0][vp 1 0 0 3 0 0][f 4 23 0 221 10 25 25]When it hits, I'll lose this form, and I won't be me anymore.[n][w][e]
[f 2 1][bup 221 3 65535 65535 0 0][vp 1 0 0 4 0 0][f 4 23 0 221 3 25 25]So, have you made a decision?[n][w][e]

[msg MSG_003_0_0 [Ryoji Mochizuki]]
[f 2 1][bup 221 3 65535 65535 0 0][vp 1 0 0 5 0 0]Then I'll be waiting in her room until midnight.[n][w][e]
[f 2 1][bup 221 3 65535 65535 0 0][vp 1 0 0 6 0 0]Come see me when you have your answer.[n][w][e]

[msg MSG_004_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 6 65535 0 0][vp 1 0 0 7 0 0]Ryoji-kun...[n][w][e]

[msg MSG_005_0_0 [Ryoji Mochizuki]]
[f 2 1][bup 221 3 65535 65535 0 0][vp 1 0 0 8 0 0]Oh, and one more thing.[n][w][e]
[f 2 1][bup 221 0 65535 65535 0 0][vp 1 0 0 9 0 0][f 4 23 0 221 0 25 25]Don't let the fact that you have to kill me influence your decision.[n][w][e]
[f 2 1][bup 221 0 65535 65535 0 0][vp 1 0 0 10 0 0]Like I said, I'm gonna disappear either way.[n][w][e]
[f 2 1][bup 221 0 65535 65535 0 0][vp 1 0 0 11 0 0]I don't have any hangups about dying.[n][w][e]
[f 2 1][bup 221 0 65535 65535 0 0][vp 1 0 0 12 0 0]So you don't need to worry about me.[n][w][e]

[msg MSG_006_0_0 [Junpei Iori]]
[f 2 1][bup 3 3 6 65535 0 0][vp 0 0 0 13 0 0]......[n][w][e]

[msg MSG_007_0_0 [Ryoji Mochizuki]]
[f 2 1][bup 221 3 65535 65535 0 0][vp 1 0 0 14 0 0]All right, I'll be waiting.[n][w][e]

[msg MSG_008_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 6 65535 0 0][vp 1 0 0 15 0 0]Have you made your decision?[n][w][e]

[sel SEL_009_0_0 top]
[f 2 1]I have.[e]
[f 2 1]......[e]

[msg MSG_010_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 6 65535 0 0][vp 1 0 0 16 0 0]...I see.[n][w][e]

[msg MSG_011_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 6 65535 0 0][vp 1 0 0 17 0 0]It's all right, you don't need to say anything.[n][w][e]

[msg MSG_012_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 6 65535 0 0][vp 1 0 0 18 0 0]Have the rest of you decided?[n][w][e]

[msg MSG_013_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 6 65535 0 0][vp 1 0 0 19 0 0]No need to ask me.[n][w][e]

[msg MSG_014_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 6 65535 0 0][vp 1 0 0 20 0 0]You know how I feel.[n][w][e]

[msg MSG_015_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 6 65535 0 0][vp 1 0 0 21 0 0]I wouldn't be here if I wasn't on board.[n][w][e]

[msg MSG_016_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 6 65535 0 0][vp 1 0 0 22 0 0]I'm with the rest of you.[n][w][e]

[msg MSG_017_0_0 [Ken Amada]]
[f 2 1][bup 8 0 6 65535 0 0][vp 1 0 0 23 0 0]I'm on board, too.[n][w][e]

[msg MSG_018_0_0 [Koromaru]]
[f 2 1][bup 9 1 65535 65535 0 0][vp 1 0 0 24 0 0]Woof![n][w][e]

[msg MSG_019_0_0 [Aigis]]
[f 2 1][bup 7 1 6 65535 0 0][vp 1 0 0 25 0 0]I've made my decision as well.[n][w][e]

[msg MSG_020_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 6 65535 0 0][vp 1 0 0 26 0 0]Sounds like we're all on the same page.[n][w][e]

[msg MSG_021_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 6 65535 0 0][vp 1 0 0 27 0 0]Better let him know, then.[n][w][e]
[f 2 1][bup 4 0 6 65535 0 0][vp 1 0 0 28 0 0]Okay?[n][w][e]

