[msg MSG_MITSURU_FIRST_TRY [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4008 0 0]The entrance to the labyrinth is at the top of the stairs. Whenever you feel ready to start, lead the way.[n][w][e]

[msg MSG_MITSURU_ENT_HELP [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 1 10089 0 0]As we explore Tartarus, this will be our temporary base of operations.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 1 10090 0 0]I'm counting on you to take charge during the operation.[n][w][e]

[msg MSG_MITSURU_HELP_WARNING [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 1 10091 0 0]It looks like it's been a while since we've come here...[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 1 10092 0 0]It's important we sharpen our combat abilities here so we're prepared for sudden Shadow attacks like the one earlier.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 1 10093 0 0]It never hurts to train beforehand. Try to keep that in mind.[n][w][e]

[msg MSG_MITSURU_2ndWARNING [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 1 10094 0 0]I'll briefly go over Tartarus once more.[n][w][e]

[msg MSG_THEURGIA_00 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 1 21001 0 0]Ooh, [nl]-chan, that new sword looks pretty cool.[n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 1 21002 0 0]This bow I got is really light and looks pretty easy to use. I can't wait to see it in action![n][w][e]

[msg MSG_THEURGIA_01 [Akihiko Sanada]]
[f 2 1][bup 4 1 65535 65535 0 0][vp 1 0 1 21003 0 0]So the chairman got us all new weapons too, huh? Guess we should be thanking him.[n][w][e]

[msg MSG_THEURGIA_02 [Yukari Takeba]]
[f 2 1][bup 2 6 65535 65535 0 0][vp 1 0 1 21004 0 0]He barely explained anything though. Sometimes I can't tell if he's actually helpful or not.[n][w][e]

[msg MSG_THEURGIA_03 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 1 21005 0 0]All of this has been custom-made for us. You can tell because of the SEES mark engraved on everything.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 1 21006 0 0]As always, you're in command, [nl]. And make sure to check the equipment before we get started.[n][w][e]

[msg MSG_MITSURU_GREET [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4115 0 0]Now that we have Yamagishi, I'll be available for the front lines as well.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]However, I think we should continue sending out four people at most on excursions.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]That would make for a most cohesive team, and having reserve members for unexpected situations is definitely wise.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Regarding the actual party members included, I'll leave that to you.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Once you've formed a party with the members here, you can move out when you feel ready.[n][w][e]

[msg MSG_FUKA_GREET [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5006 0 0]I'll do my best to help you all. Hope it goes well![n][w][e]

[msg MSG_FUKA_GREET_02 [Fuuka Yamagishi]]
[f 2 1][bup 6 4 65535 65535 0 0]Um, I don't exactly know what I'm doing, but I'll try my best![n][w][e]

[msg MSG_MITURU_WARP_NOTICE [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 1 10105 0 0]I knew it![n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 1 10106 0 0]Those devices are teleporters—they're portals that are all connected to one another.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 1 10107 0 0]Once activated, you should be able to travel between any of the other devices.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 1 10108 0 0]Be sure to activate any you come across. They'll be quite useful during future expeditions.[n][w][e]

[msg MSG_FUKA_WARP_NOTICE [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5018 0 0]Welcome back! It really is just as I had thought...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Those devices are teleporters—they're portals that are all connected to one another.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Once activated, you should be able to travel between any of the other devices.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Please activate any that you come across. They'll be very useful during future expeditions.[n][w][e]

[msg MSG_FUKA_MONAD_TUTO [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5062 0 0]About that door—it appears to lead to a side path in Tartarus.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]In short, if you're heading for the top, taking that path would be considered a detour, of sorts.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]However, it seems like you'll be able to obtain something down that path that should prove helpful to exploring...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Depending on how prepared you are, it may be a good idea to try these doors.[n][w][e]

[msg MSG_MITSURU_FIND_PERSON [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0]未使用[n][w][e]

[msg MSG_FUKA_FIND_PERSON [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0]Welcome back! So, it looks like you were able to rescue a missing person...[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0]We can have them stay here for now—we'll see them off properly when the time comes.[n][w][e]

[msg MSG_MITSURU_FIND_CAT [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0]未使用[n][w][e]

[msg MSG_FUKA_FIND_CAT [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 3 0 65535 5018 0 0]Welcome back! I'm so relieved you were able to save that kitty![n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0]It can stay here for now—we'll send it off safely when the time comes.[n][w][e]

[msg MSG_MISSING_CAT_INFO_SIN [Elizabeth]]
[f 2 1][bup 202 0 65535 65535 0 0][vp 3 0 65535 13216 0 0][nf], may I have a moment of your time?[n][w][e]
[f 2 1][bup 202 0 65535 65535 0 0]Tartarus appears to have a special little guest today...[n][w][e]
[f 2 1][bup 202 0 65535 65535 0 0]And between its jaws, it clenched a fragment that emitted a curious, blue light.[n][w][e]
[f 2 1][bup 202 0 65535 65535 0 0]Should your curiosity get the best of you, perhaps it'd be best to pay this guest a visit.[n][w][e]
[f 2 1][bup 202 0 65535 65535 0 0]I believe it will likely be on floor [f 2 4 0]. Well, off you go...[n][w][e]

[msg MSG_MISSING_CAT_INFO_DOU [Elizabeth]]
[f 2 1][bup 202 0 65535 65535 0 0][vp 3 0 65535 13216 0 0][nf], may I have a moment of your time?[n][w][e]
[f 2 1][bup 202 0 65535 65535 0 0]Tartarus appears to have some special little guests today...[n][w][e]
[f 2 1][bup 202 0 65535 65535 0 0]What a rare treat for you... Should your curiosity get the best of you, perhaps it'd be best to pay this guest a visit.[n][w][e]
[f 2 1][bup 202 0 65535 65535 0 0]Perhaps more of those curious, glowing fragments are in your future![n][w][e]
[f 2 1][bup 202 0 65535 65535 0 0]I believe they will likely be on floors [f 2 4 0] and [f 2 4 1]. Well, off you go...[n][w][e]

[msg MSG_COMBINE_INFO_00 [Elizabeth]]
[f 2 1][bup 202 0 65535 65535 0 0][vp 3 0 65535 13221 0 0]Oh? My my, what have we here?[n][w][e]
[f 2 1][bup 202 0 65535 65535 0 0]Currently, you appear to possess a great number of Personas.[n][w][e]
[f 2 1][bup 202 0 65535 65535 0 0]Quite impressive, I must say. However...[n][w][e]
[f 2 1][bup 202 0 65535 65535 0 0]Perhaps in your current state, you are able to utilize even more powerful Personas?[n][w][e]
[f 2 1][bup 202 0 65535 65535 0 0]Should you feel so inclined, please make your way to the Velvet Room.[n][w][e]

[msg MSG_SEPARATELY_MITSURU_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4017 0 0]Ah, you're back. Good—everyone's safety is more important than anything else.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]I have the items that our other squadmates found during their recon...[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Allow me to hand them over.[n][w][e]

[msg MSG_SEPARATELY_MITSURU_0_2 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4075 0 0]So, the timing for when you return is up to you, our leader, but...[n][w][e]
[f 2 1][bup 5 6 65535 65535 0 0]It's poor form to leave your comrades behind. You owe them a proper apology later.[n][w][e]

[msg MSG_SEPARATELY_FUKA_00 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 3 0 65535 5018 0 0]Welcome back! I'm glad you're safe, everyone.[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0]I'm holding the items that the others found during their efforts...[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0]I'll hand them over to you now.[n][w][e]

[msg MSG_SEPARATELY_FUKA_01 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0][vp 3 0 65535 5077 0 0]Um, I know it probably doesn't bother them, but when people are scouting...[n][w][e]
[f 2 1][bup 6 6 65535 65535 0 0]It's not good to just come back without saying anything to them... I would feel lonely if it happened to me.[n][w][e]

[msg MSG_SEPARATELY_FUKA_10 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0]Ah, if you're returning to exploring, before I forget...[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0]Let me hand over what the others found during their efforts.[n][w][e]

[msg MND_CARD_INFO_01]
[f 2 1]The [f 4 4 1 0 1 0] is reacting...[n][w][e]

[msg PFM_CARD_INFO_PRIESTESS]
[f 2 1]The High Priestess Major Arcana card[n]has been added to Shuffle Time.[n][w][e]

[msg PFM_CARD_INFO_HERMIT]
[f 2 1]The Hermit Major Arcana card[n]has been added to Shuffle Time.[n][w][e]

[msg PFM_CARD_INFO_HANGEDMAN]
[f 2 1]The Hanged Man Major Arcana card[n]has been added to Shuffle Time.[n][w][e]

[msg MND_CARD_INFO_02]
[f 2 1]The [f 4 4 1 0 1 0] and[n][f 4 4 1 0 1 1] are reacting...[n][w][e]

[msg PFM_CARD_INFO_EMPRESS_EM]
[f 2 1]The Empress and Emperor Major Arcana[n]cards have been added to Shuffle Time.[n][w][e]

[msg PFM_CARD_INFO_HIERO_LOVE]
[f 2 1]The Hierophant and Lovers Major Arcana[n]cards have been added to Shuffle Time.[n][w][e]

[msg PFM_CARD_INFO_CHARI_JUST]
[f 2 1]The Chariot and Justice Major Arcana[n]cards have been added to Shuffle Time.[n][w][e]

[msg PFM_CARD_INFO_FORT_STREN]
[f 2 1]The Fortune and Strength Major Arcana[n]cards have been added to Shuffle Time.[n][w][e]

[msg MSG_ArcanaInfo01 [Elizabeth]]
[f 2 1][bup 202 0 65535 65535 0 0][vp 3 0 65535 13202 0 0]I've been waiting for you. May I have but a moment of your time?[n][w][e]

[msg MND_ArcanaInfo02]
[f 2 1]The Lovers card is glowing...[n][w][e]

[msg SYS_ArcanaInfo]
[f 2 1]Upon acquiring the Lovers, the Social Link bonus during fusion increases.[n][w][e]

[msg SYS_TutoAfter_TheurgiaGa]
[f 2 1][clr 2]Theurgy[clr 27] has been added to Tutorials.[n][w][e]

[msg SYS_TutoAfter_PartyMembe]
[f 2 1][clr 2]Changing Party Formation[clr 27] has been added to Tutorials.[n][w][e]

[msg MSG_MISSING_NPC_NOT_EXIS [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 3 0 65535 5113 0 0]I tried another search, but I'm still not picking up anyone else's presence inside.[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0]It seems we've rescued everybody who accidently ended up in Tartarus.[n][w][e]

[msg MSG_CLOCK_FLOOR_AFTER01 [Fuuka Yamagishi]]
[f 2 1][bup 6 4 65535 65535 0 0][vp 3 0 65535 5003 0 0]Is everyone all right?[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]For a second, I lost you all... But then it was like you just teleported here.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]What an odd place... What do you think could be the deal with that clock?[n][w][e]

[sel SEL_CLOCK_FLOOR_AFTER top]
[f 2 1]Seems like we could use it...[e]
[f 2 1]No clue.[e]

[msg MSG_CLOCK_FLOOR_AFTER02 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0]If it seems like it'll be helpful, it'd be smart of us to make use of it.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]It doesn't seem dangerous... Maybe it actually has a positive effect on everyone?[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]If the entrance opens up again, let's try it![n][w][e]

[msg MSG_088_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 3 0 65535 5018 0 0]Welcome back! How'd you enjoy the clock this time?[n][w][e]

[msg MSG_059_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0]Hey, just a sec...[n][w][e]

[msg MSG_059_5_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0]Oh, me too![n][w][e]

[msg MSG_059_7_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0]I'm actually feeling pretty good right now. If it's all right with you, I'd like to join you.[n][w][e]

[msg MSG_060_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0]Hey, [nf]...[n][w][e]

[msg MSG_060_5_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0]Me too, me too![n][w][e]

[msg MSG_060_7_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0]I feel like I've got tons of energy right now! Wanna put me in the party?[n][w][e]

[msg MSG_061_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0]Hold on a second...[n][w][e]

[msg MSG_061_5_0 [Akihiko Sanada]]
[f 2 1][bup 4 1 65535 65535 0 0]Ah, same here.[n][w][e]

[msg MSG_061_7_0 [Akihiko Sanada]]
[f 2 1][bup 4 1 65535 65535 0 0]I've got a really good mental image of how I should be moving. Let me join you and you won't regret it.[n][w][e]

[msg MSG_062_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0]Excuse me, sorry...[n][w][e]

[msg MSG_062_5_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 65535 0 0]Oh, I actually feel similarly myself.[n][w][e]

[msg MSG_062_7_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 65535 0 0]I have a feeling that I'll do especially well in there right now. Could you please include me in your party?[n][w][e]

[msg MSG_063_0_0 [Fuuka Yamagishi]]
[f 2 1]未使用[n][w][e]

[msg MSG_063_5_0 [Fuuka Yamagishi]]
[f 2 1]未使用[n][w][e]

[msg MSG_063_7_0 [Fuuka Yamagishi]]
[f 2 1]未使用[n][w][e]

[msg MSG_064_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0]So, this may be sudden, but...[n][w][e]

[msg MSG_064_5_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0]This applies to myself as well.[n][w][e]

[msg MSG_064_7_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0]I am unusually energized. Please include me on the front lines.[n][w][e]

[msg MSG_065_0_0 [Ken Amada]]
[f 2 1][bup 8 3 65535 65535 0 0][nl]-san, I'd like to ask...[n][w][e]

[msg MSG_065_5_0 [Ken Amada]]
[f 2 1][bup 8 4 65535 65535 0 0]Oh, me too![n][w][e]

[msg MSG_065_7_0 [Ken Amada]]
[f 2 1][bup 8 2 65535 65535 0 0]Could you put me on the front lines? I feel like I can become a lot stronger right now.[n][w][e]

[msg MSG_066_0_0 [Koromaru]]
[f 2 1][bup 9 0 65535 65535 0 0]Arf![n][w][e]

[msg MSG_066_5_0 [Koromaru]]
[f 2 1][bup 9 0 65535 65535 0 0]*whine*[n][w][e]

[msg MSG_066_7_0 [Koromaru]]
[f 2 1][bup 9 0 65535 65535 0 0]Arf arf! Arf![n][w][e]

[msg MSG_067_0_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0]Hey, hold on a sec.[n][w][e]

[msg MSG_067_5_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0]Sorry to butt in, but, same.[n][w][e]

[msg MSG_067_7_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0]Could you include me? I mean, I'm feelin' pretty good right now.[n][w][e]

[msg MSG_064_7_0_H [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0]I have a feeling that my power is going to amplify. Could you include me in the front line?[n][w][e]

[msg MSG_KORO_THEURGIA_00 [Fuuka Yamagishi]]
[f 2 1][bup 6 4 65535 65535 0 0][vp 3 0 65535 5006 0 0]Ah, that's right—there's something I wanted to tell you...[n][w][e]

[msg MSG_KORO_THEURGIA_01 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0]It seems Koro-chan actually has two theurgies![n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]The chairman learned that from researching his potential.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]We're not totally sure why that's the case, but...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]It's certainly nice to have him on our side.[n][w][e]

[msg MSG_KORO_THEURGIA_02 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0]I suppose just keep that in mind whenever forming a party. That's all![n][w][e]

[msg MND_Tuto_MissingNPC_0]
[f 2 1]Come to think of it...[n][w][e]
[f 2 1]Elizabeth had mentioned "guests"[n]wandering into Tartarus...[n][w][e]

