[msg MSG_SENDER_NAME]
[f 2 1]Fuuka Yamagishi[n][w][e]

[msg MSG_001_0_0]
[f 2 1]Hello[n][w][e]

[msg MSG_002_0_0]
[f 2 1]Sorry about what happened the other day. But I've been practicing my cooking, and I want you to see how much I've improved! [f 1 3 157][n][f 1 5 0]I'm a little nervous about going into your classroom, so I'll wait for you in the hallway on the second floor.[n][w][e]

[msg MSG_003_0_0]
[f 2 1]If you don't mind...[n][w][e]

[msg MSG_004_0_0]
[f 2 1]Would you like to go home together?[n][f 1 5 0]I'll be waiting in the second-floor hallway. I'd love to chat with you on the way back. [f 1 3 156][n][w][e]

[msg MSG_005_0_0]
[f 2 1]I have a favor to ask...[n][w][e]

[msg MSG_006_0_0]
[f 2 1]Could you come with me to Paulownia Mall on the way home? Going there alone makes me feel a little nervous. [f 1 3 138][n][w][e]

[msg MSG_007_0_0]
[f 2 1]Do you have time?[n][w][e]

[msg MSG_008_0_0]
[f 2 1]I've been thinking a lot about what we talked about last time.[n][f 1 5 0]If you have some time, I'd like for you to see my progress.[n][f 1 5 0]Hope you're feeling hungry! [f 1 3 157][n][w][e]

[msg MSG_009_0_0]
[f 2 1](No Subject)[n][w][e]

[msg MSG_010_0_0]
[f 2 1]Sorry, I know this is kind of sudden, but I'd like to ask for your help with something. Can we meet up?[n][w][e]

[msg MSG_011_0_0]
[f 2 1]After school[n][w][e]

[msg MSG_012_0_0]
[f 2 1]Have you been to the used bookstore at the strip mall? I've been wanting to check it out, and it'd make me really happy if you came along, too. [f 1 3 157][n][f 1 5 0]You can find me in the second-floor hallway if you'd like to join me.[n][w][e]

[msg MSG_013_0_0]
[f 2 1]At the rooftop[n][w][e]

[msg MSG_014_0_0]
[f 2 1]Do you have some time today? I kind of want to talk to you.[n][f 1 5 0]It's nothing particularly important, though.[n][f 1 5 0]I'm just really grateful that you're always there for me. [f 1 3 157][n][w][e]

[msg MSG_015_0_0]
[f 2 1](No Subject)[n][w][e]

[msg MSG_016_0_0]
[f 2 1][nl]-chan, do you have time after school?[n][f 1 5 0]I'd like to talk with you alone. I think I'm finally ready to tell you how I feel.[n][w][e]

[msg MSG_017_0_0]
[f 2 1]Let's go home together?[n][w][e]

[msg MSG_018_0_0]
[f 2 1]Shall we? [f 1 3 157][n][f 1 5 0]I was actually thinking of taking a break from practicing cooking today.[n][w][e]

[msg MSG_013_5_0]
[f 2 1]For reference![n][w][e]

[msg MSG_014_5_0]
[f 2 1]I have a favor to ask you.[n][f 1 5 0]Do you have some time after school today? There's somewhere I'd like to go. [f 1 3 157][n][w][e]

[msg MSG_019_0_0]
[f 2 1]Urgent![n][w][e]

[msg MSG_020_0_0]
[f 2 1]There's something I really want to tell you right now.[n][f 1 5 0]Oh, but it's nothing that serious. I just wanted to chat, like how we always do. [f 1 3 137][n][w][e]

[msg MSG_021_0_0]
[f 2 1]Are you hungry?[n][w][e]

[msg MSG_022_0_0]
[f 2 1]Remember what we talked about the other day? I'm thinking of doing that today.[n][f 1 5 0]Are you okay with that? [f 1 3 157][n][w][e]

[msg MSG_023_0_0]
[f 2 1]Hello[n][w][e]

[msg MSG_024_0_0]
[f 2 1]If you don't mind, could we meet after school?[n][w][e]

[msg MSG_025_0_0]
[f 2 1]Let's chat[n][w][e]

[msg MSG_026_0_0]
[f 2 1]If you're not too busy, can we talk for a bit? [f 1 3 157][n][w][e]

[msg MSG_027_0_0]
[f 2 1]Hello[n][w][e]

[msg MSG_028_0_0]
[f 2 1]What are you up to, [nl]-chan? Do you have a minute? [f 1 3 137][n][w][e]

[msg MSG_029_0_0]
[f 2 1]If you don't mind...[n][w][e]

[msg MSG_030_0_0]
[f 2 1]Sorry, I know this is kind of out of the blue. [f 1 3 138][n][f 1 5 0]But if you don't have any plans, shall we go somewhere together?[n][w][e]

[msg MSG_031_0_0]
[f 2 1]Movie! [f 1 3 151][n][w][e]

[msg MSG_032_0_0]
[f 2 1]There's a movie I'm interested in. It's a sci-fi movie that takes place in a realistic setting...[n][f 1 5 0]It seems to be a fan favorite, so maybe you'll learn what makes it so charming![n][f 1 5 0]If you're interested, would you like to watch it together? [f 1 3 137][n][w][e]

[msg MSG_033_0_0]
[f 2 1]Summer festival [f 1 3 140][n][w][e]

[msg MSG_034_0_0]
[f 2 1]There's going to be a festival at Naganaki Shrine tonight. I'd love to check it out. Would you like to come with me?[n][w][e]

[msg MSG_035_0_0]
[f 2 1]Christmas [f 1 3 154][n][w][e]

[msg MSG_036_0_0]
[f 2 1]I've been thinking... I'd really love to spend Christmas together with you. [f 1 3 137][n][f 1 5 0]How about you? I'll be waiting for your reply.[n][w][e]

[msg MSG_037_0_0]
[f 2 1]About Amada-kun[n][w][e]

[msg MSG_038_0_0]
[f 2 1]I'm a little concerned about Amada-kun.[n][f 1 5 0]Ever since second semester started, he's been looking kind of down.[n][f 1 5 0]He won't tell me anything, so I was hoping you'd drop by his room and check in on him. Could you?[n][w][e]

[msg MSG_039_0_0]
[f 2 1]About Amada-kun[n][w][e]

[msg MSG_040_0_0]
[f 2 1]How was Amada-kun?[n][f 1 5 0]Maybe I'm just overthinking it, but it wouldn't hurt to talk to him.[n][f 1 5 0]Could you drop by his room and check in on him?[n][w][e]

[msg MSG_041_0_0]
[f 2 1]I'm on the 2nd floor.[n][w][e]

[msg MSG_042_0_0]
[f 2 1]I'll be at the couch on the second floor today. If you'd like to go to Tartarus, please look for me there.[n][w][e]

[msg MSG_043_0_0]
[f 2 1]I'm on the 3rd floor.[n][w][e]

[msg MSG_044_0_0]
[f 2 1]I'll be on the third floor today. If you'd like to go to Tartarus, please look for me there.[n][w][e]

[msg MSG_045_0_0]
[f 2 1]I'm in the command room.[n][w][e]

[msg MSG_046_0_0]
[f 2 1]I'll be inside the command room today. If you'd like to go to Tartarus, please look for me there.[n][w][e]

[msg MSG_047_0_0]
[f 2 1]About Koro-chan[n][w][e]

[msg MSG_048_0_0]
[f 2 1]When Koro-chan sits outside the dorm, he kind of looks like a guardian angel.[n][f 1 5 0]I wonder if he gets cold though...[n][f 1 5 0]I'm a little worried he'll get sick, so please check on him whenever you see him at the front entrance, okay? [f 1 3 157][n][w][e]

