[msg MSG_000_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 1 0 0]Let's see... I'd like to stop by the drug store before we head home. Do you mind? It'll just be a little longer.[n][w][e]

[msg MSG_001_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 2 0 0]Hang on, I've got a phone call.[n][w][e]

[msg MSG_001_5_0 [Yukari Takeba]]
[f 2 1][bup 2 10 65535 65535 0 0][vp 1 0 0 3 0 0]Oh...[n][w][e]

[msg MSG_002_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 4 0 0]...Hello.[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 5 0 0]Yeah... What?[n][w][e]
[f 2 1][bup 2 2 65535 65535 0 0][vp 1 0 0 6 0 0][f 4 23 0 2 2 25 25]...So? Get to the point already.[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 7 0 0][f 4 23 0 2 3 25 25]Huh?[n][w][e]

[msg MSG_003_1_0 [Yukari Takeba]]
[f 2 1][cut 2 2 1][e]

[msg MSG_003_0_0 [Yukari Takeba]]
[f 2 1][bup 2 8 65535 65535 0 0][vp 1 0 0 8 0 0]That's not funny![n][w][e]
[f 2 1][bup 2 8 65535 65535 0 0][vp 1 0 0 9 0 0]What!? How do you think that would make Dad feel?[n][w][e]
[f 2 1][bup 2 2 65535 65535 0 0][vp 0 0 0 10 0 0][f 4 23 0 2 2 25 25]......[n][w][e]

[msg MSG_003_3_0 [Yukari Takeba]]
[f 2 1][bup 2 2 65535 65535 0 0][vp 1 0 0 11 0 0]Fine. Do whatever you want.[n][w][e]
[f 2 1][bup 2 2 65535 65535 0 0][vp 1 0 0 12 0 0]Just don't call me again![n][w][e]

[msg MSG_004_0_0 [Yukari Takeba]]
[f 2 1][bup 2 10 65535 65535 0 0][vp 0 0 0 13 0 0]......[n][w][e]
[f 2 1][bup 2 10 65535 65535 0 0][vp 1 0 0 14 0 0]Sorry.[n][w][e]

[sel SEL_005_0_0 top]
[f 2 1]Who was that?[e]
[f 2 1]What was that about?[e]
[f 2 1]Are you okay?[e]

[msg MSG_006_0_0 [Yukari Takeba]]
[f 2 1][bup 2 10 65535 65535 0 0][vp 1 0 0 15 0 0]That was... Um...[n][w][e]

[msg MSG_007_0_0 [Yukari Takeba]]
[f 2 1][bup 2 10 65535 65535 0 0][vp 1 0 0 16 0 0]It was my mom.[n][w][e]
[f 2 1][bup 2 10 65535 65535 0 0][vp 1 0 0 17 0 0]She said she wants to get remarried.[n][w][e]

[msg MSG_008_0_0 [Yukari Takeba]]
[f 2 1][bup 2 8 65535 65535 0 0][vp 1 0 0 18 0 0]None of your business![n][w][e]

[msg MSG_009_0_0 [Yukari Takeba]]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 19 0 0]Sorry. Um...[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 20 0 0]My mom... She's saying she wants to get remarried.[n][w][e]

[msg MSG_010_0_0 [Yukari Takeba]]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 21 0 0][f 5 13 7 15 2]Oh, yeah... I'm fine. Thanks for asking.[n][w][e]

[msg MSG_011_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 22 0 0]You know who I was on the phone with, right...? Yeah, it was my mom.[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 23 0 0]She says she wants to get remarried...[n][w][e]

[msg MSG_012_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 24 0 0]I don't really care if she wants to get married again. What I can't stand is how she chose to live her life.[n][w][e]
[f 2 1][bup 2 10 65535 65535 0 0][vp 1 0 0 25 0 0][f 4 23 0 2 10 25 25]Running away from things, jumping from guy to guy...[n][w][e]
[f 2 1][bup 2 10 65535 65535 0 0][vp 1 0 0 26 0 0]I don't think that's fair to my dad.[n][w][e]

[msg MND_013_0_0]
[f 2 1]Yukari seems pretty upset.[n][w][e]

[msg MND_014_0_0]
[f 2 1]I quietly stood by her side[n]until she calmed down...[n][w][e]

[msg MSG_015_0_0 [Yukari Takeba]]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 27 0 0]Sorry. I'm okay now.[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 28 0 0][f 4 23 0 2 0 25 25]Really. Thanks.[n][w][e]

[msg MSG_015_5_0 [Yukari Takeba]]
[f 2 1][bup 2 2 65535 65535 0 0][vp 1 0 0 29 0 0]I'll never be like her. I'll never give up standing on my own two feet...[n][w][e]

[msg MSG_016_0_0 [Yukari Takeba]]
[f 2 1][bup 2 2 65535 65535 0 0][vp 1 0 0 30 0 0]Running away from your problems by clinging onto others is the worst thing you can do.[n][w][e]
[f 2 1][bup 2 2 65535 65535 0 0][vp 1 0 0 31 0 0]I've decided I'll make it through on my own.[n][w][e]
[f 2 1][bup 2 2 65535 65535 0 0][vp 1 0 0 32 0 0]I'll show her that I can be happy that way.[n][w][e]

[msg MND_017_0_0]
[f 2 1]Yukari has shared her innermost feelings.[n][w][e]
[f 2 1]I understand her a little better now...[n][w][e]

[msg MSG_018_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 33 0 0]Thanks for listening.[n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 34 0 0]For some reason, I feel like I can tell you anything, [nl]-chan...[n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 35 0 0]Let's head back now. I'll do the rest of my shopping some other day.[n][w][e]

[msg MND_019_0_0]
[f 2 1]I left the mall and went back to the dorm...[n][w][e]

