[msg MSG_000_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 1 0 0]Hey, what do you wanna do now? Karaoke?[n][w][e]

[msg MSG_001_0_0 [Child]]
[f 2 1][vp 1 0 0 2 0 0][f 5 21 0 1001]Mommy! Where are you?[n][w][e]

[msg MSG_002_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 0 0 0 3 0 0]...?[n][w][e]

[msg MSG_003_0_0 [Child]]
[f 2 1][vp 1 0 0 4 0 0][f 5 21 0 1001]M-Mooommy! Where aaaaaare you!?[n][w][e]

[msg MSG_004_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 5 0 0]Hey, what's wrong? Are you lost?[n][w][e]

[msg MSG_005_0_0 [Child]]
[f 2 1][vp 1 0 0 6 0 0][f 5 21 0 1001]M-Mommy told me to wait here... and... and... she gave me money, but...[n][w][e]
[f 2 1][vp 1 0 0 7 0 0][f 5 21 0 1001]She's... She's not coming back...[n][w][e]

[msg MSG_006_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 8 0 0]Hey, don't cry...[n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 9 0 0]See, you're okay now.[n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 10 0 0]I'll stay here with you, all right?[n][w][e]

[msg MSG_006_5_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 11 0 0]Hey, look! We can get help over there![n][w][e]

[msg MSG_007_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 12 0 0]C'mon, follow me.[n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 13 0 0]The policeman will know what to do.[n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 14 0 0]He'll find your mom, so don't worry.[n][w][e]

[msg MSG_008_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 15 0 0]Phew, what a relief... I'm glad he was able to contact the parents.[n][w][e]
[f 2 1][bup 2 2 65535 65535 0 0][vp 1 0 0 16 0 0][f 4 23 0 2 2 25 25]What were they thinking, leaving that poor kid all alone!?[n][w][e]
[f 2 1][bup 2 2 65535 65535 0 0][vp 1 0 0 17 0 0]Stuff like that really makes me upset![n][w][e]

[msg MSG_009_0_0 [Yukari Takeba]]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 18 0 0]But...[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 19 0 0]I guess my own mom's no different.[n][w][e]

[sel SEL_010_0_0 top]
[f 2 1]What makes you say that?[e]
[f 2 1]......[e]

[msg MSG_011_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 20 0 0]Why do you wanna know?[n][w][e]

[msg MSG_012_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 21 0 0]Sorry, I didn't mean to poke fun at you.[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 22 0 0]Remember what I told you before, how my mom and I aren't very close?[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 23 0 0]Well, if you asked me what kind of parent she is, I'd say, "a terrible one."[n][w][e]

[msg MSG_012_3_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 24 0 0]She wasn't always like that, though.[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 25 0 0][f 4 23 0 2 3 25 25]After what happened to Dad, she totally changed...[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 26 0 0][f 4 23 0 2 0 25 25]She's probably living with one of her boyfriends somewhere... Honestly, I'd rather not know.[n][w][e]

[msg MSG_013_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 27 0 0]...Don't you want to know what I mean?[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 28 0 0]You must be trying not to pry... Or is that my own wishful thinking?[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 29 0 0]Well, I guess you're right, it's a personal matter.[n][w][e]

[msg MSG_014_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 30 0 0]Even if you did ask, I don't know what I'd say. I have no idea what she's up to these days.[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 31 0 0]Probably shacking up with one of her boyfriends. That's about all I know.[n][w][e]

[msg MSG_015_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 32 0 0]Anyway, I'm done talking about this, okay?[n][w][e]

[msg MSG_016_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 33 0 0]Um... [nl]-chan, could we keep this between you and me? You're the only one I've told.[n][w][e]

[msg MND_017_0_0]
[f 2 1]Yukari has confided in me about her[n]complicated relationship with her mother.[n][w][e]
[f 2 1]It seems we've grown closer...[n][w][e]

[msg MSG_018_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 34 0 0]Sorry... I'm not in the mood for karaoke anymore.[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 35 0 0]Let's go home.[n][w][e]

[msg MND_019_0_0]
[f 2 1]I parted with Yukari and[n]went back to the dorm...[n][w][e]

