[msg MSG_000_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 102 65535 0 0][vp 1 0 0 1 0 0]Oh, oh! Spotted a new set of targets![n][w][e]

[msg MSG_001_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 102 65535 0 0][vp 0 0 0 2 0 0]......[n][w][e]

[msg MSG_002_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 102 65535 0 0][vp 1 0 0 3 0 0]What're you waitin' for, Sanada-san? Show us what you got.[n][w][e]

[msg MSG_003_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 102 65535 0 0][vp 1 0 0 4 0 0]Just keep your mouth shut.[n][w][e]

[msg MSG_004_0_0 [Girl in Black]]
[f 2 1][vp 1 0 0 5 0 0][f 5 21 0 1001]Hey, Nobuko. Are those boys looking at us?[n][w][e]

[msg MSG_005_0_0 [Nobuko]]
[f 2 1][vp 1 0 0 6 0 0][f 5 21 0 1002]Oh yeah, they are.[n][w][e]

[msg MSG_005_5_0 [Nobuko]]
[f 2 1][vp 1 0 0 7 0 0][f 5 21 0 1002]Wow, Yoshie, I'm surprised you could see from over there.[n][w][e]

[msg MSG_006_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 102 65535 0 0][vp 1 0 0 8 0 0]All right, time to get in the ring.[n][w][e]

[msg MSG_007_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 1 102 65535 0 0][vp 1 0 0 9 0 0]Uh... H-Hi there.[n][w][e]

[msg MSG_007_5_0 [Akihiko Sanada]]
[f 2 1][bup 4 1 102 65535 0 0][vp 1 0 0 10 0 0]S-Sorry to bother you, but, um... I-I wanted to ask you something.[n][w][e]

[msg MSG_008_0_0 [Yoshie]]
[f 2 1][vp 1 0 0 11 0 0][f 5 21 0 1001]And what would that be?[n][w][e]

[msg MSG_009_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 102 65535 0 0][vp 1 0 0 12 0 0]Er, um... Are you two here alone?[n][w][e]

[msg MSG_010_0_0 [Nobuko]]
[f 2 1][vp 1 0 0 13 0 0][f 5 21 0 1002]Ahaha, are you hitting on us?[n][w][e]

[msg MSG_011_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 102 65535 0 0][vp 1 0 0 14 0 0]N-No, no, not at all.[n][w][e]
[f 2 1][bup 4 0 102 65535 0 0][vp 1 0 0 15 0 0]We just thought that if you're bored, you might wanna talk, or...[n][w][e]
[f 2 1][bup 4 0 102 65535 0 0][vp 1 0 0 16 0 0]A chance meeting like this might stir things up for both of us, you know?[n][w][e]

[msg MSG_012_0_0 [Yoshie]]
[f 2 1][vp 1 0 0 17 0 0][f 5 21 0 1001]Um, isn't that what it means to hit on someone?[n][w][e]

[msg MSG_012_5_0 [Yoshie]]
[f 2 1][vp 1 0 0 18 0 0][f 5 21 0 1001]Haven't you heard? It's lame to hit on girls at the beach nowadays.[n][w][e]

[msg MSG_013_0_0 [Nobuko]]
[f 2 1][vp 1 0 0 19 0 0][f 5 21 0 1002]Aw, come on. We were bored anyway.[n][w][e]

[msg MSG_014_0_0 [Nobuko]]
[f 2 1][vp 1 0 0 20 0 0][f 5 21 0 1002]Besides, they look kinda cool.[n][w][e]

[msg MSG_015_0_0 [Yoshie]]
[f 2 1][vp 1 0 0 21 0 0][f 5 21 0 1001]Ugh, really, Nobuko?[n][w][e]

[msg MSG_016_0_0 [Nobuko]]
[f 2 1][vp 1 0 0 22 0 0][f 5 21 0 1002]Hey, how old do we look to you?[n][w][e]

[sel SEL_017_0_0 top]
[f 2 1]About the same as us?[e]
[f 2 1]Around twenty?[e]

[msg MSG_018_0_0 [Yoshie]]
[f 2 1][vp 1 0 0 23 0 0][f 5 21 0 1001]The same as you? That's crap and you know it.[n][w][e]

[msg MSG_019_0_0 [Nobuko]]
[f 2 1][vp 1 0 0 24 0 0][f 5 21 0 1002]They were just trying to be nice.[n][w][e]

[msg MSG_020_0_0 [Nobuko]]
[f 2 1][vp 1 0 0 25 0 0][f 5 21 0 1002]We've actually been out of college a few years now.[n][w][e]

[msg MSG_021_0_0 [Nobuko]]
[f 2 1][vp 1 0 0 26 0 0][f 5 21 0 1002]Seriously? We still look that young?[n][w][e]
[f 2 1][vp 1 0 0 27 0 0][f 5 21 0 1002]Aw, I'm so happy to hear that! Even if it's just flattery.[n][w][e]
[f 2 1][vp 1 0 0 28 0 0][f 5 21 0 1002]To tell you the truth, we're actually older than that.[n][w][e]

[msg MSG_022_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 3 102 65535 0 0][vp 1 0 0 29 0 0]O-Oh, you are? Th-That's too bad.[n][w][e]

[msg MSG_023_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 102 65535 0 0][vp 1 0 0 30 0 0]No, wait, that's fine by us! Older women are more mature and experienced and stuff![n][w][e]

[msg MSG_024_0_0 [Yoshie]]
[f 2 1][vp 1 0 0 31 0 0][f 5 21 0 1001]Y'know, you're a pretty smooth talker for someone so young.[n][w][e]
[f 2 1][vp 1 0 0 32 0 0][f 5 21 0 1001]How old are you guys, anyway?[n][w][e]

[msg MSG_025_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 102 65535 0 0][vp 1 0 0 33 0 0]Truth is, we're in high school.[n][w][e]

[msg MSG_026_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 102 65535 0 0][vp 1 0 0 34 0 0]I'll be graduating next year.[n][w][e]

[msg MSG_027_0_0 [Nobuko]]
[f 2 1][vp 1 0 0 35 0 0][f 5 21 0 1002]Oh gosh. That's more of an age gap than I was expecting...[n][w][e]

[msg MSG_028_0_0 [Yoshie]]
[f 2 1][vp 1 0 0 36 0 0][f 5 21 0 1001]See? It's not gonna work out. Besides, I doubt you're having any fun talking to us.[n][w][e]

[sel SEL_029_0_0 top]
[f 2 1]Yes we are.[e]
[f 2 1]Right, it's boring.[e]

[msg MSG_030_0_0 [Nobuko]]
[f 2 1][vp 1 0 0 37 0 0][f 5 21 0 1002]Come on, no you're not.[n][w][e]
[f 2 1][vp 1 0 0 38 0 0][f 5 21 0 1002]I don't think there's anything we could chat about that you'd find interesting. Unless you wanna hear me complain about my boss?[n][w][e]

[msg MSG_031_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 102 65535 0 0][vp 1 0 0 39 0 0]Uh, complaining about your boss... That might be fun.[n][w][e]

[msg MSG_032_0_0 [Yoshie]]
[f 2 1][vp 1 0 0 40 0 0][f 5 21 0 1001]You're not very good at lying, are you? You really don't have to try so hard.[n][w][e]

[msg MSG_033_0_0 [Nobuko]]
[f 2 1][vp 1 0 0 41 0 0][f 5 21 0 1002]Yoshie! Don't ruin the conversation![n][w][e]
[f 2 1][vp 1 0 0 42 0 0][f 5 21 0 1002]He said it might be fun, so just play along![n][w][e]

[msg MSG_034_0_0 [Yoshie]]
[f 2 1][vp 1 0 0 43 0 0][f 5 21 0 1001]Wow, she called us boring.[n][w][e]

[msg MSG_035_0_0 [Nobuko]]
[f 2 1][vp 1 0 0 44 0 0][f 5 21 0 1002]What do you mean, Yoshie? She was just kidding.[n][w][e]

[msg MSG_036_0_0 [Yoshie]]
[f 2 1][vp 1 0 0 45 0 0][f 5 21 0 1001]Nobuko, you need to stop being so nice to everyone![n][w][e]

[msg MSG_037_0_0 [Nobuko]]
[f 2 1][vp 1 0 0 46 0 0][f 5 21 0 1002]Aww, c'mon! It's been ages since I've done this![n][w][e]

[msg MSG_038_0_0 [Yoshie]]
[f 2 1][vp 1 0 0 47 0 0][f 5 21 0 1001]You've teased these kids enough. We should head back.[n][w][e]
[f 2 1][vp 1 0 0 48 0 0][f 5 21 0 1001]They're gonna be waiting on us, you know.[n][w][e]

[msg MSG_039_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 102 65535 0 0][vp 1 0 0 49 0 0]"They"...? You mean, you have boyfriends?[n][w][e]

[msg MSG_040_0_0 [Nobuko]]
[f 2 1][vp 1 0 0 50 0 0][f 5 21 0 1002]Oh, right. Sorry, forgot to mention that. Well, we gotta go now.[n][w][e]
[f 2 1][vp 1 0 0 51 0 0][f 5 21 0 1002]We're meeting our boyfriends back at the villa for a barbecue.[n][w][e]
[f 2 1][vp 1 0 0 52 0 0][f 5 21 0 1002]You can come if you want.[n][w][e]

[msg MSG_041_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 102 65535 0 0][vp 0 0 0 53 0 0]......[n][w][e]

[msg MSG_042_0_0 [Yoshie]]
[f 2 1][vp 1 0 0 54 0 0][f 5 21 0 1001]Bye.[n][w][e]

[msg MSG_043_0_0 [Junpei Iori]]
[f 2 1][bup 3 3 102 65535 0 0][vp 1 0 0 55 0 0]Sanada-san![n][w][e]
[f 2 1][bup 3 3 102 65535 0 0][vp 1 0 0 56 0 0]What happened!? We looked like a bunch of idiots![n][w][e]

[msg MSG_044_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 3 102 65535 0 0][vp 0 0 0 57 0 0]......[n][w][e]

[msg MSG_045_0_0 [Junpei Iori]]
[f 2 1][bup 3 2 102 65535 0 0][vp 1 0 0 58 0 0]And you! You haven't been pullin' your weight either![n][w][e]

[msg MSG_046_0_0 [Junpei Iori]]
[f 2 1][bup 3 2 102 65535 0 0][vp 1 0 0 59 0 0]You gotta come through on the next one, you hear me?[n][w][e]

