[msg MSG_000_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 2 51 65535 0 0][vp 1 0 0 1 0 0]Akihiko![n][w][e]

[msg MSG_001_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 5 52 65535 0 0][vp 1 0 0 2 0 0]Agh...![n][w][e]

[msg MSG_002_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 52 65535 0 0][vp 1 0 0 3 0 0]I'm all right.[n][w][e]
[f 2 1][bup 4 1 52 65535 0 0][vp 1 0 0 4 0 0][f 4 23 0 4 1 25 25]Get ready to be surprised... It'll be here any second.[n][w][e]

[msg MSG_003_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 2 51 65535 0 0][vp 1 0 0 5 0 0]This is no time to joke around![n][w][e]

[msg MSG_004_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 6 0 0]Is it one of them, Sanada-kun?[n][w][e]

[msg MSG_005_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 52 65535 0 0][vp 1 0 0 7 0 0]Yeah, but not an ordinary one...[n][w][e]

[msg MSG_006_0_0 [Yukari Takeba]]
[f 2 1][bup 2 4 51 65535 0 0][vp 1 0 0 8 0 0]Ahh![n][w][e]
[f 2 1][bup 2 4 51 65535 0 0][vp 1 0 0 9 0 0]What was that!? You've gotta be kidding me![n][w][e]

[msg MSG_007_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 51 65535 0 0][vp 1 0 0 10 0 0]Mr. Chairman, please head for the command room![n][w][e]
[f 2 1][bup 5 0 51 65535 0 0][vp 1 0 0 11 0 0]Takeba, go upstairs and wake her up! Then, escape out the back.[n][w][e]

[msg MSG_008_0_0 [Yukari Takeba]]
[f 2 1][bup 2 4 51 65535 0 0][vp 1 0 0 12 0 0]But what about you two?[n][w][e]

[msg MSG_009_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 51 65535 0 0][vp 1 0 0 13 0 0]We'll stop it here.[n][w][e]
[f 2 1][bup 5 0 51 65535 0 0][vp 1 0 0 14 0 0]You're the one who led it to us, Akihiko, so I'm going to have you fight.[n][w][e]

[msg MSG_010_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 2 52 65535 0 0][vp 1 0 0 15 0 0]It's not like I asked it to follow me![n][w][e]
[f 2 1][bup 4 2 52 65535 0 0][vp 1 0 0 16 0 0]What are you waiting for, Takeba? Go![n][w][e]

[msg MSG_011_0_0 [Yukari Takeba]]
[f 2 1][bup 2 2 51 65535 0 0][vp 1 0 0 17 0 0]O-Okay![n][w][e]

