[msg MND_000_0_0]
[f 2 1]I can hear my classmates whispering...[n][w][e]

[msg MND_001_0_0]
[f 2 1]I've become slightly more popular...[n][w][e]

[msg MND_002_0_0]
[f 2 1]I gave him the wrong answer...[n][w][e]

[msg MSG_003_0_0 [Ms. Toriumi]]
[f 2 1][bup 1581 0 65535 65535 0 0][vp 3 0 65535 15807 0 0][f 5 21 0 100]Open your textbooks and we'll take a look at the first novel by... Zenzou Kasai.[n][w][e]
[f 2 1][bup 1581 0 65535 65535 0 0][f 5 21 0 100]Ugh... Why him?[n][w][e]
[f 2 1][bup 1581 0 65535 65535 0 0][f 5 21 0 100]I've been more interested in Tota Kaneko's work lately.[n][w][e]
[f 2 1][bup 1581 0 65535 65535 0 0][f 5 21 0 100]His essays are fantastic, and he's also a famous haiku poet.[n][w][e]
[f 2 1][bup 1581 0 65535 65535 0 0][f 5 21 0 100]I wonder why all this isn't in the textbook... Well, I guess I'll just bring his book next time.[n][w][e]

[msg MSG_004_0_0 [Ms. Toriumi]]
[f 2 1][bup 1581 0 65535 65535 0 0][f 5 21 0 100]Speaking of haiku, they often use words or phrases related to seasons, but it's easy to get them mixed up.[n][w][e]
[f 2 1][bup 1581 0 65535 65535 0 0][f 5 21 0 100]For example, you'd think "tasty bamboo shoots" and "vivid carp streamers" would symbolize spring, right?[n][w][e]
[f 2 1][bup 1581 0 65535 65535 0 0][f 5 21 0 100]Well, they're actually related to summer![n][w][e]
[f 2 1][bup 1581 0 65535 65535 0 0][f 5 21 0 100]Haiku poets usually refer to seasons based on the lunar calendar, making it fairly complicated.[n][w][e]
[f 2 1][bup 1581 0 65535 65535 0 0][vp 3 0 65535 15801 0 0][f 5 21 0 100]...Hey, Iori, are you listening? Here's a question for you.[n][w][e]
[f 2 1][bup 1581 0 65535 65535 0 0][f 5 21 0 100]Among these phrases, "a rain of flowers," "mystical mirage," and "vivid carp streamers," which one symbolizes summer?[n][w][e]

[msg MSG_005_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 65535 65535 0 0][vp 3 0 65535 2099 0 0][f 5 21 0 150]Wh-Whuh? Uhhh...[n][w][e]
[f 2 1][bup 3 4 65535 65535 0 0]Psst, [nf]! You were listening, right!? Lend a brother a hand![n][w][e]

[msg MSG_006_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 65535 65535 0 0][f 5 21 0 150]What phrase symbolizes summer!?[n][w][e]

[sel SEL_007_0_0 top]
[f 2 1]"A rain of flowers."[f 5 20 45 0][e]
[f 2 1]"Mystical mirage."[f 5 20 45 1][e]
[f 2 1]"Vivid carp streamers."[f 2 9 1 0 13][f 5 20 45 2][e]

[msg MSG_008_0_0 [Ms. Toriumi]]
[f 2 1][bup 1581 1 65535 65535 0 0][vp 3 0 65535 15841 0 0][f 5 21 0 100]Yep, that's right![n][w][e]
[f 2 1][bup 1581 1 65535 65535 0 0][f 5 21 0 100]So you were listening to me after all![n][w][e]

[msg MSG_009_0_0 [Ms. Toriumi]]
[f 2 1][bup 1581 2 65535 65535 0 0][vp 3 0 65535 15829 0 0][f 5 21 0 100]Nope! I said that "vivid carp streamers" is related to summer just now, didn't I?[n][w][e]
[f 2 1][bup 1581 2 65535 65535 0 0][f 5 21 0 100]Could you PLEASE pay attention to my lectures!?[n][w][e]
[f 2 1][bup 1581 2 65535 65535 0 0][f 5 21 0 100]You'll make me cry if you keep this up! Listen closely next time![n][w][e]

[msg MSG_010_0_0 [Ms. Toriumi]]
[f 2 1][bup 1581 0 65535 65535 0 0][f 5 21 0 100]By the way, "mystical mirage" and "a rain of flowers" represent spring.[n][w][e]
[f 2 1][bup 1581 0 65535 65535 0 0][f 5 21 0 100]A mirage is a natural phenomenon that occurs around late March to early June...[n][w][e]
[f 2 1][bup 1581 0 65535 65535 0 0][f 5 21 0 100]And "a rain of flowers" refers to the spring showers around the time cherry blossoms bloom. It's not literally raining flowers.[n][w][e]
[f 2 1][bup 1581 0 65535 65535 0 0][f 5 21 0 100]Make sure you remember all that. Our next topic is...[n][w][e]

[msg MSG_011_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][f 5 21 0 150]Heheh... Well, you know how much I like to pay attention![n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2044 0 0][f 5 21 0 150]Man, you seriously saved my bacon, [nf]![n][w][e]

[msg MSG_012_0_0 [Classmate]]
[f 2 1][nl]-chan gave him the answer just now... She must have a good memory or something.[n][w][e]

[msg MSG_013_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 65535 65535 0 0][vp 3 0 65535 2112 0 0][f 5 21 0 150]O-Oh, uh... S-Sorry![n][w][e]
[f 2 1][bup 3 4 65535 65535 0 0][f 5 21 0 150]I ain't lettin' this go, man![n][w][e]

[msg MSG_014_0_0 [Ms. Miyahara]]
[f 2 1][bup 1085 0 65535 65535 0 0][vp 3 0 65535 15401 0 0][f 5 21 0 100]All right, let's review quadratic functions. You all remember those, don't you?[n][w][e]
[f 2 1][bup 1085 0 65535 65535 0 0][f 5 21 0 100]Sometimes the graph will be a parabola, or sometimes a hyperbola.[n][w][e]
[f 2 1][bup 1085 0 65535 65535 0 0][f 5 21 0 100]Well, they're certainly beautiful curves... But they can't measure up to parabolic and hyperbolic spirals![n][w][e]
[f 2 1][bup 1085 0 65535 65535 0 0][f 5 21 0 100]These are algebraic spirals. Look, aren't they magnificent?[n][w][e]

[msg MSG_015_0_0 [Ms. Miyahara]]
[f 2 1][bup 1085 0 65535 65535 0 0][vp 3 0 65535 15416 0 0][f 5 21 0 100]Now then, let's see if you can answer this from a mathematical point of view, Iori-kun.[n][w][e]
[f 2 1][bup 1085 0 65535 65535 0 0][f 5 21 0 100]Which of the following is not an algebraic spiral?[n][w][e]

[msg MSG_016_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 65535 65535 0 0][vp 3 0 65535 2103 0 0][f 5 21 0 150]H-Hold up, how the heck am I supposed to know something like that!?[n][w][e]

[msg MSG_017_0_0 [Junpei Iori]]
[f 2 1][f 5 21 0 150][nf], do you know which one's not an algebraic spiral or whatever?[n][w][e]

[sel SEL_018_0_0 top]
[f 2 1]A.[f 2 9 1 0 13][f 5 20 45 0][e]
[f 2 1]B.[f 5 20 45 1][e]
[f 2 1]C.[f 5 20 45 2][e]
[f 2 1]D.[f 5 20 45 3][e]

[msg MSG_019_0_0 [Ms. Miyahara]]
[f 2 1][bup 1085 0 65535 65535 0 0][vp 3 0 65535 15418 0 0][f 5 21 0 100]Correct! Well done![n][w][e]
[f 2 1][bup 1085 0 65535 65535 0 0][f 5 21 0 100]This is a logarithmic spiral. When the golden ratio is the growth factor, it's called a golden spiral.[n][w][e]

[msg MSG_020_0_0 [Ms. Miyahara]]
[f 2 1][bup 1085 0 65535 65535 0 0][vp 3 0 65535 15419 0 0][f 5 21 0 100]Too bad, the correct answer is A.[n][w][e]
[f 2 1][bup 1085 0 65535 65535 0 0][f 5 21 0 100]This is a logarithmic spiral. When the golden ratio is the growth factor, it's called a golden spiral.[n][w][e]

[msg MSG_021_0_0 [Ms. Miyahara]]
[f 2 1][bup 1085 0 65535 65535 0 0][f 5 21 0 100]Just as the name implies, you can graph an algebraic spiral using an algebraic equation.[n][w][e]
[f 2 1][bup 1085 0 65535 65535 0 0][f 5 21 0 100]B is the Archimedean spiral, C is a parabolic spiral, and D is a lituus. All of which are algebraic spirals.[n][w][e]
[f 2 1][bup 1085 0 65535 65535 0 0][f 5 21 0 100]However, A, the logarithmic spiral, is not considered an algebraic spiral.[n][w][e]
[f 2 1][bup 1085 0 65535 65535 0 0][f 5 21 0 100]It is a common spiral found in nature, such as on nautilus shells and sunflower seeds.[n][w][e]
[f 2 1][bup 1085 0 65535 65535 0 0][f 5 21 0 100]No matter how far you scale in or out, the shape remains roughly the same. This is called self-similarity.[n][w][e]

[msg MSG_022_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][f 5 21 0 150]The way it spirals kinda reminds me of Tartarus...[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2043 0 0][f 5 21 0 150]...What, just me? Eh. Anyways, thanks for your help, dude![n][w][e]

[msg MSG_023_0_0 [Classmate]]
[f 2 1][nl]-chan gave him the answer just now. She must be really smart![n][w][e]

[msg MSG_024_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2070 0 0][f 5 21 0 150]Huh, actually... don't it kinda look like Tartarus? Who the heck even made that place?[n][w][e]

[msg MSG_025_0_0 [Ms. Miyahara]]
[f 2 1][bup 1085 0 65535 65535 0 0][vp 3 0 65535 15405 0 0][f 5 21 0 100]Oh gosh... Cartesian coordinates really are beautiful, aren't they?[n][w][e]
[f 2 1][bup 1085 0 65535 65535 0 0][f 5 21 0 100]There is one in particular that's my favorite though... Are you curious? You are, right? Right?[n][w][e]

[msg MSG_026_0_0 [Ms. Miyahara]]
[f 2 1][bup 1085 0 65535 65535 0 0][f 5 21 0 100]This curve is a graph of a Cartesian equation...[n][w][e]
[f 2 1][bup 1085 0 65535 65535 0 0][f 5 21 0 100]One that was discovered by Italian mathematician Maria Agnesi.[n][w][e]
[f 2 1][bup 1085 0 65535 65535 0 0][f 5 21 0 100]It's actually named after her. Some people call it the curve of Agnesi.[n][w][e]
[f 2 1][bup 1085 0 65535 65535 0 0][vp 3 0 65535 15416 0 0][f 5 21 0 100]However, it is more commonly known by another name. Iori, do you have idea what it is?[n][w][e]

[msg MSG_027_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 65535 65535 0 0][vp 3 0 65535 2101 0 0][f 5 21 0 150]Huh!? How would I know!? Heck, are we even talkin' about math anymore?[n][w][e]
[f 2 1][bup 3 3 65535 65535 0 0][f 5 21 0 150]Psst, [nf]... Do you know the answer?[n][w][e]

[msg MSG_028_0_00 [Junpei Iori]]
[f 2 1][f 5 21 0 150]What else do people call this curve?[n][w][e]

[sel SEL_029_0_0 top]
[f 2 1]Orthogonal curves.[f 5 20 45 0][e]
[f 2 1]Fermat's spiral.[f 5 20 45 1][e]
[f 2 1]Witch of Agnesi.[f 2 9 1 0 13][f 5 20 45 2][e]

[msg MSG_030_0_0 [Ms. Miyahara]]
[f 2 1][bup 1085 0 65535 65535 0 0][vp 3 0 65535 15417 0 0][f 5 21 0 100]That's correct! I'm surprised you even knew that.[n][w][e]

[msg MSG_031_0_0 [Ms. Miyahara]]
[f 2 1][bup 1085 0 65535 65535 0 0][vp 3 0 65535 15420 0 0][f 5 21 0 100]Hm, that's not correct. Was my question too difficult?[n][w][e]
[f 2 1][bup 1085 0 65535 65535 0 0][f 5 21 0 100]The curve of Agnesi is more famously known as the Witch of Agnesi.[n][w][e]

[msg MSG_032_0_0 [Ms. Miyahara]]
[f 2 1][bup 1085 0 65535 65535 0 0][f 5 21 0 100]As to why it's called a "witch"...[n][w][e]
[f 2 1][bup 1085 0 65535 65535 0 0][f 5 21 0 100]Nobody really knows! Apparently, it came from a mistranslation of the Italian word for the versine of a curve.[n][w][e]
[f 2 1][bup 1085 0 65535 65535 0 0][f 5 21 0 100]Merely an inadvertent mistake, I suppose![n][w][e]
[f 2 1][bup 1085 0 65535 65535 0 0][f 5 21 0 100]I make careless mistakes fairly often as well... But it's pretty embarrassing when your mistake lasts for generations.[n][w][e]
[f 2 1][bup 1085 0 65535 65535 0 0][f 5 21 0 100]I mean, if the shape of the curve resembled a witch, maybe they could have gotten away with it, but... alas.[n][w][e]

[msg MSG_033_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][f 5 21 0 150]Haha, that's just common sense, Ms. M![n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2039 0 0][f 5 21 0 150]Phew... Thanks, [nf]! I was about to sound real stupid.[n][w][e]

[msg MSG_034_0_0 [Classmate]]
[f 2 1][nl]-chan helped him out there. Seems like you can always count on her.[n][w][e]

[msg MSG_035_0_0 [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0][vp 3 0 65535 2111 0 0][f 5 21 0 150]...Yo, how were we supposed to figure that out without any hints?[n][w][e]

[msg MSG_036_0_0 [Mr. Takenozuka]]
[f 2 1][bup 1084 0 65535 65535 0 0][vp 3 0 65535 15606 0 0][f 5 21 0 100]Everyone understand the Lorentz force and the left-hand rule? Then I'm erasing the board![n][w][e]
[f 2 1][bup 1084 0 65535 65535 0 0][f 5 21 0 100]Hopefully, all of you have been taking notes because it might be on the [clr 2]exam in two weeks[clr 27].[n][w][e]
[f 2 1][bup 1084 0 65535 65535 0 0][f 5 21 0 100]My shoulders feel lighter than usual today. I can even erase the top of the blackboard with ease.[n][w][e]
[f 2 1][bup 1084 0 65535 65535 0 0][f 5 21 0 100]Perhaps it's because I went to the bathhouse yesterday. I had a nice, long massage in the whirlpool bath.[n][w][e]

[msg MSG_037_0_0 [Mr. Takenozuka]]
[f 2 1][bup 1084 0 65535 65535 0 0][vp 3 0 65535 15616 0 0][f 5 21 0 100]Which brings us to my next question...[n][w][e]
[f 2 1][bup 1084 0 65535 65535 0 0][f 5 21 0 100]When streams of air bubbles from a whirlpool bath hit you, your body vibrates, yes?[n][w][e]
[f 2 1][bup 1084 0 65535 65535 0 0][f 5 21 0 100]There's actually a name for this phenomenon. Iori, perhaps you know what it is?[n][w][e]

[msg MSG_038_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 65535 65535 0 0][vp 3 0 65535 2099 0 0][f 5 21 0 150]Uhhh... Dude, how would I know?[n][w][e]

[msg MSG_039_0_00 [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0][f 5 21 0 150]Hey, you got any idea, [nf]?[n][w][e]
[f 2 1][bup 3 3 65535 65535 0 0][f 5 21 0 150]What's it called when the air bubbles in a whirlpool bath hit you and make your body vibrate?[n][w][e]

[sel SEL_040_0_0 top]
[f 2 1]The anchor effect.[f 5 20 45 0][e]
[f 2 1]The flutter effect.[f 2 9 1 0 13][f 5 20 45 1][e]
[f 2 1]The bubble jet phenomenon.[f 5 20 45 2][e]

[msg MSG_041_0_0 [Mr. Takenozuka]]
[f 2 1][bup 1084 0 65535 65535 0 0][vp 3 0 65535 15617 0 0]Oh, I suppose you already knew. That's right, the answer is indeed the flutter effect.[n][w][e]
[f 2 1][bup 1084 0 65535 65535 0 0]"Flutter" refers to the small vibrations generated by interactions between airflow and other forces.[n][w][e]

[msg MSG_042_0_0 [Mr. Takenozuka]]
[f 2 1][bup 1084 0 65535 65535 0 0][vp 3 0 65535 15620 0 0][f 5 21 0 100]...That's incorrect. The answer I'm looking for is the flutter effect.[n][w][e]
[f 2 1][bup 1084 0 65535 65535 0 0][f 5 21 0 100]"Flutter" refers to the small vibrations generated by interactions between airflow and other forces.[n][w][e]

[msg MSG_043_0_0 [Mr. Takenozuka]]
[f 2 1][bup 1084 0 65535 65535 0 0][f 5 21 0 100]It's not just whirlpool baths that have benefits. Do you ever feel itchy after taking a regular bath?[n][w][e]
[f 2 1][bup 1084 0 65535 65535 0 0][f 5 21 0 100]It's said taking a warm bath can improve blood circulation throughout the body.[n][w][e]
[f 2 1][bup 1084 0 65535 65535 0 0][f 5 21 0 100]And as the body warms up, the blood vessels dilate, flushing your body of toxins all at once...[n][w][e]
[f 2 1][bup 1084 0 65535 65535 0 0][f 5 21 0 100]Heat can stimulate the secretion of histamine, which often makes the body itch.[n][w][e]
[f 2 1][bup 1084 0 65535 65535 0 0][f 5 21 0 100]Hot baths may feel marvelous, but it's best to take them in moderation. Lukewarm water, on the other hand, helps cleanse the skin—[n][w][e]
[f 2 1][bup 1084 0 65535 65535 0 0][f 5 21 0 100]...Ahem, I digress. Now then, let's get back to class. Open your books to page 8...[n][w][e]

[msg MSG_044_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2095 0 0][f 5 21 0 150]Man, now I wanna try taking a dip in a whirlpool bath... Think we could ask Kirijo-senpai for one in the dorm?[n][w][e]

[msg MSG_045_0_0 [Classmate]]
[f 2 1][nl]-chan gave him the answer just now. She must be really smart![n][w][e]

[msg MSG_046_0_0 [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0][vp 3 0 65535 2115 0 0][f 5 21 0 150]This ain't gonna be on the test, right? I mean, we were just talkin' about baths...[n][w][e]

[msg MSG_047_0_0 [Mr. Ekoda]]
[f 2 1][bup 1082 0 65535 65535 0 0][vp 3 0 65535 15002 0 0][f 5 21 0 100]As you all should know, there are many theories about the author, Murasaki Shikibu.[n][w][e]
[f 2 1][bup 1082 0 65535 65535 0 0][f 5 21 0 100]That The Tale of Genji was authored by someone else... That "Murasaki Shikibu" was a shared pen name...[n][w][e]
[f 2 1][bup 1082 0 65535 65535 0 0][f 5 21 0 100]Some have even suggested that Murasaki Shikibu was an alien from outer space. A truly intriguing theory...[n][w][e]
[f 2 1][bup 1082 0 65535 65535 0 0][f 5 21 0 100]You've probably seen her portrait. It's printed on the 2,000-yen bill.[n][w][e]
[f 2 1][bup 1082 0 65535 65535 0 0][f 5 21 0 100]Well, since we're on the topic of Murasaki Shikibu, here's a question regarding The Tale of Genji.[n][w][e]

[msg MSG_048_0_0 [Mr. Ekoda]]
[f 2 1][bup 1082 0 65535 65535 0 0][f 5 21 0 100]"Thou shalt not recite such a tale of this world before the princess"...[n][w][e]
[f 2 1][bup 1082 0 65535 65535 0 0][vp 3 0 65535 15013 0 0][f 5 21 0 100]Now, what such tale does this quote refer to? Iori? Go on and answer.[n][w][e]

[msg MSG_049_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2098 0 0][f 5 21 0 150]Huh? Me?[n][w][e]

[msg MSG_050_0_0 [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0][f 5 21 0 150]H-Hey, lend me a hand here, [nf]. What kinda tale is he talkin' about?[n][w][e]

[sel SEL_051_0_0 top]
[f 2 1]About a peaceful world.[f 5 20 45 0][e]
[f 2 1]About public opinion.[f 5 20 45 1][e]
[f 2 1]About romance.[f 2 9 1 0 13][f 5 20 45 2][e]

[msg MSG_052_0_0 [Mr. Ekoda]]
[f 2 1][bup 1082 0 65535 65535 0 0][vp 3 0 65535 15018 0 0]Correct. Too easy, was it?[n][w][e]

[msg MSG_053_0_0 [Mr. Ekoda]]
[f 2 1][bup 1082 0 65535 65535 0 0][vp 3 0 65535 15010 0 0][f 5 21 0 100]That's... not correct.[n][w][e]
[f 2 1][bup 1082 0 65535 65535 0 0][f 5 21 0 100]I cannot possibly wait to see what tales you will write on the next exam...[n][w][e]

[msg MSG_054_0_0 [Mr. Ekoda]]
[f 2 1][bup 1082 0 65535 65535 0 0][f 5 21 0 100]The "world" used in this sentence refers to the world of relationships and romance.[n][w][e]
[f 2 1][bup 1082 0 65535 65535 0 0][f 5 21 0 100]Therefore, he is told not to read tales of romance in front of the princess.[n][w][e]
[f 2 1][bup 1082 0 65535 65535 0 0][f 5 21 0 100]However, "world" can also refer to "society" or "mankind," like how it's often used today.[n][w][e]
[f 2 1][bup 1082 0 65535 65535 0 0][f 5 21 0 100]Make sure you read it correctly based on the given context. Now on to the next one...[n][w][e]

[msg MSG_055_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2044 0 0][f 5 21 0 150]Phew... Thanks, [nf]. You're a life saver.[n][w][e]

[msg MSG_056_0_0 [Classmate]]
[f 2 1][nl]-chan really got Junpei out of a pinch back there. She's such a nice girl![n][w][e]

[msg MSG_057_0_0 [Junpei Iori]]
[f 2 1][bup 3 2 65535 65535 0 0][vp 3 0 65535 2129 0 0][f 5 21 0 150]Grrr... Stupid ol' Ekoda...[n][w][e]
[f 2 1][bup 3 2 65535 65535 0 0][f 5 21 0 150]Ain't nobody gonna use The Tale of Genji in the future, dammit![n][w][e]

[msg MSG_058_0_0 [Mrs. Terauchi]]
[f 2 1][bup 1583 0 65535 65535 0 0][vp 3 0 65535 16203 0 0][f 5 21 0 100]Let's take a look at some English idioms.[n][w][e]
[f 2 1][bup 1583 0 65535 65535 0 0][f 5 21 0 100]When someone has a "big mouth," it means they're a loudmouth or a boastful person.[n][w][e]

[msg MSG_059_0_0 [Mrs. Terauchi]]
[f 2 1][bup 1583 0 65535 65535 0 0][f 5 21 0 100]There's also the phrase "spill the beans"...[n][w][e]
[f 2 1][bup 1583 0 65535 65535 0 0][vp 3 0 65535 16206 0 0][f 5 21 0 100]What exactly does this idiom mean? Junpei, why don't you answer?[n][w][e]

[msg MSG_060_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2098 0 0][f 5 21 0 150]Huh...? Me?[n][w][e]

[msg MSG_061_0_0 [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0][f 5 21 0 150]H-Hey, [nf], do you know what it means to "spill the beans"?[n][w][e]

[sel SEL_062_0_0 top]
[f 2 1]To drop money.[f 5 20 45 0][e]
[f 2 1]To break into a smile.[f 5 20 45 1][e]
[f 2 1]To reveal a secret.[f 2 9 1 0 13][f 5 20 45 2][e]

[msg MSG_063_0_0 [Mrs. Terauchi]]
[f 2 1][bup 1583 0 65535 65535 0 0][vp 3 0 65535 16218 0 0][f 5 21 0 100]Yes! That's correct.[n][w][e]

[msg MSG_064_0_0 [Mrs. Terauchi]]
[f 2 1][bup 1583 0 65535 65535 0 0][vp 3 0 65535 16219 0 0][f 5 21 0 100]Oh no, no, Junpei! When you "spill the beans," that means you "reveal a secret."[n][w][e]

[msg MSG_065_0_0 [Mrs. Terauchi]]
[f 2 1][bup 1583 0 65535 65535 0 0][f 5 21 0 100]There are many theories about why the word "beans" is used.[n][w][e]
[f 2 1][bup 1583 0 65535 65535 0 0][f 5 21 0 100]One particularly famous theory says that beans were used to vote in ancient Greece.[n][w][e]
[f 2 1][bup 1583 0 65535 65535 0 0][f 5 21 0 100]At that time, they'd put white beans for "yes" and black beans for "no" into the ballot box...[n][w][e]
[f 2 1][bup 1583 0 65535 65535 0 0][f 5 21 0 100]And if you spill the beans before voting, it'd reveal their color—and your once "secret" vote.[n][w][e]
[f 2 1][bup 1583 0 65535 65535 0 0][f 5 21 0 100]Oh, that reminds me! Last time, my darling...[n][w][e]

[msg MSG_066_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2040 0 0][f 5 21 0 150]Phew... Thanks, [nf].[n][w][e]

[msg MSG_067_0_0 [Classmate]]
[f 2 1][nl]-chan gave him the answer just now. She must be really smart![n][w][e]

[msg MSG_068_0_0 [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0][vp 3 0 65535 2115 0 0][f 5 21 0 150]Well, no point cryin' over spilled milk, I guess.[n][w][e]

[msg MSG_069_0_0 [Ms. Toriumi]]
[f 2 1][bup 1581 0 65535 65535 0 0][vp 3 0 65535 15809 0 0][f 5 21 0 100][clr 2]Exams start on Monday[clr 27]. Have you guys been studying? I'm the one who takes the fall if you don't score well, you know.[n][w][e]
[f 2 1][bup 1581 0 65535 65535 0 0][f 5 21 0 100]Open your textbooks for today's lesson on... incorrect use of the plural form.[n][w][e]
[f 2 1][bup 1581 0 65535 65535 0 0][f 5 21 0 100]These can trip up a lot of people.[n][w][e]
[f 2 1][bup 1581 0 65535 65535 0 0][f 5 21 0 100]The most common forms end in "-s," "-es," and "-ies."[n][w][e]
[f 2 1][bup 1581 0 65535 65535 0 0][f 5 21 0 100]Got it?[n][w][e]

[msg MSG_070_0_0 [Ms. Toriumi]]
[f 2 1][bup 1581 2 65535 65535 0 0][vp 3 0 65535 15822 0 0][f 5 21 0 100]However, there are some irregular plural forms too.[n][w][e]
[f 2 1][bup 1581 0 65535 65535 0 0][f 5 21 0 100]You seem confused, Iori-kun.[n][w][e]
[f 2 1][bup 1581 0 65535 65535 0 0][f 5 21 0 100]Do you know which of the following is an irregular plural noun?[n][w][e]

[msg MSG_071_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 65535 65535 0 0][vp 3 0 65535 2098 0 0][f 5 21 0 150]Wha—? Huh? Me!? Ugh... I wasn't listening at all.[n][w][e]

[msg MSG_072_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][f 5 21 0 150]...[nf], help me out, man![n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0][f 5 21 0 150]Did you catch what she said? Do you know the answer?[n][w][e]

[sel SEL_073_0_0 top]
[f 2 1]Wishes.[f 5 20 45 0][e]
[f 2 1]Lives.[f 2 9 1 0 13][f 5 20 45 1][e]
[f 2 1]Dreams.[f 5 20 45 2][e]

[msg MSG_074_0_0 [Ms. Toriumi]]
[f 2 1][bup 1581 0 65535 65535 0 0][vp 3 0 65535 15842 0 0][f 5 21 0 100]Oh, so you were listening. You've got a funny way of showing it, though...[n][w][e]

[msg MSG_075_0_0 [Ms. Toriumi]]
[f 2 1][bup 1581 2 65535 65535 0 0][vp 3 0 65535 15843 0 0][f 5 21 0 100]Wrong! The answer is "Lives."[n][w][e]
[f 2 1][bup 1581 2 65535 65535 0 0][f 5 21 0 100]Stop daydreaming and pay attention![n][w][e]

[msg MSG_076_0_0 [Ms. Toriumi]]
[f 2 1][bup 1581 0 65535 65535 0 0][f 5 21 0 100]Like most singular nouns, you can add an "-s" to "dream" to form "dreams."[n][w][e]
[f 2 1][bup 1581 0 65535 65535 0 0][f 5 21 0 100]Since "wish" ends in an "-sh," you have to add "-es" to get its plural form: "wishes."[n][w][e]
[f 2 1][bup 1581 0 65535 65535 0 0][f 5 21 0 100]Okay, on to the next one...[n][w][e]

[msg MSG_077_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][f 5 21 0 150]Man... I sure wish they'd stop calling me out...[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2042 0 0][f 5 21 0 150]...Thanks, [nf]. You're a real homie.[n][w][e]

[msg MSG_078_0_0 [Classmate]]
[f 2 1][nl]-chan really got Junpei out of a pinch just now. She's such a nice girl![n][w][e]

[msg MSG_079_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2092 0 0][f 5 21 0 150]"Daydreaming"...? I guess I was, but you gotta get your head outta the clouds, too, man.[n][w][e]

