[msg MSG_000_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 102 65535 0 0][vp 1 0 0 1 0 0]Huh? Are the other girls not up yet?[n][w][e]
[f 2 1][bup 3 1 102 65535 0 0][vp 1 0 0 2 0 0]Man, those sleepyheads! The ocean's not gonna sit around and wait for us, y'know?[n][w][e]

[msg MSG_001_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 102 65535 0 0][vp 1 0 0 3 0 0]Once the sun sets, the water temperature drops, tiring you out much faster.[n][w][e]

[msg MSG_002_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 102 65535 0 0][vp 1 0 0 4 0 0]Huh? Uhh, I guess. That's really what you're worried about?[n][w][e]

[msg MSG_003_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 102 65535 0 0][vp 1 0 0 5 0 0]Junpei, that reminds me.[n][w][e]
[f 2 1][bup 4 0 102 65535 0 0][vp 1 0 0 6 0 0]Didn't one of the maids give you something as we were leaving?[n][w][e]

[msg MSG_004_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 102 65535 0 0][vp 1 0 0 7 0 0]Heheh, you saw that, huh?[n][w][e]
[f 2 1][bup 3 1 102 65535 0 0][vp 1 0 0 8 0 0]One of the maids gave me a letter. Oh man, what if it's a confession of love!?[n][w][e]
[f 2 1][bup 3 1 102 65535 0 0][vp 1 0 0 9 0 0][f 4 21 3 7]Ahh, it sure is tough, bein' this popular![n][w][e]

[msg MSG_005_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 3 102 65535 0 0][vp 1 0 0 10 0 0]...You're a moron.[n][w][e]

[msg MSG_006_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 102 65535 0 0][vp 1 0 0 11 0 0]Okay, let's see here...[n][w][e]
[f 2 1][bup 3 0 102 65535 0 0][vp 1 0 0 12 0 0]It says, "We've gone to see the Jomon Cedar Tree."[n][w][e]
[f 2 1][bup 3 4 102 65535 0 0][vp 1 0 0 13 0 0][f 4 23 0 1 4 25 25]Huh?[n][w][e]

[msg MSG_007_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 102 65535 0 0][vp 1 0 0 14 0 0]This looks like Yamagishi's handwriting.[n][w][e]

[msg MSG_008_0_0 [Junpei Iori]]
[f 2 1][bup 3 2 102 65535 0 0][vp 1 0 0 15 0 0]Aw, man![n][w][e]
[f 2 1][bup 3 2 102 65535 0 0][vp 1 0 0 16 0 0]We're at an island resort in the middle of summer! Why aren't they going to the beach!?[n][w][e]
[f 2 1][bup 3 2 102 65535 0 0][vp 1 0 0 17 0 0]That's just not right![n][w][e]

[msg MSG_009_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 102 65535 0 0][vp 1 0 0 18 0 0]Well, it is your fault.[n][w][e]

[msg MSG_010_0_0 [Junpei Iori]]
[f 2 1][bup 3 3 102 65535 0 0][vp 1 0 0 19 0 0]Whaddaya mean? I just wanted to lighten the mood yesterday.[n][w][e]

[msg MSG_011_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 102 65535 0 0][vp 1 0 0 20 0 0]I don't want to hear it.[n][w][e]

[msg MSG_012_0_0 [Junpei Iori]]
[f 2 1][bup 3 2 102 65535 0 0][vp 1 0 0 21 0 0]Well, it doesn't matter now, anyways...[n][w][e]
[f 2 1][bup 3 2 102 65535 0 0][vp 1 0 0 22 0 0]We're on our own![n][w][e]
[f 2 1][bup 3 2 102 65535 0 0][vp 1 0 0 23 0 0]This is the frontier of romance! We're bound to meet someone new out here![n][w][e]

[msg MSG_012_5_0 [Junpei Iori]]
[f 2 1][cut 3 12 0][e]

[msg MSG_013_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 102 65535 0 0][vp 1 0 0 24 0 0]We'll call this: Operation Yakushima Beach Fling![n][w][e]

[msg MSG_014_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 102 65535 0 0][vp 1 0 0 25 0 0]Fling...?[n][w][e]
[f 2 1][bup 4 0 102 65535 0 0][vp 1 0 0 26 0 0]You mean we're gonna pick up girls?[n][w][e]

[msg MSG_015_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 102 65535 0 0][vp 1 0 0 27 0 0]How 'bout it, Sanada-san? With you on the squad, we're guaranteed to succeed![n][w][e]

[msg MSG_016_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 3 102 65535 0 0][vp 1 0 0 28 0 0]I should've known this was your plan.[n][w][e]

[msg MSG_017_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 102 65535 0 0][vp 1 0 0 29 0 0][nl], what do you think about this?[n][w][e]

[sel SEL_018_0_0 top]
[f 2 1]Let's begin the operation.[e]
[f 2 1]Sounds like a hassle.[e]
[f 2 1]I don't care.[e]

[msg MSG_019_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 102 65535 0 0][vp 1 0 0 30 0 0]You're right, it does sound like a hassle.[n][w][e]

[msg MSG_020_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 102 65535 0 0][vp 1 0 0 31 0 0]Whaaat? Don't tell me you wanna spend the whole day with just us three![n][w][e]
[f 2 1][bup 3 4 102 65535 0 0][vp 1 0 0 32 0 0]Come on, guys! It'll be fun![n][w][e]

[msg MSG_021_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 102 65535 0 0][vp 1 0 0 33 0 0]You two really wanna let this opportunity to enjoy our summer vacation go to waste?[n][w][e]
[f 2 1][bup 3 4 102 65535 0 0][vp 1 0 0 34 0 0]Come on, guys! It'll be fun![n][w][e]

[msg MSG_022_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 102 65535 0 0][vp 1 0 0 35 0 0]Then I'm appointing her our leader, as usual.[n][w][e]

[msg MSG_023_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 102 65535 0 0][vp 1 0 0 36 0 0]What!? WHY!?[n][w][e]

[msg MSG_024_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 102 65535 0 0][vp 1 0 0 37 0 0]You said it yourself: this is an operation.[n][w][e]

[msg MSG_025_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 102 65535 0 0][vp 1 0 0 38 0 0]Aw, man, that's bullshit![n][w][e]

[msg MSG_026_0_0 [Junpei Iori]]
[f 2 1][bup 3 2 102 65535 0 0][vp 1 0 0 39 0 0]You better take this seriously, [nf]. It's an important operation.[n][w][e]

