[msg MSG_SENDER_NAME]
[f 2 1]Yukari Takeba[n][w][e]

[msg MSG_001_0_0]
[f 2 1]Are you free today?[n][w][e]

[msg MSG_002_0_0]
[f 2 1]Wanna walk home together?[n][f 1 5 0]Hit me up if you do.[n][w][e]

[msg MSG_003_0_0]
[f 2 1]You're totally bored, right?[n][w][e]

[msg MSG_004_0_0]
[f 2 1]Just kidding! [f 1 3 158][n][f 1 5 0]Sorry! Did you get mad? [f 1 3 143][n][f 1 5 0]Let's go home together.[n][w][e]

[msg MSG_005_0_0]
[f 2 1]Hey[n][w][e]

[msg MSG_006_0_0]
[f 2 1]Wanna drop by the [f 1 3 150] together on the way back?[n][w][e]

[msg MSG_007_0_0]
[f 2 1]Heyyy[n][w][e]

[msg MSG_008_0_0]
[f 2 1]Are you free today?[n][f 1 5 0]Let's hang out somewhere before heading back.[n][w][e]

[msg MSG_009_0_0]
[f 2 1](No Subject)[n][w][e]

[msg MSG_010_0_0]
[f 2 1]Sorry to dump this on you so suddenly, but there's something I want to talk about.[n][f 1 5 0]Can we meet after school?[n][w][e]

[msg MSG_011_0_0]
[f 2 1]Are you hungry?[n][w][e]

[msg MSG_012_0_0]
[f 2 1]I didn't have lunch today [f 1 3 138][n][f 1 5 0]I wanna eat a proper meal.[n][f 1 5 0]Do you wanna come with?[n][w][e]

[msg MSG_013_0_0]
[f 2 1]Any plans today?[n][w][e]

[msg MSG_014_0_0]
[f 2 1]Wanna go home together? [f 1 3 156][n][f 1 5 0]Lemme know if you do.[n][w][e]

[msg MSG_015_0_0]
[f 2 1]Hey...[n][w][e]

[msg MSG_016_0_0]
[f 2 1][nl]-chan, there's something I have to ask you. If you have the time, could we meet after school?[n][w][e]

[msg MSG_017_0_0]
[f 2 1]Hey [f 1 3 137][n][w][e]

[msg MSG_018_0_0]
[f 2 1]Did you fall asleep in class? I'm keeping an eye on you, missy! [f 1 3 136][n][f 1 5 0]Anyway, let's head home together.[n][w][e]

[msg MSG_019_0_0]
[f 2 1]How's it going?[n][w][e]

[msg MSG_020_0_0]
[f 2 1]Have you been eating properly?[n][f 1 5 0]Sorry, was that a weird question? [f 1 3 138][n][f 1 5 0]Anyway, are you free after school?[n][w][e]

[msg MSG_021_0_0]
[f 2 1]You're free, right?[n][w][e]

[msg MSG_022_0_0]
[f 2 1]You are, right? [f 1 3 137][n][f 1 5 0]Wanna head back to the dorm together? I'll be waiting in the classroom after school.[n][w][e]

[msg MSG_023_0_0]
[f 2 1]Just wondering[n][w][e]

[msg MSG_024_0_0]
[f 2 1]Do you have some time to spare today? Wanna walk back together?[n][w][e]

[msg MSG_025_0_0]
[f 2 1]Yukari here[n][w][e]

[msg MSG_026_0_0]
[f 2 1]Are you doing anything today? Wanna walk home together?[n][w][e]

[msg MSG_027_0_0]
[f 2 1]Yukari here[n][w][e]

[msg MSG_028_0_0]
[f 2 1]Are you free today?[n][w][e]

[msg MSG_029_0_0]
[f 2 1]You free today?[n][w][e]

[msg MSG_030_0_0]
[f 2 1]Since we have the day off, I was thinking of going somewhere [f 1 3 140][n][f 1 5 0]Do you wanna join me? Just lemme know![n][w][e]

[msg MSG_031_0_0]
[f 2 1]Wanna watch a movie? [f 1 3 151][n][w][e]

[msg MSG_032_0_0]
[f 2 1]I was supposed to go with a friend, but she couldn't make it today. [f 1 3 138][n][f 1 5 0]I'd rather not go alone, so I figured we could go together.[n][f 1 5 0]I hear the plot really makes you think! [f 1 3 139][n][w][e]

[msg MSG_033_0_0]
[f 2 1]You free tonight?[n][w][e]

[msg MSG_034_0_0]
[f 2 1]There's going to be a festival at Naganaki Shrine! [f 1 3 140][n][f 1 5 0]They don't hold festivals there very often, so I'm thinking about dressing up for it...[n][f 1 5 0]Do you wanna go together?[n][w][e]

[msg MSG_035_0_0]
[f 2 1]Guess what day it is![n][w][e]

[msg MSG_036_0_0]
[f 2 1]Hehe, I just wanted to say that for fun. [f 1 3 140][n][f 1 5 0]I know I don't usually say these kinda things, but since it's a pretty special day, I thought maybe we could spend it together like how other people do. [f 1 3 154][n][w][e]

[msg MSG_037_0_0]
[f 2 1]About Koro-chan[n][w][e]

[msg MSG_038_0_0]
[f 2 1]He really likes to lie down out at the dorm's front entrance, huh? [f 1 3 137] But it doesn't seem like he's just lazing around...[n][f 1 5 0][nl]-chan, if you see him out there, could you check in on him? [f 1 3 157][n][w][e]

