[msg MSG_000_0_0 [Teacher]]
[f 2 1][vp 1 0 0 1 0 0][f 5 21 0 3]All right, Odagiri, I'm counting on you. For both our sakes.[n][w][e]

[msg MSG_001_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 2 0 0]I understand.[n][w][e]

[msg MSG_002_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 3 65535 65535 0 0][vp 1 0 0 3 0 0]Oh, [nl]-san...[n][w][e]

[msg MSG_003_0_0 [Secretary]]
[f 2 1][vp 1 0 0 4 0 0][f 5 21 0 4]Hey, Odagiri! What was that about? What did he mean by "for both our sakes"?[n][w][e]

[msg MSG_004_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 5 0 0]He just wants to create a better school environment, so he simply asked a student fit for the job.[n][w][e]

[msg MSG_004_5_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 6 0 0]Just like how the president asked her to join the student council to help out.[n][w][e]

[msg MSG_005_0_0 [Secretary]]
[f 2 1][vp 1 0 0 7 0 0][f 5 21 0 4]What!? You can't decide something like that without talking to the president first![n][w][e]

[sel SEL_006_0_0 top]
[f 2 1]What happened?[e]
[f 2 1]No need to fight.[e]

[msg MSG_007_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 3 65535 65535 0 0][vp 1 0 0 8 0 0]Someone found a cigarette butt in the boys' bathroom.[n][w][e]
[f 2 1][bup 109 3 65535 65535 0 0][vp 1 0 0 9 0 0]And that teacher wants the disciplinary committee to look into whose it was.[n][w][e]

[msg MSG_008_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 10 0 0]Someone has broken school rules. It's only natural that I'm involved in finding and holding the transgressor accountable.[n][w][e]

[msg MSG_009_0_0 [Secretary]]
[f 2 1][vp 1 0 0 11 0 0][f 5 21 0 4]I wouldn't be so nonchalant about this if I were you, [nl].[n][w][e]

[msg MSG_010_0_0 [Secretary]]
[f 2 1][vp 1 0 0 12 0 0][f 5 21 0 4]There was a cigarette found in the boys' bathroom... And in his eyes it doesn't matter if it's you or me. We're all suspects![n][w][e]

[msg MSG_011_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 2 65535 65535 0 0][vp 1 0 0 13 0 0]Quite the exaggeration. I'm not a crime scene investigator. I'm a member of the disciplinary committee.[n][w][e]

[msg MSG_012_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 14 0 0]Look, you have two choices. Either help out and prove you can be trusted, or refuse and prove you can't.[n][w][e]

[msg MSG_012_5_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 3 65535 65535 0 0][vp 1 0 0 15 0 0][f 5 13 5 5 102]People like you and me have to deal with a lot of crap around here, don't we, [nl]-kun?[n][w][e]

[msg MND_013_0_0]
[f 2 1]Odagiri seems to have[n]high expectations of me.[n][w][e]
[f 2 1]I feel like we're becoming better friends.[n][w][e]

[msg MSG_014_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 16 0 0]Well then, I'll be excusing myself.[n][w][e]

[msg MSG_015_0_0 [Secretary]]
[f 2 1][vp 1 0 0 17 0 0][f 5 21 0 4]H-Hey! Don't ignore me! You kiss-ass![n][w][e]

[msg MSG_016_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 3 65535 65535 0 0][vp 1 0 0 18 0 0]Student council members shouldn't be fighting like this, should they?[n][w][e]
[f 2 1][bup 109 3 65535 65535 0 0][vp 1 0 0 19 0 0]I better go tell the president![n][w][e]

[msg MND_017_0_0]
[f 2 1]My work is done here, so I'll head home.[n][w][e]

