[msg MSG_000_0_0 [Bebe]]
[f 2 1][bup 112 0 65535 65535 0 0][vp 3 0 65535 11810 0 0]I am feeling a little hungry. Shall we get something to—[n][w][e]

[msg MSG_000_5_0 [Bebe]]
[f 2 1][bup 112 1 65535 65535 0 0]Oh my! This wonderful fragrance![n][w][e]

[msg MSG_001_0_0 [Bebe]]
[f 2 1][bup 112 1 65535 65535 0 0]Just as I thought! It is takoyaki![n][w][e]
[f 2 1][bup 112 3 65535 65535 0 0][f 4 23 0 112 3 25 25]Hmmm, I would like to buy some, but...[n][w][e]
[f 2 1][bup 112 3 65535 65535 0 0]But I would prefer to first try takoyaki from its origin—in Osaka.[n][w][e]

[msg MSG_002_0_0 [Bebe]]
[f 2 1][bup 112 1 65535 65535 0 0][vp 3 0 65535 11876 0 0]...I know! We can go there now! It is just a train ride away, is it not?[n][w][e]

[sel SEL_003_0_0 top]
[f 2 1]Sure, let's go.[e]
[f 2 1]What a hassle...[e]
[f 2 1]Just get it here.[e]

[msg MSG_004_0_0 [Bebe]]
[f 2 1][bup 112 1 65535 65535 0 0][vp 3 0 65535 11894 0 0][f 5 13 15 30 112]Many thanks—katajikenai! Then let us prepare for the journ—[n][w][e]
[f 2 1][bup 112 4 65535 65535 0 0][f 4 23 0 112 4 25 25][f 4 25 112]...Ah.[n][w][e]
[f 2 1][bup 112 3 65535 65535 0 0][f 4 23 0 112 3 25 25]I had forgotten I am low on funds... My deepest apologies, [nf]-sama.[n][w][e]

[msg MND_005_0_0]
[f 2 1]Bebe looks disappointed...[n][w][e]
[f 2 1]I feel like we became a lot closer today.[n][w][e]

[msg MSG_006_0_0 [Bebe]]
[f 2 1][bup 112 3 65535 65535 0 0][vp 3 0 65535 11902 0 0]Ah, alas...[n][w][e]
[f 2 1][bup 112 3 65535 65535 0 0]If you do not wish to go, then I shall forgo this dream. It would be too lonely to journey alone...[n][w][e]

[msg MND_007_0_0]
[f 2 1]Bebe looks dejected...[n][w][e]
[f 2 1]I feel like we didn't get any closer today...[n][w][e]

[msg MSG_008_0_0 [Bebe]]
[f 2 1][bup 112 3 65535 65535 0 0][vp 3 0 65535 11902 0 0][f 5 13 15 5 112]Alas...[n][w][e]
[f 2 1][bup 112 0 65535 65535 0 0][f 4 23 0 112 0 25 25]I suppose I must accept defeat this time.[n][w][e]
[f 2 1][bup 112 0 65535 65535 0 0]To tell you the truth, my funds have... ah, run dry. I do not believe I can make a trip...[n][w][e]

[msg MND_009_0_0]
[f 2 1]Bebe looks embarrassed...[n][w][e]
[f 2 1]I learned a little more about him today...[n][w][e]

[msg MSG_010_0_0 [Bebe]]
[f 2 1][bup 112 1 65535 65535 0 0][vp 3 0 65535 11908 0 0]I would still like to go to Osaka one day. When the time comes, I ask that you be my guide, [nf]-sama![n][w][e]
[f 2 1][bup 112 1 65535 65535 0 0]Now then... Let us march! To Octopia! Onwards![n][w][e]

[msg MND_011_0_0]
[f 2 1]After talking with Bebe over takoyaki,[n]I headed back to the dorm.[n][w][e]

