[msg MSG_000_0_0 [Keisuke Hiraga]]
[f 2 1][bup 108 0 65535 65535 0 0][vp 3 0 65535 11261 0 0]Lately, I've been reading all these autobiographies by famous people...[n][w][e]

[msg MSG_001_0_0 [Keisuke Hiraga]]
[f 2 1][bup 108 0 65535 65535 0 0]They were all so successful in life. I wonder what they were like at my age...[n][w][e]
[f 2 1][bup 108 0 65535 65535 0 0]I've been thinking about that a lot recently...[n][w][e]

[msg MSG_002_0_0 [Keisuke Hiraga]]
[f 2 1][bup 108 2 65535 65535 0 0]I hate my dad! First he tells me to quit the club... Now he tells me to go study abroad![n][w][e]
[f 2 1][bup 108 2 65535 65535 0 0][vp 3 0 65535 11291 0 0]This is all his fault! Why does he keep changing his mind!?[n][w][e]

[sel SEL_003_0_0 top]
[f 2 1]You're right.[e]
[f 2 1]You shouldn't blame others.[e]
[f 2 1]I don't really care.[e]

[msg MSG_004_0_0 [Keisuke Hiraga]]
[f 2 1][bup 108 0 65535 65535 0 0][vp 3 0 65535 11272 0 0][f 5 13 11 15 108]Sorry... I'm embarrassed by the way I'm acting...[n][w][e]
[f 2 1][bup 108 0 65535 65535 0 0]You don't have to agree with me all the time, you know. You can tell me when I'm wrong...[n][w][e]

[msg MND_005_0_0]
[f 2 1]Hiraga seems to be thinking[n]about what he said.[n][w][e]
[f 2 1]I learned a little more about him today.[n][w][e]

[msg MSG_006_0_0 [Keisuke Hiraga]]
[f 2 1][bup 108 0 65535 65535 0 0][vp 3 0 65535 11222 0 0][f 5 13 11 30 108]...Somehow, you always manage to see the core of the problem.[n][w][e]
[f 2 1][bup 108 0 65535 65535 0 0]Yeah... Deep down, I know that you're right. I shouldn't say things like that.[n][w][e]

[msg MND_007_0_0]
[f 2 1]Hiraga seems impressed by my words.[n][w][e]
[f 2 1]I feel like we became a lot closer today.[n][w][e]

[msg MSG_008_0_0 [Keisuke Hiraga]]
[f 2 1][bup 108 3 65535 65535 0 0][vp 3 0 65535 11269 0 0]B-But... I've been telling you all this because it's you, [nl]-chan...[n][w][e]
[f 2 1][bup 108 3 65535 65535 0 0]...But I was in the wrong. I'm just venting without considering your feelings... That isn't right.[n][w][e]

[msg MND_009_0_0]
[f 2 1]Hiraga seems depressed.[n][w][e]
[f 2 1]I feel like we didn't get any closer today...[n][w][e]

[msg MSG_010_0_0 [Keisuke Hiraga]]
[f 2 1][bup 108 0 65535 65535 0 0][vp 3 0 65535 11243 0 0]...Sorry. I didn't mean to have a conversation like this when I invited you here.[n][w][e]
[f 2 1][bup 108 0 65535 65535 0 0]Why don't we get some cake? I'll treat you.[n][w][e]
[f 2 1][bup 108 0 65535 65535 0 0]Speaking of sweets, the human brain requires 20% of the glucose derived from the body's metabolism process to function properly...[n][w][e]

[msg MND_011_0_0]
[f 2 1]The two of us hung out for a while longer[n]before I decided to go back to the dorm.[n][w][e]

