[msg MSG_000_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 156 65535 0 0][vp 1 0 0 1 0 0]Oh, I'm so glad there are other people here wearing yukatas.[n][w][e]

[msg MSG_000_5_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 156 65535 0 0][vp 1 0 0 2 0 0]Um, I don't stand out too much, do I?[n][w][e]
[f 2 1][bup 6 0 156 65535 0 0][vp 1 0 0 3 0 0]I usually don't wear this kind of clothing, so I'm feeling a little uncomfortable...[n][w][e]

[sel SEL_001_0_0 top]
[f 2 1]You look great.[e]
[f 2 1]Don't worry about it.[e]

[msg MSG_002_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 156 65535 0 0][vp 1 0 0 4 0 0][f 5 13 3 15 6]R-Really?[n][w][e]
[f 2 1][bup 6 11 156 65535 0 0][vp 1 0 0 5 0 0][f 4 23 0 6 1 25 25]...Thank you.[n][w][e]

[msg MSG_003_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 156 65535 0 0][vp 1 0 0 6 0 0][f 5 13 3 5 6]You're right.[n][w][e]
[f 2 1][bup 6 1 156 65535 0 0][vp 1 0 0 7 0 0]I tend to worry too much about what other people think.[n][w][e]
[f 2 1][bup 6 1 156 65535 0 0][vp 1 0 0 8 0 0]Thank you.[n][w][e]

[msg MSG_004_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 156 65535 0 0][vp 1 0 0 9 0 0]You know, wearing this has made me think. Yukatas are so light and airy.[n][w][e]
[f 2 1][bup 6 0 156 65535 0 0][vp 1 0 0 10 0 0]They're perfect for the humid summers we have here in Japan.[n][w][e]

[msg MSG_004_5_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 156 65535 0 0][vp 1 0 0 11 0 0]Yukatas look so simple at first glance, but they're actually very elegantly-designed.[n][w][e]

[msg MSG_005_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 4 156 65535 0 0][vp 0 0 0 12 0 0]......[n][w][e]
[f 2 1][bup 6 3 156 65535 0 0][vp 1 0 0 13 0 0][f 4 23 0 6 3 25 25]Sorry, I guess that's not really what people talk about at a festival, huh?[n][w][e]

[msg MSG_006_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 156 65535 0 0][vp 1 0 0 14 0 0]U-Umm...[n][w][e]
[f 2 1][bup 6 1 156 65535 0 0][vp 1 0 0 15 0 0][f 4 23 0 6 1 25 25]Oh, it's about time for dinner.[n][w][e]
[f 2 1][bup 6 1 156 65535 0 0][vp 1 0 0 16 0 0]Let's get something to eat from one of the food stalls.[n][w][e]

[msg MSG_007_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 156 65535 0 0][vp 1 0 0 17 0 0]Excuse me, may I have one order of takoyaki, please?[n][w][e]

[msg MSG_008_0_0 [Takoyaki Vendor]]
[f 2 1][vp 1 0 0 18 0 0][f 5 21 0 10]Ya sure can![n][w][e]

[msg MSG_009_0_0 [Takoyaki Vendor]]
[f 2 1][vp 1 0 0 19 0 0]...Here you go, one order of takoyaki![n][w][e]
[f 2 1][vp 1 0 0 20 0 0]I threw in an extra one for ya. I hope you and your girlfriend enjoy it![n][w][e]

[msg MSG_010_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 4 156 65535 1 0][vp 1 0 0 21 0 0]Oh, um, thank you...[n][w][e]

[msg MSG_011_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 156 65535 0 0][vp 1 0 0 22 0 0]She gave us an extra piece of takoyaki.[n][w][e]
[f 2 1][bup 6 1 156 65535 0 0][vp 1 0 0 23 0 0][f 4 23 0 6 1 25 25]I guess we should eat then, [nl]-chan.[n][w][e]

[msg MSG_012_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 4 156 65535 0 0][vp 0 0 0 24 0 0]...![n][w][e]

[msg MSG_013_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 156 65535 0 0][vp 1 0 0 25 0 0]It's a little too hot for me to eat it whole, but...[n][w][e]
[f 2 1][bup 6 1 156 65535 0 0][vp 1 0 0 26 0 0]But it's so good![n][w][e]

[msg MSG_013_5_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 156 65535 0 0][vp 1 0 0 27 0 0]It tastes just like the takoyaki at Octopia, doesn't it?[n][w][e]
[f 2 1][bup 6 0 156 65535 0 0][vp 0 0 0 28 0 0][f 4 23 0 6 0 25 25]......[n][w][e]

[msg MSG_014_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 156 65535 0 0][vp 1 0 0 29 0 0]Wait a minute... Do you think she's the same person?[n][w][e]
[f 2 1][bup 6 0 156 65535 0 0][vp 0 0 0 30 0 0]......[n][w][e]
[f 2 1][bup 6 0 156 65535 0 0][vp 1 0 0 31 0 0]Maybe they're twins...[n][w][e]

[msg MSG_015_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 156 65535 0 0][vp 1 0 0 32 0 0]Look at those masks.[n][w][e]

[msg MSG_015_3_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 156 65535 0 0][vp 1 0 0 33 0 0]There are animal ones too.[n][w][e]
[f 2 1][bup 6 0 156 65535 0 0][vp 1 0 0 34 0 0][f 4 23 0 6 0 25 25]There's a cat, a dog, and... an octopus?[n][w][e]

[msg MSG_015_5_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 156 65535 0 0][vp 1 0 0 35 0 0]Oh, it's actually a hyottoko mask. So it's a man's face, not an animal.[n][w][e]
[f 2 1][bup 6 1 156 65535 0 0][vp 1 0 0 36 0 0]These masks really set the mood for the festival, don't you think?[n][w][e]

[msg MSG_016_0_0 [Game Attendant]]
[f 2 1][vp 1 0 0 37 0 0][f 5 21 0 11]Hey, you two! Wanna try your hand at a lucky draw?[n][w][e]
[f 2 1][vp 1 0 0 38 0 0][f 5 21 0 11]Make some nice memories, whaddaya say? Odds are lookin' good—lots of winning tickets left![n][w][e]

[msg MSG_017_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 156 65535 0 0][vp 1 0 0 39 0 0]A lucky draw, huh.[n][w][e]
[f 2 1][bup 6 1 156 65535 0 0][vp 1 0 0 40 0 0][f 4 23 0 6 1 25 25]...Maybe we should give it a shot.[n][w][e]
[f 2 1][bup 6 0 156 65535 0 0][vp 1 0 0 41 0 0]But I'm not very lucky, so I think you should do it, [nl]-chan.[n][w][e]

[msg MND_018_0_0]
[f 2 1]The box is filled with[n]triangular lottery tickets...[n][w][e]

[sel SEL_019_0_0 top]
[f 2 1]Pick from the top[e]
[f 2 1]Dig down to the bottom[e]

[msg MSG_020_0_0 [Game Attendant]]
[f 2 1][vp 1 0 0 42 0 0][f 5 21 0 11]Congratulations, you won![n][w][e]
[f 2 1][vp 1 0 0 43 0 0][f 5 21 0 11]Wow, you must have incredible luck to win on your first try![n][w][e]
[f 2 1][vp 1 0 0 44 0 0][f 5 21 0 11]Here is your prize. Enjoy![n][w][e]

[msg MND_021_0_0]
[f 2 1]DEV:(Item name) received.[n][w][e]

[msg MSG_022_0_0 [Game Attendant]]
[f 2 1][vp 1 0 0 45 0 0][f 5 21 0 11]Congratulations, you won![n][w][e]
[f 2 1][vp 1 0 0 46 0 0][f 5 21 0 11]Wow, you must have incredible luck to win on your first try![n][w][e]
[f 2 1][vp 1 0 0 47 0 0][f 5 21 0 11]Here's your prize. Enjoy![n][w][e]

[msg MND_023_0_0]
[f 2 1]DEV: (Item name) received.[n][w][e]

[msg MSG_024_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 156 65535 0 0][vp 1 0 0 48 0 0]You actually won!? That's amazing, [nl]-chan![n][w][e]

[msg MSG_025_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 156 65535 0 0][vp 1 0 0 49 0 0]...We've been here for quite some time.[n][w][e]
[f 2 1][bup 6 1 156 65535 0 0][vp 1 0 0 50 0 0]We should probably get going. Thank you for today.[n][w][e]

[msg MSG_025_5_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 156 65535 0 0][vp 1 0 0 51 0 0]I've actually never had a chance to go to one of these before.[n][w][e]
[f 2 1][bup 6 1 156 65535 0 0][vp 1 0 0 52 0 0]...It was a lot of fun.[n][w][e]

[msg MND_026_0_0]
[f 2 1]I decided to go back to the dorm.[n][w][e]

