[msg MSG_000_0_0 [Punk]]
[f 2 1][vp 1 0 0 1 0 0][f 5 21 0 11]The hell are these guys?[n][w][e]

[msg MSG_001_0_0 [Punk's Buddy]]
[f 2 1][vp 1 0 0 2 0 0][f 5 21 0 12]Check out those rags. They're from Gekkou High.[n][w][e]

[msg MSG_002_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 65535 65535 0 0][vp 1 0 0 3 0 0]Oh man, this is even worse than I thought.[n][w][e]

[msg MSG_003_0_0 [Punk]]
[f 2 1][vp 1 0 0 4 0 0][f 5 21 0 11]You musta taken a wrong turn, 'cause this place ain't for you, buddy.[n][w][e]

[msg MSG_004_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 65535 65535 0 0][vp 1 0 0 5 0 0]Uh... Well, I...[n][w][e]

[msg MSG_005_0_0 [Punk]]
[f 2 1][vp 1 0 0 6 0 0][f 5 21 0 11]What I'm saying is, you being here is ruinin' our vibe.[n][w][e]
[f 2 1][vp 1 0 0 7 0 0][f 5 21 0 11]Beat it, Goatee![n][w][e]

[msg MSG_006_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 65535 65535 0 0][vp 1 0 0 8 0 0]Goatee?[n][w][e]

[msg MSG_006_5_0 [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0][vp 1 0 0 9 0 0]Oh, y-you mean me.[n][w][e]

[msg MSG_007_0_0 [Yukari Takeba]]
[f 2 1][bup 2 2 65535 65535 0 0][vp 1 0 0 10 0 0]We don't need your permission to be here.[n][w][e]

[msg MSG_008_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 65535 65535 0 0][vp 1 0 0 11 0 0]H-Hey! Are you nuts!?[n][w][e]
[f 2 1][bup 3 4 65535 65535 0 0][vp 1 0 0 12 0 0]Read the room, won't you!?[n][w][e]

[msg MSG_009_0_0 [Yukari Takeba]]
[f 2 1][bup 2 2 65535 65535 0 0][vp 1 0 0 13 0 0]I can read just fine.[n][w][e]
[f 2 1][bup 2 2 65535 65535 0 0][vp 1 0 0 14 0 0]Come on, don't be intimidated by these punks![n][w][e]

[msg MSG_010_0_0 [Punk]]
[f 2 1][vp 1 0 0 15 0 0][f 5 21 0 11]What'd you just say?[n][w][e]

[msg MSG_011_0_0 [Tough Chick]]
[f 2 1][vp 1 0 0 16 0 0][f 5 21 0 13]She just called us punks.[n][w][e]
[f 2 1][vp 1 0 0 17 0 0][f 5 21 0 13]Come on, let's post some pictures that'll make her daddy cry![n][w][e]
[f 2 1][vp 1 0 0 18 0 0][f 5 21 0 13]Hope you've been practicing your sexy poses![n][w][e]

[msg MSG_011_5_0 [Tough Chicks]]
[f 2 1][vp 1 0 0 19 0 0]Hahahahah! Oh boy, that's too good![n][w][e]

[msg MSG_012_0_0 [(SE) Tough Chick]]
[f 2 1][vp 1 0 0 19 0 0]Hahahahah![n][w][e]

[msg MSG_013_0_0 [(SE) Tough Chick's Friend]]
[f 2 1][vp 1 0 0 20 0 0]Hahahahah! Oh boy, that's too good![n][w][e]

[msg MSG_014_0_0 [Yukari Takeba]]
[f 2 1][bup 2 2 65535 65535 0 0][vp 1 0 0 21 0 0]These guys are scum.[n][w][e]

[msg MSG_015_0_0 [Punk]]
[f 2 1][vp 1 0 0 22 0 0][f 5 21 0 11]Oh, so now we're scum, huh?[n][w][e]

[msg MSG_015_5_0 [Punk]]
[f 2 1][vp 1 0 0 23 0 0][f 5 21 0 11]Man, I feel sorry for you, Goatee. This bitch is a real pain in the ass, isn't she!?[n][f 1 2 165][e]

[msg MSG_016_0_0 [Junpei Iori]]
[f 2 1][bup 3 5 65535 65535 0 0][vp 1 0 0 24 0 0]Guh! Urgh...[n][w][e]

[msg MSG_017_0_0 [Yukari Takeba]]
[f 2 1][bup 2 4 65535 65535 0 0][vp 1 0 0 25 0 0]Junpei![n][w][e]

[msg MSG_018_0_0 [(SE) Punk's Buddy]]
[f 2 1][vp 1 0 0 26 0 0]Ahahahaha![n][w][e]

[msg MSG_019_0_0 [(SE) Punk's Buddy 2]]
[f 2 1]Ahahahaha.[n][w][e]

[msg MSG_020_0_0 [(SE) Tough Chick]]
[f 2 1]Hahahahah![n][w][e]

[msg MSG_021_0_0 [(SE) Tough Chick's Friend]]
[f 2 1]Hahahahah![n][w][e]

[msg MSG_022_0_0 [Familiar Voice]]
[f 2 1][vp 1 0 0 30 0 0]That's enough.[n][w][e]

[msg MSG_023_0_0 [Guy from the Other Day]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 1 0 0 31 0 0]They didn't know what they were getting into. I'll make sure they leave.[n][w][e]
[f 2 1][bup 10 0 65535 65535 0 0][vp 1 0 0 32 0 0]You good with that?[n][w][e]

[msg MSG_024_0_0 [Punk]]
[f 2 1][vp 1 0 0 33 0 0][f 5 21 0 11]Who do you think you are, dumbass?[n][w][e]

[msg MSG_024_5_0 [Punk]]
[f 2 1][vp 1 0 0 34 0 0][f 5 21 0 11]They're not walkin' outta this! You want some too!?[n][w][e]

[msg MSG_025_0_0 [Punk]]
[f 2 1][vp 1 0 0 35 0 0][f 5 21 0 11]Urgh... Shit![n][w][e]
[f 2 1][vp 1 0 0 36 0 0][f 5 21 0 11]Son of a bitch... You just crossed the line! You think you're goin' home alive now!?[n][w][e]

[msg MSG_026_0_0 [Guy from the Other Day]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 1 0 0 37 0 0]Should we find out?[n][w][e]

[msg MSG_027_0_0 [Punk]]
[f 2 1][vp 1 0 0 38 0 0][f 5 21 0 11]Uh...[n][w][e]

[msg MSG_027_3_0 [Punk]]
[f 2 1][vp 1 0 0 39 0 0][f 5 21 0 11]N-No, maybe not...[n][w][e]

[msg MSG_028_0_0 [Tough Chicks]]
[f 2 1][vp 1 0 0 40 0 0]Hahahahaha! Oh man, what a loser![n][w][e]

[msg MSG_028_5_0 [(SE) Tough Chick]]
[f 2 1][vp 1 0 0 40 0 0]Hahahahaha! Oh man, what a loser![n][w][e]

[msg MSG_029_0_0 [(SE) Tough Chick's Friend]]
[f 2 1][vp 1 0 0 41 0 0]Hahahahaha![n][w][e]

[msg MSG_030_0_0 [Punk's Buddy]]
[f 2 1][vp 1 0 0 42 0 0][f 5 21 0 12]Bastard... Your name's Aragaki, right?[n][w][e]
[f 2 1][vp 1 0 0 43 0 0][f 5 21 0 12]Yeah, now I remember. Shinjiro Aragaki! You're from Gekkou High too, aren't you!?[n][w][e]

[msg MSG_031_0_0 [Punk]]
[f 2 1][vp 1 0 0 44 0 0][f 5 21 0 11]Dammit, you're gonna regret this![n][w][e]

[msg MSG_032_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 1 0 0 45 0 0]Oh man, Senpai, that was awesome![n][w][e]

[msg MSG_033_0_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 4 65535 65535 0 0][vp 1 0 0 46 0 0][f 4 27 0 0]I remember you. You guys were in Aki's room at the hospital.[n][w][e]

[msg MSG_033_5_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 2 65535 65535 0 0][vp 1 0 0 47 0 0]You idiots![n][w][e]

[msg MSG_034_0_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 1 0 0 48 0 0]Go home. You don't belong here.[n][w][e]

[msg MSG_035_0_0 [Yukari Takeba]]
[f 2 1][bup 2 2 65535 65535 0 0][vp 1 0 0 49 0 0]Wait![n][w][e]

[msg MSG_035_5_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 50 0 0]Sorry, but there's something we need to know before we leave![n][w][e]

[msg MSG_036_0_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 1 0 0 51 0 0]Did Aki tell you to come here?[n][w][e]

[sel SEL_037_0_0 top]
[f 2 1]Yeah, sort of.[e]
[f 2 1]No.[e]

[msg MSG_038_0_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 1 0 0 52 0 0]That dumbass.[n][w][e]

[msg MSG_039_0_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 0 0 0 53 0 0]Hmph.[n][w][e]

[msg MSG_040_0_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 1 0 0 54 0 0]Well, what do you wanna know? Is this about that ghost story?[n][w][e]

[msg MSG_041_0_0 [Yukari Takeba]]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 55 0 0]Yes, that's right. How'd you know?[n][w][e]

[msg MSG_042_0_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 1 0 0 56 0 0]The rumor's been going around.[n][w][e]
[f 2 1][bup 10 0 65535 65535 0 0][vp 1 0 0 57 0 0]Those girls who wound up in the hospital were here talkin' shit every night.[n][w][e]
[f 2 1][bup 10 0 65535 65535 0 0][vp 1 0 0 58 0 0]They'd brag about all the stuff they did to some girl named Yamagishi.[n][w][e]

[msg MSG_043_0_0 [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0][vp 1 0 0 59 0 0]Yamagishi? You mean Fuuka Yamagishi, from 2-E? They were picking on her?[n][w][e]

[msg MSG_044_0_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 1 0 0 60 0 0]That's why people are sayin' it's Yamagishi's ghost that did it.[n][w][e]

[msg MSG_045_0_0 [Yukari Takeba]]
[f 2 1][bup 2 2 65535 65535 0 0][vp 1 0 0 61 0 0]Yamagishi-san's ghost? Wait, what do you mean by that!?[n][w][e]

[msg MSG_046_0_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 1 0 0 62 0 0]You guys don't know?[n][w][e]

[msg MSG_046_5_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 1 0 0 63 0 0]This Yamagishi girl might be dead.[n][w][e]

[msg MSG_047_0_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 1 0 0 64 0 0]I heard she hasn't been home in over a week.[n][w][e]

[msg MSG_048_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 1 0 0 65 0 0]Wait, what? I thought she was just out recovering.[n][w][e]
[f 2 1][bup 3 4 65535 65535 0 0][vp 1 0 0 66 0 0][f 4 23 0 3 4 25 25]So, you mean she's still missing!?[n][w][e]

[msg MSG_049_0_0 [Yukari Takeba]]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 67 0 0]So much for that ghost story.[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 68 0 0][f 4 23 0 2 0 25 25]Mr. Ekoda is the homeroom teacher for 2-E, right? Does he know about this?[n][w][e]

[msg MSG_050_0_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 1 0 0 69 0 0]I get it, Aki. Still trying to make up for the past.[n][w][e]
[f 2 1][bup 10 0 65535 65535 0 0][vp 1 0 0 70 0 0]Hmph. It's you who can't let go.[n][w][e]

[msg MSG_051_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 0 0 0 71 0 0]...?[n][w][e]

[msg MSG_052_0_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 1 0 0 72 0 0]Nothing.[n][w][e]
[f 2 1][bup 10 0 65535 65535 0 0][vp 1 0 0 73 0 0]Anyways, that's all I know. We done here?[n][w][e]

[msg MSG_053_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 65535 65535 0 0][vp 1 0 0 74 0 0]Yeah, totally! Thanks a lot![n][w][e]

[msg MSG_054_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 1 0 0 75 0 0]C'mon, show some appreciation![n][w][e]

[sel SEL_055_0_0 top]
[f 2 1]Thank you very much.[e]
[f 2 1]You really saved us.[e]
[f 2 1]We didn't need your help.[e]

[msg MSG_056_0_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 1 0 0 76 0 0]I didn't do nothin'.[n][w][e]

[msg MSG_057_0_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 1 0 0 77 0 0]Just don't come around here again.[n][w][e]

[msg MSG_058_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 65535 65535 0 0][vp 1 0 0 78 0 0]Huh!? The hell d'you mean!? We were in deep shit just now![n][w][e]

[msg MND_058_5_0]
[f 2 1]I don't have the [f 4 30 2 1 1 0][n]to say this right now.[n][w][e]
[f 2 1]Maybe I could say stuff like this without[n]hesitation if only I was [f 4 31 2 5 1 0]...[n][w][e]

[msg MSG_059_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 79 0 0]Thank you for helping us, and for sharing what you know.[n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 80 0 0][f 4 23 0 2 1 25 25]That was really nice of you.[n][w][e]

[msg MSG_060_0_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 1 0 0 81 0 0]Huh?[n][w][e]

[msg MSG_061_0_0 [Yukari Takeba]]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 82 0 0]Oh, uh, sorry...[n][w][e]

[msg MSG_062_0_0 [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 1 0 0 83 0 0]...Just don't come here again.[n][w][e]

