[msg SYS_PERSONA_DROP]
[f 2 1]Are you sure you want to release [clr 35][f 2 4 0][clr 27]?[n][f 1 4 1][w][e]

[msg SYS_PERSONA_DROP_NG]
[f 2 1]You cannot release a Persona that is currently equipped.[n][w][e]

[msg SYS_PERSONA_SET]
[f 2 1]Equip this Persona?[n][f 1 4 1][w][e]

[msg SYS_PERSONA_EQUIPED]
[f 2 1][clr 35][f 2 4 0][clr 27] is already equipped.[n][w][e]

[msg SYS_SKILL_FULL]
[f 2 1]This Persona cannot learn any more skills. Please choose one to forget.[n][w][e]

[msg SYS_SKILL_FORGET]
[f 2 1]Forget [clr 35][f 2 4 0][clr 27]?[n][f 1 4 1][w][e]

[msg SYS_BIRTH_CONCEPTION]
[f 2 1][clr 35][f 2 4 0][clr 27] created [f 4 4 1 37 1 1].[n][w][e]

[msg SYS_SKILLCARD_ALREADY]
[f 2 1][clr 35][f 2 4 0][clr 27] has already been learned.[n][w][e]

[msg SYS_SKILL_CHANGE [Igor]]

[msg SYS_REMEMBER_CONF]
[f 2 1]Are you sure you want to exit?[n][f 1 4 1][w][e]

[msg SYS_NO_EFFECT_INCENSE]
[f 2 1]The limit has already been reached.[n][w][e]

[msg SYS_SYSTEM_BACK_TO_TITLE]
[f 2 1]Return to the title screen?[n][f 1 4 1][w][e]

[msg SYS_TITL_USE_NETWORK]
[f 2 1][f 1 4 1]This game supports online features when connected to the network. Would you like to enable these features now?[n][w][e]

[msg SYS_TITL_DONT_USE_NETWOR]
[f 2 1]Network functionality has been turned [clr 2]OFF[clr 27]. You can change this at any time from the Config menu.[n][w][e]

[msg SYS_SAVE_LOAD_CHECK]
[f 2 1]Load this save data?[n][f 1 4 1][w][e]

[msg SYS_SAVE_LOAD_OK [Igor]]

[msg SYS_SAVE_NETWORK_LOAD]
[f 2 1]Loading network save data...[n][w][e]

[msg SYS_SAVE_NETWORK_LOAD_OK]
[f 2 1]Network save data has been successfully loaded.[n][w][e]

[msg SYS_SAVE_NETWORK_LOAD_ER]
[f 2 1]Network save data could not be loaded.[n][w][e]

[msg SYS_SAVE_NETWORK_UP]
[f 2 1]Uploading save data...[n][w][e]

[msg SYS_SAVE_NETWORK_UP_OK]
[f 2 1]Save data has been successfully uploaded.[n][w][e]

[msg SYS_SAVE_NETWORK_UP_ERRO]
[f 2 1]Save data could not be uploaded.[n][w][e]

[msg SYS_SAVE_NETWORK_BROKEN]
[f 2 1]Network save data is corrupted.[n][w][e]

[msg SYS_SAVE_NETWORK_INVALID]
[f 2 1]Network functionality is currently disabled. You can change this setting from the Config menu.[n][w][e]

[msg SYS_SAVE_NETWORK_NOTEXIS]
[f 2 1]There is no save data on the network.[n][w][e]

[msg SYS_SAVE_OVERWRITE_CHECK]
[f 2 1]Save data already exists. Do you want to overwrite this data?[n][f 1 4 1][w][e]

[msg SYS_SAVE_OK [Igor]]

[msg SYS_SAVE_ROLLBACK_CHECK]
[f 2 1]If you return to this point, any more recent rewind data will be lost. Continue?[n][f 1 4 1][w][e]

[msg SYS_CONF_CLOSE_CHECK]
[f 2 1]Exit without applying changes?[n][f 1 4 1][w][e]

[msg SYS_CONF_DIFF_CHECK]
[f 2 1]If you change the difficulty from Merciless, you won't be able to change it back. Are you sure you want to proceed?[n][f 1 4 1][w][e]

[msg SYS_CONF_DIFF_CHANGED]
[f 2 1]The difficulty level has been changed to [clr 2][f 2 4 0][clr 27].[n][w][e]

[msg SYS_CONF_CONNECT_ERROR]
[f 2 1]Network connection failed.[n][w][e]

[msg SYS_CONF_CONNECTING]
[f 2 1]Connecting to the network...[n][w][e]

[msg SYS_PARTY_MEMBEROVER_0_0]
[f 2 1]You are [f 2 4 0] member(s) over max party size.[n][w][e]

[msg SYS_DIFFICULTY_CHECK]
[f 2 1]Begin the game at [clr 2][f 2 4 0][clr 27] difficulty?[n][f 1 4 1][w][e]

[msg SYS_DIFFICULTY_DESC_SAFE]
[f 2 1]For players who want to focus on the story.[n][w][e]

[msg SYS_DIFFICULTY_DESC_EASY]
[f 2 1]For casual players.[n][w][e]

[msg SYS_DIFFICULTY_DESC_NORM]
[f 2 1]For experienced players.[n][w][e]

[msg SYS_DIFFICULTY_DESC_HARD]
[f 2 1]For players who enjoy strategizing.[n][w][e]

[msg SYS_DIFFICULTY_DESC_LUNA]
[f 2 1]For highly advanced players.[n][w][e]

[msg SYS_DIFFICULTY_INFO_SAFE]
[f 2 1]Your party auto-revives after defeat. [clr 43]Your choice of difficulty will not affect the story and can be changed at any time (excluding Merciless).[clr 27][n][w][e]

[msg SYS_DIFFICULTY_INFO_EASY]
[f 2 1]Low-stress combat. [clr 43]Your choice of difficulty will not affect the story and can be changed at any time (excluding Merciless).[clr 27][n][w][e]

[msg SYS_DIFFICULTY_INFO_NORM]
[f 2 1]Moderately challenging combat. [clr 43]Your choice of difficulty will not affect the story and can be changed at any time (excluding Merciless).[clr 27][n][w][e]

[msg SYS_DIFFICULTY_INFO_HARD]
[f 2 1]Significantly challenging combat. [clr 43]Your choice of difficulty will not affect the story and can be changed at any time (excluding Merciless).[clr 27][n][w][e]

[msg SYS_DIFFICULTY_INFO_LUNA]
[f 2 1]Exceedingly challenging combat. [clr 43]Your choice of difficulty will not affect the story and can be changed at any time, but you cannot return to Merciless once leaving it.[clr 27][n][w][e]

[msg MND_SKILL_NOT_CHANGE]
[f 2 1](Not used) [f 2 4 2] gave a sharp cry.[n][w][e]

[msg SYS_NETWORK_CONNECT_CHEC [Igor]]

[msg SYS_NETWORK_CONNECT_YES]
[f 2 1]Network functionality has been turned [clr 2]ON[clr 27]. You can change this at any time from the Config menu.[n][w][e]

[msg SYS_NETWORK_CONNECT_NO [Igor]]

[msg SYS_NETWORK_VOICE_ERROR]
[f 2 1]Network error. Please check your connection.[n][w][e]

[msg MSG_SKILL_CHANGE [Igor]]
[f 2 1]Oh...? A skill seems to be on the verge of changing... Will you see this through?[n][w][e]

[sel SEL_SKILL_CHANGE top]
[f 2 1]Prevent skill change[e]
[f 2 1]Accept skill change[e]
[f 2 1]Check skills[e]

[msg SYS_PARTY_FIXED_MEMBER_0]
[f 2 1][f 2 4 0] must be in your party.[n][w][e]

[msg SYS_RECHECK_BACK_TO_TITL]
[f 2 1]You will lose all progress made from the last time you saved up to this point. Are you sure you want to return to the title screen?[n][f 1 4 1][w][e]

[msg SYS_GAMEDATA_INSTALL]
[f 2 1]Installing game data...[n][w][e]

[msg SYS_GAMEDATA_INSTALL_OK]
[f 2 1]Installation complete.[n][w][e]

[msg SYS_ACTIVITY_DATA_NOT_MA]
[f 2 1]The selected activity did not match the state of the latest save data. The game will start normally.[n][w][e]

[msg SYS_KEYCONFIG_ASSIGN]
[f 2 1]Enter a key to bind to [clr 35][f 2 4 0][clr 27]. Press Esc to return to the settings menu.[n][w][e]

[msg SYS_KEYCONFIG_OVERWRITE]
[f 2 1]There is a conflict with the following key binding: [clr 2][f 2 4 0][clr 27][n][f 1 5 0]Overwrite the existing key binding?[n][f 1 5 0][f 1 4 1][w][e]

[msg SYS_KEYCONFIG_FINISH]
[f 2 1]Finish with current settings?[n][f 1 4 1][w][e]

[msg SYS_KEYCONFIG_NOT_SET]
[f 2 1]Some configurations have not been set.[n][w][e]

[msg SYS_KEYCONFIG_RESET_KEYB]
[f 2 1]Restore keyboard configuration to default settings?[n][f 1 4 1][w][e]

[msg SYS_KEYCONFIG_RESET_MOUS]
[f 2 1]Restore mouse configuration to default settings?[n][f 1 4 1][w][e]

[msg SYS_KEYCONFIG_RESET_GAME]
[f 2 1]Restore gamepad configuration to default settings?[n][f 1 4 1][w][e]

[msg SYS_CONF_DISPLAY_CHECK]
[f 2 1]Display settings have been adjusted. Do you wish to keep these changes? (Settings will revert in [f 2 4 0] seconds.)[n][f 1 4 1][w][e]

[msg SYS_INPUT_DEVICE_LOST]
[f 2 1]A device was disconnected. Please check the status of the connection.[n][w][e]

[msg SYS_SAVE_NO_SPACE]
[f 2 1]Save failed. Please check available system storage space.[n][w][e]

[msg SYS_APP_QUIT]
[f 2 1]Exit the game?[n][f 1 4 1][w][e]

[msg SYS_APPLY_INIT_NAME_STOR]
[f 2 1]Due to a change in language settings, the protagonist's name will default to "Kotone Shiomi". To restore the original name, the language must match the one that was set when the name was entered.[n][w][e]

[msg SYS_APPLY_INIT_NAME_NETW]
[f 2 1]Due to a change in language settings, the protagonist's name will default to "Kotone Shiomi". To restore the original name, the language must match the one that was set when the name was entered.[n][w][e]

