[msg MSG_000_0_0 [Classmate's Voice]]
[f 2 1][vp 1 0 0 1 0 0][f 5 21 0 1]Hey, did you hear about that girl in 2-E?[n][w][e]

[msg MSG_001_0_0 [Classmate's Voice]]
[f 2 1][vp 1 0 0 2 0 0][f 5 21 0 2]Yeah, I heard they have no idea what happened.[n][w][e]

[msg MSG_002_0_0 [Classmate's Voice]]
[f 2 1][vp 1 0 0 3 0 0][f 5 21 0 1]Oh my god, isn't it so bizarre?[n][w][e]

[msg MSG_003_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 1 0 0 4 0 0]Man, everyone's talkin' about it. People sure got a lotta time on their hands.[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0][vp 1 0 0 5 0 0]So, you hear about it too?[n][w][e]

[sel SEL_004_0_0 top]
[f 2 1]About what?[e]
[f 2 1]I'm not interested.[e]

[msg MSG_005_0_0 [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0][vp 1 0 0 6 0 0]Pfft, what, you think you one of them cool city slickers?[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0][vp 1 0 0 7 0 0][f 4 23 0 3 0 25 25]C'mon, you gotta keep up with stuff like this.[n][w][e]

[msg MSG_006_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 1 0 0 8 0 0]A girl from 2-E went missing while she was out late last night.[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0][vp 1 0 0 9 0 0]And this morning, they found her lying in front of the school gate![n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0][vp 1 0 0 10 0 0]Nobody knows what happened, and supposedly she's still unconscious.[n][w][e]

[msg MSG_007_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 11 0 0]Morning.[n][w][e]

[msg MSG_008_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 1 0 0 12 0 0]Yo, Yuka-tan.[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0][vp 1 0 0 13 0 0]Man, this is a tough case, even for Junpei Iori, Ace Detective.[n][w][e]

[msg MSG_009_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 14 0 0]Ace Detective?[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 15 0 0]You're so dumb.[n][w][e]

[msg MSG_009_3_0 [Yukari Takeba]]
[f 2 1][bup 2 3 65535 65535 0 0][vp 0 0 0 16 0 0]......[n][w][e]

[msg MSG_009_5_0 [Yukari Takeba]]
[f 2 1][bup 2 3 65535 65535 0 0][vp 1 0 0 17 0 0]More like Stupei, Ace Defective.[n][w][e]

[msg MSG_010_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 65535 65535 0 0][vp 1 0 0 18 0 0]Where'd that come from!?[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0][vp 1 0 0 19 0 0][f 4 23 0 3 0 25 25]Actually, now that I think about it, I haven't seen you all morning. Where've you been?[n][w][e]

[msg MSG_011_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 20 0 0]I was talking to the teacher.[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 21 0 0]That girl they found... I saw her yesterday, on my way back from practice.[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 22 0 0]She seemed just fine then...[n][w][e]

[msg MSG_012_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 1 0 0 23 0 0]Huh...[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0][vp 1 0 0 24 0 0]The plot thickens...[n][w][e]

