[msg MSG_000_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 0 0 0 1 0 0]......[n][w][e]

[msg MND_001_0_0]
[f 2 1]I feel like my [f 4 30 0 1 1 0][n]have improved thanks to the[n]skillful expression in the writing...[n][w][e]

[msg MSG_002_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 2 0 0]Oh, [nl]-chan. Did you finish reading the final volume?[n][w][e]

[msg MSG_003_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 3 0 0]You looked really focused when you were reading. I can definitely relate.[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 4 0 0]When I got to the end, I was so absorbed that I almost forgot to breathe.[n][w][e]

[msg MSG_004_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 5 0 0]What an amazing series...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 6 0 0]I didn't notice at first, but at some point I could suddenly just make sense of the complex setting. Isn't it weird how that works?[n][w][e]

[sel SEL_005_0_0 top]
[f 2 1]It's like magic.[e]
[f 2 1]It's written well.[e]
[f 2 1]I skipped the complicated parts.[e]

[msg MSG_006_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 7 0 0]Oh, it really does feel that way, doesn't it?[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 8 0 0]They do say advanced technology is indistinguishable from magic. Maybe going in with that mindset makes sci-fi a little less intimidating.[n][w][e]

[msg MSG_007_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 9 0 0]Right. If it was just straight exposition, it would be exhausting trying to keep track of everything.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 10 0 0]Being able to tie the world-building into the narrative really shows how skilled the author is.[n][w][e]

[msg MSG_008_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 11 0 0]Ah, I actually do that a lot too...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 12 0 0][f 4 23 0 6 0 25 25]Sometimes you don't understand it on your first read, but as you continue on, it all starts to come together.[n][w][e]

[msg MSG_009_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 13 0 0]...I wish I could communicate as well as the author does in this book.[n][w][e]

[msg MSG_009_3_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 14 0 0]Remember when I told you how I recommended a book to a classmate, but she turned me down?[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 15 0 0]Knowing what to say is important, but how you say it is difficult too.[n][w][e]

[msg MSG_009_7_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 16 0 0]Before I could tell her how fascinating the story is... I was telling her how many volumes it was and that it's written by a famous author...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 17 0 0]I don't think that kind of information's going to persuade someone to read.[n][w][e]

[sel SEL_010_0_0 top]
[f 2 1]It'll go better next time.[e]
[f 2 1]That's a tough one.[e]

[msg MSG_011_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 18 0 0]...Thanks. Maybe I'll try talking to her again.[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 19 0 0]I think I'll have a lot of good things to say about this book now.[n][w][e]

[msg MSG_012_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 20 0 0]Right. It's so easy to fall back on information like that, like the number of copies sold, or the writer's prestige.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 21 0 0]But if I want to explain how good a story is, I need to start with the emotions it evokes when you read it.[n][w][e]

[msg MSG_013_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 22 0 0]It always feels nice when someone shows an interest in something you like.[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 23 0 0]Even just sharing our opinions like this is so refreshing.[n][w][e]

[msg MSG_013_3_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 24 0 0]That's why I really want to work on how I communicate things.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 25 0 0]Because if I do that, then maybe I'll get more fun moments like this.[n][w][e]

[msg MND_013_5_0]
[f 2 1]Fuuka is nodding with determination.[n][w][e]

[msg MSG_014_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 26 0 0]Oh, look at the time... We should probably call it a night.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 27 0 0]...Um...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 28 0 0]I have some other books I can recommend, if you'd like.[n][w][e]

[msg MSG_015_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 29 0 0][f 5 13 3 1 6]Thank you, [nl]-chan. I hope you'll like those too.[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 30 0 0]Well then, good night.[n][w][e]

