[msg MSG_000_0_0 [Yukari Takeba]]
[f 2 1][bup 2 3 51 65535 0 0][vp 1 0 0 1 0 0]This is it... Right?[n][w][e]

[msg MSG_001_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 51 50 0 0][vp 1 0 0 2 0 0]Can you all hear me?[n][w][e]

[msg MSG_002_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 51 65535 0 0][vp 1 0 0 3 0 0]Yes, loud and clear.[n][w][e]
[f 2 1][bup 2 0 51 65535 0 0][vp 1 0 0 4 0 0]We just got here, but I don't see anything out of the ordinary...[n][w][e]

[msg MSG_003_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 51 50 0 0][vp 1 0 0 5 0 0]The readings are definitely coming from that monorail.[n][w][e]
[f 2 1][bup 5 0 51 50 0 0][vp 1 0 0 6 0 0]Proceed with caution, and stay together.[n][w][e]

[msg MSG_004_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 51 65535 0 0][vp 1 0 0 7 0 0]Got it.[n][w][e]

[msg MSG_005_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 51 65535 0 0][vp 1 0 0 8 0 0]Heheh, my Persona's just itchin' for a fight![n][w][e]

[msg MSG_006_0_0 [Yukari Takeba]]
[f 2 1][bup 2 2 51 65535 0 0][vp 1 0 0 9 0 0]Well then, let's head on in![n][w][e]

[msg MSG_007_0_0 [Yukari Takeba]]
[f 2 1][bup 2 2 51 65535 0 0][vp 1 0 0 10 0 0]...Don't you dare look up.[n][w][e]

[msg MSG_008_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 51 65535 0 0][vp 1 0 0 11 0 0]Yeah, yeah, I won't.[n][w][e]
[f 2 1][bup 3 1 51 65535 0 0][vp 0 0 0 12 0 0][f 4 23 0 1 1 25 25]......[n][w][e]
[f 2 1][bup 3 1 51 65535 0 0][vp 1 0 0 13 0 0]...But don't blame me if I happen to catch a glimpse.[n][w][e]

[msg MSG_009_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 51 65535 0 0][vp 1 0 0 14 0 0]Say, [nl]-chan... Why don't we dig Junpei a nice grave?[n][w][e]

