[msg MSG_000_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 1 0 0]So, you're Fuuka Yamagishi-kun, right?[n][w][e]

[msg MSG_001_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 4 1 65535 0 0][vp 1 0 0 2 0 0]Y-Yes.[n][w][e]

[msg MSG_002_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 1 65535 65535 0 0][vp 1 0 0 3 0 0]Relax, there's no need to be nervous. Go on and have a seat.[n][w][e]

[msg MSG_003_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 1 65535 0 0][vp 1 0 0 4 0 0]Ah... Okay.[n][w][e]

[msg MSG_004_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 1 65535 65535 0 0][vp 1 0 0 5 0 0]I just want to quickly mention that everyone did an excellent job uncovering the truth.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 6 0 0][f 4 23 0 222 0 25 25]Ah, and one other thing to report...[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 7 0 0]I've heard that all three girls have regained consciousness.[n][w][e]

[msg MSG_005_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 1 65535 0 0][vp 1 0 0 8 0 0]That's great news...[n][w][e]

[msg MSG_006_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 9 0 0]From what I understand, they each came to the school around midnight and waited for the security guard to leave.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 10 0 0]Then, once the Dark Hour began, they were attacked by Shadows near the gate.[n][w][e]
[f 2 1][bup 222 1 65535 65535 0 0][vp 1 0 0 11 0 0][f 4 23 0 222 1 25 25]Because of the situation's similarities to an old ghost story, rumors naturally spread quickly.[n][w][e]

[msg MSG_007_0_0 [Yukari Takeba]]
[f 2 1][bup 2 6 1 65535 0 0][vp 1 0 0 12 0 0]I knew right from the beginning that it wasn't a ghost.[n][w][e]

[msg MSG_008_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 1 65535 0 0][vp 1 0 0 13 0 0]It's all my fault.[n][w][e]

[msg MSG_009_0_0 [Yukari Takeba]]
[f 2 1][bup 2 4 1 65535 0 0][vp 1 0 0 14 0 0]What? Where'd you get that from? You were the victim in all this![n][w][e]

[msg MSG_010_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 1 65535 0 0][vp 1 0 0 15 0 0]But all of those rumors started because I was absent for so long.[n][w][e]

[msg MSG_011_0_0 [Yukari Takeba]]
[f 2 1][bup 2 6 1 65535 0 0][vp 1 0 0 16 0 0]That's totally not your fault.[n][w][e]

[msg MSG_012_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 1 65535 0 0][vp 1 0 0 17 0 0]I don't think we could have won that fight if you hadn't been there.[n][w][e]
[f 2 1][bup 5 0 1 65535 0 0][vp 1 0 0 18 0 0]You saved our lives. That's not something just anyone could've done. Take pride in that.[n][w][e]
[f 2 1][bup 5 0 1 65535 0 0][vp 1 0 0 19 0 0]You have a special power that you can use to help others.[n][w][e]

[msg MSG_013_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 1 65535 0 0][vp 1 0 0 20 0 0]A special power?[n][w][e]

[msg MSG_014_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 1 65535 0 0][vp 1 0 0 21 0 0]We call it "Persona."[n][w][e]
[f 2 1][bup 5 0 1 65535 0 0][vp 1 0 0 22 0 0]And right now, our group absolutely needs your abilities. Can we count on you to help us?[n][w][e]

[msg MSG_015_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 4 1 65535 0 0][vp 1 0 0 23 0 0]Are you asking me to join you?[n][w][e]

[msg MSG_016_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 1 65535 0 0][vp 1 0 0 24 0 0]That's right.[n][w][e]

[msg MSG_017_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 1 65535 0 0][vp 1 0 0 25 0 0]Kirijo-senpai...[n][w][e]

[sel SEL_018_0_0 top]
[f 2 1]Only if you want to.[e]
[f 2 1]We won't force you to.[e]

[msg MSG_019_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 4 1 65535 0 0][vp 1 0 0 26 0 0][nl]-chan...[n][w][e]

[msg MSG_020_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 1 65535 0 0][vp 1 0 0 27 0 0]I think you'd make a good addition to the team, too.[n][w][e]

[msg MSG_021_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 4 1 65535 0 0][vp 1 0 0 28 0 0]Sanada-senpai...[n][w][e]

[msg MSG_022_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 1 65535 0 0][vp 1 0 0 29 0 0]You know, we're not trying to pressure you, so if you need some time to think about it...[n][w][e]

[msg MSG_022_5_0 [Yukari Takeba]]
[f 2 1][cut 6 2 0][e]

[msg MSG_023_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 2 1 65535 0 0][vp 1 0 0 30 0 0]I'll do it.[n][w][e]
[f 2 1][bup 6 2 1 65535 0 0][vp 1 0 0 31 0 0]It would be my honor![n][w][e]

[msg MSG_024_0_0 [Yukari Takeba]]
[f 2 1][bup 2 4 1 65535 0 0][vp 1 0 0 32 0 0]What? Are you sure?[n][w][e]
[f 2 1][bup 2 0 1 65535 0 0][vp 1 0 0 33 0 0][f 4 23 0 2 0 25 25]If you do join, you'll have to move into the dorm.[n][w][e]

[msg MSG_025_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 1 65535 0 0][vp 1 0 0 34 0 0]That's fine. I'd rather live here than at home anyway.[n][w][e]

[msg MSG_026_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 1 65535 0 0][vp 1 0 0 35 0 0]Thank you. We really appreciate this.[n][w][e]
[f 2 1][bup 5 0 1 65535 0 0][vp 1 0 0 36 0 0]We'll have the school talk to your parents to resolve any issues.[n][w][e]

[msg MSG_027_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 1 65535 0 0][vp 1 0 0 37 0 0]Okay, thank you.[n][w][e]

[msg MSG_028_0_0 [Yukari Takeba]]
[f 2 1][bup 2 3 1 65535 0 0][vp 1 0 0 38 0 0]Wait a minute. Aren't we dragging her into this a bit fast?[n][w][e]

[msg MSG_029_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 1 65535 0 0][vp 1 0 0 39 0 0]Um, it's okay. Really.[n][w][e]

[msg MSG_030_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 40 0 0]One other topic I'd like to discuss is those special Shadows. We had another encounter this month.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 41 0 0]While we still don't know where they're coming from, I do believe Sanada-kun is right.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 42 0 0]They seem to appear alongside the full moon. This, at least, will help us plan for the future.[n][w][e]

[msg MSG_031_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 1 65535 0 0][vp 1 0 0 43 0 0]So... the next full moon is showtime, huh...[n][w][e]

[msg MSG_032_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 1 65535 0 0][vp 1 0 0 44 0 0]Knowing when to expect them is a big advantage for us.[n][w][e]
[f 2 1][bup 4 0 1 65535 0 0][vp 1 0 0 45 0 0]Now, on the day of the fight, we'll be ready to get in the ring.[n][w][e]

[msg MSG_033_0_0 [Yukari Takeba]]
[f 2 1][bup 2 3 1 65535 0 0][vp 0 0 0 46 0 0]......[n][w][e]

[msg MND_034_0_0]
[f 2 1]We figured out the pattern for[n]when special Shadows appear...[n][w][e]
[f 2 1]Is this what the mysterious[n]boy was trying to tell me?[n][w][e]
[f 2 1]I should start paying attention[n]to the moon's phases...[n][w][e]

