[msg MND_000_0_0]
[f 2 1]The scratching of pencils echoes[n]throughout the art room...[n][w][e]
[f 2 1]It's been so fun that the hours flew by.[n][w][e]

[msg MSG_001_0_0 [Club Advisor]]
[f 2 1][vp 1 0 0 1 0 0][f 5 21 0 200]Everyone. Attention, please![n][w][e]

[msg MSG_002_0_0 [Club Advisor]]
[f 2 1][vp 1 0 0 2 0 0][f 5 21 0 200]I have an announcement, regarding the recent Bay Area art contest...[n][w][e]

[msg MSG_002_5_0 [Club Advisor]]
[f 2 1][vp 1 0 0 3 0 0][f 5 21 0 200]Hiraga-kun's painting was selected for consideration in the final round![n][w][e]

[msg MSG_003_0_0 [Keisuke Hiraga]]
[f 2 1][bup 108 4 65535 65535 0 0][vp 0 0 0 4 0 0]...![n][w][e]

[msg MSG_004_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 5 0 0]Wow![n][w][e]

[msg MSG_005_0_0 [Male Club Member]]
[f 2 1][vp 1 0 0 6 0 0][f 5 21 0 100]Your piece was really good! You might even win![n][w][e]

[msg MSG_006_0_0 [Keisuke Hiraga]]
[f 2 1][bup 108 0 65535 65535 0 0][vp 1 0 0 7 0 0]Please, it's all thanks to my paintbrush. I was lucky to use my dad's quality raccoon-hair one.[n][w][e]
[f 2 1][bup 108 0 65535 65535 0 0][vp 1 0 0 8 0 0]It really helped apply the paint to the canvas, so I'm sure that's the only reason the judges even noticed.[n][w][e]

[sel SEL_007_0_0 top]
[f 2 1]You've got talent.[e]
[f 2 1]You got lucky.[e]

[msg MSG_008_0_0 [Keisuke Hiraga]]
[f 2 1][bup 108 1 65535 65535 0 0][vp 1 0 0 9 0 0][f 5 13 11 15 108]Th-Thank you, [nl]-chan![n][w][e]

[msg MSG_009_0_0 [Keisuke Hiraga]]
[f 2 1][bup 108 0 65535 65535 0 0][vp 1 0 0 10 0 0]But I've only been painting for about two years now, so I never imagined my piece would go so far.[n][w][e]

[msg MSG_010_0_0 [Keisuke Hiraga]]
[f 2 1][bup 108 0 65535 65535 0 0][vp 1 0 0 11 0 0]Y-Yeah, you're probably right, [nl]-chan.[n][w][e]

[msg MSG_011_0_0 [Keisuke Hiraga]]
[f 2 1][bup 108 0 65535 65535 0 0][vp 1 0 0 12 0 0]I mean, I've only been painting for two years now, so I had to have gotten lucky.[n][w][e]

[msg MSG_012_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 13 0 0]You should have more confidence in yourself. You've been practicing so hard.[n][w][e]

[msg MSG_013_0_0 [Male Club Member]]
[f 2 1][vp 1 0 0 14 0 0][f 5 21 0 100]She's right. Everyone knows how late you stay.[n][w][e]

[msg MSG_014_0_0 [Keisuke Hiraga]]
[f 2 1][bup 108 0 65535 65535 0 0][vp 1 0 0 15 0 0]Thanks, guys. But I should be supporting all of you, not the other way around.[n][w][e]

[msg MSG_014_5_0 [Keisuke Hiraga]]
[f 2 1][bup 108 0 65535 65535 0 0][vp 1 0 0 16 0 0]I'm sorry, [nl]-chan. I should be setting a better example for new members like you.[n][w][e]
[f 2 1][bup 108 1 65535 65535 0 0][vp 1 0 0 17 0 0][f 4 23 0 1 1 25 25]I may not be much of an artist or a leader, but I hope we can keep working to improve our skills together.[n][w][e]

[msg MND_015_0_0]
[f 2 1]I can feel a sense of solidarity with Hiraga...[n][w][e]
[f 2 1]I feel like we're becoming better friends.[n][w][e]

[msg MSG_016_0_0 [Keisuke Hiraga]]
[f 2 1][bup 108 1 65535 65535 0 0][vp 1 0 0 18 0 0]I've come this far... I might as well continue this for as long as I can.[n][w][e]

[msg MSG_016_5_0 [Keisuke Hiraga]]
[f 2 1][bup 108 0 65535 65535 0 0][vp 1 0 0 19 0 0]Oh, look at the time. Time to head home, everyone.[n][w][e]

[msg MND_017_0_0]
[f 2 1]I cleaned up and went back to the dorm.[n][w][e]

