[msg MSG_000_0_0 [Bebe]]
[f 2 1][bup 112 0 65535 65535 0 0][vp 1 0 0 1 0 0]The azuki desserts here are amazing. Red bean is so oishii![n][w][e]
[f 2 1][bup 112 1 65535 65535 0 0][vp 1 0 0 2 0 0][f 4 23 0 1 1 25 25]I love the culture of Nihon! Japan is sugoi—amazing![n][w][e]

[sel SEL_001_0_0 top]
[f 2 1]It sure is![e]
[f 2 1]What about your country?[e]
[f 2 1]It's not that great.[e]

[msg MSG_002_0_0 [Bebe]]
[f 2 1][bup 112 1 65535 65535 0 0][vp 1 0 0 3 0 0][f 5 13 15 15 112]Yes! You understand![n][w][e]

[msg MSG_002_3_0 [Bebe]]
[f 2 1][bup 112 1 65535 65535 0 0][vp 1 0 0 4 0 0]Japanese culture is number one—ichiban! I am so happy I came here![n][w][e]

[msg MSG_003_0_0 [Bebe]]
[f 2 1][bup 112 3 65535 65535 0 0][vp 1 0 0 5 0 0]My home has delicious food too, but...[n][w][e]
[f 2 1][bup 112 1 65535 65535 0 0][vp 1 0 0 6 0 0][f 4 23 0 1 1 25 25]Japanese sweets are so good! I am in love—daisuki![n][w][e]

[msg MSG_003_5_0 [Bebe]]
[f 2 1][bup 112 1 65535 65535 0 0][vp 1 0 0 7 0 0]Japanese culture is number one—ichiban! I am so happy I came here![n][w][e]

[msg MSG_004_0_0 [Bebe]]
[f 2 1][bup 112 3 65535 65535 0 0][vp 1 0 0 8 0 0]You don't think so? But I think you should be proud to live in Nihon![n][w][e]

[msg MSG_004_5_0 [Bebe]]
[f 2 1][bup 112 1 65535 65535 0 0][vp 1 0 0 9 0 0]Japanese culture is number one—ichiban! I am so happy I came here![n][w][e]

[msg MSG_005_0_0 [Bebe]]
[f 2 1][bup 112 0 65535 65535 0 0][vp 1 0 0 10 0 0]I want to learn everything about Nihon and become Japanese![n][w][e]
[f 2 1][bup 112 1 65535 65535 0 0][vp 1 0 0 11 0 0][f 4 23 0 1 1 25 25]Thank you for joining me today, [nf]-sama! I won't forget your kindness![n][w][e]

[msg MSG_005_3_0 [Bebe]]
[f 2 1][bup 112 0 65535 65535 0 0][vp 1 0 0 12 0 0]I have an aunt who lives back home. She has been helping me.[n][w][e]
[f 2 1][bup 112 1 65535 65535 0 0][vp 1 0 0 13 0 0][f 4 23 0 1 1 25 25]I have to tell her that I've made a wonderful new tomodachi![n][w][e]

[msg MND_006_0_0]
[f 2 1]Bebe seems really grateful.[n][w][e]
[f 2 1]I feel like we're growing closer...[n][w][e]

[msg MSG_007_0_0 [Bebe]]
[f 2 1][bup 112 4 65535 65535 0 0][vp 1 0 0 14 0 0]Ohh, look at the time![n][w][e]
[f 2 1][bup 112 3 65535 65535 0 0][vp 1 0 0 15 0 0][f 4 23 0 1 3 25 25]But I wanted to ask you more about Nihon... I must dream a bit longer, I suppose.[n][w][e]

[msg MSG_008_0_0 [Bebe]]
[f 2 1][bup 112 1 65535 65535 0 0][vp 1 0 0 16 0 0]We'll continue our Japanese adventure another time! See you later, [nf]-sama![n][w][e]

[msg MSG_009_0_0 [Bebe]]
[f 2 1][bup 112 1 65535 65535 0 0][vp 1 0 0 17 0 0]We'll continue our Japanese adventure another time! Peace out, [nf]-sama![n][w][e]

[msg MSG_010_0_0 [Bebe]]
[f 2 1][bup 112 1 65535 65535 0 0][vp 1 0 0 18 0 0]We'll continue our Japanese adventure another time! Until we meet again, [nf]-sama![n][w][e]

[msg MSG_011_0_0 [Bebe]]
[f 2 1][bup 112 1 65535 65535 0 0][vp 1 0 0 19 0 0]We'll continue our Japanese adventure another time! I'll be back, [nf]-sama![n][w][e]

[msg MND_012_0_0]
[f 2 1]I parted ways with Bebe[n]and went back to the dorm.[n][w][e]

