[msg MND_000_0_0]
[f 2 1]It's the last day of our school trip...[n][w][e]
[f 2 1]We'll be leaving Kyoto by bullet train[n]this afternoon. I'm free until then.[n][w][e]

[msg MSG_001_0_0 [Ms. Toriumi]]
[f 2 1][bup 1581 0 65535 65535 0 0][vp 1 0 0 1 0 0]Okay, everyone! You all remember when we're meeting at Kyoto Station, right?[n][w][e]
[f 2 1][bup 1581 0 65535 65535 0 0][vp 1 0 0 2 0 0]You better make sure you're on time. If any one of you is late, I'm the one who pays the price.[n][w][e]

[msg MSG_002_0_0 [Junpei Iori]]
[f 2 1][bup 3 3 2 65535 0 0][vp 1 0 0 3 0 0]Welp, I'm never gonna forget Kyoto.[n][w][e]
[f 2 1][bup 3 3 2 65535 0 0][vp 1 0 0 4 0 0]Not like I could, even if I wanted to...[n][w][e]

[msg MSG_003_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 3 2 65535 0 0][vp 0 0 0 5 0 0][f 4 25 1]......[n][w][e]

[msg MSG_004_0_0 [Ryoji Mochizuki]]
[f 2 1][bup 221 3 65535 65535 0 0][vp 1 0 0 6 0 0]You weren't kidding about the whole execution thing...[n][w][e]

[msg MSG_005_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 3 2 65535 0 0][vp 1 0 0 7 0 0]Just try to forget about it.[n][w][e]

[msg MSG_006_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 2 65535 0 0][vp 1 0 0 8 0 0]Crap, here they come![n][w][e]

[msg MSG_007_0_0 [Yukari Takeba]]
[f 2 1][bup 2 3 2 65535 0 0][vp 0 0 0 9 0 0][f 4 25 2]......[n][w][e]

[msg MSG_008_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 2 65535 0 0][vp 0 0 0 10 0 0][f 4 25 4]......[n][w][e]

[msg MSG_009_0_0 [Aigis]]
[f 2 1][bup 7 0 2 65535 0 0][vp 0 0 0 11 0 0][f 4 25 3]......[n][w][e]

[msg MSG_010_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 2 65535 0 0][vp 1 0 0 12 0 0]Not a word, huh...[n][w][e]

[msg MSG_011_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 2 2 65535 0 0][vp 1 0 0 13 0 0]Look out, it's Mitsuru![n][w][e]
[f 2 1][bup 4 5 2 65535 0 0][vp 1 0 0 14 0 0][f 4 23 0 1 12 25 25]Brace yourselves![n][w][e]

[msg MND_012_0_0]
[f 2 1]......[n][w][e]
[f 2 1]Mitsuru walked passed them,[n]with not a single glance in their direction.[n][w][e]

[msg MSG_013_0_0 [Junpei Iori]]
[f 2 1][bup 3 3 2 65535 0 0][vp 1 0 0 15 0 0]Damn, not even a dirty look![n][w][e]

