[msg MSG_001_0_0 [Woman in a Good Mood]]
[f 2 1][f 5 21 1 692]Guys who can drive are so cool! I end up watching them instead of the scenery outside...[n][w][e]
[f 2 1][f 5 21 1 692]...Sorry, but I'm here with my boyfriend, I can't spare anymore of my time.[n][w][e]

[msg MSG_004_0_0 [Woman in a Good Mood]]
[f 2 1][f 5 21 1 692]We should get going or we might not make it in time...[n][w][e]
[f 2 1][f 5 21 1 692]I wanted to surprise my boyfriend, so I booked a fancy dinner for us![n][w][e]

