[msg MSG_000_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 2 65535 0 0][vp 1 0 0 1 0 0]Uh... Hey.[n][w][e]
[f 2 1][bup 2 0 2 65535 0 0][vp 1 0 0 2 0 0]Want to walk home together?[n][w][e]

[sel SEL_001_0_0 top]
[f 2 1]Alright![e]
[f 2 1]Why?[e]
[f 2 1]It might start rumors.[e]

[msg MSG_002_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 2 65535 0 0][vp 1 0 0 3 0 0]We live in the same dorm and all, and I've been a little worried.[n][w][e]

[msg MSG_003_0_0 [Yukari Takeba]]
[f 2 1][bup 2 3 2 65535 0 0][vp 1 0 0 4 0 0]Well... I'm a little worried.[n][w][e]

[msg MSG_004_0_0 [Yukari Takeba]]
[f 2 1][bup 2 4 2 65535 0 0][vp 0 0 0 5 0 0]Huh!?[n][w][e]
[f 2 1][bup 2 3 2 65535 0 0][vp 1 0 0 6 0 0][f 4 23 0 1 3 25 25]Come on, there's no need to put on a brave face.[n][w][e]

[msg MSG_005_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 2 65535 0 0][vp 1 0 0 7 0 0]What if you pass out again on the way home?[n][w][e]
[f 2 1][bup 2 0 2 65535 0 0][vp 1 0 0 8 0 0]I feel responsible for that, you know? Let me make it up to you.[n][w][e]
[f 2 1][bup 2 1 2 65535 0 0][vp 1 0 0 9 0 0][f 4 23 0 1 1 25 25]C'mon, let's go.[n][w][e]

