[msg MND_000_0_0]
[f 2 1]I don't see Miyamoto...[n][w][e]

[msg MSG_001_0_0 [Third-Year Club Member]]
[f 2 1][vp 1 0 0 1 0 0][f 5 21 0 1]Well, we're outta here.[n][w][e]

[msg MSG_002_0_0 [Second-Year Club Member]]
[f 2 1][vp 1 0 0 2 0 0][f 5 21 0 2]Take it easy![n][w][e]

[msg MSG_003_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 101 65535 0 0][vp 1 0 0 3 0 0]Good hustle out there![n][w][e]

[msg MSG_003_5_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 101 65535 0 0][vp 1 0 0 4 0 0]You'd better wrap up too, [nl]-chan. See you next practice![n][w][e]

[msg MND_004_0_0]
[f 2 1]I made my way back to[n]the dorm after practice.[n][w][e]

