[msg MSG_000_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 5 65535 0 0][vp 1 0 0 1 0 0]Nothin' weird about us goin' to the movies together, right? 'Cause this superhero flick's got me pumped![n][w][e]
[f 2 1][bup 3 1 5 65535 0 0][vp 1 0 0 2 0 0][f 4 21 3 7]C'mon, let's go! Ooh, I'm grabbin' some caramel corn![n][w][e]

[msg MSG_900_0_0 [Partner]]
[f 2 1][vp 1 0 0 3 0 0]Just picked up a robbery in progress on the police scanner! It's at a bank five blocks away, big guy![n][w][e]

[msg MSG_901_0_0 [Hero]]
[f 2 1][vp 1 0 0 4 0 0]The cops in this town are a joke. We'd better get moving, stat.[n][w][e]

[msg MSG_902_0_0 [Hero]]
[f 2 1][vp 1 0 0 5 0 0]And, uh, this one of those banks where tons of hot babes hang out?[n][w][e]

[msg MND_001_0_0]
[f 2 1]I watched American heroes save[n]innocent lives from evil forces.[n][w][e]
[f 2 1]I learned how to stand up[n]for freedom and justice![n][w][e]

[msg MSG_002_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 5 65535 0 0][vp 1 0 0 6 0 0]Man... I should've been born in America.[n][w][e]

[msg MSG_002_3_0 [Junpei Iori]]
[f 2 1][bup 3 1 5 65535 0 0][vp 1 0 0 7 0 0]By now, I would've like, saved so many chicks![n][w][e]
[f 2 1][bup 3 9 5 65535 0 0][vp 1 0 0 8 0 0][f 4 23 0 3 9 25 25][f 4 21 3 7]Maybe even the whole freakin' country! And everyone'd be like, "Wow, you're the best, Junpei-Man!"[n][w][e]

[msg MSG_002_5_0 [Junpei Iori]]
[f 2 1][bup 3 1 5 65535 0 0][vp 1 0 0 9 0 0]Don't ya think?[n][w][e]

[msg MSG_003_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 5 65535 0 0][vp 0 0 0 10 0 0]......[n][w][e]

[msg MSG_003_5_0 [Junpei Iori]]
[f 2 1][bup 3 6 5 65535 0 0][vp 1 0 0 11 0 0]Coulda been a whole different life, man...[n][w][e]

[msg MND_004_0_0]
[f 2 1]I went back to the dorm with Junpei.[n][w][e]

