[msg MSG_000_0_0 [Bebe]]
[f 2 1][bup 112 1 65535 65535 0 0][vp 3 0 65535 11899 0 0]Umiushi Bowl... Truly a one-of-a-kind delicacy! So very oishii![n][w][e]

[msg MSG_001_0_0 [Bebe]]
[f 2 1][bup 112 1 65535 65535 0 0]The meat goes so well with the rice! A combination that brings out both flavors![n][w][e]

[msg MSG_002_0_0 [Bebe]]
[f 2 1][bup 112 0 65535 65535 0 0][vp 3 0 65535 11875 0 0]Speaking of rice... What is your favorite dish with it, [nf]-sama?[n][w][e]

[sel SEL_003_0_0 top]
[f 2 1]I don't eat rice.[e]
[f 2 1]Ochazuke.[e]
[f 2 1]Curry.[e]

[msg MSG_004_0_0 [Bebe]]
[f 2 1][bup 112 2 65535 65535 0 0][vp 3 0 65535 11888 0 0]Honto!? Really!? What a shame. How can you be Japanese and not eat rice?[n][w][e]

[msg MND_005_0_0]
[f 2 1]Bebe seems offended.[n][w][e]
[f 2 1]I feel like we didn't get any closer today...[n][w][e]

[msg MSG_006_0_0 [Bebe]]
[f 2 1][bup 112 1 65535 65535 0 0][vp 3 0 65535 11895 0 0][f 5 13 15 30 112]Ah yes! Green tea over rice, ochazuke! A Japanese staple![n][w][e]

[msg MND_007_0_0]
[f 2 1]Bebe seems very happy.[n][w][e]
[f 2 1]I feel like we became a lot closer today.[n][w][e]

[msg MSG_008_0_0 [Bebe]]
[f 2 1][bup 112 0 65535 65535 0 0][vp 3 0 65535 11894 0 0][f 5 13 15 15 112]That is also an excellent dish![n][w][e]
[f 2 1][bup 112 0 65535 65535 0 0]But I think ochazuke is the best. A simple dish, just green tea over rice, but a Japanese staple![n][w][e]

[msg MND_009_0_0]
[f 2 1]Bebe seems happy.[n][w][e]
[f 2 1]I learned a little more about him today.[n][w][e]

[msg MSG_010_0_0 [Bebe]]
[f 2 1][bup 112 0 65535 65535 0 0][vp 3 0 65535 11900 0 0]Of course, I plan to have rice for dinner as well! Nothing beats ochazuke![n][w][e]
[f 2 1][bup 112 0 65535 65535 0 0]But first, I must buy some tea. Will you accompany me?[n][w][e]

[msg MND_011_0_0]
[f 2 1]After shopping with Bebe,[n]I returned to the dorm.[n][w][e]

