[msg MSG_000_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5067 0 0]Oh, [nl]-chan. Good timing![n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0]I was just about to invite Yukari-chan and Junpei-kun to study.[n][w][e]

[msg MSG_000_1_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0]So I was wondering if you'd like to join too.[n][w][e]

[sel SEL_001_0_0 top]
[f 2 1]Let's study together.[e]
[f 2 1]What's everyone's status?[e]
[f 2 1]I want to go to Tartarus.[e]
[f 2 1]No thanks.[e]

[msg MSG_002_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 3 0 65535 5039 0 0]Really? Thanks! I'll go ask the others![n][w][e]

[msg MSG_003_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5094 0 0]Oh... That's too bad. Well, if you feel up for it, just let me know, okay?[n][w][e]

[msg MSG_004_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5067 0 0]Oh, did you change your mind about studying with us?[n][w][e]

[msg MSG_004_1_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0]How about it?[n][w][e]

[sel SEL_005_0_0 top]
[f 2 1]Let's study together.[e]
[f 2 1]I want to go to Tartarus.[e]
[f 2 1]No thanks.[e]

[msg MSG_006_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 3 0 65535 5039 0 0]Really? Thanks! I'll go ask the others![n][w][e]

[msg MSG_007_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5094 0 0]Oh, okay... Well, I'll be here if you change your mind.[n][w][e]

[msg MSG_009_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 4 65535 65535 0 0][vp 3 0 65535 5122 0 0]Oh, well, I don't mind... But some of the others may want to study today.[n][w][e]

[sel SEL_010_0_0 top]
[f 2 1]I still want to go.[e]
[f 2 1]Never mind, then.[e]

[msg MSG_013_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5025 0 0]Everyone can go tonight.[n][w][e]

[msg MSG_014_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0]Can I help you with something else?[n][w][e]

[msg MSG_011_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5028 0 0]All right, then...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]I'll let everyone know. See you later.[n][w][e]

[msg MSG_012_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5116 0 0]I think that's for the best too.[n][w][e]

[msg MND_Temperance]
[f 2 1]Right now, the Temperance Arcana[n]may help me grow even more...[n][w][e]

