[msg MSG_000_0_0 [Stylish Student]]
[f 2 1][f 5 21 1 312]My parents always nag me to, like, study for exams and stuff. They're so annoying![n][w][e]
[f 2 1][f 5 21 1 312]I just became a second-year... I'm supposed to be having fun![n][w][e]
[f 2 1][f 5 21 1 312]They just came into some money, so they're getting all strict about my future and junk.[n][w][e]

[msg MSG_001_0_0 [Stylish Student]]
[f 2 1][f 5 21 1 312]School uniforms are so boring. I wish they'd allow us to wear our own clothes.[n][w][e]
[f 2 1][f 5 21 1 312]Yeah, like that'll happen...[n][w][e]

[msg MSG_002_0_0 [Stylish Student]]
[f 2 1][f 5 21 1 312]My parents are bugging me to choose a college.[n][w][e]
[f 2 1][f 5 21 1 312]Who decides that stuff in their second year? I just started![n][w][e]
[f 2 1][f 5 21 1 312]They say the best way to make God laugh is to make a plan... I bet my parents have made him die laughing.[n][w][e]

[msg MSG_003_0_0 [Stylish Student]]
[f 2 1][f 5 21 1 312]I'm going shopping soon. It's been a while.[n][w][e]

[sel SEL_004_0_0 top]
[f 2 1]What're you buying?[e]
[f 2 1]Is that so.[e]

[msg MSG_005_0_0 [Stylish Student]]
[f 2 1][f 5 21 1 312]I need new clothes. The summer fashions are almost here. You should be get ready too.[n][w][e]

[msg MSG_006_0_0 [Stylish Student]]
[f 2 1][f 5 21 1 312]You don't seem very interested...[n][w][e]

[msg MSG_007_0_0 [Stylish Student]]
[f 2 1][f 5 21 1 312]Everyone's talking about the ghost, and that kind of stuff...[n][w][e]
[f 2 1][f 5 21 1 312]I hate those kinds of stories.[n][w][e]
[f 2 1][f 5 21 1 312]Like how they say the ghost will get you if you stay at school for too long...[n][w][e]
[f 2 1][f 5 21 1 312]...Um, I better get going! See ya![n][w][e]

[msg MSG_008_0_0 [Stylish Student]]
[f 2 1][f 5 21 1 312]Hey, I saw this girl last time, in front of the station...[n][w][e]
[f 2 1][f 5 21 1 312]She was wearing a frilly white dress! It was like a "white goth"![n][w][e]
[f 2 1][f 5 21 1 312]Isn't it getting hot to be wearing those kinds of clothes...?[n][w][e]
[f 2 1][f 5 21 1 312]She must be seriously devoted to her look.[n][w][e]
[f 2 1][f 5 21 1 312]There's no way I could pull that off in this kind of weather...[n][w][e]

[msg MSG_009_0_0 [Stylish Student]]
[f 2 1][f 5 21 1 312]I heard from a friend online about this freaky site that's really taking off.[n][w][e]
[f 2 1][f 5 21 1 312]She said it's about revenge or something.[n][w][e]

[msg MSG_010_0_0 [Stylish Student]]
[f 2 1][f 5 21 1 312]Well, there's that revenge website, but...[n][w][e]
[f 2 1][f 5 21 1 312]It sounds like just a rumor to me.[n][w][e]

[msg MSG_011_0_0 [Stylish Student]]
[f 2 1][f 5 21 1 312]My parents get on my nerves with all that "You better study!" crap.[n][w][e]
[f 2 1][f 5 21 1 312]I wanna go out for summer vacation, but I don't know if they'll let me.[n][w][e]
[f 2 1][f 5 21 1 312]This sucks...[n][w][e]

[msg MSG_012_0_0 [Stylish Student]]
[f 2 1][f 5 21 1 312]I totally knew it![n][w][e]
[f 2 1][f 5 21 1 312]My parents were so annoying, saying, "Go study! Go study!"[n][w][e]
[f 2 1][f 5 21 1 312]I wasn't able to wear my great new clothes during summer break![n][w][e]
[f 2 1][f 5 21 1 312]The sky was blue... The sea was blue... Why did my heart have to be blue, too!?[n][w][e]

[msg MSG_013_0_0 [Stylish Student]]
[f 2 1][f 5 21 1 312]I've been thinking... Don't you think Aigis seems different somehow?[n][w][e]
[f 2 1][f 5 21 1 312]Don't get me wrong, I'm not saying she's a weirdo.[n][w][e]
[f 2 1][f 5 21 1 312]She seems like... a doll. When I see her, I'm reminded of a clothing store mannequin.[n][w][e]

[sel SEL_013_5_0 top]
[f 2 1]It's all in your head.[e]
[f 2 1]You're not far off...[e]

[msg MSG_014_0_0 [Stylish Student]]
[f 2 1][f 5 21 1 312]Haha, I thought as much.[n][w][e]

[msg MSG_015_0_0 [Stylish Student]]
[f 2 1][f 5 21 1 312]Haha... You don't have to agree with me. It's probably just my imagination, after all.[n][w][e]

[msg MSG_016_0_0 [Stylish Student]]
[f 2 1][f 5 21 1 312]It sucks that they canceled the culture festival.[n][w][e]
[f 2 1][f 5 21 1 312]I was looking forward to seeing the out-there fashions, like the maid costumes and stuff.[n][w][e]

[msg MSG_017_0_0 [Stylish Student]]
[f 2 1][f 5 21 1 312]My parents want me to go to one of those four-year colleges.[n][w][e]
[f 2 1][f 5 21 1 312]And after that, they think I should be a lawyer, or something smart like that.[n][w][e]
[f 2 1][f 5 21 1 312]*sigh* This is gonna suck...[n][w][e]

[msg MSG_018_0_0 [Stylish Student]]
[f 2 1][f 5 21 1 312]I told my parents what I wanted to do.[n][w][e]
[f 2 1][f 5 21 1 312]I said I wanted to do something related to fashion, and I'm going to school for that.[n][w][e]
[f 2 1][f 5 21 1 312]I knew they wouldn't agree with that... You could tell by their faces.[n][w][e]

[msg MSG_019_0_0 [Stylish Student]]
[f 2 1][f 5 21 1 312]Ryoji-kun seems a little different.[n][w][e]
[f 2 1][f 5 21 1 312]He's got an exotic face... No Japanese guy would ever look like that.[n][w][e]
[f 2 1][f 5 21 1 312]I should hang out with him some weekend and check out his fashion style.[n][w][e]

[msg MSG_020_0_0 [Stylish Student]]
[f 2 1][f 5 21 1 312]I HATE my stupid parents![n][w][e]
[f 2 1][f 5 21 1 312]They said anyone who doesn't graduate from a four-year college has no future![n][w][e]
[f 2 1][f 5 21 1 312]That's discrimination against the undereducated![n][w][e]

[sel SEL_021_0_0 top]
[f 2 1]It sure is.[e]
[f 2 1]You can't escape it.[e]

[msg MSG_022_0_0 [Stylish Student]]
[f 2 1][f 5 21 1 312]You agree, right? I'm not going to back down to them this time.[n][w][e]

[msg MSG_023_0_0 [Stylish Student]]
[f 2 1][f 5 21 1 312]Is that really how it is...?[n][w][e]

[msg MSG_024_0_0 [Stylish Student]]
[f 2 1][f 5 21 1 312]I love Christmas![n][w][e]
[f 2 1][f 5 21 1 312]The whole town lights up... I get all excited![n][w][e]

[msg MSG_025_0_0 [Stylish Student]]
[f 2 1][f 5 21 1 312]Now that Christmas is over, all the stores are closing, and all the lights have been taken down.[n][w][e]
[f 2 1][f 5 21 1 312]Usually, there's a post-Christmas sale war... But it feels weird.[n][w][e]

[msg MSG_026_0_0 [Stylish Student]]
[f 2 1][f 5 21 1 312]This is so lame... I can't decide on anything.[n][w][e]
[f 2 1][f 5 21 1 312]I never have this much trouble picking outfits.[n][w][e]
[f 2 1][f 5 21 1 312]Oh... I guess my clothes and my future are totally different things, huh? *sigh*[n][w][e]

