[msg MSG_000_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 1 0 0]All right, everyone. This is who I've been talking to you about. She'll be joining us in student council starting today.[n][w][e]

[msg MSG_001_0_0 [Disciplinary Committee Rep.]]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 2 0 0]Ah, so she's [nl]-kun.[n][w][e]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 3 0 0]I'm Hidetoshi Odagiri. I supervise the disciplinary committee.[n][w][e]

[msg MSG_002_0_0 [Treasurer]]
[f 2 1][bup 109 0 65535 65535 0 0][vp 1 0 0 4 0 0]I'm Chihiro Fushimi, the treasurer.[n][w][e]

[msg MSG_003_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 0 65535 65535 0 0][vp 1 0 0 5 0 0]I'm a first-year, and um, I'm still learning the ropes, so please be patient with me, [nl]-san.[n][w][e]

[sel SEL_004_0_0 top]
[f 2 1]Nice to meet you.[e]
[f 2 1]I'll do my best.[e]

[msg MSG_005_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 0 65535 65535 0 0][vp 0 0 0 6 0 0]......[n][w][e]

[msg MSG_006_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 7 0 0]You must be quite talented to be hand-picked by the president herself.[n][w][e]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 8 0 0]I look forward to working with you.[n][w][e]

[msg MSG_007_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 9 0 0]I would certainly hope so.[n][w][e]

[msg MSG_008_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 10 0 0]You must be quite talented to be hand-picked by the president herself.[n][w][e]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 11 0 0]I look forward to working with you.[n][w][e]

[msg MND_009_0_0]
[f 2 1]I think I made a good[n]impression on Odagiri.[n][w][e]
[f 2 1]I joined the student council and[n]got to know the members.[n][w][e]
[f 2 1]I hope I get along with everyone here...[n][w][e]

[msg MSG_009_5_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 12 0 0]It's getting late. Introductions will be enough for today.[n][w][e]

[msg MSG_010_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 13 0 0]What we want from you is to assist us as necessary.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 14 0 0]From now on, you have my permission to enter the student council room whenever you wish.[n][w][e]

[msg MSG_010_1_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 15 0 0]Your time is your own after school, but try to remember the student council every now and then.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 16 0 0]We meet on [clr 2]Mondays, Wednesdays, and Fridays[clr 27]. But we don't meet on days before tests.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 17 0 0]Thanks for coming today, [nl].[n][w][e]

[msg MND_011_0_0]
[f 2 1]I parted ways with the student council[n]members and went back to the dorm.[n][w][e]

