[msg MSG_000_0_0 [Ryoji Mochizuki]]
[f 2 1][bup 221 3 65535 65535 0 0][vp 1 0 0 1 0 0][f 4 23 0 1 3 25 25]Um... It's nice to meet you...?[n][w][e]
[f 2 1][bup 221 3 65535 65535 0 0][vp 1 0 0 2 0 0][f 4 23 0 1 3 25 25]So, you said you needed to talk to me?[n][w][e]

[msg MSG_001_0_0 [Angry Student]]
[f 2 1][vp 1 0 0 3 0 0][f 5 21 0 2]Yeah, keep your hands off our girlfriends.[n][w][e]

[msg MSG_002_0_0 [Dissatisfied Student]]
[f 2 1][vp 1 0 0 4 0 0][f 5 21 0 4]All I've been hearing her talk about is "Ryoji-kun [f 1 3 132]"...[n][w][e]

[msg MSG_003_0_0 [Timid Student]]
[f 2 1][vp 1 0 0 5 0 0][f 5 21 0 3]Y-Yeah, you need to stop talking to every girl you see...![n][w][e]

[msg MSG_004_0_0 [Ryoji Mochizuki]]
[f 2 1][bup 221 3 65535 65535 0 0][vp 1 0 0 6 0 0][f 4 23 0 1 3 25 25]Oh...[n][w][e]
[f 2 1][bup 221 3 65535 65535 0 0][vp 1 0 0 7 0 0][f 4 23 0 1 3 25 25]Um, sorry...[n][w][e]

[msg MSG_005_0_0 [Ryoji Mochizuki]]
[f 2 1][bup 221 0 65535 65535 0 0][vp 1 0 0 8 0 0][f 4 23 0 1 0 25 25]I actually have no idea which girls you're talking about. There's been too many that have come up to me.[n][w][e]

[msg MSG_006_0_0 [Dissatisfied Student]]
[f 2 1][vp 1 0 0 9 0 0][f 5 21 0 4]Wha—? Is this a joke to you!?[n][w][e]

[msg MSG_007_0_0 [Ryoji Mochizuki]]
[f 2 1][bup 221 3 65535 65535 0 0][vp 1 0 0 10 0 0][f 4 23 0 1 3 25 25]I'm sorry if I offended you...[n][w][e]
[f 2 1][bup 221 3 65535 65535 0 0][vp 1 0 0 11 0 0][f 4 23 0 1 3 25 25]But I haven't made any moves on anyone. I just invited them out for a bite to eat.[n][w][e]

[msg MSG_008_0_0 [Angry Student]]
[f 2 1][vp 1 0 0 12 0 0][f 5 21 0 2]That's exactly what we call making a move![n][w][e]

[msg MSG_009_0_0 [Ryoji Mochizuki]]
[f 2 1][bup 221 3 65535 65535 0 0][vp 1 0 0 13 0 0][f 4 23 0 1 3 25 25]That's a problem then...[n][w][e]
[f 2 1][bup 221 3 65535 65535 0 0][vp 1 0 0 14 0 0][f 4 23 0 1 3 25 25]I've made a promise to go out with them. I can't just cancel due to my inconvenience...[n][w][e]

[msg MSG_010_0_0 [Timid Student]]
[f 2 1][vp 1 0 0 15 0 0][f 5 21 0 3]Q-Quit messing with us...![n][w][e]

[msg MND_011_0_0]
[f 2 1]Ryoji could be in danger if this continues...[n][w][e]
[f 2 1]I should probably intervene...[n][w][e]

[msg MSG_012_0_0 [Angry Student]]
[f 2 1][vp 1 0 0 16 0 0][f 5 21 0 2]Gimme your phone! I'm gonna delete all the contact info you have![n][w][e]

[sel SEL_013_0_0 top]
[f 2 1]Calm down.[e]
[f 2 1]Sorry about this.[e]
[f 2 1]He doesn't know any better.[e]

[msg MSG_014_0_0 [Angry Student]]
[f 2 1][vp 1 0 0 17 0 0][f 5 21 0 2]...Who the hell are you? This is none of your business.[n][w][e]

[msg MSG_015_0_0 [Dissatisfied Student]]
[f 2 1][vp 1 0 0 18 0 0]Are you taking his side?[n][w][e]

[msg MSG_016_0_0 [Timid Student]]
[f 2 1][vp 1 0 0 19 0 0][f 5 21 0 3]H-Hey, it's [nl], from 2-F...[n][w][e]
[f 2 1][vp 1 0 0 20 0 0][f 5 21 0 3]I heard she's friends with Sanada-senpai and the student council president... They live in the same dorm...[n][w][e]
[f 2 1][vp 1 0 0 21 0 0][f 5 21 0 3]Wh-What do we do? If she tells them, then...[n][w][e]

[msg MSG_017_0_0 [Angry Student]]
[f 2 1][vp 1 0 0 22 0 0][f 5 21 0 2]Tch...[n][w][e]

[msg MSG_018_0_0 [Dissatisfied Student]]
[f 2 1][vp 1 0 0 23 0 0][f 5 21 0 4]Look, just stay the hell away from our girlfriends and delete 'em from your contacts, got it?[n][w][e]

[msg MSG_019_0_0 [Ryoji Mochizuki]]
[f 2 1][bup 221 4 65535 65535 0 0][vp 0 0 0 24 0 0][f 4 23 0 1 4 25 25]......[n][w][e]

[msg MSG_020_0_0 [Ryoji Mochizuki]]
[f 2 1][bup 221 2 65535 65535 0 0][vp 1 0 0 25 0 0][f 4 23 0 1 2 25 25]All right... I'll do it.[n][w][e]

[msg MSG_021_0_0 [Dissatisfied Student]]
[f 2 1][vp 1 0 0 26 0 0][f 5 21 0 4]Better watch out, or he'll steal your girlfriend too.[n][w][e]

[msg MSG_022_0_0 [Ryoji Mochizuki]]
[f 2 1][bup 221 3 65535 65535 0 0][vp 1 0 0 27 0 0][f 4 23 0 1 3 25 25]Sorry... I didn't mean to make trouble for you.[n][w][e]

[sel SEL_023_0_0 top]
[f 2 1]Well, you did.[e]
[f 2 1]It's tough being popular.[e]
[f 2 1]It's not your fault.[e]

[msg MSG_024_0_0 [Ryoji Mochizuki]]
[f 2 1][bup 221 3 65535 65535 0 0][vp 1 0 0 28 0 0][f 4 23 0 1 3 25 25]Hmm... Guess so, huh. I really didn't expect them to be so angry.[n][w][e]

[msg MSG_025_0_0 [Ryoji Mochizuki]]
[f 2 1][bup 221 1 65535 65535 0 0][vp 1 0 0 29 0 0][f 4 23 0 1 1 25 25]Haha, is that what you call it? That wasn't really my intention...[n][w][e]

[msg MSG_026_0_0 [Ryoji Mochizuki]]
[f 2 1][bup 221 3 65535 65535 0 0][vp 1 0 0 30 0 0][f 4 23 0 1 3 25 25]No... Considering how angry they were, I'd say I probably was at fault here.[n][w][e]

[msg MSG_027_0_0 [Ryoji Mochizuki]]
[f 2 1][bup 221 0 65535 65535 0 0][vp 1 0 0 31 0 0][f 4 23 0 1 0 25 25]From now on, I will ask if they have a boyfriend first before inviting them out.[n][w][e]

[msg MSG_028_0_0 [Ryoji Mochizuki]]
[f 2 1][bup 221 1 65535 65535 0 0][vp 1 0 0 32 0 0][f 4 23 0 1 1 25 25]Hey, thanks for having my back.[n][w][e]
[f 2 1][bup 221 1 65535 65535 0 0][vp 1 0 0 33 0 0][f 4 23 0 1 1 25 25]You're very kind.[n][w][e]

[msg MSG_029_0_0 [Ryoji Mochizuki]]
[f 2 1][bup 221 1 65535 65535 0 0][vp 1 0 0 34 0 0][f 4 23 0 1 1 25 25]What a great view... The ocean looks so beautiful.[n][w][e]
[f 2 1][bup 221 1 65535 65535 0 0][vp 0 0 0 35 0 0][f 4 23 0 1 1 25 25]......[n][w][e]
[f 2 1][bup 221 1 65535 65535 0 0][vp 1 0 0 36 0 0][f 4 23 0 1 1 25 25]I do like seeing it from the monorail to school each morning, but it looks so different from up here...[n][w][e]

[msg MSG_030_0_0 [Ryoji Mochizuki]]
[f 2 1][bup 221 0 65535 65535 0 0][vp 1 0 0 37 0 0][f 4 23 0 1 0 25 25]...I wonder why those guys were so mad.[n][w][e]
[f 2 1][bup 221 3 65535 65535 0 0][vp 1 0 0 38 0 0][f 4 23 0 1 3 25 25]If you're in a relationship with someone, that means you like each other, right?[n][w][e]
[f 2 1][bup 221 3 65535 65535 0 0][vp 1 0 0 39 0 0][f 4 23 0 1 3 25 25]I don't think me getting in the picture would change that, would it...?[n][w][e]

[msg MSG_031_0_0 [Ryoji Mochizuki]]
[f 2 1][bup 221 0 65535 65535 0 0][vp 1 0 0 40 0 0][f 4 23 0 1 0 25 25]I wonder what it means to like someone...[n][w][e]
[f 2 1][bup 221 0 65535 65535 0 0][vp 1 0 0 41 0 0][f 4 23 0 1 0 25 25]Do you have someone like that?[n][w][e]

[sel SEL_032_0_0 top]
[f 2 1]Yes.[e]
[f 2 1]No.[e]
[f 2 1]That's a secret.[e]

[msg MSG_033_0_0 [Ryoji Mochizuki]]
[f 2 1][bup 221 0 65535 65535 0 0][vp 1 0 0 42 0 0][f 4 23 0 1 0 25 25]Wow, that must be nice.[n][w][e]
[f 2 1][bup 221 0 65535 65535 0 0][vp 1 0 0 43 0 0][f 4 23 0 1 0 25 25]Is it anybody I know? I wonder what you two talk about.[n][w][e]

[msg MSG_034_0_0 [Ryoji Mochizuki]]
[f 2 1][bup 221 1 65535 65535 0 0][vp 1 0 0 44 0 0][f 4 23 0 1 1 25 25]Oh, you don't, huh?[n][w][e]
[f 2 1][bup 221 1 65535 65535 0 0][vp 1 0 0 45 0 0][f 4 23 0 1 1 25 25]I'm sure you'll find someone like that before long.[n][w][e]

[msg MSG_035_0_0 [Ryoji Mochizuki]]
[f 2 1][bup 221 1 65535 65535 0 0][vp 1 0 0 46 0 0][f 4 23 0 1 1 25 25]Haha, is that how it is?[n][w][e]
[f 2 1][bup 221 1 65535 65535 0 0][vp 1 0 0 47 0 0][f 4 23 0 1 1 25 25]Well, maybe you can tell me once we get to know each other better.[n][w][e]

[msg MSG_036_0_0 [Ryoji Mochizuki]]
[f 2 1][bup 221 0 65535 65535 0 0][vp 1 0 0 48 0 0][f 4 23 0 1 0 25 25]I guess there's still a lot that I don't understand...[n][w][e]

[msg MSG_037_0_0 [Ryoji Mochizuki]]
[f 2 1][bup 221 0 65535 65535 0 0][vp 1 0 0 49 0 0][f 4 23 0 1 0 25 25]Look at the world out there, the people in this city, our classmates in school, and you...[n][w][e]
[f 2 1][bup 221 0 65535 65535 0 0][vp 0 0 0 50 0 0][f 4 23 0 1 0 25 25]......[n][w][e]
[f 2 1][bup 221 0 65535 65535 0 0][vp 1 0 0 51 0 0][f 4 23 0 1 0 25 25]I want to know more about all of it.[n][w][e]

[msg MSG_038_0_0 [Ryoji Mochizuki]]
[f 2 1][bup 221 1 65535 65535 0 0][vp 1 0 0 52 0 0][f 4 23 0 1 1 25 25]All right, since I dragged you into this mess today, let me make it up to you.[n][w][e]
[f 2 1][bup 221 1 65535 65535 0 0][vp 1 0 0 53 0 0][f 4 23 0 1 1 25 25]I'll treat you to ramen. I just had some with Junpei-kun the other day.[n][w][e]
[f 2 1][bup 221 1 65535 65535 0 0][vp 1 0 0 54 0 0][f 4 23 0 1 1 25 25]And while we're at it, maybe you can show me around town? I'd like to know what kind of places you like going to.[n][w][e]

[msg MND_039_0_0]
[f 2 1]I spent some time with Ryoji,[n]then returned to the dorm...[n][w][e]
[f 2 1]I feel like I understand[n]him a little better now...[n][w][e]

[msg PFM_040_0_0]
[f 2 1]All stats of the equipped Persona have been raised by 1.[n][w][e]

