[msg MSG_000_0_0 [Bebe]]
[f 2 1][bup 112 0 65535 65535 0 0][vp 3 0 65535 11909 0 0]That samurai movie was quite thrilling![n][w][e]

[msg MSG_001_0_0 [Bebe]]
[f 2 1][bup 112 3 65535 65535 0 0]But... the leader of those ruffians in the film...[n][w][e]

[msg MSG_002_0_0 [Bebe]]
[f 2 1][bup 112 3 65535 65535 0 0][vp 3 0 65535 11906 0 0]He looked just like my scary uncle! I did not want to think about him...[n][w][e]

[sel SEL_003_0_0 top]
[f 2 1]Cheer up.[e]
[f 2 1]Get a hold of yourself.[e]
[f 2 1]Don't worry about it.[e]

[msg MSG_004_0_0 [Bebe]]
[f 2 1][bup 112 3 65535 65535 0 0][vp 3 0 65535 11898 0 0]Still... that is easier said than done.[n][w][e]
[f 2 1][bup 112 3 65535 65535 0 0]It looks like I have reached the end of the line...[n][w][e]

[msg MND_005_0_0]
[f 2 1]Bebe seems sad.[n][w][e]
[f 2 1]I feel like we didn't get any closer today...[n][w][e]

[msg MSG_006_0_0 [Bebe]]
[f 2 1][bup 112 2 65535 65535 0 0][vp 3 0 65535 11810 0 0][f 5 13 15 15 112]Hrm... You speak such harsh words.[n][w][e]
[f 2 1][bup 112 1 65535 65535 0 0][f 4 23 0 112 1 25 25]But you are right. I must stay strong. I cannot stand to have you disappointed in me[n][w][e]

[msg MND_007_0_0]
[f 2 1]Bebe seems to have cheered up a bit.[n][w][e]
[f 2 1]I learned a little more about him today...[n][w][e]

[msg MSG_008_0_0 [Bebe]]
[f 2 1][bup 112 1 65535 65535 0 0][vp 3 0 65535 11835 0 0][f 5 13 15 30 112]Sou desu ne! You are right![n][w][e]
[f 2 1][bup 112 1 65535 65535 0 0]This fight is far from over![n][w][e]

[msg MND_009_0_0]
[f 2 1]Bebe seems to have cheered up.[n][w][e]
[f 2 1]I feel like we became a lot closer today.[n][w][e]

[msg MSG_010_0_0 [Bebe]]
[f 2 1][bup 112 0 65535 65535 0 0][vp 3 0 65535 11901 0 0]Shall we go get some food to help improve our moods?[n][w][e]
[f 2 1][bup 112 1 65535 65535 0 0][f 4 23 0 112 1 25 25]Come now, let us go, [nf]-sama! I do not fear my uncle![n][w][e]

[msg MND_011_0_0]
[f 2 1]After getting something to eat with[n]Bebe, I headed back to the dorm.[n][w][e]

