[msg MSG_000_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 1 0 0]Okay, shopping for club stuff is done![n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 2 0 0]Good thing you came with me, [nl]-chan. I didn't realize there was so much to buy...[n][w][e]
[f 2 1][bup 106 3 65535 65535 0 0][vp 1 0 0 3 0 0][f 4 23 0 1 3 25 25]Also, I wasn't really in the mental state to do this alone today.[n][w][e]

[sel SEL_001_0_0 top]
[f 2 1]What happened?[e]
[f 2 1]You did good.[e]

[msg MSG_002_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 4 0 0][f 5 13 12 15 106]Oh, nothing major. Maybe I was exaggerating a bit.[n][w][e]
[f 2 1][bup 106 3 65535 65535 0 0][vp 1 0 0 5 0 0][f 4 23 0 1 3 25 25]Hmm... It's still bothering me, though.[n][w][e]

[msg MSG_003_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 4 65535 65535 0 0][vp 1 0 0 6 0 0]Huh? Oh... Um, thanks.[n][w][e]
[f 2 1][bup 106 3 65535 65535 0 0][vp 1 0 0 7 0 0][f 4 23 0 1 3 25 25][f 4 21 106 10]...You're not going to ask me what happened? That's what you're supposed to do, you know. Based on the conversation.[n][w][e]

[msg MSG_004_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 3 65535 65535 0 0][vp 1 0 0 8 0 0]On today's classic literature pop quiz, I didn't know any of the answers...[n][w][e]
[f 2 1][bup 106 3 65535 65535 0 0][vp 1 0 0 9 0 0]And before I knew it, I'd dozed off. I ended up handing in a blank paper.[n][w][e]

[sel SEL_005_0_0 top]
[f 2 1]Ouch, that sucks.[e]
[f 2 1]It wasn't your fault.[e]

[msg MSG_006_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 2 65535 65535 0 0][vp 1 0 0 10 0 0]Tell me about it. And then Mr. Ekoda got all pissed off![n][w][e]
[f 2 1][bup 106 2 65535 65535 0 0][vp 1 0 0 11 0 0]He called me to the faculty office, and even yelled at me about the length of my skirt![n][w][e]

[msg MSG_007_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 3 65535 65535 0 0][vp 1 0 0 12 0 0][f 5 13 12 5 106]I know, right? I didn't do it on purpose. But then Mr. Ekoda got all pissed off...[n][w][e]
[f 2 1][bup 106 3 65535 65535 0 0][vp 1 0 0 13 0 0]He called me to the faculty office and told me I had to write a reflection essay.[n][w][e]

[msg MSG_008_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 3 65535 65535 0 0][vp 1 0 0 14 0 0]I had to listen to Mr. Ekoda lecture me for the longest time.[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 15 0 0][f 4 23 0 1 0 25 25]He was all like, "At this rate, you'll end up as a good-for-nothing adult," and "You're not putting enough thought into your future."[n][w][e]
[f 2 1][bup 106 2 65535 65535 0 0][vp 1 0 0 16 0 0][f 4 23 0 1 2 25 25]But come on, it's way too early to worry about the future, isn't it? We're still just teenagers![n][w][e]

[sel SEL_009_0_0 top]
[f 2 1]That's true.[e]
[f 2 1]I don't think so.[e]
[f 2 1]You haven't thought about it?[e]

[msg MSG_010_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 17 0 0][f 5 13 12 15 106]Right!? We should be allowed to enjoy ourselves now, while we still can.[n][w][e]
[f 2 1][bup 106 3 65535 65535 0 0][vp 1 0 0 18 0 0][f 4 23 0 1 3 25 25]Honestly, I haven't really thought about my future at all.[n][w][e]

[msg MSG_011_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 4 65535 65535 0 0][vp 1 0 0 19 0 0]Seriously? I didn't know you cared so much about school, [nl]-chan.[n][w][e]
[f 2 1][bup 106 3 65535 65535 0 0][vp 1 0 0 20 0 0][f 4 23 0 1 3 25 25]I... still haven't really thought much about my future.[n][w][e]

[msg MSG_012_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 3 65535 65535 0 0][vp 1 0 0 21 0 0]Hmm, not particularly... Well, I guess I would like to graduate.[n][w][e]
[f 2 1][bup 106 3 65535 65535 0 0][vp 1 0 0 22 0 0]Anything after that is pretty much undecided.[n][w][e]

[msg MSG_013_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 23 0 0]I'm working hard for the track team, so I think that's good enough for now.[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 24 0 0][f 4 23 0 1 1 25 25]As for the future, well... I've got plenty of time to think about it later.[n][w][e]

[msg MND_014_0_0]
[f 2 1]Yuko is smiling happily.[n][w][e]
[f 2 1]I feel like our relationship has grown...[n][w][e]

[msg MSG_015_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 25 0 0]...Hm, I guess this isn't the best place for a long conversation, huh?[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 26 0 0]I'm gonna go drop these off at the storage room. See ya.[n][w][e]

[msg MSG_016_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 4 65535 65535 0 0][vp 1 0 0 27 0 0]Ouch![n][w][e]

[msg MSG_017_0_0 [Spunky Boy]]
[f 2 1][vp 1 0 0 28 0 0]Owww...[n][w][e]

[msg MSG_018_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 2 65535 65535 0 0][vp 1 0 0 29 0 0]Hey! It's dangerous to be running around here—[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 30 0 0][f 4 23 0 1 0 25 25]Wait, aren't you...?[n][w][e]

[msg MSG_019_0_0 [Spunky Boy]]
[f 2 1][vp 1 0 0 31 0 0]Oh, Auntie Yuko![n][w][e]

[msg MSG_020_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 3 65535 65535 0 0][vp 1 0 0 32 0 0]How many times do I have to tell you!? You can call me big sis, nothing else![n][w][e]

[msg MSG_021_0_0 [Spunky Boy]]
[f 2 1][vp 1 0 0 33 0 0][f 5 21 0 2]...Oh no, they're gonna catch me![n][w][e]
[f 2 1][vp 1 0 0 34 0 0][f 5 21 0 2]See ya, auntie![n][w][e]

[msg MSG_022_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 4 65535 65535 0 0][vp 1 0 0 35 0 0]Hey, wait—![n][w][e]

[msg MSG_023_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 3 65535 65535 0 0][vp 1 0 0 36 0 0]And he's gone...[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 37 0 0][f 4 23 0 1 0 25 25]That kid lives across the street from me. Why on earth are they playing tag in a place like this?[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 38 0 0]I mean, it's dangerous, right? They should go play in the schoolyard or something.[n][w][e]

[msg MSG_024_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 4 65535 65535 0 0][vp 1 0 0 39 0 0]Oh no, the school gate is gonna close soon! I'll see you at practice, [nl]-chan![n][w][e]

[msg MND_025_0_0]
[f 2 1]After saying goodbye to Yuko,[n]I decided to go back to the dorm.[n][w][e]

[msg MND_026_0_0]
[f 2 1]DEV: Label is not used[n][w][e]

