[msg MSG_000_0_0 [Maiko's Dad]]
[f 2 1][vp 1 0 0 1 0 0][f 5 21 0 10]When I see this place, I remember all the times I'd come here with Maiko...[n][w][e]
[f 2 1][vp 1 0 0 2 0 0][f 5 21 0 10]She came here when she ran away from home, too.[n][w][e]

[msg MSG_000_3_0 [Maiko's Dad]]
[f 2 1][vp 1 0 0 3 0 0][f 5 21 0 10]She really loved the takoyaki...[n][w][e]

[msg MSG_000_5_0 [Maiko's Dad]]
[f 2 1][vp 1 0 0 4 0 0][f 5 21 0 10]She's a good girl, wouldn't you agree?[n][w][e]

[sel SEL_001_0_0 top]
[f 2 1]Yeah...[e]
[f 2 1]Was she?[e]

[msg MSG_002_0_0 [Maiko's Dad]]
[f 2 1][vp 1 0 0 5 0 0][f 5 21 0 10]She's so good that I wonder if she's really my own child sometimes.[n][w][e]

[msg MSG_003_0_0 [Maiko's Dad]]
[f 2 1][vp 1 0 0 6 0 0][f 5 21 0 10]Oh... Were you not that close? Well, I thought I'd at least let you know.[n][w][e]

[msg MSG_004_0_0 [Maiko's Dad]]
[f 2 1][vp 1 0 0 7 0 0][f 5 21 0 10]She actually sent me a letter recently.[n][w][e]
[f 2 1][vp 1 0 0 8 0 0][f 5 21 0 10]It's chock-full of details about her new life.[n][w][e]

[msg MSG_004_1_0 [Maiko's Dad]]
[f 2 1][vp 1 0 0 9 0 0][f 5 21 0 10]She said she's made a lot of friends.[n][w][e]
[f 2 1][vp 1 0 0 10 0 0][f 5 21 0 10]Let's see... She's in charge of the rabbits at her new school, and has had to get up early to clean the cages.[n][w][e]
[f 2 1][vp 1 0 0 11 0 0][f 5 21 0 10]They scolded her for forgetting her P.E. uniform... She forgot her homework and had to copy a friend's...[n][w][e]

[msg MSG_004_2_0 [Maiko's Dad]]
[f 2 1][vp 1 0 0 12 0 0][f 5 21 0 10]I guess she can be a bit absentminded. I never knew that about her...[n][w][e]
[f 2 1][vp 1 0 0 13 0 0][f 5 21 0 10]Oh, and she did so well on her recorder test that she was asked to perform in front of everyone.[n][w][e]

[msg MSG_004_2_5 [Maiko's Dad]]
[f 2 1][vp 1 0 0 14 0 0][f 5 21 0 10]Then she went on to talk about how she plays at the park by the school with her friends every day...[n][w][e]
[f 2 1][vp 1 0 0 15 0 0][f 5 21 0 10]Her mother's doing well, too. They're having a lot of fun together.[n][w][e]

[msg MSG_004_3_0 [Maiko's Dad]]
[f 2 1][vp 0 0 0 16 0 0][f 5 21 0 10]......[n][w][e]
[f 2 1][vp 1 0 0 17 0 0][f 5 21 0 10]Having fun... Must be nice.[n][w][e]
[f 2 1][vp 1 0 0 18 0 0][f 5 21 0 10]Nowadays, I just come home to an empty house... The rooms feel so big without those two around.[n][w][e]

[msg MSG_004_5_0 [Maiko's Dad]]
[f 2 1][vp 1 0 0 19 0 0]I wonder if she feels the same way, living in a home with no father in it.[n][w][e]
[f 2 1][vp 1 0 0 20 0 0][f 5 21 0 10]We put her through so much because of our own problems...[n][w][e]
[f 2 1][vp 1 0 0 21 0 0][f 5 21 0 10]I feel terrible about it.[n][w][e]

[msg MSG_004_7_0 [Maiko's Dad]]
[f 2 1][vp 1 0 0 22 0 0][f 5 21 0 10]By the way... I've actually got a bone to pick with you too![n][w][e]
[f 2 1][vp 1 0 0 23 0 0][f 5 21 0 10]Maiko must have really liked you, huh? She wrote all about it.[n][w][e]

[msg MSG_005_0_0 [Maiko's Letter]]
[f 2 1][vp 1 0 0 24 0 0]"I can't wait to grow up!"[n][w][e]
[f 2 1][vp 1 0 0 25 0 0]"That's why I'm drinking lots of milk."[n][w][e]
[f 2 1][vp 1 0 0 26 0 0]"I'm going to marry her someday!"[n][w][e]

[msg MSG_006_0_0 [Maiko's Dad]]
[f 2 1][vp 0 0 0 27 0 0]...[n][w][e]
[f 2 1][vp 0 0 0 28 0 0]......[n][w][e]
[f 2 1][vp 0 0 0 29 0 0].........[n][w][e]

[msg MSG_006_5_0 [Maiko's Dad]]
[f 2 1][vp 1 0 0 30 0 0][f 5 21 0 10]What the hell is that about, you little punk!?[n][w][e]

[msg MSG_007_0_0 [Maiko's Dad]]
[f 2 1][vp 1 0 0 31 0 0][f 5 21 0 10]Y-You were taking advantage of my little Maiko, weren't you!?[n][w][e]
[f 2 1][vp 1 0 0 32 0 0][f 5 21 0 10]Maybe I haven't been the best dad, b-but I'm still her father, dammit![n][w][e]
[f 2 1][vp 1 0 0 33 0 0][f 5 21 0 10]And I'm not letting someone like you touch my daughter with a ten-foot pole![n][w][e]

[msg MSG_008_0_0 [Maiko's Dad]]
[f 2 1][vp 1 0 0 34 0 0][f 5 21 0 10]I-I'll never let you marry her! And don't you forget it![n][w][e]

