[msg MSG_000_0_0 [Bebe]]
[f 2 1][bup 112 1 65535 65535 0 0][vp 1 0 0 1 0 0]Yatta, yes! This is my finest sewing work yet![n][w][e]

[msg MND_001_0_0]
[f 2 1]The foreign exchange student I met[n]at the bookstore is busy sewing.[n][w][e]

[sel SEL_002_0_0 top]
[f 2 1]Hello?[e]
[f 2 1]Better leave him alone.[e]

[msg MSG_003_0_0 [Bebe]]
[f 2 1][bup 112 4 65535 65535 0 0][vp 1 0 0 2 0 0]Oh!? Bonjour, [nf]-sama![n][w][e]
[f 2 1][bup 112 1 65535 65535 0 0][vp 1 0 0 3 0 0][f 4 23 0 1 1 25 25]I haven't seen you since the bookstore![n][w][e]

[msg MSG_004_0_0 [Bebe]]
[f 2 1][bup 112 2 65535 65535 0 0][vp 1 0 0 4 0 0]Hm, who's there!? Who dares enter the sacred home economics room?[n][w][e]

[msg MSG_004_3_0 [Bebe]]
[f 2 1][bup 112 1 65535 65535 0 0][vp 1 0 0 5 0 0]Oh!? Bonjour, [nf]-sama![n][w][e]

[msg MSG_005_0_0 [Bebe]]
[f 2 1][bup 112 1 65535 65535 0 0][vp 1 0 0 6 0 0]You came![n][w][e]
[f 2 1][bup 112 1 65535 65535 0 0][vp 1 0 0 7 0 0]What a pleasant surprise! I am so happy to see you![n][w][e]

[sel SEL_006_0_0 top]
[f 2 1]What are you doing?[e]
[f 2 1]You know my name?[e]

[msg MSG_007_0_0 [Bebe]]
[f 2 1][bup 112 1 65535 65535 0 0][vp 1 0 0 8 0 0]I am training in the art of sewing![n][w][e]

[msg MSG_008_0_0 [Bebe]]
[f 2 1][bup 112 0 65535 65535 0 0][vp 1 0 0 9 0 0]Oui, I asked the teacher.[n][w][e]
[f 2 1][bup 112 1 65535 65535 0 0][vp 1 0 0 10 0 0][f 4 23 0 1 1 25 25]And from what I hear, you and I are in the same grade! How lucky![n][w][e]

[msg MSG_009_0_0 [Bebe]]
[f 2 1][bup 112 0 65535 65535 0 0][vp 1 0 0 11 0 0]I am in this fashion club in order to hone my sewing craft.[n][w][e]
[f 2 1][bup 112 1 65535 65535 0 0][vp 1 0 0 12 0 0][f 4 23 0 1 1 25 25]Would you like to join me, [nf]-sama? It is tanoshii—very fun![n][w][e]

[msg MSG_010_0_0 [Bebe]]
[f 2 1][bup 112 0 65535 65535 0 0][vp 1 0 0 13 0 0]If I may be so bold, would you sign up for my club?[n][w][e]

[sel SEL_011_0_0 top]
[f 2 1]Maybe I should try.[e]
[f 2 1]No thanks.[e]

[msg MSG_012_0_0 [Bebe]]
[f 2 1][bup 112 4 65535 65535 0 0][vp 1 0 0 14 0 0]Honto!? Really!?[n][w][e]

[msg MSG_013_0_0 [Bebe]]
[f 2 1][bup 112 0 65535 65535 0 0][vp 1 0 0 15 0 0]But club activities are very easy![n][w][e]
[f 2 1][bup 112 0 65535 65535 0 0][vp 1 0 0 16 0 0]You could just come by whenever you feel like! Onegaishimasu—please...[n][w][e]

[msg MND_014_0_0]
[f 2 1]Bebe's starting to beg...[n][w][e]
[f 2 1]How am I supposed to say[n]no now? Guess I'll just join...[n][w][e]

[msg MSG_015_0_0 [Bebe]]
[f 2 1][bup 112 1 65535 65535 0 0][vp 1 0 0 17 0 0]Katajikenai—many thanks! I am thrilled to have a new member![n][w][e]
[f 2 1][bup 112 0 65535 65535 0 0][vp 1 0 0 18 0 0][f 4 23 0 1 0 25 25]I am here on [clr 2]Tuesdays, Wednesdays, and Fridays[clr 27]. But it may be closed when we have exams.[n][w][e]

[msg MSG_015_3_0 [Bebe]]
[f 2 1][bup 112 3 65535 65535 0 0][vp 1 0 0 19 0 0]I have not made any good tomodachi—friends, so it is very sabishii—very lonely. Maybe it is because I do not fit in.[n][w][e]

[msg MSG_015_5_0 [Bebe]]
[f 2 1][bup 112 1 65535 65535 0 0][vp 1 0 0 20 0 0]But now you are here, [nf]-sama! The divine fates have brought us together![n][w][e]

[msg MND_016_0_0]
[f 2 1]I ended up joining the fashion club.[n][w][e]
[f 2 1]I've gotten to know Bebe,[n]the foreign exchange student.[n][w][e]

[msg MSG_017_0_0 [Bebe]]
[f 2 1][bup 112 4 65535 65535 0 0][vp 1 0 0 21 0 0]Whoa! Look at the time![n][w][e]

[msg MSG_017_3_0 [Bebe]]
[f 2 1][bup 112 0 65535 65535 0 0][vp 1 0 0 22 0 0]Well then, au revoir, [nf]-sama.[n][w][e]

[msg MSG_017_5_0 [Bebe]]
[f 2 1][bup 112 1 65535 65535 0 0][vp 1 0 0 23 0 0]...Oh, that's right![n][w][e]
[f 2 1][bup 112 0 65535 65535 0 0][vp 1 0 0 24 0 0][f 4 23 0 1 0 25 25]I was wondering, what is the best way to say bye to a friend? As in, what is the most culturally accepted?[n][w][e]

[sel SEL_018_0_0 top]
[f 2 1]Just a simple "See you later."[f 2 9 1 1 611][e]
[f 2 1]A cool and chummy "Peace out."[f 2 9 1 1 612][e]
[f 2 1]A stately "Until we meet again."[f 2 9 1 1 613][e]
[f 2 1]A theatrical, intense "I'll be back."[f 2 9 1 1 614][e]

[msg MSG_019_0_0 [Bebe]]
[f 2 1][bup 112 1 65535 65535 0 0][vp 1 0 0 25 0 0]I understand perfectly! See you later![n][w][e]

[msg MSG_020_0_0 [Bebe]]
[f 2 1][bup 112 1 65535 65535 0 0][vp 1 0 0 26 0 0]I understand perfectly! Peace out![n][w][e]

[msg MSG_021_0_0 [Bebe]]
[f 2 1][bup 112 1 65535 65535 0 0][vp 1 0 0 27 0 0]I understand perfectly! Until we meet again![n][w][e]

[msg MSG_022_0_0 [Bebe]]
[f 2 1][bup 112 1 65535 65535 0 0][vp 1 0 0 28 0 0]I understand perfectly! I'll be back![n][w][e]

[msg MND_023_0_0]
[f 2 1]I parted ways with Bebe[n]and went back to the dorm.[n][w][e]

