[msg MSG_000_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 1 0 0]Well, here we are. A full moon once again.[n][w][e]

[msg MSG_001_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 52 65535 0 0][vp 1 0 0 2 0 0]Any luck, Yamagishi?[n][w][e]

[msg MSG_002_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 52 65535 0 0][vp 1 0 0 3 0 0]Yes, I can sense it. There's a Shadow reading tonight, as expected.[n][w][e]

[msg MSG_003_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 52 65535 0 0][vp 1 0 0 4 0 0]That's what I'm talking about.[n][w][e]

[msg MSG_004_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 52 65535 0 0][vp 1 0 0 5 0 0]It's located by the deserted houses in the northern part of Iwatodai.[n][w][e]
[f 2 1][bup 6 3 52 65535 0 0][vp 1 0 0 6 0 0]But, there's something strange. The reading is coming from underground... Almost ten meters.[n][w][e]

[msg MSG_005_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 52 65535 0 0][vp 1 0 0 7 0 0]Maybe it's in some kind of basement?[n][w][e]

[msg MSG_006_0_0 [Aigis]]
[f 2 1][bup 7 0 52 65535 0 0][vp 1 0 0 8 0 0]According to the records for the northern harbor, there are no structures that match that criteria.[n][w][e]
[f 2 1][bup 7 0 52 65535 0 0][vp 1 0 0 9 0 0]However, there once was an underground facility used by the military.[n][w][e]

[msg MSG_007_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 52 65535 0 0][vp 1 0 0 10 0 0]The military?[n][w][e]
[f 2 1][bup 2 0 52 65535 0 0][vp 1 0 0 11 0 0]Is that true?[n][w][e]

[msg MSG_008_0_0 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 12 0 0]Well, the architectural and geographical data for the area was uploaded into her memory.[n][w][e]
[f 2 1][bup 222 0 65535 65535 0 0][vp 1 0 0 13 0 0]Then again, the information hasn't been updated in ten years.[n][w][e]

[msg MSG_009_0_0 [Aigis]]
[f 2 1][bup 7 0 52 65535 0 0][vp 1 0 0 14 0 0]Correct. The data is ten years old.[n][w][e]

[msg MSG_010_0_0 [Junpei Iori]]
[f 2 1][bup 3 3 52 65535 0 0][vp 1 0 0 15 0 0]Shouldn't someone fix that...?[n][w][e]

[msg MSG_011_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 52 65535 0 0][vp 1 0 0 16 0 0]So how exactly do we proceed?[n][w][e]

[sel SEL_012_0_0 top]
[f 2 1]Should we head down...?[e]
[f 2 1]Is the facility still there?[e]
[f 2 1]No idea.[e]

[msg MSG_013_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 52 65535 0 0][vp 1 0 0 17 0 0]We won't know more until we actually get there.[n][w][e]

[msg MSG_014_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 52 65535 0 0][vp 1 0 0 18 0 0]Old relics of war...[n][w][e]
[f 2 1][bup 5 0 52 65535 0 0][vp 1 0 0 19 0 0]It seems the situation is still unclear at this time.[n][w][e]
[f 2 1][bup 5 0 52 65535 0 0][vp 1 0 0 20 0 0]With that in mind, we'll wait until we arrive before we decide who should be deployed.[n][w][e]

[msg MSG_015_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 52 65535 0 0][vp 1 0 0 21 0 0]Agreed.[n][w][e]

[msg MSG_016_0_0 [Aigis]]
[f 2 1][bup 7 0 52 65535 0 0][vp 1 0 0 22 0 0]Understood.[n][w][e]

[msg MSG_017_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 52 65535 0 0][vp 1 0 0 23 0 0]All right, let's go.[n][w][e]

