[msg MSG_000_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 2 65535 0 0][vp 1 0 0 1 0 0]It looks like we're all here.[n][w][e]

[msg MSG_001_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 2 65535 0 0][vp 1 0 0 2 0 0]Are you okay, Ryoji-kun?[n][w][e]

[msg MSG_002_0_0 [Ryoji Mochizuki]]
[f 2 1][bup 221 1 65535 65535 0 0][vp 1 0 0 3 0 0]Yeah, I'm okay. Thanks.[n][w][e]
[f 2 1][bup 221 10 65535 65535 0 0][vp 1 0 0 4 0 0][f 4 23 0 221 10 25 25]Besides, I have more to tell you guys.[n][w][e]

[msg MSG_003_0_0 [Yukari Takeba]]
[f 2 1][bup 2 3 2 65535 0 0][vp 1 0 0 5 0 0]Ryoji-kun...[n][w][e]

[msg MSG_004_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 2 65535 0 0][vp 1 0 0 6 0 0]Then allow me to jump right in. We have many questions that need answers, after all.[n][w][e]
[f 2 1][bup 5 0 2 65535 0 0][vp 1 0 0 7 0 0]Yesterday, you said the Shadows were here to facilitate the rebirth of the maternal being.[n][w][e]
[f 2 1][bup 5 0 2 65535 0 0][vp 1 0 0 8 0 0]Tell us more about this. What happens if she returns?[n][w][e]

[msg MSG_005_0_0 [Ryoji Mochizuki]]
[f 2 1][bup 221 3 65535 65535 0 0][vp 1 0 0 9 0 0]The maternal being is called [clr 33]Nyx[clr 27].[n][w][e]

[msg MSG_006_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 2 65535 0 0][vp 1 0 0 10 0 0]Who the hell's Nyx?[n][w][e]

[msg MSG_007_0_0 [Ryoji Mochizuki]]
[f 2 1][bup 221 0 65535 65535 0 0][vp 1 0 0 11 0 0]Nyx is the mother of Shadows. In ancient times, she bestowed Death upon this world.[n][w][e]
[f 2 1][bup 221 3 65535 65535 0 0][vp 1 0 0 12 0 0][f 4 23 0 221 3 25 25]If she awakens, the world will be swallowed by darkness, and all life will perish.[n][w][e]

[msg MSG_008_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 4 2 65535 0 0][vp 1 0 0 13 0 0]All life!?[n][w][e]

[msg MSG_009_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 4 2 65535 0 0][vp 1 0 0 14 0 0]Are you saying... everyone will die!?[n][w][e]

[msg MSG_010_0_0 [Ryoji Mochizuki]]
[f 2 1][bup 221 3 65535 65535 0 0][vp 1 0 0 15 0 0]It'd be more accurate to say that we'll all surrender the will to live.[n][w][e]

[msg MSG_011_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 2 2 65535 0 0][vp 1 0 0 16 0 0]Wait, are you... talking about the Lost!?[n][w][e]

[msg MND_012_0_0]
[f 2 1]Everyone seems to have arrived[n]at the same conclusion...[n][w][e]
[f 2 1]Every single human being will[n]become like the Lost...[n][w][e]
[f 2 1]Leading to the extinction of mankind...[n][w][e]
[f 2 1]...And the end of the world.[n][w][e]

[msg MSG_013_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 3 2 65535 0 0][vp 1 0 0 17 0 0]The Fall...[n][w][e]

[msg MSG_014_0_0 [Yukari Takeba]]
[f 2 1][bup 2 2 2 65535 0 0][vp 1 0 0 18 0 0]But there's still a way to stop it from happening, right?[n][w][e]

[msg MSG_015_0_0 [Ryoji Mochizuki]]
[f 2 1][bup 221 3 65535 65535 0 0][vp 0 0 0 19 0 0]......[n][w][e]

[msg MSG_016_0_0 [Yukari Takeba]]
[f 2 1][bup 2 3 2 65535 0 0][vp 1 0 0 20 0 0]Wh-What?[n][w][e]
[f 2 1][bup 2 3 2 65535 0 0][vp 1 0 0 21 0 0]Don't tell me there's nothing we can do.[n][w][e]

[msg MSG_017_0_0 [Ryoji Mochizuki]]
[f 2 1][bup 221 10 65535 65535 0 0][vp 1 0 0 22 0 0]I'm sorry...[n][w][e]

[msg MSG_018_0_0 [Yukari Takeba]]
[f 2 1][bup 2 4 2 65535 0 0][vp 1 0 0 23 0 0]Wait, why're you apologizing!?[n][w][e]
[f 2 1][bup 2 4 2 65535 0 0][vp 1 0 0 24 0 0]Are you saying there's no way to stop it!?[n][w][e]

[msg MSG_019_0_0 [Ryoji Mochizuki]]
[f 2 1][bup 221 10 65535 65535 0 0][vp 1 0 0 25 0 0]That's right...[n][w][e]
[f 2 1][bup 221 10 65535 65535 0 0][vp 1 0 0 26 0 0]You heard the bell. That's when it was all decided.[n][w][e]

[msg MSG_019_5_0 [Ryoji Mochizuki]]
[f 2 1][bup 221 3 65535 65535 0 0][vp 1 0 0 27 0 0]I'm the Appriser... The Appriser of Death.[n][w][e]
[f 2 1][bup 221 3 65535 65535 0 0][vp 1 0 0 28 0 0]The fact that I'm here at all proves the Fall is coming.[n][w][e]

[msg MSG_020_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 2 65535 0 0][vp 1 0 0 29 0 0]The Fall is coming...[n][w][e]

[msg MND_021_0_0]
[f 2 1]Everyone is at a loss for words...[n][w][e]
[f 2 1]It's inevitable... The entire human race[n]will become members of the Lost.[n][w][e]
[f 2 1]Ryoji's existence confirms the[n]impending extinction of mankind.[n][w][e]
[f 2 1]......[n][w][e]

[msg MSG_022_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 2 2 65535 0 0][vp 1 0 0 30 0 0]When!? When will it happen!?[n][w][e]

[msg MSG_023_0_0 [Ryoji Mochizuki]]
[f 2 1][bup 221 3 65535 65535 0 0][vp 1 0 0 31 0 0]I don't think you'll live to see next spring.[n][w][e]

[msg MSG_024_0_0 [Junpei Iori]]
[f 2 1][bup 3 2 2 65535 0 0][vp 1 0 0 32 0 0]But... that's barely any time at all![n][w][e]

[msg MSG_025_0_0 [Yukari Takeba]]
[f 2 1][bup 2 3 2 65535 0 0][vp 0 0 0 33 0 0]......[n][w][e]

[msg MSG_026_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 2 2 65535 0 0][vp 0 0 0 34 0 0]......[n][w][e]

[msg MSG_027_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 3 2 65535 0 0][vp 0 0 0 35 0 0]......[n][w][e]

[msg MSG_028_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 2 65535 0 0][vp 1 0 0 36 0 0]H-Heh, what're you guys freakin' out about?[n][w][e]
[f 2 1][bup 3 1 2 65535 0 0][vp 1 0 0 37 0 0]Nyx shmyx, am I right? All we gotta do is win and we're golden![n][w][e]
[f 2 1][bup 3 1 2 65535 0 0][vp 1 0 0 38 0 0]And we haven't lost a single fight yet, have we!?[n][w][e]

[sel SEL_029_0_0 top]
[f 2 1]Yeah, Junpei's right.[e]
[f 2 1]It's not that simple...[e]

[msg MSG_030_0_0 [Ryoji Mochizuki]]
[f 2 1][bup 221 3 65535 65535 0 0][vp 1 0 0 39 0 0]You can't win...[n][w][e]

[msg MSG_031_0_0 [Ryoji Mochizuki]]
[f 2 1][bup 221 3 65535 65535 0 0][vp 1 0 0 40 0 0]More like it's not possible...[n][w][e]

[msg MSG_032_0_0 [Ryoji Mochizuki]]
[f 2 1][bup 221 10 65535 65535 0 0][vp 1 0 0 41 0 0]When you're up against Nyx, power doesn't mean a thing.[n][w][e]
[f 2 1][bup 221 3 65535 65535 0 0][vp 1 0 0 42 0 0][f 4 23 0 221 3 25 25]It's like trying to fight the inevitable, like death or the flow of time.[n][w][e]
[f 2 1][bup 221 3 65535 65535 0 0][vp 1 0 0 43 0 0]Nyx can't be defeated. She... just can't.[n][w][e]

[msg MSG_033_0_0 [Junpei Iori]]
[f 2 1][bup 3 3 2 65535 0 0][vp 1 0 0 44 0 0]What...?[n][w][e]

[msg MSG_034_0_0 [Junpei Iori]]
[f 2 1][bup 3 2 2 65535 0 0][vp 1 0 0 45 0 0]This is bullshit![n][w][e]

[msg MSG_035_0_0 [Ken Amada]]
[f 2 1][bup 8 3 2 65535 0 0][vp 1 0 0 46 0 0]This is all so sudden.[n][w][e]

[msg MND_036_0_0]
[f 2 1]Everyone is visibly distraught...[n][w][e]

[msg MSG_037_0_0 [Ryoji Mochizuki]]
[f 2 1][bup 221 3 65535 65535 0 0][vp 1 0 0 47 0 0]I was born from a collection of Shadows.[n][w][e]
[f 2 1][bup 221 3 65535 65535 0 0][vp 1 0 0 48 0 0]But now I have a human form, so I can talk with you, laugh with you, cry with you.[n][w][e]

[msg MSG_037_5_0 [Ryoji Mochizuki]]
[f 2 1][bup 221 0 65535 65535 0 0][vp 1 0 0 49 0 0]It's the gift I received for existing within her.[n][w][e]
[f 2 1][bup 221 0 65535 65535 0 0][vp 1 0 0 50 0 0]And because of that, I can give you a choice.[n][w][e]

[msg MSG_038_0_0 [Yukari Takeba]]
[f 2 1][bup 2 3 2 65535 0 0][vp 1 0 0 51 0 0]A choice?[n][w][e]

[msg MSG_039_0_0 [Ryoji Mochizuki]]
[f 2 1][bup 221 3 65535 65535 0 0][vp 1 0 0 52 0 0]Nyx's arrival is unavoidable now.[n][w][e]
[f 2 1][bup 221 0 65535 65535 0 0][vp 1 0 0 53 0 0][f 4 23 0 221 0 25 25]But you can choose to live in peace until she arrives.[n][w][e]

[msg MSG_040_0_0 [Ryoji Mochizuki]]
[f 2 1][bup 221 0 65535 65535 0 0][vp 1 0 0 54 0 0]You just... have to kill me.[n][w][e]

[msg MSG_041_0_0 [Ryoji Mochizuki]]
[f 2 1][bup 221 0 65535 65535 0 0][vp 1 0 0 55 0 0]If the Appriser disappears, all recollection of the Dark Hour would go with me.[n][w][e]
[f 2 1][bup 221 0 65535 65535 0 0][vp 1 0 0 56 0 0]And that would erase any memories of this hopeless reality.[n][w][e]

[msg MSG_041_5_0 [Ryoji Mochizuki]]
[f 2 1][bup 221 10 65535 65535 0 0][vp 1 0 0 57 0 0]There'd be no way for you to remember anything.[n][w][e]
[f 2 1][bup 221 3 65535 65535 0 0][vp 1 0 0 58 0 0][f 4 23 0 221 3 25 25]When the Fall comes, it'll happen in an instant. You won't have to suffer at all.[n][w][e]

[msg MSG_042_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 4 2 65535 0 0][vp 1 0 0 59 0 0]We'll forget everything?[n][w][e]

[msg MSG_043_0_0 [Ryoji Mochizuki]]
[f 2 1][bup 221 3 65535 65535 0 0][vp 1 0 0 60 0 0]I'm saying you can go back to your normal lives.[n][w][e]
[f 2 1][bup 221 3 65535 65535 0 0][vp 1 0 0 61 0 0]And by doing that, you might buy a little time and delay the Fall, too.[n][w][e]
[f 2 1][bup 221 3 65535 65535 0 0][vp 1 0 0 62 0 0]Technically, I'm the same as Nyx, so I can't be killed.[n][w][e]

[msg MSG_043_5_0 [Ryoji Mochizuki]]
[f 2 1][bup 221 0 65535 65535 0 0][vp 1 0 0 63 0 0]But thanks to her, there's a part of me that's become human.[n][w][e]
[f 2 1][bup 221 3 65535 65535 0 0][vp 1 0 0 64 0 0][f 4 23 0 221 3 25 25]So if it's done by her hand, then it may be possible.[n][w][e]

[msg MSG_044_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 2 65535 0 0][vp 1 0 0 65 0 0]Ryoji-kun...[n][w][e]

[msg MSG_045_0_0 [Ryoji Mochizuki]]
[f 2 1][bup 221 0 65535 65535 0 0][vp 1 0 0 66 0 0]If you don't kill me, everything will stay just as it is.[n][w][e]
[f 2 1][bup 221 3 65535 65535 0 0][vp 1 0 0 67 0 0][f 4 23 0 221 3 25 25]With no hope for salvation, you'll live every day paralyzed by the fear of your impending death.[n][w][e]
[f 2 1][bup 221 10 65535 65535 0 0][vp 1 0 0 68 0 0][f 4 23 0 221 10 25 25]And I don't want to put you through something like that.[n][w][e]

[sel SEL_046_0_0 top]
[f 2 1]I couldn't kill you...[e]
[f 2 1]I don't want to forget...[e]
[f 2 1]I don't know what to do.[e]

[msg MSG_047_0_0 [Ryoji Mochizuki]]
[f 2 1][bup 221 3 65535 65535 0 0][vp 1 0 0 69 0 0]This is something only you can do. No one else.[n][w][e]

[msg MSG_048_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 2 65535 0 0][vp 1 0 0 70 0 0]Well, I definitely don't want my memories erased.[n][w][e]

[msg MSG_049_0_0 [Yukari Takeba]]
[f 2 1][bup 2 3 2 65535 0 0][vp 1 0 0 71 0 0]Exactly.[n][w][e]

[msg MSG_050_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 2 65535 0 0][vp 1 0 0 72 0 0]I know...[n][w][e]

[msg MSG_051_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 2 65535 0 0][vp 1 0 0 73 0 0]...I don't want my memories to be erased.[n][w][e]

[msg MSG_052_0_0 [Yukari Takeba]]
[f 2 1][bup 2 2 2 65535 0 0][vp 1 0 0 74 0 0]I mean, forgetting all this would be like trying to hide from the truth![n][w][e]

[msg MSG_053_0_0 [Ryoji Mochizuki]]
[f 2 1][bup 221 0 65535 65535 0 0][vp 1 0 0 75 0 0]Is that really such a bad thing?[n][w][e]
[f 2 1][bup 221 3 65535 65535 0 0][vp 1 0 0 76 0 0][f 4 23 0 221 3 25 25]If you don't do this, all that awaits is despair greater than you can possibly imagine.[n][w][e]

[msg MSG_053_5_0 [Ryoji Mochizuki]]
[f 2 1][bup 221 3 65535 65535 0 0][vp 1 0 0 77 0 0]You don't understand the terror of certain death![n][w][e]
[f 2 1][bup 221 3 65535 65535 0 0][vp 1 0 0 78 0 0]Don't make your decision without at least thinking about it first.[n][w][e]

[msg MSG_054_0_0 [Yukari Takeba]]
[f 2 1][bup 2 3 2 65535 0 0][vp 1 0 0 79 0 0]......[n][w][e]

[msg MSG_055_0_0 [Ken Amada]]
[f 2 1][bup 8 2 2 65535 0 0][vp 1 0 0 80 0 0]Why is this happening!?[n][w][e]

[msg MSG_056_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 3 2 65535 0 0][vp 0 0 0 81 0 0]......[n][w][e]

[msg MSG_057_0_0 [Ryoji Mochizuki]]
[f 2 1][bup 221 3 65535 65535 0 0][vp 1 0 0 82 0 0]You don't have to decide right now. There's still some time.[n][w][e]
[f 2 1][bup 221 3 65535 65535 0 0][vp 1 0 0 83 0 0]December 31st, [clr 33]New Year's Eve[clr 27]. You have until then to think about it.[n][w][e]
[f 2 1][bup 221 3 65535 65535 0 0][vp 1 0 0 84 0 0]After that, I'll dissolve into the blackness of the Dark Hour and lose my physical form.[n][w][e]

[msg MSG_058_0_0 [Junpei Iori]]
[f 2 1][bup 3 3 2 65535 0 0][vp 1 0 0 85 0 0]Ryoji...[n][w][e]

[msg MSG_059_0_0 [Ryoji Mochizuki]]
[f 2 1][bup 221 3 65535 65535 0 0][vp 1 0 0 86 0 0]When Nyx arrives, I'm going to disappear anyway.[n][w][e]
[f 2 1][bup 221 0 65535 65535 0 0][vp 1 0 0 87 0 0][f 4 23 0 221 0 25 25]So please, don't worry about me.[n][w][e]
[f 2 1][bup 221 0 65535 65535 0 0][vp 1 0 0 88 0 0]I'll be back when New Year's Eve rolls around.[n][w][e]

[msg MSG_060_0_0 [Junpei Iori]]
[f 2 1][bup 3 2 2 65535 0 0][vp 1 0 0 89 0 0]H-Hey, Ryoji, wait![n][w][e]

[msg MSG_061_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 2 65535 0 0][vp 1 0 0 90 0 0]Stop, Junpei-kun![n][w][e]
[f 2 1][bup 6 3 2 65535 0 0][vp 1 0 0 91 0 0]I felt Ryoji-kun's presence vanish just now. There's no point in chasing him. He's gone.[n][w][e]

[msg MSG_062_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 3 2 65535 0 0][vp 0 0 0 92 0 0]......[n][w][e]

[msg MSG_063_0_0 [Yukari Takeba]]
[f 2 1][bup 2 3 2 65535 0 0][vp 1 0 0 93 0 0]Ryoji-kun...[n][w][e]

[msg MSG_064_0_0 [Ken Amada]]
[f 2 1][bup 8 3 2 65535 0 0][vp 0 0 0 94 0 0]......[n][w][e]

[msg MSG_065_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 3 2 65535 0 0][vp 1 0 0 95 0 0]I guess... he'll be back.[n][w][e]

[msg MND_066_0_0]
[f 2 1]......[n][w][e]
[f 2 1]...Ryoji's revelation was all too devastating.[n][w][e]
[f 2 1]The world will soon perish...[n][w][e]
[f 2 1]Mankind is destined for extinction...[n][w][e]
[f 2 1]A difficult decision lies before me...[n][w][e]
[f 2 1]Death is inevitable...[n][w][e]
[f 2 1]The Appriser truly did deliver[n]a death sentence to us all...[n][w][e]
[f 2 1]......[n][w][e]
[f 2 1]I can't think clearly right now...[n][w][e]
[f 2 1]How do you even choose[n]the way you want to die?[n][w][e]

