[msg MSG_000_0_0 [Mysterious Boy]]
[f 2 1][vp 1 0 0 1 0 0]You've prevailed yet again.[n][w][e]

[msg MSG_001_0_0 [Mysterious Boy]]
[f 2 1][bup 111 0 65535 65535 0 0][vp 1 0 0 2 0 0]Do you remember what I said before?[n][w][e]
[f 2 1][bup 111 0 65535 65535 0 0][vp 1 0 0 3 0 0]About everything coming to an end?[n][w][e]
[f 2 1][bup 111 0 65535 65535 0 0][vp 1 0 0 4 0 0]Well, I recalled something else.[n][w][e]

[msg MSG_001_5_0 [Mysterious Boy]]
[f 2 1][bup 111 0 65535 65535 0 0][vp 1 0 0 5 0 0]I'm pretty sure the end is unavoidable.[n][w][e]

[msg MSG_002_0_0 [Mysterious Boy]]
[f 2 1][bup 111 0 65535 65535 0 0][vp 1 0 0 6 0 0]But it's kind of weird.[n][w][e]
[f 2 1][bup 111 0 65535 65535 0 0][vp 1 0 0 7 0 0]It doesn't feel that inevitable right now, considering the vast potential inside you.[n][w][e]
[f 2 1][bup 111 0 65535 65535 0 0][vp 1 0 0 8 0 0]Plus, it seems like your power's changed quite a bit.[n][w][e]

[msg MSG_003_0_0 [Mysterious Boy]]
[f 2 1][bup 111 1 65535 65535 0 0][vp 1 0 0 9 0 0]Hey, if you don't mind, can I be your friend?[n][w][e]
[f 2 1][bup 111 1 65535 65535 0 0][vp 1 0 0 10 0 0]I'm really curious about you. What do you say?[n][w][e]

[sel SEL_004_0_0 top]
[f 2 1]Sure, why not.[e]
[f 2 1]Tell me your name first.[e]
[f 2 1]Yeah, whatever.[e]

[msg MSG_005_0_0 [Mysterious Boy]]
[f 2 1][bup 111 0 65535 65535 0 0][vp 1 0 0 11 0 0]Okay. Then as of right now, we're friends.[n][w][e]

[msg MSG_006_0_0 [Mysterious Boy]]
[f 2 1][bup 111 0 65535 65535 0 0][vp 1 0 0 12 0 0]Name...?[n][w][e]
[f 2 1][bup 111 0 65535 65535 0 0][vp 1 0 0 13 0 0]Oh, I see. I need a name.[n][w][e]

[msg MSG_007_0_0 [Mysterious Boy]]
[f 2 1][bup 111 0 65535 65535 0 0][vp 1 0 0 14 0 0]Hehe, guess you don't really care. Maybe I didn't need to bring it up, hm?[n][w][e]
[f 2 1][bup 111 0 65535 65535 0 0][vp 1 0 0 15 0 0]You and I have been together since the beginning.[n][w][e]

[msg MSG_008_0_0 [Mysterious Boy]]
[f 2 1][bup 111 0 65535 65535 0 0][vp 1 0 0 16 0 0]My name is... Pharos.[n][w][e]

[msg MSG_009_0_0 [Pharos]]
[f 2 1][bup 111 1 65535 65535 0 0][vp 1 0 0 17 0 0]I know we'll get along great.[n][w][e]

[msg MND_010_0_0]
[f 2 1]I can feel the beginnings of a bond[n]with the mysterious boy, Pharos...[n][w][e]

[msg MSG_011_0_0 [Pharos]]
[f 2 1][bup 111 0 65535 65535 0 0][vp 1 0 0 18 0 0]Well, it's getting late, so I'm going now.[n][w][e]
[f 2 1][bup 111 1 65535 65535 0 0][vp 1 0 0 19 0 0]I can hardly wait until the next time we meet.[n][w][e]
[f 2 1][bup 111 1 65535 65535 0 0][vp 1 0 0 20 0 0]Bye-bye.[n][w][e]

