[msg MSG_000_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 1 0 0]Oh yeah, have you been training to strengthen your core, [nl]-kun?[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 2 0 0]It's a good idea if you want to shorten your run time. You're less likely to injure yourself too.[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 3 0 0]I was talking with Kaz about putting it in the first-years' practice routine, actually.[n][w][e]

[msg MSG_001_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 4 0 0]Do you mind if we continue talking in the café? I'm a little hungry.[n][w][e]

[msg MSG_002_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 4 65535 65535 0 0][vp 1 0 0 5 0 0]Owww![n][w][e]

[msg MSG_003_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 2 65535 65535 0 0][vp 1 0 0 6 0 0]You again...![n][w][e]

[msg MSG_004_0_0 [Spunky Boy]]
[f 2 1][vp 1 0 0 7 0 0][f 5 21 0 1001]Ah, man...[n][w][e]

[msg MSG_005_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 2 65535 65535 0 0][vp 1 0 0 8 0 0]You know it's dangerous to be running around a place like this.[n][w][e]
[f 2 1][bup 106 2 65535 65535 0 0][vp 1 0 0 9 0 0]You're lucky it's just me, but what if you bumped into a scary man, huh?[n][w][e]
[f 2 1][bup 106 2 65535 65535 0 0][vp 1 0 0 10 0 0]If you want to play, do it at your schoolyard.[n][w][e]

[msg MSG_006_0_0 [Spunky Boy]]
[f 2 1][vp 1 0 0 11 0 0][f 5 21 0 1001]But we can't play there. The sixth graders are always hogging everything by playing soccer...[n][w][e]

[msg MSG_006_3_0 [Spunky Boy]]
[f 2 1][vp 1 0 0 12 0 0][f 5 21 0 1001]They said they'll move if we can beat them in a race, but...[n][w][e]
[f 2 1][vp 1 0 0 13 0 0][f 5 21 0 1001]We're only fourth graders! There's no way we could win.[n][w][e]

[msg MSG_006_5_0 [Spunky Boy]]
[f 2 1][vp 1 0 0 14 0 0][f 5 21 0 1001]That's why we had to play tag here instead, Auntie Yuko.[n][w][e]

[msg MSG_007_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 3 65535 65535 0 0][vp 1 0 0 15 0 0]I'll let the "Auntie" slide this time, but only because I feel sorry for you.[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 16 0 0][f 4 23 0 1 0 25 25]All right, come with me.[n][w][e]

