[msg MSG_000_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 3 0 65535 5097 0 0]What a beautiful day![n][w][e]

[msg MSG_000_3_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0]I'm surprised there are so many people here today...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][f 4 23 0 6 0 25 25]I thought only Port Island got this crowded.[n][w][e]

[msg MSG_000_5_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0]I didn't visit the strip mall very often until I moved into the dorms, but I really like it here.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Sometimes you never really notice how close by these places are, huh?[n][w][e]

[msg MSG_001_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0]Um, [nl]-chan.[n][w][e]

[msg MSG_002_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5076 0 0]What do you usually do on your days off?[n][w][e]

[sel SEL_003_0_0 top]
[f 2 1]Stay in my room.[e]
[f 2 1]Spend time with friends.[e]
[f 2 1]I don't remember.[e]

[msg MSG_004_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 3 0 65535 5107 0 0][f 5 13 3 15 6]Oh, so you like staying inside, huh?[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0]Oh, really? That's kind of unexpected. I didn't take you to be the indoorsy type.[n][w][e]

[msg MSG_004_5_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0]So am I, but... I guess you could probably tell by just looking at me.[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0][f 4 23 0 6 1 25 25]But I'm happy we have that in common...[n][w][e]

[msg MND_005_0_0]
[f 2 1]Fuuka has a smile on her face.[n][w][e]
[f 2 1]I learned a little more about her today.[n][w][e]

[msg MSG_006_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 3 0 65535 5107 0 0][f 5 13 3 30 6]Oh, right. You seem to have a lot of friends.[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0][f 4 23 0 6 3 25 25]I don't really have very many...[n][w][e]

[msg MSG_007_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0]It'd be nice if we could go out and do something like this again sometime...[n][w][e]

[msg MND_008_0_0]
[f 2 1]Fuuka looks a little embarrassed.[n][w][e]
[f 2 1]I feel like we became a lot closer today.[n][w][e]

[msg MSG_009_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5094 0 0]...Oh.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][f 4 25 6]......[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0][f 4 23 0 6 3 25 25]Um, er...[n][w][e]

[msg MSG_009_5_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0]Did I bring up something I shouldn't have...?[n][w][e]

[msg MND_010_0_0]
[f 2 1]Fuuka looks worried.[n][w][e]
[f 2 1]I feel like we didn't get any closer today...[n][w][e]

[msg MSG_011_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5079 0 0]Oh, sorry for spacing out.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Since we're having such pleasant weather today, why don't we buy something and sit on a bench to eat?[n][w][e]

[msg MND_012_0_0]
[f 2 1]We walked around the strip mall for a little[n]while before heading back to the dorm.[n][w][e]

