[msg MND_000_0_0 [DEV: Internal MES]]
[f 2 1]Mr. Ono seems to have stepped out...[n][w][e]

[msg MSG_001_0_0 [Ms. Toriumi]]
[f 2 1][bup 1581 3 65535 65535 0 0][vp 3 0 65535 15834 0 0]Argh, dammit! I did it again.[n][w][e]
[f 2 1][bup 1581 3 65535 65535 0 0]When does Class 2-F have their next lecture...?[n][w][e]

[msg MSG_002_0_0 [Ms. Toriumi]]
[f 2 1][bup 1581 0 65535 65535 0 0][vp 3 0 65535 15803 0 0]Oh, [nl]-san. What's up?[n][w][e]
[f 2 1][bup 1581 1 65535 65535 0 0]Ohhh, I know. You brought me some cake, huh?[n][w][e]
[f 2 1][bup 1581 1 65535 65535 0 0]I'm not a fan of Mont Blanc, but I like all the other kinds.[n][w][e]

[msg MSG_003_0_0 [Ms. Toriumi]]
[f 2 1][bup 1581 0 65535 65535 0 0][vp 3 0 65535 15825 0 0]...Er, I didn't mean to say that. But, hey, you're here just in time![n][w][e]
[f 2 1][bup 1581 0 65535 65535 0 0]I forgot to explain something in my last lecture, so I was just gonna go tell the class real quick.[n][w][e]
[f 2 1][bup 1581 0 65535 65535 0 0]If I don't do, I'm gonna get reprimanded. It's tough being a teacher.[n][w][e]
[f 2 1][bup 1581 0 65535 65535 0 0]If I explain it to you right now, could you pass it on to everyone else?[n][w][e]
[f 2 1][bup 1581 1 65535 65535 0 0]It doesn't have to be a detailed explanation or anything. Oh, do you want some watermelon the next time I have some left over?[n][w][e]

[msg MSG_004_0_0 [Ms. Toriumi]]
[f 2 1][bup 1581 0 65535 65535 0 0][vp 3 0 65535 15831 0 0][f 4 25 1581]Ugh...[n][w][e]

[msg MSG_005_0_0 [Ms. Toriumi]]
[f 2 1][bup 1581 2 65535 65535 0 0]I can practically feel that old stickler Ekoda glaring at me... Damn, guess I'll have to do it myself.[n][w][e]
[f 2 1][bup 1581 0 65535 65535 0 0]Well, I might as well practice giving the lecture with you.[n][w][e]
[f 2 1][bup 1581 1 65535 65535 0 0]I-I mean, we've already established you're not going to give the lecture in my place, right?[n][w][e]

[msg MND_006_0_0 [DEV: Internal MES]]
[f 2 1]I listened to Ms. Toriumi's lecture alone...[n][w][e]

[msg MND_007_0_0 [DEV: Internal MES]]
[f 2 1]Mr. Ono doesn't seem to be returning.[n][w][e]
[f 2 1]I decided to give up for today.[n][w][e]

