[msg MND_000_0_0]
[f 2 1]Where am I...?[n][w][e]
[f 2 1]The Velvet Room?[n][w][e]

[msg MSG_001_0_0 [Igor]]
[f 2 1][bup 201 0 65535 65535 0 0][vp 1 0 0 1 0 0]There's no need to worry.[n][w][e]
[f 2 1][bup 201 0 65535 65535 0 0][vp 1 0 0 2 0 0]This isn't the afterlife... You're still very much alive.[n][w][e]
[f 2 1][bup 201 0 65535 65535 0 0][vp 1 0 0 3 0 0]Do you remember what I once told you?[n][w][e]
[f 2 1][bup 201 0 65535 65535 0 0][vp 1 0 0 4 0 0]How the strength of your Social Links will determine your potential?[n][w][e]

[msg MSG_002_0_0 [Igor]]
[f 2 1][bup 201 0 65535 65535 0 0][vp 1 0 0 5 0 0]Listen... Can you hear their many voices?[n][w][e]
[f 2 1][bup 201 0 65535 65535 0 0][vp 1 0 0 6 0 0]Each one's power is faint... yet they all reach out to you...[n][w][e]
[f 2 1][bup 201 0 65535 65535 0 0][vp 1 0 0 7 0 0]Can you feel them?[n][w][e]

[sel SEL_003_0_0 top]
[f 2 1]Yes, I can sense them...[e]
[f 2 1]I don't know...[e]

[msg MSG_004_0_0 [Igor]]
[f 2 1][bup 201 0 65535 65535 0 0][vp 1 0 0 8 0 0]Close your eyes and listen... Their voices may be faint, but you hear them, don't you?[n][w][e]

[msg MND_005_0_0]
[f 2 1]A mysterious mass of energy[n]is gathering in Igor's hands...[n][w][e]

[msg MND_006_0_0]
[f 2 1]I can feel my friends' powerful[n]emotions flowing into my heart.[n][w][e]

[msg MSG_007_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 1 6 65 0 0][vp 1 0 0 9 0 0]I'll always have your back, [nl].[n][w][e]
[f 2 1][bup 101 1 6 65 0 0][vp 1 0 0 10 0 0]All I can do right now is pray, but whatever it is, man...[n][w][e]
[f 2 1][bup 101 1 6 65 0 0][vp 1 0 0 11 0 0]Don't worry about a thing. I know you can do it.[n][w][e]

[msg MSG_008_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 1 2 65 0 0][vp 1 0 0 12 0 0]I know you're facing a difficult task, somewhere out there...[n][w][e]
[f 2 1][bup 102 1 2 65 0 0][vp 1 0 0 13 0 0]But I truly believe that you can overcome any obstacle.[n][w][e]

[msg MSG_009_0_0 [Bunkichi]]
[f 2 1][bup 103 1 65535 65 0 0][vp 1 0 0 14 0 0]Something frightful is going on... But we're not giving up.[n][w][e]

[msg MSG_010_0_0 [Mitsuko]]
[f 2 1][bup 104 1 65535 65 0 0][vp 1 0 0 15 0 0]That's right, dear... We have to be strong for [nf]-chan...[n][w][e]

[msg MSG_011_0_0 [Kazushi Miyamoto]]
[f 2 1][bup 105 1 101 65 0 0][vp 1 0 0 16 0 0]Something crazy's going on here... But I know you're out there doing all you can, [nl].[n][w][e]
[f 2 1][bup 105 1 101 65 0 0][vp 1 0 0 17 0 0]I'm not gonna lose hope. I learned that from you...[n][w][e]

[msg MSG_012_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 1 6 65 0 0][vp 1 0 0 18 0 0]I'm okay right now... And it's because you gave me the courage to stand on my own![n][w][e]
[f 2 1][bup 109 1 6 65 0 0][vp 1 0 0 19 0 0]So please, you can't give up...![n][w][e]

[msg MSG_013_0_0 [Maya]]
[f 2 1][bup 107 0 65535 66 0 0][vp 1 0 0 20 0 0]Oh god, I'm freaking out here! But... I know she's doing her best out there too...[n][w][e]
[f 2 1][bup 107 0 65535 66 0 0][vp 1 0 0 21 0 0]I don't even know what she looks like, but I know she's okay... I can feel it.[n][w][e]

[msg MSG_014_0_0 [Keisuke Hiraga]]
[f 2 1][bup 108 1 6 65 0 0][vp 1 0 0 22 0 0][nl]-chan... I know you're trying to stay focused...[n][w][e]
[f 2 1][bup 108 1 6 65 0 0][vp 1 0 0 23 0 0]You were there when I needed you... I hope I can do the same...[n][w][e]

[msg MSG_015_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 6 65 0 0][vp 1 0 0 24 0 0]Hey, [nl]-chan... Can you believe what's going on?[n][w][e]
[f 2 1][bup 106 1 6 65 0 0][vp 1 0 0 25 0 0]I know you must be doing everything you can, so I will, too![n][w][e]

[msg MSG_016_0_0 [Maiko]]
[f 2 1][bup 110 1 6 65 0 0][vp 1 0 0 26 0 0]Everyone else is scared, but not me...[n][w][e]
[f 2 1][bup 110 1 6 65 0 0][vp 1 0 0 27 0 0]You showed me how to be tough![n][w][e]
[f 2 1][bup 110 1 6 65 0 0][vp 1 0 0 28 0 0]I won't give up.[n][w][e]

[msg MSG_017_0_0 [Bebe]]
[f 2 1][bup 112 1 6 65 0 0][vp 1 0 0 29 0 0][nf]-sama, how are you doing? Ça va, I hope...[n][w][e]
[f 2 1][bup 112 1 6 65 0 0][vp 1 0 0 30 0 0]I am here for you... like you were there for me![n][w][e]

[msg MSG_018_0_0 [President Tanaka]]
[f 2 1][bup 113 1 65535 65 0 0][vp 1 0 0 31 0 0]What on earth made me think of you at a time like this?[n][w][e]
[f 2 1][bup 113 1 65535 65 0 0][vp 1 0 0 32 0 0]Well, I suppose you did teach me a thing or two about trust...[n][w][e]

[msg MSG_019_0_0 [Mutatsu]]
[f 2 1][bup 114 1 65535 65 0 0][vp 1 0 0 33 0 0]You were the one who taught me that runnin' away never solves nothin'...[n][w][e]
[f 2 1][bup 114 1 65535 65 0 0][vp 1 0 0 34 0 0]And I bet you're somewhere out there fightin' the good fight right now...[n][w][e]
[f 2 1][bup 114 1 65535 65 0 0][vp 1 0 0 35 0 0]Well, I'm here for ya too, kid.[n][w][e]

[msg MSG_020_0_0 [Mamoru Hayase]]
[f 2 1][bup 115 1 65535 65 0 0][vp 1 0 0 36 0 0]I'll take on any challenge that comes my way without passing blame...[n][w][e]
[f 2 1][bup 115 1 65535 65 0 0][vp 1 0 0 37 0 0]You taught me that, [nl]... I bet you're fighting right now too, huh.[n][w][e]

[msg MSG_021_0_0 [Nozomi Suemitsu]]
[f 2 1][bup 116 1 2 65 0 0][vp 1 0 0 38 0 0]You saved me, [nf]-chan. I was so blind before...[n][w][e]
[f 2 1][bup 116 1 2 65 0 0][vp 1 0 0 39 0 0]I'm sure you've got things under control, right? You always do.[n][w][e]

[msg MSG_022_0_0 [Akinari Kamiki]]
[f 2 1][bup 117 1 65535 65 0 0][vp 1 0 0 40 0 0]I know I'm not the only one who's suffered... You've endured a lot, too.[n][w][e]
[f 2 1][bup 117 1 65535 65 0 0][vp 1 0 0 41 0 0]But you can't just give up... You taught me that.[n][w][e]

[msg MSG_023_0_0 [Igor]]
[f 2 1][bup 201 0 65535 65535 0 0][vp 1 0 0 42 0 0]Can you hear them?[n][w][e]
[f 2 1][bup 201 0 65535 65535 0 0][vp 1 0 0 43 0 0]These are the voices of hope that wish to help you...[n][w][e]
[f 2 1][bup 201 0 65535 65535 0 0][vp 1 0 0 44 0 0]Separately, they are weak... But together, they will bring about a great change in you.[n][w][e]
[f 2 1][bup 201 0 65535 65535 0 0][vp 1 0 0 45 0 0]Now is the time to draw on the true strength of the bonds you have forged![n][w][e]

[msg MSG_024_0_0 [Igor]]
[f 2 1][bup 201 0 65535 65535 0 0][vp 1 0 0 46 0 0]I never dreamed of seeing that card with my own eyes...[n][w][e]
[f 2 1][bup 201 0 65535 65535 0 0][vp 1 0 0 47 0 0]This is indeed a surprise...[n][w][e]
[f 2 1][bup 201 0 65535 65535 0 0][vp 1 0 0 48 0 0]Behold the greatest power that you and I shall unveil.[n][w][e]
[f 2 1][bup 201 0 65535 65535 0 0][vp 1 0 0 49 0 0]It is the power to bring about a new beginning, or the ultimate end.[n][w][e]

[msg MSG_025_0_0 [Igor]]
[f 2 1][bup 201 0 65535 65535 0 0][vp 1 0 0 50 0 0]With this newfound power, it might now be possible...[n][w][e]
[f 2 1][bup 201 0 65535 65535 0 0][vp 1 0 0 51 0 0]Perhaps you can save those you hold dear, from that which cannot be defeated.[n][w][e]
[f 2 1][bup 201 0 65535 65535 0 0][vp 1 0 0 52 0 0]What you have in your hands is the power of the Universe...[n][w][e]
[f 2 1][bup 201 0 65535 65535 0 0][vp 1 0 0 53 0 0]Nothing is outside the realm of possibility for you now.[n][w][e]

[msg MSG_026_0_0 [Elizabeth]]
[f 2 1][bup 202 0 65535 65535 0 0][vp 1 0 0 54 0 0]We will soon reach your destination.[n][w][e]

[msg MSG_027_0_0 [Igor]]
[f 2 1][bup 201 0 65535 65535 0 0][vp 1 0 0 55 0 0]It seems that, in addition to Death, fate has also dealt you the wild card.[n][w][e]
[f 2 1][bup 201 0 65535 65535 0 0][vp 1 0 0 56 0 0]You must accept your destiny.[n][w][e]
[f 2 1][bup 201 0 65535 65535 0 0][vp 1 0 0 57 0 0]Our contract has been fulfilled... I have completed my role as well.[n][w][e]
[f 2 1][bup 201 0 65535 65535 0 0][vp 1 0 0 58 0 0]You were truly a most remarkable guest.[n][w][e]

