[msg MSG_000_0_0 [Bartender]]
[f 2 1][vp 1 0 6 1 160 0]Aren't you the girl who used to talk to the monk upstairs?[n][w][e]
[f 2 1][vp 1 0 6 2 160 0]He actually called here trying to reach you. Seems like he was wondering how you were doing.[n][w][e]
[f 2 1][vp 1 0 6 3 160 0]Come to think of it, I think he left a message for you...[n][w][e]
[f 2 1][vp 1 0 6 4 160 0]What was it he said again...?[n][w][e]
[f 2 1][vp 1 0 6 5 160 0]Hey, hey, don't give me that look. Just hang on a sec.[n][w][e]

[msg MSG_001_0_0 [Bartender]]
[f 2 1][vp 1 0 6 6 160 0]Found it! Here you go.[n][w][e]
[f 2 1][vp 1 0 6 7 160 0]I actually wrote it all down. Didn't think I had it in me, did ya?[n][w][e]
[f 2 1][vp 1 0 6 8 160 0]Let's see... Oh man, the handwriting is awful. Who the hell wrote this...?[n][w][e]

[msg MSG_002_0_0 [Letter from Mutatsu]]
[f 2 1][vp 1 0 6 9 160 0]"I found my wife and son."[n][w][e]
[f 2 1][vp 1 0 6 10 160 0]"My son's still a good-for-nothing punk, and my wife is frigid as usual..."[n][w][e]
[f 2 1][vp 1 0 6 11 160 0]"She's like an old witch... What do you want!? I'm on the phone! ...Hey, don't write this down, alright?"[n][w][e]
[f 2 1][vp 1 0 6 12 160 0]"A lot's happened, but I apologized a thousand times, and I worked to make things right."[n][w][e]
[f 2 1][vp 1 0 6 13 160 0]"I guess you could say we fell in love all over again."[n][w][e]
[f 2 1][vp 1 0 6 14 160 0]"I realized..."[n][w][e]
[f 2 1][vp 1 0 6 15 160 0]"Instead of holding onto my pride, I needed to just suck it up and apologize."[n][w][e]
[f 2 1][vp 1 0 6 16 160 0]"And it's all thanks to you, [nl]..."[n][w][e]
[f 2 1][vp 1 0 6 17 160 0]"...Well, you take care, kid. If it's meant to be, we'll see each other again."[n][w][e]

[msg MSG_003_0_0 [Bartender]]
[f 2 1][vp 1 0 6 18 160 0]...That's the gist of it. I'm pretty sure I got everything he said.[n][w][e]
[f 2 1][vp 1 0 6 19 160 0]Oh, and don't bother asking for a number. He didn't say.[n][w][e]
[f 2 1][vp 1 0 6 20 160 0]But like he said, you'll see him again if it's meant to be.[n][w][e]
[f 2 1][vp 1 0 6 21 160 0]Don't they say like... fate lies in God's hands or something...? Oh, wait, that'd be Buddha for the monk, huh...[n][w][e]
[f 2 1][vp 1 0 6 22 160 0]Anyways, that's that. If fate does bring you two back together, why don'tcha come party over here again?[n][w][e]

[msg MSG_004_0_0 [Bartender]]

[msg MSG_005_0_0 [Bartender]]
[f 2 1][vp 1 0 6 27 160 0]The monk left you a bottle tag, didn't he? I'd give you the bottle, but...[n][w][e]
[f 2 1][vp 1 0 6 28 160 0]How many years will it be until you're old enough to drink? ...Well, I'll save it specially for you.[n][w][e]
[f 2 1][vp 1 0 6 29 160 0]Until then, make sure you stick to soft drinks. I'll see ya around.[n][w][e]

[msg MSG_006_0_0 [Bartender]]

