[msg MSG_000_0_0 [Nozomi Suemitsu]]
[f 2 1][bup 116 0 65535 65535 0 0][vp 1 0 4 1 0 0]Well, look who we have here. Is the Kyoto cuisine to your liking, [nl]-chan?[n][w][e]
[f 2 1][bup 116 0 65535 65535 0 0][vp 1 0 4 2 0 0]Honestly speaking, I have little interest in the plant-based fare they have going on here.[n][w][e]
[f 2 1][bup 116 0 65535 65535 0 0][vp 1 0 4 3 0 0]I sampled the food the souvenir shop had to offer, but I find myself unimpressed...[n][w][e]

[msg MSG_001_0_0 [Nozomi Suemitsu]]
[f 2 1][bup 116 0 65535 65535 0 0][vp 1 0 4 4 0 0]...Looks like you're still wet behind the ears.[n][w][e]
[f 2 1][bup 116 0 65535 65535 0 0][vp 1 0 4 5 0 0]Listen closely, all right? No gourmet worth their salt would be caught wearing a yukata.[n][w][e]
[f 2 1][bup 116 0 65535 65535 0 0][vp 1 0 4 6 0 0]We eat![n][w][e]
[f 2 1][bup 116 0 65535 65535 0 0][vp 1 0 4 7 0 0]Our belly expands![n][w][e]
[f 2 1][bup 116 0 65535 65535 0 0][vp 1 0 4 8 0 0]The sash gets too tight![n][w][e]
[f 2 1][bup 116 0 65535 65535 0 0][vp 1 0 4 9 0 0]So we loosen it![n][w][e]
[f 2 1][bup 116 0 65535 65535 0 0][vp 1 0 4 10 0 0]Then we eat some more![n][w][e]
[f 2 1][bup 116 0 65535 65535 0 0][vp 1 0 4 11 0 0]We loosen the sash more![n][w][e]
[f 2 1][bup 116 0 65535 65535 0 0][vp 1 0 4 12 0 0]The sash falls off![n][w][e]
[f 2 1][bup 116 0 65535 65535 0 0][vp 1 0 4 13 0 0]We're left in the nude![n][w][e]
[f 2 1][bup 116 0 65535 65535 0 0][vp 1 0 4 14 0 0]You follow me..? Too far, huh? Well you look good enough. Your forgiven.[n][w][e]

[msg MSG_002_0_0 [Nozomi Suemitsu]]
[f 2 1][bup 116 0 65535 65535 0 0][vp 1 0 4 15 0 0]You're stark naked, and your belly's all cold. Now, that's a real emergency.[n][w][e]

[msg MSG_003_0_0 [Nozomi Suemitsu]]
[f 2 1][bup 116 0 65535 65535 0 0][vp 3 0 65535 12609 0 0]Oh, it's you![n][w][e]
[f 2 1][bup 116 0 65535 65535 0 0][vp 1 0 4 1 0 0]I've been debating what to eat next.[n][w][e]
[f 2 1][bup 116 0 65535 65535 0 0][vp 1 0 4 2 0 0]So far I've had senbei, nama-yatsuhashi, more nama-yatsuhashi, senmaizuke...[n][w][e]
[f 2 1][bup 116 0 65535 65535 0 0][vp 1 0 4 3 0 0]Then more nama-yatsuhashi, senbei again, and senbei again... Now what?[n][w][e]

[sel SEL_004_0_0 top]
[f 2 1]Nama-yatsuhashi.[e]
[f 2 1]Senmaizuke.[e]
[f 2 1]Just eat whatever you want.[e]

[msg MSG_005_0_0 [Nozomi Suemitsu]]
[f 2 1][bup 116 0 65535 65535 0 0][vp 1 0 4 4 0 0]Ah, yes, the raw, unbaked confectionery! Getting dessert next does make the most logical sense.[n][w][e]

[msg MSG_006_0_0 [Nozomi Suemitsu]]
[f 2 1][bup 116 0 65535 65535 0 0][vp 1 0 4 5 0 0]Ah, yes! One thousand slices— Hm, that's quite a lot, isn't it? Still, I shall attempt the thousand pickle challenge![n][w][e]

[msg MSG_007_0_0 [Nozomi Suemitsu]]
[f 2 1][bup 116 0 65535 65535 0 0][vp 1 0 4 6 0 0]What!? You're making me decide!? How could I, lost in this state of hunger...? Hmmm.[n][w][e]

[msg MSG_008_0_0 [Nozomi Suemitsu]]
[f 2 1][bup 116 0 65535 65535 0 0][vp 1 0 4 7 0 0]Too much of a good thing can be a bad thing—and that goes for Kyoto's healthy cuisine, too. Now that's deep...[n][w][e]

[msg MSG_009_0_0 [Nozomi Suemitsu]]
[f 2 1][bup 116 0 65535 65535 0 0][vp 1 0 4 8 0 0]The local food in Kyoto might be healthy, but that matters little when eating in excess...[n][w][e]

[msg MND_GENERAL_EVENTPLAY]
[f 2 1]Message issued by the script. [n][f 1 5 0]Comm Event Replay.[n][w][e]

[msg MND_GENERAL_PERSPNA]
[f 2 1]I feel as if we can grow closer thanks to the[n][f 2 4 2] Persona, [clr 35][f 2 4 5][clr 27]...[n][w][e]

[msg MND_GENERALSELECTMSG_MAX]
[f 2 1]I feel an unbreakable bond[n]with [f 2 4 0]...[n][w][e]

[msg MND_GENERALMSG_BS_MAX]
[f 2 1]I feel an unbreakable bond[n]with the elderly couple...[n][w][e]

[msg MND_GENERALSELECTMSG_RAN]
[f 2 1]I feel like I might grow closer[n]to [f 2 4 0] soon...[n][w][e]

[msg MND_GENERALMSG_BS_RANKUP]
[f 2 1]I feel like I might grow closer[n]to the elderly couple soon...[n][w][e]

[msg MND_GENERALSELECTMSG_NOR]
[f 2 1]I don't think our bond will grow[n]any stronger even if I spend[n]more time with [f 2 4 0]...[n][w][e]

[msg MND_GENERALMSG_BS_NORMAL [Nozomi Suemitsu]]
[f 2 1]I don't think our bond will grow[n]any stronger even if I spend[n]more time with them...[n][w][e]

[msg MND_GENERALSELECTMSG_MAX_2]
[f 2 1]It doesn't seem that our relationship[n]can get any closer than it is...[n][w][e]
[f 2 1]Should I still spend time with them...?[n][w][e]

[msg MND_GENERAL_MSG_SOLO_AS]
[f 2 1]Should I spend some time after[n]school with [f 2 4 0]?[n][w][e]

[msg MND_GENERAL_MSG_SOLO_DT]
[f 2 1]Should I spend the day[n]with [f 2 4 0]?[n][w][e]

[msg MND__GENERAL_MSG_NET]
[f 2 1]Should I spend time online playing[n]the MMORPG with [f 2 4 0]...?[n][w][e]

[msg MND_GENERAL_MSG_SOLO_NT]
[f 2 1]Should I spend the evening[n]with [f 2 4 0]?[n][w][e]

[sel SEL_GENERALSELECTMSG_SOL top]
[f 2 1]Spend time with [f 2 4 0][e]
[f 2 1]Check Social Link[e]
[f 2 1]Never mind[e]

[msg MND_GENERAL_MSG_MULTIPLE]
[f 2 1]Should I spend some time after[n]school with the [f 2 4 1]?[n][w][e]

[msg MND_GENERAL_MSG_FASHION_]
[f 2 1]Should I spend some time after[n]school at the fashion club?[n][w][e]

[msg MND_GENERAL_MSG_BOOKSTOR]
[f 2 1]Should I spend the day at the bookstore?[n][w][e]

[msg MND_GENERAL_MSG_BOOKSTOR_2]
[f 2 1]Should I spend some time[n]after school at the bookstore?[n][w][e]

[msg MND_GENERAL_MSG_MULTIPLE_2]
[f 2 1]Should I spend the night[n]with [f 2 4 1]?[n][w][e]

[sel SEL_GENERALSELECTMSG_MUL top]
[f 2 1]Spend time w/ [f 2 4 1][e]
[f 2 1]Check Social Link[e]
[f 2 1]Never mind[e]

[sel SEL_GENERALSELECTMSG_FCL top]
[f 2 1]Go to the fashion club[e]
[f 2 1]Check Social Link[e]
[f 2 1]Never mind[e]

[sel SEL_GENERALSELECTMSG_BS top]
[f 2 1]Enter the bookstore[e]
[f 2 1]Check Social Link[e]
[f 2 1]Never mind[e]

[msg MSG_GENERAL_EXAMREWARD_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4029 0 0]Ah, [nl].[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]I saw your exam results. Good work.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Here, this is from the chairman.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4108 0 0]It's a reward for effectively balancing schoolwork as well as our... ahem, "extracurricular activities."[n][w][e]

[msg MND_GENERAL_EXAMREWARD_0]
[f 2 1]DEV: UNUSED LABEL[n][w][e]

[msg MND_GENERAL_EXAMREWARD_0_2]
[f 2 1]Since I placed at the top in the exams,[n]I also got this [f 4 4 1 37 1 3].[n][w][e]

[msg MSG_GENERAL_EXAMREWARD_0_2 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4029 0 0]Ah, [nl].[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]I saw your exam results. Good work.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Here, this is from the chairman.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4108 0 0]It's a reward for effectively balancing schoolwork as well as our... ahem, "extracurricular activities."[n][w][e]

[msg MSG_GENERAL_EXAMREWARD_0_3 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4077 0 0]Oh, right. There's something else...[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]I saw your exam results. Good work.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Here, this is from the chairman.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4131 0 0]It's a reward for effectively balancing schoolwork as well as our... ahem, "extracurricular activities."[n][w][e]

[msg MND_GENERAL_EXAMREWARD_0_3]
[f 2 1]Since I placed at the top in the exams,[n]I also got this [f 4 4 1 37 1 3].[n][w][e]

[msg MSG_GENERAL_EXAMREWARD_0_4 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4029 0 0]Ah, [nl].[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]I saw your exam results. Good work.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Here, this is from the chairman.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4108 0 0]It's a reward for effectively balancing schoolwork as well as our... ahem, "extracurricular activities."[n][w][e]

[msg MND_GENERAL_EXAMREWARD_0_4]
[f 2 1]DEV: UNUSED LABEL[n][w][e]

[msg MSG_GENERAL_EXAMREWARD_0_5 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4029 0 0]Ah, [nl].[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]I saw your exam results... Good work.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]It's admirable how you continue to excel in school while fighting arduous battle after battle.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0]I got you a gift to acknowledge all your hard work. Here, take it.[n][w][e]

[msg MND_GENERAL_EXAMREWARD_0_5]
[f 2 1]未使用ラベルです。[n][w][e]

[msg MSG_GENERAL_EXAMREWARD_0_6 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 6 65535 0 0][vp 3 0 65535 4029 0 0]Ah, [nl].[n][w][e]
[f 2 1][bup 5 0 6 65535 0 0]I saw your exam results. Good work.[n][w][e]
[f 2 1][bup 5 0 6 65535 0 0]It's admirable how you continue to excel in school while fighting arduous battle after battle.[n][w][e]
[f 2 1][bup 5 0 6 65535 0 0]I got you a gift to acknowledge all your hard work. Here, take it.[n][w][e]

[msg MND_GENERAL_EXAMREWARD_1]
[f 2 1]Since I placed at the top in the exams,[n]I also got this [f 4 4 1 37 1 3].[n][w][e]

[msg MSG_GENERAL_EXAMREWARD_1 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4029 0 0]Ah, [nl].[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]I saw your exam results. Good work.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]It's admirable how you continue to excel in school while fighting arduous battle after battle.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4108 0 0]I got you a gift to acknowledge all your hard work. Here, take it.[n][w][e]

[msg MND_GENERAL_EXAMREWARD_1_2]
[f 2 1]DEV: UNUSED LABEL[n][w][e]

[msg MND_GENERAL_EXAMREWARD_1_3]
[f 2 1]Since I placed at the top in the exams,[n]I also got this [f 4 4 1 37 1 3].[n][w][e]

