[msg MSG_000_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 0 65535 65535 0 0][vp 3 0 65535 10001 0 0]Yo, [nl].[n][w][e]
[f 2 1][bup 101 3 65535 65535 0 0]I was just about to head home, but I don't really feel up to walking...[n][w][e]
[f 2 1][bup 101 1 65535 65535 0 0]Hey, don't get the wrong idea. I'm not gonna go looking for an unlocked bicycle, alright?[n][w][e]

[msg MSG_001_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 0 65535 65535 0 0][vp 3 0 65535 10010 0 0]Oh, [nl].[n][w][e]
[f 2 1][bup 101 3 65535 65535 0 0]I was just about to head to cram school, but I don't really feel up to walking there...[n][w][e]
[f 2 1][bup 101 1 65535 65535 0 0]Hey, don't get the wrong idea. I'm not gonna go looking for an unlocked bicycle, alright?[n][w][e]

[msg MSG_002_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 0 65535 65535 0 0][vp 3 0 65535 10002 0 0]Oh! Hey, [nl].[n][w][e]
[f 2 1][bup 101 0 65535 65535 0 0]If I'm gonna buy a gift for a girl, I should probably get her a bouquet of flowers, right?[n][w][e]
[f 2 1][bup 101 1 65535 65535 0 0]I bet if I bought something like that, we'd get a lot closer.[n][w][e]

[msg MSG_003_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 0 65535 65535 0 0][vp 3 0 65535 10056 0 0]Oh, what's up, [nl]?[n][w][e]
[f 2 1][bup 101 0 65535 65535 0 0]Hey, if you were gonna give someone a present, what would it be?[n][w][e]
[f 2 1][bup 101 0 65535 65535 0 0]Hm, I think Emiri would love a bouquet of roses...[n][w][e]
[f 2 1][bup 101 1 65535 65535 0 0]I bet if I gave her something like that, we'd get a lot closer.[n][w][e]

[msg MSG_004_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 0 65535 65535 0 0][vp 3 0 65535 10009 0 0]Hey, [nl]. You studyin' for exams?[n][w][e]
[f 2 1][bup 101 1 65535 65535 0 0]I'm headin' home. It'd be straight up embarrassin' if I didn't pass.[n][w][e]
[f 2 1][bup 101 3 65535 65535 0 0]Yeah, yeah, I know I should study regularly, but I got other priorities, you know?[n][w][e]
[f 2 1][bup 101 1 65535 65535 0 0]Maybe I could study in the library, but I can't really deal with the atmosphere in there.[n][w][e]

[msg MSG_005_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 0 65535 65535 0 0][vp 3 0 65535 10001 0 0]Yo, what's up, [nl]?[n][w][e]
[f 2 1][bup 101 0 65535 65535 0 0]I'm feelin' pretty good, man.[n][w][e]
[f 2 1][bup 101 1 65535 65535 0 0]Hey, promise me you'll do whatever you want, whenever you want while we're still young, alright?[n][w][e]
[f 2 1][bup 101 1 65535 65535 0 0][vp 3 0 65535 10094 0 0]...I'll always have your back, dude.[n][w][e]

[msg MND_006_0_0]
[f 2 1]I feel an unbreakable bond[n]with Tomochika...[n][w][e]

[msg MSG_007_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 0 65535 65535 0 0][vp 3 0 65535 10002 0 0]Yo, [nl].[n][w][e]
[f 2 1][bup 101 3 65535 65535 0 0]If you're gonna give your girl a present, it's gotta be flowers, right? Well, not like I have anyone special in my life anymore.[n][w][e]
[f 2 1][bup 101 1 65535 65535 0 0]But I bet if I gave a girl some kinda gift, we'd get closer in no time.[n][w][e]
[f 2 1][bup 101 6 65535 65535 0 0][vp 3 0 65535 10084 0 0]Man... If only the girl of my dreams would show up right in front of me.[n][w][e]

[msg MND_GENERAL_EVENTPLAY]
[f 2 1]Message issued by the script. [n][f 1 5 0]Comm Event Replay.[n][w][e]

[msg MND_GENERAL_PERSPNA]
[f 2 1]I feel as if we can grow closer thanks to the[n][f 2 4 2] Persona, [clr 35][f 2 4 5][clr 27]...[n][w][e]

[msg MND_GENERALSELECTMSG_MAX]
[f 2 1]I feel an unbreakable bond[n]with [f 2 4 0]...[n][w][e]

[msg MND_GENERALMSG_BS_MAX]
[f 2 1]I feel an unbreakable bond[n]with the elderly couple...[n][w][e]

[msg MND_GENERALSELECTMSG_RAN]
[f 2 1]I feel like I might grow closer[n]to [f 2 4 0] soon...[n][w][e]

[msg MND_GENERALMSG_BS_RANKUP]
[f 2 1]I feel like I might grow closer[n]to the elderly couple soon...[n][w][e]

[msg MND_GENERALSELECTMSG_NOR]
[f 2 1]I don't think our bond will grow[n]any stronger even if I spend[n]more time with [f 2 4 0]...[n][w][e]

[msg MND_GENERALMSG_BS_NORMAL [Kenji Tomochika]]
[f 2 1]I don't think our bond will grow[n]any stronger even if I spend[n]more time with them...[n][w][e]

[msg MND_GENERALSELECTMSG_MAX_2]
[f 2 1]It doesn't seem that our relationship[n]can get any closer than it is...[n][w][e]
[f 2 1]Should I still spend time with them...?[n][w][e]

[msg MND_GENERAL_MSG_SOLO_AS]
[f 2 1]Should I spend some time after[n]school with [f 2 4 0]?[n][w][e]

[msg MND_GENERAL_MSG_SOLO_DT]
[f 2 1]Should I spend the day[n]with [f 2 4 0]?[n][w][e]

[msg MND__GENERAL_MSG_NET]
[f 2 1]Should I spend time online playing[n]the MMORPG with [f 2 4 0]...?[n][w][e]

[msg MND_GENERAL_MSG_SOLO_NT]
[f 2 1]Should I spend the evening[n]with [f 2 4 0]?[n][w][e]

[sel SEL_GENERALSELECTMSG_SOL top]
[f 2 1]Spend time with [f 2 4 0][e]
[f 2 1]Check Social Link[e]
[f 2 1]Never mind[e]

[msg MND_GENERAL_MSG_MULTIPLE]
[f 2 1]Should I spend some time after[n]school with the [f 2 4 1]?[n][w][e]

[msg MND_GENERAL_MSG_FASHION_]
[f 2 1]Should I spend some time after[n]school at the fashion club?[n][w][e]

[msg MND_GENERAL_MSG_BOOKSTOR]
[f 2 1]Should I spend the day at the bookstore?[n][w][e]

[msg MND_GENERAL_MSG_BOOKSTOR_2]
[f 2 1]Should I spend some time[n]after school at the bookstore?[n][w][e]

[msg MND_GENERAL_MSG_MULTIPLE_2]
[f 2 1]Should I spend the night[n]with [f 2 4 1]?[n][w][e]

[sel SEL_GENERALSELECTMSG_MUL top]
[f 2 1]Spend time w/ [f 2 4 1][e]
[f 2 1]Check Social Link[e]
[f 2 1]Never mind[e]

[sel SEL_GENERALSELECTMSG_FCL top]
[f 2 1]Go to the fashion club[e]
[f 2 1]Check Social Link[e]
[f 2 1]Never mind[e]

[sel SEL_GENERALSELECTMSG_BS top]
[f 2 1]Enter the bookstore[e]
[f 2 1]Check Social Link[e]
[f 2 1]Never mind[e]

[msg MSG_GENERAL_EXAMREWARD_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4029 0 0]Ah, [nl].[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]I saw your exam results. Good work.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Here, this is from the chairman.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4108 0 0]It's a reward for effectively balancing schoolwork as well as our... ahem, "extracurricular activities."[n][w][e]

[msg MND_GENERAL_EXAMREWARD_0]
[f 2 1]DEV: UNUSED LABEL[n][w][e]

[msg MND_GENERAL_EXAMREWARD_0_2]
[f 2 1]Since I placed at the top in the exams,[n]I also got this [f 4 4 1 37 1 3].[n][w][e]

[msg MSG_GENERAL_EXAMREWARD_0_2 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4029 0 0]Ah, [nl].[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]I saw your exam results. Good work.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Here, this is from the chairman.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4108 0 0]It's a reward for effectively balancing schoolwork as well as our... ahem, "extracurricular activities."[n][w][e]

[msg MSG_GENERAL_EXAMREWARD_0_3 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4077 0 0]Oh, right. There's something else...[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]I saw your exam results. Good work.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Here, this is from the chairman.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4131 0 0]It's a reward for effectively balancing schoolwork as well as our... ahem, "extracurricular activities."[n][w][e]

[msg MND_GENERAL_EXAMREWARD_0_3]
[f 2 1]Since I placed at the top in the exams,[n]I also got this [f 4 4 1 37 1 3].[n][w][e]

[msg MSG_GENERAL_EXAMREWARD_0_4 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4029 0 0]Ah, [nl].[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]I saw your exam results. Good work.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Here, this is from the chairman.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4108 0 0]It's a reward for effectively balancing schoolwork as well as our... ahem, "extracurricular activities."[n][w][e]

[msg MND_GENERAL_EXAMREWARD_0_4]
[f 2 1]DEV: UNUSED LABEL[n][w][e]

[msg MSG_GENERAL_EXAMREWARD_0_5 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4029 0 0]Ah, [nl].[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]I saw your exam results... Good work.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]It's admirable how you continue to excel in school while fighting arduous battle after battle.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0]I got you a gift to acknowledge all your hard work. Here, take it.[n][w][e]

[msg MND_GENERAL_EXAMREWARD_0_5]
[f 2 1]未使用ラベルです。[n][w][e]

[msg MSG_GENERAL_EXAMREWARD_0_6 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 6 65535 0 0][vp 3 0 65535 4029 0 0]Ah, [nl].[n][w][e]
[f 2 1][bup 5 0 6 65535 0 0]I saw your exam results. Good work.[n][w][e]
[f 2 1][bup 5 0 6 65535 0 0]It's admirable how you continue to excel in school while fighting arduous battle after battle.[n][w][e]
[f 2 1][bup 5 0 6 65535 0 0]I got you a gift to acknowledge all your hard work. Here, take it.[n][w][e]

[msg MND_GENERAL_EXAMREWARD_1]
[f 2 1]Since I placed at the top in the exams,[n]I also got this [f 4 4 1 37 1 3].[n][w][e]

[msg MSG_GENERAL_EXAMREWARD_1 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4029 0 0]Ah, [nl].[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]I saw your exam results. Good work.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]It's admirable how you continue to excel in school while fighting arduous battle after battle.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4108 0 0]I got you a gift to acknowledge all your hard work. Here, take it.[n][w][e]

[msg MND_GENERAL_EXAMREWARD_1_2]
[f 2 1]DEV: UNUSED LABEL[n][w][e]

[msg MND_GENERAL_EXAMREWARD_1_3]
[f 2 1]Since I placed at the top in the exams,[n]I also got this [f 4 4 1 37 1 3].[n][w][e]

