[msg MSG_000_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 0 65535 65535 0 0][vp 1 0 0 1 0 0]Sorry to drag you along while I go shopping...[n][w][e]

[sel SEL_001_0_0 top]
[f 2 1]Don't worry about it.[e]
[f 2 1]I was bored anyway.[e]

[msg MSG_002_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 1 65535 65535 0 0][vp 1 0 0 2 0 0][f 5 13 9 15 109]If you say so... But, um... thank you...[n][w][e]

[msg MSG_003_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 0 65535 65535 0 0][vp 1 0 0 3 0 0]I was so busy searching through the books... I'm sorry if I ignored you, [nl]-san.[n][w][e]

[msg MSG_004_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 3 65535 65535 0 0][vp 1 0 0 4 0 0]B-But even so! I notice how you're always so willing to help me, [nl]-san![n][w][e]
[f 2 1][bup 109 3 65535 65535 0 0][vp 1 0 0 5 0 0]I-It's my fault, isn't it? I didn't mean to make you feel guilty about it...[n][w][e]

[msg MSG_005_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 3 65535 65535 0 0][vp 1 0 0 6 0 0]Um... I'm sorry I took so long...[n][w][e]
[f 2 1][bup 109 0 65535 65535 0 0][vp 1 0 0 7 0 0][f 4 23 0 109 1 25 25]This place has so many interesting books, I was having a bit of trouble deciding.[n][w][e]

[msg MSG_006_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 0 65535 65535 0 0][vp 1 0 0 8 0 0]...Um, do you read much, [nl]-san?[n][w][e]

[sel SEL_007_0_0 top]
[f 2 1]I read the classics.[e]
[f 2 1]I read manga.[e]
[f 2 1]I read fashion magazines.[e]
[f 2 1]I don't read books.[e]

[msg MSG_008_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 1 65535 65535 0 0][vp 1 0 0 9 0 0][f 5 13 9 5 109]Really!? I, um... didn't think you'd be into that kind of thing...[n][w][e]

[msg MSG_009_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 0 65535 65535 0 0][vp 1 0 0 10 0 0]The classics aren't very entertaining, but I can respect what the authors were trying to accomplish.[n][w][e]

[msg MSG_010_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 1 65535 65535 0 0][vp 1 0 0 11 0 0][f 5 13 9 5 109]I love manga too. My bookshelf is full of shojo manga.[n][w][e]

[msg MSG_011_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 0 65535 65535 0 0][vp 1 0 0 12 0 0]I tend to get frustrated when the main character can't ask out the guy she likes. I think it's because I can relate to her...[n][w][e]

[msg MSG_012_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 0 65535 65535 0 0][vp 1 0 0 13 0 0]I'm actually not too familiar with that sort of thing... Not that it's uninteresting or anything...[n][w][e]
[f 2 1][bup 109 0 65535 65535 0 0][vp 1 0 0 14 0 0]I'm just clueless when it comes to fashion. I'm nothing like you, [nl]-san...[n][w][e]

[msg MSG_013_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 3 65535 65535 0 0][vp 1 0 0 15 0 0]I-I'm sorry. I'm not very good at carrying a conversation...[n][w][e]

[msg MSG_014_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 0 65535 65535 0 0][vp 1 0 0 16 0 0]That makes sense... The Internet makes information so accessible these days.[n][w][e]
[f 2 1][bup 109 0 65535 65535 0 0][vp 1 0 0 17 0 0]So it's kind of a waste of money to buy books, isn't it...?[n][w][e]

[msg MSG_015_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 3 65535 65535 0 0][vp 1 0 0 18 0 0]...Oh, I'm sorry! This, um, probably isn't the best place to talk...[n][w][e]
[f 2 1][bup 109 3 65535 65535 0 0][vp 1 0 0 19 0 0]The shop owners probably wouldn't want us standing here either...[n][w][e]

[msg MSG_016_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 0 65535 65535 0 0][vp 1 0 0 20 0 0]Um, hey... [nl]-san?[n][w][e]
[f 2 1][bup 109 0 65535 65535 0 0][vp 1 0 0 21 0 0]Is it boring for you to hang around with, um... someone like me?[n][w][e]

[sel SEL_017_0_0 top]
[f 2 1]I'm having fun.[e]
[f 2 1]Yeah, it's a drag.[e]
[f 2 1]I'm indifferent.[e]

[msg MSG_018_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 1 65535 65535 0 0][vp 1 0 0 22 0 0][f 5 13 9 5 109]O-Oh, what a relief. I've been so worried about that this entire time...[n][w][e]

[msg MSG_019_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 3 65535 65535 0 0][vp 1 0 0 23 0 0]I-I'm sorry! I didn't mean to waste your time...[n][w][e]

[msg MSG_020_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 3 65535 65535 0 0][vp 1 0 0 24 0 0]Wh-What? You're spending time with me even though you don't care?[n][w][e]

[msg MSG_021_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 0 65535 65535 0 0][vp 1 0 0 25 0 0]Oh, um... Well...[n][w][e]
[f 2 1][bup 109 1 65535 65535 0 0][vp 1 0 0 26 0 0][f 4 23 0 109 1 25 25]T-Today, I was able to, um, say what was on my mind to you, [nl]-san.[n][w][e]

[msg MSG_022_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 0 65535 65535 0 0][vp 1 0 0 27 0 0]...I want to stop being so afraid of everything, and I want to be able to talk to other people.[n][w][e]
[f 2 1][bup 109 0 65535 65535 0 0][vp 1 0 0 28 0 0]My homeroom teacher, Mr. Takenozuka... He gives me a lot of class-related tasks.[n][w][e]
[f 2 1][bup 109 0 65535 65535 0 0][vp 1 0 0 29 0 0]But I'm always so scared, that all I can do is nod...[n][w][e]

[sel SEL_023_0_0 top]
[f 2 1]Are you only like this with guys?[e]
[f 2 1]Why are you so afraid?[e]

[msg MSG_024_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 3 65535 65535 0 0][vp 1 0 0 30 0 0]Well... It's not much of a story, but... my dad is a very scary person.[n][w][e]
[f 2 1][bup 109 3 65535 65535 0 0][vp 1 0 0 31 0 0]I'm not living with him anymore, but I can still remember the face he made when he got mad.[n][w][e]
[f 2 1][bup 109 3 65535 65535 0 0][vp 1 0 0 32 0 0]So... whenever I see a man now, all I can think of is that face...[n][w][e]

[sel SEL_025_0_0 top]
[f 2 1]I shouldn't have pried...[e]
[f 2 1]I'm so sorry![e]

[msg MSG_026_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 0 65535 65535 0 0][vp 1 0 0 33 0 0]Oh, no! I'm really happy that you care. Thank you.[n][w][e]

[msg MND_027_0_0]
[f 2 1]Chihiro seems to appreciate my company.[n][w][e]
[f 2 1]I feel like our relationship has grown...[n][w][e]

[msg SYS_028_0_0]
[f 2 1]DEV: Unused[n][w][e]

[msg MSG_029_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 1 65535 65535 0 0][vp 1 0 0 34 0 0]Ah... I should get going. I'll see you at school.[n][w][e]

[msg MND_030_0_0]
[f 2 1]I parted ways with Chihiro, then[n]headed back to the dorm.[n][w][e]

