[msg MSG_006_0_0 [Voice in Your Head]]
[f 2 1][vp 1 0 0 2 0 0]I am the voice of your inner self...[n][w][e]
[f 2 1][vp 1 0 0 3 0 0]Revel in the moment...[n][w][e]
[f 2 1][vp 1 0 0 4 0 0]That which cannot be felt is merely a dream... The present is all we have.[n][w][e]

[sel SEL_007_0_0 top]
[f 2 1]That's right...[e]
[f 2 1]That's not true...[e]
[f 2 1]Who cares...?[e]

[msg MSG_008_0_0 [Voice in Your Head]]
[f 2 1][vp 1 0 0 5 0 0]The future is but a fantasy, memory a fabrication...[n][w][e]
[f 2 1][vp 1 0 0 6 0 0]Let your desire free you from your shackles... Such is your wish...[n][w][e]

[sel SEL_009_0_0 top]
[f 2 1]I can't give in...[e]
[f 2 1]It's so tempting...[e]
[f 2 1]I'm confused...[e]

[msg MSG_010_0_0 [Voice in Your Head]]
[f 2 1][vp 1 0 0 7 0 0]Pleasure is what you truly seek.[n][w][e]
[f 2 1][vp 1 0 0 8 0 0]You stand before the doorway to bliss.[n][w][e]
[f 2 1][vp 1 0 0 9 0 0]You cannot deny your instincts... Embrace your desire...[n][w][e]

[sel SEL_011_0_0 top]
[f 2 1]What does that mean...?[e]
[f 2 1]I'll do that...[e]
[f 2 1]Not now...[e]

[msg MND_012_0_0]
[f 2 1]My consciousness is starting to blur...[n][w][e]
[f 2 1]But I know I still have work to do...[n][w][e]

[msg MSG_013_0_0 [Voice in Your Head]]
[f 2 1][vp 1 0 0 10 0 0]Why do you resist...? Do not avert your eyes from the truth...[n][w][e]

