[msg MSG_000_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 3 0 65535 11061 0 0][f 5 13 12 5 106]So they aired the athlete's training regimen, and...[n][w][e]

[msg MND_001_0_0 [DEV: Internal MES]]
[f 2 1]I can feel my bond with Yuko grow[n]stronger as we spend time together...[n][w][e]

[msg MND_002_0_0 [DEV: Internal MES]]
[f 2 1]I feel like our relationship[n]will grow stronger soon...[n][w][e]

[msg MND_003_0_0 [DEV: Internal MES]]
[f 2 1]It's getting dark...[n][w][e]
[f 2 1]I decided to go back to the dorm.[n][w][e]

