[msg MSG_000_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 2 65535 0 0][vp 3 0 65535 2009 0 0]Yo, long time no see. What's up? Did you have an upset stomach or something?[n][w][e]
[f 2 1][bup 3 1 2 65535 0 0][f 4 23 0 3 1 25 25]Anyways, I got something to tell ya![n][w][e]

[sel SEL_001_0_0 top]
[f 2 1]What happened?[e]
[f 2 1]Aren't you full of energy.[e]

[msg MSG_002_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 2 65535 0 0][vp 3 0 65535 2075 0 0]Actually...[n][w][e]

[msg MSG_002_3_0 [Junpei Iori]]
[f 2 1][bup 3 4 2 65535 0 0]Oh, wait! I'm not supposed to spill![n][w][e]
[f 2 1][bup 3 1 2 65535 0 0][f 4 23 0 3 1 25 25]Sorry, man. Forget you heard anything. Hahahaha.[n][w][e]

[msg MSG_003_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 2 65535 0 0][vp 3 0 65535 1123 0 0]Sheesh, someone's full of energy today... I could hear you from all the way over there.[n][w][e]

[msg MSG_004_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 2 65535 0 0][vp 3 0 65535 2098 0 0]Huh? You two didn't come to school together even though you're in the same dorm?[n][w][e]

[msg MSG_005_0_0 [Yukari Takeba]]
[f 2 1][bup 2 2 2 65535 0 0][vp 3 0 65535 1142 0 0]Ugh, I've heard enough about that.[n][w][e]

[msg MSG_005_3_0 [Yukari Takeba]]
[f 2 1][bup 2 3 2 65535 0 0]Anyway... [nl]-chan. Are you feeling better?[n][w][e]
[f 2 1][bup 2 3 2 65535 0 0]Sorry to hit you with this so soon after you've recovered...[n][w][e]
[f 2 1][bup 2 0 2 65535 0 0][f 4 23 0 2 0 25 25]But the chairman wants to talk to you today.[n][w][e]

[msg MSG_005_5_0 [Yukari Takeba]]
[f 2 1][bup 2 0 2 65535 0 0]Head to the dorm after school and come up to the fourth floor. Don't forget, okay?[n][w][e]

[msg MSG_006_0_0 [Junpei Iori]]
[f 2 1][bup 3 2 2 65535 0 0][vp 3 0 65535 2072 0 0]Hey, you totally thought I was a pain in the ass just now, didn't you?[n][w][e]

[msg MSG_006_3_0 [Junpei Iori]]
[f 2 1][bup 3 4 2 65535 0 0]Er, my bad. I'm not the same person as I was yesterday. Just forget all about the ol' Junpei...[n][w][e]
[f 2 1][bup 3 3 2 65535 0 0][f 4 23 0 3 3 25 25]Anyways, just for always making everything about me.[n][w][e]

[msg MSG_006_5_0 [Junpei Iori]]
[f 2 1][bup 3 1 2 65535 0 0]You should cheer up, too. After all, you got a friend in me![n][w][e]

[msg MSG_007_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 2 65535 0 0][vp 3 0 65535 1123 0 0]Sheesh, someone's full of energy today... I could hear you from all the way over there.[n][w][e]

[msg MSG_008_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 2 65535 0 0][vp 3 0 65535 2098 0 0]Huh? You two didn't come to school together even though you're in the same dorm?[n][w][e]

[msg MSG_009_0_0 [Yukari Takeba]]
[f 2 1][bup 2 2 2 65535 0 0][vp 3 0 65535 1142 0 0]Ugh, I've heard enough about that.[n][w][e]

[msg MSG_009_3_0 [Yukari Takeba]]
[f 2 1][bup 2 3 2 65535 0 0]Anyway... [nl]-chan. Are you feeling better?[n][w][e]
[f 2 1][bup 2 3 2 65535 0 0]Sorry to hit you with this so soon after you've recovered...[n][w][e]
[f 2 1][bup 2 0 2 65535 0 0][f 4 23 0 2 1 25 25]But the chairman wants to talk to you today.[n][w][e]

[msg MSG_009_5_0 [Yukari Takeba]]
[f 2 1][bup 2 0 2 65535 0 0]Head to the dorm after school and come up to the fourth floor. Don't forget, okay?[n][w][e]

[msg MSG_010_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 65535 65535 0 0][vp 3 0 65535 2101 0 0]Hold up... Why are you being called out by the chairman? What the heck did you do!?[n][w][e]

[msg MSG_011_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 3 0 65535 1034 0 0]It's nothing serious. C'mon, we're gonna be late if we just stand around here talking.[n][w][e]

