[msg MND_000_0_0]
[f 2 1]It's Yuko, the team manager.[n][w][e]
[f 2 1]Should I say hello?[n][w][e]

[sel SEL_001_0_0 top]
[f 2 1]I think I will.[e]
[f 2 1]Maybe not.[e]

[msg MND_002_0_0]
[f 2 1]I left without Yuko noticing...[n][w][e]

[msg MSG_003_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 1 0 0]Oh, [nl]-chan. What's up?[n][w][e]

[sel SEL_004_0_0 top]
[f 2 1]Wanna walk home together?[f 2 9 1 1 565][e]
[f 2 1]Nothing, see you tomorrow.[e]

[msg MSG_005_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 2 0 0]Hmm... Okay, sure![n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 3 0 0][f 4 23 0 106 1 25 25]Why don't we stop somewhere along the way?[n][w][e]

[msg MSG_006_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 4 0 0]Yeah, see you tomorrow![n][w][e]

