[msg MSG_000_0_0 [Koromaru]]
[f 2 1][bup 9 0 65535 65535 0 0][vp 1 0 0 1 0 0][f 4 23 0 1 0 25 25]Arf.[n][w][e]

[msg MSG_001_0_0 [Girl in a Floral Shirt]]
[f 2 1][vp 1 0 0 2 0 0][f 5 21 0 2]Koromaru! I'm back![n][w][e]

[msg MSG_002_0_0 [Naughty-Looking Boy]]
[f 2 1][vp 1 0 0 3 0 0][f 5 21 0 3]Koromaru, you're so warm![n][w][e]

[msg MSG_003_0_0 [Koromaru]]
[f 2 1][bup 9 0 65535 65535 0 0][vp 1 0 0 4 0 0][f 4 23 0 1 0 25 25]Arr rarrr arrrrrf... *whine*[n][w][e]

[msg MND_002_5_0]
[f 2 1]The kids are playing pretty[n]rough with Koromaru...[n][w][e]

[msg MSG_004_0_0 [Girl in a Floral Shirt]]
[f 2 1][vp 1 0 0 5 0 0][f 5 21 0 2]Um...[n][w][e]
[f 2 1][vp 1 0 0 6 0 0][f 5 21 0 2]Don't get sick, okay, Koromaru? Lots of people haven't been looking so good lately.[n][w][e]

[msg MSG_005_0_0 [Naughty-Looking Boy]]
[f 2 1][vp 1 0 0 7 0 0][f 5 21 0 3]They say if you smile when you gargle, you won't get infected.[n][w][e]
[f 2 1][vp 1 0 0 8 0 0][f 5 21 0 3]And if your feet get too cold, you'll catch depression, so bundle up when you sleep![n][w][e]

[msg MSG_006_0_0 [Koromaru]]
[f 2 1][bup 9 0 65535 65535 0 0][vp 1 0 0 9 0 0][f 4 23 0 1 0 25 25]Ruff![n][w][e]

[msg MSG_007_0_0 [Girl in a Floral Shirt]]
[f 2 1][vp 1 0 0 10 0 0][f 5 21 0 2]Okay, see you guys later![n][w][e]

[msg MSG_008_0_0 [Gentle Woman]]
[f 2 1][vp 1 0 0 11 0 0][f 5 21 0 4]Hehe, quite exciting over here.[n][w][e]

[msg MSG_009_0_0 [Koromaru]]
[f 2 1][bup 9 0 65535 65535 0 0][vp 1 0 0 12 0 0][f 4 23 0 1 0 25 25]*pant* Ruh?[n][w][e]

[msg MSG_010_0_0 [Gentle Woman]]
[f 2 1][vp 1 0 0 13 0 0][f 5 21 0 4]Well, it's been different around town lately, don't you think?[n][w][e]
[f 2 1][vp 1 0 0 14 0 0][f 5 21 0 4]So many people with dead looks in their eyes, not to mention the wild stories going around.[n][w][e]
[f 2 1][vp 1 0 0 15 0 0][f 5 21 0 4]I couldn't help but worry, so I came to check in on you.[n][w][e]

[msg MSG_011_0_0 [Gentle Woman]]
[f 2 1][vp 1 0 0 16 0 0][f 5 21 0 4]But it looks like I had nothing to worry about.[n][w][e]
[f 2 1][vp 1 0 0 17 0 0][f 5 21 0 4]So that's enough of that for now. Next time, I'll bring some snacks, all right?[n][w][e]

[msg MND_012_0_0]
[f 2 1]Lots of people are uneasy about the[n]bizarre events around the world...[n][w][e]

[msg MSG_013_0_0 [Koromaru]]
[f 2 1][bup 9 0 65535 65535 0 0][vp 0 0 0 18 0 0][f 4 23 0 1 0 25 25]*pant* *pant*[n][w][e]

[sel SEL_014_0_0 top]
[f 2 1]Let's do our best.[e]
[f 2 1]We can't afford to lose.[e]
[f 2 1]I'm counting on you.[e]

[msg MSG_015_0_0 [Koromaru]]
[f 2 1][bup 9 0 65535 65535 0 0][vp 1 0 0 19 0 0][f 4 23 0 1 0 25 25]Arf! Arf![n][w][e]

[msg MSG_016_0_0 [Old Man's Voice]]
[f 2 1][vp 1 0 0 20 0 0][f 5 21 0 5]Oh, there they are![n][w][e]

[msg MSG_017_0_0 [Old Man]]
[f 2 1][vp 1 0 0 21 0 0][f 5 21 0 5]Whew, I'm beat. And it's been getting chillier, too.[n][w][e]
[f 2 1][vp 1 0 0 22 0 0][f 5 21 0 5]Ah, right. Do you know how to play shogi, young lady?[n][w][e]

[sel SEL_018_0_0 top]
[f 2 1]Yeah, I'm pretty good.[e]
[f 2 1]Just a little bit.[e]
[f 2 1]No, I've never played.[e]

[msg MSG_019_0_0 [Old Man]]
[f 2 1][vp 1 0 0 23 0 0][f 5 21 0 5]Ah, excellent, excellent.[n][w][e]
[f 2 1][vp 1 0 0 24 0 0][f 5 21 0 5]Then would you humor this old man with a game?[n][w][e]

[msg MSG_020_0_0 [Old Man]]
[f 2 1][vp 1 0 0 25 0 0][f 5 21 0 5]Is that so? Then Koromaru can lend you a helping paw.[n][w][e]

[msg MSG_021_0_0 [Old Man]]
[f 2 1][vp 1 0 0 26 0 0][f 5 21 0 5]I can teach you. While we're at it, Koromaru can lend you a helping paw.[n][w][e]

[msg MSG_022_0_0 [Koromaru]]
[f 2 1][bup 9 1 65535 65535 0 0][vp 1 0 0 27 0 0][f 4 23 0 1 1 25 25]Arf![n][w][e]

[msg MND_023_0_0]
[f 2 1]Koromaru seems like he's up for it.[n][w][e]

[msg MSG_024_0_0 [Old Man]]
[f 2 1][vp 1 0 0 28 0 0][f 5 21 0 5]Well, then, shall we begin?[n][w][e]
[f 2 1][vp 1 0 0 29 0 0][f 5 21 0 5]I don't have anyone to play with these days. This is going to be fun.[n][w][e]

[msg MND_025_0_0]
[f 2 1]Koromaru and I played[n]shogi with the old man...[n][w][e]

[msg MSG_026_0_0 [Koromaru]]
[f 2 1][bup 9 0 65535 65535 0 0][vp 1 0 0 30 0 0][f 4 23 0 1 0 25 25]*pant* Ruff![n][w][e]

[msg MSG_027_0_0 [Old Man]]
[f 2 1][vp 1 0 0 31 0 0][f 5 21 0 5]Heeey, hold it! Koro-chan, it's too early for that hint![n][w][e]

[msg MSG_028_0_0 [Koromaru]]
[f 2 1][bup 9 0 65535 65535 0 0][vp 1 0 0 32 0 0][f 4 23 0 1 0 25 25]Bark! Bark![n][w][e]

[msg MSG_029_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 33 0 0]What's going on over here?[n][w][e]

[msg MSG_030_0_0 [Old Man]]
[f 2 1][vp 1 0 0 34 0 0][f 5 21 0 5]Oh?[n][w][e]
[f 2 1][vp 1 0 0 35 0 0][f 5 21 0 5]Oh, pardon us. We are right in front of the entrance, aren't we?[n][w][e]

[msg MSG_031_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 36 0 0]Oh, no, don't worry about it.[n][w][e]

[msg MSG_032_0_0 [Old Man]]
[f 2 1][vp 1 0 0 37 0 0][f 5 21 0 5]Ah, of course. This is a student dorm, right?[n][w][e]
[f 2 1][vp 1 0 0 38 0 0][f 5 21 0 5]Then does that mean you'll leave this place one day too, young lady?[n][w][e]

[msg MSG_033_0_0 [Old Man]]
[f 2 1][vp 1 0 0 39 0 0][f 5 21 0 5]I see.[n][w][e]
[f 2 1][vp 1 0 0 40 0 0][f 5 21 0 5]Well, Koromaru. Looks like the next batch of students will look after you, too.[n][w][e]
[f 2 1][vp 1 0 0 41 0 0][f 5 21 0 5]Life may be filled with goodbyes, but they never get any easier.[n][w][e]

[msg MSG_034_0_0 [Koromaru]]
[f 2 1][bup 9 3 65535 65535 0 0][vp 1 0 0 42 0 0][f 4 23 0 1 3 25 25]*whine*[n][w][e]

[sel SEL_035_0_0 top]
[f 2 1]Check.[e]
[f 2 1]It's over.[e]

[msg MSG_036_0_0 [Old Man]]
[f 2 1][vp 1 0 0 43 0 0][f 5 21 0 5]What!?[n][w][e]

[msg MSG_037_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 44 0 0]Hm, that was a good move.[n][w][e]

[msg MSG_038_0_0 [Old Man]]
[f 2 1][vp 1 0 0 45 0 0][f 5 21 0 5]Ngh, so what? We're just getting started![n][w][e]

[msg MSG_039_0_0 [Old Man]]
[f 2 1][vp 1 0 0 46 0 0][f 5 21 0 5]Whew, that was a good match. I'll have to stop by again.[n][w][e]
[f 2 1][vp 1 0 0 47 0 0][f 5 21 0 5]Until next time, you two. And to that lovely lady over there... adieu.[n][w][e]

[msg MSG_040_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 48 0 0][f 4 23 0 6 0 25 25]Moving out of the dorms... That would be some point after we finish our fight.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 49 0 0][f 4 23 0 6 0 25 25]It's hard to even imagine right now, but it's something we'll have to face in the future.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 50 0 0][f 4 23 0 6 0 25 25]After all, we're fighting so we can even have a future.[n][w][e]

[msg MSG_041_0_0 [Koromaru]]
[f 2 1][bup 9 3 65535 65535 0 0][vp 1 0 0 51 0 0][f 4 23 0 1 3 25 25]*whine*[n][w][e]

[msg MSG_042_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 52 0 0][f 4 23 0 6 1 25 25]Oh, don't you worry, Koromaru. Everyone will love you.[n][w][e]

[msg MSG_043_0_0 [Old Man's Voice]]
[f 2 1][vp 1 0 0 53 0 0]Oh no, my shogi pieces...[n][w][e]

[msg MSG_044_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 54 0 0][f 4 23 0 6 0 25 25]Is that the old man from earlier?[n][w][e]

[msg MND_045_0_0]
[f 2 1]Shogi pieces are scattered on the[n]ground by the old man's feet.[n][w][e]
[f 2 1]I should probably help him out...[n][w][e]

[msg MSG_046_0_0 [Koromaru]]
[f 2 1][bup 9 0 65535 65535 0 0][vp 1 0 0 55 0 0][f 4 23 0 1 0 25 25]*pant* Ruff![n][w][e]

[msg MND_047_0_0]
[f 2 1]Koromaru and I helped the old man[n]and walked him back to his home.[n][w][e]

