[msg MSG_000_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 3 0 65535 5131 0 0][uf 5 13 3 5 6]Então, li isso num livro outro dia...[n][uf 1 1][e]

[msg MND_001_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]Sinto que meu laço com Fuuka fica mais forte[n]cada vez que passamos um tempo juntas...[n][uf 1 1][e]

[msg MND_002_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]Sinto que nossa relação[n]se fortalecerá ainda mais em breve...[n][uf 1 1][e]

[msg MND_003_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]Finalmente é hora da saída na escola...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Decidi voltar ao dormitório.[n][uf 1 1][e]

