[msg MSG_000_0_0 [Enregistrement vidéo]]
[uf 0 5 65278][uf 2 1]...> ...>[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]20/09/2009 01:13:41[n]Début de la lecture...[n][uf 1 1][e]

[msg MND_001_0_0 [Monologue intérieur]]
[uf 0 5 65278][uf 2 1]... ?![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Mais c'est ma chambre ![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Je me vois endormie dans mon lit.[n][uf 1 1][e]

[msg MSG_002_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 40 0 0][uf 3 1 1 0 0 1 0 0]Porte déverrouillée en 92 secondes. Je me suis améliorée.[n][uf 1 1][e]

[msg MSG_003_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 40 0 0][uf 3 1 0 0 0 2 0 0]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 40 0 0][uf 3 1 1 0 0 3 0 0]Analyse de la température corporelle... 36,2 degrés. Aucune fièvre à signaler...[n][uf 1 1][e]

[msg MSG_004_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 40 0 0][uf 3 1 1 0 0 4 0 0]À ce rythme, elle devrait être entièrement rétablie d'ici demain matin.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 40 0 0][uf 3 1 1 0 0 5 0 0]Le coussin que j'avais mis dans le congélateur ne sera pas nécessaire.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 40 0 0][uf 3 1 0 0 0 6 0 0]......[n][uf 1 1][e]

[msg MSG_005_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 40 0 0][uf 3 1 1 0 0 7 0 0]Je ne peux pas rester trop longtemps, ou Yukari va encore me réprimander.[n][uf 1 1][e]

[msg MSG_006_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 40 0 0][uf 3 1 0 0 0 8 0 0]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 40 0 0][uf 3 1 1 0 0 9 0 0]Il reste encore 4 heures et 12 minutes avant le lever du soleil.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 40 0 0][uf 3 1 0 0 0 10 0 0]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 40 0 0][uf 3 1 1 0 0 11 0 0]Je devrais pouvoir rester sans crainte tant que je pars avant le matin.[n][uf 1 1][e]

[msg MSG_007_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 40 0 0][uf 3 1 1 0 0 12 0 0]Je... Je vais rester veiller sur elle encore un peu.[n][uf 1 1][e]

[msg MND_008_0_0 [Monologue intérieur]]
[uf 0 5 65278][uf 2 1]L'enregistrement se termine ici.[n][uf 1 1][e]

