[msg MND_000_0_0]
[uf 0 5 65278][uf 2 1]I lost sight of the girl...[n][uf 1 1][e]

[msg MSG_001_0_0 [Mysterious Girl]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 204 65535 0 0][uf 3 1 0 0 0 1 0 0]......[n][uf 1 1][e]

[msg MND_002_0_0]
[uf 0 5 65278][uf 2 1]It's the girl from earlier...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]She must be the one[n]who's been watching me.[n][uf 1 1][e]

[sel SEL_003_0_0 top]
[uf 0 5 65278][uf 2 1]Approach her[e]
[uf 0 5 65278][uf 2 1]Wait patiently[e]

[msg MSG_004_0_0 [Mysterious Girl]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 204 65535 0 0][uf 3 1 1 0 0 2 0 0]I was correct.[n][uf 1 1][e]

[msg MSG_005_0_0 [Mysterious Girl]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 204 65535 0 0][uf 3 1 1 0 0 3 0 0]Now I am certain...[n][uf 1 1][e]

[msg MSG_006_0_0 [Mysterious Girl]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 204 65535 0 0][uf 3 1 1 0 0 4 0 0]I have found you.[n][uf 1 1][e]

[msg MSG_007_0_0 [Mysterious Girl]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 204 65535 0 0][uf 3 1 1 0 0 5 0 0]I have been searching for you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 204 65535 0 0][uf 3 1 1 0 0 6 0 0]My highest priority is to be at your side.[n][uf 1 1][e]

[msg MND_008_0_0 [Mysterious Girl]]

[msg MSG_009_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 102 65535 0 0][uf 3 1 1 0 0 7 0 0]WHAT!? Are you friggin' kidding me!?[n][uf 1 1][e]

[msg MSG_010_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 4 102 65535 0 0][uf 3 1 1 0 0 8 0 0]What's going on? She didn't even say anything to her![n][uf 1 1][e]

[msg MND_011_0_0]
[uf 0 5 65278][uf 2 1]It seems like she still[n]doesn't want to let go...[n][uf 1 1][e]

[msg MSG_012_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 5 65535 0 0][uf 3 1 1 0 0 9 0 0]There you guys are![n][uf 1 1][e]

[msg MSG_012_1_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 5 65535 0 0][uf 3 1 1 0 0 10 0 0]What are you doing here? We've been looking all over for you![n][uf 1 1][e]

[msg MSG_013_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 5 65535 0 0][uf 3 1 1 0 0 11 0 0]Um... What're you doing in the middle of the woods, in your swimsuits?[n][uf 1 1][e]

[msg MSG_014_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 5 65535 0 0][uf 3 1 1 0 0 12 0 0]You have no idea what we've—[n][uf 1 1][e]

[msg MSG_014_5_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 5 65535 0 0][uf 3 1 1 0 0 13 0 0]Huh!?[n][uf 1 1][e]

[msg MSG_015_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 5 65535 0 0][uf 3 1 1 0 0 14 0 0]Who's this?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 5 65535 0 0][uf 3 1 1 0 0 15 0 0]And... why is she hugging you?[n][uf 1 1][e]

[msg MSG_016_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 5 65535 0 0][uf 3 1 1 0 0 16 0 0]Listen, we have a slight situation here.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 5 65535 0 0][uf 3 1 1 0 0 17 0 0]I'm sorry to interrupt your vacation, but I need everyone to go back to the house and gear up.[n][uf 1 1][e]

[msg MSG_017_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 18 0 0]Ah, that won't be necessary. We've found what we were looking for.[n][uf 1 1][e]

[msg MSG_018_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 5 65535 0 0][uf 3 1 1 0 0 19 0 0]Mr. Chairman... What do you mean?[n][uf 1 1][e]

[msg MSG_019_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 6 65535 65535 0 0][uf 3 1 1 0 0 20 0 0]You had me worried.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 6 65535 65535 0 0][uf 3 1 1 0 0 21 0 0]You can't just leave the lab on your own, Aigis.[n][uf 1 1][e]

[msg MSG_020_0_0 [Mysterious Girl]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 204 65535 0 0][uf 3 1 1 0 0 22 0 0]...Understood.[n][uf 1 1][e]

