[msg MSG_000_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]Hmm... L'odeur des lys est trop puissante, et je ne raffole pas des roses.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 0 2 0 0][uf 4 23 0 2 1 25 25]Pourquoi pas des gerberas ?[n][uf 1 1][e]

[msg MSG_001_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]Oh... pardon ![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]Je suis en train de redécorer ma chambre, je pensais l'arranger avec des fleurs assorties.[n][uf 1 1][e]

[msg MSG_002_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]Je penche pour des gerberas. De quelle couleur, à ton avis ?[n][uf 1 1][e]

[sel SEL_003_0_0 top]
[uf 0 5 65278][uf 2 1]Du rose girly.[e]
[uf 0 5 65278][uf 2 1]Du blanc épuré.[e]
[uf 0 5 65278][uf 2 1]Du rouge vif.[e]
[uf 0 5 65278][uf 2 1]C'est quoi, un gerbera ?[e]

[msg MSG_004_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 0 6 0 0][uf 5 13 7 15 2]Tu crois ? J'aime bien le rose, aussi ![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]On a les mêmes goûts, alors...[n][uf 1 1][e]

[msg MSG_005_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 0 8 0 0]C'est décidé. Je vais acheter celles-là.[n][uf 1 1][e]

[msg MSG_006_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0][uf 3 1 1 0 0 9 0 0]Blanches ? C'est une couleur un peu fade, non ?[n][uf 1 1][e]

[msg MSG_007_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]Rouge vif ? Elles vont trop ressortir, tu crois pas ?[n][uf 1 1][e]

[msg MSG_008_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 65535 65535 0 0][uf 3 1 1 0 0 11 0 0]T'es sérieuse ?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0][uf 3 1 1 0 0 12 0 0][uf 4 23 0 2 3 25 25]Tu devrais connaître ce genre de trucs.[n][uf 1 1][e]

[msg MSG_009_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]À bien y réfléchir, des gerberas tout seuls, ça risque de faire un peu trop sobre...[n][uf 1 1][e]

[msg MSG_009_5_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]À ton avis, quelles autres fleurs donneraient du pep ?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 65535 65535 0 0][uf 3 1 1 0 0 15 0 0][uf 4 23 0 2 6 25 25]Oh, mais tu n'es jamais entrée dans ma chambre, pas vrai ? Dans ce cas, pourquoi je te demande, en fait ?[n][uf 1 1][e]

[sel SEL_010_0_0 top]
[uf 0 5 65278][uf 2 1]C'est méchant.[e]
[uf 0 5 65278][uf 2 1]Invite-moi, alors.[e]

[msg MSG_011_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 0 16 0 0][uf 5 13 7 5 2]Héhé. Mais c'est la vérité ![n][uf 1 1][e]

[msg MSG_012_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 17 0 0]Même pas en rêve ! Si tu crois que je vais me faire avoir...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 0 18 0 0][uf 4 23 0 2 1 25 25]Haha. T'es aussi tordue que Junpei.[n][uf 1 1][e]

[msg MSG_013_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 19 0 0]Honnêtement, n'importe quelles fleurs feraient l'affaire si elles venaient de toi, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 11 65535 65535 0 0][uf 3 1 1 0 0 20 0 0][uf 4 23 0 2 11 25 25]Je rigole ! Haha.[n][uf 1 1][e]

[msg MND_014_0_0]
[uf 0 5 65278][uf 2 1]Yukari semble particulièrement de bonne humeur aujourd'hui.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]J'ai l'impression que nous nous sommes rapprochées...[n][uf 1 1][e]

[msg SYS_015_0_0]
[uf 0 5 65278][uf 2 1]Not used[n][uf 1 1][e]

[msg MSG_016_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 21 0 0]Oh, il est déjà tard.[n][uf 1 1][e]

[msg MSG_016_5_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 22 0 0]Bon, qu'est-ce que je dois choisir ? J'ai du mal à me décider.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 23 0 0]Hmm... Une renoncule serait pas mal non plus...[n][uf 1 1][e]

[msg MND_017_0_0]
[uf 0 5 65278][uf 2 1]J'ai décidé de rentrer au dortoir après avoir passé du temps avec Yukari.[n][uf 1 1][e]

