[msg MSG_000_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 11 65535 65535 0 0][uf 3 1 3 0 65535 1132 0 0]Whew, what a concert! It feels good to sing as loud as you can, doesn't it?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 4 23 0 2 1 25 25]Plus, your song choices were pretty unique, [uf 4 1]-chan.[n][uf 1 1][e]

[msg MSG_001_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 3 0 65535 1067 0 0]Oh, speaking of music, what do you usually listen to?[n][uf 1 1][e]

[sel SEL_002_0_0 top]
[uf 0 5 65278][uf 2 1]Western music.[e]
[uf 0 5 65278][uf 2 1]J-pop.[e]
[uf 0 5 65278][uf 2 1]Nothin'...[e]

[msg MSG_003_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 11 65535 65535 0 0][uf 3 1 3 0 65535 1107 0 0][uf 5 13 7 15 2]Oh, I kinda thought so! You look like you'd be into that kind of music.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 4 23 0 2 1 25 25]I'm not really familiar with Western music, so let me know if you have any recs![n][uf 1 1][e]

[msg MSG_003_3_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0]I'm trying to broaden my horizons, you know?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0]It'd be a waste to miss out on good music just because it's in a different language.[n][uf 1 1][e]

[msg MND_004_0_0]
[uf 0 5 65278][uf 2 1]Yukari seems happy.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I learned a little more about her today.[n][uf 1 1][e]

[msg MSG_005_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 3 0 65535 1099 0 0][uf 5 13 7 30 2]Wait, really!? Me too![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0]Hey, who's your favorite band? These days, I've been super into this one that did a song for a popular drama.[n][uf 1 1][e]

[msg MSG_005_3_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 65535 65535 0 0]Oops, I'm sorry! I got a little too excited about it...[n][uf 1 1][e]

[msg MND_006_0_0]
[uf 0 5 65278][uf 2 1]Yukari is flustered.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like we became a lot closer today.[n][uf 1 1][e]

[msg MSG_007_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 65535 65535 0 0][uf 3 1 3 0 65535 1098 0 0]Huh? But you've always got headphones on...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0][uf 4 23 0 2 3 25 25]...Never mind, it's all right if you don't wanna say.[n][uf 1 1][e]

[msg MND_008_0_0]
[uf 0 5 65278][uf 2 1]Yukari is sighing...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like we didn't get any closer today...[n][uf 1 1][e]

[msg MSG_009_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 65535 65535 0 0]Oh, I just remembered I ran out of hand powder.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1020 0 0][uf 4 23 0 2 0 25 25]It's something we use for archery. I'm gonna go buy some, so you should head back first.[n][uf 1 1][e]

[msg MND_010_0_0]
[uf 0 5 65278][uf 2 1]I saw Yukari off, then returned to the dorm...[n][uf 1 1][e]

