[msg MSG_000_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 1 65535 0 0][uf 3 1 1 0 0 1 0 0]Has venido.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 1 65535 0 0][uf 3 1 1 0 0 2 0 0]Me gustaría que me ayudaras con un recado. Vamos.[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]Muy bien.[e]
[uf 0 5 65278][uf 2 1]¿Adónde?[e]
[uf 0 5 65278][uf 2 1]No me apetece nada.[e]

[msg MSG_002_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 1 65535 0 0][uf 3 1 1 0 0 3 0 0]Hay que recoger a un nuevo miembro. Bueno, a uno que regresa, más bien dicho.[n][uf 1 1][e]

[msg MSG_003_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 1 65535 0 0][uf 3 1 1 0 0 4 0 0]No seas así, chica.[n][uf 1 1][e]

