[msg MSG_000_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 3 0 65535 2002 0 0]¡Ahí estáis![n][uf 1 1][e]

[msg MSG_000_1_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 65535 65535 0 0][uf 3 1 3 0 65535 2004 0 0]Tía, no creía que hubiera otra sombra.[n][uf 1 1][e]

[msg MSG_000_2_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]En fin, ¿estáis bien?[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]Eh... Sí, estamos bien.[e]
[uf 0 5 65278][uf 2 1]¿Qué tal tú?[e]

[msg MSG_002_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 65535 65535 0 0][uf 3 1 3 0 65535 1073 0 0]¡S-sí! ¡Por aquí no hay nada fuera de lo normal![n][uf 1 1][e]

[msg MSG_003_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 4 65535 65535 0 0][uf 3 1 3 0 65535 4030 0 0]¡N-nada fuera de lo normal! ¡Nada de nada![n][uf 1 1][e]

[msg MSG_999_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Bien, ya estamos todos juntos de nuevo.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]No esperaba toparme con otra sombra.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Bueno, yo te veo de una pieza. ¿Ha ocurrido algo fuera de lo normal?[n][uf 1 1][e]

[msg MSG_999_0_1 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 4 65535 65535 0 0]T-todo ha ido bien por aquí.[n][uf 1 1][e]

[msg MSG_004_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0][uf 3 1 3 0 65535 5076 0 0]¡Ah! ¿Te refieres a...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]¡Lo tengo! ¡Son los espejos![n][uf 1 1][e]

[msg MSG_004_1_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 50 0 0]¡Parece que las señales de los espejos que están en las habitaciones resuenan con la sombra principal![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 50 0 0]Si destruimos los espejos, puede que consigamos romper la barrera.[n][uf 1 1][e]

[msg MSG_011_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4061 0 0]Bien hecho. ¿En qué habitaciones podemos encontrar esos espejos?[n][uf 1 1][e]

[msg MSG_012_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5145 0 0]¡Percibo algo entre la 204 y la 205![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]¡Probad con esas primero![n][uf 1 1][e]

[msg MSG_006_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]Mierda, otra vez. ¿Qué narices está pasando?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0]Pues nada, a seguir adelante. ¡Qué ganas de darle una paliza![n][uf 1 1][e]

