[msg MSG_000_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 159 65535 0 0][vp 1 0 0 1 0 0]Ich hatte überlegt, den Kohl im Kühlschrank zu benutzen, um eine Cremesuppe zu kochen.[n][w][e]
[f 2 1][bup 2 1 159 65535 0 0][vp 1 0 0 2 0 0]Ich hab gehört, dass jedes Blatt davon supergesund sein soll, also benutze ich alles davon![n][w][e]
[f 2 1][bup 2 1 159 65535 0 0][vp 1 0 0 3 0 0]Wie du sehen kannst, bin ich vorbereitet. Du auch?[n][w][e]

[sel SEL_001_0_0 top]
[f 2 1]Vorbereitet worauf?[e]
[f 2 1]Ich freu mich drauf.[e]
[f 2 1]Ich hab da so meine Zweifel.[e]

[msg MSG_002_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 159 65535 0 0][vp 1 0 0 4 0 0]Du weißt schon, ähm ... Ach, egal.[n][w][e]
[f 2 1][bup 2 0 159 65535 0 0][vp 1 0 0 5 0 0]Ich frag dich nach dem Essen noch mal.[n][w][e]

[msg MSG_003_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 159 65535 0 0][vp 1 0 0 6 0 0]Ich bin wieder voll drin, nachdem ich dieses perfekte sautierte Hühnchen gekocht hab![n][w][e]
[f 2 1][bup 2 1 159 65535 0 0][vp 1 0 0 7 0 0]Das wird überhaupt kein Problem![n][w][e]

[msg MSG_004_0_0 [Yukari Takeba]]
[f 2 1][bup 2 3 159 65535 0 0][vp 1 0 0 8 0 0]Mann, du hast ja gar kein Vertrauen ...[n][w][e]
[f 2 1][bup 2 3 159 65535 0 0][vp 1 0 0 9 0 0]Mein sautiertes Huhn war doch gut, oder?[n][w][e]

[msg MSG_005_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 159 65535 0 0][vp 1 0 0 10 0 0]Okay, weniger Reden, mehr Kochen![n][w][e]
[f 2 1][bup 2 0 159 65535 0 0][vp 1 0 0 11 0 0]Ich kümmere mich um das Hauptgericht mit dem Kohl, also warum fängst du nicht mit dem Reis und so an?[n][w][e]

[msg MND_006_0_0]
[f 2 1]Ich habe zusammen mit Yukari gekocht ...[n][w][e]
[f 2 1]......[n][w][e]
[f 2 1]Die Cremesuppe ist angenehm mild und schmeckt lecker ...![n][w][e]

[msg MSG_007_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 159 65535 0 0][vp 1 0 0 12 0 0]Puh, bin ich voll! Das haben wir aber schnell verputzt, was?[n][w][e]
[f 2 1][bup 2 1 159 65535 0 0][vp 1 0 0 13 0 0]Also, [nl]-chan ... Wie hat's dir heute geschmeckt?[n][w][e]

[sel SEL_008_0_0 top]
[f 2 1]Lecker![e]
[f 2 1]Gar nicht so übel.[e]

[msg MSG_009_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 159 65535 0 0][vp 1 0 0 14 0 0]Oh, da war es! Du hast "lecker" gesagt![n][w][e]
[f 2 1][bup 2 0 159 65535 0 0][vp 1 0 0 15 0 0][f 4 23 0 2 0 25 25]Endlich! Heute musste ich dich einfach dazu bringen, es zu sagen.[n][w][e]

[msg MSG_010_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 159 65535 0 0][vp 1 0 0 16 0 0]Komm schon, halt dich nicht zurück! Ich bin jedenfalls zufrieden damit.[n][w][e]
[f 2 1][bup 2 1 159 65535 0 0][vp 1 0 0 17 0 0][f 4 23 0 2 1 25 25]Während wir gegessen haben, hat dein ganzes Gesicht "lecker" zu mir gesagt![n][w][e]

[msg MSG_011_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 159 65535 0 0][vp 1 0 0 18 0 0]Hey, erinnerst du dich, was ich zu dir gesagt habe, als wir zum allerersten Mal zusammen gekocht haben?[n][w][e]
[f 2 1][bup 2 1 159 65535 0 0][vp 1 0 0 19 0 0]Dass ich es so gut machen würde, dass du gar nicht anders kannst, als "Lecker!" zu sagen? Ich bin ziemlich stur.[n][w][e]

[msg MSG_012_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 159 65535 0 0][vp 1 0 0 20 0 0][f 5 13 7 1 2]Aber ich muss sagen, es ist schön, jemanden zu beobachten, der etwas isst, das er wirklich mag.[n][w][e]
[f 2 1][bup 2 0 159 65535 0 0][vp 1 0 0 21 0 0][f 4 23 0 2 0 25 25]Und nicht nur, weil ich mir was beweisen will. Ich wollte dieses Lächeln einfach unbedingt noch mal sehen.[n][w][e]

[msg MSG_012_5_0 [Yukari Takeba]]
[f 2 1][bup 2 0 159 65535 0 0][vp 1 0 0 22 0 0]Moment, klang das jetzt zu aufopferungsvoll? Sorry, aber das hier ist keine Einbahnstraße![n][w][e]
[f 2 1][bup 2 1 159 65535 0 0][vp 1 0 0 23 0 0][f 4 23 0 2 1 25 25]Nächstes Mal musst du was für mich kochen! Lass uns ein paar leckere Erinnerungen zusammen machen![n][w][e]

[msg MND_012_7_0]
[f 2 1]Nach dem erfolgreichen Essen lächelt Yukari herzlich ...[n][w][e]

[msg MSG_013_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 159 65535 0 0][vp 1 0 0 24 0 0]Danke! Lass uns das wiederholen, wenn du Zeit hast.[n][w][e]
[f 2 1][bup 2 0 159 65535 0 0][vp 1 0 0 25 0 0][f 4 23 0 2 0 25 25]Okay, beeilen wir uns und räumen alles weg.[n][w][e]

