[msg Item_000]
[f 2 1]未使用[n][e]

[msg Item_001]
[f 2 1]Ein hochmoderner, tragbarer Musik-Player.[n][e]

[msg Item_002]
[f 2 1]Ein süßes, weißes Halsband mit einem Herzchen.[n][e]

[msg Item_003]
[f 2 1]Die modische Silber-Halskette ist in Männermodemagazinen gerade der letzte Schrei.[n][e]

[msg Item_004]
[f 2 1]Dünne Lederhandschuhe in perfekter Passform.[n][e]

[msg Item_005]
[f 2 1]Falsche Fingernägel mit aufgesetzten Edelsteinen. Wunderschön und elegant.[n][e]

[msg Item_006]
[f 2 1]Eine hübsche Halskette, die bei Highschool-Mädchen gerade absolut angesagt ist.[n][e]

[msg Item_007]
[f 2 1]Eine große, rote Schleife. Lässt jeden Hals elegant und farbenfroh aussehen.[n][e]

[msg Item_008]
[f 2 1]Ein simples Armband für alle, die gern Sport treiben.[n][e]

[msg Item_009]
[f 2 1]Ein verziertes Schmuckstück, das wie Engelsflügel aussieht. Hat keinerlei Funktion.[n][e]

[msg Item_00A]
[f 2 1]Eine schlichte Strickmütze für Herren.[n][e]

[msg Item_00B]
[f 2 1]Ein festes Seil. Verbessert die physische Stärke etwas.[n][e]

[msg Item_00C]
[f 2 1]Ein festes Seil. Verbessert die physische Stärke spürbar.[n][e]

[msg Item_00D]
[f 2 1]Ein festes Seil. Verbessert die physische Stärke beträchtlich.[n][e]

[msg Item_00E]
[f 2 1]Ein mystisches Seidenband. Verbessert die Magiekraft etwas.[n][e]

[msg Item_00F]
[f 2 1]Ein mystisches Seidenband. Verbessert die Magiekraft spürbar.[n][e]

[msg Item_010]
[f 2 1]Ein mystisches Seidenband. Verbessert die Magiekraft beträchtlich.[n][e]

[msg Item_011]
[f 2 1]Ein stabiles Stahlband. Verbessert die defensive Ausdauer etwas.[n][e]

[msg Item_012]
[f 2 1]Ein stabiles Stahlband. Verbessert die defensive Ausdauer spürbar.[n][e]

[msg Item_013]
[f 2 1]Ein stabiles Stahlband. Verbessert die defensive Ausdauer beträchtlich.[n][e]

[msg Item_014]
[f 2 1]Ein luftig-leichtes Stoffband. Damit fühlt man sich etwas leichter.[n][e]

[msg Item_015]
[f 2 1]Ein luftig-leichtes Stoffband. Damit fühlt man sich spürbar leichter.[n][e]

[msg Item_016]
[f 2 1]Ein luftig-leichtes Stoffband. Damit fühlt man sich beträchtlich leichter.[n][e]

[msg Item_017]
[f 2 1]Ein kunterbuntes Flechtband. Bringt etwas mehr Glück.[n][e]

[msg Item_018]
[f 2 1]Ein kunterbuntes Flechtband. Bringt spürbar mehr Glück.[n][e]

[msg Item_019]
[f 2 1]Ein kunterbuntes Flechtband. Bringt beträchtlich mehr Glück.[n][e]

[msg Item_01A]
[f 2 1]Ein luxuriöses Silberband. Verbessert alle Attribute etwas.[n][e]

[msg Item_01B]
[f 2 1]Ein durchscheinendes, luxuriöses Silberband. Verbessert alle Attribute beträchtlich.[n][e]

[msg Item_01C]
[f 2 1]未使用[n][e]

[msg Item_01D]
[f 2 1]未使用[n][e]

[msg Item_01E]
[f 2 1]未使用[n][e]

[msg Item_01F]
[f 2 1]未使用[n][e]

[msg Item_020]
[f 2 1]Ein festes Seil. Verbessert die physische Stärke enorm.[n][e]

[msg Item_021]
[f 2 1]Ein mystisches Seidenband. Verbessert die Magiekraft enorm.[n][e]

[msg Item_022]
[f 2 1]Ein stabiles Stahlband. Verbessert die defensive Ausdauer enorm.[n][e]

[msg Item_023]
[f 2 1]Ein luftig-leichtes Stoffband. Damit fühlt man sich fast schwerelos.[n][e]

[msg Item_024]
[f 2 1]Ein kunterbuntes Flechtband. Bringt enorm viel Glück.[n][e]

[msg Item_025]
[f 2 1]未使用[n][e]

[msg Item_026]
[f 2 1]未使用[n][e]

[msg Item_027]
[f 2 1]Macht den Träger zu Kampfbeginn vorübergehend stärker.[n][e]

[msg Item_028]
[f 2 1]Macht den Träger zu Kampfbeginn vorübergehend ausdauernder.[n][e]

[msg Item_029]
[f 2 1]Macht den Träger zu Kampfbeginn vorübergehend beweglicher.[n][e]

[msg Item_02A]
[f 2 1]Ein Armreif mit Flammendekor. Erhöht Feuerschaden.[n][e]

[msg Item_02B]
[f 2 1]Enthält die Macht des Feuergottes. Erhöht Feuerschaden beträchtlich.[n][e]

[msg Item_02C]
[f 2 1]Ein Armreif mit Eisdekor. Erhöht Eisschaden.[n][e]

[msg Item_02D]
[f 2 1]Enthält die Macht des Eisgottes. Erhöht Eisschaden beträchtlich.[n][e]

[msg Item_02E]
[f 2 1]Ein Armreif mit Blitzdekor. Erhöht Elektroschaden.[n][e]

[msg Item_02F]
[f 2 1]Enthält die Macht des Himmelsgottes. Erhöht Elektroschaden beträchtlich.[n][e]

[msg Item_030]
[f 2 1]Ein Armreif mit Winddekor. Erhöht Windschaden.[n][e]

[msg Item_031]
[f 2 1]Enthält die Macht des Windgottes. Erhöht Windschaden beträchtlich.[n][e]

[msg Item_032]
[f 2 1]Ein mysteriöser Rosenkranz, der die Angriffskraft des Trägers im Zustand "Wütend" erhöht.[n][e]

[msg Item_033]
[f 2 1]Eine niedliche Kürbismaske. Erhöht Dunkelheitsschaden.[n][e]

[msg Item_034]
[f 2 1]Macht vorübergehend alle Verbündeten zu Kampfbeginn stärker.[n][e]

[msg Item_035]
[f 2 1]Macht vorübergehend alle Verbündeten zu Kampfbeginn ausdauernder.[n][e]

[msg Item_036]
[f 2 1]Macht vorübergehend alle Verbündeten zu Kampfbeginn beweglicher.[n][e]

[msg Item_037]
[f 2 1]Erhöht die kritische Trefferchance des Trägers zu Kampfbeginn.[n][e]

[msg Item_038]
[f 2 1]未使用[n][e]

[msg Item_039]
[f 2 1]Eine Anleitung für eine Technik, um körperlichen Angriffen auszuweichen.[n][e]

[msg Item_03A]
[f 2 1]Eine primitive Verzauberung.[n]Verleiht die Fähigkeit, Magieangriffen[n]auszuweichen.[n][e]

[msg Item_03B]
[f 2 1]Eine Anleitung für eine Technik, um Hiebangriffen auszuweichen.[n][e]

[msg Item_03C]
[f 2 1]Ein Fortgeschrittenentext für eine Fähigkeit, um Hiebangriffen leichter auszuweichen.[n][e]

[msg Item_03D]
[f 2 1]Eine Anleitung für eine Technik, um Schlagangriffen auszuweichen.[n][e]

[msg Item_03E]
[f 2 1]Ein Fortgeschrittenentext für eine Fähigkeit, um Schlagangriffen leichter auszuweichen.[n][e]

[msg Item_03F]
[f 2 1]Eine Anleitung für eine Technik, um Durchbohrenangriffen auszuweichen.[n][e]

[msg Item_040]
[f 2 1]Ein Fortgeschrittenentext für eine Fähigkeit, um Durchbohrenangriffen leichter auszuweichen.[n][e]

[msg Item_041]
[f 2 1]Eine primitive Verzauberung. Verleiht die Fähigkeit, Feuerangriffen auszuweichen.[n][e]

[msg Item_042]
[f 2 1]Verbessert die Fähigkeit beträchtlich, Feuerangriffen auszuweichen.[n][e]

[msg Item_043]
[f 2 1]Eine primitive Verzauberung. Verleiht die Fähigkeit, Eisangriffen auszuweichen.[n][e]

[msg Item_044]
[f 2 1]Verbessert die Fähigkeit beträchtlich, Eisangriffen auszuweichen.[n][e]

[msg Item_045]
[f 2 1]Eine primitive Verzauberung. Verleiht die Fähigkeit, Windangriffen auszuweichen.[n][e]

[msg Item_046]
[f 2 1]Verbessert die Fähigkeit beträchtlich, Windangriffen auszuweichen.[n][e]

[msg Item_047]
[f 2 1]Eine primitive Verzauberung. Verleiht die Fähigkeit, Elektroangriffen auszuweichen.[n][e]

[msg Item_048]
[f 2 1]Verbessert die Fähigkeit beträchtlich, Elektroangriffen auszuweichen.[n][e]

[msg Item_049]
[f 2 1]Die Schlösser verbessern die eigene Fähigkeit, auf körperliche Angriffe zu reagieren.[n][e]

[msg Item_04A]
[f 2 1]Der uralte Text beschreibt die Geheimnisse des Ausweichens von Magieangriffen.[n][e]

[msg Item_04B]
[f 2 1]Ein einschüchterndes Armband. Damit ist der Träger schwerer zu treffen.[n][e]

[msg Item_04C]
[f 2 1]Eine primitive Verzauberung. Verleiht die Fähigkeit, Lichtangriffen auszuweichen.[n][e]

[msg Item_04D]
[f 2 1]Verbessert die Fähigkeit beträchtlich, Lichtangriffen auszuweichen.[n][e]

[msg Item_04E]
[f 2 1]Eine primitive Verzauberung. Verleiht die Fähigkeit, Dunkelheitsangriffen auszuweichen.[n][e]

[msg Item_04F]
[f 2 1]Verbessert die Fähigkeit beträchtlich, Dunkelheitsangriffen auszuweichen.[n][e]

[msg Item_050]
[f 2 1]未使用[n][e]

[msg Item_051]
[f 2 1]Die Stahlscheide soll jeden Schwerthieb abwehren.[n][e]

[msg Item_052]
[f 2 1]Ein dicker, goldener Panzer, dem Schläge nichts anhaben können.[n][e]

[msg Item_053]
[f 2 1]Eine unzerstörbare Tonfigur, die nichts durchbohren kann.[n][e]

[msg Item_054]
[f 2 1]Ein ungeheuer heißer Stein, der alle andere Hitze in den Schatten stellt.[n][e]

[msg Item_055]
[f 2 1]Ein wunderschöner, marineblauer Kristall, der Kälte und Frost aller Art abwehrt.[n][e]

[msg Item_056]
[f 2 1]Die Handschuhe trägt der Gott des Donners. Hebt sämtliche Elektrizität auf.[n][e]

[msg Item_057]
[f 2 1]Der Ring sieht aus wie eine Sturmböe. Lässt selbst den stärksten Sturm abebben.[n][e]

[msg Item_058]
[f 2 1]Ein rein weißer Ring, der vor heiligen Mächten schützt.[n][e]

[msg Item_059]
[f 2 1]Ein obsidianschwarzer Ring, der vor dunklen Mächten schützt.[n][e]

[msg Item_05A]
[f 2 1]Dieser besondere Armreif verströmt eine eisige Aura. Verhindert Starre.[n][e]

[msg Item_05B]
[f 2 1]Dieser besondere Armreif verströmt eine eisige Aura. Verhindert Schock.[n][e]

[msg Item_05C]
[f 2 1]Dieses Teil sieht aus wie das Horn eines Einhorns. Verhindert Vergiftung.[n][e]

[msg Item_05D]
[f 2 1]Dieses Schmuckstück erinnert an eine Horde Geister. Verhindert Verwirrung.[n][e]

[msg Item_05E]
[f 2 1]Diese Kugel an der Kette wirkt irgendwie beruhigend. Verhindert Qual.[n][e]

[msg Item_05F]
[f 2 1]Dieser Blumenschmuck lässt einen nicht in Versuchung geraten. Verhindert Charme.[n][e]

[msg Item_060]
[f 2 1]Diesen Augapfel kann man zur Beruhigung quetschen. Verhindert Furcht.[n][e]

[msg Item_061]
[f 2 1]Dieser blaue, edle Ring lässt beim Anblick allen Zorn verrauchen. Verhindert Wut.[n][e]

[msg Item_062]
[f 2 1]Dieses Buch verhindert Verwirrung, Qual, Charme, Furcht und Wut.[n][e]

[msg Item_063]
[f 2 1]Die Kugel besteht aus einem unbekannten Material, das nahezu unzerstörbar ist.[n][e]

[msg Item_064]
[f 2 1]Das Mal eines Meisterkriegers. Geringe Chance auf Konter bei körperlichen Angriffen.[n][e]

[msg Item_065]
[f 2 1]Das Mal des Kriegsgottes. Mittlere Chance auf Konter bei körperlichen Angriffen.[n][e]

[msg Item_066]
[f 2 1]Das Mal eines gefürchteten Berserkers. Hohe Chance auf Konter bei körperlichen Angriffen.[n][e]

[msg Item_067]
[f 2 1]Ein heiliges Artefakt. Der Benutzer kann nicht ausweichen, aber erlittener Schaden wird halbiert.[n][e]

[msg Item_068]
[f 2 1]Eine hochwertige Brille, die selbst in tiefster Dunkelheit einen extrem scharfen Blick gewährt.[n][e]

[msg Item_069]
[f 2 1]Hilft bei der Abwehr von Seelenleiden wie Furcht oder Versuchung.[n][e]

[msg Item_06A]
[f 2 1]Das Holzstück verströmt einen beruhigenden Duft. Beschleunigt die Erholung von Statuseffekten.[n][e]

[msg Item_06B]
[f 2 1]Verströmt einen angenehmen Duft. Hebt Statuseffekte sofort auf.[n][e]

[msg Item_06C]
[f 2 1]未使用[n][e]

[msg Item_06D]
[f 2 1]Das Siegel strahlt die Macht der Erde aus. Regeneriert pro Runde sehr wenige TP.[n][e]

[msg Item_06E]
[f 2 1]Das Siegel strahlt die Macht der Erde aus. Regeneriert pro Runde wenige TP.[n][e]

[msg Item_06F]
[f 2 1]Das Siegel strahlt die Macht des Weltraums aus. Regeneriert pro Runde TP.[n][e]

[msg Item_070]
[f 2 1]Das Abzeichen erweckt die Macht des Qi. Regeneriert pro Runde sehr wenige SP.[n][e]

[msg Item_071]
[f 2 1]Das Abzeichen verstärkt die Macht des Qi. Regeneriert pro Runde wenige SP.[n][e]

[msg Item_072]
[f 2 1]Das Abzeichen verströmt die Macht des Qi. Regeneriert pro Runde SP.[n][e]

[msg Item_073]
[f 2 1]Diese hübsche Puppe ist von Maiko. Regeneriert pro Runde sehr wenige SP.[n][e]

[msg Item_074]
[f 2 1]未使用[n][e]

[msg Item_075]
[f 2 1]Ein himmlisches Artefakt, das alle TP beim Tod 1x pro Kampf regeneriert.[n][e]

[msg Item_076]
[f 2 1]Dank dieser Gebetsperlen überlebt man einen einzelnen Dunkelh.-Instakill-Angriff mit 1 TP.[n][e]

[msg Item_077]
[f 2 1]Dank dieses Zubehörs überlebt man einen einzelnen Licht-Instakill-Angriff mit 1 TP.[n][e]

[msg Item_078]
[f 2 1]Dank dieser Armkette überlebt man einen einzelnen Instakill-Angriff mit 1 TP.[n][e]

[msg Item_079]
[f 2 1]未使用[n][e]

[msg Item_07A]
[f 2 1]未使用[n][e]

[msg Item_07B]
[f 2 1]未使用[n][e]

[msg Item_07C]
[f 2 1]未使用[n][e]

[msg Item_07D]
[f 2 1]Die Brosche aus einem teuren Material kostet viel Geld, hat aber sonst keine Funktion.[n][e]

[msg Item_07E]
[f 2 1]Der Ring halbiert die TP-Kosten von körperlichen Skills.[n][e]

[msg Item_07F]
[f 2 1]Der Ring halbiert die SP-Kosten von magischen Skills.[n][e]

[msg Item_080]
[f 2 1]未使用[n][e]

[msg Item_081]
[f 2 1]Verringert die Chance, kritische Treffer zu erleiden.[n][e]

[msg Item_082]
[f 2 1]Erhöht die Kritischer-Treffer-Rate des Nutzers.[n][e]

[msg Item_083]
[f 2 1]未使用[n][e]

[msg Item_084]
[f 2 1]未使用[n][e]

[msg Item_085]
[f 2 1]So eine Schärpe trugen schon die Samurai. Lässt ein klein wenig Vitalität aufflammen.[n][e]

[msg Item_086]
[f 2 1]So eine Schärpe trugen schon die Samurai. Lässt ein wenig Vitalität aufflammen.[n][e]

[msg Item_087]
[f 2 1]So eine Schärpe trugen schon die Samurai. Lässt etwas Vitalität aufflammen.[n][e]

[msg Item_088]
[f 2 1]So eine Schärpe trugen schon die Samurai. Lässt beträchtliche Vitalität aufflammen.[n][e]

[msg Item_089]
[f 2 1]So eine Schärpe trugen schon die Samurai. Lässt enorme Vitalität aufflammen.[n][e]

[msg Item_08A]
[f 2 1]Ein leuchtend rotes Banner, dem die Seelen zahlloser Krieger innewohnen.[n][e]

[msg Item_08B]
[f 2 1]Diese Verzauberung setzen Hexen ein. Lässt ein klein wenig magische Kraft aufflammen.[n][e]

[msg Item_08C]
[f 2 1]Diese Verzauberung setzen Hexen ein. Lässt ein wenig magische Kraft aufflammen.[n][e]

[msg Item_08D]
[f 2 1]Diese Verzauberung setzen Hexen ein. Lässt etwas magische Kraft aufflammen.[n][e]

[msg Item_08E]
[f 2 1]Diese Verzauberung setzen Hexen ein. Lässt beträchtliche magische Kraft aufflammen.[n][e]

[msg Item_08F]
[f 2 1]Diese Verzauberung setzen Hexen ein. Lässt enorme magische Kraft aufflammen.[n][e]

[msg Item_090]
[f 2 1]Der Haarschmuck entfesselt den sechsten Sinn des Trägers.[n][e]

[msg Item_091]
[f 2 1]Der Ring erhöht den Erfahrungsgewinn des Trägers im Kampf.[n][e]

[msg Item_092]
[f 2 1]Der Zauber maximiert den Erfahrungsgewinn des Nutzers im Kampf.[n][e]

[msg Item_093]
[f 2 1]未使用[n][e]

[msg Item_094]
[f 2 1]未使用[n][e]

[msg Item_095]
[f 2 1]未使用[n][e]

[msg Item_096]
[f 2 1]未使用[n][e]

[msg Item_097]
[f 2 1]未使用[n][e]

[msg Item_098]
[f 2 1]未使用[n][e]

[msg Item_099]
[f 2 1]未使用[n][e]

[msg Item_09A]
[f 2 1]未使用[n][e]

[msg Item_09B]
[f 2 1]So laut, dass der Träger nicht abgelenkt werden kann. Verhindert Benommenheit.[n][e]

[msg Item_09C]
[f 2 1]未使用[n][e]

[msg Item_09D]
[f 2 1]未使用[n][e]

[msg Item_09E]
[f 2 1]未使用[n][e]

[msg Item_09F]
[f 2 1]未使用[n][e]

[msg Item_0A0]
[f 2 1]未使用[n][e]

[msg Item_0A1]
[f 2 1]未使用[n][e]

[msg Item_0A2]
[f 2 1]未使用[n][e]

[msg Item_0A3]
[f 2 1]未使用[n][e]

[msg Item_0A4]
[f 2 1]Das Holzschildchen verringert die Chance, zu erstarren.[n][e]

[msg Item_0A5]
[f 2 1]Das Holzschildchen verringert die Chance, geschockt zu werden.[n][e]

[msg Item_0A6]
[f 2 1]Das Holzschildchen verringert die Chance, vergiftet zu werden.[n][e]

[msg Item_0A7]
[f 2 1]Das Holzschildchen verringert die Chance, verwirrt zu werden.[n][e]

[msg Item_0A8]
[f 2 1]Das Holzschildchen verringert die Chance, Qualen zu erleiden.[n][e]

[msg Item_0A9]
[f 2 1]Das Holzschildchen verringert die Chance, betört zu werden.[n][e]

[msg Item_0AA]
[f 2 1]Das Holzschildchen verringert die Chance, sich zu fürchten.[n][e]

[msg Item_0AB]
[f 2 1]Das Holzschildchen verringert die Chance, wütend zu werden.[n][e]

[msg Item_0AC]
[f 2 1]未使用[n][e]

[msg Item_0AD]
[f 2 1]未使用[n][e]

[msg Item_0AE]
[f 2 1]未使用[n][e]

[msg Item_0AF]
[f 2 1]未使用[n][e]

[msg Item_0B0]
[f 2 1]未使用[n][e]

[msg Item_0B1]
[f 2 1]未使用[n][e]

[msg Item_0B2]
[f 2 1]未使用[n][e]

[msg Item_0B3]
[f 2 1]未使用[n][e]

[msg Item_0B4]
[f 2 1]Das Holzschildchen erhöht die Chance, Verwirrung auszulösen.[n][e]

[msg Item_0B5]
[f 2 1]Das Holzschildchen erhöht die Chance, Qualen auszulösen.[n][e]

[msg Item_0B6]
[f 2 1]未使用[n][e]

[msg Item_0B7]
[f 2 1]Das Holzschildchen erhöht die Chance, Furcht auszulösen.[n][e]

[msg Item_0B8]
[f 2 1]未使用[n][e]

[msg Item_0B9]
[f 2 1]Das Holzschildchen erhöht die Chance, Benommenheit auszulösen.[n][e]

[msg Item_0BA]
[f 2 1]未使用[n][e]

[msg Item_0BB]
[f 2 1]未使用[n][e]

[msg Item_0BC]
[f 2 1]未使用[n][e]

[msg Item_0BD]
[f 2 1]未使用[n][e]

[msg Item_0BE]
[f 2 1]未使用[n][e]

[msg Item_0BF]
[f 2 1]未使用[n][e]

[msg Item_0C0]
[f 2 1]未使用[n][e]

[msg Item_0C1]
[f 2 1]未使用[n][e]

[msg Item_0C2]
[f 2 1]未使用[n][e]

[msg Item_0C3]
[f 2 1]未使用[n][e]

[msg Item_0C4]
[f 2 1]未使用[n][e]

[msg Item_0C5]
[f 2 1]未使用[n][e]

[msg Item_0C6]
[f 2 1]未使用[n][e]

[msg Item_0C7]
[f 2 1]未使用[n][e]

[msg Item_0C8]
[f 2 1]Die Ohrringe verringern den erlittenen Schaden von Hiebangriffen leicht.[n][e]

[msg Item_0C9]
[f 2 1]Die Brosche verringert den erlittenen Schaden von Hiebangriffen spürbar.[n][e]

[msg Item_0CA]
[f 2 1]Die Halskette verringert den erlittenen Schaden von Hiebangriffen erheblich.[n][e]

[msg Item_0CB]
[f 2 1]Die Ohrringe verringern den erlittenen Schaden von Schlagangriffen leicht.[n][e]

[msg Item_0CC]
[f 2 1]Die Brosche verringert den erlittenen Schaden von Schlagangriffen spürbar.[n][e]

[msg Item_0CD]
[f 2 1]Die Halskette verringert den erlittenen Schaden von Schlagangriffen erheblich.[n][e]

[msg Item_0CE]
[f 2 1]Die Ohrringe verringern den erlittenen Schaden von Durchbohrenangriffen leicht.[n][e]

[msg Item_0CF]
[f 2 1]Die Brosche verringert den erlittenen Schaden von Durchbohrenangriffen spürbar.[n][e]

[msg Item_0D0]
[f 2 1]Die Halskette verringert den erlittenen Schaden von Durchbohrenangriffen erheblich.[n][e]

[msg Item_0D1]
[f 2 1]Die Ohrringe verringern den erlittenen Schaden von körperlichen Angriffen leicht.[n][e]

[msg Item_0D2]
[f 2 1]Die Brosche verringert den erlittenen Schaden von körperlichen Angriffen spürbar.[n][e]

[msg Item_0D3]
[f 2 1]Die Halskette verringert den erlittenen Schaden von körperlichen Angriffen erheblich.[n][e]

[msg Item_0D4]
[f 2 1]Die Ohrringe verringern den erlittenen Schaden von Feuerangriffen leicht.[n][e]

[msg Item_0D5]
[f 2 1]Die Brosche verringert den erlittenen Schaden von Feuerangriffen spürbar.[n][e]

[msg Item_0D6]
[f 2 1]Die Halskette verringert den erlittenen Schaden von Feuerangriffen erheblich.[n][e]

[msg Item_0D7]
[f 2 1]Die Ohrringe verringern den erlittenen Schaden von Eisangriffen leicht.[n][e]

[msg Item_0D8]
[f 2 1]Die Brosche verringert den erlittenen Schaden von Eisangriffen spürbar.[n][e]

[msg Item_0D9]
[f 2 1]Die Halskette verringert den erlittenen Schaden von Eisangriffen erheblich.[n][e]

[msg Item_0DA]
[f 2 1]Die Ohrringe verringern den erlittenen Schaden von Elektroangriffen leicht.[n][e]

[msg Item_0DB]
[f 2 1]Die Brosche verringert den erlittenen Schaden von Elektroangriffen spürbar.[n][e]

[msg Item_0DC]
[f 2 1]Die Halskette verringert den erlittenen Schaden von Elektroangriffen erheblich.[n][e]

[msg Item_0DD]
[f 2 1]Die Ohrringe verringern den erlittenen Schaden von Windangriffen leicht.[n][e]

[msg Item_0DE]
[f 2 1]Die Brosche verringert den erlittenen Schaden von Windangriffen spürbar.[n][e]

[msg Item_0DF]
[f 2 1]Die Halskette verringert den erlittenen Schaden von Windangriffen erheblich.[n][e]

[msg Item_0E0]
[f 2 1]Die Ohrringe verringern den erlittenen Schaden von Lichtangriffen leicht.[n][e]

[msg Item_0E1]
[f 2 1]Die Brosche verringert den erlittenen Schaden von Lichtangriffen spürbar.[n][e]

[msg Item_0E2]
[f 2 1]Die Halskette verringert den erlittenen Schaden von Lichtangriffen erheblich.[n][e]

[msg Item_0E3]
[f 2 1]Die Ohrringe verringern den erlittenen Schaden von Dunkelheitsangriffen leicht.[n][e]

[msg Item_0E4]
[f 2 1]Die Brosche verringert den erlittenen Schaden von Dunkelheitsangriffen spürbar.[n][e]

[msg Item_0E5]
[f 2 1]Die Halskette verringert den erlittenen Schaden von Dunkelheitsangriffen erheblich.[n][e]

[msg Item_0E6]
[f 2 1]Die Ohrringe verringern den erlittenen Schaden von Magieangriffen leicht.[n][e]

[msg Item_0E7]
[f 2 1]Die Brosche verringert den erlittenen Schaden von Magieangriffen spürbar.[n][e]

[msg Item_0E8]
[f 2 1]Die Halskette verringert den erlittenen Schaden von Magieangriffen erheblich.[n][e]

[msg Item_0E9]
[f 2 1]未使用[n][e]

[msg Item_0EA]
[f 2 1]未使用[n][e]

[msg Item_0EB]
[f 2 1]未使用[n][e]

[msg Item_0EC]
[f 2 1]未使用[n][e]

[msg Item_0ED]
[f 2 1]未使用[n][e]

[msg Item_0EE]
[f 2 1]未使用[n][e]

[msg Item_0EF]
[f 2 1]未使用[n][e]

[msg Item_0F0]
[f 2 1]Ein strahlend heller Armreif. Erhöht Lichtschaden.[n][e]

[msg Item_0F1]
[f 2 1]Enthält die Macht der Göttin der Morgendämmerung. Erhöht Lichtschaden beträchtlich.[n][e]

[msg Item_0F2]
[f 2 1]Ein Armreif mit tristem Design. Erhöht Dunkelheitsschaden.[n][e]

[msg Item_0F3]
[f 2 1]Erhöht Dunkelheitsschaden beträchtlich.[n][e]

[msg Item_0F4]
[f 2 1]Ein Armreif mit einem stilisierten Schwert. Erhöht Hiebschaden.[n][e]

[msg Item_0F5]
[f 2 1]Enthält die Macht des heiligen Schwerts. Erhöht Hiebschaden beträchtlich.[n][e]

[msg Item_0F6]
[f 2 1]Ein Armreif mit einer stilisierten Faust. Erhöht Schlagschaden.[n][e]

[msg Item_0F7]
[f 2 1]Enthält die Macht des heiligen Morgensterns. Erhöht Schlagschaden beträchtlich.[n][e]

[msg Item_0F8]
[f 2 1]Ein Armreif mit einem stilisierten Pfeil. Erhöht Durchbohrenschaden.[n][e]

[msg Item_0F9]
[f 2 1]Erhöht Durchbohrenschaden beträchtlich.[n][e]

[msg Item_0FA]
[f 2 1]未使用[n][e]

[msg Item_0FB]
[f 2 1]未使用[n][e]

[msg Item_0FC]
[f 2 1]未使用[n][e]

[msg Item_0FD]
[f 2 1]未使用[n][e]

[msg Item_0FE]
[f 2 1]未使用[n][e]

[msg Item_0FF]
[f 2 1]未使用[n][e]

[msg Item_100]
[f 2 1]未使用[n][e]

[msg Item_101]
[f 2 1]未使用[n][e]

[msg Item_102]
[f 2 1]未使用[n][e]

[msg Item_103]
[f 2 1]未使用[n][e]

[msg Item_104]
[f 2 1]Der Schal widersteht Feuerschaden für 3 Runden nach Kampfbeginn.[n][e]

[msg Item_105]
[f 2 1]Der Schal widersteht Eisschaden für 3 Runden nach Kampfbeginn.[n][e]

[msg Item_106]
[f 2 1]Der Schal widersteht[n]Elektroschaden für[n]3 Runden nach Kampfbeginn.[n][e]

[msg Item_107]
[f 2 1]Der Schal widersteht Windschaden für 3 Runden nach Kampfbeginn.[n][e]

[msg Item_108]
[f 2 1]Stellt SP wieder her, wenn der Träger einen Wechsel erleidet.[n][e]

[msg Item_109]
[f 2 1]Ein Zubehörprototyp, der den Träger mit einem Magnetfeld schützt.[n][e]

[msg Item_10A]
[f 2 1]Ein luxuriöses Goldband. Verbessert alle Attribute spürbar.[n][e]

[msg Item_10B]
[f 2 1]Erhöht die Angriffskraft, wenn der Träger getauscht wird.[n][e]

[msg Item_10C]
[f 2 1]Eine Verzauberung, die alle TP beim Tod 1x pro Kampf regeneriert.[n][e]

[msg Item_10D]
[f 2 1]Entfesselt einen Stärkeschub, der von den Bindungen des Trägers abhängt.[n][e]

[msg Item_10E]
[f 2 1]Den süßen Schlüsselanhänger hat Chihiro für dich gemacht.[n][e]

[msg Item_10F]
[f 2 1]Eine luxuriöse Halskette, die den Träger vor allen Statuseffekten bewahrt.[n][e]

[msg Item_110]
[f 2 1]Die Ohrringe stellen 1 TP beim Tod 1x pro Kampf wieder her.[n][e]

[msg Item_111]
[f 2 1]未使用[n][e]

[msg Item_112]
[f 2 1]未使用[n][e]

[msg Item_113]
[f 2 1]未使用[n][e]

[msg Item_114]
[f 2 1]未使用[n][e]

[msg Item_115]
[f 2 1]未使用[n][e]

[msg Item_116]
[f 2 1]未使用[n][e]

[msg Item_117]
[f 2 1]未使用[n][e]

[msg Item_118]
[f 2 1]未使用[n][e]

[msg Item_119]
[f 2 1]未使用[n][e]

[msg Item_11A]
[f 2 1]未使用[n][e]

[msg Item_11B]
[f 2 1]未使用[n][e]

[msg Item_11C]
[f 2 1]未使用[n][e]

[msg Item_11D]
[f 2 1]未使用[n][e]

[msg Item_11E]
[f 2 1]未使用[n][e]

[msg Item_11F]
[f 2 1]未使用[n][e]

[msg Item_120]
[f 2 1]未使用[n][e]

[msg Item_121]
[f 2 1]未使用[n][e]

[msg Item_122]
[f 2 1]未使用[n][e]

[msg Item_123]
[f 2 1]未使用[n][e]

[msg Item_124]
[f 2 1]未使用[n][e]

[msg Item_125]
[f 2 1]未使用[n][e]

[msg Item_126]
[f 2 1]未使用[n][e]

[msg Item_127]
[f 2 1]未使用[n][e]

[msg Item_128]
[f 2 1]未使用[n][e]

[msg Item_129]
[f 2 1]未使用[n][e]

[msg Item_12A]
[f 2 1]未使用[n][e]

[msg Item_12B]
[f 2 1]未使用[n][e]

[msg Item_12C]
[f 2 1]未使用[n][e]

[msg Item_12D]
[f 2 1]未使用[n][e]

[msg Item_12E]
[f 2 1]未使用[n][e]

[msg Item_12F]
[f 2 1]未使用[n][e]

[msg Item_130]
[f 2 1]未使用[n][e]

[msg Item_131]
[f 2 1]未使用[n][e]

[msg Item_132]
[f 2 1]未使用[n][e]

[msg Item_133]
[f 2 1]未使用[n][e]

[msg Item_134]
[f 2 1]未使用[n][e]

[msg Item_135]
[f 2 1]未使用[n][e]

[msg Item_136]
[f 2 1]未使用[n][e]

[msg Item_137]
[f 2 1]未使用[n][e]

[msg Item_138]
[f 2 1]未使用[n][e]

[msg Item_139]
[f 2 1]未使用[n][e]

[msg Item_13A]
[f 2 1]未使用[n][e]

[msg Item_13B]
[f 2 1]未使用[n][e]

[msg Item_13C]
[f 2 1]未使用[n][e]

[msg Item_13D]
[f 2 1]未使用[n][e]

[msg Item_13E]
[f 2 1]未使用[n][e]

[msg Item_13F]
[f 2 1]未使用[n][e]

[msg Item_140]
[f 2 1]未使用[n][e]

[msg Item_141]
[f 2 1]未使用[n][e]

[msg Item_142]
[f 2 1]未使用[n][e]

[msg Item_143]
[f 2 1]未使用[n][e]

[msg Item_144]
[f 2 1]未使用[n][e]

[msg Item_145]
[f 2 1]未使用[n][e]

[msg Item_146]
[f 2 1]未使用[n][e]

[msg Item_147]
[f 2 1]未使用[n][e]

[msg Item_148]
[f 2 1]未使用[n][e]

[msg Item_149]
[f 2 1]未使用[n][e]

[msg Item_14A]
[f 2 1]未使用[n][e]

[msg Item_14B]
[f 2 1]未使用[n][e]

[msg Item_14C]
[f 2 1]未使用[n][e]

[msg Item_14D]
[f 2 1]未使用[n][e]

[msg Item_14E]
[f 2 1]未使用[n][e]

[msg Item_14F]
[f 2 1]未使用[n][e]

[msg Item_150]
[f 2 1]未使用[n][e]

[msg Item_151]
[f 2 1]未使用[n][e]

[msg Item_152]
[f 2 1]未使用[n][e]

[msg Item_153]
[f 2 1]未使用[n][e]

[msg Item_154]
[f 2 1]未使用[n][e]

[msg Item_155]
[f 2 1]未使用[n][e]

[msg Item_156]
[f 2 1]未使用[n][e]

[msg Item_157]
[f 2 1]未使用[n][e]

[msg Item_158]
[f 2 1]未使用[n][e]

[msg Item_159]
[f 2 1]未使用[n][e]

[msg Item_15A]
[f 2 1]未使用[n][e]

[msg Item_15B]
[f 2 1]未使用[n][e]

[msg Item_15C]
[f 2 1]未使用[n][e]

[msg Item_15D]
[f 2 1]未使用[n][e]

[msg Item_15E]
[f 2 1]未使用[n][e]

[msg Item_15F]
[f 2 1]未使用[n][e]

[msg Item_160]
[f 2 1]未使用[n][e]

[msg Item_161]
[f 2 1]未使用[n][e]

[msg Item_162]
[f 2 1]未使用[n][e]

[msg Item_163]
[f 2 1]未使用[n][e]

[msg Item_164]
[f 2 1]未使用[n][e]

[msg Item_165]
[f 2 1]未使用[n][e]

[msg Item_166]
[f 2 1]未使用[n][e]

[msg Item_167]
[f 2 1]未使用[n][e]

[msg Item_168]
[f 2 1]未使用[n][e]

[msg Item_169]
[f 2 1]未使用[n][e]

[msg Item_16A]
[f 2 1]未使用[n][e]

[msg Item_16B]
[f 2 1]未使用[n][e]

[msg Item_16C]
[f 2 1]未使用[n][e]

[msg Item_16D]
[f 2 1]未使用[n][e]

[msg Item_16E]
[f 2 1]未使用[n][e]

[msg Item_16F]
[f 2 1]未使用[n][e]

[msg Item_170]
[f 2 1]未使用[n][e]

[msg Item_171]
[f 2 1]未使用[n][e]

[msg Item_172]
[f 2 1]未使用[n][e]

[msg Item_173]
[f 2 1]未使用[n][e]

[msg Item_174]
[f 2 1]未使用[n][e]

[msg Item_175]
[f 2 1]未使用[n][e]

[msg Item_176]
[f 2 1]未使用[n][e]

[msg Item_177]
[f 2 1]未使用[n][e]

[msg Item_178]
[f 2 1]未使用[n][e]

[msg Item_179]
[f 2 1]未使用[n][e]

[msg Item_17A]
[f 2 1]未使用[n][e]

[msg Item_17B]
[f 2 1]未使用[n][e]

[msg Item_17C]
[f 2 1]未使用[n][e]

[msg Item_17D]
[f 2 1]未使用[n][e]

[msg Item_17E]
[f 2 1]未使用[n][e]

[msg Item_17F]
[f 2 1]未使用[n][e]

[msg Item_180]
[f 2 1]未使用[n][e]

[msg Item_181]
[f 2 1]未使用[n][e]

[msg Item_182]
[f 2 1]未使用[n][e]

[msg Item_183]
[f 2 1]未使用[n][e]

[msg Item_184]
[f 2 1]未使用[n][e]

[msg Item_185]
[f 2 1]未使用[n][e]

[msg Item_186]
[f 2 1]未使用[n][e]

[msg Item_187]
[f 2 1]未使用[n][e]

[msg Item_188]
[f 2 1]未使用[n][e]

[msg Item_189]
[f 2 1]未使用[n][e]

[msg Item_18A]
[f 2 1]未使用[n][e]

[msg Item_18B]
[f 2 1]未使用[n][e]

[msg Item_18C]
[f 2 1]未使用[n][e]

[msg Item_18D]
[f 2 1]未使用[n][e]

[msg Item_18E]
[f 2 1]未使用[n][e]

[msg Item_18F]
[f 2 1]未使用[n][e]

[msg Item_190]
[f 2 1]未使用[n][e]

[msg Item_191]
[f 2 1]未使用[n][e]

[msg Item_192]
[f 2 1]未使用[n][e]

[msg Item_193]
[f 2 1]未使用[n][e]

[msg Item_194]
[f 2 1]未使用[n][e]

[msg Item_195]
[f 2 1]未使用[n][e]

[msg Item_196]
[f 2 1]未使用[n][e]

[msg Item_197]
[f 2 1]未使用[n][e]

[msg Item_198]
[f 2 1]未使用[n][e]

[msg Item_199]
[f 2 1]未使用[n][e]

[msg Item_19A]
[f 2 1]未使用[n][e]

[msg Item_19B]
[f 2 1]未使用[n][e]

[msg Item_19C]
[f 2 1]未使用[n][e]

[msg Item_19D]
[f 2 1]未使用[n][e]

[msg Item_19E]
[f 2 1]未使用[n][e]

[msg Item_19F]
[f 2 1]未使用[n][e]

[msg Item_1A0]
[f 2 1]未使用[n][e]

[msg Item_1A1]
[f 2 1]未使用[n][e]

[msg Item_1A2]
[f 2 1]未使用[n][e]

[msg Item_1A3]
[f 2 1]未使用[n][e]

[msg Item_1A4]
[f 2 1]未使用[n][e]

[msg Item_1A5]
[f 2 1]未使用[n][e]

[msg Item_1A6]
[f 2 1]未使用[n][e]

[msg Item_1A7]
[f 2 1]未使用[n][e]

[msg Item_1A8]
[f 2 1]未使用[n][e]

[msg Item_1A9]
[f 2 1]未使用[n][e]

[msg Item_1AA]
[f 2 1]未使用[n][e]

[msg Item_1AB]
[f 2 1]未使用[n][e]

[msg Item_1AC]
[f 2 1]未使用[n][e]

[msg Item_1AD]
[f 2 1]未使用[n][e]

[msg Item_1AE]
[f 2 1]未使用[n][e]

[msg Item_1AF]
[f 2 1]未使用[n][e]

[msg Item_1B0]
[f 2 1]未使用[n][e]

[msg Item_1B1]
[f 2 1]未使用[n][e]

[msg Item_1B2]
[f 2 1]未使用[n][e]

[msg Item_1B3]
[f 2 1]未使用[n][e]

[msg Item_1B4]
[f 2 1]未使用[n][e]

[msg Item_1B5]
[f 2 1]未使用[n][e]

[msg Item_1B6]
[f 2 1]未使用[n][e]

[msg Item_1B7]
[f 2 1]未使用[n][e]

[msg Item_1B8]
[f 2 1]未使用[n][e]

[msg Item_1B9]
[f 2 1]未使用[n][e]

[msg Item_1BA]
[f 2 1]未使用[n][e]

[msg Item_1BB]
[f 2 1]未使用[n][e]

[msg Item_1BC]
[f 2 1]未使用[n][e]

[msg Item_1BD]
[f 2 1]未使用[n][e]

[msg Item_1BE]
[f 2 1]未使用[n][e]

[msg Item_1BF]
[f 2 1]未使用[n][e]

[msg Item_1C0]
[f 2 1]未使用[n][e]

[msg Item_1C1]
[f 2 1]未使用[n][e]

[msg Item_1C2]
[f 2 1]未使用[n][e]

[msg Item_1C3]
[f 2 1]未使用[n][e]

[msg Item_1C4]
[f 2 1]未使用[n][e]

[msg Item_1C5]
[f 2 1]未使用[n][e]

[msg Item_1C6]
[f 2 1]未使用[n][e]

[msg Item_1C7]
[f 2 1]未使用[n][e]

[msg Item_1C8]
[f 2 1]未使用[n][e]

[msg Item_1C9]
[f 2 1]未使用[n][e]

[msg Item_1CA]
[f 2 1]未使用[n][e]

[msg Item_1CB]
[f 2 1]未使用[n][e]

[msg Item_1CC]
[f 2 1]未使用[n][e]

[msg Item_1CD]
[f 2 1]未使用[n][e]

[msg Item_1CE]
[f 2 1]未使用[n][e]

[msg Item_1CF]
[f 2 1]未使用[n][e]

[msg Item_1D0]
[f 2 1]未使用[n][e]

[msg Item_1D1]
[f 2 1]未使用[n][e]

[msg Item_1D2]
[f 2 1]未使用[n][e]

[msg Item_1D3]
[f 2 1]未使用[n][e]

[msg Item_1D4]
[f 2 1]未使用[n][e]

[msg Item_1D5]
[f 2 1]未使用[n][e]

[msg Item_1D6]
[f 2 1]未使用[n][e]

[msg Item_1D7]
[f 2 1]未使用[n][e]

[msg Item_1D8]
[f 2 1]未使用[n][e]

[msg Item_1D9]
[f 2 1]未使用[n][e]

[msg Item_1DA]
[f 2 1]未使用[n][e]

[msg Item_1DB]
[f 2 1]未使用[n][e]

[msg Item_1DC]
[f 2 1]未使用[n][e]

[msg Item_1DD]
[f 2 1]未使用[n][e]

[msg Item_1DE]
[f 2 1]未使用[n][e]

[msg Item_1DF]
[f 2 1]未使用[n][e]

[msg Item_1E0]
[f 2 1]未使用[n][e]

[msg Item_1E1]
[f 2 1]未使用[n][e]

[msg Item_1E2]
[f 2 1]未使用[n][e]

[msg Item_1E3]
[f 2 1]未使用[n][e]

[msg Item_1E4]
[f 2 1]未使用[n][e]

[msg Item_1E5]
[f 2 1]未使用[n][e]

[msg Item_1E6]
[f 2 1]未使用[n][e]

[msg Item_1E7]
[f 2 1]未使用[n][e]

[msg Item_1E8]
[f 2 1]未使用[n][e]

[msg Item_1E9]
[f 2 1]未使用[n][e]

[msg Item_1EA]
[f 2 1]未使用[n][e]

[msg Item_1EB]
[f 2 1]未使用[n][e]

[msg Item_1EC]
[f 2 1]未使用[n][e]

[msg Item_1ED]
[f 2 1]未使用[n][e]

[msg Item_1EE]
[f 2 1]未使用[n][e]

[msg Item_1EF]
[f 2 1]未使用[n][e]

[msg Item_1F0]
[f 2 1]未使用[n][e]

[msg Item_1F1]
[f 2 1]未使用[n][e]

[msg Item_1F2]
[f 2 1]未使用[n][e]

[msg Item_1F3]
[f 2 1]未使用[n][e]

[msg Item_1F4]
[f 2 1]未使用[n][e]

[msg Item_1F5]
[f 2 1]未使用[n][e]

[msg Item_1F6]
[f 2 1]未使用[n][e]

[msg Item_1F7]
[f 2 1]未使用[n][e]

[msg Item_1F8]
[f 2 1]未使用[n][e]

[msg Item_1F9]
[f 2 1]未使用[n][e]

[msg Item_1FA]
[f 2 1]未使用[n][e]

[msg Item_1FB]
[f 2 1]未使用[n][e]

[msg Item_1FC]
[f 2 1]未使用[n][e]

[msg Item_1FD]
[f 2 1]未使用[n][e]

[msg Item_1FE]
[f 2 1]未使用[n][e]

[msg Item_1FF]
[f 2 1]未使用[n][e]

