[msg MSG_000_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]Você conseguiu mesmo me acompanhar no treino. Impressionante.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 0 0 0 2 0 0][uf 4 23 0 4 0 25 25]...[n][uf 1 1][e]

[msg MSG_001_0_0 [(Fundo) Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 3 0 0]Hunf![n][uf 1 1][e]

[msg MSG_002_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]E aí, o que você acha?[n][uf 1 1][e]

[sel SEL_003_0_0 top]
[uf 0 5 65278][uf 2 1]Do quê?[e]
[uf 0 5 65278][uf 2 1]Que cansaço.[e]

[msg MSG_004_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]Bem...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]Eu te pedi para vir aqui comigo hoje porque...[n][uf 1 1][e]

[msg MSG_005_0_0 [Voz rouca]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 7 0 0][uf 5 21 0 1001]Até que enfim te achamos, Akihiko Sanada.[n][uf 1 1][e]

[msg MSG_006_0_0 [Homem mal-encarado]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 8 0 0][uf 5 21 0 1001]Foi divertido até aqui, mas chegou a hora de pôr um fim nisso.[n][uf 1 1][e]

[msg MSG_007_0_0 [Lacaio]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 9 0 0][uf 5 21 0 1002]Não se acanha, pode gritar se quiser. Mas ninguém vai vir te salvar.[n][uf 1 1][e]

[msg MSG_008_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]Esses caras não sabem quando desistir.[n][uf 1 1][e]

[msg MSG_009_0_0 [Subalterno]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 11 0 0][uf 5 21 0 1003]Dessa vez você não escapa. Nem você nem sua amiguinha de merda aí.[n][uf 1 1][e]

[msg MSG_010_0_0 [Homem mal-encarado]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 12 0 0][uf 5 21 0 1001]Não que faça diferença. Vocês moram no alojamento aqui perto, né?[n][uf 1 1][e]

[msg MSG_011_0_0 [Lacaio]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 13 0 0][uf 5 21 0 1002]É, a gente viu umas garotas lá, até um menininho. Tomara que eles estejam seguros lá, né? Hahahaha![n][uf 1 1][e]

[sel SEL_012_0_0 top]
[uf 0 5 65278][uf 2 1]Vocês não vão se safar dessa.[e]
[uf 0 5 65278][uf 2 1]Vocês são lixo.[e]

[msg MSG_013_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]Pra trás, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 65535 65535 0 0][uf 3 1 1 0 0 15 0 0][uf 4 23 0 4 2 25 25]Eu vou abrir uma brecha pra você poder fugir.[n][uf 1 1][e]

[msg MSG_014_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 65535 65535 0 0][uf 3 1 1 0 0 16 0 0]Se vocês vão atrás dos meus amigos, então eu vou ser o primeiro obstáculo.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 65535 65535 0 0][uf 3 1 1 0 0 17 0 0]Vai, podem vir.[n][uf 1 1][e]

[msg MSG_015_0_0 [Homem mal-encarado]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 18 0 0][uf 5 21 0 1001]Ngh...[n][uf 1 1][e]

[msg MSG_016_0_0 [Homem mal-encarado]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 19 0 0][uf 5 21 0 1001]V-Você não sabe o que vai rolar se um sujeito treinado feito você bater num amador?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 20 0 0][uf 5 21 0 1001]A equipe de boxe vai ser suspensa, e você vai ser expulso! Ou pior ainda, vão te jogar na cadeia e sua vida já era![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 21 0 0][uf 5 21 0 1001]É isso que você quer, é?![n][uf 1 1][e]

[msg MSG_017_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 22 0 0]É verdade. Eu jamais poderia fazer algo assim com o meu supervisor ou meus colegas do boxe.[n][uf 1 1][e]

[msg MSG_018_0_0 [Lacaio]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 23 0 0][uf 5 21 0 1002]Heheheh.[n][uf 1 1][e]

[msg MSG_019_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 65535 65535 0 0][uf 3 1 1 0 0 24 0 0]Mas... mesmo que seja assim que eu penso, não vou recuar agora.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 65535 65535 0 0][uf 3 1 1 0 0 25 0 0]Eu vou carregar o fardo dessa responsabilidade e pagar pelo resto da minha vida, se for preciso.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 65535 65535 0 0][uf 3 1 1 0 0 26 0 0]Tudo para proteger o que é importante pra mim... É pra isso que servem meus punhos.[n][uf 1 1][e]

[msg MSG_020_0_0 [Subalterno]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 27 0 0][uf 5 21 0 1003]De que merda você tá falando?![n][uf 1 1][e]

[msg MSG_021_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 4 65535 65535 0 0][uf 3 1 1 0 0 28 0 0]Ah, [uf 4 1]...[n][uf 1 1][e]

[sel SEL_022_0_0 top]
[uf 0 5 65278][uf 2 1]Vamos dar um jeito neles.[e]
[uf 0 5 65278][uf 2 1]É legítima defesa.[e]

[msg MSG_023_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 29 0 0]Heh, tudo bem, então.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 30 0 0][uf 4 23 0 4 0 25 25]Eu confio que você vai me dar cobertura. Só tenta não machucar os caras. Sei que você consegue.[n][uf 1 1][e]

[msg MSG_024_0_0 [Homem mal-encarado]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 31 0 0][uf 5 21 0 1001]Seus metidinhos![n][uf 1 1][e]

[msg MSG_025_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 32 0 0]Acho que isso já resolve. Foi um bom desafio, considerando a quantidade.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 33 0 0]Você está bem, [uf 4 1]?[n][uf 1 1][e]

[msg MSG_026_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 65535 65535 0 0][uf 3 1 1 0 0 34 0 0]Não apareçam por aqui nunca mais.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 65535 65535 0 0][uf 3 1 1 0 0 35 0 0]Se eu ficar sabendo que vocês ameaçaram meus amigos, já sabem o que vai acontecer.[n][uf 1 1][e]

[msg MSG_027_0_0 [Homem mal-encarado]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 36 0 0]T-Tá bom...[n][uf 1 1][e]

[msg MSG_028_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 37 0 0]Vamos, tá esfriando. E alguém deve ter chamado a polícia também.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 38 0 0]Por ora vamos pro meu quarto.[n][uf 1 1][e]

