[msg MSG_001_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 6 155 65535 0 0][vp 1 0 0 4 0 0]Huh? Junpei-kun and Ryoji-kun are lying on the ground over there.[n][w][e]

[msg MSG_001_1_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 6 155 65535 0 0][vp 1 0 0 5 0 0]Their faces are all red. Are they okay?[n][w][e]

[msg MSG_002_0_0 [Yukari Takeba]]
[f 2 1][bup 2 3 155 65535 0 0][vp 1 0 0 6 0 0]I bet they were doing something stupid again.[n][w][e]
[f 2 1][bup 2 3 155 65535 0 0][vp 1 0 0 7 0 0]Just leave 'em alone.[n][w][e]

