[msg MND_000_0_0 [Internal MES]]
[uf 0 5 65278][uf 2 1]The scratching of pencils echoes[n]throughout the art room...[n][uf 1 1][e]

[msg MSG_001_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]Let's see, on cleaning duty today is... Hiraga-senpai and you, [uf 4 1]-chan. Thanks for your help![n][uf 1 1][e]

[msg MSG_002_0_0 [Male Club Member]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 2 0 0][uf 5 21 0 100]All right, we're outta here![n][uf 1 1][e]

[msg MSG_003_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]Okay, let's make this quick.[n][uf 1 1][e]

[msg MSG_004_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]This room's smaller than my bedroom, but it's still surprisingly big.[n][uf 1 1][e]

[msg MSG_004_5_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]Let's take a break.[n][uf 1 1][e]

[msg MSG_005_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]So, [uf 4 1]-chan, I've decided that I'm going to study abroad.[n][uf 1 1][e]

[msg MSG_005_3_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]To be honest, I'm not really excited about it.[n][uf 1 1][e]

[msg MSG_005_5_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 0 8 0 0]But I already told my teacher I don't want to be a doctor, so...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 0 0 0 9 0 0]......[n][uf 1 1][e]

[msg MSG_006_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]D-Do you want something to drink? It's on me.[n][uf 1 1][e]

[msg MSG_007_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 0 11 0 0]Oh, I almost forgot. Did you want something cold, or maybe—[n][uf 1 1][e]

[msg MSG_007_5_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 4 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]Hey! Look out![n][uf 1 2 35][e]

[msg MSG_008_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 2 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]Hey, [uf 4 1]-chan! Hang in there! Can you hear me? [uf 4 1]-cha...[n][uf 1 1][e]

[msg MND_009_0_0 [Internal MES]]
[uf 0 5 65278][uf 2 1]Hiraga's voice sounds like it's[n]getting farther and farther away...[n][uf 1 1][e]

