[msg MSG_000_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 51 65535 0 0][uf 3 1 1 0 0 1 0 0]Oye, ¿estás bien?[n][uf 1 1][e]

[msg MSG_001_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 51 65535 0 0][uf 3 1 1 0 0 2 0 0]¿A ti qué te pasa? Pareces una zombi.[n][uf 1 1][e]

[sel SEL_002_0_0 top]
[uf 0 5 65278][uf 2 1]Nada.[e]
[uf 0 5 65278][uf 2 1]He abierto una puerta y...[e]

[msg MSG_003_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 51 65535 0 0][uf 3 1 1 0 0 3 0 0]¡No me digas que te has sobado![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 51 65535 0 0][uf 3 1 1 0 0 4 0 0]¡Me has recordado al entrenador que se quedó frito en un partido del campeonato![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 51 65535 0 0][uf 3 1 1 0 0 5 0 0][uf 4 23 0 1 3 25 25]Venga, mujer, que se supone que eres la líder.[n][uf 1 1][e]

[msg MND_004_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]Parece que no ven la puerta.[n][uf 1 1][e]

[msg MSG_005_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 51 65535 0 0][uf 3 1 1 0 0 6 0 0]No te pases con ella. Si está todo bien, continuemos.[n][uf 1 1][e]

[msg MSG_006_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 51 65535 0 0][uf 3 1 1 0 0 7 0 0]¿Eh? ¿Qué puerta?[n][uf 1 1][e]

[msg MSG_007_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 51 65535 0 0][uf 3 1 1 0 0 8 0 0]Chica, a ti se te va la olla.[n][uf 1 1][e]

[msg MND_008_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]Parece que no ven la puerta.[n][uf 1 1][e]

[msg MSG_009_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 51 65535 0 0][uf 3 1 1 0 0 9 0 0]¿Te has quedado traspuesta? Pareces aturdida.[n][uf 1 1][e]

[msg MSG_010_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 51 65535 0 0][uf 3 1 1 0 0 10 0 0]Tía, que se supone que eres la líder. ¡Céntrate un poco![n][uf 1 1][e]

[msg MSG_011_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 51 65535 0 0][uf 3 1 1 0 0 11 0 0]Te seguimos. Venga, vamos.[n][uf 1 1][e]

