[msg MSG_009_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0][uf 4 23 0 1 0 25 25]This series always has such crazy plot twists.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 65535 65535 0 0][uf 3 1 1 0 0 2 0 0][uf 4 23 0 1 2 25 25]When the main girl's best friend betrayed her... I was like, "WHAT!?"[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0][uf 3 1 1 0 0 3 0 0][uf 4 23 0 1 3 25 25]Being backstabbed by the one person you trusted most is just horrible.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 4 0 0][uf 4 23 0 1 0 25 25]What would you do if that happened to you?[n][uf 1 1][e]

[sel SEL_010_0_0 top]
[uf 0 5 65278][uf 2 1]It's whatever.[e]
[uf 0 5 65278][uf 2 1]I'd never recover.[e]
[uf 0 5 65278][uf 2 1]Forgive and forget.[e]

[msg MSG_011_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 0 5 0 0][uf 4 23 0 1 1 25 25]Ahaha... You're not bothered by anything, huh? But that's just something special about you, [uf 4 1]-chan.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0][uf 3 1 1 0 0 6 0 0][uf 4 23 0 1 3 25 25]I find it quite difficult to think like that...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0][uf 3 1 1 0 0 7 0 0][uf 4 23 0 1 3 25 25]It wasn't really a betrayal, but I was reminded of a time a girl I was close to suddenly started avoiding me.[n][uf 1 1][e]

[msg MSG_012_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0][uf 3 1 1 0 0 8 0 0][uf 4 23 0 1 3 25 25]Yeah... Even without a dramatic betrayal, I'd be hurt if a friend started treating me differently.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0][uf 3 1 1 0 0 9 0 0][uf 4 23 0 1 3 25 25]That happened to me once. A girl I was close to suddenly started avoiding me.[n][uf 1 1][e]

[msg MSG_013_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 65535 65535 0 0][uf 3 1 1 0 0 10 0 0][uf 4 23 0 1 4 25 25][uf 4 1]-chan... That's awfully admirable. You sound just like the main character.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0][uf 3 1 1 0 0 11 0 0][uf 4 23 0 1 3 25 25]To be honest... there was once a girl I was close to who suddenly started avoiding me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0][uf 3 1 1 0 0 12 0 0][uf 4 23 0 1 3 25 25]It wasn't a full-blown betrayal or anything, but I was so hurt by that. It's hard to forgive and forget.[n][uf 1 1][e]

[msg MSG_014_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 65535 65535 0 0][uf 3 1 1 0 0 13 0 0][uf 4 23 0 1 4 25 25]Shoot, it's starting! It's so fast-paced, we really need to pay attention.[n][uf 1 1][e]

[msg MSG_015_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 65535 65535 0 0][uf 3 1 1 0 0 14 0 0][uf 4 23 0 1 4 25 25]No way! It's just gonna end like that!?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 65535 65535 0 0][uf 3 1 1 0 0 15 0 0][uf 4 23 0 1 6 25 25]Ugh, it happens every time, but they're so good at leaving you hanging...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 65535 65535 0 0][uf 3 1 1 0 0 16 0 0][uf 4 23 0 1 2 25 25][uf 5 13 7 1 2]I need to know how it ends. Let's watch more next time, okay?[n][uf 1 1][e]

[msg MND_016_0_0]
[uf 0 5 65278][uf 2 1]By observing the main character, I've begun to[n]understand the [uf 4 30 1 1 1 0] of an adult...[n][uf 1 1][e]

[msg MSG_017_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 0 17 0 0][uf 4 23 0 1 1 25 25]It's getting pretty late... We'd better head back to our rooms.[n][uf 1 1][e]

