[msg MSG_000_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 102 65535 0 0][vp 1 0 4 1 0 0][nl] ! Aide-nous, s'il te plaît ![n][w][e]
[f 2 1][bup 6 4 102 65535 0 0][vp 1 0 4 2 0 0]Junpei n'arrête pas... Ah ! Aaah ![n][w][e]

[msg MSG_001_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 102 65535 0 0][vp 1 0 4 3 0 0]Héhé ! Et vlan ! Prends ça ! Et ça ![n][w][e]
[f 2 1][bup 3 1 102 65535 0 0][vp 1 0 4 4 0 0]Allez, les batailles d'eau, c'est obligé à la plage ! Ça rafraîchit, hein ?[n][w][e]

[msg MSG_002_0_0 [Yukari Takeba]]
[f 2 1][bup 2 2 102 65535 0 0][vp 1 0 4 5 0 0]Hé, arrête ça ! Tu vas trop loin ! OK, tu sais quoi... tu l'auras voulu ![n][w][e]

[msg MSG_003_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 155 65535 0 0][vp 1 0 4 1 0 0]J'ai vu Yukari et Kirijo ensemble tout à l'heure.[n][w][e]
[f 2 1][bup 6 0 155 65535 0 0][vp 1 0 4 2 0 0]Elles avaient l'air de passer un bon moment ensemble. C'est rare.[n][w][e]

[msg MSG_004_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 155 65535 0 0][vp 1 0 4 1 0 0]Je suis contente de voir que Kirijo a l'air d'aller mieux.[n][w][e]

[msg MND_GENERAL_EVENTPLAY]
[f 2 1]Message issued by the script. [n][f 1 5 0]Comm Event Replay.[n][w][e]

[msg MND_GENERAL_PERSPNA]
[f 2 1][f 2 4 2] et la Persona [clr 35][f 2 4 5][clr 27] peuvent nous aider à nous rapprocher.[n][w][e]

[msg MND_GENERALSELECTMSG_MAX]
[f 2 1]Je ressens un lien indéfectible avec [f 2 4 0]...[n][w][e]

[msg MND_GENERALMSG_BS_MAX]
[f 2 1]Je ressens un lien indéfectible[n]avec le couple âgé...[n][w][e]

[msg MND_GENERALSELECTMSG_RAN]
[f 2 1][f 2 4 0] et moi allons bientôt nous rapprocher, je le sens...[n][w][e]

[msg MND_GENERALMSG_BS_RANKUP]
[f 2 1]Je crois que je vais bientôt me rapprocher[n]du couple âgé.[n][w][e]

[msg MND_GENERALSELECTMSG_NOR]
[f 2 1]Je ne pense pas que mon lien avec [f 2 4 0] se renforcera, même si on passe plus de temps ensemble.[n][w][e]

[msg MND_GENERALMSG_BS_NORMAL [Fuuka Yamagishi]]
[f 2 1]Je ne crois pas que nos liens se renforceront davantage, même si on passe plus de temps ensemble.[n][w][e]

[msg MND_GENERALSELECTMSG_MAX_2]
[f 2 1]Je ne crois pas que notre relation peut être plus approfondie.[n][w][e]
[f 2 1]Vais-je quand même passer du temps avec ?[n][w][e]

[msg MND_GENERAL_MSG_SOLO_AS]
[f 2 1]Vais-je passer du temps avec [f 2 4 0] après les cours ?[n][w][e]

[msg MND_GENERAL_MSG_SOLO_DT]
[f 2 1]Vais-je passer la journée avec [f 2 4 0] ?[n][w][e]

[msg MND__GENERAL_MSG_NET]
[f 2 1]Vais-je passer du temps à jouer au MMORPG en ligne avec [f 2 4 0] ?[n][w][e]

[msg MND_GENERAL_MSG_SOLO_NT]
[f 2 1]Vais-je passer la soirée avec [f 2 4 0] ?[n][w][e]

[sel SEL_GENERALSELECTMSG_SOL top]
[f 2 1]Passer du temps avec [f 2 4 0][e]
[f 2 1]Voir le lien social[e]
[f 2 1]Non, c'est bon[e]

[msg MND_GENERAL_MSG_MULTIPLE]
[f 2 1]Vais-je passer du temps ici après les cours : [f 2 4 1] ?[n][w][e]

[msg MND_GENERAL_MSG_FASHION_]
[f 2 1]Vais-je passer du temps au club de mode après les cours ?[n][w][e]

[msg MND_GENERAL_MSG_BOOKSTOR]
[f 2 1]Vais-je passer la journée à la librairie ?[n][w][e]

[msg MND_GENERAL_MSG_BOOKSTOR_2]
[f 2 1]Vais-je passer du temps à la librairie après les cours ?[n][w][e]

[msg MND_GENERAL_MSG_MULTIPLE_2]
[f 2 1]Vais-je passer la soirée avec [f 2 4 1] ?[n][w][e]

[sel SEL_GENERALSELECTMSG_MUL top]
[f 2 1]Participer à : [f 2 4 1][e]
[f 2 1]Voir le lien social[e]
[f 2 1]Non, c'est bon[e]

[sel SEL_GENERALSELECTMSG_FCL top]
[f 2 1]Aller au club de mode[e]
[f 2 1]Voir le lien social[e]
[f 2 1]Ne rien faire[e]

[sel SEL_GENERALSELECTMSG_BS top]
[f 2 1]Entrer dans la librairie[e]
[f 2 1]Voir le lien social[e]
[f 2 1]Ne rien faire[e]

[msg MSG_GENERAL_EXAMREWARD_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4029 0 0]Ah, [nl].[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]J'ai vu tes résultats. Beau travail.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Tiens, de la part du directeur.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4108 0 0]C'est ta récompense pour avoir su jongler entre études et, euh... "activités extrascolaires".[n][w][e]

[msg MND_GENERAL_EXAMREWARD_0]
[f 2 1]DEV: UNUSED LABEL[n][w][e]

[msg MND_GENERAL_EXAMREWARD_0_2]
[f 2 1]Comme j'ai fini 1er aux examens, j'ai aussi reçu : [f 4 4 1 37 1 3].[n][w][e]

[msg MSG_GENERAL_EXAMREWARD_0_2 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4029 0 0]Ah, [nl].[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]J'ai vu tes résultats. Beau travail.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Tiens, de la part du directeur.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4108 0 0]C'est ta récompense pour avoir su jongler entre études et, euh... "activités extrascolaires".[n][w][e]

[msg MSG_GENERAL_EXAMREWARD_0_3 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4077 0 0]Ah oui. Il y a autre chose...[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]J'ai vu tes résultats. Beau travail.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Tiens, de la part du directeur.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4131 0 0]C'est ta récompense pour avoir su jongler entre études et, euh... "activités extrascolaires".[n][w][e]

[msg MND_GENERAL_EXAMREWARD_0_3]
[f 2 1]Comme j'ai fini 1er aux examens, j'ai aussi reçu : [f 4 4 1 37 1 3].[n][w][e]

[msg MSG_GENERAL_EXAMREWARD_0_4 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4029 0 0]Ah, [nl].[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]J'ai vu tes résultats. Beau travail.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Tiens, de la part du directeur.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4108 0 0]C'est ta récompense pour avoir su jongler entre études et, euh... "activités extrascolaires".[n][w][e]

[msg MND_GENERAL_EXAMREWARD_0_4]
[f 2 1]DEV: UNUSED LABEL[n][w][e]

[msg MSG_GENERAL_EXAMREWARD_0_5 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4029 0 0]Ah, [nl].[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]J'ai vu tes résultats... Beau travail.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]La façon dont tu continues à réussir dans tes études tout en enchaînant les batailles est admirable.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0]Tiens, je t'ai apporté un cadeau pour te remercier de tes efforts.[n][w][e]

[msg MND_GENERAL_EXAMREWARD_0_5]
[f 2 1]未使用ラベルです。[n][w][e]

[msg MSG_GENERAL_EXAMREWARD_0_6 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 6 65535 0 0][vp 3 0 65535 4029 0 0]Ah, [nl].[n][w][e]
[f 2 1][bup 5 0 6 65535 0 0]J'ai vu tes résultats. Beau travail.[n][w][e]
[f 2 1][bup 5 0 6 65535 0 0]La façon dont tu continues à réussir dans tes études tout en enchaînant les batailles est admirable.[n][w][e]
[f 2 1][bup 5 0 6 65535 0 0]Tiens, je t'ai apporté un cadeau pour te remercier de tes efforts.[n][w][e]

[msg MND_GENERAL_EXAMREWARD_1]
[f 2 1]Comme j'ai fini 1er aux examens, j'ai aussi reçu : [f 4 4 1 37 1 3].[n][w][e]

[msg MSG_GENERAL_EXAMREWARD_1 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4029 0 0]Ah, [nl].[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]J'ai vu tes résultats. Beau travail.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]La façon dont tu continues à réussir dans tes études tout en enchaînant les batailles est admirable.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4108 0 0]Tiens, je t'ai apporté un cadeau pour te remercier de tes efforts.[n][w][e]

[msg MND_GENERAL_EXAMREWARD_1_2]
[f 2 1]DEV: UNUSED LABEL[n][w][e]

[msg MND_GENERAL_EXAMREWARD_1_3]
[f 2 1]Comme j'ai fini 1er aux examens, j'ai aussi reçu : [f 4 4 1 37 1 3].[n][w][e]

[msg MSG_042_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 155 65535 0 0]Oh, [nf]-chan. Do you want to go to the outdoor hot springs?[n][w][e]

[sel SEL_043_0_0 top]
[f 2 1]Sure, let's go.[e]
[f 2 1]I'll go in a bit.[e]

[msg MSG_044_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 155 65535 0 0]*giggle* I'm looking forward to it.[n][w][e]
[f 2 1][bup 6 0 155 65535 0 0][nf]-chan, you have to go back to your room and get ready first, right?[n][w][e]
[f 2 1][bup 6 0 155 65535 0 0]I'll talk to Kirijo-senpai and Yukari-chan about it while you're doing that.[n][w][e]
[f 2 1][bup 6 0 155 65535 0 0]I'll ask Aigis too, but... Is it all right for her to take a bath?[n][w][e]

[msg MSG_045_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 155 65535 0 0]You're not going to go yet?[n][w][e]
[f 2 1][bup 6 0 155 65535 0 0]Okay. Let me know when you're ready to go.[n][w][e]

[msg MSG_046_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 155 65535 0 0]*giggle* I'm looking forward to it.[n][w][e]

