[msg MSG_000_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]Ça me stresse un peu qu'on soit juste toutes les deux dans ma chambre comme ça...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 1 0][uf 3 1 0 0 0 2 0 0]......[n][uf 1 1][e]

[msg MSG_003_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]Hé, euh... vu que tu es là, on pourrait peut-être s'amuser un peu, toi et moi ?[n][uf 1 1][e]

[msg MSG_007_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 65535 65535 1 0][uf 3 1 1 0 0 4 0 0][uf 5 13 7 5 2]Euh, c-c'est pas ce que je voulais dire ! On pourrait, je sais pas... jouer aux cartes ou un truc du genre ![n][uf 1 1][e]

[msg MND_001_0_0 [Monologue intérieur]]
[uf 0 5 65278][uf 2 1]Je suis restée un bon moment avec Yukari.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Je ressens un lien indéfectible entre nous...[n][uf 1 1][e]

