[msg MSG_000_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]¿T-te... parece bien? ¿De verdad no te importa?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]Vaya, me alegra saber que estás dispuesta, pero...[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]¿Qué quieres decir?[e]
[uf 0 5 65278][uf 2 1]¿Has cambiado de opinión?[e]
[uf 0 5 65278][uf 2 1]Relájate un poco.[e]

[msg MSG_002_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]¡Ah! Eh... Mmm...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]N-no es nada...[n][uf 1 1][e]

[msg MSG_003_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]¡N-no! Lo que pasa es que... ha sido tan repentino...[n][uf 1 1][e]

[msg MSG_004_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]A-ah, ya... Hablar con otras personas no es que se me dé muy bien...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]En el consejo estudiantil hay muchas, así que debería empezar a acostumbrarme.[n][uf 1 1][e]

[msg MSG_005_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0][uf 3 1 1 0 0 8 0 0]¡Anda! Ya mismo cierran el instituto. Venga, vamos.[n][uf 1 1][e]

