[msg MSG_000_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]Vale... No creo que venga nadie hasta dentro de un buen rato.[n][uf 1 1][e]

[msg MSG_000_3_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]Me he aprovechado de mi puesto en el consejo estudiantil.[n][uf 1 1][e]

[msg MSG_000_1_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 65535 65535 0 0][uf 3 1 1 0 0 3 0 0][uf 4 23 0 1 3 25 25]Esta es la primera vez que uso mi autoridad por motivos personales.[n][uf 1 1][e]

[msg MSG_000_5_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 6 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]Bueno, eso da igual.[n][uf 1 1][e]

[msg MSG_000_7_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 65535 65535 0 0][uf 3 1 1 0 0 5 0 0][uf 4 23 0 1 3 25 25]No sé ni qué hago...[n][uf 1 1][e]

[msg MSG_001_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]Lo que quiero decir es que tenemos que hablar.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]Primero quiero disculparme.[n][uf 1 1][e]

[msg MSG_001_5_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 65535 65535 0 0][uf 3 1 1 0 0 8 0 0]Siento lo que pasó la última vez que nos vimos.[n][uf 1 1][e]

[sel SEL_002_0_0 top]
[uf 0 5 65278][uf 2 1]¿A qué te refieres?[e]
[uf 0 5 65278][uf 2 1]No te preocupes.[e]
[uf 0 5 65278][uf 2 1]Me hizo muy feliz.[e]

[msg MSG_003_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 4 65535 65535 1 0][uf 3 1 1 0 0 9 0 0]Ya sabes... El otro día, enfrente de la estación.[n][uf 1 1][e]

[msg MSG_003_5_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 10 0 0][uf 5 13 4 5 5]Ah, ya. Haces como que no te acuerdas para ahorrarme pasar vergüenza.[n][uf 1 1][e]

[msg MSG_003_7_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 65535 65535 1 0][uf 3 1 1 0 0 11 0 0][uf 4 23 0 1 3 25 25]No sé que me pasa...[n][uf 1 1][e]

[msg MSG_004_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 1 0][uf 3 1 1 0 0 12 0 0]Es muy amable de tu parte. Gracias.[n][uf 1 1][e]

[msg MSG_005_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]Lo que te dijo mi exprometido no tiene perdón, pero lo más importante es que...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 65535 65535 0 0][uf 3 1 1 0 0 14 0 0][uf 4 23 0 1 3 25 25]Quería disculparme por mi comportamiento.[n][uf 1 1][e]

[msg MSG_006_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 4 65535 65535 1 0][uf 3 1 0 0 0 15 0 0][uf 5 13 4 15 5]¡...![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 1 0][uf 3 1 1 0 0 16 0 0][uf 4 23 0 1 1 25 25]Ah, conque sí...[n][uf 1 1][e]

[msg MSG_007_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 65535 65535 0 0][uf 3 1 1 0 0 17 0 0]En aquel momento...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 65535 65535 0 0][uf 3 1 1 0 0 18 0 0]Dije un montón de cosas sobre ti y salí corriendo.[n][uf 1 1][e]

[msg MSG_007_3_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 65535 65535 0 0][uf 3 1 1 0 0 19 0 0]Fue muy desconsiderado por mi parte. Lo siento.[n][uf 1 1][e]

[msg MSG_007_5_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 65535 65535 0 0][uf 3 1 1 0 0 20 0 0]Llevaba tiempo queriendo decirte lo que siento...[n][uf 1 1][e]

[msg MSG_007_7_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 6 65535 65535 0 0][uf 3 1 1 0 0 21 0 0]Pero no me imaginaba que fuese a terminar gritándolo en público.[n][uf 1 1][e]

[sel SEL_008_0_0 top]
[uf 0 5 65278][uf 2 1]Qué atrevida.[e]
[uf 0 5 65278][uf 2 1]¿Lo que sientes?[e]

[msg MSG_009_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 1 0][uf 3 1 1 0 0 22 0 0]Oye, no te rías de mí. Yo tampoco me creía capaz.[n][uf 1 1][e]

[msg MSG_009_5_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 65535 65535 0 0][uf 3 1 1 0 0 23 0 0]Desde que empecé a quedar contigo, mi vida se ha llenado de nuevas experiencias.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 65535 65535 0 0][uf 3 1 1 0 0 24 0 0]Me he sentido conmovida, alegre y hasta furiosa, pero nunca he dejado de pensar en ti.[n][uf 1 1][e]

[msg MSG_010_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 4 65535 65535 1 0][uf 3 1 1 0 0 25 0 0]¡¿Qué?! A ver, es que...[n][uf 1 1][e]

[msg MSG_010_5_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 65535 65535 0 0][uf 3 1 1 0 0 26 0 0]Desde que empecé a quedar contigo, mi vida se ha llenado de nuevas experiencias.[n][uf 1 1][e]

[msg MSG_010_7_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 65535 65535 0 0][uf 3 1 1 0 0 27 0 0]Me he sentido conmovida, alegre y hasta furiosa, pero nunca he dejado de pensar en ti.[n][uf 1 1][e]

[msg MSG_011_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 65535 65535 0 0][uf 3 1 0 0 0 28 0 0]...[n][uf 1 1][e]

[msg MSG_011_5_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 29 0 0][uf 4 23 0 1 0 25 25]Ahora que hemos llegado a este punto, me veo obligada a decirte lo que siento.[n][uf 1 1][e]

[msg MSG_012_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 1 0][uf 3 1 1 0 0 30 0 0]Allá va. Te...[n][uf 1 1][e]

[msg MSG_013_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 1 0][uf 3 1 1 0 0 31 0 0]Te quiero...[n][uf 1 1][e]

[msg MSG_013_5_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 65535 65535 1 0][uf 3 1 0 0 0 32 0 0][uf 4 23 0 1 3 25 25]...[n][uf 1 1][e]

[msg MND_014_0_0]
[uf 0 5 65278][uf 2 1]A Mitsuru le tiembla la voz. Debería tener mucho cuidado con lo que digo.[n][uf 1 1][e]

[msg MND_015_0_0]
[uf 0 5 65278][uf 2 1]Ahora que lo pienso, [uf 0 1 2]ya tengo una relación especial[uf 0 1 27][n][uf 0 1 2]con otra persona[uf 0 1 27]...[n][uf 1 1][e]

[msg MSG_015_5_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 65535 65535 1 0][uf 3 1 1 0 0 33 0 0]Siento que me voy a morir de la vergüenza.[n][uf 1 1][e]

[sel SEL_016_0_0 top]
[uf 0 5 65278][uf 2 1]Yo también te quiero.[uf 2 9 1 1 349][e]
[uf 0 5 65278][uf 2 1]Lo siento, pero...[e]

[msg MSG_017_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 4 65535 65535 0 0][uf 3 1 0 0 0 34 0 0]¡...![n][uf 1 1][e]

[msg MSG_017_1_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 1 0][uf 3 1 1 0 0 35 0 0]¿Que t-tú también me quieres?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 65535 65535 1 0][uf 3 1 0 0 0 36 0 0][uf 4 23 0 1 3 25 25]...[n][uf 1 1][e]

[msg MSG_017_3_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 1 0][uf 3 1 1 0 0 37 0 0]Me alegro mucho o, bueno, ¿debería decir que me siento agradecida?[n][uf 1 1][e]

[msg MSG_017_4_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 65535 65535 1 0][uf 3 1 1 0 0 38 0 0][uf 4 23 0 1 3 25 25]Ay, mi corazón... A este paso, voy a terminar como la última vez.[n][uf 1 1][e]

[msg MSG_017_5_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 1 0][uf 3 1 1 0 0 39 0 0]Aunque es maravilloso saber que el sentimiento es mutuo.[n][uf 1 1][e]

[msg MSG_018_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 40 0 0]Je, me alegro de haber abierto mi corazón. A partir de hoy, eres más que una amiga para mí.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 0 41 0 0][uf 4 23 0 1 1 25 25]Dicho esto, y dada mi situación, todavía no puedo hacerlo público.[n][uf 1 1][e]

[msg MND_019_0_0]
[uf 0 5 65278][uf 2 1]Percibo el profundo afecto que me profesa Mitsuru.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Parece que la cosa va en serio.[n][uf 1 1][e]

[msg MND_020_0_0]
[uf 0 5 65278][uf 2 1]Ya no hay marcha atrás.[n][uf 1 1][e]

[msg MSG_021_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 1 0][uf 3 1 1 0 0 42 0 0]Oye, [uf 4 1]...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 1 0][uf 3 1 1 0 0 43 0 0]Llevo un tiempo reflexionando sobre el tema, pero la forma en la que te diriges a mí...[n][uf 1 1][e]

[sel SEL_022_0_0 top]
[uf 0 5 65278][uf 2 1]¿"Mitsuru"?[e]
[uf 0 5 65278][uf 2 1]¿Qué le pasa?[e]

[msg MSG_023_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 1 0][uf 3 1 1 0 0 44 0 0]A eso precisamente me refería.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 65535 65535 1 0][uf 3 1 1 0 0 45 0 0][uf 4 23 0 1 3 25 25]Me tratas como si me conocieras de toda la vida y yo soy mucho más formal. Es un poco raro.[n][uf 1 1][e]

[msg MSG_024_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 4 65535 65535 1 0][uf 3 1 1 0 0 46 0 0]No hagas como si no supieras de lo que estoy hablando.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 1 0][uf 3 1 1 0 0 47 0 0][uf 4 23 0 1 0 25 25]Me tratas como si me conocieras de toda la vida y yo soy mucho más formal. Es un poco raro.[n][uf 1 1][e]

[msg MSG_025_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 1 0][uf 3 1 1 0 0 48 0 0]Vale, decidido.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 1 0][uf 3 1 1 0 0 49 0 0]A partir de ahora, cuando estemos solos, se acabaron las formalidades.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 1 0][uf 3 1 1 0 0 50 0 0]Me costará acostumbrarme, pero es lo que quiero.[n][uf 1 1][e]

[msg MSG_025_5_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 51 0 0]Hoy comienza una nueva etapa. No permitiré que el legado de mi familia me oprima.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 52 0 0]Te conocí gracias a quien soy como persona.[n][uf 1 1][e]

[msg MSG_026_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 1 0][uf 3 1 1 0 0 53 0 0]Ay, mira lo que me haces decir. ¡Espero que asumas la responsabilidad![n][uf 1 1][e]

[msg MSG_027_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 0 54 0 0]Ah, [uf 4 2]... Bueno, es un comienzo.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 1 0][uf 3 1 1 0 0 55 0 0]No me sueltes todavía...[n][uf 1 1][e]

[msg MND_028_0_0]
[uf 0 5 65278][uf 2 1]Hemos pasado un rato más juntas y luego hemos vuelto a la residencia.[n][uf 1 1][e]

[msg MSG_029_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 56 0 0]Vaya...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 0 57 0 0][uf 4 23 0 1 1 25 25]Qué pena, pero me alegro de haber aclarado las cosas.[n][uf 1 1][e]

[msg MSG_030_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 58 0 0]Me dijiste que controlar mis emociones dependía de mí. Gracias a eso, he podido ser sincera conmigo misma.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 59 0 0]De haber seguido tragándome mis sentimientos, jamás habría avanzado.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 0 60 0 0][uf 4 23 0 1 1 25 25]Es fundamental que seamos sinceros con nosotros mismos, igual que tú al responderme.[n][uf 1 1][e]

[msg MSG_030_5_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 61 0 0]Gracias, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 62 0 0]De no haber albergado estas emociones, habría continuado mintiéndome a mí misma y achacándolo todo a mi apellido.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 63 0 0]De ser así, mi futuro habría sido un fracaso.[n][uf 1 1][e]

[msg MSG_031_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 0 64 0 0]A partir de ahora, no permitiré que el legado de mi familia me oprima.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 0 65 0 0]Te conocí gracias a quien soy como persona.[n][uf 1 1][e]

[msg MND_031_2_0]
[uf 0 5 65278][uf 2 1]Percibo la profunda confianza de Mitsuru.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Siento que nuestra relación se ha fortalecido.[n][uf 1 1][e]

[msg MSG_031_5_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 66 0 0]Tengo mucho por lo que darte las gracias, pero hay otro asunto del que me gustaría hablar.[n][uf 1 1][e]

[msg MSG_032_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 0 67 0 0]Estoy famélica, no he comido nada desde esta mañana. Y tú tienes parte de culpa.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 0 68 0 0]Me apetece comer takoyaki de camino a casa. ¿Me invitas?[n][uf 1 1][e]

[msg MSG_032_5_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 0 69 0 0]Qué menos que eso para reparar un corazón roto...[n][uf 1 1][e]

[msg MND_033_0_0]
[uf 0 5 65278][uf 2 1]Hemos pasado por la zona de tiendas y luego hemos vuelto a la residencia.[n][uf 1 1][e]

