[msg MSG_000_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 3 0 65535 11093 0 0]Por fin hemos sacado tiempo para pasarlo juntas en vez de conformarnos con saludos apresurados entre clases.[n][uf 1 1][e]

[msg MSG_001_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0]Qué ropa tan chula, [uf 4 1]. Tienes muy buen gusto.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 0 0][uf 4 23 0 106 3 25 25]Y no como Kaz, que va con el chándal a todas partes. Es vergonzoso, la verdad. Hay que llevar ropa que no sea del instituto.[n][uf 1 1][e]

[msg MSG_002_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 3 0 65535 11007 0 0]Mírame a mí, sin ir más lejos. ¿Qué te parece mi ropa?[n][uf 1 1][e]

[sel SEL_003_0_0 top]
[uf 0 5 65278][uf 2 1]Te hace mona.[e]
[uf 0 5 65278][uf 2 1]Pareces más madura.[e]
[uf 0 5 65278][uf 2 1]Te hace muy sofisticada.[e]

[msg MSG_004_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 3 0 65535 11054 0 0][uf 5 13 12 15 106]¿Que me hace mona?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0]Serán cosas mías, pero que te llamen "mona" resulta un poco condescendiente.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 4 23 0 106 1 25 25]Sé que tú no lo dices con esa intención, así que me lo tomaré como un cumplido.[n][uf 1 1][e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]Yuko parece avergonzada.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Hoy he aprendido un poco más sobre ella.[n][uf 1 1][e]

[msg MSG_006_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 2 65535 65535 0 0][uf 3 1 3 0 65535 11052 0 0]Espera, ¿de qué demonios va esto, [uf 4 1]?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 2 65535 65535 0 0]¿Te parezco una abuela o qué? Caray, cualquiera diría que llevo un traje pantalón. Y que madura, me dice la chica...[n][uf 1 1][e]

[msg MND_007_0_0]
[uf 0 5 65278][uf 2 1]Yuko parece molesta.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Siento que hoy nuestra relación no ha cambiado nada...[n][uf 1 1][e]

[msg MSG_008_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 4 65535 65535 0 0][uf 3 1 3 0 65535 11075 0 0][uf 5 13 12 30 106]¿De verdad? ¿Lo dices en serio?[n][uf 1 1][e]

[msg MSG_009_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 4 65535 65535 0 0]A ver, no voy a decirte que estás equivocada ni nada, pero...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 4 23 0 106 1 25 25]Supongo que no suelo rodearme con gente que se da cumplidos de improviso... ¡Gracias![n][uf 1 1][e]

[msg MND_010_0_0]
[uf 0 5 65278][uf 2 1]Yuko parece muy contenta.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Siento que hoy nuestra relación se ha estrechado.[n][uf 1 1][e]

[msg MSG_011_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 3 0 65535 11067 0 0]Sigamos paseando y busquemos algo para comer, pero que no sea takoyaki.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0]No hay nada que desluzca más un traje que tener un trozo de alga metido entre los dientes.[n][uf 1 1][e]

[msg MND_012_0_0]
[uf 0 5 65278][uf 2 1]Hemos estado un rato más juntas hasta que cada uno ha ido por su camino.[n][uf 1 1][e]

