[sel SEL_TALK top]
[uf 0 5 65278][uf 2 1]Vayamos juntos.[e]
[uf 0 5 65278][uf 2 1]Mantente a la espera por ahora.[e]
[uf 0 5 65278][uf 2 1]Deja que me lo piense...[e]

[sel SEL_BACK_UP_00 top]
[uf 0 5 65278][uf 2 1]Consultar progreso[e]
[uf 0 5 65278][uf 2 1]Da igual[e]

[sel SEL_PARTY top]
[uf 0 5 65278][uf 2 1]Yukari[e]
[uf 0 5 65278][uf 2 1]Aigis[e]
[uf 0 5 65278][uf 2 1]Mitsuru[e]
[uf 0 5 65278][uf 2 1]Junpei[e]
[uf 0 5 65278][uf 2 1]Sanada[e]
[uf 0 5 65278][uf 2 1]Amada[e]
[uf 0 5 65278][uf 2 1]Aragaki[e]
[uf 0 5 65278][uf 2 1]Koromaru[e]
[uf 0 5 65278][uf 2 1]Mantente a la espera por ahora.[e]

[sel SEL_DOOR top]
[uf 0 5 65278][uf 2 1]Introducir[e]
[uf 0 5 65278][uf 2 1]No entrar[e]

[sel SEL_BACK_UP_01 top]
[uf 0 5 65278][uf 2 1]Consultar el estado de todos[e]
[uf 0 5 65278][uf 2 1]Da igual[e]

[sel SEL_BACK_UP_02 top]
[uf 0 5 65278][uf 2 1]Preguntar por el objetivo[e]
[uf 0 5 65278][uf 2 1]Da igual[e]

[sel SEL_BACK_UP_03 top]
[uf 0 5 65278][uf 2 1]Consultar el estado de todos[e]
[uf 0 5 65278][uf 2 1]Ir al Escapade[e]
[uf 0 5 65278][uf 2 1]Un momento[e]

[sel SEL_BACK_UP_04 top]
[uf 0 5 65278][uf 2 1]Consultar el estado de todos[e]
[uf 0 5 65278][uf 2 1]Dirigirse a la estación[e]
[uf 0 5 65278][uf 2 1]Un momento[e]

[sel SEL_BACK_UP_05 top]
[uf 0 5 65278][uf 2 1]Consultar el estado de todos[e]
[uf 0 5 65278][uf 2 1]Comenzar la operación[e]
[uf 0 5 65278][uf 2 1]Un momento[e]

[msg MSG_AMADA_PARTY_IN_00 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]Llévame contigo a la exploración de esta noche.[n][uf 1 1][e]

[msg MSG_AMADA_PARTY_IN_AFTER [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0]¡Vale! ¡Me esforzaré al máximo![n][uf 1 1][e]

[msg MSG_AMADA_PARTY_OUT_00 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]Nos vamos cuando digas.[n][uf 1 1][e]

[msg MSG_AMADA_PARTY_OUT_AFTE [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]Vale...[n][uf 1 1][e]

[msg MSG_AMADA_PARTY_OVER_00 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]Em, parece que el grupo ya está lleno.[n][uf 1 1][e]

[msg MSG_AMADA_PARTY_CHANGE_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]¿Con quién me cambio?[n][uf 1 1][e]

[msg MSG_AMADA_PARTY_OVER_01 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]Vaya, parece que no hay ni un hueco libre.[n][uf 1 1][e]

[msg MSG_AMADA_PARTY_IN_AFTER_2 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]¡Lo intentaré![n][uf 1 1][e]

[msg MSG_AMADA_PARTY_IN_AFTER_3 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]Vale, entendido.[n][uf 1 1][e]

[msg MSG_AMADA_PARTY_OUT_01 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7008 0 0]Deberíamos ir tirando, ¿no?[n][uf 1 1][e]

[msg MSG_AMADA_PARTY_OUT_AFTE_2 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]Vale, lo entiendo...[n][uf 1 1][e]

[msg MSG_AMADA_PARTY_IN_01 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 65535 65535 0 0][uf 3 1 3 0 65535 7094 0 0]¡No dejaré que nadie se interponga en nuestro camino! ¡Tenemos que seguir adelante![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 65535 65535 0 0]¡Todo listo...![n][uf 1 1][e]

[msg MSG_AMADA_PARTY_OUT_02 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 65535 65535 0 0][uf 3 1 3 0 65535 7090 0 0]Seguro que ahora son más fuertes que la última vez.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 65535 65535 0 0]¡Pero nosotros también! Solo tenemos que...[n][uf 1 1][e]

[msg MSG_AMADA_PARTY_IN_02 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]¿Por qué iba a...?[n][uf 1 1][e]

[msg MSG_AMADA_PARTY_OUT_03 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]Hay que seguir avanzando. Debemos enfrentarnos a Nix.[n][uf 1 1][e]

[msg MSG_AMADA_PARTY_IN_03 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 65535 65535 0 0][uf 3 1 3 0 65535 7129 0 0]Acabemos esto de una vez por todas...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 65535 65535 0 0]¡Deja que luche![n][uf 1 1][e]

[msg MSG_AMADA_PARTY_OUT_04 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 65535 65535 0 0][uf 3 1 3 0 65535 7094 0 0]No podemos perder... Le dije que iría a por él.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 65535 65535 0 0]¡Así que no permitiré que Strega ni nadie me detenga! ¡Vamos![n][uf 1 1][e]

[msg MSG_AMADA_PARTY_IN_04 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 65535 65535 0 0][uf 3 1 3 0 65535 7090 0 0]A lo mejor, en cierto modo, me parezco más de lo que creía a estos tipos...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 65535 65535 0 0]Pero eso ahora no importa. ¡Vamos![n][uf 1 1][e]

[msg MSG_AMADA_PARTY_OUT_05 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 3 0 65535 7132 0 0]No te preocupes, miro hacia el futuro.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0]Vámonos.[n][uf 1 1][e]

[msg MSG_AMADA_PARTY_IN_05 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]Sinceramente... te mentiría si dijera que no estoy preocupado...[n][uf 1 1][e]

[msg MSG_AMADA_PARTY_IN_AFTER_4 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]Muy bien.[n][uf 1 1][e]

[msg MSG_AMADA_PARTY_OUT_06 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]Acabemos con esto.[n][uf 1 1][e]

[msg MSG_AMADA_PARTY_CHANGE_0_2 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]¿A quién sustituyo?[n][uf 1 1][e]

[msg MSG_AMADA_PARTY_IN_06 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 65535 65535 0 0][uf 3 1 3 0 65535 7129 0 0]Y ahora están aquí también... ¡No pienso dejar que se interpongan en nuestro camino![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 65535 65535 0 0]¡Dejadme ir con vosotros![n][uf 1 1][e]

[msg MSG_AMADA_PARTY_IN_07 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 65535 65535 0 0][uf 3 1 3 0 65535 7129 0 0]Me preocupa Junpei. Deberíamos ir tras él cuanto antes.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 65535 65535 0 0]¡Dime si puedo hacer algo para ayudarte![n][uf 1 1][e]

[msg MSG_AMADA_PARTY_IN_08 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7063 0 0]¿Dónde habrá ido Junpei?[n][uf 1 1][e]

[msg MSG_AMADA_PARTY_IN_09 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 65535 65535 0 0][uf 3 1 3 0 65535 7090 0 0]Han pasado muchas cosas, pero...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 65535 65535 0 0]¡Por eso tenemos que ponerle fin a esto! ¡Sé que podemos![n][uf 1 1][e]

[msg MSG_AMADA_PARTY_IN_AFTER_5 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 65535 65535 0 0]Ganaremos, cueste lo que cueste.[n][uf 1 1][e]

[msg MSG_AMADA_PARTY_OUT_07 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 65535 65535 0 0][uf 3 1 3 0 65535 7094 0 0]Tenemos que detenerlos...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 65535 65535 0 0]Puedo ir cuando digas.[n][uf 1 1][e]

[msg MSG_AMADA_PARTY_CHANGE_0_3 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]¿Con quién me cambio?[n][uf 1 1][e]

[msg MSG_AMADA_PARTY_OUT_TKJI [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 65535 65535 0 0][uf 3 1 3 0 65535 7129 0 0]Puedo hacerlo.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]¿Qué vas a hacer?[n][uf 1 1][e]

[msg MSG_AMADA_PARTY_OUT_CHID [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 65535 65535 0 0][uf 3 1 3 0 65535 7129 0 0]Deberíamos ir tras Junpei cuanto antes.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 65535 65535 0 0]Puedo ir cuando digas.[n][uf 1 1][e]

[msg MSG_0828_0902_AMADA_DUNG [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7001 0 0]No te preocupes por mí. La torre Tártaro no me asusta en absoluto.[n][uf 1 1][e]

[msg MSG_0903_0904_AMADA_DUNG [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7001 0 0]He oído que Aragaki luchaba con Sanada y Mitsuru.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]Parece fuerte, sí, pero no lo tengo muy claro.[n][uf 1 1][e]

[msg MSG_0919_1003_AMADA_DUNG [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7008 0 0]Cuando derrotemos a las tres últimas sombras, se acabó, ¿no?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]La Hora Oscura, los Perdidos, la torre Tártaro...[n][uf 1 1][e]

[msg MSG_1005_1016_AMADA_DUNG [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7026 0 0]Ya estoy bien.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]Todavía puedo luchar, así que no te preocupes.[n][uf 1 1][e]

[msg MSG_1019_1102_AMADA_DUNG [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 65535 65535 0 0][uf 3 1 3 0 65535 7094 0 0]Decidí que lucharía en su lugar...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 65535 65535 0 0]Por eso acabaré con todas las sombras, las de aquí y hasta la última de ellas.[n][uf 1 1][e]

[msg MSG_1106_1109_AMADA_DUNG [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 65535 65535 0 0][uf 3 1 3 0 65535 7090 0 0]Los adultos irresponsables hacen lo que quieren y nos dejan los problemas a los demás.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 65535 65535 0 0]La torre Tártaro es el ejemplo perfecto.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 65535 65535 0 0]No me gustaría acabar siendo un adulto de esos.[n][uf 1 1][e]

[msg MSG_1110_1117_AMADA_DUNG [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 65535 65535 0 0][uf 3 1 3 0 65535 7090 0 0]¿Estará bien Mitsuru?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 65535 65535 0 0]¿Y el resto? Parece que no sabemos muy bien qué hacer, ¿no?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]Bueno, haremos lo que podamos.[n][uf 1 1][e]

[msg MSG_1121_AMADA_DUNGE [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 3 0 65535 7096 0 0]Noto cambiada a Mitsuru.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0]Ahora es más positiva que antes.[n][uf 1 1][e]

[msg MSG_1122_1127_AMADA_DUNG [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7008 0 0]Junpei apenas ha comido desde... entonces.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]Entiendo cómo se siente, pero... me preocupa.[n][uf 1 1][e]

[msg MSG_1203_1213_AMADA_DUNG [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 65535 65535 0 0][uf 3 1 3 0 65535 7090 0 0]El fin del mundo, una muerte inevitable...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 65535 65535 0 0]Quizá seríamos más felices si no supiéramos nada.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 65535 65535 0 0][uf 4 25 8]...[n][uf 1 1][e]

[msg MSG_0101_0114_AMADA_DUNG [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 3 0 65535 7132 0 0]Sé lo que voy a hacer y no pienso dejar que nada me distraiga.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0]Lucharé con todas mis fuerzas.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0]Así es como me mantengo motivado para las contiendas de la torre Tártaro.[n][uf 1 1][e]

[msg MSG_0115_0130_AMADA_DUNG [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7026 0 0]Nunca me había planteado qué quería hacer o ser en el futuro.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]Pero, últimamente, no paro de darle vueltas.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 65535 65535 0 0]Tenemos que acabar con Nix, está claro.[n][uf 1 1][e]

[msg MSG_0131_AMADA_DUNGE [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7145 0 0]La batalla de hoy lo decidirá todo, nuestro futuro... e incluso el de todo el planeta.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]Estoy un poco nervioso, pero... no estoy preocupado. Es una sensación extraña.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0]Sé que podemos ganar.[n][uf 1 1][e]

[msg MSG_HANYOU1_AMADA_DUNGE [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7063 0 0]Luchar en la torre Tártaro es de lo más extenuante...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]Ah, pero estoy bien. Soy más fuerte de lo que aparento.[n][uf 1 1][e]

[msg MSG_HANYOU2_AMADA_DUNGE [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7001 0 0]La torre Tártaro puede variar muchísimo de un piso a otro.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]Hay algunos que dan miedo, pero luego hay otros muy ostentosos...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]Es muy raro.[n][uf 1 1][e]

[msg MSG_AMADA_ZEKKOCHO [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 3 0 65535 7132 0 0]¡Hoy déjalo todo en mis manos! ¡Las sombras no tendrán nada que hacer![n][uf 1 1][e]

