[sel SEL_TALK top]
[uf 0 5 65278][uf 2 1]Vayamos juntas.[e]
[uf 0 5 65278][uf 2 1]Mantente a la espera por ahora.[e]
[uf 0 5 65278][uf 2 1]Deja que me lo piense...[e]

[sel SEL_BACK_UP_00 top]
[uf 0 5 65278][uf 2 1]Consultar progreso[e]
[uf 0 5 65278][uf 2 1]Da igual[e]

[sel SEL_PARTY top]
[uf 0 5 65278][uf 2 1]Yukari[e]
[uf 0 5 65278][uf 2 1]Aigis[e]
[uf 0 5 65278][uf 2 1]Mitsuru[e]
[uf 0 5 65278][uf 2 1]Junpei[e]
[uf 0 5 65278][uf 2 1]Sanada[e]
[uf 0 5 65278][uf 2 1]Amada[e]
[uf 0 5 65278][uf 2 1]Aragaki[e]
[uf 0 5 65278][uf 2 1]Koromaru[e]
[uf 0 5 65278][uf 2 1]Mantente a la espera por ahora.[e]

[sel SEL_DOOR top]
[uf 0 5 65278][uf 2 1]Introducir[e]
[uf 0 5 65278][uf 2 1]No entrar[e]

[sel SEL_BACK_UP_01 top]
[uf 0 5 65278][uf 2 1]Consultar el estado de todos[e]
[uf 0 5 65278][uf 2 1]Da igual[e]

[sel SEL_BACK_UP_02 top]
[uf 0 5 65278][uf 2 1]Preguntar por el objetivo[e]
[uf 0 5 65278][uf 2 1]Da igual[e]

[sel SEL_BACK_UP_03 top]
[uf 0 5 65278][uf 2 1]Consultar el estado de todos[e]
[uf 0 5 65278][uf 2 1]Ir al Escapade[e]
[uf 0 5 65278][uf 2 1]Un momento[e]

[sel SEL_BACK_UP_04 top]
[uf 0 5 65278][uf 2 1]Consultar el estado de todos[e]
[uf 0 5 65278][uf 2 1]Dirigirse a la estación[e]
[uf 0 5 65278][uf 2 1]Un momento[e]

[sel SEL_BACK_UP_05 top]
[uf 0 5 65278][uf 2 1]Consultar el estado de todos[e]
[uf 0 5 65278][uf 2 1]Comenzar la operación[e]
[uf 0 5 65278][uf 2 1]Un momento[e]

[msg MSG_MITSURU_PARTY_IN_00 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]¿Quieres que te acompañe?[n][uf 1 1][e]

[msg MSG_MITSURU_PARTY_IN_AFT [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]No te decepcionaré.[n][uf 1 1][e]

[msg MSG_MITSURU_PARTY_OUT_00 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Bueno, allá vamos.[n][uf 1 1][e]

[msg MSG_MITSURU_PARTY_OUT_AF [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Entiendo...[n][uf 1 1][e]

[msg MSG_MITSURU_PARTY_OVER_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]No hay hueco en el grupo.[n][uf 1 1][e]

[msg MSG_MITSURU_PARTY_CHANGE [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]¿Con quién me cambio?[n][uf 1 1][e]

[msg MSG_MITSURU_PARTY_IN_AFT_2 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Muy bien.[n][uf 1 1][e]

[msg MSG_MITSURU_PARTY_IN_AFT_3 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Muy bien, vamos.[n][uf 1 1][e]

[msg MSG_MITSURU_PARTY_OVER_0_2 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Hay demasiados miembros en la vanguardia.[n][uf 1 1][e]

[msg MSG_MITSURU_PARTY_CHANGE_2 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]¿Con quién me cambio?[n][uf 1 1][e]

[msg MSG_MITSURU_PARTY_OUT_AF_2 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Muy bien. Ten cuidado.[n][uf 1 1][e]

[msg MSG_MITSURU_PARTY_OUT_01 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4061 0 0]Tenemos poco tiempo. Deprisa.[n][uf 1 1][e]

[msg MSG_MITSURU_TUTORIAL_BEF [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4094 0 0]No te preocupes, no voy a pedirte imposibles.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Te las apañarás.[n][uf 1 1][e]

[msg MSG_MITSURU_TUTORIAL_AFT [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4085 0 0]A partir de ahora, podrás seleccionar a los miembros del grupo que te acompañarán a explorar la torre Tártaro.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Te explicaré los detalles en otro momento.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]¡Très bien! Hoy lo has hecho genial. Hora de volver a la residencia.[n][uf 1 1][e]

[msg MSG_MITSURU_THEURGIA_BEF [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4131 0 0]Por fin puedo luchar a tu lado.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Y, además, tenemos nuevos atuendos y equipamiento de combate. Espero que confíes en mí...[n][uf 1 1][e]

[msg MSG_MITSURU_BACK_UP [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Me quedaré aquí para brindarte apoyo. ¿Hay algo más que pueda hacer por ti?[n][uf 1 1][e]

[msg MSG_MITSURU_BACK_UP_RE [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]¿Algo más?[n][uf 1 1][e]

[msg MSG_MITSURU_ANALYSIS [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Lo más lejos que has llegado es el piso [uf 2 4 1].[n][uf 1 1][e]

[msg MSG_MITSURU_ANALYSIS_GO [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Hay que explorar la torre Tártaro todo lo que sea posible.[n][uf 1 1][e]

[msg MSG_MITSURU_ANALYSIS_STO [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Parece que hemos llegado hasta donde podíamos. Misión cumplida, al menos por ahora.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Buen trabajo.[n][uf 1 1][e]

[msg MSG_MITSURU_PARTY_CHANGE_3 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]¿A quién quieres que reemplace...?[n][uf 1 1][e]

[msg MSG_MITSURU_PARTY_IN_01 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4094 0 0]Nos lo jugamos todo en este combate. Seguro que a él le pasa lo mismo.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Por eso... no podemos permitirnos perder, aquí no.[n][uf 1 1][e]

[msg MSG_MITSURU_PARTY_OUT_02 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4001 0 0]No hay tiempo para deliberar.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Preparaos para luchar y dejad de lado este tema.[n][uf 1 1][e]

[msg MSG_MITSURU_PARTY_IN_02 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Nada de compadecerse... Es un insulto a los caídos.[n][uf 1 1][e]

[msg MSG_MITSURU_PARTY_OUT_03 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]No es momento de arrepentirse.[n][uf 1 1][e]

[msg MSG_MITSURU_PARTY_IN_03 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 5 65535 65535 0 0][uf 3 1 3 0 65535 4127 0 0]El Grupo Kirijo... No podemos esperar que expíe sus pecados.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 65535 65535 0 0]Pero eso no significa que vayamos a dejar de intentarlo. Por la esperanza y los sueños depositados en nosotros, debemos seguir esforzándonos.[n][uf 1 1][e]

[msg MSG_MITSURU_PARTY_OUT_04 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4085 0 0]Vamos. Aún nos queda mucho para llegar a nuestro objetivo.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]¿Qué...? Lo tengo todo listo.[n][uf 1 1][e]

[msg MSG_MITSURU_PARTY_IN_04 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4094 0 0]Hemos avanzado mucho.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]No lo habríamos conseguido sin todos vosotros. No sé cómo agradecéroslo.[n][uf 1 1][e]

[msg MSG_MITSURU_PARTY_OUT_05 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4140 0 0]Vamos. Hora de recuperar nuestro futuro.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Lo tengo todo listo para luchar.[n][uf 1 1][e]

[msg MSG_MITSURU_PARTY_IN_05 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Siento que tengas que pasar por esto...[n][uf 1 1][e]

[msg MSG_MITSURU_PARTY_IN_AFT_4 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Muy bien.[n][uf 1 1][e]

[msg MSG_MITSURU_PARTY_OUT_06 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Todo se acabará después de esto.[n][uf 1 1][e]

[msg MSG_MITSURU_PARTY_OVER_0_3 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Hay demasiada gente en el grupo...[n][uf 1 1][e]

[msg MSG_MITSURU_PARTY_CHANGE_4 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]¿Con quién me cambio...?[n][uf 1 1][e]

[msg MSG_MITSURU_PARTY_IN_06 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4094 0 0]Ya nos preocuparemos de escapar más tarde. Ahora nuestra prioridad es acabar con las sombras.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]¿Prefieres que vaya yo?[n][uf 1 1][e]

[msg MSG_MITSURU_PARTY_OUT_07 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4061 0 0]Qué giro de los acontecimientos tan inesperado... Pero nuestra prioridad sigue siendo destruir al objetivo.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Saldremos en cuanto estés lista.[n][uf 1 1][e]

[msg MSG_MITSURU_PARTY_IN_07 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4094 0 0]No te distraigas por los alrededores. Céntrate en tu objetivo.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Hemos venido a derrotar sombras.[n][uf 1 1][e]

[msg MSG_MITSURU_PARTY_IN_08 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4094 0 0]Todo llegará a su fin esta noche.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]¿Quieres que vaya contigo?[n][uf 1 1][e]

[msg MSG_1103_MITURU_01 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Bueno, vámonos.[n][uf 1 1][e]

[msg MSG_1103_IKUTUKI_01 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0]Muy bien, ten cuidado.[n][uf 1 1][e]

[msg MSG_1103_MITURU_02 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]¡Vamos![n][uf 1 1][e]

[msg MSG_MITSURU_PARTY_IN_09 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4094 0 0]Tenemos que ir tras Iori cuanto antes. Ya nos preocuparemos después de los efectos colaterales.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Si hay que luchar..., ¿necesitas que me una al grupo?[n][uf 1 1][e]

[msg MSG_MITSURU_PARTY_IN_10 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4061 0 0]Me sorprende que esa sombra se hiciera con los cables subterráneos...[n][uf 1 1][e]

[msg MSG_MITSURU_PARTY_IN_11 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4061 0 0]No podemos permitirnos el lujo de preocuparnos por los que no están.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Concéntrate en el enemigo que tenemos enfrente.[n][uf 1 1][e]

[msg MSG_MITSURU_PARTY_OUT_08 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4061 0 0]No se sabe cuándo se irá de madre la cosa.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Acabaremos con ellos con nuestro grupo actual. Empezaremos en cuanto estés lista.[n][uf 1 1][e]

[msg MSG_MITSURU_PARTY_OUT_AF_3 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Entiendo... Ten cuidado.[n][uf 1 1][e]

[msg MSG_MITSURU_PARTY_IN_12 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4094 0 0]Estoy muy agradecida con vosotros, de todo corazón. Gracias por manteneros firmes de principio a fin.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Lucharé lo mejor que pueda.[n][uf 1 1][e]

[msg MSG_MITSURU_PARTY_OUT_09 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4088 0 0]Ha sido una travesía muy larga para llegar hasta aquí.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Y todo acaba hoy. Vamos allá.[n][uf 1 1][e]

[msg MSG_MITSURU_PARTY_OUT_AF_4 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Ten cuidado...[n][uf 1 1][e]

[msg MSG_MITSURU_PARTY_CHANGE_5 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]¿Con quién me cambio?[n][uf 1 1][e]

[msg MSG_MITSURU_PARTY_OUT_TK [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4088 0 0]Se avecina un combate duro.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Pero estoy lista para aguantar hasta el final.[n][uf 1 1][e]

[msg MSG_MITSURU_PARTY_OUT_CH [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4088 0 0]Es demasiado peligroso que Iori esté solo ahora mismo.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Tenemos que salir cuanto antes.[n][uf 1 1][e]

[msg MSG_0425_0508_MITURU_DUN [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4001 0 0]¿Ya te has hecho a luchar contra las sombras? Bueno, sea como sea, no te sientas presionada.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Tengo muchas esperanzas puestas en ti. No me cabe duda de que estás a la altura.[n][uf 1 1][e]

[msg MSG_0510_0514_MITURU_DUN [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4094 0 0]Seguimos todos aquí gracias a ti y a tu rápida reacción en el monorraíl.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Viendo tu destreza para actuar ante sucesos inesperados...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Igual estás hecha para ser líder, y no una usuaria de Persona más.[n][uf 1 1][e]

[msg MSG_0523_MITURU_DUNGE [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4085 0 0]Como Akihiko ya está recuperado, ahora podemos tener cuatro miembros en la vanguardia.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Podrás poner a prueba diferentes estrategias de combate. Dales un tiento.[n][uf 1 1][e]

[msg MSG_0602_0605_MITURU_DUN [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4061 0 0]La lógica y la ciencia dictan que los fantasmas no son reales...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Pero es complicado negar la existencia de otras entidades paranormales teniendo en cuenta la Hora Oscura y la torre Tártaro.[n][uf 1 1][e]

[msg MSG_0606_0607_MITURU_DUN [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4061 0 0]Uno nunca se sabe cuándo va a aparecer una sombra más grande y fuerte, como nos pasó en el monorraíl.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Aprovecha el tiempo que tienes para explorar la torre Tártaro y mejorar tus habilidades.[n][uf 1 1][e]

[msg MSG_0613_MITURU_DUNGE [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4094 0 0]Yamagishi puede servir de apoyo para el equipo.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Por tanto, a partir de ahora, lucharé a vuestro lado. Me alegro de estar de vuelta.[n][uf 1 1][e]

[msg MSG_0623_0707_MITURU_DUN [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4094 0 0]Me alegra que Yamagishi se esté adaptando tan bien.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Es un apoyo digno de confianza, lo que significa que yo puedo concentrarme en luchar.[n][uf 1 1][e]

[msg MSG_0709_0717_MITURU_DUN [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4061 0 0]Al igual que la sombra del otro día, el enemigo tiene todo un arsenal de ataques a su disposición.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]La capacidad para actuar con rapidez afectará al resultado del combate.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Asegúrate de conseguir tanta experiencia como puedas a diario.[n][uf 1 1][e]

[msg MSG_0718_MITURU_DUNGE [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4061 0 0]El Instituto Gekkoukan cierra durante las vacaciones de verano, pero la torre Tártaro no.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Sé que es todo un reto, pero cuento contigo.[n][uf 1 1][e]

[msg MSG_0724_MITURU_DUNGE [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4131 0 0]Nunca imaginé que conseguiríamos un aliado tan fuerte en Yakushima.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]En fin, me alegra que estemos mejorando el grupo.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Puede que como líder sea más difícil, pero confío en ti.[n][uf 1 1][e]

[msg MSG_0725_0805_MITURU_DUN [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4094 0 0]Puede que Amada intente actuar como un adulto, pero todavía está en primaria.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Parece que Akihiko es su modelo a seguir, así que intenta ayudarle en lo que puedas.[n][uf 1 1][e]

[msg MSG_0806_0809_MITURU_DUN [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4061 0 0]Puede que las clases de verano sean agotadoras, pero tienes que concentrarte mientras estás en la Tártaro. Espabila.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Si te distraes un solo segundo, puedes resultar herida de gravedad. Concéntrate en el combate que tienes por delante.[n][uf 1 1][e]

[msg MSG_0810_0820_MITURU_DUN [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4061 0 0]¿Strega...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]No sabía que podía haber más usuarios de Persona...[n][uf 1 1][e]

[msg MSG_0821_0827_MITURU_DUN [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4136 0 0]No pienso echarte un sermón sobre los deberes de verano.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Por supuesto, confío en que ya los has terminado, ¿no?[n][uf 1 1][e]

[msg MSG_0828_0902_MITURU_DUN [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4094 0 0]Amada sigue siendo un novato en esto del combate básico, así que tenemos que apoyarlo.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Como líder del equipo, espero que le enseñes bien.[n][uf 1 1][e]

[msg MSG_0903_0904_MITURU_DUN [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4094 0 0]Aragaki siempre ha sido un luchador con rectitud moral.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Nunca deja sus creencias de lado... Eso se nota en su forma de luchar.[n][uf 1 1][e]

[msg MSG_0919_1003_MITURU_DUN [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4061 0 0]Nuestra batalla contra las sombras está a punto de acabar.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Y, por suerte, sin mucho problema.[n][uf 1 1][e]

[msg MSG_1005_1016_MITURU_DUN [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4061 0 0]Amada ha madurado mucho después de lo que ha pasado.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Sin duda, Aragaki estaría orgulloso de lo mucho que ha mejorado.[n][uf 1 1][e]

[msg MSG_1019_1102_MITURU_DUN [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4061 0 0]Hemos venido a la torre Tártaro muchas veces, y ahora está a punto de desaparecer por completo...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Es un alivio, sí, pero aún no podemos relajarnos.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Sé que repito esto muy a menudo, pero no bajéis la guardia hasta el final.[n][uf 1 1][e]

[msg MSG_1110_1117_MITURU_DUN [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4088 0 0][uf 4 25 5]...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Lo siento...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]No debería distraerme cuando estoy en la torre Tártaro.[n][uf 1 1][e]

[msg MSG_1121_MITURU_DUNGE [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4027 0 0]Siento haberos causado problemas.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Ahora estoy bien, así que no os preocupéis.[n][uf 1 1][e]

[msg MSG_1122_1127_MITURU_DUN [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4061 0 0]Iori necesita tiempo para volver al pie del cañón.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Yo le ayudaré en todo lo que pueda...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Pero esto es algo que debe superar por sí mismo.[n][uf 1 1][e]

[msg MSG_1203_1213_MITURU_DUN [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4094 0 0]En lugar de perder tiempo lamentándonos por el fin del mundo, deberíamos ponernos en marcha.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Vamos a centrarnos en derrotar a las sombras que se interponen en nuestro camino.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Divagar mientras estás en la torre Tártaro podría costarte la vida.[n][uf 1 1][e]

[msg MSG_1219_1225_MITURU_DUN [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4061 0 0]Supongo que celebraremos la Navidad mientras luchamos en la torre Tártaro.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]No es la típica celebración tradicional para parejas, pero... es especial, todo sea dicho. Lo agradezco.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0]Creo que el único motivo por el que me siento así es porque te tengo junto a mí.[n][uf 1 1][e]

[msg MSG_0101_0114_MITURU_DUN [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4061 0 0]Hasta ahora, no entendía eso de "el tiempo es oro".[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Íbamos contra reloj incluso en la Hora Oscura.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Por eso deberíamos invertir bien nuestro tiempo, para luego no arrepentirnos.[n][uf 1 1][e]

[msg MSG_0115_0130_MITURU_DUN [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4094 0 0]Ya no queda mucho para el combate contra Nix... Independientemente de lo que ocurra, es nuestra única oportunidad para ganar.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Pero creo que, después de todo lo que hemos pasado juntos, nos irá bien.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Lograremos salir de esta juntos, como un equipo.[n][uf 1 1][e]

[msg MSG_0131_MITURU_DUNGE [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4094 0 0]Esta es la Hora Oscura final... Menuda travesía larga y peligrosa hemos vivido.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Pero ahora no es momento de echar la vista atrás. La batalla aún no ha terminado.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Ya nos pondremos todo lo melancólicos que queramos después.[n][uf 1 1][e]

[msg MSG_TEST_MITURU_DUNGE [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4061 0 0]Ojalá hubiese un examen práctico de derrotar sombras en el instituto.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Así podríamos explorar la torre Tártaro y estudiar a la vez.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Bueno, será mejor que unos sueños tan poco realistas se queden en el mundo onírico. Aprovecharíamos mejor los días estudiando.[n][uf 1 1][e]

[msg MSG_HANYOU1_MITURU_DUNGE [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4061 0 0]Todo el mundo tiene su estilo de combate único. Algunos prefieren pasar a la ofensiva y otros priorizan la defensa.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Eres tú quien decide cómo actuamos en combate. Espero mucho de ti.[n][uf 1 1][e]

[msg MSG_HANYOU2_MITURU_DUNGE [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4094 0 0]No dudes en retirarte si sientes que no puedes más. Es mejor no forzarse demasiado.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Un verdadero líder sabe cuándo rendirse.[n][uf 1 1][e]

[msg MSG_MITURU_LOVER_INPARTY [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 65535 65535 0 0][uf 3 1 3 0 65535 4098 0 0]N-no te acerques tanto.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 65535 65535 0 0]No sé cómo mantener la calma cuando estás cerca...[n][uf 1 1][e]

[msg MSG_MITURU_TODAY_COMMU [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4131 0 0]Llevamos juntas todo el día, ¿no?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0]Supongo que eso demuestra lo mucho que confío en ti.[n][uf 1 1][e]

[msg MSG_MITURU_ZEKKOCHO [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4130 0 0]Hoy me siento genial. Cuenta conmigo.[n][uf 1 1][e]

