[sel SEL_TALK top]
[uf 0 5 65278][uf 2 1]Añadir al grupo[e]
[uf 0 5 65278][uf 2 1]Eliminar del grupo[e]
[uf 0 5 65278][uf 2 1]Da igual[e]

[sel SEL_BACK_UP_00 top]
[uf 0 5 65278][uf 2 1]Consultar progreso[e]
[uf 0 5 65278][uf 2 1]Da igual[e]

[sel SEL_PARTY top]
[uf 0 5 65278][uf 2 1]Yukari[e]
[uf 0 5 65278][uf 2 1]Aigis[e]
[uf 0 5 65278][uf 2 1]Mitsuru[e]
[uf 0 5 65278][uf 2 1]Junpei[e]
[uf 0 5 65278][uf 2 1]Sanada[e]
[uf 0 5 65278][uf 2 1]Amada[e]
[uf 0 5 65278][uf 2 1]Aragaki[e]
[uf 0 5 65278][uf 2 1]Koromaru[e]
[uf 0 5 65278][uf 2 1]Da igual[e]

[sel SEL_DOOR top]
[uf 0 5 65278][uf 2 1]Introducir[e]
[uf 0 5 65278][uf 2 1]No entrar[e]

[sel SEL_BACK_UP_01 top]
[uf 0 5 65278][uf 2 1]Consultar el estado de todos[e]
[uf 0 5 65278][uf 2 1]Da igual[e]

[sel SEL_BACK_UP_02 top]
[uf 0 5 65278][uf 2 1]¿Cuál es el estado del objetivo?[e]
[uf 0 5 65278][uf 2 1]Da igual.[e]

[sel SEL_BACK_UP_03 top]
[uf 0 5 65278][uf 2 1]¿Cuál es el estado del grupo?[e]
[uf 0 5 65278][uf 2 1]Vale.[e]
[uf 0 5 65278][uf 2 1]Un momento.[e]

[sel SEL_BACK_UP_04 top]
[uf 0 5 65278][uf 2 1]Consultar el estado de todos[e]
[uf 0 5 65278][uf 2 1]Dirigirse a la estación[e]
[uf 0 5 65278][uf 2 1]Ahora no[e]

[sel SEL_BACK_UP_05 top]
[uf 0 5 65278][uf 2 1]Consultar el estado de todos[e]
[uf 0 5 65278][uf 2 1]Comenzar la operación[e]
[uf 0 5 65278][uf 2 1]Ahora no[e]

[msg MSG_FUKA_BACK_UP_00 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Os apoyaré desde aquí. Pero, ¿necesitas algo más?[n][uf 1 1][e]

[msg MSG_FUKA_BACK_UP_RE_00 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]¿Algo más?[n][uf 1 1][e]

[msg MSG_FUKA_ANALYSIS_00 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Creo que lo más lejos que has llegado es el piso [uf 2 4 1].[n][uf 1 1][e]

[msg MSG_FUKA_ANALYSIS_GO [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Por ahora, intenta subir todo lo que puedas.[n][uf 1 1][e]

[msg MSG_FUKA_ANALYSIS_STOP [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0]Hemos conseguido llegar tan lejos como hemos podido. Supongo que... ¿misión cumplida?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0]Buen trabajo.[n][uf 1 1][e]

[msg MSG_FUKA_ANALYSIS_STOP_4 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Hemos subido hasta la cima de la torre, así que hemos cumplido nuestro objetivo, pero...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Después de todo lo que ha pasado, no hemos encontrado nada en la Tártaro, ni siquiera una pista.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 65535 0 0]Uf, ¿por qué estoy tan inquieta?[n][uf 1 1][e]

[msg MSG_FUKA_ANALYSIS_STOP_5 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Hemos subido todo lo posible por ahora... Pero parece que aún nos queda mucho por recorrer.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]¿Qué nos esperará más adelante?[n][uf 1 1][e]

[msg MSG_FUKA_ANALYSIS_STOP_L [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Hasta aquí podemos llegar ahora mismo.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Ahora solo queda esperar hasta el 31 de enero...[n][uf 1 1][e]

[msg MSG_FUKA_THEURGIA_BEFORE [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5006 0 0]De ahora en adelante, estaré ahí para apoyarte.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Cuando estoy preparada, como todos los demás, me puede la emoción.[n][uf 1 1][e]

[msg MSG_FUKA_BACK_UP_01 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5145 0 0]¿Estás lista?[n][uf 1 1][e]

[msg MSG_FUKA_MEMBER_LACK [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 65535 0 0][uf 3 1 3 0 65535 5006 0 0]Es peligroso continuar con el grupo tal y como está. Añade más compañeros a la formación.[n][uf 1 1][e]

[msg MSG_FUKA_LETS_GO_00 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Ten cuidado ahí fuera.[n][uf 1 1][e]

[msg MSG_FUKA_BACK_UP_02 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5006 0 0]Detecto que... los enemigos son aún más fuertes que la última vez.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Preparaos, porque nos esperan batallas arduas. Haré todo lo que pueda por apoyaros.[n][uf 1 1][e]

[msg MSG_FUKA_BACK_UP_03 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 4 25 6]...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Perdona, no debería tener dudas en un momento así.[n][uf 1 1][e]

[msg MSG_FUKA_BACK_UP_04 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 65535 0 0][uf 3 1 3 0 65535 5028 0 0]Aunque está solo, se enfrentará a nosotros...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Saldremos en cuanto terminemos los preparativos. Seguro que nos espera más adelante.[n][uf 1 1][e]

[msg MSG_FUKA_BACK_UP_05 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 65535 0 0][uf 3 1 3 0 65535 5116 0 0]La cima está justo ahí...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Por fin lo hemos conseguido. Hemos conquistado esta torre.[n][uf 1 1][e]

[msg MSG_FUKA_BACK_UP_06 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Solo un poco más...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Hasta la batalla final.[n][uf 1 1][e]

[msg MSG_FUKA_BACK_UP_07 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5006 0 0]Ahora mejor centrémonos en la sombra. ¿Quién te gustaría que te acompañase en la vanguardia?[n][uf 1 1][e]

[msg MSG_FUKA_ANALYSIS_01 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Detecto la señal del objetivo en algún lugar bajo nosotros.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 65535 0 0]Pero es como si... hubiese varias señales superponiéndose. No estoy segura.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 65535 0 0]¿Qué demonios será?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Esta vez tampoco sabemos a lo que nos enfrentamos, así que hay que prepararse para lo que sea.[n][uf 1 1][e]

[msg MSG_FUKA_LETS_GO_01 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Cuenta con mi ayuda para que puedas ir.[n][uf 1 1][e]

[msg MSG_FUKA_LETS_GO_02 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Vamos.[n][uf 1 1][e]

[msg MSG_1103_MITURU_01 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4088 0 0]Bueno, vámonos.[n][uf 1 1][e]

[msg MSG_1103_IKUTUKI_01 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 3 0 65535 14210 0 0]Muy bien, ten cuidado.[n][uf 1 1][e]

[msg MSG_1103_MITURU_02 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]¡Vamos![n][uf 1 1][e]

[msg MSG_FUKA_BACK_UP_08 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5003 0 0]Esta es nuestra batalla final... Saldremos de esta juntos.[n][uf 1 1][e]

[msg MSG_FUKA_ANALYSIS_02 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]La sombra está flotando en el aire, no hay señales de movimiento.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 65535 0 0]Si nos acercamos, será una masacre. Asegúrate de prepararte bien para el combate.[n][uf 1 1][e]

[msg MSG_0613_FUKA_DUNGE [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5006 0 0]A partir de ahora, proporcionaré apoyo en lugar de Kirijo.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Intentaré facilitar la exploración en la medida en la que me sea posible.[n][uf 1 1][e]

[msg MSG_0623_0707_FUKA_DUNGE [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 3 0 65535 5131 0 0]Ya me voy acostumbrando a proporcionar apoyo poco a poco.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0]Podéis contar conmigo.[n][uf 1 1][e]

[msg MSG_0709_0717_FUKA_DUNGE [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5062 0 0]En la última batalla, te dejaron para el arrastre...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Los enemigos también se han vuelto más fuertes, así que haré todo lo que pueda por apoyaros.[n][uf 1 1][e]

[msg MSG_0718_FUKA_DUNGE [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 3 0 65535 5131 0 0]Solo he visto Yakushima en fotos, pero dicen que es un lugar precioso. ¿No te parece emocionante?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Ah, pero ahora tenemos que centrarnos en explorar la torre Tártaro. Venga, pongámonos en marcha.[n][uf 1 1][e]

[msg MSG_0724_FUKA_DUNGE [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5062 0 0]¿Cómo consiguieron construir a Aigis?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]La tecnología del Grupo Kirijo es increíble... Ay, perdona. Ahora no es momento de estar pensando en esas cosas.[n][uf 1 1][e]

[msg MSG_0725_0805_FUKA_DUNGE [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5062 0 0]Amada es una persona hecha y derecha, y muy educada, además.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Salta a la vista que sus padres se preocupaban mucho por él.[n][uf 1 1][e]

[msg MSG_0806_0809_FUKA_DUNGE [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5062 0 0]Tener que asistir a clases de verano es deprimente, la verdad.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0]Pero quizá pueda concentrarme si estáis conmigo. Vamos a hacerlo lo mejor que podamos.[n][uf 1 1][e]

[msg MSG_0810_0820_FUKA_DUNGE [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5145 0 0]Parece que voy a poder apoyar a Koro de la misma forma que hago con los demás.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Se ve que entiende el lenguaje humano, y nosotros comprendemos cómo se siente.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Es un perro muy inteligente, ¿a que sí, Korocito?[n][uf 1 1][e]

[msg MSG_0821_0827_FUKA_DUNGE [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5062 0 0]Las vacaciones de verano han pasado volando, ¿eh? Sobre todo este año...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Supongo que es porque, entre una cosa y otra, no hemos parado en todo el día.[n][uf 1 1][e]

[msg MSG_0828_0902_FUKA_DUNGE [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5062 0 0]Amada es increíble, ¿a que sí? A pesar de lo joven que es, se le ve muy decidido.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Me dan ganas de darle todo mi apoyo.[n][uf 1 1][e]

[msg MSG_0903_0904_FUKA_DUNGE [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 3 0 65535 5131 0 0]Ahora que Aragaki se ha unido al grupo, somos más fuertes que antes.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0]Seguro que ahora te cuesta más elegir la formación del grupo, pero es una tarea que solo puede hacer la líder.[n][uf 1 1][e]

[msg MSG_0906_0918_FUKA_DUNGE [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5061 0 0]Parece que Kirijo también quiere enfrentarse a Strega.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]¿De dónde habrá sacado esa chica un Evocador?[n][uf 1 1][e]

[msg MSG_0919_1003_FUKA_DUNGE [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5145 0 0]Ya solo quedan tres sombras...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Se acerca el final de nuestro combate. Yo os apoyaré hasta el final.[n][uf 1 1][e]

[msg MSG_1005_1016_FUKA_DUNGE [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 65535 0 0][uf 3 1 3 0 65535 5089 0 0]Sanada y Amada se están dejando de lamentaciones, y nosotras deberíamos seguir su ejemplo...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Yo estoy bien. Os daré mi apoyo, como siempre.[n][uf 1 1][e]

[msg MSG_1019_1102_FUKA_DUNGE [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5145 0 0]Cuando derrotemos a la siguiente sombra, la torre Tártaro desaparecerá para siempre.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Sigue así y no pierdas de vista tu objetivo hasta el final.[n][uf 1 1][e]

[msg MSG_1106_1109_FUKA_DUNGE [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 65535 0 0][uf 3 1 3 0 65535 5089 0 0]¿Qué hemos estado haciendo todo este tiempo?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 65535 0 0]Creíamos que ya estaba, que esto sería el final...[n][uf 1 1][e]

[msg MSG_1110_1117_FUKA_DUNGE [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 65535 0 0][uf 3 1 3 0 65535 5089 0 0]Es imposible que Kirijo esté bien, teniendo en cuenta lo que ha pasado...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 65535 0 0]Me preocupa, pero ahora mismo creo que lo mejor es darle un poco de espacio.[n][uf 1 1][e]

[msg MSG_1121_FUKA_DUNGE [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5061 0 0]Si te preocupa lo que ha pasado durante el viaje escolar, no pasa nada, ya no estoy molesta.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Porque Kirijo ya... acabó con vosotros de nuestra parte.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]En fin, vamos a centrarnos en lo que tenemos entre manos y sigamos explorando.[n][uf 1 1][e]

[msg MSG_1121_FUKA_DUNGE_2 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 3 0 65535 5131 0 0]Parece que Kirijo ya se ha recuperado. Menos mal.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0]Sabía que superaría el duelo.[n][uf 1 1][e]

[msg MSG_1122_1127_FUKA_DUNGE [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 65535 0 0][uf 3 1 3 0 65535 5089 0 0]¿Estará bien Junpei?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 65535 0 0]He estado pensando en cómo podría hacer que se sintiese mejor, pero...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 65535 0 0]Supongo que no es tan fácil recuperarse después de lo ocurrido.[n][uf 1 1][e]

[msg MSG_1203_1213_FUKA_DUNGE [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 65535 0 0][uf 3 1 3 0 65535 5089 0 0]No puedo dejar de pensar en las palabras de Ryoji...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 65535 0 0][uf 4 25 6]...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 65535 0 0]Lo siento. Voy a intentar concentrarme.[n][uf 1 1][e]

[msg MSG_1219_1225_FUKA_DUNGE [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 3 0 65535 5096 0 0]Sé que la situación es difícil, pero tengo muchas ganas de que sea Navidad.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0]Porque... me gustaría pasar tiempo contigo.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 1 0]P-perdón... Qué corte, y eso que he sido yo la que lo ha dicho.[n][uf 1 1][e]

[msg MSG_0101_0114_FUKA_DUNGE [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5116 0 0]Empieza un nuevo año.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]El día de la promesa se acerca...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]No puedo permitir que los nervios se apoderen de mí. Tenemos que hacerlo como siempre.[n][uf 1 1][e]

[msg MSG_0115_0130_FUKA_DUNGE [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5116 0 0]Haremos todo lo posible por proteger nuestras vidas normales y corrientes y nuestro futuro... No, debemos hacerlo.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]No nos queda mucho tiempo hasta el día de la promesa. Sigamos haciéndonos más fuertes para la batalla final.[n][uf 1 1][e]

[msg MSG_0131_FUKA_DUNGE [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5116 0 0]Es el día de la promesa... El día en el que luchamos contra Nix por nuestro futuro.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Mientras estemos juntos, creo que podremos superar lo que nos propongamos.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Terminemos con esto y lleguemos vivos a mañana... para que podamos vernos en la graduación.[n][uf 1 1][e]

[msg MSG_HANYOU1_FUKA_DUNGE [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 3 0 65535 5075 0 0]Los días que vamos a la Tártaro, ceno menos.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0]Me entra muchísimo sueño después de una comilona.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Ah, ahora mismo no estoy cansada, no te preocupes por mí.[n][uf 1 1][e]

[msg MSG_HANYOU1_FUKA_DUNGE_2 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5061 0 0]En cada piso, las sombras parecen diferentes.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Puede que sea buena idea cambiar la formación del grupo de vez en cuando. Así será más fácil atacar la debilidad del enemigo.[n][uf 1 1][e]

[msg MSG_HANYOU2_FUKA_DUNGE [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5076 0 0]Me encanta cuando todos atacáis a las sombras a la vez.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]¡Cuando veáis una oportunidad, deberíais realizar esos ataques![n][uf 1 1][e]

[msg MSG_HANYOU2_FUKA_DUNGE_2 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5067 0 0]Todo el mundo está calentando mientras espera su turno.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Podemos cambiarnos entre nosotros en cualquier momento, así que no te fuerces demasiado.[n][uf 1 1][e]

[msg MSG_FUKA_LOVER_INPARTY [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5061 0 0]E-estás demasiado cerca...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Si pudieses oír lo rápido que me late el corazón, me moriría de vergüenza.[n][uf 1 1][e]

[msg MSG_FUKA_TODAY_COMMU [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 3 0 65535 5131 0 0]Parece que vamos a estar juntas todo el día.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0]Je, je, deberíamos explorar tanto como podamos.[n][uf 1 1][e]

[msg MSG_FUKA_ZEKKOCHO [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 3 0 65535 5131 0 0]Hoy me siento de maravilla. ¡Daré lo mejor de mí para apoyar al grupo![n][uf 1 1][e]

