[msg MSG_SENDER_NAME]
[f 2 1]Junpei Iori[n][w][e]

[msg MSG_001_0_0]
[f 2 1]yo![n][w][e]

[msg MSG_002_0_0]
[f 2 1]y'know, the two of us have never really hung out before [f 1 3 138][n]seems like a good time for a breather, so how 'bout we go have some fun?[n][f 1 5 0]i'll stick around in the classroom, so just lemme know if you're down [f 1 3 137][n][w][e]

[msg MSG_003_0_0]
[f 2 1]some summertime fun! [f 1 3 140][n][w][e]

[msg MSG_004_0_0]
[f 2 1]if you spend your vacation doing nothing, summer will be over before you know it! [f 1 3 138][n]listen man, you gotta help me with my crazy genius idea [f 1 3 135][n]so hurry and haul your ass to the strip mall! [f 1 3 140][n][w][e]

[msg MSG_005_0_0]
[f 2 1]how you doing?[n][w][e]

[msg MSG_006_0_0]
[f 2 1]a lot's been happening all at once, so i was wondering how you've been holding up.[n][f 1 5 0]wanna grab a bite for a change of pace?[n][w][e]

[msg MSG_007_0_0]
[f 2 1](No Subject)[n][w][e]

[msg MSG_008_0_0]
[f 2 1]hey, you free today?[n][w][e]

[msg MSG_009_0_0]
[f 2 1]'sup?[n][w][e]

[msg MSG_010_0_0]
[f 2 1]you good, man? [f 1 3 137][n]come hang with me after school [f 1 3 136][n][w][e]

[msg MSG_011_0_0]
[f 2 1]summer! [f 1 3 140][f 1 3 140][f 1 3 140][n][w][e]

[msg MSG_012_0_0]
[f 2 1]dude, it's so freakin' hot outside, i'm melting.[n][f 1 5 0]wanna go cool off at the movie theater? let's watch a cool hero flick and chill.[n][f 1 5 0]i heard there's only one screening right now, so hit me up if you're down[n][w][e]

[msg MSG_013_0_0]
[f 2 1]heyyy [f 1 3 138][n][w][e]

[msg MSG_014_0_0]
[f 2 1]dude, are you even checking your messages?[n][f 1 5 0]you're killing me man, why you gotta leave me hanging? [f 1 3 133][n]let's hang out soon [f 1 3 136][n][w][e]

[msg MSG_015_0_0]
[f 2 1]hellooo [f 1 3 138][f 1 3 138][f 1 3 138][n][w][e]

[msg MSG_016_0_0]
[f 2 1]you get my last message?[n][f 1 5 0]all my genius summer plan needs is you, dude![n][f 1 5 0]i'll be at the strip mall, so hurry on over after you see this [f 1 3 140][n][w][e]

[msg MSG_017_0_0]
[f 2 1]fuuka's looking for you[n][w][e]

[msg MSG_018_0_0]
[f 2 1]she couldn't find her phone so she asked me to send you a message. She was saying something about the hot spring?[n][f 1 5 0]anyway, she's on the top floor![n][w][e]

[msg MSG_019_0_0]
[f 2 1]wanna grab some grub?[n][w][e]

[msg MSG_020_0_0]
[f 2 1]let's catch a meal together sometime. we can go whenever you have time[n][w][e]

[msg MSG_021_0_0]
[f 2 1]hey[n][w][e]

[msg MSG_022_0_0]
[f 2 1]sorry for sounding like a broken record, but i gotta talk to you about something. so... please just hear me out[n][w][e]

[msg MSG_023_0_0]
[f 2 1]'suuup [f 1 3 140][n][w][e]

[msg MSG_024_0_0]
[f 2 1]hey, lemme know if you got time today [f 1 3 136][n][w][e]

