[msg MSG_SENDER_NAME]
[uf 0 5 65278][uf 2 1]Nozomi Suemitsu[n][uf 1 1][e]

[msg MSG_001_0_0]
[uf 0 5 65278][uf 2 1]LET'S GO!!! ☆[n][uf 1 1][e]

[msg MSG_002_0_0]
[uf 0 5 65278][uf 2 1]Hey, you, cool kid. Your name was [uf 4 2]-chan, right? Well, today's the day I'll finally treat you to a meal.[n][uf 1 5 0]Come to Paulownia Mall.[n][uf 1 1][e]

[msg MSG_003_0_0]
[uf 0 5 65278][uf 2 1]Gourmet☆Friends?[n][uf 1 1][e]

[msg MSG_004_0_0]
[uf 0 5 65278][uf 2 1]I must say, I was blown away at the sight of you scarfing down your food! Every time I rewind that memory, my appetite just EXPLODES! [uf 1 3 135][uf 1 3 135][n][uf 1 5 0]Come now, let us shake on our new friendship at Paulownia Mall.[n][uf 1 1][e]

[msg MSG_005_0_0]
[uf 0 5 65278][uf 2 1]NICE☆RICE[n][uf 1 1][e]

[msg MSG_006_0_0]
[uf 0 5 65278][uf 2 1]To my fellow foodie, who drifts in the same universe of flavor as I: it will soon be launch time.[n][uf 1 5 0]We take off @ Paulownia Mall NOW.[n][uf 1 1][e]

[msg MSG_007_0_0]
[uf 0 5 65278][uf 2 1]Are you H U N G R Y?[n][uf 1 1][e]

[msg MSG_008_0_0]
[uf 0 5 65278][uf 2 1]Yes or Y E S?[n][uf 1 5 0]We are on an endless journey in a galaxy of zest and zing.[n][uf 1 3 148][uf 1 3 148][uf 1 3 148][uf 1 3 148][uf 1 3 146]Isn't that so?[n][uf 1 5 0]Now then... Come, to Paulownia Mall. ☆[n][uf 1 1][e]

[msg MSG_009_0_0]
[uf 0 5 65278][uf 2 1]FIRE!!![n][uf 1 1][e]

[msg MSG_010_0_0]
[uf 0 5 65278][uf 2 1]My heart has been thoroughly flambéed to a crisp! All I can do now is stress eat!!![n][uf 1 5 0]You better come join me right now, my dear gourmet friend.[n][uf 1 1][e]

[msg MSG_011_0_0]
[uf 0 5 65278][uf 2 1]Just between us[n][uf 1 1][e]

[msg MSG_012_0_0]
[uf 0 5 65278][uf 2 1]I shall tell you the secret of life, but you shan't tell another soul...[n]↓　↓　↓　↓[n]"Sticks and stones may break my bones, but carbs and fats will never betray me."[n][uf 1 5 0]You'll never betray me either, right?[n][uf 1 5 0]Come to Paulownia Mall.[n][uf 1 1][e]

[msg MSG_013_0_0]
[uf 0 5 65278][uf 2 1]EMERGENCYYY!!![n][uf 1 1][e]

[msg MSG_014_0_0]
[uf 0 5 65278][uf 2 1]Let's put the past behind us and talk it out like adults, shall we?[n][uf 1 5 0]Only because you're my No. 1 supporter and the best gourmet friend I could ever ask for, [uf 4 2]-chan.[n][uf 1 1][e]

[msg MSG_015_0_0]
[uf 0 5 65278][uf 2 1]YES! YES! YES![n][uf 1 1][e]

[msg MSG_016_0_0]
[uf 0 5 65278][uf 2 1]I'm in paradise today [uf 1 3 145][n][uf 1 5 0]Turn up the heat! Let's get binging![n][uf 1 5 0]How do you feel about a high-calorie meal right now? [uf 1 3 135][uf 1 3 135][n][uf 1 1][e]

[msg MSG_017_0_0]
[uf 0 5 65278][uf 2 1][uf 4 2]-chan[n][uf 1 1][e]

[msg MSG_018_0_0]
[uf 0 5 65278][uf 2 1]I'm sorry about the other day. But I really do want to eat another meal with you again.[n][uf 1 1][e]

[msg MSG_019_0_0]
[uf 0 5 65278][uf 2 1]MEAT MEAT VEGGIE MEAT[n][uf 1 1][e]

[msg MSG_020_0_0]
[uf 0 5 65278][uf 2 1]Welcome to the bottomless pit of hanger pangs. [uf 1 3 135][uf 1 3 135][n][uf 1 5 0]Won't you join me?[n][uf 1 1][e]

[msg MSG_021_0_0]
[uf 0 5 65278][uf 2 1]Fill in the blank: Eat like a __?[n][uf 1 1][e]

[msg MSG_022_0_0]
[uf 0 5 65278][uf 2 1]And the answer is... "EAT LIKE A GOURMET KING"![n][uf 1 5 0]You think you got what it takes? Then come on over![n][uf 1 1][e]

[msg MSG_023_0_0]
[uf 0 5 65278][uf 2 1]EMERGENCY!!![n][uf 1 1][e]

[msg MSG_024_0_0]
[uf 0 5 65278][uf 2 1]We have an SOS here: Suffering of Starvation! [uf 1 3 138][uf 1 3 138][n][uf 1 5 0]Gourmet friends, ASSEMBLE!!![n][uf 1 1][e]

