namespace P3R.CostumeFramework.Costumes.Models;

internal enum CostumeSet
{
    Missing = 0,
    Summer_Uniform = 1,
    Winter_Uniform = 2,
    Summer_Casual = 5,
    Winter_Casual = 6,
    Uniform_Armband = 51,
    SEES_Uniform = 52,
    Gekkoukan_Jersey = 101,
    Swimsuit = 102,
    Nightwear = 103,
    Battle_Armor = 104,
    Butler_Suit = 106,
    Track_Team_Shirt = 151,
    Hot_Springs_Towel = 154,
    Hotel_Yukata = 155,
    Shrine_Festival_Yukata = 156,
    New_Years_Kimono = 157,
    Wilduck_Burger_Uniform = 158,
    Dorm_Apron = 159,
    Cafe_Uniform = 160,
    Be_Blue_V_Uniform = 161,
    Screen_Shot_Uniform = 162,
    SEES_Outfit = 201,
    SEES_Uniform_2 = 202,
    Damaged_Ribbon = 203,
    Ocean_Sundress = 204,
    Ocean_Sundress_2 = 205,
    Firearms = 206,
    Phantom_Suit = 501,
    Shujin_Uniform = 502,
    Yasogami_Uniform = 503,
	Velvet_Outfit = 504,
}
