[msg MSG_000_0_0 [Bunkichi]]
[uf 0 5 65278][uf 2 1][uf 4 5 103 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]Ah, [uf 4 2]. Justo estábamos hablando de ti.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 103 0 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]Discúlpanos por causarte tantas molestias con el asunto del caqui.[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]Yo no le daría vueltas.[e]
[uf 0 5 65278][uf 2 1]¿Qué caqui?[e]

[msg MSG_002_0_0 [Bunkichi]]
[uf 0 5 65278][uf 2 1][uf 4 5 103 1 65535 65535 0 0][uf 3 1 1 0 0 3 0 0][uf 5 13 6 5 103]¡Qué bueno! Me alegro de que bromees hasta en momentos así.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 103 1 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]Tengo la sensación de que tú y yo nos parecemos mucho. Bien sabe Dios que aprovecho cualquier ocasión para contar una gracieta.[n][uf 1 1][e]

[msg MSG_003_0_0 [Bunkichi]]
[uf 0 5 65278][uf 2 1][uf 4 5 103 0 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]¿Ya no te acuerdas del caqui? Es el vínculo que nos une.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 103 3 65535 65535 0 0][uf 3 1 1 0 0 6 0 0][uf 4 23 0 1 3 25 25]Debes de tener muchas cosas en la cabeza, ¿no? No es que no te importemos, ¿verdad?[n][uf 1 1][e]

[msg MSG_004_0_0 [Bunkichi]]
[uf 0 5 65278][uf 2 1][uf 4 5 103 3 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]El caqui... es un recuerdo de nuestro hijo.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 103 0 65535 65535 0 0][uf 3 1 1 0 0 8 0 0][uf 4 23 0 1 0 25 25]Antes de morir, era profesor del Instituto Gekkoukan.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 103 0 65535 65535 0 0][uf 3 1 1 0 0 9 0 0]Plantó ese árbol el día de la graduación de los alumnos de su primera clase.[n][uf 1 1][e]

[msg MSG_005_0_0 [Mitsuko]]
[uf 0 5 65278][uf 2 1][uf 4 5 104 3 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]Y justo cuando creíamos que estaba a punto de dar frutos...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 104 3 65535 65535 0 0][uf 3 1 1 0 0 11 0 0]¿Por qué ahora? ¿Por qué quieren cortarlo ahora?[n][uf 1 1][e]

[sel SEL_006_0_0 top]
[uf 0 5 65278][uf 2 1]Anímese.[e]
[uf 0 5 65278][uf 2 1]No pasará nada.[e]

[msg MSG_007_0_0 [Mitsuko]]
[uf 0 5 65278][uf 2 1][uf 4 5 104 1 65535 65535 0 0][uf 3 1 1 0 0 12 0 0][uf 5 13 6 5 104]Gracias, [uf 4 2].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 104 1 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]Ya está, ahora me siento mucho mejor. Hablar contigo es muy reconfortante.[n][uf 1 1][e]

[msg MSG_008_0_0 [Bunkichi]]
[uf 0 5 65278][uf 2 1][uf 4 5 103 1 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]¡Vaya! ¡Has conquistado el corazón de mi mujer![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 103 1 65535 65535 0 0][uf 3 1 1 0 0 15 0 0]¡Debes ser muy popular con los de tu edad! Que mi esposa ya no se chupa el dedo...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 103 1 65535 65535 0 0][uf 3 1 1 0 0 16 0 0]¡Es como si me viera a mí en mis tiempos mozos![n][uf 1 1][e]

[msg MND_009_0_0]
[uf 0 5 65278][uf 2 1]Parece que la pareja de ancianos se ha encariñado conmigo.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Tengo la sensación de que estamos estrechando lazos.[n][uf 1 1][e]

[msg MSG_010_0_0 [Bunkichi]]
[uf 0 5 65278][uf 2 1][uf 4 5 103 1 65535 65535 0 0][uf 3 1 1 0 0 17 0 0]No te preocupes por el árbol. Pásate cuando tengas tiempo.[n][uf 1 1][e]

[msg MSG_010_5_0 [Bunkichi]]
[uf 0 5 65278][uf 2 1][uf 4 5 103 0 65535 65535 0 0][uf 3 1 1 0 0 18 0 0]Ah, y llévate esto. Me ha sobrado, pero todavía se puede tomar.[n][uf 1 1][e]

[msg MND_011_0_0]
[uf 0 5 65278][uf 2 1]Bunkichi me ha metido un pan que ha sobrado en el bolsillo.[n][uf 1 1][e]

[msg MSG_012_0_0 [Bunkichi]]
[uf 0 5 65278][uf 2 1][uf 4 5 103 1 65535 65535 0 0][uf 3 1 1 0 0 19 0 0]En fin, cuídate mucho.[n][uf 1 1][e]

[msg MND_013_0_0]
[uf 0 5 65278][uf 2 1]Me he despedido de la pareja de ancianos y he vuelto a la residencia.[n][uf 1 1][e]

