[msg MSG_000_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 3 0 65535 11063 0 0]... Pode ficar com o meu se ainda estiver com fome.[n][uf 1 1][e]

[msg MSG_001_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 1 0]Não se preocupa. Não estou enjoada nem nada disso...[n][uf 1 1][e]

[msg MSG_002_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 3 0 65535 11065 0 0]Ei, [uf 4 1]-chan, sua boca tá suja de molho.[n][uf 1 1][e]

[sel SEL_003_0_0 top]
[uf 0 5 65278][uf 2 1]Ah, obrigada.[e]
[uf 0 5 65278][uf 2 1]Deixa.[e]
[uf 0 5 65278][uf 2 1]Limpa pra mim?[e]

[msg MSG_004_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 3 0 65535 11019 0 0][uf 5 13 12 15 106]De nada.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 4 23 0 106 0 25 25]... Você não vai limpar? Tá me incomodando.[n][uf 1 1][e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]Yuko parece estar se divertindo.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Eu aprendi mais a respeito dela hoje.[n][uf 1 1][e]

[msg MSG_006_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 3 0 65535 11071 0 0]Sério? Tá todo mundo vendo, sabia?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0]Vai, limpa logo isso aí. Toma um guardanapo...[n][uf 1 1][e]

[msg MND_007_0_0]
[uf 0 5 65278][uf 2 1]Yuko parece meio irritada.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Acho que não nos aproximamos hoje...[n][uf 1 1][e]

[msg MSG_008_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 3 0 65535 11089 0 0][uf 5 13 12 30 106]Você é mais imatura do que eu imaginava, [uf 4 1]-chan.[n][uf 1 1][e]

[msg MSG_008_5_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 1 0][uf 4 23 0 106 1 25 25]Tá bem. Vem aqui que eu limpo pra você...[n][uf 1 1][e]

[msg MND_009_0_0]
[uf 0 5 65278][uf 2 1]Yuko está corando.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Acho que nos aproximamos muito hoje.[n][uf 1 1][e]

[msg MSG_010_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 3 0 65535 11093 0 0]... As refeições aqui são bem equilibradas em termos de nutrientes.[n][uf 1 1][e]

[msg MSG_011_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0]Baixo teor de calorias e os acompanhamentos ajudam você a obter as vitaminas e minerais necessários...[n][uf 1 1][e]

[msg MSG_012_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 3 0 65535 11065 0 0]Ei, [uf 4 1]-chan, sua boca tá suja de molho.[n][uf 1 1][e]

[sel SEL_013_0_0 top]
[uf 0 5 65278][uf 2 1]Ah, obrigada.[e]
[uf 0 5 65278][uf 2 1]Tá tudo bem.[e]
[uf 0 5 65278][uf 2 1]É meu estilo.[e]

[msg MSG_014_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 3 0 65535 11019 0 0][uf 5 13 12 15 106]Sem problema.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 4 23 0 106 0 25 25]... Você não vai limpar? Tá me incomodando.[n][uf 1 1][e]

[msg MND_015_0_0]
[uf 0 5 65278][uf 2 1]Yuko parece estar se divertindo.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Eu aprendi mais a respeito dela hoje.[n][uf 1 1][e]

[msg MSG_016_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 3 0 65535 11090 0 0]Tá nada. Já se olhou no espelho?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0]Parece que tá de bigode ou algo assim. Tipo um velho sábio, haha...[n][uf 1 1][e]

[msg MND_017_0_0]
[uf 0 5 65278][uf 2 1]Yuko está rindo da minha cara.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Acho que não nos aproximamos hoje...[n][uf 1 1][e]

[msg MSG_018_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 3 0 65535 11077 0 0][uf 5 13 12 30 106]Sei, uma graça! Tá super na moda hoje em dia...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 4 23 0 106 1 25 25]Até parece! Haha... Vai, limpa logo esse negócio.[n][uf 1 1][e]

[msg MND_019_0_0]
[uf 0 5 65278][uf 2 1]Yuko parece estar se divertindo.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Acho que nos aproximamos muito hoje.[n][uf 1 1][e]

[msg MSG_020_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 3 0 65535 11064 0 0]Ah, então, já que estamos no centro comercial, podemos parar na livraria na volta pra casa?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 4 23 0 106 1 25 25]... Quê? Surpresa? Haha, pois é, realmente não sou do tipo de gente que vive na biblioteca.[n][uf 1 1][e]

[msg MND_021_0_0]
[uf 0 5 65278][uf 2 1]Depois que a Yuko foi para a livraria,[n]decidi voltar para o dormitório.[n][uf 1 1][e]

