[msg MSG_000_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]We only have so much time to train here, so you have to practice on your own if you want to win![n][uf 1 1][e]

[msg MSG_001_0_0 [Spunky Boy]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 2 0 0][uf 5 21 0 1001]Yeah, we can do that![n][uf 1 1][e]

[msg MSG_002_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]Good! And don't forget: Know your limits, and make sure you stretch properly![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]...Oh, [uf 4 1]-chan, why don't you give them some advice too?[n][uf 1 1][e]

[sel SEL_003_0_0 top]
[uf 0 5 65278][uf 2 1]You guys got this.[e]
[uf 0 5 65278][uf 2 1]Show some guts![e]

[msg MSG_004_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 5 0 0][uf 5 13 12 5 106]Yeah! But don't forget to stay focused till the end![n][uf 1 1][e]

[msg MSG_005_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 6 0 0][uf 5 13 12 5 106]Yeah! Guts! Spirit! You can do it, I know you can![n][uf 1 1][e]

[msg MSG_006_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]Now, listen. No matter what...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 2 65535 65535 0 0][uf 3 1 1 0 0 8 0 0][uf 4 23 0 1 0 25 25]Think positive, and don't give in to fear![n][uf 1 1][e]

[msg MND_007_0_0]
[uf 0 5 65278][uf 2 1]The kids went home after[n]finishing their training.[n][uf 1 1][e]

[msg MSG_008_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 9 0 0]Those kids are going to challenge the sixth graders soon.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]Apparently, the winners will get to use the schoolyard.[n][uf 1 1][e]

[msg MSG_008_5_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 0 0][uf 3 1 1 0 0 11 0 0]Earlier, they asked me to write the challenge letter for them... I'm a little worried, actually.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]Not just about the race, but also about whether or not I spelled something wrong.[n][uf 1 1][e]

[msg MSG_009_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]So, what's your honest opinion?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]Age difference really matters when you're as young as they are. Do you really think they can beat the sixth graders?[n][uf 1 1][e]

[sel SEL_010_0_0 top]
[uf 0 5 65278][uf 2 1]It's gonna be tough.[e]
[uf 0 5 65278][uf 2 1]As long as we believe in them.[e]

[msg MSG_011_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 0 0][uf 3 1 1 0 0 15 0 0]Yeah, no way around that, I guess...[n][uf 1 1][e]

[msg MSG_012_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 0 0][uf 3 1 1 0 0 16 0 0]Some of the boys that age are even bigger than me. There's just so much difference in their physical strength.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 17 0 0][uf 4 23 0 1 0 25 25]...But even so![n][uf 1 1][e]

[msg MSG_013_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 18 0 0][uf 5 13 12 5 106]Yeah, you're right! A coach has to believe in her team![n][uf 1 1][e]

[msg MSG_014_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 19 0 0]And they've all trained so hard too![n][uf 1 1][e]

[msg MSG_015_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 20 0 0]They'll be fine, right!? After all, they learned from us![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 0 0][uf 3 1 1 0 0 21 0 0][uf 4 23 0 1 3 25 25]Then why am I feeling so nervous...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 22 0 0][uf 4 23 0 1 0 25 25]It's gonna be okay. I'm sure they can win![n][uf 1 1][e]

[msg MND_016_0_0]
[uf 0 5 65278][uf 2 1]I feel a bond forming with Yuko.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]It seems we've grown closer...[n][uf 1 1][e]

[msg MSG_017_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 0 0][uf 3 1 1 0 0 23 0 0]Come to think of it, I should've asked you to write the challenge letter, [uf 4 1]-chan...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 0 0][uf 3 1 1 0 0 24 0 0]I probably should've used bigger words... Ugh, I'll be so embarrassed if those sixth graders laugh at it.[n][uf 1 1][e]

[msg MND_018_0_0]
[uf 0 5 65278][uf 2 1]Yuko and I walked home together.[n][uf 1 1][e]

