[msg MSG_000_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]It's tough being a team manager. You really don't get any respect.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]And the guys on the team all act like little kids.[n][uf 1 1][e]

[msg MSG_000_5_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 2 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]"Where's my towel?" "Can you wash this for me?" Ugh, I'm not their mother, you know?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 4 0 0][uf 4 23 0 1 0 25 25]At least I don't have to worry about gaining weight, since I'm always running around taking care of them.[n][uf 1 1][e]

[msg MSG_000_7_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]...How about you, [uf 4 1]-chan? Are you enjoying track and field?[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]It's fun![e]
[uf 0 5 65278][uf 2 1]I'm not sure yet.[e]

[msg MSG_002_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]Oh yeah? That's good to hear.[n][uf 1 1][e]

[msg MSG_003_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]Thought it might be boring for you, since you're so much better than everyone else.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 8 0 0][uf 4 23 0 1 0 25 25]I can tell just by looking. It's like... you've got your own style, and you don't waste much energy.[n][uf 1 1][e]

[msg MSG_004_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 9 0 0]Well, you did just start, so that makes sense.[n][uf 1 1][e]

[msg MSG_005_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]I thought it might be boring for you, since you're so much better than everyone else.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 11 0 0][uf 4 23 0 1 0 25 25]I can tell just by looking. It's like... you've got your own style, and you don't waste much energy.[n][uf 1 1][e]

[msg MSG_006_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]Well, if you have any questions, just ask Kaz. Um, you know, Kazushi.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]You guys are in the same class, so I'm sure he'd be willing to help you.[n][uf 1 1][e]

[msg MSG_006_5_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]You can ask me too, if you want, since I'm the manager.[n][uf 1 1][e]

[msg MND_007_0_0]
[uf 0 5 65278][uf 2 1]Yuko seems to be looking out for me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like the two of us[n]have gotten a little closer...[n][uf 1 1][e]

[msg MSG_008_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 15 0 0]Oh, I've gotta run. There's a show I wanna catch.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 16 0 0][uf 4 23 0 1 1 25 25]See you at school.[n][uf 1 1][e]

[msg MND_009_0_0]
[uf 0 5 65278][uf 2 1]After saying goodbye to Yuko,[n]I decided to go back to the dorm.[n][uf 1 1][e]

