[msg MSG_000_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 0 0 0 1 0 0]......[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]Hallo?[e]
[uf 0 5 65278][uf 2 1]......[e]
[uf 0 5 65278][uf 2 1]Wenn nichts ist, dann gehe ich.[e]

[msg MSG_002_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]J-Ja, ich höre dich![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0][uf 3 1 1 0 0 3 0 0][uf 4 23 0 2 3 25 25]Oh, sorry. Erschreck mich doch nicht so.[n][uf 1 1][e]

[msg MSG_003_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 4 0 0][uf 5 13 7 15 2]Oh ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]Du bist gekommen ... Danke.[n][uf 1 1][e]

[msg MSG_004_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 65535 65535 0 0][uf 3 1 0 0 0 6 0 0]Wie ...?[n][uf 1 1][e]

[msg MSG_005_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]H-Hey, warte! Das ist gemein![n][uf 1 1][e]

[msg MSG_006_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0][uf 3 1 1 0 0 8 0 0]Äh, das ist wohl meine Schuld ... tut mir leid.[n][uf 1 1][e]

[msg MSG_007_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 9 0 0]Also ... ich will dich schon seit einer Weile was fragen ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]Ähm ... [uf 4 1]-chan, bist du ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 0 0 0 11 0 0]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]Machst du dir wegen irgendwas Sorgen?[n][uf 1 1][e]

[sel SEL_008_0_0 top]
[uf 0 5 65278][uf 2 1]"Was redest du da?"[e]
[uf 0 5 65278][uf 2 1]Nicht wirklich ...[e]

[msg MSG_009_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]Ich kann dir von allen meinen Problemen, du bist so eine gute Zuhörerin ...[n][uf 1 1][e]

[msg MSG_010_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]Sicher? Du musst das nicht runterschlucken. Ich habe schlechtes Gewissen, dass wir immer nur über meine Probleme reden.[n][uf 1 1][e]

[msg MSG_011_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 15 0 0]Ich dachte nur, ich könnte dir vielleicht auch mal helfen.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 65535 65535 0 0][uf 3 1 1 0 0 16 0 0][uf 4 23 0 2 4 25 25]Ich meine, du bist so eine wichtige Freundin für mich! Ist doch unfair, wenn das eine Einbahnstraße ist.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 65535 65535 0 0][uf 3 1 1 0 0 17 0 0]Also was ich eigentlich sagen will ...[n][uf 1 1][e]

[msg MSG_011_3_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 18 0 0]Du musst mit deinen Problem nicht alleine klarkommen.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 19 0 0]Mir kommt es so vor, als würdest du immer allen anderen helfen und nicht auf dich selbst achten ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 20 0 0]Deswegen ... will ich dieser Mensch für dich sein. Ich will mich um dich kümmern, wie du dich um mich kümmerst.[n][uf 1 1][e]

[sel SEL_012_0_0 top]
[uf 0 5 65278][uf 2 1]Danke.[e]
[uf 0 5 65278][uf 2 1]Du übertreibst.[e]

[msg MSG_013_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 0 21 0 0]Hey, ich sollte dir danken.[n][uf 1 1][e]

[msg MSG_014_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 65535 65535 0 0][uf 3 1 1 0 0 22 0 0]Das stimmt nicht! Dass ich ständig deine Hilfe brauche, ist doch der Beweis.[n][uf 1 1][e]

[msg MSG_015_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 23 0 0]Weißt du, ich fand schon immer, dass du irgendwas Besonderes an dir hast.[n][uf 1 1][e]

[msg MSG_016_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 0 24 0 0]Weißt du noch, wie wir uns kennengelernt haben? Du konntest mühelos deine Persona rufen.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 0 25 0 0]Und im Gegensatz zu mir hattest du nie Angst, es mit den Schatten aufzunehmen.[n][uf 1 1][e]

[msg MSG_016_3_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 26 0 0]Du bist wie eine Superheldin, die allen hilft, die Hilfe brauchen ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 27 0 0]Wahrscheinlich dachte ich einfach, dass du keine Hilfe von jemandem wie mir brauchst.[n][uf 1 1][e]

[msg MSG_017_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 28 0 0]Aber ... dass jemand stark ist, heißt nicht, dass er alles alleine machen muss.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 29 0 0]Es ist keine Schande, sich von anderen unterstützen zu lassen. Manchmal kann es einem sogar helfen, noch mehr zu erreichen.[n][uf 1 1][e]

[msg MSG_017_3_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 30 0 0]Deswegen will ich für dich da sein und dir helfen.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 31 0 0]Ich weiß, es klingt vielleicht komisch, wenn ich das sage.[n][uf 1 1][e]

[msg MND_018_0_0]
[uf 0 5 65278][uf 2 1]Ich spüre Yukaris Zuneigung.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Wir scheinen uns nähergekommen zu sein ...[n][uf 1 1][e]

[msg MSG_019_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 65535 65535 0 0][uf 3 1 1 0 0 32 0 0]Mann, es ist so peinlich, das auszusprechen! Ich geh mich mal ein wenig abkühlen![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 0 33 0 0][uf 4 23 0 2 1 25 25]Jedenfalls kannst du dich ab sofort auf meine Unterstützung als Freund verlassen, okay?[n][uf 1 1][e]

[msg MSG_019_3_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 0 34 0 0]I-Ich gehe jetzt! Ciao![n][uf 1 1][e]

[msg MND_020_0_0]
[uf 0 5 65278][uf 2 1]Yukari ist weggerannt ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Ich ging zurück zum Wohnheim.[n][uf 1 1][e]

