[msg MSG_000_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]Sorry for all the trouble. Everything is under control now.[n][uf 1 1][e]

[msg MSG_001_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 5 65535 0 0][uf 3 1 1 0 0 2 0 0]What happened to securing the tank...?[n][uf 1 1][e]

[msg MSG_002_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 1 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]Oh, that's been taken care of.[n][uf 1 1][e]

[msg MSG_002_1_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 4 0 0][uf 4 23 0 1 0 25 25]Aigis, join us over here.[n][uf 1 1][e]

[msg MSG_003_0_0 [Girl's Voice]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 5 0 0]Understood.[n][uf 1 1][e]

[msg MSG_004_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]This is [uf 0 1 33]Aigis[uf 0 1 27]. As you can see, she's a machine with the form and face of a human girl.[n][uf 1 1][e]

[msg MSG_005_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 7 0 0]I am Aigis. My objective is to exterminate Shadows.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 8 0 0]I have been assigned to SEES, effective immediately.[n][uf 1 1][e]

[msg MSG_006_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 5 65535 0 0][uf 3 1 1 0 0 9 0 0]No way. It's like she's... alive.[n][uf 1 1][e]

[msg MSG_007_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 4 5 65535 0 0][uf 3 1 1 0 0 10 0 0]This is unbelievable...[n][uf 1 1][e]

[msg MSG_008_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 5 65535 0 0][uf 3 1 1 0 0 11 0 0]How can a robot be this cute? What a cruel world...[n][uf 1 1][e]

[msg MSG_009_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]Ten years ago, a plan was enacted to create anti-Shadow weapons; a contingency in the event a Shadow became unmanageable.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]Aigis was the last one to be made. And she's the only one that still remains today.[n][uf 1 1][e]

[msg MSG_010_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 5 65535 0 0][uf 3 1 1 0 0 14 0 0]An anti-Shadow weapon... Does that mean she has a Persona too?[n][uf 1 1][e]

[msg MSG_011_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 15 0 0]Correct. I am capable of wielding the Persona called Palladion.[n][uf 1 1][e]

[msg MSG_012_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 16 0 0]She suffered major damage in combat her first year out, and she's been kept in the lab ever since.[n][uf 1 1][e]

[msg MSG_012_1_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 17 0 0]I'm still not sure as to why she suddenly reactivated herself this morning...[n][uf 1 1][e]

[msg MSG_012_2_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 1 65535 65535 0 0][uf 3 1 1 0 0 18 0 0][uf 4 23 0 1 1 25 25]In any case, I hope you'll all get along.[n][uf 1 1][e]

[msg MSG_013_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 5 65535 0 0][uf 3 1 1 0 0 19 0 0]An anti-Shadow weapon, possessing a will all her own...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 5 65535 0 0][uf 3 1 1 0 0 20 0 0][uf 4 21 6 7][uf 4 23 0 6 1 25 25]This is amazing![n][uf 1 1][e]

[msg MSG_014_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 5 65535 0 0][uf 3 1 1 0 0 21 0 0]Uh, if you don't mind me asking...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 5 65535 0 0][uf 3 1 1 0 0 22 0 0]When we first saw you earlier, you were, uh, hugging [uf 4 1]-chan?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 5 65535 0 0][uf 3 1 1 0 0 23 0 0][uf 4 23 0 2 0 25 25]Do you know her?[n][uf 1 1][e]

[msg MSG_015_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 24 0 0]Yes. It is very important for me to be by his side.[n][uf 1 1][e]

[msg MSG_016_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 6 65535 65535 0 0][uf 3 1 1 0 0 25 0 0]Hm. Maybe her facial recognition system is malfunctioning.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 1 65535 65535 0 0][uf 3 1 1 0 0 26 0 0][uf 4 23 0 1 1 25 25]Or maybe she's still half-asleep. Very interesting.[n][uf 1 1][e]

[msg MSG_016_3_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 1 65535 65535 0 0][uf 3 1 1 0 0 27 0 0]Hmmm...[n][uf 1 1][e]

[msg MSG_017_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 5 65535 0 0][uf 3 1 1 0 0 28 0 0]Half-asleep?[n][uf 1 1][e]

[msg MSG_018_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 29 0 0]...Well, I can ponder this later.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 1 65535 65535 0 0][uf 3 1 1 0 0 30 0 0][uf 4 23 0 1 1 25 25]Anyhow, I forgot to mention.[n][uf 1 1][e]

[msg MSG_018_3_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 1 65535 65535 0 0][uf 3 1 1 0 0 31 0 0]Did you know there are a wide range of recreational facilities you can use here?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 1 65535 65535 0 0][uf 3 1 1 0 0 32 0 0]There's a tennis court, a pool table, and even a karaoke machine![n][uf 1 1][e]

[msg MSG_018_4_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 17 222 11 1][e]

[msg MSG_018_5_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 1 65535 65535 0 0][uf 3 1 1 0 0 33 0 0]Would anyone care to hear me sing?[n][uf 1 1][e]

[msg MSG_019_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 5 65535 0 0][uf 3 1 1 0 0 34 0 0]Uhhh...[n][uf 1 1][e]

