[msg MSG_000_0_0 [Aufgebrachter Typ]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 1 0 0][uf 5 21 0 1001]Was hast du gesagt? Halt besser die Klappe, Schlampe![n][uf 1 1][e]

[msg MSG_001_0_0 [Grinsender Typ]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 2 0 0][uf 5 21 0 1002]Wenn du dich nicht benimmst, verlierst du noch mehr als deine Geldbörse.[n][uf 1 1][e]

[msg MSG_002_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 65535 65535 0 0][uf 3 1 0 0 0 3 0 0]......[n][uf 1 1][e]

[sel SEL_003_0_0 top]
[uf 0 5 65278][uf 2 1]Ich mache dich fertig.[e]
[uf 0 5 65278][uf 2 1]Ich rufe die Polizei.[e]
[uf 0 5 65278][uf 2 1]Was geht hier ab?[e]

[msg MSG_004_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]...![n][uf 1 1][e]

[msg MSG_005_0_0 [Aufgebrachter Typ]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 5 0 0][uf 5 21 0 1001]Hä? Wer bist du denn bitte?![n][uf 1 1][e]

[msg MSG_006_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]Hey, ich habe doch gesagt, du sollst warten![n][uf 1 1][e]

[msg MSG_007_0_0 [Aufgebrachter Typ]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 7 0 0][uf 5 21 0 1001]Hä? Wer bist du denn bitte?![n][uf 1 1][e]

[sel SEL_008_0_0 top]
[uf 0 5 65278][uf 2 1]Ihre Freundin.[uf 2 9 1 1 344][e]
[uf 0 5 65278][uf 2 1]Eine Freundin von ihr.[e]
[uf 0 5 65278][uf 2 1]Ich bin zufällig vorbeigekommen.[e]

[msg MSG_009_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 65535 65535 0 0][uf 3 1 1 0 0 8 0 0]Hey, Moment! Was soll das heißen?![n][uf 1 1][e]

[msg MSG_010_0_0 [Aufgebrachter Typ]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 9 0 0][uf 5 21 0 1001]Du kannst das Angeben nicht lassen, was? Dann verprügle ich dich eben![n][uf 1 1][e]

[msg MSG_011_0_0 [Grinsender Typ]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 10 0 0][uf 5 21 0 1002]Verzieh dich, du Zwerg, sonst gibt's was auf die Nuss![n][uf 1 1][e]

[msg MSG_012_0_0 [Aufgebrachter Typ]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 11 0 0][uf 5 21 0 1001]Scheiße, du willst wohl eine Tracht Prügel, was?![n][uf 1 1][e]

[msg MSG_013_0_0 [Grinsender Typ]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 12 0 0][uf 5 21 0 1002]Dann kümmer dich um deinen eigenen Scheiß. Oder willst du Ärger? Hm?[n][uf 1 1][e]

[msg MSG_014_0_0 [Aufgebrachter Typ]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 13 0 0][uf 5 21 0 1001]Willst du etwa vor der Kleinen angeben? Wir sind in der Überzahl![n][uf 1 1][e]

[msg MSG_015_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]D-Danke.[n][uf 1 1][e]

[msg MND_016_0_0]
[uf 0 5 65278][uf 2 1]Yukari ist dankbar.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Wir scheinen uns nähergekommen zu sein ...[n][uf 1 1][e]

[msg MSG_017_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0][uf 3 1 1 0 0 15 0 0]Das war aber ein bisschen ... heftig. Du musstest sie nicht so schlimm verprügeln.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0][uf 3 1 0 0 0 16 0 0]......[n][uf 1 1][e]

[msg MSG_018_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0][uf 3 1 1 0 0 17 0 0]Hey, warum bist du mir nachgelaufen?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0][uf 3 1 1 0 0 18 0 0]Du solltest doch warten![n][uf 1 1][e]

[msg MSG_019_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0][uf 3 1 1 0 0 19 0 0]Dachtest du, ich muss gerettet werden?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0][uf 3 1 0 0 0 20 0 0]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 65535 65535 0 0][uf 3 1 1 0 0 21 0 0][uf 4 23 0 2 2 25 25]Ich bin nicht hilflos, okay?[n][uf 1 1][e]

[msg MSG_019_3_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 65535 65535 0 0][uf 3 1 1 0 0 22 0 0]Ich habe meine Geldbörse selbst geholt.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 65535 65535 0 0][uf 3 1 1 0 0 23 0 0]Ich habe deine Hilfe nicht gebraucht![n][uf 1 1][e]

[sel SEL_020_0_0 top]
[uf 0 5 65278][uf 2 1]Es tut mir leid.[e]
[uf 0 5 65278][uf 2 1]Es ist okay, sich von anderen helfen zu lassen.[e]
[uf 0 5 65278][uf 2 1]Du bist ein Mädchen, also ...[uf 2 9 1 1 70][e]

[msg MSG_021_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0][uf 3 1 0 0 0 24 0 0]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0][uf 3 1 1 0 0 25 0 0]Du musst dich nicht entschuldigen ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0][uf 3 1 1 0 0 26 0 0][uf 5 13 7 15 2]Ich sollte mich entschuldigen. Und ... danke.[n][uf 1 1][e]

[msg MSG_022_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0][uf 3 1 1 0 0 27 0 0]Ich gehe einfach schon vor. Mir geht's wieder gut. Entschuldige noch mal.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0][uf 3 1 1 0 0 28 0 0]Bis dann ...[n][uf 1 1][e]

[msg MSG_023_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 65535 65535 0 0][uf 3 1 1 0 0 29 0 0]Nein! Ich sage es dir, ich will nicht mein ganzes Leben von anderen abhängig sein![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 65535 65535 0 0][uf 3 1 1 0 0 30 0 0]Ich ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0][uf 3 1 0 0 0 31 0 0][uf 4 23 0 2 3 25 25]......[n][uf 1 1][e]

[msg MSG_023_3_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0][uf 3 1 1 0 0 32 0 0]Tut mir leid, ich habe überreagiert ... Du hast dir ja nur Sorgen um mich gemacht, oder?[n][uf 1 1][e]

[msg MSG_024_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0][uf 3 1 1 0 0 33 0 0]Ich gehe einfach schon vor. Mir geht's wieder gut. Entschuldige noch mal.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0][uf 3 1 1 0 0 34 0 0]Bis dann ...[n][uf 1 1][e]

[msg MSG_024_5_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 17 2 2 1][e]

[msg MSG_025_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 65535 65535 0 0][uf 3 1 1 0 0 35 0 0]Was soll das denn bitte heißen?! Ich bin ein Mädchen, und?![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 65535 65535 0 0][uf 3 1 1 0 0 36 0 0]Soll ich mich etwa mein ganzes Leben lang hinter anderen verstecken, wie meine Mutter?![n][uf 1 1][e]

[msg MSG_026_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 10 65535 65535 0 0][uf 3 1 1 0 0 37 0 0]Mach dich nicht über mich lustig ...[n][uf 1 1][e]

[msg MSG_026_5_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 8 65535 65535 0 0][uf 3 1 1 0 0 38 0 0]Ich habe nie um deine Hilfe gebeten! Ich ... Ich komme alleine klar![n][uf 1 1][e]

[msg MND_027_0_0]
[uf 0 5 65278][uf 2 1]Zwischen uns herrscht eine unangenehme Spannung ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Ich habe wohl einen Nerv getroffen.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Unsere Beziehung wird brüchig.[n][uf 1 1][e]

[msg MSG_028_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 10 65535 65535 0 0][uf 3 1 1 0 0 39 0 0]I-Ich gehe nach Hause.[n][uf 1 1][e]

[msg MND_029_0_0]
[uf 0 5 65278][uf 2 1]Ich habe mich von Yukari verabschiedet und bin zum Wohnheim zurückgegangen.[n][uf 1 1][e]

