[msg MSG_000_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 0 0 0 1 0 0]...[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]Hé ho ?[e]
[uf 0 5 65278][uf 2 1]...[e]
[uf 0 5 65278][uf 2 1]Si ce n'est rien, je m'en vais.[e]

[msg MSG_002_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]O-Oui, je suis là ![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0][uf 3 1 1 0 0 3 0 0][uf 4 23 0 2 3 25 25]Oh, désolée. Me fais pas peur comme ça.[n][uf 1 1][e]

[msg MSG_003_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 4 0 0][uf 5 13 7 15 2]Oh...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]Tu es venue... Merci.[n][uf 1 1][e]

[msg MSG_004_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 65535 65535 0 0][uf 3 1 0 0 0 6 0 0]Quoi ?[n][uf 1 1][e]

[msg MSG_005_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]Hé, attends ! C'est méchant.[n][uf 1 1][e]

[msg MSG_006_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0][uf 3 1 1 0 0 8 0 0]Euh, je crois que c'est de ma faute... Désolée.[n][uf 1 1][e]

[msg MSG_007_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 9 0 0]Bref, je voulais te demander quelque chose...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]Euh... [uf 4 1], est-ce que...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 0 0 0 11 0 0]...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]Il y a quelque chose qui te préoccupe ?[n][uf 1 1][e]

[sel SEL_008_0_0 top]
[uf 0 5 65278][uf 2 1]C'est à propos de quoi ?[e]
[uf 0 5 65278][uf 2 1]Pas vraiment...[e]

[msg MSG_009_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]C'est toujours à toi que je confie tous mes problèmes...[n][uf 1 1][e]

[msg MSG_010_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]T'es sûre ? Tu peux tout me dire, tu sais. Ça me gêne, j'ai l'impression qu'on fait que parler de moi et de mes problèmes...[n][uf 1 1][e]

[msg MSG_011_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 15 0 0]Je me suis dit que je pourrais peut-être t'aider.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 65535 65535 0 0][uf 3 1 1 0 0 16 0 0][uf 4 23 0 2 4 25 25]Tu comptes beaucoup pour moi ! Alors il faut que ça marche dans les deux sens...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 65535 65535 0 0][uf 3 1 1 0 0 17 0 0]Ce que j'essaie de dire, c'est que...[n][uf 1 1][e]

[msg MSG_011_3_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 18 0 0]Tu n'as pas à toujours prendre sur toi.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 19 0 0]Tu passes ton temps à aider les autres, sans jamais te soucier de toi...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 20 0 0]Je veux changer ça. Je veux prendre soin de toi comme tu prends soin des autres.[n][uf 1 1][e]

[sel SEL_012_0_0 top]
[uf 0 5 65278][uf 2 1]Merci.[e]
[uf 0 5 65278][uf 2 1]Tu exagères.[e]

[msg MSG_013_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 0 21 0 0]Hé, c'est moi qui devrais te remercier.[n][uf 1 1][e]

[msg MSG_014_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 65535 65535 0 0][uf 3 1 1 0 0 22 0 0]Non ! La preuve, c'est que je me repose tout le temps sur toi.[n][uf 1 1][e]

[msg MSG_015_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 23 0 0]Tu sais, je me suis toujours dit que tu avais quelque chose de spécial.[n][uf 1 1][e]

[msg MSG_016_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 0 24 0 0]Tu te rappelles quand on s'est rencontrées ? Tu pouvais invoquer ta Persona comme si de rien n'était...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 0 25 0 0]Et contrairement à moi, tu n'as jamais eu peur d'affronter les Ombres.[n][uf 1 1][e]

[msg MSG_016_3_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 26 0 0]Tu me fais l'effet d'une superhéroïne qui sauve la mise à tout le monde...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 27 0 0]Je me suis convaincue que tu n'avais pas besoin d'aide venant de quelqu'un comme moi.[n][uf 1 1][e]

[msg MSG_017_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 28 0 0]Mais ce n'est pas parce qu'on est fort qu'on doit se sentir obligé de tout faire tout seul.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 29 0 0]Il n'y a pas de mal à se faire aider. Parfois, c'est même avec de l'aide qu'on accomplit les plus grandes choses.[n][uf 1 1][e]

[msg MSG_017_3_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 30 0 0]C'est pour ça que je veux être là pour toi.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 31 0 0]Je sais que ça peut paraître bizarre venant de moi.[n][uf 1 1][e]

[msg MND_018_0_0]
[uf 0 5 65278][uf 2 1]Je sens toute l'affection de Yukari.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]J'ai l'impression que nous nous sommes rapprochées...[n][uf 1 1][e]

[msg MSG_019_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 65535 65535 0 0][uf 3 1 1 0 0 32 0 0]C'est tellement gênant de le dire à voix haute ! Il faut que j'aille me calmer un peu ![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 0 33 0 0][uf 4 23 0 2 1 25 25]Bref, à partir de maintenant, tu pourras te reposer sur moi comme sur une amie, d'accord ?[n][uf 1 1][e]

[msg MSG_019_3_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 0 34 0 0]Je vais y aller ! À plus ![n][uf 1 1][e]

[msg MND_020_0_0]
[uf 0 5 65278][uf 2 1]Yukari est partie en courant...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]J'ai décidé de rentrer au dortoir.[n][uf 1 1][e]

