[msg MSG_000_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]I'm having trouble deciding which restaurant to go to.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 2 0 0][uf 4 23 0 1 0 25 25]This place looks cute, but this one looks a bit more reasonable...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]Which one sounds better to you, [uf 4 1]-kun?[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]The cute one.[e]
[uf 0 5 65278][uf 2 1]The reasonable one.[e]
[uf 0 5 65278][uf 2 1]Either is fine.[e]

[msg MSG_002_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 0 0][uf 3 1 1 0 0 4 0 0][uf 5 13 12 5 106]I hear you. It'd be great to go somewhere with a nice ambiance, right?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]...But we should try and get our money's worth too...[n][uf 1 1][e]

[msg MSG_003_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 6 0 0][uf 5 13 12 5 106]Yeah, totally! We can't call it a party without getting lots of food![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 7 0 0][uf 4 23 0 1 0 25 25]But it'd also be nice to go somewhere with a cute ambiance...[n][uf 1 1][e]

[msg MSG_004_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 2 65535 65535 0 0][uf 3 1 1 0 0 8 0 0]...That's the least helpful answer, you know. Guess it's up to me then.[n][uf 1 1][e]

[msg MSG_005_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 9 0 0]Hmm... Should we just go to both?[n][uf 1 1][e]

[msg MSG_006_0_0 [Girl in Black Tights]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 10 0 0][uf 5 21 0 10]Oh, Nishiwaki-san.[n][uf 1 1][e]

[msg MSG_007_0_0 [Girl with Bright Hair]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 11 0 0][uf 5 21 0 11]With your boyfriend again, huh? You just love to show off, don't you?[n][uf 1 1][e]

[msg MSG_008_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]I already said it's not like that.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 13 0 0][uf 4 23 0 1 0 25 25]He's just a friend from the team. That's all.[n][uf 1 1][e]

[msg MSG_009_0_0 [Girl in Black Tights]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 14 0 0][uf 5 21 0 10]You know you don't have to try so hard to hide it.[n][uf 1 1][e]

[msg MSG_010_0_0 [Girl with Bright Hair]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 15 0 0][uf 5 21 0 11]I bet there's a reason she has to keep quiet about it. Like, maybe she stole him from someone again?[n][uf 1 1][e]

[msg MSG_011_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 2 65535 65535 0 0][uf 3 1 1 0 0 16 0 0]Geez, give it a rest already![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 2 65535 65535 0 0][uf 3 1 1 0 0 17 0 0]Is that all you can think of when you see a guy and a girl together? You need to grow up.[n][uf 1 1][e]

[msg MSG_012_0_0 [Girl with Bright Hair]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 18 0 0][uf 5 21 0 11]Wha...?[n][uf 1 1][e]

[msg MSG_013_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 19 0 0]Look, I know you hate me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 20 0 0]Once you have a bad experience with something, it's hard to get over.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 2 65535 65535 0 0][uf 3 1 1 0 0 21 0 0][uf 4 23 0 1 2 25 25]But harassing and bothering people over it... It's just wrong.[n][uf 1 1][e]

[msg MSG_014_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 2 65535 65535 0 0][uf 3 1 1 0 0 22 0 0]And I'm sorry, but I don't have time to put up with you right now.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 2 65535 65535 0 0][uf 3 1 1 0 0 23 0 0]I've found something important to me that I want to achieve.[n][uf 1 1][e]

[msg MSG_015_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 24 0 0]So, how about you?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 25 0 0]Is what you're doing here now important to you?[n][uf 1 1][e]

[msg MSG_016_0_0 [Girl in Black Tights]]
[uf 0 5 65278][uf 2 1][uf 3 1 0 0 0 26 0 0]......[n][uf 1 1][e]

[msg MSG_017_0_0 [Girl with Bright Hair]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 27 0 0][uf 5 21 0 11]Excuse me? You're the one who started—[n][uf 1 1][e]

[msg MSG_018_0_0 [Girl in Black Tights]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 28 0 0][uf 5 21 0 10]It's fine. Let's just go.[n][uf 1 1][e]

[msg MSG_019_0_0 [Girl with Bright Hair]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 29 0 0][uf 5 21 0 11]Hey, wait up![n][uf 1 1][e]

[msg MSG_020_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 0 0][uf 3 1 1 0 0 30 0 0]Sorry for always dragging you into situations like this.[n][uf 1 1][e]

[sel SEL_021_0_0 top]
[uf 0 5 65278][uf 2 1]Glad it didn't turn into a fight.[e]
[uf 0 5 65278][uf 2 1]You handled it well.[e]

[msg MSG_022_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 31 0 0]That's because I had a reliable friend like you next to me. You gave me the courage I needed.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 32 0 0]...And if something did happen, I trust that you'd step in.[n][uf 1 1][e]

[msg MSG_023_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 0 0][uf 3 1 1 0 0 33 0 0]You know, if things were different, I might've turned out like her too.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 0 0][uf 3 1 1 0 0 34 0 0]Stuck in my own little bubble, never being able to take that first step forward...[n][uf 1 1][e]

[msg MSG_023_5_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 35 0 0]Well, I don't wanna overcomplicate this or anything.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 36 0 0]I'm just really glad to have such a great friend![n][uf 1 1][e]

[msg MND_024_0_0]
[uf 0 5 65278][uf 2 1]I can sense that Yuko trusts me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like our relationship has grown...[n][uf 1 1][e]

[msg MSG_025_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 37 0 0]Aw man! I'm starving![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 0 0][uf 3 1 1 0 0 38 0 0][uf 4 23 0 1 3 25 25]Thinking and talking at the same time is tiring...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 39 0 0][uf 4 23 0 1 1 25 25]Let's go get dinner. Oh, I mean, to our celebratory party![n][uf 1 1][e]

[msg MND_026_0_0]
[uf 0 5 65278][uf 2 1]I went to celebrate with Yuko. I ate so[n]much, my stomach is about to burst.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I should head back to the dorm...[n][uf 1 1][e]

