[msg MSG_000_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]Here comes the champ.[n][uf 1 1][e]

[msg MSG_001_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]Now things are getting exciting! Get 'im, Amada![n][uf 1 1][e]

[msg MSG_002_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]Arf! Arf![n][uf 1 1][e]

[sel SEL_003_0_0 top]
[uf 0 5 65278][uf 2 1]Why are you here?[e]
[uf 0 5 65278][uf 2 1]My promise was to Amada...[e]

[msg MSG_004_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]We heard you guys were gonna have a match, so we came to witness it.[n][uf 1 1][e]

[msg MSG_005_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]These kinds of things need an audience, don't you think?[n][uf 1 1][e]

[msg MSG_006_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 9 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]We heard you two were going to have a match. We're just here to witness it.[n][uf 1 1][e]

[msg MSG_007_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]That's right, we're here to watch the little dude shine.[n][uf 1 1][e]

[msg MSG_008_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 8 0 0]When I told them I wanted to beat you, they all offered to help.[n][uf 1 1][e]

[msg MSG_009_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 9 0 0]I set up a training routine for him, and gave him advice on his movements.[n][uf 1 1][e]

[msg MSG_010_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]I also wanted to build my legs and core, so I've been going on runs with Koromaru.[n][uf 1 1][e]

[msg MSG_011_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 1 65535 65535 0 0][uf 3 1 1 0 0 11 0 0]Arf![n][uf 1 1][e]

[msg MSG_012_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]And I took on the role of bein' you for practice matches.[n][uf 1 1][e]

[msg MSG_013_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]We figured if he couldn't land a hit on Junpei, then beating you would be out of the question.[n][uf 1 1][e]

[msg MSG_014_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]Wha— Hey, spare a thought for the guy covered in bruises over here![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 65535 65535 0 0][uf 3 1 1 0 0 15 0 0][uf 4 23 0 2 3 25 25]Man, he really didn't hold back anything on me...[n][uf 1 1][e]

[msg MSG_015_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 65535 65535 0 0][uf 3 1 1 0 0 16 0 0]Well then... Let's do this![n][uf 1 1][e]

[msg MSG_016_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 65535 65535 0 0][uf 3 1 1 0 0 17 0 0]Hyaaa![n][uf 1 1][e]

[msg MSG_017_0_0 [Junpei Iori (SE)]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 18 0 0]Whoaaa![n][uf 1 1][e]

[msg MSG_018_0_0 [Akihiko Sanada (SE)]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 19 0 0]Hmm...[n][uf 1 1][e]

[msg MSG_019_0_0 [Koromaru (SE)]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 20 0 0]*whimper*[n][uf 1 1][e]

[msg MSG_020_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 65535 65535 0 0][uf 3 1 1 0 0 21 0 0]*pant* *pant*[n][uf 1 1][e]

[msg MSG_021_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 0 22 0 0]You're doin' good, Amada! Keep it up![n][uf 1 1][e]

[msg MSG_022_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 65535 65535 0 0][uf 3 1 1 0 0 23 0 0]You can do this, just take it half a step further![n][uf 1 1][e]

[msg MSG_023_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 1 0 0 24 0 0]Woof, woof![n][uf 1 1][e]

[msg MSG_024_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 65535 65535 0 0][uf 3 1 1 0 0 25 0 0]Yah![n][uf 1 1][e]

[msg MSG_025_0_0 [Junpei Iori (SE)]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 26 0 0]Whoa![n][uf 1 1][e]

[msg MSG_026_0_0 [Akihiko Sanada (SE)]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 27 0 0]...![n][uf 1 1][e]

[msg MSG_027_0_0 [Koromaru (SE)]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 28 0 0]Woof...![n][uf 1 1][e]

[msg MSG_028_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 5 65535 65535 0 0][uf 3 1 1 0 0 29 0 0]Ngh...[n][uf 1 1][e]

[msg MSG_029_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 65535 65535 0 0][uf 3 1 1 0 0 30 0 0]Crap, did she get hit!?[n][uf 1 1][e]

[msg MSG_030_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0][uf 3 1 1 0 0 31 0 0]Bark, bark![n][uf 1 1][e]

[msg MSG_031_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 65535 65535 0 0][uf 3 1 1 0 0 32 0 0]The next one's coming, get up![n][uf 1 1][e]

[sel SEL_032_0_0 top]
[uf 0 5 65278][uf 2 1]You're finished.[e]
[uf 0 5 65278][uf 2 1]No hard feelings.[e]

[msg MSG_033_0_0 [Yukari's Voice]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 33 0 0]Hey, are you guys up there?[n][uf 1 1][e]

[msg MSG_033_5_0 [Yukari's Voice]]
[uf 0 5 65278][uf 2 1][uf 4 17 8 2 0][e]

[msg MSG_034_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 65535 65535 0 0][uf 3 1 1 0 0 34 0 0]Haah![n][uf 1 1][e]

[msg MSG_035_0_0 [Junpei Iori (SE)]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 35 0 0]Ahhhhhh![n][uf 1 1][e]

[msg MSG_036_0_0 [Akihiko Sanada (SE)]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 36 0 0]Oh...!?[n][uf 1 1][e]

[msg MSG_037_0_0 [Koromaru (SE)]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 37 0 0]Arf...![n][uf 1 1][e]

[msg MSG_038_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 0 38 0 0]Aw, yeah! That's a clean hit! The winner is Amada, in the blue corner![n][uf 1 1][e]

[msg MSG_039_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 1 65535 65535 0 0][uf 3 1 1 0 0 39 0 0]Arf! Arf![n][uf 1 1][e]

[msg MSG_040_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 1 0 0 40 0 0]I just got lucky. Plus, I did kind of cheat...[n][uf 1 1][e]

[msg MSG_041_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 41 0 0]No, you saw a window of opportunity and you took it. That's something to be proud of.[n][uf 1 1][e]

[msg MSG_042_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 42 0 0]Fuuka and I bought some roasted sweet potatoes. I was looking for everyone to come eat with us, but...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 65535 65535 0 0][uf 3 1 1 0 0 43 0 0][uf 4 23 0 1 6 25 25][uf 4 21 2 10]What are you guys doing up here anyway?[n][uf 1 1][e]

[msg MSG_043_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 9 65535 65535 0 0][uf 3 1 1 0 0 44 0 0]We're witnessing a showdown. Right, Amada?[n][uf 1 1][e]

[msg MSG_044_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 1 0 0 45 0 0]It sounds kinda weird when you put it like that... But yeah, I guess so.[n][uf 1 1][e]

[msg MSG_045_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 1 0 0 46 0 0]It was a great match, on both sides.[n][uf 1 1][e]

[msg MSG_046_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 47 0 0]Huh...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 0 48 0 0][uf 4 23 0 1 1 25 25]I don't really get it, but it sounds like you're having fun. It's cold though, so you should head inside soon.[n][uf 1 1][e]

[msg MSG_047_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 0 49 0 0]Oh wait, did you say sweet potatoes!? Count me in![n][uf 1 1][e]

[msg MSG_048_0_0 [Yukari Takeba (SE)]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 50 0 0]I bought them for Amada-kun! Junpei, you can have the skin and the burnt parts.[n][uf 1 1][e]

[msg MSG_049_0_0 [Junpei Iori (SE)]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 51 0 0]Hey! What am I, a dog?[n][uf 1 1][e]

[msg MSG_050_0_0 [Koromaru (SE)]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 52 0 0]Arf![n][uf 1 1][e]

[msg MSG_051_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 1 0 0 53 0 0]Thanks for the match, [uf 4 1]-san. I learned a lot from it.[n][uf 1 1][e]

[sel SEL_052_0_0 top]
[uf 0 5 65278][uf 2 1]You were great.[e]
[uf 0 5 65278][uf 2 1]I let my guard down.[e]
[uf 0 5 65278][uf 2 1]Let's do one more round...[e]

[msg MSG_053_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 54 0 0]No, I just got lucky. I was stuck on the defensive that whole time.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 1 0 0 55 0 0][uf 4 23 0 3 1 25 25]But I think I did do better than our last fight. Now, I just need to apply this to a real battle...[n][uf 1 1][e]

[msg MSG_054_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 1 0 0 56 0 0]It was just luck. I was stuck on the defensive that whole time.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 1 0 0 57 0 0]Guess I still have a long way to go. You really are amazing.[n][uf 1 1][e]

[msg MSG_055_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 1 0 0 58 0 0]If we do one more round, I'll definitely lose.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 59 0 0][uf 4 23 0 3 0 25 25]I just got lucky. You really are amazing.[n][uf 1 1][e]

[msg MSG_056_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 60 0 0]Technically, we're tied one-to-one now, so the next match decides the real winner... Not sure I actually have a chance though.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 1 0 0 61 0 0][uf 4 23 0 3 1 25 25]But I hope you'll let me challenge you again some time. You gotta promise, okay?[n][uf 1 1][e]

[msg MSG_057_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 62 0 0]Okay. Then until that time comes, will you hold on to this for me?[n][uf 1 1][e]

[msg MSG_058_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 63 0 0]That's... the key to the house I lived in with my mom.[n][uf 1 1][e]

[msg MSG_059_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 65535 65535 0 0][uf 3 1 1 0 0 64 0 0]Whenever I look at it, I remember the time I spent with her.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 65535 65535 0 0][uf 3 1 1 0 0 65 0 0]That house is filled with all kinds of memories we shared together...[n][uf 1 1][e]

[msg MSG_060_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 65535 65535 0 0][uf 3 1 1 0 0 66 0 0]I know the final battle isn't going to be easy.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 2 65535 65535 0 0][uf 3 1 1 0 0 67 0 0][uf 4 23 0 3 2 25 25]But no matter what, I want to come back here.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 68 0 0][uf 4 23 0 3 0 25 25]I feel like this key will connect us to each other.[n][uf 1 1][e]

[msg MSG_061_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 69 0 0]And I hope someday... maybe I can be that person someone can always come back to.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 70 0 0]Just like how Mom, and everyone at the dorm, was there for me.[n][uf 1 1][e]

[msg MSG_062_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 1 0 0 71 0 0]...Ah, sorry for talking for so long. Shall we go down and have some sweet potatoes?[n][uf 1 1][e]

[msg MSG_063_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 72 0 0]So our next match would be next year? Or maybe even longer than that...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 1 0 0 73 0 0][uf 4 23 0 3 1 25 25]I know! How about once I reach the same height as you?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 1 0 0 74 0 0][uf 4 23 0 3 0 25 25]And if we're around the same build, I might stand a chance. Oh, but you'll probably be even stronger by then...[n][uf 1 1][e]

[msg MSG_064_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 1 0 0 75 0 0]When that time comes, I wonder what everyone will be like.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 1 0 0 76 0 0]It's exciting just thinking about it![n][uf 1 1][e]

[msg MND_065_0_0]
[uf 0 5 65278][uf 2 1]Amada was beaming with happiness[n]as we went to join the others.[n][uf 1 1][e]

[msg SYS_066_0_0]
[uf 0 5 65278][uf 2 1]You have forged a powerful bond with Amada! You can now fuse [uf 0 1 35]Michael[uf 0 1 27], the protector of all![n][uf 1 1][e]

