[msg MSG_000_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 2 65535 0 0][uf 3 1 1 0 0 1 0 0]Hay algo que debes saber.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 2 65535 0 0][uf 3 1 1 0 0 2 0 0]¿Recuerdas a Chidori, la chica que estaba con Strega?[n][uf 1 1][e]

[msg MSG_000_5_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 2 65535 0 0][uf 3 1 1 0 0 3 0 0]No es mi intención alarmarte, pero...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 2 65535 0 0][uf 3 1 1 0 0 4 0 0]Lo cierto es que... es probable que despierte hoy mismo.[n][uf 1 1][e]

[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]¡¿...?![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]¿Chidori sigue viva?[n][uf 1 1][e]

[msg MSG_002_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 2 65535 0 0][uf 3 1 1 0 0 5 0 0]Ya sé lo que vas a decir. Sí, la vimos morir ante nuestros ojos.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 2 65535 0 0][uf 3 1 1 0 0 6 0 0][uf 4 23 0 5 0 25 25]Sin embargo, su cuerpo empezó un proceso de metamorfosis unos días después.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 2 65535 0 0][uf 3 1 1 0 0 7 0 0][uf 4 23 0 5 0 25 25]Durante las últimas semanas, ha estado sumida en un estado de estasis; no estaba ni viva ni muerta.[n][uf 1 1][e]

[sel SEL_003_0_0 top]
[uf 0 5 65278][uf 2 1]¿Cómo... es posible?[e]
[uf 0 5 65278][uf 2 1]¿Y por qué no habías dicho nada?[e]

[msg MSG_004_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 2 65535 0 0][uf 3 1 1 0 0 8 0 0]Ni idea.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 2 65535 0 0][uf 3 1 1 0 0 9 0 0]Quizá esté relacionado con sus habilidades de Persona, pero es una mera especulación.[n][uf 1 1][e]

[msg MSG_005_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 2 65535 0 0][uf 3 1 1 0 0 10 0 0]La verdad es que no estaba segura de si debía hacerlo.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 2 65535 0 0][uf 3 1 1 0 0 11 0 0]Cabía la posibilidad de que eso empeorara la situación, ya que no sabía si viviría o terminaría muriendo.[n][uf 1 1][e]

[msg MSG_006_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 2 65535 0 0][uf 3 1 1 0 0 12 0 0]Lo que quería discutir contigo es cómo crees que deberíamos darle la noticia a Junpei.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 10 2 65535 0 0][uf 3 1 1 0 0 13 0 0][uf 4 23 0 5 10 25 25]Verás, seguramente ella...[n][uf 1 1][e]

[msg MSG_007_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 2 65535 0 0][uf 3 1 1 0 0 14 0 0]Sí, soy yo.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 2 65535 0 0][uf 3 1 1 0 0 15 0 0][uf 4 23 0 5 3 25 25]Ya.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 2 65535 0 0][uf 3 1 1 0 0 16 0 0][uf 4 23 0 5 3 25 25]Entiendo.[n][uf 1 1][e]

[msg MSG_008_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 2 65535 0 0][uf 3 1 1 0 0 17 0 0]Era del hospital.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 2 65535 0 0][uf 3 1 1 0 0 18 0 0]Me han dicho que acaba de despertar.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 2 65535 0 0][uf 3 1 1 0 0 19 0 0][uf 4 23 0 5 3 25 25]Sé que es difícil de creer, pero parece que Chidori ha vuelto a la vida...[n][uf 1 1][e]

[msg MSG_009_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 2 65535 0 0][uf 3 1 1 0 0 20 0 0]¿Q-qué acabas de decir?[n][uf 1 1][e]

[msg MSG_010_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 4 2 65535 0 0][uf 3 1 1 0 0 21 0 0]¡¿Junpei?![n][uf 1 1][e]

[msg MSG_011_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 2 65535 0 0][uf 3 1 1 0 0 22 0 0]¿Chidori está...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 2 65535 0 0][uf 3 1 1 0 0 23 0 0]¿Eh? ¿E-es una broma? ¿Me estáis tomando el pelo?[n][uf 1 1][e]

[msg MSG_012_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 2 65535 0 0][uf 3 1 1 0 0 24 0 0]No, no es ninguna broma. Ahora mismo, se está recuperando en el mismo hospital de la otra vez.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 2 65535 0 0][uf 3 1 1 0 0 25 0 0][uf 4 23 0 5 3 25 25]Pero, Junpei... Puede que ella...[n][uf 1 1][e]

[msg MSG_013_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 2 65535 0 0][uf 3 1 1 0 0 26 0 0]Chidori...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 2 65535 0 0][uf 3 1 1 0 0 27 0 0]¿Chidori está... viva?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 2 2 65535 0 0][uf 3 1 0 0 0 28 0 0][uf 4 23 0 3 2 25 25]...[n][uf 1 1][e]

[msg MSG_014_0_0 [Voz de Yukari]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 29 0 0]¡Oye, espera, Junpei! ¡¿Y tus tareas de limpieza?![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 30 0 0]Jolín, ¿qué mosca le ha picado?[n][uf 1 1][e]

[msg MSG_015_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 6 2 65535 0 0][uf 3 1 1 0 0 31 0 0]Bueno, supongo que ya no importa.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 2 65535 0 0][uf 3 1 1 0 0 32 0 0][uf 4 23 0 5 0 25 25]Quizá haya sido lo mejor que se haya enterado así.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 2 65535 0 0][uf 3 1 1 0 0 33 0 0][uf 4 23 0 5 0 25 25]Creo que iré al hospital yo también. ¿Te importaría venir conmigo?[n][uf 1 1][e]

[msg MND_016_0_0]
[uf 0 5 65278][uf 2 1]Hemos decidido ir juntas al hospital Memorial de Tatsumi.[n][uf 1 1][e]

