[msg MND_000_0_0]
[uf 0 5 65278][uf 2 1]¿Con quién debería quedar...?[n][uf 1 1][e]

[msg MND_000_5_0]
[uf 0 5 65278][uf 2 1]¿Debería pasar tiempo con [uf 2 4 0]...?[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]Has pasado tiempo con Mitsuru[uf 4 27 5 0][e]
[uf 0 5 65278][uf 2 1]Has pasado tiempo con Yuko[uf 4 27 106 0][e]
[uf 0 5 65278][uf 2 1]Has pasado tiempo con Yukari[uf 4 27 2 0][e]
[uf 0 5 65278][uf 2 1]Has pasado tiempo con Fuuka[uf 4 27 6 0][e]
[uf 0 5 65278][uf 2 1]Has pasado tiempo con Chihiro[uf 4 27 109 0][e]
[uf 0 5 65278][uf 2 1]Pasar tiempo sola[e]

[msg MND_002_0_0]
[uf 0 5 65278][uf 2 1]¿Debería rechazar la invitación y pasar tiempo sola?[n][uf 1 1][e]

[msg MND_003_0_0]
[uf 0 5 65278][uf 2 1]¿Debería rechazar las invitaciones y pasar tiempo sola?[n][uf 1 1][e]

[sel SEL_004_0_0 top]
[uf 0 5 65278][uf 2 1]Reconsiderar[e]
[uf 0 5 65278][uf 2 1]Rechazar educadamente[e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]恋人がいないと選択肢を表示出来ません。[n][uf 1 5 0]エディタを使用して恋人を設定してください。[n][uf 1 1][e]

