[msg MSG_000_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 2 65535 0 0][uf 3 1 1 0 0 1 0 0]¿Quedan más?[n][uf 1 1][e]

[msg MSG_001_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 51 65535 0 0][uf 3 1 1 0 0 2 0 0]Tranquila, ya se ha acabado todo.[n][uf 1 1][e]

[msg MSG_002_0_0 [Natsuki Moriyama]]
[uf 0 5 65278][uf 2 1][uf 4 5 223 3 1 65535 0 0][uf 3 1 1 0 0 3 0 0]Fuuka..., tú...[n][uf 1 1][e]

[msg MSG_003_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 2 65535 0 0][uf 3 1 1 0 0 4 0 0]¿Estás bien?[n][uf 1 1][e]

[msg MSG_004_0_0 [Natsuki Moriyama]]
[uf 0 5 65278][uf 2 1][uf 4 5 223 3 1 65535 0 0][uf 3 1 1 0 0 5 0 0]Sí...[n][uf 1 1][e]

[msg MSG_005_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 2 65535 0 0][uf 3 1 1 0 0 6 0 0]Menos mal...[n][uf 1 1][e]

[msg MSG_006_0_0 [Natsuki Moriyama]]
[uf 0 5 65278][uf 2 1][uf 4 5 223 8 1 65535 0 0][uf 3 1 1 0 0 7 0 0]¡¿Fuuka?![n][uf 1 1][e]

[msg MSG_007_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 65535 0 0][uf 3 1 1 0 0 8 0 0]No te preocupes, solo está cansada.[n][uf 1 1][e]

[msg MSG_008_0_0 [Natsuki Moriyama]]
[uf 0 5 65278][uf 2 1][uf 4 5 223 3 1 65535 0 0][uf 3 1 1 0 0 9 0 0]Fuuka...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 223 64 1 65535 0 0][uf 3 1 1 0 0 10 0 0][uf 4 23 0 223 10 25 25]Fuuka, yo...[n][uf 1 1][e]

[msg MSG_009_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 51 65535 0 0][uf 3 1 1 0 0 11 0 0]¿De dónde han salido esas dos sombras?[n][uf 1 1][e]

[msg MSG_010_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 65535 0 0][uf 3 1 1 0 0 12 0 0]De fuera de la Tártaro, igual que en la residencia y el monorraíl.[n][uf 1 1][e]

[msg MSG_011_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 3 51 65535 0 0][uf 3 1 1 0 0 13 0 0]Vaya...[n][uf 1 1][e]

[msg MSG_012_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 51 65535 0 0][uf 3 1 1 0 0 14 0 0]Mm, ¿qué hacemos con Moriyama? Conoce la existencia de la Hora Oscura y las sombras.[n][uf 1 1][e]

[msg MSG_013_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 51 65535 0 0][uf 3 1 1 0 0 15 0 0]Da igual. No es como nosotros, así que no recordará nada de lo que pase durante la Hora Oscura.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 51 65535 0 0][uf 3 1 1 0 0 16 0 0]La buena noticia es que no ha sucumbido a las sombras a pesar de haber oído su llamada.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 51 65535 0 0][uf 3 1 1 0 0 17 0 0]Así que no creo que vuelva a sentirse atraída. Ahora está a salvo.[n][uf 1 1][e]

[msg MSG_014_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 51 65535 0 0][uf 3 1 1 0 0 18 0 0]Pero entonces, ¿olvidará que Yamagishi la ha salvado?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 51 65535 0 0][uf 3 1 1 0 0 19 0 0]Algo no cuadra.[n][uf 1 1][e]

[msg MSG_015_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 51 65535 0 0][uf 3 1 1 0 0 20 0 0]En realidad, tengo la sensación de que todo saldrá bien.[n][uf 1 1][e]

[msg MSG_016_0_0 [Natsuki Moriyama]]
[uf 0 5 65278][uf 2 1][uf 4 5 223 64 1 65535 0 0][uf 3 1 1 0 0 21 0 0]Lo siento, Fuuka. Lo siento mucho.[n][uf 1 1][e]

[msg MSG_017_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 65535 0 0][uf 3 1 1 0 0 22 0 0]Parece que ha aprendido la lección.[n][uf 1 1][e]

[msg MSG_018_0_0 [Natsuki Moriyama]]
[uf 0 5 65278][uf 2 1][uf 4 5 223 64 1 65535 0 0][uf 3 1 1 0 0 23 0 0]Lo siento...[n][uf 1 1][e]

[msg MND_019_0_0]
[uf 0 5 65278][uf 2 1]No ha sido fácil, pero hemos rescatado a Fuuka Yamagishi.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Ha vuelto a aparecer el chico misterioso.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Parece que sus advertencias no forman parte de un sueño.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Pero estoy demasiado cansada como para encontrarle explicación.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Debería echarme un rato en cuanto llegue a la residencia.[n][uf 1 1][e]

