[msg MND_000_0_0]
[uf 0 5 65278][uf 2 1]Estoy en la mazmorra de Shinagawa...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Veo a Maya.[n][uf 1 1][e]

[msg MSG_001_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17002 0 0]ayer fui al gimnsio a hcer ejercicio! =D[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]tngo agujetas, pro stoy mazadísima! ;)[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]no hay nda q no cureun chute de ndorfinas, vrdad?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]ay (q dolorrrrrrrr)[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]la vrdad es q solo fui xq stabaenfdadísima cn ese capullo! ＞=/[n][uf 1 1][e]

[sel SEL_002_0_0 top]
[uf 0 5 65278][uf 2 1]Tranquilízate.[e]
[uf 0 5 65278][uf 2 1]¡Qué desgraciado![e]

[msg MSG_003_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17005 0 0]tiens razón, voy a calmarmy ya está -_- rspira... inspira...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]nooooooo! no me lo saco de la cabeza!! x_x[n][uf 1 1][e]

[msg MND_004_0_0]
[uf 0 5 65278][uf 2 1]Maya parece molesta.[n][uf 1 1][e]

[msg MSG_005_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17004 0 0][uf 5 13 10 15 1]jo, per2na ^^;; hoy no m he lavdo la boca cn jabón ＞_＞[n][uf 1 1][e]

[msg MND_006_0_0]
[uf 0 5 65278][uf 2 1]Maya parece estar avergonzada.[n][uf 1 1][e]

[msg MSG_007_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17005 0 0]qería dcir q estoy picada cn un tío...[n][uf 1 1][e]

[msg MSG_008_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17005 0 0]t acuerdas dl Sr. E? (el HDP)[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]ps cometí 1 pqño error n el libro dcalificaciones y vnga tocarm las narices[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]"s supon q tiens q dar ejemplo", m dijo ＞=/ calla, viejo roñoso!!![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]se cree mejor x serprfesor de historia, pffff[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]acaso no sbe quién soy yo? soy maya,vejestorio d mierda! (^_^) xD[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]si el Sr. E empieza a jugar a esto,voy a mterle en la lista de ignora2 xD[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]tú tmpoco pueds hablar cn él, vale?jejjejejejjje... taguantas![n][uf 1 1][e]

[msg MND_009_0_0]
[uf 0 5 65278][uf 2 1]Maya está confiando en mí.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Tengo la sensación de que estamos estrechando lazos.[n][uf 1 1][e]

[msg MSG_010_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0][uf 3 1 3 0 65535 17005 0 0]d tdas forms, no creo q el Sr. E tngaordnador en su casa ... ＞_＞[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]seguro q usa un ábaco cmo buen prfesord historia q es! xD m parto y m mondo[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]uf... mucho mjor. creo qm voy a dar una ducha, jij[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 65535 0 0]no t preocups! no voy a djar q ese vejestorio m hunda, la-la!! ^_^[n][uf 1 1][e]

[msg MND_011_0_0]
[uf 0 5 65278][uf 2 1]La jugadora Maya se ha desconectado.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]He decidido desconectarme también.[n][uf 1 1][e]

