[msg MSG_SENDER_NAME]
[uf 0 5 65278][uf 2 1]Junpei Iori[n][uf 1 1][e]

[msg MSG_001_0_0]
[uf 0 5 65278][uf 2 1]¡ey![n][uf 1 1][e]

[msg MSG_002_0_0]
[uf 0 5 65278][uf 2 1]oye, que nunca nos ha dado por quedar un día[uf 1 3 138][n]es buen momento para darnos un respiro, qué te parece si vamos a divertirnos por ahí? estaré por el aula, así que avísame si te mola la idea [uf 1 3 137][n][uf 1 1][e]

[msg MSG_003_0_0]
[uf 0 5 65278][uf 2 1]hay que aprovechar el verano! [uf 1 3 140][n][uf 1 1][e]

[msg MSG_004_0_0]
[uf 0 5 65278][uf 2 1]si te pasas el verano sin hacer nada, se esfumarán las vacaciones antes de que te des cuenta![uf 1 3 138] tía, tienes que ayudarme con mi estupendísimo plan [uf 1 3 135] así que ven cagando leches a la zona de tiendas! [uf 1 3 140][n][uf 1 1][e]

[msg MSG_005_0_0]
[uf 0 5 65278][uf 2 1]cómo va eso?[n][uf 1 1][e]

[msg MSG_006_0_0]
[uf 0 5 65278][uf 2 1]ha pasado de todo y me preguntaba cómo andas. nos vamos por ahí a comer algo y cambiamos de aires?[n][uf 1 1][e]

[msg MSG_007_0_0]
[uf 0 5 65278][uf 2 1](Sin asunto)[n][uf 1 1][e]

[msg MSG_008_0_0]
[uf 0 5 65278][uf 2 1]andas libre hoy?[n][uf 1 1][e]

[msg MSG_009_0_0]
[uf 0 5 65278][uf 2 1]Cómo va eso[n][uf 1 1][e]

[msg MSG_010_0_0]
[uf 0 5 65278][uf 2 1]todo bien, tía? [uf 1 3 137] échate la tarde conmigo después de clase [uf 1 3 136][n][uf 1 1][e]

[msg MSG_011_0_0]
[uf 0 5 65278][uf 2 1]verano! [uf 1 3 140][uf 1 3 140][uf 1 3 140][n][uf 1 1][e]

[msg MSG_012_0_0]
[uf 0 5 65278][uf 2 1]tía, hace un calor que te torras. quieres ir a refrescarte al cine? vamos a ver una peli de héroes chula y así nos relajamos un poco. dicen que solo hay una sesión, así que avísame si te apetece[n][uf 1 1][e]

[msg MSG_013_0_0]
[uf 0 5 65278][uf 2 1]eyyyy [uf 1 3 138][n][uf 1 1][e]

[msg MSG_014_0_0]
[uf 0 5 65278][uf 2 1]tía, pero tú miras tus mensajes o qué? no me dejes colgado, mujer [uf 1 3 133] tenemos que quedar pronto [uf 1 3 136][n][uf 1 1][e]

[msg MSG_015_0_0]
[uf 0 5 65278][uf 2 1]holaaaa [uf 1 3 138][uf 1 3 138][uf 1 3 138][n][uf 1 1][e]

[msg MSG_016_0_0]
[uf 0 5 65278][uf 2 1]has recibido mi último mensaje? solo faltas tú en mi plan de verano, colega! estaré en la zona de tiendas, así que vente en cuanto leas esto [uf 1 3 140][n][uf 1 1][e]

[msg MSG_017_0_0]
[uf 0 5 65278][uf 2 1]vamos a las aguas termales![n][uf 1 1][e]

[msg MSG_018_0_0]
[uf 0 5 65278][uf 2 1]vamos a ir! sin peros ni condiciones! es más, tenemos que ir! ven a verme cuando estés libre[n][uf 1 1][e]

[msg MSG_019_0_0]
[uf 0 5 65278][uf 2 1]nos vamos por ahí a papear?[n][uf 1 1][e]

[msg MSG_020_0_0]
[uf 0 5 65278][uf 2 1]vamos a comer juntos[n]podemos ir cuando tengas tiempo[n][uf 1 1][e]

[msg MSG_021_0_0]
[uf 0 5 65278][uf 2 1]oye[n][uf 1 1][e]

[msg MSG_022_0_0]
[uf 0 5 65278][uf 2 1]perdón si sueno a disco rayado, pero tengo que hablar contigo de algo. así que... por favor, escucha lo que tengo que decir[n][uf 1 1][e]

[msg MSG_023_0_0]
[uf 0 5 65278][uf 2 1]qué pasaaa [uf 1 3 140][n][uf 1 1][e]

[msg MSG_024_0_0]
[uf 0 5 65278][uf 2 1]oye, avísame si hoy tienes tiempo [uf 1 3 136][n][uf 1 1][e]

