[msg MSG_000_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]*slurp* *slurp*[n][uf 1 1][e]

[msg MSG_000_3_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]Whew! Now that's what I'm talkin' about![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]Well, was I right, or was I right? The soup here tastes great, doesn't it?[n][uf 1 1][e]

[msg MSG_000_5_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 2 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]They've gotta put some special ingredient in it—something no other ramen shop would ever use.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 3 65535 65535 0 0][uf 3 1 1 0 0 5 0 0][uf 4 23 0 101 3 25 25]Maybe there's a secret clue in the shop's name...[n][uf 1 1][e]

[msg MSG_001_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]Ah, my bad.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]I always geek out a little whenever I eat here.[n][uf 1 1][e]

[sel SEL_002_0_0 top]
[uf 0 5 65278][uf 2 1]I know what you mean.[e]
[uf 0 5 65278][uf 2 1]Just shut up and eat.[e]

[msg MSG_003_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0][uf 3 1 1 0 0 8 0 0]You do? Really? You taste the magic, too?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0][uf 3 1 1 0 0 9 0 0]Man, wasn't expecting that. I think I'm liking you more by the minute.[n][uf 1 1][e]

[msg MSG_004_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]Ah, yeah, you're right. The noodles'll get soggy if we talk too long.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0][uf 3 1 1 0 0 11 0 0]It's just... the way you're savoring your soup, it seems like you really appreciate its flavor.[n][uf 1 1][e]

[msg MSG_005_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]By the way, I hear you and Takeba-san are pretty close.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]Damn, and you just transferred here, too![n][uf 1 1][e]

[msg MSG_005_3_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 1 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]Well, I can't blame you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0][uf 3 1 1 0 0 15 0 0][uf 4 23 0 101 0 25 25]Hey, let's hang out after school again sometime. Lemme know when you're free.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 1 65535 65535 0 0][uf 3 1 1 0 0 16 0 0][uf 4 23 0 101 1 25 25]I'll tell you all about my secret plan. You're gonna flip when you hear it![n][uf 1 1][e]

[msg MND_006_0_0]
[uf 0 5 65278][uf 2 1]Kenji Tomochika seems to[n]have taken a liking to me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]...!?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]A voice is ringing inside my head...[n][uf 1 1][e]

[msg SYS_007_0_0]
[uf 0 5 65278][uf 2 1]DEV: Unused label.[n][uf 1 1][e]

[msg MSG_008_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 4 65535 65535 0 0][uf 3 1 1 0 0 17 0 0]What, it's already dark? Damn, I missed my favorite show![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 6 65535 65535 0 0][uf 3 1 1 0 0 18 0 0][uf 4 23 0 101 3 25 25]Man, for real...? Oh, well, let's get going.[n][uf 1 1][e]

[msg MSG_008_3_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0][uf 3 1 1 0 0 19 0 0]Ah, but first, let's swap numbers. Bust out that cell phone![n][uf 1 1][e]

[msg SYS_008_5_0]
[uf 0 5 65278][uf 2 1]DEV: Unused label.[n][uf 1 1][e]

[msg MND_009_0_0]
[uf 0 5 65278][uf 2 1]I decided to return to the dorm.[n][uf 1 1][e]

