[msg MSG_000_0_0 [Lazy Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]Everyone I know is in a club, but...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]...I just can't be bothered to join one.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]They all say I'll make a lot of friends and all that, but...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]...I say, whatever.[n][uf 1 1][e]

[msg MSG_001_0_0 [Lazy Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]I can't understand why people are freaking out over those ghost stories.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]I mean, running around school screaming and spreading rumors...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]They all need to just grow up.[n][uf 1 1][e]

[msg MSG_002_0_0 [Lazy Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]It's almost summer vacation.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]I used to love summer vacation when I was a kid...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]But now it's like, whatever. I just don't get excited about it anymore.[n][uf 1 1][e]

[msg MSG_003_0_0 [Lazy Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]Culture festival this, culture festival that...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]Everyone just loooves the culture festival![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]But not me, dude. I think it's a waste of time.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]I hope there's a typhoon or something so they'll have to cancel it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]...Maybe that's a bit much, huh?[n][uf 1 1][e]

[msg MSG_004_0_0 [Lazy Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]Wh-What!? I haven't done anything wrong![n][uf 1 1][e]

[sel SEL_005_0_0 top]
[uf 0 5 65278][uf 2 1]I didn't say nothing.[e]
[uf 0 5 65278][uf 2 1]Whatever you say.[e]
[uf 0 5 65278][uf 2 1]IT WAS YOU..![e]

[msg MSG_006_0_0 [Lazy Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]Wait, you're not here about... that?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]Phew... Don't scare me like that.[n][uf 1 1][e]

[msg MSG_007_0_0 [Lazy Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]Yeah, that's right. No one has to know.[n][uf 1 1][e]

[msg MSG_008_0_0 [Lazy Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]I... I mean, I did wish for the typhoon.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]I even hung voodoo dolls upside down with lots of needles stuck in their heads.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]But I didn't think a typhoon would really come! It was an accident![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]It's not my fault![n][uf 1 1][e]

[msg MSG_009_0_0 [Lazy Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]Man, Kirijo-san is impressive.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]Her dad just died, but she still went to a meeting about the future of the Kirijo Group.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]She's a real go-getter, that one.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]I wish I could be like that... Ah, who am I kidding? I like being lazy.[n][uf 1 1][e]

[msg MSG_010_0_0 [Lazy Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]Dude, what's the deal with career experience?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]They made me carry cardboard boxes around all day...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]My arms are friggin' killing me.[n][uf 1 1][e]

[msg MSG_011_0_0 [Lazy Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]Man... I don't feel like doing anything.[n][uf 1 1][e]

[sel SEL_012_0_0 top]
[uf 0 5 65278][uf 2 1]I understand...[e]
[uf 0 5 65278][uf 2 1]Keep pushing on, you idiot.[e]

[msg MSG_013_0_0 [Lazy Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]You know what I mean, right?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]It's like everything is this huge waste of time now... I think the world should just end.[n][uf 1 1][e]

[msg MSG_014_0_0 [Lazy Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]But doing things is hard... How do you do it?[n][uf 1 1][e]

[msg MSG_015_0_0 [Lazy Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]As long as you pass your exams, you'll be fine.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]But I never study for my exams 'cause I'm too lazy.[n][uf 1 1][e]

[msg MSG_016_0_0 [Lazy Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]Last time I was hanging out at the strip mall, I saw a dude with a wild fashion sense.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]Long, wavy hair, no shirt, and tattoos all up and down his arms.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]I know it might be unseasonably warm, but he kinda went overboard...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]But hey, maybe it's cool to let your freak flag fly.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]If I was more like him, not givin' a rip what people think, I wouldn't have a care in the world.[n][uf 1 1][e]

[msg MSG_017_0_0 [Lazy Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]Everyone's making friends these days... I dunno. It seems like a lot of work.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]I know there's an upside to having friends, but...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]I wish there was a way to do it without all that "bonding" stuff, y'know?[n][uf 1 1][e]

[msg MSG_018_0_0 [Lazy Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]Man, I'm so lazy these days.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]Think I've got that Apathy Syndrome thing?[n][uf 1 1][e]

[sel SEL_019_0_0 top]
[uf 0 5 65278][uf 2 1]I doubt it.[e]
[uf 0 5 65278][uf 2 1]Maybe.[e]
[uf 0 5 65278][uf 2 1]Get better soon.[e]

[msg MSG_020_0_0 [Lazy Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]Yeah, I guess it's just plain ol' laziness.[n][uf 1 1][e]

[msg MSG_021_0_0 [Lazy Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]Dude, I was just kidding. Don't take it so seriously, man.[n][uf 1 1][e]

[msg MSG_022_0_0 [Lazy Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]H-Hey, I was just kidding![n][uf 1 1][e]

[msg MSG_023_0_0 [Lazy Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]On hot days like this, you gotta go to the manga café. It's nice and cool, and you can read all the manga you want.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]They have PCs to access the Internet there, too.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]Oh, that reminds me... Sometimes I see that weird guy there...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]He's always banging away on that little laptop of his, muttering to himself...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]And he's always got that briefcase, too... Is he, like, a day trader or something?[n][uf 1 1][e]

[msg MSG_024_0_0 [Lazy Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]Isn't the town messy these days?[n][uf 1 1][e]

[sel SEL_025_0_0 top]
[uf 0 5 65278][uf 2 1]Sure is.[e]
[uf 0 5 65278][uf 2 1]Is it?[e]
[uf 0 5 65278][uf 2 1]I like it this way.[e]

[msg MSG_026_0_0 [Lazy Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]Right? Right? The people are weird these days, too...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]I'm already lazy, but I think I'm going to get even lazier...[n][uf 1 1][e]

[msg MSG_027_0_0 [Lazy Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]I'm telling you, man...[n][uf 1 1][e]

[msg MSG_028_0_0 [Lazy Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]Uh, you're messed up. Did something bad happen to you?[n][uf 1 1][e]

[msg MSG_029_0_0 [Lazy Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]Man, school has started... I'm so lazy.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]Why? Listen, I don't need a reason to be lazy. Besides, everyone gets like this after days off.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]It's the truth, man.[n][uf 1 1][e]

[msg MSG_030_0_0 [Lazy Student]]
[uf 0 5 65278][uf 2 1]I heard some guy made friends with some workers, but isn't that a waste of time?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]I'm fine being a customer. I don't need to be "friends" too, you know?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]I mean, I'm sure there's an upside to it, but... I'll pass anyway.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]Too much trouble...[n][uf 1 1][e]

[msg MSG_031_0_0 [Lazy Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]Dude, check this out. There's lazy people all over.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]What's going through their minds? Nothing, I guess...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]I'm so jealous, man. I wanna be just like them.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]I'm already naturally lazy, so I've got a head start on achieving total blankness of mind![n][uf 1 1][e]

[msg MSG_032_0_0 [Lazy Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]You sure see a lot of couples during summer vacation, huh?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]Maybe I should get a girlfriend... It's a lot of trouble, though.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]Like just now, I saw a couple having an argument, and the girl was like...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]"I'm gonna report you to that revenge website!"[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]What was she even talking about?[n][uf 1 1][e]

[msg MSG_033_0_0 [Lazy Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]*sigh* I'm so lazy...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]Guess why...[n][uf 1 1][e]

[sel SEL_034_0_0 top]
[uf 0 5 65278][uf 2 1]Second term started?[e]
[uf 0 5 65278][uf 2 1]Is it the heat?[e]
[uf 0 5 65278][uf 2 1]You have Apathy Syndrome?[e]
[uf 0 5 65278][uf 2 1]I have no idea.[e]

[msg MSG_035_0_0 [Lazy Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]Yep. You know me, [uf 4 1]-san.[n][uf 1 1][e]

[msg MSG_036_0_0 [Lazy Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]Well, that too.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]But it's mainly 'cause I'm still stuck in summer vacation mode...[n][uf 1 1][e]

[msg MSG_037_0_0 [Lazy Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]Aww, c'mon. I'm not that bad.[n][uf 1 1][e]

[msg MSG_038_0_0 [Lazy Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]Sheesh, way to kill the conversation. Now I feel even lazier...[n][uf 1 1][e]

[msg MSG_039_0_0 [Lazy Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]That Aragaki guy died at the gang spot, right?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]Sometimes I'll aimlessly wander around there, but...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]I should quit doing that.[n][uf 1 1][e]

[msg MSG_040_0_0 [Lazy Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]The people who believe in the End have at least some energy left...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]I mean, they have enough in them to believe in something, y'know?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 317]I don't even have that much, man. It's over for me.[n][uf 1 1][e]

