[msg MSG_000_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 3 0 65535 1067 0 0]Oh, [uf 4 1]-chan. We were just talking about you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]Let me introduce you to Amada-kun.[n][uf 1 1][e]

[msg MSG_001_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 3 0 65535 7001 0 0]Nice to meet you. My name is Ken Amada.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0]I attend Gekkoukan Elementary School.[n][uf 1 1][e]

[sel SEL_001_5_0 top]
[uf 0 5 65278][uf 2 1]Nice to meet you too.[e]
[uf 0 5 65278][uf 2 1]You're very polite.[e]

[msg MSG_002_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 3 0 65535 2132 0 0]Be friends with him, alright? He's a good kid.[n][uf 1 1][e]

[msg MSG_003_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7063 0 0]Really? I think it's pretty normal to greet someone new like that...[n][uf 1 1][e]

[msg MSG_004_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 3 0 65535 2108 0 0]Elementary school kids these days seem more grown up, huh?[n][uf 1 1][e]

[msg MSG_005_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1001 0 0]Amada-kun drops by the shrine pretty often.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]It's close to our dorm, you know. So if you ever see him, say hello, okay, [uf 4 1]-kun?[n][uf 1 1][e]

[msg MSG_006_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 3 0 65535 7001 0 0]Yukari-san and Junpei-san often help me out.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0]Especially Yukari-san! Her advice is very useful.[n][uf 1 1][e]

[msg MSG_007_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 3 0 65535 1131 0 0]I don't say anything that special, though.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0]Amada-kun is surprisingly reliable. And he's so much more mature than Stupei.[n][uf 1 1][e]

[msg MSG_008_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 3 0 65535 2001 0 0]Hey, you can come to me for advice too, y'know?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0]All your problems and concerns will be solved, 100% satisfaction guaranteed![n][uf 1 1][e]

[msg MSG_009_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7026 0 0]Um, okay... I'll think about it.[n][uf 1 1][e]

[msg MSG_010_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7068 0 0]Oh, hello [uf 4 1]-san.[n][uf 1 1][e]

[msg MSG_011_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1001 0 0]I've been chatting with Amada-kun today, and boy, he really is mature, you know?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]He definitely acts a lot more adult than Junpei.[n][uf 1 1][e]

[msg MSG_012_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 3 0 65535 2036 0 0]Geez, Yuka-tan, that's mean! How 'bout you? You think I'm totally the more mature one, right?[n][uf 1 1][e]

[sel SEL_013_0_0 top]
[uf 0 5 65278][uf 2 1]Yeah, I agree.[e]
[uf 0 5 65278][uf 2 1]Amada's more mature.[e]

[msg MSG_014_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 3 0 65535 2026 0 0]Booyah! You hear that, Yuka-tan? Guess I was right and you were wrong! Ha![n][uf 1 1][e]

[msg MSG_015_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 65535 65535 0 0][uf 3 1 3 0 65535 1022 0 0]Aaaand case in point...[n][uf 1 1][e]

[msg MSG_016_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 65535 65535 0 0][uf 3 1 3 0 65535 2101 0 0]Wait, you too!? You don't gotta lie; because. C'mon, that's messed up, ganging up on me like that...[n][uf 1 1][e]

[msg MSG_017_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 3 0 65535 7038 0 0]Well, to me, Junpei-san is like a grown-up, too.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]He's really tall, and he has a lot of interesting things to say.[n][uf 1 1][e]

[msg MSG_018_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 3 0 65535 2096 0 0]See!? Even Amada says so![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]I guess it takes a certain "maturity" to realize it.[n][uf 1 1][e]

[msg MSG_019_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 65535 65535 0 0][uf 3 1 3 0 65535 1022 0 0]Oh, c'mon! You're basically just making him pity you... Sorry about that, Amada-kun.[n][uf 1 1][e]

[msg MSG_020_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1067 0 0]Oh, [uf 4 1]-chan.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]Amada-kun was just telling us about the elementary school dorm.[n][uf 1 1][e]

[msg MSG_021_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7075 0 0]Speaking of which, [uf 4 1]-san lives in the school dorms too, doesn't she?[n][uf 1 1][e]

[msg MSG_022_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0]Yep, that's right.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]She lives in the same dorm as me, Yuka-tan, and the others.[n][uf 1 1][e]

[msg MSG_023_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 4 65535 65535 0 0][uf 3 1 3 0 65535 7123 0 0]What? It's okay for boys and girls to stay in the same dorm?[n][uf 1 1][e]

[msg MSG_024_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0][uf 3 1 3 0 65535 1061 0 0]Um, actually, it's usually not... But our dorm has some special circumstances.[n][uf 1 1][e]

[msg MSG_025_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0]We're just cool like that. Right, [uf 4 2]?[n][uf 1 1][e]

[msg MSG_026_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 3 0 65535 2067 0 0]What're the rules like at the elementary school dorm?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]Is it less strict, since it's all kids?[n][uf 1 1][e]

[msg MSG_027_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7063 0 0]Hmm... It's normal.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]We have to put away whatever we take out, and we need permission to take food from the fridge.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]Pretty much stuff that's just common sense.[n][uf 1 1][e]

[msg MSG_028_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 65535 65535 0 0][uf 3 1 3 0 65535 2138 0 0]Oh... That sounds more strict than I thought...[n][uf 1 1][e]

[msg MSG_029_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 65535 65535 0 0][uf 3 1 3 0 65535 1022 0 0]...Junpei, why don't you go live at the elementary school dorm and learn some discipline?[n][uf 1 1][e]

[msg MSG_030_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7010 0 0]Hello, [uf 4 1]-san.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]You all come to the shrine quite often, huh? Well, me too, I guess...[n][uf 1 1][e]

[sel SEL_031_0_0 top]
[uf 0 5 65278][uf 2 1]Why're you coming here?[e]
[uf 0 5 65278][uf 2 1]Do you have friends your age?[e]

[msg MSG_032_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7033 0 0]No specific reason... I just feel like I can relax here.[n][uf 1 1][e]

[msg MSG_033_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]Still, it's kind of a weird place for a kid to relax. Are you sure you're in elementary school?[n][uf 1 1][e]

[msg MSG_034_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7033 0 0]Yeah, I do play with my friends sometimes, but I just wasn't in the mood today.[n][uf 1 1][e]

[msg MSG_035_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]I know the feeling. Sometimes, it's nice to just relax in silence, you know?[n][uf 1 1][e]

[msg MSG_036_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]I have to leave soon, though, since I left in the middle of doing my homework to come here.[n][uf 1 1][e]

[msg MSG_037_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 3 0 65535 2074 0 0]Come to think of it, this is where we first met Amada, huh?[n][uf 1 1][e]

[msg MSG_038_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 3 0 65535 7132 0 0]That's right. Junpei-san was the first one who came up to talk to me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0]Then Yukari-san started coming too and offered to help me out with some stuff.[n][uf 1 1][e]

[msg MSG_039_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 3 0 65535 1131 0 0]You know Junpei. He'd get chummy with just about anyone.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0]I was just worried that he might be bothering Amada-kun.[n][uf 1 1][e]

[msg MSG_040_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 65535 65535 0 0][uf 3 1 3 0 65535 2101 0 0]You don't gotta put it like that, Yuka-tan...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0]I mean, anyone would reach out to someone if they looked lonely, right?[n][uf 1 1][e]

