[msg MSG_000_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 1 101 65535 0 0][uf 3 1 1 0 4 1 0 0]Oh! Heh heh...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0][uf 3 1 1 0 4 2 0 0]Sorry, didn't mean to spy, but... you're going out with Yuko, aren't you?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 1 0 4 3 0 0]I noticed she's been way more motivated lately... So you're the reason, huh?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 1 0 4 4 0 0]She even took a look at my knee with this huge book, pointing out all the muscle groups and where I injured it...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 1 101 65535 0 0][uf 3 1 1 0 4 5 0 0]She really knows her stuff now. Guess that's the power of love, eh? Haha.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 1 0 4 6 0 0]...Well, she's a great girl. I'd better not catch you making her cry, alright?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 1 101 65535 0 0][uf 3 1 1 0 4 7 0 0]But I guess I'm the last person you wanna hear that from. Besides, you're not that kinda guy.[n][uf 1 1][e]

[msg MSG_001_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 1 0 4 8 0 0]Oh, right. I wanted to talk to you about something.[n][uf 1 1][e]

[msg MSG_002_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 1 101 65535 0 0][uf 3 1 1 0 4 9 0 0]Oh, good timing, [uf 4 1]! There's something I wanted to talk to you about.[n][uf 1 1][e]

[msg MSG_003_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 1 0 4 10 0 0]I went back to the hospital to get a checkup on my knee.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 1 0 4 11 0 0]The results are in...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0][uf 3 1 1 0 4 12 0 0][uf 4 25 105]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 1 101 65535 0 0][uf 3 1 1 0 4 13 0 0]It's 100% healed! They said I can run all I want now![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 1 101 65535 0 0][uf 3 1 1 0 4 14 0 0]Dude, I was so happy, I almost broke the doctor's back, I hugged him so hard![n][uf 1 1][e]

[msg MSG_004_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 1 0 4 15 0 0]But thinking about it now...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 1 0 4 16 0 0]How would things have gone if I'd kept running through the pain?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 2 101 65535 0 0][uf 3 1 1 0 4 17 0 0]I was pushing too hard, only thinking about myself. I got pissed off when things didn't go my way...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 2 101 65535 0 0][uf 3 1 1 0 4 18 0 0]So I threw out the advice I got, and... shot my knee to hell.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0][uf 3 1 1 0 4 19 0 0]Man, I was such a moron... At least I can see it now.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0][uf 3 1 1 0 4 20 0 0]I kept saying it was all for my nephew, but in the end, it was just about my own damn pride.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0][uf 3 1 1 0 4 21 0 0]I got you, everyone on the team, and my parents all worried about me. And I didn't even stop to notice.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0][uf 3 1 1 0 4 22 0 0]I was a real selfish brat.[n][uf 1 1][e]

[sel SEL_005_0_0 top]
[uf 0 5 65278][uf 2 1]It wasn't an issue.[e]
[uf 0 5 65278][uf 2 1]You were a real idiot.[e]

[msg MSG_006_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 1 101 65535 0 0][uf 3 1 1 0 4 23 0 0]Haha... Thanks, man.[n][uf 1 1][e]

[msg MSG_007_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 1 101 65535 0 0][uf 3 1 1 0 4 24 0 0]Haha... Seriously! It pisses me off just thinking about it.[n][uf 1 1][e]

[msg MSG_008_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 1 0 4 25 0 0]Well, it took me this long, but at least I finally snapped out of it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 1 101 65535 0 0][uf 3 1 1 0 4 26 0 0]Thanks, [uf 4 1]. It's because of you I'm standing here on two feet.[n][uf 1 1][e]

[msg MSG_009_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 1 0 4 27 0 0]I swear, things'll be different from here on out. I wanna repay you all for what you've done for me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 1 0 4 28 0 0]No more stubborn pride. I'm gonna listen to what others have to say... even when it's not what I want to hear.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 1 101 65535 0 0][uf 3 1 1 0 4 29 0 0]Well, that's about it. I just wanted you to be the one I break the news to first.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 1 101 65535 0 0][uf 3 1 1 0 4 30 0 0]I'll run around to the faculty office and club room later to let everyone else know. Have a good one![n][uf 1 1][e]

[msg MSG_010_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0][uf 3 1 1 0 4 31 0 0]...Dude, are you good? You look kinda tired.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0][uf 3 1 1 0 4 32 0 0]Go home and get some rest, good health is the most important part of training.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 1 101 65535 0 0][uf 3 1 1 0 4 33 0 0]We're still signed up for the spring tournament! If you slack off, I'm gonna leave you in the dust![n][uf 1 1][e]

[msg MSG_011_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0][uf 3 1 1 0 4 34 0 0]Man, I had everyone worried sick...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 1 101 65535 0 0][uf 3 1 1 0 4 35 0 0]Well, the Miyamoto family has a saying for times like these! "Nothing repays a debt better than hard work!"[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 1 101 65535 0 0][uf 3 1 1 0 4 36 0 0]Just you watch! Next run I do's gonna be a record breaker![n][uf 1 1][e]

