[msg MSG_000_0_0 [Very Curious Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 305]You know how every school has at least one mystery that no one can solve?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 305]There's one here too, you know...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 305]Like the sculpture in the art room that moves by itself! ...It sounded cooler in my mind...[n][uf 1 1][e]

[msg MSG_001_0_0 [Very Curious Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 305]Hey, have you heard about the ghost in the home ec room?[n][uf 1 1][e]

[sel SEL_002_0_0 top]
[uf 0 5 65278][uf 2 1]Yep.[e]
[uf 0 5 65278][uf 2 1]Nope.[e]

[msg MSG_003_0_0 [Very Curious Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 305]Impressive. You know the school well.[n][uf 1 1][e]

[msg MSG_004_0_0 [Very Curious Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 305]I heard there's a ghost in there, are you okay? Your turning pale... Anyways-[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 305]The sewing machine will be on, but no one's inside... Or you'll hear weird voices coming from in there...[n][uf 1 1][e]

[msg MSG_005_0_0 [Very Curious Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 305]Hey, I read those ghost stories that were being spread around school on the Internet.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 305]You know, the ones about those students who died, became ghosts and ate humans...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 305]Wait, how would anybody know they ate humans? There wouldn't be any remains.[n][uf 1 1][e]

[msg MSG_006_0_0 [Very Curious Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 305]I heard that those students who were sent to the hospital were bullying other students...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 305]Maybe it was their victims who did that to them.[n][uf 1 1][e]

[msg MSG_007_0_0 [Very Curious Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 305]You remember that ghost story about the angry spirit?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 305]Well, I guess there's another version that's different from the one I told you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 305]Did ya know that?[n][uf 1 1][e]

[sel SEL_008_0_0 top]
[uf 0 5 65278][uf 2 1]Not really.[e]
[uf 0 5 65278][uf 2 1]I did.[e]

[msg MSG_009_0_0 [Very Curious Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 305]Well, I'd love to tell you it myself, but I'm kinda shaky on the details.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 305]You know those two girls that are always gossiping in the hallway on the second floor...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 305]I'm sure they know the story inside and out.[n][uf 1 1][e]

[msg MSG_010_0_0 [Very Curious Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 305]I heard it's based on a real incident from ten years ago...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 305]...and they never figured out what happened.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 305]Don't you think that makes the story so much creepier?[n][uf 1 1][e]

[msg MSG_011_0_0 [Very Curious Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 305]Hey, have you ever heard about that creepy place located on the outskirts of Port Island Station?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 305]Well, I accidentally ended up there once. Dude, I was so scared I almost pissed myself.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]It was full of all these scary-looking guys...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 305]From what I heard, they meet there a few times every month on Saturday night.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 305]But, be careful if you go there, you may wanna bring a guy with you; if you do....[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 305]That place is dangerous. Real dangerous.[n][uf 1 1][e]

[msg MSG_012_0_0 [Very Curious Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 305]Have you heard that crazy rumor that's going around online?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 305]Apparently, you can get revenge on someone just by signing up at a website.[n][uf 1 1][e]

[msg MSG_013_0_0 [Very Curious Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 305]That revenge request website might be real, y'know.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 305]I know some guys personally who signed up... Okay, so it was their sister...'s cousin...[n][uf 1 1][e]

[msg MSG_014_0_0 [Very Curious Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 305]Hey, did you know there's an observatory somewhere on campus?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 305]Rumor has it there is one, anyway... But I've never seen anything.[n][uf 1 1][e]

[msg MSG_015_0_0 [Very Curious Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 305]Hey, you want to hear something weird about the observatory?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 305]No one's ever been there. In fact, no one even knows HOW to get there.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 305]It's like no one was meant to go there... ever.[n][uf 1 1][e]

[msg MSG_016_0_0 [Very Curious Student]]
[uf 0 5 65278][uf 2 1]Don't you think there's something strange about the observatory?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 305]I mean, no one has ever heard about anyone actually going inside of it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 305]And, there's no trace of it ever being used.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 305]Well, I guess if no one's ever been inside, then obviously there wouldn't be a trace of it being used...[n][uf 1 1][e]

[msg MSG_017_0_0 [Very Curious Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 305]I gave up trying to learn about the observatory.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 305]Actually, I learned that there's nothing to learn about it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 305]I just can't believe the school built that thing. I mean, why build it if no one's going to use it?[n][uf 1 1][e]

