[msg MSG_000_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 102 65535 0 0][uf 3 1 1 0 4 1 0 0]Woohoo! Thanks, Kirijo-senpai! Right now, I feel like I could die with no regrets![n][uf 1 1][e]

[msg MSG_000_5_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 102 65535 0 0][uf 3 1 1 0 4 1 0 0]C'mon, go after her! Get on your knees, beg for forgiveness, and introduce her to me! Please...?[n][uf 1 1][e]

[msg MSG_001_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 4 1 0 0]Ahaha, I tried my hand at sneaking out... but I still got caught.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 4 2 0 0]Welp, guess we oughta head to our room now.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 1 0 4 3 0 0]C'mon, let's hustle... or else Ms. Toriumi might get pissed at us.[n][uf 1 1][e]

[msg MSG_002_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 65535 65535 0 0][uf 3 1 1 0 4 1 0 0]Guess Kirijo-senpai's still in shock.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 65535 65535 0 0][uf 3 1 1 0 4 2 0 0]If I was in her shoes, I sure as heck wouldn't be in the mood to go on a trip either.[n][uf 1 1][e]

[msg MSG_003_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 155 65535 0 0][uf 3 1 1 0 4 1 0 0]'Sup, [uf 4 2]? Wanna check out the outdoor hot spring?[n][uf 1 1][e]

[sel SEL_004_0_0 top]
[uf 0 5 65278][uf 2 1]Let's go.[e]
[uf 0 5 65278][uf 2 1]Maybe later.[e]

[msg MSG_005_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 155 65535 0 0][uf 3 1 1 0 4 2 0 0]Sweet![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 155 65535 0 0][uf 3 1 1 0 4 3 0 0]I'll grab Sanada-san and Ryoji, so you can head back to the room and get ready.[n][uf 1 1][e]

[msg MSG_006_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 155 65535 0 0][uf 3 1 1 0 4 4 0 0]Whaaat? C'mon.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 155 65535 0 0][uf 3 1 1 0 4 5 0 0]Well, like it or not, you're comin' with me! Just lemme know when you're ready.[n][uf 1 1][e]

[msg MSG_007_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 155 65535 0 0][uf 3 1 1 0 4 6 0 0]I'll grab Sanada-san and Ryoji, so you can head back to the room and get ready.[n][uf 1 1][e]

