[msg MSG_000_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 4 1 0 0]Hello, [uf 4 1]-san. Are you on patrol as well?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 1 65535 65535 0 0][uf 3 1 1 0 4 2 0 0]...Just kidding. I plan on enjoying myself on this trip.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 4 3 0 0]I only hope there won't be any trouble while—[n][uf 1 1][e]

[msg MSG_001_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 4 4 0 0]Hey there, Odagiri-kun! Have you tried these complimentary snacks?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 4 5 0 0]They're sooo tasty![n][uf 1 1][e]

[msg MSG_002_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 4 6 0 0]No, I haven't had the chance—[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 3 65535 65535 0 0][uf 3 1 1 0 4 7 0 0]There's nothing left.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 3 65535 65535 0 0][uf 3 1 1 0 4 8 0 0]Aren't those snacks supposed to be limited to one per person?[n][uf 1 1][e]

[msg MSG_003_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 9 0 0]Oh, really? Oops... I ate them all. Sorry![n][uf 1 1][e]

[msg MSG_004_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 4 10 0 0]...I figured.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 4 11 0 0]I'll just pretend there weren't any in the first place.[n][uf 1 1][e]

[msg MSG_005_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 4 12 0 0]Sorry, Odagiri-kun. I'll check out the gift shop later to see if they'll have more snacks there.[n][uf 1 1][e]

[msg MSG_006_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 3 65535 65535 0 1][uf 3 1 1 0 4 13 0 0]N-No need. It's not like I wanted to try some or anything...[n][uf 1 1][e]

[msg MSG_007_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 4 1 0 0]Hello, [uf 4 1]-san. Are you on patrol as well?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 1 65535 65535 0 0][uf 3 1 1 0 4 2 0 0]...Just kidding. I plan on enjoying myself on this trip.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 4 3 0 0]I only hope there won't be any trouble while—[n][uf 1 1][e]

[msg MSG_008_0_0 [Kind-Looking Upperclassman]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 4 4 0 0]Hey there, Odagiri-kun! Have you tried these complimentary snacks?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 4 5 0 0]They're sooo tasty![n][uf 1 1][e]

[msg MSG_009_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 4 6 0 0]No, I haven't had the chance—[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 3 65535 65535 0 0][uf 3 1 1 0 4 7 0 0]There's nothing left.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 3 65535 65535 0 0][uf 3 1 1 0 4 8 0 0]Aren't those snacks supposed to be limited to one per person?[n][uf 1 1][e]

[msg MSG_010_0_0 [Kind-Looking Upperclassman]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 9 0 0]Oh, really? Augh... I ate them all. Sorry![n][uf 1 1][e]

[msg MSG_011_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 4 10 0 0]...I figured.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 4 11 0 0]I'll just pretend there weren't any in the first place.[n][uf 1 1][e]

[msg MSG_012_0_0 [Kind-Looking Upperclassman]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 4 12 0 0]Sorry, Odagiri-kun. I'll check out the gift shop later to see if they'll have more snacks there.[n][uf 1 1][e]

[msg MSG_013_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 3 65535 65535 0 1][uf 3 1 1 0 4 13 0 0]N-No need. It's not like I wanted to try some or anything...[n][uf 1 1][e]

[msg MSG_014_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 1 0 0][uf 4 1]-san, you're here, too? Oh, right, you're a second-year, huh.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 4 2 0 0]By the way, have you tried these complimentary snacks?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 4 3 0 0]They're sooo tasty![n][uf 1 1][e]

[msg MSG_015_0_0 [Stern-Looking Student]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 3 65535 65535 0 0][uf 3 1 1 0 4 4 0 0]...You know, I haven't had the chance to try any.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 3 65535 65535 0 0][uf 3 1 1 0 4 5 0 0]Care to explain why the plate is empty? Normally, these snacks are limited to one per person.[n][uf 1 1][e]

[msg MSG_016_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 6 0 0]Oh, really? Augh... I ate them all. Sorry![n][uf 1 1][e]

[msg MSG_017_0_0 [Stern-Looking Student]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 4 7 0 0]...I figured.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 4 8 0 0]I'll just pretend there weren't any in the first place.[n][uf 1 1][e]

[msg MSG_018_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 4 9 0 0]Sorry, Odagiri-kun. I'll check out the gift shop later to see if they'll have more snacks there.[n][uf 1 1][e]

[msg MSG_019_0_0 [Stern-Looking Student]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 3 65535 65535 0 1][uf 3 1 1 0 4 10 0 0]N-No need. It's not like I wanted to try some or anything...[n][uf 1 1][e]

[msg MSG_020_0_0 [Stern-Looking Student]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 4 1 0 0]As a member of the disciplinary committee, I need to remain vigilant even on a trip like this.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 4 2 0 0]I only hope there won't be any trouble while—[n][uf 1 1][e]

[msg MSG_021_0_0 [Kind-Looking Upperclassman]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 4 3 0 0]Hey there, Odagiri-kun! Have you tried these complimentary snacks?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 4 4 0 0]They're sooo tasty![n][uf 1 1][e]

[msg MSG_022_0_0 [Stern-Looking Student]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 4 5 0 0]No, I haven't had the chance to—[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 3 65535 65535 0 0][uf 3 1 1 0 4 6 0 0]There's nothing left.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 3 65535 65535 0 0][uf 3 1 1 0 4 7 0 0]Aren't those snacks supposed to be limited to one per person?[n][uf 1 1][e]

[msg MSG_023_0_0 [Kind-Looking Upperclassman]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 8 0 0]Oh, really? Augh... I ate them all. Sorry![n][uf 1 1][e]

[msg MSG_024_0_0 [Stern-Looking Student]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 4 9 0 0]...I figured.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 4 10 0 0]I'll just pretend there weren't any in the first place.[n][uf 1 1][e]

[msg MSG_025_0_0 [Kind-Looking Upperclassman]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 4 11 0 0]Sorry, Odagiri-kun. I'll check out the gift shop later to see if they'll have more snacks there.[n][uf 1 1][e]

[msg MSG_026_0_0 [Stern-Looking Student]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 3 65535 65535 0 1][uf 3 1 1 0 4 12 0 0]N-No need. It's not like I wanted to try some or anything...[n][uf 1 1][e]

[msg MSG_027_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 4 1 0 0]Oh, hey, [uf 4 1]-san. I must say, the tour today wore me out.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 3 65535 65535 0 0][uf 3 1 1 0 4 2 0 0]I was looking forward to going sightseeing around this historical city, but...[n][uf 1 1][e]

[msg MSG_028_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 3 0 0]Yeah, it was one thing after another today.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 4 4 0 0]Some of the older ladies in our tour group passed out right in front of us.[n][uf 1 1][e]

[msg MSG_029_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 4 5 0 0]I'm glad you were there, Keisuke. Thanks to you, the situation wasn't nearly as bad as it could've been.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 4 6 0 0]Nevertheless, it was a shocking turn of events...[n][uf 1 1][e]

[msg MSG_030_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 4 7 0 0]Yeah... Even the tour guide passed out.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 8 0 0]The way you took charge and directed traffic was really impressive though, Odagiri-kun.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 9 0 0]Have you ever considered becoming a police officer in the future?[n][uf 1 1][e]

[msg MSG_031_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 4 10 0 0]Huh...? No, I hadn't given it any thought before.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 4 11 0 0]...Let's head to the hot springs. I'm covered in sweat after that whole ordeal.[n][uf 1 1][e]

[msg MSG_032_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 1 65535 65535 0 0][uf 3 1 1 0 4 12 0 0]You didn't have to get involved in that mess... But I suppose you'll never break your habit of meddling, Keisuke.[n][uf 1 1][e]

[msg MSG_033_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 13 0 0]Haha, the same goes to you. Pretty sure you were the first to leap into action.[n][uf 1 1][e]

[msg MSG_034_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 4 1 0 0]Oh, hey, [uf 4 1]-san. I must say, the tour today wore me out.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 3 65535 65535 0 0][uf 3 1 1 0 4 2 0 0]I was looking forward to going sightseeing around this historical city, but...[n][uf 1 1][e]

[msg MSG_035_0_0 [Kind-Looking Upperclassman]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 3 0 0]Yeah, it was one thing after another today.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 4 4 0 0]Some of the older ladies in our tour group passed out right in front of us.[n][uf 1 1][e]

[msg MSG_036_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 4 5 0 0]I'm glad you were there, Keisuke. Thanks to you, the situation wasn't nearly as bad as it could've been.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 4 6 0 0]Nevertheless, it was a shocking turn of events...[n][uf 1 1][e]

[msg MSG_037_0_0 [Kind-Looking Upperclassman]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 4 7 0 0]Yeah... Even the tour guide passed out.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 8 0 0]The way you took charge and directed traffic was really impressive though, Odagiri-kun.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 9 0 0]Have you ever considered becoming a police officer in the future?[n][uf 1 1][e]

[msg MSG_038_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 4 10 0 0]Huh...? No, I hadn't given it any thought before.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 4 11 0 0]...Let's head to the hot springs. I'm covered in sweat after that whole ordeal.[n][uf 1 1][e]

[msg MSG_039_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 1 65535 65535 0 0][uf 3 1 1 0 4 12 0 0]You didn't have to get involved in that mess... But I suppose you'll never break your habit of meddling, Keisuke.[n][uf 1 1][e]

[msg MSG_040_0_0 [Kind-Looking Upperclassman]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 13 0 0]Ha, the same goes to you. Pretty sure you were the first to leap into action.[n][uf 1 1][e]

[msg MSG_041_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 1 0 0]Hi, [uf 4 1]-kun. How was your tour today?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 2 0 0]We ran into some trouble on ours. I wanted to visit the temples, but...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 4 3 0 0]Some of the older ladies in our tour group passed out right in front of us.[n][uf 1 1][e]

[msg MSG_042_0_0 [Stern-Looking Student]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 4 4 0 0]I'm glad you were there, Keisuke. Thanks to you, the situation wasn't nearly as bad as it could've been.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 4 5 0 0]Nevertheless, it was a shocking turn of events...[n][uf 1 1][e]

[msg MSG_043_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 4 6 0 0]Yeah... Even the tour guide passed out.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 7 0 0]The way you took charge and directed traffic was really impressive though, Odagiri-kun.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 8 0 0]Have you ever considered becoming a police officer in the future?[n][uf 1 1][e]

[msg MSG_044_0_0 [Stern-Looking Student]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 4 9 0 0]Huh...? No, I hadn't given it any thought before.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 4 10 0 0]...Let's head to the hot springs. I'm covered in sweat after that whole ordeal.[n][uf 1 1][e]

[msg MSG_045_0_0 [Stern-Looking Student]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 1 65535 65535 0 0][uf 3 1 1 0 4 11 0 0]You didn't have to get involved in that mess... But I suppose you'll never break your habit of meddling, Keisuke.[n][uf 1 1][e]

[msg MSG_046_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 12 0 0]Haha, the same goes to you. Pretty sure you were the first to leap into action.[n][uf 1 1][e]

[msg MSG_048_0_0 [Kind-Looking Upperclassman]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 2 0 0]It was one thing after another today.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 4 3 0 0]Some of the older ladies in our tour group passed out right in front of us.[n][uf 1 1][e]

[msg MSG_047_0_0 [Stern-Looking Student]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 3 65535 65535 0 0][uf 3 1 1 0 4 1 0 0]It's been a long day... I was looking forward to going sightseeing around this historical city, but...[n][uf 1 1][e]

[msg MSG_049_0_0 [Stern-Looking Student]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 4 4 0 0]I'm glad you were there, Keisuke. Thanks to you, the situation wasn't nearly as bad as it could've been.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 4 5 0 0]Nevertheless, it was a shocking turn of events...[n][uf 1 1][e]

[msg MSG_050_0_0 [Kind-Looking Upperclassman]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 4 6 0 0]Yeah... Even the tour guide passed out.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 7 0 0]The way you took charge and directed traffic was really impressive though, Odagiri-kun.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 8 0 0]Have you ever considered becoming a police officer in the future?[n][uf 1 1][e]

[msg MSG_051_0_0 [Stern-Looking Student]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 4 9 0 0]Huh...? No, I hadn't given it any thought before.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 4 10 0 0]...Let's head to the hot springs. I'm covered in sweat after that whole ordeal.[n][uf 1 1][e]

[msg MSG_052_0_0 [Stern-Looking Student]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 1 65535 65535 0 0][uf 3 1 1 0 4 11 0 0]You didn't have to get involved in that mess... But I suppose you'll never break your habit of meddling, Keisuke.[n][uf 1 1][e]

[msg MSG_053_0_0 [Kind-Looking Upperclassman]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 12 0 0]Haha, well, the same goes to you. Pretty sure you were the first to leap into action.[n][uf 1 1][e]

[msg MSG_054_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 3 65535 65535 0 0][uf 3 1 1 0 4 1 0 0]Hey, [uf 4 1]-san. Do you happen to see any tears in my pants at all?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 3 65535 65535 0 0][uf 3 1 1 0 4 2 0 0]...Maybe that was a bit much, perhaps I shouldn't be asking you...[n][uf 1 1][e]

[msg MSG_055_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 4 3 0 0]The Kamogawa River has a nice ambience, huh?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 4 0 0]You see, Odagiri-kun was trying to skip rocks across its surface, but he lost his footing and—[n][uf 1 1][e]

[msg MSG_056_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 3 65535 65535 0 0][uf 3 1 1 0 4 5 0 0]Can we please drop the topic?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 2 65535 65535 0 0][uf 3 1 1 0 4 6 0 0]Besides, I'd say you're partially at fault for challenging me to hit the opposite bank, Keisuke.[n][uf 1 1][e]

[msg MSG_057_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 7 0 0]Aw... Don't you want to see if it's possible? The wind was blowing in the perfect direction and all.[n][uf 1 1][e]

[msg MSG_058_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 4 8 0 0]What's the point in doing that?[n][uf 1 1][e]

[msg MSG_059_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 4 9 0 0]Because... it'd make me happy?[n][uf 1 1][e]

[msg MSG_060_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 2 65535 65535 0 0][uf 3 1 1 0 4 10 0 0]But I'm asking what good would come out of doing all that? It was still pointless.[n][uf 1 1][e]

[msg MSG_061_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 11 0 0]Don't you remember our elementary school days? We used to practice skipping rocks all the time.[n][uf 1 1][e]

[msg MSG_062_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 3 65535 65535 0 0][uf 3 1 1 0 4 12 0 0]...Yes, but we're in high school now. You're a third-year, for crying out loud.[n][uf 1 1][e]

[msg MSG_063_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 13 0 0]...Looked like you were going all out, though—to the point where you slipped and fell.[n][uf 1 1][e]

[msg MSG_064_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 2 65535 65535 0 0][uf 3 1 1 0 4 14 0 0]...Again, can we please change the subject?[n][uf 1 1][e]

[msg MSG_065_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 15 0 0]Oooh, you're sooo scary, Odagiri-kun.[n][uf 1 1][e]

[msg MSG_066_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 3 65535 65535 0 0][uf 3 1 1 0 4 16 0 0]To think, one of the last memories I make on this trip would make me feel so pathetic...[n][uf 1 1][e]

[msg MSG_067_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 4 17 0 0]It's not a big deal. I guess that other bank was just a bit farther than we thought.[n][uf 1 1][e]

[msg MSG_068_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 3 65535 65535 0 0][uf 3 1 1 0 4 1 0 0]Hey, [uf 4 1]-san, uh... Do you happen to see any tears in my pants at all?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 3 65535 65535 0 0][uf 3 1 1 0 4 2 0 0]...Maybe that was a bit much.[n][uf 1 1][e]

[msg MSG_069_0_0 [Kind-Looking Upperclassman]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 4 3 0 0]The Kamogawa River has a nice ambience, huh?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 4 0 0]You see, Odagiri-kun was trying to skip rocks across its surface, but he lost his footing and—[n][uf 1 1][e]

[msg MSG_070_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 3 65535 65535 0 0][uf 3 1 1 0 4 5 0 0]Can we please drop the topic?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 2 65535 65535 0 0][uf 3 1 1 0 4 6 0 0]Besides, I'd say you're partially at fault for challenging me to hit the opposite bank, Keisuke.[n][uf 1 1][e]

[msg MSG_071_0_0 [Kind-Looking Upperclassman]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 7 0 0]Aw... Don't you want to see if it's possible? The wind was blowing in the perfect direction and all.[n][uf 1 1][e]

[msg MSG_072_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 4 8 0 0]What's the point in doing that?[n][uf 1 1][e]

[msg MSG_073_0_0 [Kind-Looking Upperclassman]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 4 9 0 0]Because... it'd make me happy?[n][uf 1 1][e]

[msg MSG_074_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 2 65535 65535 0 0][uf 3 1 1 0 4 10 0 0]But I'm asking what good would come out of doing all that? It was still pointless.[n][uf 1 1][e]

[msg MSG_075_0_0 [Kind-Looking Upperclassman]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 11 0 0]Don't you remember our elementary school days? We used to practice skipping rocks all the time.[n][uf 1 1][e]

[msg MSG_076_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 3 65535 65535 0 0][uf 3 1 1 0 4 12 0 0]...Yes, but we're in high school now. You're a third-year, for crying out loud.[n][uf 1 1][e]

[msg MSG_077_0_0 [Kind-Looking Upperclassman]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 13 0 0]...It looked like you were going all out, though—to the point where you slipped and fell.[n][uf 1 1][e]

[msg MSG_078_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 2 65535 65535 0 0][uf 3 1 1 0 4 14 0 0]...Again, can we please change the subject?[n][uf 1 1][e]

[msg MSG_079_0_0 [Kind-Looking Upperclassman]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 15 0 0]Oooh, you're sooo scary, Odagiri-kun.[n][uf 1 1][e]

[msg MSG_080_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 3 65535 65535 0 0][uf 3 1 1 0 4 16 0 0]To think, one of the last memories I make on this trip would make me feel so pathetic...[n][uf 1 1][e]

[msg MSG_081_0_0 [Kind-Looking Upperclassman]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 4 17 0 0]It's not a big deal. I guess that other bank was just a bit farther than we thought.[n][uf 1 1][e]

[msg MSG_082_0_0 [Stern-Looking Student]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 3 65535 65535 0 0][uf 3 1 1 0 4 1 0 0]You there. Do you happen to see any tears in my pants at all?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 3 65535 65535 0 0][uf 3 1 1 0 4 2 0 0]...Maybe that was a bit much,*Sigh* should I even be inquiring this of you.[n][uf 1 1][e]

[msg MSG_083_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 4 3 0 0]The Kamogawa River has a nice ambience, huh?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 4 0 0]You see, Odagiri-kun was trying to skip rocks across its surface, but he lost his footing and—[n][uf 1 1][e]

[msg MSG_084_0_0 [Stern-Looking Student]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 3 65535 65535 0 0][uf 3 1 1 0 4 5 0 0]Can we please drop the topic?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 2 65535 65535 0 0][uf 3 1 1 0 4 6 0 0]Besides, I'd say you're partially at fault for challenging me to hit the opposite bank, Keisuke.[n][uf 1 1][e]

[msg MSG_085_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 7 0 0]Aw... Don't you want to see if it's possible? The wind was blowing in the perfect direction and all.[n][uf 1 1][e]

[msg MSG_086_0_0 [Stern-Looking Student]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 4 8 0 0]What's the point in doing that?[n][uf 1 1][e]

[msg MSG_087_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 4 9 0 0]Because... it'd make me happy?[n][uf 1 1][e]

[msg MSG_088_0_0 [Stern-Looking Student]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 2 65535 65535 0 0][uf 3 1 1 0 4 10 0 0]But I'm asking what good would come out of doing all that? It was still pointless.[n][uf 1 1][e]

[msg MSG_089_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 11 0 0]Don't you remember our elementary school days? We used to practice skipping rocks all the time.[n][uf 1 1][e]

[msg MSG_090_0_0 [Stern-Looking Student]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 3 65535 65535 0 0][uf 3 1 1 0 4 12 0 0]...Yes, but we're in high school now. You're a third-year, for crying out loud.[n][uf 1 1][e]

[msg MSG_091_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 13 0 0]...It looked like you were going all out, though—to the point where you slipped and fell.[n][uf 1 1][e]

[msg MSG_092_0_0 [Stern-Looking Student]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 2 65535 65535 0 0][uf 3 1 1 0 4 14 0 0]...Again, can we please change the subject?[n][uf 1 1][e]

[msg MSG_093_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 15 0 0]Oooh, you're sooo scary, Odagiri-kun.[n][uf 1 1][e]

[msg MSG_094_0_0 [Stern-Looking Student]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 3 65535 65535 0 0][uf 3 1 1 0 4 16 0 0]To think, one of the last memories I make on this trip would make me feel so pathetic...[n][uf 1 1][e]

[msg MSG_095_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 4 17 0 0]Hey, it's not a big deal. I guess that other bank was just a bit farther than we thought.[n][uf 1 1][e]

[msg MSG_096_0_0 [Stern-Looking Student]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 3 65535 65535 0 0][uf 3 1 1 0 4 1 0 0]You there. Do you happen to see any tears in my pants at all?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 3 65535 65535 0 0][uf 3 1 1 0 4 2 0 0]...Maybe that was a bit much.[n][uf 1 1][e]

[msg MSG_097_0_0 [Kind-Looking Upperclassman]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 4 3 0 0]The Kamogawa River has a nice ambience, huh?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 4 0 0]You see, Odagiri-kun was trying to skip rocks across its surface, but he lost his footing and—[n][uf 1 1][e]

[msg MSG_098_0_0 [Stern-Looking Student]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 3 65535 65535 0 0][uf 3 1 1 0 4 5 0 0]Can we please drop the topic?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 2 65535 65535 0 0][uf 3 1 1 0 4 6 0 0]Besides, I'd say you're partially at fault for challenging me to hit the opposite bank, Keisuke.[n][uf 1 1][e]

[msg MSG_099_0_0 [Kind-Looking Upperclassman]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 7 0 0]Aw... Don't you want to see if it's possible? The wind was blowing in the perfect direction and all.[n][uf 1 1][e]

[msg MSG_100_0_0 [Stern-Looking Student]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 4 8 0 0]What's the point in doing that?[n][uf 1 1][e]

[msg MSG_101_0_0 [Kind-Looking Upperclassman]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 4 9 0 0]Because... it'd make me happy?[n][uf 1 1][e]

[msg MSG_102_0_0 [Stern-Looking Student]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 2 65535 65535 0 0][uf 3 1 1 0 4 10 0 0]But I'm asking what good would come out of doing all that? It was still pointless.[n][uf 1 1][e]

[msg MSG_103_0_0 [Kind-Looking Upperclassman]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 11 0 0]Don't you remember our elementary school days? We used to practice skipping rocks all the time.[n][uf 1 1][e]

[msg MSG_104_0_0 [Stern-Looking Student]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 3 65535 65535 0 0][uf 3 1 1 0 4 12 0 0]...Yes, but we're in high school now. You're a third-year, for crying out loud.[n][uf 1 1][e]

[msg MSG_105_0_0 [Kind-Looking Upperclassman]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 13 0 0]...It looked like you were going all out, though—to the point where you slipped and fell.[n][uf 1 1][e]

[msg MSG_106_0_0 [Stern-Looking Student]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 2 65535 65535 0 0][uf 3 1 1 0 4 14 0 0]...Again, can we please change the subject?[n][uf 1 1][e]

[msg MSG_107_0_0 [Kind-Looking Upperclassman]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 15 0 0]Oooh, you're sooo scary, Odagiri-kun.[n][uf 1 1][e]

[msg MSG_108_0_0 [Stern-Looking Student]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 3 65535 65535 0 0][uf 3 1 1 0 4 16 0 0]To think, one of the last memories I make on this trip would make me feel so pathetic...[n][uf 1 1][e]

[msg MSG_109_0_0 [Kind-Looking Upperclassman]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 4 17 0 0]It's not a big deal. I guess that other bank was just a bit farther than we thought.[n][uf 1 1][e]

[msg MSG_110_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0]Hey, are my pants dirty?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0]A deer ate the treat I had in my pocket...[n][uf 1 1][e]

[msg MSG_111_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0]I didn't know there were deer in Kyoto. But you know, with the deer treat, Odagiri-kun was...[n][uf 1 1][e]

[msg MSG_112_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0]Can we not talk about it?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0]If you hadn't said you wanted to ride a deer...[n][uf 1 1][e]

[msg MSG_113_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0]Didn't you want to ride it, too? It seems like its horns would make perfect handlebars...[n][uf 1 1][e]

[msg MSG_114_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0]And what would be the point of riding it?[n][uf 1 1][e]

[msg MSG_115_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0]I don't know... It'd be cool?[n][uf 1 1][e]

[msg MSG_116_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0]No, it wouldn't.[n][uf 1 1][e]

[msg MSG_117_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0]But we did all sorts of things like that when we were in elementary school![n][uf 1 1][e]

[msg MSG_118_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0]Yes... And now we're in high school. You're a third-year.[n][uf 1 1][e]

[msg MSG_119_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0]But... the deer treat...[n][uf 1 1][e]

[msg MSG_120_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0]...Can we please change the subject?[n][uf 1 1][e]

[msg MSG_121_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0]You're a scary guy, Odagiri-kun...[n][uf 1 1][e]

[msg MSG_122_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0]Hey, are my pants dirty?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0]A deer ate the treat I had in my pocket...[n][uf 1 1][e]

[msg MSG_123_0_0 [Kind-Looking Upperclassman]]
[uf 0 5 65278][uf 2 1]I didn't know there were deer in Kyoto too. Odagiri-kun, you know, deer crackers...[n][uf 1 1][e]

[msg MSG_124_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0]Can we not talk about it?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0]If you hadn't said you wanted to ride a deer...[n][uf 1 1][e]

[msg MSG_125_0_0 [Kind-Looking Upperclassman]]
[uf 0 5 65278][uf 2 1]Didn't you want to ride it, too? It seems like its horns would make perfect handlebars...[n][uf 1 1][e]

[msg MSG_126_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0]And what would be the point of riding it?[n][uf 1 1][e]

[msg MSG_127_0_0 [Kind-Looking Upperclassman]]
[uf 0 5 65278][uf 2 1]I don't know... It'd be cool?[n][uf 1 1][e]

[msg MSG_128_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0]No, it wouldn't.[n][uf 1 1][e]

[msg MSG_129_0_0 [Kind-Looking Upperclassman]]
[uf 0 5 65278][uf 2 1]But we did all sorts of things like that when we were in elementary school![n][uf 1 1][e]

[msg MSG_130_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0]Yes... And now we're in high school. You're a third-year.[n][uf 1 1][e]

[msg MSG_131_0_0 [Kind-Looking Upperclassman]]
[uf 0 5 65278][uf 2 1]But... the deer treat...[n][uf 1 1][e]

[msg MSG_132_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0]...Can we please change the subject?[n][uf 1 1][e]

[msg MSG_133_0_0 [Kind-Looking Upperclassman]]
[uf 0 5 65278][uf 2 1]You're a scary guy, Odagiri-kun...[n][uf 1 1][e]

[msg MSG_134_0_0 [Stern-Looking Student]]
[uf 0 5 65278][uf 2 1]Hey, are my pants dirty?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]A deer ate the treat I had in my pocket...[n][uf 1 1][e]

[msg MSG_135_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0]I didn't know there were deer in Kyoto too. Odagiri-kun, you know, deer crackers...[n][uf 1 1][e]

[msg MSG_136_0_0 [Stern-Looking Student]]
[uf 0 5 65278][uf 2 1]Can we not talk about it?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]If you hadn't said you wanted to ride a deer...[n][uf 1 1][e]

[msg MSG_137_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0]Didn't you want to ride it, too? It seems like its horns would make perfect handlebars...[n][uf 1 1][e]

[msg MSG_138_0_0 [Stern-Looking Student]]
[uf 0 5 65278][uf 2 1]And what would be the point of riding it?[n][uf 1 1][e]

[msg MSG_139_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0]I don't know... It'd be cool?[n][uf 1 1][e]

[msg MSG_140_0_0 [Stern-Looking Student]]
[uf 0 5 65278][uf 2 1]No, it wouldn't.[n][uf 1 1][e]

[msg MSG_141_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0]But we did all sorts of things like that when we were in elementary school![n][uf 1 1][e]

[msg MSG_142_0_0 [Stern-Looking Student]]
[uf 0 5 65278][uf 2 1]Yes... And now we're in high school. You're a third-year.[n][uf 1 1][e]

[msg MSG_143_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0]But... the deer treat...[n][uf 1 1][e]

[msg MSG_144_0_0 [Stern-Looking Student]]
[uf 0 5 65278][uf 2 1]...Can we please change the subject?[n][uf 1 1][e]

[msg MSG_145_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0]You're a scary guy, Odagiri-kun...[n][uf 1 1][e]

[msg MSG_146_0_0 [Stern-Looking Student]]
[uf 0 5 65278][uf 2 1]Hey, are my pants dirty?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]A deer ate the treat I had in my pocket...[n][uf 1 1][e]

[msg MSG_147_0_0 [Kind-Looking Upperclassman]]
[uf 0 5 65278][uf 2 1]I didn't know there were deer in Kyoto too. Odagiri-kun, you know, deer crackers...[n][uf 1 1][e]

[msg MSG_148_0_0 [Stern-Looking Student]]
[uf 0 5 65278][uf 2 1]Can we not talk about it?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]If you hadn't said you wanted to ride a deer...[n][uf 1 1][e]

[msg MSG_149_0_0 [Kind-Looking Upperclassman]]
[uf 0 5 65278][uf 2 1]Didn't you want to ride it, too? It seems like its horns would make perfect handlebars...[n][uf 1 1][e]

[msg MSG_150_0_0 [Stern-Looking Student]]
[uf 0 5 65278][uf 2 1]And what would be the point of riding it?[n][uf 1 1][e]

[msg MSG_151_0_0 [Kind-Looking Upperclassman]]
[uf 0 5 65278][uf 2 1]I don't know... It'd be cool?[n][uf 1 1][e]

[msg MSG_152_0_0 [Stern-Looking Student]]
[uf 0 5 65278][uf 2 1]No, it wouldn't.[n][uf 1 1][e]

[msg MSG_153_0_0 [Kind-Looking Upperclassman]]
[uf 0 5 65278][uf 2 1]But we did all sorts of things like that when we were in elementary school![n][uf 1 1][e]

[msg MSG_154_0_0 [Stern-Looking Student]]
[uf 0 5 65278][uf 2 1]Yes... And now we're in high school. You're a third-year.[n][uf 1 1][e]

[msg MSG_155_0_0 [Kind-Looking Upperclassman]]
[uf 0 5 65278][uf 2 1]But... the deer treat...[n][uf 1 1][e]

[msg MSG_156_0_0 [Stern-Looking Student]]
[uf 0 5 65278][uf 2 1]...Can we please change the subject?[n][uf 1 1][e]

[msg MSG_157_0_0 [Kind-Looking Upperclassman]]
[uf 0 5 65278][uf 2 1]You're a scary guy, Odagiri-kun...[n][uf 1 1][e]

