[msg MND_000_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]There's something under Koromaru's paw...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I could pick it up if I ask[n]Koromaru to move his paw.[n][uf 1 1][e]

[msg MSG_001_5_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0]Arf?[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]May I see underneath your paw?[e]
[uf 0 5 65278][uf 2 1]It's nothing.[e]

[msg MSG_002_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0]Arf, arf![n][uf 1 1][e]

[msg MND_003_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]It's a red fountain pen... This must be what[n]the young man at the shrine was looking for.[n][uf 1 1][e]

[msg MSG_004_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 0 65535 65535 0 0]Arf![n][uf 1 1][e]

