[msg MSG_000_0_0 [Indifferent Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 309]Being on a diet sucks.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 309]Maybe you didn't notice, but I look different than I used to.[n][uf 1 1][e]

[msg MSG_001_0_0 [Indifferent Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 309]When you go to a new school, you have to worry about where you'll sit, too.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 309]It would suck if you ended up in the front row.[n][uf 1 1][e]

[msg MSG_002_0_0 [Indifferent Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 309]It sucks trying to make new friends when you transfer...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 309]You have to remember everybody's name, and you can't really say no to their offers.[n][uf 1 1][e]

[msg MSG_003_0_0 [Indifferent Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 309]Exams suck, don't they?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 309]You have to study so much and your score gets posted...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 309]And if you do bad, everyone will laugh at you.[n][uf 1 1][e]

[msg MSG_004_0_0 [Indifferent Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 309]Rumors suck, man.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 309]That one about the girl who collapsed is already all over the school.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 309]I hope no one spreads any rumors about me.[n][uf 1 1][e]

[msg MSG_005_0_0 [Indifferent Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 309]It must suck to be a bully...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 309]You have to pretend to be nice so no one gets suspicious.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 309]And if someone finds out, you'd have to be even nicer to them.[n][uf 1 1][e]

[msg MSG_006_0_0 [Indifferent Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 309]It must suck being unconscious...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 309]I mean, you don't even know if you'll wake up or not.[n][uf 1 1][e]

[msg MSG_007_0_0 [Indifferent Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 309]Summer sucks, man.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 309]I sweat so much my shirt gets drenched.[n][uf 1 1][e]

[msg MSG_008_0_0 [Indifferent Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 309]It must suck to be the "new girl."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 309]All the guys hit on you and pressure you right away.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 309]But, Aigis-san seems fine...were you okay?[n][uf 1 1][e]

[msg MSG_009_0_0 [Indifferent Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 309]The cultural festival kinda sucks, don't you think?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 309]I mean, there's always that one person who's so gung ho, and makes everyone else get involved.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 309]By the way, that person is NOT me.[n][uf 1 1][e]

[msg MSG_010_0_0 [Indifferent Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 309]It sucks when a student passes away...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 309]No matter what really happened, there's always rumors.[n][uf 1 1][e]

[msg MSG_011_0_0 [Indifferent Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 309]Exams suck, man.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 309]People completely forgot about that guy Aragaki now that they're studying.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 309]Or, maybe they never cared about his death in the first place.[n][uf 1 1][e]

[msg MSG_012_0_0 [Indifferent Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 309]It must suck being from such an influential family.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 309]I bet some people aren't sad at all about what happened... They just want to make a grab for power.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 309]By the way, did you know the Kirijo Group built this school?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 309]I hope nothing bad happens...[n][uf 1 1][e]

[msg MSG_013_0_0 [Indifferent Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 309]It must suck to move here from another country.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 309]You're always the center of attention.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 309]But, Mochizuki-kun seems to be enjoying it.[n][uf 1 1][e]

[msg MSG_014_0_0 [Indifferent Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 309]So many things happened during the school trip...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 309]People got all crazy and did things they wouldn't normally do.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 309]Glad I didn't participate. Personally, I just stayed in my room; yukata on the entire trip.[n][uf 1 1][e]

[sel SEL_015_0_0 top]
[uf 0 5 65278][uf 2 1]Cool.[e]
[uf 0 5 65278][uf 2 1]Hope you had fun.[e]

[msg MSG_016_0_0 [Indifferent Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 309]H-Hey, well I guess I should've done something crazier, huh.[n][uf 1 1][e]

[msg MSG_017_0_0 [Indifferent Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 309]Christmas sucks.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 309]Behind all those presents, there's a vicious sales war raging.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 309]I wonder how many people commit suicide during Christmas.[n][uf 1 1][e]

[msg MSG_018_0_0 [Indifferent Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 309]New Year's Day sucks.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 309]Everyone expects you to make a resolution...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 309]...even though there's no way you'll keep it.[n][uf 1 1][e]

[msg MSG_019_0_0 [Indifferent Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 309]Choosing a career sucks.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 309]...I'm serious this time.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 309]Shit, what should I do...?[n][uf 1 1][e]

