[msg MSG_000_0_0 [Vain Woman]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 410]Hm? Can I help you? I don't think I've seen you here before...[n][uf 1 1][e]

[msg MSG_001_0_0 [Vain Woman]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 410]Hmmm... Hey, you're adorable.[n][uf 1 1][e]

[msg MSG_002_0_0 [Vain Woman]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 410]Hmmm... Hey, you're adorable.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 410]This club is pretty nice, huh? I come here sometimes, too.[n][uf 1 1][e]

[msg MSG_003_0_0 [Vain Woman]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 410]Huh? Are you looking for a compliment? Sorry, I'm not giving any out either.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 410]You're not charming enough to be worth my time.[n][uf 1 1][e]

[msg MSG_004_0_0 [Vain Woman]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 410]Huh? Are you looking for a compliment? Sorry, I'm not giving any out either.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 410]You're a cute kid, but something's missing...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 410]If you're serious about standing out, maybe a bit more efforts needed.[n][uf 1 1][e]

[msg MSG_005_0_0 [Vain Woman]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 410]Huh? Are you looking for a compliment? Sorry, you don't need mine.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 410]A girl like you must already have a boyfriend. Have him coddle you![n][uf 1 1][e]

[msg MSG_006_0_0 [Vain Woman]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 410]What are you doing, standing there like a lump?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 410]You're about as charming as a rock. I bet the world is tough for someone like you, huh?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 410]Try being a little more charming. It's not too late for you yet...[n][uf 1 1][e]

[msg MSG_007_0_0 [Vain Woman]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 410]I always thought the women in this club weren't that good-looking, but...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 410]You've almost got what it takes to be worth my time.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 410]If you make just a little more effort, I'm sure you'll notice the difference.[n][uf 1 1][e]

[msg MSG_008_0_0 [Vain Woman]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 410]I always thought the women in this club weren't that good-looking, but...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 410]Ahaha... I guess I was wrong.[n][uf 1 1][e]

[msg MSG_009_0_0 [Vain Woman]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 410]Now that it's winter, people are thinking of Christmas.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 410]You must be having trouble, huh?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 410]I bet you wish you could cancel Christmas.[n][uf 1 1][e]

[msg MSG_010_0_0 [Vain Woman]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 410]Now that it's winter, people are thinking of Christmas.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 410]And in your case... Well, I shouldn't say anything.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 410]Maybe it'll work out for you, maybe it won't. My fingers will be crossed for you.[n][uf 1 1][e]

[msg MSG_011_0_0 [Vain Woman]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 410]Now that it's winter, people are thinking of Christmas.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 410]But I bet it's no sweat for you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 410]How many dates have you got lined up?[n][uf 1 1][e]

[msg MSG_012_0_0 [Vain Woman]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 410]Girls who know they're charming have no problem in life.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 410]Especially at times like this... A little charm goes a long way.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 410]You, though... I don't know.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 410]I hope you're relying on something besides charm, that's all I'm saying...[n][uf 1 1][e]

[msg MSG_013_0_0 [Vain Woman]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 410]Girls who know they're charming have no problem in life.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 410]Especially at times like this... A little charm goes a long way.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 410]You, though... I don't know.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 410]You might get by okay.[n][uf 1 1][e]

[msg MSG_014_0_0 [Vain Woman]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 410]Girls who know they're charming have no problem in life.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 410]Especially at times like this... A little charm goes a long way.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 410]I'm sure you know what I mean.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 410]I'd much rather listen to you than those cultist freaks...[n][uf 1 1][e]

