[msg MSG_133_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1093 0 0]I think I'm just going to go out and find something to eat.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0]Sorry... I'm not in much of a cooking mood today.[n][uf 1 1][e]

[msg MND_134_0_0]
[uf 0 5 65278][uf 2 1]Yukari seems upset...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I should work to repair our relationship[n]first, then maybe we could cook together.[n][uf 1 1][e]

[msg MSG_135_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0][uf 3 1 3 0 65535 1077 0 0]I was going to watch this DVD I borrowed, but I don't think I'm up for it today...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0]Maybe some other time...[n][uf 1 1][e]

[msg MND_136_0_0]
[uf 0 5 65278][uf 2 1]Yukari seems upset...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Maybe if I worked to repair our relationship[n]first, we could watch a DVD together...[n][uf 1 1][e]

[msg MSG_000_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1001 0 0]One of my classmates lent me a DVD of this show she's been watching.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]I've been curious about it for a while, and apparently it's gotten some pretty good ratings.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]I could use a break, so I was thinking about sitting down and giving it a watch.[n][uf 1 1][e]

[msg MSG_500_0616_1 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1067 0 0]Hey, [uf 4 1]-chan.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]One of the girls in my class let me borrow a DVD of this show she's been watching.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]I was thinking about watching it in my room, but it might be better to watch it out here since the TV is bigger.[n][uf 1 1][e]

[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]Watching this DVD with Yukari might[n]help improve my [uf 4 30 1 1 1 0]...[n][uf 1 1][e]

[msg MSG_002_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]Oh, what's up, [uf 4 1]-chan? Did you wanna watch with me?[n][uf 1 1][e]

[sel SEL_003_0_0 top]
[uf 0 5 65278][uf 2 1]Yeah, let's watch together.[e]
[uf 0 5 65278][uf 2 1]Maybe later.[e]

[msg MND_Temperance]
[uf 0 5 65278][uf 2 1]Right now, the Temperance Arcana[n]may help me grow even more...[n][uf 1 1][e]

[msg MSG_004_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1001 0 0]I haven't been able to stop thinking about how that show ended last time, so I borrowed the next DVD.[n][uf 1 1][e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]Watching the show with Yukari might[n]help improve my [uf 4 30 1 1 1 0]...[n][uf 1 1][e]

[msg MSG_006_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]So, how about it, [uf 4 1]-kun? You up to watch more of this zombie show with me?[n][uf 1 1][e]

[sel SEL_007_0_0 top]
[uf 0 5 65278][uf 2 1]Let's do this.[e]
[uf 0 5 65278][uf 2 1]Maybe later.[e]

[msg MSG_008_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1002 0 0]This is it. I borrowed the last volume of the series you and I have been watching.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]It's been a wild ride, and while I'm sad the story's ending, I can't wait to watch how they wrap things up.[n][uf 1 1][e]

[msg MND_009_0_0]
[uf 0 5 65278][uf 2 1]Yukari is really looking forward to this...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Watching with her might help[n]improve my [uf 4 30 1 1 1 0]...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Yukari might gain a new ability soon...[n][uf 1 1][e]

[msg MSG_010_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]Well, [uf 4 1]-chan? You ready for the finale?[n][uf 1 1][e]

[sel SEL_011_0_0 top]
[uf 0 5 65278][uf 2 1]Let's do this.[e]
[uf 0 5 65278][uf 2 1]Not now.[e]

[msg MSG_012_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1066 0 0]I borrowed a DVD of another show. I hear this one's supposed to be kinda scary, too.[n][uf 1 1][e]

[msg MND_013_0_0]
[uf 0 5 65278][uf 2 1]It doesn't seem like Yukari will gain any more[n]new skills even if I watch a DVD with her...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]But watching this show with her might[n]help improve my [uf 4 30 1 1 1 0]...[n][uf 1 1][e]

[msg MSG_014_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]How about it? Wanna watch with me?[n][uf 1 1][e]

[sel SEL_015_0_0 top]
[uf 0 5 65278][uf 2 1]Absolutely.[e]
[uf 0 5 65278][uf 2 1]Maybe another time.[e]

[msg MSG_016_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 3 0 65535 1086 0 0]All right, then. Let's get into it![n][uf 1 1][e]

[msg MSG_017_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1061 0 0]Gotcha. Talk to me if you change your mind.[n][uf 1 1][e]

[msg MSG_018_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1098 0 0]Hey, what's up? Ooh, are you actually interested in watching that DVD?[n][uf 1 1][e]

[msg MND_018_3_0]
[uf 0 5 65278][uf 2 1]Watching the show with Yukari might[n]help improve my [uf 4 30 1 1 1 0]...[n][uf 1 1][e]

[msg MSG_018_5_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]I'll go ahead and get it set up.[n][uf 1 1][e]

[msg MSG_019_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1098 0 0]Hey there. Did you still want to watch that show?[n][uf 1 1][e]

[msg MND_019_2_0]
[uf 0 5 65278][uf 2 1]It doesn't seem like Yukari will gain any more[n]new skills even if I watch a DVD with her...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]But watching this show with her might[n]help improve my [uf 4 30 1 1 1 0]...[n][uf 1 1][e]

[msg MSG_019_3_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]I'll go ahead and get it set up.[n][uf 1 1][e]

[msg MND_019_5_0]
[uf 0 5 65278][uf 2 1]Watching the show with Yukari might[n]help improve my [uf 4 30 1 1 1 0]...[n][uf 1 1][e]

[msg MSG_019_7_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]I'll go ahead and get it set up.[n][uf 1 1][e]

[msg MSG_020_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1062 0 0]I got enthusiastic about cooking for myself for once... but I bought way too many ingredients.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0]I am gonna have a lot of leftovers on my hands...[n][uf 1 1][e]

[msg MSG_500_0731_1 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1062 0 0]Since we're getting closer to the day of our mission, I wanted to cook something healthy, but... I bought way too many ingredients.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0]I am gonna have a lot of leftovers on my hands...[n][uf 1 1][e]

[msg MSG_500_1002_1 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1062 0 0]The moon will be full in two days, so I figured I'd cook something hearty...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0]I kind of overestimated how much I would need and bought too many ingredients. Looks like I'll have a lot of leftovers...[n][uf 1 1][e]

[msg MSG_500_1023_1 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1062 0 0]The next battle is going to be our last, so I wanted to cook myself something healthy in preparation.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0]I might have gone a little nuts and overstocked the fridge, though. I'm gonna have a lot of leftovers...[n][uf 1 1][e]

[msg MND_021_0_0]
[uf 0 5 65278][uf 2 1]Looks like Yukari wants[n]me to cook with her...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Should I spend the evening with Yukari?[n][uf 1 1][e]

[msg MSG_022_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 4 1]-chan, will you help me out?[n][uf 1 1][e]

[sel SEL_023_0_0 top]
[uf 0 5 65278][uf 2 1]Sure, I'll help.[e]
[uf 0 5 65278][uf 2 1]Sorry, I'm not hungry.[e]

[msg MSG_024_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1002 0 0]Hey, you got a sec?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]You know that sautéed chicken I messed up last time? I figured out what went wrong. This time, I'm gonna do it right.[n][uf 1 1][e]

[msg MSG_500_0731_2 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1002 0 0]You got a sec?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]You know that sautéed chicken I messed up last time? I figured out what went wrong. This time, I'm gonna do it right.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0]Plus, the next full moon's less than a week away... We deserve to eat something hearty, don't we?[n][uf 1 1][e]

[msg MSG_500_1002_2 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1001 0 0]Hey, [uf 4 1]-chan, do you have a minute?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]You know that sautéed chicken I messed up last time? I figured out what went wrong. This time, I'm gonna do it right.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]...Also, it's almost a full moon, and I could use a task to distract myself.[n][uf 1 1][e]

[msg MSG_500_1023_2 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1067 0 0]Oh, hey, [uf 4 1]-chan.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]I'm thinking about trying my hand at that chicken sauté I messed up last time.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0]And maybe cooking will help me de-stress a little about our final battle coming up. I could use a sous-chef, though.[n][uf 1 1][e]

[msg MND_025_0_0]
[uf 0 5 65278][uf 2 1]Sounds like Yukari wants to cook together.[n][uf 1 1][e]

[msg MSG_026_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]Wanna help? Come on, anyone can do it.[n][uf 1 1][e]

[sel SEL_027_0_0 top]
[uf 0 5 65278][uf 2 1]Let's get cooking.[e]
[uf 0 5 65278][uf 2 1]Maybe later.[e]

[msg MSG_028_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1067 0 0]Hey, [uf 4 1]-chan. Did you eat dinner already?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]I'm thinking about making some food...[n][uf 1 1][e]

[msg MSG_500_0731_3 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1067 0 0]Oh, hey. Have you eaten yet?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]I was just about to get some dinner ready.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0]The full moon's less than a week away, so I thought I'd make something a little healthier.[n][uf 1 1][e]

[msg MSG_500_1002_3 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1001 0 0]Hey, did you already eat dinner?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]I was just about to start cooking...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]Our mission is coming up, so we gotta make sure to eat well.[n][uf 1 1][e]

[msg MSG_500_1023_3 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1078 0 0]Hey, did you already eat dinner, [uf 4 1]-kun?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]I was just about to get started in the kitchen...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]The next mission is gonna be our last. Eating something healthy seems appropriate, all things considered.[n][uf 1 1][e]

[msg MND_029_0_0]
[uf 0 5 65278][uf 2 1]Yukari is all fired up.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Yukari might gain a new ability soon...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Should I spend the evening with her?[n][uf 1 1][e]

[msg MSG_030_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]If you've got time on your hands, do you want to make some food together?[n][uf 1 1][e]

[sel SEL_031_0_0 top]
[uf 0 5 65278][uf 2 1]Sure, let's do it.[e]
[uf 0 5 65278][uf 2 1]Maybe another time.[e]

[msg MSG_032_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1062 0 0]I'm thinking about putting some food together...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0]If you've got some time on your hands, do you want to cook with me?[n][uf 1 1][e]

[msg MSG_500_0731_4 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1062 0 0]Since our operation is coming up, I'm trying to think of something healthy to make.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0]Did you wanna cook together?[n][uf 1 1][e]

[msg MSG_500_1002_4 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1001 0 0]I was thinking about getting to work in the kitchen to take my mind off of things.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0]If you've got some time, we should cook together. What do you say?[n][uf 1 1][e]

[msg MSG_500_1023_4 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1078 0 0]The next battle will be our last... I gotta start preparing myself. Admittedly, I'm pretty nervous.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0]As much as I want some comfort food, I should probably make something healthy. Wanna give me a hand with food prep?[n][uf 1 1][e]

[msg MND_033_0_0]
[uf 0 5 65278][uf 2 1]It doesn't seem like Yukari will gain any[n]more new skills even if I cook with her...[n][uf 1 1][e]

[msg MSG_034_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]How about it? Sous-chef gets the leftovers.[n][uf 1 1][e]

[sel SEL_035_0_0 top]
[uf 0 5 65278][uf 2 1]Alright, let's begin![e]
[uf 0 5 65278][uf 2 1]Maybe another time.[e]

[msg MSG_036_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 3 0 65535 1039 0 0]Awesome. Let's go make something tasty.[n][uf 1 1][e]

[msg MSG_037_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1061 0 0]All right. I'll be here if you change your mind.[n][uf 1 1][e]

[msg MSG_038_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1104 0 0]Oh, hey. Did you want to make something?[n][uf 1 1][e]

[msg MND_038_3_0]
[uf 0 5 65278][uf 2 1]Should I spend the evening with Yukari?[n][uf 1 1][e]

[msg MSG_038_5_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]I'd love it if you could lend me a hand.[n][uf 1 1][e]

[msg MSG_039_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1104 0 0]Hey there. Did you want to spend some time in the kitchen?[n][uf 1 1][e]

[msg MND_040_0_0]
[uf 0 5 65278][uf 2 1]It doesn't seem like Yukari will gain any[n]more new skills even if I cook with her...[n][uf 1 1][e]

[msg MSG_041_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]If you wanted to help out, I'd really appreciate it.[n][uf 1 1][e]

[msg MND_042_0_0]
[uf 0 5 65278][uf 2 1]Should I spend the evening with Yukari?[n][uf 1 1][e]

[msg MSG_043_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]If you wanted to help out, I'd really appreciate it.[n][uf 1 1][e]

