[msg MSG_000_0_0 [Phone-Addicted Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 321]What do you want? I'm using my cell now.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 321]Talk to me when I'm not busy.[n][uf 1 1][e]

[msg MSG_001_0_0 [Phone-Addicted Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 321]Whaddaya want? What, you've never seen a cell phone?[n][uf 1 1][e]

[sel SEL_002_0_0 top]
[uf 0 5 65278][uf 2 1]Of course I have.[e]
[uf 0 5 65278][uf 2 1]Nope.[e]

[msg MSG_003_0_0 [Phone-Addicted Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 321]I thought so.[n][uf 1 1][e]

[msg MSG_004_0_0 [Phone-Addicted Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 321]Really? I've never met anyone who didn't know what a cell phone was before.[n][uf 1 1][e]

[msg MSG_005_0_0 [Phone-Addicted Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 321]Anyway, I'm busy.[n][uf 1 1][e]

[msg MSG_006_0_0 [Phone-Addicted Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 321]Man, the spammers these days annoy the crap out of me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 321]Whatever assholes send this junk to everyone, I hope they send them to prison.[n][uf 1 1][e]

[msg MSG_007_0_0 [Phone-Addicted Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 321]This is kinda random, but...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 321]Isn't it a pain having to reply to messages from people you don't care about?[n][uf 1 1][e]

[sel SEL_008_0_0 top]
[uf 0 5 65278][uf 2 1]Yeah, you're a pain.[e]
[uf 0 5 65278][uf 2 1]It's fine... For me.[e]

[msg MSG_009_0_0 [Phone-Addicted Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 321]Yeah, you got that right... hey.[n][uf 1 1][e]

[msg MSG_010_0_0 [Phone-Addicted Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 321]Sheesh, you're a patient one.[n][uf 1 1][e]

[msg MSG_011_0_0 [Phone-Addicted Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 321]Oh yeah, that girl who passed out? I heard she was by herself when it happened.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 321]Seems mysterious, doesn't it?[n][uf 1 1][e]

[sel SEL_012_0_0 top]
[uf 0 5 65278][uf 2 1]Yeah, I agree.[e]
[uf 0 5 65278][uf 2 1]Dunno.[e]

[msg MSG_013_0_0 [Phone-Addicted Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 321]I know, right?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 321]I don't really care about other people, but if it's a mystery like this, I get pumped.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 321]Like I can't rest until I get to the bottom of it.[n][uf 1 1][e]

[msg MSG_014_0_0 [Phone-Addicted Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 321]Oh, okay.[n][uf 1 1][e]

[msg MSG_015_0_0 [Phone-Addicted Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 321]Three days in a row, we've had students at this school passing out. It's a hell of a mystery.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 321]I'm itching to know more... I should try looking into it.[n][uf 1 1][e]

[msg MSG_016_0_0 [Phone-Addicted Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 321]I thought I could turn up some info, but I didn't find anything at all.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 321]All three passed out, but they were in different grades, and different classes.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 321]Different clubs, too.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 321]So my investigation isn't going very well.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 321]Partly because all their friends were those thugs...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 321]And I obviously don't want to deal with them.[n][uf 1 1][e]

[msg MSG_017_0_0 [Phone-Addicted Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 321]I'm getting bored of calling people up on my phone.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 321]It's fine for trying to kill my boredom, but to be honest, I've run out of stuff to talk about.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 321]Coming up with new stuff to talk about is a pain, too... Ugh, this is such a buzzkill.[n][uf 1 1][e]

[msg MSG_018_0_0 [Phone-Addicted Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 321]I'm thinking about downloading games to my phone, but I don't know...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 321]They say it's cheap, but it all adds up.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 321]Got any recommendations?[n][uf 1 1][e]

[sel SEL_019_0_0 top]
[uf 0 5 65278][uf 2 1]Try a puzzle game.[e]
[uf 0 5 65278][uf 2 1]Try a card game.[e]
[uf 0 5 65278][uf 2 1]Try an RPG.[e]
[uf 0 5 65278][uf 2 1]No idea.[e]

[msg MSG_020_0_0 [Phone-Addicted Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 321]Hmm... Okay, I'll try to remember that.[n][uf 1 1][e]

[msg MSG_021_0_0 [Phone-Addicted Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 321]Oh... Well, whatever.[n][uf 1 1][e]

[msg MSG_022_0_0 [Phone-Addicted Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 321]The admin of the site I'm checking out now is highly respected.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 321]I guess they come off as charismatic? Y'know, having a unique username and everything.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 321]Well, whatever. As long as the site itself is cool, I don't give a flip what kind of admin runs it.[n][uf 1 1][e]

[msg MSG_023_0_0 [Phone-Addicted Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 321]I heard there's a revenge website, but... the URL is top secret, right?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 321]I'm trying to figure it out, so I'm looking all over the web on my cell.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 321]There's a local thread that seems like it has a lot of info on the site.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 321]But it's all garbage info...[n][uf 1 1][e]

[msg MSG_024_0_0 [Phone-Addicted Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 321]My friend asked me for the URL of the revenge website, but I don't know it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 321]But even if I did, why would I tell anyone else?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 321]I'd just keep it to myself.[n][uf 1 1][e]

[msg MSG_025_0_0 [Phone-Addicted Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 321]I tried out that card game for cell phones, but I couldn't get into it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 321]It wasn't hard to understand, it was just too simple.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 321]Oh well... I'll try something else.[n][uf 1 1][e]

[msg MSG_026_0_0 [Phone-Addicted Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 321]Whaddaya want?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 321]I'm playing a shooter on my cell, so buzz off.[n][uf 1 1][e]

[msg MSG_028_0_0 [Phone-Addicted Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 321]Whaddaya want?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 321]I'm playing an RPG on my cell, so buzz off.[n][uf 1 1][e]

[msg MSG_027_0_0 [Phone-Addicted Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 321]I tried out that shooter for cell phones, but I couldn't get into it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 321]It was too tough trying to dodge the bullets on that tiny screen.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 321]Oh well... I'll try something else.[n][uf 1 1][e]

[msg MSG_029_0_0 [Phone-Addicted Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 321]RPGs aren't that bad on cell phones.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 321]One game lasts for a pretty long time, so I guess I'll play it a little while longer.[n][uf 1 1][e]

[msg MSG_030_0_0 [Phone-Addicted Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 321]I was just playing that RPG on my cell, but I think I'm finally getting bored of it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 321]I hope there are more good ones...[n][uf 1 1][e]

[msg MSG_031_0_0 [Phone-Addicted Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 321]What do you want? I'm using my cell now.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 321]This season is so busy, I have to constantly call and message people...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 321]So talk to me some other time.[n][uf 1 1][e]

[msg MSG_032_0_0 [Phone-Addicted Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 321]I used to take a picture whenever I saw one of those Apathy Syndrome people.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 321]I sent them to everyone on my contacts list, saying, "I found an Apathy Syndrome guy!"[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 321]But now, they're as common as oxygen. It's a pretty scary thing to get used to.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 321]Is it going to go away someday, or are we stuck with it forever?[n][uf 1 1][e]

[msg MSG_033_0_0 [Phone-Addicted Student]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 321]Oh man, this sucks... My friend is into that cult stuff.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 321]He keeps texting me these stupid-ass messages![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 321]Like this one, where it just says "Nyx-sama" over and over...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 321]I've gotta figure out how to block his messages...[n][uf 1 1][e]

