[msg MSG_000_0_0 [Bartender]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 20302 0 0][uf 5 21 1 160]Hey, what'll ya ha— Uh, wait a minute. Aren't you a little too young to be in here?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 160]...Well, I guess you can stay if you don't cause any trouble.[n][uf 1 1][e]

[msg MSG_001_0_0 [Bartender]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 20301 0 0][uf 5 21 1 160]What? You want a drink? You're underage, aren't you?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 160]...Oh, it's for the monk upstairs, huh?[n][uf 1 1][e]

[sel SEL_002_0_0 top]
[uf 0 5 65278][uf 2 1]Yep...honest.[e]
[uf 0 5 65278][uf 2 1]I'm just delivering it.[e]

[msg MSG_003_0_0 [Bartender]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 160]So you say... Look, I'm busy here, and something like this could really get me in trouble.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 20304 0 0][uf 5 21 1 160]Okay, how about this? Can you go around and take everyone's orders?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 160]If you do that, I'll bring a drink upstairs for him.[n][uf 1 1][e]

[msg MSG_004_0_0 [Bartender]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 20302 0 0][uf 5 21 1 160]Hey, what'll ya ha— Oh, it's you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 160]You seem to come by a lot... Maybe I'll hire you if we need an extra hand.[n][uf 1 1][e]

[msg MSG_005_0_0 [Bartender]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 20302 0 0][uf 5 21 1 160]Hey, what'll ya ha— Oh, it's you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 160]That monk's not here today. He doesn't usually come on Mondays, Tuesdays, and Wednesdays.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 160]He's probably busy holding services or something.[n][uf 1 1][e]

[msg MSG_006_0_0 [Bartender]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 20301 0 0][uf 5 21 1 160]Oh, you're back.[n][uf 1 1][e]

[msg MSG_007_0_0 [Bartender]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 160]Like I said, I want you to go around and take everyone's orders.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 160]If you can do that, then I'll go ahead and bring him a drink.[n][uf 1 1][e]

[msg MSG_008_0_0 [Bartender]]
[uf 0 5 65278][uf 2 1][uf 5 21 1 160]Like I said before, I want you to go around and take everyone's orders.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 160]If you can do that, then I'll go ahead and bring him a drink.[n][uf 1 1][e]

[msg MSG_009_0_0 [Bartender]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 20301 0 0][uf 5 21 1 160]Oh, it's you. Getting another drink for that monk?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 5 21 1 160]If you've got an order, I can get it ready for him right now.[n][uf 1 1][e]

[sel SEL_010_0_0 top]
[uf 0 5 65278][uf 2 1]Please do.[e]
[uf 0 5 65278][uf 2 1]Not right now.[e]

[msg MSG_011_0_0 [Bartender]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 20305 0 0][uf 5 21 1 160]Got it. Go ahead and let him know it's coming.[n][uf 1 1][e]

[msg MSG_012_0_0 [Bartender]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 20304 0 0][uf 5 21 1 160]Oh, really? All right, well, let me know when he's ready to order.[n][uf 1 1][e]

