[msg MND_000_0_0]
[uf 0 5 65278][uf 2 1]He pasado el tiempo con Maiko en el parque.[n][uf 1 1][e]

[msg MSG_001_0_0 [Maiko]]
[uf 0 5 65278][uf 2 1][uf 4 5 110 1 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]¡Me ruge el estómago! ¿Podemos ir a Wilduck?[n][uf 1 1][e]

[sel SEL_002_0_0 top]
[uf 0 5 65278][uf 2 1]Claro, vamos.[e]
[uf 0 5 65278][uf 2 1]Sigamos jugando.[e]

[msg MSG_003_0_0 [Maiko]]
[uf 0 5 65278][uf 2 1][uf 4 5 110 1 65535 65535 0 0][uf 3 1 1 0 0 2 0 0][uf 5 13 13 15 110]¡Bieeen! ¡Eres la mejor! ¿Cuál será la hamburguesa del día?[n][uf 1 1][e]

[msg MSG_004_0_0 [Maiko]]
[uf 0 5 65278][uf 2 1][uf 4 5 110 2 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]¡Pero ya no tengo fuerzas para jugar! ¡Vamos a comer![n][uf 1 1][e]

