[msg MSG_SENDER_NAME]
[uf 0 5 65278][uf 2 1]Keisuke Hiraga[n][uf 1 1][e]

[msg MSG_001_0_0]
[uf 0 5 65278][uf 2 1]Soy Hiraga.[n][uf 1 1][e]

[msg MSG_002_0_0]
[uf 0 5 65278][uf 2 1]Hola. No sé si te acordarás de mí, pero soy Hiraga, del club de arte.[n]Obviamente, no estás obligado a asistir, pero...[uf 1 3 138][n]Me encantaría que vinieras.[n]Si decides pasarte, estaré en el aula de arte.[uf 1 3 137][n][uf 1 1][e]

[msg MSG_003_0_0]
[uf 0 5 65278][uf 2 1]Soy Hiraga.[n][uf 1 1][e]

[msg MSG_004_0_0]
[uf 0 5 65278][uf 2 1]Oye, ¿vas a asistir a la reunión del club? Sin presión, claro, pero si te interesa, me encantaría volver a pintar contigo.[uf 1 3 137] Tengo material listo para ti por si vienes.[n][uf 1 1][e]

[msg MSG_005_0_0]
[uf 0 5 65278][uf 2 1]Club de arte.[n][uf 1 1][e]

[msg MSG_006_0_0]
[uf 0 5 65278][uf 2 1]Sigues viniendo, y eso debe de significar que estamos haciendo algo bien, ¿no?[uf 1 3 137] Hoy debería haber bastantes miembros, así que estaría bien que vinieras.[uf 1 3 136] Te espero en la sala del club.[n][uf 1 1][e]

[msg MSG_007_0_0]
[uf 0 5 65278][uf 2 1]Sobre abandonar el club.[n][uf 1 1][e]

[msg MSG_008_0_0]
[uf 0 5 65278][uf 2 1]Creo que mereces una explicación.[n]Hoy pienso contártelo todo, aunque lo tenga que hacer en mitad de la reunión del club.[uf 1 3 136][n]Espero verte por allí.[n][uf 1 1][e]

[msg MSG_009_0_0]
[uf 0 5 65278][uf 2 1]Siento lo de antes.[n][uf 1 1][e]

[msg MSG_010_0_0]
[uf 0 5 65278][uf 2 1]Todo el mundo se habrá preocupado cuando me he ido de repente.[uf 1 3 138][n]Ahora que las cosas se han calmado, puedo concentrarme en crear arte.[n]Deberías venir. Me gustaría pintar juntos.[uf 1 3 137][n][uf 1 1][e]

[msg MSG_011_0_0]
[uf 0 5 65278][uf 2 1]He estado pensando...[n][uf 1 1][e]

[msg MSG_012_0_0]
[uf 0 5 65278][uf 2 1]Pensaba que tenía todo claro...[uf 1 3 138][n]¿Te preocupa el futuro?[n]Quizá yo le dé demasiadas vueltas...[n]Con suerte, pintar aliviará el temor existencial. XD[n][uf 1 1][e]

[msg MSG_013_0_0]
[uf 0 5 65278][uf 2 1]Me zumba la cabeza.[n][uf 1 1][e]

[msg MSG_014_0_0]
[uf 0 5 65278][uf 2 1]Sigo pensando en ello...[n]De hecho, me ha quitado el sueño.[uf 1 3 138][n]Pero hoy tengo asignada la limpieza, así que estaré en el club de arte.[uf 1 3 136][n]¿Te veré por allí?[n][uf 1 1][e]

[msg MSG_015_0_0]
[uf 0 5 65278][uf 2 1]He tomado una decisión.[n][uf 1 1][e]

[msg MSG_016_0_0]
[uf 0 5 65278][uf 2 1]Por favor, si hoy puedes, ven al club de arte.[n]Quiero verte.[n]Lo siento, no pretendo ser egoísta. Es solo que preferiría decírtelo en persona.[n][uf 1 1][e]

[msg MSG_017_0_0]
[uf 0 5 65278][uf 2 1][uf 4 1]...[n][uf 1 1][e]

[msg MSG_018_0_0]
[uf 0 5 65278][uf 2 1]He pedido a todos los del club que vinieran. Me encantaría que vinieses. De hecho, he decidido que también tienes que venir. Por prescripción médica.[uf 1 3 137][n][uf 1 1][e]

[msg MSG_019_0_0]
[uf 0 5 65278][uf 2 1]Colega de pintura[n][uf 1 1][e]

[msg MSG_020_0_0]
[uf 0 5 65278][uf 2 1]¡Hola! ¿Hoy vienes al club de arte?[n][uf 1 5 0]Espero verte allí.[uf 1 3 137][n][uf 1 1][e]

[msg MSG_021_0_0]
[uf 0 5 65278][uf 2 1]¿Quemado?[n][uf 1 1][e]

[msg MSG_022_0_0]
[uf 0 5 65278][uf 2 1]¿Qué mejor forma de remediarlo que una relajante sesión de pintura?[n]...[n]Va, perdona. Dejo de poner voz de anuncio de la tele. XD[n]Pásate por allí si quieres.[uf 1 3 136][n][uf 1 1][e]

[msg MSG_023_0_0]
[uf 0 5 65278][uf 2 1]¡El club de arte se reúne hoy![uf 1 3 145][n][uf 1 1][e]

[msg MSG_024_0_0]
[uf 0 5 65278][uf 2 1]He estado probando nuevas técnicas de dibujo últimamente.[uf 1 3 137] Me encantaría enseñarte algo de lo que he aprendido. Desde luego, también podemos hablar de otras cosas que no sean arte...[n][uf 1 1][e]

[msg MSG_025_0_0]
[uf 0 5 65278][uf 2 1]Ya casi es la hora...[n][uf 1 1][e]

[msg MSG_026_0_0]
[uf 0 5 65278][uf 2 1]¡Buenos días![uf 1 3 140][n]He notado que el agotamiento está empezando a apoderarse de mí, así que voy tomarme un descanso y salir.[n]Sé que probablemente estarás ocupada, pero me encantaría que vinieras conmigo.[n]Dime qué te parece antes de esta tarde.[n]¡Gracias![uf 1 3 140][uf 1 3 137][n][uf 1 1][e]

[msg MSG_027_0_0]
[uf 0 5 65278][uf 2 1]¿Una peli?[n][uf 1 1][e]

[msg MSG_028_0_0]
[uf 0 5 65278][uf 2 1]¡Siento avisarte con tan poca antelación! Acaban de estrenar una peli y la crítica está encantada por su dirección artística. Seguro que también ayudaría a tu carisma.[uf 1 3 151] Puede que tenga una entrada de sobra y me preguntaba si te gustaría venir conmigo. ¡Dime si te apetece![uf 1 3 137][n][uf 1 1][e]

