[msg MSG_000_0_0 [Director]]
[uf 0 5 65278][uf 2 1][uf 4 5 1181 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0][uf 5 21 0 1]Empezamos un nuevo año académico.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1181 0 65535 65535 0 0][uf 3 1 1 0 0 2 0 0][uf 5 21 0 1]Quiero que todos recordéis el dicho: "Si vas a hacer algo, hazlo bien".[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1181 0 65535 65535 0 0][uf 3 1 1 0 0 3 0 0][uf 5 21 0 1]Aplicado a la vida estudiantil, significa que...[n][uf 1 1][e]

[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]El director continúa con su discurso.[n][uf 1 1][e]

[msg MSG_002_0_0 [Compi de clase]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 4 0 0][uf 5 21 0 2]Psss... Oye.[n][uf 1 1][e]

[msg MSG_003_0_0 [Compi de clase]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 5 0 0][uf 5 21 0 2]Has venido al instituto con Takeba esta mañana, ¿no?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 6 0 0][uf 5 21 0 2]Os he visto llegar. Tenéis buena relación, ¿no?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 7 0 0][uf 5 21 0 2]¿Hay algo entre vosotras?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 8 0 0][uf 5 21 0 2]Oye, ¿tiene pareja? Es que nadie lo sabe.[n][uf 1 1][e]

[sel SEL_004_0_0 top]
[uf 0 5 65278][uf 2 1]Sí tiene.[e]
[uf 0 5 65278][uf 2 1]No tiene.[e]
[uf 0 5 65278][uf 2 1]Ni idea.[e]

[msg MSG_005_0_0 [Compi de clase]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 9 0 0][uf 5 21 0 2]Jo, lo sabía...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 10 0 0][uf 5 21 0 2]¿Cómo no iba a tener pareja?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 11 0 0][uf 5 21 0 2]Un momento, ¿qué relación tenéis?[n][uf 1 1][e]

[msg MSG_006_0_0 [Compi de clase]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 12 0 0]¿En serio? ¿Se lo has preguntado?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 13 0 0]Vaya. Qué sorpresa...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 14 0 0]Un momento, ¿qué relación tenéis?[n][uf 1 1][e]

[msg MSG_007_0_0 [Compi de clase]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 15 0 0][uf 5 21 0 2]¿En serio?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 16 0 0][uf 5 21 0 2]Pensaba que lo sabrías, pero... parece que no.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 17 0 0][uf 5 21 0 2]Un momento, ¿qué relación tenéis?[n][uf 1 1][e]

[msg MSG_008_0_0 [Profesor de otra clase]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 18 0 0][uf 5 21 0 1]¿Qué pasa? ¡Alguien está hablando![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 19 0 0][uf 5 21 0 1]Parece ser de la clase de la profesora Toriumi.[n][uf 1 1][e]

[msg MSG_009_0_0 [Profesora Toriumi]]
[uf 0 5 65278][uf 2 1][uf 4 5 1581 2 65535 65535 0 0][uf 3 1 1 0 0 20 0 0]¡Oye, ssssh! ¡Cállate! ¡Me vas a meter en un lío![n][uf 1 1][e]

