[msg MSG_000_0_0 [Mamoru Hayase]]
[uf 0 5 65278][uf 2 1][uf 4 5 115 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0][uf 4 23 0 1 0 25 25]¿Mm?[n][uf 1 1][e]

[msg MSG_001_0_0 [Mamoru Hayase]]
[uf 0 5 65278][uf 2 1][uf 4 5 115 0 65535 65535 0 0][uf 3 1 1 0 0 2 0 0][uf 4 23 0 1 0 25 25]¡Oye, estás bajando el ritmo! ¿Eso es todo lo que puedes hacer?[n][uf 1 1][e]

[sel SEL_002_0_0 top]
[uf 0 5 65278][uf 2 1]¡Esto aún no ha terminado![e]
[uf 0 5 65278][uf 2 1]¡¿Quieres ver de qué pasta estoy hecha?![e]

[msg MSG_003_0_0 [Mamoru Hayase]]
[uf 0 5 65278][uf 2 1][uf 4 5 115 1 65535 65535 0 0][uf 3 1 1 0 0 3 0 0][uf 4 23 0 1 1 25 25]Ah, reservas fuerzas para la recta final, ¿eh? Venga, ¡vamos allá![n][uf 1 1][e]

[msg MSG_003_5_0 [Mamoru Hayase]]
[uf 0 5 65278][uf 2 1][uf 4 5 115 2 65535 65535 0 0][uf 3 1 1 0 0 4 0 0][uf 4 23 0 1 2 25 25]¡Vamos, vamos![n][uf 1 1][e]

[msg MSG_004_0_0 [Mamoru Hayase]]
[uf 0 5 65278][uf 2 1][uf 4 5 115 4 65535 65535 0 0][uf 3 1 1 0 0 5 0 0][uf 4 23 0 1 4 25 25]¡E-esa es la técnica prohibida de la lengua quemada! ¡Yo también lo haré![n][uf 1 1][e]

[msg MSG_004_5_0 [Mamoru Hayase]]
[uf 0 5 65278][uf 2 1][uf 4 5 115 2 65535 65535 0 0][uf 3 1 1 0 0 6 0 0][uf 4 23 0 1 2 25 25]¡Vamos, vamos! ¡Ay, cómo quema![n][uf 1 1][e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]Hayase y yo hemos terminado[n]de comer al mismo tiempo.[n][uf 1 1][e]

[msg MSG_006_0_0 [Mamoru Hayase]]
[uf 0 5 65278][uf 2 1][uf 4 5 115 0 65535 65535 0 0][uf 3 1 1 0 0 7 0 0][uf 4 23 0 1 0 25 25]Uf... Esto huele a empate.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 115 1 65535 65535 0 0][uf 3 1 1 0 0 8 0 0][uf 4 23 0 1 1 25 25]Pocos me pueden seguir el ritmo. ¡Me has impresionado, [uf 4 1]![n][uf 1 1][e]

[sel SEL_007_0_0 top]
[uf 0 5 65278][uf 2 1]Pensaba que te ganaría.[e]
[uf 0 5 65278][uf 2 1]Pues creía que perdería, la verdad.[e]

[msg MSG_008_0_0 [Mamoru Hayase]]
[uf 0 5 65278][uf 2 1][uf 4 5 115 1 65535 65535 0 0][uf 3 1 1 0 0 9 0 0][uf 4 23 0 1 1 25 25]No me digas. Supongo que ha faltado poco. Uf...[n][uf 1 1][e]

[msg MSG_009_0_0 [Mamoru Hayase]]
[uf 0 5 65278][uf 2 1][uf 4 5 115 1 65535 65535 0 0][uf 3 1 1 0 0 10 0 0][uf 4 23 0 1 1 25 25]Lo mismo digo. Jamás pensé que acabaría ganando. Uf...[n][uf 1 1][e]

[msg MSG_010_0_0 [Mamoru Hayase]]
[uf 0 5 65278][uf 2 1][uf 4 5 115 0 65535 65535 0 0][uf 3 1 1 0 0 11 0 0][uf 4 23 0 1 0 25 25]Menuda valentía, desafiándome a comer takoyaki... Te has ganado mi respeto.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 115 0 65535 65535 0 0][uf 3 1 1 0 0 12 0 0][uf 4 23 0 1 0 25 25]Cuando te conocí, sabía que tenías potencial.[n][uf 1 1][e]

[msg MND_011_0_0]
[uf 0 5 65278][uf 2 1]Hayase esboza una sonrisa sin miedo alguno.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]He dejado deslumbrado[n]a la estrella de atletismo de otro instituto.[n][uf 1 1][e]

[msg MSG_012_0_0 [Mamoru Hayase]]
[uf 0 5 65278][uf 2 1][uf 4 5 115 0 65535 65535 0 0][uf 3 1 1 0 0 13 0 0][uf 4 23 0 1 0 25 25]Para mí, un empate no es mejor que una derrota.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 115 0 65535 65535 0 0][uf 3 1 1 0 0 14 0 0][uf 4 23 0 1 0 25 25]Tal y como prometí, voy a dar cien vueltas a la ciudad. Tú haz lo que creas que es mejor.[n][uf 1 1][e]

[msg MSG_012_5_0 [Mamoru Hayase]]
[uf 0 5 65278][uf 2 1][uf 4 5 115 1 65535 65535 0 0][uf 3 1 1 0 0 15 0 0][uf 4 23 0 1 1 25 25]¡Menuda guerra me has dado hoy! ¡Nos vemos![n][uf 1 1][e]

[msg MND_013_0_0]
[uf 0 5 65278][uf 2 1]He decidido volver a la residencia.[n][uf 1 1][e]

