[msg MSG_000_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0][uf 4 23 0 1 0 25 25]Je crois que je ne t'ai jamais dit comment étaient les choses avant que tu ne nous rejoignes.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 2 0 0][uf 4 23 0 1 0 25 25]À l'origine, la SEES a démarré avec juste trois membres.[n][uf 1 1][e]

[msg MSG_001_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 3 0 0][uf 4 23 0 1 0 25 25]À l'époque du collège, j'ai invité Akihiko à rejoindre le groupe, et Aragaki l'a suivi peu après.[n][uf 1 1][e]

[msg MSG_002_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 4 0 0][uf 4 23 0 1 0 25 25]On ne savait pas ce qu'on faisait, à l'époque.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 5 0 0][uf 4 23 0 1 0 25 25]On était jeunes, inexpérimentés... et on n'avait pour ainsi dire pas de renseignements à partir desquels travailler.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 6 0 0][uf 4 23 0 1 0 25 25]On arrivait à peine à dépasser l'entrée de Tartare, à l'époque...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 7 0 0][uf 4 23 0 1 0 25 25]Explorer la tour, comme on le fait maintenant, c'était un rêve inaccessible.[n][uf 1 1][e]

[msg MSG_003_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 0 8 0 0][uf 4 23 0 1 1 25 25]Mais malgré nos défauts, on travaillait de façon correcte en équipe.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 0 9 0 0][uf 4 23 0 1 1 25 25]Comme on était semblables, c'était facile de s'entendre. Et si le travail était dur, il était aussi gratifiant.[n][uf 1 1][e]

[sel SEL_004_0_0 top]
[uf 0 5 65278][uf 2 1]Je n'imagine même pas.[e]
[uf 0 5 65278][uf 2 1]J'aurais voulu voir ça.[e]

[msg MSG_005_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 10 0 0][uf 4 23 0 1 0 25 25]Oh, pardon. Ne crois pas que je me plains des circonstances actuelles.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 11 0 0][uf 4 23 0 1 0 25 25]On a découvert comment éliminer l'Heure sombre, et on est devenus beaucoup plus forts.[n][uf 1 1][e]

[msg MSG_006_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 65535 65535 0 0][uf 3 1 1 0 0 12 0 0][uf 4 23 0 1 3 25 25]Cela dit, après ce qui s'est passé à Yakushima, et avec le retour d'Aragaki... c'est difficile de ne pas repenser à autrefois.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 65535 65535 0 0][uf 3 1 1 0 0 13 0 0][uf 4 23 0 1 3 25 25]Peut-être que si ça m'importe tant qu'il revienne au lycée, c'est parce que je vis encore dans le passé.[n][uf 1 1][e]

[sel SEL_007_0_0 top]
[uf 0 5 65278][uf 2 1]Dans le passé ?[e]
[uf 0 5 65278][uf 2 1]Pourquoi est-ce si important qu'il aille au lycée ?[e]

[msg MSG_008_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 14 0 0][uf 4 23 0 1 0 25 25]Oui.[n][uf 1 1][e]

[msg MSG_009_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 15 0 0][uf 4 23 0 1 0 25 25]Hum...[n][uf 1 1][e]

[msg MSG_010_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 16 0 0][uf 4 23 0 1 0 25 25]Quelques temps après avoir commencé à travailler ensemble, on s'est mis d'accord.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 17 0 0][uf 4 23 0 1 0 25 25]On s'est promis qu'on obtiendrait notre diplôme ensemble... Pas de laissés pour compte.[n][uf 1 1][e]

[msg MSG_011_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 18 0 0][uf 4 23 0 1 0 25 25]Akihiko était déjà aussi téméraire qu'aujourd'hui.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 19 0 0][uf 4 23 0 1 0 25 25]C'est toujours Aragaki qui lui rappelait qu'on mettait notre vie en jeu.[n][uf 1 1][e]

[msg MSG_012_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 0 20 0 0][uf 4 23 0 1 1 25 25]Bien sûr, il ne l'exprimait pas de façon très attentionnée...[n][uf 1 1][e]

[sel SEL_013_0_0 top]
[uf 0 5 65278][uf 2 1]Quelle surprise.[e]
[uf 0 5 65278][uf 2 1]J'imagine.[e]

[msg MSG_014_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 0 21 0 0][uf 4 23 0 1 1 25 25]Oui, je sais. J'ai été surprise, moi aussi.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 22 0 0][uf 4 23 0 1 0 25 25]Mais Aragaki ne prenait pas ses distances comme il le fait maintenant.[n][uf 1 1][e]

[msg MSG_015_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 0 23 0 0][uf 4 23 0 1 1 25 25]Et ça lui va bien, n'est-ce pas ? On dirait que tu commences à le connaître.[n][uf 1 1][e]

[msg MSG_016_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 65535 65535 0 0][uf 3 1 1 0 0 24 0 0][uf 4 23 0 1 3 25 25]Depuis qu'il a quitté l'équipe, il se comporte comme s'il tenait à se punir.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 65535 65535 0 0][uf 3 1 1 0 0 25 0 0][uf 4 23 0 1 3 25 25]Presque comme s'il voulait juste dépérir, disparaître...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 10 65535 65535 0 0][uf 3 1 1 0 0 26 0 0][uf 4 23 0 1 10 25 25]J'espère qu'il se souviendra de sa promesse. Qu'il prendra du recul et saura se regarder dans une glace.[n][uf 1 1][e]

[msg MSG_017_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 27 0 0][uf 4 23 0 1 0 25 25]C'est pour ça que je t'ai donné les papiers pour qu'il revienne au lycée.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 28 0 0][uf 4 23 0 1 0 25 25]C'était mon dernier espoir, mais je suppose que ça n'a pas marché. Je le dirai à Akihiko moi-même.[n][uf 1 1][e]

[msg MSG_018_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 29 0 0][uf 4 23 0 1 0 25 25]Bon, je vais prendre ça. Je vais lancer les démarches pour rallonger son autorisation d'absence.[n][uf 1 1][e]

[msg MND_019_0_0]
[uf 0 5 65278][uf 2 1]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Apparemment, Mitsuru et Sanada espéraient vraiment qu'Aragaki retournerait au lycée...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Je dois bien réfléchir pour savoir si je dois donner ce papier ou non...[n][uf 1 1][e]

[msg MSG_020_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 4 65535 65535 0 0][uf 3 1 1 0 0 30 0 0][uf 4 23 0 1 4 25 25]Qu'y a-t-il ?[n][uf 1 1][e]

[sel SEL_021_0_0 top]
[uf 0 5 65278][uf 2 1]Une minute.[e]
[uf 0 5 65278][uf 2 1]Rien.[uf 2 9 1 1 1312][e]

[msg MSG_022_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 4 65535 65535 0 0][uf 3 1 1 0 0 31 0 0][uf 4 23 0 1 4 25 25]Oui, bien sûr... Mais qu'y a-t-il ? Il manque une page ?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 32 0 0][uf 4 23 0 1 0 25 25]Je te laisse t'en occuper, alors. N'oublie pas de prévenir Aragaki.[n][uf 1 1][e]

[msg MSG_023_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 33 0 0][uf 4 23 0 1 0 25 25]Très bien, merci. Désolée que tu aies dû passer tant de temps avec ça.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 34 0 0][uf 4 23 0 1 0 25 25]Je vais m'en occuper, maintenant. N'oublie pas de prévenir Aragaki.[n][uf 1 1][e]

[msg MND_024_0_0]
[uf 0 5 65278][uf 2 1]J'ai pris le formulaire d'extension d'autorisation d'absence et j'ai quitté la salle du conseil des élèves.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Je devrais peut-être chercher Aragaki et le pousser à réétudier la question...[n][uf 1 1][e]

