[msg MSG_000_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 1 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]I'm going to go get some medicine. I'll be right back.[n][uf 1 1][e]

[msg MSG_001_0_0 [Pretentious Man]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 2 0 0][uf 5 21 0 100]Oh, hey there! You on your way home from school?[n][uf 1 1][e]

[msg MSG_002_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]Huh? Wh-What do you want...?[n][uf 1 1][e]

[msg MSG_003_0_0 [Pretentious Man]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 4 0 0][uf 5 21 0 100]Wow, you're really cute! From this angle, I can see how gorgeous you are in those glasses![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 5 0 0][uf 5 21 0 100]Say, you wanna maybe sit down at a café and chat a little?[n][uf 1 1][e]

[msg MSG_004_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]U-Um, I...[n][uf 1 1][e]

[msg MSG_005_0_0 [Pretentious Man]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 7 0 0][uf 5 21 0 100]Hey, c'mon, don't be scared. I'm not gonna bite![n][uf 1 1][e]

[msg MSG_006_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 1 0 0 8 0 0]N-No... Please stop...![n][uf 1 1][e]

[msg MSG_006_3_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 1 0 0 9 0 0][uf 4 1]-san![n][uf 1 1][e]

[sel SEL_007_0_0 top]
[uf 0 5 65278][uf 2 1]Back off![e]
[uf 0 5 65278][uf 2 1]...Get a clue.[e]

[msg MSG_008_0_0 [Pretentious Man]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 10 0 0][uf 5 21 0 100]A girl, Huh? Who the hell're you?[n][uf 1 1][e]

[msg MSG_008_3_0 [Pretentious Man]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 11 0 0][uf 5 21 0 100]Wait... Don't tell me that you're with her![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 0 0 0 12 0 0][uf 5 21 0 100]Hmph...[n][uf 1 1][e]

[msg MSG_008_7_0 [Pretentious Man]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 13 0 0][uf 5 21 0 100]Psh, I thought I had a chance since she looked so plain...[n][uf 1 1][e]

[msg MSG_009_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]Oh, thank goodness... I thought you were going to hit him for a second, [uf 4 1]-san...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 1 0 0 15 0 0]I wouldn't want you to get into a fight because of me... But just now, you were so... Um...[n][uf 1 1][e]

[msg MSG_010_0_0 [Pretentious Man]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 16 0 0][uf 5 21 0 100]What do you want? What're you glaring like that for anyways...?[n][uf 1 1][e]

[msg MSG_010_3_0 [Pretentious Man]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 17 0 0][uf 5 21 0 100]Wait... You're not with her, are you?[n][uf 1 1][e]

[msg MSG_010_7_0 [Pretentious Man]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 18 0 0][uf 5 21 0 100]Ugh, she's freakin' taken...[n][uf 1 1][e]

[msg MSG_011_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 1 0 0 19 0 0]You're usually so quiet, [uf 4 1]-san, but I guess you can be tough when you need to be.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0][uf 3 1 1 0 0 20 0 0][uf 4 23 0 109 0 25 25]I-I don't mean that in a bad way though... I... Um...[n][uf 1 1][e]

[msg MSG_012_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 1 0 0 21 0 0]Hngh... You've already saved me so I'm not scared anymore, but...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 1 0 0 22 0 0]Why am I still shaking?[n][uf 1 1][e]

[sel SEL_013_0_0 top]
[uf 0 5 65278][uf 2 1]We could hold hands?[e]
[uf 0 5 65278][uf 2 1]I'm here for you.[e]
[uf 0 5 65278][uf 2 1]Take a deep breath.[e]

[msg MSG_014_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 4 65535 65535 0 0][uf 3 1 1 0 0 23 0 0]Huh...? H-Hold hands...?[n][uf 1 1][e]

[msg MSG_015_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 1 0 0 24 0 0]I-I'm so sorry... I... don't think I'm ready for this just yet...[n][uf 1 1][e]

[msg MSG_015_5_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0][uf 3 1 1 0 0 25 0 0]...Oh, but at least I'm not shaking anymore. Thank you...[n][uf 1 1][e]

[msg MSG_016_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0][uf 3 1 1 0 0 26 0 0][uf 5 13 9 15 109]That does make me feel a lot better... Okay.[n][uf 1 1][e]

[msg MSG_016_5_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0][uf 3 1 1 0 0 27 0 0]Thank you. I think I'm fine now.[n][uf 1 1][e]

[msg MSG_017_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0][uf 3 1 1 0 0 28 0 0]...Oh, that really did help calm me down a bit.[n][uf 1 1][e]

[msg MSG_017_5_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0][uf 3 1 1 0 0 29 0 0]Thank you. I think I'm fine now.[n][uf 1 1][e]

[msg MND_018_0_0]
[uf 0 5 65278][uf 2 1]I can sense Chihiro trusts me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like our relationship has grown...[n][uf 1 1][e]

[msg MSG_019_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 1 0][uf 3 1 1 0 0 30 0 0]Huh? Wh-Why do I... suddenly feel short of breath...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 1 0][uf 3 1 1 0 0 31 0 0][uf 4 1]-san, I...[n][uf 1 1][e]

[msg MSG_020_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 1 0][uf 3 1 1 0 0 32 0 0]I think I really did catch a cold... I feel like my face is all flush.[n][uf 1 1][e]

[msg MSG_020_5_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 1 0][uf 3 1 1 0 0 33 0 0]...Um... Thank you again for saving me today![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 1 0][uf 3 1 1 0 0 34 0 0][uf 4 21 109 11]Now, please excuse me![n][uf 1 1][e]

[msg MND_021_0_0]
[uf 0 5 65278][uf 2 1]Chihiro hurried away...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I decided to return to the dorm.[n][uf 1 1][e]

