[msg MND_000_0_0]
[uf 0 5 65278][uf 2 1]Koromaru a l'air de bien s'amuser.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]J'ai regardé le documentaire animalier avec Koromaru...[n][uf 1 1][e]

[msg MSG_001_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 1 65535 65535 0 0][uf 3 1 1 0 0 1 0 0][uf 4 23 0 1 1 25 25]Ouaf ![n][uf 1 1][e]

[msg MND_002_0_0]
[uf 0 5 65278][uf 2 1]Observer comment les animaux vivent dans la nature m'a fait gagner en [uf 4 30 0 1 1 0].[n][uf 1 1][e]

[msg MSG_003_0_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 1 65535 65535 0 0][uf 3 1 1 0 0 2 0 0][uf 4 23 0 1 1 25 25]Ouaf ![n][uf 1 1][e]

