[msg MSG_000_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]¿Cómo está?[n][uf 1 1][e]

[msg MSG_001_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 65535 0 0][uf 3 1 1 0 0 2 0 0]Parece un poco cansada. Se fue a la cama sin quitarse el uniforme.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 65535 0 0][uf 3 1 1 0 0 3 0 0]Por lo demás, todo sigue igual que anoche.[n][uf 1 1][e]

[msg MSG_001_5_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 65535 0 0][uf 3 1 1 0 0 4 0 0]Igual que anoche.[n][uf 1 1][e]

[msg MSG_002_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]Mm, qué interesante.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]Incluso quienes tienen potencial son inestables al principio.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]Pérdida de memoria... Desorientación...[n][uf 1 1][e]

[msg MSG_003_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 8 0 0]Pero este sujeto es distinto. No ha mostrado ninguno de los síntomas más comunes.[n][uf 1 1][e]

[msg MSG_004_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 51 65535 0 0][uf 3 1 1 0 0 9 0 0]La estamos usando como conejillo de Indias.[n][uf 1 1][e]

[msg MSG_005_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]Oye, no lo veas así. Sois compañeras de clase, ¿no?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 11 0 0]Considéralo una oportunidad para tener aquí a alguien de tu edad.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 222 0 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]Además, necesitamos toda la ayuda posible.[n][uf 1 1][e]

[msg MSG_006_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 51 65535 0 0][uf 3 1 1 0 0 13 0 0]Supongo que es verdad, pero aun así...[n][uf 1 1][e]

[msg MSG_007_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 65535 0 0][uf 3 1 1 0 0 14 0 0]Sala de mando al habla.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 65535 0 0][uf 3 1 1 0 0 15 0 0]¿Akihiko? ¿Qué ocurre?[n][uf 1 1][e]

[msg MSG_008_0_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 16 0 0]¡No os lo vais a creer! ¡Esta cosa es enorme![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 17 0 0]Por desgracia, me está persiguiendo ahora mismo...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 18 0 0]Ya casi estoy ahí. Solo quería avisaros.[n][uf 1 1][e]

[msg MSG_008_5_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 17 2 4 0][e]

[msg MSG_009_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 51 65535 0 0][uf 3 1 1 0 0 19 0 0]Eso quiere decir... ¡¿que va a traernos esa cosa?![n][uf 1 1][e]

[msg MSG_010_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 51 65535 0 0][uf 3 1 1 0 0 20 0 0]¡Señor director![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 51 65535 0 0][uf 3 1 1 0 0 21 0 0]Suficiente observación por ahora. ¡Preparémonos para el combate![n][uf 1 1][e]

[msg MSG_011_0_0 [Shuji Ikutsuki]]
[uf 0 5 65278][uf 2 1][uf 4 5 222 4 65535 65535 0 0][uf 3 1 1 0 0 22 0 0]¡S-sí! ¡Mucho cuidado![n][uf 1 1][e]

