[msg MND_000_0_0]
[uf 0 5 65278][uf 2 1]Aigis est concentrée sur les plants.[n][uf 1 1][e]

[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]Je me suis occupée des plants avec Aigis.[n][uf 1 1][e]

[msg MSG_002_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 1 0 0][uf 5 13 22 1 7]Dans combien de temps pourra-t-on les récolter ?[n][uf 1 1][e]

[msg MSG_003_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 2 0 0][uf 5 13 22 1 7] La taille n'est pas importante tant qu'ils poussent bien.[n][uf 1 1][e]

[msg MSG_004_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 3 0 0][uf 5 13 22 1 7]Ces insectes... Je vais les asperger de répulsif.[n][uf 1 1][e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]Grâce à nos efforts, on dirait que la récolte va être bonne.[n][uf 1 1][e]

[msg MSG_006_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 4 0 0]Ça devrait suffire pour aujourd'hui. Il est temps de rentrer.[n][uf 1 1][e]

[msg MND_007_0_0]
[uf 0 5 65278][uf 2 1]Aigis est concentrée sur les plants.[n][uf 1 1][e]

[msg MND_008_0_0]
[uf 0 5 65278][uf 2 1]Je me suis occupée des plants avec Aigis.[n][uf 1 1][e]

[msg MSG_009_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 5 0 0][uf 5 13 22 1 7]Dans combien de temps pourra-t-on les récolter ?[n][uf 1 1][e]

[msg MSG_010_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 6 0 0][uf 5 13 22 1 7]Ce n'est pas grave s'ils sont petits, tant qu'ils poussent bien.[n][uf 1 1][e]

[msg MSG_011_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 7 0 0][uf 5 13 22 1 7]Ah, ces insectes... Je vais les chasser avec du répulsif ![n][uf 1 1][e]

[msg MND_012_0_0]
[uf 0 5 65278][uf 2 1]Grâce à nos efforts, on dirait que la récolte va être bonne.[n][uf 1 1][e]

[msg MSG_013_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 65535 0 0][uf 3 1 1 0 0 8 0 0]Ça devrait suffire pour aujourd'hui. Rentrons.[n][uf 1 1][e]

[msg MND_014_0_0]
[uf 0 5 65278][uf 2 1]Aigis est concentrée sur les plants.[n][uf 1 1][e]

[msg MND_015_0_0]
[uf 0 5 65278][uf 2 1]Je me suis occupée des plants avec Aigis.[n][uf 1 1][e]

[msg MSG_016_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 1 0 0][uf 5 13 22 1 7]Dans combien de temps pourra-t-on les récolter ?[n][uf 1 1][e]

[msg MSG_017_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 2 0 0][uf 5 13 22 1 7]La taille n'est pas importante tant qu'ils poussent bien.[n][uf 1 1][e]

[msg MSG_018_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 3 0 0][uf 5 13 22 1 7]Ces insectes... Je vais les asperger de répulsif.[n][uf 1 1][e]

[msg MND_019_0_0]
[uf 0 5 65278][uf 2 1]Grâce à nos efforts, on dirait que la récolte va être bonne.[n][uf 1 1][e]

[msg MSG_020_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 4 0 0]Ça devrait suffire pour aujourd'hui. Il est temps de rentrer.[n][uf 1 1][e]

[msg MND_021_0_0]
[uf 0 5 65278][uf 2 1]Aigis est concentrée sur les plants.[n][uf 1 1][e]

[msg MND_022_0_0]
[uf 0 5 65278][uf 2 1]Je me suis occupée des plants avec Aigis.[n][uf 1 1][e]

[msg MSG_023_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 5 0 0][uf 5 13 22 1 7]Dans combien de temps pourra-t-on les récolter ?[n][uf 1 1][e]

[msg MSG_024_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 6 0 0][uf 5 13 22 1 7]Ce n'est pas grave s'ils sont petits, tant qu'ils poussent bien.[n][uf 1 1][e]

[msg MSG_025_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 7 0 0][uf 5 13 22 1 7]Ah, ces insectes... Je vais les chasser avec du répulsif ![n][uf 1 1][e]

[msg MND_026_0_0]
[uf 0 5 65278][uf 2 1]Grâce à nos efforts, on dirait que la récolte va être bonne.[n][uf 1 1][e]

[msg MSG_027_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 2 65535 0 0][uf 3 1 1 0 0 8 0 0]Ça devrait suffire pour aujourd'hui. Rentrons.[n][uf 1 1][e]

[msg MND_028_0_0]
[uf 0 5 65278][uf 2 1]Aigis est concentrée sur les plants.[n][uf 1 1][e]

[msg MND_029_0_0]
[uf 0 5 65278][uf 2 1]Je me suis occupée des plants avec Aigis.[n][uf 1 1][e]

[msg MSG_030_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 1 0 0][uf 5 13 22 1 7]Dans combien de temps pourra-t-on les récolter ?[n][uf 1 1][e]

[msg MSG_031_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 2 0 0][uf 5 13 22 1 7]La taille n'est pas importante tant qu'ils poussent bien.[n][uf 1 1][e]

[msg MSG_032_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 3 0 0][uf 5 13 22 1 7]Ces insectes... Je vais les asperger de répulsif.[n][uf 1 1][e]

[msg MND_033_0_0]
[uf 0 5 65278][uf 2 1]Grâce à nos efforts, on dirait que la récolte va être bonne.[n][uf 1 1][e]

[msg MSG_034_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 4 0 0]Ça devrait suffire pour aujourd'hui. Il est temps de rentrer.[n][uf 1 1][e]

[msg MND_035_0_0]
[uf 0 5 65278][uf 2 1]Aigis est concentrée sur les plants.[n][uf 1 1][e]

[msg MND_036_0_0]
[uf 0 5 65278][uf 2 1]Je me suis occupée des plants avec Aigis.[n][uf 1 1][e]

[msg MSG_037_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 5 0 0][uf 5 13 22 1 7]Dans combien de temps pourra-t-on les récolter ?[n][uf 1 1][e]

[msg MSG_038_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 6 0 0][uf 5 13 22 1 7]Ce n'est pas grave s'ils sont petits, tant qu'ils poussent bien.[n][uf 1 1][e]

[msg MSG_039_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 7 0 0][uf 5 13 22 1 7]Ah, ces insectes... Je vais les chasser avec du répulsif ![n][uf 1 1][e]

[msg MND_040_0_0]
[uf 0 5 65278][uf 2 1]Grâce à nos efforts, on dirait que la récolte va être bonne.[n][uf 1 1][e]

[msg MSG_041_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 6 65535 0 0][uf 3 1 1 0 0 8 0 0]Ça devrait suffire pour aujourd'hui. Rentrons.[n][uf 1 1][e]

