[msg MSG_000_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]Is... Is this, um, really okay? Are you sure you don't mind or anything?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]I mean, um, I'm glad you're willing to... b-but...[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]What are you trying to say?[e]
[uf 0 5 65278][uf 2 1]Have you changed your mind?[e]
[uf 0 5 65278][uf 2 1]Just relax...[e]

[msg MSG_002_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]Oh! Um... Um...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]N-Nothing...[n][uf 1 1][e]

[msg MSG_003_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]N-No! I was just... Um... This is all just so sudden...[n][uf 1 1][e]

[msg MSG_004_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]O-Oh, right... I-I'm not very good at talking to others...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]There are a lot of guys in the student council though, so I should work on that...[n][uf 1 1][e]

[msg MSG_005_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0][uf 3 1 1 0 0 8 0 0]...Oh! School is almost out. Let's go.[n][uf 1 1][e]

