[msg MND_000_0_0]
[uf 0 5 65278][uf 2 1]El olor a pescado asado inunda el restaurante.[n][uf 1 1][e]

[msg MSG_001_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0][uf 3 1 1 0 0 1 0 0]A ver por dónde empiezo... Tengo un lío de narices.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 1 0 0 2 0 0][uf 4 23 0 1 0 25 25]Lo primero es lo primero. Toma, para ti.[n][uf 1 1][e]

[msg MND_002_0_0]
[uf 0 5 65278][uf 2 1]DEV: *Unused message label. *If this appears, it is a bug.[n][uf 1 1][e]

[msg MSG_003_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 1 0 0 3 0 0]Me lo ha dado mi sobrino. Es un amuleto de la suerte.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 1 101 65535 0 0][uf 3 1 1 0 0 4 0 0][uf 4 23 0 1 1 25 25]Pero a mí no me hace falta.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 1 101 65535 0 0][uf 3 1 1 0 0 5 0 0]Si te lesionas en un entrenamiento, podría serte de utilidad.[n][uf 1 1][e]

[msg MSG_004_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 1 0 0 6 0 0]Quería que fueses la primera en enterarte.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 1 0 0 7 0 0]He cambiado de opinión. Me voy a operar la rodilla.[n][uf 1 1][e]

[sel SEL_005_0_0 top]
[uf 0 5 65278][uf 2 1]¿Qué pasa con el encuentro?[e]
[uf 0 5 65278][uf 2 1]¿Qué pasa con tu promesa?[e]

[msg MSG_006_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 1 101 65535 0 0][uf 3 1 1 0 0 8 0 0][uf 5 13 8 15 105]Creo que no me va a dar tiempo a recuperarme para entonces, pero no pasa nada.[n][uf 1 1][e]

[msg MSG_007_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 1 101 65535 0 0][uf 3 1 1 0 0 9 0 0]Creo que no voy a poder mantenerla. Le debo una explicación.[n][uf 1 1][e]

[msg MSG_008_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 1 0 0 10 0 0]No pretendo lamentarme ni nada de eso. Solo quiero dejar de tomar decisiones egoístas.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 1 0 0 11 0 0]No me parece bien que el equipo tenga que sufrir por mi rodilla y por mi sobrino.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 1 0 0 12 0 0]Aunque ganara, creo que no me sentiría del todo bien.[n][uf 1 1][e]

[msg MSG_009_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 1 101 65535 0 0][uf 3 1 1 0 0 13 0 0]Hasta ahora, no he hecho más que pensar en ganar.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 1 101 65535 0 0][uf 3 1 1 0 0 14 0 0]Pero abrí los ojos cuando el entrenador te dio el tostón con lo de mi rodilla.[n][uf 1 1][e]

[msg MSG_009_3_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 1 101 65535 0 0][uf 3 1 1 0 0 15 0 0]Resultó tan evidente... Me di cuenta de que tenía que dejar de pensar solo en mí.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 1 0 0 16 0 0][uf 4 23 0 1 0 25 25]Pero, al mismo tiempo, no puedo renunciar a la victoria, ya que es parte de mi esencia. En fin...[n][uf 1 1][e]

[msg MSG_009_7_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 1 101 65535 0 0][uf 3 1 1 0 0 17 0 0]Por ahora, voy a dejar de pensar en ganar carreras. ¡Voy a centrarme en recuperar mi salud![n][uf 1 1][e]

[sel SEL_010_0_0 top]
[uf 0 5 65278][uf 2 1]¡Tú puedes![e]
[uf 0 5 65278][uf 2 1]Has madurado mucho.[e]

[msg MSG_011_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 1 101 65535 0 0][uf 3 1 1 0 0 18 0 0][uf 5 13 8 5 105]Ja, ja, tampoco es que se me vaya a curar por arte de magia.[n][uf 1 1][e]

[msg MSG_012_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 1 101 65535 0 0][uf 3 1 1 0 0 19 0 0][uf 5 13 8 5 105]¿T-tú crees? En el buen sentido, ¿no? ¿Crees que he madurado?[n][uf 1 1][e]

[msg MSG_013_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 1 101 65535 0 0][uf 3 1 1 0 0 20 0 0]En fin, no puedo estar pidiéndote todo el rato que me ayudes.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 1 101 65535 0 0][uf 3 1 1 0 0 21 0 0]Muchas gracias por todo lo que has hecho por mí.[n][uf 1 1][e]

[msg MSG_014_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 1 101 65535 0 0][uf 3 1 1 0 0 22 0 0]El entrenamiento y la rehabilitación me mantendrán ocupado, pero lo superaré.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 1 101 65535 0 0][uf 3 1 1 0 0 23 0 0]Y, algún día, te superaré a ti también, [uf 4 1].[n][uf 1 1][e]

[msg MND_015_0_0]
[uf 0 5 65278][uf 2 1]Kazushi me ha confesado que me aprecia mucho.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Tengo la sensación de que estamos estrechando lazos.[n][uf 1 1][e]

[msg SYS_016_0_0]
[uf 0 5 65278][uf 2 1]El vínculo social del Carro ha alcanzado su nivel máximo. ¡Ahora puedes fusionar a [uf 0 1 35]Thor[uf 0 1 27], el dios del trueno![n][uf 1 1][e]

[msg MSG_017_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 1 0 0 24 0 0]Voy a contarle a mi sobrino lo que ha pasado y le diré que vayamos juntos a rehabilitación.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 1 101 65535 0 0][uf 3 1 1 0 0 25 0 0][uf 4 23 0 1 1 25 25]¿Cuál de los dos se recuperará primero? El tío es un hueso duro de roer, como yo.[n][uf 1 1][e]

[msg MND_018_0_0]
[uf 0 5 65278][uf 2 1]He estado charlando con Kazushi un rato.[n][uf 1 1][e]

