[msg MSG_000_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]No pensé mucho en los libros que traje, tan solo cogí los que me llamaron la atención.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 65535 65535 0 0][uf 3 1 1 0 0 2 0 0][uf 4 23 0 1 3 25 25]Lo siento, [uf 4 1]. Debí haberte preguntado antes qué clase de libros te gustaban.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 3 0 0][uf 4 23 0 1 0 25 25]Si no te importa que lo haga ahora... ¿Qué clase de libros sueles leer?[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]Novelas.[e]
[uf 0 5 65278][uf 2 1]Manga.[e]
[uf 0 5 65278][uf 2 1]Libros de texto.[e]

[msg MSG_002_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 0 4 0 0][uf 4 23 0 1 1 25 25]¿Ah, sí? A mí me gusta la ficción histórica. De hecho, leo muchos libros del estilo.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 5 0 0][uf 4 23 0 1 0 25 25]Me gustan mucho las novelas. Solo tienes que pasar las páginas para experimentar la vida de alguien.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]Eso me recuerda que Yamagishi dijo que le gustaban las novelas.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]Nunca le insistí en el tema, pero quizás sería una buena compañera de lectura.[n][uf 1 1][e]

[msg MSG_003_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 8 0 0][uf 4 23 0 1 0 25 25]Mmm... No estoy muy familiarizada con ese medio, pero me da curiosidad, la verdad.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 9 0 0]Combinar imágenes con texto parece una forma de expresión muy poderosa.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 0 10 0 0][uf 4 23 0 1 1 25 25]Quizás le pida alguno a Iori para ampliar mis horizontes.[n][uf 1 1][e]

[msg MSG_004_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 0 11 0 0][uf 4 23 0 1 1 25 25]Ah, ya veo. Al final, leer es el núcleo del conocimiento.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 12 0 0][uf 4 23 0 1 0 25 25]¿Qué te interesan, las letras o las ciencias? He visto incluso libros sobre arte y arquitectura.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]Sea lo que sea, me alegra ver que tienes un abanico de intereses tan amplio.[n][uf 1 1][e]

[msg MSG_005_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]A propósito, los libros que traje son biografías, libros de historia y cosas así.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 15 0 0]Puedo dar fe de que vale la pena leerlos todos. Son muy accesibles, además.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 16 0 0]Espero que te gusten.[n][uf 1 1][e]

[msg MSG_006_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 0 17 0 0][uf 4 23 0 1 1 25 25][uf 5 13 4 1 5]Anda, te estás bebiendo las páginas. Me dejas sin palabras.[n][uf 1 1][e]

[msg MND_007_0_0]
[uf 0 5 65278][uf 2 1]Tras adentrarme en un mundo desconocido,[n]mi [uf 4 30 0 1 1 0] ha mejorado...[n][uf 1 1][e]

[msg MSG_008_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 18 0 0]Es muy agradable pasar el rato leyendo juntos así, tranquilas.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 0 19 0 0][uf 4 23 0 1 1 25 25]Gracias. Ha sido una tarde muy relajante.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 20 0 0][uf 4 23 0 1 0 25 25]En fin, es hora de volver a la habitación. Buenas noches, [uf 4 1].[n][uf 1 1][e]

[msg MSG_009_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 21 0 0]¿No te motiva leer sobre figuras influyentes del pasado?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 22 0 0]Hasta los líderes que forjaron grandes naciones se enfrentaron al reto de las relaciones interpersonales.[n][uf 1 1][e]

[sel SEL_010_0_0 top]
[uf 0 5 65278][uf 2 1]Un poco sí.[e]
[uf 0 5 65278][uf 2 1]No creas.[e]
[uf 0 5 65278][uf 2 1]¿Te preocupa algo?[e]

[msg MSG_011_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 23 0 0][uf 4 23 0 1 0 25 25]Sí, sobrellevarlo es más fácil si tienes en cuenta que todo el mundo tiene que pasar por ello.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 0 24 0 0][uf 4 23 0 1 1 25 25]¿O es presuntuoso compararme con esas figuras ilustres?[n][uf 1 1][e]

[msg MSG_012_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 0 25 0 0][uf 4 23 0 1 1 25 25]Je, ¿empaña tu imagen de tan ilustres personajes imaginarlos al mismo nivel que nosotros?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 0 26 0 0]Cada uno interpreta el arte a su manera. Es parte de lo que lo hace tan interesante.[n][uf 1 1][e]

[msg MSG_013_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 27 0 0][uf 4 23 0 1 0 25 25]A ver, es natural considerar las cosas, ¿no?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 0 28 0 0][uf 4 23 0 1 1 25 25]Ah, ¿te estabas preocupando por mí? Gracias, [uf 4 1].[n][uf 1 1][e]

[msg MSG_014_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 29 0 0]Perdona, no quería distraerte de la lectura.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 30 0 0]¿Seguimos?[n][uf 1 1][e]

[msg MSG_015_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 31 0 0][uf 4 23 0 1 0 25 25]Anda, mira la hora. Creo que ya es suficiente por hoy.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 0 32 0 0][uf 4 23 0 1 1 25 25][uf 5 13 4 1 5]Ha sido un rato muy agradable, solo se oía el sonido de pasar las páginas.[n][uf 1 1][e]

[msg MND_016_0_0]
[uf 0 5 65278][uf 2 1]Al aprender sobre las hazañas de[n]personajes ilustres, mi [uf 4 30 0 1 1 0] ha mejorado...[n][uf 1 1][e]

[msg MSG_017_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 0 33 0 0]Me gustaría seguir hablando de lectura contigo otro día. Pero ahora, buenas noches.[n][uf 1 1][e]

