[msg MSG_000_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0][uf 3 1 3 0 65535 11484 0 0]Fiu, menos mal que sigue estando el libro de ilustraciones...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 4 23 0 109 3 25 25]Pero...[n][uf 1 1][e]

[msg MSG_001_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0]Perdona el cambio de tema. Sigo preocupada por el dinero desaparecido...[n][uf 1 1][e]

[msg MSG_002_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 3 0 65535 11472 0 0]Espero que sea un error...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0]Es triste pensar que podría haber un ladrón en nuestro instituto...[n][uf 1 1][e]

[sel SEL_003_0_0 top]
[uf 0 5 65278][uf 2 1]No te preocupes, no ha sido un ladrón.[e]
[uf 0 5 65278][uf 2 1]¿Cuánto falta?[e]
[uf 0 5 65278][uf 2 1]Quizá se arrepienta ahora.[e]

[msg MSG_004_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0][uf 3 1 3 0 65535 11467 0 0][uf 5 13 9 30 109]C-claro, tienes razón. No puede ser.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0]Como miembro del consejo estudiantil, no debería hacer acusaciones así. Debería seguir tu ejemplo, [uf 4 1].[n][uf 1 1][e]

[msg MND_005_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]Chihiro está impresionada.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Siento que hoy nuestra relación se ha estrechado.[n][uf 1 1][e]

[msg MSG_006_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 3 0 65535 11450 0 0]¿Cuánto dinero? Mmm, no creo que la cantidad realmente importe...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0]Por pequeña o grande que sea la suma, el robo es un delito. No debemos tomarlo a la ligera...[n][uf 1 1][e]

[msg MND_007_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]Chihiro parece triste.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Siento que hoy nuestra relación no ha cambiado nada...[n][uf 1 1][e]

[msg MSG_008_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 3 0 65535 11450 0 0]No quiero asumir que de verdad haya un ladrón, pero... tal vez tengas razón.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0][uf 4 23 0 109 0 25 25][uf 5 13 9 15 109]Quizá solo fue el calentón... No quiero pensar que ha sido un acto de maldad...[n][uf 1 1][e]

[msg MND_009_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]Chihiro se sonroja.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Hoy he aprendido un poco más sobre ella.[n][uf 1 1][e]

[msg MSG_010_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0][uf 3 1 3 0 65535 11445 0 0]Perdona, no deberías escuchar mis preocupaciones en tu día libre...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0]Mmm, ¿te parece bien si te invito a algo como agradecimiento?[n][uf 1 1][e]

[msg MND_011_0_0 [DEV: Internal MES]]
[uf 0 5 65278][uf 2 1]Hemos pasado un rato más juntas en la zona de tiendas antes de volver a la residencia.[n][uf 1 1][e]

