[msg MSG_000_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]Everyone's working so hard...[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]So are you.[e]
[uf 0 5 65278][uf 2 1]What's the matter?[e]

[msg MSG_002_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]Is that what it seems like to you, [uf 4 1]-chan? That I'm working hard?[n][uf 1 1][e]

[msg MSG_003_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]Ah, sorry. I just wanted you to lend me an ear.[n][uf 1 1][e]

[msg MSG_004_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]Well, I told my dad about studying abroad.[n][uf 1 1][e]

[msg MSG_004_5_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]He said I should give it a try. And just the other day, he was telling me to quit.[n][uf 1 1][e]

[msg MSG_004_7_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]He's always wanted me to be a doctor till now, so for him to say that...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]I just don't know what to think.[n][uf 1 1][e]

[sel SEL_005_0_0 top]
[uf 0 5 65278][uf 2 1]Will you study abroad?[e]
[uf 0 5 65278][uf 2 1]It's your choice now.[e]

[msg MSG_006_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 0 8 0 0][uf 5 13 11 5 108]Y-Yeah, but it kinda feels like I'm doing it because that's what my dad wants.[n][uf 1 1][e]

[msg MSG_007_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 0 9 0 0][uf 5 13 11 15 108]Y-Yeah, that's true, but at the same time...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]If I study abroad, it kinda feels like I'm doing it because that's what my dad wants.[n][uf 1 1][e]

[msg MSG_008_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 0 11 0 0]Thanks. This has been eating me up for a while, and it feels good to talk about it.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]You're really the only one I can talk to about this stuff, [uf 4 1]-chan.[n][uf 1 1][e]

[msg MND_009_0_0]
[uf 0 5 65278][uf 2 1]Hiraga expressed his gratitude to me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like we're becoming better friends.[n][uf 1 1][e]

[msg MSG_010_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]It's great that you've always made your own decisions. Not like me, though.[n][uf 1 1][e]

[msg MSG_011_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]Sorry. We should get going.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 0 15 0 0][uf 4 23 0 1 1 25 25]My driver's picking me up, so I can have him drop you off near your dorm if you want.[n][uf 1 1][e]

[msg MND_012_0_0]
[uf 0 5 65278][uf 2 1]Hiraga and I left school together.[n][uf 1 1][e]

