[msg MSG_000_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 1 65535 65535 0 0][uf 3 1 3 0 65535 11897 0 0]Oishii! That was very delicious![n][uf 1 1][e]

[msg MSG_001_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 1 65535 65535 0 0]Japanese sweets do a great job showing the appeal of sugar.[n][uf 1 1][e]

[msg MSG_002_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 0 65535 65535 0 0][uf 3 1 3 0 65535 11873 0 0]Azuki, though small, is packed with such divine flavor...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 112 0 65535 65535 0 0]What exactly is it? It just looks like the eggs of an insect to me.[n][uf 1 1][e]

[sel SEL_003_0_0 top]
[uf 0 5 65278][uf 2 1]I'm not sure.[e]
[uf 0 5 65278][uf 2 1]It IS insect eggs.[e]
[uf 0 5 65278][uf 2 1]It's beans.[e]

[msg MSG_004_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 3 65535 65535 0 0][uf 3 1 3 0 65535 11865 0 0]Not even you know, [uf 4 2]-sama?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 112 3 65535 65535 0 0]This is quite problématique then—very puzzling indeed. Perhaps we will never discover the truth...[n][uf 1 1][e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]Bebe looks troubled.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like we didn't get any closer today...[n][uf 1 1][e]

[msg MSG_006_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 4 65535 65535 0 0][uf 3 1 3 0 65535 11888 0 0][uf 5 13 15 15 112]Hontou!? Really!? Do you mean to say that my guess was correct!?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 112 1 65535 65535 0 0][uf 4 23 0 112 1 25 25]Once again, I have learned something new about Japan![n][uf 1 1][e]

[msg MND_007_0_0]
[uf 0 5 65278][uf 2 1]Bebe seems happy.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I learned a little more about him today...[n][uf 1 1][e]

[msg MSG_008_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 4 65535 65535 0 0][uf 3 1 3 0 65535 11888 0 0][uf 5 13 15 30 112]Beans!? You mean to tell me something so red and soft is a bean!?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 112 1 65535 65535 0 0][uf 4 23 0 112 1 25 25]I have once again learned something new about Japan![n][uf 1 1][e]

[msg MND_009_0_0]
[uf 0 5 65278][uf 2 1]Bebe seems very happy.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like we became a lot closer today.[n][uf 1 1][e]

[msg MSG_010_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 0 65535 65535 0 0][uf 3 1 3 0 65535 11908 0 0]So then the secret to Japanese sweets must be hidden within the azuki...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 112 0 65535 65535 0 0]Where would I be able to buy some? Come, let us search for azuki, [uf 4 2]-sama![n][uf 1 1][e]

[msg MND_011_0_0]
[uf 0 5 65278][uf 2 1]After shopping with Bebe,[n]I returned to the dorm.[n][uf 1 1][e]

