[msg MSG_000_0_0 [Profesor Edogawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1081 1 65535 65535 0 0][uf 3 1 3 0 65535 14823 0 0]¿Qué te trae a la enfermería? Je, je.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1081 0 65535 65535 0 0]Ten en cuenta que estás interrumpiendo mis, mmm..., actividades escolares.[n][uf 1 1][e]

[msg MSG_000_5_0 [Profesor Edogawa]]
[uf 0 5 65278][uf 2 1][uf 4 5 1081 0 65535 65535 0 0]¿Eh? Tú estás perfectamente. ¡A mí no me la das![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 1081 0 65535 65535 0 0][uf 3 1 3 0 65535 14803 0 0]No necesito a estudiantes repantigadas en mi despacho. ¡Fuera! ¡Largo![n][uf 1 1][e]

[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]Imagino que solo accederá a verme si tengo mala cara.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Si voy a ver al profesor Edogawa después de ir a la Tártaro, a lo mejor se comporta diferente.[n][uf 1 1][e]

