[msg MSG_000_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0][uf 3 1 3 0 65535 10863 0 0]Oye, perdona por la chapa profunda que te di la otra vez, pero ¿crees que podrías volver a ayudarme?[n][uf 1 1][e]

[msg MSG_001_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0]Hoy voy a casa de mi hermana y quiero comprarle algo a mi sobrino.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0]Lo de elegir regalos se me da fatal y he pensado en pedir una segunda opinión. Y ahí entras tú.[n][uf 1 1][e]

[msg MSG_002_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0]¿Qué le compro a un niño de 5 años con la pierna lesionada?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0][uf 3 1 3 0 65535 10850 0 0]¿Alguna idea?[n][uf 1 1][e]

[sel SEL_003_0_0 top]
[uf 0 5 65278][uf 2 1]Calzado deportivo.[e]
[uf 0 5 65278][uf 2 1]Un videojuego.[e]
[uf 0 5 65278][uf 2 1]Ropa.[e]

[msg MSG_004_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0][uf 3 1 3 0 65535 10827 0 0]Tía, que te acabo de decir que se ha lesionado una pierna.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0]¿Me estabas escuchando? Madre mía, a ver si me he equivocado en pedirte ayuda.[n][uf 1 1][e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]Miyamoto parece decepcionado con mi respuesta.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Siento que hoy nuestra relación no ha cambiado nada...[n][uf 1 1][e]

[msg MSG_006_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 1 101 65535 0 0][uf 3 1 3 0 65535 10879 0 0][uf 5 13 8 30 105]Bien pensado... Así, no se aburrirá en casa.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 1 101 65535 0 0]Pero los juegos pueden ser muy caros... ¡No! ¡Es para mi sobrino! ¡Lo que sea por mi sobrino![n][uf 1 1][e]

[msg MND_007_0_0]
[uf 0 5 65278][uf 2 1]Parece que Miyamoto se lo está pasando muy bien.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Siento que hoy nuestra relación se ha estrechado.[n][uf 1 1][e]

[msg MSG_008_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0][uf 3 1 3 0 65535 10887 0 0][uf 5 13 8 15 105]¿Me estás diciendo que dos adolescentes vamos a presentarnos a comprar en la sección infantil?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0]¿Y eso no va a resultar raro? Pero lo hago por mi sobrino... ¡Es el momento de poner a prueba el entrenamiento mental![n][uf 1 1][e]

[msg MND_009_0_0]
[uf 0 5 65278][uf 2 1]Parece que Miyamoto se lo toma en serio.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Hoy he aprendido un poco más sobre él.[n][uf 1 1][e]

[msg MSG_010_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 1 101 65535 0 0][uf 3 1 3 0 65535 10867 0 0]Bueno, en marcha. ¡Cuento contigo, [uf 4 1]![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0][uf 4 23 0 105 3 25 25]Y, eh... Si me falta dinero, ¿me lo podrías prestar?[n][uf 1 1][e]

[msg MND_011_0_0]
[uf 0 5 65278][uf 2 1]Tras ir de compras con Miyamoto, he vuelto a la residencia.[n][uf 1 1][e]

