[msg MSG_000_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]...So then I went to ask about it after class, and you know what happened?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]Ms. Miyahara just wouldn't stop talking! She wrote out some weird math formula and said, "It's beautiful, isn't it?"[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 0 0][uf 3 1 1 0 0 3 0 0][uf 4 23 0 1 3 25 25]All it did was make me more confused than I originally was. Guess I'll have to go ask again tomorrow.[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]You're so hardworking.[e]
[uf 0 5 65278][uf 2 1]Why go through all that trouble?[e]

[msg MSG_002_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]Y-You think so?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 5 0 0][uf 4 23 0 1 0 25 25]I guess it just feels wrong to not try and understand something.[n][uf 1 1][e]

[msg MSG_003_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]I mean... doesn't it feel wrong to not try and understand something?[n][uf 1 1][e]

[msg MSG_004_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]Anyways, I decided to start being serious about my future.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 8 0 0]Remember when I told you about what happened to me at school?[n][uf 1 1][e]

[msg MSG_005_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 9 0 0]It was when I handed in a blank answer sheet for that pop quiz, and I got yelled at by Ekoda...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]Back then, I just wanted to graduate and go to a community college or something.[n][uf 1 1][e]

[msg MSG_005_3_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 11 0 0]But after coaching those kids, I started to realize something.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]I enjoy helping people who are willing to give it their all. So, I've finally figured out what I wanna do with my life.[n][uf 1 1][e]

[msg MSG_005_5_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]Can you guess what it is?[n][uf 1 1][e]

[sel SEL_006_0_0 top]
[uf 0 5 65278][uf 2 1]A track and field star?[e]
[uf 0 5 65278][uf 2 1]An instructor?[e]
[uf 0 5 65278][uf 2 1]A nursery teacher?[e]
[uf 0 5 65278][uf 2 1]No idea...[e]

[msg MSG_007_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 0 0][uf 3 1 1 0 0 14 0 0][uf 5 13 12 5 106]No, not that. I'd rather just teach. Being a professional athlete is too hard.[n][uf 1 1][e]

[msg MSG_008_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 15 0 0][uf 5 13 12 15 106]Hmm... Close! You almost got it, Ms. Ex-Assistant Coach![n][uf 1 1][e]

[msg MSG_009_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 16 0 0][uf 5 13 12 5 106]I did consider that one too, but I decided I should focus on one thing specifically.[n][uf 1 1][e]

[msg MSG_010_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 17 0 0][uf 5 13 12 5 106]Come on, [uf 4 1]-chan, are you really that dense? Or did I not spell it out enough?[n][uf 1 1][e]

[msg MSG_011_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 18 0 0]I'm thinking of becoming an athletic trainer.[n][uf 1 1][e]

[msg MSG_011_3_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 19 0 0]It's their job to monitor each athlete's diet, and help them plan their training routine.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 20 0 0]So I'll go to professional school once I graduate, and then work towards earning my certification when I turn twenty.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 21 0 0]Between the general education requirements and the classes for my major, it's gonna be over 350 hours.[n][uf 1 1][e]

[msg MSG_011_5_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 22 0 0]That's why I'm gonna start studying right now.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 23 0 0]Improving my writing is my first goal. It took me all night to finish that three page essay.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 24 0 0]But those kids had a huge influence on me. I know I only agreed to coach them on a whim, but teaching them really made me think.[n][uf 1 1][e]

[msg MSG_011_7_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 0 0][uf 3 1 1 0 0 25 0 0]I started wondering what I could teach my own kids one day... And I realized I didn't have the slightest clue.[n][uf 1 1][e]

[msg MSG_012_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 26 0 0]If you hadn't been there with me, I don't think I could've stuck it out until the end.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 27 0 0]And I definitely never would've thought about my future, either.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 28 0 0][uf 4 23 0 1 1 25 25]So... thanks.[n][uf 1 1][e]

[msg MND_013_0_0]
[uf 0 5 65278][uf 2 1]Yuko seems appreciative.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like our relationship has grown...[n][uf 1 1][e]

[msg MSG_014_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 0 0][uf 3 1 1 0 0 29 0 0]A-Also...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 0 0][uf 3 1 1 0 0 30 0 0]I know I'm always asking you to stick around and help me with stuff.[n][uf 1 1][e]

[msg MSG_014_5_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 0 0][uf 3 1 1 0 0 31 0 0]I just... I kinda feel bad about it. I'm sorry.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 0 0][uf 3 1 1 0 0 32 0 0]I realized now that I might've been relying too much on you.[n][uf 1 1][e]

[sel SEL_015_0_0 top]
[uf 0 5 65278][uf 2 1]I don't mind.[e]
[uf 0 5 65278][uf 2 1]You can rely on me even more.[e]

[msg MSG_016_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 0 0][uf 3 1 0 0 0 33 0 0]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 0 0][uf 3 1 1 0 0 34 0 0]Wh-Why...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 0 0][uf 3 1 1 0 0 35 0 0]Why are you... so nice to me?[n][uf 1 1][e]

[msg MND_017_0_0]
[uf 0 5 65278][uf 2 1]Yuko seems restless.[n][uf 1 1][e]

[msg MND_018_0_0]
[uf 0 5 65278][uf 2 1]I better choose my words carefully here...[n][uf 1 1][e]

[msg MND_019_0_0]
[uf 0 5 65278][uf 2 1]I better choose my words carefully here...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Come to think of it, [uf 0 1 2]I have a special[uf 0 1 27][n][uf 0 1 2]relationship with another person already[uf 0 1 27]...[n][uf 1 1][e]

[msg MSG_016_5_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 36 0 0]Are you like this... just with me? N-No, no, th-that can't be it, huh...[n][uf 1 1][e]

[sel SEL_020_0_0 top]
[uf 0 5 65278][uf 2 1]It's because I love you.[uf 2 9 1 1 352][e]
[uf 0 5 65278][uf 2 1]It's because you're a close friend.[e]

[msg MSG_021_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 0 0 0 37 0 0]......[n][uf 1 1][e]

[msg MSG_021_5_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 4 65535 65535 0 0][uf 3 1 1 0 0 38 0 0][uf 4 23 0 1 4 25 25]Huh!?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 4 65535 65535 0 0][uf 3 1 1 0 0 39 0 0]What? Y-You mean, me...?[n][uf 1 1][e]

[msg MSG_022_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 4 65535 65535 0 0][uf 3 1 1 0 0 40 0 0]A-Are you... Are you sure!? I'm not girly or anything like that, y'know?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 4 65535 65535 0 0][uf 3 1 1 0 0 41 0 0]What's happening...? Is this a dream?[n][uf 1 1][e]

[sel SEL_023_0_0 top]
[uf 0 5 65278][uf 2 1]I love you, Yuko.[e]
[uf 0 5 65278][uf 2 1]It's not a dream.[e]

[msg MSG_024_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 4 65535 65535 1 0][uf 3 1 1 0 0 42 0 0][uf 5 13 12 5 106]U-Um...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 4 65535 65535 1 0][uf 3 1 1 0 0 43 0 0]Me... Me too...[n][uf 1 1][e]

[msg MND_025_0_0]
[uf 0 5 65278][uf 2 1]Yuko's face is bright red...[n][uf 1 1][e]

[msg MSG_026_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 4 65535 65535 1 0][uf 3 1 1 0 0 44 0 0][uf 5 13 12 5 106]Y-Yeah, guess not![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 1 0][uf 3 1 1 0 0 45 0 0][uf 4 23 0 1 3 25 25]My heart is pumping so fast, there's no way it could be a dream.[n][uf 1 1][e]

[msg MND_027_0_0]
[uf 0 5 65278][uf 2 1]Yuko's face is bright red...[n][uf 1 1][e]

[msg MSG_028_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 1 0][uf 3 1 1 0 0 46 0 0]I... feel the same way as you do, [uf 4 1]-chan.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 1 0][uf 3 1 1 0 0 47 0 0]That's why... I'm so happy.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 1 0][uf 3 1 1 0 0 48 0 0]...Thank you.[n][uf 1 1][e]

[msg MND_029_0_0]
[uf 0 5 65278][uf 2 1]I have entered a special[n]relationship with Yuko...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]There's no going back now.[n][uf 1 1][e]

[msg MSG_030_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 4 65535 65535 0 0][uf 3 1 1 0 0 49 0 0]...Uh, I have to go. I've gotta study![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 1 0][uf 3 1 0 0 0 50 0 0][uf 4 23 0 1 1 25 25]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 1 0][uf 3 1 1 0 0 51 0 0]Um, I'm looking forward to... us.[n][uf 1 1][e]

[msg MND_031_0_0]
[uf 0 5 65278][uf 2 1]After saying goodbye to Yuko,[n]I decided to go back to the dorm.[n][uf 1 1][e]

[msg MSG_032_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 52 0 0]Y-Yeah, of course![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 53 0 0]I sure am lucky to have such a good friend who's so kind and reliable.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 0 0][uf 3 1 1 0 0 54 0 0][uf 4 23 0 1 3 25 25]Although, sometimes you worry me a little...[n][uf 1 1][e]

[msg MSG_033_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 55 0 0][uf 4 1]-chan, sometimes you say suggestive things with a straight face, y'know?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 56 0 0]I get the feeling you might give someone the wrong idea.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 2 65535 65535 0 0][uf 3 1 1 0 0 57 0 0][uf 4 23 0 1 2 25 25]So you should really be careful about that. It could land you in some hot water.[n][uf 1 1][e]

[sel SEL_034_0_0 top]
[uf 0 5 65278][uf 2 1]Okay, I will.[e]
[uf 0 5 65278][uf 2 1]Why?[e]

[msg MSG_035_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 58 0 0][uf 5 13 12 5 106]That's the way. Take my advice to heart![n][uf 1 1][e]

[msg MND_036_0_0]
[uf 0 5 65278][uf 2 1]Yuko seems relieved.[n][uf 1 1][e]

[msg MSG_037_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 4 65535 65535 0 0][uf 3 1 1 0 0 59 0 0]Wait, are you seriously asking me that?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 3 65535 65535 0 0][uf 3 1 1 0 0 60 0 0][uf 4 23 0 1 3 25 25]Um, just watch your back out there, okay? Seems like you're headed for trouble.[n][uf 1 1][e]

[msg MND_038_0_0]
[uf 0 5 65278][uf 2 1]Yuko seems to be worried about me...[n][uf 1 1][e]

[msg MSG_039_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 61 0 0]...Sorry, this isn't what I wanted to talk about.[n][uf 1 1][e]

[msg MSG_040_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 62 0 0]Um, [uf 4 1]-chan...[n][uf 1 1][e]

[msg MSG_040_5_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 63 0 0]Thank you again for coaching with me. I'm glad I had someone like you to rely on.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 0 0 0 64 0 0]......[n][uf 1 1][e]

[msg MSG_040_7_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 65 0 0]Next time, I'll be there to support you![n][uf 1 1][e]

[msg MSG_116_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 66 0 0]If there's anything I can help with, just let me know, okay? We're friends, aren't we?[n][uf 1 1][e]

[msg MSG_041_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 67 0 0]I'm gonna head out. I've got to work on my modern literature and English today.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 68 0 0]See ya![n][uf 1 1][e]

[msg MND_042_0_0]
[uf 0 5 65278][uf 2 1]Yuko left the café in a hurry.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I should head back to the dorm...[n][uf 1 1][e]

