[msg AST_DNG_TEST [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_DORMITORY_01 [岳羽 ゆかり]]
[f 2 1][vp 3 0 65535 1028 0 0]桐条先輩たち…大丈夫かな…[n][f 1 2 80][e]

[msg AST_DNG_DORMITORY_02 [岳羽 ゆかり]]
[f 2 1][vp 3 0 65535 1077 0 0]ま、窓から入ってきたりしないよね…[n][f 1 2 80][e]

[msg AST_DNG_DORMITORY_03 [岳羽 ゆかり]]
[f 2 1][vp 3 0 65535 1056 0 0]ごめんね、寝てるとこ急に…[n]あとでちゃんと説明するから。[n][f 1 2 120][e]

[msg AST_DNG_DORMITORY_04 [岳羽 ゆかり]]
[f 2 1][vp 3 0 65535 1064 0 0]まさか、窓から逃げようとか…？[n]それは無茶だって！[n][f 1 2 120][e]

[msg AST_DNG_DORMITORY_05 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_DORMITORY_06 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_DORMITORY_07 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_DORMITORY_08 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_DORMITORY_09 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_DORMITORY_10 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_TUTORIAL_01 [岳羽 ゆかり]]
[f 2 1][vp 3 0 65535 1028 0 0]先輩って、どこまで私たちのこと[n]見えてるのかな…？[n][f 1 2 120][e]

[msg AST_DNG_TUTORIAL_02 [伊織 順平]]
[f 2 1][vp 3 0 65535 2004 0 0]ここ、マジで学校ん中なのか…？[n][f 1 2 80][e]

[msg AST_DNG_TUTORIAL_03 [伊織 順平]]
[f 2 1]この辺…オレらの教室あるトコ[n]だったりしてな。[n][f 1 2 120][e]

[msg AST_DNG_TUTORIAL_04 [伊織 順平]]
[f 2 1][vp 3 0 65535 2101 0 0]うおっ！？　勝手に開くのかよ…[n]ビックリさせんなっつの…[n][f 1 2 120][e]

[msg AST_DNG_TUTORIAL_05 [桐条 美鶴]]
[f 2 1][vp 2 0 1 10117 0 0]出来る限りサポートはする。[n]多くを学んで来て欲しい。[n][w][e]

[msg AST_DNG_TUTORIAL_06 [伊織 順平]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_TUTORIAL_07 [桐条 美鶴]]
[f 2 1][vp 1 0 1 20507 0 0]では、引き続き探索を頼む。[n][w][e]

[msg AST_DNG_TUTORIAL_08 [桐条 美鶴]]
[f 2 1]まだ敵の反応は残っているな。[n]探索を続けよう。[n][w][e]

[msg AST_DNG_TUTORIAL_09 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_TUTORIAL_10 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_TUTORIAL_11 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_TUTORIAL_12 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_TUTORIAL_13 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_TUTORIAL_14 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_TUTORIAL_15 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_TUTORIAL_16 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_TUTORIAL_17 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_TUTORIAL_18 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_TUTORIAL_19 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_TUTORIAL_20 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_TUTORIAL_21 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_TUTORIAL_22 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_TUTORIAL_23 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_TUTORIAL_24 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_TUTORIAL_25 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_TUTORIAL_26 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_TUTORIAL_27 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_TUTORIAL_28 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_TUTORIAL_29 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_TUTORIAL_30 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_MONORAIL_01 [岳羽 ゆかり]]
[f 2 1][vp 1 0 1 20617 0 0]こんなトコからもタルタロスが…[n]なんか不吉な感じ…[n][w][e]

[msg AST_DNG_MONORAIL_02 [伊織 順平]]
[f 2 1][vp 1 0 1 20618 0 0]うわ、高っ！[n]何かスースーする…[n][w][e]

[msg AST_DNG_MONORAIL_03 [岳羽 ゆかり]]
[f 2 1][vp 1 0 1 20619 0 0]何か薄気味悪いね…[n][f 1 2 80][e]

[msg AST_DNG_MONORAIL_04 [伊織 順平]]
[f 2 1][vp 1 0 1 20620 0 0]し、静かだな…[n][w][e]

[msg AST_DNG_MONORAIL_05 [岳羽 ゆかり]]
[f 2 1][vp 1 0 1 20621 0 0]順平、なんであんなに…？[n]すぐ追いかけよう！[n][w][e]

[msg AST_DNG_MONORAIL_06 [岳羽 ゆかり]]
[f 2 1][vp 1 0 1 20622 0 0]急ごう！[n]時間ないよ！[n][w][e]

[msg AST_DNG_MONORAIL_07 [伊織 順平]]
[f 2 1][vp 1 0 1 20623 0 0]は、早く止めないと乗客が…ってか[n]オレらがやばいぞ！[n][w][e]

[msg AST_DNG_MONORAIL_08 [岳羽 ゆかり]]
[f 2 1][vp 1 0 1 20624 0 0]どんどん速くなってる…[n][w][e]

[msg AST_DNG_MONORAIL_09 [伊織 順平]]
[f 2 1][vp 1 0 1 20625 0 0]ヤベェ…[n]モタモタしてらんねえぞ！[n][w][e]

[msg AST_DNG_MONORAIL_10 [伊織 順平]]
[f 2 1][vp 3 0 65535 2118 0 0]いよいよ、大物か！[n][f 1 2 80][e]

[msg AST_DNG_MONORAIL_11 [岳羽 ゆかり]]
[f 2 1][vp 3 0 65535 1123 0 0]ちょっと、気合い入れすぎて[n]空回りしないでよね。[n][f 1 2 120][e]

[msg AST_DNG_MONORAIL_12 [岳羽 ゆかり]]
[f 2 1][vp 3 0 65535 1006 0 0]あそこで止まってるのが…？[n]見たとこ普通だけど…[n][f 1 2 120][e]

[msg AST_DNG_MONORAIL_13 [岳羽 ゆかり]]
[f 2 1][vp 3 0 65535 1028 0 0]順平、この車両にもいないね。[n][f 1 2 80][e]

[msg AST_DNG_MONORAIL_14 [伊織 順平]]
[f 2 1]オレが叩き潰してやるぜっ！[n]どっからでも来やがれ！[n][w][e]

[msg AST_DNG_MONORAIL_15 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_MONORAIL_16 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_MONORAIL_17 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_MONORAIL_18 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_MONORAIL_19 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_MONORAIL_20 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_MONORAIL_21 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_MONORAIL_22 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_MONORAIL_23 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_MONORAIL_24 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_MONORAIL_25 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_MONORAIL_26 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_MONORAIL_27 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_MONORAIL_28 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_MONORAIL_29 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_MONORAIL_30 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_MONORAIL_31 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_MONORAIL_32 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_MONORAIL_33 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_MONORAIL_34 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_MONORAIL_35 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_MONORAIL_36 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_MONORAIL_37 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_MONORAIL_38 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_MONORAIL_39 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_MONORAIL_40 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_NIGHT_SCHOOL_01 [岳羽 ゆかり]]
[f 2 1][vp 1 0 1 20626 0 0]夜の学校って気味が悪いね。[n]早く職員室に行こ。[n][w][e]

[msg AST_DNG_NIGHT_SCHOOL_02 [岳羽 ゆかり]]
[f 2 1][vp 1 0 1 20627 0 0]玄関で合流だよね。[n][w][e]

[msg AST_DNG_NIGHT_SCHOOL_03 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_NIGHT_SCHOOL_04 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_NIGHT_SCHOOL_05 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_NIGHT_SCHOOL_06 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_NIGHT_SCHOOL_07 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_NIGHT_SCHOOL_08 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_NIGHT_SCHOOL_09 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_NIGHT_SCHOOL_10 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_NIGHT_SCHOOL_11 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_NIGHT_SCHOOL_12 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_NIGHT_SCHOOL_13 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_NIGHT_SCHOOL_14 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_NIGHT_SCHOOL_15 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_NIGHT_SCHOOL_16 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_NIGHT_SCHOOL_17 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_NIGHT_SCHOOL_18 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_NIGHT_SCHOOL_19 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_NIGHT_SCHOOL_20 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_NIGHT_SCHOOL_21 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_NIGHT_SCHOOL_22 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_NIGHT_SCHOOL_23 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_NIGHT_SCHOOL_24 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_NIGHT_SCHOOL_25 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_NIGHT_SCHOOL_26 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_NIGHT_SCHOOL_27 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_NIGHT_SCHOOL_28 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_NIGHT_SCHOOL_29 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_NIGHT_SCHOOL_30 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_FUKA_RESCUE_01 [桐条 美鶴]]
[f 2 1][vp 1 0 1 10021 0 0]…明彦……は…[n]この…階……[n][w][e]

[msg AST_DNG_FUKA_RESCUE_02 [山岸 風花]]
[f 2 1]……[n][f 1 2 80][vp 1 0 1 10022 0 0]…誰？[n][w][e]

[msg AST_DNG_FUKA_RESCUE_03 [山岸 風花]]
[f 2 1][vp 1 0 1 10023 0 0]人…なの？[n][w][e]

[msg AST_DNG_FUKA_RESCUE_04 [桐条 美鶴]]
[f 2 1][vp 1 0 1 10024 0 0]聞こえ……[n]…応答……くれ…[n][w][e]

[msg AST_DNG_FUKA_RESCUE_05 [山岸 風花]]
[f 2 1][vp 1 0 1 10025 0 0]誰か…いるの？[n][w][e]

[msg AST_DNG_FUKA_RESCUE_06 [山岸 風花]]
[f 2 1][vp 1 0 1 10026 0 0]お願い…答えて…[n][w][e]

[msg AST_DNG_FUKA_RESCUE_07 [桐条 美鶴]]
[f 2 1][vp 1 0 1 10122 0 0]現在地…どこ……[n]応答…し…くれ…[n][w][e]

[msg AST_DNG_FUKA_RESCUE_08 [山岸 風花]]
[f 2 1][vp 1 0 1 10124 0 0]ここは…どこ？[n]なぜ…ここにいるの？[n][w][e]
[f 2 1][vp 1 0 1 10125 0 0]お願い…答えて…[n][w][e]

[msg AST_DNG_FUKA_RESCUE_09 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_FUKA_RESCUE_10 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_FUKA_RESCUE_11 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_FUKA_RESCUE_12 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_FUKA_RESCUE_13 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_FUKA_RESCUE_14 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_FUKA_RESCUE_15 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_FUKA_RESCUE_16 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_FUKA_RESCUE_17 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_FUKA_RESCUE_18 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_FUKA_RESCUE_19 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_FUKA_RESCUE_20 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_FUKA_RESCUE_21 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_FUKA_RESCUE_22 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_FUKA_RESCUE_23 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_FUKA_RESCUE_24 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_FUKA_RESCUE_25 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_FUKA_RESCUE_26 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_FUKA_RESCUE_27 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_FUKA_RESCUE_28 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_FUKA_RESCUE_29 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_FUKA_RESCUE_30 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_THEURGIA_01 [桐条 美鶴]]
[f 2 1][vp 3 0 65535 4131 0 0]この緊張感、久しぶりだな。[n][f 1 2 80][e]

[msg AST_DNG_THEURGIA_02 [真田 明彦]]
[f 2 1][vp 3 0 65535 3061 0 0]足を引っ張るなよ？[n][f 1 2 80][e]

[msg AST_DNG_THEURGIA_03 [桐条 美鶴]]
[f 2 1][vp 3 0 65535 4122 0 0]フ、誰に言っている。[n]後れを取るつもりはない。[n][f 1 2 120][e]

[msg AST_DNG_THEURGIA_04 [桐条 美鶴]]
[f 2 1][vp 1 0 1 20563 0 0]よし、行くぞ！[n][w][e]

[msg AST_DNG_THEURGIA_05 [山岸 風花]]
[f 2 1][vp 1 0 1 20564 0 0]シャドウ、確認できますか？[n]すぐ目の前です！[n][w][e]

[msg AST_DNG_THEURGIA_06 [岳羽 ゆかり]]
[f 2 1][vp 1 0 1 20565 0 0]いるいる、じゃあコイツもですね。[n][w][e]

[msg AST_DNG_THEURGIA_07 [桐条 美鶴]]
[f 2 1][vp 1 0 1 20566 0 0]ああ、片付けるぞ…！[n][w][e]

[msg AST_DNG_THEURGIA_08 [山岸 風花]]
[f 2 1][vp 1 0 1 20560 0 0]シャドウに接近！[n]戦闘態勢を…！[n][w][e]

[msg AST_DNG_THEURGIA_09 [岳羽 ゆかり]]
[f 2 1][vp 1 0 1 10035 0 0]行こっか、[nf]。[n]上り階段のところまで。[n][w][e]

[msg AST_DNG_THEURGIA_10 [山岸 風花]]
[f 2 1][vp 3 0 65535 5008 0 0]シャドウ、残り２体です！[n][f 1 2 80][e]

[msg AST_DNG_THEURGIA_11 [桐条 美鶴]]
[f 2 1][vp 3 0 65535 4115 0 0]ちょうど半分か。[n]油断せずに残りも片付けるぞ。[n][f 1 2 120][e]

[msg AST_DNG_THEURGIA_12 [山岸 風花]]
[f 2 1][vp 3 0 65535 5143 0 0]シャドウ、残り１体です。[n]ファイトですよ！[n][f 1 2 120][e]

[msg AST_DNG_THEURGIA_13 [桐条 美鶴]]
[f 2 1][vp 3 0 65535 4117 0 0]ラストだ。[n]気を抜くなよ！[n][f 1 2 120][e]

[msg AST_DNG_THEURGIA_14 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_THEURGIA_15 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_THEURGIA_16 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_THEURGIA_17 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_THEURGIA_18 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_THEURGIA_19 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_THEURGIA_20 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_THEURGIA_21 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_THEURGIA_22 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_THEURGIA_23 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_THEURGIA_24 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_THEURGIA_25 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_THEURGIA_26 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_THEURGIA_27 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_THEURGIA_28 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_THEURGIA_29 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_THEURGIA_30 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_THEURGIA_31 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_THEURGIA_32 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_THEURGIA_33 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_THEURGIA_34 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_THEURGIA_35 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_THEURGIA_36 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_THEURGIA_37 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_THEURGIA_38 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_THEURGIA_39 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_THEURGIA_40 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_HOTEL_01 [岳羽 ゆかり]]
[f 2 1][vp 1 0 1 20628 0 0]ほら、さっさと倒すよ！[n][w][e]

[msg AST_DNG_HOTEL_02 [伊織 順平]]
[f 2 1][vp 1 0 1 20629 0 0]今日こそはオレにバシッっと[n]決めさせてもらうぜ！[n][w][e]

[msg AST_DNG_HOTEL_03 [真田 明彦]]
[f 2 1][vp 1 0 1 20630 0 0]早く行くぞ！[n][w][e]

[msg AST_DNG_HOTEL_04 [桐条 美鶴]]
[f 2 1][vp 1 0 1 20631 0 0]宿泊客に被害が及ぶ前に[n]さっさと倒すぞ。[n][w][e]

[msg AST_DNG_HOTEL_05 [岳羽 ゆかり]]
[f 2 1][vp 1 0 1 20632 0 0]じゃ、帰ろっか？[n][w][e]

[msg AST_DNG_HOTEL_06 [伊織 順平]]
[f 2 1][vp 1 0 1 20633 0 0]クソッ、これじゃダメだ…[n][w][e]

[msg AST_DNG_HOTEL_07 [真田 明彦]]
[f 2 1][vp 1 0 1 20634 0 0]今回のはあっさりしてたな…[n][w][e]

[msg AST_DNG_HOTEL_08 [桐条 美鶴]]
[f 2 1][vp 1 0 1 20635 0 0]今回はこれで終わりか…[n][w][e]

[msg AST_DNG_HOTEL_09 [岳羽 ゆかり]]
[f 2 1][vp 1 0 1 20636 0 0]え、マジ、どこにいるの？[n][w][e]

[msg AST_DNG_HOTEL_10 [伊織 順平]]
[f 2 1][vp 1 0 1 20637 0 0]あ？　どこにもいねえぞ…[n][w][e]

[msg AST_DNG_HOTEL_11 [真田 明彦]]
[f 2 1][vp 1 0 1 20638 0 0]よし、こちらでも探すぞ。[n][w][e]

[msg AST_DNG_HOTEL_12 [桐条 美鶴]]
[f 2 1][vp 1 0 1 20639 0 0]まだ終わってないというのか…[n][w][e]

[msg AST_DNG_HOTEL_13 [岳羽 ゆかり]]
[f 2 1][vp 1 0 1 20640 0 0]…行くよ！[n][w][e]

[msg AST_DNG_HOTEL_14 [岳羽 ゆかり]]
[f 2 1][vp 1 0 1 20641 0 0]鏡が何か変だったんだよな…[n][w][e]

[msg AST_DNG_HOTEL_15 [伊織 順平]]
[f 2 1][vp 1 0 1 20642 0 0]何だか知んねえけど[n]鏡を割りゃあいいんだろ？[n][w][e]

[msg AST_DNG_HOTEL_16 [真田 明彦]]
[f 2 1][vp 1 0 1 20643 0 0]鏡を割ればいいんだろ？[n]さっさと割って本体を倒すぞ。[n][w][e]

[msg AST_DNG_HOTEL_17 [桐条 美鶴]]
[f 2 1][vp 1 0 1 20644 0 0]鏡を割ればいいんだな？[n][w][e]

[msg AST_DNG_HOTEL_18 [岳羽 ゆかり]]
[f 2 1][vp 1 0 1 20645 0 0]鏡の前に立った時、[n]何か違和感があったんだよね…[n][w][e]

[msg AST_DNG_HOTEL_19 [伊織 順平]]
[f 2 1][vp 1 0 1 20646 0 0]鏡の違い？[n]ダメだ、オレ全然分かんねえ…[n][w][e]

[msg AST_DNG_HOTEL_20 [真田 明彦]]
[f 2 1][vp 1 0 1 20647 0 0]鏡に違いがある…[n]どういうことだ？[n][w][e]

[msg AST_DNG_HOTEL_21 [桐条 美鶴]]
[f 2 1][vp 1 0 1 20648 0 0]鏡を良く調べれば[n]違いが分かるのだろうか…？[n][w][e]

[msg AST_DNG_HOTEL_22 [岳羽 ゆかり]]
[f 2 1][vp 1 0 1 20649 0 0]私たちの姿が映らない鏡を割るんだよ。[n][w][e]

[msg AST_DNG_HOTEL_23 [伊織 順平]]
[f 2 1][vp 1 0 1 20650 0 0]えっ、どの鏡を割んの？[n][w][e]

[msg AST_DNG_HOTEL_24 [真田 明彦]]
[f 2 1][vp 1 0 1 20651 0 0]『姿の映らない鏡』を割るんだ。[n][w][e]

[msg AST_DNG_HOTEL_25 [桐条 美鶴]]
[f 2 1][vp 1 0 1 20652 0 0]割るのは『姿の映らない鏡』だな。[n][w][e]

[msg AST_DNG_HOTEL_26 [岳羽 ゆかり]]
[f 2 1][vp 1 0 1 20653 0 0]ほら、行くよ！[n][w][e]

[msg AST_DNG_HOTEL_27 [伊織 順平]]
[f 2 1][vp 1 0 1 20654 0 0]今度こそバシッっと決めてやる！[n][w][e]

[msg AST_DNG_HOTEL_28 [真田 明彦]]
[f 2 1][vp 1 0 1 20655 0 0]これでようやくメインイベントだ。[n][w][e]

[msg AST_DNG_HOTEL_29 [桐条 美鶴]]
[f 2 1][vp 1 0 1 20656 0 0]よし、これで終わりにしよう。[n][w][e]

[msg AST_DNG_HOTEL_30 [岳羽 ゆかり]]
[f 2 1][vp 3 0 65535 1072 0 0]むこうに大きな扉が見えたよ。[n][f 1 2 80][e]

[msg AST_DNG_HOTEL_31 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_HOTEL_32 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_HOTEL_33 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_HOTEL_34 [岳羽 ゆかり]]
[f 2 1][vp 3 0 65535 1061 0 0]シャドウがいた部屋の鏡…[n]なんか変だったのよね…[n][f 1 2 120][e]

[msg AST_DNG_HOTEL_35 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_HOTEL_36 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_HOTEL_37 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_HOTEL_38 [岳羽 ゆかり]]
[f 2 1][vp 3 0 65535 1008 0 0]どの鏡を割るかは[n]リーダーに任せるよ！[n][f 1 2 120][e]

[msg AST_DNG_HOTEL_39 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_HOTEL_40 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_HOTEL_41 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_HOTEL_42 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_HOTEL_43 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_HOTEL_44 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_HOTEL_45 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_HOTEL_46 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_HOTEL_47 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_HOTEL_48 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_HOTEL_49 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_HOTEL_50 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_HOTEL_51 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_HOTEL_52 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_HOTEL_53 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_HOTEL_54 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_HOTEL_55 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_HOTEL_56 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_HOTEL_57 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_HOTEL_58 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_HOTEL_59 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_HOTEL_60 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_MILITARY_01 [岳羽 ゆかり]]
[f 2 1][vp 1 0 1 20657 0 0]さっきの２人…[n]ううん、まずはシャドウだよね。[n][w][e]

[msg AST_DNG_MILITARY_02 [伊織 順平]]
[f 2 1][vp 1 0 1 20658 0 0]しかしココ、カビくせえな…[n][w][e]

[msg AST_DNG_MILITARY_03 [真田 明彦]]
[f 2 1][vp 1 0 1 20659 0 0]俺たち以外に[n]まだペルソナ使いがいたとはな…[n][w][e]

[msg AST_DNG_MILITARY_04 [桐条 美鶴]]
[f 2 1][vp 1 0 1 20660 0 0]しかし、先程のペルソナ使い、[n]気になるな…[n][w][e]

[msg AST_DNG_MILITARY_05 [山岸 風花]]
[f 2 1][vp 1 0 1 20661 0 0]ルキアが反応を掴めないなんて…[n]いえ、まずはシャドウですね。[n][w][e]

[msg AST_DNG_MILITARY_06 [アイギス]]
[f 2 1][vp 1 0 1 20662 0 0]ここは戦時中に使用された[n]施設のようです。[n][w][e]

[msg AST_DNG_MILITARY_07 [岳羽 ゆかり]]
[f 2 1][vp 1 0 1 20663 0 0]早くシャドウを倒して[n]こんな所から出るよ！[n][w][e]

[msg AST_DNG_MILITARY_08 [伊織 順平]]
[f 2 1][vp 1 0 1 20664 0 0]何だ？[n]この地面のキャタピラの跡…[n][w][e]

[msg AST_DNG_MILITARY_09 [真田 明彦]]
[f 2 1][vp 1 0 1 20665 0 0]地面についているこの跡は[n]昔のものじゃなさそうだな…[n][w][e]

[msg AST_DNG_MILITARY_10 [桐条 美鶴]]
[f 2 1][vp 1 0 1 20666 0 0]ぐずぐずしていると影時間が[n]明けてしまう。さっさと片付けるぞ！[n][w][e]

[msg AST_DNG_MILITARY_11 [アイギス]]
[f 2 1][vp 1 0 1 20667 0 0]このキャタピラ跡…[n]まだ新しいです。[n][w][e]

[msg AST_DNG_MILITARY_12 [山岸 風花]]
[f 2 1][vp 1 0 1 10069 0 0]２ブロック先にターゲットの反応！[n][w][e]
[f 2 1][vp 1 0 1 10070 0 0]ゆっくりとですが、[n]下層に向かって移動しています。[n][w][e]
[f 2 1][vp 1 0 1 10071 0 0]後を追ってください！[n][w][e]

[msg AST_DNG_MILITARY_13 [山岸 風花]]
[f 2 1][vp 1 0 1 10072 0 0]ここは…[n][w][e]
[f 2 1][vp 1 0 1 10073 0 0]戦時中に武器庫として[n]使用されていたみたいですね…[n][w][e]

[msg AST_DNG_MILITARY_14 [山岸 風花]]
[f 2 1][vp 1 0 1 10078 0 0]ターゲット加速しました！[n]依然、下層に向かって移動してます。[n][w][e]
[f 2 1][vp 1 0 1 10079 0 0]後を追ってください！[n][w][e]

[msg AST_DNG_MILITARY_15 [山岸 風花]]
[f 2 1][vp 1 0 1 10080 0 0]ターゲット、停止しました！[n][w][e]
[f 2 1][vp 1 0 1 10081 0 0]１ブロック先で反転し、[n]待ち構えているようです！[n][w][e]
[f 2 1][vp 1 0 1 10082 0 0]気をつけてください！[n][w][e]

[msg AST_DNG_MILITARY_16 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_MILITARY_17 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_MILITARY_18 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_MILITARY_19 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_MILITARY_20 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_MILITARY_21 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_MILITARY_22 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_MILITARY_23 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_MILITARY_24 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_MILITARY_25 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_MILITARY_26 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_MILITARY_27 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_MILITARY_28 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_MILITARY_29 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_MILITARY_30 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_MILITARY_31 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_MILITARY_32 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_MILITARY_33 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_MILITARY_34 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_MILITARY_35 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_MILITARY_36 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_MILITARY_37 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_MILITARY_38 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_MILITARY_39 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_MILITARY_40 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_RESERVE_01 [伊織 順平]]
[f 2 1][vp 3 0 65535 2091 0 0]カッコつけたつもりかよ…[n]後味ワリぃことしやがって…[n][f 1 2 120][e]

[msg AST_DNG_RESERVE_02 [天田 乾]]
[f 2 1][vp 3 0 65535 7094 0 0]なんでなんだよ…あいつ。[n][f 1 2 80][e]

[msg AST_DNG_RESERVE_03 [岳羽 ゆかり]]
[f 2 1][vp 3 0 65535 1077 0 0]納得はできないけど…[n]でも、先に進まなきゃ。[n][f 1 2 120][e]

[msg AST_DNG_RESERVE_04 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_RESERVE_05 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_RESERVE_06 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_RESERVE_07 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_RESERVE_08 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_RESERVE_09 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_RESERVE_10 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_RESERVE_11 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_RESERVE_12 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_RESERVE_13 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_RESERVE_14 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_RESERVE_15 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_RESERVE_16 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_RESERVE_17 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_RESERVE_18 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_RESERVE_19 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_RESERVE_20 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_RESERVE_21 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_RESERVE_22 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_RESERVE_23 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_RESERVE_24 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_RESERVE_25 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_RESERVE_26 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_RESERVE_27 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_RESERVE_28 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_RESERVE_29 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_RESERVE_30 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_GET_ITEM_YUKARI_ [岳羽 ゆかり]]
[f 2 1][vp 3 0 65535 1001 0 0]あ、なんか拾った？[n][f 1 2 80][e]

[msg AST_DNG_GET_ITEM_JUNPEI_ [伊織 順平]]
[f 2 1][vp 3 0 65535 2105 0 0]おっ？[n]なんかゲットー！[n][f 1 2 120][e]

[msg AST_DNG_GET_ITEM_SANADA_ [真田 明彦]]
[f 2 1][vp 3 0 65535 3001 0 0]何か落ちたぞ。[n]もらっておけ。[n][f 1 2 80][e]

[msg AST_DNG_GET_ITEM_MITSU_0 [桐条 美鶴]]
[f 2 1][vp 3 0 65535 4070 0 0]何か落ちたな。[n]取っておくか。[n][f 1 2 120][e]

[msg AST_DNG_GET_ITEM_FUKA_01 [山岸 風花]]
[f 2 1][vp 3 0 65535 5006 0 0]あ、何か落ちましたね。[n]使えるでしょうか。[n][f 1 2 120][e]

[msg AST_DNG_GET_ITEM_AEGIS_0 [アイギス]]
[f 2 1][vp 3 0 65535 6001 0 0]アイテムを発見しました。[n][f 1 2 80][e]

[msg AST_DNG_GET_ITEM_AMADA_0 [天田 乾]]
[f 2 1][vp 3 0 65535 7072 0 0]あっ…何か出ました。[n]拾っておきます。[n][f 1 2 120][e]

[msg AST_DNG_GET_ITEM_KORO_01 [コロマル]]
[f 2 1][vp 3 0 65535 8001 0 0]ワンワン！[n][f 1 2 80][e]

[msg AST_DNG_GET_ITEM_ARAGAKI [荒垣 真次郎]]
[f 2 1][vp 3 0 65535 9043 0 0]何だ…？[n]まあ、拾っとけ。[n][f 1 2 120][e]

[msg AST_DNG_GET_ITEM_MITSU_0_2 [桐条 美鶴]]
[f 2 1][vp 3 0 65535 4061 0 0]壊したモノから何か落ちた。[n]一応、拾っておけ。[n][f 1 2 120][e]

[msg AST_DNG_GET_ITEM_FUKA_01_2 [山岸 風花]]
[f 2 1][vp 3 0 65535 5066 0 0]コロちゃんが、[n]何か拾ってくれたみたいです。[n][f 1 2 120][e]

[msg AST_DNG_GET_ITEM_YUKARI__2 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_GET_ITEM_JUNPEI__2 [伊織 順平]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_GET_ITEM_SANADA__2 [真田 明彦]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_GET_ITEM_MITSU_0_3 [桐条 美鶴]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_GET_ITEM_FUKA_02 [山岸 風花]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_GET_ITEM_AEGIS_0_2 [アイギス]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_GET_ITEM_AMADA_0_2 [天田 乾]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_GET_ITEM_KORO_02 [コロマル]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_GET_ITEM_ARAGAKI_2 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_GET_ITEM_MITSU_0_4 [桐条 美鶴]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_GET_ITEM_FUKA_02_2 [山岸 風花]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_GET_ITEM_YUKARI__3 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_GET_ITEM_JUNPEI__3 [伊織 順平]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_GET_ITEM_SANADA__3 [真田 明彦]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_GET_ITEM_MITSU_0_5 [桐条 美鶴]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_GET_ITEM_FUKA_03 [山岸 風花]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_GET_ITEM_AEGIS_0_3 [アイギス]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_GET_ITEM_AMADA_0_3 [天田 乾]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_GET_ITEM_KORO_03 [コロマル]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_GET_ITEM_ARAGAKI_3 [岳羽 ゆかり]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_GET_ITEM_MITSU_0_6 [桐条 美鶴]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_GET_ITEM_FUKA_03_2 [山岸 風花]]
[f 2 1]未使用[n][w][e]

[msg AST_DNG_TBOX_STEAL_MITU_ [桐条 美鶴]]
[f 2 1][vp 3 0 65535 4092 0 0]例のシャドウに宝箱を奪われた。[n]素早いな…[n][f 1 2 120][e]

[msg AST_DNG_TBOX_STEAL_MITU__2 [桐条 美鶴]]
[f 2 1][vp 3 0 65535 4092 0 0]宝箱を開けられたな。[n]先回りしたいが…[n][f 1 2 120][e]

[msg AST_DNG_TBOX_STEAL_MITU__3 [桐条 美鶴]]
[f 2 1][vp 3 0 65535 4092 0 0]ヤツが宝箱を漁っている。[n]落ち着いて次を読め。[n][f 1 2 120][e]

[msg AST_DNG_TBOX_STEAL_FUKA_ [山岸 風花]]
[f 2 1][vp 3 0 65535 5110 0 0]シャドウが宝箱に接触…！[n]何とか先回りしたいですね。[n][f 1 2 120][e]

[msg AST_DNG_TBOX_STEAL_FUKA__2 [山岸 風花]]
[f 2 1][vp 3 0 65535 5110 0 0]あっ、また宝箱を奪われました！[n]だったら他のところで…！[n][f 1 2 120][e]

[msg AST_DNG_TBOX_STEAL_FUKA__3 [山岸 風花]]
[f 2 1][vp 3 0 65535 5101 0 0]シャドウ、宝箱を漁っています！[n]次で待ち伏せましょう！[n][f 1 2 120][e]

[msg AST_ACCIDENT_RBOX_MITU [桐条 美鶴]]
[f 2 1][vp 2 0 1 5218 0 0]この階、レアな宝箱があるようだ。[n]できれば探してみてくれ。[n][f 1 2 120][e]

[msg AST_ACCIDENT_RBOX_MITU_2 [桐条 美鶴]]
[f 2 1][vp 3 0 65535 4114 0 0]ここにもレアな宝箱の気配がある。[n]ついてるじゃないか。[n][f 1 2 120][e]

[msg AST_ACCIDENT_MBOX_MITU [桐条 美鶴]]
[f 2 1][vp 2 0 1 5220 0 0]このフロア…施錠された宝箱がある。[n]ぜひ探して回収してくれ。[n][w][e]

[msg AST_ACCIDENT_RENEMY_MITU [桐条 美鶴]]
[f 2 1][vp 3 0 65535 4086 0 0]レアシャドウの反応だ。[n]ぜひ倒しておきたいところだな。[n][f 1 2 120][e]

[msg AST_ACCIDENT_ALLBAD_MITU [桐条 美鶴]]
[f 2 1][vp 3 0 65535 4098 0 0]ムッ、このフロア…[n]シャドウたちの様子が妙だ…[n][f 1 2 120][e]

[msg AST_ACCIDENT_ALL_R_MITU [桐条 美鶴]]
[f 2 1][vp 3 0 65535 4086 0 0]フロア全体にレアシャドウがいる！[n]またとないチャンスだな。[n][f 1 2 120][e]

[msg AST_ACCIDENT_ALL_S_MITU [桐条 美鶴]]
[f 2 1][vp 1 0 1 5256 0 0]このフロア…強力なシャドウばかりが[n]集まっている。注意するんだ。[n][f 1 2 120][e]

[msg AST_ACCIDENT_DARK_MITU [桐条 美鶴]]
[f 2 1][vp 1 0 1 5216 0 0]こちらから周囲の様子がわからない。[n]より一層、慎重に進んでくれ。[n][f 1 2 120][e]

[msg AST_ACCIDENT_MDOOR_MITU [桐条 美鶴]]
[f 2 1][vp 3 0 65535 4061 0 0]この歪み…例の扉だ。[n]危険な場所だが、行く価値はある。[n][f 1 2 120][e]

[msg AST_ACCIDENT_RBOX_FUKA [桐条 美鶴]]
[f 2 1][vp 1 0 1 5302 0 0]この階から、貴重な宝箱の気配です。[n]探してみてください。[n][f 1 2 120][e]

[msg AST_ACCIDENT_RBOX_FUKA_2 [桐条 美鶴]]
[f 2 1][vp 3 0 65535 5086 0 0]この階にもレアな宝箱が…！[n]ついてますね、リーダー。[n][f 1 2 120][e]

[msg AST_ACCIDENT_MBOX_FUKA [桐条 美鶴]]
[f 2 1][vp 2 0 1 5302 0 0]このフロア…鍵つきの宝箱があります！[n]見つけて回収したいですね。[n][f 1 2 120][e]

[msg AST_ACCIDENT_RENEMY_FUKA [桐条 美鶴]]
[f 2 1][vp 3 0 65535 5087 0 0]この反応、レアシャドウです。[n]捕捉できるでしょうか？[n][f 1 2 120][e]

[msg AST_ACCIDENT_ALLBAD_FUKA [桐条 美鶴]]
[f 2 1][vp 3 0 65535 5092 0 0]フロア内の敵の様子がおかしいです。[n]注意して進んでください。[n][f 1 2 120][e]

[msg AST_ACCIDENT_ALL_R_FUKA [桐条 美鶴]]
[f 2 1][vp 3 0 65535 5087 0 0]フロア全体にレアシャドウです！[n]これはチャンスですね！[n][f 1 2 120][e]

[msg AST_ACCIDENT_ALL_S_FUKA [桐条 美鶴]]
[f 2 1][vp 1 0 1 5343 0 0]フロア全体に強敵の反応です…！[n]十分な注意をお願いします！[n][f 1 2 120][e]

[msg AST_ACCIDENT_DARK_FUKA [桐条 美鶴]]
[f 2 1][vp 3 0 65535 5103 0 0]周囲の様子が見えません…[n]気を付けて進んでください。[n][f 1 2 120][e]

[msg AST_ACCIDENT_MDOOR_FUKA [桐条 美鶴]]
[f 2 1][vp 3 0 65535 5076 0 0]あの扉の反応があります…！[n]中に入るなら、十分に備えたいですね。[n][f 1 2 120][e]

[msg AST_MONADO_BATTLE_END [桐条 美鶴]]
[f 2 1][vp 3 0 65535 5143 0 0]無事、勝利できましたね！[n][f 1 2 80][e]

[msg AST_DNG_GENERAL_02_007_0 [岳羽 ゆかり]]
[f 2 1][vp 2 0 1 5019 0 0]階段あったね、行く？[n][w][e]

[msg AST_DNG_GENERAL_02_007_0_2 [岳羽 ゆかり]]
[f 2 1][vp 2 0 1 5020 0 0]あっ、階段…[n][w][e]

[msg AST_DNG_GENERAL_02_007_0_3 [岳羽 ゆかり]]
[f 2 1][vp 2 0 1 5021 0 0]あ、そこから登れるね。[n][w][e]

[msg AST_DNG_GENERAL_03_007_0 [伊織 順平]]
[f 2 1][vp 2 0 1 5093 0 0]階段、見っけ！[n][w][e]

[msg AST_DNG_GENERAL_03_007_0_2 [伊織 順平]]
[f 2 1][vp 2 0 1 5094 0 0]お、階段だぜ。[n][w][e]

[msg AST_DNG_GENERAL_03_007_0_3 [伊織 順平]]
[f 2 1][vp 2 0 1 5095 0 0]…上行くんだろ、早くしろよ。[n][w][e]

[msg AST_DNG_GENERAL_04_007_0 [真田 明彦]]
[f 2 1][vp 2 0 1 5167 0 0]階段だな、上るか？[n][w][e]

[msg AST_DNG_GENERAL_04_007_0_2 [真田 明彦]]
[f 2 1][vp 2 0 1 5168 0 0]ここに階段があったか。[n][w][e]

[msg AST_DNG_GENERAL_04_007_0_3 [真田 明彦]]
[f 2 1][vp 2 0 1 5169 0 0]階段があるな…まだ行くか？[n][w][e]

[msg AST_DNG_GENERAL_05_007_0 [桐条 美鶴]]
[f 2 1][vp 2 0 1 5237 0 0]よし、登れそうだな。[n][w][e]

[msg AST_DNG_GENERAL_05_007_0_2 [桐条 美鶴]]
[f 2 1][vp 2 0 1 5238 0 0]…階段はこの位置か。[n][w][e]

[msg AST_DNG_GENERAL_05_007_0_3 [桐条 美鶴]]
[f 2 1][vp 2 0 1 5239 0 0]階段だ、行こう。[n][w][e]

[msg AST_DNG_GENERAL_07_007_0 [アイギス]]
[f 2 1][vp 2 0 1 5440 0 0]階段を発見、記録します。[n][w][e]

[msg AST_DNG_GENERAL_07_007_0_2 [アイギス]]
[f 2 1][vp 2 0 1 5441 0 0]階段です、登りますか？[n][w][e]

[msg AST_DNG_GENERAL_07_007_0_3 [アイギス]]
[f 2 1][vp 2 0 1 5442 0 0]あっ、階段ですね。[n][w][e]

[msg AST_DNG_GENERAL_07_007_0_4 [アイギス]]
[f 2 1][vp 2 0 1 5443 0 0]そこから上に行けますね。[n][w][e]

[msg AST_DNG_GENERAL_08_007_0 [天田 乾]]
[f 2 1][vp 2 0 1 5557 0 0]階段がありますよ。[n][w][e]

[msg AST_DNG_GENERAL_08_007_0_2 [天田 乾]]
[f 2 1][vp 2 0 1 5558 0 0]登るところ、ありましたね。[n][w][e]

[msg AST_DNG_GENERAL_08_007_0_3 [天田 乾]]
[f 2 1][vp 2 0 1 5559 0 0]上、登れそうです。[n][w][e]

[msg AST_DNG_GENERAL_09_007_0 [コロマル]]
[f 2 1][vp 2 0 1 5621 0 0]…ワウッ。[n][w][e]

[msg AST_DNG_GENERAL_06_007_0 [山岸 風花]]
[f 2 1][vp 2 0 1 5330 0 0]コロちゃん、[n]階段を見つけてくれたんだね。[n][w][e]

[msg AST_DNG_GENERAL_09_007_0_2 [コロマル]]
[f 2 1][vp 2 0 1 5599 0 0]ワンッ。[n][w][e]

[msg AST_DNG_GENERAL_06_007_0_2 [山岸 風花]]
[f 2 1][vp 2 0 1 5331 0 0]そこから登れますね。[n]ありがとう、コロちゃん。[n][w][e]

[msg AST_DNG_GENERAL_09_007_0_3 [コロマル]]
[f 2 1][vp 2 0 1 3592 0 0]…ワウ？[n][w][e]

[msg AST_DNG_GENERAL_07_007_0_5 [アイギス]]
[f 2 1][vp 2 0 1 5527 0 0]階段ですね。コロマルさんは、[n]『どうする？』とおっしゃっています。[n][w][e]

[msg AST_DNG_GENERAL_07_007_0_6 [アイギス]]
[f 2 1][vp 2 0 1 5526 0 0]コロマルさんが階段を発見です。[n]『上るのか？』だそうです。[n][w][e]

[msg AST_DNG_GENERAL_10_007_0 [荒垣 真次郎]]
[f 2 1][vp 2 0 1 5677 0 0]…階段か、次だな。[n][w][e]

[msg AST_DNG_GENERAL_10_007_0_2 [荒垣 真次郎]]
[f 2 1][vp 2 0 1 5678 0 0]…で、登んのか？[n][w][e]

[msg AST_DNG_GENERAL_10_007_0_3 [荒垣 真次郎]]
[f 2 1][vp 2 0 1 5679 0 0]…そっから上がれんな。[n][w][e]

[msg AST_DEFEAT_GK_MITU_00 [桐条 美鶴]]
[f 2 1][vp 1 0 1 20109 0 0]門番タイプの撃破を確認した。[n]よくやってくれた。[n][f 1 2 120][e]

[msg AST_DEFEAT_GK_MITU_01 [桐条 美鶴]]
[f 2 1][vp 1 0 1 0 0 0]おかげでまた先に進めるな。[n]引き続きよろしく頼む。[n][w][e]

[msg AST_DEFEAT_GK_FUKA_00 [山岸 風花]]
[f 2 1][vp 2 0 1 20126 0 0]門番タイプのシャドウ撃破です。[n]お疲れ様でした！[n][f 1 2 120][e]

[msg AST_DEFEAT_GK_FUKA_01 [山岸 風花]]
[f 2 1][vp 2 0 1 0 0 0]これで先に進めますね。[n]油断せずに行きましょう。[n][w][e]

