[sel SEL_YESNO top]
[f 2 1]開けてみよう[e]
[f 2 1]やめておく[e]

[msg MND_TBOX_MEDAL]
[f 2 1]手元に[f 4 4 1 0 1 0]は[clr 2][f 2 4 2][clr 27]個ある。[n][clr 2][f 2 4 1][clr 27]個使えば開けられそうだ…[n][w][e]

[msg MND_TBOX_MEDAL_OPEN]
[f 2 1][f 4 4 1 0 1 0]を[clr 2][f 2 4 1][clr 27]個使った。[n](所持数：[f 2 4 3]個)[n][w][e]

[msg MND_TBOX_MEDAL_NOT_ENOUG]
[f 2 1][f 4 4 1 0 1 0]が[clr 2][f 2 4 1][clr 27]個あれば[n]開けられそうだが…今は[clr 2][f 2 4 2][clr 27]個しかない…[n][w][e]

[msg MND_TBOX_MedalNone]
[f 2 1]手元に[f 4 4 1 0 1 0]がない…[n][clr 2][f 2 4 1][clr 27]個あれば開けられそうだが…[n][w][e]

[msg MSG_TBOX_RETURN_FUKA [山岸 風花]]
[f 2 1][bup 6 0 65535 50 0 0]宝箱の反応はもう残ってないみたいです。[n][w][e]
[f 2 1][bup 6 0 65535 50 0 0]何が起きるか分かりません。[n]早めに戻ってきてくださいね。[n][w][e]

[msg MSG_TBOX_OPEN_TUTO [桐条 美鶴]]
[f 2 1][bup 5 0 65535 50 0 0][vp 1 0 1 20523 0 0]有益な物が入っていたようだな。[n]使い道は君に任せよう。[n][w][e]

[msg MSG_1ST_TRY_MEDAL_OPENED [桐条 美鶴]]
[f 2 1][bup 5 1 65535 50 0 0][vp 3 0 65535 4607 0 0]やはりか…[n]どうやら本物のようだな。[n][w][e]
[f 2 1][bup 5 1 65535 50 0 0]それは『[clr 39]薄明の欠片[clr 27]』と言って、[n]タルタロス内の装置に干渉できるものだ。[n][w][e]
[f 2 1][bup 5 0 65535 50 0 0]タルタロスやシャドウのいた痕跡のある場所で[n]時折、見つかるらしい。[n][w][e]
[f 2 1][bup 5 0 65535 50 0 0]今後も見かけたら、保管しておいてくれ。[n][w][e]

[msg MND_GET_ARCANA_CARD]
[f 2 1][f 4 4 1 0 1 0]が反応している…[n][w][e]

[msg PFM_GET_CARD_TEMPERANCE]
[f 2 1]シャッフルタイムに[n]節制の大アルカナカードが追加された。[n][w][e]

[msg PFM_GET_CARD_DEVIL]
[f 2 1]シャッフルタイムに[n]悪魔の大アルカナカードが追加された。[n][w][e]

[msg PFM_GET_CARD_TOWER]
[f 2 1]シャッフルタイムに[n]塔の大アルカナカードが追加された。[n][w][e]

[msg PFM_GET_CARD_STAR]
[f 2 1]シャッフルタイムに[n]星の大アルカナカードが追加された。[n][w][e]

[msg PFM_GET_CARD_MOON]
[f 2 1]シャッフルタイムに[n]月の大アルカナカードが追加された。[n][w][e]

[msg PFM_GET_CARD_SUN]
[f 2 1]シャッフルタイムに[n]太陽の大アルカナカードが追加された。[n][w][e]

[msg PFM_GET_CARD_JUDGEMENT]
[f 2 1]シャッフルタイムに[n]審判の大アルカナカードが追加された。[n][w][e]

[msg MSG_ESCAPE_FUKA_00 [山岸 風花]]
[f 2 1][bup 6 0 65535 50 0 0][vp 3 0 65535 5025 0 0]ここで行き止まりみたいですね。[n]すぐに戻りますか？[n][w][e]

[sel SEL_ESCAPE_HERO top]
[f 2 1]モナドの外に出る[e]
[f 2 1]探索を続ける[e]

[msg MSG_ESCAPE_FUKA_10 [山岸 風花]]
[f 2 1][bup 6 0 65535 50 0 0]了解しました。[n][w][e]
[f 2 1][bup 6 0 65535 50 0 0]迷いやすいので、[n]気を付けて戻ってくださいね。[n][w][e]

[msg MSG_ESCAPE_FUKA_11 [山岸 風花]]
[f 2 1][bup 6 0 65535 50 0 0]何か見落としでしょうか？[n][w][e]
[f 2 1][bup 6 0 65535 50 0 0]敵は残っていませんが、[n]危険な場所であることに変わりはありません。[n][w][e]
[f 2 1][bup 6 0 65535 50 0 0]探索には細心の注意をお願いします。[n][w][e]

[msg MND_ARAGAKI_REMIND]
[f 2 1]荒垣に似合いそうだ…[n]だが、荒垣はもういない…[n][w][e]

[msg MSG_TUTO01 [山岸 風花]]
[f 2 1][bup 6 0 65535 50 0 0][vp 3 0 65535 5071 0 0]これ、前に[nf]ちゃんが[n]理事長に渡されたものと似てますね。[n][w][e]
[f 2 1][bup 6 0 65535 50 0 0]珍しい物とのことでしたが、[n]こんな場所の宝箱に入ってるなんて…[n][w][e]

[msg MND_TUTO02]
[f 2 1]骨董屋の店主に渡せば、[n]装備に加工してくれるだろうか…[n][w][e]

[msg MSG_TUTO03 [山岸 風花]]
[f 2 1][bup 6 0 65535 50 0 0]ひと通り確認できましたね。[n]お疲れ様でした。[n][w][e]
[f 2 1][bup 6 0 65535 50 0 0]ひとまず、扉の外に引き返してください。[n][w][e]

[sel SEL_EQUIP_UPDATE_00 top]
[f 2 1][f 4 4 1 0 0 0]を装備する[e]
[f 2 1]今のままでいい[e]

[sel SEL_EQUIP_UPDATE_01 top]
[f 2 1]新しい装備に替える[e]
[f 2 1]今のままでいい[e]

[sel SEL_EQUIP_UPDATE_02 top]
[f 2 1]ゆかりに渡す[e]
[f 2 1]今のままでいい[e]

[sel SEL_EQUIP_UPDATE_03 top]
[f 2 1]順平に渡す[e]
[f 2 1]今のままでいい[e]

[sel SEL_EQUIP_UPDATE_04 top]
[f 2 1]真田に渡す[e]
[f 2 1]今のままでいい[e]

[sel SEL_EQUIP_UPDATE_05 top]
[f 2 1]美鶴に渡す[e]
[f 2 1]今のままでいい[e]

[sel SEL_EQUIP_UPDATE_06 top]
[f 2 1]未使用[e]

[sel SEL_EQUIP_UPDATE_07 top]
[f 2 1]アイギスに渡す[e]
[f 2 1]今のままでいい[e]

[sel SEL_EQUIP_UPDATE_08 top]
[f 2 1]天田に渡す[e]
[f 2 1]今のままでいい[e]

[sel SEL_EQUIP_UPDATE_09 top]
[f 2 1]コロマルに渡す[e]
[f 2 1]今のままでいい[e]

[sel SEL_EQUIP_UPDATE_10 top]
[f 2 1]荒垣に渡す[e]
[f 2 1]今のままでいい[e]

[msg MND_EQUIP_UPDATE_HERO_00]
[f 2 1][f 4 4 1 0 1 0]は[n]今使っている武器より強そうだ…[n][w][e]

[msg MSG_EQUIP_UPDATE_YUKARI_ [岳羽 ゆかり]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 3 0 65535 1002 0 0]あ、この弓よさそうじゃん！[n]私が使ってもいいよね？[n][w][e]

[msg MSG_EQUIP_UPDATE_JUNPEI_ [伊織 順平]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2001 0 0]強そうな武器じゃん！[n]使いこなせんのは、オレしかいねえよな？[n][w][e]

[msg MSG_EQUIP_UPDATE_SANADA_ [真田 明彦]]
[f 2 1][bup 4 1 65535 65535 0 0][vp 3 0 65535 3094 0 0]新しい武器か。[n]俺が使っている物より良さそうだ。[n][w][e]

[msg MSG_EQUIP_UPDATE_MITSURU [桐条 美鶴]]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4086 0 0]良い性能の武器じゃないか。[n]私に使わせてくれないか？[n][w][e]

[msg MSG_EQUIP_UPDATE_FUKA_00 [山岸 風花]]
[f 2 1][bup 6 1 65535 50 0 0][vp 3 0 65535 5087 0 0]中身は武器だったんですね。[n]コロちゃんなら使いこなせるんじゃないかな？[n][w][e]

[msg MSG_EQUIP_UPDATE_AEGIS_0 [アイギス]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6080 0 0]兵装の取得を確認しました。[n]装備の換装を提案いたします。[n][w][e]

[msg MSG_EQUIP_UPDATE_AMADA_0 [天田 乾]]
[f 2 1][bup 8 1 65535 65535 0 0][vp 3 0 65535 7005 0 0]新しい武器…[n]僕に使わせてくれませんか！[n][w][e]

[msg MSG_EQUIP_UPDATE_KORO_00 [コロマル]]
[f 2 1][bup 9 1 65535 65535 0 0][vp 3 0 65535 8001 0 0]ワン！　ワン！[n][w][e]

[msg MSG_EQUIP_UPDATE_ARAGAKI [荒垣 真次郎]]
[f 2 1][bup 10 1 65535 65535 0 0][vp 3 0 65535 9007 0 0]良さそうな武器じゃねえか。[n]俺に預けろよ。[n][w][e]

[msg MSG_EQUIP_UPDATE_AEGIS_0_2 [アイギス]]
[f 2 1][bup 7 1 65535 65535 0 0][vp 3 0 65535 6087 0 0]新しい兵装を入手しました。[n]わたしに使わせてもらえませんか？[n][w][e]

[msg MND_EQUIP_UPDATE_HERO_01]
[f 2 1][f 4 4 1 0 1 0]は[n]今使っている装備より性能が良さそうだ…[n][w][e]

[msg MSG_EQUIP_UPDATE_YUKARI__2 [岳羽 ゆかり]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 3 0 65535 1002 0 0]あ、これ良さそうじゃん！[n]私が使ってもいい？[n][w][e]

[msg MSG_EQUIP_UPDATE_JUNPEI__2 [伊織 順平]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2001 0 0]いい感じの装備じゃん。[n]オレに似合うと思わねえ？[n][w][e]

[msg MSG_EQUIP_UPDATE_SANADA__2 [真田 明彦]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 3 0 65535 3094 0 0]ほう、俺に似合いの装備だな。[n]使っていいか？[n][w][e]

[msg MSG_EQUIP_UPDATE_MITSURU_2 [桐条 美鶴]]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4086 0 0]良い装備が手に入ったみたいだな。[n]私が使っている物より性能が高そうだ。[n][w][e]

[msg MSG_EQUIP_UPDATE_FUKA_01 [山岸 風花]]
[f 2 1][bup 6 1 65535 50 0 0][vp 3 0 65535 5087 0 0]あ、コロちゃんにぴったりの装備じゃないですか？[n][w][e]

[msg MSG_EQUIP_UPDATE_AEGIS_0_3 [アイギス]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6080 0 0]中身は防具でしたか。[n]装備を換装するのはいかがでしょうか？[n][w][e]

[msg MSG_EQUIP_UPDATE_AMADA_0_2 [天田 乾]]
[f 2 1][bup 8 1 65535 65535 0 0][vp 3 0 65535 7005 0 0]僕に使わせてくれませんか？[n]サイズが合わなくても、すぐに大きくなります！[n][w][e]

[msg MSG_EQUIP_UPDATE_KORO_01 [コロマル]]
[f 2 1][bup 9 1 65535 65535 0 0][vp 3 0 65535 8001 0 0]ワン！　ワン！[n][w][e]

[msg MSG_EQUIP_UPDATE_ARAGAKI_2 [荒垣 真次郎]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 3 0 65535 9007 0 0]良さそうだな。[n]他が使わないなら俺に預けろ。[n][w][e]

[msg MSG_EQUIP_UPDATE_AEGIS_0_4 [アイギス]]
[f 2 1][bup 7 1 65535 65535 0 0][vp 3 0 65535 6087 0 0]中身は防具だったんですね。[n]わたしが使っているものより丈夫そうです。[n][w][e]

[msg MND_EQUIP_UPDATE_MULTI]
[f 2 1][f 4 4 1 0 1 0]を[n]誰に装備しようか？[n][w][e]

[sel SEL_PARTY top]
[f 2 1]自分で使う[e]
[f 2 1]ゆかり[e]
[f 2 1]順平[e]
[f 2 1]真田[e]
[f 2 1]美鶴[e]
[f 2 1]風花[e]
[f 2 1]アイギス[e]
[f 2 1]天田[e]
[f 2 1]コロマル[e]
[f 2 1]荒垣[e]
[f 2 1]今のままでいい[e]

[msg MND_EQUIP_UPDATE_HERO_10]
[f 2 1][f 4 4 1 0 1 0]を装備した。[n][w][e]

[msg MSG_EQUIP_UPDATE_YUKARI__3 [岳羽 ゆかり]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 3 0 65535 1039 0 0]ありがと！[n]大事に使うね。[n][w][e]

[msg MSG_EQUIP_UPDATE_JUNPEI__3 [伊織 順平]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2117 0 0]おっし、パワーアーップ！[n]このままガンガン行くぜ！[n][w][e]

[msg MSG_EQUIP_UPDATE_SANADA__3 [真田 明彦]]
[f 2 1][bup 4 1 65535 65535 0 0][vp 3 0 65535 3042 0 0]トレーニングに余念はないが[n]良い装備が使えるのはありがたい。[n][w][e]

[msg MSG_EQUIP_UPDATE_MITSURU_3 [桐条 美鶴]]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4038 0 0]ありがたく使わせてもらおう。[n]なに、期待には応えるさ。[n][w][e]

[msg MSG_EQUIP_UPDATE_FUKA_10 [山岸 風花]]
[f 2 1][bup 6 1 65535 50 0 0]未使用[n][w][e]

[msg MSG_EQUIP_UPDATE_AEGIS_1 [アイギス]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6038 0 0]装備のアップグレードを確認しました。[n]より良い戦果をお約束します。[n][w][e]

[msg MSG_EQUIP_UPDATE_AMADA_1 [天田 乾]]
[f 2 1][bup 8 1 65535 65535 0 0][vp 3 0 65535 7040 0 0]ありがとうございます。[n]役に立てるよう頑張りますね！[n][w][e]

[msg MSG_EQUIP_UPDATE_KORO_10 [コロマル]]
[f 2 1][bup 9 1 65535 65535 0 0][vp 3 0 65535 8012 0 0]ワンワン！[n][w][e]

[msg MSG_EQUIP_UPDATE_ARAGAKI_3 [荒垣 真次郎]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 3 0 65535 9051 0 0]ありがとよ。[n]ま、後悔はさせねえよ。[n][w][e]

[msg MSG_EQUIP_UPDATE_AEGIS_1_2 [アイギス]]
[f 2 1][bup 7 1 65535 65535 0 0][vp 3 0 65535 6039 0 0]装備をアップグレードしました。[n]これを使ってもっと頑張りますね！[n][w][e]

[msg MSG_HIGH_RARE_TUTO_MITU_ [桐条 美鶴]]
[f 2 1][bup 5 0 65535 50 0 0]またシャドウの反応が止まったな。[n]場所は離れているようだが…[n][w][e]

[msg MSG_HIGH_RARE_TUTO_MITU__2 [桐条 美鶴]]
[f 2 1][bup 5 3 65535 50 0 0]宝箱を奪われたか…[n]だが、こちらの存在には気づいているようだ。[n][w][e]
[f 2 1][bup 5 0 65535 50 0 0]このまま宝箱を開けていけば[n]あちらも無視はできないはずだ。[n][w][e]
[f 2 1][bup 5 0 65535 50 0 0]引き続き宝箱を探してくれ。[n][w][e]

[msg MSG_HIGH_RARE_TUTO_FUKA_ [山岸 風花]]
[f 2 1][bup 6 0 65535 50 0 0]またシャドウの反応が止まりました。[n]場所は離れているようですが…[n][w][e]

[msg MSG_HIGH_RARE_TUTO_FUKA__2 [山岸 風花]]
[f 2 1][bup 6 3 65535 50 0 0]宝箱を取られちゃいました…[n]でも、こちらの存在には気づいてるみたい。[n][w][e]
[f 2 1][bup 6 0 65535 50 0 0]このまま宝箱を開けていけば[n]あちらも無視できなくなるはずです。[n][w][e]
[f 2 1][bup 6 0 65535 50 0 0]引き続き宝箱を探していきましょう。[n][w][e]

[msg MSG_HIGH_RARE_BTL_MITU_0 [桐条 美鶴]]
[f 2 1][bup 5 0 65535 50 0 0]シャドウがこちらに接近している。[n]迎え撃つぞ！[n][w][e]

[msg MSG_HIGH_RARE_BTL_MITU_0_2 [桐条 美鶴]]
[f 2 1][bup 5 0 65535 50 0 0]シャドウの消失を確認した。[n][w][e]
[f 2 1][bup 5 0 65535 50 0 0]このフロアに敵の反応は残っていないな。[n]先に進むとしよう。[n][w][e]

[msg MSG_HIGH_RARE_BTL_FUKA_0 [山岸 風花]]
[f 2 1][bup 6 0 65535 50 0 0]シャドウがこちらに接近しています！[n]迎え撃つチャンスです。[n][w][e]

[msg MSG_HIGH_RARE_BTL_FUKA_0_2 [山岸 風花]]
[f 2 1][bup 6 0 65535 50 0 0]シャドウの消失を確認。[n][w][e]
[f 2 1][bup 6 0 65535 50 0 0]このフロアに敵の反応は残っていません。[n]先に進みましょう。[n][w][e]

