[msg MSG_000_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 4 101 65535 0 0][uf 3 1 3 0 65535 10879 0 0]Tía... Lo que te gusta fardar, ¿eh?[n][uf 1 1][e]

[msg MSG_001_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0]Tengo que comprarme ropa, pero ahora mismo ando sin tiempo.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0]Me paso los findes enteros en chándal. Me ayuda a ponerme en modo deportista y tal.[n][uf 1 1][e]

[msg MSG_002_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 1 101 65535 0 0][uf 3 1 3 0 65535 10893 0 0]Así estoy siempre listo. De dedicación voy sobrado, macho.[n][uf 1 1][e]

[sel SEL_003_0_0 top]
[uf 0 5 65278][uf 2 1]Impresionante.[e]
[uf 0 5 65278][uf 2 1]A mí me da igual.[e]
[uf 0 5 65278][uf 2 1]Relájate.[e]

[msg MSG_004_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 1 101 65535 0 0][uf 3 1 3 0 65535 10823 0 0][uf 5 13 8 30 105]Es fortaleza mental. Eso es lo mío.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 1 101 65535 0 0]Nadie puede superarme... Bueno, en espíritu. Aunque tú tampoco lo haces mal, la verdad.[n][uf 1 1][e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]Parece que Miyamoto se lo está pasando muy bien.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Siento que hoy nuestra relación se ha estrechado.[n][uf 1 1][e]

[msg MSG_006_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 1 101 65535 0 0][uf 3 1 3 0 65535 10829 0 0][uf 5 13 8 15 105]Je, no te pongas tan chula solo porque me hayas ganado una vez.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 1 101 65535 0 0]Estate al loro, colega, porque la próxima te vas a cagar. Bueno, cuando ande un poco más en forma...[n][uf 1 1][e]

[msg MND_007_0_0]
[uf 0 5 65278][uf 2 1]Parece que Miyamoto se está divirtiendo.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Hoy he aprendido un poco más sobre él.[n][uf 1 1][e]

[msg MSG_008_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0][uf 3 1 3 0 65535 10852 0 0]Yuko me dijo exactamente lo mismo.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0]Pensaba que ella no entendía lo de la dedicación, pero, si tú también lo dices, puede que me esté pasando un poco.[n][uf 1 1][e]

[msg MND_009_0_0]
[uf 0 5 65278][uf 2 1]Miyamoto parece un poco deprimido.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Siento que hoy nuestra relación no ha cambiado nada...[n][uf 1 1][e]

[msg MSG_010_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 1 101 65535 0 0][uf 3 1 3 0 65535 10854 0 0]Bueno, ¿qué plan tenemos? ¿Vamos a dar un paseo y buscamos un sitio donde comer?[n][uf 1 1][e]

[msg MND_011_0_0]
[uf 0 5 65278][uf 2 1]Dimos una vuelta por la zona de tiendas antes de volver a la residencia.[n][uf 1 1][e]

