[msg MSG_000_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]...![n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]What's wrong?[e]
[uf 0 5 65278][uf 2 1]Do you need some rest?[e]

[msg MSG_002_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]This has been happening a lot lately.[n][uf 1 1][e]

[msg MSG_003_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]I'll be okay. It'll go away in a little while.[n][uf 1 1][e]

[msg MSG_004_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]It's just a little headache. I don't think it's anything to worry about.[n][uf 1 1][e]

[msg MSG_005_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]You should really figure out what's causing the pain. It might lead to serious complications down the road.[n][uf 1 1][e]

[msg MSG_006_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]Does anywhere else hurt? Are your nose and throat all right?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]Does it feel like your head is in a vice?[n][uf 1 1][e]

[msg MND_007_0_0]
[uf 0 5 65278][uf 2 1]Hiraga is getting the details[n]on Fuuka's symptoms.[n][uf 1 1][e]

[msg MSG_008_0_0 [Female Club Member]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 8 0 0][uf 5 21 0 150]Oh boy, here we go. Keisuke-senpai strikes again.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 9 0 0][uf 5 21 0 150]Yamagishi-san won't be going anywhere for a while.[n][uf 1 1][e]

[sel SEL_009_0_0 top]
[uf 0 5 65278][uf 2 1]"Strikes again"?[e]
[uf 0 5 65278][uf 2 1]Is that a problem?[e]

[msg MSG_010_0_0 [Female Club Member]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 10 0 0][uf 5 21 0 150]If someone isn't feeling well, he always tries to figure out what's wrong.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 11 0 0][uf 5 21 0 150]And it doesn't matter when or where. Once he starts, it takes forever...[n][uf 1 1][e]

[msg MSG_011_0_0 [Female Club Member]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 12 0 0][uf 5 21 0 150]Oh, she'll be fine. He's like a walking medical encyclopedia.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 13 0 0][uf 5 21 0 150]We all appreciate him, but it can be a little too much after a while.[n][uf 1 1][e]

[msg MSG_012_0_0 [Female Club Member]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 14 0 0][uf 5 21 0 150]Keisuke-senpai's dad's the director of a big hospital, and he's an only child.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 15 0 0][uf 5 21 0 150]I guess he just can't stand to see people suffer. I bet he'll end up going to medical school.[n][uf 1 1][e]

[msg MSG_013_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 0 16 0 0]So the pain's originating from the back of your head?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 0 17 0 0]Could you turn around please?[n][uf 1 1][e]

[msg MSG_013_3_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 0 18 0 0]Don't worry, it's just a chronic tension-type headache, most likely the result of stress.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 0 19 0 0][uf 4 23 0 1 0 25 25]You might be spending too much time in front of the computer. Try to get outside and exercise more.[n][uf 1 1][e]

[msg MSG_013_5_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 0 20 0 0]...It must seem funny to get medical advice from the head of the art club.[n][uf 1 1][e]

[msg MSG_014_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 65535 0 0][uf 3 1 1 0 0 21 0 0]I was worried I'd come down with the flu or something...[n][uf 1 1][e]

[msg MSG_015_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 0 22 0 0]In that case, I can do a more thorough check.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 0 23 0 0]Could you remove your shirt? Also, open your mouth and stick out your tongue.[n][uf 1 1][e]

[msg MSG_016_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 65535 0 0][uf 3 1 1 0 0 24 0 0]Wha—!?[n][uf 1 1][e]

[msg MSG_016_5_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 65535 0 0][uf 3 1 1 0 0 25 0 0]U-Uh, that's okay, I'm fine! Besides, our dorm isn't far, so [uf 4 1]-chan can accompany me back![n][uf 1 1][e]

[msg MSG_017_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 0 26 0 0]Ah, sorry, sorry— Wait, you two live in the dorms?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 0 27 0 0]I guess I see it in Yamagishi-san. She seems like the well-adjusted type. I bet you're a great cook.[n][uf 1 1][e]

[msg MSG_018_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 0 28 0 0][uf 4 1]-chan, do you take care of the laundry? Is living alone hard?[n][uf 1 1][e]

[msg MND_019_0_0]
[uf 0 5 65278][uf 2 1]I think Hiraga has taken an interest in me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like we're becoming better friends.[n][uf 1 1][e]

[msg SYS_020_0_0]
[uf 0 5 65278][uf 2 1]DEV: Label is not used[n][uf 1 1][e]

[msg MSG_021_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 0 29 0 0]Oh, sorry, Yamagishi-san! I forgot about your condition.[n][uf 1 1][e]

[msg MSG_021_5_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 0 30 0 0]I know it's close, but I don't think you should be walking home. Why don't I call you a taxi?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 0 31 0 0]Though a bumpy taxi ride might make your headache worse... Maybe a limousine would be better.[n][uf 1 1][e]

[msg MSG_022_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 65535 0 0][uf 3 1 1 0 0 32 0 0]U-Uh, that's okay. I'm fine. Really.[n][uf 1 1][e]

[msg MND_023_0_0]
[uf 0 5 65278][uf 2 1]It's getting dark out.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I said goodbye to the club members[n]and went back to the dorm.[n][uf 1 1][e]

