[msg MSG_000_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]Je viens souvent ici dernièrement.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]Avant, je n'arrivais pas à comprendre pourquoi les gens visitaient ces "sanctuaires".[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]Mais dernièrement, ça a changé...[n][uf 1 1][e]

[msg MSG_001_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]C'est aussi ici que nous avons rencontré Koromaru l'été dernier...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]Il attendait ici que quelqu'un le trouve, même en sachant que son maître était mort.[n][uf 1 1][e]

[msg MSG_002_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]Je comprends pourquoi maintenant.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]Les actes des gens sont dictés non pas par les faits, mais par les émotions...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 65535 65535 0 0][uf 3 1 1 0 0 8 0 0]Il savait que son maître était mort, mais ce sont ses sentiments qui l'ont poussé à rester...[n][uf 1 1][e]

[msg MSG_003_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 9 0 0]Je ressens la même chose.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]J'ai pris conscience que je ne pouvais pas te protéger, mais je suis quand même revenue.[n][uf 1 1][e]

[msg MSG_003_3_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 11 0 0]Inconsciemment, j'agissais sur la base de mes émotions et non de la raison.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]J'étais tellement perturbée que je ne l'ai pas remarqué, mais c'est la vérité.[n][uf 1 1][e]

[msg MSG_003_5_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]Les paramètres de mon comportement semblent avoir été mis à jour en passant du temps à tes côtés, [uf 4 2].[n][uf 1 1][e]

[msg MND_004_0_0]
[uf 0 5 65278][uf 2 1]Je sens un peu d'affection de la part d'Aigis...[n][uf 1 1][e]

[msg MSG_005_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]... Oh, je me suis mal exprimée.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 15 0 0]J'ai parlé des "actes des gens"...[n][uf 1 1][e]

[msg MSG_005_3_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 1 0 0 16 0 0]Mais évidemment, Koromaru et moi ne faisons pas partie des "gens".[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 1 0 0 17 0 0]Héhé, désolée...[n][uf 1 1][e]

[msg MSG_005_5_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 65535 65535 0 0][uf 3 1 0 0 0 18 0 0]......[n][uf 1 1][e]

[msg MND_006_0_0]
[uf 0 5 65278][uf 2 1]Aigis semble se sentir seule.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Nous avons décidé de retourner au dortoir.[n][uf 1 1][e]

