[msg MSG_000_0_0 [Asesor del equipo de atletismo]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 1 0 0][uf 5 21 0 1093]A partir de hoy, forma oficialmente parte del equipo.[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]Soy [uf 4 3].[e]
[uf 0 5 65278][uf 2 1]Es un placer conoceros.[e]

[msg MSG_002_0_0 [Alumna en camiseta]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 101 65535 0 0][uf 3 1 1 0 0 2 0 0]Bienvenida, [uf 4 1]. Me llamo Yuko Nishiwaki.[n][uf 1 1][e]

[msg MSG_003_0_0 [Asesor del equipo de atletismo]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 3 0 0][uf 5 21 0 1093]Es la encargada. Puedes preguntarle lo que quieras.[n][uf 1 1][e]

[msg MSG_004_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 101 65535 0 0][uf 3 1 1 0 0 4 0 0]Estás en segundo, ¿verdad? Como tenemos la misma edad, llámame Yuko.[n][uf 1 1][e]

[msg MSG_005_0_0 [Asesor del equipo de atletismo]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 5 0 0][uf 5 21 0 1093]A ver... ¡Eh, Kazushi![n][uf 1 1][e]

[msg MSG_006_0_0 [Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 151 65535 0 0][uf 3 1 1 0 0 6 0 0]¡Sí![n][uf 1 1][e]

[msg MSG_007_0_0 [Asesor del equipo de atletismo]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 7 0 0][uf 5 21 0 1093]El futuro capitán del equipo, un excelente corredor que obtiene buenos resultados en las competiciones.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 8 0 0][uf 5 21 0 1093]Vais a la misma clase, ¿no? Kazushi, échale un ojo al nuevo, ¿vale?[n][uf 1 1][e]

[msg MSG_008_0_0 [Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 151 65535 0 0][uf 3 1 1 0 0 9 0 0]Hecho.[n][uf 1 1][e]

[msg MSG_009_0_0 [Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 151 65535 0 0][uf 3 1 1 0 0 10 0 0]Eres la que iba con Yukari el primer día de clase, ¿no? Aquí te conoce todo el mundo.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 151 65535 0 0][uf 3 1 1 0 0 11 0 0]Me llamo Kazushi Miyamoto. Supongo que ya me habrás visto por ahí.[n][uf 1 1][e]

[sel SEL_010_0_0 top]
[uf 0 5 65278][uf 2 1]Sí.[e]
[uf 0 5 65278][uf 2 1]Pues no.[e]

[msg MSG_011_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 1 151 65535 0 0][uf 3 1 1 0 0 12 0 0]Bueno, resumiendo: de ahora en adelante me tienes que reservar tus tardes.[n][uf 1 1][e]

[msg MSG_012_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 151 65535 0 0][uf 3 1 1 0 0 13 0 0]Tía, me hieres el orgullo. Todo el mundo me conoce.[n][uf 1 1][e]

[msg MSG_013_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 151 65535 0 0][uf 3 1 1 0 0 14 0 0]¡No te creas que voy a ser más blando contigo porque te hayas unido en mitad de temporada![n][uf 1 1][e]

[msg MND_014_0_0]
[uf 0 5 65278][uf 2 1]Kazushi me ha dado una cálida bienvenida.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]He entrado en el equipo de atletismo y he hecho buenas migas con mis compañeros.[n][uf 1 1][e]

[msg MSG_015_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 101 65535 0 0][uf 3 1 1 0 0 15 0 0]Como hoy es tu primer día, simplemente echa un vistazo y ya está.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 101 65535 0 0][uf 3 1 1 0 0 16 0 0]Los entrenamientos son los [uf 0 1 2]lunes, martes, jueves y viernes[uf 0 1 27]. La víspera de los exámenes no hay entrenamientos.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 101 65535 0 0][uf 3 1 1 0 0 17 0 0]Yo me encargo de preparar tu equipación para el próximo día.[n][uf 1 1][e]

[msg MND_016_0_0]
[uf 0 5 65278][uf 2 1]Después de echar un vistazo, he decidido volver a la residencia.[n][uf 1 1][e]

