[sel SEL_YESNO top]
[f 2 1]打开看看[e]
[f 2 1]还是算了[e]

[msg MND_TBOX_MEDAL]
[f 2 1]手上有[clr 2][f 2 4 2][clr 27]个[f 4 4 1 0 1 0]。[n]打开需要[clr 2][f 2 4 1][clr 27]个……[n][w][e]

[msg MND_TBOX_MEDAL_OPEN]
[f 2 1]使用了[clr 2][f 2 4 1][clr 27]个[f 4 4 1 0 1 0]。[n]（持有数：[f 2 4 3]个）[n][w][e]

[msg MND_TBOX_MEDAL_NOT_ENOUG]
[f 2 1]使用[clr 2][f 2 4 1][clr 27]个[f 4 4 1 0 1 0]便可打开……[n]但现在手上只有[clr 2][f 2 4 2][clr 27]个……[n][w][e]

[msg MND_TBOX_MedalNone]
[f 2 1]手上没有[f 4 4 1 0 1 0]……[n]想打开需要[clr 2][f 2 4 1][clr 27]个……[n][w][e]

[msg MSG_TBOX_RETURN_FUKA [山岸 风花]]
[f 2 1][bup 6 0 65535 50 0 0]好像已经没有宝箱的反应了。[n][w][e]
[f 2 1][bup 6 0 65535 50 0 0]不知道会发生什么。[n]请大家尽早回来吧。[n][w][e]

[msg MSG_TBOX_OPEN_TUTO [桐条 美鹤]]
[f 2 1][bup 5 0 65535 50 0 0][vp 1 0 1 20523 0 0]看来里面装了有用的东西。[n]就交给你来决定怎么使用吧。[n][w][e]

[msg MSG_1ST_TRY_MEDAL_OPENED [桐条 美鹤]]
[f 2 1][bup 5 1 65535 50 0 0][vp 3 0 65535 4607 0 0]不出我所料……[n]看来是真货啊。[n][w][e]
[f 2 1][bup 5 1 65535 50 0 0]这个东西叫“[clr 39]黄昏的碎片[clr 27]”，[n]可以用来影响塔尔塔罗斯内的装置。[n][w][e]
[f 2 1][bup 5 0 65535 50 0 0]在塔尔塔罗斯内，或者存在[n]暗影痕迹的地方，有时似乎可以找到。[n][w][e]
[f 2 1][bup 5 0 65535 50 0 0]今后如果发现了，就保管起来吧。[n][w][e]

[msg MND_GET_ARCANA_CARD]
[f 2 1][f 4 4 1 0 1 0]起了反应……[n][w][e]

[msg PFM_GET_CARD_TEMPERANCE]
[f 2 1]在洗牌时间里[n]追加了节制的大阿尔卡那卡牌。[n][w][e]

[msg PFM_GET_CARD_DEVIL]
[f 2 1]在洗牌时间里[n]追加了恶魔的大阿尔卡那卡牌。[n][w][e]

[msg PFM_GET_CARD_TOWER]
[f 2 1]在洗牌时间里[n]追加了塔的大阿尔卡那卡牌。[n][w][e]

[msg PFM_GET_CARD_STAR]
[f 2 1]在洗牌时间里[n]追加了星的大阿尔卡那卡牌。[n][w][e]

[msg PFM_GET_CARD_MOON]
[f 2 1]在洗牌时间里[n]追加了月亮的大阿尔卡那卡牌。[n][w][e]

[msg PFM_GET_CARD_SUN]
[f 2 1]在洗牌时间里[n]追加了太阳的大阿尔卡那卡牌。[n][w][e]

[msg PFM_GET_CARD_JUDGEMENT]
[f 2 1]在洗牌时间里[n]追加了审判的大阿尔卡那卡牌。[n][w][e]

[msg MSG_ESCAPE_FUKA_00 [山岸 风花]]
[f 2 1][bup 6 0 65535 50 0 0][vp 3 0 65535 5025 0 0]看来这里就是尽头了。[n]要现在返回吗？[n][w][e]

[sel SEL_ESCAPE_HERO top]
[f 2 1]离开蒙纳多[e]
[f 2 1]继续探索[e]

[msg MSG_ESCAPE_FUKA_10 [山岸 风花]]
[f 2 1][bup 6 0 65535 50 0 0]收到。[n][w][e]
[f 2 1][bup 6 0 65535 50 0 0]这里很容易迷路，[n]回来的路上请多加小心。[n][w][e]

[msg MSG_ESCAPE_FUKA_11 [山岸 风花]]
[f 2 1][bup 6 0 65535 50 0 0]还有什么遗漏吗？[n][w][e]
[f 2 1][bup 6 0 65535 50 0 0]虽然已经没有敌人了，[n]但这里仍然是个危险的地方。[n][w][e]
[f 2 1][bup 6 0 65535 50 0 0]探索时请提高警惕。[n][w][e]

[msg MND_ARAGAKI_REMIND]
[f 2 1]感觉很适合荒垣……[n]然而荒垣已经不在了……[n][w][e]

[msg MSG_TUTO01 [山岸 风花]]
[f 2 1][bup 6 0 65535 50 0 0][vp 3 0 65535 5071 0 0]这个东西和之前理事长[n]交给[nl]同学的很像呢。[n][w][e]
[f 2 1][bup 6 0 65535 50 0 0]据说是非常稀有的物品，[n]没想到能在这里的宝箱中发现……[n][w][e]

[msg MND_TUTO02]
[f 2 1]把这东西拿给古董店的店主，[n]她会帮忙加工成装备吗……[n][w][e]

[msg MSG_TUTO03 [山岸 风花]]
[f 2 1][bup 6 0 65535 50 0 0]基本都已经调查过一遍了呢。[n]辛苦大家了。[n][w][e]
[f 2 1][bup 6 0 65535 50 0 0]请先回到门外。[n][w][e]

[sel SEL_EQUIP_UPDATE_00 top]
[f 2 1]装备[f 4 4 1 0 0 0][e]
[f 2 1]维持现状[e]

[sel SEL_EQUIP_UPDATE_01 top]
[f 2 1]换上新装备[e]
[f 2 1]维持现状[e]

[sel SEL_EQUIP_UPDATE_02 top]
[f 2 1]交给由加莉[e]
[f 2 1]维持现状[e]

[sel SEL_EQUIP_UPDATE_03 top]
[f 2 1]交给顺平[e]
[f 2 1]维持现状[e]

[sel SEL_EQUIP_UPDATE_04 top]
[f 2 1]交给真田[e]
[f 2 1]维持现状[e]

[sel SEL_EQUIP_UPDATE_05 top]
[f 2 1]交给美鹤[e]
[f 2 1]维持现状[e]

[sel SEL_EQUIP_UPDATE_06 top]
[e]

[sel SEL_EQUIP_UPDATE_07 top]
[f 2 1]交给埃癸斯[e]
[f 2 1]维持现状[e]

[sel SEL_EQUIP_UPDATE_08 top]
[f 2 1]交给天田[e]
[f 2 1]维持现状[e]

[sel SEL_EQUIP_UPDATE_09 top]
[f 2 1]交给虎狼丸[e]
[f 2 1]维持现状[e]

[sel SEL_EQUIP_UPDATE_10 top]
[f 2 1]交给荒垣[e]
[f 2 1]维持现状[e]

[msg MND_EQUIP_UPDATE_HERO_00]
[f 2 1]和目前使用的武器相比，[n][f 4 4 1 0 1 0]似乎更强……[n][w][e]

[msg MSG_EQUIP_UPDATE_YUKARI_ [岳羽 由加莉]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 3 0 65535 1002 0 0]啊，这把弓不错嘛！[n]可以给我用吗？[n][w][e]

[msg MSG_EQUIP_UPDATE_JUNPEI_ [伊织 顺平]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2001 0 0]这武器看起来好强！[n]也只有我能发挥它的威力了吧？[n][w][e]

[msg MSG_EQUIP_UPDATE_SANADA_ [真田 明彦]]
[f 2 1][bup 4 1 65535 65535 0 0][vp 3 0 65535 3094 0 0]是新武器啊。[n]感觉比我现在用的这个要好。[n][w][e]

[msg MSG_EQUIP_UPDATE_MITSURU [桐条 美鹤]]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4086 0 0]这把武器性能不错啊。[n]可以交给我使用吗？[n][w][e]

[msg MSG_EQUIP_UPDATE_FUKA_00 [山岸 风花]]
[f 2 1][bup 6 1 65535 50 0 0][vp 3 0 65535 5087 0 0]原来里面是武器呀。[n]小虎应该能发挥它的威力吧？[n][w][e]

[msg MSG_EQUIP_UPDATE_AEGIS_0 [埃癸斯]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6080 0 0]确认获得武装。[n]我提议更换装备。[n][w][e]

[msg MSG_EQUIP_UPDATE_AMADA_0 [天田 乾]]
[f 2 1][bup 8 1 65535 65535 0 0][vp 3 0 65535 7005 0 0]是新的武器……[n]可以交给我使用吗！[n][w][e]

[msg MSG_EQUIP_UPDATE_KORO_00 [虎狼丸]]
[f 2 1][bup 9 1 65535 65535 0 0][vp 3 0 65535 8001 0 0]汪！汪！[n][w][e]

[msg MSG_EQUIP_UPDATE_ARAGAKI [荒垣 真次郎]]
[f 2 1][bup 10 1 65535 65535 0 0][vp 3 0 65535 9007 0 0]这武器看起来不错嘛。[n]把它给我吧。[n][w][e]

[msg MSG_EQUIP_UPDATE_AEGIS_0_2 [埃癸斯]]
[f 2 1][bup 7 1 65535 65535 0 0][vp 3 0 65535 6087 0 0]获得了新的武装。[n]可以将它交给我使用吗？[n][w][e]

[msg MND_EQUIP_UPDATE_HERO_01]
[f 2 1]和目前使用的装备相比，[n][f 4 4 1 0 1 0]的性能似乎更好……[n][w][e]

[msg MSG_EQUIP_UPDATE_YUKARI__2 [岳羽 由加莉]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 3 0 65535 1002 0 0]啊，这个很不错嘛！[n]可以给我用吗？[n][w][e]

[msg MSG_EQUIP_UPDATE_JUNPEI__2 [伊织 顺平]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2001 0 0]这个装备不错啊。[n]你不觉得它很适合我吗？[n][w][e]

[msg MSG_EQUIP_UPDATE_SANADA__2 [真田 明彦]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 3 0 65535 3094 0 0]噢，这个装备很适合我。[n]我可以拿走吗？[n][w][e]

[msg MSG_EQUIP_UPDATE_MITSURU_2 [桐条 美鹤]]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4086 0 0]看来拿到了不错的装备啊。[n]性能似乎比我现在用的更好。[n][w][e]

[msg MSG_EQUIP_UPDATE_FUKA_01 [山岸 风花]]
[f 2 1][bup 6 1 65535 50 0 0][vp 3 0 65535 5087 0 0]啊，这个装备应该很适合小虎吧？[n][w][e]

[msg MSG_EQUIP_UPDATE_AEGIS_0_3 [埃癸斯]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6080 0 0]里面是防具啊。[n]需要更换装备吗？[n][w][e]

[msg MSG_EQUIP_UPDATE_AMADA_0_2 [天田 乾]]
[f 2 1][bup 8 1 65535 65535 0 0][vp 3 0 65535 7005 0 0]这个可以给我用吗？[n]尺码不合适也没关系，我很快就会长高的！[n][w][e]

[msg MSG_EQUIP_UPDATE_KORO_01 [虎狼丸]]
[f 2 1][bup 9 1 65535 65535 0 0][vp 3 0 65535 8001 0 0]汪！汪！[n][w][e]

[msg MSG_EQUIP_UPDATE_ARAGAKI_2 [荒垣 真次郎]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 3 0 65535 9007 0 0]看起来不错嘛。[n]别人不要就给我吧。[n][w][e]

[msg MSG_EQUIP_UPDATE_AEGIS_0_4 [埃癸斯]]
[f 2 1][bup 7 1 65535 65535 0 0][vp 3 0 65535 6087 0 0]里面原来是防具啊。[n]看起来比我现在用的更结实。[n][w][e]

[msg MND_EQUIP_UPDATE_MULTI]
[f 2 1]要让谁装备[n][f 4 4 1 0 1 0]呢？[n][w][e]

[sel SEL_PARTY top]
[f 2 1]自己装备[e]
[f 2 1]由加莉[e]
[f 2 1]顺平[e]
[f 2 1]真田[e]
[f 2 1]美鹤[e]
[f 2 1]风花[e]
[f 2 1]埃癸斯[e]
[f 2 1]天田[e]
[f 2 1]虎狼丸[e]
[f 2 1]荒垣[e]
[f 2 1]维持现状[e]

[msg MND_EQUIP_UPDATE_HERO_10]
[f 2 1]装备了[f 4 4 1 0 1 0]。[n][w][e]

[msg MSG_EQUIP_UPDATE_YUKARI__3 [岳羽 由加莉]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 3 0 65535 1039 0 0]谢谢！[n]我会珍惜它的。[n][w][e]

[msg MSG_EQUIP_UPDATE_JUNPEI__3 [伊织 顺平]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2117 0 0]好，能力强化——！[n]一鼓作气继续前进吧！[n][w][e]

[msg MSG_EQUIP_UPDATE_SANADA__3 [真田 明彦]]
[f 2 1][bup 4 1 65535 65535 0 0][vp 3 0 65535 3042 0 0]我从不放松训练，[n]但有好装备用总归更理想。[n][w][e]

[msg MSG_EQUIP_UPDATE_MITSURU_3 [桐条 美鹤]]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4038 0 0]我会好好使用它的。[n]放心，我一定不辜负你的期待。[n][w][e]

[msg MSG_EQUIP_UPDATE_FUKA_10 [山岸 风花]]
[f 2 1][bup 6 1 65535 50 0 0][f 1 5 0][w][e]

[msg MSG_EQUIP_UPDATE_AEGIS_1 [埃癸斯]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6038 0 0]确认装备升级。[n]我一定会交出更好的战果。[n][w][e]

[msg MSG_EQUIP_UPDATE_AMADA_1 [天田 乾]]
[f 2 1][bup 8 1 65535 65535 0 0][vp 3 0 65535 7040 0 0]十分感谢。[n]我会努力帮上大家的忙！[n][w][e]

[msg MSG_EQUIP_UPDATE_KORO_10 [虎狼丸]]
[f 2 1][bup 9 1 65535 65535 0 0][vp 3 0 65535 8012 0 0]汪汪！[n][w][e]

[msg MSG_EQUIP_UPDATE_ARAGAKI_3 [荒垣 真次郎]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 3 0 65535 9051 0 0]谢啦。[n]我不会让你后悔的。[n][w][e]

[msg MSG_EQUIP_UPDATE_AEGIS_1_2 [埃癸斯]]
[f 2 1][bup 7 1 65535 65535 0 0][vp 3 0 65535 6039 0 0]装备已升级。[n]我将使用它更加努力地战斗！[n][w][e]

[msg MSG_HIGH_RARE_TUTO_MITU_ [桐条 美鹤]]
[f 2 1][bup 5 0 65535 50 0 0]暗影的反应又停下了。[n]距离这里好像有些远……[n][w][e]

[msg MSG_HIGH_RARE_TUTO_MITU__2 [桐条 美鹤]]
[f 2 1][bup 5 3 65535 50 0 0]宝箱被抢走了吗……[n]不过看来对方也已经注意到我们了。[n][w][e]
[f 2 1][bup 5 0 65535 50 0 0]只要我们继续开宝箱，[n]它应该也不能坐视不理。[n][w][e]
[f 2 1][bup 5 0 65535 50 0 0]继续寻找宝箱吧。[n][w][e]

[msg MSG_HIGH_RARE_TUTO_FUKA_ [山岸 风花]]
[f 2 1][bup 6 0 65535 50 0 0]暗影的反应又停下了。[n]离这里好像还有些距离……[n][w][e]

[msg MSG_HIGH_RARE_TUTO_FUKA__2 [山岸 风花]]
[f 2 1][bup 6 3 65535 50 0 0]宝箱被抢走了……[n]但对方应该已经发现我们了。[n][w][e]
[f 2 1][bup 6 0 65535 50 0 0]只要我们继续开宝箱，[n]它大概也不能坐视不理。[n][w][e]
[f 2 1][bup 6 0 65535 50 0 0]请继续寻找宝箱吧。[n][w][e]

[msg MSG_HIGH_RARE_BTL_MITU_0 [桐条 美鹤]]
[f 2 1][bup 5 0 65535 50 0 0]暗影正在靠近我们。[n]准备迎战吧！[n][w][e]

[msg MSG_HIGH_RARE_BTL_MITU_0_2 [桐条 美鹤]]
[f 2 1][bup 5 0 65535 50 0 0]确认暗影已消失。[n][w][e]
[f 2 1][bup 5 0 65535 50 0 0]这一楼层已经没有敌人的反应了。[n]继续前进吧。[n][w][e]

[msg MSG_HIGH_RARE_BTL_FUKA_0 [山岸 风花]]
[f 2 1][bup 6 0 65535 50 0 0]暗影正在向这边靠近！[n]迎击的机会来了。[n][w][e]

[msg MSG_HIGH_RARE_BTL_FUKA_0_2 [山岸 风花]]
[f 2 1][bup 6 0 65535 50 0 0]确认暗影已消失。[n][w][e]
[f 2 1][bup 6 0 65535 50 0 0]这一楼层已经没有敌人的反应了。[n]请继续前进吧。[n][w][e]

