[msg MSG_000_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 1 0 0]Man, I am beat![n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 2 0 0][f 4 23 0 106 1 25 25]I managed to stay awake all through class today! Pretty amazing, huh?[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0][vp 0 0 0 3 0 0]......[n][w][e]

[msg MSG_000_3_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 4 0 0]I kinda like days like this, when we don't have practice or anything.[n][w][e]
[f 2 1][bup 106 1 65535 65535 1 0][vp 1 0 0 5 0 0]You know, just to spend time with the one you like...[n][w][e]

[msg MSG_000_5_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 6 0 0]But at the same time, it's also kinda sad.[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 7 0 0]After you go home, I can still feel your presence in the air...[n][w][e]

[msg MSG_000_7_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 8 0 0][f 5 13 12 5 106]You'll stay just a little longer, won't you?[n][w][e]

[msg MND_001_0_0]
[f 2 1]I shared a special evening with Yuko.[n][w][e]
[f 2 1]I feel an unbreakable bond between us...[n][w][e]

