[msg MSG_000_0_0 [Yukari Takeba]]
[f 2 1][bup 2 2 52 65535 0 0][vp 1 0 0 1 0 0][nl]-chan, are you okay?[n][w][e]
[f 2 1][bup 2 3 52 65535 0 0][vp 1 0 0 2 0 0][f 4 23 0 2 3 25 25]I'm sorry. It was all my fault.[n][w][e]

[sel SEL_001_0_0 top]
[f 2 1]Good to see you're okay.[e]
[f 2 1]What was that just now...?[e]

[msg MSG_002_0_0 [Yukari Takeba]]
[f 2 1][bup 2 3 52 65535 0 0][vp 1 0 0 3 0 0]Thanks. But you shouldn't be so reckless.[n][w][e]

[msg MSG_003_0_0 [Yukari Takeba]]
[f 2 1][bup 2 3 52 65535 0 0][vp 1 0 0 4 0 0]I don't really know. My body just sort of took control.[n][w][e]

[msg MSG_004_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 2 52 65535 0 0][vp 1 0 0 5 0 0]Takeba! [nl]![n][w][e]

[msg MSG_005_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 52 65535 0 0][vp 1 0 0 6 0 0]Looks like you both are okay.[n][w][e]

[msg MSG_006_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 52 65535 0 0][vp 1 0 0 7 0 0]Sorry I worried everyone.[n][w][e]

[msg MSG_007_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 52 65535 0 0][vp 1 0 0 8 0 0]It's all right. You did well in handling an unexpected situation.[n][w][e]

[msg MSG_008_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 52 65535 0 0][vp 1 0 0 9 0 0]Maybe we should consider starting over. Let's head back to the entrance for now.[n][w][e]

