[msg MSG_000_0_0 [Ms. Toriumi]]
[f 2 1][bup 1581 0 65535 65535 0 0][vp 1 0 0 1 0 0][f 5 21 0 1581]Class, we have another new transfer student joining us today.[n][w][e]

[msg MSG_000_5_0 [Ms. Toriumi]]
[f 2 1][bup 1581 0 65535 65535 0 0][vp 1 0 0 2 0 0][f 5 21 0 1581]Go ahead and introduce yourself.[n][w][e]

[msg MSG_001_0_0 [Aigis]]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 3 0 0]My name is Aigis. I am pleased to meet you all.[n][w][e]

[msg MSG_002_0_0 [Ms. Toriumi]]
[f 2 1][bup 1581 0 65535 65535 0 0][vp 1 0 0 4 0 0][f 5 21 0 1581]Aigis-san...? I've never heard a name like that... Maybe she's a foreigner.[n][w][e]

[msg MSG_003_0_0 [Ms. Toriumi]]
[f 2 1][bup 1581 0 65535 65535 0 0][vp 1 0 0 5 0 0][f 5 21 0 1581]Let's see, anything else I should know? Hm? "Humanoid"... "tactical weapon"...?[n][w][e]

[msg MSG_004_0_0 [Yukari Takeba]]
[f 2 1][bup 2 4 1 65535 0 0][vp 1 0 0 6 0 0]What!?[n][w][e]

[msg MSG_005_0_0 [Ms. Toriumi]]
[f 2 1][bup 1581 0 65535 65535 0 0][vp 1 0 0 7 0 0][f 5 21 0 1581]...Clearly, that's a mistake.[n][w][e]
[f 2 1][bup 1581 1 65535 65535 0 0][vp 1 0 0 8 0 0][f 5 21 0 1581]It just goes to show, you can't believe everything you read.[n][w][e]

[msg MSG_006_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 1 65535 0 0][vp 1 0 0 9 0 0]Y-Yeah, you got that right![n][w][e]

[msg MSG_007_0_0 [Ms. Toriumi]]
[f 2 1][bup 1581 0 65535 65535 0 0][vp 1 0 0 10 0 0][f 5 21 0 1581]Let's see. You can sit, um... Are there any open seats?[n][w][e]

[msg MSG_008_0_0 [Ms. Toriumi]]
[f 2 1][bup 1581 0 65535 65535 0 0][vp 1 0 0 11 0 0][f 5 21 0 1581]Ooh, there's a spot, right next to her.[n][w][e]

[msg MSG_009_0_0 [Ms. Toriumi]]
[f 2 1][bup 1581 0 65535 65535 0 0][vp 1 0 0 12 0 0][f 5 21 0 1581]Okay, off you go.[n][w][e]

[msg MSG_010_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 1 65535 0 0][vp 1 0 0 13 0 0]Uh, Ms. Toriumi, someone already sits there. He just ditched today.[n][w][e]

[msg MSG_011_0_0 [Ms. Toriumi]]
[f 2 1][bup 1581 0 65535 65535 0 0][vp 1 0 0 14 0 0][f 5 21 0 1581]...Which means he's not here. So now it's yours.[n][w][e]
[f 2 1][bup 1581 0 65535 65535 0 0][vp 1 0 0 15 0 0][f 5 21 0 1581]All right, take your seat.[n][w][e]

[msg MSG_012_0_0 [Aigis]]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 16 0 0]This spot is perfect.[n][w][e]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 17 0 0]My highest priority is to be with her at all times.[n][w][e]

[msg MSG_013_0_0 [Yukari Takeba]]
[f 2 1][bup 2 2 1 65535 0 0][vp 1 0 0 18 0 0]Aigis![n][w][e]

[msg MSG_014_0_0 [Aigis]]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 19 0 0]What is it?[n][w][e]

[msg MSG_015_0_0 [Classmate's Voice]]
[f 2 1][vp 1 0 0 20 0 0]Uh, Yukari, why'd you stand up?[n][w][e]

[msg MSG_016_0_0 [Yukari Takeba]]
[f 2 1][bup 2 4 1 65535 0 0][vp 1 0 0 21 0 0]Uh, why—?[n][w][e]

[msg MSG_016_5_0 [Yukari Takeba]]
[f 2 1][bup 2 2 1 65535 0 0][vp 1 0 0 22 0 0]...Ugh![n][w][e]

[msg MSG_017_0_0 [Ms. Toriumi]]
[f 2 1][bup 1581 1 65535 65535 0 0][vp 1 0 0 23 0 0][f 5 21 0 1581]Good to see everyone's getting along so well.[n][w][e]
[f 2 1][bup 1581 2 65535 65535 0 0][vp 1 0 0 24 0 0][f 5 21 0 1581]But, do me a favor and save the drama for after class.[n][w][e]

[msg MSG_018_0_0 [Yukari Takeba]]
[f 2 1][bup 2 6 1 65535 0 0][vp 1 0 0 25 0 0]Gimme a break...[n][w][e]

