[msg MSG_000_0_0 [President Tanaka]]
[f 2 1][bup 113 1 65535 65535 0 0][vp 1 0 0 1 0 0][f 4 23 0 1 1 25 25]Just the other day, my high school organized a class reunion.[n][w][e]

[sel SEL_001_0_0 top]
[f 2 1]Sounds like fun![e]
[f 2 1]Sounds like a hassle.[e]

[msg MSG_002_0_0 [President Tanaka]]
[f 2 1][bup 113 1 65535 65535 0 0][vp 1 0 0 2 0 0][f 5 13 16 15 113]I had a splendid time! I laugh just thinking about it.[n][w][e]

[msg MSG_003_0_0 [President Tanaka]]
[f 2 1][bup 113 3 65535 65535 0 0][vp 1 0 0 3 0 0][f 4 23 0 1 3 25 25]Indeed it was. I had to pay for transportation and of course my hotel room.[n][w][e]

[msg MSG_004_0_0 [President Tanaka]]
[f 2 1][bup 113 0 65535 65535 0 0][vp 1 0 0 4 0 0][f 4 23 0 1 0 25 25]I doubt you'd understand how I feel, since you're still in high school, but...[n][w][e]
[f 2 1][bup 113 1 65535 65535 0 0][vp 1 0 0 5 0 0][f 4 23 0 1 1 25 25]A class reunion is a very important event. It's the perfect opportunity to show everyone how pathetic their lives turned out.[n][w][e]

[msg MSG_004_5_0 [President Tanaka]]
[f 2 1][bup 113 1 65535 65535 0 0][vp 1 0 0 6 0 0][f 4 23 0 1 1 25 25]Like that cad who made fun of me for eating plain rice... Or the ingrate who threw my holey socks in the trash.[n][w][e]
[f 2 1][bup 113 1 65535 65535 0 0][vp 1 0 0 7 0 0][f 4 23 0 1 1 25 25]Now, they both look at me with envy. What they make in a year, I make in a month![n][w][e]

[msg MSG_004_7_0 [President Tanaka]]
[f 2 1][bup 113 1 65535 65535 0 0][vp 1 0 0 8 0 0][f 4 23 0 1 1 25 25]My business is doing great, and I'd say I have a satisfying private life as well.[n][w][e]

[msg MSG_005_0_0 [President Tanaka]]
[f 2 1][bup 113 1 65535 65535 0 0][vp 1 0 0 9 0 0][f 4 23 0 1 1 25 25]Let me take you under my wing, as our exclusive model. It's a once-in-a-lifetime opportunity![n][w][e]
[f 2 1][bup 113 1 65535 65535 0 0][vp 1 0 0 10 0 0][f 4 23 0 1 1 25 25]Don't think I would extend this offer to just anyone.[n][w][e]

[msg MND_006_0_0 [Internal MES]]
[f 2 1]President Tanaka is opening up to me.[n][w][e]
[f 2 1]I understand him a little better now...[n][w][e]

[msg MSG_007_0_0 [President Tanaka]]
[f 2 1][bup 113 1 65535 65535 0 0][vp 1 0 0 11 0 0][f 4 23 0 1 1 25 25]Oh, remember that 40,000 yen you gave me? I'd say you've gotten your money's worth at this point.[n][w][e]
[f 2 1][bup 113 1 65535 65535 0 0][vp 1 0 0 12 0 0][f 4 23 0 1 1 25 25]My time is worth at least 100,000 yen per hour, you know![n][w][e]
[f 2 1][bup 113 1 65535 65535 0 0][vp 1 0 0 13 0 0][f 4 23 0 1 1 25 25]Just think of all the free advice I've given you! You can thank me later.[n][w][e]

[msg MND_008_0_0 [Internal MES]]
[f 2 1]It's getting late, so I'll go back to the dorm.[n][w][e]

