[msg MSG_001_0_0 [Calm Woman]]
[f 2 1][f 5 21 1 421]He seems like an interesting guy, but he's a really bad conversationalist.[n][w][e]
[f 2 1][f 5 21 1 421]I'm a little worried about him, since this is the time of year to make new friends.[n][w][e]

[msg MSG_002_0_0 [Calm Woman]]
[f 2 1][f 5 21 1 421]My boyfriend plays soccer at his college. I guess my taste in men is pretty standard...[n][w][e]
[f 2 1][f 5 21 1 421]He's not that good at soccer, though. He's still a third-stringer.[n][w][e]
[f 2 1][f 5 21 1 421]Don't you go to Gekkoukan? Are you in any clubs?[n][w][e]

[sel SEL_003_0_0 top]
[f 2 1]I am.[e]
[f 2 1]I'm not.[e]

[msg MSG_004_0_0 [Calm Woman]]
[f 2 1][f 5 21 1 421]Good luck, then.[n][w][e]

[msg MSG_005_0_0 [Calm Woman]]
[f 2 1][f 5 21 1 421]Well, it all depends on your personal taste.[n][w][e]
[f 2 1][f 5 21 1 421]You get to meet more people if you join a club, though.[n][w][e]

[msg MSG_008_0_0 [Calm Woman]]
[f 2 1][f 5 21 1 421]He's really overthinking this. He looks suave, but he worries what other people think too much.[n][w][e]
[f 2 1][f 5 21 1 421]I mean, I love that he cares about my opinion, but...[n][w][e]
[f 2 1][f 5 21 1 421]I think I'd prefer it if he didn't feel so nervous with me.[n][w][e]

[msg MSG_010_0_0 [Calm Woman]]
[f 2 1][f 5 21 1 421]He's sweating a lot now, but he's usually not like that.[n][w][e]
[f 2 1][f 5 21 1 421]That type of guy is pretty popular with the older ladies who work here.[n][w][e]
[f 2 1][f 5 21 1 421]Everyone remembers his face. I was surprised, to be honest.[n][w][e]
[f 2 1][f 5 21 1 421]It's amazing how many people say hello to him at shops...[n][w][e]

[msg MSG_013_0_0 [Calm Woman]]
[f 2 1][f 5 21 1 421]He's a sweet guy, but he seems to be holding back. It's like he won't allow himself to enjoy life.[n][w][e]
[f 2 1][f 5 21 1 421]Even after his friend and I offered to take him to the beach...[n][w][e]
[f 2 1][f 5 21 1 421]He just keeps turning us down, over and over... He'll never have fun that way.[n][w][e]
[f 2 1][f 5 21 1 421]But don't get me wrong, I won't leave him.[n][w][e]

[msg MSG_015_0_0 [Calm Woman]]
[f 2 1][f 5 21 1 421]It's that time of the year, huh?[n][w][e]
[f 2 1][f 5 21 1 421]Do you have a boyfriend? I bet you could get one if you tried.[n][w][e]
[f 2 1][f 5 21 1 421]You can do it! Just find anyone you're interested in and talk to them.[n][w][e]
[f 2 1][f 5 21 1 421]Even he managed to do it, so you should have no problem.[n][w][e]

[msg MSG_017_0_0 [Calm Woman]]
[f 2 1][f 5 21 1 421]That guy is just the type to take a question like that seriously.[n][w][e]
[f 2 1][f 5 21 1 421]I was just testing him, though...[n][w][e]
[f 2 1][f 5 21 1 421]But I think you'd do fine in a situation like that.[n][w][e]
[f 2 1][f 5 21 1 421]It's a trick we use to get the guy closer to us.[n][w][e]

[msg MSG_019_0_0 [Calm Woman]]
[f 2 1][f 5 21 1 421]Since we couldn't go to the beach this summer, he suggested we go to the mountains instead.[n][w][e]
[f 2 1][f 5 21 1 421]So I reminded him, and, well...[n][w][e]
[f 2 1][f 5 21 1 421]He got like this. It's so like him...[n][w][e]

[msg MSG_020_0_0 [Calm Woman]]
[f 2 1][f 5 21 1 421]I was about to tell him, "Okay," but...[n][w][e]
[f 2 1][f 5 21 1 421]I was so surprised that I pulled my hand out.[n][w][e]
[f 2 1][f 5 21 1 421]Did I do something wrong...?[n][w][e]

[msg MSG_021_0_0 [Calm Woman]]
[f 2 1][f 5 21 1 421]Love won't blossom if you just wait for it to happen.[n][w][e]
[f 2 1][f 5 21 1 421]If you want to get to know someone better, you have to put the effort in.[n][w][e]
[f 2 1][f 5 21 1 421]He isn't very assertive, so our relationship hasn't grown even a little.[n][w][e]
[f 2 1][f 5 21 1 421]But I don't mind, really...[n][w][e]

[msg MSG_022_0_0 [Calm Woman]]
[f 2 1][f 5 21 1 421]It sounds preachy to talk about moral stuff like this, but this is when people's bonds are tested.[n][w][e]
[f 2 1][f 5 21 1 421]At times like this, when the whole town is going crazy and there's nowhere to run...[n][w][e]
[f 2 1][f 5 21 1 421]I'm thankful he's here with me.[n][w][e]
[f 2 1][f 5 21 1 421]What about you? Do you have anyone who will stay with you?[n][w][e]

