[msg MND_000_0_0 [DEV: Internal MES]]
[f 2 1]There's something under Koromaru's paw...[n][w][e]
[f 2 1]I could pick it up if I ask[n]Koromaru to move his paw.[n][w][e]

[msg MSG_001_5_0 [Koromaru]]
[f 2 1][bup 9 0 65535 65535 0 0]Arf?[n][w][e]

[sel SEL_001_0_0 top]
[f 2 1]May I see underneath your paw?[e]
[f 2 1]It's nothing.[e]

[msg MSG_002_0_0 [Koromaru]]
[f 2 1][bup 9 0 65535 65535 0 0]Arf, arf![n][w][e]

[msg MND_003_0_0 [DEV: Internal MES]]
[f 2 1]It's a red fountain pen... This must be what[n]the young man at the shrine was looking for.[n][w][e]

[msg MSG_004_0_0 [Koromaru]]
[f 2 1][bup 9 0 65535 65535 0 0]Arf![n][w][e]

