[msg MSG_000_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 3 0 65535 11031 0 0]Thanks for coming to the bookstore with me today.[n][w][e]

[msg MSG_001_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0]But still, can't believe I'm buying books for studying, of all things.[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0]Who would've thought the day would come, am I right?[n][w][e]

[msg MSG_002_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 3 0 65535 11086 0 0]I must be in my prime![n][w][e]

[sel SEL_003_0_0 top]
[f 2 1]Hopefully.[e]
[f 2 1]Definitely.[e]
[f 2 1]This is only the beginning.[e]

[msg MSG_004_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 3 0 65535 11024 0 0]Well, either way, I better keep this up.[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0]Maybe I'll start with the subjects I'm not so good at today. I'm feeling real motivated for some reason.[n][w][e]

[msg MND_005_0_0]
[f 2 1]Yuko seems to be taking this seriously.[n][w][e]
[f 2 1]I feel like we didn't get any closer today...[n][w][e]

[msg MSG_006_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 3 0 65535 11024 0 0][f 5 13 12 15 106]Yeah. I gotta do everything I can.[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0]Usually, I can't stay motivated, so I end up quitting... But not this time![n][w][e]

[msg MND_007_0_0]
[f 2 1]Yuko seems to be enjoying herself.[n][w][e]
[f 2 1]I learned a little more about her today.[n][w][e]

[msg MSG_008_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 3 0 65535 11085 0 0][f 5 13 12 30 106]You're right. We're still teenagers.[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0]I've still got a long road ahead of me. Thanks, [nl]-chan![n][w][e]

[msg MND_009_0_0]
[f 2 1]Yuko seems impressed by what I said.[n][w][e]
[f 2 1]I feel like we became a lot closer today.[n][w][e]

[msg MSG_010_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 3 0 65535 11082 0 0]Thinking hard while surrounded by books this whole time is kinda making me hungry.[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0]Let's grab a snack from somewhere. Maybe something sweet?[n][w][e]

[msg MND_011_0_0]
[f 2 1]After getting something to eat with[n]Yuko, I decided to return to the dorm.[n][w][e]

