[msg MND_000_0_0 [Internal MES]]
[f 2 1]The scratching of pencils echoes[n]throughout the art room...[n][w][e]

[msg MSG_001_0_0 [Keisuke Hiraga]]
[f 2 1][bup 108 3 65535 65535 0 0][vp 1 0 0 1 0 0]Hey, [nl]-chan... Sorry, but I need your advice again.[n][w][e]

[msg MSG_002_0_0 [Keisuke Hiraga]]
[f 2 1][bup 108 0 65535 65535 0 0][vp 1 0 0 2 0 0]Let's meet up after art club like we did the other day.[n][w][e]

