[msg MSG_000_0_0 [Nozomi Suemitsu]]
[f 2 1][bup 116 2 65535 65535 0 0][vp 1 0 0 1 0 0][f 4 23 0 1 2 25 25]Hey, I haven't been doing so well lately, you know. And it's all because of your blasphemy![n][w][e]

[msg MSG_000_3_0 [Nozomi Suemitsu]]
[f 2 1][bup 116 3 65535 65535 0 0][vp 1 0 0 2 0 0][f 4 23 0 1 3 25 25]I begged so hard for your soul that I think I actually lost weight.[n][w][e]
[f 2 1][bup 116 3 65535 65535 0 0][vp 1 0 0 3 0 0][f 4 23 0 1 3 25 25]Look at me! I'm paper-thin now![n][w][e]

[sel SEL_001_0_0 top]
[f 2 1]You do look thinner.[e]
[f 2 1]No, you're not.[e]

[msg MSG_002_0_0 [Nozomi Suemitsu]]
[f 2 1][bup 116 0 65535 65535 0 0][vp 1 0 0 4 0 0][f 4 23 0 1 0 25 25]Oh, you really think so? I ate the same amount of food, though.[n][w][e]

[msg MSG_003_0_0 [Nozomi Suemitsu]]
[f 2 1][bup 116 1 65535 65535 0 0][vp 1 0 0 5 0 0][f 4 23 0 1 1 25 25][f 5 13 19 15 116]Damn straight! I could down a ham katsu in my sleep if I really wanted to![n][w][e]

[msg MSG_004_0_0 [Nozomi Suemitsu]]
[f 2 1][bup 116 3 65535 65535 0 0][vp 1 0 0 6 0 0][f 4 23 0 1 3 25 25]I get what you're trying to say... You're embarrassed to be seen with me, right?[n][w][e]
[f 2 1][bup 116 3 65535 65535 0 0][vp 1 0 0 7 0 0][f 4 23 0 1 3 25 25]I'm not like my little brother. I'm not smart or athletic, and I have weird, stubby legs.[n][w][e]

[msg MSG_004_3_0 [Nozomi Suemitsu]]
[f 2 1][bup 116 3 65535 65535 0 0][vp 1 0 0 8 0 0][f 4 23 0 1 3 25 25]And my pants are covered with food stains.[n][w][e]

[msg MSG_005_0_0 [Nozomi Suemitsu]]
[f 2 1][bup 116 2 65535 65535 0 0][vp 1 0 0 9 0 0][f 4 23 0 1 2 25 25]I'm just a thorn in everyone's side! They all wish I could be more like my little brother.[n][w][e]
[f 2 1][bup 116 2 65535 65535 0 0][vp 1 0 0 10 0 0][f 4 23 0 1 2 25 25]All they do is make fun of me! I just want this whole world to disappear![n][w][e]

[msg MSG_006_0_0 [Nozomi Suemitsu]]
[f 2 1][bup 116 3 65535 65535 0 0][vp 1 0 0 11 0 0][f 4 23 0 1 3 25 25]But the world can't end yet... Not until I save you first![n][w][e]

[msg MSG_006_3_0 [Nozomi Suemitsu]]
[f 2 1][bup 116 3 65535 65535 0 0][vp 1 0 0 12 0 0][f 4 23 0 1 3 25 25]Look. I can try harder [nf]-chan! I just need to make it to Paradise. That should solve all my problems![n][w][e]
[f 2 1][bup 116 1 65535 65535 0 0][vp 1 0 0 13 0 0][f 4 23 0 1 1 25 25]I'll be taller and more slender. And my body will glow, so I'll be safer at night![n][w][e]
[f 2 1][bup 116 1 65535 65535 0 0][vp 1 0 0 14 0 0][f 4 23 0 1 1 25 25]See? Then I won't be inferior to my brother, and you won't hate being seen with me![n][w][e]

[msg MSG_006_5_0 [Nozomi Suemitsu]]
[f 2 1][bup 116 3 65535 65535 0 0][vp 1 0 0 15 0 0][f 4 23 0 1 3 25 25]So, please... don't abandon me.[n][w][e]

[msg MND_007_0_0]
[f 2 1]I feel a strong connection with Suemitsu...[n][w][e]

[msg MSG_008_0_0 [Nozomi Suemitsu]]
[f 2 1][bup 116 3 65535 65535 0 0][vp 1 0 0 16 0 0][f 4 23 0 1 3 25 25]I have to go, so I don't have time to eat today. I haven't earned forgiveness just yet...[n][w][e]
[f 2 1][bup 116 3 65535 65535 0 0][vp 1 0 0 17 0 0][f 4 23 0 1 3 25 25]And I have to find a new member to recruit soon...[n][w][e]

[msg MSG_009_0_0 [Middle-Aged Man's Voice]]
[f 2 1][vp 1 0 0 18 0 0][f 5 21 0 2]That was him just now. So can you handle it?[n][w][e]

[msg MSG_010_0_0 [Thug]]
[f 2 1][vp 1 0 0 19 0 0][f 5 21 0 3]Sure. All I gotta do is rough him up and I get paid?[n][w][e]
[f 2 1][vp 1 0 0 20 0 0][f 5 21 0 3]You know, I've got this buddy who's kinda strapped for cash, too, if you catch my drift.[n][w][e]

[msg MSG_011_0_0 [Bitter-Looking Man]]
[f 2 1][vp 1 0 0 21 0 0][f 5 21 0 2]Fine, you'll both get paid. Just make sure you finish the job.[n][w][e]

[msg MSG_011_5_0 [Bitter-Looking Man]]
[f 2 1][vp 1 0 0 22 0 0]Hm?[n][w][e]
[f 2 1][vp 1 0 0 23 0 0][f 5 21 0 2]Oh, it's you...[n][w][e]

[msg MSG_012_0_0 [Bitter-Looking Man]]
[f 2 1][vp 1 0 0 24 0 0][f 5 21 0 2]132,000 yen, right? That's the same trick he used on my son.[n][w][e]
[f 2 1][vp 1 0 0 25 0 0][f 5 21 0 2]If you know what's good for you... stay the hell away from him.[n][w][e]

[msg MND_013_0_0]
[f 2 1]...I decided to go back to the dorm.[n][w][e]

