[msg MSG_000_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 1 65535 65535 0 0][vp 1 0 0 1 0 0]But yeah, Emiri is— Oh, that's Ms. Kanou's first name. Anyway, Emiri's really popular with the guys.[n][w][e]
[f 2 1][bup 101 1 65535 65535 0 0][vp 1 0 0 2 0 0]And I kinda took her away from them, y'know? Like, she became my girl before they even had a chance.[n][w][e]

[msg MSG_000_3_0 [Kenji Tomochika]]
[f 2 1][bup 101 0 65535 65535 0 0][vp 1 0 0 3 0 0]Turns out Emiri's a really strict teacher when it comes to grades.[n][w][e]
[f 2 1][bup 101 1 65535 65535 0 0][vp 1 0 0 4 0 0][f 4 23 0 101 1 25 25]At home, though, she's a real sweetheart! I love how her attitude changes when she's with me...[n][w][e]

[msg MSG_001_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 1 65535 65535 0 0][vp 1 0 0 5 0 0]Yeah, good-looking people just flock together, y'know? It's like a law of attraction.[n][w][e]

[sel SEL_002_0_0 top]
[f 2 1]...Is that so?[e]
[f 2 1]Okay...[e]
[f 2 1]Good-looking, huh?[e]

[msg MSG_003_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 1 65535 65535 0 0][vp 1 0 0 6 0 0][f 5 13 2 5 101]Aw, hey, I didn't mean to hit a nerve! C'mon, don't worry. We're still gonna hang out, alright?[n][w][e]

[msg MSG_004_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 1 65535 65535 0 0][vp 1 0 0 7 0 0][f 5 13 2 15 101]I know, right!? It's like we're actually in a TV show![n][w][e]

[msg MSG_005_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 3 65535 65535 0 0][vp 1 0 0 8 0 0]Hey, I'm just messing around! Don't take me so seriously![n][w][e]
[f 2 1][bup 101 0 65535 65535 0 0][vp 1 0 0 9 0 0][f 4 23 0 101 0 25 25]Well, Emiri is pretty gorgeous...[n][w][e]

[msg MSG_006_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 1 65535 65535 0 0][vp 1 0 0 10 0 0]Anyway, what about you, [nl]? Make any progress?[n][w][e]
[f 2 1][bup 101 1 65535 65535 0 0][vp 1 0 0 11 0 0]I feel guilty hogging all the happiness, so I'm gonna wish for you to be happy, too.[n][w][e]

[msg MSG_006_3_0 [Kenji Tomochika]]
[f 2 1][bup 101 4 65535 65535 0 0][vp 1 0 0 12 0 0]And hey, don't tell anyone about me and Emiri, okay? 'Cause teachers aren't allowed to date students.[n][w][e]
[f 2 1][bup 101 1 65535 65535 0 0][vp 1 0 0 13 0 0][f 4 23 0 101 1 25 25]I only told you because I trust you.[n][w][e]

[msg MND_007_0_0]
[f 2 1]Tomochika really trusts me...[n][w][e]
[f 2 1]I feel like our relationship is stronger...[n][w][e]

[msg MSG_008_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 0 65535 65535 0 0][vp 1 0 0 14 0 0]Shoot, look at the time. I'm way behind on my favorite show.[n][w][e]
[f 2 1][bup 101 1 65535 65535 0 0][vp 1 0 0 15 0 0][f 4 23 0 101 1 25 25]Well, I guess that's because real life is way better than any show right now.[n][w][e]

[msg MND_009_0_0]
[f 2 1]I don't think Tomochika's ever[n]going to stop talking...[n][w][e]
[f 2 1]I ended the conversation at[n]a good spot and went home.[n][w][e]

