[msg MSG_000_0_0 [Bebe]]
[f 2 1][bup 112 2 65535 65535 0 0][vp 1 0 0 1 0 0]Sewing is my life...[n][w][e]
[f 2 1][bup 112 3 65535 65535 0 0][vp 1 0 0 2 0 0]My wallet may be light, and my materials may be cheap...[n][w][e]

[msg MSG_000_3_0 [Bebe]]
[f 2 1][bup 112 0 65535 65535 0 0][vp 1 0 0 3 0 0]But I will work hard to make a beautiful kimono and save my future![n][w][e]

[msg MND_001_0_0]
[f 2 1]I helped Bebe work on the kimono.[n][w][e]

[msg MSG_002_0_0 [Bebe]]
[f 2 1][bup 112 0 65535 65535 0 0][vp 1 0 0 4 0 0]Hmm... Oui, this is starting to come together! Manzoku![n][w][e]

[msg MSG_002_3_0 [Bebe]]
[f 2 1][bup 112 1 65535 65535 0 0][vp 1 0 0 5 0 0]When my uncle sees this, I know he'll agree with me about how great Nihon is![n][w][e]

[sel SEL_003_0_0 top]
[f 2 1]When will it be done?[e]
[f 2 1]He'll definitely agree![e]
[f 2 1]Less talk, more work.[e]

[msg MSG_004_0_0 [Bebe]]
[f 2 1][bup 112 0 65535 65535 0 0][vp 1 0 0 6 0 0][f 5 13 15 5 112]It's far from being finished...[n][w][e]
[f 2 1][bup 112 0 65535 65535 0 0][vp 1 0 0 7 0 0]So I must work even harder![n][w][e]

[msg MSG_005_0_0 [Bebe]]
[f 2 1][bup 112 1 65535 65535 0 0][vp 1 0 0 8 0 0][f 5 13 15 15 112]I believe you, [nf]-sama! Which means I must work even harder![n][w][e]

[msg MSG_006_0_0 [Bebe]]
[f 2 1][bup 112 3 65535 65535 0 0][vp 1 0 0 9 0 0]I don't have the ability to stay that focused.[n][w][e]

[msg MSG_007_0_0 [Bebe]]
[f 2 1][bup 112 2 65535 65535 0 0][vp 1 0 0 10 0 0]But I know I can work harder than this![n][w][e]

[msg MSG_008_0_0 [Bebe]]
[f 2 1][bup 112 1 65535 65535 0 0][vp 1 0 0 11 0 0]I made so much progress today! And I could not have done it without your help![n][w][e]

[msg MSG_008_3_0 [Bebe]]
[f 2 1][bup 112 1 65535 65535 0 0][vp 1 0 0 12 0 0]Merci! Arigatou! Thank you![n][w][e]

[msg MND_009_0_0]
[f 2 1]Bebe seems truly grateful.[n][w][e]
[f 2 1]I feel like we're growing closer...[n][w][e]

[msg MSG_010_0_0 [Bebe]]
[f 2 1][bup 112 3 65535 65535 0 0][vp 1 0 0 13 0 0]Oooh... My arms are so very tired.[n][w][e]
[f 2 1][bup 112 3 65535 65535 0 0][vp 1 0 0 14 0 0]I must have overworked them.[n][w][e]
[f 2 1][bup 112 3 65535 65535 0 0][vp 1 0 0 15 0 0]But no matter what the cost, I will finish this kimono![n][w][e]

[msg MSG_010_3_0 [Bebe]]
[f 2 1][bup 112 2 65535 65535 0 0][vp 1 0 0 16 0 0]For my future, for Nihon... I cannot give up now![n][w][e]

[msg MND_011_0_0]
[f 2 1]I spent the day helping Bebe[n]then went back to the dorm.[n][w][e]

