[msg MSG_000_0_0 [Octopia Shopkeeper]]
[f 2 1][vp 3 0 65535 20101 0 0][f 5 21 1 103]Hey, come over here, young lady![n][w][e]
[f 2 1][f 5 21 1 103]My takoyaki is both delicious and cheap! Only 400 yen![n][w][e]
[f 2 1][vp 3 0 65535 20102 0 0][f 5 21 1 103]There's no octopus in it, but... try some anyway![n][w][e]

[msg MSG_004_0_0 [Octopia Shopkeeper]]
[f 2 1][vp 3 0 65535 20105 0 0][f 5 21 1 103]Thanks! Come again![n][w][e]

[msg MND_010_0_0]
[f 2 1]The shutters are down...[n][w][e]

