[msg MSG_000_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 1 65535 65535 0 0][vp 1 0 0 1 0 0][nl]-chan, over here![n][w][e]
[f 2 1][bup 109 0 65535 65535 0 0][vp 1 0 0 2 0 0][f 4 22 0 109 25 25 20]Can you believe I went to the faculty office and said all that? I even surprised myself a bit![n][w][e]
[f 2 1][bup 109 0 65535 65535 0 0][vp 1 0 0 3 0 0]This whole thing is just... Hehe.[n][w][e]
[f 2 1][bup 109 1 65535 65535 0 0][vp 1 0 0 4 0 0][f 4 23 0 109 1 25 25][f 4 22 0 109 31 25 20]Ehehehehe![n][w][e]

[sel SEL_001_0_0 top]
[f 2 1]What's gotten into you?[e]
[f 2 1]So you ARE guilty.[e]

[msg MSG_002_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 1 65535 65535 0 0][vp 1 0 0 5 0 0][f 5 13 9 5 109]Come on... Can you blame me? Hehe, ahaha...[n][w][e]

[msg MSG_003_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 3 65535 65535 0 0][vp 1 0 0 6 0 0]No. I'm. Not![n][w][e]

[msg MSG_004_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 1 65535 65535 0 0][vp 1 0 0 7 0 0]Remember when I said, "I can't allow that!" to the student council president? Hehe...[n][w][e]

[msg MSG_004_5_0 [Chihiro Fushimi]]
[f 2 1][bup 109 0 65535 65535 0 0][vp 1 0 0 8 0 0]It's just, when I thought about you and Miss President being alone in a room together...[n][w][e]
[f 2 1][bup 109 0 65535 65535 0 0][vp 1 0 0 9 0 0]I got really mad at even the thought of it.[n][w][e]

[msg MND_005_0_0]
[f 2 1]Chihiro has a refreshed smile on her face.[n][w][e]
[f 2 1]I feel like our relationship has grown...[n][w][e]

[msg MSG_006_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 1 65535 65535 0 0][vp 1 0 0 10 0 0]I've been like that ever since I was little, or so my mom says.[n][w][e]
[f 2 1][bup 109 1 65535 65535 0 0][vp 1 0 0 11 0 0]Normally, I'm quiet and timid, but when it comes to something I care about, I get really aggressive.[n][w][e]

[msg MSG_006_5_0 [Chihiro Fushimi]]
[f 2 1][bup 109 0 65535 65535 1 0][vp 1 0 0 12 0 0]It's because I...[n][w][e]

[msg MSG_007_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 0 65535 65535 0 0][vp 1 0 0 13 0 0]U-Um... [nl]-chan...[n][w][e]
[f 2 1][bup 109 0 65535 65535 0 0][vp 1 0 0 14 0 0][f 4 22 0 109 25 25 20]There's... something I want to say to you.[n][w][e]

[msg MSG_008_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 0 65535 65535 0 0][vp 1 0 0 15 0 0]Actually... I've wanted to say it for a while, but I didn't think I had it in me.[n][w][e]
[f 2 1][bup 109 0 65535 65535 0 0][vp 1 0 0 16 0 0]But, I think I can do it now.[n][w][e]

[msg MND_010_0_0]
[f 2 1]I better choose my words carefully here...[n][w][e]

[msg MND_011_0_0]
[f 2 1]I better choose my words carefully here...[n][w][e]
[f 2 1]Come to think of it, [clr 2]I have a special[clr 27][n][clr 2]relationship with another person already[clr 27]...[n][w][e]

[msg MSG_009_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 0 65535 65535 0 0][vp 1 0 0 17 0 0][nl]-san, I... I lo...[n][w][e]
[f 2 1][bup 109 1 65535 65535 0 0][vp 1 0 0 18 0 0][f 4 23 0 109 1 25 25]I love you![n][w][e]

[sel SEL_012_0_0 top]
[f 2 1]I feel the same, Chihiro.[f 2 9 1 1 351][e]
[f 2 1]I like working with you, but...[e]

[msg MSG_013_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 4 65535 65535 0 0][vp 1 0 0 19 0 0]Huh? What did you say...?[n][w][e]

[sel SEL_014_0_0 top]
[f 2 1]I said I feel the same.[e]
[f 2 1]I love you.[e]

[msg MSG_015_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 1 65535 65535 1 0][vp 1 0 0 20 0 0]Oh, I'm so happy, [nl]-chan![n][w][e]
[f 2 1][bup 109 1 65535 65535 1 0][vp 1 0 0 21 0 0]It feels like something out of a manga.[n][w][e]
[f 2 1][bup 109 1 65535 65535 1 0][vp 1 0 0 22 0 0][f 4 22 0 109 53 25 20]Um, uh... I hope we continue to get along well together.[n][w][e]

[msg MND_016_0_0]
[f 2 1]I have entered a special[n]relationship with Chihiro...[n][w][e]

[msg MND_017_0_0]
[f 2 1]There's no going back now...[n][w][e]

[msg MSG_018_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 0 65535 65535 0 0][vp 1 0 0 23 0 0]Oh! I still have to apologize to the student council president.[n][w][e]
[f 2 1][bup 109 1 65535 65535 0 0][vp 1 0 0 24 0 0][f 4 22 0 109 24 25 21][f 4 23 0 109 1 25 25]Um, is it okay if I ask you to wait by the school gate?[n][w][e]
[f 2 1][bup 109 1 65535 65535 1 0][vp 1 0 0 25 0 0]I'd like for us to be able to go home together...[n][w][e]

[msg MND_019_0_0]
[f 2 1]After speaking with Mitsuru, we[n]headed back home together.[n][w][e]
[f 2 1]...I ended up getting home[n]a little later than usual.[n][w][e]

[msg MSG_020_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 10 65535 65535 0 0][vp 1 0 0 26 0 0]O-Oh, I see...[n][w][e]

[msg MSG_021_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 3 65535 65535 0 0][vp 1 0 0 27 0 0]Umm...![n][w][e]
[f 2 1][bup 109 3 65535 65535 0 0][vp 1 0 0 28 0 0]Then, do you think... we could still be friends?[n][w][e]

[sel SEL_022_0_0 top]
[f 2 1]Sure thing.[e]
[f 2 1]Yeah, friends.[e]

[msg MSG_023_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 0 65535 65535 0 0][vp 1 0 0 29 0 0]Oh, thank goodness...[n][w][e]
[f 2 1][bup 109 0 65535 65535 0 0][vp 1 0 0 30 0 0]I'm just glad that we're still closer than when we first met.[n][w][e]

[msg MSG_024_0_0 [Chihiro Fushimi]]
[f 2 1][bup 109 1 65535 65535 0 0][vp 1 0 0 31 0 0]Oh! I still have to apologize to the student council president.[n][w][e]

[msg MSG_024_3_0 [Chihiro Fushimi]]
[f 2 1][bup 109 10 65535 65535 0 0][vp 1 0 0 32 0 0]I think I owe her an explanation, so... Excuse me.[n][w][e]

[msg MND_025_0_0]
[f 2 1]I parted ways with Chihiro, then[n]headed back to the dorm alone...[n][w][e]

