[msg MSG_000_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2014 0 0]'Sup, [nf]?[n][w][e]

[msg MSG_001_0_0 [Ryoji Mochizuki]]
[f 2 1][bup 221 0 65535 65535 0 0][vp 3 0 65535 14001 0 0]Good morning, [nf]-chan.[n][w][e]

[sel SEL_002_0_0 top]
[f 2 1]Morning.[e]
[f 2 1]This is an unusual sight.[e]

[msg MSG_003_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2075 0 0]Hey, you know, the two of you would totally get along.[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]He actually wanted to know more about Gekkoukan High, so naturally I had to share my wisdom with him.[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]Anyways, he's a real cool dude to hang with.[n][w][e]

[msg MSG_004_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2075 0 0]We just ran into each other earlier and started talking.[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]He actually wanted to know more about Gekkoukan High, so naturally I had to share my wisdom with him.[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]Anyways, he's a real cool dude to hang with.[n][w][e]

[msg MSG_005_0_0 [Ryoji Mochizuki]]
[f 2 1][bup 221 1 65535 65535 0 0][vp 3 0 65535 14018 0 0]Thanks for helping me out, Junpei-kun.[n][w][e]
[f 2 1][bup 221 1 65535 65535 0 0]Thanks especially for telling me who's in the "Top Ten Cuties of Gekkoukan High," too.[n][w][e]

[msg MSG_006_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 65535 65535 0 0][vp 3 0 65535 2127 0 0]Shhh! Pipe down![n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0][f 4 23 0 3 0 25 25]If Yuka-tan hears about this, my rep's gonna go down the toilet![n][w][e]

[sel SEL_007_0_0 top]
[f 2 1]But I want to know, too.[e]
[f 2 1]Isn't it already rock bottom?[e]

[msg MSG_008_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2108 0 0]Ohoho! Look at who's showing interest all of a sudden![n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]Well then, I'd like your opinion, too. It's a very serious matter, see.[n][w][e]

[msg MSG_009_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 65535 65535 0 0][vp 3 0 65535 2113 0 0]Dude, quit rubbing salt into my wound! I'm just an easily misunderstood fella, okay?[n][w][e]

[msg MSG_010_0_0 [Ryoji Mochizuki]]
[f 2 1][bup 221 1 65535 65535 0 0][vp 3 0 65535 14030 0 0]Hahaha, you two are pretty close, huh.[n][w][e]
[f 2 1][bup 221 1 65535 65535 0 0]I hope we can also be good friends, too, [nf]-chan, since we're both transfer students and all.[n][w][e]

