[msg MSG_000_0_0 [Keisuke Hiraga]]
[f 2 1][bup 108 0 65535 65535 0 0][vp 3 0 65535 11265 0 0]Oh, [nl]-chan.[n][w][e]
[f 2 1][bup 108 0 65535 65535 0 0]I'm going to club right now. What are you going to do?[n][w][e]

[msg MSG_001_0_0 [Keisuke Hiraga]]
[f 2 1][bup 108 3 65535 65535 0 0]Unused[n][w][e]

[msg MSG_002_0_0 [Keisuke Hiraga]]
[f 2 1][bup 108 0 65535 65535 0 0][vp 3 0 65535 11204 0 0][nl]-chan...[n][w][e]
[f 2 1][bup 108 3 65535 65535 0 0]Can you make time for art club today? I'd really appreciate it if you could come.[n][w][e]

[msg MND_003_0_0]
[f 2 1]Should I spend some time[n]after school at the art club?[n][w][e]

[sel SEL_004_0_0 top]
[f 2 1]Go to art club[e]
[f 2 1]Check Social Link status[e]
[f 2 1]Not now[e]

[msg MSG_005_0_0 [Keisuke Hiraga]]
[f 2 1][bup 108 1 65535 65535 0 0][vp 3 0 65535 11293 0 0]Oh, then let's go together.[n][w][e]

[msg MSG_006_0_0 [Keisuke Hiraga]]
[f 2 1][bup 108 3 65535 65535 0 0]Unused[n][w][e]

[msg MSG_007_0_0 [Keisuke Hiraga]]
[f 2 1][bup 108 4 65535 65535 0 0]Unused[n][w][e]

[msg MND_008_0_0]
[f 2 1]Unused[n][w][e]

[msg MSG_009_0_0 [Keisuke Hiraga]]
[f 2 1][bup 108 0 65535 65535 0 0][vp 3 0 65535 11246 0 0]Oh, okay... I'll see you later, then.[n][w][e]

[msg MSG_010_0_0 [Keisuke Hiraga]]
[f 2 1][bup 108 0 65535 65535 0 0]Oh, right.[n][w][e]
[f 2 1][bup 108 0 65535 65535 0 0]I'm going to club right now. What are you going to do?[n][w][e]

[msg MSG_011_0_0 [Keisuke Hiraga]]
[f 2 1][bup 108 3 65535 65535 0 0]Unused[n][w][e]

[msg MSG_012_0_0 [Keisuke Hiraga]]
[f 2 1][bup 108 0 65535 65535 0 0]Oh, by the way...[n][w][e]
[f 2 1][bup 108 0 65535 65535 0 0]Can you make time for art club today? I'd really appreciate it if you could come.[n][w][e]

[msg MSG_013_0_0 [Keisuke Hiraga]]
[f 2 1][bup 108 0 65535 65535 0 0][vp 3 0 65535 11202 0 0]Oh, [nl]-chan. How did you do on your exams?[n][w][e]

[msg MSG_014_0_0 [Keisuke Hiraga]]
[f 2 1][bup 108 1 65535 65535 0 0]In any case, now that we're finally done, the art club can be more active again.[n][w][e]

[msg MSG_015_0_0 [Keisuke Hiraga]]
[f 2 1][bup 108 1 65535 65535 0 0]In any case, we're finally done. I studied pretty hard this time around.[n][w][e]

[msg MSG_016_0_0 [Keisuke Hiraga]]
[f 2 1][bup 108 1 65535 65535 0 0][vp 3 0 65535 11201 0 0]Oh, [nl]-chan.[n][w][e]
[f 2 1][bup 108 0 65535 65535 0 0]I'm about to head to club... What are you going to do today?[n][w][e]

[msg MSG_016_5_0 [Keisuke Hiraga]]
[f 2 1][bup 108 0 65535 65535 0 0]Oh, right! I'm about to head to club... What are you going to do today?[n][w][e]

[msg MSG_017_0_0 [Keisuke Hiraga]]
[f 2 1][bup 108 1 65535 65535 0 0][vp 3 0 65535 11223 0 0]Great! Then let's go.[n][w][e]
[f 2 1][bup 108 1 65535 65535 0 0]For now, draw whatever you want. Just let me know if you have any questions.[n][w][e]

[msg MSG_018_0_0 [Keisuke Hiraga]]
[f 2 1][bup 108 1 65535 65535 0 0][vp 3 0 65535 11212 0 0]Oh, [nl]-chan.[n][w][e]
[f 2 1][bup 108 0 65535 65535 0 0]I just got here myself. Are you going to be at the art club today?[n][w][e]

[msg MSG_018_5_0 [Keisuke Hiraga]]
[f 2 1][bup 108 0 65535 65535 0 0]By the way, are you going to be at the art club today?[n][w][e]

[msg MSG_019_0_0 [Keisuke Hiraga]]
[f 2 1][bup 108 1 65535 65535 0 0][vp 3 0 65535 11293 0 0]Great! Looking forward to seeing you there.[n][w][e]
[f 2 1][bup 108 0 65535 65535 0 0]Oh yeah, that reminds me... I let the club advisor know about you.[n][w][e]

[msg MSG_020_0_0 [Keisuke Hiraga]]
[f 2 1][bup 108 0 65535 65535 0 0][vp 3 0 65535 11265 0 0]Oh, [nl]-chan.[n][w][e]
[f 2 1][bup 108 3 65535 65535 0 0]Will you be attending club activities today? I need to talk to you about the future...[n][w][e]

[msg MSG_020_5_0 [Keisuke Hiraga]]
[f 2 1][bup 108 3 65535 65535 0 0]Oh, will you be attending club activities today? I need to talk to you about the future...[n][w][e]

[msg MSG_021_0_0 [Keisuke Hiraga]]
[f 2 1][bup 108 0 65535 65535 0 0][vp 3 0 65535 11219 0 0]Okay, let's go.[n][w][e]
[f 2 1][bup 108 3 65535 65535 0 0]...The talk can wait. I think everyone's waiting on us.[n][w][e]

[msg MSG_022_0_0 [Keisuke Hiraga]]
[f 2 1][bup 108 0 65535 65535 0 0][vp 3 0 65535 11201 0 0]Oh, [nl]-chan, do you think you can make it to art club today?[n][w][e]

[msg MSG_022_5_0 [Keisuke Hiraga]]
[f 2 1][bup 108 0 65535 65535 0 0]By the way, are you going to art club today?[n][w][e]

[msg MSG_023_0_0 [Keisuke Hiraga]]
[f 2 1][bup 108 1 65535 65535 0 0][vp 3 0 65535 11219 0 0]Great, I'll see you there.[n][w][e]
[f 2 1][bup 108 3 65535 65535 0 0]In which case, um...[n][w][e]
[f 2 1][bup 108 0 65535 65535 0 0]Oh, never mind. Let's just focus on making some art.[n][w][e]

[msg MSG_024_0_0 [Keisuke Hiraga]]
[f 2 1][bup 108 3 65535 65535 0 0][vp 3 0 65535 11263 0 0]...[nl]-chan. Are you going to art club?[n][w][e]

[msg MSG_024_5_0 [Keisuke Hiraga]]
[f 2 1][bup 108 0 65535 65535 0 0]Oh, right. Are you going to art club?[n][w][e]

[msg MSG_025_0_0 [Keisuke Hiraga]]
[f 2 1][bup 108 0 65535 65535 0 0][vp 3 0 65535 11219 0 0]Great! I'll see you there.[n][w][e]
[f 2 1][bup 108 3 65535 65535 0 0][vp 3 0 65535 11252 0 0][f 4 25 108]......[n][w][e]

[msg MSG_026_0_0 [Keisuke Hiraga]]
[f 2 1][bup 108 0 65535 65535 0 0][vp 3 0 65535 11202 0 0]Oh, [nl]-chan, do you think you can make it to art club today?[n][w][e]

[msg MSG_026_5_0 [Keisuke Hiraga]]
[f 2 1][bup 108 0 65535 65535 0 0]Oh, [nl]-chan, do you think you can make it to art club today?[n][w][e]

[msg MSG_027_0_0 [Keisuke Hiraga]]
[f 2 1][bup 108 1 65535 65535 0 0][vp 3 0 65535 11293 0 0]Okay, then I'll see you there.[n][w][e]
[f 2 1][bup 108 3 65535 65535 0 0]*yawn* I'm feeling a little tired today...[n][w][e]

[msg MSG_028_0_0 [Keisuke Hiraga]]
[f 2 1][bup 108 3 65535 65535 0 0][vp 3 0 65535 11234 0 0]Thanks. Actually, I'm thinking of...[n][w][e]
[f 2 1][bup 108 1 65535 65535 0 0]Never mind, it's nothing. We can talk about that later. I should go see how everyone's doing first.[n][w][e]

[msg MSG_029_0_0 [Keisuke Hiraga]]
[f 2 1][bup 108 1 65535 65535 0 0][vp 3 0 65535 11261 0 0]Oh, [nl]-chan.[n][w][e]
[f 2 1][bup 108 0 65535 65535 0 0]There's something I need to tell everyone today...[n][w][e]
[f 2 1][bup 108 0 65535 65535 0 0]And, as the club leader, I'd like for you to be there, too.[n][w][e]

[msg MSG_029_5_0 [Keisuke Hiraga]]
[f 2 1][bup 108 0 65535 65535 0 0]Hey, [nl]-chan.[n][w][e]
[f 2 1][bup 108 0 65535 65535 0 0]There's something I need to tell everyone today.[n][w][e]
[f 2 1][bup 108 0 65535 65535 0 0]And, as the club leader, I'd like for you to be there, too.[n][w][e]

[msg MSG_030_0_0 [Keisuke Hiraga]]
[f 2 1][bup 108 1 65535 65535 0 0][vp 3 0 65535 11232 0 0]...Thank you.[n][w][e]
[f 2 1][bup 108 0 65535 65535 0 0]I think everyone else is already there, so let's just draw like we usually do first.[n][w][e]

[msg MSG_031_0_0 [Keisuke Hiraga]]
[f 2 1]Unused[n][w][e]

[msg MSG_032_0_0 [Keisuke Hiraga]]
[f 2 1][bup 108 0 65535 65535 0 0][vp 3 0 65535 11246 0 0]Are you busy? Maybe next time, then.[n][w][e]

[msg MSG_033_0_0 [Keisuke Hiraga]]
[f 2 1]Unused[n][w][e]

[msg MSG_034_0_0 [Keisuke Hiraga]]
[f 2 1][bup 108 0 65535 65535 0 0][vp 3 0 65535 11246 0 0]Oh, all right then. Be careful on your way home.[n][w][e]

[msg MSG_035_0_0 [Keisuke Hiraga]]
[f 2 1][bup 108 0 65535 65535 0 0][vp 3 0 65535 11246 0 0]Oh, are you busy? Come drop by if you ever feel like it.[n][w][e]

[msg MSG_036_0_0 [Keisuke Hiraga]]
[f 2 1][bup 108 0 65535 65535 0 0][vp 3 0 65535 11246 0 0]Oh... I'm sorry to hear that. Maybe next time, then.[n][w][e]

[msg MSG_037_0_0 [Keisuke Hiraga]]
[f 2 1][bup 108 0 65535 65535 0 0][vp 3 0 65535 11214 0 0]Oh, did you already have plans? I'll see you later, then.[n][w][e]

[msg MSG_038_0_0 [Keisuke Hiraga]]
[f 2 1][bup 108 3 65535 65535 0 0][vp 3 0 65535 11290 0 0]O-Oh... Then I guess today won't work out.[n][w][e]
[f 2 1][bup 108 0 65535 65535 0 0]Sorry, I was just talking to myself... You're heading home, right? Take care.[n][w][e]

[msg MSG_039_0_0 [Keisuke Hiraga]]
[f 2 1][bup 108 0 65535 65535 0 0][vp 3 0 65535 11214 0 0]Oh well, nothing we can do about that. Let's try again next time.[n][w][e]

[msg MND_GENERAL_EVENTPLAY]
[f 2 1]Message issued by the script. [n][f 1 5 0]Comm Event Replay.[n][w][e]

[msg MND_GENERAL_PERSPNA]
[f 2 1]I feel as if we can grow closer thanks to the[n][f 2 4 2] Persona, [clr 35][f 2 4 5][clr 27]...[n][w][e]

[msg MND_GENERALSELECTMSG_MAX]
[f 2 1]I feel an unbreakable bond[n]with [f 2 4 0]...[n][w][e]

[msg MND_GENERALMSG_BS_MAX]
[f 2 1]I feel an unbreakable bond[n]with the elderly couple...[n][w][e]

[msg MND_GENERALSELECTMSG_RAN]
[f 2 1]I feel like I might grow closer[n]to [f 2 4 0] soon...[n][w][e]

[msg MND_GENERALMSG_BS_RANKUP]
[f 2 1]I feel like I might grow closer[n]to the elderly couple soon...[n][w][e]

[msg MND_GENERALSELECTMSG_NOR]
[f 2 1]I don't think our bond will grow[n]any stronger even if I spend[n]more time with [f 2 4 0]...[n][w][e]

[msg MND_GENERALMSG_BS_NORMAL [Keisuke Hiraga]]
[f 2 1]I don't think our bond will grow[n]any stronger even if I spend[n]more time with them...[n][w][e]

[msg MND_GENERALSELECTMSG_MAX_2]
[f 2 1]It doesn't seem that our relationship[n]can get any closer than it is...[n][w][e]
[f 2 1]Should I still spend time with them...?[n][w][e]

[msg MND_GENERAL_MSG_SOLO_AS]
[f 2 1]Should I spend some time after[n]school with [f 2 4 0]?[n][w][e]

[msg MND_GENERAL_MSG_SOLO_DT]
[f 2 1]Should I spend the day[n]with [f 2 4 0]?[n][w][e]

[msg MND__GENERAL_MSG_NET]
[f 2 1]Should I spend time online playing[n]the MMORPG with [f 2 4 0]...?[n][w][e]

[msg MND_GENERAL_MSG_SOLO_NT]
[f 2 1]Should I spend the evening[n]with [f 2 4 0]?[n][w][e]

[sel SEL_GENERALSELECTMSG_SOL top]
[f 2 1]Spend time with [f 2 4 0][e]
[f 2 1]Check Social Link[e]
[f 2 1]Never mind[e]

[msg MND_GENERAL_MSG_MULTIPLE]
[f 2 1]Should I spend some time after[n]school with the [f 2 4 1]?[n][w][e]

[msg MND_GENERAL_MSG_FASHION_]
[f 2 1]Should I spend some time after[n]school at the fashion club?[n][w][e]

[msg MND_GENERAL_MSG_BOOKSTOR]
[f 2 1]Should I spend the day at the bookstore?[n][w][e]

[msg MND_GENERAL_MSG_BOOKSTOR_2]
[f 2 1]Should I spend some time[n]after school at the bookstore?[n][w][e]

[msg MND_GENERAL_MSG_MULTIPLE_2]
[f 2 1]Should I spend the night[n]with [f 2 4 1]?[n][w][e]

[sel SEL_GENERALSELECTMSG_MUL top]
[f 2 1]Spend time w/ [f 2 4 1][e]
[f 2 1]Check Social Link[e]
[f 2 1]Never mind[e]

[sel SEL_GENERALSELECTMSG_FCL top]
[f 2 1]Go to the fashion club[e]
[f 2 1]Check Social Link[e]
[f 2 1]Never mind[e]

[sel SEL_GENERALSELECTMSG_BS top]
[f 2 1]Enter the bookstore[e]
[f 2 1]Check Social Link[e]
[f 2 1]Never mind[e]

[msg MSG_GENERAL_EXAMREWARD_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4029 0 0]Ah, [nl].[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]I saw your exam results. Good work.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Here, this is from the chairman.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4108 0 0]It's a reward for effectively balancing schoolwork as well as our... ahem, "extracurricular activities."[n][w][e]

[msg MND_GENERAL_EXAMREWARD_0]
[f 2 1]DEV: UNUSED LABEL[n][w][e]

[msg MND_GENERAL_EXAMREWARD_0_2]
[f 2 1]Since I placed at the top in the exams,[n]I also got this [f 4 4 1 37 1 3].[n][w][e]

[msg MSG_GENERAL_EXAMREWARD_0_2 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4029 0 0]Ah, [nl].[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]I saw your exam results. Good work.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Here, this is from the chairman.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4108 0 0]It's a reward for effectively balancing schoolwork as well as our... ahem, "extracurricular activities."[n][w][e]

[msg MSG_GENERAL_EXAMREWARD_0_3 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4077 0 0]Oh, right. There's something else...[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]I saw your exam results. Good work.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Here, this is from the chairman.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4131 0 0]It's a reward for effectively balancing schoolwork as well as our... ahem, "extracurricular activities."[n][w][e]

[msg MND_GENERAL_EXAMREWARD_0_3]
[f 2 1]Since I placed at the top in the exams,[n]I also got this [f 4 4 1 37 1 3].[n][w][e]

[msg MSG_GENERAL_EXAMREWARD_0_4 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4029 0 0]Ah, [nl].[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]I saw your exam results. Good work.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Here, this is from the chairman.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4108 0 0]It's a reward for effectively balancing schoolwork as well as our... ahem, "extracurricular activities."[n][w][e]

[msg MND_GENERAL_EXAMREWARD_0_4]
[f 2 1]DEV: UNUSED LABEL[n][w][e]

[msg MSG_GENERAL_EXAMREWARD_0_5 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4029 0 0]Ah, [nl].[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]I saw your exam results... Good work.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]It's admirable how you continue to excel in school while fighting arduous battle after battle.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0]I got you a gift to acknowledge all your hard work. Here, take it.[n][w][e]

[msg MND_GENERAL_EXAMREWARD_0_5]
[f 2 1]未使用ラベルです。[n][w][e]

[msg MSG_GENERAL_EXAMREWARD_0_6 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 6 65535 0 0][vp 3 0 65535 4029 0 0]Ah, [nl].[n][w][e]
[f 2 1][bup 5 0 6 65535 0 0]I saw your exam results. Good work.[n][w][e]
[f 2 1][bup 5 0 6 65535 0 0]It's admirable how you continue to excel in school while fighting arduous battle after battle.[n][w][e]
[f 2 1][bup 5 0 6 65535 0 0]I got you a gift to acknowledge all your hard work. Here, take it.[n][w][e]

[msg MND_GENERAL_EXAMREWARD_1]
[f 2 1]Since I placed at the top in the exams,[n]I also got this [f 4 4 1 37 1 3].[n][w][e]

[msg MSG_GENERAL_EXAMREWARD_1 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4029 0 0]Ah, [nl].[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]I saw your exam results. Good work.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]It's admirable how you continue to excel in school while fighting arduous battle after battle.[n][w][e]
[f 2 1][bup 5 1 65535 65535 0 0][vp 3 0 65535 4108 0 0]I got you a gift to acknowledge all your hard work. Here, take it.[n][w][e]

[msg MND_GENERAL_EXAMREWARD_1_2]
[f 2 1]DEV: UNUSED LABEL[n][w][e]

[msg MND_GENERAL_EXAMREWARD_1_3]
[f 2 1]Since I placed at the top in the exams,[n]I also got this [f 4 4 1 37 1 3].[n][w][e]

