[msg MSG_000_0_0 [Ms. Toriumi]]
[f 2 1][bup 1581 0 65535 65535 0 0][vp 1 0 0 1 0 0][f 5 21 0 1581][nl]-san, I have a favor to ask of you.[n][w][e]
[f 2 1][bup 1581 0 65535 65535 0 0][vp 1 0 0 2 0 0][f 5 21 0 1581]It's about our track and field team. They don't have enough members, unfortunately.[n][w][e]
[f 2 1][bup 1581 3 65535 65535 0 0][vp 1 0 0 3 0 0][f 5 21 0 1581]The coach came crying to me about how they can't carry on like this![n][w][e]

[msg MSG_001_0_0 [Ms. Toriumi]]
[f 2 1][bup 1581 3 65535 65535 0 0][vp 1 0 0 4 0 0][f 5 21 0 1581]Please! Do your teacher a favor, would you?[n][w][e]

[msg MND_002_0_0]
[f 2 1]Ms. Toriumi looks pretty desperate...[n][w][e]
[f 2 1]I get the feeling she won't[n]let me leave unless I say yes.[n][w][e]

[sel SEL_003_0_0 top]
[f 2 1]Okay, I'll join the track team.[e]
[f 2 1]I really don't want to...[e]

[msg MSG_004_0_0 [Ms. Toriumi]]
[f 2 1][bup 1581 4 65535 65535 0 0][vp 1 0 0 5 0 0][f 5 21 0 1581]Really!? You'll do it!?[n][w][e]
[f 2 1][bup 1581 1 65535 65535 0 0][vp 1 0 0 6 0 0][f 5 21 0 1581][f 4 21 1581 7]Thank you! Yes! Just scored me a free lunch![n][w][e]
[f 2 1][bup 1581 0 65535 65535 0 0][vp 1 0 0 7 0 0][f 5 21 0 1581][f 4 21 1581 11]Ah, forget that last part.[n][w][e]
[f 2 1][bup 1581 1 65535 65535 0 0][vp 1 0 0 8 0 0][f 5 21 0 1581]Okay then, don't forget to turn in your membership application after school![n][w][e]

[msg MSG_005_0_0 [Ms. Toriumi]]
[f 2 1][bup 1581 2 65535 65535 0 0][vp 1 0 0 9 0 0][f 5 21 0 1581]Sorry, can't hear you.[n][w][e]

[msg MND_006_0_0]
[f 2 1]I ended up joining the[n]track and field team.[n][w][e]
[f 2 1]Looks like I have no choice, so I'll[n]go to the field after school today.[n][w][e]

