[msg MSG_004_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5061 0 0]Um... Did you need something?[n][w][e]

[msg MND_000_5_0]
[f 2 1]Come to think of it, Elizabeth asked[n]me to get a specific item for her...[n][w][e]

[msg MSG_000_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 4 65535 65535 0 0][vp 3 0 65535 5098 0 0]Huh...? A Christmas star?[n][w][e]
[f 2 1][bup 6 4 65535 65535 0 0]That's... the ornament at the top of the tree, right?[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0]Why do you need one of those...?[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5062 0 0]...Oh. If I'm right, it might not refer to an ornament at all.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]There's a type of plant that's sometimes called the "Christmas Star."[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0][vp 3 0 65535 5067 0 0]Could you wait a few minutes? I'll go double-check.[n][w][e]

[msg MSG_001_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 3 0 65535 5053 0 0]Sorry for the wait! Here you go.[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0]I think what you're looking for is a poinsettia.[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0]This flower is usually sold during Christmastime, so it'd be hard to find in stores now.[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0][vp 3 0 65535 5131 0 0]Fortunately, I had some in my room. Here you go.[n][w][e]

