[msg MSG_000_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 3 0 65535 1061 0 0]Hey. So, I'm here, but, uh...[n][w][e]

[msg MSG_001_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0]Isn't this the place that claims to "cleanse your soul" with healing stones or whatever?[n][w][e]

[msg MSG_002_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 3 0 65535 1062 0 0]Hmm... Sounds kinda sketchy to me, but... if you say it's okay, I guess I'll give it a shot.[n][w][e]

[msg MSG_003_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 3 0 65535 1068 0 0]Are you a fan of this place, [nl]-chan?[n][w][e]

[msg MSG_004_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0]I have to admit, it's not bad. I always feel refreshed after coming here.[n][w][e]

[msg MSG_005_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 3 0 65535 1114 0 0]Wow... I actually slept pretty well there...[n][w][e]

[msg MSG_006_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0]You know what? I wouldn't mind coming back once in a while. I actually feel pretty good![n][w][e]

[msg MSG_007_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 3 0 65535 1101 0 0]Well, while I'm here, I'm gonna do some shopping. I'll see you later, 'kay?[n][w][e]

[msg MSG_008_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 3 0 65535 1114 0 0]I had a nice nap this time too.[n][w][e]

[msg MSG_009_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0]My mind feels clearer now, even! And I think I'll stop by somewhere again before heading back...[n][w][e]

[msg MSG_010_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 3 0 65535 1101 0 0]Well, see you later![n][w][e]

[msg MND_011_0_0]
[f 2 1]It's almost nighttime... I should[n]head back to the dorm.[n][w][e]

[msg MND_012_0_0]
[f 2 1]It's getting late... I should[n]head back to the dorm.[n][w][e]

