[msg MSG_000_0_0 [Track Team Advisor]]
[f 2 1][vp 1 0 0 1 0 0][f 5 21 0 1093]...So, starting today, she's an official member of the team.[n][w][e]

[sel SEL_001_0_0 top]
[f 2 1]I'm [f 4 3].[e]
[f 2 1]Nice to meet you.[e]

[msg MSG_002_0_0 [Female Student in a Jersey]]
[f 2 1][bup 106 0 101 65535 0 0][vp 1 0 0 2 0 0]Welcome aboard, [nl]-chan. I'm Yuko Nishiwaki.[n][w][e]

[msg MSG_003_0_0 [Track Team Advisor]]
[f 2 1][vp 1 0 0 3 0 0][f 5 21 0 1093]She's our team manager. She'll answer any of your questions.[n][w][e]

[msg MSG_004_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 101 65535 0 0][vp 1 0 0 4 0 0]You're a second-year, right? Since we're in the same grade, you can just call me "Yuko."[n][w][e]

[msg MSG_005_0_0 [Track Team Advisor]]
[f 2 1][vp 1 0 0 5 0 0][f 5 21 0 1093]Let's see... Hey! Miyamoto![n][w][e]

[msg MSG_006_0_0 [Miyamoto]]
[f 2 1][bup 105 0 151 65535 0 0][vp 1 0 0 6 0 0]Yes![n][w][e]

[msg MSG_007_0_0 [Track Team Advisor]]
[f 2 1][vp 1 0 0 7 0 0][f 5 21 0 1093]This here's our future team captain. He's a great runner and places well in competitions.[n][w][e]
[f 2 1][vp 1 0 0 8 0 0][f 5 21 0 1093]You two are in the same class, right? Miyamoto, keep an eye on the new girl here, okay?[n][w][e]

[msg MSG_008_0_0 [Miyamoto]]
[f 2 1][bup 105 0 151 65535 0 0][vp 1 0 0 9 0 0]You got it.[n][w][e]

[msg MSG_009_0_0 [Miyamoto]]
[f 2 1][bup 105 0 151 65535 0 0][vp 1 0 0 10 0 0]You're the girl who went out with Takeba on the first day of school, right? You're practically a celebrity.[n][w][e]
[f 2 1][bup 105 0 151 65535 0 0][vp 1 0 0 11 0 0]I'm Kazushi Miyamoto. You've seen me around, right?[n][w][e]

[sel SEL_010_0_0 top]
[f 2 1]Yeah.[e]
[f 2 1]Nope.[e]

[msg MSG_011_0_0 [Kazushi Miyamoto]]
[f 2 1][bup 105 1 151 65535 0 0][vp 1 0 0 12 0 0]Then long story short, from now on, you're mine after school.[n][w][e]

[msg MSG_012_0_0 [Kazushi Miyamoto]]
[f 2 1][bup 105 3 151 65535 0 0][vp 1 0 0 13 0 0]Ouch, man... Kinda hurts my pride. Everyone knows who I am.[n][w][e]

[msg MSG_013_0_0 [Kazushi Miyamoto]]
[f 2 1][bup 105 0 151 65535 0 0][vp 1 0 0 14 0 0]You better not think you're getting the easy treatment just 'cause you joined mid-season![n][w][e]

[msg MND_014_0_0]
[f 2 1]Miyamoto's given me a warm welcome...[n][w][e]
[f 2 1]I joined the track team and made[n]friends with my new teammates.[n][w][e]

[msg MSG_015_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 101 65535 0 0][vp 1 0 0 15 0 0]Since this is your first practice, just have a look around and then call it a day.[n][w][e]
[f 2 1][bup 106 0 101 65535 0 0][vp 1 0 0 16 0 0]We have practice on [clr 2]Mondays, Tuesdays, Thursdays, and Fridays[clr 27]. There's no practice the days before tests, though.[n][w][e]
[f 2 1][bup 106 0 101 65535 0 0][vp 1 0 0 17 0 0]I'll make sure your uniform is ready for next time.[n][w][e]

[msg MND_016_0_0]
[f 2 1]After looking around, I decided[n]to go back to the dorm.[n][w][e]

