[msg MSG_000_0_0 [Suspicious Man]]
[f 2 1][vp 3 0 65535 20603 0 0][f 5 21 1 105]Hmmm... This is certainly a fascinating forum...[n][w][e]
[f 2 1][f 5 21 1 105]Hm? Are you interested in the dark web too...?[n][w][e]
[f 2 1][f 5 21 1 105]I collect information from various people about "interesting" sites and forums...[n][w][e]
[f 2 1][f 5 21 1 105]If you want, I can sell you some info... Top secret stuff, even...[n][w][e]

[msg MSG_001_0_0 [Suspicious Man]]
[f 2 1][vp 3 0 65535 20602 0 0][f 5 21 1 105]Heh, you're a curious one, aren't you...? Well, go on and take a look.[n][w][e]

[msg MSG_002_0_0 [Suspicious Man]]
[f 2 1][vp 3 0 65535 20604 0 0][f 5 21 1 105]Thanks... I'll be on the search for more exquisite info...[n][w][e]

[msg MSG_003_0_0 [Suspicious Man]]
[f 2 1][vp 3 0 65535 20606 0 0][f 5 21 1 105]Come again...[n][w][e]

[msg MSG_004_0_0 [Suspicious Man]]
[f 2 1][vp 3 0 65535 20605 0 0][f 5 21 1 105]Sorry, I'm a little busy tonight... Come back some other time, won't ya?[n][w][e]

[msg MSG_005_0_0 [Suspicious Man]]
[f 2 1]Hm? What do you want?[n][w][e]
[f 2 1]You got guts, comin' to a place like this on your own...[n][w][e]
[f 2 1]Well, I'd be happy to sell you some info on... "unconventional" websites, but...[n][w][e]
[f 2 1]Do you have your own computer? You'll need one to make use of my services...[n][w][e]

[msg MND_006_0_0]
[f 2 1]Looks like I can get information[n]on unusual websites here...[n][w][e]
[f 2 1][clr 2]If I can use a computer at the dorm[clr 27], I might[n]be able to look into these websites...[n][w][e]

