[msg MSG_000_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 1 65535 0 0][vp 1 0 0 1 0 0]We'd been keeping the rooftop off-limits, but recently decided to open it up.[n][w][e]
[f 2 1][bup 5 0 1 65535 0 0][vp 1 0 0 2 0 0]The chairman wanted to start a small garden here.[n][w][e]

[msg MSG_001_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 1 65535 0 0][vp 1 0 0 3 0 0]Wow... I had no idea there was something like this up here. Is it for growing vegetables?[n][w][e]
[f 2 1][bup 2 6 1 65535 0 0][vp 1 0 0 4 0 0][f 4 23 0 2 10 25 25]Oh boy, I can hear him now... "Eat your veggies, peas!"[n][w][e]

[msg MSG_001_5_0 [Junpei Iori]]
[f 2 1][bup 3 6 1 65535 0 0][vp 1 0 0 5 0 0]Thaaat sounds about right... With a terrible smirk plastered on his face.[n][w][e]

[msg MSG_002_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 1 65535 0 0][vp 1 0 0 6 0 0]I hear you're the one taking care of it, [nl].[n][w][e]
[f 2 1][bup 5 1 1 65535 0 0][vp 1 0 0 7 0 0][f 4 23 0 5 1 25 25]Looks like it's shaping up quite nicely. The chairman was right to put you in charge.[n][w][e]

[msg MSG_003_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 1 65535 0 0][vp 1 0 0 8 0 0]I've been told it was left in your care, [nl].[n][w][e]
[f 2 1][bup 5 0 1 65535 0 0][vp 1 0 0 9 0 0]I know it sounds like a lot of work, but it might be nice to try growing a thing or two.[n][w][e]

[msg MSG_004_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 1 65535 0 0][vp 1 0 0 10 0 0]Uh, are you okay doin' this all on your own?[n][w][e]

[sel SEL_004_5_0 top]
[f 2 1]It's no problem.[e]
[f 2 1]I could use some help.[e]
[f 2 1]You're in charge now.[e]

[msg MSG_005_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 1 65535 0 0][vp 1 0 0 11 0 0]Oh yeah? You like this kinda stuff? Gotta admit, looks kinda fun.[n][w][e]
[f 2 1][bup 3 1 1 65535 0 0][vp 1 0 0 12 0 0]Maybe we'll be rakin' in the harvest after a while. When that time comes... "lettuce" celebrate![n][w][e]

[msg MSG_006_0_0 [Yukari Takeba]]
[f 2 1][bup 2 6 1 65535 0 0][vp 1 0 0 13 0 0]...Why don't you use that energy to help her with the garden?[n][w][e]

[msg MSG_007_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 1 65535 0 0][vp 1 0 0 14 0 0]Why don't you help her out, Junpei? It's not like you've got anything better to do.[n][w][e]

[msg MSG_008_0_0 [Junpei Iori]]
[f 2 1][bup 3 6 1 65535 0 0][vp 1 0 0 15 0 0]Yeah, definitely saw that one coming... But I guess it does look kinda fun.[n][w][e]
[f 2 1][bup 3 1 1 65535 0 0][vp 1 0 0 16 0 0][f 4 23 0 3 1 25 25]Maybe all the vitamins from the veggies will make my skin all silky smooth.[n][w][e]

[msg MSG_009_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 6 1 65535 0 0][vp 1 0 0 17 0 0]Hehe... That would be a sight to see.[n][w][e]

[msg MSG_010_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 1 65535 0 0][vp 1 0 0 18 0 0]What, me!? No no, bad idea.[n][w][e]
[f 2 1][bup 3 3 1 65535 0 0][vp 1 0 0 19 0 0][f 4 23 0 3 3 25 25]I tried to grow morning glories for a project in elementary school... Not a single one lived.[n][w][e]
[f 2 1][bup 3 0 1 65535 0 0][vp 1 0 0 20 0 0][f 4 23 0 3 0 25 25]But hey, maybe this is my chance to give it another shot. I can help out from time to time, I guess...[n][w][e]

[msg MSG_011_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 1 65535 0 0][vp 1 0 0 21 0 0]The more time and care you put into this kind of work, the better the results.[n][w][e]
[f 2 1][bup 5 1 1 65535 0 0][vp 1 0 0 22 0 0]Cooperating with someone on this may be worth your time.[n][w][e]

[msg MSG_012_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 1 65535 0 0][vp 1 0 0 23 0 0]I might be a bit interested as well...[n][w][e]

[msg MND_013_0_0]
[f 2 1]Having someone help me with the[n]garden might affect the end result...[n][w][e]

[msg MSG_014_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 1 65535 0 0][vp 1 0 0 24 0 0]That wraps up this area. Let's head back down.[n][w][e]

