[msg MSG_000_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 3 0 65535 1107 0 0]Wow, so sieht es also hier aus.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0]Ich habe mich hier noch nie richtig umgesehen. Hier gibt es ja wirklich alles, was?[n][uf 1 1][e]

[msg MSG_001_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0]Ist das ein Zeitungsausschnitt?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 3 0 65535 1105 0 0]"Läutere deine Seele."[n]"Reinigt euch mit Zaubersteinen!"[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0]Wow, das ist eine lustige Werbung für sich selbst.[n][uf 1 1][e]

[msg MSG_002_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0]Oh, schau mal, da hat jemand was an die Wand gekritzelt.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 4 23 0 2 0 25 25]Mal sehen ...[n]"Wähle deine Lieblingsfarbe."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]"Sie zeigt deinen Gemütszustand."[n]Hm ...[n][uf 1 1][e]

[msg MSG_003_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 3 0 65535 1001 0 0]Was sind deine Lieblingsfarbe,[uf 4 1]-chan?[n][uf 1 1][e]

[sel SEL_004_0_0 top]
[uf 0 5 65278][uf 2 1]Blau.[e]
[uf 0 5 65278][uf 2 1]Schwarz.[e]
[uf 0 5 65278][uf 2 1]Grün.[e]

[msg MSG_005_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 3 0 65535 1095 0 0][uf 5 13 7 15 2]Hab ich mir gedacht. Ja, passt zu dir.[n][uf 1 1][e]

[msg MSG_005_5_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1061 0 0]Mal sehen ...[n]"Leute, die Blau wählten ..."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]"... sind heilig. Sie erfreuen sich am Ende aller Tage."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 4 23 0 2 1 25 25]Das ist ... interessant, aber nicht so glaubwürdig ...[n][uf 1 1][e]

[msg MND_006_0_0]
[uf 0 5 65278][uf 2 1]Yukari scheint Spaß zu haben.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Ich habe heute etwas Neues über sie erfahren ...[n][uf 1 1][e]

[msg MSG_007_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 65535 65535 0 0][uf 3 1 3 0 65535 1062 0 0]Wow, welch eine schlichte Wahl. Tja, das ist wohl typisch für dich.[n][uf 1 1][e]

[msg MSG_007_5_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1061 0 0]Mal sehen ...[n]"Leute, die Schwarz wählten ..."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]"... akzeptieren die Wahrheit. Sie haben das Glück, die Erleuchtung zu erlangen."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0][uf 4 23 0 2 3 25 25]Das ist ... interessant, aber nicht so glaubwürdig ...[n][uf 1 1][e]

[msg MND_008_0_0]
[uf 0 5 65278][uf 2 1]Yukari grübelt ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Ich habe das Gefühl, wir sind uns heute kein Stück nähergekommen ...[n][uf 1 1][e]

[msg MSG_009_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 3 0 65535 1132 0 0][uf 5 13 7 30 2]Oh, ich liebe diese Farbe auch. Ob es stimmt, dass sie gut für die Augen ist?[n][uf 1 1][e]

[msg MSG_009_5_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1061 0 0]Mal sehen ...[n]"Leute, die Grün wählten ..."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]"... dienen anderen mit ihren Flügeln.[n]Sie werden ernten."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 4 23 0 2 1 25 25]Das ist ... interessant, aber nicht so glaubwürdig ...[n][uf 1 1][e]

[msg MND_010_0_0]
[uf 0 5 65278][uf 2 1]Yukari und ich sehen uns an und zucken mit den Schultern ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Ich habe das Gefühl, wir sind uns heute sehr viel näher gekommen.[n][uf 1 1][e]

[msg MSG_011_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]Ich weiß nicht viel über spirituelle Dinge, aber ich verstehe, wieso das beruhigend sein kann.[n][uf 1 1][e]

[msg MSG_031_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 3 0 65535 1067 0 0]Oh, sie mal, das hier ist so niedlich! Aber der Preis eher nicht.[n][uf 1 1][e]

[msg MND_012_0_0]
[uf 0 5 65278][uf 2 1]Nachdem wir durch den Laden gestöbert hatten, gingen wir zurück zum Wohnheim.[n][uf 1 1][e]

