[msg MND_000_0_0]
[uf 0 5 65278][uf 2 1]It's Yuko, the team manager.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Should I say hello?[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]I think I will.[e]
[uf 0 5 65278][uf 2 1]Maybe not.[e]

[msg MND_002_0_0]
[uf 0 5 65278][uf 2 1]I left without Yuko noticing...[n][uf 1 1][e]

[msg MSG_003_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]Oh, [uf 4 1]-chan. What's up...?[n][uf 1 1][e]

[sel SEL_004_0_0 top]
[uf 0 5 65278][uf 2 1]Wanna walk home together?[e]
[uf 0 5 65278][uf 2 1]Nothing, see you tomorrow.[e]

[msg MSG_005_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 0 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]Actually, no. I'm in a hurry today.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 3 0 0][uf 4 23 0 106 1 25 25]See ya![n][uf 1 1][e]

[msg MND_006_0_0]
[uf 0 5 65278][uf 2 1]Yuko went home alone...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I decided to go back to the dorm by myself.[n][uf 1 1][e]

[msg MSG_007_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]Yeah, see ya![n][uf 1 1][e]

