[msg MSG_SENDER_NAME]
[uf 0 5 65278][uf 2 1]IS Online[n][uf 1 1][e]

[msg MSG_001_0_0]
[uf 0 5 65278][uf 2 1]Nuevo mensaje de Maya[n][uf 1 1][e]

[msg MSG_002_0_0]
[uf 0 5 65278][uf 2 1]ulalaaa! ^_^ te ape pasarlo bien hoy? vamos a jugar ☆[n][uf 1 1][e]

[msg MSG_003_0_0]
[uf 0 5 65278][uf 2 1]Nuevo mensaje de Maya[n][uf 1 1][e]

[msg MSG_004_0_0]
[uf 0 5 65278][uf 2 1]x fin he trminado el curro =w=[n]tu tb, la-la! deshazte d tus tareas de la vida reaal XD conéctate y juega conmigooo ^^[n][uf 1 1][e]

[msg MSG_005_0_0]
[uf 0 5 65278][uf 2 1]Nuevo mensaje de Maya[n][uf 1 1][e]

[msg MSG_006_0_0]
[uf 0 5 65278][uf 2 1]ULALAAAAAA!!!!!! tas en linea? HOY SE JUEGA!!!!!!!!!![n][uf 1 1][e]

[msg MSG_007_0_0]
[uf 0 5 65278][uf 2 1]Nuevo mensaje de Maya[n][uf 1 1][e]

[msg MSG_008_0_0]
[uf 0 5 65278][uf 2 1]VENGA LA-LA! (/ *-*)/ VAMOSSSSS! LA-LA!!! \(*-* \)[n][uf 1 1][e]

[msg MSG_009_0_0]
[uf 0 5 65278][uf 2 1]Nuevo mensaje de Maya[n][uf 1 1][e]

[msg MSG_010_0_0]
[uf 0 5 65278][uf 2 1]la-la, m recibes?? rsponde, tu compinxe te llama!!!1!! *_^ t espero en la mazmorra SNGW!!!![n][uf 1 1][e]

[msg MSG_011_0_0]
[uf 0 5 65278][uf 2 1]Nuevo mensaje de Maya[n][uf 1 1][e]

[msg MSG_012_0_0]
[uf 0 5 65278][uf 2 1](＞ '-')＞ T[n]＜( '-' )＞ A[n]＜('-' ＜) T[n]＜( '-' )＞ S[n](＞ '-')＞ U[n]＜( '-' )＞ Y[n]＜('-' ＜) A[n]＜( '-' )＞ A[n](＞ '-')＞ A[n]\( '-' )/ !!![n][uf 1 1][e]

[msg MSG_013_0_0]
[uf 0 5 65278][uf 2 1]Nuevo mensaje de Maya[n][uf 1 1][e]

[msg MSG_014_0_0]
[uf 0 5 65278][uf 2 1]hace un dia soleado magnifico! :)[n]aunq m voy a qdar en casa, no[n]pasa nada pq t tngo a ti y no t[n]imprta si stoy guapa o no[n]+ t vale q t conectes!!! =_=[n][uf 1 1][e]

[msg MSG_015_0_0]
[uf 0 5 65278][uf 2 1]Nuevo mensaje de Maya[n][uf 1 1][e]

[msg MSG_016_0_0]
[uf 0 5 65278][uf 2 1]holi coleguii :3c[n]jeje es hora de cazar monstruos!!![n][uf 1 1][e]

[msg MSG_017_0_0]
[uf 0 5 65278][uf 2 1]Nuevo mensaje de Maya[n][uf 1 1][e]

[msg MSG_018_0_0]
[uf 0 5 65278][uf 2 1]ste juego sta muerto xro voy a seguir jugando!!! X3[n]la-laaaaa!!![n]t exo de menos u.u[n][uf 1 1][e]

[msg MSG_019_0_0]
[uf 0 5 65278][uf 2 1]Nuevo mensaje de Maya[n][uf 1 1][e]

[msg MSG_020_0_0]
[uf 0 5 65278][uf 2 1]voy a conectarme yaa ^_^[n][uf 1 1][e]

[msg MSG_021_0_0]
[uf 0 5 65278][uf 2 1]Nuevo mensaje de Maya[n][uf 1 1][e]

[msg MSG_022_0_0]
[uf 0 5 65278][uf 2 1]te vienes a reventar demonios?? XD[n][uf 1 1][e]

[msg MSG_023_0_0]
[uf 0 5 65278][uf 2 1]Nuevo mensaje de Maya[n][uf 1 1][e]

[msg MSG_024_0_0]
[uf 0 5 65278][uf 2 1]eyyyyy conectate y jugamoos :D[n][uf 1 1][e]

