[msg MSG_000_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 4 101 65535 0 0][uf 3 1 1 0 0 1 0 0]¡Eh, [uf 4 1]! ¿A qué viene tanta prisa?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0][uf 3 1 1 0 0 2 0 0][uf 4 23 0 1 3 25 25]Yuko estaba cabreada, ¿verdad? Me estoy saltando muchos entrenamientos.[n][uf 1 1][e]

[msg MSG_001_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0][uf 3 1 1 0 0 3 0 0]Te tendría que haber contado antes lo de la radiografía.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0][uf 3 1 1 0 0 4 0 0]Tengo inflamados los músculos y los tendones de la rodilla.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0][uf 3 1 1 0 0 5 0 0]El médico me ha dicho que, si sigo así, no podré volver a caminar.[n][uf 1 1][e]

[msg MSG_001_5_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 1 0 0 6 0 0]Se ve que me los he jodido de tanto entrenar. Seré idiota.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0][uf 3 1 1 0 0 7 0 0][uf 4 23 0 1 3 25 25]Quiero ganar, así que no me queda otra.[n][uf 1 1][e]

[sel SEL_002_0_0 top]
[uf 0 5 65278][uf 2 1]Tampoco puedes hacer nada.[e]
[uf 0 5 65278][uf 2 1]Demuestra que tienes agallas.[e]

[msg MSG_003_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 2 101 65535 0 0][uf 3 1 1 0 0 8 0 0]¡No es excusa![n][uf 1 1][e]

[msg MSG_004_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 1 0 0 9 0 0][uf 5 13 8 5 105]S-sí, es verdad.[n][uf 1 1][e]

[msg MSG_005_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 2 101 65535 0 0][uf 3 1 1 0 0 10 0 0]Cada minuto y segundo cuentan. ¡No puedo perder más tiempo![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 2 101 65535 0 0][uf 3 1 1 0 0 11 0 0]Prometí ganar en la competición del año que viene y ser el mejor atleta de todo Japón.[n][uf 1 1][e]

[sel SEL_006_0_0 top]
[uf 0 5 65278][uf 2 1]¿En serio?[e]
[uf 0 5 65278][uf 2 1]¿Por qué te excedes tanto?[e]

[msg MSG_007_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0][uf 3 1 1 0 0 12 0 0]Sí... Lo prometí.[n][uf 1 1][e]

[msg MSG_008_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0][uf 3 1 1 0 0 13 0 0][uf 5 13 8 5 105]Bueno, no lo hago solo por mí.[n][uf 1 1][e]

[msg MSG_009_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 1 0 0 14 0 0]Mi sobrino sufrió un accidente y se hizo polvo las piernas.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 1 0 0 15 0 0]Ahora no puede andar.[n][uf 1 1][e]

[msg MSG_009_3_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 1 0 0 16 0 0]Pero, con rehabilitación, puede que se recupere.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 1 0 0 17 0 0]Aunque dice que le duele mucho y que no quiere ir...[n][uf 1 1][e]

[msg MSG_009_5_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 1 0 0 18 0 0]Solo tiene cinco añitos. Le queda toda la vida por delante.[n][uf 1 1][e]

[msg MSG_010_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 1 0 0 19 0 0]Por eso hice un trato con él. A ver... No te rías, ¿vale?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 1 0 0 20 0 0]Le dije que, si llegaba a ser el mejor de Japón, él tendría que ir a rehabilitación.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 1 0 0 21 0 0]Tengo que ganar este encuentro para poder ir al torneo nacional.[n][uf 1 1][e]

[sel SEL_011_0_0 top]
[uf 0 5 65278][uf 2 1]¿Crees que ganarás?[e]
[uf 0 5 65278][uf 2 1]¿Y qué pasa con tu rodilla?[e]

[msg MSG_012_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0][uf 3 1 1 0 0 22 0 0]Si te soy sincero, dudo que lo consiga.[n][uf 1 1][e]

[msg MSG_013_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0][uf 3 1 1 0 0 23 0 0][uf 5 13 8 5 105]Te lo agradezco, pero... ahora mismo esa es la última de mis preocupaciones.[n][uf 1 1][e]

[msg MSG_014_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0][uf 3 1 1 0 0 24 0 0]Perdona por todas las movidas en las que te he metido. Y por las charlas tan deprimentes.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 3 101 65535 0 0][uf 3 1 1 0 0 25 0 0]Es duro guardárselo todo dentro. Eres la única con la que puedo hablar.[n][uf 1 1][e]

[msg MND_015_0_0]
[uf 0 5 65278][uf 2 1]Kazushi me ha hablado de sus problemas.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Tengo la sensación de que estamos estrechando lazos.[n][uf 1 1][e]

[msg MSG_016_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 1 0 0 26 0 0]Yuko es de las que se coscan de todo enseguida, así que a lo mejor te dice algo.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 0 101 65535 0 0][uf 3 1 1 0 0 27 0 0]Si te pregunta algo, dile que venga a hablar conmigo. Bastante has hecho tú ya.[n][uf 1 1][e]

[msg MND_017_0_0]
[uf 0 5 65278][uf 2 1]Me he despedido de Kazushi y he vuelto a la residencia.[n][uf 1 1][e]

