[msg MSG_000_0_0 [Imágenes de la cámara]]
[uf 0 5 65278][uf 2 1]...> ...>[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]"20/09/2009 01:13:41[n]Iniciando reproducción...".[n][uf 1 1][e]

[msg MND_001_0_0 [Mensaje interno]]
[uf 0 5 65278][uf 2 1]¡¿...?![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]¡Es mi habitación![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Me veo durmiendo en la cama.[n][uf 1 1][e]

[msg MSG_002_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 40 0 0][uf 3 1 1 0 0 1 0 0]Puerta abierta en 92 segundos. He mejorado mi récord.[n][uf 1 1][e]

[msg MSG_003_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 40 0 0][uf 3 1 0 0 0 2 0 0]...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 40 0 0][uf 3 1 1 0 0 3 0 0]La temperatura de la superficie corporal es de 36,2 grados, sin fiebre...[n][uf 1 1][e]

[msg MSG_004_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 40 0 0][uf 3 1 1 0 0 4 0 0]A este paso, estará plenamente recuperada por la mañana.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 40 0 0][uf 3 1 1 0 0 5 0 0]No hará falta la almohada que había metido en el congelador.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 40 0 0][uf 3 1 0 0 0 6 0 0]...[n][uf 1 1][e]

[msg MSG_005_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 40 0 0][uf 3 1 1 0 0 7 0 0]No puedo quedarme mucho rato, que Yukari me echará la bronca otra vez.[n][uf 1 1][e]

[msg MSG_006_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 40 0 0][uf 3 1 0 0 0 8 0 0]...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 40 0 0][uf 3 1 1 0 0 9 0 0]Aún faltan cuatro horas y doce minutos para que amarezca.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 40 0 0][uf 3 1 0 0 0 10 0 0]...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 40 0 0][uf 3 1 1 0 0 11 0 0]Mientras salga antes de que amanezca, no me pasará nada.[n][uf 1 1][e]

[msg MSG_007_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 202 40 0 0][uf 3 1 1 0 0 12 0 0]Me quedaré a vigilarla solo un poco más...[n][uf 1 1][e]

[msg MND_008_0_0 [Mensaje interno]]
[uf 0 5 65278][uf 2 1]Aquí acaba la grabación.[n][uf 1 1][e]

