[msg MSG_000_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 1 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]Menudo saque tienes. ¡Si me has seguido el ritmo y todo! ¡Burp![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 1 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]¿Cómo te mantienes tan delgada? Las apariencias engañan, ¿eh?[n][uf 1 1][e]

[msg MSG_001_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 3 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]¡Pero eso significa que hay gente por ahí que secretamente quiere arrebatarme mi título de Rey gourmet! Bueno, quizá.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 3 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]De hecho, ¿te acuerdas de ese tío de mediana edad del otro día? ¡Fijo que era un asesino! Puede ser.[n][uf 1 1][e]

[msg MSG_001_3_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]Ahora mismo no hay nada que pueda hacer al respecto, ¡pero se van a enterar! Ya verás.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]En vista de tus recientes logros y tu valiente apetito, ¡te nombro miembro de la guardia real del Rey gourmet![n][uf 1 1][e]

[msg MSG_001_5_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]No, tal vez sea una carga demasiado pesada para ti.[n][uf 1 1][e]

[msg MND_002_0_0]
[uf 0 5 65278][uf 2 1]Parece que Suemitsu confía en mí de verdad.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Tengo la sensación de que nuestra relación se ha fortalecido.[n][uf 1 1][e]

[msg SYS_003_0_0]
[uf 0 5 65278][uf 2 1]DEV: Unused[n][uf 1 1][e]

[msg MSG_004_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 1 0 0 8 0 0]Por cierto, vas a segundo, ¿verdad, [uf 4 2]? Eres un año más joven que yo.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 1 65535 65535 0 0][uf 3 1 1 0 0 9 0 0][uf 4 23 0 116 1 25 25]Es como si tuviera una hermana pequeña.[n][uf 1 1][e]

[msg MSG_004_3_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]¿Y bien? ¿Te gustaría ser... mi hermana pequeña?[n][uf 1 1][e]

[sel SEL_005_0_0 top]
[uf 0 5 65278][uf 2 1]Claro, ¿por qué no?[e]
[uf 0 5 65278][uf 2 1]No, la verdad.[e]

[msg MSG_006_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 3 65535 65535 0 0][uf 3 1 1 0 0 11 0 0][uf 5 13 19 15 116]La verdad es que me recuerdas un poco a él... No, es imposible.[n][uf 1 1][e]

[msg MSG_007_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]Vale, como quieras. Solo me habías recordado a alguien, ¡pero me equivocaba! ¡No te pareces en nada![n][uf 1 1][e]

[msg MSG_008_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 3 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]Uf, ¡sabía que esto iba a pasar! Siempre me entra hambre si pienso demasiado en el pasado.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 3 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]Y me acabo de llenar con el bol de ternera...[n][uf 1 1][e]

[msg MSG_009_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 1 0 0 15 0 0]Será mejor seguir mi instinto y comer más, ¿no?[n][uf 1 1][e]

[msg MSG_009_3_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 1 65535 65535 0 0][uf 3 1 1 0 0 16 0 0]Por un apetito saludable, cortesía del recuerdo del pasado. ¡Rebobinando un antiguo recuerdo![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 1 65535 65535 0 0][uf 3 1 1 0 0 17 0 0]¡Vale, ahora hacia atrás! ¡A tope con el moonwalk![n][uf 1 1][e]

[msg MSG_010_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 1 0 0 18 0 0]¿Qué estás haciendo, [uf 4 2]? Eres mi leal guardián. Debes acompañarme.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 1 65535 65535 0 0][uf 3 1 1 0 0 19 0 0][uf 4 23 0 116 1 25 25]Venga, haz como yo.[n][uf 1 1][e]

[msg MSG_010_3_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 1 65535 65535 0 0][uf 3 1 1 0 0 20 0 0]¡Moonwalk hacia Umiushi![n][uf 1 1][e]

[msg MND_011_0_0]
[uf 0 5 65278][uf 2 1]He acompañado a Suemitsu[n]y me he comido otro bol de ternera.[n][uf 1 1][e]

[msg MND_012_0_0]
[uf 0 5 65278][uf 2 1]Después de comer, me he despedido de Suemitsu y he vuelto a la residencia.[n][uf 1 1][e]

