[msg MSG_000_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 0 0 0 1 0 0]...[n][uf 1 1][e]

[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]Siento que mi [uf 4 30 0 1 1 0] ha mejorado[n]gracias a la gran calidad de la escritura.[n][uf 1 1][e]

[msg MSG_002_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]Oye, [uf 4 1], ¿te has terminado ya el libro?[n][uf 1 1][e]

[msg MSG_003_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]Estabas inmersa en la lectura. A mí también me pasa.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]Cuando llegué al final, estaba tan ensimismada que se me olvidó hasta respirar.[n][uf 1 1][e]

[msg MSG_004_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]Es una saga alucinante.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]Al principio no caí, pero hay un momento en el que todo cobra sentido. Qué sensación tan rara, ¿verdad?[n][uf 1 1][e]

[sel SEL_005_0_0 top]
[uf 0 5 65278][uf 2 1]Parece magia.[e]
[uf 0 5 65278][uf 2 1]Es la magia de la escritura.[e]
[uf 0 5 65278][uf 2 1]Me he saltado las partes difíciles.[e]

[msg MSG_006_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]Sí que da esa impresión, ¿verdad?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 8 0 0]La ciencia ficción intimida, pero a veces va de la mano de la fantasía.[n][uf 1 1][e]

[msg MSG_007_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 9 0 0]Sí. Si fuesen textos meramente expositivos, menudo cansancio.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]Que el autor sea capaz de integrar la creación del mundo en la narrativa demuestra su destreza.[n][uf 1 1][e]

[msg MSG_008_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 11 0 0]Uy, yo también lo hago mucho.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 12 0 0][uf 4 23 0 6 0 25 25]A veces no se entiende bien la primera vez que lo lees, pero a medida que sigues ya empieza a cobrar sentido.[n][uf 1 1][e]

[msg MSG_009_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]Ojalá me expresase tan bien como el autor del libro.[n][uf 1 1][e]

[msg MSG_009_3_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]¿Recuerdas que te conté que le recomendé un libro a una compañera y que me dijo que no pensaba leerlo?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 15 0 0]Saber qué decir es importante, pero cómo decirlo cuesta trabajo.[n][uf 1 1][e]

[msg MSG_009_7_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 16 0 0]Quería que supiera lo fascinante que es el libro, pero le preocupaba más lo larga que era la saga y solo le interesaba si el autor era famoso.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 17 0 0]Es imposible convencer a alguien si hace semejantes preguntas.[n][uf 1 1][e]

[sel SEL_010_0_0 top]
[uf 0 5 65278][uf 2 1]A la próxima irá mejor.[e]
[uf 0 5 65278][uf 2 1]Esta es difícil.[e]

[msg MSG_011_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 18 0 0]Gracias. A lo mejor vuelvo a intentarlo.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 19 0 0]Creo que tendré muchas cosas buenas que decir de este libro cuando llegue el momento.[n][uf 1 1][e]

[msg MSG_012_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 20 0 0]Pues sí. Es muy fácil recurrir a ese tipo de datos, como el número de ejemplares vendidos o el prestigio del escritor.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 21 0 0]Pero, para hablar de lo buena que es una historia, hay que empezar por las emociones que transmite.[n][uf 1 1][e]

[msg MSG_013_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 22 0 0]Es gratificante que la gente muestre interés por las cosas que te gustan.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 23 0 0]Me encanta intercambiar opiniones.[n][uf 1 1][e]

[msg MSG_013_3_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 24 0 0]Por eso quiero aprender a expresarme mejor.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 25 0 0]A lo mejor así disfruto más.[n][uf 1 1][e]

[msg MND_013_5_0]
[uf 0 5 65278][uf 2 1]Fuuka asiente con determinación.[n][uf 1 1][e]

[msg MSG_014_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 26 0 0]Uy, mira qué hora es. Mañana seguimos.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 27 0 0]Eh...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 28 0 0]Te puedo recomendar más libros, si te apetece.[n][uf 1 1][e]

[msg MSG_015_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 29 0 0][uf 5 13 3 1 6]Gracias, [uf 4 1]. Espero que te gusten.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 30 0 0]Vale, pues buenas noches.[n][uf 1 1][e]

