[msg MSG_000_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4107 0 0]Good job. You did well handling a strong opponent.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]I'm feeling confident in your ability to lead. How do you feel?[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]Perfect.[e]
[uf 0 5 65278][uf 2 1]I'm not sure...[e]
[uf 0 5 65278][uf 2 1]I'm feeling okay.[e]

[msg MSG_002_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 50 0 0][uf 3 1 3 0 65535 4131 0 0]Well, you're sounding quite confident yourself. Keep it up.[n][uf 1 1][e]

[msg MSG_003_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 50 0 0][uf 3 1 3 0 65535 4131 0 0]Don't worry, you're doing just fine. All you need is more experience.[n][uf 1 1][e]

[msg MSG_004_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 50 0 0][uf 3 1 3 0 65535 4131 0 0]Well, I can see your potential. I'm looking forward to seeing what you can do.[n][uf 1 1][e]

[msg MSG_005_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]All right, time to resume exploration. Let me know if you need something.[n][uf 1 1][e]

[msg MSG_006_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4108 0 0]Great work. The path ahead is now accessible.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]We can stop here for the day, if you want. What do you think?[n][uf 1 1][e]

[sel SEL_007_0_0 top]
[uf 0 5 65278][uf 2 1]Let's go home, then.[e]
[uf 0 5 65278][uf 2 1]Let's keep going.[e]
[uf 0 5 65278][uf 2 1]Why don't you decide?[e]

[msg MSG_008_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4113 0 0]All right. You can use the teleporter nearby to return to the entrance.[n][uf 1 1][e]

[msg MSG_009_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4113 0 0]Roger that. Then I'll continue providing support as you go on.[n][uf 1 1][e]

[msg MSG_010_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 50 0 0][uf 3 1 3 0 65535 4094 0 0]As the leader, it's your decision what to do in the field.[n][uf 1 1][e]

[msg MSG_011_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]I'll leave it to you.[n][uf 1 1][e]

[msg MSG_012_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4107 0 0]A battle well fought.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]Do you want to continue the exploration today? How do you feel?[n][uf 1 1][e]

[sel SEL_013_0_0 top]
[uf 0 5 65278][uf 2 1]I think we can keep going.[e]
[uf 0 5 65278][uf 2 1]Let's head back for today.[e]
[uf 0 5 65278][uf 2 1]I guess if you want to...[e]

[msg MSG_014_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4115 0 0]All right. Let's resume after you catch your breath. I'll continue backing you up.[n][uf 1 1][e]

[msg MSG_015_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4113 0 0]Very well, then return to the entrance. It's good not to push yourselves.[n][uf 1 1][e]

[msg MSG_016_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4061 0 0]Oh, I'm not forcing you. You should decide based on the current situation.[n][uf 1 1][e]

[msg MSG_017_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 50 0 0][uf 3 1 3 0 65535 4086 0 0]Excellent victory![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]It seems you've gotten the hang of fighting here.[n][uf 1 1][e]

[sel SEL_018_0_0 top]
[uf 0 5 65278][uf 2 1]Sure have.[e]
[uf 0 5 65278][uf 2 1]Not really...[e]
[uf 0 5 65278][uf 2 1]But I won't drop my guard.[e]

[msg MSG_019_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 50 0 0][uf 3 1 3 0 65535 4107 0 0]Indeed. I'm impressed. You might even get by without my support.[n][uf 1 1][e]

[msg MSG_020_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 50 0 0][uf 3 1 3 0 65535 4131 0 0]*chuckle* Is that you being humble? You never fail to surprise me.[n][uf 1 1][e]

[msg MSG_021_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4065 0 0]I'm glad to hear it. We can never be sure what will happen in here.[n][uf 1 1][e]

[msg MSG_022_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]Hm... I must say, when I see all of you in action, it makes me want to join in too...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]...Never mind. Please continue exploring.[n][uf 1 1][e]

[msg MSG_023_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 4 65535 50 0 0][uf 3 1 3 0 65535 4030 0 0]I can't believe you managed victory all on your own! I must commend you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 50 0 0]Whatever your goal was in fighting alone... it was quite a spectacle indeed.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]However, I would personally prefer if you took someone along with you.[n][uf 1 1][e]

[sel SEL_024_0_0 top]
[uf 0 5 65278][uf 2 1]That's probably a good idea.[e]
[uf 0 5 65278][uf 2 1]That's not necessary.[e]
[uf 0 5 65278][uf 2 1]I'll think about it.[e]

[msg MSG_025_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 50 0 0][uf 3 1 3 0 65535 4024 0 0]Yes, there's no reason to take the risk of going alone.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]Everyone else is ready. Come back to the entrance if you want to form a party.[n][uf 1 1][e]

[msg MSG_026_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 6 65535 50 0 0][uf 3 1 3 0 65535 4061 0 0]I see... Well, you are the leader in the field, so I won't question your tactics.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]But while I trust in your abilities, make sure you're being careful at all times.[n][uf 1 1][e]

[msg MSG_027_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4036 0 0]The decision is yours, but it's important for the others to gain experience, too.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]If you want anyone to join you, come back to the entrance and form a party.[n][uf 1 1][e]

[msg MSG_028_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]All right, I'll be counting on you.[n][uf 1 1][e]

[msg MSG_029_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5011 0 0]The enemy has been defeated. Great work, everyone![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Leader, your direction was amazing![n][uf 1 1][e]

[sel SEL_030_0_0 top]
[uf 0 5 65278][uf 2 1]Yeah, it went well.[e]
[uf 0 5 65278][uf 2 1]I'm not so sure about that...[e]
[uf 0 5 65278][uf 2 1]It's all thanks to you, Fuuka.[e]

[msg MSG_031_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 50 0 0][uf 3 1 3 0 65535 5145 0 0]Yes, I knew I didn't have to worry. You did a great job, [uf 4 1]-chan.[n][uf 1 1][e]

[msg MSG_032_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 50 0 0][uf 3 1 3 0 65535 5122 0 0]Oh, really? Well, I think you did very well.[n][uf 1 1][e]

[msg MSG_033_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 1 0][uf 3 1 3 0 65535 5122 0 0]Wh-What? I don't... Um... Well, I'm glad if I was able to help you...[n][uf 1 1][e]

[msg MSG_034_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Anyway, there's a staircase up ahead. Keep it up![n][uf 1 1][e]

[msg MSG_035_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5113 0 0]Great job, everyone.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]This could be a good place to stop. Do you want to return for the day?[n][uf 1 1][e]

[sel SEL_036_0_0 top]
[uf 0 5 65278][uf 2 1]Yeah, let's do that.[e]
[uf 0 5 65278][uf 2 1]No, we're just getting started![e]
[uf 0 5 65278][uf 2 1]You're being very cautious.[e]

[msg MSG_037_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 50 0 0][uf 3 1 3 0 65535 5145 0 0]Okay, see you at the entrance.[n][uf 1 1][e]

[msg MSG_038_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5061 0 0]Oh, I see. Okay, I'll continue supporting you, then.[n][uf 1 1][e]

[msg MSG_039_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5065 0 0]Well, you never know what will happen, so I think it's good to be careful...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]But it's up to you, Leader. Just don't push yourself too hard, okay?[n][uf 1 1][e]

[msg MSG_040_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5087 0 0]The enemy has been defeated! Thanks for your hard work, everyone.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]If you're feeling up to it, how about exploring for a little more?[n][uf 1 1][e]

[sel SEL_041_0_0 top]
[uf 0 5 65278][uf 2 1]That's the plan.[e]
[uf 0 5 65278][uf 2 1]I want to return for now.[e]
[uf 0 5 65278][uf 2 1]Either way is fine.[e]

[msg MSG_042_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 50 0 0][uf 3 1 3 0 65535 5145 0 0]Okay! The stairs that lead to the next floor are right up ahead![n][uf 1 1][e]

[msg MSG_043_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5145 0 0]All right. Be careful on your way down.[n][uf 1 1][e]

[msg MSG_044_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 50 0 0][uf 3 1 3 0 65535 5062 0 0]It's a tough decision... Pulling back for now is definitely an option as well.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 50 0 0]Well, we'll do whatever you decide we should do, [uf 4 1]-chan.[n][uf 1 1][e]

[msg MSG_045_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 50 0 0][uf 3 1 3 0 65535 5086 0 0]The enemy has been defeated! How is everyone doing?[n][uf 1 1][e]

[msg MSG_046_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Um... Sorry if it's weird to bring this up right now, but...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]I really respect you all for fighting on the front line, despite the danger.[n][uf 1 1][e]

[sel SEL_047_0_0 top]
[uf 0 5 65278][uf 2 1]We're used to it.[e]
[uf 0 5 65278][uf 2 1]It's rough.[e]
[uf 0 5 65278][uf 2 1]Do you want to try?[e]

[msg MSG_048_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0][uf 3 1 3 0 65535 5099 0 0]Oh, is that what it is? Well, even still, I think it's amazing.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 50 0 0]Now that I think about it, I guess even I am more calm now than I was at first...[n][uf 1 1][e]

[msg MSG_049_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0][uf 3 1 3 0 65535 5060 0 0]Yeah... Even just one wrong move could lead to something terrible...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]But I'll be sure to keep supporting you so nothing like that ever happens.[n][uf 1 1][e]

[msg MSG_050_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0][uf 3 1 3 0 65535 5062 0 0]Sometimes, I wish I could... But I don't think that's very realistic for me...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]So, instead, I'll do whatever I can to keep you all safe on your journey.[n][uf 1 1][e]

[msg MSG_051_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0]Oh, um... Anyway, I just wanted to say that I'm really thankful to everyone.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 50 0 0]Let's all keep doing our best![n][uf 1 1][e]

[msg MSG_052_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0][uf 3 1 3 0 65535 5088 0 0]Wow... I can't believe you managed to win all by yourself![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 50 0 0]Everyone else is shocked, too. Do you plan to keep going alone?[n][uf 1 1][e]

[sel SEL_053_0_0 top]
[uf 0 5 65278][uf 2 1]I'll go as far as I can.[e]
[uf 0 5 65278][uf 2 1]I'm pretty worn out...[e]
[uf 0 5 65278][uf 2 1]I'll decide in a bit.[e]

[msg MSG_054_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 50 0 0][uf 3 1 3 0 65535 5116 0 0]All right. Honestly, I'm a little worried about you being on your own there...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 50 0 0]But I'm also excited to see what else you're capable of. Just please be careful.[n][uf 1 1][e]

[msg MSG_055_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 50 0 0][uf 3 1 3 0 65535 5099 0 0]Oh, then please come back immediately! You'll be safer with a full party.[n][uf 1 1][e]

[msg MSG_056_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5062 0 0]Okay. I'm sure you'd be fine, but please don't push yourself either.[n][uf 1 1][e]

[msg MSG_057_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 50 0 0]Everyone here is cheering you on and ready to join you if you need them.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 50 0 0]Good luck![n][uf 1 1][e]

