[msg MND_006_0_0]
[uf 0 5 65278][uf 2 1]Siento cómo las poderosas emociones de mis amigos desembocan en mi corazón.[n][uf 1 1][e]

[msg MSG_007_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 1 6 65 0 0][uf 3 1 1 0 0 9 0 0]Siempre te cubriré las espaldas, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 1 6 65 0 0][uf 3 1 1 0 0 10 0 0]De momento solo me queda rezar, sea lo que sea eso...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 1 6 65 0 0][uf 3 1 1 0 0 11 0 0]No te preocupes. Sé que podrás hacerlo.[n][uf 1 1][e]

[msg MSG_008_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 1 2 65 0 0][uf 3 1 1 0 0 12 0 0]Sé que te enfrentas a una tarea complicada, allá donde estés...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 1 2 65 0 0][uf 3 1 1 0 0 13 0 0]Pero creo firmemente que puedes superar cualquier obstáculo.[n][uf 1 1][e]

[msg MSG_009_0_0 [Bunkichi]]
[uf 0 5 65278][uf 2 1][uf 4 5 103 1 65535 65 0 0][uf 3 1 1 0 0 14 0 0]Está ocurriendo algo espantoso..., pero no nos rendiremos.[n][uf 1 1][e]

[msg MSG_010_0_0 [Mitsuko]]
[uf 0 5 65278][uf 2 1][uf 4 5 104 1 65535 65 0 0][uf 3 1 1 0 0 15 0 0]Exacto, cariño... Tenemos que ser fuertes por [uf 4 2].[n][uf 1 1][e]

[msg MSG_011_0_0 [Kazushi Miyamoto]]
[uf 0 5 65278][uf 2 1][uf 4 5 105 1 101 65 0 0][uf 3 1 1 0 0 16 0 0]Está ocurriendo algo descabellado, pero sé que estás haciendo todo cuanto está en tu mano, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 105 1 101 65 0 0][uf 3 1 1 0 0 17 0 0]No voy a perder la esperanza. Eso es algo que he aprendido de ti.[n][uf 1 1][e]

[msg MSG_012_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 1 6 65 0 0][uf 3 1 1 0 0 18 0 0]¡Si me encuentro bien ahora mismo es porque tú me has dado coraje para valerme por mí misma![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 1 6 65 0 0][uf 3 1 1 0 0 19 0 0]¡Por eso no puedes rendirte![n][uf 1 1][e]

[msg MSG_013_0_0 [Maya]]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 66 0 0][uf 3 1 1 0 0 20 0 0]Ay, madre, ¡me va a dar algo! Pero sé que ella también está esforzándose por hacerlo lo mejor posible...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 107 0 65535 66 0 0][uf 3 1 1 0 0 21 0 0]Ni siquiera sé qué aspecto tiene, pero sé que está bien. Lo presiento.[n][uf 1 1][e]

[msg MSG_014_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 6 65 0 0][uf 3 1 1 0 0 22 0 0][uf 4 1], sé que estás intentando concentrarte.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 6 65 0 0][uf 3 1 1 0 0 23 0 0]Estuviste ahí cuando te necesitaba. Espero poder hacer lo mismo por ti.[n][uf 1 1][e]

[msg MSG_015_0_0 [Yuko Nishiwaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 6 65 0 0][uf 3 1 1 0 0 24 0 0]Oye, [uf 4 1], ¿te puedes creer lo que está pasando?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 106 1 6 65 0 0][uf 3 1 1 0 0 25 0 0]Sé que estarás esforzándote al máximo, ¡así que yo haré lo propio![n][uf 1 1][e]

[msg MSG_016_0_0 [Maiko]]
[uf 0 5 65278][uf 2 1][uf 4 5 110 1 6 65 0 0][uf 3 1 1 0 0 26 0 0]Todos están asustados, excepto yo.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 110 1 6 65 0 0][uf 3 1 1 0 0 27 0 0]¡Tú me has enseñado a ser fuerte![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 110 1 6 65 0 0][uf 3 1 1 0 0 28 0 0]No me rendiré.[n][uf 1 1][e]

[msg MSG_017_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 1 6 65 0 0][uf 3 1 1 0 0 29 0 0]¿Cómo estás, [uf 4 2]? Espero que très bien...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 112 1 6 65 0 0][uf 3 1 1 0 0 30 0 0]¡Igual que tú estuviste ahí para mí, yo estoy aquí para ti![n][uf 1 1][e]

[msg MSG_018_0_0 [Presidente Tanaka]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 1 65535 65 0 0][uf 3 1 1 0 0 31 0 0]¿Qué narices me ha hecho pensar en ti en un momento como este?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 1 65535 65 0 0][uf 3 1 1 0 0 32 0 0]En fin, se ve que me enseñaste algunas cosas en materia de confianza.[n][uf 1 1][e]

[msg MSG_019_0_0 [Mutatsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 114 1 65535 65 0 0][uf 3 1 1 0 0 33 0 0]De ti aprendí que huir nunca es la solución a los problemas.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 114 1 65535 65 0 0][uf 3 1 1 0 0 34 0 0]Seguro que en estos momentos estás en alguna parte librando un buen combate...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 114 1 65535 65 0 0][uf 3 1 1 0 0 35 0 0]Puedes contar conmigo también para lo que sea, jovencita.[n][uf 1 1][e]

[msg MSG_020_0_0 [Mamoru Hayase]]
[uf 0 5 65278][uf 2 1][uf 4 5 115 1 65535 65 0 0][uf 3 1 1 0 0 36 0 0]Aceptaré todo reto que se me presente sin rechistar.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 115 1 65535 65 0 0][uf 3 1 1 0 0 37 0 0]Eso fue lo que me enseñaste, [uf 4 1]. Seguro que tú también estás luchando ahora.[n][uf 1 1][e]

[msg MSG_021_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 1 2 65 0 0][uf 3 1 1 0 0 38 0 0]Me salvaste, [uf 4 2]. Antes estaba completamente ciego.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 1 2 65 0 0][uf 3 1 1 0 0 39 0 0]Seguro que lo tienes todo bajo control, ¿verdad? Como siempre.[n][uf 1 1][e]

[msg MSG_022_0_0 [Akinari Kamiki]]
[uf 0 5 65278][uf 2 1][uf 4 5 117 1 65535 65 0 0][uf 3 1 1 0 0 40 0 0]Sé que no solo yo he sufrido... Tú también has padecido mucho.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 117 1 65535 65 0 0][uf 3 1 1 0 0 41 0 0]Pero no puedes rendirte sin más... Eso me lo enseñaste tú.[n][uf 1 1][e]

