[msg MSG_000_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]Sluup. Sluup.[n][uf 1 1][e]

[msg MSG_000_3_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]¡Uf! ¡Así me gusta![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]¿Qué, llevaba razón o no llevaba razón? ¡El caldo está que te cagas de bueno![n][uf 1 1][e]

[msg MSG_000_5_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 2 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]Le echarán algún ingrediente especial que solo tienen aquí.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 3 65535 65535 0 0][uf 3 1 1 0 0 5 0 0][uf 4 23 0 101 3 25 25]A lo mejor el nombre nos da alguna pista.[n][uf 1 1][e]

[msg MSG_001_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]Ah, perdona.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]Es que me emociono cuando vengo a comer a este sitio.[n][uf 1 1][e]

[sel SEL_002_0_0 top]
[uf 0 5 65278][uf 2 1]Ya sé por dónde vas.[e]
[uf 0 5 65278][uf 2 1]Come y calla.[e]

[msg MSG_003_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0][uf 3 1 1 0 0 8 0 0]¿De verdad? ¿Tú también saboreas la magia?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0][uf 3 1 1 0 0 9 0 0]Tía, jamás pensé que fueras una caja de sorpresas.[n][uf 1 1][e]

[msg MSG_004_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]Sí, tienes razón. Si nos liamos a hablar, se pondrán blandos los fideos.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0][uf 3 1 1 0 0 11 0 0]Por la forma en la que degustas el caldo, parece que sabes apreciar el sabor.[n][uf 1 1][e]

[msg MSG_005_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]Oye, tengo entendido que Yukari y tú estáis muy unidos.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]Y eso que acabas de llegar, ¿no?[n][uf 1 1][e]

[msg MSG_005_3_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 1 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]Pero normal, también te digo. Nosotros tenemos que lanzarnos.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0][uf 3 1 1 0 0 15 0 0][uf 4 23 0 101 0 25 25]Oye, podríamos quedar después de clase otro día. Ya me dirás cuándo te viene bien.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 1 65535 65535 0 0][uf 3 1 1 0 0 16 0 0][uf 4 23 0 101 1 25 25]Así te hablo de mi plan secreto. ¡Vas a flipar cuando te lo cuente![n][uf 1 1][e]

[msg MND_006_0_0]
[uf 0 5 65278][uf 2 1]Parece que le caigo bien a Kenji Tomochika.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]¡¿...?![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Una voz resuena en mi cabeza...[n][uf 1 1][e]

[msg SYS_007_0_0]
[uf 0 5 65278][uf 2 1]DEV: Unused label.[n][uf 1 1][e]

[msg MSG_008_0_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 4 65535 65535 0 0][uf 3 1 1 0 0 17 0 0]¿Ya es de noche? Jo, me he perdido mi programa favorito.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 101 6 65535 65535 0 0][uf 3 1 1 0 0 18 0 0][uf 4 23 0 101 3 25 25]Buah, ¿en serio? En fin, vámonos ya.[n][uf 1 1][e]

[msg MSG_008_3_0 [Kenji Tomochika]]
[uf 0 5 65278][uf 2 1][uf 4 5 101 0 65535 65535 0 0][uf 3 1 1 0 0 19 0 0]Antes de nada, vamos a darnos el número. ¡Saca el teléfono![n][uf 1 1][e]

[msg SYS_008_5_0]
[uf 0 5 65278][uf 2 1]DEV: Unused label.[n][uf 1 1][e]

[msg MND_009_0_0]
[uf 0 5 65278][uf 2 1]He decidido volver a la residencia.[n][uf 1 1][e]

