[msg MSG_000_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]C'est quoi ce délire ?! Ça dit : "Jeux de balle interdits dans le parc"...[n][uf 1 1][e]

[msg MSG_001_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]C'est chelou, tu trouves pas ?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]En jouant comme ça, les gamins se font de nouveaux potes. Les adultes peuvent pas juste interdire ça parce que ça leur chante ![n][uf 1 1][e]

[sel SEL_002_0_0 top]
[uf 0 5 65278][uf 2 1]Ça dépend où...[e]
[uf 0 5 65278][uf 2 1]Ouais, ils n'ont pas le droit ![e]

[msg MSG_003_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 4 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]Et voilà la voix de la raison...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 1 0 0 5 0 0][uf 4 23 0 1 0 25 25]Si ça continue, les gamins auront plus aucun endroit où jouer au base-ball.[n][uf 1 1][e]

[msg MSG_004_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]C'est clair ! J'aime vraiment pas ça ![n][uf 1 1][e]

[msg MSG_005_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]Dans tous les cas, je savais pas que c'était interdit ici jusqu'à aujourd'hui.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 1 0 0 8 0 0]À l'époque, quand j'ai déménagé ici, je jouais à lancer la balle contre le mur de temps en temps.[n][uf 1 1][e]

[msg MSG_006_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 1 0 0 9 0 0]Tout ça... c'est parce que je voulais me muscler les bras.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]Je pense de plus en plus à me remettre au base-ball.[n][uf 1 1][e]

[msg MSG_007_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 1 0 0 11 0 0]J'ai toujours pas la moindre idée de ce que je veux faire de ma vie.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]Et si je continue à faire l'autruche, je vais le regretter.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]La prochaine fois qu'on me demande ce que je ferai dans deux ans, je veux pouvoir répondre sincèrement.[n][uf 1 1][e]

[msg MSG_008_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]C'est pour ça que j'essaie de reprendre le base-ball. Euh... Tu penses que je fais bien ?[n][uf 1 1][e]

[sel SEL_009_0_0 top]
[uf 0 5 65278][uf 2 1]Ça me paraît être une bonne idée.[e]
[uf 0 5 65278][uf 2 1]Tu penses que c'est une bonne idée ?[e]
[uf 0 5 65278][uf 2 1]Du Junpei tout craché.[e]

[msg MSG_010_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 0 15 0 0]Ah ouais ? Ça me soulage de t'entendre dire ça.[n][uf 1 1][e]

[msg MSG_011_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 1 0 0 16 0 0]Hmm... Rien d'autre me vient à l'esprit.[n][uf 1 1][e]

[msg MSG_012_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 0 17 0 0]C'est censé être un compliment ?[n][uf 1 1][e]

[msg MSG_013_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 1 0 0 18 0 0]Bref, tiens. C'est pour toi.[n][uf 1 1][e]

[msg MSG_014_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 1 0 0 19 0 0]Bon, ça a été un fiasco aujourd'hui, mais on réessaiera. Garde ça en attendant.[n][uf 1 1][e]

[msg MSG_015_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 1 0 0 20 0 0]Même si j'imagine qu'on va devoir attendre d'en avoir fini avec... tu sais quoi.[n][uf 1 1][e]

[msg MSG_016_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 65535 65535 0 0][uf 3 1 1 0 0 21 0 0]Aaah, je sais pas... Honnêtement, je pense comme ça depuis avril.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 3 65535 65535 0 0][uf 3 1 1 0 0 22 0 0]J'arrive à peine à gérer tout ce que j'ai sur le dos, alors penser à l'avenir...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 1 0 0 23 0 0][uf 4 23 0 1 0 25 25]Mais nos senpai sont ultra balèzes. J'en reviens pas qu'ils continuent de réviser pour leurs exams avec tout ce qui se passe.[n][uf 1 1][e]

[msg MSG_017_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 1 0 0 24 0 0]Pff, ça a été une année de malade...[n][uf 1 1][e]

[msg MSG_018_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 1 0 0 25 0 0]Je suis sûr qu'on repensera à ça plus tard en se demandant comment on a fait pour s'en sortir.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 1 0 0 26 0 0]Ça a pas toujours été facile, et on a bien galéré quand même...[n][uf 1 1][e]

[msg MSG_019_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 0 27 0 0]On peut dire qu'on a eu une vie sacrément bien remplie jusque là, hein ?[n][uf 1 1][e]

[sel SEL_020_0_0 top]
[uf 0 5 65278][uf 2 1]C'est toi qui l'as dit.[e]
[uf 0 5 65278][uf 2 1]Je ne dirais pas ça.[e]

[msg MSG_021_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 0 28 0 0]Haha, c'est clair ![n][uf 1 1][e]

[msg MSG_022_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 0 29 0 0]Meuf, t'es juste censée être d'accord. Mais bon, j'en attendais pas moins de toi.[n][uf 1 1][e]

[msg MSG_023_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 1 0 0 30 0 0]Malgré tout ce qui s'est passé, je suis bien content que tu sois devenue notre chef, [uf 4 2].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 1 0 0 31 0 0]Je sais que je t'avais dit de faire ce que tu voulais, mais merci d'avoir choisi de te battre.[n][uf 1 1][e]

[msg MSG_024_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 0 32 0 0]Dans ce cas...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 0 33 0 0]Faisons de notre mieux pour boucler ce chapitre de notre vie en beauté, OK ?[n][uf 1 1][e]

[msg MSG_025_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 0 34 0 0]Et après ce sera direction Hollywood pour un film sur nos aventures ![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 0 35 0 0]Le rôle principal sera pour moi, évidemment, mais je suis sûr que tu pourrais remporter l'oscar du meilleur second rôle ![n][uf 1 1][e]

[msg MSG_026_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 0 36 0 0]Héhéhé...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 0 37 0 0]Tous ces trucs sérieux, c'est pas notre genre, hein ?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 0 38 0 0]Allez, rentrons. On réfléchira à comment rafler tous les oscars en route.[n][uf 1 1][e]

[msg MND_027_0_0]
[uf 0 5 65278][uf 2 1]Junpei et moi avons fait les idiots sur le chemin du retour.[n][uf 1 1][e]

[msg SYS_028_0_0]
[uf 0 5 65278][uf 2 1]Vous avez noué un lien indéfectible avec Junpei. Vous pouvez désormais créer [uf 0 1 35]Surt[uf 0 1 27], le seigneur du feu ![n][uf 1 1][e]

