[msg MSG_000_0_0 [Yukari Takeba]]
[f 2 1][bup 2 4 65535 65535 0 0][vp 3 0 65535 1067 0 0]Anda, ya está anocheciendo.[n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0][f 4 23 0 2 1 25 25]Se me ha pasado el tiempo volando.[n][w][e]

[msg MSG_001_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0]¿Te has dado cuenta de que hay un montón de mangas sobre estudiantes que se ven envueltos en batallas?[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][f 4 23 0 2 0 25 25]No lo había pensado hasta ahora, pero... supongo que ahora somos así.[n][w][e]

[msg MSG_002_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 3 0 65535 1062 0 0]Aunque bueno, nadie nos conoce...[n][w][e]

[sel SEL_003_0_0 top]
[f 2 1]Tú pareces una heroína.[e]
[f 2 1]Seguramente no.[e]
[f 2 1]Algunas personas sí.[e]

[msg MSG_004_0_0 [Yukari Takeba]]
[f 2 1][bup 2 4 65535 65535 0 0][vp 3 0 65535 1047 0 0]¿A qué viene eso?[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][f 4 23 0 2 0 25 25]¿Es porque estoy en el club de tiro con arco?[n][w][e]

[msg MSG_004_3_0 [Yukari Takeba]]
[f 2 1][bup 2 2 65535 65535 0 0]Pues sí, tengo los brazos fuertes...[n][w][e]
[f 2 1][bup 2 2 65535 65535 0 0]¡Pero no estoy presumiendo de ello ni nada parecido![n][w][e]

[msg MND_005_0_0]
[f 2 1]Yukari parece enfadada.[n][w][e]
[f 2 1]Siento que hoy nuestra relación no ha cambiado nada...[n][w][e]

[msg MSG_006_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 3 0 65535 1025 0 0]Le doy demasiadas vueltas...[n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0]¿Tengo que verlo como nuestro secreto?[n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0]Un secreto, ¿eh...?[n][w][e]

[msg MND_007_0_0]
[f 2 1]Yukari parece bastante feliz...[n][w][e]
[f 2 1]Hoy he aprendido un poco más sobre ella.[n][w][e]

[msg MSG_008_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 3 0 65535 1061 0 0]¿Cómo quién...?[n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0][f 4 23 0 2 1 25 25]¿El agente Kurosawa?[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][f 4 23 0 2 0 25 25]No me gusta decir estas cosas, y más porque nos ha estado ayudando, pero...[n][w][e]

[msg MSG_008_3_0 [Yukari Takeba]]
[f 2 1][bup 2 3 65535 65535 0 0]¿No te parece que su cara da un poco de yuyu? Fíjate en sus ojos. No le digas a nadie que te lo he dicho.[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0][f 5 13 7 30 2]Bueno, está bien que al menos una persona aprecie el esfuerzo que estamos haciendo.[n][w][e]

[msg MND_009_0_0]
[f 2 1]Yukari y yo ahora nos entendemos mejor.[n][w][e]
[f 2 1]Siento que hoy nuestra relación se ha estrechado.[n][w][e]

[msg MSG_010_0_0 [Yukari Takeba]]
[f 2 1][bup 2 6 65535 65535 0 0][vp 3 0 65535 1114 0 0]Ay... Tengo la espalda agarrotada de estar en la misma posición tanto tiempo.[n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0][f 4 23 0 2 1 25 25]Vamos a estirar un poco las articulaciones antes de volver. ¿Qué me dices?[n][w][e]

[msg MND_011_0_0]
[f 2 1]Hemos dado una vuelta juntas antes de volver a la residencia.[n][w][e]

