[msg MSG_000_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 3 0 65535 11083 0 0]Uf, estaba petado, ¿eh?[n][w][e]
[f 2 1][bup 106 3 65535 65535 0 0][f 4 23 0 106 3 25 25]Quería probar la máquina de boxeo, pero con tanta cola, se me han pasado las ganas.[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0][f 4 23 0 106 0 25 25]Volvamos cuando no haya tanta gente.[n][w][e]

[msg MSG_000_3_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][f 4 25 106]Ay, madre...[n][w][e]

[msg MSG_001_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0]¡Mira! ¡Qué cosa más bonita! Además, podríamos conseguirlo con un intento.[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0]Hace tiempo que no juego. Puede que no lo parezca, pero se me da bastante bien.[n][w][e]

[msg MSG_002_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 4 65535 65535 0 0]¿E-eh? No había manera de cogerlo.[n][w][e]
[f 2 1][bup 106 2 65535 65535 0 0][vp 3 0 65535 11076 0 0][f 4 23 0 106 2 25 25]¡¿Qué?! ¡No fastidies! ¡Menuda mierda! ¡Esto tiene que estar trucado o algo![n][w][e]

[sel SEL_003_0_0 top]
[f 2 1]Vamos a calmarnos.[e]
[f 2 1]Se te da fatal.[e]
[f 2 1]¿Quieres que lo intente yo?[e]

[msg MSG_004_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 3 0 65535 11019 0 0][f 5 13 12 30 106]Ah, sí, claro.[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0][f 4 23 0 106 0 25 25]Si agarrarlo no funciona... Tendré que cambiarlo de posición poco a poco hasta que caiga.[n][w][e]

[msg MSG_004_3_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0]Es un coñazo, pero con paciencia y perseverancia también se gana.[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0]Con el deporte pasa lo mismo, ¿no? Las personas dedicadas a entrenar se convierten en atletas de primer nivel.[n][w][e]

[msg MSG_004_5_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0]Ah... Que me voy por las ramas. Bueno, ¡volvamos a intentarlo![n][w][e]

[msg MND_005_0_0]
[f 2 1]Yuko parece motivada.[n][w][e]
[f 2 1]Siento que hoy nuestra relación se ha estrechado.[n][w][e]

[msg MSG_006_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 2 65535 65535 0 0][vp 3 0 65535 11027 0 0]¡Qué va! ¡Es el maldito gancho! ¡Es demasiado flojo![n][w][e]
[f 2 1][bup 106 3 65535 65535 0 0][f 4 23 0 106 3 25 25]Uf... Tendré que cambiarlo de posición poco a poco hasta que caiga.[n][w][e]

[msg MSG_006_3_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0]Al final, con paciencia y perseverancia también se gana..., aunque sea un rollo patatero.[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0]Con el deporte pasa lo mismo. Las personas dedicadas a entrenar se convierten en atletas de primer nivel.[n][w][e]

[msg MSG_006_5_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0]Pero eso ahora no importa. Venga, ¡tengo que llevarme el premio![n][w][e]

[msg MND_007_0_0]
[f 2 1]Yuko se muestra seria.[n][w][e]
[f 2 1]Siento que hoy nuestra relación no ha cambiado nada...[n][w][e]

[msg MSG_008_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 4 65535 65535 0 0][vp 3 0 65535 11075 0 0][f 5 13 12 15 106]¿Eh? Ah, gracias por ofrecerte, pero no te preocupes.[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0][f 4 23 0 106 1 25 25]Si sigo empujándolo en la dirección correcta, debería derribarlo sin problemas.[n][w][e]

[msg MSG_008_3_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0]Es un coñazo, pero con paciencia y perseverancia también se gana, ¿sabes?[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0]Con el deporte pasa lo mismo. Las personas dedicadas a entrenar se convierten en atletas de primer nivel.[n][w][e]

[msg MSG_008_5_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0]Bueno, vamos a ponernos serias. Voy a seguir insistiendo hasta que lo gane.[n][w][e]

[msg MND_009_0_0]
[f 2 1]Veo que Yuko se emplea a fondo.[n][w][e]
[f 2 1]Hoy he aprendido un poco más sobre ella.[n][w][e]

[msg MSG_010_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 3 65535 65535 0 0]Bueno, al menos me lo he llevado...[n][w][e]
[f 2 1][bup 106 3 65535 65535 0 0]Pero ahora estoy muy cansada. Me he quedado sin energía y sin dinero.[n][w][e]

[msg MSG_010_3_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 3 65535 65535 0 0][vp 3 0 65535 11071 0 0]Volvamos, [nl]. Necesito cenar y recuperarme.[n][w][e]

[msg MND_011_0_0]
[f 2 1]Tras despedirme de Yuko, he vuelto a la residencia.[n][w][e]

