[msg MSG_000_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 1 65535 65535 0 0][vp 3 0 65535 10094 0 0]¡Soy un máquina bailando! ¡Algún día conseguiré la mejor puntuación![n][w][e]

[msg MSG_001_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 4 65535 65535 0 0]Eh, bueno...[n][w][e]
[f 2 1][bup 101 0 65535 65535 0 0][f 4 23 0 101 0 25 25]Cambiando de tema... Hay algo que tengo que preguntarte.[n][w][e]

[msg MSG_002_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 0 65535 65535 0 0][vp 3 0 65535 10064 0 0]N-no te rías, ¿vale? Quería preguntarte si alguna vez has besado a una chica...[n][w][e]

[sel SEL_003_0_0 top]
[f 2 1]Yo sí.[e]
[f 2 1]Qué va.[e]
[f 2 1]Sí, un montón de veces.[e]

[msg MSG_004_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 4 65535 65535 0 1][vp 3 0 65535 10073 0 0]S-sí, claro, me lo imaginaba, pero tenía que preguntártelo.[n][w][e]
[f 2 1][bup 101 3 65535 65535 0 1][f 4 23 0 101 10 25 25]Es que no quiero salir por ahí con alguien que nunca ha besado a una chica. Ja, ja...[n][w][e]

[msg MND_005_0_0]
[f 2 1]Tomochika parece estar un poco triste.[n][w][e]
[f 2 1]Siento que hoy nuestra relación no ha cambiado nada...[n][w][e]

[msg MSG_006_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 4 65535 65535 0 0][vp 3 0 65535 10074 0 0][f 5 13 2 30 101]Espera, ¿en serio? Vaya, tía, estaba convencido de que lo habías hecho.[n][w][e]
[f 2 1][bup 101 1 65535 65535 0 0][f 4 23 0 101 1 25 25]A ver, tampoco pasa nada. Yo tampoco he besado a ninguna chica.[n][w][e]

[msg MND_007_0_0]
[f 2 1]Tomochika parece contento por algo.[n][w][e]
[f 2 1]Siento que hoy nuestra relación se ha estrechado.[n][w][e]

[msg MSG_008_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 4 65535 65535 0 1][vp 3 0 65535 10075 0 0][f 5 13 2 15 101]¡¿De verdad?![n][w][e]
[f 2 1][bup 101 4 65535 65535 0 1]Mujer... no sabía que fueras tan picada...[n][w][e]

[msg MND_009_0_0]
[f 2 1]Tomochika parece impresionado.[n][w][e]
[f 2 1]Hoy he aprendido un poco más sobre él.[n][w][e]

[msg MSG_010_0_0 [Kenji Tomochika]]
[f 2 1][bup 101 0 65535 65535 0 0][vp 3 0 65535 10047 0 0]Perdona... Ha sido una pregunta extraña, ¿verdad? Vamos a aparcar el tema y aquí no ha pasado nada.[n][w][e]
[f 2 1][bup 101 1 65535 65535 0 0][f 4 23 0 101 1 25 25]Bueno, ¿a dónde vamos? ¿Echamos un vistazo a los discos?[n][w][e]

[msg MND_011_0_0]
[f 2 1]Los dos pasamos un rato más juntos antes de volver a la residencia.[n][w][e]

