[msg MSG_000_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 1 0 0]Perdón por el retraso.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 2 0 0]Resumiendo, quiero que te unas al consejo estudiantil.[n][w][e]

[sel SEL_001_0_0 top]
[f 2 1]Eso es mucho curro.[e]
[f 2 1]No sé qué decirte...[e]

[msg MSG_002_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 3 0 0]Nos reunimos a menudo, pero no hace falta que asistas siempre.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 4 0 0]Solo tienes que pasarte por el aula del consejo estudiantil cuando puedas.[n][w][e]

[sel SEL_003_0_0 top]
[f 2 1]¿Y nada más?[e]
[f 2 1]¿Por qué yo?[e]

[msg MSG_004_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 5 0 0]Sí, nada más. Solo quiero que seas miembro.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 6 0 0]A la presidencia hay que echarle muchas horas. Me gustaría tener cerca a una aliada por si surge una emergencia.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 7 0 0]Con "aliada", me refiero a alguien que entienda mi situación. Además, tú ya sabes lo que es liderar.[n][w][e]

[msg MSG_005_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 8 0 0]Por tu destreza para dar órdenes.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 9 0 0]A la presidencia hay que echarle muchas horas. Me gustaría tener cerca a una aliada por si surge una emergencia.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 10 0 0]Con "aliada", me refiero a alguien que entienda mi situación. Además, tú ya sabes lo que es liderar.[n][w][e]

[sel SEL_006_0_0 top]
[f 2 1]Vale, acepto.[e]
[f 2 1]Pues bueno...[e]

[msg MSG_007_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 11 0 0]Sabía que podía contar contigo.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 12 0 0][f 4 23 0 1 0 25 25]Ya he rellenado y aprobado tu membresía por ti.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 13 0 0]Pero tendrás que ir a la sala de profesores para firmar los papeles.[n][w][e]

[msg MND_008_0_0]
[f 2 1]Para unirme al consejo estudiantil, [clr 2]debo hablar con la profesora Toriumi[clr 27].[n][w][e]
[f 2 1]Tengo que decirle que voy a [clr 2]unirme al consejo estudiantil[clr 27].[n][w][e]

[msg MSG_009_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 14 0 0]Siento haberlo organizado todo sin tu permiso, pero espero que entiendas mi situación.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 1 0 0 15 0 0]Ven a la sala del consejo estudiantil cuando estés listo. Allí te espero.[n][w][e]

