[msg MSG_000_0_0 [Yukari Takeba]]
[f 2 1][bup 2 11 65535 65535 0 0][vp 3 0 65535 1114 0 0]¡Mmm! ¡Estaba riquííísimo![n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0][f 4 23 0 2 1 25 25]¡No hay nada mejor que el daifuku de fresa de azuki![n][w][e]

[msg MSG_001_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0]Tengo que preguntarte una cosa.[n][w][e]

[msg MSG_002_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 3 0 65535 1075 0 0]¿Te gusta el daifuku de fresa de azuki?[n][w][e]

[sel SEL_003_0_0 top]
[f 2 1]No, la verdad.[e]
[f 2 1]Me encanta.[e]
[f 2 1]Nunca lo he probado.[e]

[msg MSG_004_0_0 [Yukari Takeba]]
[f 2 1][bup 2 3 65535 65535 0 0][vp 3 0 65535 1122 0 0][f 5 13 7 15 2]¡¿Qué?! ¡Pero si está de muerte![n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0][f 4 23 0 2 1 25 25]Supongo que cada quien tiene sus gustos. Puede que cambies de idea si lo pruebas por segunda vez.[n][w][e]

[msg MND_005_0_0]
[f 2 1]Parece que Yukari se está divirtiendo.[n][w][e]
[f 2 1]Hoy he aprendido un poco más sobre ella.[n][w][e]

[msg MSG_006_0_0 [Yukari Takeba]]
[f 2 1][bup 2 11 65535 65535 0 0][vp 3 0 65535 1029 0 0][f 5 13 7 30 2]¿A que sí? La parte de fuera rosa es bonita, ¿no?[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0][f 4 23 0 2 0 25 25]A ver, si la parte de fuera no es rosa, ¿se le podría llamar acaso pastel de arroz con fresas?[n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0][f 4 23 0 2 1 25 25]Me pregunto si además del gusto para la comida, compartiremos otros gustos...[n][w][e]

[msg MND_007_0_0]
[f 2 1]Yukari parece emocionada.[n][w][e]
[f 2 1]Siento que hoy nuestra relación se ha estrechado.[n][w][e]

[msg MSG_008_0_0 [Yukari Takeba]]
[f 2 1][bup 2 4 65535 65535 0 0][vp 3 0 65535 1122 0 0]¿Ni una sola vez? Qué locura.[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0][f 4 23 0 2 3 25 25]Creo que eres la primera persona que conozco que no lo ha probado...[n][w][e]

[msg MND_009_0_0]
[f 2 1]Yukari parece un poco incómoda.[n][w][e]
[f 2 1]Siento que hoy nuestra relación no ha cambiado nada...[n][w][e]

[msg MSG_010_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 3 0 65535 1061 0 0]¿Qué quieres hacer ahora? Como ya hemos comido, ¿vamos a dar una vuelta?[n][w][e]

[msg MND_011_0_0]
[f 2 1]He dado una vuelta con Yukari antes de volver a la residencia.[n][w][e]

