[msg TRL_000_0_0 [Usar objetos y habilidades]]
[f 2 1][f 4 8 0]Si te hieren mientras exploras la torre Tártaro, puedes usar objetos y habilidades para recuperar PS o PE.[n][w][e]

[msg TRL_001_0_0 [Usar objetos y habilidades]]
[f 2 1][f 4 8 3]Abre el menú [f 1 3 112], selecciona [clr 2]Objeto[clr 27] y elige un objeto de curación, como [f 4 4 0 37 1 16385] o [f 4 4 0 37 1 16412], por ejemplo. Luego, selecciona a un miembro del grupo.[n][w][e]

[msg TRL_002_0_0 [Usar objetos y habilidades]]
[f 2 1][f 4 8 2]Las habilidades funcionan de forma similar. Primero, abre el menú y selecciona [clr 2]Habilidad[clr 27]. Luego, elige una habilidad de recuperación, como [clr 35]Dia[clr 27], por ejemplo. Por último, selecciona a un miembro del grupo.[n][w][e]

[msg TRL_003_0_0 [Usar objetos y habilidades]]
[f 2 1][f 4 8 0]Se recomienda que priorices los PS de la líder para que [nf] no se desmaye mientras explora.[n][w][e]

