[msg MSG_000_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 1 0 0]¿Te importa acercarte un poco?[n][w][e]

[msg MSG_000_3_0 [Aigis]]
[f 2 1][bup 7 1 65535 65535 0 0][vp 1 0 0 2 0 0]Perfecto, ahí está bien.[n][w][e]
[f 2 1][bup 7 1 65535 65535 0 0][vp 1 0 0 3 0 0]Vale, allá vamos.[n][w][e]

[msg MSG_001_0_0 [Aigis]]
[f 2 1][bup 7 1 65535 65535 0 0][vp 1 0 0 4 0 0]¡P-patata![n][w][e]

[sel SEL_002_0_0 top]
[f 2 1]Patata.[e]
[f 2 1]...[e]

[msg MSG_003_0_0 [Aigis]]
[f 2 1][bup 7 1 65535 65535 0 0][vp 1 0 0 5 0 0]¡Genial! Ha salido estupenda.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 6 0 0][f 4 23 0 7 0 25 25]La última vez que os sacasteis fotos, yo no estaba.[n][w][e]

[msg MSG_004_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 7 0 0]Tenía ganas de hacerme una contigo.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 8 0 0]Técnicamente, puedo grabar vídeos con los ojos.[n][w][e]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 9 0 0][f 4 23 0 7 3 25 25]Pero entonces no saldría yo en las imágenes.[n][w][e]

[msg MSG_005_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 10 0 0]Sé que es un poco tarde para preguntarlo, pero...[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 11 0 0]¿Te gusta hacerte fotos, [nf]?[n][w][e]

[sel SEL_006_0_0 top]
[f 2 1]Sí, es divertido.[e]
[f 2 1]No, la verdad.[e]

[msg MSG_007_0_0 [Aigis]]
[f 2 1][bup 7 1 65535 65535 0 0][vp 1 0 0 12 0 0]Uf, menos mal.[n][w][e]
[f 2 1][bup 7 1 65535 65535 0 0][vp 1 0 0 13 0 0]Vamos a sacarnos una haciendo el tonto.[n][w][e]

[msg MSG_008_0_0 [Aigis]]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 14 0 0]L-lo siento si te he incomodado.[n][w][e]
[f 2 1][bup 7 1 65535 65535 0 0][vp 1 0 0 15 0 0][f 4 23 0 7 1 25 25]Guardaré esta como un tesoro.[n][w][e]

[msg MSG_009_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 16 0 0]Creo que las fotos son un invento increíble.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 17 0 0]Nos permiten preservar un momento único en el flujo infinito del tiempo.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 18 0 0]Es una tecnología nacida del deseo de conservar las experiencias valiosas.[n][w][e]

[msg MSG_010_0_0 [Aigis]]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 19 0 0]Hasta hace poco, me entristecía ser una máquina, ser tan diferente.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 20 0 0][f 4 23 0 7 0 25 25]Pero, ahora que me he sincerado contigo, me he dado cuenta de una cosa.[n][w][e]
[f 2 1][bup 7 1 65535 65535 0 0][vp 1 0 0 21 0 0][f 4 23 0 7 1 25 25]Hay algo que solo yo, una máquina con corazón humano, puedo hacer.[n][w][e]

[sel SEL_011_0_0 top]
[f 2 1]¿El qué?[e]
[f 2 1]No lo entiendo.[e]

[msg MSG_012_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 22 0 0]Por muy nítidas que sean las fotos y los vídeos, no preservan los sentimientos.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 23 0 0]Los datos y los recuerdos no son lo mismo.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 24 0 0]Una foto no puede capturar nuestros sentimientos. Solo existen en nuestro corazón.[n][w][e]

[msg MSG_012_5_0 [Aigis]]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 25 0 0]Al final, todos tendremos que despedirnos. Un día, nuestros recuerdos desaparecerán.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 26 0 0][f 4 23 0 7 0 25 25]Pero yo soy diferente.[n][w][e]

[msg MSG_013_0_0 [Aigis]]
[f 2 1][bup 7 1 65535 65535 0 0][vp 1 0 0 27 0 0]Pienso mantener vivos los recuerdos de todo el mundo.[n][w][e]
[f 2 1][bup 7 1 65535 65535 0 0][vp 1 0 0 28 0 0]Vuestras experiencias y sentimientos vivirán en mi interior.[n][w][e]
[f 2 1][bup 7 1 65535 65535 0 0][vp 1 0 0 29 0 0]Nunca lo olvidaré. Aunque cambiéis o acabemos separándonos con el tiempo...[n][w][e]

[msg MSG_014_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 30 0 0]A-ay, sí... Mmm...[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 31 0 0]Toma esto.[n][w][e]

[msg MSG_015_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 32 0 0]Es una de las piezas que tuvieron que cambiarme cuando me desmayé en el puente Moonlight.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 33 0 0]Le pedí a Mitsuru que me la enviara.[n][w][e]

[msg MSG_015_3_0 [Aigis]]
[f 2 1][bup 7 3 65535 65535 0 0][vp 1 0 0 34 0 0]La he mantenido oculta hasta hace poco porque me recordaba que no soy más que una máquina.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 35 0 0][f 4 23 0 7 0 25 25]Pero ya no.[n][w][e]

[msg MSG_015_7_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 36 0 0]Ahora, es un símbolo que indica que jamás te olvidaré.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 37 0 0]Es la forma de demostrar mi determinación, y quiero que la tengas tú.[n][w][e]

[msg MSG_016_0_0 [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 38 0 0]Quiero que sepas que mientras siga aquí, nunca te olvidaré.[n][w][e]
[f 2 1][bup 7 0 65535 65535 0 0][vp 1 0 0 39 0 0]No me importa cómo o cuándo llegue tu vida a su fin.[n][w][e]

[msg MSG_016_3_0 [Aigis]]
[f 2 1][bup 7 1 65535 65535 0 0][vp 1 0 0 40 0 0]Cuando llegue ese momento, estaré a tu lado.[n][w][e]
[f 2 1][bup 7 1 65535 65535 0 0][vp 1 0 0 41 0 0]Cada parte de tu ser siempre vivirá en mis recuerdos.[n][w][e]

[msg MSG_016_7_0 [Aigis]]
[f 2 1][bup 7 1 65535 65535 0 0][vp 1 0 0 42 0 0]Soy tu amiga, pero también una máquina que mantendrá vivos tus recuerdos.[n][w][e]
[f 2 1][bup 7 1 65535 65535 0 0][vp 1 0 0 43 0 0]Porque es algo que solo yo puedo hacer.[n][w][e]

[msg MND_017_0_0]
[f 2 1]Aigis esboza una sonrisa muy sincera.[n][w][e]
[f 2 1]Siento un fuerte vínculo con Aigis.[n][w][e]

[msg SYS_018_0_0]
[f 2 1]El vínculo social del Eón ha alcanzado su nivel máximo. ¡Ahora puedes fusionar a [clr 35]Metatrón[clr 27], el sirviente infinito![n][w][e]

[msg MSG_019_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 1 0 0 44 0 0]¡Eh, chavalas! ¡Hemos vuelto![n][w][e]

[msg MSG_020_0_0 [Aigis]]
[f 2 1][bup 7 1 65535 65535 0 0][vp 1 0 0 45 0 0]Ah, hola. ¿Habéis estado juntos?[n][w][e]

[msg MSG_021_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 46 0 0]Nos encontramos en la estación y, bueno, me daba pena dejar a Junpei por ahí solo.[n][w][e]

[msg MSG_022_0_0 [Junpei Iori]]
[f 2 1][bup 3 6 65535 65535 0 0][vp 1 0 0 47 0 0]Ajá. Qué considerada eres.[n][w][e]

[msg MSG_023_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 48 0 0]Je, je. ¿Qué estabais haciendo Aigis y tú?[n][w][e]

[sel SEL_024_0_0 top]
[f 2 1]Echándonos una foto.[e]
[f 2 1]Pues charlando.[e]

[msg MSG_025_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 1 0 0 49 0 0]¿Una foto? ¿Y eso?[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0][vp 1 0 0 50 0 0][f 4 23 0 3 1 25 25]Ah, claro. Ai no estaba cuando nos hicimos la otra.[n][w][e]

[msg MSG_026_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 51 0 0]Llevo un tiempo dándole vueltas a una cosa. ¿De qué habláis normalmente?[n][w][e]

[msg MSG_027_0_0 [Aigis]]
[f 2 1][bup 7 1 65535 65535 0 0][vp 1 0 0 52 0 0]Hoy hemos tenido una conversación muy gratificante sobre las fotografías.[n][w][e]

[msg MSG_028_0_0 [Aigis]]
[f 2 1][bup 7 1 65535 65535 0 0][vp 1 0 0 53 0 0]Ay, ya que estamos todos aquí, ¿por qué no nos echamos una foto?[n][w][e]

[msg MSG_029_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 1 0 0 54 0 0]Buah, ¡todos los de segundo juntos! Venga, dale.[n][w][e]

[msg MSG_030_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 1 0 0 55 0 0]Pero ¿quién la echa? No creo que quepamos los cinco.[n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 56 0 0][f 4 23 0 2 1 25 25]Habrá que turnarse.[n][w][e]

[msg MSG_031_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 57 0 0]Venga, yo echo la primera. ¿Dónde os queréis colocar?[n][w][e]

[msg MND_032_0_0]
[f 2 1]He estado un rato con todo el mundo.[n][w][e]

