[msg MND_001_0_0]
[f 2 1]He jugado al simulador de citas "Instituto de la juventud".[n][w][e]

[msg MND_003_0_0]
[f 2 1]¡Ya lo sé todo sobre el romance y el cortejo![n][w][e]

[msg MND_004_0_0]
[f 2 1]Tras ligarme a las heroínas, ahora entiendo mejor cómo funciona el corazón.[n][w][e]

[msg MND_005_0_0]
[f 2 1]He practicado qué decir y hacer para quedar bien delante de las chicas.[n][w][e]

[msg MND_009_0_0]
[f 2 1]He probado el juego de lucha "Puñetazos a cascoporro".[n][w][e]

[msg MND_011_0_0]
[f 2 1]¡He acabado con incontables enemigos a puñetazos y he demostrado lo fuerte que soy![n][w][e]

[msg MND_012_0_0]
[f 2 1]He lanzado ganchos potentes en el momento ideal y los he derrotado de un golpe.[n][w][e]

[msg MND_013_0_0]
[f 2 1]Derecha, derecha, izquierda, derecha... ¡Gancho! ¡Enemigo destruido![n][w][e]

[msg PFM_015_0_0]
[f 2 1]La [clr 2]fuerza[clr 27] de la Persona equipada ha aumentado en [clr 2]3[clr 27].[n][w][e]

[msg MND_017_0_0]
[f 2 1]He probado el juego de terror "Hospicio de los muertos".[n][w][e]

[msg MND_019_0_0]
[f 2 1]¡Me he mantenido firme y sin miedo ante numerosas hordas de zombis![n][w][e]

[msg MND_020_0_0]
[f 2 1]Los sustos no me han detenido y, con calma, me he deshecho de muchos.[n][w][e]

[msg MND_021_0_0]
[f 2 1]He presenciado momentos horribles, pero he derrotado a mis enemigos uno a uno.[n][w][e]

[msg MND_025_0_0]
[f 2 1]He probado el juego "Carreras a todo trapo".[n][w][e]

[msg MND_027_0_0]
[f 2 1]He superado a todos mis rivales y he sentido que me fusionaba con el viento.[n][w][e]

[msg MND_028_0_0]
[f 2 1]He perfeccionado mis técnicas de conducción y he acabado la carrera como un rayo.[n][w][e]

[msg MND_029_0_0]
[f 2 1]¡He tomado las curvas a toda velocidad y he establecido un nuevo récord de vuelta![n][w][e]

[msg PFM_031_0_0]
[f 2 1]La [clr 2]agilidad[clr 27] de la Persona equipada ha aumentado en [clr 2]3[clr 27].[n][w][e]

[msg MND_033_0_0]
[f 2 1]He probado el juego de preguntas "La respuesta eres tú".[n][w][e]

[msg MND_035_0_0]
[f 2 1]Tras competir contra jugadores de todo Japón, mi conocimiento ha aumentado.[n][w][e]

[msg MND_036_0_0]
[f 2 1]He aprendido de mis respuestas erróneas y he obtenido nuevos conocimientos.[n][w][e]

[msg MND_037_0_0]
[f 2 1]Tras derrotar a los demás con respuestas rápidas, tengo una mayor agilidad mental.[n][w][e]

[msg MND_041_0_0]
[f 2 1]He probado el juego de adivinación "La casa de la suerte de Edgar".[n][w][e]

[msg MND_043_0_0]
[f 2 1]Pese a la dudosa veracidad de sus adivinaciones, el Dr. Edgar ha acertado.[n][w][e]

[msg MND_044_0_0]
[f 2 1]Tras vivir una experiencia mística con las cartas del tarot, mi poder espiritual ha aumentado.[n][w][e]

[msg MND_045_0_0]
[f 2 1]Tras ser testigo de la veracidad de las adivinaciones del Dr. Edgar, mis sentidos se han agudizado.[n][w][e]

[msg PFM_047_0_0]
[f 2 1]La [clr 2]magia[clr 27] de la Persona equipada ha aumentado en [clr 2]3[clr 27].[n][w][e]

[msg MND_NO_UP]
[f 2 1]Parece ser que ya no puedo mejorar más en este campo.[n][w][e]

