[msg MSG_000_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 156 65535 0 0][vp 1 0 0 1 0 0]Ay, qué bien que haya más gente con yukatas.[n][w][e]

[msg MSG_000_5_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 156 65535 0 0][vp 1 0 0 2 0 0]Oye, no llamo demasiado la atención, ¿verdad?[n][w][e]
[f 2 1][bup 6 0 156 65535 0 0][vp 1 0 0 3 0 0]No suelo llevar este tipo de prendas, así que estoy un poco incómoda.[n][w][e]

[sel SEL_001_0_0 top]
[f 2 1]Estás guapísima.[e]
[f 2 1]Ni te rayes.[e]

[msg MSG_002_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 156 65535 0 0][vp 1 0 0 4 0 0][f 5 13 3 15 6]¿T-tú crees?[n][w][e]
[f 2 1][bup 6 11 156 65535 0 0][vp 1 0 0 5 0 0][f 4 23 0 6 1 25 25]Gracias...[n][w][e]

[msg MSG_003_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 156 65535 0 0][vp 1 0 0 6 0 0][f 5 13 3 5 6]Es verdad.[n][w][e]
[f 2 1][bup 6 1 156 65535 0 0][vp 1 0 0 7 0 0]Suelo preocuparme demasiado de lo que piensan los demás.[n][w][e]
[f 2 1][bup 6 1 156 65535 0 0][vp 1 0 0 8 0 0]Gracias.[n][w][e]

[msg MSG_004_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 156 65535 0 0][vp 1 0 0 9 0 0]Con esto puesto me he dado cuenta de que los yukatas son muy ligeros y frescos.[n][w][e]
[f 2 1][bup 6 0 156 65535 0 0][vp 1 0 0 10 0 0]Son perfectos para los veranos húmedos que hay en Japón.[n][w][e]

[msg MSG_004_5_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 156 65535 0 0][vp 1 0 0 11 0 0]El diseño parece muy sencillo a simple vista, pero en realidad son muy elegantes.[n][w][e]

[msg MSG_005_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 4 156 65535 0 0][vp 0 0 0 12 0 0]...[n][w][e]
[f 2 1][bup 6 3 156 65535 0 0][vp 1 0 0 13 0 0][f 4 23 0 6 3 25 25]Ay, lo siento. No es normal hablar de estas cosas en un festival, ¿verdad?[n][w][e]

[msg MSG_006_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 156 65535 0 0][vp 1 0 0 14 0 0]Mmm...[n][w][e]
[f 2 1][bup 6 1 156 65535 0 0][vp 1 0 0 15 0 0][f 4 23 0 6 1 25 25]Anda, si ya es hora de cenar.[n][w][e]
[f 2 1][bup 6 1 156 65535 0 0][vp 1 0 0 16 0 0]Vamos a comer algo de los puestos de comida.[n][w][e]

[msg MSG_007_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 156 65535 0 0][vp 1 0 0 17 0 0]Disculpe, ¿me podría poner una de takoyaki?[n][w][e]

[msg MSG_008_0_0 [Vendedora de takoyaki]]
[f 2 1][vp 1 0 0 18 0 0][f 5 21 0 10]¡Marchando![n][w][e]

[msg MSG_009_0_0 [Vendedora de takoyaki]]
[f 2 1][vp 1 0 0 19 0 0]Aquí tienes, ¡una de takoyaki![n][w][e]
[f 2 1][vp 1 0 0 20 0 0]Te he puesto uno más. ¡Que os aproveche a ti y a tu novia![n][w][e]

[msg MSG_010_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 4 156 65535 1 0][vp 1 0 0 21 0 0]Ah... Mmm, gracias.[n][w][e]

[msg MSG_011_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 156 65535 0 0][vp 1 0 0 22 0 0]Nos ha puesto un takoyaki más.[n][w][e]
[f 2 1][bup 6 1 156 65535 0 0][vp 1 0 0 23 0 0][f 4 23 0 6 1 25 25]Habrá que comérselo, ¿no, [nl]?[n][w][e]

[msg MSG_012_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 4 156 65535 0 0][vp 0 0 0 24 0 0]¡...![n][w][e]

[msg MSG_013_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 156 65535 0 0][vp 1 0 0 25 0 0]Quema mucho para comérmelo de un bocado, pero...[n][w][e]
[f 2 1][bup 6 1 156 65535 0 0][vp 1 0 0 26 0 0]¡Me encanta![n][w][e]

[msg MSG_013_5_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 156 65535 0 0][vp 1 0 0 27 0 0]Sabe igual que el takoyaki de Octopia, ¿verdad?[n][w][e]
[f 2 1][bup 6 0 156 65535 0 0][vp 0 0 0 28 0 0][f 4 23 0 6 0 25 25]...[n][w][e]

[msg MSG_014_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 156 65535 0 0][vp 1 0 0 29 0 0]Oye, ¿crees que será la misma persona?[n][w][e]
[f 2 1][bup 6 0 156 65535 0 0][vp 0 0 0 30 0 0]...[n][w][e]
[f 2 1][bup 6 0 156 65535 0 0][vp 1 0 0 31 0 0]Mmm... A lo mejor son gemelas.[n][w][e]

[msg MSG_015_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 156 65535 0 0][vp 1 0 0 32 0 0]Mira qué máscaras.[n][w][e]

[msg MSG_015_3_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 156 65535 0 0][vp 1 0 0 33 0 0]También hay de animales.[n][w][e]
[f 2 1][bup 6 0 156 65535 0 0][vp 1 0 0 34 0 0][f 4 23 0 6 0 25 25]Un gato, un perro y... ¿un pulpo?[n][w][e]

[msg MSG_015_5_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 156 65535 0 0][vp 1 0 0 35 0 0]Anda, si es una máscara de Hyottoko. Es un hombre, no un animal.[n][w][e]
[f 2 1][bup 6 1 156 65535 0 0][vp 1 0 0 36 0 0]Estas máscaras crean el ambiente del festival, ¿no crees?[n][w][e]

[msg MSG_016_0_0 [Asistente de juego]]
[f 2 1][vp 1 0 0 37 0 0][f 5 21 0 11]¡Eh, vosotras dos! ¿Os gustaría probar suerte?[n][w][e]
[f 2 1][vp 1 0 0 38 0 0][f 5 21 0 11]¡Tendréis un bonito recuerdo! La suerte os sonríe, ¡todavía quedan un montón de premios![n][w][e]

[msg MSG_017_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 156 65535 0 0][vp 1 0 0 39 0 0]Un montón de premios...[n][w][e]
[f 2 1][bup 6 1 156 65535 0 0][vp 1 0 0 40 0 0][f 4 23 0 6 1 25 25]Podríamos probar.[n][w][e]
[f 2 1][bup 6 0 156 65535 0 0][vp 1 0 0 41 0 0]Lo único que yo soy un poco gafe, así que mejor si pruebas tú, [nl].[n][w][e]

[msg MND_018_0_0]
[f 2 1]La caja está llena de papeletas[n]triangulares de la lotería.[n][w][e]

[sel SEL_019_0_0 top]
[f 2 1]Coger uno de arriba[e]
[f 2 1]Meter la mano hasta el fondo[e]

[msg MSG_020_0_0 [Asistente de juego]]
[f 2 1][vp 1 0 0 42 0 0][f 5 21 0 11]¡Enhorabuena! ¡Has ganado![n][w][e]
[f 2 1][vp 1 0 0 43 0 0][f 5 21 0 11]¡Hala! ¡Menuda suerte la tuya para ganar en el primer intento![n][w][e]
[f 2 1][vp 1 0 0 44 0 0][f 5 21 0 11]Aquí tienes tu premio. ¡Disfrútalo![n][w][e]

[msg MND_021_0_0]
[f 2 1]DEV:(Item name) received.[n][w][e]

[msg MSG_022_0_0 [Asistente de juego]]
[f 2 1][vp 1 0 0 45 0 0][f 5 21 0 11]¡Enhorabuena! ¡Has ganado![n][w][e]
[f 2 1][vp 1 0 0 46 0 0][f 5 21 0 11]¡Hala! ¡Menuda suerte la tuya para ganar en el primer intento![n][w][e]
[f 2 1][vp 1 0 0 47 0 0][f 5 21 0 11]Aquí tienes tu premio. ¡Disfrútalo![n][w][e]

[msg MND_023_0_0]
[f 2 1]DEV: (Item name) received.[n][w][e]

[msg MSG_024_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 156 65535 0 0][vp 1 0 0 48 0 0]Anda, ¡si has ganado! ¡Qué guay, [nl]![n][w][e]

[msg MSG_025_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 156 65535 0 0][vp 1 0 0 49 0 0]Llevamos aquí un buen rato.[n][w][e]
[f 2 1][bup 6 1 156 65535 0 0][vp 1 0 0 50 0 0]Deberíamos irnos ya. Gracias por lo de hoy.[n][w][e]

[msg MSG_025_5_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 156 65535 0 0][vp 1 0 0 51 0 0]Es la primera vez que voy a un sitio así.[n][w][e]
[f 2 1][bup 6 1 156 65535 0 0][vp 1 0 0 52 0 0]Me lo he pasado genial.[n][w][e]

[msg MND_026_0_0]
[f 2 1]He decidido volver a la residencia.[n][w][e]

