[msg MND_001_0_0]
[f 2 1]Hay un ordenador en este escritorio. ¿Será de alguien?[n][w][e]

[msg MND_000_0_0]
[f 2 1]Tengo entendido que se puede usar este ordenador.[n][w][e]

[msg SYS_TUTORIAL]
[f 2 1]Se pueden usar distintos programas en este ordenador para pasar el tiempo.[n][w][e]
[f 2 1]El efecto resultante depende de lo que uses.[n][w][e]
[f 2 1]Aunque el ordenador no estará disponible si alguien más lo está usando.[n][w][e]

[msg MND_013_0_0]
[f 2 1]Hay algunos programas preinstalados.[n][w][e]
[f 2 1]Hay un paquete en la estantería con una pegatina que pone: "Se puede coger prestado".[n][w][e]
[f 2 1]¿Debería coger algo prestado?[n][w][e]

[msg MND_014_0_0]
[f 2 1]¿Debería pasar el tiempo en el ordenador?[n][w][e]

[msg MND_003_0_0]
[f 2 1]¿Debería pasar el tiempo en el ordenador?[n][w][e]

[msg MND_004_0_0]
[f 2 1]Este es el ordenador que me dijeron que se puede usar.[n][w][e]
[f 2 1]Aunque ahora mismo no tengo ningún programa.[n][w][e]

[msg MND_UMIUSHI_WEB]
[f 2 1]El catálogo incluía un código de miembro[n]que se puede utilizar en la página oficial.[n][w][e]
[f 2 1]Vamos a ver la web de Umiushi.[n][w][e]

[msg MND_REVENGE_SITE_WEB]
[f 2 1]Que yo recuerde, cerraron esta web.[n][w][e]

[msg MND_022_0_0]
[f 2 1]Hoy es el día de la promesa. Más vale que vaya a la torre Tártaro.[n][w][e]

[msg MND_023_0_0]
[f 2 1]Hay otra persona usando el ordenador ahora.[n][w][e]

[msg MSG_MITSURU_0531 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4136 0 0]¿Eh? ¿Quieres utilizar el ordenador?[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Justo a tiempo. Acabo de terminar mis asuntos. Ya puedes usarlo.[n][w][e]

[msg MND_025_0_0]
[f 2 1]Tengo sueño... Debería acostarme pronto.[n][w][e]

[msg MSG_MITSURU_0429 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4136 0 0]¿Qué ocurre, [nl]? ¿Es que quieres buscar algo?[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Ese ordenador es de uso compartido. El internet ha vuelto, así que aprovéchalo cuando mejor te venga.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Doy fe de su buen rendimiento y capacidad. También puedes instalar programas.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4061 0 0]No obstante, no olvides que es de uso compartido.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Te recomiendo que evites instalar aquí el juego que Iori te dio ayer.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Desconozco los detalles, pero me parece que guarda un registro de las conversaciones privadas.[n][w][e]

[msg MND_033_0_0]
[f 2 1]El arcano de la Templanza podría ayudarme a mejorar todavía más.[n][w][e]

[msg MND_034_0_0]
[f 2 1]Parece que mi [f 4 30 0 1 1 0] ya está al máximo.[n][w][e]
[f 2 1]¿Debería pasar el tiempo en el ordenador?[n][w][e]

[msg MND_035_0_0]
[f 2 1]Parece que mi [f 4 30 1 1 1 0] ya está al máximo.[n][w][e]
[f 2 1]¿Debería pasar el tiempo en el ordenador?[n][w][e]

[msg MND_036_0_0]
[f 2 1]Parece que mi [f 4 30 2 1 1 0] ya está al máximo.[n][w][e]
[f 2 1]¿Debería pasar el tiempo en el ordenador?[n][w][e]

[sel SEL_037_0_0 top]
[f 2 1]Usar ordenador[e]
[f 2 1]Da igual[e]

