[msg MSG_000_0_0 [Bebe]]
[f 2 1][bup 112 1 65535 65535 0 0][vp 3 0 65535 11900 0 0]¡Compré un CD con canciones folclóricas japonesas![n][w][e]
[f 2 1][bup 112 1 65535 65535 0 0]Estas canciones son sencillas, sí, pero tienen mucha historia de su región de origen.[n][w][e]

[msg MSG_001_0_0 [Bebe]]
[f 2 1][bup 112 0 65535 65535 0 0]Ah, hablando de música japonesa...[n][w][e]
[f 2 1][bup 112 0 65535 65535 0 0]Me encanta el sonido que hacen los grillos. Es muy relajante y melódico.[n][w][e]

[msg MSG_002_0_0 [Bebe]]
[f 2 1][bup 112 0 65535 65535 0 0][vp 3 0 65535 11876 0 0]¿A ti también te gusta, [nf]?[n][w][e]

[sel SEL_003_0_0 top]
[f 2 1]Sí, claro.[e]
[f 2 1]La verdad es que no.[e]
[f 2 1]No está mal.[e]

[msg MSG_004_0_0 [Bebe]]
[f 2 1][bup 112 1 65535 65535 0 0][vp 3 0 65535 11895 0 0][f 5 13 15 30 112]¡Lo que yo pensaba! Los grillos son toda una sensación internacional; un éxito mundial.[n][w][e]
[f 2 1][bup 112 1 65535 65535 0 0]Me encantaría que mi tía tuviera la oportunidad de escuchar estos grillos...[n][w][e]

[msg MND_005_0_0]
[f 2 1]Bebe canturrea contento.[n][w][e]
[f 2 1]Siento que hoy nuestra relación se ha estrechado.[n][w][e]

[msg MSG_006_0_0 [Bebe]]
[f 2 1][bup 112 3 65535 65535 0 0][vp 3 0 65535 11904 0 0]¡Anda! ¿No te gusta el sonido que hacen? Qué pena...[n][w][e]

[msg MND_007_0_0]
[f 2 1]Bebe parece decepcionado.[n][w][e]
[f 2 1]Siento que hoy nuestra relación no ha cambiado nada...[n][w][e]

[msg MSG_008_0_0 [Bebe]]
[f 2 1][bup 112 0 65535 65535 0 0][vp 3 0 65535 11839 0 0][f 5 13 15 15 112]¿"No está mal"? ¿Solo eso? ¡Seguro que conoces algún sonido mejor! Mmm...[n][w][e]
[f 2 1][bup 112 1 65535 65535 0 0][f 4 23 0 112 1 25 25]¿Quizás los ruiseñores? ¿O tal vez fuentes de bambú o cigarras? Japón tiene muchos sonidos que son relajantes para el oído.[n][w][e]

[msg MND_009_0_0]
[f 2 1]Bebe parece impresionado.[n][w][e]
[f 2 1]Hoy has aprendido un poco más sobre él.[n][w][e]

[msg MSG_010_0_0 [Bebe]]
[f 2 1][bup 112 0 65535 65535 0 0][vp 3 0 65535 11880 0 0]He tenido una idea buenísima. Recopilaré los bellos sonidos de Japón y se los enviaré a mi tía.[n][w][e]
[f 2 1][bup 112 0 65535 65535 0 0]Debo comprar una cinta de casete para grabar estos sonidos. ¡Vamos, [nf]![n][w][e]

[msg MND_011_0_0]
[f 2 1]Después de ir de compras con Bebe, volví a la residencia.[n][w][e]

