[msg MSG_000_0_0 [Bebe]]
[f 2 1][bup 112 2 65535 65535 0 0][vp 1 0 0 1 0 0]Si me esfuerzo al máximo, ¡conseguiré los mejores resultados![n][w][e]

[msg MSG_000_2_0 [Bebe]]
[f 2 1][bup 112 2 65535 65535 0 0][vp 1 0 0 2 0 0]¡Soy uno con la aguja! ¡Esto lo es todo para mí, subete![n][w][e]

[msg MSG_001_0_0 [Bebe]]
[f 2 1][bup 112 0 65535 65535 0 0][vp 1 0 0 3 0 0]Mm, ¡ese material tan barato se ha transformado radicalmente![n][w][e]

[msg MSG_001_3_0 [Bebe]]
[f 2 1][bup 112 3 65535 65535 0 0][vp 1 0 0 4 0 0]Nunca podría haberlo hecho solo.[n][w][e]
[f 2 1][bup 112 3 65535 65535 0 0][vp 1 0 0 5 0 0]Sin ti, ya estaría de vuelta en mi país.[n][w][e]

[msg MSG_001_5_0 [Bebe]]
[f 2 1][bup 112 1 65535 65535 0 0][vp 1 0 0 6 0 0]Y, gracias a toda tu ayuda, ¡el kimono está casi acabado! ¡Qué bendición![n][w][e]

[sel SEL_002_0_0 top]
[f 2 1]¡Enhorabuena![e]
[f 2 1]¿No echas de menos tu hogar?[e]
[f 2 1]Recuerda que me debes una.[e]

[msg MSG_003_0_0 [Bebe]]
[f 2 1][bup 112 1 65535 65535 0 0][vp 1 0 0 7 0 0][f 5 13 15 5 112]¡Merci beaucoup! ¡Tus amables palabras hacen que me olvide del dolor![n][w][e]

[msg MSG_004_0_0 [Bebe]]
[f 2 1][bup 112 3 65535 65535 0 0][vp 1 0 0 8 0 0][f 5 13 15 15 112]En mi país, sin mi tía... ¡Ya no me queda nada allí![n][w][e]

[msg MSG_004_1_0 [Bebe]]
[f 2 1][bup 112 2 65535 65535 0 0][vp 1 0 0 9 0 0]¡Quiero darme prisa y poner fin a esto, para poder vivir y morir aquí en Nihon![n][w][e]

[msg MND_005_0_0]
[f 2 1]Bebe está muy motivado.[n][w][e]

[msg MSG_006_0_0 [Bebe]]
[f 2 1][bup 112 1 65535 65535 0 0][vp 1 0 0 10 0 0]¡Me encantaría recompensarte![n][w][e]

[msg MSG_006_1_0 [Bebe]]
[f 2 1][bup 112 3 65535 65535 0 0][vp 1 0 0 11 0 0]Si pudiera, ¡te invitaría a un montón de aperitivos japoneses! Pero, por desgracia, no me queda dinero.[n][w][e]

[msg MSG_007_0_0 [Bebe]]
[f 2 1][bup 112 0 65535 65535 0 0][vp 1 0 0 12 0 0]Necesito decirte algo, [nf].[n][w][e]
[f 2 1][bup 112 0 65535 65535 0 0][vp 1 0 0 13 0 0]He conocido a mucha gente desde que vine a Nihon.[n][w][e]

[msg MSG_007_2_0 [Bebe]]
[f 2 1][bup 112 1 65535 65535 0 0][vp 1 0 0 14 0 0]Pero tú has sido la persona más subarashii de todas.[n][w][e]

[msg MSG_008_0_0 [Bebe]]
[f 2 1][bup 112 3 65535 65535 0 0][vp 1 0 0 15 0 0]Si mi tía siguiera viva...[n][w][e]

[msg MSG_008_1_0 [Bebe]]
[f 2 1][bup 112 0 65535 65535 0 0][vp 1 0 0 16 0 0]Le hablaría de lo buena amiga que has resultado ser.[n][w][e]

[msg MND_009_0_0]
[f 2 1]Se nota que Bebe confía en mí de verdad.[n][w][e]
[f 2 1]Tengo la sensación de que estamos estrechando lazos.[n][w][e]

[msg MSG_010_0_0 [Bebe]]
[f 2 1][bup 112 1 65535 65535 0 0][vp 1 0 0 17 0 0]Y ahora, ¡los toques finales para el kimono![n][w][e]

[msg MSG_010_3_0 [Bebe]]
[f 2 1][bup 112 3 65535 65535 0 0][vp 1 0 0 18 0 0]Vale, puede que el cansancio que tengo me esté haciendo alucinar un poco.[n][w][e]
[f 2 1][bup 112 2 65535 65535 0 0][vp 1 0 0 19 0 0][f 4 23 0 1 2 25 25]Pero es la recta final... ¡No puedo rendirme ahora![n][w][e]

[msg MSG_010_5_0 [Bebe]]
[f 2 1][bup 112 0 65535 65535 0 0][vp 1 0 0 20 0 0]Preparados, listos, ¡ya![n][w][e]

[msg MND_011_0_0]
[f 2 1]He pasado el día ayudando a Bebe[n]y he vuelto a la residencia.[n][w][e]

