[msg MSG_000_0_0 [Periodista talentosa]]
[f 2 1][f 5 21 1 402]Hola, jovencita. Oye...[n][w][e]
[f 2 1][f 5 21 1 402]¿Has oído algo sobre ese asunto de que la gente normal y sana cambia de la noche a la mañana?[n][w][e]

[sel SEL_001_0_0 top]
[f 2 1]Pues sí.[e]
[f 2 1]Qué va.[e]

[msg MSG_002_0_0 [Periodista talentosa]]
[f 2 1][f 5 21 1 402]Bueno, no debería de ser sorpresa. No para de salir en la tele.[n][w][e]

[msg MSG_003_0_0 [Periodista talentosa]]
[f 2 1][f 5 21 1 402]¡Eh! ¡No parece que te preocupe en absoluto![n][w][e]
[f 2 1][f 5 21 1 402]¿Cómo es posible que no sepas nada? ¡Si vives aquí![n][w][e]

[msg MSG_004_0_0 [Periodista talentosa]]
[f 2 1][f 5 21 1 402]En el Instituto Gekkoukan han hallado otra víctima de esos misteriosos incidentes.[n][w][e]
[f 2 1][f 5 21 1 402]Como estaba en la entrada principal, ese debe ser el escenario del crimen.[n][w][e]
[f 2 1][f 5 21 1 402]Si atacaron a la víctima en otro lugar, tuvieron que llevarla hasta la entrada principal.[n][w][e]
[f 2 1][f 5 21 1 402]¿Por qué haría algo así el culpable? No tiene ningún sentido.[n][w][e]
[f 2 1][f 5 21 1 402]En cualquier caso, hay muchas probabilidades de que el Gekkoukan esté implicado en este asunto...[n][w][e]

[msg MSG_005_0_0 [Periodista talentosa]]
[f 2 1][f 5 21 1 402]Me están dejando al margen del caso del estudiante del Gekkoukan.[n][w][e]
[f 2 1][f 5 21 1 402]No hubo testigos.[n][w][e]
[f 2 1][f 5 21 1 402]Nadie oyó ni siquiera un grito.[n][w][e]
[f 2 1][f 5 21 1 402]Es como si no hubiera pasado nada... O, como poco, nadie va a admitir que sabe algo.[n][w][e]
[f 2 1][f 5 21 1 402]Le restan importancia diciendo que es un "trágico caso de delincuencia juvenil", pero yo creo que va más allá.[n][w][e]

[msg MSG_006_0_0 [Periodista talentosa]]
[f 2 1][f 5 21 1 402]¡Ha vuelto a ocurrir! ¡El jefe me ha llamado la atención por recabar información![n][w][e]
[f 2 1][f 5 21 1 402]Estaba investigando la relación entre el señor Kirijo y el profesor Ikutsuki, ¡y el jefe me ha pedido que lo deje![n][w][e]
[f 2 1][f 5 21 1 402]Le he preguntado por qué y me ha soltado la típica chorrada de que no proteste.[n][w][e]
[f 2 1][f 5 21 1 402]Pero este patrón es similar al de los incidentes del Gekkoukan.[n][w][e]
[f 2 1][f 5 21 1 402]Detrás de todo esto hay algo más, estoy segura.[n][w][e]

[msg MSG_007_0_0 [Periodista talentosa]]
[f 2 1]Alguien completamente sano sufre una enfermedad mental de un día para otro...[n][w][e]
[f 2 1][f 5 21 1 402]No tiene antecedentes familiares ni tampoco ha sufrido ningún terrible accidente.[n][w][e]
[f 2 1][f 5 21 1 402]Ni siquiera hay similitudes respecto a las anteriores víctimas. Ocurrió en un momento y en un lugar distintos.[n][w][e]
[f 2 1][f 5 21 1 402]Es un misterio de lo más complejo, ¿sabes?[n][w][e]
[f 2 1][f 5 21 1 402]Pero pienso resolverlo. De eso no me cabe duda.[n][w][e]

[msg MSG_008_0_0 [Periodista talentosa]]
[f 2 1][f 5 21 1 402]Tengo entendido que recientemente se está popularizando un movimiento en internet.[n][w][e]
[f 2 1][f 5 21 1 402]Ni idea de cómo se llama, pero hay una persona que está reuniendo a muchos usuarios.[n][w][e]
[f 2 1][f 5 21 1 402]No sé qué se traerá entre manos o por qué lo hará, pero...[n][w][e]
[f 2 1][f 5 21 1 402]No creo que esté exagerando. Ese tipo sabe exactamente lo que está haciendo.[n][w][e]
[f 2 1][f 5 21 1 402]Tal vez debería ver cómo es algún día.[n][w][e]

[msg MSG_009_0_0 [Periodista talentosa]]
[f 2 1]Está totalmente desfasado que los adultos se quejen del aspecto y la conducta de los jóvenes.[n][w][e]
[f 2 1][f 5 21 1 402]Salen artículos sobre lo que está corrompiendo a la juventud estos días hasta de debajo de las piedras.[n][w][e]
[f 2 1][f 5 21 1 402]Pero ese tipo parece que se lo busca.[n][w][e]
[f 2 1][f 5 21 1 402]Hablo de un joven que vi el otro día por la calle mientras trabajaba. Pelo largo, sin camiseta, ¡y tatuajes en los dos brazos![n][w][e]
[f 2 1][f 5 21 1 402]Cuando ves a alguien así, es imposible no pensar en si se está corrompiendo a la juventud.[n][w][e]

[msg MSG_010_0_0 [Periodista talentosa]]
[f 2 1][f 5 21 1 402]El número de víctimas de esos incidentes misteriosos está en alza.[n][w][e]
[f 2 1][f 5 21 1 402]¿Te has dado cuenta del patrón de las víctimas hasta ahora?[n][w][e]
[f 2 1][f 5 21 1 402]Por lo que ha ocurrido hasta el momento, aumentan la semana anterior a cada luna llena.[n][w][e]
[f 2 1][f 5 21 1 402]Después, cuando termina la luna llena, todos desaparecen. Eso es lo único que sabemos por ahora.[n][w][e]
[f 2 1][f 5 21 1 402]Este misterio está vinculado con la luna llena, lo tengo claro...[n][w][e]

[msg MSG_011_0_0 [Periodista talentosa]]
[f 2 1][f 5 21 1 402]Me preocupan esas víctimas de apatía. Si te fijas en lo que está pasando...[n][w][e]
[f 2 1][f 5 21 1 402]Se está extendiendo a todo el país, cada vez con más víctimas.[n][w][e]
[f 2 1][f 5 21 1 402]No me sorprendería que pronto hubiera un gran encuentro político sobre el tema.[n][w][e]

[msg MSG_012_0_0 [Periodista talentosa]]
[f 2 1][f 5 21 1 402]Han cancelado mi investigación sobre la muerte del estudiante del Gekkoukan.[n][w][e]
[f 2 1][f 5 21 1 402]Los superiores han debido de descubrir que estaba investigando sobre el tema.[n][w][e]
[f 2 1][f 5 21 1 402]Los mismos de los que mi jefe no paraba de advertirme.[n][w][e]

[msg MSG_013_0_0 [Periodista talentosa]]
[f 2 1][f 5 21 1 402]Al igual que el misterio no se toma vacaciones, los periodistas tampoco.[n][w][e]
[f 2 1][f 5 21 1 402]Pero creo que estoy cerca de un descubrimiento gordo.[n][w][e]
[f 2 1][f 5 21 1 402]No puedo descansar cuando me falta tan poco.[n][w][e]

[msg MSG_014_0_0 [Periodista talentosa]]
[f 2 1][f 5 21 1 402]Salir a preguntar es el método básico para reunir información, pero en esta ocasión no va demasiado bien.[n][w][e]
[f 2 1][f 5 21 1 402]¿Cómo lo llevas? ¿Has sacado algo en claro del incidente misterioso?[n][w][e]
[f 2 1][f 5 21 1 402]Si tienes información, te puedo recompensar.[n][w][e]

[sel SEL_015_0_0 top]
[f 2 1]No sé nada de nada.[e]
[f 2 1]¿Quién eres, señorita?[e]
[f 2 1]¿Quién eres, señora?[e]

[msg MSG_016_0_0 [Periodista talentosa]]
[f 2 1][f 5 21 1 402]Vaya... Una pena.[n][w][e]
[f 2 1][f 5 21 1 402]Te envuelve una especie de halo de misterio, así que pensé que podrías saber algo.[n][w][e]

[msg MSG_017_0_0 [Periodista talentosa]]
[f 2 1][f 5 21 1 402]¿Acaso no es evidente? Soy periodista.[n][w][e]
[f 2 1][f 5 21 1 402]Pienso llegar al fondo de este asunto y sacarlo a la luz.[n][w][e]

[msg MSG_018_0_0 [Periodista talentosa]]
[f 2 1][f 5 21 1 402]¿Cómo que señora?[n][w][e]
[f 2 1][f 5 21 1 402]Qué raro, no veo a ninguna señora por aquí.[n][w][e]
[f 2 1][f 5 21 1 402]Tan solo a una bella periodista que investiga con valentía los misteriosos incidentes de la ciudad.[n][w][e]

[msg MSG_019_0_0 [Periodista talentosa]]
[f 2 1][f 5 21 1 402]He visto a una chica con un vestido con volantes blancos delante de la estación.[n][w][e]
[f 2 1][f 5 21 1 402]El vestido era bonito y contrastaba genial con su impresionante melena pelirroja.[n][w][e]
[f 2 1][f 5 21 1 402]El estilo "gothic lolita" es difícil que quede bien, pero a ella le iba como anillo al dedo.[n][w][e]
[f 2 1][f 5 21 1 402]A lo mejor podría saludarla si vuelvo a verla.[n][w][e]

[msg MSG_020_0_0 [Periodista talentosa]]
[f 2 1][f 5 21 1 402]Los misteriosos incidentes ocurren a medianoche. Estoy segura de ello.[n][w][e]
[f 2 1][f 5 21 1 402]He estado echando un vistazo y parece que todo ocurre a esa hora.[n][w][e]
[f 2 1][f 5 21 1 402]La gente saludable contrae la apatía a medianoche, y también se llevaron a la primera víctima a medianoche.[n][w][e]
[f 2 1][f 5 21 1 402]Ocurre algo de lo más extraño sobre esa hora.[n][w][e]

[msg MSG_021_0_0 [Periodista talentosa]]
[f 2 1][f 5 21 1 402]Cuando estuve investigando sobre la muerte del señor Kirijo, había algo que me escamaba.[n][w][e]
[f 2 1][f 5 21 1 402]El director del consejo, Shuji Ikutsuki. Lo encontraron muerto el mismo día que al señor Kirijo.[n][w][e]
[f 2 1][f 5 21 1 402]Y lo conocía desde que estaban juntos en el Grupo Kirijo.[n][w][e]
[f 2 1][f 5 21 1 402]Tienen que estar relacionados...[n][w][e]

[msg MSG_022_0_0 [Periodista talentosa]]
[f 2 1][f 5 21 1 402]He investigado a esa gente que está esperando el Fin.[n][w][e]
[f 2 1][f 5 21 1 402]Creo que tiene que ver con las víctimas de esos misteriosos incidentes.[n][w][e]
[f 2 1][f 5 21 1 402]Es decir, que las víctimas de la apatía y esa gente tienen algo en común.[n][w][e]
[f 2 1][f 5 21 1 402]La secta apareció justo cuando todos empezaron a hablar del "fin".[n][w][e]
[f 2 1][f 5 21 1 402]A lo mejor saben algo de esto...[n][w][e]
[f 2 1][f 5 21 1 402]O quizá solo estén usando la situación para amasar seguidores...[n][w][e]

[msg MSG_023_0_0 [Periodista talentosa]]
[f 2 1][f 5 21 1 402]Por truculento que sea un suceso, es esencial preguntar por todos lados si quieres reunir información.[n][w][e]
[f 2 1][f 5 21 1 402]¿Cómo lo llevas? ¿Has sacado algo en claro del incidente misterioso?[n][w][e]

[sel SEL_024_0_0 top]
[f 2 1]Pues no.[e]
[f 2 1]¿Quién eres, señorita?[e]
[f 2 1]¿Quién eres, señora?[e]

[msg MSG_025_0_0 [Periodista talentosa]]
[f 2 1][f 5 21 1 402]Ya... Menuda decepción.[n][w][e]
[f 2 1][f 5 21 1 402]Te envuelve un halo de misterio, así que pensé que podrías saber algo.[n][w][e]

[msg MSG_026_0_0 [Periodista talentosa]]
[f 2 1][f 5 21 1 402]¿Acaso no es evidente? Soy periodista.[n][w][e]
[f 2 1][f 5 21 1 402]Pienso llegar al fondo de este asunto y sacarlo a la luz.[n][w][e]

[msg MSG_027_0_0 [Periodista talentosa]]
[f 2 1]...[n][w][e]

[msg MND_027_5_0]
[f 2 1][f 5 21 1 402]La mujer esboza una sonrisa firme...[n][w][e]

[msg MSG_028_0_0 [Periodista talentosa]]
[f 2 1][f 5 21 1 402]Las víctimas de la apatía no pueden volver a la normalidad.[n][w][e]
[f 2 1][f 5 21 1 402]¿Crees que será así o no?[n][w][e]

[sel SEL_029_0_0 top]
[f 2 1]Cierto es.[e]
[f 2 1]Eso es absurdo.[e]

[msg MSG_030_0_0 [Periodista talentosa]]
[f 2 1][f 5 21 1 402]Eso es lo que cree mucha gente, pero no es verdad.[n][w][e]

[msg MSG_031_0_0 [Periodista talentosa]]
[f 2 1][f 5 21 1 402]¡Tú lo has dicho![n][w][e]

[msg MSG_032_0_0 [Periodista talentosa]]
[f 2 1][f 5 21 1 402]Según los datos obtenidos con el sudor de mi frente, los síntomas varían dependiendo de la persona.[n][w][e]
[f 2 1][f 5 21 1 402]Desmayos, agotamiento, afasia, deterioro mental...[n][w][e]
[f 2 1][f 5 21 1 402]No obstante, hay quienes tienen síntomas más ligeros y ya han vuelto a la normalidad.[n][w][e]

[msg MSG_033_0_0 [Periodista talentosa]]
[f 2 1][f 5 21 1 402]Los entrevistadores no pueden apoyarse solo en fuentes primarias; los testigos también son vitales.[n][w][e]
[f 2 1][f 5 21 1 402]Lo que más me gusta a la hora de recopilar información es la gente tan variopinta con la que me encuentro.[n][w][e]
[f 2 1][f 5 21 1 402]Un ejemplo sería el joven con acento de Kansai con el que hablé el otro día.[n][w][e]
[f 2 1][f 5 21 1 402]¡No es un acento que se oiga a menudo por estos lares![n][w][e]

[msg MSG_034_0_0 [Periodista talentosa]]
[f 2 1][f 5 21 1 402]Mmm. Qué extraño. Las víctimas de aquel incidente siguen aquí...[n][w][e]
[f 2 1][f 5 21 1 402]Normalmente desaparecen después de la luna llena, pero...[n][w][e]
[f 2 1][f 5 21 1 402]¿Habrá cambiado algo y no me he enterado?[n][w][e]
[f 2 1][f 5 21 1 402]En fin, sea como sea, no tiene buena pinta...[n][w][e]

[msg MSG_035_0_0 [Periodista talentosa]]
[f 2 1][f 5 21 1 402]El señor Kirijo ha fallecido. Según fuentes oficiales, ha sido a causa de una enfermedad, pero...[n][w][e]
[f 2 1][f 5 21 1 402]¿Qué periodista sería yo si me trago la versión oficial?[n][w][e]
[f 2 1][f 5 21 1 402]Aquí huele a gato encerrado... Corre el rumor de que podría haber sido un asesinato.[n][w][e]

[msg MSG_036_0_0 [Periodista talentosa]]
[f 2 1][f 5 21 1 402]Han publicado un artículo en una revista sobre el fundador de esa secta.[n][w][e]
[f 2 1][f 5 21 1 402]Si te digo la verdad, a mí no me parece tan interesante.[n][w][e]
[f 2 1][f 5 21 1 402]No es más que un grupito que algunos chavalines se han sacado de la manga.[n][w][e]
[f 2 1][f 5 21 1 402]¿A que sí?[n][w][e]

[msg MSG_037_0_0 [Periodista talentosa]]
[f 2 1][f 5 21 1 402]¡Extra, extra! ¡El origen de los incidentes es el dios de la maldición del santuario![n][w][e]
[f 2 1][f 5 21 1 402]Crees que es una tontería, ¿verdad?[n][w][e]

[sel SEL_038_0_0 top]
[f 2 1]¿Supongo...?[e]
[f 2 1]Para nada.[e]
[f 2 1]A mí me cuadra.[e]

[msg MSG_039_0_0 [Periodista talentosa]]
[f 2 1][f 5 21 1 402]Nuestra revista cubre sucesos de este estilo. Somos una publicación amarillista de tres al cuarto, pero...[n][w][e]
[f 2 1][f 5 21 1 402]Algún día, ¡conseguiré una exclusiva que nos catapulte a la cima![n][w][e]
[f 2 1][f 5 21 1 402]Aunque mi jefe me dice que no pierda el tiempo, que eso es imposible...[n][w][e]

[msg MSG_040_0_0 [Periodista talentosa]]
[f 2 1][f 5 21 1 402]No hace falta que me mientas para intentar animarme.[n][w][e]

[msg MSG_041_0_0 [Periodista talentosa]]
[f 2 1][f 5 21 1 402]Qué gracia.[n][w][e]
[f 2 1][f 5 21 1 402]Y también tienes amplitud de miras... Estoy impresionada.[n][w][e]

[msg MSG_042_0_0 [Periodista talentosa]]
[f 2 1][f 5 21 1 402]Han asesinado a un alumno del Gekkoukan. Mmm...[n][w][e]
[f 2 1][f 5 21 1 402]Un suceso como ese podría estar en los titulares.[n][w][e]
[f 2 1][f 5 21 1 402]Mis jefes me han pedido que reúna información y aquí me tienes... Pero este tipo de casos no son lo mío.[n][w][e]

