[msg MSG_000_0_0 [Alumno que deja el club]]
[f 2 1][f 5 21 1 306]Ah, eres la nueva. ¿Vas a unirte a un club o algo de eso?[n][w][e]

[sel SEL_001_0_0 top]
[f 2 1]Esa es la idea.[e]
[f 2 1]Todavía me lo estoy pensando.[e]

[msg MSG_001_0_0 [Alumno que deja el club]]
[f 2 1][f 5 21 1 306]Ah, ¿sí? Pues tampoco es que puedas unirte al instante. Dicen que ya hay muchos llenos.[n][w][e]
[f 2 1][f 5 21 1 306]Tú estate atenta por si se libera una plaza en alguno. A lo mejor buscan nuevos miembros en abril.[n][w][e]

[msg MSG_002_0_0 [Alumno que deja el club]]
[f 2 1][f 5 21 1 306]Bueno, las actividades de los clubes son un asco. Debes socializar y ser considerada con los demás.[n][w][e]
[f 2 1][f 5 21 1 306]Supongo que sí que sirve para hacer amigos, pero yo solo vengo a disfrutar del insti, ¿me sigues?[n][w][e]

