[sel SEL_BOSS top]
[f 2 1]Todo listo.[e]
[f 2 1]Un momento.[e]

[msg MSG_OPE_STOP_YUKARI [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0]¿Qué pasa? Date prisa y forma un grupo.[n][w][e]

[msg MSG_OPE_STOP_JUNPEI [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0]Colega, ¿qué estás haciendo? ¡Escoge a los miembros del grupo de una vez![n][w][e]

[msg MSG_OPE_STOP_MITSURU [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0]¿Qué estás haciendo, si puede saberse?[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]No tenemos tiempo que perder. Decide quién irá contigo.[n][w][e]

[msg MSG_OPE_STOP_SANADA [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0]¡Eh! ¡¿Adónde te crees que vas?![n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0]Tenemos que salir de aquí lo antes posible. Date prisa y elige a quién irá contigo.[n][w][e]

[msg MSG_OPE_STOP_FUKA [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0]Será peligroso luchar con un grupo tan pequeño. Deberías llevar a más personas contigo.[n][w][e]

[msg MSG_GOTO_OPE [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0]¿Estás lista?[n][w][e]

[msg MSG_FUKA_LETS_GO_01 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0]Vale, cuenta con mi ayuda. Adelante.[n][w][e]

[msg MND_BOOK_SHELF_01]
[f 2 1]Hay muchos volúmenes de enciclopedia puestos en fila.[n][w][e]
[f 2 1]También hay mapas celestes y libros de geología.[n][w][e]

[msg MND_BOOK_SHELF_02]
[f 2 1]Hay muchos archivos con el nombre "Fechas de aparición de sombras".[n][w][e]
[f 2 1]Llevan una etiqueta que dice "No quitar".[n][w][e]

[msg MND_BOOK_SHELF_03]
[f 2 1]En los títulos hay un montón de términos esotéricos que no entiendo.[n][w][e]
[f 2 1]Parece que están relacionados con la psicología y el psicoanálisis.[n][w][e]

[msg MND_NOZOKI_ANYONE1]
[f 2 1]Es una hilera de consolas.[n][w][e]
[f 2 1]No estoy sola en la sala, así que no debería ver los vídeos.[n][w][e]

[msg MND_NOZOKI_ANYONE2]
[f 2 1]Es una hilera de consolas.[n][w][e]
[f 2 1]Parece que una de las cámaras de seguridad se ha encendido y ha grabado un vídeo...[n][w][e]
[f 2 1]Pero no estoy sola en la sala, así que no debería verlo.[n][w][e]

[sel SEL_YESNO top]
[f 2 1]Sí[e]
[f 2 1]No[e]

[msg MSG_OPE_STOP_AEGIS [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0]Decide quién te acompañará al combate.[n][w][e]

[msg MSG_OPE_STOP_AMADA [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0]¿Pasa algo?[n][w][e]
[f 2 1][bup 8 0 65535 65535 0 0]Em... Decide quién irá contigo.[n][w][e]

[msg MSG_FUKA_LETS_GO_02 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0]Muy bien, vámonos.[n][w][e]

[msg MSG_1103_MITURU_01 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0]Bueno, vámonos.[n][w][e]

[msg MSG_1103_IKUTUKI_01 [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0]Muy bien, ten cuidado.[n][w][e]

[msg MSG_1103_MITURU_02 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0]¡Vamos![n][w][e]

[msg MND_WAREHOUSE]
[f 2 1]La puerta está cerrada a cal y canto. Me pregunto si será un almacén...[n][w][e]

[msg MND_CABINET]
[f 2 1]Hay todo tipo de adornos en la estantería.[n][w][e]
[f 2 1]A ambos lados hay fotos de una mujer y de un hombre muy serio...[n][w][e]
[f 2 1]¿Quiénes serán...?[n][w][e]

