[msg MSG_JUNPEI_TARTAROS_0602 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0]Oye, ¿te hace ir a la Tártaro más tarde?[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]El Síndrome de Apatía está en aumento, o algo así, ¿no?[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Además, con todos los rumores que rondan por el insti, me siento inquieto quedándome de brazos cruzados.[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2132 0 0]En momentos como este, lo mejor es despejarse en la Tártaro.[n][w][e]

[msg MSG_JUNPEI_0602 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0]Oye, ¿vamos luego a la Tártaro?[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]El Síndrome de Apatía está en aumento, o algo así, ¿no?[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Con todos esos rumores que rondan por el insti, me siento inquieto quedándome de brazos cruzados...[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2132 0 0]Así que, ¿qué te parece ir a reventar Sombras? Para aliviar el estrés, ¿sabes?[n][w][e]

[msg MSG_JUNPEI_OK_0602 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0]Oye, el Síndrome de Apatía está en aumento, o algo así era, ¿no?[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Con todos esos rumores que rondan por el insti, me siento inquieto quedándome de brazos cruzados...[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]Ja, a ver si nos metemos en otra operación en la que nos pegamos con una Sombra grande y, ¡PAM! Le damos una buena paliza, ¿a que sí?[n][w][e]

[msg MSG_MITSURU_TARTAROS_060 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0]...[nl], ¿me haces un hueco en la agenda mañana?[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Hay mucho que avanzar sobre el caso de Fuuka Yamagishi.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Así que voy a necesitar tu ayuda.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4143 0 0]Si tienes asuntos urgentes, te sugiero que los resuelvas antes de que se acabe el día.[n][w][e]

[msg MSG_YUKARI_TARTAROS_0609 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0]Kirijo y Sanada han ido al hospital a visitar a Yamagishi.[n][w][e]
[f 2 1][bup 2 10 65535 65535 0 0]Me pregunto si estará bien...[n][w][e]

[msg MSG_JUNPEI_TARTAROS_0610 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0]Kirijo y Sanada han ido a visitar a Yamagishi hoy también. Nos quedamos nosotros a la espera en la resi.[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]Me pregunto si vendrá pronto a casa... Ay, Fuuka...[n][w][e]

[msg MSG_YUKARI_TARTAROS_0610 [Yukari Takeba]]
[f 2 1][bup 2 3 65535 65535 0 0][vp 3 0 65535 1076 0 0]Pero no ha dicho nada de unirse a nosotros, ¿verdad?[n][w][e]
[f 2 1][bup 2 3 65535 65535 0 0]Espero que no la estén presionando o algo por el estilo...[n][w][e]

[msg MSG_JUNPEI_TARTAROS_0612 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0]Ah, sí, he oído que Fuuka se muda a uno de los cuartos del tercer piso.[n][w][e]
[f 2 1][bup 3 3 65535 65535 0 0]Pero las chicas me pararon los pies cuando les ofrecí mi ayuda. Dicen que nada de chicos...[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]En fin, parece que llegará aquí mañana temprano. Qué ganitas, ¿eh?[n][w][e]

[msg MSG_SANADA_TARTAROS_0617 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0]¿Y si vamos a la Tártaro después?[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0]Todavía nos queda tiempo hasta la siguiente luna llena, pero los enemigos son cada vez más fuertes.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0]Dicho eso, me gustaría entrenar con Polideuco aún más. ¿Qué te parece?[n][w][e]

[msg MSG_SANADA_OK_0617 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0]Hemos progresado bien por ahora... Pero aún así no podemos bajar la guardia.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0]Aún falta tiempo hasta la siguiente luna llena, pero los enemigos son cada vez más fuertes.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0]Avísame si piensas en ir a la Tártaro. Total, siempre hay que empujar los límites en el entrenamiento.[n][w][e]

[msg MSG_JUNPEI_TARTAROS_0619 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0]Lo siento, me voy corriendo a las tiendas un rato.[n][w][e]

[msg MSG_YUKARI_0622 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0]Oye, ¿te has enterado? Algo le pasa a la maquinaria de la sala de comandos.[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0]Junpei le ha echado un ojo, pero parece que se estropea bastante a menudo, ¿no?[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0]La verdad es que no tengo ni idea de esas cosas. [nl], ¿te importa ir a mirarlo más tarde?[n][w][e]

[msg MSG_MITSURU_TARTAROS_062 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0]Quedan dos semanas para la próxima luna llena. Vamos a entrenar y fortalecernos mientras podamos.[n][w][e]

[msg MSG_JUNPEI_TARTAROS_0623 [Junpei Iori]]
[f 2 1][bup 3 4 65535 65535 0 0][vp 3 0 65535 2098 0 0]Oh, ¡¿se viene otra lucha con un jefe?![n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]Ja, me pregunto contra qué nos enfrentaremos esta vez. No te voy a mentir, me estoy motivando.[n][w][e]

[msg MSG_MITSURU_TARTAROS_062_2 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4122 0 0]......[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Con Akihiko e Iori, no hay manera de tener una conversación seria.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Hablando de Akihiko, ¿todavía no ha vuelto?[n][w][e]

[msg MSG_JUNPEI_TARTAROS_0623_2 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2062 0 0]Supongo que no. ¿Igual ha salido a por algo de comer?[n][w][e]

[msg MSG_SANADA_TARTAROS_0626 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0]Voy a salir esta noche. Volveré bastante tarde.[n][w][e]

[msg MSG_WELCOME_YUKARI_OUT [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 3 0 65535 1019 0 0]Ah, eh... Hola.[n][w][e]

[msg MSG_WELCOME_YUKARI_OUT2 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 3 0 65535 1012 0 0]Eh... Hola...[n][w][e]

[msg MSG_WELCOME_JUNPEI_OUT [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2018 0 0]¿Qué pasa, tía?[n][w][e]

[msg MSG_WELCOME_JUNPEI_OUT2 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2012 0 0]Hola, tía...[n][w][e]

[msg MSG_WELCOME_MITSURU_OUT [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4018 0 0]Hola de nuevo.[n][w][e]

[msg MSG_WELCOME_MITSURU_OUT2 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4027 0 0]Hola de nuevo...[n][w][e]

[msg MSG_WELCOME_SANADA_OUT [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 3 0 65535 3017 0 0]Anda, has vuelto.[n][w][e]

[msg MSG_WELCOME_FUKA_OUT [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5018 0 0]Hola, ¿qué tal el día?[n][w][e]

[msg MSG_WELCOME_FUKA_OUT2 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5028 0 0]Ah... Hola...[n][w][e]

[msg MSG_WELCOME_AEGIS_OUT_RO [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 3 0 65535 6018 0 0]Saludos.[n][w][e]

[msg MSG_WELCOME_AEGIS_OUT [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6018 0 0]Saludos.[n][w][e]

[msg MSG_WELCOME_AEGIS_OUT_NA [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6017 0 0]Hola otra vez. Me alegro de volver a verte.[n][w][e]

[msg MSG_WELCOME_KOROMARU_OUT [Koromaru]]
[f 2 1][bup 9 0 65535 65535 0 0][vp 3 0 65535 8008 0 0]¡Guau![n][w][e]

[msg MSG_WELCOME_AMADA_OUT [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 3 0 65535 7020 0 0]¡Anda, hola![n][w][e]

[msg MSG_WELCOME_AMADA_OUT2 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 3 0 65535 7012 0 0]Ah... Hola...[n][w][e]

[msg MSG_WELCOME_ARAGAKI_OUT [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 3 0 65535 9014 0 0]Ey...[n][w][e]

[msg MSG_WELCOME_IKUTSUKI_OUT [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 3 0 65535 14201 0 0]Hola de nuevo.[n][w][e]

[msg MSG_WELCOME_YUKARI_IN [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 3 0 65535 1067 0 0]¡Ah, estás aquí![n][w][e]

[msg MSG_WELCOME_YUKARI_IN2 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 3 0 65535 1012 0 0]Ah, ¿ya has llegado? Perdona, no te había visto.[n][w][e]

[msg MSG_WELCOME_JUNPEI_IN [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2009 0 0]Eh, ¿qué pasa?[n][w][e]

[msg MSG_WELCOME_JUNPEI_IN2 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2012 0 0]Ah, hola...[n][w][e]

[msg MSG_WELCOME_MITSURU_IN [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4029 0 0]¿Eh? Ah, eres tú...[n][w][e]

[msg MSG_WELCOME_MITSURU_IN2 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4027 0 0]¿Mmm? Ah, ya estás aquí.[n][w][e]

[msg MSG_WELCOME_SANADA_IN [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 3 0 65535 3024 0 0]¿Has estado en tu habitación todo este tiempo?[n][w][e]

[msg MSG_WELCOME_FUKA_IN [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5067 0 0]¡Ah, hola! No sabía que ya estabas aquí.[n][w][e]

[msg MSG_WELCOME_FUKA_IN2 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5093 0 0]Anda, ¿estás aquí? Hola...[n][w][e]

[msg MSG_WELCOME_FUKA_IN_0712 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5067 0 0]Ah, [nl]...[n][w][e]

[msg MSG_WELCOME_AEGIS_IN_ROB [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 3 0 65535 6008 0 0]Buenas tardes.[n][w][e]

[msg MSG_WELCOME_AEGIS_IN [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6008 0 0]Buenas tardes.[n][w][e]

[msg MSG_WELCOME_AEGIS_IN_NAK [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6009 0 0]¿Qué tal el día? ¿Todo bien?[n][w][e]

[msg MSG_WELCOME_KOROMARU_IN [Koromaru]]
[f 2 1][bup 9 0 65535 65535 0 0][vp 3 0 65535 8001 0 0]¡Guau, guau![n][w][e]

[msg MSG_WELCOME_AMADA_IN [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 3 0 65535 7010 0 0]¿Has estudiado algo?[n][w][e]

[msg MSG_WELCOME_AMADA_IN2 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 3 0 65535 7012 0 0]¿Estabas aquí? Pues... hola.[n][w][e]

[msg MSG_WELCOME_ARAGAKI_IN [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 3 0 65535 9056 0 0]... ¿Qué hay?[n][w][e]

[msg MSG_WELCOME_IKUTSUKI_IN [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 3 0 65535 14204 0 0]Ah, no sabía que ya estabas aquí. He venido a hacer una visita rápida.[n][w][e]

[msg MND_SHYUKAKU_OK]
[f 2 1]Ahora que lo pienso, las hortalizas que planté en la azotea ya se podrán recolectar.[n][w][e]
[f 2 1]Debería ir a echarles un ojo...[n][w][e]

[msg MND_SHYUKAKU_TAIYAKI_OK]
[f 2 1]Ahora que lo pienso, las hortalizas que planté en la azotea ya se podrán recolectar.[n][w][e]
[f 2 1]Y el taiyaki que metí en la nevera también debería estar frío.[n][w][e]
[f 2 1]Debería ir a echarles un ojo...[n][w][e]

[msg MND_SHYUKAKU_TAIYAKI_OK_]
[f 2 1]Ahora que lo pienso, las hortalizas que planté en la azotea ya se podrán recolectar.[n][w][e]
[f 2 1]Y el taiyaki que metí en la nevera también debería estar frío.[n][w][e]
[f 2 1]Debería sacarlo de la nevera y dárselo a Elizabeth.[n][w][e]

[msg MND_TAIYAKI_OK]
[f 2 1]Ahora que lo pienso, el taiyaki que metí en la nevera ya debería estar frío.[n][w][e]
[f 2 1]Debería ir a por él.[n][w][e]

[msg MND_TAIYAKI_OK_QUEST]
[f 2 1]Ahora que lo pienso, el taiyaki que metí en la nevera ya debería estar frío.[n][w][e]
[f 2 1]Debería sacarlo de la nevera y dárselo a Elizabeth.[n][w][e]

[msg MSG_ERROR [Shuji Ikutsuki]]
[f 2 1]エラーメッセージです。[n][f 1 5 0]杉山まで報告ください。[n][w][e]

