[msg MSG_002_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 1 0 0 1 0 0][f 4 23 0 1 1 25 25]Vas a tener un sabor estupendo. No dejes de crecer, ¿vale?[n][w][e]

[msg MSG_003_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 1 0 0 2 0 0][f 4 23 0 1 1 25 25]Agh, no es muy grande, ¡pero lo que falta en tamaño lo compensaremos en número![n][w][e]

[msg MSG_004_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 1 0 0 3 0 0][f 4 23 0 1 1 25 25]¡No seáis tímidas, hortalizas mías! ¡Podéis crecer más rápido![n][w][e]

[msg MSG_CHIDORILIVE [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 1 0 0 4 0 0]Las hortalizas son estupendas. Cuando las veo, me hacen pensar en la vida, ¿sabes?[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0][vp 1 0 0 5 0 0][f 4 23 0 1 1 25 25]Sí que te hacen sentir mejor cuando las comes. Igual me llevo alguna que otra el próximo día...[n][w][e]
[f 2 1][bup 3 4 65535 65535 0 0][vp 1 0 0 6 0 0][f 4 23 0 1 4 25 25]Ah, ¡estaba hablando solo![n][w][e]

