[msg MSG_000_0_0 [Voz de profesor]]
[f 2 1][vp 1 0 0 1 0 0]¡Pero mira que eres terco! ¡Pon su nombre en la lista![n][w][e]

[msg MSG_001_0_0 [Voz de Hidetoshi]]
[f 2 1][vp 1 0 0 2 0 0]La presidenta metió a [nl] en el consejo estudiantil. Es una persona responsable.[n][w][e]
[f 2 1][vp 1 0 0 3 0 0]Por eso no está en la lista de sospechosos.[n][w][e]

[msg MSG_002_0_0 [Voz de profesor]]
[f 2 1][vp 1 0 0 4 0 0]Hay testigos que la han visto merodeando por la calle a medianoche.[n][w][e]
[f 2 1][vp 1 0 0 5 0 0]Creía que odiabas a los alumnos que no cumplen las normas.[n][w][e]

[msg MSG_003_0_0 [Voz de Hidetoshi]]
[f 2 1][vp 1 0 0 6 0 0]No dudo de la veracidad del testimonio de los testigos.[n][w][e]
[f 2 1][vp 1 0 0 7 0 0]Pero confío en ella. Por eso no voy a considerarla sospechosa.[n][w][e]

[msg MSG_004_0_0 [Voz de profesor]]
[f 2 1][vp 1 0 0 8 0 0]Te tenía por una persona inteligente, Hidetoshi.[n][w][e]
[f 2 1][vp 1 0 0 9 0 0]Ya puedes olvidarte de nuestro trato.[n][w][e]

[msg MSG_005_0_0 [Voz de Hidetoshi]]
[f 2 1][vp 1 0 0 10 0 0]Entonces, si me disculpa...[n][w][e]

[msg MSG_006_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 3 65535 65535 0 0][vp 1 0 0 11 0 0]Lo habrás oído todo, ¿no?[n][w][e]

[sel SEL_007_0_0 top]
[f 2 1]Yo no he sido.[e]
[f 2 1]¿Me has defendido?[e]

[msg MSG_008_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 1 65535 65535 0 0][vp 1 0 0 12 0 0][f 5 13 5 15 102]Lo sé, no tienes que convencerme.[n][w][e]

[msg MSG_009_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 1 65535 65535 0 0][vp 1 0 0 13 0 0][f 5 13 5 5 102]No he hecho más que expresarme con sinceridad.[n][w][e]

[msg MSG_010_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 2 65535 65535 0 0][vp 1 0 0 14 0 0]El profesor sospecha ni más ni menos que de ti. No sé dónde le habrán regalado el título.[n][w][e]

[msg MSG_010_5_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 15 0 0][f 4 23 0 1 0 25 25]Tranquila. Estoy de tu parte, aunque todo el instituto se vuelva en mi contra.[n][w][e]

[msg MND_011_0_0]
[f 2 1]Parece que Hidetoshi me aprecia mucho.[n][w][e]
[f 2 1]Siento que nos estamos haciendo buenos amigos.[n][w][e]

[msg MSG_012_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 16 0 0]"Estoy de tu parte"... Todo se pega, menos la hermosura.[n][w][e]

[msg MSG_012_5_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 17 0 0]Hasta luego, [nl].[n][w][e]

[msg MND_013_0_0]
[f 2 1]Me he despedido de Hidetoshi y he vuelto a la residencia.[n][w][e]

