[msg MSG_JUNPEI_TARTAROS_1201 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0]Mañana será luna llena... Aunque ya no significa nada.[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Tío, no tengo nada que hacer. Estoy aburridísimo...[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Igual quedo con Ryoji.[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]No le he visto hoy por el instituto, a lo mejor es porque se ha saltado las clases, así que iré a buscarle.[n][w][e]
[f 2 1][bup 3 4 65535 65535 0 0][vp 3 0 65535 2072 0 0]Ah, claro... Si no sé donde vive...[n][w][e]

[msg MSG_FUKA_TARTAROS_1202_1 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0]Esta noche hay luna llena...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Pero no habrá ninguna operación.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Aún así, tenía pensado invocar a Juno y hacer una búsqueda rápida, por si acaso.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Ah, por cierto, ¿has visto a Aigis, [nl]-chan?[n][w][e]

[sel SEL_002_0_0 top]
[f 2 1]No la he visto.[e]
[f 2 1]¿Estará en su habitación?[e]

[msg MSG_FUKA_TARTAROS_1202_2 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5028 0 0]Mm... Últimamente Aigis ha estado volviendo tarde a casa...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]No es normal en ella...[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0]Me pregunto si le habrá pasado algo. Espero que esté bien...[n][w][e]

[msg MSG_JUNPEI_TARTAROS_1204 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2093 0 0][f 4 25 3]......[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0]Ah, oye...[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]O sea... ¿te imaginas que todo lo de ayer no ha sido más que una locura de sueño?[n][w][e]
[f 2 1][bup 3 0 65535 65535 0 0][f 4 25 3]......[n][w][e]
[f 2 1][bup 3 10 65535 65535 0 0][vp 3 0 65535 2056 0 0]Aunque no tiene pinta, ¿verdad...?[n][w][e]

[msg MSG_MITURU_1205_1 [Mitsuru Kirijo]]
[f 2 1][bup 5 10 65535 65535 0 0][vp 3 0 65535 4097 0 0]...Ah, [nl].[n][w][e]

[msg MSG_MITURU_1205_2 [Mitsuru Kirijo]]
[f 2 1][bup 5 10 65535 65535 0 0]Em... ¿Tú crees que...?[n][w][e]
[f 2 1][bup 5 10 65535 65535 0 0][f 4 25 5]......[n][w][e]
[f 2 1][bup 5 10 65535 65535 0 0]No, no he dicho nada. No tiene sentido hacer ese tipo de preguntas...[n][w][e]

[sel SEL_006_0_0 top]
[f 2 1]Así es.[e]
[f 2 1]¿Tienes miedo?[e]

[msg MSG_MITURU_1205_RE_1 [Mitsuru Kirijo]]
[f 2 1][bup 5 10 65535 65535 0 0]Ya...[n][w][e]
[f 2 1][bup 5 10 65535 65535 0 0][vp 3 0 65535 4027 0 0]Lo siento. Olvida que he dicho nada.[n][w][e]

[msg MSG_MITURU_1205_RE_2 [Mitsuru Kirijo]]
[f 2 1][bup 5 10 65535 65535 0 0][vp 3 0 65535 4034 0 0]No, creo que "miedo" no es la palabra correcta. Es que soy incapaz de comprender todo lo que está ocurriendo.[n][w][e]
[f 2 1][bup 5 10 65535 65535 0 0]Pensaba que me había vuelto más fuerte tras lidiar con lo que le pasó a mi padre, pero...[n][w][e]

[msg MSG_SANADA_1206 [Akihiko Sanada]]
[f 2 1][bup 4 3 65535 65535 0 0][vp 3 0 65535 3090 0 0][f 4 25 4]......[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0]Mm...? Ah, eres tú.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0]Perdona, estoy pensativo.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0]...Estaba pensando en qué me diría Shinji en el caso que le volviera a ver algún día.[n][w][e]

[sel SEL_010_0_0 top]
[f 2 1]¿Y qué es lo que te diría?[e]
[f 2 1]¿Le tienes miedo a la muerte?[e]

[msg MSG_SANADA_1206_RE_1 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 3 0 65535 3031 0 0]Creo que no diría nada.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0]Más bien, me soltaría un puñetazo en la cara antes de que ninguno diga palabra.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0]Su derecha es fuerte, así que fijo que dolería.[n][w][e]

[msg MSG_SANADA_1206_RE_2 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 3 0 65535 3061 0 0]¿La muerte, eh...?[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0]Bueno, hablando sobre mi muerte, no soy capaz de hacerme totalmente a la idea.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0]Patético, ¿verdad? Sobretodo considerando la cantidad de veces que he vivido las de otros...[n][w][e]

[msg MSG_FUKA_1207 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][f 4 25 6]......[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]E-Esto...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]¿Qué tal si... intentamos animarnos un poquito?[n][w][e]

[sel SEL_014_0_0 top]
[f 2 1]Pero si yo no estoy triste.[e]
[f 2 1]Buena idea.[e]

[msg MSG_FUKA_1207_RE_1 [Fuuka Yamagishi]]
[f 2 1][bup 6 4 65535 65535 0 0][vp 3 0 65535 5092 0 0]A-ah, entiendo.[n][w][e]
[f 2 1][bup 6 4 65535 65535 0 0]Emm...[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0]Disculpa, [nl]. No debería asumir cosas...[n][w][e]

[msg MSG_FUKA_1207_RE_2 [Fuuka Yamagishi]]
[f 2 1][bup 6 4 65535 65535 0 0][vp 3 0 65535 5067 0 0]Ah, em... Gracias.[n][w][e]
[f 2 1][bup 6 4 65535 65535 0 0][f 4 25 6]......[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0]Lo siento... Creo que soy yo la que peor lo está llevando ahora mismo...[n][w][e]

[msg MSG_YUKARI_1209 [Yukari Takeba]]
[f 2 1][bup 2 10 65535 65535 0 0]Ya ha pasado una semana desde que Ryoji nos ha dado la noticia, ¿no...?[n][w][e]
[f 2 1][bup 2 10 65535 65535 0 0]Estuve tres días sin poder dormir después de eso.[n][w][e]
[f 2 1][bup 2 10 65535 65535 0 0]Es... raro, tener tanto miedo.[n][w][e]

[sel SEL_018_0_0 top]
[f 2 1]Sí, ya te digo.[e]
[f 2 1]El resto también tiene miedo.[e]

[msg MSG_YUKARI_1209_RE_1 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 3 0 65535 1028 0 0]Ya... Creo que ahora estoy siendo consciente...[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0]Nadie se da cuenta de lo mucho que dan sus vidas por sentado...[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0]Hasta que piensan que hay una posibilidad real de perderla.[n][w][e]

[msg MSG_YUKARI_1209_RE_2 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 3 0 65535 1028 0 0]Ya, supongo que tienes razón.[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0]Sabes... Creo que nadie se da cuenta de lo mucho que dan sus vidas por sentado...[n][w][e]
[f 2 1][bup 2 10 65535 65535 0 0]Hasta que piensan que hay una posibilidad real de perderla.[n][w][e]
[f 2 1][bup 2 10 65535 65535 0 0]Creo que la gente no puede comprender cómo se siente eso hasta que lo viven de verdad...[n][w][e]

[msg MSG_SANADA_STUDY_1211 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0]Los exámenes empiezan la semana que viene.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0]Sé que cuesta centrarse, pero no es cuestión de ignorar el presente por estar preocupados por el futuro.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0]Eso sería como rendirse ante la vida. No tiene sentido.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0][vp 3 0 65535 3080 0 0]Por mi parte, voy a continuar como siempre. Seguiré yendo a la torre Tártaro y seguiré con mis estudios.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0]Yo no me salgo del cuadrilátero sin una victoria.[n][w][e]

[msg MSG_FUKA_STUDY_1212 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][nl], no te olvides de que pronto serán los exámenes.[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0]A mí me está costando horrores estudiar. Cuando me quedo sola, mi mente empieza a divagar...[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0]...[nl], ¿te importaría si pudiéramos estudiar juntas?[n][w][e]

[msg MSG_JUNPEI_TARTAROS_1213 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0]Los exámenes empiezan mañana, ¿no?[n][w][e]
[f 2 1][bup 3 10 65535 65535 0 0]Supongo que por una vez voy a usar un examen como excusa para distraerme, jaja...[n][w][e]

[msg MSG_MITURU_1219_1 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0]Después de acabar los exámenes...[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Salí un rato a darme un paseo por la ciudad.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Los Perdidos están por todas partes... Toparte con uno ya deja de ser cuestión de casualidad.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Quizá tenga que ver con la Caída.[n][w][e]

[sel SEL_026_0_0 top]
[f 2 1]Seguramente sea así.[e]
[f 2 1]Tenemos que hacer algo.[e]

[msg MSG_MITURU_1219_RE_1 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4097 0 0]No le he dado muchas vueltas últimamente, pero...[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Somos los únicos que podemos salvar el mundo.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Está en nuestras manos.[n][w][e]

[msg MSG_MITURU_1219_RE_2 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4027 0 0]Sí, estoy de acuerdo.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Debemos continuar explorando la torre Tártaro.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Aunque nuestro oponente se trate de una Sombra o del propio destino, debemos ser fuertes para ganar.[n][w][e]

[msg MSG_YUKARI_TARTAROS_1221 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0]Hoy es 21 de diciembre...[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0]En diez días será Nochevieja.[n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0]Pero, por algún motivo... Ya no siento miedo alguno.[n][w][e]
[f 2 1][bup 2 0 65535 65535 0 0]Bueno, igual "alguno" es exagerar un poco... Pero creo que estoy mucho mejor.[n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0][vp 3 0 65535 1004 0 0]Voy a luchar.[n][w][e]
[f 2 1][bup 2 1 65535 65535 0 0]Si ganaremos o perderemos... No lo sé, pero quiero saber que he hecho todo lo que he podido.[n][w][e]

[msg MSG_AMADA_TARTAROS_1223 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0]Quedan ocho días para Nochevieja...[n][w][e]
[f 2 1][bup 8 0 65535 65535 0 0][nl], ¿tienes decidido qué pensarás hacer?[n][w][e]
[f 2 1][bup 8 0 65535 65535 0 0][vp 3 0 65535 7085 0 0]Porque yo sí. Voy a luchar.[n][w][e]
[f 2 1][bup 8 1 65535 65535 0 0]Le he estado dando muchísimas vueltas, hasta que he caído en que no hay mucho que pensar.[n][w][e]
[f 2 1][bup 8 1 65535 65535 0 0]Me refiero, no voy a ir a mi madre y a Aragaki a decirles que hemos fallado. Así que eso...[n][w][e]

[msg MSG_SANADA_TARTAROS_1225 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0]Pues hoy es 25 de diciembre.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0]Y solo se habla de la "muerte" y el "destino"... Menudas Navidades tan deprimentes.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0]La Navidad será mejor el año que viene.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0][vp 3 0 65535 3061 0 0]Me has oído bien, "el año que viene". No pienso dejar que el mundo se acabe.[n][w][e]

[msg MSG_MITURU_TARTAROS_1226 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0]Se acabó el segundo trimestre... y solo quedan cinco días para Nochevieja.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Si te soy sincera, sigo bastante nerviosa...[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Pero, ya no tengo más dudas.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4080 0 0]Estoy más convencida que nunca.[n][w][e]
[f 2 1][bup 5 0 65535 65535 0 0]Pienso luchar hasta el final.[n][w][e]

[msg MSG_FUKA_TARTAROS_1227 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0]Solo cuatro días más para Nochevieja...[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0]Hasta hace poco estaba muy preocupada, no sabía para nada qué quería hacer...[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0]Incluso llegué a pensar que el miedo me superaría por completo y me volvería incapaz de tomar decisión alguna...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5035 0 0]Pero estaba equivocada.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0]Ahora me siento fuerte...[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0][vp 3 0 65535 5116 0 0]Porque os tengo a todos vosotros.[n][w][e]

[msg MSG_FUKA_TARTAROS_1228 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0]Quedan solamente tres días para Nochevieja.[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0]¿Has podido decidir qué le vas a decir a Ryoji?[n][w][e]

[msg MSG_JUNPEI_TARTAROS_1229 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0]El gran día es pasado mañana. ¿Sabes ya qué decidir?[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]Yo ya lo sé, por fin. Pero vaya si me ha costado llegar a una decisión.[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2132 0 0]Bueno, deberías tomar tu decisión si es que no lo has hecho. ¡No vale cambiar de opinión en el último momento![n][w][e]

[msg MSG_WELCOME_YUKARI_OUT [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 3 0 65535 1019 0 0]Ah, eh... Hola.[n][w][e]

[msg MSG_WELCOME_YUKARI_OUT2 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 3 0 65535 1012 0 0]Eh... Hola...[n][w][e]

[msg MSG_WELCOME_JUNPEI_OUT [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2018 0 0]¿Qué pasa, tía?[n][w][e]

[msg MSG_WELCOME_JUNPEI_OUT2 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2012 0 0]Hola, tía...[n][w][e]

[msg MSG_WELCOME_MITSURU_OUT [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4018 0 0]Hola de nuevo.[n][w][e]

[msg MSG_WELCOME_MITSURU_OUT2 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4027 0 0]Hola de nuevo...[n][w][e]

[msg MSG_WELCOME_SANADA_OUT [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 3 0 65535 3017 0 0]Anda, has vuelto.[n][w][e]

[msg MSG_WELCOME_FUKA_OUT [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5018 0 0]Hola, ¿qué tal el día?[n][w][e]

[msg MSG_WELCOME_FUKA_OUT2 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5028 0 0]Ah... Hola...[n][w][e]

[msg MSG_WELCOME_AEGIS_OUT_RO [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 3 0 65535 6018 0 0]Saludos.[n][w][e]

[msg MSG_WELCOME_AEGIS_OUT [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6018 0 0]Saludos.[n][w][e]

[msg MSG_WELCOME_AEGIS_OUT_NA [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6017 0 0]Hola otra vez. Me alegro de volver a verte.[n][w][e]

[msg MSG_WELCOME_KOROMARU_OUT [Koromaru]]
[f 2 1][bup 9 0 65535 65535 0 0][vp 3 0 65535 8008 0 0]¡Guau![n][w][e]

[msg MSG_WELCOME_AMADA_OUT [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 3 0 65535 7020 0 0]¡Anda, hola![n][w][e]

[msg MSG_WELCOME_AMADA_OUT2 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 3 0 65535 7012 0 0]Ah... Hola...[n][w][e]

[msg MSG_WELCOME_ARAGAKI_OUT [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 3 0 65535 9014 0 0]Ey...[n][w][e]

[msg MSG_WELCOME_IKUTSUKI_OUT [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 3 0 65535 14201 0 0]Hola de nuevo.[n][w][e]

[msg MSG_WELCOME_YUKARI_IN [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 3 0 65535 1067 0 0]¡Ah, estás aquí![n][w][e]

[msg MSG_WELCOME_YUKARI_IN2 [Yukari Takeba]]
[f 2 1][bup 2 0 65535 65535 0 0][vp 3 0 65535 1012 0 0]Ah, ¿ya has llegado? Perdona, no te había visto.[n][w][e]

[msg MSG_WELCOME_JUNPEI_IN [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2009 0 0]Eh, ¿qué pasa?[n][w][e]

[msg MSG_WELCOME_JUNPEI_IN2 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2012 0 0]Ah, hola...[n][w][e]

[msg MSG_WELCOME_MITSURU_IN [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4029 0 0]¿Eh? Ah, eres tú...[n][w][e]

[msg MSG_WELCOME_MITSURU_IN2 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 65535 65535 0 0][vp 3 0 65535 4027 0 0]¿Mmm? Ah, ya estás aquí.[n][w][e]

[msg MSG_WELCOME_SANADA_IN [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 3 0 65535 3024 0 0]¿Has estado en tu habitación todo este tiempo?[n][w][e]

[msg MSG_WELCOME_FUKA_IN [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5067 0 0]¡Ah, hola! No sabía que ya estabas aquí.[n][w][e]

[msg MSG_WELCOME_FUKA_IN2 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5093 0 0]Anda, ¿estás aquí? Hola...[n][w][e]

[msg MSG_WELCOME_FUKA_IN_0712 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5067 0 0]Ah, [nl]...[n][w][e]

[msg MSG_WELCOME_AEGIS_IN_ROB [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 3 0 65535 6008 0 0]Buenas tardes.[n][w][e]

[msg MSG_WELCOME_AEGIS_IN [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6008 0 0]Buenas tardes.[n][w][e]

[msg MSG_WELCOME_AEGIS_IN_NAK [Aigis]]
[f 2 1][bup 7 0 65535 65535 0 0][vp 3 0 65535 6009 0 0]¿Qué tal el día? ¿Todo bien?[n][w][e]

[msg MSG_WELCOME_KOROMARU_IN [Koromaru]]
[f 2 1][bup 9 0 65535 65535 0 0][vp 3 0 65535 8001 0 0]¡Guau, guau![n][w][e]

[msg MSG_WELCOME_AMADA_IN [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 3 0 65535 7010 0 0]¿Has estudiado algo?[n][w][e]

[msg MSG_WELCOME_AMADA_IN2 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 3 0 65535 7012 0 0]¿Estabas aquí? Pues... hola.[n][w][e]

[msg MSG_WELCOME_ARAGAKI_IN [Shinjiro Aragaki]]
[f 2 1][bup 10 0 65535 65535 0 0][vp 3 0 65535 9056 0 0]... ¿Qué hay?[n][w][e]

[msg MSG_WELCOME_IKUTSUKI_IN [Shuji Ikutsuki]]
[f 2 1][bup 222 0 65535 65535 0 0][vp 3 0 65535 14204 0 0]Ah, no sabía que ya estabas aquí. He venido a hacer una visita rápida.[n][w][e]

[msg MND_SHYUKAKU_OK]
[f 2 1]Ahora que lo pienso, las hortalizas que planté en la azotea ya se podrán recolectar.[n][w][e]
[f 2 1]Debería ir a echarles un ojo...[n][w][e]

[msg MND_SHYUKAKU_TAIYAKI_OK]
[f 2 1]Ahora que lo pienso, las hortalizas que planté en la azotea ya se podrán recolectar.[n][w][e]
[f 2 1]Y el taiyaki que metí en la nevera también debería estar frío.[n][w][e]
[f 2 1]Debería ir a echarles un ojo...[n][w][e]

[msg MND_SHYUKAKU_TAIYAKI_OK_]
[f 2 1]Ahora que lo pienso, las hortalizas que planté en la azotea ya se podrán recolectar.[n][w][e]
[f 2 1]Y el taiyaki que metí en la nevera también debería estar frío.[n][w][e]
[f 2 1]Debería sacarlo de la nevera y dárselo a Elizabeth.[n][w][e]

[msg MND_TAIYAKI_OK]
[f 2 1]Ahora que lo pienso, el taiyaki que metí en la nevera ya debería estar frío.[n][w][e]
[f 2 1]Debería ir a por él.[n][w][e]

[msg MND_TAIYAKI_OK_QUEST]
[f 2 1]Ahora que lo pienso, el taiyaki que metí en la nevera ya debería estar frío.[n][w][e]
[f 2 1]Debería sacarlo de la nevera y dárselo a Elizabeth.[n][w][e]

[msg MSG_ERROR [Shuji Ikutsuki]]
[f 2 1]エラーメッセージです。[n][f 1 5 0]杉山まで報告ください。[n][w][e]

