[sel SEL_BATTLE top]
[f 2 1]Vamos.[e]
[f 2 1]Un momento.[e]

[msg MSG_VS_LEADER_BATTLE_OK [Fuuka Yamagishi]]
[f 2 1][bup 6 2 65535 65535 0 0][vp 3 0 65535 5128 0 0]Nos está esperando. La única manera de librarnos de él es luchando.[n][w][e]

[msg MSG_NOT_ENOUGH [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 50 0 0]¡Es demasiado peligroso ir sin más gente![n][w][e]

[msg MSG_008_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0]Entendido, ¡vamos![n][w][e]

[msg MSG_009_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0]Vamos a asegurarnos de que estamos preparados antes de continuar.[n][w][e]

[msg MSG_010_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5003 0 0]¿Estás lista?[n][w][e]

[msg MSG_Ask_NotFull_VoiceOn [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 3 0 65535 5003 0 0]Aún queda hueco en tu grupo. ¿Seguro que quieres continuar?[n][w][e]

[msg MSG_011_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 2 65535 65535 0 0][vp 3 0 65535 4033 0 0]Que no te entren las dudas. Es lo mínimo que podemos hacer.[n][w][e]
[f 2 1][bup 5 2 65535 65535 0 0]No podemos mirar atrás.[n][w][e]

[msg MSG_Ask_Full_VoiceOff [Fuuka Yamagishi]]
[f 2 1][bup 6 2 65535 65535 0 0]¿Estás lista?[n][w][e]

[msg MSG_Ask_NotFull_VoiceOff [Fuuka Yamagishi]]
[f 2 1][bup 6 2 65535 65535 0 0]Aún queda hueco en tu grupo. ¿Seguro que quieres continuar?[n][w][e]

