[msg MSG_000_0_0 [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 1 0 0]Menudo enigma...[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 2 0 0]Las plantas parecen mucho más alegres que cuando empezamos.[n][w][e]

[msg MSG_001_0_0 [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 3 0 0]¿Crees que se alegran de que las cuides?[n][w][e]

[sel SEL_002_0_0 top]
[f 2 1]Eso creo.[e]
[f 2 1]Imposible.[e]
[f 2 1]¿Por qué no preguntas?[e]

[msg MSG_003_0_0 [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 4 0 0][f 5 13 22 1 7]Fascinante... No poseo información al respecto, pero parece que las entiendes.[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 5 0 0]Hola, plantas. Hoy también os voy a cuidar yo. No os preocupéis, me aseguraré de disminuir la presión.[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 6 0 0][f 4 21 1 10]Pero si os duele, levantad la mano izquierda... Digo, la hoja izquierda.[n][w][e]

[msg MSG_004_0_0 [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 7 0 0][f 5 13 22 1 7]Eso pensaba yo también.[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 8 0 0]Sin embargo, hay estudios que indican que las plantas crecen más sanas cuando se les habla.[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 9 0 0]A lo mejor poseen alguna habilidad que desconocemos.[n][w][e]

[msg MSG_005_0_0 [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 10 0 0][f 5 13 22 1 7]Buena idea. Probaré.[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 11 0 0]Hola, hola. Soy Aigis. Plantas, si me oís, responded, por favor.[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0][vp 0 0 0 12 0 0]...[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 13 0 0]Por desgracia, no he obtenido respuesta.[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 14 0 0]La comunicación será difícil con mis habilidades actuales. He de tenerlo en cuenta de cara al futuro.[n][w][e]

[msg MSG_006_0_0 [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 15 0 0]Tenía conocimientos previos sobre plantas, pero esta es la primera vez que las observo directamente.[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 16 0 0]Las semillas y los brotes de la tierra se transforman y cambian muy rápido.[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 17 0 0]¿Eso también demuestra que están vivas? Fascinante.[n][w][e]

[msg MSG_007_0_0 [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 18 0 0]Me gustaría ver cómo crecen las plantas, documentarlo y registrar mi experiencia.[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 19 0 0][f 4 21 7 7]¡Las cuidaré con tesón![n][w][e]

[msg MND_008_0_0]
[f 2 1]He regado las plantas con Aigis.[n][w][e]

[msg MSG_009_0_0 [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 20 0 0]Tarda más de lo que había previsto.[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 21 0 0]Tendré que ejecutar más simulaciones para asegurarme de que no se produzcan más retrasos.[n][w][e]

[msg MND_010_0_0]
[f 2 1]Las hemos cuidado con tanto mimo que darán buen fruto.[n][w][e]

[msg MSG_011_0_0 [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 22 0 0]Qué tarde es. Deberíamos volver.[n][w][e]

[msg MSG_012_0_0 [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 23 0 0]Estaba pensando que...[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 24 0 0]Las plantas parecen mucho más alegres ahora que cuando empezamos a cuidarlas.[n][w][e]

[msg MSG_013_0_0 [Aigis]]
[f 2 1][bup 7 1 202 65535 0 0][vp 1 0 0 25 0 0][f 4 23 0 7 1 25 25]¿Crees que se alegran de que las cuides, [nf]?[n][w][e]

[sel SEL_014_0_0 top]
[f 2 1]Es posible.[e]
[f 2 1]Ni loco.[e]
[f 2 1]¿Y si preguntas?[e]

[msg MSG_015_0_0 [Aigis]]
[f 2 1][bup 7 1 202 65535 0 0][vp 1 0 0 26 0 0][f 5 13 22 1 7]Sí, las tratas con mucha delicadeza. Está claro que te preocupas por ellas.[n][w][e]
[f 2 1][bup 7 1 202 65535 0 0][vp 1 0 0 27 0 0]Seguro que saben que te esfuerzas.[n][w][e]
[f 2 1][bup 7 1 202 65535 0 0][vp 1 0 0 28 0 0]Yo también haré todo lo posible para hacerlas felices.[n][w][e]

[msg MSG_016_0_0 [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 29 0 0][f 4 23 0 7 0 25 25][f 5 13 22 1 7]Estoy de acuerdo, pero por eso me parece tan raro.[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 30 0 0]Dicen que hablar con las plantas las ayuda a crecer, ¿no?[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 31 0 0]¿Crees que las plantas también tienen corazón y todavía no lo sabemos?[n][w][e]

[msg MSG_017_0_0 [Aigis]]
[f 2 1][bup 7 1 202 65535 0 0][vp 1 0 0 32 0 0][f 5 13 22 1 7]Estaría muy bien...[n][w][e]
[f 2 1][bup 7 1 202 65535 0 0][vp 1 0 0 33 0 0]A lo mejor las plantas tienen corazón y aún no lo sabemos.[n][w][e]
[f 2 1][bup 7 1 202 65535 0 0][vp 1 0 0 34 0 0]Si seguimos cuidándolas, ¿las entenderemos mejor?[n][w][e]

[msg MSG_018_0_0 [Aigis]]
[f 2 1][bup 7 1 202 65535 0 0][vp 1 0 0 35 0 0][f 4 23 0 7 1 25 25]Observarlas me ayuda a reflexionar.[n][w][e]
[f 2 1][bup 7 1 202 65535 0 0][vp 1 0 0 36 0 0]Las plantas son igual que tú y que los demás. También están vivas.[n][w][e]

[msg MSG_019_0_0 [Aigis]]
[f 2 1][bup 7 1 202 65535 0 0][vp 1 0 0 37 0 0]Quiero verlas crecer con mis propios ojos.[n][w][e]
[f 2 1][bup 7 1 202 65535 0 0][vp 1 0 0 38 0 0][f 4 21 7 7]Así que haré todo lo que esté en mi mano para cuidarlas.[n][w][e]

[msg MND_020_0_0]
[f 2 1]He regado las plantas con Aigis.[n][w][e]

[msg MSG_021_0_0 [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 39 0 0][f 4 21 7 11]Lo siento. Es la primera vez que hago esto y creo que te he entretenido.[n][w][e]
[f 2 1][bup 7 1 202 65535 0 0][vp 1 0 0 40 0 0][f 4 23 0 7 1 25 25]Seguiré practicando en mi habitación para ser más rápida a la próxima.[n][w][e]

[msg MND_022_0_0]
[f 2 1]Las hemos cuidado con tanto mimo que darán buen fruto.[n][w][e]

[msg MSG_023_0_0 [Aigis]]
[f 2 1][bup 7 1 202 65535 0 0][vp 1 0 0 41 0 0]Gracias por tu ayuda. Vámonos.[n][w][e]

[msg MSG_024_0_0 [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 42 0 0]Parece que las plagas han causado menos daños de lo que había previsto.[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 43 0 0]No hemos tomado medidas contra ellas. ¿A qué se deberá?[n][w][e]

[msg MSG_025_0_0 [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 44 0 0]¿Eh? Esto es...[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 45 0 0]¡Mira, [nf]! ¡Una larva de mariquita! Es pequeñísima, qué mona.[n][w][e]

[sel SEL_026_0_0 top]
[f 2 1]Matémosla.[e]
[f 2 1]Déjala.[e]
[f 2 1]No me la acerques.[e]

[msg MSG_027_0_0 [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 46 0 0]No, ni pensarlo.[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 47 0 0]Las mariquitas se alimentan de las plagas que dañan las plantas.[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 48 0 0]Por eso estarán creciendo tan sanas.[n][w][e]

[msg MSG_028_0_0 [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 49 0 0]Estoy de acuerdo. Mejor no interrumpirla mientras come.[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 50 0 0]Las mariquitas se alimentan de las plagas que dañan las plantas.[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 51 0 0]Por eso no hay insectos dañinos cerca.[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 52 0 0]Muchas gracias, mariquita.[n][w][e]

[msg MSG_029_0_0 [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 53 0 0]Te has puesto blanca. No te va a morder, tranquila.[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 54 0 0]La moveré a otra hoja.[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0][vp 0 0 0 55 0 0]...[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 56 0 0]No se queda quieta.[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 57 0 0]Parece que la mariquita prefiere estar cerca de ti, [nf].[n][w][e]

[msg MSG_030_0_0 [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 58 0 0]Con lo pequeños que son los maceteros y la cantidad de vida que albergan...[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 59 0 0]Nadie les enseña nada. Solo lo hacen lo mejor que pueden.[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0][vp 0 0 0 60 0 0]...[n][w][e]

[msg MSG_031_0_0 [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 61 0 0]Perdona, me he distraído. Continuemos.[n][w][e]

[msg MND_032_0_0]
[f 2 1]He regado las plantas con Aigis.[n][w][e]

[msg MSG_033_0_0 [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 62 0 0]Perdona, [nf]. Echa el repelente en aquel extremo, por favor.[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 63 0 0]Las plagas no merecen piedad.[n][w][e]

[msg MND_034_0_0]
[f 2 1]Las hemos cuidado con tanto mimo que darán buen fruto.[n][w][e]

[msg MSG_035_0_0 [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 64 0 0][f 5 13 22 1 7]Todo está en perfecto estado. No se detectan problemas.[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 65 0 0]Pues ya está, aquí concluye la misión de hoy. Deberíamos volver.[n][w][e]

[msg MSG_036_0_0 [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 66 0 0]Menos mal, las plagas han causado menos daños de lo que esperaba.[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 67 0 0]Pero no hemos tomado medidas de ningún tipo. ¿Qué estará pasando?[n][w][e]

[msg MSG_037_0_0 [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 68 0 0]¿Eh? Esto es...[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 69 0 0]¡Mira, [nf]! ¡Una larva de mariquita! Es pequeñísima, qué mona.[n][w][e]

[sel SEL_038_0_0 top]
[f 2 1]Matémosla.[e]
[f 2 1]Déjala.[e]
[f 2 1]No me la acerques.[e]

[msg MSG_039_0_0 [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 70 0 0]¡No, ni pensarlo![n][w][e]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 71 0 0]Las mariquitas se alimentan de las plagas que dañan las plantas.[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 72 0 0]Por eso no hay insectos dañinos cerca.[n][w][e]

[msg MSG_040_0_0 [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 73 0 0]Sí, mejor no interrumpirla mientras come.[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 74 0 0]Las mariquitas se alimentan de las plagas que dañan las plantas.[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 75 0 0]Por eso no hay insectos dañinos cerca.[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 76 0 0]Muchas gracias, mariquita.[n][w][e]

[msg MSG_041_0_0 [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 77 0 0]¿Te incomodan los insectos? La moveré a otra hoja.[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0][vp 0 0 0 78 0 0]...[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 79 0 0]No se queda quieta.[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 80 0 0]Parece que la mariquita prefiere estar cerca de ti, [nf].[n][w][e]

[msg MSG_042_0_0 [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 81 0 0]Con lo pequeños que son los maceteros y la cantidad de vida que albergan...[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 82 0 0]Nadie les enseña nada. Solo lo hacen lo mejor que pueden.[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0][vp 0 0 0 83 0 0]...[n][w][e]

[msg MSG_043_0_0 [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 84 0 0]Perdona, me he distraído. ¿Seguimos?[n][w][e]

[msg MND_044_0_0]
[f 2 1]He regado las plantas con Aigis.[n][w][e]

[msg MSG_045_0_0 [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 85 0 0]Anda, mira, [nf]...[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 86 0 0]No me gusta interferir, pero no podemos permitir que destruyan las plantas.[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 87 0 0]Ayudemos un poco a la mariquita.[n][w][e]

[msg MND_046_0_0]
[f 2 1]Las hemos cuidado con tanto mimo que darán buen fruto.[n][w][e]

[msg MSG_047_0_0 [Aigis]]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 88 0 0][f 5 13 22 1 7]Todo está en perfecto estado. No se detectan problemas.[n][w][e]
[f 2 1][bup 7 0 202 65535 0 0][vp 1 0 0 89 0 0]Bueno, pues hoy ya hemos terminado. Es hora de volver.[n][w][e]

[msg MSG_048_0_0 [Aigis]]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 1 0 0]Menudo enigma...[n][w][e]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 2 0 0]Las plantas parecen mucho más alegres que cuando empezamos.[n][w][e]

[msg MSG_049_0_0 [Aigis]]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 3 0 0]¿Crees que se alegran de que las cuides?[n][w][e]

[sel SEL_050_0_0 top]
[f 2 1]Eso creo.[e]
[f 2 1]Imposible.[e]
[f 2 1]¿Por qué no preguntas?[e]

[msg MSG_051_0_0 [Aigis]]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 4 0 0][f 5 13 22 1 7]Fascinante... No poseo información al respecto, pero parece que las entiendes.[n][w][e]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 5 0 0]Hola, plantas. Hoy también os voy a cuidar yo. No os preocupéis, me aseguraré de disminuir la presión.[n][w][e]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 6 0 0][f 4 21 1 10]Pero si os duele, levantad la mano izquierda... Digo, la hoja izquierda.[n][w][e]

[msg MSG_052_0_0 [Aigis]]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 7 0 0][f 5 13 22 1 7]Eso pensaba yo también.[n][w][e]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 8 0 0]Sin embargo, hay estudios que indican que las plantas crecen más sanas cuando se les habla.[n][w][e]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 9 0 0]A lo mejor poseen alguna habilidad que desconocemos.[n][w][e]

[msg MSG_053_0_0 [Aigis]]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 10 0 0][f 5 13 22 1 7]Buena idea. Probaré.[n][w][e]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 11 0 0]Hola, hola. Soy Aigis. Plantas, si me oís, responded, por favor.[n][w][e]
[f 2 1][bup 7 0 2 65535 0 0][vp 0 0 0 12 0 0]...[n][w][e]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 13 0 0]Por desgracia, no he obtenido respuesta.[n][w][e]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 14 0 0]La comunicación será difícil con mis habilidades actuales. He de tenerlo en cuenta de cara al futuro.[n][w][e]

[msg MSG_054_0_0 [Aigis]]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 15 0 0]Tenía conocimientos previos sobre plantas, pero esta es la primera vez que las observo directamente.[n][w][e]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 16 0 0]Las semillas y los brotes de la tierra se transforman y cambian muy rápido.[n][w][e]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 17 0 0]¿Eso también demuestra que están vivas? Fascinante.[n][w][e]

[msg MSG_055_0_0 [Aigis]]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 18 0 0]Me gustaría ver cómo crecen las plantas, documentarlo y registrar mi experiencia.[n][w][e]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 19 0 0][f 4 21 7 7]¡Las cuidaré con tesón![n][w][e]

[msg MND_056_0_0]
[f 2 1]He regado las plantas con Aigis.[n][w][e]

[msg MSG_057_0_0 [Aigis]]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 20 0 0]Tarda más de lo que había previsto.[n][w][e]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 21 0 0]Tendré que ejecutar más simulaciones para asegurarme de que no se produzcan más retrasos.[n][w][e]

[msg MND_058_0_0]
[f 2 1]Las hemos cuidado con tanto mimo que darán buen fruto.[n][w][e]

[msg MSG_059_0_0 [Aigis]]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 22 0 0]Qué tarde es. Deberíamos volver.[n][w][e]

[msg MSG_060_0_0 [Aigis]]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 23 0 0]Estaba pensando que...[n][w][e]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 24 0 0]Las plantas parecen mucho más alegres ahora que cuando empezamos a cuidarlas.[n][w][e]

[msg MSG_061_0_0 [Aigis]]
[f 2 1][bup 7 1 2 65535 0 0][vp 1 0 0 25 0 0][f 4 23 0 7 1 25 25]¿Crees que se alegran de que las cuides, [nf]?[n][w][e]

[sel SEL_062_0_0 top]
[f 2 1]Es posible.[e]
[f 2 1]Imposible.[e]
[f 2 1]¿Por qué no preguntas?[e]

[msg MSG_063_0_0 [Aigis]]
[f 2 1][bup 7 1 2 65535 0 0][vp 1 0 0 26 0 0][f 5 13 22 1 7]Sí, las tratas con mucha delicadeza. Está claro que te preocupas por ellas.[n][w][e]
[f 2 1][bup 7 1 2 65535 0 0][vp 1 0 0 27 0 0]Seguro que saben que te esfuerzas.[n][w][e]
[f 2 1][bup 7 1 2 65535 0 0][vp 1 0 0 28 0 0]Yo también haré todo lo posible para hacerlas felices.[n][w][e]

[msg MSG_064_0_0 [Aigis]]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 29 0 0][f 4 23 0 7 0 25 25][f 5 13 22 1 7]Estoy de acuerdo, pero por eso me parece tan raro.[n][w][e]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 30 0 0]Dicen que hablar con las plantas las ayuda a crecer, ¿no?[n][w][e]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 31 0 0]A lo mejor las plantas tienen corazón y aún no lo sabemos.[n][w][e]

[msg MSG_065_0_0 [Aigis]]
[f 2 1][bup 7 1 2 65535 0 0][vp 1 0 0 32 0 0][f 5 13 22 1 7] Estaría muy bien...[n][w][e]
[f 2 1][bup 7 1 2 65535 0 0][vp 1 0 0 33 0 0]A lo mejor las plantas tienen corazón y aún no lo sabemos.[n][w][e]
[f 2 1][bup 7 1 2 65535 0 0][vp 1 0 0 34 0 0]Si seguimos cuidándolas, ¿las entenderemos mejor?[n][w][e]

[msg MSG_066_0_0 [Aigis]]
[f 2 1][bup 7 1 2 65535 0 0][vp 1 0 0 35 0 0][f 4 23 0 7 1 25 25]Observarlas me ayuda a reflexionar.[n][w][e]
[f 2 1][bup 7 1 2 65535 0 0][vp 1 0 0 36 0 0]Las plantas son igual que tú y que los demás. También están vivas.[n][w][e]

[msg MSG_067_0_0 [Aigis]]
[f 2 1][bup 7 1 2 65535 0 0][vp 1 0 0 37 0 0]Quiero verlas crecer con mis propios ojos.[n][w][e]
[f 2 1][bup 7 1 2 65535 0 0][vp 1 0 0 38 0 0][f 4 21 7 7]Así que haré todo lo que esté en mi mano para cuidarlas.[n][w][e]

[msg MND_068_0_0]
[f 2 1]He regado las plantas con Aigis.[n][w][e]

[msg MSG_069_0_0 [Aigis]]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 39 0 0][f 4 21 7 11]Lo siento. Es la primera vez que hago esto y creo que te he entretenido.[n][w][e]
[f 2 1][bup 7 1 2 65535 0 0][vp 1 0 0 40 0 0][f 4 23 0 7 1 25 25]Seguiré practicando en mi habitación para ser más rápida a la próxima.[n][w][e]

[msg MND_070_0_0]
[f 2 1]Las hemos cuidado con tanto mimo que darán buen fruto.[n][w][e]

[msg MSG_071_0_0 [Aigis]]
[f 2 1][bup 7 1 2 65535 0 0][vp 1 0 0 41 0 0]Gracias por tu ayuda. Vámonos.[n][w][e]

[msg MSG_072_0_0 [Aigis]]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 42 0 0]Parece que las plagas han causado menos daños de lo que había previsto.[n][w][e]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 43 0 0]No hemos tomado medidas contra ellas. ¿A qué se deberá?[n][w][e]

[msg MSG_073_0_0 [Aigis]]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 44 0 0]¿Eh? Esto es...[n][w][e]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 45 0 0]¡Mira, [nf]! ¡Una larva de mariquita! Es pequeñísima, qué mona.[n][w][e]

[sel SEL_074_0_0 top]
[f 2 1]Matémosla.[e]
[f 2 1]Déjala.[e]
[f 2 1]No me la acerques.[e]

[msg MSG_075_0_0 [Aigis]]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 46 0 0]No, ni pensarlo.[n][w][e]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 47 0 0]Las mariquitas se alimentan de las plagas que dañan las plantas.[n][w][e]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 48 0 0]Por eso estarán creciendo tan sanas.[n][w][e]

[msg MSG_076_0_0 [Aigis]]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 49 0 0]Estoy de acuerdo. Mejor no interrumpirla mientras come.[n][w][e]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 50 0 0]Las mariquitas se alimentan de las plagas que dañan las plantas.[n][w][e]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 51 0 0]Por eso no hay insectos dañinos cerca.[n][w][e]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 52 0 0]Muchas gracias, mariquita.[n][w][e]

[msg MSG_077_0_0 [Aigis]]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 53 0 0]Te has puesto blanca. No te va a morder, tranquila.[n][w][e]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 54 0 0]La moveré a otra hoja.[n][w][e]
[f 2 1][bup 7 0 2 65535 0 0][vp 0 0 0 55 0 0]...[n][w][e]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 56 0 0]No se queda quieta.[n][w][e]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 57 0 0]Parece que la mariquita prefiere estar cerca de ti, [nf].[n][w][e]

[msg MSG_078_0_0 [Aigis]]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 58 0 0]Con lo pequeños que son los maceteros y la cantidad de vida que albergan...[n][w][e]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 59 0 0]Nadie les enseña nada. Solo lo hacen lo mejor que pueden.[n][w][e]
[f 2 1][bup 7 0 2 65535 0 0][vp 0 0 0 60 0 0]...[n][w][e]

[msg MSG_079_0_0 [Aigis]]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 61 0 0]Perdona, me he distraído. Continuemos.[n][w][e]

[msg MND_080_0_0]
[f 2 1]He regado las plantas con Aigis.[n][w][e]

[msg MSG_081_0_0 [Aigis]]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 62 0 0]Perdona, [nf]. Echa el repelente en aquel extremo, por favor.[n][w][e]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 63 0 0]Las plagas no merecen piedad.[n][w][e]

[msg MND_082_0_0]
[f 2 1]Las hemos cuidado con tanto mimo que darán buen fruto.[n][w][e]

[msg MSG_083_0_0 [Aigis]]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 64 0 0][f 5 13 22 1 7]Todo está en perfecto estado. No se detectan problemas.[n][w][e]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 65 0 0]Pues ya está, aquí concluye la misión de hoy. Deberíamos volver.[n][w][e]

[msg MSG_084_0_0 [Aigis]]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 66 0 0]Menos mal, las plagas han causado menos daños de lo que esperaba.[n][w][e]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 67 0 0]Pero no hemos tomado medidas de ningún tipo. ¿Qué estará pasando?[n][w][e]

[msg MSG_085_0_0 [Aigis]]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 68 0 0]¿Eh? Esto es...[n][w][e]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 69 0 0]¡Mira, [nf]! ¡Una larva de mariquita! Es pequeñísima, qué mona.[n][w][e]

[sel SEL_086_0_0 top]
[f 2 1]Matémosla.[e]
[f 2 1]Déjala.[e]
[f 2 1]No me la acerques.[e]

[msg MSG_087_0_0 [Aigis]]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 70 0 0]¡No, ni pensarlo![n][w][e]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 71 0 0]Las mariquitas se alimentan de las plagas que dañan las plantas.[n][w][e]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 72 0 0]Por eso no hay insectos dañinos cerca.[n][w][e]

[msg MSG_088_0_0 [Aigis]]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 73 0 0]Sí, mejor no interrumpirla mientras come.[n][w][e]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 74 0 0]Las mariquitas se alimentan de las plagas que dañan las plantas.[n][w][e]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 75 0 0]Por eso no hay insectos dañinos cerca.[n][w][e]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 76 0 0]Muchas gracias, mariquita.[n][w][e]

[msg MSG_089_0_0 [Aigis]]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 77 0 0]¿Te incomodan los insectos? La moveré a otra hoja.[n][w][e]
[f 2 1][bup 7 0 2 65535 0 0][vp 0 0 0 78 0 0]...[n][w][e]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 79 0 0]No se queda quieta.[n][w][e]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 80 0 0]Parece que la mariquita prefiere estar cerca de ti, [nf].[n][w][e]

[msg MSG_090_0_0 [Aigis]]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 81 0 0]Con lo pequeños que son los maceteros y la cantidad de vida que albergan...[n][w][e]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 82 0 0]Nadie les enseña nada. Solo lo hacen lo mejor que pueden.[n][w][e]
[f 2 1][bup 7 0 2 65535 0 0][vp 0 0 0 83 0 0]...[n][w][e]

[msg MSG_091_0_0 [Aigis]]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 84 0 0]Perdona, me he distraído. ¿Seguimos?[n][w][e]

[msg MND_092_0_0]
[f 2 1]He regado las plantas con Aigis.[n][w][e]

[msg MSG_093_0_0 [Aigis]]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 85 0 0]Anda, mira, [nf]...[n][w][e]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 86 0 0]No me gusta interferir, pero no podemos permitir que destruyan las plantas.[n][w][e]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 87 0 0]Ayudemos un poco a la mariquita.[n][w][e]

[msg MND_094_0_0]
[f 2 1]Las hemos cuidado con tanto mimo que darán buen fruto.[n][w][e]

[msg MSG_095_0_0 [Aigis]]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 88 0 0][f 5 13 22 1 7]Todo está en perfecto estado. No se detectan problemas.[n][w][e]
[f 2 1][bup 7 0 2 65535 0 0][vp 1 0 0 89 0 0]Bueno, pues hoy ya hemos terminado. Es hora de volver.[n][w][e]

[msg MSG_247_0_0 [Aigis]]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 1 0 0]Menudo enigma...[n][w][e]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 2 0 0]Las plantas parecen mucho más alegres que cuando empezamos.[n][w][e]

[msg MSG_248_0_0 [Aigis]]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 3 0 0]¿Crees que se alegran de que las cuides?[n][w][e]

[sel SEL_249_0_0 top]
[f 2 1]Eso creo.[e]
[f 2 1]Imposible.[e]
[f 2 1]¿Por qué no preguntas?[e]

[msg MSG_252_0_0 [Aigis]]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 4 0 0][f 5 13 22 1 7]Fascinante... No poseo información al respecto, pero parece que las entiendes.[n][w][e]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 5 0 0]Hola, plantas. Hoy también os voy a cuidar yo. No os preocupéis, me aseguraré de disminuir la presión.[n][w][e]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 6 0 0][f 4 21 1 10]Pero si os duele, levantad la mano izquierda... Digo, la hoja izquierda.[n][w][e]

[msg MSG_256_0_0 [Aigis]]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 7 0 0][f 5 13 22 1 7]Eso pensaba yo también.[n][w][e]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 8 0 0]Sin embargo, hay estudios que indican que las plantas crecen más sanas cuando se les habla.[n][w][e]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 9 0 0]A lo mejor poseen alguna habilidad que desconocemos.[n][w][e]

[msg MSG_259_0_0 [Aigis]]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 10 0 0][f 5 13 22 1 7]Buena idea. Probaré.[n][w][e]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 11 0 0]Hola, hola. Soy Aigis. Plantas, si me oís, responded, por favor.[n][w][e]
[f 2 1][bup 7 0 6 65535 0 0][vp 0 0 0 12 0 0]...[n][w][e]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 13 0 0]Por desgracia, no he obtenido respuesta.[n][w][e]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 14 0 0]La comunicación será difícil con mis habilidades actuales. He de tenerlo en cuenta de cara al futuro.[n][w][e]

[msg MSG_263_0_0 [Aigis]]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 15 0 0]Tenía conocimientos previos sobre plantas, pero esta es la primera vez que las observo directamente.[n][w][e]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 16 0 0]Las semillas y los brotes de la tierra se transforman y cambian muy rápido.[n][w][e]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 17 0 0]¿Eso también demuestra que están vivas? Fascinante.[n][w][e]

[msg MSG_265_0_0 [Aigis]]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 18 0 0]Me gustaría ver cómo crecen las plantas, documentarlo y registrar mi experiencia.[n][w][e]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 19 0 0][f 4 21 7 7]¡Las cuidaré con tesón![n][w][e]

[msg MND_267_0_0]
[f 2 1]He regado las plantas con Aigis.[n][w][e]

[msg MSG_269_0_0 [Aigis]]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 20 0 0]Tarda más de lo que había previsto.[n][w][e]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 21 0 0]Tendré que ejecutar más simulaciones para asegurarme de que no se produzcan más retrasos.[n][w][e]

[msg MND_270_0_0]
[f 2 1]Las hemos cuidado con tanto mimo que darán buen fruto.[n][w][e]

[msg MSG_271_0_0 [Aigis]]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 22 0 0]Qué tarde es. Deberíamos volver.[n][w][e]

[msg MSG_277_0_0 [Aigis]]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 23 0 0]Estaba pensando que...[n][w][e]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 24 0 0]Las plantas parecen mucho más alegres ahora que cuando empezamos a cuidarlas.[n][w][e]

[msg MSG_278_0_0 [Aigis]]
[f 2 1][bup 7 1 6 65535 0 0][vp 1 0 0 25 0 0][f 4 23 0 7 1 25 25]¿Crees que se alegran de que las cuides, [nf]?[n][w][e]

[sel SEL_279_0_0 top]
[f 2 1]Es posible.[e]
[f 2 1]Imposible.[e]
[f 2 1]¿Por qué no preguntas?[e]

[msg MSG_282_0_0 [Aigis]]
[f 2 1][bup 7 1 6 65535 0 0][vp 1 0 0 26 0 0][f 5 13 22 1 7]Sí, las tratas con mucha delicadeza. Está claro que te preocupas por ellas.[n][w][e]
[f 2 1][bup 7 1 6 65535 0 0][vp 1 0 0 27 0 0]Seguro que saben que te esfuerzas.[n][w][e]
[f 2 1][bup 7 1 6 65535 0 0][vp 1 0 0 28 0 0]Yo también haré todo lo posible para hacerlas felices.[n][w][e]

[msg MSG_285_0_0 [Aigis]]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 29 0 0][f 4 23 0 7 0 25 25][f 5 13 22 1 7]Estoy de acuerdo, pero por eso me parece tan raro.[n][w][e]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 30 0 0]Dicen que hablar con las plantas las ayuda a crecer, ¿no?[n][w][e]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 31 0 0]A lo mejor las plantas tienen corazón y aún no lo sabemos.[n][w][e]

[msg MSG_288_0_0 [Aigis]]
[f 2 1][bup 7 1 6 65535 0 0][vp 1 0 0 32 0 0][f 5 13 22 1 7]Estaría muy bien...[n][w][e]
[f 2 1][bup 7 1 6 65535 0 0][vp 1 0 0 33 0 0]A lo mejor las plantas tienen corazón y aún no lo sabemos.[n][w][e]
[f 2 1][bup 7 1 6 65535 0 0][vp 1 0 0 34 0 0]Si seguimos cuidándolas, ¿las entenderemos mejor?[n][w][e]

[msg MSG_292_0_0 [Aigis]]
[f 2 1][bup 7 1 6 65535 0 0][vp 1 0 0 35 0 0][f 4 23 0 7 1 25 25]Observarlas me ayuda a reflexionar.[n][w][e]
[f 2 1][bup 7 1 6 65535 0 0][vp 1 0 0 36 0 0]Las plantas son igual que tú y que los demás. También están vivas.[n][w][e]

[msg MSG_294_0_0 [Aigis]]
[f 2 1][bup 7 1 6 65535 0 0][vp 1 0 0 37 0 0]Quiero verlas crecer con mis propios ojos.[n][w][e]
[f 2 1][bup 7 1 6 65535 0 0][vp 1 0 0 38 0 0][f 4 21 7 7]Así que haré todo lo que esté en mi mano para cuidarlas.[n][w][e]

[msg MND_296_0_0]
[f 2 1]He regado las plantas con Aigis.[n][w][e]

[msg MSG_298_0_0 [Aigis]]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 39 0 0][f 4 21 7 11]Lo siento. Es la primera vez que hago esto y creo que te he entretenido.[n][w][e]
[f 2 1][bup 7 1 6 65535 0 0][vp 1 0 0 40 0 0][f 4 23 0 7 1 25 25]Seguiré practicando en mi habitación para ser más rápida a la próxima.[n][w][e]

[msg MND_299_0_0]
[f 2 1]Las hemos cuidado con tanto mimo que darán buen fruto.[n][w][e]

[msg MSG_300_0_0 [Aigis]]
[f 2 1][bup 7 1 6 65535 0 0][vp 1 0 0 41 0 0]Gracias por tu ayuda. Vámonos.[n][w][e]

[msg MSG_305_0_0 [Aigis]]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 42 0 0]Menos mal, las plagas han causado menos daños de lo que esperaba.[n][w][e]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 43 0 0]No hemos tomado medidas contra ellas. ¿A qué se deberá?[n][w][e]

[msg MSG_307_0_0 [Aigis]]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 44 0 0]¿Eh? Esto es...[n][w][e]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 45 0 0]¡Mira, [nf]! ¡Una larva de mariquita! Es pequeñísima, qué mona.[n][w][e]

[sel SEL_308_0_0 top]
[f 2 1]Matémosla.[e]
[f 2 1]Déjala.[e]
[f 2 1]No me la acerques.[e]

[msg MSG_311_0_0 [Aigis]]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 46 0 0]No, ni pensarlo.[n][w][e]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 47 0 0]Las mariquitas se alimentan de las plagas que dañan las plantas.[n][w][e]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 48 0 0]Por eso estarán creciendo tan sanas.[n][w][e]

[msg MSG_313_0_0 [Aigis]]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 49 0 0]Estoy de acuerdo. Mejor no interrumpirla mientras come.[n][w][e]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 50 0 0]Las mariquitas se alimentan de las plagas que dañan las plantas.[n][w][e]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 51 0 0]Por eso no hay insectos dañinos cerca.[n][w][e]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 52 0 0]Muchas gracias, mariquita.[n][w][e]

[msg MSG_318_0_0 [Aigis]]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 53 0 0]Te has puesto blanca. No te va a morder, tranquila.[n][w][e]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 54 0 0]La moveré a otra hoja.[n][w][e]
[f 2 1][bup 7 0 6 65535 0 0][vp 0 0 0 55 0 0]...[n][w][e]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 56 0 0]No se queda quieta.[n][w][e]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 57 0 0]Parece que la mariquita prefiere estar cerca de ti, [nf].[n][w][e]

[msg MSG_323_0_0 [Aigis]]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 58 0 0]Con lo pequeños que son los maceteros y la cantidad de vida que albergan...[n][w][e]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 59 0 0]Nadie les enseña nada. Solo lo hacen lo mejor que pueden.[n][w][e]
[f 2 1][bup 7 0 6 65535 0 0][vp 0 0 0 60 0 0]...[n][w][e]

[msg MSG_324_0_0 [Aigis]]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 61 0 0]Perdona, me he distraído. Continuemos.[n][w][e]

[msg MND_326_0_0]
[f 2 1]He regado las plantas con Aigis.[n][w][e]

[msg MSG_328_0_0 [Aigis]]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 62 0 0]Perdona, [nf]. Echa el repelente en aquel extremo, por favor.[n][w][e]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 63 0 0]Las plagas no merecen piedad.[n][w][e]

[msg MND_329_0_0]
[f 2 1]Las hemos cuidado con tanto mimo que darán buen fruto.[n][w][e]

[msg MSG_330_0_0 [Aigis]]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 64 0 0][f 5 13 22 1 7]Todo está en perfecto estado. No se detectan problemas.[n][w][e]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 65 0 0]Pues ya está, aquí concluye la misión de hoy. Deberíamos volver.[n][w][e]

[msg MSG_332_0_0 [Aigis]]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 66 0 0]Menos mal, las plagas han causado menos daños de lo que esperaba.[n][w][e]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 67 0 0]Pero no hemos tomado medidas de ningún tipo. ¿Qué estará pasando?[n][w][e]

[msg MSG_335_0_0 [Aigis]]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 68 0 0]¿Eh? Esto es...[n][w][e]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 69 0 0]¡Mira, [nf]! ¡Una larva de mariquita! Es pequeñísima, qué mona.[n][w][e]

[sel SEL_336_0_0 top]
[f 2 1]Matémosla.[e]
[f 2 1]Déjala.[e]
[f 2 1]No me la acerques.[e]

[msg MSG_339_0_0 [Aigis]]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 70 0 0]¡No, ni pensarlo![n][w][e]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 71 0 0]Las mariquitas se alimentan de las plagas que dañan las plantas.[n][w][e]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 72 0 0]Por eso no hay insectos dañinos cerca.[n][w][e]

[msg MSG_342_0_0 [Aigis]]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 73 0 0]Sí, mejor no interrumpirla mientras come.[n][w][e]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 74 0 0]Las mariquitas se alimentan de las plagas que dañan las plantas.[n][w][e]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 75 0 0]Por eso no hay insectos dañinos cerca.[n][w][e]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 76 0 0]Muchas gracias, mariquita.[n][w][e]

[msg MSG_346_0_0 [Aigis]]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 77 0 0]¿Te incomodan los insectos? La moveré a otra hoja.[n][w][e]
[f 2 1][bup 7 0 6 65535 0 0][vp 0 0 0 78 0 0]...[n][w][e]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 79 0 0]No se queda quieta.[n][w][e]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 80 0 0]Parece que la mariquita prefiere estar cerca de ti, [nf].[n][w][e]

[msg MSG_351_0_0 [Aigis]]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 81 0 0]Con lo pequeños que son los maceteros y la cantidad de vida que albergan...[n][w][e]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 82 0 0]Nadie les enseña nada. Solo lo hacen lo mejor que pueden.[n][w][e]
[f 2 1][bup 7 0 6 65535 0 0][vp 0 0 0 83 0 0]...[n][w][e]

[msg MSG_352_0_0 [Aigis]]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 84 0 0]Perdona, me he distraído. ¿Seguimos?[n][w][e]

[msg MND_354_0_0]
[f 2 1]He regado las plantas con Aigis.[n][w][e]

[msg MSG_356_0_0 [Aigis]]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 85 0 0]Anda, mira, [nf]...[n][w][e]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 86 0 0]No me gusta interferir, pero no podemos permitir que destruyan las plantas.[n][w][e]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 87 0 0]Ayudemos un poco a la mariquita.[n][w][e]

[msg MND_357_0_0]
[f 2 1]Las hemos cuidado con tanto mimo que darán buen fruto.[n][w][e]

[msg MSG_358_0_0 [Aigis]]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 88 0 0][f 5 13 22 1 7]Todo está en perfecto estado. No se detectan problemas.[n][w][e]
[f 2 1][bup 7 0 6 65535 0 0][vp 1 0 0 89 0 0]Bueno, pues hoy ya hemos terminado. Es hora de volver.[n][w][e]

