[msg MSG_000_0_0 [Presidente Tanaka]]
[f 2 1][bup 113 1 65535 65535 0 0][vp 1 0 0 1 0 0][f 4 23 0 1 1 25 25]Tengo la agenda tan apretada que no me suele dar tiempo a tratar con chavales normales, ¿sabes?[n][w][e]
[f 2 1][bup 113 0 65535 65535 0 0][vp 1 0 0 2 0 0][f 4 23 0 1 0 25 25]Deberías agradecer ser una chica tan guapa.[n][w][e]

[msg MSG_000_5_0 [Presidente Tanaka]]
[f 2 1][bup 113 1 65535 65535 0 0][vp 1 0 0 3 0 0][f 4 23 0 1 1 25 25]Muy bien, hoy vamos a añadir una nueva palabra a nuestro vocabulario. ¡Repite conmigo![n][w][e]
[f 2 1][bup 113 1 65535 65535 0 0][vp 1 0 0 4 0 0][f 4 23 0 1 1 25 25]"Placebo". Es una palabra llana.[n][w][e]

[sel SEL_001_0_0 top]
[f 2 1]"Placebo".[e]
[f 2 1]...[e]

[msg MSG_002_0_0 [Presidente Tanaka]]
[f 2 1][bup 113 1 65535 65535 0 0][vp 1 0 0 5 0 0][f 4 23 0 1 1 25 25][f 5 13 16 15 113]¡Muy bien! ¡Finges bien el interés![n][w][e]

[msg MSG_003_0_0 [Presidente Tanaka]]
[f 2 1][bup 113 1 65535 65535 0 0][vp 1 0 0 6 0 0][f 4 23 0 1 1 25 25][f 5 13 16 5 113]Sí, ¡me gusta esa mirada apasionada! ¡No se puede triunfar en la vida sin incredulidad![n][w][e]

[msg MSG_004_0_0 [Presidente Tanaka]]
[f 2 1][bup 113 0 65535 65535 0 0][vp 1 0 0 7 0 0][f 4 23 0 1 0 25 25]Un placebo es una pastilla "de mentira". En pocas palabras, una medicina para calmarte.[n][w][e]

[msg MSG_004_5_0 [Presidente Tanaka]]
[f 2 1][bup 113 1 65535 65535 0 0][vp 1 0 0 8 0 0][f 4 23 0 1 1 25 25]¡Imagina un suplemento para eliminar esos antiestéticos michelines sin mover un dedo![n][w][e]
[f 2 1][bup 113 1 65535 65535 0 0][vp 1 0 0 9 0 0][f 4 23 0 1 1 25 25]O un GPS para el coche que ponga imágenes en tiempo real para que el viaje sea más fácil... o que al menos lo parezca.[n][w][e]

[msg MSG_004_7_0 [Presidente Tanaka]]
[f 2 1][bup 113 1 65535 65535 0 0][vp 1 0 0 10 0 0][f 4 23 0 1 1 25 25]¡Eso es solo una parte de nuestra línea de productos única![n][w][e]

[sel SEL_005_0_0 top]
[f 2 1]Hala.[e]
[f 2 1]Pero ¿eso se vende?[e]

[msg MSG_006_0_0 [Presidente Tanaka]]
[f 2 1][bup 113 0 65535 65535 0 0][vp 1 0 0 11 0 0][f 4 23 0 1 0 25 25][f 5 13 16 5 113]¿Tanto te impresionan nuestros productos fraudulentos?[n][w][e]
[f 2 1][bup 113 3 65535 65535 0 0][vp 1 0 0 12 0 0][f 4 23 0 1 3 25 25]Supongo que son bastante espectaculares...[n][w][e]

[msg MSG_007_0_0 [Presidente Tanaka]]
[f 2 1][bup 113 1 65535 65535 0 0][vp 1 0 0 13 0 0][f 4 23 0 1 1 25 25][f 5 13 16 5 113]Pues claro que sí. De hecho, ¡vendo sin parar![n][w][e]

[msg MSG_008_0_0 [Presidente Tanaka]]
[f 2 1][bup 113 0 65535 65535 0 0][vp 1 0 0 14 0 0][f 4 23 0 1 0 25 25]Nuestro negocio no proporciona beneficios tangibles, sino tranquilidad.[n][w][e]

[msg MSG_008_3_0 [Presidente Tanaka]]
[f 2 1][bup 113 0 65535 65535 0 0][vp 1 0 0 15 0 0][f 4 23 0 1 0 25 25]Fíjate en los suministros de emergencia. La gente se siente segura solo por tenerlos, ¿no es así?[n][w][e]
[f 2 1][bup 113 1 65535 65535 0 0][vp 1 0 0 16 0 0][f 4 23 0 1 1 25 25]Resulta que, cuanto más dinero gastan, mejor se sienten.[n][w][e]

[msg MSG_008_5_0 [Presidente Tanaka]]
[f 2 1][bup 113 0 65535 65535 0 0][vp 1 0 0 17 0 0][f 4 23 0 1 0 25 25]¡Muy bien! Hasta aquí la lección de hoy. Puedes pagarme cuando ganes tu primer millón.[n][w][e]

[msg MND_009_0_0]
[f 2 1]He recibido un consejo un tanto[n]cuestionable del presidente Tanaka.[n][w][e]
[f 2 1]Ahora lo comprendo un poco mejor.[n][w][e]

[msg SYS_010_0_0]
[f 2 1]DEV: Unused[n][w][e]

[msg MSG_011_0_0 [Presidente Tanaka]]
[f 2 1][bup 113 0 65535 65535 0 0][vp 1 0 0 18 0 0][f 4 23 0 1 0 25 25]¿Has cumplido tu promesa? No se lo has dicho a nadie, ¿verdad?[n][w][e]
[f 2 1][bup 113 2 65535 65535 0 0][vp 1 0 0 19 0 0][f 4 23 0 1 2 25 25]Si faltas a tu palabra, colgaré tu foto en una página para ligar.[n][w][e]

[msg MND_012_0_0]
[f 2 1]Se está haciendo tarde, así que he vuelto a la residencia.[n][w][e]

