[msg MSG_000_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 2 65535 65535 0 0][vp 1 0 0 1 0 0]Pero ¿cómo os lo tengo que explicar? Es como hablar con la pared...[n][w][e]

[msg MSG_001_0_0 [Vicepresidenta]]
[f 2 1][vp 1 0 0 2 0 0][f 5 21 0 1001]¿Y por qué me acusas a mí? La colilla estaba en el baño de los chicos, ¿no?[n][w][e]

[msg MSG_002_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 2 65535 65535 0 0][vp 1 0 0 3 0 0]¿Puedes demostrar que no la dejó allí una chica?[n][w][e]

[msg MSG_003_0_0 [Secretario]]
[f 2 1][vp 1 0 0 4 0 0][f 5 21 0 1002]¡Con ese argumento, esto no va a acabar nunca![n][w][e]
[f 2 1][vp 1 0 0 5 0 0][f 5 21 0 1002]Qué hartura. Ahí te quedas.[n][w][e]

[msg MSG_004_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 2 65535 65535 0 0][vp 1 0 0 6 0 0]Vaya panda de trogloditas.[n][w][e]

[sel SEL_005_0_0 top]
[f 2 1]Son lo peor.[e]
[f 2 1]No deberías acusar a cualquiera.[e]

[msg MSG_006_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 7 0 0][f 5 13 5 15 102]No se lo tengas en cuenta. Son como niños; no pueden evitarlo.[n][w][e]

[msg MSG_007_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 1 65535 65535 0 0][vp 1 0 0 8 0 0]Tarde o temprano, verán la luz. Me ganaré su confianza y aprenderán a respetarme.[n][w][e]

[msg MSG_008_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 2 65535 65535 0 0][vp 1 0 0 9 0 0]Espero que no estés cediendo a la presión de grupo, [nl].[n][w][e]

[msg MSG_009_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 2 65535 65535 0 0][vp 1 0 0 10 0 0]Una máquina bien engrasada posee la fuerza de su engranaje más débil.[n][w][e]

[msg MSG_010_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 2 65535 65535 0 0][vp 1 0 0 11 0 0]No es mi intención aislarme; solo me distancio. En toda relación siempre hay alguien que sale herido.[n][w][e]

[msg MSG_010_5_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 3 65535 65535 0 0][vp 1 0 0 12 0 0][f 4 23 0 1 3 25 25]Supongo que me he colado. Lo siento.[n][w][e]

[msg MND_011_0_0]
[f 2 1]Hidetoshi parece estar avergonzado.[n][w][e]
[f 2 1]Creo que ahora lo comprendo un poco mejor.[n][w][e]

[msg MSG_012_0_0 [Hidetoshi Odagiri]]
[f 2 1][bup 102 0 65535 65535 0 0][vp 1 0 0 13 0 0]De poco sirve convocar una reunión si no acude nadie. Vámonos.[n][w][e]

[msg MND_013_0_0]
[f 2 1]Me he despedido de Hidetoshi y he vuelto a la residencia.[n][w][e]

