[msg MSG_000_0_0 [Hombre de aspecto sospechoso]]
[f 2 1][f 5 21 1 500]¿Estás preparada para oír la voz del mesías y recibir la salvación?[n][w][e]

[msg MND_001_0_0]
[f 2 1]Me pregunto qué me dirán si acepto.[n][w][e]
[f 2 1]Podría ser peligroso. ¿Qué hago?[n][w][e]

[msg MSG_002_0_0 [Hombre de aspecto sospechoso]]
[f 2 1][f 5 21 1 500]El tiempo no espera. Este es el momento de tomar acción.[n][w][e]

[sel SEL_003_0_0 top]
[f 2 1]Me reuniré con el mesías.[e]
[f 2 1]Ahora no.[e]

[msg MSG_004_0_0 [Hombre de aspecto sospechoso]]
[f 2 1][f 5 21 1 500]Muy bien... Sígueme.[n][w][e]

