[msg MSG_000_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2074 0 0]Tronca, Amada tenía mala cara...[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]Creo que le ha dado una insolación. Pobre chaval.[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]Los de su edad deben salir a jugar. Ya sabes, a pasárselo bien y aumentar su aguante.[n][w][e]

[msg MSG_001_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 65535 65535 0 0][vp 3 0 65535 2112 0 0]¡Ay! ¡Cómo quema![n][w][e]
[f 2 1][bup 3 4 65535 65535 0 0]¡Si no me doy prisa me voy a perder los tráileres![n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]Pero primero tengo que pillar algo de papeo o me voy a desplomar.[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2072 0 0]Ay, hola, [nf]. Iba a ver algunas películas.[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]¿Te apuntas? ¡Puedes ver la que quieras, colega![n][w][e]

[msg MND_002_0_0]
[f 2 1]¿Debería ir al festival del cine con Junpei?[n][w][e]

[sel SEL_003_0_0 top]
[f 2 1]Ir con él[e]
[f 2 1]Ahora no[e]

[msg MSG_004_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2029 0 0]¡Genial![n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]¡Dame un segundo y termino de comer![n][w][e]

[msg MSG_005_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2074 0 0]Amada parece bastante alicaído...[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]¿Será por el calor?[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]Los niños tienen que estar en el patio jugando con el perro. Aunque aquí no hay patio.[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2086 0 0]Oye, pero perro sí que tenemos. ¡Podríamos estar jugando con él![n][w][e]

[msg MND_006_0_0]
[f 2 1]Junpei parece ocupado.[n][w][e]
[f 2 1]Dudo que esté de humor para ir al cine...[n][w][e]

[msg MSG_007_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2013 0 0]¿Te gustaron las pelis de ayer? Qué pasada, ¿eh?[n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]¡Algún día seré como ese malote![n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]Si ponen las mismas pelis, te juro que soy capaz de vérmelas todas como diez veces.[n][w][e]

[msg MND_008_0_0]
[f 2 1]A Junpei no le interesa ver otras películas.[n][w][e]

[msg MSG_009_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 3 0 65535 2001 0 0]¡Ayer fui al cine y no veas qué pasote![n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]No podía dejar de mirar la pantalla. ¡Hasta me aguanté las ganas de mear para no perderme nada![n][w][e]
[f 2 1][bup 3 1 65535 65535 0 0]Si ponen las mismas pelis, te juro que soy capaz de vérmelas todas como diez veces.[n][w][e]

[msg MND_010_0_0]
[f 2 1]A Junpei no le interesa ver otras películas.[n][w][e]

[msg MSG_011_0_0 [Junpei Iori]]
[f 2 1][bup 3 3 65535 65535 0 0][vp 3 0 65535 2004 0 0]Oye, ¿se te ocurre algo por lo que me pirre?[n][w][e]

[sel SEL_012_0_0 top]
[f 2 1]¿Y yo qué sé?[e]
[f 2 1]Eso es cosa tuya.[e]
[f 2 1]No.[e]

[msg MSG_013_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2062 0 0]Es verdad. ¿Para qué te preguntaré...?[n][w][e]

[msg MSG_014_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 65535 65535 0 0][vp 3 0 65535 2093 0 0]Sí, tienes razón. Tengo que descubrirlo yo solo.[n][w][e]

[msg MSG_015_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 65535 65535 0 0][vp 3 0 65535 2098 0 0]Vaya, ni te lo has pensado. Pero seguramente tengas razón.[n][w][e]

[msg MND_Temperance]
[f 2 1]El arcano de la Templanza podría ayudarme a mejorar todavía más.[n][w][e]

