[msg MSG_000_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 51 65535 0 0][vp 1 0 0 1 0 0]Buah, por dentro también es una movida loquísima.[n][w][e]

[msg MSG_001_0_0 [Yukari Takeba]]
[f 2 1][bup 2 3 51 65535 0 0][vp 1 0 0 2 0 0]Pero pone los pelos de punta.[n][w][e]

[msg MSG_002_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 51 65535 0 0][vp 1 0 0 3 0 0]Esto no es más que la entrada. El laberinto está al otro lado de la puerta, al final de las escaleras.[n][w][e]

[msg MSG_003_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 51 65535 0 0][vp 1 0 0 4 0 0]Primero hay que conocer bien el lugar.[n][w][e]
[f 2 1][bup 4 0 51 65535 0 0][vp 1 0 0 5 0 0]¿Por qué no vais a echar un ojo los tres?[n][w][e]

[msg MSG_004_0_0 [Yukari Takeba]]
[f 2 1][bup 2 4 51 65535 0 0][vp 1 0 0 6 0 0]¡¿Qué?! ¡¿Solos?![n][w][e]

[msg MSG_005_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 0 51 65535 0 0][vp 1 0 0 7 0 0]No queremos que os alejéis mucho.[n][w][e]
[f 2 1][bup 5 0 51 65535 0 0][vp 1 0 0 8 0 0]Os ayudaré a moveros dándoos información desde aquí.[n][w][e]

[msg MSG_006_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 51 65535 0 0][vp 1 0 0 9 0 0]También habrá que nombrar a un líder para que tome decisiones cuando haga falta.[n][w][e]

[msg MSG_007_0_0 [Junpei Iori]]
[f 2 1][bup 3 0 51 65535 0 0][vp 1 0 0 10 0 0]¿Un líder?[n][w][e]
[f 2 1][bup 3 1 51 65535 0 0][vp 1 0 0 11 0 0]En plan, ¡¿como si fuera el capitán de un barco pirata?![n][w][e]
[f 2 1][bup 3 1 51 65535 0 0][vp 1 0 0 12 0 0]¡Eh, eh! ¡A mí! ¡Elegidme a mí![n][w][e]

[msg MSG_008_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 51 65535 0 0][vp 0 0 0 13 0 0]...[n][w][e]
[f 2 1][bup 4 0 51 65535 0 0][vp 1 0 0 14 0 0][nl], te dejo al mando.[n][w][e]

[msg MSG_009_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 51 65535 0 0][vp 1 0 0 15 0 0]¡E-espera! ¿Por qué ella? ¡No tiene pinta de capitana![n][w][e]

[msg MSG_010_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 51 65535 0 0][vp 1 0 0 16 0 0]Tranquilízate. Tiene experiencia luchando.[n][w][e]

[msg MSG_011_0_0 [Junpei Iori]]
[f 2 1][bup 3 4 51 65535 0 0][vp 1 0 0 17 0 0]Espera, ¡¿en serio?![n][w][e]

[msg MSG_012_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 51 65535 0 0][vp 1 0 0 18 0 0]Es cierto, pero la razón principal es mucho más simple.[n][w][e]
[f 2 1][bup 4 0 51 65535 0 0][vp 1 0 0 19 0 0]Junpei... Y tú también, Takeba...[n][w][e]
[f 2 1][bup 4 0 51 65535 0 0][vp 1 0 0 20 0 0]¿Alguno de vosotros puede invocar a su Persona sin dificultades, como ella?[n][w][e]

[msg MSG_013_0_0 [Junpei Iori]]
[f 2 1][bup 3 2 51 65535 0 0][vp 1 0 0 21 0 0]¡P-pues claro que sí![n][w][e]

[msg MSG_014_0_0 [Yukari Takeba]]
[f 2 1][bup 2 2 51 65535 0 0][vp 1 0 0 22 0 0]Yo también.[n][w][e]

[msg MSG_015_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 51 65535 0 0][vp 1 0 0 23 0 0]Con la de sombras que hay por aquí, sin vuestras Personas, estáis jodidos.[n][w][e]

[msg MSG_016_0_0 [Yukari Takeba]]
[f 2 1][bup 2 2 51 65535 0 0][vp 1 0 0 24 0 0]Soy consciente de ello.[n][w][e]

[msg MSG_017_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 51 65535 0 0][vp 1 0 0 25 0 0]Vale, vamos para dentro. ¿Estás preparada, líder?[n][w][e]

[sel SEL_018_0_0 top]
[f 2 1]Todo listo.[e]
[f 2 1]No estoy preparada mentalmente.[e]

[msg MSG_019_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 1 51 65535 0 0][vp 1 0 0 26 0 0]Je, así se habla.[n][w][e]

[msg MSG_020_0_0 [Yukari Takeba]]
[f 2 1][bup 2 3 51 65535 0 0][vp 1 0 0 27 0 0]Qué repentino es todo, ¿verdad?[n][w][e]
[f 2 1][bup 2 1 51 65535 0 0][vp 1 0 0 28 0 0][f 4 23 0 2 1 25 25]Pero me tienes a tu lado. Venga, vamos allá.[n][w][e]

[msg MND_023_0_0]
[f 2 1]La [f 4 4 0 37 1 20481] que tengo en la mano brilla.[n][w][e]

[msg MSG_022_0_0 [Yukari Takeba]]
[f 2 1][bup 2 0 51 65535 0 0][vp 1 0 0 29 0 0]¿Qué sucede?[n][w][e]

[msg MND_021_0_0]
[f 2 1]¿...?[n][w][e]
[f 2 1]Hay una extraña puerta en la esquina del vestíbulo.[n][w][e]

