[msg MSG_000_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]¿Eh?[n][uf 1 1][e]

[msg MSG_001_0_0 [Estudiante con gafas]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]Eh... Tú no perteneces al club, ¿verdad?[n][uf 1 1][e]

[msg MSG_001_3_0 [Estudiante con gafas]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]¿La conoces, Yamagishi?[n][uf 1 1][e]

[msg MSG_002_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]Sí, es precisamente de quien te estaba hablando.[n][uf 1 1][e]

[msg MSG_003_0_0 [Estudiante con gafas]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]¡Anda, así que es ella![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 0 6 0 0][uf 4 23 0 1 1 25 25]¡Yamagishi me ha hablado mucho de ti, [uf 4 1]![n][uf 1 1][e]

[msg MSG_004_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]Estamos buscando a nuevos miembros para unirse a nuestro club, así que te mencioné.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 8 0 0]Me alegra mucho que hayas decidido pasarte por aquí.[n][uf 1 1][e]

[msg MSG_005_0_0 [Estudiante con gafas]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 0 9 0 0]Soy Keisuke Hiraga. ¡U-un placer![n][uf 1 1][e]

[msg MSG_006_0_0 [Miembro del club]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 10 0 0][uf 5 21 0 100]Es ella quien tiene que presentarse, Keisuke.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 11 0 0][uf 5 21 0 100]¡Que tú eres el presidente del club![n][uf 1 1][e]

[msg MSG_007_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]S-sí, ya.[n][uf 1 1][e]

[msg MSG_008_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]No cambias.[n][uf 1 1][e]

[msg MSG_009_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]Yamagishi ha vuelto al club y ahora tenemos una nueva miembro.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 0 15 0 0][uf 4 23 0 1 1 25 25]Quizá debería pasarme más por aquí.[n][uf 1 1][e]

[msg MSG_010_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 1 0 0 16 0 0]¿No estás en tercero, Hiraga? Tus exámenes de acceso están a la vuelta de la esquina, ¿no?[n][uf 1 1][e]

[msg MSG_011_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 0 17 0 0]No, yo..., esto...[n][uf 1 1][e]

[msg MSG_011_5_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 0 18 0 0]¡Por eso no te preocupes! Oye, [uf 4 1], ¿tienes ojo para el arte?[n][uf 1 1][e]

[sel SEL_012_0_0 top]
[uf 0 5 65278][uf 2 1]No, la verdad.[e]
[uf 0 5 65278][uf 2 1]Sí, un poco.[e]

[msg MSG_013_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 0 19 0 0]No te preocupes, no hace falta ser profesional para unirte a este club.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 0 20 0 0]Mírame a mí, no soy más que un principiante, ¡y soy el presidente del club![n][uf 1 1][e]

[msg MSG_014_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 0 21 0 0]Je, je. Quizá debería aprender un par de cosas de ti.[n][uf 1 1][e]

[msg MSG_015_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 0 22 0 0]Conocerte así no puede ser coincidencia. Debe de ser cosa del destino.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 0 23 0 0]¿Formalizamos tu inscripción, [uf 4 1]?[n][uf 1 1][e]

[msg MND_016_0_0]
[uf 0 5 65278][uf 2 1]Hiraga me ha dado una cálida bienvenida.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]He entrado en el club de arte[n]y he hecho buenas migas con sus miembros.[n][uf 1 1][e]

[msg MSG_017_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 0 24 0 0]Solo para que lo sepas: únicamente se permite la entrada en esta sala a los miembros del club.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 0 25 0 0]Así que no olvides entregar la ficha de registro.[n][uf 1 1][e]

[msg MSG_017_5_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 0 26 0 0]El club de arte se reúne los [uf 0 1 2]martes, miércoles y jueves[uf 0 1 27].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 0 27 0 0]Sin embargo, cuando se acercan los exámenes, no quedamos. En esos días, debemos estudiar.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 0 28 0 0][uf 4 23 0 1 1 25 25]No hace falta que vengas a diario, pero pásate de vez en cuando.[n][uf 1 1][e]

[msg MSG_018_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 29 0 0]Quién iba a decir que íbamos a acabar en el mismo club.[n][uf 1 1][e]

[msg MSG_019_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 0 30 0 0]Vale, pues me ocuparé de todo el papeleo. ¡Será un placer pintar contigo, [uf 4 1]![n][uf 1 1][e]

[msg MND_020_0_0]
[uf 0 5 65278][uf 2 1]He decidido volver a la residencia[n]tras unirme al club.[n][uf 1 1][e]

