[msg MSG_000_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 0 65535 65535 0 0][uf 3 1 3 0 65535 11801 0 0]¡Te estaba esperando, [uf 4 2]![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 112 1 65535 65535 0 0]¡Vamos al aula de Economía Doméstica![n][uf 1 1][e]

[msg MSG_001_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 3 65535 65535 0 0][uf 3 1 3 0 65535 11878 0 0]Ah, [uf 4 2]...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 112 3 65535 65535 0 0]¿Me acompañas? Hay algo que quiero decirte...[n][uf 1 1][e]

[msg MSG_002_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 3 65535 65535 0 0][uf 3 1 3 0 65535 11886 0 0]Ah, [uf 4 2]. ¿Qué vas a hacer hoy?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 112 3 65535 65535 0 0]Si no estás ocupada, ¿pour quoi no me acompañas al aula de Economía Doméstica?[n][uf 1 1][e]

[msg MND_003_0_0]
[uf 0 5 65278][uf 2 1]¿Paso un rato en el club de moda después de clase?[n][uf 1 1][e]

[sel SEL_004_0_0 top]
[uf 0 5 65278][uf 2 1]Ir al club de moda.[e]
[uf 0 5 65278][uf 2 1]Comprobar estado de vínculo social[e]
[uf 0 5 65278][uf 2 1]Ahora no[e]

[msg MSG_005_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 1 65535 65535 0 0][uf 3 1 3 0 65535 11834 0 0]¡Coser es très amusant! ¡Coseré hasta que se me caiga la mano![n][uf 1 1][e]

[msg MSG_006_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 0 65535 65535 0 0][uf 3 1 3 0 65535 11849 0 0]Muchas, muchas gracias... ¡Venga, vamos![n][uf 1 1][e]

[msg MSG_007_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 3 65535 65535 0 0][uf 3 1 3 0 65535 11902 0 0]Vaya... Entonces hoy estaré solito...[n][uf 1 1][e]

[msg MSG_008_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 3 65535 65535 0 0][uf 3 1 3 0 65535 11898 0 0]Entiendo...[n][uf 1 1][e]

[msg MSG_009_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 1 65535 65535 0 0]¡Venga, vamos al aula de Economía Doméstica![n][uf 1 1][e]

[msg MSG_010_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 3 65535 65535 0 0]Ah, sí... ¿Vendrás hoy? Hay algo de lo que quiero hablarte.[n][uf 1 1][e]

[msg MSG_011_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 3 65535 65535 0 0]Ah, sí... ¿Qué vas a hacer hoy?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 112 0 65535 65535 0 0]Si no estás ocupada, ¿pour quoi no me acompañas al aula de Economía Doméstica?[n][uf 1 1][e]

[msg MSG_012_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 1 65535 65535 0 0][uf 3 1 3 0 65535 11805 0 0]Ah, ¡[uf 4 2]! Los exámenes han finalizado.[n][uf 1 1][e]

[msg MSG_013_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 0 65535 65535 0 0][uf 3 1 3 0 65535 11811 0 0]Ay, [uf 4 2]... Por fin han concluido los exámenes.[n][uf 1 1][e]

[msg MSG_014_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 1 65535 65535 0 0]Los dos nos hemos esforzado mucho... Mi cerebro está cansado.[n][uf 1 1][e]

[msg MSG_015_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 1 65535 65535 0 0]Hemos librado una intensa batalla... Mi cerebro está cansado.[n][uf 1 1][e]

[msg MSG_016_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 1 65535 65535 0 0][uf 3 1 3 0 65535 11812 0 0]¡Te estaba esperando, [uf 4 2]![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 112 0 65535 65535 0 0]¡Vamos al aula de Economía Doméstica![n][uf 1 1][e]

[msg MSG_016_5_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 0 65535 65535 0 0]¡Venga, vamos al aula de Economía Doméstica![n][uf 1 1][e]

[msg MSG_017_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 1 65535 65535 0 0][uf 3 1 3 0 65535 11912 0 0]¡Coser es très amusant! ¡Coseré hasta que se me caiga la mano![n][uf 1 1][e]

[msg MSG_018_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 1 65535 65535 0 0][uf 3 1 3 0 65535 11802 0 0]¡Hola, [uf 4 2]! ¿Qué tal?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 112 0 65535 65535 0 0]Si tienes tiempo, ¿te gustaría coser con moi?[n][uf 1 1][e]

[msg MSG_018_5_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 1 65535 65535 0 0]Por cierto, ¿cómo estás?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 112 0 65535 65535 0 0]Si tienes tiempo, ¿te gustaría coser con moi?[n][uf 1 1][e]

[msg MSG_019_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 1 65535 65535 0 0][uf 3 1 3 0 65535 11912 0 0]¡Gracias! ¡Merci beaucoup![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 112 1 65535 65535 0 0]Se te da bien la costura, [uf 4 2]. ¡Enséñame qué más puedes hacer, s'il te plaît![n][uf 1 1][e]

[msg MSG_020_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 3 65535 65535 0 0][uf 3 1 3 0 65535 11887 0 0]Ah, [uf 4 2]...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 112 3 65535 65535 0 0]¿Te marchas a casa? ¿O vienes a clase de Economía Doméstica?[n][uf 1 1][e]

[msg MSG_020_5_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 0 65535 65535 0 0]Anda, ¿te marchas a casa? ¿O vienes al aula de Economía Doméstica?[n][uf 1 1][e]

[msg MSG_021_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 0 65535 65535 0 0][uf 3 1 3 0 65535 11912 0 0]Cuando estoy así, tengo que coser... Continuemos desde donde lo dejamos.[n][uf 1 1][e]

[msg MSG_022_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 0 65535 65535 0 0][uf 3 1 3 0 65535 11808 0 0]Saludos, [uf 4 2].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 112 1 65535 65535 0 0]¡Me gustaría pedirte que vinieras conmigo al club de moda![n][uf 1 1][e]

[msg MSG_022_5_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 1 65535 65535 0 0]¡Me gustaría pedirte que vinieras conmigo al club de moda![n][uf 1 1][e]

[msg MSG_023_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 1 65535 65535 0 0][uf 3 1 3 0 65535 11882 0 0]¡Ah, pues vamos allá! ¡Al aula de Economía Doméstica![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 112 0 65535 65535 0 0]Sigues mejorando, pero no pienso dejarme vencer...[n][uf 1 1][e]

[msg MSG_024_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 1 65535 65535 0 0][uf 3 1 3 0 65535 11802 0 0]¡Te estaba esperando, [uf 4 2]![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 112 0 65535 65535 0 0]Parece que los hilos del destino nos han unido. ¿Tienes un momento para hablar?[n][uf 1 1][e]

[msg MSG_024_5_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 0 65535 65535 0 0]¡[uf 4 2]! Parece que los hilos del destino nos han unido. ¿Tienes un momento para hablar?[n][uf 1 1][e]

[msg MSG_025_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 1 65535 65535 0 0][uf 3 1 3 0 65535 11897 0 0]¡Oh, qué día tan magnifique! Hablemos mientras le damos a la máquina de coser.[n][uf 1 1][e]

[msg MSG_026_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 0 65535 65535 0 0][uf 3 1 3 0 65535 11805 0 0][uf 4 2], ¿estás ocupada?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 112 1 65535 65535 0 0]¡Para dominar el arte del kimono, necesito tu ayuda, s'il te plaît![n][uf 1 1][e]

[msg MSG_026_5_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 0 65535 65535 0 0][uf 4 2], ¿estás ocupada?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 112 1 65535 65535 0 0]¡Para dominar el arte del kimono, necesito tu ayuda, s'il te plaît![n][uf 1 1][e]

[msg MSG_027_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 1 65535 65535 0 0][uf 3 1 3 0 65535 11912 0 0]¡Muchísimas gracias! ¡Merci beacoup! ¡Hoy coseré como nunca![n][uf 1 1][e]

[msg MSG_028_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 0 65535 65535 0 0][uf 3 1 3 0 65535 11812 0 0]¡Oh! Saludos, [uf 4 2].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 112 3 65535 65535 0 0]Que sepas que pienso crear el kimono definitivo, pero aún hay mucho trabajo por hacer...[n][uf 1 1][e]

[msg MSG_028_5_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 3 65535 65535 0 0]Que sepas que pienso crear el kimono definitivo, pero aún hay mucho trabajo por hacer...[n][uf 1 1][e]

[msg MSG_029_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 1 65535 65535 0 0][uf 3 1 3 0 65535 11908 0 0]¡Oh là là! ¡No sé qué decir! ¡Vamos rápido al aula de Economía Doméstica![n][uf 1 1][e]

[msg MSG_030_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 0 65535 65535 0 0][uf 3 1 3 0 65535 11809 0 0]¡Ah, [uf 4 2]![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 112 2 65535 65535 0 0]Ya queda muy poquito. ¡Hoy termino mi proyecto![n][uf 1 1][e]

[msg MSG_030_5_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 2 65535 65535 0 0]Ya queda muy poquito. ¡Hoy termino mi kimono![n][uf 1 1][e]

[msg MSG_031_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 1 65535 65535 0 0][uf 3 1 3 0 65535 11847 0 0]¡Merci! ¡Te estoy muy agradecido! Y ahora... ¡a bordar![n][uf 1 1][e]

[msg MSG_032_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_033_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 3 65535 65535 0 0][uf 3 1 3 0 65535 11865 0 0]Oh, vaya... Bueno, te espero para la próxima.[n][uf 1 1][e]

[msg MSG_034_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 3 65535 65535 0 0][uf 3 1 3 0 65535 11865 0 0]Qué mala pata... Pero lo entiendo.[n][uf 1 1][e]

[msg MSG_035_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 3 65535 65535 0 0][uf 3 1 3 0 65535 11886 0 0]Muy bien.[n][uf 1 1][e]

[msg MSG_036_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 3 65535 65535 0 0][uf 3 1 3 0 65535 11886 0 0]Si ya tienes planes, no te preocupes...[n][uf 1 1][e]

[msg MSG_037_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 3 65535 65535 0 0][uf 3 1 3 0 65535 11886 0 0]Oh, vaya... Otra vez será.[n][uf 1 1][e]

[msg MSG_038_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 3 65535 65535 0 0][uf 3 1 3 0 65535 11865 0 0]Agh... No me queda otra que esperar a la próxima.[n][uf 1 1][e]

[msg MSG_039_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 3 65535 65535 0 0][uf 3 1 3 0 65535 11865 0 0]Vaya... Bueno, la próxima será.[n][uf 1 1][e]

[msg MSG_040_0_0 [Bebe]]
[uf 0 5 65278][uf 2 1][uf 4 5 112 3 65535 65535 0 0][uf 3 1 3 0 65535 11865 0 0]Ah, vaya... Tendré que echarle hoy paciencia.[n][uf 1 1][e]

[msg MND_GENERAL_EVENTPLAY]
[uf 0 5 65278][uf 2 1]Mensaje enviado por el guion. Repetición del evento del comité.[n][uf 1 1][e]

[msg MND_GENERAL_PERSPNA]
[uf 0 5 65278][uf 2 1]Siento que podemos estrechar lazos gracias a la Persona del arcano [uf 2 4 2], [uf 0 1 35][uf 2 4 5][uf 0 1 27].[n][uf 1 1][e]

[msg MND_GENERALSELECTMSG_MAX]
[uf 0 5 65278][uf 2 1]Siento un vínculo irrompible con [uf 2 4 0]...[n][uf 1 1][e]

[msg MND_GENERALMSG_BS_MAX]
[uf 0 5 65278][uf 2 1]Siento un vínculo irrompible con la pareja de ancianos...[n][uf 1 1][e]

[msg MND_GENERALSELECTMSG_RAN]
[uf 0 5 65278][uf 2 1]Creo que mi relación con [uf 2 4 0] se estrechará pronto.[n][uf 1 1][e]

[msg MND_GENERALMSG_BS_RANKUP]
[uf 0 5 65278][uf 2 1]Creo que mi relación con la pareja de ancianos se estrechará pronto.[n][uf 1 1][e]

[msg MND_GENERALSELECTMSG_NOR]
[uf 0 5 65278][uf 2 1]No creo que mi vínculo con [uf 2 4 0] se fortalezca más aunque pasemos tiempo juntos...[n][uf 1 1][e]

[msg MND_GENERALMSG_BS_NORMAL [Bebe]]
[uf 0 5 65278][uf 2 1]No creo que nuestro vínculo se fortalezca más aunque pasemos tiempo juntos.[n][uf 1 1][e]

[msg MND_GENERALSELECTMSG_MAX_2]
[uf 0 5 65278][uf 2 1]Parece que tu relación no puede avanzar más...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]¿Deberíamos pasar el rato juntos igualmente?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_SOLO_AS]
[uf 0 5 65278][uf 2 1]¿Paso un rato con [uf 2 4 0] después de clase?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_SOLO_DT]
[uf 0 5 65278][uf 2 1]¿Debería pasar el día con [uf 2 4 0]?[n][uf 1 1][e]

[msg MND__GENERAL_MSG_NET]
[uf 0 5 65278][uf 2 1]¿Debería pasar tiempo en línea jugando al MMORPG con [uf 2 4 0]?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_SOLO_NT]
[uf 0 5 65278][uf 2 1]¿Debería pasar la tarde con [uf 2 4 0]...?[n][uf 1 1][e]

[sel SEL_GENERALSELECTMSG_SOL top]
[uf 0 5 65278][uf 2 1]Pasar tiempo con [uf 2 4 0][e]
[uf 0 5 65278][uf 2 1]Comprobar vínculo social[e]
[uf 0 5 65278][uf 2 1]Da igual[e]

[msg MND_GENERAL_MSG_MULTIPLE]
[uf 0 5 65278][uf 2 1]¿Paso un rato en [uf 2 4 1] después de clase?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_FASHION_]
[uf 0 5 65278][uf 2 1]¿Paso un rato en el club de moda después de clase?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_BOOKSTOR]
[uf 0 5 65278][uf 2 1]¿Debería pasar el día en la librería?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_BOOKSTOR_2]
[uf 0 5 65278][uf 2 1]¿Paso un rato en la librería después de clase?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_MULTIPLE_2]
[uf 0 5 65278][uf 2 1]¿Debería pasar tiempo con [uf 2 4 1] esta noche...?[n][uf 1 1][e]

[sel SEL_GENERALSELECTMSG_MUL top]
[uf 0 5 65278][uf 2 1]Pasar un rato: [uf 2 4 1][e]
[uf 0 5 65278][uf 2 1]Comprobar vínculo social[e]
[uf 0 5 65278][uf 2 1]Da igual[e]

[sel SEL_GENERALSELECTMSG_FCL top]
[uf 0 5 65278][uf 2 1]Ir al club de moda.[e]
[uf 0 5 65278][uf 2 1]Comprobar vínculo social[e]
[uf 0 5 65278][uf 2 1]Da igual[e]

[sel SEL_GENERALSELECTMSG_BS top]
[uf 0 5 65278][uf 2 1]Entrar en la librería[e]
[uf 0 5 65278][uf 2 1]Comprobar vínculo social[e]
[uf 0 5 65278][uf 2 1]Da igual[e]

[msg MSG_GENERAL_EXAMREWARD_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]He visto tus notas. Buen trabajo.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Toma, de parte del director.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4108 0 0]Es tu recompensa por ser capaz de compaginar los estudios y nuestras... en fin, "actividades extraescolares".[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_0]
[uf 0 5 65278][uf 2 1]DEV: UNUSED LABEL[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_0_2]
[uf 0 5 65278][uf 2 1]Como he sacado la nota más alta en los exámenes, he obtenido: [uf 4 4 1 37 1 3].[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_0_2 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]He visto tus notas. Buen trabajo.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Toma, de parte del director.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4108 0 0]Es tu recompensa por ser capaz de compaginar los estudios y nuestras... en fin, "actividades extraescolares".[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_0_3 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4077 0 0]Ah, cierto. Hay algo más.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]He visto tus notas. Buen trabajo.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Toma, de parte del director.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4131 0 0]Es tu recompensa por ser capaz de compaginar los estudios y nuestras... en fin, "actividades extraescolares".[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_0_3]
[uf 0 5 65278][uf 2 1]Como he sacado la nota más alta en los exámenes, he obtenido: [uf 4 4 1 37 1 3].[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_0_4 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]He visto tus notas. Buen trabajo.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Toma, de parte del director.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4108 0 0]Es tu recompensa por ser capaz de compaginar los estudios y nuestras... en fin, "actividades extraescolares".[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_0_4]
[uf 0 5 65278][uf 2 1]DEV: UNUSED LABEL[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_0_5 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]He visto tus notas... Buen trabajo.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Es laudable que continúes destacando en el instituto mientras libras arduos combates.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0]Acepta este regalo para agradecerte tus esfuerzos.[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_0_5]
[uf 0 5 65278][uf 2 1]未使用ラベルです。[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_0_6 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0]He visto tus notas. Buen trabajo.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0]Es laudable que continúes destacando en el instituto mientras libras arduos combates.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0]Acepta este regalo para agradecerte tus esfuerzos.[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_1]
[uf 0 5 65278][uf 2 1]Como he sacado la nota más alta en los exámenes, he obtenido: [uf 4 4 1 37 1 3].[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_1 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]He visto tus notas. Buen trabajo.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Es laudable que continúes destacando en el instituto mientras libras arduos combates.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4108 0 0]Acepta este regalo para agradecerte tus esfuerzos.[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_1_2]
[uf 0 5 65278][uf 2 1]DEV: UNUSED LABEL[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_1_3]
[uf 0 5 65278][uf 2 1]Como he sacado la nota más alta en los exámenes, he obtenido: [uf 4 4 1 37 1 3].[n][uf 1 1][e]

