[msg MSG_000_0_0 [Hombre de familia]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 6 1 12 0]¿Mmm? Tú eres...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 6 2 12 0]Ah, eres [uf 4 1], ¿no?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 6 3 12 0]No sé si te acuerdas, pero soy el padre de Maiko.[n][uf 1 1][e]

[msg MSG_001_0_0 [Padre de Maiko]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 6 4 12 0]¿Tienes un momento? He estado dándole vueltas a lo que pasó...[n][uf 1 1][e]

[sel SEL_002_0_0 top]
[uf 0 5 65278][uf 2 1]Muy bien.[e]
[uf 0 5 65278][uf 2 1]Hoy estoy algo ocupada...[e]

[msg MSG_003_0_0 [Padre de Maiko]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 6 5 12 0]Genial. Si no te importa, vamos dando un paseo hasta el puesto de takoyaki. Yo invito.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 6 6 12 0]La comida de allí está muy buena... Pero eso ya lo sabes, ¿no?[n][uf 1 1][e]

[msg MSG_004_0_0 [Padre de Maiko]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 6 7 12 0]Vaya, qué lástima.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 6 8 12 0]Estaba pensando en Maiko cuando apareciste tú.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 6 9 12 0]Perdona, no quiero atosigarte.[n][uf 1 1][e]

