[msg MSG_000_0_0 [Anciano]]
[uf 0 5 65278][uf 2 1][uf 4 5 103 0 65535 65535 0 0][uf 3 1 3 0 65535 10424 0 0]Ah, ¿eres alumna de un instituto de la zona?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 103 0 65535 65535 0 0]Bueno, ¡te alegrará saber que puedes comer sushi de buena calidad por aquí cerca! ¡Lo hago yo mismo![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 103 1 65535 65535 0 0]¡Pásate algún día si quieres! Bueno, en realidad aún estamos reformando el local. Lo siento.[n][uf 1 1][e]

[msg MSG_004_0_0 [Anciana]]
[uf 0 5 65278][uf 2 1][uf 4 5 104 0 65535 65535 0 0][uf 3 1 3 0 65535 10607 0 0]Esto es una librería, no un restaurante de sushi.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 104 0 65535 65535 0 0]Lo siento. Siempre está igual.[n][uf 1 1][e]

