[msg MSG_000_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]Si ça continue comme ça, on est bons.[n][uf 1 1][e]

[msg MSG_001_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]S'il y a des trucs abîmés ou avec une forme bizarre, donne-les-moi.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]C'est aussi bon, et le mieux, c'est de les manger juste après les avoir ramassés.[n][uf 1 1][e]

[msg MSG_002_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]Ah, oui. Ne laisse pas les tiges et les racines comme ça une fois que tu as ramassé la récolte.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]Tu les enlèves et tu remplaces la terre tout de suite. Tu ne peux rien replanter tant que ce n'est pas fait.[n][uf 1 1][e]

[sel SEL_003_0_0 top]
[uf 0 5 65278][uf 2 1]Entendue.[e]
[uf 0 5 65278][uf 2 1]Quel gaspillage.[e]
[uf 0 5 65278][uf 2 1]Quelle barbe.[e]

[msg MSG_004_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 1 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]Tu piges tout très vite, j'apprécie. On se prend moins la tête comme ça.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 1 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]C'est un plaisir de bosser avec toi, pas comme avec quelqu'un que je ne nommerai pas.[n][uf 1 1][e]

[msg MSG_005_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0][uf 3 1 1 0 0 8 0 0]Arrête ça, on croirait Aki.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0][uf 3 1 1 0 0 9 0 0]Je ne serai peut-être pas là pour t'aider la prochaine fois, alors fais ce que je te dis.[n][uf 1 1][e]

[msg MSG_006_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]C'est toi qui es responsable. Il faut penser à celui qui les utilisera après toi.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0][uf 3 1 1 0 0 11 0 0]Je ne serai peut-être pas là pour t'aider la prochaine fois, alors fais ce que je te dis.[n][uf 1 1][e]

[msg MSG_007_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]Tu sais, j'ai démarré sur un coup de tête, mais de temps à autre, ça vaut le coup de faire ce genre de truc.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]Même quelqu'un comme moi peut... Comment dire...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]Faire pousser quelque chose, ça te permet de voir le fruit de ton travail. Tu sens que tu l'as fait de tes propres mains.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0][uf 3 1 1 0 0 15 0 0]Son cycle vital se termine quand tu le manges, mais bon.[n][uf 1 1][e]

[sel SEL_010_0_0 top]
[uf 0 5 65278][uf 2 1]Ils deviennent notre nourriture.[e]
[uf 0 5 65278][uf 2 1]On a toujours nos souvenirs.[e]

[msg MSG_011_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0][uf 3 1 1 0 0 16 0 0]Oui, c'est vrai.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0][uf 3 1 1 0 0 17 0 0]Rien qu'être en vie, ça donne faim. Ils jouent leur rôle.[n][uf 1 1][e]

[msg MSG_012_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 1 65535 65535 0 0][uf 3 1 1 0 0 18 0 0]Haha, c'est bien ringard.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0][uf 3 1 1 0 0 19 0 0]Mais tu sais quoi ? T'as peut-être raison.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0][uf 3 1 1 0 0 20 0 0]Je croyais avoir oublié le jardinage que j'avais fait étant gamin.[n][uf 1 1][e]

[msg MSG_014_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0][uf 3 1 1 0 0 21 0 0]Même si quelqu'un disparaît, peut-être qu'il peut laisser quelque chose derrière lui...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0][uf 3 1 0 0 0 22 0 0]......[n][uf 1 1][e]

[msg MSG_014_2_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0][uf 3 1 1 0 0 23 0 0]Rien. Je parlais tout seul.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 3 65535 65535 0 0][uf 3 1 1 0 0 24 0 0][uf 4 23 0 10 3 25 25]Je suppose que c'est pas vraiment mon genre.[n][uf 1 1][e]

[msg MND_014_3_0]
[uf 0 5 65278][uf 2 1]Aragaki semble avoir pris conscience de quelque chose en s'occupant du jardin...[n][uf 1 1][e]

[msg MSG_014_4_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0][uf 3 1 1 0 0 25 0 0]J'ai un peu trop causé, aujourd'hui.[n][uf 1 1][e]

[msg MSG_014_6_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0][uf 3 1 1 0 0 26 0 0]Allez, fin de la pause. On s'y remet.[n][uf 1 1][e]

[msg MND_015_0_0]
[uf 0 5 65278][uf 2 1]Je me suis occupée des plants avec Aragaki...[n][uf 1 1][e]

[msg MSG_016_0_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0][uf 3 1 1 0 0 27 0 0]Bien, je pense que c'est bon.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0][uf 3 1 1 0 0 28 0 0]Merci de ton aide. Si tu refais ça un jour, je me joindrai à toi.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0][uf 3 1 1 0 0 29 0 0]Il est temps de rentrer.[n][uf 1 1][e]

