[msg MSG_000_0_0 [Maiko]]
[uf 0 5 65278][uf 2 1][uf 4 5 110 2 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]Thank you for always helping me... But I gotta say bye for now.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 110 3 65535 65535 0 0][uf 3 1 1 0 0 2 0 0][uf 4 23 0 110 3 25 25]Yup, I have to run away now.[n][uf 1 1][e]

[msg MSG_000_5_0 [Maiko]]
[uf 0 5 65278][uf 2 1][uf 4 5 110 0 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]Remember not to tell Mom and Dad, okay? Bye-bye![n][uf 1 1][e]

[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]...?[n][uf 1 1][e]

[msg MSG_002_0_0 [Woman]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 4 0 0][uf 5 21 0 10]Hey, you![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 5 0 0][uf 5 21 0 10]Have you seen a little girl? She's in elementary school...[n][uf 1 1][e]

[msg MSG_003_0_0 [Man]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 6 0 0][uf 5 21 0 11]Will you just take a second and calm down?[n][uf 1 1][e]

[msg MSG_004_0_0 [Woman]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 7 0 0][uf 5 21 0 10]Calm down!? What if something happens to her!?[n][uf 1 1][e]

[msg MSG_005_0_0 [Man]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 8 0 0][uf 5 21 0 11]Oh please! This is what happens when you force a child to study non-stop![n][uf 1 1][e]

[msg MSG_006_0_0 [(SE) Woman]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 9 0 0]Why are you always like this!? Everything has to be MY fault![n][uf 1 1][e]

[msg MSG_007_0_0 [(SE) Man]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 10 0 0]That's because it IS your fault! This never would have happened if you'd been watching her![n][uf 1 1][e]

[msg MSG_008_0_0 [Man]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 11 0 0][uf 5 21 0 11]Look, we don't have time for this![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 12 0 0][uf 5 21 0 11]I think I know who you are. [uf 4 1]-san, right? Maiko's told me about you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 13 0 0][uf 5 21 0 11]She said she played with a high school kid instead of practicing piano.[n][uf 1 1][e]

[msg MSG_009_0_0 [Woman]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 14 0 0][uf 5 21 0 10]What!? This is the first I'm hearing of this![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 15 0 0][uf 5 21 0 10]What the hell did you do to my daughter!?[n][uf 1 1][e]

[msg MND_010_0_0]
[uf 0 5 65278][uf 2 1]The woman is extremely agitated...[n][uf 1 1][e]

[msg MSG_011_0_0 [Man]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 16 0 0][uf 5 21 0 11]Shut up! Stop jumping to stupid conclusions.[n][uf 1 1][e]

[msg MSG_011_5_0 [Man]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 17 0 0][uf 5 21 0 11]I'm sorry about this... We're Maiko's parents.[n][uf 1 1][e]

[msg MSG_012_0_0 [Maiko's Dad]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 18 0 0][uf 5 21 0 11]We haven't seen her since this morning.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 19 0 0][uf 5 21 0 11]When we checked her room, we found a note that said, "I'm running away."[n][uf 1 1][e]

[msg MSG_013_0_0 [Maiko's Mom]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 20 0 0][uf 5 21 0 10]She's never done anything like this before![n][uf 1 1][e]

[sel SEL_014_0_0 top]
[uf 0 5 65278][uf 2 1]We should look for her.[e]
[uf 0 5 65278][uf 2 1]It's probably your fault.[e]
[uf 0 5 65278][uf 2 1]Just leave her alone.[e]

[msg MSG_015_0_0 [Maiko's Dad]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 21 0 0][uf 5 21 0 11]R-Right. She might be around here somewhere.[n][uf 1 1][e]

[msg MSG_016_0_0 [Maiko's Mom]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 22 0 0][uf 5 21 0 10]Excuse me!? You don't know anything![n][uf 1 1][e]

[msg MSG_017_0_0 [Maiko's Mom]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 23 0 0][uf 5 21 0 10]Don't be stupid! What if something happens to her out there!?[n][uf 1 1][e]

[msg MSG_018_0_0 [Maiko's Mom]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 24 0 0][uf 5 21 0 10]Maiko... Why...?[n][uf 1 1][e]

[msg MSG_019_0_0 [Maiko's Dad]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 25 0 0][uf 5 21 0 11]Listen...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 26 0 0][uf 5 21 0 11]If you have any idea where she is, I'm begging you to tell us.[n][uf 1 1][e]

[sel SEL_020_0_0 top]
[uf 0 5 65278][uf 2 1]Maybe the music store.[uf 2 9 1 1 586][e]
[uf 0 5 65278][uf 2 1]Maybe the takoyaki stand.[e]

[msg MSG_021_0_0 [Maiko's Dad]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 27 0 0][uf 5 21 0 11]The music store...? Why would she have gone there?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 28 0 0][uf 5 21 0 11]Well, let's try looking![n][uf 1 1][e]

[msg MSG_022_0_0 [Maiko's Dad]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 29 0 0][uf 5 21 0 11]Takoyaki stand? Oh, that place![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 30 0 0][uf 5 21 0 11]Right, let's try looking![n][uf 1 1][e]

