[msg MSG_000_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 3 0 65535 5128 0 0]¡El enemigo es fuerte! ¡Vigila que la salud no decaiga![n][uf 1 1][e]

[msg MSG_000_0_1 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 3 0 65535 5128 0 0]¡No podemos bajar la guardia con este enemigo! ¡Haré lo posible para echar una mano![n][uf 1 1][e]

[msg MSG_000_0_2 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 3 0 65535 5128 0 0]¡El enemigo viene hacia aquí! ¡No lo pierdas de vista![n][uf 1 1][e]

[msg MSG_001_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0][uf 3 1 3 0 65535 5008 0 0]¡No tenemos datos sobre este adversario! ¡No bajes la guardia![n][uf 1 1][e]

[msg MSG_MONAD_BTL_YUKARI_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 65535 65535 0 0][uf 3 1 3 0 65535 1117 0 0]¡Sea lo que sea, pienso plantarle cara![n][uf 1 1][e]

[msg MSG_MONAD_BTL_YUKARI_1 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 8 65535 65535 0 0][uf 3 1 3 0 65535 1117 0 0]¡Ven a por mí![n][uf 1 1][e]

[msg MSG_MONAD_BTL_JUNPEI_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 3 0 65535 2088 0 0]¡Muy bien! ¡Ahora vas a verme en acción![n][uf 1 1][e]

[msg MSG_MONAD_BTL_JUNPEI_1 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 2 65535 65535 0 0][uf 3 1 3 0 65535 2117 0 0]Bueno, ¡pues es hora de acabar con esto![n][uf 1 1][e]

[msg MSG_MONAD_BTL_SANADA_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 9 65535 65535 0 0][uf 3 1 3 0 65535 3116 0 0]Parece que la cosa se pone interesante. ¡Vamos![n][uf 1 1][e]

[msg MSG_MONAD_BTL_SANADA_1 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 2 65535 65535 0 0][uf 3 1 3 0 65535 3116 0 0]Una derrota es inconcebible. ¡Ven a por mí si te atreves![n][uf 1 1][e]

[msg MSG_MONAD_BTL_MITSURU_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 2 65535 65535 0 0][uf 3 1 3 0 65535 4117 0 0]Siempre hay un punto débil al que atacar. ¡Acabemos con él![n][uf 1 1][e]

[msg MSG_MONAD_BTL_MITSURU_1 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 8 65535 65535 0 0][uf 3 1 3 0 65535 4117 0 0]¡Prepárate, que viene![n][uf 1 1][e]

[msg MSG_MONAD_BTL_FUKA_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]Unused[n][uf 1 1][e]

[msg MSG_MONAD_BTL_FUKA_1 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 50 0 0]Unused[n][uf 1 1][e]

[msg MSG_MONAD_BTL_AEGIS_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6007 0 0]El enemigo está dentro del rango. Iniciando combate.[n][uf 1 1][e]

[msg MSG_MONAD_BTL_AEGIS_1 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 2 65535 65535 0 0][uf 3 1 3 0 65535 6007 0 0]Una señal potente... ¡Me lo imaginaba! ¡Pienso ir a por todas![n][uf 1 1][e]

[msg MSG_MONAD_BTL_AMADA_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 8 65535 65535 0 0][uf 3 1 3 0 65535 7118 0 0]Tiene pinta de ser fuerte... ¡Venga, podemos hacerlo![n][uf 1 1][e]

[msg MSG_MONAD_BTL_AMADA_1 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 8 65535 65535 0 0][uf 3 1 3 0 65535 7118 0 0]¡Muy bien, te vas a enterar![n][uf 1 1][e]

[msg MSG_MONAD_BTL_KOROMARU_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 2 65535 65535 0 0][uf 3 1 3 0 65535 8002 0 0]Grr... ¡Arf![n][uf 1 1][e]

[msg MSG_MONAD_BTL_KOROMARU_1 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 2 65535 65535 0 0][uf 3 1 3 0 65535 8002 0 0]Grrr...[n][uf 1 1][e]

[msg MSG_MONAD_BTL_ARAGAKI_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 2 65535 65535 0 0][uf 3 1 3 0 65535 9109 0 0]Bueno, ha llegado la hora. Espero que estés lista.[n][uf 1 1][e]

[msg MSG_MONAD_BTL_ARAGAKI_1 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 2 65535 65535 0 0][uf 3 1 3 0 65535 9109 0 0]Menudo incordio... No bajes la guardia.[n][uf 1 1][e]

[msg MSG_MONAD_BTL_AEGIS_2 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 2 65535 65535 0 0][uf 3 1 3 0 65535 6117 0 0]Parece que es duro de roer. ¡Tened cuidado![n][uf 1 1][e]

[msg MSG_MONAD_BTL_AEGIS_3 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 2 65535 65535 0 0][uf 3 1 3 0 65535 6118 0 0]Tenemos que trabajar en equipo. ¡Yo también pienso darlo todo![n][uf 1 1][e]

