[msg MSG_000_0_0 [Yukari's Voice]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 1 0 0]Yamagishi-san, are you in there?[n][uf 1 1][e]

[msg MSG_001_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 1 65535 0 0][uf 3 1 1 0 0 2 0 0]Yes, come in.[n][uf 1 1][e]

[msg MSG_002_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 1 65535 0 0][uf 3 1 1 0 0 3 0 0]I think we should start heading to the command room, and— Huh?[n][uf 1 1][e]

[msg MSG_003_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 1 65535 0 0][uf 3 1 1 0 0 4 0 0]You already finished unpacking? I was planning on helping you out later, too![n][uf 1 1][e]

[msg MSG_004_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 1 65535 0 0][uf 3 1 1 0 0 5 0 0]Well, I didn't have too much with me, so I finished a lot sooner than I expected.[n][uf 1 1][e]

[msg MSG_005_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 1 65535 0 0][uf 3 1 1 0 0 6 0 0]Oh, are you good with computers, by any chance?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 1 65535 0 0][uf 3 1 1 0 0 7 0 0]You think you could teach me? I'm really not good with stuff like that.[n][uf 1 1][e]

[msg MSG_006_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 1 65535 0 0][uf 3 1 1 0 0 8 0 0]S-Sure, if you'd like me to.[n][uf 1 1][e]

[msg MSG_007_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 1 65535 0 0][uf 3 1 1 0 0 9 0 0]Are you looking into something?[n][uf 1 1][e]

[msg MSG_008_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 1 65535 0 0][uf 3 1 1 0 0 10 0 0]Yes, I figured I should know everyone's defining characteristics and whatnot, to prepare for battle.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 1 65535 0 0][uf 3 1 1 0 0 11 0 0]I can't do any actual fighting, so I need to make myself useful.[n][uf 1 1][e]

[msg MSG_009_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 1 65535 0 0][uf 3 1 1 0 0 12 0 0]Oh, I see.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 1 65535 0 0][uf 3 1 1 0 0 13 0 0]You're a really hard worker, Yamagishi-san. And you've got an amazing ability too.[n][uf 1 1][e]

[msg MSG_010_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 1 65535 0 0][uf 3 1 1 0 0 14 0 0]Now that I think about it, everyone in this dorm is pretty amazing, huh?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 1 65535 0 0][uf 3 1 1 0 0 15 0 0]Sanada-senpai is hands down one of the strongest, and [uf 4 1]-chan has a power unlike anyone else's.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 1 65535 0 0][uf 3 1 1 0 0 16 0 0]I bet Kirijo-senpai's strong, too. And Junpei... Well, he's whatever.[n][uf 1 1][e]

[msg MSG_010_5_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 1 65535 0 0][uf 3 1 1 0 0 17 0 0]But what do I have? I'm only half the person everyone else here is. I couldn't even do anything the last full moon.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 1 65535 0 0][uf 3 1 1 0 0 18 0 0]Maybe I don't need to be here after all, haha.[n][uf 1 1][e]

[msg MSG_011_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 1 65535 0 0][uf 3 1 1 0 0 19 0 0]That's not true at all.[n][uf 1 1][e]

[msg MSG_012_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 1 65535 0 0][uf 3 1 1 0 0 20 0 0]Huh?[n][uf 1 1][e]

[msg MSG_013_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 1 65535 0 0][uf 3 1 1 0 0 21 0 0]I was told that a Persona is the power of the soul, also known as your other self.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 1 65535 0 0][uf 3 1 1 0 0 22 0 0]That's why I think a person's personality and feelings are reflected in their Persona.[n][uf 1 1][e]

[msg MSG_013_5_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 1 65535 0 0][uf 3 1 1 0 0 23 0 0]For example, Takeba-san, your Persona has healing powers, right?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 1 65535 0 0][uf 3 1 1 0 0 24 0 0]That's because there's a kindness in you that no one else has.[n][uf 1 1][e]

[msg MSG_014_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 1 65535 0 0][uf 3 1 1 0 0 25 0 0]I... I'm not kind at all.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 1 65535 0 0][uf 3 1 1 0 0 26 0 0][uf 4 23 0 2 0 25 25]I just don't want to see anyone go down or get hurt, that's all...[n][uf 1 1][e]

[msg MSG_015_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 1 65535 0 0][uf 3 1 0 0 0 27 0 0]......[n][uf 1 1][e]

[msg MSG_016_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 1 65535 0 0][uf 3 1 1 0 0 28 0 0]C'mon. I think Ikutsuki-san's gonna be here soon.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 1 65535 0 0][uf 3 1 1 0 0 29 0 0][uf 4 23 0 2 1 25 25]Oh, and you can just call me Yukari. I hope you like it here, Fuuka.[n][uf 1 1][e]

[msg MSG_017_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 1 65535 0 0][uf 3 1 1 0 0 30 0 0]I'm sure I will.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 1 65535 0 0][uf 3 1 1 0 0 31 0 0]Thank you, Yukari-chan.[n][uf 1 1][e]

