[msg SYS_PERSONA_DROP]
[f 2 1]Quer mesmo libertar [clr 35][f 2 4 0][clr 27]?[f 1 4 1][n][w][e]

[msg SYS_PERSONA_DROP_NG]
[f 2 1]Você não pode libertar uma Persona que esteja equipada.[n][w][e]

[msg SYS_PERSONA_SET]
[f 2 1]Equipar esta Persona?[n][f 1 4 1][w][e]

[msg SYS_PERSONA_EQUIPED]
[f 2 1][clr 35][f 2 4 0][clr 27] já está equipada.[n][w][e]

[msg SYS_SKILL_FULL]
[f 2 1]Esta Persona não pode aprender mais habilidades. Escolha uma para esquecer.[n][w][e]

[msg SYS_SKILL_FORGET]
[f 2 1]Esquecer [clr 35][f 2 4 0][clr 27]?[n][f 1 4 1][w][e]

[msg SYS_BIRTH_CONCEPTION]
[f 2 1][clr 35][f 2 4 0][clr 27] criou [f 4 4 1 37 1 1].[n][w][e]

[msg SYS_SKILLCARD_ALREADY]
[f 2 1][clr 35][f 2 4 0][clr 27] já foi aprendido.[n][w][e]

[msg SYS_SKILL_CHANGE [Igor]]

[msg SYS_REMEMBER_CONF]
[f 2 1]Quer mesmo sair?[n][f 1 4 1][w][e]

[msg SYS_NO_EFFECT_INCENSE]
[f 2 1]O limite já foi alcançado.[n][w][e]

[msg SYS_SYSTEM_BACK_TO_TITLE]
[f 2 1]Voltar à tela inicial?[n][f 1 4 1][w][e]

[msg SYS_TITL_USE_NETWORK]
[f 2 1][f 1 4 1]Este jogo tem suporte a funcionalidades online quando conectado à rede.[n][f 1 5 0]Gostaria de ativar as funcionalidades?[n][w][e]

[msg SYS_TITL_DONT_USE_NETWOR]
[f 2 1]A funcionalidade de rede foi [clr 2]DESLIGADA[clr 27].[n][f 1 5 0]Você pode mudar isso a qualquer momento no menu Configurações.[n][w][e]

[msg SYS_SAVE_LOAD_CHECK]
[f 2 1]Carregar estes dados salvos?[n][f 1 4 1][w][e]

[msg SYS_SAVE_LOAD_OK [Igor]]

[msg SYS_SAVE_NETWORK_LOAD]
[f 2 1]Carregando dados salvos de rede...[n][w][e]

[msg SYS_SAVE_NETWORK_LOAD_OK]
[f 2 1]Dados salvos de rede carregados com sucesso.[n][w][e]

[msg SYS_SAVE_NETWORK_LOAD_ER]
[f 2 1]Não foi possível carregar os dados salvos de rede.[n][w][e]

[msg SYS_SAVE_NETWORK_UP]
[f 2 1]Enviando dados salvos...[n][w][e]

[msg SYS_SAVE_NETWORK_UP_OK]
[f 2 1]Dados salvos enviados com sucesso.[n][w][e]

[msg SYS_SAVE_NETWORK_UP_ERRO]
[f 2 1]Não foi possível enviar dados salvos.[n][w][e]

[msg SYS_SAVE_NETWORK_BROKEN]
[f 2 1]Dados salvos em rede corrompidos.[n][w][e]

[msg SYS_SAVE_NETWORK_INVALID]
[f 2 1]A funcionalidade de rede está desativada.[n][f 1 5 0]Você pode ativar no menu Configurações.[n][w][e]

[msg SYS_SAVE_NETWORK_NOTEXIS]
[f 2 1]Não há dados salvos na rede.[n][w][e]

[msg SYS_SAVE_OVERWRITE_CHECK]
[f 2 1]Já existem dados salvos.[n][f 1 5 0]Você quer substituir esses dados?[n][f 1 4 1][w][e]

[msg SYS_SAVE_OK [Igor]]

[msg SYS_SAVE_ROLLBACK_CHECK]
[f 2 1]Se voltar a este ponto, quaisquer dados de retrocesso mais recentes serão perdidos.[n][f 1 5 0]Continuar?[n][f 1 4 1][w][e]

[msg SYS_CONF_CLOSE_CHECK]
[f 2 1]Sair sem aplicar mudanças?[n][f 1 4 1][w][e]

[msg SYS_CONF_DIFF_CHECK]
[f 2 1]Se você sair da dificuldade Implacável, não poderá voltar.[n][f 1 5 0]Quer mesmo continuar?[n][f 1 4 1][w][e]

[msg SYS_CONF_DIFF_CHANGED]
[f 2 1]O nível de dificuldade foi alterado para [clr 2][f 2 4 0][clr 27].[n][w][e]

[msg SYS_CONF_CONNECT_ERROR]
[f 2 1]Erro na conexão de rede.[n][w][e]

[msg SYS_CONF_CONNECTING]
[f 2 1]Conectando-se à rede...[n][w][e]

[msg SYS_PARTY_MEMBEROVER_0_0]
[f 2 1]Você tem [f 2 4 0] integrante(s) além do tamanho máximo de grupo.[n][w][e]

[msg SYS_DIFFICULTY_CHECK]
[f 2 1]Começar o jogo na dificuldade [clr 2][f 2 4 0][clr 27]?[n][f 1 4 1][w][e]

[msg SYS_DIFFICULTY_DESC_SAFE]
[f 2 1]Para jogadores que querem se concentrar na história.[n][w][e]

[msg SYS_DIFFICULTY_DESC_EASY]
[f 2 1]Para jogadores casuais.[n][w][e]

[msg SYS_DIFFICULTY_DESC_NORM]
[f 2 1]Para jogadores experientes.[n][w][e]

[msg SYS_DIFFICULTY_DESC_HARD]
[f 2 1]Para jogadores que gostam de estratégia.[n][w][e]

[msg SYS_DIFFICULTY_DESC_LUNA]
[f 2 1]Para jogadores muito avançados.[n][w][e]

[msg SYS_DIFFICULTY_INFO_SAFE]
[f 2 1]O grupo é autorrevivido depois da derrota. [clr 43]Sua opção de dificuldade não afetará a história e poderá ser mudada a qualquer momento (exceto Implacável).[clr 27][n][w][e]

[msg SYS_DIFFICULTY_INFO_EASY]
[f 2 1]Combate pouco estressante. [clr 43]Sua opção de dificuldade não afetará a história e poderá ser mudada a qualquer momento (exceto Implacável).[clr 27][n][w][e]

[msg SYS_DIFFICULTY_INFO_NORM]
[f 2 1]Combate moderadamente desafiador. [clr 43]Sua opção de dificuldade não afetará a história e poderá ser mudada a qualquer momento (exceto Implacável).[clr 27][n][w][e]

[msg SYS_DIFFICULTY_INFO_HARD]
[f 2 1]Combate significativamente desafiador. [clr 43]Sua opção de dificuldade não afetará a história e poderá ser mudada a qualquer momento (exceto Implacável).[clr 27][n][w][e]

[msg SYS_DIFFICULTY_INFO_LUNA]
[f 2 1]Combate excessivamente desafiador. [clr 43]Sua opção de dificuldade não afetará a história e poderá ser mudada a qualquer momento, mas você não poderá voltar a Implacável depois de sair.[clr 27][n][w][e]

[msg MND_SKILL_NOT_CHANGE]
[f 2 1](Not used) [f 2 4 2] gave a sharp cry.[n][w][e]

[msg SYS_NETWORK_CONNECT_CHEC [Igor]]

[msg SYS_NETWORK_CONNECT_YES]
[f 2 1]A funcionalidade de rede foi [clr 2]LIGADA[clr 27].[n][f 1 5 0]Você pode mudar isso a qualquer momento no menu Configurações.[n][w][e]

[msg SYS_NETWORK_CONNECT_NO [Igor]]

[msg SYS_NETWORK_VOICE_ERROR]
[f 2 1]Erro de rede. Verifique sua conexão.[n][w][e]

[msg MSG_SKILL_CHANGE [Igor]]
[f 2 1]Hã? Uma das suas habilidades parece estar prestes a se transformar... Você quer deixar que aconteça?[n][w][e]

[sel SEL_SKILL_CHANGE top]
[f 2 1]Impedir troca de habilidade[e]
[f 2 1]Aceitar troca de habilidade[e]
[f 2 1]Conferir habilidades[e]

[msg SYS_PARTY_FIXED_MEMBER_0]
[f 2 1][f 2 4 0] tem que estar no grupo.[n][w][e]

[msg SYS_RECHECK_BACK_TO_TITL]
[f 2 1]Você perderá todo progresso feito desde a última vez que você salvou até este ponto.[n][f 1 5 0]Quer mesmo voltar à tela inicial?[n][f 1 4 1][w][e]

[msg SYS_GAMEDATA_INSTALL]
[f 2 1]Instalando dados de jogo...[n][w][e]

[msg SYS_GAMEDATA_INSTALL_OK]
[f 2 1]Instalação concluída.[n][w][e]

[msg SYS_ACTIVITY_DATA_NOT_MA]
[f 2 1]A atividade selecionada não corresponde ao estado dos dados salvos mais recentes.[n][f 1 5 0]O jogo começará normalmente.[n][w][e]

[msg SYS_KEYCONFIG_ASSIGN]
[f 2 1]Escolha a tecla a ser vinculada a [clr 35][f 2 4 0][clr 27].[n][f 1 5 0]Pressione ESC para voltar ao menu de configurações.[n][w][e]

[msg SYS_KEYCONFIG_OVERWRITE]
[f 2 1]Há um conflito com o seguinte vínculo de tecla: [clr 2][f 2 4 0][clr 27][n]Sobrescrever o vínculo de tecla existente?[n][f 1 4 1][w][e]

[msg SYS_KEYCONFIG_FINISH]
[f 2 1]Concluir com as configurações atuais?[n][f 1 4 1][w][e]

[msg SYS_KEYCONFIG_NOT_SET]
[f 2 1]Algumas configurações não foram definidas.[n][w][e]

[msg SYS_KEYCONFIG_RESET_KEYB]
[f 2 1]Restaurar ajustes de teclado às configurações padrão?[n][f 1 4 1][w][e]

[msg SYS_KEYCONFIG_RESET_MOUS]
[f 2 1]Restaurar ajustes de mouse às configurações padrão?[n][f 1 4 1][w][e]

[msg SYS_KEYCONFIG_RESET_GAME]
[f 2 1]Restaurar ajustes de gamepad às configurações padrão?[n][f 1 4 1][w][e]

[msg SYS_CONF_DISPLAY_CHECK]
[f 2 1]As configurações de exibição foram ajustadas. Quer manter as mudanças?[n][f 1 5 0]As configurações serão revertidas em [f 2 4 0] segundos se não houver ação do jogador.[n][f 1 4 1][w][e]

[msg SYS_INPUT_DEVICE_LOST]
[f 2 1]Um dispositivo foi desconectado. Verifique o status da conexão.[n][w][e]

[msg SYS_SAVE_NO_SPACE]
[f 2 1]Erro ao salvar. Verifique espaço de armazenamento disponível.[n][w][e]

[msg SYS_APP_QUIT]
[f 2 1]Sair do jogo?[n][f 1 4 1][w][e]

[msg SYS_APPLY_INIT_NAME_STOR]
[f 2 1]Devido a uma mudança nas configurações de idioma, o nome do protagonista será definido como "Kotone Shiomi".[n][f 1 5 0]Para restaurar o seu nome original, o idioma tem que ser o mesmo usado quando o nome foi inserido.[n][w][e]

[msg SYS_APPLY_INIT_NAME_NETW]
[f 2 1]Devido a uma mudança nas configurações de idioma, o nome do protagonista será definido como "Kotone Shiomi".[n][f 1 5 0]Para restaurar o seu nome original, o idioma tem que ser o mesmo usado quando o nome foi inserido.[n][w][e]

