[msg MSG_000_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 1 0 0]Hm, hm...[n][w][e]

[msg MSG_001_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 4 65535 65535 0 0][vp 1 0 0 2 0 0]Ah, desculpa se meu quarto estiver com cheiro de comida![n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 3 0 0][f 4 23 0 6 0 25 25]É que de vez em quando eu experimento minha comida aqui.[n][w][e]

[msg MSG_002_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 4 0 0]Não sei mais o cheiro do meu quarto porque já me acostumei...[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 5 0 0]Hm, v-você sabia que, dos cinco sentidos, o olfato é o que se adapta mais rápido, então, hm...[n][w][e]

[msg MSG_003_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 1 0][vp 0 0 0 6 0 0]...[n][w][e]

[msg MSG_003_5_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 1 0][vp 1 0 0 7 0 0]Desculpa, não sei o que estou dizendo...[n][w][e]

[sel SEL_004_0_0 top]
[f 2 1]Está nervosa?[e]
[f 2 1]Você parece você mesma.[e]

[msg MSG_005_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 8 0 0]S-Sim. Desculpa...[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 9 0 0]É que, hã...[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 10 0 0]Essa é a primeira vez que eu convido alguém para o meu quarto, então...[n][w][e]

[msg MSG_006_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 4 65535 65535 0 0][vp 1 0 0 11 0 0]S-Sério?[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 12 0 0][f 4 23 0 6 0 25 25]Bem, acho que é importante ser você mesmo.[n][w][e]

[msg MSG_006_5_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 13 0 0]... Obrigada.[n][w][e]

[msg MSG_007_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 14 0 0]Hum...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 15 0 0]Você lembra que eu disse que acho que não tenho forças para acreditar no futuro?[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 16 0 0]Bem, estar com você me fez entender por quê.[n][w][e]

[msg MSG_008_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 17 0 0]Acho que é porque eu não termino nada que começo.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 18 0 0]As pessoas que nunca conheceram a felicidade não conseguem se imaginar felizes no futuro...[n][w][e]

[msg MSG_008_5_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 19 0 0]E eu era assim. Sempre desistia antes de descobrir algo de bom na situação.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 20 0 0]Nunca tive um futuro para aguardar.[n][w][e]

[msg MSG_009_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 21 0 0]Mas...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 22 0 0]Eu... finalmente entendi como me sinto.[n][w][e]

[msg MSG_010_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 23 0 0]Então, hã...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 24 0 0]Senti que precisava te contar.[n][w][e]

[msg MSG_010_5_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 25 0 0]Ou melhor, eu queria te contar.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 26 0 0]Não importa se isso vai mudar as coisas entre a gente.[n][w][e]

[msg MSG_011_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 0 0 0 27 0 0]...[n][w][e]

[msg MSG_011_5_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 28 0 0]Sabe, acho que tenho o que é preciso para mudar. Devagar, mas vai acontecer.[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 29 0 0]Enquanto puder contar com você... Não vou me perder.[n][w][e]

[sel SEL_012_0_0 top]
[f 2 1]Bom saber.[e]
[f 2 1]Sempre estou aqui por você.[e]

[msg MSG_013_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 30 0 0][f 5 13 3 5 6]Muito obrigada. Sério.[n][w][e]

[msg MSG_014_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 0 0 0 31 0 0][f 5 13 3 15 6]...[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 32 0 0]Eu sei...[n][w][e]

[msg MSG_015_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 33 0 0]Ah, já ia esquecendo![n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 34 0 0]Tem algo que eu queria te dar.[n][w][e]

[msg MSG_016_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 35 0 0]Hum...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 36 0 0]Aqui está.[n][w][e]

[msg MSG_017_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 37 0 0]Como você está sempre ouvindo música, achei que ia gostar.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 38 0 0]E acho que você é fã desse design, então tentei combinar...[n][w][e]

[msg MND_018_0_0]
[f 2 1]DEV: *Unused message labels. [n][f 1 5 0]*If this appears, it is a bug.[n][w][e]

[msg MSG_019_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 39 0 0]É um presente de coração...[n][w][e]

[msg MSG_019_5_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 40 0 0]Lembra que eu falei que eu sou boa com máquinas?[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 41 0 0]Bem, queria que você visse esse lado meu em vez do lado cozinheira.[n][w][e]
[f 2 1][bup 6 1 65535 65535 1 0][vp 1 0 0 42 0 0]Quero que você saiba tudo sobre mim.[n][w][e]

[msg MND_020_0_0]
[f 2 1]Troquei meus antigos fones[n]pelos que a Fuuka me deu.[n][w][e]

[msg MND_021_0_0]
[f 2 1]!![n][w][e]
[f 2 1]A qualidade do som é ótima![n][w][e]
[f 2 1]As habilidades técnicas dela devem ser incríveis.[n][w][e]

[msg MSG_022_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 43 0 0]Então... O que achou?[n][w][e]

[sel SEL_023_0_0 top]
[f 2 1]Eu adorei![e]
[f 2 1]Suas habilidades são impressionantes.[e]

[msg MSG_024_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 44 0 0][f 5 13 3 15 6]É mesmo? Ah, que bom![n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 45 0 0]Quando usá-los, é como se eu estivesse lá com você. Não importa onde a gente esteja...[n][w][e]

[msg MND_025_0_0]
[f 2 1]Fuuka está olhando fixamente para mim...[n][w][e]

[msg MSG_026_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 46 0 0][f 5 13 3 5 6]Ah, nada de mais. É só um hobby.[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 47 0 0][f 4 23 0 6 1 25 25]Que bom que você gostou.[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 48 0 0]Quando usá-los, é como se eu estivesse lá com você. Não importa onde a gente esteja...[n][w][e]

[msg MND_027_0_0]
[f 2 1]Fuuka está olhando fixamente para mim...[n][w][e]

[msg MND_028_0_0]
[f 2 1]Sinto que tenho um laço muito forte com a Fuuka...[n][w][e]

[msg SYS_029_0_0]
[f 2 1]O Vínculo Social da Sacerdotisa chegou ao nível máximo![n]Agora você pode fundir [clr 35]Scáthach[clr 27], a Mentora![n][w][e]

[msg MSG_030_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 49 0 0]Ah, desculpa...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 50 0 0]Eu estava me divertindo, não quis ficar te prendendo aqui.[n][w][e]

[msg MSG_031_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 4 65535 65535 0 0][vp 1 0 0 51 0 0]Ah! Não percebi que estava tão tarde.[n][w][e]
[f 2 1][bup 6 0 65535 65535 1 0][vp 0 0 0 52 0 0][f 4 23 0 6 0 25 25]...[n][w][e]

[msg MSG_032_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 1 0][vp 1 0 0 53 0 0]Hum...[n][w][e]
[f 2 1][bup 6 3 65535 65535 1 0][vp 1 0 0 54 0 0]Ainda temos tempo, né?[n][w][e]

[msg MSG_032_5_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 1 0][vp 1 0 0 55 0 0]Só mais um pouco...[n][w][e]

[msg MSG_033_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 1 0][vp 1 0 0 56 0 0]Por favor... Fique comigo.[n][w][e]
[f 2 1][bup 6 1 65535 65535 1 0][vp 0 0 0 57 0 0][f 4 23 0 6 1 25 25]...[n][w][e]

[msg MND_034_0_0]
[f 2 1]Passei um bom tempo com a Fuuka.[n][w][e]

