[msg MSG_000_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 3 0 65535 11050 0 0]Tenho ouvido muita gente falar daquela Síndrome da Apatia ultimamente...[n][w][e]

[msg MSG_001_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0]Mas tenho certeza que aquelas crianças não pegam de jeito nenhum. Elas estão empolgadas demais com a corrida, sabe?[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0][f 4 23 0 106 1 25 25]É uma meninada muito incrível...[n][w][e]

[msg MSG_002_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 3 0 65535 11083 0 0]Tenho um pouco de inveja... já que eu não tenho o mesmo entusiasmo por nada assim.[n][w][e]

[sel SEL_003_0_0 top]
[f 2 1]Não desista ainda.[e]
[f 2 1]Vai encontrar o seu caminho.[e]
[f 2 1]Você também é incrível.[e]

[msg MSG_004_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 2 65535 65535 0 0][vp 3 0 65535 11069 0 0]Hã? Também não precisa falar desse jeito... Eu não desisti de nada. Só não encontrei o caminho certo pra mim ainda.[n][w][e]
[f 2 1][bup 106 3 65535 65535 0 0][f 4 23 0 106 3 25 25]Desculpa... Você só tava tentando me animar, né?[n][w][e]
[f 2 1][bup 106 3 65535 65535 0 0]Qual o problema comigo hoje? Vai ver estou só nervosa com o torneio que se aproxima...[n][w][e]

[msg MND_005_0_0]
[f 2 1]De repente, Yuko ficou em silêncio.[n][w][e]
[f 2 1]Acho que não nos aproximamos hoje...[n][w][e]

[msg MSG_006_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 3 0 65535 11081 0 0][f 5 13 12 30 106]V-Você acha mesmo? Obrigada. Fico melhor ouvindo isso de você...[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0]Ando tão ocupada como gerente da equipe e treinadora daquelas crianças... Não que eu me importe, claro.[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0]Não tenho muito tempo livre ultimamente, mas... Não sei, é um sentimento bem... gratificante, sabe?[n][w][e]

[msg MND_007_0_0]
[f 2 1]Yuko parece estar muito feliz.[n][w][e]
[f 2 1]Acho que nos aproximamos muito hoje.[n][w][e]

[msg MSG_008_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 3 0 65535 11030 0 0][f 5 13 12 15 106]Ah, deixa disso... Você tá me dando mais crédito do que mereço![n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0]Mas até que me cai bem o título de gerente de equipe e treinadora.[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0]Vamos fazer o seguinte... Se aquelas crianças ganharem a grande corrida, aí sim você pode me elogiar.[n][w][e]

[msg MND_009_0_0]
[f 2 1]Yuko parece meio envergonhada.[n][w][e]
[f 2 1]Eu aprendi mais a respeito dela hoje.[n][w][e]

[msg MSG_010_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0]Tá certo, vou rezar por um pouco de sorte. Só quero que aquelas crianças mostrem o quanto elas treinaram.[n][w][e]

[msg MSG_011_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 3 0 65535 11061 0 0]Então, hum... você se importa de ir ao santuário comigo?[n][w][e]

[msg MND_012_0_0]
[f 2 1]Depois de rezar no santuário com a Yuko,[n]decidi voltar para o dormitório.[n][w][e]

