[msg MSG_000_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 1 0 0]Ah, esqueci de te falar. Aquela menina veio me encher o saco de novo durante o almoço.[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 2 0 0]Você lembra, né? Aquela que colocou chiclete no meu armário.[n][w][e]
[f 2 1][bup 106 2 65535 65535 0 0][vp 1 0 0 3 0 0][f 4 23 0 106 2 25 25]Bom, dessa vez, eu disse tudo o que eu pensava bem na cara dela. Que ela devia descobrir o que quer fazer da vida.[n][w][e]

[msg MSG_001_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 4 0 0]Ela não deve ter entendido nada, mas desde que eu descobri o que quero pra mim, acho que consigo ver as coisas que importam de verdade.[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 5 0 0][f 4 23 0 106 1 25 25]Assim, eu costumava ser mais ou menos como ela, sabe? Acho que aprendi a ter mais empatia agora.[n][w][e]
[f 2 1][bup 106 0 65535 65535 1 0][vp 1 0 0 6 0 0][f 4 23 0 106 0 25 25]Sem contar que você acabou se tornando minha namorada, então...[n][w][e]

[msg MSG_002_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 1 0][vp 1 0 0 7 0 0]Mas, hã, não foi por isso que eu chamei você aqui![n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 8 0 0][f 4 23 0 106 0 25 25]Dava pra ter te contado sobre isso na escola, mas eu queria conversar num lugar mais tranquilo.[n][w][e]

[sel SEL_003_0_0 top]
[f 2 1]É tão importante assim?[e]
[f 2 1]O que foi?[e]

[msg MSG_004_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 9 0 0][f 5 13 12 5 106]Hmmm, mais ou menos... Mas não é nada tão sério assim.[n][w][e]

[msg MSG_005_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 4 65535 65535 0 0][vp 1 0 0 10 0 0][f 5 13 12 5 106] N-Não seja tão impaciente! Eu já ia chegar lá. Ah, por que eu que tô ficando nervosa agora...?[n][w][e]

[msg MSG_006_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 11 0 0]Então, sabe as crianças que a gente treinou?[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 12 0 0][f 4 23 0 106 1 25 25]Todas elas escreveram mensagens pra gente.[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 13 0 0]Eu sei que elas davam trabalho, mas elas também têm um lado encantador, né não?[n][w][e]

[sel SEL_007_0_0 top]
[f 2 1]É.[e]
[f 2 1]Na verdade, não.[e]

[msg MSG_008_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 14 0 0][f 5 13 12 5 106]Ah, [nl]-chan, você é muito fofa.[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 15 0 0][f 4 23 0 106 0 25 25]Às vezes, você é tão mente aberta que eu mal consigo acreditar... Preciso aprender mais com você.[n][w][e]

[msg MSG_009_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 16 0 0][f 5 13 12 5 106]Hahaha, que crueldade.[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 17 0 0]Mas eu sei que você estava sempre cuidando deles. Acho que você daria uma boa treinadora, de verdade.[n][w][e]

[msg MSG_010_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 18 0 0]Aqui, essa é pra você.[n][w][e]

[msg MND_011_0_0]
[f 2 1]Eu obtive (ITEM NAME)![n][w][e]

[msg MSG_012_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 19 0 0]As crianças disseram pra entregar pra minha namorada... Elas não são fofas?[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 20 0 0]Foi pra isso que te chamei aqui.[n][w][e]
[f 2 1][bup 106 0 65535 65535 1 0][vp 0 0 0 21 0 0][f 4 23 0 106 0 25 25]...[n][w][e]
[f 2 1][bup 106 0 65535 65535 1 0][vp 1 0 0 22 0 0]Bom, na verdade, isso foi apenas uma desculpa.[n][w][e]
[f 2 1][bup 106 3 65535 65535 1 0][vp 1 0 0 23 0 0][f 4 23 0 106 3 25 25]Porque hoje... Bom, meus pais não estão em casa, então...[n][w][e]

[sel SEL_013_0_0 top]
[f 2 1]Entendo.[e]
[f 2 1]O que isso quer dizer?[e]

[msg MSG_014_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 1 0][vp 1 0 0 24 0 0]P-Pois é. E-Então, hum...[n][w][e]

[msg MSG_015_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 1 0][vp 1 0 0 25 0 0]O que eu quis dizer é que você pode ficar à vontade e relaxar! Não vamos levar bronca se fizermos barulho. H-Haha...[n][w][e]

[msg MSG_016_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 4 65535 65535 1 0][vp 1 0 0 26 0 0]N-Não me faça dizer isso em voz alta! Eu sou uma garota, sabe...[n][w][e]

[msg MSG_017_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 3 65535 65535 1 0][vp 1 0 0 27 0 0][f 5 13 12 5 106]E-Ei, não fica me encarando. Eu sei que meu rosto tá todo vermelho...[n][w][e]

[msg MSG_018_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 1 0][vp 1 0 0 28 0 0]É só que... eu consegui encontrar a minha verdadeira vocação graças a você, [nl]-chan.[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 29 0 0][f 4 23 0 106 1 25 25]Estou tão feliz por ter te conhecido.[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 30 0 0]É assim que eu me sinto de verdade, e espero que você sinta o mesmo.[n][w][e]
[f 2 1][bup 106 0 65535 65535 1 0][vp 1 0 0 31 0 0][f 4 23 0 106 0 25 25]Então, você vai ficar comigo mais um pouco?[n][w][e]

[msg MND_019_0_0]
[f 2 1]Yuko declarou seu amor por mim.[n][w][e]

[msg SYS_020_0_0]
[f 2 1]O Vínculo Social da Força chegou ao nível máximo![n]Agora você pode fundir [clr 35]Atavaka[clr 27], o Rei General da Sabedoria![n][w][e]

[msg MSG_021_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 1 0][vp 1 0 0 32 0 0]Eu... amo você.[n][w][e]
[f 2 1][bup 106 1 65535 65535 1 0][vp 1 0 0 33 0 0][f 4 23 0 106 1 25 25]De verdade.[n][w][e]

[msg MND_022_0_0]
[f 2 1]Eu passei uma noite especial com Yuko.[n][w][e]

