[msg MSG_000_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 3 0 65535 5131 0 0][f 5 13 3 5 6]Então, li isso num livro outro dia...[n][w][e]

[msg MND_001_0_0 [DEV: Internal MES]]
[f 2 1]Sinto que meu laço com Fuuka fica mais forte[n]cada vez que passamos um tempo juntas...[n][w][e]

[msg MND_002_0_0 [DEV: Internal MES]]
[f 2 1]Sinto que nossa relação[n]se fortalecerá ainda mais em breve...[n][w][e]

[msg MND_003_0_0 [DEV: Internal MES]]
[f 2 1]Finalmente é hora da saída na escola...[n][w][e]
[f 2 1]Decidi voltar ao dormitório.[n][w][e]

