[msg MSG_000_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 3 65535 65535 0 0][vp 1 0 0 1 0 0]Escolher um restaurante tá difícil.[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 2 0 0][f 4 23 0 1 0 25 25]Esse lugar é encantador, mas esse aqui parece ser mais em conta...[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 3 0 0]Qual você prefere, [nl]-chan?[n][w][e]

[sel SEL_001_0_0 top]
[f 2 1]O encantador.[e]
[f 2 1]O mais em conta.[e]
[f 2 1]Tanto faz.[e]

[msg MSG_002_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 3 65535 65535 0 0][vp 1 0 0 4 0 0][f 5 13 12 5 106]Pois é. Seria bom comemorar em um lugar com ambiente agradável, né?[n][w][e]
[f 2 1][bup 106 3 65535 65535 0 0][vp 1 0 0 5 0 0]Mas temos que tentar fazer valer o nosso dinheiro também...[n][w][e]

[msg MSG_003_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 6 0 0][f 5 13 12 5 106]Aí sim! Não dá pra chamar de festa se não tiver muita comida![n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 7 0 0][f 4 23 0 1 0 25 25]Mas também seria legal comemorar em um lugar com ambiente agradável...[n][w][e]

[msg MSG_004_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 2 65535 65535 0 0][vp 1 0 0 8 0 0]Essa resposta não ajuda nada, viu. Acho que depende de mim então.[n][w][e]

[msg MSG_005_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 9 0 0]Hmm... Talvez os dois?[n][w][e]

[msg MSG_006_0_0 [Garota de meia-calça preta]]
[f 2 1][vp 1 0 0 10 0 0][f 5 21 0 10]Ah, Nishiwaki-san.[n][w][e]

[msg MSG_007_0_0 [Garota de cabelo claro]]
[f 2 1][vp 1 0 0 11 0 0][f 5 21 0 11]Tá com a namorada de novo, hein? Você adora se exibir, né?[n][w][e]

[msg MSG_008_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 3 65535 65535 0 0][vp 1 0 0 12 0 0]Já disse que não é nada disso.[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 13 0 0][f 4 23 0 1 0 25 25]Ela é apenas uma colega de equipe. Só isso.[n][w][e]

[msg MSG_009_0_0 [Garota de meia-calça preta]]
[f 2 1][vp 1 0 0 14 0 0][f 5 21 0 10]Você sabe que não precisa se esforçar tanto pra esconder.[n][w][e]

[msg MSG_010_0_0 [Garota de cabelo claro]]
[f 2 1][vp 1 0 0 15 0 0][f 5 21 0 11]Deve ter um motivo pra ela não querer falar disso. Tipo, talvez ela tenha roubado a namorada de alguém de novo?[n][w][e]

[msg MSG_011_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 2 65535 65535 0 0][vp 1 0 0 16 0 0]Nossa, dá um tempo![n][w][e]
[f 2 1][bup 106 2 65535 65535 0 0][vp 1 0 0 17 0 0]É só nisso que você consegue pensar quando vê duas pessoas andando juntas? Tá na hora de crescer, viu.[n][w][e]

[msg MSG_012_0_0 [Garota de cabelo claro]]
[f 2 1][vp 1 0 0 18 0 0][f 5 21 0 11]É o quê...?[n][w][e]

[msg MSG_013_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 19 0 0]Olha, eu sei que você me odeia.[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 20 0 0]Quando você passa por uma experiência ruim, é difícil de superar.[n][w][e]
[f 2 1][bup 106 2 65535 65535 0 0][vp 1 0 0 21 0 0][f 4 23 0 1 2 25 25]Mas ficar atormentando as pessoas por causa isso... não é nada legal.[n][w][e]

[msg MSG_014_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 2 65535 65535 0 0][vp 1 0 0 22 0 0]E, foi mal, mas não tenho tempo pra te aturar agora.[n][w][e]
[f 2 1][bup 106 2 65535 65535 0 0][vp 1 0 0 23 0 0]Eu encontrei um objetivo que é importante pra mim e eu vou alcançá-lo.[n][w][e]

[msg MSG_015_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 24 0 0]E você?[n][w][e]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 25 0 0]O que você está fazendo aqui agora é importante?[n][w][e]

[msg MSG_016_0_0 [Garota de meia-calça preta]]
[f 2 1][vp 0 0 0 26 0 0]...[n][w][e]

[msg MSG_017_0_0 [Garota de cabelo claro]]
[f 2 1][vp 1 0 0 27 0 0][f 5 21 0 11]Como é que é? Foi você que começou...[n][w][e]

[msg MSG_018_0_0 [Garota de meia-calça preta]]
[f 2 1][vp 1 0 0 28 0 0][f 5 21 0 10]Deixa pra lá. Vamos embora.[n][w][e]

[msg MSG_019_0_0 [Garota de cabelo claro]]
[f 2 1][vp 1 0 0 29 0 0][f 5 21 0 11]Ei, me espera![n][w][e]

[msg MSG_020_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 3 65535 65535 0 0][vp 1 0 0 30 0 0]Desculpe por sempre te arrastar pra situações como essa.[n][w][e]

[sel SEL_021_0_0 top]
[f 2 1]Que bom que não deu em briga.[e]
[f 2 1]Você lidou bem com a situação.[e]

[msg MSG_022_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 31 0 0]É porque eu tenho uma amiga confiável como você ao meu lado. Você me deu a coragem que eu precisava.[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 32 0 0]E se algo realmente acontecesse, tenho certeza que você iria intervir.[n][w][e]

[msg MSG_023_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 3 65535 65535 0 0][vp 1 0 0 33 0 0]Sabe, se as coisas tivessem sido diferentes, eu poderia ter ficado igual a ela também.[n][w][e]
[f 2 1][bup 106 3 65535 65535 0 0][vp 1 0 0 34 0 0]Presa na minha pequena bolha, incapaz de dar o primeiro passo adiante...[n][w][e]

[msg MSG_023_5_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 35 0 0]Bom, eu não quero complicar demais as coisas nem nada.[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 36 0 0]Só estou feliz por ter uma amiga tão incrível![n][w][e]

[msg MND_024_0_0]
[f 2 1]Sinto que Yuko confia em mim.[n][w][e]
[f 2 1]Sinto que minha relação com ela está amadurecendo...[n][w][e]

[msg MSG_025_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 37 0 0]Ah, cara! Eu tô morrendo de fome![n][w][e]
[f 2 1][bup 106 3 65535 65535 0 0][vp 1 0 0 38 0 0][f 4 23 0 1 3 25 25]Pensar e falar ao mesmo tempo é cansativo...[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 39 0 0][f 4 23 0 1 1 25 25]Vamos jantar. Ah, quer dizer, vamos pra nossa festa de comemoração![n][w][e]

[msg MND_026_0_0]
[f 2 1]Fui comemorar com Yuko. Comi tanto[n]que meu estômago está prestes a explodir.[n][w][e]
[f 2 1]Eu deveria voltar para o dormitório...[n][w][e]

