[msg MSG_000_0_0 [Diretor]]
[f 2 1][bup 1181 0 65535 65535 0 0][vp 1 0 0 1 0 0][f 5 21 0 1]Assim, outro ano letivo começa.[n][w][e]
[f 2 1][bup 1181 0 65535 65535 0 0][vp 1 0 0 2 0 0][f 5 21 0 1]Quero que cada um de vocês se lembre da seguinte máxima: "se vai fazer, que faça direito".[n][w][e]
[f 2 1][bup 1181 0 65535 65535 0 0][vp 1 0 0 3 0 0][f 5 21 0 1]Na vida estudantil, isso quer dizer...[n][w][e]

[msg MND_001_0_0]
[f 2 1]O diretor continua o discurso...[n][w][e]

[msg MSG_002_0_0 [Colega de classe]]
[f 2 1][vp 1 0 0 4 0 0][f 5 21 0 2]Psst. Ei.[n][w][e]

[msg MSG_003_0_0 [Colega de classe]]
[f 2 1][vp 1 0 0 5 0 0][f 5 21 0 2]Você veio pra escola com a Takeba-san hoje, né?[n][w][e]
[f 2 1][vp 1 0 0 6 0 0][f 5 21 0 2]Eu vi vocês andando juntas. Devem ser chegadas, né?[n][w][e]
[f 2 1][vp 1 0 0 7 0 0][f 5 21 0 2]Qual é o lance entre vocês duas?[n][w][e]
[f 2 1][vp 1 0 0 8 0 0][f 5 21 0 2]Ah, e ela tem namorado? Parece que ninguém sabe.[n][w][e]

[sel SEL_004_0_0 top]
[f 2 1]Ela tem.[e]
[f 2 1]Ela não tem.[e]
[f 2 1]Não sei.[e]

[msg MSG_005_0_0 [Colega de classe]]
[f 2 1][vp 1 0 0 9 0 0][f 5 21 0 2]Cara, eu sabia...[n][w][e]
[f 2 1][vp 1 0 0 10 0 0][f 5 21 0 2]Tipo, por que ela não teria, né?[n][w][e]
[f 2 1][vp 1 0 0 11 0 0][f 5 21 0 2]Pera, vocês são bem chegadas?[n][w][e]

[msg MSG_006_0_0 [Colega de classe]]
[f 2 1][vp 1 0 0 12 0 0]Sério? Você perguntou?[n][w][e]
[f 2 1][vp 1 0 0 13 0 0]Uau, que chocante...[n][w][e]
[f 2 1][vp 1 0 0 14 0 0]Pera, vocês são bem chegadas?[n][w][e]

[msg MSG_007_0_0 [Colega de classe]]
[f 2 1][vp 1 0 0 15 0 0][f 5 21 0 2]Ah, sério?[n][w][e]
[f 2 1][vp 1 0 0 16 0 0][f 5 21 0 2]Pensei que você soubesse, mas... acho que não.[n][w][e]
[f 2 1][vp 1 0 0 17 0 0][f 5 21 0 2]Pera, vocês são bem chegadas?[n][w][e]

[msg MSG_008_0_0 [Professor de outra turma]]
[f 2 1][vp 1 0 0 18 0 0][f 5 21 0 1]Hã? Tem alguém conversando![n][w][e]
[f 2 1][vp 1 0 0 19 0 0][f 5 21 0 1]Parece que está vindo da turma da Srta. Toriumi.[n][w][e]

[msg MSG_009_0_0 [Srta. Toriumi]]
[f 2 1][bup 1581 2 65535 65535 0 0][vp 1 0 0 20 0 0]Ei, xiu! Silêncio! Assim vocês vão me encrencar![n][w][e]

