[msg MSG_000_0_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 0 65535 65535 0 0][vp 1 0 0 1 0 0][f 4 23 0 1 0 25 25][nl]-chan, você tá pronta pra sair?[n][w][e]

[msg MSG_000_5_0 [Yuko Nishiwaki]]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 2 0 0][f 4 23 0 1 1 25 25]Agora é descobrir pra onde vamos... O que você acha de irmos ao Kiri Shopping?[n][w][e]
[f 2 1][bup 106 1 65535 65535 0 0][vp 1 0 0 3 0 0][f 4 23 0 1 1 25 25]Ouvi dizer que eles têm algumas decorações e luzes bem legais por lá.[n][w][e]

[msg MND_001_0_0 [Monólogo interno]]
[f 2 1]Decidi passar a véspera de Natal com a Yuko...[n][w][e]

