[msg MND_000_0_0]
[f 2 1]Parece que Sanada não chegou ainda...[n][w][e]

[msg MSG_001_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 1 0 0]Desculpa o atraso, eu tive uns contratempos.[n][w][e]

[msg MSG_002_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 2 0 0]Tá, lá vai. Me dá cobertura, pode ser?[n][w][e]

[msg MSG_003_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 3 0 0]Eu vou fazer panquecas. Acha que pode ajudar?[n][w][e]
[f 2 1][bup 4 1 65535 65535 0 0][vp 1 0 0 4 0 0][f 4 23 0 1 1 25 25]Pode-se dizer que eu ando com desejo... Eu comia panqueca direto no orfanato.[n][w][e]
[f 2 1][bup 4 1 65535 65535 0 0][vp 1 0 0 5 0 0][f 4 23 0 1 1 25 25]Sei que vendem umas congeladas hoje em dia, mas nada melhor do que umas fresquinhas, né?[n][w][e]

[sel SEL_004_0_0 top]
[f 2 1]Por que agora?[e]
[f 2 1]Você vai fazer um monte...[e]

[msg MSG_005_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 6 0 0]Eu não preciso de motivo, preciso? Só me deu na telha.[n][w][e]

[msg MSG_006_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 7 0 0]Acha mesmo? Pensei que fosse melhor sobrar do que faltar.[n][w][e]

[msg MSG_007_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 8 0 0]Bem, vamos começar. Tá, aos primeiros passos...[n][w][e]

[msg MSG_008_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 9 0 0]Hã... Qual é o primeiro passo?[n][w][e]

[msg MSG_009_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 10 0 0]Se não me engano, a receita disse para usar muita manteiga e regular a temperatura com um pano úmido...[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 11 0 0]... Espera, o pano vai na frigideira? E não queima?[n][w][e]

[sel SEL_010_0_0 top]
[f 2 1]Quer que eu faça?[e]
[f 2 1]Deixa que eu cuido disso...[e]

[msg MSG_011_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 12 0 0]Tem certeza? Valeu. Eu não sei cozinhar além do que eu faço pro treino.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 13 0 0]Eu quebro os ovos e misturo a manteiga. Vou deixar o cozimento mesmo com você.[n][w][e]

[msg MSG_012_0_0 [Akihiko Sanada (Fundo)]]
[f 2 1][vp 1 0 0 14 0 0]Ah, então é assim que se usa o pano.[n][w][e]

[msg MSG_013_0_0 [Akihiko Sanada (Fundo)]]
[f 2 1][vp 1 0 0 15 0 0]Que tal a gente acrescentar proteína em pó...?[n][w][e]

[msg MSG_014_0_0 [Akihiko Sanada (Fundo)]]
[f 2 1][vp 1 0 0 16 0 0]Ei, não me encara assim.[n][w][e]

[msg MSG_015_0_0 [Akihiko Sanada]]

[msg MSG_016_0_0 [Akihiko Sanada]]

[msg MSG_017_0_0 [Akihiko Sanada (Fundo)]]
[f 2 1][vp 1 0 0 19 0 0]Ah, melhor eu pegar os pratos.[n][w][e]

[msg MSG_018_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 1 65535 65535 0 0][vp 1 0 0 20 0 0]Tá, acho que isso vai dar.[n][w][e]

[msg MSG_019_0_0 [Yukari Takeba]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 21 0 0]Ah, olha só![n][w][e]

[msg MSG_020_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 22 0 0]Uau, quantas panquecas! Bem que eu tinha sentido um cheirinho bom.[n][w][e]

[msg MSG_021_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 1 65535 65535 0 0][vp 1 0 0 23 0 0]É, só um minutinho. A gente come assim que eu tirar elas daqui.[n][w][e]
[f 2 1][bup 4 1 65535 65535 0 0][vp 1 0 0 24 0 0]Podem reunir o resto do pessoal? E não esqueçam o Amada.[n][w][e]

[msg MSG_022_0_0 [Yukari Takeba (Fundo)]]
[f 2 1][bup 2 1 65535 65535 0 0][vp 1 0 0 25 0 0]Tá booom![n][w][e]

[msg MSG_023_0_0 [Fuuka Yamagishi (Fundo)]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 26 0 0]Tá legal![n][w][e]

[msg MSG_024_0_0 [Junpei Iori]]
[f 2 1][bup 3 1 65535 65535 0 0][vp 1 0 0 27 0 0]Nossa... É tipo um Tártaro de panquecas![n][w][e]

[msg MSG_025_0_0 [Ken Amada]]
[f 2 1][bup 8 0 65535 65535 0 0][vp 1 0 0 28 0 0]Vocês dois fizeram isso tudo sozinhos?[n][w][e]

[msg MSG_026_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 1 65535 65535 0 0][vp 1 0 0 29 0 0]É, mas foi a [nl] que cozinhou. Eu meio que tava com um desejo, mas a gente acabou fazendo demais.[n][w][e]
[f 2 1][bup 4 1 65535 65535 0 0][vp 1 0 0 30 0 0]Eu gosto de panquecas, mas de jeito nenhum eu consigo encarar isso tudo. Se vocês puderem ajudar, seria ótimo.[n][w][e]

[msg MSG_027_0_0 [Ken Amada]]
[f 2 1][bup 8 1 65535 65535 0 0][vp 1 0 0 31 0 0]Então você gosta de panquecas também, Sanada-san...[n][w][e]
[f 2 1][bup 8 1 65535 65535 0 0][vp 1 0 0 32 0 0]Obrigado! Mal posso esperar pra comer algumas![n][w][e]

[msg MSG_028_0_0 [Mitsuru Kirijo]]
[f 2 1][bup 5 1 65535 65535 0 0][vp 1 0 0 33 0 0]Eu vou preparar um chá. Tenho umas folhas ideais para a ocasião.[n][w][e]

[msg MSG_029_0_0 [Aigis]]
[f 2 1][bup 7 1 65535 65535 0 0][vp 1 0 0 34 0 0]É hora da festa das panquecas...! Bom, é como dizem...[n][w][e]

[msg MSG_030_0_0 [Koromaru]]
[f 2 1][bup 9 1 65535 65535 0 0][vp 1 0 0 35 0 0]Arf![n][w][e]

[msg MSG_031_0_0 [Ken Amada (Fundo)]]
[f 2 1][vp 1 0 0 36 0 0]Nossa, que delícia! Eu podia comer sem parar![n][w][e]

[msg MSG_032_0_0 [Akihiko Sanada (Fundo)]]
[f 2 1][vp 1 0 0 37 0 0]Ah, é? Que bom.[n][w][e]

[msg MSG_033_0_0 [Fuuka Yamagishi (Fundo)]]
[f 2 1][vp 1 0 0 38 0 0]O sabor me deixou até mais feliz![n][w][e]

[msg MSG_034_0_0 [Junpei Iori (Fundo)]]
[f 2 1][vp 1 0 0 39 0 0]Você diria que essa panqueca foi uma... pancada de boa?[n][w][e]

[msg MSG_035_0_0 [Yukari Takeba (Fundo)]]
[f 2 1][vp 1 0 0 40 0 0]Ué, virou o presidente do conselho agora?[n][w][e]
[f 2 1][vp 1 0 0 41 0 0]Mas olha, elas ficaram uma delícia mesmo![n][w][e]

[msg MSG_036_0_0 [Mitsuru Kirijo (Fundo)]]
[f 2 1][vp 1 0 0 42 0 0]As panquecas estão num ponto perfeito. Meus elogios ao chef.[n][w][e]

[msg MSG_037_0_0 [Aigis (Fundo)]]
[f 2 1][vp 1 0 0 43 0 0]Qual é a diferença entre panquecas e pizzas?[n][w][e]

[msg MSG_038_0_0 [Koromaru (Fundo)]]
[f 2 1][vp 1 0 0 44 0 0]Arf, arf![n][w][e]

[msg MSG_039_0_0 [Ken Amada]]
[f 2 1][bup 8 1 65535 65535 0 0][vp 1 0 0 45 0 0]Obrigado de novo pelas panquecas. Elas ficaram maravilhosas.[n][w][e]
[f 2 1][bup 8 1 65535 65535 0 0][vp 1 0 0 46 0 0]Não sei bem nem como explicar, mas senti um gostinho todo especial.[n][w][e]
[f 2 1][bup 8 1 65535 65535 0 0][vp 1 0 0 47 0 0]Se fizerem mais um dia desses, eu adoraria ajudar de novo![n][w][e]

[msg MSG_040_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 1 65535 65535 0 0][vp 1 0 0 48 0 0]A gente fez um monte, mas acabaram num piscar de olhos.[n][w][e]

[msg MSG_041_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 49 0 0]Cozinhar não é muito o meu forte.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 50 0 0]Como certa pessoa sempre dizia: "Se for pra botar proteína em pó nos ingredientes, então não vai pra cozinha, seu tonto".[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 51 0 0]Eu sempre só fiquei vendo outras pessoas cozinharem, então nunca aprendi eu mesmo.[n][w][e]
[f 2 1][bup 4 1 65535 65535 0 0][vp 1 0 0 52 0 0][f 4 23 0 1 1 25 25]Enfim, valeu pela ajuda hoje. Tomara que tenha animado um pouco a turma.[n][w][e]

[sel SEL_042_0_0 top]
[f 2 1]Esse era o seu plano desde o princípio?[e]
[f 2 1]Por que você quis fazer isso?[e]

[msg MSG_043_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 53 0 0]Na verdade, sim.[n][w][e]

[msg MSG_044_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 54 0 0]Era o que faziam quando eu morava lá no orfanato. Eu quis meio que recriar a situação.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 55 0 0]Minha irmã vivia chorando lá, mas as panquecas sempre a faziam sorrir de novo.[n][w][e]

[msg MSG_045_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 0 0 0 56 0 0]...[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 57 0 0]Você... se lembra daquela medalha que encontrou no pacote dos meus pais?[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 58 0 0]Minha irmã, Miki... Foi quem fez a medalha, lá na época do orfanato.[n][w][e]

[msg MSG_046_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 59 0 0]Segundo a carta que veio junto, meus pais a encontraram na faxina.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 60 0 0]Miki quis me dar a medalha quando descobrimos que eu estava sendo adotado e ia embora.[n][w][e]
[f 2 1][bup 4 3 65535 65535 0 0][vp 1 0 0 61 0 0][f 4 23 0 1 3 25 25]Mas... aí rolou aquele incêndio, e agora a medalha é tudo o que sobrou dela.[n][w][e]

[sel SEL_047_0_0 top]
[f 2 1]Parece que vocês eram chegados.[e]
[f 2 1]Sinto muito por isso.[e]

[msg MSG_048_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 62 0 0]Aparentemente... Miki sempre dizia que queria me agradecer por ser tão forte e atencioso.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 63 0 0]Ela era bem quietinha e vivia me seguindo pelos lugares.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 64 0 0]Eu não me lembro de ter feito nada de especial por ela, mas acho que Miki dependia de mim como irmão mais velho.[n][w][e]

[msg MSG_049_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 65 0 0]Ver a medalha me fez refletir.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 66 0 0]Minha irmã se orgulharia de quem eu me tornei?[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 67 0 0]Eu sou forte e atencioso o suficiente pra merecer essa medalha?[n][w][e]

[msg MSG_050_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 3 65535 65535 0 0][vp 1 0 0 68 0 0]Sinceramente, não sei bem o que significa ser forte ou atencioso.[n][w][e]
[f 2 1][bup 4 3 65535 65535 0 0][vp 1 0 0 69 0 0]Todo mundo que já me disse isso se foi sem me falar a parte mais importante.[n][w][e]
[f 2 1][bup 4 3 65535 65535 0 0][vp 1 0 0 70 0 0]Você viu como eu estava hoje... É só disso que eu sou capaz no momento.[n][w][e]
[f 2 1][bup 4 3 65535 65535 0 0][vp 1 0 0 71 0 0]Eu não cresci nada desde a infância. Ririam se me vissem agora.[n][w][e]

[sel SEL_051_0_0 top]
[f 2 1]Não é verdade.[e]
[f 2 1]Você é bem forte e atencioso.[e]
[f 2 1]Não dá para lutar de barriga vazia.[e]

[msg MSG_052_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 72 0 0][f 4 23 0 1 0 25 25]Talvez minha irmã dissesse isso, mas você sabe que nem todo mundo pegaria leve assim comigo.[n][w][e]

[msg MSG_053_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 1 65535 65535 0 0][vp 1 0 0 73 0 0][f 4 23 0 1 1 25 25]Heh. Fico feliz por você achar isso, mas ainda tenho muito o que aprender.[n][w][e]

[msg MSG_054_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 1 65535 65535 0 0][vp 1 0 0 74 0 0][f 4 23 0 1 1 25 25]É verdade. Doces aliviam a fadiga. Acho que vou estar pronto pra lutar mais amanhã.[n][w][e]

[msg MSG_055_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 75 0 0]Mas acabei de me tocar de uma coisa. Esse tempo todo, eu só tava fugindo, com a desculpa de estar ocupado demais com os meus problemas.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 76 0 0]Mas, de agora em diante, vou proteger tudo.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 77 0 0]Prometemos ficar fortes juntos... Eu não vou decepcioná-lo.[n][w][e]

[sel SEL_056_0_0 top]
[f 2 1]Sei que você consegue.[e]
[f 2 1]Eu vou ajudar como puder.[e]
[f 2 1]Boa sorte.[e]

[msg MSG_057_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 1 65535 65535 0 0][vp 1 0 0 78 0 0]Bem, se é isso que você pensa, não quero deixar você na mão.[n][w][e]

[msg MSG_058_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 1 65535 65535 0 0][vp 1 0 0 79 0 0]Valeu, eu agradeço mesmo. Vou contar contigo da próxima.[n][w][e]

[msg MSG_059_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 1 65535 65535 0 0][vp 1 0 0 80 0 0]Valeu. Tem muita gente dependendo de mim, então não posso deixar ninguém na mão.[n][w][e]

[msg MSG_060_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 1 65535 65535 0 0][vp 1 0 0 81 0 0]Heh, a ideia aqui era animar a turma, mas no final sou eu que estou recebendo o apoio.[n][w][e]
[f 2 1][bup 4 1 65535 65535 0 0][vp 1 0 0 82 0 0]Sabe, você é o tipo de pessoa que minha irmã admiraria.[n][w][e]

[msg MSG_061_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 83 0 0]Beleza, chega de falar do passado. Vamos limpar a área logo...[n][w][e]

[msg MSG_061_5_0 [Akihiko Sanada]]
[f 2 1][bup 4 5 65535 65535 0 0][vp 1 0 0 84 0 0]... Ngh.[n][w][e]

[sel SEL_062_0_0 top]
[f 2 1]O que foi?[e]
[f 2 1]Você se machucou?[e]

[msg MSG_063_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 85 0 0]Bom, voltando pra casa das compras, eu topei com aqueles sujeitos de novo.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 86 0 0]Tinha ainda mais deles, e um acabou acertando um golpe em cheio.[n][w][e]

[msg MSG_064_0_0 [Akihiko Sanada]]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 87 0 0]Mas não esquenta. Não fiz nada que fosse me encrencar com a polícia.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 88 0 0]Só deixei tentarem me socar até se cansarem e desistirem.[n][w][e]
[f 2 1][bup 4 0 65535 65535 0 0][vp 1 0 0 89 0 0]Pensei que fosse conseguir desviar de todos, mas, hã... acho que ainda tenho onde melhorar.[n][w][e]

[msg MND_065_0_0]
[f 2 1]Terminei a limpeza com Sanada[n]e voltei para o meu quarto...[n][w][e]
[f 2 1]Sinto que meu nível de [f 4 30 1 1 1 0] aumentou[n]depois de ver como Sanada é atencioso...[n][w][e]

