[msg MSG_000_0_0 [Sr. Ekoda]]
[f 2 1][bup 1082 0 65535 65535 0 0][vp 1 0 0 1 0 0][f 5 21 0 1001]Hmm? Yamagishi, o que você está fazendo diante da sala dos professores?[n][w][e]

[msg MSG_001_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 4 65535 65535 0 0][vp 1 0 0 2 0 0]Ah, bem... E-Eu quero começar um clube de tecnologia![n][w][e]

[msg MSG_002_0_0 [Sr. Ekoda]]
[f 2 1][bup 1082 0 65535 65535 0 0][vp 1 0 0 3 0 0][f 5 21 0 1001]Clube de teologia?[n][w][e]
[f 2 1][bup 1082 0 65535 65535 0 0][vp 1 0 0 4 0 0][f 5 21 0 1001]Desde quando você gosta de religião?[n][w][e]
[f 2 1][bup 1082 0 65535 65535 0 0][vp 1 0 0 5 0 0][f 5 21 0 1001]Era melhor você perguntar numa igreja.[n][w][e]

[msg MSG_003_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 4 65535 65535 0 0][vp 1 0 0 6 0 0]Hã, não é "teologia"... Um clube de tecnologia![n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 7 0 0][f 4 23 0 6 0 25 25]Tipo um clube sobre tecnologia e eletrônica![n][w][e]

[msg MSG_004_0_0 [Sr. Ekoda]]
[f 2 1][bup 1082 0 65535 65535 0 0][vp 1 0 0 8 0 0][f 5 21 0 1001]Você quer começar um clube agora?[n][w][e]
[f 2 1][bup 1082 0 65535 65535 0 0][vp 1 0 0 9 0 0][f 5 21 0 1001]Por que é sempre você, Yamagishi?[n][w][e]
[f 2 1][bup 1082 0 65535 65535 0 0][vp 1 0 0 10 0 0][f 5 21 0 1001]Olha, já estamos em março. Você não poderia esperar até abril?[n][w][e]

[msg MSG_005_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 4 65535 65535 0 0][vp 1 0 0 11 0 0]Hein? M-Mas eu queria muito começar o grupo agora![n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 12 0 0][f 4 23 0 6 0 25 25]Prometo que vou fazer todo o possível pra achar membros e tudo mais. Então, tenho permissão pra abrir o clube?[n][w][e]

[msg MSG_006_0_0 [Sr. Ekoda]]
[f 2 1][bup 1082 0 65535 65535 0 0][vp 1 0 0 13 0 0][f 5 21 0 1001]O quê? Você não tem nem membros ainda? Então não há nada o que discutir.[n][w][e]
[f 2 1][bup 1082 0 65535 65535 0 0][vp 1 0 0 14 0 0][f 5 21 0 1001]Não se pode abrir um clube com menos de cinco membros.[n][w][e]
[f 2 1][bup 1082 0 65535 65535 0 0][vp 1 0 0 15 0 0][f 5 21 0 1001]Agora, eu preciso ir.[n][w][e]

[msg MSG_007_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 16 0 0]E ele se foi...[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 17 0 0]Bem, agora parece que eu tenho que encontrar cinco pessoas.[n][w][e]

[msg MSG_008_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 18 0 0][nl]-chan, você gostaria de entrar para o meu clube de tecnologia?[n][w][e]

[sel SEL_009_0_0 top]
[f 2 1]Claro.[e]
[f 2 1]Vou pensar nisso.[e]

[msg MSG_010_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 19 0 0]Viva! Que bom ouvir isso![n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 20 0 0]Eu estava torcendo para você topar.[n][w][e]

[msg MSG_011_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 6 65535 65535 0 0][vp 1 0 0 21 0 0]Ah... Bem, acho que seria muito divertido ter um clube de tecnologia.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 22 0 0][f 4 23 0 6 0 25 25]Mas acho que eu acabo sempre arrastando você para coisas que só eu me interesso.[n][w][e]

[msg MSG_012_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0][vp 0 0 0 23 0 0]...[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 24 0 0]Sabe... Eu achava que era errado eu gostar de eletrônicos.[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 25 0 0]Nunca falei disso pra ninguém, porque sempre achei que era estranho uma garota gostar de eletrônica.[n][w][e]

[msg MSG_013_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 26 0 0]Mas você me aceita por quem eu sou, [nl]-chan.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 27 0 0]Por isso decidi ser forte e deixar todo mundo saber quem eu realmente sou.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 28 0 0]Mesmo se as pessoas me acharem estranha, sei que está tudo bem.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 29 0 0]Tenho você comigo, então não tenho nada a temer.[n][w][e]

[msg MSG_014_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 30 0 0]Agora quero conhecer mais pessoas como eu e interagir com elas.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 31 0 0]Já que eu escondia meu amor pela eletrônica, nunca tive amigos com o mesmo interesse.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 32 0 0]Por isso pensei em abrir um clube de tecnologia.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 33 0 0]Porque pode ter mais gente por aí que também curte essas coisas. E, se for o caso, quero ter um jeito de falar com elas.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 34 0 0]Mas admito que estou meio nervosa.[n][w][e]

[msg MSG_015_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 35 0 0]Mas não se preocupe. Não vou parar de frequentar o clube de arte.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 36 0 0]Vou acabar muito ocupada, mas quero insistir.[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 37 0 0][f 4 23 0 6 1 25 25]É que nem... pular do trampolim na piscina. Aquela sensação.[n][w][e]

[msg MSG_016_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 0 0 0 38 0 0]...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 39 0 0]Você também vai ficar no clube ano que vem, né, [nl]-chan?[n][w][e]

[sel SEL_017_0_0 top]
[f 2 1]Eu adoraria.[e]
[f 2 1]Não sei.[e]

[msg MSG_018_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 40 0 0]... Que bom ouvir isso.[n][w][e]

[msg MSG_019_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 41 0 0]É mesmo?[n][w][e]

[msg MSG_020_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 42 0 0]Ano que vem, quero estar nos mesmos clubes que você.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 43 0 0]Queria estar na mesma turma também.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 44 0 0]E adoraria te ver mais no dormitório...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 45 0 0]Acho que só quero estar mais com você em geral.[n][w][e]

[msg MSG_021_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 46 0 0]Ando dizendo bastante "mais", né?[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 47 0 0]Só fique sabendo que você pode dizer o que quiser para mim, tá?[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 48 0 0]Sei que não sou lá a pessoa mais de confiança...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 49 0 0][f 4 23 0 6 0 25 25]Mas quero te conhecer melhor.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 50 0 0]Quero ficar mais próxima de você.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 0 0 0 51 0 0]...[n][w][e]

[msg MSG_022_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 4 65535 65535 0 0][vp 1 0 0 52 0 0]Ah! T-Tenho que me adiantar e arrumar membros para o clube! E fazer cartazes de recrutamento, também.[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 53 0 0][f 4 23 0 6 1 25 25]B-Bem, até mais tarde![n][w][e]

[msg MSG_023_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 1 0][vp 1 0 0 54 0 0]Na próxima... talvez a gente possa conversar mais sobre isso no meu quarto?[n][w][e]
[f 2 1][bup 6 0 65535 65535 1 0][vp 0 0 0 55 0 0][f 4 23 0 6 0 25 25]...[n][w][e]
[f 2 1][bup 6 1 65535 65535 1 0][vp 1 0 0 56 0 0][f 4 23 0 6 1 25 25]Agora tenho que ir mesmo! Tchau![n][w][e]

[msg MSG_024_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 57 0 0]Só que você e a equipe me aceitaram por quem eu sou, [nl]-chan.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 58 0 0]Por isso decidi ser forte e deixar todo mundo ver quem eu realmente sou.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 59 0 0]Então, mesmo se as pessoas me acharem estranha, sei que está tudo bem.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 60 0 0]Não quero mais esconder.[n][w][e]

[msg MSG_025_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 61 0 0]Agora quero conhecer mais pessoas como eu e interagir com elas.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 62 0 0]Já que eu escondia meu amor pela eletrônica, nunca tive amigos com o mesmo interesse.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 63 0 0]Por isso pensei em abrir um clube de tecnologia.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 64 0 0]Porque pode ter mais gente por aí que também curte essas coisas. E, se for o caso, quero ter um jeito de falar com elas.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 65 0 0]Mas admito que estou meio nervosa.[n][w][e]

[msg MSG_026_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 66 0 0]Mas não se preocupe. Não vou parar de frequentar o clube de arte.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 67 0 0]Vou acabar muito ocupada, mas quero insistir.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 68 0 0]É que nem... pular do trampolim na piscina. Aquela sensação.[n][w][e]

[msg MSG_027_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 69 0 0]Enfim, tenho que achar membros para o clube![n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 70 0 0][f 4 23 0 6 0 25 25]Hmm.. Será que preciso fazer cartazes de recrutamento e coisas assim?[n][w][e]

[sel SEL_028_0_0 top]
[f 2 1]Você dá conta.[e]
[f 2 1]Precisa de ajuda?[e]

[msg MSG_029_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 71 0 0]Sim, obrigada.[n][w][e]

[msg MSG_030_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 72 0 0]Obrigada, mas... vou tentar sozinha primeiro.[n][w][e]

[msg MSG_031_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 73 0 0]Sinceramente, seria mentira se eu dissesse que não estou preocupada.[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 74 0 0]A gente logo vai pro terceiro ano.[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 75 0 0]Ou seja, todo mundo vai ter que começar a pensar no que vai fazer depois que se formar.[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 76 0 0]Inclusive, Iori-kun e Yukari-chan estavam conversando sobre o vestibular outro dia.[n][w][e]

[msg MSG_032_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 77 0 0]Mas, quer saber? Acho que vou ficar bem.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 78 0 0]Tenho todo mundo aqui para me apoiar, então não tenho nada a temer.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 0 0 0 79 0 0]...[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 80 0 0][f 4 23 0 6 3 25 25]Todo mundo?[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 81 0 0]Eu vivo dizendo isso, mas de quem estou falando?[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 82 0 0][f 4 23 0 6 0 25 25]Hã, desculpa, deixa pra lá.[n][w][e]

[msg MSG_084_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 4 65535 65535 0 0][vp 1 0 0 83 0 0]Ah, não percebi que era tão tarde! Tomara que as lojas ainda estejam abertas.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 84 0 0][f 4 23 0 6 0 25 25]Vejamos, preciso de papel... Ah, e tenho que achar uma sala para o clube também...[n][w][e]

[msg MSG_033_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 85 0 0]Acho que vai ser mais trabalho do que eu pensava![n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 86 0 0][f 4 23 0 6 0 25 25]Desculpa, [nl]-chan, preciso ir andando.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 87 0 0]Até mais tarde![n][w][e]

