[msg MSG_000_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 1 0 0]Desculpa, sei que você deve estar sem fome a essa hora.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 2 0 0]Mas, er, eu só quero que você prove, se não for incômodo![n][w][e]

[msg MND_001_0_0]
[f 2 1]...[n][w][e]
[f 2 1]A marmita tá[n]uma gororoba completa.[n][w][e]
[f 2 1]Acho que eu não tenho escolha a não ser comer.[n][w][e]

[msg MSG_002_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 3 0 0]Eu usei vinagre de base pra aliviar o cansaço e acrescentei um toque cítrico.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 4 0 0]Achei que seria melhor começar fazendo o simples.[n][w][e]

[msg MND_003_0_0]
[f 2 1]Tem um sabor muito... impactante.[n][w][e]

[msg MSG_004_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 5 0 0]Eu quero sua opinião sincera, tá? Q-Que tal?[n][w][e]

[sel SEL_005_0_0 top]
[f 2 1]...[e]
[f 2 1]Tá horrível.[e]
[f 2 1]Nada mau pra quem tá começando.[e]

[msg MSG_006_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 6 0 0]Er, hm...[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 7 0 0]Isso significa... ruim?[n][w][e]

[msg MSG_007_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 8 0 0]Ugh. Imaginei que você diria isso...[n][w][e]

[msg MSG_007_5_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0][vp 0 0 0 9 0 0]...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 10 0 0][f 4 23 0 6 0 25 25]M-Mas obrigada mesmo assim. Pela sinceridade.[n][w][e]

[msg MSG_008_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 11 0 0]S-Sério?[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 12 0 0][f 4 23 0 6 1 25 25]Por favor, me avisa se tiver alguma coisa que dê pra melhorar.[n][w][e]

[msg MSG_009_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 13 0 0]Você não parece muito bem, [nl]-chan...[n][w][e]

[msg MSG_009_5_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 4 65535 65535 0 0][vp 1 0 0 14 0 0]Ai, não! O que que eu fiz?![n][w][e]
[f 2 1][bup 6 4 65535 65535 0 0][vp 1 0 0 15 0 0]Er, vou buscar água. Não sai daqui![n][w][e]

[msg MSG_010_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 16 0 0]Desculpa ter feito você provar minha comida.[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 17 0 0]Imaginei que poderia contar com você pra ter uma opinião sincera.[n][w][e]

[msg MSG_010_5_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 18 0 0]Bom... Obrigada por hoje.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 19 0 0]Vou continuar tentando. Mas minha prioridade vai ser deixar comestível...[n][w][e]

[msg MND_011_0_0]
[f 2 1]Sinto que eu me aproximei um pouco da Fuuka.[n][w][e]

[msg MSG_012_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 20 0 0]A gente se vê no alojamento.[n][w][e]

[msg MND_013_0_0]
[f 2 1]Decidi voltar ao alojamento também...[n][w][e]

