[msg MSG_000_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 1 0 0]Então, tentei organizar meus pensamentos.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 2 0 0]Acho que não consegui expressar direito como eu me sentia porque estava tão confusa.[n][w][e]

[msg MSG_001_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 3 0 0]Já disse antes que tenho um mau hábito de pensar negativamente. Tipo quando não consigo decidir alguma coisa, por exemplo.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 4 0 0]Mas ninguém sabe como será o amanhã.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 5 0 0]Por mais que você se prepare, nunca sabe exatamente o que vai acontecer.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 6 0 0]Então, em situações assim, acho que a coisa mais importante é... acreditar.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 7 0 0]Você tem que pensar positivamente e confiar que o futuro vai sorrir pra você.[n][w][e]

[msg MSG_001_5_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 8 0 0]Só que eu não sei se consigo.[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 9 0 0]Não entendo como essa é uma atitude tão natural para todo mundo.[n][w][e]

[msg MSG_002_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 10 0 0]Como que você consegue se convencer de que as coisas darão certo no fim?[n][w][e]

[sel SEL_003_0_0 top]
[f 2 1]Eu acredito em mim mesma.[e]
[f 2 1]É só minha personalidade.[e]
[f 2 1]Nunca pensei nisso.[e]

[msg MSG_004_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 11 0 0][f 5 13 3 5 6]Ah, entendo.[n][w][e]

[msg MSG_004_5_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 12 0 0]Você é muito forte, [nl]-chan.[n][w][e]

[msg MSG_005_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 13 0 0][f 5 13 3 5 6]Parece que só é da sua natureza.[n][w][e]

[msg MSG_005_5_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 14 0 0]E você é muito forte, [nl]-chan.[n][w][e]

[msg MSG_006_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 15 0 0][f 5 13 3 5 6]Eu entendo.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 16 0 0]Você não tem que pensar nisso porque é uma reação natural sua.[n][w][e]

[msg MSG_007_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 17 0 0]Eu acho...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 18 0 0]Admiro muito essa parte de você, [nl]-chan.[n][w][e]

[msg MSG_008_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 19 0 0]Então, hã...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 20 0 0]Eu dependo tanto de você não porque você seja nossa líder.[n][w][e]
[f 2 1][bup 6 3 65535 65535 1 0][vp 1 0 0 21 0 0][f 4 23 0 6 3 25 25]É porque... você é você.[n][w][e]

[msg MSG_008_5_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 1 0][vp 1 0 0 22 0 0]Tem que ser você, [nl]-chan.[n][w][e]

[msg MND_009_0_0]
[f 2 1]Eu entendo as palavras sinceras da Fuuka.[n][w][e]
[f 2 1]Parece que nos aproximamos...[n][w][e]

[msg MSG_010_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 23 0 0]Sabe, às vezes eu penso comigo mesma.[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 24 0 0]Quando eu aprender a cozinhar e tiver retribuído sua ajuda...[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 25 0 0]A gente vai parar de passar tempo juntas assim?[n][w][e]

[sel SEL_011_0_0 top]
[f 2 1]Nem um pouco.[e]
[f 2 1]A gente se vê no dormitório.[e]

[msg MSG_012_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 26 0 0][f 5 13 3 5 6]... Obrigada.[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 27 0 0]Mas... com certeza tem muitas pessoas que confiam em você, né?[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 28 0 0]Não posso atrapalhar isso.[n][w][e]

[msg MSG_013_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 29 0 0]Desculpa! Não queria soar tão deprê.[n][w][e]

[msg MSG_014_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 30 0 0][f 5 13 3 5 6]Mas não seria a mesma coisa. Tem outras pessoas no dormitório...[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 31 0 0]E eu sei como todo mundo confia em você, [nl]-chan.[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 32 0 0]Não posso atrapalhar isso.[n][w][e]

[msg MSG_015_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 33 0 0]Desculpa! Não queria soar tão deprê.[n][w][e]

[msg MSG_016_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 34 0 0]Ah, olha só a hora. Era melhor a gente voltar.[n][w][e]

[msg MSG_016_5_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 35 0 0]Ei, você se incomoda se a gente fizer um desvio? Quero comprar ingredientes.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 36 0 0]Acho que vou cuidar do jantar do Koro-chan hoje.[n][w][e]

[msg MND_017_0_0]
[f 2 1]Fui às compras com Fuuka,[n]depois para casa.[n][w][e]

