[msg MSG_000_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 1 0 0]Hm... Por favor, não ria disso, tá bem?[n][w][e]

[msg MSG_001_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 2 0 0]Outro dia, deixei a Yukari-chan provar um novo prato que eu fiz.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 3 0 0]Ela gostou tanto que comeu tudinho.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 4 0 0]Então expliquei pra ela que era um jeito de retribuir a todo mundo pelo que fizeram por mim.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 5 0 0]Mas ela ficou muito confusa e me perguntou pelo que eu estava retribuindo às pessoas...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 6 0 0]Ela parecia não fazer a menor ideia do que eu estava falando, então contei a história toda.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 7 0 0]E, quando eu terminei... ela caiu na gargalhada.[n][w][e]

[msg MSG_002_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 8 0 0]Ela falou que eu não precisava retribuir nada, porque isso fazia parecer que não éramos amigas.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 9 0 0]E amigos não devem nada além de amizade uns aos outros.[n][w][e]

[sel SEL_003_0_0 top]
[f 2 1]Ela tem razão.[e]
[f 2 1]Ahaha! Que engraçado.[e]

[msg MSG_004_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 0 0 0 10 0 0]...[n][w][e]

[msg MSG_005_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 2 65535 65535 0 0][vp 1 0 0 11 0 0]Ei, que maldade. Eu pedi pra você não rir.[n][w][e]

[msg MSG_005_5_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 12 0 0]Sinceramente...[n][w][e]

[msg MSG_006_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 13 0 0]Eu menti esse tempo todo. Pra você e pra mim...[n][w][e]

[msg MSG_006_2_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 14 0 0]Não acho que era realmente uma questão de retribuir.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 15 0 0]Eu estou grata, mas... não era bem isso que eu queria dizer.[n][w][e]

[msg MSG_006_4_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 16 0 0]O que eu quero mesmo... é só estar com todo mundo. Pra sempre.[n][w][e]

[msg MSG_006_6_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 17 0 0]A verdade acabou sendo muito mais simples, e eu só queria deixar isso fácil.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 18 0 0]Eu nunca tive a confiança pra ser sincera sobre meus sentimentos.[n][w][e]

[msg MSG_006_8_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 19 0 0]Então quero pedir desculpas. Por arrastar você para essa mentira.[n][w][e]

[msg MSG_007_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 20 0 0]E...[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 21 0 0]Sei que não tenho direito de pedir, mas...[n][w][e]

[msg MSG_008_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 22 0 0]Queria que eu e você pudéssemos manter a amizade.[n][w][e]

[sel SEL_009_0_0 top]
[f 2 1]Claro.[e]
[f 2 1]Um brinde a nós.[e]

[msg MSG_010_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 0 0 0 23 0 0][f 5 13 3 5 6]...![n][w][e]

[msg MSG_010_5_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 24 0 0]Acho que isso nem precisava ser dito.[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 25 0 0]Mas, obrigada, mesmo assim.[n][w][e]

[msg MSG_011_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 0 0 0 26 0 0]...![n][w][e]

[msg MSG_011_5_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 27 0 0]Sim, um brinde a nós.[n][w][e]

[msg MSG_012_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 28 0 0]Acho que vou tentar aceitar melhor quem eu sou.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 29 0 0]E não vou mais me dizer que não tenho valor.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 30 0 0]Porque agora tenho amigos tão maravilhosos ao meu redor.[n][w][e]

[msg MND_013_0_0]
[f 2 1]Fuuka revelou seus sentimentos sinceros por mim.[n][w][e]
[f 2 1]Parece que nos aproximamos...[n][w][e]

[msg MSG_014_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 31 0 0]Talvez queira cozinhar comigo alguma hora, que tal?[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 32 0 0]Nunca perguntei porque achei que seria um desperdício do seu tempo, mas sempre quis cozinhar com amigos.[n][w][e]

[sel SEL_015_0_0 top]
[f 2 1]Com certeza.[e]
[f 2 1]Não sou muito boa nisso.[e]

[msg MSG_016_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 33 0 0][f 5 13 3 10 6]Que bom! Obrigada, [nl]-chan.[n][w][e]

[msg MSG_017_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 34 0 0]Não se preocupe, estarei do seu lado para ajudar![n][w][e]

[msg MSG_018_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 35 0 0]Ah, mas...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 36 0 0]Se você notar que estou fazendo alguma coisa errada, por favor me avise.[n][w][e]

[msg MSG_019_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 37 0 0]Hehe, mal posso esperar.[n][w][e]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 38 0 0]E, se fizermos um bom trabalho, seria legal compartilhar o que fizemos com todo mundo.[n][w][e]

[msg MND_020_0_0]
[f 2 1]Passei o dia conversando com Fuuka.[n][w][e]
[f 2 1]Eu deveria voltar para o dormitório...[n][w][e]

