[msg MSG_000_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 1 0 0]Hmm...[n][w][e]

[msg MSG_001_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 2 0 0]Eles não tinham lá muitos livros de receitas.[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 3 0 0]Desculpa, não sabia que a livraria praticamente só vende mangás.[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 4 0 0]Devia ter pesquisado antes.[n][w][e]

[msg MSG_002_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0][vp 0 0 0 5 0 0]...[n][w][e]

[sel SEL_003_0_0 top]
[f 2 1]O que foi?[e]
[f 2 1]Tem alguma coisa errada com isso?[e]

[msg MSG_004_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 6 0 0]Ah, hã...[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 7 0 0][f 4 23 0 6 0 25 25]Você se incomoda se a gente sentar?[n][w][e]

[msg MSG_005_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 8 0 0]Lembra o que eu te disse antes?[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 9 0 0]Comentei que não gosto muito de livrarias.[n][w][e]

[sel SEL_006_0_0 top]
[f 2 1]Aham, eu lembro.[e]
[f 2 1]Mas a gente acabou de sair de uma.[e]

[msg MSG_007_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 10 0 0]Bem, tem um motivo...[n][w][e]

[msg MSG_008_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 11 0 0]Tive uma experiência meio ruim numa livraria uma vez.[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 12 0 0]Acho que foi no começo de abril.[n][w][e]

[msg MSG_008_3_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 13 0 0]Alguém tirou uma foto minha.[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 14 0 0]Me acusaram de "roubar".[n][w][e]

[msg MSG_008_5_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 15 0 0]Não sou muito alta, né?[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 16 0 0]Então, quando me estiquei para alcançar uma prateleira alta, derrubei uns livros sem querer.[n][w][e]

[msg MSG_008_7_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 17 0 0]Bem, alguns deles caíram na minha bolsa. Fui tirar eles para colocar de volta na estante, mas...[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 18 0 0]Uma garota da minha turma tirou uma foto com o celular.[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 19 0 0]Até ameaçou de mostrar pros meus pais.[n][w][e]

[sel SEL_009_0_0 top]
[f 2 1]Você não fez nada de errado.[e]
[f 2 1]...[e]
[f 2 1]Que coisa horrível.[e]

[msg MSG_010_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 20 0 0]Né? Aposto que você me acha ridícula por deixar isso me aborrecer.[n][w][e]

[msg MSG_011_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 21 0 0]Aposto que você me acha ridícula por deixar isso me aborrecer.[n][w][e]

[msg MSG_012_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 22 0 0][f 5 13 3 5 6]Obrigada, [nl]-chan.[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 23 0 0]Mas você não me acha ridícula por deixar isso me aborrecer?[n][w][e]

[msg MSG_013_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 24 0 0]Se eu tivesse me defendido, poderia ter resolvido ali mesmo.[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 25 0 0]Eu sei disso.[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 26 0 0]Mas eu... não consegui falar nada mesmo assim.[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 27 0 0]Tinha um monte de pensamentos negativos passando na minha cabeça.[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 28 0 0]Achei que nada do que eu dissesse ajudaria no fim.[n][w][e]

[msg MSG_014_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 29 0 0]Mas, agora, quero acreditar que consigo mudar.[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 30 0 0]Sempre que estou com você, [nl]-chan, sinto que não fico presa nesses pensamentos negativos.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 31 0 0][f 4 23 0 6 0 25 25]Sei que isso é egoísmo meu, mas...[n][w][e]

[msg MSG_015_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 4 65535 65535 0 0][vp 1 0 0 32 0 0]D-Desculpa. Não sei o que estou dizendo.[n][w][e]
[f 2 1][bup 6 4 65535 65535 0 0][vp 1 0 0 33 0 0]Tô fazendo parecer até que estou só te usando, né?[n][w][e]

[msg MSG_015_5_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 4 65535 65535 0 0][vp 1 0 0 34 0 0]Não é o que eu quero dizer, sério![n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 35 0 0][f 4 23 0 6 0 25 25]O que eu estou tentando dizer é que...[n][w][e]

[msg MSG_016_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 36 0 0]Eu passei a confiar muito em você, [nl]-chan.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 37 0 0]E fico muito feliz em ter você me apoiando. Só isso.[n][w][e]

[msg MND_017_0_0]
[f 2 1]Fuuka expressou como se sente por mim.[n][w][e]
[f 2 1]Minha relação com ela está[n]ficando mais íntima.[n][w][e]

[msg MSG_018_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 38 0 0]Ah, hm, desculpa. Estou sempre tagarelando sobre meus problemas.[n][w][e]

[msg MSG_019_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 39 0 0]Nesse ritmo, nunca vou conseguir retribuir.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 40 0 0]Eu deveria ter conversado sobre minhas preocupações culinárias com todo mundo do alojamento, mas...[n][w][e]

[msg MSG_019_5_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 41 0 0]De alguma forma, eu sempre acabo procurando sua ajuda, [nl]-chan.[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 42 0 0]Quero ouvir sua opinião, mas, acima de tudo, me sinto mais tranquila quando estou com você.[n][w][e]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 43 0 0][f 4 23 0 6 3 25 25]Por que será?[n][w][e]

[msg MSG_020_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 0 0][vp 1 0 0 44 0 0]Só pode ser porque você é nossa líder. Por isso que conto tanto com você.[n][w][e]

[sel SEL_021_0_0 top]
[f 2 1]Esse é o único motivo?[f 2 9 1 1 342][e]
[f 2 1]Deve ser isso.[e]

[msg MSG_022_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 4 65535 65535 0 0][vp 0 0 0 45 0 0]Hã?[n][w][e]

[msg MSG_023_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 1 0][vp 1 0 0 46 0 0]A-Ah. Bem, talvez não seja a única razão.[n][w][e]
[f 2 1][bup 6 0 65535 65535 1 0][vp 0 0 0 47 0 0]...[n][w][e]

[msg MSG_024_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 3 65535 65535 1 0][vp 1 0 0 48 0 0]Desculpa, hã... Acho que preciso voltar ao alojamento.[n][w][e]
[f 2 1][bup 6 3 65535 65535 1 0][vp 1 0 0 49 0 0]Preciso de tempo para organizar meus pensamentos.[n][w][e]
[f 2 1][bup 6 3 65535 65535 1 0][vp 1 0 0 50 0 0]Podemos conversar sobre isso de novo mais tarde?[n][w][e]

[msg MSG_025_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 51 0 0]Obrigada. Vou voltar agora.[n][w][e]

[msg MSG_026_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 52 0 0]Ah, então é por isso?[n][w][e]
[f 2 1][bup 6 0 65535 65535 0 0][vp 1 0 0 53 0 0][f 4 23 0 6 0 25 25]Tenho uma tendência a pensar em círculos, o que me complica muito as coisas.[n][w][e]

[msg MSG_026_5_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 54 0 0][f 4 23 0 6 1 25 25]Mas vou cuidar de retribuir tudo que você fez por mim.[n][w][e]

[msg MSG_027_0_0 [Fuuka Yamagishi]]
[f 2 1][bup 6 1 65535 65535 0 0][vp 1 0 0 55 0 0]Tá, nos vemos de novo no alojamento.[n][w][e]

[msg MND_028_0_0]
[f 2 1]Fuuka foi embora.[n][w][e]
[f 2 1]Decidi voltar ao alojamento...[n][w][e]

