[msg MSG_000_0_0 [Autre fille]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 65535 0 0][uf 3 1 1 0 0 1 0 0]Je ne pensais pas que tu arriverais aussi tard.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 65535 0 0][uf 3 1 1 0 0 2 0 0]Mon nom est Mitsuru Kirijo. Je suis l'une des élèves de ce dortoir.[n][uf 1 1][e]

[msg MSG_001_0_0 [Première fille]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 51 65535 0 0][uf 3 1 1 0 0 3 0 0]C'est qui ?[n][uf 1 1][e]

[msg MSG_002_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 65535 0 0][uf 3 1 1 0 0 4 0 0]C'est une nouvelle élève. L'assigner ici a été une décision de dernière minute.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 65535 0 0][uf 3 1 1 0 0 5 0 0]À terme, elle déménagera dans le dortoir.[n][uf 1 1][e]

[msg MSG_003_0_0 [Première fille]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 51 65535 0 0][uf 3 1 1 0 0 6 0 0]Sa présence ne pose pas problème ?[n][uf 1 1][e]

[msg MSG_004_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 65535 0 0][uf 3 1 1 0 0 7 0 0]Je suppose que l'avenir nous le dira...[n][uf 1 1][e]

[msg MSG_005_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 65535 0 0][uf 3 1 1 0 0 8 0 0]Je te présente Yukari Takeba.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 65535 0 0][uf 3 1 1 0 0 9 0 0]Elle sera en deuxième année ce printemps, comme toi.[n][uf 1 1][e]

[msg MSG_006_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 51 65535 0 0][uf 3 1 1 0 0 10 0 0]Tu peux m'appeler Takeba.[n][uf 1 1][e]

[sel SEL_007_0_0 top]
[uf 0 5 65278][uf 2 1]Enchantée.[e]
[uf 0 5 65278][uf 2 1]Pourquoi tu as une arme ?[e]
[uf 0 5 65278][uf 2 1]C'est le dortoir des filles ?[e]

[msg MSG_008_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 51 65535 0 0][uf 3 1 1 0 0 11 0 0]Euh, ouais...[n][uf 1 1][e]

[msg MSG_009_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 51 65535 0 0][uf 3 1 1 0 0 12 0 0]Ravie de te rencontrer.[n][uf 1 1][e]

[msg MSG_010_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 51 65535 0 0][uf 3 1 1 0 0 13 0 0]Quoi ?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 51 65535 0 0][uf 3 1 1 0 0 14 0 0]Euh, ben, c'est genre, une passion...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 51 65535 0 0][uf 3 1 1 0 0 15 0 0]Enfin... Pas vraiment une passion, mais...[n][uf 1 1][e]

[msg MSG_011_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 65535 0 0][uf 3 1 1 0 0 16 0 0]On vit une époque dangereuse... C'est pour se défendre.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 65535 0 0][uf 3 1 1 0 0 17 0 0]Ce n'est pas une vraie arme à feu, bien entendu.[n][uf 1 1][e]

[msg MSG_012_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 51 65535 0 0][uf 3 1 1 0 0 18 0 0]Non, ça ne l'est pas, mais...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 51 65535 0 0][uf 3 1 1 0 0 19 0 0]Comment t'expliquer ?[n][uf 1 1][e]

[msg MSG_013_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 65535 0 0][uf 3 1 1 0 0 20 0 0]Il existe des dortoirs spécifiques aux garçons et aux filles, mais celui-ci est mixte. C'est un cas à part.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 65535 0 0][uf 3 1 1 0 0 21 0 0]Je t'expliquerai ça plus tard, quand j'aurai le temps.[n][uf 1 1][e]

[msg MSG_014_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 65535 0 0][uf 3 1 1 0 0 22 0 0]Il commence à se faire tard. Ta chambre se trouve au bout du couloir, au 1er étage.[n][uf 1 1][e]

[msg MSG_015_0_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 51 65535 0 0][uf 3 1 1 0 0 23 0 0]Tes affaires devraient déjà y être. Profites-en pour aller te reposer.[n][uf 1 1][e]

[msg MSG_016_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 51 65535 0 0][uf 3 1 1 0 0 24 0 0]Oh... Je vais t'accompagner. Suis-moi.[n][uf 1 1][e]

