[msg MSG_000_0_0 [Igor]]
[uf 0 5 65278][uf 2 1][uf 4 5 201 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]I've been waiting for you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 201 0 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]The time has come for you to wield your power.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 201 0 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]The tower that you are about to venture into... How did it come to be? For what purpose does it exist?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 201 0 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]Regrettably, you are not yet capable of answering these questions.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 201 0 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]That is why you must be made aware of something before you go any further.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 201 0 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]You must understand the nature of your power.[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]The nature of my power?[e]
[uf 0 5 65278][uf 2 1]About that door...[e]
[uf 0 5 65278][uf 2 1]I don't want to know.[e]

[msg MSG_002_0_0 [Igor]]
[uf 0 5 65278][uf 2 1][uf 4 5 201 0 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]The door you just passed through is the entrance to this realm. Of course, no one but you can see it.[n][uf 1 1][e]

[msg MSG_003_0_0 [Igor]]
[uf 0 5 65278][uf 2 1][uf 4 5 201 0 65535 65535 0 0][uf 3 1 1 0 0 8 0 0]Please, you must understand... It is of the utmost importance.[n][uf 1 1][e]

[msg MSG_004_0_0 [Igor]]
[uf 0 5 65278][uf 2 1][uf 4 5 201 0 65535 65535 0 0][uf 3 1 1 0 0 9 0 0]Your power is unique.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 201 0 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]It is like the number zero... Empty, but at the same time holding infinite possibilities.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 201 0 65535 65535 0 0][uf 3 1 1 0 0 11 0 0]You are able to possess multiple Personas and summon them at will.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 201 0 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]And when you have defeated your enemies, you will see the faces of possibility before you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 201 0 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]There may be times when they are difficult to grasp... But do not fear. Seize what you have earned.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 201 0 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]Your power will grow accordingly... Be sure to keep that in mind.[n][uf 1 1][e]

[msg MSG_005_0_0 [Igor]]
[uf 0 5 65278][uf 2 1][uf 4 5 201 0 65535 65535 0 0][uf 3 1 1 0 0 15 0 0]Now, then... My spare time will soon be scarce.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 201 0 65535 65535 0 0][uf 3 1 1 0 0 16 0 0]Next time, once again, may you open the door and come here of your own accord.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 201 0 65535 65535 0 0][uf 3 1 1 0 0 17 0 0]I'll tell you then about my true role... The manner in which I can best assist you.[n][uf 1 1][e]

[msg MSG_006_0_0 [Igor]]
[uf 0 5 65278][uf 2 1][uf 4 5 201 0 65535 65535 0 0][uf 3 1 1 0 0 18 0 0]Until we meet again... Farewell.[n][uf 1 1][e]

