[msg AST_DNG_TEST [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_DORMITORY_01 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 1028 0 0]¿Estarán bien Kirijo y los demás?[n][uf 1 2 80][e]

[msg AST_DNG_DORMITORY_02 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 1077 0 0]¿N-no irá a entrar por la ventana, verdad...?[n][uf 1 2 80][e]

[msg AST_DNG_DORMITORY_03 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 1056 0 0]Perdón, sé que es repentino y que estabas durmiendo... Luego te lo explico.[n][uf 1 2 120][e]

[msg AST_DNG_DORMITORY_04 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 1064 0 0]Espera, ¿estás intentando huir por la ventana? ¡No puedes hacer eso![n][uf 1 2 120][e]

[msg AST_DNG_DORMITORY_05 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_DORMITORY_06 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_DORMITORY_07 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_DORMITORY_08 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_DORMITORY_09 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_DORMITORY_10 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_TUTORIAL_01 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 1028 0 0]¿Cuán lejos podemos llegar sin perder contacto con Kirijo?[n][uf 1 2 120][e]

[msg AST_DNG_TUTORIAL_02 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 2004 0 0]¿Seguro que esto es el instituto? ¿No es coña?[n][uf 1 2 80][e]

[msg AST_DNG_TUTORIAL_03 [Junpei Iori]]
[uf 0 5 65278][uf 2 1]Sería gracioso que estuviéramos en nuestra clase ahora mismo, ¿eh?[n][uf 1 2 120][e]

[msg AST_DNG_TUTORIAL_04 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 2101 0 0]¡Hala! ¿Y se abren sin más? Joder, ¡me he asustado que flipas![n][uf 1 2 120][e]

[msg AST_DNG_TUTORIAL_05 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 10117 0 0]Cuentas con mi apoyo, pero ampliar tus conocimientos depende de ti.[n][uf 1 1][e]

[msg AST_DNG_TUTORIAL_06 [Junpei Iori]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_TUTORIAL_07 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 20507 0 0]Venga, sigamos explorando.[n][uf 1 1][e]

[msg AST_DNG_TUTORIAL_08 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1]Percibo enemigos cerca. Sigamos.[n][uf 1 1][e]

[msg AST_DNG_TUTORIAL_09 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_TUTORIAL_10 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_TUTORIAL_11 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_TUTORIAL_12 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_TUTORIAL_13 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_TUTORIAL_14 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_TUTORIAL_15 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_TUTORIAL_16 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_TUTORIAL_17 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_TUTORIAL_18 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_TUTORIAL_19 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_TUTORIAL_20 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_TUTORIAL_21 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_TUTORIAL_22 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_TUTORIAL_23 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_TUTORIAL_24 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_TUTORIAL_25 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_TUTORIAL_26 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_TUTORIAL_27 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_TUTORIAL_28 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_TUTORIAL_29 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_TUTORIAL_30 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_MONORAIL_01 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 20617 0 0]Oye, esa es la Tártaro, ¿no? Es bonita desde lejos, pero...[n][uf 1 1][e]

[msg AST_DNG_MONORAIL_02 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 20618 0 0]¡Hostia, estamos muy arriba! Creo que voy a vomitar.[n][uf 1 1][e]

[msg AST_DNG_MONORAIL_03 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 20619 0 0]Este sitio pone los pelos de punta.[n][uf 1 2 80][e]

[msg AST_DNG_MONORAIL_04 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 20620 0 0]Q-qué silencio...[n][uf 1 1][e]

[msg AST_DNG_MONORAIL_05 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 20621 0 0]¿Qué le pasa a Junpei? ¿Ha pasado algo?[n][uf 1 1][e]

[msg AST_DNG_MONORAIL_06 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 20622 0 0]¡Deprisa! ¡No nos queda mucho tiempo![n][uf 1 1][e]

[msg AST_DNG_MONORAIL_07 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 20623 0 0]S-si no paramos esta cosa, los pasajeros, no, ¡todos moriremos![n][uf 1 1][e]

[msg AST_DNG_MONORAIL_08 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 20624 0 0]¡Está acelerando...![n][uf 1 1][e]

[msg AST_DNG_MONORAIL_09 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 20625 0 0]¡Joder! ¡Tenemos que irnos ya![n][uf 1 1][e]

[msg AST_DNG_MONORAIL_10 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 2118 0 0]¡Venga, a por la grandullona![n][uf 1 2 80][e]

[msg AST_DNG_MONORAIL_11 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 1123 0 0]Oye, ¡no te vengas arriba! Nada de hacer tonterías.[n][uf 1 2 120][e]

[msg AST_DNG_MONORAIL_12 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 1006 0 0]¿Es esa que está ahí quieta? A mí me parece una sombra normal y corriente...[n][uf 1 2 120][e]

[msg AST_DNG_MONORAIL_13 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 1028 0 0]Junpei tampoco está en este coche.[n][uf 1 2 80][e]

[msg AST_DNG_MONORAIL_14 [Junpei Iori]]
[uf 0 5 65278][uf 2 1]Me da igual lo grande que sea... ¡Hasta aquí ha llegado![n][uf 1 1][e]

[msg AST_DNG_MONORAIL_15 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_MONORAIL_16 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_MONORAIL_17 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_MONORAIL_18 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_MONORAIL_19 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_MONORAIL_20 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_MONORAIL_21 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_MONORAIL_22 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_MONORAIL_23 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_MONORAIL_24 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_MONORAIL_25 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_MONORAIL_26 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_MONORAIL_27 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_MONORAIL_28 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_MONORAIL_29 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_MONORAIL_30 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_MONORAIL_31 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_MONORAIL_32 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_MONORAIL_33 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_MONORAIL_34 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_MONORAIL_35 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_MONORAIL_36 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_MONORAIL_37 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_MONORAIL_38 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_MONORAIL_39 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_MONORAIL_40 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_NIGHT_SCHOOL_01 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 20626 0 0]El instituto da miedo de noche... Venga, vamos a la sala de profesores.[n][uf 1 1][e]

[msg AST_DNG_NIGHT_SCHOOL_02 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 20627 0 0]Reunámonos con los demás en la entrada.[n][uf 1 1][e]

[msg AST_DNG_NIGHT_SCHOOL_03 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_NIGHT_SCHOOL_04 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_NIGHT_SCHOOL_05 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_NIGHT_SCHOOL_06 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_NIGHT_SCHOOL_07 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_NIGHT_SCHOOL_08 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_NIGHT_SCHOOL_09 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_NIGHT_SCHOOL_10 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_NIGHT_SCHOOL_11 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_NIGHT_SCHOOL_12 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_NIGHT_SCHOOL_13 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_NIGHT_SCHOOL_14 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_NIGHT_SCHOOL_15 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_NIGHT_SCHOOL_16 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_NIGHT_SCHOOL_17 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_NIGHT_SCHOOL_18 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_NIGHT_SCHOOL_19 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_NIGHT_SCHOOL_20 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_NIGHT_SCHOOL_21 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_NIGHT_SCHOOL_22 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_NIGHT_SCHOOL_23 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_NIGHT_SCHOOL_24 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_NIGHT_SCHOOL_25 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_NIGHT_SCHOOL_26 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_NIGHT_SCHOOL_27 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_NIGHT_SCHOOL_28 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_NIGHT_SCHOOL_29 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_NIGHT_SCHOOL_30 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_FUKA_RESCUE_01 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 10021 0 0]Akihiko y... no est... esta planta...[n][uf 1 1][e]

[msg AST_DNG_FUKA_RESCUE_02 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1]...[n][uf 1 2 80][uf 3 1 1 0 1 10022 0 0]¿Quién anda ahí...?[n][uf 1 1][e]

[msg AST_DNG_FUKA_RESCUE_03 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 10023 0 0]¿Eres... humano?[n][uf 1 1][e]

[msg AST_DNG_FUKA_RESCUE_04 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 10024 0 0]¿Me oy...? Respónd... por f....[n][uf 1 1][e]

[msg AST_DNG_FUKA_RESCUE_05 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 10025 0 0]¿Hay alguien ahí?[n][uf 1 1][e]

[msg AST_DNG_FUKA_RESCUE_06 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 10026 0 0]Respóndeme, por favor...[n][uf 1 1][e]

[msg AST_DNG_FUKA_RESCUE_07 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 10122 0 0]¿Cuál es tu... ubica...? Respon... de inme...[n][uf 1 1][e]

[msg AST_DNG_FUKA_RESCUE_08 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 10124 0 0]¿Dónde estoy? ¿Qué hago aquí?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 10125 0 0]Respóndeme, por favor...[n][uf 1 1][e]

[msg AST_DNG_FUKA_RESCUE_09 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_FUKA_RESCUE_10 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_FUKA_RESCUE_11 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_FUKA_RESCUE_12 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_FUKA_RESCUE_13 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_FUKA_RESCUE_14 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_FUKA_RESCUE_15 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_FUKA_RESCUE_16 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_FUKA_RESCUE_17 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_FUKA_RESCUE_18 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_FUKA_RESCUE_19 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_FUKA_RESCUE_20 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_FUKA_RESCUE_21 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_FUKA_RESCUE_22 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_FUKA_RESCUE_23 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_FUKA_RESCUE_24 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_FUKA_RESCUE_25 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_FUKA_RESCUE_26 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_FUKA_RESCUE_27 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_FUKA_RESCUE_28 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_FUKA_RESCUE_29 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_FUKA_RESCUE_30 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_THEURGIA_01 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 4131 0 0]Hacía mucho tiempo que no sentía esta tensión...[n][uf 1 2 80][e]

[msg AST_DNG_THEURGIA_02 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 3061 0 0]¿Crees podrás seguirle el ritmo después de tanto tiempo?[n][uf 1 2 80][e]

[msg AST_DNG_THEURGIA_03 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 4122 0 0]Créeme, no tengo intención de quedarme atrás.[n][uf 1 2 120][e]

[msg AST_DNG_THEURGIA_04 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 20563 0 0]¡Pues vamos![n][uf 1 1][e]

[msg AST_DNG_THEURGIA_05 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 20564 0 0]¿Ves alguna sombra? Deberían estar justo delante.[n][uf 1 1][e]

[msg AST_DNG_THEURGIA_06 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 20565 0 0]Sí. ¡Acabemos con ellas![n][uf 1 1][e]

[msg AST_DNG_THEURGIA_07 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 20566 0 0]¡Terminemos con esto![n][uf 1 1][e]

[msg AST_DNG_THEURGIA_08 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 20560 0 0]¡Te estás acercando a una sombra! ¡Prepárate para luchar![n][uf 1 1][e]

[msg AST_DNG_THEURGIA_09 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 10035 0 0]Subamos por las escaleras, [uf 4 1].[n][uf 1 1][e]

[msg AST_DNG_THEURGIA_10 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 5008 0 0]¡Quedan dos sombras![n][uf 1 2 80][e]

[msg AST_DNG_THEURGIA_11 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 4115 0 0]¡Ya llevamos la mitad! No bajes la guardia y acaba con ellas.[n][uf 1 2 120][e]

[msg AST_DNG_THEURGIA_12 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 5143 0 0]¡Solo queda una sombra! ¡Tú puedes![n][uf 1 2 120][e]

[msg AST_DNG_THEURGIA_13 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 4117 0 0]Es el último, ¡no os contengáis![n][uf 1 2 120][e]

[msg AST_DNG_THEURGIA_14 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_THEURGIA_15 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_THEURGIA_16 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_THEURGIA_17 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_THEURGIA_18 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_THEURGIA_19 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_THEURGIA_20 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_THEURGIA_21 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_THEURGIA_22 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_THEURGIA_23 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_THEURGIA_24 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_THEURGIA_25 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_THEURGIA_26 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_THEURGIA_27 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_THEURGIA_28 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_THEURGIA_29 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_THEURGIA_30 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_THEURGIA_31 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_THEURGIA_32 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_THEURGIA_33 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_THEURGIA_34 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_THEURGIA_35 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_THEURGIA_36 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_THEURGIA_37 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_THEURGIA_38 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_THEURGIA_39 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_THEURGIA_40 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_HOTEL_01 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 20628 0 0]¡Acabemos con esto ya![n][uf 1 1][e]

[msg AST_DNG_HOTEL_02 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 20629 0 0]¡Esta noche soy todo tuyo, pequeña![n][uf 1 1][e]

[msg AST_DNG_HOTEL_03 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 20630 0 0]¡Venga, vamos![n][uf 1 1][e]

[msg AST_DNG_HOTEL_04 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 20631 0 0]Acabemos con esto antes de que haga daño a alguien.[n][uf 1 1][e]

[msg AST_DNG_HOTEL_05 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 20632 0 0]En fin, ¿nos vamos?[n][uf 1 1][e]

[msg AST_DNG_HOTEL_06 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 20633 0 0]¡Mierda! Tengo que mejorar.[n][uf 1 1][e]

[msg AST_DNG_HOTEL_07 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 20634 0 0]Esta operación ha sido demasiado fácil.[n][uf 1 1][e]

[msg AST_DNG_HOTEL_08 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 20635 0 0]Supongo que aquí acaba la operación.[n][uf 1 1][e]

[msg AST_DNG_HOTEL_09 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 20636 0 0]Espera, ¡¿en serio?! ¡¿Dónde?![n][uf 1 1][e]

[msg AST_DNG_HOTEL_10 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 20637 0 0]¿Eh? ¿De qué estás hablando?[n][uf 1 1][e]

[msg AST_DNG_HOTEL_11 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 20638 0 0]Iré a echar un vistazo.[n][uf 1 1][e]

[msg AST_DNG_HOTEL_12 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 20639 0 0]Así que esto no ha acabado...[n][uf 1 1][e]

[msg AST_DNG_HOTEL_13 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 20640 0 0]¡Vamos...![n][uf 1 1][e]

[msg AST_DNG_HOTEL_14 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 20641 0 0]Al espejo le pasaba algo raro.[n][uf 1 1][e]

[msg AST_DNG_HOTEL_15 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 20642 0 0]No sé qué está pasando, pero solo hay que destruir los espejos, ¿no?[n][uf 1 1][e]

[msg AST_DNG_HOTEL_16 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 20643 0 0]Solo hay que destruir los espejos, ¿no? Pues venga, manos a la obra.[n][uf 1 1][e]

[msg AST_DNG_HOTEL_17 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 20644 0 0]Lo único que hay que hacer es romper los espejos, ¿correcto?[n][uf 1 1][e]

[msg AST_DNG_HOTEL_18 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 20645 0 0]He sentido algo raro al mirarme en el espejo.[n][uf 1 1][e]

[msg AST_DNG_HOTEL_19 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 20646 0 0]¿Que a los espejos les pasa algo? No me entero de nada.[n][uf 1 1][e]

[msg AST_DNG_HOTEL_20 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 20647 0 0]¿Eh? ¿Los espejos son diferentes? ¿En qué sentido?[n][uf 1 1][e]

[msg AST_DNG_HOTEL_21 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 20648 0 0]Quizá sea más fácil dar con las diferencias si los miramos de cerca.[n][uf 1 1][e]

[msg AST_DNG_HOTEL_22 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 20649 0 0]Hay que romper todos los espejos que no muestren nuestro reflejo.[n][uf 1 1][e]

[msg AST_DNG_HOTEL_23 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 20650 0 0]¿Y qué espejos hay que romper?[n][uf 1 1][e]

[msg AST_DNG_HOTEL_24 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 20651 0 0]Si un espejo no muestra nuestro reflejo, rompedlo.[n][uf 1 1][e]

[msg AST_DNG_HOTEL_25 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 20652 0 0]Recordad que hay que romper los espejos que no muestran nuestro reflejo.[n][uf 1 1][e]

[msg AST_DNG_HOTEL_26 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 20653 0 0]¡Venga, vamos![n][uf 1 1][e]

[msg AST_DNG_HOTEL_27 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 20654 0 0]¡Ahora sí que lo tengo controlado![n][uf 1 1][e]

[msg AST_DNG_HOTEL_28 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 20655 0 0]Ah... ¡Por fin! ¡Hora del espectáculo![n][uf 1 1][e]

[msg AST_DNG_HOTEL_29 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 20656 0 0]Ya es hora de acabar con esta operación.[n][uf 1 1][e]

[msg AST_DNG_HOTEL_30 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 1072 0 0]Oye, creo que antes vi una puerta enorme... ¿No deberíamos echarle un ojo?[n][uf 1 2 80][e]

[msg AST_DNG_HOTEL_31 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_HOTEL_32 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_HOTEL_33 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_HOTEL_34 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 1061 0 0]Al espejo de la habitación en la que estaba la sombra le pasaba algo raro...[n][uf 1 2 120][e]

[msg AST_DNG_HOTEL_35 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_HOTEL_36 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_HOTEL_37 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_HOTEL_38 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 1008 0 0]Vale, líder, tú decides los espejos que rompemos.[n][uf 1 2 120][e]

[msg AST_DNG_HOTEL_39 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_HOTEL_40 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_HOTEL_41 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_HOTEL_42 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_HOTEL_43 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_HOTEL_44 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_HOTEL_45 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_HOTEL_46 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_HOTEL_47 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_HOTEL_48 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_HOTEL_49 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_HOTEL_50 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_HOTEL_51 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_HOTEL_52 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_HOTEL_53 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_HOTEL_54 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_HOTEL_55 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_HOTEL_56 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_HOTEL_57 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_HOTEL_58 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_HOTEL_59 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_HOTEL_60 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_MILITARY_01 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 20657 0 0]Esos dos... No, déjalo para más tarde. Lo primero es la sombra.[n][uf 1 1][e]

[msg AST_DNG_MILITARY_02 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 20658 0 0]Uf, qué peste. Huele a queso podrido.[n][uf 1 1][e]

[msg AST_DNG_MILITARY_03 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 20659 0 0]No sabía que había más usuarios de Persona aparte de nosotros.[n][uf 1 1][e]

[msg AST_DNG_MILITARY_04 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 20660 0 0]Será mejor que tengamos cuidado con esos usuarios de Persona.[n][uf 1 1][e]

[msg AST_DNG_MILITARY_05 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 20661 0 0]Lucía no los ha percibido. Perdonad, me concentraré en la sombra.[n][uf 1 1][e]

[msg AST_DNG_MILITARY_06 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 20662 0 0]Parece que usaban estas instalaciones durante la guerra.[n][uf 1 1][e]

[msg AST_DNG_MILITARY_07 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 20663 0 0]¡Derrotemos a la sombra y salgamos de aquí![n][uf 1 1][e]

[msg AST_DNG_MILITARY_08 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 20664 0 0]¿Eh? ¿Por qué cojones hay huellas?[n][uf 1 1][e]

[msg AST_DNG_MILITARY_09 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 20665 0 0]Parecen recientes.[n][uf 1 1][e]

[msg AST_DNG_MILITARY_10 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 20666 0 0]No hay tiempo que perder. Acabemos con esto antes de que termine la Hora Oscura.[n][uf 1 1][e]

[msg AST_DNG_MILITARY_11 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 20667 0 0]Estas huellas son recientes.[n][uf 1 1][e]

[msg AST_DNG_MILITARY_12 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 10069 0 0]¡Puedo sentir al objetivo a dos secciones de ti![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 10070 0 0]Parece que se mueve despacio hacia abajo.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 10071 0 0]¡Que no escape![n][uf 1 1][e]

[msg AST_DNG_MILITARY_13 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 10072 0 0]Este lugar...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 10073 0 0]Parece que fue una especie de armería durante la guerra.[n][uf 1 1][e]

[msg AST_DNG_MILITARY_14 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 10078 0 0]¡El objetivo está ganando velocidad! Sigue bajando por el túnel.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 10079 0 0]¡Persíguelo, deprisa![n][uf 1 1][e]

[msg AST_DNG_MILITARY_15 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 10080 0 0]¡El objetivo se ha detenido![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 10081 0 0]Se ha dado la vuelta. ¡Nos está esperando más abajo![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 10082 0 0]¡Mucho cuidado![n][uf 1 1][e]

[msg AST_DNG_MILITARY_16 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_MILITARY_17 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_MILITARY_18 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_MILITARY_19 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_MILITARY_20 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_MILITARY_21 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_MILITARY_22 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_MILITARY_23 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_MILITARY_24 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_MILITARY_25 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_MILITARY_26 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_MILITARY_27 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_MILITARY_28 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_MILITARY_29 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_MILITARY_30 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_MILITARY_31 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_MILITARY_32 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_MILITARY_33 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_MILITARY_34 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_MILITARY_35 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_MILITARY_36 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_MILITARY_37 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_MILITARY_38 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_MILITARY_39 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_MILITARY_40 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_RESERVE_01 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 2091 0 0]¿Qué ha sido eso? ¿Se cree guay con esa actitud? Vaya tela...[n][uf 1 2 120][e]

[msg AST_DNG_RESERVE_02 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 7094 0 0]¿Cómo ha podido...?[n][uf 1 2 80][e]

[msg AST_DNG_RESERVE_03 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 1077 0 0]No sé qué pensar..., pero no nos sobra el tiempo. Continuemos.[n][uf 1 2 120][e]

[msg AST_DNG_RESERVE_04 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_RESERVE_05 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_RESERVE_06 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_RESERVE_07 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_RESERVE_08 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_RESERVE_09 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_RESERVE_10 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_RESERVE_11 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_RESERVE_12 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_RESERVE_13 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_RESERVE_14 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_RESERVE_15 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_RESERVE_16 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_RESERVE_17 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_RESERVE_18 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_RESERVE_19 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_RESERVE_20 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_RESERVE_21 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_RESERVE_22 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_RESERVE_23 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_RESERVE_24 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_RESERVE_25 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_RESERVE_26 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_RESERVE_27 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_RESERVE_28 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_RESERVE_29 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_RESERVE_30 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_GET_ITEM_YUKARI_ [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 1001 0 0]Anda, ¿has encontrado algo?[n][uf 1 2 80][e]

[msg AST_DNG_GET_ITEM_JUNPEI_ [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 2105 0 0]¡Genial! ¡Hemos encontrado algo![n][uf 1 2 120][e]

[msg AST_DNG_GET_ITEM_SANADA_ [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 3001 0 0]Oye, que se ha caído algo. Deberías quedártelo.[n][uf 1 2 80][e]

[msg AST_DNG_GET_ITEM_MITSU_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 4070 0 0]Parece que se ha caído algo. ¡Pues nos lo llevamos![n][uf 1 2 120][e]

[msg AST_DNG_GET_ITEM_FUKA_01 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 5006 0 0]Anda, ha salido algo. Igual puedes darle uso.[n][uf 1 2 120][e]

[msg AST_DNG_GET_ITEM_AEGIS_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 6001 0 0]Ha aparecido un objeto.[n][uf 1 2 80][e]

[msg AST_DNG_GET_ITEM_AMADA_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 7072 0 0]Anda, ha salido algo de ahí. Yo lo recojo.[n][uf 1 2 120][e]

[msg AST_DNG_GET_ITEM_KORO_01 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 8001 0 0]¡Guau, guau![n][uf 1 2 80][e]

[msg AST_DNG_GET_ITEM_ARAGAKI [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 9043 0 0]¿Lo pillas tú?[n][uf 1 2 120][e]

[msg AST_DNG_GET_ITEM_MITSU_0_2 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 4061 0 0]Del objeto que has roto ha salido algo. Deberías llevártelo por si las moscas.[n][uf 1 2 120][e]

[msg AST_DNG_GET_ITEM_FUKA_01_2 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 5066 0 0]Parece que Korocito ha recogido algo para ti.[n][uf 1 2 120][e]

[msg AST_DNG_GET_ITEM_YUKARI__2 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_GET_ITEM_JUNPEI__2 [Junpei Iori]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_GET_ITEM_SANADA__2 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_GET_ITEM_MITSU_0_3 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_GET_ITEM_FUKA_02 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_GET_ITEM_AEGIS_0_2 [Aigis]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_GET_ITEM_AMADA_0_2 [Ken Amada]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_GET_ITEM_KORO_02 [Koromaru]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_GET_ITEM_ARAGAKI_2 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_GET_ITEM_MITSU_0_4 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_GET_ITEM_FUKA_02_2 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_GET_ITEM_YUKARI__3 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_GET_ITEM_JUNPEI__3 [Junpei Iori]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_GET_ITEM_SANADA__3 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_GET_ITEM_MITSU_0_5 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_GET_ITEM_FUKA_03 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_GET_ITEM_AEGIS_0_3 [Aigis]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_GET_ITEM_AMADA_0_3 [Ken Amada]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_GET_ITEM_KORO_03 [Koromaru]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_GET_ITEM_ARAGAKI_3 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_GET_ITEM_MITSU_0_6 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_GET_ITEM_FUKA_03_2 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1]未使用[n][uf 1 1][e]

[msg AST_DNG_TBOX_STEAL_MITU_ [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 4092 0 0]Parece que es una de esas sombras que roban el contenido de los cofres del tesoro. Y va que se las pela...[n][uf 1 2 120][e]

[msg AST_DNG_TBOX_STEAL_MITU__2 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 4092 0 0]Ya se ha llevado el contenido de este cofre. Ojalá pudiésemos sacarle la delantera...[n][uf 1 2 120][e]

[msg AST_DNG_TBOX_STEAL_MITU__3 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 4092 0 0]Va a por los cofres del tesoro. A ver si puedes predecir su siguiente movimiento.[n][uf 1 2 120][e]

[msg AST_DNG_TBOX_STEAL_FUKA_ [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 5110 0 0]¡Esa sombra tiene el cofre del tesoro! Intenta interceptarla antes de que llegue a otro.[n][uf 1 2 120][e]

[msg AST_DNG_TBOX_STEAL_FUKA__2 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 5110 0 0]¡También se ha llevado el tesoro de este cofre! Busquemos otro...[n][uf 1 2 120][e]

[msg AST_DNG_TBOX_STEAL_FUKA__3 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 5101 0 0]¡La sombra va a por todos los cofres del tesoro! ¡Vamos a darle una sorpresita en el siguiente cofre![n][uf 1 2 120][e]

[msg AST_ACCIDENT_RBOX_MITU [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 5218 0 0]Parece que hay un cofre del tesoro poco común en esta planta, ¡a ver si lo encuentras![n][uf 1 2 120][e]

[msg AST_ACCIDENT_RBOX_MITU_2 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 4114 0 0]También percibo un cofre del tesoro poco común en esta planta. Qué maravilla.[n][uf 1 2 120][e]

[msg AST_ACCIDENT_MBOX_MITU [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 5220 0 0]Hay un cofre cerrado en esta planta. Si puedes, intenta hacerte con lo que hay dentro.[n][uf 1 1][e]

[msg AST_ACCIDENT_RENEMY_MITU [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 4086 0 0]Percibo una sombra rara. Búscala y acaba con ella.[n][uf 1 2 120][e]

[msg AST_ACCIDENT_ALLBAD_MITU [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 4098 0 0]Mmm... Las sombras de esta planta se comportan de forma inusual...[n][uf 1 2 120][e]

[msg AST_ACCIDENT_ALL_R_MITU [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 4086 0 0]En esta planta hay un montón de sombras raras. Menuda oportunidad de oro.[n][uf 1 2 120][e]

[msg AST_ACCIDENT_ALL_S_MITU [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 5256 0 0]Esta planta está repleta de sombras fortísimas... ¡Preparaos![n][uf 1 2 120][e]

[msg AST_ACCIDENT_DARK_MITU [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 5216 0 0]No tengo ni idea de lo que está pasando, así que ten más cuidado que de costumbre.[n][uf 1 2 120][e]

[msg AST_ACCIDENT_MDOOR_MITU [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 4061 0 0]Percibo una distorsión... Debe ser cosa de la puerta. Es peligrosa, pero podría merecer la pena explorarla.[n][uf 1 2 120][e]

[msg AST_ACCIDENT_RBOX_FUKA [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 5302 0 0]Percibo un valioso cofre del tesoro en esta planta. ¡Ve a por él![n][uf 1 2 120][e]

[msg AST_ACCIDENT_RBOX_FUKA_2 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 5086 0 0]Vaya, ¡hay un cofre del tesoro poco común también en esta planta! Qué suerte.[n][uf 1 2 120][e]

[msg AST_ACCIDENT_MBOX_FUKA [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 5302 0 0]¡Percibo un cofre del tesoro cerrado en esta planta! Deberías buscarlo.[n][uf 1 2 120][e]

[msg AST_ACCIDENT_RENEMY_FUKA [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 5087 0 0]Percibo una sombra rara. ¿Crees que podrás encontrarla?[n][uf 1 2 120][e]

[msg AST_ACCIDENT_ALLBAD_FUKA [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 5092 0 0]Los enemigos de esta planta actúan de forma extraña... Ten cuidado.[n][uf 1 2 120][e]

[msg AST_ACCIDENT_ALL_R_FUKA [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 5087 0 0]¡Hay un montón de sombras raras en esta planta! ¡Saquémosle partido a esta oportunidad![n][uf 1 2 120][e]

[msg AST_ACCIDENT_ALL_S_FUKA [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 5343 0 0]¡Percibo enemigos fuertes en toda la planta! ¡Ve con pies de plomo![n][uf 1 2 120][e]

[msg AST_ACCIDENT_DARK_FUKA [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 5103 0 0]Aún no sé lo que está pasando a tu alrededor... Ve con cuidado.[n][uf 1 2 120][e]

[msg AST_ACCIDENT_MDOOR_FUKA [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 5076 0 0]Anda, ¡detecto una lectura en esa puerta! Si vas a entrar, asegúrate de que estás totalmente preparada.[n][uf 1 2 120][e]

[msg AST_MONADO_BATTLE_END [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 3 0 65535 5143 0 0]¡Lo tenemos![n][uf 1 2 80][e]

[msg AST_DNG_GENERAL_02_007_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 5019 0 0]He encontrado las escaleras. ¿Subimos?[n][uf 1 1][e]

[msg AST_DNG_GENERAL_02_007_0_2 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 5020 0 0]¡Anda, las escaleras![n][uf 1 1][e]

[msg AST_DNG_GENERAL_02_007_0_3 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 5021 0 0]Podemos subir por las escaleras.[n][uf 1 1][e]

[msg AST_DNG_GENERAL_03_007_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 5093 0 0]¡Aquí están las escaleras![n][uf 1 1][e]

[msg AST_DNG_GENERAL_03_007_0_2 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 5094 0 0]Eh, ¡son las escaleras![n][uf 1 1][e]

[msg AST_DNG_GENERAL_03_007_0_3 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 5095 0 0]Subimos, ¿no? Pues deprisita.[n][uf 1 1][e]

[msg AST_DNG_GENERAL_04_007_0 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 5167 0 0]¿Vamos a subir las escaleras?[n][uf 1 1][e]

[msg AST_DNG_GENERAL_04_007_0_2 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 5168 0 0]Conque aquí estaban las escaleras.[n][uf 1 1][e]

[msg AST_DNG_GENERAL_04_007_0_3 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 5169 0 0]He encontrado las escaleras. ¿Quieres subir?[n][uf 1 1][e]

[msg AST_DNG_GENERAL_05_007_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 5237 0 0]Excelente, parece que podemos subir.[n][uf 1 1][e]

[msg AST_DNG_GENERAL_05_007_0_2 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 5238 0 0]Conque aquí estaban las escaleras...[n][uf 1 1][e]

[msg AST_DNG_GENERAL_05_007_0_3 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 5239 0 0]Hemos encontrado las escaleras. Vamos.[n][uf 1 1][e]

[msg AST_DNG_GENERAL_07_007_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 5440 0 0]Escaleras localizadas. Actualizando registros de datos.[n][uf 1 1][e]

[msg AST_DNG_GENERAL_07_007_0_2 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 5441 0 0]Unas escaleras. ¿Ascendemos?[n][uf 1 1][e]

[msg AST_DNG_GENERAL_07_007_0_3 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 5442 0 0]Anda, son las escaleras.[n][uf 1 1][e]

[msg AST_DNG_GENERAL_07_007_0_4 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 5443 0 0]Parece que podremos subir.[n][uf 1 1][e]

[msg AST_DNG_GENERAL_08_007_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 5557 0 0]Hemos encontrado las escaleras.[n][uf 1 1][e]

[msg AST_DNG_GENERAL_08_007_0_2 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 5558 0 0]Ya podemos subir.[n][uf 1 1][e]

[msg AST_DNG_GENERAL_08_007_0_3 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 5559 0 0]Ahora podremos subir.[n][uf 1 1][e]

[msg AST_DNG_GENERAL_09_007_0 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 5621 0 0]¡Guau![n][uf 1 1][e]

[msg AST_DNG_GENERAL_06_007_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 5330 0 0]Parece que Korocito ha encontrado las escaleras.[n][uf 1 1][e]

[msg AST_DNG_GENERAL_09_007_0_2 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 5599 0 0]¡Guau![n][uf 1 1][e]

[msg AST_DNG_GENERAL_06_007_0_2 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 5331 0 0]¡Ya podemos subir de planta! ¡Buen chico, Korocito![n][uf 1 1][e]

[msg AST_DNG_GENERAL_09_007_0_3 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 3592 0 0]¿Guau?[n][uf 1 1][e]

[msg AST_DNG_GENERAL_07_007_0_5 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 5527 0 0]Hemos encontrado las escaleras. Koromaru quiere saber cómo proceder.[n][uf 1 1][e]

[msg AST_DNG_GENERAL_07_007_0_6 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 5526 0 0]Koromaru ha localizado las escaleras. Pregunta que si vamos a subir.[n][uf 1 1][e]

[msg AST_DNG_GENERAL_10_007_0 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 5677 0 0]He encontrado unas escaleras. Hay que subir.[n][uf 1 1][e]

[msg AST_DNG_GENERAL_10_007_0_2 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 5678 0 0]Entonces..., ¿subimos?[n][uf 1 1][e]

[msg AST_DNG_GENERAL_10_007_0_3 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 5679 0 0]Nos conducirá a la siguiente planta.[n][uf 1 1][e]

[msg AST_DEFEAT_GK_MITU_00 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 20109 0 0]El enemigo ha sido derrotado. Bien hecho.[n][uf 1 2 120][e]

[msg AST_DEFEAT_GK_MITU_01 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 1 0 0 0]El camino hacia delante se ha abierto. ¡Sigue así![n][uf 1 1][e]

[msg AST_DEFEAT_GK_FUKA_00 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 20126 0 0]¡El enemigo ha sido derrotado! ¡Buen trabajo, equipo![n][uf 1 2 120][e]

[msg AST_DEFEAT_GK_FUKA_01 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 3 1 2 0 1 0 0 0]Ya podemos seguir. ¡Buena suerte y ve con ojo![n][uf 1 1][e]

