[msg MSG_000_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 1 65535 65535 0 0][uf 3 1 3 0 65535 11451 0 0][uf 5 13 9 5 109]Disfruto mucho hablando contigo, [uf 4 1]...[n][uf 1 1][e]

[msg MND_001_0_0]
[uf 0 5 65278][uf 2 1]Mi vínculo con Chihiro se estrecha a medida que paso tiempo con ella...[n][uf 1 1][e]

[msg MND_002_0_0]
[uf 0 5 65278][uf 2 1]Siento que nuestra relación se fortalecerá pronto.[n][uf 1 1][e]

[msg MND_003_0_0]
[uf 0 5 65278][uf 2 1]Es hora de irse del instituto.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]He decidido volver a la residencia.[n][uf 1 1][e]

