[msg MSG_000_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]So for lunch, I had a melon-pan, then a katsu sandwich...[n][uf 1 1][e]

[msg MSG_000_3_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]Then an age-pan, a kani-pan, a yakisoba-pan, apple strudel... another age-pan...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 1 65535 65535 0 0][uf 3 1 1 0 0 3 0 0][uf 4 23 0 116 1 25 25]But I gotta have my rice, too![n][uf 1 1][e]

[msg MSG_000_5_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 4 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]Argh... Urp! I... I think that might've been... too many carbs![n][uf 1 1][e]

[msg MSG_001_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]Today, a girl in my class asked me, "Who's that cute girl you went to Umiushi with?"[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 3 65535 65535 0 0][uf 3 1 1 0 0 6 0 0][uf 4 23 0 116 3 25 25]She wanted me to introduce you two so you could eat lunch together... without me.[n][uf 1 1][e]

[msg MSG_002_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 3 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]Girls always go for girls like you... or my little brother. I guess looks really are everything.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 1 0 0 8 0 0][uf 4 23 0 116 0 25 25]But once we're dead, we'll all just be bones. You can't tell a handsome skeleton from an ugly one.[n][uf 1 1][e]

[msg MSG_003_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 2 65535 65535 0 0][uf 3 1 1 0 0 9 0 0]Arrgh, not again! Why do my memories make me so damn hungry!?[n][uf 1 1][e]

[msg MSG_004_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]Hey, waiter! Another tonkatsu special![n][uf 1 1][e]

[msg MSG_005_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 1 0 0 11 0 0]While we wait for the food, let me share a little senryu poem I wrote.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 1 65535 65535 0 0][uf 3 1 1 0 0 12 0 0][uf 4 23 0 116 1 25 25]He who cuts you is no friend,[n]But he who katsu you,[n]Flavor until the end.[n][uf 1 1][e]

[msg MSG_006_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 5 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]Huh? Oh... Oogh... My... My stomach! Emergency![n][uf 1 1][e]

[msg MSG_007_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 3 65535 65535 0 1][uf 3 1 1 0 0 14 0 0]Whew... That was way too close. If that toilet was just a bit further away... Ohhhh, boy.[n][uf 1 1][e]

[sel SEL_008_0_0 top]
[uf 0 5 65278][uf 2 1]Did you eat too much?[e]
[uf 0 5 65278][uf 2 1]Are you feeling sick?[e]

[msg MSG_009_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 1 0 0 15 0 0]Hey, don't you know who I am? I'm the Gourmet King. I can handle way more than any average stomach.[n][uf 1 1][e]

[msg MSG_010_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 3 65535 65535 0 0][uf 3 1 1 0 0 16 0 0]In case you haven't noticed by now, I usually always have room for fried food.[n][uf 1 1][e]

[msg MSG_011_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 1 0 0 17 0 0][uf 5 13 19 15 116]No, I'm fine, no worries.[n][uf 1 1][e]

[msg MSG_012_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 1 65535 65535 0 0][uf 3 1 1 0 0 18 0 0]Everything's good and normal over here. Except for my weight, that is.[n][uf 1 1][e]

[msg MSG_013_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 4 65535 65535 0 0][uf 3 1 1 0 0 19 0 0]...Ah! The Gourmet King shouldn't say things like that. I didn't mean to be so crass![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 4 65535 65535 0 0][uf 3 1 1 0 0 20 0 0]I mean, who wants to talk about toilets while they're eating? Gah, I keep saying "toilet"! Sorry, sorry.[n][uf 1 1][e]

[msg MND_014_0_0]
[uf 0 5 65278][uf 2 1]I can tell Suemitsu's trying[n]to be considerate of me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like our relationship is stronger...[n][uf 1 1][e]

[msg MSG_015_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 1 65535 65535 0 0][uf 3 1 1 0 0 21 0 0]Okay, enough of that! Let's shovel that food down![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 1 65535 65535 0 0][uf 3 1 1 0 0 22 0 0]We have to eat every chance we get! Because once we're dead, all we'll be eating is dust![n][uf 1 1][e]

[msg MSG_015_3_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 1 65535 65535 0 0][uf 3 1 1 0 0 23 0 0]You know, just like my little brother![n][uf 1 1][e]

[msg MND_016_0_0]
[uf 0 5 65278][uf 2 1]After eating with Suemitsu,[n]I went back to the dorm.[n][uf 1 1][e]

